include::./index.adoc[]

[[v62-5-0]]
=== The First of John, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v62-5-1]]

^<<v62-5-1,1>>^ Everyone believing that Jesus is the Christ has been born from God, and everyone who loves the one that caused to be born loves him who has been born from that one.

[[v62-5-2]]

^<<v62-5-2,2>>^ By this we gain the knowledge that we are loving the children of God, when we are loving God and doing his commandments.

[[v62-5-3]]

^<<v62-5-3,3>>^ For this is what the love of God means, that we observe his commandments; and yet his commandments are not burdensome,

[[v62-5-4]]

^<<v62-5-4,4>>^ because everything that has been born from God conquers the world. And this is the conquest that has conquered the world, our faith.

[[v62-5-5]]

^<<v62-5-5,5>>^ Who is the one that conquers the world but he who has faith that Jesus is the Son of God?

[[v62-5-6]]

^<<v62-5-6,6>>^ This is he that came by means of water and blood, Jesus Christ; not with the water only, but with the water and with the blood. And the spirit is that which is bearing witness,^&#42;1^ because the spirit is the truth.

[NOTE]
====
. “Is bearing witness.” Gr., mar·ty·rounʹ; Lat., te·sti·fi·caʹtur.
====

[[v62-5-7]]

^<<v62-5-7,7>>^ For there are three witness bearers,^&#42;1^

[NOTE]
====
. After “witness bearers” אABVgSyh,p omit the words added in later Gr. mss and Vgc, namely: “in heaven, the Father, the Word and the holy spirit; and these three are one. (8) And there are three witness bearers on earth.”
====

[[v62-5-8]]

^<<v62-5-8,8>>^ the spirit and the water and the blood, and the three are in agreement.^&#42;1^

[NOTE]
====
. Lit., “the three [witness bearers] are into the one (thing).” Compare Joh 10:30 ftn. For a discussion of this vs, see App 6B.
====

[[v62-5-9]]

^<<v62-5-9,9>>^ If we receive the witness men give, the witness God gives is greater, because this is the witness God gives, the fact that he has borne witness concerning his Son.

[[v62-5-10]]

^<<v62-5-10,10>>^ The &#91;person&#93; putting his faith in the Son of God has the witness given in his own case.^&#42;1^ The &#91;person&#93; not having faith in God has made him a liar, because he has not put his faith in the witness given, which God as witness has given concerning his Son.

[NOTE]
====
. Or, “in himself.”
====

[[v62-5-11]]

^<<v62-5-11,11>>^ And this is the witness given, that God gave us everlasting life, and this life is in his Son.

[[v62-5-12]]

^<<v62-5-12,12>>^ He that has the Son has this life; he that does not have the Son of God does not have this life.

[[v62-5-13]]

^<<v62-5-13,13>>^ I write YOU these things that YOU may know that YOU have life everlasting, YOU who put YOUR faith in the name of the Son of God.

[[v62-5-14]]

^<<v62-5-14,14>>^ And this is the confidence^&#42;1^ that we have toward him, that, no matter what it is that we ask according to his will, he hears us.

[NOTE]
====
. Or, “this is the freeness of speech.”
====

[[v62-5-15]]

^<<v62-5-15,15>>^ Further, if we know he hears us respecting whatever we are asking, we know we are to have the things asked since we have asked them of him.

[[v62-5-16]]

^<<v62-5-16,16>>^ If anyone catches sight of his brother sinning a sin that does not incur death,^&#42;1^ he will^&#42;2^ ask, and he^&#42;3^ will give life to him, yes, to those not sinning so as to incur death. There is a sin that does incur death. It is concerning that sin that I do not tell him to make request.

[NOTE]
====
. Or, “a sin not to death.”
. Or, “must.”
. That is, God, according to context.
====

[[v62-5-17]]

^<<v62-5-17,17>>^ All unrighteousness is sin; and yet there is a sin that does not incur death.

[[v62-5-18]]

^<<v62-5-18,18>>^ We know that every &#91;person&#93; that has been born from God does not practice sin, but the One born from God^&#42;1^ watches him, and the wicked one does not fasten his hold on him.

[NOTE]
====
. “The One born from God,” that is, Jesus Christ the Son of God, as in vs 1; א, “the one born from God (keeps himself)”; Vg, “the generation of God (keeps him).”
====

[[v62-5-19]]

^<<v62-5-19,19>>^ We know we originate with God, but the whole world is lying in the &#91;power of the&#93; wicked one.

[[v62-5-20]]

^<<v62-5-20,20>>^ But we know that the Son of God has come, and he has given us intellectual capacity^&#42;1^ that we may gain the knowledge of the true one. And we are in union with the true one, by means of his Son Jesus Christ. This is the true God and life everlasting.

[NOTE]
====
. Lit., “mental perception.”
====

[[v62-5-21]]

^<<v62-5-21,21>>^ Little children, guard yourselves from idols.

'''

xref:062-1-john/062-1-john-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-john/063-2-john-001.adoc#v63-1-0[Próximo Capítulo &#62;]