include::./index.adoc[]

[[v62-3-0]]
=== The First of John, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v62-3-1]]

^<<v62-3-1,1>>^ See what sort of love the Father has given us, so that we should be called children of God; and such we are. That is why the world does not have a knowledge of us, because it has not come to know him.

[[v62-3-2]]

^<<v62-3-2,2>>^ Beloved ones, now we are children of God, but as yet it has not been made manifest what we shall be. We do know that whenever he^&#42;1^ is made manifest we shall be like him, because we shall see him just as he is.

[NOTE]
====
. Or, “it.”
====

[[v62-3-3]]

^<<v62-3-3,3>>^ And everyone who has this hope set upon him purifies himself just as that one is pure.

[[v62-3-4]]

^<<v62-3-4,4>>^ Everyone who practices^&#42;1^ sin is also practicing lawlessness, and so sin is lawlessness.

[NOTE]
====
. Lit., “Everyone doing.”
====

[[v62-3-5]]

^<<v62-3-5,5>>^ YOU know too that that one was made manifest to take away &#91;our&#93;^&#42;1^ sins, and there is no sin in him.

[NOTE]
====
. Lit., “the.”
====

[[v62-3-6]]

^<<v62-3-6,6>>^ Everyone remaining in union with him does not practice sin; no one that practices sin has either seen him or come to know him.

[[v62-3-7]]

^<<v62-3-7,7>>^ Little children, let no one mislead YOU; he who carries on righteousness is righteous, just as that one is righteous.

[[v62-3-8]]

^<<v62-3-8,8>>^ He who carries on sin originates with the Devil,^&#42;1^ because the Devil has been sinning from &#91;the&#93; beginning.^&#42;2^ For this purpose the Son of God was made manifest, namely, to break up the works of the Devil.

[NOTE]
====
. “The Devil.” Gr., tou Di·a·boʹlou; Lat., Di·aʹbo·lo; J17,​18,​22(Heb.), has·Sa·tanʹ.
. Or, “from when he began.”
====

[[v62-3-9]]

^<<v62-3-9,9>>^ Everyone who has been born^&#42;1^ from God does not carry on sin, because His &#91;reproductive&#93; seed remains in such one, and he cannot practice sin, because he has been born from God.

[NOTE]
====
. Lit., “having been generated.”
====

[[v62-3-10]]

^<<v62-3-10,10>>^ The children of God and the children of the Devil are evident by this fact: Everyone who does not carry on righteousness does not originate with God, neither does he who does not love his brother.

[[v62-3-11]]

^<<v62-3-11,11>>^ For this is the message which YOU have heard from &#91;the&#93; beginning,^&#42;1^ that we should have love for one another;

[NOTE]
====
. “From [the] beginning.” Gr., apʼ ar·khesʹ; Lat., ab i·niʹti·o; J17(Heb.), me·roʼshʹ.
====

[[v62-3-12]]

^<<v62-3-12,12>>^ not like Cain, who originated with the wicked one and slaughtered his brother. And for the sake of what did he slaughter him? Because his own works were wicked, but those of his brother &#91;were&#93; righteous.

[[v62-3-13]]

^<<v62-3-13,13>>^ Do not marvel, brothers, that the world hates YOU.

[[v62-3-14]]

^<<v62-3-14,14>>^ We know we have passed over from death to life, because we love the brothers. He who does not love remains in death.

[[v62-3-15]]

^<<v62-3-15,15>>^ Everyone who hates his brother is a manslayer, and YOU know that no manslayer has everlasting life remaining in him.

[[v62-3-16]]

^<<v62-3-16,16>>^ By this we have come to know love, because that one surrendered his soul^&#42;1^ for us; and we are under obligation to surrender &#91;our&#93; souls^&#42;2^ for &#91;our&#93;^&#42;3^ brothers.

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; Lat., aʹni·mam; J17,​18,​22(Heb.), naph·shohʹ, “his soul.” See App 4A.
. Or, “lives.”
. Lit., “the.”
====

[[v62-3-17]]

^<<v62-3-17,17>>^ But whoever has this world’s means for supporting life and beholds his brother having need and yet shuts the door of his tender compassions upon him, in what way does the love of God remain in him?

[[v62-3-18]]

^<<v62-3-18,18>>^ Little children, let us love, neither in word nor with the tongue, but in deed and truth.

[[v62-3-19]]

^<<v62-3-19,19>>^ By this we shall know that we originate with the truth, and we shall assure^&#42;1^ our hearts before him

[NOTE]
====
. Lit., “we shall persuade.”
====

[[v62-3-20]]

^<<v62-3-20,20>>^ as regards whatever our hearts may condemn us in, because God is greater than our hearts and knows all things.

[[v62-3-21]]

^<<v62-3-21,21>>^ Beloved ones, if &#91;our&#93; hearts do not condemn &#91;us&#93;, we have freeness of speech toward God;

[[v62-3-22]]

^<<v62-3-22,22>>^ and whatever we ask we receive from him, because we are observing his commandments and are doing the things that are pleasing in his eyes.

[[v62-3-23]]

^<<v62-3-23,23>>^ Indeed, this is his commandment, that we have faith in the name of his Son Jesus Christ and be loving one another, just as he gave us commandment.

[[v62-3-24]]

^<<v62-3-24,24>>^ Moreover, he who observes his commandments remains in union with him, and he in union with such one; and by this we gain the knowledge that he is remaining in union with us, owing to the spirit which he gave us.

'''

xref:062-1-john/062-1-john-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-john/062-1-john-004.adoc#v62-4-0[Próximo Capítulo &#62;]