include::./index.adoc[]

[[v62-4-0]]
=== The First of John, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v62-4-1]]

^<<v62-4-1,1>>^ Beloved ones, do not believe every inspired expression,^&#42;1^ but test the inspired expressions^&#42;2^ to see whether they originate with God, because many false prophets have gone forth into the world.

[NOTE]
====
. “Inspired expression.” Lit., “spirit.” Gr., pneuʹma·ti; Lat., spi·riʹtu·i; J17,​18,​22(Heb.), ruʹach.
. Or, “test the spirits.” Lit., “be you proving the spirits.”
====

[[v62-4-2]]

^<<v62-4-2,2>>^ YOU gain the knowledge of the inspired expression from God by this: Every inspired expression that confesses Jesus Christ as having come in the flesh originates with God,

[[v62-4-3]]

^<<v62-4-3,3>>^ but every inspired expression that does not confess Jesus does not originate with God. Furthermore, this is the antichrist’s &#91;inspired expression&#93; which YOU have heard was coming, and now it is already in the world.

[[v62-4-4]]

^<<v62-4-4,4>>^ YOU originate with God, little children, and YOU have conquered those &#91;persons&#93;, because he that is in union with YOU is greater than he that is in union with the world.

[[v62-4-5]]

^<<v62-4-5,5>>^ They originate with the world; that is why they speak &#91;what proceeds&#93; from the world and the world listens to them.

[[v62-4-6]]

^<<v62-4-6,6>>^ We originate with God. He that gains the knowledge of God listens to us; he that does not originate with God does not listen to us. This is how we take note of the inspired expression of truth and the inspired expression of error.

[[v62-4-7]]

^<<v62-4-7,7>>^ Beloved ones, let us continue loving one another, because love is from God, and everyone who loves has been born from God and gains the knowledge of God.

[[v62-4-8]]

^<<v62-4-8,8>>^ He that does not love has not come to know God, because God is love.

[[v62-4-9]]

^<<v62-4-9,9>>^ By this the love of God was made manifest in our case, because God sent forth his only-begotten^&#42;1^ Son into the world that we might gain life through him.

[NOTE]
====
. “Only-begotten.” Gr., mo·no·ge·neʹ; Lat., u·ni·geʹni·tum.
====

[[v62-4-10]]

^<<v62-4-10,10>>^ The love is in this respect, not that we have loved God, but that he loved us and sent forth his Son as a propitiatory sacrifice^&#42;1^ for our sins.

[NOTE]
====
. See 2:2 ftn.
====

[[v62-4-11]]

^<<v62-4-11,11>>^ Beloved ones, if this is how God loved us, then we are ourselves under obligation to love one another.

[[v62-4-12]]

^<<v62-4-12,12>>^ At no time has anyone beheld God. If we continue loving one another, God remains in us and his love is made perfect in us.

[[v62-4-13]]

^<<v62-4-13,13>>^ By this we gain the knowledge that we are remaining in union with him and he in union with us, because he has imparted his spirit to us.

[[v62-4-14]]

^<<v62-4-14,14>>^ In addition, we ourselves have beheld and are bearing witness that the Father has sent forth his Son as Savior of the world.

[[v62-4-15]]

^<<v62-4-15,15>>^ Whoever makes the confession that Jesus Christ^&#42;1^ is the Son of God, God remains in union with such one and he in union with God.

[NOTE]
====
. “Christ,” B; אAVgSyh omit.
====

[[v62-4-16]]

^<<v62-4-16,16>>^ And we ourselves have come to know and have believed the love that God has in our case.
God is love, and he that remains in love remains in union with God and God remains in union with him.

[[v62-4-17]]

^<<v62-4-17,17>>^ This is how love has been made perfect with us, that we may have freeness of speech^&#42;1^ in the day of judgment, because, just as that one is, so are we ourselves in this world.

[NOTE]
====
. “Freeness of speech.” Or, “boldness.” Lit., “outspokenness.”
====

[[v62-4-18]]

^<<v62-4-18,18>>^ There is no fear in love, but perfect love throws fear outside, because fear exercises a restraint.^&#42;1^ Indeed, he that is under fear has not been made perfect in love.

[NOTE]
====
. Or, “checking; correction; punishment.” Lit., “lopping off.” Gr., koʹla·sin. Compare Mt 25:46 where the same Gr. word occurs.
====

[[v62-4-19]]

^<<v62-4-19,19>>^ As for us, we love, because he first loved us.

[[v62-4-20]]

^<<v62-4-20,20>>^ If anyone makes the statement: “I love God,” and yet is hating his brother, he is a liar. For he who does not love his brother, whom he has seen, cannot be loving God, whom he has not seen.

[[v62-4-21]]

^<<v62-4-21,21>>^ And this commandment we have from him, that the one who loves God should be loving his brother also.

'''

xref:062-1-john/062-1-john-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-john/062-1-john-005.adoc#v62-5-0[Próximo Capítulo &#62;]