include::./index.adoc[]

[[v62-1-0]]
=== The First of John, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v62-1-1]]

^<<v62-1-1,1>>^ That which was from &#91;the&#93; beginning,^&#42;1^ which we have heard, which we have seen with our eyes, which we have viewed attentively and our hands felt, concerning the word of life,

[NOTE]
====
. See 3:11 ftn.
====

[[v62-1-2]]

^<<v62-1-2,2>>^ (yes, the life was made manifest, and we have seen and are bearing witness and reporting to YOU the everlasting life which was with the Father and was made manifest to us,)

[[v62-1-3]]

^<<v62-1-3,3>>^ that which we have seen and heard we are reporting also to YOU, that YOU too may be having a sharing with us. Furthermore, this sharing of ours is with the Father and with his Son Jesus Christ.

[[v62-1-4]]

^<<v62-1-4,4>>^ And so we are writing these things that our joy may be in full measure.^&#42;1^

[NOTE]
====
. Lit., “having been fulfilled.”
====

[[v62-1-5]]

^<<v62-1-5,5>>^ And this is the message which we have heard from him and are announcing to YOU, that God is light and there is no darkness at all in union with him.^&#42;1^

[NOTE]
====
. Or, “no darkness at all in him.”
====

[[v62-1-6]]

^<<v62-1-6,6>>^ If we make the statement:^&#42;1^ “We are having a sharing with him,” and yet we go on walking in the darkness, we are lying and are not practicing the truth.

[NOTE]
====
. Lit., “we should say.”
====

[[v62-1-7]]

^<<v62-1-7,7>>^ However, if we are walking in the light as he himself is in the light, we do have a sharing with one another, and the blood of Jesus his Son cleanses us from all sin.

[[v62-1-8]]

^<<v62-1-8,8>>^ If we make the statement: “We have no sin,” we are misleading^&#42;1^ ourselves and the truth is not in us.

[NOTE]
====
. Lit., “we are making to err.”
====

[[v62-1-9]]

^<<v62-1-9,9>>^ If we confess our sins, he is faithful and righteous so as to forgive us our sins and to cleanse us from all unrighteousness.

[[v62-1-10]]

^<<v62-1-10,10>>^ If we make the statement: “We have not sinned,” we are making him a liar, and his word is not in us.

'''

xref:061-2-peter/061-2-peter-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-john/062-1-john-002.adoc#v62-2-0[Próximo Capítulo &#62;]