include::./index.adoc[]

[[v28-10-0]]
=== Hosea, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-10-1]]

^<<v28-10-1,1>>^ “Israel is a degenerating^&#42;1^ vine. Fruit he keeps putting forth for himself. In proportion to the abundance of his fruit he has multiplied &#91;his&#93; altars. In proportion to the goodness of his land, they put up good pillars.

[NOTE]
====
. “Luxuriant; outspreading,” if derived from another Heb. verb of the same form.
====

[[v28-10-2]]

^<<v28-10-2,2>>^ Their heart has become hypocritical;^&#42;1^ now they will be found guilty.
“There is one who will break their altars; he will despoil their pillars.

[NOTE]
====
. Or, “smooth; slippery.”
====

[[v28-10-3]]

^<<v28-10-3,3>>^ For now they will say, ‘We have no king, for we have not feared Jehovah. And as regards the king, what will he do for us?’

[[v28-10-4]]

^<<v28-10-4,4>>^ “They speak words, making false oaths, concluding a covenant; and judgment has sprouted like a poisonous plant in the furrows of the open field.

[[v28-10-5]]

^<<v28-10-5,5>>^ For the calf &#91;idol&#93; of Beth-aʹven the residents of Sa·marʹi·a will get frightened; for over it its people will certainly mourn, as well as its foreign-god priests^&#42;1^ &#91;who&#93; used to be joyful over it, on account of its glory, because it will have gone into exile away from it.

[NOTE]
====
. “As well as its foreign-god priests.” Heb., u·khema·ravʹ, “Chemarim”; Vg, “temple keepers.”
====

[[v28-10-6]]

^<<v28-10-6,6>>^ Even it someone will bring to As·syrʹi·a itself as a gift to a great king.^&#42;1^ Shame is what Eʹphra·im himself will get, and Israel will be ashamed of its counsel.

[NOTE]
====
. Or, “King Jareb.” See 5:13 ftn.
====

[[v28-10-7]]

^<<v28-10-7,7>>^ Sa·marʹi·a &#91;and&#93; her king will certainly be silenced, like a snapped-off twig on the surface of waters.

[[v28-10-8]]

^<<v28-10-8,8>>^ And the high places of &#91;Beth-&#93;aʹven, the sin of Israel, will actually be annihilated. Thorns and thistles themselves will come up upon their altars. And people will in fact say to the mountains, ‘Cover us!’ and to the hills, ‘Fall over us!’

[[v28-10-9]]

^<<v28-10-9,9>>^ “From the days of Gibʹe·ah you have sinned, O Israel. There they stood still. In Gibʹe·ah war against the sons of unrighteousness did not get to overtake them.

[[v28-10-10]]

^<<v28-10-10,10>>^ When it is my craving I shall also discipline them. And against them peoples will certainly be gathered when there is a harnessing of them to their two errors.

[[v28-10-11]]

^<<v28-10-11,11>>^ “And Eʹphra·im was a trained heifer loving to thresh; and I, for my part, passed over her good-looking neck. I make &#91;someone&#93; ride Eʹphra·im. Judah plows; Jacob harrows for him.

[[v28-10-12]]

^<<v28-10-12,12>>^ Sow seed for yourselves in righteousness; reap in accord with loving-kindness. Till for yourselves arable land, when there is time for searching for Jehovah until he comes and gives instruction in righteousness to YOU.

[[v28-10-13]]

^<<v28-10-13,13>>^ “YOU people have plowed wickedness. Unrighteousness is what YOU have reaped. YOU have eaten the fruitage of deception, for you have trusted in your way, in the multitude of your mighty ones.

[[v28-10-14]]

^<<v28-10-14,14>>^ And an uproar has risen among your people, and your own fortified cities will all be despoiled, as with the despoiling by Shalʹman of the house of Arʹbel, in the day of battle &#91;when&#93; a mother herself was dashed to pieces alongside &#91;her&#93; own sons.

[[v28-10-15]]

^<<v28-10-15,15>>^ In this way one^&#42;1^ will certainly do to YOU people, O Bethʹel,^&#42;2^ because of YOUR extreme badness. In the dawn the king of Israel will positively have to be silenced.”

[NOTE]
====
. Or, “he,” MVg; LXX, “I”; Sy, “they.”
. “Bethel,” MSyVg; LXX, “house of Israel.”
====

'''

xref:028-hosea/028-hosea-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-hosea/028-hosea-011.adoc#v28-11-0[Próximo Capítulo &#62;]