include::./index.adoc[]

[[v28-14-0]]
=== Hosea, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-14-1]]

^<<v28-14-1,1>>^ “Do come back, O Israel, to Jehovah your God, for you have stumbled in your error.

[[v28-14-2]]

^<<v28-14-2,2>>^ Take with yourselves words and come back to Jehovah. Say to him, all YOU people, ‘May you pardon error; and accept what is good, and we will offer in return the young bulls of our lips.^&#42;1^

[NOTE]
====
. “The young bulls of our lips,” MVg; LXX, “the fruit of our lips.”
====

[[v28-14-3]]

^<<v28-14-3,3>>^ As·syrʹi·a itself will not save us. Upon horses we shall not ride. And no more shall we say: “O our God!” to the work of our hands, because it is by you that a fatherless boy is shown mercy.’

[[v28-14-4]]

^<<v28-14-4,4>>^ “I shall heal their unfaithfulness. I shall love them of &#91;my&#93; own free will, because my anger has turned back from him.

[[v28-14-5]]

^<<v28-14-5,5>>^ I shall become^&#42;1^ like the dew to Israel. He will blossom like the lily, and will strike his roots like Lebʹa·non.

[NOTE]
====
. Or, “I shall prove to be.” Compare Ex 3:14 ftn.
====

[[v28-14-6]]

^<<v28-14-6,6>>^ His twigs will go forth, and his dignity will become like that of the olive tree, and his fragrance will be like that of Lebʹa·non.

[[v28-14-7]]

^<<v28-14-7,7>>^ They will again be dwellers in his shadow. They will grow grain, and will bud like the vine. His memorial^&#42;1^ will be like the wine of Lebʹa·non.

[NOTE]
====
. “His memorial.” Or, “The mention of Him.” Heb., zikh·rohʹ.
====

[[v28-14-8]]

^<<v28-14-8,8>>^ “Eʹphra·im &#91;will say&#93;, ‘What do I have to do any longer with the idols?’^&#42;1^
“I myself shall certainly give an answer and I shall keep looking on him. I am like a luxuriant juniper tree. From me must fruit for you be found.”

[NOTE]
====
. Lit., “What to me yet to the idols?” A Heb. idiom; a repellent question to indicate objection to the idols. See App 7B.
====

[[v28-14-9]]

^<<v28-14-9,9>>^ Who is wise, that he may understand these things? Discreet, that he may know them? For the ways of Jehovah are upright, and the righteous are the ones who will walk in them; but the transgressors are the ones who will stumble in them.

'''

xref:028-hosea/028-hosea-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]