include::./index.adoc[]

[[v28-6-0]]
=== Hosea, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-6-1]]

^<<v28-6-1,1>>^ “Come, YOU people, and do let us return to Jehovah, for he himself has torn in pieces but he will heal us. He kept striking, but he will bind us up.

[[v28-6-2]]

^<<v28-6-2,2>>^ He will make us alive after two days. On the third day he will make us get up, and we shall live before him.

[[v28-6-3]]

^<<v28-6-3,3>>^ And we will know, we will pursue to know Jehovah. Like dawn, his going forth is firmly established. And he will come in like a pouring rain to us; like a spring rain that saturates &#91;the&#93; earth.”

[[v28-6-4]]

^<<v28-6-4,4>>^ “What shall I do to you, O Eʹphra·im? What shall I do to you, O Judah, when the loving-kindness^&#42;1^ of YOU people is like the morning clouds and like the dew that early goes away?

[NOTE]
====
. Or, “the loyal love.”
====

[[v28-6-5]]

^<<v28-6-5,5>>^ That is why I shall have to hew &#91;them&#93; by the prophets; I shall have to kill them by the sayings of my mouth. And the judgments upon you will be as the light that goes forth.

[[v28-6-6]]

^<<v28-6-6,6>>^ For in loving-kindness I have taken delight, and not in sacrifice; and in the knowledge of God^&#42;1^ rather than in whole burnt offerings.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

[[v28-6-7]]

^<<v28-6-7,7>>^ But they themselves, like earthling man,^&#42;1^ have overstepped &#91;the&#93; covenant. There is where they have dealt treacherously with me.

[NOTE]
====
. Or, “like Adam.” Heb., keʼa·dhamʹ.
====

[[v28-6-8]]

^<<v28-6-8,8>>^ Gilʹe·ad is a town of practicers of what is harmful; their footprints are blood.

[[v28-6-9]]

^<<v28-6-9,9>>^ And as in the lying in wait for a man,^&#42;1^ the association of priests are marauding bands. By the wayside they commit murder at Sheʹchem, because they have carried on nothing but loose conduct.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v28-6-10]]

^<<v28-6-10,10>>^ In the house of Israel I have seen a horrible thing. There there is fornication on the part of Eʹphra·im. Israel has defiled itself.

[[v28-6-11]]

^<<v28-6-11,11>>^ Furthermore, O Judah, a harvest has been fixed for you, when I gather back the captive ones of my people.”

'''

xref:028-hosea/028-hosea-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-hosea/028-hosea-007.adoc#v28-7-0[Próximo Capítulo &#62;]