include::./index.adoc[]

[[v28-11-0]]
=== Hosea, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-11-1]]

^<<v28-11-1,1>>^ “When Israel was a boy,^&#42;1^ then I loved him, and out of Egypt I called my son.

[NOTE]
====
. Or, “lad; young man.”
====

[[v28-11-2]]

^<<v28-11-2,2>>^ “They^&#42;1^ called them. To that same extent they went away from before them.^&#42;2^ To the Baʹal images^&#42;3^ they took up sacrificing, and to the graven images they began making sacrificial smoke.

[NOTE]
====
. “They,” MSyVg; LXX, “I.”
. “From before them (from their faces),” MTVg; LXXSy, “from my face.”
. Or, “To the Baals.” Heb., lab·Beʽa·limʹ; Gr., Ba·a·limʹ; Lat., Baʹa·lim.
====

[[v28-11-3]]

^<<v28-11-3,3>>^ But as for me, I taught Eʹphra·im to walk, taking them upon &#91;my&#93;^&#42;1^ arms; and they did not recognize that I had healed them.

[NOTE]
====
. “My,” in agreement with LXXSyVg; M, “his,” or, “one’s.”
====

[[v28-11-4]]

^<<v28-11-4,4>>^ With the ropes of earthling man^&#42;1^ I kept drawing them, with the cords of love, so that I became to them as those lifting off a yoke on their jaws, and gently I brought food to &#91;each&#93; one.

[NOTE]
====
. Or, “man.” Heb., ʼa·dhamʹ.
====

[[v28-11-5]]

^<<v28-11-5,5>>^ He will not return to the land of Egypt, but As·syrʹi·a will be his king, because they refused to return.

[[v28-11-6]]

^<<v28-11-6,6>>^ And a sword will certainly whirl about in his cities and make an end of his bars and devour because of their counsels.

[[v28-11-7]]

^<<v28-11-7,7>>^ And my people are tending toward unfaithfulness to me. And upward^&#42;1^ they call it;^&#42;2^ no one at all does any rising up.^&#42;3^

[NOTE]
====
. See 7:16 ftn.
. In M both “it” and “people” are masc.
. Or, “does any exalting.” Compare Ex 15:2; Ps 145:1, where the same Heb. verb occurs. In reality no one was exalting God.
====

[[v28-11-8]]

^<<v28-11-8,8>>^ “How can I give you up, O Eʹphra·im? &#91;How&#93; can I deliver you up, O Israel? How can I set you as Adʹmah? &#91;How&#93; can I place you like Ze·boiʹim? My heart has changed within me; at the same time my compassions have grown hot.

[[v28-11-9]]

^<<v28-11-9,9>>^ I shall not express my burning anger. I shall not bring Eʹphra·im to ruin again, for I am God^&#42;1^ and not man,^&#42;2^ the Holy One in the midst of you; and I shall not come in excitement.

[NOTE]
====
. “God.” Heb., ʼEl; Lat., Deʹus.
. “Man.” Heb., ʼish; Gr., anʹthro·pos; Lat., hoʹmo.
====

[[v28-11-10]]

^<<v28-11-10,10>>^ After Jehovah they will walk. Like a lion he will roar; for he himself will roar, and sons will come trembling from the west.

[[v28-11-11]]

^<<v28-11-11,11>>^ Like a bird they will come trembling out of Egypt, and like a dove out of the land of As·syrʹi·a; and I shall certainly make them dwell in their houses,” is the utterance of Jehovah.

[[v28-11-12]]

^<<v28-11-12,12>>^ “With lying, Eʹphra·im has surrounded me, and with deception the house of Israel. But Judah is yet roaming with God,^&#42;1^ and with the Most Holy One^&#42;2^ he is trustworthy.”^&#42;3^

[NOTE]
====
. “God.” Heb., ʼEl.
. “The Most Holy One.” Heb., Qedhoh·shimʹ, pl. of qa·dhohshʹ, “holy”; pl. to denote excellence according to GK, § 124 h. Compare Pr 9:10 and Pr 30:3 ftns.
. Or, “even with the Most Holy One, who is trustworthy.”
====

'''

xref:028-hosea/028-hosea-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-hosea/028-hosea-012.adoc#v28-12-0[Próximo Capítulo &#62;]