include::./index.adoc[]

[[v28-2-0]]
=== Hosea, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-2-1]]

^<<v28-2-1,1>>^ “SAY to YOUR brothers, ‘My people!’^&#42;1^ and to YOUR sisters, ‘O woman shown mercy!’^&#42;2^

[NOTE]
====
. “My people!” Heb., ʽam·miʹ.
. Lit., “She has been shown mercy.” Heb., ru·chaʹmah.
====

[[v28-2-2]]

^<<v28-2-2,2>>^ Carry on a legal case with YOUR mother; carry on a legal case, for she is not my wife^&#42;1^ and I am not her husband.^&#42;2^ And she should put away her fornication from before herself and her acts of adultery from between her breasts,

[NOTE]
====
. Or, “my woman.” Heb., ʼish·tiʹ.
. Or, “her man.” Heb., ʼi·shahʹ.
====

[[v28-2-3]]

^<<v28-2-3,3>>^ that I may not strip her naked and actually place her as in the day of her being born, and actually set her like a wilderness and place her like a waterless land and put her to death with thirst.

[[v28-2-4]]

^<<v28-2-4,4>>^ And to her sons I shall not show mercy, for they are the sons of fornication.

[[v28-2-5]]

^<<v28-2-5,5>>^ For their mother has committed fornication. She that was pregnant with them has acted shamefully, for she has said, ‘I want to go after those passionately loving me, those giving my bread and my water, my wool and my linen, my oil and my drink.’

[[v28-2-6]]

^<<v28-2-6,6>>^ “Therefore here I am hedging your way about with thorns; and I will heap up a stone wall against her, so that her own roadways she will not find.

[[v28-2-7]]

^<<v28-2-7,7>>^ And she will actually chase after her passionate lovers, but she will not overtake them; and she will certainly look for them, but she will not find &#91;them&#93;. And she will have to say, ‘I want to go and return to my husband, the first one, for I had it better at that time than now.’

[[v28-2-8]]

^<<v28-2-8,8>>^ But she herself did not recognize that it was I who had given to her the grain and the sweet wine and the oil, and that I had made silver itself abound for her, and gold, &#91;which&#93; they made use of for Baʹal.^&#42;1^

[NOTE]
====
. Or, “they made into a Baal [image].”
====

[[v28-2-9]]

^<<v28-2-9,9>>^ “‘Therefore I shall turn back and certainly take away my grain in its time and my sweet wine in its season, and I will snatch away my wool and my linen for covering her nakedness.

[[v28-2-10]]

^<<v28-2-10,10>>^ And now I shall uncover her private parts to the eyes of her passionate lovers, and there will be no man^&#42;1^ to snatch her out of my hand.

[NOTE]
====
. “And . . . man.” Heb., weʼishʹ.
====

[[v28-2-11]]

^<<v28-2-11,11>>^ And I shall certainly cause all her exultation, her festival, her new moon and her sabbath and her every festal season to cease.

[[v28-2-12]]

^<<v28-2-12,12>>^ And I will lay desolate her vine and her fig tree, of which she has said: “They are a gift to me, which my passionate lovers have given to me”; and I will set them as a forest, and the wild beast of the field will certainly devour them.

[[v28-2-13]]

^<<v28-2-13,13>>^ And I will hold an accounting against her for the days of the Baʹal images^&#42;1^ to which she kept making sacrificial smoke, when she kept decking herself with her ring and her ornament and kept going after her passionate lovers, and I was the one that she forgot,’ is the utterance of Jehovah.

[NOTE]
====
. Or, “the Baals.” Heb., hab·Beʽa·limʹ; Gr., Ba·a·limʹ; Lat., Baʹa·lim.
====

[[v28-2-14]]

^<<v28-2-14,14>>^ “‘Therefore here I am prevailing upon her, and I will cause her to go into the wilderness, and I will speak to her heart.

[[v28-2-15]]

^<<v28-2-15,15>>^ And I will give her her vineyards from then onward, and the low plain^&#42;1^ of Aʹchor^&#42;2^ as an entrance to hope; and she will certainly answer there as in the days of her youth and as in the day of her coming up out of the land of Egypt.

[NOTE]
====
. Or, “valley.”
. Meaning “Ostracism; Trouble.”
====

[[v28-2-16]]

^<<v28-2-16,16>>^ And it must occur in that day,’ is the utterance of Jehovah, ‘that you will call &#91;me&#93; My husband,^&#42;1^ and you will no longer call me My owner.’^&#42;2^

[NOTE]
====
. Or, “My man.” Heb., ʼi·shiʹ.
. Or, “My baal.” Heb., baʽ·liʹ.
====

[[v28-2-17]]

^<<v28-2-17,17>>^ “‘And I will remove the names of the Baʹal images from her mouth, and they will no longer be remembered^&#42;1^ by their name.

[NOTE]
====
. Or, “mentioned.”
====

[[v28-2-18]]

^<<v28-2-18,18>>^ And for them I shall certainly conclude a covenant in that day in connection with the wild beast of the field and with the flying creature of the heavens and the creeping thing of the ground, and the bow and the sword and war I shall break out of the land, and I will make them lie down in security.

[[v28-2-19]]

^<<v28-2-19,19>>^ And I will engage you to me for time indefinite, and I will engage you to me in righteousness and in justice and in loving-kindness^&#42;1^ and in mercies.

[NOTE]
====
. Or, “and in loyal love.” Heb., u·vecheʹsedh.
====

[[v28-2-20]]

^<<v28-2-20,20>>^ And I will engage you to me in faithfulness; and you will certainly know Jehovah.’^&#42;1^

[NOTE]
====
. “Know Jehovah,” MLXXSy; Vg and about 45 Heb. mss, “know that I am Jehovah.”
====

[[v28-2-21]]

^<<v28-2-21,21>>^ “‘And it must occur in that day that I shall answer,’ is the utterance of Jehovah, ‘I shall answer the heavens, and they, for their part, will answer the earth;

[[v28-2-22]]

^<<v28-2-22,22>>^ and the earth, for its part, will answer the grain and the sweet wine and the oil; and they, for their part, will answer Jezʹre·el &#91;‘God will sow seed’&#93;.

[[v28-2-23]]

^<<v28-2-23,23>>^ And I shall certainly sow her like seed for me in the earth, and I will show mercy to her who was not shown mercy,^&#42;1^ and I will say to those not my people:^&#42;2^ “You are my people”; and they, for their part,^&#42;3^ will say: “&#91;You are&#93; my God.”’”^&#42;4^

[NOTE]
====
. “Her who was not shown mercy.” Heb., loʼ ru·chaʹmah. See 1:6 ftn, “Lo-ruhamah.”
. Or, “to the one not my people.” Heb., leloʼ-ʽam·miʹ. See 1:9 ftn, “Lo-ammi.”
. Lit., “it itself,” referring to “people,” masc. sing.
. “My God.” Heb., ʼElo·haiʹ.
====

'''

xref:028-hosea/028-hosea-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-hosea/028-hosea-003.adoc#v28-3-0[Próximo Capítulo &#62;]