include::./index.adoc[]

[[v28-12-0]]
=== Hosea, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-12-1]]

^<<v28-12-1,1>>^ “Eʹphra·im is feeding on wind^&#42;1^ and chasing after the east wind all day long. Lying and despoiling are what he multiplies. And a covenant with As·syrʹi·a they conclude, and to Egypt oil itself is brought.

[NOTE]
====
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v28-12-2]]

^<<v28-12-2,2>>^ “And Jehovah has a legal case with Judah, even to hold an accounting against Jacob according to his ways; according to his dealings he will repay him.

[[v28-12-3]]

^<<v28-12-3,3>>^ In the belly he seized his brother by the heel,^&#42;1^ and with his dynamic energy he contended with God.^&#42;2^

[NOTE]
====
. Or, “he supplanted his brother.”
. “God.” Heb., ʼElo·himʹ.
====

[[v28-12-4]]

^<<v28-12-4,4>>^ And he kept contending with an angel and gradually prevailed. He wept, that he might implore favor for himself.”
At Bethʹel He got to find him, and there He began talking with us.^&#42;1^

[NOTE]
====
. “Us,” MTVg; LXXSy, “him.”
====

[[v28-12-5]]

^<<v28-12-5,5>>^ And Jehovah the God of the armies,^&#42;1^ Jehovah is his memorial.

[NOTE]
====
. “The God of the armies,” MVg; LXX, “the God almighty.”
====

[[v28-12-6]]

^<<v28-12-6,6>>^ “And as respects you, to your God you should return, keeping loving-kindness^&#42;1^ and justice; and let there be a hoping in your God constantly.

[NOTE]
====
. Or, “loyal love.”
====

[[v28-12-7]]

^<<v28-12-7,7>>^ As regards &#91;the&#93; tradesman,^&#42;1^ in his hand are the scales of deception; to defraud is what he has loved.

[NOTE]
====
. Or, “Canaanite.” Heb., kenaʹʽan; Gr., Kha·na·anʹ; Lat., Chaʹna·an. See Zec 14:21 ftn.
====

[[v28-12-8]]

^<<v28-12-8,8>>^ And Eʹphra·im keeps saying, ‘Indeed, I have become rich; I have found valuable things for myself. As regards all my toiling, they will find, on my part, no error that is sin.’

[[v28-12-9]]

^<<v28-12-9,9>>^ “But I am Jehovah your God from the land of Egypt. Yet I shall make you dwell in the tents as in the days of an appointed time.

[[v28-12-10]]

^<<v28-12-10,10>>^ And I spoke to the prophets, and visions I myself multiplied, and by the hand of the prophets I kept making likenesses.

[[v28-12-11]]

^<<v28-12-11,11>>^ “With Gilʹe·ad^&#42;1^ what is uncanny, also untruth, have occurred. In Gilʹgal they have sacrificed even bulls. Moreover, their altars are^&#42;2^ like piles of stones in the furrows of the open field.

[NOTE]
====
. “With Gilead,” by a slight correction; M, “If Gilead.”
. Or, “will be.”
====

[[v28-12-12]]

^<<v28-12-12,12>>^ And Jacob proceeded to run away to the field of Syria,^&#42;1^ and Israel kept serving for a wife,^&#42;2^ and for a wife he guarded &#91;sheep&#93;.

[NOTE]
====
. “Syria,” LXXVg; MSy, “Aram.”
. Or, “for a woman.” Heb., beʼish·shahʹ.
====

[[v28-12-13]]

^<<v28-12-13,13>>^ And by a prophet Jehovah brought up Israel out of Egypt, and by a prophet he was guarded.

[[v28-12-14]]

^<<v28-12-14,14>>^ Eʹphra·im caused offense to bitterness, and his deeds of bloodshed he leaves upon his own self, and his reproach his grand Master^&#42;1^ will repay to him.”

[NOTE]
====
. “His grand Master.” Heb., ʼAdho·navʹ, pl. of ʼA·dhohnʹ, to denote excellence or grandeur, accompanied by the sing. verb “repay.” Compare Ge 39:2 ftn.
====

'''

xref:028-hosea/028-hosea-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-hosea/028-hosea-013.adoc#v28-13-0[Próximo Capítulo &#62;]