include::./index.adoc[]

[[v28-4-0]]
=== Hosea, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-4-1]]

^<<v28-4-1,1>>^ Hear the word of Jehovah, O sons of Israel, for Jehovah has a legal case with the inhabitants of the land,^&#42;1^ for there is no truth nor loving-kindness^&#42;2^ nor knowledge of God in the land.

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
. Or, “loyal love.” Heb., cheʹsedh.
====

[[v28-4-2]]

^<<v28-4-2,2>>^ There are the pronouncing of curses and practicing of deception and murdering and stealing and committing of adultery that have broken forth, and acts of bloodshed have touched other acts of bloodshed.

[[v28-4-3]]

^<<v28-4-3,3>>^ That is why the land will mourn and every inhabitant in it will have to fade away with the wild beast of the field and with the flying creature of the heavens, and even the fishes of the sea themselves will be gathered &#91;in death&#93;.^&#42;1^

[NOTE]
====
. Or, “will die”; or, “will be taken away.” See Isa 57:1.
====

[[v28-4-4]]

^<<v28-4-4,4>>^ “However, let no man contend, neither let a man reprove, as your people are like those who are contending against a priest.^&#42;1^

[NOTE]
====
. M is obscure here.
====

[[v28-4-5]]

^<<v28-4-5,5>>^ And you will certainly stumble in the daytime, and even a prophet must stumble with you, as at night. And I will put your mother to silence.

[[v28-4-6]]

^<<v28-4-6,6>>^ My people will certainly be silenced, because there is no knowledge. Because the knowledge is what you yourself have rejected, I shall also reject you from serving as a priest to me; and &#91;because&#93; you keep forgetting the law of your God,^&#42;1^ I shall forget your sons, even I.

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
====

[[v28-4-7]]

^<<v28-4-7,7>>^ In proportion to the multitude of them, so they have sinned against me. My own glory they have exchanged^&#42;1^ for mere dishonor.

[NOTE]
====
. “My own glory they have exchanged” was the original reading. The Sopherim emended (changed) the text to read, “Their own glory I will exchange.” TSy confirm the original reading of the verb. See App 2B.
====

[[v28-4-8]]

^<<v28-4-8,8>>^ The sin of my people is what they keep devouring, and to their error they keep lifting up their soul.^&#42;1^

[NOTE]
====
. “Their soul(s),” TLXXSyVg and about 20 Heb. mss; M, “his soul (soulful desire).” See App 4A.
====

[[v28-4-9]]

^<<v28-4-9,9>>^ “And it will have to become for the people the same as for the priest; and I shall certainly hold an accounting against them for their ways; and their dealings I shall bring back upon them.

[[v28-4-10]]

^<<v28-4-10,10>>^ And they will actually eat, but will not get satisfied. They will actually treat &#91;women&#93; as harlots; but they will not increase, because they have left off paying regard to Jehovah himself.

[[v28-4-11]]

^<<v28-4-11,11>>^ Fornication^&#42;1^ and wine and sweet wine are what take away good motive.^&#42;2^

[NOTE]
====
. “Fornication.” Heb., zenuthʹ; Gr., por·neiʹan; Lat., for·ni·caʹti·o. See App 5A.
. Lit., “take away heart.” Heb., yiq·qach-levʹ. Compare interlinear reading of Grn.
====

[[v28-4-12]]

^<<v28-4-12,12>>^ Of their wooden &#91;idol&#93;^&#42;1^ my own people keep inquiring, and their own &#91;hand&#93; staff keeps telling them; because the very spirit of fornication has caused them to wander off, and by fornication they go out from under their God.^&#42;2^

[NOTE]
====
. Lit., “their tree (wood).”
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v28-4-13]]

^<<v28-4-13,13>>^ On the tops of the mountains they sacrifice, and on the hills they make sacrificial smoke, under massive tree and storax tree and big tree, because its shade is good. That is why YOUR daughters commit fornication and YOUR own daughters-in-law commit adultery.

[[v28-4-14]]

^<<v28-4-14,14>>^ “I shall not hold an accounting against YOUR daughters because they commit fornication, and against YOUR daughters-in-law because they commit adultery. For, as to the &#91;men&#93;, it is with the harlots that they get off to themselves, and with the female temple prostitutes that they sacrifice; and a people &#91;that&#93; does not understand will be trodden down.

[[v28-4-15]]

^<<v28-4-15,15>>^ Although you are committing fornication, O Israel, let not Judah become guilty, and do not YOU people come to Gilʹgal, neither go up to Beth-aʹven nor swear ‘As Jehovah is alive!’

[[v28-4-16]]

^<<v28-4-16,16>>^ For, like a stubborn cow, Israel has become stubborn. Is it now that Jehovah will shepherd them like a young ram in a roomy place?

[[v28-4-17]]

^<<v28-4-17,17>>^ Eʹphra·im is joined with idols. Let him be to himself!

[[v28-4-18]]

^<<v28-4-18,18>>^ Their wheat beer^&#42;1^ being gone, they have positively treated &#91;woman&#93; as a harlot. Her shielders have positively loved dishonor.

[NOTE]
====
. Or, “Their liquor.” Heb., sov·ʼamʹ.
====

[[v28-4-19]]

^<<v28-4-19,19>>^ A wind^&#42;1^ has wrapped her up in its wings. And they will be ashamed of their sacrifices.”

[NOTE]
====
. Or, “A spirit.” Heb., ruʹach; Gr., pneuʹma·tos; Lat., spiʹri·tus.
====

'''

xref:028-hosea/028-hosea-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-hosea/028-hosea-005.adoc#v28-5-0[Próximo Capítulo &#62;]