include::./index.adoc[]

[[v28-7-0]]
=== Hosea, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-7-1]]

^<<v28-7-1,1>>^ “At the time that I would bring healing to Israel, the error of Eʹphra·im is also actually uncovered, and the bad things of Sa·marʹi·a; for they have practiced falsehood, and a thief himself comes in; a marauder band actually makes a dash on the outside.

[[v28-7-2]]

^<<v28-7-2,2>>^ And they do not say to their own heart that all their badness I will remember. Now their dealings have surrounded them. In front of my face they have come to be.

[[v28-7-3]]

^<<v28-7-3,3>>^ By their badness they make &#91;the&#93; king rejoice, and, by their deceptions, princes.

[[v28-7-4]]

^<<v28-7-4,4>>^ All of them are adulterers, like a furnace set burning by a baker, &#91;who&#93; ceases poking after kneading dough until it is leavened.

[[v28-7-5]]

^<<v28-7-5,5>>^ On the day of our king, princes have sickened themselves—there is a rage because of wine. He has drawn his hand along with deriders.

[[v28-7-6]]

^<<v28-7-6,6>>^ For they have brought their heart near as to a furnace; it is burning inside them. All night long their baker is sleeping; by morning &#91;the furnace&#93;^&#42;1^ is burning as with a flaming fire.

[NOTE]
====
. Lit., “it,” masc., referring to “furnace,” masc.
====

[[v28-7-7]]

^<<v28-7-7,7>>^ They get hot, all of them, like the furnace, and they actually devour their judges. Their own kings have all fallen; none among them is calling out to me.

[[v28-7-8]]

^<<v28-7-8,8>>^ “As for Eʹphra·im, it is among the peoples that he personally mingles himself. Eʹphra·im himself has become a round cake not turned on the other side.

[[v28-7-9]]

^<<v28-7-9,9>>^ Strangers have eaten up his power, and he himself has not come to know &#91;it&#93;. Also, gray hairs themselves have become white on him, but he himself has not come to know &#91;it&#93;.

[[v28-7-10]]

^<<v28-7-10,10>>^ And the pride of Israel has testified to his face, and they have not returned to Jehovah their God,^&#42;1^ nor have they looked for him because of all this.

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v28-7-11]]

^<<v28-7-11,11>>^ And Eʹphra·im proves to be like a simpleminded dove without heart.^&#42;1^ To Egypt they have called; to As·syrʹi·a they have gone.

[NOTE]
====
. Or, “without good motive.” Heb., ʼehn lev.
====

[[v28-7-12]]

^<<v28-7-12,12>>^ “Whichever way they go, I shall spread out over them my net. Like flying creatures of the heavens I shall bring them down. I shall discipline them in agreement with the report to their assembly.

[[v28-7-13]]

^<<v28-7-13,13>>^ Woe to them, for they have fled from me! Despoiling to them, for they have transgressed against me! And I myself proceeded to redeem them, but they themselves have spoken lies even against me.

[[v28-7-14]]

^<<v28-7-14,14>>^ And they did not call to me for aid with their heart, although they kept howling on their beds. On account of their grain and sweet wine they kept loafing about; they kept turning against me.

[[v28-7-15]]

^<<v28-7-15,15>>^ And I, for my part, did disciplining; I strengthened their arms, but against me they kept scheming what was bad.

[[v28-7-16]]

^<<v28-7-16,16>>^ And they proceeded to return, not to anything higher;^&#42;1^ they had become like a loose bow. By the sword their princes will fall because of the denunciation of their tongue. This will be their derision in the land of Egypt.”

[NOTE]
====
. “Not to anything higher.” Lit., “not upward,” that is, not to an elevated form of worship. Heb., loʼ ʽal.
====

'''

xref:028-hosea/028-hosea-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-hosea/028-hosea-008.adoc#v28-8-0[Próximo Capítulo &#62;]