include::./index.adoc[]

[[v28-1-0]]
=== Hosea, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-1-1]]

^<<v28-1-1,1>>^ The word of Jehovah that occurred to Ho·seʹa the son of Be·eʹri in the days of Uz·ziʹah, Joʹtham, Aʹhaz &#91;and&#93; Hez·e·kiʹah, kings of Judah, and in the days of Jer·o·boʹam the son of Joʹash, the king of Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ There was a start of the word of Jehovah by Ho·seʹa, and Jehovah proceeded to say to Ho·seʹa: “Go, take to yourself a wife of fornication^&#42;1^ and children of fornication, because by fornication the land positively turns from following Jehovah.”

[NOTE]
====
. Lit., “fornications; prostitutions.” Heb., zenu·nimʹ, pl. See Ge 38:24; Eze 23:11, 29.
====

[[v28-1-3]]

^<<v28-1-3,3>>^ And he proceeded to go and take Goʹmer the daughter of Dib·laʹim, so that she became pregnant and in time bore to him a son.

[[v28-1-4]]

^<<v28-1-4,4>>^ And Jehovah went on to say to him: “Call his name Jezʹre·el, for yet a little while and I must hold an accounting for the acts of bloodshed of Jezʹre·el^&#42;1^ against the house of Jeʹhu, and I must cause the royal rule of the house of Israel to cease.

[NOTE]
====
. The royal city where the kings of northern Israel resided, although Samaria was their capital city. See 2Ki (8:29; 9:15, 25, 30-37; 10:1-11).
====

[[v28-1-5]]

^<<v28-1-5,5>>^ And it must occur in that day that I must break the bow of Israel in the low plain^&#42;1^ of Jezʹre·el.”

[NOTE]
====
. Or, “the valley.”
====

[[v28-1-6]]

^<<v28-1-6,6>>^ And she proceeded to become pregnant another time and to give birth to a daughter. And He^&#42;1^ went on to say to him: “Call her name Lo-ru·haʹmah,^&#42;2^ for I shall no more show mercy again to the house of Israel, because I shall positively take them away.^&#42;3^

[NOTE]
====
. “He,” MLXXVg; Sy, “Jehovah.”
. Meaning “She Was Not Shown Mercy.” Heb., Loʼ ru·chaʹmah.
. Or, “that I should positively pardon them.”
====

[[v28-1-7]]

^<<v28-1-7,7>>^ But to the house of Judah I shall show mercy, and I will save them by Jehovah their God;^&#42;1^ but I shall not save them by a bow or by a sword or by war, by horses or by horsemen.”

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v28-1-8]]

^<<v28-1-8,8>>^ And she gradually weaned Lo-ru·haʹmah, and she proceeded to become pregnant and give birth to a son.

[[v28-1-9]]

^<<v28-1-9,9>>^ So He said: “Call his name Lo-amʹmi,^&#42;1^ because YOU men are not my people^&#42;2^ and I myself shall prove to be not YOURS.^&#42;3^

[NOTE]
====
. Meaning “Not My People.” Heb., Loʼ ʽam·miʹ.
. “Not my people.” Heb., loʼ ʽam·miʹ.
. MLXX end chap. 1 here; TSyVg continue for two more vss.
====

[[v28-1-10]]

^<<v28-1-10,10>>^ “And the number of the sons of Israel must become like the grains of the sand of the sea that cannot be measured or numbered. And it must occur that in the place in which it used to be said to them, ‘YOU men are not my people,’ it will be said to them, ‘The sons of the living God.’^&#42;1^

[NOTE]
====
. “Living God.” Heb., ʼEl-chaiʹ.
====

[[v28-1-11]]

^<<v28-1-11,11>>^ And the sons of Judah and the sons of Israel will certainly be collected together into a unity^&#42;1^ and will actually set up for themselves one head and go up out of the land, because great will be the day of Jezʹre·el.^&#42;2^

[NOTE]
====
. “Into a unity.” Heb., yach·dawʹ.
. Meaning “God Will Sow Seed.” Heb., Yiz·reʽeʼlʹ.
====

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-hosea/028-hosea-002.adoc#v28-2-0[Próximo Capítulo &#62;]