include::./index.adoc[]

[[v28-9-0]]
=== Hosea, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-9-1]]

^<<v28-9-1,1>>^ “Do not rejoice, O Israel. Do not act joyful like the peoples. For by fornication you have gone from alongside your God. You have loved gifts of hire on all the threshing floors of grain.

[[v28-9-2]]

^<<v28-9-2,2>>^ Threshing floor and winepress do not feed them, and sweet wine itself proves disappointing to her.

[[v28-9-3]]

^<<v28-9-3,3>>^ They will not continue dwelling in the land of Jehovah, and Eʹphra·im must return to Egypt, and in As·syrʹi·a they will eat what is unclean.

[[v28-9-4]]

^<<v28-9-4,4>>^ They will not continue pouring out wine to Jehovah. And their sacrifices will not be gratifying to him; they are like the bread of times of mourning to them; all those eating it will defile themselves. For their bread is for their own soul;^&#42;1^ it will not come into the house of Jehovah.

[NOTE]
====
. Or, “for their own selves.” Heb., lenaph·shamʹ; Gr., tais psy·khaisʹ au·tonʹ; Lat., aʹni·mae i·psoʹrum. See App 4A.
====

[[v28-9-5]]

^<<v28-9-5,5>>^ What will YOU people do in the day of meeting and in the day of the festival of Jehovah?

[[v28-9-6]]

^<<v28-9-6,6>>^ For, look! they will have to go because of despoiling. Egypt itself will collect them together; Memʹphis,^&#42;1^ for its part, will bury them. As for their desirable things of silver, nettles themselves will take possession of them; thorny bushes will be in their tents.

[NOTE]
====
. “Memphis.” Gr. and Lat., Memʹphis; Heb., Moph; T(Aram.), leMa·phehsʹ; Syr., u·Ma·phes.
====

[[v28-9-7]]

^<<v28-9-7,7>>^ “The days of being given attention must come; the days of the due payment must come. Those of Israel will know &#91;it&#93;. The prophet will be foolish, the man of inspired expression^&#42;1^ will be maddened on account of the abundance of your error, even animosity being abundant.”

[NOTE]
====
. Or, “man of inspiration.” Lit., “man of the spirit.” Heb., ʼish ha·ruʹach; Gr., anʹthro·pos ho pneu·ma·to·phoʹros, “man bearing the spirit; man inspired”; Vgc(Lat.), viʹrum spi·ri·tu·aʹlem.
====

[[v28-9-8]]

^<<v28-9-8,8>>^ The watchman of Eʹphra·im was with my God.^&#42;1^ As regards a prophet, there is the trap of a birdcatcher on all his ways; there is an animosity in the house of his God.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v28-9-9]]

^<<v28-9-9,9>>^ They have gone down deep in bringing ruin,^&#42;1^ as in the days of Gibʹe·ah. He will remember their error; he will give attention to their sins.

[NOTE]
====
. Lit., “They have made [it] deep, they have brought [it] to ruin,” M; possibly, by a correction, “They have made his pit deep.”
====

[[v28-9-10]]

^<<v28-9-10,10>>^ “Like grapes in the wilderness I found Israel. Like the early fig on a fig tree in its beginning I saw the forefathers of YOU people. They themselves went in to Baʹal of Peʹor,^&#42;1^ and they proceeded to dedicate themselves to^&#42;2^ the shameful thing, and they came to be disgusting like &#91;the thing of&#93; their love.

[NOTE]
====
. Or, “Baal-peor.”
. Or, “to withdraw themselves to; to hold themselves separate for.”
====

[[v28-9-11]]

^<<v28-9-11,11>>^ As regards Eʹphra·im, like a flying creature their glory flies away, so that there is no giving birth, and no &#91;pregnant&#93; belly and no conception.

[[v28-9-12]]

^<<v28-9-12,12>>^ For although they bring up their sons, I will also bereave them of children so that there will be no man; because—woe also to them when I turn away from them!

[[v28-9-13]]

^<<v28-9-13,13>>^ Eʹphra·im, whom I have seen like Tyre planted in a pasture ground, even Eʹphra·im is destined to a bringing out of his sons even to a killer.”

[[v28-9-14]]

^<<v28-9-14,14>>^ Give to them, O Jehovah, what you should give. Give them a miscarrying womb and breasts shriveling up.

[[v28-9-15]]

^<<v28-9-15,15>>^ “All their badness was in Gilʹgal, for there I had to hate them. On account of the evil of their dealings I shall drive them away from my own house. I will not continue on loving them. All their princes are acting stubborn.

[[v28-9-16]]

^<<v28-9-16,16>>^ Eʹphra·im must be struck down. Their very root must dry up. There will be no fruit that they produce. Also, in case they bring to birth, I will even put to death the desirable things of their belly.”

[[v28-9-17]]

^<<v28-9-17,17>>^ My God^&#42;1^ will reject them, for they have not listened to him, and they will become fugitives among the nations.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

'''

xref:028-hosea/028-hosea-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-hosea/028-hosea-010.adoc#v28-10-0[Próximo Capítulo &#62;]