include::./index.adoc[]

[[v28-5-0]]
=== Hosea, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v28-5-1]]

^<<v28-5-1,1>>^ “Hear this, O priests, and pay attention, O house of Israel, and YOU, O house of the king, give ear, for with YOU people the judgment has to do; because a trap is what YOU have become to Mizʹpah and as a net spread over Taʹbor.

[[v28-5-2]]

^<<v28-5-2,2>>^ And in slaughter work those falling away have gone deep down, and I was an exhortation to all of them.

[[v28-5-3]]

^<<v28-5-3,3>>^ I personally have known Eʹphra·im, and Israel itself has not been hidden from me. For now, O Eʹphra·im, you have treated &#91;women&#93; like harlots; Israel has defiled itself.

[[v28-5-4]]

^<<v28-5-4,4>>^ Their dealings do not permit of a returning to their God,^&#42;1^ because there is a spirit of fornication in the midst of them; and Jehovah himself they have not acknowledged.

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v28-5-5]]

^<<v28-5-5,5>>^ And the pride of Israel has testified to his face; and Israel and Eʹphra·im themselves are made to stumble in their error. Judah has also stumbled with them.

[[v28-5-6]]

^<<v28-5-6,6>>^ With their flock and with their herd they proceeded to go and look for Jehovah, but they could not find &#91;him&#93;. He had drawn away from them.

[[v28-5-7]]

^<<v28-5-7,7>>^ With Jehovah himself they have dealt treacherously, for it is to strange sons that they have become father. Now a month will devour them with their portions.

[[v28-5-8]]

^<<v28-5-8,8>>^ “BLOW a horn^&#42;1^ in Gibʹe·ah, a trumpet^&#42;2^ in Raʹmah! SHOUT a war cry at Beth-aʹven—after you, O Benjamin!

[NOTE]
====
. Or, “shofar.” Heb., shoh·pharʹ.
. That is, a straight trumpet. Heb., chatso·tserahʹ; not the shofar, which was a ram’s curved horn. See Nu 10:2.
====

[[v28-5-9]]

^<<v28-5-9,9>>^ O Eʹphra·im, a mere object of astonishment you will become in the day of rebuke. Among the tribes of Israel I have made known trustworthy words.

[[v28-5-10]]

^<<v28-5-10,10>>^ The princes of Judah have become just like those moving back a boundary. Upon them I shall pour out my fury just like water.

[[v28-5-11]]

^<<v28-5-11,11>>^ Eʹphra·im is oppressed, crushed in justice, for he had taken it upon himself to walk after his adversary.^&#42;1^

[NOTE]
====
. “His adversary,” by a correction; M, “a commandment”; LXXSy, “vanities”; Vg, “filth.”
====

[[v28-5-12]]

^<<v28-5-12,12>>^ And I was like the moth^&#42;1^ to Eʹphra·im and just like rottenness to the house of Judah.

[NOTE]
====
. Possibly, “putrefaction.” LXX, “disturbance.”
====

[[v28-5-13]]

^<<v28-5-13,13>>^ “And Eʹphra·im got to see his sickness, and Judah his ulcer. And Eʹphra·im proceeded to go to As·syrʹi·a and send to a great king.^&#42;1^ But that one himself was unable to give healing to YOU people, and he could not take from YOU an ulcer with any cure.

[NOTE]
====
. Or, “King Jareb.” Lit., “a king [that] should contend.”
====

[[v28-5-14]]

^<<v28-5-14,14>>^ For I shall be like a young lion to Eʹphra·im and like a maned young lion to the house of Judah. I, I myself shall tear to pieces and I shall go &#91;and&#93; carry off, and there will be no deliverer.

[[v28-5-15]]

^<<v28-5-15,15>>^ I shall go, I will return to my place until they bear their guilt; and they will certainly seek my face. When they are in sore straits, they will seek me.”

'''

xref:028-hosea/028-hosea-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-hosea/028-hosea-006.adoc#v28-6-0[Próximo Capítulo &#62;]