include::./index.adoc[]

[[v34-2-0]]
=== Nahum, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v34-2-1]]

^<<v34-2-1,1>>^ One that does a scattering has come up before your^&#42;1^ face. Let there be a safeguarding of the fortified place. Watch &#91;the&#93; way. Strengthen &#91;the&#93; hips. Reinforce power very much.

[NOTE]
====
. “Your,” fem. sing., referring to Nineveh.
====

[[v34-2-2]]

^<<v34-2-2,2>>^ For Jehovah will certainly gather the pride of Jacob, like the pride of Israel, because those emptying out have emptied them out; and the shoots of them they have ruined.

[[v34-2-3]]

^<<v34-2-3,3>>^ The shield of his mighty men is dyed red; &#91;his&#93; men of vital energy^&#42;1^ are dressed in crimson stuff. With the fire of iron &#91;fittings&#93; is the war chariot in the day of his getting ready, and the juniper tree &#91;spears&#93;^&#42;2^ have been made to quiver.

[NOTE]
====
. Or, “men of valor.” Heb., ʼan·sheh-chaʹyil.
. Lit., “juniper trees”; a figure of speech for spear shafts.
====

[[v34-2-4]]

^<<v34-2-4,4>>^ In the streets the war chariots keep driving madly. They keep rushing up and down in the public squares. Their appearances are like torches. Like the lightnings they keep running.

[[v34-2-5]]

^<<v34-2-5,5>>^ He will remember his majestic ones. They will stumble in their walking. They will hasten to her wall, and the barricade will have to be firmly established.

[[v34-2-6]]

^<<v34-2-6,6>>^ The very gates of the rivers will certainly be opened, and the palace itself will actually be dissolved.

[[v34-2-7]]

^<<v34-2-7,7>>^ And it has been fixed; she has been uncovered; she will certainly be carried away, and her slave girls will be moaning, like the sound of doves, beating repeatedly upon their hearts.

[[v34-2-8]]

^<<v34-2-8,8>>^ And Ninʹe·veh, from the days &#91;that&#93; she &#91;has been&#93;, was like a pool of waters; but they are fleeing. “Stand still, YOU men!^&#42;1^ Stand still!” But there is no one turning back.

[NOTE]
====
. Or, “you waters!”
====

[[v34-2-9]]

^<<v34-2-9,9>>^ Plunder silver, YOU men; plunder gold; as there is no limit to the &#91;things in&#93; arrangement. There is a heavy amount of all sorts of desirable articles.

[[v34-2-10]]

^<<v34-2-10,10>>^ Emptiness and voidness, and &#91;a city&#93; laid waste! And the heart is melting, and there is a tottering of &#91;the&#93; knees, and severe pains are in all hips; and as for the faces of all of them, they have collected a glow &#91;of excitement&#93;.

[[v34-2-11]]

^<<v34-2-11,11>>^ Where is the lair of lions, and the cave^&#42;1^ that belongs to the maned young lions, where the lion^&#42;2^ walked and entered,^&#42;3^ where the lion’s cub was, and no one was making &#91;them&#93; tremble?

[NOTE]
====
. “Cave,” by transposing two letters; M, “pasture; pasturage.”
. “Lion.” Heb., ʼar·yehʹ, the African lion.
. “And entered,” or, “in order to enter” (la·vohʼʹ), by a slight correction; Heb., la·viʼʹ, the Asian lion.
====

[[v34-2-12]]

^<<v34-2-12,12>>^ &#91;The&#93; lion was tearing to pieces enough for his whelps, and was strangling for his lionesses. And he kept his holes filled with prey and his hiding places with animals torn to pieces.

[[v34-2-13]]

^<<v34-2-13,13>>^ “Look! I am against you,” is the utterance of Jehovah of armies,^&#42;1^ “and I will burn up her^&#42;2^ war chariot in the smoke. And a sword will devour your own maned young lions. And I will cut off from the earth your prey, and no more will the voice of your messengers be heard.”

[NOTE]
====
. “Jehovah of armies,” MTVg; LXX, “Jehovah Almighty.”
. “Her,” M; TLXXSyVgc, “your.”
====

'''

xref:034-nahum/034-nahum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-nahum/034-nahum-003.adoc#v34-3-0[Próximo Capítulo &#62;]