include::./index.adoc[]

[[v34-3-0]]
=== Nahum, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v34-3-1]]

^<<v34-3-1,1>>^ Woe to the city of bloodshed.^&#42;1^ She is all full of deception &#91;and&#93; of robbery. Prey does not depart!

[NOTE]
====
. Lit., “bloods.”
====

[[v34-3-2]]

^<<v34-3-2,2>>^ There is the sound of &#91;the&#93; whip and the sound of the rattling of &#91;the&#93; wheel, and the dashing horse and the leaping chariot.

[[v34-3-3]]

^<<v34-3-3,3>>^ The mounted horseman, and the flame of &#91;the&#93; sword, and the lightning of &#91;the&#93; spear, and the multitude of slain ones, and the heavy mass of carcasses; and there is no end to the dead bodies. They keep stumbling among their dead bodies;

[[v34-3-4]]

^<<v34-3-4,4>>^ owing to the abundance of the acts of prostitution of the prostitute, attractive with charm, a mistress of sorceries, she who is ensnaring nations by her acts of prostitution and families by her sorceries.

[[v34-3-5]]

^<<v34-3-5,5>>^ “Look! I am against you,”^&#42;1^ is the utterance of Jehovah of armies,^&#42;2^ “and I will put the covering of your skirts over your face, and I will cause nations to see your nakedness, and kingdoms your dishonor.

[NOTE]
====
. “You,” fem. sing., referring to Nineveh.
. “Jehovah of armies,” MTVg; LXX, “Jehovah God the Almighty.”
====

[[v34-3-6]]

^<<v34-3-6,6>>^ And I will throw disgusting things upon you, and I will make you despicable; and I will set you as a spectacle.

[[v34-3-7]]

^<<v34-3-7,7>>^ And it must occur that everyone seeing you will flee away from you and will certainly say, ‘Ninʹe·veh has been despoiled! Who will sympathize with her?’ From where shall I seek comforters for you?

[[v34-3-8]]

^<<v34-3-8,8>>^ Are you better than No-aʹmon, that was sitting by the Nile canals? Waters were all around her, whose wealth was &#91;the&#93; sea, whose wall was from &#91;the&#93; sea.

[[v34-3-9]]

^<<v34-3-9,9>>^ E·thi·oʹpi·a^&#42;1^ was her full might, also Egypt; and that without limit. Put and the Libʹy·ans^&#42;2^ themselves proved to be of assistance to you.^&#42;3^

[NOTE]
====
. “Ethiopia,” LXXVg; MTSy, “Cush.”
. “And the Libyans.” Heb., weLu·vimʹ.
. “You,” MTVg; LXX, “her.”
====

[[v34-3-10]]

^<<v34-3-10,10>>^ She, too, was meant for exile; she went into captivity. Her own children also came to be dashed to pieces at the head of all the streets; and over her glorified men they cast lots, and her great ones have all been bound with fetters.

[[v34-3-11]]

^<<v34-3-11,11>>^ “You yourself will also become drunk; you will become something hidden. You yourself also will seek a stronghold from &#91;the&#93; enemy.

[[v34-3-12]]

^<<v34-3-12,12>>^ All your fortified places are as fig trees with the first ripe fruits, which, if they get wiggled, will certainly fall into the mouth of an eater.

[[v34-3-13]]

^<<v34-3-13,13>>^ “Look! Your people are women in the midst of you. To your enemies the gates of your land must without fail be opened. Fire will certainly devour your bars.

[[v34-3-14]]

^<<v34-3-14,14>>^ Water for a siege draw out for yourself. Strengthen your fortified places. Get into the mire, and trample down in the clay; grab hold of &#91;the&#93; brick mold.

[[v34-3-15]]

^<<v34-3-15,15>>^ Even there fire will devour you. A sword will cut you off. It will devour you like the locust species.^&#42;1^ Make yourself heavy in numbers like the locust species; make yourself heavy in numbers like the locust.^&#42;2^

[NOTE]
====
. Or, “like the creeping, unwinged locust.” Heb., kai·yaʹleq. See Joe 1:4 ftn.
. Or, “like the locust crowd.” Heb., ka·ʼar·behʹ, the migratory, or desert, locust in the fully developed, winged stage.
====

[[v34-3-16]]

^<<v34-3-16,16>>^ You have multiplied your tradesmen more than the stars of the heavens.
“As for the locust species,^&#42;1^ it actually strips off its skin; then it flies away.

[NOTE]
====
. “The locust species.” Or, “the creeping, unwinged locust.”
====

[[v34-3-17]]

^<<v34-3-17,17>>^ Your guardsmen are like the locust,^&#42;1^ and your recruiting officers like the locust swarm.^&#42;2^ They are camping in the stone pens in a cold day. The sun itself has but to shine forth, and away they certainly flee; and their place is really unknown where they are.

[NOTE]
====
. See vs 15 ftn, “Locust.”
. “Locust swarm.” Heb., go·vaiʹ, used collectively; so called because of their swarming.
====

[[v34-3-18]]

^<<v34-3-18,18>>^ “Your shepherds have become drowsy, O king of As·syrʹi·a; your majestic ones stay in their residences. Your people have been scattered upon the mountains, and there is no one collecting &#91;them&#93; together.

[[v34-3-19]]

^<<v34-3-19,19>>^ There is no relief for your catastrophe. Your stroke has become unhealable. All those hearing the report about you will certainly clap their hands at you; because upon whom was it that your badness did not pass over constantly?”

'''

xref:034-nahum/034-nahum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habakkuk/035-habakkuk-001.adoc#v35-1-0[Próximo Capítulo &#62;]