include::./index.adoc[]

[[v34-1-0]]
=== Nahum, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v34-1-1]]

^<<v34-1-1,1>>^ The pronouncement against Ninʹe·veh: The book of the vision of Naʹhum the Elʹkosh·ite:^&#42;1^

[NOTE]
====
. Or, “of Elkosh.”
====

[[v34-1-2]]

^<<v34-1-2,2>>^ Jehovah is a God^&#42;1^ exacting exclusive devotion and taking vengeance; Jehovah is taking vengeance and is disposed to^&#42;2^ rage. Jehovah is taking vengeance against his adversaries, and he is resentful toward his enemies.

[NOTE]
====
. “A God.” Heb., ʼEl; Gr., The·osʹ; Lat., Deʹus.
. Lit., “and a master (lord) of.” Heb., u·vaʹʽal.
====

[[v34-1-3]]

^<<v34-1-3,3>>^ Jehovah is slow to anger and great in power, and by no means will Jehovah hold back from punishing.
In destructive wind and in storm is his way, and the cloud mass is the powder of his feet.

[[v34-1-4]]

^<<v34-1-4,4>>^ He is rebuking the sea, and he dries it up; and all the rivers he actually makes run dry.
Baʹshan and Carʹmel have withered, and the very blossom of Lebʹa·non has withered.

[[v34-1-5]]

^<<v34-1-5,5>>^ Mountains themselves have rocked because of him, and the very hills found themselves melting.
And the earth will be upheaved because of his face; the productive land also,^&#42;1^ and all those dwelling in it.

[NOTE]
====
. “The productive land also.” Heb., wethe·velʹ; LXX, “the whole [earth]”; Lat., orʹbis, “the circle,” that is, of the earth. See Mt 24:14 ftn, “Earth.”
====

[[v34-1-6]]

^<<v34-1-6,6>>^ In the face of his denunciation who can stand? And who can rise up against the heat of his anger?
His own rage will certainly be poured out like fire, and the very rocks^&#42;1^ will actually be pulled down because of him.

[NOTE]
====
. “And the very rocks.” Heb., wehats·tsu·rimʹ; Gr., peʹtrai; Syr., wetu·reʼ; Lat., peʹtrae.
====

[[v34-1-7]]

^<<v34-1-7,7>>^ Jehovah is good, a stronghold in the day of distress.
And he is cognizant of those seeking refuge in him.

[[v34-1-8]]

^<<v34-1-8,8>>^ And by the flood that is passing along he will make an outright extermination of her^&#42;1^ place, and darkness will pursue his very enemies.^&#42;2^

[NOTE]
====
. “Her,” referring to Nineveh.
. Most of the first chap. of Nahum’s prophecy appears to be an incomplete Heb. alphabetic, or acrostic, poem that goes only as far as the end of vs 8 and covers the Heb. letters ʼAʹleph through Kaph.
====

[[v34-1-9]]

^<<v34-1-9,9>>^ What will YOU men think up against Jehovah? He is causing an outright extermination.
Distress will not rise up a second time.

[[v34-1-10]]

^<<v34-1-10,10>>^ Although they are being interwoven even as thorns and they are drunken as with their wheat beer,^&#42;1^ they will certainly be devoured like stubble fully dry.

[NOTE]
====
. Or, “their liquor.”
====

[[v34-1-11]]

^<<v34-1-11,11>>^ Out of you^&#42;1^ there will actually go forth one who is thinking up against Jehovah what is bad, counseling what is not worth while.^&#42;2^

[NOTE]
====
. “You,” fem. sing.
. “What is not worth while.” Lit., “belial.” Heb., beli·yaʹʽal.
====

[[v34-1-12]]

^<<v34-1-12,12>>^ This is what Jehovah has said: “Although they were in complete form and there were many in that state, even in that state they must be cut down; and one must pass through. And I shall certainly afflict you, so that I shall not afflict you anymore.

[[v34-1-13]]

^<<v34-1-13,13>>^ And now I shall break his carrying bar from upon you, and the bands upon you I shall tear in two.

[[v34-1-14]]

^<<v34-1-14,14>>^ And concerning you^&#42;1^ Jehovah has commanded, ‘Nothing of your name will be sown anymore. Out of the house of your gods^&#42;2^ I shall cut off carved image and molten statue. I shall make a burial place for you, because you have been of no account.’^&#42;3^

[NOTE]
====
. “You,” masc. sing.
. Or, “your god.” Heb., ʼelo·heyʹkha; Gr., the·ouʹ; Lat., deʹi.
. MLXXSy end chap. 1 here.
====

[[v34-1-15]]

^<<v34-1-15,15>>^ “Look! Upon the mountains the feet of one bringing good news,^&#42;1^ one publishing peace. O Judah, celebrate your festivals. Pay your vows; because no more will any good-for-nothing person^&#42;2^ pass again through you. In his entirety he will certainly be cut off.”^&#42;3^

[NOTE]
====
. “One bringing good news.” Heb., mevas·serʹ; Gr., eu·ag·ge·li·zo·meʹnou, “evangelizer”; Lat., e·van·ge·li·zanʹtis.
. See vs 11 ftn, “While.”
. TLXXBagsterVg end chap. 1 here.
====

'''

xref:033-micah/033-micah-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-nahum/034-nahum-002.adoc#v34-2-0[Próximo Capítulo &#62;]