include::./index.adoc[]

[[v52-2-0]]
=== The First to the Thessalonians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v52-2-1]]

^<<v52-2-1,1>>^ To be sure, YOU yourselves know, brothers, how our visit to YOU has not been without results,

[[v52-2-2]]

^<<v52-2-2,2>>^ but how, after we had first suffered and been insolently treated (just as YOU know) in Phi·lipʹpi, we mustered up boldness^&#42;1^ by means of our God to speak to YOU the good news of God with a great deal of struggling.

[NOTE]
====
. Lit., “we were made outspoken.”
====

[[v52-2-3]]

^<<v52-2-3,3>>^ For the exhortation we give does not arise from error or from uncleanness or with deceit,

[[v52-2-4]]

^<<v52-2-4,4>>^ but, just as we have been proved by God as fit to be entrusted with the good news, so we speak, as pleasing, not men, but God, who makes proof of our hearts.

[[v52-2-5]]

^<<v52-2-5,5>>^ In fact, at no time have we turned up either with flattering speech, (just as YOU know) or with a false front^&#42;1^ for covetousness, God is witness!

[NOTE]
====
. “False front.” Lit., “pretense.”
====

[[v52-2-6]]

^<<v52-2-6,6>>^ Neither have we been seeking glory from men, no, either from YOU or from others, though we could be an expensive burden^&#42;1^ as apostles of Christ.

[NOTE]
====
. “Be an expensive burden.” Or, “wield authority; insist on our importance.”
====

[[v52-2-7]]

^<<v52-2-7,7>>^ To the contrary, we became gentle^&#42;1^ in the midst of YOU, as when a nursing mother cherishes her own children.

[NOTE]
====
. “Gentle,” AVgSyh,p; אBC*D*Vgc, “babes.”
====

[[v52-2-8]]

^<<v52-2-8,8>>^ So, having a tender affection for YOU, we were well pleased to impart to YOU, not only the good news of God, but also our own souls,^&#42;1^ because YOU became beloved to us.

[NOTE]
====
. Or, “lives.”
====

[[v52-2-9]]

^<<v52-2-9,9>>^ Certainly YOU bear in mind, brothers, our labor and toil. It was with working night and day, so as not to put an expensive burden upon any one of YOU, that we preached the good news of God to YOU.

[[v52-2-10]]

^<<v52-2-10,10>>^ YOU are witnesses, God is also, how loyal and righteous and unblamable we proved to be to YOU believers.

[[v52-2-11]]

^<<v52-2-11,11>>^ In harmony with that YOU well know how, as a father does his children, we kept exhorting each one of YOU, and consoling and bearing witness to YOU,

[[v52-2-12]]

^<<v52-2-12,12>>^ to the end that YOU should go on walking worthily of God who is calling YOU to his kingdom and glory.

[[v52-2-13]]

^<<v52-2-13,13>>^ Indeed, that is why we also thank God incessantly, because when YOU received God’s word, which YOU heard from us, YOU accepted it, not as the word of men, but, just as it truthfully is, as the word of God, which^&#42;1^ is also at work in YOU believers.

[NOTE]
====
. Or, “who.”
====

[[v52-2-14]]

^<<v52-2-14,14>>^ For YOU became imitators,^&#42;1^ brothers, of the congregations of God that are in Ju·deʹa in union with Christ Jesus, because YOU also began suffering at the hands of YOUR own countrymen the same things as they also &#91;are suffering&#93; at the hands of the Jews,

[NOTE]
====
. Or, “portrayers.”
====

[[v52-2-15]]

^<<v52-2-15,15>>^ who killed even the Lord Jesus and the prophets and persecuted us. Furthermore, they are not pleasing God, but are against &#91;the interests of&#93; all men,

[[v52-2-16]]

^<<v52-2-16,16>>^ as they try to hinder^&#42;1^ us from speaking to people of the nations that these might be saved, with the result that they always fill up the measure of their sins. But his^&#42;2^ wrath has at length^&#42;3^ come upon them.

[NOTE]
====
. Or, “as they keep on forbidding.”
. “The,” אAB; DVg, “God’s.”
. Or, “to the end.”
====

[[v52-2-17]]

^<<v52-2-17,17>>^ As for ourselves, brothers, when we were bereaved^&#42;1^ of YOU for but a short time,^&#42;2^ in person, not in heart, we endeavored far more than is usual to see YOUR faces with great desire.

[NOTE]
====
. Lit., “having been orphaned off.”
. Or, “for a season of an hour.” Lit., “toward an appointed time of an hour.”
====

[[v52-2-18]]

^<<v52-2-18,18>>^ For this reason we wanted to come to YOU, yes, I Paul, both once and a second time, but Satan cut across our path.

[[v52-2-19]]

^<<v52-2-19,19>>^ For what is our hope or joy or crown of exultation—why, is it not in fact YOU?—before our Lord Jesus at his presence?^&#42;1^

[NOTE]
====
. See App 5B.
====

[[v52-2-20]]

^<<v52-2-20,20>>^ YOU certainly are our glory and joy.

'''

xref:052-1-thessalonians/052-1-thessalonians-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-003.adoc#v52-3-0[Próximo Capítulo &#62;]