include::./index.adoc[]

[[v52-1-0]]
=== The First to the Thessalonians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v52-1-1]]

^<<v52-1-1,1>>^ Paul and Sil·vaʹnus^&#42;1^ and Timothy to the congregation of the Thes·sa·loʹni·ans in union with God the Father and &#91;the&#93; Lord Jesus Christ:
May YOU have undeserved kindness and peace.

[NOTE]
====
. Or, “Silas.”
====

[[v52-1-2]]

^<<v52-1-2,2>>^ We always thank God when we make mention concerning all of YOU in our prayers,

[[v52-1-3]]

^<<v52-1-3,3>>^ for we bear incessantly in mind YOUR faithful work^&#42;1^ and &#91;your&#93; loving labor^&#42;2^ and &#91;your&#93; endurance due to &#91;your&#93; hope in our Lord Jesus Christ before our God and Father.

[NOTE]
====
. Or, “your work due to faith.”
. Or, “[your] hard effort due to love.”
====

[[v52-1-4]]

^<<v52-1-4,4>>^ For we know, brothers loved by God, his choosing of YOU,

[[v52-1-5]]

^<<v52-1-5,5>>^ because the good news we preach did not turn up among YOU with speech alone but also with power and with holy spirit and strong conviction,^&#42;1^ just as YOU know what sort of men we became to YOU for YOUR sakes;

[NOTE]
====
. Lit., “full assurance.”
====

[[v52-1-6]]

^<<v52-1-6,6>>^ and YOU became imitators of us and of the Lord, seeing that YOU accepted the word under much tribulation with joy of holy spirit,

[[v52-1-7]]

^<<v52-1-7,7>>^ so that YOU came to be an example to all the believers in Mac·e·doʹni·a and in A·chaʹia.^&#42;1^

[NOTE]
====
. The Roman province of southern Greece with its capital at Corinth.
====

[[v52-1-8]]

^<<v52-1-8,8>>^ The fact is, not only has the word of Jehovah^&#42;1^ sounded forth from YOU in Mac·e·doʹni·a and A·chaʹia, but in every place YOUR faith toward God has spread abroad, so that we do not need to say anything.

[NOTE]
====
. “Of Jehovah,” J7,​8,​17,​18,​22,​23; אcB(Gr.), tou Ky·riʹou; א*, “of God.” See App 1D.
====

[[v52-1-9]]

^<<v52-1-9,9>>^ For they themselves keep reporting about the way we first entered in among YOU and how YOU turned to God from &#91;YOUR&#93; idols to slave for a living and true God,

[[v52-1-10]]

^<<v52-1-10,10>>^ and to wait for his Son from the heavens, whom he raised up from the dead, namely, Jesus, who delivers us from the wrath which is coming.

'''

xref:051-colossians/051-colossians-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-002.adoc#v52-2-0[Próximo Capítulo &#62;]