include::./index.adoc[]

[[v52-3-0]]
=== The First to the Thessalonians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v52-3-1]]

^<<v52-3-1,1>>^ Hence, when we could bear it no longer, we saw good to be left alone in Athens;

[[v52-3-2]]

^<<v52-3-2,2>>^ and we sent Timothy, our brother and God’s minister^&#42;1^ in the good news about the Christ, in order to make YOU firm and comfort YOU in behalf of YOUR faith,

[NOTE]
====
. Or, “servant.” Gr., di·aʹko·non; Lat., mi·niʹstrum (from miʹnus, “less”).
====

[[v52-3-3]]

^<<v52-3-3,3>>^ that no one might be swayed by these tribulations. For YOU yourselves know we are appointed to this very thing.

[[v52-3-4]]

^<<v52-3-4,4>>^ In fact, too, when we were with YOU, we used to tell YOU beforehand that we were destined to suffer tribulation, just as it has also happened and as YOU know.

[[v52-3-5]]

^<<v52-3-5,5>>^ That is why, indeed, when I could bear it no longer, I sent to know of YOUR faithfulness,^&#42;1^ as perhaps in some way the Tempter might have tempted YOU, and our labor might have turned out to be in vain.

[NOTE]
====
. Or, “faith.”
====

[[v52-3-6]]

^<<v52-3-6,6>>^ But Timothy has just now come to us from YOU and given us the good news about YOUR faithfulness and love, and that YOU continue having good remembrance of us always, yearning to see us in the same way, indeed, as we also do YOU.

[[v52-3-7]]

^<<v52-3-7,7>>^ That is why, brothers, we have been comforted over YOU in all our necessity and tribulation through the faithfulness YOU show,

[[v52-3-8]]

^<<v52-3-8,8>>^ because now we live if YOU stand firm in &#91;the&#93; Lord.

[[v52-3-9]]

^<<v52-3-9,9>>^ For what thanksgiving can we render to God concerning YOU in return for all the joy with which we are rejoicing on YOUR account before our God,

[[v52-3-10]]

^<<v52-3-10,10>>^ while night and day we make more than extraordinary supplications to see YOUR faces and to make good the things that are lacking about YOUR faith?

[[v52-3-11]]

^<<v52-3-11,11>>^ Now may our God and Father himself and our Lord Jesus direct our way prosperously to YOU.

[[v52-3-12]]

^<<v52-3-12,12>>^ Moreover, may the Lord cause YOU to increase, yes, make YOU abound, in love to one another and to all, even as we also do to YOU;

[[v52-3-13]]

^<<v52-3-13,13>>^ to the end that he may make YOUR hearts firm, unblamable in holiness before our God and Father at the presence^&#42;1^ of our Lord Jesus with all his holy ones.

[NOTE]
====
. See App 5B.
====

'''

xref:052-1-thessalonians/052-1-thessalonians-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-004.adoc#v52-4-0[Próximo Capítulo &#62;]