include::./index.adoc[]

[[v52-5-0]]
=== The First to the Thessalonians, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v52-5-1]]

^<<v52-5-1,1>>^ Now as for the times and the seasons,^&#42;1^ brothers, YOU need nothing to be written to YOU.

[NOTE]
====
. Or, “appointed times.” Gr., kai·ronʹ.
====

[[v52-5-2]]

^<<v52-5-2,2>>^ For YOU yourselves know quite well that Jehovah’s^&#42;1^ day is coming exactly as a thief in the night.

[NOTE]
====
. See App 1D.
====

[[v52-5-3]]

^<<v52-5-3,3>>^ Whenever it is that they are saying: “Peace and security!” then sudden destruction is to be instantly upon them just as the pang of distress upon a pregnant woman; and they will by no means escape.

[[v52-5-4]]

^<<v52-5-4,4>>^ But YOU, brothers, YOU are not in darkness, so that that day should overtake YOU as it would thieves,^&#42;1^

[NOTE]
====
. “Overtake you as it would thieves,” AB; אDItVgSyh,pArm, “overtake you as a thief.”
====

[[v52-5-5]]

^<<v52-5-5,5>>^ for YOU are all sons of light and sons of day. We belong neither to night nor to darkness.

[[v52-5-6]]

^<<v52-5-6,6>>^ So, then, let us not sleep on as the rest do, but let us stay awake and keep our senses.^&#42;1^

[NOTE]
====
. Lit., “and may we be sober.”
====

[[v52-5-7]]

^<<v52-5-7,7>>^ For those who sleep are accustomed to sleep at night, and those who get drunk are usually drunk at night.

[[v52-5-8]]

^<<v52-5-8,8>>^ But as for us who belong to the day, let us keep our senses and have on the breastplate of faith and love and as a helmet the hope of salvation;

[[v52-5-9]]

^<<v52-5-9,9>>^ because God assigned us, not to wrath, but to the acquiring of salvation through our Lord Jesus Christ.^&#42;1^

[NOTE]
====
. “Christ,” אAVgSyp; B omits.
====

[[v52-5-10]]

^<<v52-5-10,10>>^ He died for us, that, whether we stay awake or are asleep, we should live together with him.

[[v52-5-11]]

^<<v52-5-11,11>>^ Therefore keep comforting one another and building one another up, just as YOU are in fact doing.

[[v52-5-12]]

^<<v52-5-12,12>>^ Now we request YOU, brothers, to have regard for those who are working hard among YOU and presiding over^&#42;1^ YOU in &#91;the&#93; Lord and admonishing YOU;

[NOTE]
====
. Or, “directing; taking the lead among.” Lit., “standing before.” Gr., pro·i·sta·meʹnous.
====

[[v52-5-13]]

^<<v52-5-13,13>>^ and to give them more than extraordinary consideration in love because of their work. Be peaceable with one another.

[[v52-5-14]]

^<<v52-5-14,14>>^ On the other hand, we exhort YOU, brothers, admonish the disorderly, speak consolingly to the depressed souls, support the weak, be long-suffering toward all.

[[v52-5-15]]

^<<v52-5-15,15>>^ See that no one renders injury for injury to anyone else, but always pursue what is good toward one another and to all others.

[[v52-5-16]]

^<<v52-5-16,16>>^ Always be rejoicing.

[[v52-5-17]]

^<<v52-5-17,17>>^ Pray incessantly.

[[v52-5-18]]

^<<v52-5-18,18>>^ In connection with everything give thanks. For this is the will of God in union with Christ Jesus respecting YOU.

[[v52-5-19]]

^<<v52-5-19,19>>^ Do not put out the fire of the spirit.

[[v52-5-20]]

^<<v52-5-20,20>>^ Do not treat prophesyings with contempt.

[[v52-5-21]]

^<<v52-5-21,21>>^ Make sure^&#42;1^ of all things; hold fast to what is fine.

[NOTE]
====
. Lit., “Be you proving.”
====

[[v52-5-22]]

^<<v52-5-22,22>>^ Abstain from every form of wickedness.

[[v52-5-23]]

^<<v52-5-23,23>>^ May the very God of peace sanctify YOU completely. And sound in every respect may the spirit and soul and body of YOU &#91;brothers&#93; be preserved in a blameless manner at the presence^&#42;1^ of our Lord Jesus Christ.

[NOTE]
====
. See App 5B.
====

[[v52-5-24]]

^<<v52-5-24,24>>^ He who is calling YOU is faithful, and he will also do it.

[[v52-5-25]]

^<<v52-5-25,25>>^ Brothers, continue in prayer for us.

[[v52-5-26]]

^<<v52-5-26,26>>^ Greet all the brothers with a holy kiss.

[[v52-5-27]]

^<<v52-5-27,27>>^ I am putting YOU under the solemn obligation by the Lord^&#42;1^ for this letter to be read to all the brothers.

[NOTE]
====
. “The Lord,” אABVg; J7,​8,​13,​14,​16, “Jehovah.”
====

[[v52-5-28]]

^<<v52-5-28,28>>^ The undeserved kindness of our Lord Jesus Christ be with YOU.^&#42;1^

[NOTE]
====
. אADcItVgSyh,p close with “Amen”; BD*SyhiArm omit.
====

'''

xref:052-1-thessalonians/052-1-thessalonians-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-thessalonians/053-2-thessalonians-001.adoc#v53-1-0[Próximo Capítulo &#62;]