include::./index.adoc[]

[[v33-3-0]]
=== Micah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-3-1]]

^<<v33-3-1,1>>^ And I proceeded to say: “Hear, please, YOU heads of Jacob and YOU commanders of the house of Israel. Is it not YOUR business to know justice?

[[v33-3-2]]

^<<v33-3-2,2>>^ YOU haters of what is good and lovers of badness, tearing off their skin from people and their organism from off their bones;

[[v33-3-3]]

^<<v33-3-3,3>>^ YOU the ones who have also eaten the organism of my people, and have stripped their very skin from off them, and smashed to pieces their very bones, and crushed &#91;them&#93; to pieces like what is in a widemouthed pot and like flesh in the midst of a cooking pot.

[[v33-3-4]]

^<<v33-3-4,4>>^ At that time they will call to Jehovah for aid, but he will not answer them. And he will conceal his face from them in that time, according as they committed badness in their dealings.

[[v33-3-5]]

^<<v33-3-5,5>>^ “This is what Jehovah has said against the prophets that are causing my people to wander,^&#42;1^ that are biting with their teeth and that actually call out, ‘Peace!’ that, when anyone does not put &#91;something&#93; into their mouths, also actually sanctify war against him,

[NOTE]
====
. Or, “err.”
====

[[v33-3-6]]

^<<v33-3-6,6>>^ ‘Therefore YOU men will have night, so that there will be no vision; and darkness YOU will have, so as not to practice divination. And the sun will certainly set upon the prophets, and the day must get dark upon them.

[[v33-3-7]]

^<<v33-3-7,7>>^ And the visionaries will have to be ashamed, and the diviners will certainly be disappointed. And they will have to cover over the mustache, all of them, for there is no answer from God.’”^&#42;1^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Lat., Deʹi.
====

[[v33-3-8]]

^<<v33-3-8,8>>^ And, on the other hand, I myself have become full of power, with the spirit of Jehovah, and of justice and mightiness, in order to tell to Jacob his revolt and to Israel his sin.

[[v33-3-9]]

^<<v33-3-9,9>>^ Hear, please, this, YOU head ones of the house of Jacob and YOU commanders of the house of Israel, the ones detesting justice and the ones who make even everything that is straight crooked;

[[v33-3-10]]

^<<v33-3-10,10>>^ building Zion with acts of bloodshed and Jerusalem with unrighteousness.

[[v33-3-11]]

^<<v33-3-11,11>>^ Her own head ones judge merely for a bribe, and her own priests instruct just for a price, and her own prophets practice divination simply for money;^&#42;1^ yet upon Jehovah they keep supporting themselves, saying: “Is not Jehovah in the midst of us? There will come upon us no calamity.”

[NOTE]
====
. Or, “silver.”
====

[[v33-3-12]]

^<<v33-3-12,12>>^ Therefore on account of YOU men Zion will be plowed up as a mere field, and Jerusalem herself will become mere heaps of ruins, and the mountain of the house will be as the high places of a forest.

'''

xref:033-micah/033-micah-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-micah/033-micah-004.adoc#v33-4-0[Próximo Capítulo &#62;]