include::./index.adoc[]

[[v33-5-0]]
=== Micah, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-5-1]]

^<<v33-5-1,1>>^ “At this time you make cuttings upon yourself, O daughter of an invasion; a siege he has laid against us. With the rod they will strike upon the cheek the judge of Israel.^&#42;1^

[NOTE]
====
. MLXXSy end chap. 4 here; TLXXBagsterVg begin chap. 5 with this vs.
====

[[v33-5-2]]

^<<v33-5-2,2>>^ “And you, O Bethʹle·hem^&#42;1^ Ephʹra·thah, the one too little to get to be among the thousands of Judah, from you^&#42;2^ there will come out to me the one who is to become ruler in Israel, whose origin^&#42;3^ is from early times, from the days of time indefinite.

[NOTE]
====
. Meaning “House of Bread.” Heb., Behth-leʹchem.
. “You,” masc. sing.
. “Origin,” according to BDB, p. 426 and KB, p. 505.
====

[[v33-5-3]]

^<<v33-5-3,3>>^ “Therefore he will give them up until the time that she who is giving birth actually gives birth. And the rest of his brothers will return to the sons of Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ “And he will certainly stand and do shepherding in the strength of Jehovah,^&#42;1^ in the superiority of the name of Jehovah^&#42;2^ his God. And they will certainly keep dwelling, for now he will be great as far as the ends^&#42;3^ of the earth.

[NOTE]
====
. See App 1C §2.
. See App 1C §2.
. See Jer 16:19 ftn.
====

[[v33-5-5]]

^<<v33-5-5,5>>^ And this one must become peace. As for the As·syrʹi·an, when he comes into our land and when he treads upon our dwelling towers,^&#42;1^ we shall also have to raise up against him seven shepherds, yes, eight dukes of mankind.^&#42;2^

[NOTE]
====
. Possibly, “our soil (ground),” in agreement with LXXSy.
. Or, “of earthling men.” Heb., ʼa·dhamʹ.
====

[[v33-5-6]]

^<<v33-5-6,6>>^ And they will actually shepherd the land of As·syrʹi·a with the sword, and the land of Nimʹrod in its entrances. And he will certainly bring about deliverance from the As·syrʹi·an, when he comes into our land and when he treads upon our territory.

[[v33-5-7]]

^<<v33-5-7,7>>^ “And the remaining ones^&#42;1^ of Jacob must become in the midst of many peoples like dew from Jehovah, like copious showers upon vegetation, that does not hope for man^&#42;2^ or wait for the sons of earthling man.^&#42;3^

[NOTE]
====
. Or, “the remainder; the remnant.”
. “For man.” Heb., leʼishʹ.
. Or, “mankind.” Heb., ʼa·dhamʹ.
====

[[v33-5-8]]

^<<v33-5-8,8>>^ And the remaining ones of Jacob must become among the nations, in the midst of many peoples, like a lion among the beasts of a forest, like a maned young lion among droves of sheep, which, when it actually passes through, certainly both tramples down and tears in pieces; and there is no deliverer.

[[v33-5-9]]

^<<v33-5-9,9>>^ Your^&#42;1^ hand will be high above your adversaries, and all enemies of yours will be cut off.”

[NOTE]
====
. “Your,” masc. sing.
====

[[v33-5-10]]

^<<v33-5-10,10>>^ “And it must occur in that day,” is the utterance of Jehovah, “that I will cut off your horses from the midst of you and destroy your chariots.

[[v33-5-11]]

^<<v33-5-11,11>>^ And I will cut off the cities of your land and tear down all your fortified places.

[[v33-5-12]]

^<<v33-5-12,12>>^ And I will cut off sorceries out of your hand, and no practicers of magic will you continue to have.

[[v33-5-13]]

^<<v33-5-13,13>>^ And I will cut off your graven images and your pillars from the midst of you, and you will no more bow down to the work of your hands.

[[v33-5-14]]

^<<v33-5-14,14>>^ And I will uproot your sacred poles^&#42;1^ from the midst of you and annihilate your cities.

[NOTE]
====
. Or, “Asherim.”
====

[[v33-5-15]]

^<<v33-5-15,15>>^ And in anger and in rage I will execute vengeance upon the nations that have not obeyed.”

'''

xref:033-micah/033-micah-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-micah/033-micah-006.adoc#v33-6-0[Próximo Capítulo &#62;]