include::./index.adoc[]

[[v33-2-0]]
=== Micah, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-2-1]]

^<<v33-2-1,1>>^ “Woe to those who are scheming what is harmful, and to those practicing what is bad, upon their beds! By the light of the morning they proceed to do it, because it is in the power of their hand.

[[v33-2-2]]

^<<v33-2-2,2>>^ And they have desired fields and have seized &#91;them&#93;; also houses, and have taken &#91;them&#93;; and they have defrauded an able-bodied man^&#42;1^ and his household, a man^&#42;2^ and his hereditary possession.

[NOTE]
====
. “An able-bodied man.” Heb., geʹver.
. “A man.” Heb., weʼishʹ.
====

[[v33-2-3]]

^<<v33-2-3,3>>^ “Therefore this is what Jehovah has said, ‘Here I am thinking up against this family a calamity from which YOU people will not remove YOUR necks, so that YOU will not walk haughtily; because it is a time of calamity.

[[v33-2-4]]

^<<v33-2-4,4>>^ In that day one will raise up concerning YOU people a proverbial saying and will certainly lament a lamentation, even a lamentation. One will have to say: “We have positively been despoiled! The very portion of my people he alters. How he removes &#91;it&#93; from me! To the unfaithful one he apportions out our own fields.”

[[v33-2-5]]

^<<v33-2-5,5>>^ Therefore you will come to have no one casting out the cord, by lot, in the congregation^&#42;1^ of Jehovah.

[NOTE]
====
. “In the congregation of.” Heb., biq·halʹ; Gr., ek·kle·siʹai. See De 4:10 ftns.
====

[[v33-2-6]]

^<<v33-2-6,6>>^ Do not YOU people let &#91;words&#93; drop. They let &#91;words&#93; drop. They will not let &#91;words&#93; drop concerning these &#91;things&#93;. Humiliations will not move away.

[[v33-2-7]]

^<<v33-2-7,7>>^ “‘Is it being said, O house of Jacob: “Has the spirit of Jehovah^&#42;1^ become discontented, or are these his dealings?” Do not my own words do good in the case of the one walking uprightly?

[NOTE]
====
. Or, “the active force of Jehovah.” Heb., ruʹach Yehwahʹ. See Ge 1:2 ftn, “Force.”
====

[[v33-2-8]]

^<<v33-2-8,8>>^ “‘And yesterday my own people proceeded to rise up as an outright enemy. From the front of a garment YOU men strip off the majestic ornament, from the ones passing by confidently, &#91;like&#93; those returning from war.

[[v33-2-9]]

^<<v33-2-9,9>>^ The women of my people YOU drive out from the house in which a woman^&#42;1^ has exquisite delight. From off her children YOU take my splendor, to time indefinite.

[NOTE]
====
. Lit., “she.”
====

[[v33-2-10]]

^<<v33-2-10,10>>^ Get up and go, because this is not a resting-place. Because of the fact that she has become unclean, there is a wrecking; and &#91;the&#93; wrecking work is painful.

[[v33-2-11]]

^<<v33-2-11,11>>^ If a man,^&#42;1^ walking by wind^&#42;2^ and falsehood, has told the lie: “I shall let &#91;words&#93; drop to you concerning wine and concerning intoxicating liquor,” he also will certainly become the one letting &#91;words&#93; drop for this people.

[NOTE]
====
. Heb., ʼish.
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v33-2-12]]

^<<v33-2-12,12>>^ “‘I shall positively gather Jacob, all of you; I shall without fail collect the remaining ones^&#42;1^ of Israel together. In unity I shall set them, like a flock in the pen,^&#42;2^ like a drove in the midst of its pasture; they will be noisy with men.’^&#42;3^

[NOTE]
====
. Or, “the remnant.”
. “In the pen,” by a change of vowel pointing in agreement with TVg; M, “Bozrah.”
. “With men.” Heb., me·ʼa·dhamʹ.
====

[[v33-2-13]]

^<<v33-2-13,13>>^ “The one making a breakthrough will certainly come up before them: they will actually break through. And they will pass through a gate, and they will go out by it. And their king will pass through before them, with Jehovah at the head of them.”

'''

xref:033-micah/033-micah-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-micah/033-micah-003.adoc#v33-3-0[Próximo Capítulo &#62;]