include::./index.adoc[]

[[v33-6-0]]
=== Micah, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-6-1]]

^<<v33-6-1,1>>^ Hear, please, YOU people, what Jehovah is saying.^&#42;1^ Get up, conduct a legal case with the mountains, and may the hills hear your voice.

[NOTE]
====
. “Hear, then, Jehovah’s word. Jehovah said,” LXX.
====

[[v33-6-2]]

^<<v33-6-2,2>>^ Hear, O YOU mountains, the legal case of Jehovah, also YOU durable objects, YOU foundations of &#91;the&#93; earth; for Jehovah has a legal case with his people, and it is with Israel that he will argue:

[[v33-6-3]]

^<<v33-6-3,3>>^ “O my people, what have I done to you? And in what way have I tired you out? Testify against me.

[[v33-6-4]]

^<<v33-6-4,4>>^ For I brought you up out of the land of Egypt, and from the house of slaves I redeemed you; and I proceeded to send before you Moses, Aaron and Mirʹi·am.

[[v33-6-5]]

^<<v33-6-5,5>>^ O my people, remember, please, what Baʹlak the king of Moʹab counseled, and what Baʹlaam the son of Beʹor answered him. From Shitʹtim^&#42;1^ it was, all the way to Gilʹgal, to the intent that the righteous acts of Jehovah might be known.”

[NOTE]
====
. Or, “the Acacia Trees.”
====

[[v33-6-6]]

^<<v33-6-6,6>>^ With what shall I confront Jehovah? &#91;With what&#93; shall I bow myself to God on high? Shall I confront him with whole burnt offerings, with calves a year old?

[[v33-6-7]]

^<<v33-6-7,7>>^ Will Jehovah be pleased with thousands of rams, with tens of thousands of torrents of oil? Shall I give my firstborn son for my revolt, the fruitage of my belly for the sin of my soul?

[[v33-6-8]]

^<<v33-6-8,8>>^ He has told you, O earthling man,^&#42;1^ what is good. And what is Jehovah asking back from you but to exercise justice and to love kindness^&#42;2^ and to be modest in walking with your God?

[NOTE]
====
. Or, “O man.” Heb., ʼa·dhamʹ.
. Or, “loving-kindness; loyal love.” Heb., cheʹsedh.
====

[[v33-6-9]]

^<<v33-6-9,9>>^ To the city the very voice of Jehovah calls out, and &#91;the person of&#93; practical wisdom will fear your name. Hear &#91;the&#93; rod and who it was that designated it,^&#42;1^ O YOU people.

[NOTE]
====
. “It,” fem., hence, not referring to the “rod,” masc., but possibly to the punishment by means of the rod.
====

[[v33-6-10]]

^<<v33-6-10,10>>^ Do there yet exist &#91;in&#93; the house of a wicked one the treasures of wickedness, and the scrimped eʹphah measure that is denounced?

[[v33-6-11]]

^<<v33-6-11,11>>^ Can I be &#91;morally&#93; clean with wicked scales and with a bag of deceptive stone weights?

[[v33-6-12]]

^<<v33-6-12,12>>^ For her own rich men have become full of violence, and her own inhabitants have spoken falsehood, and their tongue is tricky in their mouth.

[[v33-6-13]]

^<<v33-6-13,13>>^ “And I also, for my part, shall certainly make &#91;you&#93; sick by striking you; there will be a desolating &#91;of you&#93;, on account of your sins.

[[v33-6-14]]

^<<v33-6-14,14>>^ You, for your part, will eat and not get satisfied, and your emptiness will be in the midst of you.^&#42;1^ And you will remove &#91;things&#93;, but you will not carry &#91;them&#93; safely away; and whatever you would carry away safely, I shall give to the sword itself.

[NOTE]
====
. “And there will exist no power in the midst of you,” by a correction; Sy, “and dysentery will be in your intestines.”
====

[[v33-6-15]]

^<<v33-6-15,15>>^ You, for your part, will sow seed, but you will not reap. You, for your part, will tread olives, but you will not grease yourself with oil; also sweet wine, but you will not drink wine.

[[v33-6-16]]

^<<v33-6-16,16>>^ And the statutes of Omʹri and all the work of the house of Aʹhab are observed, and YOU people walk in their counsels; to the end that I may make you an object of astonishment and her inhabitants something to be whistled at; and the reproach of peoples^&#42;1^ YOU men will bear.”

[NOTE]
====
. “Peoples,” LXX; MTSyVg, “my people.”
====

'''

xref:033-micah/033-micah-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-micah/033-micah-007.adoc#v33-7-0[Próximo Capítulo &#62;]