include::./index.adoc[]

[[v33-7-0]]
=== Micah, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-7-1]]

^<<v33-7-1,1>>^ Too bad for me, for I have become like the gatherings of summer fruit, like the gleaning of a grape gathering! There is no grape cluster to eat, no early fig, that my soul would desire!

[[v33-7-2]]

^<<v33-7-2,2>>^ The loyal one^&#42;1^ has perished from the earth,^&#42;2^ and among mankind^&#42;3^ there is no upright one. All of them, for bloodshed they lie in wait. They hunt, everyone his own brother, with a dragnet.

[NOTE]
====
. Or, “The one of loving-kindness.” Heb., cha·sidhʹ.
. Or, “the land.” Heb., ha·ʼaʹrets.
. Or, “among earthling men.” Heb., ba·ʼa·dhamʹ.
====

[[v33-7-3]]

^<<v33-7-3,3>>^ &#91;Their&#93; hands are upon what is bad, to do &#91;it&#93; well; the prince is asking &#91;for something&#93;, and the one who is judging &#91;does so&#93; for the reward, and the great one is speaking forth the craving of his soul, his very own; and they interweave it.

[[v33-7-4]]

^<<v33-7-4,4>>^ Their best one is like a brier, &#91;their&#93; most upright one is worse than a thorn hedge. The day of your watchmen, &#91;of&#93; your being given attention, must come. Now will occur the confounding of them.

[[v33-7-5]]

^<<v33-7-5,5>>^ Do not put YOUR faith in a companion. Do not put YOUR trust in a confidential friend. From her who is lying in your bosom guard the openings of your mouth.

[[v33-7-6]]

^<<v33-7-6,6>>^ For a son is despising a father; a daughter is rising up against her mother; a daughter-in-law against her mother-in-law; a man’s enemies are the men^&#42;1^ of his household.

[NOTE]
====
. “Men of.” Heb., ʼan·shehʹ, pl. of ʼish, which is earlier rendered “a man’s” in this sentence.
====

[[v33-7-7]]

^<<v33-7-7,7>>^ But as for me, it is for Jehovah that I shall keep on the lookout. I will show a waiting attitude for the God of my salvation. My God will hear me.

[[v33-7-8]]

^<<v33-7-8,8>>^ Do not rejoice over me, O you woman enemy of mine. Although I have fallen, I shall certainly rise up; although I dwell in the darkness, Jehovah will be a light to me.

[[v33-7-9]]

^<<v33-7-9,9>>^ The raging of Jehovah I shall bear—for I have sinned against him—until he conducts my legal case and actually executes justice for me. He will bring me forth to the light; I shall look upon his righteousness.

[[v33-7-10]]

^<<v33-7-10,10>>^ And my enemy will see, and shame will cover her, who was saying to me: “Where is he, Jehovah your God?” My own eyes will look upon her. Now she will become a place of trampling, like the mire of streets.

[[v33-7-11]]

^<<v33-7-11,11>>^ The day for building your^&#42;1^ stone walls, at that day &#91;the&#93; decree^&#42;2^ will be far away.

[NOTE]
====
. “Your,” fem. sing.
. Or, “prescribed limit.”
====

[[v33-7-12]]

^<<v33-7-12,12>>^ At that day even all the way to you they^&#42;1^ will come from As·syrʹi·a and the cities of Egypt,^&#42;2^ and from Egypt even all the way to &#91;the&#93; River; and from sea to sea, and &#91;from&#93; mountain to the mountain.

[NOTE]
====
. “They,” LXX; MSyVg, “he,” or “one.”
. “Egypt.” Heb., Ma·tsohrʹ.
====

[[v33-7-13]]

^<<v33-7-13,13>>^ And the land must become a desolate waste on account of its inhabitants, because of the fruit of their dealings.

[[v33-7-14]]

^<<v33-7-14,14>>^ Shepherd your^&#42;1^ people with your staff, the flock of your inheritance, the one who was residing alone in a forest—in the midst of an orchard. Let them feed on Baʹshan and Gilʹe·ad as in the days of a long time ago.

[NOTE]
====
. “Your,” masc. sing.
====

[[v33-7-15]]

^<<v33-7-15,15>>^ “As in the days of your coming forth from the land of Egypt I shall show him wonderful things.

[[v33-7-16]]

^<<v33-7-16,16>>^ Nations will see and become ashamed of all their mightiness. They will put &#91;their&#93; hand upon &#91;their&#93; mouth; their very ears will become deaf.

[[v33-7-17]]

^<<v33-7-17,17>>^ They will lick up dust like the serpents; like reptiles of &#91;the&#93; earth they will come in agitation out of their bulwarks. To Jehovah our God^&#42;1^ they will come quivering, and they will be afraid of you.”

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu.
====

[[v33-7-18]]

^<<v33-7-18,18>>^ Who is a God^&#42;1^ like you, one pardoning error and passing over transgression of the remnant of his inheritance? He will certainly not hold onto his anger forever, for he is delighting in loving-kindness.^&#42;2^

[NOTE]
====
. “God.” Heb., ʼEl; Gr., The·osʹ; Lat., Deʹus.
. Or, “loyal love.” Heb., cheʹsedh.
====

[[v33-7-19]]

^<<v33-7-19,19>>^ He will again show us mercy; he will subject our errors. And you will throw into the depths of &#91;the&#93; sea all their^&#42;1^ sins.

[NOTE]
====
. “Their,” M; LXXSyVg, “our”; T, “Israel’s.”
====

[[v33-7-20]]

^<<v33-7-20,20>>^ You will give &#91;the&#93; trueness &#91;given&#93; to Jacob, &#91;the&#93; loving-kindness &#91;given&#93; to Abraham, which you swore to our forefathers from the days of long ago.

'''

xref:033-micah/033-micah-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-nahum/034-nahum-001.adoc#v34-1-0[Próximo Capítulo &#62;]