include::./index.adoc[]

[[v33-4-0]]
=== Micah, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-4-1]]

^<<v33-4-1,1>>^ And it must occur in the final part of the days &#91;that&#93; the mountain of the house of Jehovah will become firmly established above the top of the mountains, and it will certainly be lifted up above the hills; and to it peoples must stream.

[[v33-4-2]]

^<<v33-4-2,2>>^ And many nations will certainly go and say: “Come, YOU people, and let us go up to the mountain of Jehovah and to the house of the God of Jacob; and he will instruct us about his ways, and we will walk^&#42;1^ in his paths.” For out of Zion law will go forth, and the word of Jehovah out of Jerusalem.

[NOTE]
====
. Or, “go.”
====

[[v33-4-3]]

^<<v33-4-3,3>>^ And he will certainly render judgment among many peoples, and set matters straight respecting mighty nations far away. And they will have to beat their swords into plowshares and their spears into pruning shears. They will not lift up sword, nation against nation, neither will they learn war anymore.

[[v33-4-4]]

^<<v33-4-4,4>>^ And they will actually sit,^&#42;1^ each one^&#42;2^ under his vine and under his fig tree, and there will be no one making &#91;them&#93; tremble; for the very mouth of Jehovah^&#42;3^ of armies^&#42;4^ has spoken &#91;it&#93;.

[NOTE]
====
. Or, “dwell.”
. “Each one.” Heb., ʼish.
. See App 1C §2.
. “Jehovah of armies,” MTVg; LXX, “Jehovah Almighty.”
====

[[v33-4-5]]

^<<v33-4-5,5>>^ For all the peoples, for their part, will walk each one in the name of its god;^&#42;1^ but we, for our part, shall walk in the name of Jehovah^&#42;2^ our God^&#42;3^ to time indefinite, even forever.^&#42;4^

[NOTE]
====
. Or, “its gods.” Heb., ʼelo·havʹ; Syr., ʼa·la·heh; Lat., deʹi.
. See App 1C §2.
. “Our God.” Heb., ʼElo·hehʹnu; Gr., The·ouʹ; Lat., Deʹi.
. Or, “forever and ever.” See Ex 15:18.
====

[[v33-4-6]]

^<<v33-4-6,6>>^ “In that day,” is the utterance of Jehovah, “I will gather her that was limping; and her that was dispersed I will collect together, even her whom I have treated badly.

[[v33-4-7]]

^<<v33-4-7,7>>^ And I shall certainly make her that was limping a remnant, and her that was removed far off a mighty nation; and Jehovah^&#42;1^ will actually rule as king over them in Mount Zion, from now on and into time indefinite.

[NOTE]
====
. See App 1C §2.
====

[[v33-4-8]]

^<<v33-4-8,8>>^ “And as for you,^&#42;1^ O tower of the drove,^&#42;2^ the mound^&#42;3^ of the daughter of Zion, as far as to you it will come, yes, the first^&#42;4^ dominion will certainly come, the kingdom belonging to the daughter of Jerusalem.

[NOTE]
====
. “You,” masc. sing.
. Or, “of Eder.” Compare Ge 35:21, where “the tower of Eder” occurs.
. Heb., ʽoʹphel, that is, a hill, or an eminence. Compare 2Ki 5:24 ftn.
. Or, “former.”
====

[[v33-4-9]]

^<<v33-4-9,9>>^ “Now why is it that you^&#42;1^ keep shouting loudly? Is there no king in you, or has your own counselor perished, so that pangs like those of a woman giving birth have grabbed hold of you?

[NOTE]
====
. “You,” fem. sing.
====

[[v33-4-10]]

^<<v33-4-10,10>>^ Be in severe pains and burst forth, O daughter of Zion, like a woman giving birth, for now you will go forth from a town, and you will have to reside in the field. And you will have to come as far as to Babylon.^&#42;1^ There you will be delivered. There Jehovah will buy you back out of the palm of your enemies.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v33-4-11]]

^<<v33-4-11,11>>^ “And now there will certainly be gathered against you many nations, those who are saying, ‘Let her be polluted, and may our eyes look upon Zion.’

[[v33-4-12]]

^<<v33-4-12,12>>^ But as for them, they have not come to know the thoughts of Jehovah, and they have not come to understand his counsel; because he will certainly collect them together like a row of newly cut grain to the threshing floor.

[[v33-4-13]]

^<<v33-4-13,13>>^ “Get up and thresh, O daughter of Zion; for your horn I shall change into iron, and your hoofs I shall change into copper, and you will certainly pulverize many peoples; and by a ban you will actually devote to Jehovah their unjust profit, and their resources to the &#91;true&#93; Lord^&#42;1^ of the whole earth.”

[NOTE]
====
. “To the [true] Lord.” Ca(Heb.), לָאֲדוֹן (la·ʼAdhohnʹ); Leningrad B 19A(Heb.), לַאֲדוֹן (la·ʼAdhohnʹ); Gr., Ky·riʹoi; Syr., leMa·raʼ; Lat., Doʹmi·no. See App 1H.
====

'''

xref:033-micah/033-micah-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-micah/033-micah-005.adoc#v33-5-0[Próximo Capítulo &#62;]