include::./index.adoc[]

[[v33-1-0]]
=== Micah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v33-1-1]]

^<<v33-1-1,1>>^ The word of Jehovah^&#42;1^ that occurred to Miʹcah of Moʹresh·eth,^&#42;2^ in the days of Joʹtham, Aʹhaz, Hez·e·kiʹah, kings of Judah, that he visioned concerning Sa·marʹi·a and Jerusalem:

[NOTE]
====
. See App 1C §2.
. Or, “the Morashtite.”
====

[[v33-1-2]]

^<<v33-1-2,2>>^ “Hear, O YOU peoples, all of YOU; pay attention, O earth and what fills you, and let the Sovereign Lord Jehovah serve against YOU as a witness, Jehovah^&#42;1^ from his holy temple.^&#42;2^

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. “From his holy temple.” Heb., me·heh·khalʹ qodh·shohʹ; Lat., temʹplo sancʹto. See Mt 23:16 ftn.
====

[[v33-1-3]]

^<<v33-1-3,3>>^ For, look! Jehovah^&#42;1^ is going forth from his place, and he will certainly come down and tread upon earth’s high places.

[NOTE]
====
. See App 1C §2.
====

[[v33-1-4]]

^<<v33-1-4,4>>^ And the mountains must melt under him, and the low plains themselves will split apart, like wax because of the fire, like waters being poured down a steep place.

[[v33-1-5]]

^<<v33-1-5,5>>^ “It is because of the revolt of Jacob that there is all this, even because of the sins of the house of Israel. What is the revolt of Jacob? Is it not Sa·marʹi·a? And what are the high places^&#42;1^ of Judah? Are they not Jerusalem?

[NOTE]
====
. “The high places,” MVg; LXX, “the sin of the house”; Sy, “the sin.”
====

[[v33-1-6]]

^<<v33-1-6,6>>^ And I shall certainly make Sa·marʹi·a a heap of ruins of the field, the planting places of a vineyard; and I will pour down into the valley her stones, and her foundations I shall lay bare.

[[v33-1-7]]

^<<v33-1-7,7>>^ And her graven images will all be crushed to pieces, and all the gifts &#91;made&#93; to her as her hire will be burned in the fire; and all her idols I shall make a desolate waste. For from the things given as the hire of a prostitute she collected &#91;them&#93;, and to the thing given as the hire of a prostitute they will return.”

[[v33-1-8]]

^<<v33-1-8,8>>^ On this account I will wail and howl; I will walk barefoot and naked. I shall make a wailing like the jackals, and a mourning like female ostriches.^&#42;1^

[NOTE]
====
. “Female ostriches.” Lit., “daughters of an ostrich.”
====

[[v33-1-9]]

^<<v33-1-9,9>>^ For the stroke^&#42;1^ upon her is unhealable; for it has come as far as Judah, &#91;the&#93; plague as far as the gate of my people, as far as Jerusalem.

[NOTE]
====
. “Stroke,” LXXSyVg; M, “strokes.”
====

[[v33-1-10]]

^<<v33-1-10,10>>^ “In Gath do not YOU men tell &#91;it&#93; out; positively do not weep.
“In the house of Aphʹrah wallow in the very dust.

[[v33-1-11]]

^<<v33-1-11,11>>^ Make your way across, O inhabitress of Shaʹphir, in shameful nudity. The inhabitress of Zaʹa·nan has not gone forth. The wailing of Beth-eʹzel will take from YOU people its standing place.

[[v33-1-12]]

^<<v33-1-12,12>>^ For the inhabitress of Maʹroth has waited for good, but what is bad has come down from Jehovah to the gate of Jerusalem.

[[v33-1-13]]

^<<v33-1-13,13>>^ Attach the chariot to the team of horses, O inhabitress of Laʹchish. The beginning of sin was what she was to the daughter of Zion, for in you^&#42;1^ the revolts of Israel have been found.

[NOTE]
====
. “You,” fem. sing.
====

[[v33-1-14]]

^<<v33-1-14,14>>^ Therefore you will give parting gifts to Moʹresh·eth-gath. The houses of Achʹzib were as something deceitful to the kings of Israel.

[[v33-1-15]]

^<<v33-1-15,15>>^ The dispossessor^&#42;1^ I shall yet bring to you, O inhabitress of Ma·reʹshah. As far as A·dulʹlam the glory of Israel will come.

[NOTE]
====
. Or, “The one taking possession.”
====

[[v33-1-16]]

^<<v33-1-16,16>>^ Cause baldness, and shear &#91;your hair&#93; off on account of your sons of exquisite delight. Broaden out your baldness like &#91;that of&#93; the eagle, because they have gone away from you into exile.”

'''

xref:032-jonah/032-jonah-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-micah/033-micah-002.adoc#v33-2-0[Próximo Capítulo &#62;]