include::./index.adoc[]

[[v23-43-0]]
=== Isaiah, 43
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-43-1]]

^<<v23-43-1,1>>^ And now this is what Jehovah has said, your Creator, O Jacob, and your Former, O Israel: “Do not be afraid, for I have repurchased you. I have called &#91;you&#93; by your name. You are mine.

[[v23-43-2]]

^<<v23-43-2,2>>^ In case you should pass through the waters, I will be with you; and through the rivers, they will not flood over you. In case you should walk through the fire, you will not be scorched, neither will the flame itself singe you.

[[v23-43-3]]

^<<v23-43-3,3>>^ For I am Jehovah your God,^&#42;1^ the Holy One of Israel your Savior. I have given Egypt as a ransom for you,^&#42;2^ E·thi·oʹpi·a^&#42;3^ and Seʹba in place of you.

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
. Or, “atonement price for you.” Lit., “your covering.” Heb., khoph·rekhaʹ.
. “Ethiopia,” LXXVg; MTSy, “Cush.”
====

[[v23-43-4]]

^<<v23-43-4,4>>^ Owing to the fact that you have been precious in my eyes, you have been considered honorable, and I myself have loved you. And I shall give men^&#42;1^ in place of you, and national groups in place of your soul.

[NOTE]
====
. Lit., “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-43-5]]

^<<v23-43-5,5>>^ “Do not be afraid, for I am with you. From the sunrising I shall bring your seed, and from the sunset I shall collect you together.

[[v23-43-6]]

^<<v23-43-6,6>>^ I shall say to the north, ‘Give up!’ and to the south,^&#42;1^ ‘Do not keep back. Bring my sons from far off, and my daughters from the extremity of the earth,

[NOTE]
====
. Or, “and toward Teman.” Heb., u·letheh·manʹ.
====

[[v23-43-7]]

^<<v23-43-7,7>>^ everyone that is called by my name and that I have created for my own glory, that I have formed, yes, that I have made.’

[[v23-43-8]]

^<<v23-43-8,8>>^ “Bring forth a people blind though eyes themselves exist, and the ones deaf though they have ears.

[[v23-43-9]]

^<<v23-43-9,9>>^ Let the nations all be collected together^&#42;1^ at one place, and let national groups be gathered together. Who is there among them that can tell this? Or can they cause us to hear even the first things? Let them furnish their witnesses, that they may be declared righteous, or let them hear and say, ‘It is the truth!’”^&#42;2^

[NOTE]
====
. In agreement with TSy; MLXX, “All the nations have collected themselves together.”
. “It is the truth!” Lit., “Truth!” Heb., ʼemethʹ.
====

[[v23-43-10]]

^<<v23-43-10,10>>^ “YOU are my witnesses,”^&#42;1^ is the utterance of Jehovah, “even my servant^&#42;2^ whom I have chosen, in order that YOU may know and have faith in me, and that YOU may understand that I am the same One. Before me there was no God^&#42;3^ formed, and after me there continued to be none.^&#42;4^

[NOTE]
====
. “You are my witnesses.” Heb., ʼat·temʹ ʽe·dhaiʹ, pl.; Lat., vos teʹstes meʹi.
. “Even my servant,” M(Heb., weʽav·diʹ, sing.)LXXVg; T(Aram.), we·ʽav·dhiʹ me·shi·chaʼʹ, “even my servant, the anointed”; Sy, “servants.”
. “God.” Heb., ʼEl.
. Or, “and after me there came [or, will come] to be none.”
====

[[v23-43-11]]

^<<v23-43-11,11>>^ I—I am Jehovah, and besides me there is no savior.”

[[v23-43-12]]

^<<v23-43-12,12>>^ “I myself have told forth and have saved and have caused &#91;it&#93; to be heard, when there was among YOU no strange &#91;god&#93;.^&#42;1^ So YOU are my witnesses,” is the utterance of Jehovah, “and I am God.^&#42;2^

[NOTE]
====
. Or, “no stranger.”
. “God.” Heb., ʼEl.
====

[[v23-43-13]]

^<<v23-43-13,13>>^ Also, all the time^&#42;1^ I am the same One; and there is no one effecting deliverance out of my own hand. I shall get active, and who can turn it^&#42;2^ back?”

[NOTE]
====
. Lit., “from [the] day.” LXXVg, “from the beginning.”
. “It,” fem., referring to “hand,” fem.
====

[[v23-43-14]]

^<<v23-43-14,14>>^ This is what Jehovah has said, the Repurchaser of YOU people, the Holy One of Israel: “For YOUR sakes I will send to Babylon and cause the bars of the prisons^&#42;1^ to come down, and the Chal·deʹans in the ships with whining cries on their part.

[NOTE]
====
. “The bars of the prisons,” by a correction; M, “the bars, all of them”; Vg, “all the bars (barriers).”
====

[[v23-43-15]]

^<<v23-43-15,15>>^ I am Jehovah YOUR Holy One,^&#42;1^ the Creator of Israel, YOUR King.”

[NOTE]
====
. Or, “I, Jehovah, am your Holy One.” Heb., ʼaniʹ Yehwahʹ Qedho·shekhemʹ.
====

[[v23-43-16]]

^<<v23-43-16,16>>^ This is what Jehovah has said, the One making a way through the sea itself and a roadway even through strong waters,

[[v23-43-17]]

^<<v23-43-17,17>>^ the One bringing forth the war chariot and the horse, the military force and the strong ones^&#42;1^ at the same time: “They will lie down. They will not get up. They will certainly be extinguished. Like a flaxen wick they must be put out.”

[NOTE]
====
. Lit., “and the strong one,” sing. but in a collective sense.
====

[[v23-43-18]]

^<<v23-43-18,18>>^ “Do not remember the first things, and to the former things do not turn YOUR consideration.

[[v23-43-19]]

^<<v23-43-19,19>>^ Look! I am doing something new. Now it will spring up. YOU people will know it, will YOU not? Really, through the wilderness I shall set a way, through the desert rivers.

[[v23-43-20]]

^<<v23-43-20,20>>^ The wild beast of the field will glorify me, the jackals and the ostriches;^&#42;1^ because I shall have given water even in the wilderness, rivers in the desert, to cause my people, my chosen one, to drink,

[NOTE]
====
. Lit., “daughters of an ostrich.”
====

[[v23-43-21]]

^<<v23-43-21,21>>^ the people whom I have formed for myself, that they should recount the praise of me.

[[v23-43-22]]

^<<v23-43-22,22>>^ “But you have not called even me, O Jacob, because you have grown weary of me, O Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ You have not brought me the sheep of your whole burnt offerings, and with your sacrifices you have not glorified me. I have not compelled you to serve me with a gift, nor have I made you weary with frankincense.

[[v23-43-24]]

^<<v23-43-24,24>>^ For me you have bought no &#91;sweet&#93; cane with any money;^&#42;1^ and with the fat of your sacrifices you have not saturated me. In reality you have compelled me to serve because of your sins; you have made me weary with your errors.

[NOTE]
====
. Or, “silver.”
====

[[v23-43-25]]

^<<v23-43-25,25>>^ “I—I am the One that is wiping out your transgressions for my own sake, and your sins I shall not remember.

[[v23-43-26]]

^<<v23-43-26,26>>^ Remind me; let us put ourselves on judgment^&#42;1^ together; tell your own account of it in order that you may be in the right.

[NOTE]
====
. Or, “let us enter into controversy; let us plead.”
====

[[v23-43-27]]

^<<v23-43-27,27>>^ Your own father, the first one, has sinned, and your own spokesmen^&#42;1^ have transgressed against me.

[NOTE]
====
. Or, “interpreters.”
====

[[v23-43-28]]

^<<v23-43-28,28>>^ So I shall profane the princes of the holy place,^&#42;1^ and I will give Jacob over as a man devoted to destruction and Israel over to words of abuse.

[NOTE]
====
. Or, “profane the holy princes.”
====

'''

xref:023-isaiah/023-isaiah-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaiah/023-isaiah-044.adoc#v23-44-0[Próximo Capítulo &#62;]