include::./index.adoc[]

[[v23-39-0]]
=== Isaiah, 39
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-39-1]]

^<<v23-39-1,1>>^ At that time Merʹo·dach-balʹa·dan the son of Balʹa·dan the king of Babylon^&#42;1^ sent letters and a gift to Hez·e·kiʹah, after he heard that he had been sick but was strong again.

[NOTE]
====
. “Babylon,” Vg; LXX, “Babylonia”; MTSy, “Babel.”
====

[[v23-39-2]]

^<<v23-39-2,2>>^ So Hez·e·kiʹah began to rejoice over them and proceeded to show them his treasure-house, the silver and the gold and the balsam oil and the good oil and all his armory and all that was to be found in his treasures. There proved to be nothing that Hez·e·kiʹah did not show them in his own house and in all his dominion.

[[v23-39-3]]

^<<v23-39-3,3>>^ After that Isaiah the prophet came in to King Hez·e·kiʹah and said to him: “What did these men say, and from where did they proceed to come to you?” So Hez·e·kiʹah said: “From a distant land they came to me, from Babylon.”

[[v23-39-4]]

^<<v23-39-4,4>>^ And he went on to say: “What did they see in your house?” To this Hez·e·kiʹah said: “Everything that is in my house they saw. There proved to be nothing that I did not show them in my treasures.”

[[v23-39-5]]

^<<v23-39-5,5>>^ Isaiah now said to Hez·e·kiʹah: “Hear the word of Jehovah of armies,

[[v23-39-6]]

^<<v23-39-6,6>>^ ‘Look! Days are coming, and all that is in your own house and that your forefathers have stored up down to this day will actually be carried to Babylon.’ ‘Nothing will be left,’ Jehovah has said.

[[v23-39-7]]

^<<v23-39-7,7>>^ ‘And some of your own sons that will come forth from you, to whom you will become father, will themselves be taken and actually become court officials in the palace of the king of Babylon.’”

[[v23-39-8]]

^<<v23-39-8,8>>^ At that Hez·e·kiʹah said to Isaiah: “The word of Jehovah that you have spoken is good.” And he went on to say: “Because peace and truth will continue in my own days.”

'''

xref:023-isaiah/023-isaiah-038.adoc#v23-38-0[&#60; Capítulo Anterior] | <<v23-39-0,Topo>> | xref:023-isaiah/023-isaiah-040.adoc#v23-40-0[Próximo Capítulo &#62;]