include::./index.adoc[]

[[v23-62-0]]
=== Isaiah, 62
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-62-1]]

^<<v23-62-1,1>>^ For the sake of Zion I shall not keep still, and for the sake of Jerusalem I shall not stay quiet until her righteousness goes forth just like the brightness, and her salvation like a torch that burns.

[[v23-62-2]]

^<<v23-62-2,2>>^ “And the nations will certainly see your^&#42;1^ righteousness, &#91;O woman,&#93;^&#42;2^ and all kings your glory. And you will actually be called by a new name, which the very mouth of Jehovah will designate.

[NOTE]
====
. “Your,” fem. sing.
. “O woman,” inserted because “your” is fem. sing. and refers to “Jerusalem.”
====

[[v23-62-3]]

^<<v23-62-3,3>>^ And you must become a crown of beauty in the hand of Jehovah, and a kingly turban in the palm of your God.^&#42;1^

[NOTE]
====
. “Your God.” Heb., ʼElo·haʹyikh.
====

[[v23-62-4]]

^<<v23-62-4,4>>^ No more will you be said to be a woman left entirely; and your own land will no more be said to be desolate; but you yourself will be called My Delight Is in Her,^&#42;1^ and your land Owned as a Wife.^&#42;2^ For Jehovah will have taken delight in you, and your own land will be owned as a wife.

[NOTE]
====
. “My Delight Is in Her.” Or, “Hephzibah.” Heb., Cheph·tsi-vahʹ.
. Or, “Owned by a Husband.” Or, “Beulah.” Heb., Beʽu·lahʹ.
====

[[v23-62-5]]

^<<v23-62-5,5>>^ For just as a young man takes ownership of a virgin as his wife, your sons will take ownership of you as a wife. And with the exultation of a bridegroom over a bride, your God will exult even over you.

[[v23-62-6]]

^<<v23-62-6,6>>^ Upon your walls, O Jerusalem, I have commissioned watchmen. All day long and all night long, constantly, let them not keep still.
“YOU who are making mention of Jehovah, let there be no silence on YOUR part,

[[v23-62-7]]

^<<v23-62-7,7>>^ and do not give him any silence until he fixes solidly, yes, until he sets Jerusalem as a praise in the earth.”

[[v23-62-8]]

^<<v23-62-8,8>>^ Jehovah has sworn with his right hand and with his strong arm: “I will no more give your^&#42;1^ grain as food to your enemies, nor will foreigners^&#42;2^ drink your new wine, for which you have toiled.

[NOTE]
====
. “Your,” fem. sing., addressed to Zion, or Jerusalem.
. Lit., “sons of a foreign (country).”
====

[[v23-62-9]]

^<<v23-62-9,9>>^ But the very ones gathering it will eat it, and they will be certain to praise Jehovah; and the very ones collecting it will drink it in my holy courtyards.”

[[v23-62-10]]

^<<v23-62-10,10>>^ Pass out, pass out through the gates, YOU men. Clear the way of the people. Bank up, bank up the highway. Rid &#91;it&#93; of stones. Raise up a signal^&#42;1^ for the peoples.

[NOTE]
====
. “Signal.” Heb., nes; Lat., siʹgnum.
====

[[v23-62-11]]

^<<v23-62-11,11>>^ Look! Jehovah himself has caused &#91;it&#93; to be heard to the farthest part^&#42;1^ of the earth: “Say, YOU people, to the daughter of Zion, ‘Look! Your salvation is coming. Look! The reward he gives is with him, and the wages he pays are before him.’”

[NOTE]
====
. See Jer 25:31, 33 ftns.
====

[[v23-62-12]]

^<<v23-62-12,12>>^ And men will certainly call them the holy people, those repurchased by Jehovah; and you yourself will be called Searched For,^&#42;1^ a City Not Left Entirely.

[NOTE]
====
. “Searched For.” Heb., Dheru·shahʹ, fem. sing.
====

'''

xref:023-isaiah/023-isaiah-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaiah/023-isaiah-063.adoc#v23-63-0[Próximo Capítulo &#62;]