include::./index.adoc[]

[[v23-26-0]]
=== Isaiah, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-26-1]]

^<<v23-26-1,1>>^ In that day this song will be sung in the land of Judah: “We have a strong city. He sets salvation itself for walls and rampart.

[[v23-26-2]]

^<<v23-26-2,2>>^ Open the gates, YOU men, that the righteous nation that is keeping faithful conduct may enter.

[[v23-26-3]]

^<<v23-26-3,3>>^ The inclination that is well supported^&#42;1^ you will safeguard in continuous peace,^&#42;2^ because it is in you that one^&#42;3^ is made to trust.

[NOTE]
====
. Or, “that is unshakable.”
. Lit., “[in] peace, peace.”
. Or, “it.”
====

[[v23-26-4]]

^<<v23-26-4,4>>^ Trust in Jehovah, YOU people, for all times, for in Jah^&#42;1^ Jehovah^&#42;2^ is the Rock of times indefinite.

[NOTE]
====
. See 12:2 ftn, “Jah.”
. “In Jah Jehovah.” Heb., beYahʹ Yehwahʹ. See 12:2 ftn, “Jehovah.”
====

[[v23-26-5]]

^<<v23-26-5,5>>^ “For he has laid low those inhabiting the height, the elevated town. He abases it, he abases it to the earth; he brings it in touch with the dust.

[[v23-26-6]]

^<<v23-26-6,6>>^ The foot will trample it down, the feet of the afflicted one, the steps of the lowly ones.”

[[v23-26-7]]

^<<v23-26-7,7>>^ The path of the righteous one is uprightness. You being upright, you will smooth out the very course of a righteous one.

[[v23-26-8]]

^<<v23-26-8,8>>^ Yes, for the path of your judgments, O Jehovah, we have hoped in you. For your name and for your memorial the desire of the soul has been.

[[v23-26-9]]

^<<v23-26-9,9>>^ With my soul I have desired you in the night; yes, with my spirit within me I keep looking for you; because, when there are judgments from you for the earth, righteousness is what the inhabitants of the productive land^&#42;1^ will certainly learn.

[NOTE]
====
. See 13:11 ftn, “Land.”
====

[[v23-26-10]]

^<<v23-26-10,10>>^ Though the wicked one should be shown favor, he simply will not learn righteousness. In the land of straightforwardness he will act unjustly and will not see the eminence of Jehovah.

[[v23-26-11]]

^<<v23-26-11,11>>^ O Jehovah, your hand has become high, &#91;but&#93; they do not behold &#91;it&#93;. They will behold and be ashamed at the zeal for &#91;your&#93; people. Yes, the very fire for your own adversaries will eat them up.^&#42;1^

[NOTE]
====
. “And now fire will consume those in opposition,” LXX. Compare Heb 10:27.
====

[[v23-26-12]]

^<<v23-26-12,12>>^ O Jehovah, you will adjudge peace to us, because even all our works you have performed for us.

[[v23-26-13]]

^<<v23-26-13,13>>^ O Jehovah our God,^&#42;1^ other masters^&#42;2^ besides you have acted as owners of us. By you only shall we make mention of your name.

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu, pl.
. “Masters.” Heb., ʼadho·nimʹ, pl. of ʼa·dhohnʹ.
====

[[v23-26-14]]

^<<v23-26-14,14>>^ They are dead; they will not live. Impotent in death,^&#42;1^ they will not rise up. Therefore you have turned your attention that you might annihilate them and destroy all mention of them.

[NOTE]
====
. “Impotent in death.” Heb., repha·ʼimʹ; Vg, “Giants.”
====

[[v23-26-15]]

^<<v23-26-15,15>>^ You have added to the nation; O Jehovah, you have added to the nation; you have glorified yourself. You have extended afar all the borders of the land.^&#42;1^

[NOTE]
====
. Or, “earth.” Heb., ʼaʹrets.
====

[[v23-26-16]]

^<<v23-26-16,16>>^ O Jehovah, during distress they have turned their attention to you; they have poured out a whisper &#91;of prayer&#93; when they had your disciplining.

[[v23-26-17]]

^<<v23-26-17,17>>^ Just as a pregnant woman draws near to giving birth, has labor pains, cries out in her birth pangs, so we have become because of you, O Jehovah.

[[v23-26-18]]

^<<v23-26-18,18>>^ We have become pregnant, we have had labor pains; as it were, we have given birth to wind.^&#42;1^ No real salvation do we accomplish as regards the land, and no inhabitants for the productive land proceed to fall &#91;in birth&#93;.

[NOTE]
====
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v23-26-19]]

^<<v23-26-19,19>>^ “Your dead ones will live. A corpse of mine^&#42;1^—they will rise up. Awake and cry out joyfully, YOU residents in the dust! For your dew is as the dew of mallows, and the earth itself will let even those impotent in death^&#42;2^ drop &#91;in birth&#93;.

[NOTE]
====
. “A corpse of mine.” Heb., neve·la·thiʹ, sing. but likely in a collective sense, “Corpses of mine”; LXX, “Those in the memorial tombs”; Vg, “My killed ones.”
. See vs 14 ftn.
====

[[v23-26-20]]

^<<v23-26-20,20>>^ “Go, my people, enter into your interior rooms, and shut your doors behind you. Hide yourself for but a moment until the denunciation passes over.

[[v23-26-21]]

^<<v23-26-21,21>>^ For, look! Jehovah is coming forth from his place to call to account the error of the inhabitant of the land against him, and the land will certainly expose her bloodshed^&#42;1^ and will no longer cover over her killed ones.”

[NOTE]
====
. Lit., “bloods.”
====

'''

xref:023-isaiah/023-isaiah-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaiah/023-isaiah-027.adoc#v23-27-0[Próximo Capítulo &#62;]