include::./index.adoc[]

[[v23-65-0]]
=== Isaiah, 65
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-65-1]]

^<<v23-65-1,1>>^ “I have let myself be searched for by those who had not asked &#91;for me&#93;.^&#42;1^ I have let myself be found by those who had not looked for me.^&#42;2^ I have said, ‘Here I am, here I am!’ to a nation that was not calling^&#42;3^ upon my name.

[NOTE]
====
. “For me,” LXXSy and three Heb. mss.
. “I became manifest to those who were not seeking me,” LXX. See Ro 10:20.
. “Calling,” by a slight change of vowel pointing in agreement with TSyVg; M, “called.”
====

[[v23-65-2]]

^<<v23-65-2,2>>^ “I have spread out my hands all day long to a stubborn people, those who are walking in the way that is not good, after their thoughts;

[[v23-65-3]]

^<<v23-65-3,3>>^ the people &#91;made up of&#93; those offending me right to my face constantly, sacrificing in the gardens and making sacrificial smoke upon the bricks,^&#42;1^

[NOTE]
====
. Possibly the pavement of the place for offering sacrifice or else roof tiles.
====

[[v23-65-4]]

^<<v23-65-4,4>>^ seating themselves among the burial places, who also pass the night even in the watch huts,^&#42;1^ eating the flesh of the pig, even the broth of foul things being in their vessels;

[NOTE]
====
. “Even among the rocks,” by a correction; LXXSy, “in the caves.”
====

[[v23-65-5]]

^<<v23-65-5,5>>^ those who are saying, ‘Keep close to yourself. Do not approach me, for I shall certainly convey holiness to you.’^&#42;1^ These are a smoke in my nostrils, a fire burning all day long.^&#42;2^

[NOTE]
====
. Or, “I have become holy toward you.”
. “As for these, their anger is as a smoke before me; their punishment shall be in Gehinnam (Gehenna) where the fire burns all the day,” TO. See App 4C.
====

[[v23-65-6]]

^<<v23-65-6,6>>^ “Look! It is written before me. I shall not keep still, but I will render a reward; I will even render the reward into their own bosom,^&#42;1^

[NOTE]
====
. “But I will render to them the punishment of their transgressions and will deliver their bodies to the second death,” TO.
====

[[v23-65-7]]

^<<v23-65-7,7>>^ for their^&#42;1^ own errors and for the errors of their forefathers at the same time,” Jehovah has said. “Because they have made sacrificial smoke upon the mountains, and upon the hills they have reproached me, I will also measure out their wages first of all into their own bosom.”

[NOTE]
====
. “Their,” AqLXXSymThSy; MTVg, “your.”
====

[[v23-65-8]]

^<<v23-65-8,8>>^ This is what Jehovah has said: “In the same way that the new wine is found in the cluster and someone has to say, ‘Do not ruin it, because there is a blessing in it,’ so I shall do for the sake of my servants^&#42;1^ in order not to bring everybody to ruin.

[NOTE]
====
. “Servants,” MTSyVg; LXX and seven Heb. mss, “servant.”
====

[[v23-65-9]]

^<<v23-65-9,9>>^ And I will bring forth out of Jacob an offspring^&#42;1^ and out of Judah the hereditary possessor of my mountains; and my chosen ones must take possession of it,^&#42;2^ and my own servants will reside there.

[NOTE]
====
. Lit., “seed.”
. Or, “her,” fem. sing., referring to the hereditary possession.
====

[[v23-65-10]]

^<<v23-65-10,10>>^ And Sharʹon must become a pasture ground for sheep and the low plain of Aʹchor a resting-place for cattle, for my people who will have looked for me.

[[v23-65-11]]

^<<v23-65-11,11>>^ “But YOU men are those leaving Jehovah, those forgetting my holy mountain, those setting in order a table for the god of Good Luck^&#42;1^ and those filling up mixed wine for the god of Destiny.^&#42;2^

[NOTE]
====
. “For the god of Good Luck.” Heb., lag·gadhʹ; LXX, “the demon”; Lat., For·tuʹnae. Compare Ge 30:11 ftns.
. Or, “for the god of Fate.” Heb., lam·niʹ; Gr., tei tyʹkhei.
====

[[v23-65-12]]

^<<v23-65-12,12>>^ And I will destine YOU men to the sword, and YOU will all of YOU bow down to being slaughtered; for the reason that I called, but YOU did not answer; I spoke, but YOU did not listen; and YOU kept doing what was bad in my eyes, and the thing in which I took no delight YOU chose.”

[[v23-65-13]]

^<<v23-65-13,13>>^ Therefore this is what the Sovereign Lord Jehovah has said: “Look! My own servants will eat, but YOU yourselves will go hungry. Look! My own servants will drink, but YOU yourselves will go thirsty. Look! My own servants will rejoice, but YOU yourselves will suffer shame.

[[v23-65-14]]

^<<v23-65-14,14>>^ Look! My own servants will cry out joyfully because of the good condition of the heart, but YOU yourselves will make outcries because of the pain of heart and YOU will howl because of sheer breakdown of spirit.

[[v23-65-15]]

^<<v23-65-15,15>>^ And YOU men will certainly lay up YOUR name for an oath^&#42;1^ by my chosen ones, and the Sovereign Lord Jehovah will actually put &#91;YOU&#93; individually^&#42;2^ to death,^&#42;3^ but his own servants he will call by another name;

[NOTE]
====
. That is, a curse.
. “[YOU] individually.” Lit., “you,” masc. sing., to show individuality.
. “To death,” M; T, “to death with the second death.”
====

[[v23-65-16]]

^<<v23-65-16,16>>^ so that anyone blessing himself in the earth will bless himself by the God^&#42;1^ of faith,^&#42;2^ and anyone making a sworn statement in the earth will swear by the God of faith; because the former distresses will actually be forgotten and because they will actually be concealed from my eyes.

[NOTE]
====
. “By the God of.” Heb., bEʼ·lo·hehʹ.
. Or, “faithfulness,” by a change of vowel pointing to read ʼe·munʹ; Heb., ʼa·menʹ, “Amen; Surely!”
====

[[v23-65-17]]

^<<v23-65-17,17>>^ “For here I am creating new heavens and a new earth; and the former things will not be called to mind, neither will they come up into the heart.

[[v23-65-18]]

^<<v23-65-18,18>>^ But exult, YOU people, and be joyful forever in what I am creating. For here I am creating Jerusalem a cause for joyfulness and her people a cause for exultation.

[[v23-65-19]]

^<<v23-65-19,19>>^ And I will be joyful in Jerusalem and exult in my people; and no more will there be heard in her the sound of weeping or the sound of a plaintive cry.”

[[v23-65-20]]

^<<v23-65-20,20>>^ “No more will there come to be a suckling a few days old from that place, neither an old man that does not fulfill his days; for one will die as a mere boy, although a hundred years of age; and as for the sinner, although a hundred years of age he will have evil called down upon him.

[[v23-65-21]]

^<<v23-65-21,21>>^ And they will certainly build houses and have occupancy; and they will certainly plant vineyards and eat &#91;their&#93; fruitage.

[[v23-65-22]]

^<<v23-65-22,22>>^ They will not build and someone else have occupancy; they will not plant and someone else do the eating. For like the days of a tree will the days of my people be; and the work of their own hands my chosen ones will use to the full.

[[v23-65-23]]

^<<v23-65-23,23>>^ They will not toil for nothing, nor will they bring to birth for disturbance; because they are the offspring made up of the blessed ones of Jehovah, and their descendants with them.

[[v23-65-24]]

^<<v23-65-24,24>>^ And it will actually occur that before they call out I myself shall answer; while they are yet speaking, I myself shall hear.

[[v23-65-25]]

^<<v23-65-25,25>>^ “The wolf and the lamb themselves will feed as one, and the lion will eat straw just like the bull; and as for the serpent, his food will be dust. They will do no harm nor cause any ruin in all my holy mountain,” Jehovah has said.

'''

xref:023-isaiah/023-isaiah-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaiah/023-isaiah-066.adoc#v23-66-0[Próximo Capítulo &#62;]