include::./index.adoc[]

[[v23-58-0]]
=== Isaiah, 58
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-58-1]]

^<<v23-58-1,1>>^ “Call out full-throated; do not hold back. Raise your voice just like a horn,^&#42;1^ and tell my people their revolt, and the house of Jacob their sins.

[NOTE]
====
. Or, “shofar.”
====

[[v23-58-2]]

^<<v23-58-2,2>>^ Yet day after day it was I whom they kept seeking, and it was in the knowledge of my ways that they would express delight, like a nation that carried on righteousness itself and that had not left the very justice of their God, in that they kept asking me for righteous judgments, drawing near to God^&#42;1^ in whom they had delight,

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

[[v23-58-3]]

^<<v23-58-3,3>>^ “‘For what reason did we fast and you did not see, and did we afflict our soul and you would take no note?’
“Indeed YOU people were finding delight in the very day of YOUR fasting, when there were all YOUR toilers that YOU kept driving to work.

[[v23-58-4]]

^<<v23-58-4,4>>^ Indeed for quarreling and struggle YOU would fast, and for striking with the fist of wickedness. Did YOU not keep fasting as in the day for making YOUR voice to be heard in the height?

[[v23-58-5]]

^<<v23-58-5,5>>^ Should the fast that I choose become like this, as a day for earthling man to afflict his soul? For bowing down his head just like a rush, and that he should spread out mere sackcloth and ashes as his couch? Is it this that you call a fast and a day acceptable to Jehovah?

[[v23-58-6]]

^<<v23-58-6,6>>^ “Is not this the fast that I choose? To loosen the fetters of wickedness, to release the bands of the yoke bar, and to send away the crushed ones free, and that YOU people should tear in two every yoke bar?

[[v23-58-7]]

^<<v23-58-7,7>>^ Is it not the dividing of your bread out to the hungry one, and that you should bring the afflicted, homeless people into &#91;your&#93; house? That, in case you should see someone naked, you must cover him, and that you should not hide yourself from your own flesh?

[[v23-58-8]]

^<<v23-58-8,8>>^ “In that case your light would break forth just like the dawn; and speedily would recuperation spring up for you. And before you your righteousness would certainly walk; the very glory of Jehovah would be your rear guard.

[[v23-58-9]]

^<<v23-58-9,9>>^ In that case you would call, and Jehovah himself would answer; you would cry for help, and he would say, ‘Here I am!’
“If you will remove from your midst the yoke bar, the poking out of the finger and the speaking of what is hurtful;

[[v23-58-10]]

^<<v23-58-10,10>>^ and you will grant to the hungry one your own soul&#91;ful desire&#93;, and you will satisfy the soul that is being afflicted, your light also will certainly flash up even in the darkness, and your gloom will be like midday.

[[v23-58-11]]

^<<v23-58-11,11>>^ And Jehovah will be bound to lead you constantly and to satisfy your soul even in a scorched land, and he will invigorate your very bones; and you must become like a well-watered garden, and like the source of water, the waters of which do not lie.

[[v23-58-12]]

^<<v23-58-12,12>>^ And at your instance men will^&#42;1^ certainly build up the places devastated a long time;^&#42;2^ you will raise up even the foundations of continuous generations. And you will actually be called the repairer of &#91;the&#93; gap, the restorer of roadways by which to dwell.^&#42;3^

[NOTE]
====
. “And your sons will,” by a correction.
. Or, “devastated for time indefinite.”
. Or, “roadways to [one’s] dwelling,” that is, homeward.
====

[[v23-58-13]]

^<<v23-58-13,13>>^ “If in view of the sabbath you will turn back your foot as regards doing your own delights on my holy day, and will actually call the sabbath an exquisite delight, a holy &#91;day&#93; of Jehovah, one being glorified, and will actually glorify it rather than doing your own ways, rather than finding what delights you and speaking a word;

[[v23-58-14]]

^<<v23-58-14,14>>^ you will in that case find your exquisite delight in Jehovah, and I will make you ride upon the high places of the earth; and I will cause you to eat from the hereditary possession of Jacob your forefather, for the mouth of Jehovah itself has spoken &#91;it&#93;.”

'''

xref:023-isaiah/023-isaiah-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaiah/023-isaiah-059.adoc#v23-59-0[Próximo Capítulo &#62;]