include::./index.adoc[]

[[v23-29-0]]
=== Isaiah, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-29-1]]

^<<v23-29-1,1>>^ “Woe to Arʹi·el,^&#42;1^ to Arʹi·el, the town where David encamped! Add year upon year, YOU people; let the festivals run the round.

[NOTE]
====
. Possibly meaning “The Altar Hearth of God”; or, “The Lion of God,” referring to Jerusalem.
====

[[v23-29-2]]

^<<v23-29-2,2>>^ And I have to make things tight for Arʹi·el, and there must come to be mourning and lamentation, and she must become to me as the altar hearth of God.^&#42;1^

[NOTE]
====
. Or, “as Ariel.”
====

[[v23-29-3]]

^<<v23-29-3,3>>^ And I must encamp on all sides against you,^&#42;1^ and I must lay siege to you with a palisade^&#42;2^ and raise up against you siegeworks.

[NOTE]
====
. “You,” fem. sing., referring to the town.
. Or, “sentries; outposts.”
====

[[v23-29-4]]

^<<v23-29-4,4>>^ And you must become low so that you will speak from the very earth, and as from the dust your saying will sound low. And like a spirit medium your voice must become even from the earth, and from the dust your own saying will chirp.

[[v23-29-5]]

^<<v23-29-5,5>>^ And the crowd of those strange to you must become just like fine powder, and the crowd of the tyrants just like the chaff that is passing away. And it must occur in an instant, suddenly.

[[v23-29-6]]

^<<v23-29-6,6>>^ From Jehovah of armies you will have attention with thunder and with quaking and with a great sound, storm wind and tempest, and the flame of a devouring fire.”

[[v23-29-7]]

^<<v23-29-7,7>>^ And it must occur just as in a dream, in a vision of the night, regarding the crowd of all the nations that are waging war against Arʹi·el, even all those waging war against her, and the siege towers against her and those making things tight for her.

[[v23-29-8]]

^<<v23-29-8,8>>^ Yes, it must occur just as when someone hungry dreams and here he is eating, and he actually awakes and his soul is empty; and just as when someone thirsty dreams and here he is drinking, and he actually awakes and here he is tired and his soul is dried out; thus it will occur with the crowd of all the nations that are waging war against Mount Zion.

[[v23-29-9]]

^<<v23-29-9,9>>^ Linger, YOU men, and be amazed; blind yourselves, and be blinded.^&#42;1^ They have become intoxicated, but not with wine; they have moved unsteadily, but not because of intoxicating liquor.

[NOTE]
====
. Lit., “smear yourselves over, and be smeared over.” Compare 6:10, “paste their very eyes together.”
====

[[v23-29-10]]

^<<v23-29-10,10>>^ For upon YOU men Jehovah has poured a spirit of deep sleep; and he closes YOUR eyes, the prophets, and he has covered even YOUR heads, the visionaries.

[[v23-29-11]]

^<<v23-29-11,11>>^ And for YOU men the vision of everything becomes like the words of the book that has been sealed up, which they give to someone knowing the writing, saying: “Read this out loud, please,” and he has to say: “I am unable, for it is sealed up”;

[[v23-29-12]]

^<<v23-29-12,12>>^ and the book must be given to someone that does not know writing, &#91;somebody&#93; saying: “Read this out loud, please,” and he has to say: “I do not know writing at all.”

[[v23-29-13]]

^<<v23-29-13,13>>^ And Jehovah^&#42;1^ says: “For the reason that this people have come near with their mouth, and they have glorified me merely with their lips, and they have removed their heart itself far away from me, and their fear toward me becomes men’s commandment that is being taught,

[NOTE]
====
. One of 134 scrib­al changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-29-14]]

^<<v23-29-14,14>>^ therefore here I am, the One that will act wonderfully again with this people, in a wonderful manner and with something wonderful; and the wisdom of their wise men must perish, and the very understanding of their discreet men will conceal itself.”

[[v23-29-15]]

^<<v23-29-15,15>>^ Woe to those who are going very deep in concealing counsel from Jehovah himself, and whose deeds have occurred in a dark place, while they say: “Who is seeing us, and who is knowing of us?”

[[v23-29-16]]

^<<v23-29-16,16>>^ The perversity of YOU men! Should the potter^&#42;1^ himself be accounted just like the clay? For should the thing made say respecting its maker: “He did not make me”? And does the very thing formed actually say respecting its former: “He showed no understanding”?

[NOTE]
====
. Lit., “former.”
====

[[v23-29-17]]

^<<v23-29-17,17>>^ Is it not yet but a very little time and Lebʹa·non must be turned into an orchard and the orchard itself will be accounted just as a forest?

[[v23-29-18]]

^<<v23-29-18,18>>^ And in that day the deaf ones will certainly hear the words of the book, and out of the gloom and out of the darkness even the eyes of the blind ones will see.

[[v23-29-19]]

^<<v23-29-19,19>>^ And the meek ones will certainly increase their rejoicing in Jehovah himself, and even the poor ones of mankind^&#42;1^ will be joyful in the Holy One of Israel himself,

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-29-20]]

^<<v23-29-20,20>>^ because the tyrant must reach his end, and the bragger must come to his finish, and all those keeping alert to do harm must be cut off,

[[v23-29-21]]

^<<v23-29-21,21>>^ those bringing a man into sin by &#91;his&#93; word, and those who lay bait even for the one reproving in the gate, and those who push aside the righteous one with empty arguments.

[[v23-29-22]]

^<<v23-29-22,22>>^ Therefore this is what Jehovah has said to the house of Jacob, he that redeemed Abraham: “Jacob will not now be ashamed, nor will his own face now grow pale;

[[v23-29-23]]

^<<v23-29-23,23>>^ for when he sees his children, the work of my hands, in the midst of him, they will sanctify^&#42;1^ my name, and they will certainly sanctify the Holy One of Jacob, and the God of Israel^&#42;2^ they will regard with awe.

[NOTE]
====
. “They will sanctify.” Heb., yaq·diʹshu; Gr., ha·gi·aʹsou·sin; Lat., sanc·ti·fi·canʹtes.
. “God of Israel.” Heb., ʼElo·hehʹ Yis·ra·ʼelʹ.
====

[[v23-29-24]]

^<<v23-29-24,24>>^ And those who are erring in &#91;their&#93; spirit will actually get to know understanding, and even those who are grumbling will learn instruction.”

'''

xref:023-isaiah/023-isaiah-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaiah/023-isaiah-030.adoc#v23-30-0[Próximo Capítulo &#62;]