include::./index.adoc[]

[[v23-1-0]]
=== Isaiah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-1-1]]

^<<v23-1-1,1>>^ The vision of Isaiah^&#42;1^ the son of Aʹmoz^&#42;2^ that he visioned concerning Judah and Jerusalem in the days of Uz·ziʹah,^&#42;3^ Joʹtham,^&#42;4^ Aʹhaz^&#42;5^ &#91;and&#93; Hez·e·kiʹah,^&#42;6^ kings of Judah:

[NOTE]
====
. “Isaiah.” Heb., Yesha·ʽeyaʹhu, meaning “Salvation of Jehovah”; LXXBagster(Gr.), He·sa·iʹas; Lat., I·sa·iʹas.
. Meaning “Strong.” Heb., ʼA·mohtsʹ.
. Meaning “My Strength Is Jehovah.” Heb., ʽUz·zi·yaʹhu.
. Meaning “Jehovah Is Perfect”; or, “May Jehovah Complete.” Heb., Yoh·thamʹ.
. Meaning “He [Jehovah] Has Taken Hold.” Heb., ʼA·chazʹ.
. Meaning “Jehovah Strengthens.” Heb., Yechiz·qi·yaʹhu.
====

[[v23-1-2]]

^<<v23-1-2,2>>^ Hear, O heavens, and give ear, O earth, for Jehovah himself has spoken: “Sons I have brought up and raised, but they themselves have revolted^&#42;1^ against me.

[NOTE]
====
. Or, “transgressed.”
====

[[v23-1-3]]

^<<v23-1-3,3>>^ A bull well knows its buyer, and the ass the manger of its owner;^&#42;1^ Israel itself has not known, my own people have not behaved understandingly.”

[NOTE]
====
. “Its owner.” Heb., beʽa·lavʹ, a pl. form of baʹʽal, to denote excellence.
====

[[v23-1-4]]

^<<v23-1-4,4>>^ Woe to the sinful nation, the people heavy with error, an evildoing seed, ruinous sons! They have left Jehovah, they have treated the Holy One of Israel with disrespect, they have turned backwards.

[[v23-1-5]]

^<<v23-1-5,5>>^ Where else will YOU be struck still more, in that YOU add more revolt? The whole head is in a sick condition, and the whole heart is feeble.

[[v23-1-6]]

^<<v23-1-6,6>>^ From the sole of the foot even to the head there is no sound spot in it. Wounds and bruises and fresh stripes—they have not been squeezed out or bound up, nor has there been a softening with oil.

[[v23-1-7]]

^<<v23-1-7,7>>^ YOUR land is a desolation, YOUR cities are burned with fire; YOUR ground—right in front of YOU strangers are eating it up, and the desolation is like an overthrow by strangers.

[[v23-1-8]]

^<<v23-1-8,8>>^ And the daughter of Zion has been left remaining like a booth in a vineyard, like a lookout hut in a field of cucumbers, like a blockaded city.

[[v23-1-9]]

^<<v23-1-9,9>>^ Unless Jehovah of armies himself had left remaining to us just a few survivors, we should have become^&#42;1^ just like Sodʹom, we should have resembled Go·morʹrah itself.

[NOTE]
====
. Or, “left over to us survivors, we should easily have become.”
====

[[v23-1-10]]

^<<v23-1-10,10>>^ Hear the word of Jehovah, YOU dictators of Sodʹom. Give ear to the law of our God, YOU people of Go·morʹrah.

[[v23-1-11]]

^<<v23-1-11,11>>^ “Of what benefit to me is the multitude of YOUR sacrifices?” says Jehovah. “I have had enough of whole burnt offerings of rams and the fat of well-fed animals; and in the blood of young bulls and male lambs and he-goats I have taken no delight.

[[v23-1-12]]

^<<v23-1-12,12>>^ When YOU people keep coming in to see my face, who is it that has required this from YOUR hand, to trample my courtyards?

[[v23-1-13]]

^<<v23-1-13,13>>^ Stop bringing in any more valueless grain offerings. Incense—it is something detestable to me. New moon and sabbath, the calling of a convention^&#42;1^—I cannot put up with the &#91;use of&#93; uncanny power^&#42;2^ along with the solemn assembly.

[NOTE]
====
. Or, “convocation.”
. “Uncanny power, state of taboo,” KB, p. 20; LXX, “fasting.”
====

[[v23-1-14]]

^<<v23-1-14,14>>^ YOUR new moons and YOUR festal seasons my soul has hated. To me they have become a burden; I have become tired of bearing &#91;them&#93;.

[[v23-1-15]]

^<<v23-1-15,15>>^ And when YOU spread out YOUR palms, I hide my eyes from YOU. Even though YOU make many prayers, I am not listening; with bloodshed^&#42;1^ YOUR very hands have become filled.

[NOTE]
====
. Or, “bloodguilt.” Lit., “bloods.”
====

[[v23-1-16]]

^<<v23-1-16,16>>^ Wash yourselves; make yourselves clean; remove the badness of YOUR dealings from in front of my eyes; cease to do bad.

[[v23-1-17]]

^<<v23-1-17,17>>^ Learn to do good; search for justice; set right the oppressor; render judgment for the fatherless boy; plead the cause of the widow.”

[[v23-1-18]]

^<<v23-1-18,18>>^ “Come, now, YOU people, and let us set matters straight between us,” says Jehovah. “Though the sins of YOU people should prove to be as scarlet,^&#42;1^ they will be made white just like snow; though they should be red like crimson cloth, they will become even like wool.

[NOTE]
====
. Lit., “scarlet pieces.”
====

[[v23-1-19]]

^<<v23-1-19,19>>^ If YOU people show willingness and do listen, the good of the land^&#42;1^ YOU will eat.

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v23-1-20]]

^<<v23-1-20,20>>^ But if YOU people refuse and are actually rebellious, with a sword YOU will be eaten up; for the very mouth of Jehovah has spoken &#91;it&#93;.”

[[v23-1-21]]

^<<v23-1-21,21>>^ O how the faithful town^&#42;1^ has become a prostitute! She was full of justice;^&#42;2^ righteousness itself used to lodge in her, but now murderers.

[NOTE]
====
. LXXIt add “Zion.”
. Or, “judgment.” Heb., mish·patʹ.
====

[[v23-1-22]]

^<<v23-1-22,22>>^ Your^&#42;1^ silver itself has become scummy dross. Your wheat beer^&#42;2^ is diluted with water.

[NOTE]
====
. “Your,” fem. sing., addressed to Zion, the once “faithful town,” in vs 21.
. Or, “Your liquor.”
====

[[v23-1-23]]

^<<v23-1-23,23>>^ Your princes are stubborn and partners with thieves. Every one of them is a lover of a bribe and a chaser after gifts. For a fatherless boy they do not render judgment; and even the legal case of a widow does not get admittance to them.

[[v23-1-24]]

^<<v23-1-24,24>>^ Therefore the utterance of the &#91;true&#93; Lord,^&#42;1^ Jehovah of armies, the Powerful One of Israel, is: “Aha! I shall relieve myself of my adversaries, and I will avenge myself on my enemies.

[NOTE]
====
. “The [true] Lord.” Heb., ha·ʼA·dhohnʹ; Gr., ho De·spoʹtes. See App 1H.
====

[[v23-1-25]]

^<<v23-1-25,25>>^ And I will turn back my hand upon^&#42;1^ you,^&#42;2^ and I shall smelt away your scummy dross as with lye, and I will remove all your waste products.

[NOTE]
====
. Or, “against.”
. “You,” fem. sing. Compare vs 22 ftn, “Your.”
====

[[v23-1-26]]

^<<v23-1-26,26>>^ And I will bring back again judges for you as at the first, and counselors for you as at the start. After this you will be called City of Righteousness, Faithful Town.

[[v23-1-27]]

^<<v23-1-27,27>>^ With justice^&#42;1^ Zion herself will be redeemed, and those returning of her, with righteousness.

[NOTE]
====
. Or, “judgment.”
====

[[v23-1-28]]

^<<v23-1-28,28>>^ And the crash of revolters and that of sinful ones will be at the same time, and those leaving Jehovah will come to their finish.

[[v23-1-29]]

^<<v23-1-29,29>>^ For they will be ashamed of the mighty trees that YOU people desired, and YOU will be abashed because of the gardens that YOU have chosen.

[[v23-1-30]]

^<<v23-1-30,30>>^ For YOU will become like a big tree the foliage of which is withering, and like a garden that has no water.

[[v23-1-31]]

^<<v23-1-31,31>>^ And the vigorous man will certainly become tow, and the product of his activity a spark; and both of them will certainly go up in flames at the same time, with no one to do the extinguishing.”

'''

xref:022-song-of-solomon/022-song-of-solomon-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaiah/023-isaiah-002.adoc#v23-2-0[Próximo Capítulo &#62;]