include::./index.adoc[]

[[v23-9-0]]
=== Isaiah, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-9-1]]

^<<v23-9-1,1>>^ However, the obscureness will not be as when the land^&#42;1^ had stress, as at the former time when one treated with contempt the land of Zebʹu·lun and the land of Naphʹta·li and when at the later time one caused &#91;it&#93; to be honored—the way by the sea, in the region of the Jordan, Galʹi·lee^&#42;2^ of the nations.^&#42;3^

[NOTE]
====
. Lit., “it,” fem., that is, the land or earth.
. Or, “the circuit.” Heb., Gelilʹ; Syr., Geli·lo; Gr., Ga·li·laiʹa; Lat., Ga·li·leʹae. “Galilee” later designated the Roman province north of Samaria.
. MLXX end chapter 8 here with this as vs 23.
====

[[v23-9-2]]

^<<v23-9-2,2>>^ The people that were walking in the darkness have seen a great light. As for those dwelling in the land of deep shadow, light itself has shone upon them.

[[v23-9-3]]

^<<v23-9-3,3>>^ You have made the nation populous; for it^&#42;1^ you have made the rejoicing great. They have rejoiced before you as with the rejoicing in the harvesttime, as those who are joyful when they divide up the spoil.

[NOTE]
====
. “For it,” MmarginTSy and about 20 Heb. mss.
====

[[v23-9-4]]

^<<v23-9-4,4>>^ For the yoke of their load and the rod upon their shoulders, the staff of the one driving them to work, you have shattered to pieces as in the day of Midʹi·an.

[[v23-9-5]]

^<<v23-9-5,5>>^ For every boot of the one tramping with tremors^&#42;1^ and the mantle rolled in blood^&#42;2^ have even come to be for burning as food for fire.

[NOTE]
====
. Or, “rattling; pounding.”
. Lit., “bloods.”
====

[[v23-9-6]]

^<<v23-9-6,6>>^ For there has been a child born to us, there has been a son given to us; and the princely rule^&#42;1^ will come to be upon his shoulder. And his name will be called Wonderful Counselor,^&#42;2^ Mighty God,^&#42;3^ Eternal Father,^&#42;4^ Prince of Peace.^&#42;5^

[NOTE]
====
. Or, “the princedom; the rule as prince.” Heb., ham·mis·rahʹ; Gr., he ar·kheʹ; Lat., prin·ci·paʹtus.
. Lit., “Wonder (Miracle) of a Counselor,” or, “Wonder, Counselor,” M; LXX, “The Angel of Grand Counsel”; Sy, “Wonder and Counselor.”
. Or, “Mighty Divine One.” Heb., ʼEl Gib·bohrʹ (not ʼEl Shad·daiʹ as in Ge 17:1, where see ftn); Sy, “Mighty God of times indefinite”; Lat., Deʹus forʹtis.
. Or, “Father Forever.” Heb., ʼAvi·ʽadhʹ.
. Or, “Peaceable Prince,” that is, a prince giving peace.
====

[[v23-9-7]]

^<<v23-9-7,7>>^ To the abundance of the princely rule^&#42;1^ and to peace there will be no end,^&#42;2^ upon the throne of David and upon his kingdom in order to establish it^&#42;3^ firmly and to sustain it by means of justice and by means of righteousness, from now on and to time indefinite. The very zeal of Jehovah of armies will do this.

[NOTE]
====
. “The princely rule.” Heb., ham·mis·rahʹ. Here and in vs 6 are the only occurrences of this expression.
. Or, “His princely rule will certainly abound, and there will be no end to peace,” if a dittography in M; LXX agrees.
. “It,” fem., referring to “kingdom.”
====

[[v23-9-8]]

^<<v23-9-8,8>>^ There was a word that Jehovah^&#42;1^ sent against Jacob, and it fell upon Israel.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-9-9]]

^<<v23-9-9,9>>^ And the people will certainly know &#91;it&#93;, even all of them, Eʹphra·im and the inhabitant of Sa·marʹi·a, because of &#91;their&#93; haughtiness and because of &#91;their&#93; insolence of heart in saying:

[[v23-9-10]]

^<<v23-9-10,10>>^ “Bricks are what have fallen, but with hewn stone we shall build. Sycamore trees are what have been cut down, but with cedars we shall make replacement.”

[[v23-9-11]]

^<<v23-9-11,11>>^ And Jehovah will set the adversaries of Reʹzin on high against him, and the enemies of that one he will goad on,

[[v23-9-12]]

^<<v23-9-12,12>>^ Syria from the east and the Phi·lisʹtines from behind, and they will eat up Israel with open mouth. In view of all this his anger has not turned back, but his hand is stretched out still.

[[v23-9-13]]

^<<v23-9-13,13>>^ And the people themselves have not returned to the One striking them, and Jehovah of armies they have not sought.

[[v23-9-14]]

^<<v23-9-14,14>>^ And Jehovah will cut off from Israel head and tail, shoot and rush, in one day.

[[v23-9-15]]

^<<v23-9-15,15>>^ The aged and highly respected one^&#42;1^ is the head, and the prophet giving false instruction is the tail.

[NOTE]
====
. Lit., “one lifted up as to face.”
====

[[v23-9-16]]

^<<v23-9-16,16>>^ And those who are leading this people on prove to be the ones causing &#91;them&#93; to wander; and those of them who are being led on, the ones who are being confused.

[[v23-9-17]]

^<<v23-9-17,17>>^ That is why Jehovah^&#42;1^ will not rejoice even over their young men, and upon their fatherless boys and upon their widows he will have no mercy; because all of them are apostates and evildoers and every mouth is speaking senselessness. In view of all this his anger has not turned back, but his hand is stretched out still.

[NOTE]
====
. See vs 8 ftn.
====

[[v23-9-18]]

^<<v23-9-18,18>>^ For wickedness has become aflame just like a fire; thornbushes and weeds it will eat up. And it will catch fire in the thickets of the forest, and they will be borne aloft as the billowing of smoke.

[[v23-9-19]]

^<<v23-9-19,19>>^ In the fury of Jehovah of armies the land has been set afire,^&#42;1^ and the people will become as food for the fire. No one will show compassion even on his brother.

[NOTE]
====
. “Has been set afire,” by a correction of M in agreement with TLXX; by another correction, “has been led astray,” similar to Vg.
====

[[v23-9-20]]

^<<v23-9-20,20>>^ And one will cut down on the right and will certainly be hungry; and one will eat on the left, and they will certainly not be satisfied. They will each one eat the flesh of his own arm,

[[v23-9-21]]

^<<v23-9-21,21>>^ Ma·nasʹseh Eʹphra·im, and Eʹphra·im Ma·nasʹseh. Together they will be against Judah. In view of all this his anger has not turned back, but his hand is stretched out still.

'''

xref:023-isaiah/023-isaiah-008.adoc#v23-8-0[&#60; Capítulo Anterior] | <<v23-9-0,Topo>> | xref:023-isaiah/023-isaiah-010.adoc#v23-10-0[Próximo Capítulo &#62;]