include::./index.adoc[]

[[v23-10-0]]
=== Isaiah, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-10-1]]

^<<v23-10-1,1>>^ Woe to those who are enacting harmful regulations and those who, constantly writing, have written out sheer trouble,

[[v23-10-2]]

^<<v23-10-2,2>>^ in order to push away the lowly ones from a legal case and to wrest away justice from the afflicted ones of my people, for the widows to become their spoil, and that they may plunder even the fatherless boys!

[[v23-10-3]]

^<<v23-10-3,3>>^ And what will YOU men do at the day of being given attention and at the ruin, when it comes from far away? Toward whom will YOU flee for assistance, and where will YOU leave YOUR glory,

[[v23-10-4]]

^<<v23-10-4,4>>^ except it be that one must bow down under the prisoners and that people keep falling under those who have been killed? In view of all this his anger has not turned back, but his hand is stretched out still.

[[v23-10-5]]

^<<v23-10-5,5>>^ “Aha, the As·syrʹi·an, the rod for my anger, and the stick that is in their hand for my denunciation!

[[v23-10-6]]

^<<v23-10-6,6>>^ Against an apostate nation I shall send him, and against the people of my fury I shall issue a command to him, to take much spoil and to take much plunder^&#42;1^ and to make it^&#42;2^ a trampling place like the clay of the streets.

[NOTE]
====
. Lit., “to spoil a spoil and to plunder a plunder.”
. “It,” masc., referring to the “nation” or “people.”
====

[[v23-10-7]]

^<<v23-10-7,7>>^ Though he may not be that way, he will feel inclined; though his heart may not be that way, he will scheme, because to annihilate is in his heart, and to cut off nations not a few.

[[v23-10-8]]

^<<v23-10-8,8>>^ For he will say, ‘Are not my princes at the same time kings?

[[v23-10-9]]

^<<v23-10-9,9>>^ Is not Calʹno just like Carʹche·mish? Is not Haʹmath just like Arʹpad? Is not Sa·marʹi·a just like Damascus?

[[v23-10-10]]

^<<v23-10-10,10>>^ Whenever my hand has reached the kingdoms of the valueless god whose graven images are more than those at Jerusalem and at Sa·marʹi·a,

[[v23-10-11]]

^<<v23-10-11,11>>^ will it not be that just as I shall have done to Sa·marʹi·a and to her valueless gods, even so I shall do to Jerusalem and to her idols?’

[[v23-10-12]]

^<<v23-10-12,12>>^ “And it must occur that when Jehovah^&#42;1^ terminates all his work in Mount Zion and in Jerusalem, I shall make an accounting for the fruitage of the insolence of the heart of the king of As·syrʹi·a and for the self-importance of his loftiness of eyes.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-10-13]]

^<<v23-10-13,13>>^ For he has said, ‘With the power of my hand I shall certainly act, and with my wisdom, for I do have understanding; and I shall remove the boundaries of peoples, and their things stored up I shall certainly pillage, and I shall bring down the inhabitants just like a powerful one.

[[v23-10-14]]

^<<v23-10-14,14>>^ And just as if a nest, my hand will reach the resources of the peoples; and just as when one gathers eggs that have been left, I myself will gather up even all the earth, and there will certainly be no one fluttering &#91;his&#93; wings or opening &#91;his&#93; mouth or chirping.’”

[[v23-10-15]]

^<<v23-10-15,15>>^ Will the ax enhance itself over the one chopping with it, or the saw magnify itself over the one moving it back and forth, as though the staff moved back and forth the ones^&#42;1^ raising it on high, as though the rod raised on high the one who is not wood?

[NOTE]
====
. Or, “the Grand One,” pl. in Heb., possibly to denote the grandeur of an individual.
====

[[v23-10-16]]

^<<v23-10-16,16>>^ Therefore the &#91;true&#93; Lord,^&#42;1^ Jehovah of armies, will keep sending upon his fat ones a wasting disease, and under his glory a burning will keep burning away like the burning of a fire.

[NOTE]
====
. “The [true] Lord.” Heb., ha·ʼA·dhohnʹ; Lat., Do·mi·naʹtor. See App 1H.
====

[[v23-10-17]]

^<<v23-10-17,17>>^ And Israel’s Light must become a fire, and his Holy One a flame; and it must blaze up and eat up his weeds and his thornbushes in one day.

[[v23-10-18]]

^<<v23-10-18,18>>^ And the glory of his forest and of his orchard He will bring to an end, even from the soul clear to the flesh, and it must become like the melting away of one that is ailing.^&#42;1^

[NOTE]
====
. “That is faltering,” according to a different root of the verb.
====

[[v23-10-19]]

^<<v23-10-19,19>>^ And the rest^&#42;1^ of the trees of his forest—they will become such a number that a mere boy will be able to write them down.

[NOTE]
====
. Or, “the remnant.” Compare 7:3 ftn.
====

[[v23-10-20]]

^<<v23-10-20,20>>^ And it will certainly occur in that day that those remaining over of Israel and those who have escaped^&#42;1^ of the house of Jacob will never again support themselves upon the one striking them, and they will certainly support themselves upon Jehovah, the Holy One of Israel, in trueness.^&#42;2^

[NOTE]
====
. Or, “the escaped part.”
. “In trueness (truth).” Heb., be·ʼemethʹ.
====

[[v23-10-21]]

^<<v23-10-21,21>>^ A mere remnant^&#42;1^ will return,^&#42;2^ the remnant of Jacob, to the Mighty God.^&#42;3^

[NOTE]
====
. Or, “Those remaining over,” as in vs 20.
. “A mere remnant will return.” Heb., sheʼarʹ ya·shuvʹ, the same Heb. expression as the name “Shear-jashub” in 7:3, where see ftn.
. “The Mighty God.” Heb., ʼEl Gib·bohrʹ. See 9:6 ftn, “God.”
====

[[v23-10-22]]

^<<v23-10-22,22>>^ For although your people, O Israel, would prove to be like the grains of sand of the sea, a mere remnant^&#42;1^ among them will return. An extermination decided upon will be flooding through in righteousness,

[NOTE]
====
. Or, “those remaining over,” as in vs 20.
====

[[v23-10-23]]

^<<v23-10-23,23>>^ because an exterminating and a strict decision the Sovereign Lord, Jehovah of armies, will be executing in the midst of the whole land.^&#42;1^

[NOTE]
====
. Or, “earth.”
====

[[v23-10-24]]

^<<v23-10-24,24>>^ Therefore this is what the Sovereign Lord, Jehovah of armies, has said: “Do not be afraid, O my people who are dwelling in Zion, because of the As·syrʹi·an, who with the rod used to strike &#91;you&#93; and who used to lift up his own staff against you in the way that Egypt did.

[[v23-10-25]]

^<<v23-10-25,25>>^ For yet a very little while—and the denunciation will have come to an end, and my anger, in their wearing away.

[[v23-10-26]]

^<<v23-10-26,26>>^ And Jehovah of armies will certainly brandish against him a whip as at the defeat of Midʹi·an by the rock Oʹreb; and his staff will be upon the sea, and he will certainly lift it up in the way that he did with Egypt.

[[v23-10-27]]

^<<v23-10-27,27>>^ “And it must occur in that day that his load will depart from upon your shoulder, and his yoke from upon your neck, and the yoke will certainly be wrecked because of the oil.”^&#42;1^

[NOTE]
====
. Possibly oil as used for the torches of Gideon’s 300 men; or oil with which the kings of Israel were anointed.
====

[[v23-10-28]]

^<<v23-10-28,28>>^ He has come upon Aiʹath; he has passed along through Migʹron; at Michʹmash he deposits his articles.

[[v23-10-29]]

^<<v23-10-29,29>>^ They have passed over the ford,^&#42;1^ Geʹba is a place for them to spend the night, Raʹmah has trembled, Gibʹe·ah of Saul itself has fled.

[NOTE]
====
. Or, “crossing; passage.”
====

[[v23-10-30]]

^<<v23-10-30,30>>^ Let your voice out in shrill cries, O daughter of Galʹlim. Pay attention, O Laʹi·shah. O you afflicted one, Anʹa·thoth!

[[v23-10-31]]

^<<v23-10-31,31>>^ Mad·meʹnah has run away. The inhabitants of Geʹbim themselves have taken to shelter.

[[v23-10-32]]

^<<v23-10-32,32>>^ It is yet day in Nob to make a halt. He waves his hand^&#42;1^ &#91;threateningly&#93; at the mountain of the daughter of Zion, the hill of Jerusalem.

[NOTE]
====
. Or, “shakes the fist.”
====

[[v23-10-33]]

^<<v23-10-33,33>>^ Look! The &#91;true&#93; Lord,^&#42;1^ Jehovah of armies, is lopping off boughs with a terrible crash; and those tall in growth are being cut down, and the high ones themselves become low.

[NOTE]
====
. See App 1H.
====

[[v23-10-34]]

^<<v23-10-34,34>>^ And he has struck down the thickets of the forest with an iron tool, and by a powerful one Lebʹa·non itself will fall.

'''

xref:023-isaiah/023-isaiah-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaiah/023-isaiah-011.adoc#v23-11-0[Próximo Capítulo &#62;]