include::./index.adoc[]

[[v23-25-0]]
=== Isaiah, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-25-1]]

^<<v23-25-1,1>>^ O Jehovah, you are my God.^&#42;1^ I exalt you, I laud your name, for you have done wonderful things, counsels from early times, in faithfulness, in trustworthiness.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v23-25-2]]

^<<v23-25-2,2>>^ For you have made a city a pile of stones, a fortified town a crumbling ruin, a dwelling tower of strangers to be no city, which will not be rebuilt even to time indefinite.

[[v23-25-3]]

^<<v23-25-3,3>>^ That is why those who are a strong people will glorify you; the town of the tyrannical nations, they will fear you.

[[v23-25-4]]

^<<v23-25-4,4>>^ For you have become a stronghold to the lowly one, a stronghold to the poor one in the distress that he has, a refuge from the rainstorm,^&#42;1^ a shade from the heat, when the blast^&#42;2^ of the tyrannical ones is like a rainstorm against a wall.

[NOTE]
====
. “You will deliver them from wicked men,” LXX. Compare 2Th 3:2.
. Or, “spirit.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. See Ge 1:2 ftn, “Force.”
====

[[v23-25-5]]

^<<v23-25-5,5>>^ Like the heat in a waterless country, the noise of strangers you subdue, the heat with the shadow of a cloud. The melody itself of the tyrannical ones becomes suppressed.

[[v23-25-6]]

^<<v23-25-6,6>>^ And Jehovah of armies will certainly make for all the peoples, in this mountain, a banquet of well-oiled dishes, a banquet of &#91;wine kept on&#93; the dregs, of well-oiled dishes filled with marrow, of &#91;wine kept on&#93; the dregs, filtered.

[[v23-25-7]]

^<<v23-25-7,7>>^ And in this mountain he will certainly swallow up the face of the envelopment that is enveloping over all the peoples, and the woven work that is interwoven upon all the nations.

[[v23-25-8]]

^<<v23-25-8,8>>^ He will actually swallow up death forever, and the Sovereign Lord Jehovah will certainly wipe the tears from all faces. And the reproach of his people he will take away from all the earth,^&#42;1^ for Jehovah himself has spoken &#91;it&#93;.

[NOTE]
====
. Or, “the land.” Heb., ha·ʼaʹrets.
====

[[v23-25-9]]

^<<v23-25-9,9>>^ And in that day one will certainly say: “Look! This is our God.^&#42;1^ We have hoped in him, and he will save us. This is Jehovah. We have hoped in him. Let us be joyful and rejoice in the salvation by him.”^&#42;2^

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu.
. Lit., “in his salvation.”
====

[[v23-25-10]]

^<<v23-25-10,10>>^ For the hand of Jehovah will settle down on this mountain, and Moʹab must be trodden down in its place as when a straw heap is trodden down in a manure place.

[[v23-25-11]]

^<<v23-25-11,11>>^ And he must slap out^&#42;1^ his hands in the midst of it^&#42;2^ as when a swimmer slaps &#91;them&#93; out to swim, and he must abase its haughtiness with the tricky movements of his hands.

[NOTE]
====
. Lit., “stretch out.”
. Or, “him,” that is, “Moab.”
====

[[v23-25-12]]

^<<v23-25-12,12>>^ And the fortified city, with your high walls of security, he must lay low; he must abase &#91;it&#93;, bring &#91;it&#93; into contact with the earth, to the dust.

'''

xref:023-isaiah/023-isaiah-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaiah/023-isaiah-026.adoc#v23-26-0[Próximo Capítulo &#62;]