include::./index.adoc[]

[[v23-14-0]]
=== Isaiah, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-14-1]]

^<<v23-14-1,1>>^ For Jehovah will show mercy to Jacob, and he is yet certain to choose Israel; and he will actually give them rest upon their soil, and the alien resident^&#42;1^ must be joined to them, and they must attach themselves to the house of Jacob.

[NOTE]
====
. Or, “the temporary resident.” Heb., hag·gerʹ.
====

[[v23-14-2]]

^<<v23-14-2,2>>^ And peoples will actually take them and bring them to their own place, and the house of Israel must take them to themselves as a possession upon the soil of Jehovah as menservants and as maidservants; and they must become the captors of those holding them captive, and they must have in subjection those who were driving them to work.

[[v23-14-3]]

^<<v23-14-3,3>>^ And it must occur in the day when Jehovah gives you^&#42;1^ rest from your pain and from your agitation and from the hard slavery in which you were made a slave,

[NOTE]
====
. “You,” masc. sing.
====

[[v23-14-4]]

^<<v23-14-4,4>>^ that you must raise up this proverbial saying against the king of Babylon and say:
“How has the one driving &#91;others&#93; to work come to a stop,^&#42;1^ the oppression^&#42;2^ come to a stop!

[NOTE]
====
. “Come to a stop.” Or, “ceased.” Heb., sha·vathʹ.
. Or, “might; power.” See VT, Vol. VII, 1957, pp. 202, 203. 1QIsa(Heb.), mar·he·vahʹ, “assault”; LXXSy, “the taskmaster”; Vg, “the tribute.”
====

[[v23-14-5]]

^<<v23-14-5,5>>^ Jehovah has broken the rod of the wicked ones, the staff of the ruling ones,

[[v23-14-6]]

^<<v23-14-6,6>>^ the one striking peoples in fury with a stroke incessantly, the one subduing nations in sheer anger with a persecution without restraint.

[[v23-14-7]]

^<<v23-14-7,7>>^ The whole earth has come to rest, has become free of disturbance. People have become cheerful with joyful cries.

[[v23-14-8]]

^<<v23-14-8,8>>^ Even the juniper trees have also rejoiced at you,^&#42;1^ the cedars of Lebʹa·non, &#91;saying,&#93; ‘Ever since you have lain down, no &#91;wood&#93;cutter comes up against us.’

[NOTE]
====
. “You,” masc. sing.
====

[[v23-14-9]]

^<<v23-14-9,9>>^ “Even Sheʹol^&#42;1^ underneath has become agitated at you in order to meet you on coming in. At you it has awakened those impotent in death,^&#42;2^ all the goatlike leaders^&#42;3^ of the earth. It has made all the kings of the nations get up from their thrones.

[NOTE]
====
. “Sheol,” 1QIsaM(Heb., sheʼohlʹ)T; Gr., haiʹdes; Lat., in·ferʹnus.
. “Those impotent in death.” Heb., repha·ʼimʹ; LXXSyVg, “the giants.” Compare Job 26:5 ftn; Ps 88:10 ftn.
. Lit., “the he-goats.”
====

[[v23-14-10]]

^<<v23-14-10,10>>^ All of them speak up and say to you, ‘Have you yourself also been made weak^&#42;1^ like us? Is it to us that you have been made comparable?

[NOTE]
====
. Or, “sick.”
====

[[v23-14-11]]

^<<v23-14-11,11>>^ Down to Sheʹol your pride has been brought, the din of your stringed instruments. Beneath you, maggots are spread out as a couch; and worms are your covering.’

[[v23-14-12]]

^<<v23-14-12,12>>^ “O how you have fallen from heaven, you shining one,^&#42;1^ son of the dawn! How you have been cut down to the earth, you who were disabling the nations!

[NOTE]
====
. “Shining one,” BDB, p. 237; Heb., heh·lelʹ. Gr., ho he·o·sphoʹros, “the bringer of dawn (morn)”; Lat., luʹci·fer, “light bearer.” Compare Job 38:32 ftn, “Mazzaroth constellation.”
====

[[v23-14-13]]

^<<v23-14-13,13>>^ As for you, you have said in your heart, ‘To the heavens I shall go up. Above the stars of God^&#42;1^ I shall lift up my throne, and I shall sit down upon the mountain of meeting, in the remotest parts of the north.

[NOTE]
====
. “God.” Heb., ʼEl; Lat., Deʹi; LXX, “the heaven.”
====

[[v23-14-14]]

^<<v23-14-14,14>>^ I shall go up above the high places of the clouds; I shall make myself resemble the Most High.’

[[v23-14-15]]

^<<v23-14-15,15>>^ “However, down to Sheʹol^&#42;1^ you will be brought, to the remotest parts of the pit.

[NOTE]
====
. “Sheol,” 1QIsaM(Heb., sheʼohlʹ)T; Gr., haiʹdou; Lat., in·ferʹnum.
====

[[v23-14-16]]

^<<v23-14-16,16>>^ Those seeing you will gaze even at you; they will give close examination even to you, &#91;saying,&#93; ‘Is this the man^&#42;1^ that was agitating the earth, that was making kingdoms rock,

[NOTE]
====
. “The man.” Heb., ha·ʼishʹ; Gr., ho anʹthro·pos; Syr., gab·raʼ; Lat., vir.
====

[[v23-14-17]]

^<<v23-14-17,17>>^ that made the productive land^&#42;1^ like the wilderness and that overthrew its^&#42;2^ very cities, that did not open the way homeward even for his prisoners?’

[NOTE]
====
. See 13:11 ftn, “Land.”
. Or, “his.”
====

[[v23-14-18]]

^<<v23-14-18,18>>^ All other kings of the nations, yes, all of them, have lain down in glory, each one in his own house.

[[v23-14-19]]

^<<v23-14-19,19>>^ But as for you, you have been thrown away without a burial place for you,^&#42;1^ like a detested sprout,^&#42;2^ clothed with killed men stabbed with the sword that are going down to the stones of a pit, like a carcass trodden down.

[NOTE]
====
. Lit., “away out of your grave.”
. “Like a . . . sprout.” Heb., keneʹtser.
====

[[v23-14-20]]

^<<v23-14-20,20>>^ You will not become united with them in a grave,^&#42;1^ because you brought your own land to ruin, you killed your own people. To time indefinite the offspring^&#42;2^ of evildoers will not be named.^&#42;3^

[NOTE]
====
. Or, “in burial.”
. Lit., “seed.”
. Or, “called out.”
====

[[v23-14-21]]

^<<v23-14-21,21>>^ “Make ready, YOU men, a slaughtering block for his own sons because of the error of their forefathers, that they may not rise up and actually take possession of the earth^&#42;1^ and fill the face of the productive land^&#42;2^ with cities.”

[NOTE]
====
. Or, “land.”
. See 13:11 ftn, “Land.”
====

[[v23-14-22]]

^<<v23-14-22,22>>^ “And I will rise up against them,” is the utterance of Jehovah of armies.
“And I will cut off from Babylon^&#42;1^ name and remnant^&#42;2^ and progeny and posterity,” is the utterance of Jehovah.

[NOTE]
====
. “Babylon,” Vg; MTSy, “Babel.”
. Or, “those remaining over.”
====

[[v23-14-23]]

^<<v23-14-23,23>>^ “And I will make her a possession of porcupines and reedy pools of water, and I will sweep her with the broom of annihilation,” is the utterance of Jehovah of armies.

[[v23-14-24]]

^<<v23-14-24,24>>^ Jehovah of armies has sworn, saying: “Surely just as I have figured, so it must occur; and just as I have counseled, that is what will come true,

[[v23-14-25]]

^<<v23-14-25,25>>^ in order to break the As·syrʹi·an^&#42;1^ in my land and that I may tread him down on my own mountains; and that his yoke may actually depart from upon them and that his very load may depart from upon their^&#42;2^ shoulder.”

[NOTE]
====
. “The Assyrian.” Heb., ʼAsh·shurʹ; LXX, “the Assyrians.”
. “Their,” TVg; M, “his.”
====

[[v23-14-26]]

^<<v23-14-26,26>>^ This is the counsel that is counseled against all the earth, and this is the hand that is stretched out against all the nations.

[[v23-14-27]]

^<<v23-14-27,27>>^ For Jehovah of armies himself has counseled, and who can break &#91;it&#93; up? And his hand is the one stretched out, and who can turn it back?

[[v23-14-28]]

^<<v23-14-28,28>>^ In the year that King Aʹhaz died this pronouncement occurred:

[[v23-14-29]]

^<<v23-14-29,29>>^ “Do not rejoice, O Phi·lisʹti·a, any one of you, just because the staff of the one striking you has been broken. For out of the root of the serpent there will come forth a poisonous snake, and its fruit will be a flying fiery snake.

[[v23-14-30]]

^<<v23-14-30,30>>^ And the firstborn ones of the lowly ones will certainly feed, and in security the poor ones themselves will lie down. And with famine I will put your root to death, and what remains over of you^&#42;1^ will be killed.^&#42;2^

[NOTE]
====
. Or, “and the remainder of you.” Heb., u·sheʼe·ri·thekhʹ.
. Or, “one will kill.”
====

[[v23-14-31]]

^<<v23-14-31,31>>^ Howl, O gate! Cry out, O city! All of you must become disheartened, O Phi·lisʹti·a! For out of the north a smoke is coming, and there is no one getting isolated from his ranks.”

[[v23-14-32]]

^<<v23-14-32,32>>^ And what will anyone say in answer to the messengers of the nation? That Jehovah himself has laid the foundation of Zion, and in her the afflicted ones of his people will take refuge.

'''

xref:023-isaiah/023-isaiah-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaiah/023-isaiah-015.adoc#v23-15-0[Próximo Capítulo &#62;]