include::./index.adoc[]

[[v23-52-0]]
=== Isaiah, 52
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-52-1]]

^<<v23-52-1,1>>^ Wake up, wake up, put on your strength, O Zion! Put on your beautiful garments, O Jerusalem, the holy city! For no more will there come again into you the uncircumcised and unclean one.

[[v23-52-2]]

^<<v23-52-2,2>>^ Shake yourself free from the dust, rise up, take a seat, O Jerusalem. Loosen for yourself the bands on your neck, O captive daughter of Zion.

[[v23-52-3]]

^<<v23-52-3,3>>^ For this is what Jehovah has said: “It was for nothing that YOU people were sold, and it will be without money that YOU will be repurchased.”

[[v23-52-4]]

^<<v23-52-4,4>>^ For this is what the Sovereign Lord Jehovah has said: “It was to Egypt that my people went down in the first instance to reside there as aliens; and without cause As·syrʹi·a, for its part, oppressed them.”

[[v23-52-5]]

^<<v23-52-5,5>>^ “And now, what interest do I have here?” is the utterance of Jehovah. “For my people were taken for nothing. The very ones ruling over them kept howling,”^&#42;1^ is the utterance of Jehovah, “and constantly, all day long, my name was being treated with disrespect.

[NOTE]
====
. Or, “kept making [them] howl.”
====

[[v23-52-6]]

^<<v23-52-6,6>>^ For that reason my people will know my name, even for that reason in that day, because I am the One that is speaking. Look! It is I.”

[[v23-52-7]]

^<<v23-52-7,7>>^ How comely upon the mountains are the feet of the one bringing good news, the one publishing peace, the one bringing good news of something better, the one publishing salvation, the one saying to Zion: “Your God^&#42;1^ has become king!”

[NOTE]
====
. “Your God.” Heb., ʼElo·haʹyikh.
====

[[v23-52-8]]

^<<v23-52-8,8>>^ Listen!^&#42;1^ Your^&#42;2^ own watchmen have raised &#91;their&#93; voice. In unison they keep crying out joyfully; for it will be eye into eye that they will see when Jehovah gathers back Zion.

[NOTE]
====
. Lit., “The voice of.”
. “Your,” fem. sing., referring to “Zion.”
====

[[v23-52-9]]

^<<v23-52-9,9>>^ Become cheerful, cry out joyfully in unison, YOU devastated places of Jerusalem, for Jehovah has comforted his people; he has repurchased Jerusalem.

[[v23-52-10]]

^<<v23-52-10,10>>^ Jehovah has bared his holy arm before the eyes of all the nations; and all the ends of the earth must see the salvation of our God.

[[v23-52-11]]

^<<v23-52-11,11>>^ Turn away, turn away, get out of there, touch nothing unclean; get out from the midst of her, keep yourselves clean, YOU who are carrying the utensils of Jehovah.

[[v23-52-12]]

^<<v23-52-12,12>>^ For YOU people will get out in no panic, and YOU will go in no flight. For Jehovah will be going even before YOU, and the God of Israel will be YOUR rear guard.^&#42;1^

[NOTE]
====
. “Be your rear guard.” Lit., “be gathering you up.”
====

[[v23-52-13]]

^<<v23-52-13,13>>^ Look! My servant will act with insight. He will be in high station and will certainly be elevated and exalted very much.

[[v23-52-14]]

^<<v23-52-14,14>>^ To the extent that many have stared at him^&#42;1^ in amazement—so much was the disfigurement as respects his appearance more than that of any other man^&#42;2^ and as respects his stately form more than that of the sons of mankind^&#42;3^—

[NOTE]
====
. “Him,” TSy; 1QIsaMLXXVg, “you.”
. “Than . . . man.” Heb., me·ʼishʹ.
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-52-15]]

^<<v23-52-15,15>>^ he will likewise startle many nations. At him kings will shut their mouth, because what had not been recounted to them they will actually see, and to what they had not heard they must turn their consideration.

'''

xref:023-isaiah/023-isaiah-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaiah/023-isaiah-053.adoc#v23-53-0[Próximo Capítulo &#62;]