include::./index.adoc[]

[[v23-6-0]]
=== Isaiah, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-6-1]]

^<<v23-6-1,1>>^ In the year that King Uz·ziʹah died I, however, got to see Jehovah,^&#42;1^ sitting on a throne lofty and lifted up, and his skirts were filling the temple.^&#42;2^

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. Or, “the palace.” Heb., ha·heh·khalʹ, as in 2Ki 20:18; Lat., temʹplum. See Mt 23:16 ftn.
====

[[v23-6-2]]

^<<v23-6-2,2>>^ Seraphs were standing above him.^&#42;1^ Each one had six wings. With two he kept his face covered, and with two he kept his feet covered, and with two he would fly about.

[NOTE]
====
. “It,” Vg; likely the “throne.”
====

[[v23-6-3]]

^<<v23-6-3,3>>^ And this one called to that one and said: “Holy, holy, holy is Jehovah of armies. The fullness of all the earth is his glory.”

[[v23-6-4]]

^<<v23-6-4,4>>^ And the pivots of the thresholds began to quiver at the voice of the one calling, and the house itself gradually filled with smoke.^&#42;1^

[NOTE]
====
. “And the house began to be filled with smoke,” James Washington Watts (1979). See App 3C.
====

[[v23-6-5]]

^<<v23-6-5,5>>^ And I proceeded to say: “Woe to me! For I am as good as brought to silence, because a man unclean in lips I am, and in among a people unclean in lips I am dwelling; for my eyes have seen the King, Jehovah of armies, himself!”

[[v23-6-6]]

^<<v23-6-6,6>>^ At that, one of the seraphs flew to me, and in his hand there was a glowing coal that he had taken with tongs off the altar.

[[v23-6-7]]

^<<v23-6-7,7>>^ And he proceeded to touch my mouth and to say: “Look! This has touched your lips, and your error has departed and your sin itself is atoned for.”

[[v23-6-8]]

^<<v23-6-8,8>>^ And I began to hear the voice of Jehovah^&#42;1^ saying: “Whom shall I send, and who will go for us?” And I proceeded to say: “Here I am! Send me.”

[NOTE]
====
. See vs 1 ftn, “Jehovah.”
====

[[v23-6-9]]

^<<v23-6-9,9>>^ And he went on to say: “Go, and you must say to this people, ‘Hear again and again, O men, but do not understand; and see again and again, but do not get any knowledge.’

[[v23-6-10]]

^<<v23-6-10,10>>^ Make the heart of this people unreceptive,^&#42;1^ and make their very ears unresponsive,^&#42;2^ and paste their very eyes together, that they may not see with their eyes and with their ears they may not hear, and that their own heart may not understand and that they may not actually turn back and get healing for themselves.”

[NOTE]
====
. Lit., “fat.”
. Lit., “heavy.”
====

[[v23-6-11]]

^<<v23-6-11,11>>^ At this I said: “How long, O Jehovah?”^&#42;1^ Then he said: “Until the cities actually crash in ruins, to be without an inhabitant, and the houses be without earthling man, and the ground itself is ruined into a desolation;

[NOTE]
====
. See vs 1 ftn, “Jehovah.”
====

[[v23-6-12]]

^<<v23-6-12,12>>^ and Jehovah actually removes earthling men far away, and the deserted condition does become very extensive in the midst of the land.^&#42;1^

[NOTE]
====
. Or, “earth.”
====

[[v23-6-13]]

^<<v23-6-13,13>>^ And there will still be in it a tenth, and it must again become something for burning down, like a big tree and like a massive tree in which,^&#42;1^ when there is a cutting down &#91;of them&#93;, there is a stump; a holy seed^&#42;2^ will be the stump of it.”^&#42;3^

[NOTE]
====
. “Which,” pl., M; SyVg and about 100 Heb. mss, “which,” fem. sing.
. Or, “offspring.”
. Or, “be out of the stump of it,” if there was a homoeoteleuton in M.
====

'''

xref:023-isaiah/023-isaiah-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-isaiah/023-isaiah-007.adoc#v23-7-0[Próximo Capítulo &#62;]