include::./index.adoc[]

[[v23-48-0]]
=== Isaiah, 48
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-48-1]]

^<<v23-48-1,1>>^ Hear this, O house of Jacob, YOU who are calling yourselves by the name of Israel and who have come forth from the very waters^&#42;1^ of Judah, YOU who are swearing by the name of Jehovah and who make mention even of the God^&#42;2^ of Israel, not in truth^&#42;3^ and not in righteousness.

[NOTE]
====
. “Bowels; inward parts,” by a correction of M; about 40 Heb. mss, “days.”
. “And . . . of the God of.” Heb., u·vEʼ·lo·hehʹ.
. Or, “trueness.”
====

[[v23-48-2]]

^<<v23-48-2,2>>^ For they have called themselves as being from the holy city, and upon the God of Israel they have supported themselves, Jehovah of armies being his name.

[[v23-48-3]]

^<<v23-48-3,3>>^ “The first things I have told even from that time, and out of my own mouth they went forth, and I kept making them heard. Suddenly I acted, and the things proceeded to come in.

[[v23-48-4]]

^<<v23-48-4,4>>^ Due to my knowing that you are hard and that your neck is an iron sinew and your forehead is copper,

[[v23-48-5]]

^<<v23-48-5,5>>^ I also kept telling you from that time. Before it could come in, I caused you to hear &#91;it&#93;, that you might not say, ‘My own idol has done them, and my own carved image and my own molten image have commanded them.’

[[v23-48-6]]

^<<v23-48-6,6>>^ You have heard. Behold it all. As for YOU people, will YOU not tell &#91;it&#93;? I have made you hear new things from the present time, even things kept in reserve,^&#42;1^ that you have not known.

[NOTE]
====
. Or, “kept under safeguard.”
====

[[v23-48-7]]

^<<v23-48-7,7>>^ At the present time they must be created, and not from that time, even things that before today you have not heard, that you may not say, ‘Look! I have already known them.’

[[v23-48-8]]

^<<v23-48-8,8>>^ “Moreover, you have not heard, neither have you known, nor from that time on has your ear been opened. For I well know that without fail you kept dealing treacherously, and a ‘transgressor from the belly’^&#42;1^ you have been called.

[NOTE]
====
. That is, from the mother’s womb.
====

[[v23-48-9]]

^<<v23-48-9,9>>^ For the sake of my name I shall check my anger, and for my praise I shall restrain myself toward you that there may be no cutting you off.

[[v23-48-10]]

^<<v23-48-10,10>>^ Look! I have refined you, but not in &#91;the form of&#93; silver. I have made choice of you in the smelting furnace of affliction.

[[v23-48-11]]

^<<v23-48-11,11>>^ For my own sake, for my own sake I shall act, for how could one let oneself be profaned? And to no one else shall I give my own glory.

[[v23-48-12]]

^<<v23-48-12,12>>^ “Listen to me, O Jacob, and you Israel my called one. I am the same One. I am the first. Moreover, I am the last.

[[v23-48-13]]

^<<v23-48-13,13>>^ Moreover, my own hand laid the foundation of the earth, and my own right hand extended out the heavens. I am calling to them, that they may keep standing together.

[[v23-48-14]]

^<<v23-48-14,14>>^ “Be collected together, all YOU people, and hear. Who among them^&#42;1^ has told these things? Jehovah himself has loved him. He will do what is his delight upon Babylon, and his own arm will be upon the Chal·deʹans.

[NOTE]
====
. “Them,” 1QIsaMTLXXVg; Sy and about 40 Heb. mss, “you.”
====

[[v23-48-15]]

^<<v23-48-15,15>>^ I—I myself have spoken. Moreover, I have called him. I have brought him in, and there will be a making of his way successful.

[[v23-48-16]]

^<<v23-48-16,16>>^ “Come near to me, YOU people. Hear this. From the start I have spoken in no place of concealment at all. From the time of its occurring I have been there.”
And now the Sovereign Lord Jehovah himself has sent me, even^&#42;1^ his spirit.

[NOTE]
====
. Or, “and.”
====

[[v23-48-17]]

^<<v23-48-17,17>>^ This is what Jehovah has said, your Repurchaser, the Holy One of Israel: “I, Jehovah, am your God, the One teaching you to benefit &#91;yourself&#93;, the One causing you to tread in the way in which you should walk.

[[v23-48-18]]

^<<v23-48-18,18>>^ O if only you would actually pay attention to my commandments! Then your peace would become just like a river, and your righteousness like the waves of the sea.

[[v23-48-19]]

^<<v23-48-19,19>>^ And your offspring would become just like the sand, and the descendants from your inward parts like the grains of it. One’s name^&#42;1^ would not be cut off or be annihilated from before me.”

[NOTE]
====
. Or, “His name,” 1QIsaMTSyVg; LXX, “Your name.”
====

[[v23-48-20]]

^<<v23-48-20,20>>^ Go forth, YOU people, out of Babylon! Run away from the Chal·deʹans. Tell forth even with the sound of a joyful cry, cause this to be heard. Make it to go forth to the extremity of the earth. Say: “Jehovah has repurchased his servant Jacob.

[[v23-48-21]]

^<<v23-48-21,21>>^ And they did not get thirsty when he was making them walk even through devastated places. Water out of the rock he caused to flow forth for them, and he proceeded to split a rock that the water might stream forth.”

[[v23-48-22]]

^<<v23-48-22,22>>^ “There is no peace,” Jehovah has said, “for the wicked ones.”

'''

xref:023-isaiah/023-isaiah-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaiah/023-isaiah-049.adoc#v23-49-0[Próximo Capítulo &#62;]