include::./index.adoc[]

[[v23-27-0]]
=== Isaiah, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-27-1]]

^<<v23-27-1,1>>^ In that day Jehovah, with his hard and great and strong sword, will turn his attention to Le·viʹa·than,^&#42;1^ the gliding serpent, even to Le·viʹa·than, the crooked serpent, and he will certainly kill the sea monster that is in the sea.

[NOTE]
====
. “Leviathan,” MSyVg; LXX, “the dragon.”
====

[[v23-27-2]]

^<<v23-27-2,2>>^ In that day sing to her, YOU people: “A vineyard of foaming wine!^&#42;1^

[NOTE]
====
. “Foaming wine.” AlCa(Heb.), cheʹmer; that is, fermenting wine.
====

[[v23-27-3]]

^<<v23-27-3,3>>^ I, Jehovah, am safeguarding her. Every moment I shall water her. In order that no one may turn his attention against her, I shall safeguard her even night and day.

[[v23-27-4]]

^<<v23-27-4,4>>^ There is no rage that I have. Who will give me thornbushes &#91;and&#93; weeds in the battle? I will step on such. I will set such on fire at the same time.

[[v23-27-5]]

^<<v23-27-5,5>>^ Otherwise let him take hold of my stronghold, let him make peace with me; peace let him make with me.”

[[v23-27-6]]

^<<v23-27-6,6>>^ In the coming &#91;days&#93; Jacob will take root, Israel will put forth blossoms and actually sprout; and they will simply fill the surface of the productive land^&#42;1^ with produce.

[NOTE]
====
. See 13:11 ftn, “Land.”
====

[[v23-27-7]]

^<<v23-27-7,7>>^ As with the stroke of one striking him does one have to strike him? Or as with the slaughter^&#42;1^ of his killed ones does he have to be killed?

[NOTE]
====
. Lit., “killing.”
====

[[v23-27-8]]

^<<v23-27-8,8>>^ With a scare cry you will contend with her when sending her forth. He must expel &#91;her&#93; with his blast, a hard one in the day of the east wind.

[[v23-27-9]]

^<<v23-27-9,9>>^ Therefore by this means the error of Jacob will be atoned for, and this is all the fruit &#91;when&#93; he takes away his sin, when he makes all the stones of the altar like chalkstones that have been pulverized, so that the sacred poles^&#42;1^ and the incense stands will not rise up.

[NOTE]
====
. Or, “the Asherim.”
====

[[v23-27-10]]

^<<v23-27-10,10>>^ For the fortified city will be solitary, the pasture ground will be left to itself and abandoned like a wilderness. There the calf will graze, and there it will lie down; and he will actually consume her boughs.

[[v23-27-11]]

^<<v23-27-11,11>>^ When her sprigs have dried up, women coming in will break &#91;them&#93; off, lighting them up. For it is not a people of keen understanding. That is why its Maker will show it no mercy, and its own Former will show it no favor.

[[v23-27-12]]

^<<v23-27-12,12>>^ And it must occur in that day that Jehovah will beat off &#91;the fruit&#93;, from the flowing stream of the River^&#42;1^ to the torrent valley of Egypt, and so YOU yourselves will be picked up one after the other, O sons of Israel.

[NOTE]
====
. That is, the Euphrates.
====

[[v23-27-13]]

^<<v23-27-13,13>>^ And it must occur in that day that there will be a blowing on a great horn,^&#42;1^ and those who are perishing in the land of As·syrʹi·a and those who are dispersed in the land of Egypt will certainly come and bow down to Jehovah in the holy mountain in Jerusalem.

[NOTE]
====
. Or, “shofar.”
====

'''

xref:023-isaiah/023-isaiah-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaiah/023-isaiah-028.adoc#v23-28-0[Próximo Capítulo &#62;]