include::./index.adoc[]

[[v23-47-0]]
=== Isaiah, 47
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-47-1]]

^<<v23-47-1,1>>^ Come down and sit down in the dust, O virgin daughter of Babylon.^&#42;1^ Sit down on the earth where there is no throne, O daughter of the Chal·deʹans. For you will not experience again that people call you delicate and dainty.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v23-47-2]]

^<<v23-47-2,2>>^ Take a hand mill and grind out flour. Uncover your veil. Strip off the flowing skirt. Uncover the leg. Cross over the rivers.

[[v23-47-3]]

^<<v23-47-3,3>>^ You ought to uncover your nakedness. Also, your reproach ought to be seen. Vengeance is what I shall take, and I shall not meet any man^&#42;1^ &#91;kindly&#93;.

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-47-4]]

^<<v23-47-4,4>>^ “There is One repurchasing us. Jehovah of armies is his name, the Holy One of Israel.”

[[v23-47-5]]

^<<v23-47-5,5>>^ Sit down silently and come into the darkness, O daughter of the Chal·deʹans; for you will not experience again that people call you Mistress of Kingdoms.

[[v23-47-6]]

^<<v23-47-6,6>>^ I grew indignant at my people. I profaned my inheritance, and I proceeded to give them into your hand. You showed them no mercies. Upon the old man you made your yoke very heavy.

[[v23-47-7]]

^<<v23-47-7,7>>^ And you kept saying: “To time indefinite I shall prove to be Mistress, forever.” You did not take these things to your heart; you did not remember the finale of the matter.

[[v23-47-8]]

^<<v23-47-8,8>>^ And now hear this, you pleasure-given &#91;woman&#93;, the one sitting in security, the one saying in her heart: “I am, and there is nobody else. I shall not sit as a widow, and I shall not know the loss of children.”

[[v23-47-9]]

^<<v23-47-9,9>>^ But to you these two things will come suddenly, in one day: loss of children and widowhood. In their complete measure they must come upon you, for the abundance of your sorceries, for the full might of your spells—exceedingly.

[[v23-47-10]]

^<<v23-47-10,10>>^ And you kept trusting in your badness. You have said: “There is no one seeing me.” Your wisdom and your knowledge—this is what has led you away; and you keep saying in your heart: “I am, and there is nobody else.”

[[v23-47-11]]

^<<v23-47-11,11>>^ And upon you calamity must come; you will know no charming against it. And upon you adversity will fall; you will not be able to avert it. And upon you there will suddenly come a ruin that you are not accustomed to know.

[[v23-47-12]]

^<<v23-47-12,12>>^ Stand still, now, with your spells and with the abundance of your sorceries, in which you have toiled from your youth; that perhaps you might be able to benefit, that perhaps you might strike people with awe.

[[v23-47-13]]

^<<v23-47-13,13>>^ You have grown weary with the multitude of your counselors.^&#42;1^ Let them stand up, now, and save you, the worshipers^&#42;2^ of the heavens, the lookers at the stars,^&#42;3^ those giving out knowledge at the new moons concerning the things that will come upon you.^&#42;4^

[NOTE]
====
. Lit., “counsels,” but personalized.
. “Worshipers.” Usually rendered “dividers; those who divide.” See VT, Vol. VII, 1957, pp. 183, 184.
. Or, “the astrologers.”
. In agreement with LXXVg; M, “from the things that will come upon you,” evidently by a dittography of letters.
====

[[v23-47-14]]

^<<v23-47-14,14>>^ Look! They have become like stubble. A fire itself will certainly burn them up. They will not deliver their soul from the power^&#42;1^ of the flame. There will be no glow of charcoals for people to warm themselves, no firelight in front of which to sit down.

[NOTE]
====
. Lit., “hand.”
====

[[v23-47-15]]

^<<v23-47-15,15>>^ Thus they will certainly become to you, with whom you have toiled as your charmers^&#42;1^ from your youth. They will actually wander, each one to his own region. There will be no one to save you.

[NOTE]
====
. By a correction of the first letter; M, “merchants; traffickers.”
====

'''

xref:023-isaiah/023-isaiah-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaiah/023-isaiah-048.adoc#v23-48-0[Próximo Capítulo &#62;]