include::./index.adoc[]

[[v23-66-0]]
=== Isaiah, 66
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-66-1]]

^<<v23-66-1,1>>^ This is what Jehovah has said: “The heavens are my throne, and the earth is my footstool. Where, then, is the house that YOU people can build for me, and where, then, is the place as a resting-place for me?”

[[v23-66-2]]

^<<v23-66-2,2>>^ “Now all these things my own hand has made, so that all these came to be,”^&#42;1^ is the utterance of Jehovah. “To this one, then, I shall look, to the one afflicted and contrite in spirit and trembling at^&#42;2^ my word.

[NOTE]
====
. “Came to be,” MTVg; LXXSy, “are all mine.”
. “Trembling at.” Or, “anxious toward.”
====

[[v23-66-3]]

^<<v23-66-3,3>>^ “The one slaughtering the bull is as one striking down a man.^&#42;1^ The one sacrificing the sheep is as one breaking the neck of a dog. The one offering up a gift—the blood of a pig! The one presenting a memorial of frankincense is as one saying a blessing with uncanny words.^&#42;2^ They are also the ones that have chosen their own ways, and in their disgusting things their very soul has taken a delight.

[NOTE]
====
. “Man.” Heb., ʼish.
. Or, “upon uncanny things.”
====

[[v23-66-4]]

^<<v23-66-4,4>>^ I myself, in turn, shall choose ways of ill-treating them; and the things frightful to them I shall bring upon them; for the reason that I called, but there was no one answering; I spoke, but there were none that listened; and they kept on doing what was bad in my eyes, and the thing in which I took no delight they chose.”

[[v23-66-5]]

^<<v23-66-5,5>>^ Hear the word of Jehovah, YOU men who are trembling at his word: “YOUR brothers that are hating YOU, that are excluding YOU by reason of my name, said, ‘May Jehovah be glorified!’ He must also appear with rejoicing on YOUR part, and they are the ones that will be put to shame.”

[[v23-66-6]]

^<<v23-66-6,6>>^ There is a sound of uproar out of the city, a sound out of the temple! It is the sound of Jehovah repaying what is deserved to his enemies.

[[v23-66-7]]

^<<v23-66-7,7>>^ Before she began to come into labor pains she gave birth. Before birth pangs could come to her, she even gave deliverance to a male child.

[[v23-66-8]]

^<<v23-66-8,8>>^ Who has heard of a thing like this? Who has seen things like these? Will a land be brought forth with labor pains in one day? Or will a nation be born at one time?^&#42;1^ For Zion has come into labor pains as well as given birth to her sons.

[NOTE]
====
. Or, “at once?”
====

[[v23-66-9]]

^<<v23-66-9,9>>^ “As for me, shall I cause the breaking through and not cause the giving birth?” says Jehovah. “Or am I causing a giving birth and do I actually cause a shutting up?” your^&#42;1^ God^&#42;2^ has said.

[NOTE]
====
. “Your,” fem. sing., referring to “Zion,” or “Jerusalem.”
. “Your God.” Heb., ʼElo·haʹyikh.
====

[[v23-66-10]]

^<<v23-66-10,10>>^ Rejoice with Jerusalem and be joyful with her, all YOU lovers of her. Exult greatly with her, all YOU keeping yourselves in mourning over her;

[[v23-66-11]]

^<<v23-66-11,11>>^ for the reason that YOU will suck and certainly get satisfaction from the breast of full consolation by her;^&#42;1^ for the reason that YOU will sip and experience exquisite delight from the teat of her glory.

[NOTE]
====
. Or, “of her consolations.”
====

[[v23-66-12]]

^<<v23-66-12,12>>^ For this is what Jehovah has said: “Here I am extending to her peace just like a river and the glory of nations just like a flooding torrent, and YOU will certainly suck. Upon the flank YOU will be carried, and upon the knees YOU will be fondled.

[[v23-66-13]]

^<<v23-66-13,13>>^ Like a man^&#42;1^ whom his own mother keeps comforting, so I myself shall keep comforting YOU people; and in the case of Jerusalem YOU will be comforted.

[NOTE]
====
. “Like a man.” Heb., keʼishʹ.
====

[[v23-66-14]]

^<<v23-66-14,14>>^ And YOU will certainly see, and YOUR heart will be bound to exult, and YOUR very bones will sprout just like tender grass. And the hand of Jehovah will certainly be made known to his servants, but he will actually denounce his enemies.”

[[v23-66-15]]

^<<v23-66-15,15>>^ “For here Jehovah himself comes as a very fire, and his chariots are like a storm wind, in order to pay back his anger with sheer rage and his rebuke with flames of fire.

[[v23-66-16]]

^<<v23-66-16,16>>^ For as fire Jehovah himself will for a fact take up the controversy, yes, with his sword, against all flesh; and the slain of Jehovah will certainly become many.

[[v23-66-17]]

^<<v23-66-17,17>>^ Those sanctifying themselves and cleansing themselves for the gardens behind one^&#42;1^ in the center, eating the flesh of the pig and the loathsome thing, even the jumping rodent,^&#42;2^ they will all together reach their end,” is the utterance of Jehovah.

[NOTE]
====
. “One,” masc. in M but fem. in Mmargin and 13 Heb. mss.
. Or, “the jerboa.”
====

[[v23-66-18]]

^<<v23-66-18,18>>^ “And as regards their works and their thoughts, I am coming in order to collect all the nations and tongues together; and they will have to come and see my glory.”

[[v23-66-19]]

^<<v23-66-19,19>>^ “And I will set among them a sign,^&#42;1^ and I will send some of those who are escaped to the nations, &#91;to&#93; Tarʹshish, Pul,^&#42;2^ and Lud, those drawing the bow,^&#42;3^ Tuʹbal and Jaʹvan, the faraway islands,^&#42;4^ who have not heard a report about me or seen my glory; and they will for certain tell about my glory among the nations.

[NOTE]
====
. “Sign.” Heb., ʼohth; Lat., siʹgnum.
. “Pul,” 1QIsaMSy; LXX, “Put.”
. “Those drawing the bow,” 1QIsaMSy; LXX, “Meshech.”
. Or, “coastlands.”
====

[[v23-66-20]]

^<<v23-66-20,20>>^ And they will actually bring all YOUR brothers out of all the nations as a gift to Jehovah, on horses and in chariots and in covered wagons and on mules and on swift she-camels, up to my holy mountain,^&#42;1^ Jerusalem,” Jehovah has said, “just as when the sons of Israel bring the gift in a clean vessel into the house of Jehovah.”

[NOTE]
====
. “Mountain,” 1QIsaMTSyVg; LXX, “city.”
====

[[v23-66-21]]

^<<v23-66-21,21>>^ “And from them also I shall take some for the priests, for the Levites,”^&#42;1^ Jehovah has said.

[NOTE]
====
. “For the Levites,” 1QIsaM; TLXXSyVg and some Heb. mss, “and for the Levites.”
====

[[v23-66-22]]

^<<v23-66-22,22>>^ “For just as the new heavens and the new earth that I am making are standing before me,” is the utterance of Jehovah, “so the offspring^&#42;1^ of YOU people and the name of YOU people will keep standing.”

[NOTE]
====
. Lit., “seed.”
====

[[v23-66-23]]

^<<v23-66-23,23>>^ “And it will certainly occur that from new moon to new moon^&#42;1^ and from sabbath to sabbath^&#42;2^ all flesh will come in to bow down before me,” Jehovah has said.

[NOTE]
====
. Or, “from month to month.”
. Or, “from week to week.”
====

[[v23-66-24]]

^<<v23-66-24,24>>^ “And they will actually go forth and look upon the carcasses of the men^&#42;1^ that were transgressing against me; for the very worms upon them^&#42;2^ will not die and their fire itself will not be extinguished, and they must become something repulsive to all flesh.”

[NOTE]
====
. “The men.” Heb., ha·ʼana·shimʹ, pl. of ʼish.
. Lit., “their very worm.”
====

'''

xref:023-isaiah/023-isaiah-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremiah/024-jeremiah-001.adoc#v24-1-0[Próximo Capítulo &#62;]