include::./index.adoc[]

[[v23-40-0]]
=== Isaiah, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-40-1]]

^<<v23-40-1,1>>^ “COMFORT, comfort my people,” says the God of YOU men.^&#42;1^

[NOTE]
====
. “The God of you men.” Heb., ʼElo·heh·khemʹ.
====

[[v23-40-2]]

^<<v23-40-2,2>>^ “SPEAK to the heart of Jerusalem and call out to her that her military service^&#42;1^ has been fulfilled, that her error has been paid off. For from the hand of Jehovah she has received a full amount^&#42;2^ for all her sins.”

[NOTE]
====
. “Her military service.” Heb., tseva·ʼahʹ, sing. of tseva·ʼohthʹ, translated “armies” in 39:5.
. Or, “twice the amount.” Heb., kiph·laʹyim, dual. See Job 11:6 ftn, “Manifold.”
====

[[v23-40-3]]

^<<v23-40-3,3>>^ Listen! Someone is calling out^&#42;1^ in the wilderness: “Clear up the way^&#42;2^ of Jehovah, YOU people! MAKE the highway for our God through^&#42;3^ the desert plain straight.^&#42;4^

[NOTE]
====
. Or, “A voice! There is one calling out”; or, “There is the voice of one calling out.”
. Or, “calling out: ‘Through (In) the wilderness clear up the way.’ ”
. Or, “in.”
. Or, “smooth.”
====

[[v23-40-4]]

^<<v23-40-4,4>>^ Let every valley be raised up, and every mountain and hill be made low. And the knobby ground must become level land, and the rugged ground a valley plain.

[[v23-40-5]]

^<<v23-40-5,5>>^ And the glory of Jehovah will certainly be revealed, and all flesh must see &#91;it&#93; together, for the very mouth of Jehovah has spoken &#91;it&#93;.”

[[v23-40-6]]

^<<v23-40-6,6>>^ Listen! Someone is saying:^&#42;1^ “Call out!” And one said:^&#42;2^ “What shall I call out?”
“All flesh is green grass, and all their loving-kindness^&#42;3^ is like the blossom of the field.

[NOTE]
====
. Or, “A voice! There is one saying”; or, “There is the voice of one saying.”
. Or, “he said.” 1QIsaLXXVg, “I said.”
. Or, “loyal love.” LXXVg, “glory”; Sy, “beauty.”
====

[[v23-40-7]]

^<<v23-40-7,7>>^ The green grass has dried up, the blossom has withered, because the very spirit of Jehovah has blown upon it. Surely the people are green grass.

[[v23-40-8]]

^<<v23-40-8,8>>^ The green grass has dried up, the blossom has withered; but as for the word of our God, it will last to time indefinite.”

[[v23-40-9]]

^<<v23-40-9,9>>^ Make your way up even onto a high mountain, you woman bringing good news for Zion. Raise your voice even with power, you woman bringing good news for Jerusalem. Raise &#91;it&#93;. Do not be afraid. Say to the cities of Judah: “Here is YOUR God.”^&#42;1^

[NOTE]
====
. “Your God.” Heb., ʼElo·heh·khemʹ.
====

[[v23-40-10]]

^<<v23-40-10,10>>^ Look! The Sovereign Lord Jehovah himself will come even as a strong one,^&#42;1^ and his arm will be ruling for him. Look! His reward is with him, and the wage he pays is before him.

[NOTE]
====
. “Even with strength,” 1QIsaLXXSyVg.
====

[[v23-40-11]]

^<<v23-40-11,11>>^ Like a shepherd he will shepherd his own drove. With his arm he will collect together the lambs; and in his bosom he will carry &#91;them&#93;. Those giving suck he will conduct &#91;with care&#93;.

[[v23-40-12]]

^<<v23-40-12,12>>^ Who has measured the waters in the mere hollow of his hand, and taken the proportions of the heavens themselves with a mere span and included in a measure^&#42;1^ the dust of the earth, or weighed with an indicator the mountains, and the hills in the scales?

[NOTE]
====
. Lit., “a third part,” of a measure not now known.
====

[[v23-40-13]]

^<<v23-40-13,13>>^ Who has taken the proportions of the spirit of Jehovah, and who as his man of counsel can make him know anything?

[[v23-40-14]]

^<<v23-40-14,14>>^ With whom did he consult together that one might make him understand, or who teaches him in the path of justice, or teaches him knowledge, or makes him know the very way of real understanding?

[[v23-40-15]]

^<<v23-40-15,15>>^ Look! The nations are as a drop from a bucket; and as the film of dust on the scales they have been accounted. Look! He lifts the islands themselves as mere fine &#91;dust&#93;.

[[v23-40-16]]

^<<v23-40-16,16>>^ Even Lebʹa·non is not sufficient for keeping a fire burning, and its wild animals are not sufficient for a burnt offering.

[[v23-40-17]]

^<<v23-40-17,17>>^ All the nations are as something nonexistent in front of him; as nothing and an unreality they have been accounted to him.

[[v23-40-18]]

^<<v23-40-18,18>>^ And to whom can YOU people liken God,^&#42;1^ and what likeness can YOU put alongside him?

[NOTE]
====
. “God,” M(Heb., ʼEl)Vg; LXX, “Jehovah.”
====

[[v23-40-19]]

^<<v23-40-19,19>>^ The craftsman has cast a mere molten image, and with gold the metalworker overlays it, and silver chains he is forging.

[[v23-40-20]]

^<<v23-40-20,20>>^ A certain tree as a contribution, a tree that is not rotten, he chooses. A skillful craftsman he searches out for himself, to prepare a carved image that may not be made to totter.

[[v23-40-21]]

^<<v23-40-21,21>>^ Do YOU people not know? Do YOU not hear? Has it not been told to YOU from the outset? Have YOU not applied understanding from the foundations of the earth?

[[v23-40-22]]

^<<v23-40-22,22>>^ There is One who is dwelling above the circle of the earth, the dwellers in which are as grasshoppers, the One who is stretching out the heavens just as a fine gauze, who spreads them out like a tent in which to dwell,

[[v23-40-23]]

^<<v23-40-23,23>>^ the One who is reducing high officials to nothing, who has made the very judges of the earth as a mere unreality.

[[v23-40-24]]

^<<v23-40-24,24>>^ Never yet have they been planted; never yet have they been sown; never yet has their stump taken root in the earth. And one has only to blow upon them and they dry up; and like stubble the windstorm itself will carry them away.

[[v23-40-25]]

^<<v23-40-25,25>>^ “But to whom can YOU people liken me so that I should be made his equal?” says the Holy One.

[[v23-40-26]]

^<<v23-40-26,26>>^ “Raise YOUR eyes high up and see. Who has created these things? It is the One who is bringing forth the army of them even by number, all of whom he calls even by name. Due to the abundance of dynamic energy,^&#42;1^ he also being vigorous in power,^&#42;2^ not one &#91;of them&#93; is missing.

[NOTE]
====
. “Dynamic energy.” Heb., ʼoh·nimʹ, pl.; Lat., for·ti·tuʹdi·nis, “fortitude.”
. “Power.” Heb., koʹach.
====

[[v23-40-27]]

^<<v23-40-27,27>>^ “For what reason do you say, O Jacob, and do you speak out, O Israel, ‘My way has been concealed from Jehovah, and justice to me eludes my God^&#42;1^ himself’?

[NOTE]
====
. Lit., “and from my God.” Heb., u·me·ʼElo·haiʹ.
====

[[v23-40-28]]

^<<v23-40-28,28>>^ Have you not come to know or have you not heard? Jehovah, the Creator of the extremities^&#42;1^ of the earth, is a God to time indefinite. He does not tire out or grow weary. There is no searching out of his understanding.

[NOTE]
====
. See Jer 25:31, 33 ftns.
====

[[v23-40-29]]

^<<v23-40-29,29>>^ He is giving to the tired one power; and to the one without dynamic energy he makes full might abound.

[[v23-40-30]]

^<<v23-40-30,30>>^ Boys will both tire out and grow weary, and young men themselves will without fail stumble,

[[v23-40-31]]

^<<v23-40-31,31>>^ but those who are hoping in Jehovah will regain power. They will mount up with wings like eagles. They will run and not grow weary; they will walk and not tire out.”

'''

xref:023-isaiah/023-isaiah-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaiah/023-isaiah-041.adoc#v23-41-0[Próximo Capítulo &#62;]