include::./index.adoc[]

[[v23-22-0]]
=== Isaiah, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-22-1]]

^<<v23-22-1,1>>^ The pronouncement of the valley of the vision:^&#42;1^ What is the matter with you,^&#42;2^ then, that you have gone up in your entirety to the roofs?

[NOTE]
====
. “The vision,” MVg; LXX, “Zion.”
. “You,” fem., addressed to the “city,” fem., in vs 2.
====

[[v23-22-2]]

^<<v23-22-2,2>>^ With turmoil you were full, a boisterous city, an exultant town. Your slain ones are not those slain with the sword, nor those dead in battle.

[[v23-22-3]]

^<<v23-22-3,3>>^ All your dictators themselves have fled at one time. Without &#91;need of&#93; a bow they have been taken prisoner. All those of you who have been found have been taken prisoner together. Far off they had run away.

[[v23-22-4]]

^<<v23-22-4,4>>^ That is why I have said: “Turn YOUR gaze away from me. I will show bitterness in weeping. Do not YOU people insist on comforting me over the despoiling of the daughter of my people.

[[v23-22-5]]

^<<v23-22-5,5>>^ For it is the day of confusion and of downtreading and of confounding that the Sovereign Lord, Jehovah of armies, has in the valley of the vision.^&#42;1^ There is the demolisher of the wall, and the cry^&#42;2^ to the mountain.

[NOTE]
====
. “The vision,” MVg; LXX, “Zion.”
. “Cry,” either a cry for help or a war cry.
====

[[v23-22-6]]

^<<v23-22-6,6>>^ And Eʹlam itself has taken up the quiver, in the war chariot of earthling man, &#91;with&#93; steeds; and Kir itself has uncovered the shield.

[[v23-22-7]]

^<<v23-22-7,7>>^ And it will occur that the choicest of your^&#42;1^ low plains must become full of war chariots, and the very steeds must without fail set themselves in position at the gate,

[NOTE]
====
. “Your,” fem. sing., referring to the “daughter of my people” in vs 4.
====

[[v23-22-8]]

^<<v23-22-8,8>>^ and one will remove the screen of Judah. And you will look in that day toward the armory of the house of the forest,

[[v23-22-9]]

^<<v23-22-9,9>>^ and YOU people will certainly see the very breaches of the City of David, for they will actually be many. And YOU will collect the waters of the lower pool.

[[v23-22-10]]

^<<v23-22-10,10>>^ And the houses of Jerusalem YOU will actually count. YOU will also pull down the houses to make the wall unattainable.

[[v23-22-11]]

^<<v23-22-11,11>>^ And there will be a collecting basin that YOU must make between the two walls for the waters of the old pool. And YOU will certainly not look at the grand maker of it, and the one forming it long ago YOU will certainly not see.

[[v23-22-12]]

^<<v23-22-12,12>>^ “And the Sovereign Lord, Jehovah of armies, will call in that day for weeping and for mourning and for baldness and for girding on sackcloth.

[[v23-22-13]]

^<<v23-22-13,13>>^ But, look! exultation and rejoicing, the killing of cattle and the slaughtering of sheep, the eating of flesh and the drinking of wine, ‘Let there be eating and drinking, for tomorrow we shall die.’”

[[v23-22-14]]

^<<v23-22-14,14>>^ And in my ears Jehovah of armies has revealed himself: “‘This error will not be atoned for in YOUR behalf until YOU people die,’ the Sovereign Lord, Jehovah of armies, has said.”

[[v23-22-15]]

^<<v23-22-15,15>>^ This is what the Sovereign Lord, Jehovah of armies, has said: “Go, enter in to this steward,^&#42;1^ to Shebʹna, who is over the house,

[NOTE]
====
. “This steward.” Heb., has·so·khenʹ haz·zehʹ.
====

[[v23-22-16]]

^<<v23-22-16,16>>^ ‘What is there of interest to you here, and who is there of interest to you here, that you have hewed out for yourself here a burial place?’ On a height he is hewing out his burial place; in a crag he is cutting out a residence for himself.

[[v23-22-17]]

^<<v23-22-17,17>>^ ‘Look! Jehovah is hurling you down with violent hurling, O able-bodied man, and grasping you forcibly.

[[v23-22-18]]

^<<v23-22-18,18>>^ Without fail he will wrap you up tightly,^&#42;1^ like a ball for a wide land.^&#42;2^ There you will die, and there the chariots of your glory will be the dishonor of the house of your master.^&#42;3^

[NOTE]
====
. Lit., “with a wrapping (winding).”
. Lit., “a land broad on both sides (hands).”
. “Your master.” Heb., ʼadho·neyʹkha, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v23-22-19]]

^<<v23-22-19,19>>^ And I will push you away from your position;^&#42;1^ and from your official standing^&#42;2^ one will tear you down.

[NOTE]
====
. Or, “office.”
. Or, “your function.”
====

[[v23-22-20]]

^<<v23-22-20,20>>^ “‘And it must occur in that day that I will call my servant,^&#42;1^ namely, E·liʹa·kim the son of Hil·kiʹah.^&#42;2^

[NOTE]
====
. Lit., “to my servant.” Heb., leʽav·diʹ; Lat., serʹvum meʹum.
. Meaning “My Portion Is Jehovah.” Heb., Chil·qi·yaʹhu.
====

[[v23-22-21]]

^<<v23-22-21,21>>^ And I will clothe him with your robe, and your sash I shall firmly bind about him, and your dominion^&#42;1^ I shall give into his hand; and he must become a father to the inhabitant of Jerusalem and to the house of Judah.

[NOTE]
====
. “And your dominion.” Heb., u·mem·shel·tekhaʹ; Gr., oi·ko·no·miʹan sou, “your stewardship.”
====

[[v23-22-22]]

^<<v23-22-22,22>>^ And I will put the key of the house of David upon his shoulder, and he must open without anyone’s shutting, and he must shut without anyone’s opening.

[[v23-22-23]]

^<<v23-22-23,23>>^ And I will drive him in as a peg in a lasting place, and he must become as a throne of glory to the house of his father.

[[v23-22-24]]

^<<v23-22-24,24>>^ And they must hang upon him all the glory of the house of his father, the descendants and the offshoots, all the vessels of the small sort, the vessels of the bowl sort as well as all the vessels of the large jars.

[[v23-22-25]]

^<<v23-22-25,25>>^ “‘In that day,’ is the utterance of Jehovah of armies, ‘the peg that is driven in a lasting place will be removed, and it must be hewn down and fall, and the load that is upon it must be cut off, for Jehovah himself has spoken &#91;it&#93;.’”

'''

xref:023-isaiah/023-isaiah-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaiah/023-isaiah-023.adoc#v23-23-0[Próximo Capítulo &#62;]