include::./index.adoc[]

[[v23-59-0]]
=== Isaiah, 59
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-59-1]]

^<<v23-59-1,1>>^ Look! The hand of Jehovah has not become too short that it cannot save, nor has his ear become too heavy that it cannot hear.

[[v23-59-2]]

^<<v23-59-2,2>>^ No, but the very errors of YOU people have become the things causing division between YOU and YOUR God,^&#42;1^ and YOUR own sins have caused the concealing of &#91;his&#93; face from YOU to keep from hearing.

[NOTE]
====
. “Your God.” Heb., ʼElo·heh·khemʹ.
====

[[v23-59-3]]

^<<v23-59-3,3>>^ For YOUR own palms have become polluted with blood, and YOUR fingers with error. YOUR own lips have spoken falsehood. YOUR own tongue kept muttering sheer unrighteousness.

[[v23-59-4]]

^<<v23-59-4,4>>^ There is no one calling out in righteousness, and no one at all has gone to court in faithfulness. There has been a trusting in unreality, and a speaking of worthlessness. There has been a conceiving of trouble, and a bringing of what is hurtful to birth.

[[v23-59-5]]

^<<v23-59-5,5>>^ The eggs of a poisonous snake are what they have hatched, and they kept weaving the mere cobweb of a spider. Anyone eating some of their eggs would die, and the &#91;egg&#93; that was smashed would be hatched into a viper.

[[v23-59-6]]

^<<v23-59-6,6>>^ Their mere cobweb will not serve as a garment, nor will they cover themselves with their works. Their works are hurtful works, and the activity of violence is in their palms.

[[v23-59-7]]

^<<v23-59-7,7>>^ Their own feet keep running to sheer badness, and they are in a hurry to shed innocent blood. Their thoughts are hurtful thoughts; despoiling and breakdown are in their highways.^&#42;1^

[NOTE]
====
. Lit., “wasting and ruin [are] in their tracks,” M; LXX, “ruin and misery are in their ways.” See Ro 3:16.
====

[[v23-59-8]]

^<<v23-59-8,8>>^ The way of peace they have ignored, and there is no justice in their tracks. Their roadways they have made crooked for themselves. No one at all treading in them^&#42;1^ will actually know peace.

[NOTE]
====
. “Them,” TSyVgc and one Heb. ms; 1QIsaM, “it.”
====

[[v23-59-9]]

^<<v23-59-9,9>>^ That is why justice has come to be far away from us, and righteousness does not catch up with us. We keep hoping for light, but, look! darkness; for brightness, &#91;but&#93; in continuous gloom we kept walking.

[[v23-59-10]]

^<<v23-59-10,10>>^ We keep groping for the wall just like blind men, and like those without eyes we keep groping. We have stumbled at high noon just as in evening darkness; among the stout ones &#91;we are&#93; just like dead people.

[[v23-59-11]]

^<<v23-59-11,11>>^ We keep groaning, all of us, just like bears; and like doves we mournfully keep cooing. We kept hoping for justice, but there was none; for salvation, &#91;but&#93; it has stayed far away from us.

[[v23-59-12]]

^<<v23-59-12,12>>^ For our revolts have become many in front of you; and as for our sins, each one has testified against us. For our revolts are with us; and as for our errors, we well know them.

[[v23-59-13]]

^<<v23-59-13,13>>^ There have been transgressing and a denying of Jehovah; and there was a moving back from our God,^&#42;1^ a speaking of oppression and revolt, a conceiving and a muttering of words of falsehood from the very heart.

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu.
====

[[v23-59-14]]

^<<v23-59-14,14>>^ And justice was forced to move back, and righteousness itself kept standing simply far off. For truth has stumbled even in the public square, and what is straightforward is unable to enter.

[[v23-59-15]]

^<<v23-59-15,15>>^ And the truth proves to be missing, and anyone turning away from badness is being despoiled.
And Jehovah got to see, and it was bad in his eyes that there was no justice.

[[v23-59-16]]

^<<v23-59-16,16>>^ And when he saw that there was no man,^&#42;1^ he began to show himself astonished that there was no one interposing. And his arm proceeded to save for him, and his own righteousness was the thing that supported him.

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v23-59-17]]

^<<v23-59-17,17>>^ Then he put on righteousness as a coat of mail, and the helmet of salvation upon his head. Furthermore, he put on the garments of vengeance as raiment and enwrapped himself with zeal as if a sleeveless coat.

[[v23-59-18]]

^<<v23-59-18,18>>^ In accordance with the dealings he will reward correspondingly, rage to his adversaries, due treatment to his enemies. To the islands^&#42;1^ he will recompense due treatment.

[NOTE]
====
. Or, “coastlands.”
====

[[v23-59-19]]

^<<v23-59-19,19>>^ And from the sunset they will begin to fear the name of Jehovah, and from the rising of the sun the glory of him, for he will come in like a distressing river,^&#42;1^ which the very spirit^&#42;2^ of Jehovah has driven along.

[NOTE]
====
. Or, “distress will come in like a river.”
. Or, “wind; blast.” See Ge 1:2 ftn, “Force.”
====

[[v23-59-20]]

^<<v23-59-20,20>>^ “And to Zion the Repurchaser will certainly come, and to those turning from transgression^&#42;1^ in Jacob,” is the utterance of Jehovah.

[NOTE]
====
. “And to those turning from transgression,” MVg; LXX, “and he shall turn away ungodly practices”; Sy, “and to those turning unrighteousness away.”
====

[[v23-59-21]]

^<<v23-59-21,21>>^ “And as for me, this is my covenant with them,” Jehovah has said.
“My spirit that is upon you^&#42;1^ and my words that I have put in your mouth—they will not be removed from your mouth or from the mouth of your offspring^&#42;2^ or from the mouth of the offspring of your offspring,” Jehovah has said, “from now on even to time indefinite.”

[NOTE]
====
. “You,” masc. sing.
. Lit., “seed.”
====

'''

xref:023-isaiah/023-isaiah-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaiah/023-isaiah-060.adoc#v23-60-0[Próximo Capítulo &#62;]