include::./index.adoc[]

[[v23-60-0]]
=== Isaiah, 60
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-60-1]]

^<<v23-60-1,1>>^ “Arise, O woman,^&#42;1^ shed forth light, for your light has come and upon you the very glory of Jehovah has shone forth.

[NOTE]
====
. “O woman,” because the one addressed as “you” and the verbs in Heb. are fem. sing. TLXXVgc, “O Jerusalem!”
====

[[v23-60-2]]

^<<v23-60-2,2>>^ For, look! darkness itself will cover the earth, and thick gloom the national groups; but upon you Jehovah will shine forth, and upon you his own glory will be seen.

[[v23-60-3]]

^<<v23-60-3,3>>^ And nations will certainly go to your light, and kings to the brightness of your shining forth.

[[v23-60-4]]

^<<v23-60-4,4>>^ “Raise your^&#42;1^ eyes all around and see! They have all of them been collected together; they have come to you. From far away your own sons keep coming, and your daughters who will be taken care of on the flank.

[NOTE]
====
. “Your,” fem. sing., as in vs 1.
====

[[v23-60-5]]

^<<v23-60-5,5>>^ At that time you will see^&#42;1^ and certainly become radiant, and your heart will actually quiver and expand, because to you the wealthiness of the sea will direct itself; the very resources of the nations will come to you.

[NOTE]
====
. “See,” 1QIsaMTLXXSyVg; 15 or more Heb. mss, “fear.”
====

[[v23-60-6]]

^<<v23-60-6,6>>^ The heaving mass of camels itself will cover you, the young male camels of Midʹi·an and of Eʹphah. All those from Sheʹba—they will come. Gold and frankincense they will carry. And the praises of Jehovah they will announce.

[[v23-60-7]]

^<<v23-60-7,7>>^ All the flocks of Keʹdar—they will be collected together to you. The rams of Ne·baʹioth—they will minister to you.^&#42;1^ With approval they will come up upon my altar, and I shall beautify my own house of beauty.

[NOTE]
====
. “They will minister (be attendants) to you.” Heb., yeshor·thuʹnekh; Lat., mi·ni·straʹbunt.
====

[[v23-60-8]]

^<<v23-60-8,8>>^ “Who are these that come flying just like a cloud, and like doves to their birdhouse holes?

[[v23-60-9]]

^<<v23-60-9,9>>^ For in me the islands themselves will keep hoping, the ships of Tarʹshish also as at the first, in order to bring your sons from far away, their silver and their gold being with them, to the name of Jehovah your God^&#42;1^ and to the Holy One of Israel, for he will have beautified you.

[NOTE]
====
. “Your God.” Heb., ʼElo·haʹyikh.
====

[[v23-60-10]]

^<<v23-60-10,10>>^ And foreigners^&#42;1^ will actually build your walls, and their own kings will minister^&#42;2^ to you; for in my indignation I shall have struck you, but in my goodwill I shall certainly have mercy upon you.

[NOTE]
====
. Lit., “sons of a foreign (country).”
. See vs 7 ftn.
====

[[v23-60-11]]

^<<v23-60-11,11>>^ “And your gates will actually be kept open^&#42;1^ constantly; they will not be closed even by day or by night, in order to bring to you the resources of the nations, and their kings will be taking the lead.

[NOTE]
====
. “Your gates will actually be kept open,” by a correction in agreement with TLXXSyVg; 1QIsaM, “open you your gates.”
====

[[v23-60-12]]

^<<v23-60-12,12>>^ For any nation and any kingdom that will not serve you will perish; and the nations themselves will without fail come to devastation.

[[v23-60-13]]

^<<v23-60-13,13>>^ “To you the very glory of Lebʹa·non will come, the juniper tree, the ash tree and the cypress at the same time, in order to beautify the place of my sanctuary; and I shall glorify the very place of my feet.

[[v23-60-14]]

^<<v23-60-14,14>>^ “And to you the sons of those afflicting you must go, bowing down; and all those treating you disrespectfully must bend down at the very soles of your feet, and they will have to call you the city of Jehovah, Zion of the Holy One of Israel.

[[v23-60-15]]

^<<v23-60-15,15>>^ “Instead of your proving to be one left entirely and hated, with nobody passing through, I will even set you as a thing of pride to time indefinite, an exultation for generation after generation.

[[v23-60-16]]

^<<v23-60-16,16>>^ And you will actually suck the milk of nations, and the breast of kings you will suck; and you will be certain to know that I, Jehovah, am your Savior, and the Powerful One of Jacob is your Repurchaser.^&#42;1^

[NOTE]
====
. Or, “I am Jehovah your Savior and your Repurchaser, the Powerful One of Jacob.”
====

[[v23-60-17]]

^<<v23-60-17,17>>^ Instead of the copper I shall bring in gold, and instead of the iron I shall bring in silver, and instead of the wood, copper, and instead of the stones, iron; and I will appoint peace as your overseers^&#42;1^ and righteousness as your task assigners.

[NOTE]
====
. Lit., “your oversight.”
====

[[v23-60-18]]

^<<v23-60-18,18>>^ “No more will violence be heard in your land, despoiling or breakdown within your boundaries. And you will certainly call your own walls Salvation and your gates Praise.

[[v23-60-19]]

^<<v23-60-19,19>>^ For you the sun will no more prove to be a light by day, and for brightness the moon itself will no more give you light. And Jehovah must become to you an indefinitely lasting light, and your God^&#42;1^ your beauty.

[NOTE]
====
. “And your God.” Heb., wEʼ·lo·haʹyikh.
====

[[v23-60-20]]

^<<v23-60-20,20>>^ No more will your sun set, nor will your moon go on the wane; for Jehovah himself will become for you an indefinitely lasting light, and the days of your mourning will have come to completion.

[[v23-60-21]]

^<<v23-60-21,21>>^ And as for your people, all of them will be righteous; to time indefinite they will hold possession of the land, the sprout of my^&#42;1^ planting, the work of my hands, for &#91;me&#93; to be beautified.

[NOTE]
====
. “My,” TSyVg and 14 or more Heb. mss; 1QIsa, “Jehovah’s”; M, “his.”
====

[[v23-60-22]]

^<<v23-60-22,22>>^ The little one himself will become a thousand, and the small one a mighty nation. I myself, Jehovah, shall speed it up in its own time.”

'''

xref:023-isaiah/023-isaiah-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaiah/023-isaiah-061.adoc#v23-61-0[Próximo Capítulo &#62;]