include::./index.adoc[]

[[v23-57-0]]
=== Isaiah, 57
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-57-1]]

^<<v23-57-1,1>>^ The righteous one himself has perished, but there is no one taking &#91;it&#93; to heart. And men of loving-kindness^&#42;1^ are being gathered &#91;to the dead&#93;, while no one discerns that it is because of the calamity that the righteous one has been gathered away.

[NOTE]
====
. Or, “loyal love.”
====

[[v23-57-2]]

^<<v23-57-2,2>>^ He enters into peace; they take rest upon their beds, &#91;each&#93; one that is walking straightforwardly.

[[v23-57-3]]

^<<v23-57-3,3>>^ “As for YOU men, come up close here, YOU sons of a soothsaying woman, the seed of an adulterous person and of a woman that commits prostitution:

[[v23-57-4]]

^<<v23-57-4,4>>^ Over whom is it that YOU have a jolly good time? Against whom do YOU keep opening wide the mouth, keep sticking out the tongue? Are YOU not the children of transgression, the seed of falsehood,

[[v23-57-5]]

^<<v23-57-5,5>>^ those who are working up passion among big trees, under every luxuriant tree, slaughtering the children in the torrent valleys under the clefts of the crags?

[[v23-57-6]]

^<<v23-57-6,6>>^ “With the smooth stones of the torrent valley was your^&#42;1^ portion. They—they were your lot. Moreover, to them you poured out a drink offering, you offered up a gift. For these things shall I comfort myself?

[NOTE]
====
. “Your,” fem. sing., referring to Zion, or Jerusalem.
====

[[v23-57-7]]

^<<v23-57-7,7>>^ Upon a mountain high and lifted up you set your bed. There also you went up to offer sacrifice.

[[v23-57-8]]

^<<v23-57-8,8>>^ And behind the door and the doorpost you set your memorial.^&#42;1^ For apart from me you uncovered &#91;yourself&#93; and proceeded to go up; you made your bed spacious. And for yourself you went concluding a covenant with them. You loved a bed with them. The male organ^&#42;2^ you beheld.

[NOTE]
====
. “Your memorial,” M(Heb., zikh·roh·nekhʹ)LXXSyVg; T, “memorial of your idols.” Some derive the Heb. word here from za·kharʹ, “a male,” and understand zikh·roh·nekhʹ to signify a phallic symbol.
. “The male organ.” Lit., “hand.” Heb., yadh.
====

[[v23-57-9]]

^<<v23-57-9,9>>^ And you proceeded to descend toward Melʹech^&#42;1^ with oil, and kept making your ointments abundant. And you continued sending your envoys far off, so that you lowered matters to Sheʹol.

[NOTE]
====
. Or, “the king.”
====

[[v23-57-10]]

^<<v23-57-10,10>>^ In the multitude of your ways you have toiled. You have not said, ‘It is hopeless!’ You have found a revival of your own power.^&#42;1^ That is why you have not grown sick.

[NOTE]
====
. Lit., “hand.”
====

[[v23-57-11]]

^<<v23-57-11,11>>^ “Whom did you^&#42;1^ become frightened at and begin to fear, so that you took up lying? But I was not the one that you remembered. You took nothing to your heart. Was I not keeping silent and hiding matters?^&#42;2^ So you were in no fear even of me.

[NOTE]
====
. “You,” fem. sing., referring to Zion, or Jerusalem.
. “And hiding matters,” by an adjustment in vowel pointing; M, “even from long ago.”
====

[[v23-57-12]]

^<<v23-57-12,12>>^ I myself shall tell forth your righteousness and your works, that they will not benefit you.

[[v23-57-13]]

^<<v23-57-13,13>>^ When you cry for aid your collection of things^&#42;1^ will not deliver you, but a wind^&#42;2^ will carry even all of them away. An exhalation will take them away, but the one taking refuge in me will inherit the land and will take possession of my holy mountain.

[NOTE]
====
. Evidently, “masses (of idols),” BDB, p. 868.
. “Wind.” Heb., ruʹach; Gr., aʹne·mos; Lat., venʹtus.
====

[[v23-57-14]]

^<<v23-57-14,14>>^ And one will certainly say,^&#42;1^ ‘Bank up, YOU people, bank up! Clear the way. Remove any obstacle from the way of my people.’”

[NOTE]
====
. “And they will say,” LXXSy; Vg, “And I will say.”
====

[[v23-57-15]]

^<<v23-57-15,15>>^ For this is what the High and Lofty One, who is residing forever and whose name is holy, has said: “In the height and in the holy place is where I reside, also with the one crushed and lowly in spirit,^&#42;1^ to revive the spirit of the lowly ones and to revive the heart of the ones being crushed.

[NOTE]
====
. “Spirit.” Heb., ruʹach.
====

[[v23-57-16]]

^<<v23-57-16,16>>^ For it will not be to time indefinite that I shall contend, nor perpetually that I shall be indignant; for because of me the spirit itself would grow feeble, even the breathing creatures^&#42;1^ that I myself have made.

[NOTE]
====
. Lit., “the breaths.” Compare Ps 150:6 ftn, “Thing.”
====

[[v23-57-17]]

^<<v23-57-17,17>>^ “At the erroneousness of his unjust gain I grew indignant, and I proceeded to strike him, concealing &#91;my face&#93;, while I was indignant. But he kept walking as a renegade in the way of his heart.

[[v23-57-18]]

^<<v23-57-18,18>>^ I have seen his very ways; and I began to heal him and conduct him and make compensation with comfort to him and to his mourning ones.”

[[v23-57-19]]

^<<v23-57-19,19>>^ “I am creating the fruit of the lips. Continuous peace^&#42;1^ there will be to the one that is far away and to the one that is near,” Jehovah has said, “and I will heal him.”

[NOTE]
====
. Lit., “Peace, peace.”
====

[[v23-57-20]]

^<<v23-57-20,20>>^ “But the wicked are like the sea that is being tossed, when it is unable to calm down, the waters of which keep tossing up seaweed and mire.

[[v23-57-21]]

^<<v23-57-21,21>>^ There is no peace,” my God^&#42;1^ has said, “for the wicked ones.”

[NOTE]
====
. “My God,” 1QIsaMTSyVg; LXXVgc, “Jehovah God”; about 50 Heb. mss, “Jehovah.”
====

'''

xref:023-isaiah/023-isaiah-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaiah/023-isaiah-058.adoc#v23-58-0[Próximo Capítulo &#62;]