include::./index.adoc[]

[[v23-38-0]]
=== Isaiah, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-38-1]]

^<<v23-38-1,1>>^ In those days Hez·e·kiʹah got sick to the point of dying. Accordingly Isaiah the son of Aʹmoz the prophet came in to him and said to him: “This is what Jehovah has said, ‘Give commands to your household, for you yourself will indeed die and will not live.’”

[[v23-38-2]]

^<<v23-38-2,2>>^ At that Hez·e·kiʹah turned his face to the wall and began to pray to Jehovah

[[v23-38-3]]

^<<v23-38-3,3>>^ and to say: “I beseech you, O Jehovah, remember, please, how I have walked before you in truthfulness and with a complete heart, and what was good in your eyes I have done.” And Hez·e·kiʹah began to weep profusely.^&#42;1^

[NOTE]
====
. Lit., “with a great weeping.”
====

[[v23-38-4]]

^<<v23-38-4,4>>^ And the word of Jehovah now occurred to Isaiah, saying:

[[v23-38-5]]

^<<v23-38-5,5>>^ “Go,^&#42;1^ and you must say to Hez·e·kiʹah, ‘This is what Jehovah the God of David your forefather has said: “I have heard your prayer. I have seen your tears. Here I am adding onto your days fifteen years;

[NOTE]
====
. Lit., “Let there be a going.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal. See Jer 2:2 ftn, “Go.”
====

[[v23-38-6]]

^<<v23-38-6,6>>^ and out of the palm of the king of As·syrʹi·a I shall deliver you and this city, and I will defend this city.

[[v23-38-7]]

^<<v23-38-7,7>>^ And this is the sign for you from Jehovah that Jehovah will perform this word that he has spoken:

[[v23-38-8]]

^<<v23-38-8,8>>^ Here I am making the shadow of the steps that had gone down on the steps &#91;of the stairs&#93; of Aʹhaz by the sun retrace backward ten steps.”’” And the sun gradually went back ten steps on the steps &#91;of the stairs&#93; that it had gone down.

[[v23-38-9]]

^<<v23-38-9,9>>^ A writing of Hez·e·kiʹah the king of Judah, when he got sick and revived from his sickness.

[[v23-38-10]]

^<<v23-38-10,10>>^ I myself said: “In the midst of my days I will go into the gates of Sheʹol.
I must be deprived of the remainder of my years.”

[[v23-38-11]]

^<<v23-38-11,11>>^ I have said: “I shall not see Jah, even Jah,^&#42;1^ in the land of the living ones.
I shall no more look on mankind^&#42;2^—with the inhabitants of &#91;the land of&#93; cessation.^&#42;3^

[NOTE]
====
. “Jah, even Jah.” Heb., Yah Yah; Sy, “Jehovah”; T, “the fear-inspiring One, Jehovah”; Lat., Doʹmi·num Doʹmi·num. See Ex 15:2 ftn, “Jah”; Ps 68:4 ftn.
. Or, “earthling man.” Heb., ʼa·dhamʹ.
. “Inhabitants of the system of things,” eight Heb. mss.
====

[[v23-38-12]]

^<<v23-38-12,12>>^ My own habitation^&#42;1^ has been pulled out and removed from me like the tent of shepherds.^&#42;2^
I have rolled up my life just like a loom worker;
One proceeds to cut me off from the very threads of the warp.^&#42;3^
From daylight till night you keep handing me over.

[NOTE]
====
. Or, “[circular] tent camp”; or, “generation.”
. By a slight correction; M, “of my shepherd.”
. Or, “from the thrum.”
====

[[v23-38-13]]

^<<v23-38-13,13>>^ I have soothed myself^&#42;1^ until the morning.
Like a lion, so he keeps breaking all my bones;
From daylight till night you keep handing me over.

[NOTE]
====
. “I have cried for help,” by a slight correction of M.
====

[[v23-38-14]]

^<<v23-38-14,14>>^ Like the swift, the bulbul, so I keep chirping;
I keep cooing like the dove.
My eyes have looked languishingly to the height:
‘O Jehovah,^&#42;1^ I am under oppression. Stand good for me.’

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-38-15]]

^<<v23-38-15,15>>^ What shall I speak, and &#91;what&#93; will he actually say to me?
He himself has also acted.
I keep walking solemnly all my years in the bitterness of my soul.

[[v23-38-16]]

^<<v23-38-16,16>>^ ‘O Jehovah,^&#42;1^ on that account they keep living; and as with everybody, thereby is the life of my spirit.
And you will restore me to health and certainly preserve me alive.

[NOTE]
====
. See vs 14 ftn.
====

[[v23-38-17]]

^<<v23-38-17,17>>^ Look! For peace I had what was bitter, yes, bitter;
And you yourself have become attached to my soul^&#42;1^ &#91;and kept it&#93; from the pit of disintegration.
For you have thrown behind your back all my sins.

[NOTE]
====
. “You yourself have held back my soul,” by changing one letter in M to agree with LXXVg.
====

[[v23-38-18]]

^<<v23-38-18,18>>^ For it is not Sheʹol that can laud you; death itself cannot praise you.
Those going down into the pit cannot look hopefully to your trueness.

[[v23-38-19]]

^<<v23-38-19,19>>^ The living, the living, he is the one that can laud you,
Just as I can this day.
The father himself can give knowledge to his own sons concerning your trueness.

[[v23-38-20]]

^<<v23-38-20,20>>^ O Jehovah, &#91;undertake&#93; to save me, and we shall play my string selections
All the days of our life at the house of Jehovah.’”

[[v23-38-21]]

^<<v23-38-21,21>>^ And Isaiah proceeded to say: “Let them take a cake of pressed dried figs and rub &#91;it&#93; in upon the boil, that he may revive.”

[[v23-38-22]]

^<<v23-38-22,22>>^ Meantime, Hez·e·kiʹah said: “What is the sign that I shall go up to the house of Jehovah?”

'''

xref:023-isaiah/023-isaiah-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaiah/023-isaiah-039.adoc#v23-39-0[Próximo Capítulo &#62;]