include::./index.adoc[]

[[v23-56-0]]
=== Isaiah, 56
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-56-1]]

^<<v23-56-1,1>>^ This is what Jehovah has said: “Keep justice,^&#42;1^ YOU people, and do what is righteous. For my salvation is at hand to come in, and my righteousness to be revealed.

[NOTE]
====
. Or, “judgment.”
====

[[v23-56-2]]

^<<v23-56-2,2>>^ Happy is the mortal man^&#42;1^ that does this, and the son of mankind^&#42;2^ that lays hold of it, keeping the sabbath in order not to profane it, and keeping his hand in order not to do any kind of badness.

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-56-3]]

^<<v23-56-3,3>>^ And let not the foreigner^&#42;1^ that has joined himself to Jehovah say, ‘Without doubt Jehovah will divide me off from his people.’ Neither let the eunuch say, ‘Look! I am a dry tree.’”

[NOTE]
====
. Lit., “son of the foreign (country).”
====

[[v23-56-4]]

^<<v23-56-4,4>>^ For this is what Jehovah has said to the eunuchs that keep my sabbaths and that have chosen what I have delighted in and that are laying hold of my covenant:

[[v23-56-5]]

^<<v23-56-5,5>>^ “I will even give to them in my house and within my walls a monument^&#42;1^ and a name, something better than sons and daughters. A name to time indefinite I shall give them,^&#42;2^ one that will not be cut off.

[NOTE]
====
. Lit., “a hand.” But see 1Sa 15:12; 2Sa 18:18.
. “Them,” 1QIsaTLXXSyVg; M, “him; each one.”
====

[[v23-56-6]]

^<<v23-56-6,6>>^ “And the foreigners that have joined themselves to Jehovah to minister to him and to love the name of Jehovah, in order to become servants to him, all those keeping the sabbath in order not to profane it and laying hold of my covenant,

[[v23-56-7]]

^<<v23-56-7,7>>^ I will also bring them to my holy mountain and make them rejoice inside my house of prayer. Their whole burnt offerings and their sacrifices will be for acceptance upon my altar. For my own house will be called even a house of prayer for all the peoples.”

[[v23-56-8]]

^<<v23-56-8,8>>^ The utterance of the Sovereign Lord Jehovah, who is collecting together the dispersed ones of Israel, is: “I shall collect together to him others besides those already collected together of his.”

[[v23-56-9]]

^<<v23-56-9,9>>^ All YOU wild animals of the open field, come to eat, all YOU wild animals in the forest.

[[v23-56-10]]

^<<v23-56-10,10>>^ His watchmen are blind. None of them have taken note. All of them are speechless dogs; they are not able to bark, panting, lying down, loving to slumber.

[[v23-56-11]]

^<<v23-56-11,11>>^ They are even dogs strong in soul&#91;ful desire&#93;; they have known no satisfaction. They are also shepherds that have not known how to understand. They have all of them turned to their own way, each one for his unjust gain from his own border:

[[v23-56-12]]

^<<v23-56-12,12>>^ “Come, men! Let me take some wine; and let us drink intoxicating liquor to the limit. And tomorrow will certainly turn out just as today, great in a very much larger way.”

'''

xref:023-isaiah/023-isaiah-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaiah/023-isaiah-057.adoc#v23-57-0[Próximo Capítulo &#62;]