include::./index.adoc[]

[[v23-33-0]]
=== Isaiah, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-33-1]]

^<<v23-33-1,1>>^ Woe to you who are despoiling, without you yourself being despoiled, and to you who are dealing treacherously, without &#91;others&#93; having dealt treacherously with you!^&#42;1^ As soon as you have finished as a despoiler, you will be despoiled. As soon as you have done with dealing treacherously, they will deal treacherously with you.

[NOTE]
====
. “You,” T, eight Heb. mss and four printed ed.; 1QIsaM, 20 Heb. mss and seven printed ed., “him.”
====

[[v23-33-2]]

^<<v23-33-2,2>>^ O Jehovah, show us favor. In you we have hoped. Become our^&#42;1^ arm every morning, yes, our salvation in the time of distress.

[NOTE]
====
. “Our,” TSyVgc and some Heb. mss; 1QIsaM and some Heb. mss, “their.”
====

[[v23-33-3]]

^<<v23-33-3,3>>^ At the sound of turmoil peoples have fled. At your arising nations have been dispersed.

[[v23-33-4]]

^<<v23-33-4,4>>^ And the spoil of YOU people will actually be gathered &#91;like&#93; the cockroaches when gathering in, like the onrush of locust swarms that is rushing against one.

[[v23-33-5]]

^<<v23-33-5,5>>^ Jehovah will certainly be put on high, for he is residing in the height. He must fill Zion with justice and righteousness.

[[v23-33-6]]

^<<v23-33-6,6>>^ And the trustworthiness of your times must prove to be a wealth of salvations—wisdom and knowledge, the fear of Jehovah, which is his treasure.

[[v23-33-7]]

^<<v23-33-7,7>>^ Look! Their very heroes^&#42;1^ have cried out in the street; the very messengers^&#42;2^ of peace will weep bitterly.

[NOTE]
====
. “Their very heroes.” Heb., ʼer·ʼel·lamʹ; the meaning is uncertain.
. Or, “envoys.”
====

[[v23-33-8]]

^<<v23-33-8,8>>^ The highways have been made desolate; the one passing over the path has ceased. He has broken the covenant; he has contemned the cities; he has taken no account of mortal man.^&#42;1^

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
====

[[v23-33-9]]

^<<v23-33-9,9>>^ The land^&#42;1^ has gone mourning, has withered away. Lebʹa·non has become abashed; it has moldered.^&#42;2^ Sharʹon has become like the desert plain; and Baʹshan and Carʹmel are shaking off &#91;their leaves&#93;.

[NOTE]
====
. Or, “earth.”
. Or, “it has been taken by lice.”
====

[[v23-33-10]]

^<<v23-33-10,10>>^ “Now I will rise up,” says Jehovah, “now I will exalt myself; now I will lift myself up.

[[v23-33-11]]

^<<v23-33-11,11>>^ YOU people conceive dried grass; YOU will give birth to stubble. YOUR own spirit, as a fire, will eat YOU up.

[[v23-33-12]]

^<<v23-33-12,12>>^ And peoples must become as the burnings of lime. As thorns cut away, they will be set ablaze even with fire.

[[v23-33-13]]

^<<v23-33-13,13>>^ Hear, YOU men who are far away, what I must do! And know, YOU who are nearby, my mightiness.

[[v23-33-14]]

^<<v23-33-14,14>>^ In Zion the sinners have come to be in dread; shivering has grabbed hold of the apostates: ‘Who of us can reside for any time with a devouring fire? Who of us can reside for any time with long-lasting conflagrations?’

[[v23-33-15]]

^<<v23-33-15,15>>^ “There is one who is walking in continual righteousness and speaking what is upright, who is rejecting the unjust gain from frauds, who is shaking his hands clear from taking hold on a bribe, who is stopping up his ear from listening to bloodshed, and who is closing his eyes so as not to see what is bad.

[[v23-33-16]]

^<<v23-33-16,16>>^ He is the one that will reside on the heights themselves; his secure height will be craggy places difficult to approach. His own bread will certainly be given &#91;him&#93;; his water supply will be unfailing.”

[[v23-33-17]]

^<<v23-33-17,17>>^ A king in his handsomeness is what your eyes will behold; they will see a land far away.

[[v23-33-18]]

^<<v23-33-18,18>>^ Your own heart will comment in low tones on a frightful thing: “Where is the secretary? Where is the one that does the paying out? Where is the one counting the towers?”

[[v23-33-19]]

^<<v23-33-19,19>>^ No insolent^&#42;1^ people will you see, a people too deep in language^&#42;2^ to listen to, of a stammering tongue without &#91;your&#93; understanding.

[NOTE]
====
. Or, “barbarous”; or, “presumptuous.”
. Lit., “lip.”
====

[[v23-33-20]]

^<<v23-33-20,20>>^ Behold Zion, the town of our festal occasions! Your own eyes will see Jerusalem an undisturbed abiding place, a tent that no one will pack up. Never will its tent pins be pulled out, and none of its ropes will be torn in two.

[[v23-33-21]]

^<<v23-33-21,21>>^ But there the Majestic One, Jehovah, will be for us a place of rivers, of wide^&#42;1^ canals. On it no galley fleet will go, and no majestic ship will pass over it.

[NOTE]
====
. Compare Ge 34:21 ftn, “Wide.”
====

[[v23-33-22]]

^<<v23-33-22,22>>^ For Jehovah is our Judge, Jehovah is our Statute-giver, Jehovah is our King; he himself will save us.

[[v23-33-23]]

^<<v23-33-23,23>>^ Your^&#42;1^ ropes must hang loose; their mast they will not hold firmly erect; they have not spread a sail.
At that time even spoil in abundance will have to be divided up; the lame ones themselves will actually take a big plunder.

[NOTE]
====
. “Your,” fem. sing.
====

[[v23-33-24]]

^<<v23-33-24,24>>^ And no resident will say: “I am sick.” The people that are dwelling in &#91;the land&#93;^&#42;1^ will be those pardoned for their error.

[NOTE]
====
. Lit., “it,” fem., referring to the land or earth, fem.
====

'''

xref:023-isaiah/023-isaiah-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaiah/023-isaiah-034.adoc#v23-34-0[Próximo Capítulo &#62;]