include::./index.adoc[]

[[v23-51-0]]
=== Isaiah, 51
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-51-1]]

^<<v23-51-1,1>>^ “Listen to me, YOU people who are pursuing after righteousness, YOU who are seeking to find Jehovah. Look to the rock from which YOU were hewn out, and to the hollow of the pit from which YOU were dug out.

[[v23-51-2]]

^<<v23-51-2,2>>^ Look to Abraham YOUR father and to Sarah who gradually brought YOU forth with childbirth pains. For he was one when I called him, and I proceeded to bless him and to make him many.

[[v23-51-3]]

^<<v23-51-3,3>>^ For Jehovah will certainly comfort Zion. He will for certain comfort all her devastated places, and he will make her wilderness like Eʹden and her desert plain like the garden^&#42;1^ of Jehovah. Exultation and rejoicing themselves will be found in her, thanksgiving and the voice of melody.

[NOTE]
====
. “Paradise,” LXXSy.
====

[[v23-51-4]]

^<<v23-51-4,4>>^ “Pay attention to me, O my people; and you national group of mine, to me give ear. For from me a law itself^&#42;1^ will go forth, and my judicial decision I shall cause to repose even as a light to the peoples.^&#42;2^

[NOTE]
====
. Or, “instruction itself.”
. “And my judicial decision as a light to peoples in an instant,” by a slight correction.
====

[[v23-51-5]]

^<<v23-51-5,5>>^ My righteousness is near. My salvation will certainly go forth, and my own arms will judge even the peoples. In me the islands themselves will hope, and for my arm they will wait.

[[v23-51-6]]

^<<v23-51-6,6>>^ “Raise YOUR eyes to the heavens themselves, and look at the earth beneath. For the very heavens must be dispersed in fragments just like smoke, and like a garment the earth itself will wear out, and its inhabitants themselves will die like a mere gnat. But as for my salvation, it will prove to be even to time indefinite, and my own righteousness will not be shattered.

[[v23-51-7]]

^<<v23-51-7,7>>^ “Listen to me, YOU the ones knowing righteousness, the people in whose heart is my law. Do not be afraid of the reproach of mortal men,^&#42;1^ and do not be struck with terror just because of their abusive words.

[NOTE]
====
. “Mortal men.” Heb., ʼenohshʹ.
====

[[v23-51-8]]

^<<v23-51-8,8>>^ For the moth^&#42;1^ will eat them up just as if a garment, and the clothes moth^&#42;2^ will eat them up just as if wool. But as for my righteousness, it will prove to be even to time indefinite, and my salvation to unnumbered generations.”^&#42;3^

[NOTE]
====
. “The moth.” Heb., ʽash.
. “The clothes moth.” Heb., sas.
. Lit., “to generation of generations.”
====

[[v23-51-9]]

^<<v23-51-9,9>>^ Awake, awake, clothe yourself with strength, O arm of Jehovah! Awake as in the days of long ago, as during the generations of times long past. Are you^&#42;1^ not the one that broke Raʹhab^&#42;2^ to pieces, that pierced the sea monster?^&#42;3^

[NOTE]
====
. “You,” fem., referring to “arm,” fem.
. Or, “the Stormer.” Vg, “the haughty (proud) one,” masc.
. “The dragon,” Vg.
====

[[v23-51-10]]

^<<v23-51-10,10>>^ Are you not the one that dried up the sea, the waters of the vast deep?^&#42;1^ The one that made the depths of the sea a way for the repurchased ones to go across?

[NOTE]
====
. “The . . . deep.” Heb., tehohmʹ; LXXVg, “the abyss.” Compare Ge 1:2 ftn, “Deep.”
====

[[v23-51-11]]

^<<v23-51-11,11>>^ Then the redeemed ones of Jehovah themselves will return and must come to Zion with a joyful outcry, and rejoicing to time indefinite will be upon their head. To exultation and rejoicing they will attain. Grief and sighing will certainly flee away.

[[v23-51-12]]

^<<v23-51-12,12>>^ “I—I myself am the One that is comforting YOU people.
“Who are you^&#42;1^ that you should be afraid of a mortal man that will die, and of a son of mankind^&#42;2^ that will be rendered as mere green grass?

[NOTE]
====
. “You,” fem. sing., referring to “Zion.”
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-51-13]]

^<<v23-51-13,13>>^ And that you should forget Jehovah your^&#42;1^ Maker, the One stretching out the heavens and laying the foundation of the earth, so that you were in dread constantly the whole day long on account of the rage of the one hemming &#91;you&#93; in, as though he was all set to bring &#91;you&#93; to ruin? And where is the rage of the one hemming &#91;you&#93; in?

[NOTE]
====
. “Your,” masc. sing.
====

[[v23-51-14]]

^<<v23-51-14,14>>^ “The one stooping in chains will certainly be loosened speedily, that he may not go in death to the pit and that his bread may not be lacking.

[[v23-51-15]]

^<<v23-51-15,15>>^ “But I, Jehovah, am your God,^&#42;1^ the One stirring up the sea that its waves may be boisterous. Jehovah of armies is his name.

[NOTE]
====
. “Your [masc. sing.] God [pl.].” Heb., ʼElo·heyʹkha.
====

[[v23-51-16]]

^<<v23-51-16,16>>^ And I shall put my words in your mouth, and with the shadow of my hand I shall certainly cover you, in order to plant the heavens and lay the foundation of the earth and say to Zion, ‘You are my people.’

[[v23-51-17]]

^<<v23-51-17,17>>^ “Rouse yourself, rouse yourself, rise up, O Jerusalem, you who have drunk at the hand of Jehovah his cup of rage. The goblet, the cup causing reeling, you have drunk, you have drained out.

[[v23-51-18]]

^<<v23-51-18,18>>^ There was none of all the sons that she brought to birth conducting her, and there was none of all the sons that she brought up taking hold of her hand.

[[v23-51-19]]

^<<v23-51-19,19>>^ Those two things were befalling you. Who will sympathize with you? Despoiling and breakdown, and hunger and sword! Who will^&#42;1^ comfort you?

[NOTE]
====
. “Who will?” 1QIsaLXXSyVg; M, “Who​—⁠I shall”; T, “None but I shall.”
====

[[v23-51-20]]

^<<v23-51-20,20>>^ Your own sons have swooned away. They have lain down at the head of all the streets like the wild sheep in the net, as those who are full of the rage of Jehovah, the rebuke of your God.”

[[v23-51-21]]

^<<v23-51-21,21>>^ Therefore listen to this, please, O woman afflicted and drunk, but not with wine.

[[v23-51-22]]

^<<v23-51-22,22>>^ This is what your Lord,^&#42;1^ Jehovah, even your God, who contends for his people, has said: “Look! I will take away from your hand the cup causing reeling. The goblet, my cup of rage—you will not repeat the drinking of it anymore.

[NOTE]
====
. “Your [fem. sing.] Lord.” Heb., ʼAdho·naʹyikh, pl. of ʼA·dhohnʹ, to denote grandeur or majesty.
====

[[v23-51-23]]

^<<v23-51-23,23>>^ And I will put it in the hand of the ones irritating you, who have said to your soul, ‘Bow down that we may cross over,’ so that you used to make your back just like the earth, and like the street for those crossing over.”

'''

xref:023-isaiah/023-isaiah-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaiah/023-isaiah-052.adoc#v23-52-0[Próximo Capítulo &#62;]