include::./index.adoc[]

[[v23-49-0]]
=== Isaiah, 49
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-49-1]]

^<<v23-49-1,1>>^ Listen to me, O YOU islands,^&#42;1^ and pay attention, YOU national groups far away. Jehovah himself has called me even from the belly. From the inward parts of my mother he has made mention of my name.

[NOTE]
====
. Or, “coastlands.”
====

[[v23-49-2]]

^<<v23-49-2,2>>^ And he proceeded to make my mouth like a sharp sword. In the shadow of his hand he has hidden me. And he gradually made me a polished^&#42;1^ arrow. He concealed me in his own quiver.

[NOTE]
====
. Or, “pointed.”
====

[[v23-49-3]]

^<<v23-49-3,3>>^ And he went on to say to me: “You are my servant, O Israel, you the one in whom I shall show my beauty.”

[[v23-49-4]]

^<<v23-49-4,4>>^ But as for me, I said: “It is for nothing that I have toiled. For unreality and vanity I have used up my own power. Truly my judgment is with Jehovah, and my wages with my God.”^&#42;1^

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ, pl.
====

[[v23-49-5]]

^<<v23-49-5,5>>^ And now Jehovah, the One forming me from the belly as a servant belonging to him, has said &#91;for me&#93; to bring back Jacob to him, in order that to him Israel itself may be gathered.^&#42;1^ And I shall be glorified in the eyes of Jehovah, and my own God will have become my strength.

[NOTE]
====
. “That to him Israel itself may be gathered,” 1QIsaMmarginAq; M, “and Israel, that was not being gathered.”
====

[[v23-49-6]]

^<<v23-49-6,6>>^ And he proceeded to say: “It has been more than a trivial matter for you to become my servant to raise up the tribes of Jacob and to bring back even the safeguarded ones of Israel; I also have given you for a light of the nations, that my salvation may come to be^&#42;1^ to the extremity^&#42;2^ of the earth.”

[NOTE]
====
. Or, “that you may become my salvation,” in agreement with LXXVg.
. See Jer 25:31, 33 ftns.
====

[[v23-49-7]]

^<<v23-49-7,7>>^ This is what Jehovah, the Repurchaser of Israel, his Holy One, has said to him that is despised in soul,^&#42;1^ to him that is detested by the nation,^&#42;2^ to the servant of rulers: “Kings themselves will see and certainly rise up, &#91;and&#93; princes, and they will bow down, by reason of Jehovah, who is faithful, the Holy One of Israel, who chooses you.”

[NOTE]
====
. Or, “whole-souled; thoroughly.” Heb., neʹphesh; Gr., psy·khenʹ; Lat., aʹni·mam.
. Lit., “for the soul to despise, for the nation to be detesting,” that is, to the one whom the soul despises, to the one whom the nation is detesting.
====

[[v23-49-8]]

^<<v23-49-8,8>>^ This is what Jehovah has said: “In a time of goodwill^&#42;1^ I have answered you, and in a day of salvation I have helped you; and I kept safeguarding you that I might give you as a covenant for the people,^&#42;2^ to rehabilitate the land, to bring about the repossessing of the desolated hereditary possessions,

[NOTE]
====
. Or, “In an acceptable time.”
. Sy adds: “and as a light to the peoples.”
====

[[v23-49-9]]

^<<v23-49-9,9>>^ to say to the prisoners,^&#42;1^ ‘Come out!’ to those who are in the darkness, ‘Reveal yourselves!’ By the ways they will pasture, and on all beaten paths^&#42;2^ their pasturing will be.

[NOTE]
====
. Or, “bound ones.”
. Or, “all bare hills.”
====

[[v23-49-10]]

^<<v23-49-10,10>>^ They will not go hungry, neither will they go thirsty, nor will parching heat or sun strike them. For the One who is having pity^&#42;1^ upon them will lead them, and by the springs of water he will conduct them.

[NOTE]
====
. Or, “mercy.”
====

[[v23-49-11]]

^<<v23-49-11,11>>^ And I will make all my mountains a way, and my highways themselves will be on an elevation.

[[v23-49-12]]

^<<v23-49-12,12>>^ Look! These will come even from far away, and, look! these from the north and from the west,^&#42;1^ and these from the land of Siʹnim.”^&#42;2^

[NOTE]
====
. Lit., “sea,” that is, the Mediterranean Sea to the west of Judah.
. “Sinim,” M; Syr., Sen·yam; TVg, “to the south”; LXX, “the Persians.”
====

[[v23-49-13]]

^<<v23-49-13,13>>^ Give a glad cry, YOU heavens, and be joyful, you earth. Let the mountains become cheerful with a glad outcry. For Jehovah has comforted his people, and he shows pity^&#42;1^ upon his own afflicted ones.

[NOTE]
====
. Or, “mercy.”
====

[[v23-49-14]]

^<<v23-49-14,14>>^ But Zion kept saying: “Jehovah has left me, and Jehovah^&#42;1^ himself has forgotten me.”

[NOTE]
====
. One of 134 scrib­al changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-49-15]]

^<<v23-49-15,15>>^ Can a wife forget her suckling so that she should not pity the son of her belly? Even these women can forget, yet I myself shall not forget you.^&#42;1^

[NOTE]
====
. “You,” fem., referring to “Zion.”
====

[[v23-49-16]]

^<<v23-49-16,16>>^ Look! Upon &#91;my&#93; palms^&#42;1^ I have engraved you. Your walls are in front of me constantly.

[NOTE]
====
. “The palms,” M; Sy, “the palms of my hands”; LXXVg, “my hands.”
====

[[v23-49-17]]

^<<v23-49-17,17>>^ Your sons have hurried up. The very ones tearing you down and devastating you will go forth even from you.

[[v23-49-18]]

^<<v23-49-18,18>>^ Raise your eyes all around and see. They have all of them been collected together. They have come to you. “As I am living,” is the utterance of Jehovah, “with all of them you will clothe yourself just as with ornaments, and you will bind them on yourself like a bride.

[[v23-49-19]]

^<<v23-49-19,19>>^ Although there are your devastated places and your desolated places and the land of your ruins, although now you are too cramped to be dwelling, and those swallowing you down have been far away,

[[v23-49-20]]

^<<v23-49-20,20>>^ yet in your own ears the sons of your bereaved state will say, ‘The place has become too cramped for me. Do make room for me, that I may dwell.’

[[v23-49-21]]

^<<v23-49-21,21>>^ And you will for certain say in your heart, ‘Who has become father to these for me, since I am a woman bereaved of children and sterile, gone into exile and taken prisoner?^&#42;1^ As for these, who has brought &#91;them&#93; up? Look! I myself had been left behind alone. These—where have they been?’”

[NOTE]
====
. “Taken prisoner,” by a slight correction; M, “turned (put) aside.”
====

[[v23-49-22]]

^<<v23-49-22,22>>^ This is what the Sovereign Lord Jehovah has said: “Look! I shall raise up my hand even to the nations, and to the peoples I shall lift up my signal.^&#42;1^ And they will bring your sons in the bosom, and upon the shoulder they will carry your own daughters.

[NOTE]
====
. “My signal.” Heb., nis·siʹ (from nes).
====

[[v23-49-23]]

^<<v23-49-23,23>>^ And kings must become caretakers for you, and their princesses^&#42;1^ nursing women for you. With faces^&#42;2^ to the earth they will bow down to you, and the dust of your feet they will lick up; and you will have to know that I am Jehovah, of whom those hoping in me will not be ashamed.”

[NOTE]
====
. Or, “noble ladies.”
. Lit., “noses.”
====

[[v23-49-24]]

^<<v23-49-24,24>>^ Can those already taken^&#42;1^ be taken from a mighty man himself, or can the body of captives of the tyrant^&#42;2^ make their escape?

[NOTE]
====
. Or, “the things [people] taken.”
. “Body of captives of the tyrant,” by a correction; M, “righteous body of captives.”
====

[[v23-49-25]]

^<<v23-49-25,25>>^ But this is what Jehovah has said: “Even the body of captives of the mighty man will be taken away, and those already taken by the tyrant himself will make their escape. And against anyone contending against you I myself shall contend, and your own sons I myself shall save.

[[v23-49-26]]

^<<v23-49-26,26>>^ And I will make those maltreating you eat their own flesh; and as with the sweet wine they will become drunk with their own blood. And all flesh will have to know that I, Jehovah, am your Savior and your Repurchaser, the Powerful One of Jacob.”

'''

xref:023-isaiah/023-isaiah-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaiah/023-isaiah-050.adoc#v23-50-0[Próximo Capítulo &#62;]