include::./index.adoc[]

[[v23-41-0]]
=== Isaiah, 41
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-41-1]]

^<<v23-41-1,1>>^ “Attend to me in silence, YOU islands;^&#42;1^ and let national groups themselves regain power. Let them approach. At that time let them speak. Let us come up close together for the judgment itself.

[NOTE]
====
. Or, “coastlands,” that is, of the Mediterranean Sea.
====

[[v23-41-2]]

^<<v23-41-2,2>>^ “Who has roused up &#91;someone&#93; from the sunrise? &#91;Who&#93; proceeded in righteousness to call him to His feet, to give before him the nations, and to make &#91;him&#93; go subduing even kings? &#91;Who&#93; kept giving &#91;them&#93; like dust to his sword, so that they have been driven about like mere stubble with his bow?

[[v23-41-3]]

^<<v23-41-3,3>>^ &#91;Who&#93; kept pursuing them, kept peacefully passing along on his feet over the path &#91;by which&#93; he did not proceed to come?

[[v23-41-4]]

^<<v23-41-4,4>>^ Who has been active and has done &#91;this&#93;, calling out the generations from the start?
“I, Jehovah, the First One; and with the last ones I am the same.”

[[v23-41-5]]

^<<v23-41-5,5>>^ The islands saw and began to fear. The very extremities of the earth began trembling. They drew near and kept coming.

[[v23-41-6]]

^<<v23-41-6,6>>^ They went helping each one his companion, and one would say to his brother: “Be strong.”

[[v23-41-7]]

^<<v23-41-7,7>>^ So the craftsman went strengthening the metalworker; the one doing the smoothing out with the forge hammer him that is hammering away at the anvil, saying regarding the soldering: “It is good.” Finally one fastened it with nails that it could not be made to totter.

[[v23-41-8]]

^<<v23-41-8,8>>^ “But you, O Israel, are my servant, you, O Jacob, whom I have chosen, the seed^&#42;1^ of Abraham my friend;^&#42;2^

[NOTE]
====
. Or, “offspring.”
. Or, “lover.”
====

[[v23-41-9]]

^<<v23-41-9,9>>^ you, whom I have taken hold of from the extremities of the earth, and you, whom I have called even from the remote parts of it. And so I said to you, ‘You are my servant; I have chosen you, and I have not rejected you.

[[v23-41-10]]

^<<v23-41-10,10>>^ Do not be afraid, for I am with you. Do not gaze about, for I am your God.^&#42;1^ I will fortify you. I will really help you. I will really keep fast hold of you with my right hand of righteousness.’

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
====

[[v23-41-11]]

^<<v23-41-11,11>>^ “Look! All those getting heated up against you will become ashamed and be humiliated. The men in a quarrel with you will become as nothing and will perish.

[[v23-41-12]]

^<<v23-41-12,12>>^ You will search for them, but you will not find them, those men in a struggle with you. They will become as something nonexistent and as nothing, those men at war with you.

[[v23-41-13]]

^<<v23-41-13,13>>^ For I, Jehovah your God, am grasping your right hand, the One saying to you, ‘Do not be afraid. I myself will help you.’

[[v23-41-14]]

^<<v23-41-14,14>>^ “Do not be afraid, you worm Jacob, YOU men^&#42;1^ of Israel. I myself will help you,”^&#42;2^ is the utterance of Jehovah, even your Repurchaser, the Holy One of Israel.

[NOTE]
====
. Or, “males.” Heb., methehʹ.
. “You,” fem. sing., referring to “worm.”
====

[[v23-41-15]]

^<<v23-41-15,15>>^ “Look! I have made you a threshing sledge, a new threshing instrument having double-edged &#91;teeth&#93;. You will tread down the mountains and crush &#91;them&#93;; and the hills you will make just like the chaff.

[[v23-41-16]]

^<<v23-41-16,16>>^ You will winnow them, and a wind itself will carry them away, and a windstorm itself will drive them different ways. And you yourself will be joyful in Jehovah. In the Holy One of Israel you will boast about yourself.”

[[v23-41-17]]

^<<v23-41-17,17>>^ “The afflicted ones and the poor ones are seeking for water, but there is none. Because of thirst their very tongue has become dry. I myself, Jehovah, shall answer them. I, the God of Israel,^&#42;1^ shall not leave them.

[NOTE]
====
. “The God of Israel.” Heb., ʼElo·hehʹ Yis·ra·ʼelʹ.
====

[[v23-41-18]]

^<<v23-41-18,18>>^ Upon bare hills I shall open up rivers, and in the midst of the valley plains, springs. I shall make the wilderness into a reedy pool of water, and the waterless land into sources of water.

[[v23-41-19]]

^<<v23-41-19,19>>^ In the wilderness I shall set the cedar tree, the acacia and the myrtle and the oil tree. In the desert plain^&#42;1^ I shall place the juniper tree, the ash and the cypress at the same time;

[NOTE]
====
. Or, “the Arabah.” See De 1:1 ftn, “Plains.”
====

[[v23-41-20]]

^<<v23-41-20,20>>^ in order that people may see and know and pay heed and have insight at the same time, that the very hand of Jehovah has done this, and the Holy One of Israel has himself created it.”

[[v23-41-21]]

^<<v23-41-21,21>>^ “Bring YOUR controversial case forward,” says Jehovah. “Produce YOUR arguments,” says the King of Jacob.

[[v23-41-22]]

^<<v23-41-22,22>>^ “Produce and tell to us the things that are going to happen. The first things—what they were—do tell, that we may apply our heart and know the future of them. Or cause us to hear even the things that are coming.

[[v23-41-23]]

^<<v23-41-23,23>>^ Tell the things that are to come afterward, that we may know that YOU are gods.^&#42;1^ Yes, YOU ought to do good or do bad, that we may gaze about and see &#91;it&#93; at the same time.

[NOTE]
====
. Lit., “that gods you are.” Heb., ki ʼelo·himʹ ʼat·temʹ.
====

[[v23-41-24]]

^<<v23-41-24,24>>^ Look! YOU are something nonexistent, and YOUR achievement is nothing. A detestable thing is anyone that chooses YOU.

[[v23-41-25]]

^<<v23-41-25,25>>^ “I have roused up &#91;someone&#93; from the north, and he will come. From the rising of the sun he will call upon my name. And he will come upon deputy rulers as &#91;if they were&#93; clay and just as a potter that tramples down the moist material.

[[v23-41-26]]

^<<v23-41-26,26>>^ “Who has told anything from the start, that we may know, or from times past, that we may say, ‘He is right’? Really there is no one telling. Really there is no one causing &#91;one&#93; to hear. Really there is no one that is hearing any sayings of YOU men.”

[[v23-41-27]]

^<<v23-41-27,27>>^ There is one first, &#91;saying&#93; to Zion: “Look! Here they are!” and to Jerusalem I shall give a bringer of good news.

[[v23-41-28]]

^<<v23-41-28,28>>^ And I kept seeing, and there was not a man; and out of these there was also no one that was giving counsel. And I kept asking them, that they might make a reply.

[[v23-41-29]]

^<<v23-41-29,29>>^ Look! All of them are something nonexistent.^&#42;1^ Their works are nothing. Their molten images are wind^&#42;2^ and unreality.

[NOTE]
====
. “Something nonexistent,” by a slight correction in agreement with 1QIsaTSy; M, “hurtfulness; something hurtful.”
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

'''

xref:023-isaiah/023-isaiah-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaiah/023-isaiah-042.adoc#v23-42-0[Próximo Capítulo &#62;]