include::./index.adoc[]

[[v23-23-0]]
=== Isaiah, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-23-1]]

^<<v23-23-1,1>>^ The pronouncement of Tyre:^&#42;1^ Howl, YOU ships of Tarʹshish! for it has been despoiled from &#91;being&#93; a port,^&#42;2^ from &#91;being a place&#93; to enter in. From the land of Kitʹtim^&#42;3^ it has been revealed to them.

[NOTE]
====
. Meaning “Rock.” Heb., Tsor.
. Lit., “house.”
. Or, “the Cypriots.”
====

[[v23-23-2]]

^<<v23-23-2,2>>^ Be silent, YOU inhabitants of the coastland.^&#42;1^ The merchants from Siʹdon, the ones crossing over the sea—they have filled you.

[NOTE]
====
. Or, “island.”
====

[[v23-23-3]]

^<<v23-23-3,3>>^ And on many waters has been the seed of Shiʹhor, the harvest of the Nile, her revenue; and it came to be the profit of the nations.

[[v23-23-4]]

^<<v23-23-4,4>>^ Be ashamed, O Siʹdon; because the sea, O you stronghold of the sea, has said: “I have not had birth pains, and I have not given birth, nor have I brought up young men, raised up virgins.”

[[v23-23-5]]

^<<v23-23-5,5>>^ Just as at the report pertaining to Egypt, people will likewise be in severe pains at the report on Tyre.

[[v23-23-6]]

^<<v23-23-6,6>>^ Cross over to Tarʹshish; howl, YOU inhabitants of the coastland.

[[v23-23-7]]

^<<v23-23-7,7>>^ Is this YOUR &#91;city&#93; that was exultant from days of long ago, &#91;from&#93; her early times? Her feet used to bring her far away to reside as an alien.

[[v23-23-8]]

^<<v23-23-8,8>>^ Who is it that has given this counsel against Tyre, the bestower of crowns, whose merchants were princes, whose tradesmen were the honorable ones of the earth?

[[v23-23-9]]

^<<v23-23-9,9>>^ Jehovah of armies himself has given this counsel, to profane the pride of all beauty, to treat with contempt all the honorable ones of the earth.

[[v23-23-10]]

^<<v23-23-10,10>>^ Cross over your land like the Nile River, O daughter of Tarʹshish. There is no shipyard any longer.

[[v23-23-11]]

^<<v23-23-11,11>>^ His hand he has stretched out over the sea; he has caused kingdoms to be agitated. Jehovah himself has given a command against Phoe·niʹcia,^&#42;1^ to annihilate her^&#42;2^ strongholds.

[NOTE]
====
. Lit., “Canaan”; or, “merchant land.” See Ge 10:15; 1Ch 1:13.
. Or, “its.”
====

[[v23-23-12]]

^<<v23-23-12,12>>^ And he says: “You must never again exult, O oppressed one, the virgin daughter of Siʹdon. Get up, cross over to Kitʹtim itself. Even there it will not be restful for you.”

[[v23-23-13]]

^<<v23-23-13,13>>^ Look! The land of the Chal·deʹans. This is the people—As·syrʹi·a did not prove to be &#91;the one&#93;—they founded her for the desert haunters. They have erected their siege towers; they have stripped bare her dwelling towers; one has set her as a crumbling ruin.

[[v23-23-14]]

^<<v23-23-14,14>>^ Howl, YOU ships of Tarʹshish, for YOUR stronghold has been despoiled.

[[v23-23-15]]

^<<v23-23-15,15>>^ And it must occur in that day that Tyre must be forgotten seventy years, the same as the days of one king. At the end of seventy years it will happen to Tyre as in the song of a prostitute:^&#42;1^

[NOTE]
====
. Or, “harlot.”
====

[[v23-23-16]]

^<<v23-23-16,16>>^ “Take a harp, go around the city, O forgotten prostitute. Do your best at playing on the strings; make your songs many, in order that you may be remembered.”

[[v23-23-17]]

^<<v23-23-17,17>>^ And it must occur at the end of seventy years that Jehovah will turn his attention to Tyre, and she must return to her hire and commit prostitution with all the kingdoms of the earth upon the surface of the ground.

[[v23-23-18]]

^<<v23-23-18,18>>^ And her profit and her hire must become something holy to Jehovah. It will not be stored up, nor be laid up, because her hire will come to be for those dwelling before Jehovah, for eating to satisfaction and for elegant covering.

'''

xref:023-isaiah/023-isaiah-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaiah/023-isaiah-024.adoc#v23-24-0[Próximo Capítulo &#62;]