include::./index.adoc[]

[[v23-11-0]]
=== Isaiah, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-11-1]]

^<<v23-11-1,1>>^ And there must go forth a twig out of the stump^&#42;1^ of Jesʹse; and out of his roots a sprout^&#42;2^ will be fruitful.^&#42;3^

[NOTE]
====
. Or, “rootstock.”
. “And . . . a sprout.” Heb., weneʹtser. See Mt 2:23 ftns.
. “Will be fruitful,” 1QIsaM; LXXSyVg, “will shoot up”; T reads, “And there will go forth a king from the sons of Jesse, and from the sons of his sons the Messiah (Christ) himself will be brought up.”
====

[[v23-11-2]]

^<<v23-11-2,2>>^ And upon him the spirit^&#42;1^ of Jehovah must settle down, the spirit of wisdom and of understanding, the spirit of counsel and of mightiness, the spirit of knowledge and of the fear of Jehovah;

[NOTE]
====
. “Spirit of.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. See Ge 1:2 ftn, “Force.”
====

[[v23-11-3]]

^<<v23-11-3,3>>^ and there will be enjoyment by him in the fear of Jehovah.
And he will not judge by any mere appearance to his eyes, nor reprove simply according to the thing heard by his ears.

[[v23-11-4]]

^<<v23-11-4,4>>^ And with righteousness he must judge the lowly ones, and with uprightness he must give reproof in behalf of the meek ones of the earth. And he must strike the earth^&#42;1^ with the rod of his mouth; and with the spirit of his lips he will put the wicked one to death.

[NOTE]
====
. “The earth.” Heb., ʼeʹrets; according to a correction suggested in Gins., ʽa·ritsʹ, “the tyrant.” Compare 13:11 ftn, “Tyrants.”
====

[[v23-11-5]]

^<<v23-11-5,5>>^ And righteousness must prove to be the belt of his hips, and faithfulness the belt of his loins.

[[v23-11-6]]

^<<v23-11-6,6>>^ And the wolf will actually reside for a while with the male lamb, and with the kid the leopard itself will lie down, and the calf and the maned young lion and the well-fed animal all together; and a mere little boy will be leader over them.^&#42;1^

[NOTE]
====
. Or, “will be leading among them.”
====

[[v23-11-7]]

^<<v23-11-7,7>>^ And the cow and the bear themselves will feed; together their young ones will lie down. And even the lion will eat straw just like the bull.

[[v23-11-8]]

^<<v23-11-8,8>>^ And the sucking child will certainly play upon the hole of the cobra; and upon the light aperture^&#42;1^ of a poisonous snake will a weaned child actually put his own hand.

[NOTE]
====
. Or, “young one.” LXX, “lair”; Vg, “cavern; hollow.”
====

[[v23-11-9]]

^<<v23-11-9,9>>^ They will not do any harm or cause any ruin in all my holy mountain; because the earth^&#42;1^ will certainly be filled with the knowledge of Jehovah as the waters are covering the very sea.^&#42;2^

[NOTE]
====
. Or, “land.”
. Or, “sea basin.”
====

[[v23-11-10]]

^<<v23-11-10,10>>^ And it must occur in that day that there will be the root of Jesʹse that will be standing up as a signal^&#42;1^ for the peoples. To him even the nations will turn inquiringly, and his resting-place must become glorious.

[NOTE]
====
. “As a signal.” Heb., lenesʹ; Lat., in siʹgnum.
====

[[v23-11-11]]

^<<v23-11-11,11>>^ And it must occur in that day that Jehovah^&#42;1^ will again offer his hand, a second time, to acquire the remnant^&#42;2^ of his people who will remain over from As·syrʹi·a and from Egypt and from Pathʹros and from Cush^&#42;3^ and from Eʹlam and from Shiʹnar^&#42;4^ and from Haʹmath and from the islands of the sea.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. Or, “those remaining over.”
. “Cush,” 1QIsaMSy; LXXVg, “Ethiopia”; T, “India.”
. “Shinar,” MVg; T, “Babel (Babylonia)”; Sy, “Seir.”
====

[[v23-11-12]]

^<<v23-11-12,12>>^ And he will certainly raise up a signal^&#42;1^ for the nations and gather the dispersed ones of Israel; and the scattered ones^&#42;2^ of Judah he will collect together from the four extremities^&#42;3^ of the earth.

[NOTE]
====
. See vs 10 ftn.
. “Ones,” fem.
. Lit., “wings.”
====

[[v23-11-13]]

^<<v23-11-13,13>>^ And the jealousy of Eʹphra·im must depart, and even those showing hostility to Judah will be cut off. Eʹphra·im itself will not be jealous of Judah, nor will Judah show hostility toward Eʹphra·im.

[[v23-11-14]]

^<<v23-11-14,14>>^ And they must fly at the shoulder of the Phi·lisʹtines to the west;^&#42;1^ together they will plunder the sons of the East.^&#42;2^ Eʹdom and Moʹab will be those upon whom they will thrust out their hand, and the sons of Amʹmon will be their subjects.

[NOTE]
====
. Lit., “sea.”
. Or, “the Orientals.”
====

[[v23-11-15]]

^<<v23-11-15,15>>^ And Jehovah will certainly cut off^&#42;1^ the tongue of the Egyptian sea, and wave his hand at the River in the glow^&#42;2^ of his spirit. And he must strike it in &#91;its&#93; seven torrents, and he will actually cause people to walk in &#91;their&#93; sandals.

[NOTE]
====
. “Cut off,” KB, p. 334; by another der­ivation of the Heb. verb, “devote to destruction; banish.” Compare Le 21:18, “with his nose slit.”
. “Glow,” BDB, p. 744; by a correction according to KB, p. 728, “full might.”
====

[[v23-11-16]]

^<<v23-11-16,16>>^ And there must come to be a highway out of As·syrʹi·a for the remnant of his people who will remain over, just as there came to be &#91;one&#93; for Israel in the day of his coming up out of the land of Egypt.

'''

xref:023-isaiah/023-isaiah-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaiah/023-isaiah-012.adoc#v23-12-0[Próximo Capítulo &#62;]