include::./index.adoc[]

[[v23-28-0]]
=== Isaiah, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-28-1]]

^<<v23-28-1,1>>^ Woe to the eminent crown^&#42;1^ of the drunkards of Eʹphra·im, and the fading blossom of its^&#42;2^ decoration of beauty that is upon the head of the fertile valley^&#42;3^ of those overpowered by wine!

[NOTE]
====
. Lit., “the crown of eminence.”
. Or, “his.”
. Lit., “the valley of fatnesses [or, fertile soils].”
====

[[v23-28-2]]

^<<v23-28-2,2>>^ Look! Jehovah^&#42;1^ has someone strong and vigorous. Like a thunderous storm of hail, a destructive storm, like a thunderous storm of powerful, flooding waters, he will certainly do a casting down to the earth with force.^&#42;2^

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. Lit., “hand.”
====

[[v23-28-3]]

^<<v23-28-3,3>>^ With the feet the eminent crowns of the drunkards of Eʹphra·im will be trampled down.

[[v23-28-4]]

^<<v23-28-4,4>>^ And the fading flower of its decoration of beauty that is upon the head of the fertile valley must become like the early fig before summer, that, when the seer sees it, while it is yet in his palm, he swallows it down.

[[v23-28-5]]

^<<v23-28-5,5>>^ In that day Jehovah of armies will become as a crown of decoration and as a garland of beauty to the ones remaining over^&#42;1^ of his people,

[NOTE]
====
. Or, “to the remnant.”
====

[[v23-28-6]]

^<<v23-28-6,6>>^ and as a spirit of justice^&#42;1^ to the one sitting in the judgment, and as mightiness &#91;to&#93; those turning away the battle from the gate.

[NOTE]
====
. Or, “judgment.” Heb., mish·patʹ.
====

[[v23-28-7]]

^<<v23-28-7,7>>^ And these also—because of wine they have gone astray and because of intoxicating liquor they have wandered about. Priest and prophet—they have gone astray because of intoxicating liquor, they have become confused as a result of the wine, they have wandered about as a result of the intoxicating liquor; they have gone astray in their seeing, they have reeled as to decision.

[[v23-28-8]]

^<<v23-28-8,8>>^ For the tables themselves have all become full of filthy vomit—there is no place &#91;without it&#93;.

[[v23-28-9]]

^<<v23-28-9,9>>^ Whom will one instruct in knowledge, and whom will one make understand what has been heard?^&#42;1^ Those who have been weaned from the milk, those moved away from the breasts?

[NOTE]
====
. Or, “understand the report.”
====

[[v23-28-10]]

^<<v23-28-10,10>>^ For it is “command upon command, command upon command, measuring line upon measuring line, measuring line upon measuring line, here a little, there a little.”^&#42;1^

[NOTE]
====
. Lit., “For it is ’tsaw upon tsaw, tsaw upon tsaw, qaw upon qaw, qaw upon qaw, a little here, a little there,’ ” as an imitation of the sounds of the prophet’s speech. Heb., ki tsaw la·tsawʹ tsaw la·tsawʹ, qaw la·qawʹ qaw la·qawʹ, zeʽehrʹ sham zeʽehrʹ sham.
====

[[v23-28-11]]

^<<v23-28-11,11>>^ For by those stammering with their lips and by a different tongue he will speak to this people,

[[v23-28-12]]

^<<v23-28-12,12>>^ those to whom he has said: “This is the resting-place. GIVE rest to the weary one. And this is the place of ease,” but who were not willing to hear.

[[v23-28-13]]

^<<v23-28-13,13>>^ And to them the word of Jehovah will certainly become “command upon command, command upon command, measuring line upon measuring line, measuring line upon measuring line, here a little, there a little,” in order that they may go and certainly stumble backwards and actually be broken and ensnared and caught.

[[v23-28-14]]

^<<v23-28-14,14>>^ Therefore hear the word of Jehovah, YOU braggarts,^&#42;1^ YOU rulers of this people who are in Jerusalem:

[NOTE]
====
. Lit., “you men of bragging talk.”
====

[[v23-28-15]]

^<<v23-28-15,15>>^ Because YOU men have said: “We have concluded a covenant with Death; and with Sheʹol we have effected a vision;^&#42;1^ the overflowing flash flood, in case it should pass through, will not come to us, for we have made a lie our refuge and in falsehood we have concealed ourselves”;

[NOTE]
====
. Lit., “a seer,” M; T, “peace”; LXXVg, “pact(s).”
====

[[v23-28-16]]

^<<v23-28-16,16>>^ therefore this is what the Sovereign Lord Jehovah has said: “Here I am laying^&#42;1^ as a foundation in Zion a stone,^&#42;2^ a tried stone, the precious corner of a sure foundation.^&#42;3^ No one exercising faith will get panicky.^&#42;4^

[NOTE]
====
. “Here I am laying,” in agreement with TLXXSyVg; M, “Here I am, [the One that] has laid.”
. “In Zion a stone.” Heb., beTsi·yohnʹ ʼaʹven; Gr., Si·onʹ liʹthon; Lat., in Siʹon laʹpi·dem; Syr., beTs·hiun kiʼ·phaʼ; T(Aram.), beTsi·yohnʹ meʹlekh, “in Zion a king.”
. Or, “a corner of meeting for foundation with foundation.” The expression “a sure foundation” is lit., “foundation, foundation.”
. Or, “act hastily.”
====

[[v23-28-17]]

^<<v23-28-17,17>>^ And I will make justice^&#42;1^ the measuring line and righteousness the leveling instrument; and the hail must sweep away the refuge of a lie, and the waters themselves will flood out the very place of concealment.

[NOTE]
====
. Or, “judgment.” Heb., mish·patʹ.
====

[[v23-28-18]]

^<<v23-28-18,18>>^ And YOUR covenant with Death will certainly be dissolved,^&#42;1^ and that vision of YOURS with Sheʹol will not stand. The overflowing flash flood, when it passes through—YOU must also become for it a trampling place.

[NOTE]
====
. Lit., “and was covered.” Heb., wekhup·parʹ.
====

[[v23-28-19]]

^<<v23-28-19,19>>^ As often as it passes through, it will take YOU men away, because morning by morning it will pass through, during the day and during the night; and it must become nothing but a reason for quaking to make &#91;others&#93; understand what has been heard.”^&#42;1^

[NOTE]
====
. Or, “the report.”
====

[[v23-28-20]]

^<<v23-28-20,20>>^ For the couch has proved too short for stretching oneself on, and the woven sheet itself is &#91;too&#93; narrow when wrapping oneself up.

[[v23-28-21]]

^<<v23-28-21,21>>^ For Jehovah will rise up just as at Mount Pe·raʹzim, he will be agitated just as in the low plain near Gibʹe·on, that he may do his deed—his deed is strange—and that he may work his work^&#42;1^—his work is unusual.

[NOTE]
====
. Or, “his service.” Heb., ʽavo·dha·thohʹ.
====

[[v23-28-22]]

^<<v23-28-22,22>>^ And now do not show yourselves scoffers, in order that YOUR bands may not grow strong, for there is an extermination, even something decided upon, that I have heard of from the Sovereign Lord, Jehovah of armies, for all the land.^&#42;1^

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v23-28-23]]

^<<v23-28-23,23>>^ Give ear, YOU men, and listen to my voice; pay attention and listen to my saying.

[[v23-28-24]]

^<<v23-28-24,24>>^ Is it all day long that the plower plows in order to sow seed, that he loosens and harrows his ground?

[[v23-28-25]]

^<<v23-28-25,25>>^ Does he not, when he has smoothed out its surface, then scatter black cumin and sprinkle the cumin, and must he not put in wheat, millet,^&#42;1^ and barley in the appointed place,^&#42;2^ and spelt as his boundary?

[NOTE]
====
. “Wheat, millet.” Or, “wheat in rows.” The meaning of the second Heb. word is uncertain.
. Or, “in the appointed time”; or, “in the determined portion.” The meaning is uncertain.
====

[[v23-28-26]]

^<<v23-28-26,26>>^ And one corrects him according to what is right.^&#42;1^ His own God^&#42;2^ instructs him.

[NOTE]
====
. Or, “as to judgment.”
. “His own God.” Heb., ʼElo·havʹ.
====

[[v23-28-27]]

^<<v23-28-27,27>>^ For it is not with a threshing instrument that black cumin is given a treading; and upon cumin no wheel of a wagon is turned. For it is with a rod that black cumin is generally beaten out, and cumin with a staff.

[[v23-28-28]]

^<<v23-28-28,28>>^ Is breadstuff itself generally crushed? For never does one incessantly keep treading it out. And he must set the roller of his wagon in motion, and his own steeds, &#91;but&#93; he will not crush it.

[[v23-28-29]]

^<<v23-28-29,29>>^ This also is what has come forth from Jehovah of armies himself, who has been wonderful in counsel, who has done greatly in effectual working.

'''

xref:023-isaiah/023-isaiah-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaiah/023-isaiah-029.adoc#v23-29-0[Próximo Capítulo &#62;]