include::./index.adoc[]

[[v23-63-0]]
=== Isaiah, 63
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-63-1]]

^<<v23-63-1,1>>^ Who is this one coming from Eʹdom, the one with garments of glowing colors from Bozʹrah, this one who is honorable in his clothing, marching in the abundance of his power?
“I, the One speaking in righteousness, the One abounding &#91;in power&#93; to save.”

[[v23-63-2]]

^<<v23-63-2,2>>^ Why is it that your clothing is red, and your garments are like those of one treading in the winepress?

[[v23-63-3]]

^<<v23-63-3,3>>^ “The wine trough I have trodden by myself, while there was no man^&#42;1^ with me from the peoples. And I kept treading them in my anger, and I kept trampling them down in my rage. And their spurting blood kept spattering upon my garments, and all my clothing I have polluted.

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v23-63-4]]

^<<v23-63-4,4>>^ For the day of vengeance is in my heart, and the very year of my repurchased ones has come.

[[v23-63-5]]

^<<v23-63-5,5>>^ And I kept looking, but there was no helper; and I began to show myself astonished, but there was no one offering support. So my arm furnished me salvation, and my rage was what supported me.

[[v23-63-6]]

^<<v23-63-6,6>>^ And I kept stamping down peoples in my anger, and I proceeded to make them drunk^&#42;1^ with my rage and to bring down to the earth their spurting blood.”

[NOTE]
====
. “I proceeded to break them to pieces,” some Heb. mss and early printed ed.
====

[[v23-63-7]]

^<<v23-63-7,7>>^ The loving-kindnesses^&#42;1^ of Jehovah I shall mention, the praises of Jehovah, according to all that Jehovah has rendered to us, even the abundant goodness to the house of Israel that he has rendered to them according to his mercies and according to the abundance of his loving-kindnesses.

[NOTE]
====
. Or, “The acts of loyal love.”
====

[[v23-63-8]]

^<<v23-63-8,8>>^ And he went on to say: “Surely they are my people, sons that will not prove false.” So it was to them that he came to be a Savior.

[[v23-63-9]]

^<<v23-63-9,9>>^ During all their distress it was distressing to him.^&#42;1^ And his own personal messenger^&#42;2^ saved them. In his love and in his compassion he himself repurchased them, and he proceeded to lift them up and carry them all the days of long ago.

[NOTE]
====
. According to Mmargin and 17 Heb. mss; M, “During all their distress he was no adversary.”
. Lit., “And the messenger of his face.”
====

[[v23-63-10]]

^<<v23-63-10,10>>^ But they themselves rebelled and made his holy spirit feel hurt. He now was changed into an enemy of theirs; he himself warred against them.

[[v23-63-11]]

^<<v23-63-11,11>>^ And one^&#42;1^ began to remember the days of long ago, Moses his servant:^&#42;2^ “Where is the One that brought them up out of the sea with the shepherds^&#42;3^ of his flock? Where is the One that put within him His own holy spirit?

[NOTE]
====
. Or, “he.”
. “His servant,” Sy and some Heb. mss; 1QIsaMVg, “[and] his people.”
. “Shepherds,” 1QIsaMVg; TLXXSy and 11 Heb. mss, “shepherd.”
====

[[v23-63-12]]

^<<v23-63-12,12>>^ The One making His beautiful arm go at the right hand of Moses; the One splitting the waters from before them in order to make an indefinitely lasting name for his own self;

[[v23-63-13]]

^<<v23-63-13,13>>^ the One making them walk through the surging waters^&#42;1^ so that, like a horse in the wilderness, they did not stumble?

[NOTE]
====
. Or, “through the watery deeps.” Heb., bat·teho·mohthʹ.
====

[[v23-63-14]]

^<<v23-63-14,14>>^ Just as when a beast itself goes down into the valley plain, the very spirit of Jehovah proceeded to make them rest.”
Thus you led your people in order to make a beautiful name for your own self.

[[v23-63-15]]

^<<v23-63-15,15>>^ Look from heaven and see out of your lofty abode of holiness and beauty. Where are your zeal and your full might, the commotion of your inward parts, and your mercies? Toward me they have restrained themselves.^&#42;1^

[NOTE]
====
. Or, “mercies, [that] have restrained themselves even toward me?”
====

[[v23-63-16]]

^<<v23-63-16,16>>^ For you are our Father; although Abraham himself may not have known us and Israel himself may not recognize us, you, O Jehovah, are our Father. Our Repurchaser^&#42;1^ of long ago is your name.

[NOTE]
====
. “Our Repurchaser (Redeemer).” By extension of thought, “Our Avenger (Vindicator).” Heb., go·ʼaleʹnu; Lat., re·demʹptor noʹster. See Job 19:25 and Ps 19:14 ftns.
====

[[v23-63-17]]

^<<v23-63-17,17>>^ Why do you, O Jehovah, keep making us wander from your ways? Why do you make our heart hard against the fear of you? Come back for the sake of your servants, the tribes of your hereditary possession.

[[v23-63-18]]

^<<v23-63-18,18>>^ For a little while your holy people had possession. Our own adversaries have stamped down your sanctuary.

[[v23-63-19]]

^<<v23-63-19,19>>^ We have for a long time become as those over whom you did not rule, as those upon whom your name had not been called.

'''

xref:023-isaiah/023-isaiah-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaiah/023-isaiah-064.adoc#v23-64-0[Próximo Capítulo &#62;]