include::./index.adoc[]

[[v23-34-0]]
=== Isaiah, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-34-1]]

^<<v23-34-1,1>>^ Come up close, YOU nations, to hear; and YOU national groups, pay attention. Let the earth and that which fills it listen, the productive land^&#42;1^ and all its produce.

[NOTE]
====
. See 13:11 ftn, “Land.”
====

[[v23-34-2]]

^<<v23-34-2,2>>^ For Jehovah has indignation against all the nations, and rage against all their army. He must devote them to destruction; he must give them to the slaughter.

[[v23-34-3]]

^<<v23-34-3,3>>^ And their slain ones will be thrown out; and as for their carcasses, their stink will ascend; and the mountains must melt because of their blood.

[[v23-34-4]]

^<<v23-34-4,4>>^ And all those of the army of the heavens must rot away. And the heavens must be rolled up, just like a book scroll; and their army will all shrivel away, just as the leafage shrivels off the vine and like a shriveled &#91;fig&#93; off the fig tree.

[[v23-34-5]]

^<<v23-34-5,5>>^ “For in the heavens my sword will certainly be drenched. Look! Upon Eʹdom it will descend, and upon the people devoted by me to destruction in justice.

[[v23-34-6]]

^<<v23-34-6,6>>^ Jehovah has a sword; it must be filled with blood; it must be made greasy with the fat, with the blood of young rams and he-goats, with the fat of the kidneys of rams. For Jehovah has a sacrifice in Bozʹrah, and a great slaughtering in the land of Eʹdom.

[[v23-34-7]]

^<<v23-34-7,7>>^ And the wild bulls must come down with them, and young bulls with the powerful ones; and their land must be drenched with blood, and their very dust will be made greasy with the fat.”

[[v23-34-8]]

^<<v23-34-8,8>>^ For Jehovah has a day of vengeance, a year of retributions for the legal case over Zion.

[[v23-34-9]]

^<<v23-34-9,9>>^ And her^&#42;1^ torrents must be changed into pitch, and her dust into sulphur; and her land must become as burning pitch.

[NOTE]
====
. “Her,” referring to Bozrah, the capital of Edom.
====

[[v23-34-10]]

^<<v23-34-10,10>>^ By night or by day it will not be extinguished; to time indefinite its smoke will keep ascending. From generation to generation she will be parched; forever and ever no one will be passing across her.

[[v23-34-11]]

^<<v23-34-11,11>>^ And the pelican and the porcupine must take possession of her, and long-eared owls and ravens themselves will reside in her; and he must stretch out over her the measuring line of emptiness and the stones of wasteness.

[[v23-34-12]]

^<<v23-34-12,12>>^ Her nobles—there are none there whom they will call to the kingship itself, and her very princes will all become nothing.

[[v23-34-13]]

^<<v23-34-13,13>>^ On her dwelling towers thorns must come up, nettles and thorny weeds in her fortified places; and she must become an abiding place of jackals, the courtyard for the ostriches.^&#42;1^

[NOTE]
====
. See 13:21 ftn, “Ostriches.”
====

[[v23-34-14]]

^<<v23-34-14,14>>^ And haunters of waterless regions must meet up with howling animals, and even the goat-shaped demon will call to its companion. Yes, there the nightjar^&#42;1^ will certainly take its ease and find for itself a resting-place.

[NOTE]
====
. Heb., li·lithʹ; likely a nocturnal bird.
====

[[v23-34-15]]

^<<v23-34-15,15>>^ There the arrow snake has made its nest and lays &#91;eggs&#93;, and it must hatch &#91;them&#93; and gather &#91;them&#93; together under its shadow. Yes, there the gledes must collect themselves together, each one with her mate.

[[v23-34-16]]

^<<v23-34-16,16>>^ Search for yourselves in the book of Jehovah and read out loud: not one has been missing of them; they actually do not fail to have each one her mate, for it is the mouth of Jehovah^&#42;1^ that has given the command, and it is his spirit that has collected them together.

[NOTE]
====
. “The mouth of Jehovah,” five Heb. mss; 1QIsaSy, “his mouth”; LXX and Arabic, “Jehovah”; MVg, “my mouth.” See BHK and BHS ftns; see also App 1A.
====

[[v23-34-17]]

^<<v23-34-17,17>>^ And it is He that has cast for them the lot, and his own hand has apportioned the place^&#42;1^ to them by the measuring line. To time indefinite they will take possession of it; for generation after generation they will reside in it.

[NOTE]
====
. Lit., “her.” Or, “it.” That is, a place, such as Bozrah.
====

'''

xref:023-isaiah/023-isaiah-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaiah/023-isaiah-035.adoc#v23-35-0[Próximo Capítulo &#62;]