include::./index.adoc[]

[[v23-13-0]]
=== Isaiah, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-13-1]]

^<<v23-13-1,1>>^ The pronouncement against Babylon^&#42;1^ that Isaiah^&#42;2^ the son of Aʹmoz saw in vision:

[NOTE]
====
. “Babylon,” LXXVg; 1QIsaMTSy, “Babel.”
. Heb., Yeshaʽ·yaʹhu.
====

[[v23-13-2]]

^<<v23-13-2,2>>^ “Upon a mountain of bare rocks^&#42;1^ raise up a signal,^&#42;2^ YOU men. Lift up the voice to them, wave the hand, that they may come into the entrances of the nobles.

[NOTE]
====
. Lit., “mountain swept bare.”
. “Signal.” Heb., nes.
====

[[v23-13-3]]

^<<v23-13-3,3>>^ I myself have issued the command to my sanctified ones.^&#42;1^ I have also called my mighty ones for &#91;expressing&#93; my anger, my eminently exultant ones.

[NOTE]
====
. “To my sanctified ones,” that is, sanctified for Jehovah’s war. Heb., lim·qud·da·shaiʹ; Lat., sanc·ti·fi·caʹtis meʹis. Compare Joe 3:9 (4:9 in M).
====

[[v23-13-4]]

^<<v23-13-4,4>>^ Listen!^&#42;1^ A crowd in the mountains, something like a numerous people! Listen!^&#42;2^ The uproar of kingdoms, of nations gathered together! Jehovah of armies is mustering the army of war.

[NOTE]
====
. Lit., “The sound of.” See Ge 4:10 ftn, “Listen.”
. Lit., “The sound of.”
====

[[v23-13-5]]

^<<v23-13-5,5>>^ They are coming from the land far away, from the extremity of the heavens, Jehovah and the weapons of his denunciation, to wreck all the earth.

[[v23-13-6]]

^<<v23-13-6,6>>^ “Howl, YOU people, for the day of Jehovah is near! As a despoiling from the Almighty^&#42;1^ it will come.

[NOTE]
====
. “From the Almighty.” Heb., mish·Shad·daiʹ. Compare 9:6 ftn, “God.”
====

[[v23-13-7]]

^<<v23-13-7,7>>^ That is why all hands themselves will drop down, and the whole heart itself of mortal man will melt.

[[v23-13-8]]

^<<v23-13-8,8>>^ And people have become disturbed. Convulsions and birth pains themselves grab hold; like a woman that is giving birth they have labor pains. They look at each other in amazement. Their faces are inflamed faces.

[[v23-13-9]]

^<<v23-13-9,9>>^ “Look! The day of Jehovah itself is coming, cruel both with fury and with burning anger, in order to make the land an object of astonishment, and that it may annihilate &#91;the land’s&#93;^&#42;1^ sinners out of it.

[NOTE]
====
. Or, “its.” Lit., “her.”
====

[[v23-13-10]]

^<<v23-13-10,10>>^ For the very stars of the heavens and their constellations of Keʹsil^&#42;1^ will not flash forth their light; the sun will actually grow dark at its going forth, and the moon itself will not cause its light to shine.

[NOTE]
====
. Lit., “and their Kesils.” See Job 9:9 ftn, “Kesil constellation.”
====

[[v23-13-11]]

^<<v23-13-11,11>>^ And I shall certainly bring home &#91;its own&#93; badness upon the productive land,^&#42;1^ and their own error upon the wicked themselves. And I shall actually cause the pride of the presumptuous ones to cease, and the haughtiness of the tyrants^&#42;2^ I shall abase.

[NOTE]
====
. “Productive land.” Heb., te·velʹ; Gr., oi·kou·meʹnei, “inhabited earth”; Lat., orʹbis, “circle,” that is, of the earth. See Mt 24:14 ftn, “Earth.”
. “Tyrants.” Heb., ʽa·ri·tsimʹ.
====

[[v23-13-12]]

^<<v23-13-12,12>>^ I shall make mortal man rarer than refined gold,^&#42;1^ and earthling man &#91;rarer&#93; than the gold^&#42;2^ of Oʹphir.

[NOTE]
====
. “Than refined gold.” Heb., mip·pazʹ.
. “Than the gold of.” Heb., mik·keʹthem. See Job 28:16 ftn.
====

[[v23-13-13]]

^<<v23-13-13,13>>^ That is why I shall cause heaven itself to become agitated, and the earth will rock out of its place at the fury of Jehovah of armies and at the day of his burning anger.

[[v23-13-14]]

^<<v23-13-14,14>>^ And it must occur that, like a gazelle chased away and like a flock without anyone to collect them together, they will turn, each one to his own people; and they will flee, each one to his own land.

[[v23-13-15]]

^<<v23-13-15,15>>^ Every one that is found will be pierced through, and every one that is caught in the sweep will fall by the sword;

[[v23-13-16]]

^<<v23-13-16,16>>^ and their very children will be dashed to pieces before their eyes. Their houses will be pillaged, and their own wives will be raped.

[[v23-13-17]]

^<<v23-13-17,17>>^ “Here I am arousing against them the Medes, who account silver itself as nothing and who, as respects gold, take no delight in it.

[[v23-13-18]]

^<<v23-13-18,18>>^ And &#91;their&#93; bows will dash even young men to pieces. And the fruitage of the belly they will not pity; for sons their eye will not feel sorry.

[[v23-13-19]]

^<<v23-13-19,19>>^ And Babylon, the decoration of kingdoms, the beauty of the pride of the Chal·deʹans, must become as when God^&#42;1^ overthrew Sodʹom and Go·morʹrah.

[NOTE]
====
. “God.” 1QIsaM(Heb.), ʼElo·himʹ; Gr., ho The·osʹ; TVgc, “Jehovah.”
====

[[v23-13-20]]

^<<v23-13-20,20>>^ She will never be inhabited, nor will she reside for generation after generation. And there the Arab will not pitch his tent, and no shepherds will let &#91;their flocks&#93; lie down there.

[[v23-13-21]]

^<<v23-13-21,21>>^ And there the haunters of waterless regions^&#42;1^ will certainly lie down, and their houses must be filled with eagle owls.^&#42;2^ And there the ostriches^&#42;3^ must reside, and goat-shaped demons^&#42;4^ themselves will go skipping about there.

[NOTE]
====
. “The haunters of waterless regions.” Or, “the demons.” T, “apes”; LXXSyVg, “wild beasts.”
. “Dragons,” Vg.
. Lit., “daughters of an ostrich.”
. Or, “hairy creatures.” TLXXSy, “demons”; Vg, “shaggy creatures.” Compare Le 17:7 ftn, “Demons”; 2Ch 11:15 ftn.
====

[[v23-13-22]]

^<<v23-13-22,22>>^ And jackals must howl in her dwelling towers, and the big snake will be in the palaces of exquisite delight. And the season for her is near to come, and her days themselves will not be postponed.”

'''

xref:023-isaiah/023-isaiah-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaiah/023-isaiah-014.adoc#v23-14-0[Próximo Capítulo &#62;]