include::./index.adoc[]

[[v23-37-0]]
=== Isaiah, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-37-1]]

^<<v23-37-1,1>>^ And it came about that as soon as King Hez·e·kiʹah heard, he immediately ripped his garments apart and covered himself with sackcloth and came into the house of Jehovah.

[[v23-37-2]]

^<<v23-37-2,2>>^ Further, he sent E·liʹa·kim, who was over the household, and Shebʹna the secretary and the older men^&#42;1^ of the priests covered with sackcloth to Isaiah the son of Aʹmoz the prophet.

[NOTE]
====
. Or, “elders.”
====

[[v23-37-3]]

^<<v23-37-3,3>>^ And they proceeded to say to him: “This is what Hez·e·kiʹah has said, ‘This day is a day of distress and of rebuke and of scornful insolence, for the sons have come as far as the womb’s mouth,^&#42;1^ and there is no power to give birth.

[NOTE]
====
. Lit., “the place of breaking through.” Compare 66:9.
====

[[v23-37-4]]

^<<v23-37-4,4>>^ Perhaps Jehovah your God^&#42;1^ will hear the words of Rabʹsha·keh, whom the king of As·syrʹi·a his lord^&#42;2^ sent to taunt the living God,^&#42;3^ and he will actually call him to account for the words that Jehovah your God has heard. And you must lift up prayer in behalf of the remnant that are to be found.’”

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
. “His lord.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence.
. “The living God.” Heb., ʼElo·himʹ chai; the adjective chai, “living,” is sing., although ʼElo·himʹ is pl.
====

[[v23-37-5]]

^<<v23-37-5,5>>^ So the servants of King Hez·e·kiʹah came in to Isaiah.

[[v23-37-6]]

^<<v23-37-6,6>>^ Then Isaiah said to them: “This is what YOU should say to YOUR lord, ‘This is what Jehovah has said: “Do not be afraid because of the words that you have heard with which the attendants of the king of As·syrʹi·a spoke abusively of me.

[[v23-37-7]]

^<<v23-37-7,7>>^ Here I am putting a spirit in him, and he must hear a report and return to his own land; and I shall certainly cause him to fall by the sword in his own land.”’”

[[v23-37-8]]

^<<v23-37-8,8>>^ After that Rabʹsha·keh returned and found the king of As·syrʹi·a fighting against Libʹnah, for he had heard that he had pulled away from Laʹchish.

[[v23-37-9]]

^<<v23-37-9,9>>^ Now he heard it said concerning Tir·haʹkah the king of E·thi·oʹpi·a:^&#42;1^ “He has come out to fight against you.” When he heard, he at once sent messengers to Hez·e·kiʹah, saying:

[NOTE]
====
. “Ethiopia,” Vg; LXX, “the Ethiopians”; MTSy, “Cush.”
====

[[v23-37-10]]

^<<v23-37-10,10>>^ “This is what YOU men should say to Hez·e·kiʹah the king of Judah, ‘Do not let your God in whom you are trusting deceive you, saying: “Jerusalem will not be given into the hand of the king of As·syrʹi·a.”

[[v23-37-11]]

^<<v23-37-11,11>>^ Look! You yourself have heard what the kings of As·syrʹi·a did to all the lands by devoting them to destruction, and will you yourself be delivered?

[[v23-37-12]]

^<<v23-37-12,12>>^ Have the gods of the nations that my forefathers brought to ruin delivered them, even Goʹzan and Haʹran and Reʹzeph and the sons of Eʹden that were in Tel-asʹsar?

[[v23-37-13]]

^<<v23-37-13,13>>^ Where is the king of Haʹmath and the king of Arʹpad and the king of the city of Seph·ar·vaʹim—of Heʹna and of Ivʹvah?’”

[[v23-37-14]]

^<<v23-37-14,14>>^ Then Hez·e·kiʹah took the letters out of the hand of the messengers and read them, after which Hez·e·kiʹah went up to the house of Jehovah and spread it out before Jehovah.

[[v23-37-15]]

^<<v23-37-15,15>>^ And Hez·e·kiʹah began to pray to Jehovah, saying:

[[v23-37-16]]

^<<v23-37-16,16>>^ “O Jehovah of armies, the God of Israel, sitting upon the cherubs, you alone are the &#91;true&#93; God of all the kingdoms of the earth. You yourself have made the heavens and the earth.

[[v23-37-17]]

^<<v23-37-17,17>>^ Incline your ear, O Jehovah, and hear. Open your eyes, O Jehovah, and see, and hear all the words of Sen·nachʹer·ib that he has sent to taunt the living God.^&#42;1^

[NOTE]
====
. See vs 4 ftn, “Living God.”
====

[[v23-37-18]]

^<<v23-37-18,18>>^ It is a fact, O Jehovah, that the kings of As·syrʹi·a have devastated all the lands, and their own land.

[[v23-37-19]]

^<<v23-37-19,19>>^ And there was a consigning of their gods to the fire, because they were no gods,^&#42;1^ but the workmanship of man’s hands, wood and stone, so that they destroyed them.

[NOTE]
====
. Or, “not God.” Heb., loʼ ʼelo·himʹ.
====

[[v23-37-20]]

^<<v23-37-20,20>>^ And now, O Jehovah our God, save us out of his hand, that all the kingdoms of the earth may know that you, O Jehovah, are &#91;God&#93;^&#42;1^ alone.”

[NOTE]
====
. “God,” inserted in agreement with 1QIsa and 2Ki 19:19.
====

[[v23-37-21]]

^<<v23-37-21,21>>^ And Isaiah the son of Aʹmoz proceeded to send to Hez·e·kiʹah, saying: “This is what Jehovah the God of Israel has said, ‘Because you have prayed to me concerning Sen·nachʹer·ib the king of As·syrʹi·a,

[[v23-37-22]]

^<<v23-37-22,22>>^ this is the word that Jehovah has spoken against him:
“The virgin daughter of Zion has despised you, she has held you in derision.
Behind you the daughter of Jerusalem has wagged &#91;her&#93; head.

[[v23-37-23]]

^<<v23-37-23,23>>^ Whom have you taunted and spoken of abusively?
And against whom have you lifted up &#91;your&#93; voice
And do you raise your eyes on high?
It is against the Holy One of Israel!

[[v23-37-24]]

^<<v23-37-24,24>>^ By means of your servants you have taunted Jehovah^&#42;1^ and you say,
‘With the multitude of my war chariots I myself—
I shall certainly ascend the height of mountainous regions,
The remotest parts of Lebʹa·non;
And I shall cut down its lofty cedars, its choice juniper trees.
And I shall enter its final height,^&#42;2^ the forest of its orchard.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. “Height,” M; in 2Ki 19:23, “lodging place.”
====

[[v23-37-25]]

^<<v23-37-25,25>>^ I myself shall certainly dig and drink waters,
And I shall dry up with the soles of my feet all the Nile canals of Egypt.’^&#42;1^

[NOTE]
====
. “Egypt.” Heb., Ma·tsohrʹ, sing. Compare 36:6 ftn.
====

[[v23-37-26]]

^<<v23-37-26,26>>^ Have you not heard? From remote times it is what I will do.
From bygone days I have even formed it. Now I will bring it in.
And you will serve to make fortified cities become desolate as piles of ruins.

[[v23-37-27]]

^<<v23-37-27,27>>^ And their inhabitants will be feeble-handed;
They will simply be terrified and ashamed.
They must become as vegetation of the field and green tender grass,
Grass of the roofs and of the terrace before the east wind.

[[v23-37-28]]

^<<v23-37-28,28>>^ And your sitting quiet^&#42;1^ and your going out and your coming in I well know,
And your exciting yourself against me,

[NOTE]
====
. “Grass of the roofs, which is scorched before the east wind. (28) Your rising up,” 1QIsa.
====

[[v23-37-29]]

^<<v23-37-29,29>>^ Because your exciting yourself against me and your roaring have come up into my ears.
And I shall certainly put my hook in your nose and my bridle between your lips,
And I shall indeed lead you back by the way by which you have come.”

[[v23-37-30]]

^<<v23-37-30,30>>^ “‘And this will be the sign for you: There will be an eating this year of the growth from spilled kernels, and in the second year grain that shoots up of itself; but in the third year sow seed, YOU people, and reap, and plant vineyards and eat their fruitage.

[[v23-37-31]]

^<<v23-37-31,31>>^ And those who escape of the house of Judah, those who are left remaining, will certainly take root downward and produce fruitage upward.

[[v23-37-32]]

^<<v23-37-32,32>>^ For out of Jerusalem a remnant will go forth and those who escape out of Mount Zion. The very zeal of Jehovah of armies will do this.

[[v23-37-33]]

^<<v23-37-33,33>>^ “‘Therefore this is what Jehovah has said concerning the king of As·syrʹi·a: “He will not come into this city, nor will he shoot an arrow there, nor confront it with a shield, nor cast up a siege rampart against it.”’

[[v23-37-34]]

^<<v23-37-34,34>>^ “‘By the way by which he came he will return, and into this city he will not come,’ is the utterance of Jehovah.

[[v23-37-35]]

^<<v23-37-35,35>>^ ‘And I shall certainly defend this city to save it for my own sake and for the sake of David my servant.’”

[[v23-37-36]]

^<<v23-37-36,36>>^ And the angel of Jehovah proceeded to go forth and strike down a hundred and eighty-five thousand in the camp of the As·syrʹi·ans. When people rose up early in the morning, why, there all of them were dead carcasses.

[[v23-37-37]]

^<<v23-37-37,37>>^ Hence Sen·nachʹer·ib the king of As·syrʹi·a pulled away and went and returned and took up dwelling in Ninʹe·veh.

[[v23-37-38]]

^<<v23-37-38,38>>^ And it came about that as he was bowing down at the house of Nisʹroch his god,^&#42;1^ A·dramʹme·lech and Shar·eʹzer, his own sons, struck him down with the sword, and they themselves escaped to the land of Arʹa·rat.^&#42;2^ And Eʹsar-hadʹdon his son began to reign in place of him.

[NOTE]
====
. “His god.” Heb., ʼelo·havʹ, pl. of ʼelohʹah, to denote the excellence of “Nisroch,” the false god.
. “Land of Ararat,” MVg; TSy, “land of Kardo”; LXX, “Armenia.”
====

'''

xref:023-isaiah/023-isaiah-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaiah/023-isaiah-038.adoc#v23-38-0[Próximo Capítulo &#62;]