include::./index.adoc[]

[[v23-44-0]]
=== Isaiah, 44
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-44-1]]

^<<v23-44-1,1>>^ “And now listen, O Jacob my servant, and you, O Israel, whom I have chosen.

[[v23-44-2]]

^<<v23-44-2,2>>^ This is what Jehovah has said, your Maker and your Former, who kept helping you even from the belly,^&#42;1^ ‘Do not be afraid, O my servant Jacob, and you, Jeshʹu·run,^&#42;2^ whom I have chosen.

[NOTE]
====
. That is, the mother’s womb.
. “Jeshurun” (meaning “Upright One,” an honorary title for Israel), M; Vg, “Most upright one”; LXX, “beloved Israel”; TSy, “Israel.”
====

[[v23-44-3]]

^<<v23-44-3,3>>^ For I shall pour out water upon the thirsty one, and trickling streams upon the dry place. I shall pour out my spirit upon your seed,^&#42;1^ and my blessing upon your descendants.

[NOTE]
====
. Or, “offspring.”
====

[[v23-44-4]]

^<<v23-44-4,4>>^ And they will certainly spring up as among the green grass, like poplars by the water ditches.

[[v23-44-5]]

^<<v23-44-5,5>>^ This one will say: “I belong to Jehovah.” And that one will call &#91;himself&#93; by the name of Jacob, and another will write upon his hand: “Belonging to Jehovah.”^&#42;1^ And by the name of Israel one will betitle &#91;himself&#93;.’

[NOTE]
====
. Or, “upon his hand: ‘Jehovah’s.’ ”
====

[[v23-44-6]]

^<<v23-44-6,6>>^ “This is what Jehovah has said, the King of Israel and the Repurchaser of him, Jehovah of armies, ‘I am the first and I am the last, and besides me there is no God.^&#42;1^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

[[v23-44-7]]

^<<v23-44-7,7>>^ And who is there like me? Let him call out,^&#42;1^ that he may tell it and present it to me. From when I appointed the people of long ago, both the things coming and the things that will enter in let them tell on their part.

[NOTE]
====
. “Let him stand up, let him call out,” LXX.
====

[[v23-44-8]]

^<<v23-44-8,8>>^ Do not be in dread, YOU people, and do not become stupefied. Have I not from that time on caused you individually to hear and told &#91;it&#93; out? And YOU are my witnesses. Does there exist a God^&#42;1^ besides me? No, there is no Rock.^&#42;2^ I have recognized none.’”

[NOTE]
====
. “God.” Heb., ʼElohʹah.
. “Rock.” Heb., Tsur; TSy, “Strong one.”
====

[[v23-44-9]]

^<<v23-44-9,9>>^ The formers of the carved image are all of them an unreality, and their darlings^&#42;1^ themselves will be of no benefit; and as their witnesses^&#42;2^ they see nothing and know nothing, in order that they may be ashamed.

[NOTE]
====
. Or, “desired things.”
. “And as their witnesses.” Heb., weʽe·dheh·hemʹ. The next word (hemʹmah, “they [are]”) is marked with extraordinary points by the Sopherim, indicating that it should be canceled because of being merely a dittography of the pronominal ending (hem, “their”) of the word preceding it. The pro­noun for “they” is also absent in Sy. Accordingly the passage should read: “and as their witnesses they [the darlings; the carved images] see nothing and know nothing, in order that they [the formers of the carved image] may be ashamed.” Ignoring the extraordinary points, the passage would read: “and they [Heb., hemʹmah] are their witnesses that see nothing and that know nothing, in order that they may be ashamed.” See App 2A.
====

[[v23-44-10]]

^<<v23-44-10,10>>^ Who has formed a god^&#42;1^ or cast a mere molten image? Of no benefit at all has it been.

[NOTE]
====
. “A god.” Heb., ʼel.
====

[[v23-44-11]]

^<<v23-44-11,11>>^ Look! All his partners themselves will be ashamed, and the craftsmen are from earthling men.^&#42;1^ They will all of them collect themselves together. They will stand still. They will be in dread. They will be ashamed at the same time.

[NOTE]
====
. Or, “from mankind.” Heb., me·ʼa·dhamʹ.
====

[[v23-44-12]]

^<<v23-44-12,12>>^ As for the carver of iron with the billhook, he has been busy &#91;at it&#93; with the coals; and with the hammers he proceeds to form it, and he keeps busy at it with his powerful arm. Also, he has become hungry, and so without power. He has not drunk water; so he gets tired.

[[v23-44-13]]

^<<v23-44-13,13>>^ As for the wood carver, he has stretched out the measuring line; he traces it out with red chalk; he works it up with a wood scraper; and with a compass he keeps tracing it out, and gradually he makes it like the representation of a man,^&#42;1^ like the beauty of mankind,^&#42;2^ to sit in a house.

[NOTE]
====
. “Man.” Heb., ʼish.
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v23-44-14]]

^<<v23-44-14,14>>^ There is one whose business is to cut down cedars; and he takes a certain species of tree, even a massive tree, and he lets it become strong for himself among the trees of the forest. He planted the laurel tree, and the pouring rain itself keeps making it get big.

[[v23-44-15]]

^<<v23-44-15,15>>^ And it has become &#91;something&#93; for man^&#42;1^ to keep a fire burning. So he takes part of it that he may warm himself. In fact he builds a fire and actually bakes bread. He also works on a god^&#42;2^ to which he may bow down. He has made it into a carved image, and he prostrates himself to it.

[NOTE]
====
. Or, “for an earthling man.” Heb., leʼa·dhamʹ.
. Lit., “He also makes a god [Heb., ʼel].”
====

[[v23-44-16]]

^<<v23-44-16,16>>^ Half of it^&#42;1^ he actually burns up in a fire. Upon half of it he roasts well the flesh that he eats, and he becomes satisfied. He also warms himself and says: “Aha! I have warmed myself. I have seen the firelight.”

[NOTE]
====
. “It,” that is, the fuel; possibly tree branches.
====

[[v23-44-17]]

^<<v23-44-17,17>>^ But the remainder of it he actually makes into a god itself, into his carved image. He prostrates himself to it and bows down and prays to it and says: “Deliver me, for you are my god.”

[[v23-44-18]]

^<<v23-44-18,18>>^ They have not come to know, nor do they understand, because their eyes have been besmeared so as not to see, their heart so as to have no insight.

[[v23-44-19]]

^<<v23-44-19,19>>^ And no one recalls to his heart or has knowledge or understanding, saying: “The half of it I have burned up in a fire, and upon its coals I have also baked bread; I roast flesh and eat. But the rest of it shall I make into a mere detestable thing? To the dried-out wood of a tree shall I prostrate myself?”

[[v23-44-20]]

^<<v23-44-20,20>>^ He is feeding on ashes. His own heart that has been trifled with has led him astray. And he does not deliver his soul, nor does he say: “Is there not a falsehood in my right hand?”

[[v23-44-21]]

^<<v23-44-21,21>>^ “Remember these things, O Jacob, and you, O Israel, because you are my servant. I have formed you. You are a servant belonging to me. O Israel, you will not be forgotten on my part.

[[v23-44-22]]

^<<v23-44-22,22>>^ I will wipe out your transgressions just as with a cloud, and your sins just as with a cloud mass. Do return to me, for I will repurchase you.

[[v23-44-23]]

^<<v23-44-23,23>>^ “Joyfully cry out, YOU heavens, for Jehovah has taken action! Shout in triumph, all YOU lowest parts^&#42;1^ of the earth! Become cheerful, YOU mountains, with joyful outcry, you forest and all YOU trees in it! For Jehovah has repurchased Jacob, and on Israel he shows his beauty.”

[NOTE]
====
. “Lowest parts,” M; LXXSy, “foundations”; Vg, “extreme parts.” Compare Ps 63:9 ftn.
====

[[v23-44-24]]

^<<v23-44-24,24>>^ This is what Jehovah has said, your Repurchaser and the Former of you from the belly:^&#42;1^ “I, Jehovah, am doing everything, stretching out the heavens by myself, laying out the earth. Who was with me?

[NOTE]
====
. That is, from the mother’s womb.
====

[[v23-44-25]]

^<<v23-44-25,25>>^ &#91;I am&#93; frustrating the signs of the empty talkers,^&#42;1^ and &#91;I am&#93; the One that makes diviners themselves act crazily; the One turning wise men backwards, and the One that turns even their knowledge into foolishness;

[NOTE]
====
. Lit., “the empty talk,” but personalized.
====

[[v23-44-26]]

^<<v23-44-26,26>>^ the One making the word of his servant come true, and the One that carries out completely the counsel of his own messengers; the One saying of Jerusalem, ‘She will be inhabited,’ and of the cities of Judah, ‘They will be rebuilt, and her desolated places I shall raise up’;

[[v23-44-27]]

^<<v23-44-27,27>>^ the One saying to the watery deep, ‘Be evaporated; and all your rivers I shall dry up’;

[[v23-44-28]]

^<<v23-44-28,28>>^ the One saying of Cyrus,^&#42;1^ ‘He is my shepherd, and all that I delight in he will completely carry out’; even in &#91;my&#93; saying^&#42;2^ of Jerusalem, ‘She will be rebuilt,’^&#42;3^ and of the temple, ‘You will have your foundation laid.’”

[NOTE]
====
. “Of Cyrus,” M(Heb., leKhohʹresh)TLXXVg.
. “Even in [my] saying,” MSy; LXX, “the One saying”; Vg, “I who say.”
. “To Jerusalem: ‘You will be rebuilt,’ ” TLXXVg.
====

'''

xref:023-isaiah/023-isaiah-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaiah/023-isaiah-045.adoc#v23-45-0[Próximo Capítulo &#62;]