include::./index.adoc[]

[[v23-3-0]]
=== Isaiah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-3-1]]

^<<v23-3-1,1>>^ For, look! the &#91;true&#93; Lord,^&#42;1^ Jehovah of armies, is removing from Jerusalem and from Judah support and stay, the whole support of bread and the whole support of water,

[NOTE]
====
. See 1:24 ftn.
====

[[v23-3-2]]

^<<v23-3-2,2>>^ mighty man and warrior,^&#42;1^ judge and prophet, and practicer of divination and elderly man,

[NOTE]
====
. Lit., “and man of war.” Heb., weʼishʹ mil·cha·mahʹ.
====

[[v23-3-3]]

^<<v23-3-3,3>>^ chief of fifty and highly respected man^&#42;1^ and counselor and expert in magical arts, and the skilled charmer.^&#42;2^

[NOTE]
====
. Lit., “one lifted up as to face.”
. Or, “one skilled at serpent-charming.” See App 7A.
====

[[v23-3-4]]

^<<v23-3-4,4>>^ And I shall certainly make boys their princes, and mere arbitrary power^&#42;1^ will rule over them.

[NOTE]
====
. “Arbitrary power.” Or, “caprices.”
====

[[v23-3-5]]

^<<v23-3-5,5>>^ And the people will actually tyrannize one over the other, even each one over his fellowman. They will storm, the boy against the old man, and the lightly esteemed one against the one to be honored.

[[v23-3-6]]

^<<v23-3-6,6>>^ For each one will lay hold of his brother in the house of his father, &#91;saying:&#93; “You have a mantle. A dictator you ought to become to us, and this overthrown mass should be under your hand.”

[[v23-3-7]]

^<<v23-3-7,7>>^ He will raise &#91;his voice&#93; in that day, saying: “I shall not become a wound dresser; and in my house there is neither bread nor a mantle. YOU men must not set me as dictator over the people.”

[[v23-3-8]]

^<<v23-3-8,8>>^ For Jerusalem has stumbled, and Judah itself has fallen, because their tongue and their dealings are against Jehovah, in behaving rebelliously in the eyes of his glory.

[[v23-3-9]]

^<<v23-3-9,9>>^ The very expression of their faces^&#42;1^ actually testifies against them, and of their sin like that of Sodʹom they do tell. They have not hidden &#91;it&#93;. Woe to their soul! For they have dealt out to themselves calamity.

[NOTE]
====
. Or, “Just a look at their faces”; or, “Just their showing regard for faces.”
====

[[v23-3-10]]

^<<v23-3-10,10>>^ Say, YOU men, that it &#91;will be&#93; well with the righteous one, for they will eat the very fruitage of their dealings.

[[v23-3-11]]

^<<v23-3-11,11>>^ Woe to the wicked one!—Calamity; for the treatment &#91;rendered&#93; by his own hands will be rendered to him!

[[v23-3-12]]

^<<v23-3-12,12>>^ As for my people, its task assigners^&#42;1^ are dealing severely,^&#42;2^ and mere women actually rule over it. O my people, those leading you on are causing &#91;you&#93; to wander, and the way of your paths they have confused.

[NOTE]
====
. Or, “its government.”
. “Children are their task assigners,” by a correction of M.
====

[[v23-3-13]]

^<<v23-3-13,13>>^ Jehovah is stationing himself to contend and is standing up to pass sentence upon peoples.

[[v23-3-14]]

^<<v23-3-14,14>>^ Jehovah himself will enter into judgment with the elderly ones of his people and its princes.
“And YOU yourselves have burned down the vineyard. What was taken by robbery from the afflicted one is in YOUR houses.

[[v23-3-15]]

^<<v23-3-15,15>>^ What do YOU men mean in that YOU crush my people, and that YOU grind the very faces of the afflicted ones?” is the utterance of the Sovereign Lord, Jehovah of armies.

[[v23-3-16]]

^<<v23-3-16,16>>^ And Jehovah says: “For the reason that the daughters of Zion have become haughty and they walk with their throats stretched forth and ogling with their eyes, they go walking with tripping steps, and with their feet they make a tinkling sound,^&#42;1^

[NOTE]
====
. Or, “on their feet they shake bangles.”
====

[[v23-3-17]]

^<<v23-3-17,17>>^ Jehovah^&#42;1^ also will actually make the crown of the head of the daughters of Zion scabby, and Jehovah himself will lay their very forehead bare.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v23-3-18]]

^<<v23-3-18,18>>^ In that day Jehovah^&#42;1^ will take away the beauty of the bangles^&#42;2^ and the headbands^&#42;3^ and the moon-shaped ornaments,^&#42;4^

[NOTE]
====
. See vs 17 ftn.
. Or, “anklets.”
. Lit., “little suns.”
. Or, “little moons.”
====

[[v23-3-19]]

^<<v23-3-19,19>>^ the eardrops and the bracelets and the veils,

[[v23-3-20]]

^<<v23-3-20,20>>^ the headdresses and the step chains and the breastbands^&#42;1^ and the ‘houses of the soul’^&#42;2^ and the ornamental humming shells,^&#42;3^

[NOTE]
====
. Or, “the sashes.”
. Probably perfume receptacles.
. Or, “the charms.”
====

[[v23-3-21]]

^<<v23-3-21,21>>^ the finger rings and the nose rings,

[[v23-3-22]]

^<<v23-3-22,22>>^ the robes of state and the overtunics and the cloaks and the purses,

[[v23-3-23]]

^<<v23-3-23,23>>^ and the hand mirrors and the undergarments and the turbans and the large veils.

[[v23-3-24]]

^<<v23-3-24,24>>^ “And it must occur that instead of balsam oil there will come to be merely a musty smell; and instead of a belt, a rope; and instead of an artistic hair arrangement, baldness; and instead of a rich garment, a girding of sackcloth; a brand mark instead of prettiness.

[[v23-3-25]]

^<<v23-3-25,25>>^ By the sword your^&#42;1^ own men will fall, and your mightiness^&#42;2^ by war.

[NOTE]
====
. “Your,” fem. sing., referring to Zion, or Jerusalem.
. “Mighty (strong) ones,” LXXSyVg.
====

[[v23-3-26]]

^<<v23-3-26,26>>^ And her entrances will have to mourn and express sorrow, and she will certainly be cleaned out. She will sit down on the very earth.”

'''

xref:023-isaiah/023-isaiah-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaiah/023-isaiah-004.adoc#v23-4-0[Próximo Capítulo &#62;]