include::./index.adoc[]

[[v23-19-0]]
=== Isaiah, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-19-1]]

^<<v23-19-1,1>>^ The pronouncement against Egypt: Look! Jehovah is riding on a swift cloud and coming into Egypt. And the valueless gods of Egypt will certainly quiver because of him, and the very heart of Egypt will melt in the midst of it.

[[v23-19-2]]

^<<v23-19-2,2>>^ “And I will goad Egyptians against Egyptians, and they will certainly war each one against his brother, and each one against his companion, city against city, kingdom against kingdom.

[[v23-19-3]]

^<<v23-19-3,3>>^ And the spirit of Egypt must become bewildered in the midst of it, and I shall confuse its own counsel. And they will be certain to resort to the valueless gods and to the charmers and to the spirit mediums^&#42;1^ and to the professional foretellers of events.

[NOTE]
====
. “Spirit mediums.” Agents used as a vessel of a demon of divination. Lat., py·thoʹnes. See Ac 16:16.
====

[[v23-19-4]]

^<<v23-19-4,4>>^ And I will deliver up Egypt into the hand of a hard master,^&#42;1^ and strong will be the king that will rule over them,” is the utterance of the &#91;true&#93; Lord,^&#42;2^ Jehovah of armies.

[NOTE]
====
. “Master.” Heb., ʼadho·nimʹ, pl. of ʼa·dhohnʹ, to denote majesty, modified by the sing. adjective “hard.”
. See App 1H.
====

[[v23-19-5]]

^<<v23-19-5,5>>^ And the water will certainly be dried up from the sea, and the river itself will become parched and actually run dry.

[[v23-19-6]]

^<<v23-19-6,6>>^ And the rivers must stink; the Nile canals of Egypt^&#42;1^ must become low and parched. The reed and the rush themselves must molder.^&#42;2^

[NOTE]
====
. “Egypt.” Heb., Ma·tsohrʹ.
. Or, “must be taken by lice.”
====

[[v23-19-7]]

^<<v23-19-7,7>>^ The bare places^&#42;1^ by the Nile River, at the mouth of the Nile River, and every seedland of the Nile River will dry up. It will certainly be driven away, and it will be no more.

[NOTE]
====
. Or, “The rushes.”
====

[[v23-19-8]]

^<<v23-19-8,8>>^ And the fishers will have to mourn, and all those casting fishhooks into the Nile River must express sorrow, and even those spreading fishing nets upon the surface of the water will actually fade away.

[[v23-19-9]]

^<<v23-19-9,9>>^ And the workers in carded flax must become ashamed; also the loom workers on white fabrics.

[[v23-19-10]]

^<<v23-19-10,10>>^ And her weavers must become crushed, all the wage workers grieved in soul.

[[v23-19-11]]

^<<v23-19-11,11>>^ The princes of Zoʹan are indeed foolish. As regards the wise ones of Pharʹaoh’s counselors, &#91;their&#93; counsel is something unreasonable. How will YOU men say to Pharʹaoh: “I am the son of wise ones, the son of kings of ancient time”?

[[v23-19-12]]

^<<v23-19-12,12>>^ Where, then, are they—the wise men of yours—that they may now tell you and that they may know what Jehovah of armies has counseled concerning Egypt?^&#42;1^

[NOTE]
====
. “Egypt.” Heb., Mits·raʹyim.
====

[[v23-19-13]]

^<<v23-19-13,13>>^ The princes of Zoʹan have acted foolishly, the princes of Noph^&#42;1^ have been deceived, the keymen of her tribes have caused Egypt to wander about.

[NOTE]
====
. Or, “Memphis.”
====

[[v23-19-14]]

^<<v23-19-14,14>>^ Jehovah himself has mingled in the midst of her^&#42;1^ the spirit of disconcertedness; and they have caused Egypt to wander about in all its work, just as someone drunk is made to wander about in his vomit.

[NOTE]
====
. “Her,” evidently referring to the land, fem.; LXX, “them.”
====

[[v23-19-15]]

^<<v23-19-15,15>>^ And Egypt will not come to have any work that the head or the tail, the shoot or the rush, can do.

[[v23-19-16]]

^<<v23-19-16,16>>^ In that day Egypt will become like women, and it will certainly tremble and be in dread because of the waving of the hand of Jehovah of armies which he is waving against it.

[[v23-19-17]]

^<<v23-19-17,17>>^ And the ground of Judah must become to Egypt a cause for reeling. Everybody to whom one mentions it^&#42;1^ is in dread because of the counsel of Jehovah of armies that he is counseling against him.

[NOTE]
====
. “It,” fem., referring to the “ground,” fem.
====

[[v23-19-18]]

^<<v23-19-18,18>>^ In that day there will prove to be five cities in the land of Egypt speaking the language of Caʹnaan and swearing to Jehovah of armies. The City of Tearing Down^&#42;1^ will one &#91;city&#93; be called.

[NOTE]
====
. “Tearing Down.” M(Heb.), ha·Heʹres; 1QIsa(Heb.), ha·Cheʹres, “the Sun”; Syr., He·res; Lat., Soʹlis, “(of) the Sun”; Gr., A·se·dekʹ, a transliteration of the Heb. word hats·tseʹdheq, “the righteousness.” (See Gins.Int, pp. 406, 407.) T paraphrases to read: “(City of) the House of the Sun, which is to be destroyed.”
====

[[v23-19-19]]

^<<v23-19-19,19>>^ In that day there will prove to be an altar to Jehovah in the midst of the land of Egypt, and a pillar to Jehovah beside its boundary.

[[v23-19-20]]

^<<v23-19-20,20>>^ And it must prove to be for a sign and for a witness to Jehovah of armies in the land of Egypt; for they will cry out to Jehovah because of the oppressors, and he will send them a savior, even a grand one, who will^&#42;1^ actually deliver them.

[NOTE]
====
. Or, “and will”; or, “and he will.”
====

[[v23-19-21]]

^<<v23-19-21,21>>^ And Jehovah will certainly become known to the Egyptians; and the Egyptians must know Jehovah in that day, and they must render sacrifice and gift and must make a vow to Jehovah and pay it.

[[v23-19-22]]

^<<v23-19-22,22>>^ And Jehovah will certainly deal Egypt a blow. There will be a dealing of a blow and a healing;^&#42;1^ and they must return to Jehovah, and he must let himself be entreated by them and must heal them.

[NOTE]
====
. Or, “deal Egypt a blow, dealing [it] a blow and healing [it].” In Heb. the latter two verbs are in the infinitive absolute, indefinite as to time and impersonal.
====

[[v23-19-23]]

^<<v23-19-23,23>>^ In that day there will come to be a highway out of Egypt to As·syrʹi·a, and As·syrʹi·a will actually come into Egypt, and Egypt into As·syrʹi·a; and they will certainly render service, Egypt with As·syrʹi·a.

[[v23-19-24]]

^<<v23-19-24,24>>^ In that day Israel will come to be the third with Egypt and with As·syrʹi·a, namely, a blessing in the midst of the earth,^&#42;1^

[NOTE]
====
. Or, “the land.” Heb., ha·ʼaʹrets.
====

[[v23-19-25]]

^<<v23-19-25,25>>^ because Jehovah of armies will have blessed it, saying: “Blessed be my people, Egypt, and the work of my hands, As·syrʹi·a, and my inheritance, Israel.”

'''

xref:023-isaiah/023-isaiah-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaiah/023-isaiah-020.adoc#v23-20-0[Próximo Capítulo &#62;]