include::./index.adoc[]

[[v23-5-0]]
=== Isaiah, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v23-5-1]]

^<<v23-5-1,1>>^ Let me sing, please, to my beloved one a song of my loved one concerning his vineyard. There was a vineyard that my beloved one came to have on a fruitful hillside.^&#42;1^

[NOTE]
====
. Lit., “a horn the son of oil.”
====

[[v23-5-2]]

^<<v23-5-2,2>>^ And he proceeded to dig it up and to rid it of stones and to plant it with a choice red vine, and to build a tower in the middle of it. And there was also a winepress that he hewed out in it. And he kept hoping for it to produce grapes, but it gradually produced wild grapes.^&#42;1^

[NOTE]
====
. Or, “stinking things”; or, “putrid (rotten) berries.”
====

[[v23-5-3]]

^<<v23-5-3,3>>^ “And now, O YOU inhabitants^&#42;1^ of Jerusalem and YOU men^&#42;2^ of Judah, please judge between me and my vineyard.

[NOTE]
====
. Lit., “O inhabitant,” sing. but in a collective sense.
. “And . . . men of.” Heb., weʼishʹ, sing. but in a collective sense.
====

[[v23-5-4]]

^<<v23-5-4,4>>^ What is there yet to do for my vineyard that I have not already done in it? Why is it that I hoped for it to produce grapes, but it gradually produced wild grapes?

[[v23-5-5]]

^<<v23-5-5,5>>^ And now, please, may I make known to YOU men what I am doing to my vineyard: There will be a removing of its hedge, and it must be destined for burning down. There must be a breaking down of its stone wall, and it must be destined for a place of trampling.

[[v23-5-6]]

^<<v23-5-6,6>>^ And I shall set it as a thing destroyed. It will not be pruned, nor will it be hoed. And it must come up with the thornbush and weeds; and upon the clouds I shall lay a command to keep from precipitating any rain upon it.

[[v23-5-7]]

^<<v23-5-7,7>>^ For the vineyard of Jehovah of armies is the house of Israel, and the men of Judah are the plantation of which he was fond. And he kept hoping for judgment, but, look! the breaking of law;^&#42;1^ for righteousness, but, look! an outcry.”

[NOTE]
====
. Or, “look! deviation”; or, “look! outpouring [of blood].”
====

[[v23-5-8]]

^<<v23-5-8,8>>^ Woe to the ones joining house to house, &#91;and&#93; those who annex field to field until there is no more room and YOU men have been made to dwell all by yourselves in the midst of the land!

[[v23-5-9]]

^<<v23-5-9,9>>^ In my ears Jehovah of armies &#91;has sworn that&#93; many houses, though great and good, will become an outright object of astonishment, without an inhabitant.

[[v23-5-10]]

^<<v23-5-10,10>>^ For even ten acres of vineyard will produce but one bath^&#42;1^ measure, and even a hoʹmer^&#42;2^ measure of seed will produce but an eʹphah^&#42;3^ measure.

[NOTE]
====
. About 22 L (5.81 gal). See App 8A.
. About 220 L (200 dry qt).
. About 22 L (20 dry qt).
====

[[v23-5-11]]

^<<v23-5-11,11>>^ Woe to those who are getting up early in the morning that they may seek just intoxicating liquor, who are lingering till late in the evening darkness so that wine itself inflames them!

[[v23-5-12]]

^<<v23-5-12,12>>^ And there must prove to be harp and stringed instrument, tambourine and flute, and wine at their feasts; but the activity of Jehovah they do not look at, and the work of his hands they have not seen.

[[v23-5-13]]

^<<v23-5-13,13>>^ Therefore my people will have to go into exile for lack of knowledge; and their glory will be famished men,^&#42;1^ and their crowd will be parched with thirst.

[NOTE]
====
. “Those dead from hunger,” TSy and two Heb. mss.
====

[[v23-5-14]]

^<<v23-5-14,14>>^ Therefore Sheʹol^&#42;1^ has made its soul^&#42;2^ spacious and has opened its mouth wide beyond bounds; and what is splendid in her,^&#42;3^ also her crowd and her uproar and the exultant one, will certainly go down into it.

[NOTE]
====
. “Sheol,” M(Heb., sheʼohlʹ)T; Gr., haiʹdes; Syr., shiul; Lat., in·ferʹnus. See App 4B.
. “Its soul.” Heb., naph·shahʹ; Gr., psy·khenʹ; Lat., aʹni·mam. See App 4A.
. “Her,” fem. sing., referring to Jerusalem. See vs 3.
====

[[v23-5-15]]

^<<v23-5-15,15>>^ And earthling man will bow down, and man will become low, and even the eyes of the high ones will become low.

[[v23-5-16]]

^<<v23-5-16,16>>^ And Jehovah of armies will become high through judgment, and the &#91;true&#93; God,^&#42;1^ the Holy One, will certainly sanctify himself through righteousness.

[NOTE]
====
. “And the [true] God.” Heb., weha·ʼElʹ. See App 1G.
====

[[v23-5-17]]

^<<v23-5-17,17>>^ And the male lambs will actually graze as in their pasture; and the desolate places of well-fed animals alien residents^&#42;1^ will eat.

[NOTE]
====
. Or, “temporary residents.”
====

[[v23-5-18]]

^<<v23-5-18,18>>^ Woe to those drawing error with ropes of untruth, and as with wagon cords sin;

[[v23-5-19]]

^<<v23-5-19,19>>^ those who are saying: “Let his work hasten; do let it come quickly,^&#42;1^ in order that we may see &#91;it&#93;; and let the counsel of the Holy One of Israel draw near and come, that we may know &#91;it&#93;!”

[NOTE]
====
. “Saying: ‘Quickly let Jehovah hasten his works,’ ” Sy.
====

[[v23-5-20]]

^<<v23-5-20,20>>^ Woe to those who are saying that good is bad and bad is good, those who are putting darkness for light and light for darkness, those who are putting bitter for sweet and sweet for bitter!

[[v23-5-21]]

^<<v23-5-21,21>>^ Woe to those wise in their own eyes and discreet even in front of their own faces!

[[v23-5-22]]

^<<v23-5-22,22>>^ Woe to those who are mighty in drinking wine, and to the men with vital energy for mixing intoxicating liquor,

[[v23-5-23]]

^<<v23-5-23,23>>^ those who are pronouncing the wicked one righteous in consideration of a bribe, and who take away even the righteousness^&#42;1^ of the righteous one^&#42;2^ from him!

[NOTE]
====
. Or, “innocence.”
. “The righteous one,” LXXVg and a few Heb. mss; 1QIsaMSy, “the righteous ones.”
====

[[v23-5-24]]

^<<v23-5-24,24>>^ Therefore just as a tongue of fire eats up the stubble and into the flames mere dried grass sinks down, their very rootstock will become just like a musty smell, and their blossom itself will go up just like powder, because they have rejected the law of Jehovah of armies, and the saying of the Holy One of Israel they have disrespected.

[[v23-5-25]]

^<<v23-5-25,25>>^ That is why the anger of Jehovah has grown hot against his people, and he will stretch out his hand against them and strike them. And the mountains will be agitated, and their dead bodies will become like the offal in the midst of the streets.
In view of all this his anger has not turned back, but his hand is stretched out still.

[[v23-5-26]]

^<<v23-5-26,26>>^ And he has raised up a signal to a great nation^&#42;1^ far away, and he has whistled to it at the extremity of the earth; and, look! in haste it will swiftly come in.

[NOTE]
====
. “To a great nation.” Heb., lag·goh·yimʹ, pl. to denote greatness, but with a sing. pronoun (“it”) and with a sing. verb, thus, “it will . . . come in.” See vs 27 ftn.
====

[[v23-5-27]]

^<<v23-5-27,27>>^ There is no one tired nor is anyone stumbling among them.^&#42;1^ No one is drowsy and no one sleeps. And the belt around their loins will certainly not be opened, nor the laces of their sandals be torn in two;

[NOTE]
====
. Lit., “it,” that is, the “nation,” sing. but in a collective sense.
====

[[v23-5-28]]

^<<v23-5-28,28>>^ because their arrows are sharpened and all their bows are bent. The very hoofs of their horses will have to be accounted as flint itself, and their wheels as a storm wind.

[[v23-5-29]]

^<<v23-5-29,29>>^ The roaring of theirs is like that of a lion, and they roar like maned young lions. And they will growl and grab hold of the prey and bring &#91;it&#93; safely away, and there will be no deliverer.

[[v23-5-30]]

^<<v23-5-30,30>>^ And they will growl over it in that day as with the growling of the sea. And one will actually gaze at the land, and, look! there is distressing darkness; and even the light has grown dark because of the drops falling on it.

'''

xref:023-isaiah/023-isaiah-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaiah/023-isaiah-006.adoc#v23-6-0[Próximo Capítulo &#62;]