site:
  title: Bíblia Sagrada
  start_page: bibles::index.adoc
content:
  edit_url: '{web_url}/edit/{refname}/{path}'
  sources:
    - url: .
      branches: [HEAD]
      start_paths: ./docs/components/*
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  # https://gitlab.com/antora/antora-ui-default/tree/master/src/partials
  supplemental_files: ./.next/antora
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
      languages: [pt, en]
asciidoc:
  attributes:
    figure-caption: Figura
    table-caption: Tabela
    example-caption: Exemplo
    listing-caption: Código
    appendix-caption: Apêndice
    toc-title: Sumário
    bibliography-title: Bibliografia
    index-title: Índice
    caution-caption: Atenção
    warning-caption: Aviso
    note-caption: Nota
    tip-caption: Dica
    important-caption: Importante
    abstract-title: Resumo
    part-caption: Parte
