include::./index.adoc[]

[[v11-21-0]]
=== The First of Kings, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-21-1]]

^<<v11-21-1,1>>^ And it came about after these things that there was a vineyard that happened to belong to Naʹboth the Jezʹre·el·ite, which was in Jezʹre·el, beside the palace of Aʹhab the king of Sa·marʹi·a.

[[v11-21-2]]

^<<v11-21-2,2>>^ So Aʹhab spoke to Naʹboth, saying: “Do give me your vineyard, that it may serve as a garden of vegetables to me, for it is close by my house; and let me give you in place of it a vineyard better than it. &#91;Or&#93; if it is good in your eyes, I will give you money as the price of this.”

[[v11-21-3]]

^<<v11-21-3,3>>^ But Naʹboth said to Aʹhab: “It is unthinkable on my part, from Jehovah’s standpoint, for me to give the hereditary possession of my forefathers to you.”

[[v11-21-4]]

^<<v11-21-4,4>>^ Consequently Aʹhab came into his house, sullen and dejected over the word that Naʹboth the Jezʹre·el·ite had spoken to him, when he said: “I shall not give you the hereditary possession of my forefathers.” Then he lay down upon his couch and kept his face turned, and he did not eat bread.

[[v11-21-5]]

^<<v11-21-5,5>>^ Finally Jezʹe·bel his wife came in to him and spoke to him: “Why is it that your spirit is sad and you are not eating bread?”

[[v11-21-6]]

^<<v11-21-6,6>>^ At that he spoke to her: “Because I proceeded to speak to Naʹboth the Jezʹre·el·ite and say to him, ‘Do give me your vineyard for money. Or, if you prefer, let me give you another vineyard in place of it.’ But he said, ‘I shall not give you my vineyard.’”

[[v11-21-7]]

^<<v11-21-7,7>>^ Then Jezʹe·bel his wife said to him: “Is it you that now exercise the kingship over Israel? Rise up, eat bread and let your heart be merry. I myself shall give you the vineyard of Naʹboth the Jezʹre·el·ite.”

[[v11-21-8]]

^<<v11-21-8,8>>^ Accordingly she wrote letters in Aʹhab’s name and sealed them with his seal, and sent the letters to the older men and the nobles that were in his city dwelling with Naʹboth.

[[v11-21-9]]

^<<v11-21-9,9>>^ But she wrote in the letters, saying: “Proclaim a fast, and HAVE Naʹboth sit at the head of the people.

[[v11-21-10]]

^<<v11-21-10,10>>^ And MAKE two men, good-for-nothing fellows,^&#42;1^ sit in front of him, and let them bear witness against him, saying, ‘You have cursed^&#42;2^ God and the king!’ And BRING him out and stone him that he may die.”

[NOTE]
====
. “Good-for-nothing fellows.” Lit., “sons of belial (worthlessness).” Heb., beneh-veli·yaʹʽal.
. “Cursed” was the original reading. The text was emended to read “blessed.” See App 2B.
====

[[v11-21-11]]

^<<v11-21-11,11>>^ So the men of his city, the older men and the nobles that were dwelling in his city, did just as Jezʹe·bel had sent to them, just as it was written in the letters that she had sent to them.

[[v11-21-12]]

^<<v11-21-12,12>>^ They proclaimed a fast and had Naʹboth sit at the head of the people.

[[v11-21-13]]

^<<v11-21-13,13>>^ Then two of the men, good-for-nothing fellows, came in and sat down in front of him; and the good-for-nothing men began to bear witness against him, that is, Naʹboth, in front of the people, saying: “Naʹboth has cursed^&#42;1^ God and the king!” After that they brought him out to the outskirts of the city and stoned him with stones, so that he died.

[NOTE]
====
. See vs 10 ftn, “Cursed.”
====

[[v11-21-14]]

^<<v11-21-14,14>>^ They now sent to Jezʹe·bel, saying: “Naʹboth has been stoned so that he is dead.”

[[v11-21-15]]

^<<v11-21-15,15>>^ And it came about that, as soon as Jezʹe·bel heard that Naʹboth had been stoned so that he died, Jezʹe·bel immediately said to Aʹhab: “Rise up, take possession of the vineyard of Naʹboth the Jezʹre·el·ite, which he refused to give you for money; for Naʹboth is no longer alive, but dead.”

[[v11-21-16]]

^<<v11-21-16,16>>^ And it came about that, as soon as Aʹhab heard that Naʹboth was dead, Aʹhab at once rose up to go down to the vineyard of Naʹboth the Jezʹre·el·ite, to take possession of it.

[[v11-21-17]]

^<<v11-21-17,17>>^ And Jehovah’s word came to E·liʹjah the Tishʹbite, saying:

[[v11-21-18]]

^<<v11-21-18,18>>^ “Rise up, go down to meet Aʹhab the king of Israel, who is in Sa·marʹi·a. There he is in the vineyard of Naʹboth, where he has gone down to take possession of it.

[[v11-21-19]]

^<<v11-21-19,19>>^ And you must speak to him, saying, ‘This is what Jehovah has said: “Have you murdered and also taken possession?”’ And you must speak to him, saying, ‘This is what Jehovah has said: “In the place where the dogs licked up the blood of Naʹboth, the dogs will lick up your blood, even yours.”’”

[[v11-21-20]]

^<<v11-21-20,20>>^ And Aʹhab proceeded to say to E·liʹjah: “Have you found me, O enemy of mine?” to which he said: “I have found you. ‘For the reason that you have sold yourself to do what is bad in the eyes of Jehovah,

[[v11-21-21]]

^<<v11-21-21,21>>^ here I am bringing calamity upon you; and I shall certainly make a clean sweep after you and cut off from Aʹhab anyone urinating against a wall^&#42;1^ and the helpless and worthless one^&#42;2^ in Israel.

[NOTE]
====
. “Urinating against a wall.” A Heb. idiom for males.
. Lit., “and one restrained and one let go (abandoned).” See De 32:36 ftn, “One.”
====

[[v11-21-22]]

^<<v11-21-22,22>>^ And I shall certainly constitute your house like the house of Jer·o·boʹam the son of Neʹbat and like the house of Baʹa·sha the son of A·hiʹjah, for the offense with which you have offended and then caused Israel to sin.’

[[v11-21-23]]

^<<v11-21-23,23>>^ And also as regards Jezʹe·bel Jehovah has spoken, saying, ‘The very dogs will eat up Jezʹe·bel in the plot of land of Jezʹre·el.

[[v11-21-24]]

^<<v11-21-24,24>>^ Anyone of Aʹhab’s that is dying in the city the dogs will eat up; and anyone dying in the field the fowls of the heavens will eat up.

[[v11-21-25]]

^<<v11-21-25,25>>^ Without exception no one has proved to be like Aʹhab, who sold himself to do what was bad in the eyes of Jehovah, whom Jezʹe·bel his wife egged on.

[[v11-21-26]]

^<<v11-21-26,26>>^ And he went acting very detestably by going after the dungy idols, the same as all that the Amʹor·ites had done, whom Jehovah drove out from before the sons of Israel.’”

[[v11-21-27]]

^<<v11-21-27,27>>^ And it came about that as soon as Aʹhab heard these words, he proceeded to rip his garments apart and to put sackcloth upon his flesh; and he went on a fast and kept lying down in sackcloth and walking despondently.

[[v11-21-28]]

^<<v11-21-28,28>>^ And Jehovah’s word came to E·liʹjah the Tishʹbite, saying:

[[v11-21-29]]

^<<v11-21-29,29>>^ “Have you seen how Aʹhab has humbled himself on my account? For the reason that he has humbled himself because of me, I shall not bring the calamity in his own days. In the days of his son I shall bring the calamity upon his house.”

'''

xref:011-1-kings/011-1-kings-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-kings/011-1-kings-022.adoc#v11-22-0[Próximo Capítulo &#62;]