include::./index.adoc[]

[[v11-17-0]]
=== The First of Kings, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-17-1]]

^<<v11-17-1,1>>^ And E·liʹjah^&#42;1^ the Tishʹbite from the inhabitants^&#42;2^ of Gilʹe·ad proceeded to say to Aʹhab: “As Jehovah the God of Israel before whom I do stand^&#42;3^ is living, there will occur during these years neither dew nor rain, except at the order of my word!”

[NOTE]
====
. Meaning “My God Is Jehovah.” Heb., ʼE·li·yaʹhu; LXXVg, “Elias.”
. “From the inhabitants,” MSyVg; LXX and by a slight correction of M, “from Tishbeh.”
. Or, “upon whom I do attend.”
====

[[v11-17-2]]

^<<v11-17-2,2>>^ The word of Jehovah now came to him, saying:

[[v11-17-3]]

^<<v11-17-3,3>>^ “Go away from here, and you must turn your way eastward and conceal yourself at the torrent valley of Cheʹrith that is east of the Jordan.

[[v11-17-4]]

^<<v11-17-4,4>>^ And it must occur that from the torrent valley you should drink, and the ravens I shall certainly command to supply you food there.”

[[v11-17-5]]

^<<v11-17-5,5>>^ Immediately he went and did according to the word of Jehovah, and so went and took up dwelling by the torrent valley of Cheʹrith that is east of^&#42;1^ the Jordan.

[NOTE]
====
. Lit., “in front of.”
====

[[v11-17-6]]

^<<v11-17-6,6>>^ And the ravens themselves were bringing him bread and meat in the morning and bread and meat in the evening, and from the torrent valley he kept drinking.

[[v11-17-7]]

^<<v11-17-7,7>>^ But it came about at the end of some days that the torrent valley became dry, because there had occurred no downpour upon the earth.

[[v11-17-8]]

^<<v11-17-8,8>>^ The word of Jehovah now came to him, saying:

[[v11-17-9]]

^<<v11-17-9,9>>^ “Rise up, go to Zarʹe·phath, which belongs to Siʹdon, and you must dwell there. Look! I shall certainly command there a woman, a widow, to supply you food.”

[[v11-17-10]]

^<<v11-17-10,10>>^ Accordingly he rose up and went to Zarʹe·phath and came into the entrance of the city; and, look! a woman, a widow, was there gathering up pieces of wood. So he called to her and said: “Please, get me a sip of water in a vessel that I may drink.”

[[v11-17-11]]

^<<v11-17-11,11>>^ When she began to go and get it, he went on to call to her and say: “Please, get me a bit of bread in your hand.”

[[v11-17-12]]

^<<v11-17-12,12>>^ At this she said: “As Jehovah your God is living, I have no round cake,^&#42;1^ but a handful of flour in the large jar and a little oil in the small jar; and here I am gathering up a few^&#42;2^ pieces of wood, and I must go in and make something for myself and my son, and we shall have to eat it and die.”

[NOTE]
====
. Or, “I have no pantry to turn to.”
. Lit., “two.”
====

[[v11-17-13]]

^<<v11-17-13,13>>^ Then E·liʹjah said to her: “Do not be afraid. Go in, do according to your word. Only from what is there make me a small round cake first, and you must bring it out to me, and for yourself and your son you can make something afterward.

[[v11-17-14]]

^<<v11-17-14,14>>^ For this is what Jehovah the God of Israel has said, ‘The large jar of flour itself will not get exhausted, and the small jar of oil itself will not fail until the day of Jehovah’s giving a downpour upon the surface of the ground.’”

[[v11-17-15]]

^<<v11-17-15,15>>^ So she went and did according to E·liʹjah’s word; and she continued to eat, she together with him and her household, for days.

[[v11-17-16]]

^<<v11-17-16,16>>^ The large jar of flour itself did not get exhausted, and the small jar of oil itself did not fail, according to Jehovah’s word that he had spoken by means of E·liʹjah.

[[v11-17-17]]

^<<v11-17-17,17>>^ And it came about after these things that the son of the woman, the mistress of the house, fell sick, and his sickness came to be so severe that there was no breath left in him.

[[v11-17-18]]

^<<v11-17-18,18>>^ At this she said to E·liʹjah: “What do I have to do with you,^&#42;1^ O man of the &#91;true&#93; God? You have come to me to bring my error to mind and to put my son to death.”

[NOTE]
====
. Lit., “What [is there] to me and to you?” A Heb. idiom; a repellent question. See App 7B.
====

[[v11-17-19]]

^<<v11-17-19,19>>^ But he said to her:^&#42;1^ “Give me your son.” Then he took him from her bosom and carried him up to the roof chamber, where he was dwelling, and laid him upon his own couch.

[NOTE]
====
. “But Elijah said to the woman,” LXX.
====

[[v11-17-20]]

^<<v11-17-20,20>>^ And he began calling to Jehovah and saying: “O Jehovah my God, is it also upon the widow with whom I am residing as an alien that you must bring injury by putting her son to death?”

[[v11-17-21]]

^<<v11-17-21,21>>^ And he proceeded to stretch himself upon the child three times and call to Jehovah and say: “O Jehovah my God, please, cause the soul of this child to come back within him.”

[[v11-17-22]]

^<<v11-17-22,22>>^ Finally Jehovah listened to E·liʹjah’s voice, so that the soul of the child came back within him and he came to life.

[[v11-17-23]]

^<<v11-17-23,23>>^ E·liʹjah now took the child and brought him down from the roof chamber into the house and gave him to his mother; and E·liʹjah then said: “See, your son is alive.”

[[v11-17-24]]

^<<v11-17-24,24>>^ Upon that the woman said to E·liʹjah: “Now, indeed, I do know that you are a man of God and that Jehovah’s word in your mouth is true.”^&#42;1^

[NOTE]
====
. Lit., “truth.” Heb., ʼemethʹ.
====

'''

xref:011-1-kings/011-1-kings-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-1-kings/011-1-kings-018.adoc#v11-18-0[Próximo Capítulo &#62;]