include::./index.adoc[]

[[v11-19-0]]
=== The First of Kings, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-19-1]]

^<<v11-19-1,1>>^ Then Aʹhab told Jezʹe·bel all that E·liʹjah had done and all about how he had killed all the prophets with the sword.

[[v11-19-2]]

^<<v11-19-2,2>>^ At that Jezʹe·bel sent a messenger to E·liʹjah, saying: “So may the gods^&#42;1^ do, and so may they add to it, if at this time tomorrow I shall not make your soul like the soul of each one of them!”

[NOTE]
====
. “The gods.” Heb., ʼelo·himʹ, accompanied by the pl. verb “do”; Gr., ho the·osʹ, “the god”; Lat., diʹi, “gods.”
====

[[v11-19-3]]

^<<v11-19-3,3>>^ And he became afraid.^&#42;1^ Consequently he rose up and began to go for his soul^&#42;2^ and came to Beʹer-sheʹba, which belongs to Judah. Then he left his attendant behind there.

[NOTE]
====
. “Became afraid,” LXXSyVg and many Heb. mss; M, “got to see.”
. “His soul (life).” Heb., naph·shohʹ; Gr., psy·khenʹ.
====

[[v11-19-4]]

^<<v11-19-4,4>>^ And he himself went into the wilderness a day’s journey, and at length came and sat down under a certain broom tree. And he began to ask that his soul might die and to say: “It is enough! Now, O Jehovah, take my soul away, for I am no better than my forefathers.”

[[v11-19-5]]

^<<v11-19-5,5>>^ Finally he lay down and fell asleep under the broom tree. But, look! now an angel was touching him. Then he said to him: “Rise up, eat.”

[[v11-19-6]]

^<<v11-19-6,6>>^ When he looked, why, there at his head was a round cake upon heated stones and a jug of water. And he began to eat and drink, after which he lay down again.

[[v11-19-7]]

^<<v11-19-7,7>>^ Later the angel of Jehovah came back a second time and touched him and said: “Rise up, eat, for the journey is too much for you.”

[[v11-19-8]]

^<<v11-19-8,8>>^ So he rose up and ate and drank, and he kept going in the power of that nourishment for forty days and forty nights as far as the mountain of the &#91;true&#93; God, Hoʹreb.

[[v11-19-9]]

^<<v11-19-9,9>>^ There he finally entered into a cave, that he might spend the night there; and, look! there was Jehovah’s word for him, and it went on to say to him: “What is your business here, E·liʹjah?”

[[v11-19-10]]

^<<v11-19-10,10>>^ To this he said: “I have been absolutely jealous for Jehovah the God of armies; for the sons of Israel have left your covenant, your altars they have torn down, and your prophets they have killed with the sword, so that I only am left; and they begin looking for my soul to take it away.”

[[v11-19-11]]

^<<v11-19-11,11>>^ But it said: “Go out, and you must stand on the mountain before Jehovah.” And, look! Jehovah was passing by, and a great and strong wind was rending mountains and breaking crags before Jehovah. (Jehovah was not in the wind.) And after the wind there was a quaking. (Jehovah was not in the quaking.)

[[v11-19-12]]

^<<v11-19-12,12>>^ And after the quaking there was a fire. (Jehovah was not in the fire.) And after the fire there was a calm, low voice.^&#42;1^

[NOTE]
====
. “Voice, and Jehovah was there,” LXX.
====

[[v11-19-13]]

^<<v11-19-13,13>>^ And it came about that as soon as E·liʹjah heard it, he immediately wrapped his face in his official garment and went out and stood at the entrance of the cave; and, look! there was a voice for him, and it proceeded to say to him: “What is your business here, E·liʹjah?”

[[v11-19-14]]

^<<v11-19-14,14>>^ To this he said: “I have been absolutely jealous for Jehovah the God of armies; for the sons of Israel have left your covenant, your altars they have torn down, and your prophets they have killed with the sword, so that I only am left; and they begin looking for my soul to take it away.”

[[v11-19-15]]

^<<v11-19-15,15>>^ Jehovah now said to him: “Go, return on your way to the wilderness of Damascus; and you must come in and anoint Hazʹa·el as king over Syria.

[[v11-19-16]]

^<<v11-19-16,16>>^ And Jeʹhu the grandson^&#42;1^ of Nimʹshi you should anoint as king over Israel; and E·liʹsha^&#42;2^ the son of Shaʹphat from Aʹbel-me·hoʹlah you should anoint as prophet in place of you.

[NOTE]
====
. Lit., “son.”
. Meaning “God Is Salvation.” Heb., ʼEli·shaʽʹ; Gr., He·li·sai·eʹ; Lat., He·li·seʹum.
====

[[v11-19-17]]

^<<v11-19-17,17>>^ And it must occur that the one escaping from Hazʹa·el’s sword, Jeʹhu will put to death; and the one escaping from Jeʹhu’s sword, E·liʹsha will put to death.

[[v11-19-18]]

^<<v11-19-18,18>>^ And I have let seven thousand remain in Israel, all the knees that have not bent down to Baʹal, and every mouth that has not kissed him.”

[[v11-19-19]]

^<<v11-19-19,19>>^ Accordingly he went from there and found E·liʹsha the son of Shaʹphat while he was plowing with twelve spans before him, and he with the twelfth. So E·liʹjah crossed over to him and threw his official garment upon him.

[[v11-19-20]]

^<<v11-19-20,20>>^ At that he left the bulls and went running after E·liʹjah and said: “Let me, please, kiss my father and my mother. Then I will go following you.” At this he said to him: “Go, return; for what have I done to you?”

[[v11-19-21]]

^<<v11-19-21,21>>^ So he returned from following him and then took a span of the bulls and sacrificed them, and with the implements of the bulls he boiled their flesh and then gave it to the people, and they proceeded to eat. After that he rose up and went following E·liʹjah and began to minister to him.

'''

xref:011-1-kings/011-1-kings-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-kings/011-1-kings-020.adoc#v11-20-0[Próximo Capítulo &#62;]