include::./index.adoc[]

[[v11-7-0]]
=== The First of Kings, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-7-1]]

^<<v11-7-1,1>>^ And his own house Solʹo·mon built in thirteen years, so that he finished all his own house.

[[v11-7-2]]

^<<v11-7-2,2>>^ And he proceeded to build the House of the Forest of Lebʹa·non a hundred cubits^&#42;1^ in its length, and fifty cubits in its width, and thirty cubits in its height, upon four rows of pillars of cedarwood; and there were beams of cedarwood upon the pillars.

[NOTE]
====
. See App 8A.
====

[[v11-7-3]]

^<<v11-7-3,3>>^ And it was paneled in with cedarwood above upon the girders that were upon the forty-five pillars. There were fifteen to a row.

[[v11-7-4]]

^<<v11-7-4,4>>^ As for framed windows, there were three rows, and there was an illumination opening opposite an illumination opening in three tiers.

[[v11-7-5]]

^<<v11-7-5,5>>^ And all the entrances and the doorposts were squared &#91;with the&#93; frame, and also the forefront of the illumination opening opposite an illumination opening in three tiers.

[[v11-7-6]]

^<<v11-7-6,6>>^ And the Porch of Pillars he made fifty cubits in its length, and thirty cubits in its width; and another porch was in front of them with pillars and a canopy in front of them.

[[v11-7-7]]

^<<v11-7-7,7>>^ As for the Porch of the Throne where he would do judging, he made the porch of judgment; and they covered it in with cedarwood from the floor to the rafters.^&#42;1^

[NOTE]
====
. “Rafters,” by a slight correction; Sy, “ceiling”; Vg, “top”; M, “floor.”
====

[[v11-7-8]]

^<<v11-7-8,8>>^ As regards the house of his where he was to dwell, at the other courtyard, it was away from the house belonging to the Porch. It proved to be like this in workmanship. And there was a house like this Porch that he proceeded to build for Pharʹaoh’s daughter, whom Solʹo·mon had taken.

[[v11-7-9]]

^<<v11-7-9,9>>^ All these were &#91;of&#93; expensive stones according to measures, hewn, sawed with stone-saws, inside and outside, and from the foundation up to the coping, and outside as far as the great courtyard.

[[v11-7-10]]

^<<v11-7-10,10>>^ And the expensive stones laid as a foundation were great stones, stones of ten cubits, and stones of eight cubits.

[[v11-7-11]]

^<<v11-7-11,11>>^ And up above there were expensive stones according to measures, hewn, and also cedarwood.

[[v11-7-12]]

^<<v11-7-12,12>>^ As for the great courtyard, round about were three rows of hewn stone and a row of beams of cedarwood; and &#91;this&#93; also for the inner courtyard of the house of Jehovah, and for the porch of the house.

[[v11-7-13]]

^<<v11-7-13,13>>^ And King Solʹo·mon proceeded to send and fetch Hiʹram out of Tyre.

[[v11-7-14]]

^<<v11-7-14,14>>^ He was the son of a widowed woman from the tribe of Naphʹta·li, and his father was a Tyrʹi·an man, a worker in copper; and he was full of the wisdom and the understanding and the knowledge for doing every sort of work in copper. Accordingly he came to King Solʹo·mon and began to do all his work.

[[v11-7-15]]

^<<v11-7-15,15>>^ Then he cast the two pillars of copper, eighteen cubits being the height of each pillar, and a string of twelve cubits would measure around each of the two pillars.

[[v11-7-16]]

^<<v11-7-16,16>>^ And two capitals he made to put upon the tops of the pillars, cast in copper. Five cubits was the height of the one capital, and five cubits was the height of the other capital.

[[v11-7-17]]

^<<v11-7-17,17>>^ There were nets in network, twisted ornaments in chainwork, for the capitals that were upon the top of the pillars; seven^&#42;1^ for the one capital, and seven for the other capital.

[NOTE]
====
. “Seven,” M; LXX, “a net.”
====

[[v11-7-18]]

^<<v11-7-18,18>>^ And he went on to make the pomegranates^&#42;1^ and two rows round about upon the one network to cover the capitals that were upon the top of the pillars;^&#42;2^ and that was what he did for the other capital.

[NOTE]
====
. “Pomegranates,” two Heb. mss; M, “pillars.”
. “Pillars,” Sy and 50 Heb. mss; M, “pomegranates.”
====

[[v11-7-19]]

^<<v11-7-19,19>>^ And the capitals that were upon the top of the pillars at the porch were of lily work, of four cubits.

[[v11-7-20]]

^<<v11-7-20,20>>^ And the capitals were upon the two pillars, also up close beside the belly that was adjoining the network; and there were two hundred pomegranates in rows all around upon each capital.

[[v11-7-21]]

^<<v11-7-21,21>>^ And he proceeded to set up the pillars belonging to the porch of the temple. So he set up the right-hand^&#42;1^ pillar and called its name Jaʹchin,^&#42;2^ and then set up the left-hand^&#42;3^ pillar and called its name Boʹaz.^&#42;4^

[NOTE]
====
. Or, “southern,” that is, right, when one faces east.
. Meaning “He Will Firmly Establish.”
. Or, “northern,” that is, left, when one faces east.
. Possibly meaning “In Strength,” and to be read after the name of the other pillar, “Jachin.”
====

[[v11-7-22]]

^<<v11-7-22,22>>^ And upon the top of the pillars there was lily work. And the work of the pillars was gradually completed.

[[v11-7-23]]

^<<v11-7-23,23>>^ And he proceeded to make the molten sea ten cubits from its one brim to its other brim, circular all around; and its height was five cubits, and it took a line of thirty cubits to circle all around it.

[[v11-7-24]]

^<<v11-7-24,24>>^ And there were gourd-shaped ornaments down below its brim all around, encircling it, ten in a cubit, enclosing the sea all around, with two rows of the gourd-shaped ornaments cast in its casting.

[[v11-7-25]]

^<<v11-7-25,25>>^ It was standing upon twelve bulls,^&#42;1^ three facing north, and three facing west,^&#42;2^ and three facing south,^&#42;3^ and three facing east; and the sea was above upon them, and all their hind parts were toward the center.

[NOTE]
====
. Or, “cattle.”
. Lit., “toward the sea,” that is, the Mediterranean. Heb., yamʹmah.
. Lit., “toward the Negeb.” Heb., neghʹbah, “southward.”
====

[[v11-7-26]]

^<<v11-7-26,26>>^ And its thickness was a handbreadth;^&#42;1^ and its brim was like the workmanship of the brim of a cup, a lily blossom. Two thousand bath measures^&#42;2^ were what it would contain.

[NOTE]
====
. About 7.4 cm (2.9 in.).
. About 44,000 L (11,620 gal). Probably the normal operating level. Compare 2Ch 4:5 ftn, “Measures.”
====

[[v11-7-27]]

^<<v11-7-27,27>>^ And he went on to make the ten carriages of copper, four cubits being the length of each carriage, and four cubits its width, and three cubits its height.

[[v11-7-28]]

^<<v11-7-28,28>>^ And this was the workmanship of the carriages: they had sidewalls, and the sidewalls were between the crossbars.

[[v11-7-29]]

^<<v11-7-29,29>>^ And upon the sidewalls that were between the crossbars there were lions, bulls and cherubs, and over the crossbars it was like that. Up above and beneath the lions and the bulls there were wreaths in hanging work.^&#42;1^

[NOTE]
====
. Or, “punchwork.”
====

[[v11-7-30]]

^<<v11-7-30,30>>^ And there were four wheels of copper to each carriage, with axles of copper; and its four cornerpieces were supports for them. Beneath the basin were the supports, cast with wreaths across from each.

[[v11-7-31]]

^<<v11-7-31,31>>^ And its mouth from inside to the supports and upward was &#91;?&#93; cubits;^&#42;1^ and its mouth was round, the workmanship of a stand of one and a half cubits, and also upon its mouth there were carvings. And their sidewalls were squared, not round.

[NOTE]
====
. The number of cubits is missing from M.
====

[[v11-7-32]]

^<<v11-7-32,32>>^ And the four wheels were down below the sidewalls, and the supports of the wheels were by the carriage; and the height of each wheel was one and a half cubits.

[[v11-7-33]]

^<<v11-7-33,33>>^ And the workmanship of the wheels was like the workmanship of a chariot wheel. Their supports and their felloes and their spokes and their hubs, they were all cast.

[[v11-7-34]]

^<<v11-7-34,34>>^ And there were four supports upon the four corners of each carriage; its supports were of one piece with the carriage.

[[v11-7-35]]

^<<v11-7-35,35>>^ And on top of the carriage there was &#91;a stand&#93;^&#42;1^ a half a cubit in height, circular all around; and upon the top of the carriage its sides and its sidewalls were of one piece with it.

[NOTE]
====
. “A stand,” inserted because this word is evidently missing in M.
====

[[v11-7-36]]

^<<v11-7-36,36>>^ Further, he engraved upon the plates of its sides and upon its sidewalls cherubs, lions and palm-tree figures according to the clear space of each, and wreaths all around.

[[v11-7-37]]

^<<v11-7-37,37>>^ It was like this that he made the ten carriages; they all had one cast, one measure, one shape.

[[v11-7-38]]

^<<v11-7-38,38>>^ And he proceeded to make ten basins of copper. Forty bath^&#42;1^ measures were what each basin would contain. Each basin was four cubits. There was one basin upon each carriage for the ten carriages.

[NOTE]
====
. About 880 L (230 gal).
====

[[v11-7-39]]

^<<v11-7-39,39>>^ Then he put five carriages on the right side^&#42;1^ of the house, and five on the left side^&#42;2^ of the house; and the sea itself he put to the right side of the house eastward, toward the south.

[NOTE]
====
. Or, “south,” that is, the right side, when one faces east.
. Or, “north,” that is, the left side, when one faces east.
====

[[v11-7-40]]

^<<v11-7-40,40>>^ And Hiʹram gradually made the basins and the shovels and the bowls. At length Hiʹram finished doing all the work that he did for King Solʹo·mon as respects the house of Jehovah:

[[v11-7-41]]

^<<v11-7-41,41>>^ The two pillars and the bowl-shaped capitals that were upon the top of the two pillars, and the two networks to cover the two round capitals that were upon the top of the pillars,

[[v11-7-42]]

^<<v11-7-42,42>>^ and the four hundred pomegranates for the two networks, two rows of pomegranates to each network, to cover the two bowl-shaped capitals that were upon the two pillars;^&#42;1^

[NOTE]
====
. “Upon the two pillars,” LXX; SyVg, “upon the tops of the pillars”; M, “in front of the pillars.”
====

[[v11-7-43]]

^<<v11-7-43,43>>^ and the ten carriages and the ten basins upon the carriages,

[[v11-7-44]]

^<<v11-7-44,44>>^ and the one sea and the twelve bulls beneath the sea;

[[v11-7-45]]

^<<v11-7-45,45>>^ and the cans and the shovels and the bowls and all these utensils, which Hiʹram made of polished copper for King Solʹo·mon for the house of Jehovah.

[[v11-7-46]]

^<<v11-7-46,46>>^ In the District^&#42;1^ of the Jordan it was that the king cast them in the clay mold,^&#42;2^ between Sucʹcoth and Zarʹe·than.

[NOTE]
====
. See Ge 13:10 ftn, “District.”
. Or, “in the foundry of the ground.” Possibly, “at the ford of Adamah,” by a slight correction.
====

[[v11-7-47]]

^<<v11-7-47,47>>^ And Solʹo·mon left all the utensils &#91;unweighed&#93; because of so extraordinarily great a quantity. The weight of the copper was not ascertained.

[[v11-7-48]]

^<<v11-7-48,48>>^ And Solʹo·mon gradually made all the utensils that pertained to the house of Jehovah, the altar of gold and the table on which was the showbread,^&#42;1^ of gold,

[NOTE]
====
. Or, “the bread of Presence.” Lit., “bread of the faces.” Heb., leʹchem hap·pa·nimʹ; Vg, “the loaves of presentation.”
====

[[v11-7-49]]

^<<v11-7-49,49>>^ and the lampstands, five to the right and five to the left before the innermost room, of pure gold, and the blossoms and the lamps and the snuffers, of gold,

[[v11-7-50]]

^<<v11-7-50,50>>^ and the basins and the extinguishers and the bowls and the cups and the fire holders, of pure gold, and the sockets for the doors of the inner house, that is, the Most Holy,^&#42;1^ and for the doors of the house of the temple, of gold.

[NOTE]
====
. Or, “that is, the Holy of Holies.” Heb., leQoʹdhesh haq·Qodha·shimʹ.
====

[[v11-7-51]]

^<<v11-7-51,51>>^ Finally all the work that King Solʹo·mon had to do as regards the house of Jehovah was at its completion; and Solʹo·mon began to bring in the things made holy by David his father; the silver and the gold and the articles he put in the treasures of the house of Jehovah.

'''

xref:011-1-kings/011-1-kings-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-kings/011-1-kings-008.adoc#v11-8-0[Próximo Capítulo &#62;]