include::./index.adoc[]

[[v11-18-0]]
=== The First of Kings, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-18-1]]

^<<v11-18-1,1>>^ And it came about &#91;after&#93; many days that Jehovah’s own word came to E·liʹjah in the third year, saying: “Go, show yourself to Aʹhab, as I am determined to give rain^&#42;1^ upon the surface of the ground.”

[NOTE]
====
. Or, “and let me give rain.”
====

[[v11-18-2]]

^<<v11-18-2,2>>^ Accordingly E·liʹjah went to show himself to Aʹhab, while the famine was severe in Sa·marʹi·a.

[[v11-18-3]]

^<<v11-18-3,3>>^ Meantime, Aʹhab called O·ba·diʹah,^&#42;1^ who was over the household. (Now O·ba·diʹah himself had proved to be one greatly fearing Jehovah.

[NOTE]
====
. Meaning “Servant of Jehovah.” Heb., ʽO·vadh·yaʹhu.
====

[[v11-18-4]]

^<<v11-18-4,4>>^ Hence it came about that when Jezʹe·bel cut off Jehovah’s prophets, O·ba·diʹah proceeded to take a hundred prophets and keep them hid by fifties in a cave, and he supplied them bread and water.)

[[v11-18-5]]

^<<v11-18-5,5>>^ And Aʹhab went on to say to O·ba·diʹah: “Go through the land to all the springs of water and to all the torrent valleys. Perhaps we may find green grass, that we may preserve the horses and mules alive and may not have &#91;any more&#93; of the beasts cut off.”

[[v11-18-6]]

^<<v11-18-6,6>>^ So they divided between themselves the land through which to pass. Aʹhab himself went alone by one way, and O·ba·diʹah himself went alone by another way.

[[v11-18-7]]

^<<v11-18-7,7>>^ As O·ba·diʹah continued on the way, why, there was E·liʹjah to meet him. At once he recognized him and fell upon his face and said: “Is this you, my lord E·liʹjah?”

[[v11-18-8]]

^<<v11-18-8,8>>^ At this he said to him: “It is I. Go, say to your lord, ‘Here is E·liʹjah.’”

[[v11-18-9]]

^<<v11-18-9,9>>^ But he said: “What sin have I committed that you should be putting your servant into the hand of Aʹhab to put me to death?

[[v11-18-10]]

^<<v11-18-10,10>>^ As Jehovah your God is living, there is not a nation or kingdom where my lord has not sent to look for you. After they had said, ‘He is not &#91;here&#93;,’ he made the kingdom and the nation swear that they could not find you.

[[v11-18-11]]

^<<v11-18-11,11>>^ And now you are saying, ‘Go, say to your lord: “Here is E·liʹjah.”’

[[v11-18-12]]

^<<v11-18-12,12>>^ And it is bound to occur that, when I myself go from you, then the spirit of Jehovah itself will carry you away to where I shall not know; and I shall have come to tell Aʹhab, and he will not find you, and he will be bound to kill me, as your servant himself has feared Jehovah from his youth.

[[v11-18-13]]

^<<v11-18-13,13>>^ Has not my lord been told what I did when Jezʹe·bel killed the prophets of Jehovah, how I kept some of the prophets of Jehovah hid, a hundred men by fifties in a cave, and kept supplying them bread and water?

[[v11-18-14]]

^<<v11-18-14,14>>^ And now you are saying, ‘Go, say to your lord: “Here is E·liʹjah.”’ And he will be bound to kill me.”

[[v11-18-15]]

^<<v11-18-15,15>>^ However, E·liʹjah said: “As Jehovah of armies before whom I do stand^&#42;1^ is living, today I shall show myself to him.”

[NOTE]
====
. Or, “upon whom I do attend.”
====

[[v11-18-16]]

^<<v11-18-16,16>>^ Accordingly O·ba·diʹah went off to meet Aʹhab and told him; and so Aʹhab went to meet E·liʹjah.

[[v11-18-17]]

^<<v11-18-17,17>>^ And it came about that, as soon as Aʹhab saw E·liʹjah, Aʹhab immediately said to him: “Is this you, the bringer of ostracism upon Israel?”

[[v11-18-18]]

^<<v11-18-18,18>>^ To this he said: “I have not brought ostracism upon Israel, but you and the house of your father have, because YOU men have left the commandments of Jehovah, and you went following the Baʹals.

[[v11-18-19]]

^<<v11-18-19,19>>^ And now send, collect together all Israel to me at Mount Carʹmel and also the four hundred and fifty prophets of Baʹal and the four hundred prophets of the sacred pole, who are eating at the table of Jezʹe·bel.”

[[v11-18-20]]

^<<v11-18-20,20>>^ And Aʹhab proceeded to send among all the sons of Israel and collect the prophets together at Mount Carʹmel.

[[v11-18-21]]

^<<v11-18-21,21>>^ Then E·liʹjah approached all the people and said: “How long will YOU be limping upon two different opinions?^&#42;1^ If Jehovah is the &#91;true&#93; God,^&#42;2^ go following him; but if Baʹal is, go following him.” And the people did not say a word in answer to him.

[NOTE]
====
. Or, “two crutches,” KB, p. 663.
. “The [true] God.” Heb., ha·ʼElo·himʹ, with the definite article ha, “the,” preceding the title ʼElo·himʹ. This is done for emphasis in contrast with the false god Baal. See App 1F.
====

[[v11-18-22]]

^<<v11-18-22,22>>^ And E·liʹjah went on to say to the people: “I myself have been left as a prophet of Jehovah, I alone, while the prophets of Baʹal are four hundred and fifty men.

[[v11-18-23]]

^<<v11-18-23,23>>^ Now let them give us two young bulls, and let them choose for themselves one young bull and cut it in pieces and put it upon the wood, but they should not put fire to it. And I myself shall dress the other young bull, and I must place it upon the wood, but I shall not put fire to it.

[[v11-18-24]]

^<<v11-18-24,24>>^ And YOU must call upon the name of YOUR god,^&#42;1^ and I, for my part, shall call upon the name of Jehovah; and it must occur that the &#91;true&#93; God^&#42;2^ that answers by fire is the &#91;true&#93; God.”^&#42;3^ To this all the people answered and said: “The thing is good.”

[NOTE]
====
. “Your god.” Heb., ʼelo·heh·khemʹ, pl. of ʼelohʹah, referring to the false god Baal.
. “The [true] God.” Heb., ha·ʼElo·himʹ, followed by the relative clause “that answers by fire.”
. “The [true] God.” Heb., ha·ʼElo·himʹ, absolute, in the predicate. See App 1F.
====

[[v11-18-25]]

^<<v11-18-25,25>>^ E·liʹjah now said to the prophets of Baʹal:^&#42;1^ “Choose for yourselves one young bull and dress it first, because YOU are the majority; and call upon the name of YOUR god, but YOU must not put fire to it.”

[NOTE]
====
. Lit., “the Baal.” Heb., hab·Baʹʽal.
====

[[v11-18-26]]

^<<v11-18-26,26>>^ Accordingly they took the young bull that he gave them. Then they dressed it, and they kept calling upon the name of Baʹal from morning till noon, saying: “O Baʹal, answer us!” But there was no voice, and there was no one answering. And they kept limping around the altar that they had made.

[[v11-18-27]]

^<<v11-18-27,27>>^ And it came about at noon that E·liʹjah began to mock them and say: “Call at the top of YOUR voice,^&#42;1^ for he is a god; for he must be concerned with a matter, and he has excrement and has to go to the privy. Or maybe he is asleep and ought to wake up!”

[NOTE]
====
. Lit., “Call with a great voice.”
====

[[v11-18-28]]

^<<v11-18-28,28>>^ And they began calling at the top of their voice and cutting themselves according to their custom with daggers and with lances, until they caused blood to flow out upon them.

[[v11-18-29]]

^<<v11-18-29,29>>^ And it came about that, as soon as noon was past and they continued behaving as prophets until the going up of the grain offering, there was no voice, and there was no one answering, and there was no paying of attention.

[[v11-18-30]]

^<<v11-18-30,30>>^ At length E·liʹjah said to all the people: “Approach me.” So all the people approached him. Then he proceeded to mend the altar of Jehovah that was torn down.

[[v11-18-31]]

^<<v11-18-31,31>>^ So E·liʹjah took twelve stones, according to the number of the tribes of the sons of Jacob, to whom Jehovah’s word had come, saying: “Israel is what your name will become.”

[[v11-18-32]]

^<<v11-18-32,32>>^ And he went on to build the stones into an altar in the name of Jehovah and to make a trench, of about the area sowed with two seah^&#42;1^ measures of seed, all around the altar.

[NOTE]
====
. A seah equaled 7.33 L (6.66 dry qt).
====

[[v11-18-33]]

^<<v11-18-33,33>>^ After that he put the pieces of wood in order and cut the young bull in pieces and placed it upon the pieces of wood. He now said: “FILL four large jars with water and pour it upon the burnt offering and upon the pieces of wood.”

[[v11-18-34]]

^<<v11-18-34,34>>^ Then he said: “Do it again.” So they did it again. But he said: “Do it a third time.” So they did it a third time.

[[v11-18-35]]

^<<v11-18-35,35>>^ Thus the water went all around the altar, and the trench also he filled with water.

[[v11-18-36]]

^<<v11-18-36,36>>^ And it came about at the time that the grain offering goes up that E·liʹjah the prophet began to approach and say: “O Jehovah, the God of Abraham, Isaac and Israel, today let it be known that you are God in Israel and I am your servant and it is by your word that I have done all these things.

[[v11-18-37]]

^<<v11-18-37,37>>^ Answer me, O Jehovah, answer me, that this people may know that you, Jehovah, are the &#91;true&#93; God^&#42;1^ and you yourself have turned their heart back.”

[NOTE]
====
. Lit., “Jehovah, the [true] God.” Heb., Yehwahʹ ha·ʼElo·himʹ; Gr., Kyʹri·os ho The·osʹ; Lat., Doʹmi·nus Deʹus.
====

[[v11-18-38]]

^<<v11-18-38,38>>^ At that the fire of Jehovah came falling and went eating up the burnt offering and the pieces of wood and the stones and the dust, and the water that was in the trench it licked up.

[[v11-18-39]]

^<<v11-18-39,39>>^ When all the people saw it, they immediately fell upon their faces and said: “Jehovah is the &#91;true&#93; God! Jehovah is the &#91;true&#93; God!”

[[v11-18-40]]

^<<v11-18-40,40>>^ Then E·liʹjah said to them: “Seize the prophets of Baʹal! Do not let a single one of them escape!” At once they seized them, and E·liʹjah then brought them down to the torrent valley of Kiʹshon and slaughtered them there.

[[v11-18-41]]

^<<v11-18-41,41>>^ E·liʹjah now said to Aʹhab: “Go up, eat and drink; for there is the sound of the turmoil of a downpour.”

[[v11-18-42]]

^<<v11-18-42,42>>^ And Aʹhab proceeded to go up to eat and drink. As for E·liʹjah, he went up to the top of Carʹmel and began crouching to the earth and keeping his face put between his knees.

[[v11-18-43]]

^<<v11-18-43,43>>^ Then he said to his attendant: “Go up, please. Look in the direction of the sea.” So he went up and looked and then said: “There is nothing at all.” And he went on to say, “Go back,” for seven times.

[[v11-18-44]]

^<<v11-18-44,44>>^ And it came about at the seventh time that he got to say: “Look! There is a small cloud like a man’s palm ascending out of the sea.” He now said: “Go up, say to Aʹhab, ‘Hitch up! And go down that the downpour may not detain you!’”

[[v11-18-45]]

^<<v11-18-45,45>>^ And it came about in the meantime that the heavens themselves darkened up with clouds and wind^&#42;1^ and a great downpour began to occur. And Aʹhab kept riding and made his way to Jezʹre·el.

[NOTE]
====
. “And wind.” Heb., weruʹach; Gr., pneuʹma·ti; Lat., venʹtus. Compare Ge 1:2 ftn, “Force”; Ge 8:1 ftn.
====

[[v11-18-46]]

^<<v11-18-46,46>>^ And the very hand of Jehovah proved to be upon E·liʹjah, so that he girded up his hips and went running ahead of Aʹhab all the way to Jezʹre·el.

'''

xref:011-1-kings/011-1-kings-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-kings/011-1-kings-019.adoc#v11-19-0[Próximo Capítulo &#62;]