include::./index.adoc[]

[[v11-16-0]]
=== The First of Kings, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-16-1]]

^<<v11-16-1,1>>^ The word of Jehovah now came to Jeʹhu the son of Ha·naʹni against Baʹa·sha, saying:

[[v11-16-2]]

^<<v11-16-2,2>>^ “Inasmuch as I raised you up out of the dust that I might constitute you leader over my people Israel, but you went walking in the way of Jer·o·boʹam and so caused my people Israel to sin by offending me with their sins,

[[v11-16-3]]

^<<v11-16-3,3>>^ here I am making a clean sweep after Baʹa·sha and after his house, and I shall certainly constitute his house like the house of Jer·o·boʹam the son of Neʹbat.

[[v11-16-4]]

^<<v11-16-4,4>>^ Anyone of Baʹa·sha that is dying in the city the dogs will eat; and anyone of his that is dying in the field the fowls of the heavens will eat.”

[[v11-16-5]]

^<<v11-16-5,5>>^ As for the rest of the affairs of Baʹa·sha and what he did and his mightiness, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ Finally Baʹa·sha lay down with his forefathers and was buried in Tirʹzah; and Eʹlah his son began to reign in place of him.

[[v11-16-7]]

^<<v11-16-7,7>>^ And also by means of Jeʹhu the son of Ha·naʹni the prophet, Jehovah’s word itself had come against Baʹa·sha and his house, both because of all the badness that he committed in the eyes of Jehovah by offending him with the work of his hands, that it might become like the house of Jer·o·boʹam, and because he struck him^&#42;1^ down.

[NOTE]
====
. “Him,” that is, Nadab the son of Jeroboam. See 15:25-29.
====

[[v11-16-8]]

^<<v11-16-8,8>>^ In the twenty-sixth year of Aʹsa the king of Judah, Eʹlah the son of Baʹa·sha became king over Israel in Tirʹzah for two years.

[[v11-16-9]]

^<<v11-16-9,9>>^ And his servant Zimʹri the chief of half the chariots began to conspire against him, while he was in Tirʹzah drinking himself drunk at the house of Arʹza, who was over the household in Tirʹzah.

[[v11-16-10]]

^<<v11-16-10,10>>^ And Zimʹri proceeded to come in and strike him down and put him to death in the twenty-seventh year of Aʹsa the king of Judah, and he began to reign in place of him.

[[v11-16-11]]

^<<v11-16-11,11>>^ And it came about that when he began to reign, as soon as he sat down upon his throne, he struck down all the house of Baʹa·sha. He did not let anyone of his remain that urinates against a wall^&#42;1^ or his avengers of blood^&#42;2^ or his friends.

[NOTE]
====
. “Urinates against a wall.” A Heb. idiom for males.
. Or, “his goels,” M; SyVg, “his relatives.”
====

[[v11-16-12]]

^<<v11-16-12,12>>^ Thus Zimʹri annihilated the whole house of Baʹa·sha, according to the word of Jehovah that he had spoken against Baʹa·sha by means of Jeʹhu the prophet,

[[v11-16-13]]

^<<v11-16-13,13>>^ on account of all the sins of Baʹa·sha and the sins of Eʹlah his son with which they sinned and with which they caused Israel to sin by offending Jehovah the God of Israel with their vain idols.^&#42;1^

[NOTE]
====
. Lit., “their vanities.”
====

[[v11-16-14]]

^<<v11-16-14,14>>^ As for the rest of the affairs of Eʹlah and all that he did, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ In the twenty-seventh year of Aʹsa the king of Judah, Zimʹri became king for seven days in Tirʹzah, while the people were encamping against Gibʹbe·thon, which belonged to the Phi·lisʹtines.

[[v11-16-16]]

^<<v11-16-16,16>>^ In time the people that were encamped heard it said: “Zimʹri has conspired and also struck down the king.” So all Israel made Omʹri, the chief of the army, king over Israel on that day in the camp.

[[v11-16-17]]

^<<v11-16-17,17>>^ Omʹri and all Israel with him now went on up from Gibʹbe·thon and began to lay siege to Tirʹzah.

[[v11-16-18]]

^<<v11-16-18,18>>^ And it came about that as soon as Zimʹri saw that the city had been captured, he then came into the dwelling tower of the king’s house and burned the king’s house over himself with fire, so that he died,

[[v11-16-19]]

^<<v11-16-19,19>>^ for the sins of his with which he had sinned by doing what was bad in the eyes of Jehovah by walking in the way of Jer·o·boʹam and in his sin which he did by causing Israel to sin.

[[v11-16-20]]

^<<v11-16-20,20>>^ As for the rest of the affairs of Zimʹri and his conspiracy with which he conspired, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ It was then that the people of Israel began to divide themselves into two parts. There was one part of the people that became followers of Tibʹni the son of Giʹnath, to make him king, and the other part followers of Omʹri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Finally the people that were following Omʹri overcame the people that were following Tibʹni the son of Giʹnath; so that Tibʹni met death, and Omʹri began to reign.

[[v11-16-23]]

^<<v11-16-23,23>>^ In the thirty-first year of Aʹsa the king of Judah, Omʹri became king^&#42;1^ over Israel for twelve years. In Tirʹzah he reigned six years.

[NOTE]
====
. “Became king,” that is, became sole ruler upon the death of his rival, Tibni.
====

[[v11-16-24]]

^<<v11-16-24,24>>^ And he proceeded to buy the mountain of Sa·marʹi·a^&#42;1^ from Sheʹmer for two talents^&#42;2^ of silver, and began to build &#91;on&#93; the mountain and call the name of the city that he built by the name of Sheʹmer the master^&#42;3^ of the mountain, Sa·marʹi·a.

[NOTE]
====
. Meaning “Belonging to the Clan Shemer.” Heb., Sho·merohnʹ.
. See App 8A.
. Or, “lord of.” Heb., ʼadho·nehʹ, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v11-16-25]]

^<<v11-16-25,25>>^ And Omʹri kept doing what was bad in the eyes of Jehovah and came to do worse than all who were prior to him.

[[v11-16-26]]

^<<v11-16-26,26>>^ And he went walking in all the way of Jer·o·boʹam the son of Neʹbat and in his sin with which he caused Israel to sin by offending Jehovah the God of Israel with their vain idols.

[[v11-16-27]]

^<<v11-16-27,27>>^ As for the rest of the affairs of Omʹri, what he did and his mightiness with which he acted, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ Finally Omʹri lay down with his forefathers and was buried in Sa·marʹi·a; and Aʹhab his son began to reign in place of him.

[[v11-16-29]]

^<<v11-16-29,29>>^ And as for Aʹhab the son of Omʹri, he became king over Israel in the thirty-eighth year of Aʹsa the king of Judah; and Aʹhab the son of Omʹri continued to reign over Israel in Sa·marʹi·a twenty-two years.

[[v11-16-30]]

^<<v11-16-30,30>>^ And Aʹhab the son of Omʹri proceeded to do worse in the eyes of Jehovah than all those who were prior to him.

[[v11-16-31]]

^<<v11-16-31,31>>^ And it came about that, &#91;as if it were&#93; the most trivial thing for him to walk in the sins of Jer·o·boʹam the son of Neʹbat, he now took as wife Jezʹe·bel the daughter of Eth·baʹal the king of the Si·doʹni·ans and began to go and serve Baʹal^&#42;1^ and to bow down to him.

[NOTE]
====
. Lit., “the Baal.” Heb., hab·Baʹʽal.
====

[[v11-16-32]]

^<<v11-16-32,32>>^ Further, he set up an altar to Baʹal at the house of Baʹal that he built in Sa·marʹi·a.

[[v11-16-33]]

^<<v11-16-33,33>>^ And Aʹhab went on to make the sacred pole;^&#42;1^ and Aʹhab came to do more to offend Jehovah the God of Israel than all the kings of Israel that happened to be prior to him.

[NOTE]
====
. Or, “the Asherah.” Heb., ha·ʼAshe·rahʹ.
====

[[v11-16-34]]

^<<v11-16-34,34>>^ In his days Hiʹel the Bethʹel·ite built Jerʹi·cho. At the forfeit of A·biʹram his firstborn he laid the foundation of it, and at the forfeit of Seʹgub his youngest he put up its doors, according to Jehovah’s word that he spoke by means of Joshua^&#42;1^ the son of Nun.

[NOTE]
====
. “Joshua.” Heb., Yehoh·shuʹaʽ, “Jehoshua”; LXX, “Jesus”; Syr., deYe·shuʽ.
====

'''

xref:011-1-kings/011-1-kings-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-kings/011-1-kings-017.adoc#v11-17-0[Próximo Capítulo &#62;]