include::./index.adoc[]

[[v11-20-0]]
=== The First of Kings, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-20-1]]

^<<v11-20-1,1>>^ ^&#42;1^ As for Ben-haʹdad the king of Syria, he collected all his military forces together and also thirty-two kings with him and horses and chariots, and he proceeded to go up and lay siege to Sa·marʹi·a and fight against it.

[NOTE]
====
. LXX transposes chapters 20 and 21; therefore in LXX chapter 21 begins here.
====

[[v11-20-2]]

^<<v11-20-2,2>>^ Then he sent messengers to Aʹhab the king of Israel at the city. And he went on to say to him: “This is what Ben-haʹdad has said,

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘Your silver and your gold are mine, and your wives and your sons, the best looking, are mine.’”

[[v11-20-4]]

^<<v11-20-4,4>>^ To this the king of Israel answered and said: “According to your word, my lord the king, yours I am with all that belongs to me.”

[[v11-20-5]]

^<<v11-20-5,5>>^ Later the messengers came back and said: “This is what Ben-haʹdad has said, ‘I sent to you, saying: “Your silver and your gold and your wives and your sons you will give me.

[[v11-20-6]]

^<<v11-20-6,6>>^ But about this time tomorrow I shall send my servants to you, and they must carefully search your house and the houses of your servants; and it must occur that everything desirable to your eyes they will put in their hand, and they must take it away.”’”

[[v11-20-7]]

^<<v11-20-7,7>>^ At that the king of Israel called all the older men of the land and said: “Take note, please, and see that it is calamity that this one is seeking; for he sent to me for my wives and my sons and my silver and my gold, and I did not hold them back from him.”

[[v11-20-8]]

^<<v11-20-8,8>>^ Then all the older men and all the people said to him: “Do not obey, and you should not consent.”

[[v11-20-9]]

^<<v11-20-9,9>>^ So he said to the messengers of Ben-haʹdad: “Say to my lord the king, ‘All that you sent to your servant at first I shall do; but this thing I am not able to do.’” With that the messengers went off and brought word back to him.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-haʹdad now sent to him and said: “So may the gods do to me, and so may they add to it, if the dust of Sa·marʹi·a will be sufficient for handfuls for all the people that follow me!”^&#42;1^

[NOTE]
====
. Lit., “that are at my feet!”
====

[[v11-20-11]]

^<<v11-20-11,11>>^ In turn the king of Israel answered and said: “YOU men, speak &#91;to him&#93;, ‘Do not let one girding on boast about himself like one unfastening.’”

[[v11-20-12]]

^<<v11-20-12,12>>^ And it came about that as soon as he heard this word, while he himself and the kings were drinking in the booths, he immediately said to his servants: “Get set!” And they began to get set against the city.

[[v11-20-13]]

^<<v11-20-13,13>>^ And, look! a certain prophet approached Aʹhab the king of Israel and then said: “This is what Jehovah^&#42;1^ has said, ‘Have you seen all this great crowd? Here I am giving it into your hand today, and you will certainly know that I am Jehovah.’”^&#42;2^

[NOTE]
====
. “Jehovah.” Heb., Yehwahʹ; AqBurkitt uses the Tetragrammaton in the ancient Heb. characters; Gr., Kyʹri·os. See App 1C §7.
. See App 1C §7.
====

[[v11-20-14]]

^<<v11-20-14,14>>^ Then Aʹhab said: “By whom?” to which he said: “This is what Jehovah^&#42;1^ has said, ‘By the young men of the princes of the jurisdictional districts.’” Finally he said: “Who will open the battle engagement?” to which he said: “You!”

[NOTE]
====
. See App 1C §7.
====

[[v11-20-15]]

^<<v11-20-15,15>>^ And he proceeded to take the count of the young men of the princes of the jurisdictional districts, and they came to be two hundred and thirty-two; and after them he took the count of all the people, all the sons of Israel, seven thousand.

[[v11-20-16]]

^<<v11-20-16,16>>^ And they began to go out at noon while Ben-haʹdad was drinking himself drunk in the booths, he together with the kings, the thirty-two kings that were helping him.

[[v11-20-17]]

^<<v11-20-17,17>>^ When the young men of the princes of the jurisdictional districts came out first, Ben-haʹdad at once sent out; and they came telling him, saying: “There are men that have come out from Sa·marʹi·a.”

[[v11-20-18]]

^<<v11-20-18,18>>^ At that he said: “Whether it is for peace that they have come out, YOU should seize them alive; or whether it is for battle that they have come out, alive is how YOU should seize them.”

[[v11-20-19]]

^<<v11-20-19,19>>^ And these were the ones that came out from the city, the young men of the princes of the jurisdictional districts and the military forces that were behind them.

[[v11-20-20]]

^<<v11-20-20,20>>^ And they began to strike down each one his man; and the Syrians took to flight, and Israel went in pursuit of them, but Ben-haʹdad the king of Syria got to escape upon a horse together with the horsemen.

[[v11-20-21]]

^<<v11-20-21,21>>^ But the king of Israel went out and kept striking down the horses and the chariots, and he struck down the Syrians with a great slaughter.

[[v11-20-22]]

^<<v11-20-22,22>>^ Later the prophet approached the king of Israel and said to him: “Go, strengthen yourself and take note and see what you are going to do; for at the return of the year^&#42;1^ the king of Syria is coming up against you.”

[NOTE]
====
. “At the return of the year,” that is, next spring. See 2Ch 36:10.
====

[[v11-20-23]]

^<<v11-20-23,23>>^ As for the servants of the king of Syria, they said to him: “Their God is a God of mountains.^&#42;1^ That is why they proved stronger than we were. So, on the other hand, let us fight against them on the level land &#91;and see&#93; whether we shall not prove stronger than they are.

[NOTE]
====
. Or, “Their gods are gods of mountains.” See vs 28 ftn.
====

[[v11-20-24]]

^<<v11-20-24,24>>^ And do this thing: Remove the kings each one from his place and put in governors instead of them.

[[v11-20-25]]

^<<v11-20-25,25>>^ As for you, you should number a military force for yourself equal to the military force that fell from your side, with horse for horse and chariot for chariot; and let us fight against them on the level land &#91;and see&#93; whether we shall not prove stronger than they are.” Accordingly he listened to their voice and did just that way.

[[v11-20-26]]

^<<v11-20-26,26>>^ And it came about at the return of the year that Ben-haʹdad proceeded to muster the Syrians and to go up to Aʹphek for battle against Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ As for the sons of Israel, they were mustered and supplied and began to go out to meet them; and the sons of Israel went into camp in front of them like two tiny flocks of goats, while the Syrians, for their part, filled the earth.

[[v11-20-28]]

^<<v11-20-28,28>>^ Then the man of the &#91;true&#93; God approached and said to the king of Israel, yes, he went on to say: “This is what Jehovah has said, ‘For the reason that the Syrians have said: “Jehovah is a God^&#42;1^ of mountains, and he is not a God of low plains,” I shall have to give all this great crowd into your hand, and YOU men will certainly know that I am Jehovah.’”

[NOTE]
====
. “A God of.” Heb., ʼElo·hehʹ, pl. of ʼElohʹah, to denote excellence or majesty.
====

[[v11-20-29]]

^<<v11-20-29,29>>^ And they continued encamped for seven days, these in front of those. And it came about on the seventh day that the engagement in battle began; and the sons of Israel went striking down the Syrians, a hundred thousand men on foot in one day.

[[v11-20-30]]

^<<v11-20-30,30>>^ And those that were left went fleeing to Aʹphek, to the city; and the wall came falling down upon twenty-seven thousand men that were left. As for Ben-haʹdad, he fled and finally came into the city into the innermost chamber.

[[v11-20-31]]

^<<v11-20-31,31>>^ So his servants said to him: “Here, now, we have heard that the kings of the house of Israel are kings of loving-kindness. Please, let us carry sackcloth upon our loins and ropes upon our heads, and let us go out to the king of Israel. Perhaps he will preserve your soul alive.”

[[v11-20-32]]

^<<v11-20-32,32>>^ Accordingly they girded sackcloth about their loins, with ropes upon their heads, and came in to the king of Israel and said: “Your servant Ben-haʹdad has said, ‘Please, let my soul live.’” To this he said: “Is he still alive? He is my brother.”

[[v11-20-33]]

^<<v11-20-33,33>>^ So the men themselves took it as an omen and quickly took it as a decision of his own accord, and they went on to say: “Ben-haʹdad is your brother.” At that he said: “Come, fetch him.” Then Ben-haʹdad went out to him; and he at once had him get up into the chariot.

[[v11-20-34]]

^<<v11-20-34,34>>^ &#91;Ben-haʹdad&#93; now said to him: “The cities that my father took from your father I shall return; and streets you will assign to yourself in Damascus the same as my father assigned in Sa·marʹi·a.”
“And as for me, in a covenant I shall send you away.”
With that he concluded a covenant with him and sent him away.

[[v11-20-35]]

^<<v11-20-35,35>>^ And a certain man of the sons of the prophets^&#42;1^ said to his friend by the word of Jehovah: “Strike me, please.” But the man refused to strike him.

[NOTE]
====
. “Of the sons of the prophets.” Heb., mib·benehʹ han·nevi·ʼimʹ; the first occurrence of this expression.
====

[[v11-20-36]]

^<<v11-20-36,36>>^ Therefore he said to him: “For the reason that you did not listen to the voice of Jehovah, here you are going away from me, and a lion will certainly strike you down.” After that he went away from beside him, and the lion got to find him and strike him down.

[[v11-20-37]]

^<<v11-20-37,37>>^ And he went on to find another man and to say: “Strike me, please.” So the man struck him, striking and wounding.^&#42;1^

[NOTE]
====
. “Striking and wounding.” In Heb. these are verbs in the infinitive absolute, indefinite as to time and impersonal.
====

[[v11-20-38]]

^<<v11-20-38,38>>^ Then the prophet went and stood still for the king by the road, and he kept himself disguised with a bandage over his eyes.

[[v11-20-39]]

^<<v11-20-39,39>>^ And it came about that as the king was passing by, he cried out to the king and proceeded to say: “Your servant himself went out into the thick of the battle; and, look! a man was leaving the line, and he came bringing a man to me and then said, ‘Guard this man. If he should in any way be missing, your soul will also have to take the place of his soul, or else a talent^&#42;1^ of silver you will weigh out.’

[NOTE]
====
. See App 8A.
====

[[v11-20-40]]

^<<v11-20-40,40>>^ And it came about that as your servant was active here and there, why, he himself was gone.” At this the king of Israel said to him: “Thus your own judgment is. You yourself have decided.”

[[v11-20-41]]

^<<v11-20-41,41>>^ Upon that he hurriedly removed the bandage from over his eyes, and the king of Israel got to recognize him, that he was from the prophets.

[[v11-20-42]]

^<<v11-20-42,42>>^ He now said to him: “This is what Jehovah has said, ‘For the reason that you have let go out of your hand the man devoted to me for destruction,^&#42;1^ your soul must take the place of his soul, and your people the place of his people.’”

[NOTE]
====
. Lit., “the man, my devoted thing.”
====

[[v11-20-43]]

^<<v11-20-43,43>>^ At that the king of Israel went on his way toward his house, sullen and dejected, and came to Sa·marʹi·a.

'''

xref:011-1-kings/011-1-kings-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-kings/011-1-kings-021.adoc#v11-21-0[Próximo Capítulo &#62;]