include::./index.adoc[]

[[v11-11-0]]
=== The First of Kings, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-11-1]]

^<<v11-11-1,1>>^ And King Solʹo·mon himself loved many foreign wives along with the daughter of Pharʹaoh, Moʹab·ite, Amʹmon·ite, Eʹdom·ite, Si·doʹni·an &#91;and&#93; Hitʹtite women,

[[v11-11-2]]

^<<v11-11-2,2>>^ from the nations of whom Jehovah had said to the sons of Israel: “YOU must not go in among them, and they themselves should not come in among YOU; truly they will incline YOUR heart to follow their gods.” It was to them that Solʹo·mon clung to love &#91;them&#93;.

[[v11-11-3]]

^<<v11-11-3,3>>^ And he came to have seven hundred wives, princesses, and three hundred concubines; and his wives gradually inclined his heart.

[[v11-11-4]]

^<<v11-11-4,4>>^ And it came about in the time of Solʹo·mon’s growing old that his wives themselves had inclined his heart to follow other gods; and his heart did not prove to be complete with Jehovah his God like the heart of David his father.

[[v11-11-5]]

^<<v11-11-5,5>>^ And Solʹo·mon began going after Ashʹto·reth the goddess^&#42;1^ of the Si·doʹni·ans and after Milʹcom the disgusting thing of the Amʹmon·ites.

[NOTE]
====
. “Goddess of.” Heb., ʼelo·hehʹ, pl. of ʼelohʹah, to denote excellence. Masc., but here applied to a female deity.
====

[[v11-11-6]]

^<<v11-11-6,6>>^ And Solʹo·mon began to do what was bad in the eyes of Jehovah, and he did not follow Jehovah fully like David his father.

[[v11-11-7]]

^<<v11-11-7,7>>^ It was then that Solʹo·mon proceeded to build a high place to Cheʹmosh the disgusting thing of Moʹab on the mountain that was in front of Jerusalem, and to Moʹlech the disgusting thing of the sons of Amʹmon.

[[v11-11-8]]

^<<v11-11-8,8>>^ And that was the way he did for all his foreign wives who were making sacrificial smoke and sacrificing to their gods.

[[v11-11-9]]

^<<v11-11-9,9>>^ And Jehovah came to be incensed at Solʹo·mon, because his heart had inclined away from Jehovah the God of Israel, the one appearing to him twice.

[[v11-11-10]]

^<<v11-11-10,10>>^ And respecting this thing he commanded him not to go after other gods; but he had not kept that which Jehovah had commanded.

[[v11-11-11]]

^<<v11-11-11,11>>^ Jehovah now said to Solʹo·mon: “For the reason that this has taken place with you and you have not kept my covenant and my statutes that I laid in command upon you, I shall without fail rip the kingdom away from off you, and I shall certainly give it to your servant.

[[v11-11-12]]

^<<v11-11-12,12>>^ However, in your days I shall not do it, for the sake of David your father. Out of the hand of your son I shall rip it away.

[[v11-11-13]]

^<<v11-11-13,13>>^ Only it will not be all the kingdom that I shall rip away. One tribe I shall give to your son, for the sake of David my servant and for the sake of Jerusalem which I have chosen.”

[[v11-11-14]]

^<<v11-11-14,14>>^ And Jehovah began to raise up a resister^&#42;1^ to Solʹo·mon, namely, Haʹdad the Eʹdom·ite of the offspring of the king. He was in Eʹdom.

[NOTE]
====
. “A resister.” Heb. and Gr., sa·tanʹ; Syr., sa·ta·naʼ, “the resister”; Vg, “adversary.”
====

[[v11-11-15]]

^<<v11-11-15,15>>^ And it came about when David struck down Eʹdom,^&#42;1^ when Joʹab the chief of the army came up to bury those slain, that he tried to strike down every male in Eʹdom.

[NOTE]
====
. “When David struck down Edom,” by a slight emendation to agree with LXXSy; M, “when David happened to be with Edom.”
====

[[v11-11-16]]

^<<v11-11-16,16>>^ (For it was six months that Joʹab and all Israel dwelt there until he had cut off every male in Eʹdom.)

[[v11-11-17]]

^<<v11-11-17,17>>^ And Haʹdad went running away, he and some Eʹdom·ite men of the servants of his father with him, to come into Egypt, while Haʹdad was a young^&#42;1^ boy.

[NOTE]
====
. Lit., “little.”
====

[[v11-11-18]]

^<<v11-11-18,18>>^ So they rose up out of Midʹi·an and came into Paʹran and took men with them from Paʹran and came into Egypt to Pharʹaoh the king of Egypt, who then gave him a house. Also, bread he assigned to him, and land he gave him.

[[v11-11-19]]

^<<v11-11-19,19>>^ And Haʹdad continued to find favor in the eyes of Pharʹaoh, so much that he gave him a wife, the sister of his own wife, the sister of Tahʹpe·nes the lady.

[[v11-11-20]]

^<<v11-11-20,20>>^ In time the sister of Tahʹpe·nes bore him Ge·nuʹbath his son, and Tahʹpe·nes got to wean him right inside the house of Pharʹaoh; and Ge·nuʹbath continued at the house of Pharʹaoh right among the sons of Pharʹaoh.

[[v11-11-21]]

^<<v11-11-21,21>>^ And Haʹdad himself heard in Egypt that David had lain down with his forefathers and that Joʹab the chief of the army had died. So Haʹdad said to Pharʹaoh: “Send me away, that I may go to my own land.”

[[v11-11-22]]

^<<v11-11-22,22>>^ But Pharʹaoh said to him: “What are you in need of while with me that here you are seeking to go to your own land?” To this he said: “Nothing; but you ought to send me away without fail.”

[[v11-11-23]]

^<<v11-11-23,23>>^ And God proceeded to raise up to him another resister, namely, Reʹzon the son of E·liʹa·da, who had run away from Had·ad·eʹzer the king of Zoʹbah his lord.^&#42;1^

[NOTE]
====
. “His lord.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v11-11-24]]

^<<v11-11-24,24>>^ And he kept collecting men to his side and came to be chief of a marauder band, when David killed them.^&#42;1^ So they went to Damascus and took up dwelling in it and began reigning in Damascus.

[NOTE]
====
. “Them,” M; by correcting one Heb. consonant, “Syria.”
====

[[v11-11-25]]

^<<v11-11-25,25>>^ And he came to be a resister of Israel all the days of Solʹo·mon, and that along with the injury that Haʹdad did; and he had an abhorrence of Israel while he continued reigning over Syria.

[[v11-11-26]]

^<<v11-11-26,26>>^ And there was Jer·o·boʹam the son of Neʹbat an Eʹphra·im·ite from Zerʹe·dah, a servant of Solʹo·mon, and his mother’s name was Ze·ruʹah, a widowed woman. He too began to lift up his hand against the king.

[[v11-11-27]]

^<<v11-11-27,27>>^ And this is the reason why he lifted up his hand against the king: Solʹo·mon himself had built the Mound.^&#42;1^ He had closed up the gap of the City of David his father.

[NOTE]
====
. “The Mound.” Heb., ham·mil·lohʼʹ. See 9:15 ftn.
====

[[v11-11-28]]

^<<v11-11-28,28>>^ Now the man Jer·o·boʹam was a valiant, mighty man. When Solʹo·mon got to see that the young man was a hard worker, he proceeded to make him overseer^&#42;1^ over all the compulsory service of the house of Joseph.

[NOTE]
====
. “He proceeded to make him overseer.” Heb., wai·yaph·qedhʹ ʼo·thohʹ.
====

[[v11-11-29]]

^<<v11-11-29,29>>^ And it came about at that particular time that Jer·o·boʹam himself went out from Jerusalem, and A·hiʹjah the Shiʹlo·nite the prophet got to find him on the road, and &#91;A·hiʹjah&#93;^&#42;1^ was covering himself with a new garment; and the two of them were by themselves in the field.

[NOTE]
====
. “Ahijah,” LXXSy; MVg, “he.”
====

[[v11-11-30]]

^<<v11-11-30,30>>^ A·hiʹjah now took hold of the new garment that was on him and ripped it into twelve pieces.

[[v11-11-31]]

^<<v11-11-31,31>>^ And he went on to say to Jer·o·boʹam:
“Take for yourself ten pieces; for this is what Jehovah the God of Israel has said, ‘Here I am ripping the kingdom out of the hand of Solʹo·mon, and I shall certainly give you ten tribes.

[[v11-11-32]]

^<<v11-11-32,32>>^ And the one tribe is what will continue his for the sake of my servant David and for the sake of Jerusalem, the city that I have chosen out of all the tribes of Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ The reason why is that they have left me and begun to bow down to Ashʹto·reth the goddess^&#42;1^ of the Si·doʹni·ans, to Cheʹmosh the god^&#42;2^ of Moʹab and to Milʹcom the god of the sons of Amʹmon; and they have not walked in my ways by doing what is right in my eyes and my statutes and my judicial decisions like David his father.

[NOTE]
====
. See vs 5 ftn.
. “The god of.” Heb., ʼelo·hehʹ, pl. of ʼelohʹah, applied to a pagan deity. Compare Jg 16:23 ftn.
====

[[v11-11-34]]

^<<v11-11-34,34>>^ But I shall not take the entire kingdom out of his hand, because a chieftain^&#42;1^ I shall set him for all the days of his life, for the sake of David my servant whom I chose, because he kept my commandments and my statutes.

[NOTE]
====
. Or, “nasi.”
====

[[v11-11-35]]

^<<v11-11-35,35>>^ And I shall certainly take the kingship out of the hand of his son and give it to you, even ten tribes.

[[v11-11-36]]

^<<v11-11-36,36>>^ And to his son I shall give one tribe, in order that David my servant may continue having a lamp always before me in Jerusalem, the city that I have chosen for myself to put my name there.

[[v11-11-37]]

^<<v11-11-37,37>>^ And you are the one that I shall take, and you will indeed reign over all that your soul craves, and you will certainly become king over Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ And it must occur that, if you obey all that I shall command you, and you do walk in my ways and actually do what is right in my eyes by keeping my statutes and my commandments, just as David my servant did, I will also prove to be with you, and I will build you a lasting house, just as I have built for David, and I will give you Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ And I shall humiliate the offspring of David on account of this, only not always.’”

[[v11-11-40]]

^<<v11-11-40,40>>^ And Solʹo·mon began seeking to put Jer·o·boʹam to death. So Jer·o·boʹam got up and went running off to Egypt to Shiʹshak the king of Egypt, and he continued in Egypt until Solʹo·mon’s death.

[[v11-11-41]]

^<<v11-11-41,41>>^ As for the rest of the affairs of Solʹo·mon and all that he did and his wisdom, are they not written in the book of the affairs of Solʹo·mon?

[[v11-11-42]]

^<<v11-11-42,42>>^ And the days that Solʹo·mon had reigned in Jerusalem over all Israel were forty years.

[[v11-11-43]]

^<<v11-11-43,43>>^ Then Solʹo·mon lay down with his forefathers, and was buried in the City of David his father; and Re·ho·boʹam his son began to reign in place of him.

'''

xref:011-1-kings/011-1-kings-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-kings/011-1-kings-012.adoc#v11-12-0[Próximo Capítulo &#62;]