include::./index.adoc[]

[[v11-1-0]]
=== The First of Kings, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_or, according to the Greek Septuagint, THE THIRD OF KINGS_

[[v11-1-1]]

^<<v11-1-1,1>>^ Now King^&#42;1^ David was old, advanced in days; and they would cover him with garments, but he would not feel warm.

[NOTE]
====
. Lit., “Now the King.” Heb., weham·meʹlekh, sing.
====

[[v11-1-2]]

^<<v11-1-2,2>>^ So his servants said to him: “Let them look for a girl, a virgin, for my lord the king, and she will have to attend upon the king, that she may become his nurse; and she must lie in your bosom, and my lord the king will certainly feel warm.”

[[v11-1-3]]

^<<v11-1-3,3>>^ And they^&#42;1^ went looking for a beautiful girl throughout all the territory of Israel, and finally found Abʹi·shag the Shuʹnam·mite and then brought her in to the king.

[NOTE]
====
. Not referring to the “servants” in vs 2, but to those sent out to search.
====

[[v11-1-4]]

^<<v11-1-4,4>>^ And the girl was beautiful in the extreme; and she came to be the king’s nurse and kept waiting upon him, and the king himself had no intercourse with her.

[[v11-1-5]]

^<<v11-1-5,5>>^ All the while Ad·o·niʹjah the son of Hagʹgith was lifting himself up, saying: “I myself am going to rule as king!” And he proceeded to have a chariot made for himself with horsemen and fifty men running before him.

[[v11-1-6]]

^<<v11-1-6,6>>^ And his father did not hurt his feelings at any time^&#42;1^ by saying: “Why is this the way you have done?” And he was also very good-looking in form, and &#91;his mother&#93;^&#42;2^ had borne him after Abʹsa·lom.

[NOTE]
====
. Or, “all his life.” Lit., “from his days (years).”
. Lit., “she.”
====

[[v11-1-7]]

^<<v11-1-7,7>>^ And he came to have dealings with Joʹab the son of Ze·ruʹiah and with A·biʹa·thar the priest, and they began offering help as followers of Ad·o·niʹjah.

[[v11-1-8]]

^<<v11-1-8,8>>^ As for Zaʹdok the priest and Be·naiʹah^&#42;1^ the son of Je·hoiʹa·da and Nathan the prophet and Shimʹe·i and Reʹi and the mighty men that belonged to David, they did not become involved with Ad·o·niʹjah.^&#42;2^

[NOTE]
====
. “And Benaiah.” Heb., u·Vena·yaʹhu.
. “Adonijah.” Heb., ʼAdho·ni·yaʹhu.
====

[[v11-1-9]]

^<<v11-1-9,9>>^ Eventually Ad·o·niʹjah held a sacrifice of sheep and cattle and fatlings close by the stone of Zoʹhe·leth,^&#42;1^ which is beside En-roʹgel, and he proceeded to invite all his brothers the king’s sons and all the men of Judah the king’s servants;

[NOTE]
====
. Or, “the Gliding Stone.”
====

[[v11-1-10]]

^<<v11-1-10,10>>^ and Nathan the prophet and Be·naiʹah and the mighty men and Solʹo·mon his brother he did not invite.

[[v11-1-11]]

^<<v11-1-11,11>>^ Nathan now said to Bath-sheʹba, Solʹo·mon’s mother: “Have you not heard that Ad·o·niʹjah the son of Hagʹgith has become king, and our lord^&#42;1^ David does not know of it at all?

[NOTE]
====
. “And our lord.” Heb., wa·ʼadho·nehʹnu, pl. of ʼa·dhohnʹ, to denote excellence. See Ge 39:2 ftn.
====

[[v11-1-12]]

^<<v11-1-12,12>>^ So now come, let me, please, solemnly counsel you. And provide escape for your own soul and for the soul of your son Solʹo·mon.

[[v11-1-13]]

^<<v11-1-13,13>>^ Go and enter in to King David, and you must say to him, ‘Was it not you, my lord the king, that swore to your slave girl, saying: “Solʹo·mon your son is the one that will become king after me, and he is the one that will sit upon my throne”? So why has Ad·o·niʹjah become king?’

[[v11-1-14]]

^<<v11-1-14,14>>^ Look! While you are yet speaking there with the king, then I myself shall come in after you, and I shall certainly confirm your words.”

[[v11-1-15]]

^<<v11-1-15,15>>^ Accordingly Bath-sheʹba went in to the king in the interior room, and the king was very old, and Abʹi·shag the Shuʹnam·mite was waiting upon the king.

[[v11-1-16]]

^<<v11-1-16,16>>^ Then Bath-sheʹba bowed low and prostrated herself to the king, upon which the king said: “What do you have &#91;to ask&#93;?”

[[v11-1-17]]

^<<v11-1-17,17>>^ At this she said to him: “My lord, it was you that swore by Jehovah your God to your slave girl, ‘Solʹo·mon your son is the one that will become king after me, and he is the one that will sit upon my throne.’

[[v11-1-18]]

^<<v11-1-18,18>>^ And now, look! Ad·o·niʹjah himself has become king, and now my lord the king himself does not know of it at all.

[[v11-1-19]]

^<<v11-1-19,19>>^ So he sacrificed bulls and fatlings and sheep in great quantity and invited all the sons of the king and A·biʹa·thar the priest and Joʹab the chief of the army; but Solʹo·mon your servant he has not invited.

[[v11-1-20]]

^<<v11-1-20,20>>^ And you my lord the king—the eyes of all Israel are upon you, to tell them who is going to sit upon the throne of my lord the king after him.

[[v11-1-21]]

^<<v11-1-21,21>>^ And it will certainly occur that as soon as my lord the king lies down with his forefathers, I myself and also my son Solʹo·mon shall certainly become offenders.”

[[v11-1-22]]

^<<v11-1-22,22>>^ And, look! while she was yet speaking with the king, Nathan the prophet himself came in.

[[v11-1-23]]

^<<v11-1-23,23>>^ At once they told the king, saying: “Here is Nathan the prophet!” After that he came in before the king and prostrated himself to the king with his face to the earth.

[[v11-1-24]]

^<<v11-1-24,24>>^ Then Nathan said: “My lord the king, did you yourself say, ‘Ad·o·niʹjah is the one that will become king after me, and he is the one that will sit upon my throne’?

[[v11-1-25]]

^<<v11-1-25,25>>^ For he has today gone down that he might sacrifice bulls and fatlings and sheep in great quantity and might invite all the sons of the king and the chiefs of the army and A·biʹa·thar the priest; and there they are eating and drinking before him and they keep saying, ‘Let King Ad·o·niʹjah live!’

[[v11-1-26]]

^<<v11-1-26,26>>^ But as for me your servant, me and Zaʹdok the priest and Be·naiʹah the son of Je·hoiʹa·da and Solʹo·mon your servant he has not invited.

[[v11-1-27]]

^<<v11-1-27,27>>^ If it is from my lord the king that this thing has been brought about, then you have not caused your servant to know who should sit upon the throne of my lord the king after him.”

[[v11-1-28]]

^<<v11-1-28,28>>^ King David now answered and said: “YOU men, call Bath-sheʹba for me.” At that she came in before the king and stood before the king.

[[v11-1-29]]

^<<v11-1-29,29>>^ And the king proceeded to swear and say: “As Jehovah is living who redeemed my soul out of all distress,

[[v11-1-30]]

^<<v11-1-30,30>>^ just as I have sworn to you by Jehovah the God of Israel, saying, ‘Solʹo·mon your son is the one that will become king after me, and he is the one that will sit upon my throne in place of me!’ that is the way I shall do this day.”

[[v11-1-31]]

^<<v11-1-31,31>>^ Then Bath-sheʹba bowed low with her face to the earth and prostrated herself to the king and said: “Let my lord King David live to time indefinite!”

[[v11-1-32]]

^<<v11-1-32,32>>^ Immediately King David said: “YOU men, call for me Zaʹdok the priest and Nathan the prophet and Be·naiʹah the son of Je·hoiʹa·da.” So they came in before the king.

[[v11-1-33]]

^<<v11-1-33,33>>^ And the king went on to say to them: “Take with YOU the servants of YOUR lord,^&#42;1^ and YOU must make Solʹo·mon my son ride upon the she-mule that belongs to me and lead him down to Giʹhon.

[NOTE]
====
. See vs 11 ftn.
====

[[v11-1-34]]

^<<v11-1-34,34>>^ And Zaʹdok the priest and Nathan the prophet must anoint him there as king over Israel; and YOU must blow the horn and say, ‘Let King Solʹo·mon live!’

[[v11-1-35]]

^<<v11-1-35,35>>^ And YOU must come up following him, and he must come in and sit upon my throne; and he himself will be king in place of me, and him I shall have to commission to become leader over Israel and over Judah.”

[[v11-1-36]]

^<<v11-1-36,36>>^ At once Be·naiʹah the son of Je·hoiʹa·da answered the king and said: “Amen!^&#42;1^ Thus may Jehovah the God of my lord the king say.^&#42;2^

[NOTE]
====
. Or, “So let it be!” Heb., ʼa·menʹ.
. “Say,” MVg; Sy and two Heb. mss, “do.”
====

[[v11-1-37]]

^<<v11-1-37,37>>^ Just as Jehovah proved to be with my lord the king, so let him prove to be with Solʹo·mon, and may he make his throne greater than the throne of my lord King David.”

[[v11-1-38]]

^<<v11-1-38,38>>^ And Zaʹdok the priest and Nathan the prophet and Be·naiʹah the son of Je·hoiʹa·da and the Cherʹe·thites and the Pelʹe·thites proceeded to go down and make Solʹo·mon ride upon the she-mule of King David, and then brought him to Giʹhon.

[[v11-1-39]]

^<<v11-1-39,39>>^ Zaʹdok the priest now took the horn of oil out of the tent and anointed Solʹo·mon; and they began to blow the horn, and all the people broke out saying: “Let King Solʹo·mon live!”

[[v11-1-40]]

^<<v11-1-40,40>>^ After that all the people came on up following him, and the people were playing on flutes and rejoicing with great joy, so that the earth was split by the noise of them.

[[v11-1-41]]

^<<v11-1-41,41>>^ And Ad·o·niʹjah and all the ones invited that were with him got to hear it, when they themselves had finished eating. When Joʹab got to hear the sound of the horn, he at once said: “What does the noise of the town in an uproar mean?”

[[v11-1-42]]

^<<v11-1-42,42>>^ While he was yet speaking, why, here Jonʹa·than the son of A·biʹa·thar the priest came. Then Ad·o·niʹjah said: “Come on in, for you are a valiant man, and you bring good news.”

[[v11-1-43]]

^<<v11-1-43,43>>^ But Jonʹa·than answered and said to Ad·o·niʹjah: “No! Our lord^&#42;1^ King David himself has made Solʹo·mon king.

[NOTE]
====
. See vs 11 ftn.
====

[[v11-1-44]]

^<<v11-1-44,44>>^ So the king sent with him Zaʹdok the priest and Nathan the prophet and Be·naiʹah the son of Je·hoiʹa·da and the Cherʹe·thites and the Pelʹe·thites, and they made him ride upon the she-mule of the king.

[[v11-1-45]]

^<<v11-1-45,45>>^ Then Zaʹdok the priest and Nathan the prophet anointed him as king in Giʹhon; after which they came up from there rejoicing, and the town is in an uproar. That was the noise that YOU men heard.

[[v11-1-46]]

^<<v11-1-46,46>>^ And, besides, Solʹo·mon has sat down upon the throne of the kingship.

[[v11-1-47]]

^<<v11-1-47,47>>^ And, another thing, the servants of the king have come in to wish our lord King David well, saying, ‘May your God^&#42;1^ make Solʹo·mon’s name more splendid than your name, and may he make his throne greater than your throne!’ At that the king bowed down upon the bed.

[NOTE]
====
. “Your God,” M; MmarginLXXVg, “God”; Sy, “Jehovah your God.”
====

[[v11-1-48]]

^<<v11-1-48,48>>^ And too this is what the king said, ‘Blessed be Jehovah the God of Israel, who has today given one to sit upon my throne, with my own eyes seeing it!’”

[[v11-1-49]]

^<<v11-1-49,49>>^ And all those invited that were with Ad·o·niʹjah began to tremble and rise up and go each one on his own way.

[[v11-1-50]]

^<<v11-1-50,50>>^ And Ad·o·niʹjah himself was afraid because of Solʹo·mon. So he rose up and went away and grabbed hold of the horns of the altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ In time the report was made to Solʹo·mon, saying: “Here Ad·o·niʹjah himself has become afraid of King Solʹo·mon; and here he has taken hold on the horns of the altar, saying, ‘Let King Solʹo·mon first of all swear to me that he will not put his servant to death by the sword.’”

[[v11-1-52]]

^<<v11-1-52,52>>^ To this Solʹo·mon said: “If he will become a valiant man, there will not fall a single hair of his to the earth; but if what is bad should be found in him, he will also have to die.”

[[v11-1-53]]

^<<v11-1-53,53>>^ So King Solʹo·mon sent and they brought him down from off the altar. Then he came in and bowed down to King Solʹo·mon; after which Solʹo·mon said to him: “Go to your own house.”

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-kings/011-1-kings-002.adoc#v11-2-0[Próximo Capítulo &#62;]