include::./index.adoc[]

[[v11-2-0]]
=== The First of Kings, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-2-1]]

^<<v11-2-1,1>>^ And the days of David gradually drew near for him to die; and he proceeded to command Solʹo·mon his son, saying:

[[v11-2-2]]

^<<v11-2-2,2>>^ “I am going in the way of all the earth, and you must be strong and prove yourself to be a man.

[[v11-2-3]]

^<<v11-2-3,3>>^ And you must keep the obligation to Jehovah your God by walking in his ways, by keeping his statutes, his commandments and his judicial decisions and his testimonies,^&#42;1^ according to what is written in the law of Moses, in order that you may act prudently in everything that you do and everywhere that you turn;

[NOTE]
====
. Or, “reminders; exhortations.”
====

[[v11-2-4]]

^<<v11-2-4,4>>^ in order that Jehovah may carry out his word that he spoke respecting me, saying, ‘If your sons will take care of their way by walking before me in truth^&#42;1^ with all their heart and with all their soul, there will not be cut off a man of yours from &#91;sitting&#93; upon the throne of Israel.’

[NOTE]
====
. Or, “faithfulness.”
====

[[v11-2-5]]

^<<v11-2-5,5>>^ “And you yourself also well know what Joʹab the son of Ze·ruʹiah did to me in what he did to two chiefs of the armies of Israel, to Abʹner the son of Ner and A·maʹsa the son of Jeʹther, when he killed them and placed the blood of war in peacetime and put the blood of war on his belt that was about his hips and in his sandals that were on his feet.

[[v11-2-6]]

^<<v11-2-6,6>>^ And you must act according to your wisdom, and not let his gray hairs go down in peace to Sheʹol.^&#42;1^

[NOTE]
====
. “Sheol.” Heb., sheʼolʹ; Gr., haiʹdou; Syr., la·shiul; Lat., inʹfe·ros. See App 4B.
====

[[v11-2-7]]

^<<v11-2-7,7>>^ “And toward the sons of Bar·zilʹlai the Gilʹe·ad·ite you should exercise loving-kindness,^&#42;1^ and they must prove to be among those eating at your table; for that was the way they drew near to me when I ran away from before Abʹsa·lom your brother.

[NOTE]
====
. Or, “loyal love.”
====

[[v11-2-8]]

^<<v11-2-8,8>>^ “And here there is with you Shimʹe·i the son of Geʹra the Benʹja·min·ite from Ba·huʹrim, and he it was that called down evil upon me with a painful malediction on the day that I was going to Ma·ha·naʹim; and he it was that came down to meet me at the Jordan, so that I swore to him by Jehovah, saying, ‘I shall not put you to death by the sword.’

[[v11-2-9]]

^<<v11-2-9,9>>^ And now do not leave him unpunished, for you are a wise man and you well know what you ought to do to him, and you must bring his gray hairs down to Sheʹol with blood.”

[[v11-2-10]]

^<<v11-2-10,10>>^ Then David lay down with his forefathers and was buried in the City of David.

[[v11-2-11]]

^<<v11-2-11,11>>^ And the days that David had reigned over Israel were forty years. In Heʹbron he had reigned seven years, and in Jerusalem he had reigned thirty-three years.

[[v11-2-12]]

^<<v11-2-12,12>>^ As for Solʹo·mon, he sat down upon the throne of David his father; and gradually his kingship became very firmly established.

[[v11-2-13]]

^<<v11-2-13,13>>^ In time Ad·o·niʹjah the son of Hagʹgith came to Bath-sheʹba, Solʹo·mon’s mother. At this she said: “Is your coming peaceable?” to which he said: “It is peaceable.”

[[v11-2-14]]

^<<v11-2-14,14>>^ And he went on to say: “There is a matter I have for you.” So she said: “Speak.”

[[v11-2-15]]

^<<v11-2-15,15>>^ And he continued: “You yourself well know that the kingship was to have become mine, and it was toward me that all Israel had set their face for me to become king; but the kingship turned and came to be my brother’s, for it was from Jehovah that it became his.

[[v11-2-16]]

^<<v11-2-16,16>>^ And now there is one request that I am making of you. Do not turn my face away.” Accordingly she said to him: “Speak.”

[[v11-2-17]]

^<<v11-2-17,17>>^ And he went on to say: “Please, say to Solʹo·mon the king (for he will not turn your face away) that he should give me Abʹi·shag the Shuʹnam·mite as a wife.”

[[v11-2-18]]

^<<v11-2-18,18>>^ To this Bath-sheʹba said: “Good! I myself shall speak for you to the king.”

[[v11-2-19]]

^<<v11-2-19,19>>^ So Bath-sheʹba came in to King Solʹo·mon to speak to him for Ad·o·niʹjah. At once the king rose to meet her and bowed down to her. Then he sat down upon his throne and had a throne set for the mother of the king, that she might sit at his right.

[[v11-2-20]]

^<<v11-2-20,20>>^ And she proceeded to say: “There is one little request that I am making of you. Do not turn my face away.” So the king said to her: “Make it, my mother; for I shall not turn your face away.”

[[v11-2-21]]

^<<v11-2-21,21>>^ And she went on to say: “Let Abʹi·shag the Shuʹnam·mite be given to Ad·o·niʹjah your brother as a wife.”

[[v11-2-22]]

^<<v11-2-22,22>>^ At this King Solʹo·mon answered and said to his mother: “And why are you requesting Abʹi·shag the Shuʹnam·mite for Ad·o·niʹjah? Request also for him the kingship (because he is my brother older than I am), even for him and for A·biʹa·thar the priest and for Joʹab the son of Ze·ruʹiah.”

[[v11-2-23]]

^<<v11-2-23,23>>^ With that King Solʹo·mon swore by Jehovah, saying: “So may God do to me, and so may he add to it, if it was not against his own soul that Ad·o·niʹjah spoke this thing.

[[v11-2-24]]

^<<v11-2-24,24>>^ And now, as Jehovah is living who has firmly established me and keeps me seated upon the throne of David my father and who made a house for me just as he has spoken, today Ad·o·niʹjah will be put to death.”

[[v11-2-25]]

^<<v11-2-25,25>>^ Immediately King Solʹo·mon sent by means of Be·naiʹah the son of Je·hoiʹa·da; and he proceeded to fall upon him, so that he died.^&#42;1^

[NOTE]
====
. “Upon him, and Adonijah died on that day,” LXX.
====

[[v11-2-26]]

^<<v11-2-26,26>>^ And to A·biʹa·thar the priest the king said: “Go to Anʹa·thoth to your fields! For you are deserving of death;^&#42;1^ but on this day I shall not put you to death, because you carried the ark of the Sovereign Lord Jehovah before David my father, and because you suffered affliction during all the time that my father suffered affliction.”

[NOTE]
====
. Lit., “a man of death.”
====

[[v11-2-27]]

^<<v11-2-27,27>>^ So Solʹo·mon drove out A·biʹa·thar from serving as a priest of Jehovah, to fulfill Jehovah’s word that he had spoken against the house of Eʹli in Shiʹloh.

[[v11-2-28]]

^<<v11-2-28,28>>^ And the report itself came clear to Joʹab—for Joʹab himself had inclined to follow Ad·o·niʹjah, although Abʹsa·lom^&#42;1^ he had not inclined to follow—and Joʹab went fleeing to the tent of Jehovah and began to hold fast to the horns of the altar.

[NOTE]
====
. “Absalom,” MLXXBVg; LXXSyVgc, “Solomon.”
====

[[v11-2-29]]

^<<v11-2-29,29>>^ Then King Solʹo·mon was told: “Joʹab has fled to the tent of Jehovah, and there he is beside the altar.” So Solʹo·mon sent Be·naiʹah the son of Je·hoiʹa·da, saying: “Go, fall upon him!”

[[v11-2-30]]

^<<v11-2-30,30>>^ Accordingly Be·naiʹah came to the tent of Jehovah and said to him: “This is what the king has said, ‘Come on out!’” But he said: “No! For here is where I shall die.” At that Be·naiʹah brought word back to the king, saying: “This is what Joʹab spoke, and this is what he answered me.”

[[v11-2-31]]

^<<v11-2-31,31>>^ Then the king said to him: “Do just as he has spoken and fall upon him; and you must bury him and remove from off me and from off the house of my father the blood^&#42;1^ undeservedly shed that Joʹab spilled.

[NOTE]
====
. Lit., “bloods,” denoting cases of bloodshed.
====

[[v11-2-32]]

^<<v11-2-32,32>>^ And Jehovah will certainly bring back his blood upon his own head, because he fell upon two men more righteous and better than he was, and he proceeded to kill them with the sword, when my father David himself had not known of it, namely, Abʹner the son of Ner the chief of the army of Israel and A·maʹsa the son of Jeʹther the chief of the army of Judah.

[[v11-2-33]]

^<<v11-2-33,33>>^ And their blood must come back upon the head of Joʹab and upon the head of his offspring to time indefinite; but for David and for his offspring and for his house and for his throne there will come to be peace to time indefinite from Jehovah.”

[[v11-2-34]]

^<<v11-2-34,34>>^ Then Be·naiʹah the son of Je·hoiʹa·da went on up and fell upon him and put him to death; and he got to be buried at his own house in the wilderness.

[[v11-2-35]]

^<<v11-2-35,35>>^ Upon that the king put Be·naiʹah the son of Je·hoiʹa·da in place of him over the army; and Zaʹdok the priest the king put^&#42;1^ in the place of A·biʹa·thar.

[NOTE]
====
. “The king put,” M; LXX, “the king put as the high priest.”
====

[[v11-2-36]]

^<<v11-2-36,36>>^ Finally the king sent and called Shimʹe·i and said to him: “Build yourself a house in Jerusalem, and you must dwell there and not go out from there to this place and that.

[[v11-2-37]]

^<<v11-2-37,37>>^ And it must occur that on the day of your going out and when you do pass over the torrent valley of Kidʹron, you should unmistakably know that you will positively die. Bloodguilt for you^&#42;1^ will itself come to be upon your own head.”

[NOTE]
====
. Lit., “Your blood.” Heb., dom·khaʹ.
====

[[v11-2-38]]

^<<v11-2-38,38>>^ At this Shimʹe·i said to the king: “The word is good. Just as my lord the king has spoken is the way that your servant will do.” And Shimʹe·i kept dwelling in Jerusalem many days.

[[v11-2-39]]

^<<v11-2-39,39>>^ And it came about at the end of three years that two slaves of Shimʹe·i went running away to Aʹchish the son of Maʹa·cah the king of Gath; and people came telling Shimʹe·i, saying: “Look! Your slaves are at Gath.”

[[v11-2-40]]

^<<v11-2-40,40>>^ Immediately Shimʹe·i got up and saddled his ass and went to Gath to Aʹchish to look for his slaves; after which Shimʹe·i went and brought his slaves from Gath.

[[v11-2-41]]

^<<v11-2-41,41>>^ Then Solʹo·mon was told: “Shimʹe·i has gone out of Jerusalem to Gath and is back.”

[[v11-2-42]]

^<<v11-2-42,42>>^ At that the king sent and called Shimʹe·i and said to him: “Did I not put you under oath by Jehovah that I might warn you, saying, ‘On the day of your going outside and when you do go here and there you should unmistakably know that you will positively die,’ and so did you not say to me, ‘Good is the word that I have heard’?

[[v11-2-43]]

^<<v11-2-43,43>>^ Why, then, did you not keep the oath of Jehovah and the commandment that I solemnly laid upon you?”

[[v11-2-44]]

^<<v11-2-44,44>>^ And the king went on to say to Shimʹe·i: “You yourself certainly know all the injury which your heart well knows that you did to David my father; and Jehovah will certainly return the injury by you upon your own head.

[[v11-2-45]]

^<<v11-2-45,45>>^ But King Solʹo·mon will be blessed, and the throne of David itself will prove to be firmly established before Jehovah forever.”^&#42;1^

[NOTE]
====
. Or, “before Jehovah until time indefinite.”
====

[[v11-2-46]]

^<<v11-2-46,46>>^ With that the king commanded Be·naiʹah the son of Je·hoiʹa·da, who then went out and fell upon him, so that he died.
And the kingdom was firmly established in the hand of Solʹo·mon.

'''

xref:011-1-kings/011-1-kings-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-kings/011-1-kings-003.adoc#v11-3-0[Próximo Capítulo &#62;]