include::./index.adoc[]

[[v11-10-0]]
=== The First of Kings, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-10-1]]

^<<v11-10-1,1>>^ Now the queen of Sheʹba was hearing the report about Solʹo·mon in connection with the name of Jehovah. So she came to test him with perplexing questions.^&#42;1^

[NOTE]
====
. Or, “with riddles.”
====

[[v11-10-2]]

^<<v11-10-2,2>>^ Finally she arrived at Jerusalem with a very impressive train, camels carrying balsam oil and very much gold and precious stones; and she came on in to Solʹo·mon and began to speak to him all that happened to be close to her heart.

[[v11-10-3]]

^<<v11-10-3,3>>^ Solʹo·mon, in turn, went on to tell her all her matters. There proved to be no matter hidden from the king that he did not tell her.

[[v11-10-4]]

^<<v11-10-4,4>>^ When the queen of Sheʹba got to see all the wisdom of Solʹo·mon and the house that he had built,

[[v11-10-5]]

^<<v11-10-5,5>>^ and the food^&#42;1^ of his table and the sitting of his servants and the table service^&#42;2^ of his waiters and their attire and his drinks and his burnt sacrifices that he regularly offered up at the house of Jehovah, then there proved to be no more spirit in her.

[NOTE]
====
. Or, “dishes.”
. Lit., “the standing.”
====

[[v11-10-6]]

^<<v11-10-6,6>>^ So she said to the king: “True has the word proved to be that I heard in my own land about your matters and about your wisdom.

[[v11-10-7]]

^<<v11-10-7,7>>^ And I did not put faith in the words until I had come that my own eyes might see; and, look! I had not been told the half. You have surpassed in wisdom and prosperity the things heard to which I listened.

[[v11-10-8]]

^<<v11-10-8,8>>^ Happy are your men;^&#42;1^ happy are these servants of yours who are standing before you constantly, listening to your wisdom!

[NOTE]
====
. “Men,” MVg; LXXSyIt, “wives.”
====

[[v11-10-9]]

^<<v11-10-9,9>>^ May Jehovah your God come to be blessed, who has taken delight in you by putting you upon the throne of Israel; because Jehovah loves Israel to time indefinite, so that he appointed you as king to render judicial decision and righteousness.”

[[v11-10-10]]

^<<v11-10-10,10>>^ Then she gave the king a hundred and twenty talents of gold and a very great deal of balsam oil and precious stones. There never came anymore the like of that balsam oil for quantity such as the queen of Sheʹba gave to King Solʹo·mon.

[[v11-10-11]]

^<<v11-10-11,11>>^ And Hiʹram’s fleet of ships that carried gold from Oʹphir also brought from Oʹphir timbers of algum^&#42;1^ trees in very great amount and precious stones.

[NOTE]
====
. Heb., ʼal·mug·gimʹ. Compare 2Ch 2:8 ftn, “Algum.”
====

[[v11-10-12]]

^<<v11-10-12,12>>^ And the king proceeded to make out of the timbers of the algum trees supports for the house of Jehovah and for the house of the king, and also harps and stringed instruments for the singers. Timbers of algum trees like this have not come in nor have they been seen down to this day.

[[v11-10-13]]

^<<v11-10-13,13>>^ And King Solʹo·mon himself gave the queen of Sheʹba all her delight for which she asked, apart from what he gave her according to the openhandedness of King Solʹo·mon. After that she turned about and went to her own land, she together with her servants.

[[v11-10-14]]

^<<v11-10-14,14>>^ And the weight of the gold that came to Solʹo·mon in one year amounted up to six hundred and sixty-six talents of gold,^&#42;1^

[NOTE]
====
. About $256,643,000, with gold at $350 (U.S.) per oz t.
====

[[v11-10-15]]

^<<v11-10-15,15>>^ apart from the men of travel and the profit from the traders and all the kings of the Arabs and the governors of the land.

[[v11-10-16]]

^<<v11-10-16,16>>^ And King Solʹo·mon went on to make two hundred large shields of alloyed gold (six hundred &#91;shekels&#93;^&#42;1^ of gold he proceeded to lay upon each large shield),

[NOTE]
====
. “Six hundred shekels,” Vg; M, “six hundred”; Sy, “six hundred minas.” See App 8A.
====

[[v11-10-17]]

^<<v11-10-17,17>>^ and three hundred bucklers of alloyed gold (three miʹnas^&#42;1^ of gold he proceeded to lay upon each buckler^&#42;2^). Then the king put them in the House of the Forest of Lebʹa·non.

[NOTE]
====
. See App 8A.
. “Upon each buckler.” Heb., ʽal-ham·ma·ghenʹ, a shield smaller than the tsin·nahʹ, “large shield,” mentioned in vs 16.
====

[[v11-10-18]]

^<<v11-10-18,18>>^ Further, the king made a great ivory throne and overlaid it with refined gold.

[[v11-10-19]]

^<<v11-10-19,19>>^ There were six steps to the throne, and the throne had a round canopy behind it, and there were armrests on this side and on that side by the place of sitting, and two lions were standing beside the armrests.

[[v11-10-20]]

^<<v11-10-20,20>>^ And there were twelve lions standing there upon the six steps, on this side and on that side. No other kingdom had any made just like it.

[[v11-10-21]]

^<<v11-10-21,21>>^ And all the drinking vessels of King Solʹo·mon were of gold, and all the vessels of the House of the Forest of Lebʹa·non were of pure gold. There was nothing of silver; it was considered in the days of Solʹo·mon as nothing at all.

[[v11-10-22]]

^<<v11-10-22,22>>^ For the king had a fleet of ships of Tarʹshish on the sea along with Hiʹram’s fleet of ships. Once every three years the fleet of ships of Tarʹshish would come carrying gold and silver, ivory, and apes and peacocks.

[[v11-10-23]]

^<<v11-10-23,23>>^ So King Solʹo·mon was greater in riches and wisdom than all the other kings of the earth.

[[v11-10-24]]

^<<v11-10-24,24>>^ And all the people of the earth^&#42;1^ were seeking the face of Solʹo·mon to hear his wisdom that God^&#42;2^ had put in his heart.

[NOTE]
====
. Lit., “And all the earth,” but with the pl. participle “seeking.” LXXSy, “And all the kings of the earth.”
. “God,” M(Heb., ʼElo·himʹ)Vg; LXX, “Jehovah.”
====

[[v11-10-25]]

^<<v11-10-25,25>>^ And they were bringing each his gift, articles of silver and articles of gold and garments and armor and balsam oil, horses and mules, as a yearly matter of course.

[[v11-10-26]]

^<<v11-10-26,26>>^ And Solʹo·mon kept gathering more chariots and steeds;^&#42;1^ and he came to have a thousand four hundred chariots and twelve thousand steeds, and he kept them stationed in the chariot cities and close by the king in Jerusalem.

[NOTE]
====
. Or, “horsemen.”
====

[[v11-10-27]]

^<<v11-10-27,27>>^ And the king came to make the silver in Jerusalem like the stones, and cedarwood he made like the sycamore trees that are in the She·pheʹlah^&#42;1^ for great quantity.

[NOTE]
====
. Or, “the lowland.”
====

[[v11-10-28]]

^<<v11-10-28,28>>^ And there was the export of the horses that Solʹo·mon had from Egypt, and the company of the king’s merchants would themselves take the horse drove for a price.

[[v11-10-29]]

^<<v11-10-29,29>>^ And a chariot customarily came up and was exported from Egypt for six hundred silver pieces, and a horse for a hundred and fifty; and that was the way it was for all the kings of the Hitʹtites and the kings of Syria. It was by means of them^&#42;1^ that they did the exporting.

[NOTE]
====
. “It was by means of them,” M; LXX, “It was by sea.”
====

'''

xref:011-1-kings/011-1-kings-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-kings/011-1-kings-011.adoc#v11-11-0[Próximo Capítulo &#62;]