include::./index.adoc[]

[[v11-8-0]]
=== The First of Kings, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-8-1]]

^<<v11-8-1,1>>^ At that time Solʹo·mon proceeded to congregate the older men^&#42;1^ of Israel, all the heads of the tribes, the chieftains^&#42;2^ of the fathers, of the sons of Israel, to King Solʹo·mon at Jerusalem, to bring up the ark of the covenant of Jehovah out of the City of David, that is to say, Zion.

[NOTE]
====
. Or, “elders.”
. Or, “nasis.”
====

[[v11-8-2]]

^<<v11-8-2,2>>^ So all the men of Israel congregated themselves to King Solʹo·mon in the lunar month of Ethʹa·nim in the festival, that is, the seventh month.

[[v11-8-3]]

^<<v11-8-3,3>>^ So all the older men of Israel came, and the priests began to carry the Ark.

[[v11-8-4]]

^<<v11-8-4,4>>^ And they came bringing up the ark of Jehovah and the tent of meeting and all the holy utensils that were in the tent; and the priests and the Levites came bringing them up.

[[v11-8-5]]

^<<v11-8-5,5>>^ And King Solʹo·mon and with him all the assembly of Israel, those keeping their appointment with him, were before the Ark, sacrificing sheep and cattle that could not be counted or numbered for multitude.

[[v11-8-6]]

^<<v11-8-6,6>>^ Then the priests brought in the ark of the covenant of Jehovah to its place, to the innermost room of the house, the Most Holy, to underneath the wings of the cherubs.

[[v11-8-7]]

^<<v11-8-7,7>>^ For the cherubs were spreading out their wings over the place of the Ark, so that the cherubs kept the Ark and its poles screened over from above.

[[v11-8-8]]

^<<v11-8-8,8>>^ But the poles proved to be long, so that the tips of the poles were visible from the Holy in front of the innermost room, but they were not visible outside. And there they continue down to this day.

[[v11-8-9]]

^<<v11-8-9,9>>^ There was nothing in the Ark but the two stone tablets^&#42;1^ which Moses had deposited there in Hoʹreb, when Jehovah had covenanted^&#42;2^ with the sons of Israel while they were coming out from the land of Egypt.

[NOTE]
====
. LXX adds “tablets of the covenant.”
. Lit., “had cut [a covenant].”
====

[[v11-8-10]]

^<<v11-8-10,10>>^ And it came about that when the priests came out from the holy place, the cloud itself filled the house of Jehovah.

[[v11-8-11]]

^<<v11-8-11,11>>^ And the priests were unable to stand to do their ministering because of the cloud, for the glory of Jehovah filled the house of Jehovah.

[[v11-8-12]]

^<<v11-8-12,12>>^ At that time Solʹo·mon said: “Jehovah himself said he was to reside in the thick gloom.

[[v11-8-13]]

^<<v11-8-13,13>>^ I have successfully built a house of lofty abode for you, an established place for you to dwell in to time indefinite.”^&#42;1^

[NOTE]
====
. “To time indefinite.” Lit., “times indefinite.” Heb., ʽoh·la·mimʹ, pl.
====

[[v11-8-14]]

^<<v11-8-14,14>>^ Then the king turned his face and began to bless all the congregation^&#42;1^ of Israel, while all the congregation of Israel were standing up.

[NOTE]
====
. “Congregation of.” Heb., qehalʹ; LXXVg, “ecclesia.”
====

[[v11-8-15]]

^<<v11-8-15,15>>^ And he went on to say: “Blessed is Jehovah the God of Israel, who spoke by his own mouth with David my father, and by his own hand has given fulfillment, saying,

[[v11-8-16]]

^<<v11-8-16,16>>^ ‘From the day that I brought my people Israel out from Egypt I have not chosen a city out of all the tribes of Israel to build a house for my name to continue there; but I shall choose David to come to be over my people Israel.’

[[v11-8-17]]

^<<v11-8-17,17>>^ And it came to be close to the heart of David my father to build a house to the name of Jehovah the God of Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ But Jehovah said to David my father, ‘For the reason that it proved to be close to your heart to build a house to my name, you did well, because it proved to be close to your heart.

[[v11-8-19]]

^<<v11-8-19,19>>^ Only you yourself will not build the house, but your son who is coming forth from your loins is the one that will build the house to my name.’

[[v11-8-20]]

^<<v11-8-20,20>>^ And Jehovah proceeded to carry out his word that he had spoken, that I might rise up in the place of David my father and sit upon the throne of Israel, just as Jehovah had spoken, and that I might build the house to the name of Jehovah the God of Israel,

[[v11-8-21]]

^<<v11-8-21,21>>^ and that I might locate a place there for the Ark where the covenant of Jehovah is that he concluded with our forefathers when he was bringing them out from the land of Egypt.”

[[v11-8-22]]

^<<v11-8-22,22>>^ And Solʹo·mon began standing before the altar of Jehovah in front of all the congregation of Israel, and he now spread his palms out to the heavens;

[[v11-8-23]]

^<<v11-8-23,23>>^ and he went on to say: “O Jehovah the God of Israel, there is no God^&#42;1^ like you in the heavens above or on the earth beneath, keeping the covenant and the loving-kindness^&#42;2^ toward your servants who are walking before you with all their heart,

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Gr., The·osʹ.
. Or, “loyal love.”
====

[[v11-8-24]]

^<<v11-8-24,24>>^ you who have kept toward your servant David my father that which you promised him, so that you made the promise^&#42;1^ with your own mouth, and with your own hand you have made the fulfillment, as at this day.

[NOTE]
====
. Lit., “you spoke.”
====

[[v11-8-25]]

^<<v11-8-25,25>>^ And now, O Jehovah the God of Israel, keep toward your servant David my father that which you promised him, saying, ‘There will not be cut off a man of yours from before me to sit upon the throne of Israel, if only your sons will take care of their way by walking before me just as you have walked before me.’

[[v11-8-26]]

^<<v11-8-26,26>>^ And now, O God of Israel,^&#42;1^ let your promise^&#42;2^ that you have promised to your servant David my father prove trustworthy, please.

[NOTE]
====
. “O God of Israel,” M; TLXXSyVgc and 35 Heb. mss, “O Jehovah the God of Israel.”
. Lit., “word.”
====

[[v11-8-27]]

^<<v11-8-27,27>>^ “But will God truly dwell upon the earth? Look! The heavens, yes, the heaven of the heavens, themselves cannot contain you; how much less, then, this house that I have built!

[[v11-8-28]]

^<<v11-8-28,28>>^ And you must turn toward the prayer of your servant and to his request for favor, O Jehovah my God, to listen to the entreating cry and to the prayer with which your servant is praying before you today;

[[v11-8-29]]

^<<v11-8-29,29>>^ that your eyes may prove to be opened toward this house night and day, toward the place of which you said, ‘My name will prove to be there,’ to listen to the prayer with which your servant prays toward this place.

[[v11-8-30]]

^<<v11-8-30,30>>^ And you must listen to the request for favor on the part of your servant and of your people Israel with which they pray toward this place; and may you yourself hear at the place of your dwelling, in the heavens, and you must hear and forgive.

[[v11-8-31]]

^<<v11-8-31,31>>^ “When a man sins against his fellowman, and he actually lays a cursing upon him to bring him under liability to the curse, and he actually comes &#91;within&#93; the curse before your altar in this house,

[[v11-8-32]]

^<<v11-8-32,32>>^ then may you yourself hear from the heavens, and you must act and judge your servants by pronouncing the wicked one wicked by putting his way upon his own head, and by pronouncing the righteous one righteous by giving to him according to his own righteousness.

[[v11-8-33]]

^<<v11-8-33,33>>^ “When your people Israel are defeated before the enemy, because they kept sinning against you, and they indeed return to you and laud your name and pray and make request for favor toward you in this house,

[[v11-8-34]]

^<<v11-8-34,34>>^ then may you yourself hear from heaven, and you must forgive the sin of your people Israel and you must bring them back to the ground that you gave to their forefathers.

[[v11-8-35]]

^<<v11-8-35,35>>^ “When heaven is shut up so that no rain occurs, because they kept sinning against you, and they actually pray toward this place and laud your name, and from their sin they turn back, because you kept afflicting them,

[[v11-8-36]]

^<<v11-8-36,36>>^ then may you yourself hear from the heavens, and you must forgive the sin of your servants, even of your people Israel, because you teach them the good way in which they should walk; and you must give rain upon your land that you have given to your people as a hereditary possession.

[[v11-8-37]]

^<<v11-8-37,37>>^ “In case a famine occurs in the land, in case a pestilence occurs, in case scorching, mildew, locusts, cockroaches occur; in case their enemy besieges them in the land of their gates^&#42;1^—any sort of plague, any sort of malady—

[NOTE]
====
. Or, “cities,” represented by the “gates,” by a figure of speech, synecdoche.
====

[[v11-8-38]]

^<<v11-8-38,38>>^ whatever prayer, whatever request for favor there may occur on the part of any man &#91;or&#93; of all your people Israel, because they know each one the plague of his own heart, and they actually spread out their palms to this house,

[[v11-8-39]]

^<<v11-8-39,39>>^ then may you yourself hear from the heavens, your established place of dwelling, and you must forgive and act and give to each one according to all his ways, because you know his heart (for you yourself alone well know the heart of all the sons of mankind^&#42;1^);

[NOTE]
====
. Or, “humankind.” Heb., ha·ʼa·dhamʹ; LXXVg, “men.”
====

[[v11-8-40]]

^<<v11-8-40,40>>^ to the end that they may fear you all the days that they are alive upon the surface of the ground that you gave to our forefathers.

[[v11-8-41]]

^<<v11-8-41,41>>^ “And also to the foreigner, who is no part of your people Israel and who actually comes from a distant land by reason of your name

[[v11-8-42]]

^<<v11-8-42,42>>^ (for they shall hear of your great name and of your strong hand and of your stretched-out arm), and he actually comes and prays toward this house,

[[v11-8-43]]

^<<v11-8-43,43>>^ may you yourself listen from the heavens, your established place of dwelling, and you must do according to all that for which the foreigner calls to you; in order that all the peoples of the earth may get to know your name so as to fear you the same as your people Israel do, and so as to know that your name itself has been called upon this house that I have built.

[[v11-8-44]]

^<<v11-8-44,44>>^ “In case your people go out to the war against their enemy in the way that you send them, and they indeed pray to Jehovah in the direction of the city that you have chosen and the house that I have built to your name,

[[v11-8-45]]

^<<v11-8-45,45>>^ you must also hear from the heavens their prayer and their request for favor, and you must execute judgment for them.

[[v11-8-46]]

^<<v11-8-46,46>>^ “In case they sin against you (for there is no man that does not sin), and you have to be incensed at them and abandon them to the enemy, and their captors actually carry them off captive to the land of the enemy distant or nearby;

[[v11-8-47]]

^<<v11-8-47,47>>^ and they indeed come to their senses^&#42;1^ in the land where they have been carried off captive, and they actually return and make request to you for favor in the land of their captors, saying, ‘We have sinned and erred, we have acted wickedly’;

[NOTE]
====
. Lit., “and they indeed cause a returning to their heart.”
====

[[v11-8-48]]

^<<v11-8-48,48>>^ and they indeed return to you with all their heart and with all their soul in the land of their enemies who carried them off captive, and they indeed pray to you in the direction of their land that you gave to their forefathers, the city that you have chosen and the house that I have built to your name;

[[v11-8-49]]

^<<v11-8-49,49>>^ you must also hear from the heavens, your established place of dwelling, their prayer and their request for favor, and you must execute judgment for them,

[[v11-8-50]]

^<<v11-8-50,50>>^ and you must forgive your people who had sinned against you and all their transgressions with which they transgressed against you; and you must make them objects of pity before their captors and they must pity them

[[v11-8-51]]

^<<v11-8-51,51>>^ (for they are your people and your inheritance, whom you brought out from Egypt, from inside the iron furnace),

[[v11-8-52]]

^<<v11-8-52,52>>^ that your eyes may prove to be opened to the request for favor of your servant and to the request for favor of your people Israel, by listening to them in all for which they call to you.

[[v11-8-53]]

^<<v11-8-53,53>>^ For you yourself separated them as your inheritance out of all the peoples of the earth, just as you have spoken by means of Moses your servant^&#42;1^ when you were bringing our forefathers out from Egypt, O Sovereign Lord Jehovah.”

[NOTE]
====
. “Moses your servant.” The first of three occurrences of this expression. See Ne 1:8; Ne 9:14.
====

[[v11-8-54]]

^<<v11-8-54,54>>^ And it came about that, as soon as Solʹo·mon finished praying to Jehovah with all this prayer and request for favor, he rose up from before the altar of Jehovah, from bending down upon his knees with his palms spread out to the heavens;

[[v11-8-55]]

^<<v11-8-55,55>>^ and he began to stand and bless all the congregation^&#42;1^ of Israel with a loud voice, saying:

[NOTE]
====
. “Congregation of.” Heb., qehalʹ; Gr., ek·kle·siʹan; Lat., ec·cleʹsi·ae.
====

[[v11-8-56]]

^<<v11-8-56,56>>^ “Blessed be Jehovah, who has given a resting-place to his people Israel according to all that he has promised. There has not failed one word of all his good promise that he has promised^&#42;1^ by means of Moses his servant.

[NOTE]
====
. Lit., “his good word that he has spoken.”
====

[[v11-8-57]]

^<<v11-8-57,57>>^ May Jehovah our God prove to be with us just as he proved to be with our forefathers. May he neither leave us nor forsake us,

[[v11-8-58]]

^<<v11-8-58,58>>^ so as to incline our heart to himself to walk in all his ways and to keep his commandments and his regulations and his judicial decisions, which he gave in command to our forefathers.

[[v11-8-59]]

^<<v11-8-59,59>>^ And may these words of mine with which I have made request for favor before Jehovah prove to be near to Jehovah our God by day and night, that he may execute judgment for his servant and judgment for his people Israel as it may require day by day;

[[v11-8-60]]

^<<v11-8-60,60>>^ to the end that all the peoples of the earth may know that Jehovah is the &#91;true&#93; God. There is no other.

[[v11-8-61]]

^<<v11-8-61,61>>^ And YOUR heart must prove to be complete with Jehovah our God by walking in his regulations and by keeping his commandments as at this day.”

[[v11-8-62]]

^<<v11-8-62,62>>^ And the king and all Israel with him were offering a grand sacrifice before Jehovah.

[[v11-8-63]]

^<<v11-8-63,63>>^ And Solʹo·mon proceeded to offer the communion sacrifices that he had to offer to Jehovah, twenty-two thousand cattle and a hundred and twenty thousand sheep, that the king and all the sons of Israel might inaugurate the house of Jehovah.

[[v11-8-64]]

^<<v11-8-64,64>>^ On that day the king had to sanctify the middle of the courtyard that is before the house of Jehovah, because there he had to render up the burnt sacrifice and the grain offering and the fat pieces of the communion sacrifices; for the copper altar that is before Jehovah was too small to contain the burnt sacrifice and the grain offering and the fat pieces of the communion sacrifices.

[[v11-8-65]]

^<<v11-8-65,65>>^ And Solʹo·mon proceeded to carry on at that time the festival, and all Israel with him, a great congregation from the entering in of Haʹmath^&#42;1^ down to the torrent valley of Egypt, before Jehovah our God^&#42;2^ seven days and another seven days, fourteen days.

[NOTE]
====
. See Jos 13:5 ftn, “Hamath.”
. “Before Jehovah our God in the house that he built, eating and drinking and rejoicing before Jehovah our God,” LXX.
====

[[v11-8-66]]

^<<v11-8-66,66>>^ On the eighth day he sent the people away; and they began to bless the king and to go to their homes,^&#42;1^ rejoicing and feeling merry of heart over all the goodness that Jehovah had performed for David his servant and for Israel his people.

[NOTE]
====
. Lit., “tents.”
====

'''

xref:011-1-kings/011-1-kings-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-kings/011-1-kings-009.adoc#v11-9-0[Próximo Capítulo &#62;]