include::./index.adoc[]

[[v11-22-0]]
=== The First of Kings, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-22-1]]

^<<v11-22-1,1>>^ And for three years they continued dwelling without war between Syria and Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ And it came about in the third year that Je·hoshʹa·phat^&#42;1^ the king of Judah proceeded to go down to the king of Israel.

[NOTE]
====
. Meaning “Jehovah Is Judge.” Heb., Yehoh·sha·phatʹ.
====

[[v11-22-3]]

^<<v11-22-3,3>>^ Then the king of Israel said to his servants: “Do YOU really know that Raʹmoth-gilʹe·ad belongs to us? Yet we are hesitating to take it out of the hand of the king of Syria.”

[[v11-22-4]]

^<<v11-22-4,4>>^ And he went on to say to Je·hoshʹa·phat: “Will you go with me to the fight at Raʹmoth-gilʹe·ad?” At this Je·hoshʹa·phat said to the king of Israel: “I am the same as you. My people are the same as your people. My horses are the same as your horses.”

[[v11-22-5]]

^<<v11-22-5,5>>^ However, Je·hoshʹa·phat went on to say to the king of Israel: “Inquire, please, first of all for the word of Jehovah.”

[[v11-22-6]]

^<<v11-22-6,6>>^ So the king of Israel collected the prophets together, about four hundred men, and said to them: “Shall I go against Raʹmoth-gilʹe·ad in war, or shall I refrain?” And they began to say: “Go up, and Jehovah^&#42;1^ will give it into the king’s hand.”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v11-22-7]]

^<<v11-22-7,7>>^ But Je·hoshʹa·phat said: “Is there not here a prophet of Jehovah still? Then let us inquire through him.”

[[v11-22-8]]

^<<v11-22-8,8>>^ At that the king of Israel said to Je·hoshʹa·phat: “There is still one man through whom to inquire of Jehovah; but I myself certainly hate him, for he does not prophesy good things concerning me but bad—Mi·caiʹah^&#42;1^ the son of Imʹlah.” However, Je·hoshʹa·phat said: “Do not let the king say a thing like that.”

[NOTE]
====
. Meaning “Who Is Like Jehovah?” Heb., Mi·khaiʹhu.
====

[[v11-22-9]]

^<<v11-22-9,9>>^ Accordingly the king of Israel called a certain court official and said: “Do bring Mi·caiʹah the son of Imʹlah quickly.”

[[v11-22-10]]

^<<v11-22-10,10>>^ Now the king of Israel and Je·hoshʹa·phat the king of Judah were sitting each one on his throne, clothed in garments, in the threshing floor at the entrance of the gate of Sa·marʹi·a; and all the prophets were acting as prophets before them.

[[v11-22-11]]

^<<v11-22-11,11>>^ Then Zed·e·kiʹah the son of Che·naʹa·nah made for himself horns of iron and said: “This is what Jehovah has said, ‘With these you will push the Syrians until you exterminate them.’”

[[v11-22-12]]

^<<v11-22-12,12>>^ And all the other prophets were prophesying the same as that, saying: “Go up to Raʹmoth-gilʹe·ad and prove successful; and Jehovah will certainly give it into the king’s hand.”

[[v11-22-13]]

^<<v11-22-13,13>>^ And the messenger that had gone to call Mi·caiʹah spoke to him, saying: “Look, now! The words of the prophets are unanimously^&#42;1^ of good to the king. Let your word, please, become like the word of one of them, and you must speak good.”

[NOTE]
====
. Lit., “one mouth.”
====

[[v11-22-14]]

^<<v11-22-14,14>>^ But Mi·caiʹah said: “As Jehovah is living, what Jehovah will say to me, that is what I shall speak.”

[[v11-22-15]]

^<<v11-22-15,15>>^ Then he came in to the king, and the king proceeded to say to him: “Mi·caiʹah, shall we go to Raʹmoth-gilʹe·ad in war, or shall we refrain?” At once he said to him: “Go up and prove successful; and Jehovah will certainly give it into the king’s hand.”

[[v11-22-16]]

^<<v11-22-16,16>>^ At that the king said to him: “For how many times am I putting you under oath that you should not speak to me anything but truth in the name of Jehovah?”

[[v11-22-17]]

^<<v11-22-17,17>>^ So he said: “I certainly see all the Israelites scattered on the mountains, like sheep that have no shepherd. And Jehovah went on to say: ‘These have no masters.^&#42;1^ Let them go back each one to his house in peace.’”

[NOTE]
====
. Or, “lord.” Heb., ʼadho·nimʹ, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v11-22-18]]

^<<v11-22-18,18>>^ Then the king of Israel said to Je·hoshʹa·phat: “Did I not say to you, ‘He will prophesy concerning me, not good things, but bad’?”

[[v11-22-19]]

^<<v11-22-19,19>>^ And he went on to say: “Therefore hear the word of Jehovah: I certainly see Jehovah sitting upon his throne and all the army of the heavens standing by him, to his right and to his left.

[[v11-22-20]]

^<<v11-22-20,20>>^ And Jehovah proceeded to say, ‘Who will fool Aʹhab, that he may go up and fall at Raʹmoth-gilʹe·ad?’ And this one began to say something like this, while that one was saying something like that.

[[v11-22-21]]

^<<v11-22-21,21>>^ Finally a spirit came out and stood before Jehovah and said, ‘I myself shall fool him.’ At that Jehovah said to him, ‘By what means?’

[[v11-22-22]]

^<<v11-22-22,22>>^ To this he said, ‘I shall go forth, and I shall certainly become a deceptive spirit in the mouth of all his prophets.’ So he said, ‘You will fool him, and, what is more, you will come off the winner. Go out and do that way.’

[[v11-22-23]]

^<<v11-22-23,23>>^ And now here Jehovah has put a deceptive spirit into the mouth of all these prophets of yours; but Jehovah himself has spoken calamity concerning you.”

[[v11-22-24]]

^<<v11-22-24,24>>^ Zed·e·kiʹah the son of Che·naʹa·nah now approached and struck Mi·caiʹah upon the cheek and said: “In just which &#91;way&#93; did the spirit of Jehovah pass along from me to speak with you?”

[[v11-22-25]]

^<<v11-22-25,25>>^ At that Mi·caiʹah said: “Look! You are seeing &#91;which way&#93; on that day when you will enter the innermost chamber to hide yourself.”

[[v11-22-26]]

^<<v11-22-26,26>>^ Then the king of Israel said: “Take Mi·caiʹah and turn him back to Aʹmon the chief of the city and to Joʹash the king’s son.

[[v11-22-27]]

^<<v11-22-27,27>>^ And you must say, ‘This is what the king has said: “PUT this fellow in the house of detention and feed him with a reduced allowance of bread and a reduced allowance of water until I come in peace.”’”

[[v11-22-28]]

^<<v11-22-28,28>>^ Upon that Mi·caiʹah said: “If you return at all in peace, Jehovah has not spoken with^&#42;1^ me.” And he added: “Hear, all YOU peoples.”

[NOTE]
====
. Or, “spoken by.” Compare Nu 12:8a.
====

[[v11-22-29]]

^<<v11-22-29,29>>^ And the king of Israel and Je·hoshʹa·phat the king of Judah proceeded to go up to Raʹmoth-gilʹe·ad.

[[v11-22-30]]

^<<v11-22-30,30>>^ The king of Israel now said to Je·hoshʹa·phat: “There will be a disguising and entering^&#42;1^ into the battle &#91;for me&#93;, but you, for your part, put on your garments.” Accordingly, the king of Israel disguised himself and entered into the battle.

[NOTE]
====
. “There will be a disguising and entering.” In Heb. these are verbs in the infinitive absolute, indefinite as to time and impersonal. TLXXSy, “I shall completely cover myself and enter”; Vg, “Take armor and enter.”
====

[[v11-22-31]]

^<<v11-22-31,31>>^ As for the king of Syria, he had commanded the thirty-two chiefs of the chariots that were his, saying: “YOU must fight, neither with the small nor the great, but with the king of Israel alone.”

[[v11-22-32]]

^<<v11-22-32,32>>^ And it came about that, as soon as the chiefs of the chariots saw Je·hoshʹa·phat, they, for their part, said to themselves: “Surely it is the king of Israel.” So they turned aside against him to fight; and Je·hoshʹa·phat began to cry for aid.

[[v11-22-33]]

^<<v11-22-33,33>>^ And it came about that, as soon as the chiefs of the chariots saw that it was not the king of Israel, they immediately came back from following him.

[[v11-22-34]]

^<<v11-22-34,34>>^ And there was a man that bent the bow in his innocence, but he got to strike the king of Israel between the appendages and the coat of mail, so that he said to his charioteer: “Turn your hand around, and take me out from the camp, because I have been badly wounded.”

[[v11-22-35]]

^<<v11-22-35,35>>^ And the battle kept rising in intensity on that day, and the king himself had to be kept in a standing position in the chariot facing the Syrians, and gradually he died in the evening; and the blood of the wound kept pouring out upon the interior of the war chariot.

[[v11-22-36]]

^<<v11-22-36,36>>^ And the ringing cry^&#42;1^ began to pass through the camp about the setting of the sun, saying: “Everyone to his city, and everyone to his land!”

[NOTE]
====
. Or, “And the herald,” in agreement with LXX.
====

[[v11-22-37]]

^<<v11-22-37,37>>^ Thus the king died. When he was brought^&#42;1^ to Sa·marʹi·a, then they buried the king in Sa·marʹi·a.

[NOTE]
====
. “He was brought,” Vg; MSy, “he came”; LXX, “they came.”
====

[[v11-22-38]]

^<<v11-22-38,38>>^ And they began to wash off the war chariot by the pool of Sa·marʹi·a, and the dogs went licking up his blood (and the prostitutes themselves bathed there), according to Jehovah’s word that he had spoken.

[[v11-22-39]]

^<<v11-22-39,39>>^ As for the rest of the affairs of Aʹhab and all that he did and the house of ivory that he built and all the cities that he built, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Finally Aʹhab lay down with his forefathers; and A·ha·ziʹah^&#42;1^ his son began to reign in place of him.

[NOTE]
====
. Meaning “Jehovah Has Taken Hold.” Heb., ʼAchaz·yaʹhu.
====

[[v11-22-41]]

^<<v11-22-41,41>>^ As for Je·hoshʹa·phat the son of Aʹsa, he had become king over Judah in the fourth year of Aʹhab the king of Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Je·hoshʹa·phat was thirty-five years old when he began to reign, and for twenty-five years he reigned in Jerusalem; and his mother’s name was A·zuʹbah the daughter of Shilʹhi.

[[v11-22-43]]

^<<v11-22-43,43>>^ And he kept walking in all the way of Aʹsa his father. He did not turn aside from it, by doing what was right in the eyes of Jehovah. Only the high places themselves did not disappear.^&#42;1^ The people were still sacrificing and making sacrificial smoke on the high places.

[NOTE]
====
. “Did not disappear,” M; LXXSyVg, “he did not remove.”
====

[[v11-22-44]]

^<<v11-22-44,44>>^ And Je·hoshʹa·phat kept peaceful relations with the king of Israel.

[[v11-22-45]]

^<<v11-22-45,45>>^ As for the rest of the affairs of Je·hoshʹa·phat and the mightiness with which he acted and how he warred, are they not written in the book of the affairs of the days of the kings of Judah?

[[v11-22-46]]

^<<v11-22-46,46>>^ And the rest of the male temple prostitutes that had been left over in the days of Aʹsa his father he cleared out from the land.

[[v11-22-47]]

^<<v11-22-47,47>>^ As regards a king, there was none in Eʹdom; a deputy was king.

[[v11-22-48]]

^<<v11-22-48,48>>^ Je·hoshʹa·phat, for his part, made Tarʹshish ships to go to Oʹphir for gold; but they did not go, because the ships were wrecked at Eʹzi·on-geʹber.

[[v11-22-49]]

^<<v11-22-49,49>>^ It was then that A·ha·ziʹah the son of Aʹhab said to Je·hoshʹa·phat: “Let my servants go with your servants in the ships,” but Je·hoshʹa·phat did not consent.

[[v11-22-50]]

^<<v11-22-50,50>>^ Finally Je·hoshʹa·phat lay down with his forefathers and was buried with his forefathers in the City of David his forefather; and Je·hoʹram his son began to reign in place of him.

[[v11-22-51]]

^<<v11-22-51,51>>^ As for A·ha·ziʹah the son of Aʹhab, he became king over Israel in Sa·marʹi·a in the seventeenth year of Je·hoshʹa·phat the king of Judah, and he continued to reign over Israel for two years.

[[v11-22-52]]

^<<v11-22-52,52>>^ And he kept doing what was bad in Jehovah’s eyes and went walking in the way of his father and in the way of his mother and in the way of Jer·o·boʹam the son of Neʹbat, who had caused Israel to sin.

[[v11-22-53]]

^<<v11-22-53,53>>^ And he continued serving Baʹal and bowing down to him and kept offending Jehovah the God of Israel according to all that his father had done.

'''

xref:011-1-kings/011-1-kings-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-kings/012-2-kings-001.adoc#v12-1-0[Próximo Capítulo &#62;]