include::./index.adoc[]

[[v11-3-0]]
=== The First of Kings, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-3-1]]

^<<v11-3-1,1>>^ And Solʹo·mon proceeded to form a marriage alliance with Pharʹaoh the king of Egypt and to take Pharʹaoh’s daughter and bring her to the City of David, until he finished building his own house and the house of Jehovah and Jerusalem’s wall all around.

[[v11-3-2]]

^<<v11-3-2,2>>^ Only the people were sacrificing on the high places, for a house had not been built to the name of Jehovah down to those days.

[[v11-3-3]]

^<<v11-3-3,3>>^ And Solʹo·mon continued to love Jehovah by walking in the statutes of David his father. Only it was on the high places that he was regularly sacrificing and making offerings smoke.

[[v11-3-4]]

^<<v11-3-4,4>>^ Accordingly the king went to Gibʹe·on to sacrifice there, for that was the great high place. A thousand burnt sacrifices Solʹo·mon proceeded to offer upon that altar.

[[v11-3-5]]

^<<v11-3-5,5>>^ In Gibʹe·on Jehovah appeared to Solʹo·mon in a dream by night; and God^&#42;1^ proceeded to say: “Request what I should give you.”

[NOTE]
====
. “God,” MSy; TLXX, “Jehovah.”
====

[[v11-3-6]]

^<<v11-3-6,6>>^ At this Solʹo·mon said: “You yourself have exercised great loving-kindness^&#42;1^ toward your servant David my father according as he walked before you in truth and in righteousness and in uprightness of heart with you; and you continued keeping toward him this great loving-kindness, so that you gave him a son to sit^&#42;2^ upon his throne as at this day.

[NOTE]
====
. Or, “loyal love.”
. Lit., “a son sitting.”
====

[[v11-3-7]]

^<<v11-3-7,7>>^ And now, Jehovah my God, you yourself have made your servant king in the place of David my father, and I am but a little boy. I do not know how to go out and how to come in.

[[v11-3-8]]

^<<v11-3-8,8>>^ And your servant is in the middle of your people whom you have chosen, a multitudinous people that cannot be numbered or counted for multitude.

[[v11-3-9]]

^<<v11-3-9,9>>^ And you must give to your servant an obedient heart^&#42;1^ to judge your people, to discern between good and bad; for who is able to judge this difficult^&#42;2^ people of yours?”

[NOTE]
====
. Lit., “a hearing heart.”
. Or, “numerous.” Lit., “heavy.”
====

[[v11-3-10]]

^<<v11-3-10,10>>^ And the thing was pleasing^&#42;1^ in the eyes of Jehovah,^&#42;2^ because Solʹo·mon had requested this thing.

[NOTE]
====
. Or, “good.”
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v11-3-11]]

^<<v11-3-11,11>>^ And God^&#42;1^ went on to say to him: “For the reason that you have requested this thing and have not requested for yourself many days nor requested for yourself riches nor requested the soul^&#42;2^ of your enemies, and you have requested for yourself understanding^&#42;3^ to hear judicial cases,^&#42;4^

[NOTE]
====
. “God,” MVg; LXXSyVgc, “Jehovah.”
. Or, “life.” Heb., neʹphesh; Gr., psy·khasʹ, pl.; Vgc(Lat.), aʹni·mas, pl.
. Or, “discernment.”
. Or, “to obey judgment.”
====

[[v11-3-12]]

^<<v11-3-12,12>>^ look! I shall certainly do according to your words. Look! I shall certainly give you a wise and understanding^&#42;1^ heart, so that one like you there has not happened to be before you, and after you there will not rise up one like you.

[NOTE]
====
. Or, “discerning.”
====

[[v11-3-13]]

^<<v11-3-13,13>>^ And also what you have not requested I will give you, both riches and glory, so that there will not have happened to be any among the kings like you, all your days.

[[v11-3-14]]

^<<v11-3-14,14>>^ And if you will walk in my ways by keeping my regulations and my commandments, just as David your father walked, I will also lengthen your days.”

[[v11-3-15]]

^<<v11-3-15,15>>^ When Solʹo·mon awoke, why, here it had been a dream. Then he came to Jerusalem and stood before the ark of the covenant of Jehovah^&#42;1^ and offered up burnt sacrifices and rendered up communion offerings and spread a feast for all his servants.

[NOTE]
====
. See vs 10 ftn, “Jehovah.”
====

[[v11-3-16]]

^<<v11-3-16,16>>^ At that time two women, prostitutes, got to come in to the king and stand before him.

[[v11-3-17]]

^<<v11-3-17,17>>^ Then the one woman said: “Excuse me, my lord, I and this woman are dwelling in one house, so that I gave birth close by her in the house.

[[v11-3-18]]

^<<v11-3-18,18>>^ And it came about on the third day after I gave birth, this woman also proceeded to give birth. And we were together. There was no stranger with us in the house, no one but the two of us in the house.

[[v11-3-19]]

^<<v11-3-19,19>>^ Later the son of this woman died at night, because she lay upon him.

[[v11-3-20]]

^<<v11-3-20,20>>^ So she got up in the middle of the night and took my son from beside me while your slave girl herself was asleep and laid him in her own bosom, and her dead son she laid in my bosom.

[[v11-3-21]]

^<<v11-3-21,21>>^ When I got up in the morning to nurse my son, why, there he was dead. So I examined him closely in the morning, and, look! he did not prove to be my son that I had borne.”

[[v11-3-22]]

^<<v11-3-22,22>>^ But the other woman said: “No, but my son is the living one and your son is the dead one!” All the while this woman was saying: “No, but your son is the dead one and my son is the living one.” And they kept on speaking before the king.

[[v11-3-23]]

^<<v11-3-23,23>>^ Finally the king said: “This one is saying, ‘This is my son, the living one, and your son is the dead one!’ and that one is saying, ‘No, but your son is the dead one and my son is the living one!’”

[[v11-3-24]]

^<<v11-3-24,24>>^ And the king went on to say: “YOU men, get me a sword.” So they brought the sword before the king.

[[v11-3-25]]

^<<v11-3-25,25>>^ And the king proceeded to say: “YOU men, sever the living child in two and give the one half to the one woman and the other half to the other.”

[[v11-3-26]]

^<<v11-3-26,26>>^ At once the woman whose son was the living one said to the king (for her inward emotions were excited toward her son, so that she said): “Excuse me, my lord! YOU men, give her the living child. Do not by any means put him to death.” All the while this other woman was saying: “Neither mine nor yours will he become. YOU men, do the severing!”

[[v11-3-27]]

^<<v11-3-27,27>>^ At that the king answered and said: “YOU men, give her the living child, and YOU must by no means put him to death. She is his mother.”

[[v11-3-28]]

^<<v11-3-28,28>>^ And all Israel got to hear of the judicial decision that the king had handed down; and they became fearful because of the king, for they saw that the wisdom of God was within him to execute judicial decision.

'''

xref:011-1-kings/011-1-kings-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-kings/011-1-kings-004.adoc#v11-4-0[Próximo Capítulo &#62;]