include::./index.adoc[]

[[v11-15-0]]
=== The First of Kings, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-15-1]]

^<<v11-15-1,1>>^ And in the eighteenth year of King Jer·o·boʹam the son of Neʹbat, A·biʹjam became king over Judah.

[[v11-15-2]]

^<<v11-15-2,2>>^ Three years he reigned in Jerusalem; and his mother’s name was Maʹa·cah the granddaughter^&#42;1^ of A·bishʹa·lom.^&#42;2^

[NOTE]
====
. Lit., “daughter.” Heb., bath. See 2Ch 13:1, 2.
. “Absalom” in 2Ch 11:20, 21.
====

[[v11-15-3]]

^<<v11-15-3,3>>^ And he went on walking in all the sins of his father that he did prior to him; and his heart did not prove to be complete with Jehovah his God, like the heart of David his forefather.

[[v11-15-4]]

^<<v11-15-4,4>>^ For, on account of David, Jehovah his God gave him a lamp in Jerusalem by raising his son up after him and keeping Jerusalem in existence,^&#42;1^

[NOTE]
====
. Lit., “making Jerusalem stand.” Compare Ex 9:16.
====

[[v11-15-5]]

^<<v11-15-5,5>>^ because David did what was right in the eyes of Jehovah, and he did not turn aside from anything that He had commanded him all the days of his life, only in the matter of U·riʹah the Hitʹtite.

[[v11-15-6]]

^<<v11-15-6,6>>^ And warfare itself took place between Re·ho·boʹam^&#42;1^ and Jer·o·boʹam all the days of his life.

[NOTE]
====
. “Rehoboam,” MVg; 12 Heb. mss, “Abijam (Abijah)”; Sy, “Abija the son of Rehoboam.”
====

[[v11-15-7]]

^<<v11-15-7,7>>^ As for the rest of the affairs of A·biʹjam and all that he did, are they not written in the book of the affairs of the days of the kings of Judah? There was warfare also that took place between A·biʹjam and Jer·o·boʹam.

[[v11-15-8]]

^<<v11-15-8,8>>^ Finally A·biʹjam lay down with his forefathers and they buried him in the City of David; and Aʹsa his son began to reign in place of him.

[[v11-15-9]]

^<<v11-15-9,9>>^ In the twentieth year of Jer·o·boʹam the king of Israel, Aʹsa reigned as king of Judah.

[[v11-15-10]]

^<<v11-15-10,10>>^ And forty-one years he reigned in Jerusalem; and his grandmother’s^&#42;1^ name was Maʹa·cah the granddaughter of A·bishʹa·lom.

[NOTE]
====
. Lit., “his mother’s.” Heb., ʼim·mohʹ.
====

[[v11-15-11]]

^<<v11-15-11,11>>^ And Aʹsa proceeded to do what was right in the eyes of Jehovah, like David his forefather.

[[v11-15-12]]

^<<v11-15-12,12>>^ Accordingly he had the male temple prostitutes pass out of the land and removed all the dungy idols that his forefathers had made.

[[v11-15-13]]

^<<v11-15-13,13>>^ As for even Maʹa·cah his grandmother, he went on to remove her from &#91;being&#93; lady, because she had made a horrible idol to the sacred pole; after which Aʹsa cut down her horrible idol and burned it at the torrent valley of Kidʹron.

[[v11-15-14]]

^<<v11-15-14,14>>^ And the high places he did not remove. Nevertheless, Aʹsa’s heart itself proved to be complete with Jehovah all his days.

[[v11-15-15]]

^<<v11-15-15,15>>^ And he began to bring in the things made holy by his father and the things made holy by himself into the house of Jehovah, silver and gold and articles.

[[v11-15-16]]

^<<v11-15-16,16>>^ And warfare itself took place between Aʹsa and Baʹa·sha the king of Israel all their days.

[[v11-15-17]]

^<<v11-15-17,17>>^ So Baʹa·sha the king of Israel came up against Judah and began to build Raʹmah, to allow no one to go out or come in to Aʹsa the king of Judah.

[[v11-15-18]]

^<<v11-15-18,18>>^ At that Aʹsa took all the silver and the gold that were left in the treasures of the house of Jehovah and the treasures of the house of the king and put them in the hand of his servants; and King Aʹsa now sent them to Ben-haʹdad the son of Tab·rimʹmon the son of Heʹzi·on, the king of Syria, who was dwelling in Damascus, saying:

[[v11-15-19]]

^<<v11-15-19,19>>^ “There is a covenant between me and you, between my father and your father. Here I have sent you a present of silver and gold. Come, do break your covenant with Baʹa·sha the king of Israel, that he may withdraw from me.”

[[v11-15-20]]

^<<v11-15-20,20>>^ Accordingly Ben-haʹdad listened to King Aʹsa and sent the chiefs of the military forces that were his against the cities of Israel and went striking down Iʹjon and Dan and Aʹbel-beth-maʹa·cah and all Chinʹne·reth, as far as all the land of Naphʹta·li.

[[v11-15-21]]

^<<v11-15-21,21>>^ And it came about that as soon as Baʹa·sha heard of it, he immediately quit building Raʹmah and continued dwelling in Tirʹzah.

[[v11-15-22]]

^<<v11-15-22,22>>^ And King Aʹsa, for his part, summoned all Judah—there was none exempt—and they proceeded to carry the stones of Raʹmah and the timbers of it, with which Baʹa·sha had been building; and King Aʹsa began to build with them Geʹba in Benjamin, and Mizʹpah.

[[v11-15-23]]

^<<v11-15-23,23>>^ As for the rest of all the affairs of Aʹsa and all his mightiness and all that he did and the cities that he built, are they not written in the book of the affairs of the days of the kings of Judah? Only at the time of his growing old he got diseased in his feet.

[[v11-15-24]]

^<<v11-15-24,24>>^ Finally Aʹsa lay down with his forefathers and was buried with his forefathers in the City of David his forefather; and Je·hoshʹa·phat his son began to reign in place of him.

[[v11-15-25]]

^<<v11-15-25,25>>^ As for Naʹdab the son of Jer·o·boʹam, he became king over Israel in the second year of Aʹsa the king of Judah; and he continued to reign over Israel two years.

[[v11-15-26]]

^<<v11-15-26,26>>^ And he kept doing what was bad in the eyes of Jehovah and went on walking in the way of his father and in his sin with which he caused Israel to sin.

[[v11-15-27]]

^<<v11-15-27,27>>^ And Baʹa·sha the son of A·hiʹjah of the house of Isʹsa·char began to conspire against him; and Baʹa·sha got to strike him down at Gibʹbe·thon, which belonged to the Phi·lisʹtines, while Naʹdab and all Israel were besieging Gibʹbe·thon.

[[v11-15-28]]

^<<v11-15-28,28>>^ So Baʹa·sha put him to death in the third year of Aʹsa the king of Judah and began to reign in place of him.

[[v11-15-29]]

^<<v11-15-29,29>>^ And it came about that as soon as he became king, he struck down all the house of Jer·o·boʹam. He did not let anyone breathing^&#42;1^ remain of Jer·o·boʹam’s until he had annihilated them, according to Jehovah’s word that he had spoken by means of his servant A·hiʹjah the Shiʹlo·nite,

[NOTE]
====
. Lit., “every breath,” MLXX.
====

[[v11-15-30]]

^<<v11-15-30,30>>^ on account of the sins of Jer·o·boʹam with which he sinned and with which he caused Israel to sin &#91;and&#93; by his offensiveness with which he offended Jehovah the God of Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ As for the rest of the affairs of Naʹdab and all that he did, are they not written in the book of the affairs of the days of the kings of Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ And warfare itself took place between Aʹsa and Baʹa·sha the king of Israel all their days.

[[v11-15-33]]

^<<v11-15-33,33>>^ In the third year of Aʹsa the king of Judah, Baʹa·sha the son of A·hiʹjah became king over all Israel in Tirʹzah for twenty-four years.

[[v11-15-34]]

^<<v11-15-34,34>>^ And he kept doing what was bad in the eyes of Jehovah and went walking in the way of Jer·o·boʹam and in his sin with which he caused Israel to sin.

'''

xref:011-1-kings/011-1-kings-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-kings/011-1-kings-016.adoc#v11-16-0[Próximo Capítulo &#62;]