include::./index.adoc[]

[[v11-14-0]]
=== The First of Kings, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-14-1]]

^<<v11-14-1,1>>^ At that particular time A·biʹjah the son of Jer·o·boʹam fell sick.

[[v11-14-2]]

^<<v11-14-2,2>>^ So Jer·o·boʹam said to his wife: “Rise up, please, and you must disguise yourself that they may not know that you are the wife of Jer·o·boʹam, and you must go to Shiʹloh. Look! There is where A·hiʹjah the prophet is. He is the one that spoke with reference to me as to becoming king^&#42;1^ over this people.

[NOTE]
====
. “As to becoming king,” LXXASyVg; M, “as king.”
====

[[v11-14-3]]

^<<v11-14-3,3>>^ And you must take in your hand ten loaves of bread and sprinkled cakes and a flask of honey, and you must come in to him. He it is that will certainly tell you what is going to happen to the boy.”

[[v11-14-4]]

^<<v11-14-4,4>>^ And the wife of Jer·o·boʹam proceeded to do so. Consequently she rose up and went to Shiʹloh and came to the house of A·hiʹjah. Now A·hiʹjah^&#42;1^ himself was unable to see, for his eyes had set because of his age.

[NOTE]
====
. “Now Ahijah.” Heb., wa·ʼAchi·yaʹhu.
====

[[v11-14-5]]

^<<v11-14-5,5>>^ And Jehovah himself had said to A·hiʹjah: “Here is the wife of Jer·o·boʹam coming to apply for a word from you regarding her son; for he is sick. This way and that is how you should speak to her. And it will occur^&#42;1^ that as soon as she arrives, she will be making herself unrecognizable.”

[NOTE]
====
. Or, “And let it occur.”
====

[[v11-14-6]]

^<<v11-14-6,6>>^ And it came about that as soon as A·hiʹjah heard the sound of her feet as she was coming into the entrance, he began to say: “Come in, you wife of Jer·o·boʹam. Why is it that you are making yourself unrecognizable while I am being sent to you with a severe message?

[[v11-14-7]]

^<<v11-14-7,7>>^ Go, say to Jer·o·boʹam, ‘This is what Jehovah the God of Israel has said: “For the reason that I raised you up out of the middle of your people, that I might constitute you a leader over my people Israel,

[[v11-14-8]]

^<<v11-14-8,8>>^ and I went on to rip the kingdom away from the house of David and give it to you, and you have not become like my servant David, who kept my commandments and who walked after me with all his heart by doing only what was right in my eyes,

[[v11-14-9]]

^<<v11-14-9,9>>^ but you began to act worse than all those who happened to be prior to you, and you went and made for yourself another god^&#42;1^ and molten images to offend me, and it is I whom you have cast behind your back;

[NOTE]
====
. Lit., “other gods.” Heb., ʼelo·himʹ ʼache·rimʹ. Compare 12:28 ftn, “God.”
====

[[v11-14-10]]

^<<v11-14-10,10>>^ for that reason here I am bringing calamity upon the house of Jer·o·boʹam, and I shall certainly cut off from Jer·o·boʹam anyone urinating against a wall,^&#42;1^ a helpless and worthless one in Israel;^&#42;2^ and I shall indeed make a clean sweep behind the house of Jer·o·boʹam, just as one clears away the dung until it is disposed of.

[NOTE]
====
. “Urinating against a wall.” A Heb. idiom for males.
. Lit., “one restrained and one let go (abandoned) in Israel.” See De 32:36 ftn, “One.”
====

[[v11-14-11]]

^<<v11-14-11,11>>^ The one dying of Jer·o·boʹam’s in the city, the dogs will eat; and the one dying in the field, the fowls of the heavens will eat, because Jehovah himself has spoken it.”’

[[v11-14-12]]

^<<v11-14-12,12>>^ “And you yourself, rise up, go to your house. When your feet come into the city the child will certainly die.

[[v11-14-13]]

^<<v11-14-13,13>>^ And all Israel will indeed bewail him and bury him, because this one alone of Jer·o·boʹam’s will come into a burial place; for the reason that something good toward Jehovah the God of Israel has been found in him in the house of Jer·o·boʹam.

[[v11-14-14]]

^<<v11-14-14,14>>^ And Jehovah will certainly raise up to himself a king over Israel who will cut off the house of Jer·o·boʹam the said day, and what if right now?

[[v11-14-15]]

^<<v11-14-15,15>>^ And Jehovah will indeed strike Israel down, just as the reed sways in the water; and he will certainly uproot Israel off this good ground that he gave to their forefathers, and he will indeed scatter them beyond the River,^&#42;1^ for the reason that they made their sacred poles, so offending Jehovah.

[NOTE]
====
. That is, the Euphrates.
====

[[v11-14-16]]

^<<v11-14-16,16>>^ And he will give Israel up on account of the sins of Jer·o·boʹam with which he sinned and with which he caused Israel to sin.”

[[v11-14-17]]

^<<v11-14-17,17>>^ At that Jer·o·boʹam’s wife rose up and went her way and came to Tirʹzah. As she was arriving at the threshold of the house, the boy himself died.

[[v11-14-18]]

^<<v11-14-18,18>>^ So they buried him, and all Israel went wailing for him, according to Jehovah’s word that he had spoken by means of his servant A·hiʹjah the prophet.

[[v11-14-19]]

^<<v11-14-19,19>>^ And the rest of the affairs of Jer·o·boʹam, how he warred and how he reigned, there they are written in the book of the affairs of the days of the kings of Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ And the days that Jer·o·boʹam reigned were twenty-two years, after which he lay down with his forefathers; and Naʹdab his son began to reign in place of him.

[[v11-14-21]]

^<<v11-14-21,21>>^ As for Re·ho·boʹam the son of Solʹo·mon, he had become king in Judah. Forty-one years old Re·ho·boʹam was when he began to reign, and seventeen years he reigned in Jerusalem, the city that Jehovah had chosen out of all the tribes of Israel to put his name there. And his mother’s name was Naʹa·mah the Amʹmon·it·ess.

[[v11-14-22]]

^<<v11-14-22,22>>^ And Judah went on doing what was bad in the eyes of Jehovah, so that they incited him to jealousy more than all that their forefathers had done by their sins with which they sinned.

[[v11-14-23]]

^<<v11-14-23,23>>^ And they too kept building for themselves high places and sacred pillars and sacred poles upon every high hill and under every luxuriant tree.

[[v11-14-24]]

^<<v11-14-24,24>>^ And even the male temple prostitute^&#42;1^ proved to be in the land. They acted according to all the detestable things of the nations whom Jehovah had driven out from before the sons of Israel.

[NOTE]
====
. “Male temple prostitute.” Heb., qa·dheshʹ; Lat., ef·fe·mi·naʹti, “effeminate men.”
====

[[v11-14-25]]

^<<v11-14-25,25>>^ And it came about in the fifth year of King Re·ho·boʹam that Shiʹshak the king of Egypt came up against Jerusalem.

[[v11-14-26]]

^<<v11-14-26,26>>^ And he got to take the treasures of the house of Jehovah and the treasures of the house of the king; and everything he took. And he went on to take all the gold shields that Solʹo·mon had made.

[[v11-14-27]]

^<<v11-14-27,27>>^ Consequently King Re·ho·boʹam made in place of them copper shields, and he committed them to the control of the chiefs of the runners, the guards of the entrance of the king’s house.

[[v11-14-28]]

^<<v11-14-28,28>>^ And it would occur that as often as the king came to the house of Jehovah, the runners would carry them, and they returned them to the guard chamber of the runners.

[[v11-14-29]]

^<<v11-14-29,29>>^ And the rest of the affairs of Re·ho·boʹam and all that he did, are they not written in the book of the affairs of the times of the kings of Judah?

[[v11-14-30]]

^<<v11-14-30,30>>^ And warfare itself took place between Re·ho·boʹam and Jer·o·boʹam always.

[[v11-14-31]]

^<<v11-14-31,31>>^ Finally Re·ho·boʹam lay down with his forefathers and was buried with his forefathers in the City of David. And his mother’s name was Naʹa·mah the Amʹmon·it·ess. And A·biʹjam^&#42;1^ his son began to reign in place of him.

[NOTE]
====
. “Abijam,” MVg; about 12 Heb. mss and the Bomberg ed. of the Hebrew Bible (1524–1525 C.E.), by Jacob Ben Hayim, “Abijah.”
====

'''

xref:011-1-kings/011-1-kings-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-kings/011-1-kings-015.adoc#v11-15-0[Próximo Capítulo &#62;]