include::./index.adoc[]

[[v11-9-0]]
=== The First of Kings, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-9-1]]

^<<v11-9-1,1>>^ And it came about that, as soon as Solʹo·mon had finished building the house of Jehovah and the house of the king and every desirable thing of Solʹo·mon that he took delight in making,

[[v11-9-2]]

^<<v11-9-2,2>>^ then Jehovah appeared to Solʹo·mon the second time, the same as he had appeared to him in Gibʹe·on.

[[v11-9-3]]

^<<v11-9-3,3>>^ And Jehovah went on to say to him: “I have heard your prayer and your request for favor with which you requested favor before me. I have sanctified this house that you have built by putting my name there to time indefinite; and my eyes and my heart will certainly prove to be there always.

[[v11-9-4]]

^<<v11-9-4,4>>^ And you, if you will walk before me, just as David your father walked, with integrity of heart and with uprightness by doing according to all that I have commanded you, and you will keep my regulations and my judicial decisions,

[[v11-9-5]]

^<<v11-9-5,5>>^ I also shall indeed establish the throne of your kingdom over Israel to time indefinite,^&#42;1^ just as I promised David your father, saying, ‘Not a man of yours will be cut off from &#91;sitting&#93; upon the throne of Israel.’

[NOTE]
====
. Or, “over Israel forever.”
====

[[v11-9-6]]

^<<v11-9-6,6>>^ If YOU yourselves and YOUR sons should definitely turn back from following me and not keep my commandments and my statutes that I have put before YOU men, and YOU actually go and serve other gods and bow down to them,^&#42;1^

[NOTE]
====
. Or, “and worship them.”
====

[[v11-9-7]]

^<<v11-9-7,7>>^ I will also cut Israel off from upon the surface of the ground that I have given to them; and the house that I have sanctified to my name I shall throw away^&#42;1^ from before me, and Israel will indeed become a proverbial saying and a taunt among all the peoples.

[NOTE]
====
. “Throw away,” TLXXVg and 2Ch 7:20; M, “send away.”
====

[[v11-9-8]]

^<<v11-9-8,8>>^ And this house itself will become heaps of ruins.^&#42;1^ Everyone passing by it will stare in amazement and will certainly whistle and say, ‘For what reason did Jehovah do like that to this land and this house?’

[NOTE]
====
. “Become heaps of ruins,” by a minor correction to agree with SyIt; M, “become most prominent (outstanding; conspicuous).”
====

[[v11-9-9]]

^<<v11-9-9,9>>^ And they will have to say, ‘For the reason that they left Jehovah their God who had brought their forefathers out from the land of Egypt, and they proceeded to take hold of other gods and bow down to them and serve them. That is why Jehovah brought upon them all this calamity.’”

[[v11-9-10]]

^<<v11-9-10,10>>^ And it came about at the end of twenty years, in which Solʹo·mon built the two houses, the house of Jehovah and the house of the king,

[[v11-9-11]]

^<<v11-9-11,11>>^ (Hiʹram the king of Tyre had himself assisted Solʹo·mon with timbers of cedar trees and timbers of juniper trees and with gold as much as he delighted in,) that at that time King Solʹo·mon proceeded to give to Hiʹram twenty cities in the land of Galʹi·lee.^&#42;1^

[NOTE]
====
. Or, “the circuit.” Heb., hag·Ga·lilʹ; Gr., Ga·li·laiʹai; Lat., Ga·li·leʹae. “Galilee” later designated the Roman province north of Samaria.
====

[[v11-9-12]]

^<<v11-9-12,12>>^ Accordingly Hiʹram went out from Tyre to see the cities that Solʹo·mon had given him, and they were not just right in his eyes.

[[v11-9-13]]

^<<v11-9-13,13>>^ So he said: “What sort of cities are these that you have given me, my brother?” And they came to be called the Land of Caʹbul^&#42;1^ down to this day.

[NOTE]
====
. Or, “the Land as Good as Nothing”; perhaps, “the Fettered Land.”
====

[[v11-9-14]]

^<<v11-9-14,14>>^ In the meantime Hiʹram sent to the king a hundred and twenty talents^&#42;1^ of gold.

[NOTE]
====
. See App 8A.
====

[[v11-9-15]]

^<<v11-9-15,15>>^ Now this is the account of those conscripted for forced labor that King Solʹo·mon levied to build the house of Jehovah and his own house and the Mound^&#42;1^ and the wall of Jerusalem and Haʹzor and Me·gidʹdo and Geʹzer.

[NOTE]
====
. “The Mound.” Lit., “the filling [of earth].” Heb., ham·mil·lohʼʹ. Possibly a citadellike structure.
====

[[v11-9-16]]

^<<v11-9-16,16>>^ (Pharʹaoh the king of Egypt himself had come up and then captured Geʹzer and burned it with fire, and the Caʹnaan·ites dwelling in the city he had killed. So he gave it as a parting gift to his daughter, the wife of Solʹo·mon.)

[[v11-9-17]]

^<<v11-9-17,17>>^ And Solʹo·mon went on to build Geʹzer and Lower Beth-hoʹron,

[[v11-9-18]]

^<<v11-9-18,18>>^ and Baʹal·ath and Taʹmar^&#42;1^ in the wilderness, in the land,

[NOTE]
====
. “Tadmor,” MmarginSy (see 2Ch 8:4); Vg, “Palmyra.”
====

[[v11-9-19]]

^<<v11-9-19,19>>^ and all the storage cities that became Solʹo·mon’s and the chariot cities and the cities for the horsemen, and the desirable things of Solʹo·mon that he had desired to build in Jerusalem and in Lebʹa·non and in all the land of his dominion.

[[v11-9-20]]

^<<v11-9-20,20>>^ As for all the people remaining over from the Amʹor·ites, the Hitʹtites, the Perʹiz·zites, the Hiʹvites and the Jebʹu·sites, who were no part of the sons of Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ their sons who had been left over after them in the land whom the sons of Israel had been unable to devote to destruction, Solʹo·mon kept levying them for slavish forced labor until this day.

[[v11-9-22]]

^<<v11-9-22,22>>^ And there were none of the sons of Israel that Solʹo·mon constituted slaves; for they were the warriors and his servants and his princes and his adjutants and chiefs of his charioteers and of his horsemen.

[[v11-9-23]]

^<<v11-9-23,23>>^ These were the chiefs of the deputies who were over the work of Solʹo·mon, five hundred and fifty, the foremen over the people who were active in the work.

[[v11-9-24]]

^<<v11-9-24,24>>^ However, Pharʹaoh’s daughter herself came up out of the City of David to her own house that he had built for her. It was then that he built the Mound.

[[v11-9-25]]

^<<v11-9-25,25>>^ And Solʹo·mon continued three times in the year to offer up burnt sacrifices and communion sacrifices upon the altar that he had built for Jehovah, and there was a making of sacrificial smoke^&#42;1^ on the &#91;altar&#93;, which was before Jehovah; and he completed the house.

[NOTE]
====
. “There was a making of sacrificial smoke.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v11-9-26]]

^<<v11-9-26,26>>^ And there was a fleet of ships that King Solʹo·mon made in Eʹzi·on-geʹber, which is by Eʹloth, upon the shore of the Red Sea in the land of Eʹdom.

[[v11-9-27]]

^<<v11-9-27,27>>^ And Hiʹram kept sending in the fleet of ships his own servants, seamen,^&#42;1^ having a knowledge of the sea, along with the servants of Solʹo·mon.

[NOTE]
====
. Lit., “men of ships.”
====

[[v11-9-28]]

^<<v11-9-28,28>>^ And they proceeded to go to Oʹphir and take from there four hundred and twenty talents^&#42;1^ of gold and bring it in to King Solʹo·mon.

[NOTE]
====
. See App 8A.
====

'''

xref:011-1-kings/011-1-kings-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-kings/011-1-kings-010.adoc#v11-10-0[Próximo Capítulo &#62;]