include::./index.adoc[]

[[v11-13-0]]
=== The First of Kings, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v11-13-1]]

^<<v11-13-1,1>>^ And here there was a man of God^&#42;1^ that had come out of Judah by the word of Jehovah to Bethʹel, while Jer·o·boʹam was standing by the altar to make sacrificial smoke.

[NOTE]
====
. “A man of God.” Heb., ʼish ʼElo·himʹ, without the definite article ha. Compare vs 4 ftn.
====

[[v11-13-2]]

^<<v11-13-2,2>>^ Then he called out against the altar by the word of Jehovah and said: “O altar, altar, this is what Jehovah has said, ‘Look! A son born to the house of David, whose name is Jo·siʹah! And he will certainly sacrifice upon you the priests of the high places that are making sacrificial smoke upon you, and men’s bones he^&#42;1^ will burn upon you.’”

[NOTE]
====
. “He,” LXXSyVg; M, “they.”
====

[[v11-13-3]]

^<<v11-13-3,3>>^ And he gave a portent on that day, saying: “This is the portent of which Jehovah has spoken: Look! The altar is ripped apart, and the fatty ashes that are upon it will certainly be spilled out.”

[[v11-13-4]]

^<<v11-13-4,4>>^ And it came about that, as soon as the king heard the word of the man of the &#91;true&#93; God^&#42;1^ that he had called out against the altar in Bethʹel, Jer·o·boʹam at once thrust out his hand from off the altar, saying: “YOU men, grab hold of him!” Immediately his hand that he had thrust out against him became dried up, and he was not able to draw it back to himself.

[NOTE]
====
. “The man of the [true] God.” Heb., ʼish-ha·ʼElo·himʹ.
====

[[v11-13-5]]

^<<v11-13-5,5>>^ And the altar itself was ripped apart so that the fatty ashes were spilled out from the altar, according to the portent that the man of the &#91;true&#93; God had given by the word of Jehovah.

[[v11-13-6]]

^<<v11-13-6,6>>^ The king now answered and said to the man of the &#91;true&#93; God: “Soften, please, the face of Jehovah your God and pray in my behalf that my hand may be restored to me.” At this the man of the &#91;true&#93; God softened the face of Jehovah, so that the king’s hand was restored to him, and it came to be as at first.

[[v11-13-7]]

^<<v11-13-7,7>>^ And the king went on to say to the man of the &#91;true&#93; God: “Do come with me to the house and take sustenance, and let me give you a gift.”

[[v11-13-8]]

^<<v11-13-8,8>>^ But the man of the &#91;true&#93; God said to the king: “If you gave me half of your house I would not come with you and eat bread or drink water in this place.

[[v11-13-9]]

^<<v11-13-9,9>>^ For that is the way he commanded me by the word of Jehovah, saying, ‘You must not eat bread or drink water, and you must not return by the way that you went.’”

[[v11-13-10]]

^<<v11-13-10,10>>^ And he began to go by another way, and he did not return by the way by which he had come to Bethʹel.

[[v11-13-11]]

^<<v11-13-11,11>>^ And a certain old prophet was dwelling in Bethʹel, and his sons^&#42;1^ now came in and related to him all the work that the man of the &#91;true&#93; God had done that day in Bethʹel &#91;and&#93; the words that he had spoken to the king, and they went on relating them to their father.

[NOTE]
====
. “Sons,” LXXSyItVgc; MVg, “son.”
====

[[v11-13-12]]

^<<v11-13-12,12>>^ Then their father spoke to them: “Which way, then, did he go?” So his sons showed him the way that the man of the &#91;true&#93; God that had come out of Judah had gone.

[[v11-13-13]]

^<<v11-13-13,13>>^ He now said to his sons: “Saddle the ass for me.” Accordingly they saddled the ass for him, and he went riding on it.

[[v11-13-14]]

^<<v11-13-14,14>>^ And he went following the man of the &#91;true&#93; God and got to find him sitting under the big tree. Then he said to him: “Are you the man of the &#91;true&#93; God who has come out of Judah?” to which he said: “I am.”

[[v11-13-15]]

^<<v11-13-15,15>>^ And he went on to say to him: “Go with me to the house and eat bread.”

[[v11-13-16]]

^<<v11-13-16,16>>^ But he said: “I am not able to go back with you or to come in with you, and I may not eat bread or drink water with you in this place.

[[v11-13-17]]

^<<v11-13-17,17>>^ For it has been spoken to me by the word of Jehovah, ‘You must not eat bread or drink water there. You must not go back again by the way by which you went.’”

[[v11-13-18]]

^<<v11-13-18,18>>^ At this he said to him: “I too am a prophet like you, and an angel himself spoke to me by the word of Jehovah, saying, ‘Have him come back with you to your house that he may eat bread and drink water.’” (He deceived him.)

[[v11-13-19]]

^<<v11-13-19,19>>^ So he went back with him that he might eat bread in his house and drink water.

[[v11-13-20]]

^<<v11-13-20,20>>^ And it came about, while they were sitting at the table, that the word of Jehovah came to the prophet that had brought him back;

[[v11-13-21]]

^<<v11-13-21,21>>^ and he began to call out to the man of the &#91;true&#93; God that had come out of Judah, saying: “This is what Jehovah has said, ‘For the reason that you rebelled against the order of Jehovah and did not keep the commandment with which Jehovah your God commanded you,

[[v11-13-22]]

^<<v11-13-22,22>>^ but you went back that you might eat bread and drink water in the place about which he spoke to you: “Do not eat bread or drink water,” your dead body will not come into the burial place of your forefathers.’”

[[v11-13-23]]

^<<v11-13-23,23>>^ And it came about after his eating bread and after his drinking that he at once saddled for him the ass, that is, for the prophet whom he had brought back.

[[v11-13-24]]

^<<v11-13-24,24>>^ And he got on his way. Later a lion found him on the road and put him to death, and his dead body came to be thrown onto the road. And the ass was standing beside it, and the lion was standing beside the dead body.

[[v11-13-25]]

^<<v11-13-25,25>>^ And here there were men passing by, so that they got to see the dead body thrown onto the road and the lion standing beside the dead body. Then they came in and spoke of it in the city in which the old prophet was dwelling.

[[v11-13-26]]

^<<v11-13-26,26>>^ When the prophet that had brought him back from the way heard of it, he immediately said: “It is the man of the &#91;true&#93; God that rebelled against the order of Jehovah; and so Jehovah gave him to the lion, that he might crush him and put him to death, according to the word of Jehovah that he spoke to him.”

[[v11-13-27]]

^<<v11-13-27,27>>^ And he went on to speak to his sons, saying: “Saddle the ass for me.” So they saddled it.

[[v11-13-28]]

^<<v11-13-28,28>>^ Then he got on his way and found the dead body of him thrown onto the road with the ass and the lion standing beside the dead body. The lion had not eaten the dead body, nor had it crushed the ass.

[[v11-13-29]]

^<<v11-13-29,29>>^ And the prophet proceeded to lift up the dead body of the man of the &#91;true&#93; God and to deposit him upon the ass and to bring him back. Thus he came into the city of the old prophet to bewail and bury him.

[[v11-13-30]]

^<<v11-13-30,30>>^ Accordingly he deposited his dead body in his own burial place; and they kept wailing over him: “Too bad, my brother!”

[[v11-13-31]]

^<<v11-13-31,31>>^ And it came about after his burying him that he went on to say to his sons: “When I die YOU must bury me in the burial place in which the man of the &#91;true&#93; God is buried. Beside his bones deposit my own bones.^&#42;1^

[NOTE]
====
. “Deposit me that my bones may be saved along with his bones,” LXX.
====

[[v11-13-32]]

^<<v11-13-32,32>>^ For without fail the word that he called out by the word of Jehovah against the altar that is in Bethʹel and against all the houses of the high places that are in the cities of Sa·marʹi·a will take place.”

[[v11-13-33]]

^<<v11-13-33,33>>^ After this thing Jer·o·boʹam did not turn back from his bad way, but he again went making priests of high places from the people in general. As for anyone delighting in it, he would fill his hand with power,^&#42;1^ &#91;saying&#93;: “And let him become &#91;one of the&#93; priests^&#42;2^ of high places.”

[NOTE]
====
. Or, “he would install him.”
. “[One of the] priests,” M; LXXSyItVg, “a priest.”
====

[[v11-13-34]]

^<<v11-13-34,34>>^ And in this thing there came to be a cause of sin on the part of the household of Jer·o·boʹam and an occasion for effacing them and annihilating them off the surface of the ground.

'''

xref:011-1-kings/011-1-kings-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-kings/011-1-kings-014.adoc#v11-14-0[Próximo Capítulo &#62;]