include::./index.adoc[]

[[v15-9-0]]
=== Ezra, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v15-9-1]]

^<<v15-9-1,1>>^ And as soon as these things were finished, the princes approached me, saying: “The people of Israel and the priests and the Levites have not separated themselves from the peoples of the lands as regards their detestable things, namely, the Caʹnaan·ites, the Hitʹtites, the Perʹiz·zites, the Jebʹu·sites, the Amʹmon·ites, the Moʹab·ites, the Egyptians and the Amʹor·ites.

[[v15-9-2]]

^<<v15-9-2,2>>^ For they have accepted some of their daughters for themselves and for their sons; and they, the holy seed, have become mingled with the peoples of the lands, and the hand of the princes and the deputy rulers has proved to be foremost in this unfaithfulness.”

[[v15-9-3]]

^<<v15-9-3,3>>^ Now as soon as I heard of this thing I ripped apart my garment and my sleeveless coat, and I began to pull out some of the hair of my head and of my beard, and I kept sitting stunned.

[[v15-9-4]]

^<<v15-9-4,4>>^ Also to me they came gathering themselves, everyone trembling because of the words of the God of Israel against the unfaithfulness of the exiled people, while I was sitting stunned until the grain offering of the evening.

[[v15-9-5]]

^<<v15-9-5,5>>^ And at the grain offering of the evening I stood up from my humiliation, with my garment and my sleeveless coat torn apart, and I proceeded to kneel upon my knees and spread out my palms to Jehovah my God.

[[v15-9-6]]

^<<v15-9-6,6>>^ And I went on to say: “O my God, I do feel ashamed and embarrassed to raise my face to you, O my God, for our errors themselves have multiplied over our head and our guiltiness has grown great even to the heavens.

[[v15-9-7]]

^<<v15-9-7,7>>^ From the days of our forefathers we have been in great guiltiness until this day; and because of our errors we have been given, we ourselves, our kings, our priests, into the hand of the kings of the lands with the sword, with the captivity and with the plunder and with shame of face, just as this day.

[[v15-9-8]]

^<<v15-9-8,8>>^ And now for a little moment favor from Jehovah our God has come by leaving over for us those who escape and by giving us a peg^&#42;1^ in his holy place, to make our eyes shine, O our God, and to give us a little reviving in our servitude.

[NOTE]
====
. Likely, “a remnant,” one Heb. ms and by a slight correction of M (from ya·thedhʹ to yeʹther).
====

[[v15-9-9]]

^<<v15-9-9,9>>^ For we are servants; and in our servitude our God has not left us, but he extends toward us loving-kindness before the kings of Persia, to give us a reviving so as to raise up the house of our God and to restore its desolated places and to give us a stone wall in Judah and in Jerusalem.

[[v15-9-10]]

^<<v15-9-10,10>>^ “And now what shall we say, O our God, after this? For we have left your commandments,

[[v15-9-11]]

^<<v15-9-11,11>>^ which you commanded by means of your servants the prophets, saying, ‘The land that YOU people are going in to take possession of is an impure land because of the impurity of the peoples of the lands, because of their detestable things with which they have filled it from end to end by their uncleanness.

[[v15-9-12]]

^<<v15-9-12,12>>^ And now YOUR daughters do not YOU people give to their sons, neither their daughters do YOU accept for YOUR sons; and to time indefinite YOU must not work for their peace and their prosperity,^&#42;1^ in order that YOU may grow strong and certainly eat the good of the land and indeed take possession &#91;of it&#93; for YOUR sons to time indefinite.’

[NOTE]
====
. Lit., “their good.”
====

[[v15-9-13]]

^<<v15-9-13,13>>^ And after all that has come upon us for our bad deeds and our great guiltiness—for you yourself, O our God, have underestimated our error, and you have given us those who have escaped such as these—

[[v15-9-14]]

^<<v15-9-14,14>>^ shall we go breaking your commandments again and forming marriage alliances with the peoples of these detestable things? Will you not get incensed at us to the limit so that there will be none remaining and none escaping?

[[v15-9-15]]

^<<v15-9-15,15>>^ O Jehovah the God of Israel, you are righteous, because we have been left over as an escaped people as at this day. Here we are before you in our guiltiness, for it is impossible to stand before you on account of this.”

'''

xref:015-ezra/015-ezra-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-ezra/015-ezra-010.adoc#v15-10-0[Próximo Capítulo &#62;]