include::./index.adoc[]

[[v15-10-0]]
=== Ezra, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v15-10-1]]

^<<v15-10-1,1>>^ Now as soon as Ezʹra had prayed and he had made confession while weeping and lying prostrate before the house of the &#91;true&#93; God, those of Israel collected themselves together to him, a very large congregation, men and women and children, for the people had wept profusely.^&#42;1^

[NOTE]
====
. Lit., “had wept a great weeping.”
====

[[v15-10-2]]

^<<v15-10-2,2>>^ Then Shec·a·niʹah the son of Je·hiʹel of the sons of Eʹlam answered and said to Ezʹra: “We—we have acted unfaithfully against our God, so that we gave a dwelling to foreign wives from the peoples of the land. Yet now there exists a hope for Israel concerning this.

[[v15-10-3]]

^<<v15-10-3,3>>^ And now let us conclude a covenant with our God to put away all the wives and those born from them according to the counsel of Jehovah^&#42;1^ and of those trembling at the commandment of our God, that it may be done according to the law.

[NOTE]
====
. One of 134 scrib­al changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v15-10-4]]

^<<v15-10-4,4>>^ Get up, for the matter devolves upon you, and we are with you. Be strong and act.”

[[v15-10-5]]

^<<v15-10-5,5>>^ At that Ezʹra rose and had the chiefs of the priests, the Levites and all Israel take an oath to do according to this word. Accordingly they took an oath.

[[v15-10-6]]

^<<v15-10-6,6>>^ Ezʹra now rose from before the house of the &#91;true&#93; God and went to the dining hall of Je·ho·haʹnan the son of E·liʹa·shib. Although he went there, he ate no bread and drank no water, for he was mourning over the unfaithfulness of the exiled people.

[[v15-10-7]]

^<<v15-10-7,7>>^ Then they caused a call to pass throughout Judah and Jerusalem for all the former exiles to collect themselves together at Jerusalem;

[[v15-10-8]]

^<<v15-10-8,8>>^ and anyone that did not come in three days’ time according to the counsel of the princes and the older men—all his goods would be put under a ban and he himself be separated from the congregation of the exiled people.

[[v15-10-9]]

^<<v15-10-9,9>>^ So all the men of Judah and Benjamin collected themselves together at Jerusalem within three days, that is, in the ninth month on the twentieth &#91;day&#93; of the month, and all the people kept sitting in the open place of the house of the &#91;true&#93; God, shivering because of the matter and on account of the showers of rain.

[[v15-10-10]]

^<<v15-10-10,10>>^ At length Ezʹra the priest rose and said to them: “YOU yourselves have acted unfaithfully in that YOU gave a dwelling to foreign wives so as to add to the guiltiness of Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ And now make confession to Jehovah the God of YOUR forefathers and do his pleasure and separate yourselves from the peoples of the land and from the foreign wives.”

[[v15-10-12]]

^<<v15-10-12,12>>^ To this all the congregation answered and said with a loud voice: “Exactly according to your word it devolves upon us to do.

[[v15-10-13]]

^<<v15-10-13,13>>^ However, the people are many, and it is the season of showers of rain, and it is not possible to stand outside; and the business will not take one day or two, for we have rebelled to a great extent in this matter.

[[v15-10-14]]

^<<v15-10-14,14>>^ So, please, let our princes act representatively for all the congregation; and, as for all in our cities who have given a dwelling to foreign wives, let them come at the times appointed and along with them the older men of each individual city and its judges, until we have turned back the burning anger of our God from us, on account of this matter.”

[[v15-10-15]]

^<<v15-10-15,15>>^ (However, Jonʹa·than the son of Asʹa·hel and Jah·zeiʹah the son of Tikʹvah themselves stood up against this,^&#42;1^ and Me·shulʹlam and Shabʹbe·thai the Levites were the ones that helped them.)

[NOTE]
====
. Or, “Especially Jonathan the son of Asahel and Jahzeiah the son of Tikvah were the ones that acted representatively in this behalf [LXX, “were with me in this matter”].”
====

[[v15-10-16]]

^<<v15-10-16,16>>^ And the former exiles^&#42;1^ proceeded to do that way; and Ezʹra the priest &#91;and&#93; the men that were the heads of the fathers for their paternal house, even all of them by &#91;their&#93; names, now separated themselves and began sitting on the first day of the tenth month to inquire into the matter;

[NOTE]
====
. Lit., “the sons of the Exile.”
====

[[v15-10-17]]

^<<v15-10-17,17>>^ and gradually they finished with all the men that had given a dwelling to foreign wives by the first day of the first month.

[[v15-10-18]]

^<<v15-10-18,18>>^ And some of the sons of the priests came to be found that had given a dwelling to foreign wives; of the sons of Jeshʹu·a the son of Je·hozʹa·dak^&#42;1^ and his brothers, Ma·a·seiʹah and E·li·eʹzer and Jaʹrib and Ged·a·liʹah.

[NOTE]
====
. Lit., “Jozadak.” See 3:2 ftn, “Jehozadak.”
====

[[v15-10-19]]

^<<v15-10-19,19>>^ But they promised by shaking hands^&#42;1^ to put their wives away, and that, they being guilty, there should be a ram of the flock for their guiltiness.^&#42;2^

[NOTE]
====
. Lit., “they gave their hand.”
. “And their guilt offering was a ram of the flock for their guiltiness,” by an emendation.
====

[[v15-10-20]]

^<<v15-10-20,20>>^ And of the sons of Imʹmer there were Ha·naʹni and Zeb·a·diʹah;

[[v15-10-21]]

^<<v15-10-21,21>>^ and of the sons of Haʹrim, Ma·a·seiʹah and E·liʹjah and She·maiʹah and Je·hiʹel and Uz·ziʹah;

[[v15-10-22]]

^<<v15-10-22,22>>^ and of the sons of Pashʹhur, Eli·o·eʹnai, Ma·a·seiʹah, Ishʹma·el, Ne·thanʹel, Joʹza·bad and El·e·aʹsah.

[[v15-10-23]]

^<<v15-10-23,23>>^ And of the Levites, Joʹza·bad and Shimʹe·i and Ke·laiʹah (that is, Ke·liʹta), Peth·a·hiʹah, Judah and E·li·eʹzer;

[[v15-10-24]]

^<<v15-10-24,24>>^ and of the singers, E·liʹa·shib; and of the gatekeepers, Shalʹlum and Teʹlem and Uʹri.

[[v15-10-25]]

^<<v15-10-25,25>>^ And of Israel, of the sons of Paʹrosh there were Ra·miʹah and Iz·ziʹah and Mal·chiʹjah and Mijʹa·min and El·e·aʹzar and Mal·chiʹjah^&#42;1^ and Be·naiʹah;

[NOTE]
====
. “Hashabiah,” LXX.
====

[[v15-10-26]]

^<<v15-10-26,26>>^ and of the sons of Eʹlam, Mat·ta·niʹah, Zech·a·riʹah and Je·hiʹel and Abʹdi and Jerʹe·moth and E·liʹjah;

[[v15-10-27]]

^<<v15-10-27,27>>^ and of the sons of Zatʹtu, Eli·o·eʹnai, E·liʹa·shib, Mat·ta·niʹah and Jerʹe·moth and Zaʹbad and A·ziʹza;

[[v15-10-28]]

^<<v15-10-28,28>>^ and of the sons of Beʹbai, Je·ho·haʹnan, Han·a·niʹah, Zabʹbai, Athʹlai;

[[v15-10-29]]

^<<v15-10-29,29>>^ and of the sons of Baʹni, Me·shulʹlam, Malʹluch and A·daiʹah, Jaʹshub and Sheʹal &#91;and&#93; Jerʹe·moth;^&#42;1^

[NOTE]
====
. “And Ramoth,” MmarginVg.
====

[[v15-10-30]]

^<<v15-10-30,30>>^ and of the sons of Paʹhath-moʹab, Adʹna and Cheʹlal, Be·naiʹah, Ma·a·seiʹah, Mat·ta·niʹah, Bezʹal·el and Binʹnu·i and Ma·nasʹseh;

[[v15-10-31]]

^<<v15-10-31,31>>^ and &#91;of&#93; the sons of Haʹrim, E·li·eʹzer, Is·shiʹjah, Mal·chiʹjah, She·maiʹah, Shimʹe·on,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamin, Malʹluch &#91;and&#93; Shem·a·riʹah;

[[v15-10-33]]

^<<v15-10-33,33>>^ of the sons of Haʹshum, Mat·teʹnai, Matʹtat·tah, Zaʹbad, E·liphʹe·let, Jerʹe·mai, Ma·nasʹseh &#91;and&#93; Shimʹe·i;

[[v15-10-34]]

^<<v15-10-34,34>>^ of the sons of Baʹni, Ma·a·daʹi, Amʹram and Uʹel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Be·naiʹah, Be·deiʹah, Chelʹu·hi,

[[v15-10-36]]

^<<v15-10-36,36>>^ Va·niʹah, Merʹe·moth, E·liʹa·shib,

[[v15-10-37]]

^<<v15-10-37,37>>^ Mat·ta·niʹah, Mat·teʹnai and Jaʹa·su;

[[v15-10-38]]

^<<v15-10-38,38>>^ and of the sons of Binʹnu·i,^&#42;1^ Shimʹe·i

[NOTE]
====
. “And of the sons of Binnui,” by a correction of M; LXX, “and the sons of Binnui”; MVg, “and Bani and Binnui.”
====

[[v15-10-39]]

^<<v15-10-39,39>>^ and Shel·e·miʹah and Nathan and A·daiʹah,

[[v15-10-40]]

^<<v15-10-40,40>>^ Mach·nadʹe·bai, Shaʹshai, Shaʹrai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azʹar·el and Shel·e·miʹah,^&#42;1^ Shem·a·riʹah,

[NOTE]
====
. “And Shelemiah.” Heb., weShe·lem·yaʹhu.
====

[[v15-10-42]]

^<<v15-10-42,42>>^ Shalʹlum, Am·a·riʹah, Joseph;

[[v15-10-43]]

^<<v15-10-43,43>>^ of the sons of Neʹbo, Je·iʹel, Mat·ti·thiʹah, Zaʹbad, Ze·biʹna, Jadʹdai and Joel &#91;and&#93; Be·naiʹah.

[[v15-10-44]]

^<<v15-10-44,44>>^ These all had accepted foreign wives, and they proceeded to send away wives along with sons.^&#42;1^

[NOTE]
====
. “And they proceeded to send away wives along with sons,” in agreement with LXX in First Esdras 9:36; M, possibly, “and from them there were wives and they placed sons [into the world].”
====

'''

xref:015-ezra/015-ezra-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-nehemiah/016-nehemiah-001.adoc#v16-1-0[Próximo Capítulo &#62;]