include::./index.adoc[]

[[v15-6-0]]
=== Ezra, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v15-6-1]]

^<<v15-6-1,1>>^ It was then that Da·riʹus the king put an order through, and they made an investigation in the house of the records of the treasures deposited there in Babylon.

[[v15-6-2]]

^<<v15-6-2,2>>^ And at Ec·batʹa·na,^&#42;1^ in the fortified place that was in the jurisdictional district of Meʹdi·a, there was found a scroll, and the memorandum to this effect was written within it:

[NOTE]
====
. “Ecbatana,” Vg; MSy, “Achmetha.”
====

[[v15-6-3]]

^<<v15-6-3,3>>^ “In the first year of Cyrus the king, Cyrus the king put an order through concerning the house of God in Jerusalem: Let the house be rebuilt as the place where they are to offer sacrifices, and its foundations are to be fixed, its height being sixty cubits,^&#42;1^ its width sixty cubits,

[NOTE]
====
. About 26.7 m (87.6 ft). See App 8A.
====

[[v15-6-4]]

^<<v15-6-4,4>>^ with three layers of stones rolled &#91;into place&#93; and one layer of timbers; and let the expense be given from the king’s house.

[[v15-6-5]]

^<<v15-6-5,5>>^ And also let the gold and silver vessels of the house of God that Neb·u·chad·nezʹzar took out of the temple that was in Jerusalem and brought to Babylon be returned, that they may reach the temple that is in Jerusalem at its place and be deposited in the house of God.

[[v15-6-6]]

^<<v15-6-6,6>>^ “Now Tatʹte·nai the governor beyond the River, Sheʹthar-bozʹe·nai and their colleagues, the lesser governors that are beyond the River, keep YOUR distance from there.

[[v15-6-7]]

^<<v15-6-7,7>>^ Let the work on that house of God alone. The governor of the Jews and the older men of the Jews will rebuild that house of God upon its place.

[[v15-6-8]]

^<<v15-6-8,8>>^ And by me an order has been put through as to what YOU will do with these older men of the Jews, for rebuilding that house of God; and from the royal treasury of the tax beyond the River the expense will promptly be given to these able-bodied men without cessation.

[[v15-6-9]]

^<<v15-6-9,9>>^ And what is needed, young bulls as well as rams and lambs for the burnt offerings to the God of heaven, wheat, salt, wine and oil, just as the priests that are in Jerusalem say, let there be given them continually day by day without fail;

[[v15-6-10]]

^<<v15-6-10,10>>^ that they may continually be presenting soothing offerings to the God of the heavens and praying for the life of the king and his sons.

[[v15-6-11]]

^<<v15-6-11,11>>^ And by me an order has been put through that, as for anybody that violates this decree,^&#42;1^ a timber will be pulled out of his house and he will be impaled upon it,^&#42;2^ and his house will be turned into a public privy on this account.

[NOTE]
====
. Or, “word.”
. Lit., “and, impaled, he will be struck upon it.” Compare App 5C.
====

[[v15-6-12]]

^<<v15-6-12,12>>^ And may the God who has caused his name to reside there overthrow any king and people that thrusts his hand out to commit a violation and destroy that house of God, which is in Jerusalem. I, Da·riʹus, do put through an order. Let it be done promptly.”

[[v15-6-13]]

^<<v15-6-13,13>>^ Then Tatʹte·nai the governor beyond the River, Sheʹthar-bozʹe·nai and their colleagues, just as Da·riʹus the king had sent &#91;word&#93;, so they did promptly.

[[v15-6-14]]

^<<v15-6-14,14>>^ And the older men of the Jews were building and making progress under the prophesying of Hagʹgai the prophet and Zech·a·riʹah the grandson of Idʹdo, and they built and finished &#91;it&#93; due to the order of the God of Israel and due to the order of Cyrus and Da·riʹus and Ar·ta·xerxʹes the king of Persia.

[[v15-6-15]]

^<<v15-6-15,15>>^ And they completed this house by the third day of the lunar month Aʹdar, that is, in the sixth year of the reign of Da·riʹus the king.

[[v15-6-16]]

^<<v15-6-16,16>>^ And the sons of Israel, the priests and the Levites and the rest of the former exiles^&#42;1^ held the inauguration of this house of God with joy.

[NOTE]
====
. Lit., “the sons of the Exile.” Aram., beneh-gha·lu·thaʼʹ.
====

[[v15-6-17]]

^<<v15-6-17,17>>^ And they presented for the inauguration of this house of God a hundred bulls, two hundred rams, four hundred lambs, and as a sin offering for all Israel twelve male goats, according to the number of the tribes of Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ And they appointed the priests in their classes and the Levites in their divisions, for the service of God which is in Jerusalem, according to the prescription of the book of Moses.^&#42;1^

[NOTE]
====
. The first section of Ezra written in Aram. begins in 4:8 and ends here.
====

[[v15-6-19]]

^<<v15-6-19,19>>^ And the former exiles proceeded to hold the passover on the fourteenth &#91;day&#93; of the first month.

[[v15-6-20]]

^<<v15-6-20,20>>^ As the priests and the Levites had cleansed themselves as one group, they were all of them clean, and so they slaughtered the passover victim for all the former exiles and for their brothers the priests and for themselves.

[[v15-6-21]]

^<<v15-6-21,21>>^ Then the sons of Israel that had returned from the Exile ate, and everyone that had separated himself to them from the uncleanness of the nations of the land, to search for Jehovah the God of Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ And they went on to hold the festival of unfermented cakes seven days with rejoicing; for Jehovah caused them to rejoice, and he had turned the heart of the king of As·syrʹi·a around toward them to strengthen their hands in the work of the house of the &#91;true&#93; God, the God of Israel.

'''

xref:015-ezra/015-ezra-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-ezra/015-ezra-007.adoc#v15-7-0[Próximo Capítulo &#62;]