include::./index.adoc[]

[[v15-4-0]]
=== Ezra, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v15-4-1]]

^<<v15-4-1,1>>^ When the adversaries of Judah and Benjamin heard that the sons of the Exile were building a temple to Jehovah the God of Israel,

[[v15-4-2]]

^<<v15-4-2,2>>^ they immediately approached Ze·rubʹba·bel and the heads of the paternal houses and said to them: “Let us build along with YOU; for, just like YOU, we search for YOUR God and to him we are sacrificing since the days of Eʹsar-hadʹdon the king of As·syrʹi·a, who brought us up here.”

[[v15-4-3]]

^<<v15-4-3,3>>^ However, Ze·rubʹba·bel and Jeshʹu·a and the rest of the heads of the paternal houses of Israel said to them: “YOU have nothing to do with us^&#42;1^ in building a house to our God, for we ourselves shall together build to Jehovah the God of Israel, just as King Cyrus the king of Persia has commanded us.”

[NOTE]
====
. Lit., “[There is] nothing to you and to us.” A Heb. idiom. See App 7B.
====

[[v15-4-4]]

^<<v15-4-4,4>>^ At that the people of the land were continually weakening the hands of the people of Judah and disheartening them from building,

[[v15-4-5]]

^<<v15-4-5,5>>^ and hiring counselors against them to frustrate their counsel all the days of Cyrus the king of Persia down till the reign of Da·riʹus the king of Persia.

[[v15-4-6]]

^<<v15-4-6,6>>^ And in the reign of A·has·u·eʹrus, at the start of his reign, they wrote an accusation against the inhabitants of Judah and Jerusalem.

[[v15-4-7]]

^<<v15-4-7,7>>^ Also, in the days of Ar·ta·xerxʹes, Bishʹlam, Mithʹre·dath, Tabʹe·el and the rest of his colleagues wrote to Ar·ta·xerxʹes the king of Persia, and the writing of the letter was written in Ar·a·maʹic characters and translated into the Ar·a·maʹic language.

[[v15-4-8]]

^<<v15-4-8,8>>^ ^&#42;1^ Reʹhum the chief government official and Shimʹshai the scribe wrote a letter against Jerusalem to Ar·ta·xerxʹes the king, as follows:

[NOTE]
====
. Ezra is written in Aram. from this vs through 6:18.
====

[[v15-4-9]]

^<<v15-4-9,9>>^ Then Reʹhum the chief government official and Shimʹshai the scribe and the rest of their colleagues, the judges and the lesser governors across the River,^&#42;1^ the secretaries, the people of Eʹrech, the Babylonians, the inhabitants of Suʹsa,^&#42;2^ that is, the Eʹlam·ites,

[NOTE]
====
. Or, “the transriverine (transfluvial) lesser governors.”
. Or, “Shushan.”
====

[[v15-4-10]]

^<<v15-4-10,10>>^ and the rest of the nations whom the great and honorable Asʹe·nap·par^&#42;1^ took into exile and settled in the cities of Sa·marʹi·a, and the rest beyond the River, ——;^&#42;2^ and now

[NOTE]
====
. Or, “Osnappar.” This is a clipped rendering of the name of the Assyrian king Ashurbanipal; Aram., like the Persian, which has no l, substitutes an r for the final l.
. In M the verb is evidently omitted here. LXX inserts “judged,” transposing this verb to the beginning of vs 9.
====

[[v15-4-11]]

^<<v15-4-11,11>>^ this is a copy of the letter that they sent concerning it:
“To Ar·ta·xerxʹes the king your servants, the men beyond the River: And now

[[v15-4-12]]

^<<v15-4-12,12>>^ let it become known to the king that the Jews who came up here from you to us have come to Jerusalem. They are building the rebellious and bad city, and they proceed to finish the walls and to repair the foundations.

[[v15-4-13]]

^<<v15-4-13,13>>^ Now let it become known to the king that, if this city should be rebuilt and its walls be finished, neither tax nor tribute nor toll will they give, and it will cause loss to the treasuries of the kings.

[[v15-4-14]]

^<<v15-4-14,14>>^ Now inasmuch as we do eat the salt^&#42;1^ of the palace, and it is not proper for us to see the denuding of the king, on this account we have sent and made &#91;it&#93; known to the king,

[NOTE]
====
. “Eat the salt.” An ancient expression meaning to receive a salary in payment for service.
====

[[v15-4-15]]

^<<v15-4-15,15>>^ that there may be an investigation of the book of records of your ancestors. Then you will find in the book of records and learn that that city is a city rebellious and causing loss to kings and jurisdictional districts, and within it there were movers of revolt from the days of old. For this reason that city has been laid waste.

[[v15-4-16]]

^<<v15-4-16,16>>^ We are making known to the king that, if that city should be rebuilt and its walls be finished, you also will certainly have no share beyond the River.”^&#42;1^

[NOTE]
====
. That is, the Euphrates.
====

[[v15-4-17]]

^<<v15-4-17,17>>^ The king sent word to Reʹhum the chief government official and Shimʹshai the scribe and the rest of their colleagues who were dwelling in Sa·marʹi·a and the rest beyond the River:
“Greetings!^&#42;1^ And now

[NOTE]
====
. Lit., “Peace!” Aram., shelamʹ.
====

[[v15-4-18]]

^<<v15-4-18,18>>^ the official document that YOU have sent us^&#42;1^ has been distinctly read before me.

[NOTE]
====
. “Us,” pl. to denote excellence, and it is used like the present-day editorial “we.”
====

[[v15-4-19]]

^<<v15-4-19,19>>^ So an order has been put through by me, and they have investigated and found that that city has from the days of old been one rising up against kings and one in which rebellion and revolt have been carried on.

[[v15-4-20]]

^<<v15-4-20,20>>^ And there proved to be strong kings over Jerusalem and governing all beyond the River, and tax, tribute and toll were being given to them.

[[v15-4-21]]

^<<v15-4-21,21>>^ Now PUT an order through for these able-bodied men to stop, that that city may not be rebuilt until the order is put through by me.

[[v15-4-22]]

^<<v15-4-22,22>>^ So be careful that there be no negligence about acting in this regard, that the harm may not increase to the injury of kings.”

[[v15-4-23]]

^<<v15-4-23,23>>^ Now after the copy of the official document of Ar·ta·xerxʹes the king had been read before Reʹhum and Shimʹshai the scribe and their colleagues, they went in a hurry to Jerusalem to the Jews and stopped them by force of arms.^&#42;1^

[NOTE]
====
. Or, “by an army.” Lit., “with arm and strength.”
====

[[v15-4-24]]

^<<v15-4-24,24>>^ It was then that the work on the house of God, which was in Jerusalem, stopped; and it continued stopped until the second year of the reign of Da·riʹus the king of Persia.

'''

xref:015-ezra/015-ezra-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-ezra/015-ezra-005.adoc#v15-5-0[Próximo Capítulo &#62;]