include::./index.adoc[]

[[v15-5-0]]
=== Ezra, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v15-5-1]]

^<<v15-5-1,1>>^ And Hagʹgai the prophet and Zech·a·riʹah the grandson of Idʹdo the prophet prophesied to the Jews who were in Judah and in Jerusalem, in the name of the God of Israel &#91;who was&#93; over them.

[[v15-5-2]]

^<<v15-5-2,2>>^ It was then that Ze·rubʹba·bel the son of She·alʹti·el^&#42;1^ and Jeshʹu·a the son of Je·hozʹa·dak got up and started to rebuild the house of God, which was in Jerusalem; and with them there were God’s prophets giving them aid.

[NOTE]
====
. “The son of Shealtiel.” Aram., bar-Sheʼal·ti·ʼelʹ. Compare Mt 16:17 ftn.
====

[[v15-5-3]]

^<<v15-5-3,3>>^ At that time Tatʹte·nai the governor beyond the River and Sheʹthar-bozʹe·nai and their colleagues came to them, and this is what they were saying to them: “Who put an order through to YOU to build this house and to finish this beam structure?”^&#42;1^

[NOTE]
====
. “This preparation,” LXX; Vg, “these walls.”
====

[[v15-5-4]]

^<<v15-5-4,4>>^ Then they^&#42;1^ said to them this: “What are the names of the able-bodied men that are building this building?”

[NOTE]
====
. “They,” LXXSy; MVg, “we.” See vs 10.
====

[[v15-5-5]]

^<<v15-5-5,5>>^ And the eye of their God proved to be upon the older men^&#42;1^ of the Jews, and they did not stop them until the report could go to Da·riʹus and then an official document concerning this could be sent back.

[NOTE]
====
. Or, “elders.”
====

[[v15-5-6]]

^<<v15-5-6,6>>^ &#91;Here&#93; is a copy of the letter that Tatʹte·nai the governor beyond the River and Sheʹthar-bozʹe·nai and his colleagues, the lesser governors that were beyond the River,^&#42;1^ sent to Da·riʹus the king;

[NOTE]
====
. That is, the Euphrates.
====

[[v15-5-7]]

^<<v15-5-7,7>>^ they sent the word to him, and the writing in it was in this manner:
“To Da·riʹus the king:
“All peace!

[[v15-5-8]]

^<<v15-5-8,8>>^ Let it become known to the king that we went to the jurisdictional district of Judah to the house of the great God, and it is being built with stones rolled^&#42;1^ &#91;into place&#93;, and timbers are being laid in the walls; and that work is being eagerly done and is making progress in their hands.

[NOTE]
====
. That is, stones too heavy to be carried.
====

[[v15-5-9]]

^<<v15-5-9,9>>^ Then we asked these older men. This is what we said to them: ‘Who put an order through to YOU to build this house and to finish this beam structure?’

[[v15-5-10]]

^<<v15-5-10,10>>^ And we also asked them their names, so as to let you know, that we might write the names of the able-bodied men that are at their head.

[[v15-5-11]]

^<<v15-5-11,11>>^ “And this is the word that they gave back to us, saying: ‘We are the servants of the God of the heavens and the earth, and we are rebuilding the house that had been built many years before this, which a great king of Israel built and finished.

[[v15-5-12]]

^<<v15-5-12,12>>^ However, because our fathers irritated the God of the heavens, he gave them into the hand of Neb·u·chad·nezʹzar the king of Babylon, the Chal·deʹan, and he demolished this house and took the people into exile at Babylon.

[[v15-5-13]]

^<<v15-5-13,13>>^ Nevertheless, in the first year of Cyrus the king of Babylon,^&#42;1^ Cyrus the king put an order through to rebuild this house of God.

[NOTE]
====
. “Babylon,” Vg; M, “Babel”; Sy, “Persia.”
====

[[v15-5-14]]

^<<v15-5-14,14>>^ And also the gold and silver vessels of the house of God that Neb·u·chad·nezʹzar had taken out of the temple, which was in Jerusalem, and brought to the temple of Babylon,^&#42;1^ these Cyrus the king took out of the temple of Babylon, and they were given to Shesh·bazʹzar,^&#42;2^ the name of the one whom he made governor.

[NOTE]
====
. “To the temple of Babylon.” Aram., leheh·khelaʼʹ di Va·velʹ; LXX, “to the temple of the king.”
. “Zerubbabel” in 2:2; 3:8.
====

[[v15-5-15]]

^<<v15-5-15,15>>^ And he said to him: “Take these vessels. Go, deposit them in the temple that is in Jerusalem, and let the house of God be rebuilt upon its place.”

[[v15-5-16]]

^<<v15-5-16,16>>^ When that Shesh·bazʹzar came he laid the foundations of the house of God, which is in Jerusalem; and from then until now it is being rebuilt but it has not been completed.’

[[v15-5-17]]

^<<v15-5-17,17>>^ “And now if to the king it seems good, let there be an investigation in the king’s house of treasures that is there in Babylon, whether it is so that from Cyrus the king an order was put through to rebuild that house of God in Jerusalem; and the decision of the king concerning this let him send to us.”

'''

xref:015-ezra/015-ezra-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-ezra/015-ezra-006.adoc#v15-6-0[Próximo Capítulo &#62;]