include::./index.adoc[]

[[v4-22-0]]
=== Numbers, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-22-1]]

^<<v4-22-1,1>>^ Then the sons of Israel pulled away and encamped on the desert plains of Moʹab across the Jordan from Jerʹi·cho.

[[v4-22-2]]

^<<v4-22-2,2>>^ And Baʹlak the son of Zipʹpor got to see all that Israel had done to the Amʹor·ites.

[[v4-22-3]]

^<<v4-22-3,3>>^ And Moʹab became very frightened at the people, because they were many; and Moʹab began to feel a sickening dread of the sons of Israel.

[[v4-22-4]]

^<<v4-22-4,4>>^ And Moʹab proceeded to say to the older men of Midʹi·an: “Now this congregation^&#42;1^ will lick up all our surroundings like the bull licking up the green growth of the field.”
And Baʹlak the son of Zipʹpor was king of Moʹab at that particular time.

[NOTE]
====
. “This congregation,” SamLXXSyVg; M, “the congregation.”
====

[[v4-22-5]]

^<<v4-22-5,5>>^ He now sent messengers to Baʹlaam the son of Beʹor at Peʹthor, which is by the River^&#42;1^ of the land of the sons of his people, to call him, saying: “Look! A people has come out of Egypt. Look! They have covered the earth as far as one can see,^&#42;2^ and they are dwelling right in front of me.

[NOTE]
====
. “The River,” evidently the Euphrates.
. Lit., “covered the eye of the earth.”
====

[[v4-22-6]]

^<<v4-22-6,6>>^ And now do come, please; do curse this people for me, for they are mightier than I am. Perhaps I may be able to strike them and I may drive them out of the land; for I well know that the one whom you bless is a blessed one and the one whom you curse is cursed.”

[[v4-22-7]]

^<<v4-22-7,7>>^ So the older men of Moʹab and the older men of Midʹi·an traveled with the payments for divination in their hands and went to Baʹlaam and spoke to him Baʹlak’s words.

[[v4-22-8]]

^<<v4-22-8,8>>^ At that he said to them: “Lodge here tonight, and I shall certainly return YOU word just as Jehovah may speak to me.” Accordingly the princes of Moʹab stayed with Baʹlaam.

[[v4-22-9]]

^<<v4-22-9,9>>^ Then God came to Baʹlaam and said: “Who are these men with you?”

[[v4-22-10]]

^<<v4-22-10,10>>^ So Baʹlaam said to the &#91;true&#93; God: “Baʹlak the son of Zipʹpor, the king of Moʹab, has sent to me, saying,^&#42;1^

[NOTE]
====
. “Saying,” LXXSyVg.
====

[[v4-22-11]]

^<<v4-22-11,11>>^ ‘Look! The people who are coming out of Egypt, and they go covering the earth as far as the eye can see. Now do come, do execrate them for me. Perhaps I may be able to fight against them and I shall actually drive them out.’”

[[v4-22-12]]

^<<v4-22-12,12>>^ But God said to Baʹlaam: “You must not go with them. You must not curse the people, for they are blessed.”

[[v4-22-13]]

^<<v4-22-13,13>>^ After that Baʹlaam got up in the morning and said to the princes of Baʹlak: “Go to YOUR country, because Jehovah has refused to let me go with YOU.”

[[v4-22-14]]

^<<v4-22-14,14>>^ So the princes of Moʹab got up and came to Baʹlak and said: “Baʹlaam has refused to come with us.”

[[v4-22-15]]

^<<v4-22-15,15>>^ However, Baʹlak sent again other princes in greater number and more honorable than the former.

[[v4-22-16]]

^<<v4-22-16,16>>^ In turn they came to Baʹlaam and said to him: “This is what Baʹlak the son of Zipʹpor has said, ‘Do not be detained, please, from coming to me.

[[v4-22-17]]

^<<v4-22-17,17>>^ For I shall without fail honor you greatly, and everything you may say to me I shall do. So do come, please. Do execrate this people for me.’”

[[v4-22-18]]

^<<v4-22-18,18>>^ But Baʹlaam answered and said to the servants of Baʹlak: “If Baʹlak were to give me his house full of silver and gold, I should not be able to pass beyond the order of Jehovah my God, so as to do something small or great.

[[v4-22-19]]

^<<v4-22-19,19>>^ And now YOU men also stay here, please, tonight that I may know what further Jehovah will speak with me.”

[[v4-22-20]]

^<<v4-22-20,20>>^ Then God^&#42;1^ came to Baʹlaam by night and said to him: “If it is to call you that the men have come, get up, go with them. But only the word that I shall speak to you is what you may speak.”

[NOTE]
====
. “God,” MLXXSyVg; Sam, “the angel of God.”
====

[[v4-22-21]]

^<<v4-22-21,21>>^ After that Baʹlaam got up in the morning and saddled his she-ass and went with the princes of Moʹab.

[[v4-22-22]]

^<<v4-22-22,22>>^ And the anger of God^&#42;1^ began to blaze because he was going; and Jehovah’s angel proceeded to station himself in the road to resist him.^&#42;2^ And he was riding upon his she-ass, and two attendants^&#42;3^ of his were with him.

[NOTE]
====
. “God,” MLXXSyVg; Sam and one Heb. ms, “Jehovah.”
. Lit., “in the road as a resister of him.”
. Or, “boys; young men.”
====

[[v4-22-23]]

^<<v4-22-23,23>>^ And the ass got to see Jehovah’s angel stationed in the road with his drawn sword in his hand; and the ass tried to turn aside from the road that she might go into the field, but Baʹlaam began to strike the ass in order to turn her aside to the road.

[[v4-22-24]]

^<<v4-22-24,24>>^ And Jehovah’s angel kept standing in the narrow way between the vineyards, with a stone wall on this side and a stone wall on that side.

[[v4-22-25]]

^<<v4-22-25,25>>^ And the she-ass kept seeing Jehovah’s angel and began to squeeze herself against the wall and so to squeeze Baʹlaam’s foot against the wall; and he went beating her some more.

[[v4-22-26]]

^<<v4-22-26,26>>^ Jehovah’s angel now passed by again and stood in a narrow place, where there was no way to turn aside to the right or the left.

[[v4-22-27]]

^<<v4-22-27,27>>^ When the ass got to see Jehovah’s angel she now lay down under Baʹlaam; so that Baʹlaam’s anger blazed, and he kept beating the ass with his staff.

[[v4-22-28]]

^<<v4-22-28,28>>^ Finally Jehovah opened the mouth of the ass and she said to Baʹlaam: “What have I done to you so that you have beaten me these three times?”

[[v4-22-29]]

^<<v4-22-29,29>>^ At this Baʹlaam said to the ass: “It is because you have dealt ruthlessly with me. If only there were a sword in my hand, for now I should have killed you!”

[[v4-22-30]]

^<<v4-22-30,30>>^ Then the she-ass said to Baʹlaam: “Am I not your she-ass that you have ridden upon all your life long until this day? Have I ever been used to do to you this way?” To which he said: “No!”

[[v4-22-31]]

^<<v4-22-31,31>>^ And Jehovah proceeded to uncover Baʹlaam’s eyes, so that he saw Jehovah’s angel stationed in the road with his drawn sword in his hand. At once he bowed low and prostrated himself on his face.

[[v4-22-32]]

^<<v4-22-32,32>>^ Then Jehovah’s angel said to him: “Why have you beaten your she-ass these three times? Look! I—I have come out to offer resistance, because your way has been headlong^&#42;1^ against my will.

[NOTE]
====
. “Your way is not elegant (charming; good),” LXX; Vg, “your way is perverse.”
====

[[v4-22-33]]

^<<v4-22-33,33>>^ And the she-ass got to see me and tried to turn aside before me these three times. Supposing she had not^&#42;1^ turned aside from before me! For by now even you I should have killed, but her I should have preserved alive.”

[NOTE]
====
. “Unless she had,” LXX; Vg, “Unless the she-ass had”; M, “Perhaps she had.”
====

[[v4-22-34]]

^<<v4-22-34,34>>^ At this Baʹlaam said to Jehovah’s angel: “I have sinned, because I did not know that it was you stationed in the road to meet me. And now, if it is bad in your eyes, let me go my way back.”

[[v4-22-35]]

^<<v4-22-35,35>>^ But Jehovah’s angel said to Baʹlaam: “Go with the men; and nothing but the word that I shall speak to you is what you may speak.” And Baʹlaam continued going with the princes of Baʹlak.

[[v4-22-36]]

^<<v4-22-36,36>>^ When Baʹlak got to hear that Baʹlaam had come, he at once went out to meet him at the city of Moʹab, which is on the bank of the Arʹnon, which is on the extremity of the territory.

[[v4-22-37]]

^<<v4-22-37,37>>^ Then Baʹlak said to Baʹlaam: “Have I not for a fact sent to you to call you? Why did you not come to me? Am I not really and truly able to honor you?”

[[v4-22-38]]

^<<v4-22-38,38>>^ At this Baʹlaam said to Baʹlak: “Here I have come to you now. Shall I be able at all to speak something? The word that God will place in my mouth is what I shall speak.”

[[v4-22-39]]

^<<v4-22-39,39>>^ So Baʹlaam went with Baʹlak and they came to Kirʹi·ath-huʹzoth.

[[v4-22-40]]

^<<v4-22-40,40>>^ And Baʹlak proceeded to sacrifice cattle and sheep and to send some to Baʹlaam and the princes who were with him.

[[v4-22-41]]

^<<v4-22-41,41>>^ And it came about in the morning that Baʹlak went taking Baʹlaam and bringing him up to Baʹmoth-baʹal,^&#42;1^ that he might see^&#42;2^ from there the whole of the people.

[NOTE]
====
. “Bamoth-baal,” meaning “High Places of Baal.” The Canaanite Baals usually had names denoting attachment to specific localities. Such names later came to be transferred to the localities themselves, such as Baal-hermon, Baal-hazor, Baal-zephon.
. Or, “and he got to see.”
====

'''

xref:004-numbers/004-numbers-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numbers/004-numbers-023.adoc#v4-23-0[Próximo Capítulo &#62;]