include::./index.adoc[]

[[v4-17-0]]
=== Numbers, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-17-1]]

^<<v4-17-1,1>>^ Jehovah now spoke to Moses, saying:

[[v4-17-2]]

^<<v4-17-2,2>>^ “Speak to the sons of Israel and take from them one rod for each paternal house from all their chieftains, by the house of their fathers, twelve rods. You will write the name of each one upon his rod.

[[v4-17-3]]

^<<v4-17-3,3>>^ And Aaron’s name you will write upon Leʹvi’s rod, because there is one rod for the head of the house of their fathers.

[[v4-17-4]]

^<<v4-17-4,4>>^ And you must deposit them in the tent of meeting before the Testimony, where I regularly present myself to YOU.

[[v4-17-5]]

^<<v4-17-5,5>>^ And what must occur is that the man whom I shall choose, his rod will bud, and I shall certainly make subside from against me the murmurings of the sons of Israel, which they are murmuring against YOU.”

[[v4-17-6]]

^<<v4-17-6,6>>^ So Moses spoke to the sons of Israel, and all their chieftains went giving him a rod for each chieftain, a rod for each chieftain, by the house of their fathers, twelve rods; and Aaron’s rod was in among their rods.

[[v4-17-7]]

^<<v4-17-7,7>>^ Then Moses deposited the rods before Jehovah in the tent of the Testimony.

[[v4-17-8]]

^<<v4-17-8,8>>^ And it came about the next day that when Moses went into the tent of the Testimony, look! Aaron’s rod for the house of Leʹvi had budded, and it was bringing forth buds and blossoming flowers and was bearing ripe almonds.

[[v4-17-9]]

^<<v4-17-9,9>>^ Moses then brought out all the rods from before Jehovah to all the sons of Israel, and they went looking and taking each man his own rod.

[[v4-17-10]]

^<<v4-17-10,10>>^ Subsequently Jehovah said to Moses: “Put Aaron’s rod back before the Testimony as something to be kept for a sign to the sons of rebelliousness, that their murmurings may cease from against me, that they may not die.”

[[v4-17-11]]

^<<v4-17-11,11>>^ At once Moses did just as Jehovah had commanded him. He did just so.

[[v4-17-12]]

^<<v4-17-12,12>>^ And the sons of Israel began to say this to Moses: “Now we are bound to expire, we are bound to perish, we are all of us bound to perish.

[[v4-17-13]]

^<<v4-17-13,13>>^ Anyone approaching, coming near to Jehovah’s tabernacle, will die! Must we end up in expiring that way?”

'''

xref:004-numbers/004-numbers-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numbers/004-numbers-018.adoc#v4-18-0[Próximo Capítulo &#62;]