include::./index.adoc[]

[[v4-8-0]]
=== Numbers, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-8-1]]

^<<v4-8-1,1>>^ And Jehovah proceeded to speak to Moses, saying:

[[v4-8-2]]

^<<v4-8-2,2>>^ “Speak to Aaron, and you must say to him, ‘Whenever you light up the lamps, the seven lamps should shine on the area in front of the lampstand.’”

[[v4-8-3]]

^<<v4-8-3,3>>^ And Aaron began to do so. He lit up its lamps for the area in front of the lampstand, just as Jehovah had commanded Moses.

[[v4-8-4]]

^<<v4-8-4,4>>^ Now this was the workmanship of the lampstand. It was hammered work of gold. Up to its sides and up to its blossoms it was hammered work. According to the vision that Jehovah had shown Moses, so he had made the lampstand.

[[v4-8-5]]

^<<v4-8-5,5>>^ And Jehovah spoke further to Moses, saying:

[[v4-8-6]]

^<<v4-8-6,6>>^ “Take the Levites from among the sons of Israel, and you must cleanse them.

[[v4-8-7]]

^<<v4-8-7,7>>^ And this is what you should do to them to cleanse them: Spatter sin-cleansing water upon them, and they must have a razor pass over all their flesh and must wash their garments and cleanse themselves.

[[v4-8-8]]

^<<v4-8-8,8>>^ Then they must take a young bull and its grain offering of fine flour moistened with oil, and you will take another young bull for a sin offering.

[[v4-8-9]]

^<<v4-8-9,9>>^ And you must present the Levites before the tent of meeting and congregate all the assembly of the sons of Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ And you must present the Levites before Jehovah, and the sons of Israel must lay their hands upon the Levites.

[[v4-8-11]]

^<<v4-8-11,11>>^ And Aaron must cause the Levites to move to and fro before Jehovah as a wave offering from the sons of Israel, and they must serve for carrying on the service of Jehovah.

[[v4-8-12]]

^<<v4-8-12,12>>^ “Then the Levites will lay their hands upon the heads of the bulls. After that, render up the one as a sin offering and the other as a burnt offering to Jehovah to make atonement for the Levites.

[[v4-8-13]]

^<<v4-8-13,13>>^ And you must have the Levites stand before Aaron and his sons and must cause them to move to and fro as a wave offering to Jehovah.

[[v4-8-14]]

^<<v4-8-14,14>>^ And you must separate the Levites from among the sons of Israel, and the Levites must become mine.

[[v4-8-15]]

^<<v4-8-15,15>>^ And afterward the Levites will come in to serve at the tent of meeting. So you must cleanse them and cause them to move to and fro as a wave offering.

[[v4-8-16]]

^<<v4-8-16,16>>^ For they are given ones,^&#42;1^ given to me from among the sons of Israel. In place of those opening all wombs, all the firstborn of the sons of Israel, I must take them for myself.

[NOTE]
====
. “Given ones.” Heb., nethu·nimʹ, related to the title “Nethinim.” See 1Ch 9:2.
====

[[v4-8-17]]

^<<v4-8-17,17>>^ For every firstborn among the sons of Israel is mine, among man and among beast. On the day of my striking every firstborn in the land of Egypt I sanctified them to myself.

[[v4-8-18]]

^<<v4-8-18,18>>^ And I shall take the Levites in place of all the firstborn among the sons of Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ And I shall give the Levites as given ones to Aaron and his sons from among the sons of Israel, to carry on the service of the sons of Israel in the tent of meeting and to make atonement for the sons of Israel, that no plague may occur among the sons of Israel because the sons of Israel approach the holy place.”

[[v4-8-20]]

^<<v4-8-20,20>>^ And Moses and Aaron and all the assembly of the sons of Israel proceeded to do so to the Levites. In accord with all that Jehovah had commanded Moses as regards the Levites, that is the way the sons of Israel did to them.

[[v4-8-21]]

^<<v4-8-21,21>>^ So the Levites purified themselves and washed their garments, after which Aaron caused them to move to and fro as a wave offering before Jehovah. Then Aaron made an atonement for them to cleanse them.

[[v4-8-22]]

^<<v4-8-22,22>>^ First after that the Levites came in to carry on their service in the tent of meeting before Aaron and his sons. Just as Jehovah had commanded Moses respecting the Levites, so they did to them.

[[v4-8-23]]

^<<v4-8-23,23>>^ Jehovah now spoke to Moses, saying:

[[v4-8-24]]

^<<v4-8-24,24>>^ “This is what applies to the Levites:^&#42;1^ From twenty-five years old upward he will come to enter into the company in the service of the tent of meeting.

[NOTE]
====
. “This is the law for the Levites,” SyVg.
====

[[v4-8-25]]

^<<v4-8-25,25>>^ But after the age of fifty years he will retire from the service company and serve no longer.

[[v4-8-26]]

^<<v4-8-26,26>>^ And he must minister to his brothers in the tent of meeting in taking care of the obligation, but he must render no service. In accord with this you will do to the Levites in their obligations.”

'''

xref:004-numbers/004-numbers-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numbers/004-numbers-009.adoc#v4-9-0[Próximo Capítulo &#62;]