include::./index.adoc[]

[[v4-3-0]]
=== Numbers, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-3-1]]

^<<v4-3-1,1>>^ Now these were the generations^&#42;1^ of Aaron and Moses in the day that Jehovah spoke with Moses in Mount Siʹnai.

[NOTE]
====
. Or, “happenings; history.” See Ge 2:4 ftn, “History.”
====

[[v4-3-2]]

^<<v4-3-2,2>>^ And these were the names of Aaron’s sons: the firstborn Naʹdab and A·biʹhu, El·e·aʹzar and Ithʹa·mar.

[[v4-3-3]]

^<<v4-3-3,3>>^ These were the names of Aaron’s sons, the anointed priests whose hands had been filled with power to act as priests.

[[v4-3-4]]

^<<v4-3-4,4>>^ However, Naʹdab and A·biʹhu died before Jehovah when they offered illegitimate fire before Jehovah in the wilderness of Siʹnai; and they did not come to have any sons. But El·e·aʹzar and Ithʹa·mar continued to act as priests along with Aaron their father.

[[v4-3-5]]

^<<v4-3-5,5>>^ And Jehovah proceeded to speak to Moses, saying:

[[v4-3-6]]

^<<v4-3-6,6>>^ “Bring the tribe of Leʹvi near, and you must stand them before Aaron the priest, and they must minister to him.

[[v4-3-7]]

^<<v4-3-7,7>>^ And they must keep their obligation to him and their obligation to all the assembly before the tent of meeting in discharging the service of the tabernacle.

[[v4-3-8]]

^<<v4-3-8,8>>^ And they must take care of all the utensils of the tent of meeting, even the obligation of the sons of Israel in discharging the service of the tabernacle.

[[v4-3-9]]

^<<v4-3-9,9>>^ And you must give the Levites to Aaron and his sons. They are given ones,^&#42;1^ given to him from the sons of Israel.

[NOTE]
====
. “Given ones.” Heb., nethu·nimʹ, related to the title “Nethinim.” See Ezr 2:43.
====

[[v4-3-10]]

^<<v4-3-10,10>>^ And you should appoint Aaron and his sons, and they must take care of their priesthood; and any stranger^&#42;1^ coming near should be put to death.”

[NOTE]
====
. That is, any non-Aaronite.
====

[[v4-3-11]]

^<<v4-3-11,11>>^ And Jehovah continued to speak to Moses, saying:

[[v4-3-12]]

^<<v4-3-12,12>>^ “As for me, look! I do take the Levites from among the sons of Israel in place of all the firstborn opening the womb of the sons of Israel; and the Levites must become mine.

[[v4-3-13]]

^<<v4-3-13,13>>^ For every firstborn is mine. In the day that I struck every firstborn in the land of Egypt I sanctified to myself every firstborn in Israel from man to beast. They should become mine. I am Jehovah.”

[[v4-3-14]]

^<<v4-3-14,14>>^ And Jehovah spoke further to Moses in the wilderness of Siʹnai, saying:

[[v4-3-15]]

^<<v4-3-15,15>>^ “Register the sons of Leʹvi according to the house of their fathers by their families. Every male from a month old upward you should register.”

[[v4-3-16]]

^<<v4-3-16,16>>^ And Moses began to register them at the order of Jehovah, just as he had been commanded.

[[v4-3-17]]

^<<v4-3-17,17>>^ And these came to be the sons of Leʹvi by their names: Gerʹshon and Koʹhath and Me·rarʹi.

[[v4-3-18]]

^<<v4-3-18,18>>^ Now these were the names of the sons of Gerʹshon by their families: Libʹni and Shimʹe·i.

[[v4-3-19]]

^<<v4-3-19,19>>^ And the sons of Koʹhath by their families were Amʹram and Izʹhar, Heʹbron and Uzʹzi·el.

[[v4-3-20]]

^<<v4-3-20,20>>^ And the sons of Me·rarʹi by their families were Mahʹli and Muʹshi.
These were the families of the Levites according to the house of their fathers.

[[v4-3-21]]

^<<v4-3-21,21>>^ Of Gerʹshon there were the family of the Libʹnites and the family of the Shimʹe·ites. These were the families of the Gerʹshon·ites.

[[v4-3-22]]

^<<v4-3-22,22>>^ Their registered ones were by number of all males from a month old upward. Their registered ones were seven thousand five hundred.

[[v4-3-23]]

^<<v4-3-23,23>>^ The families of the Gerʹshon·ites were behind the tabernacle. They were encamped to the west.

[[v4-3-24]]

^<<v4-3-24,24>>^ And the chieftain of the paternal house for the Gerʹshon·ites was E·liʹa·saph the son of Laʹel.

[[v4-3-25]]

^<<v4-3-25,25>>^ And the obligation of the sons of Gerʹshon in the tent of meeting was the tabernacle and the tent, its covering and the screen of the entrance of the tent of meeting,

[[v4-3-26]]

^<<v4-3-26,26>>^ and the hangings of the courtyard and the screen of the entrance of the courtyard that is round about the tabernacle and the altar, and its tent cords, for all its service.

[[v4-3-27]]

^<<v4-3-27,27>>^ And of Koʹhath there were the family of the Amʹram·ites and the family of the Izʹhar·ites and the family of the Heʹbron·ites and the family of the Uz·ziʹel·ites. These were the families of the Koʹhath·ites.

[[v4-3-28]]

^<<v4-3-28,28>>^ Among the number of all the males from a month old upward there were eight thousand six^&#42;1^ hundred, taking care of the obligation to the holy place.

[NOTE]
====
. “Six,” MSamSyVg; some mss of LXX, “three,” which, added to the sums in vss 22 and 34, totals 22,000 as given in vs 39.
====

[[v4-3-29]]

^<<v4-3-29,29>>^ The families of the sons of Koʹhath were encamped on the side of the tabernacle to the south.

[[v4-3-30]]

^<<v4-3-30,30>>^ And the chieftain of the paternal house for the families of the Koʹhath·ites was E·li·zaʹphan the son of Uzʹzi·el.

[[v4-3-31]]

^<<v4-3-31,31>>^ And their obligation was the Ark and the table and the lampstand and the altars and the utensils of the holy place with which they would minister and the screen, and all its service.

[[v4-3-32]]

^<<v4-3-32,32>>^ And the chieftain of the chieftains of the Levites was El·e·aʹzar the son of Aaron the priest, who had the oversight of those taking care of the obligation to the holy place.

[[v4-3-33]]

^<<v4-3-33,33>>^ Of Me·rarʹi there were the family of the Mahʹlites and the family of the Muʹshites. These were the families of Me·rarʹi.

[[v4-3-34]]

^<<v4-3-34,34>>^ And their registered ones by the number of all the males from a month old upward were six thousand two hundred.

[[v4-3-35]]

^<<v4-3-35,35>>^ And the chieftain of the paternal house for the families of Me·rarʹi was Zuʹri·el the son of Abʹi·ha·il. They were encamped on the side of the tabernacle toward the north.

[[v4-3-36]]

^<<v4-3-36,36>>^ And the oversight for which the sons of Me·rarʹi were obligated was over the panel frames of the tabernacle and its bars and its pillars and its socket pedestals and all its utensils and all its service,

[[v4-3-37]]

^<<v4-3-37,37>>^ and the pillars of the courtyard round about and their socket pedestals and their tent pins and their tent cords.

[[v4-3-38]]

^<<v4-3-38,38>>^ And those camping before the tabernacle toward the east, before the tent of meeting toward the sunrising, were Moses and Aaron and his sons, those taking care of the obligation to the sanctuary, as the obligation for the sons of Israel. And any stranger^&#42;1^ coming near would be put to death.

[NOTE]
====
. That is, a non-Levite. See 1:51.
====

[[v4-3-39]]

^<<v4-3-39,39>>^ All the registered ones of the Levites whom Moses and Aaron^&#42;1^ registered at the order of Jehovah by their families, all the males from a month old upward, were twenty-two thousand.

[NOTE]
====
. “And Aaron,” MLXXVg. In M the words thus translated are marked with extraordinary points by the Sopherim. Moses was commanded to do the numbering, but since Aaron took part with Moses, some ancient copyist inserted “and Aaron” in the text. Later the scribes put dots over the words rather than take them out. SamSy and 11 Heb. mss omit. See App 2A.
====

[[v4-3-40]]

^<<v4-3-40,40>>^ Then Jehovah said to Moses: “Register all the firstborn males of the sons of Israel from a month old upward, and take the number of their names.

[[v4-3-41]]

^<<v4-3-41,41>>^ And you must take the Levites for me—I am Jehovah—in place of all the firstborn among the sons of Israel, and the domestic animals of the Levites in place of all the firstborn among the domestic animals of the sons of Israel.”

[[v4-3-42]]

^<<v4-3-42,42>>^ And Moses proceeded, just as Jehovah had commanded him, to register all the firstborn among the sons of Israel.

[[v4-3-43]]

^<<v4-3-43,43>>^ And all the firstborn males by the number of the names from a month old upward of their registered ones came to be twenty-two thousand two hundred and seventy-three.

[[v4-3-44]]

^<<v4-3-44,44>>^ And Jehovah continued to speak to Moses, saying:

[[v4-3-45]]

^<<v4-3-45,45>>^ “Take the Levites in place of all the firstborn among the sons of Israel, and the domestic animals of the Levites in place of their domestic animals; and the Levites must become mine. I am Jehovah.

[[v4-3-46]]

^<<v4-3-46,46>>^ And as the ransom price of the two hundred and seventy-three from the firstborn of the sons of Israel, who are in excess of the Levites,

[[v4-3-47]]

^<<v4-3-47,47>>^ you must take five shekels for each individual. In the shekel of the holy place you should take it. A shekel is twenty geʹrahs.

[[v4-3-48]]

^<<v4-3-48,48>>^ And you must give the money to Aaron and his sons as the ransom price of those who are in excess of them.”

[[v4-3-49]]

^<<v4-3-49,49>>^ So Moses took the money of the redemption price from those who were in excess of the ransom price of the Levites.

[[v4-3-50]]

^<<v4-3-50,50>>^ From the firstborn of the sons of Israel he took the money, a thousand three hundred and sixty-five shekels,^&#42;1^ in the shekel of the holy place.

[NOTE]
====
. “Shekels,” TJ,OLXXSyVg; MSam omit.
====

[[v4-3-51]]

^<<v4-3-51,51>>^ Then Moses gave the money of the ransom price to Aaron and his sons according to the order of Jehovah, just as Jehovah had commanded Moses.

'''

xref:004-numbers/004-numbers-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numbers/004-numbers-004.adoc#v4-4-0[Próximo Capítulo &#62;]