include::./index.adoc[]

[[v4-25-0]]
=== Numbers, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-25-1]]

^<<v4-25-1,1>>^ Now Israel was dwelling in Shitʹtim. Then the people started to have immoral relations with the daughters of Moʹab.

[[v4-25-2]]

^<<v4-25-2,2>>^ And the women came calling the people to the sacrifices of their gods, and the people began to eat and to bow down to their gods.

[[v4-25-3]]

^<<v4-25-3,3>>^ So Israel^&#42;1^ attached itself to the Baʹal of Peʹor;^&#42;2^ and the anger of Jehovah began to blaze against Israel.

[NOTE]
====
. “Israel,” MLXXSyVg; Sam, “some of the sons of Israel.”
. Or, “to Baal-peor.”
====

[[v4-25-4]]

^<<v4-25-4,4>>^ Hence Jehovah said to Moses: “Take all the head ones^&#42;1^ of the people and expose^&#42;2^ them to Jehovah toward the sun, that the burning anger of Jehovah may turn back from Israel.”

[NOTE]
====
. Or, “all the heads.”
. “Expose,” that is, with legs and arms broken, MSy; TJVg, “hang”; LXX, “make an example of.”
====

[[v4-25-5]]

^<<v4-25-5,5>>^ Then Moses said to the judges of Israel: “Each one of YOU kill his men who have an attachment with the Baʹal of Peʹor.”

[[v4-25-6]]

^<<v4-25-6,6>>^ But, look! a man of the sons of Israel came, and he was bringing near to his brothers^&#42;1^ a Midʹi·an·ite woman before Moses’ eyes and before the eyes of all the assembly of the sons of Israel, while they were weeping at the entrance of the tent of meeting.

[NOTE]
====
. Possibly, “to his tent.” Compare Ge 31:25 ftn.
====

[[v4-25-7]]

^<<v4-25-7,7>>^ When Phinʹe·has the son of El·e·aʹzar the son of Aaron the priest caught sight of it, he at once got up from the midst of the assembly and took a lance in his hand.

[[v4-25-8]]

^<<v4-25-8,8>>^ Then he went after the man of Israel into the vaulted tent^&#42;1^ and pierced both of them through, the man of Israel and the woman through her genital parts.^&#42;2^ At that the scourge was halted from upon the sons of Israel.

[NOTE]
====
. Or, “women’s part (of the tent).”
. “The genital parts,” Vg; LXX, “her womb.”
====

[[v4-25-9]]

^<<v4-25-9,9>>^ And those who died from the scourge amounted to twenty-four thousand.

[[v4-25-10]]

^<<v4-25-10,10>>^ Then Jehovah spoke to Moses, saying:

[[v4-25-11]]

^<<v4-25-11,11>>^ “Phinʹe·has the son of El·e·aʹzar the son of Aaron the priest has turned back my wrath from upon the sons of Israel by his tolerating no rivalry at all toward me in the midst of them, so that I have not exterminated the sons of Israel in my insistence on exclusive devotion.

[[v4-25-12]]

^<<v4-25-12,12>>^ For that reason say, ‘Here I am giving him my covenant of peace.

[[v4-25-13]]

^<<v4-25-13,13>>^ And it must serve as the covenant of a priesthood to time indefinite for him and his offspring after him, due to the fact that he tolerated no rivalry toward his God and proceeded to make atonement for the sons of Israel.’”

[[v4-25-14]]

^<<v4-25-14,14>>^ Incidentally the name of the fatally struck Israelite man who was fatally struck with the Midʹi·an·i·tess was Zimʹri the son of Saʹlu, a chieftain of a paternal house of the Simʹe·on·ites.

[[v4-25-15]]

^<<v4-25-15,15>>^ And the name of the Midʹi·an·ite woman fatally struck was Cozʹbi the daughter of Zur; he was a head one of the clans of a paternal house in Midʹi·an.

[[v4-25-16]]

^<<v4-25-16,16>>^ Later Jehovah spoke to Moses, saying:

[[v4-25-17]]

^<<v4-25-17,17>>^ “Let there be a harassing^&#42;1^ of the Midʹi·an·ites, and YOU men must strike them,

[NOTE]
====
. “Let there be a harassing.” In Heb. this is a verb in the infinitive absolute, indefinite as to time.
====

[[v4-25-18]]

^<<v4-25-18,18>>^ because they are harassing YOU with their deeds of cunning that they committed against YOU cunningly in the affair of Peʹor and in the affair of Cozʹbi the daughter of a chieftain of Midʹi·an, their sister who was fatally struck in the day of the scourge over the affair of Peʹor.”

'''

xref:004-numbers/004-numbers-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numbers/004-numbers-026.adoc#v4-26-0[Próximo Capítulo &#62;]