include::./index.adoc[]

[[v4-27-0]]
=== Numbers, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-27-1]]

^<<v4-27-1,1>>^ Then the daughters of Ze·loʹphe·had the son of Heʹpher the son of Gilʹe·ad the son of Maʹchir the son of Ma·nasʹseh, of the families of Ma·nasʹseh the son of Joseph, came near. And these were the names of his daughters: Mahʹlah, Noah and Hogʹlah and Milʹcah and Tirʹzah.

[[v4-27-2]]

^<<v4-27-2,2>>^ And they proceeded to stand before Moses and before El·e·aʹzar the priest and before the chieftains and all the assembly at the entrance of the tent of meeting, saying:

[[v4-27-3]]

^<<v4-27-3,3>>^ “Our father has died in the wilderness, and yet he did not prove to be in among the assembly, that is, those who ranged themselves against Jehovah in the assembly of Koʹrah, but for his own sin he has died; and he did not get to have any sons.

[[v4-27-4]]

^<<v4-27-4,4>>^ Why should the name of our father be taken away from the midst of his family because he had no son? O give us a possession in the midst of our father’s brothers.”

[[v4-27-5]]

^<<v4-27-5,5>>^ At that Moses presented their case before Jehovah.

[[v4-27-6]]

^<<v4-27-6,6>>^ Jehovah then said this to Moses:

[[v4-27-7]]

^<<v4-27-7,7>>^ “The daughters of Ze·loʹphe·had are speaking right. By all means you should give them the possession of an inheritance in the midst of their father’s brothers, and you must cause their father’s inheritance to pass to them.

[[v4-27-8]]

^<<v4-27-8,8>>^ And to the sons of Israel you should speak, saying, ‘In case any man should die without his having a son, YOU must then cause his inheritance to pass to his daughter.

[[v4-27-9]]

^<<v4-27-9,9>>^ And if he has no daughter, YOU must then give his inheritance to his brothers.

[[v4-27-10]]

^<<v4-27-10,10>>^ And if he has no brothers, YOU must then give his inheritance to his father’s brothers.

[[v4-27-11]]

^<<v4-27-11,11>>^ And if his father has no brothers, YOU must then give his inheritance to his blood relation who is closest to him of his family, and he must take possession of it. And it must serve as a statute by judicial decision for the sons of Israel, just as Jehovah has commanded Moses.’”

[[v4-27-12]]

^<<v4-27-12,12>>^ Subsequently Jehovah said to Moses: “Go up into this mountain of Abʹa·rim^&#42;1^ and see the land that I shall certainly give the sons of Israel.

[NOTE]
====
. Or, “the borderland.”
====

[[v4-27-13]]

^<<v4-27-13,13>>^ When you have seen it, then you must be gathered to your people, yes, you, just as Aaron your brother was gathered,

[[v4-27-14]]

^<<v4-27-14,14>>^ inasmuch as YOU men rebelled against my order in the wilderness of Zin at the quarreling of the assembly, in relation to sanctifying me^&#42;1^ by the waters before their eyes. These are the waters of Merʹi·bah at Kaʹdesh in the wilderness of Zin.”

[NOTE]
====
. “To sanctify me, you did not sanctify me,” LXX; Vg, “and you did not wish to sanctify me.”
====

[[v4-27-15]]

^<<v4-27-15,15>>^ Then Moses spoke to Jehovah, saying:

[[v4-27-16]]

^<<v4-27-16,16>>^ “Let Jehovah the God of the spirits of all sorts of flesh^&#42;1^ appoint over the assembly a man

[NOTE]
====
. Or, “spirits of all flesh.”
====

[[v4-27-17]]

^<<v4-27-17,17>>^ who will go out before them and who will come in before them and who will bring them out and who will bring them in, that Jehovah’s assembly may not become like sheep that have no shepherd.”

[[v4-27-18]]

^<<v4-27-18,18>>^ So Jehovah said to Moses: “Take for yourself Joshua the son of Nun, a man in whom there is spirit, and you must lay your hand upon him;

[[v4-27-19]]

^<<v4-27-19,19>>^ and you must stand him before El·e·aʹzar the priest and before all the assembly, and you must commission him before their eyes.

[[v4-27-20]]

^<<v4-27-20,20>>^ And you must put some of your dignity upon him, in order that all the assembly of the sons of Israel may listen to him.

[[v4-27-21]]

^<<v4-27-21,21>>^ And it is before El·e·aʹzar the priest that he will stand, and he must inquire in his behalf by the judgment of the Uʹrim before Jehovah. At his order they will go out and at his order they will come in, he and all the sons of Israel with him and all the assembly.”

[[v4-27-22]]

^<<v4-27-22,22>>^ And Moses proceeded to do just as Jehovah had commanded him. Accordingly he took Joshua and stood him before El·e·aʹzar the priest and before all the assembly

[[v4-27-23]]

^<<v4-27-23,23>>^ and laid his hands upon him and commissioned him, just as Jehovah had spoken by means of Moses.

'''

xref:004-numbers/004-numbers-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numbers/004-numbers-028.adoc#v4-28-0[Próximo Capítulo &#62;]