include::./index.adoc[]

[[v4-24-0]]
=== Numbers, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-24-1]]

^<<v4-24-1,1>>^ When Baʹlaam got to see that it was good in the eyes of Jehovah to bless Israel, he did not go away as at the other times to come upon any unlucky omens,^&#42;1^ but he directed his face to the wilderness.

[NOTE]
====
. Or, “spells,” that is, against Israel.
====

[[v4-24-2]]

^<<v4-24-2,2>>^ When Baʹlaam raised his eyes and saw Israel tabernacling by his tribes, then the spirit of God came to be upon him.

[[v4-24-3]]

^<<v4-24-3,3>>^ Hence he took up his proverbial utterance and said:
“The utterance of Baʹlaam the son of Beʹor,
And the utterance of the able-bodied man^&#42;1^ with the eye unsealed,^&#42;2^

[NOTE]
====
. “The able-bodied man.” Heb., hag·geʹver, a virile person; Gr., anʹthro·pos; Lat., hoʹmo.
. “Eye unsealed.” Or, “unrelenting eye.” See VT, Vol. III, 1953, pp. 78, 79. Also in vs 15.
====

[[v4-24-4]]

^<<v4-24-4,4>>^ The utterance of the one hearing the sayings of God,^&#42;1^
Who got to see a vision of the Almighty
While falling down with the eyes uncovered:

[NOTE]
====
. “God.” Heb., ʼEl; ­LXXBagster, “the Mighty One”; Lat., Deʹi.
====

[[v4-24-5]]

^<<v4-24-5,5>>^ How good-looking are your tents, O Jacob, your tabernacles, O Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Like torrent valleys they have extended a long way,
Like gardens^&#42;1^ by the river.
Like aloe plants^&#42;2^ that Jehovah has planted,
Like cedars by the waters.

[NOTE]
====
. “Paradises,” LXX(Gr., pa·raʹdei·soi)Sy.
. “Aloe plants,” M. Possibly, “vigorous trees; big trees.” LXXSyVg, “tents.”
====

[[v4-24-7]]

^<<v4-24-7,7>>^ Water keeps trickling from his two leather buckets,
And his seed is by many waters.
His king also will be higher than Aʹgag,^&#42;1^
And his kingdom will be lifted up.

[NOTE]
====
. “Agag,” MSyVg; SamLXX, “Gog.”
====

[[v4-24-8]]

^<<v4-24-8,8>>^ God is bringing him out of Egypt;
The swift course of a wild bull^&#42;1^ is his.
He will consume the nations, his oppressors,
And their bones he will gnaw, and he will break them to pieces with his arrows.^&#42;2^

[NOTE]
====
. Or, “buffalo.” LXX, “unicorn”; Vg, “rhinoceros.”
. “Arrows,” MVg; LXX, “missiles.”
====

[[v4-24-9]]

^<<v4-24-9,9>>^ He bowed down, he lay down like the lion,^&#42;1^
And, like a lion,^&#42;2^ who dares rouse him?
Those blessing you are the ones blessed,
And those cursing you are the ones cursed.”

[NOTE]
====
. The African lion. See 23:24 ftn, “The lion.”
. The Asian lion. See 23:24 ftn, “A lion.”
====

[[v4-24-10]]

^<<v4-24-10,10>>^ At that Baʹlak’s anger blazed against Baʹlaam and he clapped his hands, and Baʹlak went on to say to Baʹlaam: “It was to execrate my enemies that I called you, and, look! you have blessed them to the limit these three times.

[[v4-24-11]]

^<<v4-24-11,11>>^ And now run your way off to your place. I had said to myself I was without fail going to honor you, but, look! Jehovah has held you back from honor.”

[[v4-24-12]]

^<<v4-24-12,12>>^ In turn Baʹlaam said to Baʹlak: “Was it not also to your messengers whom you sent to me that I spoke, saying,

[[v4-24-13]]

^<<v4-24-13,13>>^ ‘If Baʹlak were to give me his house full of silver and gold, I should not be able to pass beyond the order of Jehovah so as to do something good or bad out of my own heart. Whatever Jehovah may speak is what I shall speak’?

[[v4-24-14]]

^<<v4-24-14,14>>^ And now here I am going away to my people. Do come, let me advise you what this people will do to your people afterward in the end of the days.”

[[v4-24-15]]

^<<v4-24-15,15>>^ So he took up his proverbial utterance and said:
“The utterance of Baʹlaam the son of Beʹor,
And the utterance of the able-bodied man^&#42;1^ with the eye unsealed,^&#42;2^

[NOTE]
====
. See vs 3 ftn, “Man.”
. See vs 3 ftn, “Unsealed.”
====

[[v4-24-16]]

^<<v4-24-16,16>>^ The utterance of the one hearing the sayings of God,^&#42;1^
And the one knowing the knowledge of the Most High—
A vision of the Almighty he got to see
While falling down with the eyes uncovered:

[NOTE]
====
. “God.” Heb., ʼEl; Gr., The·ouʹ; Lat., Deʹi.
====

[[v4-24-17]]

^<<v4-24-17,17>>^ I shall see him, but not now;
I shall behold him, but not near.
A star^&#42;1^ will certainly step forth^&#42;2^ out of Jacob,
And a scepter^&#42;3^ will indeed rise out of Israel.
And he will certainly break apart the temples of Moʹab’s &#91;head&#93;
And the cranium of all the sons of tumult of war.^&#42;4^

[NOTE]
====
. “Star,” MSamLXXSyVg; TJ, “king.”
. Or, “march forth,” MSam; LXXSyVg, “arise.”
. “Scepter,” M; Vg, “rod”; TJ, “Messiah”; LXX, “man”; Sy, “head one.”
. “Sons of tumult of war,” to agree with Jer 48:45; MSamLXXSyVg, “sons of Seth.”
====

[[v4-24-18]]

^<<v4-24-18,18>>^ And Eʹdom must become a possession,
Yes, Seʹir must become the possession of his enemies,
While Israel is displaying his courage.

[[v4-24-19]]

^<<v4-24-19,19>>^ And out of Jacob one will go subduing,^&#42;1^
And he must destroy any survivor from the city.”

[NOTE]
====
. Possibly, “And Jacob will subdue his enemies.” Vg, “Out of Jacob there will be one who will rule.”
====

[[v4-24-20]]

^<<v4-24-20,20>>^ When he got to see Amʹa·lek, he carried further his proverbial utterance and went on to say:
“Amʹa·lek was the first one^&#42;1^ of the nations,
But his end afterward will be even his perishing.”^&#42;2^

[NOTE]
====
. Or, “the chief; the beginning.”
. Possibly, “be to perish forever.”
====

[[v4-24-21]]

^<<v4-24-21,21>>^ When he got to see the Kenʹites, he carried further his proverbial utterance and went on to say:
“Durable is your dwelling, and set on the crag is your abode.^&#42;1^

[NOTE]
====
. Or, “nest.”
====

[[v4-24-22]]

^<<v4-24-22,22>>^ But there will come to be one to burn Kaʹin^&#42;1^ down.
How long will it be till As·syrʹi·a will carry you away captive?”

[NOTE]
====
. That is, the tribe of the Kenites.
====

[[v4-24-23]]

^<<v4-24-23,23>>^ And he carried further his proverbial utterance and went on to say:
“Woe! Who will survive when God^&#42;1^ causes it?

[NOTE]
====
. “God.” Heb., ʼEl; Gr., ho The·osʹ; Lat., Deʹus.
====

[[v4-24-24]]

^<<v4-24-24,24>>^ And there will be ships from the coast of Kitʹtim,
And they will certainly afflict As·syrʹi·a,
And they will indeed afflict Eʹber.^&#42;1^
But he too will eventually perish.”

[NOTE]
====
. “Eber,” MSam; LXXSyVg, “the Hebrews.” “Eber” may be referring to the land, or people, on the other side, that is, of the Euphrates.
====

[[v4-24-25]]

^<<v4-24-25,25>>^ After that Baʹlaam got up and went and returned to his place. And Baʹlak also went his own way.

'''

xref:004-numbers/004-numbers-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numbers/004-numbers-025.adoc#v4-25-0[Próximo Capítulo &#62;]