include::./index.adoc[]

[[v4-11-0]]
=== Numbers, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-11-1]]

^<<v4-11-1,1>>^ Now the people became as men having something evil to complain about in the ears of Jehovah. When Jehovah got to hear it, then his anger grew hot, and a fire of Jehovah began to blaze against them and to consume some in the extremity of the camp.

[[v4-11-2]]

^<<v4-11-2,2>>^ When the people began to cry out to Moses, then he made supplication to Jehovah, and the fire sank down.

[[v4-11-3]]

^<<v4-11-3,3>>^ And the name of that place got to be called^&#42;1^ Tabʹe·rah,^&#42;2^ because a fire of Jehovah had blazed against them.

[NOTE]
====
. Lit., “And he came to call the name of that place.”
. Meaning “Burning; Conflagration; Blaze.”
====

[[v4-11-4]]

^<<v4-11-4,4>>^ And the mixed crowd^&#42;1^ that was in the midst of them expressed selfish longing, and the sons of Israel too began to weep again and say: “Who will give us meat to eat?

[NOTE]
====
. Or, “the cluster [of people]; the rabble.”
====

[[v4-11-5]]

^<<v4-11-5,5>>^ How we remember the fish that we used to eat in Egypt for nothing, the cucumbers and the watermelons and the leeks and the onions and the garlic!

[[v4-11-6]]

^<<v4-11-6,6>>^ But now our soul is dried away. Our eyes are on nothing at all except the manna.”

[[v4-11-7]]

^<<v4-11-7,7>>^ Incidentally, the manna was like coriander seed, and its look^&#42;1^ was like the look of bdellium gum.

[NOTE]
====
. Or, “color.”
====

[[v4-11-8]]

^<<v4-11-8,8>>^ The people spread out and picked it up and ground it in hand mills or pounded it in a mortar, and they boiled it in cooking pots or made it into round cakes, and its taste proved to be like the taste of an oiled sweet cake.

[[v4-11-9]]

^<<v4-11-9,9>>^ And when the dew descended upon the camp by night, the manna would descend upon it.

[[v4-11-10]]

^<<v4-11-10,10>>^ And Moses got to hear the people weeping in their families, each man at the entrance of his tent. And Jehovah’s anger began growing very hot, and in the eyes of Moses it was bad.

[[v4-11-11]]

^<<v4-11-11,11>>^ Then Moses said to Jehovah: “Why have you caused evil to your servant,^&#42;1^ and why have I not found favor in your eyes, in placing the load of all this people upon me?

[NOTE]
====
. Or, “slave.”
====

[[v4-11-12]]

^<<v4-11-12,12>>^ Have I myself conceived all this people? Is it I who have given them birth, so that you should say to me, ‘Carry them in your bosom, just as the male nurse carries the suckling,’ to the soil about which you swore to their forefathers?

[[v4-11-13]]

^<<v4-11-13,13>>^ From where do I have meat to give to all this people? For they keep weeping toward me, saying, ‘Do give us meat, and let us eat!’

[[v4-11-14]]

^<<v4-11-14,14>>^ I am not able, I by myself, to carry all this people, because they are too heavy for me.

[[v4-11-15]]

^<<v4-11-15,15>>^ So if this is the way you are doing to me, please kill me off^&#42;1^ altogether, if I have found favor in your eyes, and let me not look upon my calamity.”^&#42;2^

[NOTE]
====
. “Kill me off.” Lit., “to kill me off.” In Heb. this is a verb in the infinitive construct, but some read it as an imperative.
. “Upon my calamity,” as corrected to read by the Sopherim, instead of “upon your calamity.” One of the Eighteen Emendations of the Sopherim. See App 2B.
====

[[v4-11-16]]

^<<v4-11-16,16>>^ In turn Jehovah said to Moses: “Gather for me seventy men of the older men of Israel, whom you do know that they are older men of the people and officers of theirs, and you must take them to the tent of meeting, and they must station themselves there with you.

[[v4-11-17]]

^<<v4-11-17,17>>^ And I shall have to come down and speak with you there; and I shall have to take away some of the spirit that is upon you and place it upon them, and they will have to help you in carrying the load of the people that you may not carry it, just you alone.

[[v4-11-18]]

^<<v4-11-18,18>>^ And to the people you should say, ‘Sanctify yourselves for tomorrow, as YOU will certainly eat meat, because YOU have wept in the ears of Jehovah, saying: “Who will give us meat to eat, for it was well with us in Egypt?” And Jehovah will certainly give YOU meat, and YOU will indeed eat.

[[v4-11-19]]

^<<v4-11-19,19>>^ YOU will eat, not one day nor two days nor five days nor ten days nor twenty days,

[[v4-11-20]]

^<<v4-11-20,20>>^ but up to a month of days, until it comes out of YOUR nostrils and it has become a loathing to YOU, just because YOU rejected Jehovah, who is in YOUR midst, and YOU went weeping before him, saying: “Why is it that we have come out of Egypt?”’”

[[v4-11-21]]

^<<v4-11-21,21>>^ Then Moses said: “The people in the midst of whom I am are six hundred thousand men on foot, and yet you—you have said, ‘Meat I shall give them, and they will certainly eat for a month of days’!

[[v4-11-22]]

^<<v4-11-22,22>>^ Will flocks and herds be slaughtered for them, for it to be adequate for them? Or will all the fish of the sea be caught for them, for it to be adequate for them?”

[[v4-11-23]]

^<<v4-11-23,23>>^ At this Jehovah said to Moses: “The hand of Jehovah is cut short, is it? Now you will see whether what I say befalls you or not.”

[[v4-11-24]]

^<<v4-11-24,24>>^ After that Moses went out and spoke to the people the words of Jehovah. And he went gathering seventy men from the older men of the people and proceeded to have them stand round about the tent.

[[v4-11-25]]

^<<v4-11-25,25>>^ Then Jehovah came down in a cloud and spoke to him and took away some of the spirit that was upon him and put it upon each of the seventy older men.^&#42;1^ And it came about that as soon as the spirit settled down upon them, then they proceeded to act as prophets; but they did not do it again.^&#42;2^

[NOTE]
====
. “The . . . older men (elders).” Heb., haz·zeqe·nimʹ; Gr., pre·sby·teʹrous. See Ac 15:2 ftn.
. “But they did not do it again,” MLXXSy; by a different vowel pointing of the Heb. verb in agreement with TJ,OVg, “and did not quit.”
====

[[v4-11-26]]

^<<v4-11-26,26>>^ Now there were two of the men remaining in the camp. The name of the one was Elʹdad, and the name of the other was Meʹdad. And the spirit began to settle down upon them, as they were among those written down, but they had not gone out to the tent. So they proceeded to act as prophets in the camp.

[[v4-11-27]]

^<<v4-11-27,27>>^ And a young man went running and reporting to Moses and saying: “Elʹdad and Meʹdad are acting as prophets in the camp!”

[[v4-11-28]]

^<<v4-11-28,28>>^ Then Joshua^&#42;1^ the son of Nun, the minister of Moses from his young manhood on, responded and said: “My lord Moses, restrain them!”

[NOTE]
====
. “Joshua.” Heb., Yehoh·shuʹaʽ, “Jehoshua.” See Ex 17:9 ftn.
====

[[v4-11-29]]

^<<v4-11-29,29>>^ However, Moses said to him: “Are you feeling jealous for me? No, I wish^&#42;1^ that all of Jehovah’s people were prophets, because Jehovah would put his spirit^&#42;2^ upon them!”

[NOTE]
====
. Lit., “And who will give?”
. “His spirit.” Heb., ru·chohʹ; Gr., pneuʹma; Lat., spiʹri·tum.
====

[[v4-11-30]]

^<<v4-11-30,30>>^ Later Moses withdrew to the camp, he and the older men of Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ And a wind^&#42;1^ burst forth from Jehovah and began driving quails from the sea and letting them fall above the camp about a day’s journey this way and about a day’s journey that way, all around the camp, and about two cubits above the surface of the earth.^&#42;2^

[NOTE]
====
. “And a wind.” Heb., weruʹach; Gr., pneuʹma; Lat., venʹtus. See vs 29 ftn, “Spirit”; Ge 8:1 ftn.
. “All around the camp, about two cubits from the earth,” LXX; Vg, “all around the camp, and they were flying in the air at an altitude of two cubits above the earth.” A cubit equaled 44.5 cm (17.5 in.).
====

[[v4-11-32]]

^<<v4-11-32,32>>^ Then the people got up all that day and all night and all the next day and kept gathering the quail. The one collecting least gathered ten hoʹmers,^&#42;1^ and they kept spreading them extensively^&#42;2^ all around the camp for themselves.

[NOTE]
====
. A homer equaled 220 L (200 dry qt).
. “They had heated for themselves kilns,” LXXThomson; Vg, “they dried them.”
====

[[v4-11-33]]

^<<v4-11-33,33>>^ The meat was yet between their teeth, before it could be chewed, when Jehovah’s anger blazed against the people, and Jehovah began striking at the people with a very great slaughter.

[[v4-11-34]]

^<<v4-11-34,34>>^ The name of that place came to be called Kibʹroth-hat·taʹa·vah,^&#42;1^ because there they buried the people who showed selfish craving.

[NOTE]
====
. Meaning “Burial Places of the Craving.”
====

[[v4-11-35]]

^<<v4-11-35,35>>^ From Kibʹroth-hat·taʹa·vah the people pulled away for Ha·zeʹroth, and they continued in Ha·zeʹroth.

'''

xref:004-numbers/004-numbers-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numbers/004-numbers-012.adoc#v4-12-0[Próximo Capítulo &#62;]