include::./index.adoc[]

[[v4-23-0]]
=== Numbers, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-23-1]]

^<<v4-23-1,1>>^ Then Baʹlaam said to Baʹlak: “Build for me on this spot seven altars and make ready for me on this spot seven bulls and seven rams.”

[[v4-23-2]]

^<<v4-23-2,2>>^ Baʹlak immediately did just as Baʹlaam had spoken. After that Baʹlak and Baʹlaam offered up a bull and a ram on each altar.^&#42;1^

[NOTE]
====
. Lit., “on the altar,” MSamLXX; Sy, “on the altars.”
====

[[v4-23-3]]

^<<v4-23-3,3>>^ And Baʹlaam went on to say to Baʹlak: “Station yourself by your burnt offering, and let me go. Perhaps Jehovah will get in touch and meet with me. In that case whatever he will show me, I shall certainly tell you.” So he went to a bare hill.

[[v4-23-4]]

^<<v4-23-4,4>>^ When God got in touch with Baʹlaam, he then said to Him: “I set the seven altars in rows, and I proceeded to offer up a bull and a ram on each altar.”

[[v4-23-5]]

^<<v4-23-5,5>>^ Accordingly Jehovah^&#42;1^ put a word in the mouth of Baʹlaam and said: “Return to Baʹlak, and this is what you will speak.”

[NOTE]
====
. “Jehovah,” M; Sam, “the angel of Jehovah”; LXX, “God.”
====

[[v4-23-6]]

^<<v4-23-6,6>>^ So he returned to him, and, look! he and all the princes of Moʹab were stationed by his burnt offering.

[[v4-23-7]]

^<<v4-23-7,7>>^ Then he took up his proverbial utterance and said:
“From Aʹram^&#42;1^ Baʹlak the king of Moʹab tried to conduct me,
From the mountains of the east:
‘Do come, do curse Jacob for me.
Yes, do come, do denounce Israel.’

[NOTE]
====
. “Aram,” MSamSyVg; LXX, “Mesopotamia.”
====

[[v4-23-8]]

^<<v4-23-8,8>>^ How could I execrate those whom God^&#42;1^ has not execrated?
And how could I denounce those whom Jehovah has not denounced?

[NOTE]
====
. “God.” Heb., ʼEl; Gr., Kyʹri·os, “Jehovah”; Lat., Deʹus.
====

[[v4-23-9]]

^<<v4-23-9,9>>^ For from the top of the rocks I see them,^&#42;1^
And from the hills I behold them.
There as a people they keep tabernacling isolated,
And among the nations they^&#42;2^ do not reckon themselves.

[NOTE]
====
. Lit., “him,” that is, Jacob, or Israel, as a people.
. Lit., “he.”
====

[[v4-23-10]]

^<<v4-23-10,10>>^ Who has numbered the dust particles of Jacob,
And who has counted the fourth part^&#42;1^ of Israel?
Let my soul die the death of the upright ones,
And let my end turn out afterward like theirs.”^&#42;2^

[NOTE]
====
. Possibly to be read, “counted the myriads (tens of thousands).”
. “Theirs,” LXXSyVg; MSam, “his.”
====

[[v4-23-11]]

^<<v4-23-11,11>>^ At this Baʹlak said to Baʹlaam: “What have you done to me? It was in order to execrate my enemies that I took you, and here you have blessed them to the limit.”

[[v4-23-12]]

^<<v4-23-12,12>>^ In turn he answered and said: “Is it not whatever Jehovah may put in my mouth that I should take care to speak?”

[[v4-23-13]]

^<<v4-23-13,13>>^ Then Baʹlak said to him: “Do come, please, with me to another place from which you can see them. Only the extremity of them you will see, and you will not see all of them. And execrate them for me from there.”

[[v4-23-14]]

^<<v4-23-14,14>>^ So he took him to the field of Zoʹphim, to the top of Pisʹgah, and proceeded to build seven altars and to offer up a bull and a ram on each altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ After that he said to Baʹlak: “Station yourself here by your burnt offering, and, as for me, let me get in touch with him there.”

[[v4-23-16]]

^<<v4-23-16,16>>^ Subsequently Jehovah^&#42;1^ got in touch with Baʹlaam and put a word in his mouth and said: “Return to Baʹlak, and this is what you will speak.”

[NOTE]
====
. See vs 5 ftn.
====

[[v4-23-17]]

^<<v4-23-17,17>>^ So he came to him, and, look! he was stationed by his burnt offering, and the princes of Moʹab with him. Then Baʹlak said to him: “What has Jehovah spoken?”

[[v4-23-18]]

^<<v4-23-18,18>>^ At this he took up his proverbial utterance and said:
“Get up, Baʹlak, and listen.
Do give ear to me, O son of Zipʹpor.

[[v4-23-19]]

^<<v4-23-19,19>>^ God^&#42;1^ is not a man that he should tell lies,
Neither a son of mankind that he should feel regret.
Has he himself said it and will he not do it,
And has he spoken and will he not carry it out?

[NOTE]
====
. “God.” Heb., ʼEl; Gr., ho The·osʹ; Lat., Deʹus.
====

[[v4-23-20]]

^<<v4-23-20,20>>^ Look! I have been taken^&#42;1^ to bless,
And He has blessed,^&#42;2^ and I shall not reverse it.

[NOTE]
====
. “I have been taken,” LXXSyVg; M, “I have taken [the command].”
. “He has blessed,” M; SamLXX, “I shall bless.”
====

[[v4-23-21]]

^<<v4-23-21,21>>^ He has not looked upon any uncanny power^&#42;1^ against Jacob,
And no trouble has he seen against Israel.
Jehovah his God is with him,
And the loud hailing of a king is in his midst.

[NOTE]
====
. Or, “upon any state of taboo.”
====

[[v4-23-22]]

^<<v4-23-22,22>>^ God^&#42;1^ is bringing them^&#42;2^ out of Egypt.
The swift course like that of a wild bull^&#42;3^ is his.

[NOTE]
====
. “God.” Heb., ʼEl; Gr., The·osʹ; Lat., Deʹus.
. “Them,” MSamLXXSy; Vg, “him.”
. Or, “a buffalo.” LXX, “unicorn”; Vg, “rhi­noceros.”
====

[[v4-23-23]]

^<<v4-23-23,23>>^ For there is no unlucky spell against Jacob,
Nor any divination against Israel.
At this time it may be said respecting Jacob and Israel,
‘What has God^&#42;1^ worked out!’

[NOTE]
====
. “God.” MSam(Heb.), ʼEl; Gr., ho The·osʹ; Lat., Deʹus.
====

[[v4-23-24]]

^<<v4-23-24,24>>^ Behold, a people will get up like a lion,^&#42;1^
And like the lion^&#42;2^ it will lift itself up.
It will not lie down until it may eat prey,
And the blood of slain ones it will drink.”

[NOTE]
====
. “Like a lion.” Heb., kela·viʼʹ, the Asian lion.
. “And like the lion.” Heb., wekha·ʼariʹ, the African lion.
====

[[v4-23-25]]

^<<v4-23-25,25>>^ At this Baʹlak said to Baʹlaam: “If, on the one hand, you cannot execrate him at all, then, on the other hand, you should not bless him at all.”

[[v4-23-26]]

^<<v4-23-26,26>>^ In turn Baʹlaam answered and said to Baʹlak: “Did I not speak to you, saying, ‘All that Jehovah will speak is what I shall do’?”

[[v4-23-27]]

^<<v4-23-27,27>>^ Then Baʹlak said to Baʹlaam: “O come, please. Let me take you to still another place. Perhaps it will be right in the eyes of the &#91;true&#93; God so that you will certainly execrate him for me from there.”

[[v4-23-28]]

^<<v4-23-28,28>>^ With that Baʹlak took Baʹlaam to the top of Peʹor, which looks toward Je·shiʹmon.

[[v4-23-29]]

^<<v4-23-29,29>>^ Then Baʹlaam said to Baʹlak: “Build for me on this spot seven altars and make ready for me on this spot seven bulls and seven rams.”

[[v4-23-30]]

^<<v4-23-30,30>>^ So Baʹlak did just as Baʹlaam had said, and he went offering up a bull and a ram on each altar.

'''

xref:004-numbers/004-numbers-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numbers/004-numbers-024.adoc#v4-24-0[Próximo Capítulo &#62;]