include::./index.adoc[]

[[v4-20-0]]
=== Numbers, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-20-1]]

^<<v4-20-1,1>>^ And the sons of Israel, the entire assembly, proceeded to come into the wilderness of Zin in the first month, and the people took up dwelling in Kaʹdesh. It was there that Mirʹi·am died and there that she was buried.

[[v4-20-2]]

^<<v4-20-2,2>>^ Now there proved to be no water for the assembly, and they began to congregate themselves against Moses and Aaron.

[[v4-20-3]]

^<<v4-20-3,3>>^ And the people went quarreling with Moses^&#42;1^ and saying: “If only we had expired when our brothers expired before Jehovah!

[NOTE]
====
. Sy and one Heb. ms add “and Aaron.”
====

[[v4-20-4]]

^<<v4-20-4,4>>^ And why have YOU men brought Jehovah’s congregation into this wilderness for us and our beasts of burden to die there?

[[v4-20-5]]

^<<v4-20-5,5>>^ And why have YOU conducted us up out of Egypt to bring us into this evil place? It is no place of seed and figs and vines and pomegranates, and there is no water to drink.”

[[v4-20-6]]

^<<v4-20-6,6>>^ Then Moses and Aaron came from before the congregation to the entrance of the tent of meeting and fell upon their faces, and Jehovah’s glory began to appear to them.

[[v4-20-7]]

^<<v4-20-7,7>>^ Then Jehovah spoke to Moses, saying:

[[v4-20-8]]

^<<v4-20-8,8>>^ “Take the rod and call the assembly together, you and Aaron your brother, and YOU must speak to the crag before their eyes that it may indeed give^&#42;1^ its water; and you must bring out water for them from the crag^&#42;2^ and give the assembly and their beasts of burden drink.”

[NOTE]
====
. Lit., “and it must give.”
. Or, “the cliff (rock-mass).” Heb., has·seʹlaʽ; Gr., peʹtras; Syr., kiʼ·phaʼ; Lat., peʹtra.
====

[[v4-20-9]]

^<<v4-20-9,9>>^ So Moses took the rod from before Jehovah, just as he had commanded him.

[[v4-20-10]]

^<<v4-20-10,10>>^ After that Moses and Aaron called the congregation together before the crag, and he proceeded to say to them: “Hear, now, YOU rebels! Is it from this crag that we shall bring out water for YOU?”

[[v4-20-11]]

^<<v4-20-11,11>>^ With that Moses lifted his hand up and struck the crag with his rod twice; and much water began to come out, and the assembly and their beasts of burden began to drink.

[[v4-20-12]]

^<<v4-20-12,12>>^ Later Jehovah said to Moses and Aaron: “Because YOU did not show faith in me to sanctify me before the eyes of the sons of Israel, therefore YOU will not bring this congregation into the land that I shall certainly give them.”

[[v4-20-13]]

^<<v4-20-13,13>>^ These are the waters of Merʹi·bah,^&#42;1^ because the sons of Israel quarreled with Jehovah, so that he was sanctified^&#42;2^ among them.

[NOTE]
====
. Meaning “Quarreling; Strife; Contention.” Heb., Meri·vahʹ.
. Or, “so that he might be sanctified.”
====

[[v4-20-14]]

^<<v4-20-14,14>>^ Subsequently Moses sent messengers from Kaʹdesh to the king of Eʹdom: “This is what your brother Israel has said, ‘You yourself well know all the hardship that has overtaken us.

[[v4-20-15]]

^<<v4-20-15,15>>^ And our fathers proceeded to go down to Egypt, and we continued to dwell in Egypt many days; and the Egyptians began doing harm to us and our fathers.

[[v4-20-16]]

^<<v4-20-16,16>>^ Finally we cried out to Jehovah and he heard our voice and sent an angel and brought us out of Egypt; and here we are in Kaʹdesh, a city at the extremity of your territory.

[[v4-20-17]]

^<<v4-20-17,17>>^ Let us pass, please, through your land. We shall not pass through a field or a vineyard, and we shall not drink the water of a well. On the king’s road we shall march. We shall not bend toward the right or the left, until we shall pass through your territory.’”

[[v4-20-18]]

^<<v4-20-18,18>>^ However, Eʹdom said to him: “You must not pass through me, for fear I may come out with the sword to meet you.”

[[v4-20-19]]

^<<v4-20-19,19>>^ In turn the sons of Israel said to him: “By the highway we shall go up; and if I and my livestock should drink your water, I shall also certainly give the value of it. I want nothing more than to pass through on my feet.”

[[v4-20-20]]

^<<v4-20-20,20>>^ Still he said: “You must not pass through.” With that Eʹdom came on out to encounter him with a great many people and a strong hand.

[[v4-20-21]]

^<<v4-20-21,21>>^ So Eʹdom refused to grant Israel to pass through his territory. Hence Israel turned away from him.

[[v4-20-22]]

^<<v4-20-22,22>>^ And the sons of Israel, the entire assembly, proceeded to pull away from Kaʹdesh and come to Mount Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Then Jehovah said this to Moses and Aaron in Mount Hor by the border of the land of Eʹdom:

[[v4-20-24]]

^<<v4-20-24,24>>^ “Aaron will be gathered to his people, for he will not enter into the land that I shall certainly give to the sons of Israel, on the ground that YOU men rebelled against my order respecting the waters of Merʹi·bah.

[[v4-20-25]]

^<<v4-20-25,25>>^ Take Aaron and El·e·aʹzar his son and bring them up into Mount Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ And strip Aaron of his garments, and you must clothe with them El·e·aʹzar his son; and Aaron will be gathered and must die there.”

[[v4-20-27]]

^<<v4-20-27,27>>^ So Moses did just as Jehovah had commanded; and before the eyes of all the assembly they went climbing Mount Hor.

[[v4-20-28]]

^<<v4-20-28,28>>^ Then Moses stripped Aaron of his garments and clothed El·e·aʹzar his son with them, after which Aaron died there on the top of the mountain. And Moses and El·e·aʹzar came on down from the mountain.

[[v4-20-29]]

^<<v4-20-29,29>>^ And all the assembly got to see that Aaron had expired, and all the house of Israel continued weeping for Aaron thirty days.

'''

xref:004-numbers/004-numbers-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numbers/004-numbers-021.adoc#v4-21-0[Próximo Capítulo &#62;]