include::./index.adoc[]

[[v4-15-0]]
=== Numbers, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-15-1]]

^<<v4-15-1,1>>^ And Jehovah spoke further to Moses, saying:

[[v4-15-2]]

^<<v4-15-2,2>>^ “Speak to the sons of Israel, and you must say to them, ‘When YOU eventually come into the land of YOUR dwelling places, which I am giving YOU,

[[v4-15-3]]

^<<v4-15-3,3>>^ and YOU must render up an offering made by fire to Jehovah, a burnt offering or a sacrifice to perform a special vow or voluntarily^&#42;1^ or during YOUR seasonal festivals, in order to make a restful odor to Jehovah, from the herd or from the flock;

[NOTE]
====
. Lit., “in free will.”
====

[[v4-15-4]]

^<<v4-15-4,4>>^ the one presenting his offering must also present to Jehovah a grain offering of fine flour, a tenth of an eʹphah,^&#42;1^ moistened with a fourth of a hin of oil.

[NOTE]
====
. “A tenth of an ephah,” LXXVg; MSamSy, “a tenth.” See App 8A.
====

[[v4-15-5]]

^<<v4-15-5,5>>^ And you should render up wine as a drink offering, the fourth of a hin, together with the burnt offering or for the sacrifice of each male lamb.

[[v4-15-6]]

^<<v4-15-6,6>>^ Or for a ram you should render up a grain offering of two tenths of fine flour, moistened with a third of a hin of oil.

[[v4-15-7]]

^<<v4-15-7,7>>^ And you should present wine as a drink offering, a third of a hin, as a restful odor to Jehovah.

[[v4-15-8]]

^<<v4-15-8,8>>^ “‘But in case you should render up a male of the herd^&#42;1^ as a burnt offering or a sacrifice to perform a special vow or communion sacrifices to Jehovah,

[NOTE]
====
. Lit., “son of the herd.”
====

[[v4-15-9]]

^<<v4-15-9,9>>^ one must also present together with the male of the herd a grain offering of three tenths of fine flour, moistened with half a hin of oil.

[[v4-15-10]]

^<<v4-15-10,10>>^ And you should present wine as a drink offering, half a hin, as an offering made by fire, of a restful odor to Jehovah.

[[v4-15-11]]

^<<v4-15-11,11>>^ This is the way it should be done for each bull or for each ram or for one head among the male lambs or among the goats.

[[v4-15-12]]

^<<v4-15-12,12>>^ Whatever may be the number that YOU may render up, that is the way YOU should do for each one according to the number of them.

[[v4-15-13]]

^<<v4-15-13,13>>^ Every native should render up these in this way in presenting an offering made by fire, of a restful odor to Jehovah.

[[v4-15-14]]

^<<v4-15-14,14>>^ “‘And in case there should be residing as an alien with YOU an alien resident or one who is in YOUR midst for generations of YOU, and he must render up an offering made by fire, of a restful odor to Jehovah, just as YOU should do, so he should do.

[[v4-15-15]]

^<<v4-15-15,15>>^ YOU who are of the congregation and the alien resident who is residing as an alien will have one statute. It will be a statute to time indefinite for YOUR generations. The alien resident should prove to be the same as YOU^&#42;1^ before Jehovah.

[NOTE]
====
. Lit., “Like you, like the alien resident, he should prove to be.”
====

[[v4-15-16]]

^<<v4-15-16,16>>^ There should prove to be one law and one judicial decision for YOU and for the alien resident who is residing as an alien with YOU.’”

[[v4-15-17]]

^<<v4-15-17,17>>^ And Jehovah went on to speak to Moses, saying:

[[v4-15-18]]

^<<v4-15-18,18>>^ “Speak to the sons of Israel, and you must say to them, ‘On YOUR coming into the land where I am bringing YOU,

[[v4-15-19]]

^<<v4-15-19,19>>^ it must also occur that when YOU eat any of the bread of the land, YOU should make a contribution to Jehovah.

[[v4-15-20]]

^<<v4-15-20,20>>^ YOU should make a contribution of the firstfruits of YOUR coarse meal as ring-shaped cakes. Like the contribution of a threshing floor is the way YOU should contribute it.

[[v4-15-21]]

^<<v4-15-21,21>>^ Some of the firstfruits of YOUR coarse meal YOU should give as a contribution to Jehovah throughout YOUR generations.

[[v4-15-22]]

^<<v4-15-22,22>>^ “‘Now in case YOU should make a mistake and not do all these commandments, which Jehovah has spoken to Moses,

[[v4-15-23]]

^<<v4-15-23,23>>^ all that Jehovah has commanded YOU by means of Moses from the day that Jehovah commanded and onward for YOUR generations,

[[v4-15-24]]

^<<v4-15-24,24>>^ it must then occur that if it has been done far from the eyes of the assembly by mistake, the whole assembly must then render up one young bull as a burnt offering for a restful odor to Jehovah, and its grain offering and its drink offering according to the regular procedure, and one kid of the goats as a sin offering.

[[v4-15-25]]

^<<v4-15-25,25>>^ And the priest must make atonement for the whole assembly of the sons of Israel, and it must be forgiven them; because it was a mistake, and they, for their part, brought as their offering an offering made by fire to Jehovah and their sin offering before Jehovah for their mistake.

[[v4-15-26]]

^<<v4-15-26,26>>^ And it must be forgiven the whole assembly of the sons of Israel and the alien resident who is residing as an alien in their midst, because it was by mistake on the part of all the people.

[[v4-15-27]]

^<<v4-15-27,27>>^ “‘And if any soul should sin by mistake, then he must present a female goat in its first year for a sin offering.

[[v4-15-28]]

^<<v4-15-28,28>>^ And the priest must make atonement for the soul who made a mistake by a sin unintentionally before Jehovah, so as to make atonement for it, and it must be forgiven him.

[[v4-15-29]]

^<<v4-15-29,29>>^ As to the native among the sons of Israel and the alien resident who is residing as an alien in their midst, there should prove to be one law for YOU as respects doing something unintentionally.

[[v4-15-30]]

^<<v4-15-30,30>>^ “‘But the soul that does something deliberately,^&#42;1^ whether he is a native or an alien resident, he speaking abusively of Jehovah, in that case that soul must be cut off from among his people.

[NOTE]
====
. Lit., “with uplifted hand,” that is, openly, proudly, purposely.
====

[[v4-15-31]]

^<<v4-15-31,31>>^ Because it is Jehovah’s word that he has despised and his commandment that he has broken, that soul should be cut off without fail. His own error is upon him.’”

[[v4-15-32]]

^<<v4-15-32,32>>^ While the sons of Israel were continuing in the wilderness, they once found a man collecting pieces of wood on the sabbath day.

[[v4-15-33]]

^<<v4-15-33,33>>^ Then those who found him collecting pieces of wood brought him up to Moses and Aaron and the whole assembly.

[[v4-15-34]]

^<<v4-15-34,34>>^ So they committed him into custody, because it had not been distinctly stated what should be done to him.

[[v4-15-35]]

^<<v4-15-35,35>>^ In time Jehovah said to Moses: “Without fail the man should be put to death, the whole assembly pelting^&#42;1^ him with stones outside the camp.”

[NOTE]
====
. “Pelting.” In Heb. this is a verb in the infinitive absolute, indefinite as to time.
====

[[v4-15-36]]

^<<v4-15-36,36>>^ Accordingly the whole assembly brought him forth outside the camp and pelted him with stones so that he died, just as Jehovah had commanded Moses.

[[v4-15-37]]

^<<v4-15-37,37>>^ And Jehovah went on to say this to Moses:

[[v4-15-38]]

^<<v4-15-38,38>>^ “Speak to the sons of Israel, and you must say to them that they must make for themselves fringed edges upon the skirts of their garments throughout their generations, and they must put a blue string above the fringed edge of the skirt,

[[v4-15-39]]

^<<v4-15-39,39>>^ ‘And it must serve as a fringed edge for YOU, and YOU must see it and remember all the commandments of Jehovah and do them, and YOU must not go about following YOUR hearts and YOUR eyes, which YOU are following in immoral intercourse.^&#42;1^

[NOTE]
====
. Or, “you are committing fornication.” Heb., zo·nimʹ; Lat., for·ni·canʹtes.
====

[[v4-15-40]]

^<<v4-15-40,40>>^ The purpose is that YOU may remember and may certainly do all my commandments and indeed prove to be holy to YOUR God.

[[v4-15-41]]

^<<v4-15-41,41>>^ I am Jehovah YOUR God, who have brought YOU out of the land of Egypt in order to prove myself YOUR God. I am Jehovah YOUR God.’”

'''

xref:004-numbers/004-numbers-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numbers/004-numbers-016.adoc#v4-16-0[Próximo Capítulo &#62;]