include::./index.adoc[]

[[v4-21-0]]
=== Numbers, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-21-1]]

^<<v4-21-1,1>>^ Now the Caʹnaan·ite the king of Aʹrad, who dwelt in the Negʹeb,^&#42;1^ got to hear that Israel had come by the way of Athʹa·rim, and he began to fight with Israel and carry away some of them as captives.

[NOTE]
====
. Or, “the south,” that is, the southern part of the Promised Land.
====

[[v4-21-2]]

^<<v4-21-2,2>>^ Consequently Israel made a vow to Jehovah and said: “If you will without fail give this people into my hand, I shall also certainly devote their cities to destruction.”

[[v4-21-3]]

^<<v4-21-3,3>>^ So Jehovah listened to Israel’s voice and gave the Caʹnaan·ites over; and they devoted them and their cities to destruction. Hence they called the name of the place Horʹmah.^&#42;1^

[NOTE]
====
. Meaning “A Devoting to Destruction.” Heb., Chor·mahʹ; Gr., A·naʹthe·ma; Vg, “Horma, that is, anath­ema.”
====

[[v4-21-4]]

^<<v4-21-4,4>>^ While they continued trekking from Mount Hor by the way of the Red Sea to go around the land of Eʹdom, the soul of the people began tiring out because of the way.

[[v4-21-5]]

^<<v4-21-5,5>>^ And the people kept speaking against God and Moses: “Why have YOU brought us up out of Egypt to die in the wilderness? For there is no bread and no water, and our soul has come to abhor the contemptible bread.”

[[v4-21-6]]

^<<v4-21-6,6>>^ So Jehovah sent poisonous serpents^&#42;1^ among the people, and they kept biting the people, so that many people of Israel died.

[NOTE]
====
. Or, “fiery (inflammation-causing) serpents.” LXX, “death-dealing serpents”; Vg, “fiery serpents.” See vs 8.
====

[[v4-21-7]]

^<<v4-21-7,7>>^ Finally the people came to Moses and said: “We have sinned, because we have spoken against Jehovah and against you. Intercede with Jehovah that he may remove the serpents from upon us.” And Moses went interceding in behalf of the people.

[[v4-21-8]]

^<<v4-21-8,8>>^ Then Jehovah said to Moses: “Make for yourself a fiery snake^&#42;1^ and place it upon a signal pole. And it must occur that when anyone has been bitten, he then has to look at it and so must keep alive.”

[NOTE]
====
. Lit., “a fiery [snake].” Heb., sa·raphʹ, “poisonous” in vs 6; here M omits “snake”; Gr., oʹphin, “serpent”; Lat., ser·penʹtem.
====

[[v4-21-9]]

^<<v4-21-9,9>>^ Moses at once made a serpent of copper and placed it upon the signal pole; and it did occur that if a serpent had bitten a man and he gazed at the copper serpent, he then kept alive.

[[v4-21-10]]

^<<v4-21-10,10>>^ After that the sons of Israel pulled away and encamped in Oʹboth.

[[v4-21-11]]

^<<v4-21-11,11>>^ Then they pulled away from Oʹboth and encamped in Iʹye-abʹa·rim,^&#42;1^ in the wilderness that is toward the front of Moʹab, toward the rising of the sun.

[NOTE]
====
. Meaning “Ruins of the Fords (Crossings); Ruins of the Borderland (Regions Beyond).” Its exact location is uncertain, but it was near the torrent valley of Zered.
====

[[v4-21-12]]

^<<v4-21-12,12>>^ From there they pulled away and took up camping by the torrent valley of Zeʹred.

[[v4-21-13]]

^<<v4-21-13,13>>^ From there they pulled away and went camping in the region of the Arʹnon, which is in the wilderness that extends from the border of the Amʹor·ites; for the Arʹnon is the boundary of Moʹab, between Moʹab and the Amʹor·ites.

[[v4-21-14]]

^<<v4-21-14,14>>^ That is why it is said in the book of the Wars of Jehovah:
“Vaʹheb^&#42;1^ in Suʹphah and the torrent valleys of Arʹnon,^&#42;2^

[NOTE]
====
. Apparently an unknown place near the torrent valley of Arnon.
. “As he did in the Red Sea, so he will do in the torrents of Arnon,” Vg.
====

[[v4-21-15]]

^<<v4-21-15,15>>^ and the mouth of the torrent valleys, which has bent itself toward the seat of Ar and has leaned against the border of Moʹab.”

[[v4-21-16]]

^<<v4-21-16,16>>^ Next from there on to Beʹer.^&#42;1^ This is the well about which Jehovah said to Moses: “Gather the people, and let me give them water.”

[NOTE]
====
. Meaning “Well; Pit.”
====

[[v4-21-17]]

^<<v4-21-17,17>>^ At that time Israel proceeded to sing this song:
“Spring up, O well! Respond to it, YOU people!

[[v4-21-18]]

^<<v4-21-18,18>>^ A well, princes dug it. The nobles^&#42;1^ of the people excavated it,
With a commander’s staff, with their own staffs.”^&#42;2^
Then from the wilderness on to Matʹta·nah.

[NOTE]
====
. Or, “generous givers.”
. Or, “with a commander, with their rulers.”
====

[[v4-21-19]]

^<<v4-21-19,19>>^ And from Matʹta·nah on to Na·halʹi·el, and from Na·halʹi·el on to Baʹmoth.

[[v4-21-20]]

^<<v4-21-20,20>>^ And from Baʹmoth on to the valley that is in the field of Moʹab, at the head of Pisʹgah, and it projects over toward the face of Je·shiʹmon.^&#42;1^

[NOTE]
====
. “The desert (wilderness),” LXXVg.
====

[[v4-21-21]]

^<<v4-21-21,21>>^ Israel now sent messengers to Siʹhon the king of the Amʹor·ites, saying:

[[v4-21-22]]

^<<v4-21-22,22>>^ “Let me pass through your land. We shall not turn off into a field or a vineyard. We shall drink water of no well. On the king’s road we shall march until we pass through your territory.”

[[v4-21-23]]

^<<v4-21-23,23>>^ And Siʹhon did not allow Israel to pass through his territory, but Siʹhon gathered all his people and went out to meet Israel in the wilderness, and came to Jaʹhaz and began fighting with Israel.

[[v4-21-24]]

^<<v4-21-24,24>>^ At that Israel struck him with the edge of the sword and took possession of his land from the Arʹnon to the Jabʹbok, near the sons of Amʹmon; because Jaʹzer^&#42;1^ is the border of the sons of Amʹmon.

[NOTE]
====
. “Jazer,” LXX, probably reflecting the original text. (Compare vs 32.) Lit., “strong.” Heb., ʽaz; Vg, “held by a strong garrison.”
====

[[v4-21-25]]

^<<v4-21-25,25>>^ So Israel took all these cities, and Israel began dwelling in all the cities of the Amʹor·ites, in Heshʹbon and all its dependent towns.^&#42;1^

[NOTE]
====
. Lit., “all its daughters.”
====

[[v4-21-26]]

^<<v4-21-26,26>>^ For Heshʹbon was the city of Siʹhon. He was the king of the Amʹor·ites, and it was he who fought with the king of Moʹab formerly and went taking all his land out of his hand as far as the Arʹnon.

[[v4-21-27]]

^<<v4-21-27,27>>^ That is why the sayers of mock verses^&#42;1^ would say:
“Come to Heshʹbon.
Let the city of Siʹhon be built and be proved firmly set up.

[NOTE]
====
. Or, “sayers of proverbs; rhapsodists.”
====

[[v4-21-28]]

^<<v4-21-28,28>>^ For a fire has come out of Heshʹbon, a flame from the town of Siʹhon.
It has consumed Ar of Moʹab,^&#42;1^ the owners of the high places of the Arʹnon.

[NOTE]
====
. “Consumed Ar of the Moabites,” Vg; LXX, “consumed as far as Moab.”
====

[[v4-21-29]]

^<<v4-21-29,29>>^ Woe to you, Moʹab! You will certainly perish, O people of Cheʹmosh!
He will certainly give his sons as escaped ones and his daughters in the captivity to the king of the Amʹor·ites, Siʹhon.

[[v4-21-30]]

^<<v4-21-30,30>>^ So let us shoot at them.
Heshʹbon will certainly perish up to Diʹbon,
And the women^&#42;1^ up to Noʹphah, the men up to Medʹe·ba.”^&#42;2^

[NOTE]
====
. “The women,” LXX.
. “And the . . . Medeba,” according to a textual criticism of the Sopherim who marked this line with an extraordinary point. Ignoring the extraordinary point, the text would read: “so let us lay it desolate to Nophah, which is near Medeba.” See App 2A.
====

[[v4-21-31]]

^<<v4-21-31,31>>^ And Israel began to dwell in the land of the Amʹor·ites.

[[v4-21-32]]

^<<v4-21-32,32>>^ Then Moses sent some to spy on Jaʹzer. So they captured its dependent towns and dispossessed the Amʹor·ites who were there.

[[v4-21-33]]

^<<v4-21-33,33>>^ After that they turned and went up by the way of Baʹshan. At this Og the king of Baʹshan came out to meet them, he and all his people, to the battle of Edʹre·i.

[[v4-21-34]]

^<<v4-21-34,34>>^ Jehovah now said to Moses: “Do not be afraid of him, for into your hand I shall certainly give him and all his people and his land; and you must do to him just as you did to Siʹhon, the king of the Amʹor·ites, who used to dwell in Heshʹbon.”

[[v4-21-35]]

^<<v4-21-35,35>>^ So they went striking him and his sons and all his people, until there was no survivor remaining to him; and they went taking possession of his land.

'''

xref:004-numbers/004-numbers-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numbers/004-numbers-022.adoc#v4-22-0[Próximo Capítulo &#62;]