include::./index.adoc[]

[[v4-14-0]]
=== Numbers, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-14-1]]

^<<v4-14-1,1>>^ Then all the assembly raised their voice, and the people continued giving vent to their voice and weeping all through that night.

[[v4-14-2]]

^<<v4-14-2,2>>^ And all the sons of Israel began to murmur against Moses and Aaron, and all the assembly began to say against them: “If only we had died in the land of Egypt, or if only we had died in this wilderness!

[[v4-14-3]]

^<<v4-14-3,3>>^ And why is Jehovah bringing us to this land to fall by the sword? Our wives and our little ones will become plunder. Is it not better for us to return to Egypt?”

[[v4-14-4]]

^<<v4-14-4,4>>^ They even went to saying to one another: “Let us appoint a head, and let us return to Egypt!”

[[v4-14-5]]

^<<v4-14-5,5>>^ At this Moses and Aaron fell upon their faces before all the congregation of the assembly of the sons of Israel.

[[v4-14-6]]

^<<v4-14-6,6>>^ And Joshua the son of Nun and Caʹleb the son of Je·phunʹneh, who were of those who spied out the land, ripped their garments apart,

[[v4-14-7]]

^<<v4-14-7,7>>^ and they proceeded to say this to all the assembly of the sons of Israel: “The land that we passed through to spy it out is a very, very good land.

[[v4-14-8]]

^<<v4-14-8,8>>^ If Jehovah has found delight in us, then he will certainly bring us into this land and give it to us, a land that is flowing with milk and honey.

[[v4-14-9]]

^<<v4-14-9,9>>^ Only against Jehovah do not rebel; and YOU, do not YOU fear the people of the land, for they are bread to us. Their shelter has turned away from over them, and Jehovah is with us. Do not fear them.”

[[v4-14-10]]

^<<v4-14-10,10>>^ However, all the assembly talked of pelting them with stones. And Jehovah’s glory appeared on the tent of meeting to all the sons of Israel.

[[v4-14-11]]

^<<v4-14-11,11>>^ Finally Jehovah said to Moses: “How long will this people treat me without respect, and how long will they not put faith in me for all the signs that I performed in among them?

[[v4-14-12]]

^<<v4-14-12,12>>^ Let me strike them with pestilence and drive them away, and let me make you a nation greater and mightier than they are.”

[[v4-14-13]]

^<<v4-14-13,13>>^ But Moses said to Jehovah: “Then the Egyptians will be bound to hear that you by your power have led this people up out of their midst.

[[v4-14-14]]

^<<v4-14-14,14>>^ And they will be bound to tell it to the inhabitants of this land. They have heard that you are Jehovah in among this people, who has appeared face to face.^&#42;1^ You are Jehovah, and your cloud is standing over them, and you are going before them in the pillar of cloud by day and in the pillar of fire by night.

[NOTE]
====
. Lit., “eye to eye.” Heb., ʽaʹyin beʽaʹyin.
====

[[v4-14-15]]

^<<v4-14-15,15>>^ Were you to put this people to death as one man, then the nations who have heard of your fame would certainly say this,

[[v4-14-16]]

^<<v4-14-16,16>>^ ‘Because of Jehovah’s not being able to bring this people into the land about which he swore to them he proceeded to slaughter them in the wilderness.’

[[v4-14-17]]

^<<v4-14-17,17>>^ And now, please, let your power^&#42;1^ become great, O Jehovah,^&#42;2^ just as you have spoken, saying,

[NOTE]
====
. “Your power,” LXXSy; M, “power.”
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v4-14-18]]

^<<v4-14-18,18>>^ ‘Jehovah, slow to anger and abundant in loving-kindness,^&#42;1^ pardoning error and transgression, but by no means will he give exemption from punishment, bringing punishment for the error of the fathers upon sons, upon the third generation and upon the fourth generation.’

[NOTE]
====
. Or, “loyal love.”
====

[[v4-14-19]]

^<<v4-14-19,19>>^ Forgive, please, the error of this people according to the greatness of your loving-kindness, and just as you have pardoned this people from Egypt onward until now.”

[[v4-14-20]]

^<<v4-14-20,20>>^ Then Jehovah said: “I do forgive according to your word.

[[v4-14-21]]

^<<v4-14-21,21>>^ And, on the other hand, as I live, all the earth will be filled with the glory of Jehovah.

[[v4-14-22]]

^<<v4-14-22,22>>^ But all the men who have been seeing my glory and my signs that I have performed in Egypt and in the wilderness and yet kept testing me these ten times, and have not listened to my voice,

[[v4-14-23]]

^<<v4-14-23,23>>^ will never see^&#42;1^ the land about which I swore to their fathers, yes, all those treating me without respect will not see it.

[NOTE]
====
. Lit., “[I swear] if they will see.”
====

[[v4-14-24]]

^<<v4-14-24,24>>^ As for my servant Caʹleb, because a different spirit has proved to be with him and he kept following wholly after me, I shall certainly bring him into the land where he has gone, and his offspring will take possession of it.

[[v4-14-25]]

^<<v4-14-25,25>>^ While the A·malʹek·ites and the Caʹnaan·ites are dwelling in the low plain, YOU people make a turn tomorrow and pull away to march to the wilderness by way of the Red Sea.”

[[v4-14-26]]

^<<v4-14-26,26>>^ And Jehovah went on to speak to Moses and Aaron, saying:

[[v4-14-27]]

^<<v4-14-27,27>>^ “How long will this evil assembly have this murmuring that they are carrying on against me? I have heard the murmurings of the sons of Israel that they are murmuring against me.

[[v4-14-28]]

^<<v4-14-28,28>>^ Say to them, ‘“As I live,” is the utterance of Jehovah, “if I shall not do to YOU just that way as YOU have spoken in my ears!

[[v4-14-29]]

^<<v4-14-29,29>>^ In this wilderness YOUR carcasses will fall, yes, all YOUR registered ones of all YOUR number from twenty years old upward, YOU who have murmured against me.

[[v4-14-30]]

^<<v4-14-30,30>>^ As for YOU, YOU will not enter into the land in which I lifted up my hand &#91;in oath&#93; to reside with YOU, except Caʹleb the son of Je·phunʹneh and Joshua the son of Nun.

[[v4-14-31]]

^<<v4-14-31,31>>^ “‘“And YOUR little ones who YOU said would become plunder, these also I shall certainly bring in, and they will indeed know the land that YOU have rejected.

[[v4-14-32]]

^<<v4-14-32,32>>^ But the carcasses of YOU yourselves will fall in this wilderness.

[[v4-14-33]]

^<<v4-14-33,33>>^ And YOUR sons will become shepherds^&#42;1^ in the wilderness forty years, and they will have to answer for YOUR acts of fornication,^&#42;2^ until YOUR carcasses come to their end in the wilderness.

[NOTE]
====
. “Shepherds,” M; Lat., vaʹgi, “vagabonds; wanderers.”
. “Your acts of fornication.” Heb., zenu·theh·khemʹ; Gr., por·neiʹan; Lat., for·ni·ca·ti·oʹnem. See App 5A.
====

[[v4-14-34]]

^<<v4-14-34,34>>^ By the number of the days that YOU spied out the land, forty days, a day for a year, a day for a year, YOU will answer for YOUR errors forty years, as YOU must know what my being estranged means.

[[v4-14-35]]

^<<v4-14-35,35>>^ “‘“I Jehovah have spoken if this is not what I shall do to all this evil assembly, those who have gathered together against me: In this wilderness they will come to their end, and there they will die.

[[v4-14-36]]

^<<v4-14-36,36>>^ And the men whom Moses sent to spy out the land and who, when they returned, began making the whole assembly murmur against him,^&#42;1^ by bringing forth a bad report against the land,

[NOTE]
====
. “Had made the whole multitude murmur against him,” Vg.
====

[[v4-14-37]]

^<<v4-14-37,37>>^ yes, the men bringing forth the bad report about the land will die by the scourge before Jehovah.

[[v4-14-38]]

^<<v4-14-38,38>>^ But Joshua the son of Nun and Caʹleb the son of Je·phunʹneh will certainly live on, of those men who went to spy out the land.”’”

[[v4-14-39]]

^<<v4-14-39,39>>^ When Moses proceeded to speak these words to all the sons of Israel, then the people began to mourn a great deal.

[[v4-14-40]]

^<<v4-14-40,40>>^ Moreover, they got up early in the morning and tried to go up to the top of the mountain, saying: “Here we are, and we have to go up to the place that Jehovah mentioned. For we have sinned.”

[[v4-14-41]]

^<<v4-14-41,41>>^ But Moses said: “Why is it that YOU are passing beyond the order of Jehovah? But that will not succeed.

[[v4-14-42]]

^<<v4-14-42,42>>^ Do not go up, because Jehovah is not in YOUR midst, that YOU may not be defeated before YOUR enemies.

[[v4-14-43]]

^<<v4-14-43,43>>^ For the A·malʹek·ites and the Caʹnaan·ites are there before YOU; and YOU are certain to fall by the sword, because, for the reason that YOU turned back from following Jehovah, Jehovah will not continue with YOU.”

[[v4-14-44]]

^<<v4-14-44,44>>^ However, they presumed to go up to the top of the mountain, but the ark of Jehovah’s covenant and Moses did not move away from the midst of the camp.

[[v4-14-45]]

^<<v4-14-45,45>>^ Then the A·malʹek·ites and the Caʹnaan·ites who were dwelling in that mountain came on down and began striking them and went scattering them as far as Horʹmah.

'''

xref:004-numbers/004-numbers-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numbers/004-numbers-015.adoc#v4-15-0[Próximo Capítulo &#62;]