include::./index.adoc[]

[[v4-18-0]]
=== Numbers, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-18-1]]

^<<v4-18-1,1>>^ And Jehovah proceeded to say to Aaron: “You and your sons and the house of your father with you will answer for error against the sanctuary, and you and your sons with you will answer for error against YOUR priesthood.

[[v4-18-2]]

^<<v4-18-2,2>>^ And bring near, also, your brothers of the tribe of Leʹvi, the clan of your father, with you, that they may be joined to you and may minister to you, to both you and your sons with you, before the tent of the Testimony.

[[v4-18-3]]

^<<v4-18-3,3>>^ And they must keep their obligation to you and their obligation to the entire tent. Only to the utensils of the holy place and to the altar they must not come near that they may not die, neither they nor YOU men.

[[v4-18-4]]

^<<v4-18-4,4>>^ And they must be joined to you and must keep their obligation to the tent of meeting as respects all the service of the tent, and no stranger may come near to YOU men.

[[v4-18-5]]

^<<v4-18-5,5>>^ And YOU must keep YOUR obligation to the holy place and YOUR obligation to the altar, that no further indignation may occur against the sons of Israel.

[[v4-18-6]]

^<<v4-18-6,6>>^ And I, look! I have taken YOUR brothers, the Levites, from among the sons of Israel, as a gift for YOU, as those given to Jehovah to carry on the service of the tent of meeting.

[[v4-18-7]]

^<<v4-18-7,7>>^ And you and your sons with you should safeguard YOUR priesthood as regards every concern of the altar and as regards what is inside the curtain; and YOU men must render service. As a service of gift I shall give YOUR priesthood, and the stranger drawing near should be put to death.”

[[v4-18-8]]

^<<v4-18-8,8>>^ And Jehovah spoke further to Aaron: “As for me, look! I have given you the custody of the contributions made to me. Of all the holy things of the sons of Israel I have given them to you and to your sons as a portion, as an allowance to time indefinite.

[[v4-18-9]]

^<<v4-18-9,9>>^ This should become yours out of the most holy things, out of the offering made by fire, every offering of theirs together with every grain offering of theirs and every sin offering of theirs and every guilt offering of theirs, which they will return to me. It is something most holy for you and for your sons.

[[v4-18-10]]

^<<v4-18-10,10>>^ In a most holy place you should eat it. Every male should eat it. It should become something holy to you.

[[v4-18-11]]

^<<v4-18-11,11>>^ And this belongs to you: the contribution of their gift together with all the wave offerings of the sons of Israel. I have given them to you and your sons and your daughters with you, as an allowance to time indefinite. Everyone clean in your house may eat it.

[[v4-18-12]]

^<<v4-18-12,12>>^ “All the best^&#42;1^ of the oil and all the best of the new wine and the grain, their firstfruits, which they will give to Jehovah, I have given them to you.

[NOTE]
====
. Lit., “fat.”
====

[[v4-18-13]]

^<<v4-18-13,13>>^ The first ripe fruits of all that is on their land, which they will bring to Jehovah, yours it should become. Everyone clean in your house may eat it.

[[v4-18-14]]

^<<v4-18-14,14>>^ “Every devoted thing^&#42;1^ in Israel should become yours.

[NOTE]
====
. That is, everything made sacred to God by a ban.
====

[[v4-18-15]]

^<<v4-18-15,15>>^ “Everything opening the womb, of every sort of flesh, which they will present to Jehovah, among man and among beast, should become yours. However, you should without fail redeem the firstborn of mankind; and the firstborn of the unclean beast you should redeem.

[[v4-18-16]]

^<<v4-18-16,16>>^ And with a redemption price for it from a month old onward you should redeem it, by the estimated value, five silver shekels by the shekel of the holy place. It is twenty geʹrahs.

[[v4-18-17]]

^<<v4-18-17,17>>^ Only the firstborn bull or firstborn male lamb or firstborn goat you should not redeem. They are something holy. Their blood you should sprinkle upon the altar, and their fat you should make smoke as an offering made by fire for a restful odor to Jehovah.

[[v4-18-18]]

^<<v4-18-18,18>>^ And their flesh should become yours. Like the breast of the wave offering and like the right leg, it should become yours.

[[v4-18-19]]

^<<v4-18-19,19>>^ All the holy contributions, which the sons of Israel will contribute to Jehovah, I have given to you and your sons and your daughters with you, as an allowance to time indefinite. It is a covenant of salt to time indefinite before Jehovah for you and your offspring with you.”

[[v4-18-20]]

^<<v4-18-20,20>>^ And Jehovah went on to say to Aaron: “In their land you will not have an inheritance, and no share will become yours in their midst. I am your share and your inheritance in the midst of the sons of Israel.

[[v4-18-21]]

^<<v4-18-21,21>>^ “And to the sons of Leʹvi, look! I have given every tenth part in Israel as an inheritance in return for their service that they are carrying on, the service of the tent of meeting.

[[v4-18-22]]

^<<v4-18-22,22>>^ And the sons of Israel should no more come near to the tent of meeting to incur sin so as to die.

[[v4-18-23]]

^<<v4-18-23,23>>^ And the Levites themselves must carry on the service of the tent of meeting, and they are the ones who should answer for their error. It is a statute to time indefinite during YOUR generations that in the midst of the sons of Israel they should not get possession of an inheritance.

[[v4-18-24]]

^<<v4-18-24,24>>^ For the tenth part of the sons of Israel, which they will contribute to Jehovah as a contribution, I have given to the Levites as an inheritance. That is why I have said to them, ‘In the midst of the sons of Israel they should not get possession of an inheritance.’”

[[v4-18-25]]

^<<v4-18-25,25>>^ Then Jehovah spoke to Moses, saying:

[[v4-18-26]]

^<<v4-18-26,26>>^ “And you should speak to the Levites, and you must say to them, ‘YOU will receive from the sons of Israel the tenth part that I have given to YOU from them for YOUR inheritance, and YOU must contribute from it as a contribution to Jehovah a tenth part of the tenth part.

[[v4-18-27]]

^<<v4-18-27,27>>^ And it must be reckoned to YOU as YOUR contribution, like the grain of the threshing floor and like the full produce of the wine or oil press.

[[v4-18-28]]

^<<v4-18-28,28>>^ In this way YOU yourselves also will contribute a contribution to Jehovah from all YOUR tenth parts that YOU will receive from the sons of Israel, and from them YOU must give the contribution to Jehovah to Aaron the priest.

[[v4-18-29]]

^<<v4-18-29,29>>^ From all the gifts to YOU, YOU will contribute every sort of contribution to Jehovah, of the very best of it, as some holy thing from them.’

[[v4-18-30]]

^<<v4-18-30,30>>^ “And you must say to them, ‘When YOU contribute the best of them, then it will certainly be reckoned to the Levites as the produce of the threshing floor and as the produce of the wine or oil press.

[[v4-18-31]]

^<<v4-18-31,31>>^ And YOU must eat it in every place, YOU and YOUR household, because it is YOUR wages in return for YOUR service in the tent of meeting.

[[v4-18-32]]

^<<v4-18-32,32>>^ And YOU must not incur sin for it when YOU contribute the best from them, and YOU must not profane the holy things of the sons of Israel, that YOU may not die.’”

'''

xref:004-numbers/004-numbers-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numbers/004-numbers-019.adoc#v4-19-0[Próximo Capítulo &#62;]