include::./index.adoc[]

[[v4-16-0]]
=== Numbers, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-16-1]]

^<<v4-16-1,1>>^ And Koʹrah the son of Izʹhar, the son of Koʹhath, the son of Leʹvi, proceeded to get up,^&#42;1^ together with Daʹthan and A·biʹram the sons of E·liʹab, and On the son of Peʹleth, the sons of Reuʹben.

[NOTE]
====
. “Proceeded to get up” and “proceeded to congregate” are proposed readings. Lit., “proceeded to take,” M; LXX, “spoke.”
====

[[v4-16-2]]

^<<v4-16-2,2>>^ And they proceeded to rise up before Moses, they and two hundred and fifty men of the sons of Israel, chieftains of the assembly, summoned ones of the meeting, men of fame.^&#42;1^

[NOTE]
====
. Lit., “name.”
====

[[v4-16-3]]

^<<v4-16-3,3>>^ So they congregated themselves against Moses and Aaron and said to them: “That is enough of YOU, because the whole assembly are all of them holy and Jehovah is in their midst. Why, then, should YOU lift yourselves up above the congregation of Jehovah?”

[[v4-16-4]]

^<<v4-16-4,4>>^ When Moses got to hear it he at once fell upon his face.

[[v4-16-5]]

^<<v4-16-5,5>>^ Then he spoke to Koʹrah and to his entire assembly, saying: “In the morning Jehovah will make known who belongs to him and who is holy and who must come near to him, and whoever he may choose will come near to him.

[[v4-16-6]]

^<<v4-16-6,6>>^ Do this: Take fire holders for yourselves, Koʹrah and his entire assembly,

[[v4-16-7]]

^<<v4-16-7,7>>^ and put fire in them and place incense upon them before Jehovah tomorrow, and it must occur that the man whom Jehovah will choose, he is the holy one. That is enough of YOU, YOU sons of Leʹvi!”

[[v4-16-8]]

^<<v4-16-8,8>>^ And Moses went on to say to Koʹrah: “Listen, please, YOU sons of Leʹvi.

[[v4-16-9]]

^<<v4-16-9,9>>^ Is it such a little thing for YOU men that the God of Israel has separated YOU men from the assembly of Israel to present YOU to himself to carry on the service of Jehovah’s tabernacle and to stand before the assembly to minister to them,

[[v4-16-10]]

^<<v4-16-10,10>>^ and that he should bring you and all your brothers the sons of Leʹvi with you near? So must YOU men also try to secure the priesthood?

[[v4-16-11]]

^<<v4-16-11,11>>^ For that reason you and all your assembly who are gathering together are against Jehovah. As for Aaron, what is he that YOU men should murmur against him?”

[[v4-16-12]]

^<<v4-16-12,12>>^ Later Moses sent to call Daʹthan and A·biʹram the sons of E·liʹab, but they said: “We are not going to come up!

[[v4-16-13]]

^<<v4-16-13,13>>^ Is it so little a thing that you have brought us up out of a land flowing with milk and honey to put us to death in the wilderness, that you should also try to play the prince over us to the limit?

[[v4-16-14]]

^<<v4-16-14,14>>^ As it is, you have not brought us into any land flowing with milk and honey, that you may give us an inheritance of field and vineyard. Is it the eyes of those men that you want to bore out? We are not going to come up!”

[[v4-16-15]]

^<<v4-16-15,15>>^ At this Moses became very angry and said to Jehovah: “Do not turn to look at their grain offering. Not one male ass have I taken away from them, nor have I harmed one of them.”

[[v4-16-16]]

^<<v4-16-16,16>>^ Then Moses said to Koʹrah: “You and all your assembly, be present before Jehovah, you and they and Aaron, tomorrow.

[[v4-16-17]]

^<<v4-16-17,17>>^ And take each one his fire holder, and YOU men must put incense upon them and present each one his fire holder before Jehovah, two hundred and fifty fire holders, and you and Aaron each his fire holder.”

[[v4-16-18]]

^<<v4-16-18,18>>^ So they took each one his fire holder and put fire upon them and placed incense upon them and stood at the entrance of the tent of meeting together with Moses and Aaron.

[[v4-16-19]]

^<<v4-16-19,19>>^ When Koʹrah got all the^&#42;1^ assembly together against them at the entrance of the tent of meeting, then Jehovah’s glory appeared to all the assembly.

[NOTE]
====
. “The,” MSamSy; LXX, “his.”
====

[[v4-16-20]]

^<<v4-16-20,20>>^ Jehovah now spoke to Moses and Aaron, saying:

[[v4-16-21]]

^<<v4-16-21,21>>^ “Separate yourselves from the midst of this assembly, that I may exterminate them in an instant.”

[[v4-16-22]]

^<<v4-16-22,22>>^ At this they fell upon their faces and said: “O God,^&#42;1^ the God^&#42;2^ of the spirits of every sort of flesh, will just one man sin and you become indignant against the entire assembly?”

[NOTE]
====
. “O God.” Heb., ʼEl; Gr., The·osʹ.
. “The God of.” Heb., ʼElo·hehʹ, pl.; Gr., The·osʹ; Lat., Deʹus.
====

[[v4-16-23]]

^<<v4-16-23,23>>^ In turn Jehovah spoke to Moses, saying:

[[v4-16-24]]

^<<v4-16-24,24>>^ “Speak to the assembly, saying, ‘Get away from around the tabernacles^&#42;1^ of Koʹrah, Daʹthan and A·biʹram!’”

[NOTE]
====
. “Tabernacles,” Vg; MSamSy, “tabernacle.”
====

[[v4-16-25]]

^<<v4-16-25,25>>^ After that Moses got up and went to Daʹthan and A·biʹram, and the older men of Israel went with him.

[[v4-16-26]]

^<<v4-16-26,26>>^ Then he spoke to the assembly, saying: “Turn aside, please, from before the tents of these wicked men and do not touch anything that belongs to them, that YOU may not be swept away in all their sin.”

[[v4-16-27]]

^<<v4-16-27,27>>^ Immediately they got away from before the tabernacle of Koʹrah, Daʹthan and A·biʹram, from every side, and Daʹthan and A·biʹram came out, taking their stand at the entrance of their tents, together with their wives, and their sons and their little ones.

[[v4-16-28]]

^<<v4-16-28,28>>^ Then Moses said: “By this YOU will know that Jehovah has sent me to do all these deeds, that it is not of my own heart:

[[v4-16-29]]

^<<v4-16-29,29>>^ If it is according to the death of all mankind^&#42;1^ that these people will die and with the punishment of all mankind that punishment will be brought upon them, then it is not Jehovah that has sent me.

[NOTE]
====
. Or, “the earthlings; humankind.” Heb., ha·ʼa·dhamʹ.
====

[[v4-16-30]]

^<<v4-16-30,30>>^ But if it is something created that Jehovah will create, and the ground has to open its mouth and swallow up them and everything that belongs to them and they have to go down alive into Sheʹol,^&#42;1^ YOU will then know for certain that these men have treated Jehovah disrespectfully.”

[NOTE]
====
. “Into Sheol.” Heb., sheʼoʹlah; Gr., haiʹdou; Lat., in·ferʹnum.
====

[[v4-16-31]]

^<<v4-16-31,31>>^ And it came about that as soon as he had finished speaking all these words, the ground that was under them began to be split apart.

[[v4-16-32]]

^<<v4-16-32,32>>^ And the earth proceeded to open its mouth and to swallow up them and their households and all humankind that belonged to Koʹrah and all the goods.^&#42;1^

[NOTE]
====
. Or, “the property.” SyVgc, “their property”; LXX, “their livestock.”
====

[[v4-16-33]]

^<<v4-16-33,33>>^ So down they went, and all who belonged to them, alive into Sheʹol, and the earth went covering them over, so that they perished from the midst of the congregation.

[[v4-16-34]]

^<<v4-16-34,34>>^ And all the Israelites who were round about them fled at the screaming^&#42;1^ of them, for they began to say: “We are afraid that the earth may swallow us up!”

[NOTE]
====
. Lit., “voice.”
====

[[v4-16-35]]

^<<v4-16-35,35>>^ And a fire came out from Jehovah and proceeded to consume the two hundred and fifty men offering the incense.^&#42;1^

[NOTE]
====
. MLXX end chapter 16 here.
====

[[v4-16-36]]

^<<v4-16-36,36>>^ Jehovah now spoke to Moses, saying:

[[v4-16-37]]

^<<v4-16-37,37>>^ “Say to El·e·aʹzar the son of Aaron the priest that he should take up the fire holders from within the conflagration, ‘And you scatter the fire over there; for they are holy,

[[v4-16-38]]

^<<v4-16-38,38>>^ even the fire holders of these men who sinned against their own souls. And they must make them into thin metal plates as an overlaying for the altar, because they presented them before Jehovah, so that they became holy; and they should serve as a sign to the sons of Israel.’”

[[v4-16-39]]

^<<v4-16-39,39>>^ Accordingly El·e·aʹzar the priest took the copper fire holders, which those who had been burned up had presented, and they proceeded to beat them out into an overlaying for the altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ as a memorial for the sons of Israel, to the end that no strange man who is not of the offspring of Aaron should come near to make incense smoke before Jehovah, and no one might become like Koʹrah and his assembly, just as Jehovah had spoken to him by means of Moses.

[[v4-16-41]]

^<<v4-16-41,41>>^ And directly the next day the whole assembly of the sons of Israel began to murmur against Moses and Aaron, saying: “YOU men, YOU have put Jehovah’s people to death.”

[[v4-16-42]]

^<<v4-16-42,42>>^ And it came about that when the assembly had congregated themselves together against Moses and Aaron, they then turned toward the tent of meeting; and, look! the cloud covered it, and Jehovah’s glory began to appear.

[[v4-16-43]]

^<<v4-16-43,43>>^ And Moses and Aaron proceeded to come before the tent of meeting.

[[v4-16-44]]

^<<v4-16-44,44>>^ Then Jehovah spoke to Moses,^&#42;1^ saying:

[NOTE]
====
. “Moses,” MSamVg; LXXSy, “Moses and Aaron.”
====

[[v4-16-45]]

^<<v4-16-45,45>>^ “YOU men, rise up from the midst of this assembly, that I may exterminate them in an instant.” At this they fell upon their faces.

[[v4-16-46]]

^<<v4-16-46,46>>^ After that Moses said to Aaron: “Take the fire holder and put fire from upon the altar in it and put on incense and go to the assembly in a hurry and make atonement for them, because the indignation has gone out from the face of Jehovah. The plague has started!”

[[v4-16-47]]

^<<v4-16-47,47>>^ Aaron at once took it, just as Moses had spoken, and went running into the midst of the congregation; and, look! the plague had started among the people. So he put the incense on and began making atonement for the people.

[[v4-16-48]]

^<<v4-16-48,48>>^ And he kept standing between the dead and the living. Eventually the scourge was stopped.

[[v4-16-49]]

^<<v4-16-49,49>>^ And those dead from the scourge amounted to fourteen thousand seven hundred, aside from those dead on account of Koʹrah.

[[v4-16-50]]

^<<v4-16-50,50>>^ When at last Aaron returned to Moses at the entrance of the tent of meeting, the scourge had been stopped.

'''

xref:004-numbers/004-numbers-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numbers/004-numbers-017.adoc#v4-17-0[Próximo Capítulo &#62;]