include::./index.adoc[]

[[v4-26-0]]
=== Numbers, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-26-1]]

^<<v4-26-1,1>>^ And it came about after the scourge,^&#42;1^ that Jehovah went on to say this to Moses and El·e·aʹzar the son of Aaron the priest:

[NOTE]
====
. M ends chapter 25 here with the foregoing clause as vs 19.
====

[[v4-26-2]]

^<<v4-26-2,2>>^ “TAKE the sum of the whole assembly of the sons of Israel from twenty years of age and upward, according to the house of their fathers, all those going out to the army in Israel.”

[[v4-26-3]]

^<<v4-26-3,3>>^ And Moses and El·e·aʹzar the priest proceeded to speak with them in the desert plains of Moʹab by the Jordan at Jerʹi·cho, saying:

[[v4-26-4]]

^<<v4-26-4,4>>^ “&#91;Take the sum of them&#93; from the age of twenty years and upward, just as Jehovah had commanded Moses.”
Now the sons of Israel who went out of the land of Egypt were:

[[v4-26-5]]

^<<v4-26-5,5>>^ Reuʹben, Israel’s firstborn; Reuʹben’s sons: Of Haʹnoch the family of the Haʹnoch·ites; of Palʹlu the family of the Palʹlu·ites;

[[v4-26-6]]

^<<v4-26-6,6>>^ of Hezʹron the family of the Hezʹron·ites; of Carʹmi the family of the Carʹmites.

[[v4-26-7]]

^<<v4-26-7,7>>^ These were the families of the Reuʹben·ites, and their registered ones amounted to forty-three thousand seven hundred and thirty.

[[v4-26-8]]

^<<v4-26-8,8>>^ And the son^&#42;1^ of Palʹlu was E·liʹab.

[NOTE]
====
. “Son,” Vg; MSamLXXSy, “sons.”
====

[[v4-26-9]]

^<<v4-26-9,9>>^ And the sons of E·liʹab: Nemʹu·el and Daʹthan and A·biʹram. This Daʹthan and A·biʹram were summoned ones of the assembly, who engaged in a struggle against Moses and Aaron in the assembly of Koʹrah, when they engaged in a struggle against Jehovah.

[[v4-26-10]]

^<<v4-26-10,10>>^ Then the earth opened its mouth and swallowed them up. As for Koʹrah, &#91;he died&#93; at the death of the assembly when the fire consumed two hundred and fifty men.^&#42;1^ And they came to be a symbol.

[NOTE]
====
. “Then the earth opened its mouth and the earth swallowed them up, when the assembly died, when the fire consumed Korah and two hundred and fifty men,” Sam.
====

[[v4-26-11]]

^<<v4-26-11,11>>^ However, the sons of Koʹrah did not die.

[[v4-26-12]]

^<<v4-26-12,12>>^ The sons of Simʹe·on by their families: Of Nemʹu·el^&#42;1^ the family of the Nemʹu·el·ites; of Jaʹmin the family of the Jaʹmin·ites; of Jaʹchin the family of the Jaʹchin·ites;

[NOTE]
====
. “Jemuel” in Ge 46:10; Ex 6:15.
====

[[v4-26-13]]

^<<v4-26-13,13>>^ of Zeʹrah^&#42;1^ the family of the Zeʹrah·ites; of Shaʹul the family of the Sha·uʹlites.

[NOTE]
====
. “Zohar” in Ge 46:10; Ex 6:15.
====

[[v4-26-14]]

^<<v4-26-14,14>>^ These were the families of the Simʹe·on·ites: twenty-two thousand two hundred.

[[v4-26-15]]

^<<v4-26-15,15>>^ The sons of Gad by their families: Of Zeʹphon^&#42;1^ the family of the Zeʹphon·ites; of Hagʹgi the family of the Hagʹgites; of Shuʹni the family of the Shuʹnites;

[NOTE]
====
. “Ziphion” in Ge 46:16.
====

[[v4-26-16]]

^<<v4-26-16,16>>^ of Ozʹni^&#42;1^ the family of the Ozʹnites; of Eʹri the family of the Eʹrites;

[NOTE]
====
. “Ez­bon” in Ge 46:16.
====

[[v4-26-17]]

^<<v4-26-17,17>>^ of Arʹod^&#42;1^ the family of the Arʹod·ites; of A·reʹli the family of the A·reʹlites.

[NOTE]
====
. “Arodi” in Ge 46:16.
====

[[v4-26-18]]

^<<v4-26-18,18>>^ These were the families of the sons of Gad, of their registered ones: forty thousand five hundred.

[[v4-26-19]]

^<<v4-26-19,19>>^ The sons of Judah were Er and Oʹnan. However, Er and Oʹnan died in the land of Caʹnaan.

[[v4-26-20]]

^<<v4-26-20,20>>^ And the sons of Judah came to be, by their families: Of Sheʹlah the family of the She·laʹnites; of Peʹrez the family of the Perʹe·zites; of Zeʹrah the family of the Zeʹrah·ites.

[[v4-26-21]]

^<<v4-26-21,21>>^ And the sons of Peʹrez came to be: Of Hezʹron the family of the Hezʹron·ites; of Haʹmul the family of the Ha·muʹlites.

[[v4-26-22]]

^<<v4-26-22,22>>^ These were the families of Judah, of their registered ones: seventy-six thousand five hundred.

[[v4-26-23]]

^<<v4-26-23,23>>^ The sons of Isʹsa·char by their families were: Of Toʹla the family of the Toʹla·ites; of Puʹvah the family of the Puʹnites;

[[v4-26-24]]

^<<v4-26-24,24>>^ of Jaʹshub^&#42;1^ the family of the Jashʹu·bites; of Shimʹron the family of the Shimʹron·ites.

[NOTE]
====
. “Iob” in Ge 46:13.
====

[[v4-26-25]]

^<<v4-26-25,25>>^ These were the families of Isʹsa·char, of their registered ones: sixty-four thousand three hundred.

[[v4-26-26]]

^<<v4-26-26,26>>^ The sons of Zebʹu·lun by their families were: Of Seʹred the family of the Serʹe·dites; of Eʹlon the family of the Eʹlon·ites; of Jahʹle·el the family of the Jahʹle·el·ites.

[[v4-26-27]]

^<<v4-26-27,27>>^ These were the families of the Ze·buʹlu·nites, of their registered ones: sixty thousand five hundred.

[[v4-26-28]]

^<<v4-26-28,28>>^ The sons of Joseph by their families were Ma·nasʹseh and Eʹphra·im.

[[v4-26-29]]

^<<v4-26-29,29>>^ The sons of Ma·nasʹseh were: Of Maʹchir the family of the Maʹchir·ites. And Maʹchir became father to Gilʹe·ad. Of Gilʹe·ad the family of the Gilʹe·ad·ites.

[[v4-26-30]]

^<<v4-26-30,30>>^ These were the sons of Gilʹe·ad: Of Ieʹzer the family of the Ieʹzer·ites; of Heʹlek the family of the Heʹlek·ites;

[[v4-26-31]]

^<<v4-26-31,31>>^ of Asʹri·el the family of the Asʹri·el·ites; of Sheʹchem the family of the Sheʹchem·ites;

[[v4-26-32]]

^<<v4-26-32,32>>^ of She·miʹda the family of the She·miʹda·ites; of Heʹpher the family of the Heʹpher·ites.

[[v4-26-33]]

^<<v4-26-33,33>>^ Now Ze·loʹphe·had the son of Heʹpher proved to have no sons, but daughters, and the names of the daughters of Ze·loʹphe·had were Mahʹlah and Noah, Hogʹlah, Milʹcah and Tirʹzah.

[[v4-26-34]]

^<<v4-26-34,34>>^ These were the families of Ma·nasʹseh, and their registered ones were fifty-two thousand seven hundred.

[[v4-26-35]]

^<<v4-26-35,35>>^ These were the sons of Eʹphra·im by their families: Of Shuʹthe·lah the family of the Shuʹthel·aʹhites; of Beʹcher the family of the Beʹcher·ites; of Taʹhan the family of the Taʹhan·ites.

[[v4-26-36]]

^<<v4-26-36,36>>^ And these were the sons of Shuʹthe·lah: Of Eʹran the family of the Eʹran·ites.

[[v4-26-37]]

^<<v4-26-37,37>>^ These were the families of the sons of Eʹphra·im, of their registered ones: thirty-two thousand five hundred. These were the sons of Joseph by their families.

[[v4-26-38]]

^<<v4-26-38,38>>^ The sons of Benjamin by their families were: Of Beʹla the family of the Beʹla·ites; of Ashʹbel the family of the Ashʹbel·ites; of A·hiʹram^&#42;1^ the family of the A·hiʹram·ites;

[NOTE]
====
. “Ehi” in Ge 46:21.
====

[[v4-26-39]]

^<<v4-26-39,39>>^ of She·phuʹpham^&#42;1^ the family of the Shuʹpham·ites; of Huʹpham^&#42;2^ the family of the Huʹpham·ites.

[NOTE]
====
. “Muppim” in Ge 46:21; “Shuppim” in 1Ch 7:12.
. “Huppim” in Ge 46:21.
====

[[v4-26-40]]

^<<v4-26-40,40>>^ The sons of Beʹla came to be Ard and Naʹa·man: &#91;Of Ard&#93;^&#42;1^ the family of the Ardʹites; of Naʹa·man the family of the Naʹa·mites.

[NOTE]
====
. “[Of Ard],” in agreement with SamLXXVg.
====

[[v4-26-41]]

^<<v4-26-41,41>>^ These were the sons of Benjamin by their families, and their registered ones were forty-five thousand six hundred.

[[v4-26-42]]

^<<v4-26-42,42>>^ These were the sons of Dan by their families: Of Shuʹham^&#42;1^ the family of the Shuʹham·ites. These were the families of Dan by their families.

[NOTE]
====
. “Hushim” in Ge 46:23.
====

[[v4-26-43]]

^<<v4-26-43,43>>^ All the families of the Shuʹham·ites, of their registered ones, were sixty-four thousand four hundred.

[[v4-26-44]]

^<<v4-26-44,44>>^ The sons of Ashʹer by their families were: Of Imʹnah the family of the Imʹnites; of Ishʹvi the family of the Ishʹvites; of Be·riʹah the family of the Be·riʹites;

[[v4-26-45]]

^<<v4-26-45,45>>^ of the sons of Be·riʹah: Of Heʹber the family of the Heʹber·ites; of Malʹchi·el the family of the Malʹchi·el·ites.

[[v4-26-46]]

^<<v4-26-46,46>>^ And the name of Ashʹer’s daughter was Seʹrah.

[[v4-26-47]]

^<<v4-26-47,47>>^ These were the families of the sons of Ashʹer, of their registered ones: fifty-three thousand four hundred.

[[v4-26-48]]

^<<v4-26-48,48>>^ The sons of Naphʹta·li by their families were: Of Jahʹze·el the family of the Jahʹze·el·ites; of Guʹni the family of the Guʹnites;

[[v4-26-49]]

^<<v4-26-49,49>>^ of Jeʹzer the family of the Jeʹzer·ites; of Shilʹlem the family of the Shilʹlem·ites.

[[v4-26-50]]

^<<v4-26-50,50>>^ These were the families of Naphʹta·li by their families, and their registered ones were forty-five thousand four hundred.

[[v4-26-51]]

^<<v4-26-51,51>>^ These were the registered ones of the sons of Israel: six hundred and one thousand seven hundred and thirty.

[[v4-26-52]]

^<<v4-26-52,52>>^ After that Jehovah spoke to Moses, saying:

[[v4-26-53]]

^<<v4-26-53,53>>^ “To these the land should be apportioned for an inheritance by the number of the names.

[[v4-26-54]]

^<<v4-26-54,54>>^ According to the great number you should increase one’s inheritance, and according to the fewness you should reduce one’s inheritance. Each one’s inheritance should be given in proportion to his registered ones.

[[v4-26-55]]

^<<v4-26-55,55>>^ Only by the lot should the land be apportioned. According to the names of the tribes of their fathers they should get an inheritance.

[[v4-26-56]]

^<<v4-26-56,56>>^ By the determination of the lot one’s inheritance should be apportioned between the many and the few.”

[[v4-26-57]]

^<<v4-26-57,57>>^ Now these were the registered ones of the Levites by their families: Of Gerʹshon the family of the Gerʹshon·ites; of Koʹhath the family of the Koʹhath·ites; of Me·rarʹi the family of the Me·rarʹites.

[[v4-26-58]]

^<<v4-26-58,58>>^ These were the families of the Levites:^&#42;1^ the family of the Libʹnites, the family of the Heʹbron·ites, the family of the Mahʹlites, the family of the Muʹshites, the family of the Koʹrah·ites.
And Koʹhath became father to Amʹram.

[NOTE]
====
. “The Levites,” Sy; MVg, “Levi”; LXX, “the sons of Levi.”
====

[[v4-26-59]]

^<<v4-26-59,59>>^ And the name of Amʹram’s wife was Jochʹe·bed, Leʹvi’s daughter, whom his wife bore^&#42;1^ to Leʹvi in Egypt. In time she bore to Amʹram Aaron and Moses and Mirʹi·am their sister.

[NOTE]
====
. “Daughter who proceeded to bear these,” LXX; SyVg, “daughter who was born.”
====

[[v4-26-60]]

^<<v4-26-60,60>>^ Then there were born to Aaron Naʹdab and A·biʹhu, El·e·aʹzar and Ithʹa·mar.

[[v4-26-61]]

^<<v4-26-61,61>>^ But Naʹdab and A·biʹhu died for their presenting illegitimate fire before Jehovah.

[[v4-26-62]]

^<<v4-26-62,62>>^ And their registered ones amounted to twenty-three thousand, all males from a month old and upward. For they did not get registered in among the sons of Israel, because no inheritance was to be given to them in among the sons of Israel.

[[v4-26-63]]

^<<v4-26-63,63>>^ These were the ones registered by Moses and El·e·aʹzar the priest when they registered the sons of Israel in the desert plains of Moʹab by the Jordan at Jerʹi·cho.

[[v4-26-64]]

^<<v4-26-64,64>>^ But among these there did not prove to be a man of those registered by Moses and Aaron the priest when they registered the sons of Israel in the wilderness of Siʹnai.

[[v4-26-65]]

^<<v4-26-65,65>>^ For Jehovah had said concerning them: “They will die without fail in the wilderness.” So there was not left of them a man except Caʹleb the son of Je·phunʹneh and Joshua the son of Nun.

'''

xref:004-numbers/004-numbers-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numbers/004-numbers-027.adoc#v4-27-0[Próximo Capítulo &#62;]