include::./index.adoc[]

[[v4-30-0]]
=== Numbers, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-30-1]]

^<<v4-30-1,1>>^ Then Moses spoke to the heads of the tribes of the sons of Israel, saying: “This is the word that Jehovah has commanded:

[[v4-30-2]]

^<<v4-30-2,2>>^ In case a man makes a vow to Jehovah or swears an oath to bind a vow of abstinence upon his soul, he must not violate his word. According to all that has gone out of his mouth he should do.

[[v4-30-3]]

^<<v4-30-3,3>>^ “And in case a woman makes a vow to Jehovah or she does bind herself with a vow of abstinence in the house of her father in her youth,^&#42;1^

[NOTE]
====
. Or, “while she was not yet promised in marriage.”
====

[[v4-30-4]]

^<<v4-30-4,4>>^ and her father actually hears her vow or her abstinence vow that she has bound upon her soul and her father does keep silent toward her, all her vows must also stand, and every abstinence vow that she has bound upon her soul will stand.

[[v4-30-5]]

^<<v4-30-5,5>>^ But if her father has forbidden her on the day of his hearing all her vows or her abstinence vows that she has bound upon her soul, it will not stand, but Jehovah will forgive her, because her father forbade her.

[[v4-30-6]]

^<<v4-30-6,6>>^ “However, if she at all happens to belong to a husband, and her vow is upon her or the thoughtless promise of her lips that she has bound upon her soul,

[[v4-30-7]]

^<<v4-30-7,7>>^ and her husband actually hears it and keeps silent toward her on the day of his hearing it,^&#42;1^ her vows must also stand or her abstinence vows that she has bound upon her soul will stand.

[NOTE]
====
. “And keeps silent toward her on the day of his hearing it,” to agree with LXX; M has “on the day of his hearing it,” before the conjunction “and.”
====

[[v4-30-8]]

^<<v4-30-8,8>>^ But if her husband on the day of hearing it forbids her, he has also annulled her vow that was upon her or the thoughtless promise of her lips that she bound upon her soul, and Jehovah will forgive her.

[[v4-30-9]]

^<<v4-30-9,9>>^ “In the case of the vow of a widow or a divorced woman, everything that she has bound upon her soul will stand against her.

[[v4-30-10]]

^<<v4-30-10,10>>^ “However, if it is in the house of her husband that she has vowed or has bound an abstinence vow upon her soul by an oath,

[[v4-30-11]]

^<<v4-30-11,11>>^ and her husband has heard it and has kept silent toward her, he has not forbidden her;^&#42;1^ and all her vows must stand or any abstinence vow that she has bound upon her soul will stand.

[NOTE]
====
. “He has not forbidden her,” M; LXX, “and he has not forbidden her.”
====

[[v4-30-12]]

^<<v4-30-12,12>>^ But if her husband has totally annulled them on the day of his hearing any expression of her lips as her vows or as an abstinence vow of her soul, they will not stand. Her husband has annulled them, and Jehovah will forgive her.

[[v4-30-13]]

^<<v4-30-13,13>>^ Any vow or any oath of an abstinence vow to afflict the soul, her husband should establish it or her husband should annul it.

[[v4-30-14]]

^<<v4-30-14,14>>^ But if her husband absolutely keeps silent toward her from day to day, he has also established all her vows or all her abstinence vows that are upon her. He has established them because he kept silent toward her on the day of his hearing them.

[[v4-30-15]]

^<<v4-30-15,15>>^ And if he totally annuls them after his hearing them, he also actually bears her^&#42;1^ error.

[NOTE]
====
. “Her,” M; SamLXX, “his.”
====

[[v4-30-16]]

^<<v4-30-16,16>>^ “These are the regulations that Jehovah commanded Moses as between a husband and his wife, as between a father and his daughter in her youth in the house of her father.”

'''

xref:004-numbers/004-numbers-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numbers/004-numbers-031.adoc#v4-31-0[Próximo Capítulo &#62;]