include::./index.adoc[]

[[v4-9-0]]
=== Numbers, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v4-9-1]]

^<<v4-9-1,1>>^ And Jehovah proceeded to speak to Moses in the wilderness of Siʹnai in the second year of their coming out of the land of Egypt, in the first month, saying:

[[v4-9-2]]

^<<v4-9-2,2>>^ “Now the sons of Israel should prepare the passover sacrifice at its appointed time.

[[v4-9-3]]

^<<v4-9-3,3>>^ On the fourteenth day in this month between the two evenings^&#42;1^ YOU should prepare it at its appointed time. According to all its statutes and all its regular procedures YOU should prepare it.”

[NOTE]
====
. See Ex 12:6 ftn.
====

[[v4-9-4]]

^<<v4-9-4,4>>^ So Moses spoke to the sons of Israel to prepare the passover sacrifice.

[[v4-9-5]]

^<<v4-9-5,5>>^ Then they prepared the passover sacrifice in the first month, on the fourteenth day of the month between the two evenings, in the wilderness of Siʹnai. According to all that Jehovah had commanded Moses, so the sons of Israel did.

[[v4-9-6]]

^<<v4-9-6,6>>^ Now there happened to be men who had become unclean by a human soul^&#42;1^ so that they were not able to prepare the passover sacrifice on that day. Hence they presented themselves before Moses and Aaron on that day.

[NOTE]
====
. “By a human soul,” that is, by a dead soul. MSam(Heb.), leneʹphesh ʼa·dhamʹ; Gr., psy·kheiʹ an·throʹpou; Sy, “soul of a man”; Lat., aʹni·mam hoʹmi·nis.
====

[[v4-9-7]]

^<<v4-9-7,7>>^ Then those men said to him:^&#42;1^ “We are unclean by a human soul. Why should we be restrained from presenting the offering to Jehovah at its appointed time in the midst of the sons of Israel?”

[NOTE]
====
. “Him,” MSamLXXB; LXXASyVg, “them.”
====

[[v4-9-8]]

^<<v4-9-8,8>>^ At this Moses said to them: “Stand there, and let me hear what Jehovah may command regarding YOU.”

[[v4-9-9]]

^<<v4-9-9,9>>^ Then Jehovah spoke to Moses, saying:

[[v4-9-10]]

^<<v4-9-10,10>>^ “Speak to the sons of Israel, saying, ‘Although any man of YOU or of YOUR generations should happen to be unclean by a soul^&#42;1^ or off on a distant^&#42;2^ journey, he too must prepare the passover sacrifice to Jehovah.

[NOTE]
====
. “By a soul,” that is, by a dead soul. Heb., la·neʹphesh; Gr., psy·kheiʹ an·throʹpou; Lat., aʹni·ma.
. “Distant.” In M the last letter of this word was marked with an extraordinary point by the Sopherim, indicating that the reading is doubtful. See App 2A.
====

[[v4-9-11]]

^<<v4-9-11,11>>^ In the second month, on the fourteenth day between the two evenings, they should prepare it. Together with unfermented cakes and bitter greens they should eat it.

[[v4-9-12]]

^<<v4-9-12,12>>^ They must not let any of it remain until morning, and they should break no bone in it. According to the whole statute of the passover they should prepare it.

[[v4-9-13]]

^<<v4-9-13,13>>^ But when the man was clean or did not happen to be off on a journey and neglected to prepare the passover sacrifice, that soul must then be cut off from his people, because the offering of Jehovah he did not present at its appointed time. For his sin that man will answer.

[[v4-9-14]]

^<<v4-9-14,14>>^ “‘And in case an alien resident should be residing with YOU as an alien, he also must prepare the passover sacrifice to Jehovah. According to the statute of the passover and according to its regular procedure is the way he should do. There should exist one statute for YOU people, both for the alien resident and for the native of the land.’”

[[v4-9-15]]

^<<v4-9-15,15>>^ Now on the day of setting up the tabernacle the cloud covered the tabernacle of the tent of the Testimony, but in the evening what appeared to be fire continued over the tabernacle until morning.

[[v4-9-16]]

^<<v4-9-16,16>>^ That is the way it went on constantly: The cloud would cover it by day,^&#42;1^ and the appearance of fire by night.

[NOTE]
====
. “By day,” TJLXXSyVg; MSam omit.
====

[[v4-9-17]]

^<<v4-9-17,17>>^ And whenever the cloud would go up from over the tent, the sons of Israel would pull away^&#42;1^ right afterward, and in the place where the cloud would reside, there is where the sons of Israel would encamp.

[NOTE]
====
. Or, “depart; break camp.”
====

[[v4-9-18]]

^<<v4-9-18,18>>^ At the order of Jehovah the sons of Israel would pull away, and at the order of Jehovah they would encamp. All the days that the cloud would reside over the tabernacle, they would remain encamped.

[[v4-9-19]]

^<<v4-9-19,19>>^ And when the cloud prolonged its stay over the tabernacle many days, the sons of Israel also kept their obligation to Jehovah that they should not pull away.

[[v4-9-20]]

^<<v4-9-20,20>>^ And sometimes^&#42;1^ the cloud would continue a few days over the tabernacle. At the order of Jehovah they would remain encamped, and at the order of Jehovah they would pull away.

[NOTE]
====
. Lit., “And it occurs that.”
====

[[v4-9-21]]

^<<v4-9-21,21>>^ And sometimes the cloud would continue from evening to morning; and the cloud lifted itself in the morning, and they pulled away. Whether it was by day or by night that the cloud lifted itself, they also pulled away.

[[v4-9-22]]

^<<v4-9-22,22>>^ Whether it was two days or a month or more days^&#42;1^ during which the cloud prolonged its stay over the tabernacle by residing over it, the sons of Israel remained encamped and would not pull away, but when it lifted itself they would pull away.

[NOTE]
====
. Lit., “or days.” Vg, “or a longer time.”
====

[[v4-9-23]]

^<<v4-9-23,23>>^ At the order of Jehovah they would encamp, and at the order of Jehovah they would pull away. They kept their obligation to Jehovah at the order of Jehovah by means of Moses.

'''

xref:004-numbers/004-numbers-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numbers/004-numbers-010.adoc#v4-10-0[Próximo Capítulo &#62;]