include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-6-1]]

^<<v27-6-1,1>>^ It seemed good to Da·riʹus, and he set up over the kingdom one hundred and twenty satraps, who were to be over the whole kingdom;

[[v27-6-2]]

^<<v27-6-2,2>>^ and over them three high officials, of whom Daniel was one, in order that these satraps might continually be giving to them the report and the king himself might not become the loser.

[[v27-6-3]]

^<<v27-6-3,3>>^ Then it was that this Daniel was steadily distinguishing himself over the high officials and the satraps, forasmuch as an extraordinary spirit^&#42;1^ was in him; and the king was intending to elevate him over all the kingdom.

[NOTE]
====
. “Spirit.” Aram., ruʹach; LXXBagster(Gr.), pneuʹma; Lat., spiʹri·tus.
====

[[v27-6-4]]

^<<v27-6-4,4>>^ At that time the high officials and the satraps themselves were constantly seeking to find some pretext against Daniel respecting the kingdom; but there was no pretext or corrupt thing at all that they were able to find, forasmuch as he was trustworthy and no negligence or corrupt thing at all was found in him.

[[v27-6-5]]

^<<v27-6-5,5>>^ Consequently these able-bodied men were saying: “We shall find in this Daniel no pretext at all, except we have to find &#91;it&#93; against him in the law of his God.”^&#42;1^

[NOTE]
====
. “His God.” Aram., ʼEla·hehʹ; Lat., Deʹi suʹi.
====

[[v27-6-6]]

^<<v27-6-6,6>>^ Accordingly these high officials and satraps themselves entered as a throng to the king, and this is what they were saying to him: “O Da·riʹus the king, live on even for times indefinite.

[[v27-6-7]]

^<<v27-6-7,7>>^ All the high officials of the kingdom, the prefects and the satraps, the high royal officers and the governors, have taken counsel together to establish a royal statute and to enforce an interdict, that whoever makes a petition to any god or man^&#42;1^ for thirty days except to you, O king, should be thrown to the lions’ pit.

[NOTE]
====
. “God or man.” Aram., ʼelahʹ we·ʼenashʹ; Lat., deʹo et hoʹmi·ne.
====

[[v27-6-8]]

^<<v27-6-8,8>>^ Now, O king, may you establish the statute and sign the writing, in order for &#91;it&#93; not to be changed, according to the law of the Medes and the Persians, which is not annulled.”

[[v27-6-9]]

^<<v27-6-9,9>>^ In accord with this, King Da·riʹus himself signed the writing and the interdict.

[[v27-6-10]]

^<<v27-6-10,10>>^ But Daniel, as soon as he knew that the writing had been signed, entered into his house, and, the windows in his roof chamber being open for him toward Jerusalem, even three times in a day he was kneeling on his knees and praying and offering praise before his God,^&#42;1^ as he had been regularly doing prior to this.

[NOTE]
====
. “His God.” Aram., ʼEla·hehʹ.
====

[[v27-6-11]]

^<<v27-6-11,11>>^ At that time these able-bodied men themselves crowded in and found Daniel petitioning and imploring favor before his God.

[[v27-6-12]]

^<<v27-6-12,12>>^ Then it was that they approached and were saying before the king concerning the interdict of the king: “Is there not an interdict that you have signed that any man that asks a petition from any god or man for thirty days except from you, O king, he should be thrown to the lions’ pit?” The king was answering and saying: “The matter is well established according to the law of the Medes and the Persians, which is not annulled.”

[[v27-6-13]]

^<<v27-6-13,13>>^ Immediately they answered, and they were saying before the king: “Daniel, who is of the exiles^&#42;1^ of Judah, has paid no regard to you, O king, nor to the interdict that you signed, but three times in a day he is making his petition.”

[NOTE]
====
. See 2:25 ftn.
====

[[v27-6-14]]

^<<v27-6-14,14>>^ Consequently the king, as soon as he heard the word, it was very displeasing to him, and toward Daniel he set &#91;his&#93; mind in order to rescue him; and till the setting of the sun he kept on striving to deliver him.

[[v27-6-15]]

^<<v27-6-15,15>>^ Finally these able-bodied men themselves entered as a throng to the king, and they were saying to the king: “Take note, O king, that the law belonging to the Medes and the Persians is that any interdict or statute that the king himself establishes is not to be changed.”

[[v27-6-16]]

^<<v27-6-16,16>>^ Accordingly the king himself commanded,^&#42;1^ and they brought Daniel and threw him into the pit of the lions. The king was answering and saying to Daniel: “Your God^&#42;2^ whom you are serving with constancy, he himself will rescue you.”

[NOTE]
====
. Lit., “said.”
. “Your God.” Aram., ʼEla·hakhʹ; LXXBagster(Gr.), The·osʹ; Lat., Deʹus.
====

[[v27-6-17]]

^<<v27-6-17,17>>^ And a stone was brought and placed on the mouth of the pit, and the king sealed it with his signet ring and with the signet ring of his grandees, in order that nothing should be changed in the case of Daniel.

[[v27-6-18]]

^<<v27-6-18,18>>^ At that time the king went to his palace and spent the night fasting, and no musical instruments^&#42;1^ were brought in before him, and his very sleep fled from him.

[NOTE]
====
. Or, “dancing girls”; or, “concubines.”
====

[[v27-6-19]]

^<<v27-6-19,19>>^ Finally the king himself, at dawn, proceeded to get up in the daylight, and in a hurry he went right to the lions’ pit.

[[v27-6-20]]

^<<v27-6-20,20>>^ And as he got near to the pit, he cried out with a sad voice even to Daniel. The king was speaking up and saying to Daniel: “O Daniel, servant of the living God, has your God^&#42;1^ whom you are serving with constancy been able to rescue you from the lions?”

[NOTE]
====
. See vs 16 ftn, “God.”
====

[[v27-6-21]]

^<<v27-6-21,21>>^ Immediately Daniel himself spoke even with the king: “O king, live on even to times indefinite.

[[v27-6-22]]

^<<v27-6-22,22>>^ My own God sent his angel and shut the mouth of the lions, and they have not brought me to ruin, forasmuch as before him innocence itself was found in me; and also before you, O king, no hurtful act have I done.”

[[v27-6-23]]

^<<v27-6-23,23>>^ Then it was that the king himself became very glad, and Daniel himself he commanded to be lifted up out of the pit. And Daniel was lifted up out of the pit, and there was no hurt at all found on him, because he had trusted in his God.

[[v27-6-24]]

^<<v27-6-24,24>>^ And the king commanded, and they brought these able-bodied men who had accused^&#42;1^ Daniel, and into the lions’ pit they threw them, their sons and their wives; and they had not reached the bottom of the pit before the lions had got the mastery over them, and all their bones they crushed.

[NOTE]
====
. Or, “slandered.” Lit., “had eaten the pieces [of flesh torn from the body] of.”
====

[[v27-6-25]]

^<<v27-6-25,25>>^ Then it was that Da·riʹus^&#42;1^ the king himself wrote to all the peoples, the national groups and the tongues that are dwelling in all the earth: “May YOUR peace grow very much!

[NOTE]
====
. See 5:31 ftn, “Darius.”
====

[[v27-6-26]]

^<<v27-6-26,26>>^ From before me there has been put through an order that, in every dominion of my kingdom, people are to be quaking and fearing before the God of Daniel. For he is the living God and One enduring to times indefinite, and his kingdom is one that will not be brought to ruin, and his dominion^&#42;1^ is forever.^&#42;2^

[NOTE]
====
. Or, “and his rulership (sovereignty).” Aram., weshol·ta·nehʹ. Compare Ps 103:22 ftn.
. Lit., “to the end.”
====

[[v27-6-27]]

^<<v27-6-27,27>>^ He is rescuing and delivering and performing signs and wonders in the heavens and on the earth, for he has rescued Daniel from the paw of the lions.”

[[v27-6-28]]

^<<v27-6-28,28>>^ And as for this Daniel, he prospered in the kingdom of Da·riʹus^&#42;1^ and in the kingdom of Cyrus^&#42;2^ the Persian.

[NOTE]
====
. See 5:31 ftn, “Darius.”
. See 1:21 ftn.
====

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]