include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-10-1]]

^<<v27-10-1,1>>^ In the third year of Cyrus^&#42;1^ the king of Persia there was a matter revealed to Daniel, whose name was called Bel·te·shazʹzar; and the matter was true,^&#42;2^ and there was a great military service. And he understood the matter, and he had understanding in the thing seen.

[NOTE]
====
. “Of Cyrus.” Heb., leKhohʹresh; Gr., Kyʹrou; Lat., Cyʹri.
. Lit., “and . . . truth.” Heb., we·ʼemethʹ.
====

[[v27-10-2]]

^<<v27-10-2,2>>^ In those days I myself, Daniel, happened to be mourning for three full weeks.^&#42;1^

[NOTE]
====
. Lit., “three weeks of days.” Heb., shelo·shahʹ sha·vu·ʽimʹ ya·mimʹ.
====

[[v27-10-3]]

^<<v27-10-3,3>>^ Dainty bread I did not eat, and no flesh or wine entered into my mouth, and in no way did I grease myself until the completing of the three full weeks.

[[v27-10-4]]

^<<v27-10-4,4>>^ And on the twenty-fourth day of the first month, while I myself happened to be on the bank of the great river, that is, Hidʹde·kel,^&#42;1^

[NOTE]
====
. “Hiddekel.” Heb., Chid·daʹqel; LXXVg, “Tigris”; Sy, “Euphrates.”
====

[[v27-10-5]]

^<<v27-10-5,5>>^ I also proceeded to raise my eyes and see, and here was a certain man^&#42;1^ clothed in linen, with his hips girded with gold^&#42;2^ of Uʹphaz.^&#42;3^

[NOTE]
====
. Lit., “one man.” Heb., ʼish-ʼe·chadhʹ.
. “With gold.” Heb., bekheʹthem, an Egyptian loanword.
. “Uphaz.” Heb., ʼU·phazʹ; Lat., o·briʹzo, “refined.”
====

[[v27-10-6]]

^<<v27-10-6,6>>^ And his body was like chrysʹo·lite, and his face like the appearance of lightning, and his eyes like fiery torches, and his arms and the place of his feet were like the sight of burnished copper, and the sound of his words was like the sound of a crowd.

[[v27-10-7]]

^<<v27-10-7,7>>^ And I saw, I Daniel by myself, the appearance; but as for the men^&#42;1^ that happened to be with me, they did not see the appearance. However, there was a great trembling that fell upon them, so that they went running away in hiding themselves.

[NOTE]
====
. “But as for the men.” Heb., weha·ʼana·shimʹ, pl. of ʼish.
====

[[v27-10-8]]

^<<v27-10-8,8>>^ And I—I was left remaining by myself, so that I saw this great appearance. And there was left remaining in me no power, and my own dignity became changed upon me to ruination, and I retained no power.

[[v27-10-9]]

^<<v27-10-9,9>>^ And I began hearing the sound of his words; and while I was hearing the sound of his words, I myself also happened to be fast asleep upon my face, with my face to the earth.

[[v27-10-10]]

^<<v27-10-10,10>>^ And, look! there was a hand that touched me, and it gradually stirred me up to &#91;get&#93; upon my knees and the palms of my hands.

[[v27-10-11]]

^<<v27-10-11,11>>^ And he proceeded to say to me:
“O Daniel, you very desirable man,^&#42;1^ have understanding in the words that I am speaking to you, and stand up where you were standing, for now I have been sent to you.”
And when he spoke with me this word, I did stand up, shivering.

[NOTE]
====
. Lit., “man of desirable things.” Heb., ʼish-chamu·dhohthʹ.
====

[[v27-10-12]]

^<<v27-10-12,12>>^ And he went on to say to me: “Do not be afraid, O Daniel, for from the first day that you gave your heart to understanding and humbling yourself before your God^&#42;1^ your words have been heard, and I myself have come because of your words.

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
====

[[v27-10-13]]

^<<v27-10-13,13>>^ But the prince^&#42;1^ of the royal realm of Persia was standing in opposition to me for twenty-one days, and, look! Miʹcha·el,^&#42;2^ one of the foremost^&#42;3^ princes, came to help me; and I, for my part, remained^&#42;4^ there beside the kings of Persia.

[NOTE]
====
. “But the prince of.” Heb., wesarʹ; LXXBagster(Gr.), arʹkhon; Lat., prinʹceps.
. “Michael,” M(Heb., Mi·kha·ʼelʹ)LXXSyVg; meaning “Who Is Like God?”
. Or, “first.”
. “I, for my part, remained,” MVg; LXX, “him I left.”
====

[[v27-10-14]]

^<<v27-10-14,14>>^ And I have come to cause you to discern what will befall your people in the final part of the days, because it is a vision yet for the days &#91;to come&#93;.”

[[v27-10-15]]

^<<v27-10-15,15>>^ Now when he spoke with me words like these, I had set my face to the earth and had become speechless.

[[v27-10-16]]

^<<v27-10-16,16>>^ And, look! one similar to the likeness of the sons of mankind^&#42;1^ was touching my lips, and I began to open my mouth and speak and say to the one who was standing in front of me: “O my lord,^&#42;2^ because of the appearance my convulsions were turned within me, and I did not retain any power.

[NOTE]
====
. Or, “the sons of earthling men.” Heb., benehʹ ʼa·dhamʹ.
. “O my lord.” Heb., ʼadho·niʹ; Lat., doʹmi·ne mi.
====

[[v27-10-17]]

^<<v27-10-17,17>>^ So how was the servant of this my lord able to speak with this my lord? And as for me, up to now there kept standing in me no power, and no breath at all was left remaining in me.”

[[v27-10-18]]

^<<v27-10-18,18>>^ And the one like the appearance of an earthling man^&#42;1^ proceeded to touch me again and strengthen me.

[NOTE]
====
. Or, “a man.” Heb., ʼa·dhamʹ; Gr., an·throʹpou; Lat., hoʹmi·nis.
====

[[v27-10-19]]

^<<v27-10-19,19>>^ Then he said: “Do not be afraid, O very desirable man.^&#42;1^ May you have peace. Be strong, yes, be strong.” And as soon as he spoke with me I exerted my strength and finally said: “Let my lord speak, because you have strengthened me.”

[NOTE]
====
. See vs 11 ftn.
====

[[v27-10-20]]

^<<v27-10-20,20>>^ So he went on to say:
“Do you really know why I have come to you? And now I shall go back to fight with the prince^&#42;1^ of Persia. When I am going forth, look! also the prince of Greece^&#42;2^ is coming.

[NOTE]
====
. “Prince of.” Heb., sar; LXXBagster(Gr.), arʹkhon·tos; Lat., prinʹci·pem.
. “Greece.” Heb., Ya·wanʹ, “Javan.” See 8:21 ftn.
====

[[v27-10-21]]

^<<v27-10-21,21>>^ However, I shall tell you the things noted down in the writing of truth, and there is no one holding strongly with me in these &#91;things&#93; but Miʹcha·el,^&#42;1^ the prince of YOU people.

[NOTE]
====
. See vs 13 ftn, “Michael.”
====

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]