include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-7-1]]

^<<v27-7-1,1>>^ In the first year of Bel·shazʹzar^&#42;1^ the king of Babylon,^&#42;2^ Daniel himself beheld a dream and visions of his head upon his bed. At that time he wrote down the dream itself. The complete account of the matters he told.

[NOTE]
====
. See 5:1 ftn, “Belshazzar.”
. “Babylon,” Vg; MSy, “Babel”; LXX, “land of Babylonia”; LXXBagster, “the Chaldeans.”
====

[[v27-7-2]]

^<<v27-7-2,2>>^ Daniel was speaking up and saying:
“I happened to be beholding in my visions during the night, and, see there! the four winds^&#42;1^ of the heavens were stirring up the vast sea.

[NOTE]
====
. “Winds of.” Aram., ru·chehʹ; Lat., venʹti.
====

[[v27-7-3]]

^<<v27-7-3,3>>^ And four huge beasts were coming up out of the sea, each one being different from the others.

[[v27-7-4]]

^<<v27-7-4,4>>^ “The first one was like a lion, and it had the wings of an eagle. I kept on beholding until its wings were plucked out, and it was lifted up from the earth and was made to stand up on two feet just like a man, and there was given to it the heart of a man.

[[v27-7-5]]

^<<v27-7-5,5>>^ “And, see there! another beast, a second one, it being like a bear. And on one side it was raised up, and there were three ribs in its mouth between its teeth; and this is what they were saying to it, ‘Get up, eat much flesh.’

[[v27-7-6]]

^<<v27-7-6,6>>^ “After this I kept on beholding, and, see there! another &#91;beast&#93;,^&#42;1^ one like a leopard, but it had four wings of a flying creature on its back.^&#42;2^ And the beast had four heads, and there was given to it rulership indeed.

[NOTE]
====
. “Beast,” LXXSy; M omits.
. “Back,” Mmargin; M, “sides.”
====

[[v27-7-7]]

^<<v27-7-7,7>>^ “After this I kept on beholding in the visions of the night, and, see there! a fourth beast, fearsome and terrible and unusually strong. And it had teeth of iron, big ones. It was devouring and crushing, and what was left it was treading down with its feet. And it was something different from all the &#91;other&#93; beasts that were prior to it, and it had ten horns.

[[v27-7-8]]

^<<v27-7-8,8>>^ I kept on considering the horns, and, look! another horn, a small one, came up in among them, and there were three of the first horns that were plucked up from before it. And, look! there were eyes like the eyes of a man in this horn, and there was a mouth speaking grandiose things.

[[v27-7-9]]

^<<v27-7-9,9>>^ “I kept on beholding until there were thrones^&#42;1^ placed and the Ancient of Days^&#42;2^ sat down. His clothing was white just like snow, and the hair of his head was like clean wool. His throne was flames of fire; its wheels were a burning fire.

[NOTE]
====
. Or, “there was a grand throne,” if the Aram. noun is pl. to denote majesty.
. “And the Ancient of Days.” Aram., weʽAt·tiqʹ Yoh·minʹ; Lat., An·tiʹqu·us Di·eʹrum.
====

[[v27-7-10]]

^<<v27-7-10,10>>^ There was a stream of fire flowing and going out from before him. There were a thousand thousands that kept ministering to him,^&#42;1^ and ten thousand times ten thousand that kept standing right before him. The Court^&#42;2^ took its seat, and there were books that were opened.

[NOTE]
====
. “Kept ministering to him.” Aram., yesham·meshun·nehʹ; Lat., mi·ni·straʹbant eʹi.
. Lit., “The Judgment.” Aram., Di·naʼʹ; Lat., iu·diʹci·um.
====

[[v27-7-11]]

^<<v27-7-11,11>>^ “I kept on beholding at that time because of the sound of the grandiose words that the horn was speaking; I kept on beholding until the beast was killed and its body was destroyed and it was given to the burning fire.

[[v27-7-12]]

^<<v27-7-12,12>>^ But as for the rest of the beasts, their rulerships were taken away, and there was a lengthening in life given to them for a time and a season.^&#42;1^

[NOTE]
====
. Or, “for a time and an appointed time.” Aram., ʽadh-zemanʹ weʽid·danʹ; Gr., heʹos khroʹnou kai kai·rouʹ; Lat., usʹque ad temʹpus et temʹpus.
====

[[v27-7-13]]

^<<v27-7-13,13>>^ “I kept on beholding in the visions of the night, and, see there! with the clouds of the heavens someone like a son of man^&#42;1^ happened to be coming; and to the Ancient of Days he gained access, and they brought him up close even before that One.

[NOTE]
====
. “Someone like a son of man.” Aram., kevarʹ ʼenashʹ. Compare u·ven-ʼa·dhamʹ, “and the son of earthling man,” in Ps 8:4.
====

[[v27-7-14]]

^<<v27-7-14,14>>^ And to him there were given rulership and dignity and kingdom,^&#42;1^ that the peoples, national groups and languages should all serve even him. His rulership is an indefinitely lasting rulership that will not pass away, and his kingdom one that will not be brought to ruin.

[NOTE]
====
. “And kingdom.” Aram., u·mal·khuʹ; Lat., reʹgnum.
====

[[v27-7-15]]

^<<v27-7-15,15>>^ “As for me, Daniel, my spirit^&#42;1^ was distressed within on account of it, and the very visions of my head began to frighten me.

[NOTE]
====
. “My spirit.” Aram., ru·chiʹ; Th(Gr.), pneuʹma; Lat., spiʹri·tus.
====

[[v27-7-16]]

^<<v27-7-16,16>>^ I went up close to one of those who were standing, that I might request from him reliable information on all this. And he said to me, as he went on to make known to me the very interpretation of the matters,

[[v27-7-17]]

^<<v27-7-17,17>>^ “‘As for these huge beasts, because they are four, there are four kings that will stand up from the earth.

[[v27-7-18]]

^<<v27-7-18,18>>^ But the holy ones of the Supreme One^&#42;1^ will receive the kingdom, and they will take possession of the kingdom for time indefinite, even for time indefinite upon times indefinite.’

[NOTE]
====
. Or, “the holy ones of the Most High.” Aram., qad·di·shehʹ ʽEl·yoh·ninʹ (pl. of ʽEl·yohnʹ), forming with the Aram. word for “holy ones” a second pl. word, or else copying the plurality of “holy ones” because of being so close in the sentence. Evidently this is not meant to indicate that the “holy ones” are most high. “Most High” is sing. in LXXSyVg and many Heb. mss.
====

[[v27-7-19]]

^<<v27-7-19,19>>^ “Then it was that I desired to make certain concerning the fourth beast, which proved to be different from all the others, extraordinarily fearsome, the teeth of which were of iron and the claws of which were of copper, which was devouring &#91;and&#93; crushing, and which was treading down even what was left with its feet;

[[v27-7-20]]

^<<v27-7-20,20>>^ and concerning the ten horns that were on its head, and the other &#91;horn&#93; that came up and before which^&#42;1^ three fell, even that horn that had eyes and a mouth speaking grandiose things and the appearance of which was bigger than that of its fellows.

[NOTE]
====
. Or, “and to make way for which.”
====

[[v27-7-21]]

^<<v27-7-21,21>>^ “I kept on beholding when that very horn made war upon the holy ones, and it was prevailing against them,

[[v27-7-22]]

^<<v27-7-22,22>>^ until the Ancient of Days came and judgment itself was given in favor of the holy ones of the Supreme One, and the definite time arrived that the holy ones took possession of the kingdom itself.

[[v27-7-23]]

^<<v27-7-23,23>>^ “This is what he said, ‘As for the fourth beast, there is a fourth kingdom that will come to be on the earth, that will be different from all the &#91;other&#93; kingdoms; and it will devour all the earth and will trample it down and crush it.

[[v27-7-24]]

^<<v27-7-24,24>>^ And as for the ten horns, out of that kingdom there are ten kings that will rise up; and still another one will rise up after them, and he himself will be different from the first ones, and three kings he will humiliate.

[[v27-7-25]]

^<<v27-7-25,25>>^ And he will speak even words against the Most High,^&#42;1^ and he will harass continually^&#42;2^ the holy ones themselves of the Supreme One.^&#42;3^ And he will intend to change times^&#42;4^ and law, and they^&#42;5^ will be given into his hand for a time, and times and half a time.^&#42;6^

[NOTE]
====
. “The Most High.” Aram., ʽIl·lai·ʼaʹ, sing.; Gr., Hyʹpsi·ston; Lat., Ex·celʹsum.
. Lit., “will wear down (away).”
. See vs 18 ftn.
. “Times.” Aram., zim·ninʹ.
. “They,” MSyVg; LXX, “all things”; LXXBagster, “it.”
. Or, “for a season, and seasons and half a season.” Aram., ʽadh-ʽid·danʹ weʽid·da·ninʹ u·phelaghʹ ʽid·danʹ. Here weʽid·da·ninʹ is taken as dual, thus meaning “and two times.” Lexicon Linguae Aramaicae Veteris Testamenti, by E. Vogt, Rome, 1971, p. 124, “ ‘per tempus et (duo) tempora et dimidium tempus’ i. e. per 31⁄2 annos [‘for a time and (two) times and half a time,’ that is, for 31⁄2 years].” See BDB, p. 1105; KB, p. 1106; BHS, on Da 7:25 ftn “b”; see also 4:16 ftn; 12:7 ftn, “Half.”
====

[[v27-7-26]]

^<<v27-7-26,26>>^ And the Court^&#42;1^ itself proceeded to sit, and his own rulership they finally took away, in order to annihilate &#91;him&#93; and to destroy &#91;him&#93; totally.^&#42;2^

[NOTE]
====
. Lit., “Judgment.”
. Lit., “to the end.”
====

[[v27-7-27]]

^<<v27-7-27,27>>^ “‘And the kingdom and the rulership and the grandeur of the kingdoms under all the heavens were given to the people who are the holy ones of the Supreme One.^&#42;1^ Their^&#42;2^ kingdom is an indefinitely lasting kingdom, and all the rulerships will serve and obey even them.’

[NOTE]
====
. See vs 18 ftn.
. Or, “Its,” referring to the “people who are the holy ones.”
====

[[v27-7-28]]

^<<v27-7-28,28>>^ “Up to this point is the end of the matter. As for me, Daniel, my own thoughts kept frightening me a great deal, so that my very complexion changed in me; but the matter itself I kept in my own heart.”^&#42;1^

[NOTE]
====
. The Aram. that began in 2:4 ends here.
====

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]