include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-3-1]]

^<<v27-3-1,1>>^ Neb·u·chad·nezʹzar the king made an image of gold, the height of which was sixty cubits &#91;and&#93; the breadth of which was six cubits. He set it up in the plain of Duʹra in the jurisdictional district of Babylon.

[[v27-3-2]]

^<<v27-3-2,2>>^ And Neb·u·chad·nezʹzar himself as king sent to assemble the satraps, the prefects and the governors, the counselors, the treasurers, the judges, the police magistrates and all the administrators of the jurisdictional districts to come to the inauguration of the image that Neb·u·chad·nezʹzar the king had set up.

[[v27-3-3]]

^<<v27-3-3,3>>^ At that time the satraps, the prefects and the governors, the counselors, the treasurers, the judges, the police magistrates and all the administrators of the jurisdictional districts were assembling themselves for the inauguration of the image that Neb·u·chad·nezʹzar the king had set up, and they were standing in front of the image that Neb·u·chad·nezʹzar had set up.

[[v27-3-4]]

^<<v27-3-4,4>>^ And the herald^&#42;1^ was crying out loudly: “To YOU it is being said, O peoples, national groups and languages,

[NOTE]
====
. “And the herald.” Aram., wekha·roh·zaʼʹ, derived from the Old Persian noun xrausa, “caller”; Gr., keʹryx; Lat., praeʹco. See 5:29 ftn, “Heralded.”
====

[[v27-3-5]]

^<<v27-3-5,5>>^ that at the time that YOU hear the sound of the horn, the pipe, the zither, the triangular harp, the stringed instrument, the bagpipe and all sorts of musical instruments, YOU fall down and worship the image of gold that Neb·u·chad·nezʹzar the king has set up.

[[v27-3-6]]

^<<v27-3-6,6>>^ And whoever does not fall down and worship will at the same moment be thrown into the burning fiery furnace.”

[[v27-3-7]]

^<<v27-3-7,7>>^ Because of this, at the same time as all the peoples were hearing the sound of the horn, the pipe, the zither, the triangular harp, the stringed instrument and all sorts of musical instruments, all the peoples, national groups and languages were falling down &#91;and&#93; worshiping the image of gold that Neb·u·chad·nezʹzar the king had set up.

[[v27-3-8]]

^<<v27-3-8,8>>^ Because of this, at that same time certain Chal·deʹans^&#42;1^ approached and accused the Jews.^&#42;2^

[NOTE]
====
. Lit., “able-bodied men, Chaldeans.” Aram., guv·rinʹ Kas·da·ʼinʹ.
. Or, “slandered the Jews.” Lit., “ate the pieces [of flesh torn from the bodies] of the Jews.”
====

[[v27-3-9]]

^<<v27-3-9,9>>^ They answered, and they were saying to Neb·u·chad·nezʹzar the king: “O king, live on even for times indefinite.

[[v27-3-10]]

^<<v27-3-10,10>>^ You yourself, O king, set forth the command that every man that hears the sound of the horn, the pipe, the zither, the triangular harp, the stringed instrument, and the bagpipe and all sorts of musical instruments, should fall down and worship the image of gold;

[[v27-3-11]]

^<<v27-3-11,11>>^ and that whoever would not fall down and worship should be thrown into the burning fiery furnace.

[[v27-3-12]]

^<<v27-3-12,12>>^ There exist certain Jews^&#42;1^ whom you appointed over the administration of the jurisdictional district of Babylon, Shaʹdrach, Meʹshach and A·bedʹne·go; these able-bodied men have paid no regard to you, O king, they are not serving your own gods,^&#42;2^ and the image of gold that you have set up they are not worshiping.”

[NOTE]
====
. Lit., “able-bodied men, Jews.” Aram., guv·rinʹ Yehu·dhaʼ·yinʹ.
. “Your own gods.” Aram., leʼ·la·haikhʹ; LXXBagster(Gr.), the·oisʹ; Lat., deʹos.
====

[[v27-3-13]]

^<<v27-3-13,13>>^ At that time Neb·u·chad·nezʹzar, in a rage and fury, said to bring in Shaʹdrach, Meʹshach and A·bedʹne·go. Consequently these able-bodied men were brought in before the king.

[[v27-3-14]]

^<<v27-3-14,14>>^ Neb·u·chad·nezʹzar was answering and saying to them: “Is it really so, O Shaʹdrach, Meʹshach and A·bedʹne·go, that YOU are not serving my own gods,^&#42;1^ and the image of gold that I have set up YOU are not worshiping?

[NOTE]
====
. “My own gods.” Aram., leʼ·la·haiʹ.
====

[[v27-3-15]]

^<<v27-3-15,15>>^ Now if YOU are ready so that when YOU hear the sound of the horn, the pipe, the zither, the triangular harp, the stringed instrument, and the bagpipe and all sorts of musical instruments, YOU fall down and worship the image that I have made, &#91;all right&#93;. But if YOU do not worship, at that same moment YOU will be thrown into the burning fiery furnace. And who is that god^&#42;1^ that can rescue YOU out of my hands?”

[NOTE]
====
. “God.” Aram., ʼelahʹ.
====

[[v27-3-16]]

^<<v27-3-16,16>>^ Shaʹdrach, Meʹshach and A·bedʹne·go answered, and they were saying to the king: “O Neb·u·chad·nezʹzar, we are under no necessity in this regard to say back a word to you.

[[v27-3-17]]

^<<v27-3-17,17>>^ If it is to be, our God^&#42;1^ whom we are serving is able to rescue us. Out of the burning fiery furnace and out of your hand, O king, he will rescue &#91;us&#93;.

[NOTE]
====
. “Our God.” Aram., ʼEla·haʹnaʼ.
====

[[v27-3-18]]

^<<v27-3-18,18>>^ But if not, let it become known to you, O king, that your gods^&#42;1^ are not the ones we are serving, and the image of gold that you have set up we will not worship.”

[NOTE]
====
. “Your gods.” Aram., leʼ·la·haikhʹ.
====

[[v27-3-19]]

^<<v27-3-19,19>>^ Then it was that Neb·u·chad·nezʹzar himself got filled with fury, and the very expression of his face was changed toward Shaʹdrach, Meʹshach and A·bedʹne·go. He was answering and saying to heat up the furnace seven times more than it was customary to heat it up.

[[v27-3-20]]

^<<v27-3-20,20>>^ And to certain able-bodied men of vital energy who were in his military force he said to bind Shaʹdrach, Meʹshach and A·bedʹne·go, in order to throw &#91;them&#93; into the burning fiery furnace.

[[v27-3-21]]

^<<v27-3-21,21>>^ Then it was that these able-bodied men were bound in their mantles, their garments and their caps and their other clothing and were thrown into the burning fiery furnace.

[[v27-3-22]]

^<<v27-3-22,22>>^ Just because the king’s word was harsh and the furnace was heated to excess, these able-bodied men that took up Shaʹdrach, Meʹshach and A·bedʹne·go were the ones that the fiery flame killed.

[[v27-3-23]]

^<<v27-3-23,23>>^ But these &#91;other&#93; able-bodied men, the three of them, Shaʹdrach, Meʹshach and A·bedʹne·go, fell down bound in the midst of the burning fiery furnace.^&#42;1^

[NOTE]
====
. Here LXXVg make a long insertion, and in their vs 91 they resume rendering the M text.
====

[[v27-3-24]]

^<<v27-3-24,24>>^ At that time Neb·u·chad·nezʹzar the king himself became frightened and he rose up in a hurry. He was answering and saying to his high royal officials: “Was it not three able-bodied men that we threw bound into the midst of the fire?” They were answering and saying to the king: “Yes, O king.”

[[v27-3-25]]

^<<v27-3-25,25>>^ He was answering and saying: “Look! I am beholding four able-bodied men walking about free in the midst of the fire, and there is no hurt to them, and the appearance of the fourth one is resembling a son of the gods.”^&#42;1^

[NOTE]
====
. “Is resembling a son of the gods.” Aram., da·mehʹ levar-ʼela·hinʹ; Gr., the·ouʹ; Syr., ʼa·la·hin.
====

[[v27-3-26]]

^<<v27-3-26,26>>^ Then it was that Neb·u·chad·nezʹzar approached the door of the burning fiery furnace. He was answering and saying: “Shaʹdrach, Meʹshach and A·bedʹne·go, YOU servants of the Most High God,^&#42;1^ step out and come here!” At that time Shaʹdrach, Meʹshach and A·bedʹne·go were stepping out from the midst of the fire.

[NOTE]
====
. “The Most High God.” Aram., ʼEla·haʼʹ ʽIl·lai·ʼaʹ. See 5:18 ftn.
====

[[v27-3-27]]

^<<v27-3-27,27>>^ And the satraps, the prefects and the governors and the high officials of the king that were assembled were beholding these able-bodied men, that the fire had had no power over their bodies, and not a hair of their head had been singed, and even their mantles had not been changed and the smell of fire itself had not come onto them.

[[v27-3-28]]

^<<v27-3-28,28>>^ Neb·u·chad·nezʹzar was answering and saying: “Blessed be the God of Shaʹdrach, Meʹshach and A·bedʹne·go, who sent his angel and rescued his servants that trusted in him and that changed^&#42;1^ the very word of the king and gave over their bodies, because they would not serve and would not worship any god at all except their own God.^&#42;2^

[NOTE]
====
. Or, “annulled.”
. “Their own God.” Aram., lEʼ·la·hahohnʹ.
====

[[v27-3-29]]

^<<v27-3-29,29>>^ And from me an order is being put through, that any people, national group or language that says anything wrong against the God of Shaʹdrach, Meʹshach and A·bedʹne·go should be dismembered, and its house should be turned into a public privy; forasmuch as there does not exist another god^&#42;1^ that is able to deliver like this one.”

[NOTE]
====
. “God.” Aram., ʼelahʹ.
====

[[v27-3-30]]

^<<v27-3-30,30>>^ At that time the king himself caused Shaʹdrach, Meʹshach and A·bedʹne·go to prosper in the jurisdictional district of Babylon.^&#42;1^

[NOTE]
====
. Sy ends chap. 3 here; MLXXBagsterVg continue chap. 3 for three more vss.
====

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]