include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-12-1]]

^<<v27-12-1,1>>^ “And during that time Miʹcha·el^&#42;1^ will stand up, the great prince^&#42;2^ who is standing in behalf of the sons of your people. And there will certainly occur a time of distress such as has not been made to occur since there came to be a nation until that time. And during that time your people will escape, every one who is found written down in the book.

[NOTE]
====
. See 10:13 ftn, “Michael.”
. “The great prince.” Heb., has·sarʹ hag·ga·dhohlʹ; Lat., prinʹceps maʹgnus; LXX, “the great angel”; LXXBagster(Gr.), ho arʹkhon ho meʹgas, “the great ruler.”
====

[[v27-12-2]]

^<<v27-12-2,2>>^ And there will be many of those asleep in the ground of dust who will wake up, these to indefinitely lasting life and those to reproaches &#91;and&#93; to indefinitely lasting abhorrence.

[[v27-12-3]]

^<<v27-12-3,3>>^ “And the ones having insight will shine like the brightness^&#42;1^ of the expanse; and those who are bringing the many to righteousness, like the stars to time indefinite, even forever.

[NOTE]
====
. Or, “shining.”
====

[[v27-12-4]]

^<<v27-12-4,4>>^ “And as for you, O Daniel, make secret the words and seal up the book, until the time of &#91;the&#93; end.^&#42;1^ Many will rove about, and the &#91;true&#93; knowledge^&#42;2^ will become abundant.”

[NOTE]
====
. “End.” Heb., qets; Gr., syn·te·leiʹas. See Mt 13:39 and Mt 24:3 ftns, “Conclusion.”
. “The [true] knowledge.” Heb., had·daʹʽath.
====

[[v27-12-5]]

^<<v27-12-5,5>>^ And I saw, I Daniel, and, look! there were two others standing, one on the bank here of the stream^&#42;1^ and the other on the bank there of the stream.

[NOTE]
====
. Or, “the river.” Heb., hai·ʼorʹ.
====

[[v27-12-6]]

^<<v27-12-6,6>>^ Then one said to the man clothed with the linen, who was up above the waters of the stream: “How long will it be to the end of the wonderful things?”

[[v27-12-7]]

^<<v27-12-7,7>>^ And I began to hear the man^&#42;1^ clothed with the linen, who was up above the waters of the stream, as he proceeded to raise his right &#91;hand&#93; and his left &#91;hand&#93; to the heavens and to swear by the One who is alive for time indefinite: “It will be for an appointed time, appointed times and a half.^&#42;2^ And as soon as there will have been a finishing of the dashing of the power^&#42;3^ of the holy people to pieces, all these things will come to their finish.”

[NOTE]
====
. “The man.” Heb., ha·ʼishʹ; Lat., viʹrum.
. “For an appointed time, appointed times and a half.” Heb., lemoh·ʽedhʹ moh·ʽadhimʹ wa·cheʹtsi; Gr., eis kai·ronʹ kai kai·rousʹ kai heʹmi·sy kai·rouʹ; Vgc(Lat.), in temʹpus, et temʹpo·ra, et di·miʹdi·um temʹpo·ris. The Jewish scholar Aben Ezra (1089–1164 C.E.) has the dual here (two appointed times). This makes a total of three and a half appointed times as in 7:25, where see ftn, “Half a time.” Compare 4:16 ftn; Re 12:14 ftn.
. Lit., “hand.” Heb., yadh; Lat., maʹnus.
====

[[v27-12-8]]

^<<v27-12-8,8>>^ Now as for me, I heard, but I could not understand; so that I said: “O my lord,^&#42;1^ what will be the final part of these things?”

[NOTE]
====
. “O my lord.” Heb., ʼadho·niʹ; Gr., kyʹri·e; Lat., doʹmi·ne mi.
====

[[v27-12-9]]

^<<v27-12-9,9>>^ And he went on to say: “Go, Daniel, because the words are made secret and sealed up until the time of &#91;the&#93; end.

[[v27-12-10]]

^<<v27-12-10,10>>^ Many will cleanse themselves and whiten themselves and will be refined. And the wicked ones will certainly act wickedly, and no wicked ones at all will understand; but the ones having insight will understand.

[[v27-12-11]]

^<<v27-12-11,11>>^ “And from the time that the constant &#91;feature&#93;^&#42;1^ has been removed and there has been a placing of the disgusting thing that is causing desolation,^&#42;2^ there will be one thousand two hundred and ninety days.

[NOTE]
====
. Or, “the continual [sacrifice].” Heb., hat·ta·midhʹ; Vg, “the continual sacrifice”; LXX, “the sacrifice.”
. “That is causing desolation (astonishment).” Heb., sho·memʹ. Compare 9:27 ftn, “Desolate.”
====

[[v27-12-12]]

^<<v27-12-12,12>>^ “Happy is^&#42;1^ the one who is keeping in expectation and who arrives at the one thousand three hundred and thirty-five days!

[NOTE]
====
. Lit., “O the happiness of.” Heb., ʼash·rehʹ; Gr., ma·kaʹri·os; Lat., be·aʹtus. Compare Ps 1:1 ftn; Mt 5:3; Lu 6:20.
====

[[v27-12-13]]

^<<v27-12-13,13>>^ “And as for you yourself, go toward the end;^&#42;1^ and you will rest, but you will stand up for your lot at the end^&#42;2^ of the days.”

[NOTE]
====
. “Toward the end,” M(Heb., laq·qetsʹ)SyVg; LXX omits.
. “At the end of.” Heb., leqetsʹ; Gr., eis syn·teʹlei·an; Lat., in fiʹne. See vs 4 ftn, “End.”
====

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-hosea/028-hosea-001.adoc#v28-1-0[Próximo Capítulo &#62;]