include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-4-1]]

^<<v27-4-1,1>>^ “Neb·u·chad·nezʹzar the king, to all the peoples, national groups and languages that are dwelling in all the earth: May YOUR peace grow great.

[[v27-4-2]]

^<<v27-4-2,2>>^ The signs and wonders that the Most High God has performed with me, it has seemed good to me to declare.

[[v27-4-3]]

^<<v27-4-3,3>>^ How grand his signs are, and how mighty his wonders are! His kingdom is a kingdom to time indefinite, and his rulership is for generation after generation.

[[v27-4-4]]

^<<v27-4-4,4>>^ ^&#42;1^ “I, Neb·u·chad·nezʹzar, happened to be at ease in my house and flourishing in my palace.

[NOTE]
====
. MLXXBagsterVg begin chap. 4 here.
====

[[v27-4-5]]

^<<v27-4-5,5>>^ There was a dream that I beheld, and it began to make me afraid. And there were mental images upon my bed and visions of my head that began to frighten me.

[[v27-4-6]]

^<<v27-4-6,6>>^ And from me an order was being put through to bring in before me all the wise men of Babylon, that they might make known to me the very interpretation of the dream.

[[v27-4-7]]

^<<v27-4-7,7>>^ “At that time the magic-practicing priests, the conjurers, the Chal·deʹans and the astrologers were entering; and I was saying before them what the dream was, but its interpretation they were not making known to me.

[[v27-4-8]]

^<<v27-4-8,8>>^ And at last there came in before me Daniel, whose name is Bel·te·shazʹzar according to the name of my god and in whom there is the spirit of the holy gods;^&#42;1^ and before him I said what the dream was:

[NOTE]
====
. See vs 18 ftn.
====

[[v27-4-9]]

^<<v27-4-9,9>>^ “‘O Bel·te·shazʹzar the chief of the magic-practicing priests, because I myself well know that the spirit of the holy gods is in you and that there is no secret^&#42;1^ at all that is troubling you, tell &#91;me&#93; the visions of my dream that I have beheld and its interpretation.

[NOTE]
====
. “Secret.” Aram., raz; Th(Gr.), my·steʹri·on; Lat., sa·cra·menʹtum.
====

[[v27-4-10]]

^<<v27-4-10,10>>^ “‘Now the visions of my head upon my bed I happened to be beholding, and, look! a tree in the midst of the earth, the height of which was immense.

[[v27-4-11]]

^<<v27-4-11,11>>^ The tree grew up and became strong, and its very height finally reached the heavens, and it was visible^&#42;1^ to the extremity of the whole earth.

[NOTE]
====
. Lit., “and the sight of it was.”
====

[[v27-4-12]]

^<<v27-4-12,12>>^ Its foliage was fair, and its fruit was abundant, and there was food for all on it. Under it the beast of the field would seek shade, and on its boughs the birds of the heavens would dwell, and from it all flesh would feed itself.

[[v27-4-13]]

^<<v27-4-13,13>>^ “‘I continued beholding in the visions of my head upon my bed, and, look! a watcher,^&#42;1^ even a holy one, coming down from the heavens themselves.

[NOTE]
====
. “A watcher.” Aram., ʽir; LXXBagster(Gr.), eir; Gr., agʹge·los, “angel”; Lat., viʹgil.
====

[[v27-4-14]]

^<<v27-4-14,14>>^ He was calling out loudly,^&#42;1^ and this is what he was saying: “CHOP the tree down, and cut off its boughs. SHAKE off its foliage, and scatter its fruitage. Let the beast flee from under it, and the birds from its boughs.

[NOTE]
====
. Lit., “with vital energy.”
====

[[v27-4-15]]

^<<v27-4-15,15>>^ However, LEAVE its rootstock itself in the earth, even with a banding of iron and of copper, among the grass of the field; and with the dew of the heavens let it be wet, and with the beast let its portion be among the vegetation of the earth.

[[v27-4-16]]

^<<v27-4-16,16>>^ Let its heart be changed from that of mankind, and let the heart of a beast be given to it, and let seven times^&#42;1^ pass over it.

[NOTE]
====
. Or, “appointed (definite) times”; or, “time periods.” Aram., ʽid·da·ninʹ; Gr., eʹte, “years”; LXXBagster(Gr.), kai·roiʹ, “appointed times”; Lat., temʹpo·ra, “times.” “Years,” BDB, p. 1105; KB, p. 1106; Lexicon Linguae Aramaicae Veteris Testamenti, by E. Vogt, Rome, 1971, p. 124. “Seven times” as seven years are twice three and a half times. Compare 7:25 ftn, “Time”; 12:7 ftn, “Half.”
====

[[v27-4-17]]

^<<v27-4-17,17>>^ By the decree of watchers^&#42;1^ the thing is, and &#91;by&#93; the saying of holy ones the request is, to the intent that people living may know that the Most High is Ruler^&#42;2^ in the kingdom of mankind^&#42;3^ and that to the one whom he wants to, he gives it and he sets up over it even the lowliest one of mankind.”^&#42;4^

[NOTE]
====
. “Watchers.” Aram., ʽi·rinʹ; LXXBagster(Gr.), eir; Lat., viʹgi·lum.
. Or, “is ruling.” Aram., shal·litʹ.
. “Mankind.” Aram., ʼanow·shaʼʹ.
. “And . . . the lowliest one of mankind.” Aram., u·shephalʹ ʼana·shimʹ (pl. of ʼenashʹ).
====

[[v27-4-18]]

^<<v27-4-18,18>>^ “‘This was the dream that I myself, King Neb·u·chad·nezʹzar, beheld; and you yourself, O Bel·te·shazʹzar, say what the interpretation is, forasmuch as all the &#91;other&#93; wise men of my kingdom are unable to make known to me the interpretation itself. But you are competent, because the spirit of holy gods^&#42;1^ is in you.’

[NOTE]
====
. “Spirit of . . . gods.” Aram., ru·ach-ʼela·hinʹ; Lat., spiʹri·tus de·oʹrum.
====

[[v27-4-19]]

^<<v27-4-19,19>>^ “At that time Daniel himself, whose name is Bel·te·shazʹzar, was astonished for a moment, and his very thoughts began to frighten him.
“The king was answering and saying, ‘O Bel·te·shazʹzar, do not let the dream and the interpretation themselves frighten you.’
“Bel·te·shazʹzar was answering and saying, ‘O my lord,^&#42;1^ may the dream &#91;apply&#93; to those hating you, and its interpretation to your adversaries.

[NOTE]
====
. “O my lord.” Aram., ma·riʼyʹ.
====

[[v27-4-20]]

^<<v27-4-20,20>>^ “‘The tree that you beheld, that grew great and became strong and the height of which finally reached the heavens and which was visible to all the earth,

[[v27-4-21]]

^<<v27-4-21,21>>^ and the foliage of which was fair, and the fruit of which was abundant, and on which there was food for all; under which the beasts of the field would dwell, and on the boughs of which the birds of the heavens would reside,

[[v27-4-22]]

^<<v27-4-22,22>>^ it is you, O king, because you have grown great and become strong, and your grandeur has grown great and reached to the heavens, and your rulership to the extremity of the earth.

[[v27-4-23]]

^<<v27-4-23,23>>^ “‘And because the king beheld a watcher,^&#42;1^ even a holy one, coming down from the heavens, who was also saying: “CHOP the tree down, and RUIN it. However, LEAVE its rootstock itself in the earth, but with a banding of iron and of copper, among the grass of the field, and with the dew of the heavens let it become wet, and with the beasts of the field let its portion be until seven times^&#42;2^ themselves pass over it,”

[NOTE]
====
. “A watcher.” Aram., ʽir; LXXBagster(Gr.), eir; Lat., viʹgi·lem.
. See vs 16 ftn.
====

[[v27-4-24]]

^<<v27-4-24,24>>^ this is the interpretation, O king, and the decree of the Most High is that which must befall my lord^&#42;1^ the king.

[NOTE]
====
. “My lord.” Aram., ma·riʼyʹ.
====

[[v27-4-25]]

^<<v27-4-25,25>>^ And you they will be driving away from men, and with the beasts of the field your dwelling will come to be, and the vegetation is what they will give even to you to eat just like bulls; and with the dew of the heavens you yourself will be getting wet, and seven times^&#42;1^ themselves will pass over you, until you know that the Most High is Ruler^&#42;2^ in the kingdom of mankind,^&#42;3^ and that to the one whom he wants to he gives it.

[NOTE]
====
. See vs 16 ftn.
. Or, “ruling.”
. Or, “men.” Aram., ʼana·shaʼʹ.
====

[[v27-4-26]]

^<<v27-4-26,26>>^ “‘And because they said to leave the rootstock of the tree, your kingdom will be sure to you after you know that the heavens are ruling.

[[v27-4-27]]

^<<v27-4-27,27>>^ Therefore, O king, may my counsel seem good to you, and remove your own sins by righteousness, and your iniquity by showing mercy to the poor ones. Maybe there will occur a lengthening of your prosperity.’”

[[v27-4-28]]

^<<v27-4-28,28>>^ All this befell Neb·u·chad·nezʹzar the king.

[[v27-4-29]]

^<<v27-4-29,29>>^ At the end of twelve lunar months he happened to be walking upon the royal palace of Babylon.

[[v27-4-30]]

^<<v27-4-30,30>>^ The king was answering and saying: “Is not this Babylon the Great, that I myself have built for the royal house with the strength of my might and for the dignity of my majesty?”

[[v27-4-31]]

^<<v27-4-31,31>>^ While the word was yet in the king’s mouth, there was a voice that fell from the heavens: “To you it is being said, O Neb·u·chad·nezʹzar the king, ‘The kingdom itself has gone away from you,

[[v27-4-32]]

^<<v27-4-32,32>>^ and from mankind they are driving even you away, and with the beasts of the field your dwelling will be. Vegetation they will give even to you to eat just like bulls, and seven times^&#42;1^ themselves will pass over you, until you know that the Most High is Ruler^&#42;2^ in the kingdom of mankind,^&#42;3^ and that to the one whom he wants to he gives it.’”

[NOTE]
====
. See vs 16 ftn.
. Or, “ruling.”
. See vs 25 ftn, “Mankind.”
====

[[v27-4-33]]

^<<v27-4-33,33>>^ At that moment the word itself was fulfilled upon Neb·u·chad·nezʹzar, and from mankind he was being driven away, and vegetation he began to eat just like bulls, and with the dew of the heavens his own body got to be wet, until his very hair grew long just like eagles’ &#91;feathers&#93; and his nails like birds’ &#91;claws&#93;.

[[v27-4-34]]

^<<v27-4-34,34>>^ “And at the end of the days I, Neb·u·chad·nezʹzar, lifted up to the heavens my eyes, and my own understanding began to return to me; and I blessed the Most High himself, and the One living to time indefinite I praised and glorified, because his rulership is a rulership to time indefinite and his kingdom is for generation after generation.

[[v27-4-35]]

^<<v27-4-35,35>>^ And all the inhabitants of the earth are being considered as merely nothing, and he is doing according to his own will^&#42;1^ among the army of the heavens and the inhabitants of the earth. And there exists no one that can check his hand or that can say to him, ‘What have you been doing?’

[NOTE]
====
. Or, “and . . . according to his own desiring.” Aram., u·khemits·beyehʹ, an infinitive.
====

[[v27-4-36]]

^<<v27-4-36,36>>^ “At the same time my understanding itself began to return to me, and for the dignity of my kingdom my majesty and my brightness themselves began to return to me; and for me even my high royal officers and my grandees began eagerly searching, and I was reestablished upon my own kingdom, and greatness extraordinary was added to me.

[[v27-4-37]]

^<<v27-4-37,37>>^ “Now I, Neb·u·chad·nezʹzar, am praising and exalting and glorifying the King of the heavens, because all his works are truth and his ways are justice,^&#42;1^ and because those who are walking in pride he is able to humiliate.”

[NOTE]
====
. Or, “judgment.” Aram., din.
====

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]