include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v27-8-1]]

^<<v27-8-1,1>>^ In the third year of the kingship of Bel·shazʹzar the king, there was a vision that appeared to me, even me, Daniel, after the one appearing to me at the start.

[[v27-8-2]]

^<<v27-8-2,2>>^ And I began to see in the vision; and it came about, while I was seeing, that I was in Shuʹshan the castle, which is in Eʹlam the jurisdictional district; and I proceeded to see in the vision, and I myself happened to be by the watercourse^&#42;1^ of Uʹlai.

[NOTE]
====
. Or, “by the canal.” Heb., ʽal-ʼu·valʹ.
====

[[v27-8-3]]

^<<v27-8-3,3>>^ When I raised my eyes, then I saw, and, look! a ram standing before the watercourse, and it had two horns. And the two horns were tall, but the one was taller than the other,^&#42;1^ and the taller was the one that came up afterward.

[NOTE]
====
. Lit., “the second.”
====

[[v27-8-4]]

^<<v27-8-4,4>>^ I saw the ram making thrusts to the west^&#42;1^ and to the north and to the south,^&#42;2^ and no wild beasts kept standing before it, and there was no one doing any delivering out of its hand. And it did according to its will,^&#42;3^ and it put on great airs.

[NOTE]
====
. Lit., “the sea,” that is, the Mediterranean Sea to the west.
. Lit., “the Negeb.”
. Or, “according to its pleasure.” Heb., khir·tso·nohʹ.
====

[[v27-8-5]]

^<<v27-8-5,5>>^ And I, for my part, kept on considering, and, look! there was a male of the goats coming from the sunset upon the surface of the whole earth,^&#42;1^ and it was not touching the earth. And as regards the he-goat, there was a conspicuous horn between its eyes.

[NOTE]
====
. Or, “the . . . land.” Heb., ha·ʼaʹrets.
====

[[v27-8-6]]

^<<v27-8-6,6>>^ And it kept coming all the way to the ram possessing the two horns, which I had seen standing before the watercourse;^&#42;1^ and it came running toward it in its powerful rage.

[NOTE]
====
. Or, “the canal.” Heb., ha·ʼu·valʹ.
====

[[v27-8-7]]

^<<v27-8-7,7>>^ And I saw it coming into close touch with the ram, and it began showing bitterness toward it, and it proceeded to strike down the ram and to break its two horns, and there proved to be no power in the ram to stand before it. So it threw it to the earth and trampled it down, and the ram proved to have no deliverer out of its hand.

[[v27-8-8]]

^<<v27-8-8,8>>^ And the male of the goats, for its part, put on great airs to an extreme; but as soon as it became mighty, the great horn was broken, and there proceeded to come up conspicuously four instead of it, toward the four winds^&#42;1^ of the heavens.

[NOTE]
====
. Or, “directions.” See 11:4 ftn.
====

[[v27-8-9]]

^<<v27-8-9,9>>^ And out of one of them there came forth another horn, a small one, and it kept getting very much greater toward the south^&#42;1^ and toward the sunrising and toward the Decoration.^&#42;2^

[NOTE]
====
. Or, “the Negeb.”
. Or, “the Beauty.” Possibly referring to Jerusalem and its temple. Compare 11:16, 41.
====

[[v27-8-10]]

^<<v27-8-10,10>>^ And it kept getting greater all the way to the army of the heavens, so that it caused some of the army and some of the stars to fall to the earth, and it went trampling them down.

[[v27-8-11]]

^<<v27-8-11,11>>^ And all the way to the Prince of the army it put on great airs, and from him the constant &#91;feature&#93;^&#42;1^ was taken away, and the established place of his sanctuary was thrown down.

[NOTE]
====
. Or, “the continual [sacrifice],” M(Heb., hat·ta·midhʹ) Sy; Lat., iuʹge sa·cri·fiʹci·um, “the continual sacrifice”; LXXBagster(Gr.), thy·siʹa, “sacrifice.”
====

[[v27-8-12]]

^<<v27-8-12,12>>^ And an army itself was gradually given over, together with the constant &#91;feature&#93;, because of transgression; and it kept throwing truth to the earth, and it acted and had success.

[[v27-8-13]]

^<<v27-8-13,13>>^ And I got to hear a certain holy one speaking, and another holy one proceeded to say to the particular one who was speaking: “How long will the vision be of the constant &#91;feature&#93; and of the transgression causing desolation,^&#42;1^ to make both &#91;the&#93; holy place and &#91;the&#93; army things to trample on?”

[NOTE]
====
. Or, “causing astonishment (horror).” Heb., sho·memʹ. Compare 9:27 ftn, “Desolate.”
====

[[v27-8-14]]

^<<v27-8-14,14>>^ So he said to me: “Until two thousand three hundred evenings &#91;and&#93; mornings; and &#91;the&#93; holy place will certainly be brought into its right condition.”^&#42;1^

[NOTE]
====
. Or, “must be justified (declared righteous)”; or, “must be brought into its right.”
====

[[v27-8-15]]

^<<v27-8-15,15>>^ Then it came about that, while I myself, Daniel, was seeing the vision and seeking an understanding, why, look! there was standing in front of me someone in appearance like an able-bodied man.^&#42;1^

[NOTE]
====
. “An able-bodied man.” Heb., ghaʹver.
====

[[v27-8-16]]

^<<v27-8-16,16>>^ And I began to hear the voice of an earthling man in the midst of the Uʹlai,^&#42;1^ and he proceeded to call out and say: “Gaʹbri·el,^&#42;2^ make that one there understand the thing seen.”

[NOTE]
====
. Or, “Eulaeus.” LXXBagster(Gr.), Ou·balʹ; Gr., Ou·lai; Lat., Uʹlai.
. Meaning “An Able-Bodied One of God.” Heb., Gav·ri·ʼelʹ, a combination of geʹver, “an able-bodied man,” and ʼEl, “God.”
====

[[v27-8-17]]

^<<v27-8-17,17>>^ So he came beside where I was standing, but when he came I got terrified so that I fell upon my face. And he proceeded to say to me: “Understand, O son of man,^&#42;1^ that^&#42;2^ the vision is for the time of &#91;the&#93; end.”

[NOTE]
====
. “Son of man.” Heb., ben-ʼa·dhamʹ. Compare 7:13 ftn; Eze 2:1 ftn.
. Or, “because.”
====

[[v27-8-18]]

^<<v27-8-18,18>>^ And while he was speaking with me, I had become fast asleep on my face on the earth. So he touched me and made me stand up where I had been standing.

[[v27-8-19]]

^<<v27-8-19,19>>^ And he went on to say: “Here I am causing you to know what will occur in the final part of the denunciation, because it is for the appointed time^&#42;1^ of &#91;the&#93; end.

[NOTE]
====
. Or, “for the time appointed.” Heb., lemoh·ʽedhʹ.
====

[[v27-8-20]]

^<<v27-8-20,20>>^ “The ram that you saw possessing the two horns &#91;stands for&#93; the kings of Meʹdi·a and Persia.

[[v27-8-21]]

^<<v27-8-21,21>>^ And the hairy he-goat &#91;stands for&#93; the king of Greece;^&#42;1^ and as for the great horn that was between its eyes, it &#91;stands for&#93; the first king.

[NOTE]
====
. “Greece.” Heb., Ya·wanʹ, “Javan”; Gr., Hel·leʹnon, “the Hellenes (Greeks)”; Lat., Grae·coʹrum, “of the Greeks.”
====

[[v27-8-22]]

^<<v27-8-22,22>>^ And that one having been broken, so that there were four that finally stood up instead of it, there are four kingdoms from &#91;his&#93;^&#42;1^ nation that will stand up, but not with his power.

[NOTE]
====
. “His,” LXXVg; MSy omit.
====

[[v27-8-23]]

^<<v27-8-23,23>>^ “And in the final part of their kingdom, as the transgressors act to a completion, there will stand up a king fierce in countenance and understanding ambiguous sayings.^&#42;1^

[NOTE]
====
. Or, “riddles; perplexing questions.”
====

[[v27-8-24]]

^<<v27-8-24,24>>^ And his power must become mighty, but not by his own power. And in a wonderful way he will cause ruin, and he will certainly prove successful and do effectively. And he will actually bring mighty ones to ruin, also the people made up of &#91;the&#93; holy ones.

[[v27-8-25]]

^<<v27-8-25,25>>^ And according to his insight^&#42;1^ he will also certainly cause deception to succeed in his hand. And in his heart he will put on great airs, and during a freedom from care he will bring many to ruin. And against the Prince of princes he will stand up, but it will be without hand that he will be broken.

[NOTE]
====
. “According to his insight,” M; LXX, “against the holy ones his thought [will be].”
====

[[v27-8-26]]

^<<v27-8-26,26>>^ “And the thing seen concerning the evening and the morning, which has been said, it is true.^&#42;1^ And you, for your part, keep secret the vision, because it is yet for many days.”

[NOTE]
====
. Lit., “truth.” Heb., ʼemethʹ.
====

[[v27-8-27]]

^<<v27-8-27,27>>^ And as for me, Daniel, I felt exhausted and was made sick for &#91;some&#93; days. Then I got up and did the work of the king; but I kept showing myself numbed on account of the thing seen, and there was nobody understanding &#91;it&#93;.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]