include::./index.adoc[]

[[v31-1-0]]
=== Obadiah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v31-1-1]]

^<<v31-1-1,1>>^ The vision of O·ba·diʹah:
This is what the Sovereign Lord Jehovah has said regarding Eʹdom: “There is a report that we have heard from Jehovah, and there is an envoy that has been sent among the nations, ‘Rise up, YOU people, and let us rise up against her in battle.’”

[[v31-1-2]]

^<<v31-1-2,2>>^ “Look! Small is what I have made you among the nations. You are despised very much.

[[v31-1-3]]

^<<v31-1-3,3>>^ The presumptuousness of your heart is what has deceived you, you who are residing in the retreats of the crag, the height where he dwells,^&#42;1^ saying in his heart, ‘Who will bring me down to &#91;the&#93; earth?’

[NOTE]
====
. “Making his dwelling high,” by a slight correction.
====

[[v31-1-4]]

^<<v31-1-4,4>>^ If you should make your position high like the eagle, or if among the stars there were a placing of your nest, down from there I would bring you,” is the utterance of Jehovah.

[[v31-1-5]]

^<<v31-1-5,5>>^ “If it were thieves that came in to you, if despoilers &#91;came in&#93; by night, to what extent^&#42;1^ would you have been silenced? Would they not steal as much as they wanted? Or if it were grape gatherers that came in to you, would they not let some gleanings remain?

[NOTE]
====
. Or, “how?” Heb., ʼehkh.
====

[[v31-1-6]]

^<<v31-1-6,6>>^ O the extent to which^&#42;1^ those of Eʹsau have been searched out! &#91;How&#93; his concealed treasures have been sought out!

[NOTE]
====
. See vs 5 ftn.
====

[[v31-1-7]]

^<<v31-1-7,7>>^ As far as the boundary they have sent you. The very men^&#42;1^ in covenant with you have all deceived you. The men at peace with you have prevailed against you. Those &#91;eating&#93; food with you^&#42;2^ will place a net under you as one in whom there is no discernment.

[NOTE]
====
. “Men.” Heb., ʼan·shehʹ, pl. of ʼish.
. Lit., “[Those of] your bread.”
====

[[v31-1-8]]

^<<v31-1-8,8>>^ Will it not be in that day?” is the utterance of Jehovah.
“And I shall certainly destroy the wise ones out of Eʹdom, and discernment out of the mountainous region of Eʹsau.

[[v31-1-9]]

^<<v31-1-9,9>>^ And your mighty men must become terrified, O Teʹman, for the reason that each one^&#42;1^ will be cut off from the mountainous region of Eʹsau, because of a killing.

[NOTE]
====
. “Each one.” Heb., ʼish.
====

[[v31-1-10]]

^<<v31-1-10,10>>^ Because of the violence to your brother Jacob, shame will cover you, and you will have to be cut off to time indefinite.

[[v31-1-11]]

^<<v31-1-11,11>>^ In the day when you stood off on the side, in the day when strangers took his military force into captivity and &#91;when&#93; outright foreigners entered his gate and over Jerusalem they cast lots, you also were like one of them.

[[v31-1-12]]

^<<v31-1-12,12>>^ “And you ought not to watch the sight in the day of your brother, in the day of his misfortune; and you ought not to rejoice at the sons of Judah in the day of their perishing; and you ought not to maintain a big mouth in the day of &#91;their&#93; distress.

[[v31-1-13]]

^<<v31-1-13,13>>^ You ought not to come into the gate of my people in the day of their disaster. You, even you, ought not to peer at his calamity in the day of his disaster; and you ought not to thrust out a hand upon his wealth^&#42;1^ in the day of his disaster.

[NOTE]
====
. “You ought not to thrust out a hand upon his wealth,” by a correction; M, “you [fem. pl.] ought to make no thrust at his wealth.”
====

[[v31-1-14]]

^<<v31-1-14,14>>^ And you ought not to stand at the parting of the ways, in order to cut off his escapees; and you ought not to hand over his survivors in the day of distress.

[[v31-1-15]]

^<<v31-1-15,15>>^ For the day of Jehovah against all the nations is near.^&#42;1^ In the way that you have done, it will be done to you. Your sort of treatment will return upon your own head.

[NOTE]
====
. Or, “the day of Jehovah is near upon all the nations.”
====

[[v31-1-16]]

^<<v31-1-16,16>>^ For in the way that YOU people have drunk upon my holy mountain, all the nations will keep drinking constantly. And they will certainly drink and gulp down and become as though they had never happened to be.

[[v31-1-17]]

^<<v31-1-17,17>>^ “And in Mount Zion is where those escaping will prove to be, and it must become something holy; and the house of Jacob must take possession of the things for them to possess.^&#42;1^

[NOTE]
====
. “Take possession of those holding them in possession,” by a slight correction to agree with LXXSyVg.
====

[[v31-1-18]]

^<<v31-1-18,18>>^ And the house of Jacob must become a fire, and the house of Joseph a flame, and the house of Eʹsau as stubble; and they must set them ablaze and devour them. And there will prove to be no survivor to the house of Eʹsau; for Jehovah himself has spoken &#91;it&#93;.

[[v31-1-19]]

^<<v31-1-19,19>>^ And they must take possession of the Negʹeb,^&#42;1^ even of the mountainous region of Eʹsau, and of the She·pheʹlah,^&#42;2^ even of the Phi·lisʹtines. And they must take possession of the field of Eʹphra·im and of the field of Sa·marʹi·a; and Benjamin &#91;must take possession of&#93; Gilʹe·ad.

[NOTE]
====
. Or, “the south,” that is, the southern part of the Promised Land.
. Or, “the lowland.”
====

[[v31-1-20]]

^<<v31-1-20,20>>^ And as for the exiles of this rampart,^&#42;1^ to the sons of Israel will belong what the Caʹnaan·ites &#91;possessed&#93; as far as Zarʹe·phath. And the exiles of Jerusalem, who were in Se·pharʹad, will take possession of the cities of the Negʹeb.

[NOTE]
====
. “This rampart.” Heb., ha·chel-haz·zehʹ.
====

[[v31-1-21]]

^<<v31-1-21,21>>^ “And saviors^&#42;1^ will certainly come up onto^&#42;2^ Mount Zion, in order to judge the mountainous region of Eʹsau; and the kingship must become Jehovah’s.”

[NOTE]
====
. “Saviors,” MTVg; LXX, “saved men”; Sy, “the redeemed ones.”
. “Onto,” MTSyVg; LXX, “from (out of).”
====

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonah/032-jonah-001.adoc#v32-1-0[Próximo Capítulo &#62;]