include::./index.adoc[]

[[v13-14-0]]
=== The First of Chronicles, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-14-1]]

^<<v13-14-1,1>>^ And Hiʹram the king of Tyre proceeded to send messengers to David and cedar timbers and builders of walls and workers in wood to build him a house.

[[v13-14-2]]

^<<v13-14-2,2>>^ And David came to know that Jehovah had firmly established him as king over Israel, for his kingship was highly exalted on account of his people Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ And David went on to take more wives in Jerusalem, and David came to be father to more sons and daughters.

[[v13-14-4]]

^<<v13-14-4,4>>^ And these are the names of the children that became his in Jerusalem: Sham·muʹa and Shoʹbab, Nathan and Solʹo·mon,

[[v13-14-5]]

^<<v13-14-5,5>>^ and Ibʹhar and E·liʹshu·a and Elʹpe·let,

[[v13-14-6]]

^<<v13-14-6,6>>^ and Noʹgah and Neʹpheg and Ja·phiʹa,

[[v13-14-7]]

^<<v13-14-7,7>>^ and E·lishʹa·ma and Be·e·liʹa·da and E·liphʹe·let.

[[v13-14-8]]

^<<v13-14-8,8>>^ And the Phi·lisʹtines got to hear that David had been anointed as king over all Israel. At that all the Phi·lisʹtines came up to look for David. When David heard of it, then he went out against them.^&#42;1^

[NOTE]
====
. Lit., “in front of them.” Compare Ge 10:9 ftn, “Opposition to.”
====

[[v13-14-9]]

^<<v13-14-9,9>>^ And the Phi·lisʹtines, for their part, came in and kept making raids in the low plain of Rephʹa·im.

[[v13-14-10]]

^<<v13-14-10,10>>^ And David began to inquire of God, saying: “Shall I go up against the Phi·lisʹtines, and will you certainly give them into my hand?” At this Jehovah said to him: “Go up, and I shall certainly give them into your hand.”

[[v13-14-11]]

^<<v13-14-11,11>>^ So David went up to Baʹal-pe·raʹzim and there got to strike them down. At that David said: “The &#91;true&#93; God has broken through my enemies by my hand like a gap made by waters.” That is why they called the name of that place Baʹal-pe·raʹzim.

[[v13-14-12]]

^<<v13-14-12,12>>^ Consequently they left their gods^&#42;1^ there. Then David said &#91;the word&#93;, and so they were burned in the fire.

[NOTE]
====
. “Their gods,” M(Heb., ʼelo·heh·hemʹ)­LXXVg.
====

[[v13-14-13]]

^<<v13-14-13,13>>^ Later the Phi·lisʹtines once again made a raid in the low plain.

[[v13-14-14]]

^<<v13-14-14,14>>^ At that David inquired again of God, and the &#91;true&#93; God now said to him: “You must not go up after them. Go around from directly against them, and you must come at them in front of the baʹca bushes.^&#42;1^

[NOTE]
====
. “The baca bushes.” Heb., hab·bekha·ʼimʹ; LXXVg, “pear trees.”
====

[[v13-14-15]]

^<<v13-14-15,15>>^ And let it occur that, when you hear the sound of the marching in the tops of the baʹca bushes, then you go out into the fight, because the &#91;true&#93; God will have gone out before you to strike the camp of the Phi·lisʹtines down.”

[[v13-14-16]]

^<<v13-14-16,16>>^ So David did just as the &#91;true&#93; God had commanded him, and they went striking down the camp of the Phi·lisʹtines from Gibʹe·on to Geʹzer.

[[v13-14-17]]

^<<v13-14-17,17>>^ And David’s fame^&#42;1^ began to go out into all the lands, and Jehovah himself put the dread of him upon all the nations.

[NOTE]
====
. Lit., “name.”
====

'''

xref:013-1-chronicles/013-1-chronicles-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-015.adoc#v13-15-0[Próximo Capítulo &#62;]