include::./index.adoc[]

[[v13-28-0]]
=== The First of Chronicles, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-28-1]]

^<<v13-28-1,1>>^ And David proceeded to congregate all the princes of Israel, the princes of the tribes and the princes of the divisions of those ministering to the king and the chiefs^&#42;1^ of thousands and the chiefs of hundreds and the chiefs of all the goods and livestock of the king and of his sons, together with the court officials and the mighty men, even every valiant, mighty man, to Jerusalem.

[NOTE]
====
. Or, “and the princes.” Heb., wesa·rehʹ.
====

[[v13-28-2]]

^<<v13-28-2,2>>^ Then David the king rose to his feet and said:
“Hear me, my brothers and my people. As for me, it was close to my heart to build a resting house for the ark of the covenant of Jehovah and as the footstool of our God, and I had made preparation to build.

[[v13-28-3]]

^<<v13-28-3,3>>^ And the &#91;true&#93; God himself said to me, ‘You will not build a house to my name; for a man of wars you are, and blood you have spilled.’

[[v13-28-4]]

^<<v13-28-4,4>>^ Accordingly Jehovah the God of Israel chose me out of all the house of my father to become king over Israel to time indefinite; for it was Judah that he chose as leader, and in the house of Judah my father’s house, and among my father’s sons, I was the one whom he approved, to make me king over all Israel;

[[v13-28-5]]

^<<v13-28-5,5>>^ and out of all my sons (for many are the sons whom Jehovah has given me) he then chose Solʹo·mon my son to sit upon the throne of the kingship of Jehovah over Israel.

[[v13-28-6]]

^<<v13-28-6,6>>^ “Further, he said to me, ‘Solʹo·mon your son is the one that will build my house and my courtyards; for I have chosen him as my son, and I myself shall become his father.

[[v13-28-7]]

^<<v13-28-7,7>>^ And I shall certainly establish his kingship firmly to time indefinite if he will be strongly resolved to do my commandments and my judicial decisions, as at this day.’

[[v13-28-8]]

^<<v13-28-8,8>>^ And now, before the eyes of all Israel, Jehovah’s congregation,^&#42;1^ and in the ears of our God, take care and search for all the commandments of Jehovah YOUR God, in order that YOU may possess the good land and may certainly pass it on as an inheritance to YOUR sons after YOU to time indefinite.

[NOTE]
====
. “Congregation.” Heb., qehalʹ; Gr., ek·kle·siʹas.
====

[[v13-28-9]]

^<<v13-28-9,9>>^ “And you, Solʹo·mon my son, know the God of your father and serve him with a complete heart and with a delightful soul; for all hearts Jehovah is searching, and every inclination of the thoughts he is discerning. If you search for him, he will let himself be found by you; but if you leave him, he will cast you off forever.

[[v13-28-10]]

^<<v13-28-10,10>>^ See, now, for Jehovah himself has chosen you to build a house as a sanctuary. Be courageous and act.”

[[v13-28-11]]

^<<v13-28-11,11>>^ And David proceeded to give Solʹo·mon his son the architectural plan of the porch and of its houses and its storerooms and its roof chambers and its dark inner rooms and the house of the propitiatory cover;^&#42;1^

[NOTE]
====
. Or, “the mercy seat.” Heb., hak·kap·poʹreth; Lat., pro·pi·ti·a·ti·oʹnis. See Ex 25:17; Le 16:2; Heb 9:5.
====

[[v13-28-12]]

^<<v13-28-12,12>>^ even the architectural plan of everything that had come to be with him by inspiration^&#42;1^ for the courtyards of Jehovah’s house and for all the dining rooms all around, for the treasures of the house of the &#91;true&#93; God and for the treasures of the things made holy;

[NOTE]
====
. Lit., “by the spirit.” Compare Mt 22:43; Re 1:10.
====

[[v13-28-13]]

^<<v13-28-13,13>>^ and for the divisions of the priests and of the Levites and for all the work of the service of Jehovah’s house and for all the utensils of the service of Jehovah’s house;

[[v13-28-14]]

^<<v13-28-14,14>>^ for the gold by weight, the gold for all the utensils for the different services, for all the utensils of silver by weight, for all the utensils for the different services;

[[v13-28-15]]

^<<v13-28-15,15>>^ and the weight for the lampstands of gold and their lamps of gold, by weight of the different lampstands and their lamps, and for the lampstands of silver by weight for the lampstand and its lamps according to the service of the different lampstands;

[[v13-28-16]]

^<<v13-28-16,16>>^ and the gold by weight for the tables of the layer bread, for the different tables, and silver for the tables of silver;

[[v13-28-17]]

^<<v13-28-17,17>>^ and the forks and the bowls and the pitchers of pure gold, and for the small gold bowls by weight for the different small bowls, and for the small silver bowls by weight for the different small bowls;

[[v13-28-18]]

^<<v13-28-18,18>>^ and for the incense altar refined gold by weight and for the representation of the chariot, namely, the cherubs of gold for spreading &#91;their wings&#93; out and screening over the ark of the covenant of Jehovah.

[[v13-28-19]]

^<<v13-28-19,19>>^ “He gave insight for the entire thing in writing from the hand of Jehovah upon me, even for all the works of the architectural plan.”

[[v13-28-20]]

^<<v13-28-20,20>>^ And David went on to say to Solʹo·mon his son: “Be courageous and strong and act. Do not be afraid nor be terrified, for Jehovah God, my God, is with you. He will not desert you or leave you until all the work of the service of Jehovah’s house is finished.

[[v13-28-21]]

^<<v13-28-21,21>>^ And here are the divisions of the priests and of the Levites for all the service of the house of the &#91;true&#93; God; and with you in all the work there is every willing one with skill for all the service, and also the princes and all the people, for all your words.”

'''

xref:013-1-chronicles/013-1-chronicles-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-029.adoc#v13-29-0[Próximo Capítulo &#62;]