include::./index.adoc[]

[[v13-17-0]]
=== The First of Chronicles, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-17-1]]

^<<v13-17-1,1>>^ And it came about that as soon as David had begun dwelling in his own house, David proceeded to say to Nathan the prophet: “Here I am dwelling in a house of cedars, but the ark of the covenant of Jehovah is under tent cloths.”

[[v13-17-2]]

^<<v13-17-2,2>>^ Upon that Nathan said to David: “Everything that is in your heart do, for the &#91;true&#93; God is with you.”

[[v13-17-3]]

^<<v13-17-3,3>>^ And it came about on that night that the word of God came to Nathan, saying:

[[v13-17-4]]

^<<v13-17-4,4>>^ “Go, and you must say to David my servant, ‘This is what Jehovah has said: “It will not be you that will build me the house in which to dwell.

[[v13-17-5]]

^<<v13-17-5,5>>^ For I have not dwelt in a house from the day that I brought Israel up until this day, but I continued from tent to tent and from one tabernacle &#91;to another&#93;.

[[v13-17-6]]

^<<v13-17-6,6>>^ During all the time that I walked about in all Israel, did I speak a single word with one of the judges of Israel whom I commanded to shepherd my people, saying, ‘Why have YOU men not built me a house of cedars?’”’

[[v13-17-7]]

^<<v13-17-7,7>>^ “And now this is what you will say to my servant David, ‘This is what Jehovah of armies has said: “I myself took you from the pasture ground from following the flock to become a leader over my people Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ And I shall prove to be with you wherever you do walk, and I shall cut off all your enemies from before you, and I shall certainly make for you a name like the name of the great ones that are upon the earth.

[[v13-17-9]]

^<<v13-17-9,9>>^ And I shall certainly appoint a place for my people Israel and plant them, and they will indeed reside where they are and no more will they be disturbed; and the sons of unrighteousness will not wear them out again, just as they did at the first,

[[v13-17-10]]

^<<v13-17-10,10>>^ even since the days that I put judges in command over my people Israel. And I shall certainly humble all your enemies. And I tell you, ‘Also a house^&#42;1^ Jehovah will build for you.’

[NOTE]
====
. “A house,” that is, a line of kings, a dynasty.
====

[[v13-17-11]]

^<<v13-17-11,11>>^ “‘“And it must occur that when your days have come to the full &#91;for you&#93; to go &#91;to be&#93; with your forefathers, I shall certainly raise up your seed after you that will come to be one of your sons, and I shall indeed firmly establish his kingship.

[[v13-17-12]]

^<<v13-17-12,12>>^ He is the one that will build me a house, and I shall certainly establish his throne firmly to time indefinite.

[[v13-17-13]]

^<<v13-17-13,13>>^ I myself shall become his father, and he himself will become my son; and my loving-kindness^&#42;1^ I shall not remove from him the way I removed it from the one that happened to be prior to you.

[NOTE]
====
. Or, “loyal love.”
====

[[v13-17-14]]

^<<v13-17-14,14>>^ And I will cause him to stand in my house and in my kingship to time indefinite, and his throne will itself become one lasting to time indefinite.”’”

[[v13-17-15]]

^<<v13-17-15,15>>^ According to all these words and according to all this vision was the way that Nathan spoke to David.

[[v13-17-16]]

^<<v13-17-16,16>>^ After that King David came in and sat down before Jehovah and said: “Who am I, O Jehovah God, and what is my house that you have brought me thus far?

[[v13-17-17]]

^<<v13-17-17,17>>^ As though this should be something little in your eyes, O God, yet you speak concerning the house of your servant down to a distant future time, and you have looked on me according to the opportunity of the man in the ascendancy, O Jehovah God.

[[v13-17-18]]

^<<v13-17-18,18>>^ What more could David say^&#42;1^ to you as to honoring your servant, when you yourself know your servant well?

[NOTE]
====
. Lit., “add.”
====

[[v13-17-19]]

^<<v13-17-19,19>>^ O Jehovah, for the sake of your servant and in agreement with your own heart you have done all these great things by making all the great achievements known.

[[v13-17-20]]

^<<v13-17-20,20>>^ O Jehovah, there is none like you, and there is no God^&#42;1^ except you in connection with all that we have heard with our ears.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Lat., Deʹus.
====

[[v13-17-21]]

^<<v13-17-21,21>>^ And what other nation in the earth is like your people Israel, whom the &#91;true&#93; God went to redeem to himself as a people, to assign to yourself a name of great achievements and fear-inspiring things by driving out nations from before your people whom you have redeemed from Egypt?

[[v13-17-22]]

^<<v13-17-22,22>>^ And you proceeded to constitute your people Israel as your people to time indefinite, and you yourself, O Jehovah, became their God.

[[v13-17-23]]

^<<v13-17-23,23>>^ And now, O Jehovah, let the word that you have spoken concerning your servant and concerning his house prove faithful to time indefinite, and do just as you have spoken.

[[v13-17-24]]

^<<v13-17-24,24>>^ And let your name prove faithful and become great to time indefinite, saying, ‘Jehovah of armies, the God of Israel, is God to Israel,’ and let the house of David your servant be one lasting before you.

[[v13-17-25]]

^<<v13-17-25,25>>^ For you yourself, my God, have revealed to your servant^&#42;1^ the purpose to build him a house. That is why your servant has found occasion to pray before you.

[NOTE]
====
. Lit., “have uncovered the ear of your servant.”
====

[[v13-17-26]]

^<<v13-17-26,26>>^ And now, O Jehovah, you are the &#91;true&#93; God, and you promise this goodness concerning your servant.

[[v13-17-27]]

^<<v13-17-27,27>>^ And now you must take it upon yourself and bless the house of your servant &#91;for it&#93; to continue to time indefinite before you; for you yourself, O Jehovah, have blessed, and it is blessed to time indefinite.”

'''

xref:013-1-chronicles/013-1-chronicles-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-018.adoc#v13-18-0[Próximo Capítulo &#62;]