include::./index.adoc[]

[[v13-2-0]]
=== The First of Chronicles, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-2-1]]

^<<v13-2-1,1>>^ These were the sons of Israel: Reuʹben, Simʹe·on, Leʹvi and Judah, Isʹsa·char and Zebʹu·lun,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dan, Joseph and Benjamin, Naphʹta·li, Gad and Ashʹer.

[[v13-2-3]]

^<<v13-2-3,3>>^ The sons of Judah were Er and Oʹnan and Sheʹlah. The three were born to him from Shuʹa’s daughter, the Caʹnaan·it·ess. And Er the firstborn of Judah came to be bad in the eyes of Jehovah, so that he put him to death.

[[v13-2-4]]

^<<v13-2-4,4>>^ And Taʹmar his daughter-in-law it was that bore to him Peʹrez and Zeʹrah. All the sons of Judah were five.

[[v13-2-5]]

^<<v13-2-5,5>>^ The sons of Peʹrez were Hezʹron and Haʹmul.

[[v13-2-6]]

^<<v13-2-6,6>>^ And the sons of Zeʹrah were Zimʹri and Eʹthan and Heʹman and Calʹcol and Daʹra. There were five of them in all.

[[v13-2-7]]

^<<v13-2-7,7>>^ And the sons of Carʹmi were Aʹchar^&#42;1^ the bringer of ostracism^&#42;2^ upon Israel, who committed an act of unfaithfulness respecting the thing devoted to destruction.

[NOTE]
====
. Meaning “Trouble; Troubler.” Heb., ʽA·kharʹ; in Jos 7:1, 18, “Achan.”
. Or, “the bringer of trouble.” Heb., ʽoh·kherʹ, in a play on words against ʽA·kharʹ, the man’s name.
====

[[v13-2-8]]

^<<v13-2-8,8>>^ And the sons of Eʹthan were Az·a·riʹah.

[[v13-2-9]]

^<<v13-2-9,9>>^ And the sons of Hezʹron that were born to him were Je·rahʹme·el and Ram and Che·luʹbai.^&#42;1^

[NOTE]
====
. “Caleb” in vss 18, 19, 42.
====

[[v13-2-10]]

^<<v13-2-10,10>>^ As for Ram, he became father to Am·minʹa·dab. Am·minʹa·dab, in turn, became father to Nahʹshon the chieftain of the sons of Judah.

[[v13-2-11]]

^<<v13-2-11,11>>^ Nahʹshon, in turn, became father to Salʹma. Salʹma, in turn, became father to Boʹaz.

[[v13-2-12]]

^<<v13-2-12,12>>^ Boʹaz, in turn, became father to Oʹbed. Oʹbed, in turn, became father to Jesʹse.

[[v13-2-13]]

^<<v13-2-13,13>>^ Jesʹse, in turn, became father to his firstborn E·liʹab, and A·binʹa·dab the second, and Shimʹe·a the third,

[[v13-2-14]]

^<<v13-2-14,14>>^ Ne·thanʹel the fourth, Radʹdai the fifth,

[[v13-2-15]]

^<<v13-2-15,15>>^ Oʹzem the sixth, David the seventh.

[[v13-2-16]]

^<<v13-2-16,16>>^ And their sisters were Ze·ruʹiah and Abʹi·gail; and the sons of Ze·ruʹiah were A·bishʹai and Joʹab and Asʹa·hel, three.

[[v13-2-17]]

^<<v13-2-17,17>>^ As for Abʹi·gail, she gave birth to A·maʹsa; and the father of A·maʹsa was Jeʹther the Ishʹma·el·ite.

[[v13-2-18]]

^<<v13-2-18,18>>^ As for Caʹleb^&#42;1^ the son of Hezʹron, he became father to sons by A·zuʹbah his wife and by Jerʹi·oth; and these were her sons: Jeʹsher and Shoʹbab and Arʹdon.

[NOTE]
====
. “Chelubai” in vs 9.
====

[[v13-2-19]]

^<<v13-2-19,19>>^ Eventually A·zuʹbah died. So Caʹleb took to himself Ephʹrath, who in time bore Hur to him.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur, in turn, became father to Uʹri. Uʹri, in turn, became father to Bezʹal·el.

[[v13-2-21]]

^<<v13-2-21,21>>^ And afterward Hezʹron had relations with the daughter of Maʹchir the father of Gilʹe·ad. And he himself took her when he was sixty years old, but she bore Seʹgub to him.

[[v13-2-22]]

^<<v13-2-22,22>>^ Seʹgub, in turn, became father to Jaʹir, who came to have twenty-three cities in the land of Gilʹe·ad.

[[v13-2-23]]

^<<v13-2-23,23>>^ Later Geshʹur and Syria took Havʹvoth-jaʹir from them, with Keʹnath and its dependent towns,^&#42;1^ sixty cities. All these were the sons of Maʹchir the father of Gilʹe·ad.

[NOTE]
====
. Lit., “and her daughters.”
====

[[v13-2-24]]

^<<v13-2-24,24>>^ And after the death of Hezʹron in Caʹleb-ephʹra·thah, with A·biʹjah being the wife of Hezʹron, she then bore him Ashʹhur the father of Te·koʹa.

[[v13-2-25]]

^<<v13-2-25,25>>^ And the sons of Je·rahʹme·el the firstborn of Hezʹron were Ram the firstborn and Buʹnah and Oʹren and Oʹzem, A·hiʹjah.^&#42;1^

[NOTE]
====
. “Ozem, Ahijah,” M; LXX, “Asom his brother”; Vg, “Asom and Achia.”
====

[[v13-2-26]]

^<<v13-2-26,26>>^ And Je·rahʹme·el came to have another wife, whose name was Atʹa·rah. She was the mother of Oʹnam.

[[v13-2-27]]

^<<v13-2-27,27>>^ And the sons of Ram the firstborn of Je·rahʹme·el came to be Maʹaz and Jaʹmin and Eʹker.

[[v13-2-28]]

^<<v13-2-28,28>>^ And the sons of Oʹnam came to be Shamʹmai and Jaʹda. And the sons of Shamʹmai were Naʹdab and A·biʹshur.

[[v13-2-29]]

^<<v13-2-29,29>>^ And the name of A·biʹshur’s wife was Abʹi·ha·il, who in time bore him Ahʹban and Moʹlid.

[[v13-2-30]]

^<<v13-2-30,30>>^ And the sons of Naʹdab were Seʹled and Apʹpa·im. But Seʹled died without sons.

[[v13-2-31]]

^<<v13-2-31,31>>^ And the sons of Apʹpa·im were Ishʹi. And the sons of Ishʹi were Sheʹshan; and the sons of Sheʹshan, Ahʹlai.

[[v13-2-32]]

^<<v13-2-32,32>>^ And the sons of Jaʹda the brother of Shamʹmai were Jeʹther and Jonʹa·than. But Jeʹther died without sons.

[[v13-2-33]]

^<<v13-2-33,33>>^ And the sons of Jonʹa·than were Peʹleth and Zaʹza. These became the sons of Je·rahʹme·el.

[[v13-2-34]]

^<<v13-2-34,34>>^ And Sheʹshan came to have no sons, but daughters. Now Sheʹshan had an Egyptian servant whose name was Jarʹha.

[[v13-2-35]]

^<<v13-2-35,35>>^ So Sheʹshan gave his daughter to Jarʹha his servant as a wife, who in time bore him Atʹtai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atʹtai, in turn, became father to Nathan. Nathan, in turn, became father to Zaʹbad.

[[v13-2-37]]

^<<v13-2-37,37>>^ Zaʹbad, in turn, became father to Ephʹlal. Ephʹlal, in turn, became father to Oʹbed.

[[v13-2-38]]

^<<v13-2-38,38>>^ Oʹbed, in turn, became father to Jeʹhu. Jeʹhu, in turn, became father to Az·a·riʹah.

[[v13-2-39]]

^<<v13-2-39,39>>^ Az·a·riʹah, in turn, became father to Heʹlez. Heʹlez, in turn, became father to El·e·aʹsah.

[[v13-2-40]]

^<<v13-2-40,40>>^ El·e·aʹsah, in turn, became father to Sisʹmai. Sisʹmai, in turn, became father to Shalʹlum.

[[v13-2-41]]

^<<v13-2-41,41>>^ Shalʹlum, in turn, became father to Jek·a·miʹah. Jek·a·miʹah, in turn, became father to E·lishʹa·ma.

[[v13-2-42]]

^<<v13-2-42,42>>^ And the sons of Caʹleb^&#42;1^ the brother of Je·rahʹme·el were Meʹsha his firstborn, who was the father of Ziph, and the sons of Ma·reʹshah the father of Heʹbron.

[NOTE]
====
. “Chelubai” in vs 9.
====

[[v13-2-43]]

^<<v13-2-43,43>>^ And the sons of Heʹbron were Koʹrah and Tapʹpu·ah and Reʹkem and Sheʹma.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sheʹma, in turn, became father to Raʹham the father of Jorʹke·am. Reʹkem, in turn, became father to Shamʹmai.

[[v13-2-45]]

^<<v13-2-45,45>>^ And the son of Shamʹmai was Maʹon; and Maʹon was the father of Beth-zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ As for Eʹphah the concubine of Caʹleb, she gave birth to Haʹran and Moʹza and Gaʹzez. As for Haʹran, he became father to Gaʹzez.

[[v13-2-47]]

^<<v13-2-47,47>>^ And the sons of Jahʹdai were Reʹgem and Joʹtham and Geʹshan and Pelʹet and Eʹphah and Shaʹaph.

[[v13-2-48]]

^<<v13-2-48,48>>^ As for Caʹleb’s concubine Maʹa·cah, she gave birth to Sheʹber and Tirʹha·nah.

[[v13-2-49]]

^<<v13-2-49,49>>^ In time she bore Shaʹaph the father of Mad·manʹnah, Sheʹva the father of Mach·beʹnah and the father of Gibʹe·a. And Caʹleb’s daughter was Achʹsah.

[[v13-2-50]]

^<<v13-2-50,50>>^ These became the sons of Caʹleb.
The sons of Hur the firstborn of Ephʹra·thah: Shoʹbal the father of Kirʹi·ath-jeʹa·rim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salʹma the father of Bethʹle·hem, Haʹreph the father of Beth-gaʹder.

[[v13-2-52]]

^<<v13-2-52,52>>^ And Shoʹbal the father of Kirʹi·ath-jeʹa·rim came to have sons: Ha·roʹeh, half of the Me·nuʹhoth.

[[v13-2-53]]

^<<v13-2-53,53>>^ And the families of Kirʹi·ath-jeʹa·rim were the Ithʹrites and the Puʹthites and the Shuʹmath·ites and the Mishʹra·ites. It was from these that the Zoʹrath·ites and the Eshʹta·ol·ites came out.

[[v13-2-54]]

^<<v13-2-54,54>>^ The sons of Salʹma were Bethʹle·hem and the Ne·tophʹa·thites, Atʹroth-beth-joʹab and half of the Man·a·haʹthites, the Zorʹites.

[[v13-2-55]]

^<<v13-2-55,55>>^ And the families of the scribes dwelling at Jaʹbez were the Tiʹrath·ites, the Shimʹe·ath·ites, the Suʹcath·ites. These were the Kenʹites that came from Hamʹmath the father of the house of Reʹchab.

'''

xref:013-1-chronicles/013-1-chronicles-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-003.adoc#v13-3-0[Próximo Capítulo &#62;]