include::./index.adoc[]

[[v13-12-0]]
=== The First of Chronicles, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-12-1]]

^<<v13-12-1,1>>^ And these are the ones that came to David at Zikʹlag while he was still under restrictions because of Saul the son of Kish; and they were among the mighty men, the helpers in the warfare,

[[v13-12-2]]

^<<v13-12-2,2>>^ armed with the bow, using the right hand and using the left hand with stones or with arrows in the bow. They were of the brothers of Saul, of Benjamin.

[[v13-12-3]]

^<<v13-12-3,3>>^ There was the head A·hi·eʹzer and Joʹash the sons of She·maʹah the Gibʹe·ath·ite, and Jeʹzi·el and Pelʹet the sons of Azʹma·veth, and Berʹa·cah and Jeʹhu the Anʹa·thoth·ite,

[[v13-12-4]]

^<<v13-12-4,4>>^ and Ish·maʹiah the Gibʹe·on·ite, a mighty man among the thirty and over the thirty; and Jeremiah and Ja·ha·ziʹel and Jo·haʹnan and Joʹza·bad the Ge·deʹrath·ite,

[[v13-12-5]]

^<<v13-12-5,5>>^ E·luʹzai and Jerʹi·moth and Be·a·liʹah and Shem·a·riʹah and Sheph·a·tiʹah the Harʹi·phite,

[[v13-12-6]]

^<<v13-12-6,6>>^ El·kaʹnah and Is·shiʹah and Azʹar·el and Jo·eʹzer and Ja·shoʹbe·am, the Koʹrah·ites,

[[v13-12-7]]

^<<v13-12-7,7>>^ and Jo·eʹlah and Zeb·a·diʹah the sons of Je·roʹham of Geʹdor.

[[v13-12-8]]

^<<v13-12-8,8>>^ And there were some of the Gadʹites that separated themselves to David’s side at the place difficult to approach in the wilderness, valiant, mighty men, army men for the war, keeping the large shield and the lance ready, whose faces were the faces of lions, and they were like the gazelles upon the mountains for speed.

[[v13-12-9]]

^<<v13-12-9,9>>^ Eʹzer was the head, O·ba·diʹah the second, E·liʹab the third,

[[v13-12-10]]

^<<v13-12-10,10>>^ Mish·manʹnah the fourth, Jeremiah^&#42;1^ the fifth,

[NOTE]
====
. “Jeremiah.” Heb., Yir·meyahʹ.
====

[[v13-12-11]]

^<<v13-12-11,11>>^ Atʹtai the sixth, Eʹli·el the seventh,

[[v13-12-12]]

^<<v13-12-12,12>>^ Jo·haʹnan the eighth, El·zaʹbad the ninth,

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremiah^&#42;1^ the tenth, Machʹban·nai the eleventh.

[NOTE]
====
. “Jeremiah.” Heb., Yir·meyaʹhu.
====

[[v13-12-14]]

^<<v13-12-14,14>>^ These were of the sons of Gad, heads of the army. The least one was equal to a hundred, and the greatest to a thousand.

[[v13-12-15]]

^<<v13-12-15,15>>^ These are the ones that crossed the Jordan in the first month when it was overflowing all its banks, and they then chased away all those of the low plains, to the east and to the west.

[[v13-12-16]]

^<<v13-12-16,16>>^ And some of the sons of Benjamin and Judah proceeded to come clear to the place difficult to approach, to David.

[[v13-12-17]]

^<<v13-12-17,17>>^ Then David went out before them and answered and said to them: “If it is for peace that YOU have come to me to help me, my own heart will become at unity with YOU. But if it is to betray me to my adversaries when there is no wrong on my palms, let the God of our forefathers see to it and set it in order.”

[[v13-12-18]]

^<<v13-12-18,18>>^ And spirit itself enveloped^&#42;1^ A·maʹsai, the head of the thirty:
“Yours &#91;we are&#93;, O David, and with you &#91;we are&#93;, O son of Jesʹse.
Peace, peace be yours, and peace to the one helping you,
For your God has helped you.”
So David received them and put them among the heads of the troops.

[NOTE]
====
. Lit., “clothed.”
====

[[v13-12-19]]

^<<v13-12-19,19>>^ And there were some of Ma·nasʹseh that deserted^&#42;1^ to David when he came with the Phi·lisʹtines against Saul for battle; but he^&#42;2^ did not help them, for on counsel the axis lords of the Phi·lisʹtines sent him away, saying: “At the risk of our own heads he will desert to his lord^&#42;3^ Saul.”

[NOTE]
====
. Lit., “fell [away].”
. “He,” LXXA,LVg; MLXXא,B, “they.”
. “His lord.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v13-12-20]]

^<<v13-12-20,20>>^ When he came to Zikʹlag there deserted to him from Ma·nasʹseh Adʹnah and Joʹza·bad and Je·diʹa·el and Miʹcha·el and Joʹza·bad and E·liʹhu and Zilʹle·thai, heads of the thousands that belonged to Ma·nasʹseh.

[[v13-12-21]]

^<<v13-12-21,21>>^ And they, for their part, were of help to David against the marauder band, because all of them were mighty men of valor, and they came to be chiefs in the army;

[[v13-12-22]]

^<<v13-12-22,22>>^ for day by day people kept coming to David to help him, until it was a great camp, like the camp of God.

[[v13-12-23]]

^<<v13-12-23,23>>^ And these were the numbers of the heads of those equipped for the army that came to David at Heʹbron to turn the kingship of Saul over to him according to Jehovah’s order.

[[v13-12-24]]

^<<v13-12-24,24>>^ The sons of Judah carrying the large shield and the lance were six thousand eight hundred, equipped for the army.

[[v13-12-25]]

^<<v13-12-25,25>>^ Of the sons of Simʹe·on the mighty men of valor of the army were seven thousand one hundred.

[[v13-12-26]]

^<<v13-12-26,26>>^ Of the sons of the Levites four thousand six hundred.

[[v13-12-27]]

^<<v13-12-27,27>>^ And Je·hoiʹa·da was the leader &#91;of the sons&#93;^&#42;1^ of Aaron, and with him there were three thousand seven hundred.

[NOTE]
====
. Or, “[of the house].” LXXL, “of the sons”; M omits.
====

[[v13-12-28]]

^<<v13-12-28,28>>^ Also Zaʹdok a young man, mighty in valor, and the house of his forefathers, twenty-two chiefs.

[[v13-12-29]]

^<<v13-12-29,29>>^ And of the sons of Benjamin, the brothers of Saul, there were three thousand, and up till then the greater number of them were keeping strict watch of the house of Saul.

[[v13-12-30]]

^<<v13-12-30,30>>^ And of the sons of Eʹphra·im there were twenty thousand eight hundred, mighty men of valor, men of fame,^&#42;1^ by the house of their forefathers.

[NOTE]
====
. Lit., “men of names.”
====

[[v13-12-31]]

^<<v13-12-31,31>>^ And of the half tribe of Ma·nasʹseh there were eighteen thousand that had been designated by name to come to make David king.

[[v13-12-32]]

^<<v13-12-32,32>>^ And of the sons of Isʹsa·char having a knowledge of how to discern the times to know what Israel ought to do, there were two hundred head ones of theirs, and all their brothers were at their orders.

[[v13-12-33]]

^<<v13-12-33,33>>^ Of Zebʹu·lun those going out to the army, drawing up in battle formation with all the weapons of war, there were fifty thousand, and for flocking together &#91;to David&#93;^&#42;1^ they were not of a double heart.

[NOTE]
====
. “For helping David,” LXX.
====

[[v13-12-34]]

^<<v13-12-34,34>>^ And of Naphʹta·li there were a thousand chiefs, and with them with the large shield and the spear there were thirty-seven thousand.

[[v13-12-35]]

^<<v13-12-35,35>>^ And of the Danʹites those drawing up in battle formation were twenty-eight thousand six hundred.

[[v13-12-36]]

^<<v13-12-36,36>>^ And of Ashʹer those going out to the army for drawing up in battle formation were forty thousand.

[[v13-12-37]]

^<<v13-12-37,37>>^ And from across the Jordan of the Reuʹben·ites and the Gadʹites and the half tribe of Ma·nasʹseh with all the weapons of the military army there were a hundred and twenty thousand.

[[v13-12-38]]

^<<v13-12-38,38>>^ All these were men of war, flocking together in battle line; with a complete heart they came to Heʹbron to make David king over all Israel; and also all the remainder of Israel were of one heart for making David king.

[[v13-12-39]]

^<<v13-12-39,39>>^ And they continued there with David three days, eating and drinking, for their brothers had made preparation for them.

[[v13-12-40]]

^<<v13-12-40,40>>^ And also those near to them, as far as Isʹsa·char and Zebʹu·lun and Naphʹta·li, were bringing food^&#42;1^ upon asses and upon camels and upon mules and upon cattle, eatables of flour, cakes of pressed figs and cakes of raisins and wine and oil and cattle and sheep in great quantity, for there was rejoicing in Israel.

[NOTE]
====
. Lit., “bread.”
====

'''

xref:013-1-chronicles/013-1-chronicles-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-013.adoc#v13-13-0[Próximo Capítulo &#62;]