include::./index.adoc[]

[[v13-27-0]]
=== The First of Chronicles, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-27-1]]

^<<v13-27-1,1>>^ As for the sons of Israel by their number, the heads of the paternal houses and the chiefs of the thousands and of the hundreds and their officers that were ministering to the king in every matter of the divisions of those that came in and that went out month by month for all the months of the year, each division was twenty-four thousand.

[[v13-27-2]]

^<<v13-27-2,2>>^ Over the first division of the first month there was Ja·shoʹbe·am the son of Zabʹdi·el, and in his division there were twenty-four thousand.

[[v13-27-3]]

^<<v13-27-3,3>>^ Some of the sons of Peʹrez the head of all the chiefs of the service groups were for the first month.

[[v13-27-4]]

^<<v13-27-4,4>>^ And over the division of the second month there was Doʹdai the A·hoʹhite with his division, and Mikʹloth was the leader, and in his division there were twenty-four thousand.

[[v13-27-5]]

^<<v13-27-5,5>>^ The chief of the third service group for the third month was Be·naiʹah the son of Je·hoiʹa·da the chief priest, and in his division there were twenty-four thousand.

[[v13-27-6]]

^<<v13-27-6,6>>^ This Be·naiʹah was a mighty man of the thirty and over the thirty; and &#91;over&#93; his division there was Am·mizʹa·bad his son.

[[v13-27-7]]

^<<v13-27-7,7>>^ The fourth for the fourth month was Asʹa·hel, Joʹab’s brother, and Zeb·a·diʹah his son after him, and in his division there were twenty-four thousand.

[[v13-27-8]]

^<<v13-27-8,8>>^ The fifth chief for the fifth month was Shamʹhuth the Izʹrah·ite, and in his division there were twenty-four thousand.

[[v13-27-9]]

^<<v13-27-9,9>>^ The sixth for the sixth month was Iʹra the son of Ikʹkesh the Te·koʹite, and in his division there were twenty-four thousand.

[[v13-27-10]]

^<<v13-27-10,10>>^ The seventh for the seventh month was Heʹlez the Pelʹo·nite of the sons of Eʹphra·im, and in his division there were twenty-four thousand.

[[v13-27-11]]

^<<v13-27-11,11>>^ The eighth for the eighth month was Sibʹbe·cai the Huʹshath·ite of the Zeʹrah·ites, and in his division there were twenty-four thousand.

[[v13-27-12]]

^<<v13-27-12,12>>^ The ninth for the ninth month was Abi-eʹzer the Anʹa·thoth·ite of the Benʹja·min·ites, and in his division there were twenty-four thousand.

[[v13-27-13]]

^<<v13-27-13,13>>^ The tenth for the tenth month was Maʹha·rai the Ne·tophʹa·thite of the Zeʹrah·ites, and in his division there were twenty-four thousand.

[[v13-27-14]]

^<<v13-27-14,14>>^ The eleventh for the eleventh month was Be·naiʹah the Pirʹa·thon·ite of the sons of Eʹphra·im, and in his division there were twenty-four thousand.

[[v13-27-15]]

^<<v13-27-15,15>>^ The twelfth for the twelfth month was Helʹdai the Ne·tophʹa·thite, of Othʹni·el, and in his division there were twenty-four thousand.

[[v13-27-16]]

^<<v13-27-16,16>>^ And over the tribes of Israel, of the Reuʹben·ites, E·li·eʹzer the son of Zichʹri was leader; of the Simʹe·on·ites, Sheph·a·tiʹah the son of Maʹa·cah;

[[v13-27-17]]

^<<v13-27-17,17>>^ of Leʹvi, Hash·a·biʹah the son of Kem·uʹel; of Aaron, Zaʹdok;

[[v13-27-18]]

^<<v13-27-18,18>>^ of Judah, E·liʹhu, one of David’s brothers; of Isʹsa·char, Omʹri the son of Miʹcha·el;

[[v13-27-19]]

^<<v13-27-19,19>>^ of Zebʹu·lun, Ish·maʹiah the son of O·ba·diʹah; of Naphʹta·li, Jerʹi·moth the son of Azʹri·el;

[[v13-27-20]]

^<<v13-27-20,20>>^ of the sons of Eʹphra·im, Ho·sheʹa the son of Az·a·ziʹah; of the half tribe of Ma·nasʹseh, Joel the son of Pe·daiʹah;

[[v13-27-21]]

^<<v13-27-21,21>>^ of the half tribe of Ma·nasʹseh in Gilʹe·ad, Idʹdo the son of Zech·a·riʹah; of Benjamin, Ja·a·siʹel the son of Abʹner;

[[v13-27-22]]

^<<v13-27-22,22>>^ of Dan, Azʹar·el the son of Je·roʹham. These were the princes of the tribes of Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ And David did not take the number of those from twenty years of age and under, because Jehovah had promised to make Israel as many as the stars of the heavens.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joʹab the son of Ze·ruʹiah had himself started to take the count, but he did not finish; and for this there came to be indignation against Israel, and the number did not come up into the account of the affairs of the days of King David.

[[v13-27-25]]

^<<v13-27-25,25>>^ And over the treasures of the king there was Azʹma·veth the son of Adʹi·el. And over the treasures in the field, in the cities and in the villages and in the towers there was Jonʹa·than^&#42;1^ the son of Uz·ziʹah.

[NOTE]
====
. Heb., Yehoh·na·thanʹ.
====

[[v13-27-26]]

^<<v13-27-26,26>>^ And over the doers of work in the field, for the cultivation of the soil, there was Ezʹri the son of Cheʹlub.

[[v13-27-27]]

^<<v13-27-27,27>>^ And over the vineyards there was Shimʹe·i the Raʹmath·ite; and over that which was in the vineyards for the wine supplies there was Zabʹdi the Shiphʹmite.

[[v13-27-28]]

^<<v13-27-28,28>>^ And over the olive groves and the sycamore trees that were in the She·pheʹlah^&#42;1^ there was Baʹal-haʹnan the Ge·deʹrite; and over the oil supplies there was Joʹash.

[NOTE]
====
. Or, “the lowland.”
====

[[v13-27-29]]

^<<v13-27-29,29>>^ And over the herds that were grazing in Sharʹon there was Shitʹrai the Sharʹon·ite; and over the herds in the low plains there was Shaʹphat the son of Adʹlai.

[[v13-27-30]]

^<<v13-27-30,30>>^ And over the camels there was Oʹbil the Ishʹma·el·ite; and over the she-asses there was Jeh·deʹiah the Me·ronʹo·thite.

[[v13-27-31]]

^<<v13-27-31,31>>^ And over the flocks there was Jaʹziz the Hagʹrite. All these were the chiefs of the goods that belonged to King David.

[[v13-27-32]]

^<<v13-27-32,32>>^ And Jonʹa·than, David’s nephew,^&#42;1^ was a counselor, a man of understanding, he being also a secretary; and Je·hiʹel the son of Hachʹmo·ni was with the king’s sons.

[NOTE]
====
. “Nephew.” Heb., dohdh, usually “uncle,” but here “uncle’s son; nephew.” Compare 20:7; 2Sa 21:21.
====

[[v13-27-33]]

^<<v13-27-33,33>>^ And A·hithʹo·phel was a counselor of the king; and Huʹshai the Arʹchite was the king’s companion.

[[v13-27-34]]

^<<v13-27-34,34>>^ And after A·hithʹo·phel there were Je·hoiʹa·da the son of Be·naiʹah and A·biʹa·thar; and Joʹab was chief of the army of the king.

'''

xref:013-1-chronicles/013-1-chronicles-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-028.adoc#v13-28-0[Próximo Capítulo &#62;]