include::./index.adoc[]

[[v13-9-0]]
=== The First of Chronicles, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-9-1]]

^<<v13-9-1,1>>^ As for all Israelites, they were enrolled genealogically; and there they are written in the Book of the Kings of Israel. And Judah itself was taken into exile at Babylon^&#42;1^ for their unfaithfulness.

[NOTE]
====
. “Babylon,” LXXVg; MSy, “Babel.”
====

[[v13-9-2]]

^<<v13-9-2,2>>^ And the first inhabitants that were in their possession^&#42;1^ in their cities were the Israelites,^&#42;2^ the priests, the Levites and the Nethʹi·nim.^&#42;3^

[NOTE]
====
. Or, “landed property.”
. Or, “were Israel.”
. “And the Nethinim (temple slaves).” Lit., “and the given ones.” Heb., wehan·Nethi·nimʹ. Compare Nu 3:9 ftn.
====

[[v13-9-3]]

^<<v13-9-3,3>>^ And in Jerusalem there dwelt some of the sons of Judah and some of the sons of Benjamin and some of the sons of Eʹphra·im and of Ma·nasʹseh:

[[v13-9-4]]

^<<v13-9-4,4>>^ Uʹthai the son of Am·miʹhud the son of Omʹri the son of Imʹri the son of Baʹni, of the sons of Peʹrez^&#42;1^ the son of Judah.

[NOTE]
====
. “The son of Bani, of the sons of Perez,” LXXfour mssVg.
====

[[v13-9-5]]

^<<v13-9-5,5>>^ And of the Shiʹlo·nites,^&#42;1^ A·saiʹah the firstborn and his sons.

[NOTE]
====
. “The Shilonites.” Not the inhabitants of Shiloh but the descendants of Judah’s third son, Shelah. See Ge 46:12.
====

[[v13-9-6]]

^<<v13-9-6,6>>^ And of the sons of Zeʹrah, Je·uʹel, and six hundred and ninety brothers of theirs.

[[v13-9-7]]

^<<v13-9-7,7>>^ And of the sons of Benjamin, Salʹlu the son of Me·shulʹlam the son of Hod·a·viʹah the son of Has·se·nuʹah,

[[v13-9-8]]

^<<v13-9-8,8>>^ and Ib·neʹiah the son of Je·roʹham, and Eʹlah the son of Uzʹzi the son of Michʹri, and Me·shulʹlam the son of Sheph·a·tiʹah the son of Reuʹel the son of Ib·niʹjah.

[[v13-9-9]]

^<<v13-9-9,9>>^ And the brothers of theirs by their descendants were nine hundred and fifty-six. All these were men that were heads of the fathers by the house of their forefathers.

[[v13-9-10]]

^<<v13-9-10,10>>^ And of the priests there were Je·daʹiah and Je·hoiʹa·rib and Jaʹchin,

[[v13-9-11]]

^<<v13-9-11,11>>^ and Az·a·riʹah the son of Hil·kiʹah the son of Me·shulʹlam the son of Zaʹdok the son of Me·raʹioth the son of A·hiʹtub, a leader^&#42;1^ of the house of the &#91;true&#93; God,

[NOTE]
====
. “Leader of.” Heb., neghidhʹ; Lat., ponʹti·fex.
====

[[v13-9-12]]

^<<v13-9-12,12>>^ and A·daiʹah the son of Je·roʹham the son of Pashʹhur the son of Mal·chiʹjah, and Maʹa·sai the son of Adʹi·el the son of Jahʹze·rah the son of Me·shulʹlam the son of Me·shilʹle·mith the son of Imʹmer,

[[v13-9-13]]

^<<v13-9-13,13>>^ and their brothers, heads of the house of their forefathers, a thousand seven hundred and sixty, mighty men of ability for the work of the service of the house of the &#91;true&#93; God.

[[v13-9-14]]

^<<v13-9-14,14>>^ And of the Levites there were She·maiʹah the son of Hasʹshub the son of Az·riʹkam the son of Hash·a·biʹah from the sons of Me·rarʹi;

[[v13-9-15]]

^<<v13-9-15,15>>^ and Bak·bakʹkar, Heʹresh and Gaʹlal, and Mat·ta·niʹah the son of Miʹca the son of Zichʹri the son of Aʹsaph,

[[v13-9-16]]

^<<v13-9-16,16>>^ and O·ba·diʹah the son of She·maiʹah the son of Gaʹlal the son of Je·duʹthun, and Ber·e·chiʹah the son of Aʹsa the son of El·kaʹnah, who was dwelling in the settlements of the Ne·tophʹa·thites.

[[v13-9-17]]

^<<v13-9-17,17>>^ And the gatekeepers were Shalʹlum and Akʹkub and Talʹmon and A·hiʹman and their brother Shalʹlum the head,

[[v13-9-18]]

^<<v13-9-18,18>>^ and up till then he was in the king’s gate to the east. These were the gatekeepers of the camps of the sons of Leʹvi.

[[v13-9-19]]

^<<v13-9-19,19>>^ And Shalʹlum the son of Koʹre the son of E·biʹa·saph the son of Koʹrah and his brothers of the house of his father the Koʹrah·ites, over the work of the service, the doorkeepers of the tent, and their fathers over the camp of Jehovah, the keepers of the entryway.

[[v13-9-20]]

^<<v13-9-20,20>>^ And it was Phinʹe·has the son of El·e·aʹzar that happened to be leader^&#42;1^ over them in the past. Jehovah was with him.

[NOTE]
====
. “Leader.” Heb., na·ghidhʹ; Lat., dux.
====

[[v13-9-21]]

^<<v13-9-21,21>>^ Zech·a·riʹah the son of Me·shel·e·miʹah was the gatekeeper of the entrance of the tent of meeting.

[[v13-9-22]]

^<<v13-9-22,22>>^ All of them who were selected as gatekeepers at the thresholds were two hundred and twelve. They were in their settlements by their genealogical enrollment. These David and Samuel the seer ordained^&#42;1^ in their office of trust.

[NOTE]
====
. Lit., “founded.”
====

[[v13-9-23]]

^<<v13-9-23,23>>^ And they and their sons were over the gates of the house of Jehovah, even the house of the tent, for guard service.

[[v13-9-24]]

^<<v13-9-24,24>>^ It was to the four directions^&#42;1^ that the gatekeepers came to be, to the east, to the west, to the north and to the south.

[NOTE]
====
. Lit., “the four winds.”
====

[[v13-9-25]]

^<<v13-9-25,25>>^ And their brothers in their settlements were to come in for seven days, from time to time, along with these.

[[v13-9-26]]

^<<v13-9-26,26>>^ For in office of trust there were four mighty men of the gatekeepers. They were Levites, and they proved to be in charge of the dining rooms and of the treasures of the house of the &#91;true&#93; God.

[[v13-9-27]]

^<<v13-9-27,27>>^ And all around the house of the &#91;true&#93; God they would spend the night; for guard service was upon them, and they were in charge of the key, even &#91;to open up&#93;^&#42;1^ from morning to morning.

[NOTE]
====
. “To open up,” inserted for sense; LXX reads: “to open up the doors of the temple.”
====

[[v13-9-28]]

^<<v13-9-28,28>>^ And some of them were in charge of the utensils of the service, for it was by number that they would bring them in and it was by number that they would take them out.

[[v13-9-29]]

^<<v13-9-29,29>>^ And some of them were men appointed over the utensils and over all the holy utensils and over the fine flour and the wine and the oil and the frankincense and the balsam oil.

[[v13-9-30]]

^<<v13-9-30,30>>^ And some of the sons of the priests were makers of the ointment mixture of balsam oil.

[[v13-9-31]]

^<<v13-9-31,31>>^ And Mat·ti·thiʹah of the Levites, who was the firstborn of Shalʹlum the Koʹrah·ite, was in the office of trust over the things baked in pans.

[[v13-9-32]]

^<<v13-9-32,32>>^ And some of the sons of the Koʹhath·ites, their brothers, were in charge of the layer bread, to prepare it sabbath by sabbath.

[[v13-9-33]]

^<<v13-9-33,33>>^ And these were the singers, the heads of the fathers of the Levites in the dining rooms, those set free from duty; for by day and by night it was their responsibility to be in the work.

[[v13-9-34]]

^<<v13-9-34,34>>^ These were the heads of the fathers of the Levites by their descendants, headmen. These were the ones that dwelt in Jerusalem.

[[v13-9-35]]

^<<v13-9-35,35>>^ And in Gibʹe·on was where the father of Gibʹe·on, Je·iʹel, dwelt. And his wife’s name was Maʹa·cah.

[[v13-9-36]]

^<<v13-9-36,36>>^ And his son, the firstborn, was Abʹdon, and Zur and Kish and Baʹal and Ner and Naʹdab,

[[v13-9-37]]

^<<v13-9-37,37>>^ and Geʹdor and A·hiʹo and Zech·a·riʹah and Mikʹloth.

[[v13-9-38]]

^<<v13-9-38,38>>^ As for Mikʹloth, he became father to Shimʹe·am. And it was really they that dwelt in front of their brothers in Jerusalem along with brothers of theirs.

[[v13-9-39]]

^<<v13-9-39,39>>^ As for Ner, he became father to Kish; Kish, in turn, became father to Saul; Saul, in turn, became father to Jonʹa·than and Malʹchi-shuʹa and A·binʹa·dab and Esh·baʹal.

[[v13-9-40]]

^<<v13-9-40,40>>^ And the son of Jonʹa·than was Merʹib-baʹal. As for Merʹib-baʹal, he became father to Miʹcah.

[[v13-9-41]]

^<<v13-9-41,41>>^ And the sons of Miʹcah were Piʹthon and Melʹech and Tahrʹe·a &#91;and Aʹhaz&#93;.^&#42;1^

[NOTE]
====
. “And Tahrea and Ahaz,” LXXLVgc; M, “and Tahrea.”
====

[[v13-9-42]]

^<<v13-9-42,42>>^ As for Aʹhaz, he became father to Jaʹrah; Jaʹrah, in turn, became father to Alʹe·meth and Azʹma·veth and Zimʹri. Zimʹri, in turn, became father to Moʹza.

[[v13-9-43]]

^<<v13-9-43,43>>^ As for Moʹza, he became father to Binʹe·a and Re·phaʹiah his son, El·e·aʹsah his son, Aʹzel his son.

[[v13-9-44]]

^<<v13-9-44,44>>^ And Aʹzel had six sons, and these were their names: Az·riʹkam, Boʹche·ru and Ishʹma·el and She·a·riʹah and O·ba·diʹah and Haʹnan. These were the sons of Aʹzel.

'''

xref:013-1-chronicles/013-1-chronicles-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-010.adoc#v13-10-0[Próximo Capítulo &#62;]