include::./index.adoc[]

[[v13-13-0]]
=== The First of Chronicles, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-13-1]]

^<<v13-13-1,1>>^ And David proceeded to consult with the chiefs of the thousands and of the hundreds and with every leader;

[[v13-13-2]]

^<<v13-13-2,2>>^ and David went on to say to all the congregation^&#42;1^ of Israel: “If it seems good to YOU and it is acceptable with Jehovah our God, let us send to our brothers that are left over in all the lands of Israel and with them &#91;to&#93; the priests and the Levites in their cities with pasture grounds, that they may collect themselves together to us.

[NOTE]
====
. “Congregation.” Gr., ek·kle·siʹai, “ecclesia.”
====

[[v13-13-3]]

^<<v13-13-3,3>>^ And let us bring the ark of our God around to ourselves.” For they had not cared for it in the days of Saul.

[[v13-13-4]]

^<<v13-13-4,4>>^ So all the congregation said to do that way, for the thing seemed right in the eyes of all the people.

[[v13-13-5]]

^<<v13-13-5,5>>^ Accordingly David congregated all Israel from the river of Egypt^&#42;1^ as far as the entering of Haʹmath,^&#42;2^ to bring the ark of the &#91;true&#93; God from Kirʹi·ath-jeʹa·rim.

[NOTE]
====
. “From the river of Egypt.” Heb., min-shi·chohrʹ Mits·raʹyim; Vgc(Lat.), a siʹhor Ae·gyʹpti.
. Lit., “and up to where one enters Hamath.”
====

[[v13-13-6]]

^<<v13-13-6,6>>^ And David and all Israel proceeded to go up to Baʹal·ah, to Kirʹi·ath-jeʹa·rim, which belongs to Judah, to bring up from there the ark of the &#91;true&#93; God, Jehovah, sitting on the cherubs, where &#91;his&#93; name is called on.

[[v13-13-7]]

^<<v13-13-7,7>>^ However, they had the ark of the &#91;true&#93; God ride upon a new wagon from the house of A·binʹa·dab, and Uzʹzah and A·hiʹo were leading the wagon.

[[v13-13-8]]

^<<v13-13-8,8>>^ And David and all Israel were celebrating before the &#91;true&#93; God with full power and with songs and with harps and with stringed instruments and with tambourines and with cymbals and with trumpets.

[[v13-13-9]]

^<<v13-13-9,9>>^ And they came gradually as far as the threshing floor of Chiʹdon, and Uzʹzah now thrust his hand out to grab hold of the Ark, for the bulls nearly caused an upset.

[[v13-13-10]]

^<<v13-13-10,10>>^ At that Jehovah’s anger blazed against Uzʹzah, so that he struck him down because he had thrust his hand out upon the Ark, and he died there before God.

[[v13-13-11]]

^<<v13-13-11,11>>^ And David became angry because Jehovah had broken through in a rupture against Uzʹzah; and that place came to be called Peʹrez-uzʹzah^&#42;1^ down to this day.

[NOTE]
====
. Meaning “Rupture Against Uzzah.”
====

[[v13-13-12]]

^<<v13-13-12,12>>^ And David became afraid of the &#91;true&#93; God on that day, saying: “How shall I bring the ark of the &#91;true&#93; God to me?”

[[v13-13-13]]

^<<v13-13-13,13>>^ And David did not remove the Ark to himself at the City of David, but he carried it aside to the house of Oʹbed-eʹdom the Gitʹtite.

[[v13-13-14]]

^<<v13-13-14,14>>^ And the ark of the &#91;true&#93; God kept dwelling with the household of Oʹbed-eʹdom, at his house three months; and Jehovah kept blessing the household of Oʹbed-eʹdom and all that was his.

'''

xref:013-1-chronicles/013-1-chronicles-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-014.adoc#v13-14-0[Próximo Capítulo &#62;]