include::./index.adoc[]

[[v13-19-0]]
=== The First of Chronicles, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-19-1]]

^<<v13-19-1,1>>^ And it came about afterward that Naʹhash the king of the sons of Amʹmon came to die, and his son began to reign in place of him.

[[v13-19-2]]

^<<v13-19-2,2>>^ At that David said: “I shall exercise loving-kindness toward Haʹnun the son of Naʹhash, because his father exercised loving-kindness toward me.” Accordingly David sent messengers to comfort him over his father, and the servants of David proceeded to come into the land of the sons of Amʹmon to Haʹnun to comfort him.

[[v13-19-3]]

^<<v13-19-3,3>>^ However, the princes of the sons of Amʹmon said to Haʹnun: “Is David honoring your father in your eyes in that he has sent comforters to you? Is it not for the sake of making a thorough search and causing an overthrow and for spying out the land that his servants have come in to you?”

[[v13-19-4]]

^<<v13-19-4,4>>^ So Haʹnun took the servants of David and shaved them and cut their garments in half to their buttocks and sent them away.

[[v13-19-5]]

^<<v13-19-5,5>>^ Later people went and told David about the men; and he at once sent to meet them, because they had become men very much humiliated; and the king went on to say: “Dwell in Jerʹi·cho until YOUR beards grow abundantly. Then YOU must return.”

[[v13-19-6]]

^<<v13-19-6,6>>^ In time the sons of Amʹmon saw that they had become foul-smelling to David, and Haʹnun and the sons of Amʹmon proceeded to send a thousand silver talents^&#42;1^ to hire for themselves chariots and horsemen from Mes·o·po·taʹmi·a^&#42;2^ and from Aʹram-maʹa·cah and from Zoʹbah.

[NOTE]
====
. See App 8A.
. See Ge 24:10 ftn.
====

[[v13-19-7]]

^<<v13-19-7,7>>^ Thus they hired for themselves thirty-two thousand chariots and the king of Maʹa·cah and his people. Then they came in and camped before Medʹe·ba; and as for the sons of Amʹmon, they gathered together from their cities and now came in for the war.

[[v13-19-8]]

^<<v13-19-8,8>>^ When David heard of it, he immediately sent Joʹab and all the army &#91;and&#93; the mighty men.^&#42;1^

[NOTE]
====
. Lit., “all the army​—⁠the mighty men.” See 2Sa (16:6; 20:7; 23:8).
====

[[v13-19-9]]

^<<v13-19-9,9>>^ And the sons of Amʹmon began to go out and draw up in battle formation at the entrance of the city, and the kings that had come were by themselves in the open field.

[[v13-19-10]]

^<<v13-19-10,10>>^ When Joʹab saw that the battle charges^&#42;1^ had come to be against him from the front and from the rear, he at once chose some of all the choice men in Israel and drew them up in formation to meet the Syrians.

[NOTE]
====
. Lit., “the face of the battle.”
====

[[v13-19-11]]

^<<v13-19-11,11>>^ And the rest of the people he gave into the hand of A·bishʹai his brother, that they might draw up in formation to meet the sons of Amʹmon.

[[v13-19-12]]

^<<v13-19-12,12>>^ And he went on to say: “If the Syrians become too strong for me, you must also serve as a salvation for me; but if the sons of Amʹmon themselves become too strong for you, I must also save you.

[[v13-19-13]]

^<<v13-19-13,13>>^ Be strong, that we may show ourselves courageous in behalf of our people and in behalf of the cities of our God; and as for Jehovah, what is good in his own eyes he will do.”

[[v13-19-14]]

^<<v13-19-14,14>>^ Then Joʹab and the people that were with him advanced before the Syrians to the battle, and they took to flight from before him.

[[v13-19-15]]

^<<v13-19-15,15>>^ As for the sons of Amʹmon, they saw that the Syrians had fled, and they themselves also took to flight from before A·bishʹai his brother and then came into the city. Later Joʹab came into Jerusalem.

[[v13-19-16]]

^<<v13-19-16,16>>^ When the Syrians saw that they had been defeated before Israel, they proceeded to send messengers and bring out the Syrians that were in the region of the River,^&#42;1^ with Shoʹphach^&#42;2^ the chief of the army of Had·ad·eʹzer before them.

[NOTE]
====
. That is, the Euphrates.
. “Shobach” in 2Sa 10:16.
====

[[v13-19-17]]

^<<v13-19-17,17>>^ When the report was made to David, he immediately gathered all Israel together and crossed the Jordan and came to them and drew up in formation against them. When David drew up in battle formation to meet the Syrians, they began to fight against him.

[[v13-19-18]]

^<<v13-19-18,18>>^ But the Syrians took to flight because of Israel; and David went killing of the Syrians seven thousand charioteers and forty thousand men on foot, and Shoʹphach the chief of the army himself he put to death.

[[v13-19-19]]

^<<v13-19-19,19>>^ When the servants of Had·ad·eʹzer saw that they had been defeated before Israel, they promptly made peace with David and began to serve him; and Syria did not want to try saving the sons of Amʹmon anymore.

'''

xref:013-1-chronicles/013-1-chronicles-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-020.adoc#v13-20-0[Próximo Capítulo &#62;]