include::./index.adoc[]

[[v13-5-0]]
=== The First of Chronicles, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-5-1]]

^<<v13-5-1,1>>^ And the sons of Reuʹben the firstborn of Israel—for he was the firstborn; but for his profaning the lounge of his father his right as firstborn was given to the sons of Joseph the son of Israel, so that he was not to be enrolled genealogically for the right of the firstborn.

[[v13-5-2]]

^<<v13-5-2,2>>^ For Judah himself proved to be superior among his brothers, and the one for leader was from him; but the right as firstborn was Joseph’s—

[[v13-5-3]]

^<<v13-5-3,3>>^ the sons of Reuʹben the firstborn of Israel were Haʹnoch and Palʹlu, Hezʹron and Carʹmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ The sons of Joel were She·maiʹah his son, Gog his son, Shimʹe·i his son,

[[v13-5-5]]

^<<v13-5-5,5>>^ Miʹcah his son, Re·aʹiah his son, Baʹal his son,

[[v13-5-6]]

^<<v13-5-6,6>>^ Be·erʹah his son, whom Tilʹgath-pil·neʹser the king of As·syrʹi·a took into exile, he being a chieftain of the Reuʹben·ites.

[[v13-5-7]]

^<<v13-5-7,7>>^ And his brothers by their families in the genealogical enrollment by their descendants were, as the head, Je·iʹel, and Zech·a·riʹah,

[[v13-5-8]]

^<<v13-5-8,8>>^ and Beʹla the son of Aʹzaz the son of Sheʹma the son of Joel—he was dwelling in A·roʹer and as far as Neʹbo and Baʹal-meʹon.

[[v13-5-9]]

^<<v13-5-9,9>>^ Even to the east he dwelt as far as where one enters the wilderness at the river Eu·phraʹtes, for their livestock itself had become numerous in the land of Gilʹe·ad.

[[v13-5-10]]

^<<v13-5-10,10>>^ And in the days of Saul they made war upon the Hagʹrites, who came to fall by their hand; and so they dwelt in their tents throughout all the country east^&#42;1^ of Gilʹe·ad.

[NOTE]
====
. Lit., “all the face of the east.”
====

[[v13-5-11]]

^<<v13-5-11,11>>^ As for the sons of Gad in front of them, they dwelt in the land of Baʹshan as far as Salʹe·cah.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel was the head, and Shaʹpham the second, and Jaʹnai and Shaʹphat in Baʹshan.

[[v13-5-13]]

^<<v13-5-13,13>>^ And their brothers belonging to the house of their forefathers were Miʹcha·el and Me·shulʹlam and Sheʹba and Joʹrai and Jaʹcan and Ziʹa and Eʹber, seven.

[[v13-5-14]]

^<<v13-5-14,14>>^ These were the sons of Abʹi·ha·il the son of Huʹri, the son of Ja·roʹah, the son of Gilʹe·ad, the son of Miʹcha·el, the son of Je·shishʹai, the son of Jahʹdo, the son of Buz;

[[v13-5-15]]

^<<v13-5-15,15>>^ Aʹhi the son of Abʹdi·el, the son of Guʹni, head of the house of their forefathers.

[[v13-5-16]]

^<<v13-5-16,16>>^ And they continued to dwell in Gilʹe·ad, in Baʹshan and in its dependent towns and in all the pasture grounds of Sharʹon as far as their terminations.

[[v13-5-17]]

^<<v13-5-17,17>>^ They were all of them enrolled genealogically in the days of Joʹtham the king of Judah and in the days of Jer·o·boʹam^&#42;1^ the king of Israel.

[NOTE]
====
. That is, Jeroboam II. See 2Ki 14:16-29.
====

[[v13-5-18]]

^<<v13-5-18,18>>^ As for the sons of Reuʹben and the Gadʹites and the half tribe of Ma·nasʹseh; of those who were valiant fellows, men carrying shield and sword and bending the bow^&#42;1^ and trained in war, there were forty-four thousand seven hundred and sixty going out to the army.

[NOTE]
====
. Lit., “treading the bow,” that is, often by planting the foot firmly against the middle of it.
====

[[v13-5-19]]

^<<v13-5-19,19>>^ And they began to make war upon the Hagʹrites, and Jeʹtur and Naʹphish and Noʹdab.

[[v13-5-20]]

^<<v13-5-20,20>>^ And they came to be helped against them, so that the Hagʹrites and all those who were with them were given into their hand, for it was to God that they called for aid in the war, and he let himself be entreated in their favor because they trusted in him.

[[v13-5-21]]

^<<v13-5-21,21>>^ And they got to take captive their livestock, their camels fifty thousand, and sheep two hundred and fifty thousand, and asses two thousand, and human souls^&#42;1^ a hundred thousand.

[NOTE]
====
. Lit., “and soul of man (mankind).” Heb., weneʹphesh ʼa·dhamʹ; Lat., et aʹni·mas hoʹmi·num.
====

[[v13-5-22]]

^<<v13-5-22,22>>^ For there were many that had fallen slain, because it was on the part of the &#91;true&#93; God that the fighting was. And they continued to dwell in their place down to the time of the exile.

[[v13-5-23]]

^<<v13-5-23,23>>^ As for the sons of the half tribe of Ma·nasʹseh, they dwelt in the land from Baʹshan to Baʹal-herʹmon and Seʹnir and Mount Herʹmon. They themselves became numerous.

[[v13-5-24]]

^<<v13-5-24,24>>^ And these were the heads of the house of their forefathers: Eʹpher and Ishʹi and Eʹli·el and Azʹri·el and Jeremiah and Hod·a·viʹah and Jahʹdi·el, men that were valiant, mighty fellows, men of fame,^&#42;1^ heads of the house of their forefathers.

[NOTE]
====
. Lit., “men of names.”
====

[[v13-5-25]]

^<<v13-5-25,25>>^ And they began to act unfaithfully toward the God of their forefathers and went having immoral intercourse with the gods of the peoples of the land, whom God had annihilated from before them.

[[v13-5-26]]

^<<v13-5-26,26>>^ Consequently the God of Israel stirred up the spirit of Pul the king of As·syrʹi·a even the spirit of Tilʹgath-pil·neʹser the king of As·syrʹi·a, so that he took into exile those of the Reuʹben·ites and of the Gadʹites and of the half tribe of Ma·nasʹseh and brought them to Haʹlah and Haʹbor and Haʹra and the river Goʹzan &#91;to continue&#93; until this day.^&#42;1^

[NOTE]
====
. LXXBagsterSyVg end chapter 5 here; MLXX continue to vs 41.
====

'''

xref:013-1-chronicles/013-1-chronicles-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-006.adoc#v13-6-0[Próximo Capítulo &#62;]