include::./index.adoc[]

[[v13-15-0]]
=== The First of Chronicles, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-15-1]]

^<<v13-15-1,1>>^ And he continued building houses for himself in the City of David; and he went on to prepare a place for the ark of the &#91;true&#93; God and pitch a tent for it.

[[v13-15-2]]

^<<v13-15-2,2>>^ It was then that David said: “No one is to carry the ark of the &#91;true&#93; God but the Levites, for they are the ones whom Jehovah has chosen to carry the ark of Jehovah^&#42;1^ and to minister to him to time indefinite.”

[NOTE]
====
. “Jehovah,” Al, Leningrad B 19A and many mss.
====

[[v13-15-3]]

^<<v13-15-3,3>>^ Then David congregated all Israel at Jerusalem to bring the ark of Jehovah up to its place that he had prepared for it.

[[v13-15-4]]

^<<v13-15-4,4>>^ And David proceeded to gather the sons of Aaron and the Levites;

[[v13-15-5]]

^<<v13-15-5,5>>^ of the sons of Koʹhath, U·riʹel the chief and his brothers, a hundred and twenty;

[[v13-15-6]]

^<<v13-15-6,6>>^ of the sons of Me·rarʹi, A·saiʹah the chief and his brothers, two hundred and twenty;

[[v13-15-7]]

^<<v13-15-7,7>>^ of the sons of Gerʹshom, Joel the chief and his brothers, a hundred and thirty;

[[v13-15-8]]

^<<v13-15-8,8>>^ of the sons of E·li·zaʹphan, She·maiʹah the chief and his brothers, two hundred;

[[v13-15-9]]

^<<v13-15-9,9>>^ of the sons of Heʹbron, Eʹli·el the chief and his brothers, eighty;

[[v13-15-10]]

^<<v13-15-10,10>>^ of the sons of Uzʹzi·el, Am·minʹa·dab the chief and his brothers, a hundred and twelve.

[[v13-15-11]]

^<<v13-15-11,11>>^ Furthermore, David called Zaʹdok and A·biʹa·thar the priests, and the Levites U·riʹel, A·saiʹah and Joel, She·maiʹah and Eʹli·el and Am·minʹa·dab,

[[v13-15-12]]

^<<v13-15-12,12>>^ and he went on to say to them: “YOU are the heads of the fathers of the Levites. Sanctify yourselves, YOU and YOUR brothers, and YOU must bring the ark of Jehovah the God of Israel up to the place that^&#42;1^ I have prepared for it.

[NOTE]
====
. “The place that,” TVg and four Heb. mss; M omits.
====

[[v13-15-13]]

^<<v13-15-13,13>>^ Because at the first time YOU did not, Jehovah our God broke through against us, for we did not search after him according to the custom.”

[[v13-15-14]]

^<<v13-15-14,14>>^ So the priests and the Levites sanctified themselves to bring up the ark of Jehovah the God of Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Then the sons of the Levites began to carry the ark of the &#91;true&#93; God, just as Moses had commanded by Jehovah’s word, upon their shoulders with the rods upon them.

[[v13-15-16]]

^<<v13-15-16,16>>^ David now said to the chiefs of the Levites to station their brothers the singers with the instruments of song, stringed instruments and harps and cymbals, playing aloud to cause a sound of rejoicing to arise.

[[v13-15-17]]

^<<v13-15-17,17>>^ Accordingly the Levites stationed Heʹman the son of Joel and, of his brothers, Aʹsaph the son of Ber·e·chiʹah; and, of the sons of Me·rarʹi their brothers, Eʹthan the son of Kush·aʹiah;

[[v13-15-18]]

^<<v13-15-18,18>>^ and with them their brothers of the second division, Zech·a·riʹah, Ben and Ja·aʹzi·el and She·mirʹa·moth and Je·hiʹel and Unʹni, E·liʹab and Be·naiʹah and Ma·a·seiʹah and Mat·ti·thiʹah and E·liphʹe·le·hu and Mik·neʹiah, and Oʹbed-eʹdom and Je·iʹel the gatekeepers,

[[v13-15-19]]

^<<v13-15-19,19>>^ and the singers Heʹman, Aʹsaph and Eʹthan, with the copper cymbals to play aloud;

[[v13-15-20]]

^<<v13-15-20,20>>^ and Zech·a·riʹah and Aʹzi·el and She·mirʹa·moth and Je·hiʹel and Unʹni and E·liʹab and Ma·a·seiʹah and Be·naiʹah with stringed instruments tuned to Alʹa·moth,^&#42;1^

[NOTE]
====
. “Alamoth,” an unexplained musical term. Lit., “young women.” Probably referring to the soprano voices of young women or the falsetto of boys.
====

[[v13-15-21]]

^<<v13-15-21,21>>^ and Mat·ti·thiʹah and E·liphʹe·le·hu and Mik·neʹiah and Oʹbed-eʹdom and Je·iʹel and Az·a·ziʹah with harps tuned to Shemʹi·nith,^&#42;1^ to act as directors;

[NOTE]
====
. “Sheminith.” Lit., “the eighth.” Possibly referring to the eighth key or a lower octave.
====

[[v13-15-22]]

^<<v13-15-22,22>>^ and Chen·a·niʹah the chief of the Levites in carrying, he giving instruction^&#42;1^ in carrying, for he was expert;

[NOTE]
====
. “He giving instruction.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v13-15-23]]

^<<v13-15-23,23>>^ and Ber·e·chiʹah and El·kaʹnah the gatekeepers for the Ark;

[[v13-15-24]]

^<<v13-15-24,24>>^ and Sheb·a·niʹah and Joshʹa·phat and Ne·thanʹel and A·maʹsai and Zech·a·riʹah and Be·naiʹah and E·li·eʹzer the priests loudly sounding the trumpets before the ark of the &#91;true&#93; God, and Oʹbed-eʹdom and Je·hiʹah the gatekeepers for the Ark.

[[v13-15-25]]

^<<v13-15-25,25>>^ And David and the older men of Israel and the chiefs of the thousands came to be the ones walking along to bring up the ark of the covenant of Jehovah from the house of Oʹbed-eʹdom with rejoicing.

[[v13-15-26]]

^<<v13-15-26,26>>^ And it came about when the &#91;true&#93; God helped the Levites while carrying the ark of the covenant of Jehovah that they proceeded to sacrifice seven young bulls and seven rams.

[[v13-15-27]]

^<<v13-15-27,27>>^ And David was dressed in a sleeveless coat of fine fabric, and also all the Levites carrying the Ark and the singers and Chen·a·niʹah the chief of the carrying by the singers; but upon David there was an ephʹod of linen.

[[v13-15-28]]

^<<v13-15-28,28>>^ And all the Israelites were bringing up the ark of the covenant of Jehovah with joyful shouting and with the sounding of the horn and with trumpets and with cymbals, playing aloud on stringed instruments and harps.

[[v13-15-29]]

^<<v13-15-29,29>>^ And it came about that, when the ark of the covenant of Jehovah came as far as the City of David, Miʹchal, Saul’s daughter, herself looked down through the window and got to see King David skipping about and celebrating; and she began to despise him in her heart.

'''

xref:013-1-chronicles/013-1-chronicles-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-016.adoc#v13-16-0[Próximo Capítulo &#62;]