include::./index.adoc[]

[[v13-22-0]]
=== The First of Chronicles, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-22-1]]

^<<v13-22-1,1>>^ Then David said: “This is the house of Jehovah the &#91;true&#93; God,^&#42;1^ and this is an altar for burnt offering for Israel.”

[NOTE]
====
. “Jehovah the [true] God.” Heb., Yehwahʹ ha·ʼElo·himʹ; the first occurrence of this expression; next occurrence in Ne 9:7. See Ge 2:4 ftn, “God.”
====

[[v13-22-2]]

^<<v13-22-2,2>>^ David now said to bring together the alien residents^&#42;1^ that were in the land of Israel, and then he set them as stone hewers to hew squared stones for building the house of the &#91;true&#93; God.

[NOTE]
====
. Or, “the sojourners.” Heb., hag·ge·rimʹ; LXXVg(Lat., pro·seʹly·ti), “the proselytes.”
====

[[v13-22-3]]

^<<v13-22-3,3>>^ And iron in great quantity for nails for the doors of the gates and for clamps David prepared, and also copper in such quantity as to be beyond weighing,

[[v13-22-4]]

^<<v13-22-4,4>>^ and also cedar timbers without number; for the Si·doʹni·ans and the Tyrʹi·ans brought in cedar timbers in great quantity to David.

[[v13-22-5]]

^<<v13-22-5,5>>^ Accordingly David said: “Solʹo·mon my son is young and delicate, and the house to be built to Jehovah is to be surpassingly magnificent for beauteous distinction^&#42;1^ to all the lands. Let me, then, make preparation for him.” So David made preparation in great quantities before his death.

[NOTE]
====
. Lit., “for a name and for beauty,” a figure of hendiadys. Compare Ge 3:16 ftn.
====

[[v13-22-6]]

^<<v13-22-6,6>>^ Moreover, he called Solʹo·mon his son that he might command him to build a house to Jehovah the God of Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ And David went on to say to Solʹo·mon his son: “As for myself, it became close to my heart to build a house to the name of Jehovah my God.

[[v13-22-8]]

^<<v13-22-8,8>>^ But Jehovah’s word came against me, saying, ‘Blood in great quantity you have spilled, and great wars you have waged. You will not build a house to my name, for a great deal of blood^&#42;1^ you have spilled on the earth before me.

[NOTE]
====
. Lit., “many bloods.”
====

[[v13-22-9]]

^<<v13-22-9,9>>^ Look! There is a son being born to you. He himself will prove to be a restful man,^&#42;1^ and I shall certainly give him rest from all his enemies all around; for Solʹo·mon^&#42;2^ is what his name will become, and peace and quietness I shall bestow upon Israel in his days.

[NOTE]
====
. Lit., “a man of calming (restfulness).”
. Meaning “Peaceable.”
====

[[v13-22-10]]

^<<v13-22-10,10>>^ It is he that will build a house to my name, and he himself will become a son to me, and I a father to him. And I shall certainly establish the throne of his kingship firmly over Israel to time indefinite.’

[[v13-22-11]]

^<<v13-22-11,11>>^ “Now, my son, may Jehovah prove to be with you, and you must prove successful and build the house of Jehovah your God, just as he has spoken concerning you.

[[v13-22-12]]

^<<v13-22-12,12>>^ Only may Jehovah give you discretion and understanding, and may he give you commandment concerning Israel even to keep the law of Jehovah your God.

[[v13-22-13]]

^<<v13-22-13,13>>^ In that case you will prove successful if you take care to carry out the regulations and the judicial decisions that Jehovah commanded Moses respecting Israel. Be courageous and strong. Do not be afraid nor be terrified.

[[v13-22-14]]

^<<v13-22-14,14>>^ And here during my affliction I have prepared for Jehovah’s house a hundred thousand talents of gold^&#42;1^ and a million^&#42;2^ talents of silver,^&#42;3^ and the copper and the iron there is no means of weighing because they have come to be in such quantity; and timbers and stones I have prepared, but to them you will make additions.

[NOTE]
====
. About $38,535,000,000, with gold at $350 (U.S.) per oz t.
. Lit., “a thousand thousands.”
. About $7,707,000,000, with silver at $7 (U.S.) per oz t.
====

[[v13-22-15]]

^<<v13-22-15,15>>^ And with you there are in great number doers of work, stone hewers and workers in stone and wood and every one skillful in every sort of work.

[[v13-22-16]]

^<<v13-22-16,16>>^ The gold, the silver and the copper and the iron there is no means of numbering. Rise and act, and may Jehovah prove to be with you.”

[[v13-22-17]]

^<<v13-22-17,17>>^ And David went on to command all the princes of Israel to help Solʹo·mon his son:

[[v13-22-18]]

^<<v13-22-18,18>>^ “Is not Jehovah YOUR God with YOU, and has he not given YOU rest all around? For he has given into my hand the inhabitants of the land, and the land has been subdued before Jehovah and before his people.

[[v13-22-19]]

^<<v13-22-19,19>>^ Now set YOUR heart and YOUR soul to inquire after Jehovah YOUR God, and rise and build the sanctuary of Jehovah the &#91;true&#93; God, to bring the ark of the covenant of Jehovah and the holy utensils of the &#91;true&#93; God to the house built to the name of Jehovah.”

'''

xref:013-1-chronicles/013-1-chronicles-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-023.adoc#v13-23-0[Próximo Capítulo &#62;]