include::./index.adoc[]

[[v13-8-0]]
=== The First of Chronicles, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-8-1]]

^<<v13-8-1,1>>^ As for Benjamin, he became father to Beʹla his firstborn, Ashʹbel the second and A·harʹah the third,

[[v13-8-2]]

^<<v13-8-2,2>>^ Noʹhah the fourth and Raʹpha the fifth.

[[v13-8-3]]

^<<v13-8-3,3>>^ And Beʹla came to have sons, Adʹdar and Geʹra and A·biʹhud,

[[v13-8-4]]

^<<v13-8-4,4>>^ and Ab·i·shuʹa and Naʹa·man and A·hoʹah,

[[v13-8-5]]

^<<v13-8-5,5>>^ and Geʹra and She·phuʹphan and Huʹram.

[[v13-8-6]]

^<<v13-8-6,6>>^ And these were the sons of Eʹhud. These were the heads of &#91;the houses of&#93; forefathers belonging to the inhabitants of Geʹba, and they proceeded to take them into exile at Manʹa·hath.

[[v13-8-7]]

^<<v13-8-7,7>>^ And Naʹa·man and A·hiʹjah; and Geʹra—he was the one that took them into exile, and he became father to Uzʹza and A·hiʹhud.

[[v13-8-8]]

^<<v13-8-8,8>>^ As for Sha·ha·raʹim, he became father to &#91;children&#93; in the field of Moʹab after he sent them away. Huʹshim and Baʹa·ra were his wives.

[[v13-8-9]]

^<<v13-8-9,9>>^ And by Hoʹdesh his wife he came to be father to Joʹbab and Zibʹi·a and Meʹsha and Malʹcam,

[[v13-8-10]]

^<<v13-8-10,10>>^ and Jeʹuz and Sa·chiʹa and Mirʹmah. These were his sons, heads of &#91;the houses of&#93; forefathers.

[[v13-8-11]]

^<<v13-8-11,11>>^ And by Huʹshim he became father to A·biʹtub and El·paʹal.

[[v13-8-12]]

^<<v13-8-12,12>>^ And the sons of El·paʹal were Eʹber and Miʹsham and Sheʹmed, who built Oʹno and Lod and its dependent towns,

[[v13-8-13]]

^<<v13-8-13,13>>^ and Be·riʹah and Sheʹma. These were heads of &#91;the houses of&#93; forefathers, belonging to the inhabitants of Aiʹja·lon. These were the ones that chased away the inhabitants of Gath.

[[v13-8-14]]

^<<v13-8-14,14>>^ And &#91;there were&#93; A·hiʹo,^&#42;1^ Shaʹshak and Jerʹe·moth,

[NOTE]
====
. “And [there were] Ahio,” M; LXXA,L, “And their brothers were.”
====

[[v13-8-15]]

^<<v13-8-15,15>>^ and Zeb·a·diʹah and Aʹrad and Eʹder,

[[v13-8-16]]

^<<v13-8-16,16>>^ and Miʹcha·el and Ishʹpah and Joʹha, the sons of Be·riʹah,

[[v13-8-17]]

^<<v13-8-17,17>>^ and Zeb·a·diʹah and Me·shulʹlam and Hizʹki and Heʹber,

[[v13-8-18]]

^<<v13-8-18,18>>^ and Ishʹme·rai and Iz·liʹah and Joʹbab, the sons of El·paʹal,

[[v13-8-19]]

^<<v13-8-19,19>>^ and Jaʹkim and Zichʹri and Zabʹdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ and E·li·eʹnai and Zilʹle·thai and Eʹli·el,

[[v13-8-21]]

^<<v13-8-21,21>>^ and A·daiʹah and Be·raʹiah and Shimʹrath, the sons of Shimʹe·i,

[[v13-8-22]]

^<<v13-8-22,22>>^ and Ishʹpan and Eʹber and Eʹli·el,

[[v13-8-23]]

^<<v13-8-23,23>>^ and Abʹdon and Zichʹri and Haʹnan,

[[v13-8-24]]

^<<v13-8-24,24>>^ and Han·a·niʹah and Eʹlam and An·tho·thiʹjah,

[[v13-8-25]]

^<<v13-8-25,25>>^ and Iph·deʹiah and Pe·nuʹel, the sons of Shaʹshak,

[[v13-8-26]]

^<<v13-8-26,26>>^ and Shamʹshe·rai and She·ha·riʹah and Ath·a·liʹah,

[[v13-8-27]]

^<<v13-8-27,27>>^ and Ja·a·re·shiʹah and E·liʹjah and Zichʹri, the sons of Je·roʹham.

[[v13-8-28]]

^<<v13-8-28,28>>^ These were heads of &#91;the houses of&#93; forefathers by their descendants, headmen. These were the ones that dwelt in Jerusalem.

[[v13-8-29]]

^<<v13-8-29,29>>^ And it was in Gibʹe·on that the father of Gibʹe·on, &#91;Je·iʹel,&#93;^&#42;1^ dwelt, and his wife’s name was Maʹa·cah.

[NOTE]
====
. “The father of Gibeon, Jeiel,” LXXL and 9:35.
====

[[v13-8-30]]

^<<v13-8-30,30>>^ And his son, the firstborn, was Abʹdon, and Zur and Kish and Baʹal and Naʹdab,

[[v13-8-31]]

^<<v13-8-31,31>>^ and Geʹdor and A·hiʹo and Zeʹcher.

[[v13-8-32]]

^<<v13-8-32,32>>^ As for Mikʹloth, he became father to Shimʹe·ah. And these really were the ones that dwelt in front of their brothers in Jerusalem along with brothers of theirs.

[[v13-8-33]]

^<<v13-8-33,33>>^ As for Ner, he became father to Kish; Kish, in turn, became father to Saul; Saul, in turn, became father to Jonʹa·than^&#42;1^ and Malʹchi-shuʹa and A·binʹa·dab and Esh·baʹal.

[NOTE]
====
. “Jonathan.” Heb., Yehoh·na·thanʹ.
====

[[v13-8-34]]

^<<v13-8-34,34>>^ And Jonʹa·than’s son was Merʹib-baʹal. As for Merʹib-baʹal, he became father to Miʹcah.

[[v13-8-35]]

^<<v13-8-35,35>>^ And the sons of Miʹcah were Piʹthon and Melʹech and Ta·reʹa and Aʹhaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ As for Aʹhaz, he became father to Je·hoʹad·dah; Je·hoʹad·dah, in turn, became father to Alʹe·meth and Azʹma·veth and Zimʹri. Zimʹri, in turn, became father to Moʹza;

[[v13-8-37]]

^<<v13-8-37,37>>^ Moʹza, in turn, became father to Binʹe·a, Raʹphah his son, El·e·aʹsah his son, Aʹzel his son.

[[v13-8-38]]

^<<v13-8-38,38>>^ And Aʹzel had six sons, and these were their names: Az·riʹkam, Boʹche·ru and Ishʹma·el and She·a·riʹah and O·ba·diʹah and Haʹnan. All these were the sons of Aʹzel.

[[v13-8-39]]

^<<v13-8-39,39>>^ And the sons of Eʹshek his brother were Uʹlam his firstborn, Jeʹush the second and E·liphʹe·let the third.

[[v13-8-40]]

^<<v13-8-40,40>>^ And the sons of Uʹlam came to be valiant, mighty men, bending the bow, and having many sons and grandsons, a hundred and fifty. All these were from the sons of Benjamin.

'''

xref:013-1-chronicles/013-1-chronicles-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-009.adoc#v13-9-0[Próximo Capítulo &#62;]