include::./index.adoc[]

[[v13-11-0]]
=== The First of Chronicles, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-11-1]]

^<<v13-11-1,1>>^ In time all the Israelites collected themselves together to David at Heʹbron, saying: “Look! We are your bone and your flesh.

[[v13-11-2]]

^<<v13-11-2,2>>^ Both yesterday and previously, even while Saul happened to be king, you were the one leading Israel out and bringing it in; and Jehovah your God proceeded to say to you, ‘You yourself will shepherd my people Israel, and you yourself will become leader over my people Israel.’”

[[v13-11-3]]

^<<v13-11-3,3>>^ So all the older men^&#42;1^ of Israel came to the king at Heʹbron and David concluded a covenant with them in Heʹbron before Jehovah; after which they anointed David as king over Israel, according to Jehovah’s word by means of Samuel.

[NOTE]
====
. Or, “elders.”
====

[[v13-11-4]]

^<<v13-11-4,4>>^ Later David and all Israel went to Jerusalem, that is to say, Jeʹbus, where the Jebʹu·sites were the inhabitants of the land.

[[v13-11-5]]

^<<v13-11-5,5>>^ And the inhabitants of Jeʹbus began to say to David: “You will not come in here.” Just the same, David proceeded to capture the stronghold of Zion, that is to say, the City of David.

[[v13-11-6]]

^<<v13-11-6,6>>^ So David said: “Anyone striking the Jebʹu·sites first, he will become head and prince.” And Joʹab the son of Ze·ruʹiah got to go up first, and he came to be head.

[[v13-11-7]]

^<<v13-11-7,7>>^ And David took up dwelling in the place difficult to approach. That is why they called it the City of David.

[[v13-11-8]]

^<<v13-11-8,8>>^ And he began to build the city all around, from the Mound even to the parts round about, but Joʹab himself brought to life the rest of the city.

[[v13-11-9]]

^<<v13-11-9,9>>^ And David went on getting greater and greater, for Jehovah of armies was with him.

[[v13-11-10]]

^<<v13-11-10,10>>^ Now these are the heads of the mighty men that belonged to David, holding strongly with him in his kingship together with all Israel, to make him king according to Jehovah’s word concerning Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ And this is the list of the mighty men that belonged to David: Ja·shoʹbe·am the son of a Hachʹmon·ite, the head of the three.^&#42;1^ He was brandishing his spear over three hundred slain at one time.

[NOTE]
====
. “Three,” LXXL; MLXXSyVg, “thirty.”
====

[[v13-11-12]]

^<<v13-11-12,12>>^ And after him there was El·e·aʹzar the son of Doʹdo the A·hoʹhite. He was among the three mighty men.

[[v13-11-13]]

^<<v13-11-13,13>>^ He it was that happened to be with David at Pas-damʹmim, where the Phi·lisʹtines had gathered themselves together for war. Now there happened to be a tract of the field full of barley, and the people, for their part, had fled because of the Phi·lisʹtines.

[[v13-11-14]]

^<<v13-11-14,14>>^ But he^&#42;1^ took his stand in the middle of the tract and delivered it, and kept striking down the Phi·lisʹtines, so that Jehovah saved with a great salvation.

[NOTE]
====
. “He,” LXXVg and 2Sa 23:12; MSyVgc, “they.”
====

[[v13-11-15]]

^<<v13-11-15,15>>^ And three of the thirty head ones proceeded to go down to the rock, to David at the cave of A·dulʹlam, while a camp of the Phi·lisʹtines was camping in the low plain of Rephʹa·im.

[[v13-11-16]]

^<<v13-11-16,16>>^ And David was then in the place hard to approach; and a garrison of the Phi·lisʹtines was then in Bethʹle·hem.

[[v13-11-17]]

^<<v13-11-17,17>>^ After a while David showed his craving and said: “O that I might have a drink of the water from the cistern of Bethʹle·hem, which is at the gate!”

[[v13-11-18]]

^<<v13-11-18,18>>^ At that the three forced their way into the camp of the Phi·lisʹtines and drew water from the cistern of Bethʹle·hem, which is at the gate, and came carrying and bringing it to David. And David did not consent to drink it, but poured it out to Jehovah.

[[v13-11-19]]

^<<v13-11-19,19>>^ And he went on to say: “It is unthinkable on my part, as regards my God, to do this! Is it the blood of these men that I should drink at the risk of their souls?^&#42;1^ For it was at the risk of their souls that they brought it.” And he did not consent to drink it. These are the things that the three mighty men did.

[NOTE]
====
. Or, “lives.”
====

[[v13-11-20]]

^<<v13-11-20,20>>^ As for A·bishʹai the brother of Joʹab, he himself became head of the three; and he was brandishing his spear over three hundred slain, and he had a reputation like the three.^&#42;1^

[NOTE]
====
. “He had a name among the three,” TLXXSyVg and many Heb. mss. See 2Sa 23:18.
====

[[v13-11-21]]

^<<v13-11-21,21>>^ Of the three^&#42;1^ he was more distinguished than the two others, and he came to be a chief to them; and yet he did not come up to the &#91;first&#93; three.

[NOTE]
====
. “Three,” MLXX; Sy, “thirty”; Vg, “second three.”
====

[[v13-11-22]]

^<<v13-11-22,22>>^ As for Be·naiʹah the son of Je·hoiʹa·da, the son of a valiant man, who did many deeds in Kabʹze·el, he himself struck down the two &#91;sons&#93; of Arʹi·el of Moʹab; and he himself descended and struck down a lion inside a waterpit in the day of snowfall.

[[v13-11-23]]

^<<v13-11-23,23>>^ And he it was that struck down the Egyptian man, a man of extraordinary size, of five cubits.^&#42;1^ And in the hand of the Egyptian there was a spear like the beam of loom workers; yet he went on down to him with a rod and snatched the spear away from the Egyptian’s hand and killed him with his own spear.

[NOTE]
====
. About 2.23 m (7.3 ft).
====

[[v13-11-24]]

^<<v13-11-24,24>>^ These things Be·naiʹah the son of Je·hoiʹa·da did, and he had a name among the three mighty men.

[[v13-11-25]]

^<<v13-11-25,25>>^ Although he was more distinguished than the thirty, yet to the rank of the &#91;first&#93; three he did not come. However, David put him over his own bodyguard.

[[v13-11-26]]

^<<v13-11-26,26>>^ As for the mighty men of the military forces, there were Asʹa·hel the brother of Joʹab, El·haʹnan the son of Doʹdo of Bethʹle·hem,

[[v13-11-27]]

^<<v13-11-27,27>>^ Shamʹmoth the Haʹro·rite, Heʹlez the Pelʹo·nite,

[[v13-11-28]]

^<<v13-11-28,28>>^ Iʹra the son of Ikʹkesh the Te·koʹite, Abi-eʹzer the Anʹa·thoth·ite,

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibʹbe·cai the Huʹshath·ite, Iʹlai the A·hoʹhite,

[[v13-11-30]]

^<<v13-11-30,30>>^ Maʹha·rai the Ne·tophʹa·thite, Heʹled the son of Baʹa·nah the Ne·tophʹa·thite,

[[v13-11-31]]

^<<v13-11-31,31>>^ Iʹthai the son of Riʹbai of Gibʹe·ah of the sons of Benjamin, Be·naiʹah the Pirʹa·thon·ite,

[[v13-11-32]]

^<<v13-11-32,32>>^ Huʹrai from the torrent valleys of Gaʹash, A·biʹel the Arʹbath·ite,

[[v13-11-33]]

^<<v13-11-33,33>>^ Azʹma·veth the Ba·haʹrum·ite, E·liʹah·ba the Sha·alʹbo·nite,

[[v13-11-34]]

^<<v13-11-34,34>>^ the sons of Haʹshem the Giʹzo·nite, Jonʹa·than the son of Shaʹgee the Harʹa·rite,

[[v13-11-35]]

^<<v13-11-35,35>>^ A·hiʹam the son of Saʹcar the Harʹa·rite, E·liʹphal the son of Ur,

[[v13-11-36]]

^<<v13-11-36,36>>^ Heʹpher the Me·cheʹrath·ite, A·hiʹjah the Pelʹo·nite,

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezʹro the Carʹmel·ite, Naʹa·rai the son of Ezʹbai,

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel the brother of Nathan, Mibʹhar the son of Hagʹri,

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeʹlek the Amʹmon·ite, Naʹha·rai the Be·rothʹite, the armor-bearer of Joʹab the son of Ze·ruʹiah,

[[v13-11-40]]

^<<v13-11-40,40>>^ Iʹra the Ithʹrite, Gaʹreb the Ithʹrite,

[[v13-11-41]]

^<<v13-11-41,41>>^ U·riʹah the Hitʹtite, Zaʹbad the son of Ahʹlai,

[[v13-11-42]]

^<<v13-11-42,42>>^ Adʹi·na the son of Shiʹza the Reuʹben·ite, a head of the Reuʹben·ites, by whom there were thirty;

[[v13-11-43]]

^<<v13-11-43,43>>^ Haʹnan the son of Maʹa·cah, and Joshʹa·phat the Mithʹnite,

[[v13-11-44]]

^<<v13-11-44,44>>^ Uz·ziʹa the Ashʹte·rath·ite, Shaʹma and Je·iʹel, the sons of Hoʹtham the A·roʹer·ite,

[[v13-11-45]]

^<<v13-11-45,45>>^ Je·diʹa·el the son of Shimʹri, and Joʹha his brother the Tiʹzite,

[[v13-11-46]]

^<<v13-11-46,46>>^ Eʹli·el the Maʹha·vite, and Jerʹi·bai and Josh·a·viʹah the sons of Elʹna·am, and Ithʹmah the Moʹab·ite.

[[v13-11-47]]

^<<v13-11-47,47>>^ Eʹli·el and Oʹbed and Ja·a·siʹel the Me·zoʹba·ite.

'''

xref:013-1-chronicles/013-1-chronicles-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-012.adoc#v13-12-0[Próximo Capítulo &#62;]