include::./index.adoc[]

[[v13-4-0]]
=== The First of Chronicles, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-4-1]]

^<<v13-4-1,1>>^ The sons of Judah were Peʹrez, Hezʹron and Carʹmi and Hur and Shoʹbal.

[[v13-4-2]]

^<<v13-4-2,2>>^ As for Re·aʹiah the son of Shoʹbal, he became father to Jaʹhath; Jaʹhath, in turn, became father to A·huʹmai and Laʹhad. These were the families of the Zoʹrath·ites.

[[v13-4-3]]

^<<v13-4-3,3>>^ And these were &#91;the sons of&#93; the father of Eʹtam: Jezʹre·el and Ishʹma and Idʹbash, (and the name of their sister was Haz·ze·lel·poʹni,)

[[v13-4-4]]

^<<v13-4-4,4>>^ and Pe·nuʹel the father of Geʹdor and Eʹzer the father of Huʹshah. These were the sons of Hur the firstborn of Ephʹra·thah the father of Bethʹle·hem.

[[v13-4-5]]

^<<v13-4-5,5>>^ And Ashʹhur the father of Te·koʹa came to have two wives, Heʹlah and Naʹa·rah.

[[v13-4-6]]

^<<v13-4-6,6>>^ In time Naʹa·rah bore to him A·huzʹzam and Heʹpher and Teʹme·ni and Ha·a·hashʹta·ri. These were the sons of Naʹa·rah.

[[v13-4-7]]

^<<v13-4-7,7>>^ And the sons of Heʹlah were Zeʹreth, Izʹhar^&#42;1^ and Ethʹnan.

[NOTE]
====
. “Izhar,” MVg; Mmargin, “and Zohar.”
====

[[v13-4-8]]

^<<v13-4-8,8>>^ As for Koz, he became father to Aʹnub and Zo·beʹbah and the families of A·harʹhel the son of Haʹrum.

[[v13-4-9]]

^<<v13-4-9,9>>^ And Jaʹbez came to be more honorable than his brothers; and it was his mother that called his name Jaʹbez, saying: “I have given him birth in pain.”

[[v13-4-10]]

^<<v13-4-10,10>>^ And Jaʹbez began to call upon the God of Israel, saying: “If you will without fail bless me and actually enlarge my territory and your hand really proves to be with me, and you really preserve &#91;me&#93; from calamity, that it may not hurt me,—” Accordingly God brought &#91;to pass&#93; what he had asked.

[[v13-4-11]]

^<<v13-4-11,11>>^ As for Cheʹlub^&#42;1^ the brother of Shuʹhah, he became father to Meʹhir, who was the father of Eshʹton.

[NOTE]
====
. “Chelub,” M; LXXSyVgc, “Caleb.”
====

[[v13-4-12]]

^<<v13-4-12,12>>^ Eshʹton, in turn, became father to Beth-raʹpha and Pa·seʹah and Te·hinʹnah the father of Ir-naʹhash. These were the men of Reʹcah.

[[v13-4-13]]

^<<v13-4-13,13>>^ And the sons of Keʹnaz were Othʹni·el and Se·raiʹah, and the sons of Othʹni·el, Haʹthath.

[[v13-4-14]]

^<<v13-4-14,14>>^ As for Me·oʹno·thai, he became father to Ophʹrah. As for Se·raiʹah, he became father to Joʹab the father of Ge-harʹa·shim;^&#42;1^ for craftsmen are what they became.

[NOTE]
====
. Meaning “Valley of Craftsmen.”
====

[[v13-4-15]]

^<<v13-4-15,15>>^ And the sons of Caʹleb the son of Je·phunʹneh were Iʹru, Eʹlah and Naʹam; and the sons of Eʹlah, Keʹnaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ And the sons of Je·halʹle·lel were Ziph and Ziʹphah, Tirʹi·a and Asʹa·rel.

[[v13-4-17]]

^<<v13-4-17,17>>^ And the sons of Ezʹrah were Jeʹther and Meʹred and Eʹpher and Jaʹlon; and she got to conceive Mirʹi·am and Shamʹmai and Ishʹbah the father of Esh·te·moʹa.

[[v13-4-18]]

^<<v13-4-18,18>>^ As for his Jewish wife, she gave birth to Jeʹred the father of Geʹdor and Heʹber the father of Soʹco and Je·kuʹthi·el the father of Za·noʹah. And these were the sons of Bi·thiʹah the daughter of Pharʹaoh, whom Meʹred took.

[[v13-4-19]]

^<<v13-4-19,19>>^ And the sons of Ho·diʹah’s wife, the sister of Naʹham, were the father of Keiʹlah the Garʹmite and Esh·te·moʹa the Ma·acʹa·thite.

[[v13-4-20]]

^<<v13-4-20,20>>^ And the sons of Shiʹmon were Amʹnon and Rinʹnah, Ben-haʹnan and Tiʹlon. And the sons of Ishʹi were Zoʹheth and Ben-zoʹheth.

[[v13-4-21]]

^<<v13-4-21,21>>^ The sons of Sheʹlah the son of Judah were Er the father of Leʹcah and Laʹa·dah the father of Ma·reʹshah and the families of the house of the workers of fine fabric of the house of Ash·beʹa;

[[v13-4-22]]

^<<v13-4-22,22>>^ and Joʹkim and the men of Co·zeʹba and Joʹash and Saʹraph, who became owners of Moʹab·ite wives,^&#42;1^ and Jashʹu·bi-leʹhem. And the sayings are of old tradition.

[NOTE]
====
. Or, “who ruled in Moab.”
====

[[v13-4-23]]

^<<v13-4-23,23>>^ They were the potters and the inhabitants of Ne·taʹim and Ge·deʹrah. It was with the king in his work that they dwelt there.

[[v13-4-24]]

^<<v13-4-24,24>>^ The sons of Simʹe·on were Nemʹu·el and Jaʹmin, Jaʹrib, Zeʹrah, Shaʹul,

[[v13-4-25]]

^<<v13-4-25,25>>^ Shalʹlum his son, Mibʹsam his son, Mishʹma his son.

[[v13-4-26]]

^<<v13-4-26,26>>^ And the sons of Mishʹma were Hamʹmu·el his son, Zacʹcur his son, Shimʹe·i his son.

[[v13-4-27]]

^<<v13-4-27,27>>^ And Shimʹe·i had sixteen sons and six daughters; but his brothers did not have many sons, and none of their families had as many as the sons of Judah.

[[v13-4-28]]

^<<v13-4-28,28>>^ And they continued to dwell in Beʹer-sheʹba and Mo·laʹdah and Haʹzar-shuʹal

[[v13-4-29]]

^<<v13-4-29,29>>^ and in Bilʹhah and in Eʹzem and in Toʹlad

[[v13-4-30]]

^<<v13-4-30,30>>^ and in Be·thuʹel and in Horʹmah and in Zikʹlag

[[v13-4-31]]

^<<v13-4-31,31>>^ and in Beth-marʹca·both and in Haʹzar-suʹsim and in Beth-birʹi and in Shaʹa·raʹim. These were their cities down till David reigned.

[[v13-4-32]]

^<<v13-4-32,32>>^ And their settlements were Eʹtam and Aʹin, Rimʹmon and Toʹchen and Aʹshan, five cities.

[[v13-4-33]]

^<<v13-4-33,33>>^ And all their settlements that were all around these cities were as far as Baʹal. These were their dwelling places and their genealogical enrollments for them.

[[v13-4-34]]

^<<v13-4-34,34>>^ And Me·shoʹbab and Jamʹlech and Joʹshah the son of Am·a·ziʹah,

[[v13-4-35]]

^<<v13-4-35,35>>^ and Joel and Jeʹhu the son of Josh·i·biʹah the son of Se·raiʹah the son of Asʹi·el,

[[v13-4-36]]

^<<v13-4-36,36>>^ and Eli·o·eʹnai and Ja·a·koʹbah and Jesh·o·haiʹah and A·saiʹah and Adʹi·el and Je·simʹi·el and Be·naiʹah,

[[v13-4-37]]

^<<v13-4-37,37>>^ and Ziʹza the son of Shiʹphi the son of Alʹlon the son of Je·daʹiah the son of Shimʹri the son of She·maiʹah.

[[v13-4-38]]

^<<v13-4-38,38>>^ These who came in by names were the chieftains among their families, and the household itself of their forefathers increased in multitude.

[[v13-4-39]]

^<<v13-4-39,39>>^ And they proceeded to go to the entryway of Geʹdor, clear to the east of the valley, to look for pasturage for their flocks.

[[v13-4-40]]

^<<v13-4-40,40>>^ Eventually they found fat and good pasturage, and the land was quite wide^&#42;1^ and having no disturbance but at ease; for those dwelling there in former times were of Ham.

[NOTE]
====
. Lit., “was wide on both (all) sides,” that is, spacious.
====

[[v13-4-41]]

^<<v13-4-41,41>>^ And these written down by &#91;their&#93; names proceeded to come in in the days of Hez·e·kiʹah^&#42;1^ the king of Judah and strike down the tents of the Hamʹites^&#42;2^ and the Me·uʹnim that were to be found there, so that they devoted them to destruction down to this day; and they began to dwell in their place, because there was pasturage for their flocks there.

[NOTE]
====
. See 2Ki 20:10 ftn.
. “The tents of the Hamites,” by a correction; M, “their tents.”
====

[[v13-4-42]]

^<<v13-4-42,42>>^ And from them there were some of the sons of Simʹe·on that went to Mount Seʹir, five hundred men, with Pel·a·tiʹah and Ne·a·riʹah and Re·phaʹiah and Uzʹzi·el the sons of Ishʹi at their head.

[[v13-4-43]]

^<<v13-4-43,43>>^ And they proceeded to strike down the remnant that had escaped of Amʹa·lek, and they continued to dwell there down to this day.

'''

xref:013-1-chronicles/013-1-chronicles-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-005.adoc#v13-5-0[Próximo Capítulo &#62;]