include::./index.adoc[]

[[v13-21-0]]
=== The First of Chronicles, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-21-1]]

^<<v13-21-1,1>>^ And Satan^&#42;1^ proceeded to stand up against Israel and to incite David to number Israel.

[NOTE]
====
. Or, “a resister.” Heb., Sa·tanʹ; Syr., Sa·ta·naʼ; Gr., Di·aʹbo·los; Lat., Saʹtan.
====

[[v13-21-2]]

^<<v13-21-2,2>>^ So David said to Joʹab and the chiefs of the people: “Go, count Israel from Beʹer-sheʹba to Dan and bring it to me that I may know their number.”

[[v13-21-3]]

^<<v13-21-3,3>>^ But Joʹab said: “May Jehovah add to his people a hundred times as many as they are. Do they not, O my lord the king, all of them belong to my lord as servants? Why does my lord seek this? Why should he become a cause of guilt to Israel?”

[[v13-21-4]]

^<<v13-21-4,4>>^ The king’s word, however, prevailed over Joʹab, so that Joʹab went out and walked through all Israel, after which he came to Jerusalem.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joʹab now gave the number of the registration of the people to David; and all Israel amounted to a million^&#42;1^ one hundred thousand men drawing sword, and Judah four hundred and seventy thousand men drawing sword.

[NOTE]
====
. Lit., “a thousand thousands.”
====

[[v13-21-6]]

^<<v13-21-6,6>>^ And Leʹvi and Benjamin he did not register in among them, because the king’s word had been detestable to Joʹab.

[[v13-21-7]]

^<<v13-21-7,7>>^ Now this thing was bad in the eyes of the &#91;true&#93; God, and so he struck down Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Consequently David said to the &#91;true&#93; God: “I have sinned very much in that I have done this thing. And now, please, cause your servant’s error to pass away; for I have acted very foolishly.”

[[v13-21-9]]

^<<v13-21-9,9>>^ And Jehovah proceeded to speak to Gad, David’s visionary, saying:

[[v13-21-10]]

^<<v13-21-10,10>>^ “Go, and you must speak to David, saying, ‘This is what Jehovah has said: “There are three things that I am directing against you. Choose for yourself one of them, that I may do it to you.”’”

[[v13-21-11]]

^<<v13-21-11,11>>^ Accordingly Gad went in to David and said to him: “This is what Jehovah has said, ‘Take your pick,

[[v13-21-12]]

^<<v13-21-12,12>>^ whether for three years there is to be a famine; or for three months there is to be a sweeping away from before your adversaries and for the sword of your enemies to overtake &#91;you&#93;, or for three days there is to be the sword of Jehovah, even pestilence, in the land, with Jehovah’s angel bringing ruin in all the territory of Israel.’ And now see what I should reply to the One sending me.”

[[v13-21-13]]

^<<v13-21-13,13>>^ So David said to Gad: “It is very distressing to me. Please, let me fall into the hand of Jehovah, for very many are his mercies; but into the hand of man do not let me fall.”

[[v13-21-14]]

^<<v13-21-14,14>>^ Then Jehovah gave a pestilence in Israel, so that out of Israel seventy thousand persons fell.

[[v13-21-15]]

^<<v13-21-15,15>>^ Moreover, the &#91;true&#93; God sent an angel to Jerusalem to bring ruin to it; and as soon as he began bringing the ruin, Jehovah saw it and began to feel regret over the calamity; and so he said to the angel that was bringing the ruin: “It is enough! Now let your hand drop.” And Jehovah’s angel was standing close by the threshing floor of Orʹnan^&#42;1^ the Jebʹu·site.

[NOTE]
====
. “Araunah” in 2Sa 24:16.
====

[[v13-21-16]]

^<<v13-21-16,16>>^ When David raised his eyes, he got to see Jehovah’s angel standing between the earth and the heavens with his drawn sword in his hand extended toward Jerusalem; and David and the older men, covered with sackcloth, at once fell down upon their faces.

[[v13-21-17]]

^<<v13-21-17,17>>^ And David proceeded to say to the &#91;true&#93; God: “Was it not I that said to make a numbering of the people, and is it not I^&#42;1^ that have sinned and have unquestionably done bad? As for these sheep, what have they done? O Jehovah my God, let your hand, please, come to be upon me and my father’s house; but not upon your people, for a scourge.”

[NOTE]
====
. “And is it not I.” Lit., “and I am he.” Heb., wa·ʼani-huʼʹ; Gr., e·goʹ ei·miʹ. The expression ʼaniʹ huʼ, “I am he,” is used here by a man, David. Elsewhere in M this expression is used by God. See De 32:39; Isa (41:4; 43:10, 13; 46:4; 48:12; 52:6).
====

[[v13-21-18]]

^<<v13-21-18,18>>^ And Jehovah’s angel, for his part, said to Gad to say to David that David should go up to erect an altar to Jehovah on the threshing floor of Orʹnan the Jebʹu·site.

[[v13-21-19]]

^<<v13-21-19,19>>^ Accordingly David went up at the word of Gad that he had spoken in the name of Jehovah.

[[v13-21-20]]

^<<v13-21-20,20>>^ Meantime, Orʹnan turned back and saw the angel; and his four sons with him were hiding themselves. Now Orʹnan had been threshing wheat.

[[v13-21-21]]

^<<v13-21-21,21>>^ So David came as far as Orʹnan. When Orʹnan looked and saw David, he immediately went out of the threshing floor and bowed down to David with his face to the earth.

[[v13-21-22]]

^<<v13-21-22,22>>^ Then David said to Orʹnan: “Do give me the place of the threshing floor, that I may build in it an altar to Jehovah. For the money in full give it to me, that the scourge may be halted from upon the people.”

[[v13-21-23]]

^<<v13-21-23,23>>^ But Orʹnan said to David: “Take it as your own, and let my lord the king do what is good in his own eyes. See, I do give the cattle for burnt offerings and the threshing sledge for the wood and the wheat as a grain offering. The whole I do give.”

[[v13-21-24]]

^<<v13-21-24,24>>^ However, King David said to Orʹnan: “No, but without fail I shall make the purchase for the money in full, because I shall not carry what is yours to Jehovah to offer up burnt sacrifices without cost.”

[[v13-21-25]]

^<<v13-21-25,25>>^ So David gave Orʹnan for the place gold shekels^&#42;1^ to the weight of six hundred.

[NOTE]
====
. See App 8A.
====

[[v13-21-26]]

^<<v13-21-26,26>>^ Then David built there an altar to Jehovah and offered up burnt sacrifices and communion sacrifices, and he proceeded to call upon Jehovah, who now answered him with fire from the heavens upon the altar of burnt offering.

[[v13-21-27]]

^<<v13-21-27,27>>^ Moreover, Jehovah said the word to the angel, who accordingly returned his sword to its sheath.

[[v13-21-28]]

^<<v13-21-28,28>>^ At that time, when David saw that Jehovah had answered him at the threshing floor of Orʹnan the Jebʹu·site, he continued to sacrifice there.

[[v13-21-29]]

^<<v13-21-29,29>>^ But the tabernacle of Jehovah that Moses had made in the wilderness and the altar of burnt offering were at that time on the high place at Gibʹe·on.

[[v13-21-30]]

^<<v13-21-30,30>>^ And David had not been able to go before it to consult God,^&#42;1^ for he had been terrified because of the sword of Jehovah’s angel.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Gr., The·onʹ; Sy, “Jehovah”; Lat., Deʹum.
====

'''

xref:013-1-chronicles/013-1-chronicles-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-022.adoc#v13-22-0[Próximo Capítulo &#62;]