include::./index.adoc[]

[[v13-25-0]]
=== The First of Chronicles, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v13-25-1]]

^<<v13-25-1,1>>^ Further, David and the chiefs of the service groups separated for the service some of the sons of Aʹsaph, Heʹman and Je·duʹthun the ones prophesying with the harps, with the stringed instruments and with the cymbals. And from their number the official men for their service came to be.

[[v13-25-2]]

^<<v13-25-2,2>>^ Of the sons of Aʹsaph, Zacʹcur and Joseph and Neth·a·niʹah and Ash·a·reʹlah, the sons of Aʹsaph under the control of Aʹsaph the one prophesying under the control of the king.

[[v13-25-3]]

^<<v13-25-3,3>>^ Of Je·duʹthun: the sons of Je·duʹthun, Ged·a·liʹah and Zeʹri and Je·shaʹiah, &#91;and Shimʹe·i,&#93;^&#42;1^ Hash·a·biʹah and Mat·ti·thiʹah, six, under the control of their father Je·duʹthun, who was prophesying with the harp for thanking and praising Jehovah.

[NOTE]
====
. “And Shimei,” LXX and one Heb. ms. See vs 17.
====

[[v13-25-4]]

^<<v13-25-4,4>>^ Of Heʹman: the sons of Heʹman, Buk·kiʹah, Mat·ta·niʹah, Uzʹzi·el, Shebʹu·el^&#42;1^ and Jerʹi·moth, Han·a·niʹah, Ha·naʹni, E·liʹa·thah, Gid·dalʹti and Ro·mamʹti-eʹzer, Josh·be·kashʹah, Mal·loʹthi, Hoʹthir, Ma·haʹzi·oth.

[NOTE]
====
. “Shubael,” LXX, as in vs 20 and 24:20.
====

[[v13-25-5]]

^<<v13-25-5,5>>^ All these were sons of Heʹman, a visionary of the king in the things of the &#91;true&#93; God to raise up his horn; thus the &#91;true&#93; God proceeded to give Heʹman fourteen sons and three daughters.

[[v13-25-6]]

^<<v13-25-6,6>>^ All these were under the control of their father in song at the house of Jehovah, with cymbals, stringed instruments and harps for the service of the house of the &#91;true&#93; God.
Under the control of the king were Aʹsaph and Je·duʹthun and Heʹman.

[[v13-25-7]]

^<<v13-25-7,7>>^ And the number of them together with their brothers trained in song to Jehovah, all experts, came to be two hundred and eighty-eight.

[[v13-25-8]]

^<<v13-25-8,8>>^ So they cast lots as to the things to be taken care of, the little being just the same as the great, the expert along with the learner.

[[v13-25-9]]

^<<v13-25-9,9>>^ And the lot proceeded to come out: the first belonging to Aʹsaph for Joseph, for Ged·a·liʹah the second (he and his brothers and his sons were twelve);

[[v13-25-10]]

^<<v13-25-10,10>>^ the third for Zacʹcur, his sons and his brothers, twelve;

[[v13-25-11]]

^<<v13-25-11,11>>^ the fourth for Izʹri, his sons and his brothers, twelve;

[[v13-25-12]]

^<<v13-25-12,12>>^ the fifth for Neth·a·niʹah, his sons and his brothers, twelve;

[[v13-25-13]]

^<<v13-25-13,13>>^ the sixth for Buk·kiʹah, his sons and his brothers, twelve;

[[v13-25-14]]

^<<v13-25-14,14>>^ the seventh for Jesh·a·reʹlah, his sons and his brothers, twelve;

[[v13-25-15]]

^<<v13-25-15,15>>^ the eighth for Je·shaʹiah, his sons and his brothers, twelve;

[[v13-25-16]]

^<<v13-25-16,16>>^ the ninth for Mat·ta·niʹah, his sons and his brothers, twelve;

[[v13-25-17]]

^<<v13-25-17,17>>^ the tenth for Shimʹe·i, his sons and his brothers, twelve;

[[v13-25-18]]

^<<v13-25-18,18>>^ the eleventh for Azʹar·el, his sons and his brothers, twelve;

[[v13-25-19]]

^<<v13-25-19,19>>^ the twelfth for Hash·a·biʹah, his sons and his brothers, twelve;

[[v13-25-20]]

^<<v13-25-20,20>>^ for the thirteenth, Shuʹba·el, his sons and his brothers, twelve;

[[v13-25-21]]

^<<v13-25-21,21>>^ for the fourteenth, Mat·ti·thiʹah, his sons and his brothers, twelve;

[[v13-25-22]]

^<<v13-25-22,22>>^ for the fifteenth, for Jerʹe·moth, his sons and his brothers, twelve;

[[v13-25-23]]

^<<v13-25-23,23>>^ for the sixteenth, for Han·a·niʹah, his sons and his brothers, twelve;

[[v13-25-24]]

^<<v13-25-24,24>>^ for the seventeenth, for Josh·be·kashʹah, his sons and his brothers, twelve;

[[v13-25-25]]

^<<v13-25-25,25>>^ for the eighteenth, for Ha·naʹni, his sons and his brothers, twelve;

[[v13-25-26]]

^<<v13-25-26,26>>^ for the nineteenth, for Mal·loʹthi, his sons and his brothers, twelve;

[[v13-25-27]]

^<<v13-25-27,27>>^ for the twentieth, for E·liʹa·thah, his sons and his brothers, twelve;

[[v13-25-28]]

^<<v13-25-28,28>>^ for the twenty-first, for Hoʹthir, his sons and his brothers, twelve;

[[v13-25-29]]

^<<v13-25-29,29>>^ for the twenty-second, for Gid·dalʹti, his sons and his brothers, twelve;

[[v13-25-30]]

^<<v13-25-30,30>>^ for the twenty-third, for Ma·haʹzi·oth, his sons and his brothers, twelve;

[[v13-25-31]]

^<<v13-25-31,31>>^ for the twenty-fourth, for Ro·mamʹti-eʹzer, his sons and his brothers, twelve.

'''

xref:013-1-chronicles/013-1-chronicles-024.adoc#v13-24-0[&#60; Capítulo Anterior] | <<v13-25-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-026.adoc#v13-26-0[Próximo Capítulo &#62;]