include::./index.adoc[]

[[v54-6-0]]
=== The First to Timothy, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v54-6-1]]

^<<v54-6-1,1>>^ Let as many as are slaves under a yoke keep on considering their owners worthy of full honor, that the name of God and the teaching may never be spoken of injuriously.

[[v54-6-2]]

^<<v54-6-2,2>>^ Moreover, let those having believing owners not look down on them, because they are brothers. On the contrary, let them the more readily be slaves, because those receiving the benefit of their good service^&#42;1^ are believers and beloved.
Keep on teaching these things and giving these exhortations.

[NOTE]
====
. “Those receiving the benefit of their good service,” אA; J7,​8, “those partaking of the good of Jehovah on earth.”
====

[[v54-6-3]]

^<<v54-6-3,3>>^ If any man teaches other doctrine and does not assent to healthful words, those of our Lord Jesus Christ, nor to the teaching that accords with godly devotion,^&#42;1^

[NOTE]
====
. “Godly devotion,” אAVg; J7,​8, “fear of Jehovah.”
====

[[v54-6-4]]

^<<v54-6-4,4>>^ he is puffed up &#91;with pride&#93;, not understanding anything, but being mentally diseased over questionings and debates about words. From these things spring envy, strife, abusive speeches, wicked suspicions,

[[v54-6-5]]

^<<v54-6-5,5>>^ violent disputes about trifles^&#42;1^ on the part of men corrupted in mind and despoiled of the truth, thinking that godly devotion is a means of gain.

[NOTE]
====
. Or, “mutual irritations.”
====

[[v54-6-6]]

^<<v54-6-6,6>>^ To be sure, it is a means of great gain, &#91;this&#93; godly devotion^&#42;1^ along with self-sufficiency.^&#42;2^

[NOTE]
====
. “Godly devotion,” אAVg; J7,​8, “fear of Jehovah.”
. Or, “with contentment.”
====

[[v54-6-7]]

^<<v54-6-7,7>>^ For we have brought nothing into the world, and neither can we carry anything out.

[[v54-6-8]]

^<<v54-6-8,8>>^ So, having sustenance and covering, we shall be content with these things.

[[v54-6-9]]

^<<v54-6-9,9>>^ However, those who are determined to be rich fall into temptation and a snare and many senseless and hurtful desires, which plunge men into destruction and ruin.

[[v54-6-10]]

^<<v54-6-10,10>>^ For the love of money is a root of all sorts of injurious things,^&#42;1^ and by reaching out for this love some have been led astray from the faith and have stabbed themselves all over with many pains.

[NOTE]
====
. Or, “of all the injurious things.”
====

[[v54-6-11]]

^<<v54-6-11,11>>^ However, you, O man of God, flee from these things. But pursue righteousness, godly devotion,^&#42;1^ faith, love, endurance, mildness of temper.

[NOTE]
====
. “Godly devotion,” AVgSyp; J7,​8, “fear of Jehovah.”
====

[[v54-6-12]]

^<<v54-6-12,12>>^ Fight the fine fight of the faith,^&#42;1^ get a firm hold on the everlasting life for which you were called and you offered the fine public declaration in front of many witnesses.

[NOTE]
====
. Or, “Contend for victory in the right contest of the faith.”
====

[[v54-6-13]]

^<<v54-6-13,13>>^ In the sight of God, who preserves all things alive,^&#42;1^ and of Christ Jesus,^&#42;2^ who as a witness made the fine public declaration before Pontius Pilate, I give you orders

[NOTE]
====
. Or, “who brings all things to life.”
. See App 6E.
====

[[v54-6-14]]

^<<v54-6-14,14>>^ that you observe the commandment in a spotless and irreprehensible way until the manifestation of our Lord Jesus Christ.

[[v54-6-15]]

^<<v54-6-15,15>>^ This &#91;manifestation&#93; the happy and only Potentate will show in its^&#42;1^ own appointed times, &#91;he&#93; the King of those who rule as kings and Lord of those who rule as lords,

[NOTE]
====
. Or, “his.”
====

[[v54-6-16]]

^<<v54-6-16,16>>^ the one alone having immortality,^&#42;1^ who dwells in unapproachable light, whom not one of men has seen or can see. To him be honor and might everlasting. Amen.

[NOTE]
====
. Lit., “deathlessness.” Gr., a·tha·na·siʹan; Lat., in·mor·ta·li·taʹtem.
====

[[v54-6-17]]

^<<v54-6-17,17>>^ Give orders to those who are rich in the present system of things^&#42;1^ not to be high-minded,^&#42;2^ and to rest their hope, not on uncertain riches, but on God, who furnishes us all things richly for our enjoyment;

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹni; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
. Or, “haughty; arrogant.”
====

[[v54-6-18]]

^<<v54-6-18,18>>^ to work at good, to be rich in fine works, to be liberal, ready to share,

[[v54-6-19]]

^<<v54-6-19,19>>^ safely treasuring up for themselves a fine foundation for the future, in order that they may get a firm hold on the real life.

[[v54-6-20]]

^<<v54-6-20,20>>^ O Timothy, guard what is laid up in trust with you, turning away from the empty speeches that violate what is holy and from the contradictions of the falsely called “knowledge.”

[[v54-6-21]]

^<<v54-6-21,21>>^ For making a show of such &#91;knowledge&#93; some have deviated from the faith.
May the undeserved kindness be with YOU people.

'''

xref:054-1-timothy/054-1-timothy-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timothy/055-2-timothy-001.adoc#v55-1-0[Próximo Capítulo &#62;]