include::./index.adoc[]

[[v54-1-0]]
=== The First to Timothy, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v54-1-1]]

^<<v54-1-1,1>>^ Paul, an apostle of Christ Jesus under command of God our Savior^&#42;1^ and of Christ Jesus, our hope,

[NOTE]
====
. Or, “of God, Savior of us.” Gr., The·ouʹ So·teʹros he·monʹ; Lat., Deʹi Sal·va·toʹris noʹstri; J17,​18,​22(Heb.), ha·ʼElo·himʹ Moh·shi·ʽeʹnu.
====

[[v54-1-2]]

^<<v54-1-2,2>>^ to Timothy,^&#42;1^ a genuine child in the faith:
May there be undeserved kindness, mercy, peace from God &#91;the&#93; Father and Christ Jesus our Lord.

[NOTE]
====
. “To Timothy.” Gr., Ti·mo·theʹoi, meaning “One Who Honors God.”
====

[[v54-1-3]]

^<<v54-1-3,3>>^ Just as I encouraged you to stay in Ephʹe·sus when I was about to go my way into Mac·e·doʹni·a, so I do now, that you might command certain ones not to teach different doctrine,

[[v54-1-4]]

^<<v54-1-4,4>>^ nor to pay attention to false stories and to genealogies, which end up in nothing, but which furnish questions for research rather than a dispensing^&#42;1^ of anything by God in connection with faith.

[NOTE]
====
. Lit., “house-administration.” Gr., oi·ko·no·miʹan.
====

[[v54-1-5]]

^<<v54-1-5,5>>^ Really the objective^&#42;1^ of this mandate is love out of a clean heart and out of a good conscience and out of faith without hypocrisy.

[NOTE]
====
. Lit., “end.” Gr., teʹlos.
====

[[v54-1-6]]

^<<v54-1-6,6>>^ By deviating from these things certain ones have been turned aside into idle talk,

[[v54-1-7]]

^<<v54-1-7,7>>^ wanting to be teachers of law, but not perceiving either the things they are saying or the things about which they are making strong assertions.

[[v54-1-8]]

^<<v54-1-8,8>>^ Now we know that the Law is fine provided one handles it lawfully

[[v54-1-9]]

^<<v54-1-9,9>>^ in the knowledge of this fact, that law is promulgated, not for a righteous man, but for persons lawless and unruly, ungodly and sinners, lacking loving-kindness, and profane, murderers of fathers and murderers of mothers, manslayers,

[[v54-1-10]]

^<<v54-1-10,10>>^ fornicators, men who lie with males, kidnappers, liars, false swearers, and whatever other thing is in opposition to the healthful teaching

[[v54-1-11]]

^<<v54-1-11,11>>^ according to the glorious good news of the happy God, with which I was entrusted.

[[v54-1-12]]

^<<v54-1-12,12>>^ I am grateful to Christ Jesus our Lord, who imparted power to me, because he considered me faithful by assigning me to a ministry,

[[v54-1-13]]

^<<v54-1-13,13>>^ although formerly I was a blasphemer and a persecutor and an insolent man. Nevertheless, I was shown mercy, because I was ignorant and acted with a lack of faith.

[[v54-1-14]]

^<<v54-1-14,14>>^ But the undeserved kindness of our Lord abounded exceedingly along with faith and love that is in connection with Christ Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Faithful and deserving of full acceptance is the saying that Christ Jesus came into the world to save sinners. Of these I am foremost.

[[v54-1-16]]

^<<v54-1-16,16>>^ Nevertheless, the reason why I was shown mercy was that by means of me as the foremost case Christ Jesus might demonstrate all his long-suffering for a sample of those who are going to rest their faith on him for everlasting life.

[[v54-1-17]]

^<<v54-1-17,17>>^ Now to the King of eternity,^&#42;1^ incorruptible, invisible, &#91;the&#93; only God, be honor and glory forever and ever. Amen.

[NOTE]
====
. Or, “the eternal King.”
====

[[v54-1-18]]

^<<v54-1-18,18>>^ This mandate I commit to you, child, Timothy, in accord with the predictions that led directly on to you, that by these you may go on waging the fine warfare;

[[v54-1-19]]

^<<v54-1-19,19>>^ holding faith and a good conscience, which some have thrust aside and have experienced shipwreck concerning &#91;their&#93; faith.

[[v54-1-20]]

^<<v54-1-20,20>>^ Hy·me·naeʹus and Alexander belong to these, and I have handed them over to Satan that they may be taught by discipline^&#42;1^ not to blaspheme.^&#42;2^

[NOTE]
====
. “Be taught by discipline.” Or, “be chastised; be instructed.”
. Or, “speak abusively.”
====

'''

xref:053-2-thessalonians/053-2-thessalonians-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timothy/054-1-timothy-002.adoc#v54-2-0[Próximo Capítulo &#62;]