include::./index.adoc[]

[[v54-4-0]]
=== The First to Timothy, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v54-4-1]]

^<<v54-4-1,1>>^ However, the inspired utterance^&#42;1^ says definitely that in later periods of time some will fall away from the faith, paying attention to misleading inspired utterances^&#42;2^ and teachings of demons,

[NOTE]
====
. Or, “the spirit.”
. Or, “misleading spirits.”
====

[[v54-4-2]]

^<<v54-4-2,2>>^ by the hypocrisy of men who speak lies, marked in their conscience as with a branding iron;

[[v54-4-3]]

^<<v54-4-3,3>>^ forbidding to marry, commanding to abstain from foods which God created to be partaken of with thanksgiving by those who have faith and accurately know the truth.

[[v54-4-4]]

^<<v54-4-4,4>>^ The reason for this is that every creation of God is fine, and nothing is to be rejected if it is received with thanksgiving,

[[v54-4-5]]

^<<v54-4-5,5>>^ for it is sanctified^&#42;1^ through God’s word and prayer over &#91;it&#93;.

[NOTE]
====
. Or, “it is held sacred; it is treated as holy.” Gr., ha·gi·aʹze·tai; Lat., sanc·ti·fi·caʹtur; J22(Heb.), mequd·dashʹ.
====

[[v54-4-6]]

^<<v54-4-6,6>>^ By giving these advices to the brothers you will be a fine minister of Christ Jesus, one nourished with the words of the faith and of the fine teaching which you have followed closely.

[[v54-4-7]]

^<<v54-4-7,7>>^ But turn down the false stories which violate what is holy and which old women tell. On the other hand, be training yourself with godly devotion^&#42;1^ as your aim.

[NOTE]
====
. “Godly devotion,” אAVg; J7,​8, “fear of Jehovah.”
====

[[v54-4-8]]

^<<v54-4-8,8>>^ For bodily training^&#42;1^ is beneficial for a little; but godly devotion^&#42;2^ is beneficial for all things, as it holds promise of the life now and that which is to come.

[NOTE]
====
. Lit., “training (as gymnast).” Gr., gy·mna·siʹa; Lat., ex·er·ci·taʹti·o, “exercise.”
. “Godly devotion,” אAVg; J7,​8, “fear of Jehovah.”
====

[[v54-4-9]]

^<<v54-4-9,9>>^ Faithful and deserving of full acceptance is that statement.

[[v54-4-10]]

^<<v54-4-10,10>>^ For to this end we are working hard and exerting ourselves, because we have rested our hope on a living God, who is a Savior of all sorts of men, especially of faithful ones.

[[v54-4-11]]

^<<v54-4-11,11>>^ Keep on giving these commands and teaching them.

[[v54-4-12]]

^<<v54-4-12,12>>^ Let no man ever look down on your youth. On the contrary, become an example to the faithful ones in speaking, in conduct, in love, in faith, in chasteness.

[[v54-4-13]]

^<<v54-4-13,13>>^ While I am coming, continue applying yourself to public reading, to exhortation, to teaching.

[[v54-4-14]]

^<<v54-4-14,14>>^ Do not be neglecting the gift in you that was given you through a prediction and when the body of older men^&#42;1^ laid their hands upon you.

[NOTE]
====
. Or, “body of elders.” Gr., pre·sby·te·riʹou; J17,​18(Heb.), haz·zeqe·nimʹ, “the elders.” See Nu 11:25.
====

[[v54-4-15]]

^<<v54-4-15,15>>^ Ponder over these things; be absorbed in them, that your advancement may be manifest to all &#91;persons&#93;.

[[v54-4-16]]

^<<v54-4-16,16>>^ Pay constant attention to yourself and to your teaching. Stay by these things, for by doing this you will save both yourself and those who listen to you.

'''

xref:054-1-timothy/054-1-timothy-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timothy/054-1-timothy-005.adoc#v54-5-0[Próximo Capítulo &#62;]