include::./index.adoc[]

[[v54-5-0]]
=== The First to Timothy, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v54-5-1]]

^<<v54-5-1,1>>^ Do not severely criticize an older man.^&#42;1^ To the contrary, entreat him as a father, younger men as brothers,

[NOTE]
====
. Or, “elder.” Gr., pre·sby·teʹroi, dative, sing.
====

[[v54-5-2]]

^<<v54-5-2,2>>^ older women as mothers, younger women as sisters with all chasteness.

[[v54-5-3]]

^<<v54-5-3,3>>^ Honor widows that are actually widows.

[[v54-5-4]]

^<<v54-5-4,4>>^ But if any widow has children or grandchildren, let these learn first to practice godly devotion^&#42;1^ in their own household and to keep paying a due compensation to their parents and grandparents, for this is acceptable in God’s sight.

[NOTE]
====
. “Godly devotion,” אA; J7,​8, “wisdom and fear of Jehovah.”
====

[[v54-5-5]]

^<<v54-5-5,5>>^ Now the woman who is actually a widow and left destitute has put her hope in God and persists in supplications and prayers night and day.

[[v54-5-6]]

^<<v54-5-6,6>>^ But the one that goes in for sensual gratification is dead though she is living.

[[v54-5-7]]

^<<v54-5-7,7>>^ So keep on giving these commands, that they may be irreprehensible.

[[v54-5-8]]

^<<v54-5-8,8>>^ Certainly if anyone does not provide for those who are his own, and especially for those who are members of his household, he has disowned the faith and is worse than a person without faith.^&#42;1^

[NOTE]
====
. “A person without faith,” אAVgSyp; J13,​14,​18, “a person who has disowned Jehovah.”
====

[[v54-5-9]]

^<<v54-5-9,9>>^ Let a widow be put on the list who has become not less than sixty years old, a wife of one husband,

[[v54-5-10]]

^<<v54-5-10,10>>^ having a witness borne to her for fine works, if she reared children, if she entertained strangers, if she washed the feet of holy ones, if she relieved those in tribulation, if she diligently followed every good work.

[[v54-5-11]]

^<<v54-5-11,11>>^ On the other hand, turn down younger widows, for when their sexual impulses have come between them and the Christ, they want to marry,

[[v54-5-12]]

^<<v54-5-12,12>>^ having a judgment because they have disregarded their first &#91;expression of&#93; faith.

[[v54-5-13]]

^<<v54-5-13,13>>^ At the same time they also learn to be unoccupied, gadding about to the houses; yes, not only unoccupied, but also gossipers and meddlers in other people’s affairs, talking of things they ought not.

[[v54-5-14]]

^<<v54-5-14,14>>^ Therefore I desire the younger widows to marry, to bear children, to manage a household, to give no inducement to the opposer to revile.

[[v54-5-15]]

^<<v54-5-15,15>>^ Already, in fact, some have been turned aside to follow Satan.

[[v54-5-16]]

^<<v54-5-16,16>>^ If any believing woman has widows,^&#42;1^ let her relieve them, and let the congregation not be under the burden. Then it can relieve those who are actually widows.

[NOTE]
====
. “Widows,” that is, bereaved relatives.
====

[[v54-5-17]]

^<<v54-5-17,17>>^ Let the older men^&#42;1^ who preside in a fine way be reckoned worthy of double honor, especially those who work hard in speaking and teaching.

[NOTE]
====
. Or, “elders.”
====

[[v54-5-18]]

^<<v54-5-18,18>>^ For the scripture says: “You must not muzzle a bull when it threshes out the grain”; also: “The workman is worthy of his wages.”

[[v54-5-19]]

^<<v54-5-19,19>>^ Do not admit an accusation against an older man,^&#42;1^ except only on the evidence of two or three witnesses.

[NOTE]
====
. Or, “elder.” Gr., pre·sby·teʹrou.
====

[[v54-5-20]]

^<<v54-5-20,20>>^ Reprove before all onlookers persons who practice sin, that the rest also may have fear.

[[v54-5-21]]

^<<v54-5-21,21>>^ I solemnly charge you before God and Christ Jesus^&#42;1^ and the chosen angels to keep these things without prejudgment, doing nothing according to a biased leaning.

[NOTE]
====
. See App 6E.
====

[[v54-5-22]]

^<<v54-5-22,22>>^ Never lay your hands hastily upon any man; neither be a sharer in the sins of others; preserve yourself chaste.

[[v54-5-23]]

^<<v54-5-23,23>>^ Do not drink water any longer, but use a little wine for the sake of your stomach and your frequent cases of sickness.

[[v54-5-24]]

^<<v54-5-24,24>>^ The sins of some men are publicly manifest, leading directly to judgment, but as for other men &#91;their sins&#93; also become manifest later.

[[v54-5-25]]

^<<v54-5-25,25>>^ In the same way also the fine works are publicly manifest and those that are otherwise cannot be kept hid.

'''

xref:054-1-timothy/054-1-timothy-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timothy/054-1-timothy-006.adoc#v54-6-0[Próximo Capítulo &#62;]