include::./index.adoc[]

[[v32-3-0]]
=== Jonah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v32-3-1]]

^<<v32-3-1,1>>^ Then the word of Jehovah occurred to Joʹnah the second time, saying:

[[v32-3-2]]

^<<v32-3-2,2>>^ “Get up, go to Ninʹe·veh the great city, and proclaim to her the proclamation that I am speaking to you.”

[[v32-3-3]]

^<<v32-3-3,3>>^ At that, Joʹnah got up and went to Ninʹe·veh in accord with the word of Jehovah.^&#42;1^ Now Ninʹe·veh herself proved to be a city great to God,^&#42;2^ with a walking distance of three days.

[NOTE]
====
. See App 1C §3.
. Or, “extremely great; divinely great.” Heb., gedhoh·lahʹ lEʼ·lo·himʹ; Gr., me·gaʹle toi The·oiʹ. Compare the expression “divinely beautiful” in Ac 7:20, where see ftn.
====

[[v32-3-4]]

^<<v32-3-4,4>>^ Finally Joʹnah started to enter into the city the walking distance of one day, and he kept proclaiming and saying: “Only forty days more, and Ninʹe·veh will be overthrown.”

[[v32-3-5]]

^<<v32-3-5,5>>^ And the men^&#42;1^ of Ninʹe·veh began to put faith in God, and they proceeded to proclaim a fast and to put on sackcloth, from the greatest one of them even to the least one of them.

[NOTE]
====
. See 1:10 ftn.
====

[[v32-3-6]]

^<<v32-3-6,6>>^ When the word reached the king of Ninʹe·veh, then he rose up from his throne and put off his official garment from himself and covered himself with sackcloth and sat down in the ashes.

[[v32-3-7]]

^<<v32-3-7,7>>^ Furthermore, he had the cry made, and he had it said in Ninʹe·veh, by the decree of the king and his great ones, saying:
“No man and no domestic animal, no herd and no flock, should taste anything at all. None should take food. Even water they should not drink.

[[v32-3-8]]

^<<v32-3-8,8>>^ And let them cover themselves with sackcloth, man and domestic animal; and let them call out to God with strength and come back, each one from his bad way and from the violence that was in their hands.

[[v32-3-9]]

^<<v32-3-9,9>>^ Who is there knowing whether the &#91;true&#93; God may turn back and actually feel regret and turn back from his burning anger, so that we may not perish?”

[[v32-3-10]]

^<<v32-3-10,10>>^ And the &#91;true&#93; God got to see their works, that they had turned back from their bad way; and so the &#91;true&#93; God felt regret over the calamity that he had spoken of causing to them; and he did not cause &#91;it&#93;.

'''

xref:032-jonah/032-jonah-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonah/032-jonah-004.adoc#v32-4-0[Próximo Capítulo &#62;]