include::./index.adoc[]

[[v32-4-0]]
=== Jonah, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v32-4-1]]

^<<v32-4-1,1>>^ To Joʹnah, though, it was highly displeasing, and he got to be hot with anger.

[[v32-4-2]]

^<<v32-4-2,2>>^ Hence he prayed to Jehovah^&#42;1^ and said: “Ah, now, O Jehovah, was not this an affair of mine,^&#42;2^ while I happened to be on my own ground? That is why I went ahead and ran away to Tarʹshish; for I knew that you are a God^&#42;3^ gracious and merciful, slow to anger and abundant in loving-kindness,^&#42;4^ and feeling regret over the calamity.

[NOTE]
====
. See App 1C §2.
. “An affair of mine.” Or, “my word.”
. “A God.” Heb., ʼEl; Lat., Deʹus.
. Or, “loyal love.” Heb., cheʹsedh.
====

[[v32-4-3]]

^<<v32-4-3,3>>^ And now, O Jehovah, take away, please, my soul^&#42;1^ from me, for my dying is better than my being alive.”^&#42;2^

[NOTE]
====
. See 2:7 ftn.
. Or, “my life.”
====

[[v32-4-4]]

^<<v32-4-4,4>>^ In turn Jehovah said: “Have you rightly become hot with anger?”

[[v32-4-5]]

^<<v32-4-5,5>>^ Then Joʹnah went out of the city and sat down east of the city; and gradually he made for himself there a booth, that he might sit under it in the shade until he would see what would become of the city.

[[v32-4-6]]

^<<v32-4-6,6>>^ Accordingly Jehovah God^&#42;1^ appointed a bottle-gourd plant,^&#42;2^ that it should come up over Joʹnah, in order to become a shade over his head, to deliver him from his calamitous state. And Joʹnah began to rejoice greatly over the bottle-gourd plant.

[NOTE]
====
. “Jehovah God,” MTLXXSyVg. See Ge 2:4 ftn, “God.”
. Or, “castor-oil plant.” Heb., qi·qa·yohnʹ.
====

[[v32-4-7]]

^<<v32-4-7,7>>^ But the &#91;true&#93; God appointed a worm at the ascending of the dawn on the next day, that it should strike the bottle-gourd plant; and it gradually dried up.

[[v32-4-8]]

^<<v32-4-8,8>>^ And it came about that, as soon as the sun shone forth, God^&#42;1^ also went on to appoint a parching east wind, and the sun kept striking upon the head of Joʹnah, so that he was swooning away; and he kept asking that his soul^&#42;2^ might die, and he repeatedly said: “My dying off is better than my being alive.”^&#42;3^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Gr., ho The·osʹ; TVg, “Jehovah”; Sy, “Jehovah God.”
. “His soul.” Heb., naph·shohʹ; Gr., psy·khenʹ; Lat., aʹni·mae. See App 4A.
. Or, “than my life.” Heb., me·chai·yaiʹ.
====

[[v32-4-9]]

^<<v32-4-9,9>>^ And God proceeded to say to Joʹnah: “Have you rightly become hot with anger over the bottle-gourd plant?”
At that he said: “I have rightly become hot with anger, to the point of death.”

[[v32-4-10]]

^<<v32-4-10,10>>^ But Jehovah said: “You, for your part, felt sorry for the bottle-gourd plant, which you did not toil upon or make get big, which proved to be a mere growth of a night^&#42;1^ and perished as a mere growth of a night.

[NOTE]
====
. Or, “just a night old.” Lit., “a son of a night.”
====

[[v32-4-11]]

^<<v32-4-11,11>>^ And, for my part, ought I not to feel sorry for Ninʹe·veh the great city, in which there exist more than one hundred and twenty thousand^&#42;1^ men^&#42;2^ who do not at all know the difference between their right hand and their left, besides many domestic animals?”

[NOTE]
====
. Lit., “twelve ten-thousands.”
. Or, “earthling men.” Heb., ʼa·dhamʹ.
====

'''

xref:032-jonah/032-jonah-003.adoc#v32-3-0[&#60; Capítulo Anterior] | <<v32-4-0,Topo>> | xref:033-micah/033-micah-001.adoc#v33-1-0[Próximo Capítulo &#62;]