include::./index.adoc[]

[[v3-20-0]]
=== Leviticus, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-20-1]]

^<<v3-20-1,1>>^ And Jehovah went on speaking to Moses, saying:

[[v3-20-2]]

^<<v3-20-2,2>>^ “You are to say to the sons of Israel, ‘Any man of the sons of Israel, and any alien resident who resides as an alien in Israel, who gives any of his offspring to Moʹlech,^&#42;1^ should be put to death without fail. The people of the land should pelt him to death with stones.

[NOTE]
====
. “Molech,” M; Vg, “the idol Moloch”; LXX, “the ruler.”
====

[[v3-20-3]]

^<<v3-20-3,3>>^ And as for me, I shall set my face against that man, and I will cut him off from among his people, because he has given some of his offspring to Moʹlech for the purpose of defiling my holy place and to profane my holy name.^&#42;1^

[NOTE]
====
. Lit., “the name of my holiness.”
====

[[v3-20-4]]

^<<v3-20-4,4>>^ And if the people of the land should deliberately hide their eyes from that man when he gives any of his offspring to Moʹlech by not putting him to death,

[[v3-20-5]]

^<<v3-20-5,5>>^ then I, for my part, shall certainly fix my face against that man and his family, and I shall indeed cut him and all those who have immoral intercourse along with him in having immoral intercourse^&#42;1^ with Moʹlech off from among their people.

[NOTE]
====
. Or, “in committing fornication.”
====

[[v3-20-6]]

^<<v3-20-6,6>>^ “‘As for the soul who turns himself to the spirit mediums and the professional foretellers of events so as to have immoral intercourse with them, I shall certainly set my face against that soul and cut him off from among his people.

[[v3-20-7]]

^<<v3-20-7,7>>^ “‘And YOU must sanctify yourselves and prove yourselves holy, because I am Jehovah YOUR God.

[[v3-20-8]]

^<<v3-20-8,8>>^ And YOU must keep my statutes and do them. I am Jehovah who is sanctifying YOU.^&#42;1^

[NOTE]
====
. Or, “who is holding you sacred (treating you as holy).” Heb., meqad·dish·khemʹ; Gr., ho ha·gi·aʹzon hy·masʹ; Lat., qui sanc·tiʹfi·co vos.
====

[[v3-20-9]]

^<<v3-20-9,9>>^ “‘In case there should be any man who calls down evil upon his father and his mother, he should be put to death without fail. It is his father and his mother upon whom he has called down evil. His own blood^&#42;1^ is upon him.

[NOTE]
====
. That is, responsibility for his blood.
====

[[v3-20-10]]

^<<v3-20-10,10>>^ “‘Now a man who commits adultery with another man’s wife is one who commits adultery^&#42;1^ with the wife of his fellowman. He^&#42;2^ should be put to death without fail, the adulterer and the adulteress as well.

[NOTE]
====
. “Adultery.” Lat., a·dul·teʹri·um.
. “He,” MSam; LXXSyVg, “They.”
====

[[v3-20-11]]

^<<v3-20-11,11>>^ And a man who lies down with his father’s wife has laid bare the nakedness of his father. Both of them should be put to death without fail. Their own blood is upon them.

[[v3-20-12]]

^<<v3-20-12,12>>^ And where a man lies down with his daughter-in-law, both of them should be put to death without fail. They have committed a violation of what is natural. Their own blood is upon them.

[[v3-20-13]]

^<<v3-20-13,13>>^ “‘And when a man lies down with a male the same as one lies down with a woman, both of them have done a detestable thing. They should be put to death without fail. Their own blood is upon them.

[[v3-20-14]]

^<<v3-20-14,14>>^ “‘And where a man takes a woman and her mother, it is loose conduct. They should burn him and them in the fire, in order that loose conduct may not continue in YOUR midst.

[[v3-20-15]]

^<<v3-20-15,15>>^ “‘And where a man gives his seminal emission to a beast, he should be put to death without fail, and YOU should kill the beast.

[[v3-20-16]]

^<<v3-20-16,16>>^ And where a woman approaches any beast to have a connection with it,^&#42;1^ you must kill the woman and the beast. They should be put to death without fail. Their own blood is upon them.

[NOTE]
====
. Or, “her.”
====

[[v3-20-17]]

^<<v3-20-17,17>>^ “‘And where a man takes his sister, the daughter of his father or the daughter of his mother, and he does see her nakedness, and she herself sees his nakedness, it is shame. So they must be cut off before the eyes of the sons of their people. It is the nakedness of his sister that he has laid bare. He should answer for his error.

[[v3-20-18]]

^<<v3-20-18,18>>^ “‘And where a man lies down with a menstruating woman and does lay bare her nakedness, he has exposed her source, and she herself has laid bare the source of her blood. So both of them must be cut off from among their people.

[[v3-20-19]]

^<<v3-20-19,19>>^ “‘And the nakedness of your mother’s sister and of your father’s sister you must not lay bare, because it is his blood relation that one has exposed. They should answer for their error.

[[v3-20-20]]

^<<v3-20-20,20>>^ And a man who lies down with his uncle’s wife has laid bare the nakedness of his uncle. They should answer for their sin. They should die childless.

[[v3-20-21]]

^<<v3-20-21,21>>^ And where a man takes his brother’s wife, it is something abhorrent. It is the nakedness of his brother that he has laid bare. They should become^&#42;1^ childless.

[NOTE]
====
. “Become,” M; LXX, “die.”
====

[[v3-20-22]]

^<<v3-20-22,22>>^ “‘And YOU people must keep all my statutes and all my judicial decisions and do them, that the land to which I am bringing YOU to dwell in it may not vomit YOU out.

[[v3-20-23]]

^<<v3-20-23,23>>^ And YOU must not walk in the statutes of the nations whom I am sending out from before YOU, because they have done all these things and I abhor them.

[[v3-20-24]]

^<<v3-20-24,24>>^ Hence I said to YOU: “YOU, for YOUR part, will take possession of their ground, and I, for my part, shall give it to YOU to take possession of it, a land flowing with milk and honey. Jehovah YOUR God I am, who have divided YOU off from the peoples.”

[[v3-20-25]]

^<<v3-20-25,25>>^ And YOU must make a distinction between the clean beast and the unclean and between the unclean fowl and the clean; and YOU must not make YOUR souls loathsome with the beast and the fowl and anything that moves on the ground that I have divided off for YOU in declaring them unclean.

[[v3-20-26]]

^<<v3-20-26,26>>^ And YOU must prove yourselves holy to me, because I Jehovah am holy; and I am proceeding to divide YOU off from the peoples to become mine.

[[v3-20-27]]

^<<v3-20-27,27>>^ “‘And as for a man or woman in whom there proves to be a mediumistic spirit or spirit of prediction, they should be put to death without fail. They should pelt them to death with stones. Their own blood is upon them.’”

'''

xref:003-leviticus/003-leviticus-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-leviticus/003-leviticus-021.adoc#v3-21-0[Próximo Capítulo &#62;]