include::./index.adoc[]

[[v3-6-0]]
=== Leviticus, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-6-1]]

^<<v3-6-1,1>>^ ^&#42;1^ And Jehovah went on to speak to Moses, saying:

[NOTE]
====
. SyVg begin chapter 6 here; MLXX continue for seven more vss.
====

[[v3-6-2]]

^<<v3-6-2,2>>^ “In case a soul sins in that he does behave unfaithfully toward Jehovah and does deceive his associate about something in his charge or a deposit in hand or a robbery or he does defraud his associate,

[[v3-6-3]]

^<<v3-6-3,3>>^ or he does find something lost and is actually deceptive about it and does swear falsely over any of all the things that the man might do to sin by them;

[[v3-6-4]]

^<<v3-6-4,4>>^ then it must occur that in case he sins and indeed becomes guilty, he must return the robbed thing which he has robbed or the extorted thing which he has taken by fraud or the thing in his charge which was put in his charge or the thing lost that he has found,

[[v3-6-5]]

^<<v3-6-5,5>>^ or anything at all over which he might swear falsely, and he must make compensation for it in its full amount, and he will add to it a fifth of it. To the one whose it is he will give it on the day his guilt is proved.

[[v3-6-6]]

^<<v3-6-6,6>>^ And as his guilt offering he will bring to Jehovah a sound ram from the flock according to the estimated value, for a guilt offering, to the priest.

[[v3-6-7]]

^<<v3-6-7,7>>^ And the priest must make an atonement for him before Jehovah, and so it must be forgiven him regarding any of all the things that he might do resulting in guiltiness by it.”

[[v3-6-8]]

^<<v3-6-8,8>>^ And Jehovah continued to speak to Moses, saying:

[[v3-6-9]]

^<<v3-6-9,9>>^ “Command Aaron and his sons, saying, ‘This is the law of the burnt offering: The burnt offering will be on the hearth upon the altar all night long until the morning, and the fire of the altar will be kindled in it.

[[v3-6-10]]

^<<v3-6-10,10>>^ And the priest must clothe himself with his official dress of linen, and he will put the linen drawers on over his flesh. Then he must lift up the fatty ashes of the burnt offering that the fire regularly consumes upon the altar, and he must place them beside the altar.

[[v3-6-11]]

^<<v3-6-11,11>>^ And he must strip off his garments and put on other garments, and he must take the fatty ashes out to a clean place outside the camp.

[[v3-6-12]]

^<<v3-6-12,12>>^ And the fire on the altar will be kept burning on it. It must not go out. And the priest must burn wood on it morning by morning and set the burnt offering in order over it, and he must make the fatty pieces of the communion sacrifices smoke over it.

[[v3-6-13]]

^<<v3-6-13,13>>^ Fire will be kept constantly burning on the altar. It must not go out.

[[v3-6-14]]

^<<v3-6-14,14>>^ “‘Now this is the law of the grain offering: YOU sons of Aaron, present it before Jehovah in front of the altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ And one of them must lift up by his handful some of the fine flour of the grain offering and some of its oil and all the frankincense that is upon the grain offering, and he must make it smoke upon the altar as a restful odor for a remembrancer of it to Jehovah.

[[v3-6-16]]

^<<v3-6-16,16>>^ And what is left of it Aaron and his sons will eat. It will be eaten as unfermented cakes in a holy place. They will eat it in the courtyard of the tent of meeting.

[[v3-6-17]]

^<<v3-6-17,17>>^ It should not be baked with anything leavened. I have given it as their share out of my offerings made by fire. It is something most holy, like the sin offering and like the guilt offering.

[[v3-6-18]]

^<<v3-6-18,18>>^ Every male among the sons of Aaron will eat it. It is an allowance to time indefinite throughout YOUR generations from Jehovah’s offerings made by fire. Everything that may touch them will become holy.’”

[[v3-6-19]]

^<<v3-6-19,19>>^ And Jehovah went on speaking to Moses, saying:

[[v3-6-20]]

^<<v3-6-20,20>>^ “This is the offering of Aaron and his sons that they will present to Jehovah on the day of his being anointed: the tenth of an eʹphah of fine flour as a grain offering constantly, half of it in the morning and half of it in the evening.

[[v3-6-21]]

^<<v3-6-21,21>>^ It will be made with oil upon a griddle. You will bring it well mixed. You will present the pastries of the grain offering in pieces as a restful odor to Jehovah.

[[v3-6-22]]

^<<v3-6-22,22>>^ And the priest, the one anointed^&#42;1^ in place of him from among his sons, will make it. It is a regulation to time indefinite: As a whole offering it will be made to smoke to Jehovah.

[NOTE]
====
. “The one anointed.” Heb., ham·ma·shiʹach; Gr., ho khri·stosʹ.
====

[[v3-6-23]]

^<<v3-6-23,23>>^ And every grain offering of a priest should prove to be a whole offering. It must not be eaten.”

[[v3-6-24]]

^<<v3-6-24,24>>^ And Jehovah spoke further to Moses, saying:

[[v3-6-25]]

^<<v3-6-25,25>>^ “Speak to Aaron and his sons, saying, ‘This is the law of the sin offering: In the place where the burnt offering is regularly slaughtered the sin offering will be slaughtered before Jehovah. It is a most holy thing.

[[v3-6-26]]

^<<v3-6-26,26>>^ The priest who offers it for sin will eat it. In a holy place it will be eaten in the courtyard of the tent of meeting.

[[v3-6-27]]

^<<v3-6-27,27>>^ “‘Everything that may touch its flesh will become holy, and when anyone spatters some of its blood upon the garment, you will wash what he spatters blood upon in a holy place.

[[v3-6-28]]

^<<v3-6-28,28>>^ And the earthenware vessel in which it may be boiled is to be shattered. But if it was boiled in a copper vessel, then it must be scoured and rinsed with water.

[[v3-6-29]]

^<<v3-6-29,29>>^ “‘Every male among the priests will eat it. It is something most holy.

[[v3-6-30]]

^<<v3-6-30,30>>^ However, no sin offering of which some of the blood will be brought into the tent of meeting to make atonement in the holy place must be eaten. It is to be burned with fire.

'''

xref:003-leviticus/003-leviticus-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-leviticus/003-leviticus-007.adoc#v3-7-0[Próximo Capítulo &#62;]