include::./index.adoc[]

[[v3-15-0]]
=== Leviticus, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-15-1]]

^<<v3-15-1,1>>^ And Jehovah continued to speak to Moses and Aaron, saying:

[[v3-15-2]]

^<<v3-15-2,2>>^ “Speak to the sons of Israel, and YOU must say to them, ‘In case any man^&#42;1^ has a running discharge occur from his genital organ,^&#42;2^ his discharge is unclean.

[NOTE]
====
. Lit., “man, man,” MLXX.
. Lit., “his flesh.”
====

[[v3-15-3]]

^<<v3-15-3,3>>^ And this will become his uncleanness by his discharge: Whether his genital organ has flowed with a running discharge or his genital organ is obstructed from his running discharge, it is his uncleanness.

[[v3-15-4]]

^<<v3-15-4,4>>^ “‘Any bed upon which the one having a running discharge may lie down will be unclean, and any article upon which he may sit will be unclean.

[[v3-15-5]]

^<<v3-15-5,5>>^ And a man who may touch his bed should wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-6]]

^<<v3-15-6,6>>^ And whoever sits upon the article upon which the one having a running discharge was sitting should wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-7]]

^<<v3-15-7,7>>^ And whoever touches the flesh of the one having a running discharge should wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-8]]

^<<v3-15-8,8>>^ And in the case of the one who has a running discharge spitting upon someone clean, he must in that case wash his garments and bathe in water and be unclean until the evening.

[[v3-15-9]]

^<<v3-15-9,9>>^ And any saddle upon which the one having a running discharge was riding will be unclean.

[[v3-15-10]]

^<<v3-15-10,10>>^ And anyone touching anything that happens to be under him will be unclean until the evening; and he who carries them will wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-11]]

^<<v3-15-11,11>>^ And anyone whom the one having a running discharge might touch when he has not rinsed his hands in water must then wash his garments and bathe in water and be unclean until the evening.

[[v3-15-12]]

^<<v3-15-12,12>>^ And an earthenware vessel that the one having a running discharge might touch should be smashed; and any wooden vessel should be rinsed with water.

[[v3-15-13]]

^<<v3-15-13,13>>^ “‘Now in case the one having a running discharge would become clean from his running discharge, he must then count for himself seven days for his purification, and he must wash his garments and bathe his flesh in running water; and he must be clean.

[[v3-15-14]]

^<<v3-15-14,14>>^ And on the eighth day he should take for himself two turtledoves or two young pigeons,^&#42;1^ and he must come before Jehovah to the entrance of the tent of meeting and give them to the priest.

[NOTE]
====
. Lit., “sons of a pigeon.”
====

[[v3-15-15]]

^<<v3-15-15,15>>^ And the priest must offer them, the one as a sin offering and the other as a burnt offering; and the priest must make atonement for him before Jehovah concerning his running discharge.

[[v3-15-16]]

^<<v3-15-16,16>>^ “‘Now in case a man has an emission of semen go out from him, he must then bathe all his flesh in water and be unclean until the evening.

[[v3-15-17]]

^<<v3-15-17,17>>^ And any garment and any skin upon which the emission of semen gets to be must be washed with water and be unclean until the evening.

[[v3-15-18]]

^<<v3-15-18,18>>^ “‘As for a woman with whom a man may lie down with an emission of semen, they must bathe in water and be unclean until the evening.

[[v3-15-19]]

^<<v3-15-19,19>>^ “‘And in case a woman is having a running discharge, and her running discharge in her flesh proves to be blood, she should continue seven days in her menstrual impurity, and anyone touching her will be unclean until the evening.

[[v3-15-20]]

^<<v3-15-20,20>>^ And anything upon which she may lie down in her menstrual impurity will be unclean, and everything upon which she may sit will be unclean.

[[v3-15-21]]

^<<v3-15-21,21>>^ And anyone touching her bed should wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-22]]

^<<v3-15-22,22>>^ And anyone touching any article upon which she was sitting should wash his garments, and he must bathe in water and be unclean until the evening.

[[v3-15-23]]

^<<v3-15-23,23>>^ And if it was upon the bed or upon another article that she was sitting, by his touching it he will be unclean until the evening.

[[v3-15-24]]

^<<v3-15-24,24>>^ And if a man lies down with her at all and her menstrual impurity comes to be upon him, he must then be unclean seven days, and any bed upon which he might lie down will be unclean.

[[v3-15-25]]

^<<v3-15-25,25>>^ “‘As for a woman, in case the running discharge of her blood should be flowing many days when it is not the regular time of her menstrual impurity, or in case she should have a flow longer than her menstrual impurity, all the days of her unclean running discharge will prove as in the days of her menstrual impurity. She is unclean.

[[v3-15-26]]

^<<v3-15-26,26>>^ Any bed upon which she may lie any of the days of her running discharge will become for her as the bed of her menstrual impurity, and any article upon which she may sit will become unclean like the uncleanness of her menstrual impurity.

[[v3-15-27]]

^<<v3-15-27,27>>^ And anyone touching them will be unclean, and he must wash his garments and bathe in water and be unclean until the evening.

[[v3-15-28]]

^<<v3-15-28,28>>^ “‘However, if she has become clean from her running discharge, she must also count for herself seven days, and afterward she will be clean.

[[v3-15-29]]

^<<v3-15-29,29>>^ And on the eighth day she should take for herself two turtledoves or two young pigeons, and she must bring them to the priest at the entrance of the tent of meeting.

[[v3-15-30]]

^<<v3-15-30,30>>^ And the priest must make the one a sin offering and the other a burnt offering; and the priest must make atonement for her before Jehovah concerning her unclean running discharge.

[[v3-15-31]]

^<<v3-15-31,31>>^ “‘And YOU must keep the sons of Israel separate from their uncleanness, that they may not die in their uncleanness for their defiling of my tabernacle, which is in their midst.

[[v3-15-32]]

^<<v3-15-32,32>>^ “‘This is the law about the man having a running discharge and the man from whom an emission of semen may go out so that he becomes unclean by it;

[[v3-15-33]]

^<<v3-15-33,33>>^ and the menstruating woman in her uncleanness, and anyone who has a flow of his running discharge, whether a male or a female, and whether a man who lies down with an unclean woman.’”

'''

xref:003-leviticus/003-leviticus-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-leviticus/003-leviticus-016.adoc#v3-16-0[Próximo Capítulo &#62;]