include::./index.adoc[]

[[v3-16-0]]
=== Leviticus, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-16-1]]

^<<v3-16-1,1>>^ And Jehovah proceeded to speak to Moses after the death of Aaron’s two sons for their approaching^&#42;1^ before Jehovah so that they died.

[NOTE]
====
. “For their approaching,” MSam; LXXSyVg, “for their presenting strange (illegitimate) fire.” See 10:1; Nu 3:4.
====

[[v3-16-2]]

^<<v3-16-2,2>>^ And Jehovah proceeded to say to Moses: “Speak to Aaron your brother, that he should not at all times come into the holy place^&#42;1^ inside the curtain, in front of the cover^&#42;2^ which is upon the Ark, that he may not die; because in a cloud I shall appear over the cover.

[NOTE]
====
. “The holy place.” Heb., haq·qoʹdhesh.
. “The cover (mercy seat; propitiatory).” Heb., hak·kap·poʹreth; Gr., hi·la·ste·riʹou; Lat., pro·pi·ti·a·toʹri·o. See Heb 9:5 ftn.
====

[[v3-16-3]]

^<<v3-16-3,3>>^ “With the following Aaron should come into the holy place: with a young bull for a sin offering and a ram for a burnt offering.

[[v3-16-4]]

^<<v3-16-4,4>>^ He should put on the holy linen robe, and the linen drawers should come upon his flesh, and he should gird himself with the linen sash and wrap himself with the linen turban. They are holy garments. And he must bathe his flesh in water and put them on.

[[v3-16-5]]

^<<v3-16-5,5>>^ “And from the assembly of the sons of Israel he should take two male kids of the goats for a sin offering and one ram for a burnt offering.

[[v3-16-6]]

^<<v3-16-6,6>>^ “And Aaron must present the bull of the sin offering, which is for himself, and he must make atonement^&#42;1^ in behalf of himself and his house.

[NOTE]
====
. “And he must make atonement.” Heb., wekhip·perʹ.
====

[[v3-16-7]]

^<<v3-16-7,7>>^ “And he must take the two goats^&#42;1^ and make them stand before Jehovah at the entrance of the tent of meeting.

[NOTE]
====
. Or, “two male kids,” as in vs 5.
====

[[v3-16-8]]

^<<v3-16-8,8>>^ And Aaron must draw lots over the two goats, the one lot for Jehovah and the other lot for A·zaʹzel.^&#42;1^

[NOTE]
====
. “For Azazel,” M(Heb., la·ʽAzaʼ·zelʹ)Sam; LXX, “the one carrying away (averting) evil”; Syr., la·ʽAz·zaʼ·yel, “for the strong one against God”; Lat., caʹpro e·mis·saʹri·o, “the emissary goat; the scapegoat.”
====

[[v3-16-9]]

^<<v3-16-9,9>>^ And Aaron must present the goat over which the lot came up for Jehovah, and he must make it a sin offering.

[[v3-16-10]]

^<<v3-16-10,10>>^ But the goat over which the lot came up for A·zaʹzel should be stood alive before Jehovah to make atonement for it, so as to send it away for A·zaʹzel into the wilderness.

[[v3-16-11]]

^<<v3-16-11,11>>^ “And Aaron must present the bull of the sin offering, which is for himself,^&#42;1^ and make an atonement in behalf of himself and his house; and he must slaughter the bull of the sin offering, which is for himself.

[NOTE]
====
. LXX adds, “and for his house alone.”
====

[[v3-16-12]]

^<<v3-16-12,12>>^ “And he must take the fire holder full of burning coals of fire from off the altar before Jehovah, and the hollows of both his hands full of fine perfumed incense,^&#42;1^ and he must bring them inside the curtain.

[NOTE]
====
. “Incense.” Heb., qetoʹreth; Lat., in·cenʹsum.
====

[[v3-16-13]]

^<<v3-16-13,13>>^ He must also put the incense upon the fire before Jehovah, and the cloud of the incense must overspread the Ark cover, which is upon the Testimony,^&#42;1^ that he may not die.

[NOTE]
====
. “The Testimony.” Heb., ha·ʽe·dhuthʹ; Gr., mar·ty·riʹon; Lat., te·sti·moʹni·um.
====

[[v3-16-14]]

^<<v3-16-14,14>>^ “And he must take some of the bull’s blood and spatter it with his finger in front of the cover^&#42;1^ on the east side, and he will spatter some of the blood with his finger seven times before the cover.

[NOTE]
====
. “In front of the cover (mercy seat).” Heb., ʽal-penehʹ hak·kap·poʹreth; LXX, “upon the propitiatory”; Vg, “toward the propitiatory.” See vs 2.
====

[[v3-16-15]]

^<<v3-16-15,15>>^ “And he must slaughter the goat of the sin offering, which is for the people, and he must bring its blood inside the curtain and do with its blood the same as he did with the bull’s blood; and he must spatter it toward the cover^&#42;1^ and before the cover.

[NOTE]
====
. “Toward the cover (mercy seat).” Heb., ʽal-hak·kap·poʹreth; Gr., e·piʹ to hi·la·steʹri·on, “upon the propitiatory”; Lat., e re·gi·oʹne o·raʹcu·li, “against (opposite) the oracle.”
====

[[v3-16-16]]

^<<v3-16-16,16>>^ “And he must make atonement for the holy place concerning^&#42;1^ the uncleannesses of the sons of Israel and concerning their revolts in all their sins; and that is the way he should do for the tent of meeting, which is residing with them in the midst of their uncleannesses.

[NOTE]
====
. Or, “from.”
====

[[v3-16-17]]

^<<v3-16-17,17>>^ “And no other man^&#42;1^ should happen to be in the tent of meeting from when he goes in to make atonement in the holy place until he comes out; and he must make atonement in behalf of himself and in behalf of his house and in behalf of the entire congregation^&#42;2^ of Israel.

[NOTE]
====
. Or, “earthling.” Heb., ʼa·dhamʹ.
. “The entire congregation of.” Heb., kol-qehalʹ.
====

[[v3-16-18]]

^<<v3-16-18,18>>^ “And he must come out to the altar, which is before Jehovah, and make atonement^&#42;1^ for it, and he must take some of the bull’s blood and some of the goat’s blood and put it upon the horns of the altar round about.

[NOTE]
====
. “And make atonement.” Heb., wekhip·perʹ.
====

[[v3-16-19]]

^<<v3-16-19,19>>^ He must also spatter some of the blood upon it with his finger seven times and cleanse it and sanctify it from the uncleannesses of the sons of Israel.

[[v3-16-20]]

^<<v3-16-20,20>>^ “When he has finished making atonement for the holy place and the tent of meeting and the altar, he must also present the live goat.

[[v3-16-21]]

^<<v3-16-21,21>>^ And Aaron must lay both his hands upon the head of the live goat and confess over it all the errors of the sons of Israel and all their revolts in all their sins, and he must put them upon the head of the goat and send it away by the hand of a ready man into the wilderness.

[[v3-16-22]]

^<<v3-16-22,22>>^ And the goat must carry upon itself all their errors into a desert land, and he must send the goat away into the wilderness.

[[v3-16-23]]

^<<v3-16-23,23>>^ “And Aaron must come into the tent of meeting and strip off the linen garments that he put on when he went into the holy place, and he must lay them down there.

[[v3-16-24]]

^<<v3-16-24,24>>^ And he must bathe his flesh in water in a holy place and put on his garments and come out and render up his burnt offering and the people’s burnt offering and make atonement in his own behalf and in behalf of the people.^&#42;1^

[NOTE]
====
. “In his own behalf and that of his house and that of the people as well as that of the priests,” LXX.
====

[[v3-16-25]]

^<<v3-16-25,25>>^ And he will make the fat of the sin offering smoke upon the altar.

[[v3-16-26]]

^<<v3-16-26,26>>^ “As for the one who sent the goat away for A·zaʹzel, he should wash his garments, and he must bathe his flesh in water, and after that he may come into the camp.

[[v3-16-27]]

^<<v3-16-27,27>>^ “However, he will have the bull of the sin offering and the goat of the sin offering, the blood of both of which was brought in to make atonement in the holy place, taken forth outside the camp; and they must burn their skins and their flesh and their dung in the fire.

[[v3-16-28]]

^<<v3-16-28,28>>^ And the one who burned them should wash his garments, and he must bathe his flesh in water, and after that he may come into the camp.

[[v3-16-29]]

^<<v3-16-29,29>>^ “And it must serve as a statute to time indefinite^&#42;1^ for YOU people: In the seventh month^&#42;2^ on the tenth of the month YOU should afflict YOUR souls, and YOU must not do any work, either the native^&#42;3^ or the alien resident^&#42;4^ who is residing as an alien in YOUR midst.

[NOTE]
====
. “To time indefinite.” Heb., ʽoh·lamʹ.
. See App 8B.
. “The native.” Heb., ha·ʼez·rachʹ; Lat., in·diʹge·na.
. “Or the alien resident.” Heb., wehag·gerʹ; Lat., adʹve·na.
====

[[v3-16-30]]

^<<v3-16-30,30>>^ For on this day atonement will be made^&#42;1^ for YOU to pronounce YOU clean. YOU will be clean from all YOUR sins before Jehovah.

[NOTE]
====
. Lit., “For on this day he will make atonement.” LXX is similar.
====

[[v3-16-31]]

^<<v3-16-31,31>>^ It is a sabbath of complete rest^&#42;1^ for YOU, and YOU must afflict YOUR souls. It is a statute to time indefinite.

[NOTE]
====
. Or, “of sabbath observance.”
====

[[v3-16-32]]

^<<v3-16-32,32>>^ “And the priest who will be anointed^&#42;1^ and whose hand will be filled with power^&#42;2^ to act as priest as successor of his father must make an atonement and must put on the linen garments. They are holy garments.

[NOTE]
====
. According to SyVg; M, “whom he will anoint”; LXX, “whom they will anoint.”
. According to Vg; M, “he will fill with power”; LXX, “they will fill with power.”
====

[[v3-16-33]]

^<<v3-16-33,33>>^ And he must make atonement for the holy sanctuary, and for the tent of meeting and for the altar he will make atonement; and for the priests and for all the people of the congregation he will make atonement.

[[v3-16-34]]

^<<v3-16-34,34>>^ And this must serve as a statute to time indefinite for YOU, in order to make atonement for the sons of Israel concerning all their sins once in the year.”
Accordingly he did just as Jehovah had commanded Moses.

'''

xref:003-leviticus/003-leviticus-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-leviticus/003-leviticus-017.adoc#v3-17-0[Próximo Capítulo &#62;]