include::./index.adoc[]

[[v3-8-0]]
=== Leviticus, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-8-1]]

^<<v3-8-1,1>>^ And Jehovah proceeded to speak to Moses, saying:

[[v3-8-2]]

^<<v3-8-2,2>>^ “Take Aaron and his sons with him and the garments and the anointing oil and the bull of the sin offering and the two rams and the basket of unfermented cakes,

[[v3-8-3]]

^<<v3-8-3,3>>^ and make all the assembly congregate^&#42;1^ at the entrance of the tent of meeting.”

[NOTE]
====
. “Congregate.” Gr., ek·kle·siʹa·son; Lat., con·gre·gaʹbis.
====

[[v3-8-4]]

^<<v3-8-4,4>>^ Then Moses did just as Jehovah had commanded him, and the assembly congregated at the entrance of the tent of meeting.

[[v3-8-5]]

^<<v3-8-5,5>>^ Moses now said to the assembly: “This is the thing that Jehovah has given command to do.”

[[v3-8-6]]

^<<v3-8-6,6>>^ So Moses brought Aaron and his sons near and washed them with water.

[[v3-8-7]]

^<<v3-8-7,7>>^ After that he put the robe upon him and girded him with the sash and clothed him with the sleeveless coat and put the ephʹod upon him and girded him with the girdle of the ephʹod and bound it closely to him with it.

[[v3-8-8]]

^<<v3-8-8,8>>^ Next he placed the breastpiece upon him and put in the breastpiece the Uʹrim and the Thumʹmim.^&#42;1^

[NOTE]
====
. See Ex 28:30 ftn, “Thummim.”
====

[[v3-8-9]]

^<<v3-8-9,9>>^ Then he placed the turban upon his head and placed upon the turban at the forefront of it the shining plate of gold, the holy sign of dedication,^&#42;1^ just as Jehovah had commanded Moses.

[NOTE]
====
. Or, “the holy diadem; the diadem of holiness.”
====

[[v3-8-10]]

^<<v3-8-10,10>>^ Moses now took the anointing oil and anointed the tabernacle and all that was in it and sanctified them.

[[v3-8-11]]

^<<v3-8-11,11>>^ After that he spattered some of it seven times upon the altar and anointed the altar and all its utensils and the basin and its stand so as to sanctify them.

[[v3-8-12]]

^<<v3-8-12,12>>^ Finally he poured some of the anointing oil upon Aaron’s head and anointed him so as to sanctify him.

[[v3-8-13]]

^<<v3-8-13,13>>^ Moses then brought Aaron’s sons near and clothed them with robes and girded them with sashes and wrapped the headgear upon them, just as Jehovah had commanded Moses.

[[v3-8-14]]

^<<v3-8-14,14>>^ Then he led up the bull of the sin offering and Aaron and his sons laid their hands upon the head of the bull of the sin offering.

[[v3-8-15]]

^<<v3-8-15,15>>^ And Moses proceeded to slaughter it and take the blood and put it with his finger upon the horns of the altar round about and purify the altar from sin, but the rest of the blood he poured at the base of the altar, that he might sanctify it to make atonement upon it.

[[v3-8-16]]

^<<v3-8-16,16>>^ After that he took all the fat that was upon the intestines, and the appendage of the liver and the two kidneys and their fat and Moses made them smoke upon the altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ And he had the bull and its skin and its flesh and its dung burned with fire outside the camp, just as Jehovah had commanded Moses.

[[v3-8-18]]

^<<v3-8-18,18>>^ He now brought the ram of the burnt offering near, and Aaron and his sons then laid their hands upon the head of the ram.

[[v3-8-19]]

^<<v3-8-19,19>>^ After that Moses slaughtered it and sprinkled the blood round about upon the altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ And he cut up the ram into its pieces, and Moses proceeded to make the head and the pieces and the suet smoke.

[[v3-8-21]]

^<<v3-8-21,21>>^ And the intestines and the shanks he washed with water, and Moses then made the entire ram smoke upon the altar. It was a burnt offering for a restful odor. It was an offering made by fire to Jehovah, just as Jehovah had commanded Moses.

[[v3-8-22]]

^<<v3-8-22,22>>^ Then he brought the second ram, the ram of the installation, near, and Aaron and his sons laid their hands upon the ram’s head.

[[v3-8-23]]

^<<v3-8-23,23>>^ After that Moses slaughtered it and took some of its blood and put it upon the lobe of Aaron’s right ear and upon the thumb of his right hand and upon the big toe of his right foot.

[[v3-8-24]]

^<<v3-8-24,24>>^ Next Moses brought Aaron’s sons near and put some of the blood upon the lobe of their right ear and upon the thumb of their right hand and upon the big toe of their right foot; but Moses sprinkled the rest of the blood round about upon the altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Then he took the fat and the fat tail and all the fat that was upon the intestines, and the appendage of the liver and the two kidneys and their fat and the right leg.

[[v3-8-26]]

^<<v3-8-26,26>>^ And out of the basket of unfermented cakes that was before Jehovah he took one unfermented ring-shaped cake and one ring-shaped cake of oiled bread and one wafer. He then placed them upon the fatty pieces and the right leg.

[[v3-8-27]]

^<<v3-8-27,27>>^ After that he put all of them upon the palms of Aaron and the palms of his sons and began to wave them to and fro as a wave offering before Jehovah.

[[v3-8-28]]

^<<v3-8-28,28>>^ Then Moses took them off their palms and made them smoke upon the altar on top of the burnt offering. They were an installation sacrifice for a restful odor. It was an offering made by fire to Jehovah.

[[v3-8-29]]

^<<v3-8-29,29>>^ And Moses proceeded to take the breast and to wave it to and fro as a wave offering before Jehovah. From the installation ram it became the portion for Moses, just as Jehovah had commanded Moses.

[[v3-8-30]]

^<<v3-8-30,30>>^ After that Moses took some of the anointing oil and some of the blood that was upon the altar and spattered it upon Aaron and his garments and upon his sons and the garments of his sons with him. Thus he sanctified Aaron and his garments and his sons and the garments of his sons with him.

[[v3-8-31]]

^<<v3-8-31,31>>^ Then Moses said to Aaron and his sons: “Boil the flesh at the entrance of the tent of meeting, and there is where YOU will eat it and the bread that is in the installation basket, just as I was given the command,^&#42;1^ saying, ‘Aaron and his sons will eat it.’

[NOTE]
====
. According to TOLXXSy; Vgc, “just as Jehovah instructed me.” Here the Heb. verb is vowel-pointed differently from the same Heb. verb in vs 35.
====

[[v3-8-32]]

^<<v3-8-32,32>>^ And what is left over of the flesh and the bread YOU will burn with fire.

[[v3-8-33]]

^<<v3-8-33,33>>^ And YOU must not go out from the entrance of the tent of meeting for seven days, until the day of fulfilling the days of YOUR installation, because it will take seven days to fill YOUR hand with power.^&#42;1^

[NOTE]
====
. “To fill your hand with power.” Or, “to install you; to empower you.” Heb., yemal·leʼʹ ʼeth-yedh·khemʹ; Gr., te·lei·oʹsei tas kheiʹras hy·monʹ (LXXThomson, “he will consecrate your hands”). Compare Heb 5:9 ftn.
====

[[v3-8-34]]

^<<v3-8-34,34>>^ Just as it has been done this day, Jehovah has commanded to be done so as to make atonement for YOU.

[[v3-8-35]]

^<<v3-8-35,35>>^ And YOU will stay at the entrance of the tent of meeting day and night for seven days, and YOU must keep the obligatory watch of Jehovah, that YOU may not die; for so I have been commanded.”

[[v3-8-36]]

^<<v3-8-36,36>>^ And Aaron and his sons proceeded to do all the things that Jehovah had commanded by means of Moses.

'''

xref:003-leviticus/003-leviticus-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-leviticus/003-leviticus-009.adoc#v3-9-0[Próximo Capítulo &#62;]