include::./index.adoc[]

[[v3-21-0]]
=== Leviticus, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-21-1]]

^<<v3-21-1,1>>^ And Jehovah went on to say to Moses: “Talk to the priests, Aaron’s sons, and you must say to them, ‘For a deceased soul^&#42;1^ no one may defile himself among his people.

[NOTE]
====
. Lit., “For a soul,” that is, a dead soul. Heb., leneʹphesh; Gr., psy·khaisʹ, pl. Compare vs 11 and Nu 6:6 ftns. See App 4A.
====

[[v3-21-2]]

^<<v3-21-2,2>>^ But for a blood relation of his who is close to him, for his mother and for his father and for his son and for his daughter and for his brother

[[v3-21-3]]

^<<v3-21-3,3>>^ and for his sister, a virgin who is close to him, who has not become a man’s, for her^&#42;1^ he may defile himself.

[NOTE]
====
. “Her,” M; LXX, “them.”
====

[[v3-21-4]]

^<<v3-21-4,4>>^ He may not defile himself for a woman possessed by an owner^&#42;1^ among his people so as to make himself profane.

[NOTE]
====
. “He may not defile himself for a woman possessed by an owner” is a proposed rendering as M is obscure; LXX, “He must not defile himself suddenly”; Vg, “He must not defile himself for a prince.”
====

[[v3-21-5]]

^<<v3-21-5,5>>^ They should not produce baldness upon their heads, and the extremity of their beard they should not shave, and on their flesh they should not make an incision.

[[v3-21-6]]

^<<v3-21-6,6>>^ They should prove themselves holy to their God, and they should not profane the name of their God, because they are those presenting Jehovah’s offerings made by fire, the bread of their God; and they must prove themselves holy.^&#42;1^

[NOTE]
====
. “Holy,” SamLXXSyVg; M, “something holy.”
====

[[v3-21-7]]

^<<v3-21-7,7>>^ A prostitute or a violated woman they should not take; and a woman divorced from her husband they should not take, because he is holy to his God.

[[v3-21-8]]

^<<v3-21-8,8>>^ So you must sanctify him, because he is one presenting the bread of your God. He should prove to be holy to you, because I Jehovah, who am sanctifying YOU, am holy.

[[v3-21-9]]

^<<v3-21-9,9>>^ “‘Now in case the daughter of a priest should make herself profane by committing prostitution, it is her father that she is profaning. She should be burned in the fire.

[[v3-21-10]]

^<<v3-21-10,10>>^ “‘And as for the high priest of his brothers upon whose head the anointing oil would be poured and whose hand was filled with power^&#42;1^ to wear the garments, he should not let his head go ungroomed, and he should not tear his garments.

[NOTE]
====
. “And whose hand was filled with power.” Or, “and who was empowered (inaugurated; installed).” Heb., u·mil·leʼʹ ʼeth-ya·dhohʹ; Gr., te·te·lei·o·meʹnou (LXXThomson, “having been consecrated”). See Heb 5:9 and Heb 7:28 ftns.
====

[[v3-21-11]]

^<<v3-21-11,11>>^ And he should not come to any dead soul.^&#42;1^ For his father and his mother he may not defile himself.

[NOTE]
====
. Lit., “souls of one dead.” Heb., naph·shothʹ, pl., followed by meth, “dead”; Gr., psy·kheiʹ followed by te·te·leu·te·kuiʹai, the perfect participle of “decease,” combine to mean “soul deceased”; Sy, “soul of one dead”; Vg, “dead one.”
====

[[v3-21-12]]

^<<v3-21-12,12>>^ He should also not go out from the sanctuary and not profane the sanctuary of his God, because the sign of dedication, the anointing oil of his God, is upon him. I am Jehovah.

[[v3-21-13]]

^<<v3-21-13,13>>^ “‘And for his part, he should take a woman in her virginity.

[[v3-21-14]]

^<<v3-21-14,14>>^ As for a widow or a divorced woman and one violated, a prostitute, none of these may he take, but he should take a virgin from his people as a wife.

[[v3-21-15]]

^<<v3-21-15,15>>^ And he should not profane his seed^&#42;1^ among his people, because I am Jehovah who is sanctifying him.’”

[NOTE]
====
. Or, “offspring.”
====

[[v3-21-16]]

^<<v3-21-16,16>>^ And Jehovah continued to speak to Moses, saying:

[[v3-21-17]]

^<<v3-21-17,17>>^ “Speak to Aaron, saying, ‘No man of your seed throughout their generations in whom there proves to be a defect may come near to present the bread of his God.

[[v3-21-18]]

^<<v3-21-18,18>>^ In case there is any man in whom there is a defect, he may not come near: a man blind or lame or with his nose slit or with one member too long,^&#42;1^

[NOTE]
====
. Or, “with a superfluous member.”
====

[[v3-21-19]]

^<<v3-21-19,19>>^ or a man in whom there proves to be a fracture of the foot or a fracture of the hand,

[[v3-21-20]]

^<<v3-21-20,20>>^ or hunchback or thin^&#42;1^ or diseased in his eyes or scabby or having ringworms or having his testicles broken.

[NOTE]
====
. Or, “dwarfed.” Possibly, “consumptive.”
====

[[v3-21-21]]

^<<v3-21-21,21>>^ Any man of the seed of Aaron the priest in whom there is a defect may not approach to present Jehovah’s offerings made by fire. There is a defect in him. He may not approach to present the bread of his God.

[[v3-21-22]]

^<<v3-21-22,22>>^ He may eat the bread of his God from the most holy things and from the holy things.

[[v3-21-23]]

^<<v3-21-23,23>>^ However, he may not come in near the curtain, and he may not approach the altar, because there is a defect in him; and he should not profane my sanctuary, for I am Jehovah who is sanctifying them.’”

[[v3-21-24]]

^<<v3-21-24,24>>^ Accordingly Moses spoke to Aaron and his sons and all the sons of Israel.

'''

xref:003-leviticus/003-leviticus-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-leviticus/003-leviticus-022.adoc#v3-22-0[Próximo Capítulo &#62;]