include::./index.adoc[]

[[v3-9-0]]
=== Leviticus, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-9-1]]

^<<v3-9-1,1>>^ And it came about on the eighth day that Moses called Aaron and his sons and the older men of Israel.

[[v3-9-2]]

^<<v3-9-2,2>>^ Then he said to Aaron: “Take for yourself a young calf for a sin offering and a ram for a burnt offering, sound ones, and present them before Jehovah.

[[v3-9-3]]

^<<v3-9-3,3>>^ But to the sons^&#42;1^ of Israel you will speak, saying, ‘Take a male goat for a sin offering and a calf and a young ram, each a year old, sound ones, for a burnt offering,

[NOTE]
====
. “Sons,” MSyVg; SamLXX, “assembly of older men.”
====

[[v3-9-4]]

^<<v3-9-4,4>>^ and a bull and a ram for communion sacrifices to sacrifice them before Jehovah, and a grain offering moistened with oil, because today is when Jehovah will certainly appear to YOU.’”

[[v3-9-5]]

^<<v3-9-5,5>>^ Accordingly they took what Moses had commanded before the tent of meeting. Then the whole assembly came near and stood before Jehovah.

[[v3-9-6]]

^<<v3-9-6,6>>^ And Moses went on to say: “This is the thing that Jehovah has commanded YOU should do, that the glory of Jehovah may appear to YOU.”

[[v3-9-7]]

^<<v3-9-7,7>>^ Then Moses said to Aaron: “Go near to the altar and render up your sin offering and your burnt offering, and make atonement in your own behalf and in behalf of your house;^&#42;1^ and render up the offering of the people and make atonement in their behalf, just as Jehovah has commanded.”

[NOTE]
====
. “Your house,” LXX (compare 16:17); MSamSyVg, “the people.”
====

[[v3-9-8]]

^<<v3-9-8,8>>^ Aaron immediately went near to the altar and slaughtered the calf of the sin offering that was for him.

[[v3-9-9]]

^<<v3-9-9,9>>^ Then Aaron’s sons presented the blood to him and he dipped his finger in the blood and put it upon the horns of the altar, and the rest of the blood he poured at the base of the altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ And he made the fat and the kidneys and the appendage of the liver from the sin offering smoke upon the altar, just as Jehovah had commanded Moses.

[[v3-9-11]]

^<<v3-9-11,11>>^ And he burned the flesh and the skin with fire outside the camp.

[[v3-9-12]]

^<<v3-9-12,12>>^ Then he slaughtered the burnt offering and Aaron’s sons handed him the blood and he sprinkled it round about upon the altar.

[[v3-9-13]]

^<<v3-9-13,13>>^ And they handed him the burnt offering in its pieces and the head, and he proceeded to make them smoke upon the altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ Further, he washed the intestines and the shanks and made them smoke upon the burnt offering on the altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ He now went presenting the offering of the people and took the goat of the sin offering that was for the people and slaughtered it and made an offering for sin with it as with the first.

[[v3-9-16]]

^<<v3-9-16,16>>^ Then he presented the burnt offering and handled it according to the regular procedure.

[[v3-9-17]]

^<<v3-9-17,17>>^ He next presented the grain offering and filled his hand with some of it and made it smoke upon the altar, apart from the burnt offering of the morning.

[[v3-9-18]]

^<<v3-9-18,18>>^ After that he slaughtered the bull and the ram of the communion sacrifice that was for the people. Then Aaron’s sons handed him the blood and he sprinkled it round about upon the altar.

[[v3-9-19]]

^<<v3-9-19,19>>^ As for the fatty pieces of the bull and the fat tail of the ram and the fat covering^&#42;1^ and the kidneys and the appendage of the liver,

[NOTE]
====
. That is, of the intestines.
====

[[v3-9-20]]

^<<v3-9-20,20>>^ they^&#42;1^ now placed the fatty pieces upon the breasts, after which he made the fatty pieces smoke upon the altar.

[NOTE]
====
. “They,” MVg; SamLXXSy, “he.”
====

[[v3-9-21]]

^<<v3-9-21,21>>^ But the breasts and the right leg Aaron waved to and fro as a wave offering before Jehovah, just as Moses had commanded.

[[v3-9-22]]

^<<v3-9-22,22>>^ Then Aaron raised his hands toward the people and blessed them and came down from rendering the sin offering and the burnt offering and the communion sacrifices.

[[v3-9-23]]

^<<v3-9-23,23>>^ Finally Moses and Aaron went into the tent of meeting and came out and blessed the people.
Then Jehovah’s glory appeared to all the people,

[[v3-9-24]]

^<<v3-9-24,24>>^ and fire came out from before Jehovah and began consuming the burnt offering and the fatty pieces upon the altar. When all the people got to see it, they broke out into shouting and went falling upon their faces.

'''

xref:003-leviticus/003-leviticus-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-leviticus/003-leviticus-010.adoc#v3-10-0[Próximo Capítulo &#62;]