include::./index.adoc[]

[[v3-18-0]]
=== Leviticus, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-18-1]]

^<<v3-18-1,1>>^ And Jehovah continued to speak to Moses, saying:

[[v3-18-2]]

^<<v3-18-2,2>>^ “Speak to the sons of Israel, and you must say to them, ‘I am Jehovah YOUR God.

[[v3-18-3]]

^<<v3-18-3,3>>^ The way the land of Egypt does, in which YOU dwelt, YOU must not do; and the way the land of Caʹnaan does, into which I am bringing YOU, YOU must not do; and in their statutes YOU must not walk.

[[v3-18-4]]

^<<v3-18-4,4>>^ My judicial decisions YOU should carry out, and my statutes YOU should keep so as to walk in them. I am Jehovah YOUR God.

[[v3-18-5]]

^<<v3-18-5,5>>^ And YOU must keep my statutes and my judicial decisions, which if a man^&#42;1^ will do, he must also live by means of them.^&#42;2^ I am Jehovah.

[NOTE]
====
. Or, “an earthling man.” Heb., ha·ʼa·dhamʹ.
. Or, “live in them.”
====

[[v3-18-6]]

^<<v3-18-6,6>>^ “‘YOU people must not come near, any man of YOU, to any close fleshly relative of his to lay bare nakedness. I am Jehovah.

[[v3-18-7]]

^<<v3-18-7,7>>^ The nakedness^&#42;1^ of your father and the nakedness of your mother you must not lay bare. She is your mother. You must not lay bare her nakedness.

[NOTE]
====
. Or, “genital organs.”
====

[[v3-18-8]]

^<<v3-18-8,8>>^ “‘The nakedness of your father’s wife you must not lay bare. It is your father’s nakedness.

[[v3-18-9]]

^<<v3-18-9,9>>^ “‘As for the nakedness of your sister, the daughter of your father or the daughter of your mother, whether born in the same household or born outside it, you must not lay bare their nakedness.

[[v3-18-10]]

^<<v3-18-10,10>>^ “‘As for the nakedness of the daughter of your son or the daughter of your daughter, you must not lay bare their nakedness, because they are your nakedness.

[[v3-18-11]]

^<<v3-18-11,11>>^ “‘As for the nakedness of the daughter of your father’s wife, the offspring of your father, she being your sister, you must not lay bare her nakedness.

[[v3-18-12]]

^<<v3-18-12,12>>^ “‘The nakedness of your father’s sister you must not lay bare. She is the blood relation of your father.

[[v3-18-13]]

^<<v3-18-13,13>>^ “‘The nakedness of your mother’s sister you must not lay bare, because she is a blood relation of your mother.

[[v3-18-14]]

^<<v3-18-14,14>>^ “‘The nakedness of your father’s brother you must not lay bare. You must not come near his wife. She is your aunt.

[[v3-18-15]]

^<<v3-18-15,15>>^ “‘The nakedness of your daughter-in-law you must not lay bare. She is your son’s wife. You must not lay her nakedness bare.

[[v3-18-16]]

^<<v3-18-16,16>>^ “‘The nakedness of your brother’s wife you must not lay bare. It is your brother’s nakedness.

[[v3-18-17]]

^<<v3-18-17,17>>^ “‘The nakedness of a woman and her daughter you must not lay bare. The daughter of her son and the daughter of her daughter you must not take in order to lay her nakedness bare. They are cases of blood relationship. It is loose conduct.^&#42;1^

[NOTE]
====
. “Loose conduct.” Heb., zim·mahʹ; Lat., coʹi·tus in·ceʹstus. Compare Ro 13:13 ftn; Ga 5:19 ftn, “Conduct.”
====

[[v3-18-18]]

^<<v3-18-18,18>>^ “‘And you must not take a woman in addition to her sister as a rival to uncover her nakedness, that is, besides her during her lifetime.

[[v3-18-19]]

^<<v3-18-19,19>>^ “‘And you must not come near a woman during the menstruation of her impurity to lay her nakedness bare.

[[v3-18-20]]

^<<v3-18-20,20>>^ “‘And you must not give your emission as semen to the wife of your associate to become unclean by it.

[[v3-18-21]]

^<<v3-18-21,21>>^ “‘And you must not allow the devoting^&#42;1^ of any of your offspring to Moʹlech. You must not profane the name of your God that way. I am Jehovah.

[NOTE]
====
. Or, “allow the passing [through the fire].”
====

[[v3-18-22]]

^<<v3-18-22,22>>^ “‘And you must not lie down with a male the same as you lie down with a woman. It is a detestable thing.

[[v3-18-23]]

^<<v3-18-23,23>>^ “‘And you must not give your emission to any beast to become unclean by it, and a woman should not stand before a beast to have connection with it.^&#42;1^ It is a violation of what is natural.

[NOTE]
====
. Or, “to have connection with her.” Sy, “that she may be ridden by it.”
====

[[v3-18-24]]

^<<v3-18-24,24>>^ “‘Do not make yourselves unclean by any of these things, because by all these things the nations whom I am sending out from before YOU have made themselves unclean.

[[v3-18-25]]

^<<v3-18-25,25>>^ Consequently the land is unclean, and I shall bring punishment for its error upon it, and the land will vomit its inhabitants out.

[[v3-18-26]]

^<<v3-18-26,26>>^ And YOU yourselves must keep my statutes and my judicial decisions, and YOU must not do any of all these detestable things, whether a native or an alien resident who is residing as an alien in YOUR midst.

[[v3-18-27]]

^<<v3-18-27,27>>^ For all these detestable things the men of the land who were before YOU have done, so that the land is unclean.

[[v3-18-28]]

^<<v3-18-28,28>>^ Then the land will not vomit YOU out for YOUR defiling it the same way as it will certainly vomit the nations^&#42;1^ out who were before YOU.

[NOTE]
====
. “Nations,” LXXSy; MVg, “nation.”
====

[[v3-18-29]]

^<<v3-18-29,29>>^ In case anyone does any of all these detestable things, then the souls doing them must be cut off from among their people.

[[v3-18-30]]

^<<v3-18-30,30>>^ And YOU must keep YOUR obligation to me not to carry on any of the detestable customs that have been carried on before YOU, that YOU may not make yourselves unclean by them. I am Jehovah YOUR God.’”

'''

xref:003-leviticus/003-leviticus-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-leviticus/003-leviticus-019.adoc#v3-19-0[Próximo Capítulo &#62;]