include::./index.adoc[]

[[v3-2-0]]
=== Leviticus, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-2-1]]

^<<v3-2-1,1>>^ “‘Now in case some soul would present as an offering a grain offering to Jehovah, his offering should prove to be fine flour; and he must pour oil over it and put frankincense upon it.

[[v3-2-2]]

^<<v3-2-2,2>>^ And he must bring it to the sons of Aaron, the priests, and the priest must grasp from it his handful of its fine flour and its oil along with all its frankincense; and he must make it smoke as a remembrancer of it upon the altar, as an offering made by fire of a restful odor to Jehovah.

[[v3-2-3]]

^<<v3-2-3,3>>^ And what is left of the grain offering belongs to Aaron and his sons, as something most holy from Jehovah’s offerings made by fire.

[[v3-2-4]]

^<<v3-2-4,4>>^ “‘And in case you would present as an offering a grain offering in the way of something baked in the oven, it should be of fine flour, unfermented ring-shaped cakes moistened with oil or^&#42;1^ unfermented wafers smeared with oil.

[NOTE]
====
. Or, “and.”
====

[[v3-2-5]]

^<<v3-2-5,5>>^ “‘And if your offering is a grain offering from off the griddle, it should prove to be of fine flour moistened with oil, unfermented.

[[v3-2-6]]

^<<v3-2-6,6>>^ There should be a breaking^&#42;1^ of it up into pieces, and you must pour oil upon it. It is a grain offering.

[NOTE]
====
. “Breaking.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v3-2-7]]

^<<v3-2-7,7>>^ “‘And if your offering is a grain offering out of the deep-fat kettle,^&#42;1^ it should be made of fine flour with oil.

[NOTE]
====
. A cooking pot for deep-fat frying, like a present-day soup or stew kettle.
====

[[v3-2-8]]

^<<v3-2-8,8>>^ And you must bring the grain offering that was made of these to Jehovah; and it must be presented to the priest and he must bring it near to the altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ And the priest must lift off some of the grain offering as a remembrancer of it and must make it smoke on the altar, as an offering made by fire of a restful odor to Jehovah.

[[v3-2-10]]

^<<v3-2-10,10>>^ And what is left of the grain offering belongs to Aaron and his sons, as something most holy of Jehovah’s offerings by fire.

[[v3-2-11]]

^<<v3-2-11,11>>^ “‘No grain offering that YOU will present to Jehovah should be made a leavened thing, because YOU must make no sourdough and no honey^&#42;1^ at all smoke as an offering made by fire to Jehovah.

[NOTE]
====
. “Honey.” Evidently not that of the bee but the moisture or syrup of figs, or juice or syrup of fruits.
====

[[v3-2-12]]

^<<v3-2-12,12>>^ “‘As^&#42;1^ an offering of the firstfruits, YOU will present them to Jehovah, and they must not come up onto the altar for a restful odor.

[NOTE]
====
. Or, “As for.”
====

[[v3-2-13]]

^<<v3-2-13,13>>^ “‘And every offering of your grain offering you will season with salt; and you must not allow the salt of the covenant of your God to be missing upon your grain offering. Along with every offering of yours you will present salt.

[[v3-2-14]]

^<<v3-2-14,14>>^ “‘And if you would present the grain offering of the first ripe fruits to Jehovah, you should present green ears roasted with fire, the grits^&#42;1^ of new grain, as the grain offering of your first ripe fruits.

[NOTE]
====
. That is, coarsely crushed kernels.
====

[[v3-2-15]]

^<<v3-2-15,15>>^ And you must put oil upon it and place frankincense upon it. It is a grain offering.

[[v3-2-16]]

^<<v3-2-16,16>>^ And the priest must make the remembrancer of it smoke, that is, some of its grits and oil, along with all its frankincense, as an offering made by fire to Jehovah.

'''

xref:003-leviticus/003-leviticus-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-leviticus/003-leviticus-003.adoc#v3-3-0[Próximo Capítulo &#62;]