include::./index.adoc[]

[[v3-26-0]]
=== Leviticus, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-26-1]]

^<<v3-26-1,1>>^ “‘YOU must not make valueless gods^&#42;1^ for yourselves, and YOU must not set up a carved image or a sacred pillar for yourselves, and YOU must not put a stone as a showpiece in YOUR land in order to bow down toward it; for I am Jehovah YOUR God.

[NOTE]
====
. “Make an idol,” Vg.
====

[[v3-26-2]]

^<<v3-26-2,2>>^ YOU should keep my sabbaths and stand in awe of my sanctuary. I am Jehovah.

[[v3-26-3]]

^<<v3-26-3,3>>^ “‘If YOU continue walking in my statutes and keeping my commandments and YOU do carry them out,

[[v3-26-4]]

^<<v3-26-4,4>>^ I shall also certainly give YOUR showers of rain at their proper time, and the land will indeed give its yield, and the tree of the field will give its fruit.

[[v3-26-5]]

^<<v3-26-5,5>>^ And YOUR threshing will certainly reach to YOUR grape gathering, and the grape gathering will reach to the sowing of seed; and YOU will indeed eat YOUR bread to satisfaction and dwell in security in YOUR land.

[[v3-26-6]]

^<<v3-26-6,6>>^ And I will put peace in the land, and YOU will indeed lie down, with no one making &#91;YOU&#93; tremble; and I will make the injurious wild beast cease out of the land, and a sword will not pass through YOUR land.

[[v3-26-7]]

^<<v3-26-7,7>>^ And YOU will certainly chase YOUR enemies, and they will indeed fall before YOU by the sword.

[[v3-26-8]]

^<<v3-26-8,8>>^ And five of YOU will certainly chase a hundred, and a hundred of YOU will chase ten thousand, and YOUR enemies will indeed fall before YOU by the sword.

[[v3-26-9]]

^<<v3-26-9,9>>^ “‘And I will turn myself to YOU and make YOU fruitful and multiply YOU, and I will carry out my covenant with YOU.

[[v3-26-10]]

^<<v3-26-10,10>>^ And YOU will certainly eat the old of the preceding year, and YOU will bring out the old ahead of the new.

[[v3-26-11]]

^<<v3-26-11,11>>^ And I shall certainly put my tabernacle in the midst of YOU, and my soul will not abhor YOU.

[[v3-26-12]]

^<<v3-26-12,12>>^ And I shall indeed walk in the midst of YOU and prove myself YOUR God, and YOU, on YOUR part, will prove yourselves my people.

[[v3-26-13]]

^<<v3-26-13,13>>^ I am Jehovah YOUR God, who brought YOU out of the land of Egypt from acting as slaves to them, and I proceeded to break the bars of YOUR yoke and make YOU walk erect.

[[v3-26-14]]

^<<v3-26-14,14>>^ “‘However, if YOU will not listen to me nor do all these commandments,

[[v3-26-15]]

^<<v3-26-15,15>>^ and if YOU will reject my statutes, and if YOUR souls will abhor my judicial decisions so as not to do all my commandments, to the extent of YOUR violating my covenant,

[[v3-26-16]]

^<<v3-26-16,16>>^ then I, for my part, shall do the following to YOU, and in punishment I shall certainly bring upon YOU disturbance with tuberculosis and burning fever, causing the eyes to fail and making the soul pine away. And YOU will simply sow YOUR seed for nothing, as YOUR enemies will certainly eat it up.

[[v3-26-17]]

^<<v3-26-17,17>>^ And I shall indeed set my face against YOU, and YOU will certainly be defeated before YOUR enemies; and those who hate YOU will just tread down upon YOU, and YOU will actually flee when no one is pursuing YOU.

[[v3-26-18]]

^<<v3-26-18,18>>^ “‘If, though, despite these things, YOU will not listen to me, I shall then have to chastise YOU seven times as much^&#42;1^ for YOUR sins.

[NOTE]
====
. Or, “sevenfold,” without reference to any time element.
====

[[v3-26-19]]

^<<v3-26-19,19>>^ And I shall have to break the pride of YOUR strength and make YOUR heavens like iron and YOUR earth like copper.

[[v3-26-20]]

^<<v3-26-20,20>>^ And YOUR power will simply be expended for nothing, as YOUR earth will not give its yield, and the tree of the earth will not give its fruit.

[[v3-26-21]]

^<<v3-26-21,21>>^ “‘But if YOU keep walking in opposition to me and not wishing to listen to me, I shall then have to inflict seven times more blows upon YOU according to YOUR sins.

[[v3-26-22]]

^<<v3-26-22,22>>^ And I will send the wild beasts of the field among YOU, and they will certainly bereave YOU of children and cut off YOUR domestic animals and reduce the number of YOU, and YOUR roads will actually be desolated.

[[v3-26-23]]

^<<v3-26-23,23>>^ “‘Nevertheless, if with these things YOU do not let yourselves be corrected by me and YOU just have to walk in opposition to me,

[[v3-26-24]]

^<<v3-26-24,24>>^ I, yes, I, shall then have to walk in opposition to YOU; and I, even I, shall have to strike YOU seven times for YOUR sins.

[[v3-26-25]]

^<<v3-26-25,25>>^ And I shall certainly bring upon YOU a sword wreaking vengeance for the covenant; and YOU will indeed gather yourselves into YOUR cities, and I shall certainly send pestilence into the midst of YOU, and YOU must be given into the hand of an enemy.

[[v3-26-26]]

^<<v3-26-26,26>>^ When I have broken for YOU the rods around which ring-shaped loaves are suspended,^&#42;1^ ten women will then actually bake YOUR bread in but one oven and give back YOUR bread by weight; and YOU must eat but YOU will not be satisfied.

[NOTE]
====
. Lit., “the rod of bread.”
====

[[v3-26-27]]

^<<v3-26-27,27>>^ “‘If, however, with this YOU will not listen to me and YOU just must walk in opposition to me,

[[v3-26-28]]

^<<v3-26-28,28>>^ I shall then have to walk in heated opposition to YOU, and I, yes, I, shall have to chastise YOU seven times for YOUR sins.

[[v3-26-29]]

^<<v3-26-29,29>>^ So YOU will have to eat the flesh of YOUR sons, and YOU will eat the flesh of YOUR daughters.

[[v3-26-30]]

^<<v3-26-30,30>>^ And I shall certainly annihilate YOUR sacred high places and cut off YOUR incense stands and lay YOUR own carcasses upon the carcasses of YOUR dungy idols; and my soul will simply abhor YOU.

[[v3-26-31]]

^<<v3-26-31,31>>^ And I shall indeed give YOUR cities to the sword and lay YOUR sanctuaries^&#42;1^ desolate, and I shall not smell YOUR restful odors.

[NOTE]
====
. “Sanctuaries,” MLXXVg; SamSy and 53 Heb. mss, “sanctuary.”
====

[[v3-26-32]]

^<<v3-26-32,32>>^ And I, for my part, will lay the land desolate, and YOUR enemies who are dwelling in it will simply stare in amazement over it.

[[v3-26-33]]

^<<v3-26-33,33>>^ And YOU I shall scatter among the nations, and I will unsheathe a sword after YOU; and YOUR land must become a desolation, and YOUR cities will become a desolate ruin.

[[v3-26-34]]

^<<v3-26-34,34>>^ “‘At that time the land will pay off its sabbaths all the days of its lying desolated, while YOU are in the land of YOUR enemies. At that time the land will keep sabbath, as it must repay its sabbaths.

[[v3-26-35]]

^<<v3-26-35,35>>^ All the days of its lying desolated it will keep sabbath, for the reason that it did not keep sabbath during YOUR sabbaths when YOU were dwelling upon it.

[[v3-26-36]]

^<<v3-26-36,36>>^ “‘As for those remaining among YOU, I shall certainly bring timidity into their hearts in the lands of their enemies; and the sound of a leaf driven about will indeed chase them away, and they will actually flee as in flight from a sword and fall without anyone chasing.

[[v3-26-37]]

^<<v3-26-37,37>>^ And they will certainly stumble against one another as if from before a sword without anyone chasing, and for YOU there will prove to be no ability to stand &#91;in resistance&#93; before YOUR enemies.

[[v3-26-38]]

^<<v3-26-38,38>>^ And YOU must perish among the nations, and the land of YOUR enemies must eat YOU up.

[[v3-26-39]]

^<<v3-26-39,39>>^ As for those remaining among YOU, they will rot away because of their error in the lands of YOUR enemies. Yes, even because of the errors of their fathers, with them they will rot away.

[[v3-26-40]]

^<<v3-26-40,40>>^ And they will certainly confess their own error and the error of their fathers in their unfaithfulness when they behaved unfaithfully toward me, yes, even when they walked in opposition to me.

[[v3-26-41]]

^<<v3-26-41,41>>^ Yet I, for my part, proceeded to walk in opposition to them, and I had to bring them into the land of their enemies.
“‘Perhaps^&#42;1^ at that time their uncircumcised heart will be humbled, and at that time they will pay off their error.

[NOTE]
====
. “Perhaps; Or,” MSam; Sy, “And”; LXX omits.
====

[[v3-26-42]]

^<<v3-26-42,42>>^ And I shall indeed remember my covenant with Jacob; and even my covenant with Isaac and even my covenant with Abraham I shall remember, and the land I shall remember.

[[v3-26-43]]

^<<v3-26-43,43>>^ All the while the land was left abandoned by them and was paying off its sabbaths while it was lying desolated without them and they themselves were paying for their error, because, even because,^&#42;1^ they had rejected my judicial decisions, and their souls had abhorred my statutes.

[NOTE]
====
. “Because, even because.” Heb., yaʹʽan u·veyaʹʽan. This emphatic doubling of the conjunction yaʹʽan occurs three times: here, in Eze 13:10 and, without the copulative Waw (u), in Eze 36:3.
====

[[v3-26-44]]

^<<v3-26-44,44>>^ And yet for all this, while they continue in the land of their enemies, I shall certainly not reject them nor abhor them so as to exterminate them, to violate my covenant with them; for I am Jehovah their God.

[[v3-26-45]]

^<<v3-26-45,45>>^ And I will remember in their behalf the covenant of the ancestors whom I brought forth out of the land of Egypt under the eyes of the nations, in order to prove myself their God. I am Jehovah.’”

[[v3-26-46]]

^<<v3-26-46,46>>^ These are the regulations and the judicial decisions and the laws that Jehovah set between himself and the sons of Israel in Mount Siʹnai by means of Moses.

'''

xref:003-leviticus/003-leviticus-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-leviticus/003-leviticus-027.adoc#v3-27-0[Próximo Capítulo &#62;]