include::./index.adoc[]

[[v3-19-0]]
=== Leviticus, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v3-19-1]]

^<<v3-19-1,1>>^ And Jehovah spoke further to Moses, saying:

[[v3-19-2]]

^<<v3-19-2,2>>^ “Speak to the entire assembly of the sons of Israel, and you must say to them, ‘YOU should prove yourselves holy, because I Jehovah YOUR God am holy.

[[v3-19-3]]

^<<v3-19-3,3>>^ “‘YOU should fear each one his mother and his father,^&#42;1^ and my sabbaths YOU should keep. I am Jehovah YOUR God.

[NOTE]
====
. According to MVg; LXXSyVgc, “his father and his mother.”
====

[[v3-19-4]]

^<<v3-19-4,4>>^ Do not turn yourselves to valueless gods,^&#42;1^ and YOU must not make molten gods for yourselves. I am Jehovah YOUR God.

[NOTE]
====
. “To idols,” LXXVg.
====

[[v3-19-5]]

^<<v3-19-5,5>>^ “‘Now in case YOU should sacrifice a communion sacrifice to Jehovah, YOU should sacrifice it to gain approval for yourselves.

[[v3-19-6]]

^<<v3-19-6,6>>^ On the day of YOUR sacrifice and directly the next day it should be eaten, but what is left over till the third day should be burned in the fire.

[[v3-19-7]]

^<<v3-19-7,7>>^ If, though, it should at all be eaten on the third day, it is a foul thing. It will not be accepted with approval.

[[v3-19-8]]

^<<v3-19-8,8>>^ And the one^&#42;1^ eating it will answer for his error, because he has profaned a holy thing of Jehovah; and that soul must be cut off from his people.

[NOTE]
====
. “One,” SamLXXSy; M, “ones.”
====

[[v3-19-9]]

^<<v3-19-9,9>>^ “‘And when YOU people reap the harvest of YOUR land, you must not reap the edge of your field completely, and the gleaning of your harvest you must not pick up.

[[v3-19-10]]

^<<v3-19-10,10>>^ Also, you must not gather the leftovers of your vineyard, and you must not pick up the scattered grapes of your vineyard. For the afflicted one and the alien resident you should leave them. I am Jehovah YOUR God.

[[v3-19-11]]

^<<v3-19-11,11>>^ “‘YOU people must not steal, and YOU must not deceive, and YOU must not deal falsely anyone with his associate.

[[v3-19-12]]

^<<v3-19-12,12>>^ And YOU must not swear in my name to a lie, so that you do profane the name of your God. I am Jehovah.

[[v3-19-13]]

^<<v3-19-13,13>>^ You must not defraud your fellow, and you must not rob. The wages of a hired laborer should not stay all night with you until morning.

[[v3-19-14]]

^<<v3-19-14,14>>^ “‘You must not call down evil upon a deaf man, and before a blind man you must not put an obstacle; and you must be in fear of your God. I am Jehovah.

[[v3-19-15]]

^<<v3-19-15,15>>^ “‘YOU people must not do injustice in the judgment. You must not treat the lowly with partiality, and you must not prefer the person of a great one. With justice you should judge your associate.

[[v3-19-16]]

^<<v3-19-16,16>>^ “‘You must not go around among your people for the sake of slandering. You must not stand up against your fellow’s blood. I am Jehovah.

[[v3-19-17]]

^<<v3-19-17,17>>^ “‘You must not hate your brother in your heart. You should by all means reprove your associate, that you may not bear sin along with him.

[[v3-19-18]]

^<<v3-19-18,18>>^ “‘You must not take vengeance nor have a grudge against the sons of your people; and you must love your fellow as yourself. I am Jehovah.

[[v3-19-19]]

^<<v3-19-19,19>>^ “‘YOU people should keep my statutes: You must not interbreed your domestic animals of two sorts. You must not sow your field with seeds of two sorts, and you must not put upon yourself a garment of two sorts of thread, mixed together.

[[v3-19-20]]

^<<v3-19-20,20>>^ “‘Now in case a man lies down with a woman and has an emission of semen, when she is a maidservant designated for another man, and she has not in any way been redeemed nor has freedom been given her, punishment^&#42;1^ should take place.^&#42;2^ They^&#42;3^ should not be put to death, because she was not set free.

[NOTE]
====
. Or, “an investigation.”
. Sam adds, “for him.”
. “They,” MLXX; Sam, “He.”
====

[[v3-19-21]]

^<<v3-19-21,21>>^ And he must bring his guilt offering to Jehovah to the entrance of the tent of meeting, a ram of guilt offering.

[[v3-19-22]]

^<<v3-19-22,22>>^ And the priest must make atonement for him with the ram of the guilt offering before Jehovah for his sin that he committed; and his sin that he committed must be forgiven him.

[[v3-19-23]]

^<<v3-19-23,23>>^ “‘And in case YOU people come into the land, and YOU must plant any tree for food, YOU must also consider its fruitage impure as its “foreskin.” For three years it will continue uncircumcised for YOU. It should not be eaten.

[[v3-19-24]]

^<<v3-19-24,24>>^ But in the fourth year all its fruit will become a holy thing of festal exultation to Jehovah.

[[v3-19-25]]

^<<v3-19-25,25>>^ And in the fifth year YOU may eat its fruit in order to add its produce to yourselves. I am Jehovah YOUR God.

[[v3-19-26]]

^<<v3-19-26,26>>^ “‘YOU must eat nothing along with blood.
“‘YOU must not look for omens, and YOU must not practice magic.

[[v3-19-27]]

^<<v3-19-27,27>>^ “‘YOU must not cut YOUR sidelocks^&#42;1^ short around, and you must not destroy the extremity of your beard.

[NOTE]
====
. Lit., “the corner (extremity) of your head.”
====

[[v3-19-28]]

^<<v3-19-28,28>>^ “‘And YOU must not make cuts in YOUR flesh for a deceased soul,^&#42;1^ and YOU must not put tattoo marking upon yourselves. I am Jehovah.

[NOTE]
====
. Lit., “for a soul,” that is, a dead soul. Heb., la·neʹphesh; Gr., psy·kheiʹ. See 21:11 ftn; Nu 6:6 ftn.
====

[[v3-19-29]]

^<<v3-19-29,29>>^ “‘Do not profane your daughter by making her a prostitute, in order that the land may not commit prostitution and the land actually be filled with loose morals.

[[v3-19-30]]

^<<v3-19-30,30>>^ “‘My sabbaths YOU should keep, and YOU should stand in awe of my sanctuary. I am Jehovah.

[[v3-19-31]]

^<<v3-19-31,31>>^ “‘Do not turn yourselves to the spirit mediums,^&#42;1^ and do not consult professional foretellers of events, so as to become unclean by them. I am Jehovah YOUR God.

[NOTE]
====
. “Spirit mediums.” Agents used as a vessel of a demon of divination. LXX, “ventriloquists”; Lat., maʹgos, “astrologers.” See Ac 16:16.
====

[[v3-19-32]]

^<<v3-19-32,32>>^ “‘Before gray hair you should rise up, and you must show consideration for the person of an old man, and you must be in fear of your God. I am Jehovah.

[[v3-19-33]]

^<<v3-19-33,33>>^ “‘And in case an alien resident resides with you as an alien in YOUR land, YOU must not mistreat him.

[[v3-19-34]]

^<<v3-19-34,34>>^ The alien resident who resides as an alien with YOU should become to YOU like a native of YOURS; and you must love him as yourself, for YOU became alien residents in the land of Egypt. I am Jehovah YOUR God.

[[v3-19-35]]

^<<v3-19-35,35>>^ “‘YOU must not commit injustice in judging, in measuring, in weighing or in measuring liquids.

[[v3-19-36]]

^<<v3-19-36,36>>^ YOU should prove to have accurate scales, accurate weights,^&#42;1^ an accurate eʹphah and an accurate hin. Jehovah YOUR God I am, who have brought YOU out of the land of Egypt.

[NOTE]
====
. Lit., “stones.”
====

[[v3-19-37]]

^<<v3-19-37,37>>^ So YOU must keep all my statutes and all my judicial decisions, and YOU must do them. I am Jehovah.’”

'''

xref:003-leviticus/003-leviticus-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-leviticus/003-leviticus-020.adoc#v3-20-0[Próximo Capítulo &#62;]