include::./index.adoc[]

[[v39-3-0]]
=== Malachi, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v39-3-1]]

^<<v39-3-1,1>>^ “Look! I am sending my messenger,^&#42;1^ and he must clear up a way before me. And suddenly there will come to His temple^&#42;2^ the &#91;true&#93; Lord,^&#42;3^ whom YOU people are seeking, and the messenger^&#42;4^ of the covenant in whom YOU are delighting. Look! He will certainly come,” Jehovah of armies has said.

[NOTE]
====
. “My messenger.” Heb., mal·ʼa·khiʹ; Lat., anʹge·lum. See Title ftn.
. “His temple.” Heb., heh·kha·lohʹ; Gr., na·onʹ; Lat., temʹplum. See Mt 23:16 ftn.
. “The [true] Lord.” Heb., ha·ʼA·dhohnʹ; Gr., Kyʹri·os; Lat., Do·mi·naʹtor. See App 1H.
. “And the messenger (angel).” Heb., u·mal·ʼakhʹ; Gr., agʹge·los; Lat., anʹge·lus.
====

[[v39-3-2]]

^<<v39-3-2,2>>^ “But who will be putting up with the day of his coming, and who will be the one standing when he appears? For he will be like the fire of a refiner and like the lye of laundrymen.

[[v39-3-3]]

^<<v39-3-3,3>>^ And he must sit as a refiner and cleanser of silver and must cleanse the sons of Leʹvi;^&#42;1^ and he must clarify them like gold and like silver, and they will certainly become to Jehovah people presenting a gift offering in righteousness.

[NOTE]
====
. “Levi.” Heb., Le·wiʹ.
====

[[v39-3-4]]

^<<v39-3-4,4>>^ And the gift offering of Judah and of Jerusalem will actually be gratifying to Jehovah, as in the days of long ago and as in the years of antiquity.

[[v39-3-5]]

^<<v39-3-5,5>>^ “And I will come near to YOU people for the judgment, and I will become a speedy witness against the sorcerers, and against the adulterers,^&#42;1^ and against those swearing falsely, and against those acting fraudulently with the wages of a wage worker, with &#91;the&#93; widow and with &#91;the&#93; fatherless boy, and those turning away the alien resident, while they have not feared me,” Jehovah of armies has said.

[NOTE]
====
. “Adulterers.” Lat., a·dulʹte·ris.
====

[[v39-3-6]]

^<<v39-3-6,6>>^ “For I am Jehovah; I have not changed. And YOU are sons of Jacob; YOU have not come to YOUR finish.

[[v39-3-7]]

^<<v39-3-7,7>>^ From the days of YOUR forefathers YOU have turned aside from my regulations and have not kept &#91;them&#93;. Return to me, and I will return to YOU,” Jehovah of armies has said.
And YOU have said: “In what way shall we return?”

[[v39-3-8]]

^<<v39-3-8,8>>^ “Will earthling man^&#42;1^ rob God?^&#42;2^ But YOU are robbing me.”
And YOU have said: “In what way have we robbed you?”
“In the tenth parts^&#42;3^ and in the contributions.

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ; Lat., hoʹmo.
. “God.” Heb., ʼElo·himʹ; Lat., Deʹum.
. “Tenth parts.” Or, “tithes.”
====

[[v39-3-9]]

^<<v39-3-9,9>>^ With the curse YOU are cursing &#91;me&#93;,^&#42;1^ and me YOU are robbing—the nation in its entirety.

[NOTE]
====
. “You are cursing [me]” was the original reading. The Sopherim changed the text to read “you are cursed,” out of respect for God. See App 2B.
====

[[v39-3-10]]

^<<v39-3-10,10>>^ Bring all the tenth parts into the storehouse, that there may come to be food in my house; and test me out, please, in this respect,” Jehovah of armies has said, “whether I shall not open to YOU people the floodgates of the heavens and actually empty out upon YOU a blessing until there is no more want.”

[[v39-3-11]]

^<<v39-3-11,11>>^ “And I will rebuke for YOU the devouring one,^&#42;1^ and it will not ruin for YOU the fruit of the ground, nor will the vine in the field prove fruitless for YOU,” Jehovah of armies has said.

[NOTE]
====
. Or, “the eater,” referring to an insect.
====

[[v39-3-12]]

^<<v39-3-12,12>>^ “And all the nations will have to pronounce YOU happy, for YOU yourselves will become a land of delight,” Jehovah of armies has said.

[[v39-3-13]]

^<<v39-3-13,13>>^ “Strong have been YOUR words against me,” Jehovah has said.
And YOU have said: “What have we spoken with one another against you?”

[[v39-3-14]]

^<<v39-3-14,14>>^ “YOU have said, ‘It is of no value to serve God. And what profit is there in that we have kept the obligation to him, and that we have walked dejectedly on account of Jehovah of armies?

[[v39-3-15]]

^<<v39-3-15,15>>^ And at present we are pronouncing presumptuous people happy. Also, the doers of wickedness have been built up. Also, they have tested God^&#42;1^ out and keep getting away.’”

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Lat., Deʹum.
====

[[v39-3-16]]

^<<v39-3-16,16>>^ At that time those in fear of Jehovah spoke with one another, each one with his companion, and Jehovah kept paying attention and listening. And a book of remembrance^&#42;1^ began to be written up before him for those in fear of Jehovah and for those thinking upon his name.

[NOTE]
====
. Or, “record.”
====

[[v39-3-17]]

^<<v39-3-17,17>>^ “And they will certainly become mine,” Jehovah of armies has said, “at the day when I am producing a special property. And I will show compassion upon them, just as a man^&#42;1^ shows compassion upon his son who is serving him.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v39-3-18]]

^<<v39-3-18,18>>^ And YOU people will again certainly see^&#42;1^ &#91;the distinction&#93; between a righteous one and a wicked one, between one serving God and one who has not served him.”

[NOTE]
====
. Lit., “will certainly return and see.”
====

'''

xref:039-malachi/039-malachi-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malachi/039-malachi-004.adoc#v39-4-0[Próximo Capítulo &#62;]