include::./index.adoc[]

[[v39-1-0]]
=== Malachi, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v39-1-1]]

^<<v39-1-1,1>>^ A pronouncement:
The word of Jehovah concerning Israel by means of Malʹa·chi:^&#42;1^

[NOTE]
====
. “Malachi,” MTSyVg; LXX, “his messenger (angel).”
====

[[v39-1-2]]

^<<v39-1-2,2>>^ “I have loved YOU people,” Jehovah has said.
And YOU have said: “In what way have you loved us?”
“Was not Eʹsau the brother of Jacob?” is the utterance of Jehovah. “But I loved Jacob,

[[v39-1-3]]

^<<v39-1-3,3>>^ and Eʹsau I have hated; and I finally made his mountains a desolated waste and his inheritance for the jackals of &#91;the&#93; wilderness.”

[[v39-1-4]]

^<<v39-1-4,4>>^ “Because Eʹdom^&#42;1^ keeps saying, ‘We have been shattered, but we shall return and build &#91;the&#93; devastated places,’ this is what Jehovah of armies^&#42;2^ has said, ‘They, for their part, will build; but I, for my part, shall tear down. And people will certainly call them “the territory^&#42;3^ of wickedness” and “the people whom Jehovah has denounced to time indefinite.”

[NOTE]
====
. Meaning “Red; Ruddy.” A secondary name given to Esau, according to Ge 25:30; Ge 36:1.
. “Jehovah of armies.” Heb., Yehwahʹ tseva·ʼohthʹ. This expression occurs 24 times in Mal. See App 1J.
. Or, “boundary; border.”
====

[[v39-1-5]]

^<<v39-1-5,5>>^ And YOUR own eyes will see &#91;it&#93;, and YOU yourselves will say: “May Jehovah be magnified over the territory of Israel.”’”

[[v39-1-6]]

^<<v39-1-6,6>>^ “‘A son, for his part, honors a father; and a servant, his grand master.^&#42;1^ So if I am a father, where is the honor to me? And if I am a grand master, where is the fear of me?’ Jehovah of armies has said to YOU, O priests who are despising my name.
“‘And YOU have said: “In what way have we despised your name?”’

[NOTE]
====
. “His grand master.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, evidently to denote excellence.
====

[[v39-1-7]]

^<<v39-1-7,7>>^ “‘&#91;By&#93; presenting upon my altar polluted bread.’
“‘And YOU have said: “In what way have we polluted you?”’
“‘By YOUR saying: “The table of Jehovah is something to be despised.”

[[v39-1-8]]

^<<v39-1-8,8>>^ And when YOU present a blind &#91;animal&#93; for sacrificing: “It is nothing bad.” And when YOU present a lame &#91;animal&#93; or a sick one: “It is nothing bad.”’”
“Bring it near, please, to your governor. Will he find pleasure in you, or will he receive you kindly?” Jehovah of armies has said.

[[v39-1-9]]

^<<v39-1-9,9>>^ “And now, please, soften the face of God,^&#42;1^ that he may show us favor. From YOUR hand this has occurred. Will he receive any of YOU men kindly?” Jehovah of armies has said.

[NOTE]
====
. Or, “the Divine One.” Heb., ʼEl; Gr., The·ouʹ; Lat., Deʹi; Sy, “Jehovah.”
====

[[v39-1-10]]

^<<v39-1-10,10>>^ “Who also is there among YOU that will shut the doors? And YOU men will not light my altar—for nothing. No delight do I have in YOU,” Jehovah of armies has said, “and in the gift offering from YOUR hand I take no pleasure.”

[[v39-1-11]]

^<<v39-1-11,11>>^ “For from the sun’s rising even to its setting my name will be great among the nations, and in every place sacrificial smoke will be made, a presentation will be made to my name, even a clean gift; because my name will be great among the nations,” Jehovah of armies has said.

[[v39-1-12]]

^<<v39-1-12,12>>^ “But YOU men are profaning me^&#42;1^ by YOUR saying, ‘The table of Jehovah^&#42;2^ is something polluted, and its fruit is something to be despised, its food.’

[NOTE]
====
. “Me” was the original reading. The Sopherim changed the text to read “him,” or, “it.” TLXXSyVg, “it.” See App 2B.
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v39-1-13]]

^<<v39-1-13,13>>^ And YOU have said, ‘Look! What a weariness!’ and YOU have caused a sniffing at it,”^&#42;1^ Jehovah of armies has said. “And YOU have brought something torn away, and the lame one, and the sick one; yes, YOU have brought &#91;it&#93; as a gift. Can I take pleasure in it at YOUR hand?” Jehovah has said.

[NOTE]
====
. “At it,” as corrected to read by the Sopherim, instead of “at me.” One of the Eighteen Emendations of the Sopherim. See App 2B.
====

[[v39-1-14]]

^<<v39-1-14,14>>^ “And cursed is the one acting cunningly when there exists in his drove a male animal, and he is making a vow and sacrificing a ruined one to Jehovah.^&#42;1^ For I am a great King,” Jehovah of armies has said, “and my name will be fear-inspiring among the nations.”

[NOTE]
====
. See vs 12 ftn, “Jehovah.”
====

'''

xref:038-zechariah/038-zechariah-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malachi/039-malachi-002.adoc#v39-2-0[Próximo Capítulo &#62;]