include::./index.adoc[]

[[v39-2-0]]
=== Malachi, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v39-2-1]]

^<<v39-2-1,1>>^ “And now this commandment is to YOU, O priests.

[[v39-2-2]]

^<<v39-2-2,2>>^ If YOU will not listen, and if YOU will not lay &#91;it&#93; to heart to give glory to my name,” Jehovah of armies has said, “I shall also certainly send upon YOU the curse, and I will curse YOUR blessings. Yes, I have even cursed the &#91;blessing&#93;,^&#42;1^ because YOU are not laying &#91;it&#93; to heart.”

[NOTE]
====
. Lit., “it,” fem., referring to the blessing, fem.
====

[[v39-2-3]]

^<<v39-2-3,3>>^ “Look! I am rebuking on YOUR account the &#91;sown&#93; seed, and I will scatter dung^&#42;1^ upon YOUR faces, the dung of YOUR festivals; and someone will actually carry YOU away to it.

[NOTE]
====
. Or, “fecal matter.” Possibly, “the contents of the stomach.”
====

[[v39-2-4]]

^<<v39-2-4,4>>^ And YOU will have to know that I have sent to YOU this commandment, in order that my covenant with Leʹvi^&#42;1^ may continue,” Jehovah of armies has said.

[NOTE]
====
. “Levi,” MTSyVg; LXX, “the Levites.”
====

[[v39-2-5]]

^<<v39-2-5,5>>^ “As for my covenant, it proved to be with him, &#91;one&#93; of life and of peace, and I kept giving them to him, with fear. And he continued fearing me; yes, because of my name he himself was struck with terror.

[[v39-2-6]]

^<<v39-2-6,6>>^ The very law of truth^&#42;1^ proved to be in his mouth, and there was no unrighteousness to be found on his lips. In peace and in uprightness he walked with me, and many were those whom he turned back from error.

[NOTE]
====
. Or, “truthfulness; trueness.” Heb., ʼemethʹ; Lat., ve·ri·taʹtis.
====

[[v39-2-7]]

^<<v39-2-7,7>>^ For the lips of a priest are the ones that should keep knowledge, and &#91;the&#93; law is what people should seek from his mouth; for he is the messenger^&#42;1^ of Jehovah of armies.

[NOTE]
====
. “Messenger.” Heb., mal·ʼakhʹ; Gr., agʹge·los; Lat., anʹge·lus.
====

[[v39-2-8]]

^<<v39-2-8,8>>^ “But YOU men—YOU have turned aside from the way. YOU have caused many to stumble in the law. YOU have ruined the covenant of Leʹvi,” Jehovah of armies has said.

[[v39-2-9]]

^<<v39-2-9,9>>^ “And I also, for my part, shall certainly make YOU to be despised and low to all the people, according as YOU were not keeping my ways, but were showing partiality in the law.”

[[v39-2-10]]

^<<v39-2-10,10>>^ “Is it not one father that all of us have? Is it not one God^&#42;1^ that has created us? Why is it that we deal treacherously with one another, in profaning the covenant of our forefathers?

[NOTE]
====
. “God.” Heb., ʼEl; Gr., The·osʹ; Lat., Deʹus.
====

[[v39-2-11]]

^<<v39-2-11,11>>^ Judah has dealt treacherously, and a detestable thing has been committed in Israel and in Jerusalem; for Judah has profaned the holiness of Jehovah, which He has loved, and he has taken possession of the daughter of a foreign god^&#42;1^ as a bride.

[NOTE]
====
. “God.” Heb., ʼel; Gr., the·ousʹ, “gods”; Lat., deʹi.
====

[[v39-2-12]]

^<<v39-2-12,12>>^ Jehovah will cut off each one that does it, one who is awake and one who is answering, from the tents of Jacob, and one who is presenting a gift offering to Jehovah of armies.”

[[v39-2-13]]

^<<v39-2-13,13>>^ “And this is the second thing that YOU people do, &#91;this resulting in&#93; covering with tears the altar of Jehovah, with weeping and sighing, so that there is no more a turning toward the gift offering or a taking of pleasure &#91;in anything&#93; from YOUR hand.

[[v39-2-14]]

^<<v39-2-14,14>>^ And YOU have said, ‘On what account?’ On this account, that Jehovah himself has borne witness between you and the wife of your youth, with whom you yourself have dealt treacherously, although she is your partner and the wife of your covenant.

[[v39-2-15]]

^<<v39-2-15,15>>^ And there was one who did not do &#91;it&#93;, as he had what was remaining^&#42;1^ of &#91;the&#93; spirit. And what was that one seeking? The seed of God.^&#42;2^ And YOU people must guard yourselves respecting YOUR spirit, and with the wife of your youth may no one deal treacherously.

[NOTE]
====
. Lit., “as . . . the remnant (remainder).” Heb., u·sheʼarʹ.
. “God.” Heb., ʼElo·himʹ; Gr., ho The·osʹ; Lat., Deʹi.
====

[[v39-2-16]]

^<<v39-2-16,16>>^ For he has hated a divorcing,”^&#42;1^ Jehovah the God of Israel has said; “and the one who with violence has covered over his garment,” Jehovah of armies has said. “And YOU must guard yourselves respecting YOUR spirit, and YOU must not deal treacherously.

[NOTE]
====
. Lit., “a sending away.” Lat., di·mitʹte. See Mt 1:19 ftn.
====

[[v39-2-17]]

^<<v39-2-17,17>>^ “YOU people have made Jehovah weary by YOUR words, and YOU have said, ‘In what way have we made &#91;him&#93; weary?’ By YOUR saying, ‘Everyone that is doing bad is good in the eyes of Jehovah, and in such ones he himself has taken delight’; or, ‘Where is the God^&#42;1^ of justice?’”

[NOTE]
====
. “God of.” Heb., ʼElo·hehʹ; Lat., Deʹus.
====

'''

xref:039-malachi/039-malachi-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malachi/039-malachi-003.adoc#v39-3-0[Próximo Capítulo &#62;]