include::./index.adoc[]

[[v36-3-0]]
=== Zephaniah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v36-3-1]]

^<<v36-3-1,1>>^ Woe to her that is rebelling^&#42;1^ and polluting herself, the oppressive city!

[NOTE]
====
. Or, “that is dirty.”
====

[[v36-3-2]]

^<<v36-3-2,2>>^ She did not listen to a voice; she did not accept discipline. In Jehovah she did not trust. To her God^&#42;1^ she did not draw near.

[NOTE]
====
. “Her God.” Heb., ʼElo·heyʹha; Gr., The·onʹ.
====

[[v36-3-3]]

^<<v36-3-3,3>>^ Her princes in the midst of her were roaring lions. Her judges were evening wolves that did not gnaw &#91;bones&#93; till the morning.

[[v36-3-4]]

^<<v36-3-4,4>>^ Her prophets were insolent, were men of treachery. Her priests themselves profaned what was holy; they did violence to &#91;the&#93; law.

[[v36-3-5]]

^<<v36-3-5,5>>^ Jehovah was righteous in the midst of her; he would do no unrighteousness. Morning by morning he kept giving his own judicial decision. At daylight it did not prove lacking. But the unrighteous one was knowing no shame.

[[v36-3-6]]

^<<v36-3-6,6>>^ “I cut off nations; their corner towers were desolated. I devastated their streets, so that there was no one passing through. Their cities were laid waste, so that there was no man,^&#42;1^ so that there was no inhabitant.

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v36-3-7]]

^<<v36-3-7,7>>^ I said, ‘Surely you will fear me; you will accept discipline’; so that her dwelling might not be cut off—all that I must call to account against her. Truly they acted promptly in making all their dealings ruinous.

[[v36-3-8]]

^<<v36-3-8,8>>^ “‘Therefore keep yourselves in expectation of me,’ is the utterance of Jehovah, ‘till the day of my rising up^&#42;1^ to &#91;the&#93; booty,^&#42;2^ for my judicial decision is to gather nations, for me to collect together kingdoms, in order to pour out upon them my denunciation, all my burning anger; for by the fire of my zeal all the earth^&#42;3^ will be devoured.

[NOTE]
====
. “My rising up.” Heb., qu·miʹ; LXX(Gr., a·na·staʹse·osʹ mou)Vg(Lat., re·sur·rec·ti·oʹnis meʹae), “my resurrection.” See Mt 22:23 ftn.
. “To [the] booty.” Heb., leʽadhʹ; LXXSy and by a different vowel pointing, “to a witness (testimony)”; Lat., in fu·tuʹrum, “in the future.”
. Or, “the land.” Heb., ha·ʼaʹrets.
====

[[v36-3-9]]

^<<v36-3-9,9>>^ For then I shall give to peoples the change to a pure language,^&#42;1^ in order for them all to call upon the name of Jehovah, in order to serve him shoulder to shoulder.’^&#42;2^

[NOTE]
====
. Lit., “a clean lip.” Heb., sa·phahʹ veru·rahʹ. See Ge 11:1.
. Lit., “[with] one shoulder.”
====

[[v36-3-10]]

^<<v36-3-10,10>>^ “From the region of the rivers of E·thi·oʹpi·a^&#42;1^ the ones entreating me, &#91;namely,&#93; the daughter of my scattered ones, will bring a gift to me.

[NOTE]
====
. “Ethiopia,” LXXVg; M(Heb., Khush)Sy, “Cush”; T(Aram.), Hohʹdhu, “India.”
====

[[v36-3-11]]

^<<v36-3-11,11>>^ In that day you^&#42;1^ will not be ashamed because of all your dealings with which you transgressed against me, for then I shall remove from the midst of you your haughtily exultant ones; and you will never again be haughty in my holy mountain.

[NOTE]
====
. “You,” fem. sing., referring to the city.
====

[[v36-3-12]]

^<<v36-3-12,12>>^ And I shall certainly let remain in the midst of you a people humble and lowly, and they will actually take refuge in the name of Jehovah.

[[v36-3-13]]

^<<v36-3-13,13>>^ As regards the remaining ones of Israel, they will do no unrighteousness, nor speak a lie, nor will there be found in their mouths a tricky tongue; for they themselves will feed and actually lie stretched out, and there will be no one making &#91;them&#93; tremble.”

[[v36-3-14]]

^<<v36-3-14,14>>^ Joyfully cry out, O daughter of Zion! Break out in cheers, O Israel! Rejoice and exult with all the heart, O daughter of Jerusalem!

[[v36-3-15]]

^<<v36-3-15,15>>^ Jehovah has removed the judgments upon you. He has turned away your enemy. The king of Israel, Jehovah, is in the midst of you. You will fear calamity no more.

[[v36-3-16]]

^<<v36-3-16,16>>^ In that day it will be said to Jerusalem: “Do not be afraid, O Zion. May your hands not drop down.

[[v36-3-17]]

^<<v36-3-17,17>>^ Jehovah your God^&#42;1^ is in the midst of you. As a mighty One,^&#42;2^ he will save. He will exult over you with rejoicing. He will become silent in his love. He will be joyful over you with happy cries.

[NOTE]
====
. “Your God.” Heb., ʼElo·haʹyikh; Gr., The·osʹ.
. “As a mighty One.” Heb., Gib·bohrʹ. Compare Isa 10:21 ftn, “God.”
====

[[v36-3-18]]

^<<v36-3-18,18>>^ “The ones grief-stricken in absence from &#91;your&#93; festal season I shall certainly gather together; absent from you^&#42;1^ they happened to be, because of bearing reproach on her account.

[NOTE]
====
. “You,” fem. sing., referring to the city of Jerusalem.
====

[[v36-3-19]]

^<<v36-3-19,19>>^ Here I am acting against all those afflicting you, at that time; and I will save her that is limping, and her that is dispersed I shall collect together. And I will set them as a praise and as a name in all the land of their shame.

[[v36-3-20]]

^<<v36-3-20,20>>^ At that time I shall bring YOU people in, even in the time of my collecting YOU together. For I shall make YOU people to be a name and a praise among all the peoples of the earth, when I gather back YOUR captive ones before YOUR eyes,” Jehovah has said.

'''

xref:036-zephaniah/036-zephaniah-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-haggai/037-haggai-001.adoc#v37-1-0[Próximo Capítulo &#62;]