include::./index.adoc[]

[[v36-2-0]]
=== Zephaniah, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v36-2-1]]

^<<v36-2-1,1>>^ Gather yourselves together, yes, do the gathering, O nation not paling in shame.^&#42;1^

[NOTE]
====
. Or, “not yearning intensely.”
====

[[v36-2-2]]

^<<v36-2-2,2>>^ Before &#91;the&#93; statute gives birth to &#91;anything&#93;, &#91;before the&#93; day has passed by just like chaff, before there comes upon YOU people the burning anger of Jehovah, before there comes upon YOU the day of Jehovah’s anger,

[[v36-2-3]]

^<<v36-2-3,3>>^ seek Jehovah, all YOU meek^&#42;1^ ones of the earth, who have practiced His own judicial decision.^&#42;2^ Seek righteousness, seek meekness.^&#42;3^ Probably^&#42;4^ YOU may be concealed^&#42;5^ in the day of Jehovah’s anger.

[NOTE]
====
. Or, “humble.”
. Or, “who have kept His judgments.”
. Or, “humbleness; humility.”
. Or, “Perhaps.” Heb., ʼu·laiʹ.
. “You may be concealed (sheltered).” Heb., tis·sa·theruʹ; not tsa·phanʹ, as in the name Zephaniah. Compare Title ftn.
====

[[v36-2-4]]

^<<v36-2-4,4>>^ For, as regards Gaʹza, an abandoned &#91;city&#93; is what she will become; and Ashʹke·lon is to be a desolate waste. As regards Ashʹdod, at high noon they will drive her out; and as regards Ekʹron, she will be uprooted.

[[v36-2-5]]

^<<v36-2-5,5>>^ “Woe to those inhabiting the region of the sea, the nation of Cherʹe·thites!^&#42;1^ The word of Jehovah is against YOU people. O Caʹnaan, the land of the Phi·lisʹtines, I will also destroy you, so that there will be no inhabitant.

[NOTE]
====
. “Cretans,” LXX.
====

[[v36-2-6]]

^<<v36-2-6,6>>^ And the region of the sea must become pasture grounds, &#91;with&#93; wells for shepherds and stone pens for sheep.

[[v36-2-7]]

^<<v36-2-7,7>>^ And it must become a region for the remaining ones of the house of Judah. Upon them they will feed. In the houses of Ashʹke·lon, in the evening, they will lie stretched out. For Jehovah their God^&#42;1^ will turn his attention to them and certainly gather back the captive ones of them.”

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v36-2-8]]

^<<v36-2-8,8>>^ “I have heard the reproach by Moʹab and the abusive words of the sons of Amʹmon, with which they have reproached my people and kept putting on great airs against their territory.

[[v36-2-9]]

^<<v36-2-9,9>>^ Therefore, as I am alive,” is the utterance of Jehovah of armies, the God of Israel, “Moʹab herself will become just like Sodʹom, and the sons of Amʹmon like Go·morʹrah, a place possessed by nettles, and a salt pit, and a desolate waste, even to time indefinite. The remaining ones of my people will plunder them, and the remnant of my own nation will take possession of them.

[[v36-2-10]]

^<<v36-2-10,10>>^ This is what they will have instead of their pride, because they reproached and kept putting on great airs against the people of Jehovah^&#42;1^ of armies.

[NOTE]
====
. See App 1C §2.
====

[[v36-2-11]]

^<<v36-2-11,11>>^ Jehovah will be fear-inspiring against them;^&#42;1^ for he will certainly emaciate all the gods of the earth,^&#42;2^ and people will bow down to him, each one from his place, all the islands^&#42;3^ of the nations.

[NOTE]
====
. According to MVg; LXXSy, “Jehovah will appear upon them.”
. “Gods of the earth,” M(Heb., ʼelo·hehʹ ha·ʼaʹrets)Vg; LXX, “gods of the nations of the earth.”
. Or, “coastlands.”
====

[[v36-2-12]]

^<<v36-2-12,12>>^ “YOU also, YOU E·thi·oʹpi·ans,^&#42;1^ YOU yourselves will be people slain by my sword.^&#42;2^

[NOTE]
====
. “Ethiopians,” LXXVg; Heb., Ku·shimʹ; TSy, “Cushites.”
. “My sword,” MTLXXVg.
====

[[v36-2-13]]

^<<v36-2-13,13>>^ “And he will stretch out his hand toward the north, and he will destroy As·syrʹi·a. And he will make Ninʹe·veh a desolate waste, a waterless region like the wilderness.

[[v36-2-14]]

^<<v36-2-14,14>>^ And in the midst of her, droves will certainly lie stretched out, all the wild animals of a nation.^&#42;1^ Both pelican and porcupine will spend the night right among her pillar capitals. A voice will keep singing in the window. There will be devastation at the threshold; for he will certainly lay bare the very wainscoting.

[NOTE]
====
. “A nation.” Heb., ghohy; LXX, “the earth”; SyVg, “nations (peoples).”
====

[[v36-2-15]]

^<<v36-2-15,15>>^ This is the exultant city that was sitting in security, that was saying in her heart, ‘I am, and there is nobody else.’ O how she has become an object of astonishment, a place for the wild animals to lie stretched out! Everyone passing along by her will whistle; he will wag his hand.”

'''

xref:036-zephaniah/036-zephaniah-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-zephaniah/036-zephaniah-003.adoc#v36-3-0[Próximo Capítulo &#62;]