include::./index.adoc[]

[[v36-1-0]]
=== Zephaniah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v36-1-1]]

^<<v36-1-1,1>>^ The word of Jehovah that occurred to Zeph·a·niʹah the son of Cushʹi the son of Ged·a·liʹah the son of Am·a·riʹah the son of Hez·e·kiʹah in the days of Jo·siʹah the son of Aʹmon the king of Judah:

[[v36-1-2]]

^<<v36-1-2,2>>^ “I shall without fail finish everything off the surface of the ground,” is the utterance of Jehovah.

[[v36-1-3]]

^<<v36-1-3,3>>^ “I shall finish off earthling man and beast. I shall finish off the flying creature of the heavens and the fishes of the sea, and the stumbling blocks with the wicked ones; and I will cut off mankind^&#42;1^ from the surface of the ground,” is the utterance of Jehovah.^&#42;2^

[NOTE]
====
. “Mankind.” Heb., ha·ʼa·dhamʹ.
. See App 1C §2.
====

[[v36-1-4]]

^<<v36-1-4,4>>^ “And I will stretch out my hand against Judah and against all the inhabitants of Jerusalem, and I will cut off from this place the remaining ones of the Baʹal,^&#42;1^ the name of the foreign-god priests^&#42;2^ along with the priests,

[NOTE]
====
. “The Baal.” Heb., hab·Baʹʽal, the name of the false god; Gr. and Lat., Baʹal.
. “The foreign-god priests.” Heb., hak·kema·rimʹ; Vg, “temple keepers.”
====

[[v36-1-5]]

^<<v36-1-5,5>>^ and those who are bowing down upon the roofs to the army of the heavens, and those who are bowing down, making sworn oaths to Jehovah and making sworn oaths by Malʹcam;^&#42;1^

[NOTE]
====
. “By Malcam.” Heb., beMal·kamʹ; Syr., beMal·kum; Vg, “by Melchom”; LXX, “by their king.”
====

[[v36-1-6]]

^<<v36-1-6,6>>^ and those who are drawing back from following Jehovah and who have not sought Jehovah and have not inquired of him.”

[[v36-1-7]]

^<<v36-1-7,7>>^ Keep silence before the Sovereign Lord Jehovah; for the day of Jehovah is near, for Jehovah has prepared a sacrifice; he has sanctified his invited ones.

[[v36-1-8]]

^<<v36-1-8,8>>^ “And it must occur on the day of Jehovah’s sacrifice that I will give attention to the princes, and to the sons of the king, and to all those wearing foreign attire.

[[v36-1-9]]

^<<v36-1-9,9>>^ And I will give attention to everyone that is climbing upon the platform^&#42;1^ in that day, those who are filling the house of their masters^&#42;2^ with violence and deception.

[NOTE]
====
. Or, “podium”; or, “threshold.” Possibly, the platform, or dais, of the king’s throne.
. Or, “their grand master.” Heb., ʼadho·neh·hemʹ, pl. of ʼa·dhohnʹ. See Ge 39:2 ftn.
====

[[v36-1-10]]

^<<v36-1-10,10>>^ And there must occur on that day,” is the utterance of Jehovah, “the sound of an outcry from the Fish Gate, and a howling from the second quarter, and a great crashing from the hills.

[[v36-1-11]]

^<<v36-1-11,11>>^ Howl, YOU inhabitants of Makʹtesh,^&#42;1^ for all the people who are tradesmen have been silenced; all those weighing out silver have been cut off.

[NOTE]
====
. Lit., “the Mortar.” Heb., ham·Makh·teshʹ. Apparently a section of Jerusalem in the upper portion of the Central (or, Tyropoeon) Valley near the Fish Gate and the second quarter.
====

[[v36-1-12]]

^<<v36-1-12,12>>^ “And it must occur at that time that I shall carefully search Jerusalem with lamps, and I will give attention to the men^&#42;1^ who are congealing upon their dregs &#91;and&#93; who are saying in their heart, ‘Jehovah will not do good, and he will not do bad.’

[NOTE]
====
. “The men.” Heb., ha·ʼana·shimʹ, pl. of ʼish.
====

[[v36-1-13]]

^<<v36-1-13,13>>^ And their wealth must come to be for pillage and their houses for a desolate waste. And they will build houses, but they will not have occupancy; and they will plant vineyards, but they will not drink the wine of them.

[[v36-1-14]]

^<<v36-1-14,14>>^ “The great day of Jehovah^&#42;1^ is near. It is near, and there is a hurrying &#91;of it&#93; very much. The sound of the day of Jehovah is bitter. There a mighty man^&#42;2^ is letting out a cry.

[NOTE]
====
. See App 1C §2.
. “A mighty man.” Heb., gib·bohrʹ. Compare Ge 10:8 ftn.
====

[[v36-1-15]]

^<<v36-1-15,15>>^ That day is a day of fury, a day of distress and of anguish, a day of storm and of desolation, a day of darkness and of gloominess, a day of clouds and of thick gloom,

[[v36-1-16]]

^<<v36-1-16,16>>^ a day of horn^&#42;1^ and of alarm signal, against the fortified cities and against the high corner towers.

[NOTE]
====
. Or, “shofar.” Heb., shoh·pharʹ.
====

[[v36-1-17]]

^<<v36-1-17,17>>^ And I will cause distress to mankind,^&#42;1^ and they will certainly walk like blind men; because it is against Jehovah that they have sinned. And their blood will actually be poured out like dust, and their bowels like the dung.

[NOTE]
====
. Or, “to earthling men.” Heb., la·ʼa·dhamʹ.
====

[[v36-1-18]]

^<<v36-1-18,18>>^ Neither their silver nor their gold will be able to deliver them in the day of Jehovah’s fury; but by the fire of his zeal the whole earth^&#42;1^ will be devoured, because he will make an extermination, indeed a terrible one,^&#42;2^ of all the inhabitants of the earth.”

[NOTE]
====
. Or, “all the land.” Heb., kol-ha·ʼaʹrets.
. Or, “indeed a sudden terror,” by a correction.
====

'''

xref:035-habakkuk/035-habakkuk-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-zephaniah/036-zephaniah-002.adoc#v36-2-0[Próximo Capítulo &#62;]