include::./index.adoc[]

[[v26-26-0]]
=== Ezekiel, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-26-1]]

^<<v26-26-1,1>>^ And it came about in the eleventh year, on the first &#91;day&#93; of the month, that the word of Jehovah occurred to me, saying:

[[v26-26-2]]

^<<v26-26-2,2>>^ “Son of man, for the reason that Tyre has said against Jerusalem, ‘Aha! She has been broken, the doors^&#42;1^ of the peoples! The trend will certainly be to me. I shall be filled—she has been devastated,’

[NOTE]
====
. Or, “leaves of a door,” M; T, “tradeswoman.”
====

[[v26-26-3]]

^<<v26-26-3,3>>^ therefore this is what the Sovereign Lord Jehovah has said, ‘Here I am against you, O Tyre, and I will bring up against you many nations, just as the sea brings up its waves.

[[v26-26-4]]

^<<v26-26-4,4>>^ And they will certainly bring the walls of Tyre to ruin and tear down her towers, and I will scrape her dust away from her and make her a shining, bare surface of a crag.

[[v26-26-5]]

^<<v26-26-5,5>>^ A drying yard for dragnets is what she will become in the midst of the sea.’
“‘For I myself have spoken,’ is the utterance of the Sovereign Lord Jehovah, ‘and she must become an object of plunder for the nations.

[[v26-26-6]]

^<<v26-26-6,6>>^ And her dependent towns^&#42;1^ that are in the field—by the sword they will be killed, and people^&#42;2^ will have to know that I am Jehovah.’

[NOTE]
====
. See 16:46 ftn.
. Lit., “they,” masc.
====

[[v26-26-7]]

^<<v26-26-7,7>>^ “For this is what the Sovereign Lord Jehovah has said, ‘Here I am bringing against Tyre Neb·u·chad·rezʹzar the king of Babylon^&#42;1^ from the north, a king of kings, with horses and war chariots and cavalrymen and a congregation, even a multitudinous people.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v26-26-8]]

^<<v26-26-8,8>>^ Your^&#42;1^ dependent towns in the field he will kill even with the sword, and he must make against you a siege wall and throw up against you a siege rampart and raise up against you a large shield;

[NOTE]
====
. “Your,” fem. sing., referring to “Tyre.”
====

[[v26-26-9]]

^<<v26-26-9,9>>^ and the strike of his attack engine he will direct against your walls, and your towers he will pull down, with his swords.

[[v26-26-10]]

^<<v26-26-10,10>>^ Owing to the heaving mass of his horses their dust will cover you. Owing to the sound of cavalryman and wheel and war chariot your walls will rock, when he comes in through your gates, as in the cases of entering into a city opened by breaches.

[[v26-26-11]]

^<<v26-26-11,11>>^ With the hoofs of his horses he will trample down all your streets. Your people he will kill even with the sword, and to the earth your own pillars of strength will go down.^&#42;1^

[NOTE]
====
. “Will go down,” MVg; TLXXSy, “he will bring down.”
====

[[v26-26-12]]

^<<v26-26-12,12>>^ And they will certainly spoil your resources and plunder your sales goods, and tear down your walls, and your desirable houses they will pull down. And your stones and your woodwork and your dust they will place in the very midst of the water.’

[[v26-26-13]]

^<<v26-26-13,13>>^ “‘And I will cause the turmoil of your singing to cease, and the very sound of your harps will be heard no more.

[[v26-26-14]]

^<<v26-26-14,14>>^ And I will make you a shining, bare surface of a crag. A drying yard for dragnets is what you will become. Never will you be rebuilt; for I myself, Jehovah, have spoken,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-26-15]]

^<<v26-26-15,15>>^ “This is what the Sovereign Lord Jehovah has said to Tyre, ‘At the sound of your downfall, when the fatally wounded one groans, when there is a killing with slaughter in the midst of you, will not the islands^&#42;1^ rock?

[NOTE]
====
. Or, “coastlands.”
====

[[v26-26-16]]

^<<v26-26-16,16>>^ And down from their thrones all the chieftains of the sea will certainly come and remove their sleeveless coats, and they will strip off their own embroidered garments. They will put on trembling spells. Upon the earth they will sit down, and they will certainly tremble every moment and stare in amazement at you.

[[v26-26-17]]

^<<v26-26-17,17>>^ And they must raise up over you a dirge and say to you:
“‘“How you have perished, that used to be inhabited from the seas,^&#42;1^ O praised city, who became a strong one in the sea, she and those inhabiting her, those who gave their terror to all the inhabitants &#91;of the earth&#93;!^&#42;2^

[NOTE]
====
. According to M; Sy, “O inhabitress of the seas”; Vg, “you who dwell in the sea.”
. Lit., “of her,” or, “of it,” fem.
====

[[v26-26-18]]

^<<v26-26-18,18>>^ Now the islands will tremble in the day of your downfall. And the islands that are in the sea must be disturbed owing to your going out.”’

[[v26-26-19]]

^<<v26-26-19,19>>^ “For this is what the Sovereign Lord Jehovah has said, ‘When I make you a devastated city, like the cities that are actually not inhabited, when &#91;I&#93; bring up over you the watery deep,^&#42;1^ and the vast waters will have covered you,

[NOTE]
====
. Or, “surging waters.” Heb., tehohmʹ; LXXVg, “abyss.” Compare Ge 1:2 ftn, “Deep.”
====

[[v26-26-20]]

^<<v26-26-20,20>>^ I will also bring you down with those going down into the pit to the people of long ago, and I will cause you to dwell in the lowest land, like places devastated for a long time, with those going down into the pit, in order that you may not be inhabited; and I will put decoration in the land of those alive.

[[v26-26-21]]

^<<v26-26-21,21>>^ “‘Sudden terrors are what I shall make you, and you will not be; and you will be sought for, but you will no more be found to time indefinite,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezekiel/026-ezekiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]