include::./index.adoc[]

[[v26-32-0]]
=== Ezekiel, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-32-1]]

^<<v26-32-1,1>>^ And it occurred further that in the twelfth year, in the twelfth month, on the first &#91;day&#93; of the month, the word of Jehovah occurred to me, saying:

[[v26-32-2]]

^<<v26-32-2,2>>^ “Son of man, lift up a dirge concerning Pharʹaoh the king of Egypt, and you must say to him, ‘As a maned young lion of nations you have been silenced.
“‘And you have been like the marine monster in the seas, and you kept gushing in your rivers^&#42;1^ and kept muddying the waters with your feet and fouling their rivers.’

[NOTE]
====
. Possibly, “during your snortings”; or, “through your nostrils,” by a slight correction.
====

[[v26-32-3]]

^<<v26-32-3,3>>^ “This is what the Sovereign Lord Jehovah has said, ‘I will also spread over you my net by means of a congregation of many peoples, and they^&#42;1^ will certainly bring you in my dragnet.

[NOTE]
====
. “They,” MSyVg; LXXVgc, “I.”
====

[[v26-32-4]]

^<<v26-32-4,4>>^ And I must abandon you on the land. Upon the surface of the field I shall hurl you. And on you I will cause all the flying creatures of the heavens to reside, and off you I will satisfy the wild beasts of the whole earth.

[[v26-32-5]]

^<<v26-32-5,5>>^ And I will put your flesh upon the mountains and fill the valleys with the refuse^&#42;1^ of you.

[NOTE]
====
. “Refuse,” M; LXX, “blood”; Sy, “maggots”; Vg, “corrupted blood.”
====

[[v26-32-6]]

^<<v26-32-6,6>>^ And I will cause &#91;the&#93; land to drink up your discharged matter, from your blood, upon the mountains; and streambeds themselves will be filled up from you.’

[[v26-32-7]]

^<<v26-32-7,7>>^ “‘And when you get extinguished I will cover &#91;the&#93; heavens and darken their stars. As for &#91;the&#93; sun, with clouds I shall cover it, and &#91;the&#93; moon itself will not let its light shine.

[[v26-32-8]]

^<<v26-32-8,8>>^ All the luminaries of light in the heavens—I shall darken them on your account, and I will put darkness upon your land,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-32-9]]

^<<v26-32-9,9>>^ “‘And I will offend the heart of many peoples when I bring the captives^&#42;1^ from you among the nations to lands that you have not known.

[NOTE]
====
. “Body of captives,” LXX; MSy, “breakdown [or, broken parts].”
====

[[v26-32-10]]

^<<v26-32-10,10>>^ And at you I shall certainly cause many peoples to be awestruck, and their kings themselves will shudder in horror at you when I brandish my sword in their faces, and they will have to tremble every moment, each one for his own soul, on the day of your downfall.’

[[v26-32-11]]

^<<v26-32-11,11>>^ “For this is what the Sovereign Lord Jehovah has said, ‘The very sword of the king of Babylon will come upon you.

[[v26-32-12]]

^<<v26-32-12,12>>^ I shall cause your crowd to fall by the very swords of mighty ones, the tyrants of &#91;the&#93; nations, all of them; and they will actually despoil the pride of Egypt, and all her crowd must be annihilated.

[[v26-32-13]]

^<<v26-32-13,13>>^ And I will destroy all her domestic animals from beside many waters, and the foot of earthling man will no more muddy them, nor will even the hoofs of a domestic animal muddy them.’

[[v26-32-14]]

^<<v26-32-14,14>>^ “‘At that time I shall make their waters clear up, and their rivers I shall make go just like oil,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-32-15]]

^<<v26-32-15,15>>^ “‘When I make the land of Egypt a desolate waste and the land is desolated of its fullness, when I strike down all the inhabitants in it, they will also have to know that I am Jehovah.

[[v26-32-16]]

^<<v26-32-16,16>>^ “‘This is a dirge, and people will certainly chant it. Even the daughters of the nations will chant it; over Egypt and over all its crowd they will chant it,’ is the utterance of the Sovereign Lord Jehovah.”

[[v26-32-17]]

^<<v26-32-17,17>>^ And it occurred further that in the twelfth year,^&#42;1^ on the fifteenth &#91;day&#93; of the month, the word of Jehovah occurred to me, saying:

[NOTE]
====
. LXX adds, “in the first month”; MTSyVg omit.
====

[[v26-32-18]]

^<<v26-32-18,18>>^ “Son of man, lament over the crowd of Egypt and bring it down, her and the daughters of majestic nations, to the land down below, with those going down into &#91;the&#93; pit.

[[v26-32-19]]

^<<v26-32-19,19>>^ “‘Compared with whom are you more pleasant? Do go down, and you must be laid with the uncircumcised ones!’

[[v26-32-20]]

^<<v26-32-20,20>>^ “‘In the midst of those slain by the sword they will fall. &#91;To&#93; a sword she has been given. Drag her away and all her crowds, YOU men.

[[v26-32-21]]

^<<v26-32-21,21>>^ “‘The foremost men of the mighty ones will speak out of the midst of Sheʹol even to him, with his helpers. They will certainly go down; they must lie down as the uncircumcised, slain by the sword.

[[v26-32-22]]

^<<v26-32-22,22>>^ There is where As·syrʹi·a and all her congregation are. His burial places are round about him. All of them are slain, those falling by the sword.

[[v26-32-23]]

^<<v26-32-23,23>>^ For her burial places have been put in the innermost parts of a pit, and her congregation proves to be round about her grave, all of them slain, falling by the sword, because they had caused terror in the land of those alive.

[[v26-32-24]]

^<<v26-32-24,24>>^ “‘There are Eʹlam and all her crowd round about her grave, all of them slain ones, those falling by the sword, who have gone down uncircumcised to the land down below, those who have caused their terror in the land of those alive; and they will bear their humiliation with those going down into &#91;the&#93; pit.

[[v26-32-25]]

^<<v26-32-25,25>>^ In the midst of slain ones they have set a bed for her among all her crowd. Her burial places are round about it. All of them are uncircumcised, slain by the sword, because their terror was caused in the land of those alive; and they will bear their humiliation with those going down into &#91;the&#93; pit. In the midst of slain ones he^&#42;1^ has been put.

[NOTE]
====
. Or, “it,” M; TSyVg, “they.”
====

[[v26-32-26]]

^<<v26-32-26,26>>^ “‘There is where Meʹshech &#91;and&#93; Tuʹbal and all her crowd are. Her burial places are round about him. All of them are uncircumcised, pierced through by the sword, because they have caused their terror in the land of those alive.

[[v26-32-27]]

^<<v26-32-27,27>>^ And will they not^&#42;1^ lie down with mighty ones, falling from among the uncircumcised, who have gone down to Sheʹol with their weapons of war? And they will put their swords under their heads, and their errors will come to be upon their bones, because mighty ones were a terror in the land of those alive.

[NOTE]
====
. Or, “And they will not.”
====

[[v26-32-28]]

^<<v26-32-28,28>>^ And as for you,^&#42;1^ in the midst of uncircumcised ones you will be broken, and you will lie down with those slain by the sword.

[NOTE]
====
. “You,” masc. sing.
====

[[v26-32-29]]

^<<v26-32-29,29>>^ “‘There is where Eʹdom, her kings and all her chieftains are, who, in their mightiness, were put with those slain by the sword; they themselves will lie down even with the uncircumcised ones and with those going down into &#91;the&#93; pit.

[[v26-32-30]]

^<<v26-32-30,30>>^ “‘There is where the dukes of the north are, all of them, and all the Si·doʹni·ans, who have gone down with the slain ones, in their terribleness because of their mightiness, ashamed. And they will lie down uncircumcised with those slain by the sword and will bear their humiliation with those going down into &#91;the&#93; pit.

[[v26-32-31]]

^<<v26-32-31,31>>^ “‘These are the ones that Pharʹaoh will see, and he will certainly be comforted over all his crowd. Pharʹaoh and all his military force will be people slain by the sword,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-32-32]]

^<<v26-32-32,32>>^ “‘For he has^&#42;1^ caused his terror^&#42;2^ in the land of those alive, and he must be laid in the midst of the uncircumcised ones, with those slain by the sword, even Pharʹaoh and all his crowd,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. “He has,” by a slight correction in agreement with “his”; MLXXSyVg, “I have.”
. “His terror,” MLXXSy; MmarginVg, “my terror.”
====

'''

xref:026-ezekiel/026-ezekiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezekiel/026-ezekiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]