include::./index.adoc[]

[[v26-28-0]]
=== Ezekiel, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-28-1]]

^<<v26-28-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-28-2]]

^<<v26-28-2,2>>^ “Son of man, say to the leader of Tyre, ‘This is what the Sovereign Lord Jehovah has said:
“‘“For the reason that your heart has become haughty, and you keep saying, ‘I am a god.^&#42;1^ In the seat of god^&#42;2^ I have seated myself, in the heart of the open sea,’ whereas an earthling man^&#42;3^ is what you are, and not a god, and you keep making your heart like the heart of god—

[NOTE]
====
. “A god (divine one).” Heb., ʼel; Gr., the·osʹ; Lat., deʹus.
. “God.” Heb., ʼelo·himʹ; Lat., deʹi.
. Or, “a human.” Heb., ʼa·dhamʹ; Gr., anʹthro·pos; Lat., hoʹmo.
====

[[v26-28-3]]

^<<v26-28-3,3>>^ look! you are wiser than Daniel. There are no secrets that have proved a match for you.

[[v26-28-4]]

^<<v26-28-4,4>>^ By your wisdom and by your discernment you have made wealth for your own self, and you keep getting gold and silver in your storehouses.

[[v26-28-5]]

^<<v26-28-5,5>>^ By the abundance of your wisdom, by your sales goods, you have made your wealth abound, and your heart began to be haughty because of your wealth.”’

[[v26-28-6]]

^<<v26-28-6,6>>^ “‘Therefore this is what the Sovereign Lord Jehovah has said: “For the reason that you make your heart like the heart of god,

[[v26-28-7]]

^<<v26-28-7,7>>^ therefore here I am bringing upon you strangers, the tyrants of &#91;the&#93; nations, and they will certainly draw their swords against the beauty of your wisdom and profane your beaming splendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Down to the pit they will bring you, and you must die the death of someone slain in the heart of the open sea.

[[v26-28-9]]

^<<v26-28-9,9>>^ Will you without fail say, ‘I am god,’ before the one killing you, whereas you are a mere earthling man, and not a god, in the hand of those profaning you?”’

[[v26-28-10]]

^<<v26-28-10,10>>^ “‘The deaths of uncircumcised ones you will die by the hand of strangers, for I myself have spoken,’ is the utterance of the Sovereign Lord Jehovah.”

[[v26-28-11]]

^<<v26-28-11,11>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-28-12]]

^<<v26-28-12,12>>^ “Son of man, lift up a dirge concerning the king of Tyre, and you must say to him, ‘This is what the Sovereign Lord Jehovah has said:
“‘“You are sealing up a pattern, full of wisdom and perfect in beauty.

[[v26-28-13]]

^<<v26-28-13,13>>^ In Eʹden, the garden^&#42;1^ of God,^&#42;2^ you proved to be. Every precious stone was your covering, ruby, topaz and jasper; chrysʹo·lite,^&#42;3^ onyx and jade; sapphire, turquoise and emerald; and of gold was the workmanship of your settings and your sockets in you. In the day of your being created they were made ready.

[NOTE]
====
. “Garden.” Heb., gan; Gr., pa·ra·deiʹsou; Syr., par·dai·seh; Lat., pa·ra·diʹsi.
. “God.” Heb., ʼElo·himʹ; Gr., The·ouʹ; Lat., Deʹi.
. “Chrysolite,” Vg; Heb., tar·shishʹ.
====

[[v26-28-14]]

^<<v26-28-14,14>>^ You are the^&#42;1^ anointed cherub^&#42;2^ that is covering, and I have set^&#42;3^ you.^&#42;4^ On the holy mountain of God^&#42;5^ you proved to be. In the midst of fiery stones^&#42;6^ you walked about.

[NOTE]
====
. “You are the,” MTVg; by a different vowel pointing, “With the,” in agreement with LXXSy and Arabic.
. Lit., “cherub of an anointing [possibly, expansion].” Heb., keruvʹ mim·shachʹ.
. Lit., “given.”
. “You are the anointed king in the kingdom, and I have given you greatness,” T; LXX, “With the cherub I set you”; Sy, “You happened to be with the anointed cherub that is covering, and I set you”; Vg, “You are the cherub stretched out and protecting, and I set you.”
. “God.” Heb., ʼElo·himʹ; Lat., Deʹi.
. Lit., “stones of fire.”
====

[[v26-28-15]]

^<<v26-28-15,15>>^ You were faultless in your ways from the day of your being created until unrighteousness was found in you.

[[v26-28-16]]

^<<v26-28-16,16>>^ “‘“Because of the abundance of your sales goods they filled the midst of you^&#42;1^ with violence, and you began to sin. And I shall put you as profane out of the mountain of God,^&#42;2^ and I shall destroy you, O cherub that is covering,^&#42;3^ from the midst of the fiery stones.^&#42;4^

[NOTE]
====
. “They filled the midst of you,” M; Sy, “you filled your own midst”; T, “your storehouses were filled”; LXX, “you filled your storehouses”; Vg, “your inner parts were filled.”
. “God.” Heb., ʼElo·himʹ; Gr., The·ouʹ; Lat., Deʹi.
. “I shall destroy you, O cherub that is covering,” MSy; Vg, “I have destroyed you, O protecting cherub”; LXX, “the cherub led you away.”
. Lit., “stones of fire.”
====

[[v26-28-17]]

^<<v26-28-17,17>>^ “‘“Your heart became haughty because of your beauty. You brought your wisdom to ruin on account of your beaming splendor. Onto the earth I will throw you. Before kings I will set you, &#91;for them&#93; to look upon you.

[[v26-28-18]]

^<<v26-28-18,18>>^ “‘“Owing to the abundance of your errors, because of the injustice of your sales goods, you have profaned^&#42;1^ your sanctuaries. And I shall bring forth a fire from the midst of you. It is what must devour you. And I shall make you ashes upon the earth before the eyes of all those seeing you.

[NOTE]
====
. “You have profaned,” MSyVg; LXXB, “I have profaned.”
====

[[v26-28-19]]

^<<v26-28-19,19>>^ As for all those knowing you among the peoples, they will certainly stare in amazement at you. Sudden terrors are what you must become, and you will be no more to time indefinite.”’”

[[v26-28-20]]

^<<v26-28-20,20>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-28-21]]

^<<v26-28-21,21>>^ “Son of man, set your face toward Siʹdon, and prophesy against her.

[[v26-28-22]]

^<<v26-28-22,22>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said: “Here I am against you, O Siʹdon, and I shall certainly be glorified in the midst of you; and people will have to know that I am Jehovah when I execute acts of judgment in her and I am actually sanctified in her.

[[v26-28-23]]

^<<v26-28-23,23>>^ And I will send pestilence into her and blood into her streets. And the slain one must fall in the midst of her by the sword against her on every side; and people will have to know that I am Jehovah.

[[v26-28-24]]

^<<v26-28-24,24>>^ And no more will there prove to be to the house of Israel a malignant prickle or a painful thorn out of all those round about them, those who are treating them with scorn; and people will have to know that I am the Sovereign Lord Jehovah.”’

[[v26-28-25]]

^<<v26-28-25,25>>^ “‘This is what the Sovereign Lord Jehovah has said: “When I collect together the house of Israel out from the peoples among whom they have been scattered, I will also be sanctified among them in the eyes of the nations. And they will certainly dwell upon their soil that I gave to my servant, to Jacob.

[[v26-28-26]]

^<<v26-28-26,26>>^ And they will actually dwell upon it in security and build houses and plant vineyards, and they must dwell in security when I execute acts of judgment upon all those treating them with scorn all round about them; and they will have to know that I am Jehovah their God.”’”^&#42;1^

[NOTE]
====
. Or, “I, Jehovah, am their God.” Heb., ʼaniʹ Yehwahʹ ʼElo·heh·hemʹ.
====

'''

xref:026-ezekiel/026-ezekiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezekiel/026-ezekiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]