include::./index.adoc[]

[[v26-11-0]]
=== Ezekiel, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-11-1]]

^<<v26-11-1,1>>^ And a spirit proceeded to lift me up and bring me to the eastern gate of the house of Jehovah that is facing eastward, and, look! in the entrance of the gate there were twenty-five men,^&#42;1^ and I got to see in the midst of them Ja·az·a·niʹah the son of Azʹzur and Pel·a·tiʹah^&#42;2^ the son of Be·naiʹah,^&#42;3^ princes of the people.

[NOTE]
====
. “Men.” Heb., ʼish.
. Meaning “Jehovah Has Provided Escape.” Heb., Pelat·yaʹhu.
. Meaning “Jehovah Has Built.” Heb., Bena·yaʹhu.
====

[[v26-11-2]]

^<<v26-11-2,2>>^ Then he^&#42;1^ said to me: “Son of man, these are the men^&#42;2^ that are scheming hurtfulness and advising bad counsel against this city;

[NOTE]
====
. “He,” MTVg; LXXSy, “Jehovah.”
. “The men.” Heb., ha·ʼana·shimʹ, pl. of ʼish.
====

[[v26-11-3]]

^<<v26-11-3,3>>^ that are saying, ‘Is not the building of houses close at hand? She^&#42;1^ is the widemouthed cooking pot, and we are the flesh.’

[NOTE]
====
. “She,” fem., referring to the “city” of Jerusalem.
====

[[v26-11-4]]

^<<v26-11-4,4>>^ “Therefore prophesy against them. Prophesy, O son of man.”

[[v26-11-5]]

^<<v26-11-5,5>>^ Then the spirit^&#42;1^ of Jehovah fell upon me, and he went on to say to me: “Say, ‘This is what Jehovah has said: “YOU people said the right thing, O house of Israel; and as regards the things that come up in YOUR spirit,^&#42;2^ I myself have known it.^&#42;3^

[NOTE]
====
. Or, “active force.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. See Ge 1:2 ftn, “Force.”
. Lit., “and the ascents of your spirit.” Heb., u·ma·ʽalohthʹ ru·chakhemʹ.
. “It,” fem., referring to “spirit.”
====

[[v26-11-6]]

^<<v26-11-6,6>>^ YOU have caused YOUR slain ones in this city to be many, and YOU have filled her streets with the slain &#91;ones&#93;.”’”

[[v26-11-7]]

^<<v26-11-7,7>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘As regards YOUR slain ones whom YOU people have put in the midst of her,^&#42;1^ they are the flesh, and she is the widemouthed cooking pot; and there will be a bringing forth^&#42;2^ of YOU yourselves out of the midst of her.’”

[NOTE]
====
. Or, “it,” fem., referring to the “city” of Jerusalem.
. “There will be a bringing forth.” In Heb. this is understood to be a verb in the infinitive absolute, indefinite as to time and impersonal, and used as the subject of the sentence.
====

[[v26-11-8]]

^<<v26-11-8,8>>^ “‘A sword YOU have feared, and a sword I shall bring upon YOU,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-11-9]]

^<<v26-11-9,9>>^ ‘And I shall certainly bring YOU forth out of the midst of her and give YOU into the hand of strangers and execute upon YOU acts of judgment.

[[v26-11-10]]

^<<v26-11-10,10>>^ By the sword YOU will fall. On the border^&#42;1^ of Israel I shall judge YOU people; and YOU will have to know that I am Jehovah.

[NOTE]
====
. Or, “territory.”
====

[[v26-11-11]]

^<<v26-11-11,11>>^ She herself will not prove to be for YOU a widemouthed cooking pot, and YOU yourselves will not^&#42;1^ prove to be flesh in the midst of her. On the border^&#42;2^ of Israel I shall judge YOU,

[NOTE]
====
. “Not,” LXXSyVg.
. Or, “territory.”
====

[[v26-11-12]]

^<<v26-11-12,12>>^ and YOU will have to know that I am Jehovah, because in my regulations YOU did not walk and my judgments YOU did not do, but according to the judgments of the nations that are round about YOU, YOU have done.’”

[[v26-11-13]]

^<<v26-11-13,13>>^ And it came about that as soon as I prophesied Pel·a·tiʹah the son of Be·naiʹah^&#42;1^ himself died, and I proceeded to fall upon my face and cry with a loud voice and say: “Alas, O Sovereign Lord Jehovah! Is it an extermination that you are executing with the remaining ones of Israel?”

[NOTE]
====
. Heb., Bena·yahʹ. Compare vs 1 ftn, “Benaiah.”
====

[[v26-11-14]]

^<<v26-11-14,14>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-11-15]]

^<<v26-11-15,15>>^ “Son of man, as regards your brothers, your brothers, the men^&#42;1^ concerned with your right to repurchase, and all the house of Israel, all of it, are the ones to whom the inhabitants of Jerusalem have said, ‘Get far away from Jehovah. To us it belongs; the land has been given &#91;us&#93; as a thing to possess’;

[NOTE]
====
. “Men.” Heb., ʼan·shehʹ, pl. of ʼish.
====

[[v26-11-16]]

^<<v26-11-16,16>>^ therefore say, ‘This is what the Sovereign Lord Jehovah has said: “Although I have put them far away among the nations, and although I have scattered them among the lands, yet I shall become to them a sanctuary for a little while^&#42;1^ among the lands to which they have come.”’

[NOTE]
====
. Or, “in a little way.”
====

[[v26-11-17]]

^<<v26-11-17,17>>^ “Therefore say, ‘This is what the Sovereign Lord Jehovah has said: “I will also collect YOU from the peoples and gather YOU from the lands among which YOU have been scattered, and I will give YOU the soil of Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ And they will certainly come there and remove all its disgusting things and all its detestable things out of it.

[[v26-11-19]]

^<<v26-11-19,19>>^ And I will give them one heart, and a new spirit I shall put inside them;^&#42;1^ and I shall certainly remove the heart of stone from their flesh and give them a heart of flesh,

[NOTE]
====
. “Them,” TLXXSyVg and many Heb. mss; M, “you,” pl.
====

[[v26-11-20]]

^<<v26-11-20,20>>^ in order that they may walk in my own statutes and keep my own judicial decisions and actually carry them out; and they may really become my people and I myself may become their God.”’

[[v26-11-21]]

^<<v26-11-21,21>>^ “‘“But as for those whose heart^&#42;1^ is walking in their disgusting things and their detestable things, upon their head I shall certainly bring their own way,” is the utterance of the Sovereign Lord Jehovah.’”

[NOTE]
====
. Lit., “And into the heart.” Heb., weʼel-levʹ.
====

[[v26-11-22]]

^<<v26-11-22,22>>^ And the cherubs now lifted up their wings, and the wheels were close by them, and the glory of the God of Israel was over them, from above.

[[v26-11-23]]

^<<v26-11-23,23>>^ And the glory of Jehovah went ascending from over the midst of the city and began to stand over the mountain that is to the east of the city.

[[v26-11-24]]

^<<v26-11-24,24>>^ And a spirit itself lifted me up and finally brought me to Chal·deʹa to the exiled people, in the vision by the spirit^&#42;1^ of God; and the vision that I had seen went ascending from upon me.

[NOTE]
====
. Or, “by the active force.” Heb., beruʹach; Gr., pneuʹma·ti; Lat., spiʹri·tu. See Ge 1:2 ftn, “Force”; Ge 6:17 ftn, “Active.”
====

[[v26-11-25]]

^<<v26-11-25,25>>^ And I began to speak to the exiled people all the things of Jehovah that he had caused me to see.

'''

xref:026-ezekiel/026-ezekiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezekiel/026-ezekiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]