include::./index.adoc[]

[[v26-12-0]]
=== Ezekiel, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-12-1]]

^<<v26-12-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-12-2]]

^<<v26-12-2,2>>^ “Son of man, in the midst of a rebellious house is where you are dwelling, that have eyes to see but they actually do not see, that have ears to hear but they actually do not hear, for they are a rebellious house.

[[v26-12-3]]

^<<v26-12-3,3>>^ As for you, O son of man, make up for yourself luggage for exile and go into exile in the daytime before their eyes, and you must go into exile from your place to another place before their eyes. Perhaps they will see, though^&#42;1^ they are a rebellious house.

[NOTE]
====
. Or, “will see that.”
====

[[v26-12-4]]

^<<v26-12-4,4>>^ And you must bring out your luggage like luggage for exile in the daytime before their eyes, and you yourself will go out in the evening before their eyes like those being brought forth for exile.

[[v26-12-5]]

^<<v26-12-5,5>>^ “Before their eyes, bore your way through the wall, and you must do the bringing out through it.

[[v26-12-6]]

^<<v26-12-6,6>>^ Before their eyes you will do the carrying on the shoulder itself. During the darkness you will do the bringing out. You will cover your very face that you may not see the earth, because a portent is what I have made you to the house of Israel.”

[[v26-12-7]]

^<<v26-12-7,7>>^ And I proceeded to do just the way that I had been commanded. My luggage I brought out, just like luggage for exile, in the daytime; and in the evening I bored my way through the wall by hand. During the darkness I did the bringing out. On my shoulder I did the carrying, before their eyes.

[[v26-12-8]]

^<<v26-12-8,8>>^ And the word of Jehovah continued to occur to me in the morning, saying:

[[v26-12-9]]

^<<v26-12-9,9>>^ “Son of man, did not those of the house of Israel, the rebellious house, say to you, ‘What are you doing?’

[[v26-12-10]]

^<<v26-12-10,10>>^ Say to them, ‘This is what the Sovereign Lord Jehovah has said: “As regards the chieftain, there is this pronouncement against Jerusalem and all the house of Israel who are in the midst of them.”’

[[v26-12-11]]

^<<v26-12-11,11>>^ “Say, ‘I am a portent for YOU. Just as I have done, that is the way it will be done to them. Into exile, into captivity they will go.

[[v26-12-12]]

^<<v26-12-12,12>>^ And as regards the chieftain who is in the midst of them, on the shoulder he will do carrying in the darkness and go out; through the wall they will bore in order to do the bringing forth through it. His face he will cover in order that he may not see with his own eye the earth.’

[[v26-12-13]]

^<<v26-12-13,13>>^ And I shall certainly spread my net over him, and he must be caught in my hunting net; and I will bring him to Babylon,^&#42;1^ to the land of the Chal·deʹans, but it he will not see; and there he will die.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v26-12-14]]

^<<v26-12-14,14>>^ And all who are round about him as a help, and all his military bands, I shall scatter to every wind;^&#42;1^ and a sword I shall draw out after them.

[NOTE]
====
. “Wind.” Heb., ruʹach; Gr., aʹne·mon; Lat., venʹtum.
====

[[v26-12-15]]

^<<v26-12-15,15>>^ And they will have to know that I am Jehovah when I disperse them among the nations and I actually scatter them among the lands.

[[v26-12-16]]

^<<v26-12-16,16>>^ And I will leave remaining from them a few men^&#42;1^ from the sword, from the famine and from the pestilence, in order that they may recount all their detestable things among the nations to whom they must come in; and they will have to know that I am Jehovah.”

[NOTE]
====
. “Men.” Heb., ʼan·shehʹ.
====

[[v26-12-17]]

^<<v26-12-17,17>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-12-18]]

^<<v26-12-18,18>>^ “Son of man, with quaking your bread you should eat, and with agitation and with anxious care your water you should drink.

[[v26-12-19]]

^<<v26-12-19,19>>^ And you must say to the people of the land,^&#42;1^ ‘This is what the Sovereign Lord Jehovah has said to the inhabitants of Jerusalem upon the soil^&#42;2^ of Israel: “With anxious care their bread they will eat, and with horror their water they will drink, in order that its land may be laid desolate of its fullness because of the violence of all those dwelling in it.

[NOTE]
====
. See 7:27 ftn.
. Or, “concerning the soil.” Heb., ʼel-ʼadh·mathʹ; TLXXVg, “upon the land.”
====

[[v26-12-20]]

^<<v26-12-20,20>>^ And the inhabited cities themselves will be devastated, and the land itself will become a mere desolate waste; and YOU will have to know that I am Jehovah.”’”

[[v26-12-21]]

^<<v26-12-21,21>>^ And the word of Jehovah occurred further to me, saying:

[[v26-12-22]]

^<<v26-12-22,22>>^ “Son of man, what is this proverbial saying that YOU people have on the soil of Israel, saying, ‘The days are prolonged, and every vision has perished’?

[[v26-12-23]]

^<<v26-12-23,23>>^ Therefore say to them, ‘This is what the Sovereign Lord Jehovah has said: “I shall certainly cause this proverbial saying to cease, and they will no more say it as a proverb in Israel.”’ But speak to them, ‘The days have drawn near, and the matter of every vision.’

[[v26-12-24]]

^<<v26-12-24,24>>^ For there will no more prove to be any valueless vision nor double-faced^&#42;1^ divination in the midst of the house of Israel.

[NOTE]
====
. Or, “smooth.”
====

[[v26-12-25]]

^<<v26-12-25,25>>^ ‘“For I myself, Jehovah, shall speak what word I shall speak, and it will be done. There will be no postponement anymore, for in YOUR days, O rebellious house, I shall speak a word and certainly do it,” is the utterance of the Sovereign Lord Jehovah.’”

[[v26-12-26]]

^<<v26-12-26,26>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-12-27]]

^<<v26-12-27,27>>^ “Son of man, look! those of the house of Israel are saying, ‘The vision that he is visioning is many days off, and respecting times far off he is prophesying.’

[[v26-12-28]]

^<<v26-12-28,28>>^ Therefore say to them, ‘This is what the Sovereign Lord Jehovah has said: “‘There will be no postponement anymore as to any words of mine. What word I shall speak, it will even be done,’ is the utterance of the Sovereign Lord Jehovah.”’”

'''

xref:026-ezekiel/026-ezekiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezekiel/026-ezekiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]