include::./index.adoc[]

[[v26-34-0]]
=== Ezekiel, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-34-1]]

^<<v26-34-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-34-2]]

^<<v26-34-2,2>>^ “Son of man, prophesy against the shepherds of Israel. Prophesy, and you must say to them, to the shepherds, ‘This is what the Sovereign Lord Jehovah has said: “Woe to the shepherds of Israel, who have become feeders^&#42;1^ of themselves! Is it not the flock that the shepherds ought to feed?

[NOTE]
====
. Or, “shepherds.”
====

[[v26-34-3]]

^<<v26-34-3,3>>^ The fat is what YOU eat, and with the wool YOU clothe your own selves. The plump animal is what YOU slaughter. The flock^&#42;1^ itself YOU do not feed.

[NOTE]
====
. Or, “The sheep.” Heb., hats·tsoʼnʹ.
====

[[v26-34-4]]

^<<v26-34-4,4>>^ The sickened ones YOU have not strengthened, and the ailing one YOU have not healed, and the broken one YOU have not bandaged, and the dispersed one YOU have not brought back, and the lost^&#42;1^ one YOU have not sought to find, but with harshness YOU have had them in subjection, even with tyranny.

[NOTE]
====
. Lit., “perishing.”
====

[[v26-34-5]]

^<<v26-34-5,5>>^ And they were gradually scattered because of there being no shepherd, so that they became food for every wild beast of the field, and they continued to be scattered.

[[v26-34-6]]

^<<v26-34-6,6>>^ My sheep^&#42;1^ kept straying on all the mountains and on every high hill; and on all the surface of the earth my sheep were scattered, with no one making a search and with no one seeking to find.

[NOTE]
====
. Or, “My flock.” Heb., tsoʼ·niʹ.
====

[[v26-34-7]]

^<<v26-34-7,7>>^ “‘“Therefore, YOU shepherds, hear the word of Jehovah,

[[v26-34-8]]

^<<v26-34-8,8>>^ ‘“As I am alive,” is the utterance of the Sovereign Lord Jehovah, “surely for the reason that my sheep became something for plunder and my sheep continued to be food for every wild beast of the field, because there was no shepherd, and my shepherds did not search for my sheep, but the shepherds kept feeding themselves, and my own sheep they did not feed,”’

[[v26-34-9]]

^<<v26-34-9,9>>^ therefore, YOU shepherds, hear the word of Jehovah.

[[v26-34-10]]

^<<v26-34-10,10>>^ This is what the Sovereign Lord Jehovah has said, ‘Here I am against the shepherds, and I shall certainly ask back my sheep from their hand and make them cease from feeding^&#42;1^ &#91;my&#93; sheep, and the shepherds will no longer feed themselves; and I will deliver my sheep out of their mouth, and they will not become food for them.’”

[NOTE]
====
. Or, “shepherding.”
====

[[v26-34-11]]

^<<v26-34-11,11>>^ “‘For this is what the Sovereign Lord Jehovah has said: “Here I am, I myself, and I will search for my sheep and care for them.

[[v26-34-12]]

^<<v26-34-12,12>>^ According to the care of one feeding his drove in the day of his coming to be in the midst of his sheep that have been spread abroad, that is the way that I shall care for my sheep; and I will deliver them out of all the places to which they have been scattered in the day of clouds and thick gloom.

[[v26-34-13]]

^<<v26-34-13,13>>^ And I will bring them out from the peoples and collect them together from the lands and bring them in onto their soil and feed them on the mountains of Israel, by the streambeds and by all the dwelling places of the land.

[[v26-34-14]]

^<<v26-34-14,14>>^ In a good pasturage I shall feed them, and on Israel’s high mountains their abiding place will come to be. There they will lie down in a good abiding place, and on a fat pasturage they will feed upon the mountains of Israel.”

[[v26-34-15]]

^<<v26-34-15,15>>^ “‘“I myself shall feed my sheep,^&#42;1^ and I myself shall make them lie down,” is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. See vs 6 ftn.
====

[[v26-34-16]]

^<<v26-34-16,16>>^ “The lost^&#42;1^ one I shall search for, and the dispersed one I shall bring back, and the broken one I shall bandage and the ailing one I shall strengthen, but the fat one and the strong one I shall annihilate. I shall feed that one^&#42;2^ with judgment.”^&#42;3^

[NOTE]
====
. Lit., “perishing.”
. “That one.” Lit., “her,” M; LXXSyVg, “them.”
. Or, “with justice.” Heb., vemish·patʹ.
====

[[v26-34-17]]

^<<v26-34-17,17>>^ “‘And as for YOU my sheep, this is what the Sovereign Lord Jehovah has said: “Here I am judging between a sheep and a sheep,^&#42;1^ between the rams and the he-goats.

[NOTE]
====
. Lit., “between a sheep for the sheep.” Heb., behn-sehʹ la·sehʹ.
====

[[v26-34-18]]

^<<v26-34-18,18>>^ Is it such a little thing for YOU men that on the very best pasturage^&#42;1^ YOU feed but the rest of YOUR pasturages YOU should trample down with YOUR feet, and that the clear^&#42;2^ waters YOU drink but the ones left over YOU should foul by stamping with YOUR very feet?

[NOTE]
====
. Lit., “the good pasturage.”
. Or, “settled.”
====

[[v26-34-19]]

^<<v26-34-19,19>>^ And as for my sheep, on the pasture ground trampled by YOUR feet should they feed and the water befouled by the stamping of YOUR feet should they drink?”

[[v26-34-20]]

^<<v26-34-20,20>>^ “‘Therefore this is what the Sovereign Lord Jehovah has said to them: “Here I am, I myself, and I shall certainly judge between a plump sheep^&#42;1^ and a lean sheep,

[NOTE]
====
. “Sheep.” Heb., seh, sing.
====

[[v26-34-21]]

^<<v26-34-21,21>>^ for the reason that with flank and with shoulder YOU kept pushing and with YOUR horns YOU kept shoving all the sickened ones until YOU had scattered them to the outside.

[[v26-34-22]]

^<<v26-34-22,22>>^ And I will save my sheep,^&#42;1^ and they will no longer become something for plunder; and I will judge between a sheep and a sheep.^&#42;2^

[NOTE]
====
. Or, “my flock.” Heb., letsoʼ·niʹ.
. See vs 17 ftn.
====

[[v26-34-23]]

^<<v26-34-23,23>>^ And I will raise up over them one shepherd, and he must feed^&#42;1^ them, even my servant David. He himself will feed them, and he himself will become their shepherd.

[NOTE]
====
. Or, “shepherd.”
====

[[v26-34-24]]

^<<v26-34-24,24>>^ And I myself, Jehovah, will become their God,^&#42;1^ and my servant David a chieftain^&#42;2^ in the midst of them. I myself, Jehovah, have spoken.

[NOTE]
====
. Lit., “to them for God.” Heb., la·hemʹ lEʼ·lo·himʹ.
. Or, “nasi.”
====

[[v26-34-25]]

^<<v26-34-25,25>>^ “‘“And I will conclude^&#42;1^ with them a covenant of peace, and I shall certainly cause the injurious wild beast to cease out of the land, and they will actually dwell in the wilderness in security and sleep in the forests.

[NOTE]
====
. Lit., “cut.”
====

[[v26-34-26]]

^<<v26-34-26,26>>^ And I will make them and the surroundings of my hill a blessing, and I will cause the pouring rain to descend in its time. Pouring rains of blessing there will prove to be.

[[v26-34-27]]

^<<v26-34-27,27>>^ And the tree of the field must give its fruitage, and the land itself will give its yield, and they will actually prove to be on their soil in security. And they will have to know that I am Jehovah when I break the bars of their yoke and I have delivered them out of the hand of those who had been using them as slaves.

[[v26-34-28]]

^<<v26-34-28,28>>^ And they will no longer become something to plunder for the nations; and as regards the wild beast of the earth, it will not devour them, and they will actually dwell in security, with no one to make &#91;them&#93; tremble.

[[v26-34-29]]

^<<v26-34-29,29>>^ “‘“And I will raise up for them a planting for a name,^&#42;1^ and they will no more become those taken away by famine in the land, and they will no longer bear the humiliation by the nations.

[NOTE]
====
. Or, “fame; renown.”
====

[[v26-34-30]]

^<<v26-34-30,30>>^ ‘And they will have to know that I, Jehovah their God, am with them and that they are my people, the house of Israel,’ is the utterance of the Sovereign Lord Jehovah.”’

[[v26-34-31]]

^<<v26-34-31,31>>^ “‘And as regards YOU^&#42;1^ my sheep,^&#42;2^ the sheep of my pasturing, YOU^&#42;3^ are earthling men.^&#42;4^ I am YOUR God,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. “You,” fem. pl.
. See vs 6 ftn.
. “You,” masc. pl.
. “Earthling men.” Heb., ʼa·dhamʹ.
====

'''

xref:026-ezekiel/026-ezekiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezekiel/026-ezekiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]