include::./index.adoc[]

[[v26-19-0]]
=== Ezekiel, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-19-1]]

^<<v26-19-1,1>>^ “And as for you, raise a dirge concerning the chieftains of Israel,

[[v26-19-2]]

^<<v26-19-2,2>>^ and you must say, ‘What was your mother? A lioness among lions.^&#42;1^ She lay down in among maned young lions. She reared her cubs.

[NOTE]
====
. “Lions.” Heb., ʼara·yohthʹ, African lions.
====

[[v26-19-3]]

^<<v26-19-3,3>>^ “‘And gradually she brought up one of her cubs. A maned young lion is what he became, and he began to learn how to tear apart prey. He devoured even earthling man.^&#42;1^

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-19-4]]

^<<v26-19-4,4>>^ And nations kept hearing about him. In their pit he was caught, and they proceeded to bring him by means of hooks^&#42;1^ to the land of Egypt.

[NOTE]
====
. Or, “thorns”; put through the cheek or nose of animals as well as of captives in order to lead them on a rope.
====

[[v26-19-5]]

^<<v26-19-5,5>>^ “‘When she got to see that she had waited &#91;and&#93; her hope had perished, then she took another of her cubs. As a maned young lion she put him forth.

[[v26-19-6]]

^<<v26-19-6,6>>^ And he began to walk about in the midst of lions. A maned young lion is what he became. And he gradually learned how to tear apart prey. He devoured even earthling man.

[[v26-19-7]]

^<<v26-19-7,7>>^ And he got to know his dwelling towers,^&#42;1^ and he devastated even their cities, so that the land was laid desolate and he filled it with the sound of his roaring.

[NOTE]
====
. “Dwelling towers; palaces,” by the substitution of a letter; M, “widows.”
====

[[v26-19-8]]

^<<v26-19-8,8>>^ And nations all around from the jurisdictional districts began to set^&#42;1^ against him and got to spread over him their net. In their pit he was caught.

[NOTE]
====
. Possibly, “camp,” by changing the letter Taw to Chehth.
====

[[v26-19-9]]

^<<v26-19-9,9>>^ Finally they put him in the cage by means of hooks^&#42;1^ and brought him to the king of Babylon.^&#42;2^ They got to bring him by means of hunting nets, in order that his voice might no more be heard on the mountains of Israel.

[NOTE]
====
. See vs 4 ftn.
. “Babylon,” LXX­Vg; MTSy, “Babel.”
====

[[v26-19-10]]

^<<v26-19-10,10>>^ “‘Your mother was like a vine in your blood,^&#42;1^ planted by waters. A bearer of fruit and full of branches she became because of abundant water.

[NOTE]
====
. “In your blood,” MSy­Vg; two Heb. mss, “of your vineyard”; T, “she used to resemble.”
====

[[v26-19-11]]

^<<v26-19-11,11>>^ And they came to be for her strong rods, meant for the scepters of rulers. And its height gradually became tall up among branches, and it got to be visible because of its tallness, because of the abundance of its foliage.

[[v26-19-12]]

^<<v26-19-12,12>>^ But she was finally uprooted in fury. To the earth she was thrown, and there was an east wind that dried up her fruit. Her strong rod was torn off and became dry. Fire itself devoured it.

[[v26-19-13]]

^<<v26-19-13,13>>^ And now she is planted in the wilderness, in a waterless and thirsty land.

[[v26-19-14]]

^<<v26-19-14,14>>^ And fire proceeded to come forth from &#91;her&#93; rod. It devoured her very shoots, her very fruit, and there proved to be in her no strong rod, no scepter for ruling.
“‘That is a dirge, and it will become a dirge.’”

'''

xref:026-ezekiel/026-ezekiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezekiel/026-ezekiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]