include::./index.adoc[]

[[v26-33-0]]
=== Ezekiel, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-33-1]]

^<<v26-33-1,1>>^ And the word of Jehovah proceeded to occur to me, saying:

[[v26-33-2]]

^<<v26-33-2,2>>^ “Son of man, speak to the sons of your people, and you must say to them,
“‘As regards a land, in case I bring upon it a sword and the people of the land,^&#42;1^ one and all, actually take a man^&#42;2^ and set him as their watchman,^&#42;3^

[NOTE]
====
. “The people of the land.” Heb., ʽam-ha·ʼaʹrets. Later used as an expression of contempt. Compare Joh 7:47-49.
. Or, “and the people of the land actually take a man [Heb., ʼish], one from their borders.”
. Or, “as their lookout.” Heb., la·hemʹ letso·phehʹ.
====

[[v26-33-3]]

^<<v26-33-3,3>>^ and he really sees the sword coming upon the land and blows the horn^&#42;1^ and warns the people,

[NOTE]
====
. Or, “shofar.”
====

[[v26-33-4]]

^<<v26-33-4,4>>^ and the hearer actually hears the sound of the horn but he takes no warning at all, and a sword comes and takes him away, his own blood will come to be upon his own head.

[[v26-33-5]]

^<<v26-33-5,5>>^ The sound of the horn he heard, but he took no warning. His own blood will come to be upon his own self. And had he himself taken warning, his own soul^&#42;1^ would have escaped.

[NOTE]
====
. Or, “his own life.” Heb., naph·shohʹ; Gr., psy·khenʹ; Lat., aʹni·mam. See App 4A.
====

[[v26-33-6]]

^<<v26-33-6,6>>^ “‘Now as regards the watchman, in case he sees the sword coming and he actually does not blow the horn and the people itself gets no warning at all and a sword comes and takes away from them soul, for its own error it itself must be taken away, but its blood I shall ask back from the hand of the watchman^&#42;1^ himself.’

[NOTE]
====
. Or, “the lookout.”
====

[[v26-33-7]]

^<<v26-33-7,7>>^ “Now as regards you, O son of man, a watchman is what I have made you to the house of Israel, and at my mouth you must hear &#91;the&#93; word and give them warning from me.

[[v26-33-8]]

^<<v26-33-8,8>>^ When I say to someone wicked, ‘O wicked one, you will positively die!’ but you actually do not speak out to warn the wicked one from his way, he himself as a wicked one will die in his own error, but his blood I shall ask back at your own hand.

[[v26-33-9]]

^<<v26-33-9,9>>^ But as regards you, in case you actually warn someone wicked from his way &#91;for him&#93; to turn back from it but he actually does not turn back from his way, he himself will die in his own error, whereas you yourself will certainly deliver your own soul.^&#42;1^

[NOTE]
====
. Or, “your own life.” Heb., naph·shekhaʹ.
====

[[v26-33-10]]

^<<v26-33-10,10>>^ “Now as regards you, O son of man, say to the house of Israel, ‘Thus YOU people have said: “Because our revolts and our sins are upon us and in them we are rotting away, how, then, shall we keep living?”’

[[v26-33-11]]

^<<v26-33-11,11>>^ Say to them, ‘“As I am alive,” is the utterance of the Sovereign Lord Jehovah, “I take delight, not in the death of the wicked one, but in that someone wicked turns back from his way and actually keeps living. Turn back, turn back from YOUR bad ways, for why is it that YOU should die, O house of Israel?”’

[[v26-33-12]]

^<<v26-33-12,12>>^ “And as for you, O son of man, say to the sons of your people, ‘The righteousness of the righteous one will not itself deliver him in the day of his revolt. But as regards the wickedness of the wicked one, he will not be made to stumble by it in the day of his turning back from his wickedness. Nor will even anyone having righteousness be able to keep living because of it in the day of his sinning.

[[v26-33-13]]

^<<v26-33-13,13>>^ When I say to the righteous one: “You will positively keep living,” and he himself actually trusts in his own righteousness and does injustice, all his own righteous acts will not be remembered, but for his injustice that he has done—for this he will die.

[[v26-33-14]]

^<<v26-33-14,14>>^ “‘And when I say to the wicked one: “You will positively die,” and he actually turns back from his sin and carries on justice and righteousness,

[[v26-33-15]]

^<<v26-33-15,15>>^ &#91;and&#93; the wicked one returns the very thing pledged, pays back the very things taken by robbery, &#91;and&#93; actually walks in the very statutes of life by not doing injustice, he will positively keep living. He will not die.

[[v26-33-16]]

^<<v26-33-16,16>>^ None of his sins with which he has sinned will be remembered against him. Justice and righteousness are what he has carried on. He will positively keep living.’

[[v26-33-17]]

^<<v26-33-17,17>>^ “And the sons of your people have said, ‘The way of Jehovah^&#42;1^ is not adjusted right,’ but, as for them, it is their way that is not adjusted right.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v26-33-18]]

^<<v26-33-18,18>>^ “When someone righteous turns back from his righteousness and actually does injustice, he must also die for them.

[[v26-33-19]]

^<<v26-33-19,19>>^ And when someone wicked turns back from his wickedness and actually carries on justice and righteousness, it will be on account of them that he himself will keep living.

[[v26-33-20]]

^<<v26-33-20,20>>^ “And YOU people have said, ‘The way of Jehovah^&#42;1^ is not adjusted right.’ It will be each one according to his ways that I shall judge YOU, O house of Israel.”

[NOTE]
====
. See vs 17 ftn.
====

[[v26-33-21]]

^<<v26-33-21,21>>^ At length it occurred in the twelfth year, in the tenth &#91;month&#93;, on the fifth day of the month of our exile, that there came to me the escaped one from Jerusalem, saying: “The city has been struck down!”

[[v26-33-22]]

^<<v26-33-22,22>>^ Now the very hand of Jehovah had come to be upon me in the evening before the coming of the escaped one, and He proceeded to open my mouth prior to &#91;that one’s&#93; coming to me in the morning, and my mouth was opened and I proved to be speechless no longer.

[[v26-33-23]]

^<<v26-33-23,23>>^ And the word of Jehovah began to occur to me, saying:

[[v26-33-24]]

^<<v26-33-24,24>>^ “Son of man, the inhabitants of these devastated places are saying even concerning the soil of Israel, ‘Abraham happened to be just one and yet he took possession of the land. And we are many; to us the land has been given as something to possess.’

[[v26-33-25]]

^<<v26-33-25,25>>^ “Therefore say to them, ‘This is what the Sovereign Lord Jehovah has said: “With^&#42;1^ the blood YOU keep eating, and YOUR eyes YOU keep lifting to YOUR dungy idols, and blood YOU keep pouring out. So should YOU possess the land?

[NOTE]
====
. Lit., “Upon.”
====

[[v26-33-26]]

^<<v26-33-26,26>>^ YOU have depended^&#42;1^ upon YOUR sword. YOU^&#42;2^ have done a detestable thing, and YOU have defiled each one the wife of his companion. So should YOU possess the land?”’

[NOTE]
====
. Lit., “stood.”
. “You,” masc. pl., TSy and 18 Heb. mss; M, “You,” fem. pl.
====

[[v26-33-27]]

^<<v26-33-27,27>>^ “This is what you should say to them, ‘This is what the Sovereign Lord Jehovah has said: “As I am alive, surely the ones who are in the devastated places will fall by the sword itself; and the one who is upon the surface of the field, to the wild beast I shall certainly give him for food; and those who are in the strong places and in the caves will die by the pestilence itself.

[[v26-33-28]]

^<<v26-33-28,28>>^ And I shall actually make the land a desolate waste, even a desolation, and the pride of its strength must be made to cease and the mountains of Israel must be laid desolate, with no one passing through.

[[v26-33-29]]

^<<v26-33-29,29>>^ And they will have to know that I am Jehovah when I make the land a desolate waste, even a desolation, on account of all their detestable things that they have done.”’

[[v26-33-30]]

^<<v26-33-30,30>>^ “And as for you, O son of man, the sons of your people are speaking with one another about you beside the walls and in the entrances of the houses, and the one has spoken with the other, each one with his brother, saying, ‘COME, please, and hear what the word is that is going forth from Jehovah.’

[[v26-33-31]]

^<<v26-33-31,31>>^ And they will come in to you, like the coming in of people, and sit before you as my people; and they will certainly hear your words but these they will not do, for with their mouth they are expressing lustful desires &#91;and&#93; after their unjust gain is where their heart is going.

[[v26-33-32]]

^<<v26-33-32,32>>^ And, look! you are to them like a song of sensuous loves, like one with a pretty voice and playing a stringed instrument well. And they will certainly hear your words, but there are none doing them.

[[v26-33-33]]

^<<v26-33-33,33>>^ And when it comes true—look! it must come true—they will also have to know that a prophet himself had proved to be in the midst of them.”

'''

xref:026-ezekiel/026-ezekiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezekiel/026-ezekiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]