include::./index.adoc[]

[[v26-24-0]]
=== Ezekiel, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-24-1]]

^<<v26-24-1,1>>^ And the word of Jehovah continued to occur to me in the ninth year, in the tenth month, on the tenth &#91;day&#93; of the month, saying:

[[v26-24-2]]

^<<v26-24-2,2>>^ “Son of man, write down for yourself the name of the day, this selfsame day. The king of Babylon has thrown himself against Jerusalem on this selfsame day.

[[v26-24-3]]

^<<v26-24-3,3>>^ And compose a proverbial saying concerning the rebellious house, and you must say concerning them,
“‘This is what the Sovereign Lord Jehovah has said: “Put the widemouthed cooking pot on; put &#91;it&#93; on, and also pour water into it.

[[v26-24-4]]

^<<v26-24-4,4>>^ Gather pieces in it, every good piece, thigh and shoulder; fill &#91;it&#93; even with the choicest bones.

[[v26-24-5]]

^<<v26-24-5,5>>^ Let there be a taking of the choicest sheep, and also stack the logs^&#42;1^ in a circle under it. Boil its pieces,^&#42;2^ also cook its bones in the midst of it.”’”

[NOTE]
====
. Lit., “bones.”
. “Pieces,” two Heb. mss; M, “boilings.”
====

[[v26-24-6]]

^<<v26-24-6,6>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Woe to the city of deeds of bloodshed,^&#42;1^ the widemouthed cooking pot, the rust of which is in it, and the very rust of which has not gone forth from it! Piece by piece of it, bring it out; no lot must be cast over it.

[NOTE]
====
. “Deeds of bloodshed.” Lit., “the bloods.”
====

[[v26-24-7]]

^<<v26-24-7,7>>^ For its very blood has come to be right in the midst of it. Upon the shining, bare surface of a crag she placed it. She did not pour it out upon the earth, in order to cover it over with dust.

[[v26-24-8]]

^<<v26-24-8,8>>^ In order to bring up rage for the executing of vengeance, I have put her blood upon the shining, bare surface of a crag, in order that it may not be covered over.’

[[v26-24-9]]

^<<v26-24-9,9>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Woe to the city of deeds of bloodshed! I myself also shall make the pile great.

[[v26-24-10]]

^<<v26-24-10,10>>^ Make the logs many. Kindle the fire. Boil the flesh thoroughly. And empty out the broth,^&#42;1^ and let the bones themselves become piping hot.

[NOTE]
====
. “Empty out the broth,” by a correction; M, “let there be a spicing with the scented herbs.”
====

[[v26-24-11]]

^<<v26-24-11,11>>^ Stand it^&#42;1^ empty upon its coals in order that it may get hot; and its copper must become heated up, and its uncleanness must be liquefied in the midst of it. Let its rust get consumed.

[NOTE]
====
. “It,” fem.
====

[[v26-24-12]]

^<<v26-24-12,12>>^ Troubles! It has made &#91;one&#93; tired, but the great amount of its rust does not go forth from it. Into &#91;the&#93; fire with its rust!’

[[v26-24-13]]

^<<v26-24-13,13>>^ “‘There was loose conduct in your^&#42;1^ uncleanness. For that reason I had to cleanse you, but you did not become clean from your uncleanness. You will become clean no more until I cause my rage to come to its rest in your case.

[NOTE]
====
. “Your,” fem. sing., addressed to the city.
====

[[v26-24-14]]

^<<v26-24-14,14>>^ I myself, Jehovah, have spoken. It must come, and I will act. I shall not neglect, neither shall I feel sorry nor feel regret. According to your ways and according to your dealings they^&#42;1^ will certainly judge you,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. “They,” M; TLXXSyVg, “I.”
====

[[v26-24-15]]

^<<v26-24-15,15>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-24-16]]

^<<v26-24-16,16>>^ “Son of man, here I am taking away from you the thing desirable to your eyes by a blow, and you should not beat your breast, neither should you weep nor should your tears come on.

[[v26-24-17]]

^<<v26-24-17,17>>^ Sigh without words.^&#42;1^ For the dead ones no mourning should you make. Your headdress bind on yourself, and your sandals you should put upon your feet. And you should not cover over &#91;the&#93; mustache,^&#42;2^ and the bread of men you should not eat.”

[NOTE]
====
. “Without words.” Lit., “keep silent.”
. Or, “upper lip.”
====

[[v26-24-18]]

^<<v26-24-18,18>>^ And I proceeded to speak to the people in the morning, and my wife gradually died in the evening. So I did in the morning just as I had been commanded.

[[v26-24-19]]

^<<v26-24-19,19>>^ And the people kept saying to me: “Will you not tell us what these things have to do with us, that you are doing?”

[[v26-24-20]]

^<<v26-24-20,20>>^ Then I said to them: “The very word of Jehovah has occurred to me, saying,

[[v26-24-21]]

^<<v26-24-21,21>>^ ‘Say to the house of Israel: “This is what the Sovereign Lord Jehovah has said, ‘Here I am profaning my sanctuary, the pride of YOUR strength, the thing desirable to YOUR eyes and the object of YOUR soul’s compassion, and YOUR sons and YOUR daughters whom YOU people have left behind—by the sword they will fall.

[[v26-24-22]]

^<<v26-24-22,22>>^ And YOU will have to do just as I have done. Mustaches^&#42;1^ YOU will not cover over, and the bread of men YOU will not eat.

[NOTE]
====
. Or, “Upper lips.”
====

[[v26-24-23]]

^<<v26-24-23,23>>^ And YOUR headdress will be on YOUR heads, and YOUR sandals be upon YOUR feet. YOU will not beat yourselves nor will YOU weep, and YOU will have to rot away in YOUR errors, and YOU will actually groan over one another.

[[v26-24-24]]

^<<v26-24-24,24>>^ And Ezekiel has become for YOU a portent. In accord with all that he has done, YOU will do. When it comes, YOU will also have to know that I am the Sovereign Lord Jehovah.’”’”

[[v26-24-25]]

^<<v26-24-25,25>>^ “And as for you, O son of man, will it not be in the day of my taking away from them their fortress, the beautiful object of their exultation, the thing desirable to their eyes and the longing of their soul, their sons and their daughters, that

[[v26-24-26]]

^<<v26-24-26,26>>^ in that day there will come to you the escaped one for making the ears hear?

[[v26-24-27]]

^<<v26-24-27,27>>^ In that day your mouth will be opened to the escaped one, and you will speak and be mute no longer; and you will certainly become to them a portent, and they will have to know that I am Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezekiel/026-ezekiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]