include::./index.adoc[]

[[v26-48-0]]
=== Ezekiel, 48
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-48-1]]

^<<v26-48-1,1>>^ “And these are the names of the tribes. From the northern extremity, on the side by the way of Hethʹlon to the entering in to Haʹmath, Haʹzar-eʹnan, the boundary of Damascus northward, on the side of Haʹmath; and it must prove to have an eastern border &#91;and&#93; the western, Dan one &#91;portion&#93;.

[[v26-48-2]]

^<<v26-48-2,2>>^ And on the boundary of Dan, from the eastern border to the western border, Ashʹer one.

[[v26-48-3]]

^<<v26-48-3,3>>^ And on the boundary of Ashʹer, from the eastern border even to the western border, Naphʹta·li one.

[[v26-48-4]]

^<<v26-48-4,4>>^ And on the boundary of Naphʹta·li, from the eastern border to the western border, Ma·nasʹseh one.

[[v26-48-5]]

^<<v26-48-5,5>>^ And on the boundary of Ma·nasʹseh, from the eastern border to the western border, Eʹphra·im one.

[[v26-48-6]]

^<<v26-48-6,6>>^ And on the boundary of Eʹphra·im, from the eastern border even to the western border, Reuʹben one.

[[v26-48-7]]

^<<v26-48-7,7>>^ And on the boundary of Reuʹben, from the eastern border to the western border, Judah one.

[[v26-48-8]]

^<<v26-48-8,8>>^ And on the boundary of Judah, from the eastern border to the western border, the contribution that YOU people should contribute should prove to be twenty-five thousand &#91;cubits&#93; in width, and &#91;the&#93; length according to one of the portions from the eastern border to the western border. And the sanctuary^&#42;1^ must prove to be in the midst of it.

[NOTE]
====
. “The sanctuary.” Heb., ham·miq·dashʹ; Gr., to haʹgi·on; Lat., sanc·tu·aʹri·um.
====

[[v26-48-9]]

^<<v26-48-9,9>>^ “As regards the contribution that YOU should contribute to Jehovah, &#91;the&#93; length will be twenty-five thousand &#91;cubits&#93; and &#91;the&#93; width ten thousand.

[[v26-48-10]]

^<<v26-48-10,10>>^ And as to these there should prove to be the holy contribution for the priests, to the north twenty-five thousand &#91;cubits&#93;, and to the west a width of ten thousand, and to the east a width of ten thousand, and to the south a length of twenty-five thousand. And the sanctuary of Jehovah^&#42;1^ must prove to be in the midst of it.

[NOTE]
====
. “The sanctuary of Jehovah.” Heb., miq·dash-Yehwahʹ; Lat., sanc·tu·aʹri·um Doʹmi·ni; LXX, “the mountain of the holy things.”
====

[[v26-48-11]]

^<<v26-48-11,11>>^ It will be for the priests, those who are sanctified from the sons of Zaʹdok, who took care of the obligation toward me, who did not wander away when the sons of Israel wandered away, just as the Levites wandered away.

[[v26-48-12]]

^<<v26-48-12,12>>^ And they must come to have a contribution from the contribution of the land as something most holy, on the boundary of the Levites.

[[v26-48-13]]

^<<v26-48-13,13>>^ “And the Levites should have, right next to the territory of the priests, twenty-five thousand &#91;cubits&#93; in length, and in width ten thousand; the whole length being twenty-five thousand and width being ten thousand.

[[v26-48-14]]

^<<v26-48-14,14>>^ And they should not sell any of it, nor should one make an exchange, nor should one cause the choicest of the land to pass away &#91;from them&#93;; for it is something holy to Jehovah.

[[v26-48-15]]

^<<v26-48-15,15>>^ “As regards the five thousand &#91;cubits&#93; that is left remaining in width alongside the twenty-five thousand, it is something profane for the city, for a dwelling place and for pasture ground. And the city must come to be in the midst of it.

[[v26-48-16]]

^<<v26-48-16,16>>^ And these are the &#91;city’s&#93;^&#42;1^ measurements: the northern border four thousand five hundred &#91;cubits&#93;, and the southern border four thousand five hundred, and the eastern border four thousand five hundred, and the western border four thousand five hundred.

[NOTE]
====
. Lit., “its,” fem., referring to the “city,” fem.
====

[[v26-48-17]]

^<<v26-48-17,17>>^ And the city must come to have a pasture ground, to the north two hundred and fifty &#91;cubits&#93;, and to the south two hundred and fifty, and to the east two hundred and fifty, and to the west two hundred and fifty.

[[v26-48-18]]

^<<v26-48-18,18>>^ “And what is left remaining over in length will be exactly as the holy contribution, ten thousand &#91;cubits&#93; to the east, and ten thousand to the west; and it must prove to be exactly as the holy contribution, and its produce must come to be for bread for the ones serving the city.

[[v26-48-19]]

^<<v26-48-19,19>>^ And those who are serving the city out of all the tribes of Israel will cultivate it.

[[v26-48-20]]

^<<v26-48-20,20>>^ “The whole contribution is twenty-five thousand &#91;cubits&#93; by twenty-five thousand. A foursquare part YOU people should contribute as the holy contribution with the possession of the city.

[[v26-48-21]]

^<<v26-48-21,21>>^ “And what is left over will belong to the chieftain, on this side and on that side of the holy contribution and of the possession of the city, alongside the twenty-five thousand &#91;cubits&#93; &#91;of&#93; the contribution to the eastern boundary; and on the west alongside the twenty-five thousand &#91;cubits&#93; to the western boundary. Exactly like the portions, &#91;it will be&#93; for the chieftain. And the holy contribution and the sanctuary^&#42;1^ of the House^&#42;2^ must prove to be in the midst of it.

[NOTE]
====
. “And the sanctuary of.” Heb., u·miq·dashʹ; Gr., ha·giʹa·sma; Lat., sanc·tu·aʹri·um.
. “The House,” M(Heb., hab·baʹyith)TLXXSy; Lat., temʹpli.
====

[[v26-48-22]]

^<<v26-48-22,22>>^ “And as regards the possession of the Levites and the possession of the city, in between what belongs to the chieftain it should prove to be. Between the boundary of Judah and the boundary of Benjamin it should come to belong to the chieftain.

[[v26-48-23]]

^<<v26-48-23,23>>^ “And as regards the rest of the tribes, from the eastern border to the western border, Benjamin one &#91;portion&#93;.

[[v26-48-24]]

^<<v26-48-24,24>>^ And by the boundary of Benjamin, from the eastern border to the western border, Simʹe·on one.

[[v26-48-25]]

^<<v26-48-25,25>>^ And by the boundary of Simʹe·on, from the eastern border to the western border, Isʹsa·char one.

[[v26-48-26]]

^<<v26-48-26,26>>^ And by the boundary of Isʹsa·char, from the eastern border to the western border, Zebʹu·lun one.

[[v26-48-27]]

^<<v26-48-27,27>>^ And by the boundary of Zebʹu·lun, from the eastern border to the western border, Gad one.

[[v26-48-28]]

^<<v26-48-28,28>>^ And by the boundary of Gad, to the southern^&#42;1^ border, it will be southward;^&#42;2^ and the boundary must prove to be from Taʹmar to the waters of Merʹi·bath-kaʹdesh, to the torrent valley, as far as the Great Sea.

[NOTE]
====
. “Southern.” Heb., neʹghev.
. “Southward.” Heb., teh·maʹnah.
====

[[v26-48-29]]

^<<v26-48-29,29>>^ “This will be the land that YOU people should cause to fall &#91;by lot&#93; for inheritance to the tribes of Israel, and these will be their shares,” is the utterance of the Sovereign Lord Jehovah.

[[v26-48-30]]

^<<v26-48-30,30>>^ “And these will be the outlets of the city: On the northern border, four thousand five hundred &#91;cubits&#93; will be &#91;the&#93; measurement.

[[v26-48-31]]

^<<v26-48-31,31>>^ “And the gates of the city will be according to the names of the tribes of Israel, three gates being on the north, the gate of Reuʹben, one; the gate of Judah, one; the gate of Leʹvi, one.

[[v26-48-32]]

^<<v26-48-32,32>>^ “And on the eastern border there will be four thousand five hundred &#91;cubits&#93;, and three gates, even the gate of Joseph, one; the gate of Benjamin, one; the gate of Dan, one.

[[v26-48-33]]

^<<v26-48-33,33>>^ “And the southern border will be four thousand five hundred &#91;cubits&#93; as to measurement, with three gates, the gate of Simʹe·on, one; the gate of Isʹsa·char, one; the gate of Zebʹu·lun, one.

[[v26-48-34]]

^<<v26-48-34,34>>^ “The western border will be four thousand five hundred &#91;cubits&#93;, there being three gates, the gate of Gad, one; the gate of Ashʹer, one; the gate of Naphʹta·li, one.

[[v26-48-35]]

^<<v26-48-35,35>>^ “Round about &#91;there will be&#93; eighteen thousand &#91;cubits&#93;; and the name of the city from &#91;that&#93; day on will be Jehovah Himself Is There.”^&#42;1^

[NOTE]
====
. “Jehovah Himself Is There.” Or, “Jehovah-Shammah.” Heb., Yehwahʹ Shamʹmah; LXXAVg, “Jehovah [Is] There.”
====

'''

xref:026-ezekiel/026-ezekiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]