include::./index.adoc[]

[[v26-29-0]]
=== Ezekiel, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-29-1]]

^<<v26-29-1,1>>^ In the tenth year, in the tenth &#91;month&#93;, on the twelfth &#91;day&#93; of the month, the word of Jehovah occurred to me, saying:

[[v26-29-2]]

^<<v26-29-2,2>>^ “Son of man, set your face against Pharʹaoh the king of Egypt and prophesy against him and against Egypt in its entirety.

[[v26-29-3]]

^<<v26-29-3,3>>^ Speak, and you must say, ‘This is what the Sovereign Lord Jehovah has said: “Here I am against you, O Pharʹaoh, king of Egypt, the great sea monster lying stretched out in the midst of his Nile canals, that has said, ‘My Nile River belongs to me, and I—I have made &#91;it&#93; for myself.’

[[v26-29-4]]

^<<v26-29-4,4>>^ And I will put hooks^&#42;1^ in your jaws and cause the fish of your Nile canals to cling to your scales. And I will bring you up out of the midst of your Nile canals and all the fish of your Nile canals that cling to your very scales.

[NOTE]
====
. Or, “thorns”; put through the cheek or nose of animals as well as of captives in order to lead them on a rope.
====

[[v26-29-5]]

^<<v26-29-5,5>>^ And I will abandon you to the wilderness, you and all the fish of your Nile canals. Upon the surface of the field you will fall. You will not be gathered up nor be collected together. To the wild beasts of the earth and to the flying creatures of the heavens I will give you for food.

[[v26-29-6]]

^<<v26-29-6,6>>^ And all the inhabitants of Egypt will have to know that I am Jehovah, for the reason that they^&#42;1^ proved to be, as a support, a reed to the house of Israel.

[NOTE]
====
. “They,” MT; LXXSyVg, “you.”
====

[[v26-29-7]]

^<<v26-29-7,7>>^ When they took hold of you by the hand,^&#42;1^ you got to be crushed, and you caused a split in their entire shoulder.^&#42;2^ And when they supported themselves upon you, you got to be broken, and you caused all their hips to wobble.”^&#42;3^

[NOTE]
====
. “The hand,” MmarginVg and many Heb. mss; M, “your hand”; LXXSy, “their hand.”
. “Shoulder,” MVg; Sy, “hands.”
. “Wobble,” Sy; M, “stand.”
====

[[v26-29-8]]

^<<v26-29-8,8>>^ “‘Therefore this is what the Sovereign Lord Jehovah has said: “Here I am bringing upon you a sword, and I will cut off from you earthling man and domestic animal.

[[v26-29-9]]

^<<v26-29-9,9>>^ And the land of Egypt must become a desolate waste and a devastated place; and they will have to know that I am Jehovah, for the reason that he has said, ‘To me the Nile River belongs, and I myself have made &#91;it&#93;.’

[[v26-29-10]]

^<<v26-29-10,10>>^ Therefore here I am against you and against your Nile canals, and I will make the land of Egypt devastated places, dryness, a desolated waste, from Migʹdol to Sy·eʹne^&#42;1^ and to the boundary of E·thi·oʹpi·a.^&#42;2^

[NOTE]
====
. Or, “Aswān.” Heb., Sewe·nehʹ.
. “Ethiopia,” Vg; LXX, “the Ethiopians”; MTSy, “Cush.”
====

[[v26-29-11]]

^<<v26-29-11,11>>^ There will not pass through it the foot of earthling man, nor will the foot of domestic animal pass through it, and for forty years it will not be inhabited.

[[v26-29-12]]

^<<v26-29-12,12>>^ And I will make the land of Egypt a desolate waste in the midst of desolated lands; and its own cities will become a desolate waste in the very midst of devastated cities for forty years; and I will scatter the Egyptians among the nations and disperse them among the lands.”

[[v26-29-13]]

^<<v26-29-13,13>>^ “‘For this is what the Sovereign Lord Jehovah has said: “At the end of forty years I shall collect the Egyptians together out of the peoples among whom they will have been scattered,

[[v26-29-14]]

^<<v26-29-14,14>>^ and I will bring back the captive group of the Egyptians; and I will bring them back to the land of Pathʹros, to the land of their origin, and there they must become a lowly kingdom.

[[v26-29-15]]

^<<v26-29-15,15>>^ Lower than the &#91;other&#93; kingdoms it will become, and it will no more lift itself up over the &#91;other&#93; nations, and I will make them so few as not to have the &#91;other&#93; nations in subjection.

[[v26-29-16]]

^<<v26-29-16,16>>^ And it will no more prove to be the house of Israel’s confidence, bringing error to remembrance by their turning after them. And they will have to know that I am the Sovereign Lord Jehovah.”’”

[[v26-29-17]]

^<<v26-29-17,17>>^ Now it came about in the twenty-seventh year, in the first &#91;month&#93;, on the first &#91;day&#93; of the month, that the word of Jehovah occurred to me, saying:

[[v26-29-18]]

^<<v26-29-18,18>>^ “Son of man, Neb·u·chad·rezʹzar himself, the king of Babylon,^&#42;1^ made his military force perform a great service against Tyre. Every head was one made bald, and every shoulder was one rubbed bare. But as for wages, there proved to be none for him and his military force from Tyre for the service that he had performed against her.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v26-29-19]]

^<<v26-29-19,19>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Here I am giving to Neb·u·chad·rezʹzar the king of Babylon the land of Egypt, and he must carry off its wealth and make a big spoil of it and do a great deal of plundering of it; and it must become wages for his military force.’

[[v26-29-20]]

^<<v26-29-20,20>>^ “‘As his compensation for service that he did against her I have given him the land of Egypt, because they acted for me,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-29-21]]

^<<v26-29-21,21>>^ “In that day I shall cause a horn to sprout for the house of Israel, and to you I shall give occasion to open the mouth in the midst of them; and they will have to know that I am Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezekiel/026-ezekiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]