include::./index.adoc[]

[[v26-22-0]]
=== Ezekiel, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-22-1]]

^<<v26-22-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-22-2]]

^<<v26-22-2,2>>^ “And as for you, O son of man, will you judge, will you judge the bloodguilty city^&#42;1^ and certainly cause her to know all her detestable things?

[NOTE]
====
. Lit., “the city of the bloods.”
====

[[v26-22-3]]

^<<v26-22-3,3>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said: “O city that is shedding blood in her midst till her time comes, and that has made dungy idols within herself in order to become unclean,

[[v26-22-4]]

^<<v26-22-4,4>>^ by your blood that you have shed you have become guilty, and by your dungy idols that you have made you have become unclean. And you bring your days near, and you will come to your years. That is why I must make you an object of reproach to the nations and of jeering to all the lands.

[[v26-22-5]]

^<<v26-22-5,5>>^ The &#91;lands&#93; nearby and those far away from you will jeer you, O you unclean in name, abounding in confusion.

[[v26-22-6]]

^<<v26-22-6,6>>^ Look! The chieftains of Israel have proved to be in you, each one &#91;given over&#93; to his arm for the purpose of shedding blood.

[[v26-22-7]]

^<<v26-22-7,7>>^ Father and mother they have treated with contempt in you. Toward the alien resident they have acted with defrauding in the midst of you. Fatherless boy and widow they have maltreated in you.”’”

[[v26-22-8]]

^<<v26-22-8,8>>^ “‘My holy places you have despised, and my sabbaths you have profaned.

[[v26-22-9]]

^<<v26-22-9,9>>^ Outright slanderers^&#42;1^ have proved to be in you, for the purpose of shedding blood; and on the mountains they have eaten in you. Loose conduct they have carried on in the midst of you.

[NOTE]
====
. Lit., “men of slander.” Heb., ʼan·shehʹ ra·khilʹ.
====

[[v26-22-10]]

^<<v26-22-10,10>>^ The nakedness of a father they have uncovered^&#42;1^ in you; a woman unclean in &#91;her&#93; menstruation they have humiliated in you.

[NOTE]
====
. Lit., “one [or, he] has uncovered.”
====

[[v26-22-11]]

^<<v26-22-11,11>>^ And with the wife of his companion a man has done a detestable thing, and his own daughter-in-law a man has defiled with loose conduct; and his sister, the daughter of his own father, a man has humiliated in you.

[[v26-22-12]]

^<<v26-22-12,12>>^ A bribe they have taken in you for the purpose of shedding blood. Interest and usury you have taken, and you violently keep making gain of your companions with defrauding, and me you have forgotten,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-22-13]]

^<<v26-22-13,13>>^ “‘And, look! I have struck my hand at your unjust gain that you have made, and over your acts of bloodshed^&#42;1^ that have proved to be in the midst of you.

[NOTE]
====
. Lit., “your blood,” sing. but the subject of a pl. verb.
====

[[v26-22-14]]

^<<v26-22-14,14>>^ Will your heart keep enduring or your hands furnish strength in the days when I am taking action toward you? I myself, Jehovah, have spoken and I will take action.

[[v26-22-15]]

^<<v26-22-15,15>>^ And I will scatter you among the nations and disperse you among the lands, and I will destroy^&#42;1^ your uncleanness^&#42;2^ out of you.

[NOTE]
====
. Lit., “terminate.”
. “Your uncleanness.” Heb., tum·ʼa·thekhʹ; Gr., a·ka·thar·siʹa. See 2Co 12:21 and Ga 5:19 ftns, “Uncleanness.”
====

[[v26-22-16]]

^<<v26-22-16,16>>^ And you will certainly be profaned within yourself before the eyes of &#91;the&#93; nations, and you will have to know that I am Jehovah.’”

[[v26-22-17]]

^<<v26-22-17,17>>^ And the word of Jehovah continued to come to me, saying:

[[v26-22-18]]

^<<v26-22-18,18>>^ “Son of man, to me those of the house of Israel have become as scummy dross. All of them are copper and tin and iron and lead in the midst of a furnace. Much scummy dross, &#91;that of&#93; silver, they have become.

[[v26-22-19]]

^<<v26-22-19,19>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘For the reason that all of YOU have become as much scummy dross, therefore here I am collecting YOU together into the midst of Jerusalem.

[[v26-22-20]]

^<<v26-22-20,20>>^ As in collecting silver and copper and iron and lead and tin into the midst of a furnace, in order to blow upon it with fire to cause a liquefying, so I shall collect &#91;them&#93; together in my anger and in my rage, and I will blow^&#42;1^ and cause YOU people to liquefy.

[NOTE]
====
. “Blow,” by a correction; M, “deposit,” without an object.
====

[[v26-22-21]]

^<<v26-22-21,21>>^ And I will bring YOU together and blow upon YOU with the fire of my fury, and YOU must be liquefied in the midst of her.^&#42;1^

[NOTE]
====
. Or, “it,” fem., referring to the city of Jerusalem.
====

[[v26-22-22]]

^<<v26-22-22,22>>^ As in the liquefying of silver in the midst of a furnace, so YOU people will be liquefied in the midst of her; and YOU will have to know that I myself, Jehovah, have poured out my rage upon YOU.’”

[[v26-22-23]]

^<<v26-22-23,23>>^ And the word of Jehovah continued to come to me, saying:

[[v26-22-24]]

^<<v26-22-24,24>>^ “Son of man, say to her, ‘You are a land not being cleansed, one not rained down upon in the day of denunciation.

[[v26-22-25]]

^<<v26-22-25,25>>^ There is a conspiracy of her prophets in the midst of her, like the roaring lion, tearing prey. A soul they actually devour. Treasure and precious things they keep taking. Her widows they have multiplied in the midst of her.

[[v26-22-26]]

^<<v26-22-26,26>>^ Her priests themselves have done violence to my law, and they keep profaning my holy places. Between the holy thing and the common^&#42;1^ they have made no distinction, and between the unclean thing and the clean they have made nothing known, and from my sabbaths they have hidden their eyes, and I am profaned in the midst of them.

[NOTE]
====
. Or, “profane.”
====

[[v26-22-27]]

^<<v26-22-27,27>>^ Her princes in the midst of her are like wolves tearing prey in shedding blood, in destroying souls^&#42;1^ for the purpose of making unjust gain.

[NOTE]
====
. “Souls.” Heb., nepha·shohthʹ; Lat., aʹni·mas. See App 4A.
====

[[v26-22-28]]

^<<v26-22-28,28>>^ And her prophets have plastered for them with whitewash, visioning an unreality and divining for them a lie, saying: “This is what the Sovereign Lord Jehovah has said,” when Jehovah himself has not spoken.

[[v26-22-29]]

^<<v26-22-29,29>>^ The people of the land themselves have carried on a scheme of defrauding and have done a tearing away in robbery, and the afflicted one and the poor one they have maltreated, and the alien resident they have defrauded without justice.’

[[v26-22-30]]

^<<v26-22-30,30>>^ “‘And I kept looking for a man^&#42;1^ from among them who would be repairing the stone wall and standing in the gap before me in behalf of the land, in order &#91;for me&#93; not to bring it to ruin; and I found no one.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v26-22-31]]

^<<v26-22-31,31>>^ So I shall pour out my denunciation upon them. With the fire of my fury I will exterminate them. Their way I will bring upon their own head,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezekiel/026-ezekiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]