include::./index.adoc[]

[[v26-8-0]]
=== Ezekiel, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-8-1]]

^<<v26-8-1,1>>^ And it came about in the sixth year, in the sixth &#91;month&#93;, on the fifth day of the month, that I was sitting in my house and the older men^&#42;1^ of Judah were sitting before me, when the hand of the Sovereign Lord Jehovah fell upon me there.

[NOTE]
====
. Or, “elders.”
====

[[v26-8-2]]

^<<v26-8-2,2>>^ And I began to see, and, look! a likeness similar to the appearance of fire; from the appearance of his hips even downward there was fire, and from his hips even upward there was something like the appearance of a shining, like the glow of electrum.^&#42;1^

[NOTE]
====
. See 1:4 ftn, “Electrum.”
====

[[v26-8-3]]

^<<v26-8-3,3>>^ Then he thrust out the representation of a hand and took me by a tuft of hair of my head, and a spirit^&#42;1^ carried me between the earth and the heavens and brought me to Jerusalem in the visions of God, to the entrance of the inner gate that is facing northward, where the dwelling place is of the symbol of jealousy that is inciting to jealousy.

[NOTE]
====
. “A spirit.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. Compare Ge 1:2 ftn, “Force.”
====

[[v26-8-4]]

^<<v26-8-4,4>>^ And, look! the glory of the God^&#42;1^ of Israel was there, like the appearance that I had seen in the valley plain.

[NOTE]
====
. “God of.” Heb., ʼElo·hehʹ, pl.
====

[[v26-8-5]]

^<<v26-8-5,5>>^ And he proceeded to say to me: “Son of man, please, raise your eyes in the direction of the north.” So I raised my eyes in the direction of the north, and, look! to the north of the gate of the altar there was this symbol^&#42;1^ of jealousy^&#42;2^ in the entranceway.

[NOTE]
====
. “The gate of the altar there was this symbol [Heb., seʹmel, “image”],” M; by substitution of a similar letter in M in harmony with LXXSy, “the gate toward the sunrising . . .”; by a slight change in vowel pointing in M, “the gate, there was the altar of this symbol.”
. “This . . . jealousy.” Heb., haq·qin·ʼahʹ haz·zehʹ. See Ex 34:14 ftns.
====

[[v26-8-6]]

^<<v26-8-6,6>>^ And he went on to say to me: “Son of man, are you seeing what great detestable things they are doing, the things that the house of Israel are doing here &#91;for me&#93; to become far off from my sanctuary? And yet you will see again great detestable things.”

[[v26-8-7]]

^<<v26-8-7,7>>^ Accordingly he brought me to the entrance of the courtyard, and I began to see, and, look! a certain hole in the wall.

[[v26-8-8]]

^<<v26-8-8,8>>^ He now said to me: “Son of man, bore, please, through the wall.” And I gradually bored through the wall, and, look! there was a certain entrance.

[[v26-8-9]]

^<<v26-8-9,9>>^ And he further said to me: “Go in and see the bad detestable things that they are doing here.”

[[v26-8-10]]

^<<v26-8-10,10>>^ So I went in and began to see, and, look! there was every representation of creeping things and loathsome beasts, and all the dungy idols of the house of Israel, the carving being upon the wall all round about.

[[v26-8-11]]

^<<v26-8-11,11>>^ And seventy men^&#42;1^ of the elderly ones of the house of Israel, with Ja·az·a·niʹah^&#42;2^ the son of Shaʹphan standing in among them, were standing before them, each one with his censer in his hand, and the perfume of the cloud of the incense was ascending.

[NOTE]
====
. “Men of.” Heb., ʼish.
. “With Jaazaniah.” Heb., weYa·ʼazan·yaʹhu, meaning “Jehovah Gives Ear.”
====

[[v26-8-12]]

^<<v26-8-12,12>>^ And he proceeded to say to me: “Have you seen, O son of man, what the elderly ones of the house of Israel are doing in the darkness, each one in the inner rooms of his showpiece? For they are saying, ‘Jehovah is not seeing us.^&#42;1^ Jehovah has left the land.’”^&#42;2^

[NOTE]
====
. Or, “There is no Jehovah seeing us.”
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v26-8-13]]

^<<v26-8-13,13>>^ And he continued on to say to me: “You will yet see again great detestable things that they are doing.”

[[v26-8-14]]

^<<v26-8-14,14>>^ So he brought me to the entrance of the gate of the house of Jehovah, which is toward the north, and, look! there the women were sitting, weeping over the &#91;god&#93; Tamʹmuz.^&#42;1^

[NOTE]
====
. “The [god] Tammuz.” Heb., hat·Tam·muzʹ; Gr., ton Tham·mouzʹ; Lat., A·doʹni·dem.
====

[[v26-8-15]]

^<<v26-8-15,15>>^ And he further said to me: “Have you seen &#91;this&#93;, O son of man? You will yet see again great detestable things worse than these.”

[[v26-8-16]]

^<<v26-8-16,16>>^ So he brought me to the inner courtyard of the house of Jehovah, and, look! at the entrance of the temple of Jehovah, between the porch and the altar, there were about twenty-five men^&#42;1^ with their backs to the temple^&#42;2^ of Jehovah and their faces to the east, and they were bowing down to the east, to the sun.

[NOTE]
====
. “Men.” Heb., ʼish.
. See 41:1 ftn, “Temple.”
====

[[v26-8-17]]

^<<v26-8-17,17>>^ And he went on to say to me: “Have you seen &#91;this&#93;, O son of man? Is it such a light thing to the house of Judah to do the detestable things that they have done here, that they have to fill the land^&#42;1^ with violence and that they should offend me again, and here they are thrusting out the shoot^&#42;2^ to my nose?^&#42;3^

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
. Or, “the branch (twig).” Heb., haz·zemoh·rahʹ; doubtless used in idolatrous worship. It may represent the human male organ.
. “My nose,” in the original Heb. text; M, “their nose.” One of the Eighteen Emendations of the Sopherim to avoid an apparent derogatory reference to Jehovah. See App 2B.
====

[[v26-8-18]]

^<<v26-8-18,18>>^ And I myself also shall act in rage. My eye will not feel sorry, neither shall I feel compassion. And they will certainly call out in my ears with a loud voice, but I shall not hear them.”

'''

xref:026-ezekiel/026-ezekiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezekiel/026-ezekiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]