include::./index.adoc[]

[[v26-40-0]]
=== Ezekiel, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-40-1]]

^<<v26-40-1,1>>^ In the twenty-fifth year of our exile, in the start of the year, on the tenth &#91;day&#93; of the month, in the fourteenth year after the city had been struck down, on this very same day the hand of Jehovah proved to be upon me, so that he brought me to that place.

[[v26-40-2]]

^<<v26-40-2,2>>^ In the visions of God^&#42;1^ he brought me to the land of Israel and gradually set me down upon a very high mountain, on which there was something like the structure of a city to the south.^&#42;2^

[NOTE]
====
. “In the visions of God.” Heb., bemar·ʼohthʹ ʼElo·himʹ.
. Or, “toward the Negeb.”
====

[[v26-40-3]]

^<<v26-40-3,3>>^ And he proceeded to bring me there, and, look! there was a man.^&#42;1^ His appearance was like the appearance of copper, and there was a flax cord in his hand, and a measuring reed, and he was standing in the gate.^&#42;2^

[NOTE]
====
. “Man.” Heb., ʼish; Gr., a·nerʹ; Lat., vir.
. Or, “gateway,” according to its description.
====

[[v26-40-4]]

^<<v26-40-4,4>>^ And the man began to speak to me: “Son of man,^&#42;1^ see with your eyes, and with your ears hear, and set your heart upon all that I am showing you, because for the purpose of &#91;my&#93; showing you, you have been brought here. Tell everything that you are seeing to the house of Israel.”

[NOTE]
====
. “Son of man.” Heb., ben-ʼa·dhamʹ; Gr., hui·eʹ an·throʹpou; Lat., fiʹli hoʹmi·nis.
====

[[v26-40-5]]

^<<v26-40-5,5>>^ And, look! there was a wall outside the house all round about. And in the hand of the man there was the measuring reed^&#42;1^ of six cubits, by a cubit and a handbreadth.^&#42;2^ And he began to measure the breadth of the thing built,^&#42;3^ one reed; and the height, one reed.

[NOTE]
====
. “The measuring reed.” Heb., qenehʹ ham·mid·dahʹ; Gr., kaʹla·mos; Lat., caʹla·mus men·suʹrae. Compare Ga 6:16 ftn, “Conduct”; Re 11:1.
. “A cubit and a handbreadth.” A cubit of 44.5 cm (17.5 in.) and a handbreadth of 7.4 cm (2.9 in.) equaled about 51.8 cm (20.4 in.) and represented the long cubit. Hence, a “measuring reed of six cubits” equaled 3.11 m (10.2 ft).
. “The thing built.” Heb., hab·bin·yanʹ; LXX, “outer (advance) wall.”
====

[[v26-40-6]]

^<<v26-40-6,6>>^ Then he came to the gate, the front of which is toward the east, and went up by its steps. And he began to measure the threshold of the gate, one reed in width, and the other threshold, one reed in width.

[[v26-40-7]]

^<<v26-40-7,7>>^ And the guard chamber was one reed in length and one reed in width, and between the guard chambers there were five cubits; and the threshold of the gate beside the porch of the gate toward the interior was one reed.

[[v26-40-8]]

^<<v26-40-8,8>>^ And he proceeded to measure the porch of the gate toward the interior, one reed.

[[v26-40-9]]

^<<v26-40-9,9>>^ So he measured the porch of the gate, eight cubits; and its side pillars,^&#42;1^ two cubits; and the porch of the gate was toward the interior.

[NOTE]
====
. Or, “projections.”
====

[[v26-40-10]]

^<<v26-40-10,10>>^ And the guard chambers of the gate toward the east were three on this side and three on that side. The three of them were of the same measurement, and the side pillars were of the same measurement, on this side and on that side.

[[v26-40-11]]

^<<v26-40-11,11>>^ Then he measured the width of the entrance of the gate, ten cubits; the length of the gate, thirteen cubits.

[[v26-40-12]]

^<<v26-40-12,12>>^ And the fenced area in front of the guard chambers was one cubit, and there was a fenced area of one cubit on &#91;either&#93; side. And the guard chamber was six cubits on this side and six cubits on that side.

[[v26-40-13]]

^<<v26-40-13,13>>^ And he went on to measure the gate from the roof of the &#91;one&#93; guard chamber to the roof of the other, a width of twenty-five cubits; entrance was across from entrance.

[[v26-40-14]]

^<<v26-40-14,14>>^ Then he made side pillars of sixty cubits, even to the side pillar&#91;s&#93; of the courtyard in the gate&#91;s&#93; all around.^&#42;1^

[NOTE]
====
. “And the open part of the porch of the gate on the outside was twenty cubits, the chambers of the gate being round about,” LXXB.
====

[[v26-40-15]]

^<<v26-40-15,15>>^ And by the front of the gate of the entryway &#91;to&#93; by the front of the porch of the inner gate was fifty cubits.

[[v26-40-16]]

^<<v26-40-16,16>>^ And there were windows of narrowing frames for the guard chambers and for their side pillars toward the inside of the gate all around, and that is the way it was for the porches. And the windows were all around toward the inside, and on the side pillars there were palm-tree figures.

[[v26-40-17]]

^<<v26-40-17,17>>^ And he gradually brought me into the outer courtyard, and, look! there were dining rooms, and a pavement made for the courtyard all around. There were thirty dining rooms upon the pavement.

[[v26-40-18]]

^<<v26-40-18,18>>^ And the pavement at the side of the gates was exactly as the length of the gates—the lower pavement.

[[v26-40-19]]

^<<v26-40-19,19>>^ And he proceeded to measure the width from in front of the lower gate to the front of the inner courtyard. Outside it was a hundred cubits, to the east and to the north.

[[v26-40-20]]

^<<v26-40-20,20>>^ And the outer courtyard had a gate the front of which was toward the north. He measured its length and its width.

[[v26-40-21]]

^<<v26-40-21,21>>^ And its guard chambers were three on this side and three on that side. And its own side pillars and its own porch proved to be according to the measurement of the first gate. Fifty cubits was its length, and its width was twenty-five in cubits.

[[v26-40-22]]

^<<v26-40-22,22>>^ And its windows and its porch and its palm-tree figures were of the same measurement as those of the gate the front of which is toward the east. And by seven steps people could go up into it, and its porch was to their front.

[[v26-40-23]]

^<<v26-40-23,23>>^ And the gate of the inner courtyard was opposite the gate to the north; also &#91;one&#93; to the east. And he proceeded to measure from gate to gate a hundred cubits.

[[v26-40-24]]

^<<v26-40-24,24>>^ And he gradually brought me toward the south,^&#42;1^ and, look! there was a gate toward the south, and he measured its side pillars and its porch as of the same measurements as these.

[NOTE]
====
. “The south.” Heb., had·da·rohmʹ.
====

[[v26-40-25]]

^<<v26-40-25,25>>^ And it and its porch had windows all around, like these windows. Fifty cubits was the length, and the breadth was twenty-five cubits.

[[v26-40-26]]

^<<v26-40-26,26>>^ And there were seven steps for going up to it, and its porch was to their front. And it had palm-tree figures, one on this side and one on that side on its side pillars.

[[v26-40-27]]

^<<v26-40-27,27>>^ And the inner courtyard had a gate toward the south. And he measured from gate to gate toward the south a hundred cubits.

[[v26-40-28]]

^<<v26-40-28,28>>^ And he gradually brought me into the inner courtyard by the gate of the south. And he proceeded to measure the gate of the south as of the same measurements as these.

[[v26-40-29]]

^<<v26-40-29,29>>^ And its guard chambers and its side pillars and its porch were of the same measurements as these. And it and its porch had windows round about. Fifty cubits was the length, and the width was twenty-five cubits.

[[v26-40-30]]

^<<v26-40-30,30>>^ ^&#42;1^ And there were porches all around; the length was twenty-five cubits, and the width five cubits.

[NOTE]
====
. Vs 30, not found in LXXIt and some Heb. mss, is considered a dittography of vs 29.
====

[[v26-40-31]]

^<<v26-40-31,31>>^ And its porch was to the outer courtyard, and palm-tree figures were on its side pillars, and its ascent was eight steps.

[[v26-40-32]]

^<<v26-40-32,32>>^ And he gradually brought me into the inner courtyard by way of the east, and he proceeded to measure the gate as of the same measurements as these.

[[v26-40-33]]

^<<v26-40-33,33>>^ And its guard chambers and its side pillars and its porch were of the same measurements as these, and it and its porch had windows all around. The length was fifty cubits, and the width twenty-five cubits.

[[v26-40-34]]

^<<v26-40-34,34>>^ And its porch was toward the outer courtyard, and palm-tree figures were on its side pillars on this side and on that side. And its ascent was eight steps.

[[v26-40-35]]

^<<v26-40-35,35>>^ And he proceeded to bring me into the north gate, and he measured, with the same measurements as these,

[[v26-40-36]]

^<<v26-40-36,36>>^ its guard chambers, its side pillars and its porch. And it had windows all around. The length was fifty cubits, and the width twenty-five cubits.

[[v26-40-37]]

^<<v26-40-37,37>>^ And to the outer courtyard were its side pillars, and palm-tree figures were on its side pillars on this side and on that side. And its ascent was eight steps.

[[v26-40-38]]

^<<v26-40-38,38>>^ And a dining room with its entrance was by the side pillars of the gates. There it was that they would rinse the whole burnt offering.

[[v26-40-39]]

^<<v26-40-39,39>>^ And in the porch of the gate there were two tables on this side and two tables on that side, for slaughtering upon them the whole burnt offering and the sin offering and the guilt offering.

[[v26-40-40]]

^<<v26-40-40,40>>^ And on the outer side, as one goes up to the entrance of the north gate, there were two tables. And on the other side that belongs to the porch of the gate there were two tables.

[[v26-40-41]]

^<<v26-40-41,41>>^ There were four tables over here and four tables over there at the side of the gate—eight tables, upon which they would do the slaughtering.

[[v26-40-42]]

^<<v26-40-42,42>>^ And the four tables^&#42;1^ for the whole burnt offering were of hewn stone. The length was one cubit and a half, and the width one cubit and a half, and the height one cubit. Upon them they would also deposit the implements with which they would slaughter the whole burnt offering and the sacrifice.

[NOTE]
====
. The exact location of these four tables at the north gate is not stated.
====

[[v26-40-43]]

^<<v26-40-43,43>>^ And the ledges for setting down things were of one handbreadth, firmly fixed on the interior, all around; and upon the tables &#91;they would deposit&#93;^&#42;1^ the flesh of the gift offering.^&#42;2^

[NOTE]
====
. “They would deposit,” Sy; MVg omit.
. “The gift offering.” Heb., haq·qor·vanʹ; Lat., ob·la·ti·oʹnis. See Mr 7:11.
====

[[v26-40-44]]

^<<v26-40-44,44>>^ And on the outside of the inner gate there were the dining rooms of the singers, in the inner courtyard, which is on the side of the north gate. And their front side was toward the south. There was one on the side of the east^&#42;1^ gate. The front was toward the north.

[NOTE]
====
. “East,” MTSyVg; LXX, “south.”
====

[[v26-40-45]]

^<<v26-40-45,45>>^ And he proceeded to speak to me: “This one, the dining room the front of which is toward the south, is for the priests who are taking care of the obligation of the house.

[[v26-40-46]]

^<<v26-40-46,46>>^ And the dining room the front of which is toward the north is for the priests who are taking care of the obligation of the altar. They are the sons of Zaʹdok, who, from the sons of Leʹvi, are approaching Jehovah to minister to him.”

[[v26-40-47]]

^<<v26-40-47,47>>^ And he went measuring the &#91;inner&#93; courtyard. The length was a hundred cubits, and the width a hundred cubits, foursquare. And the altar was before the house.

[[v26-40-48]]

^<<v26-40-48,48>>^ And he proceeded to bring me into the porch of the house, and he went measuring the side pillar of the porch, five cubits on this side and five cubits on that side. And the width of the gate was three cubits on this side and three cubits on that side.

[[v26-40-49]]

^<<v26-40-49,49>>^ The length of the porch was twenty cubits, and the width eleven^&#42;1^ cubits. And by steps was how they would go up to it.^&#42;2^ And there were pillars by the side posts, one over here and one over there.

[NOTE]
====
. “Eleven,” MTSyVg; LXX, “twelve.”
. “And upon ten steps they would go up to it,” LXX; Vg, “And by eight steps there would be an ascent to it.”
====

'''

xref:026-ezekiel/026-ezekiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezekiel/026-ezekiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]