include::./index.adoc[]

[[v26-46-0]]
=== Ezekiel, 46
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-46-1]]

^<<v26-46-1,1>>^ “This is what the Sovereign Lord Jehovah has said, ‘As regards the gate of the inner courtyard that is facing east, it should continue shut for the six workdays, and on the sabbath day it should be opened, and on the day of the new moon it should be opened.

[[v26-46-2]]

^<<v26-46-2,2>>^ And the chieftain must come in by the way of the porch of the gate, from outside, and stand by the doorpost of the gate; and the priests must render up his whole burnt offering and his communion sacrifices, and he must bow down upon the threshold of the gate, and he must go out, but the gate itself should not be shut until the evening.

[[v26-46-3]]

^<<v26-46-3,3>>^ And the people of the land^&#42;1^ must bow down at the entrance of that gate on the sabbaths and on the new moons, before Jehovah.

[NOTE]
====
. See 7:27 ftn.
====

[[v26-46-4]]

^<<v26-46-4,4>>^ “‘And the whole burnt offering that the chieftain should present to Jehovah on the sabbath day should be six sound male lambs and a sound ram;

[[v26-46-5]]

^<<v26-46-5,5>>^ and as a grain offering an eʹphah for the ram, and for the male lambs a grain offering as he is able to give,^&#42;1^ and, as regards oil, a hin to the eʹphah.

[NOTE]
====
. Lit., “as the gift of his hand.”
====

[[v26-46-6]]

^<<v26-46-6,6>>^ And on the day of the new moon there should be a young bull, the son of the herd, a sound one, and six male lambs and a ram; sound ones they should prove to be.

[[v26-46-7]]

^<<v26-46-7,7>>^ And an eʹphah for the young bull and an eʹphah for the ram he should render up as a grain offering, and for the male lambs according to what he is able to afford;^&#42;1^ and, as regards oil, a hin to the eʹphah.

[NOTE]
====
. Lit., “what his hand may attain to (may reach).” See Le 5:7 ftn, “Afford.”
====

[[v26-46-8]]

^<<v26-46-8,8>>^ “‘And when the chieftain comes in, by the way of the porch of the gate he should come in, and by the way of it he should go out.

[[v26-46-9]]

^<<v26-46-9,9>>^ And when the people of the land come in before Jehovah in the festal seasons, the one coming in by the way of the north gate in order to bow down should go out by the way of the south gate; and the one coming in by the way of the south gate should go out by the way of the gate to the north. No one should go back by the way of the gate by which he came in, for he^&#42;1^ should go out straight ahead of him.

[NOTE]
====
. “He,” MmarginTLXXSyVg and over 100 Heb. mss; M, “they.”
====

[[v26-46-10]]

^<<v26-46-10,10>>^ And as regards the chieftain in their midst, when they come in, he should come in; and when they go out, he^&#42;1^ should go out.

[NOTE]
====
. “He,” TLXXSyVg and 37 Heb. mss; M, “they.”
====

[[v26-46-11]]

^<<v26-46-11,11>>^ And in the festivals and in the festal seasons the grain offering should prove to be an eʹphah for the young bull and an eʹphah for the ram, and for the male lambs as he is able to give;^&#42;1^ and, as regards oil, a hin to the eʹphah.

[NOTE]
====
. See vs 5 ftn.
====

[[v26-46-12]]

^<<v26-46-12,12>>^ “‘And in case the chieftain should provide as a voluntary offering a whole burnt offering, or communion sacrifices as a voluntary offering to Jehovah, one must also open to him the gate that is facing east, and he must provide his whole burnt offering and his communion sacrifices just as he does on the sabbath day. And he must go out, and one must shut the gate after his going out.

[[v26-46-13]]

^<<v26-46-13,13>>^ “‘And a sound male lamb, in its first year,^&#42;1^ you^&#42;2^ should provide as a whole burnt offering daily to Jehovah. Morning by morning you^&#42;3^ should provide it.

[NOTE]
====
. Lit., “male lamb, a son of its year.” See Le 12:6; 14:10.
. “You,” MT; LXXSyVg and some Heb. mss, “he.”
. “You,” MT; LXXVg, “he.”
====

[[v26-46-14]]

^<<v26-46-14,14>>^ And as a grain offering you^&#42;1^ should provide with it morning by morning the sixth of an eʹphah and, as regards oil, the third of a hin for sprinkling the fine flour. The grain offering to Jehovah is an indefinitely lasting statute, constantly.

[NOTE]
====
. “You,” MT; LXXSyVg and two Heb. mss, “he.”
====

[[v26-46-15]]

^<<v26-46-15,15>>^ And they must provide the male lamb and the grain offering and the oil morning by morning as a constant^&#42;1^ whole burnt offering.’

[NOTE]
====
. Or, “continual.” Heb., ta·midhʹ. Compare Da 8:11 ftn.
====

[[v26-46-16]]

^<<v26-46-16,16>>^ “This is what the Sovereign Lord Jehovah has said, ‘In case the chieftain should give a gift to each one^&#42;1^ of his sons as his inheritance, it itself will become the property of his sons themselves. It is their possession by inheritance.

[NOTE]
====
. Lit., “to a man.” Heb., leʼishʹ.
====

[[v26-46-17]]

^<<v26-46-17,17>>^ And in case he should give a gift from his inheritance to one^&#42;1^ of his servants,^&#42;2^ it must also become his until the year of liberty;^&#42;3^ and it must return to the chieftain. Only his inheritance—as regards his sons^&#42;4^—is what should continue to belong to their own selves.

[NOTE]
====
. “To one of.” Heb., leʼa·chadhʹ.
. Or, “of his slaves.” Heb., me·ʽava·dhavʹ.
. Or, “release; manumission.” See Jer 34:8, 15, 17.
. “The inheritance of his sons,” LXXSy.
====

[[v26-46-18]]

^<<v26-46-18,18>>^ And the chieftain should not take any of the inheritance of the people so as to force them out of their possession. From his own possession he should give his sons an inheritance, to the end that my people may not be scattered each one from his possession.’”

[[v26-46-19]]

^<<v26-46-19,19>>^ And he proceeded to bring me in by the entryway that was by the side of the gate to the holy dining rooms, those belonging to the priests, that were facing to the north, and, look! there was a place there on both rear sides^&#42;1^ to the west.

[NOTE]
====
. “On both rear sides,” Mmargin; M, “in the rear of them.”
====

[[v26-46-20]]

^<<v26-46-20,20>>^ And he proceeded to say to me: “This is the place where the priests will boil the guilt offering and the sin offering, &#91;and&#93; where they will bake the grain offering, in order to carry nothing out to the outer courtyard so as to sanctify the people.”

[[v26-46-21]]

^<<v26-46-21,21>>^ And he proceeded to bring me out to the outer courtyard and make me pass along to the four corner posts of the courtyard, and, look! there was a courtyard by &#91;this&#93; corner post of the courtyard, a courtyard by &#91;that&#93; corner post of the courtyard.

[[v26-46-22]]

^<<v26-46-22,22>>^ At the four corner posts of the courtyard there were small courtyards, forty &#91;cubits&#93; in length and thirty in width. The four of them with corner structures^&#42;1^ had the same measurement.

[NOTE]
====
. “With corner structures.” Heb., mehuq·tsa·ʽohthʹ; LXXSyVg omit. In M this word is marked with extraordinary points by the Sopherim to stigmatize it as spurious and hence to be omitted. See App 2A.
====

[[v26-46-23]]

^<<v26-46-23,23>>^ And there was a row round about them, round about the four of them, and there were boiling places made beneath the rows round about.

[[v26-46-24]]

^<<v26-46-24,24>>^ Then he said to me: “These are the houses of those doing the boiling, where the ministers of the House boil the sacrifice of the people.”

'''

xref:026-ezekiel/026-ezekiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezekiel/026-ezekiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]