include::./index.adoc[]

[[v26-16-0]]
=== Ezekiel, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-16-1]]

^<<v26-16-1,1>>^ And the word of Jehovah came further to me, saying:

[[v26-16-2]]

^<<v26-16-2,2>>^ “Son of man, make known to Jerusalem her detestable things.

[[v26-16-3]]

^<<v26-16-3,3>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said to Jerusalem: “Your origin and your birth were from the land of the Caʹnaan·ite. Your father was the Amʹor·ite, and your mother was a Hitʹtite.

[[v26-16-4]]

^<<v26-16-4,4>>^ And as regards your birth, on the day of your being born your navel string had not been cut, and in water you had not been washed for cleansing, and with salt you had not at all been rubbed, and by no means had you been swaddled.

[[v26-16-5]]

^<<v26-16-5,5>>^ No eye felt sorry for you to do for you one of these things in compassion upon you, but you were thrown upon the surface of the field because there was an abhorring of your soul in the day of your being born.

[[v26-16-6]]

^<<v26-16-6,6>>^ “‘“And I came passing along by you and got to see you kicking about in your blood, and I proceeded to say to you in your blood, ‘Keep living!’ yes, to say to you in your blood, ‘Keep living!’

[[v26-16-7]]

^<<v26-16-7,7>>^ A very big multitude^&#42;1^ like the sprouting of the field is what I made you so that you would grow big and become great and come in with the finest ornament. The two breasts themselves were firmly developed, and your own hair grew luxuriantly, when you had been naked and nude.”’^&#42;2^

[NOTE]
====
. Lit., “A myriad; Ten thousand.”
. Lit., “nakedness and nudity.”
====

[[v26-16-8]]

^<<v26-16-8,8>>^ “‘And I came passing along by you and got to see you, and, look! your time was the time for love’s expressions. So I proceeded to spread my skirt over you and to cover your nudeness and to make a sworn statement to you and enter into a covenant with you,’ is the utterance of the Sovereign Lord Jehovah, ‘and so you became mine.

[[v26-16-9]]

^<<v26-16-9,9>>^ Furthermore, I washed you with water and rinsed away your blood from off you and greased you with oil.

[[v26-16-10]]

^<<v26-16-10,10>>^ And I went on to clothe you with an embroidered garment and to shoe you with sealskin and to wrap you in fine linen and to cover you with costly material.

[[v26-16-11]]

^<<v26-16-11,11>>^ And I went on to deck you with ornaments and to put bracelets upon your hands and a necklace about your throat.

[[v26-16-12]]

^<<v26-16-12,12>>^ Furthermore, I put a nose ring in your nostril and earrings on your ears and a beautiful crown on your head.

[[v26-16-13]]

^<<v26-16-13,13>>^ And you kept decking yourself with gold and silver, and your attire was fine linen and costly material and an embroidered garment. Fine flour and honey and oil were what you ate, and you grew to be very, very pretty, and gradually you became fit for royal position.’”

[[v26-16-14]]

^<<v26-16-14,14>>^ “‘And for you a name began to go forth among the nations because of your prettiness, for it was perfect because of my splendor that I placed upon you,’ is the utterance of the Sovereign Lord Jehovah.”

[[v26-16-15]]

^<<v26-16-15,15>>^ “‘But you began to trust in your prettiness and become a prostitute on account of your name and to pour out your acts of prostitution on every passerby; his it came to be.

[[v26-16-16]]

^<<v26-16-16,16>>^ And you proceeded to take some of your garments and make for yourself high places of varied colors and you would prostitute yourself on them—such things are not coming in, and it should not happen.^&#42;1^

[NOTE]
====
. The meaning of this Heb. expression is uncertain. LXX, “and you will by no means go in, nor will it by any means happen”; Vg, “just as it has not happened, neither is about to be.”
====

[[v26-16-17]]

^<<v26-16-17,17>>^ And you would take your beautiful articles from my gold and from my silver that I had given to you and you would make for yourself images of a male and prostitute yourself with them.^&#42;1^

[NOTE]
====
. Or, “and commit unfaithful intercourse with them.” Heb., wat·tiz·ni-vamʹ; Lat., et for·ni·caʹta es in eʹis.
====

[[v26-16-18]]

^<<v26-16-18,18>>^ And you would take your embroidered garments and cover them; and my oil and my incense you would actually put before them.

[[v26-16-19]]

^<<v26-16-19,19>>^ And my bread that I had given to you—fine flour and oil and honey that I had had you eat—you also actually put it before them as a restful^&#42;1^ odor, and it continued to occur,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. Or, “soothing; tranquilizing.”
====

[[v26-16-20]]

^<<v26-16-20,20>>^ “‘And you would take your sons and your daughters whom you had borne to me, and you would sacrifice these to them to be devoured—is that not enough of your acts of prostitution?

[[v26-16-21]]

^<<v26-16-21,21>>^ And you would slaughter my sons,^&#42;1^ and by making them pass through &#91;the fire&#93; you would give these to them.

[NOTE]
====
. “My sons,” MSyVg; LXX and eight Heb. mss, “your sons.”
====

[[v26-16-22]]

^<<v26-16-22,22>>^ And in all your detestable things and your acts of prostitution you did not remember the days of your youth when you happened to be naked and nude; kicking about in your blood you happened to be.

[[v26-16-23]]

^<<v26-16-23,23>>^ So it came about after all your badness (“woe, woe to you,” is the utterance of the Sovereign Lord Jehovah)

[[v26-16-24]]

^<<v26-16-24,24>>^ that you went building for yourself a mound^&#42;1^ and making for yourself a height in every public square.

[NOTE]
====
. Or, “a torus,” on the foot of an altar, evidently for immoral purposes.
====

[[v26-16-25]]

^<<v26-16-25,25>>^ At every head of the way you built your height and you began to make your prettiness something detestable and sprawl out your feet to every passerby and multiply your acts of prostitution.

[[v26-16-26]]

^<<v26-16-26,26>>^ And you went prostituting yourself to the sons of Egypt, your neighbors great of flesh,^&#42;1^ and you continued making your prostitution abound in order to offend me.

[NOTE]
====
. Or, “the genital organ.” Compare Le 15:2, 3.
====

[[v26-16-27]]

^<<v26-16-27,27>>^ And, look! I shall certainly stretch out my hand against you and I shall diminish your allowance and give you to the soul&#91;ful desire&#93; of the women hating you, the daughters of the Phi·lisʹtines, the women humiliated on account of your way as regards loose conduct.

[[v26-16-28]]

^<<v26-16-28,28>>^ “‘And you went on to prostitute yourself to the sons of As·syrʹi·a because there was no satisfying of you, and you kept prostituting yourself with them and also did not get satisfaction.

[[v26-16-29]]

^<<v26-16-29,29>>^ So you kept making your prostitution abound toward the land of Caʹnaan, toward the Chal·deʹans; and even in this you did not get satisfaction.

[[v26-16-30]]

^<<v26-16-30,30>>^ O how I am filled up with rage against you,’^&#42;1^ is the utterance of the Sovereign Lord Jehovah, ‘by your doing all these things, the work of a woman, a domineering prostitute!

[NOTE]
====
. Possibly, “O how weak your heart is!”
====

[[v26-16-31]]

^<<v26-16-31,31>>^ When you built your mound at the head of every way and you made your own height in every public square, yet you became unlike a prostitute in disdaining hire.

[[v26-16-32]]

^<<v26-16-32,32>>^ In the case of the wife that commits adultery,^&#42;1^ she takes strangers instead of her own husband.

[NOTE]
====
. Or, “that commits marital sexual unfaithfulness.” Heb., ham·mena·ʼaʹpheth; Gr., he moi·kho·meʹne; Lat., a·dulʹte·ra. See Mt 5:32 ftn, “Adultery.”
====

[[v26-16-33]]

^<<v26-16-33,33>>^ To all prostitutes they are accustomed to give a present, but you—you have given your presents to all those passionately loving you, and you offer a bribe to them to come in to you from all around in your acts of prostitution.

[[v26-16-34]]

^<<v26-16-34,34>>^ And in your case the opposite thing takes place from that of other women in your acts of prostitution, and after your style no prostitution has been committed, even in your giving hire when no hire has been given to you, and so it occurs in the opposite way.’

[[v26-16-35]]

^<<v26-16-35,35>>^ “Therefore, O prostitute, hear the word of Jehovah.

[[v26-16-36]]

^<<v26-16-36,36>>^ This is what the Sovereign Lord Jehovah has said, ‘For the reason that your lustfulness^&#42;1^ has been poured out and your private parts are uncovered in your acts of prostitution toward those passionately loving you and toward all your detestable dungy idols, even with the blood of your sons whom you gave to them,

[NOTE]
====
. Possibly, “menstruation.”
====

[[v26-16-37]]

^<<v26-16-37,37>>^ therefore here I am collecting together all those passionately loving you toward whom you were pleasurable and all those whom you loved along with all those whom you hated, and I will collect them together against you from all around and uncover your private parts to them, and they must see all your private parts.

[[v26-16-38]]

^<<v26-16-38,38>>^ “‘And I will judge you with the judgments of adulteresses and women shedding blood, and I will give you the blood of rage and jealousy.

[[v26-16-39]]

^<<v26-16-39,39>>^ And I will give you into their hand, and they will certainly tear down your mound and your heights will certainly be pulled down, and they must strip you of your garments and take your beautiful articles and leave you behind naked and nude.

[[v26-16-40]]

^<<v26-16-40,40>>^ And they must bring up against you a congregation and pelt you with stones and slaughter you with their swords.

[[v26-16-41]]

^<<v26-16-41,41>>^ And they must burn your houses with fire and execute in you acts of judgment before the eyes of many women; and I will cause you to cease from &#91;being&#93; a prostitute, and also no more hire will you give.

[[v26-16-42]]

^<<v26-16-42,42>>^ And I will bring my rage to its rest in you, and my jealousy must turn away from you; and I will stay quiet and I shall no more feel offended.’

[[v26-16-43]]

^<<v26-16-43,43>>^ “‘For the reason that you did not remember the days of your youth and you would cause me agitation because of all these things, even here I also, for my part, will put your own way upon &#91;your&#93; very head,’ is the utterance of the Sovereign Lord Jehovah, ‘and you will certainly not carry on any loose conduct alongside all your detestable things.

[[v26-16-44]]

^<<v26-16-44,44>>^ “‘Look! Everyone using a proverb against you will use the proverb, saying: “Like mother is her daughter!”

[[v26-16-45]]

^<<v26-16-45,45>>^ You are the daughter of your mother, one abhorring her husband and her sons. And you are the sister of your sisters, who abhorred their husbands and their sons. The mother of YOU women was a Hitʹtite, and YOUR father was an Amʹor·ite.’”

[[v26-16-46]]

^<<v26-16-46,46>>^ “‘And your older sister is Sa·marʹi·a herself with her dependent towns,^&#42;1^ who is dwelling on your left, and your sister younger than you, who is dwelling on your right, is Sodʹom with her dependent towns.

[NOTE]
====
. “Dependent towns.” Lit., “daughters.”
====

[[v26-16-47]]

^<<v26-16-47,47>>^ And it was not in their ways that you walked, nor according to their detestable things that you did. In a very little while you even began to act more ruinously than they did in all your ways.

[[v26-16-48]]

^<<v26-16-48,48>>^ As I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘Sodʹom your sister, she with her dependent towns, has not done according to what you did, you and your dependent towns.

[[v26-16-49]]

^<<v26-16-49,49>>^ Look! This is what proved to be the error of Sodʹom your sister: Pride, sufficiency of bread and the carefreeness of keeping undisturbed were what happened to belong to her and her dependent towns, and the hand of the afflicted one and the poor one she did not strengthen.

[[v26-16-50]]

^<<v26-16-50,50>>^ And they^&#42;1^ continued to be haughty and to carry on a detestable thing before me, and I finally removed them, just as I saw &#91;fit&#93;.^&#42;2^

[NOTE]
====
. “They,” fem., referring to “Sodom” and her “dependent towns [lit., daughters].”
. “I saw [fit],” MLXX; Vg, “you have seen.”
====

[[v26-16-51]]

^<<v26-16-51,51>>^ “‘And as for Sa·marʹi·a, she has not sinned even up to half of your sins, but you kept making your detestable things abound more than they did, so that you made your sisters appear righteous because of all your detestable things that you carried on.

[[v26-16-52]]

^<<v26-16-52,52>>^ You also, bear your humiliation when you must argue in favor of your sisters. Because of your sins in which you acted more detestably than they did, they are more righteous than you. And you also, be ashamed and bear your humiliation in that you make your sisters appear righteous.’

[[v26-16-53]]

^<<v26-16-53,53>>^ “‘And I will gather their captive ones, the captive ones of Sodʹom and of her dependent towns, and the captive ones of Sa·marʹi·a and of her dependent towns; I will also gather^&#42;1^ your captive ones in the midst of them,

[NOTE]
====
. “I will also gather,” TLXXSyVg.
====

[[v26-16-54]]

^<<v26-16-54,54>>^ in order that you may bear your humiliation; and you must feel humiliated owing to all that you have done, in that you comforted them.

[[v26-16-55]]

^<<v26-16-55,55>>^ And your own sisters, Sodʹom and her dependent towns, will return to their former state, and Sa·marʹi·a and her dependent towns will return to their former state, and you yourself and your own dependent towns will return to YOUR former state.

[[v26-16-56]]

^<<v26-16-56,56>>^ And Sodʹom your sister did not prove to be anything worth hearing about from your mouth in the day of your pride,

[[v26-16-57]]

^<<v26-16-57,57>>^ before your own badness got to be exposed, just as at the time of the reproach of the daughters of Syria^&#42;1^ and of all round about her, the daughters of the Phi·lisʹtines, those treating you with scorn on all sides.

[NOTE]
====
. “Syria (Aram),” MTLXXVg; Sy and many Heb. mss and printed ed., “Edom.”
====

[[v26-16-58]]

^<<v26-16-58,58>>^ Your loose conduct and your detestable things, you yourself must bear them,’ is the utterance of Jehovah.”

[[v26-16-59]]

^<<v26-16-59,59>>^ “For this is what the Sovereign Lord Jehovah has said, ‘I also must do with you just as you have done, because you despised the oath in breaking &#91;my&#93; covenant.^&#42;1^

[NOTE]
====
. “My covenant,” LXXSy.
====

[[v26-16-60]]

^<<v26-16-60,60>>^ And I, I myself, must remember my covenant with you in the days of your youth, and I must establish for you an indefinitely lasting covenant.

[[v26-16-61]]

^<<v26-16-61,61>>^ And you will certainly remember your ways and feel humiliated when you receive your sisters, the ones older than you as well as the ones younger than you, and I shall certainly give them to you as daughters, but not owing to your covenant.’

[[v26-16-62]]

^<<v26-16-62,62>>^ “‘And I, I myself, will establish my covenant with you; and you will have to know that I am Jehovah,

[[v26-16-63]]

^<<v26-16-63,63>>^ in order that you may remember and actually be ashamed and you may no more come to have any reason to open &#91;your&#93; mouth because of your humiliation, when I make an atonement for you for all that you have done,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezekiel/026-ezekiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]