include::./index.adoc[]

[[v26-38-0]]
=== Ezekiel, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-38-1]]

^<<v26-38-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-38-2]]

^<<v26-38-2,2>>^ “Son of man, set your face against Gog &#91;of&#93; the land of Maʹgog,^&#42;1^ the head chieftain^&#42;2^ of Meʹshech and Tuʹbal, and prophesy against him.

[NOTE]
====
. “Gog [of] the land of Magog,” MT; LXX, “Gog and the land of Magog”; Sy, “Gog and against the land of Magog”; Vg, “Gog, the land of Magog.” “Magog” is an artificial form equivalent to “home of Gog,” according to KB, p. 493.
. “Head chieftain.” Or, “chieftain of Rosh.” Vg, “head prince”; LXX, “ruler of Rosh”; Sy, “leader and head.”
====

[[v26-38-3]]

^<<v26-38-3,3>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said: “Here I am against you, O Gog, you head chieftain of Meʹshech and Tuʹbal.

[[v26-38-4]]

^<<v26-38-4,4>>^ And I shall certainly turn you around and put hooks in your jaws and bring you forth with all your military force, horses and horsemen, all of them clothed in perfect taste, a numerous congregation, with large shield and buckler, all of them handling swords;

[[v26-38-5]]

^<<v26-38-5,5>>^ Persia, E·thi·oʹpi·a^&#42;1^ and Put with them, all of them with buckler and helmet;

[NOTE]
====
. “Ethiopia.” Heb., Kush; LXXVg, “Ethiopians.”
====

[[v26-38-6]]

^<<v26-38-6,6>>^ Goʹmer and all its bands, the house of To·garʹmah, &#91;of&#93; the remotest parts of the north, and all its bands, many peoples with you.

[[v26-38-7]]

^<<v26-38-7,7>>^ “‘“Be ready, and let there be preparation on your part, you with all your congregation, those congregated alongside you, and you must become their guard.

[[v26-38-8]]

^<<v26-38-8,8>>^ “‘“After many days you will be given attention. In the final part of the years you will come to the land &#91;of people&#93; brought back from the sword, collected together out of many peoples, onto the mountains of Israel, that have proved to be a constantly devastated place; even &#91;a land&#93;^&#42;1^ that has been brought forth from the peoples, &#91;where&#93; they have dwelt in security, all of them.

[NOTE]
====
. Lit., “it,” fem., referring to “land,” fem.
====

[[v26-38-9]]

^<<v26-38-9,9>>^ And you will be bound to come up. Like a storm you will come in. Like clouds to cover the land you will become, you and all your bands and many peoples with you.”’

[[v26-38-10]]

^<<v26-38-10,10>>^ “This is what the Sovereign Lord Jehovah has said, ‘And it must occur in that day that things will come up into your heart, and you will certainly think up an injurious scheme;

[[v26-38-11]]

^<<v26-38-11,11>>^ and you must say: “I shall go up against the land of open rural country. I shall come in upon those having no disturbance, dwelling in security, all of them dwelling without wall, and they do not have even bar and doors.”

[[v26-38-12]]

^<<v26-38-12,12>>^ It will be to get a big spoil and to do much plundering, in order to turn your hand back upon devastated places reinhabited and upon a people gathered together out of the nations, &#91;one&#93; that is accumulating wealth and property, &#91;those&#93; who are dwelling in the center^&#42;1^ of the earth.

[NOTE]
====
. Lit., “navel.” Lat., um·bi·liʹci.
====

[[v26-38-13]]

^<<v26-38-13,13>>^ “‘Sheʹba and Deʹdan and the merchants of Tarʹshish and all its maned young lions—they will say to you: “Is it to get a big spoil that you are coming in? Is it to do much plundering that you have congregated your congregation, in order to carry off silver and gold, to take wealth and property, to get a very great spoil?”’

[[v26-38-14]]

^<<v26-38-14,14>>^ “Therefore prophesy, O son of man, and you must say to Gog, ‘This is what the Sovereign Lord Jehovah has said: “Will it not be in that day when my people Israel are dwelling in security that you will know &#91;it&#93;?

[[v26-38-15]]

^<<v26-38-15,15>>^ And you will certainly come from your place, from the remotest parts of the north, you and many peoples with you, all of them riding on horses, a great congregation, even a numerous military force.

[[v26-38-16]]

^<<v26-38-16,16>>^ And you will be bound to come up against my people Israel, like clouds to cover the land. In the final part of the days it will occur, and I shall certainly bring you against my land, for the purpose that the nations may know me when I sanctify myself in you before their eyes, O Gog.”’

[[v26-38-17]]

^<<v26-38-17,17>>^ “This is what the Sovereign Lord Jehovah has said, ‘Are you the same one of whom I spoke in the former days by the hand of my servants the prophets of Israel, who were prophesying in those days—years—as to bringing you in upon them?’

[[v26-38-18]]

^<<v26-38-18,18>>^ “‘And it must occur in that day, in the day when Gog comes in upon the soil of Israel,’ is the utterance of the Sovereign Lord Jehovah, ‘that my rage will come up into my nose.

[[v26-38-19]]

^<<v26-38-19,19>>^ And in my ardor, in the fire of my fury, I shall have to speak. Surely in that day a great quaking will occur in the soil^&#42;1^ of Israel.

[NOTE]
====
. Or, “the ground.” Heb., ʼadh·mathʹ.
====

[[v26-38-20]]

^<<v26-38-20,20>>^ And because of me the fish of the sea and the flying creatures of the heavens and the wild beasts of the field and all the creeping things that are creeping on the ground and all mankind^&#42;1^ that are upon the surface of the ground will be bound to shiver, and the mountains will actually be thrown down and the steep ways will have to fall, and to the earth even every wall will fall.’

[NOTE]
====
. Or, “earthling men.” Heb., ha·ʼa·dhamʹ.
====

[[v26-38-21]]

^<<v26-38-21,21>>^ “‘And I will call forth against him throughout all my mountainous region a sword,’ is the utterance of the Sovereign Lord Jehovah. ‘Against his own brother the sword of each one will come to be.

[[v26-38-22]]

^<<v26-38-22,22>>^ And I will bring myself into judgment with him, with pestilence and with blood; and a flooding downpour and hailstones, fire and sulphur I shall rain down upon him and upon his bands and upon the many peoples that will be with him.

[[v26-38-23]]

^<<v26-38-23,23>>^ And I shall certainly magnify myself and sanctify myself and make myself known before the eyes of many nations; and they will have to know that I am Jehovah.’

'''

xref:026-ezekiel/026-ezekiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezekiel/026-ezekiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]