include::./index.adoc[]

[[v26-39-0]]
=== Ezekiel, 39
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-39-1]]

^<<v26-39-1,1>>^ “And as regards you, O son of man, prophesy against Gog, and you must say, ‘This is what the Sovereign Lord Jehovah has said: “Here I am against you, O Gog, you head chieftain of Meʹshech^&#42;1^ and Tuʹbal.

[NOTE]
====
. Or, “you chieftain of Rosh, Meshech.” Vg, “head prince of Meshech”; T, “the head, great one of Meshech”; LXX, “ruler of Rosh, Meshech”; Sy, “leader and head of Meshech.”
====

[[v26-39-2]]

^<<v26-39-2,2>>^ And I will turn you around and lead you on and cause you to come up from the remotest parts of the north and bring you in upon the mountains of Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ And I will strike your bow out of your left hand, and your arrows I shall cause to fall out of your own right hand.

[[v26-39-4]]

^<<v26-39-4,4>>^ On the mountains of Israel you will fall, you and all your bands and the peoples that will be with you. To birds of prey, birds of every sort of wing, and the wild beasts of the field I will give you for food.”’

[[v26-39-5]]

^<<v26-39-5,5>>^ “‘Upon the surface of the field you will fall, for I myself have spoken,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-39-6]]

^<<v26-39-6,6>>^ “‘And I will send fire upon Maʹgog^&#42;1^ and upon those who are inhabiting the islands in security; and people will have to know that I am Jehovah.

[NOTE]
====
. “Magog,” MTSyVg; LXX, “Gog.” See 38:2 ftn, “Magog.”
====

[[v26-39-7]]

^<<v26-39-7,7>>^ And my holy name I shall make known in the midst of my people Israel, and I shall no more let my holy name be profaned; and the nations will have to know that I am Jehovah, the Holy One in Israel.’^&#42;1^

[NOTE]
====
. Or, “that I, Jehovah, am holy in Israel.” Heb., ki-ʼaniʹ Yehwahʹ qa·dhohshʹ beYis·ra·ʼelʹ.
====

[[v26-39-8]]

^<<v26-39-8,8>>^ “‘Look! It must come and it must be brought to be,’ is the utterance of the Sovereign Lord Jehovah. ‘This is the day of which I have spoken.

[[v26-39-9]]

^<<v26-39-9,9>>^ And the inhabitants of the cities of Israel will certainly go forth and burn and build fires with the armor and bucklers and large shields,—with the bows and with the arrows and with the handstaves and with the lances; and with them they will have to light fires seven years.

[[v26-39-10]]

^<<v26-39-10,10>>^ And they will not carry sticks of wood from the field, nor will they gather firewood out of the forests, for with the armor they will light fires.’
“‘And they will certainly make spoil of those who had been making spoil of them, and plunder those who had been plundering them,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-39-11]]

^<<v26-39-11,11>>^ “‘And it must occur in that day that I shall give to Gog a place there,^&#42;1^ a burial place in Israel, the valley of those passing through on the east of the sea, and it^&#42;2^ will be stopping up those passing through. And there they will have to bury Gog and all his crowd, and they will be certain to call &#91;it&#93; the Valley of Gog’s Crowd.^&#42;3^

[NOTE]
====
. “A place of name (renown),” LXXVg.
. “It,” fem., referring to “valley,” fem.
. Or, “Valley of Hamon-Gog.”
====

[[v26-39-12]]

^<<v26-39-12,12>>^ And those of the house of Israel will have to bury them for the purpose of cleansing the land, for seven months.

[[v26-39-13]]

^<<v26-39-13,13>>^ And all the people of the land will have to do the burying, and it will certainly become for them a matter of fame in the day that I glorify myself,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-39-14]]

^<<v26-39-14,14>>^ “‘And there will be men^&#42;1^ for continual &#91;employment&#93; whom they will divide off, passing along through the land, burying, with those passing through,^&#42;2^ those left remaining on the surface of the earth, in order to cleanse it. To the end of seven months they will keep making search.

[NOTE]
====
. “And . . . men.” Heb., weʼan·shehʹ, pl. form of ʼish.
. “With those passing through,” MT; LXXSy omit.
====

[[v26-39-15]]

^<<v26-39-15,15>>^ And those passing through must pass along through the land, and should one actually see the bone of a man^&#42;1^ he must also build beside it a marker, until those who do the burying will have buried it in the Valley of Gog’s Crowd.^&#42;2^

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
. See vs 11 ftn, “Crowd.”
====

[[v26-39-16]]

^<<v26-39-16,16>>^ And the name of &#91;the&#93; city will also be Ha·moʹnah.^&#42;1^ And they will have to cleanse the land.’

[NOTE]
====
. Meaning “Crowd.” Heb., Hamoh·nahʹ, the fem. form of Ha·mohnʹ in vss 11, 15.
====

[[v26-39-17]]

^<<v26-39-17,17>>^ “And as regards you, O son of man, this is what the Sovereign Lord Jehovah has said, ‘Say to the birds of every sort of wing and to all the wild beasts of the field: “Collect yourselves together and come. Gather yourselves together all around to my sacrifice, which I am sacrificing for YOU, a great sacrifice on the mountains of Israel. And YOU will certainly eat flesh and drink blood.

[[v26-39-18]]

^<<v26-39-18,18>>^ The flesh of mighty ones YOU will eat, and the blood of the chieftains of the earth YOU will drink, rams, young male sheep, and he-goats, young bulls, the fatlings of Baʹshan all of them.

[[v26-39-19]]

^<<v26-39-19,19>>^ And YOU will be certain to eat fat to satisfaction and to drink blood to drunkenness, from my sacrifice that I will sacrifice for YOU.”’

[[v26-39-20]]

^<<v26-39-20,20>>^ “‘And YOU must get satisfied at my table on horses and charioteers,^&#42;1^ mighty persons and all sorts of warriors,’^&#42;2^ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. Or, “horsemen,” in agreement with LXXSyVg; M, “war chariot.”
. Lit., “every man [Heb., ʼish] of war.”
====

[[v26-39-21]]

^<<v26-39-21,21>>^ “‘And I will set my glory among the nations; and all the nations will have to see my judgment that I have executed and my hand that I have placed among them.

[[v26-39-22]]

^<<v26-39-22,22>>^ And those of the house of Israel will have to know that I am Jehovah their God from that day and forward.

[[v26-39-23]]

^<<v26-39-23,23>>^ And the nations will have to know that it was because of their error that they, the house of Israel, went into exile, on account of the fact that they behaved unfaithfully toward me, so that I concealed my face from them and gave them into the hand of their adversaries, and they kept falling, all of them, by the sword.

[[v26-39-24]]

^<<v26-39-24,24>>^ According to their uncleanness and according to their transgressions I did with them, and I kept concealing my face from them.’

[[v26-39-25]]

^<<v26-39-25,25>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Now is when I shall bring back the captive ones of Jacob and actually have mercy upon all the house of Israel; and I will show exclusive devotion for my holy name.

[[v26-39-26]]

^<<v26-39-26,26>>^ And they will have borne their humiliation and all their unfaithfulness with which they have acted toward me, when they dwell on their soil in security, with no one to make &#91;them&#93; tremble.

[[v26-39-27]]

^<<v26-39-27,27>>^ When I bring them back from the peoples and I actually collect them together out of the lands of their enemies, I will also sanctify myself^&#42;1^ among them before the eyes of many nations.’

[NOTE]
====
. Or, “I will also hold myself sacred (treat myself as holy).” Heb., weniq·dashʹti; Gr., ha·gi·a·stheʹso·mai; Lat., sanc·ti·fi·caʹtus.
====

[[v26-39-28]]

^<<v26-39-28,28>>^ “‘And they will have to know that I am Jehovah their God, when I send them in exile to the nations and actually bring them together upon their soil, so that I shall leave none of them remaining there any longer.

[[v26-39-29]]

^<<v26-39-29,29>>^ And I shall no longer conceal my face from them, because I will pour out my spirit upon the house of Israel,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezekiel/026-ezekiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]