include::./index.adoc[]

[[v26-2-0]]
=== Ezekiel, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-2-1]]

^<<v26-2-1,1>>^ And he proceeded to say to me: “Son of man,^&#42;1^ stand up upon your feet that I may speak with you.”

[NOTE]
====
. “Son of man.” Heb., ben-ʼa·dhamʹ; the first of 93 occurrences of this expression in Ezekiel. Gr., hui·eʹ an·throʹpou; Lat., fiʹli hoʹmi·nis.
====

[[v26-2-2]]

^<<v26-2-2,2>>^ And spirit began to come into me as soon as he spoke to me, and it^&#42;1^ finally made me stand up upon my feet that I might hear the One speaking to me.

[NOTE]
====
. “It,” fem., referring to “spirit,” fem.
====

[[v26-2-3]]

^<<v26-2-3,3>>^ And he went on to say to me: “Son of man, I am sending you to the sons of Israel, to rebellious nations that have rebelled against me. They themselves and their forefathers have transgressed against me down to this selfsame day.

[[v26-2-4]]

^<<v26-2-4,4>>^ And the sons insolent of face and hard of heart—I am sending you to them, and you must say to them, ‘This is what the Sovereign Lord Jehovah^&#42;1^ has said.’

[NOTE]
====
. “The Sovereign Lord Jehovah.” Heb., ʼAdho·naiʹ Yeho·wihʹ, with ʼAdho·naiʹ pl. to denote excellence, hence rendered “Sovereign Lord”; T, “Jehovah God”; Sy, “the Lord of lords”; Lat., Doʹmi·nus Deʹus; Luther (German, 1912 ed.), der Herr HErr, “the Lord LORD (Jehovah).” The first occurrence of this expression is in Ge 15:2, and it appears 217 times in Ezekiel. See App 1E.
====

[[v26-2-5]]

^<<v26-2-5,5>>^ And as for them, whether they will hear or will refrain—for they are a rebellious house—they will certainly know also that a prophet himself happened to be in the midst of them.

[[v26-2-6]]

^<<v26-2-6,6>>^ “And you, O son of man, do not be afraid of them; and of their words do not be afraid, because there are obstinate ones and things pricking you and it is among scorpions that you are dwelling. Of their words do not you be afraid, and at their faces do not you be struck with terror, for they are a rebellious house.

[[v26-2-7]]

^<<v26-2-7,7>>^ And you must speak my words to them, regardless of whether they hear or they refrain, for they are a case of rebellion.

[[v26-2-8]]

^<<v26-2-8,8>>^ “And you, O son of man, hear what I am speaking to you. Do not become rebellious like the rebellious house. Open your mouth and eat what I am giving you.”

[[v26-2-9]]

^<<v26-2-9,9>>^ And I began to see, and, look! there was a hand thrust out to me, and, look! in it there was the roll of a book.

[[v26-2-10]]

^<<v26-2-10,10>>^ And he gradually spread it out before me, and it was written upon in front and on the back; and there were written in it dirges and moaning and wailing.

'''

xref:026-ezekiel/026-ezekiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezekiel/026-ezekiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]