include::./index.adoc[]

[[v26-31-0]]
=== Ezekiel, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-31-1]]

^<<v26-31-1,1>>^ And it occurred further that in the eleventh year, in the third &#91;month&#93;, on the first &#91;day&#93; of the month, the word of Jehovah occurred to me, saying:

[[v26-31-2]]

^<<v26-31-2,2>>^ “Son of man, say to Pharʹaoh the king of Egypt and to his crowd,
“‘Whom have you come to resemble in your greatness?

[[v26-31-3]]

^<<v26-31-3,3>>^ Look! An As·syrʹi·an,^&#42;1^ a cedar in Lebʹa·non, pretty in bough, with a woody thicket offering shadow, and high in stature, so that among the clouds^&#42;2^ its treetop proved to be.

[NOTE]
====
. “An Assyrian,” MTLXXSyVg; by a correction, “I differentiate you as”; by a different correction, “A cypress.”
. “Clouds,” LXX and Arabic; MSyVg, “branches.”
====

[[v26-31-4]]

^<<v26-31-4,4>>^ Waters were what made it get big; the watery deep^&#42;1^ caused it to grow high. With its^&#42;2^ streams it was going all around its planting place; and its channels it sent forth to all the trees of the field.

[NOTE]
====
. Or, “surging waters.” Heb., tehohmʹ; LXXVg, “the abyss.” See Ge 1:2 ftn, “Deep.”
. “Its,” fem., referring to “watery deep.”
====

[[v26-31-5]]

^<<v26-31-5,5>>^ That is why it grew higher in its stature than all the &#91;other&#93; trees of the field.
“‘And its boughs kept multiplying, and its branches continued getting longer because of much water in its watercourses.^&#42;1^

[NOTE]
====
. “In its watercourses,” by a correction; M, “by its sending forth.”
====

[[v26-31-6]]

^<<v26-31-6,6>>^ On its boughs all the flying creatures of the heavens made their nests, and under its branches all the wild beasts of the field gave birth, and in its shade all the populous nations would dwell.

[[v26-31-7]]

^<<v26-31-7,7>>^ And it came to be pretty in its greatness, in the length of its foliage, for its root system proved to be over many waters.

[[v26-31-8]]

^<<v26-31-8,8>>^ &#91;Other&#93; cedars were no match for it in the garden of God.^&#42;1^ As for juniper trees, they bore no resemblance as respects its boughs. And plane trees themselves did not prove to be like it in branches. No &#91;other&#93; tree in the garden of God resembled it in its prettiness.

[NOTE]
====
. “In the garden of God.” Heb., beghan-ʼElo·himʹ; LXXSyVg, “in the paradise of God.” Compare vs 9.
====

[[v26-31-9]]

^<<v26-31-9,9>>^ Pretty is the way that I made it in the abundance of its foliage, and all the &#91;other&#93; trees of Eʹden^&#42;1^ that were in the garden of the &#91;true&#93; God^&#42;2^ kept envying it.’

[NOTE]
====
. Or, “pleasantness,” in agreement with LXXVg. Compare Ge 2:8 ftn, “Eden.”
. “The [true] God.” Heb., ha·ʼElo·himʹ. See App 1F.
====

[[v26-31-10]]

^<<v26-31-10,10>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘For the reason that you^&#42;1^ became high in stature, so that it put its treetop even among the clouds^&#42;2^ and its heart became exalted because of its height,

[NOTE]
====
. “You,” MTLXX; SyVg, “it.”
. “Clouds,” LXX and Arabic; M, “branches.”
====

[[v26-31-11]]

^<<v26-31-11,11>>^ I shall also give it into the hand of the despot of &#91;the&#93; nations. Without fail he will act against it. According to its wickedness I will drive it out.

[[v26-31-12]]

^<<v26-31-12,12>>^ And strangers, the tyrants of &#91;the&#93; nations, will cut it down, and people will abandon it upon the mountains; and in all the valleys its foliage will certainly fall, and its branches will be broken among all the streambeds of the earth. And out from its shade all the peoples of the earth will come down and abandon it.

[[v26-31-13]]

^<<v26-31-13,13>>^ Upon its fallen trunk all the flying creatures of the heavens will reside, and upon its branches there will certainly come to be all the wild beasts of the field;

[[v26-31-14]]

^<<v26-31-14,14>>^ to the end that none of the watered trees may become high in their stature, or put their treetops even among the clouds, and that none drinking water may stand up against them in their height, for they will certainly all of them be given to death, to the land down below, in the midst of the sons of mankind,^&#42;1^ to those going down into the pit.’

[NOTE]
====
. Or, “earthling men.” Heb., ʼa·dhamʹ.
====

[[v26-31-15]]

^<<v26-31-15,15>>^ “This is what the Sovereign Lord Jehovah has said, ‘On the day of its going down to Sheʹol I shall certainly cause a mourning. On its account I will cover the watery deep, that I may hold back its streams and &#91;that&#93; the many waters may be restrained; and on its account I shall darken Lebʹa·non, and on its account the trees of the field will all swoon away.

[[v26-31-16]]

^<<v26-31-16,16>>^ At the sound of its downfall I shall certainly cause nations to rock when I bring it down to Sheʹol with those going down into the pit, and in the land down below all the trees of Eʹden,^&#42;1^ the choicest and the best of Lebʹa·non, all those drinking water, will be comforted.

[NOTE]
====
. See vs 9 ftn, “Eden.”
====

[[v26-31-17]]

^<<v26-31-17,17>>^ With him they themselves also have gone down to Sheʹol,^&#42;1^ to those slain by the sword, and those who as his seed^&#42;2^ have dwelt in his shadow in the midst of nations.’

[NOTE]
====
. Or, “to the grave.” Heb., sheʼohʹlah; Gr., haiʹdou; Lat., in·ferʹnum. See App 4B.
. “Seed,” by a correction in agreement with LXXSy; MVg, “arm.”
====

[[v26-31-18]]

^<<v26-31-18,18>>^ “‘Whom have you come to resemble thus in glory and greatness among the trees of Eʹden? But you will certainly be brought down with the trees of Eʹden^&#42;1^ to the land down below. In the midst of the uncircumcised ones you will lie down with those slain by the sword. This is Pharʹaoh and all his crowd,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. Or, “pleasantness,” in agreement with LXXVg.
====

'''

xref:026-ezekiel/026-ezekiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezekiel/026-ezekiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]