include::./index.adoc[]

[[v26-21-0]]
=== Ezekiel, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-21-1]]

^<<v26-21-1,1>>^ ^&#42;1^ And the word of Jehovah continued to occur to me, saying:

[NOTE]
====
. TSyVg begin chapter 21 here.
====

[[v26-21-2]]

^<<v26-21-2,2>>^ “Son of man, set your face toward Jerusalem and drip &#91;words&#93; toward the holy places, and prophesy against the soil of Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ And you must say to the soil of Israel, ‘This is what Jehovah has said: “Here I am against you, and I will bring forth my sword out of its sheath and cut off from you righteous one and wicked one.

[[v26-21-4]]

^<<v26-21-4,4>>^ In order that I may actually cut off from you righteous one and wicked one, therefore my sword will go forth from its sheath against all flesh from south to north.

[[v26-21-5]]

^<<v26-21-5,5>>^ And all those of flesh will have to know that I myself, Jehovah, have brought forth my sword from its sheath. No more will it go back.”’

[[v26-21-6]]

^<<v26-21-6,6>>^ “And as for you, O son of man, sigh with shaking hips.^&#42;1^ Even with bitterness you should sigh before their eyes.

[NOTE]
====
. Lit., “with the breakdown of hips.”
====

[[v26-21-7]]

^<<v26-21-7,7>>^ And it must occur that, in case they say to you, ‘On account of what are you sighing?’ you must say, ‘At a report.’ For it will certainly come, and every heart must melt and all hands must drop down and every spirit must become dejected and all knees themselves will drip with water.^&#42;1^ ‘Look! It will certainly come and be brought to occur,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. That is, from urination due to pressure from fear.
====

[[v26-21-8]]

^<<v26-21-8,8>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-21-9]]

^<<v26-21-9,9>>^ “Son of man, prophesy, and you must say, ‘This is what Jehovah^&#42;1^ has said: “Say, ‘A sword, a sword! It has been sharpened, and it is also polished.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v26-21-10]]

^<<v26-21-10,10>>^ For the purpose of organizing a slaughter it has been sharpened; for the purpose of its getting a glitter^&#42;1^ it has been polished.’”’”
“Or shall we exult?”
“‘Is it rejecting the scepter of my own son, as &#91;it does&#93; every tree?

[NOTE]
====
. Lit., “lightning.” Heb., baʹroq.
====

[[v26-21-11]]

^<<v26-21-11,11>>^ “‘And one gives it to be polished, in order to wield &#91;it&#93; with the hand. It—a sword has been sharpened, and it—it has been polished, in order to give it into the hand of a killer.

[[v26-21-12]]

^<<v26-21-12,12>>^ “‘Cry out and howl, O son of man, for it itself has come to be against my people; it is against all the chieftains of Israel. The very ones hurled to the sword have come to be with my people. Therefore make a slap on &#91;the&#93; thigh.

[[v26-21-13]]

^<<v26-21-13,13>>^ For an extermination has been made, and what &#91;of it&#93; if it is rejecting also the scepter? This^&#42;1^ will not continue existing,’ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. Lit., “It,” masc., referring to the “scepter,” masc.; not the “sword,” fem.
====

[[v26-21-14]]

^<<v26-21-14,14>>^ “And you, O son of man—prophesy, and strike palm against palm, and ‘A sword!’ should be repeated for three times. The sword of the slain ones it is. It is the sword of someone slain who is great, which is making an encirclement of them.

[[v26-21-15]]

^<<v26-21-15,15>>^ In order for the heart to melt and &#91;in order&#93; to multiply those who are overthrown at all their gates, I will make a slaughter by the sword. Alas, it is made for a glittering,^&#42;1^ polished for a slaughter!

[NOTE]
====
. See vs 10 ftn.
====

[[v26-21-16]]

^<<v26-21-16,16>>^ Show yourself sharp;^&#42;1^ go to the right! Set your position; go to the left! To wherever your face is directed!

[NOTE]
====
. “Show yourself sharp,” fem., addressed to the “sword.”
====

[[v26-21-17]]

^<<v26-21-17,17>>^ And I myself also shall strike my one palm against my other palm, and I will bring my rage to its rest. I myself, Jehovah, have spoken.”

[[v26-21-18]]

^<<v26-21-18,18>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-21-19]]

^<<v26-21-19,19>>^ “And as for you, O son of man, set for yourself two ways for the sword of the king of Babylon^&#42;1^ to enter. From the one land both of them should go forth, and an &#91;index&#93; hand should be cut out; at the head of the way to the city it should be cut out.^&#42;2^

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
. “Should be cut out.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v26-21-20]]

^<<v26-21-20,20>>^ A way you should set for &#91;the&#93; sword to enter against Rabʹbah of the sons of Amʹmon, and &#91;one&#93; against Judah, against Jerusalem fortified.

[[v26-21-21]]

^<<v26-21-21,21>>^ For the king of Babylon stood still at the crossways,^&#42;1^ at the head of the two ways, in order to resort to divination. He has shaken the arrows. He has asked by means of the teraphim;^&#42;2^ he has looked into the liver.

[NOTE]
====
. Lit., “mother of the way.”
. “Teraphim,” M; LXX, “carved images”; Vg, “idols.”
====

[[v26-21-22]]

^<<v26-21-22,22>>^ In his right hand the divination proved to be for Jerusalem, to set battering rams, to open one’s mouth for a slaying,^&#42;1^ to raise the sound in an alarm signal, to set battering rams against gates, to throw up a siege rampart, to build a siege wall.

[NOTE]
====
. Or, “war cry,” by a transposition of letters.
====

[[v26-21-23]]

^<<v26-21-23,23>>^ And it has become to them like an untrue divination in their eyes—those who are sworn with oaths to them; and he is calling error to remembrance, in order &#91;for them&#93; to be caught.

[[v26-21-24]]

^<<v26-21-24,24>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘By reason of YOUR causing YOUR error to be remembered by YOUR transgressions being uncovered, in order that YOUR sins may be seen according to all YOUR dealings, by reason of YOUR being called to remembrance YOU people will be seized even by the hand.’

[[v26-21-25]]

^<<v26-21-25,25>>^ “And as for you, O deadly wounded, wicked chieftain of Israel, whose day has come in the time of the error of &#91;the&#93; end,

[[v26-21-26]]

^<<v26-21-26,26>>^ this is what the Sovereign Lord Jehovah has said, ‘Remove the turban, and lift off the crown. This^&#42;1^ will not be the same.^&#42;2^ Put on high even what is low, and bring low even the high one.

[NOTE]
====
. “This.” Heb., zoʼth, fem.
. “The same.” Lit., “this,” fem.
====

[[v26-21-27]]

^<<v26-21-27,27>>^ A ruin, a ruin, a ruin^&#42;1^ I shall make it.^&#42;2^ As for this^&#42;3^ also, it will certainly become no &#91;one’s&#93; until he comes who has the legal right, and I must give &#91;it&#93;^&#42;4^ to him.’

[NOTE]
====
. Or, “a distortion (twisting).”
. “It,” fem.
. “This.” Heb., zoʼth, fem.
. That is, the rightful due.
====

[[v26-21-28]]

^<<v26-21-28,28>>^ “And you, O son of man, prophesy, and you must say, ‘This is what the Sovereign Lord Jehovah has said concerning the sons of Amʹmon and concerning the reproach from them.’ And you must say, ‘A sword, a sword drawn for a slaughter, polished to cause &#91;it&#93; to devour,^&#42;1^ in order to glitter,

[NOTE]
====
. Or, “polished for an extermination.”
====

[[v26-21-29]]

^<<v26-21-29,29>>^ because of &#91;their&#93; beholding for you^&#42;1^ an unreality, because of &#91;their&#93; divining for you a lie, in order to put you on the necks of the slain ones, the wicked men whose day has come in the time of the error of &#91;the&#93; end.

[NOTE]
====
. “You,” fem. sing., evidently referring to Rabbah of the Ammonites.
====

[[v26-21-30]]

^<<v26-21-30,30>>^ Return &#91;it&#93; to its sheath. In the place that you were created, in the land of your origin, I shall judge you.

[[v26-21-31]]

^<<v26-21-31,31>>^ And I will pour out upon you my denunciation. With the fire of my fury I shall blow upon you, and I will give you into the hand of men who are unreasoning, the craftsmen of ruination.

[[v26-21-32]]

^<<v26-21-32,32>>^ For the fire you will become fuel. Your own blood will prove to be in the midst of the land. You will not be remembered, for I myself, Jehovah, have spoken.’”

'''

xref:026-ezekiel/026-ezekiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezekiel/026-ezekiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]