include::./index.adoc[]

[[v26-18-0]]
=== Ezekiel, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-18-1]]

^<<v26-18-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-18-2]]

^<<v26-18-2,2>>^ “What does it mean to YOU people that YOU are expressing this proverbial saying on the soil of Israel, saying, ‘Fathers are the ones that eat unripe grapes, but it is the teeth of the sons that get set on edge’?^&#42;1^

[NOTE]
====
. Lit., “get blunted (dulled).”
====

[[v26-18-3]]

^<<v26-18-3,3>>^ “‘As I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘it will no more continue to be YOURS to express this proverbial saying in Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Look! All the souls^&#42;1^—to me they belong. As the soul of the father so likewise the soul of the son—to me they belong. The soul that is sinning—it itself will die.^&#42;2^

[NOTE]
====
. “The souls.” Heb., han·nepha·shohthʹ; Gr., psy·khaiʹ; Lat., aʹni·mae. See App 4A.
. Or, “The soul that is sinning is the one that will die.” Heb., han·neʹphesh ha·cho·teʼthʹ hiʼ tha·muthʹ.
====

[[v26-18-5]]

^<<v26-18-5,5>>^ “‘And as regards a man,^&#42;1^ in case he happens to be righteous and he has executed justice and righteousness;

[NOTE]
====
. Lit., “And a man.” Heb., weʼishʹ.
====

[[v26-18-6]]

^<<v26-18-6,6>>^ on the mountains he did not eat and his eyes he did not raise to the dungy idols of the house of Israel, and his companion’s wife he did not defile and to a woman in her impurity he would not go near;

[[v26-18-7]]

^<<v26-18-7,7>>^ and no man would he maltreat; the pledge that he took for indebtedness, he would return; nothing would he wrest away in robbery; to the hungry one he would give his own bread and the naked one he would cover with a garment;

[[v26-18-8]]

^<<v26-18-8,8>>^ nothing would he give on interest and no usury would he take; from injustice he would draw back his hand; true justice he would execute between man and man;

[[v26-18-9]]

^<<v26-18-9,9>>^ in my statutes he kept walking and my judicial decisions he kept in order to execute truth, he is righteous. He will positively keep living,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-18-10]]

^<<v26-18-10,10>>^ “‘And &#91;if&#93; one has become father to a son who is a robber, a shedder of blood, who has done the like of one of these things^&#42;1^

[NOTE]
====
. Lit., “done the brother of one of these things,” M; T, “done to his brother one of these things”; SyVg, “done (any) one of these things.”
====

[[v26-18-11]]

^<<v26-18-11,11>>^ (but he himself has done none of these very things); in case he has eaten also upon the mountains, and his companion’s wife he has defiled;

[[v26-18-12]]

^<<v26-18-12,12>>^ the afflicted and poor one he has maltreated; things he has wrested away in robbery, a pledged thing he would not return; and to the dungy idols he lifted up his eyes, a detestable thing is what he has done.

[[v26-18-13]]

^<<v26-18-13,13>>^ On usury he has given, and interest he has taken, and he positively will not keep living. All these detestable things he has done. He will positively be put to death. On him his own blood will come to be.

[[v26-18-14]]

^<<v26-18-14,14>>^ “‘And, look! one has become father to a son, who keeps seeing all the sins of his father that he has done, and he sees^&#42;1^ and does not do things like them.

[NOTE]
====
. “Sees,” MT; LXXVg, “fears.”
====

[[v26-18-15]]

^<<v26-18-15,15>>^ On the mountains he has not eaten, and his eyes he has not lifted up to the dungy idols of the house of Israel; his companion’s wife he has not defiled;

[[v26-18-16]]

^<<v26-18-16,16>>^ and no man^&#42;1^ has he maltreated, no pledge has he seized, and nothing has he taken in robbery; to the hungry one he has given his own bread, and the naked one he has covered with a garment;

[NOTE]
====
. “And no man.” Heb., weʼishʹ loʼ.
====

[[v26-18-17]]

^<<v26-18-17,17>>^ from the afflicted one^&#42;1^ he has drawn back his hand; no usury and interest has he taken; my judicial decisions he has carried out; in my statutes he has walked; he himself will not die because of the error of his father. He will positively keep living.

[NOTE]
====
. “The afflicted one,” M; LXX, “injustice.”
====

[[v26-18-18]]

^<<v26-18-18,18>>^ As for his father, because he committed outright defrauding, wrested something away in robbery of a brother, and whatever is not good he has done in the midst of his peoples, look! then he must die for his error.

[[v26-18-19]]

^<<v26-18-19,19>>^ “‘And YOU people will certainly say: “Why is it that the son does not have to bear anything because of the error of the father?” Now as regards the son, justice and righteousness he has executed, all the statutes of mine he has kept and he keeps doing them. He will positively keep living.

[[v26-18-20]]

^<<v26-18-20,20>>^ The soul that is sinning—it itself will die.^&#42;1^ A son himself will bear nothing because of the error of the father, and a father himself will bear nothing because of the error of the son. Upon his own self the very righteousness of the righteous one will come to be, and upon his own self the very wickedness of a wicked one will come to be.

[NOTE]
====
. See vs 4 ftn, “Die.”
====

[[v26-18-21]]

^<<v26-18-21,21>>^ “‘Now as regards someone wicked, in case he should turn back from all his sins that he has committed and he should actually keep all my statutes and execute justice and righteousness, he will positively keep living. He will not die.

[[v26-18-22]]

^<<v26-18-22,22>>^ All his transgressions that he has committed—they will not be remembered against him. For his righteousness that he has done he will keep living.’

[[v26-18-23]]

^<<v26-18-23,23>>^ “‘Do I take any delight at all in the death of someone wicked,’ is the utterance of the Sovereign Lord Jehovah, ‘&#91;and&#93; not in that he should turn back from his ways and actually keep living?’

[[v26-18-24]]

^<<v26-18-24,24>>^ “‘Now when someone righteous turns back from his righteousness and actually does injustice; according to all the detestable things that the wicked one has done he keeps doing and he is living, none of all his righteous acts that he has done will be remembered. For his unfaithfulness that he has committed and for his sin with which he has sinned, for them he will die.

[[v26-18-25]]

^<<v26-18-25,25>>^ “‘And YOU people will certainly say: “The way of Jehovah^&#42;1^ is not adjusted right.” Hear, please, O house of Israel. Is not my own way adjusted right? Are not the ways of YOU people not adjusted right?

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v26-18-26]]

^<<v26-18-26,26>>^ “‘When someone righteous turns back from his righteousness and he actually does injustice and dies on account of them, for his injustice that he has done he will die.

[[v26-18-27]]

^<<v26-18-27,27>>^ “‘And when someone wicked turns back from his wickedness that he has committed and proceeds to execute justice and righteousness, he is the one that will preserve his own soul alive.

[[v26-18-28]]

^<<v26-18-28,28>>^ When he sees^&#42;1^ and he turns back from all his transgressions that he has done, he will positively keep living. He will not die.

[NOTE]
====
. “Sees,” MTSyVg; LXX omits.
====

[[v26-18-29]]

^<<v26-18-29,29>>^ “‘And the house of Israel will certainly say: “The way of Jehovah^&#42;1^ is not adjusted right.” As for my ways, are they not adjusted right, O house of Israel? Are not the ways of YOU people the ones that are not adjusted right?’

[NOTE]
====
. See vs 25 ftn.
====

[[v26-18-30]]

^<<v26-18-30,30>>^ “‘Therefore each one according to his ways is how I shall judge YOU, O house of Israel,’ is the utterance of the Sovereign Lord Jehovah. ‘Turn back, yes, cause a turning back from all YOUR transgressions, and let nothing prove to be for YOU people a stumbling block causing error.

[[v26-18-31]]

^<<v26-18-31,31>>^ Throw off from yourselves all YOUR transgressions in which YOU have transgressed and make for yourselves a new heart and a new spirit, for why should YOU die, O house of Israel?’

[[v26-18-32]]

^<<v26-18-32,32>>^ “‘For I do not take any delight in the death of someone dying,’ is the utterance of the Sovereign Lord Jehovah. ‘So cause a turning back and keep living, O YOU people.’”

'''

xref:026-ezekiel/026-ezekiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezekiel/026-ezekiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]