include::./index.adoc[]

[[v26-7-0]]
=== Ezekiel, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-7-1]]

^<<v26-7-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-7-2]]

^<<v26-7-2,2>>^ “And as for you, O son of man, this is what the Sovereign Lord Jehovah has said to the soil of Israel, ‘An end, the end, has come upon the four extremities^&#42;1^ of the land.^&#42;2^

[NOTE]
====
. Lit., “wings.”
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v26-7-3]]

^<<v26-7-3,3>>^ Now the end is upon you,^&#42;1^ and I must send my anger against you, and I will judge you according to your ways and bring upon you all your detestable things.

[NOTE]
====
. “You,” fem. sing., referring to the “soil of Israel.”
====

[[v26-7-4]]

^<<v26-7-4,4>>^ And my eye will not feel sorry for you, neither will I feel compassion, for upon you I shall bring your own ways, and in the midst of you your own detestable things will come to be; and YOU people will have to know that I am Jehovah.’

[[v26-7-5]]

^<<v26-7-5,5>>^ “This is what the Sovereign Lord Jehovah has said, ‘A calamity, a unique calamity, look! it is coming.

[[v26-7-6]]

^<<v26-7-6,6>>^ An end itself must come. The end must come; it must awaken for you.^&#42;1^ Look! It is coming.

[NOTE]
====
. See vs 3 ftn.
====

[[v26-7-7]]

^<<v26-7-7,7>>^ The garland^&#42;1^ must come to you,^&#42;2^ O inhabiter of the land,^&#42;3^ the time must come, the day is near. There is confusion, and not the shouting of the mountains.

[NOTE]
====
. Or, “The turn [of events].” The meaning and application of the Heb. word are uncertain.
. “You,” masc. sing., referring to “inhabiter.”
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v26-7-8]]

^<<v26-7-8,8>>^ “‘Now shortly I shall pour out my rage upon you, and I will bring my anger against you to its finish, and I will judge you according to your ways and bring upon you all your detestable things.

[[v26-7-9]]

^<<v26-7-9,9>>^ Neither will my eye feel sorry nor shall I feel compassion. According to your ways shall I do the bringing upon you yourself, and your own detestable things will come to be right in the midst of you; and YOU people will have to know that I am Jehovah doing the smiting.^&#42;1^

[NOTE]
====
. Or, “I, Jehovah, am doing the striking.”
====

[[v26-7-10]]

^<<v26-7-10,10>>^ “‘Look! The day! Look! It is coming. The garland has gone forth. The rod has blossomed. Presumptuousness has sprouted.

[[v26-7-11]]

^<<v26-7-11,11>>^ Violence itself has risen up into a rod of wickedness. It is not from them, nor is it from their wealth; and it is not from their own selves, nor is there any eminency^&#42;1^ in them.

[NOTE]
====
. Or, “lamentation; wailing.” The meaning of the Heb. word is uncertain.
====

[[v26-7-12]]

^<<v26-7-12,12>>^ The time must come, the day must arrive. As regards the buyer, let him not rejoice; and as regards the seller, let him not go into mourning, for there is hot feeling against all its crowd.

[[v26-7-13]]

^<<v26-7-13,13>>^ For to what was sold the seller himself will not return, while their life is yet among the living ones; for the vision is for all its crowd. No one will return, and they will not possess themselves each one^&#42;1^ of his own life by his own error.

[NOTE]
====
. “And . . . each one.” Heb., weʼishʹ.
====

[[v26-7-14]]

^<<v26-7-14,14>>^ “‘They have blown the trumpet and there has been a preparing of everybody, but there is no one going to the battle, because my hot feeling is against all its crowd.

[[v26-7-15]]

^<<v26-7-15,15>>^ The sword is outside, and the pestilence and the famine are inside. Whoever is in the field, by the sword he will die, and whoever are in the city, famine and pestilence themselves will devour them.

[[v26-7-16]]

^<<v26-7-16,16>>^ And their escapees will certainly make their escape and become on the mountains like the doves of the valleys, all of which are moaning, each one in his own error.

[[v26-7-17]]

^<<v26-7-17,17>>^ As for all the hands, they keep dropping down; and as for all knees, they keep dripping with water.^&#42;1^

[NOTE]
====
. That is, from urination due to pressure from fear.
====

[[v26-7-18]]

^<<v26-7-18,18>>^ And they have girded on sackcloth, and shuddering has covered them; and on all faces there is shame and on all their heads there is baldness.

[[v26-7-19]]

^<<v26-7-19,19>>^ “‘Into the streets they will throw their very silver, and an abhorrent thing their own gold will become. Neither their silver nor their gold will be able to deliver them in the day of Jehovah’s fury. Their souls they will not satisfy, and their intestines they will not fill, for it has become a stumbling block causing their error.

[[v26-7-20]]

^<<v26-7-20,20>>^ And the decoration of one’s ornament—one has set it as reason for pride; and their detestable images, their disgusting things, they have made with it.^&#42;1^ That is why I will make it to them an abhorrent thing.

[NOTE]
====
. “It,” masc. sing., possibly referring to the precious metal.
====

[[v26-7-21]]

^<<v26-7-21,21>>^ And I will give it into the hand of the strangers for plunder and to the wicked ones of the earth for spoil, and they will certainly profane it.

[[v26-7-22]]

^<<v26-7-22,22>>^ “‘And I shall have to turn away my face from them, and they will actually profane my concealed place,^&#42;1^ and into it^&#42;2^ robbers will really come and profane it.

[NOTE]
====
. Or, “hidden things.”
. “It,” fem. sing., likely referring to the holy city.
====

[[v26-7-23]]

^<<v26-7-23,23>>^ “‘Make the chain,^&#42;1^ for the land^&#42;2^ itself has become full of bloodstained judgment^&#42;3^ and the city itself has become full of violence.

[NOTE]
====
. “Slaughter,” by a slight correction.
. Or, “the earth.” Heb., ha·ʼaʹrets.
. Lit., “judgment of bloods.”
====

[[v26-7-24]]

^<<v26-7-24,24>>^ And I will bring in the worst ones of the nations, and they will certainly take possession of their houses, and I will cause the pride of the strong ones to cease, and their sanctuaries must be profaned.

[[v26-7-25]]

^<<v26-7-25,25>>^ There will come anguish, and they will certainly seek peace but there will be none.

[[v26-7-26]]

^<<v26-7-26,26>>^ There will come adversity upon adversity, and there will occur report upon report, and people will actually seek a vision from a prophet, and the law itself will perish from a priest and counsel from elderly men.

[[v26-7-27]]

^<<v26-7-27,27>>^ The king himself will go into mourning; even a chieftain will clothe himself with desolation, and the very hands of the people of the land^&#42;1^ will get disturbed. According to their way I shall act toward them, and with their judgments I shall judge them; and they will have to know that I am Jehovah.’”

[NOTE]
====
. “The people of the land.” Heb., ʽam-ha·ʼaʹrets. Later used in a contemptuous sense. Compare Joh 7:47-49.
====

'''

xref:026-ezekiel/026-ezekiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezekiel/026-ezekiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]