include::./index.adoc[]

[[v26-4-0]]
=== Ezekiel, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-4-1]]

^<<v26-4-1,1>>^ “And you, O son of man, take for yourself a brick, and you must put it before you and engrave upon it a city, even Jerusalem.

[[v26-4-2]]

^<<v26-4-2,2>>^ And you must lay siege against it and build a siege wall against it and throw up^&#42;1^ a siege rampart against it and set encampments against it and put battering rams all around against it.

[NOTE]
====
. Lit., “pour out.”
====

[[v26-4-3]]

^<<v26-4-3,3>>^ And as for you, take to yourself an iron griddle, and you must put it as an iron wall between you and the city, and you must fix your face against it, and it must get to be in a siege, and you must besiege it. It is a sign to the house of Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ “And as for you, lie upon your left side, and you must lay the error of the house of Israel upon it. For the number of the days that you will lie upon it you will carry their error.

[[v26-4-5]]

^<<v26-4-5,5>>^ And I myself must give to you the years of their error to the number of three hundred and ninety days, and you must carry the error of the house of Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ And you must complete them.
“And you must lie upon your right side in the second case, and you must carry the error of the house of Judah forty days. A day for a year, a day for a year, is what I have given you.

[[v26-4-7]]

^<<v26-4-7,7>>^ And to the siege of Jerusalem you will fix your face, with your arm bared, and you must prophesy against it.

[[v26-4-8]]

^<<v26-4-8,8>>^ “And, look! I will put cords upon you that you may not turn yourself from your one side to your other side, until you will have completed the days of your siege.

[[v26-4-9]]

^<<v26-4-9,9>>^ “And as for you, take for yourself wheat and barley and broad beans and lentils and millet and spelt, and you must put them in one utensil and make them into bread^&#42;1^ for you, for the number of the days that you are lying upon your side; three hundred and ninety days you will eat it.

[NOTE]
====
. Or, “food.”
====

[[v26-4-10]]

^<<v26-4-10,10>>^ And your food that you will eat will be by weight—twenty shekels a day. From time to time you will eat it.

[[v26-4-11]]

^<<v26-4-11,11>>^ “And water you will drink merely by measure, the sixth part of a hin.^&#42;1^ From time to time you will drink.

[NOTE]
====
. A hin equaled 3.67 L (7.75 pt).
====

[[v26-4-12]]

^<<v26-4-12,12>>^ “And as a round cake of barley you will eat it; and as for it, upon dung cakes of the excrement of mankind^&#42;1^ you will bake it before their eyes.”

[NOTE]
====
. Lit., “the earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v26-4-13]]

^<<v26-4-13,13>>^ And Jehovah went on to say: “Just like this the sons of Israel will eat their bread unclean among the nations to which I shall disperse them.”

[[v26-4-14]]

^<<v26-4-14,14>>^ And I proceeded to say: “Alas, O Sovereign Lord Jehovah! Look! My soul is not a defiled one; neither a body &#91;already&#93; dead nor a torn animal have I eaten from my youth up, even until now, and into my mouth there has come no foul flesh.”

[[v26-4-15]]

^<<v26-4-15,15>>^ Accordingly he said to me: “See, I have given you cattle manure instead of the dung cakes of mankind, and you must make your bread upon it.”

[[v26-4-16]]

^<<v26-4-16,16>>^ And he continued saying to me: “Son of man, here I am breaking the rods around which ring-shaped loaves are suspended,^&#42;1^ in Jerusalem, and they will have to eat bread by weight and in anxious care, and it will be by measure and in horror that they will drink water itself,

[NOTE]
====
. Lit., “the rod of bread.”
====

[[v26-4-17]]

^<<v26-4-17,17>>^ to the intent that they may be lacking bread and water and they may look astonished at one another and rot away in their error.

'''

xref:026-ezekiel/026-ezekiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezekiel/026-ezekiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]