include::./index.adoc[]

[[v26-36-0]]
=== Ezekiel, 36
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-36-1]]

^<<v26-36-1,1>>^ “And as for you, O son of man, prophesy concerning the mountains of Israel, and you must say, ‘O mountains of Israel, hear the word of Jehovah.

[[v26-36-2]]

^<<v26-36-2,2>>^ This is what the Sovereign Lord Jehovah has said: “For the reason that the enemy has said against YOU, ‘Aha! Even the high places of old time—as a possession it has become ours!’”’

[[v26-36-3]]

^<<v26-36-3,3>>^ “Therefore prophesy, and you must say, ‘This is what the Sovereign Lord Jehovah has said: “For the reason, even for the reason that there has been a lying desolate and a snapping at YOU from all sides, in order for YOU to become a possession to the remaining ones of the nations and YOU continue being talked about with the tongue and there is a bad report among people,

[[v26-36-4]]

^<<v26-36-4,4>>^ therefore, O mountains of Israel, hear the word of the Sovereign Lord Jehovah! This is what the Sovereign Lord Jehovah has said to the mountains and to the hills, to the streambeds and to the valleys and to the devastated places that were laid desolate and to the abandoned cities that have come to be for plunder and for ridicule to the remaining ones of the nations that are round about;

[[v26-36-5]]

^<<v26-36-5,5>>^ therefore this is what the Sovereign Lord Jehovah has said, ‘Certainly in the fire of my zeal I will speak against the remaining ones of the nations and against Eʹdom, all of it, those who have given my land to themselves as a possession with the rejoicing of all the heart, with scorn in &#91;the&#93; soul, for the sake of its pasture ground &#91;and&#93; for the plunder.’”’

[[v26-36-6]]

^<<v26-36-6,6>>^ “Therefore prophesy concerning the soil of Israel, and you must say to the mountains and to the hills, to the streambeds and to the valleys, ‘This is what the Sovereign Lord Jehovah has said: “Look! I myself in my zeal and in my rage must speak, for the reason that humiliation by nations is what YOU have borne.”’

[[v26-36-7]]

^<<v26-36-7,7>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘I myself have raised my hand &#91;in an oath&#93; that the nations that YOU have round about—they themselves will bear their own humiliation.

[[v26-36-8]]

^<<v26-36-8,8>>^ And YOU yourselves, O mountains of Israel, will give forth YOUR very own boughs and bear YOUR own fruitage for my people Israel, for they have drawn near to the point of coming in.

[[v26-36-9]]

^<<v26-36-9,9>>^ For here I am in favor of YOU, and I shall certainly turn toward YOU, and YOU will actually be cultivated and sown with seed.

[[v26-36-10]]

^<<v26-36-10,10>>^ And I will multiply upon YOU humankind,^&#42;1^ the whole house of Israel, all of it, and the cities must become inhabited, and the devastated places themselves will be rebuilt.

[NOTE]
====
. Or, “earthling men.” Heb., ʼa·dhamʹ; Lat., hoʹmi·nes.
====

[[v26-36-11]]

^<<v26-36-11,11>>^ Yes, I will multiply upon YOU humankind and animalkind, and they will certainly multiply and become fruitful, and I shall actually cause YOU to be inhabited as in YOUR former condition and I will do more good than in YOUR initial state; and YOU will have to know that I am Jehovah.

[[v26-36-12]]

^<<v26-36-12,12>>^ And upon YOU I will cause humankind to walk, even my people Israel, and they must take possession of YOU,^&#42;1^ and YOU must become a hereditary possession to them, and YOU will not bereave them again of any more children.’”

[NOTE]
====
. “You,” pl., LXXSy; MTVg, “you,” sing.
====

[[v26-36-13]]

^<<v26-36-13,13>>^ “This is what the Sovereign Lord Jehovah has said, ‘For the reason that there are those saying to YOU: “A devourer of humankind is what you yourself are, and &#91;a land&#93;^&#42;1^ bereaving your nations of children is what you have become,”’

[NOTE]
====
. Lit., “one,” fem., referring to the land, fem.
====

[[v26-36-14]]

^<<v26-36-14,14>>^ ‘therefore humankind you will no more devour, and your nations you will no more bereave of children,’^&#42;1^ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. “Bereave of children,” MmarginLXXSy and many Heb. mss; M, “cause to stumble.”
====

[[v26-36-15]]

^<<v26-36-15,15>>^ ‘And I shall cause no further humiliating talk by the nations to be heard concerning you, and reproach by peoples you will bear no more, and your nations you will no more cause to stumble,’ is the utterance of the Sovereign Lord Jehovah.”

[[v26-36-16]]

^<<v26-36-16,16>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-36-17]]

^<<v26-36-17,17>>^ “Son of man, the house of Israel &#91;were&#93; dwelling upon their soil, and they kept making it unclean with their way and with their dealings. Like the uncleanness of menstruation their way has become before me.

[[v26-36-18]]

^<<v26-36-18,18>>^ And I proceeded to pour out my rage upon them on account of the blood that they had poured out upon the land, which &#91;land&#93; they had made unclean with their dungy idols.

[[v26-36-19]]

^<<v26-36-19,19>>^ And I proceeded to scatter them among the nations, so that they were dispersed among the lands. According to their way and according to their dealings I judged them.

[[v26-36-20]]

^<<v26-36-20,20>>^ So they^&#42;1^ came in to the nations where they came in, and people^&#42;2^ proceeded to profane my holy name in saying with reference to them, ‘These are the people of Jehovah, and from his land they have gone out.’

[NOTE]
====
. “They,” TLXXSyVg and some Heb. mss; M, “he,” or, “it.”
. Lit., “they.”
====

[[v26-36-21]]

^<<v26-36-21,21>>^ And I shall have compassion on my holy name, which the house of Israel have profaned among the nations where they have come in.”

[[v26-36-22]]

^<<v26-36-22,22>>^ “Therefore say to the house of Israel, ‘This is what the Sovereign Lord Jehovah has said: “Not for YOUR sakes am I doing &#91;it&#93;, O house of Israel, but for my holy name, which YOU have profaned among the nations where YOU have come in.”’

[[v26-36-23]]

^<<v26-36-23,23>>^ ‘And I shall certainly sanctify^&#42;1^ my great name, which was being profaned among the nations, which YOU profaned in the midst of them; and the nations will have to know that I am Jehovah,’ is the utterance of the Sovereign Lord Jehovah, ‘when I am sanctified among YOU before their eyes.

[NOTE]
====
. Or, “And I shall certainly hold sacred (treat as holy).” Heb., weqid·dash·tiʹ; Gr., ha·gi·aʹso; Lat., sanc·ti·fi·caʹbo.
====

[[v26-36-24]]

^<<v26-36-24,24>>^ And I will take YOU out of the nations and collect YOU together out of all the lands and bring YOU in upon YOUR soil.

[[v26-36-25]]

^<<v26-36-25,25>>^ And I will sprinkle upon YOU clean water, and YOU will become clean; from all YOUR impurities and from all YOUR dungy idols I shall cleanse YOU.

[[v26-36-26]]

^<<v26-36-26,26>>^ And I will give YOU a new heart, and a new spirit I shall put inside YOU, and I will take away the heart of stone from YOUR flesh and give YOU a heart of flesh.

[[v26-36-27]]

^<<v26-36-27,27>>^ And my spirit I shall put inside YOU, and I will act so that in my regulations YOU will walk, and my judicial decisions YOU will keep and actually carry out.

[[v26-36-28]]

^<<v26-36-28,28>>^ And YOU will certainly dwell in the land that I gave to YOUR forefathers, and YOU must become my people and I myself shall become YOUR God.’^&#42;1^

[NOTE]
====
. Lit., “to you for God.” Heb., la·khemʹ lEʼ·lo·himʹ.
====

[[v26-36-29]]

^<<v26-36-29,29>>^ “‘And I will save YOU from all YOUR impurities and call to the grain and make it abound, and I shall put upon YOU no famine.

[[v26-36-30]]

^<<v26-36-30,30>>^ And I shall certainly make the fruitage of the tree abound, and the produce of the field, in order that YOU may no more receive among the nations the reproach of famine.

[[v26-36-31]]

^<<v26-36-31,31>>^ And YOU will be bound to remember YOUR bad ways and YOUR dealings that were not good, and YOU will be bound to feel a loathing at YOUR own person on account of YOUR errors and on account of YOUR detestable things.

[[v26-36-32]]

^<<v26-36-32,32>>^ Not for YOUR sakes am I doing &#91;this&#93;,’ is the utterance of the Sovereign Lord Jehovah, ‘let it be known to YOU. Be ashamed and feel humiliation because of YOUR ways, O house of Israel.’

[[v26-36-33]]

^<<v26-36-33,33>>^ “This is what the Sovereign Lord Jehovah has said, ‘In the day of my cleansing YOU from all YOUR errors I will also cause the cities to be inhabited, and the devastated places must be rebuilt.

[[v26-36-34]]

^<<v26-36-34,34>>^ And the desolated land itself will be cultivated, whereas it had become a desolate waste before the eyes of every passerby.

[[v26-36-35]]

^<<v26-36-35,35>>^ And people will certainly say: “That land yonder which was laid desolate has become like the garden^&#42;1^ of Eʹden, and the cities that were a waste and that were laid desolate and that were torn down are fortified; they have become inhabited.”

[NOTE]
====
. “Like the garden.” Heb., keghanʹ; Syr., par·dai·saʼ, “the paradise.”
====

[[v26-36-36]]

^<<v26-36-36,36>>^ And the nations that will be left remaining round about YOU will have to know that I myself, Jehovah, have built the things torn down, I have planted what has been laid desolate. I myself, Jehovah, have spoken and I have done &#91;it&#93;.’

[[v26-36-37]]

^<<v26-36-37,37>>^ “This is what the Sovereign Lord Jehovah has said, ‘This is what I shall yet let myself be searched for by the house of Israel to do for them: I shall multiply them like a flock with men.^&#42;1^

[NOTE]
====
. Or, “humankind.” Heb., ʼa·dhamʹ; Lat., hoʹmi·num.
====

[[v26-36-38]]

^<<v26-36-38,38>>^ Like a flock of holy persons, like the flock of Jerusalem in her festal seasons, thus the cities that had been a waste will become full of a flock of men; and people will have to know that I am Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezekiel/026-ezekiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]