include::./index.adoc[]

[[v26-13-0]]
=== Ezekiel, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-13-1]]

^<<v26-13-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-13-2]]

^<<v26-13-2,2>>^ “Son of man, prophesy concerning the prophets of Israel who are prophesying, and you must say to those prophesying out of their own heart, ‘Hear the word of Jehovah.

[[v26-13-3]]

^<<v26-13-3,3>>^ This is what the Sovereign Lord Jehovah has said: “Woe to the stupid prophets, who are walking after their own spirit,^&#42;1^ when there is nothing that they have seen!

[NOTE]
====
. “Their own spirit.” Heb., ru·chamʹ; Lat., spiʹri·tum; Gr., kar·diʹas, “heart.”
====

[[v26-13-4]]

^<<v26-13-4,4>>^ Like foxes in the devastated places are what your own prophets have become, O Israel.

[[v26-13-5]]

^<<v26-13-5,5>>^ YOU men will certainly not go up into the gaps, neither will YOU build up a stone wall in behalf of the house of Israel, in order to stand in the battle^&#42;1^ in the day of Jehovah.”

[NOTE]
====
. Or, “war.”
====

[[v26-13-6]]

^<<v26-13-6,6>>^ “They have visioned what is untrue and a lying divination, those who are saying, ‘The utterance of Jehovah is,’ when Jehovah himself has not sent them, and they have waited to have a word come true.

[[v26-13-7]]

^<<v26-13-7,7>>^ Is it not an untrue vision that YOU men have visioned, and a lying divination that YOU have said, when saying, ‘The utterance of Jehovah is,’ when I myself have spoken nothing?”’

[[v26-13-8]]

^<<v26-13-8,8>>^ “‘Therefore this is what the Sovereign Lord Jehovah has said: “‘For the reason that YOU men have spoken untruth and YOU have visioned a lie, therefore here I am against YOU,’ is the utterance of the Sovereign Lord Jehovah.”

[[v26-13-9]]

^<<v26-13-9,9>>^ And my hand has come to be against the prophets that are visioning untruth and that are divining a lie. In the intimate group of my people they will not continue on, and in the register^&#42;1^ of the house of Israel they will not be written, and to the soil of Israel they will not come; and YOU people^&#42;2^ will have to know that I am the Sovereign Lord Jehovah,

[NOTE]
====
. Lit., “writing.”
. “You people,” MTSyVg; LXX, “they.”
====

[[v26-13-10]]

^<<v26-13-10,10>>^ for the reason, yes, for the reason that they have led my people astray, saying, “There is peace!” when there is no peace, and there is one that is building a partition wall, but in vain there are those plastering it with whitewash.’

[[v26-13-11]]

^<<v26-13-11,11>>^ “Say to those plastering with whitewash that it will fall. A flooding downpour will certainly occur, and YOU, O hailstones, will fall,^&#42;1^ and a blast^&#42;2^ of windstorms itself will cause a splitting.

[NOTE]
====
. According to M; LXX, “and I shall give hurling-stones against their bondings, and they will fall”; Vg, “and I shall give very large stones rushing from above.”
. “And a blast of.” Heb., weruʹach; Gr., pneuʹma; Lat., venʹtum, “wind.”
====

[[v26-13-12]]

^<<v26-13-12,12>>^ And, look! the wall must fall. Will it not be said to YOU men, ‘Where is the coating^&#42;1^ with which YOU did the plastering?’

[NOTE]
====
. Or, “plaster.”
====

[[v26-13-13]]

^<<v26-13-13,13>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘I will also cause a blast of windstorms to burst forth in my rage, and in my anger there will occur a flooding downpour, and in rage there will be hailstones for an extermination.

[[v26-13-14]]

^<<v26-13-14,14>>^ And I will tear down the wall that YOU men have plastered with whitewash and bring it into contact with the earth, and its foundation must be exposed. And she^&#42;1^ will certainly fall, and YOU must come to an end in the midst of her; and YOU will have to know that I am Jehovah.’

[NOTE]
====
. Or, “it,” fem. sing.; not referring to the “wall,” masc., but possibly to the city.
====

[[v26-13-15]]

^<<v26-13-15,15>>^ “‘And I will bring my rage to its finish upon the wall and upon those plastering it with whitewash, and I shall say to YOU men: “The wall is no more, and those plastering it are no more,

[[v26-13-16]]

^<<v26-13-16,16>>^ the prophets of Israel that are prophesying to Jerusalem and that are visioning for her a vision of peace, when there is no peace,”’ is the utterance of the Sovereign Lord Jehovah.

[[v26-13-17]]

^<<v26-13-17,17>>^ “And as for you, O son of man, set your face against the daughters of your people who are acting as prophetesses out of their own heart, and prophesy against them.

[[v26-13-18]]

^<<v26-13-18,18>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said: “Woe to the women sewing bands together upon all elbows^&#42;1^ and making veils upon the head of every size in order to hunt souls!^&#42;2^ Are the souls that YOU women hunt down the ones belonging to my people, and the souls belonging to YOU the ones that YOU preserve alive?

[NOTE]
====
. Lit., “the joints of hands.”
. “Souls.” Heb., nepha·shohthʹ, fem. pl.; Gr., psy·khasʹ; Lat., aʹni·mas.
====

[[v26-13-19]]

^<<v26-13-19,19>>^ And will YOU profane me toward my people for the handfuls of barley and for the morsels of bread, in order to put to death the souls that ought not to die and in order to preserve alive the souls that ought not to live by YOUR lie to my people, the hearers of a lie?”’

[[v26-13-20]]

^<<v26-13-20,20>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Here I am against the bands of YOU women, with which YOU are hunting down the souls as though they were flying things,^&#42;1^ and I will rip them from off YOUR arms and let go^&#42;2^ the souls that YOU are hunting down, souls^&#42;3^ as though they were flying things.

[NOTE]
====
. Or, “as though flies.”
. Lit., “and send away.”
. “Souls.” Heb., nepha·shimʹ, masc., pl. of neʹphesh, fem. The only occurrence in M; hence, probably meant to read, choph·shimʹ, “free ones.”
====

[[v26-13-21]]

^<<v26-13-21,21>>^ And I will rip away YOUR veils and deliver my people out of YOUR hand, and they will no more prove to be in YOUR hand something caught in the hunt; and YOU will have to know that I am Jehovah.

[[v26-13-22]]

^<<v26-13-22,22>>^ By reason of dejecting the heart of a righteous one with falsehood, when I myself had not caused him pain, and for making the hands of a wicked one strong so that he would not turn back from his bad way in order to preserve him alive,

[[v26-13-23]]

^<<v26-13-23,23>>^ therefore untruth YOU women will not keep on visioning, and divination YOU will divine no longer; and I will deliver my people out of YOUR hand, and YOU will have to know that I am Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-012.adoc#v26-12-0[&#60; Capítulo Anterior] | <<v26-13-0,Topo>> | xref:026-ezekiel/026-ezekiel-014.adoc#v26-14-0[Próximo Capítulo &#62;]