include::./index.adoc[]

[[v26-6-0]]
=== Ezekiel, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-6-1]]

^<<v26-6-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-6-2]]

^<<v26-6-2,2>>^ “Son of man, set your face toward the mountains of Israel and prophesy to them.

[[v26-6-3]]

^<<v26-6-3,3>>^ And you must say, ‘O mountains of Israel, hear the word of the Sovereign Lord Jehovah: This is what the Sovereign Lord Jehovah has said to the mountains and to the hills, to the streambeds and to the valleys: “Here I am! I am bringing upon YOU a sword, and I shall certainly destroy YOUR high places.

[[v26-6-4]]

^<<v26-6-4,4>>^ And YOUR altars must be made desolate and YOUR incense stands must be broken, and I will cause YOUR slain ones to fall before YOUR dungy idols.

[[v26-6-5]]

^<<v26-6-5,5>>^ And I will put the carcasses of the sons of Israel before their dungy idols, and I will scatter YOUR bones all around YOUR altars.

[[v26-6-6]]

^<<v26-6-6,6>>^ In all YOUR dwelling places the very cities will become devastated and the high places themselves will become desolated, in order that they may lie devastated and YOUR altars may lie desolated and be actually broken and YOUR dungy idols may be actually made to cease and YOUR incense stands cut down and YOUR works wiped out.

[[v26-6-7]]

^<<v26-6-7,7>>^ And the slain one will certainly fall in the midst of YOU, and YOU will have to know that I am Jehovah.^&#42;1^

[NOTE]
====
. “And you will have to know that I am Jehovah.” Heb., wi·dhaʽ·temʹ ki-ʼaniʹ Yehwahʹ. The first of more than 60 occurrences of this phrase in Ezekiel, referring to the vindication of Jehovah’s name on earth.
====

[[v26-6-8]]

^<<v26-6-8,8>>^ “‘“And when it occurs I will let YOU have as a remnant the ones escaping from the sword among the nations, when YOU get scattered among the lands.

[[v26-6-9]]

^<<v26-6-9,9>>^ And YOUR escaped ones will certainly remember me among the nations to which they will have been taken captive, because I have been broken up at their fornicating heart that has turned aside from me and at their eyes that are going in fornication after their dungy idols; and they will certainly feel a loathing in their faces at the bad things that they have done in all their detestable things.

[[v26-6-10]]

^<<v26-6-10,10>>^ And they will have to know that I am Jehovah; not in vain did I speak about doing to them this calamitous thing.”’

[[v26-6-11]]

^<<v26-6-11,11>>^ “This is what the Sovereign Lord Jehovah has said, ‘Clap your hands and stamp with your foot, and say: “Alas!” on account of all the bad detestable things of the house of Israel, because by the sword, by the famine and by the pestilence they will fall.

[[v26-6-12]]

^<<v26-6-12,12>>^ As for the one far away, by the pestilence he will die; and as for the one that is nearby, by the sword he will fall; and as for the one that has been left remaining and that has been safeguarded, by the famine he will die, and I will bring to its finish my rage against them.

[[v26-6-13]]

^<<v26-6-13,13>>^ And YOU people will have to know that I am Jehovah, when their slain ones come to be in the midst of their dungy idols, all around their altars, upon every high hill, on all the tops of the mountains and under every luxuriant tree and under every branchy big tree, the place where they have offered a restful^&#42;1^ odor to all their dungy idols.

[NOTE]
====
. Or, “soothing; tranquilizing; appeasing.”
====

[[v26-6-14]]

^<<v26-6-14,14>>^ And I will stretch out my hand against them and make the land a desolate waste, even a desolation worse than the wilderness toward Dibʹlah,^&#42;1^ in all their dwelling places. And they will have to know that I am Jehovah.’”

[NOTE]
====
. “Diblah,” MLXXVg; one Heb. ms, “Riblah.”
====

'''

xref:026-ezekiel/026-ezekiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezekiel/026-ezekiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]