include::./index.adoc[]

[[v26-35-0]]
=== Ezekiel, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-35-1]]

^<<v26-35-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-35-2]]

^<<v26-35-2,2>>^ “Son of man, set your face against the mountainous region of Seʹir and prophesy against it.

[[v26-35-3]]

^<<v26-35-3,3>>^ And you must say to it, ‘This is what the Sovereign Lord Jehovah has said: “Here I am against you, O mountainous region of Seʹir, and I will stretch out my hand against you and make you a desolate waste, even a desolation.

[[v26-35-4]]

^<<v26-35-4,4>>^ Your cities I shall set as a devastated place, and you yourself will become a sheer desolate waste; and you will have to know that I am Jehovah,

[[v26-35-5]]

^<<v26-35-5,5>>^ for the reason that you proved to have an indefinitely lasting enmity and you kept delivering the sons of Israel over to the power^&#42;1^ of the sword, in the time of their disaster, in the time of &#91;their&#93; final error.”’^&#42;2^

[NOTE]
====
. Lit., “hands.”
. Lit., “the time of the error of [the] end.”
====

[[v26-35-6]]

^<<v26-35-6,6>>^ “‘Therefore as I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘because it was for blood that I was preparing you, blood itself will also pursue you. Surely it was blood that you hated, and blood itself will^&#42;1^ pursue you.

[NOTE]
====
. Or, “Since blood you did not hate, blood itself also will.”
====

[[v26-35-7]]

^<<v26-35-7,7>>^ And I shall certainly make the mountainous region of Seʹir a desolate waste, even a desolation, and I will cut off from it the one passing through and the one returning.

[[v26-35-8]]

^<<v26-35-8,8>>^ And I will fill its mountains with its slain ones; as for your hills and your valleys and all your streambeds, the very ones slain by &#91;the&#93; sword will fall in them.

[[v26-35-9]]

^<<v26-35-9,9>>^ Indefinitely lasting desolate wastes are what I shall make you, and your own cities will not be inhabited; and YOU people will have to know that I am Jehovah.’

[[v26-35-10]]

^<<v26-35-10,10>>^ “By reason of your saying, ‘These two nations and these two lands—they will become my own, and we shall certainly take possession of each &#91;land&#93;,’ whereas Jehovah himself happened to be right there,

[[v26-35-11]]

^<<v26-35-11,11>>^ ‘therefore as I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘I will act also according to your anger and according to your jealousy that you have expressed owing to your feelings of hatred toward them; and I will make myself known among them^&#42;1^ when I judge you.

[NOTE]
====
. “Among them,” MTSyVg; LXX, “to you.”
====

[[v26-35-12]]

^<<v26-35-12,12>>^ And you will have to know that I myself, Jehovah, have heard all your disrespectful things that you have said concerning the mountains of Israel, saying: “They have^&#42;1^ been laid desolate. To us they have been given for food.”

[NOTE]
====
. “They have,” Mmargin; MT, “She has.”
====

[[v26-35-13]]

^<<v26-35-13,13>>^ And YOU people kept acting in great style against me with YOUR mouths,^&#42;1^ and YOU have multiplied against me YOUR words. I myself have heard &#91;them&#93;.’

[NOTE]
====
. Or, “you people maintain a big mouth against me.”
====

[[v26-35-14]]

^<<v26-35-14,14>>^ “This is what the Sovereign Lord Jehovah has said, ‘At the same time that all the earth rejoices, a desolate waste is what I shall make of you.

[[v26-35-15]]

^<<v26-35-15,15>>^ Just as there was rejoicing on your part at the inheritance of the house of Israel because it was laid desolate, the same thing I shall make of you. A desolate waste is what you will become, O mountainous region of Seʹir, even all Eʹdom, all of it; and they will have to know that I am Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezekiel/026-ezekiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]