include::./index.adoc[]

[[v26-17-0]]
=== Ezekiel, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-17-1]]

^<<v26-17-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-17-2]]

^<<v26-17-2,2>>^ “Son of man, propound a riddle and compose a proverbial saying toward the house of Israel.

[[v26-17-3]]

^<<v26-17-3,3>>^ And you must say, ‘This is what the Sovereign Lord Jehovah has said: “The great eagle, having great wings, with long pinions, full of plumage, which had color variety, came to Lebʹa·non and proceeded to take the treetop of the cedar.

[[v26-17-4]]

^<<v26-17-4,4>>^ He plucked off the very top of its young shoots and came bringing it to the land of Caʹnaan; in a city of traders he placed it.

[[v26-17-5]]

^<<v26-17-5,5>>^ Furthermore, he took some of the seed of the land and put it in a field for seed. As a willow by vast waters, as a willow tree he placed it.

[[v26-17-6]]

^<<v26-17-6,6>>^ And it began to sprout and gradually became a luxuriantly growing vine low in height, inclined to turn its foliage inward; and as for its roots, they gradually came to be under it. And it finally became a vine and produced shoots and sent forth branches.

[[v26-17-7]]

^<<v26-17-7,7>>^ “‘“And there came to be another great eagle, having great wings, and having large pinions, and, look! this very vine stretched its roots hungrily toward him. And its foliage it thrust out to him in order &#91;for him&#93; to irrigate it, away from the garden beds where it was planted.

[[v26-17-8]]

^<<v26-17-8,8>>^ Into a good field, by vast waters, it was already transplanted, in order to produce boughs and to bear fruit, to become a majestic vine.”’

[[v26-17-9]]

^<<v26-17-9,9>>^ “Say, ‘This is what the Sovereign Lord Jehovah has said: “Will it have success? Will not someone tear out its very roots and make its very fruit scaly? And must &#91;not&#93; all its freshly plucked sprouts become dry? It will become dry. Neither by a great arm nor by a multitudinous people will it have to be lifted up from its roots.

[[v26-17-10]]

^<<v26-17-10,10>>^ And, look! although transplanted, will it have success? Will it not dry up completely, even as when the east wind touches it? In the garden beds of its sprout it will dry up.”’”

[[v26-17-11]]

^<<v26-17-11,11>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-17-12]]

^<<v26-17-12,12>>^ “Say, please, to the rebellious house, ‘Do YOU people actually not know what these things mean?’ Say, ‘Look! The king of Babylon^&#42;1^ came to Jerusalem and proceeded to take its king and its princes and bring them to himself at Babylon.

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v26-17-13]]

^<<v26-17-13,13>>^ Furthermore, he took one of the royal seed and concluded^&#42;1^ a covenant with him and brought him into an oath; and the foremost men of the land he took away,

[NOTE]
====
. Lit., “cut.”
====

[[v26-17-14]]

^<<v26-17-14,14>>^ in order that the kingdom might become low, unable to lift itself up, that by keeping his covenant it^&#42;1^ might stand.

[NOTE]
====
. “It,” M, fem. sing., referring to the “kingdom”; margin of one Heb. ms, “him,” masc. sing., referring to the king.
====

[[v26-17-15]]

^<<v26-17-15,15>>^ But he finally rebelled against him in sending his messengers to Egypt, &#91;for it&#93; to give him horses and a multitudinous people. Will he have success? Will he escape, he who is doing these things, and who has broken a covenant? And will he actually escape?’

[[v26-17-16]]

^<<v26-17-16,16>>^ “‘“As I am alive,” is the utterance of the Sovereign Lord Jehovah, “in the place of the king who put in as king the one that despised his oath and that broke his covenant, with him in the midst of Babylon he will die.

[[v26-17-17]]

^<<v26-17-17,17>>^ And by a great military force and by a multitudinous congregation Pharʹaoh will not make him effective in the war, by throwing up a siege rampart and by building a siege wall, in order to cut off many souls.

[[v26-17-18]]

^<<v26-17-18,18>>^ And he has despised an oath in breaking a covenant, and, look! he had given his hand and has done even all these things. He will not make his escape.”’

[[v26-17-19]]

^<<v26-17-19,19>>^ “‘Therefore this is what the Sovereign Lord Jehovah has said: “As I am alive, surely my oath that he has despised and my covenant that he has broken—I will even bring it upon his head.

[[v26-17-20]]

^<<v26-17-20,20>>^ And I will spread over him my net, and he will certainly be caught in my hunting net; and I will bring him to Babylon and put myself on judgment with him there respecting his unfaithfulness with which he acted against me.

[[v26-17-21]]

^<<v26-17-21,21>>^ And as regards all the fugitives of his in all his bands, by the sword they will fall, and the ones left remaining will be spread abroad even to every wind.^&#42;1^ And YOU people will have to know that I myself, Jehovah, have spoken &#91;it&#93;.”’

[NOTE]
====
. “To every wind,” representing direction. Heb., lekhol-ruʹach; Gr., eis panʹta aʹne·mon; Lat., in oʹmnem venʹtum. Compare Ge 1:2 ftn, “Force.”
====

[[v26-17-22]]

^<<v26-17-22,22>>^ “‘This is what the Sovereign Lord Jehovah has said: “I myself will also take and put some of the lofty treetop of the cedar; from the top of its twigs I shall pluck off a tender one and I will myself transplant &#91;it&#93; upon a high and lofty mountain.

[[v26-17-23]]

^<<v26-17-23,23>>^ On the mountain of the height of Israel I shall transplant it, and it will certainly bear boughs and produce fruit and become a majestic cedar. And under it there will actually reside all the birds of every wing; in the shadow of its foliage they will reside.

[[v26-17-24]]

^<<v26-17-24,24>>^ And all the trees of the field will have to know that I myself, Jehovah, have abased the high tree, have put on high the low tree, have dried up the still-moist tree and have made the dry tree blossom. I myself, Jehovah, have spoken and have done &#91;it&#93;.”’”

'''

xref:026-ezekiel/026-ezekiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezekiel/026-ezekiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]