include::./index.adoc[]

[[v26-14-0]]
=== Ezekiel, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-14-1]]

^<<v26-14-1,1>>^ And men^&#42;1^ from the elderly ones of Israel proceeded to come to me and sit down before me.

[NOTE]
====
. “Men.” Heb., ʼana·shimʹ, pl. of ʼish.
====

[[v26-14-2]]

^<<v26-14-2,2>>^ Then the word of Jehovah occurred to me, saying:

[[v26-14-3]]

^<<v26-14-3,3>>^ “Son of man, as regards these men, they have brought up their dungy idols upon their heart, and the stumbling block causing their error they have put in front of their faces. Shall I be inquired of at all by them?

[[v26-14-4]]

^<<v26-14-4,4>>^ Therefore speak with them and you must say to them, ‘This is what the Sovereign Lord Jehovah has said: “Any man at all^&#42;1^ of the house of Israel that brings up his dungy idols upon his heart and that places the very stumbling block causing his error in front of his face and that actually comes to the prophet, I, Jehovah, I will let myself be brought to answer him in the matter according to the multitude of his dungy idols,

[NOTE]
====
. “Any man at all.” Heb., ʼish ʼish.
====

[[v26-14-5]]

^<<v26-14-5,5>>^ for the purpose of catching the house of Israel by their heart, because they have withdrawn themselves from me through their dungy idols—all of them.”’

[[v26-14-6]]

^<<v26-14-6,6>>^ “Therefore say to the house of Israel, ‘This is what the Sovereign Lord Jehovah has said: “Come back and turn yourselves back from YOUR dungy idols and turn YOUR faces back even from all YOUR detestable things;

[[v26-14-7]]

^<<v26-14-7,7>>^ for any man at all from the house of Israel or from the alien residents that reside as aliens in Israel, that withdraws himself from following me and that brings up his dungy idols upon his heart and that sets the very stumbling block causing his error in front of his face and that actually comes to the prophet to make inquiry for himself by me, I, Jehovah, I am letting myself be brought to answer him by myself.

[[v26-14-8]]

^<<v26-14-8,8>>^ And I must set my face against that man^&#42;1^ and place him for a sign and for proverbial sayings, and I must cut him off from the midst of my people; and YOU people will have to know that I am Jehovah.”’

[NOTE]
====
. “Against that man.” Heb., ba·ʼishʹ ha·huʼʹ.
====

[[v26-14-9]]

^<<v26-14-9,9>>^ “‘And as for the prophet, in case he gets fooled and actually speaks a word, I myself, Jehovah, have fooled that prophet; and I will stretch out my hand against him and annihilate him from the midst of my people Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ And they will have to bear their error. The error of the inquirer will prove to be just the same as the error of the prophet,

[[v26-14-11]]

^<<v26-14-11,11>>^ in order that those of the house of Israel may no more go wandering off from following me and may no more go defiling themselves with all their transgressions. And they must become my people and I myself shall become their God,’^&#42;1^ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. Lit., “to them for God.” Heb., la·hemʹ lEʼ·lo·himʹ.
====

[[v26-14-12]]

^<<v26-14-12,12>>^ And the word of Jehovah continued to come to me, saying:

[[v26-14-13]]

^<<v26-14-13,13>>^ “Son of man, as regards a land, in case it commits sin against me in acting unfaithfully, I will also stretch out my hand against it and break for it the rods around which ring-shaped loaves are suspended,^&#42;1^ and I will send upon it famine and cut off from it earthling man and domestic animal.”

[NOTE]
====
. Lit., “the staff of bread.”
====

[[v26-14-14]]

^<<v26-14-14,14>>^ “‘And had these three men^&#42;1^ proved to be in the midst of it, Noah, Daniel and Job, they themselves because of their righteousness would deliver their soul,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. Lit., “the men.” Heb., ha·ʼana·shimʹ, pl. of ʼish.
====

[[v26-14-15]]

^<<v26-14-15,15>>^ “‘Or if I should make injurious wild beasts pass through the land and they actually bereaved it of children and it actually became a desolate waste without anybody passing through on account of the wild beasts,

[[v26-14-16]]

^<<v26-14-16,16>>^ were these three men in the midst of it, as I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘neither sons nor daughters would they deliver; they, only they themselves, would be delivered and the land itself would become a desolate waste.’”

[[v26-14-17]]

^<<v26-14-17,17>>^ “‘Or were it a sword that I should bring upon that land, and should I actually say: “Let a sword itself pass through the land,” and should I actually cut off from it earthling man^&#42;1^ and domestic animal,

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-14-18]]

^<<v26-14-18,18>>^ even were these three men in the midst of it, as I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘they would deliver neither sons nor daughters, but they, only they themselves, would be delivered.’”

[[v26-14-19]]

^<<v26-14-19,19>>^ “‘Or were it pestilence that I should send^&#42;1^ upon that land and should I actually pour out my rage upon it with blood, in order to cut off from it earthling man and domestic animal,

[NOTE]
====
. Or, “let go.”
====

[[v26-14-20]]

^<<v26-14-20,20>>^ even were Noah, Daniel and Job in the midst of it, as I am alive,’ is the utterance of the Sovereign Lord Jehovah, ‘neither son nor daughter would they deliver; they themselves because of their righteousness would deliver their soul.’”

[[v26-14-21]]

^<<v26-14-21,21>>^ “For this is what the Sovereign Lord Jehovah has said, ‘So, too, &#91;it will be&#93; when there will be my four injurious acts of judgment—sword and famine and injurious wild beast and pestilence—that I shall actually send upon Jerusalem in order to cut off from it earthling man and domestic animal.

[[v26-14-22]]

^<<v26-14-22,22>>^ But, look! there will certainly be left remaining in it an escaped company, those being brought forth. Sons and daughters, here they are! They are going forth to YOU people, and YOU will have to see their way and their dealings. And YOU will certainly be comforted over the calamity that I shall have brought upon Jerusalem, even all that I shall have brought upon her.’”

[[v26-14-23]]

^<<v26-14-23,23>>^ “‘And they will certainly comfort YOU people when YOU see their way and their dealings; and YOU will have to know that it was not without cause that I shall have done all that I must do against^&#42;1^ her,’ is the utterance of the Sovereign Lord Jehovah.”

[NOTE]
====
. Or, “in.”
====

'''

xref:026-ezekiel/026-ezekiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezekiel/026-ezekiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]