include::./index.adoc[]

[[v26-45-0]]
=== Ezekiel, 45
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-45-1]]

^<<v26-45-1,1>>^ “‘And when YOU people allot the land as an inheritance, YOU should offer a contribution to Jehovah, a holy portion out of the land; as to length, twenty-five thousand &#91;cubits&#93; in length, and as to width, ten^&#42;1^ thousand. It will be a holy portion in all its^&#42;2^ boundaries round about.

[NOTE]
====
. “Ten,” MTSyVg; LXX, “twenty.”
. “Its,” fem., referring to “contribution,” fem.
====

[[v26-45-2]]

^<<v26-45-2,2>>^ From this there will prove to be for the holy place^&#42;1^ five hundred by five hundred, it being made square round about; and fifty cubits it will have as pasture ground on each side.

[NOTE]
====
. “The holy place.” Heb., haq·qoʹdhesh; Gr., ha·gi·aʹsma.
====

[[v26-45-3]]

^<<v26-45-3,3>>^ And out of this measurement you should measure the length of twenty-five thousand and the width of ten^&#42;1^ thousand, and in it the sanctuary^&#42;2^ will come to be, something most holy.

[NOTE]
====
. “Ten,” MTSyVg; LXXA,B, “twenty.”
. “The sanctuary.” Heb., ham·miq·dashʹ.
====

[[v26-45-4]]

^<<v26-45-4,4>>^ As a holy portion out of the land it will come to be for the priests themselves, the ministers of the sanctuary, those approaching to minister to Jehovah. And for them it must prove to be a place for houses, and a sacred place^&#42;1^ for the sanctuary.

[NOTE]
====
. “And a sacred place.” Heb., u·miq·dashʹ; T, “a paved way.”
====

[[v26-45-5]]

^<<v26-45-5,5>>^ “‘There will be twenty-five thousand in length and ten thousand in width. It will become the Levites’, the ministers of the house. As a possession they will have twenty dining rooms.

[[v26-45-6]]

^<<v26-45-6,6>>^ “‘And as the possession of the city, YOU people will give five thousand in width and a length of twenty-five thousand, exactly as the holy contribution. To all the house of Israel it will come to belong.

[[v26-45-7]]

^<<v26-45-7,7>>^ “‘And for the chieftain there will be on this side and on that side of the holy contribution and of the possession of the city, beside the holy contribution and beside the possession of the city, something on the west side westward and something on the east side eastward. And the length will be exactly as one of the shares, from the western boundary to the eastern boundary.

[[v26-45-8]]

^<<v26-45-8,8>>^ As regards the land, it will become his as a possession in Israel. And no more will my chieftains maltreat my people, and the land they will give to the house of Israel with respect to their tribes.’

[[v26-45-9]]

^<<v26-45-9,9>>^ “This is what the Sovereign Lord Jehovah has said, ‘That is enough of YOU, O chieftains of Israel!’
“‘Remove the violence and the despoiling, and do justice and righteousness themselves. Lift YOUR expropriations^&#42;1^ off my people,’ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. Or, “your acts of expulsion.”
====

[[v26-45-10]]

^<<v26-45-10,10>>^ ‘Accurate scales and an accurate eʹphah and an accurate bath measure YOU men should come to have.

[[v26-45-11]]

^<<v26-45-11,11>>^ As regards the eʹphah and the bath measure, there should come to be but one fixed amount, for the bath^&#42;1^ to carry a tenth of a hoʹmer^&#42;2^ and the tenth of the hoʹmer an eʹphah;^&#42;3^ with reference to the hoʹmer, its required amount should prove to be.

[NOTE]
====
. A liquid measure that equaled 22 L (5.81 gal) and corresponded to the ephah, a dry measure.
. A homer equaled 220 L (200 dry qt).
. An ephah equaled 22 L (20 dry qt).
====

[[v26-45-12]]

^<<v26-45-12,12>>^ And the shekel^&#42;1^ is twenty geʹrahs.^&#42;2^ Twenty shekels, twenty-five shekels, fifteen shekels should prove to be the maʹneh for YOU.’

[NOTE]
====
. A shekel weighed 11.4 g (0.367 oz t).
. A gerah weighed 0.57 g (0.01835 oz t).
====

[[v26-45-13]]

^<<v26-45-13,13>>^ “‘This is the contribution that YOU should offer, the sixth part of the eʹphah from the hoʹmer of wheat, and the sixth part of the eʹphah from the hoʹmer of barley;

[[v26-45-14]]

^<<v26-45-14,14>>^ and as for the allowance of the oil, there is the bath measure of the oil. The bath is a tenth of the cor. Ten baths are a hoʹmer; because ten baths are a hoʹmer.

[[v26-45-15]]

^<<v26-45-15,15>>^ And one sheep out of the flock, out of two hundred from the livestock^&#42;1^ of Israel, for the grain offering and for the whole burnt offering and for the communion sacrifices, in order to make atonement for them,’ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. “Livestock,” by a correction of M; or possibly, to agree with LXX, “families”; M, “well irrigated [land].”
====

[[v26-45-16]]

^<<v26-45-16,16>>^ “‘As for all the people of the land,^&#42;1^ they will be responsible for this contribution to the chieftain in Israel.

[NOTE]
====
. See 7:27 ftn.
====

[[v26-45-17]]

^<<v26-45-17,17>>^ And upon the chieftain will devolve the whole burnt offerings and the grain offering and the drink offering during the festivals and during the new moons and during the sabbaths, during all the festal seasons of the house of Israel. He will be the one to provide the sin offering and the grain offering and the whole burnt offering and the communion sacrifices, in order to make atonement in behalf of the house of Israel.’

[[v26-45-18]]

^<<v26-45-18,18>>^ “This is what the Sovereign Lord Jehovah has said, ‘In the first &#91;month&#93;, on the first &#91;day&#93; of the month, you should take a young bull, a son of the herd, a sound one, and you must purify the sanctuary^&#42;1^ from sin.

[NOTE]
====
. “The sanctuary.” Heb., ham·miq·dashʹ; Gr., haʹgi·on; Lat., sanc·tu·aʹri·um.
====

[[v26-45-19]]

^<<v26-45-19,19>>^ And the priest must take some of the blood of the sin offering and put it upon the doorpost^&#42;1^ of the House and upon the four corners of the surrounding ledge belonging to the altar and upon the doorpost of the gate of the inner courtyard.

[NOTE]
====
. “The doorpost of.” Heb., mezu·zathʹ.
====

[[v26-45-20]]

^<<v26-45-20,20>>^ And that is how you will do on the seventh &#91;day&#93; in the month because of any man^&#42;1^ making a mistake and because of any inexperienced one; and YOU people must make atonement for the House.

[NOTE]
====
. Or, “because of the individual.” Heb., me·ʼishʹ.
====

[[v26-45-21]]

^<<v26-45-21,21>>^ “‘In the first &#91;month&#93;, on the fourteenth day of the month, there should occur for YOU the passover. As a festival for seven days unfermented cakes^&#42;1^ are what should be eaten.

[NOTE]
====
. Or, “unleavened (yeastless) bread.” Heb., mats·tsohthʹ.
====

[[v26-45-22]]

^<<v26-45-22,22>>^ And on that day, in his own behalf and in behalf of all the people of the land, the chieftain must provide a young bull as a sin offering.

[[v26-45-23]]

^<<v26-45-23,23>>^ And for the seven days of the festival he should provide as a whole burnt offering to Jehovah seven young bulls and seven rams, sound ones, daily for the seven days, and as a sin offering a buck of the goats daily.

[[v26-45-24]]

^<<v26-45-24,24>>^ And as a grain offering an eʹphah for the young bull and an eʹphah for the ram he should provide, and, as regards oil, a hin to the eʹphah.

[[v26-45-25]]

^<<v26-45-25,25>>^ “‘In the seventh &#91;month&#93;, on the fifteenth day of the month, during the festival, he should provide the same as these for the seven days, the same as the sin offering, as the whole burnt offering, and as the grain offering and as the oil.’”

'''

xref:026-ezekiel/026-ezekiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezekiel/026-ezekiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]