include::./index.adoc[]

[[v26-27-0]]
=== Ezekiel, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-27-1]]

^<<v26-27-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-27-2]]

^<<v26-27-2,2>>^ “And as for you, O son of man, raise up concerning Tyre a dirge,

[[v26-27-3]]

^<<v26-27-3,3>>^ and you must say to Tyre,
“‘O you who are dwelling at the entrances of &#91;the&#93; sea, the tradeswoman of the peoples for many islands, this is what the Sovereign Lord Jehovah has said: “O Tyre, you yourself have said, ‘I am perfect in prettiness.’^&#42;1^

[NOTE]
====
. Or, “fairness.”
====

[[v26-27-4]]

^<<v26-27-4,4>>^ In the heart of &#91;the&#93; seas are your territories. Your own builders have perfected your prettiness.

[[v26-27-5]]

^<<v26-27-5,5>>^ Out of juniper timbers from Seʹnir^&#42;1^ they built for you all the planks. A cedar from Lebʹa·non they took to make a mast upon you.

[NOTE]
====
. “Mount Hermon” in De 3:8, 9.
====

[[v26-27-6]]

^<<v26-27-6,6>>^ Out of massive trees from Baʹshan they made your oars. Your prow^&#42;1^ they made with ivory in cypress wood,^&#42;2^ from the islands of Kitʹtim.

[NOTE]
====
. Or, “boards,” collectively.
. “In cypress wood,” in agreement with T; M, “the daughter of the Ashurites.”
====

[[v26-27-7]]

^<<v26-27-7,7>>^ Linen in various colors from Egypt your cloth expanse happened to be, in order for &#91;it&#93; to serve as your sail. Blue thread and wool dyed reddish purple from the islands of E·liʹshah are what your deck covering proved to be.

[[v26-27-8]]

^<<v26-27-8,8>>^ “‘“The inhabitants of Siʹdon and of Arʹvad themselves became rowers for you. Your skilled^&#42;1^ ones, O Tyre, happened to be in you; they were your sailors.

[NOTE]
====
. Lit., “wise.”
====

[[v26-27-9]]

^<<v26-27-9,9>>^ Even old men of Geʹbal and her skilled ones happened to be in you as caulkers for your seams.^&#42;1^ All the ships of the sea and their mariners themselves proved to be in you, in order to exchange articles of merchandise.

[NOTE]
====
. Or, “leaks.”
====

[[v26-27-10]]

^<<v26-27-10,10>>^ Persians and Luʹdim and men of Put—they happened to be in your military force, your men of war. Shield and helmet they hung up in you. They were the ones that caused your splendor.

[[v26-27-11]]

^<<v26-27-11,11>>^ The sons of Arʹvad, even your military force, were upon your walls all around, and valorous men^&#42;1^ were the ones that happened to be in your own towers. Their circular shields they hung up on your walls all around. They themselves perfected your prettiness.

[NOTE]
====
. “And valorous men.” Heb., wegham·ma·dhimʹ; Lat., Pig·meʹi, “pygmies.”
====

[[v26-27-12]]

^<<v26-27-12,12>>^ “‘“Tarʹshish was your merchant because of the abundance of all sorts of valuable things. For &#91;its&#93; silver, iron, tin and lead, your stores were given.^&#42;1^

[NOTE]
====
. Lit., “they (people) gave your stores.”
====

[[v26-27-13]]

^<<v26-27-13,13>>^ Jaʹvan, Tuʹbal and Meʹshech themselves were your traders. For the souls of mankind^&#42;1^ and articles of copper your articles of exchange were given.^&#42;2^

[NOTE]
====
. Or, “of earthling men.” Heb., ʼa·dhamʹ.
. Lit., “they (people) gave your articles of exchange.”
====

[[v26-27-14]]

^<<v26-27-14,14>>^ From the house of To·garʹmah there were horses and steeds and mules, &#91;for which&#93; your stores were given.

[[v26-27-15]]

^<<v26-27-15,15>>^ The sons of Deʹdan^&#42;1^ were your traders; many islands were merchants in your employ;^&#42;2^ horns of ivory and ebony they have paid back as gift^&#42;3^ to you.

[NOTE]
====
. “Dedan,” MTVg; LXX, “the Rhodians.”
. Lit., “hand.”
. Or, “tribute.”
====

[[v26-27-16]]

^<<v26-27-16,16>>^ Eʹdom^&#42;1^ was your merchant because of the abundance of your works. For turquoise, wool dyed reddish purple and material of various colors and fine fabric and corals and rubies, your stores were given in exchange.

[NOTE]
====
. “Edom,” Sy and about 25 Heb. mss; M, “Aram”; Vg, “The Syrian.”
====

[[v26-27-17]]

^<<v26-27-17,17>>^ “‘“Judah and the land of Israel themselves were your traders. For the wheat of Minʹnith and special foodstuff^&#42;1^ and honey and oil and balsam, your articles of exchange were given.

[NOTE]
====
. “And special foodstuff.” Heb., u·phan·naghʹ. The meaning is uncertain, but it is thought to be a kind of food.
====

[[v26-27-18]]

^<<v26-27-18,18>>^ “‘“Damascus was your merchant in the abundance of your works, because of the abundance of all your valuable things, with the wine of Helʹbon and the wool of reddish gray.

[[v26-27-19]]

^<<v26-27-19,19>>^ Veʹdan and Jaʹvan from Uʹzal—for your stores they gave. Iron in wrought works, cassia and cane—for your articles of exchange they proved to be.

[[v26-27-20]]

^<<v26-27-20,20>>^ Deʹdan was your trader in garments of woven material for riding.

[[v26-27-21]]

^<<v26-27-21,21>>^ The Arabs and all the chieftains of Keʹdar themselves were merchants in your employ.^&#42;1^ In male lambs and rams and he-goats—in them they were your merchants.

[NOTE]
====
. Lit., “hand.”
====

[[v26-27-22]]

^<<v26-27-22,22>>^ The traders of Sheʹba and Raʹa·mah themselves were your traders; for the finest of all sorts of perfumes and for all sorts of precious stones and gold, your stores were given.

[[v26-27-23]]

^<<v26-27-23,23>>^ Haʹran and Canʹneh and Eʹden, the traders of Sheʹba, Asʹshur &#91;and&#93; Chilʹmad were your traders.

[[v26-27-24]]

^<<v26-27-24,24>>^ They were your traders in gorgeous garments, in wraps of blue material and material of various colors and in carpets of two-colored stuff, in ropes twined and solidly made, in your trading center.

[[v26-27-25]]

^<<v26-27-25,25>>^ “‘“The ships of Tarʹshish were your caravans for your articles of exchange, so that you get filled and become very glorious in the heart of the open sea.

[[v26-27-26]]

^<<v26-27-26,26>>^ “‘“Into vast waters those rowing you have brought you. The east wind itself has broken you in the heart of the open sea.

[[v26-27-27]]

^<<v26-27-27,27>>^ Your valuable things and your stores, your articles of exchange, your mariners and your sailors, the caulkers of your seams^&#42;1^ and those exchanging your articles of merchandise and all your men of war, who are in you and in all your congregation, who are in the midst of you,—they will fall in the heart of the open sea in the day of your downfall.

[NOTE]
====
. Or, “leaks.”
====

[[v26-27-28]]

^<<v26-27-28,28>>^ “‘“At the sound of the outcry of your sailors the open country will rock.

[[v26-27-29]]

^<<v26-27-29,29>>^ And all those handling an oar, mariners, all the sailors of the sea, will certainly go down from their ships; upon the land they will stand.

[[v26-27-30]]

^<<v26-27-30,30>>^ And over you they will certainly let themselves be heard with their voice and will cry out bitterly. And they will bring up dust upon their heads. In the ashes they will wallow.

[[v26-27-31]]

^<<v26-27-31,31>>^ And they will have to make &#91;themselves&#93; bald with a baldness for you, and gird on sackcloth and weep over you in bitterness of soul, with bitter wailing.

[[v26-27-32]]

^<<v26-27-32,32>>^ And for you in their lamentation they will certainly lift up a dirge and chant over you,
“‘“‘Who is like Tyre, like her that has been brought to silence in the midst of the sea?

[[v26-27-33]]

^<<v26-27-33,33>>^ When your stores went forth from the open sea, you satisfied many peoples. With the abundance of your valuable things and your articles of exchange you made earth’s kings rich.

[[v26-27-34]]

^<<v26-27-34,34>>^ Now you have been broken^&#42;1^ by the open sea, in the depths of the waters. As for your articles of exchange and all your congregation, in the midst of you they have fallen.

[NOTE]
====
. “You have been broken,” LXXSyVg and three Heb. mss, the verb having the fem. gender termination.
====

[[v26-27-35]]

^<<v26-27-35,35>>^ All the inhabitants of the islands—in amazement they will certainly stare at you, and their kings themselves will have to shudder in horror. Faces must become perturbed.

[[v26-27-36]]

^<<v26-27-36,36>>^ As for merchants among the peoples, they will certainly whistle over you. Sudden terrors are what you must become, and you will be no more to time indefinite.’”’”

'''

xref:026-ezekiel/026-ezekiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezekiel/026-ezekiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]