include::./index.adoc[]

[[v26-23-0]]
=== Ezekiel, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-23-1]]

^<<v26-23-1,1>>^ And the word of Jehovah proceeded to come to me, saying:

[[v26-23-2]]

^<<v26-23-2,2>>^ “Son of man, two women, the daughters of one mother, there happened to be.

[[v26-23-3]]

^<<v26-23-3,3>>^ And they began to prostitute themselves in Egypt. In their youth they committed prostitution. There their breasts were squeezed, and there they pressed the bosoms of their virginity.

[[v26-23-4]]

^<<v26-23-4,4>>^ And their names were O·hoʹlah^&#42;1^ the older one^&#42;2^ and O·holʹi·bah^&#42;3^ her sister, and they came to be mine and began to give birth to sons and daughters. And as for their names, O·hoʹlah is Sa·marʹi·a, and O·holʹi·bah is Jerusalem.

[NOTE]
====
. Meaning “Her Tent.”
. Lit., “the great one,” fem.
. Meaning “My Tent Is in Her.”
====

[[v26-23-5]]

^<<v26-23-5,5>>^ “And O·hoʹlah began to prostitute herself, while subject to me, and kept lusting after those passionately loving her, after the As·syrʹi·ans, who were near,

[[v26-23-6]]

^<<v26-23-6,6>>^ governors clothed with blue material, and deputy rulers—desirable young men all of them, cavalrymen riding horses.

[[v26-23-7]]

^<<v26-23-7,7>>^ And she continued giving forth her prostitutions upon them, the choicest sons of As·syrʹi·a all of them; and with all those after whom she lusted—with their dungy idols—she defiled herself.

[[v26-23-8]]

^<<v26-23-8,8>>^ And her prostitutions &#91;carried&#93; from Egypt she did not leave, for with her they had lain down in her youth, and they were the ones that pressed the bosoms of her virginity and they kept pouring out their immoral intercourse upon her.

[[v26-23-9]]

^<<v26-23-9,9>>^ Therefore I gave her into the hand of those passionately loving her, into the hand of the sons of As·syrʹi·a, toward whom she had lusted.

[[v26-23-10]]

^<<v26-23-10,10>>^ They were the ones that uncovered her nakedness. Her sons and her daughters they took, and her they killed even with sword. And she came to be infamy^&#42;1^ to women, and acts of judgment were what they executed upon her.

[NOTE]
====
. Or, “a reputation.” Lit., “a name,” in a bad, infamous sense.
====

[[v26-23-11]]

^<<v26-23-11,11>>^ “When her sister O·holʹi·bah got to see &#91;it&#93;, then she exercised her sensual desire more ruinously than she, and her prostitution more than the fornication^&#42;1^ of her sister.

[NOTE]
====
. Lit., “more than the fornications.” Heb., miz·zenu·nehʹ; Gr., hy·perʹ ten por·neiʹan; Lat., suʹper for·ni·ca·ti·oʹnem. See App 5A.
====

[[v26-23-12]]

^<<v26-23-12,12>>^ For the sons of As·syrʹi·a she lusted, governors and deputy rulers who were near, clothed with perfect taste, cavalrymen riding horses—desirable young men all of them.

[[v26-23-13]]

^<<v26-23-13,13>>^ And I got to see that, because she had defiled herself, both of them had one way.

[[v26-23-14]]

^<<v26-23-14,14>>^ And she kept adding to her acts of prostitution when she got to see the men in carvings upon the wall, images of Chal·deʹans carved in vermilion,

[[v26-23-15]]

^<<v26-23-15,15>>^ girded with belts on their hips, with pendant turbans on their heads, having the appearance of warriors,^&#42;1^ all of them, the likeness of the sons of Babylon,^&#42;2^ Chal·deʹans as respects the land of their birth.

[NOTE]
====
. Or, “shield-bearers.” Lit., “third men.” Heb., sha·li·shimʹ; Gr., tris·seʹ, “threefold”; Lat., duʹcum, “leaders.” Assyrian bas-reliefs show one of the three chariot occupants to be an armor-bearer or umbrella-bearer, a third man.
. “Babylon,” Vg; MTSy, “Babel.”
====

[[v26-23-16]]

^<<v26-23-16,16>>^ And she began to lust after them at the sight of her eyes and proceeded to send messengers to them in Chal·deʹa.

[[v26-23-17]]

^<<v26-23-17,17>>^ And the sons of Babylon kept coming in to her, to the bed of expressions of love, and defiling her with their immoral intercourse; and she continued getting defiled by them, and her soul began to turn away disgusted from them.

[[v26-23-18]]

^<<v26-23-18,18>>^ “And she went on uncovering her acts of prostitution and uncovering her nakedness, so that my soul turned away disgusted from company with her, just as my soul had turned away disgusted from company with her sister.

[[v26-23-19]]

^<<v26-23-19,19>>^ And she kept multiplying her acts of prostitution to the point of calling to mind the days of her youth, when she prostituted herself in the land of Egypt.

[[v26-23-20]]

^<<v26-23-20,20>>^ And she kept lusting in the style of concubines belonging to those whose fleshly member^&#42;1^ is as the fleshly member of male asses and whose genital organ is as the genital organ of male horses.

[NOTE]
====
. “Fleshly member.” Lit., “flesh.”
====

[[v26-23-21]]

^<<v26-23-21,21>>^ And you continued calling attention to the loose conduct of your youth by the pressing of your bosoms from Egypt onward, for the sake^&#42;1^ of the breasts of your youth.

[NOTE]
====
. “Through the squeezing,” by a slight correction.
====

[[v26-23-22]]

^<<v26-23-22,22>>^ “Therefore, O O·holʹi·bah, this is what the Sovereign Lord Jehovah has said, ‘Here I am rousing up your passionate lovers against you, those from whom your soul has turned away in disgust, and I will bring them in against you on all sides,

[[v26-23-23]]

^<<v26-23-23,23>>^ the sons of Babylon and all the Chal·deʹans, Peʹkod and Shoʹa and Koʹa, all the sons of As·syrʹi·a with them, desirable young men, governors and deputy rulers all of them, warriors^&#42;1^ and summoned ones, riding on horses, all of them.

[NOTE]
====
. Or, “shield-bearers.” See vs 15 ftn, “Warriors.”
====

[[v26-23-24]]

^<<v26-23-24,24>>^ And they must come in against you with rattling^&#42;1^ of war chariots and wheels, and with a congregation of peoples, with large shield and buckler and helmet. They will set themselves against you all around, and I will give judgment over to them, and they must judge you with their judgments.

[NOTE]
====
. Possibly, “a multitude.” The meaning is uncertain.
====

[[v26-23-25]]

^<<v26-23-25,25>>^ And I will express my ardor against you, and they must take action against you in rage. Your nose and your ears they will remove, and the remainder of you will fall even by the sword. Your sons and your daughters they themselves will take, and the remainder of you will be devoured by the fire.

[[v26-23-26]]

^<<v26-23-26,26>>^ And they will certainly strip off you your garments and take away your beautiful articles.

[[v26-23-27]]

^<<v26-23-27,27>>^ And I shall actually cause your loose conduct to cease from you, and your prostitution &#91;carried&#93; from the land of Egypt; and you will not raise your eyes to them, and Egypt you will remember no more.’

[[v26-23-28]]

^<<v26-23-28,28>>^ “For this is what the Sovereign Lord Jehovah has said, ‘Here I am giving you into the hand of those whom you have hated, into the hand of those from whom your soul has turned away disgusted.

[[v26-23-29]]

^<<v26-23-29,29>>^ And they must take action against you in hatred and take away all your product of toil and leave you naked and nude;^&#42;1^ and the nudeness of your acts of fornication and your loose conduct and your acts of prostitution must be uncovered.

[NOTE]
====
. Lit., “nakedness and nudity.”
====

[[v26-23-30]]

^<<v26-23-30,30>>^ There will be a doing^&#42;1^ of these things to you because of your going like a prostitute after &#91;the&#93; nations, on account of the fact that you defiled yourself with their dungy idols.

[NOTE]
====
. “There will be a doing.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v26-23-31]]

^<<v26-23-31,31>>^ In the way of your sister you have walked; and I shall have to give her cup into your hand.’

[[v26-23-32]]

^<<v26-23-32,32>>^ “This is what the Sovereign Lord Jehovah has said, ‘The cup of your sister you will drink, the deep and wide one. You will become an object of laughter and derision, &#91;the cup&#93; containing much.

[[v26-23-33]]

^<<v26-23-33,33>>^ With drunkenness and grief you will be filled, with the cup of astonishment and of desolation, the cup of your sister Sa·marʹi·a.

[[v26-23-34]]

^<<v26-23-34,34>>^ And you will have to drink it and drain &#91;it&#93; out, and its earthenware fragments you will gnaw, and your breasts you will tear out. “For I myself have spoken,” is the utterance of the Sovereign Lord Jehovah.’

[[v26-23-35]]

^<<v26-23-35,35>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘For the reason that you have forgotten me and you proceeded to cast me behind your back, then you yourself also bear your loose conduct and your acts of prostitution.’”

[[v26-23-36]]

^<<v26-23-36,36>>^ And Jehovah went on to say to me: “Son of man, will you judge O·hoʹlah and O·holʹi·bah and tell them their detestable things?

[[v26-23-37]]

^<<v26-23-37,37>>^ For they have committed adultery and there is blood on their hands, and with their dungy idols they have committed adultery. And, besides that, their sons whom they had borne to me they made pass through &#91;the fire&#93; to them^&#42;1^ as food.

[NOTE]
====
. “Them,” masc., referring to the “dungy idols.”
====

[[v26-23-38]]

^<<v26-23-38,38>>^ What is more, this is what they have done to me: They have defiled my sanctuary in that day, and my sabbaths they have profaned.

[[v26-23-39]]

^<<v26-23-39,39>>^ And when they had slaughtered their sons to their dungy idols they even proceeded to come into my sanctuary on that day to profane it, and, look! that is what they have done in the midst of my house.

[[v26-23-40]]

^<<v26-23-40,40>>^ And in addition to that, when they began to send to the men^&#42;1^ coming from far away, to whom there was sent a messenger, then, look! they came, for whom you had washed yourself, painted your eyes and decked yourself with ornaments.

[NOTE]
====
. “To the men.” Heb., la·ʼana·shimʹ, pl. of ʼish.
====

[[v26-23-41]]

^<<v26-23-41,41>>^ And you sat down upon a glorious couch, with a table set in order before it, and my incense and my oil you put upon it.

[[v26-23-42]]

^<<v26-23-42,42>>^ And the sound of a crowd at ease was in her, and to the men out of the mass of mankind^&#42;1^ there were drunkards being brought in from the wilderness, and they proceeded to put bracelets on the hands of the women^&#42;2^ and beautiful crowns upon their heads.

[NOTE]
====
. Lit., “earthling man.” Heb., ʼa·dhamʹ.
. Lit., “on their hands”; “their” is fem.
====

[[v26-23-43]]

^<<v26-23-43,43>>^ “Then I said respecting her who was worn out with adultery, ‘Now she will keep on committing her prostitution, even she herself.’

[[v26-23-44]]

^<<v26-23-44,44>>^ And they kept on coming in to her, just as one comes in to a woman that is a prostitute; in that manner they came in to O·hoʹlah and to O·holʹi·bah as women of loose conduct.

[[v26-23-45]]

^<<v26-23-45,45>>^ But as regards righteous men, they are the ones that will judge her^&#42;1^ with the judgment for adulteresses and with the judgment for female shedders of blood; for adulteresses are what they are, and there is blood on their hands.

[NOTE]
====
. Lit., “them,” masc., M; LXXSyVg, “them,” fem.
====

[[v26-23-46]]

^<<v26-23-46,46>>^ “For this is what the Sovereign Lord Jehovah has said, ‘There will be the bringing up of a congregation against them and a making^&#42;1^ of them a frightful object and something to plunder.

[NOTE]
====
. “There will be the bringing up . . . a making.” In Heb. these are verbs in the infinitive absolute, indefinite as to time and impersonal.
====

[[v26-23-47]]

^<<v26-23-47,47>>^ And the congregation must pelt them with stones, and there will be a cutting of them down with their swords. Their sons and their daughters they will kill, and with fire their houses they will burn.

[[v26-23-48]]

^<<v26-23-48,48>>^ And I shall certainly cause loose conduct to cease out of the land, and all the women will have to let themselves be corrected, so that they will not do according to YOUR^&#42;1^ loose conduct.

[NOTE]
====
. “Your,” fem. pl.
====

[[v26-23-49]]

^<<v26-23-49,49>>^ And they must bring YOUR loose conduct upon YOU, and the sins of YOUR dungy idols YOU will bear; and YOU people will have to know that I am the Sovereign Lord Jehovah.’”

'''

xref:026-ezekiel/026-ezekiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezekiel/026-ezekiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]