include::./index.adoc[]

[[v26-43-0]]
=== Ezekiel, 43
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-43-1]]

^<<v26-43-1,1>>^ Then he made me go to the gate, the gate that is facing toward the east.

[[v26-43-2]]

^<<v26-43-2,2>>^ And, look! the glory of the God of Israel^&#42;1^ was coming from the direction of the east, and his voice was like the voice of vast waters; and the earth itself shone because of his glory.

[NOTE]
====
. “The glory of the God of Israel.” Heb., kevohdhʹ ʼElo·hehʹ Yis·ra·ʼelʹ.
====

[[v26-43-3]]

^<<v26-43-3,3>>^ And it was like the appearance of the vision that I had seen, like the vision that I saw when I came^&#42;1^ to bring the city to ruin; and there were appearances^&#42;2^ like the appearance^&#42;3^ that I saw by the river Cheʹbar, and I went falling upon my face.

[NOTE]
====
. “When I came,” M; ThVg and six Heb. mss, “when he came”; T, “when I prophesied for making [the city] waste away.”
. “There were appearances,” M; LXX, “the vision of the chariot, that I saw (was).”
. Or, “vision.”
====

[[v26-43-4]]

^<<v26-43-4,4>>^ And the glory of Jehovah itself came into the House by way of the gate the front of which was toward the east.

[[v26-43-5]]

^<<v26-43-5,5>>^ And a spirit^&#42;1^ proceeded to raise me up and bring me into the inner courtyard, and, look! the House had become full of the glory of Jehovah.^&#42;2^

[NOTE]
====
. “A spirit.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus.
. Or, “the glory of Jehovah filled the House.”
====

[[v26-43-6]]

^<<v26-43-6,6>>^ And I began to hear someone speaking to me out of the House, and &#91;the&#93; man^&#42;1^ himself had come to be standing beside me.

[NOTE]
====
. “And [the] man.” Heb., weʼishʹ.
====

[[v26-43-7]]

^<<v26-43-7,7>>^ And He went on to say to me:
“Son of man,^&#42;1^ &#91;this is&#93;^&#42;2^ the place of my throne and the place of the soles of my feet, where I shall reside in the midst of the sons of Israel to time indefinite; and no more will they, the house of Israel, defile my holy name, they and their kings, by their fornication and by the carcasses of their kings at their death,^&#42;3^

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
. “This is,” T; LXX, “you have seen”; but M has only the particle that is the sign of the accusative case for the next word.
. “At their death,” TTh and about 20 Heb. mss and ed.; M, “their high places”; LXX, “in the midst of them.”
====

[[v26-43-8]]

^<<v26-43-8,8>>^ by their putting their threshold with my threshold and their doorpost beside my doorpost, with the wall between me and them. And they defiled my holy name by their detestable things that they did, so that I went exterminating them in my anger.

[[v26-43-9]]

^<<v26-43-9,9>>^ Now let them remove their fornication and the carcasses of their kings far from me, and I shall certainly reside in the midst of them to time indefinite.

[[v26-43-10]]

^<<v26-43-10,10>>^ “As for you, O son of man, inform the house of Israel about the House, that they may feel humiliated because of their errors, and they must measure the pattern.

[[v26-43-11]]

^<<v26-43-11,11>>^ And if they actually feel humiliated because of all that they have done, the ground plan of the House, and its arrangement and its exits and its entryways, and all its ground plans and all its specifications, and all its ground plans and all its laws do you make known to them and write before their eyes, in order that they may observe all its ground plan and all its specifications and may actually carry them out.

[[v26-43-12]]

^<<v26-43-12,12>>^ This is the law of the House. On the top of the mountain its entire territory all around is something most holy. Look! This is the law of the House.

[[v26-43-13]]

^<<v26-43-13,13>>^ “And these are the measurements of the altar in cubits, a cubit being a cubit and a handbreadth.^&#42;1^ And &#91;its&#93; bottom^&#42;2^ is a cubit. And a cubit is the width. And its border is upon its lip round about, one span. And this is the base of the altar.

[NOTE]
====
. See 40:5 ftn, “Handbreadth.”
. Or, “blood channel”; or, “molding.”
====

[[v26-43-14]]

^<<v26-43-14,14>>^ And from the bottom on the floor to the lower surrounding ledge there are two cubits, and the width is one cubit. And from the small surrounding ledge to the big surrounding ledge there are four cubits, and &#91;its&#93; width is a cubit.

[[v26-43-15]]

^<<v26-43-15,15>>^ And the altar hearth is four cubits, and out from the altar hearth and upward there are the four horns.

[[v26-43-16]]

^<<v26-43-16,16>>^ And the altar hearth is twelve &#91;cubits&#93; in length, with twelve &#91;cubits&#93; of width, squared on its four sides.

[[v26-43-17]]

^<<v26-43-17,17>>^ And the surrounding ledge is fourteen &#91;cubits&#93; in length, with fourteen &#91;cubits&#93; of width, on its four sides; and the border surrounding it is half a cubit, and its bottom is a cubit round about.
“And its^&#42;1^ steps are facing east.”

[NOTE]
====
. “Its,” masc., referring to the altar.
====

[[v26-43-18]]

^<<v26-43-18,18>>^ And he proceeded to say to me: “Son of man, this is what the Sovereign Lord Jehovah has said, ‘These are the statutes of the altar on the day of its being made, in order to offer upon it whole burnt offerings and to sprinkle upon it blood.’

[[v26-43-19]]

^<<v26-43-19,19>>^ “‘And you must give to the Levitical priests, who are of the offspring^&#42;1^ of Zaʹdok, the ones approaching me,’ is the utterance of the Sovereign Lord Jehovah, ‘to minister to me, a young bull, the son of &#91;the&#93; herd, as a sin offering.

[NOTE]
====
. Lit., “seed.”
====

[[v26-43-20]]

^<<v26-43-20,20>>^ And you must take some of its blood and put &#91;it&#93; upon its four horns and upon the four corners of the surrounding ledge and upon the border round about and purify it from sin and make atonement for it.

[[v26-43-21]]

^<<v26-43-21,21>>^ And you must take the young bull, the sin offering, and one must burn it in the appointed place of the House, outside the sanctuary.

[[v26-43-22]]

^<<v26-43-22,22>>^ And on the second day you will bring near a buck of the goats, a sound one, as a sin offering; and they must purify the altar from sin the same as they purified &#91;it&#93; from sin with the young bull.’

[[v26-43-23]]

^<<v26-43-23,23>>^ “‘On your making an end of the purifying from sin you will bring near a young bull, the son of &#91;the&#93; herd, a sound one, and a ram from the flock, a sound one.

[[v26-43-24]]

^<<v26-43-24,24>>^ And you must bring them near before Jehovah, and the priests must throw salt upon them and offer them up as a whole burnt offering to Jehovah.

[[v26-43-25]]

^<<v26-43-25,25>>^ For seven days you will render up a he-goat as a sin offering for the day; and a young bull, the son of &#91;the&#93; herd, and a ram out of the flock, perfect ones, they will render up.

[[v26-43-26]]

^<<v26-43-26,26>>^ For seven days they will make atonement for the altar, and they must cleanse it and install it.^&#42;1^

[NOTE]
====
. Lit., “fill its hand.” Compare 2Ch 13:9 ftn, “Power.”
====

[[v26-43-27]]

^<<v26-43-27,27>>^ And they will complete the days. And it must occur on the eighth day and from then on that the priests will render upon the altar the whole burnt offerings of YOU people and YOUR communion sacrifices; and I shall certainly find pleasure in YOU,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezekiel/026-ezekiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]