include::./index.adoc[]

[[v26-15-0]]
=== Ezekiel, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-15-1]]

^<<v26-15-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-15-2]]

^<<v26-15-2,2>>^ “Son of man, in what way does the vine tree happen to be different from every other tree, the shoot, that has come to be among the trees of the forest?

[[v26-15-3]]

^<<v26-15-3,3>>^ Is there taken from it a pole with which to do some work? Or do people take from it a peg on which to hang any kind of utensil?

[[v26-15-4]]

^<<v26-15-4,4>>^ Look! Into the fire is where it must be put for fuel. Both ends of it the fire certainly devours, and the very middle of it does get scorched. Is it fit for any work?

[[v26-15-5]]

^<<v26-15-5,5>>^ Look! When it happens to be intact, it is not used for any work. How much less so, when fire itself has devoured it and it gets scorched, can it actually be used for any further work!”

[[v26-15-6]]

^<<v26-15-6,6>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘Just like the vine tree among the trees of the forest, that I have given to the fire as fuel, so I have given the inhabitants of Jerusalem.

[[v26-15-7]]

^<<v26-15-7,7>>^ And I have set^&#42;1^ my face against them. Out of the fire they have gone forth, but the fire itself will devour them. And YOU people will have to know that I am Jehovah, when I direct my face against them.’”

[NOTE]
====
. Lit., “given.”
====

[[v26-15-8]]

^<<v26-15-8,8>>^ “‘And I will make the land a desolate waste, for the reason that they have acted unfaithfully,’ is the utterance of the Sovereign Lord Jehovah.”

'''

xref:026-ezekiel/026-ezekiel-014.adoc#v26-14-0[&#60; Capítulo Anterior] | <<v26-15-0,Topo>> | xref:026-ezekiel/026-ezekiel-016.adoc#v26-16-0[Próximo Capítulo &#62;]