include::./index.adoc[]

[[v26-44-0]]
=== Ezekiel, 44
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-44-1]]

^<<v26-44-1,1>>^ And he proceeded to bring me back by way of the gate of the sanctuary,^&#42;1^ the outer one facing east, and it was shut.

[NOTE]
====
. “The sanctuary.” Heb., ham·miq·dashʹ; Gr., ha·giʹon; Lat., sanc·tu·aʹri·i.
====

[[v26-44-2]]

^<<v26-44-2,2>>^ Then Jehovah said to me: “As regards this gate, shut is how it will continue. It will not be opened, and no mere man^&#42;1^ will come in by it; for Jehovah himself, the God^&#42;2^ of Israel, has come in by it, and it must continue shut.

[NOTE]
====
. “And . . . man.” Heb., weʼishʹ.
. “The God of.” Heb., ʼElo·hehʹ.
====

[[v26-44-3]]

^<<v26-44-3,3>>^ However, the chieftain—as chieftain he himself will sit in it, in order to eat bread before Jehovah. By way of the porch of the gate he will come in, and by way of it he will go out.”

[[v26-44-4]]

^<<v26-44-4,4>>^ And he now brought me by way of the north gate to before the House, that I might see, and, look! the glory of Jehovah had filled the house of Jehovah. And I went falling on my face.

[[v26-44-5]]

^<<v26-44-5,5>>^ Then Jehovah said to me: “Son of man, set your heart and see with your eyes, and with your ears hear all that I am speaking with you regarding all the statutes of the house of Jehovah and regarding all its laws, and you must set your heart upon the entryway of the House with all the exits of the sanctuary.

[[v26-44-6]]

^<<v26-44-6,6>>^ And you must say to Rebelliousness,^&#42;1^ to the house of Israel, ‘This is what the Sovereign Lord Jehovah has said: “That is enough of YOU because of all YOUR detestable things, O house of Israel,

[NOTE]
====
. “Rebelliousness,” M; T, “the rebellious people”; LXX, “the rebellious house.”
====

[[v26-44-7]]

^<<v26-44-7,7>>^ when YOU bring in the foreigners^&#42;1^ uncircumcised in heart and uncircumcised in flesh, in order to come to be in my sanctuary so as to profane it, even my house; when YOU present my bread, fat and blood, while they keep breaking my covenant on account of all YOUR detestable things.

[NOTE]
====
. Lit., “sons of a foreign (country).”
====

[[v26-44-8]]

^<<v26-44-8,8>>^ Neither have YOU taken care of the obligation of my holy things, nor would YOU post &#91;others&#93; as caretakers of my obligation in my sanctuary for yourselves.”’

[[v26-44-9]]

^<<v26-44-9,9>>^ “‘This is what the Sovereign Lord Jehovah has said: “No foreigner,^&#42;1^ uncircumcised in heart and uncircumcised in flesh, may come into my sanctuary, that is, any foreigner who is in the midst of the sons of Israel.”’

[NOTE]
====
. Compare vs 7 ftn.
====

[[v26-44-10]]

^<<v26-44-10,10>>^ “‘But as for the Levites who got far away from me when Israel, who wandered away from me, wandered after their dungy idols, they must also bear their error.

[[v26-44-11]]

^<<v26-44-11,11>>^ And in my sanctuary they must become ministers^&#42;1^ at posts of oversight over the gates of the House and ministers at the House. They themselves will slaughter the whole burnt offering and the sacrifice for the people, and they themselves will stand before them to minister to them.

[NOTE]
====
. Or, “attendants.” Heb., mesha·rethimʹ; Lat., mi·niʹstri.
====

[[v26-44-12]]

^<<v26-44-12,12>>^ For the reason that they kept ministering to them before their dungy idols and became to the house of Israel a stumbling block into error, that is why I have raised my hand against them,’ is the utterance of the Sovereign Lord Jehovah, ‘and they must bear their error.

[[v26-44-13]]

^<<v26-44-13,13>>^ And they will not approach to me to act as priest to me or to approach to any holy things of mine, to the most holy things, and they must bear their humiliation and their detestable things that they did.

[[v26-44-14]]

^<<v26-44-14,14>>^ And I shall certainly make them caretakers of the obligation of the House, as regards all its service and as regards all that should be done in it.’

[[v26-44-15]]

^<<v26-44-15,15>>^ “‘And as for the Levitical priests, the sons of Zaʹdok, who took care of the obligation of my sanctuary when the sons of Israel wandered away from me, they themselves will come near to me to minister to me, and they must stand before me to present to me fat and the blood,’ is the utterance of the Sovereign Lord Jehovah.

[[v26-44-16]]

^<<v26-44-16,16>>^ ‘They are the ones that will come into my sanctuary, and they themselves will come near to my table to minister to me, and they must take care of the obligation to me.

[[v26-44-17]]

^<<v26-44-17,17>>^ “‘And it must occur that when they come into the gates of the inner courtyard, linen garments they should wear, and no wool should come up on them when they minister in the gates of the inner courtyard and inside.

[[v26-44-18]]

^<<v26-44-18,18>>^ Linen headdresses are what should prove to be on their head, and linen drawers are what should prove to be upon their hips. They should not gird themselves with &#91;what causes&#93; sweat.

[[v26-44-19]]

^<<v26-44-19,19>>^ And when they go forth to the outer courtyard, &#91;even&#93; to the outer courtyard to the people, they should strip off their garments in which they were ministering, and they must deposit them in the holy dining rooms and put on other garments, that they may not sanctify the people with their garments.

[[v26-44-20]]

^<<v26-44-20,20>>^ And their head they should not shave, and the hair of the head they should not wear loose. They should by all means clip &#91;the hair of&#93; their heads.

[[v26-44-21]]

^<<v26-44-21,21>>^ And no wine should any priests drink when they come into the inner courtyard.

[[v26-44-22]]

^<<v26-44-22,22>>^ And no widow or divorced woman should they take for themselves as wives, but virgins of the offspring of the house of Israel or the widow who happens to be the widow of a priest they may take.’

[[v26-44-23]]

^<<v26-44-23,23>>^ “‘And my people they should instruct in the difference between a holy thing and a profane thing; and the difference between what is unclean and what is clean they should cause them to know.

[[v26-44-24]]

^<<v26-44-24,24>>^ And in a legal case they themselves should stand in order to judge; with my judicial decisions they must also judge it. And my laws and my statutes in regard to all my festal seasons they should keep, and my sabbaths they should sanctify.

[[v26-44-25]]

^<<v26-44-25,25>>^ And to a dead person^&#42;1^ of mankind^&#42;2^ he should not come in so as to become unclean, but for father or for mother or for son or for daughter &#91;or&#93; for brother or for a sister that has not become a husband’s^&#42;3^ they may make themselves unclean.

[NOTE]
====
. “A dead person.” Heb., meth; Gr., psy·khenʹ, “soul.”
. Or, “earthling man.” Heb., ʼa·dhamʹ; Gr., an·throʹpou; Lat., hoʹmi·nem.
. Lit., “to a man.” Heb., leʼishʹ.
====

[[v26-44-26]]

^<<v26-44-26,26>>^ And after his purification, seven days they should number off for him.

[[v26-44-27]]

^<<v26-44-27,27>>^ And on the day of his coming into the holy place,^&#42;1^ into the inner courtyard, to minister in the holy place, he should present his sin offering,’ is the utterance of the Sovereign Lord Jehovah.

[NOTE]
====
. “The holy place.” Heb., haq·qoʹdhesh; Lat., sanc·tu·aʹri·um.
====

[[v26-44-28]]

^<<v26-44-28,28>>^ “‘And it must become theirs as an inheritance:^&#42;1^ I am their inheritance. And no possession should YOU people give them in Israel: I am their possession.

[NOTE]
====
. “There will not be, however, for them an inheritance,” Vgc.
====

[[v26-44-29]]

^<<v26-44-29,29>>^ The grain offering and the sin offering and the guilt offering—they are the ones who will eat them. And every devoted thing in Israel—theirs it will become.

[[v26-44-30]]

^<<v26-44-30,30>>^ And the first of all the first ripe fruits of everything and every contribution of everything out of all YOUR contributions—to the priests it will come to belong; and the firstfruits of YOUR coarse meals YOU should give to the priest, in order to cause a blessing to rest upon your house.^&#42;1^

[NOTE]
====
. “Upon your house,” MTVg; LXXSy, “upon your [pl.] houses.”
====

[[v26-44-31]]

^<<v26-44-31,31>>^ No body &#91;already&#93; dead and no creature torn to pieces of the flying creatures or of the beasts should the priests eat.’

'''

xref:026-ezekiel/026-ezekiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezekiel/026-ezekiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]