include::./index.adoc[]

[[v26-1-0]]
=== Ezekiel, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-1-1]]

^<<v26-1-1,1>>^ Now it came about in the thirtieth year, in the fourth &#91;month&#93;, on the fifth &#91;day&#93; of the month, while I was in the midst of the exiled people by the river Cheʹbar, that the heavens were opened and I began to see visions of God.^&#42;1^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

[[v26-1-2]]

^<<v26-1-2,2>>^ On the fifth &#91;day&#93; of the month, that is, &#91;in&#93; the fifth year of the exile of King Je·hoiʹa·chin,^&#42;1^

[NOTE]
====
. “Jehoiachin.” Heb., Yoh·ya·khinʹ; Gr., I·o·a·kimʹ.
====

[[v26-1-3]]

^<<v26-1-3,3>>^ the word of Jehovah occurred specifically to Ezekiel the son of Buʹzi the priest in the land of the Chal·deʹans by the river Cheʹbar, and upon him in that place the hand of Jehovah came to be.

[[v26-1-4]]

^<<v26-1-4,4>>^ And I began to see, and, look! there was a tempestuous wind^&#42;1^ coming from the north, a great cloud mass and quivering fire, and it^&#42;2^ had a brightness all around, and out of the midst of it^&#42;3^ there was something like the look of electrum,^&#42;4^ out of the midst of the fire.

[NOTE]
====
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
. “It,” masc., referring to the “cloud mass,” masc.
. “It,” fem., evidently referring to the “fire,” fem.
. Lit., “the electrum.” Heb., ha·chash·malʹ; Gr., e·lekʹtrou; Lat., e·lecʹtri. A shining alloy of gold and silver.
====

[[v26-1-5]]

^<<v26-1-5,5>>^ And out of the midst of it there was the likeness of four living creatures,^&#42;1^ and this was how they looked: they had the likeness of earthling man.^&#42;2^

[NOTE]
====
. Or, “shapes.”
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-1-6]]

^<<v26-1-6,6>>^ And &#91;each&#93; one had four faces, and &#91;each&#93; one of them four wings.

[[v26-1-7]]

^<<v26-1-7,7>>^ And their feet were straight feet, and the sole of their feet was like the sole of the foot of a calf; and they were gleaming as with the glow^&#42;1^ of burnished copper.

[NOTE]
====
. Lit., “like the eye of.” Heb., keʽehnʹ.
====

[[v26-1-8]]

^<<v26-1-8,8>>^ And there were the hands of a man^&#42;1^ under their wings on their four sides, and the four of them had their faces and their wings.

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-1-9]]

^<<v26-1-9,9>>^ Their wings were joining one to the other. They would not turn when they went; they would go each one straight forward.

[[v26-1-10]]

^<<v26-1-10,10>>^ And as for the likeness of their faces, the four of them had a man’s face with a lion’s face to the right, and the four of them had a bull’s face on the left; the four of them also had an eagle’s face.

[[v26-1-11]]

^<<v26-1-11,11>>^ That is the way their faces were. And their wings were spreading out upward. Each one had two joining to each other, and two were covering their bodies.

[[v26-1-12]]

^<<v26-1-12,12>>^ And they would go each one straight forward. To wherever the spirit^&#42;1^ would incline to go, they would go. They would not turn as they went.

[NOTE]
====
. “The spirit.” Heb., ha·ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. Compare vs 4 ftn, “Wind.”
====

[[v26-1-13]]

^<<v26-1-13,13>>^ And as for the likeness of the living creatures,^&#42;1^ their appearance was like burning coals of fire. Something like the appearance of torches was moving back and forth between the living creatures, and the fire was bright, and out of the fire there was lightning going forth.

[NOTE]
====
. “The living creatures.” Heb., ha·chai·yohthʹ, fem. pl.; Gr., zoiʹon, the same word as in Re 4:6-9; Lat., a·ni·maʹli·um.
====

[[v26-1-14]]

^<<v26-1-14,14>>^ And on the part of the living creatures there was a going forth and a returning as with the appearance of the lightning.

[[v26-1-15]]

^<<v26-1-15,15>>^ As I kept seeing the living creatures, why, look! there was one wheel on the earth beside the living creatures, by the four faces of each.

[[v26-1-16]]

^<<v26-1-16,16>>^ As for the appearance of the wheels and their structure, it was like the glow of chrysʹo·lite; and the four of them had one likeness. And their appearance and their structure were just as when a wheel proved to be in the midst^&#42;1^ of a wheel.

[NOTE]
====
. Possibly, centered at right angles on the same axis.
====

[[v26-1-17]]

^<<v26-1-17,17>>^ When they went they would go on their four respective sides.^&#42;1^ They would not turn another way when they went.

[NOTE]
====
. Or, “toward their four directions.”
====

[[v26-1-18]]

^<<v26-1-18,18>>^ And as for their rims, they had such height that they caused fearfulness; and their rims were full of eyes all around the four of them.

[[v26-1-19]]

^<<v26-1-19,19>>^ And when the living creatures went, the wheels would go beside them, and when the living creatures were lifted up from the earth, the wheels would be lifted up.

[[v26-1-20]]

^<<v26-1-20,20>>^ Wherever the spirit inclined to go, they would go, the spirit &#91;inclining&#93; to go there; and the wheels themselves would be lifted up close alongside them, for the spirit of the living creature was in the wheels.

[[v26-1-21]]

^<<v26-1-21,21>>^ When they went, these would go; and when they stood still, these would stand still; and when they were lifted up from the earth, the wheels would be lifted up close alongside them, for the spirit of the living creature was in the wheels.

[[v26-1-22]]

^<<v26-1-22,22>>^ And over the heads of the living creatures there was the likeness of an expanse like the sparkle of awesome ice, stretched out over their heads up above.

[[v26-1-23]]

^<<v26-1-23,23>>^ And under the expanse their wings were straight, one to the other. Each one had two wings covering on this side and each one had two covering on that side their bodies.

[[v26-1-24]]

^<<v26-1-24,24>>^ And I got to hear the sound of their wings, a sound like that of vast waters, like the sound of the Almighty One, when they went, the sound of a tumult, like the sound of an encampment. When they stood still, they would let their wings down.

[[v26-1-25]]

^<<v26-1-25,25>>^ And there came to be a voice above the expanse that was over their head. (When they stood still, they would let their wings down.)

[[v26-1-26]]

^<<v26-1-26,26>>^ And above the expanse that was over their head there was something in appearance like sapphire stone, the likeness of a throne. And upon the likeness of the throne there was a likeness of someone in appearance like an earthling man upon it, up above.

[[v26-1-27]]

^<<v26-1-27,27>>^ And I got to see something like the glow of electrum, like the appearance of fire all around inside thereof, from the appearance of his hips and upward; and from the appearance of his hips and downward I saw something like the appearance of fire, and he had a brightness all around.

[[v26-1-28]]

^<<v26-1-28,28>>^ There was something like the appearance of the bow that occurs in a cloud mass on the day of a pouring rain. That is how the appearance was of the brightness round about. It was the appearance of the likeness of the glory of Jehovah. When I got to see &#91;it&#93;, then I fell upon my face, and I began to hear the voice of one speaking.

'''

xref:025-lamentations/025-lamentations-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezekiel/026-ezekiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]