include::./index.adoc[]

[[v26-37-0]]
=== Ezekiel, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-37-1]]

^<<v26-37-1,1>>^ The hand of Jehovah proved to be upon me, so that he brought me forth in the spirit^&#42;1^ of Jehovah and set me down in the midst of the valley plain, and it was full of bones.

[NOTE]
====
. “In the spirit of.” Heb., veruʹach. See Ge 1:2 ftn, “Force.”
====

[[v26-37-2]]

^<<v26-37-2,2>>^ And he had me pass along by them all round about, and, look! there were very many on the surface of the valley plain and, look! they were very dry.

[[v26-37-3]]

^<<v26-37-3,3>>^ And he began to say to me: “Son of man, can these bones come to life?” To that I said: “Sovereign Lord Jehovah, you yourself well know.”

[[v26-37-4]]

^<<v26-37-4,4>>^ And he went on to say to me: “Prophesy over these bones, and you must say to them, ‘O YOU dry bones, hear the word of Jehovah:

[[v26-37-5]]

^<<v26-37-5,5>>^ “‘This is what the Sovereign Lord Jehovah has said to these bones: “Here I am bringing into YOU breath,^&#42;1^ and YOU must come to life.

[NOTE]
====
. “Breath.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v26-37-6]]

^<<v26-37-6,6>>^ And I will put upon YOU sinews and cause to come upon YOU flesh, and I will overlay upon YOU skin and put in YOU breath, and YOU must come to life; and YOU will have to know that I am Jehovah.”’”

[[v26-37-7]]

^<<v26-37-7,7>>^ And I prophesied just as I had been commanded. And a sound began to occur as soon as I prophesied, and here there was a rattling, and bones began to approach, bone to its bone.

[[v26-37-8]]

^<<v26-37-8,8>>^ And I saw, and, look! upon them sinews themselves and flesh itself came up and skin began to be overlaid upon them above. But as regards breath, there was none in them.

[[v26-37-9]]

^<<v26-37-9,9>>^ And he went on saying to me: “Prophesy to the wind.^&#42;1^ Prophesy, O son of man, and you must say to the wind, ‘This is what the Sovereign Lord Jehovah has said: “From the four winds come in, O wind, and blow upon these killed people, that they may come to life.”’”

[NOTE]
====
. “The wind.” Heb., ha·ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v26-37-10]]

^<<v26-37-10,10>>^ And I prophesied just as he had commanded me, and the breath proceeded to come into them, and they began to live and stand upon their feet, a very, very great military force.

[[v26-37-11]]

^<<v26-37-11,11>>^ And he went on to say to me: “Son of man, as regards these bones, they are the whole house of Israel. Here they are saying, ‘Our bones have become dry, and our hope has perished. We have been severed off to ourselves.’

[[v26-37-12]]

^<<v26-37-12,12>>^ Therefore prophesy, and you must say to them, ‘This is what the Sovereign Lord Jehovah has said: “Here I am opening YOUR burial places, and I will bring YOU up out of YOUR burial places, O my people, and bring YOU in upon the soil of Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ And YOU will have to know that I am Jehovah when I open YOUR burial places and when I bring YOU up out of YOUR burial places, O my people.”’

[[v26-37-14]]

^<<v26-37-14,14>>^ ‘And I will put my spirit^&#42;1^ in YOU, and YOU must come to life, and I will settle YOU upon YOUR soil; and YOU will have to know that I myself, Jehovah, have spoken and I have done &#91;it&#93;,’ is the utterance of Jehovah.”

[NOTE]
====
. “My spirit.” Heb., ru·chiʹ.
====

[[v26-37-15]]

^<<v26-37-15,15>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-37-16]]

^<<v26-37-16,16>>^ “And as for you, O son of man, take for yourself a stick and write upon it, ‘For Judah and for the sons of Israel his partners.’^&#42;1^ And take another stick and write upon it, ‘For Joseph, the stick of Eʹphra·im, and all the house of Israel his partners.’

[NOTE]
====
. “Partners,” MmarginTLXXSyVg; M, “partner.”
====

[[v26-37-17]]

^<<v26-37-17,17>>^ And cause them to approach each other into one stick for yourself, and they will actually become just one in your hand.

[[v26-37-18]]

^<<v26-37-18,18>>^ And when the sons of your people begin to say to you, ‘Will you not tell us what these things mean to you?’

[[v26-37-19]]

^<<v26-37-19,19>>^ speak to them, ‘This is what the Sovereign Lord Jehovah has said: “Here I am taking the stick of Joseph, which is in the hand of Eʹphra·im, and the tribes of Israel his partners, and I will put them upon it, that is,^&#42;1^ the stick of Judah, and I shall actually make them one stick, and they must become one in my hand.”’

[NOTE]
====
. “That is.” Or, “with.”
====

[[v26-37-20]]

^<<v26-37-20,20>>^ And the sticks upon which you write must prove to be in your hand before their eyes.

[[v26-37-21]]

^<<v26-37-21,21>>^ “And speak to them, ‘This is what the Sovereign Lord Jehovah has said: “Here I am taking the sons of Israel from among the nations to which they have gone, and I will collect them together from round about and bring them onto their soil.

[[v26-37-22]]

^<<v26-37-22,22>>^ And I shall actually make them one nation in the land, on the mountains of Israel, and one king is what all of them will come to have as king, and they will no longer continue to be two nations, nor will they be divided any longer into two kingdoms.

[[v26-37-23]]

^<<v26-37-23,23>>^ And they will no longer defile themselves with their dungy idols and with their disgusting things and with all their transgressions; and I shall certainly save them from all their dwelling places^&#42;1^ in which they have sinned, and I will cleanse them, and they must become my people, and I myself shall become their God.^&#42;2^

[NOTE]
====
. “Acts of lawlessness,” LXX; Sym, “apostasies.”
. Lit., “to them for God.” Heb., la·hemʹ lEʼ·lo·himʹ.
====

[[v26-37-24]]

^<<v26-37-24,24>>^ “‘“And my servant David will be king over them, and one shepherd is what they will all come to have; and in my judicial decisions they will walk, and my statutes they will keep, and they will certainly carry them out.

[[v26-37-25]]

^<<v26-37-25,25>>^ And they will actually dwell upon the land that I gave to my servant, to Jacob, in which YOUR forefathers dwelt, and they will actually dwell upon it, they and their sons and their sons’ sons to time indefinite, and David my servant will be their chieftain^&#42;1^ to time indefinite.

[NOTE]
====
. Or, “nasi.” Heb., na·siʼʹ; Gr., arʹkhon; Lat., prinʹceps.
====

[[v26-37-26]]

^<<v26-37-26,26>>^ “‘“And I will conclude with them a covenant of peace; an indefinitely lasting covenant is what there will come to be with them. And I will place them and multiply them and place my sanctuary in the midst of them to time indefinite.

[[v26-37-27]]

^<<v26-37-27,27>>^ And my tabernacle will actually prove to be over them, and I shall certainly become their God, and they themselves will become my people.

[[v26-37-28]]

^<<v26-37-28,28>>^ And the nations will have to know that I, Jehovah, am sanctifying Israel when my sanctuary comes to be in the midst of them to time indefinite.”’”

'''

xref:026-ezekiel/026-ezekiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezekiel/026-ezekiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]