include::./index.adoc[]

[[v26-3-0]]
=== Ezekiel, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-3-1]]

^<<v26-3-1,1>>^ And he proceeded to say to me: “Son of man, what you find, eat. Eat this roll, and go, speak to the house of Israel.”

[[v26-3-2]]

^<<v26-3-2,2>>^ So I opened my mouth, and he gradually made me eat this roll.

[[v26-3-3]]

^<<v26-3-3,3>>^ And he went on to say to me: “Son of man, you should cause your own belly to eat, that you may fill your very intestines with this roll that I am giving you.” And I began to eat it, and it came to be in my mouth like honey for sweetness.

[[v26-3-4]]

^<<v26-3-4,4>>^ And he continued saying to me: “Son of man, go, enter in among the house of Israel, and you must speak with my words to them.

[[v26-3-5]]

^<<v26-3-5,5>>^ For it is not to a people who are unintelligible in language^&#42;1^ or heavy^&#42;2^ of tongue that you are being sent—to the house of Israel,

[NOTE]
====
. Lit., “lip.” See Ge 11:1 ftn, “Language.”
. Or, “slow.”
====

[[v26-3-6]]

^<<v26-3-6,6>>^ not to numerous peoples unintelligible in language or heavy in tongue, whose words you cannot hear &#91;understandingly&#93;. If it was to them that I had sent you, those very ones would listen to you.

[[v26-3-7]]

^<<v26-3-7,7>>^ But as for the house of Israel, they will not want to listen to you, for they are not wanting to listen to me; because all those of the house of Israel are hardheaded^&#42;1^ and hardhearted.

[NOTE]
====
. Lit., “strong of forehead.”
====

[[v26-3-8]]

^<<v26-3-8,8>>^ Look! I have made^&#42;1^ your face exactly as hard as their faces and your forehead exactly as hard as their foreheads.

[NOTE]
====
. Lit., “given.”
====

[[v26-3-9]]

^<<v26-3-9,9>>^ Like a diamond,^&#42;1^ harder than flint, I have made^&#42;2^ your forehead. You must not be afraid of them, and you must not be struck with terror at their faces, for they are a rebellious house.”

[NOTE]
====
. Or, “emery.”
. Lit., “given.”
====

[[v26-3-10]]

^<<v26-3-10,10>>^ And he went on to say to me: “Son of man, all my words that I shall speak to you, take into your heart and hear with your own ears.

[[v26-3-11]]

^<<v26-3-11,11>>^ And go, enter in among the exiled people, among the sons of your people, and you must speak to them and say to them, ‘This is what the Sovereign Lord Jehovah has said,’ regardless of whether they hear or they refrain.”

[[v26-3-12]]

^<<v26-3-12,12>>^ And a spirit^&#42;1^ proceeded to bear me along and I began to hear behind me the sound of a great rushing: “Blessed be the glory of Jehovah from his place.”

[NOTE]
====
. “A spirit.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus. Compare 1:4 ftn, “Wind.”
====

[[v26-3-13]]

^<<v26-3-13,13>>^ And there was the sound of the wings of the living creatures that were closely touching each other, and the sound of the wheels close beside them, and the sound of a great rushing.

[[v26-3-14]]

^<<v26-3-14,14>>^ And &#91;the&#93; spirit bore me along and proceeded to take me, so that I went bitterly in the rage of my spirit, and the hand of Jehovah upon me was strong.

[[v26-3-15]]

^<<v26-3-15,15>>^ So I entered in among the exiled people at Tel-aʹbib, who were dwelling by the river Cheʹbar, and I began to dwell^&#42;1^ where they were dwelling; and I kept dwelling there for seven days, stunned in the midst of them.

[NOTE]
====
. “And I began to dwell,” Mmargin and many Heb. mss.
====

[[v26-3-16]]

^<<v26-3-16,16>>^ And it came about at the end of seven days that the word of Jehovah proceeded to occur to me, saying:

[[v26-3-17]]

^<<v26-3-17,17>>^ “Son of man, a watchman^&#42;1^ is what I have made you to the house of Israel, and you must hear from my mouth speech and you must warn them from me.

[NOTE]
====
. Or, “a lookout.” Heb., tso·phehʹ.
====

[[v26-3-18]]

^<<v26-3-18,18>>^ When I say to someone wicked, ‘You will positively die,’^&#42;1^ and you do not actually warn him and speak in order to warn the wicked one from his wicked way to preserve him alive, he being wicked, in his error he will die, but his blood I shall ask back from your own hand.

[NOTE]
====
. “You will positively die.” Lit., “Dying you [sing.] will die.” Heb., mohth ta·muthʹ. See Ge 2:17 ftn.
====

[[v26-3-19]]

^<<v26-3-19,19>>^ But as for you, in case you have warned someone wicked and he does not actually turn back from his wickedness and from his wicked way, he himself for his error will die; but as for you, you will have delivered your own soul.^&#42;1^

[NOTE]
====
. “Your own soul.” Heb., naph·shekhaʹ; Gr., psy·khenʹ sou; Lat., aʹni·mam tuʹam. See App 4A.
====

[[v26-3-20]]

^<<v26-3-20,20>>^ And when someone righteous turns back from his righteousness and actually does injustice and I must put a stumbling block before him, he himself will die because you did not warn him. For his sin he will die, and his righteous acts that he did will not be remembered, but his blood I shall ask back from your own hand.

[[v26-3-21]]

^<<v26-3-21,21>>^ And as for you, in case you have warned someone righteous that the righteous one should not sin, and he himself does not actually sin, he will without fail keep on living because he had been warned, and you yourself will have delivered your own soul.”

[[v26-3-22]]

^<<v26-3-22,22>>^ And the hand of Jehovah came to be upon me there and he proceeded to say to me: “Get up, go forth to the valley plain, and there I shall speak with you.”

[[v26-3-23]]

^<<v26-3-23,23>>^ So I got up and went forth to the valley plain, and, look! the glory of Jehovah was standing there, like the glory that I had seen by the river Cheʹbar, and I went falling upon my face.

[[v26-3-24]]

^<<v26-3-24,24>>^ Then spirit entered into me and made me stand up on my feet, and he began to speak with me and say to me:
“Come, be shut up inside your house.

[[v26-3-25]]

^<<v26-3-25,25>>^ And you, O son of man, look! they will certainly put cords upon you and bind you with them so that you cannot go forth into the midst of them.

[[v26-3-26]]

^<<v26-3-26,26>>^ And your very tongue I will make stick to the roof of your mouth, and you will certainly become mute, and you will not become to them a man^&#42;1^ administering reproof, because they are a rebellious house.

[NOTE]
====
. “A man.” Heb., leʼishʹ; Gr., anʹdra; Lat., vir.
====

[[v26-3-27]]

^<<v26-3-27,27>>^ And when I speak with you I shall open your mouth, and you must say to them, ‘This is what the Sovereign Lord Jehovah has said.’ Let the one hearing hear, and let the one refraining refrain, because they are a rebellious house.

'''

xref:026-ezekiel/026-ezekiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezekiel/026-ezekiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]