include::./index.adoc[]

[[v26-10-0]]
=== Ezekiel, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-10-1]]

^<<v26-10-1,1>>^ And I continued to see, and, look! upon the expanse that was over the head of the cherubs there was something like sapphire stone, like the appearance of the likeness of a throne, appearing above them.

[[v26-10-2]]

^<<v26-10-2,2>>^ And he proceeded to say to the man clothed with the linen, even to say: “Enter in between the wheelwork, in under the cherubs,^&#42;1^ and fill the hollows of both your hands with coals of fire from between the cherubs and toss &#91;them&#93; over the city.” So he entered in before my eyes.

[NOTE]
====
. “Cher­ubs,” LXXVgc. See 9:3 ftn, “Cherubs.”
====

[[v26-10-3]]

^<<v26-10-3,3>>^ And the cherubs were standing to the right of the house when the man^&#42;1^ entered, and the cloud was filling the inner courtyard.

[NOTE]
====
. “The man.” Heb., ha·ʼishʹ.
====

[[v26-10-4]]

^<<v26-10-4,4>>^ And the glory of Jehovah proceeded to rise up from the cherubs to the threshold of the house, and the house gradually became filled with the cloud, and the courtyard itself was full of the brightness of the glory of Jehovah.

[[v26-10-5]]

^<<v26-10-5,5>>^ And the very sound of the wings of the cherubs made itself heard to the outer courtyard, like the sound of God Almighty^&#42;1^ when he speaks.

[NOTE]
====
. “God Almighty.” Heb., ʼEl-Shad·daiʹ; Gr., The·ouʹ Sad·da·iʹ; Lat., Deʹi O·mni·po·tenʹtis.
====

[[v26-10-6]]

^<<v26-10-6,6>>^ And it came about, when he commanded the man clothed with the linen, saying: “Take fire from between the wheelwork, from between the cherubs,” that he proceeded to enter and stand beside the wheel.

[[v26-10-7]]

^<<v26-10-7,7>>^ Then the cherub thrust his hand out from between the cherubs to the fire that was between the cherubs and carried and put &#91;it&#93; into the hollows of the hands of the one clothed with the linen, who now took &#91;it&#93; and went out.

[[v26-10-8]]

^<<v26-10-8,8>>^ And there was seen belonging to the cherubs the representation of a hand of earthling man^&#42;1^ under their wings.

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-10-9]]

^<<v26-10-9,9>>^ And I continued to see, and, look! there were four wheels beside the cherubs, one wheel beside the one cherub and one wheel beside the other cherub, and the appearance of the wheels was like the glow of a chrysʹo·lite stone.

[[v26-10-10]]

^<<v26-10-10,10>>^ And as for their appearance, the four of them had one likeness, just as when a wheel proves to be in the midst^&#42;1^ of a wheel.

[NOTE]
====
. See 1:16 ftn.
====

[[v26-10-11]]

^<<v26-10-11,11>>^ When they would go, to their four sides^&#42;1^ they would go. They would not change direction when they went, because the place to which the head would face, after it they would go. They would not change direction when they went.

[NOTE]
====
. Or, “directions.”
====

[[v26-10-12]]

^<<v26-10-12,12>>^ And all their flesh and their backs and their hands and their wings and the wheels were full of eyes all around. The four of them had their wheels.

[[v26-10-13]]

^<<v26-10-13,13>>^ As regards the wheels, to them it was called out in my ears, “O wheelwork!”

[[v26-10-14]]

^<<v26-10-14,14>>^ And &#91;each&#93; one had four faces. The first face was the face of the cherub, and the second face was the face of earthling man,^&#42;1^ and the third was the face of a lion, and the fourth was the face of an eagle.

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-10-15]]

^<<v26-10-15,15>>^ And the cherubs would rise—it was the &#91;same&#93; living creature that I had seen at the river Cheʹbar—

[[v26-10-16]]

^<<v26-10-16,16>>^ and when the cherubs went, the wheels would go alongside them; and when the cherubs lifted up their wings to be high above the earth, the wheels would not change direction, even they themselves, from alongside them.

[[v26-10-17]]

^<<v26-10-17,17>>^ When these stood still, they would stand still; and when these rose, they would rise with them, for the spirit of the living creature^&#42;1^ was in them.

[NOTE]
====
. “The living creature.” Heb., ha·chai·yahʹ; LXXVg, “life.”
====

[[v26-10-18]]

^<<v26-10-18,18>>^ And the glory of Jehovah proceeded to go forth from over the threshold of the house and to stand still over the cherubs.

[[v26-10-19]]

^<<v26-10-19,19>>^ And the cherubs now lifted up their wings and rose from the earth before my eyes. When they went forth, the wheels also were close alongside them; and they began standing at the eastern entrance of the gate of the house of Jehovah, and the glory of the God of Israel was over them, from above.

[[v26-10-20]]

^<<v26-10-20,20>>^ This is the living creature that I had seen under the God of Israel^&#42;1^ at the river Cheʹbar, so that I came to know that they were cherubs.

[NOTE]
====
. “The God of Israel.” Heb., ʼElo·heh-Yis·ra·ʼelʹ.
====

[[v26-10-21]]

^<<v26-10-21,21>>^ As for the four, &#91;each&#93; one had four faces and &#91;each&#93; one had four wings, and the likeness of the hands of earthling man^&#42;1^ was under their wings.

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-10-22]]

^<<v26-10-22,22>>^ And as for the likeness of their faces, they were the faces the appearance of which I had seen by the river Cheʹbar, the very ones. They would go each one straight forward.

'''

xref:026-ezekiel/026-ezekiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezekiel/026-ezekiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]