include::./index.adoc[]

[[v26-47-0]]
=== Ezekiel, 47
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-47-1]]

^<<v26-47-1,1>>^ And gradually he brought me back to the entrance of the House, and, look! there was water going forth from under the threshold of the House eastward, for the front of the House was east. And the water was going down from under, from the right-hand side of the House, south of the altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ And he gradually brought me forth by the way of the north gate and took me around by the way outside to the outer gate that is facing toward the east, and, look! water was trickling from the right-hand side.

[[v26-47-3]]

^<<v26-47-3,3>>^ When the man^&#42;1^ went forth eastward with a measuring line in his hand, he also proceeded to measure a thousand in cubits and to make me pass through the water, water &#91;up&#93; to the ankles.^&#42;2^

[NOTE]
====
. “The man.” Heb., ha·ʼishʹ.
. Lit., “water of ankles.”
====

[[v26-47-4]]

^<<v26-47-4,4>>^ And he continued measuring a thousand and then made me pass through the water, water &#91;up&#93; to the knees.
And he continued measuring a thousand and now made me pass through—water &#91;up&#93; to the hips.

[[v26-47-5]]

^<<v26-47-5,5>>^ And he continued measuring a thousand. It was a torrent that I was not able to pass through, for the water had got high, water &#91;permitting&#93; swimming, a torrent that could not be passed through.

[[v26-47-6]]

^<<v26-47-6,6>>^ At that he said to me: “Have you seen &#91;this&#93;, O son of man?”
Then he had me walk and had me return^&#42;1^ &#91;to&#93; the bank of the torrent.

[NOTE]
====
. “Had me return,” MTVg; Sy, “had me sit down”; LXX omits.
====

[[v26-47-7]]

^<<v26-47-7,7>>^ When I returned, why, look! on the bank of the torrent there were very many trees, on this side and on that side.

[[v26-47-8]]

^<<v26-47-8,8>>^ And he went on to say to me: “This water is going forth to the eastern region and must go down through the Arʹa·bah.^&#42;1^ And it must come to the sea. It being brought forth into the sea itself, &#91;its&#93; water^&#42;2^ is also actually healed.

[NOTE]
====
. Or, “the desert plain.” See De 1:1 ftn, “Plains.”
. “Into the sea, into the stinking waters, and the waters,” Sy.
====

[[v26-47-9]]

^<<v26-47-9,9>>^ And it must occur that every living soul^&#42;1^ that swarms, in every place to which the double-size torrent^&#42;2^ comes, will get life.^&#42;3^ And it must occur that there will be very many fish, because there is where this water will certainly come, and the &#91;seawater&#93; will be healed, and everything will be alive where the torrent comes.

[NOTE]
====
. “Living soul.” Heb., neʹphesh chai·yahʹ; Gr., psy·kheʹ ton zoiʹon; Lat., aʹni·ma viʹvens. See Ge 2:7 ftn, “Soul”; App 4A.
. Lit., “two torrents,” M; TSy, “the waters of the torrent”; LXX, “the river”; Vg, “the torrent.”
. Or, “will come to life; will live.” Heb., yich·yehʹ.
====

[[v26-47-10]]

^<<v26-47-10,10>>^ “And it must occur that fishers will actually stand alongside it from En-geʹdi even up to En-egʹla·im. There will come to be a drying yard for dragnets. In their kinds^&#42;1^ their fish will prove to be, like the fish of the Great Sea,^&#42;2^ very many.

[NOTE]
====
. “In their kinds.” Heb., lemi·nahʹ; Lat., speʹci·es.
. That is, the Mediterranean Sea.
====

[[v26-47-11]]

^<<v26-47-11,11>>^ “There are its swampy places and its marshy places, and they will not be healed. To salt they will certainly be given.

[[v26-47-12]]

^<<v26-47-12,12>>^ “And alongside the torrent there will come up, along its bank on this side and on that side, all sorts of trees for food. Their leafage will not wither, nor will their fruitage be consumed. In their months they will bear new fruit, because the water for them—it is coming forth from the very sanctuary.^&#42;1^ And their fruitage must prove to be for food and their leafage for healing.”

[NOTE]
====
. “The . . . sanctuary.” Heb., ham·miq·dashʹ.
====

[[v26-47-13]]

^<<v26-47-13,13>>^ This is what the Sovereign Lord Jehovah has said: “This is the territory that YOU will assign to yourselves for inheritance as the land for the twelve tribes of Israel, with two pieces of field to Joseph.

[[v26-47-14]]

^<<v26-47-14,14>>^ And YOU people must inherit it, each one the same as his brother, which &#91;land&#93; I raised my hand &#91;in an oath&#93; to give to YOUR forefathers; and this land must fall to YOU &#91;by lot&#93; for inheritance.

[[v26-47-15]]

^<<v26-47-15,15>>^ “And this is the boundary of the land to the northern side, from the Great Sea by the way to Hethʹlon, as one comes to Zeʹdad,

[[v26-47-16]]

^<<v26-47-16,16>>^ Haʹmath, Be·roʹthah, Sibʹra·im, which is between the boundary of Damascus and the boundary of Haʹmath; Haʹzer-hatʹti·con, which is toward the boundary of Ha·u·ranʹ.

[[v26-47-17]]

^<<v26-47-17,17>>^ And the boundary from the sea must prove to be Haʹzar-eʹnon,^&#42;1^ the boundary of Damascus and north—northward, and the boundary of Haʹmath. This is the northern side.

[NOTE]
====
. “Hazar-enon,” M; LXX, “the courtyard of Ainan.”
====

[[v26-47-18]]

^<<v26-47-18,18>>^ “And the eastern side is from between Ha·u·ranʹ and Damascus and between Gilʹe·ad and the land of Israel; the Jordan,^&#42;1^ from the boundary to the eastern sea YOU people should measure. This is the eastern side.

[NOTE]
====
. Possibly, parallel to the Jordan River.
====

[[v26-47-19]]

^<<v26-47-19,19>>^ “And the southern^&#42;1^ side is to the south,^&#42;2^ from Taʹmar to the waters of Merʹi·bath-kaʹdesh, the torrent valley to the Great Sea. This is the side to the south, toward the Negʹeb.^&#42;3^

[NOTE]
====
. “Southern.” Heb., neʹghev.
. Or, “southward.” Heb., teh·maʹnah.
. Or, “south.” That is, the southern part of the Promised Land. See Ge 12:9 ftn.
====

[[v26-47-20]]

^<<v26-47-20,20>>^ “And the western side is the Great Sea, from the boundary straight ahead to the entering in to Haʹmath.^&#42;1^ This is the western side.”

[NOTE]
====
. “To the entering in to Hamath.” Possibly, “Lebo-Hamath.” Heb., levohʼʹ Chamathʹ. See Jos 13:5 ftn, “Hamath”; KB, p. 470, under לבא (La·voʼʹ).
====

[[v26-47-21]]

^<<v26-47-21,21>>^ “And YOU must apportion this land to yourselves, to the twelve tribes of Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ And it must occur that YOU should allot it for inheritance to yourselves and to the alien residents who are residing as aliens in YOUR midst, who have become father to sons in the midst of YOU. And they must become to YOU like a native among the sons of Israel. With YOU people they will fall &#91;by lot&#93; into an inheritance in the midst of the tribes of Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ And it must occur that in the tribe with which the alien resident has taken up residence as an alien, there is where YOU should give his inheritance,” is the utterance of the Sovereign Lord Jehovah.

'''

xref:026-ezekiel/026-ezekiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezekiel/026-ezekiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]