include::./index.adoc[]

[[v26-25-0]]
=== Ezekiel, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v26-25-1]]

^<<v26-25-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v26-25-2]]

^<<v26-25-2,2>>^ “Son of man, set your face toward the sons of Amʹmon and prophesy against them.

[[v26-25-3]]

^<<v26-25-3,3>>^ And you must say concerning the sons of Amʹmon, ‘Hear the word of the Sovereign Lord Jehovah. This is what the Sovereign Lord Jehovah has said: “For the reason that you^&#42;1^ have said Aha! against my sanctuary, because it has been profaned, and against the soil of Israel, because it has been laid desolate, and against the house of Judah, because they have gone into exile,

[NOTE]
====
. “You,” fem. sing., referring to the country of Ammon.
====

[[v26-25-4]]

^<<v26-25-4,4>>^ therefore here I am giving you to the Orientals^&#42;1^ as something to possess, and they will set up their walled camps in you and will certainly put in you their tabernacles. They themselves will eat your fruitage, and they themselves will drink your milk.

[NOTE]
====
. Lit., “the sons of the East.”
====

[[v26-25-5]]

^<<v26-25-5,5>>^ And I will make Rabʹbah a pasture ground of camels and the sons of Amʹmon a resting-place of a flock; and YOU people will have to know that I am Jehovah.”’”

[[v26-25-6]]

^<<v26-25-6,6>>^ “For this is what the Sovereign Lord Jehovah has said, ‘For the reason that you^&#42;1^ clapped the hands and you stamped with the feet and you kept rejoicing with all scorn on your part in &#91;your&#93; soul against the soil of Israel,

[NOTE]
====
. “You,” masc. sing., referring to Ammon.
====

[[v26-25-7]]

^<<v26-25-7,7>>^ therefore here I am; I have stretched out my hand against you, and I will give you as something to plunder to the nations; and I will cut you off from the peoples and destroy you from the lands. I shall annihilate you, and you will have to know that I am Jehovah.’

[[v26-25-8]]

^<<v26-25-8,8>>^ “This is what the Sovereign Lord Jehovah has said, ‘For the reason that Moʹab and Seʹir have said: “Look! The house of Judah is like all the other nations,”

[[v26-25-9]]

^<<v26-25-9,9>>^ therefore here I am opening the slope of Moʹab at the cities, at his cities to his frontier, the decoration of &#91;the&#93; land, Beth-jeshʹi·moth, Baʹal-meʹon, even to Kir·i·a·thaʹim,

[[v26-25-10]]

^<<v26-25-10,10>>^ to the Orientals,^&#42;1^ alongside the sons of Amʹmon; and I will make it something to possess, in order that it may not be remembered, &#91;that is,&#93; the sons of Amʹmon, among the nations.

[NOTE]
====
. See vs 4 ftn.
====

[[v26-25-11]]

^<<v26-25-11,11>>^ And in Moʹab I shall execute acts of judgment; and they will have to know that I am Jehovah.’

[[v26-25-12]]

^<<v26-25-12,12>>^ “This is what the Sovereign Lord Jehovah has said, ‘For the reason that Eʹdom has acted in taking vengeance upon the house of Judah and they kept doing wrong extensively and avenged themselves on them,

[[v26-25-13]]

^<<v26-25-13,13>>^ therefore this is what the Sovereign Lord Jehovah has said: “I will also stretch out my hand against Eʹdom and cut off from it man^&#42;1^ and domestic animal, and I will make it a devastated place from Teʹman, even to Deʹdan. By the sword they will fall.

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v26-25-14]]

^<<v26-25-14,14>>^ ‘And I will bring my vengeance on Eʹdom by the hand of my people Israel; and they must do in Eʹdom according to my anger and according to my rage; and they will have to know what my vengeance is,’ is the utterance of the Sovereign Lord Jehovah.”’

[[v26-25-15]]

^<<v26-25-15,15>>^ “This is what the Sovereign Lord Jehovah has said, ‘For the reason that the Phi·lisʹtines have acted with vengeance and they kept avenging themselves with a vengeance with scorn in &#91;the&#93; soul,^&#42;1^ in order to cause ruin, with an indefinitely lasting enmity,

[NOTE]
====
. “In [the] soul.” Heb., beneʹphesh; Gr., psy·khesʹ; Lat., aʹni·mo. See App 4A.
====

[[v26-25-16]]

^<<v26-25-16,16>>^ therefore this is what the Sovereign Lord Jehovah has said: “Here I am stretching out my hand against the Phi·lisʹtines, and I will cut off the Cherʹe·thites and destroy the rest of the seacoast.

[[v26-25-17]]

^<<v26-25-17,17>>^ And I will execute in them great acts of vengeance, with raging reproofs; and they will have to know that I am Jehovah when I bring my vengeance on them.”’”

'''

xref:026-ezekiel/026-ezekiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezekiel/026-ezekiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]