include::./index.adoc[]

[[v57-1-0]]
=== To Philemon, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v57-1-1]]

^<<v57-1-1,1>>^ Paul, a prisoner for the sake of Christ Jesus,^&#42;1^ and Timothy, &#91;our&#93; brother, to Phi·leʹmon,^&#42;2^ our beloved one and fellow worker,

[NOTE]
====
. Or, “a prisoner of Christ Jesus.”
. “To Philemon.” Gr., Phi·leʹmo·ni, meaning “Loving.”
====

[[v57-1-2]]

^<<v57-1-2,2>>^ and to Apʹphi·a, our sister, and to Ar·chipʹpus, our fellow soldier, and to the congregation that is in your house:

[[v57-1-3]]

^<<v57-1-3,3>>^ May YOU people have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[[v57-1-4]]

^<<v57-1-4,4>>^ I always thank my God when I make mention of you in my prayers,

[[v57-1-5]]

^<<v57-1-5,5>>^ as I keep hearing of your love and faith which you have toward the Lord Jesus and toward all the holy ones;

[[v57-1-6]]

^<<v57-1-6,6>>^ in order that the sharing of your faith may go into action^&#42;1^ by your acknowledging^&#42;2^ of every good thing among us as related to Christ.

[NOTE]
====
. “May go into action.” Lit., “might become operative within.”
. “By your acknowledging.” Lit., “in accurate knowledge.”
====

[[v57-1-7]]

^<<v57-1-7,7>>^ For I got much joy and comfort over your love, because the tender affections^&#42;1^ of the holy ones have been refreshed through you, brother.

[NOTE]
====
. “The tender affections.” Lit., “the bowels.”
====

[[v57-1-8]]

^<<v57-1-8,8>>^ For this very reason, though I have great freeness of speech^&#42;1^ in connection with Christ to order you to do what is proper,

[NOTE]
====
. Lit., “outspokenness.”
====

[[v57-1-9]]

^<<v57-1-9,9>>^ I am exhorting^&#42;1^ you rather on the basis of love, seeing that I am such as I am, Paul an aged man,^&#42;2^ yes, now also a prisoner for the sake of Christ Jesus;

[NOTE]
====
. Lit., “I am encouraging.”
. Or, “an ambassador.”
====

[[v57-1-10]]

^<<v57-1-10,10>>^ I am exhorting you concerning my child, to whom I became a father while in my &#91;prison&#93; bonds, O·nesʹi·mus,^&#42;1^

[NOTE]
====
. “Onesimus,” meaning “Profitable.”
====

[[v57-1-11]]

^<<v57-1-11,11>>^ formerly useless to you but now useful to you and to me.

[[v57-1-12]]

^<<v57-1-12,12>>^ This very one I am sending back to you, yes, him, that is, my own tender affections.^&#42;1^

[NOTE]
====
. See vs 7 ftn.
====

[[v57-1-13]]

^<<v57-1-13,13>>^ I would like to hold him back for myself that in place of you he might keep on ministering^&#42;1^ to me in the &#91;prison&#93; bonds I bear for the sake of the good news.^&#42;2^

[NOTE]
====
. Lit., “he may serve.”
. Or, “in the bonds of the good news.”
====

[[v57-1-14]]

^<<v57-1-14,14>>^ But without your consent I do not want to do anything, so that your good act may be, not as under compulsion,^&#42;1^ but of your own free will.^&#42;2^

[NOTE]
====
. Lit., “necessity.”
. Lit., “but according to what is voluntary.”
====

[[v57-1-15]]

^<<v57-1-15,15>>^ Perhaps really on this account he broke away for an hour, that you may have him back forever,

[[v57-1-16]]

^<<v57-1-16,16>>^ no longer as a slave but as more than a slave, as a brother beloved, especially so to me, yet how much more so to you both in fleshly relationship and in &#91;the&#93; Lord.

[[v57-1-17]]

^<<v57-1-17,17>>^ If, therefore, you consider me a sharer, receive him kindly the way you would me.

[[v57-1-18]]

^<<v57-1-18,18>>^ Moreover, if he did you any wrong or owes you anything, keep this charged to my account.^&#42;1^

[NOTE]
====
. Lit., “to me be you setting to account.”
====

[[v57-1-19]]

^<<v57-1-19,19>>^ I Paul am writing with my own hand: I will pay it back—not to be telling you that, besides, you owe me even yourself.

[[v57-1-20]]

^<<v57-1-20,20>>^ Yes, brother, may I derive profit from you in connection with &#91;the&#93; Lord: refresh my tender affections in connection with Christ.

[[v57-1-21]]

^<<v57-1-21,21>>^ Trusting in your compliance,^&#42;1^ I am writing you, knowing you will even do more than the things I say.

[NOTE]
====
. Lit., “obedience.”
====

[[v57-1-22]]

^<<v57-1-22,22>>^ But along with that, also get lodging ready for me, for I am hoping that through the prayers of YOU people I shall be set at liberty for YOU.

[[v57-1-23]]

^<<v57-1-23,23>>^ Sending you greetings is Epʹa·phras my fellow captive in union with Christ,

[[v57-1-24]]

^<<v57-1-24,24>>^ &#91;also&#93; Mark, Ar·is·tarʹchus, Deʹmas, Luke, my fellow workers.

[[v57-1-25]]

^<<v57-1-25,25>>^ The undeserved kindness of the Lord Jesus Christ &#91;be&#93; with the spirit YOU people &#91;show&#93;.^&#42;1^

[NOTE]
====
. Lit., “with your spirit.”
====

'''

xref:056-titus/056-titus-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebrews/058-hebrews-001.adoc#v58-1-0[Próximo Capítulo &#62;]