include::./index.adoc[]

[[v35-2-0]]
=== Habakkuk, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v35-2-1]]

^<<v35-2-1,1>>^ At my guard post I will keep standing, and I will keep myself stationed upon &#91;the&#93; bulwark;^&#42;1^ and I shall keep watch, to see what he will speak by^&#42;2^ me and what I shall reply at the reproof of me.

[NOTE]
====
. “Bulwark.” Heb., ma·tsohrʹ; Gr., peʹtran, and Syr., kiʼ·phaʼ, “rock”; Lat., mu·ni·ti·oʹnem, “fortification.”
. Or, “with; to.”
====

[[v35-2-2]]

^<<v35-2-2,2>>^ And Jehovah proceeded to answer me and to say: “Write down &#91;the&#93; vision, and set &#91;it&#93; out plainly upon tablets, in order that the one reading aloud from it may do so fluently.^&#42;1^

[NOTE]
====
. Lit., “may run.”
====

[[v35-2-3]]

^<<v35-2-3,3>>^ For &#91;the&#93; vision is yet for the appointed time, and it keeps panting on to the end,^&#42;1^ and it will not tell a lie. Even if it should delay, keep in expectation of it; for it will without fail come true. It will not be late.

[NOTE]
====
. “It is a disclosure for the end,” by a slight correction.
====

[[v35-2-4]]

^<<v35-2-4,4>>^ “Look! His soul^&#42;1^ has been swelled up; it has not been upright within him.^&#42;2^ But as for the righteous one, by his faithfulness he will keep living.

[NOTE]
====
. “His soul.” Heb., naph·shohʹ; Lat., aʹni·ma. See App 4A.
. “If anyone shrinks back, my soul [Gr., psy·kheʹ] has no pleasure in him,” LXX.
====

[[v35-2-5]]

^<<v35-2-5,5>>^ And, indeed, because the wine is dealing treacherously, an able-bodied man is self-assuming; and he will not reach his goal, he who has made his soul spacious just like Sheʹol,^&#42;1^ and who is like death and cannot be satisfied. And he keeps gathering to himself all the nations and collecting together to himself all the peoples.

[NOTE]
====
. “Like Sheol.” Heb., kish·ʼohlʹ; Gr., haiʹdes; Syr., shiul; Lat., in·ferʹnus. See App 4B.
====

[[v35-2-6]]

^<<v35-2-6,6>>^ Will not these very ones, all of them, lift up against him a proverbial saying and an alluding remark, insinuations at him? And one will say,
“‘Woe to him who is multiplying what is not his own—O how long!—and who is making debt heavy against himself!

[[v35-2-7]]

^<<v35-2-7,7>>^ Will not those claiming interest of you rise up suddenly, and those wake up who are violently shaking you, and you certainly become to them something to pillage?

[[v35-2-8]]

^<<v35-2-8,8>>^ Because you yourself despoiled many nations, all the remaining ones of &#91;the&#93; peoples will despoil you, because of the shedding of blood of mankind^&#42;1^ and the violence to &#91;the&#93; earth, &#91;the&#93; town and all those dwelling in it.

[NOTE]
====
. Or, “earthling men.” Heb., ʼa·dhamʹ, sing. but in a collective sense.
====

[[v35-2-9]]

^<<v35-2-9,9>>^ “‘Woe to the one that is making evil gain for his house, in order to set his nest on the height, so as to be delivered from the grasp^&#42;1^ of what is calamitous!

[NOTE]
====
. Lit., “from the palm.” Heb., mik·kaphʹ.
====

[[v35-2-10]]

^<<v35-2-10,10>>^ You have counseled something shameful to your house, the cutting off of many peoples; and your soul is sinning.

[[v35-2-11]]

^<<v35-2-11,11>>^ For out of &#91;the&#93; wall a stone itself will cry out plaintively, and from the woodwork a rafter^&#42;1^ itself will answer it.

[NOTE]
====
. Possibly, “the stuccowork.”
====

[[v35-2-12]]

^<<v35-2-12,12>>^ “‘Woe to the one that is building a city by bloodshed,^&#42;1^ and that has solidly established a town by unrighteousness!

[NOTE]
====
. Lit., “bloods.”
====

[[v35-2-13]]

^<<v35-2-13,13>>^ Look! Is it not from Jehovah of armies^&#42;1^ that peoples will toil on only for the fire, and that national groups will tire themselves out merely for nothing?

[NOTE]
====
. “Jehovah of armies,” MTVg; LXX, “Jehovah Almighty.”
====

[[v35-2-14]]

^<<v35-2-14,14>>^ For the earth will be filled with the knowing of the glory of Jehovah^&#42;1^ as the waters themselves cover over &#91;the&#93; sea.

[NOTE]
====
. See App 1C §2.
====

[[v35-2-15]]

^<<v35-2-15,15>>^ “‘Woe to the one giving his companions something to drink, attaching &#91;to it&#93; your rage^&#42;1^ and anger, in order to make &#91;them&#93; drunk, for the purpose of looking upon their parts of shame.

[NOTE]
====
. “Attaching [to it] your rage.” Heb., מספ]ח[ חמתך; by omitting the possible dittography of ח, “from the bowl [or, goblet] of your rage.”
====

[[v35-2-16]]

^<<v35-2-16,16>>^ You will certainly be satiated with dishonor instead of glory. Drink also, you yourself, and be considered uncircumcised. The cup of the right hand of Jehovah^&#42;1^ will come around to you, and there will be disgrace upon your glory;

[NOTE]
====
. See App 1C §2.
====

[[v35-2-17]]

^<<v35-2-17,17>>^ because the violence &#91;done&#93; to Lebʹa·non is what will cover you, and the rapacity upon &#91;the&#93; beasts that terrifies them, because of the shedding of blood of mankind^&#42;1^ and the violence &#91;done&#93; to &#91;the&#93; earth, the town and all those dwelling in it.

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v35-2-18]]

^<<v35-2-18,18>>^ Of what benefit has a carved image been, when the former of it has carved it, a molten statue, and an instructor in falsehood? when the former of its form has trusted in it, to the extent of making valueless gods^&#42;1^ that are speechless?

[NOTE]
====
. Or, “worthless gods.” Heb., ʼeli·limʹ; LXX, “idols.”
====

[[v35-2-19]]

^<<v35-2-19,19>>^ “‘Woe to the one saying to the piece of wood: “O do awake!” to a dumb stone: “O wake up! It itself will give instruction”! Look! It is sheathed in gold and silver, and there is no breath^&#42;1^ at all in the midst of it.

[NOTE]
====
. “Breath.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus.
====

[[v35-2-20]]

^<<v35-2-20,20>>^ But Jehovah^&#42;1^ is in his holy temple.^&#42;2^ Keep silence before him, all the earth!’”

[NOTE]
====
. See App 1C §2.
. Or, “in the temple of his holiness.” Heb., beheh·khalʹ qodh·shohʹ; Gr., na·oiʹ ha·giʹoi. See Mt 23:16 ftn.
====

'''

xref:035-habakkuk/035-habakkuk-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habakkuk/035-habakkuk-003.adoc#v35-3-0[Próximo Capítulo &#62;]