include::./index.adoc[]

[[v35-3-0]]
=== Habakkuk, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v35-3-1]]

^<<v35-3-1,1>>^ The prayer of Ha·bakʹkuk the prophet in dirges:^&#42;1^

[NOTE]
====
. “Dirges.” Heb., shigh·yo·nohthʹ; LXX, “a song”; Vg, “(for) ignorant acts; (for) ignorances.” See Ps 7:Sup ftn, “Dirge.”
====

[[v35-3-2]]

^<<v35-3-2,2>>^ O Jehovah, I have heard the report about you. I have become afraid, O Jehovah, of your activity.
In the midst of &#91;the&#93; years O bring it to life! In the midst of &#91;the&#93; years may you make it known. During the agitation, to show mercy may you remember.

[[v35-3-3]]

^<<v35-3-3,3>>^ God^&#42;1^ himself proceeded to come from Teʹman,^&#42;2^ even a Holy One from Mount Paʹran. Seʹlah.^&#42;3^
His dignity covered &#91;the&#93; heavens; and with his praise the earth became filled.

[NOTE]
====
. “God.” Heb., ʼElohʹah, sing.; Gr., The·osʹ; Lat., Deʹus.
. “From Teman.” Heb., mit·Teh·manʹ; Gr., ek Thai·manʹ. Or, “from the south,” as in Vg; compare Ex 26:18, 35.
. “Selah.” Heb., seʹlah; Gr., di·aʹpsal·ma, “musical interlude.” The word occurs three times in this prayer of Habakkuk. See Ps 3:2 ftn, “Selah.”
====

[[v35-3-4]]

^<<v35-3-4,4>>^ As for &#91;his&#93;^&#42;1^ brightness, it got to be just like the light. He had two rays^&#42;2^ &#91;issuing&#93; out of his hand, and there the hiding of his strength was.

[NOTE]
====
. “His,” LXXSyVg; M omits.
. Lit., “horns.” Compare Ex 34:29, 30, 35.
====

[[v35-3-5]]

^<<v35-3-5,5>>^ Before him pestilence kept going, and burning fever would go forth at his feet.

[[v35-3-6]]

^<<v35-3-6,6>>^ He stood still, that he might shake up &#91;the&#93; earth. He saw, and then caused nations to leap.
And the eternal mountains got to be smashed; the indefinitely lasting hills bowed down. The walkings of long ago are his.

[[v35-3-7]]

^<<v35-3-7,7>>^ Under what is hurtful I saw the tents of Cuʹshan.^&#42;1^ The tent cloths of the land of Midʹi·an began to be agitated.

[NOTE]
====
. “Cushan,” MSy; LXX, “the Ethiopians”; Vg, “Ethiopia.”
====

[[v35-3-8]]

^<<v35-3-8,8>>^ Is it against the rivers, O Jehovah, is it against the rivers that your anger has become hot, or is your fury against the sea? For you went riding upon your horses; your chariots were salvation.

[[v35-3-9]]

^<<v35-3-9,9>>^ In &#91;its&#93; nakedness your bow comes to be uncovered. The sworn oaths of &#91;the&#93; tribes are the thing said.^&#42;1^ Seʹlah. With rivers you proceeded to split &#91;the&#93; earth.

[NOTE]
====
. “In [its] nakedness . . . the thing said,” M; LXXBagster, “Surely thou didst bend thy bow at sceptres, saith the Lord [LXXVTS 10a, “Jehovah”].” See App 1C §2.
====

[[v35-3-10]]

^<<v35-3-10,10>>^ Mountains saw you; they got to be in severe pains. A thunderstorm of waters passed through. The watery deep^&#42;1^ gave forth its sound. On high its hands it lifted up.

[NOTE]
====
. Or, “surging waters.” Heb., tehohmʹ; Syr., tehu·maʼ; LXXVg, “abyss.” See Ge 1:2 ftn, “Deep.”
====

[[v35-3-11]]

^<<v35-3-11,11>>^ Sun—moon—stood still, in the lofty abode thereof. Like light your own arrows kept going. The lightning of your spear served for brightness.

[[v35-3-12]]

^<<v35-3-12,12>>^ With denunciation you went marching &#91;through&#93; the earth. In anger you went threshing &#91;the&#93; nations.

[[v35-3-13]]

^<<v35-3-13,13>>^ And you went forth for the salvation of your people, to save your anointed one.^&#42;1^ You broke to pieces the head one out of the house of the wicked one. There was a laying of the foundation bare, clear up to the neck. Seʹlah.

[NOTE]
====
. “Your anointed one.” Heb., meshi·cheʹkha; LXXBagster(Gr.), khri·stonʹ; Lat., chriʹsto.
====

[[v35-3-14]]

^<<v35-3-14,14>>^ With his own rods you pierced &#91;the&#93; head of his warriors &#91;when&#93; they moved tempestuously to scatter me. Their high glee was as of those bent on devouring an afflicted one in a place of concealment.

[[v35-3-15]]

^<<v35-3-15,15>>^ Through the sea you trod &#91;with&#93; your horses, &#91;through&#93; the heap of vast waters.

[[v35-3-16]]

^<<v35-3-16,16>>^ I heard, and my belly began to be agitated; at the sound my lips quivered; rottenness began to enter into my bones; and in my situation I was agitated, that I should quietly wait for^&#42;1^ the day of distress, for &#91;his&#93; coming up to the people, &#91;that&#93; he may raid them.

[NOTE]
====
. “I should wail (lament) before,” KB, p. 602.
====

[[v35-3-17]]

^<<v35-3-17,17>>^ Although &#91;the&#93; fig tree itself may not blossom, and there may be no yield on the vines; the work of &#91;the&#93; olive tree may actually turn out a failure, and the terraces themselves may actually produce no food; &#91;the&#93; flock may actually be severed from &#91;the&#93; pen, and there may be no herd in the enclosures;

[[v35-3-18]]

^<<v35-3-18,18>>^ Yet, as for me, I will exult in Jehovah himself; I will be joyful in the God^&#42;1^ of my salvation.

[NOTE]
====
. “In the God of.” Heb., bEʼ·lo·hehʹ.
====

[[v35-3-19]]

^<<v35-3-19,19>>^ Jehovah the Sovereign Lord is my vital energy; and he will make my feet like those of the hinds, and upon my high places he will cause me to tread.

_To the director on my stringed instruments._

'''

xref:035-habakkuk/035-habakkuk-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-zephaniah/036-zephaniah-001.adoc#v36-1-0[Próximo Capítulo &#62;]