include::./index.adoc[]

[[v45-16-0]]
=== To the Romans, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-16-1]]

^<<v45-16-1,1>>^ I recommend^&#42;1^ to YOU Phoeʹbe our sister, who is a minister^&#42;2^ of the congregation that is in Cenʹchre·ae,

[NOTE]
====
. Or, “introduce.”
. Or, “a servant.” Gr., di·aʹko·non; Lat., in mi·ni·steʹri·o; J18(Heb.), mesha·rathʹ, “a female attendant.”
====

[[v45-16-2]]

^<<v45-16-2,2>>^ that YOU may welcome her in &#91;the&#93; Lord in a way worthy of the holy ones, and that YOU may assist her in any matter where she may need YOU, for she herself also proved to be a defender of many, yes, of me myself.

[[v45-16-3]]

^<<v45-16-3,3>>^ Give my greetings to Prisʹca and Aqʹui·la my fellow workers in Christ Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ who have risked their own necks for my soul,^&#42;1^ to whom not only I but also all the congregations of the nations render thanks;

[NOTE]
====
. Or, “life.”
====

[[v45-16-5]]

^<<v45-16-5,5>>^ and &#91;greet&#93; the congregation that is in their house. Greet my beloved E·paeʹne·tus, who is a firstfruits of Asia for Christ.

[[v45-16-6]]

^<<v45-16-6,6>>^ Greet Mary, who has performed many labors for YOU.

[[v45-16-7]]

^<<v45-16-7,7>>^ Greet An·dronʹi·cus and Juʹni·as my relatives and my fellow captives,^&#42;1^ who are men of note among the apostles and who have been in union with Christ longer than I have.

[NOTE]
====
. Or, “fellow prisoners.”
====

[[v45-16-8]]

^<<v45-16-8,8>>^ Give my greetings to Am·pli·aʹtus my beloved in &#91;the&#93; Lord.

[[v45-16-9]]

^<<v45-16-9,9>>^ Greet Ur·baʹnus our fellow worker in Christ, and my beloved Staʹchys.

[[v45-16-10]]

^<<v45-16-10,10>>^ Greet A·pelʹles, the approved one in Christ. Greet those from the household of A·ris·tobʹu·lus.

[[v45-16-11]]

^<<v45-16-11,11>>^ Greet He·roʹdi·on my relative. Greet those from the household of Nar·cisʹsus who are in &#91;the&#93; Lord.

[[v45-16-12]]

^<<v45-16-12,12>>^ Greet Try·phaeʹna and Try·phoʹsa, &#91;women&#93; who are working hard in &#91;the&#93; Lord. Greet Perʹsis our beloved one, for she performed many labors in &#91;the&#93; Lord.

[[v45-16-13]]

^<<v45-16-13,13>>^ Greet Ruʹfus the chosen one in &#91;the&#93; Lord, and his mother and mine.

[[v45-16-14]]

^<<v45-16-14,14>>^ Greet A·synʹcri·tus, Phleʹgon, Herʹmes, Patʹro·bas, Herʹmas, and the brothers with them.

[[v45-16-15]]

^<<v45-16-15,15>>^ Greet Phi·lolʹo·gus and Julia, Neʹreus and his sister, and O·lymʹpas, and all the holy ones with them.

[[v45-16-16]]

^<<v45-16-16,16>>^ Greet one another with a holy kiss. All the congregations of the Christ greet YOU.

[[v45-16-17]]

^<<v45-16-17,17>>^ Now I exhort YOU, brothers, to keep your eye on those who cause divisions and occasions for stumbling contrary to the teaching that YOU have learned, and avoid them.

[[v45-16-18]]

^<<v45-16-18,18>>^ For men of that sort are slaves, not of our Lord Christ, but of their own bellies; and by smooth talk and complimentary speech they seduce the hearts of guileless ones.

[[v45-16-19]]

^<<v45-16-19,19>>^ For YOUR obedience has come to the notice of all. I therefore rejoice over YOU. But I want YOU to be wise as to what is good, but innocent as to what is evil.

[[v45-16-20]]

^<<v45-16-20,20>>^ For his part, the God who gives peace will crush Satan under YOUR feet shortly. May the undeserved kindness of our Lord Jesus be with YOU.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timothy my fellow worker greets YOU, and so do Lucius and Jaʹson and So·sipʹa·ter my relatives.

[[v45-16-22]]

^<<v45-16-22,22>>^ I, Terʹtius, who have done the writing of this letter, greet YOU in &#91;the&#93; Lord.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaʹius, my host and that of all the congregation, greets YOU. E·rasʹtus the city steward greets YOU, and so does Quarʹtus his^&#42;1^ brother.

[NOTE]
====
. Or, “our.”
====

[[v45-16-24]]

^<<v45-16-24,24>>^ ^&#42;1^ ——

[NOTE]
====
. P46אABC omit; DItVgc, “May the undeserved kindness of our Lord Jesus Christ be with all of you. Amen,” which corresponds to the end of vs 20.
====

[[v45-16-25]]

^<<v45-16-25,25>>^ Now to him who can make YOU firm in accord with the good news I declare and^&#42;1^ the preaching of Jesus Christ, according to the revelation^&#42;2^ of the sacred secret which has been kept in silence for long-lasting times

[NOTE]
====
. Or, “even.”
. Lit., “uncovering; disclosure.” Gr., a·po·kaʹly·psin; Lat., re·ve·la·ti·oʹnem.
====

[[v45-16-26]]

^<<v45-16-26,26>>^ but has now been made manifest and has been made known through the prophetic scriptures among all the nations in accord with the command of the everlasting God to promote obedience by faith;

[[v45-16-27]]

^<<v45-16-27,27>>^ to God, wise alone, be the glory through Jesus Christ forever.^&#42;1^ Amen.

[NOTE]
====
. “Forever,” P46BC; אADItVgArm, “forever and ever.”
====

'''

xref:045-romans/045-romans-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-001.adoc#v46-1-0[Próximo Capítulo &#62;]