include::./index.adoc[]

[[v45-1-0]]
=== To the Romans, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-1-1]]

^<<v45-1-1,1>>^ Paul, a slave of Jesus Christ and called to be an apostle, separated to God’s good news,

[[v45-1-2]]

^<<v45-1-2,2>>^ which he promised aforetime through his prophets in the holy Scriptures,

[[v45-1-3]]

^<<v45-1-3,3>>^ concerning his Son, who sprang from the seed^&#42;1^ of David according to the flesh,

[NOTE]
====
. Or, “offspring.”
====

[[v45-1-4]]

^<<v45-1-4,4>>^ but who with power was declared^&#42;1^ God’s Son according to the spirit of holiness by means of resurrection from the dead—yes, Jesus Christ our Lord,

[NOTE]
====
. Or, “determined to be.”
====

[[v45-1-5]]

^<<v45-1-5,5>>^ through whom we^&#42;1^ received undeserved kindness and an apostleship in order that there might be obedience of faith among all the nations respecting his name,

[NOTE]
====
. “We,” used editorially. Or, “I.”
====

[[v45-1-6]]

^<<v45-1-6,6>>^ among which &#91;nations&#93; YOU also are those called to belong to Jesus Christ—

[[v45-1-7]]

^<<v45-1-7,7>>^ to all those who are in Rome as God’s beloved ones, called to be holy ones:^&#42;1^
May YOU have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[NOTE]
====
. Or, “to be saints.”
====

[[v45-1-8]]

^<<v45-1-8,8>>^ First of all, I give thanks to my God through Jesus Christ concerning all of YOU, because YOUR faith is talked about throughout the whole world.

[[v45-1-9]]

^<<v45-1-9,9>>^ For God, to whom I render sacred service^&#42;1^ with my spirit in connection with the good news about his Son, is my witness of how without ceasing I always make mention of YOU in my prayers,

[NOTE]
====
. “I render sacred service.” Gr., la·treuʹo; J17,​18(Heb.), ʼaniʹ ʽo·vedhʹ, “I serve (worship).” See Ex 3:12 ftn.
====

[[v45-1-10]]

^<<v45-1-10,10>>^ begging that if at all possible I may now at last be prospered in the will of God so as to come to YOU.

[[v45-1-11]]

^<<v45-1-11,11>>^ For I am longing to see YOU, that I may impart some spiritual gift to YOU in order for YOU to be made firm;

[[v45-1-12]]

^<<v45-1-12,12>>^ or, rather, that there may be an interchange of encouragement^&#42;1^ among YOU, by each one through the other’s faith, both YOURS and mine.

[NOTE]
====
. Lit., “to be encouraged together.”
====

[[v45-1-13]]

^<<v45-1-13,13>>^ But I do not want YOU to fail to know, brothers, that I many times purposed to come to YOU, but I have been hindered until now, in order that I might acquire some fruitage also among YOU even as among the rest of the nations.

[[v45-1-14]]

^<<v45-1-14,14>>^ Both to Greeks and to Barbarians,^&#42;1^ both to wise and to senseless ones I am a debtor:

[NOTE]
====
. Or, “foreigners.”
====

[[v45-1-15]]

^<<v45-1-15,15>>^ so there is eagerness on my part to declare the good news also to YOU there in Rome.

[[v45-1-16]]

^<<v45-1-16,16>>^ For I am not ashamed of the good news; it is, in fact, God’s power for salvation to everyone having faith, to the Jew first^&#42;1^ and also to the Greek;

[NOTE]
====
. “First.” B omits.
====

[[v45-1-17]]

^<<v45-1-17,17>>^ for in it God’s righteousness is being revealed by reason of faith and toward faith, just as it is written: “But the righteous one—by means of faith he will live.”

[[v45-1-18]]

^<<v45-1-18,18>>^ For God’s wrath is being revealed from heaven against all ungodliness and unrighteousness of men who are suppressing the truth in an unrighteous way,

[[v45-1-19]]

^<<v45-1-19,19>>^ because what may be known about God is manifest among them, for God made it manifest to them.

[[v45-1-20]]

^<<v45-1-20,20>>^ For his invisible &#91;qualities&#93; are clearly seen from the world’s^&#42;1^ creation onward, because they are perceived by the things made, even his eternal power and Godship,^&#42;2^ so that they are inexcusable;

[NOTE]
====
. “World’s.” Gr., koʹsmou; Lat., munʹdi; J17,​22(Heb.), ha·ʽoh·lamʹ, “the world.”
. “Godship.” Gr., Thei·oʹtes, related to The·osʹ, “God”; Lat., Di·viʹni·tas. Compare Ac 17:29 ftn.
====

[[v45-1-21]]

^<<v45-1-21,21>>^ because, although they knew God, they did not glorify him as God nor did they thank him, but they became empty-headed in their reasonings and their unintelligent heart became darkened.

[[v45-1-22]]

^<<v45-1-22,22>>^ Although asserting they were wise, they became foolish

[[v45-1-23]]

^<<v45-1-23,23>>^ and turned the glory of the incorruptible God into something like the image of corruptible man and of birds and four-footed creatures and creeping things.

[[v45-1-24]]

^<<v45-1-24,24>>^ Therefore God, in keeping with the desires of their hearts, gave them up to uncleanness, that their bodies might be dishonored among them,

[[v45-1-25]]

^<<v45-1-25,25>>^ even those who exchanged the truth of God for the lie and venerated and rendered sacred service to the creation rather than the One who created, who is blessed forever. Amen.^&#42;1^

[NOTE]
====
. Or, “So be it.” Gr., a·menʹ; Lat., aʹmen; J17,​18,​22(Heb.), ʼa·menʹ. See Ne 5:13.
====

[[v45-1-26]]

^<<v45-1-26,26>>^ That is why God gave them up to disgraceful sexual appetites, for both their females changed the natural use of themselves into one contrary to nature;

[[v45-1-27]]

^<<v45-1-27,27>>^ and likewise even the males left the natural use of the female and became violently inflamed in their lust toward one another, males with males, working what is obscene^&#42;1^ and receiving in themselves the full recompense, which was due for their error.

[NOTE]
====
. “What is obscene.” Lit., “the indecency.”
====

[[v45-1-28]]

^<<v45-1-28,28>>^ And just as they did not approve of holding God in accurate knowledge, God gave them up to a disapproved mental state, to do the things not fitting,

[[v45-1-29]]

^<<v45-1-29,29>>^ filled as they were with all unrighteousness, wickedness, covetousness, badness, being full of envy, murder, strife, deceit, malicious disposition, being whisperers,

[[v45-1-30]]

^<<v45-1-30,30>>^ backbiters, haters of God, insolent, haughty, self-assuming, inventors of injurious things, disobedient to parents,

[[v45-1-31]]

^<<v45-1-31,31>>^ without understanding, false to agreements,^&#42;1^ having no natural affection, merciless.

[NOTE]
====
. Or, “opposed to any agreement.”
====

[[v45-1-32]]

^<<v45-1-32,32>>^ Although these know full well the righteous decree of God, that those practicing such things are deserving of death, they not only keep on doing them but also consent with those practicing them.

'''

xref:044-acts/044-acts-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romans/045-romans-002.adoc#v45-2-0[Próximo Capítulo &#62;]