include::./index.adoc[]

[[v45-10-0]]
=== To the Romans, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-10-1]]

^<<v45-10-1,1>>^ Brothers, the goodwill of my heart and my supplication to God for them are, indeed, for their salvation.

[[v45-10-2]]

^<<v45-10-2,2>>^ For I bear them witness^&#42;1^ that they have a zeal for God; but not according to accurate knowledge;

[NOTE]
====
. “I bear . . . witness.” Gr., mar·ty·roʹ; Lat., te·sti·moʹni·um . . . per·hiʹbe·o.
====

[[v45-10-3]]

^<<v45-10-3,3>>^ for, because of not knowing the righteousness of God but seeking to establish their own, they did not subject themselves to the righteousness of God.

[[v45-10-4]]

^<<v45-10-4,4>>^ For Christ is the end^&#42;1^ of the Law, so that everyone exercising faith may have righteousness.

[NOTE]
====
. Or, “the accomplished (completed) end.” Gr., teʹlos.
====

[[v45-10-5]]

^<<v45-10-5,5>>^ For Moses writes that the man that has done the righteousness of the Law will live by it.

[[v45-10-6]]

^<<v45-10-6,6>>^ But the righteousness resulting from faith speaks in this manner: “Do not say in your heart, ‘Who will ascend into heaven?’ that is, to bring Christ down;

[[v45-10-7]]

^<<v45-10-7,7>>^ or, ‘Who will descend into the abyss?’ that is, to bring Christ up from the dead.”

[[v45-10-8]]

^<<v45-10-8,8>>^ But what does it say? “The word is near you, in your own mouth and in your own heart”; that is, the “word” of faith, which we are preaching.^&#42;1^

[NOTE]
====
. Or, “we are heralding.” Gr., ke·rysʹso·men; Lat., prae·di·caʹmus. Compare Da 5:29 ftn, “Heralded.”
====

[[v45-10-9]]

^<<v45-10-9,9>>^ For if you publicly declare that ‘word in your own mouth,’ that Jesus is Lord,^&#42;1^ and exercise faith in your heart that God raised him up from the dead, you will be saved.

[NOTE]
====
. Gr., kyʹri·os; J12-14,​16-18,​22(Heb.), ha·ʼa·dhohnʹ, “the Lord.” Not “Jehovah.”
====

[[v45-10-10]]

^<<v45-10-10,10>>^ For with the heart one exercises faith for righteousness, but with the mouth one makes public declaration for salvation.

[[v45-10-11]]

^<<v45-10-11,11>>^ For the Scripture says: “None that rests his faith on him will be disappointed.”^&#42;1^

[NOTE]
====
. Or, “ashamed.”
====

[[v45-10-12]]

^<<v45-10-12,12>>^ For there is no distinction between Jew and Greek, for there is the same Lord over all, who is rich to all those calling upon him.

[[v45-10-13]]

^<<v45-10-13,13>>^ For “everyone who calls on the name of Jehovah^&#42;1^ will be saved.”

[NOTE]
====
. See App 1D.
====

[[v45-10-14]]

^<<v45-10-14,14>>^ However, how will they call on him in whom they have not put faith? How, in turn, will they put faith in him of whom they have not heard? How, in turn, will they hear without someone to preach?

[[v45-10-15]]

^<<v45-10-15,15>>^ How, in turn, will they preach unless they have been sent forth? Just as it is written: “How comely are the feet of those who declare good news of good things!”

[[v45-10-16]]

^<<v45-10-16,16>>^ Nevertheless, they did not all obey the good news. For Isaiah says: “Jehovah,^&#42;1^ who put faith in the thing heard from us?”

[NOTE]
====
. See App 1D.
====

[[v45-10-17]]

^<<v45-10-17,17>>^ So faith follows the thing heard. In turn the thing heard is through the word about Christ.^&#42;1^

[NOTE]
====
. “Word about Christ,” P46א*BCD*Vg; אcASyp, “word of God”; J7,​8,​10, “word of Jehovah.”
====

[[v45-10-18]]

^<<v45-10-18,18>>^ Nevertheless I ask, They did not fail to hear, did they? Why, in fact, “into all the earth their sound went out, and to the extremities^&#42;1^ of the inhabited earth^&#42;2^ their utterances.”

[NOTE]
====
. See Mt 12:42 ftn.
. “Inhabited earth.” Lit., “inhabited.” Gr., oi·kou·meʹnes, fem. sing., implying the earth.
====

[[v45-10-19]]

^<<v45-10-19,19>>^ Nevertheless I ask, Israel did not fail to know, did they? First Moses says: “I will incite YOU people to jealousy through that which is not a nation; I will incite YOU to violent anger through a stupid nation.”

[[v45-10-20]]

^<<v45-10-20,20>>^ But Isaiah becomes very bold and says: “I was found by those who were not seeking me; I became manifest to those who were not asking for me.”

[[v45-10-21]]

^<<v45-10-21,21>>^ But as respects Israel he says: “All day long I have spread out my hands toward a people that is disobedient and talks back.”

'''

xref:045-romans/045-romans-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romans/045-romans-011.adoc#v45-11-0[Próximo Capítulo &#62;]