include::./index.adoc[]

[[v45-7-0]]
=== To the Romans, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-7-1]]

^<<v45-7-1,1>>^ Can it be that YOU do not know, brothers, (for I am speaking to those who know law,) that the Law is master over a man as long as he lives?

[[v45-7-2]]

^<<v45-7-2,2>>^ For instance, a married woman^&#42;1^ is bound by law to her husband while he is alive; but if her husband dies, she is discharged from the law of her husband.

[NOTE]
====
. Or, “woman subject to a husband.”
====

[[v45-7-3]]

^<<v45-7-3,3>>^ So, then, while her husband is living, she would be styled an adulteress^&#42;1^ if she became another man’s. But if her husband dies, she is free from his law, so that she is not an adulteress if she becomes another man’s.

[NOTE]
====
. “Adulteress.” Lat., a·dulʹte·ra.
====

[[v45-7-4]]

^<<v45-7-4,4>>^ So, my brothers, YOU also were made dead to the Law through the body of the Christ, that YOU might become another’s, the one’s who was raised up from the dead, that we should bear fruit to God.

[[v45-7-5]]

^<<v45-7-5,5>>^ For when we were in accord with the flesh, the sinful passions that were excited by the Law were at work in our members that we should bring forth fruit to death.

[[v45-7-6]]

^<<v45-7-6,6>>^ But now we have been discharged from the Law, because we have died to that by which we were being held fast, that we might be slaves^&#42;1^ in a new sense by the spirit, and not in the old sense by the written code.

[NOTE]
====
. “Be slaves,” אAB; J18, “be servants to Jehovah.”
====

[[v45-7-7]]

^<<v45-7-7,7>>^ What, then, shall we say? Is the Law sin? Never may that become so! Really I would not have come to know sin if it had not been for the Law; and, for example, I would not have known covetousness if the Law had not said: “You must^&#42;1^ not covet.”

[NOTE]
====
. Or, “shall.”
====

[[v45-7-8]]

^<<v45-7-8,8>>^ But sin, receiving an inducement through the commandment, worked out in me covetousness of every sort, for apart from law sin was dead.

[[v45-7-9]]

^<<v45-7-9,9>>^ In fact, I was once alive apart from law; but when the commandment arrived, sin came to life again, but I died.

[[v45-7-10]]

^<<v45-7-10,10>>^ And the commandment which was to life, this I found to be to death.

[[v45-7-11]]

^<<v45-7-11,11>>^ For sin, receiving an inducement through the commandment, seduced me and killed me through it.

[[v45-7-12]]

^<<v45-7-12,12>>^ Wherefore, on its part, the Law is holy, and the commandment is holy and righteous and good.

[[v45-7-13]]

^<<v45-7-13,13>>^ Did, then, what is good become death to me? Never may that happen! But sin did, that it might be shown as sin working out death for me through that which is good; that sin might become far more sinful through the commandment.

[[v45-7-14]]

^<<v45-7-14,14>>^ For we know that the Law is spiritual; but I am fleshly, sold under sin.

[[v45-7-15]]

^<<v45-7-15,15>>^ For what I am working out I do not know. For what I wish,^&#42;1^ this I do not practice; but what I hate is what I do.

[NOTE]
====
. Or, “will.”
====

[[v45-7-16]]

^<<v45-7-16,16>>^ However, if what I do not wish is what I do, I agree that the Law is fine.

[[v45-7-17]]

^<<v45-7-17,17>>^ But now the one working it out is no longer I, but sin that resides in me.

[[v45-7-18]]

^<<v45-7-18,18>>^ For I know that in me, that is, in my flesh, there dwells nothing good; for ability to wish is present with me, but ability to work out what is fine is not &#91;present&#93;.

[[v45-7-19]]

^<<v45-7-19,19>>^ For the good that I wish I do not do, but the bad that I do not wish is what I practice.

[[v45-7-20]]

^<<v45-7-20,20>>^ If, now, what I do not wish is what I do, the one working it out is no longer I, but the sin dwelling in me.

[[v45-7-21]]

^<<v45-7-21,21>>^ I find, then, this law in my case: that when I wish to do what is right, what is bad is present with me.

[[v45-7-22]]

^<<v45-7-22,22>>^ I really delight in the law of God according to the man I am within,

[[v45-7-23]]

^<<v45-7-23,23>>^ but I behold in my members another law warring against the law of my mind and leading me captive to sin’s law that is in my members.

[[v45-7-24]]

^<<v45-7-24,24>>^ Miserable^&#42;1^ man that I am! Who will rescue me from the body undergoing this death?

[NOTE]
====
. Lit., “Callus-bearing.”
====

[[v45-7-25]]

^<<v45-7-25,25>>^ Thanks to God through Jesus Christ our Lord! So, then, with &#91;my&#93; mind I myself am a slave to God’s law, but with &#91;my&#93; flesh to sin’s law.

'''

xref:045-romans/045-romans-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romans/045-romans-008.adoc#v45-8-0[Próximo Capítulo &#62;]