include::./index.adoc[]

[[v45-11-0]]
=== To the Romans, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-11-1]]

^<<v45-11-1,1>>^ I ask, then, God did not reject his people, did he? Never may that happen! For I also am an Israelite, of the seed of Abraham, of the tribe of Benjamin.

[[v45-11-2]]

^<<v45-11-2,2>>^ God did not reject his people, whom he first recognized.^&#42;1^ Why, do YOU not know what the Scripture says in connection with E·liʹjah, as he pleads with God against Israel?

[NOTE]
====
. Or, “he foreknew.”
====

[[v45-11-3]]

^<<v45-11-3,3>>^ “Jehovah,^&#42;1^ they have killed your prophets, they have dug up your altars, and I alone am left, and they are looking for my soul.”^&#42;2^

[NOTE]
====
. See App 1D.
. Or, “life.” See App 4A.
====

[[v45-11-4]]

^<<v45-11-4,4>>^ Yet, what does the divine pronouncement say to him? “I have left seven thousand men over for myself, &#91;men&#93; who have not bent the knee to Baʹal.”

[[v45-11-5]]

^<<v45-11-5,5>>^ In this way, therefore, at the present season also a remnant has turned up according to a choosing due to undeserved kindness.

[[v45-11-6]]

^<<v45-11-6,6>>^ Now if it is by undeserved kindness, it is no longer due to works; otherwise, the undeserved kindness no longer proves to be undeserved kindness.

[[v45-11-7]]

^<<v45-11-7,7>>^ What, then? The very thing Israel is earnestly seeking he did not obtain, but the ones chosen^&#42;1^ obtained it. The rest had their sensibilities blunted;

[NOTE]
====
. “The ones chosen.” Lit., “the choosing; the election.”
====

[[v45-11-8]]

^<<v45-11-8,8>>^ just as it is written: “God^&#42;1^ has given them a spirit of deep sleep, eyes so as not to see and ears so as not to hear, down to this very day.”

[NOTE]
====
. “God,” אABVgSyp; J7,​8,​10,​13-15,​20, “Jehovah.”
====

[[v45-11-9]]

^<<v45-11-9,9>>^ Also, David says: “Let their table^&#42;1^ become for them a snare and a trap and a stumbling block and a retribution;

[NOTE]
====
. Or, “feast.”
====

[[v45-11-10]]

^<<v45-11-10,10>>^ let their eyes become darkened so as not to see, and always bow down their back.”

[[v45-11-11]]

^<<v45-11-11,11>>^ Therefore I ask, Did they stumble so that they fell completely? Never may that happen! But by their false step there is salvation to people of the nations, to incite them to jealousy.

[[v45-11-12]]

^<<v45-11-12,12>>^ Now if their false step means riches to the world, and their decrease means riches to people of the nations, how much more will the full number^&#42;1^ of them mean it!

[NOTE]
====
. Or, “the fullness.”
====

[[v45-11-13]]

^<<v45-11-13,13>>^ Now I speak to YOU who are people of the nations. Forasmuch as I am, in reality, an apostle to the nations, I glorify my ministry,

[[v45-11-14]]

^<<v45-11-14,14>>^ if I may by any means incite &#91;those who are&#93; my own flesh to jealousy and save some from among them.

[[v45-11-15]]

^<<v45-11-15,15>>^ For if the casting of them away means reconciliation for the world, what will the receiving of them mean but life from the dead?

[[v45-11-16]]

^<<v45-11-16,16>>^ Further, if the &#91;part taken as&#93; firstfruits is holy, the lump is also; and if the root is holy, the branches are also.

[[v45-11-17]]

^<<v45-11-17,17>>^ However, if some of the branches were broken off but you, although being a wild olive, were grafted in among them and became a sharer of the olive’s root of fatness,

[[v45-11-18]]

^<<v45-11-18,18>>^ do not be exulting over the branches. If, though, you are exulting over them, it is not you that bear the root, but the root &#91;bears&#93; you.

[[v45-11-19]]

^<<v45-11-19,19>>^ You will say, then: “Branches were broken off that I might be grafted in.”

[[v45-11-20]]

^<<v45-11-20,20>>^ All right! For &#91;their&#93; lack of faith they were broken off, but you are standing by faith. Quit having lofty ideas, but be in fear.

[[v45-11-21]]

^<<v45-11-21,21>>^ For if God did not spare the natural branches, neither will he spare you.

[[v45-11-22]]

^<<v45-11-22,22>>^ See, therefore, God’s kindness and severity. Toward those who fell there is severity, but toward you there is God’s kindness, provided you remain in his kindness; otherwise, you also will be lopped off.

[[v45-11-23]]

^<<v45-11-23,23>>^ They also, if they do not remain in their lack of faith, will be grafted in; for God is able to graft them in again.

[[v45-11-24]]

^<<v45-11-24,24>>^ For if you were cut out of the olive tree that is wild by nature and were grafted contrary to nature into the garden olive tree, how much rather will these who are natural be grafted into their own olive tree!

[[v45-11-25]]

^<<v45-11-25,25>>^ For I do not want YOU, brothers, to be ignorant of this sacred secret, in order for YOU not to be discreet in your own eyes: that a dulling of sensibilities has happened in part to Israel until the full number^&#42;1^ of people of the nations has come in,

[NOTE]
====
. Or, “the fullness.”
====

[[v45-11-26]]

^<<v45-11-26,26>>^ and in this manner all Israel will be saved. Just as it is written: “The deliverer will come out of Zion and turn away ungodly practices from Jacob.

[[v45-11-27]]

^<<v45-11-27,27>>^ And this is the covenant on my part with them, when I take their sins away.”

[[v45-11-28]]

^<<v45-11-28,28>>^ True, with reference to the good news they are enemies for YOUR sakes, but with reference to &#91;God’s&#93; choosing^&#42;1^ they are beloved for the sake of their forefathers.

[NOTE]
====
. “[God’s] choosing.” Or, “the choosing; the ones chosen.”
====

[[v45-11-29]]

^<<v45-11-29,29>>^ For the gifts and the calling of God are not things he will regret.

[[v45-11-30]]

^<<v45-11-30,30>>^ For just as YOU were once disobedient to God but have now been shown mercy because of their disobedience,

[[v45-11-31]]

^<<v45-11-31,31>>^ so also these now have been disobedient with mercy resulting to YOU, that they themselves also may now be shown mercy.

[[v45-11-32]]

^<<v45-11-32,32>>^ For God has shut them all up together in disobedience, that he might show all of them mercy.

[[v45-11-33]]

^<<v45-11-33,33>>^ O the depth of God’s riches and wisdom and knowledge! How unsearchable his judgments &#91;are&#93; and past tracing out his ways &#91;are&#93;!

[[v45-11-34]]

^<<v45-11-34,34>>^ For “who has come to know Jehovah’s^&#42;1^ mind, or who has become his counselor?”

[NOTE]
====
. See App 1D.
====

[[v45-11-35]]

^<<v45-11-35,35>>^ Or, “Who has first given to him, so that it must be repaid to him?”

[[v45-11-36]]

^<<v45-11-36,36>>^ Because from him and by him and for him are all things. To him be the glory forever. Amen.

'''

xref:045-romans/045-romans-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romans/045-romans-012.adoc#v45-12-0[Próximo Capítulo &#62;]