include::./index.adoc[]

[[v45-6-0]]
=== To the Romans, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-6-1]]

^<<v45-6-1,1>>^ Consequently, what shall we say? Shall we continue in sin, that undeserved kindness may abound?

[[v45-6-2]]

^<<v45-6-2,2>>^ Never may that happen! Seeing that we died with reference to sin, how shall we keep on living any longer in it?

[[v45-6-3]]

^<<v45-6-3,3>>^ Or do YOU not know that all of us who were baptized into Christ Jesus^&#42;1^ were baptized into his death?

[NOTE]
====
. “Jesus.” B omits.
====

[[v45-6-4]]

^<<v45-6-4,4>>^ Therefore we were buried with him through our baptism into his death, in order that, just as Christ was raised up from the dead through the glory of the Father, we also should likewise walk in a newness of life.

[[v45-6-5]]

^<<v45-6-5,5>>^ For if we have become united with him^&#42;1^ in the likeness of his death, we shall certainly also be &#91;united with him in the likeness&#93; of his resurrection;

[NOTE]
====
. Or, “grown together with him.”
====

[[v45-6-6]]

^<<v45-6-6,6>>^ because we know that our old personality^&#42;1^ was impaled with &#91;him&#93;, that our sinful body^&#42;2^ might be made inactive, that we should no longer go on being slaves to sin.

[NOTE]
====
. Lit., “man.”
. Or, “our body belonging to sin.”
====

[[v45-6-7]]

^<<v45-6-7,7>>^ For he who has died has been acquitted^&#42;1^ from &#91;his&#93; sin.

[NOTE]
====
. Lit., “has been justified.” Gr., de·di·kaiʹo·tai.
====

[[v45-6-8]]

^<<v45-6-8,8>>^ Moreover, if we have died with Christ, we believe that we shall also live with him.

[[v45-6-9]]

^<<v45-6-9,9>>^ For we know that Christ, now that he has been raised up from the dead, dies no more; death is master over him no more.

[[v45-6-10]]

^<<v45-6-10,10>>^ For &#91;the death&#93; that he died, he died with reference to sin once for all time; but &#91;the life&#93; that he lives, he lives with reference to God.

[[v45-6-11]]

^<<v45-6-11,11>>^ Likewise also YOU: reckon yourselves to be dead indeed with reference to sin but living with reference to God by Christ Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Therefore do not let sin continue to rule as king in YOUR mortal bodies that YOU should obey their desires.

[[v45-6-13]]

^<<v45-6-13,13>>^ Neither go on presenting YOUR members to sin as weapons of unrighteousness, but present yourselves to God as those alive from the dead, also YOUR members to God as weapons of righteousness.

[[v45-6-14]]

^<<v45-6-14,14>>^ For sin must^&#42;1^ not be master over YOU, seeing that YOU are not under law but under undeserved kindness.

[NOTE]
====
. Or, “shall.”
====

[[v45-6-15]]

^<<v45-6-15,15>>^ What follows? Shall we commit a sin because we are not under law but under undeserved kindness? Never may that happen!

[[v45-6-16]]

^<<v45-6-16,16>>^ Do YOU not know that if YOU keep presenting yourselves to anyone as slaves to obey him, YOU are slaves of him because YOU obey him, either of sin with death in view or of obedience with righteousness in view?

[[v45-6-17]]

^<<v45-6-17,17>>^ But thanks to God that YOU were the slaves of sin but YOU became obedient from the heart to that form of teaching to which YOU were handed over.

[[v45-6-18]]

^<<v45-6-18,18>>^ Yes, since YOU were set free from sin, YOU became slaves to righteousness.

[[v45-6-19]]

^<<v45-6-19,19>>^ I am speaking in human terms because of the weakness of YOUR flesh: for even as YOU presented YOUR members as slaves to uncleanness and lawlessness with lawlessness in view,^&#42;1^ so now present YOUR members as slaves to righteousness with holiness in view.

[NOTE]
====
. “With lawlessness in view.” B omits.
====

[[v45-6-20]]

^<<v45-6-20,20>>^ For when YOU were slaves of sin, YOU were free as to righteousness.

[[v45-6-21]]

^<<v45-6-21,21>>^ What, then, was the fruit that YOU used to have at that time? Things^&#42;1^ of which YOU are now ashamed. For the end^&#42;2^ of those things is death.

[NOTE]
====
. Or, “used to have at that time from the things.”
. Or, “finish.” Gr., teʹlos.
====

[[v45-6-22]]

^<<v45-6-22,22>>^ However, now, because YOU were set free from sin but became slaves to God, YOU are having YOUR fruit in the way of holiness, and the end everlasting life.

[[v45-6-23]]

^<<v45-6-23,23>>^ For the wages^&#42;1^ sin pays is death, but the gift^&#42;2^ God gives is everlasting life by Christ Jesus our Lord.

[NOTE]
====
. “Wages.” Lat., sti·penʹdi·a.
. Lit., “gracious gift.” Gr., khaʹri·sma; Lat., graʹti·a.
====

'''

xref:045-romans/045-romans-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romans/045-romans-007.adoc#v45-7-0[Próximo Capítulo &#62;]