include::./index.adoc[]

[[v45-12-0]]
=== To the Romans, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-12-1]]

^<<v45-12-1,1>>^ Consequently I entreat YOU by the compassions of God, brothers, to present YOUR bodies a sacrifice living, holy, acceptable to God, a sacred service^&#42;1^ with YOUR power of reason.

[NOTE]
====
. “A sacred service.” Gr., la·treiʹan; J17(Heb.), ʽavoh·dhath·khemʹ, “your service (worship).” See Ex 12:25 ftn.
====

[[v45-12-2]]

^<<v45-12-2,2>>^ And quit being fashioned after this system of things,^&#42;1^ but be transformed by making YOUR mind over, that YOU may prove to yourselves the good and acceptable and perfect will of God.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹni; Lat., saeʹcu·lo.
====

[[v45-12-3]]

^<<v45-12-3,3>>^ For through the undeserved kindness given to me I tell everyone there among YOU not to think more of himself than it is necessary to think; but to think so as to have a sound mind, each one as God has distributed to him a measure of faith.

[[v45-12-4]]

^<<v45-12-4,4>>^ For just as we have in one body many members, but the members do not all have the same function,

[[v45-12-5]]

^<<v45-12-5,5>>^ so we, although many, are one body in union with Christ, but members belonging individually to one another.

[[v45-12-6]]

^<<v45-12-6,6>>^ Since, then, we have gifts differing according to the undeserved kindness given to us, whether prophecy, &#91;let us prophesy&#93; according to the faith proportioned &#91;to us&#93;;

[[v45-12-7]]

^<<v45-12-7,7>>^ or a ministry, &#91;let us be&#93; at this ministry; or he that teaches, &#91;let him be&#93; at his teaching;

[[v45-12-8]]

^<<v45-12-8,8>>^ or he that exhorts, &#91;let him be&#93; at his exhortation; he that distributes, &#91;let him do it&#93; with liberality; he that presides,^&#42;1^ &#91;let him do it&#93; in real earnest; he that shows mercy, &#91;let him do it&#93; with cheerfulness.

[NOTE]
====
. Or, “that acts as leader.”
====

[[v45-12-9]]

^<<v45-12-9,9>>^ Let &#91;YOUR&#93; love be without hypocrisy. Abhor what is wicked, cling to what is good.

[[v45-12-10]]

^<<v45-12-10,10>>^ In brotherly love have tender affection for one another. In showing honor to one another take the lead.

[[v45-12-11]]

^<<v45-12-11,11>>^ Do not loiter at YOUR business. Be aglow with the spirit. Slave for Jehovah.^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v45-12-12]]

^<<v45-12-12,12>>^ Rejoice in the hope. Endure under tribulation. Persevere in prayer.

[[v45-12-13]]

^<<v45-12-13,13>>^ Share with the holy ones according to their needs. Follow the course of hospitality.

[[v45-12-14]]

^<<v45-12-14,14>>^ Keep on blessing those who persecute; be blessing and do not be cursing.

[[v45-12-15]]

^<<v45-12-15,15>>^ Rejoice with people who rejoice; weep with people who weep.

[[v45-12-16]]

^<<v45-12-16,16>>^ Be minded the same way toward others as to yourselves; do not be minding lofty things, but be led along with the lowly things. Do not become discreet in YOUR own eyes.

[[v45-12-17]]

^<<v45-12-17,17>>^ Return evil for evil to no one. Provide fine things in the sight of all men.

[[v45-12-18]]

^<<v45-12-18,18>>^ If possible, as far as it depends upon YOU, be peaceable with all men.

[[v45-12-19]]

^<<v45-12-19,19>>^ Do not avenge yourselves, beloved, but yield place to the wrath; for it is written: “Vengeance is mine; I will repay, says Jehovah.”^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v45-12-20]]

^<<v45-12-20,20>>^ But, “if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by doing this you will heap fiery coals upon his head.”

[[v45-12-21]]

^<<v45-12-21,21>>^ Do not let yourself be conquered by the evil, but keep conquering the evil with the good.

'''

xref:045-romans/045-romans-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romans/045-romans-013.adoc#v45-13-0[Próximo Capítulo &#62;]