include::./index.adoc[]

[[v45-9-0]]
=== To the Romans, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-9-1]]

^<<v45-9-1,1>>^ I am telling the truth in Christ; I am not lying, since my conscience bears witness with me in holy spirit,

[[v45-9-2]]

^<<v45-9-2,2>>^ that I have great grief and unceasing pain in my heart.

[[v45-9-3]]

^<<v45-9-3,3>>^ For I could wish that I myself were separated as the cursed one^&#42;1^ from the Christ in behalf of my brothers, my relatives according to the flesh,

[NOTE]
====
. Lit., “anathema.” Gr. and Lat., a·naʹthe·ma.
====

[[v45-9-4]]

^<<v45-9-4,4>>^ who, as such, are Israelites, to whom belong the adoption as sons and the glory and the covenants and the giving of the Law and the sacred service^&#42;1^ and the promises;

[NOTE]
====
. “Sacred service.” Gr., la·treiʹa; J17(Heb.), weha·ʽavoh·dhahʹ, “and the service (worship).” See Ex 12:25 ftn.
====

[[v45-9-5]]

^<<v45-9-5,5>>^ to whom the forefathers belong and from whom the Christ &#91;sprang&#93; according to the flesh: God, who is over all,^&#42;1^ &#91;be&#93; blessed forever. Amen.

[NOTE]
====
. For a discussion of “God, who is over all” see App 6D.
====

[[v45-9-6]]

^<<v45-9-6,6>>^ However, it is not as though the word of God had failed. For not all who &#91;spring&#93; from Israel are really “Israel.”

[[v45-9-7]]

^<<v45-9-7,7>>^ Neither because they are Abraham’s seed are they all children, but: “What will be called ‘your seed’ will be through Isaac.”

[[v45-9-8]]

^<<v45-9-8,8>>^ That is, the children in the flesh are not really the children of God, but the children by the promise are counted as the seed.

[[v45-9-9]]

^<<v45-9-9,9>>^ For the word of promise was as follows: “At this time I will come and Sarah will have a son.”

[[v45-9-10]]

^<<v45-9-10,10>>^ Yet not that case alone, but also when Re·bekʹah conceived twins from the one &#91;man&#93;, Isaac our forefather:

[[v45-9-11]]

^<<v45-9-11,11>>^ for when they had not yet been born nor had practiced anything good or vile, in order that the purpose of God respecting the choosing might continue dependent, not upon works, but upon the One who calls,

[[v45-9-12]]

^<<v45-9-12,12>>^ it was said to her: “The older will be the slave of the younger.”

[[v45-9-13]]

^<<v45-9-13,13>>^ Just as it is written: “I loved Jacob, but Eʹsau I hated.”

[[v45-9-14]]

^<<v45-9-14,14>>^ What shall we say, then? Is there injustice with God? Never may that become so!

[[v45-9-15]]

^<<v45-9-15,15>>^ For he says to Moses: “I will have mercy upon whomever I do have mercy, and I will show compassion to whomever I do show compassion.”

[[v45-9-16]]

^<<v45-9-16,16>>^ So, then, it depends, not upon the one wishing nor upon the one running, but upon God, who has mercy.

[[v45-9-17]]

^<<v45-9-17,17>>^ For the Scripture says to Pharʹaoh: “For this very cause I have let you remain,^&#42;1^ that in connection with you I may show my power, and that my name may be declared in all the earth.”

[NOTE]
====
. “I have let you remain,” J17,​18,​22; אAB, “I have raised you up”; Ex 9:16 in LXX, which Paul here quotes, “you have been preserved.”
====

[[v45-9-18]]

^<<v45-9-18,18>>^ So, then, upon whom he wishes he has mercy, but whom he wishes he lets become obstinate.

[[v45-9-19]]

^<<v45-9-19,19>>^ You will therefore say to me: “Why does he yet find fault? For who has withstood his express will?”

[[v45-9-20]]

^<<v45-9-20,20>>^ O man, who, then, really are you to be answering back to God? Shall the thing molded say to him that molded it, “Why did you make me this way?”

[[v45-9-21]]

^<<v45-9-21,21>>^ What? Does not the potter have authority over the clay to make from the same lump one vessel for an honorable use, another for a dishonorable use?

[[v45-9-22]]

^<<v45-9-22,22>>^ If, now, God, although having the will to demonstrate his wrath and to make his power known, tolerated with much long-suffering vessels of wrath made fit for destruction,

[[v45-9-23]]

^<<v45-9-23,23>>^ in order that he might make known the riches of his glory upon vessels of mercy, which he prepared beforehand for glory,

[[v45-9-24]]

^<<v45-9-24,24>>^ namely, us, whom he called not only from among Jews but also from among nations, &#91;what of it&#93;?

[[v45-9-25]]

^<<v45-9-25,25>>^ It is as he says also in Ho·seʹa: “Those not my people I will call ‘my people,’ and her who was not beloved ‘beloved’;

[[v45-9-26]]

^<<v45-9-26,26>>^ and in the place where it was said to them, ‘YOU are not my people,’ there they will be called ‘sons of the living God.’”

[[v45-9-27]]

^<<v45-9-27,27>>^ Moreover, Isaiah cries out concerning Israel: “Although the number of the sons of Israel may be as the sand of the sea, it is the remnant that will be saved.

[[v45-9-28]]

^<<v45-9-28,28>>^ For Jehovah^&#42;1^ will make an accounting on the earth, concluding it and cutting it short.”^&#42;2^

[NOTE]
====
. See App 1D.
. Or, “executing it speedily.”
====

[[v45-9-29]]

^<<v45-9-29,29>>^ Also, just as Isaiah had said aforetime: “Unless Jehovah^&#42;1^ of armies had left a seed to us, we should have become just like Sodʹom, and we should have been made just like Go·morʹrah.”

[NOTE]
====
. See App 1D.
====

[[v45-9-30]]

^<<v45-9-30,30>>^ What shall we say, then? That people of the nations, although not pursuing righteousness, caught up with righteousness, the righteousness that results from faith;

[[v45-9-31]]

^<<v45-9-31,31>>^ but Israel, although pursuing a law of righteousness, did not attain to the law.

[[v45-9-32]]

^<<v45-9-32,32>>^ For what reason? Because he pursued it, not by faith, but as by works. They stumbled on the “stone of stumbling”;

[[v45-9-33]]

^<<v45-9-33,33>>^ as it is written: “Look! I am laying in Zion a stone of stumbling and a rock-mass of offense, but he that rests his faith on it^&#42;1^ will not come to disappointment.”^&#42;2^

[NOTE]
====
. Or, “him.”
. Or, “not be ashamed.”
====

'''

xref:045-romans/045-romans-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romans/045-romans-010.adoc#v45-10-0[Próximo Capítulo &#62;]