include::./index.adoc[]

[[v45-2-0]]
=== To the Romans, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-2-1]]

^<<v45-2-1,1>>^ Therefore you are inexcusable, O man, whoever you are, if you judge; for in the thing in which you judge another, you condemn yourself, inasmuch as you that judge practice the same things.

[[v45-2-2]]

^<<v45-2-2,2>>^ Now we know that the judgment of God is, in accord with truth, against those who practice such things.

[[v45-2-3]]

^<<v45-2-3,3>>^ But do you have this idea, O man, while you judge those who practice such things and yet you do them, that you will escape the judgment of God?

[[v45-2-4]]

^<<v45-2-4,4>>^ Or do you despise the riches of his kindness and forbearance and long-suffering, because you do not know that the kindly &#91;quality&#93; of God is trying to lead you to repentance?^&#42;1^

[NOTE]
====
. Lit., “change of mind.”
====

[[v45-2-5]]

^<<v45-2-5,5>>^ But according to your hardness and unrepentant heart you are storing up wrath for yourself on the day of wrath and of the revealing of God’s righteous judgment.

[[v45-2-6]]

^<<v45-2-6,6>>^ And he will render to each one according to his works:

[[v45-2-7]]

^<<v45-2-7,7>>^ everlasting life to those who are seeking glory and honor and incorruptibleness by endurance in work that is good;

[[v45-2-8]]

^<<v45-2-8,8>>^ however, for those who are contentious and who disobey the truth but obey unrighteousness there will be wrath and anger,

[[v45-2-9]]

^<<v45-2-9,9>>^ tribulation and distress, upon the soul of every man who works what is injurious, of the Jew first and also of the Greek;

[[v45-2-10]]

^<<v45-2-10,10>>^ but glory and honor and peace for everyone who works what is good, for the Jew first and also for the Greek.

[[v45-2-11]]

^<<v45-2-11,11>>^ For there is no partiality with God.

[[v45-2-12]]

^<<v45-2-12,12>>^ For instance, all those who sinned without law will also perish without law; but all those who sinned under law will be judged by law.

[[v45-2-13]]

^<<v45-2-13,13>>^ For the hearers of law are not the ones righteous before God, but the doers of law will be declared righteous.

[[v45-2-14]]

^<<v45-2-14,14>>^ For whenever people of the nations that do not have law do by nature the things of the law, these people, although not having law, are a law to themselves.

[[v45-2-15]]

^<<v45-2-15,15>>^ They are the very ones who demonstrate the matter of the law to be written in their hearts, while their conscience is bearing witness with them and, between their own thoughts, they are being accused or even excused.

[[v45-2-16]]

^<<v45-2-16,16>>^ This will be in the day when God through Christ Jesus judges the secret things of mankind, according to the good news I declare.

[[v45-2-17]]

^<<v45-2-17,17>>^ If, now, you are a Jew in name and are resting upon law and taking pride in God,

[[v45-2-18]]

^<<v45-2-18,18>>^ and you know his will and approve of things that are excellent^&#42;1^ because you are orally instructed out of the Law;

[NOTE]
====
. Or, “and test the things that differ.”
====

[[v45-2-19]]

^<<v45-2-19,19>>^ and you are persuaded that you are a guide of the blind, a light for those in darkness,

[[v45-2-20]]

^<<v45-2-20,20>>^ a corrector of the unreasonable ones, a teacher of babes, and having the framework^&#42;1^ of the knowledge and of the truth in the Law—

[NOTE]
====
. Lit., “form.” Gr., morʹpho·sin.
====

[[v45-2-21]]

^<<v45-2-21,21>>^ do you, however, the one teaching someone else, not teach yourself? You, the one preaching “Do not steal,” do you steal?

[[v45-2-22]]

^<<v45-2-22,22>>^ You, the one saying “Do not commit adultery,”^&#42;1^ do you commit adultery? You, the one expressing abhorrence of the idols, do you rob temples?

[NOTE]
====
. See 13:9 ftn.
====

[[v45-2-23]]

^<<v45-2-23,23>>^ You, who take pride in law, do you by your transgressing of the Law dishonor God?

[[v45-2-24]]

^<<v45-2-24,24>>^ For “the name of God is being blasphemed on account of YOU people among the nations”; just as it is written.

[[v45-2-25]]

^<<v45-2-25,25>>^ Circumcision is, in fact, of benefit only if you practice law; but if you are a transgressor of law, your circumcision has become uncircumcision.

[[v45-2-26]]

^<<v45-2-26,26>>^ If, therefore, an uncircumcised person keeps the righteous requirements of the Law, his uncircumcision will be counted as circumcision, will it not?

[[v45-2-27]]

^<<v45-2-27,27>>^ And the uncircumcised &#91;person&#93; that is such by nature will, by carrying out the Law, judge you who with its written code and circumcision are a transgressor of law.

[[v45-2-28]]

^<<v45-2-28,28>>^ For he is not a Jew who is one on the outside, nor is circumcision that which is on the outside upon the flesh.

[[v45-2-29]]

^<<v45-2-29,29>>^ But he is a Jew who is one on the inside, and &#91;his&#93; circumcision is that of the heart by spirit, and not by a written code. The praise of that one comes, not from men, but from God.

'''

xref:045-romans/045-romans-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romans/045-romans-003.adoc#v45-3-0[Próximo Capítulo &#62;]