include::./index.adoc[]

[[v45-15-0]]
=== To the Romans, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-15-1]]

^<<v45-15-1,1>>^ We, though, who are strong ought to bear the weaknesses of those not strong, and not to be pleasing ourselves.

[[v45-15-2]]

^<<v45-15-2,2>>^ Let each of us please &#91;his&#93; neighbor in what is good for &#91;his&#93; upbuilding.

[[v45-15-3]]

^<<v45-15-3,3>>^ For even the Christ did not please himself; but just as it is written: “The reproaches of those who were reproaching you have fallen upon me.”

[[v45-15-4]]

^<<v45-15-4,4>>^ For all the things that were written aforetime were written for our instruction, that through our endurance and through the comfort from the Scriptures we might have hope.^&#42;1^

[NOTE]
====
. “Hope,” אAVgSyp; B, “hope of the comfort; the comforting hope.”
====

[[v45-15-5]]

^<<v45-15-5,5>>^ Now may the God who supplies endurance and comfort grant YOU to have among yourselves the same mental attitude that Christ Jesus had,

[[v45-15-6]]

^<<v45-15-6,6>>^ that with one accord YOU may with one mouth glorify the God and Father of our Lord Jesus Christ.

[[v45-15-7]]

^<<v45-15-7,7>>^ Therefore welcome one another, just as the Christ also welcomed us, with glory to God in view.

[[v45-15-8]]

^<<v45-15-8,8>>^ For I say that Christ actually became a minister of those who are circumcised in behalf of God’s truthfulness, so as to verify the promises He made to their forefathers,

[[v45-15-9]]

^<<v45-15-9,9>>^ and that the nations might glorify God for his mercy. Just as it is written: “That is why I will openly acknowledge you among the nations^&#42;1^ and to your name I will make melody.”

[NOTE]
====
. “Nations,” ABSyp; אcVgc, “nations, O Lord.”
====

[[v45-15-10]]

^<<v45-15-10,10>>^ And again he says: “Be glad, YOU nations, with his people.”

[[v45-15-11]]

^<<v45-15-11,11>>^ And again: “Praise Jehovah,^&#42;1^ all YOU nations, and let all the peoples praise him.”

[NOTE]
====
. See App 1D.
====

[[v45-15-12]]

^<<v45-15-12,12>>^ And again Isaiah says: “There will be the root of Jesʹse, and there will be one arising to rule nations; on him nations will rest their hope.”

[[v45-15-13]]

^<<v45-15-13,13>>^ May the God who gives hope fill YOU with all joy and peace by YOUR believing, that YOU may abound in hope with power of holy spirit.

[[v45-15-14]]

^<<v45-15-14,14>>^ Now I myself also am persuaded about YOU, my brothers, that YOU yourselves are also full of goodness, as YOU have been filled with all knowledge, and that YOU can also admonish one another.

[[v45-15-15]]

^<<v45-15-15,15>>^ However, I am writing YOU the more outspokenly on some points, as if reminding YOU again, because of the undeserved kindness given to me from God

[[v45-15-16]]

^<<v45-15-16,16>>^ for me to be a public servant^&#42;1^ of Christ Jesus to the nations, engaging in the holy work of the good news of God, in order that the offering, namely, these nations, might prove to be acceptable, it being sanctified with holy spirit.

[NOTE]
====
. “Public servant.” Gr., lei·tour·gonʹ.
====

[[v45-15-17]]

^<<v45-15-17,17>>^ Therefore I have cause for exulting in Christ Jesus when it comes to things pertaining to God.

[[v45-15-18]]

^<<v45-15-18,18>>^ For I will not venture to tell one thing if it is not of those things which Christ worked through me for the nations to be obedient, by &#91;my&#93; word and deed,

[[v45-15-19]]

^<<v45-15-19,19>>^ with the power of signs and portents, with the power of holy spirit;^&#42;1^ so that from Jerusalem and in a circuit as far as Il·lyrʹi·cum I have thoroughly preached the good news about the Christ.

[NOTE]
====
. “Holy spirit,” AD*Vg; P46אSyh,p, “spirit of God”; B, “spirit.”
====

[[v45-15-20]]

^<<v45-15-20,20>>^ In this way, indeed, I made it my aim not to declare the good news where Christ had already been named, in order that I might not be building on another man’s foundation;

[[v45-15-21]]

^<<v45-15-21,21>>^ but, just as it is written: “Those to whom no announcement has been made about him will see, and those who have not heard will understand.”

[[v45-15-22]]

^<<v45-15-22,22>>^ Therefore also I was many times hindered from getting to YOU.

[[v45-15-23]]

^<<v45-15-23,23>>^ But now that I no longer have &#91;untouched&#93; territory in these regions, and for some years having had a longing to get to YOU

[[v45-15-24]]

^<<v45-15-24,24>>^ whenever I am on my way to Spain, I hope, above all, when I am on the journey there, to get a look at YOU and to be escorted partway there by YOU after I have first in some measure been satisfied with your company.

[[v45-15-25]]

^<<v45-15-25,25>>^ But now I am about to journey to Jerusalem to minister to the holy ones.

[[v45-15-26]]

^<<v45-15-26,26>>^ For those in Mac·e·doʹni·a and A·chaʹia^&#42;1^ have been pleased to share up their things by a contribution to the poor of the holy ones in Jerusalem.

[NOTE]
====
. The Roman province of southern Greece with its capital at Corinth.
====

[[v45-15-27]]

^<<v45-15-27,27>>^ True, they have been pleased to do so, and yet they were debtors to them; for if the nations have shared in their spiritual things, they also owe it to minister publicly to these with things for the fleshly body.

[[v45-15-28]]

^<<v45-15-28,28>>^ Hence after I have finished with this and have got this fruit securely to them, I shall depart by way of YOU for Spain.

[[v45-15-29]]

^<<v45-15-29,29>>^ Moreover, I know that when I do come to YOU I shall come with a full measure of blessing from Christ.

[[v45-15-30]]

^<<v45-15-30,30>>^ Now I exhort YOU, brothers,^&#42;1^ through our Lord Jesus Christ and through the love of the spirit, that YOU exert yourselves with me in prayers to God for me,

[NOTE]
====
. “Brothers,” אADVgSyp; P46B omit.
====

[[v45-15-31]]

^<<v45-15-31,31>>^ that I may be delivered from the unbelievers in Ju·deʹa and that my ministry which is for Jerusalem may prove to be acceptable to the holy ones,

[[v45-15-32]]

^<<v45-15-32,32>>^ so that when I get to YOU with joy by God’s will I shall be refreshed together with YOU.

[[v45-15-33]]

^<<v45-15-33,33>>^ May the God who gives peace be with all of YOU. Amen.

'''

xref:045-romans/045-romans-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romans/045-romans-016.adoc#v45-16-0[Próximo Capítulo &#62;]