include::./index.adoc[]

[[v45-3-0]]
=== To the Romans, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-3-1]]

^<<v45-3-1,1>>^ What, then, is the superiority of the Jew, or what is the benefit of the circumcision?

[[v45-3-2]]

^<<v45-3-2,2>>^ A great deal in every way. First of all, because they were entrusted with the sacred pronouncements^&#42;1^ of God.

[NOTE]
====
. “Sacred pronouncements.” Lit., “little words.” Gr., loʹgi·a; Lat., e·loʹqui·a; J17,​18,​22(Heb.), div·rehʹ.
====

[[v45-3-3]]

^<<v45-3-3,3>>^ What, then, &#91;is the case&#93;? If some did not express faith, will their lack of faith perhaps make the faithfulness of God without effect?

[[v45-3-4]]

^<<v45-3-4,4>>^ Never may that happen! But let God be found true, though every man be found a liar, even as it is written: “That you might be proved righteous in your words and might win when you are being judged.”

[[v45-3-5]]

^<<v45-3-5,5>>^ However, if our unrighteousness brings God’s righteousness to the fore, what shall we say? God is not unjust when he vents his wrath, is he? (I am speaking as a man does.)

[[v45-3-6]]

^<<v45-3-6,6>>^ Never may that happen! How, otherwise, will God judge the world?

[[v45-3-7]]

^<<v45-3-7,7>>^ Yet if by reason of my lie the truth of God has been made more prominent to his glory, why am I also yet being judged as a sinner?

[[v45-3-8]]

^<<v45-3-8,8>>^ And &#91;why&#93; not &#91;say&#93;, just as it is falsely charged to us and just as some men state that we say: “Let us do the bad things that the good things may come”? The judgment against those &#91;men&#93; is in harmony with justice.

[[v45-3-9]]

^<<v45-3-9,9>>^ What then? Are we in a better position? Not at all! For above we have made the charge that Jews as well as Greeks are all under sin;^&#42;1^

[NOTE]
====
. “Sin.” Gr., ha·mar·tiʹan; Lat., pec·caʹto; J17(Heb.), ha·chetʼʹ, from a root meaning “to miss the mark [as in spear throwing].” See vs 23.
====

[[v45-3-10]]

^<<v45-3-10,10>>^ just as it is written: “There is not a righteous &#91;man&#93;, not even one;

[[v45-3-11]]

^<<v45-3-11,11>>^ there is no one that has any insight, there is no one that seeks for God.

[[v45-3-12]]

^<<v45-3-12,12>>^ All &#91;men&#93; have deflected, all of them together have become worthless; there is no one that does kindness, there is not so much as one.”

[[v45-3-13]]

^<<v45-3-13,13>>^ “Their throat is an opened grave, they have used deceit with their tongues.” “Poison of asps is behind their lips.”

[[v45-3-14]]

^<<v45-3-14,14>>^ “And their mouth is full of cursing and bitter expression.”

[[v45-3-15]]

^<<v45-3-15,15>>^ “Their feet are speedy to shed blood.”

[[v45-3-16]]

^<<v45-3-16,16>>^ “Ruin and misery are in their ways,

[[v45-3-17]]

^<<v45-3-17,17>>^ and they have not known the way of peace.”

[[v45-3-18]]

^<<v45-3-18,18>>^ “There is no fear of God before their eyes.”^&#42;1^

[NOTE]
====
. The quotations in vss 13-18 are found in Ps 13:3 in LXX. See Ps 14:3 ftn.
====

[[v45-3-19]]

^<<v45-3-19,19>>^ Now we know that all the things the Law^&#42;1^ says it addresses to those under the Law, so that every mouth may be stopped and all the world may become liable to God for punishment.

[NOTE]
====
. “The Law.” Gr., ho noʹmos, with the definite article ho to particularize. Here the context warrants capitalization to indicate the “Law” given through Moses. In The Bible Translator, Vol. 1, January 1950, published by The United Bible Societies, London, p. 165, J. Harold Greenlee states: “The word ‘law’ requires individual attention. The [Greek] article indicates a particular law, or the Mosaic law; without the article, reference may be to ‘law’ as a principle.”
====

[[v45-3-20]]

^<<v45-3-20,20>>^ Therefore by works of law no flesh will be declared righteous before him, for by law is the accurate knowledge of sin.

[[v45-3-21]]

^<<v45-3-21,21>>^ But now apart from law God’s righteousness has been made manifest, as it is borne witness to by the Law and the Prophets;

[[v45-3-22]]

^<<v45-3-22,22>>^ yes, God’s righteousness through the faith in Jesus^&#42;1^ Christ, for all those having faith. For there is no distinction.

[NOTE]
====
. “Jesus.” B omits.
====

[[v45-3-23]]

^<<v45-3-23,23>>^ For all have sinned and fall short of the glory of God,

[[v45-3-24]]

^<<v45-3-24,24>>^ and it is as a free gift that they are being declared righteous by his undeserved kindness through the release by the ransom &#91;paid&#93; by Christ^&#42;1^ Jesus.

[NOTE]
====
. Or, “through the redemption that is in (by) Christ.”
====

[[v45-3-25]]

^<<v45-3-25,25>>^ God set him forth as an offering for propitiation^&#42;1^ through faith in his blood. This was in order to exhibit his own righteousness, because he was forgiving the sins that occurred in the past while God was exercising forbearance;

[NOTE]
====
. “An offering for propitiation.” Lit., “propitiatory.” Gr., hi·la·steʹri·on; Lat., pro·pi·ti·a·ti·oʹnem; J17(Heb.), lekhap·poʹreth, “as a propitiatory cover.” See Heb 9:5.
====

[[v45-3-26]]

^<<v45-3-26,26>>^ so as to exhibit his own righteousness in this present season, that he might be righteous even when declaring righteous the man that has faith in Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Where, then, is the boasting? It is shut out. Through what law? That of works? No indeed, but through the law of faith.

[[v45-3-28]]

^<<v45-3-28,28>>^ For we reckon that a man is declared righteous^&#42;1^ by faith apart from works of law.

[NOTE]
====
. Lit., “to be being justified.” Gr., di·kai·ouʹsthai; Lat., iu·sti·fi·caʹri.
====

[[v45-3-29]]

^<<v45-3-29,29>>^ Or is he the God of the Jews only? Is he not also of people of the nations? Yes, of people of the nations also,

[[v45-3-30]]

^<<v45-3-30,30>>^ if truly God is one, who will declare circumcised people righteous as a result of faith and uncircumcised people righteous by means of their faith.

[[v45-3-31]]

^<<v45-3-31,31>>^ Do we, then, abolish law by means of our faith? Never may that happen! On the contrary, we establish law.

'''

xref:045-romans/045-romans-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romans/045-romans-004.adoc#v45-4-0[Próximo Capítulo &#62;]