include::./index.adoc[]

[[v45-4-0]]
=== To the Romans, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-4-1]]

^<<v45-4-1,1>>^ That being so, what shall we say about Abraham our forefather according to the flesh?^&#42;1^

[NOTE]
====
. “Say about Abraham . . . flesh,” B; אADVg, “say that Abraham our forefather according to the flesh has gained.”
====

[[v45-4-2]]

^<<v45-4-2,2>>^ If, for instance, Abraham were declared righteous as a result of works, he would have ground for boasting; but not with God.

[[v45-4-3]]

^<<v45-4-3,3>>^ For what does the scripture say? “Abraham exercised faith in Jehovah,^&#42;1^ and it was counted to him as righteousness.”

[NOTE]
====
. See App 1D.
====

[[v45-4-4]]

^<<v45-4-4,4>>^ Now to the man that works the pay is counted,^&#42;1^ not as an undeserved kindness, but as a debt.

[NOTE]
====
. Lit., “is being reckoned.” Gr., lo·giʹze·tai; Lat., in·pu·taʹtur.
====

[[v45-4-5]]

^<<v45-4-5,5>>^ On the other hand, to the man that does not work but puts faith in him who declares the ungodly one righteous, his faith is counted as righteousness.

[[v45-4-6]]

^<<v45-4-6,6>>^ Just as David also speaks of the happiness^&#42;1^ of the man to whom God counts righteousness apart from works:

[NOTE]
====
. Or, “David also pronounces the felicitation.”
====

[[v45-4-7]]

^<<v45-4-7,7>>^ “Happy are those whose lawless deeds have been pardoned and whose sins have been covered;

[[v45-4-8]]

^<<v45-4-8,8>>^ happy is the man whose sin Jehovah^&#42;1^ will by no means take into account.”

[NOTE]
====
. See App 1D.
====

[[v45-4-9]]

^<<v45-4-9,9>>^ Does this happiness, then, come upon circumcised people or also upon uncircumcised people? For we say: “His faith was counted to Abraham as righteousness.”

[[v45-4-10]]

^<<v45-4-10,10>>^ Under what circumstances, then, was it counted? When he was in circumcision or in uncircumcision? Not in circumcision, but in uncircumcision.

[[v45-4-11]]

^<<v45-4-11,11>>^ And he received a sign, namely, circumcision, as a seal^&#42;1^ of the righteousness by the faith he had while in his uncircumcised state, that he might be the father of all those having faith while in uncircumcision, in order for righteousness to be counted to them;

[NOTE]
====
. Or, “confirmation.”
====

[[v45-4-12]]

^<<v45-4-12,12>>^ and a father of circumcised offspring, not only to those who adhere to circumcision, but also to those who walk orderly in the footsteps of that faith while in the uncircumcised state which our father Abraham had.

[[v45-4-13]]

^<<v45-4-13,13>>^ For it was not through law that Abraham or his seed had the promise that he should be heir of a world, but it was through the righteousness by faith.

[[v45-4-14]]

^<<v45-4-14,14>>^ For if those who adhere to law are heirs, faith has been made useless and the promise has been abolished.

[[v45-4-15]]

^<<v45-4-15,15>>^ In reality the Law produces wrath, but where there is no law, neither is there any transgression.

[[v45-4-16]]

^<<v45-4-16,16>>^ On this account it was as a result of faith, that it might be according to undeserved kindness, in order for the promise to be sure to all his seed, not only to that which adheres to the Law, but also to that which adheres to the faith of Abraham. (He is the father of us all,

[[v45-4-17]]

^<<v45-4-17,17>>^ just as it is written: “I have appointed you a father of many nations.”) This was in the sight of the One in whom he had faith, even of God, who makes the dead alive and calls^&#42;1^ the things that are not as though they were.

[NOTE]
====
. Or, “summons.”
====

[[v45-4-18]]

^<<v45-4-18,18>>^ Although beyond hope, yet based on hope he had faith, that he might become the father of many nations in accord with what had been said: “So your seed will be.”

[[v45-4-19]]

^<<v45-4-19,19>>^ And, although he did not grow weak in faith, he considered his own body, now already deadened, as he was about one hundred years old, also the deadness of the womb of Sarah.

[[v45-4-20]]

^<<v45-4-20,20>>^ But because of the promise of God he did not waver in a lack of faith, but became powerful by his faith, giving God glory

[[v45-4-21]]

^<<v45-4-21,21>>^ and being fully convinced that what he had promised he was also able to do.

[[v45-4-22]]

^<<v45-4-22,22>>^ Hence “it was counted to him as righteousness.”

[[v45-4-23]]

^<<v45-4-23,23>>^ That “it was counted to him” was written, however, not for his sake only,

[[v45-4-24]]

^<<v45-4-24,24>>^ but also for the sake of us to whom it is destined to be counted, because we believe on him who raised Jesus our Lord up from the dead.

[[v45-4-25]]

^<<v45-4-25,25>>^ He was delivered up for the sake of our trespasses and was raised up for the sake of declaring us righteous.

'''

xref:045-romans/045-romans-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romans/045-romans-005.adoc#v45-5-0[Próximo Capítulo &#62;]