include::./index.adoc[]

[[v45-13-0]]
=== To the Romans, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v45-13-1]]

^<<v45-13-1,1>>^ Let every soul^&#42;1^ be in subjection to the superior authorities, for there is no authority except by God; the existing authorities stand placed in their relative positions^&#42;2^ by God.

[NOTE]
====
. Or, “every living person.” See App 4A.
. “Stand placed in their relative positions.” Lit., “having been set in order they are.”
====

[[v45-13-2]]

^<<v45-13-2,2>>^ Therefore he who opposes^&#42;1^ the authority has taken a stand against the arrangement of God; those who have taken a stand against it will receive judgment to themselves.

[NOTE]
====
. Lit., “the (one) setting self against.”
====

[[v45-13-3]]

^<<v45-13-3,3>>^ For those ruling are an object of fear, not to the good deed, but to the bad. Do you, then, want to have no fear of the authority? Keep doing good, and you will have praise from it;^&#42;1^

[NOTE]
====
. Or, “her,” that is, the “authority.”
====

[[v45-13-4]]

^<<v45-13-4,4>>^ for it^&#42;1^ is God’s minister^&#42;2^ to you for your good. But if you are doing what is bad, be in fear: for it is not without purpose that it bears the sword; for it is God’s minister, an avenger to express wrath upon the one practicing what is bad.

[NOTE]
====
. Or, “she,” that is, the “authority.”
. Lit., “servant.”
====

[[v45-13-5]]

^<<v45-13-5,5>>^ There is therefore compelling reason^&#42;1^ for YOU people to be in subjection, not only on account of that wrath but also on account of &#91;YOUR&#93; conscience.

[NOTE]
====
. Lit., “necessity.”
====

[[v45-13-6]]

^<<v45-13-6,6>>^ For that is why YOU are also paying taxes; for they are God’s public servants^&#42;1^ constantly serving this very purpose.^&#42;2^

[NOTE]
====
. “Public servants.” Gr., lei·tour·goiʹ.
. Or, “devoting themselves to this very thing.”
====

[[v45-13-7]]

^<<v45-13-7,7>>^ Render^&#42;1^ to all their dues, to him who &#91;calls for&#93; the tax, the tax; to him who &#91;calls for&#93; the tribute, the tribute; to him who &#91;calls for&#93; fear, such fear; to him who &#91;calls for&#93; honor, such honor.

[NOTE]
====
. Lit., “Give you back.”
====

[[v45-13-8]]

^<<v45-13-8,8>>^ Do not YOU people be owing anybody a single thing, except to love one another; for he that loves his fellowman^&#42;1^ has fulfilled &#91;the&#93; law.

[NOTE]
====
. Or, “loves the other,” that is, the other of two.
====

[[v45-13-9]]

^<<v45-13-9,9>>^ For the &#91;law code&#93;, “You must not commit adultery,^&#42;1^ You must not murder, You must not steal, You must not covet,” and whatever other commandment there is, is summed up in this word, namely, “You must love your neighbor as yourself.”

[NOTE]
====
. Or, “You must not commit marital sexual unfaithfulness.” Gr., Ou moi·kheuʹseis; Lat., non a·dul·te·raʹbis; J22(Heb.), loʼ tin·ʼaphʹ. See Eze 16:32 ftn.
====

[[v45-13-10]]

^<<v45-13-10,10>>^ Love does not work evil to one’s neighbor; therefore love is the law’s fulfillment.

[[v45-13-11]]

^<<v45-13-11,11>>^ &#91;Do&#93; this, too, because YOU people know the season,^&#42;1^ that it is already the hour for YOU to awake from sleep, for now our salvation is nearer than at the time when we became believers.

[NOTE]
====
. Lit., “appointed time.” Gr., kai·ronʹ.
====

[[v45-13-12]]

^<<v45-13-12,12>>^ The night is well along; the day has drawn near. Let us therefore put off the works belonging to darkness and let us put on the weapons of the light.

[[v45-13-13]]

^<<v45-13-13,13>>^ As in the daytime let us walk decently, not in revelries and drunken bouts, not in illicit intercourse and loose conduct,^&#42;1^ not in strife and jealousy.

[NOTE]
====
. “Loose conduct.” Gr., a·sel·geiʹais; Lat., in·pu·di·ciʹti·is; J17,​22(Heb.), zim·mahʹ. See Ga 5:19 ftn, “Conduct.” Compare Le 18:17 ftn.
====

[[v45-13-14]]

^<<v45-13-14,14>>^ But put on the Lord^&#42;1^ Jesus Christ, and do not be planning ahead for the desires of the flesh.

[NOTE]
====
. Or, “imitate the manners of the Lord.”
====

'''

xref:045-romans/045-romans-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romans/045-romans-014.adoc#v45-14-0[Próximo Capítulo &#62;]