include::./index.adoc[]

[[v51-3-0]]
=== Letter to the Colossians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v51-3-1]]

^<<v51-3-1,1>>^ If, however, YOU were raised up with the Christ, go on seeking the things above, where the Christ is seated at the right hand of God.

[[v51-3-2]]

^<<v51-3-2,2>>^ Keep YOUR minds fixed on the things above, not on the things upon the earth.

[[v51-3-3]]

^<<v51-3-3,3>>^ For YOU died, and YOUR life has been hidden with the Christ in union with God.

[[v51-3-4]]

^<<v51-3-4,4>>^ When the Christ, our life, is made manifest, then YOU also will be made manifest with him in glory.

[[v51-3-5]]

^<<v51-3-5,5>>^ Deaden, therefore, YOUR body members that are upon the earth as respects fornication,^&#42;1^ uncleanness,^&#42;2^ sexual appetite,^&#42;3^ hurtful desire, and covetousness, which is idolatry.

[NOTE]
====
. “Fornication.” Gr., por·neiʹan; Lat., for·ni·ca·ti·oʹnem; J17,​22(Heb.), haz·zenuthʹ, “the fornication.” See App 5A.
. Or, “filthiness; depravity; lewdness.” Gr., a·ka·thar·siʹan; J17,​22(Heb.), wehat·tum·ʼahʹ, “and the uncleanness.” See 2Co 12:21 ftn, “Uncleanness.”
. Lit., “passion.” Gr., paʹthos.
====

[[v51-3-6]]

^<<v51-3-6,6>>^ On account of those things the wrath of God is coming.

[[v51-3-7]]

^<<v51-3-7,7>>^ In those very things YOU, too, once walked when YOU used to live in them.

[[v51-3-8]]

^<<v51-3-8,8>>^ But now really put them all away from YOU, wrath, anger, badness, abusive speech,^&#42;1^ and obscene talk out of YOUR mouth.

[NOTE]
====
. Or, “blasphemy.”
====

[[v51-3-9]]

^<<v51-3-9,9>>^ Do not be lying to one another. Strip off the old personality^&#42;1^ with its practices,

[NOTE]
====
. Lit., “the old man.”
====

[[v51-3-10]]

^<<v51-3-10,10>>^ and clothe yourselves with the new &#91;personality&#93;, which through^&#42;1^ accurate knowledge is being made new according to the image of the One who created it,

[NOTE]
====
. Or, “in.”
====

[[v51-3-11]]

^<<v51-3-11,11>>^ where there is neither Greek nor Jew, circumcision nor uncircumcision, foreigner, Scythʹi·an, slave, freeman, but Christ is all things and in all.

[[v51-3-12]]

^<<v51-3-12,12>>^ Accordingly, as God’s chosen ones, holy and loved, clothe yourselves with the tender affections of compassion, kindness, lowliness of mind,^&#42;1^ mildness, and long-suffering.

[NOTE]
====
. Or, “humility.”
====

[[v51-3-13]]

^<<v51-3-13,13>>^ Continue putting up with one another and forgiving one another freely if anyone has a cause for complaint against another. Even as Jehovah^&#42;1^ freely forgave YOU, so do YOU also.

[NOTE]
====
. “Jehovah,” J23; P46ABD*(Gr.), ho Kyʹri·os; אcCDcSyh,p, “the Christ”; א*, “God.” See App 1D.
====

[[v51-3-14]]

^<<v51-3-14,14>>^ But, besides all these things, &#91;clothe yourselves with&#93; love, for it is a perfect bond of union.^&#42;1^

[NOTE]
====
. Lit., “joint bond of the perfection.”
====

[[v51-3-15]]

^<<v51-3-15,15>>^ Also, let the peace of the Christ^&#42;1^ control in YOUR hearts, for YOU were, in fact, called to it in one^&#42;2^ body. And show yourselves thankful.

[NOTE]
====
. “Of the Christ,” א*ABC*D*; אcCcDc, “of God”; J7,​8, “of Jehovah.”
. “One,” אADVgSyp; P46B, “the.”
====

[[v51-3-16]]

^<<v51-3-16,16>>^ Let the word of the Christ^&#42;1^ reside in YOU richly in all wisdom. Keep on teaching and admonishing one another with psalms, praises to God,^&#42;2^ spiritual songs with graciousness, singing in YOUR hearts to Jehovah.^&#42;3^

[NOTE]
====
. “The Christ,” P46אcBCcDVg; א*, “the Lord”; AC*, “God.”
. Lit., “hymns.” Gr., hyʹmnois; Lat., hyʹmnis.
. “To Jehovah,” J7,​8,​13,​14,​16,​17; CcDc(Gr.), toi Ky·riʹoi; P46אABC*D*VgSyh,p, “to God.” See App 1D.
====

[[v51-3-17]]

^<<v51-3-17,17>>^ And whatever it is that YOU do in word or in work, do everything in the name of the Lord Jesus, thanking God the Father through him.

[[v51-3-18]]

^<<v51-3-18,18>>^ YOU wives, be in subjection to &#91;your&#93; husbands, as it is becoming in &#91;the&#93; Lord.

[[v51-3-19]]

^<<v51-3-19,19>>^ YOU husbands, keep on loving &#91;your&#93; wives and do not be bitterly angry with them.

[[v51-3-20]]

^<<v51-3-20,20>>^ YOU children, be obedient to &#91;your&#93; parents in everything, for this is well-pleasing in &#91;the&#93; Lord.

[[v51-3-21]]

^<<v51-3-21,21>>^ YOU fathers, do not be exasperating your children, so that they do not become downhearted.

[[v51-3-22]]

^<<v51-3-22,22>>^ YOU slaves, be obedient in everything to those who are &#91;your&#93; masters in a fleshly sense, not with acts of eye-service, as men pleasers, but with sincerity of heart, with fear of Jehovah.^&#42;1^

[NOTE]
====
. “Of Jehovah,” J18,​22; א*ABCD*(Gr.), ton Kyʹri·on; P46אcDc, “of God.” See App 1D.
====

[[v51-3-23]]

^<<v51-3-23,23>>^ Whatever YOU are doing, work at it whole-souled as to Jehovah,^&#42;1^ and not to men,

[NOTE]
====
. See App 1D.
====

[[v51-3-24]]

^<<v51-3-24,24>>^ for YOU know that it is from Jehovah^&#42;1^ YOU will receive the due reward of the inheritance. SLAVE for the Master, Christ.

[NOTE]
====
. See App 1D.
====

[[v51-3-25]]

^<<v51-3-25,25>>^ Certainly the one that is doing wrong will receive back what he wrongly did, and there is no partiality.

'''

xref:051-colossians/051-colossians-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossians/051-colossians-004.adoc#v51-4-0[Próximo Capítulo &#62;]