include::./index.adoc[]

[[v51-2-0]]
=== Letter to the Colossians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v51-2-1]]

^<<v51-2-1,1>>^ For I want YOU to realize how great a struggle I am having in behalf of YOU and of those at La·o·di·ceʹa and of all those who have not seen my face in the flesh,

[[v51-2-2]]

^<<v51-2-2,2>>^ that their hearts may be comforted, that they may be harmoniously joined together in love and with a view to all the riches of the full assurance of &#91;their&#93; understanding, with a view to an accurate knowledge of the sacred secret of God, namely, Christ.^&#42;1^

[NOTE]
====
. “Of the God of Christ,” P46B; א*AVg, “of God the Father of (the) Christ (Jesus).”
====

[[v51-2-3]]

^<<v51-2-3,3>>^ Carefully concealed in him are all the treasures of wisdom and of knowledge.

[[v51-2-4]]

^<<v51-2-4,4>>^ This I am saying that no man may delude^&#42;1^ YOU with persuasive arguments.

[NOTE]
====
. Or, “cheat.”
====

[[v51-2-5]]

^<<v51-2-5,5>>^ For though I am absent in the flesh, all the same I am with YOU in the spirit, rejoicing and beholding YOUR good order and the firmness of YOUR faith toward Christ.

[[v51-2-6]]

^<<v51-2-6,6>>^ Therefore, as YOU have accepted Christ Jesus the Lord, go on walking in union with him,

[[v51-2-7]]

^<<v51-2-7,7>>^ rooted and being built up in him and being stabilized in the faith, just as YOU were taught, overflowing with &#91;faith&#93;^&#42;1^ in thanksgiving.

[NOTE]
====
. “Overflowing in it,” BSyh,pArm; א*AVg, “overflowing.”
====

[[v51-2-8]]

^<<v51-2-8,8>>^ Look out: perhaps there may be someone who will carry YOU off as his prey through the philosophy and empty deception^&#42;1^ according to the tradition of men, according to the elementary things of the world and not according to Christ;

[NOTE]
====
. Lit., “seduction.”
====

[[v51-2-9]]

^<<v51-2-9,9>>^ because it is in him that all the fullness of the divine quality^&#42;1^ dwells bodily.

[NOTE]
====
. “Divine quality.” Lit., “godship.” Gr., the·oʹte·tos; Lat., di·vi·ni·taʹtis.
====

[[v51-2-10]]

^<<v51-2-10,10>>^ And so YOU are possessed of a fullness by means of him, who is the head of all government and authority.

[[v51-2-11]]

^<<v51-2-11,11>>^ By relationship with him YOU were also circumcised with a circumcision performed without hands by the stripping off the body of the flesh, by the circumcision that belongs to the Christ,

[[v51-2-12]]

^<<v51-2-12,12>>^ for YOU were buried with him in &#91;his&#93;^&#42;1^ baptism, and by relationship with him YOU were also raised up together through &#91;YOUR&#93; faith in the operation of God, who raised him up from the dead.

[NOTE]
====
. Lit., “the.”
====

[[v51-2-13]]

^<<v51-2-13,13>>^ Furthermore, though YOU were dead in YOUR trespasses and in the uncircumcised state of YOUR flesh, &#91;God&#93;^&#42;1^ made YOU alive together with him. He kindly forgave us all our trespasses

[NOTE]
====
. Lit., “he.”
====

[[v51-2-14]]

^<<v51-2-14,14>>^ and blotted out^&#42;1^ the handwritten document^&#42;2^ against us, which consisted of decrees and which was in opposition to us; and He has taken it out of the way by nailing it to the torture stake.^&#42;3^

[NOTE]
====
. Lit., “having wiped out.”
. Or, “covenant.”
. See App 5C.
====

[[v51-2-15]]

^<<v51-2-15,15>>^ Stripping the governments and the authorities bare, he exhibited^&#42;1^ them in open public as conquered, leading them in a triumphal procession by means of it.^&#42;2^

[NOTE]
====
. Lit., “he made show of.”
. Or, “him.” Gr., au·toiʹ, dative, sing.
====

[[v51-2-16]]

^<<v51-2-16,16>>^ Therefore let no man judge YOU in eating and drinking or in respect of a festival or of an observance of the new moon or of a sabbath;^&#42;1^

[NOTE]
====
. Or, “of sabbaths.”
====

[[v51-2-17]]

^<<v51-2-17,17>>^ for those things are a shadow of the things to come, but the reality^&#42;1^ belongs to the Christ.

[NOTE]
====
. Or, “substance.” Lit., “body.” Gr., soʹma; Lat., corʹpus.
====

[[v51-2-18]]

^<<v51-2-18,18>>^ Let no man deprive YOU of the prize who takes delight in a &#91;mock&#93; humility^&#42;1^ and a form of worship^&#42;2^ of the angels, “taking his stand on”^&#42;3^ the things he has seen, puffed up without proper cause by his fleshly frame of mind,

[NOTE]
====
. Lit., “lowly-mindedness.”
. “Form of worship.” Lat., re·li·gi·oʹne, “religion.”
. Quoted from the initiation rites of pagan mysteries.
====

[[v51-2-19]]

^<<v51-2-19,19>>^ whereas he is not holding fast to the head, to the one from whom all the body, being supplied and harmoniously joined together by means of its joints and ligaments, goes on growing with the growth that God gives.

[[v51-2-20]]

^<<v51-2-20,20>>^ If YOU died together with Christ toward the elementary things of the world, why do YOU, as if living in the world, further subject yourselves to the decrees:

[[v51-2-21]]

^<<v51-2-21,21>>^ “Do not handle, nor taste, nor touch,”

[[v51-2-22]]

^<<v51-2-22,22>>^ respecting things that are all destined to destruction by being used up, in accordance with the commands and teachings of men?

[[v51-2-23]]

^<<v51-2-23,23>>^ Those very things are, indeed, possessed of an appearance of wisdom in a self-imposed form of worship^&#42;1^ and &#91;mock&#93; humility, a severe treatment of the body; but they are of no value in combating the satisfying of the flesh.

[NOTE]
====
. Lit., “self-willed form of worship.” Gr., e·the·lo·thre·skiʹai; Lat., su·per·sti·ti·oʹne, “superstition.”
====

'''

xref:051-colossians/051-colossians-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossians/051-colossians-003.adoc#v51-3-0[Próximo Capítulo &#62;]