include::./index.adoc[]

[[v51-1-0]]
=== Letter to the Colossians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v51-1-1]]

^<<v51-1-1,1>>^ Paul, an apostle of Christ Jesus through God’s will, and Timothy &#91;our&#93; brother

[[v51-1-2]]

^<<v51-1-2,2>>^ to the holy ones and faithful brothers in union with Christ at Co·losʹsae:
May YOU have undeserved kindness and peace from God our Father.

[[v51-1-3]]

^<<v51-1-3,3>>^ We thank God the Father of our Lord Jesus Christ^&#42;1^ always when we pray^&#42;2^ for YOU,

[NOTE]
====
. “Christ,” אAVgSyp; B omits.
. Or, “praying always.”
====

[[v51-1-4]]

^<<v51-1-4,4>>^ since we heard of YOUR faith in connection with Christ Jesus and the love YOU have^&#42;1^ for all the holy ones

[NOTE]
====
. “You have,” אAVg; B omits.
====

[[v51-1-5]]

^<<v51-1-5,5>>^ because of the hope that is being reserved for YOU in the heavens. This &#91;hope&#93; YOU heard of before by the telling of the truth of that good news

[[v51-1-6]]

^<<v51-1-6,6>>^ which has presented itself to YOU, even as it is bearing fruit and increasing in all the world just as &#91;it is doing&#93; also among YOU, from the day YOU heard and accurately knew the undeserved kindness of God in truth.

[[v51-1-7]]

^<<v51-1-7,7>>^ That is what YOU have learned from Epʹa·phras our beloved fellow slave, who is a faithful minister^&#42;1^ of the Christ on our behalf,

[NOTE]
====
. Or, “servant.” Gr., di·aʹko·nos; Lat., mi·niʹster (from miʹnus, “less”); J17,​18(Heb.), mesha·rethʹ, “attendant.”
====

[[v51-1-8]]

^<<v51-1-8,8>>^ who also disclosed to us YOUR love in a spiritual way.^&#42;1^

[NOTE]
====
. Lit., “in spirit.”
====

[[v51-1-9]]

^<<v51-1-9,9>>^ That is also why we, from the day we heard &#91;of it&#93;, have not ceased praying for YOU and asking^&#42;1^ that YOU may be filled with the accurate knowledge of his will in all wisdom and spiritual comprehension,

[NOTE]
====
. Lit., “petitioning.”
====

[[v51-1-10]]

^<<v51-1-10,10>>^ in order to walk worthily of Jehovah^&#42;1^ to the end of fully pleasing &#91;him&#93; as YOU go on bearing fruit in every good work and increasing in the accurate knowledge of God,

[NOTE]
====
. “Of Jehovah,” J7,​8; אAB(Gr.), tou Ky·riʹou; Vg, “of God.” See App 1D.
====

[[v51-1-11]]

^<<v51-1-11,11>>^ being made powerful with all power to the extent of his glorious might so as to endure fully and be long-suffering with joy,

[[v51-1-12]]

^<<v51-1-12,12>>^ thanking the Father who rendered YOU suitable for YOUR participation in the inheritance of the holy ones in the light.

[[v51-1-13]]

^<<v51-1-13,13>>^ He delivered us from the authority of the darkness and transferred us into the kingdom of the Son of his love,

[[v51-1-14]]

^<<v51-1-14,14>>^ by means of whom we have our release by ransom, the forgiveness of our sins.

[[v51-1-15]]

^<<v51-1-15,15>>^ He is the image of the invisible God, the firstborn of all creation;

[[v51-1-16]]

^<<v51-1-16,16>>^ because by means of him all &#91;other&#93;^&#42;1^ things were created in the heavens and upon the earth, the things visible and the things invisible, no matter whether they are thrones or lordships or governments or authorities. All &#91;other&#93; things have been created through him and for him.

[NOTE]
====
. “All [other],” as in Lu 11:41, 42.
====

[[v51-1-17]]

^<<v51-1-17,17>>^ Also, he is before all &#91;other&#93; things and by means of him all &#91;other&#93; things were made to exist,

[[v51-1-18]]

^<<v51-1-18,18>>^ and he is the head of the body, the congregation. He is the beginning, the firstborn from the dead, that he might become the one who is first in all things;

[[v51-1-19]]

^<<v51-1-19,19>>^ because &#91;God&#93;^&#42;1^ saw good for all fullness to dwell in him,

[NOTE]
====
. Lit., “he.”
====

[[v51-1-20]]

^<<v51-1-20,20>>^ and through him to reconcile again to himself all &#91;other&#93; things by making peace through the blood &#91;he shed&#93; on the torture stake,^&#42;1^ no matter whether they are^&#42;2^ the things upon the earth or the things in the heavens.

[NOTE]
====
. See App 5C.
. “No matter whether they are,” BD*Vg; P46אACDc, “yes, through him, no matter whether they are.”
====

[[v51-1-21]]

^<<v51-1-21,21>>^ Indeed, YOU who were once alienated and enemies because YOUR minds were on the works that were wicked,

[[v51-1-22]]

^<<v51-1-22,22>>^ he now has again reconciled by means of that one’s fleshly body through &#91;his&#93; death, in order to present YOU holy and unblemished and open to no accusation before him,

[[v51-1-23]]

^<<v51-1-23,23>>^ provided, of course, that YOU continue in the faith, established on the foundation and steadfast and not being shifted away from the hope of that good news which YOU heard, and which was preached in all creation that is under heaven. Of this &#91;good news&#93; I Paul became a minister.

[[v51-1-24]]

^<<v51-1-24,24>>^ I am now rejoicing in my sufferings for YOU, and I, in my turn, am filling up what is lacking of the tribulations of the Christ in my flesh on behalf of his body, which is the congregation.

[[v51-1-25]]

^<<v51-1-25,25>>^ I became a minister of this &#91;congregation&#93; in accordance with the stewardship from God which was given me in YOUR interest to preach the word of God fully,

[[v51-1-26]]

^<<v51-1-26,26>>^ the sacred secret that was hidden from the past systems of things^&#42;1^ and from the past generations. But now it has been made manifest to his holy ones,

[NOTE]
====
. Or, “orders of things.” Gr., ai·oʹnon; Lat., saeʹcu·lis; J17,​22(Heb.), me·ʽoh·la·mimʹ, “from [the past] orders of things.”
====

[[v51-1-27]]

^<<v51-1-27,27>>^ to whom God has been pleased to make known what are the glorious riches of this sacred secret among the nations. It is Christ in union with YOU, the hope of &#91;his&#93;^&#42;1^ glory.

[NOTE]
====
. Lit., “the.”
====

[[v51-1-28]]

^<<v51-1-28,28>>^ He is the one we are publicizing, admonishing every man and teaching every man in all wisdom, that we may present every man complete^&#42;1^ in union with Christ.

[NOTE]
====
. Or, “mature; perfect.” Gr., teʹlei·on.
====

[[v51-1-29]]

^<<v51-1-29,29>>^ To this end I am indeed working hard, exerting myself in accordance with the operation of him and which is at work in me with power.

'''

xref:050-philippians/050-philippians-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossians/051-colossians-002.adoc#v51-2-0[Próximo Capítulo &#62;]