include::./index.adoc[]

[[v51-4-0]]
=== Letter to the Colossians, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v51-4-1]]

^<<v51-4-1,1>>^ YOU masters, keep dealing out what is righteous and what is fair to &#91;your&#93; slaves, knowing that YOU also have a Master in heaven.

[[v51-4-2]]

^<<v51-4-2,2>>^ Be persevering in prayer, remaining awake in it with thanksgiving,

[[v51-4-3]]

^<<v51-4-3,3>>^ at the same time praying also for us, that God may open a door of utterance to us, to speak the sacred secret about the Christ, for which, in fact, I am in prison bonds;

[[v51-4-4]]

^<<v51-4-4,4>>^ so that I shall make it manifest as I ought to speak.

[[v51-4-5]]

^<<v51-4-5,5>>^ Go on walking in wisdom toward those on the outside, buying out the opportune time for yourselves.

[[v51-4-6]]

^<<v51-4-6,6>>^ Let YOUR utterance be always with graciousness,^&#42;1^ seasoned with salt, so as to know how YOU ought to give an answer to each one.

[NOTE]
====
. Or, “with what is favorable.”
====

[[v51-4-7]]

^<<v51-4-7,7>>^ All my affairs Tychʹi·cus, &#91;my&#93; beloved brother and faithful minister and fellow slave in &#91;the&#93; Lord, will make known to YOU.

[[v51-4-8]]

^<<v51-4-8,8>>^ For the very purpose of YOUR knowing the things having to do with us and that he may comfort YOUR hearts, I am sending him to YOU

[[v51-4-9]]

^<<v51-4-9,9>>^ along with O·nesʹi·mus, my faithful and beloved brother, who is from among YOU. All the things here they will make known to YOU.

[[v51-4-10]]

^<<v51-4-10,10>>^ Ar·is·tarʹchus my fellow captive sends YOU his greetings, and so does Mark the cousin of Barʹna·bas, (concerning whom YOU received commands to welcome him if ever he comes to YOU,)

[[v51-4-11]]

^<<v51-4-11,11>>^ and Jesus who is called Justus, these being of those circumcised.^&#42;1^ Only these are my fellow workers for the kingdom of God, and these very ones have become a strengthening aid to me.

[NOTE]
====
. Lit., “out of circumcision.”
====

[[v51-4-12]]

^<<v51-4-12,12>>^ Epʹa·phras, who is from among YOU, a slave of Christ Jesus, sends YOU his greetings, always exerting himself in YOUR behalf in &#91;his&#93; prayers, that YOU may finally stand complete and with firm conviction in all the will of God.

[[v51-4-13]]

^<<v51-4-13,13>>^ I indeed bear him witness that he puts himself to great effort in behalf of YOU and of those at La·o·di·ceʹa and of those at Hi·e·rapʹo·lis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Luke the beloved physician^&#42;1^ sends YOU his greetings, and so does Deʹmas.

[NOTE]
====
. Lit., “healer.” Gr., i·a·trosʹ; Lat., meʹdi·cus.
====

[[v51-4-15]]

^<<v51-4-15,15>>^ Give my greetings to the brothers at La·o·di·ceʹa and to Nymʹpha and to the congregation at her house.

[[v51-4-16]]

^<<v51-4-16,16>>^ And when this letter has been read among YOU, arrange that it also be read in the congregation of the La·o·di·ceʹans and that YOU also read the one from La·o·di·ceʹa.

[[v51-4-17]]

^<<v51-4-17,17>>^ Also, tell Ar·chipʹpus: “Keep watching the ministry which you accepted in &#91;the&#93; Lord, that you fulfill it.”

[[v51-4-18]]

^<<v51-4-18,18>>^ &#91;Here is&#93; my greeting, Paul’s, in my own hand. Continue bearing my &#91;prison&#93; bonds in mind. The undeserved kindness be with YOU.

'''

xref:051-colossians/051-colossians-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-thessalonians/052-1-thessalonians-001.adoc#v52-1-0[Próximo Capítulo &#62;]