include::./index.adoc[]

[[v38-11-0]]
=== Zechariah, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-11-1]]

^<<v38-11-1,1>>^ “Open up your doors, O Lebʹa·non, that a fire may devour among your cedars.

[[v38-11-2]]

^<<v38-11-2,2>>^ Howl, O juniper tree, for the cedar has fallen; because the majestic ones themselves have been despoiled! Howl, YOU massive trees of Baʹshan, for the impenetrable^&#42;1^ forest has come down!

[NOTE]
====
. Or, “fortified; inaccessible.” Mmargin, “interdicted.”
====

[[v38-11-3]]

^<<v38-11-3,3>>^ Listen! The howling of shepherds, for their majesty has been despoiled. Listen! The roaring of maned young lions, for the proud &#91;thickets&#93;^&#42;1^ along the Jordan have been despoiled.

[NOTE]
====
. “Proud [thickets].” Or, “high [trees].” Lit., “pride.”
====

[[v38-11-4]]

^<<v38-11-4,4>>^ “This is what Jehovah my God^&#42;1^ has said, ‘Shepherd the flock &#91;meant&#93; for the killing,

[NOTE]
====
. “Jehovah my God,” M(Heb., Yehwahʹ ʼElo·haiʹ)TSyVg; Gr., Kyʹri·os pan·to·kraʹtor, “Jehovah Almighty.”
====

[[v38-11-5]]

^<<v38-11-5,5>>^ the buyers of which proceed to kill &#91;them&#93; although they are not held guilty. And those who are selling them say: “May Jehovah be blessed, while I shall gain riches.” And their own shepherds do not show any compassion upon them.’

[[v38-11-6]]

^<<v38-11-6,6>>^ “‘For I shall show compassion no more upon the inhabitants of the land,’ is the utterance of Jehovah. ‘So here I am causing mankind^&#42;1^ to find themselves, each one in the hand of his companion and in the hand of his king; and they will certainly crush to pieces the land, and I shall do no delivering out of their hand.’”

[NOTE]
====
. Or, “earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v38-11-7]]

^<<v38-11-7,7>>^ And I proceeded to shepherd the flock &#91;meant&#93; for the killing, in YOUR behalf, O afflicted ones of the flock.^&#42;1^ So I took for myself two staffs. The one I called Pleasantness, and the other I called Union,^&#42;2^ and I went shepherding the flock.

[NOTE]
====
. According to M; by a regrouping and a change in vowel pointing, “in behalf of the tradesmen of the flock.”
. Lit., “Binders.” Heb., Cho·velimʹ; that which results in a union of things.
====

[[v38-11-8]]

^<<v38-11-8,8>>^ And I finally effaced three shepherds in one lunar month, as my soul gradually became impatient with them, and also their own soul felt a loathing toward me.

[[v38-11-9]]

^<<v38-11-9,9>>^ At length I said: “I shall not keep shepherding YOU.^&#42;1^ The one that is dying, let her die. And the one that is being effaced, let her be effaced. And as for the ones left remaining, let them devour, each one the flesh of her companion.”

[NOTE]
====
. “You,” masc. pl.
====

[[v38-11-10]]

^<<v38-11-10,10>>^ So I took my staff Pleasantness and cut it to pieces, in order to break my covenant that I had concluded with all the peoples.

[[v38-11-11]]

^<<v38-11-11,11>>^ And it came to be broken in that day, and the afflicted ones of the flock^&#42;1^ who were watching me got to know in this way that it was the word of Jehovah.

[NOTE]
====
. “The afflicted ones of the flock,” M. See vs 7 ftn, “Flock.”
====

[[v38-11-12]]

^<<v38-11-12,12>>^ Then I said to them:^&#42;1^ “If it is good in YOUR eyes, give &#91;me&#93; my wages; but if not, refrain.” And they proceeded to pay^&#42;2^ my wages, thirty pieces of silver.

[NOTE]
====
. “Them,” masc.
. Lit., “weigh out.”
====

[[v38-11-13]]

^<<v38-11-13,13>>^ At that, Jehovah said to me: “Throw it to the treasury^&#42;1^—the majestic value with which I have been valued from their standpoint.” Accordingly I took the thirty pieces of silver and threw it into the treasury at the house of Jehovah.

[NOTE]
====
. “Treasury,” by a correction; M, “founder,” or, “potter”; LXX, “smelting furnace”; Vg, “statuary.”
====

[[v38-11-14]]

^<<v38-11-14,14>>^ Then I cut in pieces my second staff, the Union, in order to break the brotherhood between Judah and Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ And Jehovah went on to say to me: “Take yet for yourself the implements of a useless shepherd.

[[v38-11-16]]

^<<v38-11-16,16>>^ For here I am letting a shepherd rise up in the land. To the &#91;sheep&#93;^&#42;1^ being effaced he will give no attention. The young one he will not seek, and the broken &#91;sheep&#93; he will not heal. The one stationing herself^&#42;2^ he will not supply &#91;with food&#93;, and the flesh of the fat one he will eat, and the hoofs of the &#91;sheep&#93;^&#42;3^ he will tear off.

[NOTE]
====
. Lit., “To the ones,” fem., referring to symbolic sheep.
. “The one made sick,” by a correction; by a different correction, “The hungry one.”
. Lit., “of them,” fem.
====

[[v38-11-17]]

^<<v38-11-17,17>>^ Woe to my valueless shepherd, who is leaving the flock! A sword will be upon his arm and upon his right eye. His own arm will without fail dry up, and his own right eye will without fail grow dim.”

'''

xref:038-zechariah/038-zechariah-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zechariah/038-zechariah-012.adoc#v38-12-0[Próximo Capítulo &#62;]