include::./index.adoc[]

[[v38-7-0]]
=== Zechariah, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-7-1]]

^<<v38-7-1,1>>^ Furthermore, it came about that in the fourth year of Da·riʹus the king the word of Jehovah occurred to Zech·a·riʹah, on the fourth &#91;day&#93; of the ninth month, &#91;that is,&#93; in Chisʹlev.^&#42;1^

[NOTE]
====
. The postexilic name of the ninth Jewish lunar month, which falls within November and December. See App 8B.
====

[[v38-7-2]]

^<<v38-7-2,2>>^ And Bethʹel proceeded to send Shar·eʹzer and Reʹgem-melʹech and his men^&#42;1^ to soften the face of Jehovah,

[NOTE]
====
. “And his men.” Heb., wa·ʼana·shavʹ, pl. of ʼish.
====

[[v38-7-3]]

^<<v38-7-3,3>>^ saying to the priests who belonged to the house of Jehovah of armies, and to the prophets, even saying: “Shall I weep in the fifth month, practicing an abstinence,^&#42;1^ the way I have done these O how many years?”

[NOTE]
====
. “Practicing an abstinence.” Heb., hin·na·zerʹ, in the infinitive absolute, indefinite as to time and impersonal.
====

[[v38-7-4]]

^<<v38-7-4,4>>^ And the word of Jehovah of armies continued to occur to me, saying:

[[v38-7-5]]

^<<v38-7-5,5>>^ “Say to all the people of the land^&#42;1^ and to the priests, ‘When YOU fasted and there was a wailing in the fifth &#91;month&#93; and in the seventh &#91;month&#93;, and this for seventy years, did YOU really fast to me, even me?

[NOTE]
====
. “People of the land.” Heb., ʽam ha·ʼaʹrets. See Hag 2:4 ftn.
====

[[v38-7-6]]

^<<v38-7-6,6>>^ And when YOU would eat and when YOU would drink, were not YOU the ones doing the eating, and were not YOU the ones doing the drinking?

[[v38-7-7]]

^<<v38-7-7,7>>^ &#91;Should YOU&#93; not &#91;obey&#93; the words that Jehovah called out by means of the former prophets, while Jerusalem happened to be inhabited, and at ease, with her cities all around her, and &#91;while&#93; the Negʹeb^&#42;1^ and the She·pheʹlah^&#42;2^ were inhabited?’”

[NOTE]
====
. Or, “the south,” that is, the southern part of the Promised Land.
. Or, “the lowland.”
====

[[v38-7-8]]

^<<v38-7-8,8>>^ And the word of Jehovah continued to occur to Zech·a·riʹah, saying:

[[v38-7-9]]

^<<v38-7-9,9>>^ “This is what Jehovah of armies has said, ‘With true justice^&#42;1^ do YOUR judging; and carry on with one another loving-kindness^&#42;2^ and mercies;

[NOTE]
====
. Lit., “[With] the judgment of truth.”
. Or, “and . . . loyal love.” Heb., wecheʹsedh.
====

[[v38-7-10]]

^<<v38-7-10,10>>^ and defraud no widow or fatherless boy, no alien resident or afflicted one, and scheme out nothing bad against one another in YOUR hearts.’

[[v38-7-11]]

^<<v38-7-11,11>>^ But they kept refusing to pay attention, and they kept giving a stubborn shoulder, and their ears they made too unresponsive to hear.

[[v38-7-12]]

^<<v38-7-12,12>>^ And their heart they set as an emery stone to keep from obeying the law and the words that Jehovah of armies sent by his spirit, by means of the former prophets; so that there occurred great indignation on the part of Jehovah of armies.”

[[v38-7-13]]

^<<v38-7-13,13>>^ “‘And so it occurred that, just as he called and they did not listen, so they would call and I would not listen,’ Jehovah of armies has said.

[[v38-7-14]]

^<<v38-7-14,14>>^ ‘And I proceeded tempestuously to hurl them throughout all the nations that they had not known; and the land itself has been left desolate behind them, with no one passing through and with no one returning; and they proceeded to make the desirable land an object of astonishment.’”

'''

xref:038-zechariah/038-zechariah-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zechariah/038-zechariah-008.adoc#v38-8-0[Próximo Capítulo &#62;]