include::./index.adoc[]

[[v38-6-0]]
=== Zechariah, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-6-1]]

^<<v38-6-1,1>>^ Then I raised my eyes again and saw; and, look! there were four chariots coming forth from between two mountains, and the mountains were copper mountains.

[[v38-6-2]]

^<<v38-6-2,2>>^ In the first chariot there were red horses; and in the second chariot, black horses.

[[v38-6-3]]

^<<v38-6-3,3>>^ And in the third chariot there were white horses; and in the fourth chariot, horses speckled, parti-colored.

[[v38-6-4]]

^<<v38-6-4,4>>^ And I proceeded to answer and say to the angel^&#42;1^ who was speaking with me: “What are these, my lord?”^&#42;2^

[NOTE]
====
. Or, “messenger.”
. “My lord.” Heb., ʼadho·niʹ; Gr., kyʹri·e; Lat., doʹmi·ne.
====

[[v38-6-5]]

^<<v38-6-5,5>>^ So the angel answered and said to me: “These are the four spirits^&#42;1^ of the heavens that are going forth after having taken their station before the Lord^&#42;2^ of the whole earth.

[NOTE]
====
. “Spirits.” Heb., ru·chohthʹ; LXXVg, “winds.” See Ge 1:2 ftn, “Force.”
. “Lord of.” Heb., ʼAdhohnʹ; Gr., Ky·riʹoi; Lat., Do·mi·na·toʹre.
====

[[v38-6-6]]

^<<v38-6-6,6>>^ As for the one^&#42;1^ in which the black horses are, they are going forth to the land of the north; and as for the white ones, they must go forth to behind the sea;^&#42;2^ and as for the speckled ones, they must go forth to the land of the south.^&#42;3^

[NOTE]
====
. “The one,” fem., referring to the chariot, fem.
. “Behind the sea,” by a slight change; MLXXVg, “after them”; not in the same direction but west toward the Great Sea, the Mediterranean.
. “The south,” M(Heb., hat·teh·manʹ)TLXXSyVg.
====

[[v38-6-7]]

^<<v38-6-7,7>>^ And as for the parti-colored ones, they must go forth and keep seeking &#91;where&#93; to go, in order to walk about in the earth.” Then he said: “Go, walk about in the earth.” And they^&#42;1^ began walking about in the earth.

[NOTE]
====
. “They,” fem., possibly referring to spirits.
====

[[v38-6-8]]

^<<v38-6-8,8>>^ And he proceeded to cry out to me and speak to me, saying: “See, those going forth to the land of the north are the ones that have caused the spirit of Jehovah^&#42;1^ to rest in the land of the north.”

[NOTE]
====
. “The spirit of Jehovah,” according to BHK and BHS ftns; MSyVg, “my spirit”; LXX, “my anger”; T, “[do] my will.” See App 1A.
====

[[v38-6-9]]

^<<v38-6-9,9>>^ And the word of Jehovah continued to occur to me, saying:

[[v38-6-10]]

^<<v38-6-10,10>>^ “Let there be a taking of something from the exiled people, &#91;even&#93; from Helʹdai and from To·biʹjah and from Je·daʹiah; and you yourself must come in that day, and you must come into the house of Jo·siʹah the son of Zeph·a·niʹah &#91;with these&#93; who have come from Babylon.^&#42;1^

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v38-6-11]]

^<<v38-6-11,11>>^ And you must take silver and gold and make a grand crown^&#42;1^ and put &#91;it&#93; upon the head of Joshua^&#42;2^ the son of Je·hozʹa·dak the high priest.

[NOTE]
====
. “A grand crown,” T; LXXmssSy, “a crown”; MLXXVg, “crowns.” Compare vs 14 ftn, “Crown.”
. See 3:1 ftn, “Joshua.”
====

[[v38-6-12]]

^<<v38-6-12,12>>^ And you must say to him,
“‘This is what Jehovah of armies has said: “Here is the man^&#42;1^ whose name is Sprout. And from his own place he will sprout, and he will certainly build the temple^&#42;2^ of Jehovah.

[NOTE]
====
. “Here is the man.” Heb., hin·neh-ʼishʹ; Gr., I·douʹ a·nerʹ; Lat., ecʹce vir. See Joh 19:5.
. “The temple of.” Heb., heh·khalʹ; Lat., temʹplum. See Mt 23:16 ftn.
====

[[v38-6-13]]

^<<v38-6-13,13>>^ And he himself will build the temple of Jehovah, and he, for his part, will carry &#91;the&#93; dignity; and he must sit down and rule on his throne, and he must become a priest upon his throne, and the very counsel of peace will prove to be between both of them.

[[v38-6-14]]

^<<v38-6-14,14>>^ And the grand crown^&#42;1^ itself will come to belong to Heʹlem^&#42;2^ and to To·biʹjah and to Je·daʹiah and to Hen^&#42;3^ the son of Zeph·a·niʹah as a memorial in the temple of Jehovah.

[NOTE]
====
. “Grand crown.” Lit., “crowns,” pl. to denote excellence and accompanied by a sing. verb.
. “Helem,” MTVg; Sy, “Heldai.”
. “Hen,” MTVg; Vgc, “Hem”; Sy, “Josiah.”
====

[[v38-6-15]]

^<<v38-6-15,15>>^ And those who are far away will come and actually build in the temple of Jehovah.” And YOU people will have to know that Jehovah of armies himself has sent me to YOU. And it must occur—if YOU will without fail listen to the voice of Jehovah YOUR God.’”

'''

xref:038-zechariah/038-zechariah-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zechariah/038-zechariah-007.adoc#v38-7-0[Próximo Capítulo &#62;]