include::./index.adoc[]

[[v38-2-0]]
=== Zechariah, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-2-1]]

^<<v38-2-1,1>>^ And I proceeded to raise my eyes and see; and, look! there was a man,^&#42;1^ and in his hand a measuring rope.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v38-2-2]]

^<<v38-2-2,2>>^ So I said: “Where are you going?”
In turn he said to me: “To measure Jerusalem, in order to see what her breadth amounts to and what her length amounts to.”

[[v38-2-3]]

^<<v38-2-3,3>>^ And, look! the angel who was speaking with me was going forth, and there was another angel going forth to meet him.

[[v38-2-4]]

^<<v38-2-4,4>>^ Then he said to him: “Run, speak to the young man over there, saying, ‘“As open rural country Jerusalem will be inhabited, because of the multitude of men and domestic animals in the midst of her.

[[v38-2-5]]

^<<v38-2-5,5>>^ And I myself shall become to her,” is the utterance of Jehovah, “a wall of fire all around, and a glory is what I shall become^&#42;1^ in the midst of her.”’”

[NOTE]
====
. Or, “I shall prove to be.” Heb., ʼeh·yehʹ. See Ex 3:14 ftn.
====

[[v38-2-6]]

^<<v38-2-6,6>>^ “Hey there! Hey there! Flee, then, YOU people, from the land of the north,” is the utterance of Jehovah.
“For in the direction of the four winds^&#42;1^ of the heavens I have spread YOU people abroad,” is the utterance of Jehovah.

[NOTE]
====
. “Winds.” Heb., ru·chohthʹ, pl.; Gr., a·neʹmon; Lat., venʹtos. See Ge 1:2 ftn, “Force.”
====

[[v38-2-7]]

^<<v38-2-7,7>>^ “Hey there, Zion! Make your escape, you who are dwelling with the daughter of Babylon.^&#42;1^

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v38-2-8]]

^<<v38-2-8,8>>^ For this is what Jehovah of armies has said, ‘Following after &#91;the&#93; glory he has sent me to the nations that were despoiling YOU people; for he that is touching YOU is touching my eyeball.^&#42;1^

[NOTE]
====
. “My eyeball” was the original reading. The Sopherim changed the text to read “his eyeball.” See App 2B.
====

[[v38-2-9]]

^<<v38-2-9,9>>^ For here I am waving my hand against them, and they will have to become spoil to their slaves.’ And YOU people will certainly know that Jehovah of armies himself has sent me.

[[v38-2-10]]

^<<v38-2-10,10>>^ “Cry out loudly and rejoice, O daughter of Zion; for here I am coming, and I will reside in the midst of you,” is the utterance of Jehovah.

[[v38-2-11]]

^<<v38-2-11,11>>^ “And many nations will certainly become joined to Jehovah in that day, and they will actually become my people; and I will reside in the midst of you.”^&#42;1^ And you will have to know that Jehovah of armies himself has sent me to you.

[NOTE]
====
. “You,” fem. sing., addressed to the “daughter of Zion.”
====

[[v38-2-12]]

^<<v38-2-12,12>>^ And Jehovah will certainly take possession of Judah as his portion upon the holy ground, and he must yet choose Jerusalem.

[[v38-2-13]]

^<<v38-2-13,13>>^ Keep silence, all flesh, before Jehovah, for he has aroused himself from his holy dwelling.

'''

xref:038-zechariah/038-zechariah-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zechariah/038-zechariah-003.adoc#v38-3-0[Próximo Capítulo &#62;]