include::./index.adoc[]

[[v38-4-0]]
=== Zechariah, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-4-1]]

^<<v38-4-1,1>>^ And the angel who was speaking with me proceeded to come back and wake me up, like a man that is awakened from his sleep.

[[v38-4-2]]

^<<v38-4-2,2>>^ Then he said to me: “What are you seeing?”
So I said: “I have seen, and, look! there is a lampstand, all of it of gold, with a bowl on top of it. And its seven lamps are upon it, even seven; and the lamps that are at the top of it have seven pipes.

[[v38-4-3]]

^<<v38-4-3,3>>^ And there are two olive trees alongside it, one on the right side of the bowl and one on its left side.”

[[v38-4-4]]

^<<v38-4-4,4>>^ Then I answered and said to the angel who was speaking with me, saying: “What do these &#91;things&#93; mean, my lord?”^&#42;1^

[NOTE]
====
. “My lord.” Heb., ʼadho·niʹ.
====

[[v38-4-5]]

^<<v38-4-5,5>>^ So the angel who was speaking with me answered and said to me: “Do you not really know what these things mean?”
In turn I said: “No, my lord.”

[[v38-4-6]]

^<<v38-4-6,6>>^ Accordingly he answered and said to me: “This is the word of Jehovah to Ze·rubʹba·bel, saying, ‘“Not by a military force,^&#42;1^ nor by power,^&#42;2^ but by my spirit,”^&#42;3^ Jehovah of armies has said.

[NOTE]
====
. Or, “by vital energy.” Heb., vechaʹyil.
. “By power.” Heb., vekhoʹach.
. “By my spirit.” Heb., beru·chiʹ; Gr., pneuʹma·ti; Lat., spiʹri·tu. See Ge 1:2 ftn, “Force.”
====

[[v38-4-7]]

^<<v38-4-7,7>>^ Who are you, O great mountain? Before Ze·rubʹba·bel &#91;you will become&#93; a level land. And he will certainly bring forth the headstone. There will be shoutings to it: “How charming! How charming!”’”

[[v38-4-8]]

^<<v38-4-8,8>>^ And the word of Jehovah continued to occur to me, saying:

[[v38-4-9]]

^<<v38-4-9,9>>^ “The very hands of Ze·rubʹba·bel have laid the foundation of this house, and his own hands will finish &#91;it&#93;. And you will have to know that Jehovah of armies himself has sent me to YOU people.

[[v38-4-10]]

^<<v38-4-10,10>>^ For who has despised the day of small things? And they will certainly rejoice and see the plummet^&#42;1^ in the hand of Ze·rubʹba·bel. These seven are the eyes of Jehovah. They are roving about in all the earth.”

[NOTE]
====
. Lit., “the stone [or, weight], the tin.” Heb., ha·ʼeʹven hab·bedhilʹ.
====

[[v38-4-11]]

^<<v38-4-11,11>>^ And I proceeded to answer and say to him: “What do these two olive trees on the right side of the lampstand and on its left side mean?”

[[v38-4-12]]

^<<v38-4-12,12>>^ Then I answered the second time and said to him: “What are the two bunches of twigs^&#42;1^ of the olive trees that, by means of the two golden tubes, are pouring forth from within themselves the golden &#91;liquid&#93;?”

[NOTE]
====
. “Bunches of twigs of.” Heb., shib·balehʹ, pl. Compare similar word in Jg 12:6 ftn, “Shibboleth.”
====

[[v38-4-13]]

^<<v38-4-13,13>>^ So he said to me: “Do you not really know what these &#91;things&#93; mean?”
In turn I said: “No, my lord.”

[[v38-4-14]]

^<<v38-4-14,14>>^ Accordingly he said: “These are the two anointed ones^&#42;1^ who are standing alongside the Lord of the whole earth.”^&#42;2^

[NOTE]
====
. Lit., “sons of the oil,” MVg; LXXSy, “sons of fattiness”; T, “sons of princes.”
. “Lord of the whole earth.” Heb., ʼAdhohnʹ kol-ha·ʼaʹrets.
====

'''

xref:038-zechariah/038-zechariah-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zechariah/038-zechariah-005.adoc#v38-5-0[Próximo Capítulo &#62;]