include::./index.adoc[]

[[v38-12-0]]
=== Zechariah, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-12-1]]

^<<v38-12-1,1>>^ A pronouncement:
“The word of Jehovah concerning Israel,” is the utterance of Jehovah, the One who is stretching out &#91;the&#93; heavens and laying the foundation of &#91;the&#93; earth and forming the spirit of man^&#42;1^ inside him.

[NOTE]
====
. “The spirit of man.” Heb., ru·ach-ʼa·dhamʹ.
====

[[v38-12-2]]

^<<v38-12-2,2>>^ “Here I am making Jerusalem a bowl &#91;causing&#93; reeling to all the peoples round about; and also against Judah he will come to be in the siege, &#91;even&#93; against Jerusalem.

[[v38-12-3]]

^<<v38-12-3,3>>^ And it must occur in that day &#91;that&#93; I shall make Jerusalem a burdensome stone to all the peoples. All those lifting it will without fail get severe scratches for themselves; and against her all the nations of the earth will certainly be gathered.

[[v38-12-4]]

^<<v38-12-4,4>>^ In that day,” is the utterance of Jehovah, “I shall strike every horse with bewilderment and its rider with madness; and upon the house of Judah I shall open my eyes, and every horse of the peoples I shall strike with loss of sight.

[[v38-12-5]]

^<<v38-12-5,5>>^ And the sheiks of Judah will have to say in their heart, ‘The inhabitants of Jerusalem are a strength to me by Jehovah of armies their God.’^&#42;1^

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v38-12-6]]

^<<v38-12-6,6>>^ In that day I shall make the sheiks of Judah like a firepot among trees and like a fiery torch in a row of newly cut grain, and they must devour on the right &#91;hand&#93; and on the left all the peoples round about; and Jerusalem must yet be inhabited in her &#91;own&#93; place, in Jerusalem.

[[v38-12-7]]

^<<v38-12-7,7>>^ “And Jehovah will certainly save the tents of Judah first, to the end that the beauty of the house of David and the beauty of the inhabitants of Jerusalem may not become too great over Judah.

[[v38-12-8]]

^<<v38-12-8,8>>^ In that day Jehovah will be a defense around the inhabitants of Jerusalem; and the one that is stumbling among them must become in that day like David, and the house of David like God,^&#42;1^ like Jehovah’s angel before them.

[NOTE]
====
. Or, “godlike ones.” Heb., keʼ·lo·himʹ, pl.; LXX, “like God’s house”; Lat., quaʹsi Deʹi. Compare Ps 8:5 ftn.
====

[[v38-12-9]]

^<<v38-12-9,9>>^ And it must occur in that day &#91;that&#93; I shall seek to annihilate all the nations that are coming against Jerusalem.

[[v38-12-10]]

^<<v38-12-10,10>>^ “And I will pour out upon the house of David and upon the inhabitants of Jerusalem the spirit^&#42;1^ of favor and entreaties, and they will certainly look to the One whom^&#42;2^ they pierced through, and they will certainly wail over Him as in the wailing over an only &#91;son&#93;; and there will be a bitter lamentation over him as when there is bitter lamentation over the firstborn &#91;son&#93;.

[NOTE]
====
. “Spirit of.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tum.
. “To the One whom,” Th and Joh 19:37; MVg, “to me whom.”
====

[[v38-12-11]]

^<<v38-12-11,11>>^ In that day the wailing in Jerusalem will be great, like the wailing of Ha·dad·rimʹmon in the valley plain of Me·gidʹdo.^&#42;1^

[NOTE]
====
. “Megiddo.” Heb., Meghid·dohnʹ; Lat., Ma·gedʹdon. Compare Re 16:16 ftn, “Har–Magedon.”
====

[[v38-12-12]]

^<<v38-12-12,12>>^ And the land^&#42;1^ will certainly wail, each family by itself;^&#42;2^ the family of the house of David by itself, and their women by themselves; the family of the house of Nathan by itself, and their women by themselves;

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
. Lit., “families families apart.”
====

[[v38-12-13]]

^<<v38-12-13,13>>^ the family of the house of Leʹvi by itself, and their women by themselves; the family of the Shimʹe·ites by itself, and their women by themselves;

[[v38-12-14]]

^<<v38-12-14,14>>^ all the families that are left remaining, each family by itself, and their women by themselves.

'''

xref:038-zechariah/038-zechariah-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zechariah/038-zechariah-013.adoc#v38-13-0[Próximo Capítulo &#62;]