include::./index.adoc[]

[[v38-3-0]]
=== Zechariah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-3-1]]

^<<v38-3-1,1>>^ And he proceeded to show me Joshua^&#42;1^ the high priest standing before the angel^&#42;2^ of Jehovah, and Satan^&#42;3^ standing at his right hand in order to resist him.

[NOTE]
====
. “Joshua.” Heb., Yehoh·shuʹaʽ; LXXVg, “Jesus.” See Heb 4:8 ftn, “Joshua.”
. Or, “the messenger.”
. Or, “and the Resister.” Lit., “and the Satan.” Heb., wehas·Sa·tanʹ; Lat., Saʹtan; Gr., Di·aʹbo·los. See Job 1:6 ftn, “Satan.”
====

[[v38-3-2]]

^<<v38-3-2,2>>^ Then &#91;the angel of&#93; Jehovah^&#42;1^ said to Satan: “Jehovah rebuke you, O Satan, yes, Jehovah rebuke you, he who is choosing Jerusalem! Is this one not a log snatched out of the fire?”

[NOTE]
====
. “The angel (messenger) of Jehovah,” Sy; MLXXVg, “Jehovah.”
====

[[v38-3-3]]

^<<v38-3-3,3>>^ Now as for Joshua, he happened to be clothed in befouled^&#42;1^ garments and standing before the angel.

[NOTE]
====
.  Or, “filthy,” that is, from excrement.
====

[[v38-3-4]]

^<<v38-3-4,4>>^ Then he answered and said to those standing before him: “Remove the befouled garments from upon him.” And he went on to say to him: “See, I have caused your error to pass away from upon you, and there is a clothing of you with robes of state.”

[[v38-3-5]]

^<<v38-3-5,5>>^ At that I said:^&#42;1^ “Let them put a clean turban upon his head.” And they proceeded to put the clean turban upon his head and to clothe him with garments; and the angel of Jehovah^&#42;2^ was standing by.

[NOTE]
====
. “At that I said,” M; TSyVg, “And he said”; LXX omits.
. See App 1C §2.
====

[[v38-3-6]]

^<<v38-3-6,6>>^ And the angel of Jehovah^&#42;1^ began to bear witness to Joshua, saying:

[NOTE]
====
. See App 1C §2.
====

[[v38-3-7]]

^<<v38-3-7,7>>^ “This is what Jehovah^&#42;1^ of armies has said, ‘If it is in my ways that you will walk, and if it is my obligation that you will keep, then also it will be you that will judge my house and also keep my courtyards; and I shall certainly give you free access among these who are standing by.’

[NOTE]
====
. See App 1C §2.
====

[[v38-3-8]]

^<<v38-3-8,8>>^ “‘Hear, please, O Joshua the high priest, you and your companions who are sitting before you, for they are men^&#42;1^ &#91;serving&#93; as portents;^&#42;2^ for here I am bringing in my servant Sprout!^&#42;3^

[NOTE]
====
. “Men.” Heb., ʼan·shehʹ, pl. of ʼish.
. Lit., “men of portent (token; wonder).”
. “Sprout.” Heb., Tseʹmach. Compare Isa 4:2 ftn, “Sprout”; Jer 23:5; Jer 33:15.
====

[[v38-3-9]]

^<<v38-3-9,9>>^ For, look! the stone that I have put before Joshua! Upon the one stone there are seven eyes.^&#42;1^ Here I am engraving its engraving,’ is the utterance of Jehovah of armies, ‘and I will take away the error of that land in one day.’

[NOTE]
====
. Or, “seven pairs of eyes,” as the word for “eyes” is dual in number. Heb., shiv·ʽahʹ ʽeh·naʹyim. See App 3B.
====

[[v38-3-10]]

^<<v38-3-10,10>>^ “‘In that day,’ is the utterance of Jehovah of armies, ‘YOU will call, each one to the other, while under &#91;the&#93; vine and while under &#91;the&#93; fig tree.’”

'''

xref:038-zechariah/038-zechariah-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zechariah/038-zechariah-004.adoc#v38-4-0[Próximo Capítulo &#62;]