include::./index.adoc[]

[[v38-14-0]]
=== Zechariah, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-14-1]]

^<<v38-14-1,1>>^ “Look! There is a day coming, belonging to Jehovah, and the spoil of you^&#42;1^ will certainly be apportioned out in the midst of you.

[NOTE]
====
. “You,” fem. sing., referring to the “city” in vs 2.
====

[[v38-14-2]]

^<<v38-14-2,2>>^ And I shall certainly gather all the nations against Jerusalem for the war; and the city will actually be captured and the houses be pillaged, and the women themselves will be raped. And half of the city must go forth into the exile; but as for the remaining ones^&#42;1^ of the people, they will not be cut off from the city.

[NOTE]
====
. Or, “the remnant; the rest.”
====

[[v38-14-3]]

^<<v38-14-3,3>>^ “And Jehovah will certainly go forth and war against those nations as in the day of his warring, in the day of fight.

[[v38-14-4]]

^<<v38-14-4,4>>^ And his feet will actually stand in that day upon the mountain of the olive trees,^&#42;1^ which is in front of Jerusalem, on the east; and the mountain of the olive trees must be split at its middle, from the sunrising and to the west.^&#42;2^ There will be a very great valley; and half of the mountain will actually be moved to the north, and half of it to the south.^&#42;3^

[NOTE]
====
. Or, “the Mount of Olives.”
. Lit., “the sea,” that is, the Mediterranean Sea to the west.
. Or, “Negeb.”
====

[[v38-14-5]]

^<<v38-14-5,5>>^ And YOU people will certainly flee to the valley of my mountains; because the valley of &#91;the&#93; mountains will reach all the way to Aʹzel.^&#42;1^ And YOU will have to flee, just as YOU fled because of the &#91;earth&#93;quake in the days of Uz·ziʹah the king of Judah. And Jehovah my God will certainly come, all the holy ones being with him.^&#42;2^

[NOTE]
====
. A site near Jerusalem. There may be an echoing of the name Azel in that of the Wadi Yasul, which is an afflux to the Kidron Valley from the Mount of Olives.
. “Him,” TLXXSyVg and many Heb. mss; M, “you.”
====

[[v38-14-6]]

^<<v38-14-6,6>>^ “And it must occur in that day &#91;that&#93; there will prove to be no precious light—things will be congealed.

[[v38-14-7]]

^<<v38-14-7,7>>^ And it must become one day that is known as belonging to Jehovah. It will not be day, neither will it be night; and it must occur &#91;that&#93; at evening time it will become light.

[[v38-14-8]]

^<<v38-14-8,8>>^ And it must occur in that day &#91;that&#93; living waters will go forth from Jerusalem, half of them to the eastern sea^&#42;1^ and half of them to the western sea.^&#42;2^ In summer and in winter^&#42;3^ it will occur.

[NOTE]
====
. Or, “former sea.”
. Or, “hinder sea,” that is, to one’s back when facing east.
. Or, “autumn,” that is, the beginning of winter.
====

[[v38-14-9]]

^<<v38-14-9,9>>^ And Jehovah must become king over all the earth.^&#42;1^ In that day Jehovah will prove to be one, and his name one.

[NOTE]
====
. Or, “the land.” Heb., ha·ʼaʹrets.
====

[[v38-14-10]]

^<<v38-14-10,10>>^ “The whole land will be changed like the Arʹa·bah,^&#42;1^ from Geʹba to Rimʹmon to the south^&#42;2^ of Jerusalem; and she must rise and become inhabited in her place, from the Gate of Benjamin all the way to the place of the First Gate, all the way to the Corner Gate, and &#91;from&#93; the Tower of Ha·nanʹel all the way to the press vats of the king.

[NOTE]
====
. Or, “desert plain.” See De 1:1 ftn, “Plains.”
. “South.” Heb., neʹghev.
====

[[v38-14-11]]

^<<v38-14-11,11>>^ And people will certainly inhabit her; and there will occur no more any banning &#91;to destruction&#93;, and Jerusalem must be inhabited in security.

[[v38-14-12]]

^<<v38-14-12,12>>^ “And this is what will prove to be the scourge with which Jehovah will scourge all the peoples that will actually do military service against Jerusalem: There will be a rotting away of one’s flesh, while one is standing upon one’s feet; and one’s very eyes will rot away in their sockets, and one’s very tongue will rot away in one’s mouth.

[[v38-14-13]]

^<<v38-14-13,13>>^ “And it must occur in that day &#91;that&#93; confusion from Jehovah will become widespread among them; and they will actually grab hold, each one of the hand of his companion, and his hand will actually come up against the hand of his companion.

[[v38-14-14]]

^<<v38-14-14,14>>^ And Judah itself also will be warring at Jerusalem; and the wealth of all the nations round about will certainly be gathered, gold and silver and garments in excessive abundance.

[[v38-14-15]]

^<<v38-14-15,15>>^ “And this is how the scourge of the horse, the mule, the camel, and the male ass, and every sort of domestic animal that happens to be in those camps, will prove to be, like this scourge.

[[v38-14-16]]

^<<v38-14-16,16>>^ “And it must occur &#91;that&#93;, as regards everyone who is left remaining out of all the nations that are coming against Jerusalem, they must also go up from year to year to bow down to the King, Jehovah of armies, and to celebrate the festival of the booths.

[[v38-14-17]]

^<<v38-14-17,17>>^ And it must occur that, as regards anyone that does not come up out of the families of the earth to Jerusalem to bow down to the King, Jehovah of armies, even upon them no pouring rain will occur.

[[v38-14-18]]

^<<v38-14-18,18>>^ And if the family of Egypt itself does not come up and does not actually enter, upon them also there shall be none. The scourge will occur^&#42;1^ with which Jehovah scourges the nations that do not come up to celebrate the festival of the booths.

[NOTE]
====
. “Upon them also there will be the calamity (scourge),” LXXSy.
====

[[v38-14-19]]

^<<v38-14-19,19>>^ This itself will prove to be the &#91;punishment for the&#93; sin of Egypt and the sin of all the nations that do not come up to celebrate the festival of the booths.

[[v38-14-20]]

^<<v38-14-20,20>>^ “In that day there will prove to be upon the bells of the horse ‘Holiness belongs to Jehovah!’ And the widemouthed cooking pots in the house of Jehovah must become like the bowls before the altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ And every widemouthed cooking pot in Jerusalem and in Judah must become something holy belonging to Jehovah of armies, and all those who are sacrificing must come in and take from them and must do boiling in them. And there will no more prove to be a Caʹnaan·ite^&#42;1^ in the house of Jehovah of armies in that day.”

[NOTE]
====
. Or, “tradesman,” as in TVg; Heb., Khena·ʽaniʹ.
====

'''

xref:038-zechariah/038-zechariah-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malachi/039-malachi-001.adoc#v39-1-0[Próximo Capítulo &#62;]