include::./index.adoc[]

[[v38-10-0]]
=== Zechariah, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-10-1]]

^<<v38-10-1,1>>^ “Make YOUR requests of Jehovah for rain in the time of the spring rain, even of Jehovah who is making the storm clouds, and &#91;who&#93; gives a downpour of rain to them, to each one vegetation in the field.

[[v38-10-2]]

^<<v38-10-2,2>>^ For the teraphim themselves have spoken what is uncanny;^&#42;1^ and the practicers of divination, for their part, have visioned falsehood, and valueless dreams are what they keep speaking, and in vain they try to comfort. That is why they will certainly depart like a flock; they will become afflicted, because there is no shepherd.

[NOTE]
====
. Or, “hurtful.”
====

[[v38-10-3]]

^<<v38-10-3,3>>^ “Against the shepherds my anger has grown hot, and against the goatlike leaders I shall hold an accounting; for Jehovah of armies has turned his attention to his drove, the house of Judah, and has made them like his horse of dignity in the battle.

[[v38-10-4]]

^<<v38-10-4,4>>^ Out of him is the keyman,^&#42;1^ out of him is the supporting ruler,^&#42;2^ out of him is the battle bow; out of him goes forth every taskmaster, all together.

[NOTE]
====
. Lit., “the corner tower,” pictorial of a vital or important man; chief.
. Lit., “the peg,” pictorial of one who is a support; a ruler.
====

[[v38-10-5]]

^<<v38-10-5,5>>^ And they must become like mighty men stamping down in the mire of &#91;the&#93; streets in the battle. And they must get engaged in battle, for Jehovah is with them; and the riders of horses will have to experience shame.

[[v38-10-6]]

^<<v38-10-6,6>>^ And I will make the house of Judah superior, and the house of Joseph I shall save. And I will give them a dwelling,^&#42;1^ for I will show them mercy; and they must become like those whom I had not cast off; for I am Jehovah their God,^&#42;2^ and I shall answer them.

[NOTE]
====
. Possibly, “I will cause them to return.”
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v38-10-7]]

^<<v38-10-7,7>>^ And those of Eʹphra·im must become just like a mighty man, and their heart must rejoice as though from wine. And their own sons will see and certainly rejoice; their heart will be joyful in Jehovah.

[[v38-10-8]]

^<<v38-10-8,8>>^ “‘I will whistle for them and collect them together; for I shall certainly redeem them, and they must become many, just like those who have become many.

[[v38-10-9]]

^<<v38-10-9,9>>^ And I shall scatter them like seed among the peoples, and in the distant places they will remember me; and they must revive with their sons and return.

[[v38-10-10]]

^<<v38-10-10,10>>^ And I must bring them back from the land of Egypt; and from As·syrʹi·a I shall collect them together; and to the land of Gilʹe·ad and Lebʹa·non I shall bring them, and no &#91;room&#93; will be found for them.

[[v38-10-11]]

^<<v38-10-11,11>>^ And he must pass through the sea &#91;with&#93; distress; and in the sea he must strike down &#91;the&#93; waves, and all the depths^&#42;1^ of the Nile must dry up. And the pride of As·syrʹi·a must be brought down, and the very scepter of Egypt will depart.

[NOTE]
====
. “Depths.” Heb., metsu·lohthʹ; Gr., baʹthe; Lat., pro·funʹda.
====

[[v38-10-12]]

^<<v38-10-12,12>>^ And I will make them superior in Jehovah, and in his name they will walk about,’ is the utterance of Jehovah.”

'''

xref:038-zechariah/038-zechariah-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zechariah/038-zechariah-011.adoc#v38-11-0[Próximo Capítulo &#62;]