include::./index.adoc[]

[[v38-8-0]]
=== Zechariah, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-8-1]]

^<<v38-8-1,1>>^ And the word of Jehovah of armies continued to occur, saying:

[[v38-8-2]]

^<<v38-8-2,2>>^ “This is what Jehovah of armies has said, ‘I will be jealous for Zion with great jealousy, and with great rage I will be jealous for her.’”

[[v38-8-3]]

^<<v38-8-3,3>>^ “This is what Jehovah has said, ‘I will return to Zion and reside in the midst of Jerusalem; and Jerusalem will certainly be called the city of trueness,^&#42;1^ and the mountain of Jehovah of armies, the holy mountain.’”

[NOTE]
====
. Or, “the city of truth.” Heb., ʽir-ha·ʼemethʹ.
====

[[v38-8-4]]

^<<v38-8-4,4>>^ “This is what Jehovah of armies has said, ‘There will yet sit old men and old women in the public squares of Jerusalem, each one also with his staff in his hand because of the abundance of &#91;his&#93; days.

[[v38-8-5]]

^<<v38-8-5,5>>^ And the public squares of the city themselves will be filled with boys and girls playing in her public squares.’”

[[v38-8-6]]

^<<v38-8-6,6>>^ “This is what Jehovah of armies has said, ‘Although it should seem too difficult^&#42;1^ in the eyes of the remaining ones of this people in those days, should it seem too difficult also in my eyes?’^&#42;2^ is the utterance of Jehovah of armies.”

[NOTE]
====
. Or, “wonderful.” LXX, “impossible.”
. “Although it shall be impossible in the sight of the remaining ones of this people in those days, shall it also be impossible in my sight?” LXX. Compare Mt 19:26.
====

[[v38-8-7]]

^<<v38-8-7,7>>^ “This is what Jehovah of armies has said, ‘Here I am saving my people from the land of the sunrise and from the land of the setting of the sun.

[[v38-8-8]]

^<<v38-8-8,8>>^ And I shall certainly bring them in, and they must reside in the midst of Jerusalem; and they must become my people, and I myself shall become^&#42;1^ their God in trueness and in righteousness.’”

[NOTE]
====
. Or, “I . . . shall prove to be.” Heb., ʼeh·yehʹ. Compare Ex 3:14 ftn.
====

[[v38-8-9]]

^<<v38-8-9,9>>^ “This is what Jehovah of armies has said, ‘Let the hands of YOU people be strong, YOU who are hearing in these days these words from the mouth of the prophets, on the day on which the foundation of the house of Jehovah of armies was laid, for the temple to be built.

[[v38-8-10]]

^<<v38-8-10,10>>^ For before those days there were no wages for mankind^&#42;1^ made to exist; and as for the wages of domestic animals, there was no such thing;^&#42;2^ and to the one going out and to the one coming in there was no peace because of the adversary,^&#42;3^ as I kept thrusting all mankind against one another.’

[NOTE]
====
. Lit., “wage of the earthling man.” Heb., sekharʹ ha·ʼa·dhamʹ.
. “No such thing.” Lit., “none,” fem.; not referring to “wages,” masc., but to the paying of wages.
. Or, “distress.”
====

[[v38-8-11]]

^<<v38-8-11,11>>^ “‘And now I shall not be as in the former days to the remaining ones of this people,’ is the utterance of Jehovah of armies.

[[v38-8-12]]

^<<v38-8-12,12>>^ ‘For there will be the seed of peace; the vine itself will give its fruitage, and the earth itself will give its yield, and the heavens themselves will give their dew; and I shall certainly cause the remaining ones of this people to inherit all these &#91;things&#93;.

[[v38-8-13]]

^<<v38-8-13,13>>^ And it must occur that just as YOU became a malediction among the nations, O house of Judah and house of Israel, so I shall save YOU, and YOU must become a blessing. Do not be afraid. May YOUR hands be strong.’

[[v38-8-14]]

^<<v38-8-14,14>>^ “For this is what Jehovah of armies has said, ‘“Just as I had in mind to do what was calamitous to YOU people because of YOUR forefathers’ making me indignant,” Jehovah of armies has said, “and I felt no regret,

[[v38-8-15]]

^<<v38-8-15,15>>^ so I will again have in mind in these days to deal well with Jerusalem and with the house of Judah. Do not be afraid.”’

[[v38-8-16]]

^<<v38-8-16,16>>^ “‘These are the things that YOU people should do: Speak truthfully with one another.^&#42;1^ With truth and the judgment of peace do YOUR judging in YOUR gates.

[NOTE]
====
. Or, “Speak truth each one with his companion.”
====

[[v38-8-17]]

^<<v38-8-17,17>>^ And calamity to one another do not YOU scheme up in YOUR hearts, and do not love any false oath; for these are all things that I have hated,’ is the utterance of Jehovah.”

[[v38-8-18]]

^<<v38-8-18,18>>^ And the word of Jehovah of armies continued to occur to me, saying:

[[v38-8-19]]

^<<v38-8-19,19>>^ “This is what Jehovah of armies has said, ‘The fast of the fourth &#91;month&#93;, and the fast of the fifth &#91;month&#93;, and the fast of the seventh &#91;month&#93;, and the fast of the tenth &#91;month&#93; will become for the house of Judah an exultation and a rejoicing and good festal seasons. So love truth and peace.’

[[v38-8-20]]

^<<v38-8-20,20>>^ “This is what Jehovah^&#42;1^ of armies has said, ‘It will yet be that peoples and the inhabitants of many cities will come;

[NOTE]
====
. See App 1C §4.
====

[[v38-8-21]]

^<<v38-8-21,21>>^ and the inhabitants of one &#91;city&#93; will certainly go to &#91;those of&#93; another, saying: “Let us earnestly go to soften the face of Jehovah and to seek Jehovah of armies. I myself will go also.”

[[v38-8-22]]

^<<v38-8-22,22>>^ And many peoples and mighty nations will actually come to seek Jehovah of armies in Jerusalem and to soften the face of Jehovah.’

[[v38-8-23]]

^<<v38-8-23,23>>^ “This is what Jehovah of armies has said, ‘It will be in those days that ten men^&#42;1^ out of all the languages^&#42;2^ of the nations will take hold, yes, they will actually take hold of the skirt of a man^&#42;3^ who is a Jew,^&#42;4^ saying: “We will go with YOU people, for we have heard &#91;that&#93; God^&#42;5^ is with YOU people.”’”

[NOTE]
====
. “Men.” Heb., ʼana·shimʹ, pl. of ʼish.
. Lit., “the tongues.” Compare Ge 11:1.
. “A man.” Heb., ʼish.
. “A Jew.” Heb., Yehu·dhiʹ.
. “God.” Heb., ʼElo·himʹ.
====

'''

xref:038-zechariah/038-zechariah-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zechariah/038-zechariah-009.adoc#v38-9-0[Próximo Capítulo &#62;]