include::./index.adoc[]

[[v38-13-0]]
=== Zechariah, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-13-1]]

^<<v38-13-1,1>>^ “In that day there will come to be a well opened to the house of David and to the inhabitants of Jerusalem for sin and for an abhorrent thing.

[[v38-13-2]]

^<<v38-13-2,2>>^ “And it must occur in that day,” is the utterance of Jehovah of armies, “&#91;that&#93; I shall cut off the names of the idols out of the land, and they will no more be remembered;^&#42;1^ and also the prophets and the spirit of uncleanness^&#42;2^ I shall cause to pass out of the land.

[NOTE]
====
. Or, “mentioned.”
. Or, “the expression inspired by uncleanness”; or, “the unclean inspired expression.” Compare Re 16:13 ftn, “Expressions.”
====

[[v38-13-3]]

^<<v38-13-3,3>>^ And it must occur &#91;that&#93; in case a man^&#42;1^ should prophesy anymore, his father and his mother, the ones who caused his birth, must also say to him, ‘You will not live, because falsehood is what you have spoken in the name of Jehovah.’ And his father and his mother, the ones who caused his birth, must pierce him through because of his prophesying.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v38-13-4]]

^<<v38-13-4,4>>^ “And it must occur in that day &#91;that&#93; the prophets will become ashamed, each one of his vision when he prophesies; and they will not wear an official garment of hair for the purpose of deceiving.

[[v38-13-5]]

^<<v38-13-5,5>>^ And he will certainly say, ‘I am no prophet. I am a man^&#42;1^ cultivating &#91;the&#93; soil, because an earthling man^&#42;2^ himself acquired me from my youth on.’

[NOTE]
====
. “A man.” Heb., ʼish.
. “An earthling man.” Heb., ʼa·dhamʹ; Gr., anʹthro·pos; Vg, “Adam ([was, or, is] my example).”
====

[[v38-13-6]]

^<<v38-13-6,6>>^ And one must say to him, ‘What are these wounds^&#42;1^ &#91;on your person&#93; between your hands?’ And he will have to say, ‘Those with which I was struck^&#42;2^ in the house of my intense lovers.’”

[NOTE]
====
. Or, “strokes.”
. Or, “wounded.”
====

[[v38-13-7]]

^<<v38-13-7,7>>^ “O sword, awake against my shepherd, even against the able-bodied man who is my associate,” is the utterance of Jehovah of armies. “Strike the shepherd, and let those of the flock be scattered; and I shall certainly turn my hand back upon those who are insignificant.”^&#42;1^

[NOTE]
====
. Or, “the boy keepers.” Heb., hats·tso·ʽarimʹ; LXXA, “the shepherds”; LXXא,BVg, “the little ones,” masc.; Sy, “the superior (great) ones.”
====

[[v38-13-8]]

^<<v38-13-8,8>>^ “And it must occur in all the land,”^&#42;1^ is the utterance of Jehovah, “&#91;that&#93; two parts in it are what will be cut off &#91;and&#93; expire; and as for the third &#91;part&#93;, it will be left remaining in it.

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v38-13-9]]

^<<v38-13-9,9>>^ And I shall certainly bring the third &#91;part&#93; through the fire; and I shall actually refine them as in the refining of silver, and examine them as in the examining of gold. It, for its part, will call upon my name, and I, for my part, will answer it. I will say, ‘It is my people,’ and it, in its turn, will say, ‘Jehovah is my God.’”

'''

xref:038-zechariah/038-zechariah-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zechariah/038-zechariah-014.adoc#v38-14-0[Próximo Capítulo &#62;]