include::./index.adoc[]

[[v38-1-0]]
=== Zechariah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v38-1-1]]

^<<v38-1-1,1>>^ In the eighth month in the second year of Da·riʹus the word of Jehovah occurred to Zech·a·riʹah the son of Ber·e·chiʹah^&#42;1^ the son of Idʹdo the prophet, saying:

[NOTE]
====
. “Berechiah.” Heb., Be·rekh·yahʹ, as in 1Ch 3:20; 1Ch 9:16; Ne 3:4, 30; Ne 6:18.
====

[[v38-1-2]]

^<<v38-1-2,2>>^ “Jehovah grew indignant at YOUR fathers—very much so.

[[v38-1-3]]

^<<v38-1-3,3>>^ “And you must say to them, ‘This is what Jehovah of armies^&#42;1^ has said: “‘Return to me,’ is the utterance of Jehovah^&#42;2^ of armies, ‘and I shall return to YOU,’ Jehovah^&#42;3^ of armies has said.”’

[NOTE]
====
. “Jehovah of armies.” Heb., Yehwahʹ tseva·ʼohthʹ. This expression occurs 53 times in Zechariah.
. See App 1C §2.
. See App 1C §2.
====

[[v38-1-4]]

^<<v38-1-4,4>>^ “‘Do not become like YOUR fathers to whom the former prophets called, saying: “This is what Jehovah^&#42;1^ of armies has said, ‘Return, please, from YOUR bad ways and from YOUR bad dealings.’”’
“‘But they did not listen, and they paid no attention to me,’ is the utterance of Jehovah.

[NOTE]
====
. See App 1C §2.
====

[[v38-1-5]]

^<<v38-1-5,5>>^ “‘As for YOUR fathers, where are they? And as for the prophets, was it to time indefinite that they continued to live?

[[v38-1-6]]

^<<v38-1-6,6>>^ However, as regards my words and my regulations that I commanded my servants, the prophets, did they not catch up with YOUR fathers?’ So they returned and said: ‘According to what Jehovah of armies had in mind to do to us, according to our ways and according to our dealings, that is how he has done with us.’”

[[v38-1-7]]

^<<v38-1-7,7>>^ On the twenty-fourth day of the eleventh month, that is, the month Sheʹbat, in the second year of Da·riʹus, the word of Jehovah occurred to Zech·a·riʹah the son of Ber·e·chiʹah^&#42;1^ the son of Idʹdo the prophet, saying:

[NOTE]
====
. “Berechiah.” Heb., Be·rekh·yaʹhu, as in 1Ch 6:39; 1Ch 15:17; 2Ch 28:12.
====

[[v38-1-8]]

^<<v38-1-8,8>>^ “I saw &#91;in&#93; the night, and, look! a man^&#42;1^ riding on a red horse, and he was standing still among the myrtle trees that were in the deep place;^&#42;2^ and behind him there were horses red, bright red, and white.”

[NOTE]
====
. “A man.” Heb., ʼish.
. Or, “in the abyss.” Heb., bam·metsu·lahʹ; Lat., in pro·funʹdo; T, “Babel (Babylon).”
====

[[v38-1-9]]

^<<v38-1-9,9>>^ And so I said: “Who are these, my lord?”^&#42;1^
At that the angel^&#42;2^ who was speaking with me said to me: “I myself shall show you who these very ones are.”

[NOTE]
====
. “My lord.” Heb., ʼadho·niʹ; Gr., kyʹri·e; Lat., doʹmi·ne.
. Or, “the messenger.” Heb., ham·mal·ʼakhʹ; Gr., ho agʹge·los; Lat., anʹge·lus.
====

[[v38-1-10]]

^<<v38-1-10,10>>^ Then the man who was standing still among the myrtle trees answered and said: “These are the ones whom Jehovah has sent forth to walk about in the earth.”^&#42;1^

[NOTE]
====
. Or, “in the land.” Heb., ba·ʼaʹrets.
====

[[v38-1-11]]

^<<v38-1-11,11>>^ And they proceeded to answer the angel of Jehovah who was standing among the myrtle trees and to say: “We have walked about in the earth, and, look! the whole earth is sitting still and having no disturbance.”

[[v38-1-12]]

^<<v38-1-12,12>>^ So the angel of Jehovah answered and said: “O Jehovah of armies, how long will you yourself not show mercy to Jerusalem and to the cities of Judah, whom you have denounced these seventy years?”

[[v38-1-13]]

^<<v38-1-13,13>>^ And Jehovah proceeded to answer the angel who was speaking with me, with good words, comforting words;

[[v38-1-14]]

^<<v38-1-14,14>>^ and the angel who was speaking with me went on to say to me: “Call out, saying, ‘This is what Jehovah of armies has said: “I have been jealous for Jerusalem and for Zion with great jealousy.

[[v38-1-15]]

^<<v38-1-15,15>>^ With great indignation I am feeling indignant against the nations that are at ease; because I, for my part, felt indignant to only a little extent, but they, for their part, helped toward calamity.”’

[[v38-1-16]]

^<<v38-1-16,16>>^ “Therefore this is what Jehovah has said, ‘“I shall certainly return to Jerusalem with mercies. My own house will be built in her,” is the utterance of Jehovah of armies, “and a measuring line itself will be stretched out over Jerusalem.”’

[[v38-1-17]]

^<<v38-1-17,17>>^ “Call out further, saying, ‘This is what Jehovah of armies has said: “My cities will yet overflow with goodness; and Jehovah will yet certainly feel regrets over Zion and yet actually choose Jerusalem.”’”

[[v38-1-18]]

^<<v38-1-18,18>>^ And I proceeded to raise my eyes and see; and, look! there were four horns.

[[v38-1-19]]

^<<v38-1-19,19>>^ So I said to the angel who was speaking with me: “What are these?” In turn he said to me: “These are the horns that dispersed Judah, Israel and Jerusalem.”

[[v38-1-20]]

^<<v38-1-20,20>>^ Furthermore, Jehovah showed me four craftsmen.

[[v38-1-21]]

^<<v38-1-21,21>>^ At that I said: “What are these coming to do?”
And he went on to say: “These are the horns that dispersed Judah to such an extent that no one at all raised his head; and these others will come to set them trembling, to cast down the horns of the nations that are lifting up a horn against the land of Judah,^&#42;1^ in order to disperse her.”

[NOTE]
====
. “Judah,” MSyVg; LXX, “Jehovah.”
====

'''

xref:037-haggai/037-haggai-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zechariah/038-zechariah-002.adoc#v38-2-0[Próximo Capítulo &#62;]