include::./index.adoc[]

[[v7-16-0]]
=== Judges, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-16-1]]

^<<v7-16-1,1>>^ Once Samson went to Gaʹza and saw a prostitute woman there and came in to her.

[[v7-16-2]]

^<<v7-16-2,2>>^ And report was made^&#42;1^ to the Gaʹzites, saying: “Samson has come in here.” So they surrounded him and lay in wait for him all night long in the city gate. And they kept quiet the whole night, saying: “As soon as the morning gets light, we must also kill him.”

[NOTE]
====
. “And report was made,” LXX; M omits.
====

[[v7-16-3]]

^<<v7-16-3,3>>^ However, Samson kept lying till midnight and then rose at midnight and grabbed hold of the doors of the city gate and the two side posts and pulled them out along with the bar and put them upon his shoulders and went carrying them up to the top of the mountain that is in front of Heʹbron.^&#42;1^

[NOTE]
====
. LXX adds, “and put them there.”
====

[[v7-16-4]]

^<<v7-16-4,4>>^ And it came about after that that he fell in love with a woman in the torrent valley of Soʹrek, and her name was De·liʹlah.

[[v7-16-5]]

^<<v7-16-5,5>>^ And the axis lords of the Phi·lisʹtines proceeded to come up to her and to say to her: “Fool him and see in what his great power is and with what we can prevail over him and with what we are certain to tie him so as to master him; and we, for our part, shall give you each one thousand one hundred silver pieces.”

[[v7-16-6]]

^<<v7-16-6,6>>^ Later De·liʹlah said to Samson: “Do tell me, please, In what is your great power and with what can you be tied for one to master you?”

[[v7-16-7]]

^<<v7-16-7,7>>^ Then Samson said to her: “If they tie me with seven still-moist sinews that have not been dried out, I must also grow weak and become like an ordinary man.”

[[v7-16-8]]

^<<v7-16-8,8>>^ So the axis lords of the Phi·lisʹtines brought up to her seven still-moist sinews that had not been dried out. Later she tied him with them.

[[v7-16-9]]

^<<v7-16-9,9>>^ Now the ambush was sitting in the interior room of hers, and she began to say to him: “The Phi·lisʹtines are upon you, Samson!” At that he tore the sinews in two, just as a twisted thread of tow is torn in two when it smells fire. And his power did not become known.

[[v7-16-10]]

^<<v7-16-10,10>>^ Subsequently De·liʹlah said to Samson: “Look! You have trifled with me that you might speak lies to me. Now tell me, do please, with what you can be tied.”

[[v7-16-11]]

^<<v7-16-11,11>>^ So he said to her: “If they tie me tight with new ropes with which no work has been done, I must also grow weak and become like an ordinary man.”

[[v7-16-12]]

^<<v7-16-12,12>>^ So De·liʹlah took new ropes and tied him with them and said to him: “The Phi·lisʹtines are upon you, Samson!” All the while the ambush was sitting in the interior room. At that he tore them in two from off his arms like a thread.

[[v7-16-13]]

^<<v7-16-13,13>>^ After that De·liʹlah said to Samson: “Up till now you have trifled with me that you might speak lies to me. Do tell me with what you can be tied.” Then he said to her: “If you will weave the seven braids of my head with the warp thread.”

[[v7-16-14]]

^<<v7-16-14,14>>^ Accordingly she fixed them with the pin,^&#42;1^ after which she said to him: “The Phi·lisʹtines are upon you, Samson!” So he awoke from his sleep and pulled out the loom pin and the warp thread.

[NOTE]
====
. “And it occurred that while he was sleeping Delilah took the seven braids of his head and wove them in the warp and fixed them to the pin in the wall,” LXXB.
====

[[v7-16-15]]

^<<v7-16-15,15>>^ She now said to him: “How dare you say, ‘I do love you,’ when your heart is not with me? These three times you have trifled with me and have not told me in what your great power is.”

[[v7-16-16]]

^<<v7-16-16,16>>^ And it came about that because she pressured him with her words all the time and kept urging him, his soul got to be impatient to the point of dying.

[[v7-16-17]]

^<<v7-16-17,17>>^ Finally he disclosed to her all his heart and said to her: “A razor has never come upon my head, because I am a Nazʹi·rite of God from my mother’s belly. If I did get shaved, my power also would certainly depart from me, and I should indeed grow weak and become like all other men.”

[[v7-16-18]]

^<<v7-16-18,18>>^ When De·liʹlah got to see that he had disclosed to her all his heart, she immediately sent and called the Phi·lisʹtine axis lords, saying: “Come up this time, for he has disclosed to me all his heart.” And the Phi·lisʹtine axis lords came up to her that they might bring up the money in their hand.

[[v7-16-19]]

^<<v7-16-19,19>>^ And she proceeded to make him sleep upon her knees. Then she called the man and had him shave off the seven braids of his head, after which she started to show the mastery of him, and his power kept departing from upon him.

[[v7-16-20]]

^<<v7-16-20,20>>^ Now she said: “The Phi·lisʹtines are upon you, Samson!” At that he woke up from his sleep and said: “I shall go out as at other times and shake myself free.” And he himself did not know that it was Jehovah that had departed from him.

[[v7-16-21]]

^<<v7-16-21,21>>^ So the Phi·lisʹtines grabbed hold of him and bored his eyes out and brought him down to Gaʹza and bound him with two fetters of copper; and he came to be a grinder in the prison house.

[[v7-16-22]]

^<<v7-16-22,22>>^ Meanwhile the hair of his head started to grow luxuriantly as soon as he had been shaved.

[[v7-16-23]]

^<<v7-16-23,23>>^ As for the Phi·lisʹtine axis lords, they gathered together to sacrifice a great sacrifice to Daʹgon their god^&#42;1^ and for rejoicing, and they kept saying: “Our god has given into our hand Samson our enemy!”

[NOTE]
====
. “Their god.” Heb., ʼelo·heh·hemʹ, pl. to denote excellence, applying to Dagon and with a sing. verb; LXXA(Gr.), the·oiʹ; Lat., deʹo. See 1Sa 5:7; 2Ki 19:37.
====

[[v7-16-24]]

^<<v7-16-24,24>>^ When the people got to see him, they at once gave way to praising their god, “because,” said they, “our god has given into our hand our enemy and the devastator of our land and the one who multiplied our slain.”

[[v7-16-25]]

^<<v7-16-25,25>>^ And it came about that because their heart was merry, they began to say: “Call Samson that he may offer us some amusement.” So they called Samson out of the prison house that he might make sport before them; and they proceeded to stand him between the pillars.

[[v7-16-26]]

^<<v7-16-26,26>>^ Then Samson said to the boy that was holding him by his hand: “Do permit me to feel the pillars upon which the house is firmly established and let me lean against them.”

[[v7-16-27]]

^<<v7-16-27,27>>^ (Incidentally, the house was full of men and women and all the Phi·lisʹtine axis lords were there; and upon the roof there were about three thousand men and women who were looking on while Samson offered some amusement.)

[[v7-16-28]]

^<<v7-16-28,28>>^ Samson now called to Jehovah and said: “Sovereign Lord Jehovah,^&#42;1^ remember me, please, and strengthen me, please, just this once, O you the &#91;true&#93; God, and let me avenge myself upon the Phi·lisʹtines with vengeance for one of my two eyes.”^&#42;2^

[NOTE]
====
. “Sovereign Lord Jehovah.” Heb., ʼAdho·naiʹ Yeho·wihʹ; LXXB(Gr.), A·do·na·i·eʹ Kyʹri·e; Lat., Doʹmi·ne Deʹus. See App 1E.
. “And I shall avenge myself upon the aliens with one avenging for my two eyes,” LXX; Vg, “that I may avenge myself upon my enemies and may receive one avenging for the loss of two eyes.”
====

[[v7-16-29]]

^<<v7-16-29,29>>^ With that Samson braced himself against the two middle pillars upon which the house was firmly established, and got a grasp on them, one with his right and the other with his left hand.

[[v7-16-30]]

^<<v7-16-30,30>>^ And Samson proceeded to say: “Let my soul die with the Phi·lisʹtines.” Then he bent himself with power, and the house went falling upon the axis lords and upon all the people that were in it, so that the dead that he put to death in his own death came to be more than those he had put to death during his lifetime.

[[v7-16-31]]

^<<v7-16-31,31>>^ Later his brothers and all the household of his father came on down and lifted him up and brought him up and buried him between Zoʹrah and Eshʹta·ol in the burial place of Ma·noʹah his father. As for him, he had judged Israel twenty years.

'''

xref:007-judges/007-judges-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-judges/007-judges-017.adoc#v7-17-0[Próximo Capítulo &#62;]