include::./index.adoc[]

[[v7-11-0]]
=== Judges, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-11-1]]

^<<v7-11-1,1>>^ Now Jephʹthah the Gilʹe·ad·ite had become a mighty, valiant man, and he was the son of a prostitute woman, and Gilʹe·ad came to be the father of Jephʹthah.

[[v7-11-2]]

^<<v7-11-2,2>>^ And Gilʹe·ad’s wife kept bearing sons to him. When the sons of the wife got big, they proceeded to drive Jephʹthah out and to say to him: “You must have no inheritance in the household of our father, for you are the son of another woman.”

[[v7-11-3]]

^<<v7-11-3,3>>^ So Jephʹthah ran away because of his brothers and took up dwelling in the land of Tob. And idle men kept bringing themselves together to Jephʹthah, and they would go out with him.

[[v7-11-4]]

^<<v7-11-4,4>>^ And it came about after a while that the sons of Amʹmon began to fight against Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ And it came about that when the sons of Amʹmon did fight against Israel, the older men of Gilʹe·ad immediately went to take Jephʹthah out of the land of Tob.

[[v7-11-6]]

^<<v7-11-6,6>>^ Then they said to Jephʹthah: “Do come and serve as our commander, and let us fight against the sons of Amʹmon.”

[[v7-11-7]]

^<<v7-11-7,7>>^ But Jephʹthah said to the older men of Gilʹe·ad: “Was it not YOU that hated me so that YOU drove me out of my father’s house? And why is it that YOU have come to me now just when YOU are in distress?”

[[v7-11-8]]

^<<v7-11-8,8>>^ At this the older men of Gilʹe·ad said to Jephʹthah: “That is why now we have returned to you, and you must go with us and fight against the sons of Amʹmon, and you must become for us the head of all the inhabitants of Gilʹe·ad.”

[[v7-11-9]]

^<<v7-11-9,9>>^ So Jephʹthah said to the older men of Gilʹe·ad: “If YOU are bringing me back to fight against the sons of Amʹmon, and Jehovah does abandon them to me, I, for my part, shall become YOUR head!”

[[v7-11-10]]

^<<v7-11-10,10>>^ In turn the older men of Gilʹe·ad said to Jephʹthah: “Let Jehovah prove to be the listener between us if the way we shall do is not according to your word.”

[[v7-11-11]]

^<<v7-11-11,11>>^ Consequently Jephʹthah went with the older men of Gilʹe·ad and the people set him over them as head and commander. And Jephʹthah proceeded to speak all his words before Jehovah in Mizʹpah.

[[v7-11-12]]

^<<v7-11-12,12>>^ Then Jephʹthah sent messengers to the king of the sons of Amʹmon, saying: “What do I have to do with you,^&#42;1^ seeing that you have come against me to fight in my land?”

[NOTE]
====
. Lit., “What [is there] to me and to you?” A Heb. idiom; a repellent question indicating objection. See App 7B.
====

[[v7-11-13]]

^<<v7-11-13,13>>^ So the king of the sons of Amʹmon said to the messengers of Jephʹthah: “It is because Israel took my land when they came up out of Egypt, from the Arʹnon as far as the Jabʹbok and as far as the Jordan. And now do return it peacefully.”

[[v7-11-14]]

^<<v7-11-14,14>>^ But Jephʹthah sent once more messengers to the king of the sons of Amʹmon

[[v7-11-15]]

^<<v7-11-15,15>>^ and said to him:
“This is what Jephʹthah has said, ‘Israel did not take the land of Moʹab and the land of the sons of Amʹmon.

[[v7-11-16]]

^<<v7-11-16,16>>^ For when they came up out of Egypt Israel went walking through the wilderness as far as the Red Sea and got to come to Kaʹdesh.

[[v7-11-17]]

^<<v7-11-17,17>>^ Then Israel sent messengers to the king of Eʹdom, saying: “Let me pass, please, through your land,” and the king of Eʹdom did not listen. And also to the king of Moʹab they sent, and he did not consent. And Israel kept dwelling in Kaʹdesh.

[[v7-11-18]]

^<<v7-11-18,18>>^ When they walked on through the wilderness, they went their way around the land of Eʹdom and the land of Moʹab, so that they went toward the rising of the sun as respects the land of Moʹab^&#42;1^ and took up camping in the region of the Arʹnon; and they did not come within the boundary of Moʹab, because Arʹnon was the boundary of Moʹab.

[NOTE]
====
. Or, “they went to the east of the land of Moab.”
====

[[v7-11-19]]

^<<v7-11-19,19>>^ “‘After that Israel sent messengers to Siʹhon the king of the Amʹor·ites, the king of Heshʹbon, and Israel said to him: “Let us pass, please, through your land to my own place.”

[[v7-11-20]]

^<<v7-11-20,20>>^ And Siʹhon did not feel sure about Israel’s crossing through his territory, and Siʹhon went gathering all his people together and camping in Jaʹhaz and fighting against Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ At this Jehovah the God of Israel gave Siʹhon and all his people into Israel’s hand, so that they struck them and Israel took possession of all the land of the Amʹor·ites inhabiting that land.

[[v7-11-22]]

^<<v7-11-22,22>>^ Thus they took possession of all the territory of the Amʹor·ites from the Arʹnon as far as the Jabʹbok and from the wilderness as far as the Jordan.

[[v7-11-23]]

^<<v7-11-23,23>>^ “‘And now Jehovah the God of Israel it was that dispossessed the Amʹor·ites from before his people Israel, and you, for your part, would dispossess^&#42;1^ them.

[NOTE]
====
. “Inherit,” LXX; Vg, “take possession of.”
====

[[v7-11-24]]

^<<v7-11-24,24>>^ Is it not whomever Cheʹmosh your god^&#42;1^ causes you to dispossess that you will dispossess?^&#42;2^ And every one whom Jehovah our God has dispossessed from before us is the one we shall dispossess.^&#42;3^

[NOTE]
====
. “Your god.” Heb., ʼelo·heyʹkha; Gr., the·osʹ; Lat., deʹus; LXXVg understood ʼelo·heyʹkha (from ʼelo·himʹ) to be pl. to denote excellence and therefore rendered it in the sing.
. “Inherit,” LXX; Vg, “be due [to you] by right.”
. “Inherit,” LXX; Vg, “fall to our possession.”
====

[[v7-11-25]]

^<<v7-11-25,25>>^ And now are you any better than Baʹlak the son of Zipʹpor, the king of Moʹab? Did he ever contend with Israel, or did he ever fight against them?

[[v7-11-26]]

^<<v7-11-26,26>>^ While Israel was dwelling in Heshʹbon and its dependent towns and in A·roʹer and its dependent towns and in all the cities that are by the banks of Arʹnon for three hundred years, why, then, did you never snatch them away during that time?

[[v7-11-27]]

^<<v7-11-27,27>>^ As for me, I have not sinned against you, but you are dealing wrong with me by fighting against me. Let Jehovah the Judge judge today between the sons of Israel and the sons of Amʹmon.’”

[[v7-11-28]]

^<<v7-11-28,28>>^ And the king of the sons of Amʹmon did not listen to the words of Jephʹthah that he had sent to him.

[[v7-11-29]]

^<<v7-11-29,29>>^ Jehovah’s spirit now came upon Jephʹthah, and he proceeded to pass through Gilʹe·ad and Ma·nasʹseh and to pass through Mizʹpeh of Gilʹe·ad, and from Mizʹpeh of Gilʹe·ad he passed along to the sons of Amʹmon.

[[v7-11-30]]

^<<v7-11-30,30>>^ Then Jephʹthah made a vow to Jehovah and said: “If you without fail give the sons of Amʹmon into my hand,

[[v7-11-31]]

^<<v7-11-31,31>>^ it must also occur that the one coming out, who comes out of the doors of my house to meet me when I return in peace from the sons of Amʹmon, must also become Jehovah’s, and I must offer that one up as a burnt offering.”

[[v7-11-32]]

^<<v7-11-32,32>>^ So Jephʹthah passed along to the sons of Amʹmon to fight against them, and Jehovah proceeded to give them into his hand.

[[v7-11-33]]

^<<v7-11-33,33>>^ And he went striking them from A·roʹer all the way to Minʹnith—twenty cities—and as far as Aʹbel-kerʹa·mim with a very great slaughter. Thus the sons of Amʹmon were subdued before the sons of Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Finally Jephʹthah came to Mizʹpah to his home, and, look! his daughter coming out to meet him with tambourine playing and dancing!^&#42;1^ Now she was absolutely the only child.^&#42;2^ Besides her he had neither son nor daughter.

[NOTE]
====
. Lit., “with tambourines and dances.”
. “Now she was absolutely the only child.” Lit., “And only she, she alone.” Heb., weraqʹ hiʼ yechi·dhahʹ; LXX(Gr., mo·no·ge·nesʹ)Vg(Lat., u·ni·geʹni·ta), “only-begotten.” Compare Ge 22:2. See Lu 8:42 ftn.
====

[[v7-11-35]]

^<<v7-11-35,35>>^ And it came about that when he caught sight of her, he began to rip his garments and to say: “Alas, my daughter! You have indeed made me bend down, and you yourself have become the one I was ostracizing. And I—I have opened my mouth to Jehovah, and I am unable to turn back.”

[[v7-11-36]]

^<<v7-11-36,36>>^ But she said to him: “My father, if you have opened your mouth to Jehovah, do to me according to what has gone forth from your mouth, since Jehovah has executed acts of vengeance for you upon your enemies, the sons of Amʹmon.”

[[v7-11-37]]

^<<v7-11-37,37>>^ And she went on to say to her father: “Let this thing be done to me: Let me alone for two months, and let me go, and I will descend upon the mountains, and let me weep over my virginity, I and my girl companions.”

[[v7-11-38]]

^<<v7-11-38,38>>^ At this he said: “Go!” So he sent her away for two months; and she kept going, she with her girl companions, and weeping over her virginity upon the mountains.

[[v7-11-39]]

^<<v7-11-39,39>>^ And it came about at the end of two months that she made her return to her father, after which he carried out his vow that he had made toward her. As for her, she never had relations with a man. And it came to be a regulation in Israel:

[[v7-11-40]]

^<<v7-11-40,40>>^ From year to year the daughters of Israel would go to give commendation to^&#42;1^ the daughter of Jephʹthah the Gilʹe·ad·ite, four days in the year.

[NOTE]
====
. “To bewail,” LXX; by a correction of M, “go to answer (to converse with).” See 5:11 where the same Heb. verb, ta·nahʹ, “recount,” is used.
====

'''

xref:007-judges/007-judges-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-judges/007-judges-012.adoc#v7-12-0[Próximo Capítulo &#62;]