include::./index.adoc[]

[[v7-15-0]]
=== Judges, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-15-1]]

^<<v7-15-1,1>>^ And it came about after a while, in the days of wheat harvest, that Samson went visiting his wife with a kid of the goats. So he said: “I will go in to my wife in the interior room.” And her father did not allow him to go in.

[[v7-15-2]]

^<<v7-15-2,2>>^ But her father said: “I really said to myself, ‘You must unquestionably hate her.’ Hence I gave her to your groomsman. Is not her younger sister better than she is? Let her, please, become yours instead of the other.”

[[v7-15-3]]

^<<v7-15-3,3>>^ However, Samson said to them: “This time I must be free of guilt against the Phi·lisʹtines in case I am dealing with them to their injury.”

[[v7-15-4]]

^<<v7-15-4,4>>^ And Samson went his way and proceeded to catch three hundred foxes^&#42;1^ and to take torches and turn tail to tail and put one torch between two tails, right in the middle.

[NOTE]
====
. Possibly, “jackals.”
====

[[v7-15-5]]

^<<v7-15-5,5>>^ With that he set fire to the torches and sent them out into the fields of standing grain of the Phi·lisʹtines. Thus he set on fire everything from sheaf to standing grain and the vineyards and the olive groves.

[[v7-15-6]]

^<<v7-15-6,6>>^ And the Phi·lisʹtines began to say: “Who did this?” Then they said: “It was Samson the son-in-law of the Timʹnite, because he took his wife and then gave her to his groomsman.” At that the Phi·lisʹtines went up and burned her and her father with fire.

[[v7-15-7]]

^<<v7-15-7,7>>^ In turn Samson said to them: “If YOU do like this, there is nothing but for me to avenge myself upon YOU, and afterward I shall quit.”

[[v7-15-8]]

^<<v7-15-8,8>>^ And he went smiting them, piling legs upon thighs with a great slaughter, after which he went down and began to dwell in a cleft of the crag Eʹtam.

[[v7-15-9]]

^<<v7-15-9,9>>^ Later the Phi·lisʹtines came up and camped in Judah and went tramping about in Leʹhi.

[[v7-15-10]]

^<<v7-15-10,10>>^ Then the men of Judah said: “Why have YOU come up against us?” to which they said: “It is to tie Samson that we have come up, to do to him just as he has done to us.”

[[v7-15-11]]

^<<v7-15-11,11>>^ So three thousand men of Judah went down to the cleft of the crag Eʹtam and said to Samson: “Do you not know that the Phi·lisʹtines are ruling over us? So what does this mean that you have done to us?” Then he said to them: “Just as they did to me is the way I have done to them.”

[[v7-15-12]]

^<<v7-15-12,12>>^ But they said to him: “It is to tie you that we have come down, to give you into the hand of the Phi·lisʹtines.” At that Samson said to them: “Swear to me that YOU yourselves will not assault me.”

[[v7-15-13]]

^<<v7-15-13,13>>^ And they went on to say to him: “No, but we shall merely tie you, and we will give you into their hand; but we shall by no means put you to death.”
Accordingly they bound him with two new ropes and brought him up out of the crag.

[[v7-15-14]]

^<<v7-15-14,14>>^ He, for his part, came as far as Leʹhi, and the Phi·lisʹtines, for their part, shouted exultantly at meeting him. And Jehovah’s spirit became operative upon him, and the ropes that were upon his arms came to be like linen threads that have been scorched with fire, so that his fetters melted off his hands.

[[v7-15-15]]

^<<v7-15-15,15>>^ He now found a moist jawbone^&#42;1^ of a male ass and thrust his hand out and took it and went striking down a thousand men with it.

[NOTE]
====
. “Jawbone of.” Heb., lechiʹ.
====

[[v7-15-16]]

^<<v7-15-16,16>>^ Then Samson said:
“With the jawbone of a male ass—one heap, two heaps!^&#42;1^
With the jawbone of a male ass I have struck down a thousand men.”

[NOTE]
====
. “One heap, two heaps!” With vowel pointing altered, “I have piled them up for fair”; LXX, “I have thoroughly wiped them out.”
====

[[v7-15-17]]

^<<v7-15-17,17>>^ And it came about that when he finished speaking, he immediately threw the jawbone out of his hand and called that place Raʹmath-leʹhi.^&#42;1^

[NOTE]
====
. Meaning “The Lofty Place of the Jawbone.”
====

[[v7-15-18]]

^<<v7-15-18,18>>^ Now he became very thirsty, and he began to call on Jehovah and say: “It was you that gave this great salvation into the hand of your servant, and now shall I die of thirst and must I fall into the hand of the uncircumcised?”

[[v7-15-19]]

^<<v7-15-19,19>>^ So God^&#42;1^ split open a mortar-shaped hollow that was in Leʹhi,^&#42;2^ and water began to come out of it,^&#42;3^ and he proceeded to drink, after which his spirit returned and he revived. That is why he called its name En-hak·korʹe,^&#42;4^ which is in Leʹhi down to this day.

[NOTE]
====
. “God,” MLXX; Sy, “Jehovah God”; TVg, “Jehovah.”
. Lit., “in the Lehi.” Heb., bal·Leʹchi. “Lehi” means “Jawbone.”
. “And God broke open the hollow (pit) that was in the jaw and water came out of it,” LXXB; Sy, “And Jehovah God broke open the jaw of the cheek of the ass and water came out of it”; Vg, “So Jehovah [Lat., Doʹmi·nus] opened a molar tooth in the jaw of the ass and waters came out of it.”
. Meaning “Fountain of the Man Calling.”
====

[[v7-15-20]]

^<<v7-15-20,20>>^ And he continued to judge Israel in the days of the Phi·lisʹtines twenty years.

'''

xref:007-judges/007-judges-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-judges/007-judges-016.adoc#v7-16-0[Próximo Capítulo &#62;]