include::./index.adoc[]

[[v7-5-0]]
=== Judges, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-5-1]]

^<<v7-5-1,1>>^ And on that day Debʹo·rah along with Baʹrak the son of A·binʹo·am broke out in song, saying:

[[v7-5-2]]

^<<v7-5-2,2>>^ “For letting the hair hang loose in Israel &#91;for war&#93;,
For the people’s volunteering,
BLESS Jehovah.

[[v7-5-3]]

^<<v7-5-3,3>>^ Listen, YOU kings; give ear, YOU high officials:
I to Jehovah, yes, I, will sing.
I shall make melody to Jehovah, Israel’s God.

[[v7-5-4]]

^<<v7-5-4,4>>^ Jehovah, at your going forth from Seʹir,
At your marching out of the field of Eʹdom,
Earth rocked, heavens also dripped,
Clouds also dripped with water.

[[v7-5-5]]

^<<v7-5-5,5>>^ Mountains flowed^&#42;1^ away from the face of Jehovah,
This Siʹnai away from the face of Jehovah, Israel’s God.

[NOTE]
====
. “Flowed,” MVg; TSy, “quaked”; LXX, “were shaken.”
====

[[v7-5-6]]

^<<v7-5-6,6>>^ In the days of Shamʹgar the son of Aʹnath,
In the days of Jaʹel, pathways had no traffic,^&#42;1^
And the travelers of roadways would travel by roundabout pathways.

[NOTE]
====
. Lit., “pathways ceased [suffered neglect].”
====

[[v7-5-7]]

^<<v7-5-7,7>>^ The dwellers in open country ceased, in Israel they ceased,
Until I, Debʹo·rah, rose up,
Until I rose up as a mother in Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ They proceeded to choose new gods.
It was then there was war^&#42;1^ in the gates.^&#42;2^
A shield could not be seen, nor a lance,
Among forty thousand in Israel.

[NOTE]
====
. The meaning in M is obscure.
. “Then the cities of the governors (princes) fought,” LXXB.
====

[[v7-5-9]]

^<<v7-5-9,9>>^ My heart is for the commanders of Israel,
Who were volunteers among the people.
BLESS Jehovah.

[[v7-5-10]]

^<<v7-5-10,10>>^ YOU riders on yellowish-red she-asses,
YOU who sit on rich carpets,^&#42;1^
And YOU who walk on the road,
Consider!

[NOTE]
====
. The meaning in M is obscure; LXXBVg, “sit in judgment.”
====

[[v7-5-11]]

^<<v7-5-11,11>>^ Some of the voices of the water distributors among the places of drawing water,
There they began to recount the righteous acts of Jehovah,
The righteous acts of his dwellers in open country in Israel.
It was then Jehovah’s people made their way down to the gates.

[[v7-5-12]]

^<<v7-5-12,12>>^ Awake, awake, O Debʹo·rah;
Awake, awake, utter a song!
Rise up, Baʹrak, and lead your captives^&#42;1^ away, you son of A·binʹo·am!

[NOTE]
====
. Or, “captivity,” that is, a body of captives.
====

[[v7-5-13]]

^<<v7-5-13,13>>^ It was then the survivors came down to the majestic ones;
Jehovah’s people came down to me against the mighty ones.

[[v7-5-14]]

^<<v7-5-14,14>>^ Out of Eʹphra·im was their origin in the low plain,^&#42;1^
With^&#42;2^ you, O Benjamin, among your peoples.
Out of Maʹchir the commanders went down,
And out of Zebʹu·lun those handling the equipment of a scribe.

[NOTE]
====
. “In the low plain,” LXXATh; MLXXBVg, “in Amalek.”
. Or, “after.”
====

[[v7-5-15]]

^<<v7-5-15,15>>^ And the princes in Isʹsa·char were with Debʹo·rah,
And as Isʹsa·char, so was Baʹrak.
Into the low plain he was sent on foot.
Among the divisions of Reuʹben great were the searchings^&#42;1^ of the heart.

[NOTE]
====
. “Searchings,” as in vs 16; M, “prescriptions.”
====

[[v7-5-16]]

^<<v7-5-16,16>>^ Why did you sit down between the two saddlebags,
To listen to the pipings for the flocks?
For the divisions of Reuʹben there were great searchings of the heart.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gilʹe·ad kept to his residence on the other side of the Jordan;
And Dan, why did he continue to dwell for the time in ships?
Ashʹer sat idle at the seashore,
And by his landing places he kept residing.

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebʹu·lun was a people that scorned their souls to the point of death;
Naphʹta·li also, on the heights of the field.

[[v7-5-19]]

^<<v7-5-19,19>>^ Kings came, they fought;
It was then that the kings of Caʹnaan fought
In Taʹa·nach by the waters of Me·gidʹdo.
No gain of silver did they take.

[[v7-5-20]]

^<<v7-5-20,20>>^ From heaven did the stars fight,
From their orbits they fought against Sisʹe·ra.

[[v7-5-21]]

^<<v7-5-21,21>>^ The torrent of Kiʹshon washed them away,
The torrent of ancient days,^&#42;1^ the torrent of Kiʹshon.
You went treading down strength, O my soul.

[NOTE]
====
. “Torrent of ancient days.” Or, “torrent of attack.” Heb., naʹchal qedhu·mimʹ; qedhu·mimʹ is of uncertain meaning; LXXB, “ancient winter-torrent”; Vg, “torrent Cadumim.”
====

[[v7-5-22]]

^<<v7-5-22,22>>^ It was then that the hoofs of horses pawed
Because of dashings upon dashings of his stallions.

[[v7-5-23]]

^<<v7-5-23,23>>^ ‘CURSE Meʹroz,’ said the angel of Jehovah,
‘CURSE its inhabitants incessantly,
For they did not come to the assistance of Jehovah,
To the assistance of Jehovah with the mighty ones.’

[[v7-5-24]]

^<<v7-5-24,24>>^ Jaʹel the wife of Heʹber the Kenʹite will be most blessed among women,
Among women in the tent she will be most blessed.

[[v7-5-25]]

^<<v7-5-25,25>>^ Water he asked, milk she gave;
In the large banquet bowl of majestic ones she presented curdled milk.

[[v7-5-26]]

^<<v7-5-26,26>>^ Her hand to the tent pin she then thrust out,
And her right hand to the mallet of hard workers.
And she hammered Sisʹe·ra, she pierced his head through,
And she broke apart and cut up his temples.

[[v7-5-27]]

^<<v7-5-27,27>>^ Between her feet he collapsed, he fell, he lay down;
Between her feet he collapsed, he fell;
Where he collapsed, there he fell overcome.

[[v7-5-28]]

^<<v7-5-28,28>>^ From the window a woman looked out and kept watching for him,^&#42;1^
The mother of Sisʹe·ra from the lattice,
‘Why has his war chariot delayed in coming?
Why must the hoofbeats of his chariots be so late?’

[NOTE]
====
. “Kept watching [for him],” T; M, “kept lamenting.”
====

[[v7-5-29]]

^<<v7-5-29,29>>^ The wise ones of her noble ladies^&#42;1^ would answer her,
Yes, she too would talk back to herself with her own sayings,

[NOTE]
====
. Or, “her princesses.” Heb., sa·roh·theyʹha.
====

[[v7-5-30]]

^<<v7-5-30,30>>^ ‘Ought they not to find, ought they not to distribute spoil,
A womb—two wombs^&#42;1^ to every able-bodied man,
Spoil of dyed stuffs for Sisʹe·ra, spoil of dyed stuffs,
An embroidered garment, dyed stuff, two embroidered garments
For the necks of &#91;men of&#93; spoil?’^&#42;2^

[NOTE]
====
. Soldiers’ expression for captured concubines.
. “For the neck of a king’s wife,” by a change of one Heb. letter; by a slight change of vowel pointing, “for my neck as spoil”; by a change of a final Heb. letter, “for his neck as spoil.”
====

[[v7-5-31]]

^<<v7-5-31,31>>^ Thus let all your enemies perish, O Jehovah,
And let your^&#42;1^ lovers be as when the sun goes forth in its mightiness.”
And the land had no further disturbance for forty years.

[NOTE]
====
. “Your,” SyVg; MLXX, “his.”
====

'''

xref:007-judges/007-judges-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-judges/007-judges-006.adoc#v7-6-0[Próximo Capítulo &#62;]