include::./index.adoc[]

[[v7-19-0]]
=== Judges, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-19-1]]

^<<v7-19-1,1>>^ Now it happened in those days that there was no king in Israel. And it came about that a certain Levite was residing for a time in the remotest parts of the mountainous region of Eʹphra·im. In time he took as his wife a concubine from Bethʹle·hem in Judah.

[[v7-19-2]]

^<<v7-19-2,2>>^ And his concubine began to commit fornication^&#42;1^ against him.^&#42;2^ Finally she went away from him to the house of her father at Bethʹle·hem in Judah and continued there fully four months.

[NOTE]
====
. “And . . . began to commit fornication.” Heb., wat·tiz·nehʹ.
. “His concubine got angry with him,” LXXA.
====

[[v7-19-3]]

^<<v7-19-3,3>>^ Then her husband got up and went after her to speak consolingly to her^&#42;1^ so as to bring her back; and there were with him his attendant^&#42;2^ and a couple of he-asses. So she had him come into her father’s house. When the father of the young woman got to see him, he at once rejoiced to meet him.

[NOTE]
====
. Lit., “to speak to her heart.”
. Or, “young man; boy.”
====

[[v7-19-4]]

^<<v7-19-4,4>>^ Consequently his father-in-law, the young woman’s father, took hold of him, so that he continued to dwell with him three days; and they would eat and drink, and he^&#42;1^ would stay overnight there.

[NOTE]
====
. “He,” LXXmssIt; MSy, “they.”
====

[[v7-19-5]]

^<<v7-19-5,5>>^ And it came about on the fourth day, when they got up early in the morning as usual, he now rose to go, but the father of the young woman said to his son-in-law: “Sustain your heart with a bit of bread and afterward YOU people may go.”

[[v7-19-6]]

^<<v7-19-6,6>>^ So they sat down, and both of them began to eat and to drink together; after which the father of the young woman said to the man: “Come on, please, and stay overnight, and let your heart feel good.”

[[v7-19-7]]

^<<v7-19-7,7>>^ When the man rose to go, his father-in-law kept begging him, so that he stayed overnight there again.

[[v7-19-8]]

^<<v7-19-8,8>>^ When he got up early in the morning on the fifth day to go, the father of the young woman then said: “Please, take sustenance for your heart.” And they lingered until the fading away of the day. And both of them kept eating.

[[v7-19-9]]

^<<v7-19-9,9>>^ The man now rose to go, he and his concubine and his attendant; but his father-in-law, the young woman’s father, said to him: “Look, now! The day has declined toward becoming evening. Please, STAY overnight. Here the day is settling down. Stay here overnight, and let your heart feel good. And tomorrow YOU people must get up early for YOUR journey, and you must go to your tent.”

[[v7-19-10]]

^<<v7-19-10,10>>^ However, the man did not consent to stay overnight, but he rose and got on his way and came as far as in front of Jeʹbus, that is to say, Jerusalem; and with him there were the couple of he-asses saddled up, and his concubine and his attendant.^&#42;1^

[NOTE]
====
. “And his concubine and his attendant,” to agree with vss 9 and 11; M, “and his concubine was with him.”
====

[[v7-19-11]]

^<<v7-19-11,11>>^ While they were close by Jeʹbus, as the daylight had gone down considerably, the attendant now said to his master:^&#42;1^ “O come, now, and let us turn aside to this city of the Jebʹu·sites and stay in it overnight.”

[NOTE]
====
. “His master.” Heb., ʼadho·navʹ, pl. to denote excellence; Gr., kyʹri·on; Lat., doʹmi·num. See Ge 39:2 ftn.
====

[[v7-19-12]]

^<<v7-19-12,12>>^ But his master said to him: “Let us not turn aside to a city of foreigners who are no part of the sons of Israel; and we have to pass on as far as Gibʹe·ah.”

[[v7-19-13]]

^<<v7-19-13,13>>^ And he went on to say to his attendant: “Come and let us approach one of the places, and we must stay overnight either in Gibʹe·ah or in Raʹmah.”

[[v7-19-14]]

^<<v7-19-14,14>>^ So they passed along and kept on their way, and the sun began to set upon them when near to Gibʹe·ah, which belongs to Benjamin.

[[v7-19-15]]

^<<v7-19-15,15>>^ Consequently they turned aside there to go in to stay overnight in Gibʹe·ah. And they^&#42;1^ proceeded to go in and sit down in the public square of the city, and there was nobody taking them on into the house to stay overnight.

[NOTE]
====
. “They,” LXXSyVg; M, “he.”
====

[[v7-19-16]]

^<<v7-19-16,16>>^ Eventually, look! an old man coming in from his work in the field at evening, and the man was from the mountainous region of Eʹphra·im, and he was residing for a time in Gibʹe·ah; but the men of the place were Benʹja·mites.

[[v7-19-17]]

^<<v7-19-17,17>>^ When he raised his eyes he got to see the man, the traveler, in the public square of the city. So the old man said: “Where are you going, and where do you come from?”

[[v7-19-18]]

^<<v7-19-18,18>>^ In turn he said to him: “We are passing along from Bethʹle·hem in Judah to the remotest parts of the mountainous region of Eʹphra·im. That is where I am from, but I went to Bethʹle·hem in Judah; and it is to my own house^&#42;1^ that I am going, and there is nobody taking me on into the house.

[NOTE]
====
. “To my own house,” LXX (compare vs 29); MSy, “to Jehovah’s house”; Vg, “to God’s house.” But KB, p. 369, states that in this case “Jehovah” may be a misunderstanding of the first-person sing. pronoun “my.”
====

[[v7-19-19]]

^<<v7-19-19,19>>^ And there are both straw and fodder for our he-asses, and there are both bread and wine for me and your slave girl and for the attendant with your servant.^&#42;1^ There is no lack of a single thing.”

[NOTE]
====
. “Servant,” TBomberg,PretoriumSy; M, “servants.”
====

[[v7-19-20]]

^<<v7-19-20,20>>^ However, the old man said: “May you have peace!^&#42;1^ Just let any lack of yours be upon me. Only do not stay overnight in the public square.”

[NOTE]
====
. Lit., “Peace to you.” Heb., sha·lohmʹ lakh.
====

[[v7-19-21]]

^<<v7-19-21,21>>^ With that he brought him into his house and threw mash to the he-asses. Then they washed their feet and began to eat and drink.

[[v7-19-22]]

^<<v7-19-22,22>>^ While they were making their hearts feel good, look! the men of the city, mere good-for-nothing men,^&#42;1^ surrounded the house, shoving one another against the door; and they kept saying to the old man, the owner of the house: “Bring out the man that came into your house, that we may have intercourse with him.”

[NOTE]
====
. Lit., “men of the sons of belial (worthlessness).”
====

[[v7-19-23]]

^<<v7-19-23,23>>^ At that the owner of the house went on out to them and said to them: “No, my brothers, do not do anything wrong, please, since this man has come into my house. Do not commit this disgraceful folly.

[[v7-19-24]]

^<<v7-19-24,24>>^ Here are my virgin daughter and his concubine. Let me bring them out, please, and YOU rape them and do to them what is good in YOUR eyes. But to this man YOU must not do this disgraceful, foolish thing.”

[[v7-19-25]]

^<<v7-19-25,25>>^ And the men did not want to listen to him. Hence the man took hold of his concubine and brought her forth to them outside; and they began to have intercourse with her, and kept on abusing her all night long until the morning, after which they sent her off at the ascending of the dawn.

[[v7-19-26]]

^<<v7-19-26,26>>^ Then the woman came as it was turning to morning, and fell down at the entrance of the man’s house where her master was,—until daylight.

[[v7-19-27]]

^<<v7-19-27,27>>^ Later her master rose up in the morning and opened the doors of the house and went out to get on his way, and, look! the woman, his concubine, fallen at the entrance of the house with her hands upon the threshold!

[[v7-19-28]]

^<<v7-19-28,28>>^ So he said to her: “Rise up, and let us go.” But there was no one answering. At that the man took her upon the ass and rose up and went to his place.

[[v7-19-29]]

^<<v7-19-29,29>>^ Then he entered his house and took the slaughtering knife and laid hold of his concubine and cut her up according to her bones into twelve pieces and sent her into every territory of Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ And it occurred that everybody seeing it said: “Such a thing as this has never been brought about or been seen from the day that the sons of Israel went up out of the land of Egypt down to this day. Set YOUR hearts^&#42;1^ upon it, take counsel and speak.”

[NOTE]
====
. “Your hearts,” T; M, “for yourselves.”
====

'''

xref:007-judges/007-judges-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-judges/007-judges-020.adoc#v7-20-0[Próximo Capítulo &#62;]