include::./index.adoc[]

[[v7-9-0]]
=== Judges, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-9-1]]

^<<v7-9-1,1>>^ In time A·bimʹe·lech the son of Jer·ub·baʹal went to Sheʹchem to the brothers of his mother and began speaking to them and to all the family of the house of his mother’s father, saying:

[[v7-9-2]]

^<<v7-9-2,2>>^ “Speak, please, in the hearing of all the landowners^&#42;1^ of Sheʹchem, ‘Which is better for YOU, for seventy men, all the sons of Jer·ub·baʹal, to rule over YOU or for one man to rule over YOU? And YOU must remember that YOUR bone and YOUR flesh I am.’”

[NOTE]
====
. “Landowners of.” Heb., ba·ʽalehʹ; LXXVg, “men.”
====

[[v7-9-3]]

^<<v7-9-3,3>>^ So the brothers of his mother began speaking all these words about him in the hearing of all the landowners of Sheʹchem so that their heart inclined toward A·bimʹe·lech, for they said: “He is our own brother.”

[[v7-9-4]]

^<<v7-9-4,4>>^ Then they gave him seventy pieces of silver from the house of Baʹal-beʹrith, and with them A·bimʹe·lech proceeded to hire idle and insolent men, that they might accompany him.

[[v7-9-5]]

^<<v7-9-5,5>>^ After that he went to the house of his father at Ophʹrah and killed his brothers, the sons of Jer·ub·baʹal, seventy men, upon one stone, but Joʹtham the youngest son of Jer·ub·baʹal was left over, because he had hid.

[[v7-9-6]]

^<<v7-9-6,6>>^ Subsequently all the landowners of Sheʹchem and all the house of Milʹlo gathered together and went and made A·bimʹe·lech reign as king, close by the big tree, the pillar that was in Sheʹchem.

[[v7-9-7]]

^<<v7-9-7,7>>^ When they reported it to Joʹtham he at once went and stood on the top of Mount Gerʹi·zim and raised his voice and called out and said to them: “Listen to me, YOU landowners of Sheʹchem, and let God listen to YOU:

[[v7-9-8]]

^<<v7-9-8,8>>^ “Once upon a time the trees went to anoint a king over them. So they said to the olive tree, ‘Do be king^&#42;1^ over us.’

[NOTE]
====
. Or, “reign,” masc.
====

[[v7-9-9]]

^<<v7-9-9,9>>^ But the olive tree said to them, ‘Must I give up my fatness with which they glorify God and men, and must I go to wave over the other trees?’

[[v7-9-10]]

^<<v7-9-10,10>>^ Then the trees said to the fig tree, ‘You come, be queen^&#42;1^ over us.’

[NOTE]
====
. Or, “reign,” fem.
====

[[v7-9-11]]

^<<v7-9-11,11>>^ But the fig tree said to them, ‘Must I give up my sweetness and my good produce, and must I go to wave over the other trees?’

[[v7-9-12]]

^<<v7-9-12,12>>^ Next the trees said to the vine, ‘You come, be queen over us.’

[[v7-9-13]]

^<<v7-9-13,13>>^ In turn the vine said to them, ‘Must I give up my new wine that makes God and men rejoice, and must I go to wave over the trees?’

[[v7-9-14]]

^<<v7-9-14,14>>^ Finally all the other trees said to the bramble, ‘You come, be king over us.’

[[v7-9-15]]

^<<v7-9-15,15>>^ At this the bramble said to the trees, ‘If it is in truth that YOU are anointing me as king over YOU, come, seek refuge under my shadow. But if not, let fire come out of the bramble and consume the cedars of Lebʹa·non.’

[[v7-9-16]]

^<<v7-9-16,16>>^ “And now if it is in truth and in faultlessness that YOU have acted and that YOU went making A·bimʹe·lech king, and if it is goodness that YOU have exercised toward Jer·ub·baʹal and his household, and if YOU have done to him as the doing of his hands deserved,

[[v7-9-17]]

^<<v7-9-17,17>>^ when my father fought for YOU and went risking his soul^&#42;1^ that he might deliver YOU out of Midʹi·an’s hand;

[NOTE]
====
. “His soul (life).” Heb., naph·shohʹ; Gr., psy·khenʹ; Lat., aʹni·mam.
====

[[v7-9-18]]

^<<v7-9-18,18>>^ and YOU, for YOUR part, have risen up against the household of my father today that YOU might kill his sons, seventy men, upon one stone, and that YOU might make A·bimʹe·lech, the son of his slave girl, king over the landowners of Sheʹchem just because he is YOUR own brother;

[[v7-9-19]]

^<<v7-9-19,19>>^ yes, if it is in truth and in faultlessness that YOU have acted toward Jer·ub·baʹal and his household this day, rejoice over A·bimʹe·lech and let him too rejoice over YOU.

[[v7-9-20]]

^<<v7-9-20,20>>^ But if not, let fire come out of A·bimʹe·lech and consume the landowners of Sheʹchem and the house of Milʹlo, and let fire come out of the landowners of Sheʹchem and the house of Milʹlo and consume A·bimʹe·lech.”

[[v7-9-21]]

^<<v7-9-21,21>>^ Then Joʹtham took to flight and went running off and made his way to Beʹer, and he took up dwelling there because of A·bimʹe·lech his brother.

[[v7-9-22]]

^<<v7-9-22,22>>^ And A·bimʹe·lech kept playing the prince^&#42;1^ over Israel three years.

[NOTE]
====
. Or, “kept exercising dominion.”
====

[[v7-9-23]]

^<<v7-9-23,23>>^ Then God let develop^&#42;1^ a bad spirit between A·bimʹe·lech and the landowners of Sheʹchem, and the landowners of Sheʹchem proceeded to deal treacherously with A·bimʹe·lech,

[NOTE]
====
. Lit., “God sent.”
====

[[v7-9-24]]

^<<v7-9-24,24>>^ that the violence done to the seventy sons of Jer·ub·baʹal might come^&#42;1^ and that he might put their blood upon A·bimʹe·lech their brother because he killed them, and upon the landowners of Sheʹchem because they strengthened his hands to kill his brothers.

[NOTE]
====
. “That he might bring the violence done to the seventy sons of Jerubbaal,” LXX.
====

[[v7-9-25]]

^<<v7-9-25,25>>^ So the landowners of Sheʹchem set ambush men for him upon the tops of the mountains, and they would rob everyone that would pass by them on the road. In time it was reported to A·bimʹe·lech.

[[v7-9-26]]

^<<v7-9-26,26>>^ Then Gaʹal the son of Eʹbed and his brothers came and crossed over into Sheʹchem, and the landowners of Sheʹchem began to trust in him.

[[v7-9-27]]

^<<v7-9-27,27>>^ And they went out as usual into the field and engaged in gathering the grapes of their vineyards and in treading them and in carrying on a festal exultation, after which they went into the house of their god and ate and drank and called down evil upon A·bimʹe·lech.

[[v7-9-28]]

^<<v7-9-28,28>>^ And Gaʹal the son of Eʹbed went on to say: “Who is A·bimʹe·lech, and who is Sheʹchem^&#42;1^ that we should serve him? Is he not the son of Jer·ub·baʹal, and is not Zeʹbul a commissioner of his? Serve the men of Haʹmor, Sheʹchem’s father, YOU others, but why should we ourselves serve him?

[NOTE]
====
. “Shechem,” MSyVg; LXX, “the son of Shechem.”
====

[[v7-9-29]]

^<<v7-9-29,29>>^ And if only this people were in my hand!^&#42;1^ Then I would remove A·bimʹe·lech.” And he went on to say^&#42;2^ to A·bimʹe·lech: “Make your army numerous and come on out.”

[NOTE]
====
. Lit., “And who will give this people into my hand?”
. “And I would remove Abimelech and say,” LXX; Vg, “ ‘that I might remove Abimelech!’ And it was said.”
====

[[v7-9-30]]

^<<v7-9-30,30>>^ And Zeʹbul the prince of the city got to hear the words of Gaʹal the son of Eʹbed. Then his anger blazed.

[[v7-9-31]]

^<<v7-9-31,31>>^ So he sent messengers by subterfuge to A·bimʹe·lech,^&#42;1^ saying: “Look! Gaʹal the son of Eʹbed and his brothers are now come to Sheʹchem, and here they are massing the city against you.

[NOTE]
====
. “By subterfuge to Abimelech.” Possibly, “to Abimelech in Tormah (Arumah).” See vs 41.
====

[[v7-9-32]]

^<<v7-9-32,32>>^ And now rise up by night, you and the people that are with you, and lie in wait in the field.

[[v7-9-33]]

^<<v7-9-33,33>>^ And it must occur in the morning that as soon as the sun shines forth you should get up early, and you must make a dash against the city; and when he and the people that are with him are going out against you, you must also do to him just as your hand finds it possible.”

[[v7-9-34]]

^<<v7-9-34,34>>^ Accordingly A·bimʹe·lech and all the people that were with him rose up by night, and they began to lie in wait against Sheʹchem in four bands.

[[v7-9-35]]

^<<v7-9-35,35>>^ Later Gaʹal the son of Eʹbed went out and stood at the entrance of the city gate. Then A·bimʹe·lech and the people that were with him rose up from the place of ambush.

[[v7-9-36]]

^<<v7-9-36,36>>^ When Gaʹal caught sight of the people, he at once said to Zeʹbul: “Look! People coming down from the tops of the mountains.” But Zeʹbul said to him: “The shadows of the mountains are what you are seeing as though they were men.”

[[v7-9-37]]

^<<v7-9-37,37>>^ Later Gaʹal spoke once more and said: “Look! People coming down out of the center of the land, and one band is coming by the way of the big tree of Me·onʹe·nim.”^&#42;1^

[NOTE]
====
. Meaning “Those Practicing Magic.” See De 18:14.
====

[[v7-9-38]]

^<<v7-9-38,38>>^ At this Zeʹbul said to him: “Where now is that saying of yours that you mouthed,^&#42;1^ ‘Who is A·bimʹe·lech that we should serve him?’ Is not this the people whom you rejected? Go out now, please, and fight against them.”

[NOTE]
====
. Or, “that mouth of yours when you said.”
====

[[v7-9-39]]

^<<v7-9-39,39>>^ So Gaʹal went on out at the head of the landowners of Sheʹchem and took up the fight against A·bimʹe·lech.

[[v7-9-40]]

^<<v7-9-40,40>>^ And A·bimʹe·lech set out after him, and he went fleeing before him; and the slain kept falling in numbers as far as the entrance of the gate.

[[v7-9-41]]

^<<v7-9-41,41>>^ And A·bimʹe·lech continued to dwell in A·ruʹmah,^&#42;1^ and Zeʹbul proceeded to drive Gaʹal and his brothers out from dwelling in Sheʹchem.

[NOTE]
====
. Possibly, “Rumah.” See 2Ki 23:36.
====

[[v7-9-42]]

^<<v7-9-42,42>>^ And it came about on the next day that the people began to go out into the field. So they told A·bimʹe·lech.

[[v7-9-43]]

^<<v7-9-43,43>>^ Hence he took the people and divided them up into three bands and began to lie in wait in the field. Then he looked, and there the people were going out of the city. He now rose up against them and struck them down.

[[v7-9-44]]

^<<v7-9-44,44>>^ And A·bimʹe·lech and the bands^&#42;1^ that were with him made a dash that they might stand at the entrance of the city gate, while two bands made a dash against all who were in the field, and they went striking them down.

[NOTE]
====
. “Bands,” M; Vg, “band.”
====

[[v7-9-45]]

^<<v7-9-45,45>>^ And A·bimʹe·lech fought against the city all that day and got to capture the city; and he killed the people that were in it, after which he pulled the city down and sowed it with salt.

[[v7-9-46]]

^<<v7-9-46,46>>^ When all the landowners of the tower of Sheʹchem heard of it, they immediately went to the vault of the house of El-beʹrith.^&#42;1^

[NOTE]
====
. Meaning “God of a Covenant”; LXXA, “Baal of a covenant.”
====

[[v7-9-47]]

^<<v7-9-47,47>>^ Then it was reported to A·bimʹe·lech that all the landowners of the tower of Sheʹchem had collected together.

[[v7-9-48]]

^<<v7-9-48,48>>^ At that A·bimʹe·lech went up Mount Zalʹmon, he and all the people that were with him. A·bimʹe·lech now took an ax in his hand and cut down a branch of the trees and lifted it up and put it on his shoulder and said to the people that were with him: “What YOU have seen me do—hurry up, do like me!”

[[v7-9-49]]

^<<v7-9-49,49>>^ So all the people cut down also each one a branch for himself and went following A·bimʹe·lech. Then they put them against the vault, and over them they set the vault on fire, so that all the men of the tower of Sheʹchem died too, about a thousand men and women.

[[v7-9-50]]

^<<v7-9-50,50>>^ And A·bimʹe·lech proceeded to go to Theʹbez and to camp against Theʹbez and capture it.

[[v7-9-51]]

^<<v7-9-51,51>>^ As a strong tower happened to be in the middle of the city, there was where all the men and women and all the landowners of the city went fleeing, after which they shut it behind them and climbed onto the roof of the tower.

[[v7-9-52]]

^<<v7-9-52,52>>^ And A·bimʹe·lech made his way to the tower and began fighting against it, and he went on up close to the entrance of the tower to burn it with fire.

[[v7-9-53]]

^<<v7-9-53,53>>^ Then a certain woman pitched an upper millstone upon A·bimʹe·lech’s head and broke his skull in pieces.

[[v7-9-54]]

^<<v7-9-54,54>>^ So he quickly called the attendant bearing his weapons and said to him: “Draw your sword and put me to death, for fear they should say about me, ‘It was a woman that killed him.’” Immediately his attendant ran him through, so that he died.

[[v7-9-55]]

^<<v7-9-55,55>>^ When the men of Israel got to see that A·bimʹe·lech had died, they now went each one to his place.

[[v7-9-56]]

^<<v7-9-56,56>>^ Thus God made the evil of A·bimʹe·lech that he had done to his father by killing his seventy brothers come back.

[[v7-9-57]]

^<<v7-9-57,57>>^ And all the evil of the men of Sheʹchem God made come back upon their own heads, that the malediction of Joʹtham the son of Jer·ub·baʹal might come upon them.

'''

xref:007-judges/007-judges-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-judges/007-judges-010.adoc#v7-10-0[Próximo Capítulo &#62;]