include::./index.adoc[]

[[v7-10-0]]
=== Judges, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-10-1]]

^<<v7-10-1,1>>^ Now after A·bimʹe·lech there rose up to save Israel Toʹla the son of Puʹah, the son of Doʹdo, a man of Isʹsa·char, and he was dwelling in Shaʹmir in the mountainous region of Eʹphra·im.

[[v7-10-2]]

^<<v7-10-2,2>>^ And he continued to judge Israel for twenty-three years, after which he died and was buried in Shaʹmir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Then after him Jaʹir the Gilʹe·ad·ite rose up, and he continued to judge Israel for twenty-two years.

[[v7-10-4]]

^<<v7-10-4,4>>^ And he came to have thirty sons who rode on thirty full-grown asses, and they had thirty cities.^&#42;1^ These they continue to call Havʹvoth-jaʹir^&#42;2^ down to this day; they are in the land of Gilʹe·ad.

[NOTE]
====
. “Cities,” LXXSyVg; M, “full-grown asses.”
. Meaning “Tent Villages of Jair.”
====

[[v7-10-5]]

^<<v7-10-5,5>>^ After that Jaʹir died and was buried in Kaʹmon.

[[v7-10-6]]

^<<v7-10-6,6>>^ And the sons of Israel again proceeded to do what was bad in the eyes of Jehovah, and they began to serve the Baʹals and the Ashʹto·reth images and the gods of Syria and the gods of Siʹdon and the gods of Moʹab and the gods of the sons of Amʹmon and the gods of the Phi·lisʹtines. So they left Jehovah and did not serve him.

[[v7-10-7]]

^<<v7-10-7,7>>^ At this Jehovah’s anger blazed against Israel, so that he sold them into the hand of the Phi·lisʹtines and into the hand of the sons of Amʹmon.

[[v7-10-8]]

^<<v7-10-8,8>>^ Hence they shattered and heavily oppressed the sons of Israel in that year—for eighteen years all the sons of Israel that were on the side of the Jordan in the land of the Amʹor·ites that was in Gilʹe·ad.

[[v7-10-9]]

^<<v7-10-9,9>>^ And the sons of Amʹmon would cross the Jordan to fight even against Judah and Benjamin and the house of Eʹphra·im; and Israel was greatly distressed.

[[v7-10-10]]

^<<v7-10-10,10>>^ And the sons of Israel began to call to Jehovah for aid, saying: “We have sinned against you, because we have left our God and we serve the Baʹals.”

[[v7-10-11]]

^<<v7-10-11,11>>^ Then Jehovah said to the sons of Israel: “Was it not from Egypt and from the Amʹor·ites and from the sons of Amʹmon and from the Phi·lisʹtines

[[v7-10-12]]

^<<v7-10-12,12>>^ and the Si·doʹni·ans and Amʹa·lek and Midʹi·an,^&#42;1^ when they oppressed YOU and YOU went crying out to me, that I proceeded to save YOU out of their hand?

[NOTE]
====
. “Midian,” LXX; M, “Maon”; Vg, “Canaan.”
====

[[v7-10-13]]

^<<v7-10-13,13>>^ As for YOU, YOU abandoned me and took up serving other gods. That is why I shall not save YOU again.

[[v7-10-14]]

^<<v7-10-14,14>>^ Go and call for aid to the gods^&#42;1^ whom YOU have chosen. Let them be the ones to save YOU in the time of YOUR distress.”

[NOTE]
====
. “The gods.” Heb., ha·ʼelo·himʹ; Gr., the·ousʹ; Lat., deʹos.
====

[[v7-10-15]]

^<<v7-10-15,15>>^ But the sons of Israel said to Jehovah: “We have sinned. You yourself do to us according to anything that is good in your eyes. Only deliver us, please, this day.”

[[v7-10-16]]

^<<v7-10-16,16>>^ And they began to remove the foreign gods from their midst and to serve Jehovah, so that his soul became impatient because of the trouble of Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ In time the sons of Amʹmon were called together and pitched camp in Gilʹe·ad. So the sons of Israel gathered themselves together and pitched camp in Mizʹpah.

[[v7-10-18]]

^<<v7-10-18,18>>^ And the people and the princes of Gilʹe·ad began to say to one another: “Who is the man that will take the lead in fighting against the sons of Amʹmon? Let him become the head of all the inhabitants of Gilʹe·ad.”

'''

xref:007-judges/007-judges-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-judges/007-judges-011.adoc#v7-11-0[Próximo Capítulo &#62;]