include::./index.adoc[]

[[v7-17-0]]
=== Judges, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-17-1]]

^<<v7-17-1,1>>^ Now there happened to be a man of the mountainous region of Eʹphra·im whose name was Miʹcah.^&#42;1^

[NOTE]
====
. Meaning “Who Is Like Jehovah?” Heb., Mi·khaʹyehu.
====

[[v7-17-2]]

^<<v7-17-2,2>>^ In time he said to his mother: “The thousand one hundred silver pieces that were taken from you and over which you pronounced a curse and also said it in my hearing—look! the silver is with me. It was I who took it.” At that his mother said: “Blessed may my son be of Jehovah.”

[[v7-17-3]]

^<<v7-17-3,3>>^ Accordingly he gave back the thousand one hundred pieces of silver to his mother; and his mother went on to say: “I must without fail sanctify the silver to Jehovah from my hand for my son, so as to make a carved image and a molten statue; and now I shall give it back to you.”^&#42;1^

[NOTE]
====
. “And now I shall give it back to you.” Some suggest that this should be transposed to vs 2, after the words: “It was I who took it.”
====

[[v7-17-4]]

^<<v7-17-4,4>>^ So he returned the silver to his mother, and his mother took two hundred silver pieces and gave them to the silversmith. And he went making a carved image and a molten statue; and it got to be in Miʹcah’s house.

[[v7-17-5]]

^<<v7-17-5,5>>^ As for the man Miʹcah,^&#42;1^ he had a house of gods,^&#42;2^ and he proceeded to make an ephʹod and teraphim^&#42;3^ and to fill the hand of one of his sons with power,^&#42;4^ that he might serve as priest for him.

[NOTE]
====
. “Micah.” Heb., Mi·khahʹ; Lat., Miʹcha.
. “Gods.” Heb., ʼelo·himʹ; Gr., the·ouʹ, “god.” See 18:24.
. Compare Ge 31:19 ftn.
. Or, “and to install one of his sons.”
====

[[v7-17-6]]

^<<v7-17-6,6>>^ In those days there was no king in Israel. As for everybody, what was right in his own eyes he was accustomed to do.

[[v7-17-7]]

^<<v7-17-7,7>>^ Now there happened to be a young man of Bethʹle·hem in Judah of the family of Judah,^&#42;1^ and he was a Levite.^&#42;2^ And he was residing there for a time.

[NOTE]
====
. Possibly, “of the family of Moses.” Compare 18:30.
. Or, “and who was a Levite,” MLXXVg; Sy, “and his name was Levi.”
====

[[v7-17-8]]

^<<v7-17-8,8>>^ And the man proceeded to go from the city of Bethʹle·hem in Judah to reside for a time wherever he might find a place. At length while going his way he came into the mountainous region of Eʹphra·im as far as the house of Miʹcah.

[[v7-17-9]]

^<<v7-17-9,9>>^ Then Miʹcah said to him: “Where do you come from?” At that he said to him: “I am a Levite from Bethʹle·hem in Judah, and I am on my way to reside for a time wherever I may find a place.”

[[v7-17-10]]

^<<v7-17-10,10>>^ So Miʹcah said to him: “Do dwell with me and serve as a father and priest for me, and I, for my part, shall give you ten silver pieces a year and the usual outfit of garments and your sustenance.” Accordingly the Levite went in.

[[v7-17-11]]

^<<v7-17-11,11>>^ Thus the Levite took it upon himself to dwell with the man, and the young man got to be as one of his sons to him.

[[v7-17-12]]

^<<v7-17-12,12>>^ Furthermore, Miʹcah filled the hand of the Levite with power, that the young man might serve as a priest for him and might continue in the house of Miʹcah.

[[v7-17-13]]

^<<v7-17-13,13>>^ Hence Miʹcah said: “Now I do know that Jehovah will do me good, because the Levite has become priest for me.”

'''

xref:007-judges/007-judges-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-judges/007-judges-018.adoc#v7-18-0[Próximo Capítulo &#62;]