include::./index.adoc[]

[[v7-1-0]]
=== Judges, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-1-1]]

^<<v7-1-1,1>>^ And after the death of Joshua it came about that the sons of Israel proceeded to inquire of Jehovah, saying: “Who of us will go up first to the Caʹnaan·ites to fight against them?”

[[v7-1-2]]

^<<v7-1-2,2>>^ To this Jehovah said: “Judah will go up. Look! I shall certainly give the land into his hand.”

[[v7-1-3]]

^<<v7-1-3,3>>^ Then Judah said to Simʹe·on his brother: “Come up with me into my lot and let us fight against the Caʹnaan·ites, and I myself in turn will go with you into your lot.” Accordingly Simʹe·on went with him.

[[v7-1-4]]

^<<v7-1-4,4>>^ With that Judah went on up and Jehovah gave the Caʹnaan·ites and the Perʹiz·zites into their hands, so that they defeated them in Beʹzek, ten thousand men.

[[v7-1-5]]

^<<v7-1-5,5>>^ When they found A·doʹni-beʹzek in Beʹzek, then they fought against him and defeated the Caʹnaan·ites and the Perʹiz·zites.

[[v7-1-6]]

^<<v7-1-6,6>>^ When A·doʹni-beʹzek took to flight, then they went chasing after him and got hold of him and cut off the thumbs of his hands and the great toes of his feet.

[[v7-1-7]]

^<<v7-1-7,7>>^ At this A·doʹni-beʹzek said: “There have been seventy kings with the thumbs of their hands and the great toes of their feet cut off picking up food under my table. Just the way I have done, so God has repaid me.” After that they brought him to Jerusalem and he died there.

[[v7-1-8]]

^<<v7-1-8,8>>^ Furthermore, the sons of Judah carried on war against Jerusalem and got to capture it, and they went striking it with the edge of the sword, and the city they consigned to the fire.

[[v7-1-9]]

^<<v7-1-9,9>>^ And afterward the sons of Judah went down to fight against the Caʹnaan·ites inhabiting the mountainous region and the Negʹeb and the She·pheʹlah.

[[v7-1-10]]

^<<v7-1-10,10>>^ So Judah marched against the Caʹnaan·ites who were dwelling in Heʹbron (now the name of Heʹbron before that was Kirʹi·ath-arʹba), and they went striking down Sheʹshai and A·hiʹman and Talʹmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ And they marched on from there against the inhabitants of Deʹbir. (Now the name of Deʹbir before that was Kirʹi·ath-seʹpher.)

[[v7-1-12]]

^<<v7-1-12,12>>^ Then Caʹleb said: “Whoever strikes Kirʹi·ath-seʹpher and does capture it, why, I will give him Achʹsah my daughter as a wife.”

[[v7-1-13]]

^<<v7-1-13,13>>^ And Othʹni·el the son of Keʹnaz, Caʹleb’s younger brother, got to capture it. For that he gave him Achʹsah his daughter as a wife.

[[v7-1-14]]

^<<v7-1-14,14>>^ And it came about that while she was going home, she kept inciting him to ask a field from her father. Then she clapped her hands while upon the ass.^&#42;1^ At this Caʹleb said to her: “What do you want?”

[NOTE]
====
. Or, “Then she slid down (alighted) from off the ass.”
====

[[v7-1-15]]

^<<v7-1-15,15>>^ So she said to him: “Do grant me a blessing, for it is a southern piece of land you have given me, and you must give me Gulʹloth-maʹim.”^&#42;1^ Accordingly Caʹleb gave her Upper Gulʹloth and Lower Gulʹloth.^&#42;2^

[NOTE]
====
. Meaning “Basin of Water.”
. Or, “the upper basin and the lower basin.”
====

[[v7-1-16]]

^<<v7-1-16,16>>^ And the sons of the Kenʹite, whose son-in-law Moses was,^&#42;1^ came up out of the city of palm trees with the sons of Judah to the wilderness of Judah, which is to the south of Aʹrad. Then they went and took up dwelling with the people.

[NOTE]
====
. Or, “the Kenite, the father-in-law of Moses.”
====

[[v7-1-17]]

^<<v7-1-17,17>>^ But Judah marched on with Simʹe·on his brother, and they proceeded to strike the Caʹnaan·ites inhabiting Zeʹphath and to devote it to destruction. Hence the name of the city was called Horʹmah.^&#42;1^

[NOTE]
====
. Meaning “A Devoting to Destruction”; LXXB, “Anathema”; Vg, “Horma, that is, anathema.”
====

[[v7-1-18]]

^<<v7-1-18,18>>^ After that Judah captured Gaʹza and its territory and Ashʹke·lon and its territory and Ekʹron and its territory.

[[v7-1-19]]

^<<v7-1-19,19>>^ And Jehovah continued with Judah, so that he took possession of the mountainous region, but he could not dispossess the inhabitants of the low plain, because they had war chariots with iron scythes.^&#42;1^

[NOTE]
====
. Lit., “war chariots of iron.”
====

[[v7-1-20]]

^<<v7-1-20,20>>^ When they gave Caʹleb Heʹbron, just as Moses had promised, then he drove out from there the three sons of Aʹnak.

[[v7-1-21]]

^<<v7-1-21,21>>^ And the sons of Benjamin did not drive out the Jebʹu·sites inhabiting Jerusalem; but the Jebʹu·sites keep on dwelling with the sons of Benjamin in Jerusalem down to this day.

[[v7-1-22]]

^<<v7-1-22,22>>^ Meantime the house of Joseph itself also went up against Bethʹel, and Jehovah was with them.

[[v7-1-23]]

^<<v7-1-23,23>>^ And the house of Joseph began to spy on Bethʹel (incidentally, the name of the city before that was Luz),

[[v7-1-24]]

^<<v7-1-24,24>>^ and the watchers got to see a man going out of the city. So they said to him: “Show us, please, the way to get into the city, and we shall certainly exercise kindness toward you.”

[[v7-1-25]]

^<<v7-1-25,25>>^ Accordingly the man showed them the way to get into the city; and they went striking the city with the edge of the sword, but the man and all his family they let go.

[[v7-1-26]]

^<<v7-1-26,26>>^ Upon that the man went to the land of the Hitʹtites and built a city and called its name Luz. That is its name down to this day.

[[v7-1-27]]

^<<v7-1-27,27>>^ And Ma·nasʹseh did not take possession of Beth-sheʹan and its dependent towns and Taʹa·nach and its dependent towns^&#42;1^ and the inhabitants of Dor and its dependent towns and the inhabitants of Ibʹle·am and its dependent towns and the inhabitants of Me·gidʹdo and its dependent towns, but the Caʹnaan·ites persisted in dwelling in this land.

[NOTE]
====
. Lit., “its daughters.”
====

[[v7-1-28]]

^<<v7-1-28,28>>^ And it came about that Israel grew strong and proceeded to set the Caʹnaan·ites to forced labor, and they did not drive them out completely.

[[v7-1-29]]

^<<v7-1-29,29>>^ Neither did Eʹphra·im drive out the Caʹnaan·ites who were dwelling in Geʹzer, but the Caʹnaan·ites continued to dwell in among them in Geʹzer.

[[v7-1-30]]

^<<v7-1-30,30>>^ Zebʹu·lun did not drive out the inhabitants of Kitʹron and the inhabitants of Naʹha·lol, but the Caʹnaan·ites continued to dwell in among them and came to be subject to forced labor.

[[v7-1-31]]

^<<v7-1-31,31>>^ Ashʹer did not drive out the inhabitants of Acʹco^&#42;1^ and the inhabitants of Siʹdon and Ahʹlab and Achʹzib and Helʹbah and Aʹphik and Reʹhob.

[NOTE]
====
. Later called Ptolemais. See Ac 21:7.
====

[[v7-1-32]]

^<<v7-1-32,32>>^ And the Ashʹer·ites continued to dwell in among the Caʹnaan·ites inhabiting the land, because they did not drive them out.

[[v7-1-33]]

^<<v7-1-33,33>>^ Naphʹta·li did not drive out the inhabitants of Beth-sheʹmesh and the inhabitants of Beth-aʹnath, but they continued to dwell in among the Caʹnaan·ites inhabiting the land; and the inhabitants of Beth-sheʹmesh and of Beth-aʹnath became theirs for forced labor.

[[v7-1-34]]

^<<v7-1-34,34>>^ And the Amʹor·ites kept pressing the sons of Dan into the mountainous region, for they did not allow them to come down into the low plain.

[[v7-1-35]]

^<<v7-1-35,35>>^ So the Amʹor·ites persisted in dwelling in Mount Heʹres and in Aiʹja·lon and Sha·alʹbim. But the hand of the house of Joseph got to be so heavy that they were forced into task work.

[[v7-1-36]]

^<<v7-1-36,36>>^ And the territory of the Amʹor·ites was from the ascent of A·krabʹbim, from Seʹla^&#42;1^ upward.

[NOTE]
====
. Or, “from the Rock.” Heb., me·has·Seʹlaʽ.
====

'''

xref:006-joshua/006-joshua-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-judges/007-judges-002.adoc#v7-2-0[Próximo Capítulo &#62;]