include::./index.adoc[]

[[v7-6-0]]
=== Judges, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-6-1]]

^<<v7-6-1,1>>^ Then the sons of Israel began to do what was bad in the eyes of Jehovah. So Jehovah gave them into the hand of Midʹi·an for seven years.

[[v7-6-2]]

^<<v7-6-2,2>>^ And the hand of Midʹi·an came to prevail over Israel. Due to Midʹi·an the sons of Israel made for themselves the underground store places that were in the mountains, and the caves and the places difficult to approach.

[[v7-6-3]]

^<<v7-6-3,3>>^ And it occurred that, if Israel sowed seed, Midʹi·an and Amʹa·lek and the Easterners^&#42;1^ came up, yes, they came up against them.

[NOTE]
====
. Lit., “and sons of the East.” Vg, “and others of the Oriental nations.”
====

[[v7-6-4]]

^<<v7-6-4,4>>^ And they would camp against them and would ruin the yield of the earth all the way to Gaʹza, and they would not let any sustenance or sheep or bull or ass remain in Israel.

[[v7-6-5]]

^<<v7-6-5,5>>^ For they and their livestock would come up with their tents. They would come as numerous as the locusts, and they and their camels were without number; and they would come into the land to ruin it.

[[v7-6-6]]

^<<v7-6-6,6>>^ And Israel became greatly impoverished due to Midʹi·an; and the sons of Israel began to call to Jehovah for aid.

[[v7-6-7]]

^<<v7-6-7,7>>^ And it came about that because the sons of Israel called to Jehovah for aid on account of Midʹi·an,

[[v7-6-8]]

^<<v7-6-8,8>>^ Jehovah proceeded to send a man, a prophet, to the sons of Israel and to say to them: “This is what Jehovah the God of Israel has said, ‘It was I who brought YOU up from Egypt and thus brought YOU out of the house of slaves.

[[v7-6-9]]

^<<v7-6-9,9>>^ So I delivered YOU out of the hand of Egypt and out of the hand of all YOUR oppressors and drove them out from before YOU and gave YOU their land.

[[v7-6-10]]

^<<v7-6-10,10>>^ Furthermore, I said to YOU: “I am Jehovah YOUR God. YOU must not fear the gods of the Amʹor·ites in whose land YOU are dwelling.” And YOU did not listen to my voice.’”

[[v7-6-11]]

^<<v7-6-11,11>>^ Later Jehovah’s angel came and sat under the big tree that was in Ophʹrah, which belonged to Joʹash the Abi-ezʹrite, while Gidʹe·on his son was beating out wheat in the winepress so as to get it quickly out of the sight of Midʹi·an.

[[v7-6-12]]

^<<v7-6-12,12>>^ Then Jehovah’s angel appeared to him and said to him: “Jehovah is with you, you valiant, mighty one.”

[[v7-6-13]]

^<<v7-6-13,13>>^ At this Gidʹe·on said to him: “Excuse me, my lord, but if Jehovah is with us, then why has all this come upon us, and where are all his wonderful acts that our fathers related to us, saying, ‘Was it not out of Egypt that Jehovah brought us up?’ And now Jehovah has deserted us, and he gives us into the palm of Midʹi·an.”

[[v7-6-14]]

^<<v7-6-14,14>>^ Upon that Jehovah^&#42;1^ faced him and said: “Go in this power of yours, and you will certainly save Israel out of Midʹi·an’s palm. Do I not send you?”

[NOTE]
====
. “Jehovah,” M; Gr., ho agʹge·los Ky·riʹou, “the angel of Jehovah.”
====

[[v7-6-15]]

^<<v7-6-15,15>>^ In turn he said to him: “Excuse me, Jehovah.^&#42;1^ With what shall I save Israel? Look! My thousand^&#42;2^ is the least in Ma·nasʹseh, and I am the smallest in my father’s house.”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. “Thousand.” A subdivision in Israel’s tribes.
====

[[v7-6-16]]

^<<v7-6-16,16>>^ But Jehovah said to him: “Because I shall prove to be with you, and you will certainly strike down Midʹi·an as if one man.”

[[v7-6-17]]

^<<v7-6-17,17>>^ At this he said to him: “If, now, I have found favor in your eyes, you must also perform a sign for me that you are the one speaking with me.

[[v7-6-18]]

^<<v7-6-18,18>>^ Do not, please, move away from here until I come to you and I have brought out my gift and set it before you.” Accordingly he said: “I, for my part, shall keep sitting here until you return.”

[[v7-6-19]]

^<<v7-6-19,19>>^ And Gidʹe·on went in and proceeded to make ready a kid of the goats and an eʹphah^&#42;1^ of flour as unfermented cakes. The meat he put in the basket, and the broth he put in the cooking pot, after which he brought it out to him under the big tree and served it.

[NOTE]
====
. About 22 L (20 dry qt).
====

[[v7-6-20]]

^<<v7-6-20,20>>^ The angel of the &#91;true&#93; God^&#42;1^ now said to him: “Take the meat and the unfermented cakes and set them on the big rock there,^&#42;2^ and pour out the broth.” At that he did so.

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElo·himʹ; LXXAVg, “Jehovah”; LXXB, “God.” See App 1F.
. Lit., “the crag over there.”
====

[[v7-6-21]]

^<<v7-6-21,21>>^ Then Jehovah’s angel thrust out the tip of the staff that was in his hand and touched the meat and the unfermented cakes, and fire began to ascend out of the rock and to consume the meat and the unfermented cakes. As for Jehovah’s angel, he vanished from his sight.

[[v7-6-22]]

^<<v7-6-22,22>>^ Consequently Gidʹe·on realized that it was Jehovah’s angel.
At once Gidʹe·on said: “Alas, Sovereign Lord Jehovah, for the reason that I have seen Jehovah’s angel face to face!”

[[v7-6-23]]

^<<v7-6-23,23>>^ But Jehovah said to him: “Peace be yours. Do not fear. You will not die.”

[[v7-6-24]]

^<<v7-6-24,24>>^ So Gidʹe·on built an altar there to Jehovah, and it continues to be called^&#42;1^ Je·hoʹvah-shaʹlom^&#42;2^ down to this day. It is yet in Ophʹrah of the Abi-ezʹrites.

[NOTE]
====
. Or, “and he proceeded to call it.”
. Meaning “Jehovah Is Peace.”
====

[[v7-6-25]]

^<<v7-6-25,25>>^ And it came about during that night that Jehovah went on to say to him: “Take the young bull, the bull that belongs to your father, that is, the second young bull of seven years, and you must tear down the altar of Baʹal that is your father’s, and the sacred pole^&#42;1^ that is by it you should cut down.

[NOTE]
====
. Or, “the Asherah.”
====

[[v7-6-26]]

^<<v7-6-26,26>>^ And you must build an altar to Jehovah your God at the head of this stronghold, with the row of stones, and you must take the second young bull and offer it up as a burnt offering on the pieces of wood of the sacred pole that you will cut down.”

[[v7-6-27]]

^<<v7-6-27,27>>^ Accordingly Gidʹe·on took ten men of his servants and went doing just as Jehovah had spoken to him; but it came about that, as he feared the household of his father and the men of the city too much to do it by day, he went doing it by night.

[[v7-6-28]]

^<<v7-6-28,28>>^ When the men of the city got up early in the morning as usual, why, look! the altar of Baʹal had been pulled down and the sacred pole that was beside it had been cut down, and the second young bull had been offered up on the altar that had been built.

[[v7-6-29]]

^<<v7-6-29,29>>^ And they began to say one to another: “Who has done this thing?” And they went inquiring and seeking. Finally they said: “Gidʹe·on the son of Joʹash is the one that has done this thing.”

[[v7-6-30]]

^<<v7-6-30,30>>^ So the men of the city said to Joʹash: “Bring your son out that he may die, because he has pulled down the altar of Baʹal, and because he has cut down the sacred pole that was by it.”

[[v7-6-31]]

^<<v7-6-31,31>>^ At this Joʹash said to all those who stood against him: “Will YOU be the ones to make a legal defense for Baʹal to see whether YOU yourselves may save him? Whoever makes a legal defense for him ought to be put to death even this morning. If he is God, let him make a legal defense for himself, because someone has pulled down his altar.”

[[v7-6-32]]

^<<v7-6-32,32>>^ And he began to call him Jer·ub·baʹal^&#42;1^ on that day, saying: “Let Baʹal make a legal defense in his own behalf, because someone has pulled down his altar.”

[NOTE]
====
. Meaning “Let Baal Make a Legal Defense Against Him.”
====

[[v7-6-33]]

^<<v7-6-33,33>>^ And all Midʹi·an and Amʹa·lek and the Easterners gathered together as one and proceeded to cross over and camp in the low plain of Jezʹre·el.

[[v7-6-34]]

^<<v7-6-34,34>>^ And Jehovah’s spirit enveloped^&#42;1^ Gidʹe·on so that he went blowing the horn,^&#42;2^ and the Abi-ezʹrites^&#42;3^ got to be called together after him.

[NOTE]
====
. Or, “clothed.”
. Or, “shofar.”
. Lit., “and Abi-ezer.”
====

[[v7-6-35]]

^<<v7-6-35,35>>^ And he sent out messengers through all of Ma·nasʹseh, and they too got to be called together after him. He also sent out messengers through Ashʹer and Zebʹu·lun and Naphʹta·li, and they came on up to meet him.^&#42;1^

[NOTE]
====
. “Him,” LXXAVg; MLXXBSy, “them.”
====

[[v7-6-36]]

^<<v7-6-36,36>>^ Then Gidʹe·on said to the &#91;true&#93; God: “If you are saving Israel by means of me, just as you have promised,

[[v7-6-37]]

^<<v7-6-37,37>>^ here I am keeping a fleece of wool exposed on the threshing floor. If dew comes to be on the fleece alone but on all the earth there is dryness, then I must know that you will save Israel by means of me, just as you have promised.”

[[v7-6-38]]

^<<v7-6-38,38>>^ And it turned out to be that way. When he rose up early the next day and wrung the fleece, he got to drain off enough dew from the fleece to fill a large banquet bowl with water.

[[v7-6-39]]

^<<v7-6-39,39>>^ However, Gidʹe·on said to the &#91;true&#93; God: “Do not let your anger blaze against me, but let me speak just once more. Let me, please, make a test only once more with the fleece. Let, please, dryness occur to the fleece alone, and upon all the earth let there come to be dew.”

[[v7-6-40]]

^<<v7-6-40,40>>^ So God did that way on that night; and dryness came to be on the fleece alone, and upon all the earth dew occurred.

'''

xref:007-judges/007-judges-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-judges/007-judges-007.adoc#v7-7-0[Próximo Capítulo &#62;]