include::./index.adoc[]

[[v7-7-0]]
=== Judges, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-7-1]]

^<<v7-7-1,1>>^ Then Jer·ub·baʹal, that is to say, Gidʹe·on, and all the people who were with him, rose early and took up camping at the well of Haʹrod;^&#42;1^ and the camp of Midʹi·an happened to be on the north of him, at the hill of Moʹreh, in the low plain.

[NOTE]
====
. Meaning “Trembling.”
====

[[v7-7-2]]

^<<v7-7-2,2>>^ Jehovah now said to Gidʹe·on: “The people who are with you are too many for me to give Midʹi·an into their hand. Perhaps Israel would brag about itself against me, saying, ‘My hand it was that saved me.’

[[v7-7-3]]

^<<v7-7-3,3>>^ And now call out, please, in the hearing of the people, saying, ‘Who is there afraid and trembling? Let him retire.’” So Gidʹe·on put them to the proof.^&#42;1^ With that, twenty-two thousand of the people retired, and there were ten thousand that remained.

[NOTE]
====
. “So Gideon put them to the proof,” by a correction; M, “and let him depart early from Mount Gilead.” Some read “Gilboa” instead of “Gilead.”
====

[[v7-7-4]]

^<<v7-7-4,4>>^ Still Jehovah said to Gidʹe·on: “There are yet too many people. Have them go down to the water that I may put them to the proof for you there. And it must occur that of whomever I say to you, ‘This one will go with you,’ he is one that will go with you, but every one of whom I say to you, ‘This one will not go along with you,’ he is one that will not go along.”

[[v7-7-5]]

^<<v7-7-5,5>>^ So he had the people go down to the water.
Then Jehovah said to Gidʹe·on: “Every one that laps up some of the water with his tongue just as a dog laps, you will set him by himself, also every one that bends down upon his knees to drink.”

[[v7-7-6]]

^<<v7-7-6,6>>^ And the number of those lapping with their hand to their mouth turned out to be three hundred men. As for all the rest of the people, they bent down upon their knees to drink water.

[[v7-7-7]]

^<<v7-7-7,7>>^ Jehovah now said to Gidʹe·on: “By the three hundred men who did the lapping I shall save YOU people, and I will give Midʹi·an into your hand. As for all the other people, let them go each one to his place.”

[[v7-7-8]]

^<<v7-7-8,8>>^ So they took the provisions of the people in their hand,^&#42;1^ and their horns, and all the men of Israel he sent away each one to his home;^&#42;2^ and he kept hold of the three hundred men. As for the camp of Midʹi·an, it happened to be down below him in the low plain.

[NOTE]
====
. Possibly, “So he took the large water jars of the people out of their hands.”
. Lit., “tents.”
====

[[v7-7-9]]

^<<v7-7-9,9>>^ And it came about during that night that Jehovah proceeded to say to him: “Rise up, descend upon the camp, for I have given it into your hand.

[[v7-7-10]]

^<<v7-7-10,10>>^ But if you are afraid to descend, descend, you with Puʹrah your attendant,^&#42;1^ to the camp.

[NOTE]
====
. Or, “young man; lad; boy.”
====

[[v7-7-11]]

^<<v7-7-11,11>>^ And you must listen to what they will speak, and afterward your hands will certainly grow strong, and you will be certain to descend upon the camp.” At that he and Puʹrah his attendant made their descent to the edge of those in battle formation who were in the camp.

[[v7-7-12]]

^<<v7-7-12,12>>^ Now Midʹi·an and Amʹa·lek and all the Easterners were plumped in the low plain as numerous as locusts; and their camels were without number, as numerous as the grains of sand that are on the seashore.

[[v7-7-13]]

^<<v7-7-13,13>>^ Gidʹe·on now came, and, look! there was a man relating a dream to his companion, and he went on to say: “Here is a dream that I have dreamed. And, look! there was a round cake of barley bread turning over and over into the camp of Midʹi·an. Then it came to a tent and struck it so that it fell, and it went turning it upside down, and the tent fell flat.”

[[v7-7-14]]

^<<v7-7-14,14>>^ At this his companion answered and said: “This is nothing else but the sword of Gidʹe·on the son of Joʹash, a man of Israel. The &#91;true&#93; God has given Midʹi·an and all the camp into his hand.”

[[v7-7-15]]

^<<v7-7-15,15>>^ And it came about that as soon as Gidʹe·on heard the relating of the dream and its explanation, he began to worship.^&#42;1^ After that he returned to the camp of Israel and said: “Get up, for Jehovah has given the camp of Midʹi·an into YOUR hand.”

[NOTE]
====
. Or, “to bow down (prostrate himself).”
====

[[v7-7-16]]

^<<v7-7-16,16>>^ Then he divided the three hundred men up into three bands and put horns in the hands of all of them and large empty jars, and torches inside the large jars.

[[v7-7-17]]

^<<v7-7-17,17>>^ And he went on to say to them: “YOU should learn from watching me,^&#42;1^ and that is how YOU should do. And when I am come to the edge of the camp, it must also occur that just as I shall do, so YOU will do.

[NOTE]
====
. Lit., “From me you should see.”
====

[[v7-7-18]]

^<<v7-7-18,18>>^ When I have blown the horn, I and all who are with me, YOU also must blow the horns, YOU too, round about all the camp, and YOU must say, ‘Jehovah’s and Gidʹe·on’s!’”

[[v7-7-19]]

^<<v7-7-19,19>>^ In time Gidʹe·on came with the hundred men who were with him to the edge of the camp at the start of the middle night watch. They had just got through posting the sentries. And they proceeded to blow the horns, and there was a dashing to pieces of the large water jars that were in their hands.

[[v7-7-20]]

^<<v7-7-20,20>>^ At that the three bands blew the horns and shattered the large jars and took fresh hold on the torches with their left hand and with their right hand on the horns to blow them, and they began calling out: “Jehovah’s sword and Gidʹe·on’s!”

[[v7-7-21]]

^<<v7-7-21,21>>^ All the while they kept standing each one in his place all around the camp, and the whole camp got on the run and broke out into shouting and went fleeing.

[[v7-7-22]]

^<<v7-7-22,22>>^ And the three hundred continued to blow the horns, and Jehovah proceeded to set the sword of each one against the other in all the camp; and the camp kept up their flight as far as Beth-shitʹtah, on to Zerʹe·rah,^&#42;1^ as far as the outskirts of Aʹbel-me·hoʹlah by Tabʹbath.

[NOTE]
====
. Possibly the same as “Zarethan” in 1Ki 4:12; “Zeredah,” in 20 Heb. mss.
====

[[v7-7-23]]

^<<v7-7-23,23>>^ Meantime the men of Israel were called together from Naphʹta·li and Ashʹer and all of Ma·nasʹseh, and they went chasing after Midʹi·an.

[[v7-7-24]]

^<<v7-7-24,24>>^ And Gidʹe·on sent messengers into all the mountainous region of Eʹphra·im, saying: “Go down to meet Midʹi·an and capture ahead of them the waters as far as Beth-barʹah and the Jordan.” So all the men of Eʹphra·im were called together, and they got to capture the waters as far as Beth-barʹah and the Jordan.

[[v7-7-25]]

^<<v7-7-25,25>>^ They also got to capture the two princes of Midʹi·an, namely, Oʹreb and Zeʹeb; and they proceeded to kill Oʹreb on the rock of Oʹreb, and they killed Zeʹeb at the wine vat of Zeʹeb. And they kept on pursuing Midʹi·an, and they brought the head of Oʹreb and that of Zeʹeb to Gidʹe·on in the region of the Jordan.^&#42;1^

[NOTE]
====
. Or, “in the borderland of Jordan”; or, “in Jordan-land.”
====

'''

xref:007-judges/007-judges-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-judges/007-judges-008.adoc#v7-8-0[Próximo Capítulo &#62;]