include::./index.adoc[]

[[v7-18-0]]
=== Judges, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-18-1]]

^<<v7-18-1,1>>^ In those days there was no king in Israel. And in those days the tribe of the Danʹites was looking for an inheritance for itself to dwell there; because up to that day an inheritance had not fallen to them in the midst of the tribes of Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ Eventually the sons of Dan sent five men of their family, men from among them, men who were valiant fellows, out from Zoʹrah and Eshʹta·ol, to spy out the land and to explore it. So they said to them: “Go, explore the land.” In time they came into the mountainous region of Eʹphra·im as far as the house of Miʹcah and got to spend the night there.

[[v7-18-3]]

^<<v7-18-3,3>>^ While they were close by the house of Miʹcah, they recognized the voice of the young man, the Levite, so that they turned aside there. And they proceeded to say to him: “Who brought you here, and what are you doing in this place, and what interest do you have here?”

[[v7-18-4]]

^<<v7-18-4,4>>^ In turn he said to them: “Thus and so Miʹcah did for me that he might hire me, and that I might serve as priest for him.”

[[v7-18-5]]

^<<v7-18-5,5>>^ Then they said to him: “Inquire, please, of God that we may know whether our way on which we are going will be successful.”

[[v7-18-6]]

^<<v7-18-6,6>>^ So the priest said to them: “Go in peace. It is before Jehovah that YOUR way is in which YOU go.”

[[v7-18-7]]

^<<v7-18-7,7>>^ Accordingly the five men went on and came to Laʹish and saw how the people that were within it were dwelling in self-reliance according to the custom of the Si·doʹni·ans, quiet and unsuspecting, and there was no oppressive conqueror^&#42;1^ that was molesting a thing in the land, while they were far off from the Si·doʹni·ans and they had nothing to do with mankind.^&#42;2^

[NOTE]
====
. Or, “oppressive dispossessor.” Lit., “dispossessor (occupier) of oppression.” See VT, Vol. II, 1952, pp. 67-69.
. “With Syria,” LXXASymSyHexapla.
====

[[v7-18-8]]

^<<v7-18-8,8>>^ At length they came to their brothers at Zoʹrah and Eshʹta·ol, and their brothers began to say to them: “How was it with YOU?”

[[v7-18-9]]

^<<v7-18-9,9>>^ At this they said: “Do get up, and let us go up against them; for we have seen the land, and, look! it is very good. And YOU are hesitant. Do not be sluggish about walking to come in to take possession of the land.

[[v7-18-10]]

^<<v7-18-10,10>>^ When YOU come in, YOU will come to an unsuspecting people, and the land is quite wide;^&#42;1^ for God^&#42;2^ has given it into YOUR hand, a place where there is no lack of any sort of thing that is in the earth.”

[NOTE]
====
. Lit., “wide on both sides,” that is, spacious.
. “God,” MLXXSy; TVg, “Jehovah.”
====

[[v7-18-11]]

^<<v7-18-11,11>>^ Then six hundred men girded with weapons of war, out of the family of the Danʹites, departed from there, that is, from Zoʹrah and Eshʹta·ol.

[[v7-18-12]]

^<<v7-18-12,12>>^ And they got on their way up and went camping at Kirʹi·ath-jeʹa·rim in Judah. That is why they have called that place Maʹha·neh-dan^&#42;1^ down to this day. Look! It is west^&#42;2^ of Kirʹi·ath-jeʹa·rim.

[NOTE]
====
. Meaning “Camp of Dan.”
. Lit., “to the rear,” that is, when one faces east.
====

[[v7-18-13]]

^<<v7-18-13,13>>^ After that they passed along from there to the mountainous region of Eʹphra·im and came as far as the house of Miʹcah.

[[v7-18-14]]

^<<v7-18-14,14>>^ Then the five men that had gone to spy out the land of Laʹish answered and said to their brothers: “Did YOU know that there are in these houses an ephʹod and teraphim and a carved image and a molten statue? And now have in mind what YOU ought to do.”

[[v7-18-15]]

^<<v7-18-15,15>>^ So they turned aside there and came to the house of the young man, the Levite, at the house of Miʹcah, and began to ask how he was getting along.

[[v7-18-16]]

^<<v7-18-16,16>>^ All the while the six hundred men girded with their weapons of war, who were of the sons of Dan, were standing at the entrance of the gate.

[[v7-18-17]]

^<<v7-18-17,17>>^ The five men that had gone to spy out the land now went on up, that they might enter in there to take^&#42;1^ the carved image and the ephʹod and the teraphim and the molten image. (And the priest was standing at the entrance of the gate with the six hundred men girded with weapons of war.)^&#42;2^

[NOTE]
====
. Lit., “went on up, they entered in there, they took.”
. Or, “and the molten image and the priest, while the six hundred men girded with weapons of war were standing at the entrance of the gate.”
====

[[v7-18-18]]

^<<v7-18-18,18>>^ And these went into the house of Miʹcah and proceeded to take the carved image, the ephʹod and the teraphim and the molten image. At that the priest said to them: “What are YOU doing?”

[[v7-18-19]]

^<<v7-18-19,19>>^ But they said to him: “Be quiet. Put your hand over your mouth, and go with us and become a father and a priest for us. Which is better, for you to continue a priest to the house of one man or for you to become a priest to a tribe and family in Israel?”

[[v7-18-20]]

^<<v7-18-20,20>>^ At this the heart of the priest was pleased, and he now took the ephʹod and the teraphim and the carved image and came into the midst of the people.

[[v7-18-21]]

^<<v7-18-21,21>>^ Then they turned and went their way and put the little ones and the livestock and the valuable things ahead of them.

[[v7-18-22]]

^<<v7-18-22,22>>^ They themselves had got a distance away from the house of Miʹcah when the men who were in the houses that were close by the house of Miʹcah were called together and tried to catch up with the sons of Dan.

[[v7-18-23]]

^<<v7-18-23,23>>^ When they kept crying out to the sons of Dan, then they turned their faces and said to Miʹcah: “What is the matter with you that you have been called together?”

[[v7-18-24]]

^<<v7-18-24,24>>^ So he said: “My gods that I made YOU have taken, the priest too, and YOU go YOUR way, and what do I have anymore? How, then, is it that YOU can say to me, ‘What is the matter with you?’”

[[v7-18-25]]

^<<v7-18-25,25>>^ At this the sons of Dan said to him: “Do not let your voice be heard close to us, for fear that men bitter of soul may assault YOU people, and you have to forfeit your own soul^&#42;1^ and the soul of your household.”

[NOTE]
====
. “Your own soul (life).” Heb., naph·shekhaʹ; LXXA(Gr.), psy·khenʹ sou; Syr., naph·shakh.
====

[[v7-18-26]]

^<<v7-18-26,26>>^ And the sons of Dan kept going on their way; and Miʹcah got to see that they were stronger than he was, and so he turned and went back to his house.

[[v7-18-27]]

^<<v7-18-27,27>>^ As for them, they took what Miʹcah had made and the priest that had become his, and they kept going toward Laʹish, against a people quiet and unsuspecting. And they proceeded to strike them with the edge of the sword, and the city they burned with fire.

[[v7-18-28]]

^<<v7-18-28,28>>^ And there was no deliverer, for it was far away from Siʹdon, and they had nothing at all to do with mankind; and it was in the low plain that belonged to Beth-reʹhob. Then they built the city and took up dwelling in it.

[[v7-18-29]]

^<<v7-18-29,29>>^ Furthermore, they called the name of the city Dan by the name of their father, Dan, who had been born to Israel. Nevertheless, Laʹish was the city’s name at first.

[[v7-18-30]]

^<<v7-18-30,30>>^ After that the sons of Dan stood up the carved image for themselves; and Jonʹa·than^&#42;1^ the son of Gerʹshom, Moses’^&#42;2^ son, he and his sons became priests to the tribe of the Danʹites until the day of the land’s^&#42;3^ being taken into exile.

[NOTE]
====
. Lit., “Jehonathan,” meaning “Jehovah Gave.”
. “Moses’,” LXXAVg; MLXXBSy, “Manasseh’s.” Out of regard for Moses the scribes inserted the suspended Heb. letter Nun, “n,” in the original name in M, making it read “Manasseh’s.”
. “The land’s.” Heb., ha·ʼaʹrets. Some contend that this should read “ark’s” (ארון, ʼarohnʹ) instead of “land’s” (ארץ, ʼaʹrets), referring to 1Sa 4:3–7:2.
====

[[v7-18-31]]

^<<v7-18-31,31>>^ And they kept the carved image of Miʹcah, which he had made, set up for themselves all the days that the house of the &#91;true&#93; God continued in Shiʹloh.

'''

xref:007-judges/007-judges-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-judges/007-judges-019.adoc#v7-19-0[Próximo Capítulo &#62;]