include::./index.adoc[]

[[v7-14-0]]
=== Judges, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-14-1]]

^<<v7-14-1,1>>^ Then Samson went down to Timʹnah and saw a woman in Timʹnah of the daughters of the Phi·lisʹtines.

[[v7-14-2]]

^<<v7-14-2,2>>^ So he went up and told his father and his mother and said: “There is a woman that I have seen in Timʹnah of the daughters of the Phi·lisʹtines, and now get her for me as a wife.”

[[v7-14-3]]

^<<v7-14-3,3>>^ But his father and his mother said to him: “Is there not among the daughters of your brothers and among all my people a woman, so that you are going to take a wife from the uncircumcised Phi·lisʹtines?” Still Samson said to his father: “Get just her for me, because she is the one just right in my eyes.”

[[v7-14-4]]

^<<v7-14-4,4>>^ As for his father and his mother, they did not know that that was from Jehovah, that he was looking for an opportunity against the Phi·lisʹtines, as at that particular time the Phi·lisʹtines were ruling over Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Accordingly Samson went on down with his father and his mother to Timʹnah. When he^&#42;1^ got as far as the vineyards of Timʹnah, why, look! a maned young lion roaring upon meeting him.

[NOTE]
====
. “He,” LXX; MVg, “they.”
====

[[v7-14-6]]

^<<v7-14-6,6>>^ Then Jehovah’s spirit became operative upon him, so that he tore it in two, just as someone tears a male kid in two, and there was nothing at all in his hand. And he did not tell his father or his mother what he had done.

[[v7-14-7]]

^<<v7-14-7,7>>^ And he continued on his way down and began to speak to the woman; and she was still right in Samson’s eyes.

[[v7-14-8]]

^<<v7-14-8,8>>^ Now after a while he went on back to take her home. Meantime he turned aside to look at the carcass of the lion,^&#42;1^ and there there was a swarm of bees in the lion’s corpse, and honey.

[NOTE]
====
. “The lion.” Heb., ha·ʼar·yehʹ, the African lion.
====

[[v7-14-9]]

^<<v7-14-9,9>>^ So he scraped it out into his palms and walked on, eating as he walked.^&#42;1^ When he rejoined^&#42;2^ his father and his mother, he at once gave them some, and they began to eat. And he did not tell them that it was out of the corpse of the lion that he had scraped the honey.

[NOTE]
====
. Lit., “walking and eating.” In Heb. these are verbs in the infinitive absolute, indefinite as to time.
. Lit., “walked to.”
====

[[v7-14-10]]

^<<v7-14-10,10>>^ And his father continued on his way down to the woman, and Samson proceeded to hold a banquet there; for that was the way the young fellows used to do.

[[v7-14-11]]

^<<v7-14-11,11>>^ And it came about that, on their seeing him, they immediately took thirty groomsmen, that these should keep with him.

[[v7-14-12]]

^<<v7-14-12,12>>^ Then Samson said to them: “Let me, please, propound a riddle to YOU. If YOU will without fail tell it to me during the seven days of the banquet and YOU do solve it, I shall in that case have to give YOU thirty undergarments and thirty outfits of clothing.

[[v7-14-13]]

^<<v7-14-13,13>>^ But if YOU are unable to tell it to me, YOU yourselves also must give me thirty undergarments and thirty outfits of clothing.” At this they said to him: “Do propound your riddle, and let us hear it.”

[[v7-14-14]]

^<<v7-14-14,14>>^ So he said to them:
“Out of the eater something to eat came forth,
And out of the strong something sweet came forth.”
And they proved unable to tell the riddle for three days.

[[v7-14-15]]

^<<v7-14-15,15>>^ And it came about on the fourth^&#42;1^ day that they began to say to Samson’s wife: “Fool your husband that he may tell us the riddle. Otherwise we shall burn you and the house of your father with fire. Was it to take our possessions that YOU people invited us here?”

[NOTE]
====
. “Fourth,” LXXSy; MVg, “seventh.”
====

[[v7-14-16]]

^<<v7-14-16,16>>^ Consequently Samson’s wife began to weep over him and to say: “You only hate me, you do, and you do not love me. There was a riddle that you propounded to the sons of my people, but to me you have not told it.” At this he said to her: “Why, to my own father and my own mother I have not told it, and ought I to tell it to you?”

[[v7-14-17]]

^<<v7-14-17,17>>^ But she kept weeping over him the seven days that the banquet continued for them, and it came about on the seventh day that finally he told her, because she had pressured him. Then she told the riddle to the sons of her people.

[[v7-14-18]]

^<<v7-14-18,18>>^ So the men of the city said to him on the seventh day before ever he could go into the interior room:^&#42;1^
“What is sweeter than honey,
And what is stronger than a lion?”
In turn he said to them:
“If YOU had not plowed with my young cow,
YOU would not have solved my riddle.”

[NOTE]
====
. “Before ever he could go into the interior room,” by an emendation; Sy, “before he could go to the banquet”; MLXXAVg, “before ever the sun set”; LXXB, “before the sun rose.” Compare 15:1.
====

[[v7-14-19]]

^<<v7-14-19,19>>^ And Jehovah’s spirit became operative upon him, so that he went down to Ashʹke·lon and struck down thirty men of theirs and took what he stripped off them and gave the outfits to the tellers of the riddle. And his anger continued hot, and he went his way up to his father’s house.

[[v7-14-20]]

^<<v7-14-20,20>>^ And Samson’s wife came to belong to a groomsman of his who had associated with him.

'''

xref:007-judges/007-judges-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-judges/007-judges-015.adoc#v7-15-0[Próximo Capítulo &#62;]