include::./index.adoc[]

[[v7-3-0]]
=== Judges, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-3-1]]

^<<v7-3-1,1>>^ Now these are the nations that Jehovah let stay so as by them to test Israel, that is, all those who had not experienced any of the wars of Caʹnaan;

[[v7-3-2]]

^<<v7-3-2,2>>^ it was only in order for the generations of the sons of Israel to have the experience, so as to teach them war, that is, only those who before that had not experienced such things:

[[v7-3-3]]

^<<v7-3-3,3>>^ The five axis lords^&#42;1^ of the Phi·lisʹtines, and all the Caʹnaan·ites, even the Si·doʹni·ans and the Hiʹvites inhabiting Mount Lebʹa·non from Mount Baʹal-herʹmon as far as to the entering in of Haʹmath.^&#42;2^

[NOTE]
====
. “Satrapies,” Gr., sa·tra·peiʹas; Lat., saʹtra·pas, “satraps.” See Jos 13:3 ftn, “Lords.”
. See Jos 13:5 ftn, “Hamath.”
====

[[v7-3-4]]

^<<v7-3-4,4>>^ And they kept serving as agents to test Israel so as to know whether they would obey Jehovah’s commandments that he had commanded their fathers by means of Moses.

[[v7-3-5]]

^<<v7-3-5,5>>^ And the sons of Israel dwelt in among the Caʹnaan·ites, the Hitʹtites and the Amʹor·ites and the Perʹiz·zites and the Hiʹvites and the Jebʹu·sites.

[[v7-3-6]]

^<<v7-3-6,6>>^ And they proceeded to take their daughters as wives for themselves, and their own daughters they gave to their sons, and they took up serving their gods.

[[v7-3-7]]

^<<v7-3-7,7>>^ So the sons of Israel did what was bad in Jehovah’s eyes, and they were forgetful of Jehovah their God and went serving the Baʹals and the sacred poles.^&#42;1^

[NOTE]
====
. Or, “the Asherim.”
====

[[v7-3-8]]

^<<v7-3-8,8>>^ At this Jehovah’s anger blazed against Israel, so that he sold them into the hand of Cuʹshan-rish·a·thaʹim the king of Mes·o·po·taʹmi·a;^&#42;1^ and the sons of Israel continued to serve Cuʹshan-rish·a·thaʹim eight years.

[NOTE]
====
. “Mesopotamia,” Vg; M, “Aram-naharaim”; LXX, “Syria of [the] rivers.”
====

[[v7-3-9]]

^<<v7-3-9,9>>^ And the sons of Israel began to call to Jehovah for aid. Then Jehovah raised a savior up for the sons of Israel that he might save them, Othʹni·el the son of Keʹnaz, the younger brother of Caʹleb.

[[v7-3-10]]

^<<v7-3-10,10>>^ The spirit of Jehovah now came upon him, and he became the judge of Israel. When he went out to battle, then Jehovah gave Cuʹshan-rish·a·thaʹim the king of Syria^&#42;1^ into his hand so that his hand overpowered Cuʹshan-rish·a·thaʹim.

[NOTE]
====
. “Syria [of rivers],” LXXAVg; M, “Aram.”
====

[[v7-3-11]]

^<<v7-3-11,11>>^ After that the land had no disturbance for forty years. Eventually Othʹni·el the son of Keʹnaz died.

[[v7-3-12]]

^<<v7-3-12,12>>^ And once again the sons of Israel went doing what was bad in Jehovah’s eyes. At that Jehovah let Egʹlon the king of Moʹab grow strong against Israel, because they did what was bad in Jehovah’s eyes.

[[v7-3-13]]

^<<v7-3-13,13>>^ Furthermore, he gathered against them the sons of Amʹmon and Amʹa·lek. Then they went and struck Israel and took possession of the city of palm trees.

[[v7-3-14]]

^<<v7-3-14,14>>^ And the sons of Israel continued to serve Egʹlon the king of Moʹab eighteen years.

[[v7-3-15]]

^<<v7-3-15,15>>^ And the sons of Israel began to call to Jehovah for aid. So Jehovah raised up for them a savior, Eʹhud the son of Geʹra, a Benʹja·mite, a left-handed man.^&#42;1^ In time the sons of Israel sent tribute^&#42;2^ by his hand to Egʹlon the king of Moʹab.

[NOTE]
====
. Lit., “a man closed (impeded) of his right hand,” M; LXX, “ambidextrous.” Compare 20:16.
. Or, “gift.”
====

[[v7-3-16]]

^<<v7-3-16,16>>^ Meanwhile Eʹhud made a sword for himself, and it had two edges, its length being a cubit.^&#42;1^ Then he girded it underneath his garment upon his right thigh.

[NOTE]
====
. “A span,” LXX; Vg, “a palm of the hand”; Heb., goʹmedh, an uncertain linear measure. Some believe it was a short cubit of about 38 cm (15 in.), measured from the elbow to the knuckles of the clenched hand.
====

[[v7-3-17]]

^<<v7-3-17,17>>^ And he proceeded to present the tribute to Egʹlon the king of Moʹab. Now Egʹlon was a very fat man.

[[v7-3-18]]

^<<v7-3-18,18>>^ And it came about that when he had finished presenting the tribute, he at once sent the people away, the bearers of the tribute.

[[v7-3-19]]

^<<v7-3-19,19>>^ And he himself turned back at the quarries^&#42;1^ that were at Gilʹgal, and he proceeded to say: “I have a secret word for you, O king.” So he said: “Keep silence!” With that all those who were standing by him went on out from him.

[NOTE]
====
. Or, “[carved] images.”
====

[[v7-3-20]]

^<<v7-3-20,20>>^ And Eʹhud came to him as he was sitting in his cool roof chamber that he had to himself. And Eʹhud went on to say: “A word of God I have for you.” At that he rose up from his throne.

[[v7-3-21]]

^<<v7-3-21,21>>^ Then Eʹhud thrust in his left hand and took the sword off his right thigh and plunged it into his belly.

[[v7-3-22]]

^<<v7-3-22,22>>^ And the handle kept going in also after the blade so that the fat closed in over the blade, for he did not draw the sword out of his belly, and the fecal matter began to come out.^&#42;1^

[NOTE]
====
. Or, “and he made his way out through the loophole.” Vg, “and at once through the secret parts of nature the excrements of the belly broke forth.”
====

[[v7-3-23]]

^<<v7-3-23,23>>^ And Eʹhud proceeded to go out through the air hole,^&#42;1^ but he closed the doors of the roof chamber behind him and locked them.

[NOTE]
====
. Or, “the porch”; or, “the privy.”
====

[[v7-3-24]]

^<<v7-3-24,24>>^ And he himself went out.
And his servants came and began looking, and there the doors of the roof chamber were locked. So they said: “He is just easing nature^&#42;1^ in the cool interior room.”

[NOTE]
====
. Lit., “He is just keeping his feet hidden.”
====

[[v7-3-25]]

^<<v7-3-25,25>>^ And they kept waiting until they were ashamed, and, look! there was no one opening the doors of the roof chamber. At this they took the key and opened them, and, look! their lord^&#42;1^ was fallen to the earth dead!

[NOTE]
====
. “Their lord.” Heb., ʼadho·neh·hemʹ, pl. to denote excellence; Gr., kyʹri·os, sing.; Lat., doʹmi·num, sing.
====

[[v7-3-26]]

^<<v7-3-26,26>>^ As for Eʹhud, he escaped while they were lingering, and he himself passed by the quarries and made his escape to Se·iʹrah.

[[v7-3-27]]

^<<v7-3-27,27>>^ And it came about that when he got there he began blowing the horn^&#42;1^ in the mountainous region of Eʹphra·im; and the sons of Israel began going down with him out of the mountainous region, he being at their head.

[NOTE]
====
. Lit., “on the horn (shofar).” Heb., bash·shoh·pharʹ.
====

[[v7-3-28]]

^<<v7-3-28,28>>^ Then he said to them: “Follow me, because Jehovah has given YOUR enemies, the Moʹab·ites, into YOUR hand.” And they went following him and got to capture the fords of the Jordan against the Moʹab·ites, and they did not allow anybody to pass over.

[[v7-3-29]]

^<<v7-3-29,29>>^ And at that time they went striking down Moʹab, about ten thousand men, every one robust^&#42;1^ and every one a valiant man; and not a single one escaped.

[NOTE]
====
. Or, “fat.”
====

[[v7-3-30]]

^<<v7-3-30,30>>^ And Moʹab came to be subdued on that day under Israel’s hand; and the land had no further disturbance for eighty years.

[[v7-3-31]]

^<<v7-3-31,31>>^ And after him there proved to be Shamʹgar the son of Aʹnath, and he went striking down the Phi·lisʹtines, six hundred men, with a cattle goad; and he too got to save Israel.

'''

xref:007-judges/007-judges-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-judges/007-judges-004.adoc#v7-4-0[Próximo Capítulo &#62;]