include::./index.adoc[]

[[v7-20-0]]
=== Judges, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-20-1]]

^<<v7-20-1,1>>^ Consequently all the sons of Israel went out and the assembly congregated themselves as one man, from Dan down to Beʹer-sheʹba^&#42;1^ along with the land of Gilʹe·ad, to Jehovah at Mizʹpah.

[NOTE]
====
. “From Dan down to Beer-sheba.” Heb., lemid·Danʹ weʽadh-Beʼerʹ Sheʹvaʽ; the first occurrence of this expression.
====

[[v7-20-2]]

^<<v7-20-2,2>>^ So the keymen^&#42;1^ of all the people and all the tribes of Israel took their station in the congregation^&#42;2^ of the people of the &#91;true&#93; God, four hundred thousand men on foot who drew the sword.

[NOTE]
====
. Lit., “the corner towers,” pictorial of vital or important men, chiefs.
. “Congregation of.” Gr., ek·kle·siʹai; Lat., ec·cleʹsi·am.
====

[[v7-20-3]]

^<<v7-20-3,3>>^ And the sons of Benjamin got to hear that the sons of Israel had gone up to Mizʹpah.
Then the sons of Israel said: “SPEAK. How has this bad thing been brought about?”

[[v7-20-4]]

^<<v7-20-4,4>>^ At this the man, the Levite, the husband of the murdered woman, answered and said: “It was to Gibʹe·ah, which belongs to Benjamin, that I came, I and my concubine, to stay overnight.

[[v7-20-5]]

^<<v7-20-5,5>>^ And the landowners of Gibʹe·ah proceeded to rise up against me and to surround the house against me by night. It was I that they figured on killing, but it was my concubine that they raped, and she gradually died.

[[v7-20-6]]

^<<v7-20-6,6>>^ Hence I grasped my concubine and cut her up and sent her into every field of Israel’s inheritance, because they had carried on loose conduct and disgraceful folly in Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Look! All YOU sons of Israel, give YOUR word and counsel here.”

[[v7-20-8]]

^<<v7-20-8,8>>^ So all the people rose up as one man, saying: “We shall not go any of us to his tent, nor shall we turn aside any of us to his house.

[[v7-20-9]]

^<<v7-20-9,9>>^ And now this is the thing that we shall do to Gibʹe·ah. Let us go up^&#42;1^ by lot against it.

[NOTE]
====
. “Let us go up,” LXX; M ­omits.
====

[[v7-20-10]]

^<<v7-20-10,10>>^ And we must take ten men out of a hundred of all the tribes of Israel, and a hundred out of a thousand, and a thousand out of ten thousand, to procure provisions for the people, that they may take action by going against Gibʹe·ah^&#42;1^ of Benjamin, in view of all the disgraceful folly that they^&#42;2^ did in Israel.”

[NOTE]
====
. “Gibeah.” Lit., “Geba.” Both names mean “Hill.”
. “They,” LXXASy; M, “it.”
====

[[v7-20-11]]

^<<v7-20-11,11>>^ Thus all the men of Israel were gathered against the city as one man, as allies.

[[v7-20-12]]

^<<v7-20-12,12>>^ Accordingly the tribes of Israel sent men to all the tribesmen^&#42;1^ of Benjamin, saying: “What is this bad thing that has been brought about among YOU?

[NOTE]
====
. Lit., “tribes,” M; LXXVg, “tribe”; Sy, “house.”
====

[[v7-20-13]]

^<<v7-20-13,13>>^ And now give over the men, the good-for-nothing men, that are in Gibʹe·ah, that we may put them to death, and let us clear out what is bad from Israel.” And the sons of Benjamin^&#42;1^ did not want to listen to the voice of their brothers, the sons of Israel.

[NOTE]
====
. “The sons of Benjamin,” TLXXSy and the qere of 32 Heb. mss (with vowel points for “sons of,” but without the Heb. consonants, placed in front of “Benjamin”). It is qere but not kethib (read but not written).
====

[[v7-20-14]]

^<<v7-20-14,14>>^ Then the sons of Benjamin went gathering together out of the cities to Gibʹe·ah to go out to battle against the sons of Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ So the sons of Benjamin got to be mustered on that day from the cities, twenty-six thousand men drawing sword, apart from the inhabitants of Gibʹe·ah, of whom seven hundred chosen men were mustered.

[[v7-20-16]]

^<<v7-20-16,16>>^ Out of all this people there were seven hundred chosen men left-handed.^&#42;1^ Every one of these was a slinger of stones to a hairbreadth and would not miss.

[NOTE]
====
. “Ambidextrous,” LXX. See 3:15 ftn, “Man.”
====

[[v7-20-17]]

^<<v7-20-17,17>>^ And the men of Israel were mustered apart from Benjamin, four hundred thousand men drawing sword. Every one of these was a man of war.

[[v7-20-18]]

^<<v7-20-18,18>>^ And they proceeded to rise up and go on up to Bethʹel and to inquire of God. Then the sons of Israel said: “Who of us should go up in the lead to the battle against the sons of Benjamin?” To this Jehovah said: “Judah in the lead.”

[[v7-20-19]]

^<<v7-20-19,19>>^ After that the sons of Israel rose up in the morning and camped against Gibʹe·ah.

[[v7-20-20]]

^<<v7-20-20,20>>^ The men of Israel now went out to battle against Benjamin; and the men of Israel proceeded to draw up in battle formation against them at Gibʹe·ah.

[[v7-20-21]]

^<<v7-20-21,21>>^ So the sons of Benjamin came on out from Gibʹe·ah and brought twenty-two thousand men in Israel down to ruin to the earth on that day.

[[v7-20-22]]

^<<v7-20-22,22>>^ However, the people, the men of Israel, showed themselves courageous and again went drawing up in battle formation in the place where they had drawn up in formation on the first day.

[[v7-20-23]]

^<<v7-20-23,23>>^ Then the sons of Israel went up and wept before Jehovah until the evening and inquired of Jehovah, saying: “Shall I again approach for battle against the sons of Benjamin my brother?” To this Jehovah said: “Go up against him.”

[[v7-20-24]]

^<<v7-20-24,24>>^ Accordingly the sons of Israel drew near to the sons of Benjamin on the second day.

[[v7-20-25]]

^<<v7-20-25,25>>^ In turn Benjamin came on out from Gibʹe·ah to meet them on the second day and brought a further eighteen thousand men among the sons of Israel down to ruin to the earth, all of these drawing sword.

[[v7-20-26]]

^<<v7-20-26,26>>^ At that all the sons of Israel, even all the people, went on up and came to Bethʹel^&#42;1^ and wept and sat there before Jehovah and fasted on that day until the evening and offered up burnt offerings and communion offerings before Jehovah.

[NOTE]
====
. “Came to the house of God,” Vg.
====

[[v7-20-27]]

^<<v7-20-27,27>>^ After that the sons of Israel inquired of Jehovah, as it was there that the ark of the covenant of the &#91;true&#93; God was in those days.

[[v7-20-28]]

^<<v7-20-28,28>>^ Now Phinʹe·has the son of El·e·aʹzar, the son of Aaron, was standing before it in those days, saying: “Shall I go out yet again to battle against the sons of Benjamin my brother or shall I cease to?” To this Jehovah said: “Go up, because tomorrow I shall give him into your hand.”

[[v7-20-29]]

^<<v7-20-29,29>>^ Then Israel set men in ambush against Gibʹe·ah all around.

[[v7-20-30]]

^<<v7-20-30,30>>^ And the sons of Israel proceeded to go up against the sons of Benjamin on the third day, and to draw up in formation against Gibʹe·ah the same as at the other times.

[[v7-20-31]]

^<<v7-20-31,31>>^ When the sons of Benjamin went on out to meet the people, they were drawn away from the city. Then, the same as at the other times, they started to strike down some of the people mortally wounded on the highways, one of which goes up to Bethʹel and the other to Gibʹe·ah, in the field, about thirty men in Israel.

[[v7-20-32]]

^<<v7-20-32,32>>^ So the sons of Benjamin began to say: “They are suffering defeat before us the same as at the first.” As for the sons of Israel, they said: “Let us flee, and we shall certainly draw them away from the city onto the highways.”

[[v7-20-33]]

^<<v7-20-33,33>>^ And all the men of Israel rose up from their places and went drawing up in formation at Baʹal-taʹmar, while those of Israel in ambush were making a charge out of their places in the vicinity of Gibʹe·ah.

[[v7-20-34]]

^<<v7-20-34,34>>^ Thus ten thousand chosen men out of all Israel came in front of Gibʹe·ah, and the fighting was heavy; and the Benʹja·mites^&#42;1^ did not know that calamity was impending over them.

[NOTE]
====
. Lit., “and they.”
====

[[v7-20-35]]

^<<v7-20-35,35>>^ And Jehovah proceeded to defeat Benjamin before Israel, so that the sons of Israel on that day brought down to ruin in Benjamin twenty-five thousand one hundred men, all of these drawing sword.

[[v7-20-36]]

^<<v7-20-36,36>>^ However, the sons of Benjamin imagined that the men of Israel faced defeat when they kept giving ground to Benjamin because they trusted in the ambush that they had set against Gibʹe·ah.

[[v7-20-37]]

^<<v7-20-37,37>>^ As for the ambush, they acted quickly and went dashing toward Gibʹe·ah. Then the ambush spread out and struck all the city with the edge of the sword.

[[v7-20-38]]

^<<v7-20-38,38>>^ Now the men of Israel had come to the arrangement with the ambush^&#42;1^ for them to make a smoke signal^&#42;2^ go up from the city.

[NOTE]
====
. “The ambush.” Heb., ha·ʼo·revʹ. The following word heʹrev is to be omitted because of an evident dittography.
. Lit., “an uplifting of the smoke.”
====

[[v7-20-39]]

^<<v7-20-39,39>>^ When the sons of Israel turned around in the battle, Benjamin started to strike down about thirty men mortally wounded among the men of Israel, for they said: “They are unquestionably suffering nothing but defeat before us just as in the first battle.”

[[v7-20-40]]

^<<v7-20-40,40>>^ And the signal started to go up from the city as a pillar of smoke. So when Benjamin turned his face back, look! the whole city went up heavenward.

[[v7-20-41]]

^<<v7-20-41,41>>^ And the men of Israel made an about-face, and the men of Benjamin were disturbed, for they saw that calamity had reached them.

[[v7-20-42]]

^<<v7-20-42,42>>^ Hence they turned before the men of Israel in the direction of the wilderness, and the battle followed them up closely, while the men from out of the cities were bringing them down to ruin in their midst.

[[v7-20-43]]

^<<v7-20-43,43>>^ They surrounded Benjamin. They pursued him without a place to rest. They trampled him down directly in front of Gibʹe·ah toward the rising of the sun.

[[v7-20-44]]

^<<v7-20-44,44>>^ Finally there fell eighteen thousand men of Benjamin, all of these being valiant men.

[[v7-20-45]]

^<<v7-20-45,45>>^ Thus they turned and went fleeing to the wilderness to the crag of Rimʹmon. And they made a gleaning of five thousand men of them on the highways, and they kept following closely after them as far as Giʹdom and so struck down two thousand more men of them.

[[v7-20-46]]

^<<v7-20-46,46>>^ And all those of Benjamin that fell on that day amounted at last to twenty-five thousand men drawing sword, all these being valiant men.

[[v7-20-47]]

^<<v7-20-47,47>>^ But six hundred men turned and went fleeing to the wilderness to the crag of Rimʹmon, and they continued to dwell on the crag of Rimʹmon four months.

[[v7-20-48]]

^<<v7-20-48,48>>^ And the men of Israel came back against the sons of Benjamin and went striking with the edge of the sword those of the city, &#91;from&#93; men to domestic animal up to all that were found. Also, all the cities that were found they consigned to the fire.

'''

xref:007-judges/007-judges-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-judges/007-judges-021.adoc#v7-21-0[Próximo Capítulo &#62;]