include::./index.adoc[]

[[v7-13-0]]
=== Judges, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-13-1]]

^<<v7-13-1,1>>^ And the sons of Israel engaged again in doing what was bad in Jehovah’s eyes, so that Jehovah gave them into the hand of the Phi·lisʹtines for forty years.

[[v7-13-2]]

^<<v7-13-2,2>>^ Meanwhile there happened to be a certain man of Zoʹrah of the family of the Danʹites, and his name was Ma·noʹah. And his wife was barren and had borne no child.

[[v7-13-3]]

^<<v7-13-3,3>>^ In time Jehovah’s angel appeared to the woman and said to her: “Look, now, you are barren and have borne no child. And you will certainly become pregnant and give birth to a son.

[[v7-13-4]]

^<<v7-13-4,4>>^ And now watch yourself, please, and do not drink wine or intoxicating liquor, and do not eat anything unclean.

[[v7-13-5]]

^<<v7-13-5,5>>^ For, look! you will be pregnant,^&#42;1^ and you will certainly give birth to a son, and no razor should come upon his head, because a Nazʹi·rite of God is what the child^&#42;2^ will become on leaving the belly; and he it is who will take the lead in saving Israel out of the hand of the Phi·lisʹtines.”

[NOTE]
====
. Or, “you are pregnant,” MLXX; Vg, “you will conceive.”
. Or, “the male child; the boy.” Heb., han·naʹʽar.
====

[[v7-13-6]]

^<<v7-13-6,6>>^ Then the woman went and said to her husband: “There was a man of the &#91;true&#93; God that came to me, and his appearance was like the appearance of the angel of the &#91;true&#93; God, very fear-inspiring. And I did not ask him from just where he was, neither did he tell me his name.

[[v7-13-7]]

^<<v7-13-7,7>>^ But he said to me, ‘Look! You will be pregnant, and you will certainly give birth to a son. And now do not drink wine or intoxicating liquor, and do not eat any unclean thing, because a Nazʹi·rite of God is what the child^&#42;1^ will become on leaving the belly until the day of his death.’”

[NOTE]
====
. See vs 5 ftn, “Child.”
====

[[v7-13-8]]

^<<v7-13-8,8>>^ And Ma·noʹah began to entreat Jehovah and say: “Excuse me, Jehovah.^&#42;1^ The man of the &#91;true&#93; God that you just sent, let him, please, come again to us and instruct us as to what we ought to do to the child^&#42;2^ that will be born.”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. See vs 5 ftn, “Child.”
====

[[v7-13-9]]

^<<v7-13-9,9>>^ Accordingly the &#91;true&#93; God listened to the voice of Ma·noʹah, and the angel of the &#91;true&#93; God came again to the woman while she was sitting in the field, and Ma·noʹah her husband was not with her.

[[v7-13-10]]

^<<v7-13-10,10>>^ Immediately the woman hurried and ran and told her husband and said to him: “Look! The man that came the other day to me has appeared to me.”

[[v7-13-11]]

^<<v7-13-11,11>>^ At that Ma·noʹah got up and accompanied^&#42;1^ his wife and came to the man and said to him: “Are you the man that spoke to the woman?” to which he said: “I am.”

[NOTE]
====
. Or, “and went after.” Heb., wai·yeʹlekh ... ʼa·charehʹ. The latter Heb. word is a preposition. See Ge 16:13 ftn, “Him”; Ge 24:5, 8, 39; Ex 15:20, where forms of ʼa·charʹ appear.
====

[[v7-13-12]]

^<<v7-13-12,12>>^ Then Ma·noʹah said: “Now let your words come true. What will become the child’s^&#42;1^ mode of life and his work?”

[NOTE]
====
. See vs 5 ftn, “Child.”
====

[[v7-13-13]]

^<<v7-13-13,13>>^ So Jehovah’s angel said to Ma·noʹah: “From everything that I mentioned to the woman she should keep herself.

[[v7-13-14]]

^<<v7-13-14,14>>^ Nothing at all that comes forth from the wine vine should she eat, and no wine or intoxicating liquor let her drink, and no unclean thing of any sort let her eat. Everything that I have commanded her let her keep.”

[[v7-13-15]]

^<<v7-13-15,15>>^ Ma·noʹah now said to Jehovah’s angel: “Let us, please, detain you and fix up a kid of the goats before you.”

[[v7-13-16]]

^<<v7-13-16,16>>^ But Jehovah’s angel said to Ma·noʹah: “If you detain me, I shall not feed myself on your bread; but if you will render up a burnt offering to Jehovah, you may offer it up.” For Ma·noʹah did not know that he was Jehovah’s angel.

[[v7-13-17]]

^<<v7-13-17,17>>^ Then Ma·noʹah said to Jehovah’s angel: “What is your name, that when your word comes true we shall certainly do you honor?”

[[v7-13-18]]

^<<v7-13-18,18>>^ However, Jehovah’s angel said to him: “Just why should you ask about my name, when it is a wonderful one?”

[[v7-13-19]]

^<<v7-13-19,19>>^ And Ma·noʹah proceeded to take the kid of the goats and the grain offering and to offer it upon the rock to Jehovah. And He was doing something in a wonderful way while Ma·noʹah and his wife were looking on.

[[v7-13-20]]

^<<v7-13-20,20>>^ So it came about that, as the flame ascended from off the altar heavenward, then Jehovah’s angel ascended in the flame of the altar while Ma·noʹah and his wife were looking on. At once they fell upon their faces to the earth.

[[v7-13-21]]

^<<v7-13-21,21>>^ And Jehovah’s angel did not repeat appearing to Ma·noʹah and his wife anymore. Then it was that Ma·noʹah knew that he had been Jehovah’s angel.

[[v7-13-22]]

^<<v7-13-22,22>>^ Consequently Ma·noʹah said to his wife: “We shall positively die, because it is God that we have seen.”

[[v7-13-23]]

^<<v7-13-23,23>>^ But his wife said to him: “If Jehovah had been delighted only to put us to death, he would not have accepted a burnt offering and grain offering from our hand, and he would not have shown us all these things, and he would not as now have let us hear anything like this.”

[[v7-13-24]]

^<<v7-13-24,24>>^ Later the woman gave birth to a son and called his name Samson; and the boy kept getting bigger, and Jehovah continued to bless him.

[[v7-13-25]]

^<<v7-13-25,25>>^ In time Jehovah’s spirit started to impel him in Maʹha·neh-dan^&#42;1^ between Zoʹrah and Eshʹta·ol.

[NOTE]
====
. Meaning “Camp of Dan.”
====

'''

xref:007-judges/007-judges-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-judges/007-judges-014.adoc#v7-14-0[Próximo Capítulo &#62;]