include::./index.adoc[]

[[v7-21-0]]
=== Judges, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-21-1]]

^<<v7-21-1,1>>^ Now the men of Israel had sworn in Mizʹpah, saying: “Not a man of us will give his daughter to Benjamin as a wife.”

[[v7-21-2]]

^<<v7-21-2,2>>^ Consequently the people came to Bethʹel and kept sitting there before the &#91;true&#93; God until the evening and continued to raise their voice and indulge in a great deal of weeping.

[[v7-21-3]]

^<<v7-21-3,3>>^ And they would say: “Why, O Jehovah the God of Israel, has this occurred in Israel, for one tribe to be missing today from Israel?”

[[v7-21-4]]

^<<v7-21-4,4>>^ And it came about the next day that the people proceeded to get up early and to build an altar there and to offer up burnt offerings and communion offerings.

[[v7-21-5]]

^<<v7-21-5,5>>^ Then the sons of Israel said: “Who is there out of all the tribes of Israel that has not come up in the congregation^&#42;1^ to Jehovah, for there is a great oath that has taken place respecting the one that has not come up to Jehovah at Mizʹpah, saying, ‘Let him be put to death without fail.’”

[NOTE]
====
. “Congregation.” Gr., ek·kle·siʹai.
====

[[v7-21-6]]

^<<v7-21-6,6>>^ And the sons of Israel began to feel regret over Benjamin their brother. So they said: “Today one tribe has been chopped off from Israel.

[[v7-21-7]]

^<<v7-21-7,7>>^ What shall we do to those who are left over as to wives, now that we ourselves have sworn by Jehovah not to give them any of our daughters as wives?”

[[v7-21-8]]

^<<v7-21-8,8>>^ And they went on to say: “Which one out of the tribes of Israel is it that has not come up to Jehovah at Mizʹpah?” And, look! no one had come into the camp from Jaʹbesh-gilʹe·ad to the congregation.

[[v7-21-9]]

^<<v7-21-9,9>>^ When the people were counted, well, look! there was not a man there from the inhabitants of Jaʹbesh-gilʹe·ad.

[[v7-21-10]]

^<<v7-21-10,10>>^ Hence the assembly proceeded to send twelve thousand of the most valiant men^&#42;1^ there and to command them, saying: “Go, and YOU must strike the inhabitants of Jaʹbesh-gilʹe·ad with the edge of the sword, even the women^&#42;2^ and the little ones.

[NOTE]
====
. Lit., “twelve thousand men out of the sons of valor.”
. Or, “wives.”
====

[[v7-21-11]]

^<<v7-21-11,11>>^ And this is the thing that YOU should do: Every male and every woman that has experienced lying with a male YOU should devote to destruction.”

[[v7-21-12]]

^<<v7-21-12,12>>^ However, they found out of the inhabitants of Jaʹbesh-gilʹe·ad four hundred girls, virgins, that had not had intercourse with a man by lying with a male. So they brought them to the camp at Shiʹloh, which is in the land of Caʹnaan.

[[v7-21-13]]

^<<v7-21-13,13>>^ And all the assembly now sent and spoke to the sons of Benjamin that were on the crag of Rimʹmon and offered them peace.

[[v7-21-14]]

^<<v7-21-14,14>>^ Accordingly Benjamin came back at that time. Then they gave them the women that they had preserved alive from the women of Jaʹbesh-gilʹe·ad; but they did not find enough for them.

[[v7-21-15]]

^<<v7-21-15,15>>^ And the people felt regret over Benjamin because Jehovah had made a rupture between the tribes of Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Consequently the older men of the assembly said: “What shall we do to the men that are left over as to wives, for womankind has been annihilated out of Benjamin?”

[[v7-21-17]]

^<<v7-21-17,17>>^ Then they said: “There should be a possession for those who have escaped of Benjamin, that a tribe might not be wiped out of Israel.

[[v7-21-18]]

^<<v7-21-18,18>>^ As for us, we are not allowed to give them wives from our daughters, because the sons of Israel have sworn, saying, ‘Cursed is the one that gives a wife to Benjamin.’”

[[v7-21-19]]

^<<v7-21-19,19>>^ Finally they said: “Look! There is a festival of Jehovah from year to year in Shiʹloh, which is to the north of Bethʹel, toward the east of the highway that goes up from Bethʹel to Sheʹchem and toward the south of Le·boʹnah.”

[[v7-21-20]]

^<<v7-21-20,20>>^ So they commanded the sons of Benjamin, saying: “Go, and YOU must lie in wait in the vineyards.

[[v7-21-21]]

^<<v7-21-21,21>>^ And YOU must look, and, there now, when the daughters of Shiʹloh come on out to dance in circle dances, YOU must also come out from the vineyards and carry off for yourselves by force each one his wife from the daughters of Shiʹloh, and YOU must go to the land of Benjamin.

[[v7-21-22]]

^<<v7-21-22,22>>^ And it must occur that should their fathers or their brothers come to conduct a legal case against us,^&#42;1^ we^&#42;2^ also shall certainly say to them, ‘Do us a favor for their sakes, because we have not taken for each one his wife by war, for it was not YOU that did the giving to them at a time when YOU^&#42;3^ would become guilty.’”

[NOTE]
====
. “Us,” MSy; LXXVg, “you.”
. “We,” MLXXSyVg. Possibly, “you.”
. Possibly, “did the giving to them, because you yourselves,” by a slight correction of M. Compare 13:23, where the Heb. expression, “at a time when,” is rendered “as now.”
====

[[v7-21-23]]

^<<v7-21-23,23>>^ Accordingly the sons of Benjamin did just that way, and they proceeded to carry off wives for their number from the women dancing around, whom they snatched away; after which they went off and returned to their inheritance and built the cities and took up dwelling in them.

[[v7-21-24]]

^<<v7-21-24,24>>^ And the sons of Israel began to disperse from there at that time, each one to his own tribe and his own family; and they went their way out from there, each one to his own inheritance.

[[v7-21-25]]

^<<v7-21-25,25>>^ In those days there was no king in Israel. What was right in his own eyes was what each one was accustomed to do.

'''

xref:007-judges/007-judges-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-ruth/008-ruth-001.adoc#v8-1-0[Próximo Capítulo &#62;]