include::./index.adoc[]

[[v7-8-0]]
=== Judges, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v7-8-1]]

^<<v7-8-1,1>>^ Then the men of Eʹphra·im said to him: “What sort of thing is this that you have done to us in not calling us when you went to fight against Midʹi·an?” And they vehemently tried to pick a quarrel with him.

[[v7-8-2]]

^<<v7-8-2,2>>^ Finally he said to them: “What now have I done in comparison with YOU? Are not the gleanings of Eʹphra·im better than the grape gathering of Abi-eʹzer?

[[v7-8-3]]

^<<v7-8-3,3>>^ It was into YOUR hand that God^&#42;1^ gave Midʹi·an’s princes Oʹreb and Zeʹeb, and what have I been able to do in comparison with YOU?” It was then that their spirit calmed down toward him when he spoke this word.

[NOTE]
====
. “God,” MSy; TLXXVg, “Jehovah.”
====

[[v7-8-4]]

^<<v7-8-4,4>>^ Eventually Gidʹe·on came to the Jordan, crossing it, he and the three hundred men that were with him, tired but keeping up the pursuit.

[[v7-8-5]]

^<<v7-8-5,5>>^ Later he said to the men of Sucʹcoth: “Please give round loaves of bread to the people that are following my steps, for they are tired and I am chasing after Zeʹbah and Zal·munʹna, the kings of Midʹi·an.”

[[v7-8-6]]

^<<v7-8-6,6>>^ But the princes of Sucʹcoth said: “Are the palms of Zeʹbah and of Zal·munʹna already in your hand so that bread has to be given to your army?”

[[v7-8-7]]

^<<v7-8-7,7>>^ At this Gidʹe·on said: “That is why when Jehovah gives Zeʹbah and Zal·munʹna into my hand, I shall certainly give YOUR flesh a threshing with the thorns of the wilderness and the briers.”^&#42;1^

[NOTE]
====
. That is, something prodding; possibly, threshing sledges.
====

[[v7-8-8]]

^<<v7-8-8,8>>^ And he continued on his way up from there to Pe·nuʹel and went speaking to them in this same manner, but the men of Pe·nuʹel answered him just as the men of Sucʹcoth had answered.

[[v7-8-9]]

^<<v7-8-9,9>>^ Hence he said also to the men of Pe·nuʹel: “When I return in peace, I shall pull down this tower.”

[[v7-8-10]]

^<<v7-8-10,10>>^ Now Zeʹbah and Zal·munʹna were in Karʹkor, and their camps with them, about fifteen thousand being all who were left over out of the entire camp of the Easterners; and those already fallen were a hundred and twenty thousand men who used to draw the sword.

[[v7-8-11]]

^<<v7-8-11,11>>^ And Gidʹe·on continued on up by the way of those residing in tents to the east of Noʹbah and Jogʹbe·hah and began to strike the camp while the camp happened to be off guard.

[[v7-8-12]]

^<<v7-8-12,12>>^ When Zeʹbah and Zal·munʹna took to flight, he at once went in pursuit of them and got to capture Midʹi·an’s two kings, Zeʹbah and Zal·munʹna; and he drove all the camp into trembling.

[[v7-8-13]]

^<<v7-8-13,13>>^ And Gidʹe·on the son of Joʹash began his return from the war by the pass that goes up to Heʹres.^&#42;1^

[NOTE]
====
. Or, “by the ascent of Heres.”
====

[[v7-8-14]]

^<<v7-8-14,14>>^ En route he captured a young man of the men of Sucʹcoth and made inquiries of him. So he wrote out for him the names of the princes of Sucʹcoth and its older men, seventy-seven men.

[[v7-8-15]]

^<<v7-8-15,15>>^ With that he went to the men of Sucʹcoth and said: “Here are Zeʹbah and Zal·munʹna respecting whom YOU taunted me, saying, ‘Are the palms of Zeʹbah and of Zal·munʹna already in your hand so that bread has to be given to your tired-out men?’”

[[v7-8-16]]

^<<v7-8-16,16>>^ Then he took the older men of the city and thorns of the wilderness and briers, and with them he put the men of Sucʹcoth through an experience.

[[v7-8-17]]

^<<v7-8-17,17>>^ And the tower of Pe·nuʹel he pulled down, and he proceeded to kill the men of the city.

[[v7-8-18]]

^<<v7-8-18,18>>^ He now said to Zeʹbah and Zal·munʹna: “What sort of men were they whom YOU killed in Taʹbor?” To this they said: “As you are, so were they, each one, like the sons of a king in form.”

[[v7-8-19]]

^<<v7-8-19,19>>^ At that he said: “They were my brothers, the sons of my mother. As Jehovah lives, if YOU had preserved them alive, I would not have to kill YOU.”

[[v7-8-20]]

^<<v7-8-20,20>>^ Then he said to Jeʹther his firstborn: “Get up, kill them.” And the young man did not draw his sword, because he was afraid, for he was yet a young man.

[[v7-8-21]]

^<<v7-8-21,21>>^ So Zeʹbah and Zal·munʹna said: “Get up yourself and assault us, for as a man is, so is his mightiness.” Accordingly Gidʹe·on got up and killed Zeʹbah and Zal·munʹna and took the moon-shaped ornaments that were on the necks of their camels.

[[v7-8-22]]

^<<v7-8-22,22>>^ Later the men of Israel said to Gidʹe·on: “Rule over us, you and your son and your grandson as well, for you have saved us out of the hand of Midʹi·an.”

[[v7-8-23]]

^<<v7-8-23,23>>^ But Gidʹe·on said to them: “I myself shall not rule over YOU, nor will my son rule over YOU. Jehovah is the one who will rule over YOU.”

[[v7-8-24]]

^<<v7-8-24,24>>^ And Gidʹe·on went on to say to them: “Let me make a request of YOU: Give me, each one of YOU, the nose ring of his booty.” (For they had nose rings of gold, because they were Ishʹma·el·ites.)

[[v7-8-25]]

^<<v7-8-25,25>>^ Then they said: “We shall surely give them.” With that they spread out a mantle and went throwing each one the nose ring of his booty into it.

[[v7-8-26]]

^<<v7-8-26,26>>^ And the weight of the nose rings of gold that he had requested amounted to one thousand seven hundred gold shekels,^&#42;1^ besides the moon-shaped ornaments and the eardrops and the garments of wool dyed reddish purple that were upon the kings of Midʹi·an and besides the necklaces that were on the necks of the camels.

[NOTE]
====
. “Shekels,” LXXAVg; MLXXBSy omit. See App 8A.
====

[[v7-8-27]]

^<<v7-8-27,27>>^ And Gidʹe·on proceeded to make it into an ephʹod and to exhibit it in his city Ophʹrah; and all Israel began to have immoral intercourse with it^&#42;1^ there, so that it served as a snare to Gidʹe·on and to his household.

[NOTE]
====
. Or, “began to commit fornication (immorality) with it.”
====

[[v7-8-28]]

^<<v7-8-28,28>>^ Thus Midʹi·an was subdued before the sons of Israel, and they did not lift up their head anymore; and the land had no further disturbance for forty years in the days of Gidʹe·on.

[[v7-8-29]]

^<<v7-8-29,29>>^ And Jer·ub·baʹal the son of Joʹash went his way and continued to dwell in his house.

[[v7-8-30]]

^<<v7-8-30,30>>^ And Gidʹe·on came to have seventy sons that issued out of his upper thigh, for he came to have many wives.

[[v7-8-31]]

^<<v7-8-31,31>>^ As for the concubine of his that was in Sheʹchem, she too bore him a son. So he named him A·bimʹe·lech.

[[v7-8-32]]

^<<v7-8-32,32>>^ Eventually Gidʹe·on the son of Joʹash died at a good old age and was buried in the burial place of Joʹash his father in Ophʹrah of the Abi-ezʹrites.

[[v7-8-33]]

^<<v7-8-33,33>>^ And it came about that as soon as Gidʹe·on had died the sons of Israel again took up having^&#42;1^ immoral intercourse with the Baʹals, so that they appointed Baʹal-beʹrith as their god.^&#42;2^

[NOTE]
====
. Lit., “the sons of Israel proceeded to turn back and have.”
. “As ... god.” Heb., leʼ·lo·himʹ; Gr., the·onʹ; Lat., deʹum; LXXVg understood ʼelo·himʹ to be pl. to denote excellence and therefore rendered it in the sing.
====

[[v7-8-34]]

^<<v7-8-34,34>>^ And the sons of Israel did not remember Jehovah their God, who had delivered them out of the hand of all their enemies round about;

[[v7-8-35]]

^<<v7-8-35,35>>^ and they did not exercise loving-kindness^&#42;1^ toward the household of Jer·ub·baʹal, Gidʹe·on, in return for all the goodness that he had exercised toward Israel.

[NOTE]
====
. Or, “loyal love.”
====

'''

xref:007-judges/007-judges-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-judges/007-judges-009.adoc#v7-9-0[Próximo Capítulo &#62;]