include::./index.adoc[]

[[v40-22-0]]
=== According to Matthew, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-22-1]]

^<<v40-22-1,1>>^ In further reply Jesus again spoke to them with illustrations, saying:

[[v40-22-2]]

^<<v40-22-2,2>>^ “The kingdom of the heavens has become like a man, a king, that made a marriage feast for his son.

[[v40-22-3]]

^<<v40-22-3,3>>^ And he sent forth his slaves to call those invited to the marriage feast, but they were unwilling to come.

[[v40-22-4]]

^<<v40-22-4,4>>^ Again he sent forth other slaves, saying, ‘Tell those invited: “Look! I have prepared my dinner, my bulls and fattened animals are slaughtered, and all things are ready. Come to the marriage feast.”’

[[v40-22-5]]

^<<v40-22-5,5>>^ But unconcerned they went off, one to his own field, another to his commercial business;

[[v40-22-6]]

^<<v40-22-6,6>>^ but the rest, laying hold of his slaves, treated them insolently and killed them.

[[v40-22-7]]

^<<v40-22-7,7>>^ “But the king grew wrathful, and sent his armies and destroyed those murderers and burned their city.

[[v40-22-8]]

^<<v40-22-8,8>>^ Then he said to his slaves, ‘The marriage feast indeed is ready, but those invited were not worthy.

[[v40-22-9]]

^<<v40-22-9,9>>^ Therefore go to the roads leading out of the city, and anyone^&#42;1^ YOU find invite to the marriage feast.’

[NOTE]
====
. Or, “as many as.”
====

[[v40-22-10]]

^<<v40-22-10,10>>^ Accordingly those slaves went out to the roads and gathered together all they found, both wicked and good; and the room for the wedding ceremonies was filled with those reclining at the table.

[[v40-22-11]]

^<<v40-22-11,11>>^ “When the king came in to inspect the guests he caught sight there of a man not clothed with a marriage garment.

[[v40-22-12]]

^<<v40-22-12,12>>^ So he said to him, ‘Fellow, how did you get in here not having on a marriage garment?’ He was rendered speechless.

[[v40-22-13]]

^<<v40-22-13,13>>^ Then the king said to his servants,^&#42;1^ ‘Bind him hand and foot and throw him out into the darkness outside. There is where &#91;his&#93; weeping and the gnashing^&#42;2^ of &#91;his&#93; teeth will be.’

[NOTE]
====
. Or, “to his ministers (attendants).” Gr., tois di·a·koʹnois; Lat., mi·niʹstris; J22(Heb.), lam·sha·rethimʹ.
. Or, “grinding; clenching.”
====

[[v40-22-14]]

^<<v40-22-14,14>>^ “For there are many invited, but few chosen.”

[[v40-22-15]]

^<<v40-22-15,15>>^ Then the Pharisees went their way and took counsel together in order to trap him in his speech.

[[v40-22-16]]

^<<v40-22-16,16>>^ So they dispatched to him their disciples, together with party followers of Herod,^&#42;1^ saying: “Teacher, we know you are truthful and teach the way of God in truth, and you do not care for anybody, for you do not look upon men’s outward appearance.

[NOTE]
====
. Or, “with the Herodians.”
====

[[v40-22-17]]

^<<v40-22-17,17>>^ Tell us, therefore, What do you think? Is it lawful to pay head tax to Caesar^&#42;1^ or not?”

[NOTE]
====
. Or, “to the Emperor.” Gr., Kaiʹsa·ri; Lat., Caeʹsa·ri; J22(Heb.), laq·Qeh·sarʹ.
====

[[v40-22-18]]

^<<v40-22-18,18>>^ But Jesus, knowing their wickedness, said: “Why do YOU put me to the test, hypocrites?

[[v40-22-19]]

^<<v40-22-19,19>>^ Show me the head tax coin.” They brought him a de·narʹi·us.^&#42;1^

[NOTE]
====
. See 20:2 ftn.
====

[[v40-22-20]]

^<<v40-22-20,20>>^ And he said to them: “Whose image^&#42;1^ and inscription is this?”

[NOTE]
====
. “Image.” Gr., ei·konʹ; Lat., i·maʹgo; J22(Heb.), had·demuthʹ, “the image.”
====

[[v40-22-21]]

^<<v40-22-21,21>>^ They said: “Caesar’s.” Then he said to them: “Pay back,^&#42;1^ therefore, Caesar’s things to Caesar, but God’s things to God.”

[NOTE]
====
. Lit., “Give you back.” Gr., A·poʹdo·te; Lat., redʹdi·te; J17,​22(Heb.), tenuʹ.
====

[[v40-22-22]]

^<<v40-22-22,22>>^ Well, when they heard &#91;that&#93;, they marveled, and leaving him they went off.

[[v40-22-23]]

^<<v40-22-23,23>>^ On that day Sadducees, who say there is no resurrection,^&#42;1^ came up to him and asked him:

[NOTE]
====
. “Resurrection.” Gr., a·naʹsta·sin, “raising up; standing up” (from a·naʹ, “up,” and staʹsis, “standing”); Lat., re·sur·rec·ti·oʹnem; J17(Heb.), techi·yathʹ ham·me·thimʹ, “revival of the dead.”
====

[[v40-22-24]]

^<<v40-22-24,24>>^ “Teacher, Moses said, ‘If any man dies without having children, his brother must take his wife in marriage and raise up offspring for his brother.’

[[v40-22-25]]

^<<v40-22-25,25>>^ Now there were seven brothers with us; and the first married and deceased, and, not having offspring, he left his wife for his brother.

[[v40-22-26]]

^<<v40-22-26,26>>^ It went the same way also with the second and the third, until through all seven.

[[v40-22-27]]

^<<v40-22-27,27>>^ Last of all the woman died.

[[v40-22-28]]

^<<v40-22-28,28>>^ Consequently, in the resurrection, to which of the seven will she be wife? For they all got her.”

[[v40-22-29]]

^<<v40-22-29,29>>^ In reply Jesus said to them: “YOU are mistaken, because YOU know neither the Scriptures nor the power of God;

[[v40-22-30]]

^<<v40-22-30,30>>^ for in the resurrection neither do men marry nor are women given in marriage, but are as angels in heaven.

[[v40-22-31]]

^<<v40-22-31,31>>^ As regards the resurrection of the dead, did YOU not read what was spoken to YOU by God, saying,

[[v40-22-32]]

^<<v40-22-32,32>>^ ‘I am the God of Abraham and the God of Isaac and the God of Jacob’? He is the God,^&#42;1^ not of the dead, but of the living.”

[NOTE]
====
. “He is the God,” B; J18, “Jehovah is God.”
====

[[v40-22-33]]

^<<v40-22-33,33>>^ On hearing &#91;that&#93;, the crowds were astounded at his teaching.

[[v40-22-34]]

^<<v40-22-34,34>>^ After the Pharisees heard that he had put the Sadducees to silence, they came together in one group.

[[v40-22-35]]

^<<v40-22-35,35>>^ And one of them, versed in the Law, asked, testing him:

[[v40-22-36]]

^<<v40-22-36,36>>^ “Teacher, which is the greatest commandment in the Law?”

[[v40-22-37]]

^<<v40-22-37,37>>^ He said to him: “‘You must love Jehovah^&#42;1^ your God with your whole heart and with your whole soul and with your whole mind.’

[NOTE]
====
. See App 1D.
====

[[v40-22-38]]

^<<v40-22-38,38>>^ This is the greatest and first commandment.

[[v40-22-39]]

^<<v40-22-39,39>>^ The second, like it, is this, ‘You must love your neighbor as yourself.’

[[v40-22-40]]

^<<v40-22-40,40>>^ On these two commandments the whole Law hangs, and the Prophets.”

[[v40-22-41]]

^<<v40-22-41,41>>^ Now while the Pharisees were gathered together Jesus asked them:

[[v40-22-42]]

^<<v40-22-42,42>>^ “What do YOU think about the Christ? Whose son is he?” They said to him: “David’s.”

[[v40-22-43]]

^<<v40-22-43,43>>^ He said to them: “How, then, is it that David by inspiration^&#42;1^ calls him ‘Lord,’ saying,

[NOTE]
====
. Lit., “in spirit.” Gr., en pneuʹma·ti; Lat., in spiʹri·tu; J17,​18(Heb.), ba·ruʹach.
====

[[v40-22-44]]

^<<v40-22-44,44>>^ ‘Jehovah^&#42;1^ said to my Lord: “Sit at my right hand until I put your enemies beneath your feet”’?

[NOTE]
====
. See App 1D.
====

[[v40-22-45]]

^<<v40-22-45,45>>^ If, therefore, David calls him ‘Lord,’ how is he his son?”

[[v40-22-46]]

^<<v40-22-46,46>>^ And nobody was able to say a word in reply to him, nor did anyone dare from that day on to question him any further.

'''

xref:040-matthew/040-matthew-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-matthew/040-matthew-023.adoc#v40-23-0[Próximo Capítulo &#62;]