include::./index.adoc[]

[[v40-14-0]]
=== According to Matthew, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-14-1]]

^<<v40-14-1,1>>^ At that particular time Herod, the district ruler,^&#42;1^ heard the report about Jesus

[NOTE]
====
. Lit., “the tetrarch,” the territorial prince for the emperor.
====

[[v40-14-2]]

^<<v40-14-2,2>>^ and said to his servants: “This is John the Baptist. He was raised up from the dead, and this is why the powerful works^&#42;1^ are operating in him.”

[NOTE]
====
. Or, “the miracles.”
====

[[v40-14-3]]

^<<v40-14-3,3>>^ For Herod had arrested John and bound him and put him away in prison on account of He·roʹdi·as the wife of Philip his brother.

[[v40-14-4]]

^<<v40-14-4,4>>^ For John had been saying to him: “It is not lawful for you to be having her.”

[[v40-14-5]]

^<<v40-14-5,5>>^ However, although he wanted to kill him, he feared the crowd, because they took him for a prophet.

[[v40-14-6]]

^<<v40-14-6,6>>^ But when Herod’s birthday was being celebrated the daughter of He·roʹdi·as danced at it and pleased Herod so much

[[v40-14-7]]

^<<v40-14-7,7>>^ that he promised with an oath to give her whatever she asked.

[[v40-14-8]]

^<<v40-14-8,8>>^ Then she, under her mother’s coaching, said: “Give me here upon a platter the head of John the Baptist.”

[[v40-14-9]]

^<<v40-14-9,9>>^ Grieved though he was, the king out of regard for his oaths and for those reclining with him commanded it to be given;

[[v40-14-10]]

^<<v40-14-10,10>>^ and he sent and had John beheaded in the prison.

[[v40-14-11]]

^<<v40-14-11,11>>^ And his head was brought on a platter and given to the maiden, and she brought it to her mother.

[[v40-14-12]]

^<<v40-14-12,12>>^ Finally his disciples came up and removed the corpse and buried him and came and reported to Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ At hearing this Jesus withdrew from there by boat into a lonely place for isolation; but the crowds, getting to hear of it, followed him on foot from the cities.

[[v40-14-14]]

^<<v40-14-14,14>>^ Now when he came forth he saw a great crowd; and he felt pity for them, and he cured their sick ones.

[[v40-14-15]]

^<<v40-14-15,15>>^ But when evening fell his disciples came to him and said: “The place is lonely and the hour is already far advanced; send the crowds away, that they may go into the villages and buy themselves things to eat.”

[[v40-14-16]]

^<<v40-14-16,16>>^ However, Jesus said to them: “They do not have to leave: YOU give them something to eat.”

[[v40-14-17]]

^<<v40-14-17,17>>^ They said to him: “We have nothing here but five loaves and two fishes.”

[[v40-14-18]]

^<<v40-14-18,18>>^ He said: “BRING them here to me.”

[[v40-14-19]]

^<<v40-14-19,19>>^ Next he commanded the crowds to recline on the grass and took the five loaves and two fishes, and, looking up to heaven, he said a blessing and, after breaking the loaves, he distributed them to the disciples, the disciples in turn to the crowds.

[[v40-14-20]]

^<<v40-14-20,20>>^ So all ate and were satisfied, and they took up the surplus of fragments, twelve baskets full.

[[v40-14-21]]

^<<v40-14-21,21>>^ Yet those eating were about five thousand men, besides women and young children.

[[v40-14-22]]

^<<v40-14-22,22>>^ Then, without delay, he compelled his disciples to board the boat and go ahead of him to the other side, while he sent the crowds away.

[[v40-14-23]]

^<<v40-14-23,23>>^ Eventually, having sent the crowds away, he went up into the mountain by himself to pray. Though it became late, he was there alone.

[[v40-14-24]]

^<<v40-14-24,24>>^ By now the boat was many hundreds of yards^&#42;1^ away from land, being hard put to it by the waves, because the wind was against them.

[NOTE]
====
. Lit., “many stadia.” A stadium equaled one eighth of a Roman mile, 185 m (606.75 English ft).
====

[[v40-14-25]]

^<<v40-14-25,25>>^ But in the fourth watch period^&#42;1^ of the night he came to them, walking over the sea.

[NOTE]
====
. The last watch (from about 3 a.m. until sunrise) according to the Gr. and Roman division of the night. The Jews had three divisions, or watches, according to Ex 14:24 and Jg 7:19, but later they adopted the Roman system of four night watches. See Mr 13:35 ftns.
====

[[v40-14-26]]

^<<v40-14-26,26>>^ When they caught sight of him walking on the sea, the disciples were troubled, saying: “It is an apparition!” And they cried out in their fear.

[[v40-14-27]]

^<<v40-14-27,27>>^ But at once Jesus spoke to them with the words: “Take courage, it is I; have no fear.”

[[v40-14-28]]

^<<v40-14-28,28>>^ In reply Peter said to him: “Lord, if it is you, command me to come to you over the waters.”

[[v40-14-29]]

^<<v40-14-29,29>>^ He said: “Come!” Thereupon Peter, getting down off the boat, walked over the waters and went toward Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ But looking at the windstorm, he got afraid and, after starting to sink, he cried out: “Lord, save me!”

[[v40-14-31]]

^<<v40-14-31,31>>^ Immediately stretching out his hand Jesus caught hold of him and said to him: “You with little faith, why did you give way to doubt?”

[[v40-14-32]]

^<<v40-14-32,32>>^ And after they got up into the boat, the windstorm abated.

[[v40-14-33]]

^<<v40-14-33,33>>^ Then those in the boat did obeisance to him, saying: “You are really God’s Son.”

[[v40-14-34]]

^<<v40-14-34,34>>^ And they got across and came to land in Gen·nesʹa·ret.

[[v40-14-35]]

^<<v40-14-35,35>>^ Upon recognizing him the men of that place sent forth into all that surrounding country, and people brought him all those who were ill.

[[v40-14-36]]

^<<v40-14-36,36>>^ And they went entreating him that they might just touch the fringe of his outer garment; and all those who touched it were made completely well.

'''

xref:040-matthew/040-matthew-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-matthew/040-matthew-015.adoc#v40-15-0[Próximo Capítulo &#62;]