include::./index.adoc[]

[[v40-12-0]]
=== According to Matthew, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-12-1]]

^<<v40-12-1,1>>^ At that season Jesus went through the grainfields on the sabbath. His disciples got hungry and started to pluck heads of grain and to eat.

[[v40-12-2]]

^<<v40-12-2,2>>^ At seeing this the Pharisees said to him: “Look! Your disciples are doing what it is not lawful to do on the sabbath.”

[[v40-12-3]]

^<<v40-12-3,3>>^ He said to them: “Have YOU not read what David did when he and the men with him got hungry?

[[v40-12-4]]

^<<v40-12-4,4>>^ How he entered into the house of God and they ate the loaves of presentation,^&#42;1^ something that it was not lawful for him to eat, nor for those with him, but for the priests only?

[NOTE]
====
. Or, “showbread.” Lit., “loaves of the presentation.” Gr., arʹtous tes pro·theʹse·os; J22(Heb.), leʹchem hap·pa·nimʹ. See Ex 25:30 ftn.
====

[[v40-12-5]]

^<<v40-12-5,5>>^ Or, have YOU not read in the Law that on the sabbaths the priests in the temple treat the sabbath as not sacred and continue guiltless?

[[v40-12-6]]

^<<v40-12-6,6>>^ But I tell YOU that something greater than the temple is here.

[[v40-12-7]]

^<<v40-12-7,7>>^ However, if YOU had understood what this means,^&#42;1^ ‘I want mercy, and not sacrifice,’ YOU would not have condemned the guiltless ones.

[NOTE]
====
. Lit., “what is.” Gr., tiʹ e·stin. See 26:26 ftn.
====

[[v40-12-8]]

^<<v40-12-8,8>>^ For Lord of the sabbath is what the Son of man is.”

[[v40-12-9]]

^<<v40-12-9,9>>^ After departing from that place he went into their synagogue;

[[v40-12-10]]

^<<v40-12-10,10>>^ and, look! a man with a withered hand! So they asked him, “Is it lawful to cure on the sabbath?” that they might get an accusation against him.

[[v40-12-11]]

^<<v40-12-11,11>>^ He said to them: “Who will be the man among YOU that has one sheep and, if this falls into a pit on the sabbath, will not get hold of it and lift it out?

[[v40-12-12]]

^<<v40-12-12,12>>^ All considered, of how much more worth is a man than a sheep! So it is lawful to do a fine thing on the sabbath.”

[[v40-12-13]]

^<<v40-12-13,13>>^ Then he said to the man: “Stretch out your hand.” And he stretched it out, and it was restored sound like the other hand.

[[v40-12-14]]

^<<v40-12-14,14>>^ But the Pharisees went out and took counsel against him that they might destroy him.

[[v40-12-15]]

^<<v40-12-15,15>>^ Having come to know &#91;this&#93;, Jesus withdrew from there. Many also followed him, and he cured them all,

[[v40-12-16]]

^<<v40-12-16,16>>^ but he strictly charged them not to make him manifest;

[[v40-12-17]]

^<<v40-12-17,17>>^ that there might be fulfilled what was spoken through Isaiah the prophet, who said:

[[v40-12-18]]

^<<v40-12-18,18>>^ “Look! My servant whom I chose, my beloved, whom my soul approved! I will put my spirit upon him, and what justice is he will make clear to the nations.

[[v40-12-19]]

^<<v40-12-19,19>>^ He will not wrangle, nor cry aloud, nor will anyone hear his voice in the broad ways.

[[v40-12-20]]

^<<v40-12-20,20>>^ No bruised reed will he crush, and no smoldering flaxen wick will he extinguish, until he sends out justice with success.^&#42;1^

[NOTE]
====
. Or, “to victory.”
====

[[v40-12-21]]

^<<v40-12-21,21>>^ Indeed, in his name nations will hope.”

[[v40-12-22]]

^<<v40-12-22,22>>^ Then they brought him a demon-possessed man, blind and dumb; and he cured him, so that the dumb man spoke and saw.

[[v40-12-23]]

^<<v40-12-23,23>>^ Well, all the crowds were simply carried away and began to say: “May this not perhaps be the Son of David?”

[[v40-12-24]]

^<<v40-12-24,24>>^ At hearing this, the Pharisees said: “This fellow does not expel the demons except by means of Be·elʹze·bub,^&#42;1^ the ruler of the demons.”

[NOTE]
====
. “Beelzebub,” VgSyc,p,s; CDWSyhArm, “Beelzeboul”; אB, “Beezeboul”; possibly meaning “Lord of the Habitation,” or, if a play on the non-Biblical Heb. word zeʹvel (dung), “Lord of Dung.” Compare 2Ki 1:2 ftn, “Baal-zebub.”
====

[[v40-12-25]]

^<<v40-12-25,25>>^ Knowing their thoughts, he said to them: “Every kingdom divided against itself comes to desolation, and every city or house divided against itself will not stand.

[[v40-12-26]]

^<<v40-12-26,26>>^ In the same way, if Satan expels Satan, he has become divided against himself; how, then, will his kingdom stand?

[[v40-12-27]]

^<<v40-12-27,27>>^ Moreover, if I expel the demons by means of Be·elʹze·bub, by means of whom do YOUR sons expel them? This is why they will be judges of YOU.

[[v40-12-28]]

^<<v40-12-28,28>>^ But if it is by means of God’s spirit that I expel the demons, the kingdom of God has really overtaken YOU.

[[v40-12-29]]

^<<v40-12-29,29>>^ Or how can anyone invade the house of a strong man and seize his movable goods, unless first he binds the strong man? And then he will plunder his house.

[[v40-12-30]]

^<<v40-12-30,30>>^ He that is not on my side is against me, and he that does not gather with me scatters.

[[v40-12-31]]

^<<v40-12-31,31>>^ “On this account I say to YOU, Every sort of sin and blasphemy will be forgiven men, but the blasphemy against the spirit will not be forgiven.

[[v40-12-32]]

^<<v40-12-32,32>>^ For example, whoever speaks a word against the Son of man, it will be forgiven him; but whoever speaks against the holy spirit,^&#42;1^ it will not be forgiven him, no, not in this system of things^&#42;2^ nor in that to come.

[NOTE]
====
. Lit., “might speak down on the holy spirit.”
. Or, “order of things.” Gr., ai·oʹni; Lat., saeʹcu·lo; J1-14,​16-18(Heb.), va·ʽoh·lamʹ, “in the order of things.”
====

[[v40-12-33]]

^<<v40-12-33,33>>^ “Either YOU people make the tree fine and its fruit fine or make the tree rotten and its fruit rotten; for by its fruit the tree is known.

[[v40-12-34]]

^<<v40-12-34,34>>^ Offspring of vipers, how can YOU speak good things, when YOU are wicked? For out of the abundance of the heart the mouth speaks.

[[v40-12-35]]

^<<v40-12-35,35>>^ The good man out of his good treasure sends out good things, whereas the wicked man out of his wicked treasure sends out wicked things.

[[v40-12-36]]

^<<v40-12-36,36>>^ I tell YOU that every unprofitable saying that men speak, they will render an account concerning it on Judgment Day;

[[v40-12-37]]

^<<v40-12-37,37>>^ for by your words you will be declared righteous, and by your words you will be condemned.”

[[v40-12-38]]

^<<v40-12-38,38>>^ Then as an answer to him some of the scribes and Pharisees said: “Teacher, we want to see a sign from you.”

[[v40-12-39]]

^<<v40-12-39,39>>^ In reply he said to them: “A wicked and adulterous generation keeps on seeking for a sign, but no sign will be given it except the sign of Joʹnah the prophet.

[[v40-12-40]]

^<<v40-12-40,40>>^ For just as Joʹnah was in the belly of the huge fish three days and three nights, so the Son of man will be in the heart of the earth three days and three nights.

[[v40-12-41]]

^<<v40-12-41,41>>^ Men of Ninʹe·veh will rise up in the judgment with this generation and will condemn it; because they repented at what Joʹnah preached,^&#42;1^ but, look! something more than Joʹnah is here.

[NOTE]
====
. Lit., “the preaching of Jonah.” Gr., to keʹryg·ma I·o·naʹ; Lat., prae·di·ca·ti·oʹne Ioʹnae.
====

[[v40-12-42]]

^<<v40-12-42,42>>^ The queen of the south will be raised up in the judgment with this generation and will condemn it; because she came from the ends^&#42;1^ of the earth to hear the wisdom of Solʹo·mon, but, look! something more than Solʹo·mon is here.

[NOTE]
====
. Or, “terminations.” Gr., pe·raʹton. Compare Ac 1:8 ftn, “Part.”
====

[[v40-12-43]]

^<<v40-12-43,43>>^ “When an unclean spirit comes out of a man, it passes through parched places in search of a resting-place, and finds none.

[[v40-12-44]]

^<<v40-12-44,44>>^ Then it says, ‘I will go back to my house out of which I moved’; and on arriving it finds it unoccupied but swept clean and adorned.

[[v40-12-45]]

^<<v40-12-45,45>>^ Then it goes its way and takes along with it seven different spirits more wicked than itself, and, after getting inside, they dwell there; and the final circumstances of that man become worse than the first. That is how it will be also with this wicked generation.”

[[v40-12-46]]

^<<v40-12-46,46>>^ While he was yet speaking to the crowds, look! his mother and brothers took up a position outside seeking to speak to him.

[[v40-12-47]]

^<<v40-12-47,47>>^ So someone said to him: “Look! Your mother and your brothers are standing outside, seeking to speak to you.”^&#42;1^

[NOTE]
====
. א*BSyc,s omit vs 47.
====

[[v40-12-48]]

^<<v40-12-48,48>>^ As an answer he said to the one telling him: “Who is my mother, and who are my brothers?”

[[v40-12-49]]

^<<v40-12-49,49>>^ And extending his hand toward his disciples, he said: “Look! My mother and my brothers!

[[v40-12-50]]

^<<v40-12-50,50>>^ For whoever does the will of my Father who is in heaven, the same is my brother, and sister, and mother.”

'''

xref:040-matthew/040-matthew-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-matthew/040-matthew-013.adoc#v40-13-0[Próximo Capítulo &#62;]