include::./index.adoc[]

[[v40-13-0]]
=== According to Matthew, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-13-1]]

^<<v40-13-1,1>>^ On that day Jesus, having left the house, was sitting by the sea;

[[v40-13-2]]

^<<v40-13-2,2>>^ and great crowds gathered to him, so that he went aboard a boat and sat down, and all the crowd was standing on the beach.

[[v40-13-3]]

^<<v40-13-3,3>>^ Then he told them many things by illustrations,^&#42;1^ saying: “Look! A sower went out to sow;

[NOTE]
====
. Or, “in parables.” Gr., en pa·ra·bo·laisʹ; Lat., in pa·raʹbo·lis; J17,​18,​22(Heb.), bim·sha·limʹ.
====

[[v40-13-4]]

^<<v40-13-4,4>>^ and as he was sowing, some &#91;seeds&#93; fell alongside the road, and the birds came and ate them up.

[[v40-13-5]]

^<<v40-13-5,5>>^ Others fell upon the rocky places where they did not have much soil, and at once they sprang up because of not having depth of soil.

[[v40-13-6]]

^<<v40-13-6,6>>^ But when the sun rose they were scorched, and because of not having root they withered.

[[v40-13-7]]

^<<v40-13-7,7>>^ Others, too, fell among the thorns, and the thorns came up and choked them.

[[v40-13-8]]

^<<v40-13-8,8>>^ Still others fell upon the fine soil and they began to yield fruit, this one a hundredfold, that one sixty, the other thirty.

[[v40-13-9]]

^<<v40-13-9,9>>^ Let him that has ears listen.”

[[v40-13-10]]

^<<v40-13-10,10>>^ So the disciples came up and said to him: “Why is it you speak to them by the use of illustrations?”

[[v40-13-11]]

^<<v40-13-11,11>>^ In reply he said: “To YOU it is granted to understand the sacred secrets of the kingdom of the heavens, but to those people it is not granted.

[[v40-13-12]]

^<<v40-13-12,12>>^ For whoever has, more will be given him and he will be made to abound; but whoever does not have, even what he has will be taken from him.

[[v40-13-13]]

^<<v40-13-13,13>>^ This is why I speak to them by the use of illustrations, because, looking, they look in vain, and hearing, they hear in vain, neither do they get the sense of it;

[[v40-13-14]]

^<<v40-13-14,14>>^ and toward them the prophecy of Isaiah is having fulfillment, which says, ‘By hearing, YOU will hear but by no means get the sense of it; and, looking, YOU will look but by no means see.

[[v40-13-15]]

^<<v40-13-15,15>>^ For the heart of this people has grown unreceptive,^&#42;1^ and with their ears they have heard without response,^&#42;2^ and they have shut their eyes; that they might never see with their eyes and hear with their ears and get the sense of it with their hearts and turn back, and I heal them.’

[NOTE]
====
. Lit., “was made thick (fat).”
. Or, “heard unwillingly.”
====

[[v40-13-16]]

^<<v40-13-16,16>>^ “However, happy are YOUR eyes because they behold, and YOUR ears because they hear.

[[v40-13-17]]

^<<v40-13-17,17>>^ For I truly say to YOU, Many prophets and righteous men desired to see the things YOU are beholding and did not see them, and to hear the things YOU are hearing and did not hear them.

[[v40-13-18]]

^<<v40-13-18,18>>^ “YOU, then, listen to the illustration of the man that sowed.

[[v40-13-19]]

^<<v40-13-19,19>>^ Where anyone hears the word of the kingdom but does not get the sense of it, the wicked one comes and snatches away what has been sown in his heart; this is the one sown alongside the road.

[[v40-13-20]]

^<<v40-13-20,20>>^ As for the one sown upon the rocky places, this is the one hearing the word and at once accepting it with joy.

[[v40-13-21]]

^<<v40-13-21,21>>^ Yet he has no root in himself but continues for a time, and after tribulation or persecution has arisen on account of the word he is at once stumbled.

[[v40-13-22]]

^<<v40-13-22,22>>^ As for the one sown among the thorns, this is the one hearing the word, but the anxiety of this system of things^&#42;1^ and the deceptive power of riches^&#42;2^ choke the word, and he^&#42;3^ becomes unfruitful.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
. Or, “and the pleasure of being wealthy.”
. Or, “it,” that is, the “word.”
====

[[v40-13-23]]

^<<v40-13-23,23>>^ As for the one sown upon the fine soil, this is the one hearing the word and getting the sense of it, who really does bear fruit and produces, this one a hundredfold, that one sixty, the other thirty.”

[[v40-13-24]]

^<<v40-13-24,24>>^ Another illustration he set before them, saying: “The kingdom of the heavens has become like a man that sowed fine seed in his field.

[[v40-13-25]]

^<<v40-13-25,25>>^ While men were sleeping, his enemy came and oversowed weeds^&#42;1^ in among the wheat, and left.

[NOTE]
====
. Or, “bearded darnel.” See vs 36 ftn.
====

[[v40-13-26]]

^<<v40-13-26,26>>^ When the blade sprouted and produced fruit, then the weeds appeared also.

[[v40-13-27]]

^<<v40-13-27,27>>^ So the slaves of the householder came up and said to him, ‘Master, did you not sow fine seed in your field? How, then, does it come to have weeds?’

[[v40-13-28]]

^<<v40-13-28,28>>^ He said to them, ‘An enemy, a man, did this.’ They said to him, ‘Do you want us, then, to go out and collect them?’

[[v40-13-29]]

^<<v40-13-29,29>>^ He said, ‘No; that by no chance, while collecting the weeds, YOU uproot the wheat with them.

[[v40-13-30]]

^<<v40-13-30,30>>^ Let both grow together until the harvest; and in the harvest season I will tell the reapers, First collect the weeds and bind them in bundles to burn them up, then go to gathering the wheat into my storehouse.’”

[[v40-13-31]]

^<<v40-13-31,31>>^ Another illustration he set before them, saying: “The kingdom of the heavens is like a mustard grain, which a man took and planted in his field;

[[v40-13-32]]

^<<v40-13-32,32>>^ which is, in fact, the tiniest of all the seeds, but when it has grown it is the largest of the vegetables and becomes a tree, so that the birds of heaven come and find lodging among its branches.”

[[v40-13-33]]

^<<v40-13-33,33>>^ Another illustration he spoke to them: “The kingdom of the heavens is like leaven, which a woman took and hid in three large measures^&#42;1^ of flour, until the whole mass was fermented.”

[NOTE]
====
. “Large measures.” Or, “seah measures.” Gr., saʹta. A seah measure equaled 7.33 L (6.66 dry qt).
====

[[v40-13-34]]

^<<v40-13-34,34>>^ All these things Jesus spoke to the crowds by illustrations. Indeed, without an illustration he would not speak to them;

[[v40-13-35]]

^<<v40-13-35,35>>^ that there might be fulfilled what was spoken through the prophet who said: “I will open my mouth with illustrations, I will publish things hidden since the founding.”

[[v40-13-36]]

^<<v40-13-36,36>>^ Then after dismissing the crowds he went into the house. And his disciples came to him and said: “Explain to us the illustration of the weeds^&#42;1^ in the field.”

[NOTE]
====
. Or, “bearded darnel.” Gr., zi·za·niʹon; J17,​22(Heb.), zu·nehʹ. A species of the grass family whose seeds have poisonous properties believed to stem from a fungus growing within them.
====

[[v40-13-37]]

^<<v40-13-37,37>>^ In response he said: “The sower of the fine seed is the Son of man;

[[v40-13-38]]

^<<v40-13-38,38>>^ the field is the world; as for the fine seed, these are the sons of the kingdom; but the weeds are the sons of the wicked one,

[[v40-13-39]]

^<<v40-13-39,39>>^ and the enemy that sowed them is the Devil. The harvest is a conclusion^&#42;1^ of a system of things,^&#42;2^ and the reapers are angels.

[NOTE]
====
. Or, “joint end; combination end; ending together.” Gr., συντέλεια (syn·teʹlei·a); Lat., con·sum·maʹti·o. See Da 12:4 ftn, “End.”
. Or, “an order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J1-14,​16-18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v40-13-40]]

^<<v40-13-40,40>>^ Therefore, just as the weeds are collected and burned with fire, so it will be in the conclusion of the system of things.

[[v40-13-41]]

^<<v40-13-41,41>>^ The Son of man will send forth his angels, and they will collect out from his kingdom all things that cause stumbling and persons who are doing lawlessness,

[[v40-13-42]]

^<<v40-13-42,42>>^ and they will pitch them into the fiery furnace. There is where &#91;their&#93; weeping and the gnashing of &#91;their&#93; teeth will be.

[[v40-13-43]]

^<<v40-13-43,43>>^ At that time the righteous ones will shine as brightly as the sun in the kingdom of their Father. Let him that has ears listen.

[[v40-13-44]]

^<<v40-13-44,44>>^ “The kingdom of the heavens is like a treasure hidden in the field, which a man found and hid; and for the joy he has he goes and sells what things he has and buys that field.

[[v40-13-45]]

^<<v40-13-45,45>>^ “Again the kingdom of the heavens is like a traveling merchant seeking fine pearls.

[[v40-13-46]]

^<<v40-13-46,46>>^ Upon finding one pearl of high value, away he went and promptly sold all the things he had and bought it.

[[v40-13-47]]

^<<v40-13-47,47>>^ “Again the kingdom of the heavens is like a dragnet let down into the sea and gathering up &#91;fish&#93; of every kind.

[[v40-13-48]]

^<<v40-13-48,48>>^ When it got full they hauled it up onto the beach and, sitting down, they collected the fine ones into vessels, but the unsuitable they threw away.

[[v40-13-49]]

^<<v40-13-49,49>>^ That is how it will be in the conclusion of the system of things:^&#42;1^ the angels will go out and separate the wicked from among the righteous

[NOTE]
====
. See vs 39 ftns.
====

[[v40-13-50]]

^<<v40-13-50,50>>^ and will cast them into the fiery furnace. There is where &#91;their&#93; weeping and the gnashing of &#91;their&#93; teeth will be.

[[v40-13-51]]

^<<v40-13-51,51>>^ “Did YOU get the sense of all these things?” They said to him: “Yes.”

[[v40-13-52]]

^<<v40-13-52,52>>^ Then he said to them: “That being the case, every public instructor,^&#42;1^ when taught respecting the kingdom of the heavens, is like a man, a householder, who brings out of his treasure store things new and old.”

[NOTE]
====
. Or, “every learned person.”
====

[[v40-13-53]]

^<<v40-13-53,53>>^ Now when Jesus had finished these illustrations he went across country from there.

[[v40-13-54]]

^<<v40-13-54,54>>^ And after coming into his home territory^&#42;1^ he began to teach them in their synagogue, so that they were astounded and said: “Where did this man get this wisdom and these powerful works?

[NOTE]
====
. Or, “city.”
====

[[v40-13-55]]

^<<v40-13-55,55>>^ Is this not the carpenter’s son? Is not his mother called Mary, and his brothers James and Joseph and Simon and Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ And his sisters, are they not all with us? Where, then, did this man get all these things?”

[[v40-13-57]]

^<<v40-13-57,57>>^ So they began to stumble at him. But Jesus said to them: “A prophet is not unhonored except in his home territory and in his own house.”

[[v40-13-58]]

^<<v40-13-58,58>>^ And he did not do many powerful works there on account of their lack of faith.

'''

xref:040-matthew/040-matthew-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-matthew/040-matthew-014.adoc#v40-14-0[Próximo Capítulo &#62;]