include::./index.adoc[]

[[v40-3-0]]
=== According to Matthew, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-3-1]]

^<<v40-3-1,1>>^ In those days John^&#42;1^ the Baptist^&#42;2^ came preaching^&#42;3^ in the wilderness of Ju·deʹa,

[NOTE]
====
. “John.” Gr., I·o·aʹnes; J1-14,​16-18,​22(Heb.), Yoh·cha·nanʹ, “Johanan,” meaning “Jehovah Has Shown Favor; Jehovah Has Been Gracious.”
. Or, “the Immerser; the Dipper.” Gr., ho Ba·pti·stesʹ; J17,​22(Heb.), ham·Mat·bilʹ.
. Or, “heralding.” Gr., ke·rysʹson; Lat., praeʹdi·cans.
====

[[v40-3-2]]

^<<v40-3-2,2>>^ saying: “REPENT, for the kingdom of the heavens^&#42;1^ has drawn near.”

[NOTE]
====
. “Kingdom of the heavens.” Gr., ba·si·leiʹa ton ou·ra·nonʹ; Lat., reʹgnum cae·loʹrum; J22(Heb.), mal·khuthʹ sha·maʹyim.
====

[[v40-3-3]]

^<<v40-3-3,3>>^ This, in fact, is the one spoken of through Isaiah the prophet in these words: “Listen! Someone is crying out in the wilderness, ‘Prepare the way of Jehovah,^&#42;1^ YOU people! Make his roads straight.’”

[NOTE]
====
. See App 1D.
====

[[v40-3-4]]

^<<v40-3-4,4>>^ But this very John had his clothing of camel’s hair and a leather girdle^&#42;1^ around his loins; his food too was insect locusts and wild honey.

[NOTE]
====
. Or, “belt.”
====

[[v40-3-5]]

^<<v40-3-5,5>>^ Then Jerusalem^&#42;1^ and all Ju·deʹa and all the country around the Jordan made their way out to him,

[NOTE]
====
. Meaning “Possession [or, Foundation] of Twofold Peace.” Gr., I·e·ro·soʹly·ma; J22(Heb.), Yeru·sha·laʹyim.
====

[[v40-3-6]]

^<<v40-3-6,6>>^ and people were baptized by him in the Jordan River, openly confessing their sins.

[[v40-3-7]]

^<<v40-3-7,7>>^ When he caught sight of many of the Pharisees and Sadducees coming to the baptism, he said to them: “YOU offspring of vipers, who has intimated to YOU to flee from the coming wrath?

[[v40-3-8]]

^<<v40-3-8,8>>^ So then produce fruit that befits repentance;^&#42;1^

[NOTE]
====
. Lit., “change of mind.” Gr., me·ta·noiʹas.
====

[[v40-3-9]]

^<<v40-3-9,9>>^ and do not presume to say to yourselves, ‘As a father we have Abraham.’ For I say to YOU that God is able to raise up children to Abraham from these stones.

[[v40-3-10]]

^<<v40-3-10,10>>^ Already the ax is lying at the root of the trees; every tree, then, that does not produce fine fruit is to be cut down and thrown into the fire.

[[v40-3-11]]

^<<v40-3-11,11>>^ I, for my part, baptize^&#42;1^ YOU with water because of YOUR repentance; but the one coming after me is stronger than I am, whose sandals I am not fit to take off. That one will baptize YOU people with holy spirit^&#42;2^ and with fire.

[NOTE]
====
. Or, “immerse; dip.” Gr., ba·ptiʹzo.
. Or, “active force.” Gr., pneuʹma·ti; Lat., spiʹri·tu; J17,​18,​22(Heb.), beruʹach, “with active force.” See Ge 1:2 ftn, “Force.”
====

[[v40-3-12]]

^<<v40-3-12,12>>^ His winnowing shovel is in his hand, and he will completely clean up his threshing floor, and will gather his wheat into the storehouse, but the chaff he will burn up with fire that cannot be put out.”

[[v40-3-13]]

^<<v40-3-13,13>>^ Then Jesus came from Galʹi·lee to the Jordan to John, in order to be baptized by him.

[[v40-3-14]]

^<<v40-3-14,14>>^ But the latter tried to prevent him, saying: “I am the one needing to be baptized by you, and are you coming to me?”

[[v40-3-15]]

^<<v40-3-15,15>>^ In reply Jesus said to him: “Let it be, this time, for in that way it is suitable for us to carry out all that is righteous.” Then he quit preventing him.

[[v40-3-16]]

^<<v40-3-16,16>>^ After being baptized Jesus immediately came up from the water; and, look! the heavens were opened up, and he saw descending like a dove God’s spirit coming upon him.

[[v40-3-17]]

^<<v40-3-17,17>>^ Look! Also, there was a voice from the heavens that said: “This is my Son, the beloved, whom I have approved.”

'''

xref:040-matthew/040-matthew-002.adoc#v40-2-0[&#60; Capítulo Anterior] | <<v40-3-0,Topo>> | xref:040-matthew/040-matthew-004.adoc#v40-4-0[Próximo Capítulo &#62;]