include::./index.adoc[]

[[v40-27-0]]
=== According to Matthew, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-27-1]]

^<<v40-27-1,1>>^ When it had become morning, all the chief priests and the older men of the people held a consultation against Jesus so as to put him to death.

[[v40-27-2]]

^<<v40-27-2,2>>^ And, after binding him, they led him off and handed him over to Pilate the governor.

[[v40-27-3]]

^<<v40-27-3,3>>^ Then Judas, who betrayed him, seeing he had been condemned, felt remorse and turned the thirty silver pieces back to the chief priests and older men,

[[v40-27-4]]

^<<v40-27-4,4>>^ saying: “I sinned when I betrayed righteous blood.” They said: “What is that to us? You must see to that!”

[[v40-27-5]]

^<<v40-27-5,5>>^ So he threw the silver pieces into the temple^&#42;1^ and withdrew, and went off and hanged himself.

[NOTE]
====
. See 26:61 ftn.
====

[[v40-27-6]]

^<<v40-27-6,6>>^ But the chief priests took the silver pieces and said: “It is not lawful to drop them into the sacred treasury, because they are the price of blood.”

[[v40-27-7]]

^<<v40-27-7,7>>^ After consulting together, they bought with them the potter’s field to bury strangers.

[[v40-27-8]]

^<<v40-27-8,8>>^ Therefore that field has been called “Field of Blood” to this very day.

[[v40-27-9]]

^<<v40-27-9,9>>^ Then what was spoken through Jeremiah^&#42;1^ the prophet was fulfilled, saying: “And they took^&#42;2^ the thirty silver pieces, the price upon the man that was priced, the one on whom some of the sons of Israel set a price,

[NOTE]
====
. “Jeremiah,” אAB; Syh(margin), “Zachariah”; Syp,s omit.
. “They took,” AB; אSyh,p,s, “I took.”
====

[[v40-27-10]]

^<<v40-27-10,10>>^ and they gave^&#42;1^ them for the potter’s field, according to what Jehovah^&#42;2^ had commanded me.”

[NOTE]
====
. “They gave,” AcB*CItVg; אBcWSyh,p,s, “I gave.”
. See App 1D.
====

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus now stood before the governor; and the governor put the question to him: “Are you the king of the Jews?” Jesus replied: “You yourself say &#91;it&#93;.”

[[v40-27-12]]

^<<v40-27-12,12>>^ But, while he was being accused by the chief priests and older men, he made no answer.

[[v40-27-13]]

^<<v40-27-13,13>>^ Then Pilate said to him: “Do you not hear how many things they are testifying against you?”

[[v40-27-14]]

^<<v40-27-14,14>>^ Yet he did not answer him, no, not a word, so that the governor wondered very much.

[[v40-27-15]]

^<<v40-27-15,15>>^ Now from festival to festival it was the custom of the governor to release a prisoner to the crowd, the one they wanted.

[[v40-27-16]]

^<<v40-27-16,16>>^ Just at that time they were holding a notorious prisoner called Bar·abʹbas.

[[v40-27-17]]

^<<v40-27-17,17>>^ Hence when they were gathered together Pilate said to them: “Which one do YOU want me to release to YOU, Bar·abʹbas or Jesus the so-called Christ?”

[[v40-27-18]]

^<<v40-27-18,18>>^ For he was aware that out of envy they had handed him over.

[[v40-27-19]]

^<<v40-27-19,19>>^ Moreover, while he was sitting on the judgment seat, his wife sent out to him, saying: “Have nothing to do with that righteous man,^&#42;1^ for I suffered a lot today in a dream because of him.”

[NOTE]
====
. See App 7B.
====

[[v40-27-20]]

^<<v40-27-20,20>>^ But the chief priests and the older men persuaded the crowds to ask for Bar·abʹbas, but to have Jesus destroyed.

[[v40-27-21]]

^<<v40-27-21,21>>^ Now in responding the governor said to them: “Which of the two do YOU want me to release to YOU?” They said: “Bar·abʹbas.”

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilate said to them: “What, then, shall I do with Jesus the so-called Christ?” They all said: “Let him be impaled!”^&#42;1^

[NOTE]
====
. Or, “fastened on a stake (pole)!” See App 5C.
====

[[v40-27-23]]

^<<v40-27-23,23>>^ He said: “Why, what bad thing did he do?” Still they kept crying out all the more: “Let him be impaled!”

[[v40-27-24]]

^<<v40-27-24,24>>^ Seeing that it did no good but, rather, an uproar was arising, Pilate took water and washed his hands before the crowd, saying: “I am innocent of the blood of this &#91;man&#93;.^&#42;1^ YOU yourselves must see to it.”

[NOTE]
====
. Or, “innocent of this blood.”
====

[[v40-27-25]]

^<<v40-27-25,25>>^ At that all the people said in answer: “His blood come upon us and upon our children.”

[[v40-27-26]]

^<<v40-27-26,26>>^ Then he released Bar·abʹbas to them, but he had Jesus whipped and handed him over to be impaled.

[[v40-27-27]]

^<<v40-27-27,27>>^ Then the soldiers of the governor took Jesus into the governor’s palace and gathered the whole body of troops together to him.

[[v40-27-28]]

^<<v40-27-28,28>>^ And disrobing him, they draped him with a scarlet cloak,

[[v40-27-29]]

^<<v40-27-29,29>>^ and they braided a crown out of thorns and put it on his head and a reed in his right hand. And, kneeling before him, they made fun of him, saying: “Good day, you King of the Jews!”

[[v40-27-30]]

^<<v40-27-30,30>>^ And they spit upon him and took the reed and began hitting him upon his head.

[[v40-27-31]]

^<<v40-27-31,31>>^ Finally, when they had made fun of him, they took the cloak off and put his outer garments upon him and led him off for impaling.

[[v40-27-32]]

^<<v40-27-32,32>>^ As they were going out they found a native of Cy·reʹne named Simon. This man they impressed into service to lift up his torture stake.

[[v40-27-33]]

^<<v40-27-33,33>>^ And when they came to a place called Golʹgo·tha,^&#42;1^ that is to say, Skull Place,^&#42;2^

[NOTE]
====
. “Golgotha.” Gr., Gol·go·thaʹ; Lat., Golʹgo·tha; J17,​18(Heb.), Gol·gol·taʼʹ.
. “Skull Place.” Gr., Kra·niʹou Toʹpos; Lat., Cal·vaʹri·ae loʹcus; J17(Heb.), meqohmʹ Gul·goʹleth.
====

[[v40-27-34]]

^<<v40-27-34,34>>^ they gave him wine mixed with gall to drink; but, after tasting it, he refused to drink.

[[v40-27-35]]

^<<v40-27-35,35>>^ When they had impaled him they distributed his outer garments by casting lots,

[[v40-27-36]]

^<<v40-27-36,36>>^ and, as they sat, they watched over him there.

[[v40-27-37]]

^<<v40-27-37,37>>^ Also, they posted above his head the charge against him, in writing: “This is Jesus the King of the Jews.”

[[v40-27-38]]

^<<v40-27-38,38>>^ Then two robbers were impaled with him, one on his right and one on his left.

[[v40-27-39]]

^<<v40-27-39,39>>^ So the passersby began speaking abusively of him, wagging their heads

[[v40-27-40]]

^<<v40-27-40,40>>^ and saying: “O you would-be thrower-down of the temple and builder of it in three days, save yourself! If you are a son of God, come down off the torture stake!”

[[v40-27-41]]

^<<v40-27-41,41>>^ In like manner also the chief priests with the scribes and older men began making fun of him and saying:

[[v40-27-42]]

^<<v40-27-42,42>>^ “Others he saved; himself he cannot save! He is King of Israel; let him now come down off the torture stake and we will believe on him.

[[v40-27-43]]

^<<v40-27-43,43>>^ He has put his trust in God; let Him now rescue him if He wants him, for he said, ‘I am God’s Son.’”

[[v40-27-44]]

^<<v40-27-44,44>>^ In the same way even the robbers that were impaled together with him began reproaching him.

[[v40-27-45]]

^<<v40-27-45,45>>^ From the sixth hour^&#42;1^ on a darkness fell over all the land, until the ninth hour.^&#42;2^

[NOTE]
====
. “Sixth hour,” that is, about 12 noon.
. “Ninth hour,” that is, about 3 p.m.
====

[[v40-27-46]]

^<<v40-27-46,46>>^ About the ninth hour Jesus called out with a loud voice, saying: “Eʹli, Eʹli, laʹma sa·bach·thaʹni?”^&#42;1^ that is, “My God, my God, why have you forsaken me?”

[NOTE]
====
. “Eli, Eli, lama sabachthani?” Compare Ps 22:1 ftn, “Me.”
====

[[v40-27-47]]

^<<v40-27-47,47>>^ At hearing this, some of those standing there began to say: “This man is calling E·liʹjah.”

[[v40-27-48]]

^<<v40-27-48,48>>^ And immediately one of them ran and took a sponge and soaked it with sour wine and put it on a reed and went giving him a drink.

[[v40-27-49]]

^<<v40-27-49,49>>^ But the rest of them said: “Let him be! Let us see whether E·liʹjah comes to save him.” &#91;&#91;Another man took a spear and pierced his side, and blood and water came out.&#93;&#93;^&#42;1^

[NOTE]
====
. “Another man . . . came out,” אBC; ADWItVgSyh,p,sArm omit.
====

[[v40-27-50]]

^<<v40-27-50,50>>^ Again Jesus cried out with a loud voice, and yielded up &#91;his&#93; spirit.^&#42;1^

[NOTE]
====
. Or, “ceased to breathe.” Lit., “he let go off the spirit.” Gr., a·pheʹken to pneuʹma.
====

[[v40-27-51]]

^<<v40-27-51,51>>^ And, look! the curtain of the sanctuary was rent in two, from top to bottom, and the earth quaked, and the rock-masses were split.

[[v40-27-52]]

^<<v40-27-52,52>>^ And the memorial tombs were opened and many bodies of the holy ones that had fallen asleep were raised up,

[[v40-27-53]]

^<<v40-27-53,53>>^ (and persons,^&#42;1^ coming out from among the memorial tombs after his being raised up, entered into the holy city,) and they became visible to many people.

[NOTE]
====
. Or, “they,” not referring to the “bodies.”
====

[[v40-27-54]]

^<<v40-27-54,54>>^ But the army officer^&#42;1^ and those with him watching over Jesus, when they saw the earthquake and the things happening, grew very much afraid, saying: “Certainly this was God’s Son.”^&#42;2^

[NOTE]
====
. Lit., “the centurion,” that is, the one in command of 100 soldiers.
. Or, “a son of God; a son of a god.”
====

[[v40-27-55]]

^<<v40-27-55,55>>^ Moreover, many women were there viewing from a distance, who had accompanied Jesus from Galʹi·lee to minister to him;

[[v40-27-56]]

^<<v40-27-56,56>>^ among whom was Mary Magʹda·lene, also Mary the mother of James and Joʹses,^&#42;1^ and the mother of the sons of Zebʹe·dee.

[NOTE]
====
. “Joses,” ABCDcSyh,p; אD*WVgSys, “Joseph.”
====

[[v40-27-57]]

^<<v40-27-57,57>>^ Now as it was late in the afternoon, there came a rich man of Ar·i·ma·theʹa, named Joseph, who had also himself become a disciple of Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ This man went up to Pilate and asked for the body of Jesus. Then Pilate commanded it to be given over.

[[v40-27-59]]

^<<v40-27-59,59>>^ And Joseph took the body, wrapped it up in clean fine linen,

[[v40-27-60]]

^<<v40-27-60,60>>^ and laid it in his new memorial tomb, which he had quarried in the rock-mass. And, after rolling a big stone to the door of the memorial tomb, he left.

[[v40-27-61]]

^<<v40-27-61,61>>^ But Mary Magʹda·lene and the other Mary continued there, sitting before the grave.

[[v40-27-62]]

^<<v40-27-62,62>>^ The next day, which was after the Preparation, the chief priests and the Pharisees gathered together before Pilate,

[[v40-27-63]]

^<<v40-27-63,63>>^ saying: “Sir, we have called to mind that that impostor said while yet alive, ‘After three days I am to be raised up.’

[[v40-27-64]]

^<<v40-27-64,64>>^ Therefore command the grave to be made secure until the third day, that his disciples may never come and steal him and say to the people, ‘He was raised up from the dead!’ and this last imposture will be worse than the first.”

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilate said to them: “YOU have a guard. Go make it as secure as YOU know how.”

[[v40-27-66]]

^<<v40-27-66,66>>^ So they went and made the grave secure by sealing the stone and having the guard.

'''

xref:040-matthew/040-matthew-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-matthew/040-matthew-028.adoc#v40-28-0[Próximo Capítulo &#62;]