include::./index.adoc[]

[[v40-1-0]]
=== According to Matthew, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-1-1]]

^<<v40-1-1,1>>^ The book of the history^&#42;1^ of Jesus Christ, son of David, son of Abraham:

[NOTE]
====
. Or, “line of descent; origin.” Gr., ge·neʹse·os, “genesis”; Lat., ge·ne·ra·ti·oʹnis, “generation”; J17,​18(Heb.), toh·ledhothʹ, “geneology.” See Ge 2:4 and Ge 5:1 ftns, “History.”
====

[[v40-1-2]]

^<<v40-1-2,2>>^ Abraham became father to^&#42;1^ Isaac;
Isaac became father to Jacob;
Jacob became father to Judah and his brothers;

[NOTE]
====
. Lit., “generated.” Gr., e·genʹne·sen; Lat., geʹnu·it, “begat.”
====

[[v40-1-3]]

^<<v40-1-3,3>>^ Judah became father to Peʹrez and to Zeʹrah by Taʹmar;
Peʹrez became father to Hezʹron;
Hezʹron became father to Ram;

[[v40-1-4]]

^<<v40-1-4,4>>^ Ram became father to Am·minʹa·dab;
Am·minʹa·dab became father to Nahʹshon;
Nahʹshon became father to Salʹmon;

[[v40-1-5]]

^<<v40-1-5,5>>^ Salʹmon became father to Boʹaz by Raʹhab;
Boʹaz became father to Oʹbed by Ruth;
Oʹbed became father to Jesʹse;

[[v40-1-6]]

^<<v40-1-6,6>>^ Jesʹse became father to David the king.
 David became father to Solʹo·mon by the wife of U·riʹah;^&#42;1^

[NOTE]
====
. Or, “by her who had belonged to Uriah.”
====

[[v40-1-7]]

^<<v40-1-7,7>>^ Solʹo·mon became father to Re·ho·boʹam;
Re·ho·boʹam became father to A·biʹjah;
A·biʹjah became father to Aʹsa;

[[v40-1-8]]

^<<v40-1-8,8>>^ Aʹsa became father to Je·hoshʹa·phat;
Je·hoshʹa·phat became father to Je·hoʹram;
Je·hoʹram became father to^&#42;1^ Uz·ziʹah;

[NOTE]
====
. WH omits Ahaziah, Jehoash, Amaziah. But see 1Ch 3:11, 12.
====

[[v40-1-9]]

^<<v40-1-9,9>>^ Uz·ziʹah became father to Joʹtham;
Joʹtham became father to Aʹhaz;
Aʹhaz became father to Hez·e·kiʹah;

[[v40-1-10]]

^<<v40-1-10,10>>^ Hez·e·kiʹah became father to Ma·nasʹseh;
Ma·nasʹseh became father to Aʹmon;
Aʹmon became father to Jo·siʹah;

[[v40-1-11]]

^<<v40-1-11,11>>^ Jo·siʹah became father to Jec·o·niʹah and to his brothers at the time of the deportation to Babylon.^&#42;1^

[NOTE]
====
. Gr., Ba·by·loʹnos; J17,​22(Heb.), Ba·velʹ. See 2Ki 17:24 ftn.
====

[[v40-1-12]]

^<<v40-1-12,12>>^ After the deportation to Babylon Jec·o·niʹah became father to She·alʹti·el;
She·alʹti·el became father to Ze·rubʹba·bel;

[[v40-1-13]]

^<<v40-1-13,13>>^ Ze·rubʹba·bel became father to A·biʹud;
A·biʹud became father to E·liʹa·kim;
E·liʹa·kim became father to Aʹzor;

[[v40-1-14]]

^<<v40-1-14,14>>^ Aʹzor became father to Zaʹdok;
Zaʹdok became father to Aʹchim;
Aʹchim became father to E·liʹud;

[[v40-1-15]]

^<<v40-1-15,15>>^ E·liʹud became father to El·e·aʹzar;
El·e·aʹzar became father to Matʹthan;
Matʹthan became father to Jacob;

[[v40-1-16]]

^<<v40-1-16,16>>^ Jacob became father to Joseph the husband of Mary, of whom Jesus was born, who is called Christ.

[[v40-1-17]]

^<<v40-1-17,17>>^ All the generations, then, from Abraham until David were fourteen generations, and from David until the deportation to Babylon fourteen generations, and from the deportation to Babylon until the Christ fourteen generations.

[[v40-1-18]]

^<<v40-1-18,18>>^ But the birth of Jesus Christ was in this way. During the time his mother Mary was promised in marriage to Joseph, she was found to be pregnant by holy spirit before they were united.

[[v40-1-19]]

^<<v40-1-19,19>>^ However, Joseph her husband, because he was righteous and did not want to make her a public spectacle, intended to divorce^&#42;1^ her secretly.

[NOTE]
====
. Or, “to release.” Lit., “to loose off.”
====

[[v40-1-20]]

^<<v40-1-20,20>>^ But after he had thought these things over, look! Jehovah’s^&#42;1^ angel appeared to him in a dream, saying: “Joseph, son of David, do not be afraid to take Mary your wife home, for that which has been begotten in her is by holy spirit.

[NOTE]
====
. “Jehovah’s.” J3,​4,​7-14,​16-18,​22-24(Heb.), יהוה (Yeho·wahʹ); Gr., Κυρίου (Ky·riʹou), without the definite article, “Lord’s.” The Holy Scriptures, by J. N. Darby, 1920 (corresponding to the German “Elberfelder Bibel,” 1891), says in a ftn on Mt 1:20: “ ‘Lord’ without the article, signifying as very often, ‘Jehovah.’ ” This is the first of 237 places in the Christian Greek Scriptures where the divine name “Jehovah” occurs in the main text of this translation. In addition it occurs 72 times in the ftns but not in the main text. See App 1D.
====

[[v40-1-21]]

^<<v40-1-21,21>>^ She will give birth to a son, and you must call his name Jesus,^&#42;1^ for he will save his people from their sins.”

[NOTE]
====
. “Jesus.” Gr., Ἰησοῦν (I·e·sounʹ); J1-14,​16-18,​22(Heb.), ישוע (Ye·shuʹaʽ, “Jeshua,” meaning “Jehovah Is Salvation”).
====

[[v40-1-22]]

^<<v40-1-22,22>>^ All this actually came about for that to be fulfilled which was spoken by Jehovah^&#42;1^ through his prophet, saying:

[NOTE]
====
. See App 1D.
====

[[v40-1-23]]

^<<v40-1-23,23>>^ “Look! The virgin^&#42;1^ will become pregnant and will give birth to a son, and they will call his name Im·manʹu·el,”^&#42;2^ which means, when translated, “With Us Is God.”

[NOTE]
====
. “The virgin.” Gr., he par·theʹnos; J22(Heb.), ha·ʽal·mahʹ.
. Gr., Em·ma·nou·elʹ; J17,​18,​22(Heb.), ʽIm·ma·nu·ʼelʹ.
====

[[v40-1-24]]

^<<v40-1-24,24>>^ Then Joseph woke up from his sleep and did as the angel of Jehovah^&#42;1^ had directed him, and he took his wife home.

[NOTE]
====
. See App 1D.
====

[[v40-1-25]]

^<<v40-1-25,25>>^ But he had no intercourse with her^&#42;1^ until she gave birth to a son; and he called his name Jesus.

[NOTE]
====
. Lit., “he was not knowing her.”
====

'''

xref:039-malachi/039-malachi-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-matthew/040-matthew-002.adoc#v40-2-0[Próximo Capítulo &#62;]