include::./index.adoc[]

[[v40-17-0]]
=== According to Matthew, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-17-1]]

^<<v40-17-1,1>>^ Six days later Jesus took Peter and James and John his brother along and brought them up into a lofty mountain by themselves.

[[v40-17-2]]

^<<v40-17-2,2>>^ And he was transfigured before them, and his face shone as the sun, and his outer garments became brilliant as the light.

[[v40-17-3]]

^<<v40-17-3,3>>^ And, look! there appeared to them Moses and E·liʹjah, conversing with him.

[[v40-17-4]]

^<<v40-17-4,4>>^ Responsively Peter said to Jesus: “Lord, it is fine for us to be here. If you wish, I will erect three tents here, one for you and one for Moses and one for E·liʹjah.”

[[v40-17-5]]

^<<v40-17-5,5>>^ While he was yet speaking, look! a bright cloud overshadowed them, and, look! a voice out of the cloud, saying: “This is my Son, the beloved, whom I have approved; listen to him.”

[[v40-17-6]]

^<<v40-17-6,6>>^ At hearing this the disciples fell upon their faces and became very much afraid.

[[v40-17-7]]

^<<v40-17-7,7>>^ Then Jesus came near and, touching them, said: “Get up and have no fear.”

[[v40-17-8]]

^<<v40-17-8,8>>^ When they raised their eyes, they saw no one but Jesus himself only.

[[v40-17-9]]

^<<v40-17-9,9>>^ And as they were descending from the mountain, Jesus commanded them, saying: “Tell the vision to no one until the Son of man is raised up from the dead.”

[[v40-17-10]]

^<<v40-17-10,10>>^ However, the disciples put the question to him: “Why, then, do the scribes say that E·liʹjah must come first?”

[[v40-17-11]]

^<<v40-17-11,11>>^ In reply he said: “E·liʹjah, indeed, is coming and will restore all things.

[[v40-17-12]]

^<<v40-17-12,12>>^ However, I say to YOU that E·liʹjah has already come and they did not recognize him but did with him the things they wanted. In this way also the Son of man is destined to suffer at their hands.”

[[v40-17-13]]

^<<v40-17-13,13>>^ Then the disciples perceived that he spoke to them about John the Baptist.

[[v40-17-14]]

^<<v40-17-14,14>>^ And when they came toward the crowd, a man approached him, kneeling down to him and saying:

[[v40-17-15]]

^<<v40-17-15,15>>^ “Lord, have mercy on my son, because he is an epileptic and is ill, for he falls often into the fire and often into the water;

[[v40-17-16]]

^<<v40-17-16,16>>^ and I brought him to your disciples, but they could not cure him.”

[[v40-17-17]]

^<<v40-17-17,17>>^ In reply Jesus said: “O faithless and twisted generation, how long must I continue with YOU? How long must I put up with YOU? Bring him here to me.”

[[v40-17-18]]

^<<v40-17-18,18>>^ Then Jesus rebuked it,^&#42;1^ and the demon came out of him; and the boy was cured from that hour.

[NOTE]
====
. Or, “him.”
====

[[v40-17-19]]

^<<v40-17-19,19>>^ Thereupon the disciples came up to Jesus privately and said: “Why is it we could not expel it?”

[[v40-17-20]]

^<<v40-17-20,20>>^ He said to them: “Because of YOUR little faith. For truly I say to YOU, If YOU have faith the size of a mustard grain, YOU will say to this mountain, ‘Transfer from here to there,’ and it will transfer, and nothing will be impossible for YOU.”

[[v40-17-21]]

^<<v40-17-21,21>>^ ^&#42;1^ ——

[NOTE]
====
. א*BSyc,s omit vs 21; CDWVgSypArm, “However, this kind does not come out except by prayer and fasting.”
====

[[v40-17-22]]

^<<v40-17-22,22>>^ It was while they were gathered together in Galʹi·lee that Jesus said to them: “The Son of man is destined to be betrayed into men’s hands,

[[v40-17-23]]

^<<v40-17-23,23>>^ and they will kill him, and the third day he will be raised up.” Consequently they were very much grieved.

[[v40-17-24]]

^<<v40-17-24,24>>^ After they arrived in Ca·perʹna·um the men collecting the two drachmas^&#42;1^ &#91;tax&#93; approached Peter and said: “Does YOUR teacher not pay the two drachmas &#91;tax&#93;?”

[NOTE]
====
. Lit., “the double drachmas.” Gr., ta diʹdrakh·ma. See App 8A.
====

[[v40-17-25]]

^<<v40-17-25,25>>^ He said: “Yes.” However, when he entered the house Jesus got ahead of him by saying: “What do you think, Simon? From whom do the kings of the earth receive duties or head tax? From their sons or from the strangers?”

[[v40-17-26]]

^<<v40-17-26,26>>^ When he said: “From the strangers,” Jesus said to him: “Really, then, the sons are tax-free.

[[v40-17-27]]

^<<v40-17-27,27>>^ But that we do not cause them to stumble, you go to the sea, cast a fishhook, and take the first fish coming up and, when you open its mouth, you will find a stater coin.^&#42;1^ Take that and give it to them for me and you.”

[NOTE]
====
. “A stater coin,” considered to be the tetradrachma. See App 8A.
====

'''

xref:040-matthew/040-matthew-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-matthew/040-matthew-018.adoc#v40-18-0[Próximo Capítulo &#62;]