include::./index.adoc[]

[[v40-26-0]]
=== According to Matthew, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-26-1]]

^<<v40-26-1,1>>^ Now when Jesus had finished all these sayings, he said to his disciples:

[[v40-26-2]]

^<<v40-26-2,2>>^ “YOU know that two days from now the passover occurs, and the Son of man is to be delivered up to be impaled.”^&#42;1^

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v40-26-3]]

^<<v40-26-3,3>>^ Then the chief priests and the older men of the people gathered together in the courtyard of the high priest who was called Caʹia·phas,

[[v40-26-4]]

^<<v40-26-4,4>>^ and took counsel together to seize Jesus by crafty device and kill him.

[[v40-26-5]]

^<<v40-26-5,5>>^ However, they kept saying: “Not at the festival, in order that no uproar may arise among the people.”

[[v40-26-6]]

^<<v40-26-6,6>>^ While Jesus happened to be in Bethʹa·ny in the house of Simon the leper,

[[v40-26-7]]

^<<v40-26-7,7>>^ a woman with an alabaster case of costly perfumed oil approached him, and she began pouring it upon his head as he was reclining at the table.

[[v40-26-8]]

^<<v40-26-8,8>>^ On seeing this the disciples became indignant and said: “Why this waste?

[[v40-26-9]]

^<<v40-26-9,9>>^ For this could have been sold for a great deal and been given to poor people.”

[[v40-26-10]]

^<<v40-26-10,10>>^ Aware of this, Jesus said to them: “Why do YOU try to make trouble for the woman? For she did a fine deed toward me.

[[v40-26-11]]

^<<v40-26-11,11>>^ For YOU always have the poor with YOU, but YOU will not always have me.

[[v40-26-12]]

^<<v40-26-12,12>>^ For when this woman put this perfumed oil upon my body, she did it for the preparation of me for burial.

[[v40-26-13]]

^<<v40-26-13,13>>^ Truly I say to YOU, Wherever this good news is preached^&#42;1^ in all the world,^&#42;2^ what this woman did shall also be told as a remembrance of her.”

[NOTE]
====
. Or, “is heralded.” Gr., ke·ry·khtheiʹ; Lat., prae·di·caʹtum fuʹe·rit. Compare Da 5:29 ftn, “Heralded.”
. “World.” Gr., koʹsmoi; Lat., munʹdo.
====

[[v40-26-14]]

^<<v40-26-14,14>>^ Then one of the twelve, the one called Judas Is·carʹi·ot, went to the chief priests

[[v40-26-15]]

^<<v40-26-15,15>>^ and said: “What will YOU give me to betray him to YOU?” They stipulated to him thirty silver pieces.

[[v40-26-16]]

^<<v40-26-16,16>>^ So from then on he kept seeking a good opportunity to betray him.

[[v40-26-17]]

^<<v40-26-17,17>>^ On the first day of^&#42;1^ the unfermented cakes the disciples came up to Jesus, saying: “Where do you want us to prepare for you to eat the passover?”

[NOTE]
====
. Or, “On the day before.” This rendering of the Gr. word πρῶτος (proʹtos) followed by the genitive case of the next word agrees with the sense and rendering of a like construction in Joh 1:15, 30, namely, “he existed before [proʹtos] me.” According to LS, p. 1535, col. 1, “πρῶτος is sts. [sometimes] used where we should expect πρότερος [proʹte·ros].”
====

[[v40-26-18]]

^<<v40-26-18,18>>^ He said: “Go into the city to So-and-so and say to him, The Teacher says, ‘My appointed time is near; I will celebrate the passover with my disciples at your home.’”

[[v40-26-19]]

^<<v40-26-19,19>>^ And the disciples did as Jesus ordered them, and they got things ready for the passover.

[[v40-26-20]]

^<<v40-26-20,20>>^ When, now, it had become evening, he was reclining at the table with the twelve disciples.

[[v40-26-21]]

^<<v40-26-21,21>>^ While they were eating, he said: “Truly I say to YOU, One of YOU will betray me.”

[[v40-26-22]]

^<<v40-26-22,22>>^ Being very much grieved at this, they commenced each and every one to say to him: “Lord, it is not I, is it?”

[[v40-26-23]]

^<<v40-26-23,23>>^ In reply he said: “He that dips his hand with me in the bowl is the one that will betray me.

[[v40-26-24]]

^<<v40-26-24,24>>^ True, the Son of man is going away, just as it is written concerning him, but woe to that man through whom the Son of man is betrayed! It would have been finer for him if that man had not been born.”

[[v40-26-25]]

^<<v40-26-25,25>>^ By way of reply Judas, who was about to betray him, said: “It is not I, is it, Rabbi?” He said to him: “You yourself said &#91;it&#93;.”

[[v40-26-26]]

^<<v40-26-26,26>>^ As they continued eating, Jesus took a loaf and, after saying a blessing, he broke it and, giving it to the disciples, he said: “TAKE, eat. This means^&#42;1^ my body.”

[NOTE]
====
. Lit., “is.” Gr., e·stin, in the sense of signifying, importing, representing. See 12:7 ftn; 1Co 10:4 ftn, “Meant.”
====

[[v40-26-27]]

^<<v40-26-27,27>>^ Also, he took a cup and, having given thanks, he gave it to them, saying: “Drink out of it, all of YOU;

[[v40-26-28]]

^<<v40-26-28,28>>^ for this means my ‘blood of the covenant,’ which is to be poured out in behalf of many for forgiveness of sins.

[[v40-26-29]]

^<<v40-26-29,29>>^ But I tell YOU, I will by no means drink henceforth any of this product of the vine until that day when I drink it new^&#42;1^ with YOU in the kingdom of my Father.”

[NOTE]
====
. “It new,” that is, the vine’s new product.
====

[[v40-26-30]]

^<<v40-26-30,30>>^ Finally, after singing praises,^&#42;1^ they went out to the Mount of Olives.

[NOTE]
====
. Or, “after singing hymns (psalms).” Gr., hy·mneʹsan·tes; J18(Heb.), wai·yiq·reʼuʹ ʼeth-ha·hal·lelʹ. Doubtless the last four of the Hallel Psalms (115-118). See Ps 114:1 ftn.
====

[[v40-26-31]]

^<<v40-26-31,31>>^ Then Jesus said to them: “All of YOU will be stumbled in connection with me on this night, for it is written, ‘I will strike the shepherd, and the sheep of the flock will be scattered about.’

[[v40-26-32]]

^<<v40-26-32,32>>^ But after I have been raised up, I will go ahead of YOU into Galʹi·lee.”

[[v40-26-33]]

^<<v40-26-33,33>>^ But Peter, in answer, said to him: “Although all the others are stumbled in connection with you, never will I be stumbled!”

[[v40-26-34]]

^<<v40-26-34,34>>^ Jesus said to him: “Truly I say to you, On this night, before a cock crows, you will disown me three times.”

[[v40-26-35]]

^<<v40-26-35,35>>^ Peter said to him: “Even if I should have to die with you, I will by no means disown you.” All the other disciples also said the same thing.

[[v40-26-36]]

^<<v40-26-36,36>>^ Then Jesus came with them to the spot called Geth·semʹa·ne, and he said to the disciples: “Sit down here while I go over there and pray.”

[[v40-26-37]]

^<<v40-26-37,37>>^ And taking along Peter and the two sons of Zebʹe·dee, he started to be grieved and to be sorely troubled.

[[v40-26-38]]

^<<v40-26-38,38>>^ Then he said to them: “My soul is deeply grieved, even to death. Stay here and keep on the watch with me.”

[[v40-26-39]]

^<<v40-26-39,39>>^ And going a little way forward, he fell upon his face, praying and saying: “My Father, if it is possible, let this cup pass away from me. Yet, not as I will, but as you will.”

[[v40-26-40]]

^<<v40-26-40,40>>^ And he came to the disciples and found them sleeping, and he said to Peter: “Could YOU men not so much as watch one hour with me?

[[v40-26-41]]

^<<v40-26-41,41>>^ Keep on the watch and pray continually, that YOU may not enter into temptation. The spirit, of course, is eager, but the flesh is weak.”

[[v40-26-42]]

^<<v40-26-42,42>>^ Again, for the second time, he went off and prayed, saying: “My Father, if it is not possible for this to pass away except I drink it, let your will take place.”

[[v40-26-43]]

^<<v40-26-43,43>>^ And he came again and found them sleeping, for their eyes were heavy.

[[v40-26-44]]

^<<v40-26-44,44>>^ So leaving them, he again went off and prayed for the third time, saying once more the same word.

[[v40-26-45]]

^<<v40-26-45,45>>^ Then he came to the disciples and said to them: “At such a time as this YOU are sleeping and taking YOUR rest! Look! The hour has drawn near for the Son of man to be betrayed into the hands of sinners.

[[v40-26-46]]

^<<v40-26-46,46>>^ Get up, let us go. Look! My betrayer has drawn near.”

[[v40-26-47]]

^<<v40-26-47,47>>^ And while he was yet speaking, look! Judas, one of the twelve, came and with him a great crowd with swords and clubs from the chief priests and older men of the people.

[[v40-26-48]]

^<<v40-26-48,48>>^ Now his betrayer had given them a sign, saying: “Whoever it is I kiss, this is he; take him into custody.”

[[v40-26-49]]

^<<v40-26-49,49>>^ And going straight up to Jesus he said: “Good day, Rabbi!” and kissed him very tenderly.

[[v40-26-50]]

^<<v40-26-50,50>>^ But Jesus said to him: “Fellow, for what purpose are you present?” Then they came forward and laid hands on Jesus and took him into custody.

[[v40-26-51]]

^<<v40-26-51,51>>^ But, look! one of those with Jesus reached out his hand and drew his sword and struck the slave of the high priest and took off his ear.

[[v40-26-52]]

^<<v40-26-52,52>>^ Then Jesus said to him: “Return your sword to its place, for all those who take the sword will perish by the sword.

[[v40-26-53]]

^<<v40-26-53,53>>^ Or do you think that I cannot appeal to my Father to supply me at this moment more than twelve legions of angels?

[[v40-26-54]]

^<<v40-26-54,54>>^ In that case, how would the Scriptures be fulfilled that it must take place this way?”

[[v40-26-55]]

^<<v40-26-55,55>>^ In that hour Jesus said to the crowds: “Have YOU come out with swords and clubs as against a robber to arrest me? Day after day I used to sit in the temple teaching, and yet YOU did not take me into custody.

[[v40-26-56]]

^<<v40-26-56,56>>^ But all this has taken place for the scriptures of the prophets to be fulfilled.” Then all the disciples abandoned him and fled.

[[v40-26-57]]

^<<v40-26-57,57>>^ Those who took Jesus into custody led him away to Caʹia·phas the high priest, where the scribes and the older men were gathered together.

[[v40-26-58]]

^<<v40-26-58,58>>^ But Peter kept following him at a good distance, as far as the courtyard of the high priest, and, after going inside, he was sitting with the house attendants to see the outcome.^&#42;1^

[NOTE]
====
. Or, “end.” Gr., teʹlos.
====

[[v40-26-59]]

^<<v40-26-59,59>>^ Meantime the chief priests and the entire Sanʹhe·drin^&#42;1^ were looking for false witness against Jesus in order to put him to death,

[NOTE]
====
. “Sanhedrin,” J17,​18,​22. Or, “Supreme Court.” See 5:22.
====

[[v40-26-60]]

^<<v40-26-60,60>>^ but they found none, although many false witnesses came forward. Later on two came forward

[[v40-26-61]]

^<<v40-26-61,61>>^ and said: “This man said, ‘I am able to throw down the temple^&#42;1^ of God and build it up in three days.’”

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplum; J17,​18,​22(Heb.), heh·khalʹ, “palace; temple.”
====

[[v40-26-62]]

^<<v40-26-62,62>>^ With that the high priest stood up and said to him: “Have you no answer? What is it these are testifying against you?”

[[v40-26-63]]

^<<v40-26-63,63>>^ But Jesus kept silent. So the high priest said to him: “By the living God I put you under oath to tell us whether you are the Christ the Son of God!”

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus said to him: “You yourself said &#91;it&#93;. Yet I say to YOU men, From henceforth YOU will see the Son of man sitting at the right hand of power and coming^&#42;1^ on the clouds of heaven.”

[NOTE]
====
. “Coming.” Gr., er·khoʹme·non.
====

[[v40-26-65]]

^<<v40-26-65,65>>^ Then the high priest ripped his outer garments, saying: “He has blasphemed! What further need do we have of witnesses? See! Now YOU have heard the blasphemy.

[[v40-26-66]]

^<<v40-26-66,66>>^ What is YOUR opinion?” They returned answer: “He is liable to death.”

[[v40-26-67]]

^<<v40-26-67,67>>^ Then they spit into his face and hit him with their fists. Others slapped him in the face,

[[v40-26-68]]

^<<v40-26-68,68>>^ saying: “Prophesy to us, you Christ. Who is it that struck you?”

[[v40-26-69]]

^<<v40-26-69,69>>^ Now Peter was sitting outside in the courtyard; and a servant girl came up to him, saying: “You, too, were with Jesus the Gal·i·leʹan!”

[[v40-26-70]]

^<<v40-26-70,70>>^ But he denied it before them all, saying: “I do not know what you are talking about.”

[[v40-26-71]]

^<<v40-26-71,71>>^ After he had gone out to the gatehouse, another girl noticed him and said to those there: “This man was with Jesus the Naz·a·reneʹ.”

[[v40-26-72]]

^<<v40-26-72,72>>^ And again he denied it, with an oath: “I do not know the man!”

[[v40-26-73]]

^<<v40-26-73,73>>^ After a little while those standing around came up and said to Peter: “Certainly you also are one of them, for, in fact, your dialect gives you away.”

[[v40-26-74]]

^<<v40-26-74,74>>^ Then he started to curse and swear: “I do not know the man!” And immediately a cock crowed.

[[v40-26-75]]

^<<v40-26-75,75>>^ And Peter called to mind the saying Jesus spoke, namely: “Before a cock crows, you will disown me three times.” And he went outside and wept bitterly.

'''

xref:040-matthew/040-matthew-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-matthew/040-matthew-027.adoc#v40-27-0[Próximo Capítulo &#62;]