include::./index.adoc[]

[[v40-11-0]]
=== According to Matthew, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-11-1]]

^<<v40-11-1,1>>^ Now when Jesus had finished giving instructions to his twelve disciples, he set out from there to teach and preach in their cities.

[[v40-11-2]]

^<<v40-11-2,2>>^ But John, having heard in jail about the works of the Christ, sent by means of his own disciples

[[v40-11-3]]

^<<v40-11-3,3>>^ and said to him: “Are you the Coming One, or are we to expect a different one?”

[[v40-11-4]]

^<<v40-11-4,4>>^ In reply Jesus said to them: “Go YOUR way and report to John what YOU are hearing and seeing:

[[v40-11-5]]

^<<v40-11-5,5>>^ The blind are seeing again, and the lame are walking about, the lepers are being cleansed and the deaf are hearing, and the dead are being raised up, and the poor are having the good news declared to them;

[[v40-11-6]]

^<<v40-11-6,6>>^ and happy is he that finds no cause for stumbling in me.”

[[v40-11-7]]

^<<v40-11-7,7>>^ While these were on their way, Jesus started to say to the crowds respecting John: “What did YOU go out into the wilderness to behold? A reed being tossed by a wind?

[[v40-11-8]]

^<<v40-11-8,8>>^ What, then, did YOU go out to see? A man dressed in soft garments? Why, those wearing soft garments are in the houses of kings.

[[v40-11-9]]

^<<v40-11-9,9>>^ Really, then, why did YOU go out? To see a prophet? Yes, I tell YOU, and far more than a prophet.

[[v40-11-10]]

^<<v40-11-10,10>>^ This is he concerning whom it is written, ‘Look! I myself am sending forth my messenger^&#42;1^ before your face, who will prepare your way ahead of you!’

[NOTE]
====
. Or, “angel.”
====

[[v40-11-11]]

^<<v40-11-11,11>>^ Truly I say to YOU people, Among those born of women there has not been raised up a greater than John the Baptist;^&#42;1^ but a person that is a lesser one in the kingdom of the heavens is greater than he is.

[NOTE]
====
. Or, “Immerser; Dipper.” Gr., Ba·pti·stouʹ.
====

[[v40-11-12]]

^<<v40-11-12,12>>^ But from the days of John the Baptist until now the kingdom of the heavens is the goal toward which men press, and those pressing forward are seizing it.

[[v40-11-13]]

^<<v40-11-13,13>>^ For all, the Prophets and the Law, prophesied until John;

[[v40-11-14]]

^<<v40-11-14,14>>^ and if YOU want to accept it, He himself is ‘E·liʹjah^&#42;1^ who is destined to come.’

[NOTE]
====
. Meaning “My God Is Jehovah.” J18,​22(Heb.), ʼE·li·yaʹhu. Compare 1Ki 17:1 and 2Ki 1:3 ftns, “Elijah.”
====

[[v40-11-15]]

^<<v40-11-15,15>>^ Let him that has ears listen.

[[v40-11-16]]

^<<v40-11-16,16>>^ “With whom shall I compare this generation? It is like young children sitting in the marketplaces who cry out to their playmates,

[[v40-11-17]]

^<<v40-11-17,17>>^ saying, ‘We played the flute for YOU, but YOU did not dance; we wailed, but YOU did not beat yourselves in grief.’

[[v40-11-18]]

^<<v40-11-18,18>>^ Correspondingly, John came neither eating nor drinking, yet people say, ‘He has a demon’;

[[v40-11-19]]

^<<v40-11-19,19>>^ the Son of man did come eating and drinking, still people say, ‘Look! A man gluttonous and given to drinking wine, a friend of tax collectors and sinners.’ All the same, wisdom is proved righteous by its works.”

[[v40-11-20]]

^<<v40-11-20,20>>^ Then he started to reproach the cities in which most of his powerful works had taken place, because they did not repent:

[[v40-11-21]]

^<<v40-11-21,21>>^ “Woe to you, Cho·raʹzin! Woe to you, Beth·saʹi·da! because if the powerful works had taken place in Tyre and Siʹdon that took place in YOU, they would long ago have repented in sackcloth and ashes.

[[v40-11-22]]

^<<v40-11-22,22>>^ Consequently I say to YOU, It will be more endurable for Tyre and Siʹdon on Judgment Day than for YOU.

[[v40-11-23]]

^<<v40-11-23,23>>^ And you, Ca·perʹna·um, will you perhaps be exalted to heaven?^&#42;1^ Down to Haʹdes^&#42;2^ you will come; because if the powerful works that took place in you had taken place in Sodʹom, it would have remained until this very day.

[NOTE]
====
. Or, “will you not be exalted to heaven?”
. “Hades.” Gr., ᾅδου (haiʹdou); J7-14,​16-18,​22(Heb.), שאול (sheʼohlʹ). See App 4B.
====

[[v40-11-24]]

^<<v40-11-24,24>>^ Consequently I say to YOU people, It will be more endurable for the land of Sodʹom on Judgment Day than for you.”^&#42;1^

[NOTE]
====
. “For you,” sing., referring to “you” as a city.
====

[[v40-11-25]]

^<<v40-11-25,25>>^ At that time Jesus said in response: “I publicly praise you, Father, Lord of heaven and earth, because you have hidden these things from the wise and intellectual ones and have revealed them to babes.

[[v40-11-26]]

^<<v40-11-26,26>>^ Yes, O Father, because to do thus came to be the way approved by you.

[[v40-11-27]]

^<<v40-11-27,27>>^ All things have been delivered to me by my Father, and no one fully knows the Son but the Father, neither does anyone fully know the Father but the Son and anyone to whom the Son is willing to reveal him.

[[v40-11-28]]

^<<v40-11-28,28>>^ Come to me, all YOU who are toiling and loaded down, and I will refresh YOU.

[[v40-11-29]]

^<<v40-11-29,29>>^ Take my yoke upon YOU^&#42;1^ and learn from me,^&#42;2^ for I am mild-tempered and lowly in heart, and YOU will find refreshment for YOUR souls.^&#42;3^

[NOTE]
====
. Or, “Get under my yoke with me.”
. Or, “become my disciples.” Compare Jg 7:17.
. Or, “lives.” See App 4A.
====

[[v40-11-30]]

^<<v40-11-30,30>>^ For my yoke is kindly and my load is light.”

'''

xref:040-matthew/040-matthew-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-matthew/040-matthew-012.adoc#v40-12-0[Próximo Capítulo &#62;]