include::./index.adoc[]

[[v40-5-0]]
=== According to Matthew, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-5-1]]

^<<v40-5-1,1>>^ When he saw the crowds he went up into the mountain; and after he sat down his disciples came to him;

[[v40-5-2]]

^<<v40-5-2,2>>^ and he opened his mouth and began teaching them, saying:

[[v40-5-3]]

^<<v40-5-3,3>>^ “Happy^&#42;1^ are those conscious of their spiritual need,^&#42;2^ since the kingdom of the heavens belongs to them.

[NOTE]
====
. “Happy.” Gr., Ma·kaʹri·oi; Lat., be·aʹti, the basis for the term “beatitudes.”
. Or, “those who are beggars for the spirit.”
====

[[v40-5-4]]

^<<v40-5-4,4>>^ “Happy are those who mourn, since they will be comforted.

[[v40-5-5]]

^<<v40-5-5,5>>^ “Happy are the mild-tempered ones, since they will inherit the earth.

[[v40-5-6]]

^<<v40-5-6,6>>^ “Happy are those hungering and thirsting for righteousness, since they will be filled.

[[v40-5-7]]

^<<v40-5-7,7>>^ “Happy are the merciful, since they will be shown mercy.

[[v40-5-8]]

^<<v40-5-8,8>>^ “Happy are the pure in heart, since they will see God.

[[v40-5-9]]

^<<v40-5-9,9>>^ “Happy are the peaceable,^&#42;1^ since they will be called ‘sons of God.’

[NOTE]
====
. Lit., “peacemakers.” Gr., ei·re·no·poi·oiʹ.
====

[[v40-5-10]]

^<<v40-5-10,10>>^ “Happy are those who have been persecuted for righteousness’ sake, since the kingdom of the heavens belongs to them.

[[v40-5-11]]

^<<v40-5-11,11>>^ “Happy are YOU when people reproach YOU and persecute YOU and lyingly say every sort of wicked thing against YOU for my sake.

[[v40-5-12]]

^<<v40-5-12,12>>^ Rejoice and leap for joy, since YOUR reward is great in the heavens; for in that way they persecuted the prophets prior to YOU.

[[v40-5-13]]

^<<v40-5-13,13>>^ “YOU are the salt of the earth; but if the salt loses its strength, how will its saltness be restored? It is no longer usable for anything but to be thrown outside to be trampled on by men.

[[v40-5-14]]

^<<v40-5-14,14>>^ “YOU are the light of the world. A city cannot be hid when situated upon a mountain.

[[v40-5-15]]

^<<v40-5-15,15>>^ People light a lamp and set it, not under the measuring basket, but upon the lampstand, and it shines upon all those in the house.

[[v40-5-16]]

^<<v40-5-16,16>>^ Likewise let YOUR light shine before men, that they may see YOUR fine works and give glory to YOUR Father who is in the heavens.

[[v40-5-17]]

^<<v40-5-17,17>>^ “Do not think I came to destroy the Law or the Prophets. I came, not to destroy, but to fulfill;

[[v40-5-18]]

^<<v40-5-18,18>>^ for truly I say to YOU that sooner would heaven and earth pass away than for one smallest letter or one particle of a letter to pass away from the Law by any means and not all things take place.

[[v40-5-19]]

^<<v40-5-19,19>>^ Whoever, therefore, breaks one of these least commandments and teaches mankind to that effect, he will be called ‘least’ in relation to the kingdom of the heavens. As for anyone who does them and teaches them, this one will be called ‘great’ in relation to the kingdom of the heavens.

[[v40-5-20]]

^<<v40-5-20,20>>^ For I say to YOU that if YOUR righteousness does not abound more than that of the scribes and Pharisees, YOU will by no means enter into the kingdom of the heavens.

[[v40-5-21]]

^<<v40-5-21,21>>^ “YOU heard that it was said to those of ancient times, ‘You must not murder; but whoever commits a murder will be accountable to the court of justice.’

[[v40-5-22]]

^<<v40-5-22,22>>^ However, I say to YOU that everyone who continues wrathful with his brother will be accountable to the court of justice; but whoever addresses his brother with an unspeakable word of contempt^&#42;1^ will be accountable to the Supreme Court;^&#42;2^ whereas whoever says, ‘You despicable fool!’ will be liable to the fiery Ge·henʹna.^&#42;3^

[NOTE]
====
. “An unspeakable word of contempt.” Gr., Rha·kaʹ; J17, Re·qaʼʹ, an Aram. word of contempt.
. Or, “the Sanhedrin.”
. “Gehenna.” Gr., γέενναν (geʹen·nan); J1-14,​16-18(Heb.), גיהנם (geh·hin·nomʹ, “valley of Hinnom”). The place for burning refuse outside of Jerusalem. See App 4C.
====

[[v40-5-23]]

^<<v40-5-23,23>>^ “If, then, you are bringing your gift to the altar and you there remember that your brother has something against you,

[[v40-5-24]]

^<<v40-5-24,24>>^ leave your gift there in front of the altar, and go away; first make your peace with your brother, and then, when you have come back, offer up your gift.

[[v40-5-25]]

^<<v40-5-25,25>>^ “Be about settling matters quickly with the one complaining against you at law, while you are with him on the way there, that somehow the complainant may not turn you over to the judge, and the judge to the court attendant, and you get thrown into prison.

[[v40-5-26]]

^<<v40-5-26,26>>^ I say to you for a fact, You will certainly not come out from there until you have paid over the last coin of very little value.^&#42;1^

[NOTE]
====
. Lit., “the last quadrans”; one sixty-fourth of a denarius. See App 8A.
====

[[v40-5-27]]

^<<v40-5-27,27>>^ “YOU heard that it was said, ‘You must not commit adultery.’

[[v40-5-28]]

^<<v40-5-28,28>>^ But I say to YOU that everyone that keeps on looking at a woman so as to have a passion for her has already committed adultery with her in his heart.

[[v40-5-29]]

^<<v40-5-29,29>>^ If, now, that right eye of yours is making you stumble, tear it out and throw it away from you. For it is more beneficial to you for one of your members to be lost to you than for your whole body to be pitched into Ge·henʹna.

[[v40-5-30]]

^<<v40-5-30,30>>^ Also, if your right hand is making you stumble, cut it off and throw it away from you. For it is more beneficial to you for one of your members to be lost than for your whole body to land in Ge·henʹna.

[[v40-5-31]]

^<<v40-5-31,31>>^ “Moreover it was said, ‘Whoever divorces his wife, let him give her a certificate of divorce.’

[[v40-5-32]]

^<<v40-5-32,32>>^ However, I say to YOU that everyone divorcing his wife, except on account of fornication,^&#42;1^ makes her a subject for adultery, and whoever marries a divorced^&#42;2^ woman commits adultery.^&#42;3^

[NOTE]
====
. “Fornication.” Gr., por·neiʹas; Lat., for·ni·ca·ti·oʹnis; J17,​18,​22(Heb.), zenuthʹ. See App 5A.
. Or, “loosed off.”
. Or, “commits marital sexual unfaithfulness.” Gr., moi·khaʹtai; Lat., a·dulʹte·rat; J22(Heb.), noh·ʼephʹ. See Eze 16:32 ftn.
====

[[v40-5-33]]

^<<v40-5-33,33>>^ “Again YOU heard that it was said to those of ancient times, ‘You must not swear without performing, but you must pay your vows to Jehovah.’^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v40-5-34]]

^<<v40-5-34,34>>^ However, I say to YOU: Do not swear at all, neither by heaven, because it is God’s throne;

[[v40-5-35]]

^<<v40-5-35,35>>^ nor by earth, because it is the footstool of his feet; nor by Jerusalem, because it is the city of the great King.

[[v40-5-36]]

^<<v40-5-36,36>>^ Nor by your head must you swear, because you cannot turn one hair white or black.

[[v40-5-37]]

^<<v40-5-37,37>>^ Just let YOUR word Yes mean Yes, YOUR No, No; for what is in excess of these is from the wicked one.^&#42;1^

[NOTE]
====
. Or, “from what is wicked.”
====

[[v40-5-38]]

^<<v40-5-38,38>>^ “YOU heard that it was said, ‘Eye for eye and tooth for tooth.’

[[v40-5-39]]

^<<v40-5-39,39>>^ However, I say to YOU: Do not resist him that is wicked;^&#42;1^ but whoever slaps you on your right cheek, turn the other also to him.

[NOTE]
====
. Or, “what is wicked.”
====

[[v40-5-40]]

^<<v40-5-40,40>>^ And if a person wants to go to court with you and get possession of your inner garment, let your outer garment also go to him;

[[v40-5-41]]

^<<v40-5-41,41>>^ and if someone under authority impresses you into service for a mile,^&#42;1^ go with him two miles.

[NOTE]
====
. “Mile.” Gr., miʹli·on; Lat., milʹle. A Roman mile of 1,479.5 m (4,854 English ft). Compare Lu 24:13 ftn; see App 8A.
====

[[v40-5-42]]

^<<v40-5-42,42>>^ Give to the one asking you, and do not turn away from one that wants to borrow from you &#91;without interest&#93;.

[[v40-5-43]]

^<<v40-5-43,43>>^ “YOU heard that it was said, ‘You must love your neighbor and hate your enemy.’

[[v40-5-44]]

^<<v40-5-44,44>>^ However, I say to YOU: Continue to love YOUR enemies and to pray for those persecuting YOU;

[[v40-5-45]]

^<<v40-5-45,45>>^ that YOU may prove yourselves sons of YOUR Father who is in the heavens, since he makes his sun rise upon wicked people and good and makes it rain upon righteous people and unrighteous.

[[v40-5-46]]

^<<v40-5-46,46>>^ For if YOU love those loving YOU, what reward do YOU have? Are not also the tax collectors doing the same thing?

[[v40-5-47]]

^<<v40-5-47,47>>^ And if YOU greet YOUR brothers only, what extraordinary thing are YOU doing? Are not also the people of the nations doing the same thing?

[[v40-5-48]]

^<<v40-5-48,48>>^ YOU must accordingly be perfect, as YOUR heavenly Father is perfect.^&#42;1^

[NOTE]
====
. Or, “complete.”
====

'''

xref:040-matthew/040-matthew-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-matthew/040-matthew-006.adoc#v40-6-0[Próximo Capítulo &#62;]