include::./index.adoc[]

[[v40-8-0]]
=== According to Matthew, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-8-1]]

^<<v40-8-1,1>>^ After he had come down from the mountain great crowds followed him.

[[v40-8-2]]

^<<v40-8-2,2>>^ And, look! a leprous man came up and began doing obeisance to him, saying: “Lord, if you just want to, you can make me clean.”

[[v40-8-3]]

^<<v40-8-3,3>>^ And so, stretching out &#91;his&#93; hand, he touched him, saying: “I want to. Be made clean.” And immediately his leprosy was cleansed away.

[[v40-8-4]]

^<<v40-8-4,4>>^ Then Jesus said to him: “See that you tell no one, but go, show yourself to the priest, and offer the gift that Moses appointed, for the purpose of a witness to them.”

[[v40-8-5]]

^<<v40-8-5,5>>^ When he entered into Ca·perʹna·um, an army officer^&#42;1^ came to him, entreating him

[NOTE]
====
. Or, “centurion,” that is, one in command of 100 soldiers. Lat., cen·tuʹri·o.
====

[[v40-8-6]]

^<<v40-8-6,6>>^ and saying: “Sir, my manservant is laid up in the house with paralysis, being terribly tormented.”

[[v40-8-7]]

^<<v40-8-7,7>>^ He said to him: “When I get there I will cure him.”

[[v40-8-8]]

^<<v40-8-8,8>>^ In reply the army officer said: “Sir, I am not a fit man for you to enter under my roof, but just say the word and my manservant will be healed.

[[v40-8-9]]

^<<v40-8-9,9>>^ For I too am a man placed under authority, having soldiers under me, and I say to this one, ‘Be on your way!’ and he is on his way, and to another, ‘Come!’ and he comes, and to my slave, ‘Do this!’ and he does it.”

[[v40-8-10]]

^<<v40-8-10,10>>^ Hearing that, Jesus became amazed and said to those following him: “I tell YOU the truth, With no one in Israel have I found so great a faith.

[[v40-8-11]]

^<<v40-8-11,11>>^ But I tell YOU that many from eastern parts and western parts will come and recline at the table with Abraham and Isaac and Jacob in the kingdom of the heavens;

[[v40-8-12]]

^<<v40-8-12,12>>^ whereas the sons of the kingdom will be thrown into the darkness outside. There is where &#91;their&#93; weeping and the gnashing^&#42;1^ of &#91;their&#93; teeth will be.”

[NOTE]
====
. Or, “grinding; clenching.”
====

[[v40-8-13]]

^<<v40-8-13,13>>^ Then Jesus said to the army officer: “Go. Just as it has been your faith, so let it come to pass for you.” And the manservant was healed in that hour.

[[v40-8-14]]

^<<v40-8-14,14>>^ And Jesus, on coming into Peter’s house, saw his mother-in-law lying down and sick with fever.

[[v40-8-15]]

^<<v40-8-15,15>>^ So he touched her hand, and the fever left her, and she got up and began ministering to him.

[[v40-8-16]]

^<<v40-8-16,16>>^ But after it became evening,^&#42;1^ people brought him many demon-possessed persons; and he expelled the spirits with a word, and he cured all who were faring badly;

[NOTE]
====
. That is, after the sabbath day. See Mr 1:21-32; Lu 4:31-40.
====

[[v40-8-17]]

^<<v40-8-17,17>>^ that there might be fulfilled what was spoken through Isaiah the prophet, saying: “He himself took our sicknesses and carried our diseases.”

[[v40-8-18]]

^<<v40-8-18,18>>^ When Jesus saw a crowd around him, he gave the command to shove off for the other side.

[[v40-8-19]]

^<<v40-8-19,19>>^ And a certain scribe came up and said to him: “Teacher, I will follow you wherever you are about to go.”

[[v40-8-20]]

^<<v40-8-20,20>>^ But Jesus said to him: “Foxes have dens and birds of heaven have roosts, but the Son of man^&#42;1^ has nowhere to lay down his head.”

[NOTE]
====
. Lit., “the Son of the man.”
====

[[v40-8-21]]

^<<v40-8-21,21>>^ Then another of the disciples said to him: “Lord, permit me first to leave and bury my father.”

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus said to him: “Keep following me, and let the dead bury their dead.”

[[v40-8-23]]

^<<v40-8-23,23>>^ And when he got aboard a boat, his disciples followed him.

[[v40-8-24]]

^<<v40-8-24,24>>^ Now, look! a great agitation arose in the sea, so that the boat was being covered by the waves; he, however, was sleeping.

[[v40-8-25]]

^<<v40-8-25,25>>^ And they came and woke him up, saying: “Lord, save us, we are about to perish!”

[[v40-8-26]]

^<<v40-8-26,26>>^ But he said to them: “Why are YOU fainthearted, YOU with little faith?” Then, getting up, he rebuked the winds and the sea, and a great calm set in.

[[v40-8-27]]

^<<v40-8-27,27>>^ So the men became amazed and said: “What sort of person is this, that even the winds and the sea obey him?”

[[v40-8-28]]

^<<v40-8-28,28>>^ When he got to the other side, into the country of the Gad·a·renesʹ,^&#42;1^ there met him two demon-possessed men coming out from among^&#42;2^ the memorial tombs, unusually fierce, so that nobody had the courage to pass by on that road.

[NOTE]
====
. “The country of the Gerasenes” in Mr 5:1; Lu 8:26.
. Or, “coming out of.”
====

[[v40-8-29]]

^<<v40-8-29,29>>^ And, look! they screamed, saying: “What have we to do with you,^&#42;1^ Son of God? Did you come here to torment us before the appointed time?”

[NOTE]
====
. “What have we to do with you?” An idiom; a repellent question indicating objection. See App 7B.
====

[[v40-8-30]]

^<<v40-8-30,30>>^ But a long way off from them a herd of many swine was at pasture.

[[v40-8-31]]

^<<v40-8-31,31>>^ So the demons began to entreat him, saying: “If you expel us, send us forth into the herd of swine.”

[[v40-8-32]]

^<<v40-8-32,32>>^ Accordingly he said to them: “Go!” They came out and went off into the swine; and, look! the entire herd rushed over the precipice into the sea and died in the waters.

[[v40-8-33]]

^<<v40-8-33,33>>^ But the herders fled and, going into the city, they reported everything, including the affair of the demon-possessed men.

[[v40-8-34]]

^<<v40-8-34,34>>^ And, look! all the city turned out to meet Jesus; and after having seen him, they earnestly urged him to move out from their districts.

'''

xref:040-matthew/040-matthew-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-matthew/040-matthew-009.adoc#v40-9-0[Próximo Capítulo &#62;]