include::./index.adoc[]

[[v40-4-0]]
=== According to Matthew, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-4-1]]

^<<v40-4-1,1>>^ Then Jesus was led by the spirit up into the wilderness to be tempted by the Devil.

[[v40-4-2]]

^<<v40-4-2,2>>^ After he had fasted forty days and forty nights, then he felt hungry.

[[v40-4-3]]

^<<v40-4-3,3>>^ Also, the Tempter came and said to him: “If you are a son of God, tell these stones to become loaves of bread.”

[[v40-4-4]]

^<<v40-4-4,4>>^ But in reply he said: “It is written, ‘Man must live, not on bread alone, but on every utterance coming forth through Jehovah’s^&#42;1^ mouth.’”

[NOTE]
====
. See App 1D.
====

[[v40-4-5]]

^<<v40-4-5,5>>^ Then the Devil took him along into the holy city, and he stationed him upon the battlement of the temple

[[v40-4-6]]

^<<v40-4-6,6>>^ and said to him: “If you are a son of God, hurl yourself down; for it is written, ‘He will give his angels a charge concerning you, and they will carry you on their hands, that you may at no time strike your foot against a stone.’”

[[v40-4-7]]

^<<v40-4-7,7>>^ Jesus said to him: “Again it is written, ‘You must not put Jehovah^&#42;1^ your God to the test.’”

[NOTE]
====
. See App 1D.
====

[[v40-4-8]]

^<<v40-4-8,8>>^ Again the Devil took him along to an unusually high mountain, and showed him all the kingdoms of the world^&#42;1^ and their glory,

[NOTE]
====
. “World.” Gr., κόσμου (koʹsmou); Lat., munʹdi.
====

[[v40-4-9]]

^<<v40-4-9,9>>^ and he said to him: “All these things I will give you if you fall down and do an act of worship to me.”

[[v40-4-10]]

^<<v40-4-10,10>>^ Then Jesus said to him: “Go away, Satan! For it is written, ‘It is Jehovah^&#42;1^ your God you must worship, and it is to him alone you must render sacred service.’”^&#42;2^

[NOTE]
====
. See App 1D.
. “You must render sacred service.” Gr., la·treuʹseis; J17,​18,​22(Heb.), ta·ʽavodhʹ, “you must serve (worship).” See Ex 3:12 ftn.
====

[[v40-4-11]]

^<<v40-4-11,11>>^ Then the Devil left him, and, look! angels came and began to minister to him.

[[v40-4-12]]

^<<v40-4-12,12>>^ Now when he heard that John had been arrested, he withdrew into Galʹi·lee.

[[v40-4-13]]

^<<v40-4-13,13>>^ Further, after leaving Nazʹa·reth, he came and took up residence in Ca·perʹna·um beside the sea in the districts of Zebʹu·lun and Naphʹta·li,

[[v40-4-14]]

^<<v40-4-14,14>>^ that there might be fulfilled what was spoken through Isaiah the prophet, saying:

[[v40-4-15]]

^<<v40-4-15,15>>^ “O land of Zebʹu·lun and land of Naphʹta·li, along the road of the sea, on the other side of the Jordan, Galʹi·lee of the nations!

[[v40-4-16]]

^<<v40-4-16,16>>^ the people sitting in darkness saw a great light, and as for those sitting in a region of deathly shadow, light rose upon them.”

[[v40-4-17]]

^<<v40-4-17,17>>^ From that time on Jesus commenced preaching and saying: “Repent, YOU people, for the kingdom of the heavens has drawn near.”

[[v40-4-18]]

^<<v40-4-18,18>>^ Walking alongside the sea of Galʹi·lee he saw two brothers, Simon who is called Peter and Andrew his brother, letting down a fishing net into the sea, for they were fishers.

[[v40-4-19]]

^<<v40-4-19,19>>^ And he said to them: “Come after me, and I will make YOU fishers of men.”

[[v40-4-20]]

^<<v40-4-20,20>>^ At once abandoning the nets, they followed him.

[[v40-4-21]]

^<<v40-4-21,21>>^ Going on also from there he saw two others &#91;who were&#93; brothers, James &#91;the son&#93; of Zebʹe·dee and John his brother, in the boat with Zebʹe·dee their father, mending their nets, and he called them.

[[v40-4-22]]

^<<v40-4-22,22>>^ At once leaving the boat and their father, they followed him.

[[v40-4-23]]

^<<v40-4-23,23>>^ Then he went around throughout the whole of Galʹi·lee, teaching in their synagogues and preaching the good news^&#42;1^ of the kingdom and curing every sort of disease and every sort of infirmity among the people.

[NOTE]
====
. Or, “evangel; gospel.” Gr., eu·ag·geʹli·on; Lat., e·van·geʹli·um.
====

[[v40-4-24]]

^<<v40-4-24,24>>^ And the report about him went out into all Syria; and they brought him all those faring badly, distressed with various diseases and torments, demon-possessed and epileptic and paralyzed persons, and he cured them.

[[v40-4-25]]

^<<v40-4-25,25>>^ Consequently great crowds followed him from Galʹi·lee and De·capʹo·lis^&#42;1^ and Jerusalem and Ju·deʹa and from the other side of the Jordan.

[NOTE]
====
. Or, “The [league of] Ten Cities.”
====

'''

xref:040-matthew/040-matthew-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-matthew/040-matthew-005.adoc#v40-5-0[Próximo Capítulo &#62;]