include::./index.adoc[]

[[v40-24-0]]
=== According to Matthew, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-24-1]]

^<<v40-24-1,1>>^ Departing now, Jesus was on his way from the temple, but his disciples approached to show him the buildings of the temple.

[[v40-24-2]]

^<<v40-24-2,2>>^ In response he said to them: “Do YOU not behold all these things? Truly I say to YOU, By no means will a stone be left here upon a stone and not be thrown down.”

[[v40-24-3]]

^<<v40-24-3,3>>^ While he was sitting upon the Mount of Olives, the disciples approached him privately, saying: “Tell us, When will these things be, and what will be the sign of your presence^&#42;1^ and of the conclusion^&#42;2^ of the system of things?”^&#42;3^

[NOTE]
====
. Gr., pa·rou·siʹas. See App 5B.
. Or, “joint end; combination end; ending together.” Gr., syn·te·leiʹas; Lat., con·sum·ma·ti·oʹnis.
. Or, “of the order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J1-14,​16-18,​22(Heb.), ha·ʽoh·lamʹ.
====

[[v40-24-4]]

^<<v40-24-4,4>>^ And in answer Jesus said to them: “Look out that nobody misleads YOU;

[[v40-24-5]]

^<<v40-24-5,5>>^ for many will come on the basis of my name, saying, ‘I am the Christ,’^&#42;1^ and will mislead many.

[NOTE]
====
. “The Christ.” Gr., ho Khri·stosʹ; Lat., Chriʹstus; J17,​18,​22(Heb.), ham·Ma·shiʹach.
====

[[v40-24-6]]

^<<v40-24-6,6>>^ YOU are going to hear of wars and reports of wars; see that YOU are not terrified. For these things must take place, but the end^&#42;1^ is not yet.

[NOTE]
====
. Or, “accomplished end; completed end.”
====

[[v40-24-7]]

^<<v40-24-7,7>>^ “For nation will rise^&#42;1^ against nation and kingdom against kingdom, and there will be food shortages and earthquakes in one place after another.

[NOTE]
====
. Or, “be stirred up; be roused up.”
====

[[v40-24-8]]

^<<v40-24-8,8>>^ All these things are a beginning of pangs of distress.

[[v40-24-9]]

^<<v40-24-9,9>>^ “Then people will deliver YOU up to tribulation and will kill YOU, and YOU will be objects of hatred by all the nations on account of my name.

[[v40-24-10]]

^<<v40-24-10,10>>^ Then, also, many will be stumbled and will betray one another and will hate one another.

[[v40-24-11]]

^<<v40-24-11,11>>^ And many false prophets will arise and mislead many;

[[v40-24-12]]

^<<v40-24-12,12>>^ and because of the increasing of lawlessness the love of the greater number will cool off.

[[v40-24-13]]

^<<v40-24-13,13>>^ But he that has endured to the end^&#42;1^ is the one that will be saved.

[NOTE]
====
. See vs 14 ftn, “End.”
====

[[v40-24-14]]

^<<v40-24-14,14>>^ And this good news of the kingdom will be preached^&#42;1^ in all the inhabited earth^&#42;2^ for a witness^&#42;3^ to all the nations; and then the end^&#42;4^ will come.

[NOTE]
====
. Or, “be heralded.” Gr., ke·ry·khtheʹse·tai; Lat., prae·di·caʹbi·tur. Compare Da 5:29 ftn, “Heralded.”
. Lit., “in all the inhabited.” Gr., en hoʹlei tei oi·kou·meʹnei, fem. sing., implying the earth; Lat., in u·ni·verʹso orʹbe, “in the universal circle,” that is, of the earth. See Isa 13:11 ftn, “Land”; Na 1:5 ftn.
. “A witness.” Gr., mar·tyʹri·on; Lat., te·sti·moʹni·um.
. Or, “accomplished end; completed end; finish.” Gr., teʹlos.
====

[[v40-24-15]]

^<<v40-24-15,15>>^ “Therefore, when YOU catch sight of the disgusting thing that causes desolation, as spoken of through Daniel the prophet, standing in a holy place,^&#42;1^ (let the reader use discernment,)^&#42;2^

[NOTE]
====
. “In a holy place.” Gr., en toʹpoi ha·giʹoi; Lat., in loʹco sancʹto; J17,​18(Heb.), bim·qohmʹ qoʹdhesh.
. Lit., “let the one reading be minding.”
====

[[v40-24-16]]

^<<v40-24-16,16>>^ then let those in Ju·deʹa begin fleeing to the mountains.

[[v40-24-17]]

^<<v40-24-17,17>>^ Let the man on the housetop not come down to take the goods out of his house;

[[v40-24-18]]

^<<v40-24-18,18>>^ and let the man in the field not return to the house to pick up his outer garment.

[[v40-24-19]]

^<<v40-24-19,19>>^ Woe to the pregnant women and those suckling a baby in those days!

[[v40-24-20]]

^<<v40-24-20,20>>^ Keep praying that YOUR flight may not occur in wintertime, nor on the sabbath day;^&#42;1^

[NOTE]
====
. See Ac 1:12 ftn.
====

[[v40-24-21]]

^<<v40-24-21,21>>^ for then there will be great tribulation^&#42;1^ such as has not occurred since the world’s beginning until now, no, nor will occur again.

[NOTE]
====
. “Great tribulation.” Gr., thliʹpsis me·gaʹle; Lat., tri·bu·laʹti·o maʹgna; J17,​18(Heb.), tsa·rahʹ ghedhoh·lahʹ.
====

[[v40-24-22]]

^<<v40-24-22,22>>^ In fact, unless those days were cut short, no flesh would be saved; but on account of the chosen ones those days will be cut short.

[[v40-24-23]]

^<<v40-24-23,23>>^ “Then if anyone says to YOU, ‘Look! Here is the Christ,’ or, ‘There!’ do not believe it.

[[v40-24-24]]

^<<v40-24-24,24>>^ For false Christs and false prophets will arise and will give great signs and wonders so as to mislead, if possible, even the chosen ones.

[[v40-24-25]]

^<<v40-24-25,25>>^ Look! I have forewarned YOU.

[[v40-24-26]]

^<<v40-24-26,26>>^ Therefore, if people say to YOU, ‘Look! He is in the wilderness,’ do not go out; ‘Look! He is in the inner chambers,’ do not believe it.

[[v40-24-27]]

^<<v40-24-27,27>>^ For just as the lightning comes out of eastern parts and shines over to western parts, so the presence^&#42;1^ of the Son of man will be.

[NOTE]
====
. See App 5B.
====

[[v40-24-28]]

^<<v40-24-28,28>>^ Wherever the carcass is, there the eagles will be gathered together.

[[v40-24-29]]

^<<v40-24-29,29>>^ “Immediately after the tribulation of those days the sun will be darkened, and the moon will not give its light, and the stars will fall from heaven, and the powers of the heavens will be shaken.

[[v40-24-30]]

^<<v40-24-30,30>>^ And then the sign of the Son of man will appear in heaven, and then all the tribes of the earth will beat themselves in lamentation, and they will see the Son of man coming^&#42;1^ on the clouds of heaven with power and great glory.^&#42;2^

[NOTE]
====
. “Coming.” Gr., er·khoʹme·non.
. Or, “with great power and glory.”
====

[[v40-24-31]]

^<<v40-24-31,31>>^ And he will send forth his angels with a great trumpet sound, and they will gather his chosen ones together from the four winds, from one extremity of the heavens to their other extremity.

[[v40-24-32]]

^<<v40-24-32,32>>^ “Now learn from the fig tree as an illustration this point: Just as soon as its young branch grows tender and it puts forth leaves, YOU know that summer is near.

[[v40-24-33]]

^<<v40-24-33,33>>^ Likewise also YOU, when YOU see all these things, know that he is near at the doors.

[[v40-24-34]]

^<<v40-24-34,34>>^ Truly I say to YOU that this generation^&#42;1^ will by no means pass away until all these things occur.

[NOTE]
====
. “Generation.” Gr., ge·ne·aʹ; different from geʹnos, “race,” as in 1Pe 2:9.
====

[[v40-24-35]]

^<<v40-24-35,35>>^ Heaven and earth will pass away, but my words will by no means pass away.

[[v40-24-36]]

^<<v40-24-36,36>>^ “Concerning that day and hour nobody knows, neither the angels of the heavens nor the Son,^&#42;1^ but only the Father.

[NOTE]
====
. “Nor the Son,” א*BDVgmssArmJ18,​21,​22.
====

[[v40-24-37]]

^<<v40-24-37,37>>^ For just as the days of Noah were, so the presence^&#42;1^ of the Son of man will be.

[NOTE]
====
. See App 5B.
====

[[v40-24-38]]

^<<v40-24-38,38>>^ For as they were in those days before the flood,^&#42;1^ eating and drinking, men marrying and women being given in marriage, until the day that Noah entered into the ark;

[NOTE]
====
. Or, “deluge; cataclysm.” Gr., ka·ta·kly·smouʹ; Lat., di·luʹvi·um.
====

[[v40-24-39]]

^<<v40-24-39,39>>^ and they took no note until the flood came and swept them all away, so the presence^&#42;1^ of the Son of man will be.

[NOTE]
====
. See App 5B.
====

[[v40-24-40]]

^<<v40-24-40,40>>^ Then two men will be in the field: one will be taken along and the other be abandoned;

[[v40-24-41]]

^<<v40-24-41,41>>^ two women will be grinding at the hand mill: one will be taken along and the other be abandoned.

[[v40-24-42]]

^<<v40-24-42,42>>^ Keep on the watch, therefore, because YOU do not know on what day YOUR Lord is coming.

[[v40-24-43]]

^<<v40-24-43,43>>^ “But know one thing, that if the householder had known in what watch the thief was coming, he would have kept awake and not allowed his house to be broken into.

[[v40-24-44]]

^<<v40-24-44,44>>^ On this account YOU too prove yourselves ready, because at an hour that YOU do not think to be it, the Son of man is coming.

[[v40-24-45]]

^<<v40-24-45,45>>^ “Who really is the faithful and discreet slave whom his master appointed over his domestics, to give them their food at the proper time?

[[v40-24-46]]

^<<v40-24-46,46>>^ Happy is that slave if his master on arriving^&#42;1^ finds him doing so.

[NOTE]
====
. Lit., “having come.” Gr., el·thonʹ.
====

[[v40-24-47]]

^<<v40-24-47,47>>^ Truly I say to YOU, He will appoint him over all his belongings.

[[v40-24-48]]

^<<v40-24-48,48>>^ “But if ever that evil slave should say in his heart, ‘My master is delaying,’

[[v40-24-49]]

^<<v40-24-49,49>>^ and should start to beat his fellow slaves and should eat and drink with the confirmed drunkards,

[[v40-24-50]]

^<<v40-24-50,50>>^ the master of that slave will come on a day that he does not expect and in an hour that he does not know,

[[v40-24-51]]

^<<v40-24-51,51>>^ and will punish him with the greatest severity^&#42;1^ and will assign him his part with the hypocrites. There is where &#91;his&#93;^&#42;2^ weeping and the gnashing^&#42;3^ of &#91;his&#93;^&#42;4^ teeth will be.

[NOTE]
====
. Or, “will cut him in two.”
. Or, “their.”
. Or, “grinding; clenching.”
. Or, “their.”
====

'''

xref:040-matthew/040-matthew-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-matthew/040-matthew-025.adoc#v40-25-0[Próximo Capítulo &#62;]