include::./index.adoc[]

[[v40-16-0]]
=== According to Matthew, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-16-1]]

^<<v40-16-1,1>>^ Here the Pharisees and Sadducees approached him and, to tempt him, they asked him to display to them a sign from heaven.

[[v40-16-2]]

^<<v40-16-2,2>>^ In reply he said to them: “&#91;&#91;When evening falls YOU are accustomed to say, ‘It will be fair weather, for the sky is fire-red’;

[[v40-16-3]]

^<<v40-16-3,3>>^ and at morning, ‘It will be wintry, rainy weather today, for the sky is fire-red, but gloomy-looking.’ YOU know how to interpret the appearance of the sky, but the signs of the times YOU cannot interpret.&#93;&#93;^&#42;1^

[NOTE]
====
. According to CDWItVg; אBSyc,sArm omit the words in double brackets.
====

[[v40-16-4]]

^<<v40-16-4,4>>^ A wicked and adulterous^&#42;1^ generation keeps on seeking for a sign, but no sign will be given it except the sign of Joʹnah.” With that he went away, leaving them behind.

[NOTE]
====
. “Adulterous.” Gr., moi·kha·lisʹ; Lat., a·dulʹte·ra.
====

[[v40-16-5]]

^<<v40-16-5,5>>^ Now the disciples crossed to the other side and forgot to take loaves along.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus said to them: “Keep YOUR eyes open and watch out for the leaven of the Pharisees and Sadducees.”

[[v40-16-7]]

^<<v40-16-7,7>>^ So they began to reason among themselves, saying: “We did not take any loaves along.”

[[v40-16-8]]

^<<v40-16-8,8>>^ Knowing this, Jesus said: “Why are YOU doing this reasoning among yourselves, because YOU have no loaves, YOU with little faith?

[[v40-16-9]]

^<<v40-16-9,9>>^ Do YOU not yet see the point, or do YOU not remember the five loaves in the case of the five thousand and how many baskets YOU took up?

[[v40-16-10]]

^<<v40-16-10,10>>^ Or the seven loaves in the case of the four thousand and how many provision baskets YOU took up?

[[v40-16-11]]

^<<v40-16-11,11>>^ How is it YOU do not discern that I did not talk to YOU about loaves? But watch out for the leaven of the Pharisees and Sadducees.”

[[v40-16-12]]

^<<v40-16-12,12>>^ Then they grasped that he said to watch out, not for the leaven of the loaves, but for the teaching of the Pharisees and Sadducees.

[[v40-16-13]]

^<<v40-16-13,13>>^ Now when he had come into the parts of Caes·a·reʹa Phi·lipʹpi, Jesus went asking his disciples: “Who are men saying the Son of man is?”

[[v40-16-14]]

^<<v40-16-14,14>>^ They said: “Some say John the Baptist, others E·liʹjah, still others Jeremiah or one of the prophets.”

[[v40-16-15]]

^<<v40-16-15,15>>^ He said to them: “YOU, though, who do YOU say I am?”

[[v40-16-16]]

^<<v40-16-16,16>>^ In answer Simon Peter said: “You are the Christ, the Son of the living God.”

[[v40-16-17]]

^<<v40-16-17,17>>^ In response Jesus said to him: “Happy you are, Simon son of Joʹnah,^&#42;1^ because flesh and blood did not reveal &#91;it&#93; to you, but my Father who is in the heavens did.

[NOTE]
====
. Lit., “Bar-jonah,” meaning “Son of Jonah.” Gr., Ba·ri·o·naʹ; J17,​18,​22(Heb.), Bar-Yoh·nahʹ. Bar is the Aram. loanword for “son.” Compare Ezr 5:2 ftn.
====

[[v40-16-18]]

^<<v40-16-18,18>>^ Also, I say to you, You are Peter, and on this rock-mass^&#42;1^ I will build my congregation,^&#42;2^ and the gates of Haʹdes^&#42;3^ will not overpower it.

[NOTE]
====
. “You are Peter, and on this rock-mass.” In the original languages the words for “Peter,” meaning “A Piece of Rock,” are masc. (Gr., Peʹtros, masc.; Lat., Peʹtrus, masc.; Syr., Kiʼ·phaʼ, preceded by the masc. personal pronoun hu); whereas the words for “rock-mass” are fem. (Gr., peʹtrai, dative, fem. sing.; Lat., peʹtram, fem.; Syr., kiʼ·phaʼ, preceded by the fem. demonstrative adjective ha·deʼ).
. Or, “my ecclesia (assembly).” Gr., mou ten ek·kle·siʹan; J17,​18,​22(Heb.), qehil·la·thiʹ.
. “Hades.” Gr., haiʹdou; J7,​8,​10-14,​16-18,​22(Heb.), sheʼohlʹ. See App 4B.
====

[[v40-16-19]]

^<<v40-16-19,19>>^ I will give you the keys of the kingdom of the heavens, and whatever you may bind on earth will be the thing bound^&#42;1^ in the heavens, and whatever you may loose on earth will be the thing loosed^&#42;2^ in the heavens.”

[NOTE]
====
. Or, “the thing already bound,” the perfect passive participle.
. Or, “the thing already loosed,” the perfect passive participle.
====

[[v40-16-20]]

^<<v40-16-20,20>>^ Then he sternly charged the disciples not to say to anybody that he was the Christ.

[[v40-16-21]]

^<<v40-16-21,21>>^ From that time forward Jesus Christ commenced showing his disciples that he must go to Jerusalem and suffer many things from the older men and chief priests and scribes, and be killed, and on the third day be raised up.

[[v40-16-22]]

^<<v40-16-22,22>>^ At this Peter took him aside and commenced rebuking him, saying: “Be kind to yourself, Lord; you will not have this &#91;destiny&#93; at all.”

[[v40-16-23]]

^<<v40-16-23,23>>^ But, turning his back,^&#42;1^ he said to Peter: “Get behind me, Satan! You are a stumbling block to me, because you think, not God’s thoughts, but those of men.”^&#42;2^

[NOTE]
====
. Or, “turning around.”
. Or, “you have, not God’s mind, but that of men.”
====

[[v40-16-24]]

^<<v40-16-24,24>>^ Then Jesus said to his disciples: “If anyone wants to come after me, let him disown himself and pick up his torture stake^&#42;1^ and continually follow me.

[NOTE]
====
. See App 5C.
====

[[v40-16-25]]

^<<v40-16-25,25>>^ For whoever wants to save his soul^&#42;1^ will lose it; but whoever loses his soul for my sake will find it.

[NOTE]
====
. Or, “life.” See App 4A.
====

[[v40-16-26]]

^<<v40-16-26,26>>^ For what benefit will it be to a man if he gains the whole world but forfeits his soul? or what will a man give in exchange for his soul?

[[v40-16-27]]

^<<v40-16-27,27>>^ For the Son of man is destined to come in the glory of his Father with his angels, and then he will recompense each one according to his behavior.

[[v40-16-28]]

^<<v40-16-28,28>>^ Truly I say to YOU that there are some of those standing here that will not taste death at all until first they see the Son of man coming in his kingdom.”

'''

xref:040-matthew/040-matthew-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-matthew/040-matthew-017.adoc#v40-17-0[Próximo Capítulo &#62;]