include::./index.adoc[]

[[v40-21-0]]
=== According to Matthew, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-21-1]]

^<<v40-21-1,1>>^ Well, when they got close to Jerusalem and arrived at Bethʹpha·ge on the Mount of Olives, then Jesus sent forth two disciples,

[[v40-21-2]]

^<<v40-21-2,2>>^ saying to them: “Be on YOUR way into the village that is within sight of YOU, and YOU will at once find an ass tied, and a colt with her; untie them and bring them to me.

[[v40-21-3]]

^<<v40-21-3,3>>^ And if someone says anything to YOU, YOU must say, ‘The Lord needs them.’ At that he will immediately send them forth.”

[[v40-21-4]]

^<<v40-21-4,4>>^ This actually took place that there might be fulfilled what was spoken through the prophet, saying:

[[v40-21-5]]

^<<v40-21-5,5>>^ “TELL the daughter of Zion, ‘Look! Your King is coming to you, mild-tempered, and mounted upon an ass, yes, upon a colt, the offspring of a beast of burden.’”

[[v40-21-6]]

^<<v40-21-6,6>>^ So the disciples got on their way and did just as Jesus ordered them.

[[v40-21-7]]

^<<v40-21-7,7>>^ And they brought the ass and its colt, and they put upon these their outer garments, and he seated himself upon them.

[[v40-21-8]]

^<<v40-21-8,8>>^ Most of the crowd spread their outer garments on the road, while others began cutting down branches from the trees and spreading them on the road.

[[v40-21-9]]

^<<v40-21-9,9>>^ As for the crowds, those going ahead of him and those following kept crying out: “Save, we pray,^&#42;1^ the Son of David! Blessed is he that comes in Jehovah’s^&#42;2^ name! Save him, we pray, in the heights above!”^&#42;3^

[NOTE]
====
. Lit., “Hosanna.” Gr., Ho·san·naʹ; Vgc(Lat.), Ho·sanʹna; J1-14,​16-18,​22(Heb.), hoh·shaʽ-naʼʹ, “Save, we pray!”
. See App 1D.
. Or, “in the highest places.”
====

[[v40-21-10]]

^<<v40-21-10,10>>^ Now when he entered into Jerusalem, the whole city was set in commotion, saying: “Who is this?”

[[v40-21-11]]

^<<v40-21-11,11>>^ The crowds kept telling: “This is the prophet Jesus, from Nazʹa·reth of Galʹi·lee!”

[[v40-21-12]]

^<<v40-21-12,12>>^ And Jesus entered into the temple and threw out all those selling and buying in the temple, and overturned the tables of the money changers and the benches of those selling doves.

[[v40-21-13]]

^<<v40-21-13,13>>^ And he said to them: “It is written, ‘My house will be called a house of prayer,’ but YOU are making it a cave of robbers.”

[[v40-21-14]]

^<<v40-21-14,14>>^ Also, blind and lame persons came up to him in the temple, and he cured them.

[[v40-21-15]]

^<<v40-21-15,15>>^ When the chief priests and the scribes saw the marvelous things he did and the boys that were crying out in the temple and saying: “Save, we pray, the Son of David!” they became indignant

[[v40-21-16]]

^<<v40-21-16,16>>^ and said to him: “Do you hear what these are saying?” Jesus said to them: “Yes. Did YOU never read this, ‘Out of the mouth of babes and sucklings you have furnished praise’?”

[[v40-21-17]]

^<<v40-21-17,17>>^ And leaving them behind he went outside the city to Bethʹa·ny and passed the night there.

[[v40-21-18]]

^<<v40-21-18,18>>^ While returning to the city early in the morning, he got hungry.

[[v40-21-19]]

^<<v40-21-19,19>>^ And he caught sight of a fig tree by the road and went to it, but he found nothing on it except leaves only, and he said to it: “Let no fruit come from you anymore forever.” And the fig tree withered instantly.

[[v40-21-20]]

^<<v40-21-20,20>>^ But when the disciples saw this, they wondered, saying: “How is it that the fig tree withered instantly?”

[[v40-21-21]]

^<<v40-21-21,21>>^ In answer Jesus said to them: “Truly I say to YOU, If only YOU have faith and do not doubt, not only will YOU do what I did to the fig tree, but also if YOU say to this mountain, ‘Be lifted up and cast into the sea,’ it will happen.

[[v40-21-22]]

^<<v40-21-22,22>>^ And all the things YOU ask in prayer, having faith, YOU will receive.”

[[v40-21-23]]

^<<v40-21-23,23>>^ Now after he went into the temple, the chief priests and the older men of the people came up to him while he was teaching and said: “By what authority do you do these things? And who gave you this authority?”

[[v40-21-24]]

^<<v40-21-24,24>>^ In reply Jesus said to them: “I, also, will ask YOU one thing. If YOU tell it to me, I also will tell YOU by what authority I do these things:

[[v40-21-25]]

^<<v40-21-25,25>>^ The baptism by John, from what source was it? From heaven or from men?” But they began to reason among themselves, saying: “If we say, ‘From heaven,’ he will say to us, ‘Why, then, did YOU not believe him?’

[[v40-21-26]]

^<<v40-21-26,26>>^ If, though, we say, ‘From men,’ we have the crowd to fear, for they all hold John as a prophet.”

[[v40-21-27]]

^<<v40-21-27,27>>^ So in answer to Jesus they said: “We do not know.” He, in turn, said to them: “Neither am I telling YOU by what authority I do these things.

[[v40-21-28]]

^<<v40-21-28,28>>^ “What do YOU think? A man had two children. Going up to the first, he said, ‘Child, go work today in the vineyard.’

[[v40-21-29]]

^<<v40-21-29,29>>^ In answer this one said, ‘I will, sir,’ but did not go out.

[[v40-21-30]]

^<<v40-21-30,30>>^ Approaching the second, he said the same. In reply this one said, ‘I will not.’ Afterwards he felt regret and went out.

[[v40-21-31]]

^<<v40-21-31,31>>^ Which of the two did the will of &#91;his&#93; father?” They said: “The latter.” Jesus said to them: “Truly I say to YOU that the tax collectors and the harlots are going ahead of YOU into the kingdom of God.

[[v40-21-32]]

^<<v40-21-32,32>>^ For John came to YOU in a way of righteousness, but YOU did not believe him. However, the tax collectors and the harlots believed him, and YOU, although YOU saw &#91;this&#93;, did not feel regret afterwards so as to believe him.

[[v40-21-33]]

^<<v40-21-33,33>>^ “Hear another illustration:^&#42;1^ There was a man, a householder, who planted a vineyard and put a fence around it and dug a winepress in it and erected a tower, and let it out to cultivators, and traveled abroad.

[NOTE]
====
. Or, “parable.”
====

[[v40-21-34]]

^<<v40-21-34,34>>^ When the season of the fruits came around, he dispatched his slaves to the cultivators to get his fruits.

[[v40-21-35]]

^<<v40-21-35,35>>^ However, the cultivators took his slaves, and one they beat up, another they killed, another they stoned.

[[v40-21-36]]

^<<v40-21-36,36>>^ Again he dispatched other slaves, more than the first, but they did the same to these.

[[v40-21-37]]

^<<v40-21-37,37>>^ Lastly he dispatched his son to them, saying, ‘They will respect my son.’

[[v40-21-38]]

^<<v40-21-38,38>>^ On seeing the son the cultivators said among themselves, ‘This is the heir; come, let us kill him and get his inheritance!’

[[v40-21-39]]

^<<v40-21-39,39>>^ So they took him and threw him out of the vineyard and killed him.

[[v40-21-40]]

^<<v40-21-40,40>>^ Therefore, when the owner of the vineyard comes, what will he do to those cultivators?”

[[v40-21-41]]

^<<v40-21-41,41>>^ They said to him: “Because they are evil, he will bring an evil destruction upon them and will let out the vineyard to other cultivators, who will render him the fruits when they become due.”

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus said to them: “Did YOU never read in the Scriptures, ‘The stone that the builders rejected is the one that has become the chief cornerstone. From Jehovah^&#42;1^ this has come to be, and it is marvelous in our eyes’?

[NOTE]
====
. See App 1D.
====

[[v40-21-43]]

^<<v40-21-43,43>>^ This is why I say to YOU, The kingdom of God will be taken from YOU and be given to a nation producing its fruits.

[[v40-21-44]]

^<<v40-21-44,44>>^ Also, the person falling upon this stone will be shattered. As for anyone upon whom it falls, it will pulverize him.”

[[v40-21-45]]

^<<v40-21-45,45>>^ Now when the chief priests and the Pharisees had heard his illustrations, they took note that he was speaking about them.

[[v40-21-46]]

^<<v40-21-46,46>>^ But, although they were seeking to seize him, they feared the crowds, because these held him to be a prophet.

'''

xref:040-matthew/040-matthew-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-matthew/040-matthew-022.adoc#v40-22-0[Próximo Capítulo &#62;]