include::./index.adoc[]

[[v40-6-0]]
=== According to Matthew, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-6-1]]

^<<v40-6-1,1>>^ “Take good care not to practice YOUR righteousness in front of men in order to be observed by them; otherwise YOU will have no reward with YOUR Father who is in the heavens.

[[v40-6-2]]

^<<v40-6-2,2>>^ Hence when you go making gifts of mercy, do not blow a trumpet ahead of you, just as the hypocrites do in the synagogues and in the streets, that they may be glorified by men. Truly I say to YOU, They are having their reward in full.

[[v40-6-3]]

^<<v40-6-3,3>>^ But you, when making gifts of mercy, do not let your left hand know what your right is doing,

[[v40-6-4]]

^<<v40-6-4,4>>^ that your gifts of mercy may be in secret; then your Father who is looking on in secret will repay you.

[[v40-6-5]]

^<<v40-6-5,5>>^ “Also, when YOU pray, YOU must not be as the hypocrites; because they like to pray standing in the synagogues and on the corners of the broad ways to be visible to men. Truly I say to YOU, They are having their reward in full.

[[v40-6-6]]

^<<v40-6-6,6>>^ You, however, when you pray, go into your private room and, after shutting your door, pray to your Father who is in secret; then your Father who looks on in secret will repay you.

[[v40-6-7]]

^<<v40-6-7,7>>^ But when praying, do not say the same things over and over again,^&#42;1^ just as the people of the nations do, for they imagine they will get a hearing for their use of many words.

[NOTE]
====
. Or, “do not babble words; do not utter empty repetitions.”
====

[[v40-6-8]]

^<<v40-6-8,8>>^ So, do not make yourselves like them, for God YOUR Father knows what things YOU are needing before ever YOU ask him.

[[v40-6-9]]

^<<v40-6-9,9>>^ “YOU must pray, then, this way:
“‘Our Father in the heavens, let your name be sanctified.^&#42;1^

[NOTE]
====
. Or, “be held sacred; be treated as holy.” Gr., ha·gi·a·stheʹto; Lat., sanc·ti·fi·ceʹtur; J17,​18(Heb.), yith·qad·dashʹ, “let be sanctified.” See Ex 29:43 ftn, “Sanctified.”
====

[[v40-6-10]]

^<<v40-6-10,10>>^ Let your kingdom come. Let your will take place, as in heaven, also upon earth.

[[v40-6-11]]

^<<v40-6-11,11>>^ Give us today our bread for this day;

[[v40-6-12]]

^<<v40-6-12,12>>^ and forgive us our debts, as we also have forgiven our debtors.

[[v40-6-13]]

^<<v40-6-13,13>>^ And do not bring us into temptation, but deliver^&#42;1^ us from the wicked one.’^&#42;2^

[NOTE]
====
. Or, “rescue.”
. Or, “from what is wicked.”
====

[[v40-6-14]]

^<<v40-6-14,14>>^ “For if YOU forgive men their trespasses, YOUR heavenly Father will also forgive YOU;

[[v40-6-15]]

^<<v40-6-15,15>>^ whereas if YOU do not forgive men their trespasses, neither will YOUR Father forgive YOUR trespasses.

[[v40-6-16]]

^<<v40-6-16,16>>^ “When YOU are fasting, stop becoming sad-faced like the hypocrites, for they disfigure their faces that they may appear to men to be fasting. Truly I say to YOU, They are having their reward in full.

[[v40-6-17]]

^<<v40-6-17,17>>^ But you, when fasting, grease your head and wash your face,

[[v40-6-18]]

^<<v40-6-18,18>>^ that you may appear to be fasting, not to men, but to your Father who is in secrecy; then your Father who is looking on in secrecy will repay you.

[[v40-6-19]]

^<<v40-6-19,19>>^ “Stop storing up for yourselves treasures upon the earth, where moth and rust consume, and where thieves break in and steal.

[[v40-6-20]]

^<<v40-6-20,20>>^ Rather, store up for yourselves treasures in heaven, where neither moth nor rust consumes, and where thieves do not break in and steal.

[[v40-6-21]]

^<<v40-6-21,21>>^ For where your treasure is, there your heart will be also.

[[v40-6-22]]

^<<v40-6-22,22>>^ “The lamp of the body is the eye. If, then, your eye is simple,^&#42;1^ your whole body will be bright;

[NOTE]
====
. Or, “sincere; all one way; in focus; generous.”
====

[[v40-6-23]]

^<<v40-6-23,23>>^ but if your eye is wicked,^&#42;1^ your whole body will be dark. If in reality the light that is in you is darkness, how great that darkness is!

[NOTE]
====
. Or, “bad; envious.”
====

[[v40-6-24]]

^<<v40-6-24,24>>^ “No one can slave for two masters; for either he will hate the one and love the other, or he will stick to the one and despise the other. YOU cannot slave for God and for Riches.^&#42;1^

[NOTE]
====
. Or, “Mammon.” Gr., ma·mo·naiʹ, dative; J17,​18,​22(Heb.), ham·ma·mohnʹ, “the mammon.”
====

[[v40-6-25]]

^<<v40-6-25,25>>^ “On this account I say to YOU: Stop being anxious about YOUR souls^&#42;1^ as to what YOU will eat or what YOU will drink, or about YOUR bodies as to what YOU will wear. Does not the soul mean more than food and the body than clothing?

[NOTE]
====
. Or, “lives.” Lit., “soul.” Gr., psy·kheiʹ, sing. See App 4A.
====

[[v40-6-26]]

^<<v40-6-26,26>>^ Observe intently the birds of heaven, because they do not sow seed or reap or gather into storehouses; still YOUR heavenly Father feeds them. Are YOU not worth more than they are?

[[v40-6-27]]

^<<v40-6-27,27>>^ Who of YOU by being anxious can add one cubit to his life span?

[[v40-6-28]]

^<<v40-6-28,28>>^ Also, on the matter of clothing, why are YOU anxious? Take a lesson from the lilies of the field, how they are growing; they do not toil, nor do they spin;

[[v40-6-29]]

^<<v40-6-29,29>>^ but I say to YOU that not even Solʹo·mon in all his glory was arrayed as one of these.

[[v40-6-30]]

^<<v40-6-30,30>>^ If, now, God thus clothes the vegetation of the field, which is here today and tomorrow is thrown into the oven, will he not much rather clothe YOU, YOU with little faith?

[[v40-6-31]]

^<<v40-6-31,31>>^ So never be anxious and say, ‘What are we to eat?’ or, ‘What are we to drink?’ or, ‘What are we to put on?’

[[v40-6-32]]

^<<v40-6-32,32>>^ For all these are the things the nations are eagerly pursuing. For YOUR heavenly Father knows YOU need all these things.

[[v40-6-33]]

^<<v40-6-33,33>>^ “Keep on, then, seeking^&#42;1^ first the kingdom and his righteousness, and all these &#91;other&#93; things will be added to YOU.

[NOTE]
====
. Or, “Be you seeking.” Gr., ze·teiʹte; the verb form indicates continuous action.
====

[[v40-6-34]]

^<<v40-6-34,34>>^ So, never be anxious about the next day, for the next day will have its own anxieties. Sufficient for each day is its own badness.

'''

xref:040-matthew/040-matthew-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-matthew/040-matthew-007.adoc#v40-7-0[Próximo Capítulo &#62;]