include::./index.adoc[]

[[v40-25-0]]
=== According to Matthew, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-25-1]]

^<<v40-25-1,1>>^ “Then the kingdom of the heavens will become like ten virgins that took their lamps and went out to meet the bridegroom.

[[v40-25-2]]

^<<v40-25-2,2>>^ Five of them were foolish, and five were discreet.

[[v40-25-3]]

^<<v40-25-3,3>>^ For the foolish took their lamps but took no oil with them,

[[v40-25-4]]

^<<v40-25-4,4>>^ whereas the discreet took oil in their receptacles with their lamps.

[[v40-25-5]]

^<<v40-25-5,5>>^ While the bridegroom was delaying, they all nodded and went to sleep.

[[v40-25-6]]

^<<v40-25-6,6>>^ Right in the middle of the night there arose a cry, ‘Here is the bridegroom! Be on YOUR way out to meet him.’

[[v40-25-7]]

^<<v40-25-7,7>>^ Then all those virgins rose and put their lamps in order.

[[v40-25-8]]

^<<v40-25-8,8>>^ The foolish said to the discreet, ‘Give us some of YOUR oil, because our lamps are about to go out.’

[[v40-25-9]]

^<<v40-25-9,9>>^ The discreet answered with the words, ‘Perhaps there may not be quite enough for us and YOU. Be on YOUR way, instead, to those who sell it and buy for yourselves.’

[[v40-25-10]]

^<<v40-25-10,10>>^ While they were going off to buy, the bridegroom arrived, and the virgins that were ready went in with him to the marriage feast; and the door was shut.

[[v40-25-11]]

^<<v40-25-11,11>>^ Afterwards the rest of the virgins also came, saying, ‘Sir, sir, open to us!’

[[v40-25-12]]

^<<v40-25-12,12>>^ In answer he said, ‘I tell YOU the truth, I do not know YOU.’

[[v40-25-13]]

^<<v40-25-13,13>>^ “Keep on the watch, therefore, because YOU know neither the day nor the hour.

[[v40-25-14]]

^<<v40-25-14,14>>^ “For it is just as when a man, about to travel abroad, summoned slaves of his and committed to them his belongings.

[[v40-25-15]]

^<<v40-25-15,15>>^ And to one he gave five talents,^&#42;1^ to another two, to still another one, to each one according to his own ability, and he went abroad.

[NOTE]
====
. A Gr. talent weighed 20.4 kg (654 oz t). See App 8A.
====

[[v40-25-16]]

^<<v40-25-16,16>>^ Immediately the one that received the five talents went his way and did business with them and gained five more.

[[v40-25-17]]

^<<v40-25-17,17>>^ In the same way the one that received the two gained two more.

[[v40-25-18]]

^<<v40-25-18,18>>^ But the one that received just one went off, and dug in the ground and hid the silver money of his master.

[[v40-25-19]]

^<<v40-25-19,19>>^ “After a long time the master of those slaves came and settled accounts with them.

[[v40-25-20]]

^<<v40-25-20,20>>^ So the one that had received five talents^&#42;1^ came forward and brought five additional talents, saying, ‘Master, you committed five talents to me; see, I gained five talents more.’

[NOTE]
====
. See vs 15 ftn.
====

[[v40-25-21]]

^<<v40-25-21,21>>^ His master said to him, ‘Well done, good and faithful slave! You were faithful over a few things. I will appoint you over many things. Enter into the joy of your master.’

[[v40-25-22]]

^<<v40-25-22,22>>^ Next the one that had received the two talents came forward and said, ‘Master, you committed to me two talents; see, I gained two talents more.’

[[v40-25-23]]

^<<v40-25-23,23>>^ His master said to him, ‘Well done, good and faithful slave! You were faithful over a few things. I will appoint you over many things. Enter into the joy of your master.’

[[v40-25-24]]

^<<v40-25-24,24>>^ “Finally the one that had received the one talent came forward and said, ‘Master, I knew you to be an exacting^&#42;1^ man, reaping where you did not sow and gathering where you did not winnow.

[NOTE]
====
. Or, “hard.”
====

[[v40-25-25]]

^<<v40-25-25,25>>^ So I grew afraid and went off and hid your talent in the ground. Here you have what is yours.’

[[v40-25-26]]

^<<v40-25-26,26>>^ In reply his master said to him, ‘Wicked and sluggish^&#42;1^ slave, you knew, did you, that I reaped where I did not sow and gathered where I did not winnow?

[NOTE]
====
. Or, “timid; hesitating.”
====

[[v40-25-27]]

^<<v40-25-27,27>>^ Well, then, you ought to have deposited my silver monies with the bankers, and on my arrival I would be receiving what is mine with interest.

[[v40-25-28]]

^<<v40-25-28,28>>^ “‘Therefore TAKE away the talent^&#42;1^ from him and give it to him that has the ten talents.

[NOTE]
====
. See vs 15 ftn.
====

[[v40-25-29]]

^<<v40-25-29,29>>^ For to everyone that has, more will be given and he will have abundance; but as for him that does not have, even what he has will be taken away from him.

[[v40-25-30]]

^<<v40-25-30,30>>^ And throw the good-for-nothing slave out into the darkness outside. There is where &#91;his&#93; weeping and the gnashing^&#42;1^ of &#91;his&#93; teeth will be.’

[NOTE]
====
. Or, “grinding; clenching.”
====

[[v40-25-31]]

^<<v40-25-31,31>>^ “When the Son of man arrives in his glory, and all the angels with him, then he will sit down on his glorious throne.

[[v40-25-32]]

^<<v40-25-32,32>>^ And all the nations will be gathered before him, and he will separate people one from another, just as a shepherd separates the sheep from the goats.

[[v40-25-33]]

^<<v40-25-33,33>>^ And he will put the sheep on his right hand, but the goats^&#42;1^ on his left.

[NOTE]
====
. Lit., “little kids.”
====

[[v40-25-34]]

^<<v40-25-34,34>>^ “Then the king will say to those on his right, ‘Come, YOU who have been blessed by my Father, inherit the kingdom prepared for YOU from the founding^&#42;1^ of the world.

[NOTE]
====
. Lit., “a throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v40-25-35]]

^<<v40-25-35,35>>^ For I became hungry and YOU gave me something to eat; I got thirsty and YOU gave me something to drink. I was a stranger and YOU received me hospitably;

[[v40-25-36]]

^<<v40-25-36,36>>^ naked,^&#42;1^ and YOU clothed me. I fell sick and YOU looked after me. I was in prison and YOU came to me.’

[NOTE]
====
. Or, “not sufficiently dressed.” Gr., gy·mnosʹ, meaning “lightly clad; in the undergarment only”; not necessarily nude, or naked.
====

[[v40-25-37]]

^<<v40-25-37,37>>^ Then the righteous ones will answer him with the words, ‘Lord, when did we see you hungry and feed you, or thirsty, and give you something to drink?

[[v40-25-38]]

^<<v40-25-38,38>>^ When did we see you a stranger and receive you hospitably, or naked, and clothe you?

[[v40-25-39]]

^<<v40-25-39,39>>^ When did we see you sick or in prison and go to you?’

[[v40-25-40]]

^<<v40-25-40,40>>^ And in reply the king will say to them, ‘Truly I say to YOU, To the extent that YOU did it to one of the least of these my brothers, YOU did it to me.’

[[v40-25-41]]

^<<v40-25-41,41>>^ “Then he will say, in turn, to those on his left, ‘Be on YOUR way from me, YOU who have been cursed, into the everlasting fire prepared for the Devil and his angels.

[[v40-25-42]]

^<<v40-25-42,42>>^ For I became hungry, but YOU gave me nothing to eat, and I got thirsty, but YOU gave me nothing to drink.

[[v40-25-43]]

^<<v40-25-43,43>>^ I was a stranger, but YOU did not receive me hospitably; naked, but YOU did not clothe me; sick and in prison, but YOU did not look after me.’

[[v40-25-44]]

^<<v40-25-44,44>>^ Then they also will answer with the words, ‘Lord, when did we see you hungry or thirsty or a stranger or naked or sick or in prison and did not minister to you?’

[[v40-25-45]]

^<<v40-25-45,45>>^ Then he will answer them with the words, ‘Truly I say to YOU, To the extent that YOU did not do it to one of these least ones, YOU did not do it to me.’

[[v40-25-46]]

^<<v40-25-46,46>>^ And these will depart into everlasting cutting-off,^&#42;1^ but the righteous ones into everlasting life.”

[NOTE]
====
. Lit., “lopping off; pruning.” Gr., koʹla·sin. See 1Jo 4:18 ftn.
====

'''

xref:040-matthew/040-matthew-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-matthew/040-matthew-026.adoc#v40-26-0[Próximo Capítulo &#62;]