include::./index.adoc[]

[[v40-2-0]]
=== According to Matthew, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-2-1]]

^<<v40-2-1,1>>^ After Jesus had been born in Bethʹle·hem of Ju·deʹa in the days of Herod the king, look! astrologers^&#42;1^ from eastern parts came to Jerusalem,

[NOTE]
====
. Or, “magi.” Gr., maʹgoi.
====

[[v40-2-2]]

^<<v40-2-2,2>>^ saying: “Where is the one born king of the Jews? For we saw his star &#91;when we were&#93; in the east,^&#42;1^ and we have come to do him obeisance.”

[NOTE]
====
. Or, “we saw his star from the east.”
====

[[v40-2-3]]

^<<v40-2-3,3>>^ At hearing this King Herod was agitated, and all Jerusalem along with him;

[[v40-2-4]]

^<<v40-2-4,4>>^ and on gathering together all the chief priests and scribes of the people he began to inquire of them where the Christ^&#42;1^ was to be born.

[NOTE]
====
. “The Christ.” Gr., ὁ χριστός (ho Khri·stosʹ); J1-14,​16-18,​22(Heb.), המשיח (ham·Ma·shiʹach, “the Messiah; the Anointed One”).
====

[[v40-2-5]]

^<<v40-2-5,5>>^ They said to him: “In Bethʹle·hem of Ju·deʹa; for this is how it has been written through the prophet,

[[v40-2-6]]

^<<v40-2-6,6>>^ ‘And you, O Bethʹle·hem^&#42;1^ of the land of Judah, are by no means the most insignificant &#91;city&#93; among the governors^&#42;2^ of Judah; for out of you will come forth a governing one,^&#42;3^ who will shepherd my people, Israel.’”

[NOTE]
====
. Meaning “House of Bread.” Gr., Be·thle·emʹ; J17,​18,​22(Heb.), Behth leʹchem.
. Or, “leaders.” Gr., he·ge·moʹsin.
. Or, “a leader.” Gr., he·gouʹme·nos.
====

[[v40-2-7]]

^<<v40-2-7,7>>^ Then Herod secretly summoned the astrologers and carefully ascertained from them the time of the star’s appearing;

[[v40-2-8]]

^<<v40-2-8,8>>^ and, when sending them to Bethʹle·hem, he said: “Go make a careful search for the young child, and when YOU have found it report back to me, that I too may go and do it obeisance.”

[[v40-2-9]]

^<<v40-2-9,9>>^ When they had heard the king, they went their way; and, look! the star they had seen &#91;when they were&#93; in the east^&#42;1^ went ahead of them, until it came to a stop above where the young child was.

[NOTE]
====
. Or, “they had seen from the east.”
====

[[v40-2-10]]

^<<v40-2-10,10>>^ On seeing the star they rejoiced very much indeed.

[[v40-2-11]]

^<<v40-2-11,11>>^ And when they went into the house they saw the young child with Mary its mother, and, falling down, they did obeisance to it. They also opened their treasures and presented it with gifts, gold and frankincense and myrrh.

[[v40-2-12]]

^<<v40-2-12,12>>^ However, because they were given divine warning in a dream not to return to Herod, they withdrew to their country by another way.

[[v40-2-13]]

^<<v40-2-13,13>>^ After they had withdrawn, look! Jehovah’s^&#42;1^ angel appeared in a dream to Joseph, saying: “Get up, take the young child and its mother and flee into Egypt, and stay there until I give you word; for Herod is about to search for the young child to destroy it.”

[NOTE]
====
. See App 1D.
====

[[v40-2-14]]

^<<v40-2-14,14>>^ So he got up and took along the young child and its mother by night and withdrew into Egypt,

[[v40-2-15]]

^<<v40-2-15,15>>^ and he stayed there until the decease of Herod, for that to be fulfilled which was spoken by Jehovah^&#42;1^ through his prophet, saying: “Out of Egypt I called my son.”

[NOTE]
====
. See App 1D.
====

[[v40-2-16]]

^<<v40-2-16,16>>^ Then Herod, seeing he had been outwitted by the astrologers,^&#42;1^ fell into a great rage, and he sent out and had all the boys in Bethʹle·hem and in all its districts done away with, from two years of age and under, according to the time that he had carefully ascertained from the astrologers.

[NOTE]
====
. Or, “magi.”
====

[[v40-2-17]]

^<<v40-2-17,17>>^ Then that was fulfilled which was spoken through Jeremiah the prophet, saying:

[[v40-2-18]]

^<<v40-2-18,18>>^ “A voice was heard in Raʹmah, weeping and much wailing; it was Rachel weeping for her children, and she was unwilling to take comfort, because they are no more.”

[[v40-2-19]]

^<<v40-2-19,19>>^ When Herod had deceased, look! Jehovah’s^&#42;1^ angel appeared in a dream to Joseph in Egypt

[NOTE]
====
. See App 1D.
====

[[v40-2-20]]

^<<v40-2-20,20>>^ and said: “Get up, take the young child and its mother and be on your way into the land of Israel, for those who were seeking the soul^&#42;1^ of the young child are dead.”

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; J17,​18,​22(Heb.), neʹphesh. See App 4A.
====

[[v40-2-21]]

^<<v40-2-21,21>>^ So he got up and took the young child and its mother and entered into the land of Israel.

[[v40-2-22]]

^<<v40-2-22,22>>^ But hearing that Ar·che·laʹus ruled as king of Ju·deʹa instead of his father Herod, he became afraid to depart for there. Moreover, being given divine warning in a dream, he withdrew into the territory of Galʹi·lee,

[[v40-2-23]]

^<<v40-2-23,23>>^ and came and dwelt in a city named Nazʹa·reth,^&#42;1^ that there might be fulfilled what was spoken through the prophets: “He will be called a Naz·a·reneʹ.”^&#42;2^

[NOTE]
====
. Or, “Sprout-town.” Gr., Na·za·retʹ; J22(Heb.), Na·tseʹreth.
. “Nazarene.” J17,​18,​22(Heb.), Nots·riʹ. Gr., Na·zo·raiʹos; probably from Heb. neʹtser, meaning “sprout,” hence, figuratively “offspring.” See Isa 11:1 and ftn, “Sprout.”
====

'''

xref:040-matthew/040-matthew-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-matthew/040-matthew-003.adoc#v40-3-0[Próximo Capítulo &#62;]