include::./index.adoc[]

[[v40-15-0]]
=== According to Matthew, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-15-1]]

^<<v40-15-1,1>>^ Then there came to Jesus from Jerusalem Pharisees and scribes, saying:

[[v40-15-2]]

^<<v40-15-2,2>>^ “Why is it your disciples overstep the tradition of the men of former times? For example, they do not wash their hands when about to eat a meal.”

[[v40-15-3]]

^<<v40-15-3,3>>^ In reply he said to them: “Why is it YOU also overstep the commandment of God because of YOUR tradition?

[[v40-15-4]]

^<<v40-15-4,4>>^ For example, God said, ‘Honor your father and your mother’; and, ‘Let him that reviles father or mother end up in death.’^&#42;1^

[NOTE]
====
. Or, “die without fail.”
====

[[v40-15-5]]

^<<v40-15-5,5>>^ But YOU say, ‘Whoever says to his father or mother: “Whatever I have by which you might get benefit from me is a gift dedicated to God,”

[[v40-15-6]]

^<<v40-15-6,6>>^ he must not honor his father at all.’ And so YOU have made the word of God invalid because of YOUR tradition.

[[v40-15-7]]

^<<v40-15-7,7>>^ YOU hypocrites, Isaiah aptly prophesied about YOU, when he said,

[[v40-15-8]]

^<<v40-15-8,8>>^ ‘This people honors me with their lips, yet their heart is far removed from me.

[[v40-15-9]]

^<<v40-15-9,9>>^ It is in vain that they keep worshiping me, because they teach commands of men as doctrines.’”

[[v40-15-10]]

^<<v40-15-10,10>>^ With that he called the crowd near and said to them: “Listen and get the sense of it:

[[v40-15-11]]

^<<v40-15-11,11>>^ Not what enters into &#91;his&#93; mouth defiles a man; but it is what proceeds out of &#91;his&#93; mouth that defiles a man.”

[[v40-15-12]]

^<<v40-15-12,12>>^ Then the disciples came up and said to him: “Do you know that the Pharisees stumbled at hearing what you said?”

[[v40-15-13]]

^<<v40-15-13,13>>^ In reply he said: “Every plant that my heavenly Father did not plant will be uprooted.

[[v40-15-14]]

^<<v40-15-14,14>>^ LET them be. Blind guides is what they are. If, then, a blind man guides a blind man, both will fall into a pit.”^&#42;1^

[NOTE]
====
. Or, “ditch.”
====

[[v40-15-15]]

^<<v40-15-15,15>>^ By way of response Peter said to him: “Make the illustration^&#42;1^ plain to us.”

[NOTE]
====
. Or, “parable.”
====

[[v40-15-16]]

^<<v40-15-16,16>>^ At this he said: “Are YOU also yet without understanding?

[[v40-15-17]]

^<<v40-15-17,17>>^ Are YOU not aware that everything entering into the mouth passes along into the intestines and is discharged into the sewer?^&#42;1^

[NOTE]
====
. Or, “cesspool; water closet; privy.”
====

[[v40-15-18]]

^<<v40-15-18,18>>^ However, the things proceeding out of the mouth come out of the heart, and those things defile a man.

[[v40-15-19]]

^<<v40-15-19,19>>^ For example, out of the heart come wicked reasonings, murders, adulteries, fornications, thieveries, false testimonies, blasphemies.

[[v40-15-20]]

^<<v40-15-20,20>>^ These are the things defiling a man; but to take a meal with unwashed hands does not defile a man.”

[[v40-15-21]]

^<<v40-15-21,21>>^ Leaving there, Jesus now withdrew into the parts of Tyre and Siʹdon.

[[v40-15-22]]

^<<v40-15-22,22>>^ And, look! a Phoe·niʹcian^&#42;1^ woman from those regions came out and cried aloud, saying: “Have mercy on me, Lord, Son of David. My daughter is badly demonized.”

[NOTE]
====
. Or, “Canaanite.”
====

[[v40-15-23]]

^<<v40-15-23,23>>^ But he did not say a word in answer to her. So his disciples came up and began to request him: “Send her away; because she keeps crying out after us.”

[[v40-15-24]]

^<<v40-15-24,24>>^ In answer he said: “I was not sent forth to any but to the lost sheep of the house of Israel.”

[[v40-15-25]]

^<<v40-15-25,25>>^ When the woman came she began doing obeisance to him, saying: “Lord, help me!”

[[v40-15-26]]

^<<v40-15-26,26>>^ In answer he said: “It is not right to take the bread of the children and throw it to little dogs.”

[[v40-15-27]]

^<<v40-15-27,27>>^ She said: “Yes, Lord; but really the little dogs do eat of the crumbs falling from the table of their masters.”

[[v40-15-28]]

^<<v40-15-28,28>>^ Then Jesus said in reply to her: “O woman, great is your faith; let it happen to you as you wish.” And her daughter was healed from that hour on.

[[v40-15-29]]

^<<v40-15-29,29>>^ Crossing country from there, Jesus next came near the sea of Galʹi·lee, and, after going up into the mountain, he was sitting there.

[[v40-15-30]]

^<<v40-15-30,30>>^ Then great crowds approached him, having along with them people that were lame, maimed, blind, dumb, and many otherwise, and they fairly threw them at his feet, and he cured them;

[[v40-15-31]]

^<<v40-15-31,31>>^ so that the crowd felt amazement as they saw the dumb speaking and the lame walking and the blind seeing, and they glorified the God of Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ But Jesus called his disciples to him and said: “I feel pity for the crowd, because it is already three days that they have stayed with me and they have nothing to eat; and I do not want to send them away fasting. They may possibly give out on the road.”

[[v40-15-33]]

^<<v40-15-33,33>>^ However, the disciples said to him: “Where are we in this lonely place going to get sufficient loaves to satisfy a crowd of this size?”

[[v40-15-34]]

^<<v40-15-34,34>>^ At this Jesus said to them: “How many loaves have YOU?” They said: “Seven, and a few little fishes.”

[[v40-15-35]]

^<<v40-15-35,35>>^ So, after instructing the crowd to recline upon the ground,

[[v40-15-36]]

^<<v40-15-36,36>>^ he took the seven loaves and the fishes and, after offering thanks, he broke them and began distributing to the disciples, the disciples in turn to the crowds.

[[v40-15-37]]

^<<v40-15-37,37>>^ And all ate and were satisfied, and as a surplus of fragments they took up seven provision baskets full.

[[v40-15-38]]

^<<v40-15-38,38>>^ Yet those eating were four thousand men, besides women and young children.

[[v40-15-39]]

^<<v40-15-39,39>>^ Finally, after sending the crowds away, he got into the boat and came into the regions of Magʹa·dan.

'''

xref:040-matthew/040-matthew-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-matthew/040-matthew-016.adoc#v40-16-0[Próximo Capítulo &#62;]