include::./index.adoc[]

[[v40-28-0]]
=== According to Matthew, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v40-28-1]]

^<<v40-28-1,1>>^ After^&#42;1^ the sabbath, when it was growing light on the first day of the week, Mary Magʹda·lene and the other Mary came to view the grave.

[NOTE]
====
. “After,” J17,​18,​21,​22. For a discussion of “After the sabbath,” see App 7C.
====

[[v40-28-2]]

^<<v40-28-2,2>>^ And, notice! a great earthquake had taken place; for Jehovah’s^&#42;1^ angel had descended from heaven and approached and rolled away the stone, and was sitting on it.

[NOTE]
====
. See App 1D.
====

[[v40-28-3]]

^<<v40-28-3,3>>^ His outward appearance was as lightning, and his clothing as white as snow.

[[v40-28-4]]

^<<v40-28-4,4>>^ Yes, for fear of him the watchmen trembled and became as dead men.

[[v40-28-5]]

^<<v40-28-5,5>>^ But the angel in answer said to the women: “Do not YOU be fearful, for I know YOU are looking for Jesus who was impaled.^&#42;1^

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v40-28-6]]

^<<v40-28-6,6>>^ He is not here, for he was raised up, as he said. Come, see the place where he was lying.

[[v40-28-7]]

^<<v40-28-7,7>>^ And go quickly and tell his disciples that he was raised up from the dead, and, look! he is going ahead of YOU into Galʹi·lee; there YOU will see him. Look! I have told YOU.”

[[v40-28-8]]

^<<v40-28-8,8>>^ So, quickly leaving the memorial tomb, with fear and great joy, they ran to report to his disciples.

[[v40-28-9]]

^<<v40-28-9,9>>^ And, look! Jesus met them and said: “Good day!” They approached and caught him by his feet and did obeisance to him.

[[v40-28-10]]

^<<v40-28-10,10>>^ Then Jesus said to them: “Have no fear! Go, report to my brothers, that they may go off into Galʹi·lee; and there they will see me.”

[[v40-28-11]]

^<<v40-28-11,11>>^ While they were on their way, look! some of the guard went into the city and reported to the chief priests all the things that had happened.

[[v40-28-12]]

^<<v40-28-12,12>>^ And after these had gathered together with the older men and taken counsel, they gave a sufficient number of silver pieces to the soldiers

[[v40-28-13]]

^<<v40-28-13,13>>^ and said: “Say, ‘His disciples came in the night and stole him while we were sleeping.’

[[v40-28-14]]

^<<v40-28-14,14>>^ And if this gets to the governor’s ears, we will persuade &#91;him&#93; and will set YOU free from worry.”

[[v40-28-15]]

^<<v40-28-15,15>>^ So they took the silver pieces and did as they were instructed; and this saying has been spread abroad among the Jews up to this very day.

[[v40-28-16]]

^<<v40-28-16,16>>^ However, the eleven disciples went into Galʹi·lee to the mountain where Jesus had arranged for them,

[[v40-28-17]]

^<<v40-28-17,17>>^ and when they saw him they did obeisance, but some doubted.

[[v40-28-18]]

^<<v40-28-18,18>>^ And Jesus approached and spoke to them, saying: “All authority^&#42;1^ has been given me in heaven and on the earth.

[NOTE]
====
. “Authority.” Gr., e·xou·siʹa; Lat., po·teʹstas; J18(Heb.), mim·shalʹ.
====

[[v40-28-19]]

^<<v40-28-19,19>>^ Go therefore and make disciples^&#42;1^ of people of all the nations, baptizing them in^&#42;2^ the name of the Father and of the Son and of the holy spirit,

[NOTE]
====
. Or, “make learners.” Gr., ma·the·teuʹsa·te.
. Or, “into.”
====

[[v40-28-20]]

^<<v40-28-20,20>>^ teaching them to observe all the things I have commanded YOU. And, look! I am with YOU all the days until the conclusion^&#42;1^ of the system of things.”^&#42;2^

[NOTE]
====
. See 24:3 ftn, “Conclusion.”
. See 13:39 ftn, “Things.”
====

'''

xref:040-matthew/040-matthew-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-mark/041-mark-001.adoc#v41-1-0[Próximo Capítulo &#62;]