include::./index.adoc[]

[[v47-3-0]]
=== The Second to the Corinthians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-3-1]]

^<<v47-3-1,1>>^ Are we starting again to recommend ourselves? Or do we, perhaps, like some men, need letters of recommendation to YOU or from YOU?

[[v47-3-2]]

^<<v47-3-2,2>>^ YOU yourselves are our letter, inscribed on our^&#42;1^ hearts and known and being read by all mankind.

[NOTE]
====
. “Our,” P46ABCDVgSyh,p; א, “your.”
====

[[v47-3-3]]

^<<v47-3-3,3>>^ For YOU are shown to be a letter of Christ written by us as ministers, inscribed not with ink but with spirit of a living God, not on stone tablets, but on fleshly tablets, on hearts.^&#42;1^

[NOTE]
====
. Or, “on tablets, on fleshly hearts.”
====

[[v47-3-4]]

^<<v47-3-4,4>>^ Now through the Christ we have this sort of confidence toward God.

[[v47-3-5]]

^<<v47-3-5,5>>^ Not that we of ourselves are adequately qualified to reckon anything as issuing from ourselves, but our being adequately qualified^&#42;1^ issues from God,

[NOTE]
====
. Lit., “the sufficiency of us.”
====

[[v47-3-6]]

^<<v47-3-6,6>>^ who has indeed adequately qualified us to be ministers^&#42;1^ of a new covenant, not of a written code,^&#42;2^ but of spirit; for the written code condemns to death, but the spirit makes alive.

[NOTE]
====
. Or, “servants.” Gr., di·a·koʹnous; Lat., mi·niʹstros (from miʹnus, “less”); J22(Heb.), mesha·rethimʹ.
. Lit., “of written character.” Gr., gramʹma·tos; Lat., litʹte·rae.
====

[[v47-3-7]]

^<<v47-3-7,7>>^ Moreover, if the code which administers death and which was engraved^&#42;1^ in letters in stones came about in a glory, so that the sons of Israel could not gaze intently at the face of Moses because of the glory of his face, &#91;a glory&#93; that was to be done away with,

[NOTE]
====
. Or, “if the administering of death engraved.”
====

[[v47-3-8]]

^<<v47-3-8,8>>^ why should not the administering of the spirit be much more with glory?

[[v47-3-9]]

^<<v47-3-9,9>>^ For if the code administering condemnation^&#42;1^ was glorious,^&#42;2^ much more does the administering of righteousness abound with glory.

[NOTE]
====
. Or, “if the administering of condemnation.”
. Lit., “was a glory.”
====

[[v47-3-10]]

^<<v47-3-10,10>>^ In fact, even that which has once been made glorious has been stripped of glory in this respect, because of the glory that excels it.

[[v47-3-11]]

^<<v47-3-11,11>>^ For if that which was to be done away with was brought in with glory, much more would that which remains be with glory.

[[v47-3-12]]

^<<v47-3-12,12>>^ Therefore, as we have such a hope, we are using great freeness of speech,

[[v47-3-13]]

^<<v47-3-13,13>>^ and not doing as when Moses would put a veil upon his face, that the sons of Israel might not gaze intently at the end of that which was to be done away with.

[[v47-3-14]]

^<<v47-3-14,14>>^ But their mental powers were dulled. For to this present day the same veil remains unlifted at the reading of the old covenant,^&#42;1^ because it is done away with by means of Christ.

[NOTE]
====
. For a discussion of the expressions “The Old Testament” and “The New Testament,” see App 7E.
====

[[v47-3-15]]

^<<v47-3-15,15>>^ In fact, down till today whenever Moses is read, a veil lies upon their hearts.

[[v47-3-16]]

^<<v47-3-16,16>>^ But when there is a turning to Jehovah,^&#42;1^ the veil is taken away.

[NOTE]
====
. See App 1D.
====

[[v47-3-17]]

^<<v47-3-17,17>>^ Now Jehovah^&#42;1^ is the Spirit; and where the spirit of Jehovah^&#42;2^ is, there is freedom.

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v47-3-18]]

^<<v47-3-18,18>>^ And all of us, while we with unveiled faces reflect like mirrors the glory of Jehovah,^&#42;1^ are transformed into the same image from glory to glory, exactly as done by Jehovah^&#42;2^ &#91;the&#93; Spirit.^&#42;3^

[NOTE]
====
. See App 1D.
. See App 1D.
. Or, “by Jehovah’s spirit.”
====

'''

xref:047-2-corinthians/047-2-corinthians-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-004.adoc#v47-4-0[Próximo Capítulo &#62;]