include::./index.adoc[]

[[v47-1-0]]
=== The Second to the Corinthians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-1-1]]

^<<v47-1-1,1>>^ Paul, an apostle of Christ Jesus through God’s will, and Timothy &#91;our&#93; brother to the congregation of God that is in Corinth, together with all the holy ones who are in all of A·chaʹia:^&#42;1^

[NOTE]
====
. The Roman province of southern Greece with its capital at Corinth.
====

[[v47-1-2]]

^<<v47-1-2,2>>^ May YOU have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[[v47-1-3]]

^<<v47-1-3,3>>^ Blessed be the God and Father of our Lord Jesus Christ, the Father of tender mercies and the God of all comfort,

[[v47-1-4]]

^<<v47-1-4,4>>^ who comforts us in all our tribulation, that we may be able to comfort those in any sort of tribulation through the comfort with which we ourselves are being comforted by God.

[[v47-1-5]]

^<<v47-1-5,5>>^ For just as the sufferings for the Christ abound in us, so the comfort we get also abounds through the Christ.

[[v47-1-6]]

^<<v47-1-6,6>>^ Now whether we are in tribulation, it is for YOUR comfort and salvation; or whether we are being comforted, it is for YOUR comfort that operates to make YOU endure the same sufferings that we also suffer.

[[v47-1-7]]

^<<v47-1-7,7>>^ And so our hope for YOU is unwavering, knowing as we do that, just as YOU are sharers of the sufferings, in the same way YOU will also share the comfort.

[[v47-1-8]]

^<<v47-1-8,8>>^ For we do not wish YOU to be ignorant, brothers, about the tribulation that happened to us in the &#91;district of&#93; Asia, that we were under extreme pressure beyond our strength, so that we were very uncertain even of our lives.

[[v47-1-9]]

^<<v47-1-9,9>>^ In fact, we felt within ourselves that we had received the sentence of death. This was that we might have our trust, not in ourselves, but in the God who raises up the dead.

[[v47-1-10]]

^<<v47-1-10,10>>^ From such a great thing as death he did rescue us and will rescue us; and our hope is in him that he will also rescue us further.

[[v47-1-11]]

^<<v47-1-11,11>>^ YOU also can help along by YOUR supplication for us, in order that thanks may be given by many in our behalf for what is kindly given to us due to many &#91;prayerful&#93; faces.

[[v47-1-12]]

^<<v47-1-12,12>>^ For the thing we boast of is this, to which our conscience bears witness, that with holiness and godly sincerity, not with fleshly wisdom but with God’s undeserved kindness, we have conducted ourselves in the world, but more especially toward YOU.

[[v47-1-13]]

^<<v47-1-13,13>>^ For we are really not writing YOU things except those which YOU well know^&#42;1^ or also recognize; and which I hope YOU will continue to recognize to the end,

[NOTE]
====
. Lit., “you are reading.”
====

[[v47-1-14]]

^<<v47-1-14,14>>^ just as YOU have also recognized, to an extent, that we are a cause for YOU to boast, just as YOU will also be for us in the day of our Lord Jesus.

[[v47-1-15]]

^<<v47-1-15,15>>^ So, with this confidence, I was intending before to come to YOU, that YOU might have a second &#91;occasion for&#93; joy,

[[v47-1-16]]

^<<v47-1-16,16>>^ and after a stopover with YOU to go to Mac·e·doʹni·a, and to come back from Mac·e·doʹni·a to YOU and be conducted partway by YOU to Ju·deʹa.

[[v47-1-17]]

^<<v47-1-17,17>>^ Well, when I had such an intention, I did not indulge in any lightness, did I? Or what things I purpose, do I purpose &#91;them&#93; according to the flesh, that with me there should be “Yes, Yes” and “No, No”?

[[v47-1-18]]

^<<v47-1-18,18>>^ But God can be relied upon that our speech addressed to YOU is not Yes and yet No.^&#42;1^

[NOTE]
====
. Or, “Yes and No in one breath.” Lit., “Yes and No.” Gr., Nai kai Ou; Lat., EST et NON; J17,​18(Heb.), Hen wa·Loʼʹ.
====

[[v47-1-19]]

^<<v47-1-19,19>>^ For the Son of God, Christ Jesus, who was preached among YOU through us, that is, through me and Sil·vaʹnus and Timothy, did not become Yes and yet No, but Yes has become Yes in his case.

[[v47-1-20]]

^<<v47-1-20,20>>^ For no matter how many the promises of God are, they have become Yes by means of him.^&#42;1^ Therefore also through him is the “Amen” &#91;said&#93; to God for glory through us.

[NOTE]
====
. “By means of him.” Or, “in him.”
====

[[v47-1-21]]

^<<v47-1-21,21>>^ But he who guarantees that YOU and we belong to Christ and he who has anointed us is God.

[[v47-1-22]]

^<<v47-1-22,22>>^ He has also put his seal upon us and has given us the token of what is to come,^&#42;1^ that is, the spirit, in our hearts.

[NOTE]
====
. Or, “earnest money (down payment) of what is to come.” Gr., ar·ra·boʹna. See Eph 1:14 ftn, “Advance.”
====

[[v47-1-23]]

^<<v47-1-23,23>>^ Now I call upon God as a witness against my own soul that it is to spare YOU that I have not yet come to Corinth.

[[v47-1-24]]

^<<v47-1-24,24>>^ Not that we are the masters over YOUR faith, but we are fellow workers for YOUR joy, for it is by &#91;YOUR&#93; faith that YOU are standing.

'''

xref:046-1-corinthians/046-1-corinthians-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-002.adoc#v47-2-0[Próximo Capítulo &#62;]