include::./index.adoc[]

[[v47-9-0]]
=== The Second to the Corinthians, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-9-1]]

^<<v47-9-1,1>>^ Now concerning the ministry that is for the holy ones, it is superfluous for me to write YOU,

[[v47-9-2]]

^<<v47-9-2,2>>^ for I know YOUR readiness of mind of which I am boasting to the Mac·e·doʹni·ans about YOU, that A·chaʹia has stood ready now for a year, and YOUR zeal has stirred up the majority of them.

[[v47-9-3]]

^<<v47-9-3,3>>^ But I am sending the brothers, that our boasting about YOU might not prove empty in this respect, but that YOU may really be ready, just as I used to say YOU would be.

[[v47-9-4]]

^<<v47-9-4,4>>^ Otherwise, in some way, if Mac·e·doʹni·ans should come with me and find YOU not ready, we—not to say YOU—should be put to shame in this assurance of ours.

[[v47-9-5]]

^<<v47-9-5,5>>^ Therefore I thought it necessary to encourage the brothers to come to YOU in advance and to get ready in advance YOUR bountiful gift previously promised, that thus this might be ready as a bountiful gift and not as something extorted.^&#42;1^

[NOTE]
====
. Or, “something given with covetousness.”
====

[[v47-9-6]]

^<<v47-9-6,6>>^ But as to this, he that sows sparingly will also reap sparingly; and he that sows bountifully will also reap bountifully.

[[v47-9-7]]

^<<v47-9-7,7>>^ Let each one do just as he has resolved in his heart, not grudgingly or under compulsion, for God loves a cheerful giver.

[[v47-9-8]]

^<<v47-9-8,8>>^ God, moreover, is able to make all his undeserved kindness abound toward YOU, that, while YOU always have full self-sufficiency in everything, YOU may have plenty for every good work.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Just as it is written: “He has distributed widely, he has given to the poor ones, his righteousness^&#42;1^ continues forever.”

[NOTE]
====
. Or, “beneficence.”
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Now he that abundantly supplies seed to the sower and bread for eating will supply and multiply the seed for YOU to sow and will increase the products of YOUR righteousness.)

[[v47-9-11]]

^<<v47-9-11,11>>^ In everything YOU are being enriched for every sort of generosity, which produces through us an expression of thanks to God;

[[v47-9-12]]

^<<v47-9-12,12>>^ because the ministry of this public service is not only to supply abundantly the wants of the holy ones but also to be rich with many expressions of thanks to God.

[[v47-9-13]]

^<<v47-9-13,13>>^ Through the proof that this ministry gives, they glorify God because YOU are submissive to the good news about the Christ, as YOU publicly declare YOU are, and because YOU are generous in YOUR contribution to them and to all;

[[v47-9-14]]

^<<v47-9-14,14>>^ and with supplication for YOU they long for YOU because of the surpassing undeserved kindness of God upon YOU.

[[v47-9-15]]

^<<v47-9-15,15>>^ Thanks be to God for his indescribable free gift.

'''

xref:047-2-corinthians/047-2-corinthians-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-010.adoc#v47-10-0[Próximo Capítulo &#62;]