include::./index.adoc[]

[[v47-6-0]]
=== The Second to the Corinthians, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-6-1]]

^<<v47-6-1,1>>^ Working together with him, we also entreat YOU not to accept the undeserved kindness of God and miss its purpose.

[[v47-6-2]]

^<<v47-6-2,2>>^ For he says: “In an acceptable time I heard you, and in a day of salvation I helped you.” Look! Now is the especially acceptable time. Look! Now is the day of salvation.

[[v47-6-3]]

^<<v47-6-3,3>>^ In no way are we giving any cause for stumbling, that our ministry might not be found fault with;

[[v47-6-4]]

^<<v47-6-4,4>>^ but in every way we recommend ourselves as God’s ministers,^&#42;1^ by the endurance of much, by tribulations, by cases of need, by difficulties,

[NOTE]
====
. Or, “servants.” Gr., di·aʹko·noi; Lat., mi·niʹstros (from miʹnus, “less”); J18,​22(Heb.), kim·sha·rethehʹ, “as attendants of.”
====

[[v47-6-5]]

^<<v47-6-5,5>>^ by beatings, by prisons, by disorders, by labors, by sleepless nights, by times without food,

[[v47-6-6]]

^<<v47-6-6,6>>^ by purity, by knowledge, by long-suffering, by kindness, by holy spirit, by love free from hypocrisy,

[[v47-6-7]]

^<<v47-6-7,7>>^ by truthful speech, by God’s power; through the weapons of righteousness on the right hand and on the left,^&#42;1^

[NOTE]
====
. Or, “for offense and defense.”
====

[[v47-6-8]]

^<<v47-6-8,8>>^ through glory and dishonor, through bad report and good report; as deceivers and yet truthful,

[[v47-6-9]]

^<<v47-6-9,9>>^ as being unknown and yet being recognized, as dying and yet, look! we live, as disciplined and yet not delivered to death,

[[v47-6-10]]

^<<v47-6-10,10>>^ as sorrowing but ever rejoicing, as poor but making many rich, as having nothing and yet possessing all things.

[[v47-6-11]]

^<<v47-6-11,11>>^ Our mouth has been opened to YOU, Corinthians, our heart has widened out.

[[v47-6-12]]

^<<v47-6-12,12>>^ YOU are not cramped for room within us, but YOU are cramped for room in YOUR own tender affections.

[[v47-6-13]]

^<<v47-6-13,13>>^ So, as a recompense in return—I speak as to children—YOU, too, widen out.

[[v47-6-14]]

^<<v47-6-14,14>>^ Do not become unevenly yoked^&#42;1^ with unbelievers. For what fellowship do righteousness and lawlessness have? Or what sharing does light have with darkness?

[NOTE]
====
. Lit., “being differently yoked.”
====

[[v47-6-15]]

^<<v47-6-15,15>>^ Further, what harmony is there between Christ and Beʹli·al?^&#42;1^ Or what portion does a faithful^&#42;2^ person have with an unbeliever?

[NOTE]
====
. “Belial,” Vg; P46אBC, “Beliar”; Syp, “Satan.”
. Or, “believing.”
====

[[v47-6-16]]

^<<v47-6-16,16>>^ And what agreement does God’s temple^&#42;1^ have with idols? For we are a temple of a living God; just as God said: “I shall reside among them and walk among &#91;them&#93;, and I shall be their God, and they will be my people.”

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·oiʹ, dative, sing.; J17,​18,​22(Heb.), leheh·khalʹ, “to the palace (temple) of.”
====

[[v47-6-17]]

^<<v47-6-17,17>>^ “‘Therefore get out from among them, and separate yourselves,’ says Jehovah,^&#42;1^ ‘and quit touching the unclean thing’”; “‘and I will take YOU in.’”

[NOTE]
====
. See App 1D.
====

[[v47-6-18]]

^<<v47-6-18,18>>^ “‘And I shall be a father to YOU, and YOU will be sons and daughters to me,’ says Jehovah^&#42;1^ the Almighty.”

[NOTE]
====
. See App 1D.
====

'''

xref:047-2-corinthians/047-2-corinthians-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-007.adoc#v47-7-0[Próximo Capítulo &#62;]