include::./index.adoc[]

[[v47-5-0]]
=== The Second to the Corinthians, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-5-1]]

^<<v47-5-1,1>>^ For we know that if our earthly house, this tent, should be dissolved, we are to have a building from God, a house not made with hands, everlasting in the heavens.

[[v47-5-2]]

^<<v47-5-2,2>>^ For in this dwelling house we do indeed groan, earnestly desiring to put on the one for us from heaven,

[[v47-5-3]]

^<<v47-5-3,3>>^ so that, having really put it on, we shall not be found naked.

[[v47-5-4]]

^<<v47-5-4,4>>^ In fact, we who are in this tent groan, being weighed down; because we want, not to put it off, but to put on the other, that what is mortal may be swallowed up by life.

[[v47-5-5]]

^<<v47-5-5,5>>^ Now he that produced us for this very thing is God, who gave us the token of what is to come,^&#42;1^ that is, the spirit.

[NOTE]
====
. Or, “gave us the earnest money (down payment) of what is to come.” See 1:22 ftn.
====

[[v47-5-6]]

^<<v47-5-6,6>>^ We are therefore always of good courage and know that, while we have our home in the body, we are absent from the Lord,

[[v47-5-7]]

^<<v47-5-7,7>>^ for we are walking by faith, not by sight.

[[v47-5-8]]

^<<v47-5-8,8>>^ But we are of good courage and are well pleased rather to become absent from the body and to make our home with the Lord.

[[v47-5-9]]

^<<v47-5-9,9>>^ Therefore we are also making it our aim that, whether having our home with him or being absent from him, we may be acceptable to him.

[[v47-5-10]]

^<<v47-5-10,10>>^ For we must all be made manifest before the judgment seat of the Christ, that each one may get his award for the things done through the body, according to the things he has practiced, whether it is good or vile.

[[v47-5-11]]

^<<v47-5-11,11>>^ Knowing, therefore, the fear of the Lord, we keep persuading men, but we have been made manifest to God. However, I hope that we have been made manifest also to YOUR consciences.

[[v47-5-12]]

^<<v47-5-12,12>>^ We are not again recommending ourselves to YOU, but giving YOU an inducement for boasting in respect to us, that YOU may have &#91;an answer&#93; for those who boast over the outward appearance but not over the heart.

[[v47-5-13]]

^<<v47-5-13,13>>^ For if we were out of our mind, it was for God; if we are sound in mind, it is for YOU.

[[v47-5-14]]

^<<v47-5-14,14>>^ For the love the Christ has^&#42;1^ compels us, because this is what we have judged, that one man died for all; so, then, all had died;

[NOTE]
====
. Or, “love of the Christ.”
====

[[v47-5-15]]

^<<v47-5-15,15>>^ and he died for all that those who live might live no longer for themselves, but for him who died for them and was raised up.

[[v47-5-16]]

^<<v47-5-16,16>>^ Consequently from now on we know no man according to the flesh. Even if we have known Christ according to the flesh, certainly we now know him so no more.

[[v47-5-17]]

^<<v47-5-17,17>>^ Consequently if anyone is in union with Christ, he is a new creation;^&#42;1^ the old things passed away, look! new things have come into existence.

[NOTE]
====
. Or, “creature.” Gr., ktiʹsis; Lat., cre·a·tuʹra.
====

[[v47-5-18]]

^<<v47-5-18,18>>^ But all things are from God, who reconciled us to himself through Christ and gave us the ministry of the reconciliation,

[[v47-5-19]]

^<<v47-5-19,19>>^ namely, that God was by means of Christ reconciling a world to himself, not reckoning to them their trespasses, and he committed the word of the reconciliation to us.

[[v47-5-20]]

^<<v47-5-20,20>>^ We are therefore ambassadors substituting for^&#42;1^ Christ, as though God were making entreaty through us. As substitutes for Christ we beg: “Become reconciled to God.”

[NOTE]
====
. Or, “instead of; in the name of.”
====

[[v47-5-21]]

^<<v47-5-21,21>>^ The one who did not know sin he made to be sin^&#42;1^ for us, that we might become God’s righteousness by means of him.

[NOTE]
====
. Or, “a sin offering.” Gr., ha·mar·tiʹan; J17,​18,​22(Heb.), lechat·taʼthʹ, “as a sin offering,” as in M in Le 4:3.
====

'''

xref:047-2-corinthians/047-2-corinthians-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-006.adoc#v47-6-0[Próximo Capítulo &#62;]