include::./index.adoc[]

[[v47-10-0]]
=== The Second to the Corinthians, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-10-1]]

^<<v47-10-1,1>>^ Now I myself, Paul, entreat YOU by the mildness and kindness^&#42;1^ of the Christ, lowly though I am in appearance among YOU, whereas when absent I am bold toward YOU.

[NOTE]
====
. Or, “reasonableness.” Lit., “yieldingness.” Gr., e·pi·ei·kiʹas; Lat., mo·deʹsti·am.
====

[[v47-10-2]]

^<<v47-10-2,2>>^ Indeed I beg that, when present, I may not use boldness with that confidence with which I am counting on taking bold measures against some who appraise us as if we walked according to &#91;what we are in the&#93; flesh.

[[v47-10-3]]

^<<v47-10-3,3>>^ For though we walk in the flesh, we do not wage warfare^&#42;1^ according to &#91;what we are in the&#93; flesh.

[NOTE]
====
. “We do not wage warfare.” Lit., “we are not doing military service.” Gr., ou . . . stra·teu·oʹme·tha; Lat., non . . . mi·li·taʹmus.
====

[[v47-10-4]]

^<<v47-10-4,4>>^ For the weapons of our warfare are not fleshly, but powerful by God for overturning strongly entrenched things.

[[v47-10-5]]

^<<v47-10-5,5>>^ For we are overturning reasonings and every lofty thing raised up against the knowledge of God; and we are bringing every thought into captivity to make it obedient to the Christ;

[[v47-10-6]]

^<<v47-10-6,6>>^ and we are holding ourselves in readiness to inflict punishment for every disobedience, as soon as YOUR own obedience has been fully carried out.

[[v47-10-7]]

^<<v47-10-7,7>>^ YOU look at things according to their face value. If anyone trusts in himself that he belongs to Christ, let him again take this fact into account for himself, that, just as he belongs to Christ, so do we also.

[[v47-10-8]]

^<<v47-10-8,8>>^ For even if I should boast a bit too much about the authority that the Lord gave us to build YOU up and not to tear YOU down, I would not be put to shame,

[[v47-10-9]]

^<<v47-10-9,9>>^ that I may not seem to want to terrify YOU by &#91;my&#93; letters.

[[v47-10-10]]

^<<v47-10-10,10>>^ For, say they: “&#91;His&#93; letters are weighty and forceful, but &#91;his&#93; presence^&#42;1^ in person is weak and &#91;his&#93; speech contemptible.”

[NOTE]
====
. See App 5B.
====

[[v47-10-11]]

^<<v47-10-11,11>>^ Let such a man take this into account, that what we are in our word by letters when absent, such we shall also be in action when present.

[[v47-10-12]]

^<<v47-10-12,12>>^ For we do not dare to class ourselves among some or compare ourselves with some who recommend themselves. Certainly they in measuring themselves by themselves and comparing themselves with themselves have no understanding.

[[v47-10-13]]

^<<v47-10-13,13>>^ For our part we will boast, not outside our assigned boundaries, but according to the boundary of the territory that God apportioned to us by measure, making it reach even as far as YOU.

[[v47-10-14]]

^<<v47-10-14,14>>^ Really we are not overstretching ourselves as if we did not reach to YOU, for we were the first to come even as far as YOU in declaring the good news about the Christ.

[[v47-10-15]]

^<<v47-10-15,15>>^ No, we are not boasting outside our assigned boundaries in the labors of someone else, but we entertain hope that, as YOUR faith is being increased, we may be made great among YOU with reference to our territory. Then we will abound still more,

[[v47-10-16]]

^<<v47-10-16,16>>^ to declare the good news to the countries beyond YOU, so as not to boast in someone else’s territory where things are already prepared.

[[v47-10-17]]

^<<v47-10-17,17>>^ “But he that boasts, let him boast in Jehovah.”^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v47-10-18]]

^<<v47-10-18,18>>^ For not the one who recommends himself is approved, but the man whom Jehovah^&#42;1^ recommends.

[NOTE]
====
. See App 1D.
====

'''

xref:047-2-corinthians/047-2-corinthians-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-011.adoc#v47-11-0[Próximo Capítulo &#62;]