include::./index.adoc[]

[[v47-12-0]]
=== The Second to the Corinthians, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-12-1]]

^<<v47-12-1,1>>^ I have to boast. It is not beneficial; but I shall pass on to supernatural visions and revelations of &#91;the&#93; Lord.

[[v47-12-2]]

^<<v47-12-2,2>>^ I know a man in union with Christ who, fourteen years ago—whether in the body I do not know, or out of the body I do not know; God knows—was caught away as such to the third heaven.

[[v47-12-3]]

^<<v47-12-3,3>>^ Yes, I know such a man—whether in the body or apart from the body, I do not know,^&#42;1^ God knows—

[NOTE]
====
. “I do not know.” B omits.
====

[[v47-12-4]]

^<<v47-12-4,4>>^ that he was caught away into paradise^&#42;1^ and heard unutterable words which it is not lawful for a man to speak.

[NOTE]
====
. “Paradise,” P46אBVgSypJ11,​17,​18; J22, “garden of Eden.”
====

[[v47-12-5]]

^<<v47-12-5,5>>^ Over such a man^&#42;1^ I will boast, but I will not boast over myself, except as respects &#91;my&#93; weaknesses.

[NOTE]
====
. Or, “thing,” that is, experience.
====

[[v47-12-6]]

^<<v47-12-6,6>>^ For if I ever do want to boast, I shall not be unreasonable, for I shall say the truth. But I abstain, in order that no one should put to my credit more than what he sees I am or he hears from me,

[[v47-12-7]]

^<<v47-12-7,7>>^ just because of the excess^&#42;1^ of the revelations.
Therefore, that I might not feel overly exalted, there was given me a thorn^&#42;2^ in the flesh, an angel of Satan, to keep slapping me, that I might not be overly exalted.

[NOTE]
====
. Or, “excellence.”
. Or, “pointed stake.”
====

[[v47-12-8]]

^<<v47-12-8,8>>^ In this behalf I three times entreated the Lord that it might depart from me;

[[v47-12-9]]

^<<v47-12-9,9>>^ and yet he really said to me: “My undeserved kindness is sufficient for you; for &#91;my&#93; power is being made perfect in weakness.” Most gladly, therefore, will I rather boast as respects my weaknesses, that the power of the Christ may like a tent remain over me.

[[v47-12-10]]

^<<v47-12-10,10>>^ Therefore I take pleasure in weaknesses, in insults, in cases of need, in persecutions and difficulties, for Christ. For when I am weak, then I am powerful.

[[v47-12-11]]

^<<v47-12-11,11>>^ I have become unreasonable. YOU compelled me to, for I ought to have been recommended by YOU. For I did not prove to be inferior to &#91;YOUR&#93; superfine apostles in a single thing, even if I am nothing.

[[v47-12-12]]

^<<v47-12-12,12>>^ Indeed, the signs of an apostle were produced among YOU by all endurance, and by signs and portents and powerful works.^&#42;1^

[NOTE]
====
. Or, “and miracles.”
====

[[v47-12-13]]

^<<v47-12-13,13>>^ For in what respect is it that YOU became less than the rest of the congregations, except that I myself did not become a burden to YOU? Kindly forgive me this wrong.

[[v47-12-14]]

^<<v47-12-14,14>>^ Look! This is the third time I am ready to come to YOU, and yet I will not become a burden. For I am seeking, not YOUR possessions, but YOU; for the children ought not to lay up for &#91;their&#93; parents, but the parents for &#91;their&#93; children.

[[v47-12-15]]

^<<v47-12-15,15>>^ For my part I will most gladly spend and be completely spent for YOUR souls. If I love YOU the more abundantly, am I to be loved the less?

[[v47-12-16]]

^<<v47-12-16,16>>^ But be that as it may, I did not burden YOU down. Nevertheless, YOU say, I was “crafty” and I caught YOU “by trickery.”

[[v47-12-17]]

^<<v47-12-17,17>>^ As for any one of those I have dispatched to YOU, I did not take advantage of YOU through him, did I?

[[v47-12-18]]

^<<v47-12-18,18>>^ I urged Titus and I dispatched the brother with him. Titus did not take advantage of YOU at all, did he? We walked in the same spirit, did we not? In the same footsteps, did we not?

[[v47-12-19]]

^<<v47-12-19,19>>^ Have YOU been thinking all this while that we have been making our defense to YOU? It is before God that we are speaking in connection with Christ. But, beloved ones, all things are for YOUR upbuilding.

[[v47-12-20]]

^<<v47-12-20,20>>^ For I am afraid that somehow, when I arrive, I may find YOU not as I could wish and I may prove to be to YOU not as YOU could wish, but, instead, there should somehow be strife, jealousy, cases of anger, contentions, backbitings, whisperings, cases of being puffed up, disorders.

[[v47-12-21]]

^<<v47-12-21,21>>^ Perhaps, when I come again, my God might humiliate me among YOU, and I might mourn over many of those who formerly sinned but have not repented over their uncleanness^&#42;1^ and fornication^&#42;2^ and loose conduct^&#42;3^ that they have practiced.

[NOTE]
====
. “Uncleanness.” Gr., a·ka·thar·siʹai, dative, sing.; J17,​22(Heb.), hat·tum·ʼahʹ, “the uncleanness.” See Eze 22:15 and Ga 5:19 ftns, “Uncleanness.”
. See App 5A.
. “Loose conduct.” Gr., a·sel·geiʹai, dative, sing.; Vgc(Lat.), im·pu·di·ciʹti·a; J17,​22(Heb.), haz·zim·mahʹ, “the loose conduct.” See Ga 5:19 ftn, “Conduct.” Compare Le 18:17 ftn.
====

'''

xref:047-2-corinthians/047-2-corinthians-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-013.adoc#v47-13-0[Próximo Capítulo &#62;]