include::./index.adoc[]

[[v47-4-0]]
=== The Second to the Corinthians, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-4-1]]

^<<v47-4-1,1>>^ That is why, since we have this ministry according to the mercy that was shown us, we do not give up;

[[v47-4-2]]

^<<v47-4-2,2>>^ but we have renounced the underhanded things of which to be ashamed, not walking with cunning, neither adulterating the word of God, but by making the truth manifest recommending ourselves to every human conscience in the sight of God.

[[v47-4-3]]

^<<v47-4-3,3>>^ If, now, the good news we declare is in fact veiled, it is veiled among those who are perishing,

[[v47-4-4]]

^<<v47-4-4,4>>^ among whom the god^&#42;1^ of this system of things^&#42;2^ has blinded the minds^&#42;3^ of the unbelievers, that the illumination^&#42;4^ of the glorious good news about the Christ,^&#42;5^ who is the image of God, might not shine through.

[NOTE]
====
. Gr., ho the·osʹ; Lat., deʹus; J17,​18(Heb.), ʼelo·hehʹ; J22(Heb.), ʼel.
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
. Lit., “mental powers.” Gr., no·eʹma·ta; Lat., menʹtes.
. Lit., “the lighting.”
. Or, “of the good news about the glory of the Christ.”
====

[[v47-4-5]]

^<<v47-4-5,5>>^ For we are preaching, not ourselves, but Christ Jesus as Lord, and ourselves as YOUR slaves for Jesus’ sake.

[[v47-4-6]]

^<<v47-4-6,6>>^ For God is he who said: “Let the light shine^&#42;1^ out of darkness,” and he has shone on our hearts to illuminate &#91;them&#93; with the glorious knowledge^&#42;2^ of God by^&#42;3^ the face of Christ.

[NOTE]
====
. Or, “The light will shine.”
. Or, “the knowledge of the glory.”
. Or, “in.”
====

[[v47-4-7]]

^<<v47-4-7,7>>^ However, we have this treasure in earthen vessels,^&#42;1^ that the power beyond what is normal may be God’s and not that out of ourselves.

[NOTE]
====
. Lit., “in baked clay vessels.”
====

[[v47-4-8]]

^<<v47-4-8,8>>^ We are pressed in every way, but not cramped beyond movement; we are perplexed, but not absolutely with no way out;

[[v47-4-9]]

^<<v47-4-9,9>>^ we are persecuted, but not left in the lurch; we are thrown down, but not destroyed.

[[v47-4-10]]

^<<v47-4-10,10>>^ Always we endure everywhere in our body the death-dealing treatment given to Jesus,^&#42;1^ that the life of Jesus may also be made manifest in our body.

[NOTE]
====
. Or, “in our body the putting of Jesus to death.”
====

[[v47-4-11]]

^<<v47-4-11,11>>^ For we who live are ever being brought face to face with death^&#42;1^ for Jesus’ sake, that the life of Jesus may also be made manifest in our mortal flesh.

[NOTE]
====
. Or, “being delivered to death.”
====

[[v47-4-12]]

^<<v47-4-12,12>>^ Consequently death is at work in us, but life in YOU.

[[v47-4-13]]

^<<v47-4-13,13>>^ Now because we have the same spirit of faith as that of which it is written: “I exercised faith, therefore I spoke,” we too exercise faith and therefore we speak,

[[v47-4-14]]

^<<v47-4-14,14>>^ knowing that he who raised Jesus^&#42;1^ up will raise us up also together with Jesus and will present us together with YOU.

[NOTE]
====
. “Jesus,” P46BVg; אCDSyh, “the Lord Jesus.”
====

[[v47-4-15]]

^<<v47-4-15,15>>^ For all things are for YOUR sakes, in order that the undeserved kindness which was multiplied should abound because of the thanksgiving of many more to the glory of God.

[[v47-4-16]]

^<<v47-4-16,16>>^ Therefore we do not give up, but even if the man we are outside is wasting away, certainly the man we are inside is being renewed from day to day.

[[v47-4-17]]

^<<v47-4-17,17>>^ For though the tribulation is momentary and light, it works out for us a glory that is of more and more surpassing weight and is everlasting;

[[v47-4-18]]

^<<v47-4-18,18>>^ while we keep our eyes, not on the things seen, but on the things unseen. For the things seen are temporary, but the things unseen are everlasting.

'''

xref:047-2-corinthians/047-2-corinthians-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-005.adoc#v47-5-0[Próximo Capítulo &#62;]