include::./index.adoc[]

[[v47-8-0]]
=== The Second to the Corinthians, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-8-1]]

^<<v47-8-1,1>>^ Now we let YOU know, brothers, about the undeserved kindness of God that has been bestowed upon the congregations of Mac·e·doʹni·a,

[[v47-8-2]]

^<<v47-8-2,2>>^ that during a great test under affliction their abundance of joy and their deep poverty made the riches of their generosity abound.

[[v47-8-3]]

^<<v47-8-3,3>>^ For according to their actual ability, yes, I testify, beyond their actual ability this was,

[[v47-8-4]]

^<<v47-8-4,4>>^ while they of their own accord kept begging us with much entreaty for the &#91;privilege of&#93; kindly giving and for a share in the ministry destined for the holy ones.

[[v47-8-5]]

^<<v47-8-5,5>>^ And not merely as we had hoped, but first they gave themselves to the Lord and to us through God’s will.

[[v47-8-6]]

^<<v47-8-6,6>>^ This led us to encourage Titus that, just as he had been the one to initiate it among YOU, so too he should complete this same kind giving on YOUR part.

[[v47-8-7]]

^<<v47-8-7,7>>^ Nevertheless, just as YOU are abounding in everything, in faith and word and knowledge and all earnestness and in this love of ours to YOU, may YOU also abound in this kind giving.

[[v47-8-8]]

^<<v47-8-8,8>>^ It is not in the way of commanding YOU, but in view of the earnestness of others and to make a test of the genuineness of YOUR love, that I am speaking.

[[v47-8-9]]

^<<v47-8-9,9>>^ For YOU know the undeserved kindness of our Lord Jesus Christ,^&#42;1^ that though he was rich he became poor for YOUR sakes, that YOU might become rich through his poverty.

[NOTE]
====
. “Christ.” B omits.
====

[[v47-8-10]]

^<<v47-8-10,10>>^ And in this I render an opinion: for this matter is of benefit to YOU, seeing that already a year ago YOU initiated not only the doing but also the wanting &#91;to do&#93;;

[[v47-8-11]]

^<<v47-8-11,11>>^ now, then, finish up also the doing of it, in order that, just as there was a readiness to want to do, so also there should be a finishing up of it out of what YOU have.^&#42;1^

[NOTE]
====
. Or, “of it as you are able.”
====

[[v47-8-12]]

^<<v47-8-12,12>>^ For if the readiness is there first, it is especially acceptable according to what a person has, not according to what a person does not have.

[[v47-8-13]]

^<<v47-8-13,13>>^ For I do not mean for it to be easy for others, but hard on YOU;

[[v47-8-14]]

^<<v47-8-14,14>>^ but that by means of an equalizing YOUR surplus just now might offset their deficiency, in order that their surplus might also come to offset YOUR deficiency, that an equalizing might take place.

[[v47-8-15]]

^<<v47-8-15,15>>^ Just as it is written: “The person with much did not have too much, and the person with little did not have too little.”

[[v47-8-16]]

^<<v47-8-16,16>>^ Now thanks be to God for putting the same earnestness for YOU in the heart of Titus,

[[v47-8-17]]

^<<v47-8-17,17>>^ because he has indeed responded to the encouragement, but, being very earnest, he is going forth of his own accord to YOU.

[[v47-8-18]]

^<<v47-8-18,18>>^ But we are sending along with him the brother whose praise in connection with the good news has spread through all the congregations.

[[v47-8-19]]

^<<v47-8-19,19>>^ Not only that, but he was also appointed by the congregations to be our traveling companion in connection with this kind gift to be administered by us for the glory of the Lord and in proof of our ready mind.

[[v47-8-20]]

^<<v47-8-20,20>>^ Thus we are avoiding having any man find fault with us in connection with this liberal contribution to be administered by us.

[[v47-8-21]]

^<<v47-8-21,21>>^ For we “make honest provision, not only in the sight of Jehovah,^&#42;1^ but also in the sight of men.”

[NOTE]
====
. “Of Jehovah,” J7,​8,​24; אB(Gr.), Ky·riʹou; P46VgSyp, “of God.” See App 1D.
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Moreover, we are sending with them our brother whom we have often proved in many things to be earnest, but now much more earnest due to his great confidence in YOU.

[[v47-8-23]]

^<<v47-8-23,23>>^ If, though, there is any question about Titus, he is a sharer with me and a fellow worker for YOUR interests; or if about our brothers, they are apostles^&#42;1^ of congregations and a glory of Christ.

[NOTE]
====
. Or, “envoys; men sent forth.”
====

[[v47-8-24]]

^<<v47-8-24,24>>^ Therefore demonstrate to them the proof of YOUR love and of what we boasted about YOU, before the face of the congregations.

'''

xref:047-2-corinthians/047-2-corinthians-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-009.adoc#v47-9-0[Próximo Capítulo &#62;]