include::./index.adoc[]

[[v47-13-0]]
=== The Second to the Corinthians, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-13-1]]

^<<v47-13-1,1>>^ This is the third time I am coming to YOU. “At the mouth of two witnesses or of three every matter must be established.”

[[v47-13-2]]

^<<v47-13-2,2>>^ I have said previously and, as if present the second time and yet absent now, I say in advance to those who have sinned before and to all the rest, that if ever I come again^&#42;1^ I will not spare,

[NOTE]
====
. Or, “come back.”
====

[[v47-13-3]]

^<<v47-13-3,3>>^ since YOU are seeking a proof of Christ speaking in me, &#91;Christ&#93; who is not weak toward YOU but is powerful among YOU.

[[v47-13-4]]

^<<v47-13-4,4>>^ True, indeed, he was impaled^&#42;1^ owing to weakness, but he is alive owing to God’s power. True, also, we are weak with him, but we shall live together with him owing to God’s power toward YOU.^&#42;2^

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
. “Toward you.” B omits.
====

[[v47-13-5]]

^<<v47-13-5,5>>^ Keep testing whether YOU are in the faith, keep proving what YOU yourselves are. Or do YOU not recognize that Jesus Christ is in union with YOU? Unless YOU are disapproved.

[[v47-13-6]]

^<<v47-13-6,6>>^ I truly hope YOU will come to know we are not disapproved.

[[v47-13-7]]

^<<v47-13-7,7>>^ Now we pray to God that YOU may do nothing wrong, not that we ourselves may appear approved, but that YOU may be doing what is fine, though we ourselves may appear disapproved.

[[v47-13-8]]

^<<v47-13-8,8>>^ For we can do nothing against the truth, but only for the truth.

[[v47-13-9]]

^<<v47-13-9,9>>^ We certainly rejoice whenever we are weak but YOU are powerful; and for this we are praying, YOUR being readjusted.^&#42;1^

[NOTE]
====
. Or, “brought into proper alignment.”
====

[[v47-13-10]]

^<<v47-13-10,10>>^ That is why I write these things while absent, that, when I am present, I may not act with severity according to the authority that the Lord gave me, to build up and not to tear down.

[[v47-13-11]]

^<<v47-13-11,11>>^ Finally, brothers, continue to rejoice, to be readjusted, to be comforted, to think in agreement, to live peaceably; and the God of love and of peace will be with YOU.

[[v47-13-12]]

^<<v47-13-12,12>>^ Greet one another with a holy kiss.

[[v47-13-13]]

^<<v47-13-13,13>>^ All the holy ones send YOU their greetings.

[[v47-13-14]]

^<<v47-13-14,14>>^ The undeserved kindness of the Lord Jesus Christ^&#42;1^ and the love of God and the sharing in the holy spirit be with all of YOU.

[NOTE]
====
. “Christ.” B omits.
====

'''

xref:047-2-corinthians/047-2-corinthians-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatians/048-galatians-001.adoc#v48-1-0[Próximo Capítulo &#62;]