include::./index.adoc[]

[[v47-7-0]]
=== The Second to the Corinthians, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-7-1]]

^<<v47-7-1,1>>^ Therefore, since we have these promises, beloved ones, let us cleanse ourselves of every defilement of flesh and spirit, perfecting holiness in God’s fear.

[[v47-7-2]]

^<<v47-7-2,2>>^ ALLOW room for us.^&#42;1^ We have wronged no one, we have corrupted no one, we have taken advantage of no one.

[NOTE]
====
. Or, “Receive us.”
====

[[v47-7-3]]

^<<v47-7-3,3>>^ I do not say this to condemn YOU. For I have said before that YOU are in our hearts to die and to live with us.

[[v47-7-4]]

^<<v47-7-4,4>>^ I have great freeness of speech^&#42;1^ toward YOU. I have great boasting in regard to YOU. I am filled with comfort, I am overflowing with joy in all our affliction.

[NOTE]
====
. Or, “great boldness.”
====

[[v47-7-5]]

^<<v47-7-5,5>>^ In fact, when we arrived in Mac·e·doʹni·a, our flesh got no relief, but we continued to be afflicted in every manner—there were fights without, fears within.

[[v47-7-6]]

^<<v47-7-6,6>>^ Nevertheless God, who comforts those laid low, comforted us by the presence^&#42;1^ of Titus;

[NOTE]
====
. See App 5B.
====

[[v47-7-7]]

^<<v47-7-7,7>>^ yet not alone by his presence, but also by the comfort with which he had been comforted over YOU, as he brought us word again of YOUR longing, YOUR mourning, YOUR zeal for me; so that I rejoiced yet more.

[[v47-7-8]]

^<<v47-7-8,8>>^ Hence even if I saddened YOU by my letter, I do not regret it. Even if I did at first regret it, (I see that that letter saddened YOU, though but for a little while,)^&#42;1^

[NOTE]
====
. Or, “for an hour.”
====

[[v47-7-9]]

^<<v47-7-9,9>>^ now I rejoice, not because YOU were just saddened, but because YOU were saddened into repenting; for YOU were saddened in a godly way, that YOU might suffer no damage in anything due to us.

[[v47-7-10]]

^<<v47-7-10,10>>^ For sadness in a godly way makes for repentance^&#42;1^ to salvation that is not to be regretted; but the sadness of the world produces death.

[NOTE]
====
. Lit., “change of mind.” Gr., me·taʹnoi·an.
====

[[v47-7-11]]

^<<v47-7-11,11>>^ For, look! this very thing, YOUR being saddened in a godly way, what a great earnestness it produced in YOU, yes, clearing of yourselves, yes, indignation, yes, fear, yes, longing, yes, zeal, yes, righting of the wrong! In every respect YOU demonstrated yourselves to be chaste in this matter.

[[v47-7-12]]

^<<v47-7-12,12>>^ Certainly, although I wrote YOU, I did it, neither for the one who did the wrong, nor for the one who was wronged, but that YOUR earnestness for us might be made manifest among YOU in the sight of God.

[[v47-7-13]]

^<<v47-7-13,13>>^ That is why we have been comforted.
However, in addition to our comfort we rejoiced still more abundantly due to the joy of Titus, because his spirit has been refreshed by all of YOU.

[[v47-7-14]]

^<<v47-7-14,14>>^ For if I have made any boast to him about YOU, I have not been put to shame; but as we have spoken all things to YOU in truth, so also our boasting before Titus has proved to be true.

[[v47-7-15]]

^<<v47-7-15,15>>^ Also, his tender affections are more abundant toward YOU, while he calls to mind the obedience of all of YOU, how YOU received him with fear and trembling.

[[v47-7-16]]

^<<v47-7-16,16>>^ I rejoice that in every way I may have good courage by reason of YOU.

'''

xref:047-2-corinthians/047-2-corinthians-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-008.adoc#v47-8-0[Próximo Capítulo &#62;]