include::./index.adoc[]

[[v47-2-0]]
=== The Second to the Corinthians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v47-2-1]]

^<<v47-2-1,1>>^ For this is what I have decided for myself, not to come to YOU again in sadness.

[[v47-2-2]]

^<<v47-2-2,2>>^ For if I make YOU sad, who indeed is there to cheer me except the one that is made sad by me?

[[v47-2-3]]

^<<v47-2-3,3>>^ And so I wrote this very thing, that, when I come, I may not get sad because of those over whom I ought to rejoice; because I have confidence in all of YOU that the joy I have is that of all of YOU.

[[v47-2-4]]

^<<v47-2-4,4>>^ For out of much tribulation and anguish of heart I wrote YOU with many tears, not that YOU might be saddened, but that YOU might know the love that I have more especially for YOU.

[[v47-2-5]]

^<<v47-2-5,5>>^ Now if anyone has caused sadness, he has saddened, not me, but all of YOU to an extent—not to be too harsh in what I say.

[[v47-2-6]]

^<<v47-2-6,6>>^ This rebuke given by the majority is sufficient for such a man,

[[v47-2-7]]

^<<v47-2-7,7>>^ so that, on the contrary now, YOU should kindly forgive and comfort &#91;him&#93;, that somehow such a man may not be swallowed up by his being overly sad.

[[v47-2-8]]

^<<v47-2-8,8>>^ Therefore I exhort YOU to confirm YOUR love for him.

[[v47-2-9]]

^<<v47-2-9,9>>^ For to this end also I write to ascertain the proof of YOU, whether YOU are obedient in all things.

[[v47-2-10]]

^<<v47-2-10,10>>^ Anything YOU kindly forgive anyone, I do too. In fact, as for me, whatever I have kindly forgiven, if I have kindly forgiven anything, it has been for YOUR sakes in Christ’s sight;

[[v47-2-11]]

^<<v47-2-11,11>>^ that we may not be overreached by Satan, for we are not ignorant of his designs.

[[v47-2-12]]

^<<v47-2-12,12>>^ Now when I arrived in Troʹas to declare the good news about the Christ, and a door was opened to me in &#91;the&#93; Lord,

[[v47-2-13]]

^<<v47-2-13,13>>^ I got no relief in my spirit on account of not finding Titus my brother, but I said good-bye to them and departed for Mac·e·doʹni·a.

[[v47-2-14]]

^<<v47-2-14,14>>^ But thanks be to God who always leads us in a triumphal procession in company with the Christ and makes the odor of the knowledge of him perceptible through us in every place!

[[v47-2-15]]

^<<v47-2-15,15>>^ For to God we are a sweet odor of Christ among those who are being saved and among those who are perishing;

[[v47-2-16]]

^<<v47-2-16,16>>^ to the latter ones an odor issuing from death to death, to the former ones an odor issuing from life to life. And who is adequately qualified for these things?

[[v47-2-17]]

^<<v47-2-17,17>>^ &#91;We are;&#93; for we are not peddlers^&#42;1^ of the word of God as many men are, but as out of sincerity, yes, as sent from God, under God’s view, in company with Christ, we are speaking.

[NOTE]
====
. Or, “those who commercialize (make gain); adulterators.”
====

'''

xref:047-2-corinthians/047-2-corinthians-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-003.adoc#v47-3-0[Próximo Capítulo &#62;]