include::./index.adoc[]

[[v66-19-0]]
=== A Revelation to John, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-19-1]]

^<<v66-19-1,1>>^ After these things I heard what was as a loud voice of a great crowd in heaven. They said: “Praise Jah, YOU people!^&#42;1^ The salvation and the glory and the power belong to our God,^&#42;2^

[NOTE]
====
. Or, “Hallelujah.” Gr., Hal·le·lou·i·aʹ; J22(Heb.), ha·lelu·yahʹ. Compare Ps 104:35 ftn, “People.”
. “Our God,” אACVgSyh; TR and some cursive mss, “the Lord our God”; J7,​8,​13,​14,​16,​17, “Jehovah our God.”
====

[[v66-19-2]]

^<<v66-19-2,2>>^ because his judgments are true and righteous.^&#42;1^ For he has executed judgment upon the great harlot^&#42;2^ who corrupted the earth with her fornication, and he^&#42;3^ has avenged the blood of his slaves at her hand.”

[NOTE]
====
. “His judgments are true and righteous,” אAVg; J7,​8, “Jehovah is righteous and his judgments are upright.”
. Or, “fornicatrix; prostitute.” Gr., porʹnen. See App 5A.
. “He,” אAVgSyh; eight mss from Nos. 95-217, “the Lord”; J7,​8, “Jehovah.”
====

[[v66-19-3]]

^<<v66-19-3,3>>^ And right away for the second time they said: “Praise Jah, YOU people!^&#42;1^ And the smoke from her goes on ascending forever and ever.”

[NOTE]
====
. See vs 1 ftn, “People.”
====

[[v66-19-4]]

^<<v66-19-4,4>>^ And the twenty-four elders^&#42;1^ and the four living creatures fell down and worshiped God seated upon the throne, and said: “Amen! Praise Jah, YOU people!”^&#42;2^

[NOTE]
====
. Gr., pre·sbyʹte·roi.
. Or, “Amen! Hallelujah!” See vs 1 ftn, “People.”
====

[[v66-19-5]]

^<<v66-19-5,5>>^ Also, a voice issued forth from the throne and said: “Be praising our God, all YOU his slaves, who fear him, the small ones and the great.”

[[v66-19-6]]

^<<v66-19-6,6>>^ And I heard what was as a voice of a great crowd and as a sound of many^&#42;1^ waters and as a sound of heavy thunders. They said: “Praise Jah, YOU people,^&#42;2^ because Jehovah^&#42;3^ our^&#42;4^ God, the Almighty, has begun to rule as king.

[NOTE]
====
. Or, “great.”
. See vs 1 ftn, “People.”
. See App 1D.
. “Our.” A omits.
====

[[v66-19-7]]

^<<v66-19-7,7>>^ Let us rejoice and be overjoyed, and let us give him the glory, because the marriage of the Lamb has arrived and his wife has prepared herself.

[[v66-19-8]]

^<<v66-19-8,8>>^ Yes, it has been granted to her to be arrayed in bright, clean, fine linen, for the fine linen stands for the righteous acts of the holy ones.”

[[v66-19-9]]

^<<v66-19-9,9>>^ And he tells me: “Write: Happy are those invited^&#42;1^ to the evening meal of the Lamb’s marriage.”^&#42;2^ Also, he tells me: “These are the true sayings of God.”

[NOTE]
====
. “Those invited.” Lit., “(ones) having been called.”
. “Evening meal of the Lamb’s marriage,” AVgSyh; א, “evening meal of the Lamb.”
====

[[v66-19-10]]

^<<v66-19-10,10>>^ At that I fell down before his feet to worship him. But he tells me: “Be careful! Do not do that! All I am is a fellow slave of you and of your brothers who have the work of witnessing to Jesus. Worship God; for the bearing witness^&#42;1^ to Jesus is what inspires^&#42;2^ prophesying.”^&#42;3^

[NOTE]
====
. “Bearing witness.” Gr., mar·ty·riʹa; Lat., te·sti·moʹni·um.
. Or, “is the spirit of.”
. Or, “the prophecy.”
====

[[v66-19-11]]

^<<v66-19-11,11>>^ And I saw the heaven opened, and, look! a white horse. And the one seated upon it is called^&#42;1^ Faithful and True, and he judges and carries on war in righteousness.

[NOTE]
====
. “Called.” A omits.
====

[[v66-19-12]]

^<<v66-19-12,12>>^ His eyes are a fiery flame, and upon his head are many diadems. He has a name written that no one knows but he himself,

[[v66-19-13]]

^<<v66-19-13,13>>^ and he is arrayed with an outer garment sprinkled with blood, and the name he is called is The Word of God.

[[v66-19-14]]

^<<v66-19-14,14>>^ Also, the armies that were in heaven were following him on white horses, and they were clothed in white, clean, fine linen.

[[v66-19-15]]

^<<v66-19-15,15>>^ And out of his mouth there protrudes a sharp long sword, that he may strike the nations with it, and he will shepherd them with a rod of iron. He treads too the winepress of the anger of the wrath of God the Almighty.

[[v66-19-16]]

^<<v66-19-16,16>>^ And upon his outer garment, even upon his thigh, he has a name written, King of^&#42;1^ kings and Lord of lords.

[NOTE]
====
. Or, “over; among.”
====

[[v66-19-17]]

^<<v66-19-17,17>>^ I saw also an angel standing in the sun, and he cried out with a loud voice and said to all the birds that fly in midheaven: “Come here, be gathered together to the great evening meal of God,

[[v66-19-18]]

^<<v66-19-18,18>>^ that YOU may eat the fleshy parts of kings and the fleshy parts of military commanders^&#42;1^ and the fleshy parts of strong men and the fleshy parts of horses and of those seated upon them, and the fleshy parts of all, of freemen as well as of slaves and of small ones and great.”

[NOTE]
====
. Or, “chil­i­archs”; each a commander of 1,000 soldiers.
====

[[v66-19-19]]

^<<v66-19-19,19>>^ And I saw the wild beast and the kings of the earth and their armies gathered together to wage the war with the one seated on the horse and with his army.

[[v66-19-20]]

^<<v66-19-20,20>>^ And the wild beast was caught, and along with it the false prophet that performed in front of it the signs with which he misled those who received the mark of the wild beast and those who render worship to its image. While still alive, they both were hurled into the fiery lake that burns with sulphur.

[[v66-19-21]]

^<<v66-19-21,21>>^ But the rest were killed off with the long sword of the one seated on the horse, which &#91;sword&#93; proceeded out of his mouth. And all the birds were filled from the fleshy parts of them.

'''

xref:066-revelation/066-revelation-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-revelation/066-revelation-020.adoc#v66-20-0[Próximo Capítulo &#62;]