include::./index.adoc[]

[[v66-12-0]]
=== A Revelation to John, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-12-1]]

^<<v66-12-1,1>>^ And a great sign was seen in heaven, a woman arrayed with the sun, and the moon was beneath her feet, and on her head was a crown of twelve stars,

[[v66-12-2]]

^<<v66-12-2,2>>^ and she was pregnant. And she cries out in her pains and in her agony to give birth.

[[v66-12-3]]

^<<v66-12-3,3>>^ And another sign was seen in heaven, and, look! a great fiery-colored dragon, with seven heads and ten horns and upon its heads seven diadems;

[[v66-12-4]]

^<<v66-12-4,4>>^ and its tail drags a third of the stars of heaven, and it hurled them down to the earth. And the dragon^&#42;1^ kept standing before the woman who was about to give birth, that, when she did give birth, it might devour her child.

[NOTE]
====
. Gr., draʹkon; Lat., draʹco.
====

[[v66-12-5]]

^<<v66-12-5,5>>^ And she gave birth to a son, a male, who is to shepherd all the nations with an iron rod. And her child was caught away to God and to his throne.

[[v66-12-6]]

^<<v66-12-6,6>>^ And the woman fled into the wilderness, where she has a place prepared by God, that they should feed her there a thousand two hundred and sixty days.

[[v66-12-7]]

^<<v66-12-7,7>>^ And war broke out in heaven: Miʹcha·el^&#42;1^ and his angels battled with the dragon, and the dragon and its angels battled

[NOTE]
====
. Meaning “Who Is Like God?” Gr., Mi·kha·elʹ.
====

[[v66-12-8]]

^<<v66-12-8,8>>^ but it did not prevail, neither was a place found for them any longer in heaven.

[[v66-12-9]]

^<<v66-12-9,9>>^ So down the great dragon was hurled, the original serpent, the one called Devil and Satan, who is misleading the entire inhabited earth;^&#42;1^ he was hurled down to the earth, and his angels were hurled down with him.

[NOTE]
====
. Lit., “the inhabited.” Gr., oi·kou·meʹnen, fem. sing., referring to the earth.
====

[[v66-12-10]]

^<<v66-12-10,10>>^ And I heard a loud voice in heaven say:
“Now have come to pass the salvation^&#42;1^ and the power^&#42;2^ and the kingdom of our God and the authority^&#42;3^ of his Christ, because the accuser of our brothers has been hurled down, who accuses them day and night before our God!

[NOTE]
====
. Or, “victory.”
. “Power.” Gr., dyʹna·mis; Lat., virʹtus; J17(Heb.), weʽuz·zohʹ, “and his strength.”
. “Authority.” Gr., e·xou·siʹa; Lat., po·teʹstas; J17,​18,​22(Heb.), u·mem·sheʹleth, “and the authority of.”
====

[[v66-12-11]]

^<<v66-12-11,11>>^ And they conquered him because of the blood of the Lamb and because of the word of their witnessing, and they did not love their souls^&#42;1^ even in the face of death.^&#42;2^

[NOTE]
====
. Or, “their lives.” Lit., “their soul.”
. Or, “even despite the danger of death.” Lit., “until death.”
====

[[v66-12-12]]

^<<v66-12-12,12>>^ On this account be glad, YOU heavens and YOU who reside in them! Woe for the earth and for the sea, because the Devil has come down to YOU, having great anger, knowing he has a short period of time.”

[[v66-12-13]]

^<<v66-12-13,13>>^ Now when the dragon saw that it was hurled down to the earth, it persecuted the woman that gave birth to the male child.

[[v66-12-14]]

^<<v66-12-14,14>>^ But the two wings of the great eagle were given the woman, that she might fly into the wilderness to her place; there is where she is fed for a time and times and half a time^&#42;1^ away from the face of the serpent.

[NOTE]
====
. Or, “for an appointed time and appointed times and half an appointed time.” Gr., kai·ronʹ kai kai·rousʹ kai heʹmi·sy kai·rouʹ. Compare Da 4:16 ftn; Da 12:7 ftn, “Half.”
====

[[v66-12-15]]

^<<v66-12-15,15>>^ And the serpent disgorged water like a river from its mouth after the woman, to cause her to be drowned by the river.

[[v66-12-16]]

^<<v66-12-16,16>>^ But the earth came to the woman’s help, and the earth opened its mouth and swallowed up the river that the dragon disgorged from its mouth.

[[v66-12-17]]

^<<v66-12-17,17>>^ And the dragon grew wrathful at the woman, and went off to wage war with the remaining ones of her seed, who observe the commandments of God and have the work of bearing witness^&#42;1^ to Jesus.

[NOTE]
====
. “Work of bearing witness.” Gr., mar·ty·riʹan; Lat., te·sti·moʹni·um.
====

'''

xref:066-revelation/066-revelation-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-revelation/066-revelation-013.adoc#v66-13-0[Próximo Capítulo &#62;]