include::./index.adoc[]

[[v66-11-0]]
=== A Revelation to John, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-11-1]]

^<<v66-11-1,1>>^ And a reed^&#42;1^ like a rod was given me as he said: “Get up and measure the temple &#91;sanctuary&#93;^&#42;2^ of God^&#42;3^ and the altar and those worshiping in it.

[NOTE]
====
. “Reed.” Gr., kaʹla·mos; Lat., caʹla·mus; J17,​18,​22(Heb.), qa·nehʹ. Compare Eze 40:5 ftn, “Reed.”
. Or, “the divine habitation (dwelling).” Gr., ton na·onʹ; J17,​18,​22(Heb.), heh·khalʹ, “palace (temple) of.”
. “God,” אAVgSyh; J17, “Jehovah.”
====

[[v66-11-2]]

^<<v66-11-2,2>>^ But as for the courtyard that is outside the temple &#91;sanctuary&#93;, cast it clear out^&#42;1^ and do not measure it, because it has been given to the nations, and they will trample the holy city underfoot for forty-two months.

[NOTE]
====
. Or, “leave it out.”
====

[[v66-11-3]]

^<<v66-11-3,3>>^ And I will cause my two witnesses to prophesy a thousand two hundred and sixty days dressed in sackcloth.”

[[v66-11-4]]

^<<v66-11-4,4>>^ These are &#91;symbolized by&#93; the two olive trees and the two lampstands and are standing before the Lord^&#42;1^ of the earth.

[NOTE]
====
. “The Lord,” אAVgSyh; Vgms and Mi­nus­cule mss 1854, 2053, “God.”
====

[[v66-11-5]]

^<<v66-11-5,5>>^ And if anyone wants to harm them, fire issues forth from their mouths and devours their enemies; and if anyone should want to harm them, in this manner he must be killed.

[[v66-11-6]]

^<<v66-11-6,6>>^ These have the authority to shut up heaven that no rain should fall during the days of their prophesying, and they have authority over^&#42;1^ the waters to turn them into blood and to strike the earth with every sort of plague as often as they wish.

[NOTE]
====
. Gr., e·piʹ, with the genitive case.
====

[[v66-11-7]]

^<<v66-11-7,7>>^ And when they have finished their witnessing, the wild beast that ascends out of the abyss will make war with them and conquer them and kill them.

[[v66-11-8]]

^<<v66-11-8,8>>^ And their corpses will be on the broad way of the great city which is in a spiritual sense called Sodʹom and Egypt, where their Lord was also impaled.^&#42;1^

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v66-11-9]]

^<<v66-11-9,9>>^ And those of the peoples and tribes and tongues and nations will look at their corpses for three and a half days, and they do not let their corpses be laid in a tomb.

[[v66-11-10]]

^<<v66-11-10,10>>^ And those dwelling on the earth rejoice over them and enjoy themselves,^&#42;1^ and they will send gifts to one another, because these two prophets tormented those dwelling on the earth.

[NOTE]
====
. Lit., “are making themselves well-minded.”
====

[[v66-11-11]]

^<<v66-11-11,11>>^ And after the three and a half days spirit of life from God entered into them, and they stood upon their feet, and great fear fell upon those beholding them.

[[v66-11-12]]

^<<v66-11-12,12>>^ And they heard a loud voice out of heaven say to them: “Come on up here.” And they went up^&#42;1^ into heaven in the cloud, and their enemies beheld them.

[NOTE]
====
. Lit., “they stepped up.”
====

[[v66-11-13]]

^<<v66-11-13,13>>^ And in that hour a great earthquake occurred, and a tenth of the city fell; and seven thousand persons^&#42;1^ were killed by^&#42;2^ the earthquake, and the rest became frightened and gave glory to the God of heaven.

[NOTE]
====
. Lit., “seven thousand names of men.”
. Or, “in.”
====

[[v66-11-14]]

^<<v66-11-14,14>>^ The second woe is past. Look! The third woe is coming quickly.

[[v66-11-15]]

^<<v66-11-15,15>>^ And the seventh angel blew his trumpet. And loud voices occurred in heaven, saying: “The kingdom of the world^&#42;1^ did become the kingdom of our Lord and of his Christ, and he will rule as king^&#42;2^ forever and ever.”

[NOTE]
====
. “Of the world.” Gr., tou koʹsmou; Lat., munʹdi; J17(Heb.), ha·ʽoh·lamʹ.
. Lit., “he will reign.”
====

[[v66-11-16]]

^<<v66-11-16,16>>^ And the twenty-four elders^&#42;1^ who were seated before God upon their thrones fell upon their faces and worshiped God,

[NOTE]
====
. Gr., pre·sbyʹte·roi.
====

[[v66-11-17]]

^<<v66-11-17,17>>^ saying: “We thank you, Jehovah^&#42;1^ God, the Almighty, the One who is and who was, because you have taken your great power and begun ruling as king.

[NOTE]
====
. See App 1D.
====

[[v66-11-18]]

^<<v66-11-18,18>>^ But the nations became wrathful, and your own wrath came, and the appointed time for the dead to be judged, and to give &#91;their&#93; reward to your slaves the prophets and to the holy ones and to those fearing your name, the small and the great, and to bring to ruin those ruining^&#42;1^ the earth.”

[NOTE]
====
. Lit., “corrupting through.”
====

[[v66-11-19]]

^<<v66-11-19,19>>^ And the temple &#91;sanctuary&#93;^&#42;1^ of God^&#42;2^ that is in heaven was opened, and the ark of his covenant was seen in his temple &#91;sanctuary&#93;. And there occurred lightnings and voices and thunders and an earthquake and a great hail.

[NOTE]
====
. Or, “the divine habitation (dwelling).” Gr., ho na·osʹ; J17,​18,​22(Heb.), heh·khalʹ, “palace (temple) of.”
. “God,” אAVgSyh; J17, “Jehovah.”
====

'''

xref:066-revelation/066-revelation-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-revelation/066-revelation-012.adoc#v66-12-0[Próximo Capítulo &#62;]