include::./index.adoc[]

[[v66-10-0]]
=== A Revelation to John, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-10-1]]

^<<v66-10-1,1>>^ And I saw another strong angel descending^&#42;1^ from heaven, arrayed with a cloud, and a rainbow was upon his head, and his face was as the sun, and his feet were as fiery pillars,

[NOTE]
====
. Lit., “stepping down.”
====

[[v66-10-2]]

^<<v66-10-2,2>>^ and he had in his hand a little scroll^&#42;1^ opened. And he set his right foot upon the sea, but his left one upon the earth,

[NOTE]
====
. Lit., “little booklet.” Gr., bi·bla·riʹdi·on.
====

[[v66-10-3]]

^<<v66-10-3,3>>^ and he cried out with a loud voice just as when a lion roars. And when he cried out, the seven thunders uttered their own voices.

[[v66-10-4]]

^<<v66-10-4,4>>^ Now when the seven thunders spoke, I was at the point of writing; but I heard a voice out of heaven say: “Seal up^&#42;1^ the things the seven thunders spoke, and do not write them down.”

[NOTE]
====
. Or, “Keep secret.”
====

[[v66-10-5]]

^<<v66-10-5,5>>^ And the angel that I saw standing on the sea and on the earth raised his right hand to heaven,

[[v66-10-6]]

^<<v66-10-6,6>>^ and by the One who lives forever and ever, who created the heaven and the things in it and the earth and the things in it and the sea and the things in it,^&#42;1^ he swore: “There will be no delay^&#42;2^ any longer;

[NOTE]
====
. “And the sea and the things in it,” P47אcCVg; א*A omit.
. Lit., “time.” Gr., khroʹnos.
====

[[v66-10-7]]

^<<v66-10-7,7>>^ but in the days of the sounding^&#42;1^ of the seventh angel, when he is about to blow his trumpet, the sacred secret^&#42;2^ of God according to the good news which he declared to his own slaves the prophets is indeed brought to a finish.”

[NOTE]
====
. Or, “voice.” Gr., pho·nesʹ.
. Or, “the mystery.” Gr., to my·steʹri·on.
====

[[v66-10-8]]

^<<v66-10-8,8>>^ And the voice that I heard out of heaven is speaking again with me and saying: “Go, take the opened scroll that is in the hand of the angel who is standing on the sea and on the earth.”

[[v66-10-9]]

^<<v66-10-9,9>>^ And I went away to the angel and told him to give me the little scroll. And he said to me: “Take it and eat it up, and it will make your belly bitter, but in your mouth it will be sweet as honey.”

[[v66-10-10]]

^<<v66-10-10,10>>^ And I took the little scroll out of the hand of the angel and ate it up, and in my mouth it was sweet as honey; but when I had eaten it up, my belly was made bitter.

[[v66-10-11]]

^<<v66-10-11,11>>^ And they say to me: “You must prophesy again with regard to peoples and nations and tongues and many kings.”

'''

xref:066-revelation/066-revelation-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-revelation/066-revelation-011.adoc#v66-11-0[Próximo Capítulo &#62;]