include::./index.adoc[]

[[v66-18-0]]
=== A Revelation to John, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-18-1]]

^<<v66-18-1,1>>^ After these things I saw another angel descending from heaven, with great authority; and the earth was lighted up from his glory.

[[v66-18-2]]

^<<v66-18-2,2>>^ And he cried out with a strong voice, saying: “She has fallen! Babylon^&#42;1^ the Great has fallen, and she has become a dwelling place of demons and a lurking place of every unclean exhalation^&#42;2^ and a lurking place of every unclean and hated bird!

[NOTE]
====
. Gr., Ba·by·lonʹ; J17,​18,​22(Heb.), Ba·velʹ.
. Or, “spirit.”
====

[[v66-18-3]]

^<<v66-18-3,3>>^ For because of the wine of the anger of her fornication^&#42;1^ all the nations have fallen &#91;victim&#93;, and the kings of the earth committed fornication with her, and the traveling merchants of the earth became rich due to the power of her shameless luxury.”

[NOTE]
====
. Or, “For because of the passion-arousing wine of her fornication.” A omits “of the wine.”
====

[[v66-18-4]]

^<<v66-18-4,4>>^ And I heard another voice out of heaven say: “Get out of her, my people, if YOU do not want to share with her in her sins, and if YOU do not want to receive part of her plagues.

[[v66-18-5]]

^<<v66-18-5,5>>^ For her sins have massed together clear up to heaven, and God has called her acts of injustice to mind.

[[v66-18-6]]

^<<v66-18-6,6>>^ Render to her even as she herself rendered, and do to her twice as much, yes, twice the number of the things she did; in the cup in which she put a mixture put twice as much of the mixture for her.

[[v66-18-7]]

^<<v66-18-7,7>>^ To the extent that she glorified herself and lived in shameless luxury, to that extent give her torment and mourning. For in her heart she keeps saying, ‘I sit a queen, and I am no widow, and I shall never see mourning.’

[[v66-18-8]]

^<<v66-18-8,8>>^ That is why in one day her plagues will come, death and mourning and famine, and she will be completely burned with fire, because Jehovah^&#42;1^ God, who judged her, is strong.

[NOTE]
====
. “Jehovah,” J7,​8,​13,​14,​16-18,​22-24; אcCSyh(Gr.), Kyʹri·os; AVg omit. See App 1D.
====

[[v66-18-9]]

^<<v66-18-9,9>>^ “And the kings of the earth who committed fornication with her and lived in shameless luxury will weep and beat themselves in grief over her, when they look at the smoke from the burning of her,

[[v66-18-10]]

^<<v66-18-10,10>>^ while they stand at a distance because of their fear of her torment and say, ‘Too bad, too bad, you great city, Babylon you strong city, because in one hour your judgment has arrived!’

[[v66-18-11]]

^<<v66-18-11,11>>^ “Also, the traveling merchants of the earth are weeping and mourning over her, because there is no one to buy their full stock anymore,

[[v66-18-12]]

^<<v66-18-12,12>>^ a full stock of gold and silver and precious stone and pearls and fine linen and purple and silk and scarlet; and everything in scented wood^&#42;1^ and every sort of ivory object and every sort of object out of most precious wood and of copper and of iron and of marble;

[NOTE]
====
. Or, “thyine wood.”
====

[[v66-18-13]]

^<<v66-18-13,13>>^ also cinnamon and Indian spice^&#42;1^ and incense and perfumed oil and frankincense and wine and olive oil and fine flour and wheat and cattle and sheep, and horses and coaches and slaves^&#42;2^ and human souls.^&#42;3^

[NOTE]
====
. Or, “amomum,” an Indian spice plant.
. Lit., “bodies.”
. Or, “slaves, even souls of men.”
====

[[v66-18-14]]

^<<v66-18-14,14>>^ Yes, the fine fruit that your soul desired^&#42;1^ has departed from you, and all the dainty things and the gorgeous things have perished from you, and never again will people find them.

[NOTE]
====
. Lit., “fruit of your soul’s desire.”
====

[[v66-18-15]]

^<<v66-18-15,15>>^ “The traveling merchants of these things, who became rich from her, will stand at a distance because of &#91;their&#93; fear of her torment and will weep and mourn,

[[v66-18-16]]

^<<v66-18-16,16>>^ saying, ‘Too bad, too bad—the great city, clothed with fine linen and purple and scarlet, and richly adorned with gold ornament and precious stone and pearl,

[[v66-18-17]]

^<<v66-18-17,17>>^ because in one hour such great riches have been devastated!’
“And every ship captain and every man that voyages anywhere, and sailors and all those who make a living by the sea, stood at a distance

[[v66-18-18]]

^<<v66-18-18,18>>^ and cried out as they looked at the smoke from the burning of her and said, ‘What city is like the great city?’

[[v66-18-19]]

^<<v66-18-19,19>>^ And they threw dust upon their heads and cried out, weeping and mourning, and said, ‘Too bad, too bad—the great city, in which all those having boats at sea became rich by reason of her costliness, because in one hour she has been devastated!’

[[v66-18-20]]

^<<v66-18-20,20>>^ “Be glad over her, O heaven, also YOU holy ones and YOU apostles and YOU prophets, because God has judicially exacted punishment for YOU from her!”

[[v66-18-21]]

^<<v66-18-21,21>>^ And a strong angel lifted up a stone like a great millstone and hurled it into the sea, saying: “Thus with a swift pitch will Babylon the great city be hurled down, and she will never be found again.

[[v66-18-22]]

^<<v66-18-22,22>>^ And the sound of singers who accompany themselves on the harp and of musicians and of flutists and of trumpeters will never be heard in you again, and no craftsman of any trade^&#42;1^ will ever be found in you again, and no sound of a millstone will ever be heard in you again,

[NOTE]
====
. “Of any trade,” CVgSyh; אA omit.
====

[[v66-18-23]]

^<<v66-18-23,23>>^ and no light of a lamp will ever shine in you again, and no voice of a bridegroom and of a bride will ever be heard in you again; because your traveling merchants were the top-ranking men of the earth, for by your spiritistic practice^&#42;1^ all the nations were misled.

[NOTE]
====
. “Spiritistic practice.” Or, “sorcery.” Lit., “druggery.” Gr., phar·ma·kiʹai, dative, sing.
====

[[v66-18-24]]

^<<v66-18-24,24>>^ Yes, in her was found the blood of prophets and of holy ones and of all those who have been slaughtered on the earth.”

'''

xref:066-revelation/066-revelation-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-revelation/066-revelation-019.adoc#v66-19-0[Próximo Capítulo &#62;]