include::./index.adoc[]

[[v66-16-0]]
=== A Revelation to John, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-16-1]]

^<<v66-16-1,1>>^ And I heard a loud voice out of the sanctuary say to the seven angels: “Go and pour out the seven bowls of the anger of God into the earth.”

[[v66-16-2]]

^<<v66-16-2,2>>^ And the first one went off and poured out his bowl into the earth. And a hurtful and malignant ulcer came to be upon the men that had the mark of the wild beast and that were worshiping its image.

[[v66-16-3]]

^<<v66-16-3,3>>^ And the second one poured out his bowl into the sea. And it became blood as of a dead man, and every living soul died, &#91;yes,&#93; the things in the sea.

[[v66-16-4]]

^<<v66-16-4,4>>^ And the third one poured out his bowl into the rivers and the fountains of the waters. And they became blood.

[[v66-16-5]]

^<<v66-16-5,5>>^ And I heard the angel over the waters say: “You,^&#42;1^ the One who is and who was, the loyal One, are righteous, because you have rendered these decisions,

[NOTE]
====
. “You,” אACVgSyh; TR, “You, O Lord”; J7,​8,​13,​14,​16, “You, Jehovah.”
====

[[v66-16-6]]

^<<v66-16-6,6>>^ because they poured out the blood of holy ones and of prophets, and you have given them blood to drink. They deserve it.”

[[v66-16-7]]

^<<v66-16-7,7>>^ And I heard the altar say: “Yes, Jehovah^&#42;1^ God, the Almighty, true and righteous are your judicial decisions.”

[NOTE]
====
. See App 1D.
====

[[v66-16-8]]

^<<v66-16-8,8>>^ And the fourth one poured out his bowl upon the sun; and to &#91;the sun&#93;^&#42;1^ it was granted to scorch the men^&#42;2^ with fire.

[NOTE]
====
. Lit., “to it.”
. Or, “mankind.”
====

[[v66-16-9]]

^<<v66-16-9,9>>^ And the men were scorched with great heat, but they blasphemed the name of God, who has the authority over these plagues, and they did not repent so as to give glory to him.

[[v66-16-10]]

^<<v66-16-10,10>>^ And the fifth one poured out his bowl upon the throne of the wild beast. And its kingdom became darkened, and they began to gnaw their tongues for &#91;their&#93; pain,

[[v66-16-11]]

^<<v66-16-11,11>>^ but they blasphemed the God of heaven for their pains and for their ulcers, and they did not repent of their works.

[[v66-16-12]]

^<<v66-16-12,12>>^ And the sixth one poured out his bowl upon the great river Eu·phraʹtes, and its water was dried up, that the way might be prepared for the kings from the rising of the sun.

[[v66-16-13]]

^<<v66-16-13,13>>^ And I saw three unclean inspired expressions^&#42;1^ &#91;that looked&#93; like frogs come out of the mouth of the dragon and out of the mouth of the wild beast and out of the mouth of the false prophet.^&#42;2^

[NOTE]
====
. Or, “unclean spirits.”
. “False prophet.” Gr., pseu·do·pro·pheʹtou; Lat., pseu·do·pro·pheʹtae; J17,​22(Heb.), neviʼʹ hash·sheʹqer.
====

[[v66-16-14]]

^<<v66-16-14,14>>^ They are, in fact, expressions inspired by^&#42;1^ demons and perform signs, and they go forth to the kings of the entire inhabited earth,^&#42;2^ to gather them together to the war of the great day of God the Almighty.

[NOTE]
====
. Or, “in fact, spirits of.”
. Lit., “inhabited.” Gr., oi·kou·meʹnes, fem. sing., referring to the earth.
====

[[v66-16-15]]

^<<v66-16-15,15>>^ “Look! I am^&#42;1^ coming as a thief. Happy is the one that stays awake and keeps his outer garments, that he may not walk naked and people look upon his shamefulness.”

[NOTE]
====
. “I am,” אcAVgSyh; א*, “He is.”
====

[[v66-16-16]]

^<<v66-16-16,16>>^ And they gathered them together to the place^&#42;1^ that is called in Hebrew Har–Ma·gedʹon.^&#42;2^

[NOTE]
====
. “Place,” אVgSyh; A, “river.”
. Or, “Armageddon.” Gr., Har Ma·ge·donʹ; Lat., Her·ma·geʹdon; J18,​22(Heb.), Har Meghid·dohnʹ, “Mountain of Megiddo.”
====

[[v66-16-17]]

^<<v66-16-17,17>>^ And the seventh one poured out his bowl upon the air. At this a loud voice issued out of the sanctuary from the throne, saying: “It has come to pass!”

[[v66-16-18]]

^<<v66-16-18,18>>^ And lightnings and voices and thunders occurred, and a great earthquake occurred such as had not occurred since men came to be on the earth, so extensive an earthquake, so great.

[[v66-16-19]]

^<<v66-16-19,19>>^ And the great city split into three parts, and the cities of the nations fell; and Babylon^&#42;1^ the Great was remembered in the sight of God, to give her the cup of the wine of the anger of his wrath.

[NOTE]
====
. Gr., Ba·by·lonʹ; J17,​22(Heb.), Ba·velʹ.
====

[[v66-16-20]]

^<<v66-16-20,20>>^ Also, every island fled, and mountains were not found.

[[v66-16-21]]

^<<v66-16-21,21>>^ And a great hail with every stone about the weight of a talent^&#42;1^ descended out of heaven upon the men,^&#42;2^ and the men blasphemed God due to the plague of hail, because the plague of it was unusually great.

[NOTE]
====
. About 20.4 kg (45 lb).
. Or, “mankind.”
====

'''

xref:066-revelation/066-revelation-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-revelation/066-revelation-017.adoc#v66-17-0[Próximo Capítulo &#62;]