include::./index.adoc[]

[[v66-1-0]]
=== A Revelation to John, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-1-1]]

^<<v66-1-1,1>>^ A revelation^&#42;1^ by Jesus Christ, which God gave him, to show his slaves the things that must shortly^&#42;2^ take place. And he sent forth his angel and presented &#91;it&#93; in signs through him to his slave John,

[NOTE]
====
. Lit., “uncovering; disclosure.” Gr., A·po·kaʹly·psis; Lat., A·po·ca·lyʹpsis.
. Lit., “in quickness.”
====

[[v66-1-2]]

^<<v66-1-2,2>>^ who bore witness to the word God gave and to the witness Jesus Christ gave, even to all the things he saw.

[[v66-1-3]]

^<<v66-1-3,3>>^ Happy is he who reads aloud and those who hear the words of this prophecy, and who observe the things written in it; for the appointed time is near.

[[v66-1-4]]

^<<v66-1-4,4>>^ John to the seven congregations that are in the &#91;district of&#93; Asia:
May YOU have undeserved kindness and peace from “The One who is^&#42;1^ and who was and who is coming,” and from the seven spirits that are before his throne,

[NOTE]
====
. Lit., “The Being; The Existing One.” Gr., ho on. See Ex 3:14 ftn.
====

[[v66-1-5]]

^<<v66-1-5,5>>^ and from Jesus Christ, “the Faithful Witness,” “The firstborn from the dead,” and “The Ruler of the kings of the earth.”
To him that loves us and that loosed us from our sins by means of his own blood—

[[v66-1-6]]

^<<v66-1-6,6>>^ and he made us to be a kingdom, priests to his God and Father—yes, to him be the glory and the might forever. Amen.

[[v66-1-7]]

^<<v66-1-7,7>>^ Look! He is coming with the clouds, and every eye will see him, and those who pierced him; and all the tribes of the earth will beat themselves in grief because of him. Yes, Amen.

[[v66-1-8]]

^<<v66-1-8,8>>^ “I am the Alʹpha and the O·meʹga,”^&#42;1^ says Jehovah^&#42;2^ God, “the One who is and who was and who is coming, the Almighty.”^&#42;3^

[NOTE]
====
. Or, “the A and the Z.” Gr., τὸ Ἄλφα καὶ τὸ Ὦ (to Alʹpha kai to O[·meʹga]), the first and last letters of the Gr. alphabet; SyhJ22, “the Aleph and the Taw.”
. See App 1D.
. “The Almighty.” Gr., ho Pan·to·kraʹtor; Lat., O·mniʹpo·tens; J18(Heb.), ʼEl Shad·daiʹ, “God Almighty”; J17,​22(Heb.), ʼElo·hehʹ tseva·ʼohthʹ, “God of armies.” See Ru 1:20 ftn, “Almighty.”
====

[[v66-1-9]]

^<<v66-1-9,9>>^ I John, YOUR brother and a sharer with YOU in the tribulation and kingdom and endurance in company with Jesus, came to be in the isle that is called Patʹmos for speaking about God and bearing witness^&#42;1^ to Jesus.^&#42;2^

[NOTE]
====
. “Bearing witness.” Gr., mar·ty·riʹan; Lat., te·sti·moʹni·um.
. Lit., “through the word of the God and the witness of Jesus.”
====

[[v66-1-10]]

^<<v66-1-10,10>>^ By inspiration^&#42;1^ I came to be in the Lord’s day,^&#42;2^ and I heard behind me a strong voice like that of a trumpet,

[NOTE]
====
. “By inspiration.” Or, “In spirit.” Gr., en pneuʹma·ti; Lat., in spiʹri·tu.
. Or, “I came to be under inspiration on the Lord’s day.”
====

[[v66-1-11]]

^<<v66-1-11,11>>^ saying: “What you see write in a scroll and send it to the seven congregations, in Ephʹe·sus and in Smyrʹna and in Perʹga·mum and in Thy·a·tiʹra and in Sarʹdis and in Philadelphia and in La·o·di·ceʹa.”

[[v66-1-12]]

^<<v66-1-12,12>>^ And I turned to see the voice that was speaking with me, and, having turned, I saw seven golden lampstands,

[[v66-1-13]]

^<<v66-1-13,13>>^ and in the midst of the lampstands someone like a son of man, clothed with a garment that reached down to the feet, and girded at the breasts with a golden girdle.

[[v66-1-14]]

^<<v66-1-14,14>>^ Moreover, his head and his hair were white as white wool, as snow, and his eyes as a fiery flame;

[[v66-1-15]]

^<<v66-1-15,15>>^ and his feet were like fine copper when glowing in a furnace; and his voice was as the sound of many waters.

[[v66-1-16]]

^<<v66-1-16,16>>^ And he had in his right hand seven stars, and out of his mouth a sharp, long two-edged sword was protruding, and his countenance was as the sun when it shines in its power.

[[v66-1-17]]

^<<v66-1-17,17>>^ And when I saw him, I fell as dead at his feet.
And he laid his right hand upon me and said: “Do not be fearful. I am the First^&#42;1^ and the Last,

[NOTE]
====
. “First,” אVgSyh; A, “Firstborn.”
====

[[v66-1-18]]

^<<v66-1-18,18>>^ and the living one; and I became dead, but, look! I am living forever and ever, and I have the keys of death and of Haʹdes.^&#42;1^

[NOTE]
====
. “Hades,” אA; SyhJ7,​8,​13,​16-18,​22, “Sheol.” See App 4B.
====

[[v66-1-19]]

^<<v66-1-19,19>>^ Therefore write down the things you saw, and the things that are and the things that will take place after these.

[[v66-1-20]]

^<<v66-1-20,20>>^ As for the sacred secret of the seven stars that you saw upon my right hand, and &#91;of&#93; the seven golden lampstands: The seven stars mean^&#42;1^ &#91;the&#93; angels of the seven congregations, and the seven lampstands mean seven congregations.

[NOTE]
====
. Or, “are.”
====

'''

xref:065-jude/065-jude-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-revelation/066-revelation-002.adoc#v66-2-0[Próximo Capítulo &#62;]