include::./index.adoc[]

[[v66-8-0]]
=== A Revelation to John, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-8-1]]

^<<v66-8-1,1>>^ And when he opened the seventh seal, a silence occurred in heaven for about a half hour.

[[v66-8-2]]

^<<v66-8-2,2>>^ And I saw the seven angels that stand before God, and seven trumpets were given them.

[[v66-8-3]]

^<<v66-8-3,3>>^ And another angel arrived and stood at the altar, having a golden incense vessel; and a large quantity of incense was given him to offer it with the prayers of all the holy ones upon the golden altar that was before the throne.

[[v66-8-4]]

^<<v66-8-4,4>>^ And the smoke of the incense ascended from the hand of the angel with the prayers of the holy ones before God.

[[v66-8-5]]

^<<v66-8-5,5>>^ But right away the angel took the incense vessel, and he filled it with some of the fire of the altar and hurled it to the earth. And thunders occurred and voices and lightnings and an earthquake.

[[v66-8-6]]

^<<v66-8-6,6>>^ And the seven angels with the seven trumpets prepared to blow them.

[[v66-8-7]]

^<<v66-8-7,7>>^ And the first one blew his trumpet. And there occurred a hail and fire mingled with blood, and it was hurled to the earth; and a third of the earth was burned up, and a third of the trees was burned up, and all the green vegetation was burned up.

[[v66-8-8]]

^<<v66-8-8,8>>^ And the second angel blew his trumpet. And something like a great mountain burning with fire was hurled into the sea. And a third of the sea became blood;

[[v66-8-9]]

^<<v66-8-9,9>>^ and a third of the creatures that are in the sea which have souls^&#42;1^ died, and a third of the boats were wrecked.

[NOTE]
====
. Or, “lives.” Gr., psy·khasʹ; Lat., aʹni·mas.
====

[[v66-8-10]]

^<<v66-8-10,10>>^ And the third angel blew his trumpet. And a great star burning as a lamp fell from heaven, and it fell upon a third of the rivers and upon the fountains of waters.

[[v66-8-11]]

^<<v66-8-11,11>>^ And the name of the star is called Wormwood.^&#42;1^ And a third of the waters turned into wormwood, and many of the men^&#42;2^ died from the waters, because these had been made bitter.

[NOTE]
====
. Or, “Absinthe.”
. Or, “of mankind.”
====

[[v66-8-12]]

^<<v66-8-12,12>>^ And the fourth angel blew his trumpet. And a third of the sun was smitten^&#42;1^ and a third of the moon and a third of the stars, in order that a third of them might be darkened and the day might not have illumination for a third of it, and the night likewise.

[NOTE]
====
. Or, “was eclipsed.”
====

[[v66-8-13]]

^<<v66-8-13,13>>^ And I saw, and I heard an eagle flying in midheaven^&#42;1^ say with a loud voice: “Woe, woe, woe to those dwelling on the earth because of the rest of the trumpet blasts of the three angels who are about to blow their trumpets!”

[NOTE]
====
. Or, “in the meridian; directly overhead.”
====

'''

xref:066-revelation/066-revelation-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-revelation/066-revelation-009.adoc#v66-9-0[Próximo Capítulo &#62;]