include::./index.adoc[]

[[v66-7-0]]
=== A Revelation to John, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-7-1]]

^<<v66-7-1,1>>^ After this I saw four angels standing upon the four corners^&#42;1^ of the earth, holding tight the four winds of the earth, that no wind might blow upon the earth or upon the sea or upon any tree.

[NOTE]
====
. Or, “quarters; extremities.”
====

[[v66-7-2]]

^<<v66-7-2,2>>^ And I saw another angel ascending from the sunrising, having a seal of &#91;the&#93; living God; and he cried with a loud voice to the four angels to whom it was granted to harm the earth and the sea,

[[v66-7-3]]

^<<v66-7-3,3>>^ saying: “Do not harm^&#42;1^ the earth or the sea or the trees, until after we have sealed the slaves of our God in their foreheads.”

[NOTE]
====
. Lit., “You should not treat unrighteously.”
====

[[v66-7-4]]

^<<v66-7-4,4>>^ And I heard the number of those who were sealed,^&#42;1^ a hundred and forty-four thousand, sealed out of every tribe of the sons of Israel:

[NOTE]
====
. Lit., “(ones) having been sealed.”
====

[[v66-7-5]]

^<<v66-7-5,5>>^ Out of the tribe of Judah twelve thousand sealed;
out of the tribe of Reuʹben twelve thousand;
out of the tribe of Gad^&#42;1^ twelve thousand;

[NOTE]
====
. “Gad.” א omits.
====

[[v66-7-6]]

^<<v66-7-6,6>>^ out of the tribe of Ashʹer twelve thousand;
out of the tribe of Naphʹta·li twelve thousand;
out of the tribe of Ma·nasʹseh twelve thousand;

[[v66-7-7]]

^<<v66-7-7,7>>^ out of the tribe of Simʹe·on^&#42;1^ twelve thousand;
out of the tribe of Leʹvi twelve thousand;
out of the tribe of Isʹsa·char twelve thousand;

[NOTE]
====
. “Simeon.” א omits.
====

[[v66-7-8]]

^<<v66-7-8,8>>^ out of the tribe of Zebʹu·lun twelve thousand;
out of the tribe of Joseph twelve thousand;
out of the tribe of Benjamin twelve thousand sealed.

[[v66-7-9]]

^<<v66-7-9,9>>^ After these things I saw, and, look! a great crowd, which no man was able to number, out of all nations^&#42;1^ and tribes and peoples and tongues, standing before the throne and before the Lamb, dressed in white robes; and there were palm branches in their hands.

[NOTE]
====
. Gr., ethʹnous, “ethnic group”; Lat., genʹti·bus, “Gentiles”; J17,​18(Heb.), hag·goh·yimʹ, “the nations (goyim).”
====

[[v66-7-10]]

^<<v66-7-10,10>>^ And they keep on crying with a loud voice, saying: “Salvation^&#42;1^ &#91;we owe&#93; to our God, who is seated on the throne, and to the Lamb.”

[NOTE]
====
. Lit., “The salvation.” Gr., He so·te·riʹa; Lat., saʹlus; J17,​18,​22(Heb.), ha·yeshu·ʽahʹ.
====

[[v66-7-11]]

^<<v66-7-11,11>>^ And all the angels were standing around the throne and the elders^&#42;1^ and the four living creatures, and they fell upon their faces before the throne and worshiped God,

[NOTE]
====
. Gr., pre·sby·teʹron.
====

[[v66-7-12]]

^<<v66-7-12,12>>^ saying: “Amen! The blessing and the glory and the wisdom and the thanksgiving and the honor and the power and the strength &#91;be&#93; to our God forever and ever. Amen.”^&#42;1^

[NOTE]
====
. “Amen.” C omits.
====

[[v66-7-13]]

^<<v66-7-13,13>>^ And in response one of the elders said to me: “These who are dressed in the white robes, who are they and where did they come from?”

[[v66-7-14]]

^<<v66-7-14,14>>^ So right away I said to him: “My lord, you are the one that knows.” And he said to me: “These are the ones that come out of the great tribulation, and they have washed their robes and made them white in the blood of the Lamb.

[[v66-7-15]]

^<<v66-7-15,15>>^ That is why they are before the throne of God; and they are rendering him sacred service^&#42;1^ day and night in his temple;^&#42;2^ and the One seated on the throne will spread his tent over them.

[NOTE]
====
. “They are rendering . . . sacred service.” Gr., la·treuʹou·sin; J22(Heb.), weʽoh·vedhimʹ, “and they are serving (worshiping).” Compare Ex 3:12 ftn.
. Or, “divine habitation (dwelling).” Gr., na·oiʹ, dative, sing.; Lat., temʹplo; J17,​18,​22(Heb.), beheh·kha·lohʹ, “in his palace (temple).”
====

[[v66-7-16]]

^<<v66-7-16,16>>^ They will hunger no more nor thirst anymore, neither will the sun beat down upon them nor any scorching heat,

[[v66-7-17]]

^<<v66-7-17,17>>^ because the Lamb, who is in the midst of the throne, will shepherd them, and will guide them to fountains of waters of life. And God will wipe out every tear from their eyes.”

'''

xref:066-revelation/066-revelation-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-revelation/066-revelation-008.adoc#v66-8-0[Próximo Capítulo &#62;]