include::./index.adoc[]

[[v66-2-0]]
=== A Revelation to John, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-2-1]]

^<<v66-2-1,1>>^ “To the angel of the congregation in Ephʹe·sus write: These are the things that he says who holds the seven stars in his right hand, he who walks in the midst of the seven golden lampstands,

[[v66-2-2]]

^<<v66-2-2,2>>^ ‘I know your deeds, and your labor and endurance, and that you cannot bear bad men, and that you put those to the test who say they are apostles, but they are not, and you found them liars.

[[v66-2-3]]

^<<v66-2-3,3>>^ You are also showing endurance, and you have borne up for my name’s sake and have not grown weary.

[[v66-2-4]]

^<<v66-2-4,4>>^ Nevertheless, I hold &#91;this&#93; against you, that you have left the love you had at first.

[[v66-2-5]]

^<<v66-2-5,5>>^ “‘Therefore remember from what you have fallen, and repent and do the former deeds. If you do not, I am coming to you, and I will remove your lampstand from its place, unless you repent.

[[v66-2-6]]

^<<v66-2-6,6>>^ Still, you do have this, that you hate the deeds of the sect of Nic·o·laʹus,^&#42;1^ which I also hate.

[NOTE]
====
. Or, “deeds of the Nicolaitans.”
====

[[v66-2-7]]

^<<v66-2-7,7>>^ Let the one who has an ear hear what the spirit says to the congregations: To him that conquers I will grant to eat of the tree of life, which is in the paradise^&#42;1^ of God.’

[NOTE]
====
. “Paradise,” אAVgSyhJ11-13,​16; J17,​18,​22, “garden.”
====

[[v66-2-8]]

^<<v66-2-8,8>>^ “And to the angel of the congregation in Smyrʹna write: These are the things that he says, ‘the First and the Last,’ who became dead and came to life &#91;again&#93;,

[[v66-2-9]]

^<<v66-2-9,9>>^ ‘I know your tribulation and poverty—but you are rich—and the blasphemy by those who say they themselves are Jews, and yet they are not but are a synagogue of Satan.

[[v66-2-10]]

^<<v66-2-10,10>>^ Do not be afraid of the things you are about to suffer. Look! The Devil will keep on throwing some of YOU into prison that YOU may be fully put to the test, and that YOU may have tribulation ten days. Prove yourself faithful even to death,^&#42;1^ and I will give you the crown of life.

[NOTE]
====
. Or, “until death; even with the danger of death.”
====

[[v66-2-11]]

^<<v66-2-11,11>>^ Let the one who has an ear hear what the spirit says to the congregations: He that conquers will by no means be harmed by the second death.’

[[v66-2-12]]

^<<v66-2-12,12>>^ “And to the angel of the congregation in Perʹga·mum write: These are the things that he says who has the sharp, long two-edged sword,

[[v66-2-13]]

^<<v66-2-13,13>>^ ‘I know where you are dwelling, that is, where the throne of Satan is; and yet you keep on holding fast my name, and you did not deny your faith in me even in the days of Anʹti·pas, my witness, the faithful one, who was killed by YOUR side, where Satan is dwelling.

[[v66-2-14]]

^<<v66-2-14,14>>^ “‘Nevertheless, I have a few things against you, that you have there those holding fast the teaching of Baʹlaam, who went teaching Baʹlak to put a stumbling block before the sons of Israel, to eat things sacrificed to idols and to commit fornication.

[[v66-2-15]]

^<<v66-2-15,15>>^ So you, also, have those holding fast the teaching of the sect of Nic·o·laʹus^&#42;1^ likewise.

[NOTE]
====
. Or, “teaching of the Nicolaitans.” Gr., di·da·khenʹ Ni·ko·la·i·tonʹ; Lat., doc·triʹnam Ni·co·la·i·taʹrum.
====

[[v66-2-16]]

^<<v66-2-16,16>>^ Therefore repent. If you do not, I am coming to you quickly, and I will war with them with the long sword of my mouth.

[[v66-2-17]]

^<<v66-2-17,17>>^ “‘Let the one who has an ear hear what the spirit says to the congregations: To him that conquers I will give some of the hidden manna,^&#42;1^ and I will give him a white pebble,^&#42;2^ and upon the pebble a new name written which no one knows except the one receiving it.’

[NOTE]
====
. Or, “the manna laid up.”
. Lit., “[voting] pebble.” Gr., pseʹphon. See Ac 26:10 ftn.
====

[[v66-2-18]]

^<<v66-2-18,18>>^ “And to the angel of the congregation in Thy·a·tiʹra write: These are the things that the Son of God says, he who has his eyes like a fiery flame, and his feet are like fine copper,

[[v66-2-19]]

^<<v66-2-19,19>>^ ‘I know your deeds, and your love and faith and ministry^&#42;1^ and endurance, and that your deeds of late are more than those formerly.

[NOTE]
====
. “Ministry.” Gr., di·a·ko·niʹan.
====

[[v66-2-20]]

^<<v66-2-20,20>>^ “‘Nevertheless, I do hold &#91;this&#93; against you, that you tolerate that woman Jezʹe·bel, who calls herself a prophetess, and she teaches and misleads my slaves to commit fornication and to eat things sacrificed to idols.

[[v66-2-21]]

^<<v66-2-21,21>>^ And I gave her time to repent, but she is not willing to repent of her fornication.

[[v66-2-22]]

^<<v66-2-22,22>>^ Look! I am about to throw her into a sickbed, and those committing adultery with her into great tribulation, unless they repent of her deeds.

[[v66-2-23]]

^<<v66-2-23,23>>^ And her children I will kill with deadly plague,^&#42;1^ so that all the congregations will know that I am he who searches the kidneys^&#42;2^ and hearts, and I will give to YOU individually according to YOUR deeds.

[NOTE]
====
. Or, “with death.”
. Or, “deepest emotions.” Lit., “kidneys.” Compare Jer (11:20; 17:10; 20:12).
====

[[v66-2-24]]

^<<v66-2-24,24>>^ “‘However, I say to the rest of YOU who are in Thy·a·tiʹra, all those who do not have this teaching, the very ones who did not get to know the “deep things of Satan,” as they say: I am not putting upon YOU any other burden.

[[v66-2-25]]

^<<v66-2-25,25>>^ Just the same, hold fast what YOU have until I come.

[[v66-2-26]]

^<<v66-2-26,26>>^ And to him that conquers and observes my deeds down to the end^&#42;1^ I will give authority over the nations,

[NOTE]
====
. Or, “complete end.” Gr., teʹlous.
====

[[v66-2-27]]

^<<v66-2-27,27>>^ and he shall shepherd the people with an iron rod so that they will be broken to pieces like clay vessels,^&#42;1^ the same as I have received from my Father,

[NOTE]
====
. Lit., “with an iron rod, as the clay vessels are broken to pieces.”
====

[[v66-2-28]]

^<<v66-2-28,28>>^ and I will give him the morning star.

[[v66-2-29]]

^<<v66-2-29,29>>^ Let the one who has an ear hear what the spirit says to the congregations.’

'''

xref:066-revelation/066-revelation-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-revelation/066-revelation-003.adoc#v66-3-0[Próximo Capítulo &#62;]