include::./index.adoc[]

[[v66-6-0]]
=== A Revelation to John, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-6-1]]

^<<v66-6-1,1>>^ And I saw when the Lamb opened one of the seven seals, and I heard one of the four living creatures say with a voice as of thunder: “Come!”

[[v66-6-2]]

^<<v66-6-2,2>>^ And I saw, and, look! a white horse; and the one seated upon it had a bow; and a crown was given him, and he went forth conquering and to complete his conquest.

[[v66-6-3]]

^<<v66-6-3,3>>^ And when he opened the second seal, I heard the second living creature say: “Come!”

[[v66-6-4]]

^<<v66-6-4,4>>^ And another came forth, a fiery-colored horse; and to the one seated upon it there was granted to take peace away from the earth so that they should slaughter one another; and a great sword was given him.

[[v66-6-5]]

^<<v66-6-5,5>>^ And when he opened the third seal, I heard the third living creature say: “Come!” And I saw, and, look! a black horse; and the one seated upon it had a pair of scales in his hand.

[[v66-6-6]]

^<<v66-6-6,6>>^ And I heard a voice as if in the midst of the four living creatures say: “A quart^&#42;1^ of wheat for a de·narʹi·us,^&#42;2^ and three quarts of barley for a de·narʹi·us; and do not harm the olive oil and the wine.”

[NOTE]
====
. Gr., Khoiʹnix. More than a liter but less than a dry qt.
. A Roman silver coin that weighed 3.85 g (0.124 oz t) and equaled a day’s wage. See Mt 20:2.
====

[[v66-6-7]]

^<<v66-6-7,7>>^ And when he opened the fourth seal, I heard the voice of the fourth living creature say: “Come!”

[[v66-6-8]]

^<<v66-6-8,8>>^ And I saw, and, look! a pale horse; and the one seated upon it had the name Death. And Haʹdes^&#42;1^ was closely following him. And authority was given them over the fourth part of the earth, to kill with a long sword and with food shortage^&#42;2^ and with deadly plague^&#42;3^ and by the wild beasts of the earth.

[NOTE]
====
. “Hades,” אA; SyhJ7,​8,​11-14,​16-18,​22, “Sheol.” See App 4B.
. Lit., “famine.”
. Or, “with death.”
====

[[v66-6-9]]

^<<v66-6-9,9>>^ And when he opened the fifth seal, I saw underneath the altar the souls of those slaughtered because of the word of God and^&#42;1^ because of the witness work^&#42;2^ that they used to have.

[NOTE]
====
. Or, “even.”
. “Witness work.” Lit., “witness.” Gr., mar·ty·riʹan; Lat., te·sti·moʹni·um.
====

[[v66-6-10]]

^<<v66-6-10,10>>^ And they cried with a loud voice, saying: “Until when, Sovereign Lord^&#42;1^ holy and true, are you refraining from judging and avenging our blood upon those who dwell on the earth?”

[NOTE]
====
. “Sovereign Lord.” Gr., ho De·spoʹtes; J17,​22(Heb.), ʼAdho·naiʹ. See App 1E.
====

[[v66-6-11]]

^<<v66-6-11,11>>^ And a white robe was given to each of them; and they were told to rest a little while longer, until the number was filled also of their fellow slaves and their brothers who were about to be killed as they also had been.

[[v66-6-12]]

^<<v66-6-12,12>>^ And I saw when he opened the sixth seal, and a great earthquake occurred; and the sun became black as sackcloth of hair, and the entire moon became as blood,

[[v66-6-13]]

^<<v66-6-13,13>>^ and the stars of heaven fell to the earth, as when a fig tree shaken by a high wind casts its unripe figs.

[[v66-6-14]]

^<<v66-6-14,14>>^ And the heaven departed as a scroll that is being rolled up, and every mountain and &#91;every&#93; island were removed from their places.

[[v66-6-15]]

^<<v66-6-15,15>>^ And the kings of the earth and the top-ranking ones and the military commanders^&#42;1^ and the rich and the strong ones and every slave and &#91;every&#93; free person hid themselves in the caves and in the rock-masses of the mountains.

[NOTE]
====
. Or, “the chiliarchs,” each in command of 1,000 soldiers.
====

[[v66-6-16]]

^<<v66-6-16,16>>^ And they keep saying to the mountains and to the rock-masses: “Fall over us and hide us from the face of the One seated on the throne and from the wrath of the Lamb,

[[v66-6-17]]

^<<v66-6-17,17>>^ because the great day of their wrath has come, and who is able to stand?”

'''

xref:066-revelation/066-revelation-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-revelation/066-revelation-007.adoc#v66-7-0[Próximo Capítulo &#62;]