include::./index.adoc[]

[[v66-13-0]]
=== A Revelation to John, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-13-1]]

^<<v66-13-1,1>>^ And it stood still upon the sand of the sea.
And I saw a wild beast ascending out of the sea, with ten horns and seven heads, and upon its horns ten diadems, but upon its heads blasphemous names.

[[v66-13-2]]

^<<v66-13-2,2>>^ Now the wild beast that I saw was like a leopard, but its feet were as those of a bear, and its mouth was as a lion’s mouth. And the dragon gave to &#91;the beast&#93;^&#42;1^ its power and its throne and great authority.

[NOTE]
====
. Lit., “gave to it.”
====

[[v66-13-3]]

^<<v66-13-3,3>>^ And I saw one of its heads as though slaughtered to death, but its death-stroke got healed, and all the earth followed the wild beast with admiration.

[[v66-13-4]]

^<<v66-13-4,4>>^ And they worshiped the dragon because it gave the authority to the wild beast, and they worshiped the wild beast with the words: “Who is like the wild beast, and who can do battle with it?”

[[v66-13-5]]

^<<v66-13-5,5>>^ And a mouth speaking great things and blasphemies was given it, and authority to act forty-two months was given it.

[[v66-13-6]]

^<<v66-13-6,6>>^ And it opened its mouth in blasphemies against God, to blaspheme his name and his residence,^&#42;1^ even those residing in heaven.

[NOTE]
====
. Or, “tent; tabernacle.”
====

[[v66-13-7]]

^<<v66-13-7,7>>^ And there was granted it to wage war with the holy ones and conquer them,^&#42;1^ and authority was given it over every tribe and people and tongue and nation.

[NOTE]
====
. “And there was granted . . . conquer them,” אVg; P47ACArm omit.
====

[[v66-13-8]]

^<<v66-13-8,8>>^ And all those who dwell on the earth will worship it;^&#42;1^ the name of not one of them stands written in the scroll of life of the Lamb who was slaughtered, from the founding^&#42;2^ of the world.

[NOTE]
====
. Or, “him.”
. Lit., “throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v66-13-9]]

^<<v66-13-9,9>>^ If anyone has an ear, let him hear.

[[v66-13-10]]

^<<v66-13-10,10>>^ If anyone &#91;is meant&#93; for captivity, he goes away into captivity. If anyone will kill with the sword, he must be killed with the sword. Here is where it means the endurance and faith of the holy ones.

[[v66-13-11]]

^<<v66-13-11,11>>^ And I saw another wild beast ascending out of the earth, and it had two horns like a lamb, but it began speaking as a dragon.

[[v66-13-12]]

^<<v66-13-12,12>>^ And it exercises all the authority of the first wild beast in its sight. And it makes the earth and those who dwell in it worship the first wild beast, whose death-stroke got healed.

[[v66-13-13]]

^<<v66-13-13,13>>^ And it performs great signs, so that it should even make fire come down out of heaven to the earth in the sight of mankind.

[[v66-13-14]]

^<<v66-13-14,14>>^ And it misleads those who dwell on the earth, because of the signs that were granted it to perform in the sight of the wild beast, while it tells those who dwell on the earth to make an image to the wild beast that^&#42;1^ had the sword-stroke and yet revived.

[NOTE]
====
. Lit., “who.”
====

[[v66-13-15]]

^<<v66-13-15,15>>^ And there was granted it to give breath^&#42;1^ to the image of the wild beast, so that the image of the wild beast should both speak and cause to be killed all those who would not in any way worship the image of the wild beast.

[NOTE]
====
. Or, “spirit; active force.” Gr., pneuʹma; Lat., spiʹri·tum; J17,​18,​22(Heb.), ruʹach.
====

[[v66-13-16]]

^<<v66-13-16,16>>^ And it puts under compulsion all persons, the small and the great, and the rich and the poor, and the free and the slaves, that they should give these a mark in their right hand or upon their forehead,

[[v66-13-17]]

^<<v66-13-17,17>>^ and^&#42;1^ that nobody might be able to buy or sell except a person having the mark,^&#42;2^ the name of the wild beast or the number of its name.

[NOTE]
====
. “And,” P47אcAVg; א*CSyh omit.
. Lit., “engraving.” Gr., khaʹrag·ma; J18,​22(Heb.), hat·tawʹ, “the taw,” the Heb. letter corresponding to the English letter “T.” Compare Eze 9:4 ftn.
====

[[v66-13-18]]

^<<v66-13-18,18>>^ Here is where wisdom comes in: Let the one that has intelligence calculate the number of the wild beast, for it is a man’s number; and its number is six hundred and sixty-six.^&#42;1^

[NOTE]
====
. “Six hundred and sixty-six,” אA; P47 and Minuscule ms 046, χξςʹ, the Gr. letters representing the number 666. Here the number 6 is emphasized to a third degree, namely, 6 plus 60 plus 600.
====

'''

xref:066-revelation/066-revelation-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-revelation/066-revelation-014.adoc#v66-14-0[Próximo Capítulo &#62;]