include::./index.adoc[]

[[v66-20-0]]
=== A Revelation to John, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-20-1]]

^<<v66-20-1,1>>^ And I saw an angel coming down out of heaven with the key of the abyss and a great chain in his hand.

[[v66-20-2]]

^<<v66-20-2,2>>^ And he seized the dragon, the original serpent, who is the Devil and Satan, and bound him for a thousand years.

[[v66-20-3]]

^<<v66-20-3,3>>^ And he hurled him into the abyss and shut &#91;it&#93; and sealed &#91;it&#93; over him, that he might not mislead the nations anymore until the thousand years were ended. After these things he must be let loose for a little while.

[[v66-20-4]]

^<<v66-20-4,4>>^ And I saw thrones, and there were those who sat down on them, and power of judging was given them. Yes, I saw the souls of those executed with the ax for the witness they bore to Jesus and for speaking about God,^&#42;1^ and those who had worshiped neither the wild beast nor its image and who had not received the mark upon their forehead and upon their hand. And they came to life and ruled as kings with the Christ for a thousand years.^&#42;2^

[NOTE]
====
. Lit., “through the witness of Jesus and through the word of the God.”
. “Thousand years.” Gr., khiʹli·a eʹte, root for the English word “chiliasts,” believers in a literal thousand-year reign of Christ over mankind on a paradise earth; Lat., milʹle anʹnis, “a millennium.”
====

[[v66-20-5]]

^<<v66-20-5,5>>^ (The rest of the dead did not come to life until the thousand years were ended.)^&#42;1^ This is the first resurrection.^&#42;2^

[NOTE]
====
. “The rest of the dead . . . were ended,” AVg; אSyp omit.
. “Resurrection.” Gr., a·naʹsta·sis, “raising up; standing up” (from a·naʹ, “up,” and staʹsis, “standing”); Lat., re·sur·recʹti·o.
====

[[v66-20-6]]

^<<v66-20-6,6>>^ Happy and holy is anyone having part in the first resurrection; over these the second death has no authority, but they will be priests of God and of the Christ, and will rule as kings with him for the thousand years.

[[v66-20-7]]

^<<v66-20-7,7>>^ Now as soon as the thousand years have been ended, Satan will be let loose out of his prison,

[[v66-20-8]]

^<<v66-20-8,8>>^ and he will go out to mislead those nations in the four corners^&#42;1^ of the earth, Gog and Maʹgog, to gather them together for the war. The number of these is as the sand of the sea.

[NOTE]
====
. Or, “quarters; extremities.” Compare 7:1.
====

[[v66-20-9]]

^<<v66-20-9,9>>^ And they advanced over the breadth of the earth and encircled the camp^&#42;1^ of the holy ones and the beloved city. But fire came down out of heaven and devoured them.

[NOTE]
====
. Or, “the army in battle line.” Lit., “encampment.”
====

[[v66-20-10]]

^<<v66-20-10,10>>^ And the Devil who was misleading^&#42;1^ them was hurled into the lake of fire and sulphur, where both the wild beast and the false prophet &#91;already were&#93;; and they will be tormented day and night forever and ever.

[NOTE]
====
. Lit., “making to err.”
====

[[v66-20-11]]

^<<v66-20-11,11>>^ And I saw a great white throne and the one seated on it. From before him^&#42;1^ the earth and the heaven fled away, and no place was found for them.

[NOTE]
====
. Or, “From the face of him.”
====

[[v66-20-12]]

^<<v66-20-12,12>>^ And I saw the dead, the great and the small, standing before the throne, and scrolls^&#42;1^ were opened. But another scroll was opened; it is the scroll of life. And the dead were judged out of those things written in the scrolls according to their deeds.

[NOTE]
====
. Lit., “little books.” Gr., bi·bliʹa.
====

[[v66-20-13]]

^<<v66-20-13,13>>^ And the sea gave up those dead in it, and death and Haʹdes^&#42;1^ gave up those dead in them, and they were judged individually according to their deeds.

[NOTE]
====
. “Hades.” Gr., haiʹdes; Vg(Lat.), inʹfe·rus; Vgc​(Lat.), in·ferʹnus; SyhJ7,​8,​11-14,​16-18,​22, “Sheol.” See App 4B.
====

[[v66-20-14]]

^<<v66-20-14,14>>^ And death and Haʹdes were hurled into the lake of fire.^&#42;1^ This means^&#42;2^ the second death, the lake of fire.

[NOTE]
====
. See App 4C.
. Or, “is.”
====

[[v66-20-15]]

^<<v66-20-15,15>>^ Furthermore, whoever was not found written in the book of life was hurled into the lake of fire.

'''

xref:066-revelation/066-revelation-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-revelation/066-revelation-021.adoc#v66-21-0[Próximo Capítulo &#62;]