include::./index.adoc[]

[[v66-5-0]]
=== A Revelation to John, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-5-1]]

^<<v66-5-1,1>>^ And I saw in the right hand of the One seated upon the throne a scroll written within and on the reverse side, sealed tight with seven seals.

[[v66-5-2]]

^<<v66-5-2,2>>^ And I saw a strong angel proclaiming with a loud^&#42;1^ voice: “Who is worthy to open the scroll and loose its seals?”

[NOTE]
====
. Or, “great.”
====

[[v66-5-3]]

^<<v66-5-3,3>>^ But neither in heaven nor upon earth nor underneath the earth was there a single one able to open the scroll or to look into it.

[[v66-5-4]]

^<<v66-5-4,4>>^ And I gave way to a great deal of weeping because no one was found worthy to open the scroll or to look into it.

[[v66-5-5]]

^<<v66-5-5,5>>^ But one of the elders says to me: “Stop weeping. Look! The Lion that is of the tribe of Judah, the root of David, has conquered so as to open the scroll and its seven seals.”

[[v66-5-6]]

^<<v66-5-6,6>>^ And I saw standing in the midst of the throne and of the four living creatures and in the midst of the elders a lamb as though it had been slaughtered, having seven horns and seven eyes, which &#91;eyes&#93; mean^&#42;1^ the seven^&#42;2^ spirits of God that^&#42;3^ have been sent forth into the whole earth.

[NOTE]
====
. Or, “are.”
. “Seven,” אVgcSyh; AVg omit.
. “That,” אVg, referring to the “seven spirits”; A, “and which,” referring to the “eyes.”
====

[[v66-5-7]]

^<<v66-5-7,7>>^ And he went and at once took &#91;it&#93; out of the right hand of the One seated on the throne.

[[v66-5-8]]

^<<v66-5-8,8>>^ And when he took the scroll, the four living creatures and the twenty-four elders fell down before the Lamb, having each one a harp and golden bowls that were full of incense, and the &#91;incense&#93; means^&#42;1^ the prayers of the holy ones.

[NOTE]
====
. “The [incense] means,” א and Minuscule ms 046; A, “the [bowls] mean.”
====

[[v66-5-9]]

^<<v66-5-9,9>>^ And they sing a new song, saying: “You are worthy to take the scroll and open its seals, because you were slaughtered and with your blood you bought persons for God out of every tribe and tongue and people and nation,

[[v66-5-10]]

^<<v66-5-10,10>>^ and you made them to be a kingdom and priests to our God, and they are to rule as kings^&#42;1^ over^&#42;2^ the earth.”

[NOTE]
====
. “They are to rule as kings; they rule as kings,” ASyh and Minuscule ms 046; אVg, “they will rule as kings.”
. “Over.” Gr., e·piʹ, with the genitive, as in 9:11; 11:6.
====

[[v66-5-11]]

^<<v66-5-11,11>>^ And I saw, and I heard a voice of many angels around the throne and the living creatures and the elders, and the number of them was myriads of myriads^&#42;1^ and thousands of thousands,

[NOTE]
====
. Or, “ten thousand times tens of thousands.”
====

[[v66-5-12]]

^<<v66-5-12,12>>^ saying with a loud voice: “The Lamb that was slaughtered is worthy to receive the power and riches and wisdom and strength and honor and glory and blessing.”

[[v66-5-13]]

^<<v66-5-13,13>>^ And every creature that is in heaven and on earth and underneath the earth and on the sea, and all the things in them, I heard saying: “To the One sitting on the throne and to the Lamb be the blessing and the honor and the glory and the might forever and ever.”

[[v66-5-14]]

^<<v66-5-14,14>>^ And the four living creatures went saying: “Amen!” and the elders fell down and worshiped.

'''

xref:066-revelation/066-revelation-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-revelation/066-revelation-006.adoc#v66-6-0[Próximo Capítulo &#62;]