include::./index.adoc[]

[[v66-3-0]]
=== A Revelation to John, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-3-1]]

^<<v66-3-1,1>>^ “And to the angel of the congregation in Sarʹdis write: These are the things that he says who has the seven spirits of God and the seven stars, ‘I know your deeds, that you have the name that you are alive, but you are dead.

[[v66-3-2]]

^<<v66-3-2,2>>^ Become watchful, and strengthen the things remaining that were ready to die, for I have not found your deeds fully performed before my God.

[[v66-3-3]]

^<<v66-3-3,3>>^ Therefore, continue mindful of how you have received and how you heard, and go on keeping &#91;it&#93;, and repent. Certainly unless you wake up, I shall come as a thief, and you will not know at all at what hour I shall come upon you.

[[v66-3-4]]

^<<v66-3-4,4>>^ “‘Nevertheless, you do have a few names^&#42;1^ in Sarʹdis that did not defile their outer garments, and they shall walk with me in white ones, because they are worthy.

[NOTE]
====
. Or, “persons.”
====

[[v66-3-5]]

^<<v66-3-5,5>>^ He that conquers will thus be arrayed in white outer garments; and I will by no means blot out his name from the book of life, but I will make acknowledgment of his name before my Father and before his angels.

[[v66-3-6]]

^<<v66-3-6,6>>^ Let the one who has an ear hear what the spirit says to the congregations.’

[[v66-3-7]]

^<<v66-3-7,7>>^ “And to the angel of the congregation in Philadelphia write: These are the things he says who is holy, who is true, who has the key of David, who opens so that no one will shut, and shuts so that no one opens,

[[v66-3-8]]

^<<v66-3-8,8>>^ ‘I know your deeds—look! I have set before you an opened door, which no one can shut—that you have a little power, and you kept my word and did not prove false to my name.

[[v66-3-9]]

^<<v66-3-9,9>>^ Look! I will give those from the synagogue of Satan who say they are Jews, and yet they are not but are lying—look! I will make them come and do obeisance before your feet and make them know I have loved you.

[[v66-3-10]]

^<<v66-3-10,10>>^ Because you kept the word about my endurance,^&#42;1^ I will also keep you from the hour of test,^&#42;2^ which is to come upon the whole inhabited earth, to put a test upon those dwelling on the earth.

[NOTE]
====
. Or, “kept what I said about endurance.”
. Lit., “the hour of the temptation.”
====

[[v66-3-11]]

^<<v66-3-11,11>>^ I am coming quickly. Keep on holding fast what you have, that no one may take your crown.

[[v66-3-12]]

^<<v66-3-12,12>>^ “‘The one that conquers—I will make him a pillar in the temple^&#42;1^ of my God, and he will by no means go out &#91;from it&#93; anymore, and I will write upon him the name of my God and the name of the city of my God, the new Jerusalem^&#42;2^ which descends out of heaven from my God, and that new name of mine.

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·oiʹ, dative, sing.; Lat., temʹplo; J17,​18,​22(Heb.), beheh·khalʹ, “in the palace (temple) of.”
. “Jerusalem,” meaning “Possession [or, Foundation] of Twofold Peace.”
====

[[v66-3-13]]

^<<v66-3-13,13>>^ Let the one who has an ear hear what the spirit says to the congregations.’

[[v66-3-14]]

^<<v66-3-14,14>>^ “And to the angel of the congregation in La·o·di·ceʹa write: These are the things that the Amen^&#42;1^ says, the faithful and true witness, the beginning of the creation by God,

[NOTE]
====
. “The Amen.” Gr., ho A·menʹ; Lat., Aʹmen; J17,​18,​22(Heb.), ha·ʼA·menʹ, “the So Be It.”
====

[[v66-3-15]]

^<<v66-3-15,15>>^ ‘I know your deeds, that you are neither cold nor hot. I wish you were cold or else hot.

[[v66-3-16]]

^<<v66-3-16,16>>^ So, because you are lukewarm and neither hot nor cold, I am going to vomit^&#42;1^ you out of my mouth.

[NOTE]
====
. “I am going to vomit,” AVgSyh; א, “keep [your mouth] still!”
====

[[v66-3-17]]

^<<v66-3-17,17>>^ Because you say: “I am rich and have acquired riches and do not need anything at all,” but you do not know you are miserable and pitiable and poor and blind and naked,

[[v66-3-18]]

^<<v66-3-18,18>>^ I advise you to buy from me gold refined by fire that you may become rich, and white outer garments that you may become dressed and that the shame of your nakedness may not become manifested, and eyesalve to rub in your eyes that you may see.

[[v66-3-19]]

^<<v66-3-19,19>>^ “‘All those for whom I have affection I reprove and discipline. Therefore be zealous and repent.

[[v66-3-20]]

^<<v66-3-20,20>>^ Look! I am standing at the door and knocking. If anyone hears my voice and opens the door, I will come into his &#91;house&#93; and take the evening meal with him and he with me.

[[v66-3-21]]

^<<v66-3-21,21>>^ To the one that conquers I will grant to sit down with me on my throne, even as I conquered and sat down with my Father on his throne.

[[v66-3-22]]

^<<v66-3-22,22>>^ Let the one who has an ear hear what the spirit says to the congregations.’”

'''

xref:066-revelation/066-revelation-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-revelation/066-revelation-004.adoc#v66-4-0[Próximo Capítulo &#62;]