include::./index.adoc[]

[[v66-21-0]]
=== A Revelation to John, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-21-1]]

^<<v66-21-1,1>>^ And I saw a new heaven and a new earth; for the former heaven and the former earth had passed away, and the sea is no more.

[[v66-21-2]]

^<<v66-21-2,2>>^ I saw also the holy city, New Jerusalem, coming down out of heaven from God and prepared as a bride adorned for her husband.

[[v66-21-3]]

^<<v66-21-3,3>>^ With that I heard a loud voice from the throne say: “Look! The tent^&#42;1^ of God is with mankind, and he will reside^&#42;2^ with them, and they will be his peoples. And God himself will be with them.

[NOTE]
====
. “Tent.” Gr., ske·neʹ; Lat., ta·ber·naʹcu·lum; J17,​18,​22(Heb.), mish·kanʹ. See Ex 25:8.
. Lit., “he will tent.”
====

[[v66-21-4]]

^<<v66-21-4,4>>^ And he will wipe out every tear from their eyes, and death will be no more, neither will mourning nor outcry nor pain be anymore. The former things have passed away.”

[[v66-21-5]]

^<<v66-21-5,5>>^ And the One seated on the throne said: “Look! I am making all things new.” Also, he says: “Write, because these words are faithful and true.”

[[v66-21-6]]

^<<v66-21-6,6>>^ And he said to me: “They have come to pass!^&#42;1^ I am the Alʹpha and the O·meʹga,^&#42;2^ the beginning and the end. To anyone thirsting I will give from the fountain of the water of life free.

[NOTE]
====
. Or, “They are a fact!”
. Or, “I am the A and the Z.” Compare 1:8 ftn, “Omega.”
====

[[v66-21-7]]

^<<v66-21-7,7>>^ Anyone conquering will inherit these things, and I shall be his God and he will be my son.

[[v66-21-8]]

^<<v66-21-8,8>>^ But as for the cowards and those without faith and those who are disgusting in their filth and murderers and fornicators and those practicing spiritism^&#42;1^ and idolaters and all the liars, their portion will be in the lake that burns with fire and sulphur. This means^&#42;2^ the second death.”

[NOTE]
====
. “Those practicing spiritism.” Or, “sorcerers.” Lit., “druggers.” Gr., phar·ma·koisʹ.
. Or, “This portion is.”
====

[[v66-21-9]]

^<<v66-21-9,9>>^ And there came one of the seven angels who had the seven bowls which were full of the seven last plagues, and he spoke with me and said: “Come here, I will show you the bride, the Lamb’s wife.”

[[v66-21-10]]

^<<v66-21-10,10>>^ So he carried me away in &#91;the power of the&#93; spirit to a great and lofty mountain, and he showed me the holy city Jerusalem coming down out of heaven from God

[[v66-21-11]]

^<<v66-21-11,11>>^ and having the glory of God. Its radiance^&#42;1^ was like a most precious stone, as a jasper stone shining crystal-clear.

[NOTE]
====
. Or, “illuminator.”
====

[[v66-21-12]]

^<<v66-21-12,12>>^ It had a great and lofty wall and had twelve gates, and at the gates twelve angels, and names were inscribed which are those of the twelve tribes of the sons of Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ On the east were three gates, and on the north three gates, and on the south three gates, and on the west three gates.

[[v66-21-14]]

^<<v66-21-14,14>>^ The wall of the city also had twelve foundation stones, and on them the twelve names of the twelve apostles of the Lamb.

[[v66-21-15]]

^<<v66-21-15,15>>^ Now the one who was speaking with me was holding as a measure a golden reed, that he might measure the city and its gates and its wall.

[[v66-21-16]]

^<<v66-21-16,16>>^ And the city lies foursquare, and its length is as great as its breadth. And he measured the city with the reed, twelve thousand furlongs;^&#42;1^ its length and breadth and height are equal.

[NOTE]
====
. About 2,220 km (1,379 English mi). A furlong corresponded to a stadium and equaled one eighth of a Roman mile, 185 m (606.75 ft).
====

[[v66-21-17]]

^<<v66-21-17,17>>^ Also, he measured its wall, one hundred and forty-four cubits,^&#42;1^ according to a man’s measure, at the same time an angel’s.^&#42;2^

[NOTE]
====
. About 64 m (210 ft).
. Or, “that is, an angel’s.”
====

[[v66-21-18]]

^<<v66-21-18,18>>^ Now the structure of its wall was jasper, and the city was pure gold like clear glass.

[[v66-21-19]]

^<<v66-21-19,19>>^ The foundations of the city’s wall were adorned with every sort of precious stone: the first foundation was jasper, the second sapphire, the third chal·cedʹo·ny, the fourth emerald,

[[v66-21-20]]

^<<v66-21-20,20>>^ the fifth sarʹdo·nyx, the sixth sardius, the seventh chrysʹo·lite, the eighth beryl, the ninth topaz, the tenth chrysʹo·prase, the eleventh hyacinth, the twelfth amethyst.

[[v66-21-21]]

^<<v66-21-21,21>>^ Also, the twelve gates were twelve pearls; each one of the gates was made of one pearl. And the broad way of the city was pure gold, as transparent glass.

[[v66-21-22]]

^<<v66-21-22,22>>^ And I did not see a temple^&#42;1^ in it, for Jehovah^&#42;2^ God the Almighty^&#42;3^ is its temple, also the Lamb &#91;is&#93;.

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplum; J17,​18(Heb.), weheh·khalʹ, “and a palace (temple).”
. See App 1D.
. “Almighty.” Gr., Pan·to·kraʹtor; Lat., O·mniʹpo·tens; J17,​22(Heb.), ʼElo·himʹ tseva·ʼohthʹ, “God of armies.” See Ru 1:20 ftn, “Almighty.”
====

[[v66-21-23]]

^<<v66-21-23,23>>^ And the city has no need of the sun nor of the moon to shine upon it, for the glory of God lighted it up, and its lamp was the Lamb.

[[v66-21-24]]

^<<v66-21-24,24>>^ And the nations will walk by means of its light, and the kings of the earth will bring their glory into it.

[[v66-21-25]]

^<<v66-21-25,25>>^ And its gates will not be closed at all by day, for night will not exist there.

[[v66-21-26]]

^<<v66-21-26,26>>^ And they will bring the glory and the honor of the nations into it.

[[v66-21-27]]

^<<v66-21-27,27>>^ But anything not sacred and anyone that carries on a disgusting thing and a lie will in no way enter into it; only those written in the Lamb’s scroll of life &#91;will&#93;.

'''

xref:066-revelation/066-revelation-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-revelation/066-revelation-022.adoc#v66-22-0[Próximo Capítulo &#62;]