include::./index.adoc[]

[[v66-17-0]]
=== A Revelation to John, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-17-1]]

^<<v66-17-1,1>>^ And one of the seven angels that had the seven bowls came and spoke with me, saying: “Come, I will show you the judgment upon the great harlot^&#42;1^ who sits on many^&#42;2^ waters,

[NOTE]
====
. Or, “fornicatrix; prostitute.” Gr., porʹnes. See App 5A.
. Or, “great.”
====

[[v66-17-2]]

^<<v66-17-2,2>>^ with whom the kings of the earth committed fornication, whereas those who inhabit the earth were made drunk with the wine of her fornication.”^&#42;1^

[NOTE]
====
. Gr., por·neiʹas. See App 5A.
====

[[v66-17-3]]

^<<v66-17-3,3>>^ And he carried me away in &#91;the power of the&#93; spirit into a wilderness. And I caught sight of a woman sitting upon a scarlet-colored wild beast that was full of blasphemous names and that had seven heads and ten horns.

[[v66-17-4]]

^<<v66-17-4,4>>^ And the woman was arrayed in purple and scarlet, and was adorned with gold and precious stone and pearls and had in her hand a golden cup that was full of disgusting things and the unclean things of her fornication.

[[v66-17-5]]

^<<v66-17-5,5>>^ And upon her forehead was written a name, a mystery:^&#42;1^ “Babylon^&#42;2^ the Great, the mother of the harlots and of the disgusting things of the earth.”

[NOTE]
====
. Or, “a religious secret,” sacred to Babylon.
. See 16:19 ftn.
====

[[v66-17-6]]

^<<v66-17-6,6>>^ And I saw that the woman was drunk with the blood of the holy ones and with the blood of the witnesses of Jesus.
Well, on catching sight of her I wondered with great wonderment.

[[v66-17-7]]

^<<v66-17-7,7>>^ And so the angel said to me: “Why is it you wondered? I will tell you the mystery^&#42;1^ of the woman and of the wild beast that is carrying her and that has the seven heads and the ten horns:

[NOTE]
====
. Or, “religious secret.” Gr., my·steʹri·on.
====

[[v66-17-8]]

^<<v66-17-8,8>>^ The wild beast that you saw was, but is not, and yet is about to ascend out of the abyss, and it is to go off into destruction. And when they see how the wild beast was, but is not, and yet will be present, those who dwell on the earth will wonder admiringly, but their names have not been written upon the scroll of life from the founding^&#42;1^ of the world.

[NOTE]
====
. Lit., “throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v66-17-9]]

^<<v66-17-9,9>>^ “Here is where the intelligence that has wisdom comes in: The seven heads mean^&#42;1^ seven mountains, where the woman sits on top.

[NOTE]
====
. Or, “are.”
====

[[v66-17-10]]

^<<v66-17-10,10>>^ And there are^&#42;1^ seven kings: five have fallen, one is, the other has not yet arrived, but when he does arrive he must remain a short while.

[NOTE]
====
. Or, “And they mean.”
====

[[v66-17-11]]

^<<v66-17-11,11>>^ And the wild beast that was but is not, it is also itself an eighth &#91;king&#93;, but springs from the seven,^&#42;1^ and it goes off into destruction.

[NOTE]
====
. Or, “but owes its existence to the seven.”
====

[[v66-17-12]]

^<<v66-17-12,12>>^ “And the ten horns that you saw mean ten kings, who have not yet received a kingdom, but they do receive authority as kings one hour with the wild beast.

[[v66-17-13]]

^<<v66-17-13,13>>^ These have one thought, and so they give their power and authority to the wild beast.

[[v66-17-14]]

^<<v66-17-14,14>>^ These will battle with the Lamb, but, because he is Lord of^&#42;1^ lords and King of^&#42;2^ kings, the Lamb will conquer them. Also, those called and chosen and faithful with him &#91;will do so&#93;.”

[NOTE]
====
. Or, “over; among.”
. Or, “over; among.”
====

[[v66-17-15]]

^<<v66-17-15,15>>^ And he says to me: “The waters that you saw, where the harlot is sitting, mean peoples and crowds^&#42;1^ and nations and tongues.

[NOTE]
====
. Or, “masses.”
====

[[v66-17-16]]

^<<v66-17-16,16>>^ And the ten horns that you saw, and the wild beast, these will hate the harlot and will make her devastated and naked, and will eat up her fleshy parts and will completely burn her with fire.

[[v66-17-17]]

^<<v66-17-17,17>>^ For God put &#91;it&#93; into their hearts to carry out his thought, even to carry out &#91;their&#93; one thought by giving^&#42;1^ their kingdom to the wild beast, until the words of God will have been accomplished.

[NOTE]
====
. Or, “to carry out one purpose and give.” Lit., “to do one opinion and to give.”
====

[[v66-17-18]]

^<<v66-17-18,18>>^ And the woman whom you saw means^&#42;1^ the great city that has a kingdom over the kings of the earth.”

[NOTE]
====
. Or, “is.”
====

'''

xref:066-revelation/066-revelation-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-revelation/066-revelation-018.adoc#v66-18-0[Próximo Capítulo &#62;]