include::./index.adoc[]

[[v66-9-0]]
=== A Revelation to John, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-9-1]]

^<<v66-9-1,1>>^ And the fifth angel blew his trumpet. And I saw a star that had fallen from heaven to the earth, and the key of the pit of the abyss was given him.^&#42;1^

[NOTE]
====
. Or, “it.”
====

[[v66-9-2]]

^<<v66-9-2,2>>^ And he^&#42;1^ opened the pit of the abyss, and smoke ascended out of the pit as the smoke of a great furnace, and the sun was darkened, also the air, by the smoke of the pit.

[NOTE]
====
. Or, “it.”
====

[[v66-9-3]]

^<<v66-9-3,3>>^ And out of the smoke locusts came forth upon the earth; and authority was given them, the same authority as the scorpions of the earth have.

[[v66-9-4]]

^<<v66-9-4,4>>^ And they were told to harm no vegetation of the earth nor any green thing nor any tree, but only those men who do not have the seal of God on their foreheads.

[[v66-9-5]]

^<<v66-9-5,5>>^ And it was granted the &#91;locusts&#93;, not to kill them, but that these should be tormented five months, and the torment upon them was as torment by a scorpion when it strikes a man.

[[v66-9-6]]

^<<v66-9-6,6>>^ And in those days the men will seek death but will by no means find it, and they will desire to die but death keeps fleeing from them.

[[v66-9-7]]

^<<v66-9-7,7>>^ And the likenesses of the locusts resembled horses prepared for battle; and upon their heads &#91;were&#93; what seemed to be crowns like gold, and their faces &#91;were&#93; as men’s faces,

[[v66-9-8]]

^<<v66-9-8,8>>^ but they had hair as women’s hair. And their teeth were as those of lions;

[[v66-9-9]]

^<<v66-9-9,9>>^ and they had breastplates like iron breastplates. And the sound of their wings &#91;was&#93; as the sound of chariots of many horses running into battle.

[[v66-9-10]]

^<<v66-9-10,10>>^ Also, they have tails and stings like scorpions; and in their tails is their authority to hurt^&#42;1^ the men five months.

[NOTE]
====
. Lit., “to treat unrighteously.”
====

[[v66-9-11]]

^<<v66-9-11,11>>^ They have over them a king, the angel of the abyss. In Hebrew his name is A·badʹdon,^&#42;1^ but in Greek he has the name A·polʹlyon.^&#42;2^

[NOTE]
====
. “Abaddon.” Or, “Destruction.” J17,​18,​22(Heb.), ʼAvad·dohnʹ. Compare Job 26:6; Ps 88:11; Pr 15:11 ftns, “Destruction.”
. “Apollyon.” Or, “Destroyer.” Gr., A·pol·lyʹon. Vg adds: “and in Latin he has the name Exterminator (Ex·terʹmi·nans).” See Mt 7:13 ftn.
====

[[v66-9-12]]

^<<v66-9-12,12>>^ The one woe is past. Look! Two more woes are coming after these things.^&#42;1^

[NOTE]
====
. Or, “the following things.”
====

[[v66-9-13]]

^<<v66-9-13,13>>^ And the sixth angel blew his trumpet. And I heard one voice out of the horns^&#42;1^ of the golden altar that is before God

[NOTE]
====
. “Out of the horns,” P47אcAItmssSyh; Vgc, “out of the four horns.”
====

[[v66-9-14]]

^<<v66-9-14,14>>^ say to the sixth angel, who had the trumpet: “Untie the four angels that are bound at the great river Eu·phraʹtes.”

[[v66-9-15]]

^<<v66-9-15,15>>^ And the four angels were untied, who have been prepared for the hour and day and month and year, to kill a third of the men.

[[v66-9-16]]

^<<v66-9-16,16>>^ And the number of the armies of cavalry^&#42;1^ was two myriads of myriads:^&#42;2^ I heard the number of them.

[NOTE]
====
. Or, “of the horsemen.”
. Or, “twenty thousand times ten thousand,” that is, 200,000,000.
====

[[v66-9-17]]

^<<v66-9-17,17>>^ And this is how I saw the horses in the vision, and those seated on them: they had fire-red and hyacinth-blue and sulphur-yellow breastplates; and the heads of the horses were as heads of lions, and out of their mouths fire and smoke and sulphur issued forth.

[[v66-9-18]]

^<<v66-9-18,18>>^ By these three plagues a third of the men were killed, from the fire and the smoke and the sulphur which issued forth from their mouths.

[[v66-9-19]]

^<<v66-9-19,19>>^ For the authority of the horses is in their mouths and in their tails; for their tails are like serpents and have heads, and with these they do harm.

[[v66-9-20]]

^<<v66-9-20,20>>^ But the rest of the men who were not killed by these plagues did not repent of the works of their hands, so that they should not worship the demons and the idols of gold and silver and copper and stone and wood, which can neither see nor hear nor walk;

[[v66-9-21]]

^<<v66-9-21,21>>^ and they did not repent of their murders nor of their spiritistic practices^&#42;1^ nor of their fornication nor of their thefts.

[NOTE]
====
. “Spiritistic practices.” Or, “sorceries.” Lit., “drugs.” Gr., phar·maʹkon.
====

'''

xref:066-revelation/066-revelation-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-revelation/066-revelation-010.adoc#v66-10-0[Próximo Capítulo &#62;]