include::./index.adoc[]

[[v66-15-0]]
=== A Revelation to John, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-15-1]]

^<<v66-15-1,1>>^ And I saw in heaven another sign, great and wonderful, seven angels with seven plagues. These are the last ones, because by means of them the anger of God is brought to a finish.

[[v66-15-2]]

^<<v66-15-2,2>>^ And I saw what seemed to be a glassy sea mingled with fire, and those who come off victorious from the wild beast and from its image and from the number of its name standing by^&#42;1^ the glassy sea, having harps of God.

[NOTE]
====
. Or, “upon.”
====

[[v66-15-3]]

^<<v66-15-3,3>>^ And they are singing the song of Moses the slave of God and the song of the Lamb, saying:
“Great and wonderful are your works, Jehovah^&#42;1^ God, the Almighty. Righteous and true are your ways, King of eternity.^&#42;2^

[NOTE]
====
. See App 1D.
. “Eternity,” P47א*CVgSyh; A and Minuscule ms 046, “the nations.”
====

[[v66-15-4]]

^<<v66-15-4,4>>^ Who will not really fear you, Jehovah,^&#42;1^ and glorify your name, because you alone are loyal? For all the nations will come and worship before you, because your righteous decrees have been made manifest.”

[NOTE]
====
. See App 1D.
====

[[v66-15-5]]

^<<v66-15-5,5>>^ And after these things I saw, and the sanctuary of the tent of the witness^&#42;1^ was opened in heaven,

[NOTE]
====
. Or, “tabernacle of the testimony.”
====

[[v66-15-6]]

^<<v66-15-6,6>>^ and the seven angels with the seven plagues emerged from the sanctuary, clothed with clean, bright linen^&#42;1^ and girded about their breasts with golden girdles.

[NOTE]
====
. “Linen,” P47אVgcSyh; AC, “stone.”
====

[[v66-15-7]]

^<<v66-15-7,7>>^ And one of the four living creatures gave the seven angels seven golden bowls that were full of the anger of God, who lives forever and ever.

[[v66-15-8]]

^<<v66-15-8,8>>^ And the sanctuary became filled with smoke because of the glory of God and because of his power, and no one was able to enter into the sanctuary until the seven plagues of the seven angels were finished.

'''

xref:066-revelation/066-revelation-014.adoc#v66-14-0[&#60; Capítulo Anterior] | <<v66-15-0,Topo>> | xref:066-revelation/066-revelation-016.adoc#v66-16-0[Próximo Capítulo &#62;]