include::./index.adoc[]

[[v66-4-0]]
=== A Revelation to John, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v66-4-1]]

^<<v66-4-1,1>>^ After these things I saw, and, look! an opened door in heaven, and the first voice that I heard was as of a trumpet, speaking with me, saying: “Come on up^&#42;1^ here, and I shall show you the things that must take place.”

[NOTE]
====
. Lit., “Step up.”
====

[[v66-4-2]]

^<<v66-4-2,2>>^ After these things I immediately came to be in &#91;the power of the&#93; spirit: and, look! a throne was in its position in heaven, and there is one seated upon the throne.

[[v66-4-3]]

^<<v66-4-3,3>>^ And the one seated is, in appearance, like a jasper stone and a precious red-colored stone,^&#42;1^ and round about the throne &#91;there is&#93; a rainbow like an emerald in appearance.

[NOTE]
====
. Or, “a sardius [or, sardian stone].”
====

[[v66-4-4]]

^<<v66-4-4,4>>^ And round about the throne &#91;there are&#93; twenty-four thrones, and upon these thrones &#91;I saw&#93; seated twenty-four elders^&#42;1^ dressed in white outer garments, and upon their heads golden crowns.

[NOTE]
====
. “Elders.” Gr., pre·sby·teʹrous.
====

[[v66-4-5]]

^<<v66-4-5,5>>^ And out of the throne there are proceeding lightnings and voices and thunders; and &#91;there are&#93; seven lamps of fire burning before the throne, and these mean^&#42;1^ the seven spirits of God.

[NOTE]
====
. Lit., “are.”
====

[[v66-4-6]]

^<<v66-4-6,6>>^ And before the throne there is, as it were, a glassy sea like crystal.
And in the midst of the throne and around the throne &#91;there are&#93; four living creatures that are full of eyes in front and behind.

[[v66-4-7]]

^<<v66-4-7,7>>^ And the first living creature is like a lion, and the second living creature is like a young bull, and the third living creature has a face like a man’s, and the fourth living creature is like a flying eagle.

[[v66-4-8]]

^<<v66-4-8,8>>^ And as for the four living creatures, each one of them respectively has six wings; round about and underneath^&#42;1^ they are full of eyes. And they have no rest day and night as they say: “Holy, holy, holy^&#42;2^ is Jehovah^&#42;3^ God, the Almighty,^&#42;4^ who was and who is and who is coming.”

[NOTE]
====
. Or, “within.”
. “Holy, holy, holy,” AVgSyh; א* reads “holy” eight times. See App 1J.
. See App 1D.
. See 1:8 ftn, “Almighty.”
====

[[v66-4-9]]

^<<v66-4-9,9>>^ And whenever the living creatures offer glory and honor and thanksgiving to the one seated upon the throne, the one that lives forever and ever,

[[v66-4-10]]

^<<v66-4-10,10>>^ the twenty-four elders^&#42;1^ fall down before the One seated upon the throne and worship the One that lives forever and ever, and they cast their crowns before the throne, saying:

[NOTE]
====
. “Elders.” Gr., pre·sbyʹte·roi.
====

[[v66-4-11]]

^<<v66-4-11,11>>^ “You are worthy, Jehovah,^&#42;1^ even our God, to receive the glory and the honor and the power, because you created all things, and because of your will they existed and were created.”

[NOTE]
====
. See App 1D.
====

'''

xref:066-revelation/066-revelation-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-revelation/066-revelation-005.adoc#v66-5-0[Próximo Capítulo &#62;]