include::./index.adoc[]

[[v63-1-0]]
=== The Second of John, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v63-1-1]]

^<<v63-1-1,1>>^ The older man^&#42;1^ to the chosen lady^&#42;2^ and to her children, whom I truly love,^&#42;3^ and not I alone, but all those also who have come to know the truth,

[NOTE]
====
. Or, “elder.” Gr., pre·sbyʹte·ros.
. Or, “to the chosen woman, Kyria.” Gr., e·kle·kteiʹ ky·riʹai.
. Or, “I love in the truth.”
====

[[v63-1-2]]

^<<v63-1-2,2>>^ because of the truth that remains in us, and it will be with us forever.

[[v63-1-3]]

^<<v63-1-3,3>>^ There will be with us undeserved kindness, mercy &#91;and&#93; peace from God the Father and from Jesus Christ the Son of the Father, with truth and love.

[[v63-1-4]]

^<<v63-1-4,4>>^ I rejoice very much because I have found^&#42;1^ certain ones of your children walking in the truth, just as we received commandment from the Father.

[NOTE]
====
. Or, “I rejoiced very much at actually finding.”
====

[[v63-1-5]]

^<<v63-1-5,5>>^ So now I request you, lady,^&#42;1^ as &#91;a person&#93; writing you, not a new commandment, but one which we had from &#91;the&#93; beginning,^&#42;2^ that we love one another.

[NOTE]
====
. Or, “Kyria.”
. “From [the] beginning.” Gr., apʼ ar·khesʹ; Lat., ab i·niʹti·o; J17(Heb.), me·roʼshʹ.
====

[[v63-1-6]]

^<<v63-1-6,6>>^ And this is what love means, that we go on walking according to his commandments. This is the commandment, just as YOU people have heard from &#91;the&#93; beginning, that YOU should go on walking in it.

[[v63-1-7]]

^<<v63-1-7,7>>^ For many deceivers have gone forth into the world, persons not confessing Jesus Christ as coming^&#42;1^ in the flesh. This is the deceiver^&#42;2^ and the antichrist.

[NOTE]
====
. “As coming.” Gr., er·khoʹme·non, referring to Christ’s past coming. It refers to past time, as in the case of the Gr. participle in 3Jo 3, where see ftn, “Came.”
. Lit., “the errant (one).”
====

[[v63-1-8]]

^<<v63-1-8,8>>^ Look out for yourselves, that YOU do not lose^&#42;1^ the things we have worked to produce, but that YOU may obtain a full reward.

[NOTE]
====
. Lit., “destroy.”
====

[[v63-1-9]]

^<<v63-1-9,9>>^ Everyone that pushes ahead^&#42;1^ and does not remain in the teaching of the Christ does not have God. He that does remain in this teaching is the one that has both the Father and the Son.

[NOTE]
====
. Lit., “Everyone going before.”
====

[[v63-1-10]]

^<<v63-1-10,10>>^ If anyone comes to YOU and does not bring this teaching, never receive him into YOUR homes or say a greeting^&#42;1^ to him.

[NOTE]
====
. Lit., “to be rejoicing.”
====

[[v63-1-11]]

^<<v63-1-11,11>>^ For he that says a greeting to him is a sharer^&#42;1^ in his wicked works.^&#42;2^

[NOTE]
====
. Lit., “he is sharing.”
. Vgs adds: “Look! I have told you beforehand so that you may not be confused in the day of the Lord”; J7,​8 add: “(Look! I have told you beforehand that you may not be ashamed in Jehovah’s day).”
====

[[v63-1-12]]

^<<v63-1-12,12>>^ Although I have many things to write YOU, I do not desire to do so with paper and ink, but I am hoping to come to YOU and to speak with YOU face to face,^&#42;1^ that YOUR joy may be in full measure.

[NOTE]
====
. Lit., “mouth toward mouth.”
====

[[v63-1-13]]

^<<v63-1-13,13>>^ The children of your sister, the chosen one, send you their greetings.

'''

xref:062-1-john/062-1-john-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-john/064-3-john-001.adoc#v64-1-0[Próximo Capítulo &#62;]