include::./index.adoc[]

[[v55-3-0]]
=== The Second to Timothy, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v55-3-1]]

^<<v55-3-1,1>>^ But know this, that in the last days critical times hard^&#42;1^ to deal with will be here.

[NOTE]
====
. Lit., “fierce.”
====

[[v55-3-2]]

^<<v55-3-2,2>>^ For men will be lovers of themselves, lovers of money, self-assuming, haughty,^&#42;1^ blasphemers,^&#42;2^ disobedient to parents, unthankful, disloyal,

[NOTE]
====
. Lit., “superior-appearing.”
. Or, “speaking abusively.”
====

[[v55-3-3]]

^<<v55-3-3,3>>^ having no natural affection, not open to any agreement,^&#42;1^ slanderers,^&#42;2^ without self-control, fierce,^&#42;3^ without love of goodness,

[NOTE]
====
. Lit., “truceless.”
. Lit., “devils.” Gr., di·aʹbo·loi.
. Lit., “untamed.”
====

[[v55-3-4]]

^<<v55-3-4,4>>^ betrayers, headstrong, puffed up &#91;with pride&#93;, lovers of pleasures rather than lovers of God,

[[v55-3-5]]

^<<v55-3-5,5>>^ having a form of godly devotion^&#42;1^ but proving false to its power; and from these turn away.

[NOTE]
====
. “Godly devotion.” Lit., “revering well.”
====

[[v55-3-6]]

^<<v55-3-6,6>>^ For from these arise those men who slyly work their way^&#42;1^ into households and lead as their captives weak women loaded down with sins, led by various desires,

[NOTE]
====
. “Slyly work their way.” Lit., “slipping in.”
====

[[v55-3-7]]

^<<v55-3-7,7>>^ always learning and yet never able to come to an accurate knowledge of truth.

[[v55-3-8]]

^<<v55-3-8,8>>^ Now in the way that Janʹnes and Jamʹbres resisted Moses, so these also go on resisting the truth, men completely corrupted in mind, disapproved as regards the faith.

[[v55-3-9]]

^<<v55-3-9,9>>^ Nevertheless, they will make no further progress, for their madness will be very plain to all, even as the &#91;madness&#93; of those &#91;two men&#93; became.

[[v55-3-10]]

^<<v55-3-10,10>>^ But you have closely followed my teaching, my course of life, my purpose, my faith, my long-suffering, my love, my endurance,

[[v55-3-11]]

^<<v55-3-11,11>>^ my persecutions, my sufferings, the sort of things that happened to me in Antioch, in I·coʹni·um, in Lysʹtra, the sort of persecutions I have borne; and yet out of them all the Lord delivered me.

[[v55-3-12]]

^<<v55-3-12,12>>^ In fact, all those desiring to live with godly devotion in association with Christ Jesus will also be persecuted.

[[v55-3-13]]

^<<v55-3-13,13>>^ But wicked men and impostors will advance from bad to worse, misleading and being misled.

[[v55-3-14]]

^<<v55-3-14,14>>^ You, however, continue in the things that you learned and were persuaded to believe, knowing from what persons you learned them

[[v55-3-15]]

^<<v55-3-15,15>>^ and that from infancy you have known the holy writings, which are able to make you wise for salvation through the faith in connection with Christ Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ All Scripture is inspired of God^&#42;1^ and beneficial for teaching, for reproving, for setting things straight,^&#42;2^ for disciplining in righteousness,

[NOTE]
====
. Lit., “God-breathed.” Gr., The·oʹpneu·stos; Lat., Di·viʹni·tus in·spi·raʹta; J17(Heb.), beruʹach ʼElo·himʹ, “by God’s spirit.”
. Lit., “straightening up upon.”
====

[[v55-3-17]]

^<<v55-3-17,17>>^ that the man of God may be fully competent, completely equipped^&#42;1^ for every good work.

[NOTE]
====
. Lit., “having been fitted out.”
====

'''

xref:055-2-timothy/055-2-timothy-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timothy/055-2-timothy-004.adoc#v55-4-0[Próximo Capítulo &#62;]