include::./index.adoc[]

[[v55-1-0]]
=== The Second to Timothy, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v55-1-1]]

^<<v55-1-1,1>>^ Paul, an apostle of Christ Jesus through God’s will according to the promise of the life that is in union with Christ Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ to Timothy, a beloved child:
May there be undeserved kindness, mercy, peace from God &#91;the&#93; Father and Christ Jesus our Lord.

[[v55-1-3]]

^<<v55-1-3,3>>^ I am grateful to God, to whom I am rendering sacred service^&#42;1^ as my forefathers did and with a clean conscience, that I never leave off remembering you in my supplications, night and day

[NOTE]
====
. “I am rendering sacred service.” Gr., la·treuʹo; J17(Heb.), ʼaniʹ ʽo·vedhʹ, “I am serving (worshiping).” See Ex 3:12 ftn.
====

[[v55-1-4]]

^<<v55-1-4,4>>^ longing to see you, as I remember your tears, that I may get filled with joy.

[[v55-1-5]]

^<<v55-1-5,5>>^ For I recollect the faith which is in you without any hypocrisy, and which dwelt first in your grandmother Loʹis and your mother Euʹnice, but which I am confident is also in you.

[[v55-1-6]]

^<<v55-1-6,6>>^ For this very cause I remind you to stir up like a fire the gift of God which is in you through the laying of my hands upon you.

[[v55-1-7]]

^<<v55-1-7,7>>^ For God gave us not a spirit of cowardice, but that of power and of love and of soundness of mind.

[[v55-1-8]]

^<<v55-1-8,8>>^ Therefore do not become ashamed of the witness^&#42;1^ about our Lord, neither of me a prisoner for his sake,^&#42;2^ but take your part in suffering evil for the good news according to the power of God.

[NOTE]
====
. “Witness.” Gr., mar·tyʹri·on; Lat., te·sti·moʹni·um.
. Or, “me his prisoner.”
====

[[v55-1-9]]

^<<v55-1-9,9>>^ He saved us and called us with a holy calling, not by reason of our works, but by reason of his own purpose and undeserved kindness. This was given us in connection with Christ Jesus before times long lasting,^&#42;1^

[NOTE]
====
. Or, “times eternal.”
====

[[v55-1-10]]

^<<v55-1-10,10>>^ but now it has been made clearly evident through the manifestation of our Savior, Christ Jesus, who has abolished^&#42;1^ death but has shed light upon life and incorruption through the good news,

[NOTE]
====
. Lit., “having made ineffective.”
====

[[v55-1-11]]

^<<v55-1-11,11>>^ for which I was appointed a preacher and apostle and teacher.

[[v55-1-12]]

^<<v55-1-12,12>>^ For this very cause I am also suffering these things, but I am not ashamed. For I know the one whom I have believed, and I am confident^&#42;1^ he is able to guard what I have laid up in trust with him until that day.

[NOTE]
====
. Lit., “I have been persuaded.”
====

[[v55-1-13]]

^<<v55-1-13,13>>^ Keep holding the pattern of healthful words that you heard from me with the faith and love that are in connection with Christ Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ This fine trust guard through the holy spirit which is dwelling in us.

[[v55-1-15]]

^<<v55-1-15,15>>^ You know this, that all the men in^&#42;1^ the &#91;district of&#93; Asia have turned away from me. Phy·gelʹus and Her·mogʹe·nes are of that number.

[NOTE]
====
. Or, “of.”
====

[[v55-1-16]]

^<<v55-1-16,16>>^ May the Lord^&#42;1^ grant mercy to the household of On·e·siphʹo·rus, because he often brought me refreshment, and he did not become ashamed of my chains.

[NOTE]
====
. “The Lord,” אAVg; J7,​8,​13,​14,​16, “Jehovah.”
====

[[v55-1-17]]

^<<v55-1-17,17>>^ On the contrary, when he happened to be in Rome, he diligently looked for me and found me.

[[v55-1-18]]

^<<v55-1-18,18>>^ May the Lord^&#42;1^ grant him to find mercy from Jehovah^&#42;2^ in that day. And all the services he rendered in Ephʹe·sus you know well enough.^&#42;3^

[NOTE]
====
. “The Lord,” אAVg; J7,​8,​13,​14,​16, “Jehovah.”
. See App 1D.
. Or, “know better than I do.”
====

'''

xref:054-1-timothy/054-1-timothy-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timothy/055-2-timothy-002.adoc#v55-2-0[Próximo Capítulo &#62;]