include::./index.adoc[]

[[v55-4-0]]
=== The Second to Timothy, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v55-4-1]]

^<<v55-4-1,1>>^ I solemnly charge you before God and Christ Jesus,^&#42;1^ who is destined to judge the living and the dead, and by his manifestation and his kingdom,

[NOTE]
====
. See App 6E.
====

[[v55-4-2]]

^<<v55-4-2,2>>^ preach the word, be at it urgently in favorable season, in troublesome season, reprove, reprimand,^&#42;1^ exhort, with all long-suffering and &#91;art of&#93; teaching.

[NOTE]
====
. Lit., “rebuke you,” imperative, second person sing.
====

[[v55-4-3]]

^<<v55-4-3,3>>^ For there will be a period of time when they will not put up with the healthful teaching, but, in accord with their own desires, they will accumulate teachers for themselves to have their ears tickled;

[[v55-4-4]]

^<<v55-4-4,4>>^ and they will turn their ears away from the truth, whereas they will be turned aside to false stories.^&#42;1^

[NOTE]
====
. Lit., “myths.” Gr., myʹthous; Lat., faʹbu·las, “fables.”
====

[[v55-4-5]]

^<<v55-4-5,5>>^ You, though, keep your senses in all things, suffer evil, do &#91;the&#93; work of an evangelizer,^&#42;1^ fully accomplish^&#42;2^ your ministry.

[NOTE]
====
. Or, “of a missionary.” Gr., eu·ag·ge·li·stouʹ; Lat., e·van·ge·liʹstae.
. Lit., “fully bear.”
====

[[v55-4-6]]

^<<v55-4-6,6>>^ For I am already being poured out like a drink offering, and the due time for my releasing^&#42;1^ is imminent.

[NOTE]
====
. See App 5D.
====

[[v55-4-7]]

^<<v55-4-7,7>>^ I have fought the fine fight,^&#42;1^ I have run the course to the finish, I have observed the faith.^&#42;2^

[NOTE]
====
. Lit., “The fine struggle I have struggled.”
. Or, “kept faithfulness.”
====

[[v55-4-8]]

^<<v55-4-8,8>>^ From this time on there is reserved for me the crown of righteousness, which the Lord, the righteous judge, will give me as a reward in that day, yet not only to me, but also to all those who have loved his manifestation.

[[v55-4-9]]

^<<v55-4-9,9>>^ Do your utmost to come to me shortly.

[[v55-4-10]]

^<<v55-4-10,10>>^ For Deʹmas has forsaken me because he loved the present system of things,^&#42;1^ and he has gone to Thes·sa·lo·niʹca; Cresʹcens to Ga·laʹti·a, Titus to Dal·maʹtia.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹna; Lat., saeʹcu·lum; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v55-4-11]]

^<<v55-4-11,11>>^ Luke alone is with me. Take Mark and bring him with you, for he is useful to me for ministering.

[[v55-4-12]]

^<<v55-4-12,12>>^ But I have sent Tychʹi·cus off to Ephʹe·sus.

[[v55-4-13]]

^<<v55-4-13,13>>^ When you come, bring the cloak I left at Troʹas with Carpus, and the scrolls,^&#42;1^ especially the parchments.

[NOTE]
====
. Lit., “little books.” Gr., bi·bliʹa; Lat., liʹbros.
====

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexander the coppersmith did me many injuries—Jehovah^&#42;1^ will repay him according to his deeds—

[NOTE]
====
. See App 1D.
====

[[v55-4-15]]

^<<v55-4-15,15>>^ and you too be on guard against him, for he resisted our words to an excessive degree.

[[v55-4-16]]

^<<v55-4-16,16>>^ In my first defense no one came to my side, but they all proceeded to forsake me—may it not be put to their account—

[[v55-4-17]]

^<<v55-4-17,17>>^ but the Lord stood near me and infused power into me, that through me the preaching might be fully accomplished and all the nations might hear it; and I was delivered from the lion’s mouth.

[[v55-4-18]]

^<<v55-4-18,18>>^ The Lord will deliver me from every wicked work and will save &#91;me&#93; for his heavenly kingdom. To him be the glory forever and ever. Amen.

[[v55-4-19]]

^<<v55-4-19,19>>^ Give my greetings to Prisʹca^&#42;1^ and Aqʹui·la and the household of On·e·siphʹo·rus.

[NOTE]
====
. Or, “Priscilla.”
====

[[v55-4-20]]

^<<v55-4-20,20>>^ E·rasʹtus stayed in Corinth, but I left Trophʹi·mus sick at Mi·leʹtus.

[[v55-4-21]]

^<<v55-4-21,21>>^ Do your utmost to arrive before winter.
Eu·buʹlus sends you his greetings, and &#91;so do&#93; Puʹdens and Liʹnus and Clauʹdi·a and all^&#42;1^ the brothers.

[NOTE]
====
. “All,” AVgSyp; א* omits.
====

[[v55-4-22]]

^<<v55-4-22,22>>^ The Lord &#91;be&#93; with the spirit you &#91;show&#93;. His undeserved kindness &#91;be&#93; with YOU people.

'''

xref:055-2-timothy/055-2-timothy-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-titus/056-titus-001.adoc#v56-1-0[Próximo Capítulo &#62;]