include::./index.adoc[]

[[v49-2-0]]
=== To the Ephesians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v49-2-1]]

^<<v49-2-1,1>>^ Furthermore, &#91;it is&#93; YOU &#91;God made alive&#93; though YOU were dead in YOUR trespasses and sins,

[[v49-2-2]]

^<<v49-2-2,2>>^ in which YOU at one time walked according to the system of things^&#42;1^ of this world,^&#42;2^ according to the ruler of the authority of the air, the spirit that now operates in the sons of disobedience.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹna; Lat., saeʹcu·lum; J17(Heb.), dohr, “period; age; generation”; J18(Heb.), kemin·haghʹ, “according to the custom.”
. “World.” Gr., koʹsmou; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the world.”
====

[[v49-2-3]]

^<<v49-2-3,3>>^ Yes, among them we all at one time conducted ourselves in harmony with the desires of our flesh, doing the things willed by the flesh and the thoughts, and we were naturally children of wrath even as the rest.

[[v49-2-4]]

^<<v49-2-4,4>>^ But God, who is rich in mercy, for his great love with which he loved us,

[[v49-2-5]]

^<<v49-2-5,5>>^ made us alive together with the Christ, even when we were dead in trespasses—by undeserved kindness YOU have been saved—

[[v49-2-6]]

^<<v49-2-6,6>>^ and he raised us up together and seated us together in the heavenly places in union with Christ Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ that in the coming systems of things^&#42;1^ there might be demonstrated the surpassing riches of his undeserved kindness in his graciousness toward us in union with Christ Jesus.

[NOTE]
====
. Or, “orders of things.” Gr., ai·oʹsin; Lat., saeʹcu·lis.
====

[[v49-2-8]]

^<<v49-2-8,8>>^ By this undeserved kindness, indeed, YOU have been saved through faith; and this not owing to YOU, it is God’s gift.

[[v49-2-9]]

^<<v49-2-9,9>>^ No, it is not owing to works, in order that no man should have ground for boasting.

[[v49-2-10]]

^<<v49-2-10,10>>^ For we are a product of his work and were created in union with Christ Jesus for good works, which God prepared in advance for us to walk in them.

[[v49-2-11]]

^<<v49-2-11,11>>^ Therefore keep bearing in mind that formerly YOU were people of the nations as to flesh; “uncircumcision” YOU were called by that which is called “circumcision” made in the flesh with hands—

[[v49-2-12]]

^<<v49-2-12,12>>^ that YOU were at that particular time without Christ, alienated from the state of Israel and strangers to the covenants of the promise, and YOU had no hope and were without God in the world.^&#42;1^

[NOTE]
====
. “In the world.” Gr., en toi koʹsmoi; J17,​22(Heb.), ba·ʽoh·lamʹ.
====

[[v49-2-13]]

^<<v49-2-13,13>>^ But now in union with Christ Jesus YOU who were once far off have come to be near by the blood of the Christ.

[[v49-2-14]]

^<<v49-2-14,14>>^ For he is our peace, he who made the two parties^&#42;1^ one and destroyed the wall in between^&#42;2^ that fenced them off.

[NOTE]
====
. Or, “things.”
. Lit., “middle wall.” An allusion to the wall in the area of the temple that fenced off the unsanctified Gentile worshipers from entering the inner courtyards that were open only to the sanctified Jewish worshipers. According to the Mishnah (translated by Danby, 1950, p. 592), the stone barrier was called “the Soreg.” This wall was said to be 1.3 m (4.3 ft) high. See App 9F; see also ad under “Temple,” subheading, “Court of the Gentiles.”
====

[[v49-2-15]]

^<<v49-2-15,15>>^ By means of his flesh he abolished the enmity, the Law of commandments consisting in decrees, that he might create the two peoples in union with himself into one new man and make peace;

[[v49-2-16]]

^<<v49-2-16,16>>^ and that he might fully reconcile both peoples in one body to God through the torture stake, because he had killed off the enmity by means of himself.^&#42;1^

[NOTE]
====
. Or, “it.”
====

[[v49-2-17]]

^<<v49-2-17,17>>^ And he came and declared the good news of peace to YOU, the ones far off, and peace to those near,

[[v49-2-18]]

^<<v49-2-18,18>>^ because through him we, both peoples, have the approach to the Father by^&#42;1^ one spirit.

[NOTE]
====
. Or, “in.”
====

[[v49-2-19]]

^<<v49-2-19,19>>^ Certainly, therefore, YOU are no longer strangers and alien residents, but YOU are fellow citizens of the holy ones and are members of the household of God,

[[v49-2-20]]

^<<v49-2-20,20>>^ and YOU have been built up upon the foundation^&#42;1^ of the apostles and prophets, while Christ Jesus himself is the foundation cornerstone.

[NOTE]
====
. “Foundation.” Gr., the·me·liʹoi, dative, sing.; Lat., fun·da·menʹtum.
====

[[v49-2-21]]

^<<v49-2-21,21>>^ In union with him the whole building, being harmoniously joined together,^&#42;1^ is growing into a holy temple^&#42;2^ for Jehovah.^&#42;3^

[NOTE]
====
. Lit., “being jointed together.”
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplum; J22(Heb.), heh·khalʹ, “palace; temple.”
. See App 1D.
====

[[v49-2-22]]

^<<v49-2-22,22>>^ In union with him YOU, too, are being built up together into a place for God to inhabit by spirit.

'''

xref:049-ephesians/049-ephesians-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-ephesians/049-ephesians-003.adoc#v49-3-0[Próximo Capítulo &#62;]