include::./index.adoc[]

[[v49-3-0]]
=== To the Ephesians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v49-3-1]]

^<<v49-3-1,1>>^ On account of this I, Paul, the prisoner of Christ Jesus in behalf of YOU, the people of the nations—

[[v49-3-2]]

^<<v49-3-2,2>>^ if, really, YOU have heard about the stewardship^&#42;1^ of the undeserved kindness of God that was given me with YOU in view,

[NOTE]
====
. Or, “administering.” See 1:10 ftn, “Administration.”
====

[[v49-3-3]]

^<<v49-3-3,3>>^ that by way of a revelation the sacred secret was made known to me, just as I wrote previously in brief.

[[v49-3-4]]

^<<v49-3-4,4>>^ In the face of this YOU, when YOU read this, can realize the comprehension I have in the sacred secret of the Christ.

[[v49-3-5]]

^<<v49-3-5,5>>^ In other generations this &#91;secret&#93; was not made known to the sons of men as it has now been revealed to his holy apostles and prophets by spirit,

[[v49-3-6]]

^<<v49-3-6,6>>^ namely, that people of the nations should be joint heirs and fellow members of the body and partakers with us of the promise in union with Christ Jesus through the good news.

[[v49-3-7]]

^<<v49-3-7,7>>^ I became a minister of this according to the free gift of the undeserved kindness of God that was given me according to the way his power operates.

[[v49-3-8]]

^<<v49-3-8,8>>^ To me, a man less than the least of all holy ones, this undeserved kindness was given, that I should declare to the nations the good news about the unfathomable riches of the Christ

[[v49-3-9]]

^<<v49-3-9,9>>^ and should make men see^&#42;1^ how the sacred secret is administered^&#42;2^ which has from the indefinite past been hidden in God, who created all things.

[NOTE]
====
. Or, “should bring to light.”
. Lit., “what is the house administration of the mystery (sacred secret).”
====

[[v49-3-10]]

^<<v49-3-10,10>>^ &#91;This was&#93; to the end that now to the governments and the authorities in the heavenly places there might be made known through the congregation the greatly diversified wisdom of God,

[[v49-3-11]]

^<<v49-3-11,11>>^ according to the eternal purpose that he formed in connection with the Christ, Jesus our Lord,

[[v49-3-12]]

^<<v49-3-12,12>>^ by means of whom we have this freeness of speech and an approach with confidence through our faith in him.

[[v49-3-13]]

^<<v49-3-13,13>>^ Wherefore I ask YOU not to give up on account of these tribulations of mine in YOUR behalf, for these mean^&#42;1^ glory for YOU.

[NOTE]
====
. Or, “for this means.” Lit., “which is.”
====

[[v49-3-14]]

^<<v49-3-14,14>>^ On account of this I bend my knees to the Father,

[[v49-3-15]]

^<<v49-3-15,15>>^ to whom every family in heaven and on earth owes its name,

[[v49-3-16]]

^<<v49-3-16,16>>^ to the end that he may grant YOU according to the riches of his glory to be made mighty in the man YOU are inside with power through his spirit,

[[v49-3-17]]

^<<v49-3-17,17>>^ to have the Christ dwell through &#91;YOUR&#93; faith in YOUR hearts with^&#42;1^ love; that YOU may be rooted and established on the foundation,

[NOTE]
====
. Or, “in.”
====

[[v49-3-18]]

^<<v49-3-18,18>>^ in order that YOU may be thoroughly able to grasp mentally with all the holy ones what is the breadth and length and height and depth,

[[v49-3-19]]

^<<v49-3-19,19>>^ and to know the love of the Christ which surpasses knowledge, that YOU may be filled with all^&#42;1^ the fullness that God gives.

[NOTE]
====
. Or, “may be filled up to all.”
====

[[v49-3-20]]

^<<v49-3-20,20>>^ Now to the one who can, according to his power which is operating in us, do more than superabundantly beyond all the things we ask or conceive,

[[v49-3-21]]

^<<v49-3-21,21>>^ to him be the glory by means of the congregation and by means of Christ Jesus to all generations forever and ever. Amen.

'''

xref:049-ephesians/049-ephesians-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-ephesians/049-ephesians-004.adoc#v49-4-0[Próximo Capítulo &#62;]