include::./index.adoc[]

[[v49-5-0]]
=== To the Ephesians, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v49-5-1]]

^<<v49-5-1,1>>^ Therefore, become imitators of God, as beloved children,

[[v49-5-2]]

^<<v49-5-2,2>>^ and go on walking in love, just as the Christ also loved YOU and delivered himself up for YOU as an offering and a sacrifice to God for a sweet-smelling odor.

[[v49-5-3]]

^<<v49-5-3,3>>^ Let fornication and uncleanness of every sort or greediness^&#42;1^ not even be mentioned among YOU, just as it befits holy people;

[NOTE]
====
. Or, “covetousness.” Lit., “having more,” that is, a desire to have more; insatiableness. Gr., ple·o·ne·xiʹa.
====

[[v49-5-4]]

^<<v49-5-4,4>>^ neither shameful conduct nor foolish talking nor obscene jesting, things which are not becoming, but rather the giving of thanks.

[[v49-5-5]]

^<<v49-5-5,5>>^ For YOU know this, recognizing it for yourselves, that no fornicator or unclean person or greedy person—which means being an idolater—has any inheritance in the kingdom of the Christ and of God.^&#42;1^

[NOTE]
====
. See App 6E.
====

[[v49-5-6]]

^<<v49-5-6,6>>^ Let no man deceive YOU with empty words, for because of the aforesaid^&#42;1^ things the wrath of God is coming upon the sons of disobedience.

[NOTE]
====
. Or, “because of these.”
====

[[v49-5-7]]

^<<v49-5-7,7>>^ Therefore do not become partakers with them;

[[v49-5-8]]

^<<v49-5-8,8>>^ for YOU were once darkness, but YOU are now light in connection with &#91;the&#93; Lord. Go on walking as children of light,

[[v49-5-9]]

^<<v49-5-9,9>>^ for the fruitage of the light consists of every sort of goodness and righteousness and truth.

[[v49-5-10]]

^<<v49-5-10,10>>^ Keep on making sure of what is acceptable to the Lord;

[[v49-5-11]]

^<<v49-5-11,11>>^ and quit sharing with &#91;them&#93; in the unfruitful works that belong to the darkness, but, rather, even be reproving &#91;them&#93;,

[[v49-5-12]]

^<<v49-5-12,12>>^ for the things that take place in secret by them it is shameful even to relate.

[[v49-5-13]]

^<<v49-5-13,13>>^ Now all the things that are being reproved are made manifest by the light, for everything that is being made manifest is light.

[[v49-5-14]]

^<<v49-5-14,14>>^ Wherefore he^&#42;1^ says: “Awake, O sleeper, and arise from the dead, and the Christ will shine upon you.”

[NOTE]
====
. Or, “it.”
====

[[v49-5-15]]

^<<v49-5-15,15>>^ So keep strict watch that how YOU walk is not as unwise but as wise &#91;persons&#93;,

[[v49-5-16]]

^<<v49-5-16,16>>^ buying out the opportune time for yourselves, because the days are wicked.

[[v49-5-17]]

^<<v49-5-17,17>>^ On this account cease becoming unreasonable, but go on perceiving what the will of Jehovah^&#42;1^ is.

[NOTE]
====
. “Of Jehovah,” J7,​8; אD(Gr.), tou Ky·riʹou; AVgcSyp, “of God”; B, “of our Lord”; P46, “of the Christ.” See App 1D.
====

[[v49-5-18]]

^<<v49-5-18,18>>^ Also, do not be getting drunk with wine, in which there is debauchery, but keep getting filled with spirit,

[[v49-5-19]]

^<<v49-5-19,19>>^ speaking to yourselves with psalms and praises to God and spiritual songs, singing and accompanying yourselves with music in YOUR hearts to Jehovah,^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v49-5-20]]

^<<v49-5-20,20>>^ in the name of our Lord Jesus Christ giving thanks always for all things to our^&#42;1^ God and Father.

[NOTE]
====
. Lit., “to the.”
====

[[v49-5-21]]

^<<v49-5-21,21>>^ Be in subjection to one another in fear of Christ.

[[v49-5-22]]

^<<v49-5-22,22>>^ Let wives be in subjection to their husbands as to the Lord,

[[v49-5-23]]

^<<v49-5-23,23>>^ because a husband is head of his wife as the Christ also is head of the congregation, he being a savior of &#91;this&#93; body.

[[v49-5-24]]

^<<v49-5-24,24>>^ In fact, as the congregation is in subjection to the Christ, so let wives also be to their husbands in everything.

[[v49-5-25]]

^<<v49-5-25,25>>^ Husbands, continue loving YOUR wives, just as the Christ also loved the congregation and delivered up himself for it,

[[v49-5-26]]

^<<v49-5-26,26>>^ that he might sanctify it, cleansing it with the bath of water by means of the word,

[[v49-5-27]]

^<<v49-5-27,27>>^ that he might present the congregation to himself in its splendor, not having a spot or a wrinkle or any of such things, but that it should be holy and without blemish.

[[v49-5-28]]

^<<v49-5-28,28>>^ In this way husbands ought to be loving their wives as their own bodies. He who loves his wife loves himself,

[[v49-5-29]]

^<<v49-5-29,29>>^ for no man ever hated his own flesh; but he feeds and cherishes it, as the Christ also does the congregation,

[[v49-5-30]]

^<<v49-5-30,30>>^ because we are members of his body.

[[v49-5-31]]

^<<v49-5-31,31>>^ “For this reason a man will leave &#91;his&#93; father and &#91;his&#93; mother and he will stick to his wife, and the two will become one flesh.”

[[v49-5-32]]

^<<v49-5-32,32>>^ This sacred secret is great. Now I am speaking with respect to Christ and the congregation.

[[v49-5-33]]

^<<v49-5-33,33>>^ Nevertheless, also, let each one of YOU individually so love his wife as he does himself; on the other hand, the wife should have deep respect for her husband.

'''

xref:049-ephesians/049-ephesians-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-ephesians/049-ephesians-006.adoc#v49-6-0[Próximo Capítulo &#62;]