include::./index.adoc[]

[[v49-6-0]]
=== To the Ephesians, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v49-6-1]]

^<<v49-6-1,1>>^ Children, be obedient^&#42;1^ to YOUR parents in union with &#91;the&#93; Lord,^&#42;2^ for this is righteous:

[NOTE]
====
. Lit., “be you obeying.”
. “In union with [the] Lord,” P46אADcVgSyh,pArm; BD* omit.
====

[[v49-6-2]]

^<<v49-6-2,2>>^ “Honor your father and &#91;your&#93; mother”; which is the first command with a promise:

[[v49-6-3]]

^<<v49-6-3,3>>^ “That it may go well with you and you may endure a long time on the earth.”

[[v49-6-4]]

^<<v49-6-4,4>>^ And YOU, fathers, do not be irritating^&#42;1^ YOUR children, but go on bringing them up in the discipline and mental-regulating^&#42;2^ of Jehovah.^&#42;3^

[NOTE]
====
. Lit., “not be you provoking to wrath.”
. Lit., “putting mind in.”
. See App 1D.
====

[[v49-6-5]]

^<<v49-6-5,5>>^ YOU slaves, be obedient to those who are &#91;YOUR&#93; masters in a fleshly sense, with fear and trembling in the sincerity of YOUR hearts, as to the Christ,

[[v49-6-6]]

^<<v49-6-6,6>>^ not by way of eye-service as men pleasers, but as Christ’s slaves, doing the will of God whole-souled.

[[v49-6-7]]

^<<v49-6-7,7>>^ Be slaves with good inclinations, as to Jehovah,^&#42;1^ and not to men,

[NOTE]
====
. See App 1D.
====

[[v49-6-8]]

^<<v49-6-8,8>>^ for YOU know that each one, whatever good he may do, will receive this back from Jehovah,^&#42;1^ whether he be slave or freeman.

[NOTE]
====
. See App 1D.
====

[[v49-6-9]]

^<<v49-6-9,9>>^ Also, YOU masters, keep doing the same things to them, letting up on the threatening, for YOU know that the Master^&#42;1^ of both them and YOU is in the heavens, and there is no partiality with him.

[NOTE]
====
. Or, “Lord.”
====

[[v49-6-10]]

^<<v49-6-10,10>>^ Finally, go on acquiring power in &#91;the&#93; Lord and in the mightiness of his strength.

[[v49-6-11]]

^<<v49-6-11,11>>^ Put on the complete suit of armor from God that YOU may be able to stand firm against the machinations^&#42;1^ of the Devil;

[NOTE]
====
. Or, “crafty acts.” Gr., me·tho·diʹas; Lat., in·siʹdi·as.
====

[[v49-6-12]]

^<<v49-6-12,12>>^ because we have a wrestling, not against blood and flesh, but against the governments, against the authorities, against the world rulers^&#42;1^ of this darkness, against the wicked spirit forces in the heavenly places.

[NOTE]
====
. Lit., “world-mighty ones.” Gr., ko·smo·kraʹto·ras.
====

[[v49-6-13]]

^<<v49-6-13,13>>^ On this account take up the complete suit of armor^&#42;1^ from God, that YOU may be able to resist in the wicked day and, after YOU have done all things thoroughly, to stand firm.

[NOTE]
====
. Lit., “the panoply.” Gr., ten pa·no·pliʹan; Lat., ar·ma·tuʹram.
====

[[v49-6-14]]

^<<v49-6-14,14>>^ Stand firm, therefore, with YOUR loins girded about with truth, and having on the breastplate of righteousness,

[[v49-6-15]]

^<<v49-6-15,15>>^ and with YOUR feet shod with the equipment^&#42;1^ of the good news of peace.

[NOTE]
====
. “With the equipment.” Lit., “in readiness; in preparedness.”
====

[[v49-6-16]]

^<<v49-6-16,16>>^ Above all things, take up the large shield of faith, with which YOU will be able to quench all the wicked one’s burning missiles.

[[v49-6-17]]

^<<v49-6-17,17>>^ Also, accept the helmet of salvation, and the sword of the spirit, that is, God’s word,

[[v49-6-18]]

^<<v49-6-18,18>>^ while with every form of prayer and supplication YOU carry on prayer on every occasion in spirit. And to that end keep awake with all constancy and with supplication in behalf of all the holy ones,

[[v49-6-19]]

^<<v49-6-19,19>>^ also for me, that ability to speak may be given me with the opening of my mouth, with freeness of speech to make known the sacred secret of the good news,

[[v49-6-20]]

^<<v49-6-20,20>>^ for which I am acting as an ambassador in chains; that I may speak in connection with it with boldness^&#42;1^ as I ought to speak.

[NOTE]
====
. Or, “with freeness of speech.”
====

[[v49-6-21]]

^<<v49-6-21,21>>^ Now in order that YOU may also know about my affairs, as to how I am doing, Tychʹi·cus, a beloved brother and faithful minister in &#91;the&#93; Lord, will make everything known to YOU.

[[v49-6-22]]

^<<v49-6-22,22>>^ I am sending him to YOU for this very purpose, that YOU may know of the things having to do with us and that he may comfort YOUR hearts.

[[v49-6-23]]

^<<v49-6-23,23>>^ May the brothers have peace and love with faith from God the Father and the Lord Jesus Christ.

[[v49-6-24]]

^<<v49-6-24,24>>^ May the undeserved kindness be with all those loving our Lord Jesus Christ in incorruptness.

'''

xref:049-ephesians/049-ephesians-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-philippians/050-philippians-001.adoc#v50-1-0[Próximo Capítulo &#62;]