include::./index.adoc[]

[[v49-1-0]]
=== To the Ephesians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v49-1-1]]

^<<v49-1-1,1>>^ Paul, an apostle of Christ Jesus through God’s will, to the holy ones who are &#91;in Ephʹe·sus&#93;^&#42;1^ and faithful ones in union with Christ Jesus:

[NOTE]
====
. “In Ephesus,” אcABcDVgSyh,p; P46א*B* omit.
====

[[v49-1-2]]

^<<v49-1-2,2>>^ May YOU have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[[v49-1-3]]

^<<v49-1-3,3>>^ Blessed be the God and Father of our Lord Jesus Christ, for he has blessed us with every spiritual blessing in the heavenly places in union with Christ,

[[v49-1-4]]

^<<v49-1-4,4>>^ just as he chose us in union with him before the founding^&#42;1^ of the world, that we should be holy and without blemish before him in love.

[NOTE]
====
. Lit., “a throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v49-1-5]]

^<<v49-1-5,5>>^ For he foreordained^&#42;1^ us to the adoption through Jesus Christ as sons to himself, according to the good pleasure of his will,

[NOTE]
====
. Or, “without blemish before him. For in love (5) he foreordained.”
====

[[v49-1-6]]

^<<v49-1-6,6>>^ in praise of his glorious undeserved kindness which he kindly conferred upon us by means of &#91;his&#93; loved one.

[[v49-1-7]]

^<<v49-1-7,7>>^ By means of him we have the release by ransom through the blood of that one, yes, the forgiveness of &#91;our&#93; trespasses, according to the riches of his undeserved kindness.

[[v49-1-8]]

^<<v49-1-8,8>>^ This he caused to abound toward us in all wisdom and good sense,

[[v49-1-9]]

^<<v49-1-9,9>>^ in that^&#42;1^ he made known to us the sacred secret of his will. It is according to his good pleasure which he purposed in himself

[NOTE]
====
. “In that.” Or, “and.”
====

[[v49-1-10]]

^<<v49-1-10,10>>^ for an administration^&#42;1^ at the full limit of the appointed times, namely, to gather all things together again^&#42;2^ in the Christ, the things in the heavens and the things on the earth. &#91;Yes,&#93; in him,

[NOTE]
====
. Lit., “house administration; household management.” Gr., oi·ko·no·miʹan; Lat., di·spen·sa·ti·oʹnem. See Lu 12:42 ftn.
. “To gather . . . together again.” According to G. H. Thayer’s Greek-English Lexicon of the New Testament, fourth ed. (1901), p. 39, “to bring together again for himself.”
====

[[v49-1-11]]

^<<v49-1-11,11>>^ in union with whom we were also assigned as heirs, in that we were foreordained according to the purpose of him who operates all things according to the way his will counsels,

[[v49-1-12]]

^<<v49-1-12,12>>^ that we should serve for the praise of his glory, we who have been first to hope^&#42;1^ in the Christ.

[NOTE]
====
. Or, “we who have hoped beforehand.”
====

[[v49-1-13]]

^<<v49-1-13,13>>^ But YOU also hoped in him after YOU heard the word of truth, the good news about YOUR salvation. By means of him also, after YOU believed,^&#42;1^ YOU were sealed with the promised holy spirit,

[NOTE]
====
. Or, “After believing in him also.”
====

[[v49-1-14]]

^<<v49-1-14,14>>^ which^&#42;1^ is a token in advance^&#42;2^ of our inheritance, for the purpose of releasing by a ransom &#91;God’s&#93; own^&#42;3^ possession, to his glorious praise.

[NOTE]
====
. “Which,” P46AB; אDVg, “who.”
. Or, “earnest money (down payment) in advance.” Gr., ar·ra·bonʹ; J18,​22(Heb.), ʽe·ra·vohnʹ. See 2Co 1:22 ftn.
. Lit., “of the.”
====

[[v49-1-15]]

^<<v49-1-15,15>>^ That is why I also, since I have heard of the faith YOU have in the Lord Jesus and toward all the holy ones,

[[v49-1-16]]

^<<v49-1-16,16>>^ do not cease giving thanks for YOU. I continue mentioning YOU in my prayers,

[[v49-1-17]]

^<<v49-1-17,17>>^ that the God of our Lord Jesus Christ, the Father of glory, may give YOU a spirit of wisdom and of revelation^&#42;1^ in the accurate knowledge of him;

[NOTE]
====
. Lit., “uncovering; disclosure.” Gr., a·po·ka·lyʹpse·os.
====

[[v49-1-18]]

^<<v49-1-18,18>>^ the eyes of YOUR heart having been enlightened, that YOU may know what is the hope to which he called YOU, what the glorious riches are which he holds as an inheritance for^&#42;1^ the holy ones,

[NOTE]
====
. Or, “which he inherits in.”
====

[[v49-1-19]]

^<<v49-1-19,19>>^ and what the surpassing greatness of his power is toward us believers. It is according to the operation of the mightiness of his strength,

[[v49-1-20]]

^<<v49-1-20,20>>^ with which he has operated in the case of the Christ when he raised him up from the dead and seated him at his right hand in the heavenly places,

[[v49-1-21]]

^<<v49-1-21,21>>^ far above every government and authority and power and lordship and every name named, not only in this system of things,^&#42;1^ but also in that to come.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹni; Lat., saeʹcu·lo; J17,​18,​22(Heb.), ba·ʽoh·lamʹ haz·zehʹ, “in this order of things.”
====

[[v49-1-22]]

^<<v49-1-22,22>>^ He also subjected all things under his feet, and made him head over all things to the congregation,

[[v49-1-23]]

^<<v49-1-23,23>>^ which is his body, the fullness of him who fills up all things in all.

'''

xref:048-galatians/048-galatians-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-ephesians/049-ephesians-002.adoc#v49-2-0[Próximo Capítulo &#62;]