include::./index.adoc[]

[[v10-16-0]]
=== The Second of Samuel, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-16-1]]

^<<v10-16-1,1>>^ When David himself had crossed over a little beyond the summit, there was Ziʹba the attendant of Me·phibʹo·sheth to meet him with a couple of asses saddled and upon them two hundred loaves of bread and a hundred cakes of raisins and a hundred loads of summer fruit and a large jar of wine.

[[v10-16-2]]

^<<v10-16-2,2>>^ Then the king said to Ziʹba: “What do these things mean on your part?” To this Ziʹba said: “The asses are for the household of the king to ride, and the bread and the load of summer fruit are for the young men to eat, and the wine is for the one tired out in the wilderness to drink.”

[[v10-16-3]]

^<<v10-16-3,3>>^ The king now said: “And where is the son of your master?”^&#42;1^ At this Ziʹba said to the king: “There he is dwelling in Jerusalem; for he said, ‘Today the house of Israel will give back to me the royal rule of my father.’”

[NOTE]
====
. “Your master.” Heb., ʼadho·neyʹkha, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v10-16-4]]

^<<v10-16-4,4>>^ The king then said to Ziʹba: “Look! Yours is everything that belongs to Me·phibʹo·sheth.” Upon that Ziʹba said: “I do bow down. Let me find favor in your eyes, my lord the king.”

[[v10-16-5]]

^<<v10-16-5,5>>^ And King David came as far as Ba·huʹrim, and, look! coming out from there was a man of the family of Saul’s house, and his name was Shimʹe·i, the son of Geʹra, coming out and calling down evil as he came out.

[[v10-16-6]]

^<<v10-16-6,6>>^ And he began throwing stones at David and at all the servants of King David; and all the people and all the mighty men were at his right and at his left.

[[v10-16-7]]

^<<v10-16-7,7>>^ And this is what Shimʹe·i said as he called down evil: “Get out, get out, you bloodguilty man^&#42;1^ and good-for-nothing man!^&#42;2^

[NOTE]
====
. Lit., “man of the bloods.” Heb., ʼish had·da·mimʹ, pl.
. Or, “and man of worthlessness.” Lit., “and man of the belial.” Heb., weʼishʹ hab·beli·yaʹʽal.
====

[[v10-16-8]]

^<<v10-16-8,8>>^ Jehovah has brought back upon you all the bloodguilt for the house of Saul in place of whom you have ruled as king; and Jehovah gives the kingship into the hand of Abʹsa·lom your son. And here you are in your calamity, because you are a bloodguilty man!”

[[v10-16-9]]

^<<v10-16-9,9>>^ Finally A·bishʹai the son of Ze·ruʹiah said to the king: “Why should this dead dog call down evil upon my lord the king? Let me go over, please, and take off his head.”

[[v10-16-10]]

^<<v10-16-10,10>>^ But the king said: “What do I have to do with YOU men,^&#42;1^ YOU sons of Ze·ruʹiah? Thus let him call down evil, because Jehovah himself has said to him, ‘Call down evil upon David!’ So who^&#42;2^ should say, ‘Why did you do that way?’”

[NOTE]
====
. Lit., “What [is there] to me and to you men?” A Heb. idiom; a repellent question indicating objection to the action proposed by Abishai. See App 7B.
. According to Mmargin; M, “In case he calls down evil and in case Jehovah has said to him, ‘Call down evil upon David!’ who, then?”
====

[[v10-16-11]]

^<<v10-16-11,11>>^ And David went on to say to A·bishʹai and all his servants: “Here my own son, who has come forth out of my own inward parts, is looking for my soul; and how much more now a Benʹja·min·ite! Let him alone that he may call down evil, for Jehovah has said so to him!

[[v10-16-12]]

^<<v10-16-12,12>>^ Perhaps Jehovah will see with his eye,^&#42;1^ and Jehovah will actually restore to me goodness instead of his malediction this day.”

[NOTE]
====
. “With his eye.” One of the Eighteen Emendations. Here the Sopherim made the text read “on my error,” that is, on the error committed against me. LXXSyVg, “on my affliction.” See App 2B.
====

[[v10-16-13]]

^<<v10-16-13,13>>^ With that David and his men kept going on in the road, while Shimʹe·i was walking on the side of the mountain, walking abreast of him that he might call down evil; and he kept throwing stones while abreast of him, and he threw a lot of dust.

[[v10-16-14]]

^<<v10-16-14,14>>^ At length the king and all the people that were with him arrived tired. So they refreshed themselves there.

[[v10-16-15]]

^<<v10-16-15,15>>^ As for Abʹsa·lom and all the people, the men of Israel, they entered Jerusalem; and A·hithʹo·phel was with him.

[[v10-16-16]]

^<<v10-16-16,16>>^ And it came about that, as soon as Huʹshai the Arʹchite, David’s companion, came in to Abʹsa·lom, Huʹshai proceeded to say to Abʹsa·lom: “Let the king live! Let the king live!”

[[v10-16-17]]

^<<v10-16-17,17>>^ At this Abʹsa·lom said to Huʹshai: “This is the loving-kindness of yours toward your companion, is it? Why did you not go with your companion?”

[[v10-16-18]]

^<<v10-16-18,18>>^ So Huʹshai said to Abʹsa·lom: “No; but the one whom Jehovah has chosen and also this people and all the men of Israel, his I shall become,^&#42;1^ and with him I shall dwell.

[NOTE]
====
. Or, “I shall prove to be.” Compare Ex 3:14.
====

[[v10-16-19]]

^<<v10-16-19,19>>^ And for the second time &#91;I must say&#93;, Whom shall I myself serve? Is it not before his son? Just as I served before your father, so I shall prove to be^&#42;1^ before you.”

[NOTE]
====
. See vs 18 ftn.
====

[[v10-16-20]]

^<<v10-16-20,20>>^ Later Abʹsa·lom said to A·hithʹo·phel: “YOU men, give counsel on YOUR part. What shall we do?”

[[v10-16-21]]

^<<v10-16-21,21>>^ Then A·hithʹo·phel said to Abʹsa·lom: “Have relations with the concubines of your father, whom he left behind to take care of the house. And all Israel will certainly hear that you have made yourself foul-smelling to your father, and the hands of all those who are with you will certainly become strong.”

[[v10-16-22]]

^<<v10-16-22,22>>^ Accordingly they pitched a tent for Abʹsa·lom upon the roof, and Abʹsa·lom began to have relations with the concubines of his father under the eyes of all Israel.

[[v10-16-23]]

^<<v10-16-23,23>>^ And the counsel of A·hithʹo·phel, with which he counseled in those days, was just as when a man^&#42;1^ would inquire of the word of the &#91;true&#93; God.^&#42;2^ That was the way all the counsel of A·hithʹo·phel was both to David and to Abʹsa·lom.

[NOTE]
====
. “A man,” 30 Heb. mss; in M only the vowel point appears. This is qere but not kethib (read but not written). See Jg 20:13 ftn.
. “Of the word of the [true] God.” Heb., bidh·varʹ ha·ʼElo·himʹ. The definite article ha, “the,” preceding the title ʼElo·himʹ is for emphasis. This is the first occurrence of the expression. Many translators take bidh·varʹ (from da·varʹ, “word”) to be equivalent to devirʹ, “innermost room,” as in 1Ki 6:5. See App 1F.
====

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]