include::./index.adoc[]

[[v10-2-0]]
=== The Second of Samuel, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-2-1]]

^<<v10-2-1,1>>^ And it came about afterward that David proceeded to inquire of Jehovah, saying: “Shall I go up into one of the cities of Judah?” At this Jehovah said to him: “Go up.” And David went on to say: “Where shall I go up?” Then he said: “To Heʹbron.”

[[v10-2-2]]

^<<v10-2-2,2>>^ Accordingly David went up there and also his two wives, A·hinʹo·am the Jezʹre·el·i·tess and Abʹi·gail the wife of Naʹbal the Carʹmel·ite.

[[v10-2-3]]

^<<v10-2-3,3>>^ And the men that were with him David brought up, each with his household; and they took up dwelling in the cities of Heʹbron &#91;territory&#93;.

[[v10-2-4]]

^<<v10-2-4,4>>^ Then the men of Judah came and anointed David there as king over the house of Judah.
And they came telling David, saying: “The men of Jaʹbesh-gilʹe·ad were the ones that buried Saul.”

[[v10-2-5]]

^<<v10-2-5,5>>^ Hence David sent messengers to the men of Jaʹbesh-gilʹe·ad and said to them: “Blessed may YOU be of Jehovah, because YOU exercised this loving-kindness^&#42;1^ toward YOUR lord,^&#42;2^ toward Saul, in that YOU buried him.

[NOTE]
====
. Or, “loyal love.”
. “Your lord.” Heb., ʼadho·neh·khemʹ, pl. to denote excellence. See Ge 39:2 ftn.
====

[[v10-2-6]]

^<<v10-2-6,6>>^ And now may Jehovah exercise toward YOU loving-kindness and trustworthiness,^&#42;1^ and I too shall exercise to YOU this goodness because YOU have done this thing.

[NOTE]
====
. Or, “truth.”
====

[[v10-2-7]]

^<<v10-2-7,7>>^ And now let YOUR hands strengthen themselves and prove yourselves valiant men, because YOUR lord Saul is dead, and it is even I whom the house of Judah have anointed as king over them.”

[[v10-2-8]]

^<<v10-2-8,8>>^ As for Abʹner the son of Ner the chief of the army that had belonged to Saul, he took Ish-boʹsheth, Saul’s son, and proceeded to bring him across^&#42;1^ to Ma·ha·naʹim,

[NOTE]
====
. “Bring him out of the camp,” LXX.
====

[[v10-2-9]]

^<<v10-2-9,9>>^ and to make him king over Gilʹe·ad and the Ashʹur·ites^&#42;1^ and Jezʹre·el and over Eʹphra·im and Benjamin and over Israel, all of it.

[NOTE]
====
. “Geshurites,” SyVg; T, “Asherites.”
====

[[v10-2-10]]

^<<v10-2-10,10>>^ Forty years old Ish-boʹsheth, Saul’s son, was when he became king over Israel, and for two years he ruled as king. Only the house of Judah proved themselves followers of David.

[[v10-2-11]]

^<<v10-2-11,11>>^ And the number of the days that David proved to be king in Heʹbron over the house of Judah came to be seven years and six months.

[[v10-2-12]]

^<<v10-2-12,12>>^ In time Abʹner the son of Ner and the servants of Ish-boʹsheth, Saul’s son, went out from Ma·ha·naʹim to Gibʹe·on.

[[v10-2-13]]

^<<v10-2-13,13>>^ As for Joʹab the son of Ze·ruʹiah and the servants of David, they went out^&#42;1^ and later met together by the pool of Gibʹe·on; and they kept sitting, these on this side of the pool and those on that side of the pool.

[NOTE]
====
. “Went out from Hebron,” LXX.
====

[[v10-2-14]]

^<<v10-2-14,14>>^ Finally Abʹner said to Joʹab: “Let the young men rise up, please, and let them put on a combat before us.” To this Joʹab said: “Let them rise up.”

[[v10-2-15]]

^<<v10-2-15,15>>^ So they rose up and went across by number, twelve belonging to Benjamin and Ish-boʹsheth, Saul’s son, and twelve from the servants of David.

[[v10-2-16]]

^<<v10-2-16,16>>^ And they began grabbing hold of one another by the head, with the sword of each one in the side of the other, so that they fell down together. And that place came to be called Helʹkath-haz·zuʹrim,^&#42;1^ which is in Gibʹe·on.

[NOTE]
====
. Meaning “Field of Flint Knives”; or, by an emendation, “Field of Sides.” Compare Jos 5:2 ftn.
====

[[v10-2-17]]

^<<v10-2-17,17>>^ And the fighting came to be extremely hard on that day, and Abʹner and the men of Israel were finally defeated before the servants of David.

[[v10-2-18]]

^<<v10-2-18,18>>^ Now the three sons of Ze·ruʹiah happened to be there, Joʹab and A·bishʹai and Asʹa·hel; and Asʹa·hel was swift on his feet, like one of the gazelles that are in the open field.

[[v10-2-19]]

^<<v10-2-19,19>>^ And Asʹa·hel went chasing after Abʹner, and he did not incline to go to the right or to the left from following Abʹner.

[[v10-2-20]]

^<<v10-2-20,20>>^ At length Abʹner looked behind him and said: “Is this you, Asʹa·hel?” to which he said: “It is I.”

[[v10-2-21]]

^<<v10-2-21,21>>^ Then Abʹner said to him: “Veer to your right or to your left and seize one of the young men as yours and take what you strip off him as yours.” And Asʹa·hel did not want to turn aside from following him.

[[v10-2-22]]

^<<v10-2-22,22>>^ So Abʹner said to Asʹa·hel yet again: “Turn your course aside from following me. Why should I strike^&#42;1^ you down to the earth? How, then, could I raise my face to Joʹab your brother?”

[NOTE]
====
. “Following me lest I strike,” LXX.
====

[[v10-2-23]]

^<<v10-2-23,23>>^ But he kept refusing to turn aside; and Abʹner got to strike him in the abdomen with the butt end^&#42;1^ of the spear, so that the spear came out from his back; and he fell there and died where he was. And it came about that all those who came to the place where Asʹa·hel fell and then died would stand still.

[NOTE]
====
. Or, “the hinder part,” possibly striking with a backward movement of the spear.
====

[[v10-2-24]]

^<<v10-2-24,24>>^ And Joʹab and A·bishʹai went chasing after Abʹner. As the sun was setting they themselves came to the hill of Amʹmah, which is in front of Giʹah on the way to the wilderness of Gibʹe·on.

[[v10-2-25]]

^<<v10-2-25,25>>^ And the sons of Benjamin went collecting together behind Abʹner, and they came to be one company and kept standing upon the top of one hill.

[[v10-2-26]]

^<<v10-2-26,26>>^ And Abʹner began to call to Joʹab and say: “Is the sword going to eat endlessly? Do you not really know that bitterness is what will develop at last? How long, then, will it be before you say to the people to turn back from following their brothers?”

[[v10-2-27]]

^<<v10-2-27,27>>^ At that Joʹab said: “As the &#91;true&#93; God^&#42;1^ is living, if you had not spoken, then only by the morning would the people have been withdrawn, each one from following his brother.”

[NOTE]
====
. “The [true] God.” See App 1F.
====

[[v10-2-28]]

^<<v10-2-28,28>>^ Joʹab now blew the horn, and all the people came to a halt and did not continue chasing after Israel anymore, and they did not renew the fighting anymore.

[[v10-2-29]]

^<<v10-2-29,29>>^ As for Abʹner and his men, they marched through the Arʹa·bah all that night and went crossing the Jordan and marching through the entire gully and finally came to Ma·ha·naʹim.

[[v10-2-30]]

^<<v10-2-30,30>>^ As for Joʹab, he turned back from following Abʹner and began to collect all the people together. And there were missing from the servants of David nineteen men and Asʹa·hel.

[[v10-2-31]]

^<<v10-2-31,31>>^ And the servants of David, for their part, had struck down those of Benjamin and of the men of Abʹner—there were three hundred and sixty men that died.

[[v10-2-32]]

^<<v10-2-32,32>>^ And they proceeded to carry Asʹa·hel and bury him in the burial place of his father, which is at Bethʹle·hem. Then Joʹab and his men went marching on all night long, and it became daylight for them at Heʹbron.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]