include::./index.adoc[]

[[v10-23-0]]
=== The Second of Samuel, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-23-1]]

^<<v10-23-1,1>>^ And these are the last words of David:
“The utterance of David the son of Jesʹse,
And the utterance of the able-bodied man^&#42;1^ that was raised up on high,
The anointed of the God of Jacob,
And the pleasant one of the melodies^&#42;2^ of Israel.^&#42;3^

[NOTE]
====
. “The able-bodied man.” Heb., hag·geʹver.
. “Melodies of.” Heb., zemi·rohthʹ, that is, musically accompanied songs.
. Or, “and the pleasant singer of Israel.”
====

[[v10-23-2]]

^<<v10-23-2,2>>^ The spirit of Jehovah it was that spoke by me,
And his word^&#42;1^ was upon my tongue.

[NOTE]
====
. “And his word.” Heb., u·mil·la·thohʹ (from mil·lahʹ), a word used only in poetry, as in Ps 19:4; Ps 139:4; Pr 23:9 and 34 times in Job.
====

[[v10-23-3]]

^<<v10-23-3,3>>^ The God of Israel said,
To me the Rock of Israel spoke,
‘When one ruling over mankind is righteous,
Ruling in the fear of God,

[[v10-23-4]]

^<<v10-23-4,4>>^ Then it is as the light of morning, when the sun shines forth,
A morning without clouds.
From brightness, from rain, there is grass out of the earth.’

[[v10-23-5]]

^<<v10-23-5,5>>^ For is not my household like that with God?^&#42;1^
Because it is an indefinitely lasting covenant^&#42;2^ that he has assigned to me,
Nicely put in order in everything and secured.
Because it is all my salvation and all my delight,
Is that not why he will make it grow?

[NOTE]
====
. “God.” Heb., ʼEl; Lat., Deʹum; LXX, “the Strong One.”
. Or, “a covenant of indefinite time.”
====

[[v10-23-6]]

^<<v10-23-6,6>>^ But good-for-nothing persons are chased away, like thornbushes, all of them;
For it is not by the hand that they should be taken.

[[v10-23-7]]

^<<v10-23-7,7>>^ When a man touches them
He should be fully armed with iron and the shaft of a spear,
And with fire they will thoroughly be burned up.”^&#42;1^

[NOTE]
====
. M adds, “in the dwelling,” but this expression seems to have been inserted inadvertently because of the similar Heb. expression bash·sheʹveth in the next line.
====

[[v10-23-8]]

^<<v10-23-8,8>>^ These are the names of the mighty men that belonged to David: Joʹsheb-bas·sheʹbeth a Tah·cheʹmo·nite, the head of the three.^&#42;1^ He was brandishing his spear^&#42;2^ over eight hundred slain at one time.

[NOTE]
====
. “Three,” LXXL.
. “He was brandishing his spear,” by a correction of M in agreement with 1Ch 11:11; M, “He was Adino the Eznite.”
====

[[v10-23-9]]

^<<v10-23-9,9>>^ Next to him El·e·aʹzar the son of Doʹdo the son of A·hoʹhi was among the three mighty men with David when they taunted the Phi·lisʹtines. They^&#42;1^ had gathered themselves there for the battle, and so the men of Israel retreated.

[NOTE]
====
. “With David at Pas-dammim, where the Philistines,” in 1Ch 11:13.
====

[[v10-23-10]]

^<<v10-23-10,10>>^ He it was that rose up and kept striking down the Phi·lisʹtines until his hand wearied and his hand kept cleaving to the sword, so that Jehovah performed a great salvation on that day; and as for the people, they returned behind him only to strip &#91;those struck down&#93;.

[[v10-23-11]]

^<<v10-23-11,11>>^ And next to him was Shamʹmah the son of Aʹgee the Harʹa·rite. And the Phi·lisʹtines proceeded to gather themselves to Leʹhi, where there then happened to be a tract of the field full of lentils; and the people themselves fled because of the Phi·lisʹtines.

[[v10-23-12]]

^<<v10-23-12,12>>^ But he took his stand in the middle of the tract and delivered it and kept striking down the Phi·lisʹtines, so that Jehovah performed a great salvation.

[[v10-23-13]]

^<<v10-23-13,13>>^ And three of the thirty head ones proceeded to go down and come at &#91;the&#93; harvest,^&#42;1^ to David at the cave of A·dulʹlam; and a tent village of the Phi·lisʹtines was encamped in the low plain of the Rephʹa·im.^&#42;2^

[NOTE]
====
. “At [the] harvest,” M; LXXL and 1Ch 11:15, “to the rock.”
. “Rephaim.” Heb., Repha·ʼimʹ; Gr., Rha·pha·imʹ; SyVg, “the giants.”
====

[[v10-23-14]]

^<<v10-23-14,14>>^ And David was then in the place hard to approach; and an outpost of the Phi·lisʹtines was then in Bethʹle·hem.

[[v10-23-15]]

^<<v10-23-15,15>>^ After a while David expressed his craving and said: “O that I might have a drink of the water from the cistern of Bethʹle·hem that is at the gate!”

[[v10-23-16]]

^<<v10-23-16,16>>^ At that the three mighty men forced their way into the camp of the Phi·lisʹtines and drew water from the cistern of Bethʹle·hem that is at the gate and came carrying and bringing it to David; and he did not consent to drink it, but poured it out to Jehovah.

[[v10-23-17]]

^<<v10-23-17,17>>^ And he went on to say: “It is unthinkable on my part, O Jehovah, that I should do this! &#91;Shall I drink&#93;^&#42;1^ the blood of the men going at the risk of their souls?” And he did not consent to drink it.
These are the things the three mighty men did.

[NOTE]
====
. “Shall I drink?” LXX; missing from M as an aposiopesis (sudden silence).
====

[[v10-23-18]]

^<<v10-23-18,18>>^ As for A·bishʹai the brother of Joʹab the son of Ze·ruʹiah, he was the head of the thirty,^&#42;1^ and he was brandishing his spear over three hundred slain ones, and he had a reputation like the three.

[NOTE]
====
. “Thirty,” Sy and two Heb. mss; MLXXVg, “three.”
====

[[v10-23-19]]

^<<v10-23-19,19>>^ Although he was distinguished even more than the rest of the thirty,^&#42;1^ and he came to be their chief, to the rank of the &#91;first&#93; three he did not come.

[NOTE]
====
. “Thirty,” in agreement with vs 18; MLXXVg, “three.”
====

[[v10-23-20]]

^<<v10-23-20,20>>^ As for Be·naiʹah^&#42;1^ the son of Je·hoiʹa·da the son of a valiant man, who did many deeds in Kabʹze·el, he himself struck down the two sons of Arʹi·el of Moʹab; and he himself descended and struck down a lion^&#42;2^ inside a waterpit on a day of snowfall.

[NOTE]
====
. Lit., “Benaiahu.”
. Lit., “the lion.” Heb., ha·ʼarihʹ, the African lion.
====

[[v10-23-21]]

^<<v10-23-21,21>>^ And he it was that struck down the Egyptian man that was of extraordinary size.^&#42;1^ Though there was a spear in the hand of the Egyptian, yet he went on down to him with a rod and snatched the spear away from the Egyptian’s hand and killed him with his own spear.

[NOTE]
====
. “Of extraordinary size,” in agreement with 1Ch 11:23; MLXX, “of appearance.”
====

[[v10-23-22]]

^<<v10-23-22,22>>^ These things Be·naiʹah the son of Je·hoiʹa·da did; and he had a reputation like the three mighty men.

[[v10-23-23]]

^<<v10-23-23,23>>^ Although he was distinguished even more than the thirty, to the rank of the three he did not come; but David appointed him to his own bodyguard.

[[v10-23-24]]

^<<v10-23-24,24>>^ Asʹa·hel the brother of Joʹab was among the thirty; El·haʹnan the son of Doʹdo of Bethʹle·hem,

[[v10-23-25]]

^<<v10-23-25,25>>^ Shamʹmah the Haʹrod·ite, E·liʹka the Haʹrod·ite,

[[v10-23-26]]

^<<v10-23-26,26>>^ Heʹlez the Palʹtite, Iʹra the son of Ikʹkesh the Te·koʹite,

[[v10-23-27]]

^<<v10-23-27,27>>^ Abi-eʹzer the Anʹa·thoth·ite, Me·bunʹnai the Huʹshath·ite,

[[v10-23-28]]

^<<v10-23-28,28>>^ Zalʹmon the A·hoʹhite, Maʹha·rai the Ne·tophʹa·thite,

[[v10-23-29]]

^<<v10-23-29,29>>^ Heʹleb the son of Baʹa·nah the Ne·tophʹa·thite, Itʹtai the son of Riʹbai of Gibʹe·ah of the sons of Benjamin,

[[v10-23-30]]

^<<v10-23-30,30>>^ Be·naiʹah a Pirʹa·thon·ite, Hidʹdai of the torrent valleys of Gaʹash,

[[v10-23-31]]

^<<v10-23-31,31>>^ Aʹbi-alʹbon the Arʹbath·ite, Azʹma·veth the Bar-huʹmite,

[[v10-23-32]]

^<<v10-23-32,32>>^ E·liʹah·ba the Sha·alʹbo·nite, the sons of Jaʹshen, Jonʹa·than,

[[v10-23-33]]

^<<v10-23-33,33>>^ Shamʹmah the Harʹa·rite, A·hiʹam the son of Shaʹrar the Harʹa·rite,

[[v10-23-34]]

^<<v10-23-34,34>>^ E·liphʹe·let the son of A·hasʹbai the son of the Ma·acʹa·thite, E·liʹam the son of A·hithʹo·phel the Giʹlon·ite,

[[v10-23-35]]

^<<v10-23-35,35>>^ Hezʹro the Carʹmel·ite, Paʹa·rai the Arʹbite,

[[v10-23-36]]

^<<v10-23-36,36>>^ Iʹgal the son of Nathan of Zoʹbah, Baʹni the Gadʹite,

[[v10-23-37]]

^<<v10-23-37,37>>^ Zeʹlek the Amʹmon·ite, Naʹha·rai the Be·erʹoth·ite, armor-bearers of Joʹab the son of Ze·ruʹiah,

[[v10-23-38]]

^<<v10-23-38,38>>^ Iʹra the Ithʹrite, Gaʹreb the Ithʹrite,

[[v10-23-39]]

^<<v10-23-39,39>>^ U·riʹah the Hitʹtite—thirty-seven in all.

'''

xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[&#60; Capítulo Anterior] | <<v10-23-0,Topo>> | xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[Próximo Capítulo &#62;]