include::./index.adoc[]

[[v10-17-0]]
=== The Second of Samuel, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-17-1]]

^<<v10-17-1,1>>^ And A·hithʹo·phel proceeded to say to Abʹsa·lom: “Let me choose, please, twelve thousand men and rise up and chase after David tonight.

[[v10-17-2]]

^<<v10-17-2,2>>^ And I shall come upon him when he is weary and feeble in both hands, and I shall certainly drive him into trembling; and all the people that are with him will have to flee, and I shall certainly strike down the king by himself.

[[v10-17-3]]

^<<v10-17-3,3>>^ And let me bring all the people back to you. Equivalent to the returning of all is the man whom you are seeking; &#91;and&#93; all the people will themselves come to be at peace.”^&#42;1^

[NOTE]
====
. Possibly, “Let me bring all the people back to you just as the bride returns to her husband. It is only the soul of one man that you are seeking, and all the people will themselves come to be at peace.” LXX agrees.
====

[[v10-17-4]]

^<<v10-17-4,4>>^ And the word was just right in the eyes of Abʹsa·lom and in the eyes of all the older men of Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ However, Abʹsa·lom said: “Call, please, Huʹshai the Arʹchite also, and let us hear what is in his mouth, even his.”

[[v10-17-6]]

^<<v10-17-6,6>>^ So Huʹshai came in to Abʹsa·lom. Then Abʹsa·lom said to him: “According to this word is the way A·hithʹo·phel spoke. Shall we act upon his word? If not, you yourself speak.”

[[v10-17-7]]

^<<v10-17-7,7>>^ At this Huʹshai said to Abʹsa·lom: “The counsel with which A·hithʹo·phel has counseled is not good in this instance!”

[[v10-17-8]]

^<<v10-17-8,8>>^ And Huʹshai went on to say: “You yourself well know your father and the men of his, that they are mighty, and they are bitter of soul, like a female bear that has lost her cubs in the field; and your father is a warrior, and he will not spend the night with the people.

[[v10-17-9]]

^<<v10-17-9,9>>^ Look! Now he is in hiding in one of the hollows or in one of the other places; and it will certainly occur that, just as soon as he falls upon them at the start, the one hearing of it will then be bound to hear and say, ‘A defeat has taken place among the people that are following Abʹsa·lom!’

[[v10-17-10]]

^<<v10-17-10,10>>^ And even the valiant man whose heart is as the heart of the lion^&#42;1^ will himself surely soften in weakness; for all Israel is aware that your father is a mighty man and so, too, are the valiant men that are with him.

[NOTE]
====
. “The lion.” Heb., ha·ʼar·yehʹ, the African lion.
====

[[v10-17-11]]

^<<v10-17-11,11>>^ I myself do say in counsel: Let all Israel without fail be gathered to you, from Dan to Beʹer-sheʹba, as the sand particles that are by the sea for multitude, with your own person^&#42;1^ going into the fight.^&#42;2^

[NOTE]
====
. Lit., “and with your own face.”
. Or, “into battle.” LXXSyVg, “in among them.”
====

[[v10-17-12]]

^<<v10-17-12,12>>^ And we must come against him in one of the places where he is certain to be found, and we ourselves will be upon him just as the dew falls upon the ground; and there will certainly not be left even a single one among him and all the men that are with him.

[[v10-17-13]]

^<<v10-17-13,13>>^ And if it is into some city that he will withdraw, all Israel must also carry ropes to that city, and we shall certainly drag it down to the torrent valley, until there shall not be found there even a pebble.”

[[v10-17-14]]

^<<v10-17-14,14>>^ Then Abʹsa·lom and all the men of Israel said: “The counsel of Huʹshai the Arʹchite is better than the counsel of A·hithʹo·phel!” And Jehovah himself had given command to frustrate the counsel of A·hithʹo·phel although good, in order that Jehovah might bring calamity upon Abʹsa·lom.

[[v10-17-15]]

^<<v10-17-15,15>>^ Later Huʹshai said to Zaʹdok and A·biʹa·thar the priests: “This and that was the way that A·hithʹo·phel counseled Abʹsa·lom and the older men of Israel; and this and that was the way that I myself counseled.

[[v10-17-16]]

^<<v10-17-16,16>>^ And now send speedily and tell David, saying, ‘Do not lodge in the desert plains of the wilderness tonight, but you also ought to cross over without fail, for fear that the king and all the people that are with him may be swallowed up.’”^&#42;1^

[NOTE]
====
. Or, “for fear that it may be communicated to the king and to all the people that are with him.”
====

[[v10-17-17]]

^<<v10-17-17,17>>^ As Jonʹa·than and A·himʹa·az were standing at En-roʹgel, a maidservant went off and told them. So they themselves went off, as they had to tell King David; for they were not able to appear entering the city.

[[v10-17-18]]

^<<v10-17-18,18>>^ However, a young man got to see them and told Abʹsa·lom. So the two of them went off speedily and came to the house of a man in Ba·huʹrim, who had a well in his courtyard; and they went down into it.

[[v10-17-19]]

^<<v10-17-19,19>>^ After that the woman took and spread out a screen over the face of the well and heaped up cracked grain upon it; and not a thing became known of it.

[[v10-17-20]]

^<<v10-17-20,20>>^ The servants of Abʹsa·lom now came to the woman at her house and said: “Where are A·himʹa·az and Jonʹa·than?” At this the woman said to them: “They passed on from here to the waters.” Then they kept on searching, and they did not find them and so returned to Jerusalem.

[[v10-17-21]]

^<<v10-17-21,21>>^ And it came about after their going away that then they came up out of the well and went on and told King David and said to David: “YOU people, rise up and speedily pass over the waters; for this is the way that A·hithʹo·phel counseled against YOU.”

[[v10-17-22]]

^<<v10-17-22,22>>^ Immediately David rose up and also all the people that were with him, and they kept crossing the Jordan until the morning became light, until not a one was lacking that had not passed over the Jordan.

[[v10-17-23]]

^<<v10-17-23,23>>^ As for A·hithʹo·phel, he saw that his counsel had not been acted upon, and he proceeded to saddle an ass and rise up and go off to his house at his own city. Then he gave commands to his household and strangled himself^&#42;1^ and thus died. So he was buried in the burial place of his forefathers.

[NOTE]
====
. “Hanged himself,” LXX, as in Mt 27:5.
====

[[v10-17-24]]

^<<v10-17-24,24>>^ As for David, he came to Ma·ha·naʹim, and Abʹsa·lom himself crossed the Jordan, he and all the men of Israel with him.

[[v10-17-25]]

^<<v10-17-25,25>>^ And A·maʹsa was the one whom Abʹsa·lom put in the place of Joʹab over the army; and A·maʹsa was the son of a man whose name was Ithʹra the Israelite,^&#42;1^ who had relations with Abʹi·gail the daughter of Naʹhash,^&#42;2^ the sister of Ze·ruʹiah, Joʹab’s mother.

[NOTE]
====
. “Israelite,” MLXXSyVg; LXXA and 1Ch 2:17, “Ishmaelite.”
. “Nahash,” MLXXSyVg; LXXL and 1Ch 2:12, 13, “Jesse.”
====

[[v10-17-26]]

^<<v10-17-26,26>>^ And Israel and Abʹsa·lom took up camping in the land of Gilʹe·ad.

[[v10-17-27]]

^<<v10-17-27,27>>^ And it came about that, as soon as David came to Ma·ha·naʹim, Shoʹbi the son of Naʹhash from Rabʹbah of the sons of Amʹmon, and Maʹchir the son of Amʹmi·el from Lo-deʹbar, and Bar·zilʹlai the Gilʹe·ad·ite from Ro·geʹlim

[[v10-17-28]]

^<<v10-17-28,28>>^ &#91;brought&#93;^&#42;1^ beds and basins and potter’s vessels, and wheat and barley and flour and roasted grain and broad beans and lentils and parched grain;

[NOTE]
====
. “Brought,” LXX.
====

[[v10-17-29]]

^<<v10-17-29,29>>^ and honey and butter and sheep and curds of cattle they brought forward for David and the people that were with him to eat, for they said: “The people are hungry and tired and thirsty in the wilderness.”

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]