include::./index.adoc[]

[[v10-8-0]]
=== The Second of Samuel, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-8-1]]

^<<v10-8-1,1>>^ And it came about afterward that David proceeded to strike the Phi·lisʹtines down and subdue them, and David got to take Methʹeg-amʹmah out of the hand of the Phi·lisʹtines.

[[v10-8-2]]

^<<v10-8-2,2>>^ And he went on to strike down the Moʹab·ites and measure them with a line, making them lie down^&#42;1^ on the earth, that he might measure two lines to put them to death, and a full line to preserve them alive; and the Moʹab·ites came to be David’s servants to carry tribute.^&#42;2^

[NOTE]
====
. “Making . . . lie down.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. Or, “gifts.”
====

[[v10-8-3]]

^<<v10-8-3,3>>^ And David went on to strike down Had·ad·eʹzer^&#42;1^ the son of Reʹhob the king of Zoʹbah as he was going his way to put his control back again at the river Eu·phraʹtes.^&#42;2^

[NOTE]
====
. “Hadadezer,” Al, Ca, Leningrad B 19A, many other Heb. mss and 1Ch 18:10; LXXSyVgc and about 55 Heb. mss, “Hadarezer.”
. “Euphrates.” Only the vowel points appear in M, but the name appears in MmarginLXXSyVg and in about 45 Heb. mss. It is qere but not kethib (read but not written). Compare Jg 20:13 ftn.
====

[[v10-8-4]]

^<<v10-8-4,4>>^ And David got to capture from him one thousand seven hundred horsemen and twenty thousand men on foot; and David proceeded to hamstring all the chariot horses, but he let a hundred chariot horses^&#42;1^ of them remain.

[NOTE]
====
. Possibly, “teams.”
====

[[v10-8-5]]

^<<v10-8-5,5>>^ When Syria^&#42;1^ of Damascus came to help Had·ad·eʹzer the king of Zoʹbah, David then struck down among the Syrians twenty-two thousand men.

[NOTE]
====
. “Syria,” LXXVg; M, “Aram”; Sy, “Edom.”
====

[[v10-8-6]]

^<<v10-8-6,6>>^ Further, David put garrisons in Syria of Damascus; and the Syrians came to be David’s servants to carry tribute. And Jehovah continued to save David wherever he went.

[[v10-8-7]]

^<<v10-8-7,7>>^ Moreover, David took the circular shields of gold that happened to be on the servants of Had·ad·eʹzer and brought them to Jerusalem.

[[v10-8-8]]

^<<v10-8-8,8>>^ And from Beʹtah^&#42;1^ and Be·roʹthai, cities of Had·ad·eʹzer, King David took copper in very great quantity.

[NOTE]
====
. “Betah,” MVg; Sy, “Tebah”; in 1Ch 18:8, “Tibhath.” Compare “Tebah” in Ge 22:24.
====

[[v10-8-9]]

^<<v10-8-9,9>>^ Now Toʹi^&#42;1^ the king of Haʹmath got to hear that David had struck down all the military force of Had·ad·eʹzer.

[NOTE]
====
. “Toi,” M; LXX, “Thoou”; Vg, “Thou”; in 1Ch 18:9, 10, “Tou.”
====

[[v10-8-10]]

^<<v10-8-10,10>>^ So Toʹi sent Joʹram his son to King David to ask him about his welfare and congratulate^&#42;1^ him over the fact that he had fought against Had·ad·eʹzer so that he struck him down (for Had·ad·eʹzer had become trained in warfare against Toʹi); and in his hand there proved to be articles of silver and articles of gold and articles of copper.

[NOTE]
====
. Or, “bless.”
====

[[v10-8-11]]

^<<v10-8-11,11>>^ These also King David sanctified^&#42;1^ to Jehovah, together with the silver and the gold that he had sanctified from all the nations that he had subdued,

[NOTE]
====
. Or, “declared sacred.”
====

[[v10-8-12]]

^<<v10-8-12,12>>^ from Syria and from Moʹab and from the sons of Amʹmon and from the Phi·lisʹtines and from Amʹa·lek and from the spoil of Had·ad·eʹzer the son of Reʹhob the king of Zoʹbah.

[[v10-8-13]]

^<<v10-8-13,13>>^ And David proceeded to make a name when he came back from striking down the Eʹdom·ites^&#42;1^ in the Valley of Salt—eighteen thousand.

[NOTE]
====
. “The Edomites,” LXXSy, six Heb. mss and 1Ch 18:12; MVg, “Syria (Aram); the Syrians.”
====

[[v10-8-14]]

^<<v10-8-14,14>>^ And he kept garrisons placed in Eʹdom. In all Eʹdom he placed garrisons, and all the Eʹdom·ites came to be servants of David; and Jehovah kept saving David wherever he went.

[[v10-8-15]]

^<<v10-8-15,15>>^ And David kept reigning over all Israel; and David was continually rendering judicial decision and righteousness for all his people.

[[v10-8-16]]

^<<v10-8-16,16>>^ And Joʹab the son of Ze·ruʹiah was over the army; and Je·hoshʹa·phat the son of A·hiʹlud was recorder.^&#42;1^

[NOTE]
====
. Lit., “remembrancer.”
====

[[v10-8-17]]

^<<v10-8-17,17>>^ And Zaʹdok the son of A·hiʹtub and A·himʹe·lech the son of A·biʹa·thar^&#42;1^ were priests, and Se·raiʹah was secretary.

[NOTE]
====
. “And Ahimelech the son of Abiathar,” MLXXVg; Sy, “and Abiathar the son of Ahimelech.”
====

[[v10-8-18]]

^<<v10-8-18,18>>^ And Be·naiʹah^&#42;1^ the son of Je·hoiʹa·da &#91;was over&#93;^&#42;2^ the Cherʹe·thites and the Pelʹe·thites. As for the sons of David, they became priests.^&#42;3^

[NOTE]
====
. “And Benaiah.” Heb., u·Vena·yaʹhu.
. “Was over,” TSyVg and 1Ch 18:17; MLXX, “and,” or “was with.”
. “Priests,” MVg; LXX, “chiefs of the court”; Sy, “chiefs”; in 1Ch 18:17, “first in position at the side of the king.”
====

'''

xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[&#60; Capítulo Anterior] | <<v10-8-0,Topo>> | xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[Próximo Capítulo &#62;]