include::./index.adoc[]

[[v10-14-0]]
=== The Second of Samuel, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-14-1]]

^<<v10-14-1,1>>^ Now Joʹab the son of Ze·ruʹiah came to know that the king’s heart was toward Abʹsa·lom.

[[v10-14-2]]

^<<v10-14-2,2>>^ Accordingly Joʹab sent to Te·koʹa and took from there a wise woman and said to her: “Go in mourning, please, and dress yourself, please, with garments of mourning, and do not rub yourself with oil; and you must become like a woman here who has been mourning many days over someone dead.

[[v10-14-3]]

^<<v10-14-3,3>>^ And you must come in to the king and speak to him a word like this.” With that Joʹab put the words in her mouth.

[[v10-14-4]]

^<<v10-14-4,4>>^ And the Te·koʹite woman proceeded to come in^&#42;1^ to the king and fall upon her face to the earth and prostrate herself and say: “Do save, O king!”

[NOTE]
====
. “Come in,” TLXXSyVg and many Heb. mss; M, “say.”
====

[[v10-14-5]]

^<<v10-14-5,5>>^ At this the king said to her: “What is the matter with you?” To this she said: “For a fact I am a widowed woman, now that my husband is dead.

[[v10-14-6]]

^<<v10-14-6,6>>^ And your maidservant had two sons, and the two of them began to struggle with each other in the field while there was no deliverer to part them.^&#42;1^ Finally the one struck the other down and put him to death.

[NOTE]
====
. Lit., “between them.”
====

[[v10-14-7]]

^<<v10-14-7,7>>^ And here all the family have risen up against your maidservant and keep saying, ‘Give over the striker of his brother, that we may put him to death for the soul of his brother whom he killed, and let us even annihilate the heir!’ And they will certainly extinguish the glow of my charcoals that has remained, so as to assign to my husband neither a name nor a remnant^&#42;1^ on the surface of the ground.”

[NOTE]
====
. Or, “survivor.”
====

[[v10-14-8]]

^<<v10-14-8,8>>^ Then the king said to the woman: “Go to your house, and I myself shall give command regarding you.”

[[v10-14-9]]

^<<v10-14-9,9>>^ At this the Te·koʹite woman said to the king: “Upon me, O my lord the king, be the error, and also upon the house of my father, while the king and his throne are innocent.”

[[v10-14-10]]

^<<v10-14-10,10>>^ And the king went on to say: “If there is anyone speaking to you, you must also bring him to me, and he will never hurt you again.”

[[v10-14-11]]

^<<v10-14-11,11>>^ But she said: “Let the king, please, remember Jehovah your God, that the avenger of blood may not be continually causing ruin and that they may not annihilate my son.” To this he said: “As Jehovah is living, not a single hair of your son will fall to the earth.”

[[v10-14-12]]

^<<v10-14-12,12>>^ The woman now said: “Let your maidservant, please, speak a word to my lord the king.” So he said: “Speak!”

[[v10-14-13]]

^<<v10-14-13,13>>^ And the woman went on to say: “Why, then, have you reasoned like this against the people of God? As the king is speaking this word he is like one that is guilty, in that the king does not bring back his own banished one.

[[v10-14-14]]

^<<v10-14-14,14>>^ For we shall die without fail and be like waters that are being poured down to the earth, which cannot be gathered. But God will not take away a soul, and he has thought out reasons why the one banished should not be banished from him.

[[v10-14-15]]

^<<v10-14-15,15>>^ And now that I have come in to speak this word to the king my lord, it is because the people made me afraid. So your maidservant said, ‘Let me speak, please, to the king. Perhaps the king will act on the word of his slave girl.

[[v10-14-16]]

^<<v10-14-16,16>>^ Because the king proceeded to listen so as to deliver his slave girl out of the palm of the man &#91;seeking&#93; to annihilate me^&#42;1^ and my lone son from the inheritance given by God,’^&#42;2^

[NOTE]
====
. “Seeking to annihilate me,” LXX; M omits “seeking.”
. “God,” MLXXSyVg; TLXXL, “Jehovah.”
====

[[v10-14-17]]

^<<v10-14-17,17>>^ then your maidservant said, ‘Let the word of my lord the king serve, please, to give rest.’ For just like an angel of the &#91;true&#93; God is the way my lord the king is, to distinguish what is good and what is bad, and may Jehovah your God himself prove to be with you.”

[[v10-14-18]]

^<<v10-14-18,18>>^ The king now answered and said to the woman: “Do not, please, hide from me a thing about which I am asking you.” To this the woman said: “Let my lord the king speak, please.”

[[v10-14-19]]

^<<v10-14-19,19>>^ And the king went on to say: “Is the hand of Joʹab with you in all this?” Then the woman answered and said: “As your soul is living, O my lord the king, no man can go to the right or go to the left from all that my lord the king has spoken; for it was your servant Joʹab that commanded me, and he it was that put in the mouth of your maidservant all these words.

[[v10-14-20]]

^<<v10-14-20,20>>^ For the sake of altering the face of the matter your servant Joʹab has done this thing, but my lord is wise as with the wisdom of the angel of the &#91;true&#93; God so as to know all that is in the earth.”

[[v10-14-21]]

^<<v10-14-21,21>>^ Subsequently the king said to Joʹab: “Here, now, I shall certainly do^&#42;1^ this thing. So go, bring the young man Abʹsa·lom back.”

[NOTE]
====
. “Here, now, you have done,” many Heb. mss.
====

[[v10-14-22]]

^<<v10-14-22,22>>^ At this Joʹab fell upon his face to the earth and prostrated himself and blessed the king; and Joʹab went on to say: “Today your servant does know that I have found favor in your eyes, O my lord the king, because the king has acted on the word of his servant.”

[[v10-14-23]]

^<<v10-14-23,23>>^ With that Joʹab rose up and went to Geshʹur and brought Abʹsa·lom to Jerusalem.

[[v10-14-24]]

^<<v10-14-24,24>>^ However, the king said: “Let him turn toward his own house, but my face he may not see.” So Abʹsa·lom turned toward his own house, and the face of the king he did not see.

[[v10-14-25]]

^<<v10-14-25,25>>^ Now compared with Abʹsa·lom there proved to be no man so beautiful in all Israel as to be praised so much. From the sole of his foot to the crown of his head there proved to be no defect in him.

[[v10-14-26]]

^<<v10-14-26,26>>^ And when he shaved his head—and it occurred at the end of every year that he would shave it; because it was so heavy upon him, he shaved it—he weighed the hair of his head, two hundred shekels^&#42;1^ by the royal stone weight.^&#42;2^

[NOTE]
====
. About 2.3 kg (5 lb).
. “Royal stone weight.” This may have been a standard weight kept at the royal palace or a “royal” shekel different from the common shekel. Compare Ex 30:13 ftn, “Place.”
====

[[v10-14-27]]

^<<v10-14-27,27>>^ And there came to be born to Abʹsa·lom three sons and one daughter whose name was Taʹmar. She proved to be a woman most beautiful in appearance.

[[v10-14-28]]

^<<v10-14-28,28>>^ And Abʹsa·lom continued dwelling in Jerusalem for two full years, and the face of the king he did not see.

[[v10-14-29]]

^<<v10-14-29,29>>^ So Abʹsa·lom sent for Joʹab to send him to the king, and he did not consent to come to him. Then he sent again, a second time, and he did not consent to come.

[[v10-14-30]]

^<<v10-14-30,30>>^ Finally he said to his servants: “See Joʹab’s tract of land beside mine, and there he has barley. Go and set it ablaze with fire.” Accordingly the servants of Abʹsa·lom set the tract of land ablaze with fire.

[[v10-14-31]]

^<<v10-14-31,31>>^ At this Joʹab rose up and came to Abʹsa·lom at the house and said to him: “Why did your servants set the tract of land that is mine ablaze with fire?”

[[v10-14-32]]

^<<v10-14-32,32>>^ So Abʹsa·lom said to Joʹab: “Look! I sent to you, saying, ‘Come here and let me send you to the king, saying: “Why have I come from Geshʹur? It would be better for me that I should still be there. And now let me see the face of the king and, if there is any error in me, he must then put me to death.”’”

[[v10-14-33]]

^<<v10-14-33,33>>^ Subsequently Joʹab came in to the king and told him. Then he called Abʹsa·lom, who now came in to the king and prostrated himself to him, &#91;falling&#93;^&#42;1^ upon his face to the earth before the king; after which the king kissed Abʹsa·lom.

[NOTE]
====
. “Falling,” in agreement with LXX, “and he fell”; M omits.
====

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]