include::./index.adoc[]

[[v10-15-0]]
=== The Second of Samuel, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-15-1]]

^<<v10-15-1,1>>^ And it came about following such things that Abʹsa·lom proceeded to have a chariot made for himself, with horses and with fifty men running before him.

[[v10-15-2]]

^<<v10-15-2,2>>^ And Abʹsa·lom rose up early and stood at the side of the road to the gate. And it came about, when any man happened to have a legal case to come to the king for judgment, then Abʹsa·lom would call him and say: “From what city are you?” and he would say: “From one of the tribes of Israel your servant is.”

[[v10-15-3]]

^<<v10-15-3,3>>^ And Abʹsa·lom would say to him: “See, your matters are good and straight; but there is no one from the king giving you a hearing.”

[[v10-15-4]]

^<<v10-15-4,4>>^ And Abʹsa·lom would go on to say: “O that I were appointed judge in the land, that to me every man might come that happens to have a legal case or judgment! Then I should certainly do justice to him.”

[[v10-15-5]]

^<<v10-15-5,5>>^ It also occurred that, when a man drew near to bow down to him, he thrust his hand out and grabbed hold of him and kissed him.

[[v10-15-6]]

^<<v10-15-6,6>>^ And Abʹsa·lom kept doing a thing like this to all Israelites that would come in for judgment to the king; and Abʹsa·lom kept stealing the hearts of the men of Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ And it came about at the end of forty years^&#42;1^ that Abʹsa·lom proceeded to say to the king: “Let me go, please, and pay in Heʹbron my vow that I solemnly made to Jehovah.

[NOTE]
====
. “Forty years,” MLXXVgc; LXXLSyVg, “four years.” Perhaps 40 years from the anointing of David. Compare 1Sa 16:13.
====

[[v10-15-8]]

^<<v10-15-8,8>>^ For your servant made a solemn vow when I was dwelling in Geshʹur in Syria, saying, ‘If Jehovah will without fail bring me back to Jerusalem, I must also render service to Jehovah.’”

[[v10-15-9]]

^<<v10-15-9,9>>^ So the king said to him: “Go in peace.” With that he rose up and went to Heʹbron.

[[v10-15-10]]

^<<v10-15-10,10>>^ Abʹsa·lom now sent spies through all the tribes of Israel, saying: “As soon as YOU hear the sound of the horn, YOU must also say, ‘Abʹsa·lom has become king in Heʹbron!’”

[[v10-15-11]]

^<<v10-15-11,11>>^ Now there had gone with Abʹsa·lom two hundred men from Jerusalem, being called and going unsuspectingly,^&#42;1^ and they did not know a single thing.

[NOTE]
====
. Lit., “in their innocence.”
====

[[v10-15-12]]

^<<v10-15-12,12>>^ Further, when he offered the sacrifices, Abʹsa·lom sent for^&#42;1^ A·hithʹo·phel the Giʹlon·ite, David’s counselor, from his city Giʹloh. And the conspiracy kept getting stronger, and the people were continually growing in number with Abʹsa·lom.

[NOTE]
====
. “Sent for,” M; LXX, “sent and called.”
====

[[v10-15-13]]

^<<v10-15-13,13>>^ In time an informer came to David, saying: “The heart of the men of Israel has come to be behind Abʹsa·lom.”

[[v10-15-14]]

^<<v10-15-14,14>>^ At once David said to all his servants that were with him in Jerusalem: “Get up, and let us run away; for there will prove to be no escaping for us because of Abʹsa·lom! Go hurriedly, for fear he may hurry up and actually catch up with us and bring down upon us what is bad and strike the city with the edge of the sword!”

[[v10-15-15]]

^<<v10-15-15,15>>^ At this the king’s servants said to the king: “According to all that my lord the king may choose, here are your servants.”

[[v10-15-16]]

^<<v10-15-16,16>>^ So the king went out with all his household at his feet, and the king left ten women, concubines, to take care of the house.

[[v10-15-17]]

^<<v10-15-17,17>>^ And the king continued on his way out with all the people at his feet; and they came to a stop at Beth-merʹhak.^&#42;1^

[NOTE]
====
. Meaning “The Far House.”
====

[[v10-15-18]]

^<<v10-15-18,18>>^ And all his servants were crossing at his side; and all the Cherʹe·thites and all the Pelʹe·thites and all the Gitʹtites, six hundred men that had followed him^&#42;1^ from Gath, were crossing before the king’s face.

[NOTE]
====
. Lit., “had come at his feet,” that is, the feet of Ittai mentioned in vs 19.
====

[[v10-15-19]]

^<<v10-15-19,19>>^ Then the king said to Itʹtai the Gitʹtite: “Why should you yourself also go with us? Go back and dwell with the king; for you are a foreigner and, besides, you are an exile from your place.

[[v10-15-20]]

^<<v10-15-20,20>>^ Yesterday was when you came and today shall I make you wander with us, to go when I am going wherever I am going? Go back and take your brothers back with you, &#91;and may Jehovah exercise toward you&#93;^&#42;1^ loving-kindness and trustworthiness!”

[NOTE]
====
. “And may Jehovah exercise toward you,” in agreement with LXX; M omits.
====

[[v10-15-21]]

^<<v10-15-21,21>>^ But Itʹtai answered the king and said: “As Jehovah is living and as my lord the king is living, in the place where my lord the king may come to be, whether for death or for life, there is where your servant will come to be!”

[[v10-15-22]]

^<<v10-15-22,22>>^ At that David said to Itʹtai: “Go and cross over.” So Itʹtai the Gitʹtite crossed over, and also all his men and all the little ones that were with him.

[[v10-15-23]]

^<<v10-15-23,23>>^ And all the people of the land^&#42;1^ were weeping with a loud voice, and all the people were crossing over, and the king was standing by the torrent valley of Kidʹron, and all the people were crossing over upon the open road to the wilderness.^&#42;2^

[NOTE]
====
. Lit., “And all the land (earth).”
. Possibly, “the king was standing by the torrent valley of Kidron, and all the people were crossing over before him by the way of the olive tree in the wilderness,” LXXLucian.
====

[[v10-15-24]]

^<<v10-15-24,24>>^ And here also there were Zaʹdok and with him all the Levites carrying the ark of the covenant of the &#91;true&#93; God; and they proceeded to set the ark of the &#91;true&#93; God down by A·biʹa·thar^&#42;1^ until all the people completed crossing over from the city.

[NOTE]
====
. “By Abiathar,” by an emendation; M, “and Abiathar proceeded to go up.”
====

[[v10-15-25]]

^<<v10-15-25,25>>^ But the king said to Zaʹdok: “Take the ark of the &#91;true&#93; God back to the city. If I shall find favor in the eyes of Jehovah, he will also certainly bring me back and let me see it and its abiding place.

[[v10-15-26]]

^<<v10-15-26,26>>^ But if this is what he should say, ‘I have found no delight in you,’ here I am, let him do to me just as it is good in his eyes.”

[[v10-15-27]]

^<<v10-15-27,27>>^ And the king went on to say to Zaʹdok the priest: “You are a seer, are you? Do return to the city in peace, and also A·himʹa·az your son and Jonʹa·than the son of A·biʹa·thar, the two sons of YOU men, with YOU.

[[v10-15-28]]

^<<v10-15-28,28>>^ See, I am lingering by the fords^&#42;1^ of the wilderness until word comes from YOU men to inform me.”

[NOTE]
====
. “By the fords,” M; MmarginLXXSyVg, “in the desert plains.”
====

[[v10-15-29]]

^<<v10-15-29,29>>^ Accordingly Zaʹdok and A·biʹa·thar took the ark of the &#91;true&#93; God back to Jerusalem, and they continued^&#42;1^ to dwell there.

[NOTE]
====
. “And they continued,” MSyVg; LXX, “and it continued.”
====

[[v10-15-30]]

^<<v10-15-30,30>>^ And David was going up by the ascent of the Olives, weeping as he went up, with his head covered; and he was walking barefoot, and all the people that were with him covered each one his head, and they went up weeping as they went up.

[[v10-15-31]]

^<<v10-15-31,31>>^ And to David the report was made, saying: “A·hithʹo·phel himself is among those conspiring with Abʹsa·lom.” At this David said: “Turn, please, the counsel of A·hithʹo·phel into foolishness, O Jehovah!”

[[v10-15-32]]

^<<v10-15-32,32>>^ And it came about that when David himself came to the summit where people^&#42;1^ used to bow down to God, here to meet him was Huʹshai the Arʹchite, with his robe ripped apart and dirt upon his head.

[NOTE]
====
. Or, “one; he.”
====

[[v10-15-33]]

^<<v10-15-33,33>>^ However, David said to him: “If you actually went across with me, you would then certainly become a load upon me.

[[v10-15-34]]

^<<v10-15-34,34>>^ But if you return to the city and you actually say to Abʹsa·lom, ‘I am your servant, O King. I used to prove myself the servant of your father, even I at that time, but now even I am your servant,’ you must then frustrate the counsel of A·hithʹo·phel for me.

[[v10-15-35]]

^<<v10-15-35,35>>^ Are not Zaʹdok and A·biʹa·thar the priests there with you? And it must occur that everything that you may hear from the house of the king you should tell to Zaʹdok and A·biʹa·thar the priests.

[[v10-15-36]]

^<<v10-15-36,36>>^ Look! There with them are their two sons, A·himʹa·az belonging to Zaʹdok and Jonʹa·than belonging to A·biʹa·thar; and by means of them YOU men must send to me everything that YOU may hear.”

[[v10-15-37]]

^<<v10-15-37,37>>^ So Huʹshai, David’s companion, came into the city. As for Abʹsa·lom, he proceeded to come into Jerusalem.

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]