include::./index.adoc[]

[[v10-20-0]]
=== The Second of Samuel, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-20-1]]

^<<v10-20-1,1>>^ Now there happened to be there a good-for-nothing man,^&#42;1^ whose name was Sheʹba, the son of Bichʹri a Benʹja·min·ite; and he proceeded to blow the horn and say: “We have no share in David, and we have no inheritance in the son of Jesʹse. Every one to his gods,^&#42;2^ O Israel!”

[NOTE]
====
. Or, “a scoundrel.” Lit., “a man of belial (worthlessness).”
. “To his gods.” Lit., “to his tents.” Heb., leʼo·ha·lavʹ. One of the Eighteen Emendations of the Sopherim, the original Heb. text being alleged to have read leʼ·lo·havʹ (from ʼelo·himʹ, “gods” or “God”). See App 2B.
====

[[v10-20-2]]

^<<v10-20-2,2>>^ At that all the men of Israel began to go up from following David to follow Sheʹba the son of Bichʹri; but as for the men of Judah, they stuck to their king from the Jordan to Jerusalem.

[[v10-20-3]]

^<<v10-20-3,3>>^ Eventually David came to his house at Jerusalem. Then the king took the ten women, the concubines whom he had left behind to take care of the house, and he put them in a house of confinement, but he kept on supplying food to them. And with them he did not have any relations, but they continued shut up closely until the day of their dying, in a widowhood with a living &#91;husband&#93;.^&#42;1^

[NOTE]
====
. Lit., “[in] a widowhood of livingness,” M; LXX, “living widows”; Vg, “living in widowhood.”
====

[[v10-20-4]]

^<<v10-20-4,4>>^ The king now said to A·maʹsa: “Call the men of Judah together to me within three days, and you yourself stand here.”

[[v10-20-5]]

^<<v10-20-5,5>>^ So A·maʹsa went to call Judah together; but he came later than the fixed time that he had appointed for him.

[[v10-20-6]]

^<<v10-20-6,6>>^ Then David said to A·bishʹai: “Now Sheʹba the son of Bichʹri will be worse for us than Abʹsa·lom. You yourself take the servants of your lord and chase after him, that he may not actually find for himself fortified cities and escape before our eyes.”^&#42;1^

[NOTE]
====
. Lit., “and snatch away our eyes.”
====

[[v10-20-7]]

^<<v10-20-7,7>>^ Accordingly the men of Joʹab and the Cherʹe·thites and the Pelʹe·thites and all the mighty men went out after him; and they went on out of Jerusalem to chase after Sheʹba the son of Bichʹri.

[[v10-20-8]]

^<<v10-20-8,8>>^ They were close by the great stone that is in Gibʹe·on, and A·maʹsa himself came to meet them. Now Joʹab was girded, clothed with a garment; and upon him there was girded a sword attached to his hip, in its sheath. And he himself came forth, and so it^&#42;1^ fell out.

[NOTE]
====
. “It,” in agreement with LXX, which reads, “the sword.”
====

[[v10-20-9]]

^<<v10-20-9,9>>^ And Joʹab proceeded to say to A·maʹsa: “Is it all right with you, my brother?” Then Joʹab’s right hand took hold of A·maʹsa’s beard so as to kiss him.

[[v10-20-10]]

^<<v10-20-10,10>>^ As for A·maʹsa, he was not on guard against the sword that was in Joʹab’s hand; so that he struck him with it in the abdomen, and his intestines spilled out to the earth, and he did not have to do it to him again. So he died. And Joʹab and A·bishʹai his brother, for their part, chased after Sheʹba the son of Bichʹri.

[[v10-20-11]]

^<<v10-20-11,11>>^ And a certain one of Joʹab’s young men stood over him and kept saying: “Whoever has found delight in Joʹab and whoever belongs to David, let him follow Joʹab!”

[[v10-20-12]]

^<<v10-20-12,12>>^ All the while A·maʹsa was wallowing in the blood in the middle of the highway. When the man saw that all the people stood still, then he moved A·maʹsa from the highway to the field. Finally he cast a garment over him, as he saw that everyone coming up to him stood still.

[[v10-20-13]]

^<<v10-20-13,13>>^ As soon as he had removed him from the highway, each man passed by following Joʹab to chase after Sheʹba the son of Bichʹri.

[[v10-20-14]]

^<<v10-20-14,14>>^ And &#91;Sheʹba&#93; went passing through all the tribes of Israel to Abel of Beth-maʹa·cah. As for all the Bichʹrites,^&#42;1^ they then congregated together and also went in after him.

[NOTE]
====
. Lit., “Berites.”
====

[[v10-20-15]]

^<<v10-20-15,15>>^ And they proceeded to come and lay siege against him in Abel of Beth-maʹa·cah and cast up a siege rampart against the city, as it was standing within a rampart. And all the people that were with Joʹab were undermining the wall, to throw it down.

[[v10-20-16]]

^<<v10-20-16,16>>^ And a wise woman began to call from the city: “Listen, men, listen! Say, please, to Joʹab, ‘Come near as far as here, and let me speak to you.’”

[[v10-20-17]]

^<<v10-20-17,17>>^ So he went near to her, and the woman then said: “Are you Joʹab?” to which he said: “I am.” At this she said to him: “Listen to the words of your slave girl.” In turn he said: “I am listening.”

[[v10-20-18]]

^<<v10-20-18,18>>^ And she went on to say: “Without exception they used to speak in former times, saying, ‘Let them but inquire in Abel, and thus they will certainly end the matter.’

[[v10-20-19]]

^<<v10-20-19,19>>^ I represent the peaceable and faithful ones of Israel. You are seeking to put to death a city and a mother in Israel. Why should you swallow up the inheritance of Jehovah?”

[[v10-20-20]]

^<<v10-20-20,20>>^ To this Joʹab answered and said: “It is altogether unthinkable on my part that I should swallow up and that I should bring to ruin.

[[v10-20-21]]

^<<v10-20-21,21>>^ The matter is not that way, but a man from the mountainous region of Eʹphra·im, whose name is Sheʹba the son of Bichʹri, has lifted up his hand against King David. YOU people, give him over by himself, and I will withdraw from the city.” Then the woman said to Joʹab: “Look! His head &#91;will be&#93; pitched to you over the wall!”

[[v10-20-22]]

^<<v10-20-22,22>>^ At once the woman went in her wisdom to all the people, and they proceeded to cut off the head of Sheʹba the son of Bichʹri and pitch it to Joʹab. Upon that he blew the horn, and so they were scattered from the city, each one to his home;^&#42;1^ and Joʹab himself returned to Jerusalem to the king.

[NOTE]
====
. Lit., “tents.”
====

[[v10-20-23]]

^<<v10-20-23,23>>^ And Joʹab was over all the army of Israel; and Be·naiʹah the son of Je·hoiʹa·da was over the Cherʹe·thites and over the Pelʹe·thites.

[[v10-20-24]]

^<<v10-20-24,24>>^ And A·doʹram was over those conscripted for forced labor; and Je·hoshʹa·phat the son of A·hiʹlud was the recorder.^&#42;1^

[NOTE]
====
. Or, “remembrancer.”
====

[[v10-20-25]]

^<<v10-20-25,25>>^ And Sheʹva was secretary, and Zaʹdok and A·biʹa·thar were priests.

[[v10-20-26]]

^<<v10-20-26,26>>^ And Iʹra the Jaʹir·ite also became a priest^&#42;1^ of David.

[NOTE]
====
. See 8:18 ftn, “Priests.”
====

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]