include::./index.adoc[]

[[v10-24-0]]
=== The Second of Samuel, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-24-1]]

^<<v10-24-1,1>>^ And again the anger of Jehovah came to be hot against Israel, when one^&#42;1^ incited David^&#42;2^ against them, saying: “Go, take a count of Israel and Judah.”

[NOTE]
====
. Or, “he.” See 1Ch 21:1.
. Or, “when David was incited.”
====

[[v10-24-2]]

^<<v10-24-2,2>>^ So the king said to Joʹab the chief^&#42;1^ of the military forces who was with him:^&#42;2^ “Move about, please, through all the tribes of Israel, from Dan to Beʹer-sheʹba, and YOU men register the people, and I shall certainly know the number of the people.”

[NOTE]
====
. “Chief of.” Heb., sar; LXX, “ruler”; Vg, “prince.”
. “To Joab and to the chiefs of the military forces who were with him,” LXXL. See vs 4; 1Ch 21:2.
====

[[v10-24-3]]

^<<v10-24-3,3>>^ But Joʹab said to the king: “May Jehovah your God even add to the people a hundred times as many as they are while the very eyes of my lord the king are seeing it. But as for my lord the king, why has he found delight in this thing?”

[[v10-24-4]]

^<<v10-24-4,4>>^ Finally the king’s word prevailed upon Joʹab and the chiefs of the military forces. So Joʹab and the chiefs of the military forces went out from before the king to register the people Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Then they crossed the Jordan and took up camping at A·roʹer to the right of the city^&#42;1^ that is in the middle of the torrent valley, toward the Gadʹites, and to Jaʹzer.

[NOTE]
====
. “Took up camping at Aroer to the right of the city,” M; LXXL, “began at Aroer and at the city”; Vg, “came to Aroer at the right of the city.”
====

[[v10-24-6]]

^<<v10-24-6,6>>^ After that they came on to Gilʹe·ad and the land of Tahʹtim-hodʹshi^&#42;1^ and continued on to Dan-jaʹan and went around to Siʹdon.

[NOTE]
====
. “Land of Tahtim-hodshi,” M; LXXL, “land of the Hittites toward Kadesh.”
====

[[v10-24-7]]

^<<v10-24-7,7>>^ Then they came to the fortress of Tyre and all the cities of the Hiʹvites and of the Caʹnaan·ites and came to the terminating point in the Negʹeb of Judah at Beʹer-sheʹba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Thus they went moving about through all the land and came to Jerusalem at the end of nine months and twenty days.

[[v10-24-9]]

^<<v10-24-9,9>>^ Joʹab now gave the number of the registration of the people to the king; and Israel amounted to eight hundred thousand valiant men drawing sword, and the men of Judah were five hundred thousand men.

[[v10-24-10]]

^<<v10-24-10,10>>^ And David’s heart began to beat him after he had so numbered the people. Consequently David said to Jehovah: “I have sinned very much in what I have done. And now, Jehovah, let your servant’s error pass by, please; for I have acted very foolishly.”

[[v10-24-11]]

^<<v10-24-11,11>>^ When David proceeded to rise up in the morning, Jehovah’s word itself came to Gad the prophet, David’s visionary, saying:

[[v10-24-12]]

^<<v10-24-12,12>>^ “Go,^&#42;1^ and you must say to David, ‘This is what Jehovah has said: “Three things I am laying upon you. Choose for yourself one of them that I may do it to you.”’”

[NOTE]
====
. Lit., “There will be a going.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v10-24-13]]

^<<v10-24-13,13>>^ Accordingly Gad came in to David and told him and said to him: “Should there come to you seven^&#42;1^ years of famine in your land, or three months of your fleeing before your adversaries, with them pursuing you, or the occurring of three days of pestilence^&#42;2^ in your land? Now know and see what I shall reply to the One sending me.”

[NOTE]
====
. “Seven,” MSyVg; LXX and 1Ch 21:12, “three.”
. Or, “(bubonic) plague.” Lat., pe·sti·lenʹti·a; LXX, “death (deadly plague).”
====

[[v10-24-14]]

^<<v10-24-14,14>>^ So David said to Gad: “It is very distressing to me. Let us fall, please, into the hand of Jehovah, for many are his mercies; but into the hand of man^&#42;1^ do not let me fall.”^&#42;2^

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
. LXX adds: “And David made his choice of the deadly plague. (15) And it was the days of the wheat harvest.”
====

[[v10-24-15]]

^<<v10-24-15,15>>^ Then Jehovah gave a pestilence in Israel from the morning until the time appointed, so that out of the people from Dan to Beʹer-sheʹba seventy thousand persons died.

[[v10-24-16]]

^<<v10-24-16,16>>^ And the angel kept his hand thrust out toward Jerusalem to bring it to ruin; and Jehovah began to feel regret over the calamity, and so he said to the angel that was bringing ruin among the people: “It is enough! Now let your hand drop.” And Jehovah’s angel himself happened to be close by the threshing floor of A·rauʹnah the Jebʹu·site.

[[v10-24-17]]

^<<v10-24-17,17>>^ And David proceeded to say to Jehovah, when he saw the angel that was striking the people down, yes, he proceeded to say: “Here it is I that have sinned and it is I that have done wrong; but these sheep—what have they done? Let your hand, please, come upon me and upon the house of my father.”

[[v10-24-18]]

^<<v10-24-18,18>>^ Later Gad came in to David on that day and said to him: “Go up, set up for Jehovah an altar on the threshing floor of A·rauʹnah the Jebʹu·site.”

[[v10-24-19]]

^<<v10-24-19,19>>^ And David began to go up in accord with the word of Gad, according to what Jehovah had commanded.

[[v10-24-20]]

^<<v10-24-20,20>>^ When A·rauʹnah looked down and saw the king and his servants passing along toward him, A·rauʹnah at once went out and bowed down to the king with his face to the earth.

[[v10-24-21]]

^<<v10-24-21,21>>^ Then A·rauʹnah said: “Why has my lord the king come to his servant?” At that David said: “To buy from you the threshing floor for building an altar to Jehovah, that the scourge may be halted from upon the people.”

[[v10-24-22]]

^<<v10-24-22,22>>^ But A·rauʹnah said to David: “Let my lord the king take it and offer up what is good in his eyes. See the cattle for the burnt offering and the threshing sledge and the implements of the cattle for the wood.

[[v10-24-23]]

^<<v10-24-23,23>>^ Everything A·rauʹnah, O king,^&#42;1^ does give to the king.” And A·rauʹnah went on to say to the king: “May Jehovah your God show pleasure in you.”

[NOTE]
====
. Or, “Everything Araunah as a king.”
====

[[v10-24-24]]

^<<v10-24-24,24>>^ However, the king said to A·rauʹnah: “No, but without fail I shall buy it from you for a price; and I shall not offer up to Jehovah my God burnt sacrifices without cost.” Accordingly David bought the threshing floor and the cattle for fifty silver shekels.^&#42;1^

[NOTE]
====
. To calculate value, see App 8A.
====

[[v10-24-25]]

^<<v10-24-25,25>>^ And David proceeded to build there an altar to Jehovah and offer up burnt sacrifices and communion sacrifices, and Jehovah began letting himself be entreated for the land, so that the scourge was halted from upon Israel.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-kings/011-1-kings-001.adoc#v11-1-0[Próximo Capítulo &#62;]