include::./index.adoc[]

[[v10-3-0]]
=== The Second of Samuel, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-3-1]]

^<<v10-3-1,1>>^ And the war between the house of Saul and the house of David came to be long drawn out; and David kept getting stronger, and the house of Saul kept declining more and more.

[[v10-3-2]]

^<<v10-3-2,2>>^ Meantime, sons were born to David in Heʹbron, and his firstborn came to be Amʹnon by A·hinʹo·am the Jezʹre·el·i·tess.

[[v10-3-3]]

^<<v10-3-3,3>>^ And his second was Chilʹe·ab by Abʹi·gail the wife of Naʹbal the Carʹmel·ite, and the third was Abʹsa·lom the son of Maʹa·cah the daughter of Talʹmai the king of Geshʹur.

[[v10-3-4]]

^<<v10-3-4,4>>^ And the fourth was Ad·o·niʹjah the son of Hagʹgith, and the fifth was Sheph·a·tiʹah the son of A·biʹtal.

[[v10-3-5]]

^<<v10-3-5,5>>^ And the sixth was Ithʹre·am by Egʹlah, David’s wife. These were the ones born to David in Heʹbron.

[[v10-3-6]]

^<<v10-3-6,6>>^ And it came about that while the war between the house of Saul and the house of David kept up, Abʹner himself was continually strengthening his position in the house of Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Now Saul had had a concubine whose name was Rizʹpah, the daughter of Aʹiah. Later Ish-boʹsheth^&#42;1^ said to Abʹner: “Why was it that you had relations with the concubine of my father?”

[NOTE]
====
. “Ish-bosheth,” LXXBagsterSyVg; M, “he.”
====

[[v10-3-8]]

^<<v10-3-8,8>>^ And Abʹner got very angry at the words of Ish-boʹsheth and went on to say: “Am I a dog’s head that belongs to Judah? Today I keep exercising loving-kindness toward the house of Saul your father, to his brothers and his personal friends, and I have not let you find yourself in the hand of David; and yet you call me to account for an error concerning a woman today.

[[v10-3-9]]

^<<v10-3-9,9>>^ So may God do to Abʹner and so may he add to it, if, just as Jehovah swore to David, that is not the way that I shall do to him,

[[v10-3-10]]

^<<v10-3-10,10>>^ so as to transfer the kingdom from the house of Saul and to establish the throne of David over Israel and over Judah from Dan to Beʹer-sheʹba.”

[[v10-3-11]]

^<<v10-3-11,11>>^ And he was not able to say one word more in reply to Abʹner because of being afraid of him.

[[v10-3-12]]

^<<v10-3-12,12>>^ Accordingly Abʹner sent messengers to David on the spot, saying: “To whom does the land belong?” adding: “Do conclude your covenant with me, and, look! my hand will be with you to turn to your side the whole of Israel.”

[[v10-3-13]]

^<<v10-3-13,13>>^ To this he said: “Good! I myself shall conclude a covenant with you. Only one thing there is that I am asking of you, saying, ‘You may not see my face except first you bring Miʹchal, Saul’s daughter, when you come to see my face.’”

[[v10-3-14]]

^<<v10-3-14,14>>^ Further, David sent messengers to Ish-boʹsheth, Saul’s son, saying: “Do give over my wife Miʹchal, whom I engaged to myself for a hundred foreskins of the Phi·lisʹtines.”

[[v10-3-15]]

^<<v10-3-15,15>>^ So Ish-boʹsheth sent and took her from her husband,^&#42;1^ Palʹti·el^&#42;2^ the son of Laʹish.

[NOTE]
====
. “Her husband,” LXXSyVg; M, “a man.”
. “Palti” in 1Sa 25:44.
====

[[v10-3-16]]

^<<v10-3-16,16>>^ But her husband kept walking with her, weeping as he walked after her as far as Ba·huʹrim. Then Abʹner said to him: “Go, return!” At that he returned.

[[v10-3-17]]

^<<v10-3-17,17>>^ Meanwhile there had come to be communication by Abʹner with the older men of Israel, saying: “Both yesterday and previously YOU proved yourselves seeking David as king over YOU.

[[v10-3-18]]

^<<v10-3-18,18>>^ And now act, for Jehovah himself said to David, ‘By the hand of David my servant I shall save my people Israel from the hand of the Phi·lisʹtines and from the hand of all their enemies.’”

[[v10-3-19]]

^<<v10-3-19,19>>^ Then Abʹner also spoke in the ears of Benjamin, after which Abʹner also went to speak in the ears of David at Heʹbron all that was good in the eyes of Israel and in the eyes of the whole house of Benjamin.

[[v10-3-20]]

^<<v10-3-20,20>>^ When Abʹner came to David at Heʹbron, and with him twenty men, David proceeded to make a feast for Abʹner and for the men that were with him.

[[v10-3-21]]

^<<v10-3-21,21>>^ Then Abʹner said to David: “Let me rise up and go and collect all Israel together to my lord the king, that they may conclude a covenant with you, and you will certainly become king over all that your soul craves.” So David sent Abʹner off, and he got on his way in peace.

[[v10-3-22]]

^<<v10-3-22,22>>^ And here David’s servants and Joʹab were coming from a raid, and the spoil that they brought with them was abundant. As for Abʹner, he was not with David in Heʹbron, for he had sent him off, and he was on his way in peace.

[[v10-3-23]]

^<<v10-3-23,23>>^ And Joʹab and all the army that was with him came in, and they now reported to Joʹab, saying: “Abʹner the son of Ner came to the king, and he proceeded to send him off, and he is on his way in peace.”

[[v10-3-24]]

^<<v10-3-24,24>>^ So Joʹab went in to the king and said: “What have you done? Look! Abʹner has come to you. Why was it that you sent him off so that he successfully went away?

[[v10-3-25]]

^<<v10-3-25,25>>^ You well know Abʹner the son of Ner,^&#42;1^ that it was to fool you that he came and to get to know your going out and your coming in and to get to know everything that you are doing.”

[NOTE]
====
. “You sent him off that he might go in peace? (25) Or do you not really know the badness of Abner the son of Ner?” LXX.
====

[[v10-3-26]]

^<<v10-3-26,26>>^ With that Joʹab went out from David and sent messengers after Abʹner, and they then had him return from the cistern of Siʹrah; and David himself did not know of it.

[[v10-3-27]]

^<<v10-3-27,27>>^ When Abʹner returned to Heʹbron, Joʹab now led him aside inside the gate to speak with him quietly. However, there he struck him in the abdomen, so that he died because of the blood of Asʹa·hel his brother.

[[v10-3-28]]

^<<v10-3-28,28>>^ When David heard of it afterward, he at once said: “I and my kingdom, from the standpoint of Jehovah, are innocent for time indefinite of bloodguilt for Abʹner the son of Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ May it whirl back upon the head of Joʹab and upon the entire house of his father, and let there not be cut off from Joʹab’s house a man with a running discharge or a leper or a man taking hold of the twirling spindle or one falling by the sword or one in need of bread!”

[[v10-3-30]]

^<<v10-3-30,30>>^ As for Joʹab and A·bishʹai his brother, they killed Abʹner over the fact that he had put Asʹa·hel their brother to death at Gibʹe·on in the battle.

[[v10-3-31]]

^<<v10-3-31,31>>^ Then David said to Joʹab and all the people that were with him: “Rip YOUR garments apart and tie on sackcloth and wail before Abʹner.” Even King David was walking behind the couch.

[[v10-3-32]]

^<<v10-3-32,32>>^ And they had the burial of Abʹner in Heʹbron; and the king began to raise his voice and weep at Abʹner’s burial place, and all the people gave way to weeping.

[[v10-3-33]]

^<<v10-3-33,33>>^ And the king went on to chant over Abʹner and say:
“As with the death of a senseless person should Abʹner die?

[[v10-3-34]]

^<<v10-3-34,34>>^ Your hands had not been bound ones,
And your feet had not been put into fetters of copper.
As one falling before the sons of unrighteousness you have fallen.”
At that all the people wept over him again.

[[v10-3-35]]

^<<v10-3-35,35>>^ Later all the people came to give David bread for consolation while it was yet that day, but David swore, saying: “So may God do to me and so may he add to it, if before the sun sets I shall taste bread or anything at all!”

[[v10-3-36]]

^<<v10-3-36,36>>^ And all the people themselves took notice, and it was good in their eyes. Like everything that the king did, it was in the eyes of all the people good.

[[v10-3-37]]

^<<v10-3-37,37>>^ And all the people and all Israel got to know on that day that it had not originated with the king to have Abʹner the son of Ner put to death.

[[v10-3-38]]

^<<v10-3-38,38>>^ And the king went on to say to his servants: “Do YOU not know that it is a prince and a great man that has fallen this day in Israel?

[[v10-3-39]]

^<<v10-3-39,39>>^ And I today am weak although anointed as king, and these men, the sons of Ze·ruʹiah, are too severe for me. May Jehovah repay the doer of what is bad according to his own badness.”

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]