include::./index.adoc[]

[[v10-6-0]]
=== The Second of Samuel, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-6-1]]

^<<v10-6-1,1>>^ And David proceeded again to gather all the choice men in Israel, thirty thousand.

[[v10-6-2]]

^<<v10-6-2,2>>^ Then David and all the people that were with him rose up and went to Baʹal·e-juʹdah to bring up from there the ark of the &#91;true&#93; God, where a name is called on, the name of Jehovah of armies, sitting on the cherubs.

[[v10-6-3]]

^<<v10-6-3,3>>^ However, they had the ark of the &#91;true&#93; God ride upon a new wagon, that they might carry it from the house of A·binʹa·dab, which was on the hill; and Uzʹzah and A·hiʹo, the sons of A·binʹa·dab, were leading the new wagon.

[[v10-6-4]]

^<<v10-6-4,4>>^ So they carried it from A·binʹa·dab’s house, which was on the hill—with the ark of the &#91;true&#93; God; and A·hiʹo was walking ahead of the Ark.

[[v10-6-5]]

^<<v10-6-5,5>>^ And David and all the house of Israel were celebrating before Jehovah with all sorts of instruments of juniper wood and with harps and with stringed instruments and with tambourines and with sistrums^&#42;1^ and with cymbals.

[NOTE]
====
. Or, “musical rattles.”
====

[[v10-6-6]]

^<<v10-6-6,6>>^ And they came gradually as far as the threshing floor of Naʹcon,^&#42;1^ and Uzʹzah now thrust &#91;his hand&#93; out to the ark of the &#91;true&#93; God and grabbed hold of it, for the cattle nearly caused an upset.

[NOTE]
====
. “Chidon” in 1Ch 13:9.
====

[[v10-6-7]]

^<<v10-6-7,7>>^ At that Jehovah’s anger blazed against Uzʹzah and the &#91;true&#93; God struck him down there for the irreverent act, so that he died there close by the ark of the &#91;true&#93; God.

[[v10-6-8]]

^<<v10-6-8,8>>^ And David became angry over the fact that Jehovah had broken through in a rupture against Uzʹzah, and that place came to be called Peʹrez-uzʹzah^&#42;1^ down to this day.

[NOTE]
====
. Meaning “Rupture Against Uzzah.”
====

[[v10-6-9]]

^<<v10-6-9,9>>^ And David became afraid of Jehovah on that day and began to say: “How will the ark of Jehovah come to me?”

[[v10-6-10]]

^<<v10-6-10,10>>^ And David was not willing to remove the ark of Jehovah to him at the City of David. So David had it carried aside to the house of Oʹbed-eʹdom the Gitʹtite.

[[v10-6-11]]

^<<v10-6-11,11>>^ And the ark of Jehovah kept dwelling at the house of Oʹbed-eʹdom the Gitʹtite three months; and Jehovah kept blessing Oʹbed-eʹdom and all his household.

[[v10-6-12]]

^<<v10-6-12,12>>^ Finally the report was made to King David, saying: “Jehovah has blessed the house of Oʹbed-eʹdom and all that is his on account of the ark of the &#91;true&#93; God.” At that David proceeded to go and bring the ark of the &#91;true&#93; God out of the house of Oʹbed-eʹdom up to the City of David with rejoicing.

[[v10-6-13]]

^<<v10-6-13,13>>^ And it came about that when the carriers of the ark of Jehovah had marched six steps, he immediately sacrificed a bull and a fatling.

[[v10-6-14]]

^<<v10-6-14,14>>^ And David was dancing around before Jehovah with all his power, all the while David being girded with an ephʹod of linen.

[[v10-6-15]]

^<<v10-6-15,15>>^ And David and all the house of Israel were bringing up the ark of Jehovah with joyful shouting and sound of horn.

[[v10-6-16]]

^<<v10-6-16,16>>^ And it occurred that when the ark of Jehovah came into the City of David, Miʹchal, Saul’s daughter, herself looked down through the window and got to see King David leaping and dancing around before Jehovah; and she began to despise him in her heart.

[[v10-6-17]]

^<<v10-6-17,17>>^ So they brought the ark of Jehovah in and set it in its place inside the tent that David had pitched for it; after which David offered up burnt sacrifices and communion sacrifices before Jehovah.

[[v10-6-18]]

^<<v10-6-18,18>>^ When David was finished with offering up the burnt sacrifices and the communion sacrifices, he then blessed the people in the name of Jehovah of armies.

[[v10-6-19]]

^<<v10-6-19,19>>^ Further, he apportioned to all the people, to the whole crowd of Israel, man as well as woman, to each one a ring-shaped cake of bread and a date cake and a raisin cake, after which all the people went each to his own house.

[[v10-6-20]]

^<<v10-6-20,20>>^ David now returned to bless his own household, and Miʹchal, Saul’s daughter, came on out to meet David and then said: “How glorious the king of Israel made himself today when he uncovered himself today to the eyes of the slave girls of his servants, just as one of the empty-headed men^&#42;1^ uncovers himself outright!”

[NOTE]
====
. “Empty-headed men,” M; LXX, “dancers.”
====

[[v10-6-21]]

^<<v10-6-21,21>>^ At this David said to Miʹchal: “It was before Jehovah, who^&#42;1^ chose me rather than your father and all his household to put me in command as leader over Jehovah’s people Israel, and I will celebrate before Jehovah.

[NOTE]
====
. “It was before Jehovah, who,” M; LXX, “Before Jehovah I shall dance. Blessed be Jehovah, who.”
====

[[v10-6-22]]

^<<v10-6-22,22>>^ And I will make myself even more lightly esteemed than this, and I will become low in my^&#42;1^ eyes; and with the slave girls whom you mentioned, with them I am determined to glorify myself.”

[NOTE]
====
. “My,” MSyVg; LXX, “your.”
====

[[v10-6-23]]

^<<v10-6-23,23>>^ So, as regards Miʹchal, Saul’s daughter, she came to have no child down to the day of her death.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]