include::./index.adoc[]

[[v10-18-0]]
=== The Second of Samuel, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-18-1]]

^<<v10-18-1,1>>^ And David proceeded to number the people that were with him and to place over them chiefs of thousands and chiefs of hundreds.

[[v10-18-2]]

^<<v10-18-2,2>>^ Further, David sent one third of the people under the hand of Joʹab and one third under the hand of A·bishʹai the son of Ze·ruʹiah, Joʹab’s brother, and one third under the hand of Itʹtai the Gitʹtite. Then the king said to the people: “I myself also shall without fail go out with YOU.”

[[v10-18-3]]

^<<v10-18-3,3>>^ But the people said: “You must not go out, for if we should at all flee, they would not set heart upon us; and if half of us would die, they would not set heart upon us, because you are worth ten thousand of us; and now it would be better if you would be of service to us to give help from the city.”

[[v10-18-4]]

^<<v10-18-4,4>>^ So the king said to them: “Whatever seems good in YOUR eyes I shall do.” And the king kept standing at the side of the gate, and all the people themselves went out by hundreds and by thousands.

[[v10-18-5]]

^<<v10-18-5,5>>^ And the king went on to command Joʹab and A·bishʹai and Itʹtai, saying: “Deal gently for my sake with the young man Abʹsa·lom.” And all the people themselves heard when the king commanded all the chiefs over the matter of Abʹsa·lom.

[[v10-18-6]]

^<<v10-18-6,6>>^ And the people continued on their way out to the field to meet Israel; and the battle came to be in the forest of Eʹphra·im.^&#42;1^

[NOTE]
====
. “Ephraim,” MLXXVg; LXXL, “Mahanaim.”
====

[[v10-18-7]]

^<<v10-18-7,7>>^ Finally the people of Israel were defeated there before the servants of David, and the slaughter there turned out to be great on that day, of twenty thousand men.

[[v10-18-8]]

^<<v10-18-8,8>>^ And the battle there got to be spread out over all the land that was in sight. Furthermore, the forest did more in eating up the people than the sword did in eating them up on that day.

[[v10-18-9]]

^<<v10-18-9,9>>^ Eventually Abʹsa·lom found himself before the servants of David. And Abʹsa·lom was riding upon a mule, and the mule got to come under the network of boughs of a massive big tree, so that his head got caught fast in the big tree, and he was taken up between the heavens and the earth, as the mule itself that was under him passed along.

[[v10-18-10]]

^<<v10-18-10,10>>^ Then a certain man saw it and told Joʹab and said: “Look! I have seen Abʹsa·lom hung in a big tree.”

[[v10-18-11]]

^<<v10-18-11,11>>^ At this Joʹab said to the man who was telling him: “And here you saw it, and why did you not strike him down to the earth there? Then it would have been my obligation to give you ten pieces of silver and a belt.”

[[v10-18-12]]

^<<v10-18-12,12>>^ But the man said to Joʹab: “And although I were weighing upon my palms a thousand pieces of silver, I should not thrust my hand out against the king’s son; for in our hearing^&#42;1^ it was that the king commanded you and A·bishʹai and Itʹtai, saying, ‘WATCH, whoever &#91;you are&#93;, over the young man, over Abʹsa·lom.’

[NOTE]
====
. Lit., “ears.”
====

[[v10-18-13]]

^<<v10-18-13,13>>^ Otherwise I should have dealt treacherously against his soul and the whole matter itself would not be hidden from the king, and you yourself would take a position off on the side.”

[[v10-18-14]]

^<<v10-18-14,14>>^ To this Joʹab said: “Let me not hold myself up this way before you!” With that he took three shafts^&#42;1^ in his palm and proceeded to drive them through the heart of Abʹsa·lom while he was yet alive in the heart of the big tree.

[NOTE]
====
. Or, “weapons.” Lit., “rods.”
====

[[v10-18-15]]

^<<v10-18-15,15>>^ Then ten attendants carrying Joʹab’s weapons came around and struck Abʹsa·lom, that they might put him to death.

[[v10-18-16]]

^<<v10-18-16,16>>^ Joʹab now blew the horn, that the people might return from chasing after Israel; for Joʹab had held back the people.

[[v10-18-17]]

^<<v10-18-17,17>>^ Finally they took Abʹsa·lom and pitched him in the forest into a big hollow and raised up over him a very big pile of stones. As for all Israel, they fled each man to his home.^&#42;1^

[NOTE]
====
. Lit., “tent.”
====

[[v10-18-18]]

^<<v10-18-18,18>>^ Now Abʹsa·lom himself, while he was alive, had taken and proceeded to raise up for himself a pillar, which is in the Low Plain of the King, for he said: “I have no son in order to keep my name in remembrance.” So he called the pillar by his own name, and it continues to be called Abʹsa·lom’s Monument down to this day.

[[v10-18-19]]

^<<v10-18-19,19>>^ Now as regards A·himʹa·az the son of Zaʹdok, he said: “Let me run, please, and break the news to the king, because Jehovah has judged him &#91;to free him&#93; from the hand of his enemies.”

[[v10-18-20]]

^<<v10-18-20,20>>^ But Joʹab said to him: “You are not a man of news this day, and you must break the news on another day; but this day you must not break the news, for the very reason that^&#42;1^ the king’s own son has died.”

[NOTE]
====
. “For the very reason that.” Heb., ki-ʽa·leʹ. M is vowel-pointed to indicate the reading ki-ʽal-kenʹ as in some Heb. mss. This is qere but not kethib (read but not written). Compare Jg 20:13 ftn.
====

[[v10-18-21]]

^<<v10-18-21,21>>^ Then Joʹab said to the Cushʹite: “Go, tell the king what you have seen.” At that the Cushʹite bowed to Joʹab and began to run.

[[v10-18-22]]

^<<v10-18-22,22>>^ A·himʹa·az the son of Zaʹdok now said once again to Joʹab: “Let, now, happen whatever will, let me also myself, please, run behind the Cushʹite.” However, Joʹab said: “Why is it that you yourself have to run, my son, when there is no news being found for you?”

[[v10-18-23]]

^<<v10-18-23,23>>^ &#91;Still he said:&#93;^&#42;1^ “Let, now, happen whatever will, let me run.” So he said to him: “Run!” And A·himʹa·az began to run by the way of the District,^&#42;2^ and he eventually passed by the Cushʹite.

[NOTE]
====
. “Still he said,” LXXSyVg.
. Or, “Basin.” See Ge 13:10 ftn, “District.”
====

[[v10-18-24]]

^<<v10-18-24,24>>^ Now David was sitting between the two gates. Meantime, the watchman went to the roof of the gate by the wall. At length he raised his eyes and saw and, look! there was a man running by himself.

[[v10-18-25]]

^<<v10-18-25,25>>^ So the watchman called and told the king, at which the king said: “If he is by himself, there is news in his mouth.” And he kept coming, steadily getting nearer.

[[v10-18-26]]

^<<v10-18-26,26>>^ The watchman now saw another man running. The watchman therefore called to the gatekeeper and said: “Look! Another man running by himself!” at which the king said: “This one also is a news bearer.”

[[v10-18-27]]

^<<v10-18-27,27>>^ And the watchman went on to say: “I am seeing that the running style of the first is like the running style of A·himʹa·az the son of Zaʹdok,” at which the king said: “This is a good man, and with good news he should come.”

[[v10-18-28]]

^<<v10-18-28,28>>^ Eventually A·himʹa·az called and said to the king: “It is well!”^&#42;1^ With that he bowed to the king with his face to the earth. And he went on to say: “Blessed be Jehovah your God, who has surrendered the men that lifted up their hand against my lord the king!”

[NOTE]
====
. “It is well!” Heb., sha·lohmʹ, “Peace!” Compare vss 29, 32.
====

[[v10-18-29]]

^<<v10-18-29,29>>^ However, the king said: “Is it well with the young man Abʹsa·lom?” To this A·himʹa·az said: “I saw the great commotion at the time Joʹab sent the king’s servant and your servant, and I did not know what it was.”

[[v10-18-30]]

^<<v10-18-30,30>>^ So the king said: “Step aside, take your position here.” At that he stepped aside and kept standing still.

[[v10-18-31]]

^<<v10-18-31,31>>^ And here was the Cushʹite coming in, and the Cushʹite began to say: “Let my lord the king accept news, for Jehovah has judged you today &#91;to free you&#93; from the hand of all those rising up against you.”

[[v10-18-32]]

^<<v10-18-32,32>>^ But the king said to the Cushʹite: “Is it well with the young man Abʹsa·lom?” To this the Cushʹite said: “May the enemies of my lord the king and all those who rose up against you for evil become as the young man.”^&#42;1^

[NOTE]
====
. MLXX end chapter 18 here.
====

[[v10-18-33]]

^<<v10-18-33,33>>^ Then the king became disturbed and went up to the roof chamber over the gateway and gave way to weeping; and this is what he said as he walked: “My son Abʹsa·lom, my son, my son Abʹsa·lom! O that I might have died, I myself, instead of you, Abʹsa·lom my son, my son!”

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]