include::./index.adoc[]

[[v10-5-0]]
=== The Second of Samuel, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v10-5-1]]

^<<v10-5-1,1>>^ In time all the tribes of Israel came to David at Heʹbron and said: “Look! We ourselves are your bone and your flesh.

[[v10-5-2]]

^<<v10-5-2,2>>^ Both yesterday and previously while Saul happened to be king over us, you yourself became the one leading Israel out and bringing it in. And Jehovah proceeded to say to you, ‘You yourself will shepherd my people Israel, and you yourself will become leader over Israel.’”

[[v10-5-3]]

^<<v10-5-3,3>>^ So all the older men^&#42;1^ of Israel came to the king at Heʹbron, and King David concluded a covenant with them in Heʹbron before Jehovah; after which they anointed David as king over Israel.^&#42;2^

[NOTE]
====
. Or, “elders.”
. “Over Israel,” MSyVg; LXX, “over Israel as a whole.”
====

[[v10-5-4]]

^<<v10-5-4,4>>^ Thirty years old was David when he became king. For forty years he ruled as king.

[[v10-5-5]]

^<<v10-5-5,5>>^ In Heʹbron he ruled as king over Judah for seven years and six months; and in Jerusalem he ruled as king for thirty-three years over all Israel and Judah.

[[v10-5-6]]

^<<v10-5-6,6>>^ Consequently the king and his men went to Jerusalem against the Jebʹu·sites inhabiting the land, and they began to say to David: “You will not come in here, but the blind and the lame ones will certainly turn you away,” they thinking: “David will not come in here.”

[[v10-5-7]]

^<<v10-5-7,7>>^ Just the same, David proceeded to capture the stronghold of Zion, that is, the City of David.

[[v10-5-8]]

^<<v10-5-8,8>>^ So David said on that day: “Anyone striking the Jebʹu·sites, let him, by means of the water tunnel, make contact with both the lame and the blind, hateful to the soul of David!” That is why they say: “The blind one and the lame one will not come into the house.”

[[v10-5-9]]

^<<v10-5-9,9>>^ And David took up dwelling in the stronghold, and it came to be called the City of David; and David began to build all around from the Mound^&#42;1^ and inward.

[NOTE]
====
. Lit., “the Millo (filling).” Heb., ham·mil·lohʼʹ. Possibly a citadellike structure.
====

[[v10-5-10]]

^<<v10-5-10,10>>^ Thus David went on getting greater and greater, and Jehovah the God of armies^&#42;1^ was with him.

[NOTE]
====
. “And Jehovah the God of armies.” Heb., wa·Yhwahʹ ʼElo·hehʹ tseva·ʼohthʹ; the first occurrence of this expression. See 1Ki 19:10, 14.
====

[[v10-5-11]]

^<<v10-5-11,11>>^ And Hiʹram the king of Tyre proceeded to send messengers to David, and also cedar trees and workers in wood and workers in stone for walls, and they began to build a house for David.

[[v10-5-12]]

^<<v10-5-12,12>>^ And David came to know that Jehovah had firmly established him as king over Israel and that he had exalted his kingdom for the sake of his people Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ Meantime, David went on taking more concubines and wives out of Jerusalem after he came from Heʹbron; and more sons and daughters continued to be born to David.

[[v10-5-14]]

^<<v10-5-14,14>>^ And these are the names of those born to him in Jerusalem: Sham·muʹa and Shoʹbab and Nathan and Solʹo·mon,

[[v10-5-15]]

^<<v10-5-15,15>>^ and Ibʹhar and E·liʹshu·a and Neʹpheg and Ja·phiʹa,

[[v10-5-16]]

^<<v10-5-16,16>>^ and E·lishʹa·ma and E·liʹa·da and E·liphʹe·let.

[[v10-5-17]]

^<<v10-5-17,17>>^ And the Phi·lisʹtines got to hear that they had anointed David as king over Israel. At that all the Phi·lisʹtines came up to look for David. When David heard of it, then he went down to the place hard to approach.

[[v10-5-18]]

^<<v10-5-18,18>>^ And the Phi·lisʹtines, for their part, came in and kept tramping about in the low plain of Rephʹa·im.

[[v10-5-19]]

^<<v10-5-19,19>>^ And David began to inquire of Jehovah, saying: “Shall I go up against the Phi·lisʹtines? Will you give them into my hand?” At this Jehovah said to David: “Go up, for I shall without fail give the Phi·lisʹtines into your hands.”

[[v10-5-20]]

^<<v10-5-20,20>>^ So David came to Baʹal-pe·raʹzim, and David got to strike them down there. At that he said: “Jehovah has broken through my enemies ahead of me, like a gap made by waters.” That is why he called the name of that place Baʹal-pe·raʹzim.^&#42;1^

[NOTE]
====
. Meaning “Master of Breakings Through.”
====

[[v10-5-21]]

^<<v10-5-21,21>>^ Consequently they left their idols^&#42;1^ there, and so David and his men took them away.

[NOTE]
====
. “Idols,” MSyVg; LXX and 1Ch 14:12, “gods.”
====

[[v10-5-22]]

^<<v10-5-22,22>>^ Later the Phi·lisʹtines came up once again and tramped about in the low plain of Rephʹa·im.

[[v10-5-23]]

^<<v10-5-23,23>>^ At that David inquired of Jehovah, but he said: “You must not go up. Go around to the rear of them, and you must come against them in front of the baʹca bushes.^&#42;1^

[NOTE]
====
. “Baca bushes.” Heb., bekha·ʼimʹ, pl.; LXX, “place of weeping.”
====

[[v10-5-24]]

^<<v10-5-24,24>>^ And let it occur that, when you hear the sound of a marching^&#42;1^ in the tops of the baʹca bushes, at that time you act with decision, because at that time Jehovah will have gone out ahead of you to strike down the camp of the Phi·lisʹtines.”

[NOTE]
====
. “The marching” in 1Ch 14:15.
====

[[v10-5-25]]

^<<v10-5-25,25>>^ Accordingly David did that way, just as Jehovah had commanded him, and he went striking down the Phi·lisʹtines from Geʹba^&#42;1^ to as far as Geʹzer.

[NOTE]
====
. “From Geba.” Heb., mig·Geʹvaʽ; Gr., Ga·ba·onʹ; in 1Ch 14:16, “Gibeon.”
====

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]