include::./index.adoc[]

[[v64-1-0]]
=== The Third of John, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v64-1-1]]

^<<v64-1-1,1>>^ The older man^&#42;1^ to Gaʹius, the beloved, whom I truly love.^&#42;2^

[NOTE]
====
. Or, “elder.” Gr., pre·sbyʹte·ros.
. Or, “I love in the truth.”
====

[[v64-1-2]]

^<<v64-1-2,2>>^ Beloved one, I pray that in all things you may be prospering^&#42;1^ and having good health, just as your soul is prospering.

[NOTE]
====
. Lit., “to make one’s way well.”
====

[[v64-1-3]]

^<<v64-1-3,3>>^ For I rejoiced very much^&#42;1^ when brothers came^&#42;2^ and bore witness to the truth you hold, just as you go on walking in the truth.

[NOTE]
====
. Lit., “excessively.”
. “Came.” Gr., er·kho·meʹnon, referring to a past coming.
====

[[v64-1-4]]

^<<v64-1-4,4>>^ No greater cause for thankfulness do I have than these things, that I should be hearing that my children go on walking in the truth.

[[v64-1-5]]

^<<v64-1-5,5>>^ Beloved one, you are doing a faithful work in whatever you do for the brothers, and strangers at that,

[[v64-1-6]]

^<<v64-1-6,6>>^ who have borne witness to your love before the congregation. These you will please^&#42;1^ send on their way in a manner worthy of God.

[NOTE]
====
. Or, “you will do well to.”
====

[[v64-1-7]]

^<<v64-1-7,7>>^ For it was in behalf of &#91;his&#93;^&#42;1^ name that they went forth, not taking anything from the people of the nations.

[NOTE]
====
. Or, “the.”
====

[[v64-1-8]]

^<<v64-1-8,8>>^ We, therefore, are under obligation to receive such persons hospitably, that we may become fellow workers in the truth.^&#42;1^

[NOTE]
====
. Or, “become workers with the truth.”
====

[[v64-1-9]]

^<<v64-1-9,9>>^ I wrote something to the congregation, but Di·otʹre·phes, who likes to have the first place^&#42;1^ among them, does not receive anything from us with respect.

[NOTE]
====
. Lit., “the (one) liking to be first.”
====

[[v64-1-10]]

^<<v64-1-10,10>>^ That is why, if I come, I will call to remembrance his works which he goes on doing, chattering about us with wicked words. Also, not being content^&#42;1^ with these things, neither does he himself receive the brothers with respect, and those who are wanting to receive them he tries^&#42;2^ to hinder and to throw out of the congregation.

[NOTE]
====
. Lit., “not being satisfied.”
. Or, “continues; makes it his practice.”
====

[[v64-1-11]]

^<<v64-1-11,11>>^ Beloved one, be an imitator, not of what is bad, but of what is good. He that does good originates with God. He that does bad has not seen God.

[[v64-1-12]]

^<<v64-1-12,12>>^ De·meʹtri·us has had witness borne to him by them all and by the truth itself. In fact, we, also, are bearing witness, and you know that the witness we give is true.

[[v64-1-13]]

^<<v64-1-13,13>>^ I had many things to write you, yet I do not wish to go on writing you with ink and pen.^&#42;1^

[NOTE]
====
. Lit., “reed.”
====

[[v64-1-14]]

^<<v64-1-14,14>>^ But I am hoping to see you directly, and we shall speak face to face.^&#42;1^
May you have peace.
The friends send you their greetings. Give my greetings to the friends by name.

[NOTE]
====
. Lit., “mouth toward mouth.”
====

'''

xref:063-2-john/063-2-john-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-jude/065-jude-001.adoc#v65-1-0[Próximo Capítulo &#62;]