include::./index.adoc[]

[[v30-1-0]]
=== Amos, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-1-1]]

^<<v30-1-1,1>>^ The words of Aʹmos, who happened to be among the sheep raisers from Te·koʹa, which he visioned concerning Israel in the days of Uz·ziʹah the king of Judah and in the days of Jer·o·boʹam the son of Joʹash, the king of Israel, two years before the earthquake.

[[v30-1-2]]

^<<v30-1-2,2>>^ And he proceeded to say:
“Jehovah—out of Zion he will roar, and out of Jerusalem he will give forth his voice; and the pasture grounds of the shepherds must go to mourning, and the summit of Carʹmel must dry up.”

[[v30-1-3]]

^<<v30-1-3,3>>^ “This is what Jehovah has said, ‘“On account of three revolts of Damascus, and on account of four, I shall not turn it back, on account of their threshing Gilʹe·ad even with iron threshing instruments.

[[v30-1-4]]

^<<v30-1-4,4>>^ And I will send a fire onto the house of Hazʹa·el, and it must devour the dwelling towers of Ben-haʹdad.

[[v30-1-5]]

^<<v30-1-5,5>>^ And I will break the bar of Damascus and cut off &#91;the&#93; inhabitant from Bikʹath-aʹven,^&#42;1^ and the holder of &#91;the&#93; scepter from Beth-eʹden;^&#42;2^ and the people of Syria^&#42;3^ will have to go as exiles to Kir,” Jehovah has said.’

[NOTE]
====
. Or, “the Valley Plain of Aven.”
. Or, “the House of Eden.”
. “Syria,” LXXVg; MTSy, “Aram.”
====

[[v30-1-6]]

^<<v30-1-6,6>>^ “This is what Jehovah has said, ‘“On account of three revolts of Gaʹza, and on account of four, I shall not turn it back, on account of their taking into exile a complete body of exiles to hand over to Eʹdom.

[[v30-1-7]]

^<<v30-1-7,7>>^ And I will send a fire onto the wall of Gaʹza, and it must devour her dwelling towers.

[[v30-1-8]]

^<<v30-1-8,8>>^ And I will cut off &#91;the&#93; inhabitant from Ashʹdod, and the holder of &#91;the&#93; scepter from Ashʹke·lon; and I will turn my hand back upon Ekʹron, and the remaining ones^&#42;1^ of the Phi·lisʹtines must perish,” the Sovereign Lord Jehovah has said.’

[NOTE]
====
. Or, “the remnant.”
====

[[v30-1-9]]

^<<v30-1-9,9>>^ “This is what Jehovah has said, ‘On account of three revolts of Tyre, and on account of four, I shall not turn it back, on account of their handing over a complete body of exiles to Eʹdom, and &#91;because&#93; they did not remember the covenant of brothers.

[[v30-1-10]]

^<<v30-1-10,10>>^ And I will send a fire onto the wall of Tyre, and it must devour her dwelling towers.’

[[v30-1-11]]

^<<v30-1-11,11>>^ “This is what Jehovah has said, ‘On account of three revolts of Eʹdom, and on account of four, I shall not turn it back, on account of his pursuing his own brother with the sword, and &#91;because&#93; he ruined his &#91;own&#93; merciful qualities, and his anger keeps tearing away forever; and his fury—he has kept it perpetually.

[[v30-1-12]]

^<<v30-1-12,12>>^ And I will send a fire into Teʹman, and it must devour the dwelling towers of Bozʹrah.’

[[v30-1-13]]

^<<v30-1-13,13>>^ “This is what Jehovah has said, ‘“On account of three revolts of the sons of Amʹmon,^&#42;1^ and on account of four, I shall not turn it back, on account of their slitting open the pregnant women of Gilʹe·ad, for the purpose of widening out their own territory.

[NOTE]
====
. “The sons of Ammon.” Or, “the Ammonites.”
====

[[v30-1-14]]

^<<v30-1-14,14>>^ And I will set fire to the wall of Rabʹbah, and it must devour her dwelling towers, with an alarm signal in the day of battle, with a tempest in the day of storm wind.

[[v30-1-15]]

^<<v30-1-15,15>>^ And their king must go into exile, he and his princes together,” Jehovah has said.’

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]