include::./index.adoc[]

[[v30-8-0]]
=== Amos, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-8-1]]

^<<v30-8-1,1>>^ This is what the Sovereign Lord Jehovah caused me to see, and, look! there was a basket of summer fruit.

[[v30-8-2]]

^<<v30-8-2,2>>^ Then he said: “What are you seeing, Aʹmos?” So I said: “A basket of summer fruit.”^&#42;1^ And Jehovah went on to say to me: “The end^&#42;2^ has come to my people Israel. I shall no more do any further excusing of them.

[NOTE]
====
. “Summer fruit.” Heb., qaʹyits; points to the ending of the agricultural year.
. “The end.” Heb., haq·qetsʹ; a play on the Heb. word qaʹyits, “summer fruit,” in the first part of the vs.
====

[[v30-8-3]]

^<<v30-8-3,3>>^ ‘And the songs of &#91;the&#93; temple will actually be a howling in that day,’ is the utterance of the Sovereign Lord Jehovah. ‘There will be many a carcass. In every place one will certainly throw &#91;them&#93; out—hush!’

[[v30-8-4]]

^<<v30-8-4,4>>^ “Hear this, YOU men snapping at someone poor, even in order to cause the meek ones^&#42;1^ of the earth to cease,

[NOTE]
====
. “Meek ones,” M; Mmargin, “afflicted ones.”
====

[[v30-8-5]]

^<<v30-8-5,5>>^ saying, ‘How long will it be before the new moon passes and we may sell cereals? Also, the sabbath, and we may offer grain for sale; in order to make the eʹphah small and to make the shekel great and to falsify the scales of deception;

[[v30-8-6]]

^<<v30-8-6,6>>^ in order to buy lowly people for mere silver and someone poor for &#91;the price of&#93; a pair of sandals, and that we may sell mere refuse of grain?’

[[v30-8-7]]

^<<v30-8-7,7>>^ “Jehovah has sworn by the Superiority^&#42;1^ of Jacob, ‘Never will I forget all their works.

[NOTE]
====
. Or, “Pride.”
====

[[v30-8-8]]

^<<v30-8-8,8>>^ Will it not be on this account that the land^&#42;1^ will be agitated, and every inhabitant in it will have to mourn; and it will, all of it, certainly come up just like the Nile and be tossed and sink down like the Nile of Egypt?’

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v30-8-9]]

^<<v30-8-9,9>>^ “‘And it must occur in that day,’ is the utterance of the Sovereign Lord Jehovah, ‘that I will make the sun go down at high noon, and I will cause darkness for the land on a bright day.

[[v30-8-10]]

^<<v30-8-10,10>>^ And I will turn YOUR festivals into mourning and all YOUR songs into a dirge, and I will bring up upon all hips sackcloth and upon every head baldness; and I will make the situation like the mourning for an only &#91;son&#93;, and the end result of it as a bitter day.’

[[v30-8-11]]

^<<v30-8-11,11>>^ “‘Look! There are days coming,’ is the utterance of the Sovereign Lord Jehovah, ‘and I will send a famine into the land, a famine, not for bread,^&#42;1^ and a thirst, not for water, but for hearing the words of Jehovah.

[NOTE]
====
. Or, “for food.” Heb., lal·leʹchem.
====

[[v30-8-12]]

^<<v30-8-12,12>>^ And they will certainly stagger from sea all the way to sea, and from north even to the sunrise. They will keep roving about while searching for the word of Jehovah, but they will not find &#91;it&#93;.

[[v30-8-13]]

^<<v30-8-13,13>>^ In that day the pretty virgins will swoon away, also the young men, because of the thirst;

[[v30-8-14]]

^<<v30-8-14,14>>^ those who are swearing by the guiltiness of Sa·marʹi·a, and who actually say: “As your god is alive,^&#42;1^ O Dan!” and, “As the way of Beʹer-sheʹba is alive!” And they will certainly fall, and they will rise up no more.’”

[NOTE]
====
. Lit., “Alive [is] your god.” Heb., cheh ʼelo·heyʹkha, the adjective “alive” being masc. sing.; Gr., the·osʹ; Lat., deʹus.
====

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]