include::./index.adoc[]

[[v30-4-0]]
=== Amos, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-4-1]]

^<<v30-4-1,1>>^ “Hear this word, YOU cows of Baʹshan, who are on the mountain of Sa·marʹi·a, who are defrauding the lowly ones, who are crushing the poor ones, who are saying to their masters, ‘Do bring, and let us drink!’

[[v30-4-2]]

^<<v30-4-2,2>>^ The Sovereign Lord Jehovah has sworn by his holiness, ‘“Look! There are days coming upon YOU, and he will certainly lift YOU up with butcher hooks and the last part of YOU with fishhooks.

[[v30-4-3]]

^<<v30-4-3,3>>^ And &#91;by&#93; breaches YOU will go forth, each one straight ahead;^&#42;1^ and YOU will certainly be thrown out^&#42;2^ to Harʹmon,” is the utterance of Jehovah.’

[NOTE]
====
. Lit., “each female [Heb., ʼish·shahʹ] in front of her.”
. “You will certainly be thrown out,” by a correction; M, “you [fem. pl.] will certainly throw out.”
====

[[v30-4-4]]

^<<v30-4-4,4>>^ “‘Come, YOU people, to Bethʹel and commit transgression. At Gilʹgal be frequent in committing transgression, and bring YOUR sacrifices in the morning; on the third day, YOUR tenth parts.^&#42;1^

[NOTE]
====
. Or, “your tithes.”
====

[[v30-4-5]]

^<<v30-4-5,5>>^ And from what is leavened make a thanksgiving sacrifice to smoke, and proclaim voluntary offerings; publish &#91;it&#93;, for that is the way YOU have loved, O sons of Israel,’ is the utterance of the Sovereign Lord Jehovah.

[[v30-4-6]]

^<<v30-4-6,6>>^ “‘And I also, for my part, gave YOU people cleanness of teeth in all YOUR cities and want of bread in all YOUR places; but YOU did not come back to me,’ is the utterance of Jehovah.

[[v30-4-7]]

^<<v30-4-7,7>>^ “‘And as for me, I also withheld from YOU people the downpour when there were yet three months to the harvest; and I made it rain on one city, but on another city I would not make it rain. There was one tract of land that would be rained on, but a tract of land on which I would not make it rain^&#42;1^ would be dried up.

[NOTE]
====
. “I would not make it rain,” LXXVg; M, “it would not rain.”
====

[[v30-4-8]]

^<<v30-4-8,8>>^ And two or three cities staggered to one city in order to drink water, and they would not get satisfied; but YOU did not come back to me,’ is the utterance of Jehovah.

[[v30-4-9]]

^<<v30-4-9,9>>^ “‘I struck YOU people with scorching and mildew. There was a multiplying of YOUR gardens and of YOUR vineyards, but YOUR fig trees and YOUR olive trees the caterpillar would devour; yet YOU did not come back to me,’ is the utterance of Jehovah.

[[v30-4-10]]

^<<v30-4-10,10>>^ “‘I sent among YOU people a pestilence in the nature of that of Egypt. With the sword I killed YOUR young men, along with the taking captive of YOUR horses. And I kept making the stink of YOUR camps ascend even into YOUR nostrils; but YOU did not come back to me,’ is the utterance of Jehovah.

[[v30-4-11]]

^<<v30-4-11,11>>^ “‘I caused an overthrow among YOU people, like God’s^&#42;1^ overthrow of Sodʹom and Go·morʹrah. And YOU came to be like a log snatched out of &#91;the&#93; burning; but YOU did not come back to me,’ is the utterance of Jehovah.

[NOTE]
====
. “God’s.” Heb., ʼElo·himʹ; Gr., The·osʹ; Lat., Deʹus.
====

[[v30-4-12]]

^<<v30-4-12,12>>^ “Therefore that is what I shall do to you, O Israel. As a consequence of the fact that I shall do this very thing to you, get ready to meet your God,^&#42;1^ O Israel.

[NOTE]
====
. “Your God.” Heb., ʼElo·heyʹkha.
====

[[v30-4-13]]

^<<v30-4-13,13>>^ For, look! the Former of &#91;the&#93; mountains and the Creator of &#91;the&#93; wind, and the One telling to earthling man^&#42;1^ what his mental concern^&#42;2^ is, the One making dawn into obscurity, and the One treading on earth’s high places, Jehovah the God of armies^&#42;3^ is his name.”

[NOTE]
====
. “To earthling man.” Heb., leʼa·dhamʹ; Gr., an·throʹpous; Lat., hoʹmi·ni.
. “His mental concern,” M; LXX, “his Christ (Anointed One).”
. “God of armies,” M; LXX, “God, the Almighty.” Compare Re 11:17.
====

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]