include::./index.adoc[]

[[v30-3-0]]
=== Amos, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-3-1]]

^<<v30-3-1,1>>^ “Hear this word that Jehovah has spoken concerning YOU, O sons of Israel, concerning the whole family that I brought up out of the land of Egypt, saying,

[[v30-3-2]]

^<<v30-3-2,2>>^ ‘YOU people only have I known out of all the families of the ground. That is why I shall hold an accounting against YOU for all YOUR errors.

[[v30-3-3]]

^<<v30-3-3,3>>^ “‘Will two walk together unless they have met by appointment?

[[v30-3-4]]

^<<v30-3-4,4>>^ Will a lion roar in the forest when it has no prey? Will a young maned lion give forth its voice from its hiding place if it has caught nothing at all?

[[v30-3-5]]

^<<v30-3-5,5>>^ Will a bird fall into a trap on the earth when there is no snare for it? Does a trap go up from the ground when it has absolutely caught nothing?

[[v30-3-6]]

^<<v30-3-6,6>>^ If a horn is blown in a city, do not also the people themselves tremble? If a calamity occurs in the city, is it not also Jehovah who has acted?

[[v30-3-7]]

^<<v30-3-7,7>>^ For the Sovereign Lord Jehovah will not do a thing unless he has revealed his confidential matter^&#42;1^ to his servants the prophets.

[NOTE]
====
. “His confidential matter.” Heb., soh·dhohʹ; Lat., se·creʹtum.
====

[[v30-3-8]]

^<<v30-3-8,8>>^ There is a lion that has roared! Who will not be afraid? The Sovereign Lord Jehovah himself has spoken! Who will not prophesy?’

[[v30-3-9]]

^<<v30-3-9,9>>^ “‘PUBLISH it on &#91;the&#93; dwelling towers in Ashʹdod and on &#91;the&#93; dwelling towers in the land of Egypt, and say: “Be gathered together against the mountains of Sa·marʹi·a, and see the many disorders in the midst of her and cases of defrauding inside her.

[[v30-3-10]]

^<<v30-3-10,10>>^ And they have not known how to do what is straightforward,” is the utterance of Jehovah, “those who are storing up violence and despoiling in their dwelling towers.”’

[[v30-3-11]]

^<<v30-3-11,11>>^ “Therefore this is what the Sovereign Lord Jehovah has said, ‘There is an adversary even round about the land, and he will certainly bring your^&#42;1^ strength down from you, and your dwelling towers will actually be plundered.’

[NOTE]
====
. “Your,” fem. sing., referring to the city, fem.
====

[[v30-3-12]]

^<<v30-3-12,12>>^ “This is what Jehovah has said, ‘Just as the shepherd snatches away from the mouth of the lion two shanks or a piece of an ear, so the sons of Israel will be snatched away, those sitting in Sa·marʹi·a on a splendid couch and on a Dam·a·sceneʹ divan.’

[[v30-3-13]]

^<<v30-3-13,13>>^ “‘HEAR and give witness^&#42;1^ in the house of Jacob,’ is the utterance of the Sovereign Lord Jehovah, the God of the armies.^&#42;2^

[NOTE]
====
. Or, “warning.”
. “The God of the armies.” Heb., ʼElo·hehʹ hats·tseva·ʼohthʹ; Lat., Deʹus e·xer·ciʹtu·um.
====

[[v30-3-14]]

^<<v30-3-14,14>>^ ‘For, in the day of my holding an accounting for the revolts of Israel against him, I will also hold an accounting against the altars of Bethʹel; and the horns of the altar will certainly be cut off and must fall to the earth.

[[v30-3-15]]

^<<v30-3-15,15>>^ And I will strike down the winter house in addition to the summer house.’
“‘And the houses of ivory will have to perish, and many houses will have to come to their finish,’ is the utterance of Jehovah.”

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]