include::./index.adoc[]

[[v30-7-0]]
=== Amos, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-7-1]]

^<<v30-7-1,1>>^ This is what the Sovereign Lord Jehovah caused me to see, and, look! he was forming a &#91;locust&#93; swarm at the start of the coming up of the later sowing.^&#42;1^ And, look! it was the later sowing after the mown grass of the king.^&#42;2^

[NOTE]
====
. “Later sowing,” that is, during January and February. See App 8B.
. “And, look! one locust was Gog the king,” LXX. Compare Eze 38:2.
====

[[v30-7-2]]

^<<v30-7-2,2>>^ And it occurred that when it had finished eating up the vegetation of the land,^&#42;1^ I proceeded to say: “O Sovereign Lord Jehovah, forgive, please. Who will rise up of Jacob? For he is small!”

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v30-7-3]]

^<<v30-7-3,3>>^ Jehovah felt regret over this. “It shall not occur,” Jehovah said.

[[v30-7-4]]

^<<v30-7-4,4>>^ This is what the Sovereign Lord Jehovah caused me to see, and, look! the Sovereign Lord Jehovah was calling for a contention by means of fire; and it went eating up the vast watery deep^&#42;1^ and ate up the tract of land.

[NOTE]
====
. “Watery deep.” Or, “surging waters.” Heb., tehohmʹ; LXXVg, “abyss.” Compare Ge 1:2 ftn, “Deep.”
====

[[v30-7-5]]

^<<v30-7-5,5>>^ And I proceeded to say: “O Sovereign Lord Jehovah, hold off, please. Who will rise up of Jacob? For he is small!”

[[v30-7-6]]

^<<v30-7-6,6>>^ Jehovah felt regret over this. “That, too, will not occur,” the Sovereign Lord Jehovah said.

[[v30-7-7]]

^<<v30-7-7,7>>^ This is what he caused me to see, and, look! Jehovah^&#42;1^ was stationed on a wall &#91;made with&#93; a plummet, and there was a plummet in his hand.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v30-7-8]]

^<<v30-7-8,8>>^ Then Jehovah said to me: “What are you seeing, Aʹmos?”^&#42;1^ So I said: “A plummet.” And Jehovah^&#42;2^ went on to say: “Here I am setting a plummet in the midst of my people Israel. I shall no more do any further excusing of it.

[NOTE]
====
. See Title ftn.
. See vs 7 ftn.
====

[[v30-7-9]]

^<<v30-7-9,9>>^ And the high places of Isaac^&#42;1^ will certainly be laid desolate, and the sanctuaries themselves of Israel will be devastated; and I will rise up against the house of Jer·o·boʹam^&#42;2^ with a sword.”

[NOTE]
====
. “Isaac.” Heb., Yis·chaqʹ, as in Ps 105:9 and Jer 33:26.
. That is, Jeroboam II, the son of Joash (Jehoash); not Jeroboam I, the son of Nebat. See 1:1.
====

[[v30-7-10]]

^<<v30-7-10,10>>^ And Am·a·ziʹah the priest of Bethʹel proceeded to send to Jer·o·boʹam the king of Israel, saying: “Aʹmos has conspired against you right inside the house of Israel. The land^&#42;1^ is not able to put up with all his words.

[NOTE]
====
. Or, “The earth.” Heb., ha·ʼaʹrets.
====

[[v30-7-11]]

^<<v30-7-11,11>>^ For this is what Aʹmos has said, ‘By the sword Jer·o·boʹam will die; and as regards Israel, it will without fail go into exile from its own ground.’”

[[v30-7-12]]

^<<v30-7-12,12>>^ And Am·a·ziʹah proceeded to say to Aʹmos: “O visionary, go, run your way off to the land of Judah, and there eat bread, and there you may prophesy.

[[v30-7-13]]

^<<v30-7-13,13>>^ But at Bethʹel you must no longer do any further prophesying, for it is the sanctuary of a king and it is the house of a kingdom.”

[[v30-7-14]]

^<<v30-7-14,14>>^ Then Aʹmos answered and said to Am·a·ziʹah: “I was not a prophet, neither was I the son of a prophet;^&#42;1^ but I was a herdsman and a nipper of figs of sycamore trees.

[NOTE]
====
. Or, “was I a member of the band of prophets.” See GK, § 128 v.
====

[[v30-7-15]]

^<<v30-7-15,15>>^ And Jehovah proceeded to take me from following the flock, and Jehovah went on to say to me, ‘Go, prophesy to my people Israel.’

[[v30-7-16]]

^<<v30-7-16,16>>^ And now hear the word of Jehovah, ‘Are you saying: “You must not prophesy against Israel, and you must let no &#91;word&#93; drop against the house of Isaac”?^&#42;1^

[NOTE]
====
. See vs 9 ftn, “Isaac.”
====

[[v30-7-17]]

^<<v30-7-17,17>>^ Therefore this is what Jehovah has said: “As regards your wife, in the city she will become a prostitute. And as regards your sons and your daughters, by the sword they will fall. And as regards your ground, by the measuring rope it will be apportioned out. And as regards you yourself, on unclean ground you will die; and as regards Israel, it will without fail go into exile from its own ground.”’”

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]