include::./index.adoc[]

[[v30-5-0]]
=== Amos, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-5-1]]

^<<v30-5-1,1>>^ “Hear this word that I am taking up over YOU people as a dirge, O house of Israel:

[[v30-5-2]]

^<<v30-5-2,2>>^ “The virgin, Israel, has fallen;
She cannot get up again.
She has been forsaken upon her own ground;
There is no one raising her up.

[[v30-5-3]]

^<<v30-5-3,3>>^ “For this is what the Sovereign Lord Jehovah has said, ‘The very city that was going forth with a thousand will have a hundred left; and the one going forth with a hundred will have ten left, for the house of Israel.’

[[v30-5-4]]

^<<v30-5-4,4>>^ “For this is what Jehovah has said to the house of Israel, ‘Search for me, and keep living.

[[v30-5-5]]

^<<v30-5-5,5>>^ And do not search for Bethʹel, and to Gilʹgal YOU must not come, and to Beʹer-sheʹba YOU must not pass over; because Gilʹgal itself will without fail go into exile; and as regards Bethʹel, it will become something uncanny.

[[v30-5-6]]

^<<v30-5-6,6>>^ Search for Jehovah, and keep living, that he may not become operative just like fire, O house of Joseph, and it may not actually devour, and Bethʹel^&#42;1^ may not be with no one to extinguish &#91;it&#93;,

[NOTE]
====
. “Bethel,” MTSyVg; LXX, “the house of Israel.”
====

[[v30-5-7]]

^<<v30-5-7,7>>^ O YOU who are turning justice into mere wormwood, and the ones who have cast righteousness itself to the earth.

[[v30-5-8]]

^<<v30-5-8,8>>^ The Maker of the Kiʹmah constellation^&#42;1^ and the Keʹsil constellation,^&#42;2^ and the One turning deep shadow into the morning itself, and the One who has made day itself dark as night, the One calling for the waters of the sea, that he may pour them out upon the surface of the earth—Jehovah is his name;

[NOTE]
====
. See Job 9:9 ftn, “Kimah constellation.”
. See Job 9:9 ftn, “Kesil constellation.”
====

[[v30-5-9]]

^<<v30-5-9,9>>^ he who is causing a despoiling to flash forth upon someone strong, that despoiling itself may come upon even a fortified place.

[[v30-5-10]]

^<<v30-5-10,10>>^ “‘In the gate they have hated a reprover, and a speaker of perfect things they detest.

[[v30-5-11]]

^<<v30-5-11,11>>^ Therefore, for the reason that YOU are extracting farm rent from someone lowly, and the tribute of grain YOU keep taking from him; houses of hewn stone YOU have built, but YOU will not keep dwelling in them; and desirable vineyards YOU have planted, but YOU will not keep drinking the wine of them.

[[v30-5-12]]

^<<v30-5-12,12>>^ For I have known how many YOUR revolts are and how mighty YOUR sins are, O YOU who are showing hostility toward someone righteous, YOU who are taking hush money,^&#42;1^ and the ones who have turned aside poor people even in the gate.

[NOTE]
====
. Or, “a ransom.” Heb., khoʹpher.
====

[[v30-5-13]]

^<<v30-5-13,13>>^ Therefore the very one having insight will in that time keep silent, for it will be a calamitous time.

[[v30-5-14]]

^<<v30-5-14,14>>^ “‘Search for what is good, and not what is bad, to the end that YOU people may keep living; and that thus Jehovah the God of armies^&#42;1^ may come to be with YOU, just as YOU have said.

[NOTE]
====
. “The God of armies.” Heb., ʼElo·heh-tseva·ʼohthʹ.
====

[[v30-5-15]]

^<<v30-5-15,15>>^ Hate what is bad, and love what is good, and give justice a place in the gate. It may be that Jehovah the God of armies will show favor to the remaining ones of Joseph.’

[[v30-5-16]]

^<<v30-5-16,16>>^ “Therefore this is what Jehovah the God of armies, Jehovah,^&#42;1^ has said, ‘In all the public squares there will be wailing, and in all the streets people will be saying: “Ah! Ah!” And they will have to call a farmer to mourning, and to wailing those experienced in lamentation.’

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v30-5-17]]

^<<v30-5-17,17>>^ ‘And in all vineyards there will be wailing; for I shall pass through the midst of you,’ Jehovah has said.

[[v30-5-18]]

^<<v30-5-18,18>>^ “‘Woe to those who are craving the day of Jehovah! What, then, will the day of Jehovah mean to YOU people? It will be darkness, and no light,

[[v30-5-19]]

^<<v30-5-19,19>>^ just as when a man^&#42;1^ flees because of the lion, and the bear actually meets him; and &#91;as when&#93; he went into the house and supported his hand against the wall, and the serpent bit him.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v30-5-20]]

^<<v30-5-20,20>>^ Will not the day of Jehovah be darkness, and not light; and will it not have gloom, and not brightness?

[[v30-5-21]]

^<<v30-5-21,21>>^ I have hated, I have rejected YOUR festivals, and I shall not enjoy the smell of YOUR solemn assemblies.

[[v30-5-22]]

^<<v30-5-22,22>>^ But if YOU people offer up to me whole burnt offerings, even in YOUR gift offerings I shall find no pleasure, and on YOUR communion sacrifices of fatlings I shall not look.

[[v30-5-23]]

^<<v30-5-23,23>>^ Remove from me the turmoil of your songs; and the melodious sound of your stringed instruments may I not hear.

[[v30-5-24]]

^<<v30-5-24,24>>^ And let justice roll forth just like waters, and righteousness like a constantly flowing torrent.

[[v30-5-25]]

^<<v30-5-25,25>>^ Was it sacrifices and gift offerings that YOU people brought near to me in the wilderness for forty years, O house of Israel?

[[v30-5-26]]

^<<v30-5-26,26>>^ And YOU will certainly carry^&#42;1^ Sakʹkuth^&#42;2^ YOUR king^&#42;3^ and Kaiʹwan,^&#42;4^ YOUR images, the star of YOUR god,^&#42;5^ whom YOU made for yourselves.

[NOTE]
====
. Or, “you have carried.”
. “Sakkuth.” Heb., Sik·kuthʹ. The name was purposely vocalized in Heb. to correspond to shiq·qutsʹ, “disgusting thing.” It possibly refers to a star-god, for it is put in a parallelism with the “star of your god” in the same vs. LXXSy, “the tent”; Lat., ta·ber·naʹcu·lum.
. “Your king.” Heb., mal·kekhemʹ; Gr., Mo·lokhʹ; Syr., demal·kum; Lat., Moʹloch.
. “Kaiwan.” Or, “Kewan.” Heb., Ki·yunʹ, vowel-pointed intentionally to correspond with shiq·qutsʹ, “disgusting thing.” Evidently the Akkadian star Kai·maʹnu, or Kai·waʹnu, is meant, because this occurs in Akkadian inscriptions as the name for Saturn (a star-god). Gr., Rhai·phanʹ; in Ac 7:43 in Stephen’s quotation, Rhom·phaʹ.
. “Your god.” Heb., ʼelo·heh·khemʹ, referring to a false god.
====

[[v30-5-27]]

^<<v30-5-27,27>>^ And I will cause YOU to go into exile beyond Damascus,’ he whose name is Jehovah the God of armies has said.”

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]