include::./index.adoc[]

[[v30-6-0]]
=== Amos, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-6-1]]

^<<v30-6-1,1>>^ “Woe to those who are at ease in Zion and to those trusting in the mountain of Sa·marʹi·a! They are the distinguished ones of the chief part of the nations, and to them the house of Israel have come.

[[v30-6-2]]

^<<v30-6-2,2>>^ Make YOUR way over to Calʹneh, and see; and go from there to populous Haʹmath, and go down to Gath of the Phi·lisʹtines. Are they better than these kingdoms, or is their territory bigger than YOUR territory?

[[v30-6-3]]

^<<v30-6-3,3>>^ &#91;Are YOU&#93; putting out of &#91;YOUR&#93; mind the calamitous day, and do YOU bring near the dwelling of violence?

[[v30-6-4]]

^<<v30-6-4,4>>^ &#91;YOU men&#93; that are lying down on couches of ivory and are sprawling on their divans, and are eating the rams out of a flock and the young bulls from among fattened calves;

[[v30-6-5]]

^<<v30-6-5,5>>^ that are improvising according to the sound^&#42;1^ of the stringed instrument; that, like David, have devised for themselves instruments for song;

[NOTE]
====
. Lit., “mouth.”
====

[[v30-6-6]]

^<<v30-6-6,6>>^ that are drinking out of bowls of wine, and that with the choicest oils do their anointing, and that have not been made sick at the catastrophe of Joseph.

[[v30-6-7]]

^<<v30-6-7,7>>^ “Therefore now they will go into exile at the head of those going into exile, and the revelry of sprawling ones must depart.

[[v30-6-8]]

^<<v30-6-8,8>>^ “‘The Sovereign Lord Jehovah has sworn by his own soul,’ is the utterance of Jehovah the God of armies, ‘“I am detesting the pride of Jacob, and his dwelling towers I have hated, and I will deliver up &#91;the&#93; city and what fills it.

[[v30-6-9]]

^<<v30-6-9,9>>^ And it must occur that if ten men^&#42;1^ should be left remaining in one house, they must also die.

[NOTE]
====
. “Men.” Heb., ʼana·shimʹ, pl. of ʼish.
====

[[v30-6-10]]

^<<v30-6-10,10>>^ And his father’s brother will have to carry them forth one by one, and will be burning them one by one, in order to bring out &#91;the&#93; bones from the house. And he will have to say to whoever is in the innermost parts of the house, ‘Are there any more with you?’ And he will certainly say, ‘Nobody!’ And he will have to say, ‘Keep silence! For it is not the occasion for making any mention of the name of Jehovah.’”

[[v30-6-11]]

^<<v30-6-11,11>>^ “‘For here is Jehovah commanding, and he will certainly strike down the great house into rubble and the small house into debris.

[[v30-6-12]]

^<<v30-6-12,12>>^ “‘On a crag will horses run, or will one plow &#91;there&#93; with cattle? For into a poisonous plant YOU people have turned justice, and the fruitage of righteousness into wormwood,

[[v30-6-13]]

^<<v30-6-13,13>>^ &#91;YOU who&#93; are rejoicing in a thing that is not; who are saying: “Have we not in our strength taken horns to ourselves?”

[[v30-6-14]]

^<<v30-6-14,14>>^ Look! I am raising up against YOU, O house of Israel,’ is the utterance of Jehovah the God of the armies, ‘a nation, and they must oppress YOU people from the entering in of Haʹmath^&#42;1^ down to the torrent valley of the Arʹa·bah.’”^&#42;2^

[NOTE]
====
. Possibly, “from Lebi-hamath (Lion of Hamath).” See Jos 13:5 ftn, “Hamath.”
. Or, “the desert plain.” See De 1:1 ftn, “Plains.”
====

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]