include::./index.adoc[]

[[v30-9-0]]
=== Amos, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v30-9-1]]

^<<v30-9-1,1>>^ I saw Jehovah^&#42;1^ stationed above the altar, and he proceeded to say: “Strike the pillar head, so that the thresholds will rock. And cut them off at the head, all of them. And the last part of them I shall kill with the sword itself. No one fleeing of them will make good his flight, and no one escaping of them will make his getaway.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v30-9-2]]

^<<v30-9-2,2>>^ If they dig down into Sheʹol,^&#42;1^ from there my own hand will take them; and if they go up to the heavens, from there I shall bring them down.

[NOTE]
====
. “Into Sheol.” Heb., vish·ʼohlʹ; Gr., haiʹdou; Lat., in·ferʹnum. See App 4B.
====

[[v30-9-3]]

^<<v30-9-3,3>>^ And if they hide themselves on the top of Carʹmel, from there I shall carefully search and be certain to take them. And if they conceal themselves from in front of my eyes on the floor of the sea, down there I shall command the serpent, and it must bite them.

[[v30-9-4]]

^<<v30-9-4,4>>^ And if they go into captivity before their enemies, from there I shall command the sword, and it must kill them; and I will set my eyes upon them for bad, and not for good.

[[v30-9-5]]

^<<v30-9-5,5>>^ And the Sovereign Lord, Jehovah of the armies,^&#42;1^ is the One touching the land,^&#42;2^ so that it melts; and all the inhabitants in it will have to mourn; and it will certainly come up like the Nile, all of it, and sink down like the Nile of Egypt.

[NOTE]
====
. “Of the armies,” MTVg; LXX, “God the Almighty”; Sy, “the Mighty One.”
. Lit., “on the earth.” Heb., ba·ʼaʹrets.
====

[[v30-9-6]]

^<<v30-9-6,6>>^ “‘He who is building in the heavens his stairs, and his structure over the earth that he founded; he who is calling for the waters of the sea, that he may pour them out upon the surface of the earth—Jehovah is his name.’

[[v30-9-7]]

^<<v30-9-7,7>>^ “‘Are YOU not like the sons of the Cushʹites^&#42;1^ to me, O sons of Israel?’ is the utterance of Jehovah. ‘Did I not bring Israel itself up out of the land of Egypt, and the Phi·lisʹtines out of Crete,^&#42;2^ and Syria^&#42;3^ out of Kir?’^&#42;4^

[NOTE]
====
. “The Cushites,” MSy; LXXVg, “the Ethiopians.”
. “Out of Crete.” Heb., mik·Kaph·tohrʹ; TLXXSyVg, “Cappadocia.” See De 2:23.
. Lit., “Aram,” MTSy; LXXVg, “the Syrians.”
. “Kir,” MSy; TVg, “Cyrene.”
====

[[v30-9-8]]

^<<v30-9-8,8>>^ “‘Look! The eyes of the Sovereign Lord Jehovah are upon the sinful kingdom, and he will certainly annihilate it from upon the surface of the ground. Nevertheless, I shall not completely annihilate the house of Jacob,’ is the utterance of Jehovah.

[[v30-9-9]]

^<<v30-9-9,9>>^ ‘For, look! I am commanding, and I will jiggle the house of Israel among all the nations, just as one jiggles the sieve, so that not a pebble falls to the earth.

[[v30-9-10]]

^<<v30-9-10,10>>^ By the sword they will die—all the sinners of my people, those who are saying: “The calamity will not come near or reach as far as us.”’

[[v30-9-11]]

^<<v30-9-11,11>>^ “‘In that day I shall raise up the booth^&#42;1^ of David that is fallen, and I shall certainly repair their breaches. And its ruins I shall raise up, and I shall certainly build it up as in the days of long ago,

[NOTE]
====
. “The booth of.” Heb., suk·kathʹ; Gr., ske·nenʹ (“tent”; “booth,” in Ac 15:16); Lat., ta·ber·naʹcu·lum.
====

[[v30-9-12]]

^<<v30-9-12,12>>^ to the end that they may take possession of what is left remaining of Eʹdom, and all the nations^&#42;1^ upon whom my name has been called,’ is the utterance of Jehovah, who is doing this.^&#42;2^

[NOTE]
====
. According to MTSyVg; LXX, “that the rest of the men may seek out, and all the nations.”
. According to MSyVg; LXX, “says Jehovah God, who is doing these things.”
====

[[v30-9-13]]

^<<v30-9-13,13>>^ “‘Look! There are days coming,’ is the utterance of Jehovah, ‘and the plowman will actually overtake^&#42;1^ the harvester, and the treader of grapes, the carrier^&#42;2^ of the seed; and the mountains must drip with sweet wine, and the very hills will all find themselves melting.

[NOTE]
====
. Or, “approach.”
. Or, “drawer out,” that is, from the seed bag.
====

[[v30-9-14]]

^<<v30-9-14,14>>^ And I will gather back the captive ones of my people Israel, and they will actually build &#91;the&#93; desolated cities and inhabit &#91;them&#93;, and plant vineyards and drink the wine of them, and make gardens and eat the fruit of them.’

[[v30-9-15]]

^<<v30-9-15,15>>^ “‘And I shall certainly plant them upon their ground, and they will no more be uprooted from their ground that I have given them,’ Jehovah your God^&#42;1^ has said.”

[NOTE]
====
. “Your God,” MTSyVg; LXX, “God the Almighty.”
====

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadiah/031-obadiah-001.adoc#v31-1-0[Próximo Capítulo &#62;]