include::./index.adoc[]

[[v12-4-0]]
=== The Second of Kings, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-4-1]]

^<<v12-4-1,1>>^ Now there was a certain woman of the wives of the sons of the prophets that cried out to E·liʹsha, saying: “Your servant, my husband, is dead; and you yourself well know that your own servant had continually feared Jehovah, and the creditor himself has come to take both my children for his slaves.”

[[v12-4-2]]

^<<v12-4-2,2>>^ At this E·liʹsha said to her: “What shall I do for you? Tell me; what do you have in the house?” To this she said: “Your maidservant has nothing at all in the house but a spouted jar of oil.”

[[v12-4-3]]

^<<v12-4-3,3>>^ Then he said: “Go, ask for vessels for yourself from outside, from all your neighbors, empty vessels. Do not hold yourself to a few.

[[v12-4-4]]

^<<v12-4-4,4>>^ And you must go and close the door behind yourself and your sons, and you must pour out into all these vessels, and the full ones you should set aside.”

[[v12-4-5]]

^<<v12-4-5,5>>^ Upon that she went away from him.
When she closed the door behind herself and her sons, they were bringing &#91;the vessels&#93;^&#42;1^ near to her, and she was doing the pouring out.

[NOTE]
====
. Lit., “them.”
====

[[v12-4-6]]

^<<v12-4-6,6>>^ And it came about that as soon as the vessels were full she went on to say to her son: “Do bring still another vessel near to me.” But he said to her: “There is no other vessel.” At that the oil stopped.

[[v12-4-7]]

^<<v12-4-7,7>>^ So she came in and told the man of the &#91;true&#93; God, and he now said: “Go, sell the oil and pay off your debts, and you &#91;and&#93; your sons should live from what is left.”

[[v12-4-8]]

^<<v12-4-8,8>>^ And it came about one day that E·liʹsha went passing along to Shuʹnem, where there was a prominent woman, and she began to constrain him to eat bread. And it came about that as often as he would pass by, he would turn aside there to eat bread.

[[v12-4-9]]

^<<v12-4-9,9>>^ At length she said to her husband: “Here, now, I well know that it is a holy man of God that is passing by us constantly.

[[v12-4-10]]

^<<v12-4-10,10>>^ Please, let us make a little roof chamber on the wall and put there for him a couch and a table and a chair and a lampstand; and it must occur that whenever he comes in to us he can turn aside there.”

[[v12-4-11]]

^<<v12-4-11,11>>^ And it came about one day that as usual he came in there and turned aside to the roof chamber and lay down there.

[[v12-4-12]]

^<<v12-4-12,12>>^ So he said to Ge·haʹzi his attendant: “Call this Shuʹnam·mite woman.” At that he called her that she might stand before him.

[[v12-4-13]]

^<<v12-4-13,13>>^ Then he said to him: “Please, say to her, ‘Here you have restricted yourself for us with all this restriction. What is there to be done for you? Is there anything to speak to the king or to the chief of the army for you?’” To this she said: “In among my own people I am dwelling.”

[[v12-4-14]]

^<<v12-4-14,14>>^ And he went on to say: “What, then, is there to be done for her?” Ge·haʹzi now said: “For a fact, a son she does not have, and her husband is old.”

[[v12-4-15]]

^<<v12-4-15,15>>^ Immediately he said: “Call her.” So he called her, and she kept standing at the entrance.

[[v12-4-16]]

^<<v12-4-16,16>>^ Then he said: “At this appointed time next year^&#42;1^ you will be embracing a son.” But she said: “No, my master, O man of the &#91;true&#93; God! Do not tell lies in connection with your maidservant.”

[NOTE]
====
. “At this appointed time next year.” Compare Ge 18:10 ftn.
====

[[v12-4-17]]

^<<v12-4-17,17>>^ However, the woman became pregnant and gave birth to a son at this appointed time the next year, just as E·liʹsha had spoken to her.

[[v12-4-18]]

^<<v12-4-18,18>>^ And the child kept on growing up, and it came about one day that he went out as usual to his father with the reapers.

[[v12-4-19]]

^<<v12-4-19,19>>^ And he kept saying to his father: “My head, O my head!” At last he said to the attendant: “Carry him to his mother.”

[[v12-4-20]]

^<<v12-4-20,20>>^ Accordingly he carried him and brought him to his mother. And he kept sitting upon her knees until noon, and gradually he died.

[[v12-4-21]]

^<<v12-4-21,21>>^ Then she went up and laid him upon the couch of the man of the &#91;true&#93; God and closed the door upon him and went out.

[[v12-4-22]]

^<<v12-4-22,22>>^ She now called her husband and said: “Do send me, please, one of the attendants and one of the she-asses, and let me run as far as the man of the &#91;true&#93; God and return.”

[[v12-4-23]]

^<<v12-4-23,23>>^ But he said: “Why are you going to him today? It is not a new moon nor a sabbath.” However, she said: “It is all right.”

[[v12-4-24]]

^<<v12-4-24,24>>^ So she saddled up the she-ass and said to her attendant: “Drive and go ahead. Do not hold back for my sake from riding unless I shall have said so to you.”

[[v12-4-25]]

^<<v12-4-25,25>>^ And she proceeded to go and come to the man of the &#91;true&#93; God at Mount Carʹmel. And it came about that, as soon as the man of the &#91;true&#93; God saw her out ahead, he immediately said to Ge·haʹzi his attendant: “Look! The Shuʹnam·mite woman over there.

[[v12-4-26]]

^<<v12-4-26,26>>^ Now run, please, to meet her and say to her, ‘Is it all right with you? Is it all right with your husband? Is it all right with the child?’” To this she said: “It is all right.”

[[v12-4-27]]

^<<v12-4-27,27>>^ When she came to the man of the &#91;true&#93; God at the mountain, she at once took hold of him by his feet. At this Ge·haʹzi came near to push her away, but the man of the &#91;true&#93; God said: “Let her alone, for her soul is bitter within her; and Jehovah himself has hidden it from me and not told me.”

[[v12-4-28]]

^<<v12-4-28,28>>^ She now said: “Did I ask for a son through my lord? Did I not say, ‘You must not lead me to a false hope’?”

[[v12-4-29]]

^<<v12-4-29,29>>^ Immediately he said to Ge·haʹzi: “Gird up your loins and take my staff in your hand and go. In case you encounter anyone, you must not greet him; and in case anyone should greet you, you must not answer him. And you must place my staff upon the face of the boy.”

[[v12-4-30]]

^<<v12-4-30,30>>^ At this the mother of the boy said: “As Jehovah is living and as your soul is living, I will not leave you.” Therefore he got up and went with her.^&#42;1^

[NOTE]
====
. Or, “after her.” Instead of saying “together with her,” the Hebrews said, “behind her; after her.”
====

[[v12-4-31]]

^<<v12-4-31,31>>^ And Ge·haʹzi himself passed along before them and then put the staff upon the boy’s face, but there was no voice nor paying of attention. So he went back to meet him and told him, saying: “The boy did not wake up.”

[[v12-4-32]]

^<<v12-4-32,32>>^ At last E·liʹsha came into the house, and there the boy was dead, being laid upon his couch.

[[v12-4-33]]

^<<v12-4-33,33>>^ Then he came in and closed the door behind them both and began to pray to Jehovah.

[[v12-4-34]]

^<<v12-4-34,34>>^ Finally he went up and lay down upon the child and put his own mouth upon his mouth and his own eyes upon his eyes and his own palms upon his palms and kept bent over him, and gradually the child’s flesh grew warm.

[[v12-4-35]]

^<<v12-4-35,35>>^ Then he began walking again in the house, once this way and once that way, after which he went up and bent over him. And the boy began to sneeze^&#42;1^ as many as seven times, after which the boy opened his eyes.

[NOTE]
====
. Or, “wink.”
====

[[v12-4-36]]

^<<v12-4-36,36>>^ He now called Ge·haʹzi and said: “Call this Shuʹnam·mite woman.” So he called her and she came in to him. Then he said: “Lift up your son.”

[[v12-4-37]]

^<<v12-4-37,37>>^ And she proceeded to come in and fall at his feet and bow down to him to the earth, after which she lifted up her son and went out.

[[v12-4-38]]

^<<v12-4-38,38>>^ And E·liʹsha himself returned to Gilʹgal,^&#42;1^ and there was famine in the land. As the sons of the prophets were sitting before him, he in time said to his attendant: “Put the large cooking pot on and boil stew for the sons of the prophets.”

[NOTE]
====
. See 2:1 ftn, “Gilgal.”
====

[[v12-4-39]]

^<<v12-4-39,39>>^ Accordingly a certain one went out to the field to pick mallows, and he got to find a wild vine and went picking wild gourds from it, his garment full, and then came and sliced them into the stewpot, for they were not acquainted with them.

[[v12-4-40]]

^<<v12-4-40,40>>^ Later they poured it out for the men to eat. And it came about that, as soon as they ate from the stew, they themselves cried out and began saying: “There is death in the pot, O man of the &#91;true&#93; God.” And they were not able to eat.

[[v12-4-41]]

^<<v12-4-41,41>>^ So he said: “FETCH, then, flour.” After he threw it into the pot, he went on to say: “Pour out for the people that they may eat.” And nothing injurious proved to be in the pot.

[[v12-4-42]]

^<<v12-4-42,42>>^ And there was a man that came from Baʹal-shalʹi·shah, and he came bringing to the man of the &#91;true&#93; God bread of the first ripe fruits, twenty barley loaves, and new grain in his bread bag. Then he said: “Give it to the people that they may eat.”

[[v12-4-43]]

^<<v12-4-43,43>>^ However, his waiter said: “How shall I put this before a hundred men?” To this he said: “Give it to the people that they may eat, for this is what Jehovah has said, ‘There will be an eating and a having of leftovers.’”^&#42;1^

[NOTE]
====
. “There will be an eating and a having of leftovers.” In Heb. these are verbs in the infinitive absolute, indefinite as to time and impersonal.
====

[[v12-4-44]]

^<<v12-4-44,44>>^ At that he put it before them, and they began to eat, and they had leftovers according to the word of Jehovah.

'''

xref:012-2-kings/012-2-kings-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-kings/012-2-kings-005.adoc#v12-5-0[Próximo Capítulo &#62;]