include::./index.adoc[]

[[v12-15-0]]
=== The Second of Kings, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-15-1]]

^<<v12-15-1,1>>^ In the twenty-seventh year of Jer·o·boʹam the king of Israel, Az·a·riʹah the son of Am·a·ziʹah the king of Judah became king.

[[v12-15-2]]

^<<v12-15-2,2>>^ Sixteen years old he happened to be when he began to reign, and for fifty-two years he reigned in Jerusalem. And his mother’s name was Je·co·liʹah^&#42;1^ of Jerusalem.

[NOTE]
====
. Meaning “Jehovah Has Been Able.” Heb., Yekhol·yaʹhu.
====

[[v12-15-3]]

^<<v12-15-3,3>>^ And he continued to do what was upright in Jehovah’s eyes, according to all that Am·a·ziʹah his father had done.

[[v12-15-4]]

^<<v12-15-4,4>>^ It was only that the high places did not disappear. The people were still sacrificing and making sacrificial smoke on the high places.

[[v12-15-5]]

^<<v12-15-5,5>>^ Finally Jehovah plagued the king, and he continued to be a leper until the day of his death, and he kept dwelling in his house exempt from duties, while Joʹtham the king’s son was over the house, judging the people of the land.^&#42;1^

[NOTE]
====
. “The people of the land.” Heb., ʽam ha·ʼaʹrets. See Ge 23:7 ftn.
====

[[v12-15-6]]

^<<v12-15-6,6>>^ As for the rest of the affairs of Az·a·riʹah^&#42;1^ and all that he did, are they not written in the book of the affairs of the days of the kings of Judah?

[NOTE]
====
. Meaning “Jehovah Has Helped.” Heb., ʽAzar·yaʹhu. In vs 13; 2Ch 26:1-23; Isa 6:1; Zec 14:5, “Uzziah.”
====

[[v12-15-7]]

^<<v12-15-7,7>>^ At length Az·a·riʹah lay down with his forefathers, and they buried him with his forefathers in the City of David; and Joʹtham his son began to reign in place of him.

[[v12-15-8]]

^<<v12-15-8,8>>^ In the thirty-eighth year of Az·a·riʹah the king of Judah, Zech·a·riʹah^&#42;1^ the son of Jer·o·boʹam became king over Israel in Sa·marʹi·a for six months.

[NOTE]
====
. Meaning “Jehovah Has Remembered.” Heb., Zekhar·yaʹhu.
====

[[v12-15-9]]

^<<v12-15-9,9>>^ And he went on doing what was bad in Jehovah’s eyes, just as his forefathers had done. He did not depart from the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin.

[[v12-15-10]]

^<<v12-15-10,10>>^ Then Shalʹlum the son of Jaʹbesh conspired against him and struck him down at Ibʹle·am^&#42;1^ and put him to death and began to reign in place of him.

[NOTE]
====
. “At Ibleam,” LXXL; M, “before the people”; Vg, “publicly.”
====

[[v12-15-11]]

^<<v12-15-11,11>>^ As for the rest of the affairs of Zech·a·riʹah, there they are written in the book of the affairs of the days of the kings of Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ That was Jehovah’s word that he had spoken to Jeʹhu, saying: “Sons themselves to the fourth generation will sit for you upon the throne of Israel.” And it came to be that way.

[[v12-15-13]]

^<<v12-15-13,13>>^ As for Shalʹlum the son of Jaʹbesh, he became king in the thirty-ninth year of Uz·ziʹah^&#42;1^ the king of Judah, and he continued to reign for a full lunar month^&#42;2^ in Sa·marʹi·a.

[NOTE]
====
. “Of Uzziah.” Heb., leʽU·zi·yahʹ, meaning “My Strength Is Jah”; in vs 1, “Azariah.” See vs 6 ftn.
. Lit., “a lunar month of days.”
====

[[v12-15-14]]

^<<v12-15-14,14>>^ Then Menʹa·hem the son of Gaʹdi came up from Tirʹzah and came to Sa·marʹi·a and struck down Shalʹlum the son of Jaʹbesh in Sa·marʹi·a and put him to death; and he began to reign in place of him.

[[v12-15-15]]

^<<v12-15-15,15>>^ As for the rest of the affairs of Shalʹlum and his conspiracy with which he conspired, there they are written in the book of the affairs of the days of the kings of Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ It was then that Menʹa·hem proceeded to strike down Tiphʹsah and all that was in it and its territory out from Tirʹzah, because it did not open up,^&#42;1^ and he went striking it down. All its pregnant women he ripped up.

[NOTE]
====
. “Because they did not open up (the gate) to him,” LXXSyVg.
====

[[v12-15-17]]

^<<v12-15-17,17>>^ In the thirty-ninth year of Az·a·riʹah^&#42;1^ the king of Judah, Menʹa·hem the son of Gaʹdi became king over Israel for ten years in Sa·marʹi·a.

[NOTE]
====
. “Of Azariah.” Heb., la·ʽAzar·yahʹ; in vs 13, “Uzziah.” See vs 6 ftn.
====

[[v12-15-18]]

^<<v12-15-18,18>>^ And he continued to do what was bad in Jehovah’s eyes. He did not depart from all the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin, all his days.

[[v12-15-19]]

^<<v12-15-19,19>>^ Pul the king of As·syrʹi·a came into the land. Consequently Menʹa·hem gave Pul a thousand talents of silver, that his hands might prove to be with him to strengthen the kingdom in his own hand.

[[v12-15-20]]

^<<v12-15-20,20>>^ So Menʹa·hem brought forth the silver at the expense of Israel, at the expense of all the valiant, mighty men, to give to the king of As·syrʹi·a fifty silver shekels^&#42;1^ for each man. At that the king of As·syrʹi·a turned back, and he did not stay there in the land.

[NOTE]
====
. See App 8A.
====

[[v12-15-21]]

^<<v12-15-21,21>>^ As for the rest of the affairs of Menʹa·hem and all that he did, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-15-22]]

^<<v12-15-22,22>>^ Finally Menʹa·hem lay down with his forefathers, and Pek·a·hiʹah his son began to reign in place of him.

[[v12-15-23]]

^<<v12-15-23,23>>^ In the fiftieth year of Az·a·riʹah the king of Judah, Pek·a·hiʹah the son of Menʹa·hem became king over Israel in Sa·marʹi·a for two years.

[[v12-15-24]]

^<<v12-15-24,24>>^ And he continued to do what was bad in Jehovah’s eyes. He did not depart from the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin.

[[v12-15-25]]

^<<v12-15-25,25>>^ Then Peʹkah the son of Rem·a·liʹah^&#42;1^ his adjutant conspired against him and struck him down in Sa·marʹi·a in the dwelling tower of the king’s house with Arʹgob and A·riʹeh, and with him there were fifty men of the sons of Gilʹe·ad.^&#42;2^ So he put him to death and began to reign in place of him.

[NOTE]
====
. Meaning “Jehovah Has Adorned.” Heb., Remal·yaʹhu.
. Lit., “sons of Gileadites.”
====

[[v12-15-26]]

^<<v12-15-26,26>>^ As for the rest of the affairs of Pek·a·hiʹah and all that he did, there they are written in the book of the affairs of the days of the kings of Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ In the fifty-second year of Az·a·riʹah the king of Judah, Peʹkah the son of Rem·a·liʹah became king over Israel in Sa·marʹi·a for twenty years.

[[v12-15-28]]

^<<v12-15-28,28>>^ And he continued to do what was bad in Jehovah’s eyes. He did not depart from the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin.

[[v12-15-29]]

^<<v12-15-29,29>>^ In the days of Peʹkah the king of Israel, Tigʹlath-pil·eʹser the king of As·syrʹi·a came in and proceeded to take Iʹjon and Aʹbel-beth-maʹa·cah and Ja·noʹah and Keʹdesh and Haʹzor and Gilʹe·ad and Galʹi·lee,^&#42;1^ all the land of Naphʹta·li, and to carry them into exile in As·syrʹi·a.

[NOTE]
====
. Lit., “[the] Galilee.” Heb., hag·Ga·liʹlah; Gr., Ga·li·laiʹan; Lat., Ga·li·leʹam. See Jos 20:7 ftn, “Galilee.”
====

[[v12-15-30]]

^<<v12-15-30,30>>^ Finally Ho·sheʹa the son of Eʹlah formed a conspiracy against Peʹkah the son of Rem·a·liʹah and struck him and put him to death; and he began to reign in place of him in the twentieth year of Joʹtham the son of Uz·ziʹah.^&#42;1^

[NOTE]
====
. “Azariah” in vs 1.
====

[[v12-15-31]]

^<<v12-15-31,31>>^ As for the rest of the affairs of Peʹkah and all that he did, there they are written in the book of the affairs of the days of the kings of Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ In the second year of Peʹkah the son of Rem·a·liʹah the king of Israel, Joʹtham the son of Uz·ziʹah the king of Judah became king.

[[v12-15-33]]

^<<v12-15-33,33>>^ Twenty-five years old he happened to be when he began to reign, and for sixteen years he reigned in Jerusalem. And his mother’s name was Je·ruʹsha the daughter of Zaʹdok.

[[v12-15-34]]

^<<v12-15-34,34>>^ And he continued to do what was right in Jehovah’s eyes. According to all that Uz·ziʹah his father had done, he did.

[[v12-15-35]]

^<<v12-15-35,35>>^ It was only that the high places did not disappear. The people were still sacrificing and making sacrificial smoke on the high places. He it was that built the upper gate of the house of Jehovah.

[[v12-15-36]]

^<<v12-15-36,36>>^ As for the rest of the affairs of Joʹtham, what he did, are they not written in the book of the affairs of the days of the kings of Judah?

[[v12-15-37]]

^<<v12-15-37,37>>^ In those days Jehovah started to send against Judah Reʹzin the king of Syria and Peʹkah the son of Rem·a·liʹah.

[[v12-15-38]]

^<<v12-15-38,38>>^ Finally Joʹtham lay down with his forefathers and was buried with his forefathers in the City of David his forefather; and Aʹhaz his son began to reign in place of him.

'''

xref:012-2-kings/012-2-kings-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-kings/012-2-kings-016.adoc#v12-16-0[Próximo Capítulo &#62;]