include::./index.adoc[]

[[v12-11-0]]
=== The Second of Kings, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-11-1]]

^<<v12-11-1,1>>^ Now as regards Ath·a·liʹah the mother of A·ha·ziʹah, she saw that her son had died. So she rose up and destroyed all the offspring of the kingdom.

[[v12-11-2]]

^<<v12-11-2,2>>^ However, Je·hoshʹe·ba the daughter of King Je·hoʹram, the sister of A·ha·ziʹah, took Je·hoʹash^&#42;1^ the son of A·ha·ziʹah and stole him from among the sons of the king that were to be put to death, even him and his nursing woman, into the inner room for the couches, and they^&#42;2^ kept him concealed from the face of Ath·a·liʹah, and he was not put to death.

[NOTE]
====
. Lit., “Joash.” Compare vs 21 ftn.
. “They,” M; LXXSyVg, “she.”
====

[[v12-11-3]]

^<<v12-11-3,3>>^ And he continued with her at the house of Jehovah in hiding for six years, while Ath·a·liʹah was reigning over the land.

[[v12-11-4]]

^<<v12-11-4,4>>^ And in the seventh year Je·hoiʹa·da sent and then took the chiefs of hundreds of the Caʹri·an bodyguard and of the runners and brought them to himself at the house of Jehovah and concluded a covenant with them and made them swear at the house of Jehovah, after which he showed them the son of the king.

[[v12-11-5]]

^<<v12-11-5,5>>^ And he went on to command them, saying: “This is the thing that YOU will do: One third of YOU are coming in on the sabbath and keeping strict watch over the king’s house;

[[v12-11-6]]

^<<v12-11-6,6>>^ and one third will be at the Gate of the Foundation,^&#42;1^ and one third will be at the gate behind the runners; and YOU must keep strict watch over the house by turns.

[NOTE]
====
. “Foundation,” in harmony with 2Ch 23:5. Lit., “Sur.”
====

[[v12-11-7]]

^<<v12-11-7,7>>^ And there are two divisions among YOU that are all going out on the sabbath, and they must keep strict watch over the house of Jehovah in behalf of the king.

[[v12-11-8]]

^<<v12-11-8,8>>^ And YOU must encircle the king all around, each one with his weapons in his hand; and anyone entering within the rows will be put to death. And continue with the king when he goes out and when he comes in.”

[[v12-11-9]]

^<<v12-11-9,9>>^ And the chiefs of hundreds proceeded to do according to all that Je·hoiʹa·da the priest had commanded. So they took each one his men that were coming in on the sabbath, together with those that were going out on the sabbath, and then came in to Je·hoiʹa·da the priest.

[[v12-11-10]]

^<<v12-11-10,10>>^ The priest now gave the chiefs of hundreds the spears and the circular shields that had belonged to King David, which were in the house of Jehovah.

[[v12-11-11]]

^<<v12-11-11,11>>^ And the runners kept standing each one with his weapons in his hand, from the right side^&#42;1^ of the house clear to the left side^&#42;2^ of the house, by the altar and by the house, all around near the king.

[NOTE]
====
. Lit., “the right shoulder,” that is, the south side, when one faces east.
. Lit., “the left shoulder,” that is, the north side, when one faces east.
====

[[v12-11-12]]

^<<v12-11-12,12>>^ Then he brought the son of the king out and put upon him the diadem and the Testimony; and so they made^&#42;1^ him king and anointed^&#42;2^ him. And they began to clap their hands and say: “Let the king live!”

[NOTE]
====
. “And so they made,” MSyVg; LXX, “and he made.”
. “And (they) anointed,” MSyVg; LXX, “and he anointed.”
====

[[v12-11-13]]

^<<v12-11-13,13>>^ When Ath·a·liʹah heard the sound of the people running, she at once came to the people at the house of Jehovah.

[[v12-11-14]]

^<<v12-11-14,14>>^ Then she saw, and there the king was standing by the pillar according to the custom, and the chiefs and the trumpets^&#42;1^ by the king, and all the people of the land rejoicing and blowing the trumpets. Immediately Ath·a·liʹah ripped her garments apart and began crying: “Conspiracy! Conspiracy!”

[NOTE]
====
. Or, “and the straight trumpets.” Heb., weha·chatso·tserohthʹ; not the shohpharʹ, “shofar,” which was an animal’s curved horn. See Nu 10:2 ftn.
====

[[v12-11-15]]

^<<v12-11-15,15>>^ But Je·hoiʹa·da the priest commanded the chiefs of hundreds, the appointed ones of the military force, and said to them: “Take her out from inside the rows, and, as for anyone coming after her, let there be an execution of death^&#42;1^ with the sword!” For the priest had said: “Do not let her be put to death in the house of Jehovah.”

[NOTE]
====
. “Let there be an execution of death.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v12-11-16]]

^<<v12-11-16,16>>^ So they laid their hands upon her and she came by the way of the horse entry of the king’s house, and she got put to death there.

[[v12-11-17]]

^<<v12-11-17,17>>^ Then Je·hoiʹa·da concluded the covenant between Jehovah and the king and the people, that they should prove themselves the people of Jehovah; and also between the king and the people.

[[v12-11-18]]

^<<v12-11-18,18>>^ After that all the people of the land came to the house of Baʹal and pulled down his altars; and his images they broke up thoroughly, and Matʹtan the priest of Baʹal they killed before the altars.
And the priest proceeded to put overseers^&#42;1^ over the house of Jehovah.

[NOTE]
====
. Lit., “oversights; charges.” Heb., pequd·dohthʹ. The Heb. abstract noun for “oversights” is translated by the concrete designation “overseers.”
====

[[v12-11-19]]

^<<v12-11-19,19>>^ Further, he took the chiefs of hundreds and the Caʹri·an bodyguard and the runners and all the people of the land, that they might bring the king down from the house of Jehovah; and they came gradually by the way of the gate of the runners to the king’s house; and he began to sit upon the throne of the kings.

[[v12-11-20]]

^<<v12-11-20,20>>^ And all the people of the land continued to rejoice; and the city, for its part, had no disturbance, and Ath·a·liʹah herself they had put to death with the sword at the king’s house.^&#42;1^

[NOTE]
====
. MLXX end chapter 11 here.
====

[[v12-11-21]]

^<<v12-11-21,21>>^ Seven years old Je·hoʹash^&#42;1^ was when he began to reign.

[NOTE]
====
. Meaning “Jehovah Is Strong; Jehovah Has Bestowed.” Heb., Yehoh·ʼashʹ.
====

'''

xref:012-2-kings/012-2-kings-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-kings/012-2-kings-012.adoc#v12-12-0[Próximo Capítulo &#62;]