include::./index.adoc[]

[[v12-14-0]]
=== The Second of Kings, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-14-1]]

^<<v12-14-1,1>>^ In the second year of Je·hoʹash the son of Je·hoʹa·haz^&#42;1^ the king of Israel, Am·a·ziʹah^&#42;2^ the son of Je·hoʹash the king of Judah became king.

[NOTE]
====
. “Jehoahaz.” Heb., Yoh·ʼa·chazʹ.
. Meaning “Jehovah Is Mighty.” Heb., ʼAmats·yaʹhu.
====

[[v12-14-2]]

^<<v12-14-2,2>>^ Twenty-five years old he happened to be when he began to reign, and for twenty-nine years he reigned in Jerusalem. And his mother’s name was Je·ho·adʹdin of Jerusalem.

[[v12-14-3]]

^<<v12-14-3,3>>^ And he continued to do what was upright in Jehovah’s eyes, only not like David his forefather. According to all that Je·hoʹash his father had done, he did.

[[v12-14-4]]

^<<v12-14-4,4>>^ It was only the high places that did not disappear. The people were still sacrificing and making sacrificial smoke on the high places.

[[v12-14-5]]

^<<v12-14-5,5>>^ And it came about that as soon as the kingdom had become firm in his hand, he began to strike down his servants that had struck down the king his father.

[[v12-14-6]]

^<<v12-14-6,6>>^ And the sons of the strikers he did not put to death, according to what is written in the book of Moses’ law that Jehovah gave in command, saying: “Fathers should not be put to death for sons, and sons themselves should not be put to death for fathers; but for his own sin should each one be put to death.”

[[v12-14-7]]

^<<v12-14-7,7>>^ He himself struck down the Eʹdom·ites in the Valley of Salt, ten thousand men, and got to seize Seʹla in the war, and its name came to be called Jokʹthe·el down to this day.

[[v12-14-8]]

^<<v12-14-8,8>>^ Then it was that Am·a·ziʹah sent messengers to Je·hoʹash the son of Je·hoʹa·haz the son of Jeʹhu the king of Israel, saying: “Do come. Let us look each other in the face.”

[[v12-14-9]]

^<<v12-14-9,9>>^ At that Je·hoʹash the king of Israel sent to Am·a·ziʹah the king of Judah, saying: “The thorny weed itself that was in Lebʹa·non sent to the cedar that was in Lebʹa·non, saying, ‘Do give your daughter to my son as a wife.’ However, a wild beast of the field that was in Lebʹa·non passed by and trampled the thorny weed down.

[[v12-14-10]]

^<<v12-14-10,10>>^ You have unmistakably struck down Eʹdom, and your heart has lifted you up. Enjoy your honor and dwell in your own house. Why, then, should you engage in strife under unfavorable conditions and have to fall, you and Judah with you?”

[[v12-14-11]]

^<<v12-14-11,11>>^ And Am·a·ziʹah did not listen.
So Je·hoʹash the king of Israel came up, and they proceeded to look each other in the face, he and Am·a·ziʹah the king of Judah, at Beth-sheʹmesh, which belongs to Judah.

[[v12-14-12]]

^<<v12-14-12,12>>^ And Judah came to be defeated before Israel, so that they took to flight, each one to his tent.

[[v12-14-13]]

^<<v12-14-13,13>>^ And it was Am·a·ziʹah the king of Judah the son of Je·hoʹash the son of A·ha·ziʹah that Je·hoʹash the king of Israel captured at Beth-sheʹmesh, after which they came to Jerusalem and he made a breach in the wall of Jerusalem at the Gate of Eʹphra·im clear to the Corner Gate, four hundred cubits.^&#42;1^

[NOTE]
====
. About 178 m (584 ft).
====

[[v12-14-14]]

^<<v12-14-14,14>>^ And he took all the gold and silver and all the articles to be found at the house of Jehovah and in the treasures of the house of the king and the hostages^&#42;1^ and then returned to Sa·marʹi·a.

[NOTE]
====
. Lit., “and the sons of the pledges.”
====

[[v12-14-15]]

^<<v12-14-15,15>>^ As for the rest of the affairs of Je·hoʹash, what he did and his mightiness and how he fought against Am·a·ziʹah the king of Judah, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ Finally Je·hoʹash lay down with his forefathers and was buried in Sa·marʹi·a with the kings of Israel, and Jer·o·boʹam^&#42;1^ his son began to reign in place of him.

[NOTE]
====
. That is, Jeroboam II.
====

[[v12-14-17]]

^<<v12-14-17,17>>^ And Am·a·ziʹah the son of Je·hoʹash the king of Judah continued to live after the death of Je·hoʹash the son of Je·hoʹa·haz the king of Israel for fifteen years.

[[v12-14-18]]

^<<v12-14-18,18>>^ As for the rest of the affairs of Am·a·ziʹah, are they not written in the book of the affairs of the days of the kings of Judah?

[[v12-14-19]]

^<<v12-14-19,19>>^ At length they leagued against him in a conspiracy at Jerusalem, and he went fleeing to Laʹchish; but they sent in pursuit of him to Laʹchish and put him to death there.

[[v12-14-20]]

^<<v12-14-20,20>>^ So they carried him upon horses and he was buried in Jerusalem with his forefathers in the City of David.

[[v12-14-21]]

^<<v12-14-21,21>>^ Then all the people of Judah took Az·a·riʹah, he at the time being sixteen years old, and they made him king in place of his father Am·a·ziʹah.

[[v12-14-22]]

^<<v12-14-22,22>>^ He himself built Eʹlath and got to restore it to Judah after the king lay down with his forefathers.

[[v12-14-23]]

^<<v12-14-23,23>>^ In the fifteenth year of Am·a·ziʹah the son of Je·hoʹash the king of Judah, Jer·o·boʹam the son of Je·hoʹash the king of Israel became king in Sa·marʹi·a for forty-one years.

[[v12-14-24]]

^<<v12-14-24,24>>^ And he continued to do what was bad in Jehovah’s eyes. He did not depart from all the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin.

[[v12-14-25]]

^<<v12-14-25,25>>^ He it was that restored the boundary of Israel from the entering in of Haʹmath clear to the sea of the Arʹa·bah, according to the word of Jehovah the God of Israel who spoke by means of his servant Joʹnah the son of A·mitʹtai, the prophet that was from Gath-heʹpher.

[[v12-14-26]]

^<<v12-14-26,26>>^ For Jehovah had seen the very bitter affliction of Israel. There was neither any helpless one nor any worthless one,^&#42;1^ nor was there a helper for Israel.

[NOTE]
====
. Lit., “neither anyone restrained nor anyone let go (abandoned).” Compare De 32:36 ftn, “One.”
====

[[v12-14-27]]

^<<v12-14-27,27>>^ And Jehovah had promised not to wipe out the name of Israel from under the heavens. Consequently he saved them by the hand of Jer·o·boʹam the son of Je·hoʹash.

[[v12-14-28]]

^<<v12-14-28,28>>^ As for the rest of the affairs of Jer·o·boʹam and all that he did and his mightiness, how he fought and how he restored Damascus and Haʹmath to Judah in Israel, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ Finally Jer·o·boʹam lay down with his forefathers, with the kings of Israel, and Zech·a·riʹah his son began to reign in place of him.

'''

xref:012-2-kings/012-2-kings-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-kings/012-2-kings-015.adoc#v12-15-0[Próximo Capítulo &#62;]