include::./index.adoc[]

[[v12-10-0]]
=== The Second of Kings, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-10-1]]

^<<v12-10-1,1>>^ Now Aʹhab had seventy sons in Sa·marʹi·a. Therefore Jeʹhu wrote letters and sent them to Sa·marʹi·a to the princes of Jezʹre·el, the older men and the caretakers of Aʹhab,^&#42;1^ saying:

[NOTE]
====
. Or, “the trustees of Ahab,” M; LXX, “the caretakers of the sons of Ahab.”
====

[[v12-10-2]]

^<<v12-10-2,2>>^ “Now, then, at the very time that this letter comes to YOU there are with YOU the sons of YOUR lord, and there are with YOU the war chariots and the horses and a fortified city and the armor.

[[v12-10-3]]

^<<v12-10-3,3>>^ And YOU must see which is the best and most upright of the sons of YOUR lord and put him upon the throne of his father. Then fight for the house of YOUR lord.”

[[v12-10-4]]

^<<v12-10-4,4>>^ And they became very greatly afraid and began to say: “Look! Two kings themselves did not stand before him, and how shall we ourselves stand?”

[[v12-10-5]]

^<<v12-10-5,5>>^ Consequently the one who was over the house and the one who was over the city and the older men and the caretakers sent to Jeʹhu, saying: “We are your servants, and everything that you say to us we shall do. We shall not make anyone king. What is good in your own eyes do.”

[[v12-10-6]]

^<<v12-10-6,6>>^ At that he wrote them a second letter, saying: “If YOU belong to me, and it is my voice that YOU are obeying, take the heads of the men that are sons of YOUR lord and come to me tomorrow at this time at Jezʹre·el.”
Now the sons of the king, seventy men, were with the distinguished men of the city that were bringing them up.

[[v12-10-7]]

^<<v12-10-7,7>>^ And it came about that as soon as the letter came to them, they went taking the sons of the king and slaughtering &#91;them&#93;, seventy men, after which they put their heads in baskets and sent them to him at Jezʹre·el.

[[v12-10-8]]

^<<v12-10-8,8>>^ Then the messenger came in and told him, saying: “They have brought the heads of the sons of the king.” So he said: “PUT them in two heaps at the entrance of the gate until morning.”

[[v12-10-9]]

^<<v12-10-9,9>>^ And it came about in the morning that he proceeded to go out. Then he stood still and said to all the people: “YOU are righteous.^&#42;1^ Here I myself conspired against my lord, and I got to kill him; but who struck down all these?

[NOTE]
====
. Or, “innocent.”
====

[[v12-10-10]]

^<<v12-10-10,10>>^ Know, then, that nothing of Jehovah’s word will fall &#91;unfulfilled&#93; to the earth that Jehovah has spoken against the house of Aʹhab; and Jehovah himself has done what he spoke by means of his servant E·liʹjah.”

[[v12-10-11]]

^<<v12-10-11,11>>^ Moreover, Jeʹhu went on to strike down all who were left over of the house of Aʹhab in Jezʹre·el and all his distinguished men and his acquaintances and his priests, until he had let no survivor of his remain.

[[v12-10-12]]

^<<v12-10-12,12>>^ And he proceeded to rise and come in, then get on his way to Sa·marʹi·a. The binding house of the shepherds was on the way.^&#42;1^

[NOTE]
====
. Or, “Beth-eked of the Shepherds was on the way.”
====

[[v12-10-13]]

^<<v12-10-13,13>>^ And Jeʹhu himself encountered the brothers of A·ha·ziʹah the king of Judah. When he said to them, “Who are YOU?” then they said: “We are the brothers of A·ha·ziʹah, and we are on our way down to ask if all is well with^&#42;1^ the sons of the king and the sons of the lady.”

[NOTE]
====
. Lit., “on our way down for the welfare of.”
====

[[v12-10-14]]

^<<v12-10-14,14>>^ Immediately he said: “Seize them alive, YOU men!” So they seized them alive and slaughtered them at the cistern of the binding house,^&#42;1^ forty-two men, and he did not let a single one of them remain.

[NOTE]
====
. Or, “cistern of Beth-eked.”
====

[[v12-10-15]]

^<<v12-10-15,15>>^ As he was going along from there he got to encounter Je·honʹa·dab^&#42;1^ the son of Reʹchab &#91;coming&#93; to meet him. When he blessed him, he accordingly said to him: “Is your heart upright with me, just as my own heart is with your heart?”
To this Je·honʹa·dab said: “It is.”
“If it is, do give me your hand.”
So he gave him his hand. At that he made him get up into the chariot with him.

[NOTE]
====
. Meaning “Jehovah Is Willing; Jehovah Is Noble.” Compare 2Sa 13:3 ftn.
====

[[v12-10-16]]

^<<v12-10-16,16>>^ Then he said: “Do go along with me and look upon my toleration of no rivalry toward Jehovah.” And they^&#42;1^ kept him riding with him in his war chariot.

[NOTE]
====
. “They,” M; LXXSy, “he.”
====

[[v12-10-17]]

^<<v12-10-17,17>>^ Finally he came to Sa·marʹi·a. Now he went striking down all who were left over of Aʹhab’s in Sa·marʹi·a, until he had annihilated them, according to Jehovah’s word that he had spoken to E·liʹjah.

[[v12-10-18]]

^<<v12-10-18,18>>^ Further, Jeʹhu collected all the people together and said to them: “Aʹhab, on the one hand, worshiped^&#42;1^ Baʹal^&#42;2^ a little. Jeʹhu, on the other hand, will worship him a great deal.

[NOTE]
====
. Or, “rendered sacred service to.” Lit., “served.” Heb., ʽa·vadhʹ.
. Lit., “the Baal.” Heb., hab·Baʹʽal. Compare Nu 22:41 ftn, “Bamoth-baal.”
====

[[v12-10-19]]

^<<v12-10-19,19>>^ So now call all the prophets of Baʹal, all his worshipers and all his priests to me. Do not let a single one be missing, because I have a great sacrifice for Baʹal. Anyone that is missing will not keep living.” As for Jeʹhu, he acted slyly, for the purpose of destroying the worshipers of Baʹal.

[[v12-10-20]]

^<<v12-10-20,20>>^ And Jeʹhu went on to say: “Sanctify a solemn assembly for Baʹal.” Accordingly they proclaimed it.

[[v12-10-21]]

^<<v12-10-21,21>>^ After that Jeʹhu sent through all Israel, so that all the worshipers of Baʹal came in. And not a single one was left over that did not come in. And they kept coming into the house of Baʹal, and the house of Baʹal came to be full from end to end.^&#42;1^

[NOTE]
====
. Lit., “full, mouth to mouth.” Possibly meaning standing very close to one another.
====

[[v12-10-22]]

^<<v12-10-22,22>>^ He now said to the one who was over the wardrobe: “Bring out garments for all the worshipers of Baʹal.” So he brought the attire out for them.

[[v12-10-23]]

^<<v12-10-23,23>>^ Then Jeʹhu entered with Je·honʹa·dab the son of Reʹchab into the house of Baʹal. He now said to the worshipers of Baʹal: “Search carefully and see that there may be here with YOU none of the worshipers of Jehovah, but only the worshipers of Baʹal.”

[[v12-10-24]]

^<<v12-10-24,24>>^ Finally they came in to render up sacrifices and burnt offerings, and Jeʹhu himself stationed eighty^&#42;1^ men outside at his disposal and went on to say: “As for the man that escapes from the men whom I am bringing into YOUR hands, the one’s soul will go for the other’s soul.”

[NOTE]
====
. “Eighty,” MLXXVg; Sy, “three hundred and eighty”; LXXLItLegionensis(margin), “three thousand.”
====

[[v12-10-25]]

^<<v12-10-25,25>>^ And it came about that as soon as he finished rendering up the burnt offering, Jeʹhu immediately said to the runners and the adjutants: “Come in, strike them down! Do not let a single one go out.” And the runners and the adjutants began to strike them down with the edge of the sword and to throw them out, and they kept going as far as the city of the house of Baʹal.

[[v12-10-26]]

^<<v12-10-26,26>>^ Then they brought out the sacred pillars^&#42;1^ of the house of Baʹal and burned each one.^&#42;2^

[NOTE]
====
. “Sacred pillars,” M; LXXSyVg, “sacred pillar.” Possibly the sacred pole or Asherah.
. Lit., “it,” fem., that is, each sacred pillar (pole) individually.
====

[[v12-10-27]]

^<<v12-10-27,27>>^ Further, they pulled down the sacred pillar of Baʹal and pulled down the house of Baʹal, and they kept it set aside for privies down to this day.

[[v12-10-28]]

^<<v12-10-28,28>>^ Thus Jeʹhu annihilated Baʹal out of Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ It was only the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin, that Jeʹhu did not turn aside from following them, &#91;that is,&#93; the golden calves of which one was in Bethʹel and one in Dan.

[[v12-10-30]]

^<<v12-10-30,30>>^ Consequently Jehovah said to Jeʹhu: “For the reason that you have acted well in doing what is right in my eyes, &#91;and&#93; according to all that was in my heart you have done to the house of Aʹhab, sons themselves to the fourth generation will sit for you upon the throne of Israel.”

[[v12-10-31]]

^<<v12-10-31,31>>^ And Jeʹhu himself did not take care to walk in the law of Jehovah the God of Israel with all his heart. He did not turn aside from the sins of Jer·o·boʹam with which he caused Israel to sin.

[[v12-10-32]]

^<<v12-10-32,32>>^ In those days Jehovah started to cut off Israel piece by piece; and Hazʹa·el kept striking them in all the territory of Israel,

[[v12-10-33]]

^<<v12-10-33,33>>^ from the Jordan toward the rising of the sun, all the land of Gilʹe·ad, the Gadʹites and the Reuʹben·ites and the Ma·nasʹsites, from A·roʹer, which is by the torrent valley of Arʹnon, even Gilʹe·ad and Baʹshan.

[[v12-10-34]]

^<<v12-10-34,34>>^ And the rest of the affairs of Jeʹhu and all that he did and all his mightiness, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Finally Jeʹhu lay down with his forefathers, and they buried him in Sa·marʹi·a; and Je·hoʹa·haz his son began to reign in place of him.

[[v12-10-36]]

^<<v12-10-36,36>>^ And the days that Jeʹhu had reigned over Israel were twenty-eight years in Sa·marʹi·a.

'''

xref:012-2-kings/012-2-kings-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-kings/012-2-kings-011.adoc#v12-11-0[Próximo Capítulo &#62;]