include::./index.adoc[]

[[v12-18-0]]
=== The Second of Kings, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-18-1]]

^<<v12-18-1,1>>^ And it came about in the third year of Ho·sheʹa the son of Eʹlah the king of Israel that Hez·e·kiʹah the son of Aʹhaz the king of Judah became king.

[[v12-18-2]]

^<<v12-18-2,2>>^ Twenty-five years old he happened to be when he began to reign, and for twenty-nine years he reigned in Jerusalem. And his mother’s name was Aʹbi^&#42;1^ the daughter of Zech·a·riʹah.

[NOTE]
====
. “Abi” (an abbreviation for Abijah), MSyVg; in 2Ch 29:1, “Abijah”; Gr., Aʹbou.
====

[[v12-18-3]]

^<<v12-18-3,3>>^ And he continued to do what was right in Jehovah’s eyes, according to all that David his forefather had done.

[[v12-18-4]]

^<<v12-18-4,4>>^ He it was that removed the high places and broke the sacred pillars to pieces and cut down the sacred pole and crushed to pieces the copper serpent that Moses had made; for down to those days the sons of Israel had continually been making sacrificial smoke to it, and it used to be called the copper serpent-idol.^&#42;1^

[NOTE]
====
. Lit., “he (one) began to call it Nehushtan.”
====

[[v12-18-5]]

^<<v12-18-5,5>>^ In Jehovah the God of Israel he trusted; and after him there proved to be no one like him among all the kings of Judah, even those who had happened to be prior to him.

[[v12-18-6]]

^<<v12-18-6,6>>^ And he kept sticking to Jehovah. He did not turn aside from following him, but he continued keeping his commandments that Jehovah had commanded Moses.

[[v12-18-7]]

^<<v12-18-7,7>>^ And Jehovah proved to be with him. Wherever he would go out, he would act prudently; and he proceeded to rebel against the king of As·syrʹi·a and did not serve him.

[[v12-18-8]]

^<<v12-18-8,8>>^ It was he that struck down the Phi·lisʹtines clear to Gaʹza and also its territories, from the tower of the watchmen clear to the fortified city.

[[v12-18-9]]

^<<v12-18-9,9>>^ And it came about in the fourth year of King Hez·e·kiʹah,^&#42;1^ that is, the seventh year of Ho·sheʹa the son of Eʹlah the king of Israel, that Shal·man·eʹser the king of As·syrʹi·a came up against Sa·marʹi·a and began to lay siege to it.

[NOTE]
====
. “Hezekiah.” Heb., Chiz·qi·yaʹhu, as in 16:20.
====

[[v12-18-10]]

^<<v12-18-10,10>>^ And they got to capture it at the end of three years; in the sixth year of Hez·e·kiʹah, that is, the ninth year of Ho·sheʹa the king of Israel, Sa·marʹi·a was captured.

[[v12-18-11]]

^<<v12-18-11,11>>^ After that the king of As·syrʹi·a took Israel into exile in As·syrʹi·a and set them down in Haʹlah and in Haʹbor at the river Goʹzan and in the cities of the Medes,

[[v12-18-12]]

^<<v12-18-12,12>>^ over the fact that they had not listened to the voice of Jehovah their God, but kept overstepping his covenant, even all that Moses the servant of Jehovah had commanded. They neither listened nor performed.

[[v12-18-13]]

^<<v12-18-13,13>>^ And in the fourteenth year of King Hez·e·kiʹah, Sen·nachʹer·ib the king of As·syrʹi·a came up against all the fortified cities of Judah and proceeded to seize them.

[[v12-18-14]]

^<<v12-18-14,14>>^ So Hez·e·kiʹah the king of Judah sent to the king of As·syrʹi·a at Laʹchish, saying: “I have sinned. Turn back from against me. Whatever you may impose upon me I shall carry.” Accordingly the king of As·syrʹi·a laid upon Hez·e·kiʹah the king of Judah three hundred silver talents^&#42;1^ and thirty gold talents.

[NOTE]
====
. See App 8A.
====

[[v12-18-15]]

^<<v12-18-15,15>>^ Therefore Hez·e·kiʹah gave all the silver that was to be found at the house of Jehovah and in the treasures of the king’s house.

[[v12-18-16]]

^<<v12-18-16,16>>^ At that time Hez·e·kiʹah cut off the doors of the temple^&#42;1^ of Jehovah and the doorposts that Hez·e·kiʹah the king of Judah had overlaid and then gave them to the king of As·syrʹi·a.

[NOTE]
====
. “Temple of.” Heb., heh·khalʹ; Gr., na·ouʹ; Lat., temʹpli. Compare 20:18 ftn; Mt 23:16 ftn.
====

[[v12-18-17]]

^<<v12-18-17,17>>^ And the king of As·syrʹi·a proceeded to send Tarʹtan^&#42;1^ and Rabʹsa·ris^&#42;2^ and Rabʹsha·keh^&#42;3^ from Laʹchish to King Hez·e·kiʹah with a heavy military force to Jerusalem, that they might go up and come to Jerusalem. So they went up and came and stood still by the conduit of the upper pool, which is at the highway of the laundryman’s field.

[NOTE]
====
. Or, “the commander.”
. Or, “the chief court official.”
. Or, “the chief cupbearer.”
====

[[v12-18-18]]

^<<v12-18-18,18>>^ And they began to call out to the king, but there came out to them E·liʹa·kim the son of Hil·kiʹah,^&#42;1^ who was over the household, and Shebʹnah the secretary and Joʹah the son of Aʹsaph the recorder.

[NOTE]
====
. Meaning “My Portion Is Jehovah.” Heb., Chil·qi·yaʹhu.
====

[[v12-18-19]]

^<<v12-18-19,19>>^ Accordingly Rabʹsha·keh said to them: “Please, say to Hez·e·kiʹah, ‘This is what the great king, the king of As·syrʹi·a, has said: “What is this confidence in which you have trusted?

[[v12-18-20]]

^<<v12-18-20,20>>^ You have said (but it is the word of lips), ‘There are counsel and mightiness for the war.’ Now in whom have you put your trust, that you have rebelled against me?

[[v12-18-21]]

^<<v12-18-21,21>>^ Now, look! you have put your trust in the support of this crushed reed, Egypt, which, if a man should brace himself upon it, would certainly enter into his palm and pierce it. That is the way Pharʹaoh the king of Egypt is to all those putting their trust in him.

[[v12-18-22]]

^<<v12-18-22,22>>^ And in case YOU men should say to me, ‘It is Jehovah our God in whom we have put our trust,’ is he not the one whose high places and whose altars Hez·e·kiʹah has removed, while he says to Judah and Jerusalem, ‘Before this altar YOU should bow down in Jerusalem’?”’

[[v12-18-23]]

^<<v12-18-23,23>>^ Now, then, make a wager, please, with my lord the king of As·syrʹi·a, and let me give you two thousand horses &#91;to see&#93; whether you are able, on your part, to put riders upon them.

[[v12-18-24]]

^<<v12-18-24,24>>^ How, then, could you turn back the face of one governor of the smallest servants of my lord, while you, for your part, put your trust in Egypt for chariots and for horsemen?

[[v12-18-25]]

^<<v12-18-25,25>>^ Now is it without authorization from Jehovah that I have come up against this place to bring it to ruin? Jehovah himself said to me, ‘Go up against this land, and you must bring it to ruin.’”

[[v12-18-26]]

^<<v12-18-26,26>>^ At this E·liʹa·kim the son of Hil·kiʹah and Shebʹnah and Joʹah said to Rabʹsha·keh: “Speak with your servants, please, in the Syrian language,^&#42;1^ for we can listen;^&#42;2^ and do not speak with us in the Jews’ language^&#42;3^ in the ears of the people that are on the wall.”

[NOTE]
====
. “The Syrian language.” Or, “the Aramaic language.” Heb., ʼAra·mithʹ; the first occurrence of this word. See Ezr 4:7; Isa 36:11; Da 2:4.
. Or, “understand.”
. “The Jews’ language.” Heb., Yehu·dhithʹ; the first occurrence of this word.
====

[[v12-18-27]]

^<<v12-18-27,27>>^ But Rabʹsha·keh said to them: “Is it to your lord and to you that my lord has sent me to speak these words? Is it not to the men sitting upon the wall, that they may eat their own excrement and drink their own urine with YOU men?”

[[v12-18-28]]

^<<v12-18-28,28>>^ And Rabʹsha·keh continued to stand and call out in a loud voice in the Jews’ language; and he went on to speak and say: “HEAR the word of the great king, the king of As·syrʹi·a.

[[v12-18-29]]

^<<v12-18-29,29>>^ This is what the king has said, ‘Do not let Hez·e·kiʹah deceive YOU people, for he is not able to deliver YOU out of my hand.

[[v12-18-30]]

^<<v12-18-30,30>>^ And do not let Hez·e·kiʹah cause YOU to trust in Jehovah, saying: “Without fail Jehovah will deliver us, and this city will not be given into the hand of the king of As·syrʹi·a.”

[[v12-18-31]]

^<<v12-18-31,31>>^ Do not listen to Hez·e·kiʹah; for this is what the king of As·syrʹi·a has said: “Make a capitulation to me,^&#42;1^ and come out to me, and eat each one from his own vine and each one from his own fig tree and drink each one the water of his own cistern,

[NOTE]
====
. Lit., “Make with me a blessing [that is, what will be a blessing].”
====

[[v12-18-32]]

^<<v12-18-32,32>>^ until I come and I actually take YOU to a land like YOUR own land, a land of grain and new wine, a land of bread and vineyards, a land of oil-olive trees and honey; and keep living that YOU may not die. And do not listen to Hez·e·kiʹah, for he allures YOU, saying, ‘Jehovah himself will deliver us.’

[[v12-18-33]]

^<<v12-18-33,33>>^ Have the gods of the nations at all delivered each one his own land out of the hand of the king of As·syrʹi·a?

[[v12-18-34]]

^<<v12-18-34,34>>^ Where are the gods of Haʹmath and Arʹpad? Where are the gods of Seph·ar·vaʹim, Heʹna and Ivʹvah? Have they delivered Sa·marʹi·a out of my hand?

[[v12-18-35]]

^<<v12-18-35,35>>^ Who are there among all the gods of the lands that have delivered their land out of my hand, so that Jehovah should deliver Jerusalem out of my hand?”’”

[[v12-18-36]]

^<<v12-18-36,36>>^ And the people kept silent and did not answer him a word, for the commandment of the king was, saying: “YOU must not answer him.”

[[v12-18-37]]

^<<v12-18-37,37>>^ But E·liʹa·kim the son of Hil·kiʹah, who was over the household, and Shebʹnah the secretary and Joʹah the son of Aʹsaph the recorder came to Hez·e·kiʹah with their garments ripped apart and told him the words of Rabʹsha·keh.

'''

xref:012-2-kings/012-2-kings-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-kings/012-2-kings-019.adoc#v12-19-0[Próximo Capítulo &#62;]