include::./index.adoc[]

[[v12-6-0]]
=== The Second of Kings, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-6-1]]

^<<v12-6-1,1>>^ And the sons of the prophets began to say to E·liʹsha: “Look, now! The place where we are dwelling before you is too cramped for us.

[[v12-6-2]]

^<<v12-6-2,2>>^ Let us go, please, as far as the Jordan and take from there each one a beam and make for ourselves there a place in which to dwell.” So he said: “Go.”

[[v12-6-3]]

^<<v12-6-3,3>>^ And a certain one went on to say: “Come on, please, and go with your servants.” At that he said: “I myself shall go.”

[[v12-6-4]]

^<<v12-6-4,4>>^ Accordingly he went with them, and they finally came to the Jordan and began to cut down the trees.

[[v12-6-5]]

^<<v12-6-5,5>>^ And it came about that a certain one was felling his beam, and the axhead^&#42;1^ itself fell into the water. And he began to cry out and say: “Alas, my master, for it was borrowed!”

[NOTE]
====
. Lit., “the iron.”
====

[[v12-6-6]]

^<<v12-6-6,6>>^ Then the man of the &#91;true&#93; God said: “Where did it fall?” So he showed him the place. Immediately he cut off a piece of wood and threw it there and made the axhead float.

[[v12-6-7]]

^<<v12-6-7,7>>^ He now said: “Lift it up for yourself.” At once he thrust his hand out and took it.

[[v12-6-8]]

^<<v12-6-8,8>>^ And the king of Syria, for his part, became involved in war against Israel. Accordingly he took counsel with his servants, saying: “At such and such a place YOU will encamp with me.”^&#42;1^

[NOTE]
====
. “You will encamp with me,” by a slight change in M.
====

[[v12-6-9]]

^<<v12-6-9,9>>^ Then the man of the &#91;true&#93; God sent to the king of Israel, saying: “Guard yourself against passing by this place, because there is where the Syrians are coming down.”

[[v12-6-10]]

^<<v12-6-10,10>>^ So the king of Israel sent to the place that the man of the &#91;true&#93; God had said to him. And he warned him, and he kept away from there, not once or twice.

[[v12-6-11]]

^<<v12-6-11,11>>^ Consequently the heart of the king of Syria became enraged over this matter, so that he called his servants and said to them: “Will YOU not tell me who from those who belong to us is for the king of Israel?”

[[v12-6-12]]

^<<v12-6-12,12>>^ Then one of his servants said: “None, my lord the king, but it is E·liʹsha the prophet who is in Israel that tells the king of Israel the things that you speak in your inner bedroom.”

[[v12-6-13]]

^<<v12-6-13,13>>^ So he said: “YOU men go and see where he is, that I may send and take him.” Later the report was made to him, saying: “There he is in Doʹthan.”

[[v12-6-14]]

^<<v12-6-14,14>>^ Immediately he sent horses and war chariots and a heavy military force there; and they proceeded to come by night and close in upon the city.

[[v12-6-15]]

^<<v12-6-15,15>>^ When the minister of the man of the &#91;true&#93; God rose early to get up, and went out, why, there a military force was surrounding the city with horses and war chariots. At once his attendant said to him: “Alas, my master! What shall we do?”

[[v12-6-16]]

^<<v12-6-16,16>>^ But he said: “Do not be afraid, for there are more who are with us than those who are with them.”

[[v12-6-17]]

^<<v12-6-17,17>>^ And E·liʹsha began to pray and say: “O Jehovah, open his eyes, please, that he may see.” Immediately Jehovah opened the attendant’s eyes, so that he saw; and, look! the mountainous region was full of horses and war chariots of fire all around E·liʹsha.

[[v12-6-18]]

^<<v12-6-18,18>>^ When they began to come down to him, E·liʹsha went on to pray to Jehovah and say: “Please, strike this nation^&#42;1^ with blindness.” So he struck them with blindness according to the word of E·liʹsha.

[NOTE]
====
. Or, “these Gentiles (heathens).”
====

[[v12-6-19]]

^<<v12-6-19,19>>^ E·liʹsha now said to them: “This is not the way, and this is not the city. Follow me, and let me conduct YOU to the man YOU look for.” However, he conducted them to Sa·marʹi·a.

[[v12-6-20]]

^<<v12-6-20,20>>^ And it came about that as soon as they arrived at Sa·marʹi·a, E·liʹsha then said: “O Jehovah, open the eyes of these that they may see.” Immediately Jehovah opened their eyes, and they got to see; and here they were in the middle of Sa·marʹi·a.

[[v12-6-21]]

^<<v12-6-21,21>>^ The king of Israel now said to E·liʹsha as soon as he saw them: “Shall I strike &#91;them&#93; down, shall I strike &#91;them&#93; down, my father?”

[[v12-6-22]]

^<<v12-6-22,22>>^ But he said: “You must not strike &#91;them&#93; down. Are those whom you have taken captive with your sword and with your bow the ones that you are striking down? Set bread and water before them that they may eat and drink and go to their lord.”

[[v12-6-23]]

^<<v12-6-23,23>>^ Accordingly he spread a great feast for them; and they began to eat and drink, after which he sent them away and they went to their lord. And not once did the marauding bands of the Syrians come again into the land of Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ And it came about afterward that Ben-haʹdad the king of Syria proceeded to collect all his camp together and to go up and besiege Sa·marʹi·a.

[[v12-6-25]]

^<<v12-6-25,25>>^ In time a great famine arose in Sa·marʹi·a, and, look! they were besieging it until an ass’s head got to be worth eighty silver pieces, and the fourth of a cab^&#42;1^ measure of dove’s dung was worth five silver pieces.

[NOTE]
====
. A cab equaled 1.22 L (2.2 dry pt).
====

[[v12-6-26]]

^<<v12-6-26,26>>^ And it came about as the king of Israel was passing along upon the wall that a certain woman cried out to him, saying: “Do save, O my lord the king!”

[[v12-6-27]]

^<<v12-6-27,27>>^ To this he said: “If Jehovah does not save you, from what &#91;source&#93; shall I save you? either from the threshing floor or from the wine or oil press?”

[[v12-6-28]]

^<<v12-6-28,28>>^ And the king went on to say to her: “What is the matter with you?” So she said: “This very woman said to me, ‘Give your son that we may eat him today, and my own son we shall eat tomorrow.’

[[v12-6-29]]

^<<v12-6-29,29>>^ Accordingly we boiled my son and ate him. Then I said to her on the next day, ‘Give your son that we may eat him.’ But she hid her son.”

[[v12-6-30]]

^<<v12-6-30,30>>^ And it came about that as soon as the king heard the woman’s words, he immediately ripped his garments apart; and as he was passing along upon the wall, the people got to see, and, look! sackcloth was underneath upon his flesh.

[[v12-6-31]]

^<<v12-6-31,31>>^ And he went on to say: “So may God do to me, and so may he add to it, if the head of E·liʹsha the son of Shaʹphat continues standing upon him today!”

[[v12-6-32]]

^<<v12-6-32,32>>^ And E·liʹsha was sitting in his own house, and the older men^&#42;1^ were sitting with him, when he sent a man from before him. Before the messenger could come in to him, he himself said to the older men: “Have YOU seen how this son of a murderer has sent to take off my head? See to it: as soon as the messenger comes, close the door, and YOU must press him back with the door. Is there not the sound of the feet of his lord behind him?”

[NOTE]
====
. “And the older men (elders).” Heb., wehaz·zeqe·nimʹ; Gr., pre·sbyʹte·roi. See Ac 15:2 ftn.
====

[[v12-6-33]]

^<<v12-6-33,33>>^ While he was yet speaking with them, here was the messenger^&#42;1^ coming down to him, and &#91;the king&#93;^&#42;2^ proceeded to say: “Here this is the calamity from Jehovah. Why should I wait any longer for Jehovah?”

[NOTE]
====
. Possibly, “the king.” Compare 7:2.
. Lit., “he.” See 7:2.
====

'''

xref:012-2-kings/012-2-kings-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-kings/012-2-kings-007.adoc#v12-7-0[Próximo Capítulo &#62;]