include::./index.adoc[]

[[v12-7-0]]
=== The Second of Kings, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-7-1]]

^<<v12-7-1,1>>^ E·liʹsha now said: “Listen, YOU men, to the word of Jehovah. This is what Jehovah has said, ‘Tomorrow about this time a seah^&#42;1^ measure of fine flour will be worth a shekel,^&#42;2^ and two seah measures of barley worth a shekel in the gateway of Sa·marʹi·a.’”

[NOTE]
====
. A seah equaled 7.33 L (6.66 dry qt).
. See App 8A.
====

[[v12-7-2]]

^<<v12-7-2,2>>^ At that the adjutant upon whose hand the king was supporting himself answered the man of the &#91;true&#93; God and said: “If Jehovah were making floodgates in the heavens, could this thing take place?” To this he said: “Here you are seeing it with your own eyes, but from it you will not eat.”

[[v12-7-3]]

^<<v12-7-3,3>>^ And there were four men, lepers, that happened to be at the entrance of the gate; and they began to say the one to the other: “Why are we sitting here until we have died?

[[v12-7-4]]

^<<v12-7-4,4>>^ If we had said, ‘Let us enter the city,’ when the famine is in the city, we would also have to die there. And if we do sit here, we shall also have to die. So now come and let us invade the camp of the Syrians. If they preserve us alive, we shall live; but if they put us to death, then we shall have to die.”

[[v12-7-5]]

^<<v12-7-5,5>>^ Accordingly they rose up in the evening darkness to enter the camp of the Syrians; and they got to come as far as the outskirts of the camp of the Syrians, and, look! nobody was there.

[[v12-7-6]]

^<<v12-7-6,6>>^ And Jehovah^&#42;1^ himself had caused the camp of the Syrians to hear the sound of war chariots, the sound of horses, the sound of a great military force, so that they said to one another: “Look! The king of Israel has hired against us the kings of the Hitʹtites and the kings of Egypt to come against us!”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v12-7-7]]

^<<v12-7-7,7>>^ Immediately they got up and went fleeing in the evening darkness and leaving their tents and their horses and their asses—the camp just as it was—and they kept fleeing for their soul.^&#42;1^

[NOTE]
====
. Or, “life.”
====

[[v12-7-8]]

^<<v12-7-8,8>>^ When these lepers came as far as the outskirts of the camp, they then entered into one tent and began to eat and drink and carry from there silver and gold and garments and go off and stick them away. After that they returned and entered into another tent and carried things from there and went off and stuck them away.

[[v12-7-9]]

^<<v12-7-9,9>>^ Finally they began to say the one to the other: “It is not right what we are doing. This day is a day of good news! If we are hesitating, and we actually wait until the morning light, guilt must also catch up with us. So now come and let us enter and make report at the king’s house.”

[[v12-7-10]]

^<<v12-7-10,10>>^ So they came and called to the gatekeepers of the city and reported to them, saying: “We came into the camp of the Syrians, and, look! there was nobody there nor sound of a man, but only the horses tied and the asses tied and the tents just as they were.”

[[v12-7-11]]

^<<v12-7-11,11>>^ At once the gatekeepers called out and they reported to the king’s house inside.

[[v12-7-12]]

^<<v12-7-12,12>>^ Immediately the king rose up by night and said to his servants: “Let me tell YOU, please, what the Syrians have done to us. They well know that we are hungry; and so they went out from the camp to hide themselves in the field, saying, ‘They will come out from the city, and we shall catch them alive, and into the city we shall enter.’”

[[v12-7-13]]

^<<v12-7-13,13>>^ Then one of his servants answered and said: “Let them take, please, five of the remaining horses that have remained in the city. Look! They are the same as all the crowd of Israel that have remained in it. Look! They are the same as all the crowd of Israel that have perished. And let us send out and see.”

[[v12-7-14]]

^<<v12-7-14,14>>^ Accordingly they took two chariots with horses and the king sent them out after the camp of the Syrians, saying: “Go and see.”

[[v12-7-15]]

^<<v12-7-15,15>>^ At that they went following them as far as the Jordan; and, look! all the way was full of garments and utensils that the Syrians had thrown away as they were hurrying away. Then the messengers returned and reported to the king.

[[v12-7-16]]

^<<v12-7-16,16>>^ And the people proceeded to go out and plunder the camp of the Syrians; and so a seah measure of fine flour came to be worth a shekel, and two seah measures of barley worth a shekel, according to the word of Jehovah.

[[v12-7-17]]

^<<v12-7-17,17>>^ And the king himself had appointed the adjutant upon whose hand he was supporting himself to have charge of the gateway; and the people kept trampling him in the gateway, so that he died, just as the man of the &#91;true&#93; God had spoken, when he spoke at the time that the king came down to him.

[[v12-7-18]]

^<<v12-7-18,18>>^ Thus it came about just as the man of the &#91;true&#93; God had spoken to the king, saying: “Two seah measures of barley worth a shekel and a seah measure of fine flour worth a shekel it will come to be tomorrow at this time in the gateway of Sa·marʹi·a.”

[[v12-7-19]]

^<<v12-7-19,19>>^ But the adjutant answered the man of the &#91;true&#93; God and said: “Even if Jehovah were making floodgates in the heavens, could it take place according to this word?” To this he said: “Here you are seeing it with your own eyes, but from it you will not eat.”

[[v12-7-20]]

^<<v12-7-20,20>>^ Thus it happened to him like that, when the people kept trampling him in the gateway, so that he died.

'''

xref:012-2-kings/012-2-kings-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-kings/012-2-kings-008.adoc#v12-8-0[Próximo Capítulo &#62;]