include::./index.adoc[]

[[v12-2-0]]
=== The Second of Kings, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-2-1]]

^<<v12-2-1,1>>^ And it came about that when Jehovah was to take E·liʹjah in a windstorm up to the heavens, E·liʹjah and E·liʹsha^&#42;1^ proceeded to go from Gilʹgal.^&#42;2^

[NOTE]
====
. Meaning “God Is Salvation.” LXXBagster(Gr.), He·li·sai·eʹ; Vgc(Lat.), E·li·seʹus.
. Not the Gilgal near Jericho in the low Jordan valley but the Gilgal in the hilly region near Bethel from which they could go “down” to Bethel as stated in vs 2. See 4:38.
====

[[v12-2-2]]

^<<v12-2-2,2>>^ And E·liʹjah began to say to E·liʹsha: “Sit here, please, because Jehovah himself has sent me clear to Bethʹel.” But E·liʹsha said: “As Jehovah is living and as your soul is living, I will not leave you.” So they went down to Bethʹel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Then the sons of the prophets that were at Bethʹel came out to E·liʹsha and said to him: “Do you really know that today Jehovah is taking your master^&#42;1^ from headship over you?” At this he said: “I, too, well know it. BE silent.”

[NOTE]
====
. “Your master (lord).” Heb., ʼadho·neyʹkha, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v12-2-4]]

^<<v12-2-4,4>>^ E·liʹjah now said to him: “E·liʹsha, sit here, please, because Jehovah himself has sent me to Jerʹi·cho.” But he said: “As Jehovah is living and as your soul is living, I will not leave you.” So they came on to Jerʹi·cho.

[[v12-2-5]]

^<<v12-2-5,5>>^ Then the sons of the prophets that were at Jerʹi·cho approached E·liʹsha and said to him: “Do you really know that today Jehovah is taking your master from headship over you?” At this he said: “I, too, well know it. BE silent.”

[[v12-2-6]]

^<<v12-2-6,6>>^ E·liʹjah now said to him: “Sit here, please, because Jehovah himself has sent me to the Jordan.” But he said: “As Jehovah is living and as your soul is living, I will not leave you.” So both of them went on.

[[v12-2-7]]

^<<v12-2-7,7>>^ And there were fifty men of the sons of the prophets that went and kept standing in view at a distance; but, as for both of them, they stood by the Jordan.

[[v12-2-8]]

^<<v12-2-8,8>>^ Then E·liʹjah took his official garment and wrapped it up and struck the waters, and gradually they were divided this way and that way, so that both of them went across on the dry ground.

[[v12-2-9]]

^<<v12-2-9,9>>^ And it came about that as soon as they had gone across E·liʹjah himself said to E·liʹsha: “Ask what I should do for you before I am taken from you.” To this E·liʹsha said: “Please, that two parts in your spirit may come to me.”

[[v12-2-10]]

^<<v12-2-10,10>>^ At that he said: “You have asked a difficult thing. If you see me when taken from you, it will happen to you that way; but if &#91;you do&#93; not, it will not happen.”

[[v12-2-11]]

^<<v12-2-11,11>>^ And it came about that as they were walking along, speaking as they walked, why, look! a fiery war chariot and fiery horses, and they proceeded to make a separation between them both; and E·liʹjah went ascending in the windstorm to the heavens.

[[v12-2-12]]

^<<v12-2-12,12>>^ All the while E·liʹsha was seeing it, and he was crying out: “My father, my father, the war chariot^&#42;1^ of Israel and his horsemen!” And he did not see him anymore. Consequently he took hold of his own garments and ripped them into two pieces.

[NOTE]
====
. Or, “war chariots.” Heb., reʹkhev, sing., possibly in a collective sense, as also in vs 11.
====

[[v12-2-13]]

^<<v12-2-13,13>>^ After that he picked up the official garment of E·liʹjah that had fallen off him, and went back and stood by the shore of the Jordan.

[[v12-2-14]]

^<<v12-2-14,14>>^ Then he took the official garment of E·liʹjah that had fallen off him and struck the waters and said: “Where is Jehovah the God of E·liʹjah, even He?” When he struck the waters, then they were gradually divided this way and that way, so that E·liʹsha went across.

[[v12-2-15]]

^<<v12-2-15,15>>^ When the sons of the prophets that were at Jerʹi·cho saw him some way off, they began to say: “The spirit of E·liʹjah has settled down upon E·liʹsha.” Accordingly they came to meet him and bowed down^&#42;1^ to him to the earth.

[NOTE]
====
. “They . . . bowed down.” Gr., pro·se·kyʹne·san. Compare Heb 1:6 ftn.
====

[[v12-2-16]]

^<<v12-2-16,16>>^ And they went on to say to him: “Here, now, there are with your servants fifty men, valiant persons. Let them go, please, and look for your master. It may be that the spirit^&#42;1^ of Jehovah has lifted him up and then thrown him upon one of the mountains or in one of the valleys.” But he said: “YOU must not send them.”

[NOTE]
====
. Or, “wind.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus.
====

[[v12-2-17]]

^<<v12-2-17,17>>^ And they kept urging him until he was embarrassed, so that he said: “Send.” They now sent fifty men; and they kept looking for three days, but they did not find him.

[[v12-2-18]]

^<<v12-2-18,18>>^ When they returned to him, he was dwelling in Jerʹi·cho. Then he said to them: “Did I not say to YOU, ‘Do not go’?”

[[v12-2-19]]

^<<v12-2-19,19>>^ In time the men of the city said to E·liʹsha: “Here, now, the situation of the city is good, just as my master is seeing; but the water is bad, and the land is causing miscarriages.”

[[v12-2-20]]

^<<v12-2-20,20>>^ At that he said: “Fetch me a small new bowl and put salt in it.” So they fetched it for him.

[[v12-2-21]]

^<<v12-2-21,21>>^ Then he went on out to the source of the water and threw salt in it and said: “This is what Jehovah has said, ‘I do make this water healthful. No more will death or any causing of miscarriages result from it.’”

[[v12-2-22]]

^<<v12-2-22,22>>^ And the water continues healed down to this day, according to E·liʹsha’s word that he spoke.

[[v12-2-23]]

^<<v12-2-23,23>>^ And he proceeded to go up from there to Bethʹel. As he was going up on the way, there were small boys that came out from the city and began to jeer him and that kept saying to him: “Go up, you baldhead! Go up, you baldhead!”

[[v12-2-24]]

^<<v12-2-24,24>>^ Finally he turned behind him and saw them and called down evil upon them in the name of Jehovah. Then two she-bears came out from the woods and went tearing to pieces forty-two children of their number.

[[v12-2-25]]

^<<v12-2-25,25>>^ And he kept going from there to Mount Carʹmel, and from there he returned to Sa·marʹi·a.

'''

xref:012-2-kings/012-2-kings-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-kings/012-2-kings-003.adoc#v12-3-0[Próximo Capítulo &#62;]