include::./index.adoc[]

[[v12-13-0]]
=== The Second of Kings, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-13-1]]

^<<v12-13-1,1>>^ In the twenty-third year of Je·hoʹash the son of A·ha·ziʹah the king of Judah, Je·hoʹa·haz the son of Jeʹhu became king over Israel in Sa·marʹi·a for seventeen years.

[[v12-13-2]]

^<<v12-13-2,2>>^ And he continued to do what was bad in Jehovah’s eyes and went walking in pursuit of the sin of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin. He did not turn aside from it.

[[v12-13-3]]

^<<v12-13-3,3>>^ And Jehovah’s anger became hot against Israel, so that he gave them into the hand of Hazʹa·el the king of Syria and into the hand of Ben-haʹdad the son of Hazʹa·el all their days.

[[v12-13-4]]

^<<v12-13-4,4>>^ In time Je·hoʹa·haz softened the face of Jehovah, so that Jehovah listened to him; for he had seen the oppression upon Israel, because the king of Syria had oppressed them.

[[v12-13-5]]

^<<v12-13-5,5>>^ Consequently Jehovah gave Israel a savior, so that they came out from under the hand of Syria, and the sons of Israel continued to dwell in their homes^&#42;1^ as formerly.

[NOTE]
====
. Lit., “tents.”
====

[[v12-13-6]]

^<<v12-13-6,6>>^ (Only they did not depart from the sin of the house of Jer·o·boʹam, with which he caused Israel to sin. In it he walked; and even the sacred pole^&#42;1^ itself stood in Sa·marʹi·a.)

[NOTE]
====
. Or, “the Asherah.”
====

[[v12-13-7]]

^<<v12-13-7,7>>^ For he had not left to Je·hoʹa·haz any people but fifty horsemen and ten chariots and ten thousand men on foot, because the king of Syria had destroyed them, that he might make them like the dust at threshing.

[[v12-13-8]]

^<<v12-13-8,8>>^ As for the rest of the affairs of Je·hoʹa·haz and all that he did and his mightiness, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Finally Je·hoʹa·haz lay down with his forefathers, and they buried him in Sa·marʹi·a; and Je·hoʹash his son began to reign in place of him.

[[v12-13-10]]

^<<v12-13-10,10>>^ In the thirty-seventh year of Je·hoʹash the king of Judah, Je·hoʹash the son of Je·hoʹa·haz became king over Israel in Sa·marʹi·a for sixteen years.

[[v12-13-11]]

^<<v12-13-11,11>>^ And he continued to do what was bad in Jehovah’s eyes. He did not depart from all the sins of Jer·o·boʹam the son of Neʹbat, with which he made Israel sin. In them he walked.

[[v12-13-12]]

^<<v12-13-12,12>>^ As for the rest of the affairs of Je·hoʹash and all that he did and his mightiness &#91;and&#93; how he fought against Am·a·ziʹah the king of Judah, are they not written in the book of the affairs of the days of the kings of Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Finally Je·hoʹash lay down with his forefathers, and Jer·o·boʹam^&#42;1^ himself sat upon his throne. In turn Je·hoʹash was buried in Sa·marʹi·a with the kings of Israel.

[NOTE]
====
. That is, Jeroboam II.
====

[[v12-13-14]]

^<<v12-13-14,14>>^ As regards E·liʹsha, he had taken sick with the sickness with which he was to die. So Je·hoʹash the king of Israel came down to him and began to weep over his face and say: “My father, my father, the war chariot^&#42;1^ of Israel and his horsemen!”

[NOTE]
====
. See 2:12 ftn.
====

[[v12-13-15]]

^<<v12-13-15,15>>^ And E·liʹsha proceeded to say to him: “Take a bow and arrows.” So he took to himself a bow and arrows.

[[v12-13-16]]

^<<v12-13-16,16>>^ And he went on to say to the king of Israel: “Put your hand to the bow.”^&#42;1^ Accordingly he put his hand to it, after which E·liʹsha laid his hands upon the hands of the king.

[NOTE]
====
. Lit., “Make your hand ride upon the bow.”
====

[[v12-13-17]]

^<<v12-13-17,17>>^ Then he said: “Open the window to the east.” So he opened it. Finally E·liʹsha said: “Shoot!” So he shot. He now said: “Jehovah’s arrow of salvation, even the arrow of salvation against Syria! And you will certainly strike down Syria at Aʹphek to the finishing point.”

[[v12-13-18]]

^<<v12-13-18,18>>^ And he went on to say: “Take the arrows.” At that he took &#91;them&#93;. Then he said to the king of Israel: “Strike on the earth.” So he struck three times and stopped.

[[v12-13-19]]

^<<v12-13-19,19>>^ And the man of the &#91;true&#93; God grew indignant at him; hence he said: “It was meant to strike five or six times!^&#42;1^ In that case you would certainly be striking down Syria to the finishing point, but now it is three times that you will strike down Syria.”

[NOTE]
====
. “If you had struck five or six times,” LXX; Vg, “If you had struck five or six or seven times.”
====

[[v12-13-20]]

^<<v12-13-20,20>>^ After that E·liʹsha died and they buried him. And there were marauding bands of the Moʹab·ites that regularly came into the land at the coming in of the year.

[[v12-13-21]]

^<<v12-13-21,21>>^ And it came about that as they were burying a man, why, here they saw the marauding band. At once they threw the man into E·liʹsha’s burial place and went off. When the man touched the bones of E·liʹsha, he immediately came to life and stood upon his feet.

[[v12-13-22]]

^<<v12-13-22,22>>^ As for Hazʹa·el the king of Syria, he oppressed Israel all the days of Je·hoʹa·haz.

[[v12-13-23]]

^<<v12-13-23,23>>^ However, Jehovah showed them favor and had mercy upon them and turned to them for the sake of his covenant with Abraham, Isaac and Jacob; and he did not want to bring them to ruin, and he did not cast them away from before his face until now.

[[v12-13-24]]

^<<v12-13-24,24>>^ Finally Hazʹa·el the king of Syria died, and Ben-haʹdad his son began to reign in place of him.

[[v12-13-25]]

^<<v12-13-25,25>>^ And Je·hoʹash the son of Je·hoʹa·haz proceeded to take back again from the hand of Ben-haʹdad the son of Hazʹa·el the cities that he had taken from the hand of Je·hoʹa·haz his father in war. Three times Je·hoʹash struck him down, and he got to recover the cities of Israel.

'''

xref:012-2-kings/012-2-kings-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-kings/012-2-kings-014.adoc#v12-14-0[Próximo Capítulo &#62;]