include::./index.adoc[]

[[v12-12-0]]
=== The Second of Kings, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-12-1]]

^<<v12-12-1,1>>^ In the seventh year of Jeʹhu, Je·hoʹash became king, and for forty years he reigned in Jerusalem. And his mother’s name was Zibʹi·ah from Beʹer-sheʹba.

[[v12-12-2]]

^<<v12-12-2,2>>^ And Je·hoʹash continued doing what was right in Jehovah’s eyes all the days of his that Je·hoiʹa·da the priest instructed him.

[[v12-12-3]]

^<<v12-12-3,3>>^ It was only the high places that did not disappear. The people were still sacrificing and making sacrificial smoke on the high places.

[[v12-12-4]]

^<<v12-12-4,4>>^ And Je·hoʹash proceeded to say to the priests: “All the money^&#42;1^ for the holy offerings that is brought to the house of Jehovah, the money at which each one is assessed,^&#42;2^ the money for the souls according to individual valuation, all the money that it comes up on the heart of each one to bring to the house of Jehovah,

[NOTE]
====
. Lit., “silver.” Heb., keʹseph.
. Lit., “the silver of each one passing by.”
====

[[v12-12-5]]

^<<v12-12-5,5>>^ let the priests take for themselves, each one from his acquaintance; and let them, for their part, repair the cracks of the house wherever any crack is found.”

[[v12-12-6]]

^<<v12-12-6,6>>^ And it came about that by the twenty-third year of King Je·hoʹash, the priests had not yet repaired the cracks of the house.

[[v12-12-7]]

^<<v12-12-7,7>>^ So King Je·hoʹash called Je·hoiʹa·da the priest and the priests and said to them: “Why is it that YOU are not repairing the cracks of the house? Now, then, do not take any more money from YOUR acquaintances, but for the cracks of the house YOU should give it.”

[[v12-12-8]]

^<<v12-12-8,8>>^ At that the priests consented not to take any more money from the people and not to repair the cracks of the house.

[[v12-12-9]]

^<<v12-12-9,9>>^ Je·hoiʹa·da the priest now took a chest^&#42;1^ and bored a hole in its lid and put it beside the altar on the right as a person comes into the house of Jehovah, and there the priests, the doorkeepers,^&#42;2^ put all the money that was being brought into the house of Jehovah.

[NOTE]
====
. “Chest.” Heb., ʼarohnʹ. See Ex 25:10 ftn, “Ark.”
. Lit., “keepers of the threshold.”
====

[[v12-12-10]]

^<<v12-12-10,10>>^ And it came about that as soon as they saw that there was a great deal of money in the chest, the secretary of the king and the high priest^&#42;1^ would come up, and they would bind it up and count the money that was being found at the house of Jehovah.

[NOTE]
====
. Or, “and the chief priest.” Lit., “and the great[est] priest.” Heb., wehak·ko·henʹ hag·ga·dhohlʹ.
====

[[v12-12-11]]

^<<v12-12-11,11>>^ And they gave the money that had been counted off over to the hands of doers of the work that were appointed &#91;to&#93; the house of Jehovah. In turn they paid it out to the workers in wood and to the builders that were working at the house of Jehovah,

[[v12-12-12]]

^<<v12-12-12,12>>^ and to the masons and to the hewers of stone, and to buy timbers and hewn stones for repairing the cracks of the house of Jehovah and for all that was expended upon the house to repair it.

[[v12-12-13]]

^<<v12-12-13,13>>^ Only as respects the house of Jehovah there were not made basins of silver, extinguishers, bowls, trumpets, any sort of gold article and article of silver from the money that was being brought to the house of Jehovah;

[[v12-12-14]]

^<<v12-12-14,14>>^ for it was to the doers of the work that they would give it, and with it they repaired the house of Jehovah.

[[v12-12-15]]

^<<v12-12-15,15>>^ And they would not call for an accounting with the men into whose hand they would give the money to give to the doers of the work, because it was with faithfulness that they were working.

[[v12-12-16]]

^<<v12-12-16,16>>^ As for the money for guilt offerings and the money for sin offerings, it was not being brought to the house of Jehovah. So it came to belong to the priests.

[[v12-12-17]]

^<<v12-12-17,17>>^ Then it was that Hazʹa·el the king of Syria proceeded to go up and fight against Gath and capture it, after which Hazʹa·el set his face to go up against Jerusalem.

[[v12-12-18]]

^<<v12-12-18,18>>^ At that Je·hoʹash the king of Judah took all the holy offerings that Je·hoshʹa·phat and Je·hoʹram and A·ha·ziʹah his forefathers, the kings of Judah, had sanctified and his own holy offerings and all the gold to be found in the treasures of the house of Jehovah and the house of the king and sent them to Hazʹa·el the king of Syria. So he withdrew from against Jerusalem.

[[v12-12-19]]

^<<v12-12-19,19>>^ As for the rest of the affairs of Je·hoʹash^&#42;1^ and all that he did, are they not written in the book of the affairs of the days of the kings of Judah?

[NOTE]
====
. Lit., “Joash.” But see vss 1-7, 18.
====

[[v12-12-20]]

^<<v12-12-20,20>>^ However, his servants rose up and leagued together in a conspiracy and struck Je·hoʹash down at the house of the Mound,^&#42;1^ &#91;on the way&#93; that goes down to Silʹla.

[NOTE]
====
. Or, “Millo.” Heb., mil·loʼʹ.
====

[[v12-12-21]]

^<<v12-12-21,21>>^ And Joʹza·car^&#42;1^ the son of Shimʹe·ath and Je·hozʹa·bad the son of Shoʹmer, his servants, were the ones that struck him down, so that he died. Accordingly they buried him with his forefathers in the City of David; and Am·a·ziʹah his son began to reign in place of him.

[NOTE]
====
. “Jozacar,” AlCaLXXVg and some Heb. mss; Leningrad B 19A, “Jozabad”; in 2Ch 24:26, “Zabad.”
====

'''

xref:012-2-kings/012-2-kings-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-kings/012-2-kings-013.adoc#v12-13-0[Próximo Capítulo &#62;]