include::./index.adoc[]

[[v12-25-0]]
=== The Second of Kings, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-25-1]]

^<<v12-25-1,1>>^ And it came about in the ninth year of his being king, in the tenth month on the tenth day of the month, that Neb·u·chad·nezʹzar the king of Babylon came, yes, he and all his military force, against Jerusalem and began camping against it and building against it a siege wall all around.

[[v12-25-2]]

^<<v12-25-2,2>>^ And the city came to be under siege until the eleventh year of King Zed·e·kiʹah.

[[v12-25-3]]

^<<v12-25-3,3>>^ On the ninth day of the &#91;fourth&#93; month^&#42;1^ the famine was severe in the city, and there proved to be no bread for the people of the land.

[NOTE]
====
. “Fourth month” in Jer 52:6; M, “month.”
====

[[v12-25-4]]

^<<v12-25-4,4>>^ And the city got to be breached, and all the men of war &#91;fled&#93;^&#42;1^ by night by the way of the gate between the double wall that is by the king’s garden, while the Chal·deʹans were all around against the city; and &#91;the king&#93;^&#42;2^ began to go in the direction of the Arʹa·bah.

[NOTE]
====
. “Fled,” in agreement with Sy and Jer 52:7; M omits.
. “He,” M; Vgc, “Zed­ekiah”; Sy, some Heb. mss and Jer 52:7, “they.”
====

[[v12-25-5]]

^<<v12-25-5,5>>^ And a military force of Chal·deʹans went chasing after the king, and they got to overtake him in the desert plains of Jerʹi·cho; and all his own military force was scattered from his side.

[[v12-25-6]]

^<<v12-25-6,6>>^ Then they seized the king and brought him up to the king of Babylon at Ribʹlah, that they might pronounce a judicial decision upon him.

[[v12-25-7]]

^<<v12-25-7,7>>^ And Zed·e·kiʹah’s sons they slaughtered before his eyes, and Zed·e·kiʹah’s eyes he blinded, after which he bound him with copper fetters and brought him to Babylon.

[[v12-25-8]]

^<<v12-25-8,8>>^ And in the fifth month on the seventh &#91;day&#93; of the month, that is to say, the nineteenth year of King Neb·u·chad·nezʹzar the king of Babylon, Neb·uʹzar·adʹan the chief of the bodyguard, the servant of the king of Babylon, came to Jerusalem.

[[v12-25-9]]

^<<v12-25-9,9>>^ And he proceeded to burn the house of Jehovah and the king’s house and all the houses of Jerusalem; and the house of every great man^&#42;1^ he burned with fire.

[NOTE]
====
. “Every great house,” according to a few mss.
====

[[v12-25-10]]

^<<v12-25-10,10>>^ And the walls of Jerusalem, all around, the entire military force of Chal·deʹans that were with the chief of the bodyguard pulled down.

[[v12-25-11]]

^<<v12-25-11,11>>^ And the rest of the people that were left behind in the city and the deserters that had gone over^&#42;1^ to the king of Babylon and the rest of the crowd Neb·uʹzar·adʹan the chief of the bodyguard took into exile.

[NOTE]
====
. Or, “that had deserted.” Lit., “that had fallen.”
====

[[v12-25-12]]

^<<v12-25-12,12>>^ And some of the lowly people of the land the chief of the bodyguard let remain as vinedressers and compulsory laborers.

[[v12-25-13]]

^<<v12-25-13,13>>^ And the pillars of copper that were in the house of Jehovah, and the carriages and the copper sea that were in the house of Jehovah, the Chal·deʹans broke in pieces and went carrying the copper of them to Babylon.

[[v12-25-14]]

^<<v12-25-14,14>>^ And the cans and the shovels and the extinguishers and the cups and all the utensils of copper with which they used to minister they took.

[[v12-25-15]]

^<<v12-25-15,15>>^ And the chief of the bodyguard took the fire holders and the bowls that were of genuine gold and those that were of genuine silver.

[[v12-25-16]]

^<<v12-25-16,16>>^ As for the two pillars, the one sea and the carriages that Solʹo·mon had made for the house of Jehovah, there happened to be no way to tell the weight of the copper of all these utensils.

[[v12-25-17]]

^<<v12-25-17,17>>^ Eighteen cubits was the height of each pillar, and the capital upon it was of copper; and the height of the capital was three^&#42;1^ cubits; and the network and the pomegranates all around upon the capital, the whole of it, was copper; and the second pillar had the same as these upon the network.

[NOTE]
====
. “Three,” M; TLagardian, “five,” as in Jer 52:22.
====

[[v12-25-18]]

^<<v12-25-18,18>>^ Furthermore, the chief of the bodyguard took Se·raiʹah the chief priest^&#42;1^ and Zeph·a·niʹah^&#42;2^ the second priest and three doorkeepers;

[NOTE]
====
. Lit., “the head priest.” Heb., ko·henʹ ha·roʼshʹ; LXXVg, “the first priest”; Sy, “the great priest.”
. Meaning “Jehovah Has Concealed [or, Treasured].” Heb., Tsephan·yaʹhu.
====

[[v12-25-19]]

^<<v12-25-19,19>>^ and from the city he took one court official that had a command over the men of war, and five men from those having access to the king^&#42;1^ that were found in the city; and the secretary of the chief of the army, the one mustering the people of the land, and sixty men of the people of the land that were to be found in the city;

[NOTE]
====
. Lit., “from those seeing the king’s face.”
====

[[v12-25-20]]

^<<v12-25-20,20>>^ and Neb·uʹzar·adʹan the chief of the bodyguard then took them and conducted them to the king of Babylon at Ribʹlah.

[[v12-25-21]]

^<<v12-25-21,21>>^ And the king of Babylon proceeded to strike them down and put them to death at Ribʹlah in the land of Haʹmath. Thus Judah went into exile from off its soil.

[[v12-25-22]]

^<<v12-25-22,22>>^ As for the people left behind in the land of Judah, whom Neb·u·chad·nezʹzar the king of Babylon had left behind, he now appointed over them Ged·a·liʹah^&#42;1^ the son of A·hiʹkam the son of Shaʹphan.

[NOTE]
====
. Meaning “Great Is Jehovah.” Heb., Gedhal·yaʹhu.
====

[[v12-25-23]]

^<<v12-25-23,23>>^ When all the chiefs of the military forces, they and their men, heard that the king of Babylon had appointed Ged·a·liʹah, they immediately came to Ged·a·liʹah at Mizʹpah, that is, Ishʹma·el the son of Neth·a·niʹah and Jo·haʹnan the son of Ka·reʹah and Se·raiʹah the son of Tan·huʹmeth the Ne·tophʹa·thite and Ja·az·a·niʹah^&#42;1^ the son of the Ma·acʹa·thite, they and their men.

[NOTE]
====
. “And Jaazaniah.” Heb., weYa·ʼazan·yaʹhu, meaning “Jehovah Gives Ear.”
====

[[v12-25-24]]

^<<v12-25-24,24>>^ Then Ged·a·liʹah swore to them and their men and said to them: “Do not be afraid of &#91;being&#93; servants to the Chal·deʹans. Dwell in the land and serve the king of Babylon, and it will go well with YOU.”

[[v12-25-25]]

^<<v12-25-25,25>>^ And it came about in the seventh month that Ishʹma·el the son of Neth·a·niʹah the son of E·lishʹa·ma of the royal offspring came, and also ten men with him, and they got to strike down Ged·a·liʹah, so that he died, and also the Jews and the Chal·deʹans that happened to be with him in Mizʹpah.

[[v12-25-26]]

^<<v12-25-26,26>>^ After that all the people, from small to great, and the chiefs of the military forces rose up and came into Egypt; for they had become afraid because of the Chal·deʹans.

[[v12-25-27]]

^<<v12-25-27,27>>^ And it came about in the thirty-seventh year of the exile of Je·hoiʹa·chin the king of Judah, in the twelfth month, on the twenty-seventh day of the month, that Eʹvil-merʹo·dach the king of Babylon, in the year of his becoming king, raised up the head of Je·hoiʹa·chin the king of Judah out of the house of detention;

[[v12-25-28]]

^<<v12-25-28,28>>^ and he began to speak good things with him, and then put his throne higher than the thrones of the kings that were with him in Babylon.

[[v12-25-29]]

^<<v12-25-29,29>>^ And he took off his prison garments; and he ate bread constantly before him all the days of his life.

[[v12-25-30]]

^<<v12-25-30,30>>^ As for his allowance, an allowance was constantly given him from the king, daily as due,^&#42;1^ all the days of his life.

[NOTE]
====
. Lit., “a thing of a day on its day.”
====

'''

xref:012-2-kings/012-2-kings-024.adoc#v12-24-0[&#60; Capítulo Anterior] | <<v12-25-0,Topo>> | xref:013-1-chronicles/013-1-chronicles-001.adoc#v13-1-0[Próximo Capítulo &#62;]