include::./index.adoc[]

[[v12-24-0]]
=== The Second of Kings, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-24-1]]

^<<v12-24-1,1>>^ In his days Neb·u·chad·nezʹzar the king of Babylon^&#42;1^ came up, and so Je·hoiʹa·kim became his servant for three years. However, he turned back and rebelled against him.

[NOTE]
====
. “Babylon,” LXXVg; MSy, “Babel.”
====

[[v12-24-2]]

^<<v12-24-2,2>>^ And Jehovah began to send against him marauder bands of Chal·deʹans and marauder bands of Syrians^&#42;1^ and marauder bands of Moʹab·ites and marauder bands of the sons of Amʹmon, and he kept sending them against Judah to destroy it, according to Jehovah’s word that he had spoken by means of his servants the prophets.

[NOTE]
====
. “Syrians,” MLXXVg; Sy, “Edomites.”
====

[[v12-24-3]]

^<<v12-24-3,3>>^ It was only by the order of Jehovah that it took place against Judah, to remove it from his sight for the sins of Ma·nasʹseh, according to all that he had done;

[[v12-24-4]]

^<<v12-24-4,4>>^ and also &#91;for&#93; the innocent blood that he had shed, so that he filled Jerusalem with innocent blood, and Jehovah did not consent to grant forgiveness.

[[v12-24-5]]

^<<v12-24-5,5>>^ As for the rest of the affairs of Je·hoiʹa·kim and all that he did, are they not written in the book of the affairs of the days of the kings of Judah?

[[v12-24-6]]

^<<v12-24-6,6>>^ Finally Je·hoiʹa·kim lay down with his forefathers, and Je·hoiʹa·chin his son began to reign in place of him.

[[v12-24-7]]

^<<v12-24-7,7>>^ And never again did the king of Egypt come out from his land, for the king of Babylon had taken all that happened to belong to the king of Egypt from the torrent valley of Egypt up to the river Eu·phraʹtes.

[[v12-24-8]]

^<<v12-24-8,8>>^ Eighteen years old was Je·hoiʹa·chin when he began to reign, and for three months he reigned in Jerusalem. And his mother’s name was Ne·hushʹta the daughter of El·naʹthan of Jerusalem.

[[v12-24-9]]

^<<v12-24-9,9>>^ And he continued to do what was bad in Jehovah’s eyes, according to all that his father had done.

[[v12-24-10]]

^<<v12-24-10,10>>^ During that time the servants of Neb·u·chad·nezʹzar the king of Babylon came up to Jerusalem, so that the city came under siege.

[[v12-24-11]]

^<<v12-24-11,11>>^ And Neb·u·chad·nezʹzar the king of Babylon proceeded to come against the city, while his servants were laying siege against it.

[[v12-24-12]]

^<<v12-24-12,12>>^ At length Je·hoiʹa·chin the king of Judah went out to the king of Babylon, he with his mother and his servants and his princes and his court officials; and the king of Babylon got to take him in the eighth year of his being king.

[[v12-24-13]]

^<<v12-24-13,13>>^ Then he brought out from there all the treasures of the house of Jehovah and the treasures of the king’s house, and went on to cut to pieces all the gold utensils that Solʹo·mon the king of Israel had made in the temple of Jehovah, just as Jehovah had spoken.

[[v12-24-14]]

^<<v12-24-14,14>>^ And he took into exile all Jerusalem and all the princes and all the valiant, mighty men—ten thousand he was taking into exile—and also every craftsman and builder of bulwarks. No one had been left behind except the lowly class of the people of the land.

[[v12-24-15]]

^<<v12-24-15,15>>^ Thus he took Je·hoiʹa·chin into exile to Babylon; and the king’s mother and the king’s wives and his court officials and the foremost men of the land he led away as exiled people from Jerusalem to Babylon.

[[v12-24-16]]

^<<v12-24-16,16>>^ As for all the valiant men, seven thousand, and the craftsmen and the builders of bulwarks, a thousand, all the mighty men carrying on war, the king of Babylon proceeded to bring them as exiled people to Babylon.

[[v12-24-17]]

^<<v12-24-17,17>>^ Further, the king of Babylon made Mat·ta·niʹah his uncle king in place of him. Then he changed his name to Zed·e·kiʹah.^&#42;1^

[NOTE]
====
. Or, “his name was changed to Zedekiah.”
====

[[v12-24-18]]

^<<v12-24-18,18>>^ Twenty-one years old was Zed·e·kiʹah^&#42;1^ when he began to reign, and for eleven years he reigned in Jerusalem. And his mother’s name was Ha·muʹtal the daughter of Jeremiah^&#42;2^ from Libʹnah.

[NOTE]
====
. Meaning “Jehovah Is Righteousness.” Heb., Tsidh·qi·yaʹhu.
. See Jer 1:1 ftn, “Jeremiah.”
====

[[v12-24-19]]

^<<v12-24-19,19>>^ And he continued to do what was bad in Jehovah’s eyes, according to all that Je·hoiʹa·kim had done.

[[v12-24-20]]

^<<v12-24-20,20>>^ For on account of the anger of Jehovah it took place in Jerusalem and in Judah, until he had cast them out of his sight. And Zed·e·kiʹah began to rebel against the king of Babylon.

'''

xref:012-2-kings/012-2-kings-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-kings/012-2-kings-025.adoc#v12-25-0[Próximo Capítulo &#62;]