include::./index.adoc[]

[[v12-5-0]]
=== The Second of Kings, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-5-1]]

^<<v12-5-1,1>>^ Now a certain Naʹa·man, the chief of the army of the king of Syria, had become a great man before his lord^&#42;1^ and held in esteem,^&#42;2^ because it was by him that Jehovah had given salvation^&#42;3^ to Syria; and the man himself had proved to be a valiant, mighty man, though a leper.^&#42;4^

[NOTE]
====
. “His lord (master).” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence.
. Lit., “lifted up of face.”
. Or, “rescue; deliverance.”
. Or, “struck with skin disease.” The Biblical term for leprosy includes what is today medically called Hansen’s disease.
====

[[v12-5-2]]

^<<v12-5-2,2>>^ And the Syrians, for their part, had gone out as marauder bands, and they got to take captive from the land of Israel a little girl, and she came to be before Naʹa·man’s wife.

[[v12-5-3]]

^<<v12-5-3,3>>^ In time she said to her mistress: “If only my lord were before the prophet that is in Sa·marʹi·a! In that case he would recover him from his leprosy.”

[[v12-5-4]]

^<<v12-5-4,4>>^ Subsequently someone came and reported to his lord, saying: “It was like this and that that the girl spoke who is from the land of Israel.”

[[v12-5-5]]

^<<v12-5-5,5>>^ Then the king of Syria said: “Get going! Come, and let me send a letter to the king of Israel.” So he proceeded to go and take in his hand ten talents of silver and six thousand pieces of gold and ten changes of garments.

[[v12-5-6]]

^<<v12-5-6,6>>^ And he came bringing the letter to the king of Israel, saying: “And now at the same time that this letter comes to you, here I do send to you Naʹa·man my servant, that you may recover him from his leprosy.”

[[v12-5-7]]

^<<v12-5-7,7>>^ And it came about that as soon as the king of Israel read the letter, he immediately ripped his garments apart and said: “Am I God, to put to death and to preserve alive? For this person is sending to me to recover a man from his leprosy; for just take note, please, YOU men, and see how he is seeking a quarrel with me.”

[[v12-5-8]]

^<<v12-5-8,8>>^ And it came about that, as soon as E·liʹsha the man of the &#91;true&#93; God heard that the king of Israel had ripped his garments apart, he at once sent to the king, saying: “Why did you rip your garments apart? Let him come, please, to me that he may know that there exists a prophet in Israel.”

[[v12-5-9]]

^<<v12-5-9,9>>^ So Naʹa·man came with his horses and his war chariots and stood at the entrance of the house of E·liʹsha.

[[v12-5-10]]

^<<v12-5-10,10>>^ However, E·liʹsha sent a messenger to him, saying: “Going there,^&#42;1^ you must bathe seven times in the Jordan that your flesh may come back to you; and be clean.”

[NOTE]
====
. Or, “Let there be a going.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v12-5-11]]

^<<v12-5-11,11>>^ At this Naʹa·man grew indignant and began to go away and say: “Here I had said &#91;to myself&#93;, ‘To me he will come out all the way and will certainly stand and call upon the name of Jehovah his God and move his hand to and fro over the place and actually give the leper recovery.’

[[v12-5-12]]

^<<v12-5-12,12>>^ Are not the A·baʹnah^&#42;1^ and the Pharʹpar, the rivers of Damascus, better than all the waters of Israel? Can I not bathe in them and certainly be clean?” With that he turned and went away in a rage.

[NOTE]
====
. “Abanah,” MLXXVg; MmarginTSy, “Amanah.”
====

[[v12-5-13]]

^<<v12-5-13,13>>^ His servants now approached and spoke to him and said: “My father, had it been a great thing that the prophet himself had spoken to you, would you not do it? How much more, then, since he said to you, ‘Bathe and be clean’?”

[[v12-5-14]]

^<<v12-5-14,14>>^ At that he went down and began to plunge^&#42;1^ into the Jordan seven times according to the word of the man of the &#91;true&#93; God; after which his flesh came back like the flesh of a little boy and he became clean.

[NOTE]
====
. Or, “and began to dive (dip himself).” Heb., wai·yit·bolʹ; Gr., e·ba·ptiʹsa·to (from ba·ptiʹzo, “baptize”).
====

[[v12-5-15]]

^<<v12-5-15,15>>^ Then he went back to the man of the &#91;true&#93; God, he with all his camp, and came and stood before him and said: “Here, now, I certainly know that there is no God anywhere in the earth but in Israel. And now accept, please, a blessing gift from your servant.”

[[v12-5-16]]

^<<v12-5-16,16>>^ However, he said: “As Jehovah before whom I do stand^&#42;1^ is living, I will not accept it.” And he began to urge him to accept it, but he kept refusing.

[NOTE]
====
. Or, “upon whom I attend.”
====

[[v12-5-17]]

^<<v12-5-17,17>>^ Finally Naʹa·man said: “If not, please, let there be given to your servant some ground, the load of a pair of mules; because your servant will no more render up a burnt offering or a sacrifice to any other gods but to Jehovah.

[[v12-5-18]]

^<<v12-5-18,18>>^ In this thing may Jehovah forgive your servant: When my lord comes into the house of Rimʹmon to bow down there, and he is supporting himself upon my hand, and I have to bow down at the house of Rimʹmon, when I bow down at the house of Rimʹmon may Jehovah, please, forgive your servant in this respect.”

[[v12-5-19]]

^<<v12-5-19,19>>^ At this he said to him: “Go in peace.” Accordingly he went away from him for a good stretch of the land.

[[v12-5-20]]

^<<v12-5-20,20>>^ Then Ge·haʹzi the attendant of E·liʹsha the man of the &#91;true&#93; God said: “Here my master^&#42;1^ has spared Naʹa·man this Syrian by not accepting from his hand what he brought. As Jehovah is living, I will run after him and take something from him.”

[NOTE]
====
. Or, “my lord.” Heb., ʼadho·niʹ.
====

[[v12-5-21]]

^<<v12-5-21,21>>^ And Ge·haʹzi went chasing after Naʹa·man. When Naʹa·man saw someone running after him, he at once got down from his chariot to meet him and then said: “Is all well?”

[[v12-5-22]]

^<<v12-5-22,22>>^ To this he said: “All is well. My master himself has sent me, saying, ‘Look! Just now there have come to me two young men from the mountainous region of Eʹphra·im from the sons of the prophets. Do give them, please, a talent^&#42;1^ of silver and two changes of garments.’”

[NOTE]
====
. A talent weighed 34.2 kg (1101 oz t).
====

[[v12-5-23]]

^<<v12-5-23,23>>^ At that Naʹa·man said: “Go on, take two talents.” And he kept urging him and finally bound up two talents of silver in two bags, with two changes of garments, and gave them to two of his attendants, that they might carry them before him.

[[v12-5-24]]

^<<v12-5-24,24>>^ When he came to Oʹphel,^&#42;1^ he immediately took them from their hand and deposited them in the house and sent the men away. So off they went.

[NOTE]
====
. Meaning “Bulge; Swelling; Projection; Eminence.” Located in Samaria.
====

[[v12-5-25]]

^<<v12-5-25,25>>^ And he himself came in and then stood by his master. E·liʹsha now said to him: “Where &#91;did you come&#93; from, Ge·haʹzi?” But he said: “Your servant did not go anywhere at all.”

[[v12-5-26]]

^<<v12-5-26,26>>^ At that he said to him: “Did not my heart itself go along just as the man turned &#91;to get down&#93; off his chariot to meet you? Is it a time to accept silver or to accept garments or olive groves or vineyards or sheep or cattle or menservants or maidservants?

[[v12-5-27]]

^<<v12-5-27,27>>^ So the leprosy of Naʹa·man will stick to you and your offspring to time indefinite.” Immediately he went out from before him, a leper white as snow.

'''

xref:012-2-kings/012-2-kings-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-kings/012-2-kings-006.adoc#v12-6-0[Próximo Capítulo &#62;]