include::./index.adoc[]

[[v12-20-0]]
=== The Second of Kings, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-20-1]]

^<<v12-20-1,1>>^ In those days Hez·e·kiʹah got sick to the point of dying. Accordingly Isaiah the son of Aʹmoz the prophet came in to him and said to him: “This is what Jehovah has said, ‘Give commands to your household, for you yourself will indeed die and will not live.’”

[[v12-20-2]]

^<<v12-20-2,2>>^ At that he turned his face to the wall and began to pray to Jehovah, saying:

[[v12-20-3]]

^<<v12-20-3,3>>^ “I beseech you, O Jehovah, remember, please, how I have walked before you in truthfulness and with a complete heart, and what was good in your eyes I have done.” And Hez·e·kiʹah began to weep profusely.^&#42;1^

[NOTE]
====
. Lit., “with a great weeping.”
====

[[v12-20-4]]

^<<v12-20-4,4>>^ And it came about that Isaiah himself had not yet gone out to the middle court^&#42;1^ when Jehovah’s word itself came to him, saying:

[NOTE]
====
. “Court,” MmarginLXXSyVg; M, “city.”
====

[[v12-20-5]]

^<<v12-20-5,5>>^ “Go back, and you must say to Hez·e·kiʹah the leader of my people, ‘This is what Jehovah the God of David your forefather has said: “I have heard your prayer. I have seen your tears. Here I am healing you. On the third day you will go up to the house of Jehovah.

[[v12-20-6]]

^<<v12-20-6,6>>^ And I shall certainly add fifteen years to your days, and out of the palm of the king of As·syrʹi·a I shall deliver you and this city, and I will defend this city for my own sake and for the sake of David my servant.”’”

[[v12-20-7]]

^<<v12-20-7,7>>^ And Isaiah went on to say: “YOU men, take a cake of pressed dried figs.” So they took and put it upon the boil, after which he gradually revived.

[[v12-20-8]]

^<<v12-20-8,8>>^ Meantime, Hez·e·kiʹah said to Isaiah: “What is the sign that Jehovah will heal me and I shall certainly go up on the third day to the house of Jehovah?”

[[v12-20-9]]

^<<v12-20-9,9>>^ To this Isaiah said: “This is the sign for you from Jehovah that Jehovah will perform the word that he has spoken: Shall the shadow actually go forward ten steps &#91;of the stairs&#93; or should it go back ten steps?”

[[v12-20-10]]

^<<v12-20-10,10>>^ Then Hez·e·kiʹah^&#42;1^ said: “It is an easy thing for the shadow to extend itself ten steps, but not that the shadow should go backward ten steps.”

[NOTE]
====
. Meaning “Jehovah Strengthens.” Heb., Yechiz·qi·yaʹhu. Compare 16:20 ftn.
====

[[v12-20-11]]

^<<v12-20-11,11>>^ At that Isaiah the prophet began to call out to Jehovah; and he made the shadow that had gone down gradually go back on the steps, that is, on the steps &#91;of the stairs&#93; of Aʹhaz, ten steps backward.

[[v12-20-12]]

^<<v12-20-12,12>>^ At that time Be·roʹdach-balʹa·dan the son of Balʹa·dan the king of Babylon^&#42;1^ sent letters and a gift to Hez·e·kiʹah;^&#42;2^ for he had heard that Hez·e·kiʹah had been sick.

[NOTE]
====
. “The king of Babylon,” LXX; Heb., me·lekh-Ba·velʹ, “the king of Babel”; Lat., rex Ba·by·lo·ni·oʹrum, “the king of the Babylonians.” The first occurrence of this expression.
. “Hezekiah.” Heb., Chiz·qi·yaʹhu, the same spelling as in 16:20.
====

[[v12-20-13]]

^<<v12-20-13,13>>^ And Hez·e·kiʹah proceeded to listen to them^&#42;1^ and show them all his treasure-house, the silver and the gold and the balsam oil and the good oil and his armory and all that was to be found in his treasures. There proved to be nothing that Hez·e·kiʹah did not show them in his own house and in all his dominion.

[NOTE]
====
. “Listen to them,” M; LXXSyVg and Isa 39:2, “rejoice over them.”
====

[[v12-20-14]]

^<<v12-20-14,14>>^ After that Isaiah the prophet came in to King Hez·e·kiʹah and said to him: “What did these men say and from where did they proceed to come to you?” So Hez·e·kiʹah said: “From a distant land they came, from Babylon.”

[[v12-20-15]]

^<<v12-20-15,15>>^ And he went on to say: “What did they see in your house?” To this Hez·e·kiʹah said: “Everything that is in my house they saw. There proved to be nothing that I did not show them in my treasures.”

[[v12-20-16]]

^<<v12-20-16,16>>^ Isaiah now said to Hez·e·kiʹah: “Hear the word of Jehovah,

[[v12-20-17]]

^<<v12-20-17,17>>^ ‘“Look! Days are coming, and all that is in your own house and that your forefathers have stored up down to this day will actually be carried to Babylon. Nothing will be left,” Jehovah has said.

[[v12-20-18]]

^<<v12-20-18,18>>^ “And some of your own sons that will come forth from you to whom you will become father will themselves be taken and actually become court officials in the palace^&#42;1^ of the king of Babylon.”’”

[NOTE]
====
. “In the palace of.” Heb., beheh·khalʹ, “in the habitation (dwelling; temple) of”; Lat., pa·laʹti·o. Compare 1Sa 1:9 ftn, “Temple”; Mt 23:16 ftn.
====

[[v12-20-19]]

^<<v12-20-19,19>>^ At that Hez·e·kiʹah said to Isaiah: “The word of Jehovah that you have spoken is good.” And he went on to say: “Is it not so, if peace and truth themselves will continue in my own days?”

[[v12-20-20]]

^<<v12-20-20,20>>^ As for the rest of the affairs of Hez·e·kiʹah and all his mightiness and how he made the pool and the conduit and then brought the water into the city, are they not written in the book of the affairs of the days of the kings of Judah?

[[v12-20-21]]

^<<v12-20-21,21>>^ Finally Hez·e·kiʹah lay down with his forefathers; and Ma·nasʹseh his son began to reign in place of him.

'''

xref:012-2-kings/012-2-kings-019.adoc#v12-19-0[&#60; Capítulo Anterior] | <<v12-20-0,Topo>> | xref:012-2-kings/012-2-kings-021.adoc#v12-21-0[Próximo Capítulo &#62;]