include::./index.adoc[]

[[v12-3-0]]
=== The Second of Kings, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-3-1]]

^<<v12-3-1,1>>^ As for Je·hoʹram the son of Aʹhab, he became king over Israel in Sa·marʹi·a in the eighteenth year of Je·hoshʹa·phat the king of Judah, and he continued to reign for twelve years.

[[v12-3-2]]

^<<v12-3-2,2>>^ And he kept on doing what was bad in Jehovah’s eyes, only not like his father or like his mother, but he removed the sacred pillar of Baʹal that his father had made.

[[v12-3-3]]

^<<v12-3-3,3>>^ Only he stuck to the sins of Jer·o·boʹam the son of Neʹbat, with which he caused Israel to sin. He did not depart from them.

[[v12-3-4]]

^<<v12-3-4,4>>^ As regards Meʹsha the king of Moʹab, he became a sheep raiser, and he paid to the king of Israel a hundred thousand lambs and a hundred thousand unshorn male sheep.^&#42;1^

[NOTE]
====
. Or, “the wool of a hundred thousand male sheep.”
====

[[v12-3-5]]

^<<v12-3-5,5>>^ And it came about that as soon as Aʹhab died, the king of Moʹab began to revolt against the king of Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Consequently King Je·hoʹram went out on that day from Sa·marʹi·a and mustered all Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ He went farther and now sent to Je·hoshʹa·phat the king of Judah, saying: “The king of Moʹab himself has revolted against me. Will you go with me to Moʹab in war?” To this he said: “I shall go. I am the same as you are; my people are the same as your people; my horses are the same as your horses.”

[[v12-3-8]]

^<<v12-3-8,8>>^ And he went on to say: “By which particular way shall we go up?” So he said: “By the way of the wilderness of Eʹdom.”

[[v12-3-9]]

^<<v12-3-9,9>>^ And the king of Israel and the king of Judah and the king of Eʹdom proceeded to go, and they kept going their way around for seven days, and there proved to be no water for the camp and for the domestic animals that were following their steps.

[[v12-3-10]]

^<<v12-3-10,10>>^ At length the king of Israel said: “How unfortunate that Jehovah has called these three kings to give them into the hand of Moʹab!”

[[v12-3-11]]

^<<v12-3-11,11>>^ At that Je·hoshʹa·phat said: “Is there not here a prophet of Jehovah? Then let us inquire of Jehovah through him.” So one of the servants of the king of Israel answered and said: “There is here E·liʹsha the son of Shaʹphat, who poured out water upon the hands of E·liʹjah.”

[[v12-3-12]]

^<<v12-3-12,12>>^ Then Je·hoshʹa·phat said: “The word of Jehovah exists with him.” Accordingly the king of Israel and Je·hoshʹa·phat and the king of Eʹdom went down to him.

[[v12-3-13]]

^<<v12-3-13,13>>^ And E·liʹsha proceeded to say to the king of Israel: “What do I have to do with you?^&#42;1^ Go to the prophets of your father and to the prophets of your mother.” But the king of Israel said to him: “No, for Jehovah has called these three kings to give them into the hand of Moʹab.”

[NOTE]
====
. Lit., “What [is there] to me and to you?” A Heb. idiom; a repellent question indicating objection. See App 7B.
====

[[v12-3-14]]

^<<v12-3-14,14>>^ To this E·liʹsha said: “As Jehovah of armies before whom I do stand^&#42;1^ is living, if it were not that it is the face of Je·hoshʹa·phat the king of Judah for which I am having consideration, I would not look at you or see you.

[NOTE]
====
. Or, “upon whom I do attend.”
====

[[v12-3-15]]

^<<v12-3-15,15>>^ And now YOU men fetch me a string-instrument player.” And it occurred that, as soon as the string-instrument player played, the hand of Jehovah came to be upon him.

[[v12-3-16]]

^<<v12-3-16,16>>^ And he went on to say: “This is what Jehovah has said, ‘Let there be a making^&#42;1^ of this torrent valley full of ditches;^&#42;2^

[NOTE]
====
. “Let there be a making.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. Lit., “ditches, ditches.”
====

[[v12-3-17]]

^<<v12-3-17,17>>^ for this is what Jehovah has said: “YOU men will not see a wind, and YOU will not see a downpour; yet that torrent valley will be filled with water, and YOU men will certainly drink &#91;from it&#93;, YOU and YOUR livestock and YOUR domestic animals.”’

[[v12-3-18]]

^<<v12-3-18,18>>^ And this will indeed be a trivial thing in the eyes of Jehovah, and he will certainly give Moʹab into YOUR hand.

[[v12-3-19]]

^<<v12-3-19,19>>^ And YOU must strike down every fortified city and every choice city, and every good tree YOU should fell, and all the springs of water YOU should stop up, and every good tract of land YOU should mar with stones.”

[[v12-3-20]]

^<<v12-3-20,20>>^ And it came about in the morning, at the time of the going up of the grain offering, that, look! water was coming from the direction of Eʹdom, and the land came to be filled with the water.

[[v12-3-21]]

^<<v12-3-21,21>>^ As regards all the Moʹab·ites, they heard that the kings had come up to fight against them. Consequently they called together &#91;men&#93; from as many as were girding on a belt and upward, and they began standing at the boundary.

[[v12-3-22]]

^<<v12-3-22,22>>^ When they got up early in the morning, the sun itself flashed upon the water, so that the Moʹab·ites from the opposite side saw the water red like blood.

[[v12-3-23]]

^<<v12-3-23,23>>^ And they began to say: “This is blood! The kings have unquestionably been put to the sword, and they went striking one another down. So now, to the spoil, O Moʹab!”

[[v12-3-24]]

^<<v12-3-24,24>>^ When they came into the camp of Israel, the Israelites immediately rose up and began striking the Moʹab·ites down so that they took to flight from before them. Hence they came into Moʹab,^&#42;1^ striking the Moʹab·ites down as they came.^&#42;2^

[NOTE]
====
. Lit., “it.”
. “Hence they came to Moab, striking . . . as they came,” by an emendation of M in agreement with LXX.
====

[[v12-3-25]]

^<<v12-3-25,25>>^ And the cities they went throwing down, and, as for every good tract of land, they would pitch each one his stone and actually fill it; and every spring of water they would stop up, and every good tree they would fell, until they left only the stones of Kir-harʹe·seth remaining in it; and the slingers began going around it and striking it down.

[[v12-3-26]]

^<<v12-3-26,26>>^ When the king of Moʹab saw that the battle had proved too strong for him, he at once took with him seven hundred men drawing sword to break through to the king of Eʹdom; but they were not able to.

[[v12-3-27]]

^<<v12-3-27,27>>^ Finally he took his firstborn son who was going to reign in place of him and offered him up as a burnt sacrifice upon the wall. And there came to be great indignation against Israel, so that they pulled away from against him and returned to their land.

'''

xref:012-2-kings/012-2-kings-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-kings/012-2-kings-004.adoc#v12-4-0[Próximo Capítulo &#62;]