include::./index.adoc[]

[[v12-23-0]]
=== The Second of Kings, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v12-23-1]]

^<<v12-23-1,1>>^ Then the king sent and they gathered together to him all the older men of Judah and Jerusalem.

[[v12-23-2]]

^<<v12-23-2,2>>^ After that the king went up to the house of Jehovah, and also all the men of Judah and all the inhabitants of Jerusalem with him, and also the priests and the prophets and all the people, from small to great; and he began to read in their ears all the words of the book of the covenant that had been found in the house of Jehovah.

[[v12-23-3]]

^<<v12-23-3,3>>^ And the king kept standing by the pillar and now concluded the covenant before Jehovah, to walk after Jehovah and to keep his commandments and his testimonies^&#42;1^ and his statutes with all the heart and with all the soul by carrying out the words of this covenant that were written in this book. Accordingly all the people took their stand in the covenant.

[NOTE]
====
. Or, “reminders.”
====

[[v12-23-4]]

^<<v12-23-4,4>>^ And the king went on to command Hil·kiʹah the high priest and the priests of the second rank and the doorkeepers to bring out from the temple of Jehovah all the utensils made for Baʹal and for the sacred pole and for all the army of the heavens. Then he burned them outside Jerusalem on the terraces of Kidʹron, and he brought the dust of them to Bethʹel.

[[v12-23-5]]

^<<v12-23-5,5>>^ And he put out of business the foreign-god priests,^&#42;1^ whom the kings of Judah had put in that they might make sacrificial smoke on the high places in the cities of Judah and the surroundings of Jerusalem, and also those making sacrificial smoke to Baʹal, to the sun and to the moon and to the constellations of the zodiac and to all the army of the heavens.

[NOTE]
====
. “The foreign-god priests.” Heb., hak·kema·rimʹ.
====

[[v12-23-6]]

^<<v12-23-6,6>>^ Furthermore, he brought out the sacred pole from the house of Jehovah to the outskirts of Jerusalem, to the torrent valley of Kidʹron, and burned it in the torrent valley of Kidʹron and ground it to dust and cast its dust upon the burial place of the sons of the people.

[[v12-23-7]]

^<<v12-23-7,7>>^ Further, he pulled down the houses of the male temple prostitutes that were in the house of Jehovah, where the women were weaving tent shrines for the sacred pole.

[[v12-23-8]]

^<<v12-23-8,8>>^ Then he brought all the priests from the cities of Judah, that he might make unfit for worship the high places where the priests had made sacrificial smoke, from Geʹba as far as Beʹer-sheʹba; and he pulled down the high places of the gates^&#42;1^ that were at the entrance of the gate of Joshua, the chief of the city, which was at the left as a person came into^&#42;2^ the gate of the city.

[NOTE]
====
. Possibly, “goat-shaped demons,” by a slight change in M. See KB, p. 926.
. “As a person (man) came into,” LXXL.
====

[[v12-23-9]]

^<<v12-23-9,9>>^ Only the priests of the high places would not come up to the altar of Jehovah in Jerusalem, but they ate unfermented cakes in among their brothers.

[[v12-23-10]]

^<<v12-23-10,10>>^ And he made unfit for worship Toʹpheth,^&#42;1^ which is in the valley of the sons of Hinʹnom,^&#42;2^ that no one might make his son or his daughter pass through the fire to Moʹlech.

[NOTE]
====
. “Topheth,” M(Heb., hat·Toʹpheth)Vg; the first occurrence of this name.
. According to M; MmarginLXXSyVg and many Heb. mss, “the valley of the son of Hinnom.” See App 4C.
====

[[v12-23-11]]

^<<v12-23-11,11>>^ Further, he caused the horses that the kings of Judah had given to the sun to cease from entering the house of Jehovah by the dining room of Naʹthan-melʹech the court official, which was in the porticoes; and the chariots of the sun he burned in the fire.

[[v12-23-12]]

^<<v12-23-12,12>>^ And the altars that were upon the roof of the roof chamber of Aʹhaz that the kings of Judah had made, and the altars that Ma·nasʹseh had made in two courtyards of the house of Jehovah,^&#42;1^ the king pulled down, after which he crushed them there,^&#42;2^ and he cast their dust into the torrent valley of Kidʹron.

[NOTE]
====
. See App 1C §7.
. “He crushed them there,” by a correction of M.
====

[[v12-23-13]]

^<<v12-23-13,13>>^ And the high places that were in front of Jerusalem, that were to the right^&#42;1^ of the Mount of Ruination,^&#42;2^ that Solʹo·mon the king of Israel had built to Ashʹto·reth the disgusting thing of the Si·doʹni·ans and to Cheʹmosh the disgusting thing of Moʹab and to Milʹcom the detestable thing of the sons of Amʹmon, the king made unfit for worship.

[NOTE]
====
. That is, south, when one faces east.
. “The Mount of Ruination.” Heb., leHar-ham·Mash·chithʹ. That is, the Mount of Olives, particularly the southern extremity known also as the Mount of Offense.
====

[[v12-23-14]]

^<<v12-23-14,14>>^ And he broke the sacred pillars to pieces and went on to cut down the sacred poles and to fill their places with human bones.

[[v12-23-15]]

^<<v12-23-15,15>>^ And also the altar that was in Bethʹel, the high place that Jer·o·boʹam the son of Neʹbat, who caused Israel to sin, had made, even that altar and the high place he pulled down. Then he burned the high place; he ground &#91;it&#93; to dust^&#42;1^ and burned the sacred pole.

[NOTE]
====
. “He pulled down and ground its stones and reduced [them] to dust,” LXX.
====

[[v12-23-16]]

^<<v12-23-16,16>>^ When Jo·siʹah^&#42;1^ turned, he got to see the burial places that were there in the mountain. So he sent and took the bones from the burial places and burned them upon the altar, that he might make it unfit for worship, according to Jehovah’s^&#42;2^ word that the man of the &#91;true&#93; God had proclaimed, who proclaimed these things.

[NOTE]
====
. “Josiah.” Heb., Yoʼ·shi·yaʹhu, as in 22:1.
. See App 1C §7.
====

[[v12-23-17]]

^<<v12-23-17,17>>^ Then he said: “What is the gravestone over there that I am seeing?” At this the men of the city said to him: “It is the burial place of the man of the &#91;true&#93; God that came from Judah and proceeded to proclaim these things that you have done against the altar of Bethʹel.”

[[v12-23-18]]

^<<v12-23-18,18>>^ So he said: “Let him rest. Do not let anyone disturb his bones.” Consequently they let his bones alone along with the bones of the prophet that had come from Sa·marʹi·a.

[[v12-23-19]]

^<<v12-23-19,19>>^ And also all the houses of the high places that were in the cities of Sa·marʹi·a that the kings of Israel had built to cause offense^&#42;1^ Jo·siʹah removed, and he went on to do to them according to all the doings that he had done at Bethʹel.

[NOTE]
====
. “To cause offense,” M; LXXSyVg, “to offend Jehovah.”
====

[[v12-23-20]]

^<<v12-23-20,20>>^ Accordingly he sacrificed all the priests of the high places that were there upon the altars and burned human bones upon them. After that he returned to Jerusalem.

[[v12-23-21]]

^<<v12-23-21,21>>^ The king now commanded all the people, saying: “Hold a passover to Jehovah^&#42;1^ YOUR God according to what is written in this book of the covenant.”

[NOTE]
====
. See App 1C §7.
====

[[v12-23-22]]

^<<v12-23-22,22>>^ For no passover like this had been held from the days of the judges that had judged Israel, nor all the days of the kings of Israel and the kings of Judah.

[[v12-23-23]]

^<<v12-23-23,23>>^ But in the eighteenth year of King Jo·siʹah this passover was held to Jehovah^&#42;1^ in Jerusalem.

[NOTE]
====
. See App 1C §7.
====

[[v12-23-24]]

^<<v12-23-24,24>>^ And also the spirit mediums and the professional foretellers of events and the teraphim^&#42;1^ and the dungy idols and all the disgusting things that had appeared in the land of Judah and in Jerusalem Jo·siʹah cleared out, in order that he might actually carry out the words of the law that were written in the book that Hil·kiʹah the priest had found at the house of Jehovah.

[NOTE]
====
. “Teraphim,” MLXX; Sy, “idols”; Vg, “figures of idols.” See Ge 31:19 ftn.
====

[[v12-23-25]]

^<<v12-23-25,25>>^ And like him there did not prove to be a king prior to him who returned to Jehovah^&#42;1^ with all his heart and with all his soul and with all his vital force, according to all the law of Moses; neither after him has there risen up one like him.

[NOTE]
====
. See App 1C §7.
====

[[v12-23-26]]

^<<v12-23-26,26>>^ Nevertheless, Jehovah^&#42;1^ did not turn back from the great burning of his anger, with which his anger burned against Judah over all the offensive things with which Ma·nasʹseh had made them offend.

[NOTE]
====
. See App 1C §7.
====

[[v12-23-27]]

^<<v12-23-27,27>>^ But Jehovah^&#42;1^ said: “Judah, too, I shall remove from my sight, just as I have removed Israel; and I shall certainly reject this city that I have chosen, even Jerusalem, and the house of which I have said, ‘My name will continue there.’”

[NOTE]
====
. See App 1C §7.
====

[[v12-23-28]]

^<<v12-23-28,28>>^ As for the rest of the affairs of Jo·siʹah and all that he did, are they not written in the book of the affairs of the days of the kings of Judah?

[[v12-23-29]]

^<<v12-23-29,29>>^ In his days Pharʹaoh Neʹchoh^&#42;1^ the king of Egypt came up to the king of As·syrʹi·a^&#42;2^ by the river Eu·phraʹtes, and King Jo·siʹah proceeded to go to meet him; but he put him to death at Me·gidʹdo as soon as he saw him.

[NOTE]
====
. Or, “Nekaw (Nekau).”
. That is, the Babylonian conqueror of Assyria.
====

[[v12-23-30]]

^<<v12-23-30,30>>^ So his servants conveyed him dead in a chariot from Me·gidʹdo and brought him to Jerusalem and buried him in his grave. Then the people of the land took Je·hoʹa·haz the son of Jo·siʹah and anointed him and made him king in place of his father.

[[v12-23-31]]

^<<v12-23-31,31>>^ Twenty-three years old was Je·hoʹa·haz when he began to reign, and for three months he reigned in Jerusalem. And his mother’s name was Ha·muʹtal the daughter of Jeremiah from Libʹnah.

[[v12-23-32]]

^<<v12-23-32,32>>^ And he began to do what was bad in Jehovah’s eyes, according to all that forefathers of his had done.

[[v12-23-33]]

^<<v12-23-33,33>>^ And Pharʹaoh Neʹchoh got to put him in bonds at Ribʹlah in the land of Haʹmath, to keep him from reigning^&#42;1^ in Jerusalem, and then imposed a fine upon the land of a hundred silver talents^&#42;2^ and a gold talent.

[NOTE]
====
. According to MmarginTLXXVg; MSy, “while he was reigning.”
. See App 8A.
====

[[v12-23-34]]

^<<v12-23-34,34>>^ Furthermore, Pharʹaoh Neʹchoh made E·liʹa·kim the son of Jo·siʹah king in place of Jo·siʹah his father and changed his name to Je·hoiʹa·kim; and Je·hoʹa·haz he took and then brought to Egypt, where he eventually died.

[[v12-23-35]]

^<<v12-23-35,35>>^ And the silver and the gold Je·hoiʹa·kim gave to Pharʹaoh. Only he taxed the land, to give the silver at the order of Pharʹaoh. According to each one’s individual tax rate he exacted the silver and the gold from the people of the land, to give it to Pharʹaoh Neʹchoh.

[[v12-23-36]]

^<<v12-23-36,36>>^ Twenty-five years old was Je·hoiʹa·kim when he began to reign, and for eleven years he reigned in Jerusalem. And his mother’s name was Ze·biʹdah the daughter of Pe·daiʹah from Ruʹmah.

[[v12-23-37]]

^<<v12-23-37,37>>^ And he continued to do what was bad in Jehovah’s eyes, according to all that forefathers of his had done.

'''

xref:012-2-kings/012-2-kings-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-kings/012-2-kings-024.adoc#v12-24-0[Próximo Capítulo &#62;]