include::./index.adoc[]

[[v9-23-0]]
=== The First of Samuel, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-23-1]]

^<<v9-23-1,1>>^ In time they came reporting to David, saying: “Here the Phi·lisʹtines are warring against Keiʹlah, and they are pillaging the threshing floors.”

[[v9-23-2]]

^<<v9-23-2,2>>^ And David proceeded to inquire of Jehovah, saying: “Shall I go, and must I strike down these Phi·lisʹtines?” In turn Jehovah said to David: “Go, and you must strike down the Phi·lisʹtines and save Keiʹlah.”

[[v9-23-3]]

^<<v9-23-3,3>>^ At this the men of David said to him: “Look! We are afraid while here in Judah, and how much more so in case we should go to Keiʹlah against the battle lines of the Phi·lisʹtines!”

[[v9-23-4]]

^<<v9-23-4,4>>^ So David inquired yet again of Jehovah. Jehovah now answered him and said: “Rise up, go down to Keiʹlah, because I am giving the Phi·lisʹtines into your hand.”

[[v9-23-5]]

^<<v9-23-5,5>>^ Accordingly David went with his men to Keiʹlah and fought against the Phi·lisʹtines and drove off with their livestock, but struck them down with a great slaughter; and David came to be the savior of the inhabitants of Keiʹlah.

[[v9-23-6]]

^<<v9-23-6,6>>^ Now it came about that when A·biʹa·thar the son of A·himʹe·lech ran away to David at Keiʹlah, there was an ephʹod that went down^&#42;1^ in his hand.

[NOTE]
====
. “There was an ephod that went down,” M; T, “he brought down the ephod.”
====

[[v9-23-7]]

^<<v9-23-7,7>>^ In time the report was made to Saul: “David has come to Keiʹlah.” And Saul began to say: “God has sold^&#42;1^ him into my hand, for he has shut himself up by coming into a city with doors and bar.”

[NOTE]
====
. “Sold,” TLXX; M, “alienated (rejected)”; Vg and by altering the first letter of this word in M, “delivered.”
====

[[v9-23-8]]

^<<v9-23-8,8>>^ So Saul summoned all the people to war, to go down to Keiʹlah, to besiege David and his men.

[[v9-23-9]]

^<<v9-23-9,9>>^ And David got to know that Saul was fabricating mischief against him. Hence he said to A·biʹa·thar the priest: “Do bring the ephʹod near.”

[[v9-23-10]]

^<<v9-23-10,10>>^ And David went on to say: “O Jehovah the God of Israel, your servant has definitely heard that Saul is seeking to come to Keiʹlah to lay the city in ruin on my account.

[[v9-23-11]]

^<<v9-23-11,11>>^ Will the landowners^&#42;1^ of Keiʹlah surrender me into his hand? Will Saul come down just as your servant has heard? O Jehovah the God of Israel, tell your servant, please.” To this Jehovah said: “He will come down.”

[NOTE]
====
. “The landowners of.” Heb., va·ʽalehʹ; Vg, “men.”
====

[[v9-23-12]]

^<<v9-23-12,12>>^ And David went on to say: “Will the landowners of Keiʹlah surrender me and my men into Saul’s hand?” In turn Jehovah said: “They will do the surrendering.”

[[v9-23-13]]

^<<v9-23-13,13>>^ At once David rose up with his men, about six^&#42;1^ hundred men, and they went out of Keiʹlah and continued walking about wherever they could walk about. And to Saul it was reported that David had escaped from Keiʹlah, and so he gave up going out.

[NOTE]
====
. “Six,” MSyVg; LXX, “four.”
====

[[v9-23-14]]

^<<v9-23-14,14>>^ And David took up dwelling in the wilderness in places difficult to approach, and he kept dwelling in the mountainous region in the wilderness of Ziph. And Saul kept looking for him always, and God^&#42;1^ did not give him into his hand.

[NOTE]
====
. “God,” MSyVg; LXX, “Jehovah.”
====

[[v9-23-15]]

^<<v9-23-15,15>>^ And David continued in fear^&#42;1^ because Saul had gone out to look for his soul while David was in the wilderness of Ziph at Hoʹresh.^&#42;2^

[NOTE]
====
. “Continued in fear,” by a different vowel pointing of the Heb. verb; M, “got to see [that].”
. Meaning “Wooded Place.”
====

[[v9-23-16]]

^<<v9-23-16,16>>^ Jonʹa·than the son of Saul now rose up and went to David at Hoʹresh, that he might strengthen his hand in regard to God.

[[v9-23-17]]

^<<v9-23-17,17>>^ And he went on to say to him: “Do not be afraid; for the hand of Saul my father will not find you, and you yourself will be king over Israel, and I myself shall become second to you; and Saul my father also has knowledge to that effect.”

[[v9-23-18]]

^<<v9-23-18,18>>^ Then the two of them concluded a covenant before Jehovah; and David kept dwelling in Hoʹresh, and Jonʹa·than himself went to his own home.

[[v9-23-19]]

^<<v9-23-19,19>>^ Later the men of Ziph^&#42;1^ went up to Saul at Gibʹe·ah, saying: “Is not David concealing himself close by us in the places difficult to approach at Hoʹresh, on the hill of Hach·iʹlah, which is to the right side of Je·shiʹmon?^&#42;2^

[NOTE]
====
. Or, “the Ziphites.”
. Or, “the desert.”
====

[[v9-23-20]]

^<<v9-23-20,20>>^ And now in harmony with all the craving of your soul, O king, to come down, come down, and our part will be to surrender him into the hand of the king.”

[[v9-23-21]]

^<<v9-23-21,21>>^ At this Saul said: “Blessed are YOU of Jehovah, for YOU have had compassion on me.

[[v9-23-22]]

^<<v9-23-22,22>>^ Go, please, persevere some more and ascertain and see his place where his foot comes to be—whoever saw him there—for it has been said to me that he himself is surely cunning.

[[v9-23-23]]

^<<v9-23-23,23>>^ And see and ascertain about all the hiding places where he hides himself; and YOU must return to me with the evidence,^&#42;1^ and I will go with YOU; and it must occur that, if he is in the land, I will also search for him carefully among all the thousands^&#42;2^ of Judah.”

[NOTE]
====
. Or, “on a certainty; assuredly.”
. Or, “tribal subdivisions.”
====

[[v9-23-24]]

^<<v9-23-24,24>>^ So they rose up and went to Ziph ahead of Saul, while David and his men were in the wilderness of Maʹon in the Arʹa·bah^&#42;1^ to the south^&#42;2^ of Je·shiʹmon.

[NOTE]
====
. That part of the rift valley that runs south to the Gulf of ‘Aqaba at the Red Sea.
. Lit., “to the right side,” that is, when one faces east.
====

[[v9-23-25]]

^<<v9-23-25,25>>^ Later Saul came with his men to look for him. When they told David, he at once went down to the crag and continued dwelling^&#42;1^ in the wilderness of Maʹon. When Saul got to hear of it, he went chasing after David into the wilderness of Maʹon.

[NOTE]
====
. “The crag and continued dwelling,” MSyVg; LXX, “the crag that is.”
====

[[v9-23-26]]

^<<v9-23-26,26>>^ Eventually Saul came to this side of the mountain, and David and his men were on that side of the mountain. So David became hurried to go away because of Saul; all the while Saul and his men were closing in on David and his men to grab hold of them.

[[v9-23-27]]

^<<v9-23-27,27>>^ But there was a messenger that came to Saul, saying: “Do hasten and go, for the Phi·lisʹtines have made a raid on the land!”

[[v9-23-28]]

^<<v9-23-28,28>>^ At that Saul turned back from chasing after David and went to meet the Phi·lisʹtines. That is why they have called that place the Crag of the Divisions.^&#42;1^

[NOTE]
====
. Or, “called that place Sela-hammahlekoth,” referring to the smooth, or slippery, places.
====

[[v9-23-29]]

^<<v9-23-29,29>>^ ^&#42;1^ Then David made his way up from there and took up dwelling in the places difficult to approach at En-geʹdi.

[NOTE]
====
. MLXXVg begin chapter 24 here.
====

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]