include::./index.adoc[]

[[v9-9-0]]
=== The First of Samuel, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-9-1]]

^<<v9-9-1,1>>^ Now there happened to be a man of Benjamin, and his name was Kish, the son of A·biʹel, the son of Zeʹror, the son of Be·coʹrath, the son of A·phiʹah, a Benʹja·min·ite,^&#42;1^ a man mighty in wealth.

[NOTE]
====
. Lit., “a son of a man a Jaminite.”
====

[[v9-9-2]]

^<<v9-9-2,2>>^ And he happened to have a son whose name was Saul, young and handsome,^&#42;1^ and there was no man of the sons of Israel that was handsomer than he; from his shoulders upward he was taller than all the people.

[NOTE]
====
. Or, “good.”
====

[[v9-9-3]]

^<<v9-9-3,3>>^ And the she-asses belonging to Kish the father of Saul got lost. So Kish said to Saul his son: “Take, please, with you one of the attendants and get up, go, look for the she-asses.”

[[v9-9-4]]

^<<v9-9-4,4>>^ And he^&#42;1^ went passing through the mountainous region of Eʹphra·im and passing on through the land of Shalʹi·shah, and they did not find &#91;them&#93;. And they went passing on through the land of Shaʹa·lim, but they were not &#91;there&#93;. And he went passing on through the land of the Benʹja·min·ites, and they did not find &#91;them&#93;.

[NOTE]
====
. “He,” MSy; LXXVg, “they.”
====

[[v9-9-5]]

^<<v9-9-5,5>>^ They themselves came into the land of Zuph; and Saul, for his part, said to his attendant that was with him: “Do come, and let us return, that my father may not quit attending to the she-asses and actually become anxious about us.”

[[v9-9-6]]

^<<v9-9-6,6>>^ But he said to him: “Look, please! There is a man of God^&#42;1^ in this city, and the man is held in honor. All that he says comes true without fail. Let us go there now. Perhaps he can tell us our way that we must go.”

[NOTE]
====
. “A man of God.” Heb., ʼish-ʼElo·himʹ.
====

[[v9-9-7]]

^<<v9-9-7,7>>^ At this Saul said to his attendant: “And if we should go, what shall we bring to the man? because the bread itself has disappeared from our receptacles, and, as a gift, there is nothing to bring to the man of the &#91;true&#93; God. What is there with us?”

[[v9-9-8]]

^<<v9-9-8,8>>^ So the attendant answered Saul once more and said: “Look! There is a quarter of a shekel^&#42;1^ of silver found in my hand, and I shall^&#42;2^ have to give it to the man of the &#91;true&#93; God, and he will have to tell us our way.”

[NOTE]
====
. See App 8A.
. “I shall,” M; LXX, “you will.”
====

[[v9-9-9]]

^<<v9-9-9,9>>^ (In former times in Israel this was the way the man would have talked on his going to seek God: “COME, and let us go to the seer.” For the prophet of today used to be called a seer in former times.)

[[v9-9-10]]

^<<v9-9-10,10>>^ Then Saul said to his attendant: “Your word is good. Do come, let us go.” And they went their way to the city where the man of the &#91;true&#93; God was.

[[v9-9-11]]

^<<v9-9-11,11>>^ While they were going up on the ascent to the city, they themselves found girls going out to draw water. So they said to them: “Is the seer in this place?”

[[v9-9-12]]

^<<v9-9-12,12>>^ Then they answered them and said: “He is. Look! He is ahead of you. Hurry now, because today he has come to the city, for there is a sacrifice today for the people on the high place.

[[v9-9-13]]

^<<v9-9-13,13>>^ As soon as YOU men come into the city, YOU will directly find him before he goes up to the high place to eat; because the people may not eat until his coming, for he is the one that blesses the sacrifice. First after that those who are invited may eat. And now GO up, because him—just now YOU will find him.”

[[v9-9-14]]

^<<v9-9-14,14>>^ Accordingly they went on up to the city. As they were coming into the middle of the city, why, there was Samuel coming out to meet them to go up to the high place.

[[v9-9-15]]

^<<v9-9-15,15>>^ As for Jehovah, he had uncovered the ear of Samuel the day before Saul came, saying:

[[v9-9-16]]

^<<v9-9-16,16>>^ “Tomorrow about this time I shall send to you a man from the land of Benjamin, and you must anoint him as leader over my people Israel; and he must save my people from the hand of the Phi·lisʹtines, because I have seen &#91;the affliction of&#93; my people,^&#42;1^ for their outcry has come to me.”

[NOTE]
====
. “The affliction of my people,” TLXX; MSyVg, “my people.”
====

[[v9-9-17]]

^<<v9-9-17,17>>^ And Samuel himself saw Saul, and Jehovah, for his part, answered him: “Here is the man of whom I said to you, ‘This is the one that will keep my people within bounds.’”

[[v9-9-18]]

^<<v9-9-18,18>>^ Then Saul approached Samuel in the middle of the gate and said: “Do tell me, please, Just where is the house of the seer?”

[[v9-9-19]]

^<<v9-9-19,19>>^ And Samuel proceeded to answer Saul and say: “I am the seer. Go up before me to the high place, and YOU men must eat with me today, and I must send you away in the morning, and all that is in your heart I shall tell you.

[[v9-9-20]]

^<<v9-9-20,20>>^ As regards the she-asses that were lost to you three days ago, do not set your heart on them, for they have been found. And to whom does all that is desirable of Israel belong? Is it not to you and to the whole house of your father?”

[[v9-9-21]]

^<<v9-9-21,21>>^ At this Saul answered and said: “Am I not a Benʹja·min·ite of the smallest of the tribes of Israel, and my family the most insignificant of all the families of the tribe of Benjamin? So why have you spoken to me a thing like this?”

[[v9-9-22]]

^<<v9-9-22,22>>^ Then Samuel took Saul and his attendant and brought them to the dining hall and gave them a place at the head of those invited; and they were about thirty men.

[[v9-9-23]]

^<<v9-9-23,23>>^ Later Samuel said to the cook: “Do give the portion that I have given to you, of which I said to you, ‘Put it away by you.’”

[[v9-9-24]]

^<<v9-9-24,24>>^ At that the cook lifted off the leg and what was on it, and put it before Saul. And he went on to say: “Here is what has been reserved.^&#42;1^ Put it before yourself. Eat, because to the appointed time they have reserved it for you that you may eat with those invited.”^&#42;2^ So Saul ate with Samuel on that day.

[NOTE]
====
. “What has been reserved,” by a slight emendation; M, “what has been left over.”
. “For you that you may eat with those invited,” by a slight emendation. Lit., “for you​—⁠saying, ‘The people I have invited.’ ” M is obscure.
====

[[v9-9-25]]

^<<v9-9-25,25>>^ Subsequently they went down from the high place to the city, and he continued speaking with Saul on the housetop.

[[v9-9-26]]

^<<v9-9-26,26>>^ Then they rose early,^&#42;1^ and it came about that as soon as the dawn ascended Samuel proceeded to call to Saul on the housetop, saying: “Do get up, that I may send you away.” So Saul got up and both of them, he and Samuel, went forth out of doors.

[NOTE]
====
. “And he continued speaking with Saul on the housetop. (26) Then they rose early,” M; LXX, “and they prepared a couch for Saul on the housetop, (26) and he slept”; Vgc, “and he spoke with Saul on the housetop; and Saul stretched himself out on the housetop and slept.”
====

[[v9-9-27]]

^<<v9-9-27,27>>^ While they were descending by the edge of the city Samuel himself said to Saul: “Say to the attendant that he should pass on ahead of us”—so he passed on—“and, as for you, stand still now that I may let you hear the word of God.”^&#42;1^

[NOTE]
====
. “The word of God.” Heb., devarʹ ʼElo·himʹ. Compare Jg 3:20.
====

'''

xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[&#60; Capítulo Anterior] | <<v9-9-0,Topo>> | xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[Próximo Capítulo &#62;]