include::./index.adoc[]

[[v9-2-0]]
=== The First of Samuel, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-2-1]]

^<<v9-2-1,1>>^ And Hanʹnah went on to pray and say:
“My heart does exult in Jehovah,
My horn is indeed exalted in Jehovah.^&#42;1^
My mouth is widened against my enemies,
For I do rejoice in the salvation from you.

[NOTE]
====
. “In Jehovah,” MVg; LXX and 27 Heb. mss, “in my God.”
====

[[v9-2-2]]

^<<v9-2-2,2>>^ There is no one holy like Jehovah, for there is no one but you;
And there is no rock like our God.^&#42;1^

[NOTE]
====
. “Like our God.” Heb., kEʼ·lo·hehʹnu; Gr., The·osʹ; Lat., Deʹus.
====

[[v9-2-3]]

^<<v9-2-3,3>>^ Do not YOU people speak very haughtily so much,
Let nothing go forth unrestrained from YOUR mouth,
For a God^&#42;1^ of knowledge Jehovah is,
And by him^&#42;2^ deeds are rightly estimated.

[NOTE]
====
. “God of.” Heb., ʼEl; Gr., The·osʹ; Lat., Deʹus.
. “By him,” MmarginVg and many Heb. mss.
====

[[v9-2-4]]

^<<v9-2-4,4>>^ The mighty men of the bow are^&#42;1^ filled with terror,
But those that are stumbling^&#42;2^ do gird on vital energy.

[NOTE]
====
. Lit., “The bow of mighty men is.”
. Or, “that are about to stumble.”
====

[[v9-2-5]]

^<<v9-2-5,5>>^ The satisfied must hire themselves out for bread,
But the hungry actually cease &#91;to hunger&#93;.
Even^&#42;1^ the barren has given birth to seven,
But she that was abundant in sons has faded away.

[NOTE]
====
. Lit., “cease. Even.” By a slight emendation of M, “cease to serve (slave).”
====

[[v9-2-6]]

^<<v9-2-6,6>>^ Jehovah is a Killer and a Preserver of life,^&#42;1^
A Bringer down to Sheʹol,^&#42;2^ and He brings up.

[NOTE]
====
. “And a Preserver of life.” Or, “and a Reviver.” Heb., u·mechai·yehʹ; Lat., vi·viʹfi·cat.
. The common grave of mankind. Gr., haiʹdou; Syr., la·shiul; Lat., in·ferʹnum. See App 4B.
====

[[v9-2-7]]

^<<v9-2-7,7>>^ Jehovah is an Impoverisher and an Enricher,
An Abaser, also an Exalter,

[[v9-2-8]]

^<<v9-2-8,8>>^ A Raiser of a lowly one from the dust;
From the ashpit he lifts up a poor one,
To make them sit with nobles; and a throne of glory he gives to them as a possession.
For to Jehovah belong earth’s supports,
And he places upon them the productive land.^&#42;1^

[NOTE]
====
. “The productive land,” MSy; Lat., orʹbem, “the circle,” that is, of the earth.
====

[[v9-2-9]]

^<<v9-2-9,9>>^ The feet of his loyal ones^&#42;1^ he guards;
As for the wicked ones, they are silenced in darkness,
For not by power does a man^&#42;2^ prove superior.

[NOTE]
====
. Or, “his men of loyal love.”
. “Man.” Heb., ʼish; Gr., a·nerʹ; Lat., vir.
====

[[v9-2-10]]

^<<v9-2-10,10>>^ As for Jehovah, those contending against him will be terrified;
Against them^&#42;1^ he will thunder in the heavens.
Jehovah himself will judge the ends of the earth,
That he may give strength to his king,
That he may exalt the horn of his anointed one.”^&#42;2^

[NOTE]
====
. “Them,” SyVg; M, “him,” that is, each member of the class contending against him.
. “His anointed one (messiah).” Heb., meshi·chohʹ; Gr., khri·stouʹ; Syr., dam·shi·cheh; Lat., chriʹsti.
====

[[v9-2-11]]

^<<v9-2-11,11>>^ Then El·kaʹnah went to Raʹmah to his house;^&#42;1^ and as for the boy, he became a minister^&#42;2^ of Jehovah before Eʹli the priest.

[NOTE]
====
. “Then . . . house,” MSyVg; LXXB, “And she left him there before Jehovah and went off to Armathaim.”
. Or, “attendant.” Heb., mesha·rethʹ; Gr., lei·tour·gonʹ, “public servant”; Lat., mi·niʹster.
====

[[v9-2-12]]

^<<v9-2-12,12>>^ Now the sons of Eʹli were good-for-nothing men;^&#42;1^ they did not acknowledge Jehovah.

[NOTE]
====
. Lit., “sons of belial (worthlessness).”
====

[[v9-2-13]]

^<<v9-2-13,13>>^ As for the due right of the priests from^&#42;1^ the people,^&#42;2^ whenever any man was offering a sacrifice, an attendant of the priest came with the three-pronged fork in his hand, just when the meat was boiling,

[NOTE]
====
. “From,” TLXXSy and a few Heb. mss; M, “with.”
. “Recognize Jehovah. (13) And the due right of the priests from the people,” LXX. See De 18:3.
====

[[v9-2-14]]

^<<v9-2-14,14>>^ and made a thrust into the basin or the two-handled cooking pot or the caldron or the one-handled cooking pot. Anything that the fork might bring up the priest would take for himself.^&#42;1^ That is the way they would do in Shiʹloh to all the Israelites coming there.^&#42;2^

[NOTE]
====
. “For himself,” LXXSyVg; M, “on (with) it.”
. “There,” MSy; LXX, “to sacrifice to Jehovah.”
====

[[v9-2-15]]

^<<v9-2-15,15>>^ Also, before ever they could make the fat smoke, an attendant of the priest came and said to the man sacrificing: “Do give meat to roast for the priest so that he may receive from you, not boiled meat, but raw.”

[[v9-2-16]]

^<<v9-2-16,16>>^ When the man would say to him: “Let them be sure to make the fat smoke first of all. Then take for yourself just whatever your soul may crave,” he actually said: “No,^&#42;1^ but you should give it now; and, if not, I shall have to take it by force!”

[NOTE]
====
. “No,” MmarginLXX and 20 Heb. mss; MSyVg, “to him.”
====

[[v9-2-17]]

^<<v9-2-17,17>>^ And the sin of the attendants^&#42;1^ came to be very great before Jehovah; for the men treated the offering of Jehovah with disrespect.

[NOTE]
====
. Or, “young men.”
====

[[v9-2-18]]

^<<v9-2-18,18>>^ And Samuel was ministering before Jehovah, as a boy, having a linen ephʹod girded on.

[[v9-2-19]]

^<<v9-2-19,19>>^ Also, a little sleeveless coat his mother would make for him, and she brought it up to him from year to year when she came up with her husband to sacrifice the yearly sacrifice.

[[v9-2-20]]

^<<v9-2-20,20>>^ And Eʹli blessed El·kaʹnah and his wife and said: “May Jehovah appoint to you an offspring from this wife in place of the thing lent, that was lent to Jehovah.”^&#42;1^ And they went to their place.^&#42;2^

[NOTE]
====
. Or, “that Jehovah asked for (borrowed),” by omitting the Heb. preposition for “to”; M is vowel-pointed to read: “that he asked for (borrowed) for Jehovah.”
. “Their place,” Sy and 12 Heb. mss; M, “his place.”
====

[[v9-2-21]]

^<<v9-2-21,21>>^ Accordingly Jehovah turned his attention to Hanʹnah, so that she had pregnancy and gave birth^&#42;1^ to three sons and two daughters. And the boy Samuel continued growing up with Jehovah.

[NOTE]
====
. “Gave birth yet,” LXX.
====

[[v9-2-22]]

^<<v9-2-22,22>>^ And Eʹli was very old, and he had heard of all that his sons kept doing to all Israel and how they would lie down with the women that were serving^&#42;1^ at the entrance of the tent of meeting.^&#42;2^

[NOTE]
====
. “Were serving.” Heb., hats·tso·veʼohthʹ. This verb is one used for military service, suggesting organized service in companies for these women.
. “And how they . . . tent of meeting,” M; LXX omits.
====

[[v9-2-23]]

^<<v9-2-23,23>>^ And he used to say to them: “Why do YOU keep doing things like these? For the things I am hearing about YOU from all the people are bad.^&#42;1^

[NOTE]
====
. M adds “even these [words],” but this appears to be a dittography.
====

[[v9-2-24]]

^<<v9-2-24,24>>^ No, my sons, because the report is not good that I am hearing, that the people of Jehovah are causing to circulate.

[[v9-2-25]]

^<<v9-2-25,25>>^ If a man should sin against a man, God will arbitrate for him; but if it is against Jehovah that a man should sin, who is there to pray for him?” But they would not listen to the voice of their father, because Jehovah was now pleased to put them to death.

[[v9-2-26]]

^<<v9-2-26,26>>^ All the while the boy Samuel was growing bigger and more likable^&#42;1^ both from Jehovah’s standpoint and from that of men.

[NOTE]
====
. Or, “and better.”
====

[[v9-2-27]]

^<<v9-2-27,27>>^ And a man of God^&#42;1^ proceeded to come to Eʹli and say to him: “This is what Jehovah has said, ‘Did I not for a fact reveal myself to the house of your forefather while they happened to be in Egypt as slaves^&#42;2^ to the house of Pharʹaoh?

[NOTE]
====
. “A man of God.” Heb., ʼish-ʼElo·himʹ.
. “As slaves,” LXX; MSyVg omit.
====

[[v9-2-28]]

^<<v9-2-28,28>>^ And there was a choosing^&#42;1^ of him out of all the tribes of Israel for me, to act as priest^&#42;2^ and go up upon my altar to make sacrificial smoke billow up,^&#42;3^ to bear an ephʹod before me, that I might give to the house of your forefather all the offerings made by fire of the sons of Israel.

[NOTE]
====
. “There was a choosing.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. “For me, to act as priest,” LXX; MSyVg, “for me as a priest.”
. Or, “to make incense smoke.”
====

[[v9-2-29]]

^<<v9-2-29,29>>^ Why do YOU men keep kicking at my sacrifice and at my offering that I have commanded &#91;in my&#93; dwelling,^&#42;1^ and you keep honoring your sons more than me by fattening yourselves^&#42;2^ from the best of every offering of Israel my people?^&#42;3^

[NOTE]
====
. “[In my] dwelling.” M uses “dwelling” here in an absolute way, without modifiers.
. “Yourselves,” M; T, “them.”
. “My people.” Possibly, by an emendation, “in full view of me,” to agree with LXX.
====

[[v9-2-30]]

^<<v9-2-30,30>>^ “‘That is why the utterance of Jehovah the God of Israel is: “I did indeed say, As for your house and the house of your forefather, they will walk before me to time indefinite.” But now the utterance of Jehovah is: “It is unthinkable, on my part, because those honoring me I shall honor, and those despising me will be of little account.”

[[v9-2-31]]

^<<v9-2-31,31>>^ Look! Days are coming when I shall certainly chop off your arm and the arm of the house of your forefather, so that there will not come to be an old man in your house.

[[v9-2-32]]

^<<v9-2-32,32>>^ And you will actually look upon an adversary &#91;in my&#93; dwelling amid all the good that is done to Israel; and never will there come to be an old man in your house.

[[v9-2-33]]

^<<v9-2-33,33>>^ And yet there is a man of yours that I shall not cut off from being at my altar so as to cause your^&#42;1^ eyes to fail and to make your^&#42;2^ soul pine away; but the greater number of your house will all die by the sword of men.^&#42;3^

[NOTE]
====
. “Your,” MSyVg; LXX, “his.”
. “Your,” MSyVg; LXX, “his.” Evidently LXX refers to Abiathar, a descendant of Eli.
. “Die by the sword of men,” LXX; MSy, “die as men.”
====

[[v9-2-34]]

^<<v9-2-34,34>>^ And this is the sign for you that will come to your two sons, Hophʹni and Phinʹe·has: On one day both of them will die.

[[v9-2-35]]

^<<v9-2-35,35>>^ And I shall certainly raise up for myself a faithful priest. In harmony with what is in my heart and in my soul he will do; and I shall certainly build for him a lasting^&#42;1^ house, and he will certainly walk before my anointed one^&#42;2^ always.^&#42;3^

[NOTE]
====
. Or, “faithful; firmly established.”
. “My anointed one.” Heb., meshi·chiʹ; Gr., khri·stouʹ; Syr., meshi·chai; Lat., chriʹsto.
. Lit., “all the days.”
====

[[v9-2-36]]

^<<v9-2-36,36>>^ And it must occur that anyone left over in your house will come and bow down to him for the payment of money and a round loaf of bread, and will certainly say: “Attach me, please, to one of the priestly offices to eat a piece of bread.”’”

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]