include::./index.adoc[]

[[v9-3-0]]
=== The First of Samuel, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-3-1]]

^<<v9-3-1,1>>^ All the while the boy Samuel was ministering to Jehovah before Eʹli, and word from Jehovah had become rare in those days; there was no vision being spread abroad.

[[v9-3-2]]

^<<v9-3-2,2>>^ Now it came about on that day that Eʹli was lying in his place, and his eyes had begun to grow dim; he was not able to see.

[[v9-3-3]]

^<<v9-3-3,3>>^ And the lamp of God^&#42;1^ was not yet extinguished, and Samuel was lying in the temple of Jehovah, where the ark of God was.

[NOTE]
====
. “The lamp of God,” that is, the lampstand. See Le 24:2, 3.
====

[[v9-3-4]]

^<<v9-3-4,4>>^ And Jehovah proceeded to call Samuel.^&#42;1^ At this he said: “Here I am.”

[NOTE]
====
. “Proceeded to call Samuel,” MSyVg; LXX, “called: ‘Samuel, Samuel!’ ” See vs 10.
====

[[v9-3-5]]

^<<v9-3-5,5>>^ And he went running to Eʹli and saying: “Here I am, for you called me.” But he said: “I did not call. Lie down again.” So he went and lay down.

[[v9-3-6]]

^<<v9-3-6,6>>^ And Jehovah went on to call yet again: “Samuel!” At this Samuel got up and went to Eʹli and said: “Here I am, for you did call me.” But he said: “I did not call, my son. Lie down again.”

[[v9-3-7]]

^<<v9-3-7,7>>^ (As regards Samuel, he had not yet come to know Jehovah, and the word of Jehovah had not yet begun to be revealed to him.)

[[v9-3-8]]

^<<v9-3-8,8>>^ So Jehovah called again for the third time: “Samuel!” At that he got up and went to Eʹli and said: “Here I am, for you must have called me.”
And Eʹli began to discern that it was Jehovah that was calling the boy.

[[v9-3-9]]

^<<v9-3-9,9>>^ Consequently Eʹli said to Samuel: “Go, lie down, and it must occur that, if he should call you, you must say, ‘Speak, Jehovah, for your servant is listening.’” So Samuel went and lay down in his place.

[[v9-3-10]]

^<<v9-3-10,10>>^ Then Jehovah came and took his position and called as at the other times: “Samuel, Samuel!” At this Samuel said: “Speak, for your servant is listening.”

[[v9-3-11]]

^<<v9-3-11,11>>^ And Jehovah went on to say to Samuel: “Look! I am doing something in Israel which if anyone hears about, both his ears will tingle.

[[v9-3-12]]

^<<v9-3-12,12>>^ On that day I shall carry out toward Eʹli all that I have said respecting his house, from beginning to end.

[[v9-3-13]]

^<<v9-3-13,13>>^ And you must tell^&#42;1^ him that I am judging his house to time indefinite for the error that he has known, because^&#42;2^ his sons are calling down evil upon God,^&#42;3^ and he has not rebuked them.

[NOTE]
====
. “And you must tell,” in harmony with vs 15; MLXXSyVg, “And I have told.”
. According to MSy; by a slight emendation, “for the reason that he has known that”; LXX, “for the injustices of his sons, because.”
. “God,” originally, but emended by the Sopherim to read “for themselves.” One of the Eighteen Emendations. Gr., The·onʹ, “God.” See App 2B.
====

[[v9-3-14]]

^<<v9-3-14,14>>^ And that is why I have sworn to the house of Eʹli that the error of the house of Eʹli will not be brought to exemption from punishment by sacrifice or by offering to time indefinite.”

[[v9-3-15]]

^<<v9-3-15,15>>^ And Samuel continued lying down until the morning.^&#42;1^ Then he opened the doors of Jehovah’s house. And Samuel was afraid to tell Eʹli of the appearing.

[NOTE]
====
. LXX adds, “and got up early in the morning.”
====

[[v9-3-16]]

^<<v9-3-16,16>>^ But Eʹli called Samuel and said: “Samuel, my son!” At this he said: “Here I am.”

[[v9-3-17]]

^<<v9-3-17,17>>^ And he went on to say: “What is the word that he has spoken to you? Do not, please, hide it from me. May God do so to you and so may he add to it if you should hide from me a word of all the word that he has spoken to you.”

[[v9-3-18]]

^<<v9-3-18,18>>^ So Samuel told him all the words, and he did not hide anything from him. At that he said: “It is Jehovah. What is good in his eyes let him do.”

[[v9-3-19]]

^<<v9-3-19,19>>^ And Samuel continued growing up, and Jehovah himself proved to be with him and did not cause any of all his words to fall to the earth.

[[v9-3-20]]

^<<v9-3-20,20>>^ And all Israel from Dan to Beʹer-sheʹba became aware that Samuel was one accredited for the position of prophet to Jehovah.

[[v9-3-21]]

^<<v9-3-21,21>>^ And Jehovah proceeded to appear again in Shiʹloh, because Jehovah revealed himself to Samuel in Shiʹloh by the word of Jehovah.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]