include::./index.adoc[]

[[v9-20-0]]
=== The First of Samuel, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-20-1]]

^<<v9-20-1,1>>^ And David went running away from Naiʹoth in Raʹmah. However, he came and said in front of Jonʹa·than: “What have I done? What is my error, and what sin have I committed before your father, for he is seeking for my soul?”

[[v9-20-2]]

^<<v9-20-2,2>>^ At this he said to him: “It is unthinkable! You will not die. Look! My father will not do a big thing or a little thing and not disclose it to my ear;^&#42;1^ and for what reason should my father conceal this matter from me? This does not happen.”

[NOTE]
====
. Lit., “and not uncover my ear.”
====

[[v9-20-3]]

^<<v9-20-3,3>>^ But David swore in addition and said: “Your father must surely know that I have found favor in your eyes, and so would say, ‘Do not let Jonʹa·than know this for fear he may feel hurt.’ But, in fact, as Jehovah is living and as your soul is living, there is just about a step between me and death!”

[[v9-20-4]]

^<<v9-20-4,4>>^ And Jonʹa·than went on to say to David: “Whatever your soul may say^&#42;1^ I shall do for you.”

[NOTE]
====
. “Say,” MSyVg; TLXX, “desire.”
====

[[v9-20-5]]

^<<v9-20-5,5>>^ At this David said to Jonʹa·than: “Look! Tomorrow is new moon, and I myself ought, without fail, to be sitting with the king to eat; and you must send me away, and I must conceal myself in the field until the evening on the third day.^&#42;1^

[NOTE]
====
. Lit., “the third,” M; LXX omits.
====

[[v9-20-6]]

^<<v9-20-6,6>>^ If your father should miss me at all, then you must say, ‘David earnestly asked leave of absence of me to run to Bethʹle·hem his city, because there is a yearly sacrifice there for all the family.’

[[v9-20-7]]

^<<v9-20-7,7>>^ If the way he should say is, ‘It is all right!’ it means peace to your servant. But if he should at all become angry, know that what is bad has been determined upon by him.

[[v9-20-8]]

^<<v9-20-8,8>>^ And you must render loving-kindness^&#42;1^ toward your servant, for it is into a covenant of Jehovah that you have brought your servant with you. But if there is error in me, put me to death yourself, since why should it be to your father that you should bring me?”

[NOTE]
====
. Or, “loyal love.”
====

[[v9-20-9]]

^<<v9-20-9,9>>^ To this Jonʹa·than said: “That is unthinkable respecting you! But if I should at all get to know that evil has been determined upon by my father to come upon you, shall I not tell it to you?”

[[v9-20-10]]

^<<v9-20-10,10>>^ Then David said to Jonʹa·than: “Who will tell me whether what your father may answer you is harsh?”

[[v9-20-11]]

^<<v9-20-11,11>>^ In turn Jonʹa·than said to David: “Just come, and let us go out into the field.” So both of them went out into the field.

[[v9-20-12]]

^<<v9-20-12,12>>^ And Jonʹa·than went on to say to David: “Jehovah the God of Israel &#91;be a witness&#93;^&#42;1^ that I shall sound out my father about this time tomorrow, or the third day, and if he is well-disposed toward David,^&#42;2^ shall I not then send to you and certainly disclose it to your ear?^&#42;3^

[NOTE]
====
. “Be a witness,” or, “bears witness,” Sy; LXX, “knows”; M omits.
. Or, “if it is good toward David.”
. Lit., “uncover your ear.”
====

[[v9-20-13]]

^<<v9-20-13,13>>^ So may Jehovah do to Jonʹa·than and so may he add to it, if, in case it should seem good to my father to do evil against you, I do not indeed disclose it to your ear and send you away, and you do not certainly go in peace. And may Jehovah prove to be with you, just as he proved to be with my father.

[[v9-20-14]]

^<<v9-20-14,14>>^ And will you not, if I shall be still alive, yes, will you not exercise the loving-kindness of Jehovah toward me, that I may not die?

[[v9-20-15]]

^<<v9-20-15,15>>^ And you will not^&#42;1^ cut off your own loving-kindness from being with my household to time indefinite. Nor, when Jehovah cuts off the enemies of David, every one from the surface of the ground,

[NOTE]
====
. “Toward me. And if I should indeed die, (15) you will not,” LXXVg.
====

[[v9-20-16]]

^<<v9-20-16,16>>^ will &#91;the name of&#93; Jonʹa·than be cut off from the house of David.^&#42;1^ And Jehovah must require it at the hand of David’s enemies.”

[NOTE]
====
. “Will the name of Jonathan be cut off from the house of David,” LXX; MVg, “And Jonathan proceeded to contract (make a covenant) with the house of David [, saying].”
====

[[v9-20-17]]

^<<v9-20-17,17>>^ So Jonʹa·than swore again to David^&#42;1^ because of his love for him; for as he loved his own soul he loved him.

[NOTE]
====
. “Swore again to David,” LXXVg; MSy, “had David swear again.”
====

[[v9-20-18]]

^<<v9-20-18,18>>^ And Jonʹa·than went on to say to him: “Tomorrow is new moon, and you will certainly be missed, because your seat will be vacant.

[[v9-20-19]]

^<<v9-20-19,19>>^ And certainly on the third day you will be missed very much; and you must come to the place where you concealed yourself on the working day, and you must dwell near this stone here.^&#42;1^

[NOTE]
====
. “Near that mound of earth,” by an emendation of M to agree with LXX; Vg, “near the stone, the name of which is Ezel.”
====

[[v9-20-20]]

^<<v9-20-20,20>>^ And as for me, I shall shoot three arrows^&#42;1^ to one side of it, to send them where I will to a target.

[NOTE]
====
. Or, “I shall on the third day shoot arrows.”
====

[[v9-20-21]]

^<<v9-20-21,21>>^ And, look! I shall send the attendant, &#91;saying,&#93; ‘Go, find the arrows.’ If I should specifically say to the attendant, ‘Look! The arrows are on this side of you, take them,’^&#42;1^ then you come, for it means peace for you and there is nothing the matter, as Jehovah is living.

[NOTE]
====
. Lit., “it.”
====

[[v9-20-22]]

^<<v9-20-22,22>>^ But if this is the way I should say to the lad, ‘Look! The arrows are farther away from you,’ go, for Jehovah has sent you away.

[[v9-20-23]]

^<<v9-20-23,23>>^ And as for the word that we have spoken, I and you, why, may Jehovah be between me and you to time indefinite.”

[[v9-20-24]]

^<<v9-20-24,24>>^ And David proceeded to conceal himself in the field. And it came to be new moon, and the king took his seat at the meal^&#42;1^ to eat.

[NOTE]
====
. “Meal (bread),” MSy; LXX, “table.”
====

[[v9-20-25]]

^<<v9-20-25,25>>^ And the king was sitting in his seat as at other times, in the seat by the wall; and Jonʹa·than was facing him,^&#42;1^ and Abʹner was sitting at Saul’s side, but David’s place was vacant.

[NOTE]
====
. In agreement with LXX. Lit., “but Jonathan rose up.”
====

[[v9-20-26]]

^<<v9-20-26,26>>^ And Saul did not say anything at all on that day, for he said to himself: “Something has happened so that he is not clean, for he has not been cleansed.”^&#42;1^

[NOTE]
====
. “He has not been cleansed,” LXX; M, “he is not clean.”
====

[[v9-20-27]]

^<<v9-20-27,27>>^ And it came about the day after the new moon, on the second day, that David’s place continued vacant. At this Saul said to Jonʹa·than his son: “Why has not the son of Jesʹse come to the meal either yesterday or today?”

[[v9-20-28]]

^<<v9-20-28,28>>^ So Jonʹa·than answered Saul: “David earnestly asked leave of absence from me &#91;to go&#93; to Bethʹle·hem.

[[v9-20-29]]

^<<v9-20-29,29>>^ And he went on to say, ‘Send me away, please, because we have a family sacrifice in the city, and it was my own brother that commanded me. So now, if I have found favor in your eyes, let me slip away, please, that I may see my brothers.’ That is why he has not come to the king’s table.”

[[v9-20-30]]

^<<v9-20-30,30>>^ Then Saul’s anger grew hot against Jonʹa·than and he said to him: “You son of a rebellious maid, do I not well know that you are choosing^&#42;1^ the son of Jesʹse to your own shame and to the shame of the secret parts of your mother?

[NOTE]
====
. “You are a partner of,” LXX.
====

[[v9-20-31]]

^<<v9-20-31,31>>^ For all the days that the son of Jesʹse is alive on the ground, you and your kingship will not be firmly established. So now send and fetch him to me, for he is destined for death.”^&#42;1^

[NOTE]
====
. Lit., “for he is a son of death.”
====

[[v9-20-32]]

^<<v9-20-32,32>>^ However, Jonʹa·than answered Saul his father and said to him: “Why should he be put to death? What has he done?”

[[v9-20-33]]

^<<v9-20-33,33>>^ At that Saul went hurling the spear at him to strike him; and Jonʹa·than came to know that it had been determined upon by his father to put David to death.

[[v9-20-34]]

^<<v9-20-34,34>>^ Immediately Jonʹa·than rose up from the table in the heat of anger, and he did not eat bread on the second day after the new moon, for he had been hurt respecting David, because his own father had humiliated him.

[[v9-20-35]]

^<<v9-20-35,35>>^ And it came about in the morning that Jonʹa·than made his way out to the field of David’s appointed place, and a young attendant was with him.

[[v9-20-36]]

^<<v9-20-36,36>>^ And he proceeded to say to his attendant: “Run, please, find the arrows that I am shooting.” The attendant ran, and he himself shot the arrow to make it pass beyond him.

[[v9-20-37]]

^<<v9-20-37,37>>^ When the attendant came as far as the place of the arrow that Jonʹa·than had shot, Jonʹa·than began to call from behind the attendant and say: “Is not the arrow farther away from you?”

[[v9-20-38]]

^<<v9-20-38,38>>^ And Jonʹa·than went on calling from behind the attendant: “In haste! Act quickly! Do not stand still!” And the attendant of Jonʹa·than went picking up the arrows and then came to his master.^&#42;1^

[NOTE]
====
. “His master.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence. See Ge 39:2 ftn.
====

[[v9-20-39]]

^<<v9-20-39,39>>^ As for the attendant, he did not know anything; only Jonʹa·than and David themselves knew about the matter.

[[v9-20-40]]

^<<v9-20-40,40>>^ After that Jonʹa·than gave his weapons to the attendant that belonged to him and he said to him: “Go, take them to the city.”

[[v9-20-41]]

^<<v9-20-41,41>>^ The attendant went. As for David, he rose up from nearby to the south. Then he fell on his face to the earth and bowed three times; and they began kissing each other and weeping for each other, until David had done it the most.

[[v9-20-42]]

^<<v9-20-42,42>>^ And Jonʹa·than went on to say to David: “Go in peace, since we have sworn, both of us, in the name of Jehovah, saying, ‘May Jehovah himself prove to be between me and you and between my offspring and your offspring to time indefinite.’”^&#42;1^
Accordingly David^&#42;2^ rose up and went his way, and Jonʹa·than himself came into the city.

[NOTE]
====
. MLXX end chapter 20 here.
. “David,” LXXVgc; M, “he.”
====

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]