include::./index.adoc[]

[[v9-16-0]]
=== The First of Samuel, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-16-1]]

^<<v9-16-1,1>>^ Eventually Jehovah said to Samuel: “For how long will you be mourning for Saul, while I, on the other hand, have rejected him from ruling as king over Israel? Fill your horn with oil and go. I shall send you to Jesʹse the Bethʹle·hem·ite, because I have provided among his sons a king for myself.”

[[v9-16-2]]

^<<v9-16-2,2>>^ But Samuel said: “How can I go? Once Saul has heard of it he will certainly kill me.” And Jehovah went on to say: “A young cow of the herd you should take with you,^&#42;1^ and you must say, ‘To sacrifice to Jehovah is why I have come.’

[NOTE]
====
. Lit., “in your hand.”
====

[[v9-16-3]]

^<<v9-16-3,3>>^ And you must call Jesʹse to the sacrifice; and I, for my part, shall make known to you what you should do, and you must anoint for me the one whom I designate to you.”

[[v9-16-4]]

^<<v9-16-4,4>>^ And Samuel proceeded to do what Jehovah spoke. When he came to Bethʹle·hem the older men of the city began to tremble at meeting him, and so they said: “Does your coming mean peace?”

[[v9-16-5]]

^<<v9-16-5,5>>^ To this he said: “It means peace. To sacrifice to Jehovah is why I have come. Sanctify yourselves, and YOU must come with me to the sacrifice.” Then he sanctified Jesʹse and his sons, after which he called them to the sacrifice.

[[v9-16-6]]

^<<v9-16-6,6>>^ And it came about that, as they came in and he caught sight of E·liʹab, he at once said: “Surely his anointed one^&#42;1^ is before Jehovah.”

[NOTE]
====
. “His anointed one.” Heb., meshi·chohʹ; Gr., khri·stosʹ; Syr., meshi·cheh; Lat., chriʹstus.
====

[[v9-16-7]]

^<<v9-16-7,7>>^ But Jehovah said to Samuel: “Do not look at his appearance and at the height of his stature, for I have rejected him. For not the way man sees &#91;is the way God sees&#93;,^&#42;1^ because mere man sees what appears to the eyes;^&#42;2^ but as for Jehovah, he sees what the heart is.”^&#42;3^

[NOTE]
====
. “Is the way God sees,” LXX; M omits.
. Lit., “sees as to the eyes.”
. Lit., “sees as to the heart.”
====

[[v9-16-8]]

^<<v9-16-8,8>>^ Then Jesʹse called A·binʹa·dab and had him pass before Samuel, but he said: “Neither has Jehovah chosen this one.”

[[v9-16-9]]

^<<v9-16-9,9>>^ Next Jesʹse had Shamʹmah pass by, but he said: “Neither has Jehovah chosen this one.”

[[v9-16-10]]

^<<v9-16-10,10>>^ So Jesʹse had seven of his sons pass before Samuel; still Samuel said to Jesʹse: “Jehovah has not chosen these.”

[[v9-16-11]]

^<<v9-16-11,11>>^ Finally Samuel said to Jesʹse: “Are these all the boys?” To this he said: “The youngest one has till now been left out, and, look! he is pasturing the sheep.” At that Samuel said to Jesʹse: “Do send and fetch him, because we shall not sit down to meal until his coming here.”

[[v9-16-12]]

^<<v9-16-12,12>>^ Accordingly he sent and had him come. Now he was ruddy, a young man with^&#42;1^ beautiful eyes and handsome in appearance. Then Jehovah said: “Get up, anoint him, for this is he!”

[NOTE]
====
. “A young man with,” by an emendation of M from עִם (ʽim, “together with”) to עֶלֶם (ʽeʹlem, “lad”). Compare 17:56; 20:22.
====

[[v9-16-13]]

^<<v9-16-13,13>>^ Accordingly Samuel took the horn of oil and anointed him in the midst of his brothers. And the spirit of Jehovah began to be operative upon David from that day forward. Later Samuel rose and went his way to Raʹmah.

[[v9-16-14]]

^<<v9-16-14,14>>^ And the very spirit of Jehovah departed from Saul, and a bad spirit from Jehovah terrorized him.

[[v9-16-15]]

^<<v9-16-15,15>>^ And the servants of Saul began to say to him: “Here, now, God’s^&#42;1^ bad spirit is terrorizing you.

[NOTE]
====
. “God’s,” MVg; LXX, “Jehovah’s.”
====

[[v9-16-16]]

^<<v9-16-16,16>>^ Let our lord, please, command your servants before you that they should look for a skilled man playing upon the harp. And it must occur that, when God’s bad spirit comes to be upon you, he will have to play with his hand, and it will certainly be well with you.”

[[v9-16-17]]

^<<v9-16-17,17>>^ So Saul said to his servants: “Provide me, please, a man doing well at playing, and YOU must bring him to me.”

[[v9-16-18]]

^<<v9-16-18,18>>^ And one of the attendants proceeded to answer and say: “Look! I have seen how a son of Jesʹse the Bethʹle·hem·ite is skilled at playing, and he is a valiant, mighty man and a man of war and an intelligent speaker and a well-formed man, and Jehovah is with him.”

[[v9-16-19]]

^<<v9-16-19,19>>^ Then Saul sent messengers to Jesʹse and said: “Do send to me David your son, who is with the flock.”

[[v9-16-20]]

^<<v9-16-20,20>>^ So Jesʹse took an ass, bread and a skin bottle of wine and a kid of the goats and sent them by the hand of David his son to Saul.

[[v9-16-21]]

^<<v9-16-21,21>>^ Thus David came to Saul and attended upon him;^&#42;1^ and he got to loving him very much, and he came to be his armor-bearer.

[NOTE]
====
. Lit., “continued standing before him,” that is, in order to wait upon him.
====

[[v9-16-22]]

^<<v9-16-22,22>>^ Consequently Saul sent to Jesʹse, saying: “Let David, please, keep attending upon me, for he has found favor in my eyes.”

[[v9-16-23]]

^<<v9-16-23,23>>^ And it occurred that, when God’s spirit came to be upon Saul, David took the harp and played with his hand; and there was relief for Saul and it was well with him, and the bad spirit departed from upon him.

'''

xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[&#60; Capítulo Anterior] | <<v9-16-0,Topo>> | xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[Próximo Capítulo &#62;]