include::./index.adoc[]

[[v9-30-0]]
=== The First of Samuel, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-30-1]]

^<<v9-30-1,1>>^ And it came about while David and his men were coming to Zikʹlag on the third day, that the A·malʹek·ites made a raid on the south and on Zikʹlag; and they proceeded to strike Zikʹlag and burn it with fire,

[[v9-30-2]]

^<<v9-30-2,2>>^ and to carry off captive the women &#91;and all&#93; that^&#42;1^ were in it, from the smallest to the greatest. They did not put anyone^&#42;2^ to death, but they drove them along and went on their way.

[NOTE]
====
. “The women and all things that,” LXX; M, “the women that.”
. “Anyone,” or, “a man,” MVg; LXX, “a man or woman.”
====

[[v9-30-3]]

^<<v9-30-3,3>>^ When David came with his men to the city, why, there it was burned with fire, and, as for their wives and their sons and their daughters, they had been carried off captive.

[[v9-30-4]]

^<<v9-30-4,4>>^ And David and the people that were with him began to raise their voice and weep, until there was in them no power to weep &#91;anymore&#93;.

[[v9-30-5]]

^<<v9-30-5,5>>^ And David’s two wives had been carried off captive, A·hinʹo·am the Jezʹre·el·i·tess and Abʹi·gail the wife of Naʹbal the Carʹmel·ite.

[[v9-30-6]]

^<<v9-30-6,6>>^ And it became very distressing to David, because the people said to stone him; for the soul of all the people had become bitter, each one because of his sons and his daughters. So David took to strengthening himself by Jehovah his God.

[[v9-30-7]]

^<<v9-30-7,7>>^ Hence David said to A·biʹa·thar the priest, the son of A·himʹe·lech: “Do, please, bring the ephʹod near to me.” And A·biʹa·thar came bringing the ephʹod near to David.

[[v9-30-8]]

^<<v9-30-8,8>>^ And David began to inquire of Jehovah, saying: “Shall I chase after this marauder band? Shall I overtake them?” At this he said to him: “Go in chase, for you will without fail overtake them, and you will without fail make a deliverance.”

[[v9-30-9]]

^<<v9-30-9,9>>^ Promptly David got on his way, he and the six hundred men that were with him, and they went on as far as the torrent valley of Beʹsor, and the men that were to be left behind stood still.

[[v9-30-10]]

^<<v9-30-10,10>>^ And David kept up the chase, he and four hundred men, but two hundred men that were too tired to pass over the torrent valley of Beʹsor stood still.

[[v9-30-11]]

^<<v9-30-11,11>>^ And they got to find a man, an Egyptian, in the field. So they took him to David and gave him bread that he might eat and gave him water to drink.

[[v9-30-12]]

^<<v9-30-12,12>>^ Further, they gave him a slice of a cake of pressed figs and two cakes of raisins. Then he ate and his spirit returned to him; for he had not eaten bread or drunk water for three days and three nights.

[[v9-30-13]]

^<<v9-30-13,13>>^ David now said to him: “To whom do you belong, and where are you from?” to which he said: “I am an Egyptian attendant, a slave of an A·malʹek·ite man, but my master left me because I took sick three days ago.

[[v9-30-14]]

^<<v9-30-14,14>>^ We were the ones that made a raid on the south of the Cherʹe·thites and upon that which belongs to Judah and upon the south of Caʹleb; and Zikʹlag we burned with fire.”

[[v9-30-15]]

^<<v9-30-15,15>>^ At this David said to him: “Will you lead me down to this marauder band?” To this he said: “Do swear to me by God^&#42;1^ that you will not put me to death, and that you will not surrender me into the hand of my master, and I shall lead you down to this marauder band.”^&#42;2^

[NOTE]
====
. “By God.” Heb., vEʼ·lo·himʹ; Gr., The·ouʹ; Lat., Deʹum.
. LXXL adds, “And he swore to him.”
====

[[v9-30-16]]

^<<v9-30-16,16>>^ Accordingly he led him down, and there they were spread disorderly over the surface of all the land eating and drinking and having a feast on account of all the great spoil that they had taken from the land of the Phi·lisʹtines and the land of Judah.

[[v9-30-17]]

^<<v9-30-17,17>>^ And David went striking them down from the morning darkness until the evening, that he might devote them to destruction;^&#42;1^ and not a man of them escaped except four hundred young men that rode upon camels and took to flight.

[NOTE]
====
. “That he might devote them to destruction,” by an emendation; M, “of their following day.”
====

[[v9-30-18]]

^<<v9-30-18,18>>^ And David got to deliver all that the A·malʹek·ites had taken, and his two wives David delivered.

[[v9-30-19]]

^<<v9-30-19,19>>^ And there was nothing of theirs lacking, from the smallest to the greatest and to sons and daughters and from the spoil, even to anything that they had taken for themselves. Everything David recovered.

[[v9-30-20]]

^<<v9-30-20,20>>^ So David took all the flocks and the herds, which they drove before that &#91;other&#93; livestock. Then they said: “This is David’s spoil.”

[[v9-30-21]]

^<<v9-30-21,21>>^ At length David came to the two hundred men who had been too tired to go along with David,^&#42;1^ and whom they^&#42;2^ had kept sitting by the torrent valley of Beʹsor; and they came out to meet David and to meet the people that were with him. When David came near to the people he began to ask them how they were.

[NOTE]
====
. Or, “after David.”
. “They,” MSy; LXXVg, “he.”
====

[[v9-30-22]]

^<<v9-30-22,22>>^ However, every bad and good-for-nothing man out of the men that had gone with David answered and kept saying: “For the reason that they did not go with us,^&#42;1^ we will give them none of the spoil that we delivered, except to each one his wife and his sons, and let them lead them and go.”

[NOTE]
====
. “With us,” LXXSyVg and six Heb. mss; M, “with me.”
====

[[v9-30-23]]

^<<v9-30-23,23>>^ But David said: “YOU must not do that way, my brothers, with what Jehovah has given us, in that he safeguarded us and gave the marauder band that came against us into our hand.

[[v9-30-24]]

^<<v9-30-24,24>>^ And who will listen to YOU as to this saying?^&#42;1^ For as the share of the one that went down into the battle even so will the share of the one that sat by the baggage be. All will have a share together.”

[NOTE]
====
. “This saying?” MSyVg; LXX, “this saying? For they are not less than you are.”
====

[[v9-30-25]]

^<<v9-30-25,25>>^ And it came about from that day forward that he kept it set as a regulation and a judicial decision for Israel down to this day.

[[v9-30-26]]

^<<v9-30-26,26>>^ When David came to Zikʹlag he proceeded to send some of the spoil to the older men of Judah, his friends, saying: “Here is a gift blessing for YOU from the spoil of Jehovah’s enemies.”

[[v9-30-27]]

^<<v9-30-27,27>>^ To those who were in Bethʹel, and to those in Raʹmoth of the south, and to those in Jatʹtir,

[[v9-30-28]]

^<<v9-30-28,28>>^ and to those in A·roʹer, and to those in Siphʹmoth, and to those in Esh·te·moʹa,

[[v9-30-29]]

^<<v9-30-29,29>>^ and to those in Raʹcal, and to those in the cities of the Je·rahʹme·el·ites, and to those in the cities of the Kenʹites,

[[v9-30-30]]

^<<v9-30-30,30>>^ and to those in Horʹmah, and to those in Borʹa·shan, and to those in Aʹthach,

[[v9-30-31]]

^<<v9-30-31,31>>^ and to those in Heʹbron, and to all the places where David had walked about, he and his men.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]