include::./index.adoc[]

[[v9-4-0]]
=== The First of Samuel, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-4-1]]

^<<v9-4-1,1>>^ And the word of Samuel continued to come^&#42;1^ to all Israel.^&#42;2^
Then Israel went out to meet the Phi·lisʹtines^&#42;3^ in battle; and they took up camping alongside^&#42;4^ Eb·en·eʹzer,^&#42;5^ and the Phi·lisʹtines themselves encamped in Aʹphek.

[NOTE]
====
. Or, “occur.”
. Many Heb. mss have an open space here, possibly to indicate an omission, which would be filled by this addition of LXX: “And it occurred in those days that the Philistines began gathering together against Israel for battle.”
. Or, “went out against the Philistines,” M; LXX, “went out to meet them.”
. Or, “upon.”
. “Ebenezer.” Lit., “the Stone Help.” Heb., ha·ʼEʹven (“the Stone”) ha·ʽEʹzer (“the Help”); Gr., A·be·neʹzer; Vg, “the Stone of Help.” Compare 7:12 ftn, “Ebenezer.”
====

[[v9-4-2]]

^<<v9-4-2,2>>^ And the Phi·lisʹtines proceeded to draw up in formation to meet Israel, and the battle went badly,^&#42;1^ so that Israel was defeated before the Phi·lisʹtines, who went striking down about four thousand men^&#42;2^ in closed battle line in the field.

[NOTE]
====
. “The battle kept inclining,” LXX, that is, adversely to Israel.
. “Who went striking down about four thousand men,” M; LXXSyVg, “and (about) four thousand men were struck down.”
====

[[v9-4-3]]

^<<v9-4-3,3>>^ When the people came to the camp the older men^&#42;1^ of Israel began to say: “Why did Jehovah defeat us today before the Phi·lisʹtines? Let us take to ourselves from Shiʹloh the ark of Jehovah’s covenant, that it may come into our midst and may save us from the palm of our enemies.”

[NOTE]
====
. Or, “elders.”
====

[[v9-4-4]]

^<<v9-4-4,4>>^ So the people sent to Shiʹloh and carried from there the ark of the covenant of Jehovah of armies, who is sitting upon^&#42;1^ the cherubs. And the two sons of Eʹli were there with the ark of the covenant of the &#91;true&#93; God,^&#42;2^ namely, Hophʹni and Phinʹe·has.

[NOTE]
====
. Or, “between.” M omits.
. “The [true] God.” Heb., ha·ʼElo·himʹ; SyVg, “Jehovah”; Vgc, “God.” See App 1F.
====

[[v9-4-5]]

^<<v9-4-5,5>>^ And it came about that as soon as the ark of the covenant of Jehovah came into the camp, all the Israelites broke out into loud shouting, so that the earth was in a stir.

[[v9-4-6]]

^<<v9-4-6,6>>^ The Phi·lisʹtines also got to hear the sound of the shouting and began saying: “What does the sound of this loud shouting in the camp of the Hebrews mean?” Finally they got to know that the ark of Jehovah itself had come into the camp.

[[v9-4-7]]

^<<v9-4-7,7>>^ And the Phi·lisʹtines became afraid, because, they said: “God^&#42;1^ has come into the camp!” So they said: “Woe to us, for such a thing as this never occurred before!

[NOTE]
====
. “God.” Heb., ʼElo·himʹ, pl. to denote majesty, with the sing. verb “has come”; LXX, “These gods”; Lat., Deʹus.
====

[[v9-4-8]]

^<<v9-4-8,8>>^ Woe to us! Who will save us from the hand of this majestic God? This is the God that was the smiter^&#42;1^ of Egypt with every sort of slaughter in the wilderness.

[NOTE]
====
. Or, “these majestic gods? These are the gods that were the smiters.” These words are pl. in M and may denote majesty even by the pagan Philistines. See 5:7 ftn.
====

[[v9-4-9]]

^<<v9-4-9,9>>^ Show yourselves courageous and prove yourselves men, YOU Phi·lisʹtines, that YOU may not serve the Hebrews just as they have served YOU; and YOU must prove yourselves men and fight!”

[[v9-4-10]]

^<<v9-4-10,10>>^ Accordingly the Phi·lisʹtines fought and Israel was defeated, and they went fleeing each one to his tent;^&#42;1^ and the slaughter came to be very great, so that out of Israel there fell thirty thousand men on foot.

[NOTE]
====
. “Tent,” LXXSyVg; M, “tents.”
====

[[v9-4-11]]

^<<v9-4-11,11>>^ And the ark of God^&#42;1^ itself was captured, and the two sons of Eʹli, Hophʹni and Phinʹe·has, died.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Gr., The·ouʹ; Lat., Deʹi; Sy, “Jehovah.”
====

[[v9-4-12]]

^<<v9-4-12,12>>^ And a man of Benjamin went running from the battle line so that he arrived at Shiʹloh on that day with his garments ripped apart and dirt on his head.

[[v9-4-13]]

^<<v9-4-13,13>>^ When he arrived, there was Eʹli sitting on the seat by the roadside, watching, because his heart had become atremble over the ark of the &#91;true&#93; God. And the man himself went in to report in the city, and the whole city began crying out.

[[v9-4-14]]

^<<v9-4-14,14>>^ And Eʹli got to hear the sound of the outcry. So he said: “What does the sound of this turmoil mean?” And the man himself hurried that he might go in and report to Eʹli.

[[v9-4-15]]

^<<v9-4-15,15>>^ (Now Eʹli was ninety-eight years old, and his eyes had set so that he was unable to see.)

[[v9-4-16]]

^<<v9-4-16,16>>^ And the man proceeded to say to Eʹli: “I am the one coming from the battle line,^&#42;1^ and I—it is from the battle line that I have fled today.” At this he said: “What is the thing that has happened, my son?”

[NOTE]
====
. “Battle line,” M; Vg, “battle”; LXX, “camp.”
====

[[v9-4-17]]

^<<v9-4-17,17>>^ So the news bearer answered and said: “Israel has fled before the Phi·lisʹtines, and there has also occurred a great defeat among the people; and also your own two sons have died—Hophʹni and Phinʹe·has—and the very ark of the &#91;true&#93; God has been captured.”

[[v9-4-18]]

^<<v9-4-18,18>>^ And it came about that at the moment that he mentioned^&#42;1^ the ark of the &#91;true&#93; God, he began to fall from the seat backward beside the gate, and his neck got broken so that he died, because the man was old and heavy; and he himself had judged Israel forty years.

[NOTE]
====
. Or, “brought to remembrance.”
====

[[v9-4-19]]

^<<v9-4-19,19>>^ And his daughter-in-law, the wife of Phinʹe·has, was pregnant near to giving birth, and she got to hear the report that the ark of the &#91;true&#93; God was captured and that her father-in-law and her husband had died. At that she bowed herself and began giving birth, because her pangs came unexpectedly^&#42;1^ upon her.

[NOTE]
====
. Lit., “her pangs turned.”
====

[[v9-4-20]]

^<<v9-4-20,20>>^ And about the time of her death, the women standing by her began to speak: “Do not be afraid, because it is a son that you have borne.” And she did not answer and did not set her heart on it.

[[v9-4-21]]

^<<v9-4-21,21>>^ But she called the boy Ichʹa·bod,^&#42;1^ saying: “Glory has gone away from Israel into exile,” &#91;this&#93; with reference to the ark of the &#91;true&#93; God’s being captured and with reference to her father-in-law and her husband.

[NOTE]
====
. Meaning “Where Is the Glory?”
====

[[v9-4-22]]

^<<v9-4-22,22>>^ So she said: “Glory has gone away from Israel into exile, because the ark of the &#91;true&#93; God^&#42;1^ has been captured.”

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElo·himʹ; LXX, “Jehovah.” See App 1F.
====

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]