include::./index.adoc[]

[[v9-5-0]]
=== The First of Samuel, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-5-1]]

^<<v9-5-1,1>>^ As for the Phi·lisʹtines, they took the ark of the &#91;true&#93; God and then brought it from Eb·en·eʹzer to Ashʹdod.

[[v9-5-2]]

^<<v9-5-2,2>>^ And the Phi·lisʹtines proceeded to take the ark of the &#91;true&#93; God and bring it into the house of Daʹgon and station it beside Daʹgon.

[[v9-5-3]]

^<<v9-5-3,3>>^ Then the Ashʹdod·ites got up early the very next day,^&#42;1^ and there Daʹgon was fallen upon his face to the earth before the ark of Jehovah. So they took^&#42;2^ Daʹgon and returned him to his place.

[NOTE]
====
. LXX adds: “and went into the house of Dagon and looked.”
. “Took,” MSyVg; LXX, “raised up.”
====

[[v9-5-4]]

^<<v9-5-4,4>>^ When they got up early in the morning the very day after, there Daʹgon was fallen upon his face to the earth before the ark of Jehovah, with the head of Daʹgon and the palms of both his hands cut off, to the threshold.^&#42;1^ Only the fish part^&#42;2^ had been left upon him.

[NOTE]
====
. Or, “podium.”
. Lit., “Only Dagon,” as the Dagon idol was seemingly half man, half fish.
====

[[v9-5-5]]

^<<v9-5-5,5>>^ That is why the priests of Daʹgon and all those going into the house of Daʹgon do not tread upon the threshold of Daʹgon in Ashʹdod down to this day.^&#42;1^

[NOTE]
====
. LXX adds: “because those stepping (leaping) over step (leap) over.” Compare Zep 1:9.
====

[[v9-5-6]]

^<<v9-5-6,6>>^ And the hand of Jehovah came to be heavy upon the Ashʹdod·ites, and he began causing panic^&#42;1^ and striking them with piles,^&#42;2^ namely, Ashʹdod and its territories.

[NOTE]
====
. Or, “began desolating [them].”
. Or, “with plague boils.” Heb., baʽ·pho·limʹ. Since this Heb. word is associated with the human anus, the Masoretes, as a show of modesty, pointed the word with the vowels for techo·rimʹ, “tumors.” They also showed this word in the margin, for it to be read instead.
====

[[v9-5-7]]

^<<v9-5-7,7>>^ And the men of Ashʹdod came to see that it was so, and they said: “Do not let the ark of the God of Israel dwell with us, because his hand has been hard against us and against Daʹgon our god.”^&#42;1^

[NOTE]
====
. “Our god.” Heb., ʼelo·hehʹnu, pl. to denote majesty, applied to Dagon; Gr., the·onʹ; Lat., deʹum. Compare Jg 16:23 ftn.
====

[[v9-5-8]]

^<<v9-5-8,8>>^ Consequently they sent and gathered all the axis lords of the Phi·lisʹtines to them and said: “What shall we do to the ark of the God of Israel?” Finally they said: “Toward Gath let the ark of the God of Israel go around.” So they brought the ark of the God of Israel around to there.^&#42;1^

[NOTE]
====
. “To Gath,” LXX.
====

[[v9-5-9]]

^<<v9-5-9,9>>^ And it came about that after they had brought it around to there, the hand of Jehovah came to be upon the city with a very great confusion, and he began striking the men of the city, from small to great, and piles began breaking out on them.^&#42;1^

[NOTE]
====
. “From small to great, and their rectums protruding began putrefying. And the people of Gath took counsel together and made themselves seats of skins,” Vgc.
====

[[v9-5-10]]

^<<v9-5-10,10>>^ Hence they sent the ark of the &#91;true&#93; God^&#42;1^ to Ekʹron. And it came about that as soon as the ark of the &#91;true&#93; God came to Ekʹron, the Ekʹron·ites began to cry out, saying: “They have brought the ark of the God of Israel around to me to put me and my people to death!”

[NOTE]
====
. “The [true] God.” Heb., ha·­ʼElo·himʹ, the definite article ha, “the,” preceding the title ʼElo·himʹ to distinguish him from the false god Dagon. See App 1F.
====

[[v9-5-11]]

^<<v9-5-11,11>>^ Consequently they sent and gathered all the axis lords of the Phi·lisʹtines and said: “SEND the ark of the God of Israel away that it may return to its place and may not put me and my people to death.” For a death-dealing confusion had occurred in the whole city; the hand of the &#91;true&#93; God had been very heavy there,

[[v9-5-12]]

^<<v9-5-12,12>>^ and the men that did not die had been struck with piles. And the cry of the city for help kept ascending to the heavens.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]