include::./index.adoc[]

[[v9-14-0]]
=== The First of Samuel, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-14-1]]

^<<v9-14-1,1>>^ And it came about one day that Jonʹa·than the son of Saul proceeded to say to the attendant carrying his weapons: “Do come and let us cross over to the outpost of the Phi·lisʹtines who are across over there.” But to his father he did not tell it.

[[v9-14-2]]

^<<v9-14-2,2>>^ And Saul was dwelling at the outskirts of Gibʹe·ah under the pomegranate tree that is in Migʹron; and the people that were with him were about six hundred men.

[[v9-14-3]]

^<<v9-14-3,3>>^ (And A·hiʹjah the son of A·hiʹtub, the brother of Ichʹa·bod, the son of Phinʹe·has, the son of Eʹli, the priest of Jehovah in Shiʹloh, was carrying the ephʹod.) And the people themselves did not know that Jonʹa·than had gone.

[[v9-14-4]]

^<<v9-14-4,4>>^ Now between the passages that Jonʹa·than looked for to cross over against the outpost of the Phi·lisʹtines there was a toothlike crag^&#42;1^ here on this side and a toothlike crag there on that side, and the name of the one was Boʹzez and the name of the other was Seʹneh.

[NOTE]
====
. Lit., “tooth of the crag.”
====

[[v9-14-5]]

^<<v9-14-5,5>>^ The one tooth was a pillar^&#42;1^ on the north facing Michʹmash, and the other was on the south facing Geʹba.

[NOTE]
====
. “A pillar,” M; LXX omits.
====

[[v9-14-6]]

^<<v9-14-6,6>>^ So Jonʹa·than^&#42;1^ said to the attendant, his armor-bearer: “Do come and let us cross over to the outpost of these uncircumcised men. Perhaps Jehovah will work for us, for there is no hindrance to Jehovah to save by many or by few.”

[NOTE]
====
. Lit., “Jehonathan.”
====

[[v9-14-7]]

^<<v9-14-7,7>>^ At this his armor-bearer said to him: “Do whatever is in your heart. Turn where you wish to. Here I am with you in accord with your heart.”

[[v9-14-8]]

^<<v9-14-8,8>>^ Then Jonʹa·than said: “Here we are crossing over to the men, and let us expose ourselves to them.

[[v9-14-9]]

^<<v9-14-9,9>>^ If this is the way they should say to us, ‘Stand still until we make contact with YOU!’ we must then stand where we are, and we should not go on up to them.

[[v9-14-10]]

^<<v9-14-10,10>>^ But if this is the way they should say, ‘Come up against us!’ we must then go up, because Jehovah will certainly give them into our hand, and this is for us the sign.”

[[v9-14-11]]

^<<v9-14-11,11>>^ With that the two of them exposed themselves to the outpost of the Phi·lisʹtines. And the Phi·lisʹtines proceeded to say: “Here are the Hebrews coming out from the holes where they have hidden themselves.”

[[v9-14-12]]

^<<v9-14-12,12>>^ So the men of the outpost answered Jonʹa·than and his armor-bearer and said: “Come on up to us, and we will let YOU know a thing!” At once Jonʹa·than said to his armor-bearer: “Come up after me, because Jehovah will certainly give them into the hand of Israel.”

[[v9-14-13]]

^<<v9-14-13,13>>^ And Jonʹa·than kept going up on his hands and his feet, and his armor-bearer after him; and they began to fall before Jonʹa·than, and his armor-bearer was putting them to death behind him.

[[v9-14-14]]

^<<v9-14-14,14>>^ And the first slaughter with which Jonʹa·than and his armor-bearer struck them down amounted to about twenty men within about half the plowing line in an acre of field.^&#42;1^

[NOTE]
====
. “In an acre of field.” Lit., “a span of a field,” that is, the measure of land that a span of bulls can plow in a day.
====

[[v9-14-15]]

^<<v9-14-15,15>>^ Then a trembling occurred in the camp in the field and among all the people of the outpost; and the force of pillagers trembled, even they, and the earth began quaking, and it developed into a trembling from God.

[[v9-14-16]]

^<<v9-14-16,16>>^ And the watchmen belonging to Saul in Gibʹe·ah of Benjamin got to see it, and, look! the turmoil swayed this way and that.^&#42;1^

[NOTE]
====
. “And, look! the camp was in a commotion from one end to the other,” LXX.
====

[[v9-14-17]]

^<<v9-14-17,17>>^ And Saul proceeded to say to the people that were with him: “Take the count, please, and see who has gone out from us.” When they took the count, why, look! Jonʹa·than and his armor-bearer were not there.

[[v9-14-18]]

^<<v9-14-18,18>>^ Saul now said to A·hiʹjah: “Do bring the ark of the &#91;true&#93; God near!” (For the ark of the &#91;true&#93; God proved to be on that day with the sons of Israel.)^&#42;1^

[NOTE]
====
. “To Ahijah: ‘Bring the ephod near!’ (For he carried the ephod in that day before Israel.),” LXX.
====

[[v9-14-19]]

^<<v9-14-19,19>>^ And it came about that while Saul was speaking to the priest, the turmoil that was in the camp of the Phi·lisʹtines continued to go on, getting greater and greater. Then Saul said to the priest: “Withdraw your hand.”

[[v9-14-20]]

^<<v9-14-20,20>>^ Thus Saul and all the people that were with him were called out. So they came as far as the battle, and there the sword of each one had come to be against his fellowman; the rout was very great.

[[v9-14-21]]

^<<v9-14-21,21>>^ And the Hebrews that had come to belong to the Phi·lisʹtines as formerly and that had gone up with them into the camp round about, even they too were for proving themselves to be with Israel who was with Saul and Jonʹa·than.^&#42;1^

[NOTE]
====
. “And the slaves who were formerly with the Philistines, going up into the camp, turned around and they were for being with the Israelites who were with Saul and Jonathan,” LXX.
====

[[v9-14-22]]

^<<v9-14-22,22>>^ All the men of Israel also that were hidden in the mountainous region of Eʹphra·im heard that the Phi·lisʹtines had taken to flight, and they too went pursuing closely after them into the battle.

[[v9-14-23]]

^<<v9-14-23,23>>^ And Jehovah proceeded on that day to save Israel, and the battle itself passed over to Beth-aʹven.^&#42;1^

[NOTE]
====
. “And the battle passed over to Beth-aven. And all the people with Saul were about ten thousand men. And the battle was spread about to every city in the mountainous region of Ephraim,” LXX.
====

[[v9-14-24]]

^<<v9-14-24,24>>^ And the men of Israel themselves were hard pressed^&#42;1^ on that day, and yet Saul put the people under the pledge of an oath,^&#42;2^ saying: “Cursed is the man that eats bread before the evening and until I have taken vengeance upon my enemies!” And none of the people tasted bread.

[NOTE]
====
. “Were hard pressed,” by a slight change of vowel pointing; M, “drew near.”
. “And yet Saul . . . oath,” by a slight emendation; M, “and Saul acted willfully with the people”; LXX, “And Saul ignorantly committed a great sin of error on that day and put the people under a curse (saying: ‘Accursed is the man that eats bread before evening’).”
====

[[v9-14-25]]

^<<v9-14-25,25>>^ And all those of the land came into the woods, when honey happened to be over all the surface of the field.

[[v9-14-26]]

^<<v9-14-26,26>>^ When the people came into the woods, why, look! there was a dripping of honey, but there was no one putting his hand to his mouth, because the people were afraid of the oath.

[[v9-14-27]]

^<<v9-14-27,27>>^ As for Jonʹa·than, he had not been listening when his father put the people under an oath, so he stretched out the tip of the rod that was in his hand and dipped it into the honeycomb and drew his hand back to his mouth, and his eyes began to beam.

[[v9-14-28]]

^<<v9-14-28,28>>^ At this one of the people answered and said: “Your father solemnly put the people under oath, saying, ‘Cursed is the man that eats bread today!’” (And the people began to get tired.)

[[v9-14-29]]

^<<v9-14-29,29>>^ However, Jonʹa·than said: “My father has brought ostracism upon the land. SEE, please, how my eyes have beamed because I tasted this little bit of honey.

[[v9-14-30]]

^<<v9-14-30,30>>^ How much more so if the people had but eaten today from the spoil of their enemies that they found! For now the slaughter upon the Phi·lisʹtines has not been great.”

[[v9-14-31]]

^<<v9-14-31,31>>^ And on that day they kept striking down the Phi·lisʹtines from Michʹmash to Aiʹja·lon, and the people got to be very tired.

[[v9-14-32]]

^<<v9-14-32,32>>^ And the people began darting greedily at the spoil and taking sheep and cattle and calves and slaughtering them on the earth, and the people fell to eating along with the blood.

[[v9-14-33]]

^<<v9-14-33,33>>^ So they told Saul, saying: “Look! The people are sinning against Jehovah by eating along with the blood.” At this he said: “YOU have dealt treacherously. First of all, roll a great stone to me.”

[[v9-14-34]]

^<<v9-14-34,34>>^ After that Saul said: “Scatter among the people, and YOU must say to them, ‘Bring near to me, each one of YOU, his bull and, each one, his sheep, and YOU must do the slaughtering in this place and the eating, and YOU must not sin against Jehovah by eating along with the blood.’” Accordingly all the people brought near each one his bull that was in his hand that night and did the slaughtering there.

[[v9-14-35]]

^<<v9-14-35,35>>^ And Saul proceeded to build an altar to Jehovah. With it he started altar building to Jehovah.

[[v9-14-36]]

^<<v9-14-36,36>>^ Later Saul said: “Let us go down after the Phi·lisʹtines by night and plunder them until the morning lightens up, and let us not leave a single one among them.” To this they said: “Anything that is good in your eyes do.” Then the priest said: “Let us approach here to the &#91;true&#93; God.”

[[v9-14-37]]

^<<v9-14-37,37>>^ And Saul began to inquire of God: “Shall I go down after the Phi·lisʹtines? Will you give them into the hand of Israel?” And he did not answer him on that day.

[[v9-14-38]]

^<<v9-14-38,38>>^ So Saul said: “Come near here, all YOU keymen^&#42;1^ of the people, and ascertain and see in what way this sin has come to be today.

[NOTE]
====
. Lit., “the corner towers,” pictorial of vital or important men, chiefs.
====

[[v9-14-39]]

^<<v9-14-39,39>>^ For as Jehovah, who is the Deliverer of Israel, is alive, even if it is in Jonʹa·than my son, yet he will positively die.” But there was no one answering him out of all the people.

[[v9-14-40]]

^<<v9-14-40,40>>^ And he went on to say to all Israel: “YOU yourselves will come to be on the one side, and I and Jonʹa·than my son—we will come to be on the other side.” At this the people said to Saul: “What is good in your eyes do.”

[[v9-14-41]]

^<<v9-14-41,41>>^ And Saul proceeded to say to Jehovah: “O God of Israel,^&#42;1^ do give Thumʹmim!” Then Jonʹa·than and Saul were taken, and the people themselves went out.

[NOTE]
====
. LXX adds: “why is it that you did not answer your servant today? If in me or in Jonathan my son the unrighteousness is, O Jehovah, the God of Israel, give clear manifestations [Urim]. And if thus you should say, In your people Israel, then give holiness [Thummim]”; ItVgc make a similar addition. See Ex 28:30 ftn, “Thummim.”
====

[[v9-14-42]]

^<<v9-14-42,42>>^ Saul now said: “CAST lots to decide between me and Jonʹa·than my son.” And Jonʹa·than got to be taken.

[[v9-14-43]]

^<<v9-14-43,43>>^ Then Saul said to Jonʹa·than: “Do tell me, What have you done?” So Jonʹa·than told him and said: “I did for a fact taste a little honey on the tip of the rod that is in my hand. Here I am! Let me die!”

[[v9-14-44]]

^<<v9-14-44,44>>^ At this Saul said: “Thus may God do and thus may he add to it, if you do not positively die, Jonʹa·than.”

[[v9-14-45]]

^<<v9-14-45,45>>^ But the people said to Saul: “Is Jonʹa·than to die, who has performed this great salvation in Israel? It is unthinkable! As Jehovah is alive, not as much as a single hair of his head will fall to the earth; for it was with God that he worked this day.” With that the people redeemed Jonʹa·than, and he did not die.

[[v9-14-46]]

^<<v9-14-46,46>>^ So Saul withdrew from following the Phi·lisʹtines, and the Phi·lisʹtines themselves went to their place.

[[v9-14-47]]

^<<v9-14-47,47>>^ And Saul himself took the kingship over Israel and went warring round about against all his enemies, against Moʹab and against the sons of Amʹmon and against Eʹdom and against the kings of Zoʹbah and against the Phi·lisʹtines; and wherever he would turn he administered condemnation.^&#42;1^

[NOTE]
====
. Or, “he was victorious,” in agreement with LXXVg; M, “he treated as wicked (condemned).”
====

[[v9-14-48]]

^<<v9-14-48,48>>^ And he went on acting valiantly and proceeded to strike down Amʹa·lek and to deliver Israel out of the hand of their pillager.

[[v9-14-49]]

^<<v9-14-49,49>>^ And the sons of Saul came to be Jonʹa·than and Ishʹvi and Malʹchi-shuʹa, and, as for the names of his two daughters, the name of the one born first was Meʹrab and the name of the younger one Miʹchal.

[[v9-14-50]]

^<<v9-14-50,50>>^ And the name of Saul’s wife was A·hinʹo·am the daughter of A·himʹa·az, and the name of the chief of his army was Abʹner the son of Ner, the uncle^&#42;1^ of Saul.

[NOTE]
====
. According to 1Ch 8:33, Ner was the grandfather of Saul, therefore, Abner, as the brother of Kish (vs 51), was the uncle of Saul.
====

[[v9-14-51]]

^<<v9-14-51,51>>^ And Kish was the father of Saul, and Ner the father of Abʹner was the son^&#42;1^ of A·biʹel.^&#42;2^

[NOTE]
====
. “Son,” MSyVg; LXX, “the son of Jamin, the son (of Abiel).”
. Or, “And Kish, the father of Saul, and Ner, the father of Abner, were the sons of Abiel.” See 9:1; Josephus’ Jewish Antiquities, Book VI, chapter 6, ¶6.
====

[[v9-14-52]]

^<<v9-14-52,52>>^ And the warfare continued heavy against the Phi·lisʹtines all the days of Saul. When Saul saw any mighty man or any valiant person, he would gather him to himself.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]