include::./index.adoc[]

[[v9-10-0]]
=== The First of Samuel, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-10-1]]

^<<v9-10-1,1>>^ Samuel then took the flask of oil and poured it out upon his head and kissed him and said: “Is it not because Jehovah^&#42;1^ has anointed you as a leader over his inheritance?

[NOTE]
====
. Here the Heb. scribe may have made an omission (homoeoteleuton). LXX reads: “Has Jehovah anointed you as a leader over his people, over Israel? And you will rule over Jehovah’s people, and you will save them out of the hand of their enemies round about. And this will be the sign to you that Jehovah”; Vgc is similar.
====

[[v9-10-2]]

^<<v9-10-2,2>>^ On your going away from me today you will certainly find two men close by the tomb of Rachel in the territory of Benjamin at Zelʹzah, and they will certainly say to you, ‘The she-asses that you have gone to look for have been found, but now your father has given up the matter of the she-asses and has become anxious about YOU men, saying: “What shall I do about my son?”’

[[v9-10-3]]

^<<v9-10-3,3>>^ And you must pass on from there still farther and come as far as the big tree of Taʹbor, and there there must encounter you three men going up to the &#91;true&#93; God at Bethʹel, one carrying three kids and one carrying three round loaves of bread and one carrying a large jar of wine.

[[v9-10-4]]

^<<v9-10-4,4>>^ And they will certainly ask about your welfare and give you two loaves, and you must accept them from their hand.

[[v9-10-5]]

^<<v9-10-5,5>>^ It is after that that you will come to the hill of the &#91;true&#93; God, where there is a garrison of the Phi·lisʹtines. And it should come about that at the time of your coming there to the city, you will certainly meet a group of prophets coming down from the high place, and ahead of them a stringed instrument and tambourine and flute and harp, while they are speaking as prophets.

[[v9-10-6]]

^<<v9-10-6,6>>^ And the spirit of Jehovah will certainly become operative upon you, and you will certainly speak as a prophet along with them and be changed into another man.

[[v9-10-7]]

^<<v9-10-7,7>>^ And it must occur that when these signs come to you, do for yourself what your hand finds possible, because the &#91;true&#93; God is with you.

[[v9-10-8]]

^<<v9-10-8,8>>^ And you must go down ahead of me to Gilʹgal; and, look! I am going down to you to offer up burnt sacrifices, to render up communion sacrifices. Seven days you should keep waiting until my coming to you, and I shall certainly let you know what you should do.”

[[v9-10-9]]

^<<v9-10-9,9>>^ And it occurred that as soon as he turned his shoulder to go from Samuel, God began changing the heart of his into another; and all these signs proceeded to come true on that day.

[[v9-10-10]]

^<<v9-10-10,10>>^ So they went from there to the hill, and here there was a group of prophets to meet him; at once the spirit of God became operative upon him, and he began to speak as a prophet in the middle of them.

[[v9-10-11]]

^<<v9-10-11,11>>^ And it came about that when all those knowing him formerly saw him, look! it was with prophets that he prophesied. Consequently the people said one to another: “What is this that has happened to the son of Kish? Is Saul also among the prophets?”

[[v9-10-12]]

^<<v9-10-12,12>>^ Then a man from there answered and said: “But who is their father?” That is why it has become a proverbial saying: “Is Saul also among the prophets?”

[[v9-10-13]]

^<<v9-10-13,13>>^ At length he finished speaking as a prophet and came to the high place.

[[v9-10-14]]

^<<v9-10-14,14>>^ Later the brother of Saul’s father said to him and to his attendant: “Where did YOU go?” Upon that he said: “To look for the she-asses, and we kept on going to see, but they were not &#91;there&#93;. So we came to Samuel.”

[[v9-10-15]]

^<<v9-10-15,15>>^ At this Saul’s uncle said: “Do tell me, please, What did Samuel say to YOU men?”

[[v9-10-16]]

^<<v9-10-16,16>>^ In turn Saul said to his uncle: “He told us unmistakably that the she-asses had been found.” And the matter of the kingship about which Samuel had talked, he did not tell him.

[[v9-10-17]]

^<<v9-10-17,17>>^ And Samuel proceeded to call the people together to Jehovah at Mizʹpah

[[v9-10-18]]

^<<v9-10-18,18>>^ and to say to the sons of Israel: “This is what Jehovah the God of Israel has said, ‘It was I who brought Israel up out of Egypt and who went delivering YOU from the hand of Egypt and from the hand of all the kingdoms that were oppressing YOU.

[[v9-10-19]]

^<<v9-10-19,19>>^ But YOU—today YOU have rejected YOUR God who was a savior to YOU out of all YOUR evils and YOUR distresses, and YOU went on to say: “No, but^&#42;1^ a king is what you should put over us.” And now take YOUR stand before Jehovah by YOUR tribes and by YOUR thousands.’”^&#42;2^

[NOTE]
====
. “Say: ‘No, but,’ ” LXXSyVg and 35 Heb. mss; M, “say to him: ‘But.’ ”
. Or, “tribal subdivisions.”
====

[[v9-10-20]]

^<<v9-10-20,20>>^ Accordingly Samuel had all the tribes of Israel draw near, and the tribe of Benjamin came to be picked.

[[v9-10-21]]

^<<v9-10-21,21>>^ Then he had the tribe of Benjamin draw near by its families, and the family of the Matʹrites came to be picked.^&#42;1^ Finally Saul the son of Kish came to be picked. And they went looking for him, and he was not to be found.

[NOTE]
====
. LXX adds: “And they bring the family of the Matrites near, man by man.”
====

[[v9-10-22]]

^<<v9-10-22,22>>^ Hence they inquired further of Jehovah: “Has the man come here as yet?” To this Jehovah said: “Here he is, hidden among the luggage.”

[[v9-10-23]]

^<<v9-10-23,23>>^ So they went running and took him from there. When he took his stand in the middle of the people, he was taller than all the other people from his shoulders upward.

[[v9-10-24]]

^<<v9-10-24,24>>^ Then Samuel said to all the people: “Have YOU seen the one whom Jehovah has chosen, that there is none like him among all the people?” And all the people began to shout and say: “Let the king live!”

[[v9-10-25]]

^<<v9-10-25,25>>^ Upon that Samuel spoke to the people about the rightful due of the kingship and wrote it in a book and deposited it before Jehovah. Then Samuel sent all the people away, each one to his house.

[[v9-10-26]]

^<<v9-10-26,26>>^ As for Saul himself, he went to his home at Gibʹe·ah, and the valiant men whose heart God had touched proceeded to go with him.

[[v9-10-27]]

^<<v9-10-27,27>>^ As for the good-for-nothing men, they said: “How will this one save us?” Accordingly they despised him, and they did not bring any gift to him. But he continued like one grown speechless.^&#42;1^

[NOTE]
====
. “But he continued like one grown speechless,” M; by an emendation in agreement with LXX, “And it came about approximately a month later.” LXX begins chapter 11 with these words.
====

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]