include::./index.adoc[]

[[v9-26-0]]
=== The First of Samuel, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-26-1]]

^<<v9-26-1,1>>^ In time the men of Ziph^&#42;1^ came to Saul at Gibʹe·ah, saying: “Is not David concealing himself^&#42;2^ on the hill of Hach·iʹlah, facing Je·shiʹmon?”^&#42;3^

[NOTE]
====
. Or, “the Ziphites.”
. “Concealing himself close by us,” LXX.
. Or, “the desert.”
====

[[v9-26-2]]

^<<v9-26-2,2>>^ And Saul proceeded to rise up and go down to the wilderness of Ziph, and with him three thousand men, the chosen ones of Israel, to look for David in the wilderness of Ziph.

[[v9-26-3]]

^<<v9-26-3,3>>^ And Saul took up camping on the hill of Hach·iʹlah, which faces Je·shiʹmon, by the road, while David was dwelling in the wilderness. And he got to see that Saul had come after him into the wilderness.

[[v9-26-4]]

^<<v9-26-4,4>>^ So David sent spies that he might know that Saul had for a fact come.

[[v9-26-5]]

^<<v9-26-5,5>>^ Later David rose up and went to the place where Saul had encamped, and David got to see the place where Saul had lain down, and also Abʹner the son of Ner the chief of his army; and Saul was lying in the camp enclosure with the people camping all around him.

[[v9-26-6]]

^<<v9-26-6,6>>^ Then David answered and said to A·himʹe·lech the Hitʹtite and A·bishʹai the son of Ze·ruʹiah, the brother of Joʹab: “Who will go down with me to Saul into the camp?” To this A·bishʹai said: “I myself shall go down with you.”

[[v9-26-7]]

^<<v9-26-7,7>>^ And David made his way with A·bishʹai to the people by night; and, look! Saul was lying asleep in the camp enclosure with his spear stuck into the earth at his head, and Abʹner and the people were lying all around him.

[[v9-26-8]]

^<<v9-26-8,8>>^ A·bishʹai now said to David: “God^&#42;1^ has today surrendered your enemy into your hand. And now let me, please, pin him to the earth with the spear just once, and I shall not do it to him twice.”

[NOTE]
====
. “God,” MVg; Sy, “Your God”; LXX, “Jehovah.”
====

[[v9-26-9]]

^<<v9-26-9,9>>^ However, David said to A·bishʹai: “Do not bring him to ruin, for who is it that has thrust his hand out against the anointed^&#42;1^ of Jehovah and has remained innocent?”

[NOTE]
====
. “Against the anointed of.” Heb., bim·shiʹach; Gr., khri·stonʹ; Syr., meshi·cheh; Lat., chriʹstum.
====

[[v9-26-10]]

^<<v9-26-10,10>>^ And David went on to say: “As Jehovah is living, Jehovah himself will deal him a blow; or his day will come and he will have to die, or down into battle he will go, and he will certainly be swept away.

[[v9-26-11]]

^<<v9-26-11,11>>^ It is unthinkable, on my part, from Jehovah’s standpoint, to thrust my hand out against the anointed of Jehovah! So now take, please, the spear that is at his head and the water jug, and let us get on our way.”

[[v9-26-12]]

^<<v9-26-12,12>>^ Accordingly David took the spear and the water jug from the place at Saul’s head, and then they got on their way; and there was no one seeing nor anyone taking note nor anyone waking up, for all of them were asleep, because it was a deep sleep from Jehovah that had fallen upon them.

[[v9-26-13]]

^<<v9-26-13,13>>^ Then David passed on to the other side and stood upon the top of the mountain at a distance, the space between them being vast.

[[v9-26-14]]

^<<v9-26-14,14>>^ And David began to call out to the people and to Abʹner the son of Ner, saying: “Will you not answer, Abʹner?” And Abʹner began to answer and say: “Who are you that have called out to the king?”

[[v9-26-15]]

^<<v9-26-15,15>>^ And David went on to say to Abʹner: “Are you not a man? And who is like you in Israel? Why, then, did you not watch over your lord^&#42;1^ the king? For one of the people came in to bring the king your lord to ruin.

[NOTE]
====
. “Your lord.” Heb., ʼadho·neyʹkha, pl. to denote excellence. See 20:38 ftn.
====

[[v9-26-16]]

^<<v9-26-16,16>>^ This thing that you have done is not good. As Jehovah is living, YOU men deserve to die,^&#42;1^ because YOU have not watched over YOUR lord, over the anointed of Jehovah. And now see where the king’s spear and the water jug are that were at his head.”

[NOTE]
====
. Lit., “you men are the sons of death.”
====

[[v9-26-17]]

^<<v9-26-17,17>>^ And Saul began to recognize the voice of David and to say: “Is this your voice, my son David?” To this David said: “It is my voice, my lord the king.”

[[v9-26-18]]

^<<v9-26-18,18>>^ And he added: “Why is this that my lord is chasing after his servant, for what have I done, and what badness is there in my hand?

[[v9-26-19]]

^<<v9-26-19,19>>^ And now let my lord the king, please, listen to the words of his servant: If it is Jehovah that has incited you against me, let him smell a grain offering. But if it is the sons of man,^&#42;1^ they are cursed before Jehovah, because they have driven me out today from feeling myself attached to the inheritance of Jehovah, saying, ‘Go, serve other gods!’

[NOTE]
====
. Lit., “sons of the man.” Heb., benehʹ ha·ʼa·dhamʹ.
====

[[v9-26-20]]

^<<v9-26-20,20>>^ And now do not let my blood fall to the earth before the face of Jehovah; for the king of Israel has gone out to look for a single flea,^&#42;1^ just as one chases a partridge upon the mountains.”

[NOTE]
====
. “Look for a single flea,” MSyVg; LXX, “look for my soul.”
====

[[v9-26-21]]

^<<v9-26-21,21>>^ In turn Saul said: “I have sinned. Come back, my son David, for I shall no more do you injury, in view of the fact that my soul has been precious in your eyes this day. Look! I have acted foolishly and am very much mistaken.”

[[v9-26-22]]

^<<v9-26-22,22>>^ Then David answered and said: “Here is the spear of the king, and let one of the young men come on over and fetch it.

[[v9-26-23]]

^<<v9-26-23,23>>^ And Jehovah it is who will repay to each one his own righteousness and his own faithfulness, in that Jehovah today gave you into my hand, and I was unwilling to thrust my hand out against the anointed of Jehovah.

[[v9-26-24]]

^<<v9-26-24,24>>^ And, look! just as your soul was great this day in my eyes, so may my soul be great in the eyes of Jehovah, that he may deliver me out of all distress.”

[[v9-26-25]]

^<<v9-26-25,25>>^ At this Saul said to David: “Blessed may you be, my son David. Not only will you without fail work but you will also without fail come off the winner.” And David proceeded to go on his way; and as for Saul, he returned to his place.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]