include::./index.adoc[]

[[v9-18-0]]
=== The First of Samuel, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-18-1]]

^<<v9-18-1,1>>^ And it came about that, as soon as he had finished speaking to Saul, Jonʹa·than’s^&#42;1^ very soul became bound up with the soul of David, and Jonʹa·than began to love him as his own soul.

[NOTE]
====
. Lit., “Jehonathan’s.” See 19:1 ftn.
====

[[v9-18-2]]

^<<v9-18-2,2>>^ Then Saul took him on that day, and he did not allow him to return to his father’s house.

[[v9-18-3]]

^<<v9-18-3,3>>^ And Jonʹa·than and David proceeded to conclude a covenant, because of his loving him as his own soul.

[[v9-18-4]]

^<<v9-18-4,4>>^ Further, Jonʹa·than stripped himself of the sleeveless coat that was on him and gave it to David, and also his garments, and even his sword and his bow and his belt.

[[v9-18-5]]

^<<v9-18-5,5>>^ And David began going out. Wherever Saul would send him he would act prudently, so that Saul placed him over the men of war; and it seemed good in the eyes of all the people and also in the eyes of the servants of Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ And it came about that at their coming in, when David returned from striking the Phi·lisʹtines^&#42;1^ down,^&#42;2^ the women began coming out from all the cities of Israel with song and dances to meet Saul the king, with tambourines, with rejoicing and with lutes.

[NOTE]
====
. Lit., “the Philistine,” but in a collective sense.
. LXXB omits from 17:55 to here.
====

[[v9-18-7]]

^<<v9-18-7,7>>^ And the women that were celebrating kept responding and saying:
“Saul has struck down his thousands,
And David his tens of thousands.”

[[v9-18-8]]

^<<v9-18-8,8>>^ And Saul began to be very angry, and this saying was bad from his viewpoint,^&#42;1^ so that he said: “They have given David tens of thousands, but to me they have given the thousands, and there is yet only the kingship to give him!”

[NOTE]
====
. Lit., “bad in his eyes.”
====

[[v9-18-9]]

^<<v9-18-9,9>>^ And Saul was continually looking suspiciously at David from that day forward.

[[v9-18-10]]

^<<v9-18-10,10>>^ And it came about the next day that God’s bad spirit became operative upon Saul, so that he behaved like a prophet within the house, while David was playing music with his hand, as in former days; and the spear was in Saul’s hand.

[[v9-18-11]]

^<<v9-18-11,11>>^ And Saul proceeded to hurl the spear and say: “I will pin David even to the wall!” but David turned aside from before him, twice.

[[v9-18-12]]

^<<v9-18-12,12>>^ And Saul grew afraid of David because Jehovah proved to be with him, but from Saul he had departed.

[[v9-18-13]]

^<<v9-18-13,13>>^ Consequently Saul removed him from his company and appointed him as chief of a thousand for him; and he regularly went out and came in before the people.

[[v9-18-14]]

^<<v9-18-14,14>>^ And David was continually acting prudently in all his ways, and Jehovah was with him.

[[v9-18-15]]

^<<v9-18-15,15>>^ And Saul kept seeing that he was acting very prudently, so that he was scared of him.

[[v9-18-16]]

^<<v9-18-16,16>>^ And all Israel and Judah were lovers of David, because he was going out and coming in before them.

[[v9-18-17]]

^<<v9-18-17,17>>^ Finally Saul said to David: “Here is my oldest daughter Meʹrab. She is the one that I shall give you as a wife. Only prove yourself a valiant person to me and fight the wars^&#42;1^ of Jehovah.” But as for Saul, he said to himself: “Do not let my hand come to be upon him, but let the hand of the Phi·lisʹtines come to be upon him.”

[NOTE]
====
. Or, “battles.”
====

[[v9-18-18]]

^<<v9-18-18,18>>^ At this David said to Saul: “Who am I and who are my kinsfolk, my father’s family, in Israel, so that I should become son-in-law to the king?”

[[v9-18-19]]

^<<v9-18-19,19>>^ However, it came about that at the time for giving Meʹrab, Saul’s daughter, to David, she herself had already been given to Aʹdri·el the Me·holʹath·ite as a wife.

[[v9-18-20]]

^<<v9-18-20,20>>^ Now Miʹchal, Saul’s daughter, was in love with David, and they went reporting it to Saul, and the matter was to his liking.^&#42;1^

[NOTE]
====
. Lit., “was right in his eyes.”
====

[[v9-18-21]]

^<<v9-18-21,21>>^ So Saul said: “I shall give her to him that she may serve as a snare to him, and that the hand of the Phi·lisʹtines may come to be upon him.” Accordingly Saul said to David: “By &#91;one of&#93; the two women^&#42;1^ you will form a marriage alliance with me today.”

[NOTE]
====
. “By one of the two women,” T; M, “By two,” that is, a second time.
====

[[v9-18-22]]

^<<v9-18-22,22>>^ Further, Saul commanded his servants: “Speak to David secretly, saying, ‘Look! The king has found delight in you, and all his servants themselves have fallen in love with you. So now form a marriage alliance with the king.’”

[[v9-18-23]]

^<<v9-18-23,23>>^ And the servants of Saul began to speak these words in the ears of David, but David said: “Is it an easy thing in YOUR eyes to form a marriage alliance with the king, when I am a man of little means and lightly esteemed?”

[[v9-18-24]]

^<<v9-18-24,24>>^ Then the servants of Saul reported to him, saying: “It was with words like these that David spoke.”

[[v9-18-25]]

^<<v9-18-25,25>>^ At that Saul said: “This is what YOU men will say to David, ‘The king has delight, not in marriage money, but in a hundred foreskins of the Phi·lisʹtines, to avenge himself on the enemies of the king.’” But as for Saul, he had schemed to have David fall by the hand of the Phi·lisʹtines.

[[v9-18-26]]

^<<v9-18-26,26>>^ So his servants reported these words to David, and the matter was to David’s liking,^&#42;1^ to form a marriage alliance with the king, and the days had not yet expired.

[NOTE]
====
. Lit., “was right in David’s eyes.”
====

[[v9-18-27]]

^<<v9-18-27,27>>^ So David rose and he and his men went and struck down among the Phi·lisʹtines two^&#42;1^ hundred men, and David came bringing their foreskins and giving them in full number to the king, to form a marriage alliance with the king. In turn Saul gave him Miʹchal his daughter as a wife.

[NOTE]
====
. “Two,” MSyVg; LXX, “one.”
====

[[v9-18-28]]

^<<v9-18-28,28>>^ And Saul got to see and know that Jehovah was with David. As for Miʹchal, Saul’s daughter, she loved him.^&#42;1^

[NOTE]
====
. “With David, and all Israel was loving him,” LXX.
====

[[v9-18-29]]

^<<v9-18-29,29>>^ And again Saul felt still more fear because of David, and Saul came to be an enemy of David always.

[[v9-18-30]]

^<<v9-18-30,30>>^ And the princes of the Phi·lisʹtines would go out, and it would happen that as often as they went out David acted most prudently of all the servants of Saul; and his name came to be very precious.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]