include::./index.adoc[]

[[v9-19-0]]
=== The First of Samuel, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v9-19-1]]

^<<v9-19-1,1>>^ At length Saul spoke to Jonʹa·than^&#42;1^ his son and to all his servants of putting David to death.

[NOTE]
====
. “Jonathan.” Heb., Yoh·na·thanʹ. In all other references to Saul’s son from 18:1 to the end of 2Sa, M has Yehoh·na·thanʹ, also translated “Jonathan.”
====

[[v9-19-2]]

^<<v9-19-2,2>>^ As for Jonʹa·than, Saul’s son, he took great delight in David. So Jonʹa·than told David, saying: “Saul my father is seeking to have you put to death. And now be on your guard, please, in the morning, and you must dwell in secrecy and keep yourself hidden.

[[v9-19-3]]

^<<v9-19-3,3>>^ And I, for my part, shall go out and certainly stand at the side of my father in the field where you will be, and I myself shall speak for you to my father, and I shall certainly see what will happen, and I shall be sure to tell you.”

[[v9-19-4]]

^<<v9-19-4,4>>^ Accordingly Jonʹa·than spoke well of David to Saul his father and said to him: “Do not let the king sin against his servant David, for he has not sinned toward you and his works have been very good toward you.

[[v9-19-5]]

^<<v9-19-5,5>>^ And he proceeded to put his soul in his palm and strike the Phi·lisʹtine down, so that Jehovah performed a great salvation^&#42;1^ for all Israel. You saw it, and you gave way to rejoicing. So why should you sin against innocent blood in having David put to death for nothing?”

[NOTE]
====
. Sy adds, “by his hand.”
====

[[v9-19-6]]

^<<v9-19-6,6>>^ Then Saul obeyed the voice of Jonʹa·than, and Saul swore: “As Jehovah is living, he will not be put to death.”

[[v9-19-7]]

^<<v9-19-7,7>>^ Afterward Jonʹa·than called David and Jonʹa·than told him all these words. Then Jonʹa·than brought David to Saul, and he continued before him the same as formerly.

[[v9-19-8]]

^<<v9-19-8,8>>^ In time war broke out again and David went sallying forth and fighting against the Phi·lisʹtines and striking them down with a great slaughter, and they took to flight from before him.

[[v9-19-9]]

^<<v9-19-9,9>>^ And Jehovah’s^&#42;1^ bad spirit came to be upon Saul when he was sitting in his house with his spear in his hand, while David was playing music with his hand.

[NOTE]
====
. “Jehovah’s,” MSyVg; LXX, “God’s.”
====

[[v9-19-10]]

^<<v9-19-10,10>>^ Consequently Saul sought to pin David to the wall with the spear, but he dodged from before Saul, so that he struck the spear into the wall. And David himself fled that he might escape during that night.

[[v9-19-11]]

^<<v9-19-11,11>>^ Later Saul sent messengers to David’s house to watch it and to have him put to death in the morning; but Miʹchal his wife told David, saying: “If you are not letting your soul escape tonight, tomorrow you will be a man put to death.”

[[v9-19-12]]

^<<v9-19-12,12>>^ Immediately Miʹchal had David descend through the window, that he might go and run away and escape.

[[v9-19-13]]

^<<v9-19-13,13>>^ Then Miʹchal took the teraphim image and placed it on the couch, and a net^&#42;1^ of goats’ hair she put at the place of his head, after which she covered it with a garment.

[NOTE]
====
. Or, “quilt.”
====

[[v9-19-14]]

^<<v9-19-14,14>>^ Saul now sent messengers to take David, but she said: “He is sick.”

[[v9-19-15]]

^<<v9-19-15,15>>^ So Saul sent the messengers to see David, saying: “Bring him on his couch up to me to have him put to death.”

[[v9-19-16]]

^<<v9-19-16,16>>^ When the messengers came in, why, there was the teraphim image on the couch and a net of goats’ hair at the place of his head.

[[v9-19-17]]

^<<v9-19-17,17>>^ At this Saul said to Miʹchal: “Why did you trick me like this, so that you sent my enemy away that he might escape?” In turn Miʹchal said to Saul: “He himself said to me, ‘Send me away! Why should I put you to death?’”^&#42;1^

[NOTE]
====
. Or, “Send me away, that I may not put you to death.”
====

[[v9-19-18]]

^<<v9-19-18,18>>^ As for David, he ran away and made his escape and got to come to Samuel at Raʹmah. And he proceeded to tell him all that Saul had done to him. Then he and Samuel went away, and they took up dwelling in Naiʹoth.

[[v9-19-19]]

^<<v9-19-19,19>>^ In time the report got to Saul, saying: “Look! David is in Naiʹoth in Raʹmah.”

[[v9-19-20]]

^<<v9-19-20,20>>^ At once Saul sent messengers to take David. When they got to see the elderly ones^&#42;1^ of the prophets prophesying, and Samuel standing in his position over them, the spirit of God came to be upon Saul’s messengers, and they began behaving like prophets, they also.

[NOTE]
====
. Possibly, “company; band.” LXX, “ecclesia”; Sy, “assembly”; Vg, “wedge-division.”
====

[[v9-19-21]]

^<<v9-19-21,21>>^ When they told it to Saul, he immediately sent other messengers, and they began behaving like prophets, they also. So Saul sent messengers again, the third set, and they began behaving like prophets, they also.

[[v9-19-22]]

^<<v9-19-22,22>>^ Finally he too went to Raʹmah. When he got as far as the great cistern that is in Seʹcu,^&#42;1^ he began to inquire and say: “Where are Samuel and David?” To this they said: “There in Naiʹoth in Raʹmah.”

[NOTE]
====
. “The well of the threshing floor that is in Sephi [the bare height],” LXX.
====

[[v9-19-23]]

^<<v9-19-23,23>>^ And he kept on his way from there to Naiʹoth in Raʹmah, and the spirit of God came to be upon him, yes, him, and he went on walking and continued behaving like a prophet until he came into Naiʹoth in Raʹmah.

[[v9-19-24]]

^<<v9-19-24,24>>^ And he also proceeded to strip off his garments and behave, he also, like a prophet before Samuel, and he lay fallen naked^&#42;1^ all that day and all that night. That is why they came to say: “Is Saul also among the prophets?”

[NOTE]
====
. Or, “lightly clad.”
====

'''

xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[&#60; Capítulo Anterior] | <<v9-19-0,Topo>> | xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[Próximo Capítulo &#62;]