include::./index.adoc[]

[[v17-6-0]]
=== Esther, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v17-6-1]]

^<<v17-6-1,1>>^ During that night the king’s sleep fled. Therefore he said to bring the book of the records of the affairs of the times. Thus there came to be a reading of them before the king.

[[v17-6-2]]

^<<v17-6-2,2>>^ At length there was found written what Morʹde·cai had reported concerning Big·thaʹna and Teʹresh, two court officials of the king, doorkeepers, who had sought to lay hand on King A·has·u·eʹrus.^&#42;1^

[NOTE]
====
. “Artaxerxes,” LXX.
====

[[v17-6-3]]

^<<v17-6-3,3>>^ Then the king said: “What honor and great thing has been done to Morʹde·cai for this?” To this the king’s attendants, his ministers,^&#42;1^ said: “Nothing has been done with him.”

[NOTE]
====
. “His ministers.” Heb., mesha·rethavʹ; Gr., di·aʹko·noi; Lat., mi·niʹstri.
====

[[v17-6-4]]

^<<v17-6-4,4>>^ Later the king said: “Who is in the courtyard?” Now Haʹman himself had come into the outer courtyard of the king’s house to say to the king to hang Morʹde·cai on the stake that he had prepared for him.

[[v17-6-5]]

^<<v17-6-5,5>>^ Accordingly the king’s attendants said to him: “Here is Haʹman standing in the courtyard.” So the king said: “Let him come in.”

[[v17-6-6]]

^<<v17-6-6,6>>^ When Haʹman came in, the king proceeded to say to him: “What is to be done to the man in whose honor the king himself has taken a delight?” At this Haʹman said in his heart: “To whom would the king take delight in rendering an honor more than me?”

[[v17-6-7]]

^<<v17-6-7,7>>^ So Haʹman said to the king: “As for the man in whose honor the king himself has taken a delight,

[[v17-6-8]]

^<<v17-6-8,8>>^ let them bring royal apparel with which the king does clothe himself and a horse upon which the king does ride and on the head of which the royal headdress has been put.

[[v17-6-9]]

^<<v17-6-9,9>>^ And let there be a putting^&#42;1^ of the apparel and the horse into the charge of one of the king’s noble princes; and they must clothe the man in whose honor the king himself has taken a delight, and they must make him ride on the horse in the public square of the city, and they must call out before him, ‘This is how it is done to the man in whose honor the king himself has taken a delight.’”

[NOTE]
====
. “Let there be a putting.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-6-10]]

^<<v17-6-10,10>>^ At once the king said to Haʹman: “Quickly, take the apparel and the horse, just as you have said, and do that way to Morʹde·cai the Jew who is sitting in the king’s gate. Do not let anything go unfulfilled^&#42;1^ of all that you have spoken.”

[NOTE]
====
. Lit., “anything fall.”
====

[[v17-6-11]]

^<<v17-6-11,11>>^ And Haʹman proceeded to take the apparel and the horse and clothe Morʹde·cai and make him ride in the public square of the city and call out before him: “This is how it is done to the man in whose honor the king himself has taken a delight.”

[[v17-6-12]]

^<<v17-6-12,12>>^ Afterward Morʹde·cai returned to the king’s gate. As for Haʹman, he hurried to his house, mourning and with his head covered.

[[v17-6-13]]

^<<v17-6-13,13>>^ And Haʹman went on to relate to Zeʹresh his wife and to all his friends^&#42;1^ everything that had befallen him. At that his wise men and Zeʹresh his wife said to him: “If it is from the seed of the Jews that Morʹde·cai is before whom you have started to fall, you will not prevail against him, but you will without fail fall before him.”

[NOTE]
====
. Or, “lovers.”
====

[[v17-6-14]]

^<<v17-6-14,14>>^ While they were yet speaking with him the king’s court officials themselves arrived and proceeded hastily to bring Haʹman to the banquet that Esther had made.

'''

xref:017-esther/017-esther-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-esther/017-esther-007.adoc#v17-7-0[Próximo Capítulo &#62;]