include::./index.adoc[]

[[v17-9-0]]
=== Esther, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v17-9-1]]

^<<v17-9-1,1>>^ And in the twelfth month, that is, the month of Aʹdar, on the thirteenth day of it, when the king’s word and his law came due to be performed, on the day for which the enemies of the Jews had waited to domineer over them, there was even a turning to the contrary,^&#42;1^ in that the Jews themselves domineered over those hating them.

[NOTE]
====
. “There was even a turning to the contrary.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-9-2]]

^<<v17-9-2,2>>^ The Jews congregated themselves in their cities in all the jurisdictional districts of King A·has·u·eʹrus to lay hand on those seeking their injury, and not a man stood his ground before them, for the dread of them had fallen upon all the peoples.

[[v17-9-3]]

^<<v17-9-3,3>>^ And all the princes of the jurisdictional districts and the satraps and the governors and the doers of the business that belonged to the king were assisting the Jews, for the dread of Morʹde·cai had fallen upon them.

[[v17-9-4]]

^<<v17-9-4,4>>^ For Morʹde·cai was great in the king’s house and his fame was traveling throughout all the jurisdictional districts, because the man Morʹde·cai was steadily growing greater.

[[v17-9-5]]

^<<v17-9-5,5>>^ And the Jews went striking down all their enemies with a slaughter by the sword and with a killing and destruction, and they went doing to those hating them according to their liking.

[[v17-9-6]]

^<<v17-9-6,6>>^ And in Shuʹshan the castle the Jews killed and there was a destroying of five hundred men.

[[v17-9-7]]

^<<v17-9-7,7>>^ Also, Par·shan·daʹtha and Dalʹphon and As·paʹtha

[[v17-9-8]]

^<<v17-9-8,8>>^ and Po·raʹtha and A·daʹli·a and A·ri·daʹtha

[[v17-9-9]]

^<<v17-9-9,9>>^ and Par·mashʹta and Arʹi·sai and Arʹi·dai and Vai·zaʹtha,

[[v17-9-10]]

^<<v17-9-10,10>>^ the ten sons of Haʹman the son of Ham·me·daʹtha, the one showing hostility to the Jews, they killed; but on the plunder they did not lay their hand.

[[v17-9-11]]

^<<v17-9-11,11>>^ On that day the number of those killed in Shuʹshan the castle came before the king.

[[v17-9-12]]

^<<v17-9-12,12>>^ And the king proceeded to say to Esther the queen: “In Shuʹshan the castle the Jews have killed, and there has been a destroying^&#42;1^ of five hundred men and the ten sons of Haʹman. In the rest of the jurisdictional districts of the king what have they done? And what is your petition? Let it even be given to you. And what is your further request? Let it even be done.”

[NOTE]
====
. “There has been (was) a destroying.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-9-13]]

^<<v17-9-13,13>>^ Accordingly Esther said: “If to the king it does seem good, let it be granted tomorrow also to the Jews that are in Shuʹshan to do according to the law of today; and let the ten sons of Haʹman be hanged upon the stake.”

[[v17-9-14]]

^<<v17-9-14,14>>^ So the king said for it to be done that way. Then a law was given out in Shuʹshan, and the ten sons of Haʹman were hanged.

[[v17-9-15]]

^<<v17-9-15,15>>^ And the Jews that were in Shuʹshan proceeded to congregate themselves also on the fourteenth day of the month Aʹdar, and they got to kill in Shuʹshan three hundred men; but on the plunder they did not lay their hand.

[[v17-9-16]]

^<<v17-9-16,16>>^ As for the rest of the Jews that were in the jurisdictional districts of the king, they congregated themselves, and there was a stand^&#42;1^ for their souls,^&#42;2^ and there was an avenging of themselves upon^&#42;3^ their enemies and a killing^&#42;4^ among those hating them of seventy-five thousand; but on the plunder they did not lay their hand,

[NOTE]
====
. “There was a stand.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. Or, “lives.”
. “An avenging of themselves upon,” by a correction; M, “a rest from.”
. “There was an avenging of themselves . . . and a killing.” In Heb. these are verbs in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-9-17]]

^<<v17-9-17,17>>^ on the thirteenth day of the month Aʹdar; and there was a rest on the fourteenth &#91;day&#93; of it, and there was a making^&#42;1^ of it a day of banqueting and of rejoicing.

[NOTE]
====
. “There was a making.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-9-18]]

^<<v17-9-18,18>>^ As for the Jews that were in Shuʹshan, they congregated themselves on the thirteenth &#91;day&#93; of it and on the fourteenth &#91;day&#93; of it, and there was a rest on the fifteenth &#91;day&#93; of it, and there was a making of it a day of banqueting and of rejoicing.

[[v17-9-19]]

^<<v17-9-19,19>>^ That is why the country Jews, inhabiting the cities of the outlying districts, were making the fourteenth day of the month Aʹdar a rejoicing and a banqueting and a good day and a sending of portions to one another.

[[v17-9-20]]

^<<v17-9-20,20>>^ And Morʹde·cai proceeded to write these things and send written documents to all the Jews that were in all the jurisdictional districts of King A·has·u·eʹrus,^&#42;1^ the nearby and the distant ones,

[NOTE]
====
. “Artaxerxes,” LXX.
====

[[v17-9-21]]

^<<v17-9-21,21>>^ to impose upon them the obligation to be regularly holding the fourteenth day of the month Aʹdar and the fifteenth day of it in each and every year,

[[v17-9-22]]

^<<v17-9-22,22>>^ according to the days on which the Jews had rested from their enemies and the month that was changed for them from grief to rejoicing and from mourning to a good day, to hold them as days of banqueting and rejoicing and sending of portions to one another and of gifts to the poor people.

[[v17-9-23]]

^<<v17-9-23,23>>^ And the Jews accepted what they had started to do and what Morʹde·cai had written to them.

[[v17-9-24]]

^<<v17-9-24,24>>^ For Haʹman the son of Ham·me·daʹtha, the Agʹag·ite, the one showing hostility to all the Jews, had himself schemed against the Jews to destroy them, and he had had Pur, that is, the Lot, cast, to disquiet them and destroy them.

[[v17-9-25]]

^<<v17-9-25,25>>^ But when Esther^&#42;1^ came in before the king he said with the written document: “Let his bad scheme that he has schemed against the Jews come back upon his own head”; and they hanged him and his sons upon the stake.

[NOTE]
====
. “Esther,” SyVg; M, “she.”
====

[[v17-9-26]]

^<<v17-9-26,26>>^ That is why they called these days Puʹrim, by the name of the Pur. That is why, according to all the words of this letter and what they had seen as to this and what had come upon them,

[[v17-9-27]]

^<<v17-9-27,27>>^ the Jews imposed and accepted upon themselves and upon their offspring^&#42;1^ and upon all those joining themselves to them, that it should not pass away, the obligation to be regularly holding these two days according to what was written concerning them and according to their appointed time in each and every year.

[NOTE]
====
. Or, “seed.”
====

[[v17-9-28]]

^<<v17-9-28,28>>^ And these days were to be remembered and held in each and every generation, each family, each jurisdictional district and each city, and these days of Puʹrim themselves should not pass away from the midst of the Jews and the commemoration itself of them not come to an end among their offspring.

[[v17-9-29]]

^<<v17-9-29,29>>^ And Esther the queen, the daughter of Abʹi·ha·il, and Morʹde·cai the Jew proceeded to write with all forcefulness to confirm this second letter concerning Puʹrim.

[[v17-9-30]]

^<<v17-9-30,30>>^ Then he^&#42;1^ sent written documents to all the Jews in the one hundred and twenty-seven jurisdictional districts, the realm of A·has·u·eʹrus, &#91;in&#93; words of peace and truth,

[NOTE]
====
. “He,” M; SyVg, “they.”
====

[[v17-9-31]]

^<<v17-9-31,31>>^ to confirm these days of Puʹrim at their appointed times, just as Morʹde·cai the Jew and Esther the queen had imposed upon them, and just as they had imposed upon their own soul^&#42;1^ and upon their offspring, the matters of the fasts and their cry for aid.

[NOTE]
====
. Or, “selves.”
====

[[v17-9-32]]

^<<v17-9-32,32>>^ And the very saying of Esther confirmed these matters of Puʹrim, and it was written down in a book.

'''

xref:017-esther/017-esther-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-esther/017-esther-010.adoc#v17-10-0[Próximo Capítulo &#62;]