include::./index.adoc[]

[[v17-4-0]]
=== Esther, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v17-4-1]]

^<<v17-4-1,1>>^ And Morʹde·cai himself got knowledge of everything that had been done; and Morʹde·cai proceeded to rip his garments apart and put on sackcloth and ashes and go out into the middle of the city and cry out with a loud and bitter outcry.

[[v17-4-2]]

^<<v17-4-2,2>>^ Finally he came as far as in front of the king’s gate, for no one was to come into the king’s gate in clothing of sackcloth.

[[v17-4-3]]

^<<v17-4-3,3>>^ And in all the different jurisdictional districts, wherever the king’s word and his law were reaching, there was great mourning among the Jews, and fasting and weeping and wailing. Sackcloth and ashes themselves came to be spread out as a couch for many.

[[v17-4-4]]

^<<v17-4-4,4>>^ And Esther’s young women and her eunuchs began to come in and tell her. And the queen was very much pained. Then she sent garments to clothe Morʹde·cai and to remove his sackcloth off him. And he did not accept &#91;them&#93;.

[[v17-4-5]]

^<<v17-4-5,5>>^ At this Esther called Haʹthach, one of the king’s eunuchs, whom he had made to attend upon her, and she proceeded to give him a command concerning Morʹde·cai, to know what this meant and what this was all about.

[[v17-4-6]]

^<<v17-4-6,6>>^ So Haʹthach went out to Morʹde·cai into the public square of the city that was before the king’s gate.

[[v17-4-7]]

^<<v17-4-7,7>>^ Then Morʹde·cai told him about all the things that had befallen him and the exact statement of the money that Haʹman had said to pay to the king’s treasury against the Jews, to destroy them.

[[v17-4-8]]

^<<v17-4-8,8>>^ And a copy of the writing of the law that had been given in Shuʹshan to have them annihilated he gave him to show Esther and to tell her and to lay the command upon her to come in to the king and implore favor of him and make request directly before him for her own people.

[[v17-4-9]]

^<<v17-4-9,9>>^ Haʹthach now came in and told Esther Morʹde·cai’s words.

[[v17-4-10]]

^<<v17-4-10,10>>^ Then Esther said to Haʹthach and commanded him concerning Morʹde·cai:

[[v17-4-11]]

^<<v17-4-11,11>>^ “All the king’s servants and the people of the king’s jurisdictional districts are aware that, as regards any man or woman that comes in to the king at the inner courtyard who is not called, his one law is to have &#91;him&#93; put to death; only in case the king holds out to him the golden scepter, he will also certainly stay alive. As for me, I have not been called to come in to the king now for thirty days.”

[[v17-4-12]]

^<<v17-4-12,12>>^ And they proceeded to tell Morʹde·cai the words of Esther.

[[v17-4-13]]

^<<v17-4-13,13>>^ Then Morʹde·cai said to reply to Esther: “Do not imagine within your own soul that the king’s household will escape any more than all the other Jews.

[[v17-4-14]]

^<<v17-4-14,14>>^ For if you are altogether silent at this time, relief and deliverance themselves will stand up for the Jews from another place; but as for you and your father’s house, YOU people will perish. And who is there knowing whether it is for a time like this that you have attained to royal dignity?”

[[v17-4-15]]

^<<v17-4-15,15>>^ Accordingly Esther said to reply to Morʹde·cai:

[[v17-4-16]]

^<<v17-4-16,16>>^ “Go, gather all the Jews that are to be found in Shuʹshan and fast in my behalf and neither eat nor drink for three days, night and day. I too with my young women, I shall fast likewise, and upon that I shall come in to the king, which is not according to the law; and in case I must perish, I must perish.”

[[v17-4-17]]

^<<v17-4-17,17>>^ At this Morʹde·cai passed along and proceeded to do according to all that Esther had laid in command upon him.

'''

xref:017-esther/017-esther-003.adoc#v17-3-0[&#60; Capítulo Anterior] | <<v17-4-0,Topo>> | xref:017-esther/017-esther-005.adoc#v17-5-0[Próximo Capítulo &#62;]