include::./index.adoc[]

[[v17-3-0]]
=== Esther, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v17-3-1]]

^<<v17-3-1,1>>^ After these things King A·has·u·eʹrus magnified Haʹman the son of Ham·me·daʹtha the Agʹag·ite and proceeded to exalt him and to put his throne above all the other princes that were with him.

[[v17-3-2]]

^<<v17-3-2,2>>^ And all the king’s servants that were in the king’s gate were bowing low and prostrating themselves to Haʹman, for so the king had commanded respecting him. But as for Morʹde·cai, he would neither bow low nor prostrate himself.

[[v17-3-3]]

^<<v17-3-3,3>>^ And the king’s servants who were in the king’s gate began to say to Morʹde·cai: “Why are you sidestepping the king’s commandment?”

[[v17-3-4]]

^<<v17-3-4,4>>^ And it came about that, as they talked to him day by day, and he did not listen to them, then they told Haʹman to see whether Morʹde·cai’s affairs would stand; for he had told them that he was a Jew.

[[v17-3-5]]

^<<v17-3-5,5>>^ Now Haʹman kept seeing that Morʹde·cai was not bowing low and prostrating himself to him, and Haʹman became filled with rage.

[[v17-3-6]]

^<<v17-3-6,6>>^ But it was despicable in his eyes to lay hand upon Morʹde·cai alone, for they had told him about Morʹde·cai’s people; and Haʹman began seeking to annihilate all the Jews who were in all the realm of A·has·u·eʹrus, Morʹde·cai’s people.

[[v17-3-7]]

^<<v17-3-7,7>>^ In the first month, that is, the month Niʹsan,^&#42;1^ in the twelfth year of King A·has·u·eʹrus, someone cast Pur,^&#42;2^ that is, the Lot, before Haʹman from day to day and from month to month, &#91;to&#93; the twelfth, that is, the month Aʹdar.^&#42;3^

[NOTE]
====
. See Ne 2:1 ftn.
. “Pur,” meaning “Lot.” “Purim,” pl., came to designate the Jewish festival celebrated in the 12th month of the sacred calendar. See App 8B.
. “Adar.” Heb., ʼAdharʹ. This name of the 12th month of the Jewish sacred calendar occurs only in Ezr 6:15 and eight times in Esther. Adar falls within February and March. See App 8B.
====

[[v17-3-8]]

^<<v17-3-8,8>>^ And Haʹman proceeded to say to King A·has·u·eʹrus: “There is one certain people scattered and separated among the peoples in all the jurisdictional districts of your realm; and their laws are different from all other people’s, and the king’s own laws they are not performing, and for the king it is not appropriate to let them alone.

[[v17-3-9]]

^<<v17-3-9,9>>^ If to the king it does seem good, let there be a writing that they be destroyed; and ten thousand silver talents^&#42;1^ I shall pay into the hands of those doing the work by bringing &#91;it&#93; into the king’s treasury.”

[NOTE]
====
. About $77,070,000 with silver valued at $7 (U.S.) per oz t.
====

[[v17-3-10]]

^<<v17-3-10,10>>^ At that the king removed his signet ring from his own hand and gave it to Haʹman the son of Ham·me·daʹtha the Agʹag·ite, the one showing hostility to the Jews.

[[v17-3-11]]

^<<v17-3-11,11>>^ And the king went on to say to Haʹman: “The silver is given to you, also the people, to do with them according to what is good in your own eyes.”

[[v17-3-12]]

^<<v17-3-12,12>>^ The king’s secretaries were then called in the first month on the thirteenth day of it, and writing went on according to all that Haʹman commanded the king’s satraps and the governors who were over the different jurisdictional districts, and the princes of the different peoples, of each jurisdictional district, in its own style of writing, and each people in its own tongue; in the name of King A·has·u·eʹrus it was written and it was sealed with the king’s signet ring.

[[v17-3-13]]

^<<v17-3-13,13>>^ And there was a sending^&#42;1^ of the letters by means of couriers to all the king’s jurisdictional districts, to annihilate, to kill and to destroy all the Jews, young man as well as old man, little ones and women, on one day, on the thirteenth &#91;day&#93; of the twelfth month, that is, the month Aʹdar, and to plunder the spoil of them.

[NOTE]
====
. “There was a sending.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v17-3-14]]

^<<v17-3-14,14>>^ A copy of the writing to be given as law in all the different jurisdictional districts was being published to all the peoples, &#91;for them&#93; to become ready for this day.

[[v17-3-15]]

^<<v17-3-15,15>>^ The couriers themselves went out, being moved to speed because of the king’s word, and the law itself was given in Shuʹshan the castle. As for the king and Haʹman, they sat down to drink; but as for the city of Shuʹshan, it was in confusion.

'''

xref:017-esther/017-esther-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-esther/017-esther-004.adoc#v17-4-0[Próximo Capítulo &#62;]