include::./index.adoc[]

[[v46-4-0]]
=== The First to the Corinthians, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-4-1]]

^<<v46-4-1,1>>^ Let a man so appraise us as being subordinates^&#42;1^ of Christ and stewards of sacred secrets of God.

[NOTE]
====
. Or, “attendants; assistants.” Gr., hy·pe·reʹtas; Lat., mi·niʹstros.
====

[[v46-4-2]]

^<<v46-4-2,2>>^ Besides, in this case, what is looked for in stewards^&#42;1^ is for a man to be found faithful.

[NOTE]
====
. “Stewards.” Gr., oi·ko·noʹmois, “house managers”; Lat., di·spen·sa·toʹres; J17(Heb.), has·so·khenimʹ, “the stewards.”
====

[[v46-4-3]]

^<<v46-4-3,3>>^ Now to me it is a very trivial matter that I should be examined by YOU or by a human tribunal.^&#42;1^ Even I do not examine myself.

[NOTE]
====
. “Human tribunal.” Lit., “human day,” that is, a day appointed by a human judge.
====

[[v46-4-4]]

^<<v46-4-4,4>>^ For I am not conscious of anything against myself. Yet by this I am not proved righteous, but he that examines me is Jehovah.^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v46-4-5]]

^<<v46-4-5,5>>^ Hence do not judge anything before the due time, until the Lord comes, who will both bring the secret things of darkness to light and make the counsels of the hearts manifest, and then each one will have his praise come to him^&#42;1^ from God.

[NOTE]
====
. Or, “his praise will come to each one.”
====

[[v46-4-6]]

^<<v46-4-6,6>>^ Now, brothers, these things I have transferred so as to apply to myself and A·polʹlos for YOUR good, that in our case YOU may learn the &#91;rule&#93;: “Do not go beyond the things that are written,” in order that YOU may not be puffed up individually in favor of the one against the other.

[[v46-4-7]]

^<<v46-4-7,7>>^ For who makes you to differ from another? Indeed, what do you have that you did not receive? If, now, you did indeed receive &#91;it&#93;, why do you boast as though you did not receive &#91;it&#93;?

[[v46-4-8]]

^<<v46-4-8,8>>^ YOU men already have YOUR fill, do YOU? YOU are rich already, are YOU? YOU have begun ruling as kings without us, have YOU? And I wish indeed that YOU had begun ruling as kings, that we also might rule with YOU as kings.

[[v46-4-9]]

^<<v46-4-9,9>>^ For it seems to me that God has put us the apostles last on exhibition as men appointed to death, because we have become a theatrical spectacle^&#42;1^ to the world, and to angels, and to men.^&#42;2^

[NOTE]
====
. “Theatrical spectacle.” Lit., “a theater.” Gr., theʹa·tron; Lat., spec·taʹcu·lum.
. Or, “both to angels and to men.”
====

[[v46-4-10]]

^<<v46-4-10,10>>^ We are fools because of Christ, but YOU are discreet in Christ; we are weak, but YOU are strong; YOU are in good repute, but we are in dishonor.^&#42;1^

[NOTE]
====
. “In dishonor.” Lit., “dishonorable (ones).” Gr., aʹti·moi.
====

[[v46-4-11]]

^<<v46-4-11,11>>^ Down to this very hour we continue to hunger and also to thirst and to be scantily clothed^&#42;1^ and to be knocked about and to be homeless

[NOTE]
====
. Or, “naked.”
====

[[v46-4-12]]

^<<v46-4-12,12>>^ and to toil, working with our own hands. When being reviled, we bless; when being persecuted, we bear up;

[[v46-4-13]]

^<<v46-4-13,13>>^ when being defamed, we entreat; we have become as the refuse of the world, the offscouring of all things, until now.

[[v46-4-14]]

^<<v46-4-14,14>>^ I am writing these things, not to shame YOU, but to admonish YOU as my beloved children.

[[v46-4-15]]

^<<v46-4-15,15>>^ For though YOU may have ten thousand tutors in Christ, &#91;YOU&#93; certainly &#91;do&#93; not &#91;have&#93; many fathers; for in Christ Jesus I have become YOUR father through the good news.

[[v46-4-16]]

^<<v46-4-16,16>>^ I entreat YOU, therefore, become imitators of me.

[[v46-4-17]]

^<<v46-4-17,17>>^ That is why I am sending Timothy to YOU, as he is my beloved and faithful child in &#91;the&#93; Lord; and he will put YOU in mind of my methods in connection with Christ Jesus,^&#42;1^ just as I am teaching everywhere in every congregation.

[NOTE]
====
. “Jesus,” P46אCVgc; ABVgSyp omit.
====

[[v46-4-18]]

^<<v46-4-18,18>>^ Some are puffed up as though I were in fact not coming to YOU.

[[v46-4-19]]

^<<v46-4-19,19>>^ But I will come to YOU shortly, if Jehovah^&#42;1^ wills, and I shall get to know, not the speech of those who are puffed up, but &#91;their&#93; power.

[NOTE]
====
. See App 1D.
====

[[v46-4-20]]

^<<v46-4-20,20>>^ For the kingdom of God &#91;lies&#93; not in speech, but in power.

[[v46-4-21]]

^<<v46-4-21,21>>^ What do YOU want? Shall I come to YOU with a rod, or with love and mildness of spirit?

'''

xref:046-1-corinthians/046-1-corinthians-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-005.adoc#v46-5-0[Próximo Capítulo &#62;]