include::./index.adoc[]

[[v46-8-0]]
=== The First to the Corinthians, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-8-1]]

^<<v46-8-1,1>>^ Now concerning foods offered to idols:^&#42;1^ we know we all have knowledge. Knowledge puffs up, but love builds up.

[NOTE]
====
. Or, “the things sacrificed to idols.”
====

[[v46-8-2]]

^<<v46-8-2,2>>^ If anyone thinks he has acquired knowledge of something, he does not yet know &#91;it&#93; just as he ought to know &#91;it&#93;.

[[v46-8-3]]

^<<v46-8-3,3>>^ But if anyone loves God, this one is known by him.

[[v46-8-4]]

^<<v46-8-4,4>>^ Now concerning the eating of foods offered to idols, we know that an idol is nothing in the world,^&#42;1^ and that there is no God but one.

[NOTE]
====
. Or, “nothing at all.”
====

[[v46-8-5]]

^<<v46-8-5,5>>^ For even though there are those who are called “gods,” whether in heaven or on earth, just as there are many “gods” and many “lords,”

[[v46-8-6]]

^<<v46-8-6,6>>^ there is actually to us one God^&#42;1^ the Father, out of whom all things are, and we for him; and there is one Lord, Jesus Christ, through whom all things are, and we through him.

[NOTE]
====
. “One God.” Gr., heis The·osʹ; Lat., uʹnus Deʹus; J18,​22(Heb.), ʼElo·himʹ ʼe·chadhʹ.
====

[[v46-8-7]]

^<<v46-8-7,7>>^ Nevertheless, there is not this knowledge in all persons; but some, being accustomed until now to the idol, eat food as something sacrificed to an idol, and their conscience, being weak, is defiled.

[[v46-8-8]]

^<<v46-8-8,8>>^ But food will not commend us to God; if we do not eat, we do not fall short, and, if we eat, we have no credit to ourselves.

[[v46-8-9]]

^<<v46-8-9,9>>^ But keep watching that this authority of YOURS does not somehow become a stumbling block to those who are weak.

[[v46-8-10]]

^<<v46-8-10,10>>^ For if anyone should see you, the one having knowledge, reclining at a meal in an idol temple,^&#42;1^ will not the conscience of that one who is weak be built up to the point of eating foods offered to idols?

[NOTE]
====
. Compare Jg 9:27.
====

[[v46-8-11]]

^<<v46-8-11,11>>^ Really, by your knowledge, the man that is weak is being ruined, &#91;your&#93; brother for whose sake Christ died.

[[v46-8-12]]

^<<v46-8-12,12>>^ But when YOU people thus sin against YOUR brothers and wound their conscience that is weak, YOU are sinning against Christ.

[[v46-8-13]]

^<<v46-8-13,13>>^ Therefore, if food makes my brother stumble, I will never again eat flesh at all, that I may not make my brother stumble.

'''

xref:046-1-corinthians/046-1-corinthians-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-009.adoc#v46-9-0[Próximo Capítulo &#62;]