include::./index.adoc[]

[[v46-10-0]]
=== The First to the Corinthians, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-10-1]]

^<<v46-10-1,1>>^ Now I do not want YOU to be ignorant, brothers, that our forefathers were all under the cloud and all passed through the sea

[[v46-10-2]]

^<<v46-10-2,2>>^ and all got baptized into Moses by means of the cloud and of the sea;

[[v46-10-3]]

^<<v46-10-3,3>>^ and all ate the same^&#42;1^ spiritual food

[NOTE]
====
. “The same,” אcBVgSyp; א* omits; P46A, “the.”
====

[[v46-10-4]]

^<<v46-10-4,4>>^ and all drank the same spiritual drink. For they used to drink from the spiritual rock-mass that followed them, and that rock-mass^&#42;1^ meant^&#42;2^ the Christ.

[NOTE]
====
. “Rock-mass.” Gr., peʹtra, fem. See Mt 16:18 ftn, “Rock-mass.”
. Or, “was.” See Mt 26:26 ftn.
====

[[v46-10-5]]

^<<v46-10-5,5>>^ Nevertheless, on most of them God did not express his approval, for they were laid low in the wilderness.

[[v46-10-6]]

^<<v46-10-6,6>>^ Now these things became our examples,^&#42;1^ for us not to be persons desiring injurious things, even as they desired them.

[NOTE]
====
. Or, “types.” Gr., tyʹpoi; Lat., in fi·guʹra.
====

[[v46-10-7]]

^<<v46-10-7,7>>^ Neither become idolaters, as some of them did; just as it is written: “The people sat down to eat and drink, and they got up to have a good time.”

[[v46-10-8]]

^<<v46-10-8,8>>^ Neither let us practice fornication, as some of them committed fornication, only to fall, twenty-three thousand &#91;of them&#93; in one day.

[[v46-10-9]]

^<<v46-10-9,9>>^ Neither let us put Jehovah^&#42;1^ to the test, as some of them put &#91;him&#93; to the test, only to perish by the serpents.

[NOTE]
====
. “Jehovah,” J18,​22,​23; אBC(Gr.), ton Kyʹri·on; P46D, “the Christ”; A, “God.” See App 1D.
====

[[v46-10-10]]

^<<v46-10-10,10>>^ Neither be murmurers, just as some of them murmured, only to perish by the destroyer.

[[v46-10-11]]

^<<v46-10-11,11>>^ Now these things went on befalling them as examples,^&#42;1^ and they were written for a warning to us upon whom the ends^&#42;2^ of the systems of things^&#42;3^ have arrived.

[NOTE]
====
. Or, “as for a typical purpose.” Gr., ty·pi·kosʹ; Lat., in fi·guʹra.
. Or, “accomplished (completed) ends.” Gr., teʹle.
. Or, “of the orders of things.” Gr., ton ai·oʹnon; Lat., sae·cu·loʹrum; J17,​22(Heb.), ha·ʽoh·la·mimʹ.
====

[[v46-10-12]]

^<<v46-10-12,12>>^ Consequently let him that thinks he is standing beware that he does not fall.

[[v46-10-13]]

^<<v46-10-13,13>>^ No temptation has taken YOU except what is common to men. But God is faithful, and he will not let YOU be tempted beyond what YOU can bear, but along with the temptation he will also make the way out in order for YOU to be able to endure it.

[[v46-10-14]]

^<<v46-10-14,14>>^ Therefore, my beloved ones, flee from idolatry.

[[v46-10-15]]

^<<v46-10-15,15>>^ I speak as to men with discernment; judge for yourselves what I say.

[[v46-10-16]]

^<<v46-10-16,16>>^ The cup of blessing which we bless, is it not a sharing in the blood of the Christ? The loaf which we break, is it not a sharing in the body of the Christ?

[[v46-10-17]]

^<<v46-10-17,17>>^ Because there is one loaf, we, although many, are one body,^&#42;1^ for we are all partaking of that one loaf.

[NOTE]
====
. Or, “Because we, although many, are one loaf, one body.”
====

[[v46-10-18]]

^<<v46-10-18,18>>^ LOOK at that which is Israel in a fleshly way: Are not those who eat the sacrifices sharers with^&#42;1^ the altar?

[NOTE]
====
. Or, “in.”
====

[[v46-10-19]]

^<<v46-10-19,19>>^ What, then, am I to say? That what is sacrificed to an idol is anything, or that an idol is anything?

[[v46-10-20]]

^<<v46-10-20,20>>^ No; but I say that the things which the nations^&#42;1^ sacrifice they sacrifice to demons, and not to God; and I do not want YOU to become sharers with the demons.

[NOTE]
====
. “The nations,” P46אACVgSyh,p; BD, “they.”
====

[[v46-10-21]]

^<<v46-10-21,21>>^ YOU cannot be drinking the cup of Jehovah^&#42;1^ and the cup of demons; YOU cannot be partaking of “the table of Jehovah”^&#42;2^ and the table of demons.

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v46-10-22]]

^<<v46-10-22,22>>^ Or “are we inciting Jehovah^&#42;1^ to jealousy”? We are not stronger than he is, are we?

[NOTE]
====
. See App 1D.
====

[[v46-10-23]]

^<<v46-10-23,23>>^ All things are lawful; but not all things are advantageous. All things are lawful; but not all things build up.

[[v46-10-24]]

^<<v46-10-24,24>>^ Let each one keep seeking, not his own &#91;advantage&#93;, but that of the other person.

[[v46-10-25]]

^<<v46-10-25,25>>^ Everything that is sold in a meat market keep eating, making no inquiry on account of YOUR conscience;

[[v46-10-26]]

^<<v46-10-26,26>>^ for “to Jehovah^&#42;1^ belong the earth and that which fills it.”

[NOTE]
====
. See App 1D.
====

[[v46-10-27]]

^<<v46-10-27,27>>^ If anyone of the unbelievers invites YOU and YOU wish to go, proceed to eat everything that is set before YOU, making no inquiry on account of YOUR conscience.

[[v46-10-28]]

^<<v46-10-28,28>>^ But if anyone should say to YOU: “This is something offered in sacrifice,” do not eat on account of the one that disclosed it and on account of conscience.^&#42;1^

[NOTE]
====
. Syh and TR add: “(For the earth belongs to the Lord [J7,​8,​10,​11,​13,​14,​16,​17, “to Jehovah”], and so does its fullness).”
====

[[v46-10-29]]

^<<v46-10-29,29>>^ “Conscience,” I say, not your own, but that of the other person. For why should it be that my freedom is judged by another person’s conscience?

[[v46-10-30]]

^<<v46-10-30,30>>^ If I am partaking with thanks, why am I to be spoken of abusively over that for which I give thanks?

[[v46-10-31]]

^<<v46-10-31,31>>^ Therefore, whether YOU are eating or drinking or doing anything else, do all things for God’s glory.

[[v46-10-32]]

^<<v46-10-32,32>>^ Keep from becoming causes for stumbling to Jews as well as Greeks and to the congregation of God,

[[v46-10-33]]

^<<v46-10-33,33>>^ even as I am pleasing all people in all things, not seeking my own advantage but that of the many, in order that they might get saved.

'''

xref:046-1-corinthians/046-1-corinthians-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-011.adoc#v46-11-0[Próximo Capítulo &#62;]