include::./index.adoc[]

[[v46-16-0]]
=== The First to the Corinthians, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-16-1]]

^<<v46-16-1,1>>^ Now concerning the collection that is for the holy ones, just as I gave orders to the congregations of Ga·laʹti·a, do that way also yourselves.

[[v46-16-2]]

^<<v46-16-2,2>>^ Every first day of the week let each of YOU at his own house set something aside in store as he may be prospering, so that when I arrive collections will not take place then.

[[v46-16-3]]

^<<v46-16-3,3>>^ But when I get there, whatever men YOU approve of by letters, these I shall send to carry YOUR kind gift to Jerusalem.

[[v46-16-4]]

^<<v46-16-4,4>>^ However, if it is fitting for me to go there also, they will go there with me.

[[v46-16-5]]

^<<v46-16-5,5>>^ But I shall come to YOU when I have gone through Mac·e·doʹni·a, for I am going through Mac·e·doʹni·a;

[[v46-16-6]]

^<<v46-16-6,6>>^ and perhaps I shall stay or even pass the winter with YOU, that YOU may conduct me partway to where I may be going.

[[v46-16-7]]

^<<v46-16-7,7>>^ For I do not want to see YOU just now on &#91;my&#93; passing through, for I hope to remain some time with YOU, if Jehovah^&#42;1^ permits.

[NOTE]
====
. See App 1D.
====

[[v46-16-8]]

^<<v46-16-8,8>>^ But I am remaining in Ephʹe·sus until the &#91;festival of&#93; Pentecost;

[[v46-16-9]]

^<<v46-16-9,9>>^ for a large door that leads to activity has been opened to me, but there are many opposers.

[[v46-16-10]]

^<<v46-16-10,10>>^ However, if Timothy arrives, see that he becomes free of fear among YOU, for he is performing the work of Jehovah,^&#42;1^ even as I am.

[NOTE]
====
. See App 1D.
====

[[v46-16-11]]

^<<v46-16-11,11>>^ Let no one, therefore, look down upon him. Conduct him partway in peace, that he may get here to me, for I am waiting for him with the brothers.

[[v46-16-12]]

^<<v46-16-12,12>>^ Now concerning A·polʹlos our brother, I entreated him very much to come to YOU with the brothers, and yet it was not his will at all to come now; but he will come when he has the opportunity.

[[v46-16-13]]

^<<v46-16-13,13>>^ Stay awake, stand firm in the faith, carry on as men, grow^&#42;1^ mighty.

[NOTE]
====
. Or, “be.”
====

[[v46-16-14]]

^<<v46-16-14,14>>^ Let all YOUR affairs take place with love.

[[v46-16-15]]

^<<v46-16-15,15>>^ Now I exhort^&#42;1^ YOU, brothers: YOU know that the household of Stephʹa·nas is the firstfruits of A·chaʹia^&#42;2^ and that they set themselves to minister to the holy ones.

[NOTE]
====
. Or, “entreat.”
. The Roman province of southern Greece with its capital at Corinth.
====

[[v46-16-16]]

^<<v46-16-16,16>>^ May YOU also keep submitting yourselves to persons of that kind and to everyone cooperating and laboring.

[[v46-16-17]]

^<<v46-16-17,17>>^ But I rejoice over the presence^&#42;1^ of Stephʹa·nas and For·tu·naʹtus and A·chaʹi·cus, because they have made up for YOUR not being here.

[NOTE]
====
. See App 5B.
====

[[v46-16-18]]

^<<v46-16-18,18>>^ For they have refreshed my spirit and YOURS. Therefore recognize men of that sort.

[[v46-16-19]]

^<<v46-16-19,19>>^ The congregations of Asia send YOU their greetings. Aqʹui·la and Prisʹca together with the congregation that is in their house greet YOU heartily in &#91;the&#93; Lord.

[[v46-16-20]]

^<<v46-16-20,20>>^ All the brothers greet YOU. Greet one another with a holy kiss.

[[v46-16-21]]

^<<v46-16-21,21>>^ &#91;Here is&#93; my greeting, Paul’s, in my own hand.

[[v46-16-22]]

^<<v46-16-22,22>>^ If anyone has no affection for the Lord, let him be accursed. O our Lord, come!^&#42;1^

[NOTE]
====
. Or, “Our Lord is coming”; or, “Our Lord has come.” Gr., Ma·ranʹ a·thaʹ, a transliteration from Aram.
====

[[v46-16-23]]

^<<v46-16-23,23>>^ May the undeserved kindness of the Lord Jesus be with YOU.

[[v46-16-24]]

^<<v46-16-24,24>>^ May my love be with all of YOU in union with Christ Jesus.

'''

xref:046-1-corinthians/046-1-corinthians-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corinthians/047-2-corinthians-001.adoc#v47-1-0[Próximo Capítulo &#62;]