include::./index.adoc[]

[[v46-14-0]]
=== The First to the Corinthians, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-14-1]]

^<<v46-14-1,1>>^ Pursue love, yet keep zealously seeking the spiritual gifts, but preferably that YOU may prophesy.

[[v46-14-2]]

^<<v46-14-2,2>>^ For he that speaks in a tongue speaks, not to men, but to God, for no one listens, but he speaks sacred secrets by the spirit.

[[v46-14-3]]

^<<v46-14-3,3>>^ However, he that prophesies upbuilds and encourages and consoles men by his speech.

[[v46-14-4]]

^<<v46-14-4,4>>^ He that speaks in a tongue upbuilds himself, but he that prophesies upbuilds a congregation.

[[v46-14-5]]

^<<v46-14-5,5>>^ Now I would like for all of YOU to speak in tongues, but I prefer that YOU prophesy. Indeed, he that prophesies is greater than he that speaks in tongues, unless, in fact, he translates, that the congregation may receive upbuilding.

[[v46-14-6]]

^<<v46-14-6,6>>^ But at this time, brothers, if I should come speaking to YOU in tongues, what good would I do YOU unless I spoke to YOU either with a revelation^&#42;1^ or with knowledge or with a prophecy or with a teaching?

[NOTE]
====
. Lit., “uncovering; disclosure.” Gr., a·po·ka·lyʹpsei.
====

[[v46-14-7]]

^<<v46-14-7,7>>^ As it is, the inanimate things^&#42;1^ give off sound, whether a flute or a harp; unless it makes an interval to the tones, how will it be known what is being played on the flute or on the harp?

[NOTE]
====
. Or, “soulless things.” Gr., aʹpsy·kha.
====

[[v46-14-8]]

^<<v46-14-8,8>>^ For truly, if the trumpet sounds an indistinct call, who will get ready for battle?

[[v46-14-9]]

^<<v46-14-9,9>>^ In the same way also, unless YOU through the tongue utter speech easily understood, how will it be known what is being spoken? YOU will, in fact, be speaking into the air.

[[v46-14-10]]

^<<v46-14-10,10>>^ It may be that there are so many kinds of speech sounds in the world, and yet no &#91;kind&#93; is without meaning.

[[v46-14-11]]

^<<v46-14-11,11>>^ If, then, I do not understand the force of the speech sound, I shall be a foreigner to the one speaking, and the one speaking will be a foreigner to me.

[[v46-14-12]]

^<<v46-14-12,12>>^ So also YOU yourselves, since YOU are zealously desirous of &#91;gifts of the&#93; spirit,^&#42;1^ seek to abound in them for the upbuilding of the congregation.

[NOTE]
====
. Lit., “zealous of spirits.”
====

[[v46-14-13]]

^<<v46-14-13,13>>^ Therefore let the one who speaks in a tongue pray that he may translate.

[[v46-14-14]]

^<<v46-14-14,14>>^ For if I am praying in a tongue, it is my &#91;gift of the&#93; spirit that is praying, but my mind is unfruitful.

[[v46-14-15]]

^<<v46-14-15,15>>^ What is to be done, then? I will pray with the &#91;gift of the&#93; spirit, but I will also pray with &#91;my&#93; mind. I will sing praise with the &#91;gift of the&#93; spirit, but I will also sing praise with &#91;my&#93; mind.

[[v46-14-16]]

^<<v46-14-16,16>>^ Otherwise, if you offer praise with a &#91;gift of the&#93; spirit, how will the man occupying the seat of the ordinary person say “Amen” to your giving of thanks, since he does not know what you are saying?

[[v46-14-17]]

^<<v46-14-17,17>>^ True, you give thanks in a fine way, but the other man is not being built up.

[[v46-14-18]]

^<<v46-14-18,18>>^ I thank God, I speak in more tongues than all of YOU do.

[[v46-14-19]]

^<<v46-14-19,19>>^ Nevertheless, in a congregation I would rather speak five words with my mind, that I might also instruct others orally, than ten thousand words in a tongue.

[[v46-14-20]]

^<<v46-14-20,20>>^ Brothers, do not become young children in powers of understanding, but be babes as to badness; yet become full-grown in powers of understanding.

[[v46-14-21]]

^<<v46-14-21,21>>^ In the Law it is written: “‘With the tongues of foreigners and with the lips of strangers^&#42;1^ I will speak to this people, and yet not even then will they give heed to me,’ says Jehovah.”^&#42;2^

[NOTE]
====
. Lit., “of different (ones).”
. See App 1D.
====

[[v46-14-22]]

^<<v46-14-22,22>>^ Consequently tongues are for a sign, not to the believers, but to the unbelievers, whereas prophesying is, not for the unbelievers, but for the believers.

[[v46-14-23]]

^<<v46-14-23,23>>^ Therefore, if the whole congregation comes together to one place and they all speak in tongues, but ordinary people or unbelievers come in, will they not say that YOU are mad?

[[v46-14-24]]

^<<v46-14-24,24>>^ But if YOU are all prophesying and any unbeliever or ordinary person comes in, he is reproved by them all, he is closely examined by all;

[[v46-14-25]]

^<<v46-14-25,25>>^ the secrets of his heart become manifest, so that he will fall upon &#91;his&#93; face^&#42;1^ and worship God, declaring: “God is really among YOU.”

[NOTE]
====
. Or, “prostrate [himself].”
====

[[v46-14-26]]

^<<v46-14-26,26>>^ What is to be done, then, brothers? When YOU come together, one has a psalm,^&#42;1^ another has a teaching, another has a revelation, another has a tongue, another has an interpretation. Let all things take place for upbuilding.

[NOTE]
====
. Or, “sacred composition.”
====

[[v46-14-27]]

^<<v46-14-27,27>>^ And if someone speaks in a tongue, let it be limited to two or three at the most, and in turns; and let someone translate.

[[v46-14-28]]

^<<v46-14-28,28>>^ But if there be no translator, let him keep silent in the congregation and speak to himself and to God.

[[v46-14-29]]

^<<v46-14-29,29>>^ Further, let two or three prophets speak, and let the others discern the meaning.

[[v46-14-30]]

^<<v46-14-30,30>>^ But if there is a revelation to another one while sitting there, let the first one keep silent.

[[v46-14-31]]

^<<v46-14-31,31>>^ For YOU can all prophesy one by one, that all may learn and all be encouraged.

[[v46-14-32]]

^<<v46-14-32,32>>^ And &#91;gifts of&#93; the spirit^&#42;1^ of the prophets are to be controlled by the prophets.

[NOTE]
====
. Lit., “And spirits.”
====

[[v46-14-33]]

^<<v46-14-33,33>>^ For God is &#91;a God&#93;, not of disorder, but of peace.
As in all the congregations of the holy ones,

[[v46-14-34]]

^<<v46-14-34,34>>^ let the women keep silent in the congregations, for it is not permitted for them to speak, but let them be in subjection, even as the Law says.

[[v46-14-35]]

^<<v46-14-35,35>>^ If, then, they want to learn something, let them question their own husbands at home, for it is disgraceful for a woman to speak in a congregation.

[[v46-14-36]]

^<<v46-14-36,36>>^ What? Was it from YOU that the word of God came forth, or was it only as far as YOU that it reached?

[[v46-14-37]]

^<<v46-14-37,37>>^ If anyone thinks he is a prophet or gifted with the spirit,^&#42;1^ let him acknowledge the things I am writing to YOU, because^&#42;2^ they are the Lord’s commandment.

[NOTE]
====
. “Gifted with the spirit.” Lit., “spiritual (one).”
. Or, “that.”
====

[[v46-14-38]]

^<<v46-14-38,38>>^ But if anyone is ignorant, he continues ignorant.

[[v46-14-39]]

^<<v46-14-39,39>>^ Consequently, my brothers, keep zealously seeking the prophesying, and yet do not forbid the speaking in tongues.

[[v46-14-40]]

^<<v46-14-40,40>>^ But let all things take place decently and by arrangement.^&#42;1^

[NOTE]
====
. Or, “according to order.” Gr., ka·taʹ taʹxin. See Nu 1:52 ftn, “Camp.”
====

'''

xref:046-1-corinthians/046-1-corinthians-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-015.adoc#v46-15-0[Próximo Capítulo &#62;]