include::./index.adoc[]

[[v46-12-0]]
=== The First to the Corinthians, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-12-1]]

^<<v46-12-1,1>>^ Now concerning the spiritual gifts,^&#42;1^ brothers, I do not want YOU to be ignorant.

[NOTE]
====
. Or, “the spiritual things”; or, “the spiritual persons.” Lit., “the spiritual (things).” Gr., ton pneu·ma·ti·konʹ; Vgc(Lat.), spi·ri·tu·aʹli·bus.
====

[[v46-12-2]]

^<<v46-12-2,2>>^ YOU know that when YOU were people of the nations, YOU were being led away to those voiceless idols just as YOU happened to be led.

[[v46-12-3]]

^<<v46-12-3,3>>^ Therefore I would have YOU know that nobody when speaking by God’s spirit says: “Jesus is accursed!”^&#42;1^ and nobody can say: “Jesus is Lord!” except by holy spirit.

[NOTE]
====
. Lit., “anathema.” Gr., A·naʹthe·ma.
====

[[v46-12-4]]

^<<v46-12-4,4>>^ Now there are varieties of gifts,^&#42;1^ but there is the same spirit;

[NOTE]
====
. Lit., “of gracious gifts.” Gr., kha·ri·smaʹton.
====

[[v46-12-5]]

^<<v46-12-5,5>>^ and there are varieties of ministries, and yet there is the same Lord;

[[v46-12-6]]

^<<v46-12-6,6>>^ and there are varieties of operations, and yet it is the same God who performs all the operations in all persons.

[[v46-12-7]]

^<<v46-12-7,7>>^ But the manifestation of the spirit is given to each one for a beneficial purpose.

[[v46-12-8]]

^<<v46-12-8,8>>^ For example, to one there is given through the spirit speech of wisdom, to another speech of knowledge according to the same spirit,

[[v46-12-9]]

^<<v46-12-9,9>>^ to another faith by the same spirit, to another gifts of healings by that one spirit,

[[v46-12-10]]

^<<v46-12-10,10>>^ to yet another operations of powerful works,^&#42;1^ to another prophesying, to another discernment of inspired utterances,^&#42;2^ to another different tongues, and to another interpretation of tongues.

[NOTE]
====
. Or, “of miracles.”
. Lit., “of spirits.” Gr., pneu·maʹton.
====

[[v46-12-11]]

^<<v46-12-11,11>>^ But all these operations the one and the same spirit performs, making a distribution to each one respectively just as it wills.

[[v46-12-12]]

^<<v46-12-12,12>>^ For just as the body is one but has many members, and all the members of that body, although being many, are one body, so also is the Christ.

[[v46-12-13]]

^<<v46-12-13,13>>^ For truly by one spirit we were all baptized into one body, whether Jews or Greeks, whether slaves or free, and we were all made to drink one spirit.

[[v46-12-14]]

^<<v46-12-14,14>>^ For the body, indeed, is not one member, but many.

[[v46-12-15]]

^<<v46-12-15,15>>^ If the foot should say: “Because I am not a hand, I am no part of the body,” it is not for this reason no part of the body.

[[v46-12-16]]

^<<v46-12-16,16>>^ And if the ear should say: “Because I am not an eye, I am no part of the body,” it is not for this reason no part of the body.

[[v46-12-17]]

^<<v46-12-17,17>>^ If the whole body were an eye, where would the &#91;sense of&#93; hearing be? If it were all hearing, where would the smelling be?

[[v46-12-18]]

^<<v46-12-18,18>>^ But now God has set the members in the body, each one of them, just as he pleased.

[[v46-12-19]]

^<<v46-12-19,19>>^ If they were all one member, where would the body be?

[[v46-12-20]]

^<<v46-12-20,20>>^ But now they are many members, yet one body.

[[v46-12-21]]

^<<v46-12-21,21>>^ The eye cannot say to the hand: “I have no need of you”; or, again, the head &#91;cannot say&#93; to the feet: “I have no need of YOU.”

[[v46-12-22]]

^<<v46-12-22,22>>^ But much rather is it the case that the members of the body which seem to be weaker are necessary,

[[v46-12-23]]

^<<v46-12-23,23>>^ and the parts of the body which we think to be less honorable, these we surround with more abundant honor, and so our unseemly parts have the more abundant comeliness,

[[v46-12-24]]

^<<v46-12-24,24>>^ whereas our comely parts do not need anything. Nevertheless, God compounded^&#42;1^ the body, giving honor more abundant to the part which had a lack,

[NOTE]
====
. Lit., “mixed together.” Gr., sy·ne·keʹra·sen.
====

[[v46-12-25]]

^<<v46-12-25,25>>^ so that there should be no division^&#42;1^ in the body, but that its members should have the same care for one another.

[NOTE]
====
. Or, “split.” Gr., skhiʹsma, “schism”; Lat., sciʹsma.
====

[[v46-12-26]]

^<<v46-12-26,26>>^ And if one member suffers, all the other members suffer with it; or if a member is glorified, all the other members rejoice with it.

[[v46-12-27]]

^<<v46-12-27,27>>^ Now YOU are Christ’s body, and members individually.

[[v46-12-28]]

^<<v46-12-28,28>>^ And God has set the respective ones in the congregation, first, apostles; second, prophets; third, teachers; then powerful works;^&#42;1^ then gifts of healings; helpful services, abilities to direct,^&#42;2^ different tongues.

[NOTE]
====
. “Powerful works.” Or, “miracles.”
. Lit., “steerings.” Gr., ky·ber·neʹseis; Lat., gu·ber·na·ti·oʹnes.
====

[[v46-12-29]]

^<<v46-12-29,29>>^ Not all are apostles, are they? Not all are prophets, are they? Not all are teachers, are they? Not all perform powerful works, do they?^&#42;1^

[NOTE]
====
. Lit., “Not all are powers, are they?”
====

[[v46-12-30]]

^<<v46-12-30,30>>^ Not all have gifts of healings, do they? Not all speak in tongues, do they? Not all are translators, are they?

[[v46-12-31]]

^<<v46-12-31,31>>^ But keep zealously seeking the greater^&#42;1^ gifts. And yet I show YOU a surpassing way.

[NOTE]
====
. Or, “the greatest.”
====

'''

xref:046-1-corinthians/046-1-corinthians-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-013.adoc#v46-13-0[Próximo Capítulo &#62;]