include::./index.adoc[]

[[v46-11-0]]
=== The First to the Corinthians, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-11-1]]

^<<v46-11-1,1>>^ Become imitators of me, even as I am of Christ.

[[v46-11-2]]

^<<v46-11-2,2>>^ Now I commend YOU because in all things YOU have me in mind and YOU are holding fast the traditions just as I handed &#91;them&#93; on to YOU.

[[v46-11-3]]

^<<v46-11-3,3>>^ But I want YOU to know that the head of every man is the Christ; in turn the head of a woman is the man; in turn the head of the Christ is God.

[[v46-11-4]]

^<<v46-11-4,4>>^ Every man that prays or prophesies having something on his head shames his head;

[[v46-11-5]]

^<<v46-11-5,5>>^ but every woman that prays or prophesies with her head uncovered^&#42;1^ shames her head, for it is one and the same as if she were a &#91;woman&#93; with a shaved head.^&#42;2^

[NOTE]
====
. Or, “unveiled.”
. That is, as punishment for immorality.
====

[[v46-11-6]]

^<<v46-11-6,6>>^ For if a woman does not cover herself, let her also be shorn; but if it is disgraceful for a woman to be shorn or shaved, let her be covered.

[[v46-11-7]]

^<<v46-11-7,7>>^ For a man ought not to have his head covered, as he is God’s image and glory; but the woman is man’s glory.

[[v46-11-8]]

^<<v46-11-8,8>>^ For man is not out of^&#42;1^ woman, but woman out of^&#42;2^ man;

[NOTE]
====
. Or, “man does not belong to.”
. Or, “woman belongs to.”
====

[[v46-11-9]]

^<<v46-11-9,9>>^ and, what is more, man was not created for the sake of the woman, but woman for the sake of the man.

[[v46-11-10]]

^<<v46-11-10,10>>^ That is why the woman ought to have a sign of authority^&#42;1^ upon her head because of the angels.

[NOTE]
====
. Or, “permitted freedom.”
====

[[v46-11-11]]

^<<v46-11-11,11>>^ Besides, in connection with &#91;the&#93; Lord neither is woman without man nor man without woman.

[[v46-11-12]]

^<<v46-11-12,12>>^ For just as the woman is out of the man, so also the man is through the woman; but all things are out of God.

[[v46-11-13]]

^<<v46-11-13,13>>^ Judge for YOUR own selves: Is it fitting for a woman to pray uncovered to God?

[[v46-11-14]]

^<<v46-11-14,14>>^ Does not nature itself teach YOU that if a man has long hair, it is a dishonor to him;

[[v46-11-15]]

^<<v46-11-15,15>>^ but if a woman has long hair, it is a glory to her? Because her hair is given her instead of a headdress.^&#42;1^

[NOTE]
====
. Or, “given her as a covering.”
====

[[v46-11-16]]

^<<v46-11-16,16>>^ However, if any man seems to dispute for some other custom, we have no other, neither do the congregations of God.

[[v46-11-17]]

^<<v46-11-17,17>>^ But, while giving these instructions, I do not commend YOU because it is, not for the better, but for the worse that YOU meet together.

[[v46-11-18]]

^<<v46-11-18,18>>^ For first of all, when YOU come together in a congregation, I hear^&#42;1^ divisions^&#42;2^ exist among YOU; and in some measure I believe it.

[NOTE]
====
. Or, “keep on hearing.”
. Or, “splits.” Gr., skhiʹsma·ta, “schisms.”
====

[[v46-11-19]]

^<<v46-11-19,19>>^ For there must also be sects^&#42;1^ among YOU, that the persons approved may also become manifest among YOU.

[NOTE]
====
. “Sects.” Gr., hai·reʹseis; Lat., heʹre·ses.
====

[[v46-11-20]]

^<<v46-11-20,20>>^ Therefore, when YOU come together to one place, it is not possible to eat^&#42;1^ the Lord’s evening meal.^&#42;2^

[NOTE]
====
. Or, “there is no eating of.”
. Lit., “supper pertaining to the Lord.”
====

[[v46-11-21]]

^<<v46-11-21,21>>^ For, when YOU eat &#91;it&#93;,^&#42;1^ each one takes his own evening meal beforehand, so that one is hungry but another is intoxicated.

[NOTE]
====
. Or, “when he eats [it].”
====

[[v46-11-22]]

^<<v46-11-22,22>>^ Certainly YOU do have houses for eating and drinking, do YOU not? Or do YOU despise the congregation of God and make those who have nothing ashamed? What shall I say to YOU? Shall I commend YOU? In this I do not commend YOU.

[[v46-11-23]]

^<<v46-11-23,23>>^ For I received from the Lord^&#42;1^ that which I also handed on to YOU, that the Lord Jesus in the night in which he was going to be handed over took a loaf

[NOTE]
====
. “The Lord,” אAB; J13,​14, “Jehovah.”
====

[[v46-11-24]]

^<<v46-11-24,24>>^ and, after giving thanks, he broke it and said: “This means^&#42;1^ my body which is in YOUR behalf. Keep doing this in remembrance of me.”

[NOTE]
====
. Lit., “is.” Gr., e·stin. See Mt 26:26 ftn.
====

[[v46-11-25]]

^<<v46-11-25,25>>^ He did likewise respecting the cup also, after he had the evening meal, saying: “This cup means the new covenant by virtue of my blood. Keep doing this, as often as YOU drink it, in remembrance of me.”

[[v46-11-26]]

^<<v46-11-26,26>>^ For as often as YOU eat this loaf and drink this cup, YOU keep proclaiming the death of the Lord, until he arrives.

[[v46-11-27]]

^<<v46-11-27,27>>^ Consequently whoever eats the loaf or drinks the cup of the Lord unworthily will be guilty respecting the body and the blood of the Lord.

[[v46-11-28]]

^<<v46-11-28,28>>^ First let a man approve himself after scrutiny, and thus let him eat of the loaf and drink of the cup.

[[v46-11-29]]

^<<v46-11-29,29>>^ For he that eats and drinks eats and drinks judgment against himself if he does not discern the body.

[[v46-11-30]]

^<<v46-11-30,30>>^ That is why many among YOU are weak and sickly, and quite a few are sleeping &#91;in death&#93;.

[[v46-11-31]]

^<<v46-11-31,31>>^ But if we would discern what we ourselves are, we would not be judged.

[[v46-11-32]]

^<<v46-11-32,32>>^ However, when we are judged, we are disciplined by Jehovah,^&#42;1^ that we may not become condemned with the world.

[NOTE]
====
. See App 1D.
====

[[v46-11-33]]

^<<v46-11-33,33>>^ Consequently, my brothers, when YOU come together to eat &#91;it&#93;, wait for one another.

[[v46-11-34]]

^<<v46-11-34,34>>^ If anyone is hungry, let him eat at home, that YOU may not come together for judgment. But the remaining matters I will set in order when I get there.

'''

xref:046-1-corinthians/046-1-corinthians-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-012.adoc#v46-12-0[Próximo Capítulo &#62;]