include::./index.adoc[]

[[v46-6-0]]
=== The First to the Corinthians, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-6-1]]

^<<v46-6-1,1>>^ Does anyone of YOU that has a case against the other dare to go to court before unrighteous men, and not before the holy ones?

[[v46-6-2]]

^<<v46-6-2,2>>^ Or do YOU not know that the holy ones will judge the world? And if the world is to be judged by YOU, are YOU unfit to try very trivial matters?

[[v46-6-3]]

^<<v46-6-3,3>>^ Do YOU not know that we shall judge angels? Why, then, not matters of this life?

[[v46-6-4]]

^<<v46-6-4,4>>^ If, then, YOU do have matters of this life to be tried, is it the men looked down upon in the congregation that YOU put in as judges?

[[v46-6-5]]

^<<v46-6-5,5>>^ I am speaking to move YOU to shame. Is it true that there is not one wise man among YOU that will be able to judge between his brothers,

[[v46-6-6]]

^<<v46-6-6,6>>^ but brother goes to court with brother, and that before unbelievers?

[[v46-6-7]]

^<<v46-6-7,7>>^ Really, then, it means altogether a defeat for YOU that YOU are having lawsuits with one another. Why do YOU not rather let yourselves be wronged? Why do YOU not rather let yourselves be defrauded?

[[v46-6-8]]

^<<v46-6-8,8>>^ To the contrary, YOU wrong and defraud, and YOUR brothers at that.

[[v46-6-9]]

^<<v46-6-9,9>>^ What! Do YOU not know that unrighteous persons will not inherit God’s kingdom? Do not be misled. Neither fornicators, nor idolaters, nor adulterers,^&#42;1^ nor men kept for unnatural purposes, nor men who lie with men,^&#42;2^

[NOTE]
====
. “Adulterers.” Lat., a·dulʹte·ri.
. Or, “nor sodomites.” Lit., “nor liers with males.” Gr., ouʹte ar·se·no·koiʹtai; Lat., neʹque ma·scu·loʹrum con·cu·bi·toʹres.
====

[[v46-6-10]]

^<<v46-6-10,10>>^ nor thieves, nor greedy persons, nor drunkards, nor revilers, nor extortioners will inherit God’s kingdom.

[[v46-6-11]]

^<<v46-6-11,11>>^ And yet that is what some of YOU were. But YOU have been washed clean, but YOU have been sanctified,^&#42;1^ but YOU have been declared righteous in the name of our^&#42;2^ Lord Jesus Christ and with the spirit of our God.

[NOTE]
====
. Or, “you have been held sacred (treated as holy).” Gr., he·gi·aʹsthe·te; Lat., sanc·ti·fi·caʹti eʹstis; J17,​22(Heb.), qud·dash·temʹ.
. “Our,” BVgSypArm; P46אAD omit.
====

[[v46-6-12]]

^<<v46-6-12,12>>^ All things are lawful for me; but not all things are advantageous. All things are lawful for me; but I will not let myself be brought under authority by anything.

[[v46-6-13]]

^<<v46-6-13,13>>^ Foods for the belly, and the belly for foods; but God will bring both it and them to nothing. Now the body is not for fornication, but for the Lord; and the Lord is for the body.

[[v46-6-14]]

^<<v46-6-14,14>>^ But God both raised up the Lord and will raise us up out of &#91;death&#93; through his power.

[[v46-6-15]]

^<<v46-6-15,15>>^ Do YOU not know that YOUR bodies are members of Christ? Shall I, then, take the members of the Christ away and make them members of a harlot?^&#42;1^ Never may that happen!

[NOTE]
====
. Or, “fornicatrix; prostitute.” Gr., porʹnes.
====

[[v46-6-16]]

^<<v46-6-16,16>>^ What! Do YOU not know that he who is joined to a harlot is one body? For, “The two,” says he,^&#42;1^ “will be one flesh.”

[NOTE]
====
. Or, “it,” that is, the scripture.
====

[[v46-6-17]]

^<<v46-6-17,17>>^ But he who is joined to the Lord is one spirit.

[[v46-6-18]]

^<<v46-6-18,18>>^ Flee from fornication. Every other sin that a man may commit is outside his^&#42;1^ body, but he that practices fornication is sinning against his own body.

[NOTE]
====
. Lit., “of the.”
====

[[v46-6-19]]

^<<v46-6-19,19>>^ What! Do YOU not know that the body of YOU people is &#91;the&#93; temple^&#42;1^ of the holy spirit within YOU, which YOU have from God? Also, YOU do not belong to yourselves,

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·osʹ; Lat., temʹplum; J17(Heb.), heh·khalʹ, “palace (temple) of.”
====

[[v46-6-20]]

^<<v46-6-20,20>>^ for YOU were bought with a price. By all means, glorify God in the body of YOU people.

'''

xref:046-1-corinthians/046-1-corinthians-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-007.adoc#v46-7-0[Próximo Capítulo &#62;]