include::./index.adoc[]

[[v46-5-0]]
=== The First to the Corinthians, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v46-5-1]]

^<<v46-5-1,1>>^ Actually fornication^&#42;1^ is reported among YOU, and such fornication as is not even among the nations, that a wife a certain &#91;man&#93; has of &#91;his&#93; father.^&#42;2^

[NOTE]
====
. “Fornication.” Gr., por·neiʹa; Lat., for·ni·caʹti·o. See Nu 14:33 ftn, “Fornication”; App 5A.
. Or, “that a certain [man] has [his] father’s wife.”
====

[[v46-5-2]]

^<<v46-5-2,2>>^ And are YOU puffed up, and did YOU not rather mourn, in order that the man that committed this deed should be taken away from YOUR midst?

[[v46-5-3]]

^<<v46-5-3,3>>^ I for one, although absent in body but present in spirit, have certainly judged already, as if I were present, the man who has worked in such a way as this,

[[v46-5-4]]

^<<v46-5-4,4>>^ that in the name of our Lord Jesus, when YOU are gathered together, also my spirit with the power of our Lord Jesus,

[[v46-5-5]]

^<<v46-5-5,5>>^ YOU hand such a man over to Satan for the destruction of the flesh, in order that the spirit may be saved in the day of the Lord.

[[v46-5-6]]

^<<v46-5-6,6>>^ YOUR &#91;cause for&#93; boasting is not fine. Do YOU not know that a little leaven ferments the whole lump?

[[v46-5-7]]

^<<v46-5-7,7>>^ Clear away the old leaven, that YOU may be a new lump, according as YOU are free from ferment. For, indeed, Christ our passover has been sacrificed.

[[v46-5-8]]

^<<v46-5-8,8>>^ Consequently let us keep the festival, not with old leaven, neither with leaven of badness and wickedness, but with unfermented cakes of sincerity and truth.

[[v46-5-9]]

^<<v46-5-9,9>>^ In my letter I wrote YOU to quit mixing in company with fornicators,

[[v46-5-10]]

^<<v46-5-10,10>>^ not &#91;meaning&#93; entirely with the fornicators of this world or the greedy persons and extortioners or idolaters. Otherwise, YOU would actually have to get out of the world.

[[v46-5-11]]

^<<v46-5-11,11>>^ But now I am writing YOU to quit mixing in company with^&#42;1^ anyone called a brother that is a fornicator or a greedy person or an idolater or a reviler or a drunkard or an extortioner, not even eating with such a man.

[NOTE]
====
. Lit., “not to be mixing selves up with.” Gr., me sy·na·na·miʹgny·sthai; Lat., non com·miʹsce·ri.
====

[[v46-5-12]]

^<<v46-5-12,12>>^ For what do I have to do with judging those outside? Do YOU not judge those inside,

[[v46-5-13]]

^<<v46-5-13,13>>^ while God judges those outside? “Remove the wicked &#91;man&#93; from among yourselves.”

'''

xref:046-1-corinthians/046-1-corinthians-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corinthians/046-1-corinthians-006.adoc#v46-6-0[Próximo Capítulo &#62;]