include::./index.adoc[]

[[v6-2-0]]
=== Joshua, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-2-1]]

^<<v6-2-1,1>>^ Then Joshua the son of Nun sent two men out secretly from Shitʹtim^&#42;1^ as spies, saying: “Go, take a look at the land and Jerʹi·cho.” So they went and came to the house of a prostitute woman whose name was Raʹhab, and they took up lodging there.

[NOTE]
====
. Or, “the acacia trees.”
====

[[v6-2-2]]

^<<v6-2-2,2>>^ In time it was said to the king of Jerʹi·cho: “Look! Men from the sons of Israel have come in here tonight to search out the land.”

[[v6-2-3]]

^<<v6-2-3,3>>^ At that the king of Jerʹi·cho sent to Raʹhab, saying: “Bring out the men that came to you, that have come into your house, for it is to search out all the land that they have come.”

[[v6-2-4]]

^<<v6-2-4,4>>^ Meantime the woman took the two men and concealed them. And she proceeded to say: “Yes, the men did come to me, and I did not know from where they were.

[[v6-2-5]]

^<<v6-2-5,5>>^ And it came about at the closing of the gate by dark that the men went out. I just do not know where the men have gone. Chase after them quickly, for YOU will overtake them.”

[[v6-2-6]]

^<<v6-2-6,6>>^ (She, though, had taken them up to the roof, and she kept them out of sight among stalks of flax laid in rows for her upon the roof.)

[[v6-2-7]]

^<<v6-2-7,7>>^ And the men chased after them in the direction of the Jordan at the fords, and they shut the gate immediately after those chasing after them had gone out.

[[v6-2-8]]

^<<v6-2-8,8>>^ As for these, before they could lie down, she herself came up to them on the roof.

[[v6-2-9]]

^<<v6-2-9,9>>^ And she went on to say to the men: “I do know that Jehovah will certainly give YOU the land, and that the fright of YOU has fallen upon us, and that all the inhabitants of the land have become disheartened because of YOU.

[[v6-2-10]]

^<<v6-2-10,10>>^ For we have heard how Jehovah dried up the waters of the Red Sea from before YOU when YOU came out of Egypt, and what YOU did to the two kings of the Amʹor·ites who were on the other side of the Jordan, namely, Siʹhon and Og, whom YOU devoted to destruction.

[[v6-2-11]]

^<<v6-2-11,11>>^ When we got to hear it, then our hearts began to melt, and no spirit^&#42;1^ has arisen yet in anybody because of YOU, for Jehovah YOUR God is God in the heavens above and on the earth beneath.

[NOTE]
====
. Or, “courage.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus.
====

[[v6-2-12]]

^<<v6-2-12,12>>^ And now, please, swear to me by Jehovah that, because I have exercised loving-kindness^&#42;1^ toward YOU, YOU also will certainly exercise loving-kindness toward the household of my father, and YOU must give me a trustworthy sign.

[NOTE]
====
. Or, “loyal love.”
====

[[v6-2-13]]

^<<v6-2-13,13>>^ And YOU must preserve alive my father and my mother and my brothers and my sisters and all who belong to them, and YOU must deliver our souls from death.”

[[v6-2-14]]

^<<v6-2-14,14>>^ At that the men said to her: “Our souls are to die instead of YOU people! If YOU will not tell about this matter of ours, it must also occur that when Jehovah gives us the land, we also shall certainly exercise loving-kindness and trustworthiness^&#42;1^ toward you.”

[NOTE]
====
. Or, “and truth (faithfulness).” Heb., we·ʼemethʹ.
====

[[v6-2-15]]

^<<v6-2-15,15>>^ After that she had them descend by a rope through the window, for her house was on a side of the wall, and it was on the wall that she was dwelling.

[[v6-2-16]]

^<<v6-2-16,16>>^ And she proceeded to say to them: “Go to the mountainous region, that those in pursuit may not come in contact with YOU; and YOU must keep hid there three days, until those in pursuit have come back, and afterward YOU may go in YOUR own direction.”

[[v6-2-17]]

^<<v6-2-17,17>>^ In turn the men said to her: “We are free from guilt respecting this oath of yours that you have made us swear.

[[v6-2-18]]

^<<v6-2-18,18>>^ Look! We are coming into the land. This cord of scarlet thread you should tie in the window by which you have had us descend, and your father and your mother and your brothers and all the household of your father you should gather to yourself into the house.

[[v6-2-19]]

^<<v6-2-19,19>>^ And it must occur that anyone who goes out of the doors of your house into the open, his blood will be upon his own head, and we shall be free from guilt; and everyone who continues with you in the house, his blood will be on our heads if a hand should come upon him.

[[v6-2-20]]

^<<v6-2-20,20>>^ And if you should report this matter of ours, we shall also have become free from guilt respecting this oath of yours that you have made us swear.”

[[v6-2-21]]

^<<v6-2-21,21>>^ To this she said: “According to YOUR words so let it be.”
With that she sent them off, and they went their way. After that she tied the scarlet cord in the window.

[[v6-2-22]]

^<<v6-2-22,22>>^ So they went and came to the mountainous region and kept dwelling there three days, until the pursuers had come back. Now the pursuers were looking for them on every road, and they did not find them.

[[v6-2-23]]

^<<v6-2-23,23>>^ And the two men proceeded to descend again from the mountainous region and to cross over and come to Joshua the son of Nun, and they began to relate to him all the things that had happened to them.

[[v6-2-24]]

^<<v6-2-24,24>>^ And they went on to say to Joshua: “Jehovah has given all the land into our hand. Consequently all the inhabitants of the land have also grown disheartened because of us.”

'''

xref:006-joshua/006-joshua-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-joshua/006-joshua-003.adoc#v6-3-0[Próximo Capítulo &#62;]