include::./index.adoc[]

[[v6-19-0]]
=== Joshua, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-19-1]]

^<<v6-19-1,1>>^ Then the second lot came out for Simʹe·on, for the tribe of the sons of Simʹe·on by their families. And their inheritance came to be in the midst of the inheritance of the sons of Judah.

[[v6-19-2]]

^<<v6-19-2,2>>^ And they came to have in their inheritance Beʹer-sheʹba with Sheʹba,^&#42;1^ and Mo·laʹdah,

[NOTE]
====
. “Sheba.” LXXB(Gr.), Sa·ma·aʹ, “Shema.”
====

[[v6-19-3]]

^<<v6-19-3,3>>^ and Haʹzar-shuʹal and Baʹlah and Eʹzem,

[[v6-19-4]]

^<<v6-19-4,4>>^ and El·toʹlad and Beʹthul and Horʹmah,

[[v6-19-5]]

^<<v6-19-5,5>>^ and Zikʹlag and Beth-marʹca·both and Haʹzar-suʹsah,

[[v6-19-6]]

^<<v6-19-6,6>>^ and Beth-le·baʹoth and Sha·ruʹhen; thirteen cities and their settlements.

[[v6-19-7]]

^<<v6-19-7,7>>^ Aʹin, Rimʹmon and Eʹther and Aʹshan; four cities and their settlements,

[[v6-19-8]]

^<<v6-19-8,8>>^ and all the settlements that were all around these cities as far as Baʹal·ath-beʹer, Raʹmah of the south.^&#42;1^ This was the inheritance of the tribe of the sons of Simʹe·on by their families.

[NOTE]
====
. Or, “the Negeb.”
====

[[v6-19-9]]

^<<v6-19-9,9>>^ The inheritance of the sons of Simʹe·on was out of the allotment of the sons of Judah, because the share of the sons of Judah proved to be too large for them. So the sons of Simʹe·on got a possession in the midst of their inheritance.

[[v6-19-10]]

^<<v6-19-10,10>>^ Next the third lot came up for the sons of Zebʹu·lun by their families, and the boundary of their inheritance came to be as far as Saʹrid.

[[v6-19-11]]

^<<v6-19-11,11>>^ And their boundary went up westward also to Marʹe·al and reached to Dabʹbe·sheth and reached to the torrent valley that is in front of Jokʹne·am.

[[v6-19-12]]

^<<v6-19-12,12>>^ And it went back from Saʹrid eastward toward the rising of the sun to the border of Chisʹloth-taʹbor and went out to Dabʹe·rath and went up to Ja·phiʹa.

[[v6-19-13]]

^<<v6-19-13,13>>^ And from there it passed over eastward toward the sunrise to Gath-heʹpher, to Eth-kaʹzin, and went out to Rimʹmon and was marked out to Neʹah.^&#42;1^

[NOTE]
====
. Lit., “which was marked out to Neah.”
====

[[v6-19-14]]

^<<v6-19-14,14>>^ And the boundary went around it on the north to Hanʹna·thon, and its terminations proved to be at the valley of Iphʹtah-el,

[[v6-19-15]]

^<<v6-19-15,15>>^ and Katʹtath and Na·halʹal and Shimʹron and Iʹda·lah and Bethʹle·hem; twelve cities and their settlements.

[[v6-19-16]]

^<<v6-19-16,16>>^ This was the inheritance of the sons of Zebʹu·lun by their families. These were the cities and their settlements.

[[v6-19-17]]

^<<v6-19-17,17>>^ It was for Isʹsa·char that the fourth lot came out, for the sons of Isʹsa·char by their families.

[[v6-19-18]]

^<<v6-19-18,18>>^ And their boundary came to be to Jezʹre·el and Che·sulʹloth and Shuʹnem,

[[v6-19-19]]

^<<v6-19-19,19>>^ and Haphʹa·raʹim and Shiʹon and An·a·haʹrath,

[[v6-19-20]]

^<<v6-19-20,20>>^ and Rabʹbith and Kishʹi·on and Eʹbez,

[[v6-19-21]]

^<<v6-19-21,21>>^ and Reʹmeth and En-ganʹnim and En-hadʹdah and Beth-pazʹzez.

[[v6-19-22]]

^<<v6-19-22,22>>^ And the boundary reached to Taʹbor and Sha·ha·zuʹmah and Beth-sheʹmesh, and the terminations of their border proved to be at the Jordan; sixteen cities and their settlements.

[[v6-19-23]]

^<<v6-19-23,23>>^ This was the inheritance of the tribe of the sons of Isʹsa·char by their families, the cities and their settlements.

[[v6-19-24]]

^<<v6-19-24,24>>^ Then the fifth lot came out for the tribe of the sons of Ashʹer by their families.

[[v6-19-25]]

^<<v6-19-25,25>>^ And their boundary came to be Helʹkath and Haʹli and Beʹten and Achʹshaph,

[[v6-19-26]]

^<<v6-19-26,26>>^ and Al·lamʹme·lech and Aʹmad and Miʹshal. And it reached westward to Carʹmel and to Shiʹhor-libʹnath,

[[v6-19-27]]

^<<v6-19-27,27>>^ and it went back toward the rising of the sun to Beth-daʹgon and reached to Zebʹu·lun and the valley of Iphʹtah-el to the north, to Beth-eʹmek and Ne·iʹel, and it went out to Caʹbul on the left,

[[v6-19-28]]

^<<v6-19-28,28>>^ and to Eʹbron and Reʹhob and Hamʹmon and Kaʹnah as far as populous Siʹdon.

[[v6-19-29]]

^<<v6-19-29,29>>^ And the boundary went back to Raʹmah and as far as the fortified city of Tyre. And the boundary went back to Hoʹsah, and its terminations came to be at the sea in the region of Achʹzib,^&#42;1^

[NOTE]
====
. “In the region of Achzib.” Possibly, “and to Meheleb and Achzib.” LXXB, “and toward Leb and Echozob.”
====

[[v6-19-30]]

^<<v6-19-30,30>>^ and Umʹmah and Aʹphek and Reʹhob; twenty-two cities and their settlements.

[[v6-19-31]]

^<<v6-19-31,31>>^ This was the inheritance of the tribe of the sons of Ashʹer by their families. These were the cities and their settlements.

[[v6-19-32]]

^<<v6-19-32,32>>^ It was for the sons of Naphʹta·li that the sixth lot came out, for the sons of Naphʹta·li by their families.

[[v6-19-33]]

^<<v6-19-33,33>>^ And their boundary came to be from Heʹleph, from the big tree in Za·a·nanʹnim, and Adʹa·mi-neʹkeb and Jabʹne·el as far as Lakʹkum; and its terminations came to be at the Jordan.

[[v6-19-34]]

^<<v6-19-34,34>>^ And the boundary went back westward to Azʹnoth-taʹbor and went out from there to Hukʹkok and reached to Zebʹu·lun on the south, and to Ashʹer it reached on the west and to Judah at the Jordan^&#42;1^ toward the rising of the sun.

[NOTE]
====
. “And to Judah at the Jordan.” Possibly, “and by the banks of the Jordan,” by a slight correction of M proposed by C. F. Houbigant; LXX, “and the Jordan.” Compare 3:15.
====

[[v6-19-35]]

^<<v6-19-35,35>>^ And the fortified cities were Zidʹdim, Zer and Hamʹmath, Rakʹkath and Chinʹne·reth,

[[v6-19-36]]

^<<v6-19-36,36>>^ and Adʹa·mah and Raʹmah and Haʹzor,

[[v6-19-37]]

^<<v6-19-37,37>>^ and Keʹdesh and Edʹre·i and En-haʹzor,

[[v6-19-38]]

^<<v6-19-38,38>>^ and Yiʹron and Migʹdal-el, Hoʹrem and Beth-aʹnath and Beth-sheʹmesh; nineteen cities and their settlements.

[[v6-19-39]]

^<<v6-19-39,39>>^ This was the inheritance of the tribe of the sons of Naphʹta·li by their families, the cities and their settlements.

[[v6-19-40]]

^<<v6-19-40,40>>^ It was for the tribe of the sons of Dan by their families that the seventh lot came out.

[[v6-19-41]]

^<<v6-19-41,41>>^ And the border of their inheritance came to be Zoʹrah and Eshʹta·ol and Ir-sheʹmesh,

[[v6-19-42]]

^<<v6-19-42,42>>^ and Sha·al·abʹbin and Aiʹja·lon and Ithʹlah,

[[v6-19-43]]

^<<v6-19-43,43>>^ and Eʹlon and Timʹnah and Ekʹron,

[[v6-19-44]]

^<<v6-19-44,44>>^ and Elʹte·keh and Gibʹbe·thon and Baʹal·ath,

[[v6-19-45]]

^<<v6-19-45,45>>^ and Jeʹhud^&#42;1^ and Benʹe-beʹrak and Gath-rimʹmon,

[NOTE]
====
. Or, “Jazur.” LXXB, “Azor.”
====

[[v6-19-46]]

^<<v6-19-46,46>>^ and Me-jarʹkon and Rakʹkon, with the border in front of Jopʹpa.

[[v6-19-47]]

^<<v6-19-47,47>>^ And the territory of the sons of Dan was too cramped for them.^&#42;1^ And the sons of Dan proceeded to go up and war against Leʹshem and to capture it and strike it with the edge of the sword. Then they took possession of it and went dwelling in it, and they began to call Leʹshem Dan, according to the name of Dan their forefather.

[NOTE]
====
. Lit., “And the territory of the sons of Dan went on out (got away; was lost) from them.”
====

[[v6-19-48]]

^<<v6-19-48,48>>^ This was the inheritance of the tribe of the sons of Dan by their families. These were the cities and their settlements.

[[v6-19-49]]

^<<v6-19-49,49>>^ Thus they finished dividing the land for a possession by its territories. Then the sons of Israel gave an inheritance to Joshua the son of Nun in their midst.

[[v6-19-50]]

^<<v6-19-50,50>>^ At the order of Jehovah they gave him the city for which he asked, namely, Timʹnath-seʹrah, in the mountainous region of Eʹphra·im; and he began to build up the city and dwell in it.

[[v6-19-51]]

^<<v6-19-51,51>>^ These were the inheritances that El·e·aʹzar the priest and Joshua the son of Nun and the heads of the fathers of the tribes of the sons of Israel distributed as a possession by lot in Shiʹloh before Jehovah, at the entrance of the tent of meeting. So they left off from apportioning the land.

'''

xref:006-joshua/006-joshua-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-joshua/006-joshua-020.adoc#v6-20-0[Próximo Capítulo &#62;]