include::./index.adoc[]

[[v6-9-0]]
=== Joshua, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-9-1]]

^<<v6-9-1,1>>^ And it came about that as soon as all the kings who were on the side of the Jordan in the mountainous region and in the She·pheʹlah^&#42;1^ and along the whole coast of the Great Sea and^&#42;2^ in front of Lebʹa·non, the Hitʹtites and the Amʹor·ites, the Caʹnaan·ites, the Perʹiz·zites, the Hiʹvites and the Jebʹu·sites, heard of it,

[NOTE]
====
. Or, “the lowland.”
. “And,” LXX; Vg, “also”; M omits.
====

[[v6-9-2]]

^<<v6-9-2,2>>^ they began to assemble themselves all together to make war against Joshua and Israel unanimously.

[[v6-9-3]]

^<<v6-9-3,3>>^ And the inhabitants of Gibʹe·on heard what Joshua had done to Jerʹi·cho and Aʹi.

[[v6-9-4]]

^<<v6-9-4,4>>^ So they, even of their own accord, acted with shrewdness and went and stocked themselves with provisions and took worn-out sacks for their asses, and wine skin-bottles worn out and burst and tied up,

[[v6-9-5]]

^<<v6-9-5,5>>^ and worn-out and patched sandals on their feet, and worn-out garments upon themselves, and all the bread of their provisions proved to be dry and crumby.

[[v6-9-6]]

^<<v6-9-6,6>>^ Then they went to Joshua at the camp at Gilʹgal and said to him and the men of Israel: “It is from a distant land that we have come. And now CONCLUDE a covenant with us.”

[[v6-9-7]]

^<<v6-9-7,7>>^ At this the men of Israel said to the Hiʹvites: “Perhaps it is in our vicinity that you are dwelling. So how could we conclude^&#42;1^ a covenant with you?”

[NOTE]
====
. Lit., “could I [collectively] cut.”
====

[[v6-9-8]]

^<<v6-9-8,8>>^ In turn they said to Joshua: “We are your servants.”^&#42;1^
Then Joshua said to them: “Who are YOU, and where do YOU come from?”

[NOTE]
====
. Or, “slaves.”
====

[[v6-9-9]]

^<<v6-9-9,9>>^ At this they said to him: “It is from a very distant land that your servants have come in regard to the name of Jehovah your God, because we have heard of his fame and of all that he did in Egypt,

[[v6-9-10]]

^<<v6-9-10,10>>^ and of all that he did to the two kings of the Amʹor·ites who were on the other side of the Jordan, namely, Siʹhon the king of Heshʹbon and Og the king of Baʹshan, who was in Ashʹta·roth.

[[v6-9-11]]

^<<v6-9-11,11>>^ Hence our older men and all the inhabitants of our land said this to us, ‘Take provisions in YOUR hands for the journey and go to meet them, and YOU must say to them: “We are YOUR servants. And now conclude a covenant with us.”’

[[v6-9-12]]

^<<v6-9-12,12>>^ This bread of ours, it was hot when we took it as our provisions out of our houses on the day of our going out to come here to YOU, and now, look! it is dry and has become crumby.

[[v6-9-13]]

^<<v6-9-13,13>>^ And these are the wine skin-bottles that we filled new, and, look! they have burst, and these garments and sandals of ours, they have worn out because of the great length of the journey.”

[[v6-9-14]]

^<<v6-9-14,14>>^ Upon that the men took some of their provisions, and at the mouth of Jehovah they did not inquire.

[[v6-9-15]]

^<<v6-9-15,15>>^ And Joshua went making peace with them and concluding a covenant with them to let them live, and so the chieftains of the assembly swore to them.

[[v6-9-16]]

^<<v6-9-16,16>>^ And it came about that at the end of three days, after they had concluded a covenant with them, they got to hear that they were near to them and it was in their vicinity they were dwelling.

[[v6-9-17]]

^<<v6-9-17,17>>^ Then the sons of Israel pulled out and came to their cities on the third day, and their cities were Gibʹe·on and Che·phiʹrah and Be·erʹoth and Kirʹi·ath-jeʹa·rim.

[[v6-9-18]]

^<<v6-9-18,18>>^ And the sons of Israel did not strike them, because the chieftains of the assembly had sworn to them by Jehovah the God of Israel. And all the assembly began to murmur against the chieftains.

[[v6-9-19]]

^<<v6-9-19,19>>^ At this all the chieftains said to all the assembly: “We, for our part, have sworn to them by Jehovah the God of Israel, and now we are not allowed to hurt them.

[[v6-9-20]]

^<<v6-9-20,20>>^ This is what we shall do to them while letting them live,^&#42;1^ that no indignation may come upon us over the oath that we have sworn to them.”

[NOTE]
====
. “Letting . . . live.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v6-9-21]]

^<<v6-9-21,21>>^ So the chieftains said to them: “Let them live and let them become gatherers^&#42;1^ of wood and drawers of water for all the assembly, just as the chieftains have promised them.”

[NOTE]
====
. Or, “cutters.”
====

[[v6-9-22]]

^<<v6-9-22,22>>^ Joshua now called them and spoke to them, saying: “Why did YOU trick us, saying, ‘We are very far away from YOU,’ whereas YOU are dwelling in our very midst?

[[v6-9-23]]

^<<v6-9-23,23>>^ And now YOU are cursed people, and a slave’s position and being gatherers^&#42;1^ of wood and drawers of water for the house of my God will never be cut off from YOU.”

[NOTE]
====
. Lit., “and a slave and gatherers.”
====

[[v6-9-24]]

^<<v6-9-24,24>>^ Then they answered Joshua and said: “It was because your servants were plainly told that Jehovah your God had commanded Moses his servant to give YOU all the land and to annihilate all the inhabitants of the land from before YOU, and we became very much afraid for our souls^&#42;1^ because of YOU. So we did this thing.

[NOTE]
====
. “For our souls (lives).” Heb., lenaph·sho·thehʹnu; Gr., psy·khonʹ; Lat., a·ni·maʹbus.
====

[[v6-9-25]]

^<<v6-9-25,25>>^ And now here we are, in your hand. Just as it is good and right in your eyes to do to us, do.”

[[v6-9-26]]

^<<v6-9-26,26>>^ And he proceeded to do so to them and to deliver them from the hand of the sons of Israel, and they did not kill them.

[[v6-9-27]]

^<<v6-9-27,27>>^ Accordingly Joshua constituted them^&#42;1^ on that day gatherers of wood and drawers of water for the assembly and for Jehovah’s altar, down to this day, at the place that he should choose.

[NOTE]
====
. “Accordingly . . . [he] constituted them.” Lit., “And [he] gave them.” Heb., wai·yit·tenemʹ (from na·thanʹ, from which the word “Nethinim” is derived).
====

'''

xref:006-joshua/006-joshua-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-joshua/006-joshua-010.adoc#v6-10-0[Próximo Capítulo &#62;]