include::./index.adoc[]

[[v6-5-0]]
=== Joshua, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-5-1]]

^<<v6-5-1,1>>^ And it came about that as soon as all the kings of the Amʹor·ites, who were on the side of the Jordan to the west,^&#42;1^ and all the kings of the Caʹnaan·ites, who were by the sea, heard that Jehovah had dried up the waters of the Jordan from before the sons of Israel until they had passed over, then their hearts began to melt, and there proved to be no spiritedness^&#42;2^ in them anymore because of the sons of Israel.

[NOTE]
====
. Lit., “seaward.”
. Or, “spirit; courage.” See 2:11 ftn.
====

[[v6-5-2]]

^<<v6-5-2,2>>^ At that particular time Jehovah said to Joshua: “Make for yourself flint knives^&#42;1^ and circumcise the sons of Israel again, the second time.”

[NOTE]
====
. Lit., “daggers (swords) of rock.” Heb., cha·revohthʹ tsu·rimʹ.
====

[[v6-5-3]]

^<<v6-5-3,3>>^ Accordingly Joshua made flint knives for himself and circumcised the sons of Israel at Gibʹe·ath-ha·arʹa·loth.^&#42;1^

[NOTE]
====
. “Hill of the Foreskins,” Vg; LXX, “the place called Hill (Mound) of the Foreskins.”
====

[[v6-5-4]]

^<<v6-5-4,4>>^ And this was the reason why Joshua did the circumcising: all the people that came out of Egypt, the males, all the men of war, had died in the wilderness on the road when they were coming out of Egypt.

[[v6-5-5]]

^<<v6-5-5,5>>^ For all the people who came out proved to be circumcised, but all the people born in the wilderness on the road when they were coming out of Egypt they had not circumcised.

[[v6-5-6]]

^<<v6-5-6,6>>^ For the sons of Israel had walked forty years in the wilderness, until all the nation of the men of war who came out of Egypt that did not listen to the voice of Jehovah had come to its finish, to whom Jehovah swore that he would never let them see the land that Jehovah had sworn to their forefathers to give to us, a land flowing with milk and honey.

[[v6-5-7]]

^<<v6-5-7,7>>^ And their sons he raised up instead of them. These Joshua circumcised, because they proved to be uncircumcised, for they had not circumcised them on the road.

[[v6-5-8]]

^<<v6-5-8,8>>^ And it came about that when they had completed circumcising all the nation, they kept sitting in their place in the camp until they revived.

[[v6-5-9]]

^<<v6-5-9,9>>^ Then Jehovah said to Joshua: “Today I have rolled away the reproach of Egypt from off YOU.” So the name of that place came to be called Gilʹgal^&#42;1^ until this day.

[NOTE]
====
. Meaning “A Rolling Away.”
====

[[v6-5-10]]

^<<v6-5-10,10>>^ And the sons of Israel continued to camp in Gilʹgal, and they proceeded to carry out the passover on the fourteenth day of the month, in the evening, on the desert plains of Jerʹi·cho.

[[v6-5-11]]

^<<v6-5-11,11>>^ And they began to eat some of the yield of the land the day after the passover, unfermented cakes and roasted grains, on this same day.

[[v6-5-12]]

^<<v6-5-12,12>>^ Then the manna ceased on the following day when they had eaten some of the yield of the land, and manna did not occur anymore for the sons of Israel, and they began to eat some of the produce of the land of Caʹnaan in that year.

[[v6-5-13]]

^<<v6-5-13,13>>^ And it came about when Joshua happened to be by Jerʹi·cho that he proceeded to raise his eyes and look, and there there was a man standing in front of him with his drawn sword in his hand. So Joshua walked up to him and said to him: “Are you for us or for our adversaries?”

[[v6-5-14]]

^<<v6-5-14,14>>^ To this he said: “No, but I—as prince of the army of Jehovah^&#42;1^ I have now come.” With that Joshua fell on his face to the earth and prostrated himself and said to him: “What is my lord saying to his servant?”

[NOTE]
====
. Or, “but I​—⁠as chief of the army of Jehovah.” Heb., ki ʼaniʹ sar-tsevaʼ-Yehwahʹ.
====

[[v6-5-15]]

^<<v6-5-15,15>>^ In turn the prince of the army of Jehovah said to Joshua: “Draw your sandals from off your feet, because the place on which you are standing is holy.” At once Joshua did so.

'''

xref:006-joshua/006-joshua-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-joshua/006-joshua-006.adoc#v6-6-0[Próximo Capítulo &#62;]