include::./index.adoc[]

[[v6-15-0]]
=== Joshua, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-15-1]]

^<<v6-15-1,1>>^ And the lot of the tribe of the sons of Judah by their families came to be to the boundary of Eʹdom, the wilderness of Zin, to the Negʹeb at its southern end.

[[v6-15-2]]

^<<v6-15-2,2>>^ And their southern boundary came to be from the extremity of the Salt Sea, from the bay that faces southward.

[[v6-15-3]]

^<<v6-15-3,3>>^ And it went out southward to the ascent^&#42;1^ of A·krabʹbim and passed over to Zin and went up from the south to Kaʹdesh-barʹne·a and passed over to Hezʹron and went up to Adʹdar and went around to Karʹka.

[NOTE]
====
. Or, “pass.”
====

[[v6-15-4]]

^<<v6-15-4,4>>^ And it passed on to Azʹmon and went out to the torrent valley of Egypt; and the boundary’s termination proved to be at the sea. This came to be their^&#42;1^ southern boundary.

[NOTE]
====
. “Their,” LXX; MSy, “your”; Vg omits.
====

[[v6-15-5]]

^<<v6-15-5,5>>^ And the eastern boundary was the Salt Sea up to the end^&#42;1^ of the Jordan, and the boundary at the northern corner was at the bay of the sea, at the end of the Jordan.

[NOTE]
====
. Or, “mouth.”
====

[[v6-15-6]]

^<<v6-15-6,6>>^ And the boundary went up to Beth-hogʹlah and passed over at the north of Beth-arʹa·bah, and the boundary went up to the stone of Boʹhan the son of Reuʹben.

[[v6-15-7]]

^<<v6-15-7,7>>^ And the boundary went up to Deʹbir at the low plain of Aʹchor and turning northward to Gilʹgal, which is in front of the ascent of A·dumʹmim, which is south of the torrent valley; and the boundary passed over to the waters of En-sheʹmesh, and its termination proved to be En-roʹgel.

[[v6-15-8]]

^<<v6-15-8,8>>^ And the boundary went up to the valley of the son of Hinʹnom to the slope of the Jebʹu·site at the south, that is to say, Jerusalem; and the boundary went up to the top of the mountain that faces the valley of Hinʹnom^&#42;1^ to the west, which is at the extremity of the low plain of Rephʹa·im to the north.

[NOTE]
====
. “Valley of Hinnom.” Heb., gheh-Hin·nomʹ; LXXA(Gr.), phaʹrag·gos En·nomʹ; Lat., Ge·henʹnom. See App 4C.
====

[[v6-15-9]]

^<<v6-15-9,9>>^ And the boundary was marked out from the top of the mountain to the spring of the waters of Neph·toʹah, and went out to the cities of Mount Eʹphron; and the boundary was marked out to Baʹal·ah, that is to say, Kirʹi·ath-jeʹa·rim.

[[v6-15-10]]

^<<v6-15-10,10>>^ And the boundary went around from Baʹal·ah westward to Mount Seʹir and passed over to the slope of Mount Jeʹa·rim at the north, that is to say, Chesʹa·lon; and it went down to Beth-sheʹmesh and passed over to Timʹnah.

[[v6-15-11]]

^<<v6-15-11,11>>^ And the boundary went out to the slope of Ekʹron to the north, and the boundary was marked out to Shikʹke·ron and passed over to Mount Baʹal·ah and went out to Jabʹne·el; and the boundary’s termination proved to be at the sea.

[[v6-15-12]]

^<<v6-15-12,12>>^ And the western boundary was at the Great Sea and its shoreland. This was the boundary all around, of the sons of Judah by their families.

[[v6-15-13]]

^<<v6-15-13,13>>^ And to Caʹleb the son of Je·phunʹneh he gave a share in the midst of the sons of Judah at the order of Jehovah to Joshua, namely, Kirʹi·ath-arʹba (&#91;said Arʹba being&#93; the father of Aʹnak), that is to say, Heʹbron.

[[v6-15-14]]

^<<v6-15-14,14>>^ So Caʹleb drove away from there the three sons of Aʹnak, namely, Sheʹshai and A·hiʹman and Talʹmai, those born of Aʹnak.^&#42;1^

[NOTE]
====
. See Nu 13:22 ftn.
====

[[v6-15-15]]

^<<v6-15-15,15>>^ Then he went up from there to the inhabitants of Deʹbir. (Now the name of Deʹbir before that was Kirʹi·ath-seʹpher.)

[[v6-15-16]]

^<<v6-15-16,16>>^ And Caʹleb proceeded to say: “Whoever strikes Kirʹi·ath-seʹpher and does capture it, I shall certainly give him Achʹsah my daughter as a wife.”

[[v6-15-17]]

^<<v6-15-17,17>>^ At that Othʹni·el the son of Keʹnaz, Caʹleb’s brother, captured it. Accordingly he gave him Achʹsah his daughter as a wife.

[[v6-15-18]]

^<<v6-15-18,18>>^ And it came about that when she was going home, she kept inciting him to ask a field from her father. Then she clapped her hands while upon the ass.^&#42;1^ At this Caʹleb said to her: “What do you want?”

[NOTE]
====
. Or, “Then she slid down (alighted) from off the ass.”
====

[[v6-15-19]]

^<<v6-15-19,19>>^ So she said: “Do give me a blessing, for it is a piece of land to the south you have given me, and you must give me Gulʹloth-maʹim.”^&#42;1^ Accordingly he gave her Upper Gulʹloth and Lower Gulʹloth.^&#42;2^

[NOTE]
====
. Meaning “Basin of Water.”
. Or, “the upper basin and the lower basin.”
====

[[v6-15-20]]

^<<v6-15-20,20>>^ This was the inheritance of the tribe of the sons of Judah by their families.

[[v6-15-21]]

^<<v6-15-21,21>>^ And the cities at the extremity of the tribe of the sons of Judah toward the boundary of Eʹdom in the south came to be Kabʹze·el and Eʹder and Jaʹgur,

[[v6-15-22]]

^<<v6-15-22,22>>^ and Kiʹnah and Di·moʹnah and A·daʹdah,

[[v6-15-23]]

^<<v6-15-23,23>>^ and Keʹdesh and Haʹzor and Ithʹnan,

[[v6-15-24]]

^<<v6-15-24,24>>^ Ziph and Teʹlem and Be·aʹloth,

[[v6-15-25]]

^<<v6-15-25,25>>^ and Haʹzor-ha·datʹtah and Keʹri·oth-hezʹron, that is to say, Haʹzor,

[[v6-15-26]]

^<<v6-15-26,26>>^ Aʹmam and Sheʹma and Mo·laʹdah,

[[v6-15-27]]

^<<v6-15-27,27>>^ and Haʹzar-gadʹdah and Heshʹmon and Beth-pelʹet,

[[v6-15-28]]

^<<v6-15-28,28>>^ and Haʹzar-shuʹal and Beʹer-sheʹba and Biz·i·o·thiʹah,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baʹal·ah and Iʹim and Eʹzem,

[[v6-15-30]]

^<<v6-15-30,30>>^ and El·toʹlad and Cheʹsil and Horʹmah,

[[v6-15-31]]

^<<v6-15-31,31>>^ and Zikʹlag and Mad·manʹnah and San·sanʹnah,

[[v6-15-32]]

^<<v6-15-32,32>>^ and Le·baʹoth and Shilʹhim and Aʹin and Rimʹmon; all the cities being twenty-nine, together with their settlements.

[[v6-15-33]]

^<<v6-15-33,33>>^ In the She·pheʹlah there were Eshʹta·ol and Zoʹrah and Ashʹnah,

[[v6-15-34]]

^<<v6-15-34,34>>^ and Za·noʹah and En-ganʹnim, Tapʹpu·ah and Eʹnam,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarʹmuth and A·dulʹlam, Soʹcoh and A·zeʹkah,

[[v6-15-36]]

^<<v6-15-36,36>>^ and Shaʹa·raʹim and Ad·i·thaʹim and Ge·deʹrah and Ged·e·ro·thaʹim; fourteen cities and their settlements.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zeʹnan and Ha·dashʹah and Migʹdal-gad,

[[v6-15-38]]

^<<v6-15-38,38>>^ and Diʹle·an and Mizʹpeh and Jokʹthe·el,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laʹchish and Bozʹkath and Egʹlon,

[[v6-15-40]]

^<<v6-15-40,40>>^ and Cabʹbon and Lahʹmam and Chitʹlish,

[[v6-15-41]]

^<<v6-15-41,41>>^ and Ge·deʹroth, Beth-daʹgon and Naʹa·mah and Mak·keʹdah; sixteen cities and their settlements.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libʹnah and Eʹther and Aʹshan,

[[v6-15-43]]

^<<v6-15-43,43>>^ and Iphʹtah and Ashʹnah and Neʹzib,

[[v6-15-44]]

^<<v6-15-44,44>>^ and Keiʹlah and Achʹzib and Ma·reʹshah; nine cities and their settlements.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ekʹron and its dependent towns^&#42;1^ and its settlements.

[NOTE]
====
. Lit., “its daughters.”
====

[[v6-15-46]]

^<<v6-15-46,46>>^ From Ekʹron westward all that is alongside Ashʹdod and their settlements.

[[v6-15-47]]

^<<v6-15-47,47>>^ Ashʹdod, its dependent towns and its settlements; Gaʹza, its dependent towns and its settlements, down to the torrent valley of Egypt, and the Great Sea^&#42;1^ and the adjacent region.

[NOTE]
====
. Lit., “the sea of the border; the bordering sea.” MmarginLXXSyVg, “the Great Sea.”
====

[[v6-15-48]]

^<<v6-15-48,48>>^ And in the mountainous region Shaʹmir and Jatʹtir and Soʹcoh,

[[v6-15-49]]

^<<v6-15-49,49>>^ and Danʹnah and Kirʹi·ath-sanʹnah, that is to say, Deʹbir,

[[v6-15-50]]

^<<v6-15-50,50>>^ and Aʹnab and Eshʹte·moh and Aʹnim,

[[v6-15-51]]

^<<v6-15-51,51>>^ and Goʹshen and Hoʹlon and Giʹloh; eleven cities and their settlements.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arab and Duʹmah and Eʹshan,

[[v6-15-53]]

^<<v6-15-53,53>>^ and Jaʹnim and Beth-tapʹpu·ah and A·pheʹkah,

[[v6-15-54]]

^<<v6-15-54,54>>^ and Humʹtah and Kirʹi·ath-arʹba, that is to say, Heʹbron, and Ziʹor; nine cities and their settlements.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maʹon, Carʹmel and Ziph and Jutʹtah,

[[v6-15-56]]

^<<v6-15-56,56>>^ and Jezʹre·el and Jokʹde·am and Za·noʹah,

[[v6-15-57]]

^<<v6-15-57,57>>^ Kaʹin, Gibʹe·ah and Timʹnah; ten cities and their settlements.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halʹhul, Beth-zur and Geʹdor,

[[v6-15-59]]

^<<v6-15-59,59>>^ and Maʹa·rath and Beth-aʹnoth and Elʹte·kon; six cities and their settlements.

[[v6-15-60]]

^<<v6-15-60,60>>^ Kirʹi·ath-baʹal, that is to say, Kirʹi·ath-jeʹa·rim, and Rabʹbah; two cities and their settlements.

[[v6-15-61]]

^<<v6-15-61,61>>^ In the wilderness Beth-arʹa·bah, Midʹdin and Se·caʹcah,

[[v6-15-62]]

^<<v6-15-62,62>>^ and Nibʹshan and the City of Salt and En-geʹdi; six cities and their settlements.

[[v6-15-63]]

^<<v6-15-63,63>>^ As for the Jebʹu·sites who were dwelling in Jerusalem, the sons of Judah were not able to drive them away; and the Jebʹu·sites continue dwelling with the sons of Judah in Jerusalem down to this day.

'''

xref:006-joshua/006-joshua-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-joshua/006-joshua-016.adoc#v6-16-0[Próximo Capítulo &#62;]