include::./index.adoc[]

[[v6-8-0]]
=== Joshua, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-8-1]]

^<<v6-8-1,1>>^ Then Jehovah said to Joshua: “Do not be afraid or be terrified. Take with you all the people of war and get up, go up to Aʹi. See, I have given into your hand the king of Aʹi and his people and his city and his land.

[[v6-8-2]]

^<<v6-8-2,2>>^ And you must do to Aʹi and to its king just as you did to Jerʹi·cho and its king. Only YOU people may plunder its spoil and its domestic animals for yourselves. Set an ambush of yours against the city at its rear.”

[[v6-8-3]]

^<<v6-8-3,3>>^ Accordingly Joshua and all the people of war rose to go up to Aʹi, and Joshua proceeded to choose thirty thousand men, valiant mighty ones, and to send them off by night.

[[v6-8-4]]

^<<v6-8-4,4>>^ And he went on to command them, saying: “See, YOU are lying in ambush against the city to the rear of the city. Do not go very far away from the city, and YOU must all of YOU hold yourselves in readiness.

[[v6-8-5]]

^<<v6-8-5,5>>^ As for me and all the people who are with me, we shall go close to the city. And it must occur that, in case they should come out to meet us just as at the first, we must then flee before them.

[[v6-8-6]]

^<<v6-8-6,6>>^ And they must come out after us until we have drawn them away from the city, for they will say, ‘They are fleeing before us just as at the first.’ And we must flee before them.

[[v6-8-7]]

^<<v6-8-7,7>>^ Then YOU—YOU will rise up from the ambush, and YOU must take possession of the city; and Jehovah YOUR God will certainly give it into YOUR hands.

[[v6-8-8]]

^<<v6-8-8,8>>^ And it must occur that as soon as YOU have seized the city, YOU should set the city on fire. According to Jehovah’s word YOU should do. See, I have commanded YOU.”

[[v6-8-9]]

^<<v6-8-9,9>>^ After that Joshua sent them out and they marched to the place of ambush and took up quarters between Bethʹel and Aʹi to the west of Aʹi, while Joshua kept lodging on that night in the midst of the people.

[[v6-8-10]]

^<<v6-8-10,10>>^ Then Joshua rose up early in the morning and reviewed the people and went up, he and the older men of Israel, before the people to Aʹi.

[[v6-8-11]]

^<<v6-8-11,11>>^ And all the people of war who were with him went up, that they might approach and get in front of the city, and they proceeded to camp to the north of Aʹi, with the valley between them and Aʹi.

[[v6-8-12]]

^<<v6-8-12,12>>^ In the meantime he took about five thousand men and set them as an ambush between Bethʹel and Aʹi, to the west of the city.

[[v6-8-13]]

^<<v6-8-13,13>>^ So the people set the main camp that was to the north of the city and the extreme rear of it that was to the west of the city, and Joshua proceeded to go during that night into the middle of the low plain.^&#42;1^

[NOTE]
====
. Or, “of the valley.”
====

[[v6-8-14]]

^<<v6-8-14,14>>^ And it came about that, as soon as the king of Aʹi saw it, then the men of the city got in a hurry and rose up early and went out to meet Israel in battle, he and all his people, at the appointed time, before the desert plain. As for him, he did not know that there was an ambush against him to the rear of the city.

[[v6-8-15]]

^<<v6-8-15,15>>^ When Joshua and all Israel suffered a blow before them, then they took to flight by the way of the wilderness.

[[v6-8-16]]

^<<v6-8-16,16>>^ At that all the people who were in the city were called out to chase after them, and they went chasing after Joshua and got to be drawn away from the city.

[[v6-8-17]]

^<<v6-8-17,17>>^ And there was not a man remaining in Aʹi and Bethʹel^&#42;1^ that did not go out after Israel, so that they left the city wide open and went chasing after Israel.

[NOTE]
====
. LXX ­omits “and Bethel.”
====

[[v6-8-18]]

^<<v6-8-18,18>>^ Jehovah now said to Joshua: “Stretch out the javelin^&#42;1^ that is in your hand toward Aʹi, for into your hand I shall give it.” Accordingly Joshua stretched out the javelin that was in his hand toward the city.

[NOTE]
====
. Or, “dart.”
====

[[v6-8-19]]

^<<v6-8-19,19>>^ And the ambush rose up quickly from its place, and they began to run at the instant that he stretched out his hand, and they proceeded to enter the city and capture it. Then they hurried and set the city on fire.

[[v6-8-20]]

^<<v6-8-20,20>>^ And the men of Aʹi began to turn back and look, and there the smoke of the city ascended to the heavens, and there proved to be no ability^&#42;1^ in them to flee this way or that. And the people that were fleeing to the wilderness turned upon the pursuers.

[NOTE]
====
. Lit., “two hands.”
====

[[v6-8-21]]

^<<v6-8-21,21>>^ And Joshua and all Israel saw that the ambush had captured the city, and that the smoke of the city ascended, and so they turned around and went striking the men of Aʹi down.

[[v6-8-22]]

^<<v6-8-22,22>>^ And these others came out of the city to meet them, so that they got to be in between Israel, these on this side and those on that, and they went striking them down until there did not remain of them either a survivor or an escapee.

[[v6-8-23]]

^<<v6-8-23,23>>^ And the king of Aʹi they caught alive and proceeded to bring him near to Joshua.

[[v6-8-24]]

^<<v6-8-24,24>>^ And it came about that while Israel was finishing the killing of all the inhabitants of Aʹi in the field, in the wilderness in which they had pursued them, they kept falling, all of them, by the edge of the sword until they came to their end. After that all Israel returned to Aʹi and struck it with the edge of the sword.

[[v6-8-25]]

^<<v6-8-25,25>>^ And all those who fell on that day, from man to woman, amounted to twelve thousand, all the people^&#42;1^ of Aʹi.

[NOTE]
====
. Lit., “men,” M; LXX, “inhabitants.”
====

[[v6-8-26]]

^<<v6-8-26,26>>^ And Joshua did not draw back his hand with which he stretched out the javelin until he had devoted all the inhabitants of Aʹi to destruction.

[[v6-8-27]]

^<<v6-8-27,27>>^ Only the domestic animals and the spoil of that city Israel plundered for themselves, according to Jehovah’s word that he had laid in command upon Joshua.

[[v6-8-28]]

^<<v6-8-28,28>>^ Then Joshua burned Aʹi and reduced it to an indefinitely lasting mound, as a desolation down to this day.

[[v6-8-29]]

^<<v6-8-29,29>>^ And he hanged the king of Aʹi upon a stake until the evening time; and as the sun was about to set Joshua gave the command, and then they took his dead body down from the stake^&#42;1^ and pitched it at the entrance of the gate of the city and raised up a great pile of stones over him, down to this day.

[NOTE]
====
. “The stake.” Lit., “the tree (wood).” Heb., ha·ʽetsʹ; Gr., xyʹlou; Lat., cruʹce.
====

[[v6-8-30]]

^<<v6-8-30,30>>^ It was then that Joshua proceeded to build an altar to Jehovah the God of Israel, in Mount Eʹbal,

[[v6-8-31]]

^<<v6-8-31,31>>^ just as Moses the servant of Jehovah had commanded the sons of Israel, as it is written in the book of the law of Moses: “An altar of whole stones, upon which no iron tool has been wielded”; and they went offering up burnt offerings upon it to Jehovah and sacrificing communion sacrifices.

[[v6-8-32]]

^<<v6-8-32,32>>^ Then he wrote there upon the stones a copy^&#42;1^ of the law of Moses that he had written before the sons of Israel.

[NOTE]
====
. “A copy of.” Heb., mish·nehʹ; Gr., deu·te·ro·noʹmi·on. See De 1:1 ftn, “Words.”
====

[[v6-8-33]]

^<<v6-8-33,33>>^ And all Israel and their older men and the officers and their judges were standing on this side and on that side of the Ark in front of the priests, the Levites, carrying the ark of the covenant of Jehovah, the alien resident as well as the native, one half of them in front of Mount Gerʹi·zim and the other half of them in front of Mount Eʹbal, (just as Moses the servant of Jehovah had commanded,) to bless the people of Israel first of all.

[[v6-8-34]]

^<<v6-8-34,34>>^ And after this he read aloud all the words of the law, the blessing and the malediction, according to all that is written in the book of the law.

[[v6-8-35]]

^<<v6-8-35,35>>^ There proved to be not a word of all that Moses had commanded that Joshua did not read aloud in front of all the congregation^&#42;1^ of Israel, together with the women and the little ones and the alien residents who walked in their midst.

[NOTE]
====
. “The congregation of.” Heb., qehalʹ; Gr., ek·kle·siʹas.
====

'''

xref:006-joshua/006-joshua-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-joshua/006-joshua-009.adoc#v6-9-0[Próximo Capítulo &#62;]