include::./index.adoc[]

[[v6-22-0]]
=== Joshua, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-22-1]]

^<<v6-22-1,1>>^ At that time Joshua proceeded to call the Reuʹben·ites and the Gadʹites and the half tribe of Ma·nasʹseh

[[v6-22-2]]

^<<v6-22-2,2>>^ and to say to them: “For YOUR part, YOU have kept all that Moses the servant of Jehovah commanded YOU, and YOU were obedient to my voice in all that I have commanded YOU.

[[v6-22-3]]

^<<v6-22-3,3>>^ YOU have not left YOUR brothers these many days down to this day, and YOU have kept the obligation of the commandment of Jehovah YOUR God.

[[v6-22-4]]

^<<v6-22-4,4>>^ And now Jehovah YOUR God has given YOUR brothers rest, just as he promised them. So now turn and go YOUR way to YOUR tents in the land of YOUR possession, which Moses the servant of Jehovah gave YOU on the other side of the Jordan.

[[v6-22-5]]

^<<v6-22-5,5>>^ Only be very careful to carry out the commandment and the law that Moses the servant of Jehovah commanded YOU by loving Jehovah YOUR God and by walking in all his ways and by keeping his commandments and by cleaving to him and by serving him with all YOUR heart and with all YOUR soul.”

[[v6-22-6]]

^<<v6-22-6,6>>^ With that Joshua blessed them and sent them away that they might go to their tents.^&#42;1^

[NOTE]
====
. “Homes,” LXX.
====

[[v6-22-7]]

^<<v6-22-7,7>>^ And to the half tribe of Ma·nasʹseh Moses had made a gift in Baʹshan, and to the other half of it Joshua made a gift with their brothers on the side of the Jordan to the west. So, too, when Joshua sent them away to their tents, he proceeded to bless them.

[[v6-22-8]]

^<<v6-22-8,8>>^ And he went on to say to them: “Return to YOUR tents with many riches and with very much livestock, with silver and gold and copper and iron and garments in very great quantity. Take YOUR share of the spoil of YOUR enemies together with YOUR brothers.”

[[v6-22-9]]

^<<v6-22-9,9>>^ After that the sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh returned and went away from the other sons of Israel, from Shiʹloh, which is in the land of Caʹnaan, so as to go to the land of Gilʹe·ad, to the land of their possession in which they had been settled at the order of Jehovah by means of Moses.

[[v6-22-10]]

^<<v6-22-10,10>>^ When they came to the regions of the Jordan that were in the land of Caʹnaan, then the sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh built there an altar by the Jordan, an altar great in conspicuousness.

[[v6-22-11]]

^<<v6-22-11,11>>^ Later on the other sons of Israel heard it said: “Look! The sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh have built an altar on the frontier of the land of Caʹnaan in the regions of the Jordan on the side belonging to the sons of Israel.”

[[v6-22-12]]

^<<v6-22-12,12>>^ When the sons of Israel got to hear of it, the whole assembly of the sons of Israel were then congregated at Shiʹloh to go up for military action against them.

[[v6-22-13]]

^<<v6-22-13,13>>^ Then the sons of Israel sent to the sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh in the land of Gilʹe·ad Phinʹe·has the son of El·e·aʹzar the priest,

[[v6-22-14]]

^<<v6-22-14,14>>^ and ten chieftains with him, one chieftain of each paternal house of all the tribes of Israel, and they were each a head of the house of their fathers of the thousands of Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ In time they came to the sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh in the land of Gilʹe·ad and began to speak with them, saying:

[[v6-22-16]]

^<<v6-22-16,16>>^ “This is what all the assembly of Jehovah have said, ‘What is this act of unfaithfulness that YOU have perpetrated against the God of Israel in turning back today from following Jehovah by YOUR building for yourselves an altar, that YOU may rebel today against Jehovah?

[[v6-22-17]]

^<<v6-22-17,17>>^ Was the error of Peʹor too small for us, from which we have not cleansed ourselves down to this day, although the plague came to be upon the assembly of Jehovah?

[[v6-22-18]]

^<<v6-22-18,18>>^ And YOU—YOU would turn back today from following Jehovah; and it must occur that should YOU, for YOUR part, rebel today against Jehovah, then tomorrow it will be against the entire assembly of Israel that he will be indignant.

[[v6-22-19]]

^<<v6-22-19,19>>^ Now if it is indeed that the land of YOUR possession is unclean, make YOUR way across to the land of Jehovah’s possession where the tabernacle of Jehovah has resided, and get settled in our midst; and against Jehovah do not YOU rebel and do not make us the ones to rebel by YOUR building for yourselves an altar in addition to the altar of Jehovah our God.

[[v6-22-20]]

^<<v6-22-20,20>>^ Was it not Aʹchan the son of Zeʹrah that perpetrated an act of unfaithfulness in the thing devoted to destruction, and was it not against all the assembly of Israel that there came indignation? And he was not the only man to expire in his error.’”

[[v6-22-21]]

^<<v6-22-21,21>>^ At this the sons of Reuʹben and the sons of Gad and the half tribe of Ma·nasʹseh answered and spoke with the heads of the thousands of Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ “Divine One, God, Jehovah, Divine One, God, Jehovah,^&#42;1^ he is knowing, and Israel, he too will know. If it is in rebellion^&#42;2^ and if it is in unfaithfulness against Jehovah, do not save us this day.

[NOTE]
====
. Or, “The God of gods, Jehovah, the God of gods, Jehovah.” Heb., ʼEl ׀ ʼElo·himʹ ׀ Yehwahʹ, ʼEl ׀ ʼElo·himʹ ׀ Yehwahʹ, with the dividing stroke (pa·seqʹ) between the words. This expression ʼEl ʼElo·himʹ Yehwahʹ occurs, unrepeated, in Ps 50:1. Lat., For·tisʹsi·mus Deʹus Doʹmi·nus, For·tisʹsi·mus Deʹus Doʹmi·nus, “The Most Mighty God Jehovah, The Most Mighty God Jehovah.” The first word, ʼEl, of the Heb. expression we have rendered “Divine One.” It may also be rendered “God; Mighty One.”
. “Rebellion,” M. Gr., a·po·sta·siʹai, “apostasy,” from the verb a·phiʹste·mi, “stand away from”; the noun has the sense of “desertion; abandonment; rebellion.” See 2Ch 29:19; Ac 21:21; 2Th 2:3 ftns.
====

[[v6-22-23]]

^<<v6-22-23,23>>^ If^&#42;1^ it was to build for ourselves an altar so as to turn back from following Jehovah, and if it was to offer up burnt offerings and grain offerings on it, and if it was to render up communion sacrifices on it, Jehovah himself will search out;

[NOTE]
====
. “And if,” LXXVg; M omits.
====

[[v6-22-24]]

^<<v6-22-24,24>>^ or if it was not rather out of anxious care for something else that we did this, saying, ‘In a future day YOUR sons will say to our sons: “What do YOU have to do with Jehovah^&#42;1^ the God of Israel?

[NOTE]
====
. Or, “What do you have in common with Jehovah?” Lit., “What [is there] to you and to Jehovah?” A Heb. idiom; a repellent question indicating an objection. See App 7B.
====

[[v6-22-25]]

^<<v6-22-25,25>>^ And there is a boundary that Jehovah has put between us and YOU, the sons of Reuʹben and the sons of Gad, namely, the Jordan. YOU have no share in Jehovah.” And YOUR sons will certainly make our sons desist from fearing Jehovah.’

[[v6-22-26]]

^<<v6-22-26,26>>^ “Hence we said, ‘Let us take action in our behalf, please, by building the altar, not for burnt offering nor for sacrifice,

[[v6-22-27]]

^<<v6-22-27,27>>^ but that it may be a witness between us and YOU and our generations after us that we shall render the service^&#42;1^ of Jehovah before him with our burnt offerings and our sacrifices and our communion sacrifices, that YOUR sons may not say in a future day to our sons: “YOU have no share in Jehovah.”’

[NOTE]
====
. Or, “feature of worship.” Heb., ʽavo·dhathʹ; Gr., la·treiʹan, “sacred service.” Compare Ex 3:12 ftn.
====

[[v6-22-28]]

^<<v6-22-28,28>>^ So we said, ‘And it must occur that in case they should say that to us and to our generations in a future day, we must also say: “See the representation of Jehovah’s altar that our fathers made, not for burnt offering nor for sacrifice, but it is a witness between us and YOU.”’

[[v6-22-29]]

^<<v6-22-29,29>>^ It is unthinkable, on our part, to rebel of our own accord against Jehovah and to turn back today from following Jehovah by building an altar for burnt offering, grain offering and sacrifice besides the altar of Jehovah our God that is before his tabernacle!”

[[v6-22-30]]

^<<v6-22-30,30>>^ Now when Phinʹe·has the priest and the chieftains of the assembly and the heads of the thousands of Israel who were with him heard the words that the sons of Reuʹben and the sons of Gad and the sons of Ma·nasʹseh spoke, it came to be good in their eyes.

[[v6-22-31]]

^<<v6-22-31,31>>^ So Phinʹe·has the son of El·e·aʹzar the priest said to the sons of Reuʹben and the sons of Gad and the sons of Ma·nasʹseh: “Today we do know that Jehovah is in our midst, because YOU have not perpetrated against Jehovah this act of unfaithfulness. Now YOU have delivered the sons of Israel out of the hand of Jehovah.”

[[v6-22-32]]

^<<v6-22-32,32>>^ With that Phinʹe·has the son of El·e·aʹzar the priest and the chieftains returned from the sons of Reuʹben and the sons of Gad in the land of Gilʹe·ad to the land of Caʹnaan to the other sons of Israel and brought back word to them.

[[v6-22-33]]

^<<v6-22-33,33>>^ And the word came to be good in the eyes of the sons of Israel; and the sons of Israel proceeded to bless God, and they did not talk of going up for army service against them to ruin the land in which the sons of Reuʹben and the sons of Gad were dwelling.

[[v6-22-34]]

^<<v6-22-34,34>>^ And the sons of Reuʹben and the sons of Gad began to name the altar,^&#42;1^ because “it is a witness between us that Jehovah is the &#91;true&#93; God.”

[NOTE]
====
. From the explanation given, the altar was likely named Witness. Sy adds, “the altar of witness.”
====

'''

xref:006-joshua/006-joshua-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-joshua/006-joshua-023.adoc#v6-23-0[Próximo Capítulo &#62;]