include::./index.adoc[]

[[v6-7-0]]
=== Joshua, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-7-1]]

^<<v6-7-1,1>>^ And the sons of Israel went committing an act of unfaithfulness respecting the thing devoted to destruction in that Aʹchan^&#42;1^ the son of Carʹmi, the son of Zabʹdi, the son of Zeʹrah, of the tribe of Judah, took some of the thing devoted to destruction. At this Jehovah’s anger grew hot against the sons of Israel.

[NOTE]
====
. “Achan.” Heb., ʽA·khanʹ; in 1Ch 2:7, “Achar,” both meaning “Trouble; Troubler.” See 1Ch 2:7 ftns.
====

[[v6-7-2]]

^<<v6-7-2,2>>^ Then Joshua sent men out from Jerʹi·cho to Aʹi, which is close by Beth-aʹven, to the east of Bethʹel, and said to them: “Go up and spy on the land.” Accordingly the men went up and spied on Aʹi.

[[v6-7-3]]

^<<v6-7-3,3>>^ After that they returned to Joshua and said to him: “Let not all the people go up. Let about two thousand men or about three thousand men go up and strike Aʹi. Do not weary all the people with going there, for they are few.”

[[v6-7-4]]

^<<v6-7-4,4>>^ So about three thousand men of the people went up there, but they took to flight before the men of Aʹi.

[[v6-7-5]]

^<<v6-7-5,5>>^ And the men of Aʹi got to strike down about thirty-six men of them, and they went pursuing them from before the gate as far as Shebʹa·rim^&#42;1^ and continued striking them down on the descent. Consequently the heart of the people began to melt and became as water.

[NOTE]
====
. Meaning “Quarries.”
====

[[v6-7-6]]

^<<v6-7-6,6>>^ At this Joshua ripped his mantles and fell upon his face to the earth before the ark of Jehovah until the evening, he and the older men^&#42;1^ of Israel, and they kept putting dust upon their heads.

[NOTE]
====
. Or, “elders.”
====

[[v6-7-7]]

^<<v6-7-7,7>>^ And Joshua went on to say: “Alas, Sovereign Lord Jehovah, why did you bring this people all the way across the Jordan, just to give us into the hand of the Amʹor·ites for them to destroy us? And if only we had taken it upon ourselves and continued dwelling on the other side of the Jordan!

[[v6-7-8]]

^<<v6-7-8,8>>^ Excuse me, O Jehovah,^&#42;1^ but what can I say after Israel has turned his back before his enemies?

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v6-7-9]]

^<<v6-7-9,9>>^ And the Caʹnaan·ites and all the inhabitants of the land will hear of it, and they will certainly surround us and cut our name off from the earth; and what will you do for your great name?”

[[v6-7-10]]

^<<v6-7-10,10>>^ In turn Jehovah said to Joshua: “Get up, you! Why is it that you are falling upon your face?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel has sinned, and they have also overstepped my covenant that I laid as a command upon them; and they have also taken some of the thing devoted to destruction and have also stolen and also kept it secret and have also put it among their own articles.

[[v6-7-12]]

^<<v6-7-12,12>>^ And the sons of Israel will not be able to rise up against their enemies. The back is what they will turn before their enemies, because they have become a thing devoted to destruction. I shall not prove to be with YOU again unless YOU annihilate the thing devoted to destruction out of YOUR midst.

[[v6-7-13]]

^<<v6-7-13,13>>^ Get up! Sanctify the people, and you must say, ‘Sanctify yourselves tomorrow, for this is what Jehovah the God of Israel has said: “A thing devoted to destruction is in your midst, O Israel. You will not be able to rise up against your enemies until YOU people have removed the thing devoted to destruction from YOUR midst.

[[v6-7-14]]

^<<v6-7-14,14>>^ And YOU must present yourselves in the morning, tribe by tribe, and it must occur that the tribe that Jehovah will pick will come near, family by family, and the family that Jehovah will pick will come near, household by household, and the household that Jehovah will pick will come near, able-bodied man by able-bodied man.

[[v6-7-15]]

^<<v6-7-15,15>>^ And it must occur that the one picked with the thing devoted to destruction will be burned with fire, he and all that belongs to him, because he has overstepped the covenant of Jehovah and because he has committed a disgraceful folly in Israel.”’”

[[v6-7-16]]

^<<v6-7-16,16>>^ Then Joshua rose early in the morning and had Israel come near, tribe by tribe of it, and the tribe of Judah got to be picked.

[[v6-7-17]]

^<<v6-7-17,17>>^ Next he had the families of Judah come near and picked the family of the Zeʹrah·ites, after which he had the family of the Zeʹrah·ites come near, able-bodied man by able-bodied man,^&#42;1^ and Zabʹdi got to be picked.

[NOTE]
====
. Lit., “by the able-bodied men.” Heb., lag·geva·rimʹ; Gr., ka·taʹ anʹdra, used in the distributive sense; SyVgc and six Heb. mss, “household by household.”
====

[[v6-7-18]]

^<<v6-7-18,18>>^ Finally he had his household come near, able-bodied man by able-bodied man, and Aʹchan the son of Carʹmi, the son of Zabʹdi, the son of Zeʹrah, of the tribe of Judah, got to be picked.

[[v6-7-19]]

^<<v6-7-19,19>>^ Then Joshua said to Aʹchan: “My son,^&#42;1^ render, please, glory to Jehovah the God of Israel and make confession to him, and tell me, please, What have you done? Do not hide it from me.”

[NOTE]
====
. “My son,” MVg; LXXSy omit.
====

[[v6-7-20]]

^<<v6-7-20,20>>^ At this Aʹchan answered Joshua and said: “For a fact I—I have sinned against Jehovah the God of Israel, and this way and that way I have done.

[[v6-7-21]]

^<<v6-7-21,21>>^ When I got to see among the spoil an official garment from Shiʹnar, a good-looking one, and two hundred shekels^&#42;1^ of silver and one gold bar, fifty shekels being its weight, then I wanted them, and I took them; and, look! they are hidden in the earth in the midst of my tent with the money^&#42;2^ underneath it.”^&#42;3^

[NOTE]
====
. See App 8A.
. Or, “silver.”
. “It,” fem., that is, the “garment.”
====

[[v6-7-22]]

^<<v6-7-22,22>>^ At once Joshua sent messengers, and they went running to the tent, and, look! it was hidden in his tent with the money underneath it.

[[v6-7-23]]

^<<v6-7-23,23>>^ So they took them from the midst of the tent and brought them to Joshua and all the sons of Israel and poured them out before Jehovah.

[[v6-7-24]]

^<<v6-7-24,24>>^ Joshua, and all Israel with him, now took Aʹchan the son of Zeʹrah and the silver and the official garment and the bar of gold and his sons and his daughters and his bull and his ass and his flock and his tent and everything that was his and they brought them up to the low plain of Aʹchor.

[[v6-7-25]]

^<<v6-7-25,25>>^ Then Joshua said: “Why have you brought ostracism upon us? Jehovah will bring ostracism upon you on this day.” With that all Israel went pelting him with stones, after which they burned them with fire. Thus they stoned them with stones.

[[v6-7-26]]

^<<v6-7-26,26>>^ And they proceeded to raise up over him a big pile of stones, down to this day. At this Jehovah turned away from his hot anger. That is why the name of that place has been called Low Plain of Aʹchor,^&#42;1^ down to this day.

[NOTE]
====
. Meaning “Ostracism; Trouble.”
====

'''

xref:006-joshua/006-joshua-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-joshua/006-joshua-008.adoc#v6-8-0[Próximo Capítulo &#62;]