include::./index.adoc[]

[[v6-10-0]]
=== Joshua, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-10-1]]

^<<v6-10-1,1>>^ And it came about that as soon as A·doʹni-zeʹdek the king of Jerusalem heard that Joshua had captured Aʹi and then devoted it to destruction, that just as he had done to Jerʹi·cho and its king, so he had done to Aʹi and its king, and that the inhabitants of Gibʹe·on had made peace with Israel and were continuing in their midst,

[[v6-10-2]]

^<<v6-10-2,2>>^ he^&#42;1^ became very much afraid, because Gibʹe·on was a great city, like one of the royal cities,^&#42;2^ and because it was greater than Aʹi, and all its men were mighty ones.

[NOTE]
====
. “He,” SyVg; MLXX, “they.”
. Lit., “the cities of the kingdom.”
====

[[v6-10-3]]

^<<v6-10-3,3>>^ Consequently A·doʹni-zeʹdek the king of Jerusalem sent to Hoʹham the king of Heʹbron and to Piʹram the king of Jarʹmuth and to Ja·phiʹa the king of Laʹchish and to Deʹbir the king of Egʹlon, saying,

[[v6-10-4]]

^<<v6-10-4,4>>^ “Come up to me and help me and let us strike Gibʹe·on, because it has made peace with Joshua and the sons of Israel.”

[[v6-10-5]]

^<<v6-10-5,5>>^ At this they gathered together and went on up, five kings of the Amʹor·ites, the king of Jerusalem, the king of Heʹbron, the king of Jarʹmuth, the king of Laʹchish, the king of Egʹlon, these and all their camps, and they proceeded to camp against Gibʹe·on and to war against it.

[[v6-10-6]]

^<<v6-10-6,6>>^ Upon that the men of Gibʹe·on sent to Joshua at the camp at Gilʹgal, saying: “Do not let your hand relax from your slaves. Come up to us quickly and do save us and help us, for all the kings of the Amʹor·ites inhabiting the mountainous region have collected together against us.”

[[v6-10-7]]

^<<v6-10-7,7>>^ So Joshua went on up from Gilʹgal, he and all the people of war with him and all the valiant mighty men.

[[v6-10-8]]

^<<v6-10-8,8>>^ Then Jehovah said to Joshua: “Do not be afraid of them, for into your hand I have given them. Not a man of them will stand against you.”

[[v6-10-9]]

^<<v6-10-9,9>>^ And Joshua proceeded to come against them by surprise. All night long he had gone up from Gilʹgal.

[[v6-10-10]]

^<<v6-10-10,10>>^ And Jehovah went throwing them into confusion before Israel, and they^&#42;1^ began to slay them with a great slaughter at Gibʹe·on and went pursuing them by way of the ascent of Beth-hoʹron and slaying them as far as A·zeʹkah and Mak·keʹdah.

[NOTE]
====
. “They,” TLagardianSy; M, “he,” in the collective sense, referring to “Israel”; Gr., Kyʹri·os, “Jehovah.”
====

[[v6-10-11]]

^<<v6-10-11,11>>^ And it came about that while they were fleeing from before Israel and were on the descent of Beth-hoʹron, Jehovah hurled great stones from the heavens upon them as far as A·zeʹkah, so that they died. There were more who died from the hailstones than those whom the sons of Israel killed with the sword.

[[v6-10-12]]

^<<v6-10-12,12>>^ It was then that Joshua proceeded to speak to Jehovah on the day of Jehovah’s abandoning the Amʹor·ites to the sons of Israel, and he went on to say before the eyes of Israel:
“Sun, be motionless^&#42;1^ over Gibʹe·on,
And, moon, over the low plain of Aiʹja·lon.”

[NOTE]
====
. Or, “keep quiet (silent).”
====

[[v6-10-13]]

^<<v6-10-13,13>>^ Accordingly the sun kept motionless, and the moon did stand still, until the nation could take vengeance on its enemies. Is it not written in the book of Jaʹshar?^&#42;1^ And the sun kept standing still in the middle of the heavens and did not hasten to set for about a whole day.

[NOTE]
====
. Or, “The Upright One.”
====

[[v6-10-14]]

^<<v6-10-14,14>>^ And no day has proved to be like that one, either before it or after it, in that Jehovah listened to the voice of a man, for Jehovah himself was fighting for Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ After that Joshua and all Israel with him returned to the camp at Gilʹgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Meantime these five kings fled and went hiding themselves in the cave at Mak·keʹdah.

[[v6-10-17]]

^<<v6-10-17,17>>^ Then the report was made to Joshua, saying: “The five kings have been found hidden in the cave at Mak·keʹdah.”

[[v6-10-18]]

^<<v6-10-18,18>>^ At that Joshua said: “ROLL great stones up to the mouth of the cave and assign men over it to guard them.

[[v6-10-19]]

^<<v6-10-19,19>>^ As for YOU men, do not stand still. Chase after YOUR enemies, and YOU must strike them in the rear. Do not allow them to enter into their cities, for Jehovah YOUR God has given them into YOUR hands.”

[[v6-10-20]]

^<<v6-10-20,20>>^ And it came about that as soon as Joshua and the sons of Israel had finished slaying them with a very great slaughter, until these came to their end, and those who did survive of them escaped and went entering into the fortified cities,

[[v6-10-21]]

^<<v6-10-21,21>>^ all the people then began to return to the camp, to Joshua, at Mak·keʹdah in peace. Not a man moved his tongue eagerly against the sons of Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Then Joshua said: “OPEN the mouth of the cave and bring out these five kings from the cave to me.”

[[v6-10-23]]

^<<v6-10-23,23>>^ At that they did so and brought out to him from the cave these five kings, the king of Jerusalem, the king of Heʹbron, the king of Jarʹmuth, the king of Laʹchish, the king of Egʹlon.

[[v6-10-24]]

^<<v6-10-24,24>>^ And it came about that as soon as they had brought out these kings to Joshua, Joshua proceeded to call all the men of Israel and to say to the commanders of the men of war that had gone with him: “Come forward. Place YOUR feet on the back of the necks of these kings.” So they came forward and placed their feet on the back of their necks.

[[v6-10-25]]

^<<v6-10-25,25>>^ And Joshua went on to say to them: “Do not be afraid or be terrified. Be courageous and strong, for it is like this that Jehovah will do to all YOUR enemies against whom YOU are warring.”

[[v6-10-26]]

^<<v6-10-26,26>>^ And after that Joshua proceeded to strike them and put them to death and hang them upon five stakes,^&#42;1^ and they continued hanging upon the stakes until the evening.

[NOTE]
====
. Lit., “trees.” Gr., xyʹlon; Lat., stiʹpi·tes, “posts; tree trunks.”
====

[[v6-10-27]]

^<<v6-10-27,27>>^ And it came about that at the time of the setting of the sun Joshua commanded, and they went taking them down off the stakes and throwing them into the cave where they had hid themselves. Then they placed big stones at the mouth of the cave—until this very day.

[[v6-10-28]]

^<<v6-10-28,28>>^ And Joshua captured Mak·keʹdah on that day and went striking it with the edge of the sword. As for its king, he devoted him and every soul^&#42;1^ that was in it to destruction. He let no survivor remain. So he did to the king of Mak·keʹdah just as he had done to the king of Jerʹi·cho.

[NOTE]
====
. “Every soul.” Heb., kol-han·neʹphesh; Gr., pan em·pneʹon, “everything breathing.”
====

[[v6-10-29]]

^<<v6-10-29,29>>^ Then Joshua and all Israel with him passed on from Mak·keʹdah to Libʹnah and warred against Libʹnah.

[[v6-10-30]]

^<<v6-10-30,30>>^ Accordingly Jehovah gave it also and its king into Israel’s hand, and they went striking it and every soul that was in it with the edge of the sword. They did not let a survivor remain in it. So they did to its king just as they had done to the king of Jerʹi·cho.

[[v6-10-31]]

^<<v6-10-31,31>>^ Next Joshua and all Israel with him passed on from Libʹnah to Laʹchish and went camping against it and warring upon it.

[[v6-10-32]]

^<<v6-10-32,32>>^ Accordingly Jehovah gave Laʹchish into Israel’s hand so that they captured it on the second day, and they went striking it and every soul that was in it with the edge of the sword, according to all that they had done to Libʹnah.

[[v6-10-33]]

^<<v6-10-33,33>>^ It was then that Hoʹram the king of Geʹzer went up to help Laʹchish. So Joshua struck him and his people until he had let not a survivor of his remain.

[[v6-10-34]]

^<<v6-10-34,34>>^ Then Joshua and all Israel with him passed on from Laʹchish to Egʹlon and went camping against it and warring against it.

[[v6-10-35]]

^<<v6-10-35,35>>^ And they got to capture it on that day and began to smite it with the edge of the sword, and they devoted every soul that was in it to destruction on that day, according to all that they had done to Laʹchish.

[[v6-10-36]]

^<<v6-10-36,36>>^ Then Joshua and all Israel with him went up from Egʹlon to Heʹbron and began to war against it.

[[v6-10-37]]

^<<v6-10-37,37>>^ And they got to capture it and went striking it and its king and all its towns and every soul that was in it with the edge of the sword. He did not let a survivor remain, according to all that he had done to Egʹlon. So he devoted it and every soul that was in it to destruction.

[[v6-10-38]]

^<<v6-10-38,38>>^ Finally Joshua and all Israel with him came back to Deʹbir and began to war against it.

[[v6-10-39]]

^<<v6-10-39,39>>^ And he got to capture it and its king and all its towns, and they went striking them with the edge of the sword and devoting every soul that was in it to destruction. He did not let a survivor remain. Just as he had done to Heʹbron, so he did to Deʹbir and its king, and just as he had done to Libʹnah and its king.

[[v6-10-40]]

^<<v6-10-40,40>>^ And Joshua proceeded to strike all the land of the mountainous region and the Negʹeb and the She·pheʹlah^&#42;1^ and the slopes and all their kings. He did not let a survivor remain, and everything that breathed^&#42;2^ he devoted to destruction, just as Jehovah the God of Israel had commanded.

[NOTE]
====
. Or, “lowland.”
. Lit., “every breath.” Gr., pan em·pneʹon zo·esʹ, “every breather of life”; Vg, “everything that could breathe.”
====

[[v6-10-41]]

^<<v6-10-41,41>>^ And Joshua went striking them from Kaʹdesh-barʹne·a to Gaʹza and all the land of Goʹshen and up to Gibʹe·on.

[[v6-10-42]]

^<<v6-10-42,42>>^ And Joshua captured all these kings and their land at one time, because it was Jehovah the God of Israel who was fighting for Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ After that Joshua and all Israel with him returned to the camp at Gilʹgal.

'''

xref:006-joshua/006-joshua-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-joshua/006-joshua-011.adoc#v6-11-0[Próximo Capítulo &#62;]