include::./index.adoc[]

[[v6-13-0]]
=== Joshua, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-13-1]]

^<<v6-13-1,1>>^ Now Joshua was old, being advanced in years.^&#42;1^ So Jehovah said to him: “You yourself have grown old and have advanced in years, and to a very great extent the land yet remains to be taken in possession.

[NOTE]
====
. Lit., “days.”
====

[[v6-13-2]]

^<<v6-13-2,2>>^ This is the land yet remaining: all the regions of the Phi·lisʹtines and all the Geshʹur·ites

[[v6-13-3]]

^<<v6-13-3,3>>^ (from the branch of the Nile^&#42;1^ that is in front of Egypt and up to the border of Ekʹron to the north, it used to be reckoned as belonging to the Caʹnaan·ites); five axis lords^&#42;2^ of the Phi·lisʹtines, the Gaʹzites^&#42;3^ and the Ashʹdod·ites, the Ashʹke·lon·ites, the Gitʹtites^&#42;4^ and the Ekʹron·ites; and the Avʹvim.

[NOTE]
====
. Or, “from Shihor.”
. “Axis lords of.” Heb., sar·nehʹ, used only with reference to the Philistines. Taken from the Heb. root word seʹren, “axle; axis,” as in 1Ki 7:30.
. Or, “people of Gaza.”
. Or, “people of Gath.”
====

[[v6-13-4]]

^<<v6-13-4,4>>^ To the south all the land of the Caʹnaan·ites; and Me·arʹah,^&#42;1^ which belongs to the Si·doʹni·ans, as far as Aʹphek, as far as the border of the Amʹor·ites;

[NOTE]
====
. “Maara,” Vg.
====

[[v6-13-5]]

^<<v6-13-5,5>>^ and the land of the Geʹbal·ites^&#42;1^ and all of Lebʹa·non toward the rising of the sun, from Baʹal-gad at the base of Mount Herʹmon as far as to the entering in of Haʹmath;^&#42;2^

[NOTE]
====
. Or, “people of Gebal.” In Eze 27:9 (LXX), they are called Biblians, inhabitants of Byblos, a city that was prominent for making papyrus into paper for writing material. In time bi·bliʹa came to describe various writings, scrolls, books and eventually the collection of little books that make up the Bible.
. Possibly, “as far as Lebi-hamath (Lion of Hamath),” the name of a place. See VT, Vol. II, 1952, p. 114.
====

[[v6-13-6]]

^<<v6-13-6,6>>^ all the inhabitants of the mountainous region, from Lebʹa·non to Misʹre·photh-maʹim, all the Si·doʹni·ans; I myself shall dispossess them from before the sons of Israel. Only make it fall to Israel as an inheritance, just as I have commanded you.

[[v6-13-7]]

^<<v6-13-7,7>>^ And now apportion this land as an inheritance to the nine tribes and the half tribe of Ma·nasʹseh.”

[[v6-13-8]]

^<<v6-13-8,8>>^ With the other half tribe the Reuʹben·ites and the Gadʹites took their inheritance that Moses gave them on the side of the Jordan toward the east, just as Moses the servant of Jehovah had given them,

[[v6-13-9]]

^<<v6-13-9,9>>^ from A·roʹer, which is on the bank of the torrent valley of Arʹnon, and the city that is in the middle of the torrent valley, and all the tableland of Medʹe·ba as far as Diʹbon;

[[v6-13-10]]

^<<v6-13-10,10>>^ and all the cities of Siʹhon the king of the Amʹor·ites, who reigned in Heshʹbon, up to the border of the sons of Amʹmon;

[[v6-13-11]]

^<<v6-13-11,11>>^ and Gilʹe·ad and the territory of the Geshʹur·ites and the Ma·acʹa·thites and all of Mount Herʹmon and all Baʹshan as far as Salʹe·cah;

[[v6-13-12]]

^<<v6-13-12,12>>^ all the royal realm of Og in Baʹshan, who reigned in Ashʹta·roth and in Edʹre·i—he it was who remained of what was left of the Rephʹa·im—and Moses went striking them and dispossessing them.

[[v6-13-13]]

^<<v6-13-13,13>>^ And the sons of Israel did not dispossess the Geshʹur·ites and the Ma·acʹa·thites, but Geshʹur and Maʹa·cath keep dwelling in the midst of Israel down to this day.

[[v6-13-14]]

^<<v6-13-14,14>>^ It was only to the tribe of the Levites that he did not give an inheritance. The offerings made by fire of Jehovah the God of Israel are their inheritance, just as he has promised them.

[[v6-13-15]]

^<<v6-13-15,15>>^ Then Moses made a gift to the tribe of the sons of Reuʹben by their families,

[[v6-13-16]]

^<<v6-13-16,16>>^ and the territory came to be theirs from A·roʹer, which is on the bank of the torrent valley of Arʹnon, and the city that is in the middle of the torrent valley, and all the tableland by Medʹe·ba;

[[v6-13-17]]

^<<v6-13-17,17>>^ Heshʹbon and all its towns that are on the tableland, Diʹbon and Baʹmoth-baʹal and Beth-baʹal-meʹon,

[[v6-13-18]]

^<<v6-13-18,18>>^ and Jaʹhaz and Kedʹe·moth and Mephʹa·ath,

[[v6-13-19]]

^<<v6-13-19,19>>^ and Kir·i·a·thaʹim and Sibʹmah and Zeʹreth-shaʹhar in the mountain of the low plain,

[[v6-13-20]]

^<<v6-13-20,20>>^ and Beth-peʹor and the slopes of Pisʹgah and Beth-jeshʹi·moth,

[[v6-13-21]]

^<<v6-13-21,21>>^ and all the cities of the tableland and all the royal realm of Siʹhon the king of the Amʹor·ites, who reigned in Heshʹbon, and whom Moses struck, together with the chieftains of Midʹi·an, Eʹvi and Reʹkem and Zur and Hur and Reʹba, the dukes of Siʹhon, who were dwelling in the land.

[[v6-13-22]]

^<<v6-13-22,22>>^ And Baʹlaam the son of Beʹor, the diviner, was one whom the sons of Israel killed with the sword along with their slain ones.

[[v6-13-23]]

^<<v6-13-23,23>>^ And the boundary of the sons of Reuʹben came to be the Jordan; and this as a territory was the inheritance of the sons of Reuʹben by their families, with the cities and their settlements.

[[v6-13-24]]

^<<v6-13-24,24>>^ Furthermore, Moses made a gift to the tribe of Gad, the sons of Gad by their families,

[[v6-13-25]]

^<<v6-13-25,25>>^ and their territory came to be Jaʹzer and all the cities of Gilʹe·ad and half of the land of the sons of Amʹmon as far as A·roʹer, which is in front of Rabʹbah;

[[v6-13-26]]

^<<v6-13-26,26>>^ and from Heshʹbon to Raʹmath-mizʹpeh and Betʹo·nim and from Ma·ha·naʹim to the border of Deʹbir;

[[v6-13-27]]

^<<v6-13-27,27>>^ and in the low plain Beth-haʹram and Beth-nimʹrah and Sucʹcoth and Zaʹphon, the rest of the royal realm of Siʹhon the king of Heshʹbon, the Jordan being the border as far as the extremity of the sea of Chinʹne·reth^&#42;1^ on the side of Jordan toward the east.

[NOTE]
====
. “Chinneroth” in M in 11:2; 12:3.
====

[[v6-13-28]]

^<<v6-13-28,28>>^ This was the inheritance of the sons of Gad by their families, with the cities and their settlements.

[[v6-13-29]]

^<<v6-13-29,29>>^ Further, Moses made a gift to the half tribe^&#42;1^ of Ma·nasʹseh, and it came to be that of the half tribe^&#42;2^ of the sons of Ma·nasʹseh by their families.

[NOTE]
====
. “To the half tribe of.” Heb., la·chatsiʹ sheʹvet (tribe).
. “Of the half tribe of.” Heb., la·chatsiʹ mat·tehʹ (“tribe,” used interchangeably with sheʹvet).
====

[[v6-13-30]]

^<<v6-13-30,30>>^ And their territory came to be from Ma·ha·naʹim all of Baʹshan, all the royal realm of Og the king of Baʹshan, and all the tent villages of Jaʹir that are in Baʹshan, sixty towns.

[[v6-13-31]]

^<<v6-13-31,31>>^ And half of Gilʹe·ad, and Ashʹta·roth and Edʹre·i, the cities of the royal realm of Og in Baʹshan, went to the sons of Maʹchir the son of Ma·nasʹseh, to half of the sons of Maʹchir by their families.

[[v6-13-32]]

^<<v6-13-32,32>>^ These were what Moses caused &#91;them&#93; to inherit, on the desert plains of Moʹab on the side of the Jordan, at Jerʹi·cho, toward the east.

[[v6-13-33]]

^<<v6-13-33,33>>^ And to the tribe of the Levites Moses did not give an inheritance. Jehovah the God of Israel is their inheritance, just as he has promised them.

'''

xref:006-joshua/006-joshua-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-joshua/006-joshua-014.adoc#v6-14-0[Próximo Capítulo &#62;]