include::./index.adoc[]

[[v6-14-0]]
=== Joshua, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-14-1]]

^<<v6-14-1,1>>^ Now this is what the sons of Israel took as a hereditary possession in the land of Caʹnaan, which El·e·aʹzar the priest and Joshua the son of Nun and the heads of the fathers of the tribes of the sons of Israel caused them to inherit.

[[v6-14-2]]

^<<v6-14-2,2>>^ Their inheritance was by lot, just as Jehovah had commanded by means of Moses for the nine tribes and the half tribe.

[[v6-14-3]]

^<<v6-14-3,3>>^ For Moses had given the inheritance of the two other tribes and the other half tribe on the other side of the Jordan; and to the Levites he did not give an inheritance in their midst.

[[v6-14-4]]

^<<v6-14-4,4>>^ For the sons of Joseph had become two tribes, Ma·nasʹseh and Eʹphra·im; and they had not given a share in the land to the Levites, except cities to dwell in and their pasture grounds for their livestock and their property.

[[v6-14-5]]

^<<v6-14-5,5>>^ Just as Jehovah had commanded Moses, so the sons of Israel did; and they proceeded to apportion the land.

[[v6-14-6]]

^<<v6-14-6,6>>^ Then the sons of Judah approached Joshua in Gilʹgal, and Caʹleb the son of Je·phunʹneh the Kenʹiz·zite said to him: “You yourself well know the word that Jehovah spoke to Moses the man of the &#91;true&#93; God^&#42;1^ with regard to me and with regard to you at Kaʹdesh-barʹne·a.

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElo·himʹ. See App 1F.
====

[[v6-14-7]]

^<<v6-14-7,7>>^ Forty years old I was when Moses the servant of Jehovah sent me out of Kaʹdesh-barʹne·a to spy out the land, and I came bringing him back word just as it was in my heart.

[[v6-14-8]]

^<<v6-14-8,8>>^ And my brothers who went up with me caused the heart of the people to melt; but as for me, I followed Jehovah my God fully.

[[v6-14-9]]

^<<v6-14-9,9>>^ Consequently Moses swore on that day, saying, ‘The land upon which your foot has trod will become yours and your sons’ as an inheritance to time indefinite, because you have followed Jehovah my God fully.’

[[v6-14-10]]

^<<v6-14-10,10>>^ And now here Jehovah has preserved me alive, just as he promised, these forty-five years since Jehovah made this promise to Moses when Israel walked in the wilderness, and now here I am today eighty-five years old.

[[v6-14-11]]

^<<v6-14-11,11>>^ Yet I am today as strong as on the day of Moses’ sending me out. As my power was then, so my power is now for the war, both to go out and to come in.

[[v6-14-12]]

^<<v6-14-12,12>>^ And now do give me this mountainous region that Jehovah promised on that day, for you yourself heard on that day that there were Anʹa·kim there and great fortified cities. Likely Jehovah will be with me, and I shall certainly dispossess them, just as Jehovah promised.”

[[v6-14-13]]

^<<v6-14-13,13>>^ At that Joshua blessed him and gave Heʹbron to Caʹleb the son of Je·phunʹneh as an inheritance.

[[v6-14-14]]

^<<v6-14-14,14>>^ That is why Heʹbron has come to belong to Caʹleb the son of Je·phunʹneh the Kenʹiz·zite as an inheritance down to this day, for the reason that he followed Jehovah the God of Israel fully.

[[v6-14-15]]

^<<v6-14-15,15>>^ The name of Heʹbron before that was Kirʹi·ath-arʹba (&#91;said Arʹba was&#93; the great man among the Anʹa·kim).^&#42;1^ And the land had no disturbance from war.

[NOTE]
====
. “Was the city of Arbok [LXXB, “Argob”], this being the metropolis of the Anakim,” LXX.
====

'''

xref:006-joshua/006-joshua-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-joshua/006-joshua-015.adoc#v6-15-0[Próximo Capítulo &#62;]