include::./index.adoc[]

[[v6-1-0]]
=== Joshua, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v6-1-1]]

^<<v6-1-1,1>>^ And it came about after the death of Moses the servant^&#42;1^ of Jehovah that Jehovah proceeded to say to Joshua^&#42;2^ the son of Nun, the minister^&#42;3^ of Moses:

[NOTE]
====
. Or, “slave.”
. “Joshua.” Heb., Yehoh·shuʹaʽ, “Jehoshua,” meaning “Jehovah Is Salvation”; Gr., Ἰησοῖ (I·e·soiʹ, “Jesus”); Sy, “Jeshua”; Vgc, “Josue.” See Ge 49:18 ftn, “You”; Heb 4:8 ftn, “Joshua.”
. Or, “attendant.” Heb., mesha·rethʹ; Lat., mi·niʹstrum.
====

[[v6-1-2]]

^<<v6-1-2,2>>^ “Moses my servant is dead; and now get up, cross this Jordan, you and all this people, into the land that I am giving to them, to the sons of Israel.

[[v6-1-3]]

^<<v6-1-3,3>>^ Every place upon which the sole of YOUR foot will tread, to YOU people I shall certainly give it, just as I promised to Moses.

[[v6-1-4]]

^<<v6-1-4,4>>^ From the wilderness and^&#42;1^ this Lebʹa·non to the great river, the river Eu·phraʹtes, that is, all the land of the Hitʹtites, and to the Great Sea toward the setting of the sun YOUR territory will prove to be.

[NOTE]
====
. Possibly, “up to.”
====

[[v6-1-5]]

^<<v6-1-5,5>>^ Nobody will take a firm stand before you all the days of your life. Just as I proved to be with Moses I shall prove to be with you. I shall neither desert you nor leave you entirely.

[[v6-1-6]]

^<<v6-1-6,6>>^ Be courageous and strong, for you are the one who will cause this people to inherit the land that I swore to their forefathers to give to them.

[[v6-1-7]]

^<<v6-1-7,7>>^ “Only be courageous and very strong to take care to do according to all the law that Moses my servant commanded you. Do not turn aside from it to the right or to the left, in order that you may act wisely everywhere you go.

[[v6-1-8]]

^<<v6-1-8,8>>^ This book of the law should not depart from your mouth, and you must in an undertone read in it day and night, in order that you may take care to do according to all that is written in it; for then you will make your way successful and then you will act wisely.

[[v6-1-9]]

^<<v6-1-9,9>>^ Have I not commanded you? Be courageous and strong. Do not suffer shock or be terrified, for Jehovah your God is with you wherever you go.”

[[v6-1-10]]

^<<v6-1-10,10>>^ And Joshua proceeded to command the officers of the people, saying:

[[v6-1-11]]

^<<v6-1-11,11>>^ “Pass through the midst of the camp and command the people, saying, ‘Get provisions ready for yourselves, because three days from now YOU are crossing this Jordan to go in and take possession of the land that Jehovah YOUR God is giving YOU to take possession of it.’”

[[v6-1-12]]

^<<v6-1-12,12>>^ And to the Reuʹben·ites and the Gadʹites and the half tribe of Ma·nasʹseh Joshua said:

[[v6-1-13]]

^<<v6-1-13,13>>^ “Let there be a remembering^&#42;1^ of the word that Moses the servant of Jehovah commanded YOU, saying, ‘Jehovah YOUR God is giving YOU rest and has given YOU this land.

[NOTE]
====
. “Let there be a remembering.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v6-1-14]]

^<<v6-1-14,14>>^ YOUR wives, YOUR little ones and YOUR livestock will dwell in the land that Moses has given YOU on this side of the Jordan; but YOU men will pass over in battle formation before YOUR brothers, all the valiant mighty men, and YOU must help them.

[[v6-1-15]]

^<<v6-1-15,15>>^ First when Jehovah gives rest to YOUR brothers the same as to YOU and they also have taken possession of the land that Jehovah YOUR God is giving them, YOU must also return to the land of YOUR holding and take possession of it, the one that Moses the servant of Jehovah has given YOU on the side of the Jordan toward the rising of the sun.’”

[[v6-1-16]]

^<<v6-1-16,16>>^ Accordingly they answered Joshua, saying: “All that you have commanded us we shall do, and wherever you may send us we shall go.

[[v6-1-17]]

^<<v6-1-17,17>>^ As we listened to Moses in everything, so we shall listen to you. Only may Jehovah your God prove to be with you just as he proved to be with Moses.

[[v6-1-18]]

^<<v6-1-18,18>>^ Any man that behaves rebelliously against your order and does not listen to your words in all that you may command him will be put to death. Only be courageous and strong.”

'''

xref:005-deuteronomy/005-deuteronomy-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-joshua/006-joshua-002.adoc#v6-2-0[Próximo Capítulo &#62;]