include::./index.adoc[]

[[v19-37-0]]
=== Psalms, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_Of David._

_א &#91;ʼAʹleph&#93;^&#42;1^_

[[v19-37-1]]

^<<v19-37-1,1>>^ Do not show yourself heated up because of the evildoers.
Do not be envious of those doing unrighteousness.

[[v19-37-2]]

^<<v19-37-2,2>>^ For like grass they will speedily wither,
And like green new grass they will fade away.

_ב &#91;Behth&#93;_

[[v19-37-3]]

^<<v19-37-3,3>>^ Trust in Jehovah and do good;
Reside in the earth, and deal with faithfulness.

[[v19-37-4]]

^<<v19-37-4,4>>^ Also take exquisite delight in Jehovah,
And he will give you the requests of your heart.

_ג &#91;Giʹmel&#93;_

[[v19-37-5]]

^<<v19-37-5,5>>^ Roll upon Jehovah your way,
And rely upon him, and he himself will act.

[[v19-37-6]]

^<<v19-37-6,6>>^ And he will certainly bring forth your righteousness as the light itself,
And your justice as the midday.

_ד &#91;Daʹleth&#93;_

[[v19-37-7]]

^<<v19-37-7,7>>^ Keep silent before Jehovah
And wait longingly for him.
Do not show yourself heated up at anyone making his way successful,
At the man carrying out &#91;his&#93; ideas.

_ה &#91;Heʼ&#93;_

[[v19-37-8]]

^<<v19-37-8,8>>^ Let anger alone and leave rage;
Do not show yourself heated up only to do evil.

[[v19-37-9]]

^<<v19-37-9,9>>^ For evildoers themselves will be cut off,
But those hoping in Jehovah are the ones that will possess the earth.

_ו &#91;Waw&#93;_

[[v19-37-10]]

^<<v19-37-10,10>>^ And just a little while longer, and the wicked one will be no more;
And you will certainly give attention to his place, and he will not be.

[[v19-37-11]]

^<<v19-37-11,11>>^ But the meek ones themselves will possess the earth,
And they will indeed find their exquisite delight in the abundance of peace.

_ז &#91;Zaʹyin&#93;_

[[v19-37-12]]

^<<v19-37-12,12>>^ The wicked one is plotting against the righteous one,
And at him he is grinding his teeth.

[[v19-37-13]]

^<<v19-37-13,13>>^ Jehovah^&#42;1^ himself will laugh at him,
For he certainly sees that his day will come.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

_ח &#91;Chehth&#93;_

[[v19-37-14]]

^<<v19-37-14,14>>^ The wicked ones have drawn a sword itself and have bent their bow,
To cause the afflicted and poor one to fall,
To slaughter those who are upright in &#91;their&#93; way.

[[v19-37-15]]

^<<v19-37-15,15>>^ Their own sword will enter into their heart,
And their own bows will be broken.

_ט &#91;Tehth&#93;_

[[v19-37-16]]

^<<v19-37-16,16>>^ Better is the little of the righteous one
Than the abundance of the many wicked ones.

[[v19-37-17]]

^<<v19-37-17,17>>^ For the very arms of the wicked ones will be broken,
But Jehovah will be supporting the righteous ones.

_י &#91;Yohdh&#93;_

[[v19-37-18]]

^<<v19-37-18,18>>^ Jehovah is aware of the days of the faultless ones,
And their very inheritance will continue even to time indefinite.

[[v19-37-19]]

^<<v19-37-19,19>>^ They will not be ashamed in the time of calamity,
And in the days of famine they will be satisfied.

_כ &#91;Kaph&#93;_

[[v19-37-20]]

^<<v19-37-20,20>>^ For the wicked themselves will perish,
And the enemies of Jehovah will be like the preciousness of pastures;
They must come to their end. In smoke they must come to their end.

_ל &#91;Laʹmedh&#93;_

[[v19-37-21]]

^<<v19-37-21,21>>^ The wicked one is borrowing and does not pay back,
But the righteous one is showing favor and is making gifts.

[[v19-37-22]]

^<<v19-37-22,22>>^ For those being blessed by him will themselves possess the earth,
But those upon whom evil is called by him will be cut off.

_מ &#91;Mem&#93;_

[[v19-37-23]]

^<<v19-37-23,23>>^ By Jehovah the very steps of an able-bodied man have been made ready,
And in his way He takes delight.

[[v19-37-24]]

^<<v19-37-24,24>>^ Although he may fall, he will not be hurled down,
For Jehovah is supporting his hand.

_נ &#91;Nun&#93;_

[[v19-37-25]]

^<<v19-37-25,25>>^ A young man I used to be, I have also grown old,
And yet I have not seen anyone righteous left entirely,
Nor his offspring^&#42;1^ looking for bread.

[NOTE]
====
. Or, “seed.”
====

[[v19-37-26]]

^<<v19-37-26,26>>^ All day long he is showing favor and lending,
And so his offspring are in line for a blessing.

_ס &#91;Saʹmekh&#93;_

[[v19-37-27]]

^<<v19-37-27,27>>^ Turn away from what is bad and do what is good,
And so reside to time indefinite.

[[v19-37-28]]

^<<v19-37-28,28>>^ For Jehovah is a lover of justice,
And he will not leave his loyal ones.

[NOTE]
====
. By dropping the preposition “to” (ל), this line begins with the acrostic Heb. letter ʽAʹyin.
====

_ע &#91;ʽAʹyin&#93;_

To^&#42;1^ time indefinite they will certainly be guarded;
But as for the offspring of the wicked ones, they will indeed be cut off.

[NOTE]
====
. By dropping the preposition “to” (ל), this line begins with the acrostic Heb. letter ʽAʹyin.
====

[[v19-37-29]]

^<<v19-37-29,29>>^ The righteous themselves will possess the earth,
And they will reside forever upon it.

_פ &#91;Peʼ&#93;_

[[v19-37-30]]

^<<v19-37-30,30>>^ The mouth of the righteous is the one that utters wisdom in an undertone,
And his is the tongue that speaks justly.

[[v19-37-31]]

^<<v19-37-31,31>>^ The law of his God is in his heart;
His steps will not wobble.

_צ &#91;Tsa·dhehʹ&#93;_

[[v19-37-32]]

^<<v19-37-32,32>>^ The wicked one is keeping on the watch for the righteous
And is seeking to put him to death.

[[v19-37-33]]

^<<v19-37-33,33>>^ As for Jehovah, he will not leave him to the hand of that one,
And he will not pronounce him wicked when he is being judged.

_ק &#91;Qohph&#93;_

[[v19-37-34]]

^<<v19-37-34,34>>^ Hope in Jehovah and keep his way,
And he will exalt you to take possession of the earth.
When the wicked ones are cut off, you will see &#91;it&#93;.

_ר &#91;Rehsh&#93;_

[[v19-37-35]]

^<<v19-37-35,35>>^ I have seen the wicked a tyrant
And spreading himself^&#42;1^ as a luxuriant &#91;tree&#93; in native soil.

[NOTE]
====
. Lit., “pouring himself out.”
====

[[v19-37-36]]

^<<v19-37-36,36>>^ And yet he proceeded to pass away,^&#42;1^ and there he was not;
And I kept seeking him, and he was not found.

[NOTE]
====
. According to M; LXXSyVg, “I passed by.”
====

_ש &#91;Shin&#93;_

[[v19-37-37]]

^<<v19-37-37,37>>^ Watch the blameless one and keep the upright one in sight,
For the future of &#91;that&#93; man will be peaceful.

[[v19-37-38]]

^<<v19-37-38,38>>^ But the transgressors themselves will certainly be annihilated together;
The future of wicked people will indeed be cut off.

_ת &#91;Taw&#93;_

[[v19-37-39]]

^<<v19-37-39,39>>^ And^&#42;1^ the salvation of the righteous ones is from Jehovah;
He is their fortress in the time of distress.

[NOTE]
====
. By dropping the conjunction “and” (ו), this line begins with an acrostic Taw, the last letter of the Heb. alphabet.
====

[[v19-37-40]]

^<<v19-37-40,40>>^ And Jehovah will help them and provide them with escape.
He will provide them with escape from wicked people and save them,
Because they have taken refuge in him.

'''

xref:019-psalm/019-psalm-036.adoc#v19-36-0[&#60; Capítulo Anterior] | <<v19-37-0,Topo>> | xref:019-psalm/019-psalm-038.adoc#v19-38-0[Próximo Capítulo &#62;]