include::./index.adoc[]

[[v19-44-0]]
=== Psalms, 44
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. Of the sons of Koʹrah. Masʹkil.^&#42;1^_

[[v19-44-1]]

^<<v19-44-1,1>>^ O God, with our ears we have heard,
Our forefathers themselves have recounted to us
The activity that you performed in their days,
In the days of long ago.

[[v19-44-2]]

^<<v19-44-2,2>>^ You yourself by your hand drove away even nations,
And you proceeded to plant them &#91;instead&#93;.
You went breaking national groups and sending them away.

[[v19-44-3]]

^<<v19-44-3,3>>^ For it was not by their own sword that they took possession of the land,
And their own arm was not what brought them salvation.
For it was your right hand and your arm and the light of your face,
Because you took pleasure in them.

[[v19-44-4]]

^<<v19-44-4,4>>^ You yourself are my King, O God.
Command grand salvation^&#42;1^ for Jacob.

[NOTE]
====
. See 42:5 ftn, “Salvation.”
====

[[v19-44-5]]

^<<v19-44-5,5>>^ By you we shall push our adversaries themselves;
In your name we shall tread down those rising up against us.

[[v19-44-6]]

^<<v19-44-6,6>>^ For it was not in my bow that I kept trusting
And it was not my sword that was saving me.

[[v19-44-7]]

^<<v19-44-7,7>>^ For you saved us from our adversaries,
And those intensely hating us you put to shame.

[[v19-44-8]]

^<<v19-44-8,8>>^ In God we will offer praise all day long,
And to time indefinite your name we shall laud. Seʹlah.

[[v19-44-9]]

^<<v19-44-9,9>>^ But now you have cast off and keep humiliating us,
And you do not go forth with our armies.

[[v19-44-10]]

^<<v19-44-10,10>>^ You keep making us turn back from the adversary,
And the very ones intensely hating us have pillaged for themselves.

[[v19-44-11]]

^<<v19-44-11,11>>^ You give us up like sheep, as something to eat,
And among the nations you have scattered us.

[[v19-44-12]]

^<<v19-44-12,12>>^ You sell your people for no value at all,
And you have made no wealth by the price for them.

[[v19-44-13]]

^<<v19-44-13,13>>^ You set us as a reproach to our neighbors,
A derision and jeering to those all around us.

[[v19-44-14]]

^<<v19-44-14,14>>^ You set us as a proverbial saying among the nations,
A shaking of the head among the national groups.

[[v19-44-15]]

^<<v19-44-15,15>>^ All day long my humiliation is in front of me,
And the shame of my own face has covered me,

[[v19-44-16]]

^<<v19-44-16,16>>^ Due to the voice of the one reproaching and speaking abusively,
Because of the enemy and the one taking his revenge.

[[v19-44-17]]

^<<v19-44-17,17>>^ All this is what has come upon us, and we have not forgotten you,
And we have not acted falsely in your covenant.

[[v19-44-18]]

^<<v19-44-18,18>>^ Our heart has not turned faithlessly back,
Nor do our footsteps deviate from your path.

[[v19-44-19]]

^<<v19-44-19,19>>^ For you have crushed us in the place of jackals,
And you cover us over with deep shadow.

[[v19-44-20]]

^<<v19-44-20,20>>^ If we have forgotten the name of our God,^&#42;1^
Or we spread out our palms to a strange god,^&#42;2^

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu.
. “To . . . god.” Heb., leʼelʹ.
====

[[v19-44-21]]

^<<v19-44-21,21>>^ Will not God himself search this out?
For he is aware of the secrets of the heart.

[[v19-44-22]]

^<<v19-44-22,22>>^ But for your sake we have been killed all day long;
We have been accounted as sheep for slaughtering.

[[v19-44-23]]

^<<v19-44-23,23>>^ Do arouse yourself. Why do you keep sleeping, O Jehovah?^&#42;1^
Do awake. Do not keep casting off forever.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-44-24]]

^<<v19-44-24,24>>^ Why do you keep your very face concealed?
Why do you forget our affliction and our oppression?

[[v19-44-25]]

^<<v19-44-25,25>>^ For our soul has bowed down^&#42;1^ to the dust itself;
Our belly has clung to the very earth.

[NOTE]
====
. “Has melted (vanished) away,” by another derivation of the Heb. verb.
====

[[v19-44-26]]

^<<v19-44-26,26>>^ Do arise in assistance to us
And redeem us for the sake of your loving-kindness.

'''

xref:019-psalm/019-psalm-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-psalm/019-psalm-045.adoc#v19-45-0[Próximo Capítulo &#62;]