include::./index.adoc[]

[[v19-43-0]]
=== Psalms, 43
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-43-1]]

^<<v19-43-1,1>>^ Judge me, O God,
And do conduct my legal case against a nation not loyal.^&#42;1^
From the man of deception and unrighteousness may you provide me with escape.

[NOTE]
====
. Or, “without loving-kindness.”
====

[[v19-43-2]]

^<<v19-43-2,2>>^ For you are the God of my fortress.
Why have you cast me off?
Why do I walk about sad because of the oppression by the enemy?

[[v19-43-3]]

^<<v19-43-3,3>>^ Send out your light and your truth.
May these themselves lead me.^&#42;1^
May they bring me to your holy mountain and to your grand tabernacle.

[NOTE]
====
. “Comfort me,” Sy and three Heb. mss.
====

[[v19-43-4]]

^<<v19-43-4,4>>^ And I will come to the altar of God,
To God,^&#42;1^ my exultant rejoicing.
And I will laud you on the harp, O God, my God.^&#42;2^

[NOTE]
====
. “God.” Heb., ʼEl.
. “O God, my God,” M(Heb., ʼElo·himʹ ʼElo·haiʹ)LXXASyVg; TLXXB, “O Jehovah my God.”
====

[[v19-43-5]]

^<<v19-43-5,5>>^ Why are you in despair, O my soul,
And why are you boisterous within me?
Wait for God,
For I shall yet laud him as the grand salvation of my person and as my God.

'''

xref:019-psalm/019-psalm-042.adoc#v19-42-0[&#60; Capítulo Anterior] | <<v19-43-0,Topo>> | xref:019-psalm/019-psalm-044.adoc#v19-44-0[Próximo Capítulo &#62;]