include::./index.adoc[]

[[v19-38-0]]
=== Psalms, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A melody of David, to bring to remembrance._

[[v19-38-1]]

^<<v19-38-1,1>>^ O Jehovah, do not in your indignation reprove me,
Nor in your rage correct me.

[[v19-38-2]]

^<<v19-38-2,2>>^ For your own arrows have sunk themselves deep into me,
And upon me your hand is come down.

[[v19-38-3]]

^<<v19-38-3,3>>^ There is no sound spot in my flesh because of your denunciation.
There is no peace in my bones on account of my sin.

[[v19-38-4]]

^<<v19-38-4,4>>^ For my own errors have passed over my head;
Like a heavy load they are too heavy for me.

[[v19-38-5]]

^<<v19-38-5,5>>^ My wounds have become stinky, they have festered,
Because of my foolishness.

[[v19-38-6]]

^<<v19-38-6,6>>^ I have become disconcerted, I have bowed low to an extreme degree;
All day long I have walked about sad.

[[v19-38-7]]

^<<v19-38-7,7>>^ For my very loins have become full of burning,
And there is no sound spot in my flesh.

[[v19-38-8]]

^<<v19-38-8,8>>^ I have grown numb and become crushed to an extreme degree;
I have roared due to the groaning of my heart.

[[v19-38-9]]

^<<v19-38-9,9>>^ O Jehovah,^&#42;1^ in front of you is all my desire,
And from you my sighing itself has not been concealed.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-38-10]]

^<<v19-38-10,10>>^ My own heart has palpitated heavily, my power has left me,
And the light of my own eyes also is not with me.

[[v19-38-11]]

^<<v19-38-11,11>>^ As for my lovers^&#42;1^ and my companions, they keep standing away from my plague,
And my close acquaintances themselves have stood off at a distance.

[NOTE]
====
. Or, “friends.”
====

[[v19-38-12]]

^<<v19-38-12,12>>^ But those seeking my soul lay out traps,
And those working for a calamity to me have spoken of adversities,
And deceptions they keep muttering all day long.

[[v19-38-13]]

^<<v19-38-13,13>>^ As for me, like someone deaf, I would not listen;
And like someone speechless, I would not open my mouth.

[[v19-38-14]]

^<<v19-38-14,14>>^ And I came to be like a man that was not hearing,
And in my mouth there were no counterarguments.

[[v19-38-15]]

^<<v19-38-15,15>>^ For on you, O Jehovah, I waited;
You yourself proceeded to answer, O Jehovah^&#42;1^ my God.

[NOTE]
====
. See vs 9 ftn.
====

[[v19-38-16]]

^<<v19-38-16,16>>^ For I said: “Otherwise they would rejoice at me;
When my foot moved unsteadily, they would certainly assume great airs against me.”

[[v19-38-17]]

^<<v19-38-17,17>>^ For I was ready to limp,
And my pain was in front of me constantly.

[[v19-38-18]]

^<<v19-38-18,18>>^ For I proceeded to tell about my own error;
I began to be anxious over my sin.

[[v19-38-19]]

^<<v19-38-19,19>>^ And my enemies who are alive became mighty,
And those hating me for no reason became many.

[[v19-38-20]]

^<<v19-38-20,20>>^ And they were rewarding me with bad for good;
They kept resisting me^&#42;1^ in return for my pursuing what is good.

[NOTE]
====
. Or, “they were adversaries (satans) to me.” Heb., yis·tenuʹni.
====

[[v19-38-21]]

^<<v19-38-21,21>>^ Do not leave me, O Jehovah.
O my God, do not keep far away from me.

[[v19-38-22]]

^<<v19-38-22,22>>^ Do make haste to my assistance,
O Jehovah^&#42;1^ my salvation.

[NOTE]
====
. See vs 9 ftn.
====

'''

xref:019-psalm/019-psalm-037.adoc#v19-37-0[&#60; Capítulo Anterior] | <<v19-38-0,Topo>> | xref:019-psalm/019-psalm-039.adoc#v19-39-0[Próximo Capítulo &#62;]