include::./index.adoc[]

[[v19-12-0]]
=== Psalms, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director on the lower octave.^&#42;1^ A melody of David._

[[v19-12-1]]

^<<v19-12-1,1>>^ Do save &#91;me&#93;,^&#42;1^ O Jehovah, for the loyal one has come to an end;
For faithful people have vanished from the sons of men.

[NOTE]
====
. “Me,” LXXVg; MSy omit.
====

[[v19-12-2]]

^<<v19-12-2,2>>^ Untruth they keep speaking one to the other;
With a smooth lip they keep speaking even with a double heart.^&#42;1^

[NOTE]
====
. Lit., “with a heart and a heart.”
====

[[v19-12-3]]

^<<v19-12-3,3>>^ Jehovah will cut off all smooth lips,
The tongue speaking great things,

[[v19-12-4]]

^<<v19-12-4,4>>^ Those who have said: “With our tongue we shall prevail.
Our lips are with us. Who will be a master to us?”

[[v19-12-5]]

^<<v19-12-5,5>>^ “Because of the despoiling of the afflicted ones, because of the sighing of the poor ones,
I shall at this time arise,” says Jehovah.
“I shall put &#91;him&#93; in safety from anyone that puffs at him.”

[[v19-12-6]]

^<<v19-12-6,6>>^ The sayings of Jehovah are pure sayings,
As silver refined in a smelting furnace^&#42;1^ of earth, clarified seven times.

[NOTE]
====
. “A smelting furnace,” T. Possibly, “an entrance.” The meaning is uncertain.
====

[[v19-12-7]]

^<<v19-12-7,7>>^ You yourself, O Jehovah, will guard them;
You will preserve each one from this generation to time indefinite.

[[v19-12-8]]

^<<v19-12-8,8>>^ The wicked ones walk all around,
Because vileness is exalted among the sons of men.

'''

xref:019-psalm/019-psalm-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-psalm/019-psalm-013.adoc#v19-13-0[Próximo Capítulo &#62;]