include::./index.adoc[]

[[v19-102-0]]
=== Psalms, 102
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A prayer of the afflicted in case he grows feeble and pours out his concern before Jehovah himself._

[[v19-102-1]]

^<<v19-102-1,1>>^ O Jehovah, do hear my prayer;
And to you may my own cry for help come.

[[v19-102-2]]

^<<v19-102-2,2>>^ Do not conceal your face from me on the day that I am in sore straits.
Incline to me your ear;
On the day that I call, hurry, answer me.

[[v19-102-3]]

^<<v19-102-3,3>>^ For my days have come to an end just like smoke,
And my very bones have been made red-hot just like a fireplace.

[[v19-102-4]]

^<<v19-102-4,4>>^ My heart has been struck just like vegetation and is dried up,
For I have forgotten to eat my food.^&#42;1^

[NOTE]
====
. Lit., “bread.”
====

[[v19-102-5]]

^<<v19-102-5,5>>^ Because of the sound of my sighing
My bones have stuck to my flesh.

[[v19-102-6]]

^<<v19-102-6,6>>^ I do resemble the pelican of the wilderness.
I have become like a little owl of desolated places.

[[v19-102-7]]

^<<v19-102-7,7>>^ I have grown emaciated,^&#42;1^
And I am become like a bird isolated upon a roof.

[NOTE]
====
. Possibly, “I have kept awake,” by another derivation of the Heb. verb.
====

[[v19-102-8]]

^<<v19-102-8,8>>^ All day long my enemies have reproached me.
Those making a fool of me have sworn even by me.

[[v19-102-9]]

^<<v19-102-9,9>>^ For I have eaten ashes themselves just like bread;
And the things I drink I have mingled even with weeping,

[[v19-102-10]]

^<<v19-102-10,10>>^ Because of your denunciation and your indignation;
For you have lifted me up, that you might throw me away.

[[v19-102-11]]

^<<v19-102-11,11>>^ My days are like a shadow that has declined,^&#42;1^
And I myself am dried up like mere vegetation.

[NOTE]
====
. “My own days have declined just like a shadow,” LXXSyVg and by a slight correction of M.
====

[[v19-102-12]]

^<<v19-102-12,12>>^ As for you, O Jehovah, to time indefinite you will dwell,
And your memorial will be for generation after generation.

[[v19-102-13]]

^<<v19-102-13,13>>^ You yourself will arise, you will have mercy on Zion,
For it is the season to be favorable to her,
For the appointed time has come.

[[v19-102-14]]

^<<v19-102-14,14>>^ For your servants have found pleasure in her stones,
And to her dust they direct their favor.

[[v19-102-15]]

^<<v19-102-15,15>>^ And the nations will fear the name of Jehovah,^&#42;1^
And all the kings of the earth your glory.

[NOTE]
====
. See App 1C §8.
====

[[v19-102-16]]

^<<v19-102-16,16>>^ For Jehovah^&#42;1^ will certainly build up Zion;
He must appear in his glory.

[NOTE]
====
. See App 1C §8.
====

[[v19-102-17]]

^<<v19-102-17,17>>^ He will certainly turn to the prayer of those stripped &#91;of everything&#93;,
And not despise their prayer.

[[v19-102-18]]

^<<v19-102-18,18>>^ This is written for the future generation;
And the people that is to be created will praise Jah.^&#42;1^

[NOTE]
====
. See 68:4 ftn.
====

[[v19-102-19]]

^<<v19-102-19,19>>^ For he has looked down from his holy height,
From the very heavens Jehovah^&#42;1^ himself has looked even at the earth,

[NOTE]
====
. See App 1C §8.
====

[[v19-102-20]]

^<<v19-102-20,20>>^ To hear the sighing of the prisoner,
To loosen those appointed to death;^&#42;1^

[NOTE]
====
. Lit., “the sons of death.”
====

[[v19-102-21]]

^<<v19-102-21,21>>^ For the name of Jehovah^&#42;1^ to be declared^&#42;2^ in Zion
And his praise in Jerusalem,

[NOTE]
====
. See App 1C §8.
. Lit., “to declare the name of Jehovah.”
====

[[v19-102-22]]

^<<v19-102-22,22>>^ When the peoples are collected all together,
And the kingdoms to serve^&#42;1^ Jehovah.

[NOTE]
====
. Or, “to worship (render sacred service).” Heb., la·ʽavodhʹ.
====

[[v19-102-23]]

^<<v19-102-23,23>>^ On the way he afflicted my power,
He cut short my days.

[[v19-102-24]]

^<<v19-102-24,24>>^ I proceeded to say: “O my God,^&#42;1^
Do not take me off at the half of my days;
Your years are throughout all generations.^&#42;2^

[NOTE]
====
. “O my God.” Heb., ʼE·liʹ.
. Lit., “in (throughout) the generation of generations.”
====

[[v19-102-25]]

^<<v19-102-25,25>>^ Long ago you laid the foundations of the earth itself,
And the heavens are the work of your hands.

[[v19-102-26]]

^<<v19-102-26,26>>^ They themselves will perish, but you yourself will keep standing;^&#42;1^
And just like a garment they will all of them wear out.
Just like clothing you will replace them, and they will finish their turn.

[NOTE]
====
. Or, “existing.” Compare Ex 9:16 ftn, “Existence.”
====

[[v19-102-27]]

^<<v19-102-27,27>>^ But you are the same,^&#42;1^ and your own years will not be completed.

[NOTE]
====
. Lit., “you are he.”
====

[[v19-102-28]]

^<<v19-102-28,28>>^ The sons of your servants will continue residing;
And before you their own offspring will be firmly established.”

'''

xref:019-psalm/019-psalm-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-psalm/019-psalm-103.adoc#v19-103-0[Próximo Capítulo &#62;]