include::./index.adoc[]

[[v19-118-0]]
=== Psalms, 118
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-118-1]]

^<<v19-118-1,1>>^ Give thanks to Jehovah, YOU people, for he is good;
For his loving-kindness is to time indefinite.

[[v19-118-2]]

^<<v19-118-2,2>>^ Let Israel now say:
“For his loving-kindness is to time indefinite.”

[[v19-118-3]]

^<<v19-118-3,3>>^ Let those of the house of Aaron now say:
“For his loving-kindness is to time indefinite.”

[[v19-118-4]]

^<<v19-118-4,4>>^ Let those fearing Jehovah now say:
“For his loving-kindness is to time indefinite.”

[[v19-118-5]]

^<<v19-118-5,5>>^ Out of the distressing circumstances I called upon Jah;^&#42;1^
Jah answered &#91;and put&#93; me into a roomy place.^&#42;2^

[NOTE]
====
. See 68:4 ftn.
. “He answered me with the roomy (spacious) place of Jah,” according to many Heb. mss.
====

[[v19-118-6]]

^<<v19-118-6,6>>^ Jehovah is on my side;^&#42;1^ I shall not fear.
What can earthling man^&#42;2^ do to me?

[NOTE]
====
. Or, “Jehovah is mine (belongs to me).”
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v19-118-7]]

^<<v19-118-7,7>>^ Jehovah is on my side among those helping me,
So that I myself shall look upon those hating me.

[[v19-118-8]]

^<<v19-118-8,8>>^ It is better to take refuge in Jehovah
Than to trust in earthling man.

[[v19-118-9]]

^<<v19-118-9,9>>^ It is better to take refuge in Jehovah
Than to trust in nobles.

[[v19-118-10]]

^<<v19-118-10,10>>^ All the nations themselves surrounded me.
It was in the name of Jehovah that I kept holding them off.

[[v19-118-11]]

^<<v19-118-11,11>>^ They surrounded me, yes, they had me surrounded.
It was in the name of Jehovah that I kept holding them off.

[[v19-118-12]]

^<<v19-118-12,12>>^ They surrounded me like bees;
They were extinguished like a fire of thornbushes.
It was in the name of Jehovah that I kept holding them off.

[[v19-118-13]]

^<<v19-118-13,13>>^ You pushed me hard that I should fall,
But Jehovah himself helped me.

[[v19-118-14]]

^<<v19-118-14,14>>^ Jah is my shelter and &#91;my&#93; might,^&#42;1^
And to me he becomes salvation.

[NOTE]
====
. Possibly, “Jah is my strength and [my] melody.”
====

[[v19-118-15]]

^<<v19-118-15,15>>^ The voice of a joyful cry and salvation
Is in the tents of the righteous ones.
The right hand of Jehovah is demonstrating vital energy.

[[v19-118-16]]

^<<v19-118-16,16>>^ The right hand of Jehovah is exalting &#91;itself&#93;;^&#42;1^
The right hand of Jehovah is demonstrating vital energy.

[NOTE]
====
. “Me,” LXXSyVg.
====

[[v19-118-17]]

^<<v19-118-17,17>>^ I shall not die, but I shall keep living,
That I may declare the works of Jah.^&#42;1^

[NOTE]
====
. “Jah.” Heb., Yah; LXXSyVg, “Jehovah.”
====

[[v19-118-18]]

^<<v19-118-18,18>>^ Jah corrected me severely,
But he did not give me over to death itself.

[[v19-118-19]]

^<<v19-118-19,19>>^ Open to me the gates of righteousness, YOU people.
I shall go into them; I shall laud Jah.^&#42;1^

[NOTE]
====
. See 68:4 ftn.
====

[[v19-118-20]]

^<<v19-118-20,20>>^ This is the gate of Jehovah.
The righteous themselves will go into it.

[[v19-118-21]]

^<<v19-118-21,21>>^ I shall laud you, for you answered me
And you came to be my salvation.

[[v19-118-22]]

^<<v19-118-22,22>>^ The stone that the builders rejected
Has become the head of the corner.

[[v19-118-23]]

^<<v19-118-23,23>>^ This has come to be from Jehovah himself;
It^&#42;1^ is wonderful in our eyes.

[NOTE]
====
. “This . . . it,” both fem., possibly referring to “the stone,” fem., in vs 22.
====

[[v19-118-24]]

^<<v19-118-24,24>>^ This is the day that Jehovah has made;^&#42;1^
We will be joyful and rejoice in it.

[NOTE]
====
. Or, “This is the day that Jehovah has done [it].”
====

[[v19-118-25]]

^<<v19-118-25,25>>^ Ah, now, Jehovah, do save, please!
Ah, now, Jehovah, do grant success, please!

[[v19-118-26]]

^<<v19-118-26,26>>^ Blessed be the One coming in the name of Jehovah;
We have blessed YOU people out of the house of Jehovah.

[[v19-118-27]]

^<<v19-118-27,27>>^ Jehovah is the Divine One,^&#42;1^
And he gives us light.
Bind the festival procession with boughs, O YOU people,
As far as the horns of the altar.

[NOTE]
====
. “Divine One.” Or, “God.” Heb., ʼEl.
====

[[v19-118-28]]

^<<v19-118-28,28>>^ You are my Divine One, and I shall laud you;
My God^&#42;1^—I shall exalt you.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v19-118-29]]

^<<v19-118-29,29>>^ Give thanks to Jehovah, YOU people, for he is good;
For his loving-kindness is to time indefinite.

'''

xref:019-psalm/019-psalm-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-psalm/019-psalm-119.adoc#v19-119-0[Próximo Capítulo &#62;]