include::./index.adoc[]

[[v19-109-0]]
=== Psalms, 109
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. Of David. A melody._

[[v19-109-1]]

^<<v19-109-1,1>>^ O God of my praise, do not keep silent.

[[v19-109-2]]

^<<v19-109-2,2>>^ For the mouth of the wicked one and the mouth of deception have opened against me.
They have spoken about me with the tongue of falsehood;

[[v19-109-3]]

^<<v19-109-3,3>>^ And with words of hatred they have surrounded me,
And they keep fighting against me without cause.

[[v19-109-4]]

^<<v19-109-4,4>>^ For my love they keep resisting me;
But on my part there is prayer.

[[v19-109-5]]

^<<v19-109-5,5>>^ And they render to me bad for good
And hatred for my love.

[[v19-109-6]]

^<<v19-109-6,6>>^ Appoint over him someone wicked,
And may a resister^&#42;1^ himself keep standing at his right hand.

[NOTE]
====
. “And . . . a resister.” Heb., wesa·tanʹ; Gr., di·aʹbo·los; Lat., saʹtan.
====

[[v19-109-7]]

^<<v19-109-7,7>>^ When he is judged, let him go forth as someone wicked;
And let his very prayer become a sin.

[[v19-109-8]]

^<<v19-109-8,8>>^ Let his days prove to be few;
His office of oversight^&#42;1^ let someone else take.

[NOTE]
====
. “His office of oversight.” Heb., pequd·da·thohʹ; Gr., e·pi·sko·penʹ au·touʹ; Lat., e·pi·sco·paʹtum eʹius. See 2Ki 11:18; Ac 1:20.
====

[[v19-109-9]]

^<<v19-109-9,9>>^ Let his sons become fatherless boys
And his wife be a widow.

[[v19-109-10]]

^<<v19-109-10,10>>^ And without fail let his sons go wandering about;
And they must do begging,
And they must look for &#91;food&#93; from their desolate places.

[[v19-109-11]]

^<<v19-109-11,11>>^ Let the usurer lay out traps for all that he has,
And let strangers make plunder of his product of toil.

[[v19-109-12]]

^<<v19-109-12,12>>^ May he come to have no one extending loving-kindness,
And may there prove to be no one showing favor to his fatherless boys.

[[v19-109-13]]

^<<v19-109-13,13>>^ Let his posterity be for cutting off.
In the following generation let their name be wiped out.

[[v19-109-14]]

^<<v19-109-14,14>>^ Let the error of his forefathers be remembered to Jehovah,
And the sin of his mother—may it not be wiped out.

[[v19-109-15]]

^<<v19-109-15,15>>^ Let them prove to be in front of Jehovah constantly;
And may he cut off the remembrance^&#42;1^ of them from the very earth;

[NOTE]
====
. Or, “mention.”
====

[[v19-109-16]]

^<<v19-109-16,16>>^ For the reason that he did not remember to exercise loving-kindness,
But he kept pursuing the afflicted and poor man^&#42;1^
And the one dejected at heart, to put &#91;him&#93; to death.

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v19-109-17]]

^<<v19-109-17,17>>^ And he kept loving the malediction, so that it came upon him;
And he did not take delight in the blessing,
So that it became far away from him;

[[v19-109-18]]

^<<v19-109-18,18>>^ And he came to be clothed with malediction as his garment.
So it came like waters into the midst of him
And like oil into his bones.

[[v19-109-19]]

^<<v19-109-19,19>>^ May it prove to be for him like a garment with which he enwraps himself
And as a girdle that he keeps girded about himself constantly.

[[v19-109-20]]

^<<v19-109-20,20>>^ This is the wages from Jehovah of the one resisting me
And of those speaking evil against my soul.

[[v19-109-21]]

^<<v19-109-21,21>>^ But you are Jehovah the Sovereign Lord.
Deal with me for the sake of your name.
Because your loving-kindness is good, deliver me.

[[v19-109-22]]

^<<v19-109-22,22>>^ For I am afflicted and poor,
And my heart itself has been pierced^&#42;1^ within me.

[NOTE]
====
. Lit., “one has pierced my heart itself.”
====

[[v19-109-23]]

^<<v19-109-23,23>>^ Like a shadow when it declines, I am obliged to go away;
I have been shaken off like a locust.

[[v19-109-24]]

^<<v19-109-24,24>>^ My knees themselves have swayed from fasting,
And my very flesh has grown lean, without any oil.

[[v19-109-25]]

^<<v19-109-25,25>>^ And to them I myself have become something reproachable.
They see me—they begin wagging their head.

[[v19-109-26]]

^<<v19-109-26,26>>^ Help me, O Jehovah my God;
Save me according to your loving-kindness.

[[v19-109-27]]

^<<v19-109-27,27>>^ And may they know that this is your hand;
That you yourself, O Jehovah, have done it.

[[v19-109-28]]

^<<v19-109-28,28>>^ Let them, for their part, pronounce a malediction,
But may you, for your part, pronounce a blessing.
They have risen up, but let them be ashamed,
And let your own servant rejoice.

[[v19-109-29]]

^<<v19-109-29,29>>^ Let those resisting me be clothed with humiliation,
And let them enwrap themselves with their shame just as with a sleeveless coat.

[[v19-109-30]]

^<<v19-109-30,30>>^ I shall laud Jehovah very much with my mouth,
And in among many people I shall praise him.

[[v19-109-31]]

^<<v19-109-31,31>>^ For he will stand at the right hand of the poor,
To save &#91;him&#93; from those judging his soul.

'''

xref:019-psalm/019-psalm-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-psalm/019-psalm-110.adoc#v19-110-0[Próximo Capítulo &#62;]