include::./index.adoc[]

[[v19-50-0]]
=== Psalms, 50
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A melody of Aʹsaph._

[[v19-50-1]]

^<<v19-50-1,1>>^ The Divine One, God, Jehovah,^&#42;1^ has himself spoken,
And he proceeds to call the earth,^&#42;2^
From the rising of the sun until its setting.

[NOTE]
====
. “The Divine One, God, Jehovah.” Or, “The God of gods, Jehovah.” Heb., ʼEl ʼElo·himʹ Yehwahʹ. See Jos 22:22 ftn, “Jehovah.”
. “And the earth begins to fear,” by a change in M.
====

[[v19-50-2]]

^<<v19-50-2,2>>^ Out of Zion, the perfection of prettiness, God himself has beamed forth.

[[v19-50-3]]

^<<v19-50-3,3>>^ Our God will come and cannot possibly keep silent.^&#42;1^
Before him there devours a fire,
And all around him it has become exceedingly stormy weather.

[NOTE]
====
. Or, “be deaf,” as to prayer.
====

[[v19-50-4]]

^<<v19-50-4,4>>^ He calls to the heavens above and to the earth
So as to execute judgment on his people:

[[v19-50-5]]

^<<v19-50-5,5>>^ “Gather to me my loyal ones,
Those concluding^&#42;1^ my covenant^&#42;2^ over sacrifice.”

[NOTE]
====
. Lit., “cutting.”
. Or, “the covenant with me.”
====

[[v19-50-6]]

^<<v19-50-6,6>>^ And the heavens tell of his righteousness,
For God himself is Judge.^&#42;1^ Seʹlah.

[NOTE]
====
. “A God of judgment he is,” by a different partitioning and vowel pointing of some letters.
====

[[v19-50-7]]

^<<v19-50-7,7>>^ “Do listen, O my people, and I will speak,
O Israel, and I will bear witness against you.^&#42;1^
I am God, your God.

[NOTE]
====
. Or, “I will admonish (warn) you.”
====

[[v19-50-8]]

^<<v19-50-8,8>>^ Not concerning your sacrifices do I reprove you,
Nor &#91;concerning&#93; your whole burnt offerings &#91;that are&#93; in front of me constantly.

[[v19-50-9]]

^<<v19-50-9,9>>^ I will not take out of your house a bull,
Out of your pens he-goats.

[[v19-50-10]]

^<<v19-50-10,10>>^ For to me belongs every wild animal of the forest,
The beasts upon a thousand mountains.

[[v19-50-11]]

^<<v19-50-11,11>>^ I well know every winged creature of the mountains,
And the animal throngs of the open field are with me.

[[v19-50-12]]

^<<v19-50-12,12>>^ If I were hungry, I would not say it to you;
For to me the productive land^&#42;1^ and its fullness belong.

[NOTE]
====
. “The productive land.” Heb., the·velʹ; LXX, “the habitable earth”; Lat., orʹbis terʹrae, “the circle of the earth.”
====

[[v19-50-13]]

^<<v19-50-13,13>>^ Shall I eat the flesh of powerful &#91;bulls&#93;,
And the blood of he-goats shall I drink?

[[v19-50-14]]

^<<v19-50-14,14>>^ Offer thanksgiving as your sacrifice to God,
And pay to the Most High your vows;

[[v19-50-15]]

^<<v19-50-15,15>>^ And call me in the day of distress.
I shall rescue you, and you will glorify me.”

[[v19-50-16]]

^<<v19-50-16,16>>^ But to the wicked one God will have to say:
“What right do you have to enumerate my regulations,
And that you may bear my covenant^&#42;1^ in your mouth?

[NOTE]
====
. “My covenant,” as in vs 5.
====

[[v19-50-17]]

^<<v19-50-17,17>>^ Why, you—you have hated discipline,
And you keep throwing my words behind you.

[[v19-50-18]]

^<<v19-50-18,18>>^ Whenever you saw a thief, you were even pleased^&#42;1^ with him;
And your sharing was with adulterers.

[NOTE]
====
. “You were even pleased,” M; TLXXSyVg, “you even ran.”
====

[[v19-50-19]]

^<<v19-50-19,19>>^ Your mouth you have let loose to what is bad,
And your tongue you keep attached to deception.

[[v19-50-20]]

^<<v19-50-20,20>>^ You sit &#91;and&#93; speak against your own brother,
Against the son of your mother you give away a fault.

[[v19-50-21]]

^<<v19-50-21,21>>^ These things you have done, and I kept silent.
You imagined that I would positively become like you.
I am going to reprove you, and I will set things in order before your eyes.

[[v19-50-22]]

^<<v19-50-22,22>>^ Understand this, please, YOU forgetters of God,^&#42;1^
That I may not tear &#91;YOU&#93; to pieces without there being any deliverer.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v19-50-23]]

^<<v19-50-23,23>>^ The one offering thanksgiving as his sacrifice is the one that glorifies me;
And as for the one keeping a set way,
I will cause him to see salvation by God.”^&#42;1^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

'''

xref:019-psalm/019-psalm-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-psalm/019-psalm-051.adoc#v19-51-0[Próximo Capítulo &#62;]