include::./index.adoc[]

[[v19-59-0]]
=== Psalms, 59
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. “Do not bring to ruin.” Of David. Mikʹtam.^&#42;1^ When Saul sent, and they kept watching the house, to put him to death._

[[v19-59-1]]

^<<v19-59-1,1>>^ Deliver me from my enemies, O my God;
From those rising up against me may you protect me.

[[v19-59-2]]

^<<v19-59-2,2>>^ Deliver me from the practicers of what is hurtful,
And from bloodguilty men save me.

[[v19-59-3]]

^<<v19-59-3,3>>^ For, look! they have lain in wait for my soul;
Strong ones make an attack upon me,
For no revolt on my part, nor any sin on my part, O Jehovah.

[[v19-59-4]]

^<<v19-59-4,4>>^ Though there is no error, they run and get themselves ready.
Do rouse yourself at my calling and see.

[[v19-59-5]]

^<<v19-59-5,5>>^ And you, O Jehovah God of armies, are the God of Israel.
Do wake up to turn your attention to all the nations.
Do not show favor to any hurtful traitors. Seʹlah.

[[v19-59-6]]

^<<v19-59-6,6>>^ They keep returning at evening time;
They keep barking like a dog and go all around the city.

[[v19-59-7]]

^<<v19-59-7,7>>^ Look! They make a bubbling forth with their mouth;
Swords are on their lips,
For who is listening?

[[v19-59-8]]

^<<v19-59-8,8>>^ But you yourself, O Jehovah, will laugh at them;
You will hold all the nations in derision.

[[v19-59-9]]

^<<v19-59-9,9>>^ O my Strength,^&#42;1^ toward you I will keep watch;
For God is my secure height.

[NOTE]
====
. “My Strength,” TLXXVg and several Heb. mss; M, “His (One’s) Strength.”
====

[[v19-59-10]]

^<<v19-59-10,10>>^ The God of loving-kindness^&#42;1^ to me^&#42;2^ will himself confront me;
God himself will cause me to look upon my foes.

[NOTE]
====
. Or, “loyal love.”
. “To me,” MmarginT and many Heb. mss.
====

[[v19-59-11]]

^<<v19-59-11,11>>^ Do not kill them, that my people may not forget.
By your vital energy make them wander about,
And bring them down, O our shield Jehovah,^&#42;1^

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-59-12]]

^<<v19-59-12,12>>^ &#91;For&#93; the sin of their mouth, the word of their lips;
And may they be caught in their pride,
Even for the cursing and the deception that they rehearse.

[[v19-59-13]]

^<<v19-59-13,13>>^ Bring &#91;them&#93; to an end in rage;
Bring &#91;them&#93; to an end, that they may not be;
And may they know that God is ruling in Jacob to the ends of the earth. Seʹlah.

[[v19-59-14]]

^<<v19-59-14,14>>^ And let them return at evening time;
Let them bark like a dog and go all around the city.

[[v19-59-15]]

^<<v19-59-15,15>>^ Let those very ones wander about for something to eat;
Let them not be satisfied or stay overnight.

[[v19-59-16]]

^<<v19-59-16,16>>^ But as for me, I shall sing of your strength,
And in the morning I shall joyfully tell about your loving-kindness.
For you have proved to be a secure height for me
And a place to which to flee in the day of my distress.

[[v19-59-17]]

^<<v19-59-17,17>>^ O my Strength, to you I will make melody,
For God is my secure height, the God of loving-kindness to me.

'''

xref:019-psalm/019-psalm-058.adoc#v19-58-0[&#60; Capítulo Anterior] | <<v19-59-0,Topo>> | xref:019-psalm/019-psalm-060.adoc#v19-60-0[Próximo Capítulo &#62;]