include::./index.adoc[]

[[v19-71-0]]
=== Psalms, 71
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-71-1]]

^<<v19-71-1,1>>^ In you, O Jehovah, I have taken refuge.
O may I never be ashamed.

[[v19-71-2]]

^<<v19-71-2,2>>^ In your righteousness may you deliver me and provide me with escape.
Incline to me your ear and save me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Become to me a rock fortress into which to enter constantly.
You must command to save me,
For you are my crag and my stronghold.

[[v19-71-4]]

^<<v19-71-4,4>>^ O my God, provide me with escape from the hand of the wicked one,
From the palm of the one acting unjustly and oppressively.

[[v19-71-5]]

^<<v19-71-5,5>>^ For you are my hope, O Sovereign Lord Jehovah, my confidence from my youth.

[[v19-71-6]]

^<<v19-71-6,6>>^ Upon you I have supported myself from the belly;
You are the One severing me even from the inward parts of my mother.
In you my praise is constantly.

[[v19-71-7]]

^<<v19-71-7,7>>^ I have become just like a miracle to many people;
But you are my strong refuge.

[[v19-71-8]]

^<<v19-71-8,8>>^ My mouth is filled with your praise,
All day long with your beauty.

[[v19-71-9]]

^<<v19-71-9,9>>^ Do not throw me away in the time of old age;
Just when my power is failing, do not leave me.

[[v19-71-10]]

^<<v19-71-10,10>>^ For my enemies have said in regard to me,
And the very ones keeping watch for my soul have jointly exchanged counsel,

[[v19-71-11]]

^<<v19-71-11,11>>^ Saying: “God himself has left him.
Pursue and catch him, for there is no deliverer.”

[[v19-71-12]]

^<<v19-71-12,12>>^ O God, do not keep far away from me.
O my God, do hurry to my assistance.

[[v19-71-13]]

^<<v19-71-13,13>>^ May those be ashamed, may those come to their end, who are resisting my soul.
May those cover themselves with reproach and humiliation who are seeking calamity for me.

[[v19-71-14]]

^<<v19-71-14,14>>^ But as for me, I shall wait constantly,
And I will add to all your praise.

[[v19-71-15]]

^<<v19-71-15,15>>^ My own mouth will recount your righteousness,
All day long your salvation,
For I have not come to know the numbers &#91;of them&#93;.

[[v19-71-16]]

^<<v19-71-16,16>>^ I shall come in grand mightiness, O Sovereign Lord Jehovah;
I shall mention your righteousness, yours alone.

[[v19-71-17]]

^<<v19-71-17,17>>^ O God, you have taught me from my youth on,
And until now I keep telling about your wonderful works.

[[v19-71-18]]

^<<v19-71-18,18>>^ And even until old age and gray-headedness, O God, do not leave me,
Until I may tell about your arm to the generation,
To all those who are to come, about your mightiness.

[[v19-71-19]]

^<<v19-71-19,19>>^ Your righteousness, O God, is up to the height;
As respects the great things that you have done,
O God, who is like you?

[[v19-71-20]]

^<<v19-71-20,20>>^ Because you have made me^&#42;1^ see many distresses and calamities,
May you revive me again;
And from the watery deeps^&#42;2^ of the earth may you again bring me up.

[NOTE]
====
. “Me,” MmarginLXXSyVg; M, “us.”
. Or, “the surging waters.” By a correction of M, “the lower (lowest) parts,” as in 63:9.
====

[[v19-71-21]]

^<<v19-71-21,21>>^ May you enlarge my greatness,
And may you surround &#91;and&#93; comfort me.

[[v19-71-22]]

^<<v19-71-22,22>>^ I too, I shall laud you on an instrument of a stringed sort,
As regards your trueness, O my God.
I will make melody to you on the harp, O Holy One of Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ My lips will cry out joyfully when I am inclined to make melody to you,
Even my soul that you have redeemed.

[[v19-71-24]]

^<<v19-71-24,24>>^ Also, my own tongue, all day long, will utter in an undertone your righteousness,
For they have become ashamed, for they have become abashed, who are seeking calamity for me.

'''

xref:019-psalm/019-psalm-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-psalm/019-psalm-072.adoc#v19-72-0[Próximo Capítulo &#62;]