include::./index.adoc[]

[[v19-27-0]]
=== Psalms, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_Of David._

[[v19-27-1]]

^<<v19-27-1,1>>^ Jehovah is my light and my salvation.
Of whom shall I be in fear?
Jehovah is the stronghold of my life.
Of whom shall I be in dread?

[[v19-27-2]]

^<<v19-27-2,2>>^ When the evildoers approached against me to eat up my flesh,
They being my adversaries and my enemies personally,
They themselves stumbled and fell.

[[v19-27-3]]

^<<v19-27-3,3>>^ Though against me an encampment should pitch tent,
My heart will not fear.
Though against me war should rise,
Even then I shall be trusting.

[[v19-27-4]]

^<<v19-27-4,4>>^ One thing I have asked from Jehovah—
It is what I shall look for,
That I may dwell in the house of Jehovah all the days of my life,
To behold the pleasantness of Jehovah
And to look with appreciation upon his temple.^&#42;1^

[NOTE]
====
. “Upon his temple.” Heb., beheh·kha·lohʹ; Gr., na·onʹ; Lat., temʹplum. Compare 2Ki 20:18 ftn. See Mt 23:16 ftn.
====

[[v19-27-5]]

^<<v19-27-5,5>>^ For he will hide me in his covert in the day of calamity;
He will conceal me in the secret place of his tent;
High on a rock he will put me.

[[v19-27-6]]

^<<v19-27-6,6>>^ And now my head will be high above my enemies all around me;
And I will sacrifice at his tent sacrifices of joyful shouting;
I will sing and make melody to Jehovah.

[[v19-27-7]]

^<<v19-27-7,7>>^ Hear, O Jehovah, when I call with my voice,
And show me favor and answer me.

[[v19-27-8]]

^<<v19-27-8,8>>^ Concerning you my heart has said: “Seek to find my face, YOU people.”
Your face, O Jehovah, I shall seek to find.

[[v19-27-9]]

^<<v19-27-9,9>>^ Do not conceal your face from me.
Do not in anger turn your servant away.
My assistance you must become.
Do not forsake me and do not leave me, O my God of salvation.

[[v19-27-10]]

^<<v19-27-10,10>>^ In case my own father and my own mother did leave me,
Even Jehovah himself would take me up.

[[v19-27-11]]

^<<v19-27-11,11>>^ Instruct me, O Jehovah, in your way,
And lead me in the path of uprightness on account of my foes.

[[v19-27-12]]

^<<v19-27-12,12>>^ Do not give me over to the soul of my adversaries;
For against me false witnesses have risen up,
And he who launches forth violence.

[[v19-27-13]]

^<<v19-27-13,13>>^ If I had not^&#42;1^ had faith in seeing the goodness of Jehovah in the land of those alive—!

[NOTE]
====
. “If . . . not.” Heb., lu·leʼʹ; LXXSyVg and five Heb. mss omit. In M this word is marked with extraordinary points by the Sopherim. See App 2A.
====

[[v19-27-14]]

^<<v19-27-14,14>>^ Hope in Jehovah; be courageous and let your heart be strong.
Yes, hope in Jehovah.

'''

xref:019-psalm/019-psalm-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-psalm/019-psalm-028.adoc#v19-28-0[Próximo Capítulo &#62;]