include::./index.adoc[]

[[v19-66-0]]
=== Psalms, 66
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. A song, a melody._

[[v19-66-1]]

^<<v19-66-1,1>>^ Shout in triumph to God, all &#91;YOU people of&#93; the earth.^&#42;1^

[NOTE]
====
. Lit., “O all the earth,” with a pl. verb. Compare 1Ki 10:24 ftn, “Earth.”
====

[[v19-66-2]]

^<<v19-66-2,2>>^ Make melody to the glory of his name.
Render his praise glorious.

[[v19-66-3]]

^<<v19-66-3,3>>^ Say to God: “How fear-inspiring your works are!
Because of the abundance of your strength your enemies will come cringing to you.

[[v19-66-4]]

^<<v19-66-4,4>>^ All &#91;people of&#93; the earth will bow down to you,
And they will make melody to you, they will make melody to your name.” Seʹlah.

[[v19-66-5]]

^<<v19-66-5,5>>^ Come, YOU people, and see the activities of God.
His dealing with the sons of men^&#42;1^ is fear-inspiring.

[NOTE]
====
. “Men.” Heb., ʼa·dhamʹ.
====

[[v19-66-6]]

^<<v19-66-6,6>>^ He has changed the sea into dry land;
Through the river they went crossing over on foot.
There we began to rejoice in him.

[[v19-66-7]]

^<<v19-66-7,7>>^ He is ruling by his mightiness to time indefinite.
Upon the nations his own eyes keep watch.
As for those who are stubborn, let them not be exalted in themselves. Seʹlah.

[[v19-66-8]]

^<<v19-66-8,8>>^ Bless our God, O YOU peoples,
And cause the voice of praise to him to be heard.

[[v19-66-9]]

^<<v19-66-9,9>>^ He is setting our soul in life,^&#42;1^
And he has not allowed our foot to totter.

[NOTE]
====
. Or, “among the living ones.”
====

[[v19-66-10]]

^<<v19-66-10,10>>^ For you have examined us, O God;
You have refined us as when refining silver.

[[v19-66-11]]

^<<v19-66-11,11>>^ You have brought us into a hunting net;
You have put pressure on our hips.

[[v19-66-12]]

^<<v19-66-12,12>>^ You have made mortal man to ride over our head;
We have come through fire and through water,
And you proceeded to bring us forth to relief.

[[v19-66-13]]

^<<v19-66-13,13>>^ I shall come into your house with whole burnt offerings;
I shall pay to you my vows

[[v19-66-14]]

^<<v19-66-14,14>>^ That my lips have opened up to say
And that my mouth has spoken when I was in sore straits.

[[v19-66-15]]

^<<v19-66-15,15>>^ Whole burnt offerings of fatlings I shall offer up to you,
With the sacrificial smoke of rams.
I shall render up a bull with he-goats. Seʹlah.

[[v19-66-16]]

^<<v19-66-16,16>>^ Come, listen, all YOU who fear God, and I will relate
What he has done for my soul.

[[v19-66-17]]

^<<v19-66-17,17>>^ To him I called with my mouth,
And there was an extolling with my tongue.

[[v19-66-18]]

^<<v19-66-18,18>>^ If I have regarded anything hurtful in my heart,
Jehovah^&#42;1^ will not hear &#91;me&#93;.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-66-19]]

^<<v19-66-19,19>>^ Truly God has heard;
He has paid attention to the voice of my prayer.

[[v19-66-20]]

^<<v19-66-20,20>>^ Blessed be God, who has not turned aside my prayer,
Nor his loving-kindness from me.

'''

xref:019-psalm/019-psalm-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-psalm/019-psalm-067.adoc#v19-67-0[Próximo Capítulo &#62;]