include::./index.adoc[]

[[v19-51-0]]
=== Psalms, 51
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. A melody of David. When Nathan the prophet came in to him after he had had relations with Bath-sheʹba._

[[v19-51-1]]

^<<v19-51-1,1>>^ Show me favor, O God,^&#42;1^ according to your loving-kindness.^&#42;2^
According to the abundance of your mercies wipe out my transgressions.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
. Or, “loyal love.”
====

[[v19-51-2]]

^<<v19-51-2,2>>^ Thoroughly wash me from my error,
And cleanse me even from my sin.

[[v19-51-3]]

^<<v19-51-3,3>>^ For my transgressions I myself know,
And my sin is in front of me constantly.

[[v19-51-4]]

^<<v19-51-4,4>>^ Against you, you alone, I have sinned,
And what is bad in your eyes I have done,
In order that you may prove to be righteous when you speak,
That you may be in the clear when you judge.

[[v19-51-5]]

^<<v19-51-5,5>>^ Look! With error I was brought forth with birth pains,
And in sin my mother conceived me.

[[v19-51-6]]

^<<v19-51-6,6>>^ Look! You have taken delight in truthfulness itself in the inward parts;
And in the secret self may you cause me to know sheer wisdom.

[[v19-51-7]]

^<<v19-51-7,7>>^ May you purify me from sin with hyssop, that I may be clean;
May you wash me, that I may become whiter even than snow.

[[v19-51-8]]

^<<v19-51-8,8>>^ May you cause me to hear exultation and rejoicing,
That the bones that you have crushed may be joyful.

[[v19-51-9]]

^<<v19-51-9,9>>^ Conceal your face from my sins,
And wipe out even all my errors.

[[v19-51-10]]

^<<v19-51-10,10>>^ Create in me even a pure heart, O God,
And put within me a new spirit, a steadfast one.

[[v19-51-11]]

^<<v19-51-11,11>>^ Do not throw me away from before your face;
And your holy spirit O do not take away from me.

[[v19-51-12]]

^<<v19-51-12,12>>^ Do restore to me the exultation of salvation by you,
And may you support me even with a willing spirit.

[[v19-51-13]]

^<<v19-51-13,13>>^ I will teach transgressors your ways,
That sinners themselves may turn right back to you.

[[v19-51-14]]

^<<v19-51-14,14>>^ Deliver me from bloodguiltiness,^&#42;1^ O God the God of my salvation,
That my tongue may joyfully tell about your righteousness.

[NOTE]
====
. Lit., “bloods.”
====

[[v19-51-15]]

^<<v19-51-15,15>>^ O Jehovah,^&#42;1^ may you open these lips of mine,
That my own mouth may tell forth your praise.

[NOTE]
====
. One of 134 scrib­al changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-51-16]]

^<<v19-51-16,16>>^ For you do not take delight in sacrifice—otherwise I would give &#91;it&#93;;
In whole burnt offering you do not find pleasure.

[[v19-51-17]]

^<<v19-51-17,17>>^ The sacrifices to God are a broken spirit;
A heart broken and crushed, O God, you will not despise.

[[v19-51-18]]

^<<v19-51-18,18>>^ In your goodwill do deal well with Zion;
May you build the walls of Jerusalem.

[[v19-51-19]]

^<<v19-51-19,19>>^ In that case you will be delighted with sacrifices of righteousness,
With burnt sacrifice and whole offering;
In that case bulls will be offered up on your very own altar.

'''

xref:019-psalm/019-psalm-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-psalm/019-psalm-052.adoc#v19-52-0[Próximo Capítulo &#62;]