include::./index.adoc[]

[[v19-129-0]]
=== Psalms, 129
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A Song of the Ascents._

[[v19-129-1]]

^<<v19-129-1,1>>^ “Long enough they have shown hostility to me from my youth,”
Let Israel now say,

[[v19-129-2]]

^<<v19-129-2,2>>^ “Long enough they have shown hostility to me from my youth;
Yet they have not prevailed over me.

[[v19-129-3]]

^<<v19-129-3,3>>^ Plowmen have plowed upon my very back;
They have lengthened their furrows.”^&#42;1^

[NOTE]
====
. Or, “plowing grounds.”
====

[[v19-129-4]]

^<<v19-129-4,4>>^ Jehovah is righteous.
He has cut in pieces the ropes of the wicked ones.

[[v19-129-5]]

^<<v19-129-5,5>>^ They will be ashamed and turn themselves back,
All those hating Zion.

[[v19-129-6]]

^<<v19-129-6,6>>^ They will become like green grass of the roofs,
Which before it has been torn out has dried up,

[[v19-129-7]]

^<<v19-129-7,7>>^ With which the reaper has not filled his own hand,
Nor anyone gathering sheaves his own bosom.

[[v19-129-8]]

^<<v19-129-8,8>>^ Nor have those passing by said:
“The blessing of Jehovah be upon YOU men.
We have blessed YOU in the name of Jehovah.”

'''

xref:019-psalm/019-psalm-128.adoc#v19-128-0[&#60; Capítulo Anterior] | <<v19-129-0,Topo>> | xref:019-psalm/019-psalm-130.adoc#v19-130-0[Próximo Capítulo &#62;]