include::./index.adoc[]

[[v19-30-0]]
=== Psalms, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A melody. A song of inauguration of the house. Of David._

[[v19-30-1]]

^<<v19-30-1,1>>^ I shall exalt you, O Jehovah,^&#42;1^ for you have drawn me up
And you have not let my enemies rejoice over me.

[NOTE]
====
. See App 1C §10.
====

[[v19-30-2]]

^<<v19-30-2,2>>^ O Jehovah^&#42;1^ my God, I cried to you for help, and you proceeded to heal me.

[NOTE]
====
. See App 1C §10.
====

[[v19-30-3]]

^<<v19-30-3,3>>^ O Jehovah, you have brought up my soul from Sheʹol^&#42;1^ itself;
You have kept me alive, that I should not go down into the pit.

[NOTE]
====
. “Sheol.” Heb., sheʼohlʹ; Gr., haiʹdou; Lat., in·ferʹno. See App 4B.
====

[[v19-30-4]]

^<<v19-30-4,4>>^ Make melody to Jehovah,^&#42;1^ O YOU loyal ones of his,
Give thanks to his holy memorial;^&#42;2^

[NOTE]
====
. See App 1C §10.
. “To his holy memorial.” Lit., “for memorial (mention) of his holiness.” Heb., lezeʹkher qodh·shohʹ.
====

[[v19-30-5]]

^<<v19-30-5,5>>^ Because being under his anger is for a moment,
Being under his goodwill is for a lifetime.
In the evening weeping may take up lodging, but in the morning there is a joyful cry.

[[v19-30-6]]

^<<v19-30-6,6>>^ As for me, I have said in my ease:
“Never shall I be made to totter.”

[[v19-30-7]]

^<<v19-30-7,7>>^ O Jehovah,^&#42;1^ in your goodwill you have made my mountain to stand in strength.
You concealed your face; I became one that is disturbed.

[NOTE]
====
. See App 1C §10.
====

[[v19-30-8]]

^<<v19-30-8,8>>^ To you, O Jehovah,^&#42;1^ I kept calling;
And to Jehovah^&#42;2^ I kept making entreaty for favor.

[NOTE]
====
. See App 1C §10.
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-30-9]]

^<<v19-30-9,9>>^ What profit is there in my blood when I go down to the pit?^&#42;1^
Will the dust laud you? Will it tell of your trueness?^&#42;2^

[NOTE]
====
. “Pit.” Heb., shaʹchath; T, “heart of the grave”; LXXSyVg, “corruption.”
. Or, “truthfulness; truth.”
====

[[v19-30-10]]

^<<v19-30-10,10>>^ Hear, O Jehovah,^&#42;1^ and show me favor.
O Jehovah,^&#42;2^ prove yourself my helper.

[NOTE]
====
. See App 1C §10.
. See App 1C §10.
====

[[v19-30-11]]

^<<v19-30-11,11>>^ You have changed my mourning into dancing for me;
You have loosened my sackcloth, and you keep me girded with rejoicing,

[[v19-30-12]]

^<<v19-30-12,12>>^ In order that &#91;my&#93; glory^&#42;1^ may make melody to you and not keep silent.
O Jehovah^&#42;2^ my God, to time indefinite I will laud you.

[NOTE]
====
. “My glory,” LXXVg.
. See App 1C §10.
====

'''

xref:019-psalm/019-psalm-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-psalm/019-psalm-031.adoc#v19-31-0[Próximo Capítulo &#62;]