include::./index.adoc[]

[[v19-73-0]]
=== Psalms, 73
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_BOOK THREE_

_(Psalms 73 – 89)_

_A melody of Aʹsaph._

[[v19-73-1]]

^<<v19-73-1,1>>^ God is indeed good to Israel, to those clean in heart.

[[v19-73-2]]

^<<v19-73-2,2>>^ As for me, my feet had almost turned aside,
My steps had nearly been made to slip.^&#42;1^

[NOTE]
====
. Or, “been poured out.”
====

[[v19-73-3]]

^<<v19-73-3,3>>^ For I became envious of the boasters,
&#91;When&#93; I would see the very peace of wicked people.

[[v19-73-4]]

^<<v19-73-4,4>>^ For they have no deathly pangs;
And their paunch is fat.

[[v19-73-5]]

^<<v19-73-5,5>>^ They are not even in the trouble of mortal man,^&#42;1^
And they are not plagued the same as other men.^&#42;2^

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
. “Other men.” Heb., ʼa·dhamʹ.
====

[[v19-73-6]]

^<<v19-73-6,6>>^ Therefore haughtiness has served as a necklace to them;
Violence envelops them as a garment.

[[v19-73-7]]

^<<v19-73-7,7>>^ Their eye has bulged from fatness;
They have exceeded the imaginations of the heart.

[[v19-73-8]]

^<<v19-73-8,8>>^ They scoff and speak about what is bad;
About defrauding they speak in an elevated style.

[[v19-73-9]]

^<<v19-73-9,9>>^ They have put their mouth in the very heavens,
And their tongue itself walks about in the earth.

[[v19-73-10]]

^<<v19-73-10,10>>^ Therefore he brings his people back hither,
And the waters of what is full are drained out for them.

[[v19-73-11]]

^<<v19-73-11,11>>^ And they have said: “How has God^&#42;1^ come to know?
And does there exist knowledge in the Most High?”

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v19-73-12]]

^<<v19-73-12,12>>^ Look! These are the wicked, who are at ease indefinitely.
They have increased &#91;their&#93; means of maintenance.

[[v19-73-13]]

^<<v19-73-13,13>>^ Surely it is in vain that I have cleansed my heart
And that I wash my hands in innocence itself.

[[v19-73-14]]

^<<v19-73-14,14>>^ And I came to be plagued all day long,
And my correction is every morning.

[[v19-73-15]]

^<<v19-73-15,15>>^ If I had said: “I will tell a story like that,”
Look! against the generation of your sons
I should have acted treacherously.

[[v19-73-16]]

^<<v19-73-16,16>>^ And I kept considering so as to know this;
It was a trouble in my eyes,

[[v19-73-17]]

^<<v19-73-17,17>>^ Until I proceeded to come into the grand sanctuary of God.
I wanted to discern their future.

[[v19-73-18]]

^<<v19-73-18,18>>^ Surely on slippery ground is where you place them.
You have made them fall to ruins.

[[v19-73-19]]

^<<v19-73-19,19>>^ O how they have become an object of astonishment as in a moment!
&#91;How&#93; they have reached their end, have been brought to their finish through sudden terrors!

[[v19-73-20]]

^<<v19-73-20,20>>^ Like a dream after awaking, O Jehovah,^&#42;1^
&#91;So&#93; when arousing &#91;yourself&#93; you will despise their very image.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v19-73-21]]

^<<v19-73-21,21>>^ For my heart was soured
And in my kidneys I was sharply pained,

[[v19-73-22]]

^<<v19-73-22,22>>^ And I was unreasoning and I could not know;
I became as mere beasts from your standpoint.

[[v19-73-23]]

^<<v19-73-23,23>>^ But I am constantly with you;
You have taken hold of my right hand.

[[v19-73-24]]

^<<v19-73-24,24>>^ With your counsel you will lead me,
And afterward you will take me even to glory.

[[v19-73-25]]

^<<v19-73-25,25>>^ Whom do I have in the heavens?
And besides you I do have no other delight on the earth.

[[v19-73-26]]

^<<v19-73-26,26>>^ My organism and my heart have failed.
God is the rock of my heart and my share to time indefinite.

[[v19-73-27]]

^<<v19-73-27,27>>^ For, look! the very ones keeping away from you will perish.
You will certainly silence every one immorally leaving you.

[[v19-73-28]]

^<<v19-73-28,28>>^ But as for me, the drawing near to God is good for me.
In the Sovereign Lord Jehovah I have placed my refuge,
To declare all your works.^&#42;1^

[NOTE]
====
. LXXVg add: “in the gates of the daughter of Zion.”
====

'''

xref:019-psalm/019-psalm-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-psalm/019-psalm-074.adoc#v19-74-0[Próximo Capítulo &#62;]