include::./index.adoc[]

[[v19-103-0]]
=== Psalms, 103
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_Of David._

[[v19-103-1]]

^<<v19-103-1,1>>^ Bless Jehovah,^&#42;1^ O my soul,
Even everything within me, his holy name.

[NOTE]
====
. See App 1C §8.
====

[[v19-103-2]]

^<<v19-103-2,2>>^ Bless Jehovah,^&#42;1^ O my soul,
And do not forget all his doings,

[NOTE]
====
. See App 1C §8.
====

[[v19-103-3]]

^<<v19-103-3,3>>^ Him who is forgiving all your error,
Who is healing all your maladies,

[[v19-103-4]]

^<<v19-103-4,4>>^ Who is reclaiming your life from the very pit,
Who is crowning you with loving-kindness and mercies,

[[v19-103-5]]

^<<v19-103-5,5>>^ Who is satisfying your lifetime with what is good;
Your youth keeps renewing itself just like that of an eagle.

[[v19-103-6]]

^<<v19-103-6,6>>^ Jehovah^&#42;1^ is executing acts of righteousness^&#42;2^
And judicial decisions for all those being defrauded.

[NOTE]
====
. See App 1C §8.
. Or, “righteousnesses,” M; LXX, “charitable acts.”
====

[[v19-103-7]]

^<<v19-103-7,7>>^ He made known his ways to Moses,
His dealings even to the sons of Israel.

[[v19-103-8]]

^<<v19-103-8,8>>^ Jehovah^&#42;1^ is merciful and gracious,
Slow to anger and abundant in loving-kindness.

[NOTE]
====
. See App 1C §8.
====

[[v19-103-9]]

^<<v19-103-9,9>>^ He will not for all time keep finding fault,
Neither will he to time indefinite keep resentful.

[[v19-103-10]]

^<<v19-103-10,10>>^ He has not done to us even according to our sins;
Nor according to our errors has he brought upon us what we deserve.

[[v19-103-11]]

^<<v19-103-11,11>>^ For as the heavens are higher than the earth,
His loving-kindness is superior toward those fearing him.

[[v19-103-12]]

^<<v19-103-12,12>>^ As far off as the sunrise is from the sunset,
So far off from us he has put our transgressions.

[[v19-103-13]]

^<<v19-103-13,13>>^ As a father shows mercy to his sons,
Jehovah has shown mercy to those fearing him.

[[v19-103-14]]

^<<v19-103-14,14>>^ For he himself well knows the formation of us,
Remembering that we are dust.

[[v19-103-15]]

^<<v19-103-15,15>>^ As for mortal man,^&#42;1^ his days are like those of green grass;
Like a blossom of the field is the way he blossoms forth.

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
====

[[v19-103-16]]

^<<v19-103-16,16>>^ For a mere wind has to pass over it, and it is no more;
And its place will acknowledge it no further.

[[v19-103-17]]

^<<v19-103-17,17>>^ But the loving-kindness^&#42;1^ of Jehovah is from time indefinite even to time indefinite
Toward those fearing him,
And his righteousness to the sons of sons,

[NOTE]
====
. Or, “loyal love.”
====

[[v19-103-18]]

^<<v19-103-18,18>>^ Toward those keeping his covenant
And toward those remembering his orders so as to carry them out.

[[v19-103-19]]

^<<v19-103-19,19>>^ Jehovah himself has firmly established his throne in the very heavens;
And over everything his own kingship has held domination.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bless Jehovah, O YOU angels of his, mighty in power, carrying out his word,
By listening to the voice of his word.

[[v19-103-21]]

^<<v19-103-21,21>>^ Bless Jehovah, all YOU armies of his,
You ministers of his, doing his will.^&#42;1^

[NOTE]
====
. Or, “pleasure.”
====

[[v19-103-22]]

^<<v19-103-22,22>>^ Bless Jehovah, all YOU his works,
In all places of his domination.^&#42;1^
Bless Jehovah, O my soul.

[NOTE]
====
. Or, “his dominion (sovereignty).” Heb., mem·shal·tohʹ. See 1Ch 29:12 ftn.
====

'''

xref:019-psalm/019-psalm-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-psalm/019-psalm-104.adoc#v19-104-0[Próximo Capítulo &#62;]