include::./index.adoc[]

[[v19-35-0]]
=== Psalms, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_Of David._

[[v19-35-1]]

^<<v19-35-1,1>>^ Do conduct my case, O Jehovah,^&#42;1^ against my opponents;
War against those warring against me.

[NOTE]
====
. See App 1C §10.
====

[[v19-35-2]]

^<<v19-35-2,2>>^ Take hold of buckler and large shield,
And do rise up in assistance of me,

[[v19-35-3]]

^<<v19-35-3,3>>^ And draw spear and double ax to meet those pursuing me.
Say to my soul: “I am your salvation.”

[[v19-35-4]]

^<<v19-35-4,4>>^ May those be shamed and humiliated who are hunting for my soul.
May those be turned back and be abashed who are scheming calamity for me.

[[v19-35-5]]

^<<v19-35-5,5>>^ May they become like chaff before the wind,
And let Jehovah’s angel be pushing &#91;them&#93; along.

[[v19-35-6]]

^<<v19-35-6,6>>^ Let their way become darkness and slippery places,
And let Jehovah’s angel be pursuing them.

[[v19-35-7]]

^<<v19-35-7,7>>^ For without cause they have hid for me their netted pit;
Without cause they have dug it for my soul.^&#42;1^

[NOTE]
====
. “For my soul.” Heb., lenaph·shiʹ; Gr., psy·khenʹ; Lat., aʹni·mam. See App 4A.
====

[[v19-35-8]]

^<<v19-35-8,8>>^ Let ruin come upon him without his knowing,
And let his own net that he hid catch him;
With ruin let him fall into it.

[[v19-35-9]]

^<<v19-35-9,9>>^ But let my own soul be joyful in Jehovah;
Let it exult in his salvation.

[[v19-35-10]]

^<<v19-35-10,10>>^ Let all my bones themselves say:
“O Jehovah, who is there like you,
Delivering the afflicted one from one stronger than he is,
And the afflicted and poor one from the one robbing him?”

[[v19-35-11]]

^<<v19-35-11,11>>^ Violent witnesses rise up;
What I have not known they ask me.

[[v19-35-12]]

^<<v19-35-12,12>>^ They reward me with bad for good,
Bereavement to my soul.

[[v19-35-13]]

^<<v19-35-13,13>>^ As for me, when they became ill, my clothing was sackcloth,
With fasting I afflicted my soul,
And upon my bosom my own prayer would return.

[[v19-35-14]]

^<<v19-35-14,14>>^ As for a companion, as for a brother of mine,
I walked about like one mourning for a mother.
Saddened, I bowed down.

[[v19-35-15]]

^<<v19-35-15,15>>^ But at my limping they rejoiced and gathered together;
They gathered together against me,
Striking &#91;me&#93; down when I did not know it;
They ripped &#91;me&#93; to pieces and did not keep silent.

[[v19-35-16]]

^<<v19-35-16,16>>^ Among the apostate mockers for a cake^&#42;1^
There was a grinding^&#42;2^ of their teeth even against me.

[NOTE]
====
. “The apostate mockers for a cake,” that is, ungodly buffoons.
. “There was a grinding.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v19-35-17]]

^<<v19-35-17,17>>^ O Jehovah,^&#42;1^ how long will you keep seeing &#91;it&#93;?
Do bring back my soul from their ravages,
Even my only one^&#42;2^ from the maned young lions.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
. “My only one,” fem., referring to “my soul,” fem.
====

[[v19-35-18]]

^<<v19-35-18,18>>^ I will laud you in the big congregation;^&#42;1^
Among a numerous people I shall praise you.

[NOTE]
====
. “In the big congregation.” Heb., beqa·halʹ rav; Gr., ek·kle·siʹai; Lat., ec·cleʹsi·a.
====

[[v19-35-19]]

^<<v19-35-19,19>>^ O may those who for no reason are my enemies not rejoice over me;
As for those hating me without cause, let them not wink the eye.

[[v19-35-20]]

^<<v19-35-20,20>>^ For it is not peace that they speak;
But against the quiet ones of the earth
Things of deception they keep scheming.

[[v19-35-21]]

^<<v19-35-21,21>>^ And they open wide their mouth even against me.
They have said: “Aha! Aha! our eye has seen &#91;it&#93;.”

[[v19-35-22]]

^<<v19-35-22,22>>^ You have seen, O Jehovah.^&#42;1^ Do not keep silent.^&#42;2^
O Jehovah,^&#42;3^ do not keep yourself far from me.

[NOTE]
====
. See App 1C §10.
. Or, “Do not be deaf.”
. See vs 17 ftn, “Jehovah.”
====

[[v19-35-23]]

^<<v19-35-23,23>>^ Do arouse yourself^&#42;1^ and awake to my judgment,
O my God, even Jehovah,^&#42;2^ to my case at law.

[NOTE]
====
. LXX adds “O Jehovah.”
. See vs 17 ftn, “Jehovah.”
====

[[v19-35-24]]

^<<v19-35-24,24>>^ Judge me according to your righteousness, O Jehovah^&#42;1^ my God,
And may they not rejoice over me.

[NOTE]
====
. See App 1C §10.
====

[[v19-35-25]]

^<<v19-35-25,25>>^ O may they not say in their heart: “Aha, our soul!”^&#42;1^
May they not say: “We have swallowed him up.”

[NOTE]
====
. That is, ‘What our souls wanted!’
====

[[v19-35-26]]

^<<v19-35-26,26>>^ Let those be ashamed and abashed all together
Who are joyful at my calamity.
Let those be clothed with shame and humiliation who are assuming great airs against me.

[[v19-35-27]]

^<<v19-35-27,27>>^ Let those cry out joyfully and rejoice who are delighting in my righteousness,
And let them say constantly:
“Let Jehovah^&#42;1^ be magnified, who takes delight in the peace of his servant.”

[NOTE]
====
. See App 1C §10.
====

[[v19-35-28]]

^<<v19-35-28,28>>^ And let my own tongue utter in an undertone your righteousness,
All day long your praise.

'''

xref:019-psalm/019-psalm-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-psalm/019-psalm-036.adoc#v19-36-0[Próximo Capítulo &#62;]