include::./index.adoc[]

[[v19-81-0]]
=== Psalms, 81
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director upon the Gitʹtith.^&#42;1^ Of Aʹsaph._

[[v19-81-1]]

^<<v19-81-1,1>>^ O cry out joyfully, YOU people, to God our strength;
Shout in triumph to the God of Jacob.

[[v19-81-2]]

^<<v19-81-2,2>>^ Strike up a melody and take a tambourine,
The pleasant harp together with the stringed instrument.

[[v19-81-3]]

^<<v19-81-3,3>>^ On the new moon, BLOW the horn;^&#42;1^
On the full moon, for the day of our festival.

[NOTE]
====
. Or, “shofar.” Heb., shoh·pharʹ.
====

[[v19-81-4]]

^<<v19-81-4,4>>^ For it is a regulation for Israel,
A judicial decision of the God^&#42;1^ of Jacob.

[NOTE]
====
. “Tents,” by transposing two Heb. letters to correspond with the first half of the vs.
====

[[v19-81-5]]

^<<v19-81-5,5>>^ As a reminder he laid it upon Joseph himself,
When he was going forth over the land of Egypt.
A language^&#42;1^ that I did not know I kept hearing.

[NOTE]
====
. Lit., “lip.” See Ge 11:1 ftn, “Language.”
====

[[v19-81-6]]

^<<v19-81-6,6>>^ “I^&#42;1^ turned aside his shoulder even from &#91;the&#93; burden;
His own hands got to be free even from the basket.

[NOTE]
====
. “I,” MTSy; LXXVg, “He.”
====

[[v19-81-7]]

^<<v19-81-7,7>>^ In distress you called, and I proceeded to rescue you;
I began to answer you in the concealed place of thunder.
I went examining you at the waters of Merʹi·bah. Seʹlah.

[[v19-81-8]]

^<<v19-81-8,8>>^ Hear, O my people, and I will bear witness against you,
O Israel, if you will listen to me.

[[v19-81-9]]

^<<v19-81-9,9>>^ Among you there will prove to be no strange god;^&#42;1^
And you will not bow down to a foreign god.

[NOTE]
====
. “God.” Heb., ʼel.
====

[[v19-81-10]]

^<<v19-81-10,10>>^ I, Jehovah, am your God,^&#42;1^
The One bringing you up out of the land of Egypt.
Open your mouth wide, and I shall fill it.

[NOTE]
====
. Or, “I am Jehovah your God.” Heb., ʼa·no·khiʹ Yehwahʹ ʼElo·heyʹkha.
====

[[v19-81-11]]

^<<v19-81-11,11>>^ But my people has not listened to my voice;
And Israel itself has not showed any willingness toward me.

[[v19-81-12]]

^<<v19-81-12,12>>^ And so I let them go^&#42;1^ in the stubbornness of their heart;
They went walking in their own counsels.

[NOTE]
====
. Lit., “I sent them away.” Compare Ex 5:1, 2.
====

[[v19-81-13]]

^<<v19-81-13,13>>^ O that my people were listening to me,
O that Israel itself would walk in my very ways!

[[v19-81-14]]

^<<v19-81-14,14>>^ Their enemies I would easily subdue,
And against their adversaries I would turn my hand.

[[v19-81-15]]

^<<v19-81-15,15>>^ As for those intensely hating Jehovah, they will come cringing to him,
And their time will prove to be to time indefinite.

[[v19-81-16]]

^<<v19-81-16,16>>^ And he will keep feeding him off the fat of the wheat,
And out of the rock I shall satisfy you with honey itself.”

'''

xref:019-psalm/019-psalm-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-psalm/019-psalm-082.adoc#v19-82-0[Próximo Capítulo &#62;]