include::./index.adoc[]

[[v19-31-0]]
=== Psalms, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. A melody of David._

[[v19-31-1]]

^<<v19-31-1,1>>^ In you, O Jehovah,^&#42;1^ have I taken refuge.
O may I never be ashamed.
In your righteousness provide escape for me.

[NOTE]
====
. See App 1C §10.
====

[[v19-31-2]]

^<<v19-31-2,2>>^ Incline to me your ear.
Deliver me speedily.
Become for me a rocky stronghold,
A house of strongholds to save me.

[[v19-31-3]]

^<<v19-31-3,3>>^ For you are my crag and my stronghold;
And for the sake of your name you will lead me and conduct me.

[[v19-31-4]]

^<<v19-31-4,4>>^ You will bring me out of the net that they have hidden for me,
For you are my fortress.

[[v19-31-5]]

^<<v19-31-5,5>>^ Into your hand I entrust my spirit.
You have redeemed me, O Jehovah^&#42;1^ the God of truth.^&#42;2^

[NOTE]
====
. See App 1C §10.
. “The God of truth.” Or, “the true God.” Heb., ʼEl ʼemethʹ.
====

[[v19-31-6]]

^<<v19-31-6,6>>^ I do hate those paying regard to worthless, vain idols;^&#42;1^
But as for me, in Jehovah^&#42;2^ I do trust.

[NOTE]
====
. Lit., “vanities.”
. See App 1C §10.
====

[[v19-31-7]]

^<<v19-31-7,7>>^ I will be joyful and rejoice in your loving-kindness,^&#42;1^
In that you have seen my affliction;
You have known about the distresses of my soul,

[NOTE]
====
. Or, “loyal love.”
====

[[v19-31-8]]

^<<v19-31-8,8>>^ And you have not surrendered me into the hand of the enemy.
You have made my feet stand in a roomy place.

[[v19-31-9]]

^<<v19-31-9,9>>^ Show me favor, O Jehovah,^&#42;1^ for I am in sore straits.
With vexation my eye has become weak, my soul and my belly.

[NOTE]
====
. See App 1C §10.
====

[[v19-31-10]]

^<<v19-31-10,10>>^ For with grief my life has come to an end,
And my years in sighing.
Because of my error my power has stumbled,
And my very bones have become weak.

[[v19-31-11]]

^<<v19-31-11,11>>^ From the standpoint of all those showing hostility to me I have become a reproach,
And to my neighbors very much so,
And a dread to my acquaintances.
When seeing me out of doors, they have fled from me.

[[v19-31-12]]

^<<v19-31-12,12>>^ Like someone dead &#91;and&#93; not in the heart, I have been forgotten;
I have become like a damaged^&#42;1^ vessel;

[NOTE]
====
. Or, “missing.”
====

[[v19-31-13]]

^<<v19-31-13,13>>^ For I have heard the bad report by many,
Fright being on all sides.
When they mass together as one against me,
It is to take away my soul^&#42;1^ that they do scheme.

[NOTE]
====
. Or, “my life.” Heb., naph·shiʹ; Gr., psy·khenʹ; Lat., aʹni·mam.
====

[[v19-31-14]]

^<<v19-31-14,14>>^ But I—in you I have put my trust, O Jehovah.
I have said: “You are my God.”^&#42;1^

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v19-31-15]]

^<<v19-31-15,15>>^ My times are in your hand.
Deliver me from the hand of my enemies and from those pursuing me.

[[v19-31-16]]

^<<v19-31-16,16>>^ Do cause your face to shine upon your servant.
Save me in your loving-kindness.

[[v19-31-17]]

^<<v19-31-17,17>>^ O Jehovah, may I not be ashamed, for I have called on you.
May the wicked ones be ashamed;
May they keep silent in Sheʹol.

[[v19-31-18]]

^<<v19-31-18,18>>^ May false lips become speechless,
That are speaking against the righteous one, unrestrainedly in haughtiness and contempt.

[[v19-31-19]]

^<<v19-31-19,19>>^ How abundant your goodness is, which you have treasured up for those fearing you!
&#91;Which&#93; you have rendered to those taking refuge in you,
In front of the sons of men.^&#42;1^

[NOTE]
====
. Or, “earthling men.” Heb., ʼa·dhamʹ.
====

[[v19-31-20]]

^<<v19-31-20,20>>^ You will conceal them in the secret place of your person^&#42;1^
From the banding together of men.^&#42;2^
You will hide them in your booth from the quarreling of tongues.

[NOTE]
====
. Lit., “face.” Compare 2Sa 17:11 ftn, “Person.”
. “Men.” Heb., ʼish.
====

[[v19-31-21]]

^<<v19-31-21,21>>^ Blessed be Jehovah,^&#42;1^
For he has rendered wonderful loving-kindness to me in a city under stress.

[NOTE]
====
. See App 1C §10.
====

[[v19-31-22]]

^<<v19-31-22,22>>^ As for me, I said when I became panicky:
“I shall certainly be exterminated from in front of your eyes.”
Surely you have heard the voice of my entreaties when I cried to you for help.

[[v19-31-23]]

^<<v19-31-23,23>>^ O love Jehovah,^&#42;1^ all YOU loyal ones of his.
The faithful ones Jehovah^&#42;2^ is safeguarding,
But he is rewarding exceedingly anyone showing haughtiness.

[NOTE]
====
. See App 1C §10.
. See App 1C §10.
====

[[v19-31-24]]

^<<v19-31-24,24>>^ Be courageous, and may YOUR heart be strong,
All YOU who are waiting for Jehovah.^&#42;1^

[NOTE]
====
. See App 1C §10.
====

'''

xref:019-psalm/019-psalm-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-psalm/019-psalm-032.adoc#v19-32-0[Próximo Capítulo &#62;]