include::./index.adoc[]

[[v19-40-0]]
=== Psalms, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. Of David, a melody._

[[v19-40-1]]

^<<v19-40-1,1>>^ I earnestly hoped in Jehovah,
And so he inclined &#91;his ear&#93; to me and heard my cry for help.

[[v19-40-2]]

^<<v19-40-2,2>>^ He also proceeded to bring me up out of a roaring pit,
Out of the mire of &#91;the&#93; sediment.
Then he raised up my feet upon a crag;
He firmly established my steps.

[[v19-40-3]]

^<<v19-40-3,3>>^ Further, he put in my mouth a new song,
Praise to our God.
Many will see &#91;it&#93; and will fear,
And they will trust in Jehovah.

[[v19-40-4]]

^<<v19-40-4,4>>^ Happy is the able-bodied man^&#42;1^ that has put Jehovah as his trust
And that has not turned his face to defiant people,
Nor to those falling away to lies.

[NOTE]
====
. “The able-bodied man.” Heb., hag·geʹver.
====

[[v19-40-5]]

^<<v19-40-5,5>>^ Many things you yourself have done,
O Jehovah my God, even your wonderful works and your thoughts toward us;
There is none to be compared to you.
Were I inclined to tell and speak &#91;of them&#93;,
They have become more numerous than I can recount.

[[v19-40-6]]

^<<v19-40-6,6>>^ Sacrifice and offering you did not delight in;
These ears of mine you opened up.^&#42;1^
Burnt offering and sin offering you did not ask for.

[NOTE]
====
. “Sacrifice and offering you did not want, but you prepared a body for me,” LXXא,A,B. Lit., “ears you excavated for me,” M. Compare Heb 10:5.
====

[[v19-40-7]]

^<<v19-40-7,7>>^ In view of that, I said: “Here I have come,
In the roll of the book it being written about me.

[[v19-40-8]]

^<<v19-40-8,8>>^ To do your will,^&#42;1^ O my God, I have delighted,
And your law is within my inward parts.

[NOTE]
====
. Or, “pleasure.”
====

[[v19-40-9]]

^<<v19-40-9,9>>^ I have told the good news^&#42;1^ of righteousness in the big congregation.^&#42;2^
Look! My lips I do not restrain.
O Jehovah, you yourself know that well.

[NOTE]
====
. “I have told the good news of.” Heb., bis·sarʹti; Gr., eu·eg·ge·li·saʹmen.
. See 35:18 ftn.
====

[[v19-40-10]]

^<<v19-40-10,10>>^ Your righteousness I have not covered over within my heart.
Your faithfulness and your salvation I have declared.
I have not hidden your loving-kindness^&#42;1^ and your trueness in^&#42;2^ the big congregation.”

[NOTE]
====
. Or, “loyal love.”
. “In,” T and many Heb. mss; M, “to”; LXXSyVg, “from.”
====

[[v19-40-11]]

^<<v19-40-11,11>>^ You yourself, O Jehovah, do not restrain your pity from me.
Let your loving-kindness and your trueness themselves constantly safeguard me.

[[v19-40-12]]

^<<v19-40-12,12>>^ For calamities encircled me until there was no numbering of them.
More errors of mine overtook me than I was able to see;
They became more numerous than the hairs of my head,
And my own heart left me.

[[v19-40-13]]

^<<v19-40-13,13>>^ Be pleased, O Jehovah, to deliver me.
O Jehovah, to my assistance do make haste.

[[v19-40-14]]

^<<v19-40-14,14>>^ May those be ashamed and abashed all together
Who are seeking my soul to sweep it away.
May those turn back and be humiliated who are delighting in my calamity.

[[v19-40-15]]

^<<v19-40-15,15>>^ Let those stare in amazement in consequence of their shame
Who are saying to me: “Aha! Aha!”

[[v19-40-16]]

^<<v19-40-16,16>>^ Let those exult and rejoice in you,
All those who are seeking you.
Let those say constantly: “May Jehovah be magnified,”
Those who are loving salvation by you.

[[v19-40-17]]

^<<v19-40-17,17>>^ But I am afflicted and poor.
Jehovah^&#42;1^ himself takes account of me.
You are my assistance and the Provider of escape for me.
O my God, do not be too late.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

'''

xref:019-psalm/019-psalm-039.adoc#v19-39-0[&#60; Capítulo Anterior] | <<v19-40-0,Topo>> | xref:019-psalm/019-psalm-041.adoc#v19-41-0[Próximo Capítulo &#62;]