include::./index.adoc[]

[[v19-104-0]]
=== Psalms, 104
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-104-1]]

^<<v19-104-1,1>>^ Bless Jehovah, O my soul.
O Jehovah my God, you have proved very great.
With dignity and splendor you have clothed yourself,

[[v19-104-2]]

^<<v19-104-2,2>>^ Enwrapping yourself with light as with a garment,
Stretching out the heavens like a tent cloth,

[[v19-104-3]]

^<<v19-104-3,3>>^ The One building his upper chambers with beams in the very waters,
Making the clouds his chariot,
Walking upon the wings of the wind,

[[v19-104-4]]

^<<v19-104-4,4>>^ Making his angels spirits,^&#42;1^
His ministers a devouring fire.

[NOTE]
====
. Or, “winds.” Heb., ru·chohthʹ, pl. Vs 3 contains “wind” (ruʹach), sing.
====

[[v19-104-5]]

^<<v19-104-5,5>>^ He has founded the earth upon its established places;
It will not be made to totter to time indefinite, or forever.

[[v19-104-6]]

^<<v19-104-6,6>>^ With a watery deep^&#42;1^ just like a garment you covered it.
The waters were standing above the very mountains.

[NOTE]
====
. Or, “surging waters.” Heb., tehohmʹ; LXXVg, “abyss.” See Ge 1:2 ftn, “Deep.”
====

[[v19-104-7]]

^<<v19-104-7,7>>^ At your rebuke they began to flee;
At the sound of your thunder they were sent running in panic—

[[v19-104-8]]

^<<v19-104-8,8>>^ Mountains proceeded to ascend,
Valley plains proceeded to descend—
To the place that you have founded for them.

[[v19-104-9]]

^<<v19-104-9,9>>^ A boundary you set, beyond which they should not pass,
That they should not again cover the earth.

[[v19-104-10]]

^<<v19-104-10,10>>^ He is sending springs into the torrent valleys;
Between the mountains they keep going on.

[[v19-104-11]]

^<<v19-104-11,11>>^ They continually give drink to all the wild beasts of the open field;
The zebras regularly quench their thirst.

[[v19-104-12]]

^<<v19-104-12,12>>^ Above them roost the flying creatures of the heavens;
From among the thick foliage they keep giving forth sound.

[[v19-104-13]]

^<<v19-104-13,13>>^ He is watering the mountains from his upper chambers.
With the fruitage^&#42;1^ of your works the earth is satisfied.

[NOTE]
====
. Or, “With the moisture,” by a correction of M.
====

[[v19-104-14]]

^<<v19-104-14,14>>^ He is making green grass sprout for the beasts,
And vegetation for the service of mankind,^&#42;1^
To cause food^&#42;2^ to go forth from the earth,

[NOTE]
====
. Lit., “the earthling man.” Heb., ha·ʼa·dhamʹ.
. Lit., “bread.”
====

[[v19-104-15]]

^<<v19-104-15,15>>^ And wine that makes the heart of mortal man^&#42;1^ rejoice,
To make the face shine with oil,
And bread that sustains the very heart of mortal man.

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
====

[[v19-104-16]]

^<<v19-104-16,16>>^ The trees of Jehovah are satisfied,
The cedars of Lebʹa·non that he planted,

[[v19-104-17]]

^<<v19-104-17,17>>^ Where the birds themselves make nests.
As for the stork, the juniper trees are its house.

[[v19-104-18]]

^<<v19-104-18,18>>^ The high mountains are for the mountain goats;
The crags are a refuge for the rock badgers.

[[v19-104-19]]

^<<v19-104-19,19>>^ He has made the moon for appointed times;
The sun itself knows well where it sets.

[[v19-104-20]]

^<<v19-104-20,20>>^ You cause darkness, that it may become night;
In it all the wild animals of the forest move forth.

[[v19-104-21]]

^<<v19-104-21,21>>^ The maned young lions are roaring for the prey
And for seeking their food from God^&#42;1^ himself.

[NOTE]
====
. “From God.” Heb., me·ʼElʹ.
====

[[v19-104-22]]

^<<v19-104-22,22>>^ The sun begins to shine—they withdraw
And they lie down in their own hiding places.^&#42;1^

[NOTE]
====
. Or, “dwellings.”
====

[[v19-104-23]]

^<<v19-104-23,23>>^ Man^&#42;1^ goes forth to his activity
And to his service until evening.

[NOTE]
====
. Or, “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v19-104-24]]

^<<v19-104-24,24>>^ How many your works are, O Jehovah!
All of them in wisdom you have made.
The earth is full of your productions.

[[v19-104-25]]

^<<v19-104-25,25>>^ As for this sea so great and wide,^&#42;1^
There there are moving things without number,
Living creatures, small as well as great.

[NOTE]
====
. Lit., “wide on both sides (hands),” that is, spacious.
====

[[v19-104-26]]

^<<v19-104-26,26>>^ There the ships go;
As for Le·viʹa·than,^&#42;1^ him you have formed to play about in it.

[NOTE]
====
. “Leviathan.” Heb., liw·ya·thanʹ; LXXVg, “the dragon (serpent).”
====

[[v19-104-27]]

^<<v19-104-27,27>>^ All of them—for you they keep waiting
To give &#91;them&#93; their food in its season.

[[v19-104-28]]

^<<v19-104-28,28>>^ What you give them they pick up.
You open your hand—they get satisfied with good things.

[[v19-104-29]]

^<<v19-104-29,29>>^ If you conceal your face, they get disturbed.
If you take away their spirit,^&#42;1^ they expire,
And back to their dust they go.

[NOTE]
====
. “Their spirit (breath).” Heb., ru·chamʹ; Gr., pneuʹma; Lat., spiʹri·tum.
====

[[v19-104-30]]

^<<v19-104-30,30>>^ If you send forth your spirit, they are created;
And you make the face of the ground new.

[[v19-104-31]]

^<<v19-104-31,31>>^ The glory of Jehovah will prove to be to time indefinite.
Jehovah will rejoice in his works.

[[v19-104-32]]

^<<v19-104-32,32>>^ He is looking at the earth, and it trembles;
He touches the mountains, and they smoke.

[[v19-104-33]]

^<<v19-104-33,33>>^ I will sing to Jehovah throughout my life;
I will make melody to my God as long as I am.

[[v19-104-34]]

^<<v19-104-34,34>>^ Let my musing about him be pleasurable.
I, for my part, shall rejoice in Jehovah.

[[v19-104-35]]

^<<v19-104-35,35>>^ The sinners will be finished off from the earth;
And as for the wicked, they will be no longer.
Bless Jehovah, O my soul. Praise Jah,^&#42;1^ YOU people!^&#42;2^

[NOTE]
====
. “Jah.” Heb., Yah, an abbreviated form of the divine name. Compare 68:4 ftn.
. “Praise Jah, you people!” Heb., Ha·lelu-Yahʹ; Gr., Al·le·louʹi·a; Lat., Al·le·luʹia. See App 1D.
====

'''

xref:019-psalm/019-psalm-103.adoc#v19-103-0[&#60; Capítulo Anterior] | <<v19-104-0,Topo>> | xref:019-psalm/019-psalm-105.adoc#v19-105-0[Próximo Capítulo &#62;]