include::./index.adoc[]

[[v19-23-0]]
=== Psalms, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A melody of David._

[[v19-23-1]]

^<<v19-23-1,1>>^ Jehovah is my Shepherd.
I shall lack nothing.

[[v19-23-2]]

^<<v19-23-2,2>>^ In grassy pastures he makes me lie down;
By well-watered resting-places he conducts me.

[[v19-23-3]]

^<<v19-23-3,3>>^ My soul he refreshes.
He leads me in the tracks of righteousness for his name’s sake.

[[v19-23-4]]

^<<v19-23-4,4>>^ Even though I walk in the valley of deep shadow,^&#42;1^
I fear nothing bad,
For you are with me;
Your rod and your staff are the things that comfort me.

[NOTE]
====
. Or, “valley of death shadow.”
====

[[v19-23-5]]

^<<v19-23-5,5>>^ You arrange before me a table in front of those showing hostility to me.
With oil you have greased my head;
My cup is well filled.^&#42;1^

[NOTE]
====
. Lit., “is saturation itself.”
====

[[v19-23-6]]

^<<v19-23-6,6>>^ Surely goodness and loving-kindness^&#42;1^ themselves will pursue me all the days of my life;
And I will dwell^&#42;2^ in the house of Jehovah to the length of days.

[NOTE]
====
. Or, “loyal love.”
. “I will dwell,” TSyVg.
====

'''

xref:019-psalm/019-psalm-022.adoc#v19-22-0[&#60; Capítulo Anterior] | <<v19-23-0,Topo>> | xref:019-psalm/019-psalm-024.adoc#v19-24-0[Próximo Capítulo &#62;]