include::./index.adoc[]

[[v19-72-0]]
=== Psalms, 72
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_Regarding Solomon._

[[v19-72-1]]

^<<v19-72-1,1>>^ O God, give your own judicial decisions to the king,
And your righteousness to the son of the king.

[[v19-72-2]]

^<<v19-72-2,2>>^ May he plead the cause of your people with righteousness
And of your afflicted ones with judicial decision.

[[v19-72-3]]

^<<v19-72-3,3>>^ Let the mountains carry peace to the people,
Also the hills, through righteousness.

[[v19-72-4]]

^<<v19-72-4,4>>^ Let him judge the afflicted ones of the people,
Let him save the sons of the poor one,
And let him crush the defrauder.

[[v19-72-5]]

^<<v19-72-5,5>>^ They will^&#42;1^ fear you as long as there is a sun,^&#42;2^
And before the moon for generation after generation.^&#42;3^

[NOTE]
====
. Or, “Let them.”
. Lit., “fear you with the sun.”
. Lit., “generation of generations.”
====

[[v19-72-6]]

^<<v19-72-6,6>>^ He will descend like the rain upon the mown grass,
Like copious showers that wet the earth.^&#42;1^

[NOTE]
====
. Lit., “a wetting (moistening) of the earth.”
====

[[v19-72-7]]

^<<v19-72-7,7>>^ In his days the righteous one^&#42;1^ will sprout,
And the abundance of peace until the moon is no more.^&#42;2^

[NOTE]
====
. “The righteous one,” M; LXXSyVg and three Heb. mss, “righteousness.”
. According to M; T, “until the servants of the moon are destroyed.”
====

[[v19-72-8]]

^<<v19-72-8,8>>^ And he will have subjects from sea to sea
And from the River^&#42;1^ to the ends of the earth.

[NOTE]
====
. “River,” MLXXSyVg; T, “Euphrates.”
====

[[v19-72-9]]

^<<v19-72-9,9>>^ Before him the inhabitants of waterless regions^&#42;1^ will bow down,
And his very enemies will lick the dust itself.

[NOTE]
====
. Or, “the demons.”
====

[[v19-72-10]]

^<<v19-72-10,10>>^ The kings of Tarʹshish and of the islands^&#42;1^—
Tribute they will pay.
The kings of Sheʹba and of Seʹba—
A gift they will present.

[NOTE]
====
. Or, “coastlands.”
====

[[v19-72-11]]

^<<v19-72-11,11>>^ And to him all the kings will prostrate themselves;
All the nations, for their part, will serve him.

[[v19-72-12]]

^<<v19-72-12,12>>^ For he will deliver the poor one crying for help,
Also the afflicted one and whoever has no helper.

[[v19-72-13]]

^<<v19-72-13,13>>^ He will feel sorry for the lowly one and the poor one,
And the souls of the poor ones he will save.

[[v19-72-14]]

^<<v19-72-14,14>>^ From oppression and from violence he will redeem their soul,
And their blood will be precious in his eyes.

[[v19-72-15]]

^<<v19-72-15,15>>^ And let him live, and to him let some of the gold of Sheʹba be given.
And in his behalf let prayer be made constantly;
All day long let him be blessed.

[[v19-72-16]]

^<<v19-72-16,16>>^ There will come to be plenty of grain on the earth;
On the top of the mountains there will be an overflow.
His fruit will be as in Lebʹa·non,
And those who are from the city will blossom like the vegetation of the earth.

[[v19-72-17]]

^<<v19-72-17,17>>^ Let his name prove to be to time indefinite;
Before the sun let his name have increase,
And by means of him let them bless themselves;
Let all nations pronounce him happy.

[[v19-72-18]]

^<<v19-72-18,18>>^ Blessed be Jehovah God, Israel’s God,
Who alone is doing wonderful works.

[[v19-72-19]]

^<<v19-72-19,19>>^ And blessed be his glorious name to time indefinite,
And let his glory fill the whole earth.
Amen and Amen.^&#42;1^

[NOTE]
====
. See 41:13 ftn.
====

[[v19-72-20]]

^<<v19-72-20,20>>^ The prayers of David, the son of Jesʹse, have come to their end.

'''

xref:019-psalm/019-psalm-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-psalm/019-psalm-073.adoc#v19-73-0[Próximo Capítulo &#62;]