include::./index.adoc[]

[[v19-69-0]]
=== Psalms, 69
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director on The Lilies.^&#42;1^ Of David._

[[v19-69-1]]

^<<v19-69-1,1>>^ Save me, O God, for the waters have come clear to the soul.^&#42;1^

[NOTE]
====
. Or, “life.” Heb., naʹphesh; T(Aram.)­Syr., naph·shaʼ; Gr., psy·khesʹ; Lat., aʹni·mam.
====

[[v19-69-2]]

^<<v19-69-2,2>>^ I have sunk down in deep mire, where there is no standing ground.
I have come into profound waters,
And a flowing stream^&#42;1^ itself has washed me away.

[NOTE]
====
. “And a flowing stream.” Heb., weshib·boʹleth.
====

[[v19-69-3]]

^<<v19-69-3,3>>^ I have become tired by my calling out;
My throat has become hoarse.
My eyes have failed while waiting for my God.

[[v19-69-4]]

^<<v19-69-4,4>>^ Those hating me without a cause have become even more than the hairs of my head.
Those bringing me to silence, being my enemies for no reason, have become numerous.
What I had not taken by robbery I then proceeded to give back.

[[v19-69-5]]

^<<v19-69-5,5>>^ O God, you yourself have come to know my foolishness,
And from you my own guiltiness has not been hidden.

[[v19-69-6]]

^<<v19-69-6,6>>^ O may those hoping in you not be ashamed because of me,
O Sovereign Lord, Jehovah of armies.
O may those seeking you not be humiliated because of me,
O God of Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ For on your account I have borne reproach,
Humiliation has covered my face.

[[v19-69-8]]

^<<v19-69-8,8>>^ I have become one estranged to my brothers,
And a foreigner to the sons of my mother.

[[v19-69-9]]

^<<v19-69-9,9>>^ For sheer zeal for your house has eaten me up,
And the very reproaches of those reproaching you have fallen upon me.

[[v19-69-10]]

^<<v19-69-10,10>>^ And I proceeded to weep with the fasting of my soul,
But it came to be for reproaches to me.

[[v19-69-11]]

^<<v19-69-11,11>>^ When I made sackcloth my clothing,
Then I became to them a proverbial saying.

[[v19-69-12]]

^<<v19-69-12,12>>^ Those sitting in the gate began concerning themselves about me,
And &#91;I was&#93; the subject of the songs of drinkers of intoxicating liquor.

[[v19-69-13]]

^<<v19-69-13,13>>^ But as for me, my prayer was to you, O Jehovah,^&#42;1^
At an acceptable time, O God.
In the abundance of your loving-kindness answer me with the truth of salvation by you.

[NOTE]
====
. “Jehovah.” Heb., Yehwahʹ; Fragment SymP. Vindob. G. 39777, the Tetragrammaton in archaic Heb. characters. See App 1C §9.
====

[[v19-69-14]]

^<<v19-69-14,14>>^ Deliver me from the mire, that I may not sink down.
O may I be delivered from those hating me and from the deep waters.

[[v19-69-15]]

^<<v19-69-15,15>>^ O may not the flowing stream of waters wash me away,
Nor the depth swallow me up,
Nor the well close its mouth over me.

[[v19-69-16]]

^<<v19-69-16,16>>^ Answer me, O Jehovah, for your loving-kindness is good.
According to the multitude of your mercies turn to me,

[[v19-69-17]]

^<<v19-69-17,17>>^ And do not conceal your face from your servant.
Because I am in sore straits, answer me quickly.

[[v19-69-18]]

^<<v19-69-18,18>>^ Do come near to my soul, reclaim it;
On account of my enemies redeem me.

[[v19-69-19]]

^<<v19-69-19,19>>^ You yourself have come to know my reproach and my shame and my humiliation.
All those showing hostility to me are in front of you.

[[v19-69-20]]

^<<v19-69-20,20>>^ Reproach itself has broken my heart, and &#91;the wound&#93; is incurable.
And I kept hoping for someone to show sympathy, but there was none;
And for comforters, but I found none.

[[v19-69-21]]

^<<v19-69-21,21>>^ But for food^&#42;1^ they gave &#91;me&#93; a poisonous plant,^&#42;2^
And for my thirst they tried to make me drink vinegar.

[NOTE]
====
. Or, “bread of consolation.”
. Or, “they proceeded to put poison.”
====

[[v19-69-22]]

^<<v19-69-22,22>>^ Let their table before them become a trap,
And what is for their welfare a snare.

[[v19-69-23]]

^<<v19-69-23,23>>^ Let their eyes become darkened so as not to see;
And cause their very hips to wobble constantly.

[[v19-69-24]]

^<<v19-69-24,24>>^ Pour out upon them your denunciation,
And may your own burning anger overtake them.

[[v19-69-25]]

^<<v19-69-25,25>>^ Let their walled camp become desolate;
In their tents may there come to be no dweller.

[[v19-69-26]]

^<<v19-69-26,26>>^ For the one whom you yourself have struck they have pursued,
And the pains of those pierced by you they keep recounting.

[[v19-69-27]]

^<<v19-69-27,27>>^ Do give error upon their error,
And may they not come into your righteousness.

[[v19-69-28]]

^<<v19-69-28,28>>^ Let them be wiped out of the book of the living ones,^&#42;1^
And with the righteous ones may they not be written in.

[NOTE]
====
. Or, “book of life.”
====

[[v19-69-29]]

^<<v19-69-29,29>>^ But I am afflicted and aching.
May your own salvation, O God, protect me.

[[v19-69-30]]

^<<v19-69-30,30>>^ I will praise the name of God^&#42;1^ with song,
And I will magnify him with thanksgiving.

[NOTE]
====
. “God.” Heb., ʼElo·himʹ. Fragment SymP. Vindob. G. 39777 has here “Jehovah God,” with the Tetragrammaton in archaic Heb. characters. See App 1C §9.
====

[[v19-69-31]]

^<<v19-69-31,31>>^ This will also be more pleasing to Jehovah^&#42;1^ than a bull,
Than a young bull displaying horns, splitting the hoof.

[NOTE]
====
. See App 1C §9.
====

[[v19-69-32]]

^<<v19-69-32,32>>^ The meek ones will certainly see &#91;it&#93;; they will rejoice.
YOU who are seeking God, let YOUR heart also keep alive.

[[v19-69-33]]

^<<v19-69-33,33>>^ For Jehovah is listening to the poor ones,
And he will indeed not despise his very own prisoners.^&#42;1^

[NOTE]
====
. Or, “those of his who are prisoners.”
====

[[v19-69-34]]

^<<v19-69-34,34>>^ Let heaven and earth praise him,
The seas and everything moving about in them.

[[v19-69-35]]

^<<v19-69-35,35>>^ For God himself will save Zion
And will build the cities of Judah;
And they will certainly dwell there and take possession of it.^&#42;1^

[NOTE]
====
. “It,” fem., referring to the land.
====

[[v19-69-36]]

^<<v19-69-36,36>>^ And the offspring^&#42;1^ of his servants themselves will inherit it,
And those loving his name will be the ones to reside in it.

[NOTE]
====
. Lit., “seed.”
====

'''

xref:019-psalm/019-psalm-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-psalm/019-psalm-070.adoc#v19-70-0[Próximo Capítulo &#62;]