include::./index.adoc[]

[[v19-74-0]]
=== Psalms, 74
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_A masʹkil.^&#42;1^ Of Aʹsaph._

[[v19-74-1]]

^<<v19-74-1,1>>^ Why, O God, have you cast off forever?
Why does your anger keep smoking against the flock of your pasturage?

[[v19-74-2]]

^<<v19-74-2,2>>^ Remember your assembly that you acquired long ago,
The tribe that you redeemed as your inheritance,
This Mount Zion in which you have resided.

[[v19-74-3]]

^<<v19-74-3,3>>^ Do lift up your steps to the long-lasting desolations.
Everything the enemy has treated badly in the holy place.

[[v19-74-4]]

^<<v19-74-4,4>>^ Those showing hostility to you have roared in the middle of your meeting place.
They have set their own signs as &#91;the&#93; signs.

[[v19-74-5]]

^<<v19-74-5,5>>^ One is notorious in being like him that brings up axes on high against a thicket of trees.

[[v19-74-6]]

^<<v19-74-6,6>>^ And now the very engravings of it, one and all, they strike even with hatchet and iron-tipped beams.

[[v19-74-7]]

^<<v19-74-7,7>>^ They have thrust your sanctuary into the fire itself.
They have profaned the tabernacle of your name to the very earth.

[[v19-74-8]]

^<<v19-74-8,8>>^ They, even their offspring, have said together in their own heart:
“All the meeting places of God^&#42;1^ must be burned in the land.”

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v19-74-9]]

^<<v19-74-9,9>>^ Our signs we have not seen; there is no prophet anymore,
And there is no one with us knowing how long.

[[v19-74-10]]

^<<v19-74-10,10>>^ How long, O God, will the adversary keep reproaching?
Will the enemy keep treating your name with disrespect forever?

[[v19-74-11]]

^<<v19-74-11,11>>^ Why do you keep your hand, even your right hand, withdrawn
From the midst of your bosom to make an end &#91;of us&#93;?

[[v19-74-12]]

^<<v19-74-12,12>>^ And yet God is my King from long ago,
The One performing grand salvation in the midst of the earth.

[[v19-74-13]]

^<<v19-74-13,13>>^ You yourself stirred up the sea with your own strength;
You broke the heads of the sea monsters in the waters.

[[v19-74-14]]

^<<v19-74-14,14>>^ You yourself crushed to pieces the heads of Le·viʹa·than.^&#42;1^
You proceeded to give it as food to the people, to those inhabiting the waterless regions.

[NOTE]
====
. “Leviathan,” MSy; T, “the strong ones of Pharaoh”; LXXVg, “the dragon.”
====

[[v19-74-15]]

^<<v19-74-15,15>>^ You were the One that split the spring and the torrent;
You yourself dried up ever-flowing rivers.

[[v19-74-16]]

^<<v19-74-16,16>>^ To you the day belongs; also, to you the night belongs.
You yourself prepared the luminary, even the sun.

[[v19-74-17]]

^<<v19-74-17,17>>^ It was you that set up all the boundaries of the earth;
Summer and winter—you yourself formed them.

[[v19-74-18]]

^<<v19-74-18,18>>^ Remember this: The enemy himself has reproached, O Jehovah,
And a senseless people have treated your name with disrespect.

[[v19-74-19]]

^<<v19-74-19,19>>^ Do not give to the wild beast the soul of your turtledove.
Do not forget the very life of your afflicted ones forever.

[[v19-74-20]]

^<<v19-74-20,20>>^ Take a look at the covenant,
For the dark places of the earth have become full of the abodes of violence.

[[v19-74-21]]

^<<v19-74-21,21>>^ O may the crushed one not return humiliated.
May the afflicted one and the poor one praise your name.

[[v19-74-22]]

^<<v19-74-22,22>>^ Do arise, O God, do conduct your own case at law.
Remember your reproach from the senseless one all day long.

[[v19-74-23]]

^<<v19-74-23,23>>^ Do not forget the voice of those showing hostility to you.
The noise of those rising up against you is ascending constantly.

'''

xref:019-psalm/019-psalm-073.adoc#v19-73-0[&#60; Capítulo Anterior] | <<v19-74-0,Topo>> | xref:019-psalm/019-psalm-075.adoc#v19-75-0[Próximo Capítulo &#62;]