include::./index.adoc[]

[[v19-8-0]]
=== Psalms, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director upon the Gitʹtith.^&#42;1^ A melody of David._

[[v19-8-1]]

^<<v19-8-1,1>>^ O Jehovah our Lord,^&#42;1^ how majestic your name is in all the earth,
You whose dignity is recounted^&#42;2^ above the heavens!

[NOTE]
====
. “Our Lord.” Heb., ʼAdho·nehʹnu, pl. of ʼA·dhohnʹ, to denote excellence.
. “You whose dignity is recounted.” TSy, “you who have put (given) your glory”; LXXVgc, “because your magnificence has been lifted up.”
====

[[v19-8-2]]

^<<v19-8-2,2>>^ Out of the mouth of children and sucklings you have founded^&#42;1^ strength,
On account of those showing hostility to you,
So as to make the enemy and the one taking his vengeance desist.

[NOTE]
====
. Or, “corrected,” by a change of one Heb. letter.
====

[[v19-8-3]]

^<<v19-8-3,3>>^ When I see your heavens, the works of your fingers,
The moon and the stars that you have prepared,

[[v19-8-4]]

^<<v19-8-4,4>>^ What is mortal man that you keep him in mind,
And the son of earthling man that you take care of him?

[[v19-8-5]]

^<<v19-8-5,5>>^ You also proceeded to make him a little less than godlike ones,^&#42;1^
And with glory and splendor you then crowned him.

[NOTE]
====
. “Than godlike ones.” Heb., me·ʼelo·himʹ; TLXXSyVg, “angels; messengers.”
====

[[v19-8-6]]

^<<v19-8-6,6>>^ You make him dominate over the works of your hands;
Everything you have put under his feet:

[[v19-8-7]]

^<<v19-8-7,7>>^ Small cattle^&#42;1^ and oxen, all of them,
And also the beasts of the open field,

[NOTE]
====
. “Small cattle,” that is, sheep and goats.
====

[[v19-8-8]]

^<<v19-8-8,8>>^ The birds of heaven and the fish of the sea,
Anything passing through the paths of the seas.

[[v19-8-9]]

^<<v19-8-9,9>>^ O Jehovah our Lord, how majestic your name is in all the earth!

'''

xref:019-psalm/019-psalm-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-psalm/019-psalm-009.adoc#v19-9-0[Próximo Capítulo &#62;]