include::./index.adoc[]

[[v19-148-0]]
=== Psalms, 148
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-148-1]]

^<<v19-148-1,1>>^ Praise Jah, YOU people!^&#42;1^
Praise Jehovah from the heavens,
Praise him in the heights.

[NOTE]
====
. See 104:35 ftns.
====

[[v19-148-2]]

^<<v19-148-2,2>>^ Praise him, all YOU his angels.
Praise him, all YOU his army.

[[v19-148-3]]

^<<v19-148-3,3>>^ Praise him, YOU sun and moon.
Praise him, all YOU stars of light.

[[v19-148-4]]

^<<v19-148-4,4>>^ Praise him, YOU heavens of the heavens,
And YOU waters that are above the heavens.

[[v19-148-5]]

^<<v19-148-5,5>>^ Let them praise the name of Jehovah;
For he himself commanded, and they were created.

[[v19-148-6]]

^<<v19-148-6,6>>^ And he keeps them standing forever, to time indefinite.
A regulation he has given, and it will not pass away.

[[v19-148-7]]

^<<v19-148-7,7>>^ Praise Jehovah from the earth,
YOU sea monsters and all YOU watery deeps,^&#42;1^

[NOTE]
====
. Or, “surging waters.” Heb., teho·mohthʹ, pl. of tehohmʹ. See Ge 1:2 ftn, “Deep.”
====

[[v19-148-8]]

^<<v19-148-8,8>>^ YOU fire and hail, snow and thick smoke,
You tempestuous wind,^&#42;1^ accomplishing his word,

[NOTE]
====
. See 147:18 ftn.
====

[[v19-148-9]]

^<<v19-148-9,9>>^ YOU mountains and all YOU hills,
YOU fruit trees and all YOU cedars,

[[v19-148-10]]

^<<v19-148-10,10>>^ YOU wild animals and all YOU domestic animals,
YOU creeping things and winged birds,

[[v19-148-11]]

^<<v19-148-11,11>>^ YOU kings of the earth and all YOU national groups,
YOU princes and all YOU judges of the earth,

[[v19-148-12]]

^<<v19-148-12,12>>^ YOU young men and also YOU virgins,
YOU old men together with boys.

[[v19-148-13]]

^<<v19-148-13,13>>^ Let them praise the name of Jehovah,
For his name alone is unreachably high.
His dignity is above earth and heaven.

[[v19-148-14]]

^<<v19-148-14,14>>^ And he will exalt the horn of his people,
The praise of all his loyal ones,
Of the sons of Israel, the people near to him.
Praise Jah, YOU people!

'''

xref:019-psalm/019-psalm-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-psalm/019-psalm-149.adoc#v19-149-0[Próximo Capítulo &#62;]