include::./index.adoc[]

[[v19-136-0]]
=== Psalms, 136
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-136-1]]

^<<v19-136-1,1>>^ Give thanks to Jehovah, O YOU people, for he is good:
For his loving-kindness^&#42;1^ is to time indefinite;

[NOTE]
====
. Or, “loyal love.”
====

[[v19-136-2]]

^<<v19-136-2,2>>^ Give thanks to the God of the gods:^&#42;1^
For his loving-kindness is to time indefinite;

[NOTE]
====
. “To the God of the gods.” Heb., lEʼ·lo·hehʹ ha·ʼelo·himʹ; Gr., toi The·oiʹ ton the·onʹ.
====

[[v19-136-3]]

^<<v19-136-3,3>>^ Give thanks to the Lord of the lords:^&#42;1^
For his loving-kindness is to time indefinite;

[NOTE]
====
. “To the Lord of the lords.” Heb., la·ʼAdho·nehʹ (pl. to denote excellence) ha·ʼadho·nimʹ (numerically pl.). Compare Ge 39:2 ftn.
====

[[v19-136-4]]

^<<v19-136-4,4>>^ To the Doer of wonderful, great things by himself:
For his loving-kindness is to time indefinite;

[[v19-136-5]]

^<<v19-136-5,5>>^ To the One making the heavens with understanding:
For his loving-kindness is to time indefinite;

[[v19-136-6]]

^<<v19-136-6,6>>^ To the One laying out^&#42;1^ the earth above the waters:
For his loving-kindness is to time indefinite;

[NOTE]
====
. Or, “spreading out,” as if by beating out.
====

[[v19-136-7]]

^<<v19-136-7,7>>^ To the One making the great lights:
For his loving-kindness is to time indefinite;

[[v19-136-8]]

^<<v19-136-8,8>>^ Even the sun for dominion by day:
For his loving-kindness is to time indefinite;

[[v19-136-9]]

^<<v19-136-9,9>>^ The moon and the stars for combined dominion^&#42;1^ by night:
For his loving-kindness is to time indefinite;

[NOTE]
====
. “For combined dominion.” Lit., “for dominions.”
====

[[v19-136-10]]

^<<v19-136-10,10>>^ To the One striking down Egypt in their firstborn ones:
For his loving-kindness is to time indefinite;

[[v19-136-11]]

^<<v19-136-11,11>>^ And the One bringing Israel out of the midst of them:
For his loving-kindness is to time indefinite;

[[v19-136-12]]

^<<v19-136-12,12>>^ By a strong hand and by an arm stretched out:
For his loving-kindness is to time indefinite;

[[v19-136-13]]

^<<v19-136-13,13>>^ To the One severing the Red Sea into parts:
For his loving-kindness is to time indefinite;

[[v19-136-14]]

^<<v19-136-14,14>>^ And who caused Israel to pass through the middle of it:
For his loving-kindness is to time indefinite;

[[v19-136-15]]

^<<v19-136-15,15>>^ And who shook off Pharʹaoh and his military force into the Red Sea:
For his loving-kindness is to time indefinite;

[[v19-136-16]]

^<<v19-136-16,16>>^ To the One making his people walk through the wilderness:
For his loving-kindness is to time indefinite;

[[v19-136-17]]

^<<v19-136-17,17>>^ To the One striking down great kings:
For his loving-kindness is to time indefinite;

[[v19-136-18]]

^<<v19-136-18,18>>^ And who proceeded to kill majestic kings:
For his loving-kindness is to time indefinite;

[[v19-136-19]]

^<<v19-136-19,19>>^ Even Siʹhon the king of the Amʹor·ites:
For his loving-kindness is to time indefinite;

[[v19-136-20]]

^<<v19-136-20,20>>^ And Og the king of Baʹshan:
For his loving-kindness is to time indefinite;

[[v19-136-21]]

^<<v19-136-21,21>>^ And who gave their land as an inheritance:
For his loving-kindness is to time indefinite;

[[v19-136-22]]

^<<v19-136-22,22>>^ An inheritance to Israel his servant:
For his loving-kindness is to time indefinite;

[[v19-136-23]]

^<<v19-136-23,23>>^ Who during our low condition remembered us:
For his loving-kindness is to time indefinite;

[[v19-136-24]]

^<<v19-136-24,24>>^ And who repeatedly tore us away from our adversaries:
For his loving-kindness is to time indefinite;

[[v19-136-25]]

^<<v19-136-25,25>>^ The One giving food^&#42;1^ to all flesh:
For his loving-kindness is to time indefinite;

[NOTE]
====
. Lit., “bread.”
====

[[v19-136-26]]

^<<v19-136-26,26>>^ Give thanks to the God^&#42;1^ of the heavens:
For his loving-kindness is to time indefinite.

[NOTE]
====
. “To the God of.” Heb., leʼElʹ.
====

'''

xref:019-psalm/019-psalm-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-psalm/019-psalm-137.adoc#v19-137-0[Próximo Capítulo &#62;]