include::./index.adoc[]

[[v19-18-0]]
=== Psalms, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. Of Jehovah’s servant, of David, who spoke to Jehovah the words of this song in the day that Jehovah had delivered him out of the palm of all his enemies and^&#42;1^ out of the hand of Saul. And he proceeded to say:_

[[v19-18-1]]

^<<v19-18-1,1>>^ I shall have affection for you,^&#42;1^ O Jehovah my strength.

[NOTE]
====
. Or, “I shall exalt you,” by a correction of M.
====

[[v19-18-2]]

^<<v19-18-2,2>>^ Jehovah is my crag and my stronghold and the Provider of escape for me.
My God^&#42;1^ is my rock. I shall take refuge in him,^&#42;2^
My shield and my horn of salvation, my secure height.

[NOTE]
====
. “My God.” Heb., ʼE·liʹ.
. Or, “my rock in which I shall take refuge.”
====

[[v19-18-3]]

^<<v19-18-3,3>>^ On the One to be praised, Jehovah, I shall call,
And from my enemies I shall be saved.

[[v19-18-4]]

^<<v19-18-4,4>>^ The ropes of death encircled me;
Flash floods of good-for-nothing &#91;men&#93;^&#42;1^ also kept terrifying me.

[NOTE]
====
. Or, “of no usefulness.” Lit., “of belial.”
====

[[v19-18-5]]

^<<v19-18-5,5>>^ The very ropes of Sheʹol surrounded me;
The snares of death confronted me.

[[v19-18-6]]

^<<v19-18-6,6>>^ In my distress I kept calling upon Jehovah,
And to my God^&#42;1^ I kept crying for help.
Out of his temple he proceeded to hear my voice,
And my own cry before him for help now came into his ears.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v19-18-7]]

^<<v19-18-7,7>>^ And the earth began to shake and rock,
And the foundations of the mountains themselves became agitated,
And they kept shaking back and forth because he had been angered.

[[v19-18-8]]

^<<v19-18-8,8>>^ Smoke went up at his nostrils, and fire itself from his mouth kept devouring;
Coals themselves blazed forth from him.

[[v19-18-9]]

^<<v19-18-9,9>>^ And he proceeded to bend the heavens down and descend.
And thick gloom was beneath his feet.

[[v19-18-10]]

^<<v19-18-10,10>>^ And he came riding upon a cherub and came flying,
And he came darting upon the wings of a spirit.^&#42;1^

[NOTE]
====
. Or, “wings of wind [LXXVg, “winds”].” Heb., kan·pheh-ruʹach.
====

[[v19-18-11]]

^<<v19-18-11,11>>^ He then made darkness his concealment place,
All around him as his booth,
Dark waters,^&#42;1^ thick clouds.

[NOTE]
====
. Lit., “darkness of waters.”
====

[[v19-18-12]]

^<<v19-18-12,12>>^ Out of the brightness in front of him there were his clouds that passed by,
Hail and burning coals of fire.

[[v19-18-13]]

^<<v19-18-13,13>>^ And in the heavens Jehovah began to thunder,
And the Most High himself began to give his voice,
Hail and burning coals of fire.

[[v19-18-14]]

^<<v19-18-14,14>>^ And he kept sending out his arrows, that he might scatter them;
And lightnings he shot out, that he might throw them into confusion.

[[v19-18-15]]

^<<v19-18-15,15>>^ And the streambeds of waters became visible,
And the foundations of the productive land^&#42;1^ became uncovered
From your rebuke, O Jehovah, from the blast^&#42;2^ of the breath^&#42;3^ of your nostrils.^&#42;4^

[NOTE]
====
. “The inhabited earth,” LXX (the same word as in Mt 24:14); Lat., orʹbis ter·raʹrum, “circle of the whole earth.”
. “From the blast.” Heb., min·nish·mathʹ; in Ge 2:7, “breath.”
. “Breath of.” Heb., ruʹach; Gr., pneuʹma·tos; Lat., spiʹri·tus. See Ge 1:2 ftn, “Force.”
. Or, “anger.”
====

[[v19-18-16]]

^<<v19-18-16,16>>^ He was sending^&#42;1^ from on high, he was taking me,
He was drawing me out of great waters.

[NOTE]
====
. Or, “reaching,” that is, sending out his hand.
====

[[v19-18-17]]

^<<v19-18-17,17>>^ He was delivering me from my strong enemy,
And from those hating me; because they were stronger than I was.

[[v19-18-18]]

^<<v19-18-18,18>>^ They kept confronting me in the day of my disaster,
But Jehovah came to be as a support for me.

[[v19-18-19]]

^<<v19-18-19,19>>^ And he proceeded to bring me out into a roomy place;
He was rescuing me, because he had found delight in me.

[[v19-18-20]]

^<<v19-18-20,20>>^ Jehovah rewards me according to my righteousness;
According to the cleanness of my hands he repays me.

[[v19-18-21]]

^<<v19-18-21,21>>^ For I have kept the ways of Jehovah,
And I have not wickedly departed from my God.

[[v19-18-22]]

^<<v19-18-22,22>>^ For all his judicial decisions are in front of me,
And his statutes I shall not remove from myself.

[[v19-18-23]]

^<<v19-18-23,23>>^ And I will prove myself faultless with him,
And I shall keep myself from error on my part.

[[v19-18-24]]

^<<v19-18-24,24>>^ And let Jehovah repay me according to my righteousness,
According to the cleanness of my hands in front of his eyes.

[[v19-18-25]]

^<<v19-18-25,25>>^ With someone loyal^&#42;1^ you will act in loyalty;^&#42;2^
With the faultless, able-bodied man you will deal faultlessly;

[NOTE]
====
. Or, “one of loving-kindness.”
. Or, “act in loving-kindness.”
====

[[v19-18-26]]

^<<v19-18-26,26>>^ With the one keeping clean you will show yourself clean;
And with the crooked one you will show yourself tortuous;^&#42;1^

[NOTE]
====
. “Tortuous,” like a wrestler, according to the Heb. root verb.
====

[[v19-18-27]]

^<<v19-18-27,27>>^ Because the afflicted^&#42;1^ people you yourself will save;
But the haughty eyes you will abase.

[NOTE]
====
. Or, “humble.”
====

[[v19-18-28]]

^<<v19-18-28,28>>^ For you yourself will light my lamp, O Jehovah;
My God^&#42;1^ himself will make my darkness shine.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v19-18-29]]

^<<v19-18-29,29>>^ For by you I can run against a marauder band;
And by my God I can climb a wall.

[[v19-18-30]]

^<<v19-18-30,30>>^ As for the &#91;true&#93; God, perfect is his way;
The saying of Jehovah^&#42;1^ is a refined one.
A shield he is to all those taking refuge in him.

[NOTE]
====
. “Jehovah.” Heb., Yehwahʹ; Gr. ms Ambrosian O 39 sup. See App 1C §10.
====

[[v19-18-31]]

^<<v19-18-31,31>>^ For who is a God^&#42;1^ besides Jehovah?^&#42;2^
And who is a rock except our God?^&#42;3^

[NOTE]
====
. “God.” Heb., ʼElohʹah, sing. of ʼElo·himʹ. See Job 3:4 ftn.
. See App 1C §10.
. “Our God.” Heb., ʼElo·hehʹnu.
====

[[v19-18-32]]

^<<v19-18-32,32>>^ The &#91;true&#93; God is the One girding me closely with vital energy,
And he will grant my way to be perfect,

[[v19-18-33]]

^<<v19-18-33,33>>^ Making my feet like those of the hinds,
And upon places high for me he keeps me standing.

[[v19-18-34]]

^<<v19-18-34,34>>^ He is teaching my hands for warfare,^&#42;1^
And my arms have pressed down a bow of copper.

[NOTE]
====
. Or, “the battle.”
====

[[v19-18-35]]

^<<v19-18-35,35>>^ And you will give me your shield of salvation,
And your own right hand will sustain me,
And your own humility will make me great.^&#42;1^

[NOTE]
====
. Or, “increase.”
====

[[v19-18-36]]

^<<v19-18-36,36>>^ You will make room large enough for my steps under me,
And my ankles will certainly not wobble.

[[v19-18-37]]

^<<v19-18-37,37>>^ I shall pursue my enemies and overtake them;
And I shall not return until they are exterminated.

[[v19-18-38]]

^<<v19-18-38,38>>^ I shall break them in pieces so that they will not be able to rise up;
They will fall under my feet.

[[v19-18-39]]

^<<v19-18-39,39>>^ And you will gird me with vital energy for warfare;
You will make those rising against me collapse under me.

[[v19-18-40]]

^<<v19-18-40,40>>^ And as for my enemies, you will certainly give me the back of &#91;their&#93; neck;^&#42;1^
And as for those hating me intensely, I shall silence them.

[NOTE]
====
. That is, make them flee before me.
====

[[v19-18-41]]

^<<v19-18-41,41>>^ They cry for help, but there is no savior,
To Jehovah,^&#42;1^ but he actually does not answer them.

[NOTE]
====
. See App 1C §10.
====

[[v19-18-42]]

^<<v19-18-42,42>>^ And I shall pound them fine like dust before the wind;
Like the mire of the streets I shall pour them out.

[[v19-18-43]]

^<<v19-18-43,43>>^ You will provide me escape from the faultfinding of the people.
You will appoint me the head of the nations.
A people that I have not known—they will serve me.

[[v19-18-44]]

^<<v19-18-44,44>>^ At mere hearsay they will be obedient to me;
Foreigners^&#42;1^ themselves will come cringing to me.

[NOTE]
====
. Lit., “sons of a foreign (country).”
====

[[v19-18-45]]

^<<v19-18-45,45>>^ Foreigners themselves will fade away,
And they will come quaking out from their bulwarks.

[[v19-18-46]]

^<<v19-18-46,46>>^ Jehovah^&#42;1^ is living, and blessed be my Rock,
And let the God of my salvation be exalted.

[NOTE]
====
. See App 1C §10.
====

[[v19-18-47]]

^<<v19-18-47,47>>^ The &#91;true&#93; God is the Giver of acts of vengeance to me;
And he subdues the peoples under me.

[[v19-18-48]]

^<<v19-18-48,48>>^ He is providing escape for me from my angry enemies;
Above those who rise up against me you will lift me up,
From the man of violence you will deliver me.

[[v19-18-49]]

^<<v19-18-49,49>>^ That is why I shall laud you among the nations, O Jehovah,
And to your name I will make melody.

[[v19-18-50]]

^<<v19-18-50,50>>^ He is doing great acts of salvation for his king
And exercising loving-kindness^&#42;1^ to his anointed one,^&#42;2^
To David and to his seed^&#42;3^ to time indefinite.

[NOTE]
====
. Or, “loyal love.”
. “To his anointed one.” Heb., lim·shi·chohʹ; Gr., khri·stoiʹ; Syr., lam·shi·cheh; Lat., chriʹsto.
. Or, “offspring; posterity.”
====

'''

xref:019-psalm/019-psalm-017.adoc#v19-17-0[&#60; Capítulo Anterior] | <<v19-18-0,Topo>> | xref:019-psalm/019-psalm-019.adoc#v19-19-0[Próximo Capítulo &#62;]