include::./index.adoc[]

[[v19-113-0]]
=== Psalms, 113
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-113-1]]

^<<v19-113-1,1>>^ ^&#42;1^ Praise Jah, YOU people!^&#42;2^
Offer praise,^&#42;3^ O YOU servants of Jehovah,
Praise the name of Jehovah.

[NOTE]
====
. Ps 113 is the first of the six Hallel Psalms. See 114:1 ftn.
. See 104:35 ftns.
. “Offer praise.” Heb., ha·leluʹ.
====

[[v19-113-2]]

^<<v19-113-2,2>>^ May Jehovah’s name become blessed
From now on and to time indefinite.

[[v19-113-3]]

^<<v19-113-3,3>>^ From the rising of the sun until its setting
Jehovah’s name is to be praised.

[[v19-113-4]]

^<<v19-113-4,4>>^ Jehovah has become high above all the nations;
His glory is above the heavens.

[[v19-113-5]]

^<<v19-113-5,5>>^ Who is like Jehovah our God,
Him who is making his dwelling on high?

[[v19-113-6]]

^<<v19-113-6,6>>^ He is condescending to look on heaven and earth,

[[v19-113-7]]

^<<v19-113-7,7>>^ Raising up the lowly one from the very dust;
He exalts the poor one from the ashpit itself,

[[v19-113-8]]

^<<v19-113-8,8>>^ To make &#91;him&#93; sit with nobles,
With the nobles of his people.

[[v19-113-9]]

^<<v19-113-9,9>>^ He is causing the barren woman to dwell in a house
As a joyful mother of sons.
Praise Jah, YOU people!^&#42;1^

[NOTE]
====
. See 104:35 ftns.
====

'''

xref:019-psalm/019-psalm-112.adoc#v19-112-0[&#60; Capítulo Anterior] | <<v19-113-0,Topo>> | xref:019-psalm/019-psalm-114.adoc#v19-114-0[Próximo Capítulo &#62;]