include::./index.adoc[]

[[v19-97-0]]
=== Psalms, 97
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-97-1]]

^<<v19-97-1,1>>^ Jehovah^&#42;1^ himself has become king! Let the earth be joyful.
Let the many islands^&#42;2^ rejoice.

[NOTE]
====
. See App 1C §8.
. Or, “coastlands.”
====

[[v19-97-2]]

^<<v19-97-2,2>>^ Clouds and thick gloom are all around him;
Righteousness and judgment are the established place of his throne.

[[v19-97-3]]

^<<v19-97-3,3>>^ Before him a very fire goes,
And it consumes his adversaries all around.

[[v19-97-4]]

^<<v19-97-4,4>>^ His lightnings lighted up the productive land;
The earth saw and came to be in severe pains.

[[v19-97-5]]

^<<v19-97-5,5>>^ The mountains themselves proceeded to melt just like wax on account of Jehovah,^&#42;1^
On account of the Lord^&#42;2^ of the whole earth.

[NOTE]
====
. See App 1C §8.
. “Lord of.” Heb., ʼAdhohnʹ.
====

[[v19-97-6]]

^<<v19-97-6,6>>^ The heavens have told forth his righteousness,
And all the peoples have seen his glory.

[[v19-97-7]]

^<<v19-97-7,7>>^ Let all those serving^&#42;1^ any carved image be ashamed,
Those who are making their boast in valueless gods.^&#42;2^
Bow down to him, all YOU gods.^&#42;3^

[NOTE]
====
. Or, “those worshiping.” Heb., ʽo·vedhehʹ.
. Or, “in worthless gods.” Heb., ba·ʼeli·limʹ; LXX, “in their idols”; Vg, “in their images (likenesses).”
. “Gods.” Heb., ʼelo·himʹ; LXXSyVg, “his angels.”
====

[[v19-97-8]]

^<<v19-97-8,8>>^ Zion heard and began to rejoice,
And the dependent towns^&#42;1^ of Judah began to be joyful
By reason of your judicial decisions, O Jehovah.

[NOTE]
====
. Lit., “the daughters.”
====

[[v19-97-9]]

^<<v19-97-9,9>>^ For you, O Jehovah,^&#42;1^ are the Most High over all the earth;
You are very high in your ascent over all &#91;other&#93; gods.^&#42;2^

[NOTE]
====
. See App 1C §8.
. “Gods.” Heb., ʼelo·himʹ.
====

[[v19-97-10]]

^<<v19-97-10,10>>^ O YOU lovers of Jehovah,^&#42;1^ hate what is bad.
He is guarding the souls of his loyal ones;
Out of the hand of the wicked ones he delivers them.

[NOTE]
====
. See App 1C §8.
====

[[v19-97-11]]

^<<v19-97-11,11>>^ Light itself has flashed up^&#42;1^ for the righteous one,
And rejoicing even for the ones upright in heart.

[NOTE]
====
. “Has flashed up,” TLXXSyVg and one Heb. ms; M, “is sown.” Compare 112:4 ftn.
====

[[v19-97-12]]

^<<v19-97-12,12>>^ Rejoice in Jehovah,^&#42;1^ O YOU righteous ones,
And give thanks to his holy memorial.^&#42;2^

[NOTE]
====
. See App 1C §8.
. Or, “to the memory of his holiness.”
====

'''

xref:019-psalm/019-psalm-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-psalm/019-psalm-098.adoc#v19-98-0[Próximo Capítulo &#62;]