include::./index.adoc[]

[[v19-58-0]]
=== Psalms, 58
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_To the director. “Do not bring to ruin.” Of David. Mikʹtam.^&#42;1^_

[[v19-58-1]]

^<<v19-58-1,1>>^ &#91;In YOUR&#93; silence can YOU really speak about righteousness itself?
Can YOU judge in uprightness itself, O YOU sons of men?^&#42;1^

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v19-58-2]]

^<<v19-58-2,2>>^ How much, rather, do YOU with the heart practice outright unrighteousness in the earth,
&#91;And&#93; prepare the road for the very violence of YOUR hands!

[[v19-58-3]]

^<<v19-58-3,3>>^ The wicked ones have been perverts from the womb;
They have wandered about from the belly onward;
They are speaking lies.

[[v19-58-4]]

^<<v19-58-4,4>>^ The venom of theirs is like the venom of the serpent,
Deaf like the cobra that stops up its ear,

[[v19-58-5]]

^<<v19-58-5,5>>^ That will not listen to the voice of charmers,
Though someone wise is binding with spells.^&#42;1^

[NOTE]
====
. See App 7A regarding cobras responding to sound.
====

[[v19-58-6]]

^<<v19-58-6,6>>^ O God, knock out their teeth in their mouth.
Break down the very jawbones of maned young lions, O Jehovah.

[[v19-58-7]]

^<<v19-58-7,7>>^ May they dissolve as into waters that go their way;
May he bend &#91;the bow for&#93; his arrows as they collapse.

[[v19-58-8]]

^<<v19-58-8,8>>^ Like a snail melting away he walks;^&#42;1^
Like a miscarriage of a woman they will certainly not behold the sun.

[NOTE]
====
. Or, “leaving a slimy track.”
====

[[v19-58-9]]

^<<v19-58-9,9>>^ Before YOUR pots feel the &#91;kindled&#93; bramble,
The live green as well as the burning, he will carry them off as a stormy wind.

[[v19-58-10]]

^<<v19-58-10,10>>^ The righteous one will rejoice because he has beheld the vengeance.
His steps he will bathe in the blood of the wicked one.

[[v19-58-11]]

^<<v19-58-11,11>>^ And mankind will say: “Surely there is fruitage for the righteous one.
Surely there exists a God that is judging^&#42;1^ in the earth.”

[NOTE]
====
. “That is judging.” Heb., sho·phetimʹ, pl. to agree with ʼElo·himʹ, “God,” which is pl. to denote excellence and grandeur; LXXSyVg make the participle sing., “that is judging them.”
====

'''

xref:019-psalm/019-psalm-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-psalm/019-psalm-059.adoc#v19-59-0[Próximo Capítulo &#62;]