include::./index.adoc[]

[[v19-106-0]]
=== Psalms, 106
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v19-106-1]]

^<<v19-106-1,1>>^ Praise Jah, YOU people!^&#42;1^
Give thanks to Jehovah, for he is good;
For his loving-kindness^&#42;2^ is to time indefinite.

[NOTE]
====
. See 104:35 ftns.
. Or, “loyal love.”
====

[[v19-106-2]]

^<<v19-106-2,2>>^ Who can utter the mighty performances of Jehovah,
&#91;Or&#93; can make all his praise to be heard?

[[v19-106-3]]

^<<v19-106-3,3>>^ Happy are those observing justice,
Doing^&#42;1^ righteousness all the time.

[NOTE]
====
. “Doing,” pl., TLXXSyVg; M, “anyone doing.”
====

[[v19-106-4]]

^<<v19-106-4,4>>^ Remember me, O Jehovah, with the goodwill toward your people.
Take care of me with your salvation,

[[v19-106-5]]

^<<v19-106-5,5>>^ That I may see the goodness to your chosen ones,
That I may rejoice with the rejoicing of your nation,
That I may make my boast with your inheritance.

[[v19-106-6]]

^<<v19-106-6,6>>^ We have sinned just the same as our forefathers;
We have done wrong; we have acted wickedly.

[[v19-106-7]]

^<<v19-106-7,7>>^ As for our forefathers in Egypt,
They did not show any insight into your wonderful works.
They did not remember the abundance of your grand loving-kindness,
But they behaved rebelliously at the sea, by the Red Sea.

[[v19-106-8]]

^<<v19-106-8,8>>^ And he proceeded to save them for the sake of his name,
So as to make his mightiness known.

[[v19-106-9]]

^<<v19-106-9,9>>^ Accordingly he rebuked the Red Sea, and it was gradually dried up;
And he went walking them through the watery deep^&#42;1^ as through the wilderness;

[NOTE]
====
. Or, “through the surging waters.” Heb., bat·teho·mohthʹ, pl. of tehohmʹ; LXXVg, “abyss(es).” See Ge 1:2 ftn, “Deep.”
====

[[v19-106-10]]

^<<v19-106-10,10>>^ And so he saved them from the hand of the hater
And reclaimed them from the hand of the enemy.

[[v19-106-11]]

^<<v19-106-11,11>>^ And the waters came covering their adversaries;
Not one of them was left.

[[v19-106-12]]

^<<v19-106-12,12>>^ Then they had faith in his word;
They began to sing his praise.

[[v19-106-13]]

^<<v19-106-13,13>>^ Quickly they forgot his works;
They did not wait for his counsel.

[[v19-106-14]]

^<<v19-106-14,14>>^ But they showed their selfish desire in the wilderness
And went putting God^&#42;1^ to the proof in the desert.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v19-106-15]]

^<<v19-106-15,15>>^ And he proceeded to give them their request
And to send a wasting disease^&#42;1^ into their soul.

[NOTE]
====
. Or, “emaciation.” Heb., ra·zohnʹ; T, “leanness”; LXXVg, “satiety; surfeit.”
====

[[v19-106-16]]

^<<v19-106-16,16>>^ And they began to envy Moses in the camp,
Even Aaron the holy one of Jehovah.

[[v19-106-17]]

^<<v19-106-17,17>>^ The earth then opened up and swallowed down Daʹthan,
And covered over the assembly of A·biʹram.

[[v19-106-18]]

^<<v19-106-18,18>>^ And a fire went burning among their assembly;
A flame itself went devouring the wicked ones.

[[v19-106-19]]

^<<v19-106-19,19>>^ Furthermore, they made a calf in Hoʹreb
And bowed down to a molten image,

[[v19-106-20]]

^<<v19-106-20,20>>^ So that they exchanged my glory^&#42;1^
For a representation of a bull, an eater of vegetation.

[NOTE]
====
. “My glory.” M, “their glory.” One of the Eighteen Emendations of the Sopherim, who changed the reading because the expression “my glory” was thought to be derogatory to God. LXXmssVgmss, “his glory.” See App 2B.
====

[[v19-106-21]]

^<<v19-106-21,21>>^ They forgot God their Savior,^&#42;1^
The Doer of great things in Egypt,

[NOTE]
====
. “God their Savior.” Heb., ʼEl Moh·shi·ʽamʹ.
====

[[v19-106-22]]

^<<v19-106-22,22>>^ Wonderful works in the land of Ham,
Fear-inspiring things at the Red Sea.

[[v19-106-23]]

^<<v19-106-23,23>>^ And he was about to say to annihilate them,
If it had not been for Moses his chosen one,
Who stood in the gap before him,
To turn back his rage from bringing &#91;them&#93; to ruin.

[[v19-106-24]]

^<<v19-106-24,24>>^ And they got to contemning the desirable land;
They had no faith in his word.

[[v19-106-25]]

^<<v19-106-25,25>>^ And they kept grumbling in their tents;
They did not listen to the voice of Jehovah.

[[v19-106-26]]

^<<v19-106-26,26>>^ So he proceeded to raise his hand &#91;in an oath&#93; concerning them,
That he would make them fall in the wilderness,

[[v19-106-27]]

^<<v19-106-27,27>>^ And that he would make their offspring fall among the nations,
And that he would scatter them among the lands.

[[v19-106-28]]

^<<v19-106-28,28>>^ And they began to attach themselves to Baʹal of Peʹor
And to eat the sacrifices of the dead ones.

[[v19-106-29]]

^<<v19-106-29,29>>^ As they were causing offense by their dealings,
A scourge now broke out among them.

[[v19-106-30]]

^<<v19-106-30,30>>^ When Phinʹe·has stood up and intervened,
Then the scourge was halted.

[[v19-106-31]]

^<<v19-106-31,31>>^ And it came to be counted to him as righteousness
For generation after generation to time indefinite.

[[v19-106-32]]

^<<v19-106-32,32>>^ Further, they caused provocation at the waters of Merʹi·bah,
So that it went badly with Moses by reason of them.

[[v19-106-33]]

^<<v19-106-33,33>>^ For they embittered his spirit^&#42;1^
And he began to speak rashly with his lips.

[NOTE]
====
. “His spirit.” Heb., ru·chohʹ; Gr., pneuʹma; Lat., spiʹri·tum.
====

[[v19-106-34]]

^<<v19-106-34,34>>^ They did not annihilate the peoples,
As Jehovah had said to them.

[[v19-106-35]]

^<<v19-106-35,35>>^ And they went mingling with the nations
And took up learning their works.

[[v19-106-36]]

^<<v19-106-36,36>>^ And they kept serving^&#42;1^ their idols,
And these came to be a snare to them.

[NOTE]
====
. Or, “And they kept worshiping (rendering sacred service).” Heb., wai·ya·ʽav·dhuʹ.
====

[[v19-106-37]]

^<<v19-106-37,37>>^ And they would sacrifice their sons
And their daughters to demons.^&#42;1^

[NOTE]
====
. “To demons (evil spirits),” M(Heb., lash·sheʹdhim)LXXVg.
====

[[v19-106-38]]

^<<v19-106-38,38>>^ So they kept spilling innocent blood,
The blood of their sons and their daughters,
Whom they sacrificed to the idols of Caʹnaan;
And the land came to be polluted with bloodshed.^&#42;1^

[NOTE]
====
. Lit., “bloods.”
====

[[v19-106-39]]

^<<v19-106-39,39>>^ And they got to be unclean by their works
And kept having immoral intercourse by their dealings.

[[v19-106-40]]

^<<v19-106-40,40>>^ And the anger of Jehovah began to blaze against his people,
And he came to detest his inheritance.

[[v19-106-41]]

^<<v19-106-41,41>>^ And he repeatedly gave them into the hand of the nations,
That those hating them might rule over them,

[[v19-106-42]]

^<<v19-106-42,42>>^ And that their enemies might oppress them,
And that they might be subdued under their hand.

[[v19-106-43]]

^<<v19-106-43,43>>^ Many times he would deliver them,
But they themselves would behave rebelliously in their disobedient course,
And they would be brought low for their error.

[[v19-106-44]]

^<<v19-106-44,44>>^ And he^&#42;1^ would see the distress of theirs
When he heard their entreating cry.

[NOTE]
====
. “He,” MTSyVg; LXXA and one Heb. ms, “Jehovah.”
====

[[v19-106-45]]

^<<v19-106-45,45>>^ And he would remember concerning them his covenant,
And he would feel regret according to the abundance of his grand loving-kindness.

[[v19-106-46]]

^<<v19-106-46,46>>^ And he would grant them to be objects of pity
Before all those holding them captive.

[[v19-106-47]]

^<<v19-106-47,47>>^ Save us, O Jehovah our God,
And collect us together from the nations
To give thanks to your holy name,
To speak exultingly in your praise.

[[v19-106-48]]

^<<v19-106-48,48>>^ Blessed be Jehovah the God of Israel
From time indefinite even to time indefinite;
And all the people must say^&#42;1^ Amen.
Praise Jah, YOU people!^&#42;2^

[NOTE]
====
. Lit., “have said.”
. See 41:13 and 104:35 ftns.
====

'''

xref:019-psalm/019-psalm-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-psalm/019-psalm-107.adoc#v19-107-0[Próximo Capítulo &#62;]