include::./index.adoc[]

[[v2-40-0]]
=== Exodus, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-40-1]]

^<<v2-40-1,1>>^ Then Jehovah spoke to Moses, saying:

[[v2-40-2]]

^<<v2-40-2,2>>^ “On the day of the first month, on the first of the month, you are to set up the tabernacle of the tent of meeting.

[[v2-40-3]]

^<<v2-40-3,3>>^ And you must place the ark of the testimony in it and shut off approach to the Ark with the curtain.

[[v2-40-4]]

^<<v2-40-4,4>>^ And you must bring the table in and set its arrangement in order, and you must bring in the lampstand and light up its lamps.

[[v2-40-5]]

^<<v2-40-5,5>>^ And you must put the golden altar for incense before the ark of the testimony and put the screen of the entrance for the tabernacle in place.

[[v2-40-6]]

^<<v2-40-6,6>>^ “And you must put the altar of burnt offering before the entrance of the tabernacle of the tent of meeting,

[[v2-40-7]]

^<<v2-40-7,7>>^ and you must put the basin between the tent of meeting and the altar and put water in it.

[[v2-40-8]]

^<<v2-40-8,8>>^ And you must place the courtyard round about and put up the screen of the gate of the courtyard.

[[v2-40-9]]

^<<v2-40-9,9>>^ And you must take the anointing oil and anoint the tabernacle and all that is in it, and you must sanctify it and all its utensils, and so it must become something holy.

[[v2-40-10]]

^<<v2-40-10,10>>^ And you must anoint the altar of burnt offering and all its utensils and sanctify the altar, and so it must become a most holy altar.

[[v2-40-11]]

^<<v2-40-11,11>>^ And you must anoint the basin and its stand and sanctify it.

[[v2-40-12]]

^<<v2-40-12,12>>^ “Then you must bring Aaron and his sons near to the entrance of the tent of meeting and wash them with water.

[[v2-40-13]]

^<<v2-40-13,13>>^ And you must clothe Aaron with the holy garments and anoint him and sanctify him, and so he must act as priest to me.

[[v2-40-14]]

^<<v2-40-14,14>>^ After that you will bring his sons near and you must clothe them with robes.

[[v2-40-15]]

^<<v2-40-15,15>>^ And you must anoint them just as you anointed their father, and so they must act as priests to me, and their anointing must serve continually for them as a priesthood to time indefinite during their generations.”

[[v2-40-16]]

^<<v2-40-16,16>>^ And Moses proceeded to do according to all that Jehovah had commanded him. He did just so.

[[v2-40-17]]

^<<v2-40-17,17>>^ Accordingly it came about that in the first month, in the second year, on the first day of the month, the tabernacle was set up.

[[v2-40-18]]

^<<v2-40-18,18>>^ When Moses proceeded to set up the tabernacle, he went putting its socket pedestals down and placing its panel frames and putting its bars in and setting up its pillars.

[[v2-40-19]]

^<<v2-40-19,19>>^ Then he spread out the tent over the tabernacle and placed the covering of the tent above upon it, just as Jehovah had commanded Moses.

[[v2-40-20]]

^<<v2-40-20,20>>^ After that he took the Testimony and put it into the Ark and placed the poles on the Ark and put the cover above upon the Ark.

[[v2-40-21]]

^<<v2-40-21,21>>^ Then he brought the Ark into the tabernacle and put the curtain of the screen in place and shut off approach to the ark of the testimony, just as Jehovah had commanded Moses.

[[v2-40-22]]

^<<v2-40-22,22>>^ Next he put the table in the tent of meeting on the side of the tabernacle to the north outside the curtain,

[[v2-40-23]]

^<<v2-40-23,23>>^ and he arranged the row of bread upon it before Jehovah, just as Jehovah had commanded Moses.

[[v2-40-24]]

^<<v2-40-24,24>>^ Then he placed the lampstand in the tent of meeting in front of the table, on the side of the tabernacle to the south.^&#42;1^

[NOTE]
====
. Lit., “Negeb.”
====

[[v2-40-25]]

^<<v2-40-25,25>>^ He then lit up the lamps before Jehovah, just as Jehovah had commanded Moses.

[[v2-40-26]]

^<<v2-40-26,26>>^ He next placed the golden altar in the tent of meeting before the curtain,

[[v2-40-27]]

^<<v2-40-27,27>>^ that he might^&#42;1^ make perfumed incense smoke upon it, just as Jehovah had commanded Moses.

[NOTE]
====
. Or, “and he began to.”
====

[[v2-40-28]]

^<<v2-40-28,28>>^ Finally he put the screen of the entrance of the tabernacle in place.

[[v2-40-29]]

^<<v2-40-29,29>>^ And he placed the altar of burnt offering at the entrance of the tabernacle of the tent of meeting, that he might offer up the burnt offering and the grain offering upon it, just as Jehovah had commanded Moses.

[[v2-40-30]]

^<<v2-40-30,30>>^ Then he placed the basin between the tent of meeting and the altar and put water in it for washing.

[[v2-40-31]]

^<<v2-40-31,31>>^ And Moses and Aaron and his sons washed their hands and their feet at it.

[[v2-40-32]]

^<<v2-40-32,32>>^ When they went into the tent of meeting and when they went near to the altar they would wash, just as Jehovah had commanded Moses.

[[v2-40-33]]

^<<v2-40-33,33>>^ Finally he set up the courtyard round about the tabernacle and the altar and put up the screen of the gate of the courtyard.
So Moses finished the work.

[[v2-40-34]]

^<<v2-40-34,34>>^ And the cloud began to cover the tent of meeting, and Jehovah’s glory filled the tabernacle.

[[v2-40-35]]

^<<v2-40-35,35>>^ And Moses was not able to go into the tent of meeting, because the cloud resided over it and Jehovah’s glory filled the tabernacle.

[[v2-40-36]]

^<<v2-40-36,36>>^ And when the cloud lifted itself up from over the tabernacle the sons of Israel would break camp during all their stages of journey.

[[v2-40-37]]

^<<v2-40-37,37>>^ However, if the cloud did not lift itself up, then they would not break camp until the day when it lifted itself up.

[[v2-40-38]]

^<<v2-40-38,38>>^ For Jehovah’s cloud was over the tabernacle by day, and a fire continued upon it by night in the sight of all the house of Israel during all their stages of journey.

'''

xref:002-exodus/002-exodus-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-leviticus/003-leviticus-001.adoc#v3-1-0[Próximo Capítulo &#62;]