include::./index.adoc[]

[[v2-19-0]]
=== Exodus, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-19-1]]

^<<v2-19-1,1>>^ In the third month after the sons of Israel came out of the land of Egypt, on the same day, they came into the wilderness of Siʹnai.

[[v2-19-2]]

^<<v2-19-2,2>>^ And they proceeded to pull away from Rephʹi·dim and to come into the wilderness of Siʹnai and to encamp in the wilderness; and Israel went camping there in front of the mountain.

[[v2-19-3]]

^<<v2-19-3,3>>^ And Moses went up to the &#91;true&#93; God, and Jehovah began to call^&#42;1^ to him out of the mountain, saying: “This is what you are to say to the house of Jacob and to tell the sons of Israel,

[NOTE]
====
. “Jehovah began to call”; the first occurrence of this expression in Exodus. Compare 3:4; 19:20.
====

[[v2-19-4]]

^<<v2-19-4,4>>^ ‘YOU yourselves have seen what I did to the Egyptians, that I might carry YOU on wings of eagles and bring YOU to myself.

[[v2-19-5]]

^<<v2-19-5,5>>^ And now if YOU will strictly obey^&#42;1^ my voice and will indeed keep my covenant, then YOU will certainly become^&#42;2^ my special property out of all &#91;other&#93; peoples, because the whole earth belongs to me.

[NOTE]
====
. Or, “listen to.”
. Or, “then you must become.”
====

[[v2-19-6]]

^<<v2-19-6,6>>^ And YOU yourselves will become to me a kingdom of priests and a holy nation.’ These are the words that you are to say to the sons of Israel.”

[[v2-19-7]]

^<<v2-19-7,7>>^ So Moses came and called the older men of the people and set before them all these words that Jehovah had commanded him.

[[v2-19-8]]

^<<v2-19-8,8>>^ After that all the people answered unanimously and said: “All that Jehovah has spoken we are willing to do.” Immediately Moses took back the words of the people to Jehovah.

[[v2-19-9]]

^<<v2-19-9,9>>^ At this Jehovah said to Moses: “Look! I am coming to you in a dark cloud, in order that the people may hear when I speak with you, and that in you also they may put faith to time indefinite.” Then Moses reported the words of the people to Jehovah.

[[v2-19-10]]

^<<v2-19-10,10>>^ And Jehovah went on to say to Moses: “Go to the people, and you must sanctify them today and tomorrow, and they must wash their mantles.

[[v2-19-11]]

^<<v2-19-11,11>>^ And they must prove ready for the third day, because on the third day Jehovah will come down before the eyes of all the people upon Mount Siʹnai.

[[v2-19-12]]

^<<v2-19-12,12>>^ And you must set bounds for the people round about, saying, ‘Guard yourselves against going up into the mountain, and do not touch the edge of it. Anybody touching the mountain will positively be put to death.

[[v2-19-13]]

^<<v2-19-13,13>>^ No hand is to touch him, because he will positively be stoned or will positively be shot through. Whether beast or man, he will not live.’ At the blowing of the ram’s horn^&#42;1^ they themselves may come up to the mountain.”

[NOTE]
====
. “The ram’s horn.” Heb., hai·yo·velʹ. See Le 25:10 ftn, “Jubilee.”
====

[[v2-19-14]]

^<<v2-19-14,14>>^ Then Moses went down from the mountain to the people, and he set about sanctifying the people; and they engaged in washing their mantles.

[[v2-19-15]]

^<<v2-19-15,15>>^ Accordingly he said to the people: “Get ready during the three days. Do not YOU men come near a woman.”

[[v2-19-16]]

^<<v2-19-16,16>>^ And on the third day when it became morning it came about that thunders and lightnings began occurring, and a heavy cloud upon the mountain and a very loud sound of a horn, so that all the people who were in the camp began to tremble.

[[v2-19-17]]

^<<v2-19-17,17>>^ Moses now brought the people out of the camp to meet the &#91;true&#93; God, and they went taking their stand at the base of the mountain.

[[v2-19-18]]

^<<v2-19-18,18>>^ And Mount Siʹnai smoked all over, due to the fact that Jehovah came down upon it in fire; and its smoke kept ascending like the smoke of a kiln, and the whole mountain was trembling very much.

[[v2-19-19]]

^<<v2-19-19,19>>^ When the sound of the horn became continually louder and louder, Moses began to speak, and the &#91;true&#93; God began to answer him with a voice.

[[v2-19-20]]

^<<v2-19-20,20>>^ So Jehovah came down upon Mount Siʹnai to the top of the mountain. Then Jehovah called Moses to the top of the mountain, and Moses went on up.

[[v2-19-21]]

^<<v2-19-21,21>>^ Jehovah now said to Moses: “Go down, warn the people, that they do not try to break through to Jehovah to take a look and many of them have to fall.

[[v2-19-22]]

^<<v2-19-22,22>>^ And let the priests also who regularly come near to Jehovah sanctify themselves, that Jehovah may not break out upon them.”

[[v2-19-23]]

^<<v2-19-23,23>>^ At this Moses said to Jehovah: “The people are not able to come up to Mount Siʹnai, because you yourself already warned us, saying, ‘Set bounds for the mountain and make it sacred.’”^&#42;1^

[NOTE]
====
. Or, “and sanctify it.”
====

[[v2-19-24]]

^<<v2-19-24,24>>^ However, Jehovah said to him: “Go, descend, and you must come up, you and Aaron with you; but let not the priests and the people break through to come up to Jehovah, that he may not break out upon them.”

[[v2-19-25]]

^<<v2-19-25,25>>^ Accordingly Moses descended to the people and told them.

'''

xref:002-exodus/002-exodus-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodus/002-exodus-020.adoc#v2-20-0[Próximo Capítulo &#62;]