include::./index.adoc[]

[[v2-12-0]]
=== Exodus, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-12-1]]

^<<v2-12-1,1>>^ Jehovah now said to Moses and Aaron in the land of Egypt:

[[v2-12-2]]

^<<v2-12-2,2>>^ “This month will be the start of the months for YOU. It will be the first of the months of the year for YOU.

[[v2-12-3]]

^<<v2-12-3,3>>^ Speak to the entire assembly of Israel, saying, ‘On the tenth day of this month they are to take for themselves each one a sheep^&#42;1^ for the ancestral house, a sheep to a house.

[NOTE]
====
. “Sheep.” Heb., seh; Gr., proʹba·ton; Lat., aʹgnum, “lamb.”
====

[[v2-12-4]]

^<<v2-12-4,4>>^ But if the household proves to be too small for the sheep, then he and his neighbor close by must take it into his house according to the number of souls;^&#42;1^ YOU should compute each one proportionate to his eating as regards the sheep.

[NOTE]
====
. Or, “persons.” Heb., nepha·shothʹ, pl.; Gr., psy·khonʹ, pl.
====

[[v2-12-5]]

^<<v2-12-5,5>>^ The sheep should prove to be sound, a male, a year old, for YOU. YOU may pick from the young rams^&#42;1^ or from the goats.

[NOTE]
====
. Or, “the male lambs.”
====

[[v2-12-6]]

^<<v2-12-6,6>>^ And it must continue under safeguard by YOU until the fourteenth day of this month, and the whole congregation of the assembly of Israel must slaughter it between the two evenings.^&#42;1^

[NOTE]
====
. “Between the two evenings.” According to some scholars, as well as the Karaite Jews and Samaritans, this is the time between sunset and actual darkness. The Pharisees and the Rabbinists considered it otherwise: the first evening when the sun began to descend and the second evening the actual sunset.
====

[[v2-12-7]]

^<<v2-12-7,7>>^ And they must take some of the blood and splash^&#42;1^ it upon the two doorposts^&#42;2^ and the upper part of the doorway^&#42;3^ belonging to the houses in which they will eat it.

[NOTE]
====
. Lit., “give.”
. “The . . . doorposts.” Heb., ham·mezu·zothʹ. The modern Jewish term “mezuzah” denotes a rectangular piece of parchment containing the Heb. text of De 6:4-9 and De 11:13-21. The parchment is placed in a small case and affixed in a slanting position on the right-hand doorpost of the dwellings of Orthodox Jews. See De 6:9 ftn.
. Or, “and the lintel.”
====

[[v2-12-8]]

^<<v2-12-8,8>>^ “‘And they must eat the flesh on this night. They should eat it roasted with fire and with unfermented cakes^&#42;1^ along with bitter greens.

[NOTE]
====
. Or, “yeastless bread; unleavened bread.”
====

[[v2-12-9]]

^<<v2-12-9,9>>^ Do not eat any of it raw^&#42;1^ or boiled, cooked in water, but roast with fire, its head together with its shanks and its interior parts.

[NOTE]
====
. Or, “half done.”
====

[[v2-12-10]]

^<<v2-12-10,10>>^ And YOU must not leave any of it over till morning, but what is left over of it till morning YOU should burn with fire.

[[v2-12-11]]

^<<v2-12-11,11>>^ And in this way YOU should eat it, with YOUR hips girded, sandals on YOUR feet and YOUR staff in YOUR hand; and YOU must eat it in haste. It is Jehovah’s passover.^&#42;1^

[NOTE]
====
. Lit., “an overleaping; a passing over.” Heb., peʹsach.
====

[[v2-12-12]]

^<<v2-12-12,12>>^ And I must pass through the land of Egypt on this night and strike every firstborn in the land of Egypt, from man to beast; and on all the gods^&#42;1^ of Egypt I shall execute judgments. I am Jehovah.

[NOTE]
====
. “And on all the gods of.” Heb., u·vekhol-ʼelo·hehʹ, pl. to denote more than one Egyptian god.
====

[[v2-12-13]]

^<<v2-12-13,13>>^ And the blood must serve as YOUR sign upon the houses where YOU are; and I must see the blood and pass over YOU, and the plague will not come on YOU as a ruination when I strike at the land of Egypt.

[[v2-12-14]]

^<<v2-12-14,14>>^ “‘And this day must serve as a memorial for YOU, and YOU must celebrate it as a festival to Jehovah^&#42;1^ throughout YOUR generations. As a statute to time indefinite YOU should celebrate it.

[NOTE]
====
. Or, “celebrate it as Jehovah’s festival.”
====

[[v2-12-15]]

^<<v2-12-15,15>>^ Seven days YOU are to eat unfermented cakes. Yes, on the first day YOU are to take away sourdough^&#42;1^ from YOUR houses, because anyone eating what is leavened, from the first day down to the seventh, that soul must be cut off from Israel.

[NOTE]
====
. Or, “yeast; leaven.”
====

[[v2-12-16]]

^<<v2-12-16,16>>^ And on the first day there is to take place for YOU a holy convention,^&#42;1^ and on the seventh day a holy convention. No work is to be done on them. Only what every soul needs to eat, that alone may be done for YOU.

[NOTE]
====
. Or, “convocation.”
====

[[v2-12-17]]

^<<v2-12-17,17>>^ “‘And YOU must keep the festival of unfermented cakes, because on this very day I must bring YOUR armies out from the land of Egypt. And YOU must keep this day throughout YOUR generations as a statute to time indefinite.

[[v2-12-18]]

^<<v2-12-18,18>>^ In the first month, on the fourteenth day of the month, in the evening YOU are to eat unfermented cakes down till the twenty-first day of the month in the evening.

[[v2-12-19]]

^<<v2-12-19,19>>^ Seven days no sourdough is to be found in YOUR houses, because anyone tasting what is leavened, whether he is an alien resident or a native of the land, that soul must be cut off from the assembly of Israel.

[[v2-12-20]]

^<<v2-12-20,20>>^ Nothing leavened are YOU to eat. In all YOUR dwellings YOU are to eat unfermented cakes.’”

[[v2-12-21]]

^<<v2-12-21,21>>^ Promptly Moses called all the older men of Israel and said to them: “Draw out and take for yourselves small cattle^&#42;1^ according to YOUR families, and slaughter the passover victim.

[NOTE]
====
. Or, “take for yourselves sheep and goats.”
====

[[v2-12-22]]

^<<v2-12-22,22>>^ And YOU must take a bunch of hyssop and dip^&#42;1^ it into the blood in a basin and strike upon the upper part of the doorway and upon the two doorposts some of the blood that is in the basin; and none of YOU should go out of the entrance of his house until morning.

[NOTE]
====
. Or, “immerse; baptize.” Gr., baʹpsan·tes.
====

[[v2-12-23]]

^<<v2-12-23,23>>^ Then when Jehovah does pass through to plague the Egyptians and does see the blood upon the upper part of the doorway and upon the two doorposts, Jehovah will certainly pass over the entrance, and he will not allow the ruination to enter into YOUR houses to plague YOU.

[[v2-12-24]]

^<<v2-12-24,24>>^ “And YOU must keep this thing as a regulation for you and your sons to time indefinite.

[[v2-12-25]]

^<<v2-12-25,25>>^ And it must occur that when YOU come into the land that Jehovah will give YOU, just as he has stated, then YOU must keep this service.^&#42;1^

[NOTE]
====
. Or, “feature of worship.” Heb., ha·ʽavo·dhahʹ; Gr., la·treiʹan, “sacred service.” Compare 3:12 ftn.
====

[[v2-12-26]]

^<<v2-12-26,26>>^ And it must occur that when YOUR sons say to YOU, ‘What does this service mean to YOU?’

[[v2-12-27]]

^<<v2-12-27,27>>^ then YOU must say, ‘It is the sacrifice of the passover to Jehovah, who passed over the houses of the sons of Israel in Egypt when he plagued the Egyptians, but he delivered our houses.’”
Then the people bowed low and prostrated themselves.

[[v2-12-28]]

^<<v2-12-28,28>>^ Subsequently the sons of Israel went and did just as Jehovah had commanded Moses and Aaron. They did just so.

[[v2-12-29]]

^<<v2-12-29,29>>^ And it came about that at midnight Jehovah struck every firstborn in the land of Egypt, from the firstborn of Pharʹaoh sitting on his throne to the firstborn of the captive who was in the prison hole,^&#42;1^ and every firstborn of beast.

[NOTE]
====
. Or, “the penitentiary.” Lit., “the house of the cistern.” See Ge 40:15 ftn.
====

[[v2-12-30]]

^<<v2-12-30,30>>^ Then Pharʹaoh got up at night, he and all his servants and all &#91;other&#93; Egyptians; and there began arising a great outcry among the Egyptians, because there was not a house where there was not one dead.

[[v2-12-31]]

^<<v2-12-31,31>>^ At once he called Moses and Aaron by night and said: “Get up, get out from the midst of my people, both YOU and the &#91;other&#93; sons of Israel, and go, serve Jehovah, just as YOU have stated.

[[v2-12-32]]

^<<v2-12-32,32>>^ Take both YOUR flocks and YOUR herds, just as YOU have stated, and go. Also, YOU must bless me besides.”

[[v2-12-33]]

^<<v2-12-33,33>>^ And the Egyptians began to urge the people in order to send them away quickly out of the land, “because,” they said, “we are all as good as dead!”

[[v2-12-34]]

^<<v2-12-34,34>>^ Consequently the people carried their flour dough before it was leavened, with their kneading troughs wrapped up in their mantles upon their shoulder.

[[v2-12-35]]

^<<v2-12-35,35>>^ And the sons of Israel did according to the word of Moses in that they went asking from the Egyptians articles of silver and articles of gold and mantles.

[[v2-12-36]]

^<<v2-12-36,36>>^ And Jehovah gave the people favor in the eyes of the Egyptians, so that these granted them what was asked; and they stripped the Egyptians.

[[v2-12-37]]

^<<v2-12-37,37>>^ And the sons of Israel proceeded to depart from Ramʹe·ses for Sucʹcoth, to the number of six hundred thousand able-bodied men on foot, besides little ones.

[[v2-12-38]]

^<<v2-12-38,38>>^ And a vast mixed company^&#42;1^ also went up with them, as well as flocks and herds, a very numerous stock of animals.

[NOTE]
====
. Or, “And many aliens (strangers).”
====

[[v2-12-39]]

^<<v2-12-39,39>>^ And they began to bake the flour dough that they had brought out from Egypt into round cakes, unfermented cakes, because it had not leavened, for they had been driven out of Egypt and had not been able to linger and too they had not prepared any provisions for themselves.

[[v2-12-40]]

^<<v2-12-40,40>>^ And the dwelling of the sons of Israel,^&#42;1^ who had dwelt^&#42;2^ in Egypt, was four hundred and thirty years.

[NOTE]
====
. Sam adds, “and their fathers.”
. “Who had dwelt.” In Heb. this verb is pl. The relative pronoun ʼasherʹ, “who,” can apply to the “sons of Israel” rather than to the “dwelling.” LXX, “But the dwelling of the sons of Israel which they [LXXA adds “and their fathers”] dwelt in the land of Egypt and in the land of Canaan [was] four hundred and thirty years long”; Sam, “in the land of Canaan and in the land of Egypt.” Likewise Josephus wrote in Jewish Antiquities, Book II, chapter 15, ¶2: “They left Egypt in the month of Xanthicus [the Macedonian month equated by Josephus with the month Nisan], on the fifteenth by lunar reckoning, 430 years after the coming of our forefather Abraham to Canaan.” (Loeb Classical Library, by H. Thackeray, 1967, p. 305) The sons of Israel went out of the land of Egypt on the 15th day of the first month. See Ex 12:37; Nu 33:3, 5. SamLXX and Josephus show that the 430 years are counted from the time Abraham entered the land of Canaan until the time the Israelites went out of Egypt. See Ga 3:17.
====

[[v2-12-41]]

^<<v2-12-41,41>>^ And it came about at the end of the four hundred and thirty years, it even came about on this very day that all the armies of Jehovah went out of the land of Egypt.

[[v2-12-42]]

^<<v2-12-42,42>>^ It is a night for observance with regard to Jehovah for bringing them out of the land of Egypt. With regard to Jehovah this night is one for observance on the part of all the sons of Israel throughout their generations.

[[v2-12-43]]

^<<v2-12-43,43>>^ And Jehovah went on to say to Moses and Aaron: “This is the statute of the passover: No foreigner^&#42;1^ may eat of it.

[NOTE]
====
. Lit., “son of a foreign (country).”
====

[[v2-12-44]]

^<<v2-12-44,44>>^ But where there is any slave man purchased with money, you must circumcise him. Then first he may share in eating it.

[[v2-12-45]]

^<<v2-12-45,45>>^ A settler^&#42;1^ and a hired laborer may not eat of it.

[NOTE]
====
. Or, “stranger; immigrant.”
====

[[v2-12-46]]

^<<v2-12-46,46>>^ In one house it is to be eaten. You must not take any of the flesh out of the house to some place outside. And YOU must not break a bone in it.

[[v2-12-47]]

^<<v2-12-47,47>>^ All the assembly of Israel are to celebrate it.

[[v2-12-48]]

^<<v2-12-48,48>>^ And in case an alien resident resides as an alien with you and he will actually celebrate the passover to Jehovah, let there be a circumcising^&#42;1^ of every male of his. First then he may come near to celebrate it; and he must become like a native of the land. But no uncircumcised man may eat of it.

[NOTE]
====
. In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v2-12-49]]

^<<v2-12-49,49>>^ One law is to exist for the native and for the alien resident who is residing as an alien in YOUR midst.”

[[v2-12-50]]

^<<v2-12-50,50>>^ So all the sons of Israel did just as Jehovah had commanded Moses and Aaron. They did just so.

[[v2-12-51]]

^<<v2-12-51,51>>^ And it came about on this very day that Jehovah brought the sons of Israel together with their armies out of the land of Egypt.

'''

xref:002-exodus/002-exodus-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodus/002-exodus-013.adoc#v2-13-0[Próximo Capítulo &#62;]