include::./index.adoc[]

[[v2-9-0]]
=== Exodus, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-9-1]]

^<<v2-9-1,1>>^ Consequently Jehovah said to Moses: “Go in to Pharʹaoh and you must state to him, ‘This is what Jehovah the God of the Hebrews has said: “Send my people away that they may serve me.

[[v2-9-2]]

^<<v2-9-2,2>>^ But if you continue refusing to send them away and you are still keeping hold of them,

[[v2-9-3]]

^<<v2-9-3,3>>^ look! Jehovah’s hand is coming upon your livestock that is in the field. On the horses, the asses, the camels, the herd and the flock there will be a very heavy pestilence.

[[v2-9-4]]

^<<v2-9-4,4>>^ And Jehovah will certainly make a distinction between the livestock of Israel and the livestock of Egypt, and not a thing of all that belongs to the sons of Israel will die.”’”

[[v2-9-5]]

^<<v2-9-5,5>>^ Moreover, Jehovah set an appointed time, saying: “Tomorrow Jehovah will do this thing in the land.”

[[v2-9-6]]

^<<v2-9-6,6>>^ Accordingly Jehovah did this thing on the next day, and all sorts of livestock^&#42;1^ of Egypt began to die; but not one of the livestock of the sons of Israel died.

[NOTE]
====
. Or, “and all the livestock.”
====

[[v2-9-7]]

^<<v2-9-7,7>>^ Then Pharʹaoh sent, and, look! not so much as one of Israel’s livestock had died. Nevertheless, Pharʹaoh’s heart continued to be unresponsive, and he did not send the people away.

[[v2-9-8]]

^<<v2-9-8,8>>^ After that Jehovah said to Moses and Aaron: “Take for yourselves both hands full of soot from a kiln, and Moses must toss it toward the heavens in Pharʹaoh’s sight.

[[v2-9-9]]

^<<v2-9-9,9>>^ And it must become a powder upon all the land of Egypt, and it must become boils breaking out with blisters upon man and beast in all the land of Egypt.”

[[v2-9-10]]

^<<v2-9-10,10>>^ So they took the soot of a kiln and stood before Pharʹaoh, and Moses tossed it toward the heavens, and it became boils with blisters, breaking out on man and beast.

[[v2-9-11]]

^<<v2-9-11,11>>^ And the magic-practicing priests were unable to stand before Moses as a result of the boils, because the boils had developed on the magic-practicing priests and on all the Egyptians.

[[v2-9-12]]

^<<v2-9-12,12>>^ But Jehovah let Pharʹaoh’s heart become obstinate, and he did not listen to them, just as Jehovah had stated to Moses.

[[v2-9-13]]

^<<v2-9-13,13>>^ Then Jehovah said to Moses: “Get up early in the morning and take a position in front of Pharʹaoh, and you must say to him, ‘This is what Jehovah the God of the Hebrews has said: “Send my people away that they may serve me.

[[v2-9-14]]

^<<v2-9-14,14>>^ For at this time I am sending all my blows against your heart and upon your servants and your people, to the end that you may know that there is none like me in all the earth.

[[v2-9-15]]

^<<v2-9-15,15>>^ For by now I could have thrust my hand out that I might strike you and your people with pestilence and that you might be effaced from the earth.

[[v2-9-16]]

^<<v2-9-16,16>>^ But, in fact, for this cause I have kept you in existence,^&#42;1^ for the sake of showing you my power and in order to have my name declared in all the earth.^&#42;2^

[NOTE]
====
. Or, “I have preserved you; I have let you remain.” Lit., “I have kept you standing.” Compare 21:21 ftn, “Lingers.”
. “And for this purpose you have been preserved, that in connection with you I may show my strength, and that my name may be declared in all the earth,” LXX. Compare Ro 9:17.
====

[[v2-9-17]]

^<<v2-9-17,17>>^ Are you still behaving haughtily^&#42;1^ against my people in not sending them away?

[NOTE]
====
. “As yet you are exalting yourself,” James Washington Watts (1977).
====

[[v2-9-18]]

^<<v2-9-18,18>>^ Here I am causing it to rain down tomorrow about this time a very heavy hail, the like of which has never occurred in Egypt from the day it was founded until now.

[[v2-9-19]]

^<<v2-9-19,19>>^ And now send, bring all your livestock and all that is yours in the field under shelter. As for any man and beast that will be found in the field and not gathered into the house, the hail will have to come down upon them, and they will have to die.”’”

[[v2-9-20]]

^<<v2-9-20,20>>^ Anyone who feared Jehovah’s word among Pharʹaoh’s servants caused his own servants and his livestock to flee into the houses,

[[v2-9-21]]

^<<v2-9-21,21>>^ but whoever did not set his heart to have any regard for Jehovah’s word left his servants and his livestock in the field.

[[v2-9-22]]

^<<v2-9-22,22>>^ Jehovah now said to Moses: “Stretch out your hand toward the heavens, that hail may come on all the land of Egypt, upon man and beast and all vegetation of the field in the land of Egypt.”

[[v2-9-23]]

^<<v2-9-23,23>>^ So Moses stretched out his rod toward the heavens; and Jehovah gave thunders and hail, and fire would run down to the earth, and Jehovah kept making it rain down hail upon the land of Egypt.

[[v2-9-24]]

^<<v2-9-24,24>>^ Thus there came hail, and fire quivering in among the hail. It was very heavy, so that there had not occurred any like it in all the land of Egypt from the time it became a nation.

[[v2-9-25]]

^<<v2-9-25,25>>^ And the hail went striking at all the land of Egypt. The hail struck everything that was in the field, from man to beast, and all sorts of vegetation^&#42;1^ of the field; and it shattered all sorts of trees^&#42;2^ of the field.

[NOTE]
====
. Or, “all the vegetation.”
. Or, “all the trees; every tree.”
====

[[v2-9-26]]

^<<v2-9-26,26>>^ Only in the land of Goʹshen, where the sons of Israel were, there occurred no hail.

[[v2-9-27]]

^<<v2-9-27,27>>^ Eventually Pharʹaoh sent and called Moses and Aaron and said to them: “I have sinned this time. Jehovah is righteous, and I and my people are in the wrong.^&#42;1^

[NOTE]
====
. Or, “are the wicked ones.”
====

[[v2-9-28]]

^<<v2-9-28,28>>^ Entreat Jehovah that this may be enough of the occurring of God’s thunders and hail. Then I am willing to send YOU away, and YOU will not stay any longer.”

[[v2-9-29]]

^<<v2-9-29,29>>^ So Moses said to him: “As soon as I go out of the city I shall spread my hands up to Jehovah. The thunders will stop and the hail will not continue any longer, in order that you may know that the earth belongs to Jehovah.

[[v2-9-30]]

^<<v2-9-30,30>>^ As for you and your servants, I know already that YOU will not even then show fear because of Jehovah God.”

[[v2-9-31]]

^<<v2-9-31,31>>^ As it was, the flax and the barley had been struck, because the barley was in the ear and the flax had flower buds.

[[v2-9-32]]

^<<v2-9-32,32>>^ But the wheat and the spelt^&#42;1^ had not been struck, because they were seasonally late.

[NOTE]
====
. An inferior kind of wheat cultivated in ancient Egypt.
====

[[v2-9-33]]

^<<v2-9-33,33>>^ Moses now went out of the city from Pharʹaoh and spread his hands up to Jehovah, and the thunders and the hail began to stop and rain did not pour down on the earth.

[[v2-9-34]]

^<<v2-9-34,34>>^ When Pharʹaoh got to see that the rain and the hail and the thunders had stopped, he went sinning again and making his heart unresponsive, he as well as his servants.

[[v2-9-35]]

^<<v2-9-35,35>>^ And Pharʹaoh’s heart continued obstinate, and he did not send the sons of Israel away, just as Jehovah had stated by means of Moses.^&#42;1^

[NOTE]
====
. Lit., “by the hand of Moses.”
====

'''

xref:002-exodus/002-exodus-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodus/002-exodus-010.adoc#v2-10-0[Próximo Capítulo &#62;]