include::./index.adoc[]

[[v2-37-0]]
=== Exodus, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezʹal·el now made the Ark of acacia wood. Two cubits and a half was its length, and a cubit and a half its width, and a cubit and a half its height.

[[v2-37-2]]

^<<v2-37-2,2>>^ Then he overlaid it with pure gold inside and outside and made a border of gold round about for it.

[[v2-37-3]]

^<<v2-37-3,3>>^ After that he cast four rings of gold for it, for above its four feet, with two rings on its one side and two rings on its other side.

[[v2-37-4]]

^<<v2-37-4,4>>^ He next made poles of acacia wood and overlaid them with gold.

[[v2-37-5]]

^<<v2-37-5,5>>^ Then he put the poles through the rings on the sides of the Ark for carrying the Ark.

[[v2-37-6]]

^<<v2-37-6,6>>^ And he went on to make the cover^&#42;1^ of pure gold. Two cubits and a half was its length, and a cubit and a half its width.

[NOTE]
====
. Or, “mercy seat; propitiatory,” LXXVg(Lat., pro·pi·ti·a·toʹri·um); Heb., kap·poʹreth. See 25:17 ftn.
====

[[v2-37-7]]

^<<v2-37-7,7>>^ He further made two cherubs of gold. Of hammered work he made them on both ends of the cover.

[[v2-37-8]]

^<<v2-37-8,8>>^ One cherub was on the end over there, and the other cherub on the end over here. He made the cherubs on the cover on both of its ends.

[[v2-37-9]]

^<<v2-37-9,9>>^ And they came to be cherubs spreading out two wings upward, screening over the cover with their wings, and their faces were one to the other. The faces of the cherubs proved to be toward the cover.

[[v2-37-10]]

^<<v2-37-10,10>>^ And he proceeded to make the table of acacia wood. Two cubits was its length, and a cubit its width, and a cubit and a half its height.

[[v2-37-11]]

^<<v2-37-11,11>>^ Then he overlaid it with pure gold and made a border of gold round about for it.

[[v2-37-12]]

^<<v2-37-12,12>>^ Next he made for it a rim of a handbreadth round about and made a border of gold for its rim round about.

[[v2-37-13]]

^<<v2-37-13,13>>^ Further, he cast four rings of gold for it and put the rings upon the four corners that were for the four feet.

[[v2-37-14]]

^<<v2-37-14,14>>^ The rings proved to be near the rim, as supports for the poles for carrying the table.

[[v2-37-15]]

^<<v2-37-15,15>>^ Then he made the poles of acacia wood and overlaid them with gold for carrying the table.

[[v2-37-16]]

^<<v2-37-16,16>>^ After that he made the utensils that are upon the table, its dishes and its cups and its bowls and its pitchers with which &#91;libations&#93; would be poured,^&#42;1^ out of pure gold.

[NOTE]
====
. Lit., “with which it would be poured.”
====

[[v2-37-17]]

^<<v2-37-17,17>>^ Then he made the lampstand of pure gold. Of hammered work he made the lampstand. Its sides and its branches, its cups, its knobs and its blossoms proceeded out of it.

[[v2-37-18]]

^<<v2-37-18,18>>^ And six branches were running out from its sides, three branches of the lampstand out from its one side and three branches of the lampstand out from its other side.

[[v2-37-19]]

^<<v2-37-19,19>>^ Three cups shaped like flowers of almond were on the one set of branches, with knobs and blossoms alternating; and three cups shaped like flowers of almond were on the other set of branches, with knobs and blossoms alternating. That is the way it was for the six branches running out from the lampstand.

[[v2-37-20]]

^<<v2-37-20,20>>^ And on the lampstand there were four cups shaped like flowers of almond, with its knobs and its blossoms alternating.

[[v2-37-21]]

^<<v2-37-21,21>>^ And the knob under two branches was out of it, and the knob under two other branches was out of it, and the knob under two more branches was out of it, for the six branches running out from the lampstand.

[[v2-37-22]]

^<<v2-37-22,22>>^ Their knobs and their branches proceeded out from it. All of it was one piece of hammered work, of pure gold.

[[v2-37-23]]

^<<v2-37-23,23>>^ Then he made its seven lamps and its snuffers and its fire holders out of pure gold.

[[v2-37-24]]

^<<v2-37-24,24>>^ Of a talent of pure gold he made it and all its utensils.

[[v2-37-25]]

^<<v2-37-25,25>>^ He now made the altar of incense out of acacia wood. A cubit^&#42;1^ was its length and a cubit its width, it being foursquare, and two cubits was its height. Its horns proceeded out of it.

[NOTE]
====
. About 44.5 cm (17.5 in.).
====

[[v2-37-26]]

^<<v2-37-26,26>>^ Then he overlaid it with pure gold, its top surface and its sides round about and its horns, and he made a border of gold round about for it.

[[v2-37-27]]

^<<v2-37-27,27>>^ And he made for it two rings of gold down below its border upon two of its sides, upon two opposite sides of it, as supports for the poles with which to carry it.

[[v2-37-28]]

^<<v2-37-28,28>>^ After that he made the poles of acacia wood and overlaid them with gold.

[[v2-37-29]]

^<<v2-37-29,29>>^ He made additionally the holy anointing oil and the pure, perfumed incense, the work of an ointment maker.

'''

xref:002-exodus/002-exodus-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodus/002-exodus-038.adoc#v2-38-0[Próximo Capítulo &#62;]