include::./index.adoc[]

[[v2-32-0]]
=== Exodus, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-32-1]]

^<<v2-32-1,1>>^ Meanwhile the people got to see that Moses was taking a long time about coming down from the mountain. So the people congregated themselves about Aaron and said to him: “Get up, make for us a god^&#42;1^ who will go ahead of us, because as regards this Moses, the man who led us up out of the land of Egypt, we certainly do not know what has happened to him.”

[NOTE]
====
. “A god.” Heb., ʼelo·himʹ, pl., likely to denote excellence; LXXVg, “gods”; also pl. in Ac 7:40, evidently quoting LXX. See vs 4 ftn, “God”; vs 31 ftn.
====

[[v2-32-2]]

^<<v2-32-2,2>>^ At this Aaron said to them: “Tear off the gold earrings that are in the ears of YOUR wives, of YOUR sons and of YOUR daughters and bring them to me.”

[[v2-32-3]]

^<<v2-32-3,3>>^ And all the people began tearing off the gold earrings that were in their ears and bringing them to Aaron.

[[v2-32-4]]

^<<v2-32-4,4>>^ Then he took &#91;the gold&#93;^&#42;1^ from their hands, and he formed it with a graving tool and proceeded to make it into a molten statue of a calf. And they^&#42;2^ began to say: “This is your God,^&#42;3^ O Israel, who led you up out of the land of Egypt.”

[NOTE]
====
. The words in brackets are understood and correspond with “it” in the same vs.
. “They,” MSyVg; LXX, “he.”
. Lit., “These [are] your gods.” Heb., ʼelʹleh ʼelo·heyʹkha. But Ne 9:18 explains this to mean “This is your God,” Heb., zeh ʼelo·heyʹkha. The Heb. pronoun and accompanying verb are sing. and ʼelo·himʹ is pl. to denote excellence. Compare Ps 106:19-21.
====

[[v2-32-5]]

^<<v2-32-5,5>>^ When Aaron got to see this, he went to building an altar before it. Finally Aaron called out and said: “There is a festival to Jehovah tomorrow.”

[[v2-32-6]]

^<<v2-32-6,6>>^ So on the next day they were early in rising, and they began offering up burnt offerings and presenting communion sacrifices. After that the people sat down to eat and drink. Then they got up to have a good time.

[[v2-32-7]]

^<<v2-32-7,7>>^ Jehovah now said to Moses: “Go, descend, because your people whom you led up out of the land of Egypt have acted ruinously.

[[v2-32-8]]

^<<v2-32-8,8>>^ They have turned aside in a hurry from the way I have commanded them to go. They have made a molten statue of a calf for themselves and keep bowing down to it and sacrificing to it and saying, ‘This is your God,^&#42;1^ O Israel, who led you up out of the land of Egypt.’”

[NOTE]
====
. See vs 4 ftn, “God.”
====

[[v2-32-9]]

^<<v2-32-9,9>>^ And Jehovah went on to say to Moses: “I have looked at this people and here it is a stiff-necked people.

[[v2-32-10]]

^<<v2-32-10,10>>^ So now let me be, that my anger may blaze against them and I may exterminate them, and let me make you into a great nation.”

[[v2-32-11]]

^<<v2-32-11,11>>^ And Moses proceeded to soften the face of Jehovah his God and to say: “Why, O Jehovah, should your anger blaze against your people whom you brought out of the land of Egypt with great power and with a strong hand?

[[v2-32-12]]

^<<v2-32-12,12>>^ Why should the Egyptians say, ‘With evil intent he brought them out in order to kill them among the mountains and to exterminate them from the surface of the ground’? Turn from your burning anger and feel regret over the evil against your people.

[[v2-32-13]]

^<<v2-32-13,13>>^ Remember Abraham, Isaac and Israel your servants, to whom you swore by yourself, in that you said to them, ‘I shall multiply YOUR seed^&#42;1^ like the stars of the heavens, and all this land that I have designated I shall give to YOUR seed, that they may indeed take possession of it to time indefinite.’”

[NOTE]
====
. Or, “offspring; posterity.”
====

[[v2-32-14]]

^<<v2-32-14,14>>^ And Jehovah began to feel regret over the evil that he had spoken of doing to his people.

[[v2-32-15]]

^<<v2-32-15,15>>^ After that Moses turned and went down from the mountain with the two tablets of the Testimony in his hand, tablets written upon on both their sides. On this side and on that they were written upon.

[[v2-32-16]]

^<<v2-32-16,16>>^ And the tablets were the workmanship of God, and the writing was the writing of God engraved upon the tablets.

[[v2-32-17]]

^<<v2-32-17,17>>^ And Joshua^&#42;1^ began to hear the noise of the people because of their shouting, and he proceeded to say to Moses: “There is a noise of battle in the camp.”

[NOTE]
====
. See 17:9 ftn.
====

[[v2-32-18]]

^<<v2-32-18,18>>^ But he said:
“It is not the sound of the singing over mighty performance,
And it is not the sound of the singing of defeat;
It is the sound of other singing that I am hearing.”

[[v2-32-19]]

^<<v2-32-19,19>>^ So it came about that as soon as he got near the camp and could see the calf and the dances, Moses’ anger began to blaze, and he at once threw the tablets from his hands and shattered them at the foot of the mountain.

[[v2-32-20]]

^<<v2-32-20,20>>^ Then he took the calf that they had made and he burnt it with fire and crushed it till it was fine, after which he scattered it upon the surface of the waters and made the sons of Israel drink it.

[[v2-32-21]]

^<<v2-32-21,21>>^ After that Moses said to Aaron: “What did this people do to you that you have brought a great sin upon it?”

[[v2-32-22]]

^<<v2-32-22,22>>^ To this Aaron said: “Do not let the anger of my lord blaze. You yourself well know the people, that they are evil-inclined.

[[v2-32-23]]

^<<v2-32-23,23>>^ So they said to me, ‘Make for us a god^&#42;1^ who will go ahead of us, because as regards this Moses, the man who led us up out of the land of Egypt, we certainly do not know what has happened to him.’

[NOTE]
====
. “A god.” Heb., ʼelo·himʹ; Gr., the·ousʹ, “gods”; Lat., deʹos, “gods.” See vs 1 ftn.
====

[[v2-32-24]]

^<<v2-32-24,24>>^ Hence I said to them, ‘Who have any gold? They must tear it off themselves that they may give it to me.’ And I proceeded to throw it into the fire and this calf came on out.”

[[v2-32-25]]

^<<v2-32-25,25>>^ And Moses got to see that the people went unrestrained, because Aaron had let them go unrestrained for a disgrace among their opposers.

[[v2-32-26]]

^<<v2-32-26,26>>^ Then Moses took his stand in the gate of the camp and said: “Who is on Jehovah’s side?^&#42;1^ To me!” And all the sons of Leʹvi began gathering themselves to him.

[NOTE]
====
. Or, “Who is for Jehovah?; Who is Jehovah’s?”
====

[[v2-32-27]]

^<<v2-32-27,27>>^ He now said to them: “This is what Jehovah the God of Israel has said, ‘Put each one of YOU his sword on his side. Pass through and return from gate to gate in the camp and kill each one his brother and each one his fellow and each one his intimate acquaintance.’”

[[v2-32-28]]

^<<v2-32-28,28>>^ And the sons of Leʹvi proceeded to do as Moses had said, so that there fell of the people on that day about three^&#42;1^ thousand men.

[NOTE]
====
. “Three,” MLXXSy; Vgc, “twenty-three.”
====

[[v2-32-29]]

^<<v2-32-29,29>>^ And Moses went on to say: “Fill YOUR hand today with power^&#42;1^ for Jehovah, because each one of YOU is against his own son and his own brother, and that he may confer a blessing upon YOU today.”

[NOTE]
====
. Or, “Do empower yourselves today.”
====

[[v2-32-30]]

^<<v2-32-30,30>>^ And it came about on the very next day that Moses proceeded to say to the people: “YOU—YOU have sinned with a great sin, and now I shall go up to Jehovah. Perhaps I can make amends for YOUR sin.”

[[v2-32-31]]

^<<v2-32-31,31>>^ So Moses returned to Jehovah and said: “Ah, but this people has sinned with a great sin, in that they made a god^&#42;1^ of gold for themselves!

[NOTE]
====
. “A god.” Heb., ʼelo·hehʹ, pl. to denote excellence, referring to the one golden calf; LXXVg, “gods.”
====

[[v2-32-32]]

^<<v2-32-32,32>>^ But now if you will pardon their sin,—and if not, wipe me out, please, from your book that you have written.”

[[v2-32-33]]

^<<v2-32-33,33>>^ However, Jehovah said to Moses: “Whoever has sinned against me, I shall wipe him out of my book.

[[v2-32-34]]

^<<v2-32-34,34>>^ And now, come, lead the people to where I have spoken to you of. Look! My angel will go ahead of you, and on the day of my bringing punishment I shall certainly bring punishment upon them for their sin.”

[[v2-32-35]]

^<<v2-32-35,35>>^ And Jehovah began plaguing the people because they had made the calf, which Aaron had made.

'''

xref:002-exodus/002-exodus-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodus/002-exodus-033.adoc#v2-33-0[Próximo Capítulo &#62;]