include::./index.adoc[]

[[v2-14-0]]
=== Exodus, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-14-1]]

^<<v2-14-1,1>>^ Jehovah^&#42;1^ now spoke to Moses, saying:

[NOTE]
====
. Heb., Yeho·wahʹ. See App 1A.
====

[[v2-14-2]]

^<<v2-14-2,2>>^ “Speak to the sons of Israel, that they should turn back and encamp before Pi·ha·hiʹroth between Migʹdol and the sea in view of Baʹal-zeʹphon. In front of it YOU are to encamp by the sea.

[[v2-14-3]]

^<<v2-14-3,3>>^ Then Pharʹaoh will certainly say respecting the sons of Israel, ‘They are wandering in confusion in the land. The wilderness has closed in upon them.’

[[v2-14-4]]

^<<v2-14-4,4>>^ So I shall indeed let Pharʹaoh’s heart become obstinate, and he will certainly chase after them and I shall get glory for myself by means of Pharʹaoh and all his military forces; and the Egyptians will certainly know that I am Jehovah.” Accordingly they did just that.

[[v2-14-5]]

^<<v2-14-5,5>>^ Later it was reported to the king of Egypt that the people had run away. Immediately the heart of Pharʹaoh as well as his servants was changed regarding the people, so that they said: “What is this that we have done, in that we have sent Israel away from slaving for us?”

[[v2-14-6]]

^<<v2-14-6,6>>^ So he proceeded to make his war chariots ready, and he took his people with him.

[[v2-14-7]]

^<<v2-14-7,7>>^ And he proceeded to take six hundred chosen chariots and all the other chariots of Egypt and warriors^&#42;1^ upon every one of them.

[NOTE]
====
. “And warriors.” Lit., “and third men.” Heb., wesha·li·shimʹ; Gr., tri·staʹtas. Though Egyptian monuments usually do not show it, three men rode in a war chariot, one of whom managed the horses while the other two fought from the chariot; also, Assyrian bas-reliefs show a third man as an armor-bearer or an umbrella-bearer.
====

[[v2-14-8]]

^<<v2-14-8,8>>^ Thus Jehovah^&#42;1^ let the heart of Pharʹaoh the king of Egypt become obstinate, and he went chasing after the sons of Israel, while the sons of Israel were going out with uplifted hand.

[NOTE]
====
. Heb., Yeho·wahʹ. See App 1A.
====

[[v2-14-9]]

^<<v2-14-9,9>>^ And the Egyptians went chasing after them, and all the chariot horses of Pharʹaoh and his cavalrymen and his military forces were overtaking them while camping by the sea, by Pi·ha·hiʹroth in view of Baʹal-zeʹphon.

[[v2-14-10]]

^<<v2-14-10,10>>^ When Pharʹaoh got close by, the sons of Israel began to raise their eyes and here the Egyptians were marching after them; and the sons of Israel got quite afraid and began to cry out to Jehovah.

[[v2-14-11]]

^<<v2-14-11,11>>^ And they proceeded to say to Moses: “Is it because there are no burial places at all in Egypt that you have taken us here to die in the wilderness? What is this that you have done to us in leading us out of Egypt?

[[v2-14-12]]

^<<v2-14-12,12>>^ Is this not the word we spoke to you in Egypt, saying, ‘Let us alone, that we may serve the Egyptians’? For it is better for us to serve the Egyptians than for us to die in the wilderness.”

[[v2-14-13]]

^<<v2-14-13,13>>^ Then Moses said to the people: “Do not be afraid. Stand firm and see the salvation of Jehovah, which he will perform for YOU today. For the Egyptians whom YOU do see today YOU will not see again, no, never again.

[[v2-14-14]]

^<<v2-14-14,14>>^ Jehovah will himself fight for YOU, and YOU yourselves will be silent.”

[[v2-14-15]]

^<<v2-14-15,15>>^ Jehovah now said to Moses: “Why do you keep crying out to me? Speak to the sons of Israel that they should break camp.

[[v2-14-16]]

^<<v2-14-16,16>>^ As for you, lift up your rod and stretch your hand out over the sea and split it apart, that the sons of Israel may go through the midst of the sea on dry land.

[[v2-14-17]]

^<<v2-14-17,17>>^ As for me, here I am letting the hearts of the Egyptians become obstinate, that they may go in after them and that I may get glory for myself by means of Pharʹaoh and all his military forces, his war chariots and his cavalrymen.

[[v2-14-18]]

^<<v2-14-18,18>>^ And the Egyptians will certainly know that I am Jehovah when I get glory for myself by means of Pharʹaoh, his war chariots and his cavalrymen.”

[[v2-14-19]]

^<<v2-14-19,19>>^ Then the angel of the &#91;true&#93; God who was going ahead of the camp of Israel departed and went to their rear, and the pillar of cloud departed from their van and stood in the rear of them.

[[v2-14-20]]

^<<v2-14-20,20>>^ So it came in between the camp of the Egyptians and the camp of Israel. On the one hand it proved to be a cloud together with darkness. On the other hand it kept lighting up the night. And this group did not come near that group all night long.

[[v2-14-21]]

^<<v2-14-21,21>>^ Moses now stretched his hand out over the sea; and Jehovah began making the sea go back by a strong east wind all night long and converting the sea basin into dry ground, and the waters were being split apart.

[[v2-14-22]]

^<<v2-14-22,22>>^ At length the sons of Israel went through the midst of the sea on dry land, while the waters were a wall to them on their right hand and on their left.

[[v2-14-23]]

^<<v2-14-23,23>>^ And the Egyptians took up the pursuit, and all the horses of Pharʹaoh, his war chariots and his cavalrymen began going in after them, into the midst of the sea.

[[v2-14-24]]

^<<v2-14-24,24>>^ And it came about during the morning watch^&#42;1^ that Jehovah began to look out upon the camp of the Egyptians from within the pillar of fire and cloud, and he went throwing the camp of the Egyptians into confusion.

[NOTE]
====
. The third and last watch according to the Hebrews, from about 2 a.m. to 6 a.m.
====

[[v2-14-25]]

^<<v2-14-25,25>>^ And he kept taking wheels off their chariots so that they were driving them with difficulty; and the Egyptians began to say: “Let us flee from any contact with Israel, because Jehovah certainly fights for them against the Egyptians.”

[[v2-14-26]]

^<<v2-14-26,26>>^ Finally Jehovah said to Moses: “Stretch your hand out over the sea, that the waters may come back over the Egyptians, their war chariots and their cavalrymen.”

[[v2-14-27]]

^<<v2-14-27,27>>^ Moses at once stretched his hand out over the sea, and the sea began to come back to its normal condition at the approaching of morning. All the while the Egyptians were fleeing from encountering it, but Jehovah shook the Egyptians off into the midst of the sea.

[[v2-14-28]]

^<<v2-14-28,28>>^ And the waters kept coming back. Finally they covered the war chariots and the cavalrymen belonging to all of Pharʹaoh’s military forces and who had gone into the sea after them. Not so much as one among them was let remain.

[[v2-14-29]]

^<<v2-14-29,29>>^ As for the sons of Israel, they walked on dry land in the midst of the seabed, and the waters were for them a wall on their right hand and on their left.

[[v2-14-30]]

^<<v2-14-30,30>>^ Thus on that day Jehovah saved Israel from the hand of the Egyptians, and Israel got to see the Egyptians dead on the seashore.

[[v2-14-31]]

^<<v2-14-31,31>>^ Israel also got to see the great hand that Jehovah put in action against the Egyptians; and the people began to fear Jehovah and to put faith in Jehovah and in Moses his servant.

'''

xref:002-exodus/002-exodus-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodus/002-exodus-015.adoc#v2-15-0[Próximo Capítulo &#62;]