include::./index.adoc[]

[[v2-8-0]]
=== Exodus, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-8-1]]

^<<v2-8-1,1>>^ ^&#42;1^ Then Jehovah said to Moses: “Go in to Pharʹaoh, and you must say to him, ‘This is what Jehovah has said: “Send my people away that they may serve me.

[NOTE]
====
. MLXX make this 7:26.
====

[[v2-8-2]]

^<<v2-8-2,2>>^ And if you keep refusing to send them away, here I am plaguing all your territory with frogs.

[[v2-8-3]]

^<<v2-8-3,3>>^ And the Nile River will fairly teem with frogs, and they will certainly come up and enter into your house and your inner bedroom and upon your couch and into the houses of your servants and on your people and into your ovens and into your kneading troughs.

[[v2-8-4]]

^<<v2-8-4,4>>^ And on you and on your people and on all your servants the frogs will come up.”’”

[[v2-8-5]]

^<<v2-8-5,5>>^ ^&#42;1^ Later on Jehovah said to Moses: “Say to Aaron, ‘Stretch your hand with your rod out over the rivers, the Nile canals and the reedy pools and make the frogs come up over the land of Egypt.’”

[NOTE]
====
. MLXX begin chapter 8 here.
====

[[v2-8-6]]

^<<v2-8-6,6>>^ At that Aaron stretched his hand out over the waters of Egypt, and the frogs began to come up and to cover the land of Egypt.

[[v2-8-7]]

^<<v2-8-7,7>>^ However, the magic-practicing priests did the same thing by their secret arts and made the frogs come up over the land of Egypt.

[[v2-8-8]]

^<<v2-8-8,8>>^ In time Pharʹaoh called Moses and Aaron and said: “Entreat Jehovah that he may remove the frogs from me and my people, as I want to send the people away that they may sacrifice to Jehovah.”

[[v2-8-9]]

^<<v2-8-9,9>>^ Then Moses said to Pharʹaoh: “You take the glory over me to say^&#42;1^ when I shall make entreaty for you and your servants and your people in order to cut the frogs off from you and your houses. Only in the Nile River will they be left.”

[NOTE]
====
. Possibly, “explain to me.”
====

[[v2-8-10]]

^<<v2-8-10,10>>^ To this he said: “Tomorrow.” So he said: “It will be according to your word, in order that you may know that there is no one else like Jehovah our God,

[[v2-8-11]]

^<<v2-8-11,11>>^ in that the frogs will certainly turn away from you and your houses and your servants and your people. Only in the Nile River will they be left.”

[[v2-8-12]]

^<<v2-8-12,12>>^ Accordingly Moses and Aaron went out from Pharʹaoh, and Moses cried out to Jehovah because of the frogs that He had put upon Pharʹaoh.

[[v2-8-13]]

^<<v2-8-13,13>>^ Then Jehovah did according to Moses’ word, and the frogs began to die off from the houses, the courtyards and the fields.

[[v2-8-14]]

^<<v2-8-14,14>>^ And they went piling them up, heaps upon heaps, and the land began to stink.

[[v2-8-15]]

^<<v2-8-15,15>>^ When Pharʹaoh got to see that relief had taken place, he made his heart unresponsive;^&#42;1^ and he did not listen to them, just as Jehovah had spoken.

[NOTE]
====
. “He made . . . unresponsive,” in agreement with Sam. In M this verb is in the infinitive absolute, indefinite as to time.
====

[[v2-8-16]]

^<<v2-8-16,16>>^ Jehovah now said to Moses: “Say to Aaron, ‘Stretch your rod out and strike the dust of the earth, and it must become gnats in all the land of Egypt.’”

[[v2-8-17]]

^<<v2-8-17,17>>^ And they proceeded to do this. So Aaron stretched out his hand with his rod and struck the dust of the earth, and the gnats^&#42;1^ came to be on man and beast. All the dust of the earth became gnats in all the land of Egypt.

[NOTE]
====
. Or, “the mosquitoes.” Heb., hak·kin·namʹ. Without much probability for it, historian Josephus (Jewish Antiquities, Book II, chapter 14, ¶3) explains this word to mean lice, and the Talmud also uses the form kin·nimʹ for lice.
====

[[v2-8-18]]

^<<v2-8-18,18>>^ And the magic-practicing priests tried to do the same by their secret arts, in order to bring forth gnats, but they were unable. And the gnats came to be on man and beast.

[[v2-8-19]]

^<<v2-8-19,19>>^ Hence the magic-practicing priests said to Pharʹaoh: “It is the finger of God!” But Pharʹaoh’s heart continued to be obstinate, and he did not listen to them, just as Jehovah had spoken.

[[v2-8-20]]

^<<v2-8-20,20>>^ Then Jehovah said to Moses: “Get up early in the morning and take a position in front of Pharʹaoh. Look! He is coming out to the water! And you must say to him, ‘This is what Jehovah has said: “Send my people away that they may serve me.^&#42;1^

[NOTE]
====
. “That they may serve (worship) me.” Heb., weya·ʽav·dhuʹni; Gr., la·treuʹso·sin, “they may render sacred service.” See 3:12 ftn.
====

[[v2-8-21]]

^<<v2-8-21,21>>^ But if you are not sending my people away, here I am sending upon you and your servants and your people and into your houses the gadfly;^&#42;1^ and the houses of Egypt will simply be full of the gadfly, and also the ground upon which they are.

[NOTE]
====
. “Dog fly,” LXX.
====

[[v2-8-22]]

^<<v2-8-22,22>>^ And on that day I shall certainly make the land of Goʹshen upon which my people are standing distinct, that no gadfly may exist there; in order that you may know that I am Jehovah in the midst of the earth.^&#42;1^

[NOTE]
====
. Or, “I, Jehovah, am in the midst of the earth (land).”
====

[[v2-8-23]]

^<<v2-8-23,23>>^ And I shall indeed set a demarcation between my people and your people. Tomorrow this sign will take place.”’”

[[v2-8-24]]

^<<v2-8-24,24>>^ And Jehovah proceeded to do so; and heavy swarms of gadflies began to invade the house of Pharʹaoh and the houses of his servants and all the land of Egypt. The land came to ruin as a result of the gadflies.

[[v2-8-25]]

^<<v2-8-25,25>>^ Finally Pharʹaoh called Moses and Aaron and said: “Go, sacrifice to YOUR God^&#42;1^ in the land.”

[NOTE]
====
. “To your God.” Heb., lEʼ·lo·heh·khemʹ; TJLXXBagsterSy, “Jehovah your God.”
====

[[v2-8-26]]

^<<v2-8-26,26>>^ But Moses said: “It is not admissible to do so, because we would sacrifice to Jehovah our God a thing detestable to the Egyptians. Suppose we would sacrifice a thing detestable to the Egyptians before their eyes; would they not stone us?

[[v2-8-27]]

^<<v2-8-27,27>>^ We shall go a journey of three days into the wilderness and we shall definitely sacrifice to Jehovah our God just as he has said to us.”

[[v2-8-28]]

^<<v2-8-28,28>>^ Pharʹaoh now said: “I—I shall send YOU away, and YOU will indeed sacrifice to Jehovah YOUR God in the wilderness. Only do not make it quite so far away that YOU are going. Make entreaty in my behalf.”

[[v2-8-29]]

^<<v2-8-29,29>>^ Then Moses said: “Here I am going forth from you, and I shall indeed make entreaty to Jehovah, and the gadflies will certainly turn away from Pharʹaoh, his servants and his people tomorrow. Only let not Pharʹaoh trifle again in not sending the people away to sacrifice to Jehovah.”

[[v2-8-30]]

^<<v2-8-30,30>>^ After that Moses went out from Pharʹaoh and made entreaty to Jehovah.

[[v2-8-31]]

^<<v2-8-31,31>>^ So Jehovah did according to Moses’ word, and the gadflies turned away from Pharʹaoh, his servants and his people. Not one was left.

[[v2-8-32]]

^<<v2-8-32,32>>^ However, Pharʹaoh made his heart unresponsive this time also and did not send the people away.

'''

xref:002-exodus/002-exodus-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodus/002-exodus-009.adoc#v2-9-0[Próximo Capítulo &#62;]