include::./index.adoc[]

[[v2-25-0]]
=== Exodus, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-25-1]]

^<<v2-25-1,1>>^ And Jehovah proceeded to speak to Moses, saying:

[[v2-25-2]]

^<<v2-25-2,2>>^ “Speak to the sons of Israel, that they may take up a contribution^&#42;1^ for me: From every man whose heart incites him YOU people are to take up the contribution of mine.

[NOTE]
====
. Or, “sacred portion; heave offering.”
====

[[v2-25-3]]

^<<v2-25-3,3>>^ And this is the contribution that YOU are to take up from them: gold and silver and copper,

[[v2-25-4]]

^<<v2-25-4,4>>^ and blue thread, and wool dyed reddish purple, and coccus scarlet material, and fine linen, and goat’s hair,

[[v2-25-5]]

^<<v2-25-5,5>>^ and ram skins dyed red, and sealskins,^&#42;1^ and acacia wood;

[NOTE]
====
. Or, “tahash leather.” Heb., techa·shimʹ.
====

[[v2-25-6]]

^<<v2-25-6,6>>^ oil for the luminary, balsam oil for the anointing oil and for perfumed incense;

[[v2-25-7]]

^<<v2-25-7,7>>^ and onyx stones and setting stones for the ephʹod^&#42;1^ and for the breastpiece.

[NOTE]
====
. Apparently an apronlike garment consisting of front and back parts.
====

[[v2-25-8]]

^<<v2-25-8,8>>^ And they must make a sanctuary for me, as I must tabernacle in the midst of them.

[[v2-25-9]]

^<<v2-25-9,9>>^ According to all that I am showing you as the pattern of the tabernacle^&#42;1^ and pattern of all its furnishings, that is the way YOU are to make it.

[NOTE]
====
. Or, “the residence place.”
====

[[v2-25-10]]

^<<v2-25-10,10>>^ “And they must make an Ark^&#42;1^ of acacia wood, two and a half cubits^&#42;2^ its length and a cubit and a half its width and a cubit and a half its height.

[NOTE]
====
. “An Ark of.” Heb., ʼarohnʹ; different from te·vathʹ used in Ex 2:3 and Ge 6:14; Lat., arʹcam.
. A cubit equaled 44.5 cm (17.5 in.).
====

[[v2-25-11]]

^<<v2-25-11,11>>^ And you must overlay it with pure gold. Inside and outside you are to overlay it, and you must make a border of gold round about upon it.

[[v2-25-12]]

^<<v2-25-12,12>>^ And you must cast four rings of gold for it and put them above its four feet, with two rings upon the one side of it and two rings upon its other side.

[[v2-25-13]]

^<<v2-25-13,13>>^ And you must make poles of acacia wood and overlay them with gold.

[[v2-25-14]]

^<<v2-25-14,14>>^ And you must put the poles through the rings upon the sides of the Ark in order to carry the Ark with them.

[[v2-25-15]]

^<<v2-25-15,15>>^ In the rings of the Ark the poles are to stay. They are not to be removed from it.

[[v2-25-16]]

^<<v2-25-16,16>>^ And you must place in the Ark the testimony that I shall give you.

[[v2-25-17]]

^<<v2-25-17,17>>^ “And you must make a cover^&#42;1^ of pure gold, two and a half cubits its length and a cubit and a half its width.

[NOTE]
====
. Or, “mercy seat; propitiatory.” Heb., khap·poʹreth; Lat., pro·pi·ti·a·toʹri·um. See Heb 9:5 ftn.
====

[[v2-25-18]]

^<<v2-25-18,18>>^ And you must make two cherubs of gold. Of hammered work you are to make them on both ends of the cover.

[[v2-25-19]]

^<<v2-25-19,19>>^ And make one cherub on this end and one cherub on that end. On the cover YOU are to make the cherubs at its two ends.

[[v2-25-20]]

^<<v2-25-20,20>>^ And the cherubs must be spreading out their two wings upward, screening over the cover with their wings, with their faces one toward the other. Toward the cover the faces of the cherubs should be.

[[v2-25-21]]

^<<v2-25-21,21>>^ And you must place the cover above upon the Ark, and in the Ark you will place the testimony that I shall give you.

[[v2-25-22]]

^<<v2-25-22,22>>^ And I will present myself to you there and speak with you from above the cover, from between the two cherubs that are upon the ark of the testimony, even all that I shall command you for the sons of Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ “And you must make a table of acacia wood, two cubits its length and a cubit its width and a cubit and a half its height.

[[v2-25-24]]

^<<v2-25-24,24>>^ And you must overlay it with pure gold, and you must make for it a border of gold round about.

[[v2-25-25]]

^<<v2-25-25,25>>^ And you must make for it a rim of a handbreadth^&#42;1^ round about, and you must make the border of gold for its rim round about.

[NOTE]
====
. About 7.4 cm (2.9 in.).
====

[[v2-25-26]]

^<<v2-25-26,26>>^ And you must make for it four rings of gold and place the rings on the four corners that are for the four feet.

[[v2-25-27]]

^<<v2-25-27,27>>^ The rings should be close by the rim as supports for the poles to carry the table.

[[v2-25-28]]

^<<v2-25-28,28>>^ And you must make the poles of acacia wood and overlay them with gold, and they must carry^&#42;1^ the table with them.

[NOTE]
====
. “They must carry,” SamSy.
====

[[v2-25-29]]

^<<v2-25-29,29>>^ “And you must make its dishes and its cups and its pitchers and its bowls with which they will pour &#91;libations&#93;.^&#42;1^ You are to make them out of pure gold.

[NOTE]
====
. Lit., “with which it is to be poured.”
====

[[v2-25-30]]

^<<v2-25-30,30>>^ And you must put the showbread^&#42;1^ upon the table before me constantly.

[NOTE]
====
. Or, “bread of Presence.” Heb., leʹchem pa·nimʹ; Vg, “loaves of presentation.”
====

[[v2-25-31]]

^<<v2-25-31,31>>^ “And you must make a lampstand of pure gold. Of hammered work the lampstand is to be made. Its base,^&#42;1^ its branches, its cups, its knobs and its blossoms are to proceed out from it.

[NOTE]
====
. Or, “thigh; flank.”
====

[[v2-25-32]]

^<<v2-25-32,32>>^ And six branches are running out from its sides, three branches of the lampstand from its one side and three branches of the lampstand from its other side.

[[v2-25-33]]

^<<v2-25-33,33>>^ Three cups shaped like flowers of almond are on the one set of branches, with knobs and blossoms alternating, and three cups shaped like flowers of almond on the other set of branches, with knobs and blossoms alternating. This is the way it is with the six branches running out from the lampstand.

[[v2-25-34]]

^<<v2-25-34,34>>^ And on the lampstand are four cups shaped like flowers of almond, with its knobs and its blossoms alternating.

[[v2-25-35]]

^<<v2-25-35,35>>^ And the knob under two branches is out of it and the knob under the two other branches is out of it and the knob under two more branches is out of it, for the six branches running out from the lampstand.

[[v2-25-36]]

^<<v2-25-36,36>>^ Their knobs and their branches are to proceed out from it. All of it is one piece of hammered work, of pure gold.

[[v2-25-37]]

^<<v2-25-37,37>>^ And you must make seven lamps for it; and the lamps must be lit up, and they must shine upon the area in front of it.

[[v2-25-38]]

^<<v2-25-38,38>>^ And its snuffers and its fire holders are of pure gold.

[[v2-25-39]]

^<<v2-25-39,39>>^ Of a talent^&#42;1^ of pure gold he should make it with all these utensils of it.

[NOTE]
====
. About 34.2 kg (1101 oz t). See App 8A.
====

[[v2-25-40]]

^<<v2-25-40,40>>^ And see that you make them after their pattern that was shown to you in the mountain.

'''

xref:002-exodus/002-exodus-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodus/002-exodus-026.adoc#v2-26-0[Próximo Capítulo &#62;]