include::./index.adoc[]

[[v2-35-0]]
=== Exodus, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-35-1]]

^<<v2-35-1,1>>^ Later Moses called the entire assembly of the sons of Israel together and said to them: “These are the words^&#42;1^ that Jehovah has commanded, to do them:

[NOTE]
====
. Or, “things.”
====

[[v2-35-2]]

^<<v2-35-2,2>>^ Six days may work be done, but on the seventh day it will become something holy to YOU, a sabbath of complete rest to Jehovah. Anybody doing work on it will be put to death.

[[v2-35-3]]

^<<v2-35-3,3>>^ YOU must not light a fire in any of YOUR dwelling places on the sabbath day.”

[[v2-35-4]]

^<<v2-35-4,4>>^ And Moses went on to say to the entire assembly of the sons of Israel: “This is the word that Jehovah has commanded, saying,

[[v2-35-5]]

^<<v2-35-5,5>>^ ‘From among yourselves take up a contribution for Jehovah. Let every willing-hearted one bring it as Jehovah’s contribution, namely, gold and silver and copper

[[v2-35-6]]

^<<v2-35-6,6>>^ and blue thread and wool dyed reddish purple and coccus scarlet material and fine linen and goat’s hair

[[v2-35-7]]

^<<v2-35-7,7>>^ and ram skins dyed red and sealskins and acacia wood

[[v2-35-8]]

^<<v2-35-8,8>>^ and oil for the luminary and balsam oil for the anointing oil and for the perfumed incense

[[v2-35-9]]

^<<v2-35-9,9>>^ and onyx stones and setting stones for the ephʹod and for the breastpiece.

[[v2-35-10]]

^<<v2-35-10,10>>^ “‘And let all the wise-hearted ones among YOU come and make all that Jehovah has commanded,

[[v2-35-11]]

^<<v2-35-11,11>>^ namely, the tabernacle with its tent and its covering, its hooks and its panel frames,^&#42;1^ its bars, its pillars and its socket pedestals;

[NOTE]
====
. See 26:15 ftn.
====

[[v2-35-12]]

^<<v2-35-12,12>>^ the Ark and its poles, the cover and the curtain of the screen;

[[v2-35-13]]

^<<v2-35-13,13>>^ the table and its poles and all its utensils and the showbread;^&#42;1^

[NOTE]
====
. Or, “bread of Presence.” Vg, “loaves of presentation.” See 25:30.
====

[[v2-35-14]]

^<<v2-35-14,14>>^ and the lampstand of illumination and its utensils and its lamps and the oil for illumination;^&#42;1^

[NOTE]
====
. Or, “the luminary; the lamp.”
====

[[v2-35-15]]

^<<v2-35-15,15>>^ and the altar of incense and its poles; and the anointing oil and the perfumed incense; and the screen of the entrance for the tabernacle’s entrance;

[[v2-35-16]]

^<<v2-35-16,16>>^ the altar of burnt offering and the copper grating that is for it, its poles and all its utensils; the basin^&#42;1^ and its stand;

[NOTE]
====
. Or, “laver.”
====

[[v2-35-17]]

^<<v2-35-17,17>>^ the hangings of the courtyard, its pillars and its socket pedestals; and the screen of the gate of the courtyard;

[[v2-35-18]]

^<<v2-35-18,18>>^ the tent pins of the tabernacle and the tent pins of the courtyard and their cords;

[[v2-35-19]]

^<<v2-35-19,19>>^ the garments of knitted work^&#42;1^ for ministering in the sanctuary, the holy garments for Aaron the priest and the garments of his sons for acting as priests.’”

[NOTE]
====
. Or, “garments of official dress.”
====

[[v2-35-20]]

^<<v2-35-20,20>>^ Accordingly all the assembly of the sons of Israel went out from before Moses.

[[v2-35-21]]

^<<v2-35-21,21>>^ Then they came, everyone whose heart impelled him, and they brought, everyone whose spirit incited him, Jehovah’s contribution for the work of the tent of meeting and for all its service and for the holy garments.

[[v2-35-22]]

^<<v2-35-22,22>>^ And they kept coming, the men along with the women, every willing-hearted one. They brought brooches^&#42;1^ and earrings and rings and female ornaments, all sorts of articles of gold, that is, everyone who presented the wave offering of gold to Jehovah.

[NOTE]
====
. Or, “buckles.”
====

[[v2-35-23]]

^<<v2-35-23,23>>^ And all those with whom there were found blue thread and wool dyed reddish purple and coccus scarlet material and fine linen and goat’s hair and ram skins dyed red and sealskins, brought them.

[[v2-35-24]]

^<<v2-35-24,24>>^ All those contributing the contribution of silver and copper brought Jehovah’s contribution, and all those with whom there was found acacia wood for all the work of the service brought it.

[[v2-35-25]]

^<<v2-35-25,25>>^ And all the women who were wise of heart spun with their hands, and they kept bringing as yarn the blue thread and the wool dyed reddish purple, the coccus scarlet material and the fine linen.

[[v2-35-26]]

^<<v2-35-26,26>>^ And all the women whose hearts impelled them with wisdom spun the goat’s hair.

[[v2-35-27]]

^<<v2-35-27,27>>^ And the chieftains brought onyx stones and setting stones for the ephʹod and the breastpiece,

[[v2-35-28]]

^<<v2-35-28,28>>^ and the balsam oil and the oil for illumination and for the anointing oil and for the perfumed incense.

[[v2-35-29]]

^<<v2-35-29,29>>^ Every man and woman whose hearts incited them to bring something for all the work that Jehovah had commanded to make by means of Moses did so; the sons of Israel brought a voluntary offering to Jehovah.

[[v2-35-30]]

^<<v2-35-30,30>>^ Then Moses said to the sons of Israel: “See, Jehovah has called by name Bezʹal·el the son of Uʹri the son of Hur of the tribe of Judah.

[[v2-35-31]]

^<<v2-35-31,31>>^ And he proceeded to fill him with the spirit of God in wisdom, in understanding and in knowledge and in every sort of craftsmanship

[[v2-35-32]]

^<<v2-35-32,32>>^ and for designing devices, for working in gold and silver and copper,

[[v2-35-33]]

^<<v2-35-33,33>>^ and in working of stones to set them and in working of wood to make ingenious products of every sort.

[[v2-35-34]]

^<<v2-35-34,34>>^ And he has put it into his heart that he should teach, he and O·hoʹli·ab the son of A·hisʹa·mach of the tribe of Dan.

[[v2-35-35]]

^<<v2-35-35,35>>^ He has filled them with wisdom of heart to do all the work of a craftsman and an embroiderer and of a weaver in blue thread and wool dyed reddish purple, in coccus scarlet material and fine linen, and of a loom worker, men doing every sort of work and designing devices.

'''

xref:002-exodus/002-exodus-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodus/002-exodus-036.adoc#v2-36-0[Próximo Capítulo &#62;]