include::./index.adoc[]

[[v2-38-0]]
=== Exodus, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-38-1]]

^<<v2-38-1,1>>^ And he went on to make the altar of burnt offering out of acacia wood. Five cubits was its length, and five cubits its width, it being foursquare, and three cubits was its height.

[[v2-38-2]]

^<<v2-38-2,2>>^ Then he made its horns upon its four corners. Its horns proceeded out of it. Next he overlaid it with copper.

[[v2-38-3]]

^<<v2-38-3,3>>^ After that he made all the utensils of the altar, the cans and the shovels and the bowls, the forks and the fire holders. All its utensils he made of copper.

[[v2-38-4]]

^<<v2-38-4,4>>^ He further made for the altar a grating, a network of copper, under its rim, down toward its center.

[[v2-38-5]]

^<<v2-38-5,5>>^ Then he cast four rings on the four extremities near the grating of copper, as supports for the poles.

[[v2-38-6]]

^<<v2-38-6,6>>^ After that he made the poles of acacia wood and overlaid them with copper.

[[v2-38-7]]

^<<v2-38-7,7>>^ Then he put the poles into the rings on the sides of the altar for carrying it with them. He made it a hollow chest of planks.

[[v2-38-8]]

^<<v2-38-8,8>>^ Then he made the basin^&#42;1^ of copper and its stand of copper, by the use of the mirrors^&#42;2^ of the women servants who did organized service^&#42;3^ at the entrance of the tent of meeting.

[NOTE]
====
. Or, “laver.”
. Metal mirrors highly polished for reflecting.
. Lit., “the serving women who served.” Here the two Heb. verbs have the same root, tsa·vaʼʹ, as for military service, suggesting organized service in companies for these women.
====

[[v2-38-9]]

^<<v2-38-9,9>>^ And he proceeded to make the courtyard. For the side toward the Negʹeb, to the south, the hangings of the courtyard were of fine twisted linen, for a hundred cubits.

[[v2-38-10]]

^<<v2-38-10,10>>^ Their twenty pillars and their twenty socket pedestals were of copper. The pegs of the pillars and their joints^&#42;1^ were of silver.

[NOTE]
====
. Or, “hoops; rings; bands; fillets,” for attachments.
====

[[v2-38-11]]

^<<v2-38-11,11>>^ Also, for the north side there were a hundred cubits. Their twenty pillars and their twenty socket pedestals were of copper. The pegs of the pillars and their joints were of silver.

[[v2-38-12]]

^<<v2-38-12,12>>^ But for the west side the hangings were for fifty cubits. Their pillars were ten and their socket pedestals ten. The pegs of the pillars and their joints were of silver.

[[v2-38-13]]

^<<v2-38-13,13>>^ And for the east side toward the sunrising there were fifty cubits.

[[v2-38-14]]

^<<v2-38-14,14>>^ The hangings were for fifteen cubits to the one wing.^&#42;1^ Their pillars were three and their socket pedestals three.

[NOTE]
====
. Lit., “shoulder.”
====

[[v2-38-15]]

^<<v2-38-15,15>>^ And for the other wing, on this as well as that side, of the gate of the courtyard, the hangings were for fifteen cubits. Their pillars were three and their socket pedestals three.

[[v2-38-16]]

^<<v2-38-16,16>>^ All the hangings of the courtyard round about were of fine twisted linen.

[[v2-38-17]]

^<<v2-38-17,17>>^ And the socket pedestals for the pillars were of copper. The pegs of the pillars and their joints were of silver and the overlaying of their tops was of silver, and there were silver joinings for all the pillars of the courtyard.

[[v2-38-18]]

^<<v2-38-18,18>>^ And the screen of the gate of the courtyard was the work of a weaver, of blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen, and twenty cubits was the length, and the height throughout its extent was five cubits equally with the hangings of the courtyard.

[[v2-38-19]]

^<<v2-38-19,19>>^ And their four pillars and their four socket pedestals were of copper. Their pegs were of silver and the overlaying of their heads and their joints were of silver.

[[v2-38-20]]

^<<v2-38-20,20>>^ And all the tent pins for the tabernacle and for the courtyard round about were of copper.

[[v2-38-21]]

^<<v2-38-21,21>>^ The following are the things inventoried of the tabernacle, the tabernacle of the Testimony, which was inventoried at the command of Moses, as the service of the Levites under the guidance of Ithʹa·mar the son of Aaron the priest.

[[v2-38-22]]

^<<v2-38-22,22>>^ And Bezʹal·el the son of Uʹri the son of Hur of the tribe of Judah did all that Jehovah had commanded Moses.

[[v2-38-23]]

^<<v2-38-23,23>>^ And with him was O·hoʹli·ab the son of A·hisʹa·mach of the tribe of Dan, a craftsman and embroiderer and weaver in the blue thread and the wool dyed reddish purple and coccus scarlet material and fine linen.

[[v2-38-24]]

^<<v2-38-24,24>>^ All the gold^&#42;1^ that was used for the work in all the work of the holy place came to the amount of the gold of the wave offering, twenty-nine talents and seven hundred and thirty shekels by the shekel of the holy place.

[NOTE]
====
. The gold alone used for the tabernacle would be worth about $11,269,000 with gold valued at $350 (U.S.) per oz t. Compare 1Ch 29:7 ftn, “Talents.”
====

[[v2-38-25]]

^<<v2-38-25,25>>^ And the silver of the ones registered of the assembly was a hundred talents and one thousand seven hundred and seventy-five shekels by the shekel of the holy place.

[[v2-38-26]]

^<<v2-38-26,26>>^ The half shekel^&#42;1^ for an individual^&#42;2^ was the half of a shekel by the shekel of the holy place, for every man who was passing over to those who were registered from twenty years of age and upward, amounting to six hundred and three thousand five hundred and fifty.

[NOTE]
====
. Lit., “The bekah,” of silver. LXX, “One drachma.”
. Lit., “skull.” The head that was counted for a poll tax.
====

[[v2-38-27]]

^<<v2-38-27,27>>^ And a hundred talents of silver went into the casting of the socket pedestals of the holy place and the socket pedestals of the curtain. A hundred socket pedestals equaled a hundred talents, a talent to a socket pedestal.

[[v2-38-28]]

^<<v2-38-28,28>>^ And out of the thousand seven hundred and seventy-five shekels^&#42;1^ he made pegs for the pillars and overlaid their tops and joined them together.

[NOTE]
====
. “Shekels,” LXX.
====

[[v2-38-29]]

^<<v2-38-29,29>>^ And the copper of the wave offering was seventy talents and two thousand four hundred shekels.

[[v2-38-30]]

^<<v2-38-30,30>>^ And with this he proceeded to make the socket pedestals of the entrance of the tent of meeting and the copper altar and the copper grating that belonged to it, and all the utensils of the altar,

[[v2-38-31]]

^<<v2-38-31,31>>^ and the socket pedestals of the courtyard round about, and the socket pedestals of the gate of the courtyard, and all the tent pins of the tabernacle and all the tent pins of the courtyard round about.

'''

xref:002-exodus/002-exodus-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodus/002-exodus-039.adoc#v2-39-0[Próximo Capítulo &#62;]