include::./index.adoc[]

[[v2-36-0]]
=== Exodus, 36
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-36-1]]

^<<v2-36-1,1>>^ “And Bezʹal·el must work, also O·hoʹli·ab and every wise-hearted man to whom Jehovah has given wisdom and understanding in these things in order to know how to do all the work of the holy service according to all that Jehovah has commanded.”

[[v2-36-2]]

^<<v2-36-2,2>>^ And Moses proceeded to call Bezʹal·el and O·hoʹli·ab and every wise-hearted man into whose heart Jehovah had put wisdom, everyone whose heart impelled him to approach the work in order to do it.

[[v2-36-3]]

^<<v2-36-3,3>>^ Then they took from before Moses all the contribution that the sons of Israel had brought for the work of the holy service so as to do it, and, as for the latter, they still brought to him a voluntary offering morning after morning.

[[v2-36-4]]

^<<v2-36-4,4>>^ And all the wise ones who were doing all the holy work began to come, one man after another, from their work that they were doing,

[[v2-36-5]]

^<<v2-36-5,5>>^ and to say to Moses: “The people are bringing much more than what the service needs for the work that Jehovah has commanded to be done.”

[[v2-36-6]]

^<<v2-36-6,6>>^ So Moses commanded that they should cause an announcement to pass through the camp, saying: “Men and women, do not produce any more stuff for the holy contribution.” With that the people were restrained from bringing it in.

[[v2-36-7]]

^<<v2-36-7,7>>^ And the stuff proved to be enough for all the work to be done, and more than enough.

[[v2-36-8]]

^<<v2-36-8,8>>^ And all the wise-hearted among those doing the work went making the tabernacle, the ten tent cloths of fine twisted linen and blue thread and wool dyed reddish purple and coccus scarlet material; with cherubs, the work of an embroiderer, he^&#42;1^ made them.

[NOTE]
====
. “He,” evidently referring to Bezalel.
====

[[v2-36-9]]

^<<v2-36-9,9>>^ The length of each tent cloth was twenty-eight cubits, and the width of each tent cloth four cubits. There was one measure for all the tent cloths.

[[v2-36-10]]

^<<v2-36-10,10>>^ Then he joined five tent cloths one to another, and the five other tent cloths he joined one to another.

[[v2-36-11]]

^<<v2-36-11,11>>^ After that he made loops of blue thread upon the edge of the one tent cloth at the junction end. He did the same on the edge of the outermost tent cloth at the other place of junction.

[[v2-36-12]]

^<<v2-36-12,12>>^ He made fifty loops on the one tent cloth, and he made fifty loops on the extremity of the tent cloth that was at the other place of junction, the loops being opposite one another.

[[v2-36-13]]

^<<v2-36-13,13>>^ Finally he made fifty hooks of gold and joined the tent cloths to one another by the hooks, so that it became one tabernacle.

[[v2-36-14]]

^<<v2-36-14,14>>^ And he went on to make tent cloths of goat’s hair for the tent upon the tabernacle. Eleven tent cloths were what he made.

[[v2-36-15]]

^<<v2-36-15,15>>^ The length of each tent cloth was thirty cubits, and the width of each tent cloth four cubits. There was one measure for the eleven tent cloths.

[[v2-36-16]]

^<<v2-36-16,16>>^ Then he joined five tent cloths together by themselves and the six other tent cloths by themselves.

[[v2-36-17]]

^<<v2-36-17,17>>^ Next he made fifty loops upon the edge of the outermost tent cloth at the place of junction, and he made fifty loops upon the edge of the other tent cloth that joined with it.

[[v2-36-18]]

^<<v2-36-18,18>>^ After that he made fifty hooks of copper for joining the tent together to become one piece.

[[v2-36-19]]

^<<v2-36-19,19>>^ And he proceeded to make a covering for the tent out of ram skins dyed red and a covering out of sealskins up on top.

[[v2-36-20]]

^<<v2-36-20,20>>^ Then he made the panel frames for the tabernacle out of acacia wood, standing on end.

[[v2-36-21]]

^<<v2-36-21,21>>^ Ten cubits was the length of a panel frame, and one cubit and a half the width of each panel frame.

[[v2-36-22]]

^<<v2-36-22,22>>^ Each panel frame had two tenons fitted one to the other. That is the way he did to all the panel frames of the tabernacle.

[[v2-36-23]]

^<<v2-36-23,23>>^ So he made the panel frames for the tabernacle, twenty panel frames for the side toward the Negʹeb, to the south.

[[v2-36-24]]

^<<v2-36-24,24>>^ And he made forty socket pedestals of silver for beneath the twenty panel frames, two socket pedestals beneath the one panel frame with its two tenons and two socket pedestals beneath the other panel frame with its two tenons.

[[v2-36-25]]

^<<v2-36-25,25>>^ And for the other side of the tabernacle, the northern side, he made twenty panel frames

[[v2-36-26]]

^<<v2-36-26,26>>^ and their forty socket pedestals of silver, two socket pedestals beneath the one panel frame and two socket pedestals beneath the other panel frame.

[[v2-36-27]]

^<<v2-36-27,27>>^ And for the rear sections of the tabernacle to the west^&#42;1^ he made six panel frames.

[NOTE]
====
. Lit., “sea,” that is, the Mediterranean.
====

[[v2-36-28]]

^<<v2-36-28,28>>^ And he made two panel frames as corner posts of the tabernacle on its two rear sections.

[[v2-36-29]]

^<<v2-36-29,29>>^ And they proved to be duplicates at the bottom and together they came to be twins to the top of each one at the first ring. That is what he did to them both, to the two corner posts.

[[v2-36-30]]

^<<v2-36-30,30>>^ So they amounted to eight panel frames and their socket pedestals of silver to sixteen, two socket pedestals next to two socket pedestals beneath each panel frame.

[[v2-36-31]]

^<<v2-36-31,31>>^ And he went on to make bars of acacia wood, five for the panel frames of the one side of the tabernacle

[[v2-36-32]]

^<<v2-36-32,32>>^ and five bars for the panel frames of the other side of the tabernacle and five bars for the panel frames of the tabernacle for the two rear sections to the west.

[[v2-36-33]]

^<<v2-36-33,33>>^ Then he made the middle bar to run through at the middle of the panel frames from one end to the other.

[[v2-36-34]]

^<<v2-36-34,34>>^ And he overlaid the panel frames with gold, and he made their rings of gold as supports for the bars, and he went on to overlay the bars with gold.

[[v2-36-35]]

^<<v2-36-35,35>>^ And he proceeded to make a curtain of blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen. With the work of an embroiderer he made it with cherubs.

[[v2-36-36]]

^<<v2-36-36,36>>^ Then he made for it four acacia pillars and overlaid them with gold, their pegs being of gold, and cast four socket pedestals of silver for them.

[[v2-36-37]]

^<<v2-36-37,37>>^ And he went on to make a screen for the entrance of the tent out of blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen, the work of a weaver,

[[v2-36-38]]

^<<v2-36-38,38>>^ and its five pillars and their pegs. And he overlaid their tops and their joints with gold, but their five socket pedestals were of copper.

'''

xref:002-exodus/002-exodus-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodus/002-exodus-037.adoc#v2-37-0[Próximo Capítulo &#62;]