include::./index.adoc[]

[[v2-3-0]]
=== Exodus, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-3-1]]

^<<v2-3-1,1>>^ And Moses became a shepherd of the flock of Jethʹro, the priest of Midʹi·an, whose son-in-law he was.^&#42;1^ While he was driving the flock to the west side of the wilderness, he came at length to the mountain of the &#91;true&#93; God, to Hoʹreb.

[NOTE]
====
. Or, “Jethro, . . . his father-in-law.”
====

[[v2-3-2]]

^<<v2-3-2,2>>^ Then Jehovah’s^&#42;1^ angel appeared to him in a flame of fire in the midst of a thornbush. As he kept looking, why, here the thornbush was burning with the fire and yet the thornbush was not consumed.

[NOTE]
====
. Heb., Yeho·wahʹ. See App 1A.
====

[[v2-3-3]]

^<<v2-3-3,3>>^ At this Moses said: “Let me just turn aside that I may inspect this great phenomenon, as to why the thornbush is not burnt up.”

[[v2-3-4]]

^<<v2-3-4,4>>^ When Jehovah^&#42;1^ saw that he turned aside to inspect, God at once called to him out of the midst of the thornbush and said: “Moses! Moses!” to which he said: “Here I am.”

[NOTE]
====
. “God,” Sam; that is, Jehovah’s angel who spoke for Him. See vs 2.
====

[[v2-3-5]]

^<<v2-3-5,5>>^ Then he said: “Do not come near here. Draw your sandals from off your feet, because the place where you are standing is holy ground.”

[[v2-3-6]]

^<<v2-3-6,6>>^ And he went on to say: “I am the God of your father,^&#42;1^ the God of Abraham, the God of Isaac and the God of Jacob.” Then Moses concealed his face, because he was afraid to look at the &#91;true&#93; God.^&#42;2^

[NOTE]
====
. “Father,” MLXXSyVg; Sam, “fathers.”
. See App 1F.
====

[[v2-3-7]]

^<<v2-3-7,7>>^ And Jehovah added: “Unquestionably I have seen the affliction of my people who are in Egypt, and I have heard their outcry as a result of those who drive them to work; because I well know the pains they suffer.

[[v2-3-8]]

^<<v2-3-8,8>>^ And I am proceeding to go down to deliver them out of the hand of the Egyptians and to bring them up out of that land to a land good and spacious, to a land flowing with milk and honey, to the locality of the Caʹnaan·ites and the Hitʹtites and the Amʹor·ites and the Perʹiz·zites and the Hiʹvites and the Jebʹu·sites.

[[v2-3-9]]

^<<v2-3-9,9>>^ And now, look! the outcry of the sons of Israel has come to me, and I have seen also the oppression with which the Egyptians are oppressing them.

[[v2-3-10]]

^<<v2-3-10,10>>^ And now come and let me send you to Pharʹaoh, and you bring my people the sons of Israel out of Egypt.”

[[v2-3-11]]

^<<v2-3-11,11>>^ However, Moses said to the &#91;true&#93; God: “Who am I that I should go to Pharʹaoh and that I have to bring the sons of Israel out of Egypt?”

[[v2-3-12]]

^<<v2-3-12,12>>^ To this he said: “Because I shall prove to be with you, and this is the sign for you that it is I who have sent you: After you have brought the people out of Egypt, YOU people will serve^&#42;1^ the &#91;true&#93; God on this mountain.”

[NOTE]
====
. “You people will serve (worship).” Heb., ta·ʽav·dhunʹ; Gr., la·treuʹse·te, “you will render sacred service.” See KB, p. 671, for the rendering “worship a god.” See also Mt 4:10 ftn, “Service.”
====

[[v2-3-13]]

^<<v2-3-13,13>>^ Nevertheless, Moses said to the &#91;true&#93; God: “Suppose I am now come to the sons of Israel and I do say to them, ‘The God of YOUR forefathers has sent me to YOU,’ and they do say to me, ‘What is his name?’ What shall I say to them?”

[[v2-3-14]]

^<<v2-3-14,14>>^ At this God said to Moses: “I SHALL PROVE TO BE WHAT I SHALL PROVE TO BE.”^&#42;1^ And he added: “This is what you are to say to the sons of Israel, ‘I SHALL PROVE TO BE has sent me to YOU.’”

[NOTE]
====
. “I SHALL PROVE TO BE WHAT I SHALL PROVE TO BE.” Heb., אֶהְיֶֽה אֲשֶֽׁר אֶהְיֶֽה (ʼEh·yehʹ ʼAsherʹ ʼEh·yehʹ), God’s own self-designation; Leeser, “I WILL BE THAT I WILL BE”; Rotherham, “I Will Become whatsoever I please.” Gr., E·goʹ ei·mi ho on, “I am The Being,” or, “I am The Existing One”; Lat., eʹgo sum qui sum, “I am Who I am.” ʼEh·yehʹ comes from the Heb. verb ha·yahʹ, “become; prove to be.” Here ʼEh·yehʹ is in the imperfect state, first person sing., meaning “I shall become”; or, “I shall prove to be.” The reference here is not to God’s self-existence but to what he has in mind to become toward others. Compare Ge 2:4 ftn, “Jehovah,” where the kindred, but different, Heb. verb ha·wahʹ appears in the divine name.
====

[[v2-3-15]]

^<<v2-3-15,15>>^ Then God said once more to Moses:
“This is what you are to say to the sons of Israel, ‘Jehovah the God of YOUR forefathers, the God of Abraham, the God of Isaac and the God of Jacob, has sent me to YOU.’ This is my name to time indefinite,^&#42;1^ and this is the memorial of me^&#42;2^ to generation after generation.

[NOTE]
====
. “My name to time indefinite.” Heb., shemiʹ leʽo·lamʹ.
. “The memorial of me.” Heb., zikh·riʹ; Lat., me·mo·ri·aʹle meʹum.
====

[[v2-3-16]]

^<<v2-3-16,16>>^ You go, and you must gather the older men^&#42;1^ of Israel, and you must say to them, ‘Jehovah the God of YOUR forefathers has appeared to me, the God of Abraham, Isaac and Jacob, saying: “I will without fail give attention to YOU and to what is being done to YOU in Egypt.

[NOTE]
====
. Or, “elders.”
====

[[v2-3-17]]

^<<v2-3-17,17>>^ And so I say, I shall bring YOU up out of affliction by the Egyptians to the land of the Caʹnaan·ites and the Hitʹtites and the Amʹor·ites and the Perʹiz·zites and the Hiʹvites and the Jebʹu·sites, to a land flowing with milk and honey.”’

[[v2-3-18]]

^<<v2-3-18,18>>^ “And they will certainly listen to your voice, and you must come, you and the older men of Israel, to the king of Egypt, and YOU men must say to him, ‘Jehovah the God of the Hebrews has come in touch with us, and now we want to go, please, a journey of three days into the wilderness, and we want to sacrifice to Jehovah our God.’

[[v2-3-19]]

^<<v2-3-19,19>>^ And I, even I, well know that the king of Egypt will not give YOU permission to go except by a strong hand.

[[v2-3-20]]

^<<v2-3-20,20>>^ And I shall have to stretch out my hand and strike Egypt with all my wonderful acts that I shall do in the midst of it; and after that he will send YOU out.

[[v2-3-21]]

^<<v2-3-21,21>>^ And I will give this people favor in the eyes of the Egyptians; and it will certainly occur that when YOU go, YOU will not go empty-handed.

[[v2-3-22]]

^<<v2-3-22,22>>^ And each woman must ask from her neighbor and from the woman residing as an alien in her house articles of silver and articles of gold and mantles, and YOU must put them upon YOUR sons and YOUR daughters; and YOU must strip the Egyptians.”

'''

xref:002-exodus/002-exodus-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodus/002-exodus-004.adoc#v2-4-0[Próximo Capítulo &#62;]