include::./index.adoc[]

[[v2-24-0]]
=== Exodus, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-24-1]]

^<<v2-24-1,1>>^ And to Moses he said: “Go up to Jehovah, you and Aaron, Naʹdab and A·biʹhu and seventy of the older men of Israel, and YOU must bow down^&#42;1^ from a distance.

[NOTE]
====
. Or, “you must worship.”
====

[[v2-24-2]]

^<<v2-24-2,2>>^ And Moses by himself must approach Jehovah; but they should not approach, and the people should not go up with him.”

[[v2-24-3]]

^<<v2-24-3,3>>^ Then Moses came and related to the people all the words of Jehovah and all the judicial decisions, and all the people answered with one voice and said: “All the words that Jehovah has spoken we are willing to do.”

[[v2-24-4]]

^<<v2-24-4,4>>^ Accordingly Moses wrote down all the words of Jehovah. Then he got up early in the morning and built at the foot of the mountain an altar and twelve pillars corresponding with the twelve tribes of Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ After that he sent young men of the sons of Israel and they offered up burnt offerings and sacrificed bulls as sacrifices, as communion sacrifices to Jehovah.

[[v2-24-6]]

^<<v2-24-6,6>>^ Then Moses took half the blood and put it in bowls, and half the blood he sprinkled upon the altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ Finally he took the book of the covenant^&#42;1^ and read it in the ears of the people. Then they said: “All that Jehovah has spoken we are willing to do and be obedient.”

[NOTE]
====
. “Book of the covenant.” This doubtless contained the legislation set out in 20:22–23:33.
====

[[v2-24-8]]

^<<v2-24-8,8>>^ So Moses took the blood and sprinkled it upon the people and said: “Here is the blood of the covenant that Jehovah has concluded with YOU as respects all these words.”

[[v2-24-9]]

^<<v2-24-9,9>>^ And Moses and Aaron, Naʹdab and A·biʹhu and seventy of the older men of Israel proceeded to go up,

[[v2-24-10]]

^<<v2-24-10,10>>^ and they got to see the God of Israel. And under his feet there was what seemed like a work of sapphire flagstones and like the very heavens for purity.

[[v2-24-11]]

^<<v2-24-11,11>>^ And he did not put out his hand against the distinguished men of the sons of Israel, but they got a vision of the &#91;true&#93; God and ate and drank.

[[v2-24-12]]

^<<v2-24-12,12>>^ Jehovah now said to Moses: “Come up to me in the mountain and stay there, as I want to give you the stone tablets and the law and the commandment that I must write in order to teach them.”

[[v2-24-13]]

^<<v2-24-13,13>>^ So Moses and Joshua^&#42;1^ his minister^&#42;2^ got up and Moses went up into the mountain of the &#91;true&#93; God.

[NOTE]
====
. See 17:9 ftn.
. “His minister (attendant; waiter; servant).” Heb., meshor·thohʹ; Lat., mi·niʹster.
====

[[v2-24-14]]

^<<v2-24-14,14>>^ But to the older men he had said: “YOU wait for us in this place until we return to YOU. And, look! Aaron and Hur are with YOU. Whoever has a case at law,^&#42;1^ let him approach them.”

[NOTE]
====
. Lit., “Whoever is an owner of words,” that is, a litigant or controversialist.
====

[[v2-24-15]]

^<<v2-24-15,15>>^ Thus Moses went up into the mountain while the cloud was covering the mountain.

[[v2-24-16]]

^<<v2-24-16,16>>^ And Jehovah’s glory continued to reside^&#42;1^ upon Mount Siʹnai, and the cloud continued to cover it for six days. At length on the seventh day he called to Moses from the midst of the cloud.

[NOTE]
====
. Or, “to extend like a tent.”
====

[[v2-24-17]]

^<<v2-24-17,17>>^ And to the eyes of the sons of Israel the sight of Jehovah’s glory was like a devouring fire on the mountaintop.

[[v2-24-18]]

^<<v2-24-18,18>>^ Then Moses entered into the midst of the cloud and went on up the mountain. And Moses continued in the mountain forty days and forty nights.

'''

xref:002-exodus/002-exodus-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodus/002-exodus-025.adoc#v2-25-0[Próximo Capítulo &#62;]