include::./index.adoc[]

[[v2-28-0]]
=== Exodus, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-28-1]]

^<<v2-28-1,1>>^ “And as for you, bring near to yourself Aaron your brother and his sons with him from the midst of the sons of Israel that he may act as priest to me, Aaron, Naʹdab and A·biʹhu, El·e·aʹzar and Ithʹa·mar, the sons of Aaron.

[[v2-28-2]]

^<<v2-28-2,2>>^ And you must make holy garments for Aaron your brother, for glory and beauty.

[[v2-28-3]]

^<<v2-28-3,3>>^ And you yourself are to speak to all the ones wise with a heart that I have filled with the spirit of wisdom, and they must make Aaron’s garments for sanctifying him, that he may act as priest to me.

[[v2-28-4]]

^<<v2-28-4,4>>^ “And these are the garments that they will make: a breastpiece, and an ephʹod and a sleeveless coat and a robe of checkerwork, a turban and a sash;^&#42;1^ and they must make the holy garments for Aaron your brother and his sons, that he may act as priest to me.

[NOTE]
====
. Or, “belt; girdle.”
====

[[v2-28-5]]

^<<v2-28-5,5>>^ And they themselves will take the gold and the blue thread and the wool dyed reddish purple and coccus scarlet material and the fine linen.

[[v2-28-6]]

^<<v2-28-6,6>>^ “And they must make the ephʹod of gold, blue thread and wool dyed reddish purple, coccus scarlet material and fine twisted linen, the work of an embroiderer.

[[v2-28-7]]

^<<v2-28-7,7>>^ And it is to have two shoulder pieces to be joined at its two extremities, and it must be joined.

[[v2-28-8]]

^<<v2-28-8,8>>^ And the girdle, which is upon it for tying it close, according to its workmanship should be of its materials, of gold, blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen.

[[v2-28-9]]

^<<v2-28-9,9>>^ “And you must take two onyx^&#42;1^ stones and engrave upon them the names of the sons of Israel,

[NOTE]
====
. Or, “car­ne­lian.”
====

[[v2-28-10]]

^<<v2-28-10,10>>^ six of their names upon the one stone and the names of the six remaining ones upon the other stone in the order of their births.

[[v2-28-11]]

^<<v2-28-11,11>>^ With the work of a craftsman in stones, with the engravings of a seal, you are to engrave the two stones with the names of the sons of Israel. Set in settings of gold is how you will make them.

[[v2-28-12]]

^<<v2-28-12,12>>^ And you must put the two stones upon the shoulder pieces of the ephʹod as memorial stones for the sons of Israel; and Aaron must carry their names before Jehovah upon his two shoulder pieces as a memorial.

[[v2-28-13]]

^<<v2-28-13,13>>^ And you must make settings of gold,

[[v2-28-14]]

^<<v2-28-14,14>>^ and two chains of pure gold. As cords you will make them, with the workmanship of a rope; and you must attach the ropelike chains to the settings.

[[v2-28-15]]

^<<v2-28-15,15>>^ “And you must make the breastpiece of judgment with the workmanship of an embroiderer. Like the workmanship of the ephʹod you will make it. Of gold, blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen you will make it.

[[v2-28-16]]

^<<v2-28-16,16>>^ It should be foursquare when doubled, a span of the hand^&#42;1^ being its length and a span of the hand its width.

[NOTE]
====
. About 22.2 cm (8.75 in.).
====

[[v2-28-17]]

^<<v2-28-17,17>>^ And you must fill it with a filling of stones, there being four rows of stones. A row of ruby, topaz and emerald is the first row.

[[v2-28-18]]

^<<v2-28-18,18>>^ And the second row is turquoise, sapphire and jasper.

[[v2-28-19]]

^<<v2-28-19,19>>^ And the third row is leshʹem stone,^&#42;1^ agate^&#42;2^ and amethyst.

[NOTE]
====
. “Leshem stone.” Heb., leʹshem, an unidentified precious stone; LXXVg, “ligure.”
. “Agate,” LXXVg; Heb., shevohʹ, a kind of precious stone.
====

[[v2-28-20]]

^<<v2-28-20,20>>^ And the fourth row is chrysʹo·lite^&#42;1^ and onyx and jade. Sockets of gold should be in their fillings.

[NOTE]
====
. “Chrysolite,” LXXVg; Heb., tar·shishʹ.
====

[[v2-28-21]]

^<<v2-28-21,21>>^ And the stones should be according to the names of the sons of Israel, the twelve according to their names. With the engravings of a seal they should be, each one according to its name, for the twelve tribes.

[[v2-28-22]]

^<<v2-28-22,22>>^ “And you must make upon the breastpiece wreathed chains, in ropework, of pure gold.

[[v2-28-23]]

^<<v2-28-23,23>>^ And you must make upon the breastpiece two rings of gold, and you must put the two rings upon the two extremities of the breastpiece.

[[v2-28-24]]

^<<v2-28-24,24>>^ And you must put the two ropes of gold through the two rings at the extremities of the breastpiece.

[[v2-28-25]]

^<<v2-28-25,25>>^ And you will put the two ends of the two ropes through the two settings, and you must put them upon the shoulder pieces of the ephʹod, at the forefront of it.

[[v2-28-26]]

^<<v2-28-26,26>>^ And you must make two rings of gold and set them at the two extremities of the breastpiece upon its edge that is on the side toward the ephʹod inward.

[[v2-28-27]]

^<<v2-28-27,27>>^ And you must make two rings of gold and put them upon the two shoulder pieces of the ephʹod from below, on its forefront, near its place of joining, above the girdle of the ephʹod.

[[v2-28-28]]

^<<v2-28-28,28>>^ And they will bind the breastpiece by its rings to the rings of the ephʹod with a blue string, that it may continue above the girdle of the ephʹod and the breastpiece may not get displaced from on top the ephʹod.

[[v2-28-29]]

^<<v2-28-29,29>>^ “And Aaron must carry the names of the sons of Israel on the breastpiece of judgment over his heart when he comes into the Holy as a memorial before Jehovah constantly.

[[v2-28-30]]

^<<v2-28-30,30>>^ And you must put the Uʹrim and the Thumʹmim^&#42;1^ into the breastpiece of judgment, and they must prove to be over Aaron’s heart when he comes in before Jehovah; and Aaron must carry the judgments^&#42;2^ of the sons of Israel over his heart before Jehovah constantly.

[NOTE]
====
. “The Urim and the Thummim.” Heb., ha·ʼu·rimʹ weʼeth-hat·tum·mimʹ; LXX, “the explanation (manifestation) and the truth”; Sy, “the light and the perfection”; Vg, “the doctrine and the truth.” However, LXXSyVg are understood to be conjecturing at the meaning of the Heb. expression. The Urim and the Thummim were used in delivering sacred pronouncements.
. “Judgments,” LXXSy; MVg, “judgment.”
====

[[v2-28-31]]

^<<v2-28-31,31>>^ “And you must make the sleeveless coat of the ephʹod completely of blue thread.

[[v2-28-32]]

^<<v2-28-32,32>>^ And there must be an opening at its top^&#42;1^ in the middle of it. Its opening should have a border round about, the product of a loom worker. Like the opening of a coat of mail it should be for it, that it may not be torn.

[NOTE]
====
. Or, “opening for his head.”
====

[[v2-28-33]]

^<<v2-28-33,33>>^ And you must make upon the hem of it pomegranates of blue thread and wool dyed reddish purple and coccus scarlet material, upon its hem round about, and bells of gold in between them round about;

[[v2-28-34]]

^<<v2-28-34,34>>^ a bell of gold and a pomegranate, a bell of gold and a pomegranate upon the hem^&#42;1^ of the sleeveless coat round about.

[NOTE]
====
. Or, “skirt.”
====

[[v2-28-35]]

^<<v2-28-35,35>>^ And it must be upon Aaron that he may minister, and the sound from him must be heard when he goes into the sanctuary^&#42;1^ before Jehovah and when he comes out, that he may not die.

[NOTE]
====
. Or, “the Holy.” Heb., haq·Qoʹdhesh.
====

[[v2-28-36]]

^<<v2-28-36,36>>^ “And you must make a shining plate of pure gold and engrave upon it with the engravings of a seal, ‘Holiness belongs to Jehovah.’

[[v2-28-37]]

^<<v2-28-37,37>>^ And you must fasten it with a blue string, and it must come to be upon the turban. On the forefront of the turban it should come to be.

[[v2-28-38]]

^<<v2-28-38,38>>^ And it must come to be upon Aaron’s forehead, and Aaron must answer for the error committed against the holy objects, which the sons of Israel will sanctify, that is to say, all their holy gifts; and it must stay upon his forehead constantly, to gain approval for them before Jehovah.

[[v2-28-39]]

^<<v2-28-39,39>>^ “And you must weave in checkerwork the robe of fine linen and make a turban of fine linen, and you will make a sash, the work of a weaver.

[[v2-28-40]]

^<<v2-28-40,40>>^ “And for Aaron’s sons you will make robes, and you must make sashes for them, and you will make headgears for them for glory and beauty.

[[v2-28-41]]

^<<v2-28-41,41>>^ And with them you must clothe Aaron your brother and his sons with him, and you must anoint them and fill their hand with power^&#42;1^ and sanctify them, and they must act as priests to me.

[NOTE]
====
. Or, “and empower them.” Lit., “and fill their hand.”
====

[[v2-28-42]]

^<<v2-28-42,42>>^ And make drawers of linen for them to cover the naked flesh. From the hips and to the thighs they are to extend.

[[v2-28-43]]

^<<v2-28-43,43>>^ And they must be upon Aaron and his sons when they come into the tent of meeting or when they go near to the altar to minister in the holy place, that they may not incur error and certainly die. It is a statute to time indefinite for him and his offspring after him.

'''

xref:002-exodus/002-exodus-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodus/002-exodus-029.adoc#v2-29-0[Próximo Capítulo &#62;]