include::./index.adoc[]

[[v2-15-0]]
=== Exodus, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-15-1]]

^<<v2-15-1,1>>^ At that time Moses and the sons of Israel proceeded to sing this song to Jehovah and to say the following:
“Let me sing to Jehovah, for he has become highly exalted.
The horse and its rider he has pitched into the sea.

[[v2-15-2]]

^<<v2-15-2,2>>^ My strength and &#91;my&#93; might^&#42;1^ is Jah,^&#42;2^ since he serves for my salvation.
This is my God, and I shall laud him; my father’s God, and I shall raise him on high.

[NOTE]
====
. “And [my] might.” Possibly, “and [my] melody.” Heb., wezim·rathʹ; Sam and three Heb. mss add “my”; Lat., laus meʹa, “my praise.”
. “Jah.” Heb., Yah; the first occurrence of this abbreviation for the name “Jehovah.” See App 1A.
====

[[v2-15-3]]

^<<v2-15-3,3>>^ Jehovah is a manly person of war. Jehovah is his name.

[[v2-15-4]]

^<<v2-15-4,4>>^ Pharʹaoh’s chariots and his military forces he has cast into the sea,
And the choice of his warriors have been sunk in the Red Sea.

[[v2-15-5]]

^<<v2-15-5,5>>^ The surging waters^&#42;1^ proceeded to cover them; down they went into the depths like a stone.

[NOTE]
====
. “The surging waters.” Heb., teho·mothʹ; Lat., a·bysʹsi. See Ge 1:2 ftn, “Deep.”
====

[[v2-15-6]]

^<<v2-15-6,6>>^ Your right hand, O Jehovah, is proving itself powerful in ability,
Your right hand, O Jehovah, can shatter an enemy.

[[v2-15-7]]

^<<v2-15-7,7>>^ And in the abundance of your superiority you can throw down those who rise up against you;
You send out your burning anger, it eats them up like stubble.

[[v2-15-8]]

^<<v2-15-8,8>>^ And by a breath^&#42;1^ from your nostrils^&#42;2^ waters were heaped up;
They stood still like a dam of floods;
The surging waters were congealed in the heart of the sea.

[NOTE]
====
. “And by a breath.” Heb., u·veruʹach; Gr., pneuʹma·tos. See Ge 1:2 ftn, “Force.”
. Or, “anger.”
====

[[v2-15-9]]

^<<v2-15-9,9>>^ The enemy said, ‘I shall pursue! I shall overtake!
I shall divide spoil! My soul will be filled with them!
I shall draw my sword! My hand will drive them away!’^&#42;1^

[NOTE]
====
. Or, “dispossess them.”
====

[[v2-15-10]]

^<<v2-15-10,10>>^ You blew with your breath, the sea covered them;
They sank like lead in majestic waters.

[[v2-15-11]]

^<<v2-15-11,11>>^ Who among the gods^&#42;1^ is like you, O Jehovah?
Who is like you, proving yourself mighty in holiness?
The One to be feared with songs of praise, the One doing marvels.

[NOTE]
====
. “Among the gods.” Heb., ba·ʼe·limʹ, pl. of ʼel.
====

[[v2-15-12]]

^<<v2-15-12,12>>^ You stretched out your right hand, the earth proceeded to swallow them up.

[[v2-15-13]]

^<<v2-15-13,13>>^ You in your loving-kindness^&#42;1^ have led the people whom you have recovered;^&#42;2^
You in your strength will certainly conduct them to your holy abiding place.

[NOTE]
====
. Or, “your loyal love.”
. Or, “reclaimed; redeemed.”
====

[[v2-15-14]]

^<<v2-15-14,14>>^ Peoples must^&#42;1^ hear, they will be agitated;
Birth pangs must take hold on the inhabitants of Phi·lisʹti·a.

[NOTE]
====
. Or, “will certainly.”
====

[[v2-15-15]]

^<<v2-15-15,15>>^ At that time the sheiks of Eʹdom will indeed be disturbed;
As for the despots of Moʹab, trembling will take hold on them.
All the inhabitants of Caʹnaan will indeed be disheartened.

[[v2-15-16]]

^<<v2-15-16,16>>^ Fright and dread will fall upon them.
Because of the greatness of your arm they will be motionless like a stone,
Until your people pass by, O Jehovah,
Until the people whom you have produced^&#42;1^ pass by.

[NOTE]
====
. Or, “acquired.”
====

[[v2-15-17]]

^<<v2-15-17,17>>^ You will bring them and plant them in the mountain of your inheritance,^&#42;1^
An established place^&#42;2^ that you have made ready for you to inhabit, O Jehovah,
A sanctuary, O Jehovah,^&#42;3^ that your hands have established.

[NOTE]
====
. Or, “possession.”
. Or, “a site.”
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v2-15-18]]

^<<v2-15-18,18>>^ Jehovah will rule as king to time indefinite, even forever.

[[v2-15-19]]

^<<v2-15-19,19>>^ When Pharʹaoh’s horses with his war chariots and his cavalrymen went into the sea,
Then Jehovah brought back the waters of the sea upon them,
While the sons of Israel walked on dry land through the midst of the sea.”

[[v2-15-20]]

^<<v2-15-20,20>>^ And Mirʹi·am the prophetess, Aaron’s sister, proceeded to take a tambourine in her hand; and all the women began going out with her with tambourines and in dances.^&#42;1^

[NOTE]
====
. Or, “round dances.”
====

[[v2-15-21]]

^<<v2-15-21,21>>^ And Mirʹi·am kept responding to the men:^&#42;1^
“Sing^&#42;2^ to Jehovah, for he has become highly exalted.
The horse and its rider he has pitched into the sea.”

[NOTE]
====
. “The men.” Lit., “them,” masc.
. “Sing,” M; LXXVg, “Let us sing.”
====

[[v2-15-22]]

^<<v2-15-22,22>>^ Later Moses caused Israel to depart from the Red Sea and they went out to the wilderness of Shur and marched on for three days in the wilderness, but they did not find water.

[[v2-15-23]]

^<<v2-15-23,23>>^ In time they came to Maʹrah, but they were not able to drink the water from Maʹrah because it was bitter. That is why he called its name Maʹrah.^&#42;1^

[NOTE]
====
. Meaning “Bitterness.”
====

[[v2-15-24]]

^<<v2-15-24,24>>^ And the people began to murmur against Moses, saying: “What are we to drink?”

[[v2-15-25]]

^<<v2-15-25,25>>^ Then he cried out to Jehovah. So Jehovah directed him to a tree, and he threw it into the water and the water became sweet.
There He established for them^&#42;1^ a regulation and a case for judgment and there he put them to the test.

[NOTE]
====
. “Them,” referring to the “people.” Lit., “him,” or, “it.”
====

[[v2-15-26]]

^<<v2-15-26,26>>^ And he went on to say: “If you will strictly listen to the voice of Jehovah your God and will do what is right in his eyes and will indeed give ear to his commandments and keep all his regulations, I shall put none of the maladies upon you that I put upon the Egyptians; because I am Jehovah who is healing you.”

[[v2-15-27]]

^<<v2-15-27,27>>^ After that they came to Eʹlim, where there were twelve springs of water and seventy palm trees. So they went camping there by the water.

'''

xref:002-exodus/002-exodus-014.adoc#v2-14-0[&#60; Capítulo Anterior] | <<v2-15-0,Topo>> | xref:002-exodus/002-exodus-016.adoc#v2-16-0[Próximo Capítulo &#62;]