include::./index.adoc[]

[[v2-4-0]]
=== Exodus, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-4-1]]

^<<v2-4-1,1>>^ However, Moses in answering said: “But suppose they do not believe me and do not listen to my voice, because they are going to say, ‘Jehovah did not appear to you.’”

[[v2-4-2]]

^<<v2-4-2,2>>^ Then Jehovah said to him: “What is that in your hand?” to which he said: “A rod.”

[[v2-4-3]]

^<<v2-4-3,3>>^ Next he said: “Throw it on the earth.” So he threw it on the earth, and it became a serpent; and Moses began to flee from it.

[[v2-4-4]]

^<<v2-4-4,4>>^ Jehovah now said to Moses: “Thrust your hand out and grab hold of it by the tail.” So he thrust his hand out and grabbed hold of it, and it became a rod in his palm.

[[v2-4-5]]

^<<v2-4-5,5>>^ “In order that,” to quote him, “they may believe that Jehovah the God of their forefathers, the God of Abraham, the God of Isaac and the God of Jacob, has appeared to you.”

[[v2-4-6]]

^<<v2-4-6,6>>^ Then Jehovah said to him once more: “Stick your hand, please, into the upper fold of your garment.” So he stuck his hand into the upper fold of his garment. When he drew it out, why, here his hand was stricken with leprosy like snow!

[[v2-4-7]]

^<<v2-4-7,7>>^ After that he said: “Return your hand into the upper fold of your garment.” So he returned his hand into the upper fold of his garment. When he drew it out of the upper fold of his garment, why, here it was restored like the rest of his flesh!

[[v2-4-8]]

^<<v2-4-8,8>>^ “And it must occur that,” to quote him, “if they will not believe you and will not listen to the voice of the first sign, then they will certainly believe the voice of the later sign.

[[v2-4-9]]

^<<v2-4-9,9>>^ Still, it must occur that, if they will not believe even these two signs and will not listen to your voice, then you will have to take some water from the Nile River and pour it out on the dry land; and the water that you will take from the Nile River will certainly become, yes, it will indeed become blood on the dry land.”

[[v2-4-10]]

^<<v2-4-10,10>>^ Moses now said to Jehovah: “Excuse me, Jehovah,^&#42;1^ but I am not a fluent speaker, neither since yesterday nor since before that nor since your speaking to your servant, for I am slow of mouth and slow of tongue.”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v2-4-11]]

^<<v2-4-11,11>>^ At that Jehovah said to him: “Who appointed a mouth for man or who appoints the speechless or the deaf or the clear-sighted or the blind? Is it not I, Jehovah?

[[v2-4-12]]

^<<v2-4-12,12>>^ So now go, and I myself shall prove to be with your mouth and I will teach you what you ought to say.”

[[v2-4-13]]

^<<v2-4-13,13>>^ But he said: “Excuse me, Jehovah,^&#42;1^ but send, please, by the hand of the one whom you are going to send.”

[NOTE]
====
. See vs 10 ftn.
====

[[v2-4-14]]

^<<v2-4-14,14>>^ Then Jehovah’s anger grew hot against Moses and he said: “Is not Aaron the Levite your brother? I do know that he can really speak. And, besides, here he is on his way out to meet you. When he does see you, he will certainly rejoice in his heart.

[[v2-4-15]]

^<<v2-4-15,15>>^ And you must speak to him and put the words in his mouth; and I myself shall prove to be with your mouth and his mouth, and I will teach YOU men what YOU are to do.

[[v2-4-16]]

^<<v2-4-16,16>>^ And he must speak for you to the people; and it must occur that he will serve as a mouth to you, and you will serve as God^&#42;1^ to him.

[NOTE]
====
. “As God.” Heb., leʼ·lo·himʹ, pl.; Gr., the·onʹ; Lat., Deʹum.
====

[[v2-4-17]]

^<<v2-4-17,17>>^ And this rod you will take in your hand that you may perform the signs with it.”

[[v2-4-18]]

^<<v2-4-18,18>>^ Accordingly Moses went and returned to Jethʹro^&#42;1^ his father-in-law and said to him: “I want to go, please, and return to my brothers who are in Egypt that I may see whether they are still alive.” So Jethʹro said to Moses: “Go in peace.”

[NOTE]
====
. Heb., Yeʹther.
====

[[v2-4-19]]

^<<v2-4-19,19>>^ After that Jehovah said to Moses in Midʹi·an: “Go, return to Egypt, because all the men who were hunting for your soul^&#42;1^ are dead.”

[NOTE]
====
. “Your soul (life).” Heb., naph·sheʹkha; Gr., psy·khenʹ.
====

[[v2-4-20]]

^<<v2-4-20,20>>^ Then Moses took his wife and his sons and made them ride on an ass, and he proceeded to return to the land of Egypt. Moreover, Moses took the rod of the &#91;true&#93; God in his hand.

[[v2-4-21]]

^<<v2-4-21,21>>^ And Jehovah went on to say to Moses: “After you have gone and returned to Egypt see that YOU men actually perform all the miracles that I have put in your hand before Pharʹaoh. As for me, I shall let his heart become obstinate;^&#42;1^ and he will not send the people away.

[NOTE]
====
. Or, “hard.”
====

[[v2-4-22]]

^<<v2-4-22,22>>^ And you must say to Pharʹaoh, ‘This is what Jehovah has said: “Israel is my son, my firstborn.

[[v2-4-23]]

^<<v2-4-23,23>>^ And I say to you: Send my son away that he may serve me.^&#42;1^ But should you refuse to send him away, here I am killing your son, your firstborn.”’”

[NOTE]
====
. “That he may serve (worship) me.” Heb., weya·ʽav·dheʹni; Gr., la·treuʹsei. See 3:12 ftn.
====

[[v2-4-24]]

^<<v2-4-24,24>>^ Now it came about on the road at the lodging place that Jehovah^&#42;1^ got to meet him and kept looking for a way to put him to death.

[NOTE]
====
. “Jehovah,” MSam; TLXX, “Jehovah’s angel.”
====

[[v2-4-25]]

^<<v2-4-25,25>>^ Finally Zip·poʹrah took a flint and cut off her son’s foreskin and caused it to touch his feet and said: “It is because you are a bridegroom of blood^&#42;1^ to me.”^&#42;2^

[NOTE]
====
. Lit., “bloods.”
. “And said: ‘The blood of my young child’s circumcision has stood (is staunched),’ ” LXX.
====

[[v2-4-26]]

^<<v2-4-26,26>>^ Consequently he let go of him. At that time she said: “A bridegroom of blood,” because of the circumcision.^&#42;1^

[NOTE]
====
. Lit., “circumcisions.”
====

[[v2-4-27]]

^<<v2-4-27,27>>^ Then Jehovah said to Aaron: “Go to meet Moses into the wilderness.” With that he went and met him in the mountain of the &#91;true&#93; God and kissed him.

[[v2-4-28]]

^<<v2-4-28,28>>^ And Moses proceeded to tell Aaron all the words of Jehovah, who had sent him, and all the signs that he had commanded him to do.^&#42;1^

[NOTE]
====
. “Commanded him to do,” Sy; MLXXVg, “commanded (him).”
====

[[v2-4-29]]

^<<v2-4-29,29>>^ After that Moses and Aaron went and gathered all the older men of the sons of Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Then Aaron spoke all the words that Jehovah had spoken to Moses, and he performed the signs under the eyes of the people.

[[v2-4-31]]

^<<v2-4-31,31>>^ At this the people believed. When they heard that Jehovah had turned his attention to the sons of Israel and that he had seen their affliction, then they bowed down and prostrated themselves.

'''

xref:002-exodus/002-exodus-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodus/002-exodus-005.adoc#v2-5-0[Próximo Capítulo &#62;]