include::./index.adoc[]

[[v2-33-0]]
=== Exodus, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-33-1]]

^<<v2-33-1,1>>^ And Jehovah said further to Moses: “Go, move up from here, you and the people whom you led up out of the land of Egypt, to the land about which I swore^&#42;1^ to Abraham, Isaac and Jacob, saying, ‘To your seed I shall give it.’

[NOTE]
====
. Or, “land that I promised on oath.”
====

[[v2-33-2]]

^<<v2-33-2,2>>^ And I will send an angel ahead of you and drive out the Caʹnaan·ites, the Amʹor·ites, and the Hitʹtites and the Perʹiz·zites, the Hiʹvites and the Jebʹu·sites;

[[v2-33-3]]

^<<v2-33-3,3>>^ to a land^&#42;1^ flowing with milk and honey, for I shall not go up in the midst of you, because you are a stiff-necked people, that I may not exterminate you on the way.”

[NOTE]
====
. “To a land,” M; LXX, “and I shall lead you into a land.”
====

[[v2-33-4]]

^<<v2-33-4,4>>^ When the people got to hear this evil word, they began to mourn; and none of them put his ornaments on himself.

[[v2-33-5]]

^<<v2-33-5,5>>^ And Jehovah went on to say to Moses: “Say to the sons of Israel, ‘YOU are a stiff-necked people. In one moment I could go up into the midst of you and certainly exterminate you. So now put down your ornaments off yourself, as I want to know what I am going to do to you.’”

[[v2-33-6]]

^<<v2-33-6,6>>^ And the sons of Israel went stripping their ornaments off themselves from Mount Hoʹreb onward.

[[v2-33-7]]

^<<v2-33-7,7>>^ As for Moses, he proceeded to take his^&#42;1^ tent away and he pitched it outside the camp, far away from the camp; and he called it a tent of meeting. And it occurred that everyone inquiring of Jehovah would go out to the tent of meeting, which was outside the camp.

[NOTE]
====
. “His,” LXXSy; MVg, “the.”
====

[[v2-33-8]]

^<<v2-33-8,8>>^ And it occurred that as soon as Moses went out to the tent, all the people would rise, and they stationed themselves each one at the entrance of his own tent, and they gazed after Moses until he went into the tent.

[[v2-33-9]]

^<<v2-33-9,9>>^ It also occurred that as soon as Moses had gone into the tent, the pillar of cloud would come down, and it stood at the entrance of the tent and he spoke with Moses.

[[v2-33-10]]

^<<v2-33-10,10>>^ And all the people saw the pillar of cloud standing at the entrance of the tent, and all the people rose and bowed down each one at the entrance of his own tent.

[[v2-33-11]]

^<<v2-33-11,11>>^ And Jehovah spoke to Moses face to face, just as a man would speak to his fellow. When he returned to the camp, his minister Joshua, the son of Nun, as attendant,^&#42;1^ would not withdraw from the midst of the tent.

[NOTE]
====
. Or, “a young man.”
====

[[v2-33-12]]

^<<v2-33-12,12>>^ Now Moses said to Jehovah: “See, you are saying to me, ‘Lead this people up,’ but you yourself have not let me know whom you will send with me. Moreover, you yourself have said, ‘I do know you by name and, besides, you have found favor in my eyes.’

[[v2-33-13]]

^<<v2-33-13,13>>^ And now, if, please, I have found favor in your eyes, make me know, please, your ways, that I may know you, in order that I may find favor in your eyes. And consider^&#42;1^ that this nation is your people.”

[NOTE]
====
. “And consider,” MSy; LXX, “And that I may know.”
====

[[v2-33-14]]

^<<v2-33-14,14>>^ So he said: “My own person^&#42;1^ will go along^&#42;2^ and I shall certainly give you rest.”^&#42;3^

[NOTE]
====
. Lit., “My face,” M(Heb., pa·naiʹ)​Vg.
. “I myself shall go before you,” LXX; Sy, “Walk before me.”
. Some read the compound sentence as a question: “Will my own person go along and shall I certainly give you rest?”
====

[[v2-33-15]]

^<<v2-33-15,15>>^ At this he said to him: “If your own person^&#42;1^ is not going along, do not lead us up from here.

[NOTE]
====
. Lit., “your face,” M; LXXVg, “you yourself.”
====

[[v2-33-16]]

^<<v2-33-16,16>>^ And by what, now, will it be known that I have found favor in your eyes, I and your people? Is it not by your going along with us, in that I and your people have been made distinct from all the other people who are upon the surface of the ground?”

[[v2-33-17]]

^<<v2-33-17,17>>^ And Jehovah went on to say to Moses: “This thing, too, of which you have spoken, I shall do, because you have found favor in my eyes and I know you by name.”

[[v2-33-18]]

^<<v2-33-18,18>>^ At this he said: “Cause me to see, please, your glory.”

[[v2-33-19]]

^<<v2-33-19,19>>^ But he said: “I myself shall cause all my goodness to pass before your face, and I will declare^&#42;1^ the name of Jehovah before you; and I will favor the one^&#42;2^ whom I may favor, and I will show mercy to the one to whom I may show mercy.”

[NOTE]
====
. Or, “preach.” Lit., “call upon.”
. “One,” LXXVg. Or, “ones.”
====

[[v2-33-20]]

^<<v2-33-20,20>>^ And he added: “You are not able to see my face, because no man^&#42;1^ may see me and yet live.”

[NOTE]
====
. Or, “earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v2-33-21]]

^<<v2-33-21,21>>^ And Jehovah said further: “Here is a place with me, and you must station yourself upon the rock.

[[v2-33-22]]

^<<v2-33-22,22>>^ And it has to occur that while my glory is passing by I must place you in a hole in the rock, and I must put my palm over you as a screen until I have passed by.

[[v2-33-23]]

^<<v2-33-23,23>>^ After that I must take my palm away, and you will indeed see my back.^&#42;1^ But my face may not be seen.”

[NOTE]
====
. Or, “rear parts.”
====

'''

xref:002-exodus/002-exodus-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodus/002-exodus-034.adoc#v2-34-0[Próximo Capítulo &#62;]