include::./index.adoc[]

[[v2-7-0]]
=== Exodus, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-7-1]]

^<<v2-7-1,1>>^ Consequently Jehovah said to Moses: “See, I have made you God^&#42;1^ to Pharʹaoh, and Aaron your own brother will become your prophet.

[NOTE]
====
. “God.” Heb., ʼelo·himʹ; Gr., the·onʹ; Lat., Deʹum.
====

[[v2-7-2]]

^<<v2-7-2,2>>^ You—you will speak all that I shall command you; and Aaron your brother will do the speaking to Pharʹaoh, and he must send the sons of Israel away from his land.

[[v2-7-3]]

^<<v2-7-3,3>>^ As for me, I shall let Pharʹaoh’s heart become obstinate,^&#42;1^ and I shall certainly multiply my signs and my miracles in the land of Egypt.

[NOTE]
====
. Or, “I shall make Pharaoh’s heart obstinate (hard).”
====

[[v2-7-4]]

^<<v2-7-4,4>>^ And Pharʹaoh will not listen to YOU men; and I shall have to lay my hand upon Egypt and bring my armies, my people, the sons of Israel, out from the land of Egypt with great judgments.

[[v2-7-5]]

^<<v2-7-5,5>>^ And the Egyptians will certainly know that I am Jehovah when I stretch out my hand against Egypt, and I shall indeed bring the sons of Israel out from their midst.”

[[v2-7-6]]

^<<v2-7-6,6>>^ And Moses and Aaron went ahead doing as Jehovah had commanded them. They did just so.

[[v2-7-7]]

^<<v2-7-7,7>>^ And Moses was eighty years old and Aaron was eighty-three years old at the time of their speaking to Pharʹaoh.

[[v2-7-8]]

^<<v2-7-8,8>>^ Jehovah now said to Moses and Aaron:

[[v2-7-9]]

^<<v2-7-9,9>>^ “In case that Pharʹaoh speaks to YOU, saying, ‘Produce a miracle for yourselves,’ then you must say to Aaron, ‘Take your rod and throw it down before Pharʹaoh.’ It will become^&#42;1^ a big snake.”

[NOTE]
====
. “And it will become,” SamLXXSyVg.
====

[[v2-7-10]]

^<<v2-7-10,10>>^ So Moses and Aaron went on in to Pharʹaoh and did exactly as Jehovah had commanded. Accordingly Aaron threw his rod down before Pharʹaoh and his servants and it became a big snake.

[[v2-7-11]]

^<<v2-7-11,11>>^ However, Pharʹaoh also called for the wise men and the sorcerers; and the magic-practicing priests of Egypt themselves also proceeded to do the same thing with their magic arts.

[[v2-7-12]]

^<<v2-7-12,12>>^ So they threw down each one his rod, and they became big snakes; but Aaron’s rod swallowed up their rods.

[[v2-7-13]]

^<<v2-7-13,13>>^ Still, Pharʹaoh’s heart became obstinate, and he did not listen to them, just as Jehovah had spoken.

[[v2-7-14]]

^<<v2-7-14,14>>^ Then Jehovah said to Moses: “Pharʹaoh’s heart is unresponsive.^&#42;1^ He has refused to send the people away.

[NOTE]
====
. Lit., “heavy.”
====

[[v2-7-15]]

^<<v2-7-15,15>>^ Go to Pharʹaoh in the morning. Look! He is going out to the water! And you must put yourself in position to meet him by the edge of the Nile River, and the rod that turned into a serpent you are to take in your hand.

[[v2-7-16]]

^<<v2-7-16,16>>^ And you must say to him, ‘Jehovah the God of the Hebrews has sent me to you, saying: “Send my people away that they may serve^&#42;1^ me in the wilderness,” but here you have not obeyed until now.

[NOTE]
====
. See 3:12 ftn.
====

[[v2-7-17]]

^<<v2-7-17,17>>^ This is what Jehovah has said: “By this you will know that I am Jehovah. Here I am striking with the rod that is in my hand upon the water that is in the Nile River, and it will certainly turn into blood.

[[v2-7-18]]

^<<v2-7-18,18>>^ And the fish that are in the Nile River will die, and the Nile River will actually stink, and the Egyptians will simply have no stomach for drinking water from the Nile River.”’”

[[v2-7-19]]

^<<v2-7-19,19>>^ Subsequently Jehovah said to Moses: “Say to Aaron, ‘Take your rod and stretch your hand out over the waters of Egypt, over their rivers, over their Nile canals and over their reedy pools and over all their impounded waters,^&#42;1^ that they may become blood.’ And there will certainly be blood in all the land of Egypt and in the wooden vessels and in the stone vessels.”

[NOTE]
====
. Lit., “all the collected mass of their waters.”
====

[[v2-7-20]]

^<<v2-7-20,20>>^ Immediately Moses and Aaron did so, just as Jehovah had commanded, and he lifted up the rod and struck the water that was in the Nile River under the eyes of Pharʹaoh and his servants, and all the water that was in the Nile River was turned into blood.

[[v2-7-21]]

^<<v2-7-21,21>>^ And the fish that were in the Nile River died, and the Nile River began to stink; and the Egyptians were unable to drink water from the Nile River; and the blood came to be in all the land of Egypt.

[[v2-7-22]]

^<<v2-7-22,22>>^ Nevertheless, the magic-practicing priests of Egypt proceeded to do the same thing with their secret arts; so that Pharʹaoh’s heart continued to be obstinate, and he did not listen to them, just as Jehovah had spoken.

[[v2-7-23]]

^<<v2-7-23,23>>^ Hence Pharʹaoh turned and went into his house, and he did not set his heart to have any regard for this either.

[[v2-7-24]]

^<<v2-7-24,24>>^ And all the Egyptians went digging round about the Nile River for water to drink, because they were unable to drink any water of the Nile River.

[[v2-7-25]]

^<<v2-7-25,25>>^ And seven days came to be fulfilled after Jehovah’s striking the Nile River.

'''

xref:002-exodus/002-exodus-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodus/002-exodus-008.adoc#v2-8-0[Próximo Capítulo &#62;]