include::./index.adoc[]

[[v2-30-0]]
=== Exodus, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-30-1]]

^<<v2-30-1,1>>^ “And you must make an altar as a place for burning incense; out of acacia wood you will make it.

[[v2-30-2]]

^<<v2-30-2,2>>^ A cubit in length and a cubit in width, it should be foursquare, and its height two cubits. Its horns extend out of it.

[[v2-30-3]]

^<<v2-30-3,3>>^ And you must overlay it with pure gold, its top surface and its sides^&#42;1^ round about and its horns; and you must make a border of gold round about for it.

[NOTE]
====
. Lit., “walls.”
====

[[v2-30-4]]

^<<v2-30-4,4>>^ You will also make for it two rings of gold. Down below its border upon two of its sides you will make them, upon two opposite sides of it, as they must serve as supports for the poles with which to carry it.

[[v2-30-5]]

^<<v2-30-5,5>>^ And you must make the poles of acacia wood and overlay them with gold.

[[v2-30-6]]

^<<v2-30-6,6>>^ And you must put it before the curtain that is near the ark of the testimony, before the cover that is over the Testimony, where I shall present myself to you.

[[v2-30-7]]

^<<v2-30-7,7>>^ “And Aaron must make perfumed incense smoke upon it. Morning by morning, when he dresses the lamps, he will make it smoke.

[[v2-30-8]]

^<<v2-30-8,8>>^ And when Aaron lights up the lamps between the two evenings, he will make it smoke. It is an incense constantly before Jehovah during YOUR generations.

[[v2-30-9]]

^<<v2-30-9,9>>^ YOU must not offer upon it illegitimate^&#42;1^ incense or a burnt offering or a grain offering;^&#42;2^ and YOU must not pour a drink offering upon it.

[NOTE]
====
. Lit., “strange.”
. Lit., “a gift.”
====

[[v2-30-10]]

^<<v2-30-10,10>>^ And Aaron must make atonement upon its horns once a year. With some of the blood of the sin offering of the atonement he will make atonement for it once a year during YOUR generations. It is most holy to Jehovah.”

[[v2-30-11]]

^<<v2-30-11,11>>^ And Jehovah went on to speak to Moses, saying:

[[v2-30-12]]

^<<v2-30-12,12>>^ “Whenever you take the sum of the sons of Israel as a census of them,^&#42;1^ then they must each give a ransom^&#42;2^ for his soul^&#42;3^ to Jehovah when^&#42;4^ taking a census of them, that there may come to be no plague upon them when taking a census of them.

[NOTE]
====
. Or, “by their registered ones.”
. Or, “reparation.” Lit., “covering.” Gr., lyʹtra, pl.
. “His soul (life).” Heb., naph·shohʹ; Gr., psy·khesʹ.
. Or, “because of.”
====

[[v2-30-13]]

^<<v2-30-13,13>>^ This is what all those will give who pass over to those numbered: a half shekel by the shekel^&#42;1^ of the holy place.^&#42;2^ Twenty geʹrahs^&#42;3^ equal a shekel. A half shekel is the contribution to Jehovah.

[NOTE]
====
. “Shekel,” MSy; LXX, “didrachma.” See App 8A.
. Or, “by the holy shekel.” A standard weight kept at the tabernacle, or possibly to emphasize that the weight should be precise. Compare 2Sa 14:26 ftn, “Weight.”
. See App 8A.
====

[[v2-30-14]]

^<<v2-30-14,14>>^ Everyone passing over to those registered from twenty years old and upward will give Jehovah’s contribution.

[[v2-30-15]]

^<<v2-30-15,15>>^ The rich should not give more, and the lowly must not give less than the half shekel, in order to give Jehovah’s contribution so as to make atonement for YOUR souls.

[[v2-30-16]]

^<<v2-30-16,16>>^ And you must take the silver money of the atonement from the sons of Israel and give it in behalf of the service of the tent of meeting, that it may indeed serve as a memorial before Jehovah for the sons of Israel, to make atonement for YOUR souls.”

[[v2-30-17]]

^<<v2-30-17,17>>^ And Jehovah spoke further to Moses, saying:

[[v2-30-18]]

^<<v2-30-18,18>>^ “You must make a basin^&#42;1^ of copper and its stand of copper for washing, and you must put it between the tent of meeting and the altar and put water into it.

[NOTE]
====
. Or, “laver.”
====

[[v2-30-19]]

^<<v2-30-19,19>>^ And Aaron and his sons must wash their hands and their feet at it.

[[v2-30-20]]

^<<v2-30-20,20>>^ When they go into the tent of meeting they will wash with water that they may not die, or when they go near the altar to minister in order to make an offering made by fire smoke to Jehovah.

[[v2-30-21]]

^<<v2-30-21,21>>^ And they must wash their hands and their feet that they may not die, and it must serve as a regulation to time indefinite for them, for him and his offspring throughout their generations.”

[[v2-30-22]]

^<<v2-30-22,22>>^ And Jehovah continued to speak to Moses, saying:

[[v2-30-23]]

^<<v2-30-23,23>>^ “As for you, take to yourself the choicest perfumes: myrrh in congealed drops^&#42;1^ five hundred units, and sweet cinnamon in half that amount, two hundred and fifty units, and sweet calamus two hundred and fifty units,

[NOTE]
====
. Or, “myrrh of pearls,” that is, white drops of myrrh having congealed and turned dark red or black.
====

[[v2-30-24]]

^<<v2-30-24,24>>^ and cassia five hundred units by the shekel of the holy place, and olive oil a hin.

[[v2-30-25]]

^<<v2-30-25,25>>^ Then you must make out of it a holy anointing oil, an ointment, a mixture that is the work of an ointment maker. It is to be a holy anointing oil.

[[v2-30-26]]

^<<v2-30-26,26>>^ “And you must anoint with it the tent of meeting and the ark of the testimony,

[[v2-30-27]]

^<<v2-30-27,27>>^ and the table and all its utensils and the lampstand and its utensils and the altar of incense,

[[v2-30-28]]

^<<v2-30-28,28>>^ and the altar of burnt offering and all its utensils and the basin and its stand.

[[v2-30-29]]

^<<v2-30-29,29>>^ And you must sanctify them that they may indeed become most holy. Anyone^&#42;1^ touching them is to be holy.

[NOTE]
====
. Or, “Anything.”
====

[[v2-30-30]]

^<<v2-30-30,30>>^ And you will anoint Aaron and his sons, and you must sanctify them for acting as priests to me.

[[v2-30-31]]

^<<v2-30-31,31>>^ “And you will speak to the sons of Israel, saying, ‘This is to continue as a holy anointing oil to me during YOUR generations.

[[v2-30-32]]

^<<v2-30-32,32>>^ It is not to be rubbed in the flesh of mankind, and with its composition YOU must not make any like it. It is something holy. It is to continue as something holy for YOU.

[[v2-30-33]]

^<<v2-30-33,33>>^ Anyone who makes an ointment like it and who puts some of it upon a stranger^&#42;1^ must be cut off from his people.’”

[NOTE]
====
. “Stranger,” that is, a non-Aaronite. See 29:32, 33.
====

[[v2-30-34]]

^<<v2-30-34,34>>^ And Jehovah went on to say to Moses: “Take to yourself perfumes: stacte drops and onycha and perfumed galbanum and pure frankincense. There should be the same portion of each.

[[v2-30-35]]

^<<v2-30-35,35>>^ And you must make it into an incense, a spice mixture, the work of an ointment maker, salted, pure, something holy.

[[v2-30-36]]

^<<v2-30-36,36>>^ And you must pound some of it into fine powder and put some of it before the Testimony in the tent of meeting, where I shall present myself to you. It should be most holy to YOU people.

[[v2-30-37]]

^<<v2-30-37,37>>^ And the incense that you will make with this composition, YOU must not make for yourselves. For you it is to continue as something holy to Jehovah.

[[v2-30-38]]

^<<v2-30-38,38>>^ Whoever makes any like it to enjoy its smell must be cut off from his people.”

'''

xref:002-exodus/002-exodus-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodus/002-exodus-031.adoc#v2-31-0[Próximo Capítulo &#62;]