include::./index.adoc[]

[[v2-29-0]]
=== Exodus, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-29-1]]

^<<v2-29-1,1>>^ “And this is the thing that you are to do to them to sanctify them for acting as priests to me: Take a young bull,^&#42;1^ and two rams, sound ones,

[NOTE]
====
. Lit., “one bull, a son of the herd.”
====

[[v2-29-2]]

^<<v2-29-2,2>>^ and unfermented bread and unfermented ring-shaped cakes moistened with oil and unfermented wafers smeared with oil. Out of fine wheat flour you will make them.

[[v2-29-3]]

^<<v2-29-3,3>>^ And you must put them upon a basket and present them in the basket, and also the bull and the two rams.

[[v2-29-4]]

^<<v2-29-4,4>>^ “And you will present Aaron and his sons at the entrance of the tent of meeting, and you must wash them with water.

[[v2-29-5]]

^<<v2-29-5,5>>^ Then you must take the garments and clothe Aaron with the robe and the sleeveless coat of the ephʹod and with the ephʹod and the breastpiece, and you must tie it closely to him with the girdle of the ephʹod.

[[v2-29-6]]

^<<v2-29-6,6>>^ And you must set the turban upon his head and put the holy sign of dedication^&#42;1^ upon the turban.

[NOTE]
====
. Or, “the holy diadem; the diadem of holiness.” See 39:30 ftn, “Dedication.”
====

[[v2-29-7]]

^<<v2-29-7,7>>^ And you must take the anointing oil and pour it upon his head and anoint him.

[[v2-29-8]]

^<<v2-29-8,8>>^ “Then you will bring his sons near and you must clothe them with the robes.

[[v2-29-9]]

^<<v2-29-9,9>>^ And you must gird them with the sashes, Aaron as well as his sons, and you must wrap the headgear upon them; and the priesthood must become theirs as a statute to time indefinite.^&#42;1^ So you must fill the hand of Aaron and the hand of his sons with power.

[NOTE]
====
. “And they shall have a priestly office to me forever,” LXX. Compare Heb 7:28.
====

[[v2-29-10]]

^<<v2-29-10,10>>^ “You must now present the bull before the tent of meeting, and Aaron and his sons must lay their hands upon the bull’s head.

[[v2-29-11]]

^<<v2-29-11,11>>^ And you must slaughter the bull before Jehovah, at the entrance of the tent of meeting.

[[v2-29-12]]

^<<v2-29-12,12>>^ And you must take some of the bull’s blood and put it with your finger upon the horns of the altar, and all the rest of the blood you will pour out at the base of the altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ And you must take all the fat that covers the intestines, and the appendage upon the liver, and the two kidneys and the fat that is upon them, and you must make them smoke upon the altar.

[[v2-29-14]]

^<<v2-29-14,14>>^ But the bull’s flesh and its skin and its dung you will burn with fire outside the camp. It is a sin offering.

[[v2-29-15]]

^<<v2-29-15,15>>^ “Then you will take the one ram, and Aaron and his sons must lay their hands upon the ram’s head.

[[v2-29-16]]

^<<v2-29-16,16>>^ And you must slaughter the ram and take its blood and sprinkle it round about upon the altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ And you will cut up the ram into its pieces, and you must wash its intestines and its shanks and put its pieces to one another and up to its head.

[[v2-29-18]]

^<<v2-29-18,18>>^ And you must make the entire ram smoke upon the altar. It is a burnt offering to Jehovah, a restful odor. It is an offering made by fire^&#42;1^ to Jehovah.

[NOTE]
====
. “An offering made by fire.” The usual rendering, as though derived from ʼesh, “fire.” Others, deriving it from ʼnsh (KB, p. 70), take it to mean “the means by which to set up friendly relations with God.”
====

[[v2-29-19]]

^<<v2-29-19,19>>^ “Next you must take the other ram, and Aaron and his sons must lay their hands upon the ram’s head.

[[v2-29-20]]

^<<v2-29-20,20>>^ And you must slaughter the ram and take some of its blood and put it upon the lobe of Aaron’s right ear and upon the lobe of his sons’ right ear and upon the thumb of their right hand and the big toe of their right foot, and you must sprinkle the blood round about upon the altar.

[[v2-29-21]]

^<<v2-29-21,21>>^ And you must take some of the blood that is upon the altar and some of the anointing oil, and you must spatter it upon Aaron and his garments and upon his sons and the garments of his sons with him, that he and his garments and his sons and the garments of his sons with him may indeed be holy.

[[v2-29-22]]

^<<v2-29-22,22>>^ “And you must take from the ram the fat and the fat tail and the fat that covers the intestines, and the appendage of the liver, and the two kidneys and the fat that is upon them, and the right leg, for it is a ram of installation;^&#42;1^

[NOTE]
====
. Lit., “filling,” that is, filling of the hand with power, an empowering.
====

[[v2-29-23]]

^<<v2-29-23,23>>^ also a round loaf of bread and a ring-shaped cake of oiled bread and a wafer out of the basket of unfermented cakes that is before Jehovah.

[[v2-29-24]]

^<<v2-29-24,24>>^ And you must place them all upon the palms of Aaron and upon the palms of his sons, and you must wave them to and fro as a wave offering before Jehovah.

[[v2-29-25]]

^<<v2-29-25,25>>^ And you must take them off their hands and make them smoke upon the altar upon the burnt offering as a restful odor before Jehovah. It is an offering made by fire to Jehovah.

[[v2-29-26]]

^<<v2-29-26,26>>^ “And you must take the breast of the ram of installation, which is for Aaron, and wave it to and fro as a wave offering before Jehovah, and it must become your portion.

[[v2-29-27]]

^<<v2-29-27,27>>^ And you must sanctify the breast of the wave offering and the leg of the sacred portion^&#42;1^ that was waved and that was contributed from the ram of installation, from what was for Aaron and from what was for his sons.

[NOTE]
====
. Or, “heave offering; contribution.”
====

[[v2-29-28]]

^<<v2-29-28,28>>^ And it must become Aaron’s and his sons’ by a regulation to time indefinite to be performed by the sons of Israel, because it is a sacred portion; and it will become a sacred portion to be rendered by the sons of Israel. From their communion sacrifices^&#42;1^ it is their sacred portion for Jehovah.

[NOTE]
====
. Or, “From the sacrifices of their peace offerings.”
====

[[v2-29-29]]

^<<v2-29-29,29>>^ “And the holy garments that are Aaron’s will serve for his sons after him to anoint them in them and to fill their hand with power in them.

[[v2-29-30]]

^<<v2-29-30,30>>^ Seven days the priest who succeeds him from among his sons and who comes into the tent of meeting to minister in the holy place will wear them.

[[v2-29-31]]

^<<v2-29-31,31>>^ “And you will take the ram of installation, and you must boil its flesh in a holy place.

[[v2-29-32]]

^<<v2-29-32,32>>^ And Aaron and his sons must eat the flesh of the ram and the bread that is in the basket at the entrance of the tent of meeting.

[[v2-29-33]]

^<<v2-29-33,33>>^ And they must eat the things with which atonement^&#42;1^ has been made to fill their hand with power, in order to sanctify them. But a stranger^&#42;2^ may not eat them, because they are something holy.

[NOTE]
====
. Lit., “a covering.”
. Or, “non-Aaronite,” that is, a man not of the family of Aaron.
====

[[v2-29-34]]

^<<v2-29-34,34>>^ And if any of the flesh of the installation sacrifice and of the bread should be left over until the morning, then you must burn what is left over with fire. It must not be eaten, because it is something holy.

[[v2-29-35]]

^<<v2-29-35,35>>^ “And you must do this way to Aaron and his sons according to all that I have commanded you. You will take seven days to fill their hand with power.

[[v2-29-36]]

^<<v2-29-36,36>>^ And you will offer the bull of the sin offering daily for an atonement, and you must purify the altar from sin by your making atonement over it, and you must anoint it to sanctify it.

[[v2-29-37]]

^<<v2-29-37,37>>^ You will take seven days to make atonement over the altar, and you must sanctify it that it may indeed become a most holy altar. Anyone who^&#42;1^ touches the altar is to be holy.

[NOTE]
====
. Or, “Anything that.”
====

[[v2-29-38]]

^<<v2-29-38,38>>^ “And this is what you will offer upon the altar: young rams each a year old, two a day constantly.

[[v2-29-39]]

^<<v2-29-39,39>>^ And you will offer the one young ram^&#42;1^ in the morning, and you will offer the other young ram between the two evenings.^&#42;2^

[NOTE]
====
. Or, “one male lamb.”
. See 12:6 ftn.
====

[[v2-29-40]]

^<<v2-29-40,40>>^ And a tenth part of an eʹphah measure^&#42;1^ of fine flour moistened with the fourth of a hin^&#42;2^ of beaten oil, and a drink offering of the fourth of a hin of wine, will go for the first young ram.

[NOTE]
====
. “And a tenth part of an ephah measure,” according to Nu 15:4 in LXXVg. Lit., “And a tenth part of.” See App 8A.
. A hin equaled 3.67 L (7.75 pt).
====

[[v2-29-41]]

^<<v2-29-41,41>>^ And you will offer the second young ram between the two evenings. With a grain offering like that of the morning and with a drink offering like its, you will render it as a restful odor, an offering made by fire to Jehovah.

[[v2-29-42]]

^<<v2-29-42,42>>^ It is a constant burnt offering throughout YOUR generations at the entrance of the tent of meeting before Jehovah, where I shall present myself to YOU people to speak to you there.

[[v2-29-43]]

^<<v2-29-43,43>>^ “And I will present myself there to the sons of Israel, and it^&#42;1^ will certainly be sanctified^&#42;2^ by my glory.

[NOTE]
====
. “It,” M; Vg, “the altar.”
. “And it will certainly be sanctified (held sacred; treated as holy).” Heb., weniq·dashʹ; Lat., sanc·ti·fi·caʹbi·tur; Gr., ha·gi·a·stheʹso·mai, “I will be sanctified.” See Mt 6:9 ftn.
====

[[v2-29-44]]

^<<v2-29-44,44>>^ And I will sanctify the tent of meeting and the altar; and I shall sanctify Aaron and his sons for them to act as priests to me.

[[v2-29-45]]

^<<v2-29-45,45>>^ And I will tabernacle in the midst of the sons of Israel, and I will prove to be their God.

[[v2-29-46]]

^<<v2-29-46,46>>^ And they will certainly know that I am Jehovah their God, who brought them out of the land of Egypt that I may tabernacle in the midst of them. I am Jehovah their God.

'''

xref:002-exodus/002-exodus-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodus/002-exodus-030.adoc#v2-30-0[Próximo Capítulo &#62;]