include::./index.adoc[]

[[v2-26-0]]
=== Exodus, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-26-1]]

^<<v2-26-1,1>>^ “And the tabernacle^&#42;1^ you are to make of ten tent cloths, of fine twisted linen and blue thread and wool dyed reddish purple and coccus scarlet material. With cherubs, the work of an embroiderer, you will make them.

[NOTE]
====
. Or, “residence place.”
====

[[v2-26-2]]

^<<v2-26-2,2>>^ The length of each tent cloth is twenty-eight cubits and the width of each tent cloth is four cubits. There is one measure for all the tent cloths.

[[v2-26-3]]

^<<v2-26-3,3>>^ Five tent cloths are to form a series with the one joined to the other, and five tent cloths a series with the one joined to the other.

[[v2-26-4]]

^<<v2-26-4,4>>^ And you must make loops of blue thread upon the edge of the one tent cloth at the end of the series; and you are to do the same upon the edge of the outermost tent cloth at the other place of junction.

[[v2-26-5]]

^<<v2-26-5,5>>^ You will make fifty loops on the one tent cloth, and fifty loops you will make on the extremity of the tent cloth that is at the other place of junction, the loops being opposite one to the other.

[[v2-26-6]]

^<<v2-26-6,6>>^ And you must make fifty hooks of gold and join the tent cloths one to the other by means of the hooks, and it must become one tabernacle.

[[v2-26-7]]

^<<v2-26-7,7>>^ “And you must make cloths of goat’s hair for the tent upon the tabernacle. You will make eleven tent cloths.

[[v2-26-8]]

^<<v2-26-8,8>>^ The length of each tent cloth is thirty cubits, and the width of each tent cloth is four cubits. There is one measure for the eleven tent cloths.

[[v2-26-9]]

^<<v2-26-9,9>>^ And you must join five tent cloths by themselves and six tent cloths by themselves, and you must fold double the sixth tent cloth at the forefront of the tent.

[[v2-26-10]]

^<<v2-26-10,10>>^ And you must make fifty loops upon the edge of the one tent cloth, the outermost one in the series, and fifty loops upon the edge of the tent cloth at the other place of junction.

[[v2-26-11]]

^<<v2-26-11,11>>^ And you must make fifty hooks of copper and put the hooks in the loops and join the tent together, and it must become one.

[[v2-26-12]]

^<<v2-26-12,12>>^ And what remains over of the cloths of the tent is an overhanging. Half of the tent cloth that remains over is to hang over the back of the tabernacle.

[[v2-26-13]]

^<<v2-26-13,13>>^ And the cubit on this side and the cubit on that side in what remains over in the length of the cloths of the tent will serve as an overhanging on the sides of the tabernacle, to cover it on this side and on that.

[[v2-26-14]]

^<<v2-26-14,14>>^ “And you must make a covering for the tent of ram skins dyed red and a covering of sealskins up on top.

[[v2-26-15]]

^<<v2-26-15,15>>^ “And you must make the panel frames^&#42;1^ for the tabernacle of acacia wood, standing on end.

[NOTE]
====
. “Panel frames,” rather than boards, which would have been solid timbers, hence, difficult to handle because of size and weight.
====

[[v2-26-16]]

^<<v2-26-16,16>>^ Ten cubits is the length of a panel frame, and a cubit and a half is the width of each panel frame.

[[v2-26-17]]

^<<v2-26-17,17>>^ Each panel frame has two tenons joined one to the other. That is the way you will do with all the panel frames of the tabernacle.

[[v2-26-18]]

^<<v2-26-18,18>>^ And you must make the panel frames for the tabernacle, twenty panel frames for the side toward the Negʹeb, to the south.

[[v2-26-19]]

^<<v2-26-19,19>>^ “And you will make forty socket pedestals of silver under the twenty panel frames; two socket pedestals under the one panel frame with its two tenons, and two socket pedestals under the other panel frame with its two tenons.

[[v2-26-20]]

^<<v2-26-20,20>>^ And for the other side of the tabernacle, the northern side, twenty panel frames,

[[v2-26-21]]

^<<v2-26-21,21>>^ and their forty socket pedestals of silver, two socket pedestals under the one panel frame and two socket pedestals under the other panel frame.

[[v2-26-22]]

^<<v2-26-22,22>>^ And for the rear sections of the tabernacle to the west you will make six panel frames.

[[v2-26-23]]

^<<v2-26-23,23>>^ And you will make two panel frames as corner posts of the tabernacle on its two rear sections.

[[v2-26-24]]

^<<v2-26-24,24>>^ And they should be duplicates at the bottom, and together they should be duplicates up to the top of each one at the first ring. That is the way it should be for the two of them. They will serve as two corner posts.

[[v2-26-25]]

^<<v2-26-25,25>>^ And there must be eight panel frames and their socket pedestals of silver, sixteen pedestals, two socket pedestals under the one panel frame and two socket pedestals under the other panel frame.

[[v2-26-26]]

^<<v2-26-26,26>>^ “And you must make bars of acacia wood, five for the panel frames of the one side of the tabernacle,

[[v2-26-27]]

^<<v2-26-27,27>>^ and five bars for the panel frames of the other side of the tabernacle and five bars for the panel frames of the side of the tabernacle for the two rear sections to the west.

[[v2-26-28]]

^<<v2-26-28,28>>^ And the middle bar at the center of the panel frames is running through from end to end.

[[v2-26-29]]

^<<v2-26-29,29>>^ “And you will overlay the panel frames with gold, and their rings you will make of gold as supports for the bars; and you must overlay the bars with gold.

[[v2-26-30]]

^<<v2-26-30,30>>^ And you must set up the tabernacle according to the plan of it that you have been shown in the mountain.

[[v2-26-31]]

^<<v2-26-31,31>>^ “And you must make a curtain of blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen. He will make it with cherubs, the work of an embroiderer.

[[v2-26-32]]

^<<v2-26-32,32>>^ And you must put it upon four pillars of acacia overlaid with gold. Their pegs are of gold. They are upon four socket pedestals of silver.

[[v2-26-33]]

^<<v2-26-33,33>>^ And you must put the curtain under the hooks and bring the ark of the testimony there within the curtain; and the curtain must make a division for YOU between the Holy and the Most Holy.^&#42;1^

[NOTE]
====
. Or, “the Holy of Holies.” Lit., “Holy of the Holies.” Heb., Qoʹdhesh haq·Qodha·shimʹ.
====

[[v2-26-34]]

^<<v2-26-34,34>>^ And you must put the cover upon the ark of the testimony in the Most Holy.

[[v2-26-35]]

^<<v2-26-35,35>>^ “And you must set the table outside the curtain, and the lampstand opposite the table on the side of the tabernacle toward the south; and the table you will put on the north side.

[[v2-26-36]]

^<<v2-26-36,36>>^ And you must make a screen for the entrance of the tent of blue thread and wool dyed reddish purple and coccus scarlet material and fine twisted linen, the work of a weaver.

[[v2-26-37]]

^<<v2-26-37,37>>^ And you must make for the screen five pillars of acacia and overlay them with gold. Their pegs are of gold. And you must cast for them five socket pedestals of copper.

'''

xref:002-exodus/002-exodus-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodus/002-exodus-027.adoc#v2-27-0[Próximo Capítulo &#62;]