include::./index.adoc[]

[[v2-22-0]]
=== Exodus, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v2-22-1]]

^<<v2-22-1,1>>^ “In case a man should steal a bull or a sheep and he does slaughter it or sell it, he is to compensate with five of the herd for the bull and four of the flock for the sheep.^&#42;1^

[NOTE]
====
. MLXX end 21:37 here.
====

[[v2-22-2]]

^<<v2-22-2,2>>^ (“If a thief should be found in the act of breaking in and he does get struck and die, there is no bloodguilt^&#42;1^ for him.

[NOTE]
====
. Lit., “bloods.”
====

[[v2-22-3]]

^<<v2-22-3,3>>^ If the sun has shone forth upon him, there is bloodguilt for him.)
“He is to make compensation without fail. If he has nothing, then he must be sold for the things he stole.

[[v2-22-4]]

^<<v2-22-4,4>>^ If there should be unmistakably found in his hand what was stolen, from bull to ass and to sheep, alive, he is to make double compensation.

[[v2-22-5]]

^<<v2-22-5,5>>^ “If a man causes a field or a vineyard to be grazed over^&#42;1^ and he does send out his beasts of burden and cause a consuming in another field, he is to make compensation with the best of his own field or with the best of his own vineyard.

[NOTE]
====
. “But if anyone should feed his cattle (flocks) in a field or a vineyard,” LXX; Vg, “If anybody should damage a field or a vineyard.”
====

[[v2-22-6]]

^<<v2-22-6,6>>^ “In case a fire should spread out and it does catch thorns, and sheaves or standing grain or a field gets consumed, the one who started the fire is to make compensation without fail &#91;for what was burned&#93;.

[[v2-22-7]]

^<<v2-22-7,7>>^ “In case a man should give his fellow money or articles to keep, and it gets stolen from the man’s house, if the thief should be found, he is to make double compensation.

[[v2-22-8]]

^<<v2-22-8,8>>^ If the thief should not be found, then the owner of the house must be brought near to the &#91;true&#93; God to see whether he did not put his hand upon the goods of his fellow.

[[v2-22-9]]

^<<v2-22-9,9>>^ As regards any case of transgression, concerning a bull, an ass, a sheep, a garment, anything lost of which he may say, ‘This is it!’ the case of them both is to come to the &#91;true&#93; God.^&#42;1^ The one whom God^&#42;2^ will pronounce^&#42;3^ wicked is to make double compensation to his fellow.

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElo·himʹ; Sam, “Jehovah.”
. “God.” Heb., ʼElo·himʹ; Sam(Heb.), ha·ʼElo·himʹ; Gr., The·ouʹ. Compare App 1F.
. “Will pronounce.” This verb, of which ʼElo·himʹ is the subject, is pl. in M but sing. in Sam.
====

[[v2-22-10]]

^<<v2-22-10,10>>^ “In case a man should give his fellow an ass or bull or sheep or any domestic animal to keep, and it does die or get maimed or gets led off while nobody is looking,

[[v2-22-11]]

^<<v2-22-11,11>>^ an oath by Jehovah is to take place between them both that he did not put his hand on the goods of his fellow; and their owner^&#42;1^ must accept it, and the other is not to make compensation.

[NOTE]
====
. Lit., “its owners.” Heb., beʽa·lavʹ, pl. to denote respect and with a sing. verb; Gr., kyʹri·os.
====

[[v2-22-12]]

^<<v2-22-12,12>>^ But if they should for a fact be stolen from him, he is to make compensation to their owner.^&#42;1^

[NOTE]
====
. Lit., “to its owners.” Heb., liv·ʽa·lavʹ, pl. to denote respect; Gr., ky·riʹoi; Lat., doʹmi·no.
====

[[v2-22-13]]

^<<v2-22-13,13>>^ If it should for a fact be torn by a wild beast, he is to bring it as evidence. For something torn by a wild beast he is not to make compensation.

[[v2-22-14]]

^<<v2-22-14,14>>^ “But in case anybody should ask for something of his fellow, and it does get maimed or die while its owner is not with it, he is to make compensation without fail.

[[v2-22-15]]

^<<v2-22-15,15>>^ If its owner is with it, he is not to make compensation. If it is hired, it must come in its hire.

[[v2-22-16]]

^<<v2-22-16,16>>^ “Now in case a man seduces a virgin who is not engaged, and he actually lies down with her, he is to obtain her without fail as his wife for the purchase price.

[[v2-22-17]]

^<<v2-22-17,17>>^ If her father flatly refuses to give her to him, he is to pay over the money at the rate of purchase money for virgins.

[[v2-22-18]]

^<<v2-22-18,18>>^ “You must not preserve a sorceress alive.

[[v2-22-19]]

^<<v2-22-19,19>>^ “Anyone lying down with a beast is positively to be put to death.

[[v2-22-20]]

^<<v2-22-20,20>>^ “One who sacrifices to any gods but Jehovah alone is to be devoted to destruction.^&#42;1^

[NOTE]
====
. Or, “be put under ban; be devoted to Jehovah for extermination.”
====

[[v2-22-21]]

^<<v2-22-21,21>>^ “And you must not maltreat an alien resident^&#42;1^ or oppress him, for YOU people became alien residents in the land of Egypt.

[NOTE]
====
. Or, “a sojourner; an immigrant.”
====

[[v2-22-22]]

^<<v2-22-22,22>>^ “YOU people must not afflict any widow or fatherless boy.

[[v2-22-23]]

^<<v2-22-23,23>>^ If you should afflict him at all, then if he cries out to me at all, I shall unfailingly hear his outcry;

[[v2-22-24]]

^<<v2-22-24,24>>^ and my anger will indeed blaze, and I shall certainly kill YOU with the sword, and YOUR wives must become widows and YOUR sons fatherless boys.

[[v2-22-25]]

^<<v2-22-25,25>>^ “If you should lend money to my people, to the afflicted alongside you, you must not become like a usurer to him. YOU must not lay interest upon him.

[[v2-22-26]]

^<<v2-22-26,26>>^ “If you should at all seize the garment of your fellow as a pledge, you are to return it to him at the setting of the sun.

[[v2-22-27]]

^<<v2-22-27,27>>^ For it is his only covering. It is his mantle for his skin. In what will he lie down? And it must occur that he will cry out to me, and I shall certainly hear, because I am gracious.

[[v2-22-28]]

^<<v2-22-28,28>>^ “You must not call down evil upon God^&#42;1^ nor curse a chieftain^&#42;2^ among your people.

[NOTE]
====
. “God.” MSam(Heb.), ʼElo·himʹ; Gr., the·ousʹ, “gods”; Lat., diʹis, “gods.”
. Or, “nasi.”
====

[[v2-22-29]]

^<<v2-22-29,29>>^ “Your full produce and the overflow of your press you must not give hesitantly. The firstborn of your sons you are to give to me.

[[v2-22-30]]

^<<v2-22-30,30>>^ The way you are to do with your bull and your sheep is this: Seven days it will continue with its mother. On the eighth day you are to give it to me.

[[v2-22-31]]

^<<v2-22-31,31>>^ “And YOU should prove yourselves holy men to me; and YOU must not eat flesh in the field that is something torn by a wild beast. YOU should throw it to the dogs.

'''

xref:002-exodus/002-exodus-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodus/002-exodus-023.adoc#v2-23-0[Próximo Capítulo &#62;]