include::./index.adoc[]

[[v8-2-0]]
=== Ruth, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v8-2-1]]

^<<v8-2-1,1>>^ Now Naʹo·mi had a kinsman^&#42;1^ of her husband, a man mighty in wealth, of the family of E·limʹe·lech, and his name was Boʹaz.^&#42;2^

[NOTE]
====
. Or, “acquaintance.”
. Possibly meaning “In Strength.”
====

[[v8-2-2]]

^<<v8-2-2,2>>^ In time Ruth the Moʹab·ite woman said to Naʹo·mi: “Let me go, please, to the field and glean among the ears of grain following after whoever it is in whose eyes I may find favor.” So she said to her: “Go, my daughter.”

[[v8-2-3]]

^<<v8-2-3,3>>^ At that she went off and entered and began to glean in the field behind the harvesters. Thus by chance she lighted on the tract of the field belonging to Boʹaz, who was of the family of E·limʹe·lech.

[[v8-2-4]]

^<<v8-2-4,4>>^ And, look! Boʹaz came from Bethʹle·hem and proceeded to say to the harvesters: “Jehovah be with YOU.” In turn they would say to him: “Jehovah bless you.”

[[v8-2-5]]

^<<v8-2-5,5>>^ Subsequently Boʹaz said to the young man who was set over the harvesters: “To whom does this young woman belong?”

[[v8-2-6]]

^<<v8-2-6,6>>^ So the young man set over the harvesters answered and said: “The young woman is a Moʹab·i·tess, who returned with Naʹo·mi from the field of Moʹab.

[[v8-2-7]]

^<<v8-2-7,7>>^ Then she said, ‘Let me glean, please, and I shall certainly gather among the cut-off ears of grain behind the harvesters.’ So she entered and kept on her feet from that time in the morning until her sitting down just now in the house a little while.”

[[v8-2-8]]

^<<v8-2-8,8>>^ Later Boʹaz said to Ruth: “You have heard, have you not, my daughter? Do not go away to glean in another field, and you must also not cross over from this place, and in that way you should keep close by my young women.

[[v8-2-9]]

^<<v8-2-9,9>>^ Let your eyes be on the field that they will harvest, and you must go with them. Have I not commanded the young men not to touch you? When you are thirsty, you must also go to the vessels and drink from what the young men will draw.”

[[v8-2-10]]

^<<v8-2-10,10>>^ At that she fell upon her face and bowed down to the earth and said to him: “How is it I have found favor in your eyes so that I am taken notice of, when I am a foreigner?”

[[v8-2-11]]

^<<v8-2-11,11>>^ Then Boʹaz answered and said to her: “The report was fully made to me of all that you have done to your mother-in-law after the death of your husband, and how you proceeded to leave your father and your mother and the land of your relatives and to go to a people whom you had not known formerly.

[[v8-2-12]]

^<<v8-2-12,12>>^ May Jehovah reward the way you act, and may there come to be a perfect wage for you from Jehovah the God of Israel, under whose wings you have come to seek refuge.”

[[v8-2-13]]

^<<v8-2-13,13>>^ To this she said: “Let me find favor in your eyes, my lord, because you have comforted me and because you have spoken reassuringly to^&#42;1^ your maidservant, although I myself may not happen to be like one of your maidservants.”

[NOTE]
====
. Lit., “spoken to the heart of.”
====

[[v8-2-14]]

^<<v8-2-14,14>>^ And Boʹaz proceeded to say to her at mealtime: “Approach here, and you must eat some of the bread and dip your piece in the vinegar.” So she sat down beside the harvesters, and he would hold out roasted grain to her and she would eat, so that she was satisfied and yet had something left over.

[[v8-2-15]]

^<<v8-2-15,15>>^ Then she got up to glean. Boʹaz now commanded his young men, saying: “Let her glean also among the cut-off ears of grain, and YOU must not molest her.

[[v8-2-16]]

^<<v8-2-16,16>>^ And YOU should also be sure to pull out some from the bundles of ears for her, and YOU must leave them behind that she may glean them, and YOU must not rebuke her.”

[[v8-2-17]]

^<<v8-2-17,17>>^ And she continued to glean in the field until the evening, after which she beat out what she had gleaned, and it came to be about an eʹphah^&#42;1^ of barley.

[NOTE]
====
. About 22 L (20 dry qt).
====

[[v8-2-18]]

^<<v8-2-18,18>>^ Then she took it up and went into the city, and her mother-in-law got to see^&#42;1^ what she had gleaned. After that she took out what food she had left over when she had satisfied herself and gave it to her.

[NOTE]
====
. “And her mother-in-law got to see,” MLXX; SyVg, “and showed her mother-in-law.”
====

[[v8-2-19]]

^<<v8-2-19,19>>^ Her mother-in-law now said to her: “Where did you glean today, and where did you work? May the one who took notice of you become blessed.” So she told her mother-in-law with whom she had worked; and she went on to say: “The name of the man with whom I worked today is Boʹaz.”

[[v8-2-20]]

^<<v8-2-20,20>>^ At that Naʹo·mi said to her daughter-in-law: “Blessed be he of Jehovah, who has not left his loving-kindness toward the living and the dead.” And Naʹo·mi went on to say to her: “The man is related to us. He is one of our repurchasers.”^&#42;1^

[NOTE]
====
. Or, “one of our kinsmen with the right to repurchase (redeem).” Heb., mig·go·ʼaleʹnu, sing.; pl. in several Heb. mss.
====

[[v8-2-21]]

^<<v8-2-21,21>>^ Then Ruth the Moʹab·i·tess said: “He also said to me, ‘Close by the young people that are mine is where you should keep until they have finished the entire harvest that I have.’”

[[v8-2-22]]

^<<v8-2-22,22>>^ So Naʹo·mi said to Ruth her daughter-in-law: “It is better, my daughter, that you should go out with his young women, that they may not annoy you in another field.”

[[v8-2-23]]

^<<v8-2-23,23>>^ And she continued to keep close by the young women of Boʹaz to glean until the harvest of the barley and the harvest of the wheat came to an end. And she kept on dwelling with her mother-in-law.

'''

xref:008-ruth/008-ruth-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-ruth/008-ruth-003.adoc#v8-3-0[Próximo Capítulo &#62;]