include::./index.adoc[]

[[v8-4-0]]
=== Ruth, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v8-4-1]]

^<<v8-4-1,1>>^ As for Boʹaz, he went up to the gate and began to sit there. And, look! the repurchaser was passing by, whom Boʹaz had mentioned. Then he said: “Do turn aside, do sit down here, So-and-so.”^&#42;1^ Hence he turned aside and sat down.

[NOTE]
====
. “So-and-so.” Heb., Pelo·niʹ ʼAl·mo·niʹ.
====

[[v8-4-2]]

^<<v8-4-2,2>>^ After that he took ten men of the older men^&#42;1^ of the city and said: “Sit down here.” So they sat down.

[NOTE]
====
. Or, “elders.”
====

[[v8-4-3]]

^<<v8-4-3,3>>^ He now said to the repurchaser: “The tract of the field that belonged to our brother E·limʹe·lech, Naʹo·mi, who has returned from the field of Moʹab, must sell.

[[v8-4-4]]

^<<v8-4-4,4>>^ As for me, I thought^&#42;1^ that I should disclose it to you,^&#42;2^ saying, ‘Buy it in front of the inhabitants and the older men of my people. If you will repurchase it, repurchase it; but if you will not repurchase it, do tell me, that I may know, for there is no one else but you to do the repurchasing, and I am next to you.’” At that he said: “I shall be the one to repurchase it.”

[NOTE]
====
. Lit., “I said [to myself].”
. Lit., “I should uncover your ear.”
====

[[v8-4-5]]

^<<v8-4-5,5>>^ Then Boʹaz said: “On the day that you buy the field from Naʹo·mi’s hand, it is also from Ruth the Moʹab·i·tess, the wife of the dead man, that you must buy it so as to cause the name of the dead man to rise upon his inheritance.”

[[v8-4-6]]

^<<v8-4-6,6>>^ To this the repurchaser said: “I am unable to repurchase it for myself, for fear I may ruin my own inheritance. You repurchase it for yourself with my right of repurchase, because I am not able to do the repurchasing.”

[[v8-4-7]]

^<<v8-4-7,7>>^ Now this was the custom^&#42;1^ of former times in Israel concerning the right of repurchase and concerning the exchange, to establish every sort of thing: A man had to draw his sandal off and give it to his fellow, and this was the attestation in Israel.

[NOTE]
====
. “Custom,” LXXSyVg; M omits.
====

[[v8-4-8]]

^<<v8-4-8,8>>^ So when the repurchaser^&#42;1^ said to Boʹaz: “Buy it for yourself,” he proceeded to draw his sandal off.^&#42;2^

[NOTE]
====
. “The repurchaser (goel).” Heb., hag·go·ʼelʹ. See Nu 5:8; 35:12.
. LXX adds, “and give it to him.”
====

[[v8-4-9]]

^<<v8-4-9,9>>^ Then Boʹaz said to the older men and all the people: “YOU are witnesses today that I do buy all that belonged to E·limʹe·lech and all that belonged to Chilʹi·on and Mahʹlon from the hand of Naʹo·mi.

[[v8-4-10]]

^<<v8-4-10,10>>^ And also Ruth the Moʹab·i·tess, the wife of Mahʹlon, I do buy for myself as a wife to cause the name of the dead man to rise upon his inheritance and that the name of the dead man may not be cut off from among his brothers and from the gate of his place. YOU are witnesses today.”

[[v8-4-11]]

^<<v8-4-11,11>>^ At this all the people that were in the gate and the older men said: “Witnesses! May Jehovah grant the wife^&#42;1^ who is coming into your house to be like Rachel and like Leʹah, both of whom built the house of Israel; and you prove your worth in Ephʹra·thah and make a notable name^&#42;2^ in Bethʹle·hem.

[NOTE]
====
. Or, “woman.” TSy, “this wife of yours”; LXX, “your wife.”
. Lit., “and proclaim a name.” See vs 14.
====

[[v8-4-12]]

^<<v8-4-12,12>>^ And may your house become like the house of Peʹrez, whom Taʹmar bore to Judah, from the offspring that Jehovah will give you out of this young woman.”

[[v8-4-13]]

^<<v8-4-13,13>>^ Accordingly Boʹaz took Ruth and she became his wife and he had relations with her. So Jehovah granted her conception and she bore a son.

[[v8-4-14]]

^<<v8-4-14,14>>^ And the women began to say to Naʹo·mi: “Blessed be Jehovah, who has not let a repurchaser fail for you today; that his^&#42;1^ name may be proclaimed in Israel.

[NOTE]
====
. “His,” MSyVg; LXXIt, “your.”
====

[[v8-4-15]]

^<<v8-4-15,15>>^ And he has become a restorer of your soul^&#42;1^ and one to nourish your old age, because your daughter-in-law who does love you, who is better to you than seven sons, has given birth to him.”

[NOTE]
====
. Or, “a bringer back of your life [Heb., neʹphesh; Gr., psy·khenʹ; Lat., aʹni·mam].”
====

[[v8-4-16]]

^<<v8-4-16,16>>^ And Naʹo·mi proceeded to take the child and to put it in her bosom, and she came to be its nurse.

[[v8-4-17]]

^<<v8-4-17,17>>^ Then the neighbor ladies gave it a name, saying: “A son has been born to Naʹo·mi.” And they began to call his name Oʹbed.^&#42;1^ He is the father of Jesʹse, David’s father.

[NOTE]
====
. Meaning “Servant; One Serving.”
====

[[v8-4-18]]

^<<v8-4-18,18>>^ Now these are the generations of Peʹrez: Peʹrez became father to Hezʹron;

[[v8-4-19]]

^<<v8-4-19,19>>^ and Hezʹron became father to Ram; and Ram became father to Am·minʹa·dab;

[[v8-4-20]]

^<<v8-4-20,20>>^ and Am·minʹa·dab became father to Nahʹshon; and Nahʹshon became father to Salʹmon;^&#42;1^

[NOTE]
====
. “Salmon,” LXXAVgc, several Heb. mss and Armenian, Ethiopic and Sahidic versions; M, “Salma”; LXXB, “Salman.”
====

[[v8-4-21]]

^<<v8-4-21,21>>^ and Salʹmon^&#42;1^ became father to Boʹaz; and Boʹaz became father to Oʹbed;

[NOTE]
====
. “Salmon,” MLXXAVgc; LXXB, “Salman.” See Mt 1:4, 5; Lu 3:31-33.
====

[[v8-4-22]]

^<<v8-4-22,22>>^ and Oʹbed became father to Jesʹse; and Jesʹse became father to David.

'''

xref:008-ruth/008-ruth-003.adoc#v8-3-0[&#60; Capítulo Anterior] | <<v8-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[Próximo Capítulo &#62;]