include::./index.adoc[]

[[v8-1-0]]
=== Ruth, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v8-1-1]]

^<<v8-1-1,1>>^ Now it came about in the days when the judges administered justice that a famine arose in the land, and a man proceeded to go from Bethʹle·hem in Judah to reside as an alien in the fields of Moʹab, he with his wife and his two sons.

[[v8-1-2]]

^<<v8-1-2,2>>^ And the man’s name was E·limʹe·lech,^&#42;1^ and his wife’s name Naʹo·mi, and the names of his two sons were Mahʹlon and Chilʹi·on, Ephʹrath·ites^&#42;2^ from Bethʹle·hem in Judah. Eventually they came to the fields of Moʹab and continued there.

[NOTE]
====
. Meaning “God Is King.”
. Or, “inhabitants of Ephrath.” See Ge 35:16, 19.
====

[[v8-1-3]]

^<<v8-1-3,3>>^ In time E·limʹe·lech the husband of Naʹo·mi died, so that she remained with her two sons.

[[v8-1-4]]

^<<v8-1-4,4>>^ Later the men took wives for themselves, Moʹab·ite women. The name of the one was Orʹpah, and the name of the other Ruth. And they went on dwelling there for about ten years.

[[v8-1-5]]

^<<v8-1-5,5>>^ In time the two of them, Mahʹlon^&#42;1^ and Chilʹi·on,^&#42;2^ also died, so that the woman remained without her two children and her husband.

[NOTE]
====
. Meaning “Sickly; Invalid.”
. Meaning “Frailty.”
====

[[v8-1-6]]

^<<v8-1-6,6>>^ And she proceeded to get up with her daughters-in-law and to return from the fields of Moʹab, for she had heard in the field of Moʹab that Jehovah had turned his attention to^&#42;1^ his people by giving them bread.

[NOTE]
====
. Or, “had visited.”
====

[[v8-1-7]]

^<<v8-1-7,7>>^ And she went her way out from the place where she had continued, and both of her daughters-in-law were with her, and they kept walking on the road to return to the land of Judah.

[[v8-1-8]]

^<<v8-1-8,8>>^ Finally Naʹo·mi said to both of her daughters-in-law: “Go, return, each one to the house of her mother. May Jehovah exercise loving-kindness^&#42;1^ toward YOU, just as YOU have exercised it toward the men now dead and toward me.

[NOTE]
====
. Or, “loyal love.”
====

[[v8-1-9]]

^<<v8-1-9,9>>^ May Jehovah make a gift to YOU, and do YOU find a resting-place each one in the house of her husband.” Then she kissed them, and they began to raise their voices and weep.

[[v8-1-10]]

^<<v8-1-10,10>>^ And they kept saying to her: “No, but with you we shall return to your people.”

[[v8-1-11]]

^<<v8-1-11,11>>^ But Naʹo·mi said: “Return, my daughters. Why should YOU go with me? Do I still have sons in my inward parts, and will they have to become YOUR husbands?

[[v8-1-12]]

^<<v8-1-12,12>>^ Return, my daughters, go, for I have grown too old to get to belong to a husband. If I had said I had hope also that I should certainly become a husband’s tonight and also should certainly bear sons,

[[v8-1-13]]

^<<v8-1-13,13>>^ would YOU keep waiting for them^&#42;1^ until they could grow up? Would YOU keep yourselves secluded for them so as not to become a husband’s? No, my daughters, for it is very bitter to me because of YOU, that the hand of Jehovah has gone out against me.”

[NOTE]
====
. “Them,” masc., LXXSyVg.
====

[[v8-1-14]]

^<<v8-1-14,14>>^ At that they raised their voices and wept some more, after which Orʹpah kissed her mother-in-law. As for Ruth, she stuck with her.

[[v8-1-15]]

^<<v8-1-15,15>>^ So she said: “Look! Your widowed sister-in-law^&#42;1^ has returned to her people and her gods. Return with your widowed sister-in-law.”

[NOTE]
====
. That is, the widow of the brother of a wife’s husband. See De 25:5, 7.
====

[[v8-1-16]]

^<<v8-1-16,16>>^ And Ruth proceeded to say: “Do not plead with me to abandon you, to turn back from accompanying you;^&#42;1^ for where you go I shall go, and where you spend the night I shall spend the night. Your people will be my people, and your God my God.

[NOTE]
====
. Or, “from following you.” Lit., “from after you.” Heb., me·ʼa·charaʹyikh. Compare Ge 16:13 ftn, “Him”; Jg 13:11 ftn.
====

[[v8-1-17]]

^<<v8-1-17,17>>^ Where you die I shall die, and there is where I shall be buried. May Jehovah do so to me and add to it if anything but death should make a separation between me and you.”

[[v8-1-18]]

^<<v8-1-18,18>>^ When she got to see that she was persistent about going with her, then she left off speaking to her.

[[v8-1-19]]

^<<v8-1-19,19>>^ And they both continued on their way until they came to Bethʹle·hem. And it came about that as soon as they came to Bethʹle·hem, all the city became stirred up over them, and the women kept saying: “Is this Naʹo·mi?”

[[v8-1-20]]

^<<v8-1-20,20>>^ And she would say to the women: “Do not call me Naʹo·mi.^&#42;1^ Call me Maʹra,^&#42;2^ for the Almighty^&#42;3^ has made it very bitter for me.

[NOTE]
====
. Meaning “My Pleasantness.”
. Meaning “Bitter.”
. “The Almighty.” Heb., Shad·daiʹ; Syr., ʼEl·Shad·dai, “God Almighty”; Lat., O·mniʹpo·tens. See Re 1:8 ftn, “Almighty.”
====

[[v8-1-21]]

^<<v8-1-21,21>>^ I was full when I went, and it is empty-handed that Jehovah has made me return. Why should YOU call me Naʹo·mi, when it is Jehovah that has humiliated me and the Almighty that has caused me calamity?”

[[v8-1-22]]

^<<v8-1-22,22>>^ Thus Naʹo·mi made her return, Ruth the Moʹab·ite woman, her daughter-in-law, being with her when returning from the fields of Moʹab; and they came to Bethʹle·hem at the commencement of barley harvest.

'''

xref:007-judges/007-judges-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-ruth/008-ruth-002.adoc#v8-2-0[Próximo Capítulo &#62;]