include::./index.adoc[]

[[v48-5-0]]
=== To the Galatians, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-5-1]]

^<<v48-5-1,1>>^ For such freedom^&#42;1^ Christ set us free. Therefore stand fast, and do not let yourselves be confined again in a yoke of slavery.

[NOTE]
====
. Or, “With her freedom.” Gr., Tei e·leu·the·riʹai.
====

[[v48-5-2]]

^<<v48-5-2,2>>^ See! I, Paul, am telling YOU that if YOU become circumcised, Christ will be of no benefit to YOU.

[[v48-5-3]]

^<<v48-5-3,3>>^ Moreover, I bear witness again to every man getting circumcised that he is under obligation to perform the whole Law.

[[v48-5-4]]

^<<v48-5-4,4>>^ YOU are parted from Christ, whoever YOU are that try to be declared righteous by means of law; YOU have fallen away from his undeserved kindness.

[[v48-5-5]]

^<<v48-5-5,5>>^ For our part we by spirit are eagerly waiting for the hoped-for righteousness^&#42;1^ as a result of faith.

[NOTE]
====
. Lit., “hope of righteousness.”
====

[[v48-5-6]]

^<<v48-5-6,6>>^ For as regards Christ Jesus^&#42;1^ neither circumcision is of any value nor is uncircumcision, but faith operating through love &#91;is&#93;.

[NOTE]
====
. “Jesus.” B omits.
====

[[v48-5-7]]

^<<v48-5-7,7>>^ YOU were running well. Who hindered YOU from keeping on obeying the truth?

[[v48-5-8]]

^<<v48-5-8,8>>^ This sort of persuasion is not from the One calling YOU.

[[v48-5-9]]

^<<v48-5-9,9>>^ A little leaven ferments the whole lump.

[[v48-5-10]]

^<<v48-5-10,10>>^ I am confident about YOU who are in union with &#91;the&#93; Lord^&#42;1^ that YOU will not come to think otherwise; but the one who is causing YOU trouble will bear &#91;his&#93; judgment, no matter who he may be.

[NOTE]
====
. “I am confident in Jehovah concerning you,” J7,​8.
====

[[v48-5-11]]

^<<v48-5-11,11>>^ As for me, brothers, if I am still preaching circumcision, why am I still being persecuted? Then, indeed, the stumbling block^&#42;1^ of the torture stake^&#42;2^ has been abolished.

[NOTE]
====
. Or, “the offense.” Lit., “the fall-causer.” Gr., to skanʹda·lon; Lat., scanʹda·lum.
. See App 5C.
====

[[v48-5-12]]

^<<v48-5-12,12>>^ I wish the men who are trying to overturn YOU would even get themselves emasculated.^&#42;1^

[NOTE]
====
. “Would even get themselves emasculated,” P46אABD; J7,​8, “would even be cut off from before the eyes of Jehovah.”
====

[[v48-5-13]]

^<<v48-5-13,13>>^ YOU were, of course, called for freedom, brothers; only do not use this freedom as an inducement for the flesh, but through love slave for one another.

[[v48-5-14]]

^<<v48-5-14,14>>^ For the entire Law stands fulfilled in one saying, namely: “You must^&#42;1^ love your neighbor as yourself.”

[NOTE]
====
. Or, “shall.”
====

[[v48-5-15]]

^<<v48-5-15,15>>^ If, though, YOU keep on biting and devouring one another, look out that YOU do not get annihilated by one another.

[[v48-5-16]]

^<<v48-5-16,16>>^ But I say, Keep walking by spirit and YOU will carry out no fleshly desire at all.

[[v48-5-17]]

^<<v48-5-17,17>>^ For the flesh is against the spirit in its desire, and the spirit against the flesh; for these are opposed to each other, so that the very things that YOU would like to do YOU do not do.

[[v48-5-18]]

^<<v48-5-18,18>>^ Furthermore, if YOU are being led by spirit, YOU are not under law.

[[v48-5-19]]

^<<v48-5-19,19>>^ Now the works of the flesh are manifest, and they are fornication,^&#42;1^ uncleanness,^&#42;2^ loose conduct,^&#42;3^

[NOTE]
====
. See App 5A.
. Or, “filthiness; depravity; lewdness.” Gr., a·ka·thar·siʹa; J17,​22(Heb.), tum·ʼahʹ. See Eze 22:15 ftn, “Uncleanness.”
. Or, “licentiousness; wantonness; shameless conduct.” Gr., a·selʹgei·a; Vgc(Lat.), im·pu·di·ciʹti·a; J18,​22(Heb.), zim·mahʹ. See Pr 10:23 ftn, “Conduct.”
====

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatry, practice of spiritism,^&#42;1^ enmities, strife, jealousy, fits of anger, contentions, divisions, sects,^&#42;2^

[NOTE]
====
. Or, “druggery.” Gr., phar·ma·kiʹa. See Re 21:8 ftn, “Spiritism.”
. “Sects.” Gr., hai·reʹseis; Lat., secʹtae.
====

[[v48-5-21]]

^<<v48-5-21,21>>^ envies, drunken bouts, revelries, and things like these. As to these things I am forewarning YOU, the same way as I did forewarn YOU, that those who practice such things will not inherit God’s kingdom.

[[v48-5-22]]

^<<v48-5-22,22>>^ On the other hand, the fruitage of the spirit is love, joy, peace, long-suffering, kindness, goodness, faith,

[[v48-5-23]]

^<<v48-5-23,23>>^ mildness, self-control. Against such things there is no law.

[[v48-5-24]]

^<<v48-5-24,24>>^ Moreover, those who belong to Christ Jesus impaled^&#42;1^ the flesh together with its passions and desires.

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v48-5-25]]

^<<v48-5-25,25>>^ If we are living by spirit, let us go on walking orderly also by spirit.

[[v48-5-26]]

^<<v48-5-26,26>>^ Let us not become egotistical, stirring up competition with one another,^&#42;1^ envying one another.

[NOTE]
====
. Or, “forcing one another to a showdown.”
====

'''

xref:048-galatians/048-galatians-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatians/048-galatians-006.adoc#v48-6-0[Próximo Capítulo &#62;]