include::./index.adoc[]

[[v48-4-0]]
=== To the Galatians, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-4-1]]

^<<v48-4-1,1>>^ Now I say that as long as the heir is a babe he does not differ at all from a slave, lord of all things though he is,

[[v48-4-2]]

^<<v48-4-2,2>>^ but he is under men in charge and under stewards^&#42;1^ until the day his father appointed beforehand.

[NOTE]
====
. Or, “house managers.”
====

[[v48-4-3]]

^<<v48-4-3,3>>^ Likewise we also, when we were babes, continued enslaved by the elementary things belonging to the world.

[[v48-4-4]]

^<<v48-4-4,4>>^ But when the full limit of the time arrived, God sent forth his Son, who came to be out of a woman and who came to be under law,

[[v48-4-5]]

^<<v48-4-5,5>>^ that he might release by purchase those under law, that we, in turn, might receive the adoption as sons.

[[v48-4-6]]

^<<v48-4-6,6>>^ Now because YOU are sons, God has sent forth the spirit of his Son into our hearts and it cries out: “Abba,^&#42;1^ Father!”

[NOTE]
====
. “Abba,” an Aram. word meaning “the father,” or, “O Father!”
====

[[v48-4-7]]

^<<v48-4-7,7>>^ So, then, you are no longer a slave but a son; and if a son, also an heir through God.

[[v48-4-8]]

^<<v48-4-8,8>>^ Nevertheless, when YOU did not know God, then it was that YOU slaved for those who by nature are not gods.

[[v48-4-9]]

^<<v48-4-9,9>>^ But now that YOU have come to know God, or rather now that YOU have come to be known by God, how is it that YOU are turning back again to the weak and beggarly elementary things and want to slave for them over again?

[[v48-4-10]]

^<<v48-4-10,10>>^ YOU are scrupulously observing days and months and seasons^&#42;1^ and years.

[NOTE]
====
. Or, “appointed times.” Gr., kai·rousʹ.
====

[[v48-4-11]]

^<<v48-4-11,11>>^ I fear for YOU, that somehow I have toiled to no purpose respecting YOU.

[[v48-4-12]]

^<<v48-4-12,12>>^ Brothers, I beg YOU, Become as I am, because I used to be also as YOU are. YOU did me no wrong.

[[v48-4-13]]

^<<v48-4-13,13>>^ But YOU know that it was through a sickness of my flesh I declared the good news to YOU the first time.

[[v48-4-14]]

^<<v48-4-14,14>>^ And what was a trial^&#42;1^ to YOU in my flesh, YOU did not treat with contempt or spit at in disgust; but YOU received me like an angel of God, like Christ Jesus.

[NOTE]
====
. Or, “temptation.” Lit., “testing.”
====

[[v48-4-15]]

^<<v48-4-15,15>>^ Where, then, is that happiness YOU had? For I bear YOU witness that, if it had been possible, YOU would have gouged out YOUR eyes and given them to me.

[[v48-4-16]]

^<<v48-4-16,16>>^ Well, then, have I become YOUR enemy because I tell YOU the truth?

[[v48-4-17]]

^<<v48-4-17,17>>^ They zealously seek YOU, not in a fine way, but they want to shut YOU off &#91;from me&#93;, that YOU may zealously seek them.

[[v48-4-18]]

^<<v48-4-18,18>>^ However, it is fine for YOU to be zealously sought for in a fine cause at all times, and not only when I am present with YOU,

[[v48-4-19]]

^<<v48-4-19,19>>^ my little children, with whom I am again in childbirth pains until Christ is formed in YOU.

[[v48-4-20]]

^<<v48-4-20,20>>^ But I could wish to be present with YOU just now and to speak in a different way,^&#42;1^ because I am perplexed over YOU.

[NOTE]
====
. Lit., “and to alter my voice.”
====

[[v48-4-21]]

^<<v48-4-21,21>>^ Tell me, YOU who want to be under law, Do YOU not hear the Law?

[[v48-4-22]]

^<<v48-4-22,22>>^ For example, it is written that Abraham acquired two sons, one by the servant girl and one by the free woman;

[[v48-4-23]]

^<<v48-4-23,23>>^ but the one by the servant girl was actually born in the manner of flesh, the other by the free woman through a promise.

[[v48-4-24]]

^<<v48-4-24,24>>^ These things stand as a symbolic drama;^&#42;1^ for these &#91;women&#93; mean two covenants, the one from Mount Siʹnai, which brings forth children for slavery, and which is Haʹgar.

[NOTE]
====
. Or, “as an allegory.” Gr., al·le·go·rouʹme·na; Lat., per al·le·goʹri·am.
====

[[v48-4-25]]

^<<v48-4-25,25>>^ Now this Haʹgar means Siʹnai, a mountain in Arabia, and she corresponds with the Jerusalem today, for she is in slavery with her children.

[[v48-4-26]]

^<<v48-4-26,26>>^ But the Jerusalem above is free, and she is our mother.

[[v48-4-27]]

^<<v48-4-27,27>>^ For it is written: “Be glad, you barren woman who does not give birth; break out and cry aloud, you woman who does not have childbirth pains; for the children of the desolate woman are more numerous than &#91;those&#93; of her who has the husband.”

[[v48-4-28]]

^<<v48-4-28,28>>^ Now we, brothers, are children belonging to the promise the same as Isaac was.

[[v48-4-29]]

^<<v48-4-29,29>>^ But just as then the one born in the manner of flesh began persecuting the one born in the manner of spirit, so also now.

[[v48-4-30]]

^<<v48-4-30,30>>^ Nevertheless, what does the Scripture say? “Drive out the servant girl and her son, for by no means shall the son of the servant girl be an heir with the son of the free woman.”

[[v48-4-31]]

^<<v48-4-31,31>>^ Wherefore, brothers, we are children, not of a servant girl, but of the free woman.

'''

xref:048-galatians/048-galatians-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatians/048-galatians-005.adoc#v48-5-0[Próximo Capítulo &#62;]