include::./index.adoc[]

[[v48-3-0]]
=== To the Galatians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-3-1]]

^<<v48-3-1,1>>^ O senseless Ga·laʹtians, who is it that brought YOU under evil influence, YOU before whose eyes Jesus Christ was openly portrayed impaled?

[[v48-3-2]]

^<<v48-3-2,2>>^ This alone I want to learn from YOU: Did YOU receive the spirit due to works of law or due to a hearing by faith?^&#42;1^

[NOTE]
====
. Or, “due to a report of faith.”
====

[[v48-3-3]]

^<<v48-3-3,3>>^ Are YOU so senseless? After starting in spirit are YOU now being completed in flesh?

[[v48-3-4]]

^<<v48-3-4,4>>^ Did YOU undergo so many sufferings to no purpose? If it really was to no purpose.

[[v48-3-5]]

^<<v48-3-5,5>>^ He, therefore, who supplies YOU the spirit and performs powerful works^&#42;1^ among YOU, does he do it owing to works of law or owing to a hearing by faith?

[NOTE]
====
. Or, “performs miracles.”
====

[[v48-3-6]]

^<<v48-3-6,6>>^ Just as Abraham “put faith in Jehovah,^&#42;1^ and it was counted to him as righteousness.”

[NOTE]
====
. See App 1D.
====

[[v48-3-7]]

^<<v48-3-7,7>>^ Surely YOU know that those who adhere to faith are the ones who are sons of Abraham.

[[v48-3-8]]

^<<v48-3-8,8>>^ Now the Scripture, seeing in advance that God would declare people of the nations righteous due to faith, declared the good news beforehand to Abraham, namely: “By means of you all the nations will be blessed.”

[[v48-3-9]]

^<<v48-3-9,9>>^ Consequently those who adhere to faith are being blessed together with faithful^&#42;1^ Abraham.

[NOTE]
====
. Or, “believing.”
====

[[v48-3-10]]

^<<v48-3-10,10>>^ For all those who depend upon works of law are under a curse; for it is written: “Cursed is every one that does not continue in all the things written in the scroll of the Law in order to do them.”

[[v48-3-11]]

^<<v48-3-11,11>>^ Moreover, that by law no one is declared righteous with God is evident, because “the righteous one will live by reason of faith.”

[[v48-3-12]]

^<<v48-3-12,12>>^ Now the Law does not adhere to faith, but “he that does them shall live by means of them.”

[[v48-3-13]]

^<<v48-3-13,13>>^ Christ by purchase released us from the curse of the Law by becoming a curse instead of us, because it is written: “Accursed is every man hanged upon a stake.”^&#42;1^

[NOTE]
====
. Or, “tree.” Gr., xyʹlou. See App 5C.
====

[[v48-3-14]]

^<<v48-3-14,14>>^ The purpose was that the blessing of Abraham might come to be by means of Jesus Christ for the nations, that we might receive the promised spirit^&#42;1^ through our faith.

[NOTE]
====
. Lit., “the promise of the spirit.”
====

[[v48-3-15]]

^<<v48-3-15,15>>^ Brothers, I speak with a human illustration: A validated covenant, though it is a man’s, no one sets aside or attaches additions to it.

[[v48-3-16]]

^<<v48-3-16,16>>^ Now the promises were spoken to Abraham and to his seed. It^&#42;1^ says, not: “And to seeds,” as in the case of many such, but as in the case of one: “And to your seed,” who is Christ.

[NOTE]
====
. Or, “He.”
====

[[v48-3-17]]

^<<v48-3-17,17>>^ Further, I say this: As to the covenant previously validated by God, the Law that has come into being four hundred and thirty years later does not invalidate it, so as to abolish the promise.

[[v48-3-18]]

^<<v48-3-18,18>>^ For if the inheritance is due to law, it is no longer due to promise; whereas God has kindly given it to Abraham through a promise.

[[v48-3-19]]

^<<v48-3-19,19>>^ Why, then, the Law? It was added to make transgressions manifest,^&#42;1^ until the seed should arrive to whom the promise had been made; and it was transmitted through angels by the hand of a mediator.

[NOTE]
====
. Or, “added in favor of the transgressions.”
====

[[v48-3-20]]

^<<v48-3-20,20>>^ Now there is no mediator where only one person is concerned, but God^&#42;1^ is only one.

[NOTE]
====
. “God,” P46אABVgSyp; J7,​8, “Jehovah.”
====

[[v48-3-21]]

^<<v48-3-21,21>>^ Is the Law, therefore, against the promises of God?^&#42;1^ May that never happen! For if a law had been given that was able to give life, righteousness would actually have been by means of law.

[NOTE]
====
. “Of God,” אACDItVgSyh,pArm; P46B omit.
====

[[v48-3-22]]

^<<v48-3-22,22>>^ But the Scripture delivered up all things together to the custody of sin, that the promise resulting from faith toward Jesus Christ might be given to those exercising faith.

[[v48-3-23]]

^<<v48-3-23,23>>^ However, before the faith arrived, we were being guarded under law, being delivered up together into custody, looking to the faith that was destined to be revealed.

[[v48-3-24]]

^<<v48-3-24,24>>^ Consequently the Law has become our tutor^&#42;1^ leading to Christ, that we might be declared righteous due to faith.

[NOTE]
====
. Lit., “pedagogue.” Gr., pai·da·go·gosʹ; Lat., pe·da·goʹgus.
====

[[v48-3-25]]

^<<v48-3-25,25>>^ But now that the faith has arrived, we are no longer under a tutor.

[[v48-3-26]]

^<<v48-3-26,26>>^ YOU are all, in fact, sons of God through YOUR faith in Christ Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ For all of YOU who were baptized into Christ have put on Christ.^&#42;1^

[NOTE]
====
. Or, “have clothed (identified) yourselves with Christ.”
====

[[v48-3-28]]

^<<v48-3-28,28>>^ There is neither Jew nor Greek, there is neither slave nor freeman, there is neither male nor female; for YOU are all one &#91;person&#93; in union with Christ Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ Moreover, if YOU belong to Christ, YOU are really Abraham’s seed, heirs with reference to a promise.

'''

xref:048-galatians/048-galatians-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatians/048-galatians-004.adoc#v48-4-0[Próximo Capítulo &#62;]