include::./index.adoc[]

[[v48-1-0]]
=== To the Galatians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-1-1]]

^<<v48-1-1,1>>^ Paul, an apostle, neither from men nor through a man, but through Jesus Christ and God the Father, who raised him up from the dead,

[[v48-1-2]]

^<<v48-1-2,2>>^ and all the brothers with me, to the congregations of Ga·laʹti·a:^&#42;1^

[NOTE]
====
. The Roman province that occupied the central portion of what is now known as Asia Minor.
====

[[v48-1-3]]

^<<v48-1-3,3>>^ May YOU have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[[v48-1-4]]

^<<v48-1-4,4>>^ He gave himself for our sins that he might deliver us from the present wicked system of things^&#42;1^ according to the will of our God and Father,

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·lo; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v48-1-5]]

^<<v48-1-5,5>>^ to whom be the glory forever and ever. Amen.

[[v48-1-6]]

^<<v48-1-6,6>>^ I marvel that YOU are being so quickly removed from the One who called YOU with Christ’s undeserved kindness over to another sort of good news.

[[v48-1-7]]

^<<v48-1-7,7>>^ But it is not another; only there are certain ones who are causing YOU trouble and wanting to pervert the good news about the Christ.

[[v48-1-8]]

^<<v48-1-8,8>>^ However, even if we or an angel out of heaven were to declare to YOU as good news something beyond what we declared to YOU as good news, let him be accursed.^&#42;1^

[NOTE]
====
. Lit., “anath­e­ma,” that is, one devoted to destruction or accursed. See De 7:26 and De 13:17 ftns.
====

[[v48-1-9]]

^<<v48-1-9,9>>^ As we have said above, I also now say again, Whoever it is that is declaring to YOU as good news something beyond what YOU accepted, let him be accursed.

[[v48-1-10]]

^<<v48-1-10,10>>^ Is it, in fact, men I am now trying to persuade or God? Or am I seeking to please men? If I were yet pleasing men, I would not be Christ’s slave.

[[v48-1-11]]

^<<v48-1-11,11>>^ For I put YOU on notice, brothers, that the good news which was declared by me as good news is not something human;

[[v48-1-12]]

^<<v48-1-12,12>>^ for neither did I receive it from man, nor was I taught &#91;it&#93;, except through revelation^&#42;1^ by Jesus Christ.

[NOTE]
====
. Lit., “uncovering; disclosure.” Gr., a·po·ka·lyʹpse·os.
====

[[v48-1-13]]

^<<v48-1-13,13>>^ YOU, of course, heard about my conduct formerly in Juʹda·ism, that to the point of excess I kept on persecuting the congregation of God and devastating it,

[[v48-1-14]]

^<<v48-1-14,14>>^ and I was making greater progress in Juʹda·ism than many of my own age in my race, as I was far more zealous for the traditions of my fathers.

[[v48-1-15]]

^<<v48-1-15,15>>^ But when God, who separated me from my mother’s womb^&#42;1^ and called &#91;me&#93; through his undeserved kindness, thought good

[NOTE]
====
. Lit., “having defined me off out of the cavity of my mother.”
====

[[v48-1-16]]

^<<v48-1-16,16>>^ to reveal his Son in connection with me, that I might declare the good news about him to the nations, I did not go at once into conference with flesh and blood.

[[v48-1-17]]

^<<v48-1-17,17>>^ Neither did I go up to Jerusalem to those who were apostles previous to me, but I went off into Arabia, and I came back again to Damascus.

[[v48-1-18]]

^<<v48-1-18,18>>^ Then three years later I went up to Jerusalem to visit^&#42;1^ Ceʹphas, and I stayed with him for fifteen days.

[NOTE]
====
. Lit., “to visit for inquiry.”
====

[[v48-1-19]]

^<<v48-1-19,19>>^ But I saw no one else of the apostles, only James the brother of the Lord.

[[v48-1-20]]

^<<v48-1-20,20>>^ Now as to the things I am writing YOU, look! in the sight of God, I am not lying.

[[v48-1-21]]

^<<v48-1-21,21>>^ After that I went into the regions of Syria and of Ci·liʹcia.

[[v48-1-22]]

^<<v48-1-22,22>>^ But I was unknown by face to the congregations of Ju·deʹa that were in union with Christ;

[[v48-1-23]]

^<<v48-1-23,23>>^ they only used to hear: “The man that formerly persecuted us is now declaring the good news about the faith which he formerly devastated.”

[[v48-1-24]]

^<<v48-1-24,24>>^ So they began glorifying God because of me.

'''

xref:047-2-corinthians/047-2-corinthians-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatians/048-galatians-002.adoc#v48-2-0[Próximo Capítulo &#62;]