include::./index.adoc[]

[[v48-6-0]]
=== To the Galatians, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-6-1]]

^<<v48-6-1,1>>^ Brothers, even though a man takes some false step^&#42;1^ before he is aware of it, YOU who have spiritual qualifications try to readjust^&#42;2^ such a man in a spirit of mildness, as you each keep an eye on yourself, for fear you also may be tempted.

[NOTE]
====
. Lit., “should be overtaken.”
. Or, “to restore to proper position; to bring into proper alignment.”
====

[[v48-6-2]]

^<<v48-6-2,2>>^ Go on carrying the burdens^&#42;1^ of one another, and thus fulfill the law of the Christ.

[NOTE]
====
. Or, “troublesome things.” Lit., “heavy things.” Gr., baʹre.
====

[[v48-6-3]]

^<<v48-6-3,3>>^ For if anyone thinks he is something when he is nothing, he is deceiving his own mind.

[[v48-6-4]]

^<<v48-6-4,4>>^ But let each one^&#42;1^ prove what his own work is, and then he will have cause for exultation in regard to himself alone, and not in comparison with the other person.

[NOTE]
====
. “Each one,” אACDVg; P46B, “him.”
====

[[v48-6-5]]

^<<v48-6-5,5>>^ For each one will carry his own load.^&#42;1^

[NOTE]
====
. “Load.” Gr., phor·tiʹon. Compare vs 2.
====

[[v48-6-6]]

^<<v48-6-6,6>>^ Moreover, let anyone who is being orally taught^&#42;1^ the word share in all good things with the one who gives such oral teaching.

[NOTE]
====
. Lit., “being sounded down to.” Gr., ka·te·khouʹme·nos; Lat., ca·te·ci·zaʹtur.
====

[[v48-6-7]]

^<<v48-6-7,7>>^ Do not be misled: God is not one to be mocked. For whatever a man is sowing, this he will also reap;

[[v48-6-8]]

^<<v48-6-8,8>>^ because he who is sowing with a view to his flesh will reap corruption from his flesh, but he who is sowing with a view to the spirit will reap everlasting life from the spirit.

[[v48-6-9]]

^<<v48-6-9,9>>^ So let us not give up in doing what is fine, for in due season we shall reap if we do not tire out.

[[v48-6-10]]

^<<v48-6-10,10>>^ Really, then, as long as we have time favorable for it, let us work what is good toward all, but especially toward those related to &#91;us&#93; in the faith.

[[v48-6-11]]

^<<v48-6-11,11>>^ SEE^&#42;1^ with what large letters^&#42;2^ I have written YOU with my own hand.

[NOTE]
====
. Or, “You see.”
. Or, “with what a long letter.”
====

[[v48-6-12]]

^<<v48-6-12,12>>^ All those who want to make a pleasing appearance in the flesh are the ones that try to compel YOU to get circumcised, only that they may not be persecuted for the torture stake^&#42;1^ of the Christ, Jesus.^&#42;2^

[NOTE]
====
. See App 5C.
. “Christ, Jesus,” P46B; אACDVgSyp, “Christ.”
====

[[v48-6-13]]

^<<v48-6-13,13>>^ For not even do those who are getting circumcised keep the Law themselves, but they want YOU to be circumcised that they may have cause for boasting in YOUR flesh.

[[v48-6-14]]

^<<v48-6-14,14>>^ Never may it occur that I should boast, except in the torture stake of our Lord Jesus Christ, through whom the world has been impaled to me and I to the world.

[[v48-6-15]]

^<<v48-6-15,15>>^ For neither is circumcision anything nor is uncircumcision, but a new creation &#91;is something&#93;.

[[v48-6-16]]

^<<v48-6-16,16>>^ And all those who will walk orderly by this rule of conduct,^&#42;1^ upon them be peace and mercy, even upon the Israel^&#42;2^ of God.

[NOTE]
====
. “By . . . rule of conduct.” Or, “by . . . ­canon (rule).” Lit., “to the (measuring) reed.” Gr., toi ka·noʹni; Lat., reʹgu·lam, “regulation”; J18(Heb.), qenehʹ ham·mid·dahʹ, “the reed of measure.” Compare Eze 40:5 ftn, “Reed.”
. Meaning “God Contends; Contender (Perseverer) With God.”
====

[[v48-6-17]]

^<<v48-6-17,17>>^ Henceforth^&#42;1^ let no one be making trouble for me, for I am carrying on my body the brand marks &#91;of a slave&#93; of Jesus.

[NOTE]
====
. Or, “Finally.”
====

[[v48-6-18]]

^<<v48-6-18,18>>^ The undeserved kindness of our^&#42;1^ Lord Jesus Christ &#91;be&#93; with the spirit YOU &#91;show&#93;, brothers. Amen.

[NOTE]
====
. “Our,” P46ABCDVgSyp; א, “the.”
====

'''

xref:048-galatians/048-galatians-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-ephesians/049-ephesians-001.adoc#v49-1-0[Próximo Capítulo &#62;]