include::./index.adoc[]

[[v48-2-0]]
=== To the Galatians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v48-2-1]]

^<<v48-2-1,1>>^ Then after fourteen years I again went up to Jerusalem with Barʹna·bas, taking also Titus along with me.

[[v48-2-2]]

^<<v48-2-2,2>>^ But I went up as a result of a revelation. And I laid before them the good news which I am preaching^&#42;1^ among the nations, privately, however, before those who were outstanding men, for fear that somehow I was running or had run in vain.

[NOTE]
====
. Or, “I am heralding.” Gr., ke·rysʹso; Lat., praeʹdi·co. Compare Da 5:29 ftn, “Heralded.”
====

[[v48-2-3]]

^<<v48-2-3,3>>^ Nevertheless, not even Titus, who was with me, was compelled to be circumcised, although he was a Greek.

[[v48-2-4]]

^<<v48-2-4,4>>^ But because of the false brothers brought in quietly, who sneaked in to spy upon our freedom which we have in union with Christ Jesus, that they might completely enslave us—

[[v48-2-5]]

^<<v48-2-5,5>>^ to these we did not yield by way of submission, no, not for an hour, in order that the truth of the good news might continue with YOU.

[[v48-2-6]]

^<<v48-2-6,6>>^ But on the part of those who seemed to be something—whatever sort of men they formerly were makes no difference to me—God^&#42;1^ does not go by a man’s outward appearance—to me, in fact, those outstanding men imparted nothing new.

[NOTE]
====
. “God,” P46אABCD; J7,​8, “Jehovah.”
====

[[v48-2-7]]

^<<v48-2-7,7>>^ But, on the contrary, when they saw that I had entrusted to me the good news for those who are uncircumcised,^&#42;1^ just as Peter &#91;had it&#93; for those who are circumcised^&#42;2^—

[NOTE]
====
. Lit., “of the uncircumcision.”
. Lit., “of the circumcision.”
====

[[v48-2-8]]

^<<v48-2-8,8>>^ for He who gave Peter powers necessary for an apostleship to those who are circumcised gave powers also to me for those who are of the nations;

[[v48-2-9]]

^<<v48-2-9,9>>^ yes, when they came to know the undeserved kindness that was given me, James and Ceʹphas and John, the ones who seemed to be pillars, gave me and Barʹna·bas the right hand of sharing together, that we should go to the nations, but they to those who are circumcised.

[[v48-2-10]]

^<<v48-2-10,10>>^ Only we should keep the poor in mind. This very thing I have also earnestly endeavored to do.

[[v48-2-11]]

^<<v48-2-11,11>>^ However, when Ceʹphas came to Antioch, I resisted^&#42;1^ him face to face, because he stood condemned.

[NOTE]
====
. Lit., “I stood against.”
====

[[v48-2-12]]

^<<v48-2-12,12>>^ For before the arrival of certain men from James, he used to eat with people of the nations; but when they arrived, he went withdrawing and separating himself, in fear of those of the circumcised class.^&#42;1^

[NOTE]
====
. Lit., “the (ones) out of circumcision.”
====

[[v48-2-13]]

^<<v48-2-13,13>>^ The rest of the Jews also joined him in putting on this pretense, so that even Barʹna·bas was led along with them in their pretense.^&#42;1^

[NOTE]
====
. Lit., “hypocrisy.” Gr., hy·po·kriʹsei.
====

[[v48-2-14]]

^<<v48-2-14,14>>^ But when I saw they were not walking straight according to the truth of the good news, I said to Ceʹphas before them all: “If you, though you are a Jew, live as the nations do, and not as Jews do, how is it that you are compelling people of the nations to live according to Jewish practice?”

[[v48-2-15]]

^<<v48-2-15,15>>^ We who are Jews by nature, and not sinners from the nations,

[[v48-2-16]]

^<<v48-2-16,16>>^ knowing as we do that a man is declared righteous,^&#42;1^ not due to works of law, but only through faith toward Christ Jesus, even we have put our faith in Christ Jesus, that we may be declared righteous due to faith toward Christ, and not due to works of law, because due to works of law no flesh will be declared righteous.

[NOTE]
====
. Lit., “is being justified.” Gr., di·kai·ouʹtai.
====

[[v48-2-17]]

^<<v48-2-17,17>>^ Now if we, in seeking to be declared righteous by means of Christ, have also ourselves been found sinners, is Christ in reality sin’s minister? May that never happen!

[[v48-2-18]]

^<<v48-2-18,18>>^ For if the very things that I once threw down I build up again, I demonstrate myself to be a transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ As for me, through law I died toward law, that I might become alive toward God.

[[v48-2-20]]

^<<v48-2-20,20>>^ I am impaled^&#42;1^ along with Christ. It is no longer I that live, but it is Christ that is living in union with me. Indeed, the life that I now live in flesh I live by the faith that is toward the Son of God, who loved me and handed himself over for me.

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v48-2-21]]

^<<v48-2-21,21>>^ I do not shove aside the undeserved kindness of God; for if righteousness is through law, Christ actually died for nothing.

'''

xref:048-galatians/048-galatians-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatians/048-galatians-003.adoc#v48-3-0[Próximo Capítulo &#62;]