include::./index.adoc[]

[[v1-35-0]]
=== Genesis, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-35-1]]

^<<v1-35-1,1>>^ After that God said to Jacob: “Rise, go up to Bethʹel and dwell there, and make an altar there to the &#91;true&#93; God who appeared to you when you were running away from Eʹsau your brother.”

[[v1-35-2]]

^<<v1-35-2,2>>^ Then Jacob said to his household and to all who were with him: “Put away the foreign gods^&#42;1^ that are in the midst of YOU and cleanse yourselves and change YOUR mantles,

[NOTE]
====
. Lit., “gods of.” Heb., ʼelo·hehʹ, pl. of ʼelohʹah, indicating a plurality of gods.
====

[[v1-35-3]]

^<<v1-35-3,3>>^ and let us rise and go up to Bethʹel. And there I shall make an altar to the &#91;true&#93; God who answered me in the day of my distress in that he proved to be with me in the way that I have gone.”

[[v1-35-4]]

^<<v1-35-4,4>>^ So they gave Jacob all the foreign gods that were in their hands and the earrings that were in their ears, and Jacob hid them under the big tree that was close by Sheʹchem.

[[v1-35-5]]

^<<v1-35-5,5>>^ After that they pulled away, and the terror of God came to be upon the cities that were round about them, so that they did not chase after the sons of Jacob.

[[v1-35-6]]

^<<v1-35-6,6>>^ Eventually Jacob came to Luz, which is in the land of Caʹnaan, that is to say, Bethʹel, he and all the people who were with him.

[[v1-35-7]]

^<<v1-35-7,7>>^ Then he built an altar there and began to call the place El-bethʹel,^&#42;1^ because there the &#91;true&#93; God had revealed himself to him at the time of his running away from his brother.

[NOTE]
====
. Meaning “The God of Bethel.”
====

[[v1-35-8]]

^<<v1-35-8,8>>^ Later Debʹo·rah the nursing woman of Re·bekʹah died and was buried at the foot of Bethʹel under a massive tree. Hence he called its name Alʹlon-bacʹuth.^&#42;1^

[NOTE]
====
. Meaning “Massive Tree of Weeping.”
====

[[v1-35-9]]

^<<v1-35-9,9>>^ God now appeared to Jacob once again during his coming from Padʹdan-aʹram and blessed him.

[[v1-35-10]]

^<<v1-35-10,10>>^ And God went on to say to him: “Your name is Jacob. No longer is your name to be called Jacob, but Israel will your name become.” And he began to call his name Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ And God said further to him: “I am God Almighty.^&#42;1^ Be fruitful and become many. Nations^&#42;2^ and a congregation of nations will proceed out of you, and kings will come out of your loins.

[NOTE]
====
. See 17:1 ftn.
. “Nations,” LXXVg; M, “A nation.”
====

[[v1-35-12]]

^<<v1-35-12,12>>^ As for the land that I have given to Abraham and to Isaac, to you I shall give it, and to your seed^&#42;1^ after you I shall give the land.”

[NOTE]
====
. Or, “offspring; posterity.”
====

[[v1-35-13]]

^<<v1-35-13,13>>^ After that God went up from above him at the place where he had spoken with him.

[[v1-35-14]]

^<<v1-35-14,14>>^ Consequently Jacob stationed a pillar in the place where he had spoken with him, a pillar of stone, and he poured a drink offering upon it and poured oil upon it.

[[v1-35-15]]

^<<v1-35-15,15>>^ And Jacob continued to call the name of the place where God had spoken with him Bethʹel.

[[v1-35-16]]

^<<v1-35-16,16>>^ Then they pulled away from Bethʹel. And while there was yet a good stretch of land before coming to Ephʹrath, Rachel proceeded to give birth, and it was going hard with her in making the delivery.

[[v1-35-17]]

^<<v1-35-17,17>>^ But so it was that while she had difficulty in making the delivery the midwife said to her: “Do not be afraid, for you will have this son also.”

[[v1-35-18]]

^<<v1-35-18,18>>^ And the result was that as her soul^&#42;1^ was going out (because she died) she called his name Ben-oʹni;^&#42;2^ but his father called him Benjamin.^&#42;3^

[NOTE]
====
. “Her soul (life).” Heb., naph·shahʹ; Gr., psy·khenʹ.
. Meaning “Son of My Sorrow.”
. Meaning “Son of the Right Hand.” Heb., Vin·ya·minʹ.
====

[[v1-35-19]]

^<<v1-35-19,19>>^ Thus Rachel died and was buried on the way to Ephʹrath, that is to say, Bethʹle·hem.

[[v1-35-20]]

^<<v1-35-20,20>>^ Hence Jacob stationed a pillar over her grave. This is the pillar of Rachel’s grave down to this day.

[[v1-35-21]]

^<<v1-35-21,21>>^ After that Israel pulled away and pitched his tent a distance beyond the tower of Eʹder.

[[v1-35-22]]

^<<v1-35-22,22>>^ And it came about while Israel was tabernacling in that land that once Reuʹben went and lay down with Bilʹhah his father’s concubine, and Israel got to hear of it.
So there came to be twelve sons of Jacob.

[[v1-35-23]]

^<<v1-35-23,23>>^ The sons by Leʹah were Jacob’s firstborn Reuʹben and Simʹe·on and Leʹvi and Judah and Isʹsa·char and Zebʹu·lun.

[[v1-35-24]]

^<<v1-35-24,24>>^ The sons by Rachel were Joseph and Benjamin.

[[v1-35-25]]

^<<v1-35-25,25>>^ And the sons by Bilʹhah, Rachel’s maidservant, were Dan and Naphʹta·li.

[[v1-35-26]]

^<<v1-35-26,26>>^ And the sons by Zilʹpah, Leʹah’s maidservant, were Gad and Ashʹer. These are Jacob’s sons who were born to him in Padʹdan-aʹram.

[[v1-35-27]]

^<<v1-35-27,27>>^ At length Jacob came to Isaac his father to Mamʹre, to Kirʹi·ath-arʹba, that is to say, Heʹbron, where Abraham and also Isaac had resided as aliens.

[[v1-35-28]]

^<<v1-35-28,28>>^ And the days of Isaac came to be a hundred and eighty years.

[[v1-35-29]]

^<<v1-35-29,29>>^ After that Isaac expired and died and was gathered to his people, old and satisfied with days,^&#42;1^ and Eʹsau and Jacob his sons buried him.

[NOTE]
====
. Or, “full of (sated with) days,” MLXXVg.
====

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]