include::./index.adoc[]

[[v1-36-0]]
=== Genesis, 36
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-36-1]]

^<<v1-36-1,1>>^ And this is the history of Eʹsau, that is to say, Eʹdom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Eʹsau took his wives from the daughters of Caʹnaan: Aʹdah the daughter of Eʹlon the Hitʹtite and O·hol·i·baʹmah the daughter of Aʹnah, the granddaughter^&#42;1^ of Zibʹe·on the Hiʹvite,

[NOTE]
====
. Lit., “daughter,” M; SamLXXSy, “son.” Compare vs 24.
====

[[v1-36-3]]

^<<v1-36-3,3>>^ and Basʹe·math, Ishʹma·el’s daughter, the sister of Ne·baʹioth.

[[v1-36-4]]

^<<v1-36-4,4>>^ And Aʹdah proceeded to bear Elʹi·phaz to Eʹsau, and Basʹe·math bore Reuʹel,

[[v1-36-5]]

^<<v1-36-5,5>>^ and O·hol·i·baʹmah bore Jeʹush and Jaʹlam and Koʹrah.
These are the sons of Eʹsau who were born to him in the land of Caʹnaan.

[[v1-36-6]]

^<<v1-36-6,6>>^ After that Eʹsau took his wives and his sons and his daughters and all the souls of his house and his herd and all his other beasts and all his wealth, which he had accumulated in the land of Caʹnaan, and went to a land^&#42;1^ away from Jacob his brother,

[NOTE]
====
. “A land,” M; Sy, “the land of Seir.”
====

[[v1-36-7]]

^<<v1-36-7,7>>^ because their goods had become too great for them to dwell together and the land of their alien residences was not able to sustain them as a result of their herds.

[[v1-36-8]]

^<<v1-36-8,8>>^ So Eʹsau took up dwelling in the mountainous region of Seʹir. Eʹsau is Eʹdom.

[[v1-36-9]]

^<<v1-36-9,9>>^ And this is the history of Eʹsau the father of Eʹdom in the mountainous region of Seʹir.

[[v1-36-10]]

^<<v1-36-10,10>>^ These are the names of the sons of Eʹsau: Elʹi·phaz the son of Aʹdah, Eʹsau’s wife; Reuʹel the son of Basʹe·math, Eʹsau’s wife.

[[v1-36-11]]

^<<v1-36-11,11>>^ And the sons of Elʹi·phaz came to be Teʹman, Oʹmar, Zeʹpho and Gaʹtam and Keʹnaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ And Timʹna became the concubine of Elʹi·phaz, Eʹsau’s son. In time she bore to Elʹi·phaz Amʹa·lek. These are the sons of Aʹdah, Eʹsau’s wife.

[[v1-36-13]]

^<<v1-36-13,13>>^ These are the sons of Reuʹel: Naʹhath and Zeʹrah, Shamʹmah and Mizʹzah. These came to be the sons^&#42;1^ of Basʹe·math, Eʹsau’s wife.

[NOTE]
====
. Or, “grandsons.”
====

[[v1-36-14]]

^<<v1-36-14,14>>^ And these came to be the sons of O·hol·i·baʹmah the daughter of Aʹnah, the granddaughter of Zibʹe·on, Eʹsau’s wife, in that she bore to Eʹsau Jeʹush and Jaʹlam and Koʹrah.

[[v1-36-15]]

^<<v1-36-15,15>>^ These are the sheiks^&#42;1^ of the sons of Eʹsau: The sons of Elʹi·phaz, Eʹsau’s firstborn: Sheik Teʹman, sheik Oʹmar, sheik Zeʹpho, sheik Keʹnaz,

[NOTE]
====
. Or, “chiefs.” LXX, “chiefs; leaders; governors”; Vg, “leaders; dukes.” The Heb. word is ʼal·lu·phehʹ and is derived from ʼeʹleph, “thousand.” Hence ʼal·luphʹ basically means “leader of a thousand” and corresponds with the Gr. chiliarch. See Mr 6:21 ftn.
====

[[v1-36-16]]

^<<v1-36-16,16>>^ sheik Koʹrah,^&#42;1^ sheik Gaʹtam, sheik Amʹa·lek. These are the sheiks of Elʹi·phaz in the land of Eʹdom. These are the sons by Aʹdah.

[NOTE]
====
. “Sheik Korah,” MLXXSyVg; Sam omits. Vss 5, 14, 18 show he was Esau’s (not Eliphaz’) son by Oholibamah.
====

[[v1-36-17]]

^<<v1-36-17,17>>^ These are the sons of Reuʹel, Eʹsau’s son: Sheik Naʹhath, sheik Zeʹrah, sheik Shamʹmah, sheik Mizʹzah. These are the sheiks of Reuʹel in the land of Eʹdom. These are the sons by Basʹe·math, Eʹsau’s wife.

[[v1-36-18]]

^<<v1-36-18,18>>^ Finally these are the sons of O·hol·i·baʹmah, Eʹsau’s wife: Sheik Jeʹush, sheik Jaʹlam, sheik Koʹrah. These are the sheiks of O·hol·i·baʹmah the daughter of Aʹnah, Eʹsau’s wife.

[[v1-36-19]]

^<<v1-36-19,19>>^ These are the sons of Eʹsau, and these are their sheiks. He is Eʹdom.

[[v1-36-20]]

^<<v1-36-20,20>>^ These are the sons of Seʹir the Horʹite, the inhabitants of the land: Loʹtan and Shoʹbal and Zibʹe·on and Aʹnah

[[v1-36-21]]

^<<v1-36-21,21>>^ and Diʹshon and Eʹzer and Diʹshan. These are the sheiks of the Horʹite, the sons of Seʹir, in the land of Eʹdom.

[[v1-36-22]]

^<<v1-36-22,22>>^ And the sons of Loʹtan came to be Hoʹri and Heʹmam; and Loʹtan’s sister was Timʹna.

[[v1-36-23]]

^<<v1-36-23,23>>^ And these are the sons of Shoʹbal: Alʹvan and Manʹa·hath and Eʹbal, Sheʹpho and Oʹnam.

[[v1-36-24]]

^<<v1-36-24,24>>^ And these are the sons of Zibʹe·on: Aʹiah and Aʹnah. This is the Aʹnah who found the hot springs^&#42;1^ in the wilderness while he was tending the asses for Zibʹe·on his father.

[NOTE]
====
. “The hot springs.” Heb., hai·ye·mimʹ; Lat., aʹquas caʹli·das, “hot waters.”
====

[[v1-36-25]]

^<<v1-36-25,25>>^ And these are the children of Aʹnah: Diʹshon and O·hol·i·baʹmah the daughter of Aʹnah.

[[v1-36-26]]

^<<v1-36-26,26>>^ And these are the sons of Diʹshon:^&#42;1^ Hemʹdan and Eshʹban and Ithʹran and Cheʹran.

[NOTE]
====
. “Dishon,” SamLXXSyVgc and 1Ch 1:41; MVg, “Dishan.”
====

[[v1-36-27]]

^<<v1-36-27,27>>^ These are the sons of Eʹzer: Bilʹhan and Zaʹa·van and Aʹkan.

[[v1-36-28]]

^<<v1-36-28,28>>^ These are the sons of Diʹshan: Uz and Aʹran.

[[v1-36-29]]

^<<v1-36-29,29>>^ These are the sheiks of the Horʹite: Sheik Loʹtan, sheik Shoʹbal, sheik Zibʹe·on, sheik Aʹnah,

[[v1-36-30]]

^<<v1-36-30,30>>^ sheik Diʹshon, sheik Eʹzer, sheik Diʹshan. These are the sheiks of the Horʹite according to their sheiks in the land of Seʹir.

[[v1-36-31]]

^<<v1-36-31,31>>^ Now these are the kings who reigned in the land of Eʹdom before any king reigned over the sons of Israel.

[[v1-36-32]]

^<<v1-36-32,32>>^ And Beʹla son of Beʹor proceeded to reign in Eʹdom, and the name of his city was Dinʹha·bah.

[[v1-36-33]]

^<<v1-36-33,33>>^ When Beʹla died, Joʹbab son of Zeʹrah from Bozʹrah began to reign instead of him.

[[v1-36-34]]

^<<v1-36-34,34>>^ When Joʹbab died, Huʹsham from the land of the Teʹman·ites began to reign instead of him.

[[v1-36-35]]

^<<v1-36-35,35>>^ When Huʹsham died, Haʹdad son of Beʹdad, who defeated the Midʹi·an·ites in the field of Moʹab, began to reign instead of him, and the name of his city was Aʹvith.

[[v1-36-36]]

^<<v1-36-36,36>>^ When Haʹdad died, Samʹlah from Mas·reʹkah began to reign instead of him.

[[v1-36-37]]

^<<v1-36-37,37>>^ When Samʹlah died, Shaʹul from Re·hoʹboth by the River began to reign instead of him.

[[v1-36-38]]

^<<v1-36-38,38>>^ When Shaʹul died, Baʹal-haʹnan son of Achʹbor began to reign instead of him.

[[v1-36-39]]

^<<v1-36-39,39>>^ When Baʹal-haʹnan son of Achʹbor died, Haʹdar began to reign instead of him; and the name of his city was Paʹu, and the name of his wife was Me·hetʹa·bel the daughter of Maʹtred the daughter of Meʹza·hab.

[[v1-36-40]]

^<<v1-36-40,40>>^ So these are the names of the sheiks of Eʹsau according to their families, according to their places, by their names: Sheik Timʹna, sheik Alʹvah, sheik Jeʹtheth,

[[v1-36-41]]

^<<v1-36-41,41>>^ sheik O·hol·i·baʹmah, sheik Eʹlah, sheik Piʹnon,

[[v1-36-42]]

^<<v1-36-42,42>>^ sheik Keʹnaz, sheik Teʹman, sheik Mibʹzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ sheik Magʹdi·el, sheik Iʹram. These are the sheiks of Eʹdom according to their dwellings in the land of their possession. This is Eʹsau the father of Eʹdom.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]