include::./index.adoc[]

[[v1-44-0]]
=== Genesis, 44
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-44-1]]

^<<v1-44-1,1>>^ Later on he commanded the man who was over his house, saying: “Fill the bags of the men with food to the extent they are able to carry it and place the money of each one in the mouth of his bag.

[[v1-44-2]]

^<<v1-44-2,2>>^ But you must place my cup, the silver cup, in the mouth of the bag of the youngest and the money for his cereals.” So he did according to the word of Joseph which he had spoken.

[[v1-44-3]]

^<<v1-44-3,3>>^ The morning had become light when the men were sent away, both they and their asses.

[[v1-44-4]]

^<<v1-44-4,4>>^ They went out of the city. They had not gone far when Joseph said to the man who was over his house: “Get up! Chase after the men and be certain to overtake them and to say to them, ‘Why have YOU repaid bad for good?

[[v1-44-5]]

^<<v1-44-5,5>>^ Is not this the thing that my master drinks from and by means of which he expertly reads omens? It is a bad deed YOU have committed.’”

[[v1-44-6]]

^<<v1-44-6,6>>^ Eventually he overtook them and spoke these words to them.

[[v1-44-7]]

^<<v1-44-7,7>>^ But they said to him: “Why does my lord speak with such words as these? It is unthinkable that your servants should do anything like this.

[[v1-44-8]]

^<<v1-44-8,8>>^ Why, the money that we found in the mouth of our bags we brought back to you from the land of Caʹnaan. How, then, could we steal silver or gold from the house of your master?

[[v1-44-9]]

^<<v1-44-9,9>>^ Let the one of your slaves^&#42;1^ with whom it may be found die and let us ourselves also become slaves to my master.”

[NOTE]
====
. Or, “servants.”
====

[[v1-44-10]]

^<<v1-44-10,10>>^ So he said: “Let it be now exactly according to YOUR words. Thus the one with whom it may be found will become a slave to me, but YOU yourselves will be proved innocent.”

[[v1-44-11]]

^<<v1-44-11,11>>^ With that they quickly let down each one his bag to the earth and they opened each one his own bag.

[[v1-44-12]]

^<<v1-44-12,12>>^ And he went searching carefully. He started with the oldest and finished with the youngest. At last the cup was found in Benjamin’s bag.

[[v1-44-13]]

^<<v1-44-13,13>>^ Then they ripped their mantles apart and lifted each one his load back onto his ass and returned to the city.

[[v1-44-14]]

^<<v1-44-14,14>>^ And Judah and his brothers went on into Joseph’s house, and he was still there; and they proceeded to fall before him to the earth.

[[v1-44-15]]

^<<v1-44-15,15>>^ Joseph now said to them: “What sort of deed is this that YOU have done? Did YOU not know that such a man as I am can expertly read omens?”

[[v1-44-16]]

^<<v1-44-16,16>>^ At this Judah exclaimed: “What can we say to my master? What can we speak? And how can we prove ourselves righteous? The &#91;true&#93; God has found out the error of your slaves. Here we are slaves to my master, both we and the one in whose hand the cup was found!”

[[v1-44-17]]

^<<v1-44-17,17>>^ However, he said: “It is unthinkable for me to do this! The man in whose hand the cup was found is the one who will become a slave to me. As for the rest of YOU, go up in peace to YOUR father.”

[[v1-44-18]]

^<<v1-44-18,18>>^ Judah now came near to him and said: “I pray you, my master, please let your slave speak a word in the hearing of my master, and do not let your anger grow hot against your slave, because it is the same with you as with Pharʹaoh.^&#42;1^

[NOTE]
====
. Or, “you are like Pharaoh.”
====

[[v1-44-19]]

^<<v1-44-19,19>>^ My master^&#42;1^ asked his slaves, saying, ‘Do YOU have a father or a brother?’

[NOTE]
====
. Or, “My lord.”
====

[[v1-44-20]]

^<<v1-44-20,20>>^ So we said to my master, ‘We do have an aged father and a child of his old age, the youngest. But his brother is dead so that he alone is left of his mother, and his father does love him.’

[[v1-44-21]]

^<<v1-44-21,21>>^ After that you said to your slaves, ‘Bring him down to me that I may set my eye upon him.’

[[v1-44-22]]

^<<v1-44-22,22>>^ But we said to my master, ‘The boy is not able to leave his father. If he did leave his father, he would certainly die.’

[[v1-44-23]]

^<<v1-44-23,23>>^ Then you said to your slaves, ‘Unless YOUR youngest brother comes down with YOU, YOU may not see my face anymore.’

[[v1-44-24]]

^<<v1-44-24,24>>^ “And it came about that we went up to your slave my father and then told him the words of my master.

[[v1-44-25]]

^<<v1-44-25,25>>^ Later our father said, ‘Return, buy a little food for us.’

[[v1-44-26]]

^<<v1-44-26,26>>^ But we said, ‘We are not able to go down. If our youngest brother is with us we will go down, because we are not able to see the man’s face in case our youngest brother is not with us.’

[[v1-44-27]]

^<<v1-44-27,27>>^ Then your slave my father said to us, ‘YOU yourselves well know that my wife bore but two sons to me.

[[v1-44-28]]

^<<v1-44-28,28>>^ Later the one went out from my company and I exclaimed: “Ah, he must surely be torn to pieces!” and I have not seen him till now.

[[v1-44-29]]

^<<v1-44-29,29>>^ If YOU were to take this one also out of my sight and a fatal accident were to befall him, YOU would certainly bring down my gray hairs with calamity to Sheʹol.’

[[v1-44-30]]

^<<v1-44-30,30>>^ “And now, as soon as I should come to your slave my father without the boy along with us, when that one’s soul is bound up with this one’s soul,

[[v1-44-31]]

^<<v1-44-31,31>>^ then it is certain to occur that as soon as he sees that the boy is not there he will simply die, and your slaves will indeed bring down the gray hairs of your slave our father with grief to Sheʹol.^&#42;1^

[NOTE]
====
. “To Sheol.” Heb., sheʼoʹlah; Gr., eis haiʹdou; Syr., la·shiul; Lat., ad inʹfe·ros. See App 4B.
====

[[v1-44-32]]

^<<v1-44-32,32>>^ For your slave became surety for the boy when away from his father, saying, ‘If I fail to bring him back to you, then I shall have sinned against my father forever.’^&#42;1^

[NOTE]
====
. Lit., “all the days.”
====

[[v1-44-33]]

^<<v1-44-33,33>>^ So now, please, let your slave stay instead of the boy as a slave to my master, that the boy may go up with his brothers.

[[v1-44-34]]

^<<v1-44-34,34>>^ For how can I go up to my father without the boy along with me, for fear that then I may look upon the calamity that will find out my father?”

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]