include::./index.adoc[]

[[v1-3-0]]
=== Genesis, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-3-1]]

^<<v1-3-1,1>>^ Now the serpent proved to be the most cautious of all the wild beasts of the field that Jehovah God had made. So it began to say to the woman: “Is it really so that God said YOU must not eat from every tree of the garden?”

[[v1-3-2]]

^<<v1-3-2,2>>^ At this the woman said to the serpent: “Of the fruit of the trees^&#42;1^ of the garden we may eat.

[NOTE]
====
. Lit., “tree,” sing. but in a collective sense, denoting a grove or wood.
====

[[v1-3-3]]

^<<v1-3-3,3>>^ But as for &#91;eating&#93; of the fruit of the tree that is in the middle of the garden, God has said, ‘YOU must not eat from it, no, YOU must not touch it that YOU do not die.’”

[[v1-3-4]]

^<<v1-3-4,4>>^ At this the serpent said to the woman: “YOU positively will not die.^&#42;1^

[NOTE]
====
. “You positively will not die.” Lit., “not dying you [pl.] will die.” Heb., loʼ-mohthʹ temu·thunʹ. Compare 2:17.
====

[[v1-3-5]]

^<<v1-3-5,5>>^ For God knows that in the very day of YOUR eating from it YOUR eyes are bound to be opened and YOU are bound to be like God,^&#42;1^ KNOWING good and bad.”

[NOTE]
====
. “Like God.” Heb., kEʼ·lo·himʹ, without the definite article. This title is pl. to denote majesty or excellence.
====

[[v1-3-6]]

^<<v1-3-6,6>>^ Consequently the woman saw that the tree was good for food and that it was something to be longed for to the eyes, yes, the tree was desirable to look upon.^&#42;1^ So she began taking of its fruit and eating it. Afterward she gave some also to her husband^&#42;2^ when with her and he began eating it.

[NOTE]
====
. “To look upon,” LXXSyVg. Lit., “to impart wisdom (intelligence; prudence).”
. Or, “to her man.” Heb., leʼi·shahʹ.
====

[[v1-3-7]]

^<<v1-3-7,7>>^ Then the eyes of both of them became opened and they began to realize that they were naked. Hence they sewed fig leaves together and made loin coverings for themselves.

[[v1-3-8]]

^<<v1-3-8,8>>^ Later they heard the voice^&#42;1^ of Jehovah God walking in the garden about the breezy part^&#42;2^ of the day, and the man^&#42;3^ and his wife went into hiding from the face of Jehovah God in between the trees of the garden.

[NOTE]
====
. Or, “sound.”
. Lit., “about the breeze of.” Heb., leruʹach, the same basic word translated “active force” in 1:2.
. Or, “the earthling man.” Heb., ha·ʼa·dhamʹ; LXXSyVg, “and Adam.”
====

[[v1-3-9]]

^<<v1-3-9,9>>^ And Jehovah God kept calling to the man and saying to him: “Where are you?”

[[v1-3-10]]

^<<v1-3-10,10>>^ Finally he said: “Your voice I heard in the garden, but I was afraid because I was naked and so I hid myself.”

[[v1-3-11]]

^<<v1-3-11,11>>^ At that he said: “Who told you that you were naked? From the tree from which I commanded you not to eat have you eaten?”

[[v1-3-12]]

^<<v1-3-12,12>>^ And the man went on to say: “The woman whom you gave to be^&#42;1^ with me, she gave me &#91;fruit&#93; from the tree and so I ate.”

[NOTE]
====
. Or, “whom you put.”
====

[[v1-3-13]]

^<<v1-3-13,13>>^ With that Jehovah God said to the woman: “What is this you have done?” To this the woman replied: “The serpent—it deceived me and so I ate.”

[[v1-3-14]]

^<<v1-3-14,14>>^ And Jehovah^&#42;1^ God proceeded to say to the serpent: “Because you have done this thing, you are the cursed one out of all^&#42;2^ the domestic animals and out of all the wild beasts of the field. Upon your belly you will go and dust is what you will eat^&#42;3^ all the days of your life.

[NOTE]
====
. Heb., Yeho·wahʹ. The first of quite a few occurrences in BHK and BHS where the divine name is vowel-pointed with the additional vowel “o.” See 2:4 ftn, “Jehovah”; App 1A.
. Or, “you are cursed as no other of.”
. Or, “bite.”
====

[[v1-3-15]]

^<<v1-3-15,15>>^ And I shall put enmity between you and the woman and between your seed^&#42;1^ and her seed. He^&#42;2^ will bruise^&#42;3^ you in the head and you will bruise him^&#42;4^ in the heel.”

[NOTE]
====
. Or, “offspring; posterity.”
. “He,” M(Heb., huʼ)LXXSyVgmss.
. This rendering agrees with the reference to this divine utterance in Ro 16:20, where the Gr. word used means “crush” or “bruise.”
. “Him,” MLXXSy; that is, the woman’s “seed,” masc.
====

[[v1-3-16]]

^<<v1-3-16,16>>^ To the woman he said: “I shall greatly increase the pain of your pregnancy;^&#42;1^ in birth pangs you will bring forth children, and your craving will be for your husband, and he will dominate you.”

[NOTE]
====
. Lit., “increase your pain and your pregnancy.” This is a figure of hendiadys in which two words are connected by “and,” but one thing is meant.
====

[[v1-3-17]]

^<<v1-3-17,17>>^ And to Adam he said: “Because you listened to your wife’s voice and took to eating from the tree concerning which I gave you this command, ‘You must not eat from it,’ cursed is the ground on your account. In pain you will eat its produce all the days of your life.

[[v1-3-18]]

^<<v1-3-18,18>>^ And thorns and thistles it will grow for you, and you must eat the vegetation of the field.

[[v1-3-19]]

^<<v1-3-19,19>>^ In the sweat of your face you will eat bread until you return to the ground, for out of it you were taken. For dust you are and to dust you will return.”

[[v1-3-20]]

^<<v1-3-20,20>>^ After this Adam called his wife’s name Eve,^&#42;1^ because she had to become the mother of everyone living.

[NOTE]
====
. Meaning “Living One,” fem. Heb., Chaw·wahʹ; Gr., Zo·eʹ, “Life”; Vgc(Lat.), Heʹva.
====

[[v1-3-21]]

^<<v1-3-21,21>>^ And Jehovah God proceeded to make long garments of skin for Adam and for his wife and to clothe them.

[[v1-3-22]]

^<<v1-3-22,22>>^ And Jehovah God went on to say: “Here the man has become like one of us in knowing good and bad, and now in order that he may not put his hand out and actually take &#91;fruit&#93; also from the tree of life and eat and live to time indefinite,—”

[[v1-3-23]]

^<<v1-3-23,23>>^ With that Jehovah God^&#42;1^ put him out of the garden of Eʹden to cultivate the ground from which he had been taken.

[NOTE]
====
. See 2:4 ftn, “God.”
====

[[v1-3-24]]

^<<v1-3-24,24>>^ And so he drove the man out and posted^&#42;1^ at the east of the garden of Eʹden the cherubs and the flaming blade of a sword that was turning itself continually to guard the way to the tree of life.

[NOTE]
====
. Lit., “caused to reside.” See Ps 7:5; 78:55; Eze 32:4.
====

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]