include::./index.adoc[]

[[v1-41-0]]
=== Genesis, 41
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-41-1]]

^<<v1-41-1,1>>^ And it came about at the end of two full years^&#42;1^ that Pharʹaoh was dreaming and here he was standing by the river Nile.

[NOTE]
====
. Lit., “two years of days.”
====

[[v1-41-2]]

^<<v1-41-2,2>>^ And here ascending out of the river Nile were seven cows beautiful in appearance and fat-fleshed, and they went feeding among the Nile grass.^&#42;1^

[NOTE]
====
. Or, “the reeds.”
====

[[v1-41-3]]

^<<v1-41-3,3>>^ And here there were seven other cows ascending after them out of the river Nile, ugly in appearance and thin-fleshed, and they took their stand alongside the cows by the bank of the river Nile.

[[v1-41-4]]

^<<v1-41-4,4>>^ Then the cows that were ugly in appearance and thin-fleshed began to eat up the seven cows that were beautiful in appearance and fat. At this Pharʹaoh woke up.

[[v1-41-5]]

^<<v1-41-5,5>>^ However, he went back to sleep and dreamed a second time. And here there were seven ears of grain coming up on one stalk, fat and good.

[[v1-41-6]]

^<<v1-41-6,6>>^ And here there were seven ears of grain, thin and scorched by the east wind, growing up after them.

[[v1-41-7]]

^<<v1-41-7,7>>^ And the thin ears of grain began to swallow up the seven fat and full ears of grain. At this Pharʹaoh woke up and here it was a dream.

[[v1-41-8]]

^<<v1-41-8,8>>^ And it developed in the morning that his spirit became agitated. So he sent and called all the magic-practicing priests of Egypt and all her wise men, and Pharʹaoh went on to relate his dreams^&#42;1^ to them. But there was no interpreter of them for Pharʹaoh.

[NOTE]
====
. “Dreams,” Sam; MLXXVg, “dream.”
====

[[v1-41-9]]

^<<v1-41-9,9>>^ Then the chief of the cupbearers spoke with Pharʹaoh, saying: “My sins I am mentioning today.

[[v1-41-10]]

^<<v1-41-10,10>>^ Pharʹaoh was indignant at his servants. So he committed me to the jail of the house of the chief of the bodyguard, both me and the chief of the bakers.

[[v1-41-11]]

^<<v1-41-11,11>>^ After that we both dreamed a dream in the one night, both I and he. We dreamed each one his dream with its own interpretation.

[[v1-41-12]]

^<<v1-41-12,12>>^ And there was with us there a young man, a Hebrew, a servant of the chief of the bodyguard. When we related them to him, he proceeded to interpret our dreams to us. He interpreted to each according to his dream.

[[v1-41-13]]

^<<v1-41-13,13>>^ And it turned out that just as he had interpreted to us so it happened. Me he returned to my office, but him he hanged.”^&#42;1^

[NOTE]
====
. “Him he hanged,” M; LXX, “that one was hanged”; Vg, “that one was hanged on a torture stake [Lat., cruʹce (from crux)].”
====

[[v1-41-14]]

^<<v1-41-14,14>>^ And Pharʹaoh proceeded to send and to call Joseph, that they might bring him quickly from the prison hole. Hence he shaved and changed his mantles and went in to Pharʹaoh.

[[v1-41-15]]

^<<v1-41-15,15>>^ Then Pharʹaoh said to Joseph: “I have dreamed a dream, but there is no interpreter of it. Now I myself have heard it said about you that you can hear a dream and interpret it.”

[[v1-41-16]]

^<<v1-41-16,16>>^ At this Joseph answered Pharʹaoh, saying: “I need not be considered! God will announce^&#42;1^ welfare to Pharʹaoh.”

[NOTE]
====
. “Without me God will announce,” Vg.
====

[[v1-41-17]]

^<<v1-41-17,17>>^ And Pharʹaoh went on to speak to Joseph: “In my dream here I was standing on the bank of the river Nile.

[[v1-41-18]]

^<<v1-41-18,18>>^ And here ascending out of the river Nile were seven cows fat-fleshed and beautiful in form, and they began to feed among the Nile grass.

[[v1-41-19]]

^<<v1-41-19,19>>^ And here there were seven other cows ascending after them, poor and very bad in form and thin-fleshed. For badness I have not seen the like of them in all the land of Egypt.

[[v1-41-20]]

^<<v1-41-20,20>>^ And the skinny and bad cows began to eat up the first seven fat cows.

[[v1-41-21]]

^<<v1-41-21,21>>^ So these came into their bellies, and yet it could not be known that they had come into their bellies, as their appearance was bad just as at the start. At that I woke up.

[[v1-41-22]]

^<<v1-41-22,22>>^ “After that I saw in my dream and here there were seven ears of grain coming up on one stalk, full and good.

[[v1-41-23]]

^<<v1-41-23,23>>^ And here there were seven ears of grain shriveled, thin, scorched by the east wind, growing up after them.

[[v1-41-24]]

^<<v1-41-24,24>>^ And the thin ears of grain began to swallow up the seven good ears of grain. So I stated it to the magic-practicing priests, but there was none telling me.”

[[v1-41-25]]

^<<v1-41-25,25>>^ Then Joseph said to Pharʹaoh: “The dream of Pharʹaoh is but one. What the &#91;true&#93; God is doing he has told to Pharʹaoh.

[[v1-41-26]]

^<<v1-41-26,26>>^ The seven good cows are seven years. Likewise the seven good ears of grain are seven years. The dream is but one.

[[v1-41-27]]

^<<v1-41-27,27>>^ And the seven skinny and bad cows that came up after them are seven years; and the seven empty ears of grain, scorched by the east wind, will prove to be seven years of famine.

[[v1-41-28]]

^<<v1-41-28,28>>^ This is the thing that I have spoken to Pharʹaoh: What the &#91;true&#93; God is doing he has caused Pharʹaoh to see.

[[v1-41-29]]

^<<v1-41-29,29>>^ “Here there are seven years coming with great plenty in all the land of Egypt.

[[v1-41-30]]

^<<v1-41-30,30>>^ But seven years of famine will certainly arise after them, and all the plenty in the land of Egypt will certainly be forgotten and the famine will simply consume the land.

[[v1-41-31]]

^<<v1-41-31,31>>^ And the plenty once in the land will not be known as a result of that famine afterward, because it will certainly be very severe.

[[v1-41-32]]

^<<v1-41-32,32>>^ And the fact that the dream was repeated to Pharʹaoh twice means that the thing is firmly established on the part of the &#91;true&#93; God, and the &#91;true&#93; God is speeding to do it.

[[v1-41-33]]

^<<v1-41-33,33>>^ “So now let Pharʹaoh look for a man discreet and wise and set him over the land of Egypt.

[[v1-41-34]]

^<<v1-41-34,34>>^ Let Pharʹaoh act and appoint overseers over the land, and he must take up one fifth of the land of Egypt during the seven years of plenty.

[[v1-41-35]]

^<<v1-41-35,35>>^ And let them collect all the foodstuffs of these coming good years, and let them pile up grain under Pharʹaoh’s hand as foodstuffs in the cities, and they must safeguard it.

[[v1-41-36]]

^<<v1-41-36,36>>^ And the foodstuffs must serve as a supply for the land for the seven famine years, which will develop in the land of Egypt, in order that the land may not be cut off by the famine.”

[[v1-41-37]]

^<<v1-41-37,37>>^ Well, the thing proved to be good in the eyes of Pharʹaoh and of all his servants.

[[v1-41-38]]

^<<v1-41-38,38>>^ So Pharʹaoh said to his servants: “Can another man be found like this one in whom the spirit of God is?”

[[v1-41-39]]

^<<v1-41-39,39>>^ After that Pharʹaoh said to Joseph: “Since God has caused you to know all this, there is no one as discreet and wise as you are.

[[v1-41-40]]

^<<v1-41-40,40>>^ You will personally be over my house, and all my people will obey you implicitly.^&#42;1^ Only as to the throne shall I be greater than you.”

[NOTE]
====
. Lit., “upon your mouth all my people will kiss [fit; adjust themselves].”
====

[[v1-41-41]]

^<<v1-41-41,41>>^ And Pharʹaoh added to Joseph: “See, I do place you over all the land of Egypt.”

[[v1-41-42]]

^<<v1-41-42,42>>^ With that Pharʹaoh removed his signet ring from his own hand and put it upon Joseph’s hand and clothed him with garments of fine linen^&#42;1^ and placed a necklace of gold about his neck.

[NOTE]
====
. Or, “byssus fabric.”
====

[[v1-41-43]]

^<<v1-41-43,43>>^ Moreover, he had him ride in the second chariot of honor that he had, so that they should call out ahead of him, “A·vrékh!”^&#42;1^ thus putting him over all the land of Egypt.

[NOTE]
====
. “Avrékh!” Heb., ʼAv·rekhʹ. The exact meaning of this expression transliterated from Egyptian into Heb. has not yet been determined. Sy, “Father and Ruler!”; Vg, “That all should bend the knee before him.”
====

[[v1-41-44]]

^<<v1-41-44,44>>^ And Pharʹaoh further said to Joseph: “I am Pharʹaoh, but without your authorization no man may lift up his hand or his foot in all the land of Egypt.”

[[v1-41-45]]

^<<v1-41-45,45>>^ After that Pharʹaoh called Joseph’s name Zaphʹe·nath-pa·neʹah^&#42;1^ and gave him Asʹe·nath the daughter of Pot·iʹphe·ra^&#42;2^ the priest of On^&#42;3^ as a wife. And Joseph began to go out over the land of Egypt.

[NOTE]
====
. Meaning “Revealer of Hidden Things,” the way the Hebrews understood this form of the word. Lat., Sal·va·toʹrem munʹdi, “Savior of the world.”
. In the Cairo Museum there is a funeral pillar (stele) discovered in 1935 that refers to a personage named Potiphare.
. “On,” M; LXXVg, “Heliopolis,” meaning “City of the Sun,” because worship of the sun in the form of the god Ra was carried on in his temple there.
====

[[v1-41-46]]

^<<v1-41-46,46>>^ And Joseph was thirty years old when he stood before Pharʹaoh the king of Egypt.
Then Joseph went out from before Pharʹaoh and toured about in all the land of Egypt.

[[v1-41-47]]

^<<v1-41-47,47>>^ And during the seven years of plenty the land went on producing by the handfuls.

[[v1-41-48]]

^<<v1-41-48,48>>^ And he kept collecting all the foodstuffs of the seven years that came upon the land of Egypt and he would put the foodstuffs in the cities. The foodstuffs of the field that was round about a city he put in the midst of it.

[[v1-41-49]]

^<<v1-41-49,49>>^ And Joseph continued piling up grain in very great quantity, like the sand of the sea, until finally they gave up counting it, because it was without number.

[[v1-41-50]]

^<<v1-41-50,50>>^ And before the year of the famine arrived there were born to Joseph two sons, whom Asʹe·nath the daughter of Pot·iʹphe·ra the priest of On bore to him.

[[v1-41-51]]

^<<v1-41-51,51>>^ So Joseph called the name of the firstborn Ma·nasʹseh,^&#42;1^ because, to quote him, “God^&#42;2^ has made me forget all my trouble and all the house of my father.”

[NOTE]
====
. Meaning “One Making Forgetful; One Who Makes Forget.” Heb., Menash·shehʹ.
. Heb., ʼElo·himʹ, without the definite article.
====

[[v1-41-52]]

^<<v1-41-52,52>>^ And the name of the second he called Eʹphra·im,^&#42;1^ because, to quote him, “God has made me fruitful in the land of my wretchedness.”

[NOTE]
====
. Meaning “Doubly Fruitful; Fruitland.” Heb., ʼEph·raʹyim.
====

[[v1-41-53]]

^<<v1-41-53,53>>^ And the seven years of the plenty that had obtained in the land of Egypt gradually ended,

[[v1-41-54]]

^<<v1-41-54,54>>^ and, in turn, the seven years of the famine started to come, just as Joseph had said. And the famine developed in all the lands, but in all the land of Egypt there was found bread.

[[v1-41-55]]

^<<v1-41-55,55>>^ Finally all the land of Egypt became famished and the people began to cry to Pharʹaoh for bread. Then Pharʹaoh said to all the Egyptians: “Go to Joseph. Whatever he says to YOU, YOU are to do.”

[[v1-41-56]]

^<<v1-41-56,56>>^ And the famine obtained over all the surface of the earth. Then Joseph began to open up all the grain depositories that were among them^&#42;1^ and to sell to the Egyptians,^&#42;2^ as the famine got a strong grip on the land of Egypt.

[NOTE]
====
. Lit., “open up all that was among them.” LXX, “open up all the grain depositories.”
. Or, “to Egypt.”
====

[[v1-41-57]]

^<<v1-41-57,57>>^ Moreover, people of all the earth^&#42;1^ came to Egypt to buy from Joseph, because the famine had a strong grip on all the earth.

[NOTE]
====
. Lit., “Moreover, all the earth,” but the verb “came” is pl., denoting people.
====

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]