include::./index.adoc[]

[[v1-18-0]]
=== Genesis, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-18-1]]

^<<v1-18-1,1>>^ Afterward Jehovah appeared to him among the big trees of Mamʹre, while he was sitting at the entrance of the tent about the heat of the day.

[[v1-18-2]]

^<<v1-18-2,2>>^ When he raised his eyes, then he looked and there three men were standing some distance from him. When he caught sight of them he began running to meet them from the entrance of the tent and proceeded to bow down to the earth.

[[v1-18-3]]

^<<v1-18-3,3>>^ Then he said: “Jehovah,^&#42;1^ if, now, I have found favor in your eyes, please do not pass by your servant.

[NOTE]
====
. This is the first of 134 places where the Jewish Sopherim changed YHWH to ʼAdho·naiʹ. This substitution was made out of misapplied reverence for God’s name. See App 1B.
====

[[v1-18-4]]

^<<v1-18-4,4>>^ Let a little water be taken, please, and YOU must have YOUR feet washed. Then recline under the tree.

[[v1-18-5]]

^<<v1-18-5,5>>^ And let me get a piece of bread, and refresh YOUR hearts. Following that, YOU can pass on, because that is why YOU have passed this way to YOUR servant.” At this they said: “All right. You may do just as you have spoken.”

[[v1-18-6]]

^<<v1-18-6,6>>^ So Abraham went hurrying to the tent to Sarah and said: “Hurry! Get three seah^&#42;1^ measures of fine flour, knead the dough and make round cakes.”

[NOTE]
====
. A seah equaled 7.33 L (6.66 dry qt).
====

[[v1-18-7]]

^<<v1-18-7,7>>^ Next Abraham ran to the herd and proceeded to get a tender and good young bull and to give it to the attendant, and he went hurrying to get it ready.

[[v1-18-8]]

^<<v1-18-8,8>>^ He then took butter and milk and the young bull that he had got ready and set it before them. Then he himself kept standing by them under the tree as they were eating.

[[v1-18-9]]

^<<v1-18-9,9>>^ They now said to him:^&#42;1^ “Where is Sarah your wife?” To this he said: “Here in the tent!”

[NOTE]
====
. “To him.” This expression in M is marked with extraordinary points by the Sopherim but requires no change in the English translation. See App 2A.
====

[[v1-18-10]]

^<<v1-18-10,10>>^ So he continued: “I am surely going to return to you next year at this time,^&#42;1^ and, look! Sarah your wife will have a son.” Now Sarah was listening at the tent entrance, and it was behind the man.

[NOTE]
====
. Or, “at this time in spring.” Sy, “at this time next year”; Vg, “at this [same] time, life being a companion.” Compare Ro 4:17-20.
====

[[v1-18-11]]

^<<v1-18-11,11>>^ And Abraham and Sarah were old, being advanced in years. Sarah had stopped having menstruation.^&#42;1^

[NOTE]
====
. Lit., “the way according to women.” To this day, the common Heb. expression for the menstrual period.
====

[[v1-18-12]]

^<<v1-18-12,12>>^ Hence Sarah began to laugh inside herself, saying: “After I am worn out, shall I really have pleasure, my lord^&#42;1^ being old besides?”

[NOTE]
====
. Lit., “and my lord.” Heb., waʼ·dho·niʹ. Sarah is commended for addressing her husband, “my lord.” See 1Pe 3:6.
====

[[v1-18-13]]

^<<v1-18-13,13>>^ Then Jehovah said to Abraham: “Why was it that Sarah laughed, saying, ‘Shall I really and truly give birth although I have become old?’

[[v1-18-14]]

^<<v1-18-14,14>>^ Is anything too extraordinary for Jehovah? At the appointed time I shall return to you, next year at this time, and Sarah will have a son.”

[[v1-18-15]]

^<<v1-18-15,15>>^ But Sarah began to deny it, saying: “I did not laugh!” For she was afraid. At this he said: “No! but you did laugh.”

[[v1-18-16]]

^<<v1-18-16,16>>^ Later the men got up from there and looked down toward Sodʹom, and Abraham was walking with them to escort them.

[[v1-18-17]]

^<<v1-18-17,17>>^ And Jehovah^&#42;1^ said: “Am I keeping covered from Abraham what I am doing?

[NOTE]
====
. “And Jehovah.” Heb., wa·Yho·wahʹ.
====

[[v1-18-18]]

^<<v1-18-18,18>>^ Why, Abraham is surely going to become a nation great and mighty, and all the nations of the earth must bless themselves by means of him.

[[v1-18-19]]

^<<v1-18-19,19>>^ For I have become acquainted with him in order that he may command his sons and his household after him so that they shall keep Jehovah’s way to do righteousness and judgment; in order that Jehovah may certainly bring upon Abraham what he has spoken about him.”

[[v1-18-20]]

^<<v1-18-20,20>>^ Consequently Jehovah said: “The cry of complaint about Sodʹom and Go·morʹrah, yes, it is loud, and their sin, yes, it is very heavy.

[[v1-18-21]]

^<<v1-18-21,21>>^ I am quite determined to go down that I may see whether they act altogether according to the outcry over it that has come to me, and, if not, I can get to know it.”

[[v1-18-22]]

^<<v1-18-22,22>>^ At this point the men turned from there and got on their way to Sodʹom; but as for Jehovah, he was still standing before Abraham.^&#42;1^

[NOTE]
====
. The first of the Eighteen Emendations of the Sopherim, the only one in Ge. M, “but as for Abraham, he was still standing before Jehovah.” See App 2B.
====

[[v1-18-23]]

^<<v1-18-23,23>>^ Then Abraham approached and began to say: “Will you really sweep away the righteous with the wicked?

[[v1-18-24]]

^<<v1-18-24,24>>^ Suppose there are fifty righteous men in the midst of the city. Will you, then, sweep them away and not pardon the place for the sake of the fifty righteous who are inside it?

[[v1-18-25]]

^<<v1-18-25,25>>^ It is unthinkable of you that you are acting in this manner to put to death the righteous man with the wicked one so that it has to occur with the righteous man as it does with the wicked! It is unthinkable of you. Is the Judge of all the earth not going to do what is right?”

[[v1-18-26]]

^<<v1-18-26,26>>^ Then Jehovah said: “If I shall find in Sodʹom fifty righteous men in the midst of the city I will pardon the whole place on their account.”

[[v1-18-27]]

^<<v1-18-27,27>>^ But Abraham went on to answer and say: “Please, here I have taken upon myself to speak to Jehovah,^&#42;1^ whereas I am dust and ashes.

[NOTE]
====
. See vs 3 ftn.
====

[[v1-18-28]]

^<<v1-18-28,28>>^ Suppose the fifty righteous should be lacking five. Will you for the five bring the whole city to ruin?” To this he said: “I shall not bring it to ruin if I find there forty-five.”

[[v1-18-29]]

^<<v1-18-29,29>>^ But yet again he spoke further to him and said: “Suppose forty are found there.” In turn he said: “I shall not do it on account of the forty.”

[[v1-18-30]]

^<<v1-18-30,30>>^ But he continued: “May Jehovah,^&#42;1^ please, not grow hot with anger, but let me go on speaking: Suppose thirty are found there.” In turn he said: “I shall not do it if I find thirty there.”

[NOTE]
====
. See vs 3 ftn.
====

[[v1-18-31]]

^<<v1-18-31,31>>^ But he continued on: “Please, here I have taken upon myself to speak to Jehovah:^&#42;1^ Suppose twenty are found there.” In turn he said: “I shall not bring it to ruin on account of the twenty.”

[NOTE]
====
. See vs 3 ftn.
====

[[v1-18-32]]

^<<v1-18-32,32>>^ Finally he said: “May Jehovah,^&#42;1^ please, not grow hot with anger, but let me speak just this once: Suppose ten are found there.” In turn he said: “I shall not bring it to ruin on account of the ten.”

[NOTE]
====
. See vs 3 ftn.
====

[[v1-18-33]]

^<<v1-18-33,33>>^ Then Jehovah went his way when he had finished speaking to Abraham, and Abraham returned to his place.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]