include::./index.adoc[]

[[v1-24-0]]
=== Genesis, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-24-1]]

^<<v1-24-1,1>>^ Now Abraham was old, advanced in years;^&#42;1^ and Jehovah had blessed Abraham in everything.

[NOTE]
====
. Lit., “days.”
====

[[v1-24-2]]

^<<v1-24-2,2>>^ Hence Abraham said to his servant, the oldest one of his household, who was managing^&#42;1^ all he had: “Put your hand, please, under my thigh,

[NOTE]
====
. “Who was managing.” Lit., “the one ruling.” Heb., ham·mo·shelʹ, that is, the one serving as a steward, a household manager. See Lu 12:42 ftn.
====

[[v1-24-3]]

^<<v1-24-3,3>>^ as I must have you swear by Jehovah, the God of the heavens and the God of the earth, that you will not take a wife for my son from the daughters of the Caʹnaan·ites in among whom I am dwelling,

[[v1-24-4]]

^<<v1-24-4,4>>^ but you will go to my country and to my relatives, and you will certainly take a wife for my son, for Isaac.”

[[v1-24-5]]

^<<v1-24-5,5>>^ However, the servant said to him: “What if the woman does not wish to come with me to this land? Must I be sure to return your son to the land from where you went out?”

[[v1-24-6]]

^<<v1-24-6,6>>^ At this Abraham said to him: “Be on your guard that you do not return my son there.

[[v1-24-7]]

^<<v1-24-7,7>>^ Jehovah the God of the heavens, who took me from my father’s house and from the land of my relatives^&#42;1^ and who spoke to me and who swore to me, saying, ‘To your seed I am going to give this land,’ he will send his angel ahead of you, and you will certainly take a wife for my son from there.

[NOTE]
====
. Or, “home.”
====

[[v1-24-8]]

^<<v1-24-8,8>>^ But if the woman should not wish to come with you, you also will have become free from this oath you gave me. Only you must not return my son there.”

[[v1-24-9]]

^<<v1-24-9,9>>^ With that the servant put his hand under the thigh of Abraham his master and swore to him concerning this matter.

[[v1-24-10]]

^<<v1-24-10,10>>^ So the servant took ten camels from the camels of his master and proceeded to go with every sort of good thing of his master’s in his hand. Then he rose and got on his way to Mes·o·po·taʹmi·a^&#42;1^ to the city of Naʹhor.

[NOTE]
====
. “Mesopotamia” (meaning “[Land] Between Rivers”), LXXVg; Heb., ʼAramʹ Na·haraʹyim, meaning “Aram of the Two Rivers.”
====

[[v1-24-11]]

^<<v1-24-11,11>>^ Eventually he had the camels kneel down outside the city at a well of water about evening time, about the time that the women who draw water were accustomed to go out.

[[v1-24-12]]

^<<v1-24-12,12>>^ And he went on to say: “Jehovah the God of my master Abraham, cause it to happen, please, before me this day and perform loving-kindness with my master Abraham.

[[v1-24-13]]

^<<v1-24-13,13>>^ Here I am stationed at a fountain of water, and the daughters of the men of the city are coming out to draw water.

[[v1-24-14]]

^<<v1-24-14,14>>^ What must occur is that the young woman to whom I shall say, ‘Let your water jar down, please, that I may take a drink,’ and who will indeed say, ‘Take a drink, and I shall also water your camels,’ this is the one you must assign to your servant, to Isaac; and by this let me know that you have performed loyal love with my master.”

[[v1-24-15]]

^<<v1-24-15,15>>^ Well, it came about that before he had finished speaking, why, here coming out was Re·bekʹah, who had been born to Be·thuʹel the son of Milʹcah the wife of Naʹhor, Abraham’s brother, and her water jar was upon her shoulder.

[[v1-24-16]]

^<<v1-24-16,16>>^ Now the young woman^&#42;1^ was very attractive in appearance, a virgin,^&#42;2^ and no man had had sexual intercourse with her; and she made her way down to the fountain and began to fill her water jar and then came up.

[NOTE]
====
. “Now the young woman.” Heb., wehan·na·ʽaraʹ.
. “Virgin.” Heb., bethu·lahʹ; Gr., par·theʹnos; Lat., virʹgo.
====

[[v1-24-17]]

^<<v1-24-17,17>>^ At once the servant ran to meet her and said: “Give me, please, a little sip of water from your jar.”

[[v1-24-18]]

^<<v1-24-18,18>>^ In turn she said: “Drink, my lord.” With that she quickly lowered her jar upon her hand and gave him a drink.

[[v1-24-19]]

^<<v1-24-19,19>>^ When she was finished giving him a drink, then she said: “For your camels too I shall draw water until they are done drinking.”

[[v1-24-20]]

^<<v1-24-20,20>>^ So she quickly emptied her jar into the drinking trough and ran yet again and again to the well to draw water, and kept drawing for all his camels.

[[v1-24-21]]

^<<v1-24-21,21>>^ All the while the man was gazing at her in wonder, keeping silent to know whether Jehovah had made his trip successful or not.

[[v1-24-22]]

^<<v1-24-22,22>>^ Consequently it came about that, when the camels had finished drinking, then the man took a gold nose ring of a half shekel^&#42;1^ in weight and two bracelets for her hands, ten shekels of gold was their weight,

[NOTE]
====
. A shekel weighed 11.4 g (0.367 oz t).
====

[[v1-24-23]]

^<<v1-24-23,23>>^ and he went on to say: “Whose daughter are you? Tell me, please. Is there any room at the house of your father for us to spend the night?”

[[v1-24-24]]

^<<v1-24-24,24>>^ At that she said to him: “I am the daughter of Be·thuʹel the son of Milʹcah, whom she bore to Naʹhor.”

[[v1-24-25]]

^<<v1-24-25,25>>^ And she said further to him: “There is both straw and much fodder with us, also a place to spend the night.”

[[v1-24-26]]

^<<v1-24-26,26>>^ And the man proceeded to bow down and prostrate himself before Jehovah

[[v1-24-27]]

^<<v1-24-27,27>>^ and say: “Blessed be Jehovah the God of my master Abraham, who has not left his loving-kindness and his trustworthiness toward my master. I being on the way, Jehovah has led me to the house of the brothers of my master.”

[[v1-24-28]]

^<<v1-24-28,28>>^ And the young woman went running and telling the household of her mother about these things.

[[v1-24-29]]

^<<v1-24-29,29>>^ Now Re·bekʹah had a brother and his name was Laʹban. So Laʹban went running to the man who was outside at the fountain.

[[v1-24-30]]

^<<v1-24-30,30>>^ And it came about that on seeing the nose ring and the bracelets on the hands of his sister and on hearing the words of Re·bekʹah his sister, saying: “This is the way the man spoke to me,” then he came to the man and there he was, standing by the camels at the fountain.

[[v1-24-31]]

^<<v1-24-31,31>>^ At once he said: “Come, you blessed one of Jehovah. Why do you keep standing out here, when I myself have made the house ready and room for the camels?”

[[v1-24-32]]

^<<v1-24-32,32>>^ With that the man came on into the house, and he went unharnessing the camels and giving straw and fodder to the camels and water to wash his feet and the feet of the men who were with him.

[[v1-24-33]]

^<<v1-24-33,33>>^ Then something to eat was set before him, but he said: “I shall not eat until I have spoken about my matters.” Hence he said: “Speak!”

[[v1-24-34]]

^<<v1-24-34,34>>^ Then he went on to say: “I am Abraham’s servant.

[[v1-24-35]]

^<<v1-24-35,35>>^ And Jehovah has blessed my master very much in that he goes on making him greater and giving him sheep and cattle and silver and gold and menservants and maidservants and camels and asses.

[[v1-24-36]]

^<<v1-24-36,36>>^ Further, Sarah the wife of my master bore a son to my master after her growing old; and he will give him everything he has.

[[v1-24-37]]

^<<v1-24-37,37>>^ So my master made me swear, saying, ‘You must not take a wife for my son from the daughters of the Caʹnaan·ites in whose land I am dwelling.

[[v1-24-38]]

^<<v1-24-38,38>>^ No, but you will go to the house of my father and to my family and you must take a wife for my son.’

[[v1-24-39]]

^<<v1-24-39,39>>^ But I said to my master, ‘What if the woman will not come with me?’

[[v1-24-40]]

^<<v1-24-40,40>>^ Then he said to me, ‘Jehovah, before whom I have walked, will send his angel with you and will certainly give success to your way; and you must take a wife for my son from my family and from the house of my father.

[[v1-24-41]]

^<<v1-24-41,41>>^ At that time you will be cleared of obligation to me by oath^&#42;1^ when you get to my family, and if they will not give her to you, then you shall become free of obligation to me by oath.’

[NOTE]
====
. Or, “cursing,” to which the swearer makes himself liable by transgressing his oath.
====

[[v1-24-42]]

^<<v1-24-42,42>>^ “When I got to the fountain today, then I said, ‘Jehovah the God of my master Abraham, if you are really giving success to my way on which I am going,

[[v1-24-43]]

^<<v1-24-43,43>>^ here I am stationed at a fountain of water. What must occur is that the maiden^&#42;1^ coming out to draw water to whom I shall actually say: “Please, let me drink a little water from your jar,”

[NOTE]
====
. “The maiden (virgin).” Heb., ha·ʽal·mahʹ; Gr., par·theʹnos; Lat., virʹgo. See Isa 7:14 ftn, “Maiden.”
====

[[v1-24-44]]

^<<v1-24-44,44>>^ and who will indeed say to me: “Both you take a drink, and I shall also draw water for your camels,” she is the woman whom Jehovah has assigned for the son of my master.’

[[v1-24-45]]

^<<v1-24-45,45>>^ “Before I was finished speaking in my heart, why, there was Re·bekʹah coming out, with her jar upon her shoulder; and she made her way down to the fountain and began to draw water. Then I said to her, ‘Give me a drink, please.’

[[v1-24-46]]

^<<v1-24-46,46>>^ So she quickly lowered her jar from off her and said, ‘Take a drink, and I shall also water your camels.’ Then I took a drink, and she also watered the camels.

[[v1-24-47]]

^<<v1-24-47,47>>^ After that I asked her and said, ‘Whose daughter are you?’ to which she said, ‘The daughter of Be·thuʹel the son of Naʹhor, whom Milʹcah bore to him.’ Accordingly I put the nose ring on her nostril and the bracelets on her hands.

[[v1-24-48]]

^<<v1-24-48,48>>^ And I proceeded to bow down and prostrate myself before Jehovah and bless Jehovah the God of my master Abraham, who had led me in the true way to take the daughter of the brother of my master for his son.

[[v1-24-49]]

^<<v1-24-49,49>>^ And now if YOU are actually exercising loving-kindness and trustworthiness toward my master, tell me; but if not, tell me, that I may turn to the right hand or to the left.”

[[v1-24-50]]

^<<v1-24-50,50>>^ Then Laʹban and Be·thuʹel answered and said: “From Jehovah this thing has issued. We are unable to speak bad or good to you.

[[v1-24-51]]

^<<v1-24-51,51>>^ Here is Re·bekʹah before you. Take her and go, and let her become a wife to the son of your master, just as Jehovah has spoken.”

[[v1-24-52]]

^<<v1-24-52,52>>^ And it came about that when Abraham’s servant had heard their words, he at once prostrated himself on the earth before Jehovah.

[[v1-24-53]]

^<<v1-24-53,53>>^ And the servant began to bring out articles of silver and articles of gold and garments and to give them to Re·bekʹah; and he gave choice things to her brother and to her mother.

[[v1-24-54]]

^<<v1-24-54,54>>^ After that they ate and drank, he and the men who were with him, and they spent the night there and got up in the morning.
Then he said: “SEND me off to my master.”

[[v1-24-55]]

^<<v1-24-55,55>>^ To this her brother and her mother said: “Let the young woman^&#42;1^ stay with us at least ten days.^&#42;2^ Afterward she can go.”

[NOTE]
====
. “The young woman (girl; virgin).” Heb., han·na·ʽaraʹ; Gr., par·theʹnos.
. Lit., “with us days or ten [of them].” Sy, “with us a month of days.” Compare 29:14.
====

[[v1-24-56]]

^<<v1-24-56,56>>^ But he said to them: “Do not detain me, seeing that Jehovah has given success to my way. Send me off, that I may go to my master.”

[[v1-24-57]]

^<<v1-24-57,57>>^ So they said: “Let us call the young woman and inquire at her mouth.”

[[v1-24-58]]

^<<v1-24-58,58>>^ Then they called Re·bekʹah and said to her: “Will you go with this man?” In turn she said: “I am willing to go.”

[[v1-24-59]]

^<<v1-24-59,59>>^ At that they sent off Re·bekʹah their sister and her nurse and Abraham’s servant and his men.

[[v1-24-60]]

^<<v1-24-60,60>>^ And they began to bless Re·bekʹah and say to her: “O you, our sister, may you become thousands times ten thousand,^&#42;1^ and let your seed take possession of the gate^&#42;2^ of those who hate it.”^&#42;3^

[NOTE]
====
. Lit., “thousands of myriads.”
. That is, of the city.
. Or, “them,” that is, the seed, offspring, posterity.
====

[[v1-24-61]]

^<<v1-24-61,61>>^ After that Re·bekʹah and her lady attendants^&#42;1^ rose and they went riding on the camels and following the man; and the servant took Re·bekʹah and got on his way.

[NOTE]
====
. Or, “her girls.”
====

[[v1-24-62]]

^<<v1-24-62,62>>^ Now Isaac had come from the way that goes to Beʹer-laʹhai-roi, for he was dwelling in the land of the Negʹeb.

[[v1-24-63]]

^<<v1-24-63,63>>^ And Isaac was out walking in order to meditate^&#42;1^ in the field at about the falling of evening. When he raised his eyes and looked, why, there camels were coming!

[NOTE]
====
. “Meditate,” LXXVg; that is, talk with himself.
====

[[v1-24-64]]

^<<v1-24-64,64>>^ When Re·bekʹah raised her eyes, she caught sight of Isaac and she swung herself down from off the camel.

[[v1-24-65]]

^<<v1-24-65,65>>^ Then she said to the servant: “Who is that man there walking in the field to meet us?” and the servant said: “It is my master.” And she proceeded to take a headcloth and to cover herself.

[[v1-24-66]]

^<<v1-24-66,66>>^ And the servant went relating to Isaac all the things he had done.

[[v1-24-67]]

^<<v1-24-67,67>>^ After that Isaac brought her into the tent of Sarah his mother. Thus he took Re·bekʹah and she became his wife; and he fell in love with her, and Isaac found comfort after the loss of his mother.^&#42;1^

[NOTE]
====
. Lit., “after his mother.” LXX, “concerning Sarah his mother.” Vg says in the closing part of this vs, “he loved [her] so greatly as to temper the grief that resulted from the death of [his] mother.”
====

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]