include::./index.adoc[]

[[v1-39-0]]
=== Genesis, 39
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-39-1]]

^<<v1-39-1,1>>^ As for Joseph, he was brought down to Egypt, and Potʹi·phar, a court official of Pharʹaoh,^&#42;1^ the chief of the bodyguard, an Egyptian, got to buy him from the hand of the Ishʹma·el·ites who had brought him down there.

[NOTE]
====
. See 12:15 ftn.
====

[[v1-39-2]]

^<<v1-39-2,2>>^ But Jehovah proved to be with Joseph, so that he turned out a successful man and came to be over the house of his master,^&#42;1^ the Egyptian.

[NOTE]
====
. “His master.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence, as in vss 3, 7, 8, 16, 19, 20.
====

[[v1-39-3]]

^<<v1-39-3,3>>^ And his master got to see that Jehovah was with him and that everything he was doing Jehovah was making turn out successful in his hand.

[[v1-39-4]]

^<<v1-39-4,4>>^ And Joseph kept finding favor in his eyes and waited upon him continually, so that he appointed him over his house, and all that was his he gave into his hand.

[[v1-39-5]]

^<<v1-39-5,5>>^ And it followed that from the time he appointed him over his house and in charge of all that was his Jehovah kept blessing the house of the Egyptian due to Joseph, and Jehovah’s blessing came to be upon all that he had in the house and in the field.

[[v1-39-6]]

^<<v1-39-6,6>>^ Finally he left everything that was his in Joseph’s hand; and he did not know what was with him at all except the bread he was eating. Moreover, Joseph grew to be beautiful in form and beautiful in appearance.

[[v1-39-7]]

^<<v1-39-7,7>>^ Now after these things it came about that the wife of his master began to raise her eyes toward Joseph and say: “Lie down with me.”

[[v1-39-8]]

^<<v1-39-8,8>>^ But he would refuse and would say to his master’s wife: “Here my master does not know what is with me in the house, and everything he has he has given into my hand.

[[v1-39-9]]

^<<v1-39-9,9>>^ There is no one greater in this house than I am, and he has not withheld from me anything at all except you, because you are his wife. So how could I commit this great badness and actually sin against God?”

[[v1-39-10]]

^<<v1-39-10,10>>^ So it turned out that as she spoke to Joseph day after day he never listened to her to lie alongside her, to continue with her.

[[v1-39-11]]

^<<v1-39-11,11>>^ But it happened that on this day as other days^&#42;1^ he went into the house to do his business, and there was none of the men of the house there in the house.

[NOTE]
====
. “On this day as other days.” For this rendering see VT, Vol. II, 1952, pp. 85-87.
====

[[v1-39-12]]

^<<v1-39-12,12>>^ Then she grabbed hold of him by his garment, saying: “Lie down with me!” But he left his garment in her hand and took to flight and went on outside.

[[v1-39-13]]

^<<v1-39-13,13>>^ So it occurred that as soon as she saw that he had left his garment in her hand that he might flee outside,

[[v1-39-14]]

^<<v1-39-14,14>>^ she began to cry out to the men of her house and to say to them: “Look! He brought to us a man, a Hebrew, to make us a laughingstock. He came to me to lie down with me, but I began to cry out at the top of my voice.

[[v1-39-15]]

^<<v1-39-15,15>>^ And it followed that as soon as he heard that I raised my voice and began crying out, he then left his garment beside me and took to flight and went on outside.”

[[v1-39-16]]

^<<v1-39-16,16>>^ After that she kept his garment laid up beside her until his master came to his house.

[[v1-39-17]]

^<<v1-39-17,17>>^ Then she spoke to him according to these words, saying: “The Hebrew servant whom you brought to us came to me to make me a laughingstock.^&#42;1^

[NOTE]
====
. LXX adds: “and he said to me, ‘I am going to cohabit with you.’ ”
====

[[v1-39-18]]

^<<v1-39-18,18>>^ But it followed that as soon as I raised my voice and began to cry out, he then left his garment beside me and went fleeing outside.”

[[v1-39-19]]

^<<v1-39-19,19>>^ The result was that as soon as his master heard the words of his wife which she spoke to him, saying: “Like this and this your servant did to me,” his anger blazed.

[[v1-39-20]]

^<<v1-39-20,20>>^ So Joseph’s master took him and gave him over to the prison house,^&#42;1^ the place where the prisoners^&#42;2^ of the king were kept under arrest,^&#42;3^ and he continued there in the prison house.

[NOTE]
====
. Lit., “house of the [round] castle.”
. Lit., “bound ones.”
. Lit., “were kept bound.”
====

[[v1-39-21]]

^<<v1-39-21,21>>^ However, Jehovah continued with Joseph and kept extending loving-kindness to him and granting him to find favor in the eyes of the chief officer^&#42;1^ of the prison house.

[NOTE]
====
. Or, “the prince.” Heb., sar.
====

[[v1-39-22]]

^<<v1-39-22,22>>^ So the chief officer of the prison house gave over into Joseph’s hand all the prisoners who were in the prison house; and everything that they were doing there he proved to be the one having it done.

[[v1-39-23]]

^<<v1-39-23,23>>^ The chief officer of the prison house was looking after absolutely nothing that was in his hand, because Jehovah was with &#91;Joseph&#93;^&#42;1^ and what he was doing Jehovah was making it turn out successful.

[NOTE]
====
. Lit., “him.”
====

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]