include::./index.adoc[]

[[v1-49-0]]
=== Genesis, 49
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-49-1]]

^<<v1-49-1,1>>^ Later on Jacob called his sons and said: “Gather yourselves together that I may tell YOU what will happen to YOU in the final part of the days.

[[v1-49-2]]

^<<v1-49-2,2>>^ Assemble yourselves and listen, YOU sons of Jacob, yes, listen to Israel YOUR father.

[[v1-49-3]]

^<<v1-49-3,3>>^ “Reuʹben, you are my firstborn, my vigor and the beginning of my generative power, the excellence of dignity and the excellence of strength.

[[v1-49-4]]

^<<v1-49-4,4>>^ With reckless license like waters,^&#42;1^ do not you excel, because you have gone up to your father’s bed. At that time you profaned my lounge. He went up to it!

[NOTE]
====
. Or, “There was reckless license like impetuous waters.”
====

[[v1-49-5]]

^<<v1-49-5,5>>^ “Simʹe·on and Leʹvi are brothers.^&#42;1^ Instruments of violence are their slaughter weapons.^&#42;2^

[NOTE]
====
. “Eagle owls; hye­nas,” according to another vowel pointing.
. “Slaughter weapons.” Some view the Heb. word here as yet unexplainable. Vs 5 in LXX, “Simeon and Levi, brothers, accomplished the injustice of their cutting off.”
====

[[v1-49-6]]

^<<v1-49-6,6>>^ Into their intimate group do not come, O my soul. With their congregation do not become united, O my disposition,^&#42;1^ because in their anger they killed men,^&#42;2^ and in their arbitrariness they hamstrung bulls.

[NOTE]
====
. “My glory,” MVg; LXX, “my liver.” See VT, Vol. II, 1952, pp. 358-362.
. Or, “a man.” Heb., ʼish, possibly in the collective sense.
====

[[v1-49-7]]

^<<v1-49-7,7>>^ Cursed be their anger, because it is cruel, and their fury, because it acts harshly. Let me parcel them out in Jacob and let me scatter them in Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ “As for you, Judah, your brothers will laud you. Your hand will be on the back of the neck of your enemies. The sons of your father will prostrate themselves to you.

[[v1-49-9]]

^<<v1-49-9,9>>^ A lion cub Judah is. From the prey, my son, you will certainly go up. He bowed down, he stretched himself out like a lion^&#42;1^ and, like a lion,^&#42;2^ who dares rouse him?

[NOTE]
====
. “Like a lion.” Heb., keʼar·yehʹ, the African lion.
. “And, like a lion.” Heb., u·khela·viʼʹ, the Asian lion.
====

[[v1-49-10]]

^<<v1-49-10,10>>^ The scepter^&#42;1^ will not turn aside from Judah, neither the commander’s staff^&#42;2^ from between his feet,^&#42;3^ until Shiʹloh^&#42;4^ comes; and to him the obedience of the peoples will belong.^&#42;5^

[NOTE]
====
. “Scepter.” Heb., sheʹvet; Lat., scepʹtrum; Gr., arʹkhon, “ruler.”
. Or, “neither a commander.” Heb., loʼ . . . u·mecho·qeqʹ.
. Or, “from before him.” Compare Jg 5:27.
. “Shiloh.” Or, “the one whose it is.” Heb., Shi·lohʹ, meaning “He Whose It Is,” or, “He to Whom It Belongs”; LXX, “the things stored up for him”; Vg, “he who is to be sent.”
. “And he will be the expectation of nations,” LXXVg.
====

[[v1-49-11]]

^<<v1-49-11,11>>^ Tying his full-grown ass to a vine and the descendant of his own she-ass to a choice vine,^&#42;1^ he will certainly wash his clothing in wine and his garment in the blood of grapes.

[NOTE]
====
. Or, “a vine with bright-red grapes.”
====

[[v1-49-12]]

^<<v1-49-12,12>>^ Dark red are his eyes from wine, and the whiteness of his teeth is from milk.

[[v1-49-13]]

^<<v1-49-13,13>>^ “Zebʹu·lun will reside by the seashore, and he will be by the shore where the ships lie anchored;^&#42;1^ and his remote side will be toward Siʹdon.

[NOTE]
====
. Or, “the ships disembark.”
====

[[v1-49-14]]

^<<v1-49-14,14>>^ “Isʹsa·char is a strong-boned ass, lying down between the two saddlebags.

[[v1-49-15]]

^<<v1-49-15,15>>^ And he will see that the resting-place is good and that the land is pleasant; and he will bend down his shoulder to bear burdens and he will become subject to slavish forced labor.^&#42;1^

[NOTE]
====
. Or, “become a slave under forced labor.”
====

[[v1-49-16]]

^<<v1-49-16,16>>^ “Dan will judge his people as one of the tribes of Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Let Dan prove to be a serpent by the roadside, a horned snake at the wayside, that bites the heels of the horse so that its rider falls backward.

[[v1-49-18]]

^<<v1-49-18,18>>^ I shall indeed wait^&#42;1^ for salvation from you,^&#42;2^ O Jehovah.

[NOTE]
====
. Or, “I have waited.”
. “For salvation from you.” Heb., li·shu·ʽoth·khaʹ; the first occurrence of this noun. The Heb. word yeshu·ʽahʹ, “salvation,” has the same root as the Bible names Jeshua, Joshua and Jesus.
====

[[v1-49-19]]

^<<v1-49-19,19>>^ “As for Gad, a marauder band will raid him, but he will raid the extreme rear.

[[v1-49-20]]

^<<v1-49-20,20>>^ “Out of Ashʹer his bread will be fat, and he will give the dainties of a king.

[[v1-49-21]]

^<<v1-49-21,21>>^ “Naphʹta·li is a slender^&#42;1^ hind. He is giving words of elegance.^&#42;2^

[NOTE]
====
. Or, “nimble.”
. Or, “He is putting forth branched ant­lers.”
====

[[v1-49-22]]

^<<v1-49-22,22>>^ “Offshoot^&#42;1^ of a fruit-bearing tree, Joseph is the offshoot of a fruit-bearing tree by the fountain, that propels its branches^&#42;2^ up over a wall.

[NOTE]
====
. Lit., “Son.”
. Lit., “daughters.”
====

[[v1-49-23]]

^<<v1-49-23,23>>^ But the archers kept harassing him and shot at him and kept harboring animosity against him.

[[v1-49-24]]

^<<v1-49-24,24>>^ And yet his bow was dwelling in a permanent place, and the strength^&#42;1^ of his hands was supple.^&#42;2^ From the hands of the powerful one of Jacob, from there is the shepherd, the stone of Israel.

[NOTE]
====
. Lit., “the arms.”
. Or, “agile.”
====

[[v1-49-25]]

^<<v1-49-25,25>>^ He is from the God^&#42;1^ of your father, and he will help you; and he is with the Almighty, and he will bless you with the blessings of the heavens above, with the blessings of the watery deep^&#42;2^ lying down below, with the blessings of the breasts and womb.

[NOTE]
====
. “From the God of.” Heb., me·ʼElʹ.
. Or, “surging waters.” Vg, “abyss,” as in 1:2.
====

[[v1-49-26]]

^<<v1-49-26,26>>^ The blessings of your father will indeed be superior to the blessings of the eternal mountains, to the ornament^&#42;1^ of the indefinitely lasting hills. They will continue upon the head of Joseph, even upon the crown of the head of the one singled out^&#42;2^ from his brothers.

[NOTE]
====
. Or, “desire; abode.”
. “One singled out.” Heb., nezirʹ; in Nu 6:2, 13, 18-20 translated “Nazirite,” meaning “One Singled Out; Dedicated One; Separated One.”
====

[[v1-49-27]]

^<<v1-49-27,27>>^ “Benjamin will keep on tearing like a wolf. In the morning he will eat the animal seized and at evening he will divide spoil.”

[[v1-49-28]]

^<<v1-49-28,28>>^ All these are the twelve tribes of Israel, and this is what their father spoke to them when he was blessing them. He blessed them each one according to his own blessing.

[[v1-49-29]]

^<<v1-49-29,29>>^ After that he commanded them and said to them: “I am being gathered to my people. Bury me with my fathers in the cave that is in the field of Eʹphron the Hitʹtite,

[[v1-49-30]]

^<<v1-49-30,30>>^ in the cave that is in the field of Mach·peʹlah that is in front of Mamʹre in the land of Caʹnaan, the field that Abraham purchased from Eʹphron the Hitʹtite for the possession of a burial place.

[[v1-49-31]]

^<<v1-49-31,31>>^ There they buried Abraham and Sarah his wife. There they buried Isaac and Re·bekʹah his wife, and there I buried Leʹah.

[[v1-49-32]]

^<<v1-49-32,32>>^ The field purchased^&#42;1^ and the cave that is in it were from the sons of Heth.”

[NOTE]
====
. Lit., “The purchase of the field.”
====

[[v1-49-33]]

^<<v1-49-33,33>>^ Thus Jacob finished giving commands to his sons. Then he gathered his feet up onto the couch and expired and was gathered to his people.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]