include::./index.adoc[]

[[v1-48-0]]
=== Genesis, 48
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-48-1]]

^<<v1-48-1,1>>^ And it came about after these things that it was said to Joseph: “Look, your father is becoming weak.” At that he took with him his two sons Ma·nasʹseh and Eʹphra·im.

[[v1-48-2]]

^<<v1-48-2,2>>^ Then it was reported to Jacob and said: “Here your son Joseph has come to you.” So Israel exerted his strength and sat up on his couch.

[[v1-48-3]]

^<<v1-48-3,3>>^ And Jacob proceeded to say to Joseph:
“God Almighty^&#42;1^ appeared to me at Luz in the land of Caʹnaan that he might bless me.

[NOTE]
====
. See 43:14 ftn.
====

[[v1-48-4]]

^<<v1-48-4,4>>^ And he went on to say to me, ‘Here I am making you fruitful, and I will make you many and I will transform you into a congregation of peoples and I will give this land to your seed after you for a possession to time indefinite.’

[[v1-48-5]]

^<<v1-48-5,5>>^ And now your two sons who were born to you in the land of Egypt before I came here to you into Egypt, they are mine. Eʹphra·im and Ma·nasʹseh will become mine like Reuʹben and Simʹe·on.

[[v1-48-6]]

^<<v1-48-6,6>>^ But your progeny to which you shall^&#42;1^ become father after them will become yours. Together with the name of their brothers they will be called in their inheritance.

[NOTE]
====
. Or, “have.”
====

[[v1-48-7]]

^<<v1-48-7,7>>^ And as for me, when I was coming from Padʹdan, Rachel died alongside me in the land of Caʹnaan on the way while there was yet a good stretch of land before coming to Ephʹrath, so that I buried her there on the way to Ephʹrath, that is to say, Bethʹle·hem.”

[[v1-48-8]]

^<<v1-48-8,8>>^ Then Israel saw Joseph’s sons and said: “Who are these?”

[[v1-48-9]]

^<<v1-48-9,9>>^ So Joseph said to his father: “They are my sons whom God has given me in this place.” At this he said: “Bring them, please, to me that I may bless them.”

[[v1-48-10]]

^<<v1-48-10,10>>^ Now the eyes of Israel were dull from old age. He was unable to see. Accordingly he brought them close to him, and he then kissed them and embraced them.

[[v1-48-11]]

^<<v1-48-11,11>>^ And Israel went on to say to Joseph: “I had no idea of seeing your face, but here God has let me see also your offspring.”

[[v1-48-12]]

^<<v1-48-12,12>>^ After that Joseph brought them out away from his knees, and he bowed down with his face to the earth.

[[v1-48-13]]

^<<v1-48-13,13>>^ Joseph now took the two of them, Eʹphra·im by his right hand to Israel’s left, and Ma·nasʹseh by his left hand to Israel’s right, and brought them close to him.

[[v1-48-14]]

^<<v1-48-14,14>>^ However, Israel put out his right hand and placed it on Eʹphra·im’s head, although he was the younger, and his left hand upon Ma·nasʹseh’s head. He purposely laid his hands so,^&#42;1^ since Ma·nasʹseh was the firstborn.

[NOTE]
====
. Or, “He laid his hands crosswise,” in agreement with LXXVg.
====

[[v1-48-15]]

^<<v1-48-15,15>>^ And he proceeded to bless Joseph and to say:
“The &#91;true&#93; God before whom my fathers Abraham and Isaac walked,
The &#91;true&#93; God who has been shepherding me during all my existence until this day,

[[v1-48-16]]

^<<v1-48-16,16>>^ The angel who has been recovering^&#42;1^ me from all calamity, bless the boys.
And let my name be called upon them and the name of my fathers, Abraham and Isaac,
And let them increase to a multitude in the midst of the earth.”

[NOTE]
====
. Or, “redeeming; reclaiming.”
====

[[v1-48-17]]

^<<v1-48-17,17>>^ When Joseph saw that his father kept his right hand placed on Eʹphra·im’s head, it was displeasing to him, and he tried to take hold of his father’s hand to remove it from Eʹphra·im’s head to Ma·nasʹseh’s head.

[[v1-48-18]]

^<<v1-48-18,18>>^ Hence Joseph said to his father: “Not so, my father, because this is the firstborn. Put your right hand on his head.”

[[v1-48-19]]

^<<v1-48-19,19>>^ But his father kept refusing and said: “I know it, my son, I know it. He too will become a people and he too will become great. But, just the same, his younger brother will become greater than he will, and his offspring will become the full equivalent^&#42;1^ of nations.”

[NOTE]
====
. Or, “the full number.” Lit., “the fullness.”
====

[[v1-48-20]]

^<<v1-48-20,20>>^ And he continued to bless them on that day, saying:
“By means of you^&#42;1^ let Israel repeatedly pronounce blessing, saying,
‘May God constitute you like Eʹphra·im and like Ma·nasʹseh.’”
Thus he kept putting Eʹphra·im before Ma·nasʹseh.

[NOTE]
====
. “You,” sing., MSamSyVg; TPLXX, “you,” pl.
====

[[v1-48-21]]

^<<v1-48-21,21>>^ After that Israel said to Joseph: “Look, I am dying, but God will certainly continue with YOU people and return YOU to the land of YOUR forefathers.

[[v1-48-22]]

^<<v1-48-22,22>>^ As for me, I do give you one shoulder &#91;of land&#93; more than to your brothers, which I took from the hand of the Amʹor·ites by my sword and by my bow.”

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]