include::./index.adoc[]

[[v1-28-0]]
=== Genesis, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-28-1]]

^<<v1-28-1,1>>^ Consequently Isaac called Jacob and blessed him and commanded him and said to him: “You must not take a wife from the daughters of Caʹnaan.^&#42;1^

[NOTE]
====
. Or, “the Canaanites.”
====

[[v1-28-2]]

^<<v1-28-2,2>>^ Get up, go to Padʹdan-aʹram^&#42;1^ to the house of Be·thuʹel the father of your mother and from there take yourself a wife from the daughters of Laʹban the brother of your mother.

[NOTE]
====
. See 25:20 ftn, “Paddan-aram.”
====

[[v1-28-3]]

^<<v1-28-3,3>>^ And God Almighty will bless you and make you fruitful and multiply you, and you will certainly become a congregation of peoples.

[[v1-28-4]]

^<<v1-28-4,4>>^ And he will give to you the blessing of Abraham, to you and to your seed with you, that you may take possession of the land of your alien residences, which God has given to Abraham.”

[[v1-28-5]]

^<<v1-28-5,5>>^ So Isaac sent Jacob away, and he struck out for Padʹdan-aʹram, for Laʹban the son of Be·thuʹel the Syrian,^&#42;1^ the brother of Re·bekʹah, mother of Jacob and Eʹsau.^&#42;2^

[NOTE]
====
. Lit., “the Aramaean.”
. “Jacob and Esau.” Jacob is put before his older twin brother, Esau, denoting preference.
====

[[v1-28-6]]

^<<v1-28-6,6>>^ When Eʹsau saw that Isaac had blessed Jacob and had sent him away to Padʹdan-aʹram to take from there a wife for himself, and that when he blessed him he laid the command upon him, saying: “Do not take a wife from the daughters of Caʹnaan”;

[[v1-28-7]]

^<<v1-28-7,7>>^ and that Jacob was obeying his father and his mother and was on his way to Padʹdan-aʹram;

[[v1-28-8]]

^<<v1-28-8,8>>^ then Eʹsau saw that the daughters of Caʹnaan were displeasing^&#42;1^ in the eyes of Isaac his father.

[NOTE]
====
. Or, “bad; evil.”
====

[[v1-28-9]]

^<<v1-28-9,9>>^ Hence Eʹsau went to Ishʹma·el^&#42;1^ and took as wife Maʹha·lath the daughter of Ishʹma·el the son of Abraham, the sister of Ne·baʹioth, besides his other wives.

[NOTE]
====
. Or, “the Ishmaelites.” By now Ishmael himself was dead and Esau was about 77 years old. See 25:17, 26.
====

[[v1-28-10]]

^<<v1-28-10,10>>^ And Jacob continued on his way out from Beʹer-sheʹba and kept going to Haʹran.

[[v1-28-11]]

^<<v1-28-11,11>>^ In time he came across a place and set about spending the night there because the sun had set. So he took one of the stones of the place and set it as his head supporter^&#42;1^ and lay down in that place.

[NOTE]
====
. Or, “his pillow.”
====

[[v1-28-12]]

^<<v1-28-12,12>>^ And he began to dream, and, look! there was a ladder^&#42;1^ stationed upon the earth and its top reaching up to the heavens; and, look! there were God’s angels ascending and descending on it.

[NOTE]
====
. Or, “rising flight of stones.”
====

[[v1-28-13]]

^<<v1-28-13,13>>^ And, look! there was Jehovah stationed above it, and he proceeded to say:
“I am Jehovah the God of Abraham your father and the God of Isaac. The land upon which you are lying, to you I am going to give it and to your seed.

[[v1-28-14]]

^<<v1-28-14,14>>^ And your seed will certainly become like the dust particles of the earth, and you will certainly spread abroad to the west and to the east and to the north and to the south, and by means of you and by means of your seed all the families of the ground will certainly bless themselves.^&#42;1^

[NOTE]
====
. “Will be blessed,” LXXVg. See 22:18 ftn.
====

[[v1-28-15]]

^<<v1-28-15,15>>^ And here I am with you and I will keep you in all the way you are going and I will return you to this ground, because I am not going to leave you until I have actually done what I have spoken to you.”

[[v1-28-16]]

^<<v1-28-16,16>>^ Then Jacob awoke from his sleep and said: “Truly Jehovah is in this place and I myself did not know it.”

[[v1-28-17]]

^<<v1-28-17,17>>^ And he grew fearful and added: “How fear-inspiring this place is! This is nothing else but the house of God and this is the gate of the heavens.”

[[v1-28-18]]

^<<v1-28-18,18>>^ So Jacob got up early in the morning and took the stone that was there as his head supporter and he set it up as a pillar and poured oil on the top of it.

[[v1-28-19]]

^<<v1-28-19,19>>^ Further, he called the name of that place Bethʹel;^&#42;1^ but the fact is, Luz was the city’s name formerly.

[NOTE]
====
. Meaning “House of God.” Heb., Behth-ʼElʹ.
====

[[v1-28-20]]

^<<v1-28-20,20>>^ And Jacob went on to vow a vow, saying: “If God will continue with me and will certainly keep me on this way on which I am going and will certainly give me bread to eat and garments to wear

[[v1-28-21]]

^<<v1-28-21,21>>^ and I shall certainly return in peace to the house of my father, then Jehovah will have proved to be my God.^&#42;1^

[NOTE]
====
. Or, “God to me.” Heb., li lEʼ·lo·himʹ.
====

[[v1-28-22]]

^<<v1-28-22,22>>^ And this stone that I have set up as a pillar will become a house of God, and as for everything that you will give me I shall without fail give the tenth of it to you.”

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]