include::./index.adoc[]

[[v1-45-0]]
=== Genesis, 45
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-45-1]]

^<<v1-45-1,1>>^ At this Joseph was no longer able to control himself before all those who were stationed by him. So he cried out: “HAVE everybody go out from me!” And no one else stood with him while Joseph made himself known to his brothers.

[[v1-45-2]]

^<<v1-45-2,2>>^ And he began to raise his voice in weeping, so that the Egyptians got to hear it and Pharʹaoh’s house got to hear it.

[[v1-45-3]]

^<<v1-45-3,3>>^ Finally Joseph said to his brothers: “I am Joseph. Is my father still alive?” But his brothers were unable to answer him at all, because they were disturbed by reason of him.

[[v1-45-4]]

^<<v1-45-4,4>>^ So Joseph said to his brothers: “Come close to me, please.” With that they came close to him.
Then he said: “I am Joseph YOUR brother, whom YOU sold into Egypt.

[[v1-45-5]]

^<<v1-45-5,5>>^ But now do not feel hurt and do not be angry with yourselves because YOU sold me here; because for the preservation of life God has sent me ahead of YOU.

[[v1-45-6]]

^<<v1-45-6,6>>^ For this is the second year of the famine in the midst of the earth, and there are yet five years in which there will be no plowing time or harvest.

[[v1-45-7]]

^<<v1-45-7,7>>^ Consequently God sent me ahead of YOU in order to place a remnant^&#42;1^ for YOU men in the earth and to keep YOU alive by a great escape.

[NOTE]
====
. Or, “survivors; a remainder.” Heb., sheʼe·rithʹ.
====

[[v1-45-8]]

^<<v1-45-8,8>>^ So now it was not YOU who sent me here, but it was the &#91;true&#93; God, that he might appoint me a father to Pharʹaoh and a lord for all his house and as one dominating over all the land of Egypt.

[[v1-45-9]]

^<<v1-45-9,9>>^ “Go up quickly to my father, and YOU must say to him, ‘This is what your son Joseph has said: “God has appointed me lord for all Egypt. Come down to me. Do not delay.

[[v1-45-10]]

^<<v1-45-10,10>>^ And you must dwell in the land of Goʹshen, and you must continue near me, you and your sons and the sons of your sons and your flocks and your herds and everything you have.

[[v1-45-11]]

^<<v1-45-11,11>>^ And I will supply you with food there, for there are yet five years of famine; for fear you and your house and everything you have may come to poverty.”’

[[v1-45-12]]

^<<v1-45-12,12>>^ And here YOUR eyes and the eyes of my brother Benjamin are seeing that it is my mouth that is speaking to YOU.

[[v1-45-13]]

^<<v1-45-13,13>>^ So YOU must tell my father about all my glory in Egypt and everything YOU have seen; and YOU must hurry and bring my father down here.”

[[v1-45-14]]

^<<v1-45-14,14>>^ Then he fell upon the neck of Benjamin his brother and gave way to weeping, and Benjamin wept upon his neck.

[[v1-45-15]]

^<<v1-45-15,15>>^ And he proceeded to kiss all his brothers and to weep over them, and after that his brothers spoke with him.

[[v1-45-16]]

^<<v1-45-16,16>>^ And the news was heard at the house of Pharʹaoh, saying: “Joseph’s brothers have come!” And it proved to be good in the eyes of Pharʹaoh and of his servants.

[[v1-45-17]]

^<<v1-45-17,17>>^ Accordingly Pharʹaoh said to Joseph: “Say to your brothers, ‘Do this: Load YOUR beasts of burden and go enter the land of Caʹnaan,

[[v1-45-18]]

^<<v1-45-18,18>>^ and take YOUR father and YOUR households and come here to me, that I may give YOU the good of the land of Egypt; and eat the fat part of the land.

[[v1-45-19]]

^<<v1-45-19,19>>^ And you yourself are commanded:^&#42;1^ “Do this: TAKE for yourselves wagons from the land of Egypt for YOUR little ones and YOUR wives, and YOU must lift YOUR father on one and come here.

[NOTE]
====
. “Commanded,” that is, to say to them. LXX, “give orders.”
====

[[v1-45-20]]

^<<v1-45-20,20>>^ And do not let YOUR eye feel sorry over YOUR equipment, because the good of all the land of Egypt is YOURS.”’”

[[v1-45-21]]

^<<v1-45-21,21>>^ Following that the sons of Israel did so, and Joseph gave them wagons according to Pharʹaoh’s orders and gave them provisions for the way.

[[v1-45-22]]

^<<v1-45-22,22>>^ To each of them he gave individual changes of mantles, but to Benjamin he gave three hundred silver pieces and five changes of mantles.

[[v1-45-23]]

^<<v1-45-23,23>>^ And to his father he sent as follows: ten asses carrying good things of Egypt and ten she-asses carrying grain and bread and sustenance for his father for the way.

[[v1-45-24]]

^<<v1-45-24,24>>^ Thus he sent his brothers off, and they proceeded to go. However, he said to them: “Do not get exasperated at one another on the way.”

[[v1-45-25]]

^<<v1-45-25,25>>^ And they began going up out of Egypt and at length came into the land of Caʹnaan to Jacob their father.

[[v1-45-26]]

^<<v1-45-26,26>>^ Then they reported to him, saying: “Joseph is still alive, and he is the one dominating over all the land of Egypt!” But his heart grew numb, because he did not believe them.

[[v1-45-27]]

^<<v1-45-27,27>>^ When they went on speaking to him all of Joseph’s words that he had spoken to them and he got to see the wagons that Joseph had sent to carry him, the spirit of Jacob their father began to revive.

[[v1-45-28]]

^<<v1-45-28,28>>^ Then Israel exclaimed: “It is enough! Joseph my son is still alive! Ah, let me go and see him before I die!”

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]