include::./index.adoc[]

[[v1-32-0]]
=== Genesis, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-32-1]]

^<<v1-32-1,1>>^ And as for Jacob, he got on his way, and the angels^&#42;1^ of God now met up with him.

[NOTE]
====
. Or, “messengers,” as in vss 3, 6.
====

[[v1-32-2]]

^<<v1-32-2,2>>^ Immediately Jacob said, when he saw them: “The camp of God this is!” Hence he called the name of that place Ma·ha·naʹim.^&#42;1^

[NOTE]
====
. Meaning “Two Camps.”
====

[[v1-32-3]]

^<<v1-32-3,3>>^ Then Jacob sent messengers ahead of him to Eʹsau his brother to the land of Seʹir, the field of Eʹdom,

[[v1-32-4]]

^<<v1-32-4,4>>^ and he commanded them, saying: “This is what YOU will say to my lord, to Eʹsau, ‘This is what your servant Jacob has said: “With Laʹban I have resided as an alien and I have stayed for a long time till now.

[[v1-32-5]]

^<<v1-32-5,5>>^ And I have come to have bulls and asses, sheep, and menservants and maidservants, and I would like to send to notify my lord, that I may find favor in your eyes.”’”

[[v1-32-6]]

^<<v1-32-6,6>>^ In time the messengers returned to Jacob, saying: “We got to your brother Eʹsau, and he is also on his way to meet you, and four hundred men with him.”

[[v1-32-7]]

^<<v1-32-7,7>>^ And Jacob became very much afraid and grew anxious. So he divided the people who were with him, and the flocks and the cattle and the camels into two camps,

[[v1-32-8]]

^<<v1-32-8,8>>^ and he said: “If Eʹsau should come to the one camp and assault it, then there is certain to be a camp remaining to make an escape.”

[[v1-32-9]]

^<<v1-32-9,9>>^ After that Jacob said: “O God of my father Abraham and God of my father Isaac, O Jehovah, you who are saying to me, ‘Return to your land and to your relatives and I will deal well with you,’

[[v1-32-10]]

^<<v1-32-10,10>>^ I am unworthy of all the loving-kindnesses and of all the faithfulness^&#42;1^ that you have exercised toward your servant, for with but my staff I crossed this Jordan and now I have become two camps.

[NOTE]
====
. Or, “the truth.” Heb., ha·ʼemethʹ.
====

[[v1-32-11]]

^<<v1-32-11,11>>^ Deliver me, I pray you, from my brother’s hand, from Eʹsau’s hand, because I am afraid of him that he may come and certainly assault me, mother together with children.

[[v1-32-12]]

^<<v1-32-12,12>>^ And you, you have said, ‘Unquestionably I shall deal well with you and I will constitute your seed^&#42;1^ like the grains of sand of the sea, which cannot be numbered for multitude.’”

[NOTE]
====
. Or, “offspring; posterity.”
====

[[v1-32-13]]

^<<v1-32-13,13>>^ And he kept lodging there on that night. And from what came to his hand he proceeded to take a gift for Eʹsau his brother:

[[v1-32-14]]

^<<v1-32-14,14>>^ two hundred she-goats and twenty he-goats, two hundred female sheep and twenty rams,

[[v1-32-15]]

^<<v1-32-15,15>>^ thirty camels giving suck and their young ones, forty cows and ten bulls, twenty she-asses and ten full-grown asses.

[[v1-32-16]]

^<<v1-32-16,16>>^ Then he handed over to his servants one drove after another by itself and repeatedly said to his servants: “Cross over ahead of me, and YOU are to set an interval between drove and drove.”

[[v1-32-17]]

^<<v1-32-17,17>>^ Further he commanded the first one, saying: “In case that Eʹsau my brother should meet you and ask you, saying, ‘To whom do you belong, and where are you going and to whom do these ahead of you belong?’

[[v1-32-18]]

^<<v1-32-18,18>>^ then you must say, ‘To your servant, to Jacob. A gift it is, sent to my lord, to Eʹsau, and look! he himself is also behind us.’”

[[v1-32-19]]

^<<v1-32-19,19>>^ And he went on to command also the second, also the third, also all those following the droves, saying: “According to this word YOU are to speak to Eʹsau on YOUR encountering him.

[[v1-32-20]]

^<<v1-32-20,20>>^ And YOU must say also, ‘Here is your servant Jacob behind us.’” For he said to himself: “I may appease him by the gift going ahead of me, and afterward I shall see his face. Perhaps he will give a kindly reception.”

[[v1-32-21]]

^<<v1-32-21,21>>^ So the gift went crossing over ahead of him, but he himself lodged that night in the camp.

[[v1-32-22]]

^<<v1-32-22,22>>^ Later during that night he rose and took his two wives and his two maidservants and his eleven young sons and crossed over the ford of Jabʹbok.

[[v1-32-23]]

^<<v1-32-23,23>>^ So he took them and brought them over the torrent valley,^&#42;1^ and he brought over what he had.

[NOTE]
====
. Or, “the wadi; the arroyo; the stream [the wadi running with water].”
====

[[v1-32-24]]

^<<v1-32-24,24>>^ Finally Jacob was left by himself. Then a man began to grapple with him until the dawn ascended.

[[v1-32-25]]

^<<v1-32-25,25>>^ When he got to see that he had not prevailed over him, then he touched the socket of his thigh joint;^&#42;1^ and the socket of Jacob’s thigh joint got out of place during his grappling with him.

[NOTE]
====
. Or, “touched the hollow of his hip.”
====

[[v1-32-26]]

^<<v1-32-26,26>>^ After that he said: “Let me go,^&#42;1^ for the dawn has ascended.” To this he said: “I am not going to let you go until you first bless me.”

[NOTE]
====
. Lit., “Send me away.”
====

[[v1-32-27]]

^<<v1-32-27,27>>^ So he said to him: “What is your name?” to which he said: “Jacob.”

[[v1-32-28]]

^<<v1-32-28,28>>^ Then he said: “Your name will no longer be called Jacob but Israel,^&#42;1^ for you have contended^&#42;2^ with God and with men so that you at last prevailed.”

[NOTE]
====
. Meaning “God Contends; Contender (Perseverer) With God.” Heb., Yis·ra·ʼelʹ.
. Or, “persisted; exerted yourself; persevered,” according to BDB, p. 975.
====

[[v1-32-29]]

^<<v1-32-29,29>>^ In turn Jacob inquired and said: “Tell me, please, your name.” However, he said: “Why is it that you inquire for my name?” With that he blessed him there.

[[v1-32-30]]

^<<v1-32-30,30>>^ Hence Jacob called the name of the place Pe·niʹel,^&#42;1^ because, to quote him, “I have seen God face to face and yet my soul was delivered.”

[NOTE]
====
. Meaning “Face of God.” Heb., Peni·ʼelʹ.
====

[[v1-32-31]]

^<<v1-32-31,31>>^ And the sun began to flash upon him as soon as he passed by Pe·nuʹel, but he was limping upon his thigh.

[[v1-32-32]]

^<<v1-32-32,32>>^ That is why the sons of Israel are not accustomed to eat the sinew of the thigh nerve,^&#42;1^ which is on the socket of the thigh joint, down to this day, because he touched the socket of Jacob’s thigh joint by the sinew of the thigh nerve.

[NOTE]
====
. Or, “thigh vein.”
====

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]