include::./index.adoc[]

[[v1-19-0]]
=== Genesis, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-19-1]]

^<<v1-19-1,1>>^ Now the two angels arrived at Sodʹom by evening, and Lot was sitting in the gate of Sodʹom. When Lot caught sight of them, then he got up to meet them and bowed down with his face to the earth.

[[v1-19-2]]

^<<v1-19-2,2>>^ And he proceeded to say: “Please, now, my lords, turn aside, please, into the house of YOUR servant and stay overnight and have YOUR feet washed. Then YOU must get up early and travel on YOUR way.” To this they said: “No, but in the public square is where we shall stay overnight.”

[[v1-19-3]]

^<<v1-19-3,3>>^ But he was very insistent with them, so that they turned aside to him and came into his house. Then he made a feast for them, and he baked unfermented cakes, and they went to eating.

[[v1-19-4]]

^<<v1-19-4,4>>^ Before they could lie down, the men of the city, the men of Sodʹom, surrounded the house, from boy to old man, all the people in one mob.^&#42;1^

[NOTE]
====
. Or, “from every quarter.”
====

[[v1-19-5]]

^<<v1-19-5,5>>^ And they kept calling out to Lot and saying to him: “Where are the men who came in to you tonight? Bring them out to us that we may have intercourse with them.”

[[v1-19-6]]

^<<v1-19-6,6>>^ Finally Lot went out to them to the entrance, but he shut the door behind him.

[[v1-19-7]]

^<<v1-19-7,7>>^ Then he said: “Please, my brothers, do not act badly.

[[v1-19-8]]

^<<v1-19-8,8>>^ Please, here I have two daughters who have never had intercourse with a man. Please, let me bring them out to YOU. Then do to them as is good in YOUR eyes. Only to these men do not do a thing, because that is why they have come under the shadow of my roof.”

[[v1-19-9]]

^<<v1-19-9,9>>^ At this they said: “Stand back there!” And they added: “This lone man came here to reside as an alien and yet he would actually play the judge. Now we are going to do worse to you than to them.” And they came pressing heavily in on the man, on Lot, and were getting near to break in the door.

[[v1-19-10]]

^<<v1-19-10,10>>^ So the men thrust out their hands and brought Lot in to them, into the house, and they shut the door.

[[v1-19-11]]

^<<v1-19-11,11>>^ But they struck with blindness the men who were at the entrance of the house, from the least to the greatest, so that they were wearing themselves out trying to find the entrance.

[[v1-19-12]]

^<<v1-19-12,12>>^ Then the men said to Lot: “Do you have anyone else here? Son-in-law and your sons and your daughters and all who are yours in the city, bring out of the place!

[[v1-19-13]]

^<<v1-19-13,13>>^ For we are bringing this place to ruin, because the outcry against them has grown loud before Jehovah, so that Jehovah sent us to bring the city^&#42;1^ to ruin.”

[NOTE]
====
. Lit., “it,” fem., referring to the “city,” fem.
====

[[v1-19-14]]

^<<v1-19-14,14>>^ Hence Lot went on out and began to speak to his sons-in-law who were to take^&#42;1^ his daughters, and he kept on saying: “Get up! Get out of this place, because Jehovah is bringing the city to ruin!” But in the eyes of his sons-in-law he seemed like a man who was joking.

[NOTE]
====
. Or, “who were intending to take.”
====

[[v1-19-15]]

^<<v1-19-15,15>>^ However, when the dawn ascended, then the angels became urgent with Lot, saying: “Get up! Take your wife and your two daughters who are found here, for fear you may be swept away in the error of the city!”

[[v1-19-16]]

^<<v1-19-16,16>>^ When he kept lingering, then in the compassion of Jehovah upon him, the men seized hold of his hand and of the hand of his wife and of the hands of his two daughters and they proceeded to bring him out and to station him outside the city.

[[v1-19-17]]

^<<v1-19-17,17>>^ And it came about that, as soon as they had brought them forth to the outskirts, he^&#42;1^ began to say: “Escape for your soul! Do not look behind you and do not stand still in all the District!^&#42;2^ Escape to the mountainous region for fear you may be swept away!”

[NOTE]
====
. “They,” LXXSyVgc.
. Or, “the Basin.” See 13:10 ftn, “District.”
====

[[v1-19-18]]

^<<v1-19-18,18>>^ Then Lot said to them: “Not that, please, Jehovah!^&#42;1^

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v1-19-19]]

^<<v1-19-19,19>>^ Please, now, your servant has found favor in your eyes so that you are magnifying your loving-kindness,^&#42;1^ which you have exercised with me to preserve my soul alive, but I—I am not able to escape to the mountainous region for fear calamity may keep close to me and I certainly die.

[NOTE]
====
. Or, “your loyal love.” Heb., chas·dekhaʹ.
====

[[v1-19-20]]

^<<v1-19-20,20>>^ Please, now, this city is nearby to flee there and it is a small thing. May I, please, escape there—is it not a small thing?—and my soul will live on.”

[[v1-19-21]]

^<<v1-19-21,21>>^ So he said to him: “Here I do show you consideration to this extent^&#42;1^ also, by my not overthrowing the city of which you have spoken.

[NOTE]
====
. Or, “consideration in this thing.”
====

[[v1-19-22]]

^<<v1-19-22,22>>^ Hurry! Escape there, because I am not able to do a thing until your arriving there!” That is why he called the name of the city Zoʹar.^&#42;1^

[NOTE]
====
. Meaning “Smallness.”
====

[[v1-19-23]]

^<<v1-19-23,23>>^ The sun had gone forth over the land when Lot arrived at Zoʹar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Then Jehovah made it rain sulphur and fire from Jehovah, from the heavens, upon Sodʹom and upon Go·morʹrah.

[[v1-19-25]]

^<<v1-19-25,25>>^ So he went ahead overthrowing these cities, even the entire District and all the inhabitants of the cities and the plants of the ground.

[[v1-19-26]]

^<<v1-19-26,26>>^ And his wife began to look around from behind him,^&#42;1^ and she became a pillar of salt.

[NOTE]
====
. “Look behind her,” SyVg.
====

[[v1-19-27]]

^<<v1-19-27,27>>^ Now Abraham made his way early in the morning to the place where he had stood before Jehovah.

[[v1-19-28]]

^<<v1-19-28,28>>^ Then he looked down toward Sodʹom and Go·morʹrah and toward all the land of the District and saw a sight. Why, here thick smoke ascended from the land like the thick smoke of a kiln!

[[v1-19-29]]

^<<v1-19-29,29>>^ And it came about that when God brought the cities of the District to ruin God kept Abraham in mind in that he took steps to send Lot out of the midst of the overthrow when overthrowing the cities among which Lot had been dwelling.

[[v1-19-30]]

^<<v1-19-30,30>>^ Later Lot went up from Zoʹar and began dwelling in the mountainous region, and his two daughters along with him, because he got afraid of dwelling in Zoʹar. So he began dwelling in a cave, he and his two daughters.

[[v1-19-31]]

^<<v1-19-31,31>>^ And the firstborn proceeded to say to the younger woman: “Our father is old and there is not a man in the land to have relations with us according to the way of the whole earth.

[[v1-19-32]]

^<<v1-19-32,32>>^ Come, let us give our father wine to drink and let us lie down with him and preserve offspring from our father.”

[[v1-19-33]]

^<<v1-19-33,33>>^ So they kept giving their father wine to drink during that night; then the firstborn went in and lay down with her father, but he did not know when she lay down and when she got up.^&#42;1^

[NOTE]
====
. “And when she got up.” In M the expression thus translated is marked with extraordinary points by the Sopherim to call attention to the original Heb. reading, “but he did know when she got up.” See App 2A.
====

[[v1-19-34]]

^<<v1-19-34,34>>^ And it came about on the next day that the firstborn then said to the younger: “Here I lay down with my father last night. Let us give him wine to drink tonight also. Then you go in, lie down with him, and let us preserve offspring from our father.”

[[v1-19-35]]

^<<v1-19-35,35>>^ So they repeatedly gave their father wine to drink during that night also; then the younger got up and lay down with him, but he did not know when she lay down and when she got up.

[[v1-19-36]]

^<<v1-19-36,36>>^ And both the daughters of Lot became pregnant from their father.

[[v1-19-37]]

^<<v1-19-37,37>>^ In time the firstborn became mother to a son and called his name Moʹab.^&#42;1^ He is the father of Moʹab, to this day.

[NOTE]
====
. Meaning “From Father.” Heb., Moh·ʼavʹ. LXX adds, “saying, ‘From my father.’ ”
====

[[v1-19-38]]

^<<v1-19-38,38>>^ As for the younger, she too gave birth to a son and then called his name Ben-amʹmi.^&#42;1^ He is the father of the sons of Amʹmon, to this day.

[NOTE]
====
. Meaning “Son of My People,” that is, son of my relatives; not of foreigners like the Sodomites. Heb., Ben-ʽam·miʹ.
====

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]