include::./index.adoc[]

[[v1-9-0]]
=== Genesis, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-9-1]]

^<<v1-9-1,1>>^ And God went on to bless Noah and his sons and to say to them: “Be fruitful and become many and fill the earth.

[[v1-9-2]]

^<<v1-9-2,2>>^ And a fear of YOU and a terror of YOU will continue upon every living creature of the earth and upon every flying creature of the heavens, upon everything that goes moving on the ground, and upon all the fishes of the sea. Into YOUR hand they are now given.

[[v1-9-3]]

^<<v1-9-3,3>>^ Every moving animal that is alive may serve as food for YOU. As in the case of green vegetation, I do give it all to YOU.

[[v1-9-4]]

^<<v1-9-4,4>>^ Only flesh with its soul^&#42;1^—its blood—YOU must not eat.

[NOTE]
====
. Or, “life.” See 1:30 ftn.
====

[[v1-9-5]]

^<<v1-9-5,5>>^ And, besides that, YOUR blood of YOUR souls^&#42;1^ shall I ask back. From the hand of every living creature shall I ask it back; and from the hand of man,^&#42;2^ from the hand of each one^&#42;3^ who is his brother, shall I ask back the soul^&#42;4^ of man.

[NOTE]
====
. Or, “lives.”
. Or, “mankind.” Heb., ha·ʼa·dhamʹ.
. Lit., “a man.” Heb., ʼish.
. Heb., neʹphesh, as in 2:7; Gr., psy·khenʹ.
====

[[v1-9-6]]

^<<v1-9-6,6>>^ Anyone shedding man’s blood, by man will his own blood be shed, for in God’s image he made man.

[[v1-9-7]]

^<<v1-9-7,7>>^ And as for YOU men, be fruitful and become many, make the earth swarm with YOU and become many in it.”

[[v1-9-8]]

^<<v1-9-8,8>>^ And God went on to say to Noah and to his sons with him:

[[v1-9-9]]

^<<v1-9-9,9>>^ “And as for me, here I am establishing my covenant with YOU men and with YOUR offspring^&#42;1^ after YOU,

[NOTE]
====
. Lit., “seed.”
====

[[v1-9-10]]

^<<v1-9-10,10>>^ and with every living soul that is with YOU, among fowls, among beasts and among all living creatures of the earth with YOU, from all those going out of the ark to every living creature of the earth.

[[v1-9-11]]

^<<v1-9-11,11>>^ Yes, I do establish my covenant with YOU: No more will all flesh be cut off by waters of a deluge, and no more will there occur a deluge to bring the earth to ruin.”

[[v1-9-12]]

^<<v1-9-12,12>>^ And God added: “This is the sign of the covenant that I am giving between me and YOU and every living soul that is with YOU, for the generations to time indefinite.

[[v1-9-13]]

^<<v1-9-13,13>>^ My rainbow I do give^&#42;1^ in the cloud, and it must serve as a sign of the covenant between me and the earth.

[NOTE]
====
. Or, “I will certainly give.”
====

[[v1-9-14]]

^<<v1-9-14,14>>^ And it shall occur that when I bring a cloud over the earth, then the rainbow will certainly appear in the cloud.

[[v1-9-15]]

^<<v1-9-15,15>>^ And I shall certainly remember my covenant which is between me and YOU and every living soul among all flesh; and no more will the waters become a deluge to bring all flesh to ruin.

[[v1-9-16]]

^<<v1-9-16,16>>^ And the rainbow must occur in the cloud, and I shall certainly see it to remember the covenant to time indefinite between God and every living soul among all flesh that is upon the earth.”

[[v1-9-17]]

^<<v1-9-17,17>>^ And God repeated to Noah: “This is the sign of the covenant that I do establish between me and all flesh that is upon the earth.”

[[v1-9-18]]

^<<v1-9-18,18>>^ And Noah’s sons who came out of the ark were Shem and Ham and Jaʹpheth. Later Ham was the father of Caʹnaan.

[[v1-9-19]]

^<<v1-9-19,19>>^ These three were Noah’s sons, and from these was all the earth’s population^&#42;1^ spread abroad.

[NOTE]
====
. Lit., “all the earth.”
====

[[v1-9-20]]

^<<v1-9-20,20>>^ Now Noah started off as a farmer^&#42;1^ and proceeded to plant a vineyard.

[NOTE]
====
. Lit., “a man of the soil.”
====

[[v1-9-21]]

^<<v1-9-21,21>>^ And he began drinking of the wine and became intoxicated, and so he uncovered himself in the midst of his tent.

[[v1-9-22]]

^<<v1-9-22,22>>^ Later Ham the father of Caʹnaan saw his father’s nakedness and went telling it to his two brothers outside.

[[v1-9-23]]

^<<v1-9-23,23>>^ At that Shem and Jaʹpheth took a^&#42;1^ mantle and put it upon both their shoulders and walked in backwards. Thus they covered their father’s nakedness, while their faces were turned away,^&#42;2^ and they did not see their father’s nakedness.

[NOTE]
====
. Lit., “the.”
. Lit., “were backward.”
====

[[v1-9-24]]

^<<v1-9-24,24>>^ Finally Noah awoke from his wine and got to know what his youngest son had done to him.

[[v1-9-25]]

^<<v1-9-25,25>>^ At this he said:
“Cursed be Caʹnaan.
Let him become the lowest slave^&#42;1^ to his brothers.”

[NOTE]
====
. Lit., “the slave of slaves.”
====

[[v1-9-26]]

^<<v1-9-26,26>>^ And he added:
“Blessed be Jehovah,^&#42;1^ Shem’s God,
And let Caʹnaan become a slave^&#42;2^ to him.

[NOTE]
====
. Heb., Yeho·wahʹ. See 3:14 ftn, “Jehovah.”
. Or, “servant.”
====

[[v1-9-27]]

^<<v1-9-27,27>>^ Let God grant ample space to Jaʹpheth,
And let him reside^&#42;1^ in the tents of Shem.
Let Caʹnaan become a slave to him also.”

[NOTE]
====
. Or, “tent; tabernacle.”
====

[[v1-9-28]]

^<<v1-9-28,28>>^ And Noah continued to live three hundred and fifty years after the deluge.

[[v1-9-29]]

^<<v1-9-29,29>>^ So all the days of Noah amounted to nine hundred and fifty years and he died.

'''

xref:001-genesis/001-genesis-008.adoc#v1-8-0[&#60; Capítulo Anterior] | <<v1-9-0,Topo>> | xref:001-genesis/001-genesis-010.adoc#v1-10-0[Próximo Capítulo &#62;]