include::./index.adoc[]

[[v1-38-0]]
=== Genesis, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-38-1]]

^<<v1-38-1,1>>^ Now in the meantime it came about that when Judah went down from his brothers he pitched &#91;his tent&#93; near a man, an A·dulʹlam·ite, and his name was Hiʹrah.

[[v1-38-2]]

^<<v1-38-2,2>>^ And there Judah got to see a daughter of a certain Caʹnaan·ite, and his^&#42;1^ name was Shuʹa. So he took her and had relations with her.

[NOTE]
====
. “His,” M; LXXSy, “her.”
====

[[v1-38-3]]

^<<v1-38-3,3>>^ And she became pregnant. Later she bore a son and he called his name Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Again she became pregnant. In time she bore a son and called his name Oʹnan.

[[v1-38-5]]

^<<v1-38-5,5>>^ Yet another time she went on to bear a son and then called his name Sheʹlah. Now he^&#42;1^ happened to be in Achʹzib^&#42;2^ at the time she bore him.

[NOTE]
====
. “He,” that is, Judah; LXX, “she.”
. Understood to be the same as “Achzib” in Jos 15:44 and Mic 1:14; M, “Chezib.”
====

[[v1-38-6]]

^<<v1-38-6,6>>^ In time Judah took a wife for Er his firstborn, and her name was Taʹmar.

[[v1-38-7]]

^<<v1-38-7,7>>^ But Er, Judah’s firstborn, proved to be bad in the eyes of Jehovah; hence Jehovah put him to death.

[[v1-38-8]]

^<<v1-38-8,8>>^ In view of that Judah said to Oʹnan: “Have relations with^&#42;1^ your brother’s wife and perform brother-in-law marriage^&#42;2^ with her and raise up offspring for your brother.”

[NOTE]
====
. Lit., “Go in to.”
. Or, “levirate marriage.” Jehovah later gave official recognition to this in the Mosaic Law, in De 25:5-9.
====

[[v1-38-9]]

^<<v1-38-9,9>>^ But Oʹnan knew that the offspring would not become his; and it occurred that when he did have relations with his brother’s wife he wasted his semen on the earth^&#42;1^ so as not to give offspring to his brother.

[NOTE]
====
. Lit., “he wasted [it] on the earth.”
====

[[v1-38-10]]

^<<v1-38-10,10>>^ Now what he did was bad in the eyes of Jehovah; hence he put him also to death.

[[v1-38-11]]

^<<v1-38-11,11>>^ So Judah said to Taʹmar his daughter-in-law: “Dwell as a widow in the house of your father until Sheʹlah my son grows up.” For he said to himself:^&#42;1^ “He too may die like his brothers.” Accordingly Taʹmar went and continued to dwell at her own father’s house.

[NOTE]
====
. Or, “For he thought.”
====

[[v1-38-12]]

^<<v1-38-12,12>>^ Thus the days became many and the daughter of Shuʹa, Judah’s wife, died; and Judah kept the period of mourning. After that he went up to the shearers of his sheep, he and Hiʹrah his companion the A·dulʹlam·ite, to Timʹnah.

[[v1-38-13]]

^<<v1-38-13,13>>^ Then it was told to Taʹmar: “Here your father-in-law is going up to Timʹnah to shear his sheep.”

[[v1-38-14]]

^<<v1-38-14,14>>^ With that she removed the garments of her widowhood from her and covered herself with a shawl and veiled herself and sat down at the entrance of E·naʹim, which is along the road to Timʹnah. For she saw that Sheʹlah had grown up and yet she had not been given as a wife to him.

[[v1-38-15]]

^<<v1-38-15,15>>^ When Judah caught sight of her, he at once took her for a harlot,^&#42;1^ because she had covered her face.

[NOTE]
====
. Or, “prostitute.” Gr., porʹnen. See 1Co 6:15 ftn.
====

[[v1-38-16]]

^<<v1-38-16,16>>^ So he turned aside to her by the road and said: “Allow me, please, to have relations with you.” For he did not know that she was his daughter-in-law. However, she said: “What will you give me that you may have relations with me?”

[[v1-38-17]]

^<<v1-38-17,17>>^ To this he said: “I myself shall send a kid of the goats from the herd.” But she said: “Will you give a security until you send it?”

[[v1-38-18]]

^<<v1-38-18,18>>^ And he continued: “What is the security that I shall give you?” to which she said: “Your seal ring and your cord and your rod that is in your hand.” Then he gave them to her and had relations with her, so that she became pregnant by him.

[[v1-38-19]]

^<<v1-38-19,19>>^ After that she got up and went and removed her shawl off her and clothed herself with the garments of her widowhood.

[[v1-38-20]]

^<<v1-38-20,20>>^ And Judah proceeded to send the kid of the goats by the hand of his companion the A·dulʹlam·ite in order to get back the security from the hand of the woman, but he never found her.

[[v1-38-21]]

^<<v1-38-21,21>>^ And he went inquiring of the men of her place, saying: “Where is that temple prostitute in E·naʹim along the road?” But they kept saying: “No temple prostitute has ever been in this place.”

[[v1-38-22]]

^<<v1-38-22,22>>^ Finally he returned to Judah and said: “I never found her and, besides, the men of the place said, ‘No temple prostitute has ever been in this place.’”

[[v1-38-23]]

^<<v1-38-23,23>>^ So Judah said: “Let her take them for herself, in order that we may not fall into contempt. At any rate, I have sent this kid, but you—you never found her.”

[[v1-38-24]]

^<<v1-38-24,24>>^ However, about three months later it happened that it was told to Judah: “Taʹmar your daughter-in-law has played the harlot, and here she is also pregnant by her harlotry.”^&#42;1^ At that Judah said: “BRING her out and let her be burned.”

[NOTE]
====
. Or, “fornication.”
====

[[v1-38-25]]

^<<v1-38-25,25>>^ As she was being brought out she herself sent to her father-in-law, saying: “By the man to whom these belong I am pregnant.” And she added: “Examine, please, to whom these belong, the seal ring and the cord^&#42;1^ and the rod.”

[NOTE]
====
. “Cord,” TOLXXSyVg; M, “cords.”
====

[[v1-38-26]]

^<<v1-38-26,26>>^ Then Judah examined them and said: “She is more righteous than I am, for the reason that I did not give her to Sheʹlah my son.” And he had no further intercourse with her after that.

[[v1-38-27]]

^<<v1-38-27,27>>^ Now it developed that in the time of her giving birth, why, here there were twins in her belly.

[[v1-38-28]]

^<<v1-38-28,28>>^ Further, it turned out that when she was giving birth one extended his hand, and the midwife at once took and tied a scarlet piece about his hand, saying: “This one came out first.”

[[v1-38-29]]

^<<v1-38-29,29>>^ Finally it developed that as soon as he drew back his hand, why, here his brother came out, so that she exclaimed: “What do you mean by this, that you have produced a perineal rupture for yourself?” Hence his name was called Peʹrez.^&#42;1^

[NOTE]
====
. Meaning “Perineal Rupture.”
====

[[v1-38-30]]

^<<v1-38-30,30>>^ And afterward his brother upon whose hand the scarlet piece was came out and his name came to be called Zeʹrah.^&#42;1^

[NOTE]
====
. Meaning “A Shining Forth; A Rising.”
====

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]