include::./index.adoc[]

[[v1-29-0]]
=== Genesis, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-29-1]]

^<<v1-29-1,1>>^ After that Jacob set his feet in motion and traveled on to the land of the Orientals.^&#42;1^

[NOTE]
====
. Lit., “to the land of the sons of the East.”
====

[[v1-29-2]]

^<<v1-29-2,2>>^ Now he looked, and here there was a well in the field and here three droves of sheep^&#42;1^ were lying down there by it, because from that well they were accustomed to water the droves; and there was a great stone over the mouth of the well.

[NOTE]
====
. Or, “small cattle,” including goats.
====

[[v1-29-3]]

^<<v1-29-3,3>>^ When all the droves had been gathered there, they rolled away the stone from off the mouth of the well, and they watered the flocks, after which they returned the stone over the mouth of the well to its place.

[[v1-29-4]]

^<<v1-29-4,4>>^ So Jacob said to them: “My brothers, from what place are YOU?” to which they said: “We are from Haʹran.”

[[v1-29-5]]

^<<v1-29-5,5>>^ Then he said to them: “Do YOU know Laʹban the grandson of Naʹhor?” to which they said: “We know him.”

[[v1-29-6]]

^<<v1-29-6,6>>^ At this he said to them: “Is it all right with him?”^&#42;1^ In turn they said: “It is all right.^&#42;2^ And here is Rachel his daughter coming with the sheep!”

[NOTE]
====
. Lit., “[Is there] peace to him?” Heb., hasha·lohmʹ loh?
. Lit., “And they said: ‘Peace!’ ” Heb., wai·yoʼ·meruʹ sha·lohmʹ.
====

[[v1-29-7]]

^<<v1-29-7,7>>^ And he went on to say: “Why, it is yet full day.^&#42;1^ It is not the time for gathering the herds. WATER the sheep, then go feed them.”

[NOTE]
====
. Or, “Why, there is yet much of the day left.”
====

[[v1-29-8]]

^<<v1-29-8,8>>^ To this they said: “We are not allowed to do so until all the droves are gathered and they actually roll away the stone from off the mouth of the well. Then we must water the sheep.”

[[v1-29-9]]

^<<v1-29-9,9>>^ While he was yet speaking with them, Rachel came with the sheep that belonged to her father, for she was a shepherdess.

[[v1-29-10]]

^<<v1-29-10,10>>^ And it came about that when Jacob saw Rachel the daughter of Laʹban his mother’s brother and the sheep of Laʹban his mother’s brother, Jacob immediately approached and rolled away the stone from off the mouth of the well and watered the sheep of Laʹban his mother’s brother.

[[v1-29-11]]

^<<v1-29-11,11>>^ Then Jacob kissed Rachel and raised his voice and burst into tears.

[[v1-29-12]]

^<<v1-29-12,12>>^ And Jacob began to tell Rachel that he was the brother^&#42;1^ of her father and that he was the son of Re·bekʹah. And she went running and telling her father.

[NOTE]
====
. “Brother,” but actually the nephew.
====

[[v1-29-13]]

^<<v1-29-13,13>>^ Now it came about that as soon as Laʹban heard the report about Jacob the son of his sister, he went running to meet him. Then he embraced him and kissed him and brought him on into his house. And he began to relate to Laʹban all these things.

[[v1-29-14]]

^<<v1-29-14,14>>^ After that Laʹban said to him: “You are indeed my bone and my flesh.” So he dwelt with him a full month.^&#42;1^

[NOTE]
====
. Lit., “a month of days.”
====

[[v1-29-15]]

^<<v1-29-15,15>>^ After that Laʹban said to Jacob: “Are you my brother, and must you serve me for nothing? Tell me, What are your wages to be?”

[[v1-29-16]]

^<<v1-29-16,16>>^ As it was, Laʹban had two daughters. The name of the older was Leʹah and the name of the younger Rachel.

[[v1-29-17]]

^<<v1-29-17,17>>^ But the eyes of Leʹah had no luster,^&#42;1^ whereas Rachel had become beautiful in form and beautiful of countenance.

[NOTE]
====
. Or, “were dull (weak).”
====

[[v1-29-18]]

^<<v1-29-18,18>>^ And Jacob was in love with Rachel. So he said: “I am willing to serve you seven years for Rachel your younger daughter.”

[[v1-29-19]]

^<<v1-29-19,19>>^ To this Laʹban said: “It is better for me to give her to you than for me to give her to another man. Keep dwelling with me.”

[[v1-29-20]]

^<<v1-29-20,20>>^ And Jacob proceeded to serve seven years for Rachel, but in his eyes they proved to be like some few days because of his love for her.

[[v1-29-21]]

^<<v1-29-21,21>>^ Then Jacob said to Laʹban: “Give over my wife, because my days are up,^&#42;1^ and let me have relations with her.”

[NOTE]
====
. Or, “fulfilled.”
====

[[v1-29-22]]

^<<v1-29-22,22>>^ With that Laʹban gathered all the men of the place and made a feast.

[[v1-29-23]]

^<<v1-29-23,23>>^ But it turned out that during the evening he resorted to taking Leʹah his daughter and bringing her to him that he might have relations with her.

[[v1-29-24]]

^<<v1-29-24,24>>^ Moreover, Laʹban gave to her Zilʹpah his maidservant, even to Leʹah his daughter, as a maidservant.

[[v1-29-25]]

^<<v1-29-25,25>>^ So it followed in the morning that here it was Leʹah! Consequently he said to Laʹban: “What is this you have done to me? Was it not for Rachel that I served with you? So why have you tricked me?”

[[v1-29-26]]

^<<v1-29-26,26>>^ To this Laʹban said: “It is not customary to do this way in our place, to give the younger woman before the firstborn.

[[v1-29-27]]

^<<v1-29-27,27>>^ Celebrate to the full^&#42;1^ the week of this woman.^&#42;2^ After that there shall be given to you also this other woman^&#42;3^ for the service that you can serve with me for seven years more.”

[NOTE]
====
. Or, “Fulfill.”
. That is, Leah.
. That is, Rachel.
====

[[v1-29-28]]

^<<v1-29-28,28>>^ Accordingly Jacob did so and celebrated fully the week of this woman, after which he gave him Rachel his daughter as his wife.

[[v1-29-29]]

^<<v1-29-29,29>>^ Besides, Laʹban gave Bilʹhah his maidservant to Rachel his daughter as her maidservant.

[[v1-29-30]]

^<<v1-29-30,30>>^ Then he had relations also with Rachel and also expressed more love for Rachel than for Leʹah, and he went serving with him for yet seven years more.

[[v1-29-31]]

^<<v1-29-31,31>>^ When Jehovah came to see that Leʹah was hated, he then opened her womb, but Rachel was barren.

[[v1-29-32]]

^<<v1-29-32,32>>^ And Leʹah became pregnant and brought a son to birth and then called his name Reuʹben,^&#42;1^ for she said: “It is because Jehovah has looked upon my wretchedness, in that now my husband will begin to love me.”

[NOTE]
====
. Meaning “See, a Son!” Heb., Reʼu·venʹ.
====

[[v1-29-33]]

^<<v1-29-33,33>>^ And she became pregnant again and brought a son to birth and then said: “It is because Jehovah has listened, in that I was hated and so he gave me also this one.” Hence she called his name Simʹe·on.^&#42;1^

[NOTE]
====
. Meaning “Hearing,” that is, with acceptance. Heb., Shim·ʽohnʹ.
====

[[v1-29-34]]

^<<v1-29-34,34>>^ And she became pregnant yet again and brought a son to birth and then said: “Now this time my husband will join himself to me, because I have borne him three sons.” His name was therefore called Leʹvi.^&#42;1^

[NOTE]
====
. Meaning “Adherence; Joined.” Heb., Le·wiʹ.
====

[[v1-29-35]]

^<<v1-29-35,35>>^ And she became pregnant once more and brought a son to birth and then said: “This time I shall laud Jehovah.” She therefore called his name Judah.^&#42;1^ After that she left off giving birth.

[NOTE]
====
. Meaning “Lauded; [Object of] Laudation.” Heb., Yehu·dhahʹ.
====

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]