include::./index.adoc[]

[[v1-37-0]]
=== Genesis, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-37-1]]

^<<v1-37-1,1>>^ And Jacob continued to dwell in the land of the alien residences of his father, in the land of Caʹnaan.

[[v1-37-2]]

^<<v1-37-2,2>>^ This is the history of Jacob.
Joseph, when seventeen years old, happened to be tending sheep^&#42;1^ with his brothers among the flock, and, being but a boy, he was with the sons of Bilʹhah and the sons of Zilʹpah, the wives of his father. So Joseph brought a bad report about them to their father.

[NOTE]
====
. Or, “happened to be associating.”
====

[[v1-37-3]]

^<<v1-37-3,3>>^ And Israel loved Joseph more than all his other sons, because he was the son of his old age; and he had a long, striped shirtlike garment made for him.

[[v1-37-4]]

^<<v1-37-4,4>>^ When his brothers came to see that their father loved him more than all his brothers, they began to hate him, and they were not able to speak peacefully to him.

[[v1-37-5]]

^<<v1-37-5,5>>^ Later on Joseph had a dream and told it to his brothers, and they found further reason to hate him.

[[v1-37-6]]

^<<v1-37-6,6>>^ And he went on to say to them: “Listen, please, to this dream that I have dreamed.

[[v1-37-7]]

^<<v1-37-7,7>>^ Well, here we were binding sheaves in the middle of the field when here my sheaf got up and also stood erect and here YOUR sheaves proceeded to encircle and bow down to my sheaf.”

[[v1-37-8]]

^<<v1-37-8,8>>^ And his brothers began to say to him: “Are you going to be king over us for certain? or, Are you going to dominate over us for certain?” So they found fresh reason to hate him over his dreams and over his words.

[[v1-37-9]]

^<<v1-37-9,9>>^ After that he had still another dream, and he related it to his brothers and said: “Here I have had a dream once more, and here the sun and the moon and eleven stars were bowing down to me.”

[[v1-37-10]]

^<<v1-37-10,10>>^ Then he related it to his father as well as his brothers, and his father began to rebuke him and say to him: “What does this dream that you have dreamed mean? Am I and also your mother and your brothers for certain going to come and bow down to the earth to you?”

[[v1-37-11]]

^<<v1-37-11,11>>^ And his brothers grew jealous of him, but his father observed the saying.^&#42;1^

[NOTE]
====
. Or, “matter.”
====

[[v1-37-12]]

^<<v1-37-12,12>>^ His brothers now went to feed the flock of their father^&#42;1^ close by Sheʹchem.

[NOTE]
====
. “The flock of their father,” MLXXSyVg. In M the Heb. particle ʼeth, which modifies these words, is marked with extraordinary points by the Sopherim to indicate the words are doubtful and are to be omitted. If so, it may mean that Joseph’s brothers had gone to feed themselves. In vs 13 the word “flocks” does not specifically occur, but the verb is the same as in vs 12. See App 2A.
====

[[v1-37-13]]

^<<v1-37-13,13>>^ After a while Israel said to Joseph: “Your brothers are tending &#91;flocks&#93; close by Sheʹchem, are they not? Come, and let me send you to them.” At this he said to him: “Here I am!”

[[v1-37-14]]

^<<v1-37-14,14>>^ So he said to him: “Go, please. See whether your brothers are safe and sound and whether the flock is safe and sound,^&#42;1^ and bring me back word.” With that he sent him away from the low plain of Heʹbron, and he went on toward Sheʹchem.

[NOTE]
====
. Lit., “See the peace of your brothers and the peace of the flock.”
====

[[v1-37-15]]

^<<v1-37-15,15>>^ Later a man found him and here he was wandering in a field. Then the man inquired of him, saying: “What are you looking for?”

[[v1-37-16]]

^<<v1-37-16,16>>^ To this he said: “It is my brothers I am looking for. Tell me, please, Where are they tending flocks?”

[[v1-37-17]]

^<<v1-37-17,17>>^ And the man continued: “They have pulled away from here, because I heard them saying, ‘Let us go to Doʹthan.’” So Joseph kept on after his brothers and found them at Doʹthan.

[[v1-37-18]]

^<<v1-37-18,18>>^ Well, they caught sight of him from a distance, and before he could get close by them they began plotting cunningly against him to put him to death.

[[v1-37-19]]

^<<v1-37-19,19>>^ So they said to one another: “Look! Here comes that dreamer.^&#42;1^

[NOTE]
====
. “Here comes that dreamer.” Lit., “The master (lord) of dreams, that one there comes.”
====

[[v1-37-20]]

^<<v1-37-20,20>>^ And now come and let us kill him and pitch him into one of the waterpits; and we must say a vicious wild beast devoured him. Then let us see what will become of his dreams.”

[[v1-37-21]]

^<<v1-37-21,21>>^ When Reuʹben heard this he tried to deliver him out of their hand. So he said: “Let us not strike his soul fatally.”^&#42;1^

[NOTE]
====
. Lit., “strike him at the soul.”
====

[[v1-37-22]]

^<<v1-37-22,22>>^ And Reuʹben went on to say to them: “Do not spill blood. Pitch him into this waterpit which is in the wilderness and do not lay a violent hand upon him.” His purpose was to deliver him out of their hand in order to return him to his father.

[[v1-37-23]]

^<<v1-37-23,23>>^ So it came about that as soon as Joseph came to his brothers, they went stripping Joseph of his long garment, even the long striped garment that was upon him;

[[v1-37-24]]

^<<v1-37-24,24>>^ after which they took him and pitched him into the waterpit. At the time the pit was empty; there was no water in it.

[[v1-37-25]]

^<<v1-37-25,25>>^ Then they sat down to eat bread. When they raised their eyes and took a look, why, here was a caravan of Ishʹma·el·ites that was coming from Gilʹe·ad, and their camels were carrying labdanum and balsam^&#42;1^ and resinous bark, on their way to take it down to Egypt.

[NOTE]
====
. Or, “balm,” that is, of Gilead.
====

[[v1-37-26]]

^<<v1-37-26,26>>^ At this Judah said to his brothers: “What profit would there be in case we killed our brother and did cover over his blood?

[[v1-37-27]]

^<<v1-37-27,27>>^ Come and let us sell him to the Ishʹma·el·ites, and do not let our hand be upon him. After all, he is our brother, our flesh.” So they listened to their brother.

[[v1-37-28]]

^<<v1-37-28,28>>^ Now men, Midʹi·an·ite merchants, went passing by. Hence they drew and lifted up Joseph out of the waterpit and then sold Joseph to the Ishʹma·el·ites for twenty silver pieces. Eventually these brought Joseph into Egypt.

[[v1-37-29]]

^<<v1-37-29,29>>^ Later Reuʹben returned to the waterpit and here Joseph was not in the waterpit. Consequently he ripped his garments apart.

[[v1-37-30]]

^<<v1-37-30,30>>^ When he returned to his other brothers he exclaimed: “The child is gone! And I—where am I really to go?”

[[v1-37-31]]

^<<v1-37-31,31>>^ However, they took Joseph’s long garment and slaughtered a male goat and repeatedly dipped the long garment in the blood.

[[v1-37-32]]

^<<v1-37-32,32>>^ After that they sent the long striped garment and had it brought to their father and said: “This is what we found. Examine, please, whether it is your son’s long garment or not.”

[[v1-37-33]]

^<<v1-37-33,33>>^ And he went examining it and exclaimed: “It is my son’s long garment! A vicious wild beast must have devoured him! Joseph is surely torn to pieces!”

[[v1-37-34]]

^<<v1-37-34,34>>^ With that Jacob ripped his mantles apart and put sackcloth upon his hips and carried on mourning over his son for many days.

[[v1-37-35]]

^<<v1-37-35,35>>^ And all his sons and all his daughters kept rising up to comfort him, but he kept refusing to take comfort and saying: “For I shall go down mourning to my son into Sheʹol!”^&#42;1^ And his father continued weeping for him.

[NOTE]
====
. “Into Sheol.” Heb., sheʼoʹlah; Gr., eis haiʹdou; Syr., la·shiul; Lat., in in·ferʹnum; the first occurrence of this word. See App 4B.
====

[[v1-37-36]]

^<<v1-37-36,36>>^ However, the Midʹi·an·ites sold him into Egypt to Potʹi·phar a court official of Pharʹaoh,^&#42;1^ the chief of the bodyguard.

[NOTE]
====
. See 12:15 ftn.
====

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]