include::./index.adoc[]

[[v1-42-0]]
=== Genesis, 42
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-42-1]]

^<<v1-42-1,1>>^ Eventually Jacob got to see that there were cereals in Egypt. Then Jacob said to his sons: “Why do YOU keep looking at one another?”

[[v1-42-2]]

^<<v1-42-2,2>>^ And he added: “Here I have heard that there are cereals in Egypt. Go down there and buy for us from there, that we may keep alive and not die off.”

[[v1-42-3]]

^<<v1-42-3,3>>^ Accordingly ten brothers of Joseph went down to buy grain from Egypt.

[[v1-42-4]]

^<<v1-42-4,4>>^ But Jacob did not send Benjamin, Joseph’s brother, with his other brothers, because he said: “Otherwise a fatal accident^&#42;1^ may befall him.”

[NOTE]
====
. Lit., “a healing,” used as a euphemism for “a fatal accident.”
====

[[v1-42-5]]

^<<v1-42-5,5>>^ So Israel’s sons came along with the others who were coming to buy, because the famine existed in the land of Caʹnaan.

[[v1-42-6]]

^<<v1-42-6,6>>^ And Joseph was the man in power over the land. He was the one that did the selling to all people of the earth. Consequently Joseph’s brothers came and bowed low to him with their faces to the earth.

[[v1-42-7]]

^<<v1-42-7,7>>^ When Joseph got to see his brothers, he at once recognized them, but he made himself unrecognizable to them. So he spoke harshly with them and said to them: “Where have YOU come from?” to which they said: “From the land of Caʹnaan to buy foodstuffs.”

[[v1-42-8]]

^<<v1-42-8,8>>^ Thus Joseph recognized his brothers, but they themselves did not recognize him.

[[v1-42-9]]

^<<v1-42-9,9>>^ Immediately Joseph remembered the dreams that he had dreamed respecting them, and he went on to say to them: “YOU are spies! YOU have come to see the exposed condition^&#42;1^ of the land!”

[NOTE]
====
. Or, “the defenselessness.” Lit., “the nakedness.”
====

[[v1-42-10]]

^<<v1-42-10,10>>^ Then they said to him: “No, my lord, but your servants have come to buy foodstuffs.

[[v1-42-11]]

^<<v1-42-11,11>>^ We are all of us sons of but one man. We are upright men. Your servants do not act as spies.”

[[v1-42-12]]

^<<v1-42-12,12>>^ But he said to them: “Not so! Because YOU have come to see the exposed condition of the land!”

[[v1-42-13]]

^<<v1-42-13,13>>^ At this they said: “Your servants are twelve brothers. We are the sons of but one man in the land of Caʹnaan; and here the youngest is with our father today, whereas the other one is no more.”

[[v1-42-14]]

^<<v1-42-14,14>>^ However, Joseph said to them: “It is what I have spoken to YOU, saying, ‘YOU are spies!’

[[v1-42-15]]

^<<v1-42-15,15>>^ By this YOU will be tested out. As Pharʹaoh lives, YOU will not go out of here except when YOUR youngest brother comes here.

[[v1-42-16]]

^<<v1-42-16,16>>^ Send one of YOU that he may get YOUR brother while YOU have been bound, that YOUR words may be tested out as the truth in YOUR case. And if not, then, as Pharʹaoh lives, YOU are spies.”

[[v1-42-17]]

^<<v1-42-17,17>>^ With that he put them together in custody for three days.

[[v1-42-18]]

^<<v1-42-18,18>>^ After that Joseph said to them on the third day: “Do this and keep alive. I fear the &#91;true&#93; God.

[[v1-42-19]]

^<<v1-42-19,19>>^ If YOU are upright, let one of YOUR brothers be kept bound in YOUR house of custody, but the rest of YOU go, take cereals for the famine in YOUR houses.

[[v1-42-20]]

^<<v1-42-20,20>>^ Then YOU will bring YOUR youngest brother to me, that YOUR words may be found trustworthy; and YOU will not die.” And they proceeded to do so.

[[v1-42-21]]

^<<v1-42-21,21>>^ And they began to say one to the other: “Unquestionably we are guilty with regard to our brother, because we saw the distress of his soul when he implored compassion on our part, but we did not listen. That is why this distress has come upon us.”

[[v1-42-22]]

^<<v1-42-22,22>>^ Then Reuʹben answered them, saying: “Did not I say to YOU, ‘Do not sin against the child,’ but YOU did not listen? And now his blood, here it is certainly asked back.”

[[v1-42-23]]

^<<v1-42-23,23>>^ As for them, they did not know that Joseph was listening, because there was an interpreter between them.

[[v1-42-24]]

^<<v1-42-24,24>>^ Consequently he turned away from them and began to weep. Then he returned to them and spoke to them and took Simʹe·on from them and bound him before their eyes.

[[v1-42-25]]

^<<v1-42-25,25>>^ After that Joseph gave the command, and they went filling up their receptacles with grain. Also, they were to return the money of the men to each one’s individual sack and to give them provisions for the journey. Accordingly it was done so to them.

[[v1-42-26]]

^<<v1-42-26,26>>^ So they loaded their cereals upon their asses and got on their way from there.

[[v1-42-27]]

^<<v1-42-27,27>>^ When one opened his sack to give fodder to his ass at the lodging place, he got to see his money, and here it was in the mouth of his bag.

[[v1-42-28]]

^<<v1-42-28,28>>^ At that he said to his brothers: “My money has been returned and now here it is in my bag!” Then their hearts sank, so that they turned trembling to one another, saying: “What is this God has done to us?”

[[v1-42-29]]

^<<v1-42-29,29>>^ At length they came to Jacob their father to the land of Caʹnaan and told him all the things that had befallen them, saying:

[[v1-42-30]]

^<<v1-42-30,30>>^ “The man who is the lord^&#42;1^ of the country spoke harshly with us, since he took us for men spying on the country.

[NOTE]
====
. Heb., ʼadho·nehʹ, pl. to denote excellence.
====

[[v1-42-31]]

^<<v1-42-31,31>>^ But we said to him, ‘We are upright men. We do not act as spies.

[[v1-42-32]]

^<<v1-42-32,32>>^ We are twelve brothers, the sons of our father. One is no more, and the youngest is today with our father in the land of Caʹnaan.’

[[v1-42-33]]

^<<v1-42-33,33>>^ But the man who is the lord of the country said to us, ‘By this I am going to know YOU are upright: Have one brother of YOURS stay with me. Then YOU take something for the famine in YOUR houses and go.

[[v1-42-34]]

^<<v1-42-34,34>>^ And bring YOUR youngest brother to me, that I may know that YOU are no spies but YOU are upright. Your brother I shall give back to YOU, and YOU may carry on business in the land.’”

[[v1-42-35]]

^<<v1-42-35,35>>^ And it came about that when they were emptying their sacks here was each one’s bundle of money in his sack. And they as well as their father got to see their bundles of money, and they became afraid.

[[v1-42-36]]

^<<v1-42-36,36>>^ Then Jacob their father exclaimed to them: “It is I YOU have bereaved! Joseph is no more and Simʹe·on is no more, and Benjamin YOU are going to take! It is upon me that all these things have come!”

[[v1-42-37]]

^<<v1-42-37,37>>^ But Reuʹben said to his father: “My own two sons you may put to death if I do not bring him back to you. Give him over to my care, and I shall be the one to return him to you.”

[[v1-42-38]]

^<<v1-42-38,38>>^ However, he said: “My son will not go down with YOU men, because his brother is dead and he has been left by himself. If a fatal accident^&#42;1^ should befall him on the way on which YOU would go, then YOU would certainly bring down my gray hairs with grief to Sheʹol.”^&#42;2^

[NOTE]
====
. See vs 4 ftn.
. “To Sheol.” Heb., sheʼohʹlah; Gr., eis haiʹdou; Syr., la·shiul; Lat., ad inʹfe·ros. See App 4B.
====

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]