include::./index.adoc[]

[[v1-34-0]]
=== Genesis, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-34-1]]

^<<v1-34-1,1>>^ Now Diʹnah the daughter of Leʹah, whom she had borne to Jacob, used to go out to see the daughters of the land.

[[v1-34-2]]

^<<v1-34-2,2>>^ And Sheʹchem the son of Haʹmor the Hiʹvite, a chieftain^&#42;1^ of the land, got to see her and then took her and lay down with her and violated^&#42;2^ her.

[NOTE]
====
. “Chieftain of.” Heb., nesiʼʹ; LXX, “ruler (prince)”; Vg, “prince.”
. “Humiliated,” LXX.
====

[[v1-34-3]]

^<<v1-34-3,3>>^ And his soul began clinging to Diʹnah^&#42;1^ the daughter of Jacob, and he fell in love with the young woman and kept speaking persuasively to^&#42;2^ the young woman.

[NOTE]
====
. Or, “his mind (desire) kept fixed on Dinah.”
. Lit., “to the heart of.”
====

[[v1-34-4]]

^<<v1-34-4,4>>^ Finally Sheʹchem said to Haʹmor his father: “Get me this young lady as a wife.”

[[v1-34-5]]

^<<v1-34-5,5>>^ And Jacob heard that he had defiled Diʹnah his daughter. And his sons happened to be with his herd in the field; and Jacob kept silent until they should come in.

[[v1-34-6]]

^<<v1-34-6,6>>^ Later Haʹmor, Sheʹchem’s father, went out to Jacob to speak with him.

[[v1-34-7]]

^<<v1-34-7,7>>^ And the sons of Jacob came in from the field as soon as they heard of it; and the men became hurt in their feelings and they grew very angry, because he had committed a disgraceful folly against Israel in lying down with Jacob’s daughter, whereas nothing like that ought to be done.

[[v1-34-8]]

^<<v1-34-8,8>>^ And Haʹmor proceeded to speak with them, saying: “As for Sheʹchem my son, his soul is attached to YOUR daughter. Give her, please, to him as a wife,

[[v1-34-9]]

^<<v1-34-9,9>>^ and form marriage alliances with us. YOUR daughters YOU are to give to us, and our daughters YOU are to take for yourselves.

[[v1-34-10]]

^<<v1-34-10,10>>^ And with us YOU may dwell, and the land will become available for YOU. Dwell and carry on business^&#42;1^ in it and get settled in it.”

[NOTE]
====
. Or, “travel about,” that is, for commercial purposes.
====

[[v1-34-11]]

^<<v1-34-11,11>>^ Then Sheʹchem said to her father and to her brothers: “Let me find favor in YOUR eyes, and whatever YOU will say to me I shall give it.

[[v1-34-12]]

^<<v1-34-12,12>>^ Raise very high the marriage money^&#42;1^ and gift imposed upon me, and I stand willing to give according to what YOU may say to me; only give me the young woman as a wife.”

[NOTE]
====
. Or, “purchase price of a wife.”
====

[[v1-34-13]]

^<<v1-34-13,13>>^ And Jacob’s sons began to answer Sheʹchem and Haʹmor his father with deceit and to speak so because he had defiled Diʹnah their sister.

[[v1-34-14]]

^<<v1-34-14,14>>^ And they went on to say to them: “We cannot possibly do such a thing, to give our sister to a man who has a foreskin, because that is a reproach to us.

[[v1-34-15]]

^<<v1-34-15,15>>^ Only on this condition can we give consent to YOU, that YOU become like us, by every male of YOURS getting circumcised.

[[v1-34-16]]

^<<v1-34-16,16>>^ Then we shall certainly give our daughters to YOU, and YOUR daughters we shall take for ourselves, and we shall certainly dwell with YOU and become one people.

[[v1-34-17]]

^<<v1-34-17,17>>^ But if YOU do not listen to us to get circumcised, then we will take our daughter and go.”

[[v1-34-18]]

^<<v1-34-18,18>>^ And their words seemed good in the eyes of Haʹmor and in the eyes of Sheʹchem, Haʹmor’s son,

[[v1-34-19]]

^<<v1-34-19,19>>^ and the young man did not delay to perform the condition, because he did find delight in Jacob’s daughter and he was the most honorable of the whole house of his father.

[[v1-34-20]]

^<<v1-34-20,20>>^ So Haʹmor and Sheʹchem his son went to the gate of their city and began to speak to the men of their city, saying:

[[v1-34-21]]

^<<v1-34-21,21>>^ “These men are peace-loving toward us. Hence let them dwell in the land and carry on business^&#42;1^ in it, as the land is quite wide^&#42;2^ before them. Their daughters we can take as wives for ourselves and our own daughters we can give to them.

[NOTE]
====
. “Carry on business.” See vs 10 ftn.
. Lit., “wide on both sides,” that is, spacious.
====

[[v1-34-22]]

^<<v1-34-22,22>>^ Only on this condition will the men give us their consent to dwell with us so as to become one people, that every male of ours gets circumcised just the way they are circumcised.

[[v1-34-23]]

^<<v1-34-23,23>>^ Then their possessions and their wealth and all their livestock, will they not be ours? Only let us give them our consent that they may dwell with us.”

[[v1-34-24]]

^<<v1-34-24,24>>^ Then all those going out by the gate of his city listened to Haʹmor and to Sheʹchem his son, and all the males got circumcised, all those going out by the gate of his city.

[[v1-34-25]]

^<<v1-34-25,25>>^ However, it came about that on the third day, when they got to be aching, the two sons of Jacob, Simʹe·on and Leʹvi, brothers of Diʹnah, proceeded to take each one his sword and to go unsuspectedly^&#42;1^ to the city and to kill every male.

[NOTE]
====
. Or, “undisturbed.”
====

[[v1-34-26]]

^<<v1-34-26,26>>^ And Haʹmor and Sheʹchem his son they killed with the edge of the sword. Then they took Diʹnah from Sheʹchem’s house and went on out.

[[v1-34-27]]

^<<v1-34-27,27>>^ The other sons of Jacob attacked^&#42;1^ the fatally wounded men and went plundering the city, because they had defiled their sister.

[NOTE]
====
. Or, “came in upon.”
====

[[v1-34-28]]

^<<v1-34-28,28>>^ Their flocks and their herds and their asses and what was in the city and what was in the field they took.

[[v1-34-29]]

^<<v1-34-29,29>>^ And all their means of maintenance and all their little children and their wives they carried off captive, so that they plundered all that was in the houses.

[[v1-34-30]]

^<<v1-34-30,30>>^ At this Jacob said to Simʹe·on and to Leʹvi: “YOU have brought ostracism upon me in making me a stench to the inhabitants of the land, with the Caʹnaan·ites and the Perʹiz·zites; whereas I am few in number,^&#42;1^ and they will certainly gather together against me and assault me and I must be annihilated, I and my house.”

[NOTE]
====
. “Few in number.” Lit., “men of number.” See 1Ch 16:19; Ps 105:12.
====

[[v1-34-31]]

^<<v1-34-31,31>>^ In turn they said: “Ought anyone to treat our sister like a prostitute?”^&#42;1^

[NOTE]
====
. Or, “harlot.”
====

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]