include::./index.adoc[]

[[v1-31-0]]
=== Genesis, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-31-1]]

^<<v1-31-1,1>>^ In time he got to hear the words of the sons of Laʹban, saying: “Jacob has taken everything that belonged to our father; and from what belonged to our father he has amassed all this wealth.”

[[v1-31-2]]

^<<v1-31-2,2>>^ When Jacob would look at the face of Laʹban, here it was not with him as formerly.

[[v1-31-3]]

^<<v1-31-3,3>>^ Finally Jehovah said to Jacob: “Return to the land of your fathers and to your relatives,^&#42;1^ and I shall continue with you.”

[NOTE]
====
. Or, “home.” Lit., “place of birth.”
====

[[v1-31-4]]

^<<v1-31-4,4>>^ Then Jacob sent and called Rachel and Leʹah out to the field to his flock,

[[v1-31-5]]

^<<v1-31-5,5>>^ and he said to them:
“I am seeing the face of YOUR father, that he is not the same toward me as formerly; but the God of my father has proved to be with me.

[[v1-31-6]]

^<<v1-31-6,6>>^ And YOU yourselves certainly know that with all my power I have served YOUR father.

[[v1-31-7]]

^<<v1-31-7,7>>^ And YOUR father has trifled with me^&#42;1^ and he has changed my wages ten times, but God^&#42;2^ has not allowed him to do me harm.

[NOTE]
====
. Or, “has deceived me.”
. “God,” MLXXVg; Sam, “Jehovah.”
====

[[v1-31-8]]

^<<v1-31-8,8>>^ If on the one hand he would say, ‘The speckled ones will become your wages,’ then the whole flock produced speckled ones; but if on the other hand he would say, ‘The striped ones will become your wages,’ then the whole flock produced striped ones.

[[v1-31-9]]

^<<v1-31-9,9>>^ So God kept taking the herd of YOUR father away and giving it to me.

[[v1-31-10]]

^<<v1-31-10,10>>^ At last it came about at the time when the flock got in heat that I raised my eyes and saw a sight in a dream and here the he-goats springing upon the flock were striped, speckled and spotty.

[[v1-31-11]]

^<<v1-31-11,11>>^ Then the angel of the &#91;true&#93; God said to me in the dream, ‘Jacob!’ to which I said, ‘Here I am.’

[[v1-31-12]]

^<<v1-31-12,12>>^ And he continued, ‘Raise your eyes, please, and see all the he-goats springing upon the flock are striped, speckled and spotty, for I have seen all that Laʹban is doing to you.

[[v1-31-13]]

^<<v1-31-13,13>>^ I am the &#91;true&#93; God of Bethʹel,^&#42;1^ where you anointed a pillar and where you vowed a vow to me. Now get up, go out of this land and return to the land of your birth.’”^&#42;2^

[NOTE]
====
. “The [true] God of Bethel.” Heb., ha·ʼElʹ Behth-ʼElʹ; LXX, “the God who appeared to you in the place of God.” See App 1G.
. Or, “home; relatives.”
====

[[v1-31-14]]

^<<v1-31-14,14>>^ At this Rachel and Leʹah answered and said to him: “Is there a share of inheritance^&#42;1^ for us anymore in the house of our father?

[NOTE]
====
. Lit., “a share and an inheritance (possession),” in a figure of hendiadys. Compare 3:16 ftn.
====

[[v1-31-15]]

^<<v1-31-15,15>>^ Are we not really considered as foreigners to him since he has sold us, so that he keeps eating continually even from the money given for us?

[[v1-31-16]]

^<<v1-31-16,16>>^ For all the riches that God^&#42;1^ has taken away from our father are ours and our children’s. So now everything God has said to you do.”

[NOTE]
====
. “God,” MLXXVg; Sam, “Jehovah.”
====

[[v1-31-17]]

^<<v1-31-17,17>>^ Then Jacob got up and lifted his children and his wives onto the camels;

[[v1-31-18]]

^<<v1-31-18,18>>^ and he began driving all his herd and all the goods that he had accumulated, the herd of his acquisition that he had accumulated in Padʹdan-aʹram, in order to go to Isaac his father to the land of Caʹnaan.

[[v1-31-19]]

^<<v1-31-19,19>>^ Now Laʹban had gone to shear his sheep. Meantime Rachel stole the teraphim^&#42;1^ that belonged to her father.

[NOTE]
====
. “Teraphim,” M; LXXVg, “idols”; Sy, “images.”
====

[[v1-31-20]]

^<<v1-31-20,20>>^ So Jacob outwitted^&#42;1^ Laʹban the Syrian, because he had not told him that he was running away.

[NOTE]
====
. Lit., “stole the heart of.”
====

[[v1-31-21]]

^<<v1-31-21,21>>^ And he proceeded to run away and to get up and cross the River, he and all he had. After that he directed his face to the mountainous region of Gilʹe·ad.

[[v1-31-22]]

^<<v1-31-22,22>>^ Later, on the third day, it was told to Laʹban that Jacob had run away.

[[v1-31-23]]

^<<v1-31-23,23>>^ With that he took his brothers with him and went chasing after him for a distance of seven days’ journey and caught up with him in the mountainous region of Gilʹe·ad.

[[v1-31-24]]

^<<v1-31-24,24>>^ Then God came to Laʹban the Syrian in a dream by night and said to him: “Watch yourself that you do not go speaking either good or bad^&#42;1^ with Jacob.”

[NOTE]
====
. Lit., “from good to bad.”
====

[[v1-31-25]]

^<<v1-31-25,25>>^ So Laʹban approached Jacob, as Jacob had pitched his tent in the mountain and Laʹban had encamped his brothers^&#42;1^ in the mountainous region of Gilʹe·ad.

[NOTE]
====
. Apparently it should read, “Laban had pitched his tent.” “His tent” was meant originally instead of the similar Heb. word for “his brothers.”
====

[[v1-31-26]]

^<<v1-31-26,26>>^ Then Laʹban said to Jacob: “What have you done, in that you resorted to outwitting me and driving my daughters off like captives taken by the sword?

[[v1-31-27]]

^<<v1-31-27,27>>^ Why did you have to run away secretly and outwit me and not tell me, that I might send you away with rejoicing and with songs, with tambourine and with harp?

[[v1-31-28]]

^<<v1-31-28,28>>^ And you did not give me a chance to kiss my children^&#42;1^ and my daughters. Now you have acted foolishly.

[NOTE]
====
. Or, “sons.”
====

[[v1-31-29]]

^<<v1-31-29,29>>^ It is in the power of my hand to do harm to YOU people, but the God of YOUR father talked to me last night, saying, ‘Watch yourself against speaking either good or bad with Jacob.’

[[v1-31-30]]

^<<v1-31-30,30>>^ While you have actually gone now because you have been yearning intensely for the house of your father, why, though, have you stolen my gods?”^&#42;1^

[NOTE]
====
. “My gods.” Heb., ʼelo·haiʹ, pl., referring to false gods; Gr., the·ousʹ; Lat., deʹos.
====

[[v1-31-31]]

^<<v1-31-31,31>>^ In answer Jacob proceeded to say to Laʹban: “It was because I was afraid. For I said to myself, ‘You might tear your daughters away from me.’

[[v1-31-32]]

^<<v1-31-32,32>>^ Whoever it is with whom you may find your gods,^&#42;1^ let him not live. Before our brothers, examine for yourself what is with me and take them for yourself.” But Jacob did not know that Rachel had stolen them.

[NOTE]
====
. “Your gods.” Heb., ʼelo·heyʹkha, pl., referring to false gods.
====

[[v1-31-33]]

^<<v1-31-33,33>>^ So Laʹban went on into the tent of Jacob and into the tent of Leʹah and into the tent of the two slave girls, but did not find them. Finally he went out of Leʹah’s tent and went on into Rachel’s tent.

[[v1-31-34]]

^<<v1-31-34,34>>^ Now Rachel had taken the teraphim, and she resorted to putting them in the woman’s saddle basket of the camel, and she kept sitting upon them. So Laʹban went feeling through the whole tent, but did not find them.

[[v1-31-35]]

^<<v1-31-35,35>>^ Then she said to her father: “Do not let anger gleam in the eyes of my lord,^&#42;1^ because I am not able to get up before you, for the customary thing with women is upon me.” So he searched on carefully, but did not find the teraphim.

[NOTE]
====
. “My lord.” Heb., ʼadho·niʹ, the word ʼa·dhohnʹ, “lord; master,” with the pronominal suffix i, “my.”
====

[[v1-31-36]]

^<<v1-31-36,36>>^ And Jacob became angry and began to quarrel with Laʹban, and in answer Jacob went on to say to Laʹban: “What is the revolt on my part, what the sin of mine, as a reason why you have hotly pursued after me?

[[v1-31-37]]

^<<v1-31-37,37>>^ Now that you have felt through all my goods, what of all the goods of your house have you found? Put it here in front of my brothers and your brothers, and let them decide between us two.

[[v1-31-38]]

^<<v1-31-38,38>>^ These twenty years I have been with you. Your female sheep and your she-goats did not suffer abortions, and the rams of your flock I never ate.

[[v1-31-39]]

^<<v1-31-39,39>>^ Any animal torn to pieces I did not bring to you. I myself would stand the loss of it. Whether one was stolen by day or was stolen by night, you would put in a claim for it from my hand.

[[v1-31-40]]

^<<v1-31-40,40>>^ It has been my experience that by day the heat consumed me and the cold by night, and my sleep would flee from my eyes.

[[v1-31-41]]

^<<v1-31-41,41>>^ This makes twenty years for me in your house. I have served you^&#42;1^ fourteen years for your two daughters and six years for your flock, and you kept changing my wages ten times.

[NOTE]
====
. “And thus for twenty years I have served you in your house,” Vg.
====

[[v1-31-42]]

^<<v1-31-42,42>>^ If the God of my father, the God of Abraham and the Dread^&#42;1^ of Isaac, had not proved on my side, you would now have sent me away empty-handed. My wretchedness and the toil of my hands God has seen, and so he reproved you^&#42;2^ last night.”

[NOTE]
====
. Or, “Dreaded One.”
. Or, “and so he rendered a decision.”
====

[[v1-31-43]]

^<<v1-31-43,43>>^ Then Laʹban in answer said to Jacob: “The daughters are my daughters and the children my children and the flock my flock, and everything you are looking at is mine and my daughters’. What can I do against these today or against their children whom they have borne?

[[v1-31-44]]

^<<v1-31-44,44>>^ And now, come, let us conclude a covenant, I and you, and it must^&#42;1^ serve as a witness between me and you.”

[NOTE]
====
. Or, “that it may indeed.”
====

[[v1-31-45]]

^<<v1-31-45,45>>^ Accordingly Jacob took a stone and set it up as a pillar.

[[v1-31-46]]

^<<v1-31-46,46>>^ Then Jacob said to his brothers: “Pick up stones!” And they went taking stones and making a heap. After that they ate there on the heap.

[[v1-31-47]]

^<<v1-31-47,47>>^ And Laʹban began calling it Jeʹgar-sa·ha·duʹtha,^&#42;1^ but Jacob called it Galʹe·ed.^&#42;2^

[NOTE]
====
. The Aramaic (Syrian) expression meaning “Witness Heap.”
. The Heb. expression meaning “Witness Heap.”
====

[[v1-31-48]]

^<<v1-31-48,48>>^ And Laʹban proceeded to say: “This heap is a witness between me and you today.” That is why he called its name Galʹe·ed,

[[v1-31-49]]

^<<v1-31-49,49>>^ and The Watchtower,^&#42;1^ because he said: “Let Jehovah keep watch between me and you when we are situated unseen^&#42;2^ the one from the other.

[NOTE]
====
. “And The Watchtower (Lookout Point).” Heb., weham·Mits·pahʹ.
. Lit., “when we lie concealed.”
====

[[v1-31-50]]

^<<v1-31-50,50>>^ If you go to afflicting my daughters and if you go to taking wives in addition to my daughters, there is no man with us. See!^&#42;1^ God is a witness between me and you.”

[NOTE]
====
. “See, there is no man with us seeing,” LXXmss.
====

[[v1-31-51]]

^<<v1-31-51,51>>^ And Laʹban went on to say to Jacob: “Here is this heap and here is the pillar that I have erected between me and you.

[[v1-31-52]]

^<<v1-31-52,52>>^ This heap is a witness, and the pillar is something that bears witness, that I will not pass this heap against you and that you will not pass this heap and this pillar against me for harm.

[[v1-31-53]]

^<<v1-31-53,53>>^ Let the god^&#42;1^ of Abraham and the god of Naʹhor judge^&#42;2^ between us, the god^&#42;3^ of their father.” But Jacob swore by the Dread of his father Isaac.

[NOTE]
====
. Or, “gods.” Heb., ʼelo·hehʹ, pl.; possibly used in the pl. sense because the Syrian Laban believed in teraphim.
. “Let . . . judge.” This verb is pl. here. Compare 20:13 ftn, “Wander.”
. Or, “gods.” Heb., ʼelo·hehʹ, pl. and may not refer to Jehovah only, because the verb “Let . . . judge” is also pl. SamLXXSyVg have “judge” in the sing. to indicate one God.
====

[[v1-31-54]]

^<<v1-31-54,54>>^ After that Jacob sacrificed a sacrifice in the mountain and invited his brothers to eat bread. Accordingly they ate bread and passed the night in the mountain.^&#42;1^

[NOTE]
====
. MLXX end chapter 31 here with only 54 vss.
====

[[v1-31-55]]

^<<v1-31-55,55>>^ However, Laʹban got up early in the morning and kissed his children^&#42;1^ and his daughters and blessed them. Then Laʹban got on his way that he might return to his own place.^&#42;2^

[NOTE]
====
. Or, “sons.”
. SyVg end chapter 31 here with 55 vss, so chapter 32 is one vs shorter than in M.
====

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]