include::./index.adoc[]

[[v1-26-0]]
=== Genesis, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-26-1]]

^<<v1-26-1,1>>^ Now there arose a famine in the land, besides the first famine that occurred in the days of Abraham, so that Isaac directed himself to A·bimʹe·lech, king of the Phi·lisʹtines, to Geʹrar.

[[v1-26-2]]

^<<v1-26-2,2>>^ Then Jehovah appeared to him and said: “Do not go down to Egypt. Tabernacle in the land that I designate to you.

[[v1-26-3]]

^<<v1-26-3,3>>^ Reside as an alien in this land, and I shall continue with you and bless you, because to you and to your seed I shall give all these lands, and I will carry out the sworn statement that I swore to Abraham your father,

[[v1-26-4]]

^<<v1-26-4,4>>^ ‘And I will multiply your seed like the stars of the heavens and I will give to your seed all these lands; and by means of your seed all nations of the earth will certainly bless themselves,’^&#42;1^

[NOTE]
====
. See 22:18 ftn.
====

[[v1-26-5]]

^<<v1-26-5,5>>^ due to the fact that Abraham listened to^&#42;1^ my voice and continued to keep his obligations to me, my commands, my statutes, and my laws.”

[NOTE]
====
. Or, “obeyed.”
====

[[v1-26-6]]

^<<v1-26-6,6>>^ So Isaac went on dwelling at Geʹrar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Well, the men of the place kept asking with respect to his wife, and he would say: “She is my sister.” For he was afraid to say “My wife” for fear that, to quote him, “the men of the place should kill me because of Re·bekʹah,” because she was attractive in appearance.

[[v1-26-8]]

^<<v1-26-8,8>>^ So it came about that as his days there extended themselves A·bimʹe·lech, king of the Phi·lisʹtines, was looking out of the window and taking in the sight, and there was Isaac having a good time with Re·bekʹah his wife.

[[v1-26-9]]

^<<v1-26-9,9>>^ At once A·bimʹe·lech called Isaac and said: “Why, she is no other than your wife! So how is it that you said, ‘She is my sister’?” At this Isaac said to him: “I said it for fear I should die on her account.”

[[v1-26-10]]

^<<v1-26-10,10>>^ But A·bimʹe·lech continued: “What is this you have done to us? A little more and certainly one of the people would have lain down with your wife, and you would have brought guilt upon us!”

[[v1-26-11]]

^<<v1-26-11,11>>^ Then A·bimʹe·lech commanded all the people, saying: “Anybody touching this man and his wife will surely be put to death!”

[[v1-26-12]]

^<<v1-26-12,12>>^ Afterward Isaac began to sow seed in that land, and in that year he was getting up to a hundred measures to one, as Jehovah was blessing him.

[[v1-26-13]]

^<<v1-26-13,13>>^ Consequently the man became great and went on advancing more and more and growing great until he got very great.

[[v1-26-14]]

^<<v1-26-14,14>>^ And he came to have flocks of sheep and herds of cattle and a large body of servants, so that the Phi·lisʹtines began to envy him.

[[v1-26-15]]

^<<v1-26-15,15>>^ As for all the wells that the servants of his father had dug in the days of Abraham his father, these the Phi·lisʹtines stopped up and they would fill them with dry earth.

[[v1-26-16]]

^<<v1-26-16,16>>^ Finally A·bimʹe·lech said to Isaac: “Move from our neighborhood, because you have grown far stronger than we are.”

[[v1-26-17]]

^<<v1-26-17,17>>^ So Isaac moved from there and encamped in the torrent valley^&#42;1^ of Geʹrar and took up dwelling there.

[NOTE]
====
. Or, “in the wadi (arroyo).”
====

[[v1-26-18]]

^<<v1-26-18,18>>^ And Isaac proceeded to dig again the wells of water that they had dug in the days of Abraham his father^&#42;1^ but which the Phi·lisʹtines went stopping up after Abraham’s death; and he resumed calling their names by the names that his father had called them.

[NOTE]
====
. “That they had dug in the days of Abraham his father,” M; SamLXXVg, “that the servants of Abraham his father had dug.”
====

[[v1-26-19]]

^<<v1-26-19,19>>^ And the servants of Isaac went on digging in the torrent valley and so they found there a well of fresh^&#42;1^ water.

[NOTE]
====
. Or, “live; living.” Heb., chai·yimʹ.
====

[[v1-26-20]]

^<<v1-26-20,20>>^ And the shepherds of Geʹrar fell to quarreling with the shepherds of Isaac, saying: “The water is ours!” Hence he called the name of the well Eʹsek,^&#42;1^ because they had contended with him.

[NOTE]
====
. Meaning “Contention; Strife.”
====

[[v1-26-21]]

^<<v1-26-21,21>>^ And they went digging another well, and they fell to quarreling over it also. Hence he called its name Sitʹnah.^&#42;1^

[NOTE]
====
. Meaning “Accusation.”
====

[[v1-26-22]]

^<<v1-26-22,22>>^ Later he moved away from there and dug another well, but they did not quarrel over it. Hence he called its name Re·hoʹboth^&#42;1^ and said: “It is because now Jehovah has given us ample room and has made us fruitful in the earth.”^&#42;2^

[NOTE]
====
. Meaning “Broad Places.”
. Or, “land.”
====

[[v1-26-23]]

^<<v1-26-23,23>>^ Then he went up from there to Beʹer-sheʹba.

[[v1-26-24]]

^<<v1-26-24,24>>^ And Jehovah proceeded to appear to him during that night and to say: “I am the God of Abraham your father. Do not be afraid, because I am with you, and I will bless you and multiply your seed on account of Abraham my servant.”

[[v1-26-25]]

^<<v1-26-25,25>>^ Accordingly he built an altar there and called on^&#42;1^ the name of Jehovah and pitched his tent there, and the servants of Isaac went excavating a well there.

[NOTE]
====
. Or, “and declared (preached).”
====

[[v1-26-26]]

^<<v1-26-26,26>>^ Later on A·bimʹe·lech came to him from Geʹrar with A·huzʹzath his confidential friend and Phiʹcol the chief of his army.

[[v1-26-27]]

^<<v1-26-27,27>>^ At this Isaac said to them: “Why have YOU come to me, seeing that YOU yourselves hated me and so sent me away from YOUR neighborhood?”

[[v1-26-28]]

^<<v1-26-28,28>>^ To this they said: “We have unmistakably seen that Jehovah has proved to be with you. Hence we said, ‘Let, please, an oath of obligation occur between us, between us and you, and let us conclude a covenant with you,

[[v1-26-29]]

^<<v1-26-29,29>>^ that you will do nothing bad toward us just as we have not touched you and just as we have done only good toward you in that^&#42;1^ we sent you away in peace. You now are the blessed of Jehovah.’”

[NOTE]
====
. Or, “toward you and.”
====

[[v1-26-30]]

^<<v1-26-30,30>>^ Then he made a feast for them and they ate and drank.

[[v1-26-31]]

^<<v1-26-31,31>>^ Next morning they were early in rising and they made sworn statements one to the other. After that Isaac sent them away and they went from him in peace.

[[v1-26-32]]

^<<v1-26-32,32>>^ Now on that day it occurred that the servants of Isaac proceeded to come and report to him regarding the well that they had dug, and to say to him: “We have found water!”

[[v1-26-33]]

^<<v1-26-33,33>>^ Hence he called its name Shiʹbah. That is why the name of the city is Beʹer-sheʹba, down to this day.

[[v1-26-34]]

^<<v1-26-34,34>>^ And Eʹsau grew to be forty years old. Then he took as wife Juʹdith the daughter of Be·eʹri the Hitʹtite and also Basʹe·math the daughter of Eʹlon the Hitʹtite.

[[v1-26-35]]

^<<v1-26-35,35>>^ And they were a source of bitterness of spirit^&#42;1^ to Isaac and Re·bekʹah.

[NOTE]
====
. Or, “grief of mind.”
====

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]