include::./index.adoc[]

[[v1-6-0]]
=== Genesis, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-6-1]]

^<<v1-6-1,1>>^ Now it came about that when men started to grow in numbers on the surface of the ground and daughters were born to them,

[[v1-6-2]]

^<<v1-6-2,2>>^ then the sons^&#42;1^ of the &#91;true&#93; God began to notice the daughters of men, that they were good-looking; and they went taking wives for themselves, namely, all whom they chose.

[NOTE]
====
. “Angels,” LXXA.
====

[[v1-6-3]]

^<<v1-6-3,3>>^ After that Jehovah said: “My spirit shall not act toward man indefinitely in that he^&#42;1^ is also flesh. Accordingly his days shall amount to a hundred and twenty years.”

[NOTE]
====
. “He,” referring to “man,” and not to “my spirit.”
====

[[v1-6-4]]

^<<v1-6-4,4>>^ The Nephʹi·lim^&#42;1^ proved to be in the earth in those days, and also after that, when the sons of the &#91;true&#93; God continued to have relations with the daughters of men and they bore sons to them, they were the mighty ones^&#42;2^ who were of old, the men of fame.^&#42;3^

[NOTE]
====
. Or, “The Fellers.” Heb., han·Nephi·limʹ, “those who cause others to fall down.”
. “The mighty ones.” Heb., hag·gib·bo·rimʹ.
. Lit., “name.”
====

[[v1-6-5]]

^<<v1-6-5,5>>^ Consequently Jehovah saw that the badness of man was abundant in the earth and every inclination of the thoughts of his heart was only bad all the time.^&#42;1^

[NOTE]
====
. Lit., “day.”
====

[[v1-6-6]]

^<<v1-6-6,6>>^ And Jehovah felt regrets that he had made men in the earth, and he felt hurt at his heart.

[[v1-6-7]]

^<<v1-6-7,7>>^ So Jehovah said: “I am going to wipe men whom I have created off the surface of the ground, from man to domestic animal, to moving animal and to flying creature of the heavens, because I do regret that I have made them.”

[[v1-6-8]]

^<<v1-6-8,8>>^ But Noah found favor in the eyes of Jehovah.

[[v1-6-9]]

^<<v1-6-9,9>>^ This is the history of Noah.
Noah was a righteous man. He proved himself faultless among his contemporaries.^&#42;1^ Noah walked with the &#91;true&#93; God.

[NOTE]
====
. “Among his contemporaries.” Lit., “among his generations.” Heb., bedho·ro·thavʹ.
====

[[v1-6-10]]

^<<v1-6-10,10>>^ In time Noah became father to three sons, Shem, Ham and Jaʹpheth.

[[v1-6-11]]

^<<v1-6-11,11>>^ And the earth came to be ruined in the sight of the &#91;true&#93; God and the earth became filled with violence.

[[v1-6-12]]

^<<v1-6-12,12>>^ So God saw the earth and, look! it was ruined, because all flesh had ruined its way on the earth.

[[v1-6-13]]

^<<v1-6-13,13>>^ After that God said to Noah: “The end of all flesh has come before me, because the earth is full of violence as a result of them; and here I am bringing them to ruin together with the earth.

[[v1-6-14]]

^<<v1-6-14,14>>^ Make for yourself an ark^&#42;1^ out of wood of a resinous tree.^&#42;2^ You will make compartments^&#42;3^ in the ark, and you must cover it inside and outside with tar.

[NOTE]
====
. Lit., “a chest.” Heb., te·vathʹ. See Ex 2:3, 5.
. Lit., “trees of gopher,” a resinous wood, possibly cypress.
. Or, “cells; chambers; cabins.”
====

[[v1-6-15]]

^<<v1-6-15,15>>^ And this is how you will make it: three hundred cubits^&#42;1^ the length of the ark, fifty cubits its width, and thirty cubits its height.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.).
====

[[v1-6-16]]

^<<v1-6-16,16>>^ You will make a tsoʹhar &#91;roof; or, window&#93;^&#42;1^ for the ark, and you will complete it to the extent of a cubit upward,^&#42;2^ and the entrance of the ark you will put in its side; you will make it with a lower &#91;story&#93;, a second &#91;story&#93; and a third &#91;story&#93;.

[NOTE]
====
. Or, “opening for illumination.” Heb., tsoʹhar.
. Lit., “from above.”
====

[[v1-6-17]]

^<<v1-6-17,17>>^ “And as for me, here I am bringing the deluge^&#42;1^ of waters upon the earth to bring to ruin all flesh in which the force of life is active^&#42;2^ from under the heavens. Everything that is in the earth will expire.

[NOTE]
====
. Or, “the heavenly ocean.” Heb., ham·mab·bulʹ; Lat., di·luʹvi·i (root of “diluvial”). See 7:6 ftn.
. Lit., “in which the active force (spirit) of life [is].” Heb., ʼasher-bohʹ ruʹach chai·yimʹ. Here ruʹach means “active force; spirit.” See 1:2 ftn, “Force.”
====

[[v1-6-18]]

^<<v1-6-18,18>>^ And I do establish my covenant with you; and you must go into the ark, you and your sons and your wife and your sons’ wives with you.

[[v1-6-19]]

^<<v1-6-19,19>>^ And of every living creature of every sort of flesh, two of each, you will bring into the ark to preserve them alive with you. Male and female they will be.

[[v1-6-20]]

^<<v1-6-20,20>>^ Of the flying creatures according to their kinds and of the domestic animals according to their kinds, of all moving animals of the ground according to their kinds,^&#42;1^ two of each will go in there to you to preserve them alive.

[NOTE]
====
. Lit., “according to its kind.” Heb., lemi·neʹhu. See 1:11 ftn.
====

[[v1-6-21]]

^<<v1-6-21,21>>^ And as for you, take for yourself every sort of food that is eaten; and you must gather it to yourself, and it must serve as food for you and for them.”

[[v1-6-22]]

^<<v1-6-22,22>>^ And Noah proceeded to do according to all that God had commanded him. He did just so.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]