include::./index.adoc[]

[[v1-27-0]]
=== Genesis, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-27-1]]

^<<v1-27-1,1>>^ Now it came about that when Isaac was old and his eyes were too dim to see he then called Eʹsau his older son and said to him: “My son!” at which he said to him: “Here I am!”

[[v1-27-2]]

^<<v1-27-2,2>>^ And he went on to say: “Here, now, I have become old. I do not know the day of my death.

[[v1-27-3]]

^<<v1-27-3,3>>^ So at this time take, please, your implements, your quiver and your bow, and go out to the field and hunt some venison for me.

[[v1-27-4]]

^<<v1-27-4,4>>^ Then make me a tasty dish such as I am fond of and bring it to me and, ah, let me eat, in order that my soul may bless you before I die.”

[[v1-27-5]]

^<<v1-27-5,5>>^ However, Re·bekʹah was listening while Isaac spoke to Eʹsau his son. And Eʹsau went on out into the field to hunt game and to bring it in.

[[v1-27-6]]

^<<v1-27-6,6>>^ And Re·bekʹah said to Jacob her son: “Here I just heard your father speaking to Eʹsau your brother, saying,

[[v1-27-7]]

^<<v1-27-7,7>>^ ‘Bring me some game and make me a tasty dish and, ah, let me eat, that I may bless you before Jehovah before my death.’

[[v1-27-8]]

^<<v1-27-8,8>>^ And now, my son, listen to my voice in what I am commanding you.

[[v1-27-9]]

^<<v1-27-9,9>>^ Go, please, to the herd and get me from there two kids of the goats, good ones, that I may make them up into a tasty dish for your father such as he is fond of.

[[v1-27-10]]

^<<v1-27-10,10>>^ Then you must bring it to your father and he must eat it, in order that he may bless you before his death.”

[[v1-27-11]]

^<<v1-27-11,11>>^ And Jacob proceeded to say to Re·bekʹah his mother: “But Eʹsau my brother is a hairy man and I am a smooth man.

[[v1-27-12]]

^<<v1-27-12,12>>^ What if my father feels me? Then I shall certainly become in his eyes like one making a mockery, and I shall certainly bring upon myself a malediction and not a blessing.”

[[v1-27-13]]

^<<v1-27-13,13>>^ At this his mother said to him: “Upon me be the malediction meant for you, my son. Only listen to my voice and go, get them for me.”

[[v1-27-14]]

^<<v1-27-14,14>>^ Accordingly he went and got them and brought them to his mother, and his mother made a tasty dish such as his father was fond of.

[[v1-27-15]]

^<<v1-27-15,15>>^ After that Re·bekʹah took garments of Eʹsau her older son, the most desirable ones which were with her in the house, and put them on Jacob her younger son.

[[v1-27-16]]

^<<v1-27-16,16>>^ And the skins of the kids of the goats she put upon his hands and upon the hairless part of his neck.

[[v1-27-17]]

^<<v1-27-17,17>>^ Then she gave the tasty dish and the bread that she had made into the hand of Jacob her son.

[[v1-27-18]]

^<<v1-27-18,18>>^ So he went on in to his father and said: “My father!” to which he said: “Here I am! Who are you, my son?”

[[v1-27-19]]

^<<v1-27-19,19>>^ And Jacob went on to say to his father: “I am Eʹsau your firstborn. I have done just as you have spoken to me. Raise yourself up, please. Sit down and eat some of my game, in order that your soul may bless me.”

[[v1-27-20]]

^<<v1-27-20,20>>^ At that Isaac said to his son: “How is it that you have been so quick in finding it, my son?” In turn he said: “Because Jehovah your God caused it to meet up with me.”

[[v1-27-21]]

^<<v1-27-21,21>>^ Then Isaac said to Jacob: “Come near, please, that I may feel you, my son, to know whether you are really my son Eʹsau or not.”

[[v1-27-22]]

^<<v1-27-22,22>>^ So Jacob came near to Isaac his father, and he went feeling him, after which he said: “The voice is the voice of Jacob, but the hands are the hands of Eʹsau.”

[[v1-27-23]]

^<<v1-27-23,23>>^ And he did not recognize him, because his hands proved to be hairy like the hands of Eʹsau his brother. Hence he blessed him.

[[v1-27-24]]

^<<v1-27-24,24>>^ After that he said: “You are really my son Eʹsau?” to which he said: “I am.”

[[v1-27-25]]

^<<v1-27-25,25>>^ Then he said: “Bring it near to me that I may eat some of the game of my son, to the end that my soul may bless you.” With that he brought it near to him and he began to eat, and he brought him wine and he began to drink.

[[v1-27-26]]

^<<v1-27-26,26>>^ Then Isaac his father said to him: “Come near, please, and kiss me, my son.”

[[v1-27-27]]

^<<v1-27-27,27>>^ So he came near and kissed him, and he could smell the scent of his garments. And he proceeded to bless him and to say:
“See, the scent of my son is like the scent of the field which Jehovah has blessed.

[[v1-27-28]]

^<<v1-27-28,28>>^ And may the &#91;true&#93; God give you the dews of the heavens and the fertile soils^&#42;1^ of the earth and an abundance of grain and new wine.

[NOTE]
====
. “The fertile soils.” Lit., “the fatnesses,” referring to fertility.
====

[[v1-27-29]]

^<<v1-27-29,29>>^ Let peoples serve you and let national groups bow low to you. Become master over your brothers, and let the sons of your mother bow low to you. Cursed be each one of those cursing you, and blessed be each one of those blessing you.”

[[v1-27-30]]

^<<v1-27-30,30>>^ Now it came about as soon as Isaac had finished blessing Jacob, yes, it indeed came about when Jacob had barely come out from before the face of Isaac his father, that Eʹsau his brother came back from his hunting.

[[v1-27-31]]

^<<v1-27-31,31>>^ And he too went about making a tasty dish. Then he brought it to his father and said to his father: “Let my father get up and eat some of his son’s game, in order that your soul may bless me.”

[[v1-27-32]]

^<<v1-27-32,32>>^ At this Isaac his father said to him: “Who are you?” to which he said: “I am your son, your firstborn, Eʹsau.”

[[v1-27-33]]

^<<v1-27-33,33>>^ And Isaac began to shake with a great trembling in extreme measure, and so he said: “Who, then, was it that hunted for game and came bringing it to me, so that I ate of everything before you could come in and I blessed him? Blessed too he will become!”^&#42;1^

[NOTE]
====
. Or, “continue.”
====

[[v1-27-34]]

^<<v1-27-34,34>>^ On hearing his father’s words Eʹsau began to cry out in an extremely loud and bitter manner and to say to his father: “Bless me, even me too, my father!”

[[v1-27-35]]

^<<v1-27-35,35>>^ But he went on to say: “Your brother came with deception that he might get the blessing meant for you.”

[[v1-27-36]]

^<<v1-27-36,36>>^ At this he said: “Is that not why his name is called Jacob,^&#42;1^ in that he should supplant me these two times? My birthright he has already taken, and here at this time he has taken my blessing!” Then he added: “Have you not reserved a blessing for me?”

[NOTE]
====
. Meaning “Taking Hold of the Heel; Supplanter.”
====

[[v1-27-37]]

^<<v1-27-37,37>>^ But in answer to Eʹsau Isaac continued: “Here I have appointed him master over you, and all his brothers I have given to him as servants, and grain and new wine I have bestowed for his support, and where is there anything I can do for you, my son?”

[[v1-27-38]]

^<<v1-27-38,38>>^ Then Eʹsau said to his father: “Is there just one blessing that you have, my father? Bless me, even me too, my father!” With that Eʹsau raised his voice and burst into tears.

[[v1-27-39]]

^<<v1-27-39,39>>^ So in answer Isaac his father said to him:
“Behold, away from the fertile soils of the earth your dwelling will be found, and away from the dew of the heavens above.

[[v1-27-40]]

^<<v1-27-40,40>>^ And by your sword you will live, and your brother you will serve. But it will certainly occur that, when you grow restless, you will indeed break his yoke off your neck.”

[[v1-27-41]]

^<<v1-27-41,41>>^ However, Eʹsau harbored animosity for Jacob on account of the blessing with which his father had blessed him, and Eʹsau kept saying in his heart: “The days of the period of mourning for my father are getting closer. After that I am going to kill Jacob my brother.”

[[v1-27-42]]

^<<v1-27-42,42>>^ When the words of Eʹsau her older son were told to Re·bekʹah, she at once sent and called Jacob her younger son and said to him: “Look! Eʹsau your brother is comforting himself^&#42;1^ in regard to you—to kill you.

[NOTE]
====
. Or, “is nursing revenge.”
====

[[v1-27-43]]

^<<v1-27-43,43>>^ Now, then, my son, listen to my voice and get up, run away to Laʹban my brother at Haʹran.

[[v1-27-44]]

^<<v1-27-44,44>>^ And you must dwell with him for some days until the rage of your brother calms down,

[[v1-27-45]]

^<<v1-27-45,45>>^ until the anger of your brother turns away from you and he has forgotten what you have done to him. And I shall certainly send and get you from there. Why should I be bereaved also of both of YOU in one day?”

[[v1-27-46]]

^<<v1-27-46,46>>^ After that Re·bekʹah kept saying to Isaac: “I have come to abhor this life of mine because of the daughters of Heth. If Jacob ever takes a wife from the daughters of Heth like these from the daughters of the land, of what good^&#42;1^ is life to me?”

[NOTE]
====
. Or, “use.”
====

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]