include::./index.adoc[]

[[v1-46-0]]
=== Genesis, 46
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v1-46-1]]

^<<v1-46-1,1>>^ Accordingly Israel and all who were his pulled out and came to Beʹer-sheʹba, and he proceeded to sacrifice sacrifices to the God of his father Isaac.

[[v1-46-2]]

^<<v1-46-2,2>>^ Then God talked to Israel in visions of the night and said: “Jacob, Jacob!” to which he said: “Here I am!”

[[v1-46-3]]

^<<v1-46-3,3>>^ And he went on to say: “I am the &#91;true&#93; God, the God of your father.^&#42;1^ Do not be afraid to go down to Egypt, for I shall constitute you there into a great nation.

[NOTE]
====
. Or, “I, the [true] God, am the God of your father.”
====

[[v1-46-4]]

^<<v1-46-4,4>>^ I myself shall go down with you to Egypt and I myself shall surely bring you up also; and Joseph will lay his hand upon your eyes.”^&#42;1^

[NOTE]
====
. That is, to close them at Jacob’s death.
====

[[v1-46-5]]

^<<v1-46-5,5>>^ After that Jacob got up out of Beʹer-sheʹba, and the sons of Israel continued transporting Jacob their father and their little ones and their wives in the wagons that Pharʹaoh had sent to transport him.

[[v1-46-6]]

^<<v1-46-6,6>>^ Further, they took along their herds and their goods, which they had accumulated in the land of Caʹnaan. Eventually they came into Egypt, Jacob and all his offspring with him.

[[v1-46-7]]

^<<v1-46-7,7>>^ He brought his sons and his sons’ sons with him, his daughters and his sons’ daughters, even all his offspring, with him into Egypt.

[[v1-46-8]]

^<<v1-46-8,8>>^ Now these are the names of Israel’s sons who came into Egypt: Jacob and his sons: Jacob’s firstborn was Reuʹben.

[[v1-46-9]]

^<<v1-46-9,9>>^ And the sons of Reuʹben were Haʹnoch and Palʹlu and Hezʹron and Carʹmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ And the sons of Simʹe·on were Jem·uʹel and Jaʹmin and Oʹhad and Jaʹchin and Zoʹhar and Shaʹul the son of a Caʹnaan·ite woman.

[[v1-46-11]]

^<<v1-46-11,11>>^ And the sons of Leʹvi were Gerʹshon, Koʹhath and Me·rarʹi.

[[v1-46-12]]

^<<v1-46-12,12>>^ And the sons of Judah were Er and Oʹnan and Sheʹlah and Peʹrez and Zeʹrah. However, Er and Oʹnan died in the land of Caʹnaan.
And the sons of Peʹrez came to be Hezʹron and Haʹmul.

[[v1-46-13]]

^<<v1-46-13,13>>^ And the sons of Isʹsa·char were Toʹla and Puʹvah and Iob and Shimʹron.

[[v1-46-14]]

^<<v1-46-14,14>>^ And the sons of Zebʹu·lun were Seʹred and Eʹlon and Jahʹle·el.

[[v1-46-15]]

^<<v1-46-15,15>>^ These are the sons of Leʹah, whom she bore to Jacob in Padʹdan-aʹram, together with his daughter Diʹnah. All the souls of his sons and of his daughters were thirty-three.

[[v1-46-16]]

^<<v1-46-16,16>>^ And the sons of Gad were Ziphʹi·on and Hagʹgi, Shuʹni and Ezʹbon, Eʹri and Ar·oʹdi and A·reʹli.

[[v1-46-17]]

^<<v1-46-17,17>>^ And the sons of Ashʹer were Imʹnah and Ishʹvah and Ishʹvi and Be·riʹah, and there was Seʹrah their sister.
And the sons of Be·riʹah were Heʹber and Malʹchi·el.

[[v1-46-18]]

^<<v1-46-18,18>>^ These are the sons of Zilʹpah, whom Laʹban gave to his daughter Leʹah. In time she bore these to Jacob: sixteen souls.

[[v1-46-19]]

^<<v1-46-19,19>>^ The sons of Rachel, Jacob’s wife, were Joseph and Benjamin.

[[v1-46-20]]

^<<v1-46-20,20>>^ And there came to be born to Joseph in the land of Egypt Ma·nasʹseh and Eʹphra·im,^&#42;1^ whom Asʹe·nath the daughter of Pot·iʹphe·ra the priest of On bore to him.

[NOTE]
====
. After “Ephraim” LXX adds five more names, as it reads: “But there were sons born to Manasseh, whom his Syrian concubine bore to him, namely, Machir. And Machir became father to Galaad. But the sons of Ephraim, Manasseh’s brother, were Sutalaam and Taam. And the sons of Sutalaam were Edem.” This may explain why LXX, in Ge 46:27 and Ex 1:5, and Stephen, in Ac 7:14, count 75 souls instead of 70.
====

[[v1-46-21]]

^<<v1-46-21,21>>^ And the sons of Benjamin were Beʹla and Beʹcher and Ashʹbel, Geʹra and Naʹa·man, Eʹhi and Rosh, Mupʹpim and Hupʹpim and Ard.

[[v1-46-22]]

^<<v1-46-22,22>>^ These are the sons of Rachel who were born to Jacob. All the souls were fourteen.

[[v1-46-23]]

^<<v1-46-23,23>>^ And the sons of Dan were Huʹshim.

[[v1-46-24]]

^<<v1-46-24,24>>^ And the sons of Naphʹta·li were Jahʹze·el and Guʹni and Jeʹzer and Shilʹlem.

[[v1-46-25]]

^<<v1-46-25,25>>^ These are the sons of Bilʹhah, whom Laʹban gave to his daughter Rachel. In time she bore these to Jacob; all the souls were seven.

[[v1-46-26]]

^<<v1-46-26,26>>^ All the souls who came to Jacob into Egypt were those who issued out of his upper thigh, aside from the wives of Jacob’s sons. All the souls were sixty-six.

[[v1-46-27]]

^<<v1-46-27,27>>^ And Joseph’s sons who were born to him in Egypt were two souls. All the souls of the house of Jacob who came into Egypt were seventy.^&#42;1^

[NOTE]
====
. “Seventy,” MTSyVg; LXX, “seventy-five.”
====

[[v1-46-28]]

^<<v1-46-28,28>>^ And he sent Judah in advance of him to Joseph to impart information ahead of him^&#42;1^ to Goʹshen. After that they came into the land of Goʹshen.^&#42;2^

[NOTE]
====
. “To Joseph, that he might make announcement to him,” Vg.
. “To Joseph to meet him at Heroopolis in the land of Rameses,” LXX.
====

[[v1-46-29]]

^<<v1-46-29,29>>^ Then Joseph had his chariot made ready and went up to meet Israel his father at Goʹshen. When he appeared to him he at once fell upon his neck and gave way to tears upon his neck again and again.

[[v1-46-30]]

^<<v1-46-30,30>>^ Finally Israel said to Joseph: “This time I am willing to die, now that I have seen your face, since you are still alive.”

[[v1-46-31]]

^<<v1-46-31,31>>^ Then Joseph said to his brothers and to his father’s household: “Let me go up and report to Pharʹaoh and say to him, ‘My brothers and my father’s household who were in the land of Caʹnaan have come here to me.

[[v1-46-32]]

^<<v1-46-32,32>>^ And the men are shepherds, because they became stock raisers; and their flocks and their herds and all they have they have brought here.’

[[v1-46-33]]

^<<v1-46-33,33>>^ And what must occur is that when Pharʹaoh will call YOU and actually say, ‘What is YOUR occupation?’

[[v1-46-34]]

^<<v1-46-34,34>>^ YOU must say, ‘Your servants have continued to be stock raisers from our youth until now, both we and our forefathers,’ in order that YOU may dwell in the land of Goʹshen, because every herder of sheep is a detestable thing to Egypt.”

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]