include::./index.adoc[]

[[v41-4-0]]
=== According to Mark, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-4-1]]

^<<v41-4-1,1>>^ And he again started teaching beside the sea. And a very great crowd gathered near him, so that he went aboard a boat and sat out on the sea, but all the crowd beside the sea were on the shore.

[[v41-4-2]]

^<<v41-4-2,2>>^ So he began to teach them many things with illustrations and to say to them in his teaching:

[[v41-4-3]]

^<<v41-4-3,3>>^ “Listen. Look! The sower went out to sow.

[[v41-4-4]]

^<<v41-4-4,4>>^ And as he was sowing, some &#91;seed&#93; fell alongside the road, and the birds came and ate it up.

[[v41-4-5]]

^<<v41-4-5,5>>^ And other &#91;seed&#93; fell upon the rocky place where it, of course, did not have much soil, and it immediately sprang up because of not having depth of soil.

[[v41-4-6]]

^<<v41-4-6,6>>^ But when the sun rose, it was scorched, and for not having root it withered.

[[v41-4-7]]

^<<v41-4-7,7>>^ And other &#91;seed&#93; fell among the thorns, and the thorns came up and choked it, and it yielded no fruit.

[[v41-4-8]]

^<<v41-4-8,8>>^ But others fell upon the fine soil, and, coming up and increasing, they began to yield fruit, and they were bearing thirtyfold, and sixty and a hundred.”

[[v41-4-9]]

^<<v41-4-9,9>>^ So he added the word: “Let him that has ears to listen listen.”

[[v41-4-10]]

^<<v41-4-10,10>>^ Now when he got to be alone, those around him with the twelve began questioning him on the illustrations.

[[v41-4-11]]

^<<v41-4-11,11>>^ And he proceeded to say to them: “To YOU the sacred secret of the kingdom of God has been given, but to those outside all things occur in illustrations,

[[v41-4-12]]

^<<v41-4-12,12>>^ in order that, though looking, they may look and yet not see, and, though hearing, they may hear and yet not get the sense of it, nor ever turn back and forgiveness be given them.”

[[v41-4-13]]

^<<v41-4-13,13>>^ Further, he said to them: “YOU do not know this illustration, and so how will YOU understand all the other illustrations?

[[v41-4-14]]

^<<v41-4-14,14>>^ “The sower sows the word.

[[v41-4-15]]

^<<v41-4-15,15>>^ These, then, are the ones alongside the road where the word is sown; but as soon as they have heard &#91;it&#93; Satan comes and takes away the word that was sown in them.

[[v41-4-16]]

^<<v41-4-16,16>>^ And likewise these are the ones sown upon the rocky places: as soon as they have heard the word, they accept it with joy.

[[v41-4-17]]

^<<v41-4-17,17>>^ Yet they have no root in themselves, but they continue for a time; then as soon as tribulation or persecution arises because of the word, they are stumbled.

[[v41-4-18]]

^<<v41-4-18,18>>^ There are still others who are sown among the thorns; these are the ones that have heard the word,

[[v41-4-19]]

^<<v41-4-19,19>>^ but the anxieties of this system of things^&#42;1^ and the deceptive power of riches and the desires for the rest of the things make inroads and choke the word, and it becomes unfruitful.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v41-4-20]]

^<<v41-4-20,20>>^ Finally, the ones that were sown on the fine soil are those who listen to the word and favorably receive it and bear fruit thirtyfold and sixty and a hundred.”

[[v41-4-21]]

^<<v41-4-21,21>>^ And he went on to say to them: “A lamp is not brought to be put under a measuring basket or under a bed, is it? It is brought to be put upon a lampstand, is it not?

[[v41-4-22]]

^<<v41-4-22,22>>^ For there is nothing hidden except for the purpose of being exposed; nothing has become carefully concealed but for the purpose of coming into the open.

[[v41-4-23]]

^<<v41-4-23,23>>^ Whoever has ears to listen, let him listen.”

[[v41-4-24]]

^<<v41-4-24,24>>^ He further said to them: “Pay attention to what YOU are hearing. With the measure that YOU are measuring out, YOU will have it measured out to YOU, yes, YOU will have more added to YOU.

[[v41-4-25]]

^<<v41-4-25,25>>^ For he that has will have more given to him; but he that does not have, even what he has will be taken away from him.”

[[v41-4-26]]

^<<v41-4-26,26>>^ So he went on to say: “In this way the kingdom of God is just as when a man casts the seed upon the ground,

[[v41-4-27]]

^<<v41-4-27,27>>^ and he sleeps at night and rises up by day, and the seed sprouts and grows tall, just how he does not know.

[[v41-4-28]]

^<<v41-4-28,28>>^ Of its own self the ground bears fruit gradually, first the grass-blade, then the stalk head, finally the full grain in the head.

[[v41-4-29]]

^<<v41-4-29,29>>^ But as soon as the fruit permits it, he thrusts in the sickle, because the harvesttime has come.”

[[v41-4-30]]

^<<v41-4-30,30>>^ And he went on to say: “With what are we to liken the kingdom of God, or in what illustration shall we set it out?

[[v41-4-31]]

^<<v41-4-31,31>>^ Like a mustard grain, which at the time it was sown in the ground was the tiniest of all the seeds that are on the earth—

[[v41-4-32]]

^<<v41-4-32,32>>^ but when it has been sown, it comes up and becomes greater than all other vegetables and produces great branches, so that the birds of the heaven are able to find lodging under its shadow.”

[[v41-4-33]]

^<<v41-4-33,33>>^ So with many illustrations of that sort he would speak the word to them, as far as they were able to listen.

[[v41-4-34]]

^<<v41-4-34,34>>^ Indeed, without an illustration he would not speak to them, but privately to his disciples he would explain all things.

[[v41-4-35]]

^<<v41-4-35,35>>^ And on that day, when evening had fallen, he said to them: “Let us cross to the other shore.”

[[v41-4-36]]

^<<v41-4-36,36>>^ So, after they had dismissed the crowd, they took him in the boat, just as he was, and there were other boats with him.

[[v41-4-37]]

^<<v41-4-37,37>>^ Now a great violent windstorm broke out, and the waves kept dashing into the boat, so that the boat was close to being swamped.

[[v41-4-38]]

^<<v41-4-38,38>>^ But he was in the stern, sleeping upon a pillow. So they woke him up and said to him: “Teacher, do you not care that we are about to perish?”

[[v41-4-39]]

^<<v41-4-39,39>>^ With that he roused himself and rebuked the wind and said to the sea: “Hush! Be quiet!” And the wind abated, and a great calm set in.

[[v41-4-40]]

^<<v41-4-40,40>>^ So he said to them: “Why are YOU fainthearted? Do YOU not yet have any faith?”

[[v41-4-41]]

^<<v41-4-41,41>>^ But they felt an unusual fear, and they would say to one another: “Who really is this, because even the wind and the sea obey him?”

'''

xref:041-mark/041-mark-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-mark/041-mark-005.adoc#v41-5-0[Próximo Capítulo &#62;]