include::./index.adoc[]

[[v41-15-0]]
=== According to Mark, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-15-1]]

^<<v41-15-1,1>>^ And immediately at dawn the chief priests with the older men and the scribes, even the whole Sanʹhe·drin, conducted a consultation, and they bound Jesus and led him off and handed him over to Pilate.

[[v41-15-2]]

^<<v41-15-2,2>>^ So Pilate put the question to him: “Are you the king of the Jews?” In answer to him he said: “You yourself say &#91;it&#93;.”

[[v41-15-3]]

^<<v41-15-3,3>>^ But the chief priests proceeded to accuse him of many things.

[[v41-15-4]]

^<<v41-15-4,4>>^ Now Pilate began questioning him again, saying: “Have you no reply to make? See how many charges they are bringing against you.”

[[v41-15-5]]

^<<v41-15-5,5>>^ But Jesus made no further answer, so that Pilate began to marvel.

[[v41-15-6]]

^<<v41-15-6,6>>^ Well, from festival to festival he used to release to them one prisoner, whom they petitioned for.

[[v41-15-7]]

^<<v41-15-7,7>>^ At the time there was the so-called Bar·abʹbas in bonds with the seditionists, who in their sedition had committed murder.

[[v41-15-8]]

^<<v41-15-8,8>>^ So the crowd came on up and started to make petition according to what he used to do for them.

[[v41-15-9]]

^<<v41-15-9,9>>^ Pilate responded to them, saying: “Do YOU want me to release to YOU the king of the Jews?”

[[v41-15-10]]

^<<v41-15-10,10>>^ For he was aware that because of envy the chief priests had handed him over.

[[v41-15-11]]

^<<v41-15-11,11>>^ But the chief priests stirred up the crowd to have him release Bar·abʹbas to them, instead.

[[v41-15-12]]

^<<v41-15-12,12>>^ Again in reply Pilate was saying to them: “What, then, shall I do with him whom YOU call the king of the Jews?”

[[v41-15-13]]

^<<v41-15-13,13>>^ Once more they cried out: “Impale him!”^&#42;1^

[NOTE]
====
. Or, “Fasten him on a stake (pole).” See App 5C.
====

[[v41-15-14]]

^<<v41-15-14,14>>^ But Pilate went on to say to them: “Why, what bad thing did he do?” Still they cried out all the more: “Impale him!”

[[v41-15-15]]

^<<v41-15-15,15>>^ At that Pilate, wishing to satisfy the crowd, released Bar·abʹbas to them, and, after having Jesus whipped, he handed him over to be impaled.

[[v41-15-16]]

^<<v41-15-16,16>>^ The soldiers now led him off into the courtyard, that is, into the governor’s palace; and they called the whole body of troops together,

[[v41-15-17]]

^<<v41-15-17,17>>^ and they decked him with purple and braided a crown of thorns and put it on him.

[[v41-15-18]]

^<<v41-15-18,18>>^ And they started greeting him: “Good day, you King of the Jews!”

[[v41-15-19]]

^<<v41-15-19,19>>^ Also, they would hit him on the head with a reed and spit upon him and, bending their knees, they would do obeisance to him.

[[v41-15-20]]

^<<v41-15-20,20>>^ Finally, when they had made fun of him, they stripped him of the purple and put his outer garments upon him. And they led him out to impale him.^&#42;1^

[NOTE]
====
. See vs 13 ftn.
====

[[v41-15-21]]

^<<v41-15-21,21>>^ Also, they impressed into service a passerby, a certain Simon of Cy·reʹne, coming from the country, the father of Alexander and Ruʹfus, that he should lift up his torture stake.^&#42;1^

[NOTE]
====
. See App 5C.
====

[[v41-15-22]]

^<<v41-15-22,22>>^ So they brought him to the place Golʹgo·tha, which means, when translated, Skull Place.^&#42;1^

[NOTE]
====
. “Skull Place.” Gr., Kra·niʹou Toʹpos; Lat., Cal·vaʹri·ae loʹcus.
====

[[v41-15-23]]

^<<v41-15-23,23>>^ Here they tried to give him wine drugged with myrrh, but he would not take it.

[[v41-15-24]]

^<<v41-15-24,24>>^ And they impaled him and distributed his outer garments by casting the lot over them as to who takes what.

[[v41-15-25]]

^<<v41-15-25,25>>^ It was now the third hour,^&#42;1^ and they impaled him.

[NOTE]
====
. “Third hour,” that is, about 9 a.m.
====

[[v41-15-26]]

^<<v41-15-26,26>>^ And the inscription of the charge against him was written above, “The King of the Jews.”

[[v41-15-27]]

^<<v41-15-27,27>>^ Moreover, they impaled two robbers with him, one on his right and one on his left.

[[v41-15-28]]

^<<v41-15-28,28>>^ ^&#42;1^ ——

[NOTE]
====
. אABCD omit; VgSyh,p, “And the scripture was fulfilled that says, ‘And he was reckoned with lawless ones.’ ”
====

[[v41-15-29]]

^<<v41-15-29,29>>^ And those going by would speak abusively to him, wagging their heads and saying: “Bah! You would-be thrower-down of the temple^&#42;1^ and builder of it in three days’ time,

[NOTE]
====
. See 14:58 ftn.
====

[[v41-15-30]]

^<<v41-15-30,30>>^ save yourself by coming down off the torture stake.”

[[v41-15-31]]

^<<v41-15-31,31>>^ In like manner also the chief priests were making fun among themselves with the scribes and saying: “Others he saved; himself he cannot save!

[[v41-15-32]]

^<<v41-15-32,32>>^ Let the Christ the King of Israel now come down off the torture stake, that we may see and believe.” Even those impaled together with him were reproaching him.

[[v41-15-33]]

^<<v41-15-33,33>>^ When it became the sixth hour^&#42;1^ a darkness fell over the whole land until the ninth hour.^&#42;2^

[NOTE]
====
. “Sixth hour,” that is, about 12 noon.
. “Ninth hour,” that is, about 3 p.m.
====

[[v41-15-34]]

^<<v41-15-34,34>>^ And at the ninth hour Jesus called out with a loud voice: “Eʹli, Eʹli, laʹma sa·bach·thaʹni?”^&#42;1^ which means, when translated: “My God, my God, why have you forsaken me?”

[NOTE]
====
. “Eli, Eli, lama sabachthani?” Compare Ps 22:1 ftn, “Me.”
====

[[v41-15-35]]

^<<v41-15-35,35>>^ And some of those standing near, on hearing it, began to say: “See! He is calling E·liʹjah.”^&#42;1^

[NOTE]
====
. Meaning “My God Is Jehovah.” J17,​18(Heb.), ʼE·li·yaʹhu.
====

[[v41-15-36]]

^<<v41-15-36,36>>^ But a certain one ran, soaked a sponge with sour wine, put it on a reed, and began giving him a drink, saying: “LET &#91;him&#93; be! Let us see whether E·liʹjah comes to take him down.”

[[v41-15-37]]

^<<v41-15-37,37>>^ But Jesus let out a loud cry and expired.

[[v41-15-38]]

^<<v41-15-38,38>>^ And the curtain of the sanctuary^&#42;1^ was rent in two from top to bottom.

[NOTE]
====
. See 14:58 ftn.
====

[[v41-15-39]]

^<<v41-15-39,39>>^ Now, when the army officer^&#42;1^ that was standing by with him in view saw he had expired under these circumstances, he said: “Certainly this man was God’s Son.”^&#42;2^

[NOTE]
====
. Or, “centurion.” Gr., ken·ty·riʹon; an officer in command of 100 soldiers.
. Or, “a son of God”; or, “a son of a god.”
====

[[v41-15-40]]

^<<v41-15-40,40>>^ There were also women viewing from a distance, among them Mary Magʹda·lene as well as Mary the mother of James the Less and of Joʹses,^&#42;1^ and Sa·loʹme,

[NOTE]
====
. “Joses,” א*ACSyh,p; אcBD, “Josetos”; ItVgSys, “Joseph.”
====

[[v41-15-41]]

^<<v41-15-41,41>>^ who used to accompany him and minister to him when he was in Galʹi·lee, and many other women who had come up together with him to Jerusalem.

[[v41-15-42]]

^<<v41-15-42,42>>^ Now as it was already late in the afternoon, and since it was Preparation, that is, the day before the sabbath,

[[v41-15-43]]

^<<v41-15-43,43>>^ there came Joseph of Ar·i·ma·theʹa, a reputable member of the Council, who also himself was waiting for the kingdom of God. He took courage to go in before Pilate and asked for the body of Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ But Pilate wondered whether he was already dead, and, summoning the army officer, he asked him whether he had already died.

[[v41-15-45]]

^<<v41-15-45,45>>^ So after making certain from the army officer, he granted the corpse to Joseph.

[[v41-15-46]]

^<<v41-15-46,46>>^ Accordingly he bought fine linen and took him down, wrapped him in the fine linen and laid him in a tomb which was quarried out of a rock-mass; and he rolled a stone up to the door of the memorial tomb.

[[v41-15-47]]

^<<v41-15-47,47>>^ But Mary Magʹda·lene and Mary the mother of Joʹses^&#42;1^ continued looking at where he had been laid.

[NOTE]
====
. “Joses,” CSyh,p; אcB, “Josetos”; AVg, “Joseph.”
====

'''

xref:041-mark/041-mark-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-mark/041-mark-016.adoc#v41-16-0[Próximo Capítulo &#62;]