include::./index.adoc[]

[[v41-7-0]]
=== According to Mark, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-7-1]]

^<<v41-7-1,1>>^ Now the Pharisees and some of the scribes that had come from Jerusalem gathered about him.

[[v41-7-2]]

^<<v41-7-2,2>>^ And when they saw some of his disciples eat their meal with defiled hands, that is, unwashed ones—

[[v41-7-3]]

^<<v41-7-3,3>>^ for the Pharisees and all the Jews do not eat unless they wash their hands up to the elbow,^&#42;1^ holding fast the tradition of the men of former times,

[NOTE]
====
. Or, “wash their hands with the fist.”
====

[[v41-7-4]]

^<<v41-7-4,4>>^ and, when back from market, they do not eat unless they cleanse themselves by sprinkling; and there are many other traditions that they have received to hold fast, baptisms of cups and pitchers and copper vessels;—

[[v41-7-5]]

^<<v41-7-5,5>>^ so these Pharisees and scribes asked him: “Why is it your disciples do not conduct themselves according to the tradition of the men of former times, but they take their meal with defiled hands?”

[[v41-7-6]]

^<<v41-7-6,6>>^ He said to them: “Isaiah aptly prophesied about YOU hypocrites, as it is written, ‘This people honor me with &#91;their&#93; lips, but their hearts are far removed from me.

[[v41-7-7]]

^<<v41-7-7,7>>^ It is in vain that they keep worshiping me, because they teach as doctrines commands of men.’

[[v41-7-8]]

^<<v41-7-8,8>>^ Letting go the commandment of God, YOU hold fast the tradition of men.”

[[v41-7-9]]

^<<v41-7-9,9>>^ Further, he went on to say to them: “Adroitly YOU set aside the commandment of God in order to retain YOUR tradition.

[[v41-7-10]]

^<<v41-7-10,10>>^ For example, Moses said, ‘Honor your father and your mother,’ and, ‘Let him that reviles father or mother end up in death.’^&#42;1^

[NOTE]
====
. Or, “die without fail.”
====

[[v41-7-11]]

^<<v41-7-11,11>>^ But YOU men say, ‘If a man says to his father or his mother: “Whatever I have by which you may get benefit from me is corban,^&#42;1^ (that is, a gift dedicated to God,)”’^&#42;2^—

[NOTE]
====
. Gr., Kor·banʹ; Lat., corʹban; J17,​18,​22(Heb.), qor·banʹ. See Le 1:2 ftn, “Offering”; Ne 10:34 ftn.
. Or, “a votive gift.”
====

[[v41-7-12]]

^<<v41-7-12,12>>^ YOU men no longer let him do a single thing for his father or his mother,

[[v41-7-13]]

^<<v41-7-13,13>>^ and thus YOU make the word of God invalid by YOUR tradition which YOU handed down. And many things similar to this YOU do.”

[[v41-7-14]]

^<<v41-7-14,14>>^ So, calling the crowd to him again, he proceeded to say to them: “Listen to me, all of YOU, and get the meaning.

[[v41-7-15]]

^<<v41-7-15,15>>^ There is nothing from outside a man that passes into him that can defile him; but the things that issue forth out of a man are the things that defile a man.”

[[v41-7-16]]

^<<v41-7-16,16>>^ ^&#42;1^ ——

[NOTE]
====
. אB omit; ADVgSyh,p,sArm, “If anyone has ears to listen, let him listen.”
====

[[v41-7-17]]

^<<v41-7-17,17>>^ Now when he had entered a house away from the crowd, his disciples began to question him respecting the illustration.

[[v41-7-18]]

^<<v41-7-18,18>>^ So he said to them: “Are YOU also without perception like them? Are YOU not aware that nothing from outside that passes into a man can defile him,

[[v41-7-19]]

^<<v41-7-19,19>>^ since it passes, not into &#91;his&#93; heart, but into &#91;his&#93; intestines, and it passes out into the sewer?”^&#42;1^ Thus he declared all foods clean.^&#42;2^

[NOTE]
====
. Or, “cesspool; water closet; privy.”
. According to אAB; some mss, “into the sewer, thus proving all foods clean?”
====

[[v41-7-20]]

^<<v41-7-20,20>>^ Further, he said: “That which issues forth out of a man is what defiles a man;

[[v41-7-21]]

^<<v41-7-21,21>>^ for from inside, out of the heart of men, injurious reasonings issue forth: fornications,^&#42;1^ thieveries, murders,

[NOTE]
====
. “Fornications.” Gr., por·neiʹai; Lat., for·ni·ca·ti·oʹnes; J18,​22(Heb.), zenu·nimʹ. See App 5A.
====

[[v41-7-22]]

^<<v41-7-22,22>>^ adulteries, covetings, acts of wickedness, deceit, loose conduct,^&#42;1^ an envious eye,^&#42;2^ blasphemy, haughtiness, unreasonableness.

[NOTE]
====
. “Loose conduct.” Gr., a·selʹgei·a; Vgc(Lat.), im·pu·di·ciʹti·ae; J22(Heb.), zim·mahʹ. See Ga 5:19 ftn, “Conduct.”
. Or, “wicked eye.”
====

[[v41-7-23]]

^<<v41-7-23,23>>^ All these wicked things issue forth from within and defile a man.”

[[v41-7-24]]

^<<v41-7-24,24>>^ From there he rose up and went into the regions of Tyre and Siʹdon. And he entered into a house and did not want anyone to get to know it. Yet he could not escape notice;

[[v41-7-25]]

^<<v41-7-25,25>>^ but immediately a woman whose little daughter had an unclean spirit heard about him and came and prostrated herself at his feet.

[[v41-7-26]]

^<<v41-7-26,26>>^ The woman was a Grecian, a Sy·ro·phoe·niʹcian nationally; and she kept asking him to expel the demon from her daughter.

[[v41-7-27]]

^<<v41-7-27,27>>^ But he began by saying to her: “First let the children be satisfied, for it is not right to take the bread of the children and throw it to the little dogs.”

[[v41-7-28]]

^<<v41-7-28,28>>^ In reply, however, she said to him: “Yes, sir, and yet the little dogs underneath the table eat of the crumbs of the little children.”

[[v41-7-29]]

^<<v41-7-29,29>>^ At that he said to her: “Because of saying this, go; the demon has gone out of your daughter.”

[[v41-7-30]]

^<<v41-7-30,30>>^ So she went away to her home and found the young child laid on the bed and the demon gone out.

[[v41-7-31]]

^<<v41-7-31,31>>^ Now coming back out of the regions of Tyre he went through Siʹdon to the sea of Galʹi·lee up through the midst of the regions of De·capʹo·lis.^&#42;1^

[NOTE]
====
. Or, “Ten Cities.” Gr., De·ka·poʹle·os.
====

[[v41-7-32]]

^<<v41-7-32,32>>^ Here they brought him a man deaf and with a speech impediment, and they entreated him to lay his hand upon him.

[[v41-7-33]]

^<<v41-7-33,33>>^ And he took him away from the crowd privately and put his fingers into the man’s ears and, after spitting, he touched his tongue.

[[v41-7-34]]

^<<v41-7-34,34>>^ And with a look up into heaven he sighed deeply and said to him: “Ephʹpha·tha,” that is, “Be opened.”

[[v41-7-35]]

^<<v41-7-35,35>>^ Well, his hearing powers were opened, and the impediment^&#42;1^ of his tongue was loosed, and he began speaking normally.

[NOTE]
====
. Or, “bond.”
====

[[v41-7-36]]

^<<v41-7-36,36>>^ With that he charged them not to tell anyone; but the more he would charge them, that much more they would proclaim it.

[[v41-7-37]]

^<<v41-7-37,37>>^ Indeed, they were being astounded in a most extraordinary way and they said: “He has done all things well. He even makes the deaf hear and the speechless speak.”

'''

xref:041-mark/041-mark-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-mark/041-mark-008.adoc#v41-8-0[Próximo Capítulo &#62;]