include::./index.adoc[]

[[v41-16-0]]
=== According to Mark, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-16-1]]

^<<v41-16-1,1>>^ So when the sabbath had passed, Mary Magʹda·lene, and Mary the mother of James, and Sa·loʹme bought spices in order to come and grease him.

[[v41-16-2]]

^<<v41-16-2,2>>^ And very early on the first day of the week they came to the memorial tomb, when the sun had risen.

[[v41-16-3]]

^<<v41-16-3,3>>^ And they were saying one to another: “Who will roll the stone away from the door of the memorial tomb for us?”

[[v41-16-4]]

^<<v41-16-4,4>>^ But when they looked up, they beheld that the stone had been rolled away, although it was very large.

[[v41-16-5]]

^<<v41-16-5,5>>^ When they entered into the memorial tomb, they saw a young man sitting on the right side clothed in a white robe, and they were stunned.

[[v41-16-6]]

^<<v41-16-6,6>>^ He said to them: “Stop being stunned. YOU are looking for Jesus the Naz·a·reneʹ, who was impaled.^&#42;1^ He was raised up, he is not here. See! The place where they laid him.

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v41-16-7]]

^<<v41-16-7,7>>^ But go, tell his disciples and Peter, ‘He is going ahead of YOU into Galʹi·lee; there YOU will see him, just as he told YOU.’”

[[v41-16-8]]

^<<v41-16-8,8>>^ So when they came out they fled from the memorial tomb, for trembling and strong emotion were gripping them. And they told nobody anything, for they were in fear.^&#42;1^

[NOTE]
====
. Manuscript L 019 (Codex Regius of the eighth cent.) contains both long and short conclusions after vs 8, giving the short conclusion first and prefixing to each conclusion a note that says these passages are current in some quarters, while evidently not recognizing either conclusion as authoritative.
====

_SHORT CONCLUSION_

_Some late manuscripts and versions contain a short conclusion after Mark 16:8, as follows:_

But all the things that had been commanded they related briefly to those around Peter. Further, after these things, Jesus himself sent out through them from the east to the west the holy and incorruptible proclamation of everlasting salvation.

[NOTE]
====
. Manuscript L 019 (Codex Regius of the eighth cent.) contains both long and short conclusions after vs 8, giving the short conclusion first and prefixing to each conclusion a note that says these passages are current in some quarters, while evidently not recognizing either conclusion as authoritative.
====

_LONG CONCLUSION_

_Certain ancient manuscripts (ACD) and versions (VgSyc,p) add the following long conclusion, but which אBSysArm omit:_

[[v41-16-9]]

^<<v41-16-9,9>>^ After he rose early on the first day of the week he appeared first to Mary Magʹda·lene, from whom he had expelled seven demons.

[[v41-16-10]]

^<<v41-16-10,10>>^ She went and reported to those who had been with him, as they were mourning and weeping.

[[v41-16-11]]

^<<v41-16-11,11>>^ But they, when they heard he had come to life and had been viewed by her, did not believe.

[[v41-16-12]]

^<<v41-16-12,12>>^ Moreover, after these things he appeared in another form to two of them walking along, as they were going into the country;

[[v41-16-13]]

^<<v41-16-13,13>>^ and they came back and reported to the rest. Neither did they believe these.

[[v41-16-14]]

^<<v41-16-14,14>>^ But later he appeared to the eleven themselves as they were reclining at the table, and he reproached their lack of faith and hardheartedness, because they did not believe those who had beheld him now raised up from the dead.

[[v41-16-15]]

^<<v41-16-15,15>>^ And he said to them: “Go into all the world and preach the good news to all creation.

[[v41-16-16]]

^<<v41-16-16,16>>^ He that believes and is baptized will be saved, but he that does not believe will be condemned.

[[v41-16-17]]

^<<v41-16-17,17>>^ Furthermore, these signs will accompany those believing: By the use of my name they will expel demons, they will speak with tongues,

[[v41-16-18]]

^<<v41-16-18,18>>^ and with their hands they will pick up serpents, and if they drink anything deadly it will not hurt them at all. They will lay their hands upon sick persons, and these will become well.”

[[v41-16-19]]

^<<v41-16-19,19>>^ So, then, the Lord Jesus, after having spoken to them, was taken up to heaven and sat down at the right hand of God.

[[v41-16-20]]

^<<v41-16-20,20>>^ They, accordingly, went out and preached everywhere, while the Lord worked with them and backed up the message through the accompanying signs.

'''

xref:041-mark/041-mark-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-luke/042-luke-001.adoc#v42-1-0[Próximo Capítulo &#62;]