include::./index.adoc[]

[[v41-13-0]]
=== According to Mark, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-13-1]]

^<<v41-13-1,1>>^ As he was going out of the temple one of his disciples said to him: “Teacher, see! what sort of stones and what sort of buildings!”

[[v41-13-2]]

^<<v41-13-2,2>>^ However, Jesus said to him: “Do you behold these great buildings? By no means will a stone be left here upon a stone and not be thrown down.”

[[v41-13-3]]

^<<v41-13-3,3>>^ And as he was sitting on the Mount of Olives with the temple in view, Peter and James and John and Andrew began to ask him privately:

[[v41-13-4]]

^<<v41-13-4,4>>^ “Tell us, When will these things be, and what will be the sign when all these things are destined to come to a conclusion?”^&#42;1^

[NOTE]
====
. Or, “joint end.” See Mt 13:39 ftn, “Conclusion.”
====

[[v41-13-5]]

^<<v41-13-5,5>>^ So Jesus started to say to them: “Look out that nobody misleads YOU.

[[v41-13-6]]

^<<v41-13-6,6>>^ Many will come on the basis of my name, saying, ‘I am he,’ and will mislead many.

[[v41-13-7]]

^<<v41-13-7,7>>^ Moreover, when YOU hear of wars and reports of wars, do not be terrified; &#91;these things&#93; must take place, but the end^&#42;1^ is not yet.

[NOTE]
====
. Or, “accomplished end; completed end; finish.” Gr., τέλος (teʹlos).
====

[[v41-13-8]]

^<<v41-13-8,8>>^ “For nation will rise^&#42;1^ against nation and kingdom against kingdom, there will be earthquakes^&#42;2^ in one place after another, there will be food shortages. These are a beginning of pangs of distress.

[NOTE]
====
. Or, “be stirred up; be roused up.”
. “Earthquakes.” Gr., sei·smoiʹ.
====

[[v41-13-9]]

^<<v41-13-9,9>>^ “As for YOU, look out for yourselves; people will deliver YOU up to local courts,^&#42;1^ and YOU will be beaten in synagogues and be put on the stand before governors and kings for my sake, for a witness^&#42;2^ to them.

[NOTE]
====
. Or, “to Lesser Sanhedrins.”
. “A witness.” Gr., mar·tyʹri·on; Lat., te·sti·moʹni·um.
====

[[v41-13-10]]

^<<v41-13-10,10>>^ Also, in all the nations the good news has to be preached^&#42;1^ first.

[NOTE]
====
. Or, “to be heralded.” Gr., ke·ry·khtheʹnai; Lat., prae·di·caʹri. Compare Da 5:29 ftn, “Heralded.”
====

[[v41-13-11]]

^<<v41-13-11,11>>^ But when they are leading YOU along to deliver YOU up, do not be anxious beforehand about what to speak; but whatever is given YOU in that hour, speak this, for YOU are not the ones speaking, but the holy spirit is.

[[v41-13-12]]

^<<v41-13-12,12>>^ Furthermore, brother will deliver brother over to death, and a father a child, and children will rise up against parents and have them put to death;

[[v41-13-13]]

^<<v41-13-13,13>>^ and YOU will be objects of hatred by all people on account of my name. But he that has endured to the end^&#42;1^ is the one that will be saved.

[NOTE]
====
. See vs 7 ftn.
====

[[v41-13-14]]

^<<v41-13-14,14>>^ “However, when YOU catch sight of the disgusting thing that causes desolation standing where it ought not (let the reader use discernment), then let those in Ju·deʹa begin fleeing to the mountains.

[[v41-13-15]]

^<<v41-13-15,15>>^ Let the man on the housetop not come down, nor go inside to take anything out of his house;

[[v41-13-16]]

^<<v41-13-16,16>>^ and let the man in the field not return to the things behind to pick up his outer garment.

[[v41-13-17]]

^<<v41-13-17,17>>^ Woe to the pregnant women and those suckling a baby in those days!

[[v41-13-18]]

^<<v41-13-18,18>>^ Keep praying that it may not occur in wintertime;

[[v41-13-19]]

^<<v41-13-19,19>>^ for those days will be &#91;days of&#93; a tribulation such as has not occurred from &#91;the&#93; beginning of the creation which God created until that time,^&#42;1^ and will not occur again.

[NOTE]
====
. Lit., “until the present time.”
====

[[v41-13-20]]

^<<v41-13-20,20>>^ In fact, unless Jehovah^&#42;1^ had cut short the days, no flesh would be saved. But on account of the chosen ones whom he has chosen he has cut short the days.

[NOTE]
====
. See App 1D.
====

[[v41-13-21]]

^<<v41-13-21,21>>^ “Then, too, if anyone says to YOU, ‘See! Here is the Christ,’ ‘See! There he is,’ do not believe &#91;it&#93;.

[[v41-13-22]]

^<<v41-13-22,22>>^ For false Christs and false prophets will arise and will give signs and wonders to lead astray, if possible, the chosen ones.

[[v41-13-23]]

^<<v41-13-23,23>>^ YOU, then, watch out; I have told YOU all things beforehand.

[[v41-13-24]]

^<<v41-13-24,24>>^ “But in those days, after that tribulation, the sun will be darkened, and the moon will not give its light,

[[v41-13-25]]

^<<v41-13-25,25>>^ and the stars will be falling out of heaven, and the powers that are in the heavens will be shaken.

[[v41-13-26]]

^<<v41-13-26,26>>^ And then they will see the Son of man coming^&#42;1^ in clouds with great power and glory.

[NOTE]
====
. “Coming.” Gr., er·khoʹme·non.
====

[[v41-13-27]]

^<<v41-13-27,27>>^ And then he will send forth the angels and will gather his chosen ones together from the four winds, from earth’s extremity to heaven’s extremity.

[[v41-13-28]]

^<<v41-13-28,28>>^ “Now from the fig tree learn the illustration: Just as soon as its young branch grows tender and puts forth its leaves, YOU know that summer is near.

[[v41-13-29]]

^<<v41-13-29,29>>^ Likewise also YOU, when YOU see these things happening, know that he is near, at the doors.

[[v41-13-30]]

^<<v41-13-30,30>>^ Truly I say to YOU that this generation^&#42;1^ will by no means pass away until all these things happen.

[NOTE]
====
. “Generation.” Gr., ge·ne·aʹ; different from geʹnos, “race,” as in 1Pe 2:9.
====

[[v41-13-31]]

^<<v41-13-31,31>>^ Heaven and earth will pass away, but my words will not pass away.

[[v41-13-32]]

^<<v41-13-32,32>>^ “Concerning that day or the hour nobody knows, neither the angels in heaven nor the Son, but the Father.

[[v41-13-33]]

^<<v41-13-33,33>>^ Keep looking, keep awake, for YOU do not know when the appointed time is.

[[v41-13-34]]

^<<v41-13-34,34>>^ It is like a man traveling abroad that left his house and gave the authority to his slaves, to each one his work, and commanded the doorkeeper to keep on the watch.

[[v41-13-35]]

^<<v41-13-35,35>>^ Therefore keep on the watch, for YOU do not know when the master of the house is coming, whether late in the day^&#42;1^ or at midnight^&#42;2^ or at cockcrowing^&#42;3^ or early in the morning;^&#42;4^

[NOTE]
====
. “Late in the day.” The first watch according to the Gr. and Roman division of the night, from sunset until about 9 p.m.
. “Midnight.” The second watch according to the Gr. and Roman division of the night, from about 9 p.m. until midnight.
. “Cockcrowing.” The third watch according to the Gr. and Roman division of the night, from midnight until about 3 a.m.
. “Early in the morning.” The fourth watch according to the Gr. and Roman division of the night, from about 3 a.m. until sunrise.
====

[[v41-13-36]]

^<<v41-13-36,36>>^ in order that when he arrives suddenly, he does not find YOU sleeping.

[[v41-13-37]]

^<<v41-13-37,37>>^ But what I say to YOU I say to all, Keep on the watch.”

'''

xref:041-mark/041-mark-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-mark/041-mark-014.adoc#v41-14-0[Próximo Capítulo &#62;]