include::./index.adoc[]

[[v41-2-0]]
=== According to Mark, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-2-1]]

^<<v41-2-1,1>>^ However, after some days he again entered into Ca·perʹna·um and he was reported to be at home.

[[v41-2-2]]

^<<v41-2-2,2>>^ Consequently many gathered, so much so that there was no more room, not even about the door, and he began to speak the word to them.

[[v41-2-3]]

^<<v41-2-3,3>>^ And men came bringing him a paralytic carried by four.

[[v41-2-4]]

^<<v41-2-4,4>>^ But not being able to bring him right to &#91;Jesus&#93;^&#42;1^ on account of the crowd, they removed the roof over where he was, and having dug an opening they lowered the cot on which the paralytic was lying.

[NOTE]
====
. Lit., “him.”
====

[[v41-2-5]]

^<<v41-2-5,5>>^ And when Jesus saw their faith he said to the paralytic: “Child, your sins are forgiven.”

[[v41-2-6]]

^<<v41-2-6,6>>^ Now there were some of the scribes there, sitting and reasoning in their hearts:

[[v41-2-7]]

^<<v41-2-7,7>>^ “Why is this man talking in this manner? He is blaspheming. Who can forgive sins except one, God?”

[[v41-2-8]]

^<<v41-2-8,8>>^ But Jesus, having discerned immediately by his spirit that they were reasoning that way in themselves, said to them: “Why are YOU reasoning these things in YOUR hearts?

[[v41-2-9]]

^<<v41-2-9,9>>^ Which is easier, to say to the paralytic, ‘Your sins are forgiven,’ or to say, ‘Get up and pick up your cot and walk’?

[[v41-2-10]]

^<<v41-2-10,10>>^ But in order for YOU men to know that the Son of man has authority to forgive sins upon the earth,”—he said to the paralytic:

[[v41-2-11]]

^<<v41-2-11,11>>^ “I say to you, Get up, pick up your cot, and go to your home.”

[[v41-2-12]]

^<<v41-2-12,12>>^ At that he did get up, and immediately picked up his cot and walked out in front of them all, so that they were all simply carried away, and they glorified God, saying: “We never saw the like of it.”

[[v41-2-13]]

^<<v41-2-13,13>>^ Again he went out beside the sea; and all the crowd kept coming to him, and he began to teach them.

[[v41-2-14]]

^<<v41-2-14,14>>^ But as he was passing along, he caught sight of Leʹvi the &#91;son&#93; of Al·phaeʹus sitting at the tax office, and he said to him: “Be my follower.” And rising up he followed him.

[[v41-2-15]]

^<<v41-2-15,15>>^ Later he happened to be reclining at the table in his house, and many tax collectors and sinners were reclining with Jesus and his disciples, for there were many of them and they began following him.

[[v41-2-16]]

^<<v41-2-16,16>>^ But the scribes of the Pharisees, when they saw he was eating with the sinners and tax collectors, began saying to his disciples: “Does he eat with the tax collectors and sinners?”

[[v41-2-17]]

^<<v41-2-17,17>>^ Upon hearing this Jesus said to them: “Those who are strong do not need a physician, but those who are ill do. I came to call, not righteous people, but sinners.”

[[v41-2-18]]

^<<v41-2-18,18>>^ Now John’s disciples and the Pharisees practiced fasting. So they came and said to him: “Why is it the disciples of John and the disciples of the Pharisees practice fasting, but your disciples do not practice fasting?”

[[v41-2-19]]

^<<v41-2-19,19>>^ And Jesus said to them: “While the bridegroom is with them the friends of the bridegroom^&#42;1^ cannot fast, can they? As long as they have the bridegroom with them they cannot fast.

[NOTE]
====
. Lit., “the sons of the bridechamber.”
====

[[v41-2-20]]

^<<v41-2-20,20>>^ But days will come when the bridegroom will be taken away from them, and then they will fast in that day.

[[v41-2-21]]

^<<v41-2-21,21>>^ Nobody sews a patch of unshrunk cloth upon an old outer garment; if he does, its full strength pulls from it, the new from the old, and the tear becomes worse.

[[v41-2-22]]

^<<v41-2-22,22>>^ Also, nobody puts new wine into old wineskins; if he does, the wine bursts the skins, and the wine is lost as well as the skins. But people put new wine into new wineskins.”

[[v41-2-23]]

^<<v41-2-23,23>>^ Now it happened that he was proceeding through the grainfields on the sabbath, and his disciples started to make their way plucking the heads of grain.

[[v41-2-24]]

^<<v41-2-24,24>>^ So the Pharisees went saying to him: “Look here! Why are they doing on the sabbath what is not lawful?”

[[v41-2-25]]

^<<v41-2-25,25>>^ But he said to them: “Have YOU never once read what David did when he fell in need and got hungry, he and the men with him?

[[v41-2-26]]

^<<v41-2-26,26>>^ How he entered into the house of God, in the account about A·biʹa·thar the chief priest,^&#42;1^ and ate the loaves of presentation,^&#42;2^ which it is not lawful for anybody to eat except the priests, and he gave some also to the men who were with him?”

[NOTE]
====
. “In the account about Abiathar the chief priest.” Lit., “upon (at) Abiathar chief priest.” DWItmssSys, Mt 12:4 and Lu 6:4 omit. Compare similar construction in Mr 12:26; Lu 20:37.
. Or, “the showbread.”
====

[[v41-2-27]]

^<<v41-2-27,27>>^ So he went on to say to them: “The sabbath came into existence for the sake of man, and not man for the sake of the sabbath;

[[v41-2-28]]

^<<v41-2-28,28>>^ hence the Son of man is Lord even of the sabbath.”

'''

xref:041-mark/041-mark-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-mark/041-mark-003.adoc#v41-3-0[Próximo Capítulo &#62;]