include::./index.adoc[]

[[v41-9-0]]
=== According to Mark, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-9-1]]

^<<v41-9-1,1>>^ Furthermore, he went on to say to them: “Truly I say to YOU, There are some of those standing here that will not taste death at all until first they see the kingdom of God already come in power.”

[[v41-9-2]]

^<<v41-9-2,2>>^ Accordingly six days later Jesus took Peter and James and John along, and brought them up into a lofty mountain to themselves alone. And he was transfigured before them,

[[v41-9-3]]

^<<v41-9-3,3>>^ and his outer garments became glistening, far whiter than any clothes cleaner on earth could whiten them.

[[v41-9-4]]

^<<v41-9-4,4>>^ Also, E·liʹjah with Moses appeared to them, and they were conversing with Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ And responsively Peter said to Jesus: “Rabbi, it is fine for us to be here, so let us erect three tents, one for you and one for Moses and one for E·liʹjah.”

[[v41-9-6]]

^<<v41-9-6,6>>^ In fact, he did not know what response he should make, for they became quite fearful.

[[v41-9-7]]

^<<v41-9-7,7>>^ And a cloud formed, overshadowing them, and a voice came out of the cloud: “This is my Son, the beloved; listen to him.”

[[v41-9-8]]

^<<v41-9-8,8>>^ Suddenly, however, they looked around and saw no one with them any longer, except Jesus alone.

[[v41-9-9]]

^<<v41-9-9,9>>^ As they were coming down out of the mountain, he expressly ordered them not to relate to anybody what they saw, until after the Son of man had risen from the dead.

[[v41-9-10]]

^<<v41-9-10,10>>^ And they took the word to heart,^&#42;1^ but discussed among themselves what this rising from the dead meant.

[NOTE]
====
. Or, “they kept the word to themselves.”
====

[[v41-9-11]]

^<<v41-9-11,11>>^ And they began to question him, saying: “Why do the scribes say that first E·liʹjah must come?”

[[v41-9-12]]

^<<v41-9-12,12>>^ He said to them: “E·liʹjah does come first and restore all things; but how is it that it is written respecting the Son of man that he must undergo many sufferings and be treated as of no account?

[[v41-9-13]]

^<<v41-9-13,13>>^ But I say to YOU, E·liʹjah, in fact, has come, and they did to him as many things as they wanted, just as it is written respecting him.”

[[v41-9-14]]

^<<v41-9-14,14>>^ When, now, they came toward the other disciples, they noticed a great crowd about them and scribes disputing with them.

[[v41-9-15]]

^<<v41-9-15,15>>^ But as soon as all the crowd caught sight of him they were stunned, and, running up to him, they began to greet him.

[[v41-9-16]]

^<<v41-9-16,16>>^ And he asked them: “What are YOU disputing with them?”

[[v41-9-17]]

^<<v41-9-17,17>>^ And one of the crowd answered him: “Teacher, I brought my son to you because he has a speechless spirit;

[[v41-9-18]]

^<<v41-9-18,18>>^ and wherever it seizes him it dashes him to the ground, and he foams and grinds his teeth and loses his strength. And I told your disciples to expel it, but they were not capable.”

[[v41-9-19]]

^<<v41-9-19,19>>^ In response he said to them: “O faithless generation, how long must I continue with YOU? How long must I put up with YOU? Bring him to me.”

[[v41-9-20]]

^<<v41-9-20,20>>^ So they brought him to him. But at the sight of him the spirit at once threw &#91;the child&#93;^&#42;1^ into convulsions, and after falling on the ground he kept rolling about, foaming.

[NOTE]
====
. Lit., “him.”
====

[[v41-9-21]]

^<<v41-9-21,21>>^ And he asked his father: “How long has this been happening to him?” He said: “From childhood on;

[[v41-9-22]]

^<<v41-9-22,22>>^ and time and again it would throw him both into the fire and into the water to destroy him. But if you can do anything, have pity on us and help us.”

[[v41-9-23]]

^<<v41-9-23,23>>^ Jesus said to him: “That expression, ‘If you can’! Why, all things can be to one if one has faith.”

[[v41-9-24]]

^<<v41-9-24,24>>^ Immediately crying out, the father of the young child was saying: “I have faith! Help me out where I need faith!”^&#42;1^

[NOTE]
====
. Lit., “Help my lack of faith!”
====

[[v41-9-25]]

^<<v41-9-25,25>>^ Jesus, now noticing that a crowd was running together upon &#91;them&#93;, rebuked the unclean spirit, saying to it: “You speechless and deaf spirit, I order you, get out of him and enter into him no more.”

[[v41-9-26]]

^<<v41-9-26,26>>^ And after crying out and going through many convulsions it got out; and he became as dead, so that the greater number of them were saying: “He is dead!”

[[v41-9-27]]

^<<v41-9-27,27>>^ But Jesus took him by the hand and raised him up, and he rose.

[[v41-9-28]]

^<<v41-9-28,28>>^ So after he entered into a house his disciples proceeded to ask him privately: “Why could we not expel it?”

[[v41-9-29]]

^<<v41-9-29,29>>^ And he said to them: “This kind cannot get out by anything except by prayer.”

[[v41-9-30]]

^<<v41-9-30,30>>^ From there they departed and went their way through Galʹi·lee, but he did not want anyone to get to know it.

[[v41-9-31]]

^<<v41-9-31,31>>^ For he was teaching his disciples and telling them: “The Son of man is to be delivered^&#42;1^ into men’s hands, and they will kill him, but, despite being killed, he will rise three days later.”

[NOTE]
====
. Or, “betrayed.”
====

[[v41-9-32]]

^<<v41-9-32,32>>^ However, they were not understanding the saying, and they were afraid to question him.

[[v41-9-33]]

^<<v41-9-33,33>>^ And they came into Ca·perʹna·um. Now when he was inside the house he put the question to them: “What were YOU arguing over on the road?”

[[v41-9-34]]

^<<v41-9-34,34>>^ They kept silent, for on the road they had argued among themselves who is greater.

[[v41-9-35]]

^<<v41-9-35,35>>^ So he sat down and called the twelve and said to them: “If anyone wants to be first, he must be last of all and minister of all.”

[[v41-9-36]]

^<<v41-9-36,36>>^ And he took a young child, stood it in their midst and put his arms around it and said to them:

[[v41-9-37]]

^<<v41-9-37,37>>^ “Whoever receives one of such young children on the basis of my name, receives me; and whoever receives me, receives, not me only, but also him that sent me forth.”

[[v41-9-38]]

^<<v41-9-38,38>>^ John said to him: “Teacher, we saw a certain man expelling demons by the use of your name and we tried to prevent him, because he was not accompanying us.”

[[v41-9-39]]

^<<v41-9-39,39>>^ But Jesus said: “Do not try to prevent him, for there is no one that will do a powerful work on the basis of my name that will quickly be able to revile me;

[[v41-9-40]]

^<<v41-9-40,40>>^ for he that is not against us is for us.

[[v41-9-41]]

^<<v41-9-41,41>>^ For whoever gives YOU a cup of water to drink on the ground that YOU belong to Christ, I truly tell YOU, he will by no means lose his reward.

[[v41-9-42]]

^<<v41-9-42,42>>^ But whoever stumbles one of these little ones that believe, it would be finer for him if a millstone such as is turned by an ass were put around his neck and he were actually pitched into the sea.

[[v41-9-43]]

^<<v41-9-43,43>>^ “And if ever your hand makes you stumble, cut it off; it is finer for you to enter into life maimed than with two hands to go off into Ge·henʹna,^&#42;1^ into the fire that cannot be put out.

[NOTE]
====
. See App 4C.
====

[[v41-9-44]]

^<<v41-9-44,44>>^ ^&#42;1^ ——

[NOTE]
====
. אBCW omit; AD, “where their maggot does not die and the fire is not put out.”
====

[[v41-9-45]]

^<<v41-9-45,45>>^ And if your foot makes you stumble, cut it off; it is finer for you to enter into life lame than with two feet to be pitched into Ge·henʹna.

[[v41-9-46]]

^<<v41-9-46,46>>^ ^&#42;1^ ——

[NOTE]
====
. אBCW omit; AD, “where their maggot does not die and the fire is not put out.”
====

[[v41-9-47]]

^<<v41-9-47,47>>^ And if your eye makes you stumble, throw it away; it is finer for you to enter one-eyed into the kingdom of God than with two eyes to be pitched into Ge·henʹna,

[[v41-9-48]]

^<<v41-9-48,48>>^ where their maggot does not die and the fire is not put out.

[[v41-9-49]]

^<<v41-9-49,49>>^ “For everyone must be salted with fire.

[[v41-9-50]]

^<<v41-9-50,50>>^ Salt is fine; but if ever the salt loses its strength,^&#42;1^ with what will YOU season it itself? Have salt in yourselves, and keep peace between one another.”

[NOTE]
====
. Or, “becomes without saltness.”
====

'''

xref:041-mark/041-mark-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-mark/041-mark-010.adoc#v41-10-0[Próximo Capítulo &#62;]