include::./index.adoc[]

[[v41-12-0]]
=== According to Mark, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-12-1]]

^<<v41-12-1,1>>^ Also, he started to speak to them with illustrations: “A man planted a vineyard, and put a fence around it, and dug a vat for the winepress and erected a tower, and let it out to cultivators, and traveled abroad.

[[v41-12-2]]

^<<v41-12-2,2>>^ Now in due season he sent forth a slave to the cultivators, that he might get some of the fruits of the vineyard from the cultivators.

[[v41-12-3]]

^<<v41-12-3,3>>^ But they took him, beat him up and sent him away empty.

[[v41-12-4]]

^<<v41-12-4,4>>^ And again he sent forth another slave to them; and that one they struck on the head and dishonored.

[[v41-12-5]]

^<<v41-12-5,5>>^ And he sent forth another, and that one they killed; and many others, some of whom they beat up and some of whom they killed.

[[v41-12-6]]

^<<v41-12-6,6>>^ One more he had, a beloved son. He sent him forth last to them, saying, ‘They will respect my son.’

[[v41-12-7]]

^<<v41-12-7,7>>^ But those cultivators said among themselves, ‘This is the heir. Come, let us kill him, and the inheritance will be ours.’

[[v41-12-8]]

^<<v41-12-8,8>>^ So they took him and killed him, and threw him outside the vineyard.

[[v41-12-9]]

^<<v41-12-9,9>>^ What will the owner of the vineyard do? He will come and destroy the cultivators, and will give the vineyard to others.

[[v41-12-10]]

^<<v41-12-10,10>>^ Did YOU never read this scripture, ‘The stone that the builders rejected, this has become the chief cornerstone.

[[v41-12-11]]

^<<v41-12-11,11>>^ From Jehovah^&#42;1^ this has come to be, and it is marvelous in our eyes’?”

[NOTE]
====
. See App 1D.
====

[[v41-12-12]]

^<<v41-12-12,12>>^ At that they began seeking how to seize him, but they feared the crowd, for they took note that he spoke the illustration with them in mind. So they left him and went away.

[[v41-12-13]]

^<<v41-12-13,13>>^ Next they sent forth to him some of the Pharisees and of the party followers of Herod,^&#42;1^ to catch him in his speech.

[NOTE]
====
. Or, “of the He­ro­di­ans.”
====

[[v41-12-14]]

^<<v41-12-14,14>>^ On arrival these said to him: “Teacher, we know you are truthful and you do not care for anybody, for you do not look upon men’s outward appearance, but you teach the way of God in line with truth: Is it lawful to pay head tax to Caesar^&#42;1^ or not?

[NOTE]
====
. Or, “the emperor.” Gr., Kaiʹsa·ri.
====

[[v41-12-15]]

^<<v41-12-15,15>>^ Shall we pay, or shall we not pay?” Detecting their hypocrisy, he said to them: “Why do YOU put me to the test? Bring me a de·narʹi·us^&#42;1^ to look at.”

[NOTE]
====
. See 6:37 ftn.
====

[[v41-12-16]]

^<<v41-12-16,16>>^ They brought one. And he said to them: “Whose image and inscription is this?” They said to him: “Caesar’s.”

[[v41-12-17]]

^<<v41-12-17,17>>^ Jesus then said: “Pay back^&#42;1^ Caesar’s things to Caesar, but God’s things to God.” And they began to marvel at him.

[NOTE]
====
. Lit., “Give you back.”
====

[[v41-12-18]]

^<<v41-12-18,18>>^ Now Sadducees came to him, who say there is no resurrection, and they put the question to him:

[[v41-12-19]]

^<<v41-12-19,19>>^ “Teacher, Moses wrote us that if someone’s brother dies and leaves a wife behind but does not leave a child, his brother should take the wife and raise up offspring from her for his brother.

[[v41-12-20]]

^<<v41-12-20,20>>^ There were seven brothers; and the first took a wife, but when he died he left no offspring.

[[v41-12-21]]

^<<v41-12-21,21>>^ And the second took her, but died without leaving offspring; and the third the same way.

[[v41-12-22]]

^<<v41-12-22,22>>^ And the seven did not leave any offspring. Last of all the woman also died.

[[v41-12-23]]

^<<v41-12-23,23>>^ In the resurrection to which of them will she be wife? For the seven got her as wife.”

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus said to them: “Is not this why YOU are mistaken, YOUR not knowing either the Scriptures or the power of God?

[[v41-12-25]]

^<<v41-12-25,25>>^ For when they rise from the dead, neither do men marry nor are women given in marriage, but are as angels in the heavens.

[[v41-12-26]]

^<<v41-12-26,26>>^ But concerning the dead, that they are raised up, did YOU not read in the book of Moses, in the account about the thornbush, how God said to him, ‘I am the God of Abraham and God of Isaac and God of Jacob’?

[[v41-12-27]]

^<<v41-12-27,27>>^ He is a God, not of the dead, but of the living. YOU are much mistaken.”

[[v41-12-28]]

^<<v41-12-28,28>>^ Now one of the scribes that had come up and heard them disputing, knowing that he had answered them in a fine way, asked him: “Which commandment is first of all?”

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus answered: “The first is, ‘Hear, O Israel, Jehovah^&#42;1^ our God is one Jehovah,^&#42;2^

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v41-12-30]]

^<<v41-12-30,30>>^ and you must love Jehovah^&#42;1^ your God with your whole heart and with your whole soul^&#42;2^ and with your whole mind and with your whole strength.’

[NOTE]
====
. See App 1D.
. Or, “your . . . life.” Gr., tes psy·khesʹ sou; J17,​18,​22(Heb.), naph·shekhaʹ.
====

[[v41-12-31]]

^<<v41-12-31,31>>^ The second is this, ‘You must love your neighbor as yourself.’ There is no other commandment greater than these.”

[[v41-12-32]]

^<<v41-12-32,32>>^ The scribe said to him: “Teacher, you well said in line with truth, ‘He is One, and there is no other than He’;

[[v41-12-33]]

^<<v41-12-33,33>>^ and this loving him with one’s whole heart and with one’s whole understanding and with one’s whole strength and this loving one’s neighbor as oneself is worth far more than all the whole burnt offerings and sacrifices.”

[[v41-12-34]]

^<<v41-12-34,34>>^ At this Jesus, discerning he had answered intelligently, said to him: “You are not far from the kingdom of God.” But nobody had the courage anymore to question him.

[[v41-12-35]]

^<<v41-12-35,35>>^ However, when making a reply, Jesus began to say as he taught in the temple: “How is it that the scribes say that the Christ is David’s son?

[[v41-12-36]]

^<<v41-12-36,36>>^ By the holy spirit David himself said, ‘Jehovah^&#42;1^ said to my Lord: “Sit at my right hand until I put your enemies beneath your feet.”’

[NOTE]
====
. See App 1D.
====

[[v41-12-37]]

^<<v41-12-37,37>>^ David himself calls him ‘Lord,’ but how does it come that he is his son?”
And the great crowd was listening to him with pleasure.

[[v41-12-38]]

^<<v41-12-38,38>>^ And in his teaching he went on to say: “Look out for the scribes that want to walk around in robes and want greetings in the marketplaces^&#42;1^

[NOTE]
====
. Or, “places of assembly.”
====

[[v41-12-39]]

^<<v41-12-39,39>>^ and front seats in the synagogues and most prominent places at evening meals.

[[v41-12-40]]

^<<v41-12-40,40>>^ They are the ones devouring the houses of the widows and for a pretext making long prayers; these will receive a heavier judgment.”

[[v41-12-41]]

^<<v41-12-41,41>>^ And he sat down with the treasury chests in view and began observing how the crowd was dropping money^&#42;1^ into the treasury chests;^&#42;2^ and many rich people were dropping in many coins.

[NOTE]
====
. Lit., “copper [money].”
. Or, “the sacred treasury.”
====

[[v41-12-42]]

^<<v41-12-42,42>>^ Now a poor widow came and dropped in two small coins,^&#42;1^ which have very little value.^&#42;2^

[NOTE]
====
. Lit., “two lepta.” A lepton was the smallest Jewish copper or bronze coin. See App 8A.
. Lit., “which is a quadrans.” A Roman copper or bronze coin valued at one sixty-fourth of a denarius. See App 8A.
====

[[v41-12-43]]

^<<v41-12-43,43>>^ So he called his disciples to him and said to them: “Truly I say to YOU that this poor widow dropped in more than all those dropping money into the treasury chests;

[[v41-12-44]]

^<<v41-12-44,44>>^ for they all dropped in out of their surplus, but she, out of her want, dropped in all of what she had, her whole living.”

'''

xref:041-mark/041-mark-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-mark/041-mark-013.adoc#v41-13-0[Próximo Capítulo &#62;]