include::./index.adoc[]

[[v41-11-0]]
=== According to Mark, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-11-1]]

^<<v41-11-1,1>>^ Now when they were getting near to Jerusalem, to Bethʹpha·ge and Bethʹa·ny at the Mount of Olives, he dispatched two of his disciples

[[v41-11-2]]

^<<v41-11-2,2>>^ and told them: “Go into the village that is within sight of YOU, and as soon as YOU pass into it YOU will find a colt tied, on which none of mankind has yet sat; loose it and bring it.

[[v41-11-3]]

^<<v41-11-3,3>>^ And if anyone says to YOU, ‘Why are YOU doing this?’ say, ‘The Lord needs it, and will at once send it off back here.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ So they went away and found the colt tied at the door, outside on the side street, and they loosed it.

[[v41-11-5]]

^<<v41-11-5,5>>^ But some of those standing there began to say to them: “What are YOU doing loosing the colt?”

[[v41-11-6]]

^<<v41-11-6,6>>^ They said to these just as Jesus had said; and they let them go.

[[v41-11-7]]

^<<v41-11-7,7>>^ And they brought the colt to Jesus, and they put their outer garments upon it, and he sat on it.

[[v41-11-8]]

^<<v41-11-8,8>>^ Also, many spread their outer garments on the road, but others cut down foliage from the fields.

[[v41-11-9]]

^<<v41-11-9,9>>^ And those going in front and those coming behind kept crying out: “Save, we pray!^&#42;1^ Blessed is he that comes in Jehovah’s^&#42;2^ name!

[NOTE]
====
. Lit., “Hosanna.” Gr., Ho·san·naʹ; J7-14,​16-18,​22(Heb.), Hoh·shaʽ-naʼʹ, “Save, we pray.”
. See App 1D.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Blessed is the coming kingdom of our father David!^&#42;1^ Save, we pray, in the heights above!”^&#42;2^

[NOTE]
====
. “The coming kingdom of our father David,” אBCD; ASyh, “the kingdom of our father David that comes in the name of the Lord”; J7,​8,​10-14,​16,​17, “the kingdom of our father David that comes in the name of Jehovah.”
. Or, “in the highest places.”
====

[[v41-11-11]]

^<<v41-11-11,11>>^ And he entered into Jerusalem, into the temple; and he looked around upon all things, and, as the hour was already late, he went out to Bethʹa·ny with the twelve.

[[v41-11-12]]

^<<v41-11-12,12>>^ The next day, when they had come out from Bethʹa·ny, he became hungry.

[[v41-11-13]]

^<<v41-11-13,13>>^ And from a distance he caught sight of a fig tree that had leaves, and he went to see whether he would perhaps find something on it. But, on coming to it, he found nothing but leaves, for it was not the season of figs.

[[v41-11-14]]

^<<v41-11-14,14>>^ So, in response, he said to it: “Let no one eat fruit from you anymore forever.” And his disciples were listening.

[[v41-11-15]]

^<<v41-11-15,15>>^ Now they came to Jerusalem. There he entered into the temple and started to throw out those selling and buying in the temple, and he overturned the tables of the money changers and the benches of those selling doves;

[[v41-11-16]]

^<<v41-11-16,16>>^ and he would not let anyone carry a utensil through the temple,

[[v41-11-17]]

^<<v41-11-17,17>>^ but he kept teaching and saying: “Is it not written, ‘My house will be called a house of prayer for all the nations’? But YOU have made it a cave of robbers.”

[[v41-11-18]]

^<<v41-11-18,18>>^ And the chief priests and the scribes heard it, and they began to seek how to destroy him; for they were in fear of him, for all the crowd was continually being astounded at his teaching.

[[v41-11-19]]

^<<v41-11-19,19>>^ And when it became late in the day, they would go out of the city.

[[v41-11-20]]

^<<v41-11-20,20>>^ But when they were passing by early in the morning, they saw the fig tree already withered up from the roots.

[[v41-11-21]]

^<<v41-11-21,21>>^ So Peter, remembering it, said to him: “Rabbi, see! the fig tree that you cursed has withered up.”

[[v41-11-22]]

^<<v41-11-22,22>>^ And in reply Jesus said to them: “Have faith in God.

[[v41-11-23]]

^<<v41-11-23,23>>^ Truly I say to YOU that whoever tells this mountain, ‘Be lifted up and thrown into the sea,’ and does not doubt in his heart but has faith that what he says is going to occur, he will have it so.

[[v41-11-24]]

^<<v41-11-24,24>>^ This is why I tell YOU, All the things YOU pray and ask for have faith that YOU have practically received, and YOU will have them.

[[v41-11-25]]

^<<v41-11-25,25>>^ And when YOU stand praying, forgive whatever YOU have against anyone; in order that YOUR Father who is in the heavens may also forgive YOU YOUR trespasses.”

[[v41-11-26]]

^<<v41-11-26,26>>^ ^&#42;1^ ——

[NOTE]
====
. אBWSys omit; ACDVgSyp, “But if you do not forgive, neither will your Father who is in the heavens forgive your trespasses.”
====

[[v41-11-27]]

^<<v41-11-27,27>>^ And they came again to Jerusalem. And as he was walking in the temple, the chief priests and the scribes and the older men came to him

[[v41-11-28]]

^<<v41-11-28,28>>^ and began to say to him: “By what authority do you do these things? or who gave you this authority to do these things?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus said to them: “I will ask YOU one question. YOU answer me, and I will also tell YOU by what authority I do these things.

[[v41-11-30]]

^<<v41-11-30,30>>^ Was the baptism by John from heaven or from men? Answer me.”

[[v41-11-31]]

^<<v41-11-31,31>>^ So they began to reason among themselves, saying: “If we say, ‘From heaven,’ he will say, ‘Why is it, therefore, YOU did not believe him?’

[[v41-11-32]]

^<<v41-11-32,32>>^ But dare we say, ‘From men’?”—They were in fear of the crowd, for these all held that John had really been a prophet.

[[v41-11-33]]

^<<v41-11-33,33>>^ Well, in reply to Jesus they said: “We do not know.” And Jesus said to them: “Neither am I telling YOU by what authority I do these things.”

'''

xref:041-mark/041-mark-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-mark/041-mark-012.adoc#v41-12-0[Próximo Capítulo &#62;]