include::./index.adoc[]

[[v41-3-0]]
=== According to Mark, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-3-1]]

^<<v41-3-1,1>>^ Once again he entered into a synagogue, and a man was there with a dried-up hand.

[[v41-3-2]]

^<<v41-3-2,2>>^ So they were watching him closely to see whether he would cure the man on the sabbath, in order that they might accuse him.

[[v41-3-3]]

^<<v41-3-3,3>>^ And he said to the man with the withered hand: “Get up &#91;and come&#93; to the center.”

[[v41-3-4]]

^<<v41-3-4,4>>^ Next he said to them: “Is it lawful on the sabbath to do a good deed or to do a bad deed, to save or to kill a soul?”^&#42;1^ But they kept silent.

[NOTE]
====
. Or, “a life.” Gr., psy·khenʹ; Lat., aʹni·mam; J17,​18,​22(Heb.), neʹphesh. See App 4A.
====

[[v41-3-5]]

^<<v41-3-5,5>>^ And after looking around upon them with indignation, being thoroughly grieved at the insensibility of their hearts, he said to the man: “Stretch out your hand.” And he stretched it out, and his hand was restored.

[[v41-3-6]]

^<<v41-3-6,6>>^ At that the Pharisees went out and immediately began holding council with the party followers of Herod^&#42;1^ against him, in order to destroy him.

[NOTE]
====
. Or, “with the Herodians.”
====

[[v41-3-7]]

^<<v41-3-7,7>>^ But Jesus with his disciples withdrew to the sea; and a great multitude from Galʹi·lee and from Ju·deʹa followed him.

[[v41-3-8]]

^<<v41-3-8,8>>^ Even from Jerusalem and from Id·u·meʹa and from across the Jordan and around Tyre and Siʹdon, a great multitude, on hearing of how many things he was doing, came to him.

[[v41-3-9]]

^<<v41-3-9,9>>^ And he told his disciples to have a little boat continually at his service so that the crowd might not press upon him.

[[v41-3-10]]

^<<v41-3-10,10>>^ For he cured many, with the result that all those who had grievous diseases were falling upon him to touch him.

[[v41-3-11]]

^<<v41-3-11,11>>^ Even the unclean spirits, whenever they would behold him, would prostrate themselves before him and cry out, saying: “You are the Son of God.”

[[v41-3-12]]

^<<v41-3-12,12>>^ But many times he sternly charged them not to make him known.

[[v41-3-13]]

^<<v41-3-13,13>>^ And he ascended a mountain and summoned those he wanted, and they went off to him.

[[v41-3-14]]

^<<v41-3-14,14>>^ And he formed &#91;a group of&#93; twelve, whom he also named “apostles,” that they might continue with him and that he might send them out to preach

[[v41-3-15]]

^<<v41-3-15,15>>^ and to have authority to expel the demons.

[[v41-3-16]]

^<<v41-3-16,16>>^ And the &#91;group of&#93; twelve that he formed were Simon, to whom he also gave the surname Peter,

[[v41-3-17]]

^<<v41-3-17,17>>^ and James the &#91;son&#93; of Zebʹe·dee and John the brother of James (he also gave these the surname Bo·a·nerʹges,^&#42;1^ which means Sons of Thunder),

[NOTE]
====
. “Boanerges.” Syr., Benai Reghshi; J17(Heb.), Beneh-reghohshʹ; J18(Heb.), Beneh-raʹghesh.
====

[[v41-3-18]]

^<<v41-3-18,18>>^ and Andrew and Philip and Bar·tholʹo·mew and Matthew and Thomas and James the &#91;son&#93; of Al·phaeʹus and Thad·daeʹus and Simon the Ca·na·naeʹan

[[v41-3-19]]

^<<v41-3-19,19>>^ and Judas Is·carʹi·ot, who later betrayed him.
And he went into a house.

[[v41-3-20]]

^<<v41-3-20,20>>^ Once more the crowd gathered, so that they were not able even to eat a meal.

[[v41-3-21]]

^<<v41-3-21,21>>^ But when his relatives heard about it, they went out to lay hold of him, for they were saying: “He has gone out of his mind.”

[[v41-3-22]]

^<<v41-3-22,22>>^ Also, the scribes that came down from Jerusalem were saying: “He has Be·elʹze·bub,^&#42;1^ and he expels the demons by means of the ruler of the demons.”

[NOTE]
====
. “Beelzebub,” VgSypJ18; אACDW(Gr.), Be·el·ze·boulʹ; B(Gr.), Be·e·ze·boulʹ; J22(Heb.), Ba·ʽal-zevulʹ.
====

[[v41-3-23]]

^<<v41-3-23,23>>^ So, after calling them to him, he began to say to them with illustrations:^&#42;1^ “How can Satan expel Satan?

[NOTE]
====
. Or, “parables.”
====

[[v41-3-24]]

^<<v41-3-24,24>>^ Why, if a kingdom becomes divided against itself, that kingdom cannot stand;

[[v41-3-25]]

^<<v41-3-25,25>>^ and if a house becomes divided against itself, that house will not be able to stand.

[[v41-3-26]]

^<<v41-3-26,26>>^ Also, if Satan has risen up against himself and become divided, he cannot stand, but is coming to an end.

[[v41-3-27]]

^<<v41-3-27,27>>^ In fact, no one that has got into the house of a strong man is able to plunder his movable goods unless first he binds the strong man, and then he will plunder his house.

[[v41-3-28]]

^<<v41-3-28,28>>^ Truly I say to YOU that all things will be forgiven the sons of men, no matter what sins and blasphemies they blasphemously commit.

[[v41-3-29]]

^<<v41-3-29,29>>^ However, whoever blasphemes against the holy spirit has no forgiveness forever, but is guilty of everlasting sin.”

[[v41-3-30]]

^<<v41-3-30,30>>^ This, because they were saying: “He has an unclean spirit.”

[[v41-3-31]]

^<<v41-3-31,31>>^ Now his mother and his brothers came, and, as they were standing on the outside, they sent in to him to call him.

[[v41-3-32]]

^<<v41-3-32,32>>^ As it was, a crowd was sitting around him, so they said to him: “Look! Your mother and your brothers outside are seeking you.”

[[v41-3-33]]

^<<v41-3-33,33>>^ But in reply he said to them: “Who are my mother and my brothers?”

[[v41-3-34]]

^<<v41-3-34,34>>^ And having looked about upon those sitting around him in a circle, he said: “See, my mother and my brothers!

[[v41-3-35]]

^<<v41-3-35,35>>^ Whoever does the will of God, this one is my brother and sister and mother.”

'''

xref:041-mark/041-mark-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-mark/041-mark-004.adoc#v41-4-0[Próximo Capítulo &#62;]