include::./index.adoc[]

[[v41-8-0]]
=== According to Mark, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-8-1]]

^<<v41-8-1,1>>^ In those days, when there was again a big crowd and they had nothing to eat, he summoned the disciples and said to them:

[[v41-8-2]]

^<<v41-8-2,2>>^ “I feel pity for the crowd, because it is already three days that they have remained near me and they have nothing to eat;

[[v41-8-3]]

^<<v41-8-3,3>>^ and if I should send them off to their homes fasting, they will give out on the road. Indeed, some of them are from far away.”

[[v41-8-4]]

^<<v41-8-4,4>>^ But his disciples answered him: “From where will anybody here in an isolated place be able to satisfy these people with loaves?”

[[v41-8-5]]

^<<v41-8-5,5>>^ Still he went on to ask them: “How many loaves have YOU?” They said: “Seven.”

[[v41-8-6]]

^<<v41-8-6,6>>^ And he instructed the crowd to recline on the ground, and he took the seven loaves, gave thanks, broke them, and began to give them to his disciples to serve, and they served them to the crowd.

[[v41-8-7]]

^<<v41-8-7,7>>^ They also had a few little fishes; and, having blessed these, he told them also to serve these.

[[v41-8-8]]

^<<v41-8-8,8>>^ Accordingly they ate and were satisfied, and they took up surpluses of fragments, seven provision baskets full.

[[v41-8-9]]

^<<v41-8-9,9>>^ Yet there were about four thousand &#91;men&#93;. Finally he sent them away.

[[v41-8-10]]

^<<v41-8-10,10>>^ And immediately he boarded the boat with his disciples and came into the parts of Dal·ma·nuʹtha.

[[v41-8-11]]

^<<v41-8-11,11>>^ Here the Pharisees came out and started disputing with him, seeking from him a sign from heaven, to put him to the test.

[[v41-8-12]]

^<<v41-8-12,12>>^ So he groaned deeply with his spirit, and said: “Why does this generation seek a sign? Truly I say, No sign will be given to this generation.”

[[v41-8-13]]

^<<v41-8-13,13>>^ With that he left them, got aboard again, and went off to the opposite shore.

[[v41-8-14]]

^<<v41-8-14,14>>^ As it was, they forgot to take loaves along, and except for one loaf they had nothing with them in the boat.

[[v41-8-15]]

^<<v41-8-15,15>>^ And he began to order them expressly and say: “Keep YOUR eyes open, look out for the leaven of the Pharisees and the leaven of Herod.”

[[v41-8-16]]

^<<v41-8-16,16>>^ So they went arguing with one another over the fact that they had no loaves.

[[v41-8-17]]

^<<v41-8-17,17>>^ Noting this, he said to them: “Why do YOU argue over your having no loaves? Do YOU not yet perceive and get the meaning? Do YOU have YOUR hearts dull of understanding?

[[v41-8-18]]

^<<v41-8-18,18>>^ ‘Though having eyes, do YOU not see; and though having ears, do YOU not hear?’ And do YOU not remember,

[[v41-8-19]]

^<<v41-8-19,19>>^ when I broke the five loaves for the five thousand &#91;men&#93;, how many baskets full of fragments YOU took up?” They said to him: “Twelve.”

[[v41-8-20]]

^<<v41-8-20,20>>^ “When I broke the seven for the four thousand &#91;men&#93;, how many provision baskets full of fragments did YOU take up?” And they said to him: “Seven.”

[[v41-8-21]]

^<<v41-8-21,21>>^ With that he said to them: “Do YOU not yet get the meaning?”

[[v41-8-22]]

^<<v41-8-22,22>>^ Now they put in at Beth·saʹi·da. Here people brought him a blind man, and they entreated him to touch him.

[[v41-8-23]]

^<<v41-8-23,23>>^ And he took the blind man by the hand, brought him outside the village, and, having spit upon his eyes, he laid his hands upon him and began to ask him: “Do you see anything?”

[[v41-8-24]]

^<<v41-8-24,24>>^ And the man looked up^&#42;1^ and began saying: “I see men, because I observe what seem to be trees, but they are walking about.”

[NOTE]
====
. Or, “recovered sight; saw again.”
====

[[v41-8-25]]

^<<v41-8-25,25>>^ Then he laid his hands again upon the man’s eyes, and the man saw clearly, and he was restored, and he was seeing everything distinctly.

[[v41-8-26]]

^<<v41-8-26,26>>^ So he sent him off home, saying: “But do not enter into the village.”

[[v41-8-27]]

^<<v41-8-27,27>>^ Jesus and his disciples now left for the villages of Caes·a·reʹa Phi·lipʹpi, and on the way he began questioning his disciples, saying to them: “Who are men saying that I am?”

[[v41-8-28]]

^<<v41-8-28,28>>^ They said to him: “John the Baptist,^&#42;1^ and others, E·liʹjah, still others, One of the prophets.”

[NOTE]
====
. Or, “Immerser; Dipper.” Gr., Ba·pti·stenʹ.
====

[[v41-8-29]]

^<<v41-8-29,29>>^ And he put the question to them: “YOU, though, who do YOU say I am?” In answer Peter^&#42;1^ said to him: “You are the Christ.”

[NOTE]
====
. “Peter,” אAB; Syp, “Simon”; Sys, “Kepha.” See Mt 16:18 ftn, “Rock-mass.”
====

[[v41-8-30]]

^<<v41-8-30,30>>^ At that he strictly charged them not to tell anyone about him.

[[v41-8-31]]

^<<v41-8-31,31>>^ Also, he started teaching them that the Son of man must undergo many sufferings and be rejected by the older men and the chief priests and the scribes and be killed, and rise three days later.

[[v41-8-32]]

^<<v41-8-32,32>>^ Indeed, with outspokenness he was making that statement. But Peter took him aside and started rebuking him.

[[v41-8-33]]

^<<v41-8-33,33>>^ He turned, looked at his disciples and rebuked Peter, and said: “Get behind me, Satan, because you think, not God’s thoughts,^&#42;1^ but those of men.”

[NOTE]
====
. Or, “not the things of God.”
====

[[v41-8-34]]

^<<v41-8-34,34>>^ He now called the crowd to him with his disciples and said to them: “If anyone wants to come after me, let him disown himself and pick up his torture stake^&#42;1^ and follow me continually.

[NOTE]
====
. See App 5C.
====

[[v41-8-35]]

^<<v41-8-35,35>>^ For whoever wants to save his soul^&#42;1^ will lose it; but whoever loses his soul for the sake of me and the good news will save it.

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; J17,​18,​22(Heb.), naph·shohʹ (from neʹphesh). See App 4A.
====

[[v41-8-36]]

^<<v41-8-36,36>>^ Really, of what benefit is it for a man to gain the whole world and to forfeit his soul?

[[v41-8-37]]

^<<v41-8-37,37>>^ What, really, would a man give in exchange for his soul?

[[v41-8-38]]

^<<v41-8-38,38>>^ For whoever becomes ashamed of me and my words in this adulterous and sinful generation, the Son of man will also be ashamed of him when he arrives in the glory of his Father with the holy angels.”

'''

xref:041-mark/041-mark-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-mark/041-mark-009.adoc#v41-9-0[Próximo Capítulo &#62;]