include::./index.adoc[]

[[v41-14-0]]
=== According to Mark, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-14-1]]

^<<v41-14-1,1>>^ Now the passover and the &#91;festival of&#93; unfermented cakes was two days later. And the chief priests and the scribes were seeking how to seize him by crafty device and kill him;

[[v41-14-2]]

^<<v41-14-2,2>>^ for they repeatedly said: “Not at the festival; perhaps there might be an uproar of the people.”

[[v41-14-3]]

^<<v41-14-3,3>>^ And while he was at Bethʹa·ny in the house of Simon the leper, as he was reclining at the meal, a woman came with an alabaster case of perfumed oil, genuine nard, very expensive. Breaking open the alabaster case she began to pour it upon his head.

[[v41-14-4]]

^<<v41-14-4,4>>^ At this there were some expressing indignation among themselves: “Why has this waste of the perfumed oil taken place?

[[v41-14-5]]

^<<v41-14-5,5>>^ For this perfumed oil could have been sold for upward of three hundred de·narʹi·i^&#42;1^ and been given to the poor!” And they were feeling great displeasure at her.

[NOTE]
====
. See 6:37 ftn.
====

[[v41-14-6]]

^<<v41-14-6,6>>^ But Jesus said: “Let her alone. Why do YOU try to make trouble for her? She did a fine deed toward me.

[[v41-14-7]]

^<<v41-14-7,7>>^ For YOU always have the poor with YOU, and whenever YOU want to YOU can always do them good, but me YOU do not have always.

[[v41-14-8]]

^<<v41-14-8,8>>^ She did what she could; she undertook beforehand to put perfumed oil on my body in view of the burial.

[[v41-14-9]]

^<<v41-14-9,9>>^ Truly I say to YOU, Wherever the good news is preached in all the world, what this woman did shall also be told as a remembrance of her.”

[[v41-14-10]]

^<<v41-14-10,10>>^ And Judas Is·carʹi·ot, one of the twelve, went off to the chief priests in order to betray him to them.

[[v41-14-11]]

^<<v41-14-11,11>>^ When they heard it, they rejoiced and promised to give him silver money. So he began seeking how to betray him conveniently.

[[v41-14-12]]

^<<v41-14-12,12>>^ Now on the first day of^&#42;1^ unfermented cakes, when they customarily sacrificed the passover &#91;victim&#93;, his disciples said to him: “Where do you want us to go and prepare for you to eat the passover?”

[NOTE]
====
. See Mt 26:17 ftn.
====

[[v41-14-13]]

^<<v41-14-13,13>>^ With that he sent forth two of his disciples and said to them: “Go into the city, and a man carrying an earthenware vessel of water will encounter YOU. Follow him,

[[v41-14-14]]

^<<v41-14-14,14>>^ and wherever he goes inside say to the householder, ‘The Teacher says: “Where is the guest room for me where I may eat the passover with my disciples?”’

[[v41-14-15]]

^<<v41-14-15,15>>^ And he will show YOU a large upper room, furnished in preparation; and there prepare for us.”

[[v41-14-16]]

^<<v41-14-16,16>>^ So the disciples went out, and they entered the city and found it just as he said to them; and they prepared for the passover.

[[v41-14-17]]

^<<v41-14-17,17>>^ After evening had fallen he came with the twelve.

[[v41-14-18]]

^<<v41-14-18,18>>^ And as they were reclining at the table and eating, Jesus said: “Truly I say to YOU, One of YOU, who is eating with me, will betray me.”

[[v41-14-19]]

^<<v41-14-19,19>>^ They started to be grieved and to say to him one by one: “It is not I, is it?”

[[v41-14-20]]

^<<v41-14-20,20>>^ He said to them: “It is one of the twelve, who is dipping with me into the common bowl.

[[v41-14-21]]

^<<v41-14-21,21>>^ True, the Son of man is going away, just as it is written concerning him, but woe to that man through whom the Son of man is betrayed! It would have been finer for that man if he had not been born.”

[[v41-14-22]]

^<<v41-14-22,22>>^ And as they continued eating, he took a loaf, said a blessing, broke it and gave it to them, and said: “Take it, this means my body.”

[[v41-14-23]]

^<<v41-14-23,23>>^ And taking a cup, he offered thanks and gave it to them, and they all drank out of it.

[[v41-14-24]]

^<<v41-14-24,24>>^ And he said to them: “This means^&#42;1^ my ‘blood of the covenant,’ which is to be poured out in behalf of many.

[NOTE]
====
. Or, “is,” in the sense of signifying, importing, representing. See Mt 26:26 ftn.
====

[[v41-14-25]]

^<<v41-14-25,25>>^ Truly I say to YOU, I shall by no means drink anymore of the product of the vine until that day when I drink it new^&#42;1^ in the kingdom of God.”

[NOTE]
====
. “It new,” that is, the vine’s new product.
====

[[v41-14-26]]

^<<v41-14-26,26>>^ Finally, after singing praises,^&#42;1^ they went out to the Mount of Olives.

[NOTE]
====
. Or, “hymns; psalms.” Doubtless the Hallel Psalms. See Ps 114:1 ftn.
====

[[v41-14-27]]

^<<v41-14-27,27>>^ And Jesus said to them: “YOU will all be stumbled, because it is written, ‘I will strike the shepherd, and the sheep will be scattered about.’

[[v41-14-28]]

^<<v41-14-28,28>>^ But after I have been raised up I will go ahead of YOU into Galʹi·lee.”

[[v41-14-29]]

^<<v41-14-29,29>>^ But Peter said to him: “Even if all the others are stumbled, yet I will not be.”

[[v41-14-30]]

^<<v41-14-30,30>>^ At that Jesus said to him: “Truly I say to you, You today, yes, this night, before a cock crows twice, even you will disown me three times.”

[[v41-14-31]]

^<<v41-14-31,31>>^ But he began to say profusely: “If I have to die with you, I will by no means disown you.” Also, all the others began saying the same thing.

[[v41-14-32]]

^<<v41-14-32,32>>^ So they came to a spot named Geth·semʹa·ne, and he said to his disciples: “Sit down here while I pray.”

[[v41-14-33]]

^<<v41-14-33,33>>^ And he took Peter and James and John along with him, and he started to be stunned and to be sorely troubled.

[[v41-14-34]]

^<<v41-14-34,34>>^ And he said to them: “My soul is deeply grieved, even to death. Stay here and keep on the watch.”

[[v41-14-35]]

^<<v41-14-35,35>>^ And going a little way forward he proceeded to fall on the ground and began praying that, if it were possible, the hour might pass away from him.

[[v41-14-36]]

^<<v41-14-36,36>>^ And he went on to say: “Abba,^&#42;1^ Father, all things are possible to you; remove this cup from me. Yet not what I want, but what you want.”

[NOTE]
====
. An Aram. word meaning “the father,” or, “O Father!” Gr., Ab·baʹ; J17,​22(Heb.), ʼAb·baʼʹ.
====

[[v41-14-37]]

^<<v41-14-37,37>>^ And he came and found them sleeping, and he said to Peter: “Simon, are you sleeping? Did you not have strength to keep on the watch one hour?

[[v41-14-38]]

^<<v41-14-38,38>>^ Men, keep on the watch and praying, in order that YOU do not come into temptation. The spirit, of course, is eager, but the flesh is weak.”

[[v41-14-39]]

^<<v41-14-39,39>>^ And he went away again and prayed, saying the same word.

[[v41-14-40]]

^<<v41-14-40,40>>^ And again he came and found them sleeping, for their eyes were weighed down, and so they did not know what to answer him.

[[v41-14-41]]

^<<v41-14-41,41>>^ And he came the third time and said to them: “At such a time as this YOU are sleeping and taking YOUR rest! It is enough! The hour has come! Look! The Son of man is betrayed into the hands of sinners.

[[v41-14-42]]

^<<v41-14-42,42>>^ Get up, let us go. Look! My betrayer has drawn near.”

[[v41-14-43]]

^<<v41-14-43,43>>^ And immediately, while he was yet speaking, Judas, one of the twelve, arrived and with him a crowd with swords and clubs from the chief priests and the scribes and the older men.

[[v41-14-44]]

^<<v41-14-44,44>>^ Now his betrayer had given them an agreed sign, saying: “Whoever it is I kiss, this is he; take him into custody and lead him away safely.”^&#42;1^

[NOTE]
====
. Or, “without fail.”
====

[[v41-14-45]]

^<<v41-14-45,45>>^ And he came straight up and approached him and said: “Rabbi!” and kissed him very tenderly.

[[v41-14-46]]

^<<v41-14-46,46>>^ So they laid their hands upon him and took him into custody.

[[v41-14-47]]

^<<v41-14-47,47>>^ However, a certain one of those standing by drew his sword and struck the slave of the high priest and took his ear off.

[[v41-14-48]]

^<<v41-14-48,48>>^ But in response Jesus said to them: “Did YOU come out with swords and clubs as against a robber to arrest me?

[[v41-14-49]]

^<<v41-14-49,49>>^ Day after day I was with YOU in the temple teaching, and yet YOU did not take me into custody. Nevertheless, it is in order that the Scriptures may be fulfilled.”

[[v41-14-50]]

^<<v41-14-50,50>>^ And they all abandoned him and fled.

[[v41-14-51]]

^<<v41-14-51,51>>^ But a certain young man wearing a fine linen garment over his naked body began to follow him nearby; and they tried to seize him,

[[v41-14-52]]

^<<v41-14-52,52>>^ but he left his linen garment behind and got away naked.^&#42;1^

[NOTE]
====
. Or, “lightly clad.” See Mt 25:36 ftn.
====

[[v41-14-53]]

^<<v41-14-53,53>>^ They now led Jesus away to the high priest, and all the chief priests and the older men and the scribes assembled.

[[v41-14-54]]

^<<v41-14-54,54>>^ But Peter, from a good distance, followed him as far as in the courtyard of the high priest; and he was sitting together with the house attendants and warming himself before a bright fire.

[[v41-14-55]]

^<<v41-14-55,55>>^ Meantime the chief priests and the whole Sanʹhe·drin were looking for testimony against Jesus to put him to death, but they were not finding any.

[[v41-14-56]]

^<<v41-14-56,56>>^ Many, indeed, were giving false witness against him, but their testimonies were not in agreement.

[[v41-14-57]]

^<<v41-14-57,57>>^ Also, certain ones were rising and bearing false witness against him, saying:

[[v41-14-58]]

^<<v41-14-58,58>>^ “We heard him say, ‘I will throw down this temple^&#42;1^ that was made with hands and in three days I will build another not made with hands.’”

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplum; J17,​18,​22(Heb.), ha·heh·khalʹ, “the palace (temple).”
====

[[v41-14-59]]

^<<v41-14-59,59>>^ But neither on these grounds was their testimony in agreement.

[[v41-14-60]]

^<<v41-14-60,60>>^ Finally the high priest rose in their midst and questioned Jesus, saying: “Do you say nothing in reply? What is it these are testifying against you?”

[[v41-14-61]]

^<<v41-14-61,61>>^ But he kept silent and made no reply at all. Again the high priest began to question him and said to him: “Are you the Christ the Son of the Blessed One?”

[[v41-14-62]]

^<<v41-14-62,62>>^ Then Jesus said: “I am; and YOU persons will see the Son of man sitting at the right hand of power and coming^&#42;1^ with the clouds of heaven.”

[NOTE]
====
. “Coming.” Gr., er·khoʹme·non.
====

[[v41-14-63]]

^<<v41-14-63,63>>^ At this the high priest ripped his inner garments and said: “What further need do we have of witnesses?

[[v41-14-64]]

^<<v41-14-64,64>>^ YOU heard the blasphemy. What is evident to YOU?” They all condemned him to be liable to death.

[[v41-14-65]]

^<<v41-14-65,65>>^ And some started to spit on him and to cover his whole face and hit him with their fists and say to him: “Prophesy!” And, slapping him in the face, the court attendants took him.

[[v41-14-66]]

^<<v41-14-66,66>>^ Now while Peter was below in the courtyard, one of the servant girls of the high priest came,

[[v41-14-67]]

^<<v41-14-67,67>>^ and, seeing Peter warming himself, she looked straight at him and said: “You, too, were with the Naz·a·reneʹ, this Jesus.”

[[v41-14-68]]

^<<v41-14-68,68>>^ But he denied it, saying: “Neither do I know him nor do I understand^&#42;1^ what you are saying,” and he went outside to the vestibule.

[NOTE]
====
. Or, “I neither know nor understand.”
====

[[v41-14-69]]

^<<v41-14-69,69>>^ There the servant girl, at the sight of him, started again to say to those standing by: “This is one of them.”

[[v41-14-70]]

^<<v41-14-70,70>>^ Again he was denying it. And once more after a little while those standing by began saying to Peter: “Certainly you are one of them, for, in fact, you are a Gal·i·leʹan.”

[[v41-14-71]]

^<<v41-14-71,71>>^ But he commenced to curse and swear: “I do not know this man of whom YOU speak.”

[[v41-14-72]]

^<<v41-14-72,72>>^ And immediately a cock crowed a second time; and Peter recalled the saying that Jesus spoke to him: “Before a cock crows twice, you will disown me three times.” And he broke down and gave way to weeping.

'''

xref:041-mark/041-mark-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-mark/041-mark-015.adoc#v41-15-0[Próximo Capítulo &#62;]