include::./index.adoc[]

[[v41-5-0]]
=== According to Mark, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-5-1]]

^<<v41-5-1,1>>^ Well, they got to the other side of the sea into the country of the Gerʹa·senes.^&#42;1^

[NOTE]
====
. “Gerasenes,” א*BDVg; ACSyh,p, “Gadarenes.”
====

[[v41-5-2]]

^<<v41-5-2,2>>^ And immediately after he got out of the boat a man under the power of an unclean spirit met him from among the memorial tombs.

[[v41-5-3]]

^<<v41-5-3,3>>^ He had his haunt among the tombs; and up to that time absolutely nobody was able to bind him fast even with a chain,

[[v41-5-4]]

^<<v41-5-4,4>>^ because he had oftentimes been bound with fetters and chains, but the chains were snapped apart by him and the fetters were actually smashed; and nobody had the strength to subdue him.

[[v41-5-5]]

^<<v41-5-5,5>>^ And continually, night and day, he was crying out in the tombs and in the mountains and slashing himself with stones.

[[v41-5-6]]

^<<v41-5-6,6>>^ But on catching sight of Jesus from a distance he ran and did obeisance to him,

[[v41-5-7]]

^<<v41-5-7,7>>^ and, when he had cried out with a loud voice, he said: “What have I to do with you,^&#42;1^ Jesus, Son of the Most High God? I put you under oath by God not to torment me.”

[NOTE]
====
. An idiom; a repellent form of question. See App 7B.
====

[[v41-5-8]]

^<<v41-5-8,8>>^ For he had been telling it: “Come out of the man, you unclean spirit.”

[[v41-5-9]]

^<<v41-5-9,9>>^ But he began to ask him: “What is your name?” And he said to him: “My name is Legion, because there are many of us.”

[[v41-5-10]]

^<<v41-5-10,10>>^ And he entreated him many times not to send the spirits out of the country.

[[v41-5-11]]

^<<v41-5-11,11>>^ Now a great herd of swine was there at the mountain feeding.

[[v41-5-12]]

^<<v41-5-12,12>>^ So they entreated him, saying: “Send us into the swine, that we may enter into them.”

[[v41-5-13]]

^<<v41-5-13,13>>^ And he permitted them. With that the unclean spirits came out and entered into the swine; and the herd rushed over the precipice into the sea, about two thousand of them, and they drowned one after another in the sea.

[[v41-5-14]]

^<<v41-5-14,14>>^ But the herders of them fled and reported it in the city and in the countryside; and people came to see what it was that had happened.

[[v41-5-15]]

^<<v41-5-15,15>>^ So they came to Jesus, and they beheld the demon-possessed &#91;man&#93; sitting clothed and in his sound mind, this &#91;man&#93; that had had the legion; and they grew fearful.

[[v41-5-16]]

^<<v41-5-16,16>>^ Also, those who had seen it related to them how this had happened to the demon-possessed &#91;man&#93; and about the swine.

[[v41-5-17]]

^<<v41-5-17,17>>^ And so they started to entreat him to go away from their districts.

[[v41-5-18]]

^<<v41-5-18,18>>^ Now as he was boarding the boat, the &#91;man&#93; that had been demon-possessed began entreating him that he might continue with him.

[[v41-5-19]]

^<<v41-5-19,19>>^ However, he did not let him, but said to him: “Go home to your relatives, and report to them all the things Jehovah^&#42;1^ has done for you and the mercy he had on you.”

[NOTE]
====
. See App 1D.
====

[[v41-5-20]]

^<<v41-5-20,20>>^ And he went away and started to proclaim^&#42;1^ in the De·capʹo·lis^&#42;2^ all the things Jesus did for him, and all the people began to wonder.

[NOTE]
====
. Lit., “to be heralding.” Gr., ke·rysʹsein. See 13:10 ftn.
. Or, “Ten Cities.” Gr., De·ka·poʹlei.
====

[[v41-5-21]]

^<<v41-5-21,21>>^ After Jesus had crossed back again in the boat to the opposite shore a great crowd gathered together to him; and he was beside the sea.

[[v41-5-22]]

^<<v41-5-22,22>>^ Now one of the presiding officers of the synagogue, Jaʹi·rus by name, came and, on catching sight of him, he fell at his feet

[[v41-5-23]]

^<<v41-5-23,23>>^ and entreated him many times, saying: “My little daughter is in an extreme condition. Would you please come and put your hands upon her that she may get well and live.”

[[v41-5-24]]

^<<v41-5-24,24>>^ At that he went off with him. And a great crowd was following him and pressing against him.

[[v41-5-25]]

^<<v41-5-25,25>>^ Now there was a woman subject to a flow of blood twelve years,

[[v41-5-26]]

^<<v41-5-26,26>>^ and she had been put to many pains by many physicians and had spent all her resources and had not been benefited but, rather, had got worse.

[[v41-5-27]]

^<<v41-5-27,27>>^ When she heard the things about Jesus, she came behind in the crowd and touched his outer garment;

[[v41-5-28]]

^<<v41-5-28,28>>^ for she kept saying: “If I touch just his outer garments I shall get well.”^&#42;1^

[NOTE]
====
. Or, “saved.”
====

[[v41-5-29]]

^<<v41-5-29,29>>^ And immediately her fountain of blood dried up, and she sensed in her body that she had been healed of the grievous sickness.

[[v41-5-30]]

^<<v41-5-30,30>>^ Immediately, also, Jesus recognized in himself that power had gone out of him, and he turned about in the crowd and began to say: “Who touched my outer garments?”

[[v41-5-31]]

^<<v41-5-31,31>>^ But his disciples began to say to him: “You see the crowd pressing in upon you, and do you say, ‘Who touched me?’”

[[v41-5-32]]

^<<v41-5-32,32>>^ However, he was looking around to see her that had done this.

[[v41-5-33]]

^<<v41-5-33,33>>^ But the woman, frightened and trembling, knowing what had happened to her, came and fell down before him and told him the whole truth.

[[v41-5-34]]

^<<v41-5-34,34>>^ He said to her: “Daughter, your faith has made you well.^&#42;1^ Go in peace,^&#42;2^ and be in good health from your grievous sickness.”

[NOTE]
====
. Or, “has saved you.”
. Lit., “into peace.” Gr., eis ei·reʹnen; Lat., in paʹce; J17,​18,​22(Heb.), lesha·lohmʹ.
====

[[v41-5-35]]

^<<v41-5-35,35>>^ While he was yet speaking, some men from the home of the presiding officer of the synagogue came and said: “Your daughter died! Why bother the teacher any longer?”

[[v41-5-36]]

^<<v41-5-36,36>>^ But Jesus, overhearing the word being spoken, said to the presiding officer of the synagogue: “Have no fear, only exercise faith.”

[[v41-5-37]]

^<<v41-5-37,37>>^ Now he did not let anyone follow along with him except Peter and James and John the brother of James.

[[v41-5-38]]

^<<v41-5-38,38>>^ So they came to the house of the presiding officer of the synagogue, and he beheld the noisy confusion and those weeping and letting out many wails,

[[v41-5-39]]

^<<v41-5-39,39>>^ and, after stepping in, he said to them: “Why are YOU causing noisy confusion and weeping? The young child has not died, but is sleeping.”

[[v41-5-40]]

^<<v41-5-40,40>>^ At this they began to laugh scornfully at him. But, having put them all out, he took along the young child’s father and mother and those with him, and he went in where the young child was.

[[v41-5-41]]

^<<v41-5-41,41>>^ And, taking the hand of the young child, he said to her: “Talʹi·tha cuʹmi,” which, translated, means: “Maiden, I say to you, Get up!”

[[v41-5-42]]

^<<v41-5-42,42>>^ And immediately the maiden rose and began walking, for she was twelve years old. And at once they were beside themselves with great ecstasy.

[[v41-5-43]]

^<<v41-5-43,43>>^ But he ordered them again and again to let no one learn of this, and he said that something should be given her to eat.

'''

xref:041-mark/041-mark-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-mark/041-mark-006.adoc#v41-6-0[Próximo Capítulo &#62;]