include::./index.adoc[]

[[v41-10-0]]
=== According to Mark, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-10-1]]

^<<v41-10-1,1>>^ From there he rose and came to the frontiers of Ju·deʹa and across the Jordan, and again crowds came together to him, and as he was accustomed to do he again went teaching them.

[[v41-10-2]]

^<<v41-10-2,2>>^ Pharisees now approached and, to put him to the test, began questioning him whether it was lawful for a man to divorce a wife.

[[v41-10-3]]

^<<v41-10-3,3>>^ In answer he said to them: “What did Moses command YOU?”

[[v41-10-4]]

^<<v41-10-4,4>>^ They said: “Moses allowed the writing of a certificate of dismissal and divorcing &#91;her&#93;.”

[[v41-10-5]]

^<<v41-10-5,5>>^ But Jesus said to them: “Out of regard for YOUR hardheartedness he wrote YOU this commandment.

[[v41-10-6]]

^<<v41-10-6,6>>^ However, from &#91;the&#93; beginning of creation ‘He^&#42;1^ made them male and female.

[NOTE]
====
. “He,” אBC; ADVgSyh,p,sArm, “God.”
====

[[v41-10-7]]

^<<v41-10-7,7>>^ On this account a man will leave his father and mother,

[[v41-10-8]]

^<<v41-10-8,8>>^ and the two will be one flesh’; so that they are no longer two, but one flesh.

[[v41-10-9]]

^<<v41-10-9,9>>^ Therefore what God yoked together let no man put apart.”

[[v41-10-10]]

^<<v41-10-10,10>>^ When again in the house the disciples began to question him concerning this.

[[v41-10-11]]

^<<v41-10-11,11>>^ And he said to them: “Whoever divorces^&#42;1^ his wife and marries another commits adultery against her,

[NOTE]
====
. Lit., “might loosen from.” See Mal 2:16 ftn.
====

[[v41-10-12]]

^<<v41-10-12,12>>^ and if ever a woman, after divorcing her husband, marries another, she commits adultery.”

[[v41-10-13]]

^<<v41-10-13,13>>^ Now people began bringing him young children for him to touch these; but the disciples reprimanded them.

[[v41-10-14]]

^<<v41-10-14,14>>^ At seeing this Jesus was indignant and said to them: “Let the young children come to me; do not try to stop them, for the kingdom of God belongs to suchlike ones.

[[v41-10-15]]

^<<v41-10-15,15>>^ Truly I say to YOU, Whoever does not receive the kingdom of God like a young child will by no means enter into it.”

[[v41-10-16]]

^<<v41-10-16,16>>^ And he took the children into his arms and began blessing them, laying his hands upon them.

[[v41-10-17]]

^<<v41-10-17,17>>^ And as he was going out on his way, a certain man ran up and fell upon his knees before him and put the question to him: “Good Teacher, what must I do to inherit everlasting life?”^&#42;1^

[NOTE]
====
. Or, “life everlasting.” Gr., zo·enʹ ai·oʹni·on; Lat., viʹtam ae·terʹnam; J17,​18,​22(Heb.), chai·yehʹ ʽoh·lamʹ.
====

[[v41-10-18]]

^<<v41-10-18,18>>^ Jesus said to him: “Why do you call me good? Nobody is good, except one, God.

[[v41-10-19]]

^<<v41-10-19,19>>^ You know the commandments, ‘Do not murder, Do not commit adultery, Do not steal, Do not bear false witness, Do not defraud, Honor your father and mother.’”

[[v41-10-20]]

^<<v41-10-20,20>>^ The man said to him: “Teacher, all these things I have kept from my youth on.”

[[v41-10-21]]

^<<v41-10-21,21>>^ Jesus looked upon him and felt love for him and said to him: “One thing is missing about you: Go, sell what things you have and give to the poor, and you will have treasure in heaven, and come be my follower.”

[[v41-10-22]]

^<<v41-10-22,22>>^ But he grew sad at the saying and went off grieved, for he was holding many possessions.

[[v41-10-23]]

^<<v41-10-23,23>>^ After looking around Jesus said to his disciples: “How difficult a thing it will be for those with money to enter into the kingdom of God!”

[[v41-10-24]]

^<<v41-10-24,24>>^ But the disciples gave way to surprise at his words. In response Jesus again said to them: “Children, how difficult a thing it is to enter into the kingdom of God!

[[v41-10-25]]

^<<v41-10-25,25>>^ It is easier for a camel to go through a needle’s eye than for a rich man to enter into the kingdom of God.”

[[v41-10-26]]

^<<v41-10-26,26>>^ They became still more astounded and said to him: “Who, in fact, can be saved?”

[[v41-10-27]]

^<<v41-10-27,27>>^ Looking straight at them Jesus said: “With men it is impossible, but not so with God, for all things are possible with God.”

[[v41-10-28]]

^<<v41-10-28,28>>^ Peter started to say to him: “Look! We left all things and have been following you.”

[[v41-10-29]]

^<<v41-10-29,29>>^ Jesus said: “Truly I say to YOU men, No one has left house or brothers or sisters or mother or father or children or fields for my sake and for the sake of the good news

[[v41-10-30]]

^<<v41-10-30,30>>^ who will not get a hundredfold now in this period of time, houses and brothers and sisters and mothers and children and fields, with persecutions, and in the coming system of things^&#42;1^ everlasting life.

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹni; J17,​22(Heb.), u·va·ʽoh·lamʹ, “and in the order of things.”
====

[[v41-10-31]]

^<<v41-10-31,31>>^ However, many that are first will be last, and the last first.”

[[v41-10-32]]

^<<v41-10-32,32>>^ Now they were advancing on the road up to Jerusalem, and Jesus was going in front of them, and they felt amazement; but those who followed began to fear. Once again he took the twelve aside and started to tell them these things destined to befall him:

[[v41-10-33]]

^<<v41-10-33,33>>^ “Here we are, advancing up to Jerusalem, and the Son of man will be delivered to the chief priests and the scribes, and they will condemn him to death and will deliver him to &#91;men of&#93; the nations,

[[v41-10-34]]

^<<v41-10-34,34>>^ and they will make fun of him and will spit upon him and scourge him and kill him, but three days later he will rise.”

[[v41-10-35]]

^<<v41-10-35,35>>^ And James and John, the two sons of Zebʹe·dee, stepped up to him and said to him: “Teacher, we want you to do for us whatever it is we ask you for.”

[[v41-10-36]]

^<<v41-10-36,36>>^ He said to them: “What do YOU want me to do for YOU?”

[[v41-10-37]]

^<<v41-10-37,37>>^ They said to him: “Grant us to sit down, one at your right hand and one at your left, in your glory.”

[[v41-10-38]]

^<<v41-10-38,38>>^ But Jesus said to them: “YOU do not know what YOU are asking for. Are YOU able to drink the cup which I am drinking, or to be baptized with the baptism^&#42;1^ with which I am being baptized?”

[NOTE]
====
. Or, “immersion; dipping.” Gr., baʹpti·sma.
====

[[v41-10-39]]

^<<v41-10-39,39>>^ They said to him: “We are able.” At that Jesus said to them: “The cup I am drinking YOU will drink, and with the baptism with which I am being baptized YOU will be baptized.

[[v41-10-40]]

^<<v41-10-40,40>>^ However, this sitting down at my right or at my left is not mine to give, but it belongs to those for whom it has been prepared.”

[[v41-10-41]]

^<<v41-10-41,41>>^ Well, when the ten others heard about it, they started to be indignant at James and John.

[[v41-10-42]]

^<<v41-10-42,42>>^ But Jesus, after calling them to him, said to them: “YOU know that those who appear to be ruling the nations lord it over them and their great ones wield authority over them.

[[v41-10-43]]

^<<v41-10-43,43>>^ This is not the way among YOU; but whoever wants to become great among YOU must be YOUR minister,

[[v41-10-44]]

^<<v41-10-44,44>>^ and whoever wants to be first among YOU must be the slave of all.

[[v41-10-45]]

^<<v41-10-45,45>>^ For even the Son of man came, not to be ministered to, but to minister and to give his soul^&#42;1^ a ransom in exchange for many.”

[NOTE]
====
. Or, “life.” See Mt 20:28 ftn, “Soul.”
====

[[v41-10-46]]

^<<v41-10-46,46>>^ And they came into Jerʹi·cho. But as he and his disciples and a considerable crowd were going out of Jerʹi·cho, Bar·ti·maeʹus (the son of Ti·maeʹus), a blind beggar, was sitting beside the road.

[[v41-10-47]]

^<<v41-10-47,47>>^ When he heard that it was Jesus the Naz·a·reneʹ, he started shouting and saying: “Son of David, Jesus, have mercy on me!”

[[v41-10-48]]

^<<v41-10-48,48>>^ At this many began sternly telling him to be silent; but he kept shouting that much more: “Son of David, have mercy on me!”

[[v41-10-49]]

^<<v41-10-49,49>>^ So Jesus stopped and said: “CALL him.” And they called the blind man, saying to him: “Take courage, get up, he is calling you.”

[[v41-10-50]]

^<<v41-10-50,50>>^ Throwing off his outer garment, he leaped to his feet and went to Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ And in answer to him Jesus said: “What do you want me to do for you?” The blind man said to him: “Rab·boʹni,^&#42;1^ let me recover sight.”

[NOTE]
====
. “Rabboni.” See Joh 20:16.
====

[[v41-10-52]]

^<<v41-10-52,52>>^ And Jesus said to him: “Go, your faith has made you well.”^&#42;1^ And immediately he recovered sight, and he began to follow him on the road.

[NOTE]
====
. Or, “has saved you.”
====

'''

xref:041-mark/041-mark-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-mark/041-mark-011.adoc#v41-11-0[Próximo Capítulo &#62;]