include::./index.adoc[]

[[v41-1-0]]
=== According to Mark, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v41-1-1]]

^<<v41-1-1,1>>^ &#91;The&#93; beginning of the good news^&#42;1^ about^&#42;2^ Jesus Christ:

[NOTE]
====
. “Good news.” Or, “evangel; gospel.” Gr., eu·ag·ge·liʹou; Lat., e·van·geʹli·i.
. Or, “of.”
====

[[v41-1-2]]

^<<v41-1-2,2>>^ Just as it is written in Isaiah the prophet: “(Look! I am sending forth my messenger^&#42;1^ before your face, who will prepare your way;)

[NOTE]
====
. Or, “angel.”
====

[[v41-1-3]]

^<<v41-1-3,3>>^ listen! someone is crying out in the wilderness, ‘Prepare the way of Jehovah,^&#42;1^ YOU people, make his roads straight,’”

[NOTE]
====
. See App 1D.
====

[[v41-1-4]]

^<<v41-1-4,4>>^ John the baptizer^&#42;1^ turned up in the wilderness, preaching baptism &#91;in symbol&#93; of repentance for forgiveness of sins.

[NOTE]
====
. Or, “immerser; dipper.” Gr., ba·ptiʹzon.
====

[[v41-1-5]]

^<<v41-1-5,5>>^ Consequently all the territory of Ju·deʹa and all the inhabitants of Jerusalem made their way out to him, and they were baptized by him in the Jordan River, openly confessing their sins.

[[v41-1-6]]

^<<v41-1-6,6>>^ Now John was clothed with camel’s hair and with a leather girdle around his loins, and was eating insect locusts and wild honey.

[[v41-1-7]]

^<<v41-1-7,7>>^ And he would preach, saying: “After me someone stronger than I am is coming; I am not fit to stoop and untie the laces of his sandals.

[[v41-1-8]]

^<<v41-1-8,8>>^ I baptized YOU with water, but he will baptize YOU with holy spirit.”

[[v41-1-9]]

^<<v41-1-9,9>>^ In the course of those days Jesus came from Nazʹa·reth of Galʹi·lee and was baptized in the Jordan by John.

[[v41-1-10]]

^<<v41-1-10,10>>^ And immediately on coming up out of the water he saw the heavens being parted, and, like a dove, the spirit coming down upon^&#42;1^ him;

[NOTE]
====
. Or, “into”; that is, to enter into him.
====

[[v41-1-11]]

^<<v41-1-11,11>>^ and a voice came out of the heavens: “You are my Son, the beloved; I have approved you.”

[[v41-1-12]]

^<<v41-1-12,12>>^ And immediately the spirit^&#42;1^ impelled him to go into the wilderness.

[NOTE]
====
. Or, “the active force.” Gr., to pneuʹma; J17,​18,​22(Heb.), ha·ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v41-1-13]]

^<<v41-1-13,13>>^ So he continued in the wilderness forty days, being tempted by Satan, and he was with the wild beasts, but the angels were ministering to him.

[[v41-1-14]]

^<<v41-1-14,14>>^ Now after John was put under arrest Jesus went into Galʹi·lee, preaching the good news of God

[[v41-1-15]]

^<<v41-1-15,15>>^ and saying: “The appointed time has been fulfilled, and the kingdom of God has drawn near. Be repentant, YOU people, and have faith in the good news.”

[[v41-1-16]]

^<<v41-1-16,16>>^ While walking alongside the sea of Galʹi·lee he saw Simon and Andrew the brother of Simon casting &#91;their nets&#93; about in the sea, for they were fishers.

[[v41-1-17]]

^<<v41-1-17,17>>^ So Jesus said to them: “Come after me, and I shall cause YOU to become fishers of men.”

[[v41-1-18]]

^<<v41-1-18,18>>^ And at once they abandoned their nets and followed him.

[[v41-1-19]]

^<<v41-1-19,19>>^ And after going a little farther he saw James the &#91;son&#93; of Zebʹe·dee and John his brother, in fact, while they were in their boat mending their nets;

[[v41-1-20]]

^<<v41-1-20,20>>^ and without delay he called them. In turn they left their father Zebʹe·dee in the boat with the hired men and went off after him.

[[v41-1-21]]

^<<v41-1-21,21>>^ And they went their way into Ca·perʹna·um.
No sooner was it the sabbath than he entered into the synagogue and began to teach.

[[v41-1-22]]

^<<v41-1-22,22>>^ And they became astounded at his way of teaching, for there he was teaching them as one having authority, and not as the scribes.

[[v41-1-23]]

^<<v41-1-23,23>>^ Also, at that immediate time there was in their synagogue a man under the power of an unclean spirit, and he shouted,

[[v41-1-24]]

^<<v41-1-24,24>>^ saying: “What have we to do with you,^&#42;1^ Jesus you Naz·a·reneʹ? Did you come to destroy us? I know exactly who you are, the Holy One of God.”

[NOTE]
====
. An idiom; a repellent form of question. See App 7B.
====

[[v41-1-25]]

^<<v41-1-25,25>>^ But Jesus rebuked it, saying: “Be silent, and come on out of him!”

[[v41-1-26]]

^<<v41-1-26,26>>^ And the unclean spirit, after throwing him into a convulsion and yelling at the top of its voice, came on out of him.

[[v41-1-27]]

^<<v41-1-27,27>>^ Well, the people were all so astonished that they began a discussion among themselves, saying: “What is this? A new teaching! He authoritatively orders even the unclean spirits, and they obey him.”

[[v41-1-28]]

^<<v41-1-28,28>>^ So the report about him spread out immediately in all directions through all the country round about in Galʹi·lee.

[[v41-1-29]]

^<<v41-1-29,29>>^ And immediately they went out of the synagogue and went into the home of Simon and Andrew with James and John.

[[v41-1-30]]

^<<v41-1-30,30>>^ Now Simon’s mother-in-law was lying down sick with a fever, and they at once told him about her.

[[v41-1-31]]

^<<v41-1-31,31>>^ And going to her he raised her up, taking her by the hand; and the fever left her, and she began ministering to them.

[[v41-1-32]]

^<<v41-1-32,32>>^ After evening had fallen, when the sun had set, the people began bringing him all those who were ill and those demon-possessed;

[[v41-1-33]]

^<<v41-1-33,33>>^ and the whole city was gathered right at the door.

[[v41-1-34]]

^<<v41-1-34,34>>^ So he cured many that were ill with various sicknesses, and he expelled many demons, but he would not let the demons speak, because they knew him to be Christ.

[[v41-1-35]]

^<<v41-1-35,35>>^ And early in the morning, while it was still dark, he rose up and went outside and left for a lonely place, and there he began praying.

[[v41-1-36]]

^<<v41-1-36,36>>^ However, Simon and those with him hunted him down

[[v41-1-37]]

^<<v41-1-37,37>>^ and found him, and they said to him: “All are looking for you.”

[[v41-1-38]]

^<<v41-1-38,38>>^ But he said to them: “Let us go somewhere else, into the village towns nearby, that I may preach there also, for it is for this purpose I have gone out.”

[[v41-1-39]]

^<<v41-1-39,39>>^ And he did go, preaching in their synagogues throughout the whole of Galʹi·lee and expelling the demons.

[[v41-1-40]]

^<<v41-1-40,40>>^ There also came to him a leper, entreating him even on bended knee, saying to him: “If you just want to, you can make me clean.”

[[v41-1-41]]

^<<v41-1-41,41>>^ At that he was moved with pity, and he stretched out his hand and touched him, and said to him: “I want to. Be made clean.”

[[v41-1-42]]

^<<v41-1-42,42>>^ And immediately the leprosy vanished from him, and he became clean.

[[v41-1-43]]

^<<v41-1-43,43>>^ Furthermore, he gave him strict orders and at once sent him away,

[[v41-1-44]]

^<<v41-1-44,44>>^ and said to him: “See that you tell nobody a thing, but go show yourself to the priest and offer in behalf of your cleansing the things Moses directed, for a witness to them.”

[[v41-1-45]]

^<<v41-1-45,45>>^ But after going away the man started to proclaim it a great deal and to spread the account abroad, so that &#91;Jesus&#93;^&#42;1^ was no longer able to enter openly into a city, but he continued outside in lonely places. Yet they kept coming to him from all sides.

[NOTE]
====
. Lit., “he.”
====

'''

xref:040-matthew/040-matthew-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-mark/041-mark-002.adoc#v41-2-0[Próximo Capítulo &#62;]