include::./index.adoc[]

[[v53-2-0]]
=== The Second to the Thessalonians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v53-2-1]]

^<<v53-2-1,1>>^ However, brothers, respecting the presence^&#42;1^ of our^&#42;2^ Lord Jesus Christ and our being gathered together to him, we request of YOU

[NOTE]
====
. See App 5B.
. “Our,” אADVgSyp; B, “the.”
====

[[v53-2-2]]

^<<v53-2-2,2>>^ not to be quickly shaken from YOUR reason nor to be excited either through an inspired expression^&#42;1^ or through a verbal message or through a letter as though from us, to the effect that the day of Jehovah^&#42;2^ is here.

[NOTE]
====
. Or, “through a spirit.”
. See App 1D.
====

[[v53-2-3]]

^<<v53-2-3,3>>^ Let no one seduce YOU in any manner, because it will not come unless the apostasy^&#42;1^ comes first and the man of lawlessness^&#42;2^ gets revealed, the son of destruction.^&#42;3^

[NOTE]
====
. “Apostasy.” Gr., a·po·sta·siʹa. This noun comes from the verb a·phiʹste·mi, “stand away from.” The noun has the sense of “desertion; abandonment; rebellion.” See Ac 21:21 ftn.
. “Lawlessness,” אB; ADVgSyp, “sin.”
. Or, “of annihilation.” See Mt 7:13 ftn.
====

[[v53-2-4]]

^<<v53-2-4,4>>^ He is set in opposition and lifts himself up over everyone who is called “god” or an object of reverence, so that he sits down in the temple^&#42;1^ of The God,^&#42;2^ publicly showing himself to be a god.

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplo; J17,​18,​22(Heb.), beheh·khalʹ, “in the palace (temple) of.”
. “The God.” Gr., tou The·ouʹ; J17,​22(Heb.), ha·ʼElo·himʹ, “the [true] God.” See Ge 5:22 ftn, “God.”
====

[[v53-2-5]]

^<<v53-2-5,5>>^ Do YOU not remember that, while I was yet with YOU, I used to tell YOU these things?

[[v53-2-6]]

^<<v53-2-6,6>>^ And so now YOU know the thing that acts as a restraint, with a view to his being revealed in his own due time.

[[v53-2-7]]

^<<v53-2-7,7>>^ True, the mystery of this lawlessness is already at work; but only till he who is right now acting as a restraint^&#42;1^ gets to be out of the way.

[NOTE]
====
. Lit., “the (one) holding down right now.”
====

[[v53-2-8]]

^<<v53-2-8,8>>^ Then, indeed, the lawless one will be revealed, whom the Lord Jesus^&#42;1^ will do away with by the spirit of his mouth and bring to nothing by the manifestation of his presence.

[NOTE]
====
. “Jesus,” אAD*Vg; BDc omit.
====

[[v53-2-9]]

^<<v53-2-9,9>>^ But the lawless one’s presence^&#42;1^ is according to the operation^&#42;2^ of Satan with every powerful work and lying signs and portents

[NOTE]
====
. Or, “whose presence,” referring to “whom” in vs 8. See App 5B.
. Lit., “working within.”
====

[[v53-2-10]]

^<<v53-2-10,10>>^ and with every unrighteous deception^&#42;1^ for those who are perishing, as a retribution because they did not accept the love of the truth that they might be saved.

[NOTE]
====
. Lit., “seduction.”
====

[[v53-2-11]]

^<<v53-2-11,11>>^ So that is why God lets an operation of error go to them, that they may get to believing the lie,

[[v53-2-12]]

^<<v53-2-12,12>>^ in order that they all may be judged because they did not believe the truth but took pleasure^&#42;1^ in unrighteousness.

[NOTE]
====
. Lit., “having thought well.”
====

[[v53-2-13]]

^<<v53-2-13,13>>^ However, we are obligated to thank God always for YOU, brothers loved by Jehovah,^&#42;1^ because God selected YOU from &#91;the&#93; beginning for salvation by sanctifying YOU with spirit and by YOUR faith in the truth.

[NOTE]
====
. “Jehovah,” J13,​16,​24; אAB(Gr.), Ky·riʹou; D*Vg, “God.” See App 1D.
====

[[v53-2-14]]

^<<v53-2-14,14>>^ To this very destiny he called YOU through the good news we declare, for the purpose of acquiring the glory of our Lord Jesus Christ.

[[v53-2-15]]

^<<v53-2-15,15>>^ So, then, brothers, stand firm and maintain YOUR hold on the traditions that YOU were taught, whether it was through a verbal message or through a letter of ours.

[[v53-2-16]]

^<<v53-2-16,16>>^ Moreover, may our Lord Jesus Christ himself and God our Father, who loved us and gave everlasting comfort and good hope by means of undeserved kindness,

[[v53-2-17]]

^<<v53-2-17,17>>^ comfort YOUR hearts and make YOU firm in every good deed and word.

'''

xref:053-2-thessalonians/053-2-thessalonians-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-thessalonians/053-2-thessalonians-003.adoc#v53-3-0[Próximo Capítulo &#62;]