include::./index.adoc[]

[[v53-3-0]]
=== The Second to the Thessalonians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v53-3-1]]

^<<v53-3-1,1>>^ Finally, brothers, carry on prayer for us, that the word of Jehovah^&#42;1^ may keep moving speedily and being glorified just as it is in fact with YOU;

[NOTE]
====
. See App 1D.
====

[[v53-3-2]]

^<<v53-3-2,2>>^ and that we may be delivered from harmful and wicked men, for faith is not a possession of all people.

[[v53-3-3]]

^<<v53-3-3,3>>^ But the Lord is faithful, and he will make YOU firm and keep YOU from the wicked one.

[[v53-3-4]]

^<<v53-3-4,4>>^ Moreover, we have confidence in &#91;the&#93; Lord regarding YOU, that YOU are doing and will go on doing the things we order.

[[v53-3-5]]

^<<v53-3-5,5>>^ May the Lord continue directing YOUR hearts successfully into the love of God and into the endurance for the Christ.

[[v53-3-6]]

^<<v53-3-6,6>>^ Now we are giving YOU orders, brothers, in the name of the Lord Jesus Christ, to withdraw from every brother walking disorderly and not according to the tradition^&#42;1^ YOU received from us.

[NOTE]
====
. Or, “instruction.”
====

[[v53-3-7]]

^<<v53-3-7,7>>^ For YOU yourselves know the way YOU ought to imitate us, because we did not behave disorderly among YOU

[[v53-3-8]]

^<<v53-3-8,8>>^ nor did we eat food from anyone free. To the contrary, by labor and toil night and day we were working so as not to impose an expensive burden upon any one of YOU.

[[v53-3-9]]

^<<v53-3-9,9>>^ Not that we do not have authority, but in order that we might offer ourselves as an example to YOU to imitate us.

[[v53-3-10]]

^<<v53-3-10,10>>^ In fact, also, when we were with YOU, we used to give YOU this order: “If anyone does not want to work, neither let him eat.”

[[v53-3-11]]

^<<v53-3-11,11>>^ For we hear certain ones are walking disorderly among YOU, not working at all but meddling with what does not concern them.

[[v53-3-12]]

^<<v53-3-12,12>>^ To such persons we give the order and exhortation in &#91;the&#93; Lord Jesus Christ that by working with quietness they should eat food they themselves earn.

[[v53-3-13]]

^<<v53-3-13,13>>^ For YOUR part, brothers, do not give up in doing right.

[[v53-3-14]]

^<<v53-3-14,14>>^ But if anyone is not obedient to our word through this letter, keep this one marked,^&#42;1^ stop associating with^&#42;2^ him, that he may become ashamed.

[NOTE]
====
. Lit., “be you putting sign on.”
. Lit., “not to mix up selves with.”
====

[[v53-3-15]]

^<<v53-3-15,15>>^ And yet do not be considering him as an enemy, but continue admonishing^&#42;1^ him as a brother.

[NOTE]
====
. Lit., “be you putting mind in.”
====

[[v53-3-16]]

^<<v53-3-16,16>>^ Now may the Lord of peace himself give YOU peace constantly in every way. The Lord be with all of YOU.

[[v53-3-17]]

^<<v53-3-17,17>>^ &#91;Here is&#93; my greeting, Paul’s, in my own hand, which is a sign in every letter; this is the way I write.

[[v53-3-18]]

^<<v53-3-18,18>>^ The undeserved kindness of our Lord Jesus Christ be with all of YOU.

'''

xref:053-2-thessalonians/053-2-thessalonians-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timothy/054-1-timothy-001.adoc#v54-1-0[Próximo Capítulo &#62;]