include::./index.adoc[]

[[v53-1-0]]
=== The Second to the Thessalonians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v53-1-1]]

^<<v53-1-1,1>>^ Paul and Sil·vaʹnus^&#42;1^ and Timothy to the congregation of the Thes·sa·loʹni·ans in union with God our Father and &#91;the&#93; Lord Jesus Christ:

[NOTE]
====
. Or, “Silas.”
====

[[v53-1-2]]

^<<v53-1-2,2>>^ May YOU have undeserved kindness and peace from God the Father and &#91;the&#93; Lord Jesus Christ.

[[v53-1-3]]

^<<v53-1-3,3>>^ We are obligated to give God thanks always for YOU, brothers, as it is fitting, because YOUR faith is growing exceedingly and the love of each and all of YOU is increasing one toward the other.

[[v53-1-4]]

^<<v53-1-4,4>>^ As a result we ourselves take pride in YOU among the congregations of God because of YOUR endurance and faith in all YOUR persecutions and the tribulations that YOU are bearing.

[[v53-1-5]]

^<<v53-1-5,5>>^ This is a proof of the righteous judgment of God, leading to YOUR being counted worthy of the kingdom of God, for which YOU are indeed suffering.

[[v53-1-6]]

^<<v53-1-6,6>>^ This takes into account that it is righteous on God’s part to repay^&#42;1^ tribulation to those who make tribulation for YOU,

[NOTE]
====
. Lit., “to give back instead.”
====

[[v53-1-7]]

^<<v53-1-7,7>>^ but, to YOU who suffer tribulation, relief along with us at the revelation^&#42;1^ of the Lord Jesus from heaven with his powerful angels

[NOTE]
====
. Or, “uncovering; disclosure.” Gr., a·po·ka·lyʹpsei.
====

[[v53-1-8]]

^<<v53-1-8,8>>^ in a flaming fire, as he brings vengeance^&#42;1^ upon those who do not know God and those who do not obey the good news about our Lord Jesus.

[NOTE]
====
. “Vengeance.” Gr., ek·diʹke·sin; Lat., vin·dicʹtam.
====

[[v53-1-9]]

^<<v53-1-9,9>>^ These very ones will undergo the judicial punishment of everlasting destruction from before the Lord and from the glory of his strength,

[[v53-1-10]]

^<<v53-1-10,10>>^ at the time he comes to be glorified in connection with his holy ones and to be regarded in that day with wonder in connection with all those who exercised faith, because the witness^&#42;1^ we gave met with faith among YOU.

[NOTE]
====
. “Witness.” Gr., mar·tyʹri·on; Lat., te·sti·moʹni·um.
====

[[v53-1-11]]

^<<v53-1-11,11>>^ To that very end indeed we always pray for YOU, that our God may count YOU worthy of &#91;his&#93; calling and perform completely all he pleases of goodness and the work of faith with power;

[[v53-1-12]]

^<<v53-1-12,12>>^ in order that the name of our Lord Jesus may be glorified in YOU, and YOU in union with him, in accord with the undeserved kindness of our God and of the Lord Jesus Christ.^&#42;1^

[NOTE]
====
. See App 6E.
====

'''

xref:052-1-thessalonians/052-1-thessalonians-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-thessalonians/053-2-thessalonians-002.adoc#v53-2-0[Próximo Capítulo &#62;]