include::./index.adoc[]

[[v22-7-0]]
=== The Song of Solomon, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-7-1]]

^<<v22-7-1,1>>^ “How beautiful your steps have become in &#91;your&#93; sandals, O willing daughter! The curvings of your thighs are like ornaments, the work of an artisan’s hands.

[[v22-7-2]]

^<<v22-7-2,2>>^ Your navel roll is a round bowl. Let not the mixed wine be lacking &#91;from it&#93;. Your belly is a heap of wheat, fenced about with lilies.

[[v22-7-3]]

^<<v22-7-3,3>>^ Your two breasts are like two young ones, the twins of a female gazelle.

[[v22-7-4]]

^<<v22-7-4,4>>^ Your neck is like an ivory tower. Your eyes are like the pools in Heshʹbon, by the gate of Bath-rabʹbim. Your nose is like the tower of Lebʹa·non, which is looking out toward Damascus.

[[v22-7-5]]

^<<v22-7-5,5>>^ Your head upon you is like Carʹmel, and the tresses of your head are like wool dyed reddish purple. The king is held bound by the flowings.

[[v22-7-6]]

^<<v22-7-6,6>>^ How beautiful you are, and how pleasant you are, O beloved girl,^&#42;1^ among exquisite delights!

[NOTE]
====
. Lit., “O love.”
====

[[v22-7-7]]

^<<v22-7-7,7>>^ This stature of yours does resemble a palm tree, and your breasts, date clusters.

[[v22-7-8]]

^<<v22-7-8,8>>^ I have said, ‘I shall go up on the palm tree, that I may take hold of its fruit stalks of dates.’ And, please, may your breasts become like clusters of the vine, and the fragrance of your nose like apples,

[[v22-7-9]]

^<<v22-7-9,9>>^ and your palate like the best wine that is going with a slickness for my dear one, softly flowing over the lips of sleeping ones.”

[[v22-7-10]]

^<<v22-7-10,10>>^ “I am my dear one’s, and toward me is his craving.

[[v22-7-11]]

^<<v22-7-11,11>>^ Do come, O my dear one, let us go forth to the field; do let us lodge among the henna plants.^&#42;1^

[NOTE]
====
. “The villages,” LXXSyVg. But see 1:14; 4:13.
====

[[v22-7-12]]

^<<v22-7-12,12>>^ Do let us rise early and go to the vineyards, that we may see whether the vine has sprouted, the blossom has burst open, the pomegranate trees have bloomed. There I shall give my expressions of endearment to you.

[[v22-7-13]]

^<<v22-7-13,13>>^ The mandrakes themselves have given &#91;their&#93; fragrance, and by our entranceways there are all sorts of the choicest fruits. The new ones as well as the old, O my dear one, I have treasured up for you.

'''

xref:022-song-of-solomon/022-song-of-solomon-006.adoc#v22-6-0[&#60; Capítulo Anterior] | <<v22-7-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-008.adoc#v22-8-0[Próximo Capítulo &#62;]