include::./index.adoc[]

[[v22-4-0]]
=== The Song of Solomon, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-4-1]]

^<<v22-4-1,1>>^ “Look! You are beautiful, O girl companion of mine. Look! You are beautiful. Your eyes are &#91;those of&#93; doves, behind your veil. Your hair is like a drove of goats that have hopped down from the mountainous region of Gilʹe·ad.

[[v22-4-2]]

^<<v22-4-2,2>>^ Your teeth are like a drove of freshly shorn &#91;ewes&#93; that have gone up from the washing, all of which are bearing twins, with none among them having lost its young ones.

[[v22-4-3]]

^<<v22-4-3,3>>^ Your lips are just like a scarlet thread, and your speaking is agreeable. Like a segment of pomegranate are your temples behind your veil.

[[v22-4-4]]

^<<v22-4-4,4>>^ Your neck is like the tower of David, built in courses of stone, upon which are hung a thousand shields, all the circular shields of the mighty men.^&#42;1^

[NOTE]
====
. “The mighty men.” Heb., hag·gib·boh·rimʹ.
====

[[v22-4-5]]

^<<v22-4-5,5>>^ Your two breasts are like two young ones, the twins of a female gazelle, that are feeding among the lilies.”

[[v22-4-6]]

^<<v22-4-6,6>>^ “Until the day breathes and the shadows have fled, I shall go my way to the mountain of myrrh and to the hill of frankincense.”

[[v22-4-7]]

^<<v22-4-7,7>>^ “You are altogether beautiful, O girl companion of mine, and there is no defect in you.

[[v22-4-8]]

^<<v22-4-8,8>>^ With me from Lebʹa·non, O bride, with me from Lebʹa·non may you come. May you descend from the top of Anti-Lebʹa·non,^&#42;1^ from the top of Seʹnir, even Herʹmon, from the lairs of lions, from the mountains of leopards.

[NOTE]
====
. Lit., “Amanah.”
====

[[v22-4-9]]

^<<v22-4-9,9>>^ You have made my heart beat, O my sister, &#91;my&#93; bride, you have made my heart beat^&#42;1^ by one of your eyes, by one pendant of your necklace.

[NOTE]
====
. Or, “you have encouraged me.”
====

[[v22-4-10]]

^<<v22-4-10,10>>^ How beautiful your expressions of endearment are, O my sister, my bride! How much better your expressions of endearment are than wine and the fragrance of your oils than all sorts of perfume!

[[v22-4-11]]

^<<v22-4-11,11>>^ With comb honey your lips keep dripping, O &#91;my&#93; bride. Honey and milk are under your tongue, and the fragrance of your garments is like the fragrance of Lebʹa·non.

[[v22-4-12]]

^<<v22-4-12,12>>^ A garden barred in is my sister, &#91;my&#93; bride, a garden^&#42;1^ barred in, a spring sealed up.

[NOTE]
====
. “Garden,” LXXSyVg and many Heb. mss; M, “wave.”
====

[[v22-4-13]]

^<<v22-4-13,13>>^ Your skin is a paradise^&#42;1^ of pomegranates,^&#42;2^ with the choicest fruits, henna plants along with spikenard plants;

[NOTE]
====
. Lit., “park [preserve].” Heb., par·desʹ; LXXVg, “paradise”; Syr., par·dai·saʼ.
. Lit., “pomegranate trees.”
====

[[v22-4-14]]

^<<v22-4-14,14>>^ spikenard and saffron, cane and cinnamon, along with all sorts of trees of frankincense, myrrh and aloes, along with all the finest perfumes;

[[v22-4-15]]

^<<v22-4-15,15>>^ &#91;and&#93; a spring of gardens, a well of fresh water,^&#42;1^ and trickling streams from Lebʹa·non.

[NOTE]
====
. Lit., “living waters.” Heb., maʹyim chai·yimʹ.
====

[[v22-4-16]]

^<<v22-4-16,16>>^ Awake, O north wind, and come in, O south wind. Breathe upon my garden. Let its perfumes trickle.”
“Let my dear one come into his garden and eat its choicest fruits.”

'''

xref:022-song-of-solomon/022-song-of-solomon-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-005.adoc#v22-5-0[Próximo Capítulo &#62;]