include::./index.adoc[]

[[v22-8-0]]
=== The Song of Solomon, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-8-1]]

^<<v22-8-1,1>>^ “O that you were like a brother of mine, sucking the breasts of my mother! Should I find you outside, I would kiss you. People would not even despise me.

[[v22-8-2]]

^<<v22-8-2,2>>^ I would lead you, I would bring you into the house of my mother, who used to teach me. I would give you a drink of spiced wine, the fresh juice of pomegranates.

[[v22-8-3]]

^<<v22-8-3,3>>^ His left hand would be under my head; and his right hand—it would embrace me.

[[v22-8-4]]

^<<v22-8-4,4>>^ “I have put YOU under oath, O daughters of Jerusalem, that YOU try not to awaken or arouse love &#91;in me&#93; until it feels inclined.”

[[v22-8-5]]

^<<v22-8-5,5>>^ “Who is this woman coming up from the wilderness, leaning upon her dear one?”
“Under the apple tree I aroused you.^&#42;1^ There your mother was in birth pangs with you. There she that was giving birth to you experienced birth pangs.

[NOTE]
====
. “You,” masc.
====

[[v22-8-6]]

^<<v22-8-6,6>>^ “Place me as a seal upon your^&#42;1^ heart, as a seal upon your arm; because love is as strong as death is, insistence on exclusive devotion is as unyielding as Sheʹol^&#42;2^ is. Its blazings are the blazings of a fire, the flame of Jah.^&#42;3^

[NOTE]
====
. “Your,” masc.
. “As Sheol.” Heb., khish·ʼohlʹ; Gr., haiʹdes; Lat., inʹfer·us. See App 4B.
. “Jah.” This is the only place in The Song of Solomon where the divine name occurs, here in abbreviated form. See Gins.Int, pp. 386, 387; Ps 68:4 ftn; App 1A.
====

[[v22-8-7]]

^<<v22-8-7,7>>^ Many waters themselves are not able to extinguish love, nor can rivers themselves wash it away. If a man^&#42;1^ would give all the valuable things of his house for love, persons would positively despise them.”^&#42;2^

[NOTE]
====
. “Man.” Heb., ʼish.
. Or, “him.”
====

[[v22-8-8]]

^<<v22-8-8,8>>^ “We have a little sister that does not have any breasts. What shall we do for our sister on the day that she will be spoken for?”

[[v22-8-9]]

^<<v22-8-9,9>>^ “If she should be a wall, we shall build upon her a battlement of silver; but if she should be a door, we shall block her up with a cedar plank.”

[[v22-8-10]]

^<<v22-8-10,10>>^ “I am a wall, and my breasts are like towers. In this case I have become in his eyes like her that is finding peace.

[[v22-8-11]]

^<<v22-8-11,11>>^ “There was a vineyard that Solʹo·mon happened to have in Baʹal-haʹmon. He gave the vineyard over to the keepers. Each one would bring in for its fruitage a thousand silver pieces.^&#42;1^

[NOTE]
====
. Or, “a thousand pieces of money.”
====

[[v22-8-12]]

^<<v22-8-12,12>>^ “My vineyard, which belongs to me, is at my disposal.^&#42;1^ The thousand belong to you, O Solʹo·mon, and two hundred to those keeping its fruitage.”

[NOTE]
====
. Lit., “is before me.”
====

[[v22-8-13]]

^<<v22-8-13,13>>^ “O you who are dwelling in the gardens, the partners are paying attention to your^&#42;1^ voice. Let me hear it.”

[NOTE]
====
. “You,” and “your,” both fem.
====

[[v22-8-14]]

^<<v22-8-14,14>>^ “Run away, my dear one, and make yourself^&#42;1^ like a gazelle or like a young one of the stags upon the mountains of spices.”

[NOTE]
====
. “Yourself,” masc. Compare 2:8, 9, 16, 17.
====

'''

xref:022-song-of-solomon/022-song-of-solomon-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaiah/023-isaiah-001.adoc#v23-1-0[Próximo Capítulo &#62;]