include::./index.adoc[]

[[v22-2-0]]
=== The Song of Solomon, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-2-1]]

^<<v22-2-1,1>>^ “A mere saffron^&#42;1^ of the coastal plain^&#42;2^ I am, a lily of the low plains.”

[NOTE]
====
. Or, “crocus; asphodel.”
. “The coastal plain.” Or, “Sharon.” Heb., hash·sha·rohnʹ.
====

[[v22-2-2]]

^<<v22-2-2,2>>^ “Like a lily among thorny weeds, so is my girl companion among the daughters.”

[[v22-2-3]]

^<<v22-2-3,3>>^ “Like an apple tree among the trees of the forest, so is my dear one among the sons. His shade I have passionately desired, and there I have sat down, and his fruit has been sweet to my palate.

[[v22-2-4]]

^<<v22-2-4,4>>^ He brought me into the house of wine, and his banner over me was love.^&#42;1^

[NOTE]
====
. “Love.” Heb., ʼa·havahʹ.
====

[[v22-2-5]]

^<<v22-2-5,5>>^ Do YOU people refresh me with cakes of raisins, sustain me with apples; for I am lovesick.

[[v22-2-6]]

^<<v22-2-6,6>>^ His left hand is under my head; and his right hand—it embraces me.

[[v22-2-7]]

^<<v22-2-7,7>>^ I have put YOU under oath, O daughters of Jerusalem, by the female gazelles or by the hinds of the field, that YOU try not to awaken or arouse love &#91;in me&#93; until it feels inclined.

[[v22-2-8]]

^<<v22-2-8,8>>^ “The sound of my dear one! Look! This one is coming, climbing upon the mountains, leaping upon the hills.

[[v22-2-9]]

^<<v22-2-9,9>>^ My dear one is resembling a gazelle or the young of the stags. Look! This one is standing behind our wall, gazing through the windows, glancing through the lattices.

[[v22-2-10]]

^<<v22-2-10,10>>^ My dear one has answered and said to me, ‘Rise up, you girl companion of mine, my beautiful one, and come away.

[[v22-2-11]]

^<<v22-2-11,11>>^ For, look! the rainy season^&#42;1^ itself has passed, the downpour itself is over, it has gone its way.

[NOTE]
====
. Or, “the winter.”
====

[[v22-2-12]]

^<<v22-2-12,12>>^ Blossoms themselves have appeared in the land, the very time of vine trimming has arrived, and the voice of the turtledove itself has been heard in our land.

[[v22-2-13]]

^<<v22-2-13,13>>^ As for the fig tree, it has gained a mature color for its early figs; and the vines are abloom, they have given &#91;their&#93; fragrance. Rise up, come, O girl companion of mine, my beautiful one, and come away.

[[v22-2-14]]

^<<v22-2-14,14>>^ O my dove in the retreats of the crag, in the concealed place of the steep way, show me your form, let me hear your voice, for your voice is pleasurable and your form is comely.’”

[[v22-2-15]]

^<<v22-2-15,15>>^ “Do YOU people grab hold of the foxes for us, the little foxes that are making spoil of the vineyards, as our vineyards are abloom.”

[[v22-2-16]]

^<<v22-2-16,16>>^ “My dear one is mine and I am his. He is shepherding among the lilies.

[[v22-2-17]]

^<<v22-2-17,17>>^ Until the day breathes and the shadows have fled, turn around, O my dear one; be like the gazelle or like the young of the stags upon the mountains of separation.^&#42;1^

[NOTE]
====
. Or, “cleft mountains.” Lit., “mountains of Bether.” The meaning of “Bether” is uncertain.
====

'''

xref:022-song-of-solomon/022-song-of-solomon-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-003.adoc#v22-3-0[Próximo Capítulo &#62;]