include::./index.adoc[]

[[v22-3-0]]
=== The Song of Solomon, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-3-1]]

^<<v22-3-1,1>>^ “On my bed during the nights I have sought the one whom my soul has loved. I sought him, but I did not find him.

[[v22-3-2]]

^<<v22-3-2,2>>^ Let me rise up, please, and go round about in the city; in the streets and in the public squares let me seek the one whom my soul has loved. I sought him, but I did not find him.

[[v22-3-3]]

^<<v22-3-3,3>>^ The watchmen who were going around in the city found me, ‘The one whom my soul has loved have YOU men seen?’

[[v22-3-4]]

^<<v22-3-4,4>>^ Hardly had I passed on from them until I found the one whom my soul has loved. I grabbed hold of him, and I would not let go of him, until I had brought him into my mother’s house and into the interior room of her that had been pregnant with me.

[[v22-3-5]]

^<<v22-3-5,5>>^ I have put YOU under oath, O daughters of Jerusalem, by the female gazelles or by the hinds of the field, that YOU try not to awaken or arouse love &#91;in me&#93; until it feels inclined.”

[[v22-3-6]]

^<<v22-3-6,6>>^ “What^&#42;1^ is this thing that is coming up from the wilderness like columns of smoke, being perfumed with myrrh and frankincense, even with every sort of scent powder of a trader?”

[NOTE]
====
. Lit., “Who,” with a fem. predicate.
====

[[v22-3-7]]

^<<v22-3-7,7>>^ “Look! It is his couch, the one belonging to Solʹo·mon. Sixty mighty men^&#42;1^ are all around it, from the mighty men of Israel,

[NOTE]
====
. “Mighty men.” Heb., gib·bo·rimʹ.
====

[[v22-3-8]]

^<<v22-3-8,8>>^ all of them in possession of a sword, being taught in warfare, each one with his sword upon his thigh because of dread during the nights.”

[[v22-3-9]]

^<<v22-3-9,9>>^ “It is the litter that King Solʹo·mon has made for himself from the trees of Lebʹa·non.

[[v22-3-10]]

^<<v22-3-10,10>>^ Its pillars he has made of silver, its supports of gold. Its seat is of wool dyed reddish purple, its interior being fitted out lovingly^&#42;1^ by the daughters of Jerusalem.”

[NOTE]
====
. Or, “with ebony,” by a correction of M.
====

[[v22-3-11]]

^<<v22-3-11,11>>^ “Go out and look, O YOU daughters of Zion, on King Solʹo·mon with the wreath that his mother wove for him on the day of his marriage and on the day of the rejoicing of his heart.”

'''

xref:022-song-of-solomon/022-song-of-solomon-002.adoc#v22-2-0[&#60; Capítulo Anterior] | <<v22-3-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-004.adoc#v22-4-0[Próximo Capítulo &#62;]