include::./index.adoc[]

[[v22-5-0]]
=== The Song of Solomon, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-5-1]]

^<<v22-5-1,1>>^ “I have come into my garden, O my sister, &#91;my&#93; bride. I have plucked my myrrh along with my spice. I have eaten my honeycomb along with my honey; I have drunk my wine along with my milk.”
“Eat, O companions! Drink and become drunk with expressions of endearment!”^&#42;1^

[NOTE]
====
. Or, “become drunk, O dear ones!”
====

[[v22-5-2]]

^<<v22-5-2,2>>^ “I am asleep, but my heart is awake. There is the sound of my dear one knocking!”
“Open to me, O my sister, my girl companion, my dove, my blameless one! For my head is filled with dew, the locks of my hair with the drops of the night.”

[[v22-5-3]]

^<<v22-5-3,3>>^ “‘I have put off my robe. How can I put it back on? I have washed my feet. How can I soil them?’

[[v22-5-4]]

^<<v22-5-4,4>>^ My dear one himself pulled back his hand from the hole &#91;of the door&#93;, and my inward parts themselves became boisterous within me.^&#42;1^

[NOTE]
====
. “Within me,” more than 50 Heb. mss and some printed Heb. ed.; MLXXSyVg, “over him.”
====

[[v22-5-5]]

^<<v22-5-5,5>>^ I got up, even I, to open to my dear one, and my own hands dripped with myrrh and my fingers with liquid^&#42;1^ myrrh, upon the hollows of the lock.^&#42;2^

[NOTE]
====
. Lit., “current (passing along).”
. That is, the hollow into which the door bolt is pushed.
====

[[v22-5-6]]

^<<v22-5-6,6>>^ I opened, even I, to my dear one, but my dear one himself had turned away, he had passed along. My very soul had gone out &#91;of me&#93; when he spoke. I sought him, but I did not find him. I called him, but he did not answer me.

[[v22-5-7]]

^<<v22-5-7,7>>^ The watchmen that were going about in the city found me. They struck me, they wounded me. The watchmen of the walls lifted my wide wrap off me.

[[v22-5-8]]

^<<v22-5-8,8>>^ “I have put YOU under oath, O daughters of Jerusalem, that, if YOU find my dear one, YOU should tell him that I am lovesick.”

[[v22-5-9]]

^<<v22-5-9,9>>^ “How is your dear one more than any other dear one, O you most beautiful one among women? How is your dear one more than any other dear one, that you have put us under such an oath as this?”

[[v22-5-10]]

^<<v22-5-10,10>>^ “My dear one is dazzling and ruddy, the most conspicuous^&#42;1^ of ten thousand.

[NOTE]
====
. Lit., “lifted up like a banner.”
====

[[v22-5-11]]

^<<v22-5-11,11>>^ His head is gold, refined gold. The locks of his hair are date clusters. His black &#91;hair&#93; is like the raven.

[[v22-5-12]]

^<<v22-5-12,12>>^ His eyes are like doves by the channels of water, which are bathing themselves in milk, sitting within the rims.

[[v22-5-13]]

^<<v22-5-13,13>>^ His cheeks are like a garden bed of spice, towers of scented herbs. His lips are lilies, dripping with liquid myrrh.

[[v22-5-14]]

^<<v22-5-14,14>>^ His hands are cylinders of gold, filled with chrysʹo·lite.^&#42;1^ His abdomen is an ivory plate covered with sapphires.

[NOTE]
====
. “With chrysolite.” Heb., bat·tar·shishʹ.
====

[[v22-5-15]]

^<<v22-5-15,15>>^ His legs are pillars of marble based on socket pedestals of refined gold. His appearance is like Lebʹa·non, choice like the cedars.

[[v22-5-16]]

^<<v22-5-16,16>>^ His palate is sheer sweetness, and everything about him is altogether desirable. This is my dear one, and this is my boy companion, O daughters of Jerusalem.”

'''

xref:022-song-of-solomon/022-song-of-solomon-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-006.adoc#v22-6-0[Próximo Capítulo &#62;]