include::./index.adoc[]

[[v22-1-0]]
=== The Song of Solomon, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v22-1-1]]

^<<v22-1-1,1>>^ The superlative song,^&#42;1^ which is Solʹo·mon’s:

[NOTE]
====
. Or, “The most beautiful (most excellent) song.” Lit., “Song of the songs.”
====

[[v22-1-2]]

^<<v22-1-2,2>>^ “May he kiss me with the kisses of his mouth, for your expressions of endearment^&#42;1^ are better than wine.

[NOTE]
====
. Lit., “your endearments.” Heb., do·dheyʹkha.
====

[[v22-1-3]]

^<<v22-1-3,3>>^ For fragrance your oils are good. Like an oil that is poured out is your name. That is why maidens themselves have loved you.

[[v22-1-4]]

^<<v22-1-4,4>>^ Draw me with^&#42;1^ you; let us run. The king has brought me into his interior rooms! Do let us be joyful and rejoice in you. Do let us mention your expressions of endearment more than wine. Deservedly they have loved you.

[NOTE]
====
. Or, “after.” See Jg 13:11 ftn; Ru 1:16 ftn.
====

[[v22-1-5]]

^<<v22-1-5,5>>^ “A black girl I am, but comely, O YOU daughters of Jerusalem, like the tents of Keʹdar, &#91;yet&#93; like the tent cloths of Solʹo·mon.

[[v22-1-6]]

^<<v22-1-6,6>>^ Do not YOU look at me because I am swarthy, because the sun has caught sight of me. The sons of my own mother grew angry with me; they appointed me the keeper of the vineyards, &#91;although&#93; my vineyard, one that was mine, I did not keep.

[[v22-1-7]]

^<<v22-1-7,7>>^ “Do tell me, O you whom my soul has loved, where you do shepherding, where you make the flock lie down at midday. Just why should I become like a woman wrapped in mourning among the droves of your partners?”

[[v22-1-8]]

^<<v22-1-8,8>>^ “If you do not know for yourself, O you most beautiful one among women, go out yourself in the footprints of the flock and pasture your kids of the goats alongside the tabernacles of the shepherds.”

[[v22-1-9]]

^<<v22-1-9,9>>^ “To a mare of mine in the chariots of Pharʹaoh I have likened you, O girl companion of mine.

[[v22-1-10]]

^<<v22-1-10,10>>^ Your cheeks are comely among the hair braids, your neck in a string of beads.

[[v22-1-11]]

^<<v22-1-11,11>>^ Circlets of gold we shall make for you, along with studs of silver.”

[[v22-1-12]]

^<<v22-1-12,12>>^ “As long as the king is at his round table my own spikenard has given out its fragrance.

[[v22-1-13]]

^<<v22-1-13,13>>^ As a bag of myrrh my dear one is to me; between my breasts he will spend the night.

[[v22-1-14]]

^<<v22-1-14,14>>^ As a cluster of henna my dear one is to me, among the vineyards of En-geʹdi.”

[[v22-1-15]]

^<<v22-1-15,15>>^ “Look! You are beautiful, O girl companion of mine. Look! You are beautiful. Your eyes are &#91;those of&#93; doves.”

[[v22-1-16]]

^<<v22-1-16,16>>^ “Look! You are beautiful,^&#42;1^ my dear one, also pleasant. Our divan also is one of foliage.

[NOTE]
====
. “You are beautiful,” masc., referring to her shepherd lover.
====

[[v22-1-17]]

^<<v22-1-17,17>>^ The beams of our grand house^&#42;1^ are cedars, our rafters juniper trees.

[NOTE]
====
. Lit., “our houses.”
====

'''

xref:021-ecclesiastes/021-ecclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-song-of-solomon/022-song-of-solomon-002.adoc#v22-2-0[Próximo Capítulo &#62;]