include::./index.adoc[]

[[v43-21-0]]
=== According to John, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-21-1]]

^<<v43-21-1,1>>^ After these things Jesus manifested himself again to the disciples at the sea of Ti·beʹri·as; but he made the manifestation in this way.

[[v43-21-2]]

^<<v43-21-2,2>>^ There were in company Simon Peter and Thomas, who was called The Twin, and Na·thanʹa·el from Caʹna of Galʹi·lee and the sons of Zebʹe·dee and two others of his disciples.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simon Peter said to them: “I am going fishing.” They said to him: “We also are coming with you.” Out they went and got aboard the boat, but during that night they caught nothing.

[[v43-21-4]]

^<<v43-21-4,4>>^ However, just as it was getting to be morning, Jesus stood on the beach, but the disciples did not, of course, discern that it was Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Then Jesus said to them: “Young children, YOU do not have anything to eat, do YOU?” They answered “No!” to him.

[[v43-21-6]]

^<<v43-21-6,6>>^ He said to them: “Cast the net on the right side of the boat and YOU will find &#91;some&#93;.” Then they cast it, but they were no longer able to draw it in because of the multitude of the fishes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Therefore that disciple whom Jesus used to love^&#42;1^ said to Peter: “It is the Lord!”^&#42;2^ Hence Simon Peter, upon hearing that it was the Lord, girded about himself his top garment, for he was naked, and plunged into the sea.

[NOTE]
====
. Or, “prefer.”
. Or, “Master.”
====

[[v43-21-8]]

^<<v43-21-8,8>>^ But the other disciples came in the little boat, for they were not a long way from land, only about three hundred feet^&#42;1^ away, dragging the net of fishes.

[NOTE]
====
. Lit., “about two hundred cubits.” See App 8A.
====

[[v43-21-9]]

^<<v43-21-9,9>>^ However, when they disembarked onto land they beheld lying there a charcoal fire and fish lying upon it and bread.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus said to them: “Bring some of the fish YOU just now caught.”

[[v43-21-11]]

^<<v43-21-11,11>>^ Simon Peter, therefore, went on board and drew the net to land full of big fishes, one hundred and fifty-three of them. But although there were so many the net did not burst.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus said to them: “Come, take YOUR breakfast.” Not one of the disciples had the courage to inquire of him: “Who are you?” because they knew it was the Lord.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus came and took the bread and gave it to them, and the fish likewise.

[[v43-21-14]]

^<<v43-21-14,14>>^ This was now the third time that Jesus appeared to the disciples after his being raised up from the dead.

[[v43-21-15]]

^<<v43-21-15,15>>^ When, now, they had breakfasted, Jesus said to Simon Peter: “Simon son of John,^&#42;1^ do you love^&#42;2^ me more than these?” He said to him: “Yes, Lord, you know I have affection for you.”^&#42;3^ He said to him: “Feed my lambs.”

[NOTE]
====
. “John,” BVg; ASyp,s, “Jona.” See 1:42 ftn, “John.”
. Lit., “are you loving.” Gr., a·ga·paisʹ.
. Lit., “I am having affection for you.” Gr., phi·loʹ se.
====

[[v43-21-16]]

^<<v43-21-16,16>>^ Again he said to him, a second time: “Simon son of John, do you love^&#42;1^ me?” He said to him: “Yes, Lord, you know I have affection for you.”^&#42;2^ He said to him: “Shepherd my little sheep.”

[NOTE]
====
. Lit., “are you loving.” Gr., a·ga·paisʹ.
. Lit., “I am having affection for you.” Gr., phi·loʹ se.
====

[[v43-21-17]]

^<<v43-21-17,17>>^ He said to him the third time: “Simon son of John, do you have affection for me?”^&#42;1^ Peter became grieved that he said to him the third time: “Do you have affection for me?” So he said to him: “Lord, you know all things; you are aware that I have affection for you.”^&#42;2^ Jesus said to him: “Feed my little sheep.

[NOTE]
====
. Lit., “are you having affection for me?” Gr., phi·leisʹ me.
. Lit., “I am having affection for you.” Gr., phi·loʹ se.
====

[[v43-21-18]]

^<<v43-21-18,18>>^ Most truly I say to you, When you were younger, you used to gird yourself and walk about where you wanted. But when you grow old you will stretch out your hands and another &#91;man&#93; will gird you and bear you where you do not wish.”

[[v43-21-19]]

^<<v43-21-19,19>>^ This he said to signify by what sort of death he would glorify God. So, when he had said this, he said to him: “Continue following me.”

[[v43-21-20]]

^<<v43-21-20,20>>^ Upon turning about Peter saw the disciple whom Jesus used to love^&#42;1^ following, the one who at the evening meal had also leaned back upon his breast and said: “Lord, who is the one betraying you?”

[NOTE]
====
. Or, “prefer.”
====

[[v43-21-21]]

^<<v43-21-21,21>>^ Accordingly, when he caught sight of him, Peter said to Jesus: “Lord, what will this &#91;man do&#93;?”

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus said to him: “If it is my will for him to remain until I come, of what concern is that to you? You continue following me.”

[[v43-21-23]]

^<<v43-21-23,23>>^ In consequence, this saying went out among the brothers, that that disciple would not die. However, Jesus did not say to him that he would not die, but: “If it is my will for him to remain until I come, of what concern is that to you?”

[[v43-21-24]]

^<<v43-21-24,24>>^ This is the disciple that bears witness about these things and that wrote these things, and we know that the witness he gives is true.

[[v43-21-25]]

^<<v43-21-25,25>>^ There are, in fact, many other things also which Jesus did, which, if ever they were written in full detail, I suppose, the world itself could not contain the scrolls written.^&#42;1^

[NOTE]
====
. Vs 25 is contained in אcABCVgSyp,s; א* omits.
====

'''

xref:043-john/043-john-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-acts/044-acts-001.adoc#v44-1-0[Próximo Capítulo &#62;]