include::./index.adoc[]

[[v43-5-0]]
=== According to John, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-5-1]]

^<<v43-5-1,1>>^ After these things there was a^&#42;1^ festival of the Jews, and Jesus went up to Jerusalem.

[NOTE]
====
. “A,” ABD; אC, “the.”
====

[[v43-5-2]]

^<<v43-5-2,2>>^ Now in Jerusalem at the sheepgate there is a pool designated in Hebrew Beth·zaʹtha,^&#42;1^ with five colonnades.

[NOTE]
====
. “Bethzatha” (meaning “House of the Olive,” or, “House of Olives”), א; P75BVg, “Bethsaida,” meaning “House of Fishing”; ACSyc,hi,pArm, “Bethesda.”
====

[[v43-5-3]]

^<<v43-5-3,3>>^ In these a multitude of the sick, blind, lame and those with withered members, was lying down.

[[v43-5-4]]

^<<v43-5-4,4>>^ ^&#42;1^ ——

[NOTE]
====
. P66,​75אBDVgSyc omit vs 4; AItVgcSyhi,pArm add: “For an angel of the Lord [J9,​22,​23, “of Jehovah”] would come down into the pool from season to season and disturb the water; the first one then to step in after the disturbance of the water would become sound in health from whatever disease it was by which he was afflicted.”
====

[[v43-5-5]]

^<<v43-5-5,5>>^ But a certain man was there who had been in his sickness for thirty-eight years.

[[v43-5-6]]

^<<v43-5-6,6>>^ Seeing this man lying down, and being aware that he had already been &#91;sick&#93; a long time, Jesus said to him: “Do you want to become sound in health?”

[[v43-5-7]]

^<<v43-5-7,7>>^ The sick man answered him: “Sir, I do not have a man to put me into the pool when the water is disturbed; but while I am coming another steps down ahead of me.”

[[v43-5-8]]

^<<v43-5-8,8>>^ Jesus said to him: “Get up, pick up your cot and walk.”

[[v43-5-9]]

^<<v43-5-9,9>>^ With that the man immediately became sound in health, and he picked up his cot and began to walk.
Now on that day it was a sabbath.

[[v43-5-10]]

^<<v43-5-10,10>>^ Therefore the Jews began to say to the cured man: “It is Sabbath, and it is not lawful for you to carry the cot.”

[[v43-5-11]]

^<<v43-5-11,11>>^ But he answered them: “The very one that made me sound in health said to me, ‘Pick up your cot and walk.’”

[[v43-5-12]]

^<<v43-5-12,12>>^ They asked him: “Who is the man that told you, ‘Pick it up and walk’?”

[[v43-5-13]]

^<<v43-5-13,13>>^ But the healed man did not know who he was, for Jesus had turned aside, there being a crowd in the place.

[[v43-5-14]]

^<<v43-5-14,14>>^ After these things Jesus found him in the temple and said to him: “See, you have become sound in health. Do not sin anymore, in order that something worse does not happen to you.”

[[v43-5-15]]

^<<v43-5-15,15>>^ The man went away and told the Jews it was Jesus that made him sound in health.

[[v43-5-16]]

^<<v43-5-16,16>>^ So on this account the Jews went persecuting Jesus, because he was doing these things during Sabbath.

[[v43-5-17]]

^<<v43-5-17,17>>^ But he answered them: “My Father has kept working until now, and I keep working.”

[[v43-5-18]]

^<<v43-5-18,18>>^ On this account, indeed, the Jews began seeking all the more to kill him, because not only was he breaking the Sabbath but he was also calling God his own Father, making himself equal to God.

[[v43-5-19]]

^<<v43-5-19,19>>^ Therefore, in answer, Jesus^&#42;1^ went on to say to them: “Most truly I say to YOU, The Son cannot do a single thing of his own initiative,^&#42;2^ but only what he beholds the Father doing. For whatever things that One does, these things the Son also does in like manner.

[NOTE]
====
. “Jesus,” אAVg; B, “he.”
. Or, “thing original with him.”
====

[[v43-5-20]]

^<<v43-5-20,20>>^ For the Father has affection for the Son and shows him all the things he himself does, and he will show him works greater than these, in order that YOU may marvel.

[[v43-5-21]]

^<<v43-5-21,21>>^ For just as the Father raises the dead up and makes them alive, so the Son also makes those alive whom he wants to.

[[v43-5-22]]

^<<v43-5-22,22>>^ For the Father judges no one at all, but he has committed all the judging to the Son,

[[v43-5-23]]

^<<v43-5-23,23>>^ in order that all may honor the Son just as they honor the Father. He that does not honor the Son does not honor the Father who sent him.

[[v43-5-24]]

^<<v43-5-24,24>>^ Most truly I say to YOU, He that hears my word and believes him that sent me has everlasting life, and he does not come into judgment but has passed over from death to life.

[[v43-5-25]]

^<<v43-5-25,25>>^ “Most truly I say to YOU, The hour is coming, and it is now, when the dead will hear the voice of the Son of God and those who have given heed will live.

[[v43-5-26]]

^<<v43-5-26,26>>^ For just as the Father has life in himself,^&#42;1^ so he has granted also to the Son to have life in himself.

[NOTE]
====
. Or, “in himself the gift of life.” See Ro 6:23.
====

[[v43-5-27]]

^<<v43-5-27,27>>^ And he has given him authority to do judging, because Son of man he is.

[[v43-5-28]]

^<<v43-5-28,28>>^ Do not marvel at this, because the hour is coming in which all those in the memorial tombs will hear his voice

[[v43-5-29]]

^<<v43-5-29,29>>^ and come out, those who did good things to a resurrection of life, those who practiced vile things to a resurrection of judgment.^&#42;1^

[NOTE]
====
. “Resurrection of judgment.” Gr., a·naʹsta·sin kriʹse·os; Lat., re·sur·rec·ti·oʹnem iu·diʹci·i.
====

[[v43-5-30]]

^<<v43-5-30,30>>^ I cannot do a single thing of my own initiative;^&#42;1^ just as I hear, I judge; and the judgment that I render is righteous, because I seek, not my own will, but the will of him that sent me.

[NOTE]
====
. Or, “thing original with me.”
====

[[v43-5-31]]

^<<v43-5-31,31>>^ “If I alone bear witness about myself, my witness is not true.

[[v43-5-32]]

^<<v43-5-32,32>>^ There is another that bears witness about me, and I know that the witness which he bears about me is true.

[[v43-5-33]]

^<<v43-5-33,33>>^ YOU have dispatched men to John, and he has borne witness to the truth.

[[v43-5-34]]

^<<v43-5-34,34>>^ However, I do not accept the witness from man, but I say these things that YOU may be saved.

[[v43-5-35]]

^<<v43-5-35,35>>^ That man was a burning and shining lamp, and YOU for a short time were willing to rejoice greatly in his light.

[[v43-5-36]]

^<<v43-5-36,36>>^ But I have the witness greater than that of John, for the very works that my Father assigned me to accomplish, the works themselves that I am doing, bear witness about me that the Father dispatched me.

[[v43-5-37]]

^<<v43-5-37,37>>^ Also, the Father who sent me has himself borne witness about me. YOU have neither heard his voice at any time nor seen his figure;

[[v43-5-38]]

^<<v43-5-38,38>>^ and YOU do not have his word remaining in YOU, because the very one whom he dispatched YOU do not believe.

[[v43-5-39]]

^<<v43-5-39,39>>^ “YOU are searching the Scriptures, because YOU think that by means of them YOU will have everlasting life; and these are the very ones that bear witness about me.

[[v43-5-40]]

^<<v43-5-40,40>>^ And yet YOU do not want to come to me that YOU may have life.

[[v43-5-41]]

^<<v43-5-41,41>>^ I do not accept glory from men,

[[v43-5-42]]

^<<v43-5-42,42>>^ but I well know that YOU do not have the love of God in YOU.

[[v43-5-43]]

^<<v43-5-43,43>>^ I have come in the name of my Father, but YOU do not receive me; if someone else arrived in his own name, YOU would receive that one.

[[v43-5-44]]

^<<v43-5-44,44>>^ How can YOU believe, when YOU are accepting glory from one another and YOU are not seeking the glory that is from the only God?^&#42;1^

[NOTE]
====
. “God,” אADItVgSyc,h,hi,p; P66,​75B omit.
====

[[v43-5-45]]

^<<v43-5-45,45>>^ Do not think that I will accuse YOU to the Father; there is one that accuses YOU, Moses, in whom YOU have put YOUR hope.

[[v43-5-46]]

^<<v43-5-46,46>>^ In fact, if YOU believed Moses YOU would believe me, for that one wrote about me.

[[v43-5-47]]

^<<v43-5-47,47>>^ But if YOU do not believe the writings of that one, how will YOU believe my sayings?”

'''

xref:043-john/043-john-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-john/043-john-006.adoc#v43-6-0[Próximo Capítulo &#62;]