include::./index.adoc[]

[[v43-18-0]]
=== According to John, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-18-1]]

^<<v43-18-1,1>>^ Having said these things, Jesus went out with his disciples across the winter torrent^&#42;1^ of Kidʹron to where there was a garden, and he and his disciples entered into it.

[NOTE]
====
. Or, “the valley.”
====

[[v43-18-2]]

^<<v43-18-2,2>>^ Now Judas, his betrayer, also knew the place, because Jesus had many times met there with his disciples.

[[v43-18-3]]

^<<v43-18-3,3>>^ Therefore Judas took the soldier band and officers of the chief priests and of the Pharisees and came there with torches and lamps and weapons.

[[v43-18-4]]

^<<v43-18-4,4>>^ Jesus, therefore, knowing all the things coming upon him, went forth and said to them: “Whom are YOU looking for?”

[[v43-18-5]]

^<<v43-18-5,5>>^ They answered him: “Jesus the Naz·a·reneʹ.” He said to them: “I am &#91;he&#93;.” Now Judas, his betrayer, was also standing with them.

[[v43-18-6]]

^<<v43-18-6,6>>^ However, when he said to them: “I am &#91;he&#93;,” they drew back and fell to the ground.

[[v43-18-7]]

^<<v43-18-7,7>>^ Therefore he asked them again: “Whom are YOU looking for?” They said: “Jesus the Naz·a·reneʹ.”

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus answered: “I told YOU I am &#91;he&#93;. If, therefore, it is I YOU are looking for, let these go”;

[[v43-18-9]]

^<<v43-18-9,9>>^ in order that the word might be fulfilled which he said: “Of those whom you have given me I have not lost a single one.”

[[v43-18-10]]

^<<v43-18-10,10>>^ Then Simon Peter, as he had a sword, drew it and struck the slave of the high priest and cut his right ear off. The name of the slave was Malchus.

[[v43-18-11]]

^<<v43-18-11,11>>^ Jesus, however, said to Peter: “Put the sword into &#91;its&#93; sheath. The cup that the Father has given me, should I not by all means drink it?”

[[v43-18-12]]

^<<v43-18-12,12>>^ Then the soldier band and the military commander^&#42;1^ and the officers of the Jews seized Jesus and bound him,

[NOTE]
====
. Or, “the chiliarch.” Gr., ho khi·liʹar·khos; commander of 1,000 soldiers.
====

[[v43-18-13]]

^<<v43-18-13,13>>^ and they led him first to Anʹnas; for he was father-in-law to Caʹia·phas, who was high priest that year.

[[v43-18-14]]

^<<v43-18-14,14>>^ Caʹia·phas was, in fact, the one that counseled the Jews that it was to their benefit for one man to die in behalf of the people.

[[v43-18-15]]

^<<v43-18-15,15>>^ Now Simon Peter as well as another disciple was following Jesus. That disciple was known to the high priest, and he went in with Jesus into the courtyard of the high priest,

[[v43-18-16]]

^<<v43-18-16,16>>^ but Peter was standing outside at the door. Therefore the other disciple, who was known to the high priest, went out and spoke to the doorkeeper and brought Peter in.

[[v43-18-17]]

^<<v43-18-17,17>>^ The servant girl, the doorkeeper, then said to Peter: “You are not also one of this man’s disciples, are you?” He said: “I am not.”

[[v43-18-18]]

^<<v43-18-18,18>>^ Now the slaves and the officers were standing about, as they had built a charcoal fire, because it was cold, and they were warming themselves. Peter also was standing with them and warming himself.

[[v43-18-19]]

^<<v43-18-19,19>>^ And so the chief priest questioned Jesus about his disciples and about his teaching.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus answered him: “I have spoken to the world publicly. I always taught in a synagogue and in the temple, where all the Jews come together; and I spoke nothing in secret.

[[v43-18-21]]

^<<v43-18-21,21>>^ Why do you question me? Question those who have heard what I spoke to them. See! These know what I said.”

[[v43-18-22]]

^<<v43-18-22,22>>^ After he said these things, one of the officers that was standing by gave Jesus a slap in the face and said: “Is that the way you answer the chief priest?”

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus answered him: “If I spoke wrongly, bear witness concerning the wrong; but if rightly, why do you hit me?”

[[v43-18-24]]

^<<v43-18-24,24>>^ Then Anʹnas sent him away bound to Caʹia·phas the high priest.

[[v43-18-25]]

^<<v43-18-25,25>>^ Now Simon Peter was standing and warming himself. Then they said to him: “You are not also one of his disciples, are you?” He denied it and said: “I am not.”

[[v43-18-26]]

^<<v43-18-26,26>>^ One of the slaves of the high priest, being a relative of the man whose ear Peter cut off, said: “I saw you in the garden with him, did I not?”

[[v43-18-27]]

^<<v43-18-27,27>>^ However, Peter denied it again; and immediately a cock crowed.

[[v43-18-28]]

^<<v43-18-28,28>>^ Then they led Jesus from Caʹia·phas to the governor’s palace. It was now early in the day. But they themselves did not enter into the governor’s palace, that they might not get defiled but might eat the passover.

[[v43-18-29]]

^<<v43-18-29,29>>^ Therefore Pilate came outside to them and said: “What accusation do YOU bring against this man?”

[[v43-18-30]]

^<<v43-18-30,30>>^ In answer they said to him: “If this man were not a wrongdoer, we would not have delivered him up to you.”

[[v43-18-31]]

^<<v43-18-31,31>>^ Hence Pilate said to them: “Take him yourselves and judge him according to YOUR law.” The Jews said to him: “It is not lawful for us to kill anyone.”

[[v43-18-32]]

^<<v43-18-32,32>>^ This, in order that the word of Jesus might be fulfilled which he said to signify what sort of death he was destined to die.

[[v43-18-33]]

^<<v43-18-33,33>>^ So Pilate entered into the governor’s palace again and called Jesus and said to him: “Are you the king of the Jews?”^&#42;1^

[NOTE]
====
. “King of the Jews.” Gr., ba·si·leusʹ ton I·ou·daiʹon; Lat., rex Iu·dae·oʹrum; J17,​18,​22(Heb.), meʹlekh hai·Yehu·dhimʹ.
====

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus answered: “Is it of your own originality that you say this, or did others tell you about me?”

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilate answered: “I am not a Jew, am I? Your own nation and the chief priests delivered you up to me. What did you do?”

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus answered: “My kingdom is no part of this world. If my kingdom were part of this world, my attendants would have fought that I should not be delivered up to the Jews. But, as it is, my kingdom is not from this source.”

[[v43-18-37]]

^<<v43-18-37,37>>^ Therefore Pilate said to him: “Well, then, are you a king?” Jesus answered: “You yourself are saying that I am a king. For this I have been born, and for this I have come into the world, that I should bear witness^&#42;1^ to the truth. Everyone that is on the side of the truth listens to my voice.”

[NOTE]
====
. “I should bear witness.” Gr., mar·ty·reʹso; Lat., te·sti·moʹni·um per·hiʹbe·am.
====

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilate said to him: “What is truth?”^&#42;1^
And after saying this, he went out again to the Jews and said to them: “I find no fault in him.

[NOTE]
====
. “What is truth?” Gr., Tiʹ e·stin a·leʹthei·a; Lat., Quid est veʹri·tas; J17,​18(Heb.), Mah hiʼ ha·ʼemethʹ.
====

[[v43-18-39]]

^<<v43-18-39,39>>^ Moreover, YOU have a custom that I should release a man to YOU at the passover. Do YOU, therefore, wish me to release to YOU the king of the Jews?”

[[v43-18-40]]

^<<v43-18-40,40>>^ Then they shouted again, saying: “Not this man, but Bar·abʹbas!” Now Bar·abʹbas was a robber.

'''

xref:043-john/043-john-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-john/043-john-019.adoc#v43-19-0[Próximo Capítulo &#62;]