include::./index.adoc[]

[[v43-2-0]]
=== According to John, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-2-1]]

^<<v43-2-1,1>>^ Now on the third day a marriage feast took place in Caʹna of Galʹi·lee, and the mother of Jesus was there.

[[v43-2-2]]

^<<v43-2-2,2>>^ Jesus and his disciples were also invited to the marriage feast.

[[v43-2-3]]

^<<v43-2-3,3>>^ When the wine ran short the mother of Jesus said to him: “They have no wine.”

[[v43-2-4]]

^<<v43-2-4,4>>^ But Jesus said to her: “What have I to do with you,^&#42;1^ woman? My hour has not yet come.”

[NOTE]
====
. Lit., “What to me and to you?” meaning “What is there in common between me and you?” An idiom; a repellent question indicating objection. See App 7B.
====

[[v43-2-5]]

^<<v43-2-5,5>>^ His mother said to those ministering: “Whatever he tells YOU, do.”

[[v43-2-6]]

^<<v43-2-6,6>>^ As it was, there were six stone water jars sitting there as required by the purification rules of the Jews, each able to hold two or three liquid measures.^&#42;1^

[NOTE]
====
. Likely the bath that equaled 22 L (5.81 gal). See App 8A.
====

[[v43-2-7]]

^<<v43-2-7,7>>^ Jesus said to them: “Fill the water jars with water.” And they filled them to the brim.

[[v43-2-8]]

^<<v43-2-8,8>>^ And he said to them: “Draw some out now and take it to the director of the feast.” So they took it.

[[v43-2-9]]

^<<v43-2-9,9>>^ When, now, the director of the feast tasted the water that had been turned into wine but did not know what its source was, although those ministering who had drawn out the water knew, the director of the feast called the bridegroom

[[v43-2-10]]

^<<v43-2-10,10>>^ and said to him: “Every other man puts out the fine wine first, and when people are intoxicated, the inferior. You have reserved the fine wine until now.”

[[v43-2-11]]

^<<v43-2-11,11>>^ Jesus performed this in Caʹna of Galʹi·lee as &#91;the&#93; beginning of his signs, and he made his glory manifest; and his disciples put their faith in him.

[[v43-2-12]]

^<<v43-2-12,12>>^ After this he and his mother and brothers and his disciples went down to Ca·perʹna·um, but they did not stay there many days.

[[v43-2-13]]

^<<v43-2-13,13>>^ Now the passover of the Jews was near, and Jesus went up to Jerusalem.

[[v43-2-14]]

^<<v43-2-14,14>>^ And he found in the temple those selling cattle and sheep and doves and the money brokers in their seats.

[[v43-2-15]]

^<<v43-2-15,15>>^ So, after making a whip of ropes, he drove all those with the sheep and cattle out of the temple, and he poured out the coins of the money changers and overturned their tables.

[[v43-2-16]]

^<<v43-2-16,16>>^ And he said to those selling the doves: “Take these things away from here! Stop making the house of my Father a house of merchandise!”

[[v43-2-17]]

^<<v43-2-17,17>>^ His disciples called to mind that it is written: “The zeal for your house will eat me up.”

[[v43-2-18]]

^<<v43-2-18,18>>^ Therefore, in answer, the Jews said to him: “What sign have you to show us, since you are doing these things?”

[[v43-2-19]]

^<<v43-2-19,19>>^ In answer Jesus said to them: “Break down this temple,^&#42;1^ and in three days I will raise it up.”

[NOTE]
====
. Or, “divine habitation (dwelling).” Gr., na·onʹ; Lat., temʹplum; J17,​18,​22(Heb.), ha·heh·khalʹ haz·zehʹ, “this palace (temple).”
====

[[v43-2-20]]

^<<v43-2-20,20>>^ Therefore the Jews said: “This temple was built in forty-six years, and will you raise it up in three days?”

[[v43-2-21]]

^<<v43-2-21,21>>^ But he was talking about the temple of his body.

[[v43-2-22]]

^<<v43-2-22,22>>^ When, though, he was raised up from the dead, his disciples called to mind that he used to say this; and they believed the Scripture and the saying that Jesus said.

[[v43-2-23]]

^<<v43-2-23,23>>^ However, when he was in Jerusalem at the passover, at its festival, many people put their faith in his name, viewing his signs that he was performing.

[[v43-2-24]]

^<<v43-2-24,24>>^ But Jesus himself was not entrusting himself to them because of his knowing them all

[[v43-2-25]]

^<<v43-2-25,25>>^ and because he was in no need to have anyone bear witness about man, for he himself knew what was in man.

'''

xref:043-john/043-john-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-john/043-john-003.adoc#v43-3-0[Próximo Capítulo &#62;]