include::./index.adoc[]

[[v43-16-0]]
=== According to John, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-16-1]]

^<<v43-16-1,1>>^ “I have spoken these things to YOU that YOU may not be stumbled.

[[v43-16-2]]

^<<v43-16-2,2>>^ Men will expel YOU from the synagogue.^&#42;1^ In fact, the hour is coming when everyone that kills YOU will imagine he has rendered a sacred service^&#42;2^ to God.

[NOTE]
====
. Compare 9:22 ftn.
. “A sacred service.” Gr., la·treiʹan. Compare Ex 12:25 ftn.
====

[[v43-16-3]]

^<<v43-16-3,3>>^ But they will do these things because they have not come to know either the Father or me.

[[v43-16-4]]

^<<v43-16-4,4>>^ Nevertheless, I have spoken these things to YOU that, when the hour for them arrives, YOU may remember I told them to YOU.
“These things, however, I did not tell YOU at first, because I was with YOU.

[[v43-16-5]]

^<<v43-16-5,5>>^ But now I am going to him that sent me, and yet not one of YOU asks me, ‘Where are you going?’

[[v43-16-6]]

^<<v43-16-6,6>>^ But because I have spoken these things to YOU grief has filled YOUR hearts.

[[v43-16-7]]

^<<v43-16-7,7>>^ Nevertheless, I am telling YOU the truth, It is for YOUR benefit I am going away. For if I do not go away, the helper^&#42;1^ will by no means come to YOU; but if I do go my way, I will send him to YOU.

[NOTE]
====
. Or, “the paraclete (comforter).” Gr., ho pa·raʹkle·tos, masc.
====

[[v43-16-8]]

^<<v43-16-8,8>>^ And when that one arrives he will give the world convincing evidence^&#42;1^ concerning sin and concerning righteousness and concerning judgment:

[NOTE]
====
. “Will give . . . convincing evidence.” Or, “will reprove.” Gr., e·legʹxei.
====

[[v43-16-9]]

^<<v43-16-9,9>>^ in the first place, concerning sin, because they are not exercising faith in me;

[[v43-16-10]]

^<<v43-16-10,10>>^ then concerning righteousness, because I am going to the Father and YOU will behold me no longer;

[[v43-16-11]]

^<<v43-16-11,11>>^ then concerning judgment, because the ruler of this world has been judged.

[[v43-16-12]]

^<<v43-16-12,12>>^ “I have many things yet to say to YOU, but YOU are not able to bear them at present.

[[v43-16-13]]

^<<v43-16-13,13>>^ However, when that one^&#42;1^ arrives, the spirit of the truth, he will guide YOU into all the truth, for he will not speak of his own impulse, but what things he hears he will speak, and he will declare to YOU the things coming.

[NOTE]
====
. “That one,” masc., referring to “the helper,” masc., in vs 7.
====

[[v43-16-14]]

^<<v43-16-14,14>>^ That one will glorify me, because he will receive from what is mine and will declare it to YOU.

[[v43-16-15]]

^<<v43-16-15,15>>^ All the things that the Father has are mine. That is why I said he receives from what is mine and declares &#91;it&#93; to YOU.

[[v43-16-16]]

^<<v43-16-16,16>>^ In a little while YOU will behold me no longer, and, again, in a little while YOU will see me.”

[[v43-16-17]]

^<<v43-16-17,17>>^ Therefore some of his disciples said to one another: “What does this mean that he says to us, ‘In a little while YOU will not behold me, and, again, in a little while YOU will see me,’ and, ‘because I am going to the Father’?”

[[v43-16-18]]

^<<v43-16-18,18>>^ Hence they were saying: “What does this mean that he says, ‘a little while’? We do not know what he is talking about.”^&#42;1^

[NOTE]
====
. “What he is talking about.” B omits.
====

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus knew they were wanting to question him, so he said to them: “Are YOU inquiring among yourselves over this, because I said, In a little while YOU will not behold me, and, again, in a little while YOU will see me?

[[v43-16-20]]

^<<v43-16-20,20>>^ Most truly I say to YOU, YOU will weep and wail, but the world will rejoice; YOU will be grieved, but YOUR grief will be turned into joy.

[[v43-16-21]]

^<<v43-16-21,21>>^ A woman, when she is giving birth, has grief, because her hour has arrived; but when she has brought forth the young child, she remembers the tribulation no more because of the joy that a man has been born into the world.

[[v43-16-22]]

^<<v43-16-22,22>>^ YOU also, therefore, are now, indeed, having grief; but I shall see YOU again and YOUR hearts will rejoice, and YOUR joy no one will take from YOU.

[[v43-16-23]]

^<<v43-16-23,23>>^ And in that day YOU will ask me no question at all. Most truly I say to YOU, If YOU ask the Father for anything he will give it to YOU in my name.

[[v43-16-24]]

^<<v43-16-24,24>>^ Until this present time YOU have not asked a single thing in my name. Ask and YOU will receive, that YOUR joy may be made full.

[[v43-16-25]]

^<<v43-16-25,25>>^ “I have spoken these things to YOU in comparisons. The hour is coming when I will speak to YOU no more in comparisons, but I will report to YOU with plainness concerning the Father.

[[v43-16-26]]

^<<v43-16-26,26>>^ In that day YOU will ask in my name, and I do not say to YOU that I shall make request of the Father concerning YOU.

[[v43-16-27]]

^<<v43-16-27,27>>^ For the Father himself has affection for YOU, because YOU have had affection for me and have believed that I came out as the Father’s representative.

[[v43-16-28]]

^<<v43-16-28,28>>^ I came out from the Father and have come into the world. Further, I am leaving the world and am going my way to the Father.”

[[v43-16-29]]

^<<v43-16-29,29>>^ His disciples said: “See! Now you are speaking with plainness, and are uttering no comparison.

[[v43-16-30]]

^<<v43-16-30,30>>^ Now we know that you know all things and you do not need to have anyone question you. By this we believe that you came out from God.”

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus answered them: “Do YOU believe at present?

[[v43-16-32]]

^<<v43-16-32,32>>^ Look! The hour is coming, indeed, it has come, when YOU will be scattered each one to his own house and YOU will leave me alone; and yet I am not alone, because the Father is with me.

[[v43-16-33]]

^<<v43-16-33,33>>^ I have said these things to YOU that by means of me^&#42;1^ YOU may have peace. In the world YOU are having tribulation, but take courage! I have conquered the world.”

[NOTE]
====
. Or, “in union with me.” Gr., en e·moiʹ. See 6:56 ftn.
====

'''

xref:043-john/043-john-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-john/043-john-017.adoc#v43-17-0[Próximo Capítulo &#62;]