include::./index.adoc[]

[[v43-11-0]]
=== According to John, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-11-1]]

^<<v43-11-1,1>>^ Now there was a certain man sick, Lazʹa·rus^&#42;1^ of Bethʹa·ny, of the village of Mary and of Martha her sister.

[NOTE]
====
. “Lazarus,” אABJ17; J7-14,​16,​18,​19,​22, “Eleazar,” meaning “God Has Helped.”
====

[[v43-11-2]]

^<<v43-11-2,2>>^ It was, in fact, the Mary that greased the Lord^&#42;1^ with perfumed oil and wiped his feet dry with her hair, whose brother Lazʹa·rus was sick.

[NOTE]
====
. Or, “Master.”
====

[[v43-11-3]]

^<<v43-11-3,3>>^ Therefore his sisters dispatched word to him, saying: “Lord, see! the one for whom you have affection is sick.”

[[v43-11-4]]

^<<v43-11-4,4>>^ But when Jesus heard it he said: “This sickness is not with death as its object, but is for the glory of God, in order that the Son of God may be glorified through it.”

[[v43-11-5]]

^<<v43-11-5,5>>^ Now Jesus loved Martha and her sister and Lazʹa·rus.

[[v43-11-6]]

^<<v43-11-6,6>>^ However, when he heard that he was sick, then he actually remained two days in the place where he was.

[[v43-11-7]]

^<<v43-11-7,7>>^ Then after this he said to the disciples: “Let us go into Ju·deʹa again.”

[[v43-11-8]]

^<<v43-11-8,8>>^ The disciples said to him: “Rabbi, just lately the Ju·deʹans^&#42;1^ were seeking to stone you, and are you going there again?”

[NOTE]
====
. Or, “Jews.” Gr., I·ou·daiʹoi, as in 10:31, 33.
====

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus answered: “There are twelve hours of daylight, are there not? If anyone walks in daylight he does not bump against anything, because he sees the light of this world.

[[v43-11-10]]

^<<v43-11-10,10>>^ But if anyone walks in the night, he bumps against something, because the light is not in him.”

[[v43-11-11]]

^<<v43-11-11,11>>^ He said these things, and after this he said to them: “Lazʹa·rus our friend has gone to rest, but I am journeying there to awaken him from sleep.”

[[v43-11-12]]

^<<v43-11-12,12>>^ Therefore the disciples said to him: “Lord, if he has gone to rest, he will get well.”^&#42;1^

[NOTE]
====
. Or, “he will be saved.”
====

[[v43-11-13]]

^<<v43-11-13,13>>^ Jesus had spoken, however, about his death. But they imagined he was speaking about taking rest in sleep.

[[v43-11-14]]

^<<v43-11-14,14>>^ At that time, therefore, Jesus said to them outspokenly: “Lazʹa·rus has died,

[[v43-11-15]]

^<<v43-11-15,15>>^ and I rejoice on YOUR account that I was not there, in order for YOU to believe. But let us go to him.”

[[v43-11-16]]

^<<v43-11-16,16>>^ Therefore Thomas, who was called The Twin,^&#42;1^ said to his fellow disciples: “Let us also go, that we may die with him.”

[NOTE]
====
. Or, “Didymous.” Gr., Diʹdy·mos; Lat., Diʹdy·mus.
====

[[v43-11-17]]

^<<v43-11-17,17>>^ Consequently when Jesus arrived, he found he had already been four days in the memorial tomb.

[[v43-11-18]]

^<<v43-11-18,18>>^ Now Bethʹa·ny was near Jerusalem at a distance of about two miles.^&#42;1^

[NOTE]
====
. Lit., “about fifteen stadia away.” About 2.8 km (1.7 mi). A stadium equaled one eighth of a Roman mile, 185 m (606.75 English ft).
====

[[v43-11-19]]

^<<v43-11-19,19>>^ Accordingly many of the Jews had come to Martha and Mary in order to console them concerning their brother.

[[v43-11-20]]

^<<v43-11-20,20>>^ Therefore Martha, when she heard that Jesus was coming, met him; but Mary kept sitting at home.

[[v43-11-21]]

^<<v43-11-21,21>>^ Martha therefore said to Jesus: “Lord,^&#42;1^ if you had been here my brother would not have died.

[NOTE]
====
. Or, “Master.”
====

[[v43-11-22]]

^<<v43-11-22,22>>^ And yet at present I know that as many things as you ask God for, God will give you.”

[[v43-11-23]]

^<<v43-11-23,23>>^ Jesus said to her: “Your brother will rise.”

[[v43-11-24]]

^<<v43-11-24,24>>^ Martha said to him: “I know he will rise in the resurrection on the last day.”

[[v43-11-25]]

^<<v43-11-25,25>>^ Jesus said to her: “I am the resurrection and the life.^&#42;1^ He that exercises faith in me, even though he dies, will come to life;

[NOTE]
====
. “I am the resurrection and the life.” Gr., E·goʹ ei·mi he a·naʹsta·sis kai he zo·eʹ; Lat., Eʹgo sum re·sur·recʹti·o et viʹta; J22(Heb.), ʼAniʹ hat·techi·yahʹ weha·chai·yimʹ.
====

[[v43-11-26]]

^<<v43-11-26,26>>^ and everyone that is living and exercises faith in me will never die at all. Do you believe this?”

[[v43-11-27]]

^<<v43-11-27,27>>^ She said to him: “Yes, Lord; I have believed that you are the Christ the Son of God, the One coming into the world.”

[[v43-11-28]]

^<<v43-11-28,28>>^ And when she had said this, she went off and called Mary her sister, saying secretly: “The Teacher is present and is calling you.”

[[v43-11-29]]

^<<v43-11-29,29>>^ The latter, when she heard this, got up quickly and was on her way to him.

[[v43-11-30]]

^<<v43-11-30,30>>^ Jesus had not yet, in fact, come into the village, but he was still in the place where Martha met him.

[[v43-11-31]]

^<<v43-11-31,31>>^ Therefore the Jews that were with her in the house and that were consoling her, on seeing Mary rise quickly and go out, followed her, supposing that she was going to the memorial tomb to weep there.

[[v43-11-32]]

^<<v43-11-32,32>>^ And so Mary, when she arrived where Jesus was and caught sight of him, fell at his feet, saying to him: “Lord, if you had been here, my brother would not have died.”

[[v43-11-33]]

^<<v43-11-33,33>>^ Jesus, therefore, when he saw her weeping and the Jews that came with her weeping, groaned in the spirit and became troubled;

[[v43-11-34]]

^<<v43-11-34,34>>^ and he said: “Where have YOU laid him?” They said to him: “Lord, come and see.”

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus gave way to tears.

[[v43-11-36]]

^<<v43-11-36,36>>^ Therefore the Jews began to say: “See, what affection he used to have for him!”

[[v43-11-37]]

^<<v43-11-37,37>>^ But some of them said: “Was not this &#91;man&#93; that opened the eyes of the blind man able to prevent this one from dying?”

[[v43-11-38]]

^<<v43-11-38,38>>^ Hence Jesus, after groaning again within himself, came to the memorial tomb. It was, in fact, a cave, and a stone was lying against it.

[[v43-11-39]]

^<<v43-11-39,39>>^ Jesus said: “TAKE the stone away.” Martha, the sister of the deceased, said to him: “Lord, by now he must smell, for it is four days.”

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus said to her: “Did I not tell you that if you would believe you would see the glory of God?”

[[v43-11-41]]

^<<v43-11-41,41>>^ Therefore they took the stone away. Now Jesus raised his eyes heavenward and said: “Father, I thank you that you have heard me.

[[v43-11-42]]

^<<v43-11-42,42>>^ True, I knew that you always hear me; but on account of the crowd standing around I spoke, in order that they might believe that you sent me forth.”

[[v43-11-43]]

^<<v43-11-43,43>>^ And when he had said these things, he cried out with a loud voice: “Lazʹa·rus,^&#42;1^ come on out!”

[NOTE]
====
. See vs 1 ftn.
====

[[v43-11-44]]

^<<v43-11-44,44>>^ The &#91;man&#93; that had been dead came out with his feet and hands bound with wrappings, and his countenance was bound about with a cloth. Jesus said to them: “Loose him and let him go.”

[[v43-11-45]]

^<<v43-11-45,45>>^ Therefore many of the Jews that had come to Mary and that beheld what he did put faith in him;

[[v43-11-46]]

^<<v43-11-46,46>>^ but some of them went off to the Pharisees and told them the things Jesus did.

[[v43-11-47]]

^<<v43-11-47,47>>^ Consequently the chief priests and the Pharisees gathered the Sanʹhe·drin together and began to say: “What are we to do, because this man performs many signs?

[[v43-11-48]]

^<<v43-11-48,48>>^ If we let him alone this way, they will all put faith in him, and the Romans will come and take away both our place^&#42;1^ and our nation.”

[NOTE]
====
. That is, the temple.
====

[[v43-11-49]]

^<<v43-11-49,49>>^ But a certain one of them, Caʹia·phas, who was high priest that year, said to them: “YOU do not know anything at all,

[[v43-11-50]]

^<<v43-11-50,50>>^ and YOU do not reason out that it is to YOUR benefit for one man to die in behalf of the people and not for the whole nation to be destroyed.”

[[v43-11-51]]

^<<v43-11-51,51>>^ This, though, he did not say of his own originality; but because he was high priest that year, he prophesied that Jesus was destined to die for the nation,

[[v43-11-52]]

^<<v43-11-52,52>>^ and not for the nation only, but in order that the children of God who are scattered about he might also gather together in one.

[[v43-11-53]]

^<<v43-11-53,53>>^ Therefore from that day on they took counsel to kill him.

[[v43-11-54]]

^<<v43-11-54,54>>^ Hence Jesus no longer walked about publicly among the Jews, but he departed from there to the country near the wilderness, into a city called Eʹphra·im, and there he remained with the disciples.

[[v43-11-55]]

^<<v43-11-55,55>>^ Now the passover of the Jews was near, and many people went up out of the country to Jerusalem before the passover in order to cleanse themselves ceremonially.

[[v43-11-56]]

^<<v43-11-56,56>>^ Therefore they went looking for Jesus and they would say to one another as they stood around in the temple: “What is YOUR opinion? That he will not come to the festival at all?”

[[v43-11-57]]

^<<v43-11-57,57>>^ As it was, the chief priests and the Pharisees had given orders that if anyone got to know where he was, he should disclose &#91;it&#93;, in order that they might seize him.

'''

xref:043-john/043-john-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-john/043-john-012.adoc#v43-12-0[Próximo Capítulo &#62;]