include::./index.adoc[]

[[v43-17-0]]
=== According to John, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-17-1]]

^<<v43-17-1,1>>^ Jesus spoke these things, and, raising his eyes to heaven, he said: “Father, the hour has come; glorify your son, that your son may glorify you,

[[v43-17-2]]

^<<v43-17-2,2>>^ according as you have given him authority over all flesh, that, as regards the whole &#91;number&#93; whom you have given him, he may give them everlasting life.

[[v43-17-3]]

^<<v43-17-3,3>>^ This means everlasting life, their taking in knowledge of you,^&#42;1^ the only true God, and of the one whom you sent forth, Jesus Christ.

[NOTE]
====
. Or, “their knowing you.” Gr., hiʹna gi·noʹsko·si se.
====

[[v43-17-4]]

^<<v43-17-4,4>>^ I have glorified you on the earth, having finished the work you have given me to do.

[[v43-17-5]]

^<<v43-17-5,5>>^ So now you, Father, glorify me alongside yourself with the glory that I had alongside you before the world was.

[[v43-17-6]]

^<<v43-17-6,6>>^ “I have made your name manifest to the men you gave me out of the world. They were yours, and you gave them to me, and they have observed your word.

[[v43-17-7]]

^<<v43-17-7,7>>^ They have now come to know that all the things you gave me are from you;

[[v43-17-8]]

^<<v43-17-8,8>>^ because the sayings that you gave me I have given to them, and they have received them and have certainly come to know that I came out as your representative, and they have believed that you sent me forth.

[[v43-17-9]]

^<<v43-17-9,9>>^ I make request concerning them; I make request, not concerning the world, but concerning those you have given me; because they are yours,

[[v43-17-10]]

^<<v43-17-10,10>>^ and all my things are yours and yours are mine, and I have been glorified among them.

[[v43-17-11]]

^<<v43-17-11,11>>^ “Also, I am no longer in the world, but they are in the world and I am coming to you. Holy Father, watch over them on account of your own name which you have given me, in order that they may be one just as we are.

[[v43-17-12]]

^<<v43-17-12,12>>^ When I was with them I used to watch over them on account of your own name which you have given me; and I have kept them, and not one of them is destroyed except the son of destruction, in order that the scripture might be fulfilled.

[[v43-17-13]]

^<<v43-17-13,13>>^ But now I am coming to you, and I am speaking these things in the world in order that they may have my joy in themselves to the full.

[[v43-17-14]]

^<<v43-17-14,14>>^ I have given your word to them, but the world has hated them, because they are no part of the world, just as I am no part of the world.

[[v43-17-15]]

^<<v43-17-15,15>>^ “I request you, not to take them out of the world, but to watch over them because of the wicked one.

[[v43-17-16]]

^<<v43-17-16,16>>^ They are no part of the world, just as I am no part of the world.

[[v43-17-17]]

^<<v43-17-17,17>>^ Sanctify them by means of the truth; your word is truth.

[[v43-17-18]]

^<<v43-17-18,18>>^ Just as you sent me forth into the world, I also sent them forth into the world.

[[v43-17-19]]

^<<v43-17-19,19>>^ And I am sanctifying myself^&#42;1^ in their behalf, that they also may be sanctified by means of truth.

[NOTE]
====
. Or, “And I am holding myself sacred (treating myself as holy).” Gr., kai . . . e·goʹ ha·gi·aʹzo e·mau·tonʹ; Lat., et . . . eʹgo sanc·tiʹfi·co me ipʹsum; J17(Heb.), wehith·qad·dash·tiʹ.
====

[[v43-17-20]]

^<<v43-17-20,20>>^ “I make request, not concerning these only, but also concerning those putting faith in me through their word;

[[v43-17-21]]

^<<v43-17-21,21>>^ in order that they may all be one,^&#42;1^ just as you, Father, are in union with me and I am in union with you, that they also may be in union with us, in order that the world may believe that you sent me forth.

[NOTE]
====
. Or, “at unity.” Lit., “one (thing).” Gr., hen, neuter, to show oneness in cooperation. See 10:30 ftn.
====

[[v43-17-22]]

^<<v43-17-22,22>>^ Also, I have given them the glory that you have given me, in order that they may be one just as we are one.

[[v43-17-23]]

^<<v43-17-23,23>>^ I in union with them and you in union with me, in order that they may be perfected into one, that the world may have the knowledge that you sent me forth and that you loved them just as you loved me.

[[v43-17-24]]

^<<v43-17-24,24>>^ Father, as to what you have given me, I wish that, where I am, they also may be with me, in order to behold my glory that you have given me, because you loved me before the founding^&#42;1^ of the world.

[NOTE]
====
. Lit., “before a throwing down [of seed].” Gr., pro ka·ta·bo·lesʹ.
====

[[v43-17-25]]

^<<v43-17-25,25>>^ Righteous Father, the world has, indeed, not come to know you; but I have come to know you, and these have come to know that you sent me forth.

[[v43-17-26]]

^<<v43-17-26,26>>^ And I have made your name known to them and will make it known, in order that the love with which you loved me may be in them and I in union with them.”

'''

xref:043-john/043-john-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-john/043-john-018.adoc#v43-18-0[Próximo Capítulo &#62;]