include::./index.adoc[]

[[v43-13-0]]
=== According to John, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-13-1]]

^<<v43-13-1,1>>^ Now, because he knew before the festival of the passover that his hour had come for him to move out of this world to the Father, Jesus, having loved his own that were in the world, loved them to the end.

[[v43-13-2]]

^<<v43-13-2,2>>^ So, while the evening meal was going on,^&#42;1^ the Devil having already put it into the heart of Judas Is·carʹi·ot, the son of Simon, to betray him,

[NOTE]
====
. Or, “was being prepared.”
====

[[v43-13-3]]

^<<v43-13-3,3>>^ he, knowing that the Father had given all things into &#91;his&#93; hands and that he came forth from God and was going to God,

[[v43-13-4]]

^<<v43-13-4,4>>^ got up from the evening meal and laid aside his outer garments. And, taking a towel, he girded himself.

[[v43-13-5]]

^<<v43-13-5,5>>^ After that he put water into a basin and started to wash the feet of the disciples and to dry them off with the towel with which he was girded.

[[v43-13-6]]

^<<v43-13-6,6>>^ And so he came to Simon Peter. He said to him: “Lord,^&#42;1^ are you washing my feet?”

[NOTE]
====
. Or, “Master.”
====

[[v43-13-7]]

^<<v43-13-7,7>>^ In answer Jesus said to him: “What I am doing you do not understand at present, but you will understand after these things.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Peter said to him: “You will certainly never wash my feet.” Jesus answered him: “Unless I wash you, you have no part with me.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simon Peter said to him: “Lord, not my feet only, but also my hands and my head.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus said to him: “He that has bathed does not need to have more than his feet washed, but is wholly clean. And YOU men are clean, but not all.”

[[v43-13-11]]

^<<v43-13-11,11>>^ He knew, indeed, the man betraying him. This is why he said: “Not all of YOU are clean.”

[[v43-13-12]]

^<<v43-13-12,12>>^ When, now, he had washed their feet and had put his outer garments on and laid himself down at the table again, he said to them: “Do YOU know what I have done to YOU?

[[v43-13-13]]

^<<v43-13-13,13>>^ YOU address me, ‘Teacher,’ and, ‘Lord,’ and YOU speak rightly, for I am such.

[[v43-13-14]]

^<<v43-13-14,14>>^ Therefore, if I, although Lord and Teacher, washed YOUR feet, YOU also ought to wash the feet of one another.

[[v43-13-15]]

^<<v43-13-15,15>>^ For I set the pattern for YOU, that, just as I did to YOU, YOU should do also.

[[v43-13-16]]

^<<v43-13-16,16>>^ Most truly I say to YOU, A slave is not greater than his master, nor is one that is sent forth^&#42;1^ greater than the one that sent him.

[NOTE]
====
. “One that is sent forth.” Or, “an apostle (envoy).” Gr., a·poʹsto·los; Lat., a·poʹsto·lus.
====

[[v43-13-17]]

^<<v43-13-17,17>>^ If YOU know these things, happy YOU are if YOU do them.

[[v43-13-18]]

^<<v43-13-18,18>>^ I am not talking about all of YOU; I know the ones I have chosen. But it is in order that the Scripture might be fulfilled, ‘He that used to feed on my bread has lifted up his heel against me.’

[[v43-13-19]]

^<<v43-13-19,19>>^ From this moment on I am telling YOU before it occurs, in order that when it does occur YOU may believe that I am &#91;he&#93;.

[[v43-13-20]]

^<<v43-13-20,20>>^ Most truly I say to YOU, He that receives anyone I send receives me &#91;also&#93;. In turn he that receives me, receives &#91;also&#93; him that sent me.”

[[v43-13-21]]

^<<v43-13-21,21>>^ After saying these things, Jesus became troubled in spirit, and he bore witness and said: “Most truly I say to YOU, One of YOU will betray me.”

[[v43-13-22]]

^<<v43-13-22,22>>^ The disciples began to look at one another, being at a loss as to which one he was saying &#91;it&#93; about.

[[v43-13-23]]

^<<v43-13-23,23>>^ There was reclining in front of Jesus’ bosom one of his disciples, and Jesus loved^&#42;1^ him.

[NOTE]
====
. Or, “preferred.”
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Therefore Simon Peter nodded to this one and said to him: “Tell who it is about whom he is saying &#91;it&#93;.”

[[v43-13-25]]

^<<v43-13-25,25>>^ So the latter leaned back upon the breast of Jesus and said to him: “Lord, who is it?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Therefore Jesus answered: “It is that one to whom I shall give the morsel that I dip.” And so, having dipped the morsel, he took and gave it to Judas, the son of Simon Is·carʹi·ot.

[[v43-13-27]]

^<<v43-13-27,27>>^ And after the morsel then Satan entered into the latter. Jesus, therefore, said to him: “What you are doing get done more quickly.”

[[v43-13-28]]

^<<v43-13-28,28>>^ However, none of those reclining at the table knew for what purpose he said this to him.

[[v43-13-29]]

^<<v43-13-29,29>>^ Some, in fact, were imagining, since Judas was holding the money box, that Jesus was telling him: “Buy what things we need for the festival,” or that he should give something to the poor.

[[v43-13-30]]

^<<v43-13-30,30>>^ Therefore, after he received the morsel, he went out immediately. And it was night.

[[v43-13-31]]

^<<v43-13-31,31>>^ Hence when he had gone out, Jesus said: “Now the Son of man is glorified, and God is glorified in connection with him.^&#42;1^

[NOTE]
====
. Or, “by means of him.”
====

[[v43-13-32]]

^<<v43-13-32,32>>^ And God will himself glorify him, and he will glorify him immediately.

[[v43-13-33]]

^<<v43-13-33,33>>^ Little children, I am with YOU a little longer. YOU will look for me; and just as I said to the Jews, ‘Where I go YOU cannot come,’ I say also to YOU at present.

[[v43-13-34]]

^<<v43-13-34,34>>^ I am giving YOU a new commandment, that YOU love one another; just as I have loved YOU, that YOU also love one another.

[[v43-13-35]]

^<<v43-13-35,35>>^ By this all will know that YOU are my disciples, if YOU have love among yourselves.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simon Peter said to him: “Lord, where are you going?” Jesus answered: “Where I am going you cannot follow me now, but you will follow afterwards.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Peter said to him: “Lord, why is it I cannot follow you at present? I will surrender my soul in your behalf.”

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus answered: “Will you surrender your soul^&#42;1^ in my behalf? Most truly I say to you, A cock will by no means crow until you have disowned me three times.”

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; Lat., aʹni·mam; J17,​18,​22(Heb.), naph·shekhaʹ (from neʹphesh).
====

'''

xref:043-john/043-john-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-john/043-john-014.adoc#v43-14-0[Próximo Capítulo &#62;]