include::./index.adoc[]

[[v43-3-0]]
=== According to John, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-3-1]]

^<<v43-3-1,1>>^ Now there was a man of the Pharisees, Nic·o·deʹmus was his name, a ruler of the Jews.

[[v43-3-2]]

^<<v43-3-2,2>>^ This one came to him in the night and said to him: “Rabbi, we know that you as a teacher have come from God; for no one can perform these signs that you perform unless God is with him.”

[[v43-3-3]]

^<<v43-3-3,3>>^ In answer Jesus said to him: “Most truly I say to you, Unless anyone is born again,^&#42;1^ he cannot see the kingdom of God.”

[NOTE]
====
. “Is born again.” Lit., “should be generated from above.” Gr., gen·ne·theiʹ aʹno·then.
====

[[v43-3-4]]

^<<v43-3-4,4>>^ Nic·o·deʹmus said to him: “How can a man be born when he is old? He cannot enter into the womb of his mother a second time and be born, can he?”

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus answered: “Most truly I say to you, Unless anyone is born from water and spirit,^&#42;1^ he cannot enter into the kingdom of God.

[NOTE]
====
. Or, “active force.” Gr., pneuʹma·tos; Lat., Spiʹri·tu; J17,​22(Heb.), weha·ruʹach, “and the active force.” See Ge 1:2 ftn, “Force.”
====

[[v43-3-6]]

^<<v43-3-6,6>>^ What has been born from the flesh is flesh, and what has been born from the spirit is spirit.

[[v43-3-7]]

^<<v43-3-7,7>>^ Do not marvel because I told you, YOU people must be born again.

[[v43-3-8]]

^<<v43-3-8,8>>^ The wind^&#42;1^ blows where it wants to, and you hear the sound of it, but you do not know where it comes from and where it is going. So is everyone that has been born from the spirit.”

[NOTE]
====
. “Wind.” Gr., pneuʹma.
====

[[v43-3-9]]

^<<v43-3-9,9>>^ In answer Nic·o·deʹmus said to him: “How can these things come about?”

[[v43-3-10]]

^<<v43-3-10,10>>^ In answer Jesus said to him: “Are you a teacher of Israel and yet do not know these things?

[[v43-3-11]]

^<<v43-3-11,11>>^ Most truly I say to you, What we know we speak and what we have seen we bear witness of, but YOU people do not receive the witness we give.

[[v43-3-12]]

^<<v43-3-12,12>>^ If I have told YOU earthly things and yet YOU do not believe, how will YOU believe if I tell YOU heavenly things?^&#42;1^

[NOTE]
====
. “Heavenly things.” Gr., e·pou·raʹni·a; Lat., cae·leʹsti·a, “celestial things.”
====

[[v43-3-13]]

^<<v43-3-13,13>>^ Moreover, no man has ascended into heaven but he that descended from heaven, the Son of man.

[[v43-3-14]]

^<<v43-3-14,14>>^ And just as Moses lifted up the serpent in the wilderness, so the Son of man must be lifted up,

[[v43-3-15]]

^<<v43-3-15,15>>^ that everyone believing in him may have everlasting life.

[[v43-3-16]]

^<<v43-3-16,16>>^ “For God loved the world^&#42;1^ so much that he gave his only-begotten Son, in order that everyone exercising faith in him might not be destroyed but have everlasting life.

[NOTE]
====
. “The world.” Gr., ton koʹsmon; Lat., munʹdum; J17,​18,​22(Heb.), ha·ʽoh·lamʹ.
====

[[v43-3-17]]

^<<v43-3-17,17>>^ For God sent forth his Son into the world, not for him to judge the world, but for the world to be saved through him.

[[v43-3-18]]

^<<v43-3-18,18>>^ He that exercises faith in him is not to be judged. He that does not exercise faith has been judged already, because he has not exercised faith in the name of the only-begotten Son of God.

[[v43-3-19]]

^<<v43-3-19,19>>^ Now this is the basis for judgment, that the light has come into the world but men have loved the darkness rather than the light, for their works were wicked.

[[v43-3-20]]

^<<v43-3-20,20>>^ For he that practices vile things hates the light and does not come to the light, in order that his works may not be reproved.

[[v43-3-21]]

^<<v43-3-21,21>>^ But he that does what is true comes to the light, in order that his works may be made manifest as having been worked in harmony with God.”

[[v43-3-22]]

^<<v43-3-22,22>>^ After these things Jesus and his disciples went into Ju·deʹan country, and there he spent some time with them and did baptizing.

[[v43-3-23]]

^<<v43-3-23,23>>^ But John also was baptizing in Aeʹnon near Saʹlim, because there was a great quantity of water there, and people kept coming and being baptized;

[[v43-3-24]]

^<<v43-3-24,24>>^ for John had not yet been thrown into prison.

[[v43-3-25]]

^<<v43-3-25,25>>^ Therefore a dispute arose on the part of the disciples of John with a Jew concerning purification.

[[v43-3-26]]

^<<v43-3-26,26>>^ So they came to John and said to him: “Rabbi, the man that was with you across the Jordan, to whom you have borne witness, see, this one is baptizing and all are going to him.”

[[v43-3-27]]

^<<v43-3-27,27>>^ In answer John said: “A man cannot receive a single thing unless it has been given him from heaven.

[[v43-3-28]]

^<<v43-3-28,28>>^ YOU yourselves bear me witness that I said, I am not the Christ, but, I have been sent forth in advance of that one.

[[v43-3-29]]

^<<v43-3-29,29>>^ He that has the bride is the bridegroom. However, the friend of the bridegroom, when he stands and hears him, has a great deal of joy on account of the voice of the bridegroom. Therefore this joy of mine has been made full.

[[v43-3-30]]

^<<v43-3-30,30>>^ That one must go on increasing, but I must go on decreasing.”

[[v43-3-31]]

^<<v43-3-31,31>>^ He that comes from above is over all others.^&#42;1^ He that is from the earth is from the earth and speaks of things of the earth. He that comes from heaven is over all others.

[NOTE]
====
. Or, “all things.”
====

[[v43-3-32]]

^<<v43-3-32,32>>^ What he has seen and heard, of this he bears witness, but no man is accepting his witness.

[[v43-3-33]]

^<<v43-3-33,33>>^ He that has accepted his witness has put his seal to it that God is true.

[[v43-3-34]]

^<<v43-3-34,34>>^ For the one whom God sent forth speaks the sayings of God, for he does not give the spirit by measure.^&#42;1^

[NOTE]
====
. Or, “sparingly.”
====

[[v43-3-35]]

^<<v43-3-35,35>>^ The Father loves the Son and has given all things into his hand.

[[v43-3-36]]

^<<v43-3-36,36>>^ He that exercises faith in the Son has everlasting life; he that disobeys the Son will not see life, but the wrath of God remains upon him.

'''

xref:043-john/043-john-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-john/043-john-004.adoc#v43-4-0[Próximo Capítulo &#62;]