include::./index.adoc[]

[[v43-7-0]]
=== According to John, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-7-1]]

^<<v43-7-1,1>>^ Now after these things Jesus continued walking about in Galʹi·lee, for he did not want to walk about in Ju·deʹa, because the Jews were seeking to kill him.

[[v43-7-2]]

^<<v43-7-2,2>>^ However, the festival of the Jews, the festival of tabernacles, was near.

[[v43-7-3]]

^<<v43-7-3,3>>^ Therefore his brothers said to him: “Pass on over from here and go into Ju·deʹa, in order that your disciples also may behold the works you do.

[[v43-7-4]]

^<<v43-7-4,4>>^ For nobody does anything in secret while himself seeking to be known publicly. If you do these things, manifest yourself to the world.”

[[v43-7-5]]

^<<v43-7-5,5>>^ His brothers were, in fact, not exercising faith in him.

[[v43-7-6]]

^<<v43-7-6,6>>^ Therefore Jesus said to them: “My due time is not yet present, but YOUR due time is always at hand.

[[v43-7-7]]

^<<v43-7-7,7>>^ The world has no reason to hate YOU, but it hates me, because I bear witness concerning it that its works are wicked.

[[v43-7-8]]

^<<v43-7-8,8>>^ YOU go up to the festival; I am not yet going up to this festival, because my due time has not yet fully come.”

[[v43-7-9]]

^<<v43-7-9,9>>^ So after he told them these things, he remained in Galʹi·lee.

[[v43-7-10]]

^<<v43-7-10,10>>^ But when his brothers had gone up to the festival, then he also went up himself, not openly but as in secret.

[[v43-7-11]]

^<<v43-7-11,11>>^ Therefore the Jews began looking for him at the festival and saying: “Where is that &#91;man&#93;?”

[[v43-7-12]]

^<<v43-7-12,12>>^ And there was a lot of subdued talk about him among the crowds. Some would say: “He is a good man.” Others would say: “He is not, but he misleads the crowd.”

[[v43-7-13]]

^<<v43-7-13,13>>^ No one, of course, would speak about him publicly because of the fear of the Jews.

[[v43-7-14]]

^<<v43-7-14,14>>^ When by now the festival was half over, Jesus went up into the temple and began teaching.

[[v43-7-15]]

^<<v43-7-15,15>>^ Therefore the Jews fell to wondering, saying: “How does this man have a knowledge of letters, when he has not studied^&#42;1^ at the schools?”

[NOTE]
====
. Or, “when he has not learned.”
====

[[v43-7-16]]

^<<v43-7-16,16>>^ Jesus, in turn, answered them and said: “What I teach is not mine, but belongs to him that sent me.

[[v43-7-17]]

^<<v43-7-17,17>>^ If anyone desires to do His will, he will know concerning the teaching whether it is from God or I speak of my own originality.^&#42;1^

[NOTE]
====
. Lit., “from myself.”
====

[[v43-7-18]]

^<<v43-7-18,18>>^ He that speaks of his own originality is seeking his own glory; but he that seeks the glory of him that sent him, this one is true, and there is no unrighteousness in him.

[[v43-7-19]]

^<<v43-7-19,19>>^ Moses gave YOU the Law, did he not? But not one of YOU obeys the Law. Why are YOU seeking to kill me?”

[[v43-7-20]]

^<<v43-7-20,20>>^ The crowd answered: “You have a demon.^&#42;1^ Who is seeking to kill you?”

[NOTE]
====
. Or, “You are demonized.”
====

[[v43-7-21]]

^<<v43-7-21,21>>^ In answer Jesus said to them: “One deed I performed, and YOU are all wondering.

[[v43-7-22]]

^<<v43-7-22,22>>^ For this reason Moses has given YOU the circumcision—not that it is from Moses, but that it is from the forefathers—and YOU circumcise a man on a sabbath.

[[v43-7-23]]

^<<v43-7-23,23>>^ If a man receives circumcision on a sabbath in order that the law of Moses may not be broken, are YOU violently angry at me because I made a man completely sound in health on a sabbath?

[[v43-7-24]]

^<<v43-7-24,24>>^ Stop judging from the outward appearance, but judge with righteous judgment.”

[[v43-7-25]]

^<<v43-7-25,25>>^ Therefore some of the inhabitants of Jerusalem began to say: “This is the man they are seeking to kill, is it not?

[[v43-7-26]]

^<<v43-7-26,26>>^ And yet, see! he is speaking in public, and they say nothing to him. The rulers have not come to know for a certainty that this is the Christ, have they?

[[v43-7-27]]

^<<v43-7-27,27>>^ On the contrary, we know where this man is from; yet when the Christ comes, no one is to know where he is from.”

[[v43-7-28]]

^<<v43-7-28,28>>^ Therefore Jesus cried out as he was teaching in the temple and said: “YOU both know me and know where I am from. Also, I have not come of my own initiative, but he that sent me is real, and YOU do not know him.

[[v43-7-29]]

^<<v43-7-29,29>>^ I know him, because I am a representative from him, and that One sent me forth.”

[[v43-7-30]]

^<<v43-7-30,30>>^ Hence they began seeking to get hold of him, but no one laid a hand upon him, because his hour had not yet come.

[[v43-7-31]]

^<<v43-7-31,31>>^ Still, many of the crowd put faith in him; and they commenced saying: “When the Christ arrives, he will not perform more signs than this man has performed, will he?”

[[v43-7-32]]

^<<v43-7-32,32>>^ The Pharisees heard the crowd murmuring these things about him, and the chief priests and the Pharisees dispatched officers to get hold of him.

[[v43-7-33]]

^<<v43-7-33,33>>^ Therefore Jesus said: “I continue a little while longer with YOU before I go to him that sent me.

[[v43-7-34]]

^<<v43-7-34,34>>^ YOU will look for me, but YOU will not find me, and where I am YOU cannot come.”

[[v43-7-35]]

^<<v43-7-35,35>>^ Therefore the Jews said among themselves: “Where does this &#91;man&#93; intend going, so that we shall not find him? He does not intend to go to the &#91;Jews&#93; dispersed^&#42;1^ among the Greeks and teach the Greeks, does he?

[NOTE]
====
. “[Jews] dispersed.” Lit., “dispersion.” Gr., di·a·spo·ranʹ.
====

[[v43-7-36]]

^<<v43-7-36,36>>^ What does this saying mean that he said, ‘YOU will look for me, but YOU will not find me, and where I am YOU cannot come’?”

[[v43-7-37]]

^<<v43-7-37,37>>^ Now on the last day, the great day of the festival, Jesus was standing up and he cried out, saying: “If anyone is thirsty, let him come to me and drink.

[[v43-7-38]]

^<<v43-7-38,38>>^ He that puts faith in me, just as the Scripture has said, ‘Out from his inmost part streams of living water will flow.’”

[[v43-7-39]]

^<<v43-7-39,39>>^ However, he said this concerning the spirit which those who put faith in him were about to receive; for as yet there was no spirit, because Jesus had not yet been glorified.

[[v43-7-40]]

^<<v43-7-40,40>>^ Therefore some of the crowd that heard these words began saying: “This is for a certainty The Prophet.”

[[v43-7-41]]

^<<v43-7-41,41>>^ Others were saying: “This is the Christ.” But some were saying: “The Christ is not actually coming out of Galʹi·lee, is he?

[[v43-7-42]]

^<<v43-7-42,42>>^ Has not the Scripture said that the Christ is coming from the offspring of David, and from Bethʹle·hem the village where David used to be?”

[[v43-7-43]]

^<<v43-7-43,43>>^ Therefore a division over him developed among the crowd.

[[v43-7-44]]

^<<v43-7-44,44>>^ Some of them, though, were wanting to get hold of him, but no one did lay &#91;his&#93; hands upon him.

[[v43-7-45]]

^<<v43-7-45,45>>^ Therefore the officers went back to the chief priests and Pharisees, and the latter said to them: “Why is it YOU did not bring him in?”

[[v43-7-46]]

^<<v43-7-46,46>>^ The officers replied: “Never has &#91;another&#93; man spoken like this.”

[[v43-7-47]]

^<<v43-7-47,47>>^ In turn the Pharisees answered: “YOU have not been misled also, have YOU?

[[v43-7-48]]

^<<v43-7-48,48>>^ Not one of the rulers or of the Pharisees has put faith in him, has he?

[[v43-7-49]]

^<<v43-7-49,49>>^ But this crowd that does not know the Law are accursed people.”

[[v43-7-50]]

^<<v43-7-50,50>>^ Nic·o·deʹmus, who had come to him previously, and who was one of them, said to them:

[[v43-7-51]]

^<<v43-7-51,51>>^ “Our law does not judge a man unless first it has heard from him and come to know what he is doing, does it?”

[[v43-7-52]]

^<<v43-7-52,52>>^ In answer they said to him: “You are not also out of Galʹi·lee, are you? Search and see that no prophet is to be raised up out of Galʹi·lee.”

_Manuscripts אBSys omit verses 53 to chapter 8, verse 11, which read (with some variations in the various Greek texts and versions) as follows:_

[[v43-7-53]]

^<<v43-7-53,53>>^ So they went each one to his home.

'''

xref:043-john/043-john-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-john/043-john-008.adoc#v43-8-0[Próximo Capítulo &#62;]