include::./index.adoc[]

[[v43-9-0]]
=== According to John, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-9-1]]

^<<v43-9-1,1>>^ Now as he was passing along he saw a man blind from birth.

[[v43-9-2]]

^<<v43-9-2,2>>^ And his disciples asked him: “Rabbi, who sinned, this man or his parents, so that he was born blind?”

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus answered: “Neither this man sinned nor his parents, but it was in order that the works of God might be made manifest in his case.

[[v43-9-4]]

^<<v43-9-4,4>>^ We must work the works of him that sent me while it is day; the night is coming when no man can work.

[[v43-9-5]]

^<<v43-9-5,5>>^ As long as I am in the world, I am the world’s light.”

[[v43-9-6]]

^<<v43-9-6,6>>^ After he said these things, he spit on the ground and made a clay with the saliva, and put his clay upon the &#91;man’s&#93; eyes

[[v43-9-7]]

^<<v43-9-7,7>>^ and said to him: “Go wash in the pool of Si·loʹam”^&#42;1^ (which is translated ‘Sent forth’). And so he went off and washed, and came back seeing.

[NOTE]
====
. “Siloam,” אAB; J7-14,​16-19,​22, “Shiloah.” See Isa 8:6 in LXX.
====

[[v43-9-8]]

^<<v43-9-8,8>>^ Therefore the neighbors and those who formerly used to see he was a beggar began to say: “This is the man that used to sit and beg, is it not?”

[[v43-9-9]]

^<<v43-9-9,9>>^ Some would say: “This is he.” Others would say: “Not at all, but he is like him.” The man would say: “I am &#91;he&#93;.”

[[v43-9-10]]

^<<v43-9-10,10>>^ Consequently they began to say to him: “How, then, were your eyes opened?”

[[v43-9-11]]

^<<v43-9-11,11>>^ He answered: “The man called Jesus made a clay and smeared &#91;it&#93; on my eyes and said to me, ‘Go to Si·loʹam and wash.’ I therefore went and washed and gained sight.”

[[v43-9-12]]

^<<v43-9-12,12>>^ At this they said to him: “Where is that &#91;man&#93;?” He said: “I do not know.”

[[v43-9-13]]

^<<v43-9-13,13>>^ They led the once-blind man himself to the Pharisees.

[[v43-9-14]]

^<<v43-9-14,14>>^ Incidentally it was Sabbath on the day that Jesus made the clay and opened his eyes.

[[v43-9-15]]

^<<v43-9-15,15>>^ This time, therefore, the Pharisees also took up asking him how he gained sight. He said to them: “He put a clay upon my eyes, and I washed and have sight.”

[[v43-9-16]]

^<<v43-9-16,16>>^ Therefore some of the Pharisees began to say: “This is not a man from God, because he does not observe the Sabbath.” Others began to say: “How can a man that is a sinner perform signs of that sort?” So there was a division among them.

[[v43-9-17]]

^<<v43-9-17,17>>^ Hence they said to the blind man again: “What do you say about him, seeing that he opened your eyes?” The &#91;man&#93; said: “He is a prophet.”

[[v43-9-18]]

^<<v43-9-18,18>>^ However, the Jews did not believe concerning him that he had been blind and had gained sight, until they called the parents of the man that gained sight.

[[v43-9-19]]

^<<v43-9-19,19>>^ And they asked them: “Is this YOUR son who YOU say was born blind? How, then, is it he sees at present?”

[[v43-9-20]]

^<<v43-9-20,20>>^ Then in answer his parents said: “We know that this is our son and that he was born blind.

[[v43-9-21]]

^<<v43-9-21,21>>^ But how it is he now sees we do not know, or who opened his eyes we do not know. ASK him. He is of age. He must speak for himself.”

[[v43-9-22]]

^<<v43-9-22,22>>^ His parents said these things because they were in fear of the Jews, for the Jews had already come to an agreement that, if anyone confessed him as Christ, he should get expelled from the synagogue.^&#42;1^

[NOTE]
====
. “Expelled from the synagogue.” Or, “unchurched.”
====

[[v43-9-23]]

^<<v43-9-23,23>>^ This is why his parents said: “He is of age. QUESTION him.”

[[v43-9-24]]

^<<v43-9-24,24>>^ Therefore a second time they called the man that had been blind and said to him: “Give glory to God; we know that this man is a sinner.”

[[v43-9-25]]

^<<v43-9-25,25>>^ In turn he answered: “Whether he is a sinner I do not know. One thing I do know, that, whereas I was blind, I see at present.”

[[v43-9-26]]

^<<v43-9-26,26>>^ Therefore they said to him: “What did he do to you? How did he open your eyes?”

[[v43-9-27]]

^<<v43-9-27,27>>^ He answered them: “I told YOU already, and yet YOU did not listen. Why do YOU want to hear it again? YOU do not want to become his disciples also, do YOU?”

[[v43-9-28]]

^<<v43-9-28,28>>^ At this they reviled him and said: “You are a disciple of that &#91;man&#93;, but we are disciples of Moses.

[[v43-9-29]]

^<<v43-9-29,29>>^ We know that God has spoken to Moses; but as for this &#91;man&#93;, we do not know where he is from.”

[[v43-9-30]]

^<<v43-9-30,30>>^ In answer the man said to them: “This certainly is a marvel, that YOU do not know where he is from, and yet he opened my eyes.

[[v43-9-31]]

^<<v43-9-31,31>>^ We know that God does not listen to sinners, but if anyone is God-fearing and does his will, he listens to this one.

[[v43-9-32]]

^<<v43-9-32,32>>^ From of old it has never been heard that anyone opened the eyes of one born blind.

[[v43-9-33]]

^<<v43-9-33,33>>^ If this &#91;man&#93; were not from God, he could do nothing at all.”

[[v43-9-34]]

^<<v43-9-34,34>>^ In answer they said to him: “You were altogether born in sins, and yet are you teaching us?” And they threw him out!

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus heard that they had thrown him out, and, on finding him, he said: “Are you putting faith in the Son of man?”

[[v43-9-36]]

^<<v43-9-36,36>>^ The &#91;man&#93; answered: “And who is he, sir, that I may put faith in him?”

[[v43-9-37]]

^<<v43-9-37,37>>^ Jesus said to him: “You have seen him and, besides, he that is speaking with you is that one.”

[[v43-9-38]]

^<<v43-9-38,38>>^ Then he said: “I do put faith &#91;in him&#93;, Lord.”^&#42;1^ And he did obeisance to him.

[NOTE]
====
. Or, “Sir; Master.”
====

[[v43-9-39]]

^<<v43-9-39,39>>^ And Jesus said: “For &#91;this&#93; judgment I came into this world: that those not seeing might see and those seeing might become blind.”

[[v43-9-40]]

^<<v43-9-40,40>>^ Those of the Pharisees who were with him heard these things, and they said to him: “We are not blind also, are we?”

[[v43-9-41]]

^<<v43-9-41,41>>^ Jesus said to them: “If YOU were blind, YOU would have no sin. But now YOU say, ‘We see.’ YOUR sin remains.”

'''

xref:043-john/043-john-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-john/043-john-010.adoc#v43-10-0[Próximo Capítulo &#62;]