include::./index.adoc[]

[[v43-10-0]]
=== According to John, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-10-1]]

^<<v43-10-1,1>>^ “Most truly I say to YOU, He that does not enter into the sheepfold through the door but climbs up some other place, that one is a thief and a plunderer.

[[v43-10-2]]

^<<v43-10-2,2>>^ But he that enters through the door is shepherd of the sheep.

[[v43-10-3]]

^<<v43-10-3,3>>^ The doorkeeper opens to this one, and the sheep listen to his voice, and he calls his own sheep by name and leads them out.

[[v43-10-4]]

^<<v43-10-4,4>>^ When he has got all his own out, he goes before them, and the sheep follow him, because they know his voice.

[[v43-10-5]]

^<<v43-10-5,5>>^ A stranger they will by no means follow but will flee from him, because they do not know the voice of strangers.”

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus spoke this comparison to them; but they did not know what the things meant that he was speaking to them.

[[v43-10-7]]

^<<v43-10-7,7>>^ Therefore Jesus said again: “Most truly I say to YOU, I am the door of the sheep.

[[v43-10-8]]

^<<v43-10-8,8>>^ All those that have come in place of me are thieves and plunderers; but the sheep have not listened to them.

[[v43-10-9]]

^<<v43-10-9,9>>^ I am the door; whoever enters through me will be saved, and he will go in and out and find pasturage.

[[v43-10-10]]

^<<v43-10-10,10>>^ The thief does not come unless it is to steal and slay and destroy. I have come that they might have life and might have it in abundance.

[[v43-10-11]]

^<<v43-10-11,11>>^ I am the fine shepherd; the fine shepherd surrenders his soul in behalf of the sheep.

[[v43-10-12]]

^<<v43-10-12,12>>^ The hired man, who is no shepherd and to whom the sheep do not belong as his own, beholds the wolf coming and abandons the sheep and flees—and the wolf snatches them and scatters them—

[[v43-10-13]]

^<<v43-10-13,13>>^ because he is a hired man and does not care for the sheep.

[[v43-10-14]]

^<<v43-10-14,14>>^ I am the fine^&#42;1^ shepherd, and I know my sheep and my sheep know me,

[NOTE]
====
. Or, “right.”
====

[[v43-10-15]]

^<<v43-10-15,15>>^ just as the Father knows me and I know the Father; and I surrender my soul^&#42;1^ in behalf of the sheep.

[NOTE]
====
. Or, “my life.” Gr., psy·khenʹ mou; J17,​18,​22(Heb.), naph·shiʹ. See App 4A.
====

[[v43-10-16]]

^<<v43-10-16,16>>^ “And I have other sheep, which are not of this fold; those also I must bring,^&#42;1^ and they will listen to my voice, and they will become one flock, one shepherd.

[NOTE]
====
. Lit., “it is necessary [for] me to lead.”
====

[[v43-10-17]]

^<<v43-10-17,17>>^ This is why the Father loves me, because I surrender my soul, in order that I may receive it again.

[[v43-10-18]]

^<<v43-10-18,18>>^ No man has taken^&#42;1^ it away from me, but I surrender it of my own initiative. I have authority to surrender it, and I have authority to receive it again. The commandment on this I received from my Father.”

[NOTE]
====
. “Has taken,” P45א*BSyp; P66אcADVgSys, “takes.”
====

[[v43-10-19]]

^<<v43-10-19,19>>^ Again a division resulted among the Jews because of these words.

[[v43-10-20]]

^<<v43-10-20,20>>^ Many of them were saying: “He has a demon and is mad. Why do YOU listen to him?”

[[v43-10-21]]

^<<v43-10-21,21>>^ Others would say: “These are not the sayings of a demonized man. A demon cannot open blind people’s eyes, can it?”

[[v43-10-22]]

^<<v43-10-22,22>>^ At that time the festival of dedication^&#42;1^ took place in Jerusalem. It was wintertime,

[NOTE]
====
. “The festival of dedication (Hanukkah).” J22(Heb.), chagh ha·chanuk·kahʹ.
====

[[v43-10-23]]

^<<v43-10-23,23>>^ and Jesus was walking in the temple in the colonnade of Solʹo·mon.

[[v43-10-24]]

^<<v43-10-24,24>>^ Therefore the Jews encircled him and began to say to him: “How long are you to keep our souls in suspense? If you are the Christ, tell us outspokenly.”

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus answered them: “I told YOU, and yet YOU do not believe. The works that I am doing in the name of my Father, these bear witness about me.

[[v43-10-26]]

^<<v43-10-26,26>>^ But YOU do not believe, because YOU are none of my sheep.

[[v43-10-27]]

^<<v43-10-27,27>>^ My sheep listen to my voice, and I know them, and they follow me.

[[v43-10-28]]

^<<v43-10-28,28>>^ And I give them everlasting life, and they will by no means ever be destroyed, and no one will snatch them out of my hand.

[[v43-10-29]]

^<<v43-10-29,29>>^ What my Father has given me is something greater than all other things,^&#42;1^ and no one can snatch them out of the hand of the Father.

[NOTE]
====
. “What . . . things,” BItVg (אW, with a slight variation, agree); ASyh,p,s, “My Father, who has given me them, is greater than all others.”
====

[[v43-10-30]]

^<<v43-10-30,30>>^ I and the Father are one.”^&#42;1^

[NOTE]
====
. Or, “at unity.” Lit., “one (thing).” Gr., hen, neuter, to show oneness in cooperation. See 17:21 and 1Co 3:8 ftns.
====

[[v43-10-31]]

^<<v43-10-31,31>>^ Once more the Jews lifted up stones to stone him.

[[v43-10-32]]

^<<v43-10-32,32>>^ Jesus replied to them: “I displayed to YOU many fine works from the Father. For which of those works are YOU stoning me?”

[[v43-10-33]]

^<<v43-10-33,33>>^ The Jews answered him: “We are stoning you, not for a fine work, but for blasphemy, even because you, although being a man, make yourself a god.”

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus answered them: “Is it not written in your Law, ‘I said: “YOU are gods”’?^&#42;1^

[NOTE]
====
. “You are gods.” Gr., the·oiʹ e·ste; Lat., diʹi eʹstis; J17,​18,​22(Heb.), ʼelo·himʹ ʼat·temʹ.
====

[[v43-10-35]]

^<<v43-10-35,35>>^ If he called ‘gods’ those against^&#42;1^ whom the word of God came, and yet the Scripture cannot be nullified,

[NOTE]
====
. Or, “to.”
====

[[v43-10-36]]

^<<v43-10-36,36>>^ do YOU say to me^&#42;1^ whom the Father sanctified and dispatched into the world, ‘You blaspheme,’ because I said, I am God’s Son?

[NOTE]
====
. Or, “of him.”
====

[[v43-10-37]]

^<<v43-10-37,37>>^ If I am not doing the works of my Father, do not believe me.

[[v43-10-38]]

^<<v43-10-38,38>>^ But if I am doing them, even though YOU do not believe me, believe the works, in order that YOU may come to know and may continue knowing that the Father is in union with me and I am in union with the Father.”

[[v43-10-39]]

^<<v43-10-39,39>>^ Therefore they tried again to seize him; but he got out of their reach.

[[v43-10-40]]

^<<v43-10-40,40>>^ So he went off again across the Jordan to the place where John was baptizing at first, and he stayed there.

[[v43-10-41]]

^<<v43-10-41,41>>^ And many people came to him, and they began saying: “John, indeed, did not perform a single sign, but as many things as John said about this man were all true.”

[[v43-10-42]]

^<<v43-10-42,42>>^ And many put faith in him there.

'''

xref:043-john/043-john-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-john/043-john-011.adoc#v43-11-0[Próximo Capítulo &#62;]