include::./index.adoc[]

[[v43-12-0]]
=== According to John, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-12-1]]

^<<v43-12-1,1>>^ Accordingly Jesus, six days before the passover, arrived at Bethʹa·ny, where Lazʹa·rus^&#42;1^ was whom Jesus had raised up from the dead.

[NOTE]
====
. See 11:1 ftn.
====

[[v43-12-2]]

^<<v43-12-2,2>>^ Therefore they spread an evening meal for him there, and Martha was ministering, but Lazʹa·rus was one of those reclining at the table with him.

[[v43-12-3]]

^<<v43-12-3,3>>^ Mary, therefore, took a pound^&#42;1^ of perfumed oil, genuine nard, very costly, and she greased the feet of Jesus and wiped his feet dry with her hair. The house became filled with the scent of the perfumed oil.

[NOTE]
====
. Gr., liʹtran. About 327 g (11.5 oz).
====

[[v43-12-4]]

^<<v43-12-4,4>>^ But Judas Is·carʹi·ot, one of his disciples, who was about to betray him, said:

[[v43-12-5]]

^<<v43-12-5,5>>^ “Why was it this perfumed oil was not sold for three hundred de·narʹi·i^&#42;1^ and given to the poor people?”

[NOTE]
====
. About $260 with silver valued at $7 (U.S.) per oz t. See App 8A.
====

[[v43-12-6]]

^<<v43-12-6,6>>^ He said this, though, not because he was concerned about the poor, but because he was a thief and had the money box and used to carry off the monies put in it.

[[v43-12-7]]

^<<v43-12-7,7>>^ Therefore Jesus said: “Let her alone, that she may keep this observance in view of the day of my burial.

[[v43-12-8]]

^<<v43-12-8,8>>^ For YOU have the poor always with YOU, but me YOU will not have always.”

[[v43-12-9]]

^<<v43-12-9,9>>^ Therefore a great crowd of the Jews got to know he was there, and they came, not on account of Jesus only, but also to see Lazʹa·rus, whom he raised up from the dead.

[[v43-12-10]]

^<<v43-12-10,10>>^ The chief priests now took counsel to kill Lazʹa·rus also,

[[v43-12-11]]

^<<v43-12-11,11>>^ because on account of him many of the Jews were going there and putting faith in Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ The next day the great crowd that had come to the festival, on hearing that Jesus was coming to Jerusalem,

[[v43-12-13]]

^<<v43-12-13,13>>^ took the branches of palm trees and went out to meet him. And they began to shout: “Save, we pray you!^&#42;1^ Blessed is he that comes in Jehovah’s^&#42;2^ name, even the king of Israel!”

[NOTE]
====
. Lit., “Hosanna!” J7-14,​16-19,​22(Heb.), Hoh·shaʽ-naʼʹ.
. See App 1D.
====

[[v43-12-14]]

^<<v43-12-14,14>>^ But when Jesus had found a young ass, he sat on it, just as it is written:

[[v43-12-15]]

^<<v43-12-15,15>>^ “Have no fear, daughter of Zion. Look! Your king is coming, seated upon an ass’s colt.”

[[v43-12-16]]

^<<v43-12-16,16>>^ These things his disciples took no note of at first, but when Jesus became glorified, then they called to mind that these things were written respecting him and that they did these things to him.

[[v43-12-17]]

^<<v43-12-17,17>>^ Accordingly the crowd that was with him when he called Lazʹa·rus out of the memorial tomb and raised him up from the dead kept bearing witness.

[[v43-12-18]]

^<<v43-12-18,18>>^ On this account the crowd, because they heard he had performed this sign, also met him.

[[v43-12-19]]

^<<v43-12-19,19>>^ Therefore the Pharisees said among themselves: “YOU observe YOU are getting absolutely nowhere. See! The world has gone after him.”

[[v43-12-20]]

^<<v43-12-20,20>>^ Now there were some Greeks among those that came up to worship at the festival.

[[v43-12-21]]

^<<v43-12-21,21>>^ These, therefore, approached Philip who was from Beth·saʹi·da of Galʹi·lee, and they began to request him, saying: “Sir, we want to see Jesus.”

[[v43-12-22]]

^<<v43-12-22,22>>^ Philip came and told Andrew. Andrew and Philip came and told Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ But Jesus answered them, saying: “The hour has come for the Son of man to be glorified.

[[v43-12-24]]

^<<v43-12-24,24>>^ Most truly I say to YOU, Unless a grain of wheat falls into the ground and dies, it remains just one &#91;grain&#93;; but if it dies, it then bears much fruit.

[[v43-12-25]]

^<<v43-12-25,25>>^ He that is fond of his soul^&#42;1^ destroys it, but he that hates his soul in this world will safeguard it for everlasting life.

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; J17,​18,​22(Heb.), naph·shohʹ (from neʹphesh).
====

[[v43-12-26]]

^<<v43-12-26,26>>^ If anyone would minister to me, let him follow me, and where I am there my minister^&#42;1^ will be also. If anyone would minister to me, the Father will honor him.

[NOTE]
====
. “Minister.” Gr., di·aʹko·nos; Lat., mi·niʹster (from miʹnus, “less”); J18,​22(Heb.), mesha·rethiʹ, “my attendant.”
====

[[v43-12-27]]

^<<v43-12-27,27>>^ Now my soul is troubled, and what shall I say? Father, save me out of this hour. Nevertheless, this is why I have come to this hour.

[[v43-12-28]]

^<<v43-12-28,28>>^ Father, glorify your name.” Therefore a voice came out of heaven: “I both glorified &#91;it&#93; and will glorify &#91;it&#93; again.”

[[v43-12-29]]

^<<v43-12-29,29>>^ Hence the crowd that stood about and heard it began to say that it had thundered. Others began to say: “An angel has spoken to him.”

[[v43-12-30]]

^<<v43-12-30,30>>^ In answer Jesus said: “This voice has occurred, not for my sake, but for YOUR sakes.

[[v43-12-31]]

^<<v43-12-31,31>>^ Now there is a judging of this world; now the ruler of this world will be cast out.

[[v43-12-32]]

^<<v43-12-32,32>>^ And yet I, if I am lifted up from the earth, will draw men of all sorts^&#42;1^ to me.”

[NOTE]
====
. Or, “all men.”
====

[[v43-12-33]]

^<<v43-12-33,33>>^ This he was really saying to signify what sort of death he was about to die.

[[v43-12-34]]

^<<v43-12-34,34>>^ Therefore the crowd answered him: “We heard from the Law that the Christ remains forever; and how is it you say that the Son of man must be lifted up? Who is this Son of man?”

[[v43-12-35]]

^<<v43-12-35,35>>^ Jesus therefore said to them: “The light will be among YOU a little while longer. Walk while YOU have the light, so that darkness does not overpower YOU; and he that walks in the darkness does not know where he is going.

[[v43-12-36]]

^<<v43-12-36,36>>^ While YOU have the light, exercise faith in the light, in order to become sons of light.”
Jesus spoke these things and went off and hid from them.

[[v43-12-37]]

^<<v43-12-37,37>>^ But although he had performed so many signs before them, they were not putting faith in him,

[[v43-12-38]]

^<<v43-12-38,38>>^ so that the word of Isaiah the prophet was fulfilled which he said: “Jehovah,^&#42;1^ who has put faith in the thing heard by us?^&#42;2^ And as for the arm of Jehovah,^&#42;3^ to whom has it been revealed?”

[NOTE]
====
. See App 1D.
. Or, “who has believed our report?”
. See App 1D.
====

[[v43-12-39]]

^<<v43-12-39,39>>^ The reason why they were not able to believe is that again Isaiah said:

[[v43-12-40]]

^<<v43-12-40,40>>^ “He has blinded their eyes and he has made their hearts hard, that they should not see with their eyes and get the thought with their hearts and turn around and I should heal them.”

[[v43-12-41]]

^<<v43-12-41,41>>^ Isaiah said these things because he saw his glory, and he spoke about him.

[[v43-12-42]]

^<<v43-12-42,42>>^ All the same, many even of the rulers actually put faith in him, but because of the Pharisees they would not confess &#91;him&#93;, in order not to be expelled from the synagogue;^&#42;1^

[NOTE]
====
. See 9:22 ftn.
====

[[v43-12-43]]

^<<v43-12-43,43>>^ for they loved the glory of men more than even the glory of God.

[[v43-12-44]]

^<<v43-12-44,44>>^ However, Jesus cried out and said: “He that puts faith in me puts faith, not in me &#91;only&#93;, but in him &#91;also&#93; that sent me;

[[v43-12-45]]

^<<v43-12-45,45>>^ and he that beholds me beholds &#91;also&#93; him that sent me.

[[v43-12-46]]

^<<v43-12-46,46>>^ I have come as a light into the world, in order that everyone putting faith in me may not remain in the darkness.

[[v43-12-47]]

^<<v43-12-47,47>>^ But if anyone hears my sayings and does not keep them, I do not judge him; for I came, not to judge the world, but to save the world.

[[v43-12-48]]

^<<v43-12-48,48>>^ He that disregards me and does not receive my sayings has one to judge him. The word that I have spoken is what will judge him in the last day;

[[v43-12-49]]

^<<v43-12-49,49>>^ because I have not spoken out of my own impulse, but the Father himself who sent me has given me a commandment as to what to tell and what to speak.

[[v43-12-50]]

^<<v43-12-50,50>>^ Also, I know that his commandment means^&#42;1^ everlasting life. Therefore the things I speak, just as the Father has told me &#91;them&#93;, so I speak &#91;them&#93;.”

[NOTE]
====
. Or, “is.”
====

'''

xref:043-john/043-john-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-john/043-john-013.adoc#v43-13-0[Próximo Capítulo &#62;]