include::./index.adoc[]

[[v43-19-0]]
=== According to John, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-19-1]]

^<<v43-19-1,1>>^ At that time, therefore, Pilate took Jesus and scourged him.

[[v43-19-2]]

^<<v43-19-2,2>>^ And the soldiers braided a crown of thorns and put it on his head and arrayed him with a purple outer garment;

[[v43-19-3]]

^<<v43-19-3,3>>^ and they began coming up to him and saying: “Good day, you King of the Jews!” Also, they would give him slaps in the face.

[[v43-19-4]]

^<<v43-19-4,4>>^ And Pilate went outside again and said to them: “See! I bring him outside to YOU in order for YOU to know I find no fault in him.”

[[v43-19-5]]

^<<v43-19-5,5>>^ Accordingly Jesus came outside, wearing the thorny crown and the purple outer garment. And he said to them: “Look! The man!”^&#42;1^

[NOTE]
====
. Or, “See! The man!” Gr., I·douʹ ho anʹthro·pos; Lat., ecʹce hoʹmo; J22(Heb.), Hin·nehʹ ha·ʼishʹ; J17(Heb.), Hin·nehʹ ha·ʼa·dhamʹ, “Look! The earthling man!”; J18(Heb.), Hin·nehʹ hag·ga·verʹ, “Look! The able-bodied man.” Compare Zec 6:12 ftn, “Man.”
====

[[v43-19-6]]

^<<v43-19-6,6>>^ However, when the chief priests and the officers saw him, they shouted, saying: “Impale &#91;him&#93;!^&#42;1^ Impale &#91;him&#93;!” Pilate said to them: “Take him yourselves and impale him, for I do not find any fault in him.”

[NOTE]
====
. Or, “Fasten [him] on a stake (pole)!” See App 5C.
====

[[v43-19-7]]

^<<v43-19-7,7>>^ The Jews answered him: “We have a law, and according to the law he ought to die, because he made himself God’s son.”

[[v43-19-8]]

^<<v43-19-8,8>>^ When, therefore, Pilate heard this saying, he became more fearful;

[[v43-19-9]]

^<<v43-19-9,9>>^ and he entered into the governor’s palace again and said to Jesus: “Where are you from?” But Jesus gave him no answer.

[[v43-19-10]]

^<<v43-19-10,10>>^ Hence Pilate said to him: “Are you not speaking to me? Do you not know I have authority to release you and I have authority to impale you?”

[[v43-19-11]]

^<<v43-19-11,11>>^ Jesus answered him: “You would have no authority^&#42;1^ at all against me unless it had been granted to you from above.^&#42;2^ This is why the man that handed me over to you has greater sin.”

[NOTE]
====
. “Authority.” Gr., e·xou·siʹan; Lat., po·te·staʹtem; J17(Heb.), reshuthʹ.
. Or, “from heaven.”
====

[[v43-19-12]]

^<<v43-19-12,12>>^ For this reason Pilate kept on seeking how to release him. But the Jews shouted, saying: “If you release this &#91;man&#93;, you are not a friend of Caesar.^&#42;1^ Every man making himself a king speaks against Caesar.”

[NOTE]
====
. Or, “of the emperor.” Gr., tou Kaiʹsa·ros.
====

[[v43-19-13]]

^<<v43-19-13,13>>^ Therefore Pilate, after hearing these words, brought Jesus outside, and he sat down on a judgment seat in a place called The Stone Pavement, but, in Hebrew, Gabʹba·tha.

[[v43-19-14]]

^<<v43-19-14,14>>^ Now it was preparation of the passover; it was about the sixth hour.^&#42;1^ And he said to the Jews: “See! YOUR king!”

[NOTE]
====
. That is, about 12 noon, counting from sunrise.
====

[[v43-19-15]]

^<<v43-19-15,15>>^ However, they shouted: “Take &#91;him&#93; away! Take &#91;him&#93; away! Impale him!” Pilate said to them: “Shall I impale YOUR king?” The chief priests answered: “We have no king but Caesar.”

[[v43-19-16]]

^<<v43-19-16,16>>^ At that time, therefore, he handed him over to them to be impaled.
Then they took charge of Jesus.

[[v43-19-17]]

^<<v43-19-17,17>>^ And, bearing the torture stake^&#42;1^ for himself, he went out to the so-called Skull Place,^&#42;2^ which is called Golʹgo·tha^&#42;3^ in Hebrew;

[NOTE]
====
. See App 5C.
. See Mt 27:33 ftn, “Skull Place.”
. “Golgotha.” Gr., Gol·go·thaʹ; J17,​18(Aram.), Gol·gol·taʼʹ, “the Skull.”
====

[[v43-19-18]]

^<<v43-19-18,18>>^ and there they impaled him, and two other &#91;men&#93; with him, one on this side and one on that, but Jesus in the middle.

[[v43-19-19]]

^<<v43-19-19,19>>^ Pilate wrote a title also and put it on the torture stake. It was written: “Jesus the Naz·a·reneʹ the King of the Jews.”^&#42;1^

[NOTE]
====
. See 18:33 ftn.
====

[[v43-19-20]]

^<<v43-19-20,20>>^ Therefore many of the Jews read this title, because the place where Jesus was impaled was near the city; and it was written in Hebrew, in Latin, in Greek.

[[v43-19-21]]

^<<v43-19-21,21>>^ However, the chief priests of the Jews began to say to Pilate: “Do not write ‘The King of the Jews,’ but that he said, ‘I am King of the Jews.’”

[[v43-19-22]]

^<<v43-19-22,22>>^ Pilate answered: “What I have written I have written.”

[[v43-19-23]]

^<<v43-19-23,23>>^ Now when the soldiers had impaled Jesus, they took his outer garments and made four parts, for each soldier a part, and the inner garment. But the inner garment was without a seam, being woven from the top throughout its length.

[[v43-19-24]]

^<<v43-19-24,24>>^ Therefore they said to one another: “Let us not tear it, but let us determine by lots over it whose it will be.” This was that the scripture might be fulfilled: “They apportioned my outer garments among themselves, and upon my apparel they cast lots.” And so the soldiers really did these things.

[[v43-19-25]]

^<<v43-19-25,25>>^ By the torture stake of Jesus, however, there were standing his mother and the sister of his mother; Mary the wife of Cloʹpas, and Mary Magʹda·lene.

[[v43-19-26]]

^<<v43-19-26,26>>^ Therefore Jesus, seeing his mother and the disciple whom he loved^&#42;1^ standing by, said to his mother: “Woman, see! Your son!”

[NOTE]
====
. Or, “preferred.”
====

[[v43-19-27]]

^<<v43-19-27,27>>^ Next he said to the disciple: “See! Your mother!” And from that hour on the disciple took her to his own home.

[[v43-19-28]]

^<<v43-19-28,28>>^ After this, when Jesus knew that by now all things had been accomplished, in order that the scripture might be accomplished he said: “I am thirsty.”

[[v43-19-29]]

^<<v43-19-29,29>>^ A vessel was sitting there full of sour wine. Therefore they put a sponge full of the sour wine upon a hyssop &#91;stalk&#93; and brought it to his mouth.

[[v43-19-30]]

^<<v43-19-30,30>>^ When, now, he had received the sour wine, Jesus said: “It has been accomplished!” and, bowing his head, he delivered up &#91;his&#93; spirit.^&#42;1^

[NOTE]
====
. Or, “he stopped breathing.” Lit., “he gave up the spirit.” Gr., pa·reʹdo·ken to pneuʹma.
====

[[v43-19-31]]

^<<v43-19-31,31>>^ Then the Jews, since it was Preparation, in order that the bodies might not remain upon the torture stakes on the Sabbath, (for the day of that Sabbath was a great one,) requested Pilate to have their legs broken and the &#91;bodies&#93;^&#42;1^ taken away.

[NOTE]
====
. Or, “them.”
====

[[v43-19-32]]

^<<v43-19-32,32>>^ The soldiers came, therefore, and broke the legs of the first &#91;man&#93; and those of the other &#91;man&#93; that had been impaled with him.

[[v43-19-33]]

^<<v43-19-33,33>>^ But on coming to Jesus, as they saw that he was already dead, they did not break his legs.

[[v43-19-34]]

^<<v43-19-34,34>>^ Yet one of the soldiers jabbed his side with a spear, and immediately blood and water came out.

[[v43-19-35]]

^<<v43-19-35,35>>^ And he that has seen &#91;it&#93; has borne witness, and his witness is true, and that man knows he tells true things, in order that YOU also may believe.

[[v43-19-36]]

^<<v43-19-36,36>>^ In fact, these things took place in order for the scripture to be fulfilled: “Not a bone of his will be crushed.”

[[v43-19-37]]

^<<v43-19-37,37>>^ And, again, a different scripture says: “They will look to the One whom they pierced.”

[[v43-19-38]]

^<<v43-19-38,38>>^ Now after these things Joseph from Ar·i·ma·theʹa, who was a disciple of Jesus but a secret one out of &#91;his&#93; fear of the Jews, requested Pilate that he might take away the body of Jesus; and Pilate gave him permission. Therefore he came and took his body away.

[[v43-19-39]]

^<<v43-19-39,39>>^ Nic·o·deʹmus also, the man that came to him in the night the first time, came bringing a roll^&#42;1^ of myrrh and aloes, about a hundred pounds^&#42;2^ &#91;of it&#93;.

[NOTE]
====
. “Roll,” א*B; P66אcAVgSyp, “mixture.”
. “Pounds.” Gr., liʹtras, generally equated with the Roman pound that weighed 327 g (11.5 oz); Lat., liʹbras.
====

[[v43-19-40]]

^<<v43-19-40,40>>^ So they took the body of Jesus and bound it up with bandages with the spices, just the way the Jews have the custom of preparing for burial.

[[v43-19-41]]

^<<v43-19-41,41>>^ Incidentally, at the place where he was impaled there was a garden, and in the garden a new memorial tomb, in which no one had ever yet been laid.

[[v43-19-42]]

^<<v43-19-42,42>>^ There, then, on account of the preparation of the Jews, they laid Jesus, because the memorial tomb was nearby.

'''

xref:043-john/043-john-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-john/043-john-020.adoc#v43-20-0[Próximo Capítulo &#62;]