include::./index.adoc[]

[[v43-1-0]]
=== According to John, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v43-1-1]]

^<<v43-1-1,1>>^ In &#91;the&#93; beginning the Word^&#42;1^ was, and the Word was with God,^&#42;2^ and the Word was a god.^&#42;3^

[NOTE]
====
. Or, “the Logos.” Gr., ho loʹgos; Lat., Verʹbum; J17,​18,​22(Heb.), had·Da·varʹ.
. Lit., “was toward the God.” Gr., en pros ton The·onʹ; J17,​18(Heb.), ha·yahʹ ʼeth ha·ʼElo·himʹ.
. “A god.” Gr., the·osʹ, in contrast with ton The·onʹ, “the God,” in the same sentence; J17,​18(Heb.), weʼ·lo·himʹ, “and god.” For a discussion of “a god,” see App 6A.
====

[[v43-1-2]]

^<<v43-1-2,2>>^ This one was in &#91;the&#93; beginning with God.

[[v43-1-3]]

^<<v43-1-3,3>>^ All things came into existence through him, and apart from him not even one thing came into existence.
What has come into existence

[[v43-1-4]]

^<<v43-1-4,4>>^ by means of him was life, and the life was the light of men.^&#42;1^

[NOTE]
====
. The punctuation of vss 3 and 4 is according to WH, Vgww and The Greek New Testament by the United Bible Societies.
====

[[v43-1-5]]

^<<v43-1-5,5>>^ And the light is shining in the darkness, but the darkness has not overpowered it.

[[v43-1-6]]

^<<v43-1-6,6>>^ There arose a man that was sent forth as a representative of God: his name was John.^&#42;1^

[NOTE]
====
. See Mt 3:1 ftn, “John.”
====

[[v43-1-7]]

^<<v43-1-7,7>>^ This &#91;man&#93; came for a witness, in order to bear witness about the light, that people of all sorts might believe through him.

[[v43-1-8]]

^<<v43-1-8,8>>^ He was not that light, but he was meant to bear witness about that light.

[[v43-1-9]]

^<<v43-1-9,9>>^ The true light that gives light to every sort of man was about to come into the world.^&#42;1^

[NOTE]
====
. See 3:16 ftn.
====

[[v43-1-10]]

^<<v43-1-10,10>>^ He was in the world, and the world came into existence through him, but the world did not know him.

[[v43-1-11]]

^<<v43-1-11,11>>^ He came to his own home, but his own people did not take him in.

[[v43-1-12]]

^<<v43-1-12,12>>^ However, as many as did receive him, to them he gave authority to become God’s children, because they were exercising faith in his name;

[[v43-1-13]]

^<<v43-1-13,13>>^ and they were born, not from blood^&#42;1^ or from a fleshly will or from man’s will, but from God.

[NOTE]
====
. Lit., “bloods.”
====

[[v43-1-14]]

^<<v43-1-14,14>>^ So the Word became flesh and resided^&#42;1^ among us, and we had a view of his glory, a glory such as belongs to an only-begotten son from a father; and he was full of undeserved kindness and truth.

[NOTE]
====
. Lit., “tented.” See Re 21:3 ftns.
====

[[v43-1-15]]

^<<v43-1-15,15>>^ (John bore witness about him, yes, he actually cried out—this was the one who said &#91;it&#93;—saying: “The one coming behind me has advanced in front of me, because he existed before me.”)

[[v43-1-16]]

^<<v43-1-16,16>>^ For we all received from out of his fullness, even undeserved kindness upon undeserved kindness.

[[v43-1-17]]

^<<v43-1-17,17>>^ Because the Law was given through Moses, the undeserved kindness and the truth came to be through Jesus Christ.

[[v43-1-18]]

^<<v43-1-18,18>>^ No man has seen God at any time; the only-begotten god^&#42;1^ who is in the bosom &#91;position&#93; with the Father is the one that has explained him.

[NOTE]
====
. “The only-begotten god,” P75אc; P66א*BC*, “only-begotten god”; ACcItVgSyc,h, “the only-begotten Son.”
====

[[v43-1-19]]

^<<v43-1-19,19>>^ Now this is the witness^&#42;1^ of John when the Jews sent forth priests and Levites from Jerusalem to him to ask him: “Who are you?”

[NOTE]
====
. “Witness.” Gr., mar·ty·riʹa; Lat., te·sti·moʹni·um.
====

[[v43-1-20]]

^<<v43-1-20,20>>^ And he confessed and did not deny, but confessed: “I am not the Christ.”

[[v43-1-21]]

^<<v43-1-21,21>>^ And they asked him: “What, then? Are you E·liʹjah?”^&#42;1^ And he said: “I am not.” “Are you The Prophet?” And he answered: “No!”

[NOTE]
====
. “Elijah” (meaning “My God Is Jehovah”), J17,​18,​22; Gr., E·leiʹas.
====

[[v43-1-22]]

^<<v43-1-22,22>>^ Therefore they said to him: “Who are you? that we may give an answer to those who sent us. What do you say about yourself?”

[[v43-1-23]]

^<<v43-1-23,23>>^ He said: “I am a voice of someone crying out in the wilderness, ‘MAKE the way of Jehovah^&#42;1^ straight,’ just as Isaiah the prophet said.”

[NOTE]
====
. See App 1D.
====

[[v43-1-24]]

^<<v43-1-24,24>>^ Now those sent forth were from the Pharisees.

[[v43-1-25]]

^<<v43-1-25,25>>^ So they questioned him and said to him: “Why, then, do you baptize if you yourself are not the Christ or E·liʹjah or The Prophet?”

[[v43-1-26]]

^<<v43-1-26,26>>^ John answered them, saying: “I baptize^&#42;1^ in water. In the midst of YOU one is standing whom YOU do not know,

[NOTE]
====
. Or, “I immerse; I dip.” Gr., ba·ptiʹzo.
====

[[v43-1-27]]

^<<v43-1-27,27>>^ the one coming behind me, but the lace of whose sandal I am not worthy to untie.”

[[v43-1-28]]

^<<v43-1-28,28>>^ These things took place in Bethʹa·ny^&#42;1^ across the Jordan, where John was baptizing.

[NOTE]
====
. Not the Bethany near Jerusalem.
====

[[v43-1-29]]

^<<v43-1-29,29>>^ The next day he beheld Jesus coming toward him, and he said: “See, the Lamb of God that takes away the sin of the world!^&#42;1^

[NOTE]
====
. Compare 3:16 ftn.
====

[[v43-1-30]]

^<<v43-1-30,30>>^ This is the one about whom I said, Behind me there comes a man who has advanced in front of me, because he existed before me.

[[v43-1-31]]

^<<v43-1-31,31>>^ Even I did not know him, but the reason why I came baptizing in water was that he might be made manifest to Israel.”

[[v43-1-32]]

^<<v43-1-32,32>>^ John also bore witness, saying: “I viewed the spirit coming down as a dove out of heaven, and it remained upon him.

[[v43-1-33]]

^<<v43-1-33,33>>^ Even I did not know him, but the very One who sent me to baptize in water said to me, ‘Whoever it is upon whom you see the spirit coming down and remaining, this is the one that baptizes in holy spirit.’

[[v43-1-34]]

^<<v43-1-34,34>>^ And I have seen &#91;it&#93;, and I have borne witness that this one is the Son of God.”

[[v43-1-35]]

^<<v43-1-35,35>>^ Again the next day John was standing with two of his disciples,

[[v43-1-36]]

^<<v43-1-36,36>>^ and as he looked at Jesus walking he said: “See, the Lamb of God!”

[[v43-1-37]]

^<<v43-1-37,37>>^ And the two disciples heard him speak, and they followed Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Then Jesus turned and, getting a view of them following, he said to them: “What are YOU looking for?” They said to him: “Rabbi, (which means, when translated, Teacher,) where are you staying?”

[[v43-1-39]]

^<<v43-1-39,39>>^ He said to them: “Come, and YOU will see.” Accordingly they went and saw where he was staying, and they stayed with him that day; it was about the tenth hour.^&#42;1^

[NOTE]
====
. That is, about 4 p.m., counting from sunrise.
====

[[v43-1-40]]

^<<v43-1-40,40>>^ Andrew the brother of Simon Peter was one of the two that heard what John said and followed &#91;Jesus&#93;.^&#42;1^

[NOTE]
====
. Lit., “him.”
====

[[v43-1-41]]

^<<v43-1-41,41>>^ First^&#42;1^ this one found his own brother, Simon, and said to him: “We have found the Mes·siʹah”^&#42;2^ (which means, when translated, Christ).

[NOTE]
====
. “Early next morning,” ItmssSys.
. Or, “the Anointed One.” Gr., ton Mes·siʹan; Lat., Mes·siʹam; J17,​18,​22(Heb.), ham·Ma·shiʹach.
====

[[v43-1-42]]

^<<v43-1-42,42>>^ He led him to Jesus. When Jesus looked upon him he said: “You are Simon the son of John;^&#42;1^ you will be called Ceʹphas”^&#42;2^ (which is translated Peter).^&#42;3^

[NOTE]
====
. “John,” P66,​75אB*It; ABcVgcSyp,s, “Jona.”
. “Cephas.” Gr., Ke·phasʹ. An Aram. name (Keh·phaʼ), here in the masc. gender, as in Mt 16:18 in Syr. mss. See Mt 16:18 ftn, “Rock-mass.”
. Meaning “A Piece of Rock.” Gr., Peʹtros.
====

[[v43-1-43]]

^<<v43-1-43,43>>^ The next day he desired to depart for Galʹi·lee. So Jesus found Philip and said to him: “Be my follower.”

[[v43-1-44]]

^<<v43-1-44,44>>^ Now Philip was from Beth·saʹi·da, from the city of Andrew and Peter.

[[v43-1-45]]

^<<v43-1-45,45>>^ Philip found Na·thanʹa·el and said to him: “We have found the one of whom Moses, in the Law, and the Prophets wrote, Jesus, the son of Joseph, from Nazʹa·reth.”

[[v43-1-46]]

^<<v43-1-46,46>>^ But Na·thanʹa·el said to him: “Can anything good come out of Nazʹa·reth?” Philip said to him: “Come and see.”

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus saw Na·thanʹa·el coming toward him and said about him: “See, an Israelite for a certainty, in whom there is no deceit.”

[[v43-1-48]]

^<<v43-1-48,48>>^ Na·thanʹa·el said to him: “How does it come that you know me?” Jesus in answer said to him: “Before Philip called you, while you were under the fig tree, I saw you.”

[[v43-1-49]]

^<<v43-1-49,49>>^ Na·thanʹa·el answered him: “Rabbi, you are the Son of God, you are King of Israel.”

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus in answer said to him: “Because I told you I saw you underneath the fig tree do you believe? You will see things greater than these.”

[[v43-1-51]]

^<<v43-1-51,51>>^ He further said to him: “Most truly^&#42;1^ I say to YOU men, YOU will see heaven opened up and the angels^&#42;2^ of God ascending and descending to^&#42;3^ the Son of man.”

[NOTE]
====
. Lit., “Truly, truly.” Gr., A·menʹ, a·menʹ.
. Or, “messengers.” Gr., ag·geʹlous; Lat., anʹge·los. Compare Job 33:23; Ps 91:11.
. Or, “in the service of.”
====

'''

xref:042-luke/042-luke-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-john/043-john-002.adoc#v43-2-0[Próximo Capítulo &#62;]