include::./index.adoc[]

[[v20-24-0]]
=== Proverbs, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-24-1]]

^<<v20-24-1,1>>^ Do not be envious of bad men, and do not show yourself craving to get in with them.

[[v20-24-2]]

^<<v20-24-2,2>>^ For despoiling is what their heart keeps meditating, and trouble is what their own lips keep speaking.

[[v20-24-3]]

^<<v20-24-3,3>>^ By wisdom a household will be built up, and by discernment it will prove firmly established.

[[v20-24-4]]

^<<v20-24-4,4>>^ And by knowledge will the interior rooms be filled with all precious and pleasant things of value.

[[v20-24-5]]

^<<v20-24-5,5>>^ One wise in strength is an able-bodied man, and a man of knowledge is reinforcing power.^&#42;1^

[NOTE]
====
. “The wise one is superior to the strong one, and a man of knowledge to the one vigorous in power,” by slight changes of M and in agreement with LXX.
====

[[v20-24-6]]

^<<v20-24-6,6>>^ For by skillful direction you will carry on your war, and in the multitude of counselors there is salvation.

[[v20-24-7]]

^<<v20-24-7,7>>^ For a foolish one true wisdom is too high;^&#42;1^ in the gate he will not open his mouth.

[NOTE]
====
. Or, “is as corals.”
====

[[v20-24-8]]

^<<v20-24-8,8>>^ As for anyone scheming to do bad, he will be called a mere master at evil ideas.

[[v20-24-9]]

^<<v20-24-9,9>>^ The loose conduct of foolishness is sin, and a ridiculer is something detestable to mankind.

[[v20-24-10]]

^<<v20-24-10,10>>^ Have you shown yourself discouraged in the day of distress? Your power will be scanty.

[[v20-24-11]]

^<<v20-24-11,11>>^ Deliver those who are being taken away to death; and those staggering to the slaughter, O may you hold &#91;them&#93; back.

[[v20-24-12]]

^<<v20-24-12,12>>^ In case you should say: “Look! We did not know of this,” will not he himself that is making an estimate of hearts discern it, and he himself that is observing your soul know and certainly pay back to earthling man according to his activity?

[[v20-24-13]]

^<<v20-24-13,13>>^ My son, eat honey, for it is good; and let sweet comb honey be upon your palate.

[[v20-24-14]]

^<<v20-24-14,14>>^ In the same way, do know wisdom for your soul. If you have found &#91;it&#93;, then there exists a future, and your own hope will not be cut off.

[[v20-24-15]]

^<<v20-24-15,15>>^ Do not, as a wicked one, lie in wait for the abiding place of the righteous one; do not despoil his resting-place.

[[v20-24-16]]

^<<v20-24-16,16>>^ For the righteous one may fall even seven times, and he will certainly get up; but the wicked ones will be made to stumble by calamity.

[[v20-24-17]]

^<<v20-24-17,17>>^ When your enemy falls, do not rejoice; and when he is caused to stumble, may your heart not be joyful,

[[v20-24-18]]

^<<v20-24-18,18>>^ that Jehovah may not see and it be bad in his eyes and he certainly turn back his anger from against him.

[[v20-24-19]]

^<<v20-24-19,19>>^ Do not show yourself heated up at evildoers. Do not become envious of wicked people.

[[v20-24-20]]

^<<v20-24-20,20>>^ For there will prove to be no future for anyone bad; the very lamp of wicked people will be extinguished.

[[v20-24-21]]

^<<v20-24-21,21>>^ My son, fear Jehovah and the king.^&#42;1^ With those who are for a change, do not intermeddle.

[NOTE]
====
. “My son, fear Jehovah [Heb., Yehwahʹ] and the king.” Gr., pho·bouʹ ton the·onʹ, hui·eʹ, kai ba·si·leʹa, “[My] son, fear God and the king.” Two distinct persons, “God” and “king,” are connected in Gr. by kai, “and.” In Gr. the definite article occurs before the first person, but it was not necessary before the second person, so it was omitted. See App 6E.
====

[[v20-24-22]]

^<<v20-24-22,22>>^ For their disaster will arise so suddenly, that who is aware of the extinction of those who are for a change?

[[v20-24-23]]

^<<v20-24-23,23>>^ These &#91;sayings&#93; also are for the wise ones: The showing of partiality^&#42;1^ in judgment is not good.

[NOTE]
====
. Lit., “To discern faces.”
====

[[v20-24-24]]

^<<v20-24-24,24>>^ He that is saying to the wicked one: “You are righteous,” the peoples will execrate him, national groups will denounce him.

[[v20-24-25]]

^<<v20-24-25,25>>^ But for those reproving &#91;him&#93; it will be pleasant, and upon them there will come the blessing of good.

[[v20-24-26]]

^<<v20-24-26,26>>^ Lips will he kiss who is replying in a straightforward way.

[[v20-24-27]]

^<<v20-24-27,27>>^ Prepare your work out of doors, and make it ready for yourself in the field. Afterward you must also build up your household.

[[v20-24-28]]

^<<v20-24-28,28>>^ Do not become a witness against your fellowman without grounds. Then you would have to be foolish with your lips.

[[v20-24-29]]

^<<v20-24-29,29>>^ Do not say: “Just as he did to me, so I am going to do to him. I shall repay to each one according to his acting.”

[[v20-24-30]]

^<<v20-24-30,30>>^ I passed along by the field of the lazy individual and by the vineyard of the man in need of heart.^&#42;1^

[NOTE]
====
. Or, “the earthling man in need of good motive.” Heb., ʼa·dhamʹ chasar-levʹ.
====

[[v20-24-31]]

^<<v20-24-31,31>>^ And, look! all of it produced weeds. Nettles covered its very surface, and its stone wall itself had been torn down.

[[v20-24-32]]

^<<v20-24-32,32>>^ So I proceeded to behold, I myself; I began taking &#91;it&#93; to heart; I saw, I took the discipline:

[[v20-24-33]]

^<<v20-24-33,33>>^ A little sleeping, a little slumbering, a little folding of the hands to lie down,

[[v20-24-34]]

^<<v20-24-34,34>>^ and as a highwayman your poverty will certainly come and your neediness as an armed man.^&#42;1^

[NOTE]
====
. Lit., “like a man of a shield.” Heb., keʼishʹ ma·ghenʹ.
====

'''

xref:020-proverbs/020-proverbs-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbs/020-proverbs-025.adoc#v20-25-0[Próximo Capítulo &#62;]