include::./index.adoc[]

[[v20-19-0]]
=== Proverbs, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-19-1]]

^<<v20-19-1,1>>^ Anyone of little means who is walking in his integrity is better than the one crooked in his lips,^&#42;1^ and the one that is stupid.

[NOTE]
====
. “Lips,” MVg; TSy and about 50 Heb. mss, “ways.”
====

[[v20-19-2]]

^<<v20-19-2,2>>^ Also, that the soul should be without knowledge is not good, and he that is hastening with his feet is sinning.^&#42;1^

[NOTE]
====
. Or, “missing the mark.” See Ro 3:23.
====

[[v20-19-3]]

^<<v20-19-3,3>>^ It is the foolishness of an earthling man that distorts his way, and so his heart becomes enraged against Jehovah himself.

[[v20-19-4]]

^<<v20-19-4,4>>^ Wealth is what adds many companions, but one that is lowly gets separated even from his companion.

[[v20-19-5]]

^<<v20-19-5,5>>^ A false witness will not be free from punishment, and he that launches forth lies will not escape.

[[v20-19-6]]

^<<v20-19-6,6>>^ Many are those who soften the face of a noble, and everybody is a companion to the man making gifts.

[[v20-19-7]]

^<<v20-19-7,7>>^ The brothers of one of little means have all hated him. How much farther have his personal friends kept away from him! He is pursuing with things to say; they are not.

[[v20-19-8]]

^<<v20-19-8,8>>^ He that is acquiring heart^&#42;1^ is loving his own soul. He that is guarding discernment is going to find good.

[NOTE]
====
. Or, “He that is acquiring good motive.” Heb., qo·neh-levʹ.
====

[[v20-19-9]]

^<<v20-19-9,9>>^ The false witness will not be free from punishment, and he that launches forth lies will perish.

[[v20-19-10]]

^<<v20-19-10,10>>^ Luxury is not fitting for anyone stupid. How much less for a servant to rule over princes!

[[v20-19-11]]

^<<v20-19-11,11>>^ The insight of a man^&#42;1^ certainly slows down his anger, and it is beauty on his part to pass over transgression.

[NOTE]
====
. Or, “The insight of an earthling man.” Heb., seʹkhel ʼa·dhamʹ.
====

[[v20-19-12]]

^<<v20-19-12,12>>^ The raging of a king is a growling like that of a maned young lion, but his goodwill is like the dew upon the vegetation.

[[v20-19-13]]

^<<v20-19-13,13>>^ A stupid son means adversities to his father, and the contentions of a wife are as a leaking roof that drives one away.

[[v20-19-14]]

^<<v20-19-14,14>>^ The inheritance from fathers is a house and wealth, but a discreet wife is from Jehovah.

[[v20-19-15]]

^<<v20-19-15,15>>^ Laziness causes a deep sleep to fall, and a slack soul goes hungry.

[[v20-19-16]]

^<<v20-19-16,16>>^ He that is keeping the commandment is keeping his soul; he that is despising his ways will be put to death.

[[v20-19-17]]

^<<v20-19-17,17>>^ He that is showing favor to the lowly one is lending to Jehovah, and his treatment He will repay to him.

[[v20-19-18]]

^<<v20-19-18,18>>^ Chastise your son while there exists hope; and to the putting of him to death do not lift up your soul&#91;ful desire&#93;.

[[v20-19-19]]

^<<v20-19-19,19>>^ He that is of great rage will be bearing the fine; for if you would deliver &#91;him&#93;, you will also keep doing it again and again.

[[v20-19-20]]

^<<v20-19-20,20>>^ Listen to counsel and accept discipline, in order that you may become wise in your future.

[[v20-19-21]]

^<<v20-19-21,21>>^ Many are the plans in the heart of a man,^&#42;1^ but the counsel of Jehovah is what will stand.

[NOTE]
====
. “In the heart of a man.” Heb., belev-ʼishʹ.
====

[[v20-19-22]]

^<<v20-19-22,22>>^ The desirable thing in earthling man^&#42;1^ is his loving-kindness; and one of little means is better than a lying man.

[NOTE]
====
. “The desirable thing in earthling man.” Heb., ta·ʼawathʹ ʼa·dhamʹ.
====

[[v20-19-23]]

^<<v20-19-23,23>>^ The fear of Jehovah tends toward life, and one will spend the night satisfied; one will not be visited with what is bad.

[[v20-19-24]]

^<<v20-19-24,24>>^ The lazy one has hidden his hand in the banquet bowl; he cannot bring it back even to his own mouth.

[[v20-19-25]]

^<<v20-19-25,25>>^ The ridiculer you should strike, that the inexperienced one may become shrewd; and there should be a reproving of the understanding one, that he may discern knowledge.

[[v20-19-26]]

^<<v20-19-26,26>>^ He that is maltreating a father &#91;and&#93; that chases a mother away is a son acting shamefully and disgracefully.

[[v20-19-27]]

^<<v20-19-27,27>>^ Cease, my son, to listen to discipline &#91;and it will mean&#93; to stray from the sayings of knowledge.

[[v20-19-28]]

^<<v20-19-28,28>>^ A good-for-nothing witness^&#42;1^ derides justice, and the very mouth of wicked people swallows down what is hurtful.

[NOTE]
====
. Lit., “A witness of belial.” Heb., ʽedh beli·yaʹʽal.
====

[[v20-19-29]]

^<<v20-19-29,29>>^ Judgments have been firmly established for ridiculers, and strokes for the back of stupid ones.

'''

xref:020-proverbs/020-proverbs-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbs/020-proverbs-020.adoc#v20-20-0[Próximo Capítulo &#62;]