include::./index.adoc[]

[[v20-5-0]]
=== Proverbs, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-5-1]]

^<<v20-5-1,1>>^ My son, to my wisdom O do pay attention. To my discernment incline your ears,

[[v20-5-2]]

^<<v20-5-2,2>>^ so as to guard thinking abilities; and may your own lips safeguard knowledge itself.

[[v20-5-3]]

^<<v20-5-3,3>>^ For as a honeycomb the lips of a strange woman keep dripping, and her palate is smoother than oil.

[[v20-5-4]]

^<<v20-5-4,4>>^ But the aftereffect from her is as bitter as wormwood; it is as sharp as a two-edged sword.

[[v20-5-5]]

^<<v20-5-5,5>>^ Her feet are descending to death. Her very steps take hold on Sheʹol^&#42;1^ itself.

[NOTE]
====
. “Sheol.” Heb., sheʼohlʹ; Gr., haiʹden; Lat., inʹfe·ros.
====

[[v20-5-6]]

^<<v20-5-6,6>>^ The path of life she does not contemplate. Her tracks have wandered she does not know &#91;where&#93;.

[[v20-5-7]]

^<<v20-5-7,7>>^ So now, O sons, listen to me and do not turn away from the sayings of my mouth.

[[v20-5-8]]

^<<v20-5-8,8>>^ Keep your way far off from alongside her, and do not get near to the entrance of her house,

[[v20-5-9]]

^<<v20-5-9,9>>^ that you may not give to others your dignity,^&#42;1^ nor your years to what is cruel;

[NOTE]
====
. “Dignity,” M; TSy, “vital energy”; LXX, “life”; Vg, “honor.”
====

[[v20-5-10]]

^<<v20-5-10,10>>^ that strangers may not satisfy themselves with your power, nor the things you got by pain be in the house of a foreigner,

[[v20-5-11]]

^<<v20-5-11,11>>^ nor you have to groan in your future when your flesh and your organism come to an end.

[[v20-5-12]]

^<<v20-5-12,12>>^ And you will have to say: “How I have hated discipline and my heart has disrespected even reproof!

[[v20-5-13]]

^<<v20-5-13,13>>^ And I have not listened to the voice of my instructors, and to my teachers I have not inclined my ear.

[[v20-5-14]]

^<<v20-5-14,14>>^ Easily I have come to be in every sort of badness in the midst of the congregation and of the assembly.”

[[v20-5-15]]

^<<v20-5-15,15>>^ Drink water out of your own cistern, and tricklings out of the midst of your own well.

[[v20-5-16]]

^<<v20-5-16,16>>^ Should your springs be scattered out of doors, &#91;your&#93; streams of water in the public squares themselves?

[[v20-5-17]]

^<<v20-5-17,17>>^ Let them prove to be for you alone, and not for strangers with you.

[[v20-5-18]]

^<<v20-5-18,18>>^ Let your water source prove to be blessed, and rejoice with the wife of your youth,

[[v20-5-19]]

^<<v20-5-19,19>>^ a lovable hind and a charming mountain goat. Let her own breasts intoxicate you at all times. With her love may you be in an ecstasy constantly.

[[v20-5-20]]

^<<v20-5-20,20>>^ So why should you, my son, be in an ecstasy with a strange woman or embrace the bosom of a foreign woman?

[[v20-5-21]]

^<<v20-5-21,21>>^ For the ways of man^&#42;1^ are in front of the eyes of Jehovah, and he is contemplating all his tracks.

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v20-5-22]]

^<<v20-5-22,22>>^ His own errors will catch the wicked one,^&#42;1^ and in the ropes of his own sin he will be taken hold of.

[NOTE]
====
. Or, “catch him with the wicked one.”
====

[[v20-5-23]]

^<<v20-5-23,23>>^ He will be the one to die because there is no discipline, and &#91;because&#93; in the abundance of his foolishness he goes astray.^&#42;1^

[NOTE]
====
. “Will be swept away,” by a correction of M; LXX, “has been destroyed.”
====

'''

xref:020-proverbs/020-proverbs-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbs/020-proverbs-006.adoc#v20-6-0[Próximo Capítulo &#62;]