include::./index.adoc[]

[[v20-8-0]]
=== Proverbs, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-8-1]]

^<<v20-8-1,1>>^ Does not wisdom keep calling out, and discernment keep giving forth its voice?

[[v20-8-2]]

^<<v20-8-2,2>>^ On top of the heights, by the way, at the crossing of the roadways it has stationed itself.

[[v20-8-3]]

^<<v20-8-3,3>>^ At the side of the gates, at the mouth of the town, at the going in of the entrances it keeps crying loudly:

[[v20-8-4]]

^<<v20-8-4,4>>^ “To YOU, O men,^&#42;1^ I am calling, and my voice is to the sons of men.^&#42;2^

[NOTE]
====
. “Men.” Heb., ʼi·shimʹ, pl. of ʼish. See Isa 53:3 ftn, “Men.”
. Lit., “earthling man.” Heb., ʼa·dhamʹ.
====

[[v20-8-5]]

^<<v20-8-5,5>>^ O inexperienced ones, understand shrewdness; and YOU stupid ones, understand heart.^&#42;1^

[NOTE]
====
. Or, “have good motive.” Heb., ha·viʹnu lev.
====

[[v20-8-6]]

^<<v20-8-6,6>>^ Listen, for it is about the foremost things that I speak, and the opening of my lips is about uprightness.

[[v20-8-7]]

^<<v20-8-7,7>>^ For my palate in low tones utters truth itself; and wickedness is something detestable to my lips.

[[v20-8-8]]

^<<v20-8-8,8>>^ All the sayings of my mouth are in righteousness. Among them there is nothing twisted or crooked.

[[v20-8-9]]

^<<v20-8-9,9>>^ All of them are straight to the discerning one, and upright to the ones finding knowledge.

[[v20-8-10]]

^<<v20-8-10,10>>^ TAKE my discipline and not silver, and knowledge rather than choice gold.

[[v20-8-11]]

^<<v20-8-11,11>>^ For wisdom is better than corals, and all other delights themselves cannot be made equal to it.

[[v20-8-12]]

^<<v20-8-12,12>>^ “I, wisdom, I have resided with shrewdness and I find even the knowledge of thinking abilities.

[[v20-8-13]]

^<<v20-8-13,13>>^ The fear of Jehovah means the hating of bad. Self-exaltation and pride and the bad way and the perverse mouth I have hated.

[[v20-8-14]]

^<<v20-8-14,14>>^ I have counsel and practical wisdom. I—understanding; I have mightiness.

[[v20-8-15]]

^<<v20-8-15,15>>^ By me kings themselves keep reigning, and high officials themselves keep decreeing righteousness.

[[v20-8-16]]

^<<v20-8-16,16>>^ By me princes themselves keep ruling as princes, and nobles are all judging in righteousness.

[[v20-8-17]]

^<<v20-8-17,17>>^ Those loving me^&#42;1^ I myself love, and those looking for me are the ones that find me.

[NOTE]
====
. “Me,” MmarginTLXXSyVg; M, “it (her).”
====

[[v20-8-18]]

^<<v20-8-18,18>>^ Riches and glory^&#42;1^ are with me, hereditary values and righteousness.

[NOTE]
====
. Or, “honor.”
====

[[v20-8-19]]

^<<v20-8-19,19>>^ My fruitage is better than gold,^&#42;1^ even than refined gold, and my produce than choice silver.

[NOTE]
====
. “Than gold.” Heb., me·cha·rutsʹ.
====

[[v20-8-20]]

^<<v20-8-20,20>>^ In the path of righteousness I walk, in the middle of the roadways of judgment,

[[v20-8-21]]

^<<v20-8-21,21>>^ to cause those loving me to take possession of substance; and their storehouses I keep filled.

[[v20-8-22]]

^<<v20-8-22,22>>^ “Jehovah himself produced me^&#42;1^ as the beginning^&#42;2^ of his way, the earliest of his achievements of long ago.

[NOTE]
====
. “Produced me.” Heb., qa·naʹni; TLXX(Gr., eʹkti·senʹ me)Sy, “created me”; Lat., pos·seʹdit me, “possessed me.” See Ge 14:19 ftn.
. “As the beginning of.” Heb., reʼ·shithʹ; Gr., ar·khenʹ; not bereʼ·shithʹ (Heb.) or en ar·kheiʹ (Gr.) as in Ge 1:1; Sy, “as the first”; TVgc(Lat., in i·niʹti·o), “in the beginning.”
====

[[v20-8-23]]

^<<v20-8-23,23>>^ From time indefinite I was installed, from the start,^&#42;1^ from times earlier than the earth.

[NOTE]
====
. Lit., “from the head.” Heb., me·roʼshʹ.
====

[[v20-8-24]]

^<<v20-8-24,24>>^ When there were no watery deeps^&#42;1^ I was brought forth as with labor pains, when there were no springs heavily charged with water.

[NOTE]
====
. Or, “surging waters.” Heb., teho·mohthʹ. See Ge 1:2 ftn, “Deep.”
====

[[v20-8-25]]

^<<v20-8-25,25>>^ Before the mountains themselves had been settled down, ahead of the hills, I was brought forth as with labor pains,

[[v20-8-26]]

^<<v20-8-26,26>>^ when as yet he had not made the earth and the open spaces and the first part of the dust masses of the productive land.^&#42;1^

[NOTE]
====
. “Productive land.” Heb., te·velʹ; Lat., orʹbis terʹrae, “circle of the earth.”
====

[[v20-8-27]]

^<<v20-8-27,27>>^ When he prepared the heavens I was there; when he decreed a circle upon the face of the watery deep,

[[v20-8-28]]

^<<v20-8-28,28>>^ when he made firm the cloud masses above, when he caused the fountains of the watery deep to be strong,

[[v20-8-29]]

^<<v20-8-29,29>>^ when he set for the sea his decree that the waters themselves should not pass beyond his order,^&#42;1^ when he decreed the foundations of the earth,

[NOTE]
====
. Lit., “mouth.”
====

[[v20-8-30]]

^<<v20-8-30,30>>^ then I came to be beside him as a master worker,^&#42;1^ and I came to be the one he^&#42;2^ was specially fond of day by day, I being glad before him all the time,

[NOTE]
====
. Or, “a fosterling.” Heb., ʼa·mohnʹ; T, “proving faithful”; LXX, “acting suitably”; Vg, “composing all things.”
. “He,” LXXSy.
====

[[v20-8-31]]

^<<v20-8-31,31>>^ being glad at the productive land^&#42;1^ of his earth, and the things I was fond of were with the sons of men.^&#42;2^

[NOTE]
====
. “At the productive land of.” Heb., bethe·velʹ; LXX, “the inhabited earth.”
. Lit., “earthling man.” Heb., ʼa·dhamʹ.
====

[[v20-8-32]]

^<<v20-8-32,32>>^ “And now, O sons, listen to me; yes, happy are the ones that keep my very ways.

[[v20-8-33]]

^<<v20-8-33,33>>^ Listen to discipline and become wise, and do not show any neglect.

[[v20-8-34]]

^<<v20-8-34,34>>^ Happy is the man that is listening to me by keeping awake at my doors day by day, by watching at the posts of my entrances.

[[v20-8-35]]

^<<v20-8-35,35>>^ For the one finding me will certainly find life, and gets goodwill from Jehovah.

[[v20-8-36]]

^<<v20-8-36,36>>^ But the one missing me is doing violence to his soul; all those intensely hating me are the ones that do love death.”

'''

xref:020-proverbs/020-proverbs-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbs/020-proverbs-009.adoc#v20-9-0[Próximo Capítulo &#62;]