include::./index.adoc[]

[[v20-11-0]]
=== Proverbs, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-11-1]]

^<<v20-11-1,1>>^ A cheating pair of scales is something detestable to Jehovah, but a complete stone-weight is a pleasure to him.

[[v20-11-2]]

^<<v20-11-2,2>>^ Has presumptuousness come? Then dishonor will come; but wisdom is with the modest ones.

[[v20-11-3]]

^<<v20-11-3,3>>^ The integrity of the upright ones is what leads them, but distortion by those dealing treacherously will despoil them.^&#42;1^

[NOTE]
====
. “Will despoil them,” according to MmarginVg.
====

[[v20-11-4]]

^<<v20-11-4,4>>^ Valuable things will be of no benefit on the day of fury, but righteousness itself will deliver from death.

[[v20-11-5]]

^<<v20-11-5,5>>^ The righteousness of the blameless one is what will make his way straight, but in his own wickedness the wicked one will fall.

[[v20-11-6]]

^<<v20-11-6,6>>^ The righteousness of the upright ones is what will deliver them, but by their^&#42;1^ craving^&#42;2^ those dealing treacherously will themselves be caught.

[NOTE]
====
. “Their,” TLXXSyVg; M omits.
. “Destruction,” LXX.
====

[[v20-11-7]]

^<<v20-11-7,7>>^ When a wicked man^&#42;1^ dies, &#91;his&#93; hope perishes; and even expectation &#91;based&#93; on powerfulness has perished.

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v20-11-8]]

^<<v20-11-8,8>>^ The righteous is the one rescued even from distress, and the wicked one comes in instead of him.

[[v20-11-9]]

^<<v20-11-9,9>>^ By &#91;his&#93; mouth the one who is an apostate brings his fellowman to ruin, but by knowledge are the righteous rescued.

[[v20-11-10]]

^<<v20-11-10,10>>^ Because of the goodness of the righteous ones a town is elated, but when the wicked ones perish there is a joyful cry.

[[v20-11-11]]

^<<v20-11-11,11>>^ Because of the blessing of the upright ones a town is exalted, but because of the mouth of the wicked ones it gets torn down.

[[v20-11-12]]

^<<v20-11-12,12>>^ The one in want of heart^&#42;1^ has despised his own fellowman, but the man^&#42;2^ of broad discernment is one that keeps silent.

[NOTE]
====
. Or, “lacking good motive.” Heb., chasar-levʹ.
. “But the man of.” Heb., weʼishʹ.
====

[[v20-11-13]]

^<<v20-11-13,13>>^ The one walking about as a slanderer is uncovering confidential talk, but the one faithful in spirit^&#42;1^ is covering over a matter.

[NOTE]
====
. “Spirit.” Heb., ruʹach; Gr., pno·eiʹ, “breath”; Lat., aʹni·mi.
====

[[v20-11-14]]

^<<v20-11-14,14>>^ When there is no skillful direction, the people fall; but there is salvation in the multitude of counselors.

[[v20-11-15]]

^<<v20-11-15,15>>^ One will positively fare badly because he has gone surety for a stranger, but the one hating handshaking is keeping carefree.

[[v20-11-16]]

^<<v20-11-16,16>>^ A woman of charm is the one that takes hold of glory;^&#42;1^ but the tyrants, for their part, take hold of riches.

[NOTE]
====
. Or, “honor.”
====

[[v20-11-17]]

^<<v20-11-17,17>>^ A man of loving-kindness^&#42;1^ is dealing rewardingly with his own soul, but the cruel person is bringing ostracism upon his own organism.

[NOTE]
====
. Or, “loyal love.”
====

[[v20-11-18]]

^<<v20-11-18,18>>^ The wicked one is making false wages,^&#42;1^ but the one sowing righteousness, true earnings.^&#42;2^

[NOTE]
====
. “False wages,” that is, the reward for bad activity. Heb., pheʽul·lath-shaʹqer.
. “True earnings,” that is, the reward for good activity. Heb., seʹkher ʼemethʹ.
====

[[v20-11-19]]

^<<v20-11-19,19>>^ The one firmly standing for righteousness^&#42;1^ is in line for life, but the one chasing after what is bad is in line for his own death.

[NOTE]
====
. “The one firmly standing for righteousness,” by a correction of M; T, “Thus whoever does righteousness”; LXXSy (reading ben for ken), “A son of righteousness (righteous son).”
====

[[v20-11-20]]

^<<v20-11-20,20>>^ Those crooked at heart are something detestable to Jehovah, but the ones blameless in &#91;their&#93; way are a pleasure to him.

[[v20-11-21]]

^<<v20-11-21,21>>^ Though hand be to hand, a bad person will not go unpunished; but the offspring of the righteous ones will certainly escape.

[[v20-11-22]]

^<<v20-11-22,22>>^ As a gold nose ring in the snout of a pig, so is a woman that is pretty but that is turning away from sensibleness.^&#42;1^

[NOTE]
====
. Or, “tastefulness; good taste.”
====

[[v20-11-23]]

^<<v20-11-23,23>>^ The desire of the righteous ones is surely good; the hope of the wicked ones is fury.

[[v20-11-24]]

^<<v20-11-24,24>>^ There exists the one that is scattering and yet is being increased; also the one that is keeping back from what is right, but it results only in want.

[[v20-11-25]]

^<<v20-11-25,25>>^ The generous soul^&#42;1^ will itself be made fat, and the one freely watering &#91;others&#93; will himself also be freely watered.

[NOTE]
====
. Lit., “The soul with a blessing gift.”
====

[[v20-11-26]]

^<<v20-11-26,26>>^ The one holding back grain—the populace will execrate him, but there is a blessing for the head of the one letting it be bought.

[[v20-11-27]]

^<<v20-11-27,27>>^ He that is looking for good will keep seeking goodwill; but as for the one searching for bad, it will come upon him.

[[v20-11-28]]

^<<v20-11-28,28>>^ The one trusting in his riches—he himself will fall; but just like foliage the righteous ones will flourish.

[[v20-11-29]]

^<<v20-11-29,29>>^ As for anyone bringing ostracism upon his own house, he will take possession of wind; and a foolish person will be a servant to the one wise in heart.

[[v20-11-30]]

^<<v20-11-30,30>>^ The fruitage of the righteous one is a tree of life, and he that is winning souls is wise.

[[v20-11-31]]

^<<v20-11-31,31>>^ Look! The righteous one—in the earth he will be rewarded. How much more should the wicked one and the sinner be!

'''

xref:020-proverbs/020-proverbs-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbs/020-proverbs-012.adoc#v20-12-0[Próximo Capítulo &#62;]