include::./index.adoc[]

[[v20-4-0]]
=== Proverbs, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-4-1]]

^<<v20-4-1,1>>^ Listen, O sons, to the discipline of a father and pay attention, so as to know understanding.

[[v20-4-2]]

^<<v20-4-2,2>>^ For good instruction is what I certainly shall give to YOU. My law DO not leave.

[[v20-4-3]]

^<<v20-4-3,3>>^ For I proved to be a real son to my father, tender and the only one before my mother.

[[v20-4-4]]

^<<v20-4-4,4>>^ And he would instruct me and say to me: “May your heart keep fast hold of my words. Keep my commandments and continue living.

[[v20-4-5]]

^<<v20-4-5,5>>^ Acquire wisdom, acquire understanding. Do not forget, and do not turn aside from the sayings of my mouth.

[[v20-4-6]]

^<<v20-4-6,6>>^ Do not leave it,^&#42;1^ and it will keep you. Love it, and it will safeguard you.

[NOTE]
====
. Or, “her,” referring to “wisdom.”
====

[[v20-4-7]]

^<<v20-4-7,7>>^ Wisdom is the prime thing. Acquire wisdom; and with all that you acquire, acquire understanding.

[[v20-4-8]]

^<<v20-4-8,8>>^ Highly esteem it, and it will exalt you. It will glorify you because you embrace it.

[[v20-4-9]]

^<<v20-4-9,9>>^ To your head it will give a wreath of charm; a crown of beauty it will bestow upon you.”

[[v20-4-10]]

^<<v20-4-10,10>>^ Hear, my son, and accept my sayings. Then for you the years of life will become many.^&#42;1^

[NOTE]
====
. Or, “And they [the sayings of mine] will become many for you during the years of life.”
====

[[v20-4-11]]

^<<v20-4-11,11>>^ I will instruct you even in the way of wisdom; I will cause you to tread in the tracks of uprightness.

[[v20-4-12]]

^<<v20-4-12,12>>^ When you walk, your pace will not be cramped; and if you run, you will not stumble.

[[v20-4-13]]

^<<v20-4-13,13>>^ Take hold on discipline; do not let go.^&#42;1^ Safeguard it,^&#42;2^ for it itself is your life.

[NOTE]
====
. Or, “do not let [it] alone.”
. Or, “her.” See vs 6 ftn.
====

[[v20-4-14]]

^<<v20-4-14,14>>^ Into the path of the wicked ones do not enter, and do not walk straight on into the way of the bad ones.

[[v20-4-15]]

^<<v20-4-15,15>>^ Shun it, do not pass along by it; turn aside from it, and pass along.

[[v20-4-16]]

^<<v20-4-16,16>>^ For they do not sleep unless they do badness, and their sleep has been snatched away unless they cause someone to stumble.

[[v20-4-17]]

^<<v20-4-17,17>>^ For they have fed themselves with the bread of wickedness, and the wine of acts of violence is what they drink.

[[v20-4-18]]

^<<v20-4-18,18>>^ But the path of the righteous ones is like the bright light that is getting lighter and lighter until the day is firmly established.

[[v20-4-19]]

^<<v20-4-19,19>>^ The way of the wicked ones is like the gloom; they have not known at what they keep stumbling.

[[v20-4-20]]

^<<v20-4-20,20>>^ My son, to my words do pay attention. To my sayings incline your ear.

[[v20-4-21]]

^<<v20-4-21,21>>^ May they not get away from your eyes. Keep them in the midst of your heart.

[[v20-4-22]]

^<<v20-4-22,22>>^ For they are life to those finding them and health to all their flesh.

[[v20-4-23]]

^<<v20-4-23,23>>^ More than all else that is to be guarded, safeguard your heart, for out of it are the sources of life.

[[v20-4-24]]

^<<v20-4-24,24>>^ Remove from yourself the crookedness of speech;^&#42;1^ and the deviousness of lips put far away from yourself.

[NOTE]
====
. Lit., “mouth.”
====

[[v20-4-25]]

^<<v20-4-25,25>>^ As for your eyes, straight ahead they should look, yes, your own beaming eyes should gaze straight in front of you.

[[v20-4-26]]

^<<v20-4-26,26>>^ Smooth out the course of your foot,^&#42;1^ and may all your own ways be firmly established.

[NOTE]
====
. “Make straight paths for your feet,” LXX. Compare Heb 12:13.
====

[[v20-4-27]]

^<<v20-4-27,27>>^ Do not incline to the right hand or to the left. Remove your foot from what is bad.

'''

xref:020-proverbs/020-proverbs-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbs/020-proverbs-005.adoc#v20-5-0[Próximo Capítulo &#62;]