include::./index.adoc[]

[[v20-25-0]]
=== Proverbs, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-25-1]]

^<<v20-25-1,1>>^ These also are the proverbs of Solʹo·mon that the men of Hez·e·kiʹah the king of Judah transcribed:

[[v20-25-2]]

^<<v20-25-2,2>>^ The glory of God is the keeping of a matter secret, and the glory of kings is the searching through a matter.

[[v20-25-3]]

^<<v20-25-3,3>>^ The heavens for height and the earth for depth, and the heart of kings, that is unsearchable.

[[v20-25-4]]

^<<v20-25-4,4>>^ Let there be a removing^&#42;1^ of scummy dross from the silver, and all of it will come forth refined.^&#42;2^

[NOTE]
====
. “Let there be a removing.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. “All of it will come forth refined,” by slight changes in M and in agreement with LXX; M, “a vessel will come forth for the refiner.”
====

[[v20-25-5]]

^<<v20-25-5,5>>^ Let there be the removing of the wicked one before the king, and his throne will be firmly established by righteousness itself.

[[v20-25-6]]

^<<v20-25-6,6>>^ Do not do yourself honor before the king, and in the place of great ones do not stand.

[[v20-25-7]]

^<<v20-25-7,7>>^ For it is better &#91;for him&#93; to say to you: “Come up here,” than to abase you before a noble whom your eyes have seen.

[[v20-25-8]]

^<<v20-25-8,8>>^ Do not go forth to conduct a legal case hastily, that it may not be a question of what you will do in the culmination of it when your fellowman now humiliates you.

[[v20-25-9]]

^<<v20-25-9,9>>^ Plead your own cause with your fellowman, and do not reveal the confidential talk of another;

[[v20-25-10]]

^<<v20-25-10,10>>^ that the one listening may not put you to shame and the bad report by you can have no recall.

[[v20-25-11]]

^<<v20-25-11,11>>^ As apples of gold in silver carvings is a word spoken at the right time for it.

[[v20-25-12]]

^<<v20-25-12,12>>^ An earring of gold, and an ornament of special gold,^&#42;1^ is a wise reprover upon the hearing ear.

[NOTE]
====
. “Special gold.” Heb., khaʹthem, an Egyptian loanword.
====

[[v20-25-13]]

^<<v20-25-13,13>>^ Just like the coolness of snow in the day of harvest is the faithful envoy to those sending^&#42;1^ him, for he restores the very soul^&#42;2^ of his masters.^&#42;3^

[NOTE]
====
. Or, “the one sending,” pl. in M, to denote excellence.
. Or, “for . . . the very life.” Heb., weneʹphesh.
. Or, “his master.” Heb., ʼadho·navʹ, pl., possibly to denote excellence.
====

[[v20-25-14]]

^<<v20-25-14,14>>^ As vaporous clouds and a wind without any downpour is a man^&#42;1^ boasting himself about a gift in falsehood.

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v20-25-15]]

^<<v20-25-15,15>>^ By patience^&#42;1^ a commander is induced, and a mild tongue itself can break a bone.

[NOTE]
====
. Lit., “In length (slowness) of nostrils (anger).”
====

[[v20-25-16]]

^<<v20-25-16,16>>^ Is it honey that you have found? Eat what is sufficient for you, that you may not take too much of it and have to vomit it up.

[[v20-25-17]]

^<<v20-25-17,17>>^ Make your foot rare at the house of your fellowman, that he may not have his sufficiency of you and certainly hate you.

[[v20-25-18]]

^<<v20-25-18,18>>^ As a war club and a sword and a sharpened arrow is a man testifying against his fellowman as a false witness.

[[v20-25-19]]

^<<v20-25-19,19>>^ As a broken tooth and a wobbling foot is the confidence in one proving treacherous in the day of distress.

[[v20-25-20]]

^<<v20-25-20,20>>^ He that is removing a garment on a cold day is as vinegar upon alkali and as a singer with songs upon a gloomy heart.

[[v20-25-21]]

^<<v20-25-21,21>>^ If the one hating you is hungry, give him bread to eat; and if he is thirsty, give him water to drink.

[[v20-25-22]]

^<<v20-25-22,22>>^ For coals are what you are raking together upon his head, and Jehovah himself will reward you.

[[v20-25-23]]

^<<v20-25-23,23>>^ The wind from the north brings forth as with labor pains a downpour; and a tongue &#91;giving away&#93; a secret, a denounced face.

[[v20-25-24]]

^<<v20-25-24,24>>^ Better is it to dwell upon a corner of a roof than with a contentious wife, although in a house in common.

[[v20-25-25]]

^<<v20-25-25,25>>^ As cold water upon a tired soul, so is a good report from a distant land.

[[v20-25-26]]

^<<v20-25-26,26>>^ A fouled spring and a ruined well is the righteous one when staggering before the wicked one.

[[v20-25-27]]

^<<v20-25-27,27>>^ The eating of too much honey is not good; and for people to search out their own glory, is it glory?

[[v20-25-28]]

^<<v20-25-28,28>>^ As a city broken through, without a wall, is the man that has no restraint for his spirit.

'''

xref:020-proverbs/020-proverbs-024.adoc#v20-24-0[&#60; Capítulo Anterior] | <<v20-25-0,Topo>> | xref:020-proverbs/020-proverbs-026.adoc#v20-26-0[Próximo Capítulo &#62;]