include::./index.adoc[]

[[v20-23-0]]
=== Proverbs, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-23-1]]

^<<v20-23-1,1>>^ In case you should sit down to feed yourself with a king, you should diligently consider what is before you,

[[v20-23-2]]

^<<v20-23-2,2>>^ and you must put a knife to your throat if you are the owner of soul&#91;ful desire&#93;.^&#42;1^

[NOTE]
====
. Lit., “soul.” Heb., neʹphesh; Lat., aʹni·mam.
====

[[v20-23-3]]

^<<v20-23-3,3>>^ Do not show yourself craving his tasty dishes, as it is the food of lies.

[[v20-23-4]]

^<<v20-23-4,4>>^ Do not toil to gain riches. Cease from your own understanding.

[[v20-23-5]]

^<<v20-23-5,5>>^ Have you caused your eyes to glance at it, when it is nothing? For without fail it makes wings for itself like those of an eagle and flies away toward the heavens.

[[v20-23-6]]

^<<v20-23-6,6>>^ Do not feed yourself with the food of anyone of ungenerous eye,^&#42;1^ nor show yourself craving his tasty dishes.

[NOTE]
====
. Lit., “evil as to eye.” Heb., raʽ ʽaʹyin.
====

[[v20-23-7]]

^<<v20-23-7,7>>^ For as one that has calculated within his soul, so he is. “Eat and drink,” he says to you, but his heart itself is not with you.

[[v20-23-8]]

^<<v20-23-8,8>>^ Your morsel that you have eaten, you will vomit it out, and you will have wasted your pleasant words.

[[v20-23-9]]

^<<v20-23-9,9>>^ Into the ears of a stupid one do not speak, for he will despise your discreet words.

[[v20-23-10]]

^<<v20-23-10,10>>^ Do not move back the boundary of long ago, and into the field of fatherless boys do not enter.

[[v20-23-11]]

^<<v20-23-11,11>>^ For their Redeemer^&#42;1^ is strong; he himself will plead their cause with you.

[NOTE]
====
. “Their Redeemer (Repurchaser).” By extension of thought, “their Avenger (Vindicator).” Heb., gho·ʼalamʹ. See Job 19:25 and Ps 19:14 ftns.
====

[[v20-23-12]]

^<<v20-23-12,12>>^ Do bring your heart to discipline and your ear to the sayings of knowledge.

[[v20-23-13]]

^<<v20-23-13,13>>^ Do not hold back discipline from the mere boy. In case you beat him with the rod, he will not die.

[[v20-23-14]]

^<<v20-23-14,14>>^ With the rod you yourself should beat him, that you may deliver his very soul from Sheʹol^&#42;1^ itself.

[NOTE]
====
. “From Sheol.” Heb., mish·sheʼohlʹ; LXX, “death”; Syr., shiul; Lat., in·ferʹno. See App 4B.
====

[[v20-23-15]]

^<<v20-23-15,15>>^ My son, if your heart has become wise, my heart will rejoice, even mine.

[[v20-23-16]]

^<<v20-23-16,16>>^ And my kidneys^&#42;1^ will exult when your lips speak uprightness.

[NOTE]
====
. Or, “my deepest emotions.” Heb., khil·yoh·thaiʹ.
====

[[v20-23-17]]

^<<v20-23-17,17>>^ Let your heart not be envious of sinners, but be in the fear of Jehovah all day long.

[[v20-23-18]]

^<<v20-23-18,18>>^ For in that case there will exist a future, and your own hope will not be cut off.

[[v20-23-19]]

^<<v20-23-19,19>>^ You, O my son, hear and become wise, and lead your heart on in the way.

[[v20-23-20]]

^<<v20-23-20,20>>^ Do not come to be among heavy drinkers of wine, among those who are gluttonous eaters of flesh.

[[v20-23-21]]

^<<v20-23-21,21>>^ For a drunkard and a glutton will come to poverty, and drowsiness will clothe one with mere rags.

[[v20-23-22]]

^<<v20-23-22,22>>^ Listen to your father who caused your birth, and do not despise your mother just because she has grown old.

[[v20-23-23]]

^<<v20-23-23,23>>^ Buy truth itself and do not sell it—wisdom and discipline and understanding.

[[v20-23-24]]

^<<v20-23-24,24>>^ The father of a righteous one will without fail be joyful; the one becoming father to a wise one will also rejoice in him.

[[v20-23-25]]

^<<v20-23-25,25>>^ Your father and your mother will rejoice, and she that gave birth to you will be joyful.

[[v20-23-26]]

^<<v20-23-26,26>>^ My son, do give your heart to me, and may those eyes of yours take pleasure in my own ways.

[[v20-23-27]]

^<<v20-23-27,27>>^ For a prostitute is a deep pit and a foreign woman is a narrow well.

[[v20-23-28]]

^<<v20-23-28,28>>^ Surely she, just like a robber, lies in wait; and among men she increases the treacherous ones.

[[v20-23-29]]

^<<v20-23-29,29>>^ Who has woe? Who has uneasiness? Who has contentions? Who has concern? Who has wounds for no reason? Who has dullness of eyes?

[[v20-23-30]]

^<<v20-23-30,30>>^ Those staying a long time with the wine, those coming in to search out mixed wine.

[[v20-23-31]]

^<<v20-23-31,31>>^ Do not look at wine when it exhibits a red color, when it gives off its sparkle in the cup, &#91;when&#93; it goes with a slickness.

[[v20-23-32]]

^<<v20-23-32,32>>^ At its end it bites just like a serpent, and it secretes poison just like a viper.

[[v20-23-33]]

^<<v20-23-33,33>>^ Your own eyes will see strange things,^&#42;1^ and your own heart will speak perverse things.

[NOTE]
====
. Or, “strange women.”
====

[[v20-23-34]]

^<<v20-23-34,34>>^ And you will certainly become like one lying down in the heart of the sea, even like one lying down at the top of a mast.

[[v20-23-35]]

^<<v20-23-35,35>>^ “They have struck me, but I did not become sick; they have smitten me, but I did not know it. When shall I wake up? I shall seek it yet some more.”

'''

xref:020-proverbs/020-proverbs-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbs/020-proverbs-024.adoc#v20-24-0[Próximo Capítulo &#62;]