include::./index.adoc[]

[[v20-18-0]]
=== Proverbs, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-18-1]]

^<<v20-18-1,1>>^ One isolating himself will seek &#91;his own&#93; selfish longing; against all practical wisdom he will break forth.

[[v20-18-2]]

^<<v20-18-2,2>>^ Anyone stupid finds no delight in discernment, except that his heart should uncover itself.

[[v20-18-3]]

^<<v20-18-3,3>>^ When a wicked one comes in, contempt also must come in; and along with dishonor there is reproach.

[[v20-18-4]]

^<<v20-18-4,4>>^ The words of a man’s mouth are deep waters. The well of wisdom is a torrent bubbling forth.

[[v20-18-5]]

^<<v20-18-5,5>>^ The showing of partiality to the wicked one is not good, nor the turning aside of the righteous one in judgment.

[[v20-18-6]]

^<<v20-18-6,6>>^ The lips of one who is stupid enter into quarreling, and his very mouth calls even for strokes.

[[v20-18-7]]

^<<v20-18-7,7>>^ The mouth of the stupid one is the ruin of him, and his lips are a snare for his soul.

[[v20-18-8]]

^<<v20-18-8,8>>^ The words of the slanderer are like things to be swallowed greedily, which do go down into the innermost parts of the belly.

[[v20-18-9]]

^<<v20-18-9,9>>^ Also, the one showing himself slack in his work—he is a brother to the one causing ruin.^&#42;1^

[NOTE]
====
. Lit., “to the lord of ruin.”
====

[[v20-18-10]]

^<<v20-18-10,10>>^ The name of Jehovah is a strong tower. Into it the righteous runs and is given protection.^&#42;1^

[NOTE]
====
. Lit., “is put on high,” that is, out of reach, safe.
====

[[v20-18-11]]

^<<v20-18-11,11>>^ The valuable things of the rich are his strong town, and they are like a protective wall in his imagination.

[[v20-18-12]]

^<<v20-18-12,12>>^ Before a crash the heart of a man is lofty, and before glory there is humility.

[[v20-18-13]]

^<<v20-18-13,13>>^ When anyone is replying to a matter before he hears &#91;it&#93;, that is foolishness on his part and a humiliation.

[[v20-18-14]]

^<<v20-18-14,14>>^ The spirit of a man^&#42;1^ can put up with his malady; but as for a stricken spirit, who can bear it?

[NOTE]
====
. “The spirit of a man.” Heb., ru·ach-ʼishʹ.
====

[[v20-18-15]]

^<<v20-18-15,15>>^ The heart of the understanding one acquires knowledge, and the ear of wise ones seeks to find knowledge.

[[v20-18-16]]

^<<v20-18-16,16>>^ A man’s gift^&#42;1^ will make a large opening for him, and it will lead him even before great people.

[NOTE]
====
. Lit., “A gift of an earthling man.” Heb., mat·tanʹ ʼa·dhamʹ.
====

[[v20-18-17]]

^<<v20-18-17,17>>^ The one first in his legal case is righteous; his fellow comes in and certainly searches him through.

[[v20-18-18]]

^<<v20-18-18,18>>^ The lot puts even contentions to rest, and it separates even the mighty from one another.

[[v20-18-19]]

^<<v20-18-19,19>>^ A brother who is transgressed against is more than a strong town; and there are contentions that are like the bar of a dwelling tower.

[[v20-18-20]]

^<<v20-18-20,20>>^ From the fruitage of a man’s^&#42;1^ mouth his belly will be satisfied; he will be satisfied even with the produce of his lips.

[NOTE]
====
. “Man’s.” Heb., ʼish.
====

[[v20-18-21]]

^<<v20-18-21,21>>^ Death and life are in the power^&#42;1^ of the tongue, and he that is loving it will eat its fruitage.

[NOTE]
====
. Lit., “in [the] hand of.” Heb., beyadhʹ.
====

[[v20-18-22]]

^<<v20-18-22,22>>^ Has one found a &#91;good&#93;^&#42;1^ wife? One has found a good thing, and one gets goodwill from Jehovah.

[NOTE]
====
. “Good,” LXXSyVgc and one Heb. ms; M omits.
====

[[v20-18-23]]

^<<v20-18-23,23>>^ Entreaties the one of little means speaks out, but one that is rich answers in a strong way.

[[v20-18-24]]

^<<v20-18-24,24>>^ There exist^&#42;1^ companions disposed to break one another to pieces, but there exists a friend sticking closer than a brother.

[NOTE]
====
. “There exist,” TSy; M, “A man of.”
====

'''

xref:020-proverbs/020-proverbs-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbs/020-proverbs-019.adoc#v20-19-0[Próximo Capítulo &#62;]