include::./index.adoc[]

[[v20-26-0]]
=== Proverbs, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-26-1]]

^<<v20-26-1,1>>^ Like snow in summer and like rain in harvesttime, so glory is not fitting for a stupid one.

[[v20-26-2]]

^<<v20-26-2,2>>^ Just as a bird has cause for fleeing &#91;and&#93; just as a swallow for flying, so a malediction itself does not come without real cause.

[[v20-26-3]]

^<<v20-26-3,3>>^ A whip is for the horse, a bridle is for the ass, and the rod is for the back of stupid people.

[[v20-26-4]]

^<<v20-26-4,4>>^ Do not answer anyone stupid according to his foolishness, that you yourself also may not become equal to him.

[[v20-26-5]]

^<<v20-26-5,5>>^ Answer someone stupid according to his foolishness, that he may not become someone wise in his own eyes.

[[v20-26-6]]

^<<v20-26-6,6>>^ As one that is mutilating &#91;his&#93; feet, as one that is drinking mere violence, is he that is thrusting matters into the hand of someone stupid.

[[v20-26-7]]

^<<v20-26-7,7>>^ Have the legs of the lame one drawn up water? Then there is a proverb in the mouth of stupid people.

[[v20-26-8]]

^<<v20-26-8,8>>^ Like one shutting up a stone in a heap of stones, so is the one giving glory to a mere stupid one.

[[v20-26-9]]

^<<v20-26-9,9>>^ As a thorny weed has come up into the hand of a drunkard, so a proverb into the mouth of stupid people.

[[v20-26-10]]

^<<v20-26-10,10>>^ As an archer piercing everything is the one hiring someone stupid or the one hiring passersby.

[[v20-26-11]]

^<<v20-26-11,11>>^ Just like a dog returning to its vomit, the stupid one is repeating his foolishness.

[[v20-26-12]]

^<<v20-26-12,12>>^ Have you seen a man wise in his own eyes? There is more hope for the stupid one than for him.

[[v20-26-13]]

^<<v20-26-13,13>>^ The lazy one has said: “There is a young lion in the way, a lion in among the public squares.”

[[v20-26-14]]

^<<v20-26-14,14>>^ A door keeps turning upon its pivot, and the lazy one upon his couch.

[[v20-26-15]]

^<<v20-26-15,15>>^ The lazy one has hidden his hand in the banquet bowl; he has become too weary to bring it back to his mouth.

[[v20-26-16]]

^<<v20-26-16,16>>^ The lazy one is wiser in his own eyes than seven giving a sensible reply.

[[v20-26-17]]

^<<v20-26-17,17>>^ As one grabbing hold of the ears of a dog is anyone passing by that is becoming furious at the quarrel that is not his.

[[v20-26-18]]

^<<v20-26-18,18>>^ Just like someone mad that is shooting fiery missiles, arrows and death,

[[v20-26-19]]

^<<v20-26-19,19>>^ so is the man that has tricked his fellowman and has said: “Was I not having fun?”

[[v20-26-20]]

^<<v20-26-20,20>>^ Where there is no wood the fire goes out, and where there is no slanderer contention grows still.

[[v20-26-21]]

^<<v20-26-21,21>>^ As charcoal for the embers and wood for the fire, so is a contentious man for causing a quarrel to glow.

[[v20-26-22]]

^<<v20-26-22,22>>^ The words of a slanderer are like things to be swallowed greedily, which do go down into the innermost parts of the belly.

[[v20-26-23]]

^<<v20-26-23,23>>^ As a silver glazing overlaid upon a fragment of earthenware are fervent lips along with a bad heart.

[[v20-26-24]]

^<<v20-26-24,24>>^ With his lips the hater makes himself unrecognizable, but inside of him he puts deception.

[[v20-26-25]]

^<<v20-26-25,25>>^ Although he makes his voice gracious, do not believe in him, for there are seven detestable things in his heart.

[[v20-26-26]]

^<<v20-26-26,26>>^ Hatred is covered over by deceit. His badness will be uncovered in the congregation.

[[v20-26-27]]

^<<v20-26-27,27>>^ He that is excavating a pit will fall into the same, and he that is rolling away a stone—back to him it will return.

[[v20-26-28]]

^<<v20-26-28,28>>^ A tongue that is false hates the one crushed by it, and a flattering mouth^&#42;1^ causes an overthrow.

[NOTE]
====
. Lit., “and a mouth smooth.”
====

'''

xref:020-proverbs/020-proverbs-025.adoc#v20-25-0[&#60; Capítulo Anterior] | <<v20-26-0,Topo>> | xref:020-proverbs/020-proverbs-027.adoc#v20-27-0[Próximo Capítulo &#62;]