include::./index.adoc[]

[[v20-16-0]]
=== Proverbs, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-16-1]]

^<<v20-16-1,1>>^ To earthling man^&#42;1^ belong the arrangings of the heart, but from Jehovah is the answer of the tongue.

[NOTE]
====
. “To earthling man.” Heb., leʼa·dhamʹ.
====

[[v20-16-2]]

^<<v20-16-2,2>>^ All the ways of a man^&#42;1^ are pure in his own eyes, but Jehovah is making an estimate of spirits.

[NOTE]
====
. “All the ways of a man.” Heb., kal-dar·kheh-ʼishʹ.
====

[[v20-16-3]]

^<<v20-16-3,3>>^ Roll your works upon Jehovah himself and your plans will be firmly established.

[[v20-16-4]]

^<<v20-16-4,4>>^ Everything Jehovah has made for his purpose, yes, even the wicked one for the evil day.

[[v20-16-5]]

^<<v20-16-5,5>>^ Everyone that is proud in heart is something detestable to Jehovah. Hand &#91;may join&#93; to hand, &#91;yet&#93; one will not be free from punishment.

[[v20-16-6]]

^<<v20-16-6,6>>^ By loving-kindness^&#42;1^ and trueness error is atoned for, and in the fear of Jehovah one turns away from bad.

[NOTE]
====
. Or, “loyal love.”
====

[[v20-16-7]]

^<<v20-16-7,7>>^ When Jehovah takes pleasure in the ways of a man he causes even his enemies themselves to be at peace with him.

[[v20-16-8]]

^<<v20-16-8,8>>^ Better is a little with righteousness than an abundance of products without justice.^&#42;1^

[NOTE]
====
. Or, “judgment.”
====

[[v20-16-9]]

^<<v20-16-9,9>>^ The heart of earthling man may think out his way, but Jehovah himself does the directing of his steps.

[[v20-16-10]]

^<<v20-16-10,10>>^ Inspired decision should be upon the lips of a king; in judgment his mouth should not prove unfaithful.

[[v20-16-11]]

^<<v20-16-11,11>>^ The just indicator and scales belong to Jehovah; all the stone weights of the bag are his work.

[[v20-16-12]]

^<<v20-16-12,12>>^ The doing of wickedness is something detestable to kings, for by righteousness is the throne firmly established.

[[v20-16-13]]

^<<v20-16-13,13>>^ The lips of righteousness are a pleasure to a grand king;^&#42;1^ and the speaker of upright things he loves.

[NOTE]
====
. “A grand king.” Lit., “kings,” pl. to denote majesty, as in vs 12.
====

[[v20-16-14]]

^<<v20-16-14,14>>^ The rage of a king means messengers of death, but the wise man is one that averts it.^&#42;1^

[NOTE]
====
. Lit., “he will cover it.” Heb., yekhap·perenʹnah.
====

[[v20-16-15]]

^<<v20-16-15,15>>^ In the light of the king’s face there is life, and his goodwill is like the cloud of spring rain.

[[v20-16-16]]

^<<v20-16-16,16>>^ The getting of wisdom is O how much better than gold! And the getting of understanding is to be chosen more than silver.

[[v20-16-17]]

^<<v20-16-17,17>>^ The highway of the upright ones is to turn away from bad. One who is safeguarding his way is keeping his soul.

[[v20-16-18]]

^<<v20-16-18,18>>^ Pride is before a crash, and a haughty spirit^&#42;1^ before stumbling.

[NOTE]
====
. Lit., “height (haughtiness) of spirit.” Heb., goʹvah ruʹach.
====

[[v20-16-19]]

^<<v20-16-19,19>>^ Better is it to be lowly in spirit^&#42;1^ with the meek ones^&#42;2^ than to divide spoil with the self-exalted ones.

[NOTE]
====
. Lit., “lowness of spirit.” Heb., shephal-ruʹach.
. “Meek ones,” Mmargin; M, “afflicted ones.”
====

[[v20-16-20]]

^<<v20-16-20,20>>^ He that is showing insight in a matter will find good, and happy is he that is trusting in Jehovah.

[[v20-16-21]]

^<<v20-16-21,21>>^ The one that is wise in heart will be called understanding, and he that is sweet in &#91;his&#93; lips adds persuasiveness.

[[v20-16-22]]

^<<v20-16-22,22>>^ To its owners insight is a well of life; and the discipline of the foolish ones is foolishness.

[[v20-16-23]]

^<<v20-16-23,23>>^ The heart of the wise one causes his mouth to show insight, and to his lips it adds persuasiveness.

[[v20-16-24]]

^<<v20-16-24,24>>^ Pleasant sayings are a honeycomb, sweet to the soul and a healing to the bones.

[[v20-16-25]]

^<<v20-16-25,25>>^ There exists a way that is upright before a man, but the ways of death are the end of it afterward.

[[v20-16-26]]

^<<v20-16-26,26>>^ The soul^&#42;1^ of the hard worker has worked hard for him, because his mouth has pressed him hard.

[NOTE]
====
. Or, “soulful desire.”
====

[[v20-16-27]]

^<<v20-16-27,27>>^ A good-for-nothing man^&#42;1^ is digging up what is bad, and upon his lips there is, as it were, a scorching fire.

[NOTE]
====
. Lit., “A man of belial.” Heb., ʼish beli·yaʹʽal.
====

[[v20-16-28]]

^<<v20-16-28,28>>^ A man of intrigues keeps sending forth contention, and a slanderer is separating those familiar with one another.

[[v20-16-29]]

^<<v20-16-29,29>>^ A man of violence will seduce his fellow, and certainly causes him to go in a way that is not good.

[[v20-16-30]]

^<<v20-16-30,30>>^ He is blinking with his eyes to scheme up intrigues. Pinching his lips together, he certainly brings mischief to completion.

[[v20-16-31]]

^<<v20-16-31,31>>^ Gray-headedness is a crown of beauty when it is found in the way of righteousness.

[[v20-16-32]]

^<<v20-16-32,32>>^ He that is slow to anger is better than a mighty man, and he that is controlling his spirit than the one capturing a city.

[[v20-16-33]]

^<<v20-16-33,33>>^ Into the lap the lot is cast down, but every decision by it is from Jehovah.

'''

xref:020-proverbs/020-proverbs-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbs/020-proverbs-017.adoc#v20-17-0[Próximo Capítulo &#62;]