include::./index.adoc[]

[[v20-14-0]]
=== Proverbs, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v20-14-1]]

^<<v20-14-1,1>>^ The truly wise woman has built up her house, but the foolish one tears it down with her own hands.

[[v20-14-2]]

^<<v20-14-2,2>>^ The one walking in his uprightness is fearing Jehovah, but the one crooked in his ways is despising Him.

[[v20-14-3]]

^<<v20-14-3,3>>^ The rod of haughtiness is in the mouth of the foolish one, but the very lips of the wise ones will guard them.

[[v20-14-4]]

^<<v20-14-4,4>>^ Where there are no cattle the manger is clean, but the crop is abundant because of the power of a bull.

[[v20-14-5]]

^<<v20-14-5,5>>^ A faithful witness is one that will not lie, but a false witness launches forth mere lies.

[[v20-14-6]]

^<<v20-14-6,6>>^ The ridiculer has sought to find wisdom, and there is none; but to the understanding one knowledge is an easy thing.

[[v20-14-7]]

^<<v20-14-7,7>>^ Go away from in front of the stupid man, for you will certainly not take note of the lips of knowledge.

[[v20-14-8]]

^<<v20-14-8,8>>^ The wisdom of the shrewd is to understand his way, but the foolishness of stupid ones is deception.

[[v20-14-9]]

^<<v20-14-9,9>>^ Foolish are those who make a derision of guilt, but among the upright ones there is agreement.^&#42;1^

[NOTE]
====
. Or, “approval.”
====

[[v20-14-10]]

^<<v20-14-10,10>>^ The heart is aware of the bitterness of one’s soul, and with its rejoicing no stranger will intermeddle.

[[v20-14-11]]

^<<v20-14-11,11>>^ The house of wicked people will be annihilated, but the tent of the upright ones will flourish.

[[v20-14-12]]

^<<v20-14-12,12>>^ There exists a way that is upright before a man, but the ways of death are the end of it afterward.

[[v20-14-13]]

^<<v20-14-13,13>>^ Even in laughter the heart may be in pain; and grief is what rejoicing ends up in.

[[v20-14-14]]

^<<v20-14-14,14>>^ The one faithless at heart will be satisfied with the results of his own ways, but the good man with the results of his dealings.

[[v20-14-15]]

^<<v20-14-15,15>>^ Anyone inexperienced puts faith in every word,^&#42;1^ but the shrewd one considers his steps.

[NOTE]
====
. Or, “thing.” Heb., da·varʹ.
====

[[v20-14-16]]

^<<v20-14-16,16>>^ The wise one fears and is turning away from badness, but the stupid is becoming furious and self-confident.

[[v20-14-17]]

^<<v20-14-17,17>>^ He that is quick to anger will commit foolishness, but the man of thinking abilities is hated.

[[v20-14-18]]

^<<v20-14-18,18>>^ The inexperienced ones will certainly take possession of foolishness, but the shrewd ones will bear knowledge as a headdress.

[[v20-14-19]]

^<<v20-14-19,19>>^ Bad people will have to bow down before the good ones, and the wicked people at the gates of the righteous one.

[[v20-14-20]]

^<<v20-14-20,20>>^ Even to his fellowman one who is of little means is an object of hatred, but many are the friends of the rich person.

[[v20-14-21]]

^<<v20-14-21,21>>^ The one despising his own fellowman is sinning, but happy is he who is showing favor to the afflicted ones.

[[v20-14-22]]

^<<v20-14-22,22>>^ Will not those devising mischief go wandering about? But there are loving-kindness^&#42;1^ and trueness as regards those devising good.

[NOTE]
====
. Or, “loyal love.”
====

[[v20-14-23]]

^<<v20-14-23,23>>^ By every kind of toil there comes to be an advantage, but merely the word of the lips &#91;tends&#93; to want.

[[v20-14-24]]

^<<v20-14-24,24>>^ The crown of the wise is their riches; the foolishness of the stupid ones is foolishness.

[[v20-14-25]]

^<<v20-14-25,25>>^ A true witness^&#42;1^ is delivering souls, but a deceitful one^&#42;2^ launches forth mere lies.

[NOTE]
====
. Lit., “A witness of truth.” Heb., ʽedh ʼemethʹ.
. Lit., “a deception,” that is, a witness of deception. Heb., mir·mahʹ.
====

[[v20-14-26]]

^<<v20-14-26,26>>^ In the fear of Jehovah there is strong confidence, and for his sons there will come to be a refuge.

[[v20-14-27]]

^<<v20-14-27,27>>^ The fear of Jehovah is a well of life, to turn away from the snares of death.

[[v20-14-28]]

^<<v20-14-28,28>>^ In the multitude of people there is an adornment of a king, but in the lack of population is the ruin of a high official.

[[v20-14-29]]

^<<v20-14-29,29>>^ He that is slow to anger is abundant in discernment, but one that is impatient^&#42;1^ is exalting foolishness.

[NOTE]
====
. Lit., “but one that is short of spirit.” Heb., u·qetsar-ruʹach.
====

[[v20-14-30]]

^<<v20-14-30,30>>^ A calm heart is the life of the fleshly organism, but jealousy is rottenness to the bones.

[[v20-14-31]]

^<<v20-14-31,31>>^ He that is defrauding the lowly one has reproached his Maker, but the one showing favor to the poor one is glorifying Him.

[[v20-14-32]]

^<<v20-14-32,32>>^ Because of his badness the wicked will be pushed down, but the righteous will be finding refuge in his integrity.^&#42;1^

[NOTE]
====
. “Integrity,” by a slight correction of M to agree with LXXSy; M, “death.”
====

[[v20-14-33]]

^<<v20-14-33,33>>^ In the heart of the understanding one there rests wisdom, and in the midst of stupid ones it becomes known.

[[v20-14-34]]

^<<v20-14-34,34>>^ Righteousness is what exalts a nation, but sin is something disgraceful to national groups.

[[v20-14-35]]

^<<v20-14-35,35>>^ The pleasure of a king is in the servant who is acting with insight, but his fury comes to be toward one acting shamefully.

'''

xref:020-proverbs/020-proverbs-013.adoc#v20-13-0[&#60; Capítulo Anterior] | <<v20-14-0,Topo>> | xref:020-proverbs/020-proverbs-015.adoc#v20-15-0[Próximo Capítulo &#62;]