include::./index.adoc[]

[[v24-7-0]]
=== Jeremiah, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-7-1]]

^<<v24-7-1,1>>^ The word that occurred to Jeremiah^&#42;1^ from Jehovah, saying:

[NOTE]
====
. See 1:1 ftn, “Jeremiah.”
====

[[v24-7-2]]

^<<v24-7-2,2>>^ “Stand in the gate of the house of Jehovah, and you must proclaim there this word, and you must say, ‘Hear the word of Jehovah, all YOU of Judah, who are entering into these gates to bow down to Jehovah.

[[v24-7-3]]

^<<v24-7-3,3>>^ This is what Jehovah of armies, the God^&#42;1^ of Israel, has said: “Make YOUR ways and YOUR dealings good, and I will keep YOU people residing in this place.

[NOTE]
====
. “The God of.” Heb., ʼElo·hehʹ.
====

[[v24-7-4]]

^<<v24-7-4,4>>^ Do not put YOUR trust in fallacious words,^&#42;1^ saying, ‘The temple^&#42;2^ of Jehovah, the temple of Jehovah, the temple of Jehovah they are!’

[NOTE]
====
. Lit., “words [or, things] of falsehood.”
. “Temple of.” Heb., heh·khalʹ; Gr., na·osʹ; Lat., temʹplum. Compare 2Ki 20:18 ftn. See Mt 23:16 ftn.
====

[[v24-7-5]]

^<<v24-7-5,5>>^ For if YOU will positively make YOUR ways and YOUR dealings good, if YOU will positively carry out justice between a man^&#42;1^ and his companion,

[NOTE]
====
. “Man.” Heb., ʼish.
====

[[v24-7-6]]

^<<v24-7-6,6>>^ if no alien resident,^&#42;1^ no fatherless boy and no widow YOU will oppress, and innocent blood YOU will not shed in this place, and after other gods^&#42;2^ YOU will not walk for calamity to yourselves,

[NOTE]
====
. Or, “temporary resident.”
. “Gods.” Heb., ʼelo·himʹ.
====

[[v24-7-7]]

^<<v24-7-7,7>>^ I, in turn, shall certainly keep YOU residing in this place, in the land that I gave to YOUR forefathers, from time indefinite even to time indefinite.”’”

[[v24-7-8]]

^<<v24-7-8,8>>^ “Here YOU are putting YOUR trust in fallacious words—it will certainly be of no benefit at all.

[[v24-7-9]]

^<<v24-7-9,9>>^ Can there be stealing, murdering and committing adultery and swearing falsely and making sacrificial smoke to Baʹal and walking after other gods whom YOU had not known,

[[v24-7-10]]

^<<v24-7-10,10>>^ and must YOU come and stand before me in this house upon which my name has been called, and must YOU say, ‘We shall certainly be delivered,’ in the face of doing all these detestable things?

[[v24-7-11]]

^<<v24-7-11,11>>^ Has this house upon which my name has been called become a mere cave of robbers in YOUR eyes? Here I myself also have seen &#91;it&#93;,” is the utterance of Jehovah.

[[v24-7-12]]

^<<v24-7-12,12>>^ “‘However, GO, now, to my place that was in Shiʹloh, where I caused my name to reside at first, and see what I did to it because of the badness of my people Israel.

[[v24-7-13]]

^<<v24-7-13,13>>^ And now for the reason that YOU kept doing all these works,’ is the utterance of Jehovah, ‘and I kept speaking to YOU, getting up early and speaking, but YOU did not listen, and I kept calling YOU, but YOU did not answer,

[[v24-7-14]]

^<<v24-7-14,14>>^ I will do also to the house upon which my name has been called, in which YOU are trusting, and to the place that I gave to YOU and to YOUR forefathers, just as I did to Shiʹloh.

[[v24-7-15]]

^<<v24-7-15,15>>^ And I will throw YOU out from before my face, just as I threw out all YOUR brothers, the whole offspring of Eʹphra·im.’

[[v24-7-16]]

^<<v24-7-16,16>>^ “And as for you, do not pray in behalf of this people, neither raise in their behalf an entreating cry or a prayer nor beseech me, for I shall not be listening to you.

[[v24-7-17]]

^<<v24-7-17,17>>^ Are you not seeing what they are doing in the cities of Judah and in the streets of Jerusalem?

[[v24-7-18]]

^<<v24-7-18,18>>^ The sons are picking up sticks of wood, and the fathers are lighting the fire, and the wives^&#42;1^ are kneading flour dough in order to make sacrificial cakes to the ‘queen^&#42;2^ of the heavens’; and there is a pouring out^&#42;3^ of drink offerings to other gods for the purpose of offending me.

[NOTE]
====
. Or, “women.”
. “To the ‘queen of.’ ” Heb., lim·leʹkheth; LXX, “to the army”; 52 Heb. mss, “to the work (worship) of.”
. “There is a pouring out.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v24-7-19]]

^<<v24-7-19,19>>^ ‘Is it I whom they are offending?’ is the utterance of Jehovah. ‘Is it not they themselves, for the purpose of shame to their faces?’

[[v24-7-20]]

^<<v24-7-20,20>>^ Therefore this is what the Sovereign Lord Jehovah has said, ‘Look! My anger and my rage are being poured forth upon this place, upon mankind^&#42;1^ and upon domestic animal, and upon the tree of the field and upon the fruitage of the ground; and it must burn, and it will not be extinguished.’

[NOTE]
====
. Or, “the earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v24-7-21]]

^<<v24-7-21,21>>^ “This is what Jehovah of armies, the God^&#42;1^ of Israel, has said, ‘Add those whole burnt offerings of YOURS to YOUR sacrifices and eat flesh.

[NOTE]
====
. See vs 3 ftn.
====

[[v24-7-22]]

^<<v24-7-22,22>>^ For I did not speak with YOUR forefathers, nor did I command them in the day of my bringing them out from the land of Egypt concerning the matters of whole burnt offering and sacrifice.

[[v24-7-23]]

^<<v24-7-23,23>>^ But this word I did express in command upon them, saying: “Obey my voice, and I will become YOUR God, and YOU yourselves will become my people; and YOU must walk in all the way that I shall command YOU, in order that it may go well with YOU.”’

[[v24-7-24]]

^<<v24-7-24,24>>^ But they did not listen, neither did they incline their ear, but they went walking in the counsels in the stubbornness of their bad heart, so that they became backward in direction and not forward,

[[v24-7-25]]

^<<v24-7-25,25>>^ from the day that YOUR forefathers came forth out of the land of Egypt until this day; and I kept sending to YOU all my servants the prophets, daily getting up early and sending &#91;them&#93;.

[[v24-7-26]]

^<<v24-7-26,26>>^ But they did not listen to me, and they did not incline their ear, but they kept hardening their neck. They acted worse than their forefathers!

[[v24-7-27]]

^<<v24-7-27,27>>^ “And you must speak to them all these words, but they will not listen to you; and you must call to them, but they will not answer you.

[[v24-7-28]]

^<<v24-7-28,28>>^ And you must say to them, ‘This is the nation whose people have not obeyed the voice of Jehovah its God, and have not taken discipline. Faithfulness has perished, and it has been cut off from their mouth.’

[[v24-7-29]]

^<<v24-7-29,29>>^ “Shear off your^&#42;1^ uncut hair^&#42;2^ and throw &#91;it&#93; away, and upon the bare hills raise a dirge, for Jehovah has rejected and will desert the generation with which he is furious.^&#42;3^

[NOTE]
====
. “Your,” fem. sing., addressed to Zion, or Jerusalem.
. “Your uncut (dedicated) hair.” Heb., niz·rekhʹ.
. Lit., “generation of his fury.”
====

[[v24-7-30]]

^<<v24-7-30,30>>^ ‘For the sons of Judah have done what is bad in my eyes,’ is the utterance of Jehovah. ‘They have set their disgusting things in the house upon which my name has been called, in order to defile it.

[[v24-7-31]]

^<<v24-7-31,31>>^ And they have built the high places of Toʹpheth, which is in the valley of the son of Hinʹnom,^&#42;1^ in order to burn their sons and their daughters in the fire, a thing that I had not commanded and that had not come up into my heart.’

[NOTE]
====
. “In the valley of the son of Hinnom.” Heb., beghehʼʹ ven-Hin·nomʹ; Gr., en phaʹrag·gi hui·ouʹ En·nomʹ; Lat., in valʹle fiʹli·i Enʹnom. See App 4C.
====

[[v24-7-32]]

^<<v24-7-32,32>>^ “‘Therefore, look! days are coming,’ is the utterance of Jehovah, ‘when it will no more be said &#91;to be&#93; Toʹpheth and the valley of the son of Hinʹnom, but the valley of the killing; and they will have to bury in Toʹpheth without there being enough place.^&#42;1^

[NOTE]
====
. Or, “because of there being no place [else].”
====

[[v24-7-33]]

^<<v24-7-33,33>>^ And the dead bodies of this people must become food for the flying creatures of the heavens and for the beasts of the earth, with nobody to make &#91;them&#93; tremble.

[[v24-7-34]]

^<<v24-7-34,34>>^ And I will cause to cease from the cities of Judah and from the streets of Jerusalem the voice of exultation and the voice of rejoicing, the voice of the bridegroom and the voice of the bride; for the land will become nothing but a devastated place.’”

'''

xref:024-jeremiah/024-jeremiah-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremiah/024-jeremiah-008.adoc#v24-8-0[Próximo Capítulo &#62;]