include::./index.adoc[]

[[v24-38-0]]
=== Jeremiah, 38
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-38-1]]

^<<v24-38-1,1>>^ And Sheph·a·tiʹah the son of Matʹtan and Ged·a·liʹah^&#42;1^ the son of Pashʹhur and Juʹcal the son of Shel·e·miʹah^&#42;2^ and Pashʹhur the son of Mal·chiʹjah got to hear the words that Jeremiah was speaking to all the people, saying:

[NOTE]
====
. “And Gedaliah.” Heb., u·Ghedhal·yaʹhu, meaning “Great Is Jehovah.”
. See 36:14 ftn, “Shelemiah.”
====

[[v24-38-2]]

^<<v24-38-2,2>>^ “This is what Jehovah has said, ‘The one continuing to dwell in this city is the one that will die by the sword, by the famine and by the pestilence. But the one going out to the Chal·deʹans is the one that will keep living and that will certainly come to have his soul as a spoil and alive.’

[[v24-38-3]]

^<<v24-38-3,3>>^ This is what Jehovah has said, ‘Without fail this city will be given into the hand of the military force of the king of Babylon, and he will certainly capture it.’”

[[v24-38-4]]

^<<v24-38-4,4>>^ And the princes began to say to the king: “Let this man,^&#42;1^ please, be put to death, for that is how he is weakening the hands of the men of war who are left remaining in this city and the hands of all the people, by speaking to them according to these words. For this man is one seeking not for the peace of this people but for calamity.”

[NOTE]
====
. “This man.” Heb., ha·ʼishʹ haz·zehʹ.
====

[[v24-38-5]]

^<<v24-38-5,5>>^ So King Zed·e·kiʹah said: “Look! He is in YOUR hands. For there is nothing at all in which the king himself can prevail against YOU.”

[[v24-38-6]]

^<<v24-38-6,6>>^ And they proceeded to take Jeremiah and throw him into the cistern of Mal·chiʹjah^&#42;1^ the son of the king, which was in the Courtyard of the Guard. So they let Jeremiah down by means of ropes. Now in the cistern there was no water, but mire; and Jeremiah began to sink down into the mire.

[NOTE]
====
. Meaning “My King Is Jehovah.” Heb., Mal·ki·yaʹhu.
====

[[v24-38-7]]

^<<v24-38-7,7>>^ And Eʹbed-melʹech the E·thi·oʹpi·an,^&#42;1^ a man who was a eunuch and who was in the house of the king, got to hear that they had put Jeremiah into the cistern; and the king was sitting in the Gate of Benjamin.

[NOTE]
====
. “Ethiopian,” LXXVg; MSy, “Cushite.”
====

[[v24-38-8]]

^<<v24-38-8,8>>^ So Eʹbed-melʹech went out of the house of the king and spoke to the king, saying:

[[v24-38-9]]

^<<v24-38-9,9>>^ “O my lord the king, these men have done bad in all that they have done to Jeremiah the prophet, whom they have thrown into the cistern, so that he will die where he is because of the famine. For there is no bread anymore in the city.”

[[v24-38-10]]

^<<v24-38-10,10>>^ Then the king commanded Eʹbed-melʹech the E·thi·oʹpi·an, saying: “Take in your charge^&#42;1^ from this place thirty men, and you must get Jeremiah the prophet up out of the cistern before he dies.”

[NOTE]
====
. Lit., “in your hand.” Heb., beyodh·khaʹ.
====

[[v24-38-11]]

^<<v24-38-11,11>>^ Accordingly Eʹbed-melʹech took the men in his charge and went into the house of the king to beneath the treasury and took from there worn-out rags and worn-out pieces of cloth and let them down to Jeremiah into the cistern by means of the ropes.

[[v24-38-12]]

^<<v24-38-12,12>>^ Then Eʹbed-melʹech the E·thi·oʹpi·an said to Jeremiah: “Put, please, the worn-out rags and the pieces of cloth under your armpits beneath the ropes.” Jeremiah now did so.

[[v24-38-13]]

^<<v24-38-13,13>>^ Finally they drew out Jeremiah by means of the ropes and brought him up out of the cistern. And Jeremiah continued to dwell in the Courtyard of the Guard.

[[v24-38-14]]

^<<v24-38-14,14>>^ And King Zed·e·kiʹah proceeded to send and take Jeremiah the prophet to him to the third entryway, which is in the house of Jehovah, and then the king said to Jeremiah: “I am asking something of you. Do not hide from me anything.”

[[v24-38-15]]

^<<v24-38-15,15>>^ At this Jeremiah said to Zed·e·kiʹah: “In case I should tell you, will you not without fail put me to death? And in case I advise you, you will not listen to me.”

[[v24-38-16]]

^<<v24-38-16,16>>^ At that King Zed·e·kiʹah swore to Jeremiah in the place of concealment, saying: “As Jehovah is alive, who has made for us this soul, I will not put you to death, and I will not give you into the hand of these men who are seeking for your soul.”

[[v24-38-17]]

^<<v24-38-17,17>>^ Jeremiah now said to Zed·e·kiʹah: “This is what Jehovah, the God of armies, the God of Israel, has said, ‘If you will without fail go out to the princes of the king of Babylon, your soul will also certainly keep living and this city itself will not be burned with fire, and you yourself and your household will certainly keep living.

[[v24-38-18]]

^<<v24-38-18,18>>^ But if you will not go out to the princes of the king of Babylon, this city must also be given into the hand of the Chal·deʹans, and they will actually burn it with fire, and you yourself will not escape out of their hand.’”

[[v24-38-19]]

^<<v24-38-19,19>>^ Then King Zed·e·kiʹah said to Jeremiah: “I am in fright of the Jews that have fallen away to the Chal·deʹans, for fear that they might give me into their hand and they might actually deal abusively with me.”

[[v24-38-20]]

^<<v24-38-20,20>>^ But Jeremiah said: “They will do no such giving. Obey, please, the voice of Jehovah in what I am speaking to you, and it will go well with you, and your soul will continue to live.

[[v24-38-21]]

^<<v24-38-21,21>>^ But if you are refusing to go out, this is the thing that Jehovah has caused me to see:

[[v24-38-22]]

^<<v24-38-22,22>>^ And, look! all the women that have been left remaining in the house of the king of Judah are being brought out to the princes of the king of Babylon, and they are saying,
‘The men at peace with you have allured you and prevailed over you.
They have caused your foot to sink down into the very ooze; they have retreated in the opposite direction.’

[[v24-38-23]]

^<<v24-38-23,23>>^ And all your wives and your sons they are bringing out to the Chal·deʹans, and you yourself will not escape out of their hand, but by the hand of the king of Babylon you will be seized, and because of you this city will be burned^&#42;1^ with fire.”

[NOTE]
====
. “This city will be burned,” TLXXSy; M, “this city you will burn.”
====

[[v24-38-24]]

^<<v24-38-24,24>>^ And Zed·e·kiʹah proceeded to say to Jeremiah: “May no man at all get to know about these things, so that you do not die.

[[v24-38-25]]

^<<v24-38-25,25>>^ And in case the princes hear that I have spoken with you and they actually come in to you and say to you, ‘Do tell us, please, What did you speak about to the king? Do not hide anything from us, and we shall not put you to death. And what did the king speak about to you?’

[[v24-38-26]]

^<<v24-38-26,26>>^ you must also say to them, ‘I was letting my request for favor fall before the king, that he should not send me back to the house of Je·honʹa·than to die there.’”

[[v24-38-27]]

^<<v24-38-27,27>>^ In time all the princes came in to Jeremiah and began questioning him. In turn, he told them according to all these words that the king had commanded. So they became silent before him, for the matter was not heard.

[[v24-38-28]]

^<<v24-38-28,28>>^ And Jeremiah continued to dwell in the Courtyard of the Guard until the day that Jerusalem was captured. And it occurred just when Jerusalem was captured.

'''

xref:024-jeremiah/024-jeremiah-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremiah/024-jeremiah-039.adoc#v24-39-0[Próximo Capítulo &#62;]