include::./index.adoc[]

[[v24-23-0]]
=== Jeremiah, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-23-1]]

^<<v24-23-1,1>>^ “Woe to the shepherds who are destroying and scattering the sheep of my pasturage!” is the utterance of Jehovah.

[[v24-23-2]]

^<<v24-23-2,2>>^ Therefore this is what Jehovah the God of Israel has said against the shepherds who are shepherding my people: “YOU yourselves have scattered my sheep; and YOU kept dispersing them, and YOU have not turned your attention to them.”
“Here I am turning my attention upon YOU for the badness of YOUR dealings,” is the utterance of Jehovah.

[[v24-23-3]]

^<<v24-23-3,3>>^ “And I myself shall collect together the remnant of my sheep out of all the lands to which I had dispersed them, and I will bring them back to their pasture ground, and they will certainly be fruitful and become many.

[[v24-23-4]]

^<<v24-23-4,4>>^ And I will raise up over them shepherds who will actually shepherd them; and they will be afraid no more, neither will they be struck with any terror, and none will be missing,” is the utterance of Jehovah.

[[v24-23-5]]

^<<v24-23-5,5>>^ “Look! There are days coming,” is the utterance of Jehovah, “and I will raise up to David a righteous sprout. And a king will certainly reign and act with discretion and execute justice and righteousness in the land.

[[v24-23-6]]

^<<v24-23-6,6>>^ In his days Judah will be saved, and Israel itself will reside in security. And this is his name with which he will be called, Jehovah Is Our Righteousness.”^&#42;1^

[NOTE]
====
. “Jehovah Is Our Righteousness.” Heb., Yehwahʹ Tsidh·qeʹnu.
====

[[v24-23-7]]

^<<v24-23-7,7>>^ “Therefore, look! there are days coming,” is the utterance of Jehovah, “and they will no more say, ‘Jehovah is alive who brought the sons of Israel up out of the land of Egypt,’

[[v24-23-8]]

^<<v24-23-8,8>>^ but, ‘Jehovah is alive who brought up and who brought in the offspring^&#42;1^ of the house of Israel out of the land of the north and out of all the lands to which I have dispersed them,’ and they will certainly dwell on their own ground.”

[NOTE]
====
. Lit., “seed.”
====

[[v24-23-9]]

^<<v24-23-9,9>>^ As regards the prophets, my heart has been broken within me. All my bones have begun shaking. I have become like a man^&#42;1^ that is drunk, and like an able-bodied man^&#42;2^ whom wine has overcome, because of Jehovah and because of his holy words.

[NOTE]
====
. “Like a man.” Heb., keʼishʹ.
. “And like an able-bodied man.” Heb., u·khegheʹver.
====

[[v24-23-10]]

^<<v24-23-10,10>>^ For it is with adulterers^&#42;1^ that the land has become full. For because of the curse^&#42;2^ the land has gone to mourning, the pasture grounds of the wilderness have dried up; and their course of action proves to be bad, and their mightiness is not right.

[NOTE]
====
. “Adulterers.” Lat., a·dulʹte·ris.
. Or, “oath-bound curse.” Heb., ʼa·lahʹ.
====

[[v24-23-11]]

^<<v24-23-11,11>>^ “For both the prophet and the priest themselves have become polluted. Also in my own house I have found their badness,” is the utterance of Jehovah.

[[v24-23-12]]

^<<v24-23-12,12>>^ “Therefore their way will become for them like slippery places in the gloom, into which they will be pushed and certainly fall.”
“For I shall bring upon them a calamity, the year of their being given attention,” is the utterance of Jehovah.

[[v24-23-13]]

^<<v24-23-13,13>>^ “And in the prophets of Sa·marʹi·a I have seen impropriety.^&#42;1^ They have acted as prophets &#91;incited&#93; by Baʹal, and they keep making my people, even Israel, wander about.

[NOTE]
====
. Or, “unseemliness.”
====

[[v24-23-14]]

^<<v24-23-14,14>>^ And in the prophets of Jerusalem I have seen horrible things, committing adultery and walking in falsehood; and they have strengthened the hands of evildoers in order that they should not return, each one from his own badness. To me all of them have become like Sodʹom, and the inhabitants of her like Go·morʹrah.”

[[v24-23-15]]

^<<v24-23-15,15>>^ Therefore this is what Jehovah of armies has said against the prophets: “Here I am making them eat wormwood, and I will give them poisoned water to drink. For from the prophets of Jerusalem apostasy has gone forth to all the land.”

[[v24-23-16]]

^<<v24-23-16,16>>^ This is what Jehovah of armies has said: “Do not listen to the words of the prophets who are prophesying to YOU people. They are making YOU become vain. The vision of their own heart is what they speak—not from the mouth of Jehovah.

[[v24-23-17]]

^<<v24-23-17,17>>^ They are saying again and again to those who are disrespectful of me, ‘Jehovah has spoken: “Peace is what YOU people will come to have.”’ And &#91;to&#93; every one walking in the stubbornness of his heart they have said, ‘No calamity will come upon YOU people.’

[[v24-23-18]]

^<<v24-23-18,18>>^ For who has stood in the intimate group of Jehovah that he might see and hear his word? Who has given attention to his word that he might hear it?

[[v24-23-19]]

^<<v24-23-19,19>>^ Look! The windstorm of Jehovah, rage itself, will certainly go forth, even a whirling tempest. Upon the head of the wicked ones it will whirl itself.

[[v24-23-20]]

^<<v24-23-20,20>>^ The anger of Jehovah will not turn back until he will have carried out and until he will have made the ideas of his heart come true. In the final part of the days YOU people will give YOUR consideration to it with understanding.

[[v24-23-21]]

^<<v24-23-21,21>>^ “I did not send the prophets, yet they themselves ran. I did not speak to them, yet they themselves prophesied.

[[v24-23-22]]

^<<v24-23-22,22>>^ But if they had stood in my intimate group, then they would have made my people hear my own words, and they would have caused them to turn back from their bad way and from the badness of their dealings.”

[[v24-23-23]]

^<<v24-23-23,23>>^ “Am I a God^&#42;1^ nearby,” is the utterance of Jehovah, “and not a God far away?”

[NOTE]
====
. “God.” Heb., ha·ʼElo·hehʹ. Here ha is an interrogative particle introducing a question.
====

[[v24-23-24]]

^<<v24-23-24,24>>^ “Or can any man^&#42;1^ be concealed in places of concealment and I myself not see him?” is the utterance of Jehovah.
“Is it not the heavens and the earth that I myself actually fill?” is the utterance of Jehovah.

[NOTE]
====
. “Any man.” Heb., ʼish.
====

[[v24-23-25]]

^<<v24-23-25,25>>^ “I have heard what the prophets who are prophesying falsehood in my own name have said, saying, ‘I have had a dream! I have had a dream!’

[[v24-23-26]]

^<<v24-23-26,26>>^ How long will it exist in the heart of the prophets who are prophesying the falsehood and who are prophets of the trickiness of their own heart?

[[v24-23-27]]

^<<v24-23-27,27>>^ They are thinking of making my people forget my name by means of their dreams that they keep relating each one to the other, just as their fathers forgot my name by means of Baʹal.

[[v24-23-28]]

^<<v24-23-28,28>>^ The prophet with whom there is a dream, let him relate the dream; but the one with whom my own word is, let him speak forth my word truthfully.”
“What does the straw have to do with the grain?” is the utterance of Jehovah.

[[v24-23-29]]

^<<v24-23-29,29>>^ “Is not my word correspondingly like a fire,” is the utterance of Jehovah, “and like a forge hammer that smashes the crag?”

[[v24-23-30]]

^<<v24-23-30,30>>^ “Therefore here I am against the prophets,” is the utterance of Jehovah, “the ones who are stealing away my words, each one from his companion.”

[[v24-23-31]]

^<<v24-23-31,31>>^ “Here I am against the prophets,” is the utterance of Jehovah, “the ones who are employing their tongue that they may utter forth, ‘An utterance!’”^&#42;1^

[NOTE]
====
. “And say, ‘Jehovah says,’ ” Vg; Sy, “and are saying, ‘Jehovah himself has said thus.’ ”
====

[[v24-23-32]]

^<<v24-23-32,32>>^ “Here I am against the prophets of false dreams,” is the utterance of Jehovah, “who relate them and cause my people to wander about because of their falsehoods and because of their boasting.”
“But I myself did not send them or command them. So they will by no means benefit this people,” is the utterance of Jehovah.

[[v24-23-33]]

^<<v24-23-33,33>>^ “And when this people or the prophet or priest asks you, saying, ‘What is the burden^&#42;1^ of Jehovah?’ you must also say to them, ‘“YOU people are—O what a burden!^&#42;2^ And I shall certainly abandon YOU,” is the utterance of Jehovah.’

[NOTE]
====
. Or, “What is the pronouncement?” Heb., mah-mas·saʼʹ.
. For the rendering “You people are​—⁠O what a burden!” see VT, Vol. VI, 1956, pp. 315, 316. Heb., ʼeth-mah-mas·saʼʹ! Thus in answer to the people’s question mah-mas·saʼʹ? Jeremiah puns and replies, ʼeth-mah-mas·saʼʹ! LXXVgc(Lat., vos eʹstis oʹnus), “You people are the burden.”
====

[[v24-23-34]]

^<<v24-23-34,34>>^ As for the prophet or the priest or the people who say, ‘The burden of Jehovah!’ I will also turn my attention upon that man^&#42;1^ and upon his household.

[NOTE]
====
. “That man.” Heb., ha·ʼishʹ ha·huʼʹ.
====

[[v24-23-35]]

^<<v24-23-35,35>>^ This is what YOU keep saying each one to his fellow and each one to his brother, ‘What has Jehovah answered? And what has Jehovah spoken?’

[[v24-23-36]]

^<<v24-23-36,36>>^ But the burden of Jehovah mention no more YOU people, for the burden itself becomes to each one his own word, and YOU have changed the words of the living God,^&#42;1^ Jehovah of armies, our God.

[NOTE]
====
. “The living God.” Heb., ʼElo·himʹ chai·yimʹ, both pl.
====

[[v24-23-37]]

^<<v24-23-37,37>>^ “This is what you will say to the prophet, ‘What answer has Jehovah given you? And what has Jehovah spoken?

[[v24-23-38]]

^<<v24-23-38,38>>^ And if “The burden of Jehovah!” is what YOU keep on saying, therefore this is what Jehovah has said: “By reason of YOUR saying, ‘This word is the very burden of Jehovah,’ when I kept sending to YOU, saying, ‘YOU must not say: “The burden of Jehovah!”’

[[v24-23-39]]

^<<v24-23-39,39>>^ therefore here I am! And I will give YOU people to neglect, with finality, and I will desert YOU and the city that I gave to YOU and to YOUR forefathers—from before me.

[[v24-23-40]]

^<<v24-23-40,40>>^ And I will put upon YOU reproach to time indefinite and humiliation to time indefinite, which will not be forgotten.”’”

'''

xref:024-jeremiah/024-jeremiah-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremiah/024-jeremiah-024.adoc#v24-24-0[Próximo Capítulo &#62;]