include::./index.adoc[]

[[v24-50-0]]
=== Jeremiah, 50
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-50-1]]

^<<v24-50-1,1>>^ The word that Jehovah spoke concerning Babylon,^&#42;1^ concerning the land of the Chal·deʹans, by means of Jeremiah the prophet:

[NOTE]
====
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v24-50-2]]

^<<v24-50-2,2>>^ “Tell &#91;it&#93; among the nations and publish &#91;it&#93;. And lift up a signal;^&#42;1^ publish &#91;it&#93;. Hide nothing, O men. Say, ‘Babylon has been captured. Bel^&#42;2^ has been put to shame. Merʹo·dach has become terrified. Her images have been put to shame. Her dungy idols have become terrified.’

[NOTE]
====
. “Signal.” Heb., nes.
. “Belus,” LXX.
====

[[v24-50-3]]

^<<v24-50-3,3>>^ For against her a nation has come up from the north. It is the one that makes her land an object of astonishment, so that there proves to be no one dwelling in her. Both man^&#42;1^ and domestic animal have taken flight. They have gone away.”

[NOTE]
====
. “Both man.” Heb., me·ʼa·dhamʹ.
====

[[v24-50-4]]

^<<v24-50-4,4>>^ “In those days and at that time,” is the utterance of Jehovah, “the sons of Israel, they and the sons of Judah together, will come. They will walk, weeping as they walk, and for Jehovah their God they will seek.

[[v24-50-5]]

^<<v24-50-5,5>>^ To Zion they will keep asking the way, with their faces in that direction, &#91;saying,&#93; ‘Come and let us join ourselves to Jehovah in an indefinitely lasting covenant that will not be forgotten.’

[[v24-50-6]]

^<<v24-50-6,6>>^ A flock of perishing creatures my people has become. Their own shepherds have caused them to wander about. On the mountains they have led them away. From mountain to hill they have gone. They have forgotten their resting-place.

[[v24-50-7]]

^<<v24-50-7,7>>^ All those finding them have eaten them up, and their own adversaries have said, ‘We shall not become guilty, due to the fact that they have sinned against Jehovah the abiding place of righteousness and the hope of their forefathers, Jehovah.’”

[[v24-50-8]]

^<<v24-50-8,8>>^ “Take YOUR flight out of the midst of Babylon, and go forth even out of the land of the Chal·deʹans, and become like the leading animals^&#42;1^ before the flock.

[NOTE]
====
. Or, “rams and he-goats.” Vg, “kids.”
====

[[v24-50-9]]

^<<v24-50-9,9>>^ For here I am arousing and bringing up against Babylon a congregation of great nations from the land of the north, and they will certainly array themselves against her. From there she will be captured. One’s arrows are like those of a mighty man causing bereavement of children, who does not come back without results.

[[v24-50-10]]

^<<v24-50-10,10>>^ And Chal·deʹa^&#42;1^ must become a spoil. All those making spoil of her will satisfy themselves,” is the utterance of Jehovah.

[NOTE]
====
. “Chaldea,” LXXVg; TSy, “the land of the Chaldeans”; M, “the Chaldeans,” but with a fem. sing. verb.
====

[[v24-50-11]]

^<<v24-50-11,11>>^ “For YOU men kept rejoicing, for YOU men kept exulting when pillaging my own inheritance. For YOU kept pawing like a heifer in the tender grass, and YOU kept neighing like stallions.

[[v24-50-12]]

^<<v24-50-12,12>>^ The mother of YOU men has become very much ashamed. She that gave YOU birth has been disappointed. Look! She is the least important of the nations, a waterless wilderness and a desert plain.

[[v24-50-13]]

^<<v24-50-13,13>>^ Because of the indignation of Jehovah she will not be inhabited, and she must become a desolate waste in her entirety. As for anyone passing along by Babylon, he will stare in astonishment and whistle on account of all her plagues.

[[v24-50-14]]

^<<v24-50-14,14>>^ “Array yourselves against Babylon on every side, all YOU who are treading the bow. Shoot at her. Spare no arrow, for it is against Jehovah that she has sinned.

[[v24-50-15]]

^<<v24-50-15,15>>^ Shout a war cry against her on every side. She has given her hand. Her pillars have fallen. Her walls have been torn down. For it is the vengeance of Jehovah. Take YOUR vengeance on her. Just as she has done, do to her.

[[v24-50-16]]

^<<v24-50-16,16>>^ Cut off the sower from Babylon, and the one handling the sickle in the time of harvest. Because of the maltreating sword they will turn each one to his own people, and they will flee each one to his own land.

[[v24-50-17]]

^<<v24-50-17,17>>^ “Israel is a scattered sheep. Lions themselves have done the dispersing. In the first instance the king of As·syrʹi·a has devoured him, and in this latter instance Neb·u·chad·rezʹzar the king of Babylon has gnawed on his bones.

[[v24-50-18]]

^<<v24-50-18,18>>^ Therefore this is what Jehovah of armies, the God of Israel, has said, ‘Here I am turning my attention upon the king of Babylon and upon his land in the same way that I turned my attention upon the king of As·syrʹi·a.

[[v24-50-19]]

^<<v24-50-19,19>>^ And I will bring Israel back to his pasture ground, and he will certainly graze on Carʹmel and on Baʹshan; and in the mountainous region of Eʹphra·im and of Gilʹe·ad his soul will be satisfied.’”

[[v24-50-20]]

^<<v24-50-20,20>>^ “And in those days and at that time,” is the utterance of Jehovah, “the error of Israel will be searched for, but it will not be; and the sins of Judah, and they will not be found, for I shall forgive those whom I let remain.”

[[v24-50-21]]

^<<v24-50-21,21>>^ “Against the land of Mer·a·thaʹim^&#42;1^—come up against her and against the inhabitants of Peʹkod. Let there be a massacre and a devoting to destruction close upon them,” is the utterance of Jehovah, “and do according to all that I have commanded you.

[NOTE]
====
. Meaning “Double Rebellion”; or, “Double Bitterness.”
====

[[v24-50-22]]

^<<v24-50-22,22>>^ There is the sound of war in the land, and a great breakdown.

[[v24-50-23]]

^<<v24-50-23,23>>^ O how the forge hammer of all the earth has been cut down and gets broken! O how Babylon has become a mere object of astonishment among the nations!

[[v24-50-24]]

^<<v24-50-24,24>>^ I have laid a snare for you and you have also been caught, O Babylon, and you yourself did not know &#91;it&#93;. You were found and also taken hold of, for it was against Jehovah that you excited yourself.

[[v24-50-25]]

^<<v24-50-25,25>>^ “Jehovah has opened his storehouse, and he brings forth the weapons of his denunciation. For there is a work that the Sovereign Lord, Jehovah of armies, has in the land of the Chal·deʹans.

[[v24-50-26]]

^<<v24-50-26,26>>^ Come in to her from the farthest part. Open up her granaries. Bank her up, just like those making heaps, and devote her to destruction. May she not come to have any remaining ones.

[[v24-50-27]]

^<<v24-50-27,27>>^ Massacre all her young bulls. May they go down to the slaughter. Woe to them, for their day has come, the time for their being given attention!

[[v24-50-28]]

^<<v24-50-28,28>>^ “There is the sound of those fleeing and those escaping from the land of Babylon to tell out in Zion the vengeance of Jehovah our God, the vengeance for his temple.

[[v24-50-29]]

^<<v24-50-29,29>>^ “SUMMON against Babylon archers, all who are treading the bow. Encamp against her all around. May there prove to be no escapees. Pay back to her according to her activity. According to all that she has done, do to her. For it is against Jehovah that she has acted presumptuously, against the Holy One of Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Therefore her young men will fall in her public squares, and even all her men of war will be brought to silence in that day,” is the utterance of Jehovah.

[[v24-50-31]]

^<<v24-50-31,31>>^ “Look! I am against you, O Presumptuousness,” is the utterance of the Sovereign Lord, Jehovah of armies, “for your day must come, the time that I must give you attention.

[[v24-50-32]]

^<<v24-50-32,32>>^ And Presumptuousness will certainly stumble and fall, and it will have no one to cause it to rise up. And I will set a fire ablaze in its cities, and it must devour all its surroundings.”

[[v24-50-33]]

^<<v24-50-33,33>>^ This is what Jehovah of armies has said: “The sons of Israel and the sons of Judah are being oppressed together, and all those taking them captive have laid hold on them. They have refused to let them go.

[[v24-50-34]]

^<<v24-50-34,34>>^ Their Repurchaser^&#42;1^ is strong, Jehovah of armies being his name. Without fail he will conduct their legal case, in order that he may actually give repose to the land^&#42;2^ and cause agitation to the inhabitants of Babylon.”

[NOTE]
====
. “Their Repurchaser (Redeemer).” By extension of thought, “Their Avenger (Vindicator).” Heb., go·ʼalamʹ; Lat., re·demʹptor e·oʹrum. See Job 19:25 and Ps 19:14 ftns.
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v24-50-35]]

^<<v24-50-35,35>>^ “There is a sword against the Chal·deʹans,” is the utterance of Jehovah, “and against the inhabitants of Babylon and against her princes and against her wise ones.

[[v24-50-36]]

^<<v24-50-36,36>>^ There is a sword against the empty talkers, and they will certainly act foolishly. There is a sword against her mighty men, and they will actually become terrified.

[[v24-50-37]]

^<<v24-50-37,37>>^ There is a sword against their horses and against their war chariots and against all the mixed company that are in the midst of her, and they will certainly become women. There is a sword against her treasures, and they will actually be plundered.

[[v24-50-38]]

^<<v24-50-38,38>>^ There is a devastation upon her waters, and they must be dried up. For it is a land of graven images, and because of &#91;their&#93; frightful visions they keep acting crazy.

[[v24-50-39]]

^<<v24-50-39,39>>^ Therefore the haunters of waterless regions^&#42;1^ will dwell with the howling animals, and in her the ostriches^&#42;2^ must dwell; and she will nevermore be dwelt in, nor will she reside for generation after generation.”

[NOTE]
====
. “The dragons,” Lat., dra·coʹnes.
. Lit., “daughters of an ostrich.” Compare Le 11:16 ftn, “Ostrich.”
====

[[v24-50-40]]

^<<v24-50-40,40>>^ “Just as with God’s overthrow of Sodʹom and of Go·morʹrah and of her neighbor &#91;towns&#93;,” is the utterance of Jehovah, “no man^&#42;1^ will dwell there, nor will the son of mankind^&#42;2^ reside in her as an alien.

[NOTE]
====
. “Man.” Heb., ʼish.
. Or, “the son of men.” Heb., ben-ʼa·dhamʹ.
====

[[v24-50-41]]

^<<v24-50-41,41>>^ “Look! A people is coming in from the north; and a great nation and grand kings themselves will be roused up from the remotest parts of the earth.

[[v24-50-42]]

^<<v24-50-42,42>>^ Bow and javelin they handle. They are cruel and will show no mercy. The sound of them is like the sea that is boisterous, and upon horses they will ride; set in array as one man for war against you, O daughter of Babylon.

[[v24-50-43]]

^<<v24-50-43,43>>^ “The king of Babylon has heard the report about them, and his hands have dropped down. There is distress! Severe pains have seized hold of him, just like a woman giving birth.

[[v24-50-44]]

^<<v24-50-44,44>>^ “Look! Someone will come up just like a lion from the proud &#91;thickets&#93; along the Jordan to the durable abiding place, but in a moment I shall make them run away from her. And the one who is chosen I shall appoint over her. For who is like me, and who will challenge me, and who, now, is the shepherd that can stand before me?

[[v24-50-45]]

^<<v24-50-45,45>>^ Therefore hear, O men, the counsel of Jehovah that he has formulated against Babylon and his thoughts that he has thought out against the land of the Chal·deʹans. Surely the little ones of the flock will be dragged about. Surely on account of them he will cause their abiding place to be desolated.

[[v24-50-46]]

^<<v24-50-46,46>>^ At the sound &#91;when&#93; Babylon has been seized, the earth will certainly be set rocking, and among the nations an outcry itself be heard.”

'''

xref:024-jeremiah/024-jeremiah-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremiah/024-jeremiah-051.adoc#v24-51-0[Próximo Capítulo &#62;]