include::./index.adoc[]

[[v24-31-0]]
=== Jeremiah, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-31-1]]

^<<v24-31-1,1>>^ “At that time,” is the utterance of Jehovah, “I shall become God to all the families of Israel; and as for them, they will become my people.”

[[v24-31-2]]

^<<v24-31-2,2>>^ This is what Jehovah has said: “The people made up of survivors from the sword found favor in the wilderness, when Israel was walking^&#42;1^ to get his repose.”

[NOTE]
====
. Lit., “there was a walking.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v24-31-3]]

^<<v24-31-3,3>>^ From far away Jehovah himself appeared to me, &#91;saying:&#93; “And with a love to time indefinite I have loved you.^&#42;1^ That is why I have drawn you with loving-kindness.^&#42;2^

[NOTE]
====
. “You,” fem. sing., referring to the “virgin” in vs 4.
. Or, “loyal love.” Heb., chaʹsedh.
====

[[v24-31-4]]

^<<v24-31-4,4>>^ Yet shall I rebuild you and you will actually be rebuilt, O virgin of Israel. You will yet deck yourself with your tambourines and actually go forth in the dance of those who are laughing.

[[v24-31-5]]

^<<v24-31-5,5>>^ You will yet plant vineyards in the mountains of Sa·marʹi·a. The planters will certainly plant and start to use &#91;them&#93;.

[[v24-31-6]]

^<<v24-31-6,6>>^ For there exists a day when the lookouts in the mountainous region of Eʹphra·im will actually call out, ‘Rise up, O men, and let us go up to Zion, to Jehovah our God.’”

[[v24-31-7]]

^<<v24-31-7,7>>^ For this is what Jehovah has said: “CRY out loudly to Jacob with rejoicing, and CRY shrilly at the head of nations. PUBLISH &#91;it&#93;. GIVE praise and SAY, ‘Save, O Jehovah, your people, the remnant of Israel.’

[[v24-31-8]]

^<<v24-31-8,8>>^ Here I am bringing them from the land of the north, and I will collect them together from the remotest parts of the earth. Among them will be the blind and the lame, the pregnant woman and the one giving birth, all together. As a great congregation they will return here.

[[v24-31-9]]

^<<v24-31-9,9>>^ With weeping they will come, and with &#91;their&#93; entreaties for favor I shall bring them. I shall make them walk to torrent valleys of water, in a right way in which they will not be caused to stumble. For I have become to Israel a Father; and as for Eʹphra·im, he is my firstborn.”

[[v24-31-10]]

^<<v24-31-10,10>>^ Hear the word of Jehovah, O YOU nations, and tell &#91;it&#93; among the islands^&#42;1^ far away, and say: “The One scattering Israel will himself collect him together, and he will certainly keep him as a shepherd does his drove.

[NOTE]
====
. Or, “coastlands.”
====

[[v24-31-11]]

^<<v24-31-11,11>>^ For Jehovah will actually redeem Jacob and reclaim him out of the hand of the one stronger than he is.

[[v24-31-12]]

^<<v24-31-12,12>>^ And they will certainly come and cry out joyfully on the height of Zion and become radiant over the goodness of Jehovah, over the grain and over the new wine and over the oil and over the young ones^&#42;1^ of the flock and the cattle. And their soul will simply become like a well-watered garden, and no more will they languish again.”

[NOTE]
====
. Lit., “the sons.”
====

[[v24-31-13]]

^<<v24-31-13,13>>^ “At that time the virgin will rejoice in the dance, also the young men and the old men, all together. And I will change their mourning into exultation, and I will comfort them and make them rejoice away from their grief.

[[v24-31-14]]

^<<v24-31-14,14>>^ And I will saturate the soul of the priests with fatness, and with my goodness my own people will become satisfied,” is the utterance of Jehovah.

[[v24-31-15]]

^<<v24-31-15,15>>^ “This is what Jehovah has said, ‘In Raʹmah a voice is being heard, lamentation and bitter weeping; Rachel weeping over her sons. She has refused to be comforted over her sons, because they are no more.’”

[[v24-31-16]]

^<<v24-31-16,16>>^ This is what Jehovah has said: “‘Hold back your^&#42;1^ voice from weeping, and your eyes from tears, for there exists a reward for your activity,’ is the utterance of Jehovah, ‘and they will certainly return from the land of the enemy.’

[NOTE]
====
. “Your,” fem. sing., addressed to “Rachel.”
====

[[v24-31-17]]

^<<v24-31-17,17>>^ “‘And there exists a hope for your future,’ is the utterance of Jehovah, ‘and the sons will certainly return to their own territory.’”

[[v24-31-18]]

^<<v24-31-18,18>>^ “I have positively heard Eʹphra·im bemoaning himself, ‘You have corrected me, that I may be corrected, like a calf that has not been trained. Cause me to turn back, and I shall readily turn back, for you are Jehovah my God.

[[v24-31-19]]

^<<v24-31-19,19>>^ For after my turning back I felt regret; and after my being led to know I made a slap upon the thigh. I became ashamed, and I also felt humiliated, for I had carried the reproach of my youth.’”

[[v24-31-20]]

^<<v24-31-20,20>>^ “Is Eʹphra·im a precious son to me, or a fondly treated child? For to the extent of my speaking against him I shall without fail remember him further. That is why my intestines have become boisterous for him. By all means I shall have pity upon him,” is the utterance of Jehovah.

[[v24-31-21]]

^<<v24-31-21,21>>^ “Set up road marks for yourself.^&#42;1^ Place signposts for yourself. Fix your heart upon the highway, the way that you will have to go.^&#42;2^ Come back, O virgin of Israel. Come back to these cities of yours.

[NOTE]
====
. “Yourself,” fem. sing., addressed to the “virgin.”
. Or, “the way that you have gone.”
====

[[v24-31-22]]

^<<v24-31-22,22>>^ How long will you turn this way and that, O unfaithful daughter? For Jehovah has created a new thing in the earth: A mere female will press around an able-bodied man.”^&#42;1^

[NOTE]
====
. “Able-bodied man.” Heb., gaʹver.
====

[[v24-31-23]]

^<<v24-31-23,23>>^ This is what Jehovah of armies, the God of Israel, has said: “They will yet say this word in the land of Judah and in his cities, when I shall gather their captives, ‘May Jehovah bless you,^&#42;1^ O righteous dwelling place, O holy mountain.’

[NOTE]
====
. “You,” masc. sing.
====

[[v24-31-24]]

^<<v24-31-24,24>>^ And in it^&#42;1^ Judah and all his cities will certainly dwell all together, farmers and those who have set out with the drove.

[NOTE]
====
. “It,” fem., referring to the “land.”
====

[[v24-31-25]]

^<<v24-31-25,25>>^ For I will saturate the tired soul, and every languishing soul I will fill.”

[[v24-31-26]]

^<<v24-31-26,26>>^ At this thing I awoke and began to see; and as for my sleep, it had been pleasurable to me.

[[v24-31-27]]

^<<v24-31-27,27>>^ “Look! There are days coming,” is the utterance of Jehovah, “and I will sow the house of Israel and the house of Judah with the seed of man^&#42;1^ and with the seed of domestic animal.”

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v24-31-28]]

^<<v24-31-28,28>>^ “And it must occur that just as I had kept alert toward them to uproot and to pull down and to tear down and to destroy and to do damage, so I shall keep alert toward them to build up and to plant,” is the utterance of Jehovah.

[[v24-31-29]]

^<<v24-31-29,29>>^ “In those days they will no more say, ‘The fathers were the ones that ate the unripe grape, but it was the teeth of the sons that got set on edge.’^&#42;1^

[NOTE]
====
. Lit., “got blunted (dulled).”
====

[[v24-31-30]]

^<<v24-31-30,30>>^ But it will be each one for his own error that one will die. Any man^&#42;1^ eating the unripe grape, his will be the teeth that will be set on edge.”

[NOTE]
====
. “Man.” Heb., ha·ʼa·dhamʹ.
====

[[v24-31-31]]

^<<v24-31-31,31>>^ “Look! There are days coming,” is the utterance of Jehovah, “and I will conclude^&#42;1^ with the house of Israel and with the house of Judah a new covenant;^&#42;2^

[NOTE]
====
. Lit., “cut.”
. “A new covenant.” Heb., berithʹ chadha·shahʹ.
====

[[v24-31-32]]

^<<v24-31-32,32>>^ not one like the covenant that I concluded with their forefathers in the day of my taking hold of their hand to bring them forth out of the land of Egypt, ‘which covenant of mine they themselves broke, although^&#42;1^ I myself had husbandly ownership of them,’^&#42;2^ is the utterance of Jehovah.”

[NOTE]
====
. Lit., “and.”
. “Had husbandly ownership of them,” MVg; T, “was finding pleasure for myself in them”; LXX, “had no concern for them”; Sy, “despised them.”
====

[[v24-31-33]]

^<<v24-31-33,33>>^ “For this is the covenant that I shall conclude with the house of Israel after those days,” is the utterance of Jehovah. “I will put my law within them, and in their heart I shall write it. And I will become their God, and they themselves will become my people.”

[[v24-31-34]]

^<<v24-31-34,34>>^ “And they will no more teach each one his companion and each one his brother, saying, ‘KNOW Jehovah!’ for they will all of them know me, from the least one of them even to the greatest one of them,” is the utterance of Jehovah. “For I shall forgive their error, and their sin I shall remember no more.”

[[v24-31-35]]

^<<v24-31-35,35>>^ This is what Jehovah, the Giver of the sun for light by day, the statutes of^&#42;1^ the moon and the stars for light by night, the One stirring up the sea that its waves may become boisterous, the One whose name is Jehovah of armies, has said:

[NOTE]
====
. “The statutes of,” MTSyVg; LXX and one Heb. ms omit.
====

[[v24-31-36]]

^<<v24-31-36,36>>^ “‘If these regulations could be removed from before me,’ is the utterance of Jehovah, ‘those who are the seed of Israel could likewise cease from proving to be a nation before me always.’”

[[v24-31-37]]

^<<v24-31-37,37>>^ This is what Jehovah has said: “‘If the heavens up above could be measured and the foundations of the earth below could be searched out, I myself also could reject the entire seed of Israel on account of all that they have done,’ is the utterance of Jehovah.”

[[v24-31-38]]

^<<v24-31-38,38>>^ “Look! There are days coming,”^&#42;1^ is the utterance of Jehovah, “and the city will certainly be built to Jehovah from the Tower of Ha·nanʹel to the Corner Gate.

[NOTE]
====
. “Coming,” MmarginTLXXSyVg and 48 Heb. mss. In M the Heb. consonants for this participle are missing, but the vowel points have been inserted to indicate “coming” is to be read. This is qere but not kethib (read but not written).
====

[[v24-31-39]]

^<<v24-31-39,39>>^ And the line for measurement will yet actually go forth straight ahead to the hill of Gaʹreb, and it will certainly go around to Goʹah.

[[v24-31-40]]

^<<v24-31-40,40>>^ And all the low plain of the carcasses and of the fatty ashes, and all the terraces as far as the torrent valley of Kidʹron, clear to the corner of the Horse Gate^&#42;1^ toward the sunrising, will be something holy to Jehovah. It will not be uprooted, neither will it be torn down anymore to time indefinite.”

[NOTE]
====
. Or, “gate of the horses.”
====

'''

xref:024-jeremiah/024-jeremiah-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremiah/024-jeremiah-032.adoc#v24-32-0[Próximo Capítulo &#62;]