include::./index.adoc[]

[[v24-22-0]]
=== Jeremiah, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-22-1]]

^<<v24-22-1,1>>^ This is what Jehovah has said: “Go down to the house of the king of Judah, and you must speak there this word.

[[v24-22-2]]

^<<v24-22-2,2>>^ And you must say, ‘Hear the word of Jehovah, O king of Judah who are sitting on the throne of David, you with your servants and your people, those who are coming in through these gates.

[[v24-22-3]]

^<<v24-22-3,3>>^ This is what Jehovah has said: “RENDER justice and righteousness, and deliver the one that is being robbed out of the hand of the defrauder; and do not maltreat any alien resident,^&#42;1^ fatherless boy or widow. Do &#91;them&#93; no violence. And do not shed any innocent blood in this place.

[NOTE]
====
. Or, “temporary resident.”
====

[[v24-22-4]]

^<<v24-22-4,4>>^ For if YOU will by all means perform this word, there will also certainly come in through the gates of this house the kings sitting for David upon his throne, riding in chariots and on horses, he with his servants and his people.”’

[[v24-22-5]]

^<<v24-22-5,5>>^ “‘But if YOU will not obey these words, by myself I do swear,’ is the utterance of Jehovah, ‘that this house will become a mere devastated place.’

[[v24-22-6]]

^<<v24-22-6,6>>^ “For this is what Jehovah has said concerning the house of the king of Judah, ‘You are as Gilʹe·ad to me, the head^&#42;1^ of Lebʹa·non. Assuredly I shall make you a wilderness; as for the cities, not one will be inhabited.

[NOTE]
====
. Or, “summit; top.”
====

[[v24-22-7]]

^<<v24-22-7,7>>^ And I will sanctify against you those bringing ruin, each one^&#42;1^ and his weapons; and they must cut down the choicest of your cedars and cause them to fall into the fire.

[NOTE]
====
. “Each one.” Heb., ʼish.
====

[[v24-22-8]]

^<<v24-22-8,8>>^ And many nations will actually pass along by this city and say one to the other: “On what account did Jehovah do like this to this great city?”

[[v24-22-9]]

^<<v24-22-9,9>>^ And they will have to say: “On account of the fact that they left the covenant of Jehovah their God and proceeded to bow down to other gods^&#42;1^ and to serve them.”’

[NOTE]
====
. See 19:4 ftn.
====

[[v24-22-10]]

^<<v24-22-10,10>>^ “Do not weep for the dead one, and do not sympathize with him, YOU people. Weep profusely for the one going away, for he will return no more and he will actually not see the land of his relatives.

[[v24-22-11]]

^<<v24-22-11,11>>^ For this is what Jehovah has said concerning Shalʹlum^&#42;1^ the son of Jo·siʹah, the king of Judah who is reigning instead of Jo·siʹah his father, who has gone forth from this place, ‘He will return there no more.

[NOTE]
====
. “Shallum,” MTLXXSyVg; LXXL, “Jehoahaz.”
====

[[v24-22-12]]

^<<v24-22-12,12>>^ For in the place where they have taken him into exile he will die, and this land he will see no more.’

[[v24-22-13]]

^<<v24-22-13,13>>^ “Woe to the one building his house, but not with righteousness, and his upper chambers, but not with justice, by use of his fellowman who serves for nothing, and whose wages he does not give him;

[[v24-22-14]]

^<<v24-22-14,14>>^ the one saying, ‘I am going to build for myself a roomy house and commodious upper chambers; and my windows must be widened out for it, and the paneling will be with cedar and smeared with vermilion.’

[[v24-22-15]]

^<<v24-22-15,15>>^ Will you continue reigning because you are competing by use of cedar? As for your father, did he not eat and drink and execute justice and righteousness? In that case it went well with him.

[[v24-22-16]]

^<<v24-22-16,16>>^ He pleaded the legal claim of the afflicted one and the poor one. In that case it went well. ‘Was not that a case of knowing me?’ is the utterance of Jehovah.

[[v24-22-17]]

^<<v24-22-17,17>>^ ‘Assuredly your eyes and your heart are upon nothing but upon your unjust gain, and upon the blood of the innocent one in order to shed &#91;it&#93;, and upon defrauding and upon extortion in order to carry &#91;them&#93; on.’

[[v24-22-18]]

^<<v24-22-18,18>>^ “Therefore this is what Jehovah has said concerning Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah, ‘They will not wail for him: “Alas, my brother! And alas, &#91;my&#93; sister!” They will not wail for him: “Alas, O master! And alas, his dignity!”

[[v24-22-19]]

^<<v24-22-19,19>>^ With the burial of a he-ass he will be buried, with a dragging about and a throwing away, out beyond the gates of Jerusalem.’

[[v24-22-20]]

^<<v24-22-20,20>>^ “Go up onto Lebʹa·non and cry out, and on Baʹshan let your^&#42;1^ voice out. And cry out from Abʹa·rim,^&#42;2^ because all those intensely loving you have been broken.

[NOTE]
====
. “Your,” fem. sing., referring to the city.
. Or, “from the borderland.” Heb., me·ʽAva·rimʹ.
====

[[v24-22-21]]

^<<v24-22-21,21>>^ I spoke to you during your freedom from care. You said, ‘I shall not obey.’ This has been your way since your youth, for you did not obey my voice.

[[v24-22-22]]

^<<v24-22-22,22>>^ A wind will shepherd all your own shepherds; and as for those intensely loving you, they will go into captivity itself. For at that time you will be ashamed and certainly feel humiliated because of all your calamity.

[[v24-22-23]]

^<<v24-22-23,23>>^ O you who are dwelling in Lebʹa·non, being nested in the cedars, how you will certainly sigh when there come to you birth pangs, the labor pains like those of a woman giving birth!”

[[v24-22-24]]

^<<v24-22-24,24>>^ “‘As I am alive,’ is the utterance of Jehovah, ‘even if Co·niʹah^&#42;1^ the son of Je·hoiʹa·kim, the king of Judah, happened to be the seal ring on my right hand, from there I would pull you off!

[NOTE]
====
. “Coniah,” M(Heb., Kon·yaʹhu)T; LXXSyVg, “Jeconiah”; in 2Ki 24:6-15, “Jehoiachin.” The grandson of Josiah.
====

[[v24-22-25]]

^<<v24-22-25,25>>^ And I will give you^&#42;1^ into the hand of those who are seeking for your soul and into the hand of those of whom you are scared and into the hand of Neb·u·chad·rezʹzar the king of Babylon and into the hand of the Chal·deʹans.

[NOTE]
====
. “You,” masc. sing.
====

[[v24-22-26]]

^<<v24-22-26,26>>^ And I will hurl you and your mother who gave you birth out into another land in which YOU people were not born, and there is where YOU will die.

[[v24-22-27]]

^<<v24-22-27,27>>^ And into the land to which they will be lifting up their soul^&#42;1^ to return, there they will not return.

[NOTE]
====
. “Their soul (soulful desire).” Heb., naph·shamʹ; Gr., psy·khaisʹ au·tonʹ; Lat., aʹni·mam suʹam.
====

[[v24-22-28]]

^<<v24-22-28,28>>^ Is this man^&#42;1^ Co·niʹah a mere form despised, dashed to pieces, or a vessel in which there is no delight? Why is it that he himself and his offspring must be hurled down and thrown into the land that they have not known?’

[NOTE]
====
. “This man.” Heb., ha·ʼishʹ haz·zehʹ.
====

[[v24-22-29]]

^<<v24-22-29,29>>^ “O earth, earth, earth, hear the word of Jehovah.

[[v24-22-30]]

^<<v24-22-30,30>>^ This is what Jehovah has said, ‘WRITE down this man as childless, as an able-bodied man who will not have any success in his days; for from his offspring not a single one will have any success, sitting upon the throne of David and ruling anymore in Judah.’”

'''

xref:024-jeremiah/024-jeremiah-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremiah/024-jeremiah-023.adoc#v24-23-0[Próximo Capítulo &#62;]