include::./index.adoc[]

[[v24-8-0]]
=== Jeremiah, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-8-1]]

^<<v24-8-1,1>>^ “At that time,” is the utterance of Jehovah, “people will also bring forth the bones of the kings of Judah and the bones of its princes and the bones of the priests and the bones of the prophets and the bones of the inhabitants of Jerusalem from their graves.

[[v24-8-2]]

^<<v24-8-2,2>>^ And they will actually spread them out to the sun and to the moon and to all the army of the heavens that they have loved and that they have served and that they have walked after and that they have sought and that they have bowed down to. They will not be gathered, nor will they be buried. As manure upon the face of the ground they will become.”

[[v24-8-3]]

^<<v24-8-3,3>>^ “And death will certainly be chosen rather than life on the part of all the remnant of those remaining out of this bad family in all the places of the remaining ones, where I will have dispersed them,” is the utterance of Jehovah of armies.

[[v24-8-4]]

^<<v24-8-4,4>>^ “And you must say to them, ‘This is what Jehovah has said: “Will they fall and not get up again? If one would turn back, will the other not also turn back?

[[v24-8-5]]

^<<v24-8-5,5>>^ Why is it that this people, Jerusalem, is unfaithful with an enduring unfaithfulness? They have taken hold of trickiness; they have refused to turn back.

[[v24-8-6]]

^<<v24-8-6,6>>^ I have paid attention, and I kept listening. It was not right the way they kept speaking. There was not a man repenting over his badness, saying, ‘What have I done?’ Each one is going back into the popular course, like a horse that is dashing into the battle.

[[v24-8-7]]

^<<v24-8-7,7>>^ Even the stork in the heavens—it well knows its appointed times; and the turtledove and the swift and the bulbul—they observe well the time of each one’s coming in. But as for my people, they have not come to know the judgment of Jehovah.”’

[[v24-8-8]]

^<<v24-8-8,8>>^ “‘How can YOU men say: “We are wise, and the law of Jehovah is with us”? Surely, now, the false stylus of the secretaries has worked in sheer falsehood.

[[v24-8-9]]

^<<v24-8-9,9>>^ The wise ones have become ashamed. They have become terrified and will be caught. Look! They have rejected the very word of Jehovah, and what wisdom do they have?

[[v24-8-10]]

^<<v24-8-10,10>>^ Therefore I shall give their wives to other men, their fields to those taking possession; for, from the least one even to the greatest one, each one is making unjust gain; from the prophet even to the priest, each one is acting falsely.

[[v24-8-11]]

^<<v24-8-11,11>>^ And they try to heal the breakdown^&#42;1^ of the daughter of my people lightly,^&#42;2^ saying: “There is peace! There is peace!”^&#42;3^ when there is no peace.

[NOTE]
====
. Or, “fracture.”
. Or, “superficially.”
. See 6:14 ftn, “Peace.”
====

[[v24-8-12]]

^<<v24-8-12,12>>^ Did they feel shame because they had done even what was detestable? For one thing, they positively could not feel ashamed; for another thing, they did not know even how to feel humiliated.
“‘Therefore they will fall among those who are falling. In the time of their being given attention, they will stumble,’ Jehovah has said.

[[v24-8-13]]

^<<v24-8-13,13>>^ “‘When doing the gathering, I shall bring them to their finish,’^&#42;1^ is the utterance of Jehovah. ‘There will be no grapes on the vine, and there will be no figs on the fig tree, and the foliage itself will certainly wither. And things that I give to them will pass by them.’”

[NOTE]
====
. “[When] I shall [or, would] without fail gather them,” by a change of vowel pointing.
====

[[v24-8-14]]

^<<v24-8-14,14>>^ “Why are we sitting still? Gather yourselves together, and let us enter into the fortified cities and be silent there. For Jehovah our God^&#42;1^ has himself put us to silence,^&#42;2^ and he gives us poisoned water to drink, because we have sinned against Jehovah.

[NOTE]
====
. “Our God.” Heb., ʼElo·hehʹnu.
. Or, “put us out of action,” that is, caused us to perish.
====

[[v24-8-15]]

^<<v24-8-15,15>>^ There was a hoping for peace, but no good &#91;came&#93;; for a time of healing, but, look! terror!

[[v24-8-16]]

^<<v24-8-16,16>>^ From Dan has been heard the snorting of his horses. Due to the sound of the neighing of his stallions the whole land has begun to rock. And they come in and eat up the land^&#42;1^ and what fills it, the city and its inhabitants.”

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v24-8-17]]

^<<v24-8-17,17>>^ “For here I am sending in among YOU serpents, poisonous snakes, for which there is no charming, and they will certainly bite YOU,” is the utterance of Jehovah.

[[v24-8-18]]

^<<v24-8-18,18>>^ A grief that is beyond curing has come up into me. My heart is ill.

[[v24-8-19]]

^<<v24-8-19,19>>^ Here there is the sound of the cry for help of the daughter of my people from a land far away: “Is Jehovah not in Zion? Or is her king not in her?”
“Why is it that they have offended me with their graven images, with their vain foreign gods?”

[[v24-8-20]]

^<<v24-8-20,20>>^ “The harvest has passed, the summer has come to an end; but as for us, we have not been saved!”

[[v24-8-21]]

^<<v24-8-21,21>>^ Over the breakdown of the daughter of my people I have become shattered. I have grown sad. Outright astonishment has seized hold of me.

[[v24-8-22]]

^<<v24-8-22,22>>^ Is there no balsam in Gilʹe·ad? Or is there no healer there? Why is it, then, that the recuperation of the daughter of my people has not come up?

'''

xref:024-jeremiah/024-jeremiah-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremiah/024-jeremiah-009.adoc#v24-9-0[Próximo Capítulo &#62;]