include::./index.adoc[]

[[v24-11-0]]
=== Jeremiah, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-11-1]]

^<<v24-11-1,1>>^ The word that occurred to Jeremiah^&#42;1^ from Jehovah, saying:

[NOTE]
====
. See 1:1 ftn, “Jeremiah.”
====

[[v24-11-2]]

^<<v24-11-2,2>>^ “Hear the words of this covenant, YOU men!
“And you must speak them to the men^&#42;1^ of Judah and to the inhabitants of Jerusalem,

[NOTE]
====
. “Men of.” Heb., ʼish, sing. but used collectively.
====

[[v24-11-3]]

^<<v24-11-3,3>>^ and you must say to them, ‘This is what Jehovah the God of Israel has said: “Cursed is the man^&#42;1^ that does not listen to the words of this covenant,

[NOTE]
====
. “The man.” Heb., ha·ʼishʹ.
====

[[v24-11-4]]

^<<v24-11-4,4>>^ which I commanded YOUR forefathers in the day of my bringing them out of the land of Egypt, out of the furnace of iron, saying, ‘Obey my voice, and YOU must do things according to all that I command YOU; and YOU will certainly become my people and I myself shall become YOUR God,^&#42;1^

[NOTE]
====
. Lit., “to God.” Heb., lEʼ·lo·himʹ, pl.
====

[[v24-11-5]]

^<<v24-11-5,5>>^ for the purpose of carrying out the oath that I swore to YOUR forefathers, to give them the land flowing with milk and honey, as in this day.’”’”
And I proceeded to answer and say: “Amen,^&#42;1^ O Jehovah.”

[NOTE]
====
. Or, “So be it.” Heb., ʼa·menʹ.
====

[[v24-11-6]]

^<<v24-11-6,6>>^ And Jehovah went on to say to me: “Proclaim all these words in the cities of Judah and in the streets of Jerusalem, saying, ‘Hear, YOU people, the words of this covenant, and YOU must do them.

[[v24-11-7]]

^<<v24-11-7,7>>^ For I solemnly admonished YOUR forefathers in the day of my bringing them up out of the land of Egypt and down to this day, rising up early and admonishing, saying: “Obey my voice.”

[[v24-11-8]]

^<<v24-11-8,8>>^ But they did not listen or incline their ear, but they kept walking each one in the stubbornness of their bad heart; and so I brought upon them all the words of this covenant that I commanded &#91;them&#93; to do, but that they did not do.’”

[[v24-11-9]]

^<<v24-11-9,9>>^ Furthermore, Jehovah said to me: “Conspiracy has been found among the men of Judah and among the inhabitants of Jerusalem.

[[v24-11-10]]

^<<v24-11-10,10>>^ They have returned to the errors of their forefathers, the first ones, who refused to obey^&#42;1^ my words, but who themselves have walked after other gods^&#42;2^ in order to serve them. The house of Israel and the house of Judah have broken my covenant that I concluded with their forefathers.

[NOTE]
====
. Or, “hear.”
. “Gods.” Heb., ʼelo·himʹ.
====

[[v24-11-11]]

^<<v24-11-11,11>>^ Therefore this is what Jehovah has said, ‘Here I am bringing upon them a calamity that they will not be able to get out of; and they will certainly call to me for aid, but I shall not listen to them.

[[v24-11-12]]

^<<v24-11-12,12>>^ And the cities of Judah and the inhabitants of Jerusalem will have to go and call for aid to the gods^&#42;1^ to which they are making sacrificial smoke, but which will positively bring no salvation to them in the time of their calamity.

[NOTE]
====
. “The gods.” Heb., ha·ʼelo·himʹ.
====

[[v24-11-13]]

^<<v24-11-13,13>>^ For your gods have become as many as your cities, O Judah; and as many altars as the streets of Jerusalem YOU people have placed for the shameful thing, altars to make sacrificial smoke to Baʹal.’

[[v24-11-14]]

^<<v24-11-14,14>>^ “And as for you, do not pray in behalf of this people, and do not lift up in their behalf an entreating cry or a prayer, for I shall not be listening in the time of their calling out to me in regard to their calamity.^&#42;1^

[NOTE]
====
. “In regard to their calamity,” M; TLXXSyVg and 34 Heb. mss, “in the time of their calamity.”
====

[[v24-11-15]]

^<<v24-11-15,15>>^ “What business does my beloved one have in my house, that many of them should do this thing, the &#91;evil&#93; device? And with holy flesh will they make &#91;it&#93; pass over from upon you, when your calamity &#91;comes&#93;? At that time will you exult?

[[v24-11-16]]

^<<v24-11-16,16>>^ ‘A luxuriant olive tree, pretty with fruit &#91;and&#93; in form,’ is what Jehovah has called your name. With sound of the great roaring, he has set a fire blazing against her, and they have broken its branches.

[[v24-11-17]]

^<<v24-11-17,17>>^ “And Jehovah of armies himself, the Planter of you,^&#42;1^ has spoken against you a calamity on account of the badness of the house of Israel and the house of Judah that they have committed on their own part to offend me in making sacrificial smoke to Baʹal.”

[NOTE]
====
. “You,” fem. sing.
====

[[v24-11-18]]

^<<v24-11-18,18>>^ And Jehovah himself has informed me that I may know. At that time you caused me to see their dealings.

[[v24-11-19]]

^<<v24-11-19,19>>^ And I was like a male lamb, an intimate one, that is brought to slaughter, and I did not know that it was against me that they thought out schemes: “Let us bring to ruin the tree with its food, and let us cut him off from the land of the living ones, that his very name may no more be remembered.”

[[v24-11-20]]

^<<v24-11-20,20>>^ But Jehovah of armies is judging with righteousness; he is examining the kidneys^&#42;1^ and the heart. O may I see your vengeance on them, for it is to you that I have revealed my case at law.

[NOTE]
====
. Or, “deepest emotions.” Heb., kela·yohthʹ.
====

[[v24-11-21]]

^<<v24-11-21,21>>^ Therefore this is what Jehovah has said against the men of Anʹa·thoth who are seeking for your soul,^&#42;1^ saying: “You must not prophesy in the name of Jehovah, that you may not die at our hand”;

[NOTE]
====
. “Seeking for your soul,” MSyVg; LXX, “seeking for my soul”; T, “seeking to put you to death.”
====

[[v24-11-22]]

^<<v24-11-22,22>>^ therefore this is what Jehovah of armies has said: “Here I am turning my attention upon them. The young men themselves will die by the sword. Their sons and their daughters themselves will die by the famine.

[[v24-11-23]]

^<<v24-11-23,23>>^ And not even a remnant will there come to be for them, because I shall bring calamity upon the men of Anʹa·thoth, the year of their being given attention.”

'''

xref:024-jeremiah/024-jeremiah-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremiah/024-jeremiah-012.adoc#v24-12-0[Próximo Capítulo &#62;]