include::./index.adoc[]

[[v24-43-0]]
=== Jeremiah, 43
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-43-1]]

^<<v24-43-1,1>>^ Now it came about that as soon as Jeremiah finished speaking to all the people all the words of Jehovah their God with which Jehovah their God had sent him to them, even all these words,

[[v24-43-2]]

^<<v24-43-2,2>>^ Az·a·riʹah the son of Ho·shaiʹah and Jo·haʹnan the son of Ka·reʹah and all the presumptuous men proceeded to say to Jeremiah: “It is a falsehood that you are speaking. Jehovah our God has not sent you, saying, ‘Do not enter into Egypt to reside there as aliens.’

[[v24-43-3]]

^<<v24-43-3,3>>^ But Barʹuch the son of Ne·riʹah is instigating you against us for the purpose of giving us into the hand of the Chal·deʹans, to put us to death or to take us into exile in Babylon.”

[[v24-43-4]]

^<<v24-43-4,4>>^ And Jo·haʹnan the son of Ka·reʹah and all the chiefs of the military forces and all the people did not obey the voice of Jehovah, to keep on dwelling in the land of Judah.

[[v24-43-5]]

^<<v24-43-5,5>>^ So Jo·haʹnan the son of Ka·reʹah and all the chiefs of the military forces took all the remnant of Judah that had returned from all the nations to which they had been dispersed, in order to reside for a while in the land of Judah,

[[v24-43-6]]

^<<v24-43-6,6>>^ even the able-bodied men and the wives and the little children and the daughters of the king and every soul^&#42;1^ that Neb·uʹzar·adʹan the chief of the bodyguard had let stay with Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan, and Jeremiah the prophet and Barʹuch the son of Ne·riʹah.

[NOTE]
====
. See App 4A.
====

[[v24-43-7]]

^<<v24-43-7,7>>^ And they finally came into the land of Egypt, for they did not obey the voice of Jehovah; and they came gradually as far as Tahʹpan·hes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Then the word of Jehovah occurred to Jeremiah in Tahʹpan·hes, saying:

[[v24-43-9]]

^<<v24-43-9,9>>^ “Take in your hand great stones, and you must hide them in the mortar in the terrace of bricks that is at the entrance of the house of Pharʹaoh in Tahʹpan·hes before the eyes of the Jewish men.

[[v24-43-10]]

^<<v24-43-10,10>>^ And you must say to them, ‘This is what Jehovah of armies, the God of Israel, has said: “Here I am sending and I will take Neb·u·chad·rezʹzar the king of Babylon, my servant, and I will place his throne right above these stones that I have hidden, and he will certainly extend his state tent^&#42;1^ over them.

[NOTE]
====
. Or, “his canopy”; or, “his carpet.”
====

[[v24-43-11]]

^<<v24-43-11,11>>^ And he must come in and strike the land of Egypt. Whoever is &#91;due&#93; for deadly plague will be for deadly plague, and whoever is &#91;due&#93; for captivity will be for captivity, and whoever is &#91;due&#93; for the sword will be for the sword.

[[v24-43-12]]

^<<v24-43-12,12>>^ And I will set a fire ablaze in the houses of the gods of Egypt; and he will certainly burn them and lead them captive and wrap himself up in the land of Egypt, just as a shepherd wraps himself up in his garment, and he will actually go out from there in peace.

[[v24-43-13]]

^<<v24-43-13,13>>^ And he will certainly break to pieces the pillars of Beth-sheʹmesh,^&#42;1^ which is in the land of Egypt; and the houses of the gods of Egypt he will burn with fire.”’”

[NOTE]
====
. Lit., “House of the Sun.” Heb., Behth Sheʹmesh; Lat., doʹmus soʹlis; Gr., He·liʹou poʹle·os, “City of the Sun.”
====

'''

xref:024-jeremiah/024-jeremiah-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremiah/024-jeremiah-044.adoc#v24-44-0[Próximo Capítulo &#62;]