include::./index.adoc[]

[[v24-36-0]]
=== Jeremiah, 36
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-36-1]]

^<<v24-36-1,1>>^ Now it came about in the fourth year of Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah, that this word occurred to Jeremiah from Jehovah, saying:

[[v24-36-2]]

^<<v24-36-2,2>>^ “Take for yourself a roll of a book, and you must write in it all the words that I have spoken to you against Israel and against Judah and against all the nations, since the day that I spoke to you, since the days of Jo·siʹah, clear down to this day.

[[v24-36-3]]

^<<v24-36-3,3>>^ Perhaps those of the house of Judah will listen to all the calamity that I am thinking of doing to them, to the end that they may return, each one from his bad way, and that I may actually forgive their error and their sin.”

[[v24-36-4]]

^<<v24-36-4,4>>^ And Jeremiah proceeded to call Barʹuch the son of Ne·riʹah that Barʹuch might write at the mouth of Jeremiah all the words of Jehovah that He had spoken to him, on the roll of the book.

[[v24-36-5]]

^<<v24-36-5,5>>^ Then Jeremiah commanded Barʹuch, saying: “I am shut up. I am unable to enter into the house of Jehovah.

[[v24-36-6]]

^<<v24-36-6,6>>^ And you yourself must enter in and read aloud from the roll that you have written at my mouth the words of Jehovah in the ears of the people at the house of Jehovah in the day of fast; and also in the ears of all Judah who are coming in from their cities you should read them aloud.

[[v24-36-7]]

^<<v24-36-7,7>>^ Perhaps their request for favor will fall before Jehovah and they will return, each one from his bad way, for great is the anger and the rage that Jehovah has spoken against this people.”

[[v24-36-8]]

^<<v24-36-8,8>>^ And Barʹuch the son of Ne·riʹah proceeded to do according to all that Jeremiah the prophet had commanded him, to read aloud from the book the words of Jehovah at the house of Jehovah.

[[v24-36-9]]

^<<v24-36-9,9>>^ Now it came about in the fifth year of Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah, in the ninth month, that all the people in Jerusalem and all the people that were coming in from the cities of Judah into Jerusalem proclaimed a fast before Jehovah.

[[v24-36-10]]

^<<v24-36-10,10>>^ And Barʹuch began to read aloud from the book the words of Jeremiah at the house of Jehovah, in the dining room of Gem·a·riʹah^&#42;1^ the son of Shaʹphan the copyist, in the upper courtyard, at the entrance of the new gate of the house of Jehovah, in the ears of all the people.

[NOTE]
====
. Meaning “Jehovah Has Perfected.” Heb., Gemar·yaʹhu.
====

[[v24-36-11]]

^<<v24-36-11,11>>^ And Mi·caiʹah^&#42;1^ the son of Gem·a·riʹah the son of Shaʹphan got to hear all the words of Jehovah from out of the book.

[NOTE]
====
. Meaning “Who Is Like Jehovah?” Heb., Mi·khaiʹhu.
====

[[v24-36-12]]

^<<v24-36-12,12>>^ At that he went down to the house of the king, to the dining room of the secretary, and, look! there is where all the princes were sitting, E·lishʹa·ma the secretary and De·laʹiah^&#42;1^ the son of She·maiʹah^&#42;2^ and El·naʹthan the son of Achʹbor and Gem·a·riʹah the son of Shaʹphan and Zed·e·kiʹah the son of Han·a·niʹah^&#42;3^ and all the other princes.

[NOTE]
====
. “And Delaiah.” Heb., u·Dhela·yaʹhu, meaning “Jehovah Has Drawn Up [in deliverance].”
. Meaning “Jehovah Has Heard.” Heb., Shemaʽ·yaʹhu.
. Meaning “Jehovah Has Shown Favor; Jehovah Has Been Gracious.” Heb., Chanan·yaʹhu.
====

[[v24-36-13]]

^<<v24-36-13,13>>^ And Mi·caiʹah proceeded to tell them all the words that he had heard when Barʹuch read aloud from the book in the ears of the people.

[[v24-36-14]]

^<<v24-36-14,14>>^ Then all the princes sent out to Barʹuch Je·huʹdi the son of Neth·a·niʹah^&#42;1^ the son of Shel·e·miʹah^&#42;2^ the son of Cushʹi, saying: “The roll from which you read aloud in the ears of the people—take it in your hand and come.” Accordingly Barʹuch the son of Ne·riʹah^&#42;3^ took the roll in his hand and came in to them.

[NOTE]
====
. Meaning “Jehovah Has Given.” Heb., Nethan·yaʹhu.
. Meaning “Jehovah Is Recompense”; or, “Communion Sacrifice of Jehovah.” Heb., She·lem·yaʹhu.
. Meaning “My Lamp Is Jehovah.” Heb., Ne·ri·yaʹhu.
====

[[v24-36-15]]

^<<v24-36-15,15>>^ Then they said to him: “Sit down, please, and read it aloud in our ears.” So Barʹuch read aloud in their ears.

[[v24-36-16]]

^<<v24-36-16,16>>^ Now it came about that as soon as they heard all the words, they looked at one another in dread; and they proceeded to say to Barʹuch: “We shall without fail tell the king all these words.”

[[v24-36-17]]

^<<v24-36-17,17>>^ And Barʹuch they asked, saying: “Tell us, please, How did you write all these words from his mouth?”

[[v24-36-18]]

^<<v24-36-18,18>>^ Then Barʹuch said to them: “Out of his mouth he kept declaring to me all these words, and I was writing in the book with ink.”

[[v24-36-19]]

^<<v24-36-19,19>>^ Finally the princes said to Barʹuch: “Go, conceal yourself, you and Jeremiah, so that no one at all will know where YOU men are.”

[[v24-36-20]]

^<<v24-36-20,20>>^ Then they came in to the king, to the courtyard, and the roll they entrusted to the dining room of E·lishʹa·ma the secretary; and they began to tell all the words in the ears of the king.

[[v24-36-21]]

^<<v24-36-21,21>>^ So the king sent Je·huʹdi out to get the roll. Accordingly he got it out of the dining room of E·lishʹa·ma the secretary. And Je·huʹdi began to read it aloud in the ears of the king and in the ears of all the princes standing by the king.

[[v24-36-22]]

^<<v24-36-22,22>>^ And the king was sitting in the winter house, in the ninth month,^&#42;1^ with a brazier burning before him.

[NOTE]
====
. “The ninth month,” that is, Chislev, the postexilic name of the ninth Jewish lunar month that corresponds to the latter half of November and the first half of December. See App 8B.
====

[[v24-36-23]]

^<<v24-36-23,23>>^ Then it came about that as soon as Je·huʹdi had read three or four page-columns, he proceeded to tear it apart with the secretary’s knife, pitching &#91;it&#93; also into the fire that was in the brazier until all the roll ended up in the fire that was in the brazier.

[[v24-36-24]]

^<<v24-36-24,24>>^ And they felt no dread; neither did the king and all his servants, who were listening to all these words, rip their garments apart.

[[v24-36-25]]

^<<v24-36-25,25>>^ And even El·naʹthan and De·laʹiah^&#42;1^ and Gem·a·riʹah^&#42;2^ themselves pleaded with the king not to burn the roll, but he did not listen to them.

[NOTE]
====
. See vs 12 ftn, “Delaiah.”
. See vs 10 ftn.
====

[[v24-36-26]]

^<<v24-36-26,26>>^ Further, the king commanded Je·rahʹme·el the son of the king and Se·raiʹah^&#42;1^ the son of Azʹri·el and Shel·e·miʹah^&#42;2^ the son of Abʹde·el to get Barʹuch the secretary and Jeremiah the prophet. But Jehovah kept them concealed.

[NOTE]
====
. Meaning “Jehovah Has Contended (Persevered).” Heb., Sera·yaʹhu.
. See vs 14 ftn, “Shelemiah.”
====

[[v24-36-27]]

^<<v24-36-27,27>>^ And the word of Jehovah occurred further to Jeremiah after the king had burned up the roll with the words that Barʹuch had written at the mouth of Jeremiah, saying:

[[v24-36-28]]

^<<v24-36-28,28>>^ “Take again for yourself a roll, another one, and write on it all the first words that proved to be on the first roll, which Je·hoiʹa·kim the king of Judah burned up.

[[v24-36-29]]

^<<v24-36-29,29>>^ And against Je·hoiʹa·kim the king of Judah you should say, ‘This is what Jehovah has said: “You yourself have burned up this roll, saying, ‘Why is it that you have written on it, saying: “The king of Babylon will come without fail and will certainly bring this land to ruin and cause man^&#42;1^ and beast to cease from it”?’

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v24-36-30]]

^<<v24-36-30,30>>^ Therefore this is what Jehovah has said against Je·hoiʹa·kim the king of Judah, ‘He will come to have no one sitting upon the throne of David, and his own dead body will become something thrown out to the heat by day and to the frost by night.

[[v24-36-31]]

^<<v24-36-31,31>>^ And I will call to account against him and against his offspring and against his servants their error, and I will bring upon them and upon the inhabitants of Jerusalem and upon the men^&#42;1^ of Judah all the calamity that I have spoken against them, and they did not listen.’”’”

[NOTE]
====
. “Men of.” Heb., ʼish.
====

[[v24-36-32]]

^<<v24-36-32,32>>^ And Jeremiah himself took another roll and then gave it to Barʹuch the son of Ne·riʹah, the secretary, who proceeded to write upon it at the mouth of Jeremiah all the words of the book that Je·hoiʹa·kim the king of Judah had burned in the fire; and there were added to them many more words like those.

'''

xref:024-jeremiah/024-jeremiah-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremiah/024-jeremiah-037.adoc#v24-37-0[Próximo Capítulo &#62;]