include::./index.adoc[]

[[v24-18-0]]
=== Jeremiah, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-18-1]]

^<<v24-18-1,1>>^ The word that occurred to Jeremiah^&#42;1^ from Jehovah, saying:

[NOTE]
====
. See 1:1 ftn, “Jeremiah.”
====

[[v24-18-2]]

^<<v24-18-2,2>>^ “Rise up, and you must go down to the house of the potter, and there I shall cause you to hear my words.”

[[v24-18-3]]

^<<v24-18-3,3>>^ And I proceeded to go down to the house of the potter, and there he was doing work upon the potter’s wheels.

[[v24-18-4]]

^<<v24-18-4,4>>^ And the vessel that he was making with the clay was spoiled by the potter’s hand, and he turned back and went making it into another vessel, just as it looked right in the eyes of the potter^&#42;1^ to make.

[NOTE]
====
. Lit., “former”; or, “one forming.” See vs 11.
====

[[v24-18-5]]

^<<v24-18-5,5>>^ And the word of Jehovah continued to occur to me, saying:

[[v24-18-6]]

^<<v24-18-6,6>>^ “‘Am I not able to do just like this potter to YOU people, O house of Israel?’ is the utterance of Jehovah. ‘Look! As the clay in the hand of the potter, so YOU are in my hand, O house of Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ At any moment that I may speak against a nation and against a kingdom to uproot &#91;it&#93; and to pull &#91;it&#93; down and to destroy &#91;it&#93;,

[[v24-18-8]]

^<<v24-18-8,8>>^ and that nation actually turns back from its badness against which I spoke, I will also feel regret over the calamity that I had thought to execute upon it.

[[v24-18-9]]

^<<v24-18-9,9>>^ But at any moment that I may speak concerning a nation and concerning a kingdom to build &#91;it&#93; up and to plant &#91;it&#93;,

[[v24-18-10]]

^<<v24-18-10,10>>^ and it actually does what is bad in my eyes by not obeying my voice, I will also feel regret over the good that I said &#91;to myself&#93; to do for its good.’

[[v24-18-11]]

^<<v24-18-11,11>>^ “And now say, please, to the men of Judah and to the inhabitants of Jerusalem, ‘This is what Jehovah has said: “Here I am forming against YOU a calamity and thinking against YOU a thought. Turn back, please, each one from his bad way, and make YOUR ways and YOUR dealings good.”’”

[[v24-18-12]]

^<<v24-18-12,12>>^ And they said: “It is hopeless! For after our own thoughts we shall walk, and we are going to carry out each one the stubbornness of his bad heart.”

[[v24-18-13]]

^<<v24-18-13,13>>^ Therefore this is what Jehovah has said: “Ask for yourselves, please, among the nations. Who has heard things like these? There is a horrible thing that the virgin of Israel has done to an excess.

[[v24-18-14]]

^<<v24-18-14,14>>^ Will the snow of Lebʹa·non go away from the rock of the open field? Or will strange waters, cool, trickling, be dried up?

[[v24-18-15]]

^<<v24-18-15,15>>^ For my people have forgotten me in that they make sacrificial smoke to something worthless, and in that they make men stumble in their ways, the paths of long ago, to walk in roadways, a way not banked up,

[[v24-18-16]]

^<<v24-18-16,16>>^ in order to make their land an object of astonishment, for whistling at to time indefinite. Every last one passing along by it will stare in astonishment and shake his head.

[[v24-18-17]]

^<<v24-18-17,17>>^ As with an east wind I shall scatter them before the enemy. The back, and not the face, I shall show them in the day of their disaster.”

[[v24-18-18]]

^<<v24-18-18,18>>^ And they proceeded to say: “Come, men, and let us think out against Jeremiah some thoughts, for the law will not perish from the priest or counsel from the wise one or the word from the prophet. Come and let us strike him with the tongue, and let us pay no attention to any of his words.”

[[v24-18-19]]

^<<v24-18-19,19>>^ Do pay attention to me, O Jehovah, and listen to the voice of my opponents.^&#42;1^

[NOTE]
====
. Or, “contenders.” LXX, “pleading”; Sy, “oppression.”
====

[[v24-18-20]]

^<<v24-18-20,20>>^ Should bad be repaid for good? For they have excavated a pit for my soul. Remember my standing before you to speak good even concerning them, to turn back your rage from them.

[[v24-18-21]]

^<<v24-18-21,21>>^ Therefore give their sons over to the famine, and deliver them over to the power^&#42;1^ of the sword; and may their wives become women bereaved of children, and widows. And may their own men become those killed with deadly plague, their young men those struck down with the sword in the battle.

[NOTE]
====
. Lit., “hands.”
====

[[v24-18-22]]

^<<v24-18-22,22>>^ Let a cry be heard out of their houses, when you bring upon them suddenly a marauder band. For they have excavated a pit to capture me, and traps they have hid for my feet.

[[v24-18-23]]

^<<v24-18-23,23>>^ But you yourself, O Jehovah, well know all their counsel against me for &#91;my&#93; death. Do not cover over^&#42;1^ their error, and do not wipe out that sin of theirs from before you; but let them become those who are made to stumble before you. In the time of your anger take action against them.

[NOTE]
====
. Or, “Do not make atonement for.” Heb., ʼal-tekhap·perʹ.
====

'''

xref:024-jeremiah/024-jeremiah-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremiah/024-jeremiah-019.adoc#v24-19-0[Próximo Capítulo &#62;]