include::./index.adoc[]

[[v24-47-0]]
=== Jeremiah, 47
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-47-1]]

^<<v24-47-1,1>>^ This is what proved to be the word of Jehovah to Jeremiah the prophet concerning the Phi·lisʹtines before Pharʹaoh proceeded to strike down Gaʹza.

[[v24-47-2]]

^<<v24-47-2,2>>^ This is what Jehovah has said:
“Look! Waters are coming up from the north and have become a flooding torrent. And they will flood the land and what fills it, the city and those inhabiting it. And the men^&#42;1^ will certainly cry out, and everyone dwelling in the land must howl.

[NOTE]
====
. Or, “the earthling men.” Heb., ha·ʼa·dhamʹ.
====

[[v24-47-3]]

^<<v24-47-3,3>>^ At the sound of the stamping of the hoofs of his stallions, at the rattling of his war chariots, the turmoil of his wheels, the fathers will actually not turn around to the sons, because of the dropping down of &#91;their&#93; hands,

[[v24-47-4]]

^<<v24-47-4,4>>^ on account of the day that is coming to despoil all the Phi·lisʹtines, to cut off from Tyre and from Siʹdon every survivor that was helping. For Jehovah is despoiling the Phi·lisʹtines, who are the remaining ones from the island of Caphʹtor.

[[v24-47-5]]

^<<v24-47-5,5>>^ Baldness must come to Gaʹza. Ashʹke·lon has been put to silence. O remnant of their low plain, how long will you keep making cuts upon yourself?

[[v24-47-6]]

^<<v24-47-6,6>>^ “Aha, the sword of Jehovah! How long will you not stay quiet? Be shoved^&#42;1^ into your sheath. Take your repose and keep silent.

[NOTE]
====
. Lit., “Be gathered.”
====

[[v24-47-7]]

^<<v24-47-7,7>>^ “How can it stay quiet, when Jehovah himself has given a command to it? It is for Ashʹke·lon and for the coast of the sea. There is where he has designated it^&#42;1^ to be.”

[NOTE]
====
. “It,” fem. sing., referring to the “sword.”
====

'''

xref:024-jeremiah/024-jeremiah-046.adoc#v24-46-0[&#60; Capítulo Anterior] | <<v24-47-0,Topo>> | xref:024-jeremiah/024-jeremiah-048.adoc#v24-48-0[Próximo Capítulo &#62;]