include::./index.adoc[]

[[v24-27-0]]
=== Jeremiah, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-27-1]]

^<<v24-27-1,1>>^ In the beginning of the kingdom of Je·hoiʹa·kim^&#42;1^ the son of Jo·siʹah, the king of Judah, this word occurred to Jeremiah^&#42;2^ from Jehovah, saying:

[NOTE]
====
. “Jehoiakim,” MTLXXVg; Sy, the Arabic version and three Heb. mss, “Zed­e­ki­ah,” as in vss 3, 12.
. Heb., Yir·meyahʹ.
====

[[v24-27-2]]

^<<v24-27-2,2>>^ “This is what Jehovah has said to me, ‘Make for yourself bands and yoke bars, and you must put them upon your neck.

[[v24-27-3]]

^<<v24-27-3,3>>^ And you must send them to the king of Eʹdom and to the king of Moʹab and to the king of the sons of Amʹmon and to the king of Tyre and to the king of Siʹdon by the hand of the messengers who are coming to Jerusalem to Zed·e·kiʹah^&#42;1^ the king of Judah.

[NOTE]
====
. Meaning “Jehovah Is Righteousness.” Heb., Tsidh·qi·yaʹhu.
====

[[v24-27-4]]

^<<v24-27-4,4>>^ And you must give them a command for their masters,^&#42;1^ saying:
“‘“This is what Jehovah of armies, the God of Israel, has said; this is what YOU should say to YOUR masters,

[NOTE]
====
. “Their masters.” Heb., ʼadho·neh·khemʹ, pl. of ʼa·dhohnʹ, to denote more than one.
====

[[v24-27-5]]

^<<v24-27-5,5>>^ ‘I myself have made the earth, mankind^&#42;1^ and the beasts that are upon the surface of the earth by my great power and by my stretched-out arm; and I have given it to whom it has proved right in my eyes.

[NOTE]
====
. Or, “men.” Heb., ha·ʼa·dhamʹ.
====

[[v24-27-6]]

^<<v24-27-6,6>>^ And now I myself have given all these lands into the hand of Neb·u·chad·nezʹzar^&#42;1^ the king of Babylon,^&#42;2^ my servant; and even the wild beasts of the field I have given him to serve him.

[NOTE]
====
. “Nebuchadnezzar,” in 27:6–29:3; in 21:2 and elsewhere throughout the book, “Nebuchadrezzar.”
. “Babylon,” LXXVg; MTSy, “Babel.”
====

[[v24-27-7]]

^<<v24-27-7,7>>^ And all the nations must serve even him and his son and his grandson until the time even of his own land comes, and many nations and great kings must exploit him as a servant.’

[[v24-27-8]]

^<<v24-27-8,8>>^ “‘“‘And it must occur that the nation and the kingdom that will not serve him, even Neb·u·chad·nezʹzar the king of Babylon; and the one that will not put its neck under the yoke of the king of Babylon, with the sword and with the famine and with the pestilence I shall turn my attention upon that nation,’ is the utterance of Jehovah, ‘until I shall have finished them off by his hand.’

[[v24-27-9]]

^<<v24-27-9,9>>^ “‘“‘And as for YOU men, do not listen to YOUR prophets and to YOUR practicers of divination and to YOUR dreamers^&#42;1^ and to YOUR practicers of magic and to YOUR sorcerers, who are saying to YOU: “YOU men will not serve the king of Babylon.”

[NOTE]
====
. “Dreamers,” TLXXSyVg; M, “dreams.”
====

[[v24-27-10]]

^<<v24-27-10,10>>^ For falsehood is what they are prophesying to YOU, for the purpose of having YOU taken far away from off YOUR ground; and I shall have to disperse YOU, and YOU will have to perish.

[[v24-27-11]]

^<<v24-27-11,11>>^ “‘“‘And as for the nation that will bring its neck under the yoke of the king of Babylon and actually serve him, I will also let it rest upon its ground,’ is the utterance of Jehovah, ‘and it will certainly cultivate it and dwell in it.’”’”

[[v24-27-12]]

^<<v24-27-12,12>>^ Even to Zed·e·kiʹah^&#42;1^ the king of Judah I spoke according to all these words, saying: “Bring YOUR necks under the yoke of the king of Babylon and serve him and his people and keep on living.

[NOTE]
====
. “Zedekiah.” Heb., Tsidh·qi·yahʹ. Compare vs 3 ftn.
====

[[v24-27-13]]

^<<v24-27-13,13>>^ Why should you yourself and your people die by the sword, by the famine and by the pestilence according to what Jehovah has spoken to the nation that does not serve the king of Babylon?

[[v24-27-14]]

^<<v24-27-14,14>>^ And do not listen to the words of the prophets that are saying to YOU men, ‘YOU will not serve the king of Babylon,’ because falsehood is what they are prophesying to YOU.

[[v24-27-15]]

^<<v24-27-15,15>>^ “‘For I have not sent them,’ is the utterance of Jehovah, ‘but they are prophesying in my name falsely, to the end that I shall disperse YOU, and YOU will have to perish, YOU men and the prophets that are prophesying to YOU.’”

[[v24-27-16]]

^<<v24-27-16,16>>^ And to the priests and to all this people I spoke, saying: “This is what Jehovah has said, ‘Do not listen to the words of YOUR prophets that are prophesying to YOU, saying: “Look! The utensils of the house of Jehovah are being brought back from Babylon soon now!” For falsehood is what they are prophesying to YOU.

[[v24-27-17]]

^<<v24-27-17,17>>^ Do not listen to them. Serve the king of Babylon and keep on living. Why should this city become a devastated place?

[[v24-27-18]]

^<<v24-27-18,18>>^ But if they are prophets and if the word of Jehovah does exist with them, let them, please, beseech Jehovah of armies, that the utensils that are remaining over in the house of Jehovah and the house of the king of Judah and in Jerusalem may not come into Babylon.’

[[v24-27-19]]

^<<v24-27-19,19>>^ “For this is what Jehovah of armies has said concerning the pillars and concerning the sea and concerning the carriages and concerning the remainder of the utensils that are remaining over in this city,

[[v24-27-20]]

^<<v24-27-20,20>>^ that Neb·u·chad·nezʹzar the king of Babylon had not taken when he carried Jec·o·niʹah^&#42;1^ the son of Je·hoiʹa·kim, the king of Judah, into exile from Jerusalem to Babylon, together with all the nobles of Judah and Jerusalem;

[NOTE]
====
. See Es 2:6 ftn, “Jeconiah.”
====

[[v24-27-21]]

^<<v24-27-21,21>>^ for this is what Jehovah of armies, the God^&#42;1^ of Israel, has said concerning the utensils that are remaining over at the house of Jehovah and the house of the king of Judah and Jerusalem,

[NOTE]
====
. “The God of.” Heb., ʼElo·hehʹ.
====

[[v24-27-22]]

^<<v24-27-22,22>>^ ‘“To Babylon is where they will be brought and there they will continue to be until the day of my turning my attention to them,” is the utterance of Jehovah. “And I will bring them up and restore them to this place.”’”

'''

xref:024-jeremiah/024-jeremiah-026.adoc#v24-26-0[&#60; Capítulo Anterior] | <<v24-27-0,Topo>> | xref:024-jeremiah/024-jeremiah-028.adoc#v24-28-0[Próximo Capítulo &#62;]