include::./index.adoc[]

[[v24-19-0]]
=== Jeremiah, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-19-1]]

^<<v24-19-1,1>>^ This is what Jehovah said: “Go,^&#42;1^ and you must get an earthenware flask of a potter and some of the older men of the people and some of the older men of the priests.

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-19-2]]

^<<v24-19-2,2>>^ And you must go out to the valley of the son of Hinʹnom,^&#42;1^ which is at the entrance of the Gate of the Potsherds.^&#42;2^ And there you must proclaim the words that I shall speak to you.

[NOTE]
====
. “Valley of the son of Hinnom.” Heb., gehʼ ven-Hin·nomʹ; Lat., valʹlem fiʹli·i Enʹnom. See App 4C.
. “Gate of the Potsherds.” Because this gate opened upon the most easterly section of the valley of Hinnom, it is likely identical with the Gate of the Ash-heaps, or the Dung Gate. In Jerusalem in the Old Testament, p. 230, ftn 1, Dr. J. Simons says: “Instead of ‘Gate of the Potsherds’ it is possible to translate ‘Gate of the Potters’, or, better perhaps, ‘Gate of the Earthenware Pots.’ ”
====

[[v24-19-3]]

^<<v24-19-3,3>>^ And you must say, ‘Hear the word of Jehovah, O YOU kings of Judah and YOU inhabitants of Jerusalem. This is what Jehovah of armies, the God^&#42;1^ of Israel, has said:
“‘“Here I am bringing a calamity upon this place, of which when anyone hears, his ears will tingle;

[NOTE]
====
. “The God of.” Heb., ʼElo·hehʹ.
====

[[v24-19-4]]

^<<v24-19-4,4>>^ for the reason that they have left me and have proceeded to make this place unrecognizable and to make sacrificial smoke in it to other gods^&#42;1^ whom they had not known, they and their forefathers and the kings of Judah; and they have filled this place with the blood of the innocent ones.

[NOTE]
====
. “To . . . gods.” Heb., leʼ·lo·himʹ.
====

[[v24-19-5]]

^<<v24-19-5,5>>^ And they built the high places of the Baʹal in order to burn their sons in the fire as whole burnt offerings to the Baʹal, something that I had not commanded or spoken of, and that had not come up into my heart.”’

[[v24-19-6]]

^<<v24-19-6,6>>^ “‘“Therefore, look! there are days coming,” is the utterance of Jehovah, “when this place will be called no more Toʹpheth and the valley of the son of Hinʹnom, but the valley of the killing.

[[v24-19-7]]

^<<v24-19-7,7>>^ And I will make void the counsel of Judah and of Jerusalem in this place, and I will cause them to fall by the sword before their enemies and by the hand of those seeking for their soul. And I will give their dead bodies as food to the flying creatures of the heavens and to the beasts of the earth.

[[v24-19-8]]

^<<v24-19-8,8>>^ And I will make this city an object of astonishment and something to be whistled at. Every last one passing along by it will stare in astonishment and whistle over all its plagues.

[[v24-19-9]]

^<<v24-19-9,9>>^ And I will make them eat the flesh of their sons and the flesh of their daughters; and they will eat each one the flesh of his fellowman, because of the tightness and because of the stress with which their enemies and those seeking for their soul will hem them in.”’

[[v24-19-10]]

^<<v24-19-10,10>>^ “And you must break the flask before the eyes of the men who are going with you.

[[v24-19-11]]

^<<v24-19-11,11>>^ And you must say to them, ‘This is what Jehovah of armies has said: “In the same way I shall break this people and this city as someone breaks the vessel of the potter so that it is no more able to be repaired; and in Toʹpheth they will bury until there is no more place^&#42;1^ to bury.”’

[NOTE]
====
. Lit., “because of there being no place.”
====

[[v24-19-12]]

^<<v24-19-12,12>>^ “‘That is how I shall do to this place,’ is the utterance of Jehovah, ‘and to the inhabitants of it, even to make this city like Toʹpheth.

[[v24-19-13]]

^<<v24-19-13,13>>^ And the houses of Jerusalem and the houses of the kings of Judah must become like the place of Toʹpheth, unclean ones, that is, all the houses upon the roofs of which they made sacrificial smoke to all the army of the heavens and there was a pouring out of drink offerings to other gods.’”^&#42;1^

[NOTE]
====
. See vs 4 ftn.
====

[[v24-19-14]]

^<<v24-19-14,14>>^ And Jeremiah proceeded to come from Toʹpheth, to which Jehovah had sent him to prophesy, and to stand in the courtyard of the house of Jehovah and say to all the people:

[[v24-19-15]]

^<<v24-19-15,15>>^ “This is what Jehovah of armies, the God^&#42;1^ of Israel, has said, ‘Here I am bringing upon this city and upon all its cities all the calamity that I have spoken against it, because they have hardened their neck in order not to obey my words.’”

[NOTE]
====
. See vs 3 ftn.
====

'''

xref:024-jeremiah/024-jeremiah-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremiah/024-jeremiah-020.adoc#v24-20-0[Próximo Capítulo &#62;]