include::./index.adoc[]

[[v24-3-0]]
=== Jeremiah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-3-1]]

^<<v24-3-1,1>>^ There is a saying: “If a man^&#42;1^ should send away his wife^&#42;2^ and she should actually go away from him and become another man’s, should he return to her anymore?”
Has that land^&#42;3^ not positively been polluted?
“And you^&#42;4^ yourself have committed prostitution with many companions; and should there be a returning to me?” is the utterance of Jehovah.

[NOTE]
====
. Or, “husband.” Heb., ʼish.
. “His wife (woman).” Heb., ʼish·tohʹ.
. “Land,” MTSy; LXXVg, “woman.”
. “You,” fem. sing., addressed to Jerusalem, or Zion.
====

[[v24-3-2]]

^<<v24-3-2,2>>^ “Raise your eyes to the beaten paths and see. Where is it that you have not been raped?^&#42;1^ Alongside the ways you have sat for them, like an Arabian in the wilderness; and you keep polluting the land with your acts of prostitution and with your badness.

[NOTE]
====
. “Raped,” M; Mmargin, “lain with.”
====

[[v24-3-3]]

^<<v24-3-3,3>>^ So copious showers are withheld, and not even a spring rain has occurred. And the forehead of a wife committing prostitution is what has become yours. You have refused to feel humiliated.

[[v24-3-4]]

^<<v24-3-4,4>>^ Have you from now on called out to me, ‘My Father, you are the confidential friend of my youth!

[[v24-3-5]]

^<<v24-3-5,5>>^ Should one stay resentful to time indefinite, or keep watching &#91;something&#93; forever?’ Look! You have spoken, and you went on to do bad things and prevail.”

[[v24-3-6]]

^<<v24-3-6,6>>^ And Jehovah proceeded to say to me in the days of Jo·siʹah the king: “‘Have you seen what unfaithful Israel^&#42;1^ has done? She is going upon every high mountain and underneath every luxuriant tree, that she may commit prostitution there.

[NOTE]
====
. Lit., “the unfaithfulness (apostasy), Israel,” thus terming Israel a concrete example of unfaithfulness, or apostasy.
====

[[v24-3-7]]

^<<v24-3-7,7>>^ And after her doing all these things I kept saying that she should return even to me, but she did not return; and Judah kept looking at her own treacherous sister.

[[v24-3-8]]

^<<v24-3-8,8>>^ When I got to see that, for the very reason that unfaithful Israel had committed adultery, I sent her away and proceeded to give the certificate of her full divorce to her, yet treacherously dealing Judah her sister did not become afraid, but she herself also began to go and commit prostitution.

[[v24-3-9]]

^<<v24-3-9,9>>^ And her prostitution occurred because of &#91;her&#93; frivolous view, and she kept polluting the land and committing adultery with stones and with trees;

[[v24-3-10]]

^<<v24-3-10,10>>^ and even for all this her treacherous sister Judah did not return to me with all her heart, only falsely,’ is the utterance of Jehovah.”

[[v24-3-11]]

^<<v24-3-11,11>>^ And Jehovah went on to say to me: “Unfaithful Israel has proved her own soul to be more righteous than treacherously dealing Judah.

[[v24-3-12]]

^<<v24-3-12,12>>^ Go,^&#42;1^ and you must proclaim these words to the north and say:
“‘“Do return, O renegade Israel,” is the utterance of Jehovah.’ ‘“I shall not have my face drop &#91;angrily&#93; upon YOU people, for I am loyal,” is the utterance of Jehovah.’ ‘“I shall not stay resentful to time indefinite.

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-3-13]]

^<<v24-3-13,13>>^ Only take note of your error, for it is against Jehovah your God^&#42;1^ that you^&#42;2^ have transgressed. And you continued scattering your ways to the strangers under every luxuriant tree, but to my voice YOU people did not listen,” is the utterance of Jehovah.’”

[NOTE]
====
. “Your God.” Heb., ʼElo·haʹyikh, pl.
. “You,” fem. sing.
====

[[v24-3-14]]

^<<v24-3-14,14>>^ “Return, O YOU renegade sons,” is the utterance of Jehovah. “For I myself have become the husbandly owner of YOU people; and I will take YOU, one out of a city and two out of a family, and I will bring YOU to Zion.

[[v24-3-15]]

^<<v24-3-15,15>>^ And I will give YOU shepherds in agreement with my heart, and they will certainly feed^&#42;1^ YOU with knowledge and insight.

[NOTE]
====
. Or, “shepherd.”
====

[[v24-3-16]]

^<<v24-3-16,16>>^ And it must occur that YOU will become many and certainly bear fruit in the land^&#42;1^ in those days,” is the utterance of Jehovah. “No more will they say, ‘The ark of the covenant of Jehovah!’ nor will it come up into the heart, nor will they remember it or miss it, and no more will it be made.

[NOTE]
====
. “In the land (earth).” Heb., ba·ʼaʹrets.
====

[[v24-3-17]]

^<<v24-3-17,17>>^ In that time they will call Jerusalem the throne of Jehovah; and to her all the nations must be brought together to the name of Jehovah at Jerusalem, and they will no more walk after the stubbornness of their bad heart.”

[[v24-3-18]]

^<<v24-3-18,18>>^ “In those days they will walk, the house of Judah alongside^&#42;1^ the house of Israel, and together they will come out of the land of the north into the land that I gave as a hereditary possession to YOUR^&#42;2^ forefathers.

[NOTE]
====
. Or, “up to.”
. “Your,” pl., MVg; TLXXSy, “their.”
====

[[v24-3-19]]

^<<v24-3-19,19>>^ And I myself have said, ‘O how I proceeded to place you^&#42;1^ among the sons and to give you the desirable land, the hereditary possession of the ornament of the armies of the nations!’ And I further said, ‘“My Father!” YOU people will call out to me, and from following me YOU people will not turn back.’

[NOTE]
====
. “You,” fem. sing.
====

[[v24-3-20]]

^<<v24-3-20,20>>^ ‘Truly &#91;as&#93; a wife^&#42;1^ has treacherously gone from her companion, so YOU, O house of Israel, have dealt treacherously with me,’ is the utterance of Jehovah.”

[NOTE]
====
. Or, “woman.” Heb., ʼish·shahʹ.
====

[[v24-3-21]]

^<<v24-3-21,21>>^ On the beaten paths there has been heard a sound, the weeping, the entreaties of the sons of Israel. For they have twisted their way; they have forgotten Jehovah their God.^&#42;1^

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ, pl.
====

[[v24-3-22]]

^<<v24-3-22,22>>^ “Return, YOU renegade sons. I shall heal YOUR renegade condition.”^&#42;1^
“Here we are! We have come to you, for you, O Jehovah, are our God.

[NOTE]
====
. Or, “your state of unfaithfulness.” Lit., “your unfaithfulnesses.”
====

[[v24-3-23]]

^<<v24-3-23,23>>^ Truly the hills as well as the turmoil on the mountains belong to falsehood. Truly in Jehovah our God is the salvation of Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ But the shameful thing itself has eaten up the toil of our forefathers from our youth, their flocks and their herds, their sons and their daughters.

[[v24-3-25]]

^<<v24-3-25,25>>^ We lie down in our shame, and our humiliation keeps covering us; for it is toward Jehovah our God that we have sinned, we and our fathers from our youth on and down to this day, and we have not obeyed the voice of Jehovah our God.”

'''

xref:024-jeremiah/024-jeremiah-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremiah/024-jeremiah-004.adoc#v24-4-0[Próximo Capítulo &#62;]