include::./index.adoc[]

[[v24-49-0]]
=== Jeremiah, 49
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-49-1]]

^<<v24-49-1,1>>^ For the sons of Amʹmon this is what Jehovah has said: “Are there no sons that Israel has, or is there no inheritor that he has? Why is it that Malʹcam^&#42;1^ has taken possession of Gad,^&#42;2^ and his own people have taken up dwelling in &#91;Israel’s&#93;^&#42;3^ very cities?”

[NOTE]
====
. “Malcam” (meaning “Their King”), M; LXXSyVg, “Melchom”; LXXא,B, “Melchol”; T, “their king.”
. “Gad,” MLXXSyVg; T, “the land of Gad”; LXXא,A,B, “Gilead.”
. Or, “its.” Lit., “his.”
====

[[v24-49-2]]

^<<v24-49-2,2>>^ “‘Therefore, look! there are days coming,’ is the utterance of Jehovah, ‘and I will cause the alarm signal of war to be heard even against Rabʹbah of the sons of Amʹmon; and she will certainly become a mound of a desolate waste, and her dependent towns^&#42;1^ themselves will be set aflame in the very fire.’
“‘And Israel will actually take possession of those in possession of him,’ Jehovah has said.

[NOTE]
====
. Lit., “her daughters.”
====

[[v24-49-3]]

^<<v24-49-3,3>>^ “‘Howl, O Heshʹbon, for Aʹi has been despoiled! Cry out, O dependent towns of Rabʹbah. Gird sackcloth on yourselves. Wail, and rove about among the stone pens, for Malʹcam himself will go even into exile, his priests and his princes, all together.

[[v24-49-4]]

^<<v24-49-4,4>>^ Why do you brag about the low plains, your flowing low plain, O daughter unfaithful, you the one trusting in her treasures, &#91;saying:&#93; “Who will come to me?”’”

[[v24-49-5]]

^<<v24-49-5,5>>^ “‘Here I am bringing in upon you^&#42;1^ a dreadful thing,’ is the utterance of the Sovereign Lord, Jehovah of armies, ‘from all those round about you. And YOU people will certainly be dispersed, each one in his own direction, and there will be no one collecting together those running away.’”

[NOTE]
====
. “You,” fem. sing.
====

[[v24-49-6]]

^<<v24-49-6,6>>^ “‘But afterward I shall gather the captive ones of the sons of Amʹmon,’ is the utterance of Jehovah.”

[[v24-49-7]]

^<<v24-49-7,7>>^ For Eʹdom this is what Jehovah of armies has said: “Is there no longer any wisdom in Teʹman? Has counsel perished from those having understanding?^&#42;1^ Has their wisdom gone to putrefying?

[NOTE]
====
. “Those having understanding,” in agreement with LXXSy; MTVg, “the sons.”
====

[[v24-49-8]]

^<<v24-49-8,8>>^ Flee! Let yourselves give way! Go down deep in order to dwell, O inhabitants of Deʹdan! For the disaster of Eʹsau I will bring in upon him, the time that I must turn my attention to him.

[[v24-49-9]]

^<<v24-49-9,9>>^ If grape gatherers themselves actually came in to you, would they not let some gleanings remain? If thieves &#91;came in&#93; by night, they would certainly cause only as much ruin as they wanted.

[[v24-49-10]]

^<<v24-49-10,10>>^ But as for me, I will strip Eʹsau bare. I will uncover his places of concealment, and one will not be able to hide oneself. His offspring and his brothers and his neighbors will certainly be despoiled, and he will not be.

[[v24-49-11]]

^<<v24-49-11,11>>^ Do leave your fatherless boys. I myself shall preserve &#91;them&#93; alive, and your own widows will trust even in me.”

[[v24-49-12]]

^<<v24-49-12,12>>^ For this is what Jehovah has said: “Look! Although it is not their custom to drink the cup, they will drink without fail. And you yourself, will you be absolutely left unpunished? You will not be left unpunished, for you will drink without fail.”

[[v24-49-13]]

^<<v24-49-13,13>>^ “For by my own self I have sworn,” is the utterance of Jehovah, “that nothing but an object of astonishment, a reproach, a devastation and a malediction will Bozʹrah become; and all her own cities will become devastated places to time indefinite.”

[[v24-49-14]]

^<<v24-49-14,14>>^ There is a report that I have heard from Jehovah, and there is an envoy that is sent among the nations, &#91;saying:&#93; “Collect yourselves together, and come against her, and rise up to battle.”

[[v24-49-15]]

^<<v24-49-15,15>>^ “For, look! I have made you small indeed among the nations, despised among mankind.^&#42;1^

[NOTE]
====
. Or, “among men.” Heb., ba·ʼa·dhamʹ.
====

[[v24-49-16]]

^<<v24-49-16,16>>^ The shuddering you caused has deceived you, the presumptuousness of your heart, O you who are residing in the retreats of the crag, holding the height of the hill. Although you build your nest high up just like an eagle, down from there I shall bring you,” is the utterance of Jehovah.

[[v24-49-17]]

^<<v24-49-17,17>>^ “And Eʹdom must become an object of astonishment. Everyone passing along by her will stare in astonishment and whistle on account of all her plagues.

[[v24-49-18]]

^<<v24-49-18,18>>^ Just as in the overthrow of Sodʹom and Go·morʹrah and her neighbor &#91;towns&#93;,” Jehovah has said, “no man will dwell there, and no son of mankind^&#42;1^ will reside in her as an alien.

[NOTE]
====
. Or, “son of earthling man.” Heb., ben-ʼa·dhamʹ.
====

[[v24-49-19]]

^<<v24-49-19,19>>^ “Look! Someone will come up just like a lion from the proud &#91;thickets&#93; along the Jordan to the durable abiding place, but in a moment I will make him run away from her. And the one who is chosen I shall appoint over her. For who is like me, and who will challenge me, and who, now, is the shepherd that can stand before me?

[[v24-49-20]]

^<<v24-49-20,20>>^ Therefore hear, O men, the counsel of Jehovah that he has formulated against Eʹdom, and his thoughts that he has thought out against the inhabitants of Teʹman: Surely the little ones of the flock will be dragged about. Surely on account of them he will make their dwelling place become desolate.

[[v24-49-21]]

^<<v24-49-21,21>>^ At the sound of their falling the earth has begun to rock. There is an outcry! The sound of it has been heard even at the Red Sea.

[[v24-49-22]]

^<<v24-49-22,22>>^ Look! Just like an eagle someone will ascend and pounce down, and he will spread out his wings over Bozʹrah; and the heart of the mighty men of Eʹdom will actually become in that day like the heart of the wife having distress in childbirth.”

[[v24-49-23]]

^<<v24-49-23,23>>^ For Damascus: “Haʹmath and Arʹpad have become ashamed, for it is a bad report that they have heard. They have disintegrated. In the sea there is anxious care; it is not able to keep undisturbed.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damascus has lost courage. She has turned to flee, and sheer panic has seized her. Distress and birth pangs themselves have taken hold of her, as with a woman that is giving birth.

[[v24-49-25]]

^<<v24-49-25,25>>^ How is it that the city of praise has not been abandoned, the town of exultation?

[[v24-49-26]]

^<<v24-49-26,26>>^ “Therefore her young men will fall in her public squares, and all the men of war themselves will be brought to silence in that day,” is the utterance of Jehovah of armies.

[[v24-49-27]]

^<<v24-49-27,27>>^ “And I will set a fire ablaze on the wall of Damascus, and it will certainly devour the dwelling towers of Ben-haʹdad.”

[[v24-49-28]]

^<<v24-49-28,28>>^ For Keʹdar and the kingdoms of Haʹzor, which Neb·u·chad·rezʹzar the king of Babylon struck down, this is what Jehovah has said: “Rise up, go up to Keʹdar, O men, and despoil the sons of the East.

[[v24-49-29]]

^<<v24-49-29,29>>^ Their own tents and their own flocks will be taken, their tent cloths and all their articles. And their own camels will be carried off from them. And they will certainly cry out to them, ‘Fright is all around!’”

[[v24-49-30]]

^<<v24-49-30,30>>^ “Flee, take flight far away; go down deep in order to dwell, O inhabitants of Haʹzor,” is the utterance of Jehovah. “For Neb·u·chad·rezʹzar the king of Babylon has formulated a counsel even against YOU and has thought out against YOU^&#42;1^ a thought.”

[NOTE]
====
. “You,” MmarginTLXXVg and more than 100 Heb. mss; MSy, “them.”
====

[[v24-49-31]]

^<<v24-49-31,31>>^ “Rise up, O men, go up against the nation that is at ease, dwelling in security!” is the utterance of Jehovah.
“No doors and no bar does it have. Solitary they reside.

[[v24-49-32]]

^<<v24-49-32,32>>^ And their camels must become a plunder, and the multitude of their livestock a spoil. And I will scatter them to every wind, those who have their hair clipped at the temples; and from all regions near it I shall bring in their disaster,” is the utterance of Jehovah.

[[v24-49-33]]

^<<v24-49-33,33>>^ “And Haʹzor must become the lair of jackals, a desolate waste to time indefinite. No man^&#42;1^ will dwell there, and in her no son of mankind^&#42;2^ will reside as an alien.”

[NOTE]
====
. “Man.” Heb., ʼish.
. See vs 18 ftn.
====

[[v24-49-34]]

^<<v24-49-34,34>>^ This is what occurred as the word of Jehovah to Jeremiah the prophet concerning Eʹlam in the beginning of the kingship of Zed·e·kiʹah the king of Judah, saying:

[[v24-49-35]]

^<<v24-49-35,35>>^ “This is what Jehovah of armies has said, ‘Here I am breaking the bow of Eʹlam, the beginning of their mightiness.

[[v24-49-36]]

^<<v24-49-36,36>>^ And I will bring in upon Eʹlam the four winds from the four extremities of the heavens. And I will scatter them to all these winds, and there will prove to be no nation to which the dispersed ones of Eʹlam^&#42;1^ will not come.’”

[NOTE]
====
. “Of Elam,” MmarginTLXXSyVg and many Heb. mss; M, “to (of) time indefinite.”
====

[[v24-49-37]]

^<<v24-49-37,37>>^ “And I will shatter the Eʹlam·ites before their enemies and before those seeking for their soul; and I will bring upon them a calamity, my burning anger,” is the utterance of Jehovah. “And I will send after them the sword until I shall have exterminated them.”

[[v24-49-38]]

^<<v24-49-38,38>>^ “And I will set my throne in Eʹlam, and I will destroy out of there the king and the princes,” is the utterance of Jehovah.

[[v24-49-39]]

^<<v24-49-39,39>>^ “And it will certainly occur in the final part of the days that I shall gather the captive ones of Eʹlam,” is the utterance of Jehovah.

'''

xref:024-jeremiah/024-jeremiah-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremiah/024-jeremiah-050.adoc#v24-50-0[Próximo Capítulo &#62;]