include::./index.adoc[]

[[v24-48-0]]
=== Jeremiah, 48
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-48-1]]

^<<v24-48-1,1>>^ For Moʹab this is what Jehovah of armies, the God of Israel, has said: “Woe to Neʹbo, for she has been despoiled! Kir·i·a·thaʹim has been put to shame, has been captured. The secure height has been put to shame and been put in terror.

[[v24-48-2]]

^<<v24-48-2,2>>^ No more is there any praise of Moʹab. In Heshʹbon they have thought out against her a calamity: ‘Come, men, and let us cut her off from being a nation.’
“You, too, O Madʹmen, should keep silent. After you there walks a sword.

[[v24-48-3]]

^<<v24-48-3,3>>^ There is the sound of an outcry from Hor·o·naʹim, a despoiling and great breaking down.

[[v24-48-4]]

^<<v24-48-4,4>>^ Moʹab has been broken down. Her little ones have caused a cry to be heard.

[[v24-48-5]]

^<<v24-48-5,5>>^ For on the way up to Luʹhith it is with weeping that one goes up—there is a weeping. For on the way down from Hor·o·naʹim there is a distressing outcry over the breakdown that people have heard.

[[v24-48-6]]

^<<v24-48-6,6>>^ “Take to flight; provide escape for YOUR souls,^&#42;1^ and YOU should become like a juniper tree^&#42;2^ in the wilderness.

[NOTE]
====
. Lit., “your soul,” sing. but in a collective sense. Heb., naph·shekhemʹ; Gr., psy·khasʹ; Lat., aʹni·mas.
. “A juniper tree.” The meaning of the Heb. word is uncertain; by a correction in agreement with LXX, “a wild ass.”
====

[[v24-48-7]]

^<<v24-48-7,7>>^ Because your^&#42;1^ trust is in your works and in your treasures, you yourself will also be captured. And Cheʹmosh will certainly go forth into exile, his priests and his princes at the same time.

[NOTE]
====
. “Your,” fem. sing., referring to Moab.
====

[[v24-48-8]]

^<<v24-48-8,8>>^ And the despoiler will come in on every city, and there will be no city that can make its escape. And the low plain will certainly perish and the level land be annihilated, a thing that Jehovah has said.

[[v24-48-9]]

^<<v24-48-9,9>>^ “Give a road mark to Moʹab, YOU people, for at the falling in ruins she will go forth; and her very cities will become a mere object of astonishment, with no one dwelling in them.

[[v24-48-10]]

^<<v24-48-10,10>>^ “Cursed be the one that is carrying out the mission of Jehovah neglectfully; and cursed be the one that is holding back his sword from blood!

[[v24-48-11]]

^<<v24-48-11,11>>^ “The Moʹab·ites^&#42;1^ have been at ease since their^&#42;2^ youth, and they^&#42;3^ are keeping undisturbed on their dregs. And they have not been emptied from one vessel into another vessel, and into exile they have not gone. That is why their taste has stood still within them,^&#42;4^ and their very scent has not been changed.

[NOTE]
====
. Lit., “Moab.”
. Lit., “his.”
. Lit., “he.”
. Lit., “him.” “Moab” is fem. in vss 1-9.
====

[[v24-48-12]]

^<<v24-48-12,12>>^ “‘Therefore, look! there are days coming,’ is the utterance of Jehovah, ‘and I will send to them &#91;vessel&#93; tilters, and they will certainly tilt them; and their vessels they will empty out, and their^&#42;1^ large jars they will dash to pieces.

[NOTE]
====
. “Their,” masc. pl., referring to the men of Moab.
====

[[v24-48-13]]

^<<v24-48-13,13>>^ And the Moʹab·ites will have to be ashamed of Cheʹmosh, just as those of the house of Israel have become ashamed of Bethʹel their confidence.

[[v24-48-14]]

^<<v24-48-14,14>>^ How dare YOU people say: “We are mighty men and men of vital energy for the war”?’

[[v24-48-15]]

^<<v24-48-15,15>>^ “‘Moʹab has been despoiled, and one has gone up against her own cities. And their choicest young men themselves have gone down to the slaughtering,’ is the utterance of the King, whose name is Jehovah of armies.

[[v24-48-16]]

^<<v24-48-16,16>>^ “The disaster on the Moʹab·ites is near to come, and their very calamity is actually hurrying up very much.

[[v24-48-17]]

^<<v24-48-17,17>>^ All those round about them will have to sympathize with them, even all those knowing their name. Say, YOU people, ‘O how the rod of strength has been broken, the staff of beauty!’

[[v24-48-18]]

^<<v24-48-18,18>>^ “Get down from glory, and sit down in thirst, O inhabitress of the daughter of Diʹbon; for the despoiler of Moʹab has come up against you. He will actually bring your fortified places to ruin.

[[v24-48-19]]

^<<v24-48-19,19>>^ “Stand still and look out for the way itself, O inhabitress of A·roʹer. Ask him that is fleeing and her that is making her escape. Say, ‘What has been brought about?’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moʹab has been put to shame, for she has been struck with terror. Howl and cry out. Tell in Arʹnon, O men, that Moʹab has been despoiled.

[[v24-48-21]]

^<<v24-48-21,21>>^ And judgment itself has come to the land of level country, to Hoʹlon and to Jaʹhaz^&#42;1^ and against Mephʹa·ath,

[NOTE]
====
. Heb., Yahʹtsah.
====

[[v24-48-22]]

^<<v24-48-22,22>>^ and against Diʹbon and against Neʹbo and against Beth-dib·la·thaʹim,

[[v24-48-23]]

^<<v24-48-23,23>>^ and against Kir·i·a·thaʹim and against Beth-gaʹmul and against Beth-meʹon

[[v24-48-24]]

^<<v24-48-24,24>>^ and against Keʹri·oth and against Bozʹrah and against all the cities of the land of Moʹab, those far away and those near.

[[v24-48-25]]

^<<v24-48-25,25>>^ “‘The horn of Moʹab has been cut down, and his own arm has been broken,’ is the utterance of Jehovah.

[[v24-48-26]]

^<<v24-48-26,26>>^ ‘Make him drunk, O men, for he has put on great airs against Jehovah himself; and Moʹab has slapped around in his vomit, and he has become an object of ridicule, even he himself.

[[v24-48-27]]

^<<v24-48-27,27>>^ “‘And did not Israel become a mere object of ridicule to you?^&#42;1^ Or was he^&#42;2^ found among outright thieves? For you would shake yourself just as often as you spoke against him.

[NOTE]
====
. “You,” masc. sing.
. “He,” Mmargin; M, “she.”
====

[[v24-48-28]]

^<<v24-48-28,28>>^ “‘Leave the cities and reside on the crag, YOU inhabitants of Moʹab, and become like the dove that makes its nest in the regions of the mouth of the hollow.’”

[[v24-48-29]]

^<<v24-48-29,29>>^ “We have heard of the pride of Moʹab—he is very haughty—of his highness and of his pride and of his haughtiness and of the loftiness of his heart.”

[[v24-48-30]]

^<<v24-48-30,30>>^ “‘I myself have known his fury,’ is the utterance of Jehovah, ‘and that is not the way it will be; his empty talk—they will not actually do in just that way.

[[v24-48-31]]

^<<v24-48-31,31>>^ That is why it is over Moʹab that I shall howl, and for Moʹab in his entirety I shall cry out. For the men of Kir-heʹres one shall moan.

[[v24-48-32]]

^<<v24-48-32,32>>^ “‘With more than the weeping for Jaʹzer I shall weep for you, O vine of Sibʹmah. Your own flourishing shoots have crossed over the sea. To the sea—&#91;to&#93; Jaʹzer—they have reached. Upon your summer fruitage and upon your grape gathering the despoiler himself has fallen.

[[v24-48-33]]

^<<v24-48-33,33>>^ And rejoicing and joyfulness have been taken away from the orchard and from the land of Moʹab. And from the winepresses I have caused the wine itself to cease. No one will be doing the treading with shouting. The shouting will be no shouting.’”

[[v24-48-34]]

^<<v24-48-34,34>>^ “‘From the cry in Heshʹbon clear to E·le·aʹleh, clear to Jaʹhaz they have given forth their voice, from Zoʹar clear to Hor·o·naʹim, to Egʹlath-she·liʹshi·yah; for even the waters of Nimʹrim themselves will become mere desolations.

[[v24-48-35]]

^<<v24-48-35,35>>^ And I will cause to cease from Moʹab,’ is the utterance of Jehovah, ‘the one bringing up an offering upon the high place and the one making sacrificial smoke to his god.^&#42;1^

[NOTE]
====
. Or, “to his gods.” Heb., leʼ·lo·havʹ; Lat., diʹis.
====

[[v24-48-36]]

^<<v24-48-36,36>>^ That is why my own heart will be boisterous for Moʹab himself, just like flutes; and for the men of Kir-heʹres my very heart will be boisterous, just like flutes. That is why the very abundance that he has produced will certainly perish.

[[v24-48-37]]

^<<v24-48-37,37>>^ For upon every head there is baldness, and every beard is clipped. Upon all hands there are cuts, and upon the hips there is sackcloth!’”

[[v24-48-38]]

^<<v24-48-38,38>>^ “‘On all the roofs of Moʹab and in her public squares—all of it—there is wailing; for I have broken Moʹab just like a vessel in which there is no delight,’ is the utterance of Jehovah.

[[v24-48-39]]

^<<v24-48-39,39>>^ ‘O how she has become terrified!^&#42;1^ Howl, YOU people! O how Moʹab has turned the back! He has become ashamed. And Moʹab has become an object of ridicule and something terrifying to all those round about him.’”

[NOTE]
====
. Or, “she has been shattered!”
====

[[v24-48-40]]

^<<v24-48-40,40>>^ “For this is what Jehovah has said, ‘Look! Just like an eagle that pounces, someone must also spread his wings over Moʹab.

[[v24-48-41]]

^<<v24-48-41,41>>^ The towns will actually be captured, and her own strong places will certainly be seized. And the heart of the mighty men of Moʹab must become in that day like the heart of a wife having childbirth distress.’”

[[v24-48-42]]

^<<v24-48-42,42>>^ “‘And Moʹab will certainly be annihilated from being a people, for it is against Jehovah that he has put on great airs.

[[v24-48-43]]

^<<v24-48-43,43>>^ Dread and the hollow and the trap are upon you, O inhabitant of Moʹab,’ is the utterance of Jehovah.

[[v24-48-44]]

^<<v24-48-44,44>>^ ‘Anyone fleeing because of the dread will fall into the hollow; and anyone coming up out of the hollow will be caught in the trap.’
“‘For I shall bring upon her, upon Moʹab, the year of their being given attention,’ is the utterance of Jehovah.

[[v24-48-45]]

^<<v24-48-45,45>>^ ‘In the shadow of Heshʹbon those fleeing have stood still without power. For a very fire will certainly go forth out of Heshʹbon, and a flame from the midst of Siʹhon; and it will devour the temples of Moʹab and the crown of the head of the sons of uproar.’

[[v24-48-46]]

^<<v24-48-46,46>>^ “‘Woe to you,^&#42;1^ O Moʹab! The people of Cheʹmosh have perished. For your sons have been taken as captives and your daughters as captives.

[NOTE]
====
. “You,” masc. sing.
====

[[v24-48-47]]

^<<v24-48-47,47>>^ And I will gather the captive ones of Moʹab in the final part of the days,’ is the utterance of Jehovah. ‘Down to this point is the judgment upon Moʹab.’”

'''

xref:024-jeremiah/024-jeremiah-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremiah/024-jeremiah-049.adoc#v24-49-0[Próximo Capítulo &#62;]