include::./index.adoc[]

[[v24-40-0]]
=== Jeremiah, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-40-1]]

^<<v24-40-1,1>>^ The word that occurred to Jeremiah from Jehovah after Neb·uʹzar·adʹan the chief of the bodyguard sent him from Raʹmah, when he took him while he was bound with handcuffs in the midst of all the exiles of Jerusalem and of Judah, who were being taken into exile in Babylon.

[[v24-40-2]]

^<<v24-40-2,2>>^ Then the chief of the bodyguard took Jeremiah and said to him: “Jehovah your God himself spoke this calamity against this place,

[[v24-40-3]]

^<<v24-40-3,3>>^ that Jehovah might bring &#91;it&#93; true and do just as he has spoken, because YOU people have sinned against Jehovah and have not obeyed his voice. And this thing has happened to YOU.

[[v24-40-4]]

^<<v24-40-4,4>>^ And now, look! I have let you loose today from the handcuffs that were upon your hands. If it is good in your eyes to come with me to Babylon, come, and I shall keep my eye upon you. But if it is bad in your eyes to come with me to Babylon, refrain. See! The entire land is before you. To wherever it is good and right in your eyes to go, go there.”

[[v24-40-5]]

^<<v24-40-5,5>>^ And he was yet not one that would return, when &#91;Neb·uʹzar·adʹan said&#93;: “Do return to Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan, whom the king of Babylon has commissioned over the cities of Judah, and dwell with him in the midst of the people; or to wherever it is right in your eyes to go, go.”
And the chief of the bodyguard then gave him a food allowance and a present and let him go.

[[v24-40-6]]

^<<v24-40-6,6>>^ Accordingly Jeremiah came to Ged·a·liʹah the son of A·hiʹkam at Mizʹpah and took up dwelling with him in the midst of the people who were left remaining in the land.

[[v24-40-7]]

^<<v24-40-7,7>>^ In time all the chiefs^&#42;1^ of the military forces who were in the field, they and their men, got to hear that the king of Babylon had commissioned Ged·a·liʹah the son of A·hiʹkam over the land and that he had commissioned him &#91;over&#93; the men and women and little children and some of the lowly people of the land, who had not been taken into exile in Babylon.

[NOTE]
====
. Or, “the princes of.” Heb., sa·rehʹ.
====

[[v24-40-8]]

^<<v24-40-8,8>>^ So they came to Ged·a·liʹah at Mizʹpah, even Ishʹma·el the son of Neth·a·niʹah^&#42;1^ and Jo·haʹnan and Jonʹa·than, the sons of Ka·reʹah, and Se·raiʹah the son of Tan·huʹmeth and the sons of Eʹphai the Ne·tophʹa·thite and Jez·a·niʹah^&#42;2^ the son of the Ma·acʹa·thite, they and their men.

[NOTE]
====
. Meaning “Jehovah Has Given.” Heb., Nethan·yaʹhu.
. “And Jezaniah.” Heb., wI·zan·yaʹhu, meaning “Jehovah Gives Ear.”
====

[[v24-40-9]]

^<<v24-40-9,9>>^ And Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan proceeded to swear to them and to their men, saying: “Do not be afraid of serving the Chal·deʹans. Continue dwelling in the land and serve the king of Babylon, and it will go well with YOU.

[[v24-40-10]]

^<<v24-40-10,10>>^ And as for me, here I am dwelling in Mizʹpah, in order to stand before the Chal·deʹans who will come to us. And as for YOU yourselves, gather wine and summer fruits and oil and put &#91;them&#93; in YOUR vessels and dwell in YOUR cities that YOU have seized.”

[[v24-40-11]]

^<<v24-40-11,11>>^ And all the Jews that were in Moʹab and among the sons of Amʹmon and in Eʹdom and those who were in all the &#91;other&#93; lands, they also heard that the king of Babylon had given a remnant to Judah and that he had commissioned over them Ged·a·liʹah the son of A·hiʹkam the son of Shaʹphan.

[[v24-40-12]]

^<<v24-40-12,12>>^ And all the Jews began to return from all the places to which they had been dispersed, and they kept coming into the land of Judah to Ged·a·liʹah at Mizʹpah. And they went gathering wine and summer fruits in very great quantity.

[[v24-40-13]]

^<<v24-40-13,13>>^ As for Jo·haʹnan the son of Ka·reʹah and all the chiefs of the military forces who were in the field, they came to Ged·a·liʹah at Mizʹpah.

[[v24-40-14]]

^<<v24-40-14,14>>^ And they proceeded to say to him: “Do you not at all know that Baʹa·lis, the king of the sons of Amʹmon, himself has sent Ishʹma·el the son of Neth·a·niʹah to strike you to the soul?” But Ged·a·liʹah the son of A·hiʹkam did not believe them.

[[v24-40-15]]

^<<v24-40-15,15>>^ And Jo·haʹnan the son of Ka·reʹah himself said to Ged·a·liʹah, in a place of concealment in Mizʹpah: “I want to go, now, and strike down Ishʹma·el the son of Neth·a·niʹah, as no one at all will know. Why should he strike you to the soul,^&#42;1^ and why must all those of Judah who are being collected together to you be scattered and the remnant of Judah perish?”

[NOTE]
====
. “Should he strike you to the soul,” that is, mortally. Heb., yak·kekʹkah neʹphesh; Gr., pa·taʹxei sou psy·khenʹ; Lat., in·ter·fiʹci·at aʹni·mam tuʹam. See App 4A.
====

[[v24-40-16]]

^<<v24-40-16,16>>^ But Ged·a·liʹah the son of A·hiʹkam said to Jo·haʹnan the son of Ka·reʹah: “Do not do this thing, for it is a falsehood that you are speaking concerning Ishʹma·el.”

'''

xref:024-jeremiah/024-jeremiah-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremiah/024-jeremiah-041.adoc#v24-41-0[Próximo Capítulo &#62;]