include::./index.adoc[]

[[v24-21-0]]
=== Jeremiah, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-21-1]]

^<<v24-21-1,1>>^ The word that occurred to Jeremiah from Jehovah, when King Zed·e·kiʹah^&#42;1^ sent to him Pashʹhur the son of Mal·chiʹah and Zeph·a·niʹah the son of Ma·a·seiʹah, the priest, saying:

[NOTE]
====
. See 1:3 ftn.
====

[[v24-21-2]]

^<<v24-21-2,2>>^ “Please inquire in our behalf of Jehovah, because Neb·u·chad·rezʹzar the king of Babylon is making war against us. Perhaps Jehovah will do with us according to all his wonderful works, so that he will withdraw from us.”

[[v24-21-3]]

^<<v24-21-3,3>>^ And Jeremiah proceeded to say to them: “This is what YOU will say to Zed·e·kiʹah,

[[v24-21-4]]

^<<v24-21-4,4>>^ ‘This is what Jehovah the God of Israel has said: “Here I am turning in reverse the weapons of war that are in the hand of YOU people, with which YOU are fighting the king of Babylon, and the Chal·deʹans who are laying siege against YOU outside the wall, and I will gather them into the middle of this city.

[[v24-21-5]]

^<<v24-21-5,5>>^ And I myself will fight against YOU with a stretched-out hand and with a strong arm and with anger and with rage and with great indignation.

[[v24-21-6]]

^<<v24-21-6,6>>^ And I will strike the inhabitants of this city, both man^&#42;1^ and beast. With a great pestilence they will die.”’

[NOTE]
====
. Or, “the earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v24-21-7]]

^<<v24-21-7,7>>^ “‘“And after that,” is the utterance of Jehovah, “I shall give Zed·e·kiʹah the king of Judah and his servants and the people and those who are remaining over in this city from the pestilence, from the sword and from the famine, into the hand of Neb·u·chad·rezʹzar the king of Babylon, even into the hand of their enemies and into the hand of those who are seeking for their soul, and he will certainly strike them with the edge^&#42;1^ of the sword. He will not feel sorry for them, nor will he show compassion or have any mercy.”’

[NOTE]
====
. Lit., “mouth.”
====

[[v24-21-8]]

^<<v24-21-8,8>>^ “And to this people you will say, ‘This is what Jehovah has said: “Here I am putting before YOU people the way of life and the way of death.

[[v24-21-9]]

^<<v24-21-9,9>>^ The one sitting still in this city will die by the sword and by the famine and by the pestilence; but the one who is going out and who actually falls away^&#42;1^ to the Chal·deʹans who are laying siege against YOU will keep living, and his soul will certainly come to be his as a spoil.”’

[NOTE]
====
. Or, “actually deserts.”
====

[[v24-21-10]]

^<<v24-21-10,10>>^ “‘“For I have set my face against this city for calamity and not for good,” is the utterance of Jehovah. “Into the hand of the king of Babylon it will be given, and he will certainly burn it with fire.”

[[v24-21-11]]

^<<v24-21-11,11>>^ “‘And as regards the household of the king of Judah, hear, O men, the word of Jehovah.

[[v24-21-12]]

^<<v24-21-12,12>>^ O house of David, this is what Jehovah has said: “Every morning render sentence in justice, and deliver the one being robbed out of the hand of the defrauder, that my rage may not go forth just like a fire and actually burn and there be no one to extinguish it because of the badness of YOUR dealings.”’

[[v24-21-13]]

^<<v24-21-13,13>>^ “‘Here I am against you, O inhabitress of the low plain, O rock of the level land,’ is the utterance of Jehovah. ‘As for YOU who are saying: “Who will descend against us? And who will come into our dwellings?”

[[v24-21-14]]

^<<v24-21-14,14>>^ I will also hold an accounting against YOU according to the fruitage of YOUR dealings,’ is the utterance of Jehovah. ‘And I will set a fire ablaze in her forest, and it will certainly devour all the things round about her.’”

'''

xref:024-jeremiah/024-jeremiah-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremiah/024-jeremiah-022.adoc#v24-22-0[Próximo Capítulo &#62;]