include::./index.adoc[]

[[v24-16-0]]
=== Jeremiah, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-16-1]]

^<<v24-16-1,1>>^ And the word of Jehovah continued to occur to me, saying:

[[v24-16-2]]

^<<v24-16-2,2>>^ “You must not take for yourself a wife, and you must not come to have sons and daughters in this place.

[[v24-16-3]]

^<<v24-16-3,3>>^ For this is what Jehovah has said concerning the sons and concerning the daughters that are born in this place, and concerning their mothers who are giving them birth and concerning their fathers who are causing their birth in this land,

[[v24-16-4]]

^<<v24-16-4,4>>^ ‘With deaths from maladies they will die. They will not be bewailed, neither will they be buried. As manure upon the surface of the ground they will become; and by the sword and by famine they will come to an end, and their dead bodies will actually serve as food for the flying creatures of the heavens and for the beasts of the earth.’

[[v24-16-5]]

^<<v24-16-5,5>>^ “For this is what Jehovah has said, ‘Do not enter into the house of a mourners’ feast, and do not go to bewail and do not sympathize with them.’
“‘For I have taken away my peace from this people,’ is the utterance of Jehovah, ‘even loving-kindness^&#42;1^ and mercies.

[NOTE]
====
. Or, “loyal love.”
====

[[v24-16-6]]

^<<v24-16-6,6>>^ And they will certainly die, the great ones and the small ones, in this land. They will not be buried, neither will people beat themselves for them, nor will anyone make cuts upon himself or make himself bald for them.

[[v24-16-7]]

^<<v24-16-7,7>>^ And they will not deal out to them any bread on account of mourning to comfort someone over the dead; neither will they give them the cup of consolation to drink on account of one’s father and on account of one’s mother.

[[v24-16-8]]

^<<v24-16-8,8>>^ And you must enter no house of banqueting at all to sit down with them to eat and to drink.’

[[v24-16-9]]

^<<v24-16-9,9>>^ “For this is what Jehovah of armies, the God^&#42;1^ of Israel, has said, ‘Here I am causing to cease out of this place before the eyes of YOU people and in YOUR days the voice of exultation and the voice of rejoicing, the voice of the bridegroom and the voice of the bride.’

[NOTE]
====
. “The God of.” Heb., ʼElo·hehʹ.
====

[[v24-16-10]]

^<<v24-16-10,10>>^ “And it must occur that, when you tell to this people all these words and they actually say to you, ‘On what account has Jehovah spoken against us all this great calamity, and what is our error and what is our sin with which we have sinned against Jehovah our God?’

[[v24-16-11]]

^<<v24-16-11,11>>^ you must also say to them, ‘“On account of the fact that YOUR fathers left me,” is the utterance of Jehovah, “and they kept going after other gods^&#42;1^ and serving them and bowing down to them. But me they left, and my law they did not keep.

[NOTE]
====
. “Gods.” Heb., ʼelo·himʹ.
====

[[v24-16-12]]

^<<v24-16-12,12>>^ And YOU yourselves have acted worse in YOUR doing than YOUR fathers, and here YOU are walking each one after the stubbornness of his bad heart in not obeying me.

[[v24-16-13]]

^<<v24-16-13,13>>^ And I will hurl YOU out from off this land into the land that YOU yourselves have not known, neither YOUR fathers, and there YOU will have to serve other gods day and night, because I shall not give YOU any favor.”’

[[v24-16-14]]

^<<v24-16-14,14>>^ “‘Therefore,^&#42;1^ look! days are coming,’ is the utterance of Jehovah, ‘when it will no more be said: “As Jehovah is alive who brought the sons of Israel up out of the land of Egypt!”

[NOTE]
====
. Or, “As a result.”
====

[[v24-16-15]]

^<<v24-16-15,15>>^ but: “As Jehovah is alive who brought the sons of Israel up out of the land of the north and out of all the lands to which he had dispersed them!” and I shall certainly bring them back to their soil, which I gave to their forefathers.’

[[v24-16-16]]

^<<v24-16-16,16>>^ “‘Here I am sending for many fishers,’ is the utterance of Jehovah, ‘and they will certainly fish for them; and afterward I shall send for many hunters, and they will certainly hunt them from every mountain and from every hill and out of the clefts of the crags.

[[v24-16-17]]

^<<v24-16-17,17>>^ For my eyes are upon all their ways. They have not been concealed from before me, neither has their error been hid from in front of my eyes.

[[v24-16-18]]

^<<v24-16-18,18>>^ And, first of all, I will repay the full amount^&#42;1^ of their error and of their sin, on account of their profaning my land. With the corpses of their disgusting things and their detestable things they had filled my inheritance.’”

[NOTE]
====
. “Full amount.” Or, “double amount; duplicate.” Heb., mish·nehʹ.
====

[[v24-16-19]]

^<<v24-16-19,19>>^ O Jehovah my strength and my stronghold, and my place for flight in the day of distress, to you the nations themselves will come from the ends of the earth,^&#42;1^ and they will say: “Indeed our forefathers came to possess sheer falsehood, vanity and things in which there was nothing beneficial.”

[NOTE]
====
. “From the ends (terminations) of the earth.” Heb., me·ʼaph·seh-ʼaʹrets. Compare 25:31.
====

[[v24-16-20]]

^<<v24-16-20,20>>^ Can earthling man make for himself gods when they are no gods?

[[v24-16-21]]

^<<v24-16-21,21>>^ “Therefore here I am causing them to know; at this one time I shall cause them to know my hand and my mightiness, and they will have to know that my name is Jehovah.”

'''

xref:024-jeremiah/024-jeremiah-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremiah/024-jeremiah-017.adoc#v24-17-0[Próximo Capítulo &#62;]