include::./index.adoc[]

[[v24-32-0]]
=== Jeremiah, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-32-1]]

^<<v24-32-1,1>>^ The word that occurred to Jeremiah from Jehovah in the tenth year of Zed·e·kiʹah the king of Judah, that is, the eighteenth year of Neb·u·chad·rezʹzar.

[[v24-32-2]]

^<<v24-32-2,2>>^ And at that time the military forces of the king of Babylon were laying siege to Jerusalem; and as for Jeremiah the prophet, he happened to be under restraint in the Courtyard of the Guard that is in the house of the king of Judah;

[[v24-32-3]]

^<<v24-32-3,3>>^ because Zed·e·kiʹah the king of Judah had restrained him, saying:
“Why is it that you are prophesying, saying, ‘This is what Jehovah has said: “Here I am giving this city into the hand of the king of Babylon, and he will certainly capture it;

[[v24-32-4]]

^<<v24-32-4,4>>^ and Zed·e·kiʹah himself, the king of Judah, will not escape from the hand of the Chal·deʹans, for he will without fail be given into the hand of the king of Babylon, and his mouth will actually speak with the mouth of that one, and his own eyes will see even the eyes of that one”’;

[[v24-32-5]]

^<<v24-32-5,5>>^ ‘and to Babylon he will take Zed·e·kiʹah, and there he will continue until I turn my attention to him,’ is the utterance of Jehovah; ‘although YOU men keep warring against the Chal·deʹans, YOU will not succeed’?”

[[v24-32-6]]

^<<v24-32-6,6>>^ And Jeremiah proceeded to say: “The word of Jehovah has occurred to me, saying,

[[v24-32-7]]

^<<v24-32-7,7>>^ ‘Here is Hanʹa·mel the son of Shalʹlum your paternal uncle coming in to you, saying: “Buy for yourself the field of mine that is in Anʹa·thoth, because the right of repurchase belongs to you for buying &#91;it&#93;.”’”

[[v24-32-8]]

^<<v24-32-8,8>>^ In time Hanʹa·mel the son of my paternal uncle came in to me, according to the word of Jehovah, into the Courtyard of the Guard, and proceeded to say to me: “Buy,^&#42;1^ please, the field of mine that is in Anʹa·thoth, which is in the land of Benjamin, for the right of hereditary possession is yours, and the repurchasing power is yours. Buy &#91;it&#93; for yourself.” At that I knew that it had been the word of Jehovah.

[NOTE]
====
. Or, “Acquire.”
====

[[v24-32-9]]

^<<v24-32-9,9>>^ So I proceeded to buy from Hanʹa·mel the son of my paternal uncle the field that was in Anʹa·thoth. And I began to weigh out to him the money, seven shekels^&#42;1^ and ten silver pieces.

[NOTE]
====
. A shekel weighed 11.4 g (0.367 oz t).
====

[[v24-32-10]]

^<<v24-32-10,10>>^ Then I wrote in a deed and affixed the seal and took witnesses as I went weighing the money in the scales.

[[v24-32-11]]

^<<v24-32-11,11>>^ After that I took the deed of purchase, the one sealed according to the commandment and the regulations, and the one left open;

[[v24-32-12]]

^<<v24-32-12,12>>^ and I then gave the deed of purchase to Barʹuch the son of Ne·riʹah the son of Mah·seiʹah before the eyes of Hanʹa·mel &#91;the son of&#93; my paternal uncle and before the eyes of the witnesses, those writing in the deed of purchase, before the eyes of all the Jews who were sitting in the Courtyard of the Guard.

[[v24-32-13]]

^<<v24-32-13,13>>^ I now commanded Barʹuch before their eyes, saying:

[[v24-32-14]]

^<<v24-32-14,14>>^ “This is what Jehovah of armies, the God of Israel, has said, ‘Taking these deeds, this deed of purchase, even the sealed one, and the other deed left open, you must also put them into an earthenware vessel, in order that they may last for many days.’

[[v24-32-15]]

^<<v24-32-15,15>>^ For this is what Jehovah of armies, the God of Israel, has said, ‘Houses and fields and vineyards will yet be bought in this land.’”

[[v24-32-16]]

^<<v24-32-16,16>>^ And I began to pray to Jehovah after my having given the deed of purchase to Barʹuch the son of Ne·riʹah, saying:

[[v24-32-17]]

^<<v24-32-17,17>>^ “Alas, O Sovereign Lord Jehovah! Here you yourself have made the heavens and the earth by your great power and by your outstretched arm. The whole matter is not too wonderful for you yourself,

[[v24-32-18]]

^<<v24-32-18,18>>^ the One exercising loving-kindness toward thousands, and repaying the error of the fathers into the bosom of their sons after them, the &#91;true&#93; God,^&#42;1^ the great One, the mighty One,^&#42;2^ Jehovah of armies being his name,

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElʹ. See App 1G.
. “The mighty One.” Heb., hag·Gib·bohrʹ. Compare Isa 9:6 and Isa 10:21 ftns, “God.”
====

[[v24-32-19]]

^<<v24-32-19,19>>^ great in counsel and abundant in acts, you whose eyes are opened upon all the ways of the sons of men,^&#42;1^ in order to give to each one according to his ways and according to the fruitage of his dealings;

[NOTE]
====
. “The sons of men.” Heb., benehʹ ʼa·dhamʹ.
====

[[v24-32-20]]

^<<v24-32-20,20>>^ you who set signs and miracles in the land of Egypt down to this day and in Israel and among men,^&#42;1^ that you might make a name for your own self, just as at this day.

[NOTE]
====
. Or, “and among other men.” Heb., u·va·ʼa·dhamʹ.
====

[[v24-32-21]]

^<<v24-32-21,21>>^ And you proceeded to bring forth your people Israel out of the land of Egypt, with signs and with miracles and with a strong hand and with a stretched-out arm and with great fearsomeness.

[[v24-32-22]]

^<<v24-32-22,22>>^ “In time you gave them this land that you swore to their forefathers to give to them, a land flowing with milk and honey.

[[v24-32-23]]

^<<v24-32-23,23>>^ And they proceeded to come in and take possession of it, but they did not obey your voice, and in your law they did not walk. All the things that you commanded them to do they did not do, so that you caused all this calamity to befall them.

[[v24-32-24]]

^<<v24-32-24,24>>^ Look! With siege ramparts men have come to the city to capture it, and the very city will certainly be given into the hand of the Chal·deʹans who are fighting against it, because of the sword and the famine and the pestilence; and what you have said has happened, and here you are seeing &#91;it&#93;.

[[v24-32-25]]

^<<v24-32-25,25>>^ Yet you yourself have said to me, O Sovereign Lord Jehovah, ‘Buy for yourself the field with money and take witnesses,’ although the city itself must be given into the hand of the Chal·deʹans.”

[[v24-32-26]]

^<<v24-32-26,26>>^ At that the word of Jehovah occurred to Jeremiah, saying:

[[v24-32-27]]

^<<v24-32-27,27>>^ “Here I am, Jehovah, the God of all flesh. For me is there any matter at all too wonderful?

[[v24-32-28]]

^<<v24-32-28,28>>^ Therefore this is what Jehovah has said, ‘Here I am giving this city into the hand of the Chal·deʹans and into the hand of Neb·u·chad·rezʹzar the king of Babylon, and he must capture it.

[[v24-32-29]]

^<<v24-32-29,29>>^ And the Chal·deʹans who are fighting against this city must come in and set this city aflame with fire and must burn it down and the houses upon the roofs of which they have made sacrificial smoke to Baʹal and have poured out drink offerings to other gods^&#42;1^ for the purpose of offending me.’

[NOTE]
====
. “To . . . gods.” Heb., leʼ·lo·himʹ.
====

[[v24-32-30]]

^<<v24-32-30,30>>^ “‘For the sons of Israel and the sons of Judah have proved to be mere doers of what was bad in my eyes, from their youth on up; for the sons of Israel are even offending me by the work of their hands,’ is the utterance of Jehovah.

[[v24-32-31]]

^<<v24-32-31,31>>^ ‘For this city, from the day that they built it, clear down to this day, has proved to be nothing but a cause of anger in me and a cause of rage in me, in order to remove it from before my face,

[[v24-32-32]]

^<<v24-32-32,32>>^ on account of all the badness of the sons of Israel and of the sons of Judah that they have done to offend me, they, their kings, their princes, their priests and their prophets, and the men^&#42;1^ of Judah and the inhabitants of Jerusalem.

[NOTE]
====
. “And the men of.” Heb., weʼishʹ, sing. but in a collective sense.
====

[[v24-32-33]]

^<<v24-32-33,33>>^ And they kept turning to me the back and not the face; though there was a teaching of them, a rising up early and teaching, but there were none of them listening to receive discipline.

[[v24-32-34]]

^<<v24-32-34,34>>^ And they went putting their disgusting things in the house upon which my own name has been called, in order to defile it.

[[v24-32-35]]

^<<v24-32-35,35>>^ Furthermore, they built the high places of Baʹal that are in the valley of the son of Hinʹnom,^&#42;1^ in order to make their sons and their daughters pass through &#91;the fire&#93; to Moʹlech, a thing that I did not command them, neither did it come up into my heart to do this detestable thing, for the purpose of making Judah sin.’

[NOTE]
====
. See App 4C.
====

[[v24-32-36]]

^<<v24-32-36,36>>^ “And now, therefore, this is what Jehovah the God of Israel has said concerning this city which YOU persons are saying will certainly be given into the hand of the king of Babylon by the sword and by the famine and by the pestilence,

[[v24-32-37]]

^<<v24-32-37,37>>^ ‘Here I am collecting them together out of all the lands to which I shall have dispersed them in my anger and in my rage and in great indignation; and I will bring them back to this place and make them dwell in security.

[[v24-32-38]]

^<<v24-32-38,38>>^ And they will certainly become my people, and I myself shall become their God.

[[v24-32-39]]

^<<v24-32-39,39>>^ And I will give them one heart and one way in order to fear me always,^&#42;1^ for good to them and to their sons after them.

[NOTE]
====
. Lit., “all the days.”
====

[[v24-32-40]]

^<<v24-32-40,40>>^ And I will conclude with them an indefinitely lasting covenant, that I shall not turn back from behind them, for me to do them good; and the fear of me I shall put in their heart in order not to turn aside from me.

[[v24-32-41]]

^<<v24-32-41,41>>^ And I will exult over them to do them good, and I will plant them in this land in trueness^&#42;1^ with all my heart and with all my soul.’”

[NOTE]
====
. “In trueness (truth).” Heb., be·ʼemethʹ.
====

[[v24-32-42]]

^<<v24-32-42,42>>^ “For this is what Jehovah has said, ‘Just as I have brought in upon this people all this great calamity, so I am bringing in upon them all the goodness that I am speaking concerning them.

[[v24-32-43]]

^<<v24-32-43,43>>^ And fields^&#42;1^ will certainly be bought in this land of which YOU people will be saying: “It is a desolate waste without man^&#42;2^ and domestic animal. It has been given into the hand of the Chal·deʹans.”’

[NOTE]
====
. Lit., “the field,” sing. but in a collective sense.
. “Man.” Heb., ʼa·dhamʹ.
====

[[v24-32-44]]

^<<v24-32-44,44>>^ “‘With money people will buy fields themselves, and there will be a recording in the deed and a sealing and a taking of witnesses in the land of Benjamin and in the surroundings of Jerusalem and in the cities of Judah and in the cities of the mountainous region and in the cities of the lowland^&#42;1^ and in the cities of the south,^&#42;2^ because I shall bring back their captives,’ is the utterance of Jehovah.”

[NOTE]
====
. Or, “the Shephelah.”
. Or, “the Negeb.”
====

'''

xref:024-jeremiah/024-jeremiah-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremiah/024-jeremiah-033.adoc#v24-33-0[Próximo Capítulo &#62;]