include::./index.adoc[]

[[v24-6-0]]
=== Jeremiah, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-6-1]]

^<<v24-6-1,1>>^ Take shelter, O YOU sons of Benjamin, from the midst of Jerusalem; and in Te·koʹa blow the horn.^&#42;1^ And over Beth-hac·cheʹrem raise a fire signal; because calamity itself has looked down out of the north, even a great crash.

[NOTE]
====
. Or, “shofar.”
====

[[v24-6-2]]

^<<v24-6-2,2>>^ The daughter of Zion has resembled indeed a comely and daintily bred woman.

[[v24-6-3]]

^<<v24-6-3,3>>^ To her the shepherds and their droves proceeded to come. Against her they pitched &#91;their&#93; tents all around. They grazed off each one his own part.

[[v24-6-4]]

^<<v24-6-4,4>>^ Against her they have sanctified war: “Rise up, and let us go up at midday!”
“Woe to us, for the day has declined, for the shadows of evening keep extending themselves!”

[[v24-6-5]]

^<<v24-6-5,5>>^ “Rise up, and let us go up during the night and bring to ruin her dwelling towers.”

[[v24-6-6]]

^<<v24-6-6,6>>^ For this is what Jehovah of armies has said: “Cut down wood^&#42;1^ and throw up against Jerusalem a siege rampart. She is the city with which an accounting must be held. She is nothing but oppression in the midst of her.

[NOTE]
====
. “Wood,” MT; LXXSyVg, “her trees.”
====

[[v24-6-7]]

^<<v24-6-7,7>>^ As a cistern keeps its waters cool, so she has kept her badness cool. Violence and despoiling are heard in her; sickness and plague are before my face constantly.

[[v24-6-8]]

^<<v24-6-8,8>>^ Be corrected, O Jerusalem, that my soul may not turn away disgusted from you; that I may not set you as a desolate waste, a land not inhabited.”

[[v24-6-9]]

^<<v24-6-9,9>>^ This is what Jehovah of armies has said: “They will without fail glean the remnant of Israel just like a vine. Put your hand back like one that is gathering grapes upon the vine tendrils.”

[[v24-6-10]]

^<<v24-6-10,10>>^ “To whom shall I speak and give warning, that they may hear? Look! Their ear is uncircumcised, so that they are unable to pay attention. Look! The very word of Jehovah has become to them a reproach, in which^&#42;1^ &#91;word&#93; they can take no delight.

[NOTE]
====
. “Which,” referring to the “very word,” both masc. sing.
====

[[v24-6-11]]

^<<v24-6-11,11>>^ And with the rage of Jehovah I have become full. I have become weary with holding in.”
“Pour &#91;it&#93; out upon the child in the street and upon the intimate group of young men at the same time; for they will also be caught, a man^&#42;1^ along with his wife,^&#42;2^ an old man along with one that is full of days.

[NOTE]
====
. Or, “husband.” Heb., ʼish.
. Or, “woman.” Heb., ʼish·shahʹ.
====

[[v24-6-12]]

^<<v24-6-12,12>>^ And their houses will certainly be turned over to others for possession, the fields and the wives at the same time. For I shall stretch my hand out against the inhabitants of the land,” is the utterance of Jehovah.

[[v24-6-13]]

^<<v24-6-13,13>>^ “For from the least one of them even to the greatest one of them, every one is making for himself unjust gain; and from the prophet even to the priest, each one is acting falsely.

[[v24-6-14]]

^<<v24-6-14,14>>^ And they try to heal the breakdown^&#42;1^ of my people lightly,^&#42;2^ saying, ‘There is peace! There is peace!’^&#42;3^ when there is no peace.

[NOTE]
====
. Or, “fracture.”
. Or, “superficially.”
. Or, “saying, ‘Perfect peace!’ ” Lit., “saying, ‘Peace! Peace!’ ” See Isa 26:3 ftn, “Peace.”
====

[[v24-6-15]]

^<<v24-6-15,15>>^ Did they feel shame because it was something detestable that they had done? For one thing, they positively do not feel any shame; for another thing, they have not come to know even how to feel humiliated. Therefore they will fall among those who are falling; in the time that I must hold an accounting with them they will stumble,” Jehovah has said.

[[v24-6-16]]

^<<v24-6-16,16>>^ This is what Jehovah has said: “Stand still in the ways, YOU people, and see, and ask for the roadways of long ago, where, now, the good way is; and walk in it, and find ease for YOUR souls.” But they kept saying: “We are not going to walk.”

[[v24-6-17]]

^<<v24-6-17,17>>^ “And I raised up over YOU people^&#42;1^ watchmen, ‘Pay attention to the sound of the horn!’” But they kept saying: “We are not going to pay attention.”

[NOTE]
====
. “You people,” MTLXXSyVg; two Heb. mss, “them.”
====

[[v24-6-18]]

^<<v24-6-18,18>>^ “Therefore hear, O YOU nations! And know, O you assembly, what will be among them.

[[v24-6-19]]

^<<v24-6-19,19>>^ Listen, O earth! Here I am bringing in calamity upon this people as the fruitage of their thoughts, for they paid no attention to my very own words; and my law—they also kept rejecting it.”

[[v24-6-20]]

^<<v24-6-20,20>>^ “What does this matter to me that you bring in even frankincense from Sheʹba and the good cane^&#42;1^ from the land far away? The whole burnt offerings of YOU people serve for no pleasure, and YOUR very sacrifices have not been gratifying to me.”

[NOTE]
====
. Or, “the sweet cane.”
====

[[v24-6-21]]

^<<v24-6-21,21>>^ Therefore this is what Jehovah has said: “Here I am setting for this people stumbling blocks, and they will certainly stumble over them, fathers and sons together; the neighbor and his companion—they will perish.”

[[v24-6-22]]

^<<v24-6-22,22>>^ This is what Jehovah has said: “Look! A people is coming from the land of the north, and there is a great nation that will be awakened from the remotest parts of the earth.

[[v24-6-23]]

^<<v24-6-23,23>>^ The bow and the javelin they will grab hold of. It^&#42;1^ is a cruel one, and they will have no pity. Their very voice will resound just like the sea, and upon horses they will ride. It is drawn up in battle order like a man of war against you, O daughter of Zion.”

[NOTE]
====
. “It,” that is, the “people,” or “nation.”
====

[[v24-6-24]]

^<<v24-6-24,24>>^ We have heard the report about it.^&#42;1^ Our hands have dropped. Distress itself has seized hold of us, labor pains like those of a woman giving birth.

[NOTE]
====
. See vs 23 ftn.
====

[[v24-6-25]]

^<<v24-6-25,25>>^ Do not go out^&#42;1^ into the field, and do not walk even in the way; for there is the sword belonging to the enemy, there is fright all around.

[NOTE]
====
. “Do not go out,” fem., addressed to the “daughter” of Zion in vs 23.
====

[[v24-6-26]]

^<<v24-6-26,26>>^ O daughter of my people, gird on sackcloth and wallow in the ashes. Make your mourning that for an only &#91;son&#93;, the wailing of bitterness; because suddenly the despoiler will come upon us.

[[v24-6-27]]

^<<v24-6-27,27>>^ “I have made you^&#42;1^ a metal tester among my people, one making a thorough search;^&#42;2^ and you will take note and you must examine^&#42;3^ their way.

[NOTE]
====
. “You,” masc. sing.
. “One making a thorough search” (like a grape gatherer), by a change of vowel pointing; M, “as a fortified place.”
. Or, “assay.”
====

[[v24-6-28]]

^<<v24-6-28,28>>^ All of them are the most stubborn men,^&#42;1^ walking about as slanderers—copper and iron. They are all of them ruinous.

[NOTE]
====
. Lit., “the sullen ones of the stubborn ones.”
====

[[v24-6-29]]

^<<v24-6-29,29>>^ The bellows have been scorched.^&#42;1^ Out from their fire there is lead. One has kept refining intensely simply for nothing, and those who are bad have not been separated.

[NOTE]
====
. “Have been scorched,” by one derivation of the Heb. verb; by another derivation, “have snorted.”
====

[[v24-6-30]]

^<<v24-6-30,30>>^ Rejected silver is what people will certainly call them, for Jehovah has rejected them.”

'''

xref:024-jeremiah/024-jeremiah-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremiah/024-jeremiah-007.adoc#v24-7-0[Próximo Capítulo &#62;]