include::./index.adoc[]

[[v24-34-0]]
=== Jeremiah, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-34-1]]

^<<v24-34-1,1>>^ The word that occurred to Jeremiah from Jehovah, when Neb·u·chad·rezʹzar the king of Babylon and all his military force and all the kingdoms of the earth, the dominion under his hand, and all the peoples were fighting against Jerusalem and against all her cities, saying:

[[v24-34-2]]

^<<v24-34-2,2>>^ “This is what Jehovah the God of Israel has said, ‘Go,^&#42;1^ and you must say to Zed·e·kiʹah the king of Judah, yes, you must say to him: “This is what Jehovah has said, ‘Here I am giving this city into the hand of the king of Babylon, and he must burn it with fire.

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-34-3]]

^<<v24-34-3,3>>^ And you yourself will not escape out of his hand, because you will without fail be caught and into his hand you will be given. And your own eyes will see even the eyes of the king of Babylon, and his own mouth will speak even with your mouth, and to Babylon you will come.’

[[v24-34-4]]

^<<v24-34-4,4>>^ However, hear the word of Jehovah, O Zed·e·kiʹah king of Judah, ‘This is what Jehovah has said concerning you: “You will not die by the sword.

[[v24-34-5]]

^<<v24-34-5,5>>^ In peace you will die; and as with the burnings for your fathers, the former kings who happened to be prior to you, so they will make a burning for you, and ‘Alas, O master!’ is what they will say in lament for you, for ‘I myself have spoken the very word,’ is the utterance of Jehovah.”’”’”

[[v24-34-6]]

^<<v24-34-6,6>>^ And Jeremiah the prophet proceeded to speak to Zed·e·kiʹah the king of Judah all these words in Jerusalem,

[[v24-34-7]]

^<<v24-34-7,7>>^ when the military forces of the king of Babylon were fighting against Jerusalem and against all the cities of Judah that were left remaining, against Laʹchish and against A·zeʹkah; for they, the fortified cities, were the ones that remained over among the cities of Judah.

[[v24-34-8]]

^<<v24-34-8,8>>^ The word that occurred to Jeremiah from Jehovah after King Zed·e·kiʹah concluded a covenant with all the people who were in Jerusalem to proclaim to them liberty,^&#42;1^

[NOTE]
====
. Or, “release.” Heb., derohrʹ.
====

[[v24-34-9]]

^<<v24-34-9,9>>^ to let each one his manservant and each one his maidservant, Hebrew man and Hebrew woman, go free, in order not to use them as servants, that is, a Jew, who is his brother.

[[v24-34-10]]

^<<v24-34-10,10>>^ So all the princes obeyed, and all the people who had entered into the covenant to let each one his manservant and each one his maidservant go free, in order to use them no more as servants, and they proceeded to obey and to let &#91;them&#93; go.

[[v24-34-11]]

^<<v24-34-11,11>>^ But they turned about after that and began to bring back the menservants and the maidservants whom they had let go free, and they went subjecting them as menservants and as maidservants.

[[v24-34-12]]

^<<v24-34-12,12>>^ Consequently the word of Jehovah occurred to Jeremiah from Jehovah, saying:

[[v24-34-13]]

^<<v24-34-13,13>>^ “This is what Jehovah the God of Israel has said, ‘I myself concluded a covenant with YOUR forefathers in the day of my bringing them out of the land of Egypt, out of the house of servants,^&#42;1^ saying:

[NOTE]
====
. Or, “slaves.”
====

[[v24-34-14]]

^<<v24-34-14,14>>^ “At the end of seven^&#42;1^ years YOU men should let go each one his brother, a Hebrew man, who came to be sold to you and who has served you six years; and you must let him go free from being with you.” But YOUR forefathers did not listen to me, neither did they incline their ear.

[NOTE]
====
. “Seven,” MTSyVg; LXX, “six.”
====

[[v24-34-15]]

^<<v24-34-15,15>>^ And YOU yourselves turn around today and do what is upright in my eyes in proclaiming liberty each one to his companion, and YOU conclude a covenant before me in the house upon which my name has been called.

[[v24-34-16]]

^<<v24-34-16,16>>^ Then YOU turn back and profane my name and bring back each one his manservant and each one his maidservant, whom YOU let go free agreeably to their soul,^&#42;1^ and YOU subject them to become YOUR menservants and maidservants.’

[NOTE]
====
. Or, “where they wish.” Lit., “free to their soul.” Compare De 21:14 ftn.
====

[[v24-34-17]]

^<<v24-34-17,17>>^ “Therefore this is what Jehovah has said, ‘YOU yourselves have not obeyed me in keeping on proclaiming liberty each one to his brother and each one to his companion. Here I am proclaiming to YOU a liberty,’ is the utterance of Jehovah, ‘to the sword, to the pestilence and to the famine, and I shall certainly give YOU for a quaking to all the kingdoms of the earth.

[[v24-34-18]]

^<<v24-34-18,18>>^ And I will give the men^&#42;1^ sidestepping my covenant, in that they did not carry out the words of the covenant that they concluded^&#42;2^ before me &#91;with&#93; the calf that they cut in two that they might pass between its pieces;

[NOTE]
====
. “The men.” Heb., ha·ʼana·shimʹ, pl. of ʼish.
. Lit., “they cut.” Heb., kor·thuʹ; the same as for cutting the calf.
====

[[v24-34-19]]

^<<v24-34-19,19>>^ &#91;namely,&#93; the princes of Judah and the princes of Jerusalem, the court officials and the priests and all the people of the land^&#42;1^ who went passing between the pieces of the calf—

[NOTE]
====
. “The people of the land.” Heb., ʽam ha·ʼaʹrets.
====

[[v24-34-20]]

^<<v24-34-20,20>>^ yes, I will give them into the hand of their enemies and into the hand of those seeking for their soul; and their dead bodies must become food for the flying creatures of the heavens and for the beasts of the earth.

[[v24-34-21]]

^<<v24-34-21,21>>^ And Zed·e·kiʹah the king of Judah and his princes I shall give into the hand of their enemies and into the hand of those seeking for their soul and into the hand of the military forces of the king of Babylon who are withdrawing from against YOU men.’

[[v24-34-22]]

^<<v24-34-22,22>>^ “‘Here I am commanding,’ is the utterance of Jehovah, ‘and I shall certainly bring them back to this city, and they must fight against it and capture it and burn it with fire; and the cities of Judah I shall make a desolate waste without an inhabitant.’”

'''

xref:024-jeremiah/024-jeremiah-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremiah/024-jeremiah-035.adoc#v24-35-0[Próximo Capítulo &#62;]