include::./index.adoc[]

[[v24-5-0]]
=== Jeremiah, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-5-1]]

^<<v24-5-1,1>>^ Go roving about in the streets of Jerusalem and see, now, and know, and seek for yourselves in her public squares whether YOU can find a man, whether there exists anyone doing justice, anyone seeking faithfulness, and I shall forgive her.

[[v24-5-2]]

^<<v24-5-2,2>>^ Even if they should say: “As Jehovah is alive!” they would thereby be swearing to sheer falsehood.

[[v24-5-3]]

^<<v24-5-3,3>>^ O Jehovah, are not those eyes of yours toward faithfulness? You have struck them, but they did not become ill. You exterminated them. They refused to take discipline. They made their faces harder than a crag. They refused to turn back.

[[v24-5-4]]

^<<v24-5-4,4>>^ Even I myself had said: “Surely they are of low class. They acted foolishly, for they have ignored the way of Jehovah, the judgment of their God.^&#42;1^

[NOTE]
====
. “Their God.” Heb., ʼElo·heh·hemʹ, pl.
====

[[v24-5-5]]

^<<v24-5-5,5>>^ I will go my way to the great ones and speak with them; for they themselves must have taken note of the way of Jehovah, the judgment of their God. Surely they themselves must have all together broken the yoke; they must have torn apart the bands.”

[[v24-5-6]]

^<<v24-5-6,6>>^ That is why a lion out of the forest has struck them, a wolf itself of the desert plains keeps despoiling them, a leopard is keeping awake at their cities. Everyone going forth from them gets torn to pieces. For their transgressions have become many; their acts of unfaithfulness have become numerous.

[[v24-5-7]]

^<<v24-5-7,7>>^ How can I forgive you^&#42;1^ for this very thing? Your own sons have left me, and they keep swearing by what is no God.^&#42;2^ And I kept satisfying them, but they continued committing adultery, and to the house of a prostitute woman they go in troops.

[NOTE]
====
. “You,” fem. sing.
. Or, “by what are no gods.” Heb., beloʼʹ ʼelo·himʹ.
====

[[v24-5-8]]

^<<v24-5-8,8>>^ Horses seized with sexual heat, having &#91;strong&#93; testicles, they have become. They neigh each one to the wife of his companion.

[[v24-5-9]]

^<<v24-5-9,9>>^ “Should I not take an accounting because of these very things?” is the utterance of Jehovah. “Or upon a nation that is like this should not my soul avenge itself?”

[[v24-5-10]]

^<<v24-5-10,10>>^ “Come up against her &#91;vine&#93; rows^&#42;1^ and cause ruin, but do not YOU men make an actual extermination. Take away her luxuriating shoots, for they do not belong to Jehovah.

[NOTE]
====
. “Her terrace walls,” by a slight change of vowel pointing.
====

[[v24-5-11]]

^<<v24-5-11,11>>^ For the house of Israel and the house of Judah have positively dealt treacherously with me,” is the utterance of Jehovah.

[[v24-5-12]]

^<<v24-5-12,12>>^ “They have denied Jehovah, and they keep saying, ‘He is not. And upon us no calamity will come, and no sword or famine shall we see.’

[[v24-5-13]]

^<<v24-5-13,13>>^ And the prophets themselves become a wind, and the word is not in them. That is how it will be done to them.”

[[v24-5-14]]

^<<v24-5-14,14>>^ Therefore this is what Jehovah, the God of armies, has said: “For the reason that YOU men are saying this thing, here I am making my words in your mouth a fire, and this people will be pieces of wood, and it will certainly devour them.”

[[v24-5-15]]

^<<v24-5-15,15>>^ “Here I am bringing in upon YOU men a nation from far away, O house of Israel,” is the utterance of Jehovah. “It is an enduring nation. It is a nation of long ago, a nation whose language^&#42;1^ you do not know, and you cannot hear &#91;understandingly&#93; what they speak.

[NOTE]
====
. Lit., “tongue.”
====

[[v24-5-16]]

^<<v24-5-16,16>>^ Their quiver is like an open burial place; all of them are mighty men.

[[v24-5-17]]

^<<v24-5-17,17>>^ They will also certainly eat up your harvest and your bread. The men will eat up your sons and your daughters. They will eat up your flocks and your herds. They will eat up your vine and your fig tree. They will shatter with the sword your fortified cities in which you are trusting.”

[[v24-5-18]]

^<<v24-5-18,18>>^ “And even in those days,” is the utterance of Jehovah, “I shall not carry out an extermination of YOU men.

[[v24-5-19]]

^<<v24-5-19,19>>^ And it must occur that YOU will say, ‘Due to what fact has Jehovah our God done to us all these things?’ And you must say to them, ‘Just as YOU have left me and have gone serving a foreign god^&#42;1^ in YOUR land, so YOU will serve strangers in a land that is not YOURS.’”

[NOTE]
====
. Or, “foreign gods.” Lit., “a god [or, gods] of a foreign (country).” Heb., ʼelo·hehʹ ne·kharʹ. The pl. form of “god” may denote excellence.
====

[[v24-5-20]]

^<<v24-5-20,20>>^ TELL this in the house of Jacob, and publish it in Judah, saying:

[[v24-5-21]]

^<<v24-5-21,21>>^ “Hear, now, this, O unwise people that is without heart:^&#42;1^ They have eyes, but they cannot see; they have ears, but they cannot hear.

[NOTE]
====
. Or, “good motive.” Heb., lev.
====

[[v24-5-22]]

^<<v24-5-22,22>>^ ‘Do YOU not fear even me,’ is the utterance of Jehovah, ‘or are YOU in no severe pains even because of me, who have set the sand as the boundary for the sea, an indefinitely lasting regulation that it cannot pass over? Although its waves toss themselves, still they cannot prevail; and &#91;although&#93; they do become boisterous, still they cannot pass over it.

[[v24-5-23]]

^<<v24-5-23,23>>^ But this very people has come to have a stubborn and rebellious heart; they have turned aside and keep walking in their course.

[[v24-5-24]]

^<<v24-5-24,24>>^ But they have not said in their heart: “Let us, now, fear Jehovah our God, the One who is giving the downpour and the autumn rain and the spring rain in its season, the One who guards even the prescribed weeks of the harvest for us.”

[[v24-5-25]]

^<<v24-5-25,25>>^ YOUR own errors have turned these things away, and YOUR own sins have held back what is good from YOU people.

[[v24-5-26]]

^<<v24-5-26,26>>^ “‘For among my people there have been found wicked men. They keep peering, as when birdcatchers crouch down. They have set a ruinous &#91;trap&#93;.^&#42;1^ It is men^&#42;2^ that they catch.

[NOTE]
====
. “A ruinous [trap].” Or, “ruination,” that is, in the form of a trap or snare.
. “Men.” Heb., ʼana·shimʹ.
====

[[v24-5-27]]

^<<v24-5-27,27>>^ As a cage is full of flying creatures, so their houses are full of deception. That is why they have become great and they gain riches.

[[v24-5-28]]

^<<v24-5-28,28>>^ They have grown fat; they have become shiny. They have also overflowed with bad things.^&#42;1^ No legal case have they pleaded, even the legal case of the fatherless boy, that they may gain success; and the judgment of the poor ones they have not taken up.’”

[NOTE]
====
. Or, “words; matters.”
====

[[v24-5-29]]

^<<v24-5-29,29>>^ “Should I not hold an accounting because of these very things,” is the utterance of Jehovah, “or on a nation that is like this should not my soul avenge itself?

[[v24-5-30]]

^<<v24-5-30,30>>^ An astonishing situation, even a horrible thing, has been brought to be^&#42;1^ in the land:

[NOTE]
====
. Compare De 27:9 ftn.
====

[[v24-5-31]]

^<<v24-5-31,31>>^ The prophets themselves actually prophesy in falsehood; and as for the priests, they go subduing according to their powers.^&#42;1^ And my own people have loved &#91;it&#93; that way; and what will YOU men do in the finale of it?”

[NOTE]
====
. Lit., “hands.”
====

'''

xref:024-jeremiah/024-jeremiah-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremiah/024-jeremiah-006.adoc#v24-6-0[Próximo Capítulo &#62;]