include::./index.adoc[]

[[v24-17-0]]
=== Jeremiah, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-17-1]]

^<<v24-17-1,1>>^ “The sin of Judah is written down with an iron stylus. With a diamond point it is engraved on the tablet of their heart, and on the horns of their^&#42;1^ altars,

[NOTE]
====
. “Their,” ThSyVg and about 170 Heb. mss; M, “your,” pl.
====

[[v24-17-2]]

^<<v24-17-2,2>>^ when their sons remember their altars and their sacred poles^&#42;1^ beside a luxuriant tree, upon the high hills,

[NOTE]
====
. Or, “their Asherim.”
====

[[v24-17-3]]

^<<v24-17-3,3>>^ &#91;on&#93; the mountains in the field. Your^&#42;1^ resources, all your treasures, I shall give for mere plunder—your high places because of sin throughout all your territories.

[NOTE]
====
. “Your,” masc. sing.
====

[[v24-17-4]]

^<<v24-17-4,4>>^ And you let loose, even of your own accord, from your hereditary possession that I had given you. I also will make you serve your enemies in the land that you have not known; for as a fire YOU people have been ignited in my anger. To time indefinite it will keep kindled.”

[[v24-17-5]]

^<<v24-17-5,5>>^ This is what Jehovah has said: “Cursed is the able-bodied man^&#42;1^ who puts his trust in earthling man^&#42;2^ and actually makes flesh his arm, and whose heart turns away from Jehovah himself.

[NOTE]
====
. “The able-bodied man.” Heb., hag·geʹver.
. “In earthling man.” Heb., ba·ʼa·dhamʹ.
====

[[v24-17-6]]

^<<v24-17-6,6>>^ And he will certainly become like a solitary tree in the desert plain and will not see when good comes; but he must reside in parched places^&#42;1^ in the wilderness, in a salt country that is not inhabited.

[NOTE]
====
. Or, “lava-covered stretches.”
====

[[v24-17-7]]

^<<v24-17-7,7>>^ Blessed is the able-bodied man who puts his trust in Jehovah, and whose confidence^&#42;1^ Jehovah has become.

[NOTE]
====
. Or, “trust.”
====

[[v24-17-8]]

^<<v24-17-8,8>>^ And he will certainly become like a tree planted by the waters, that sends out its roots right by the watercourse; and he will not see when heat comes, but his foliage will actually prove to be luxuriant. And in the year of drought he will not become anxious, nor will he leave off from producing fruit.

[[v24-17-9]]

^<<v24-17-9,9>>^ “The heart is more treacherous than anything else and is desperate. Who can know it?

[[v24-17-10]]

^<<v24-17-10,10>>^ I, Jehovah, am searching the heart, examining the kidneys,^&#42;1^ even to give to each one according to his ways,^&#42;2^ according to the fruitage of his dealings.

[NOTE]
====
. See 11:20 ftn.
. “Ways,” TLXXSy and about 130 Heb. mss.
====

[[v24-17-11]]

^<<v24-17-11,11>>^ &#91;As&#93; the partridge that has gathered together^&#42;1^ what it has not laid is the one making riches, but not with justice. At the half of his days he will leave them, and in his finale he will prove to be senseless.”

[NOTE]
====
. Or, “that has hatched.”
====

[[v24-17-12]]

^<<v24-17-12,12>>^ There is the glorious throne on high from the start; it is the place of our sanctuary.

[[v24-17-13]]

^<<v24-17-13,13>>^ O Jehovah, the hope of Israel, all those who are leaving you will be put to shame. Those apostatizing from me will be written down even in the earth, because they have left the source of living water, Jehovah.

[[v24-17-14]]

^<<v24-17-14,14>>^ Heal me, O Jehovah, and I shall be healed. Save me, and I will be saved; for you are my praise.

[[v24-17-15]]

^<<v24-17-15,15>>^ Look! There are those saying to me: “Where is the word of Jehovah? Let it come in, please.”

[[v24-17-16]]

^<<v24-17-16,16>>^ But as for me, I did not hasten from being a shepherd following you, and for the desperate day I did not show any craving. You yourself have known the expression of my lips; in front of your face it has occurred.

[[v24-17-17]]

^<<v24-17-17,17>>^ Do not become something terrifying to me. You are my refuge in the day of calamity.

[[v24-17-18]]

^<<v24-17-18,18>>^ Let my persecutors be put to shame, but let me personally be put to no shame. Let them be the ones to be struck with terror, but let me personally not be struck with terror. Bring upon them the day of calamity, and break them even with twice as much breakdown.

[[v24-17-19]]

^<<v24-17-19,19>>^ This is what Jehovah has said to me: “Go,^&#42;1^ and you must stand in the gate of the sons of the people by which the kings of Judah enter in and by which they go out, and in all the gates of Jerusalem.

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-17-20]]

^<<v24-17-20,20>>^ And you must say to them, ‘Hear the word of Jehovah, YOU kings of Judah and all Judah and all YOU inhabitants of Jerusalem, who are entering in by these gates.

[[v24-17-21]]

^<<v24-17-21,21>>^ This is what Jehovah has said: “Watch out for YOUR souls,^&#42;1^ and do not carry on the sabbath day any load that YOU must bring in through the gates of Jerusalem.

[NOTE]
====
. “For your souls.” Heb., benaph·shoh·theh·khemʹ, pl. of neʹphesh; Gr., psy·khasʹ; Lat., aʹni·mas. See App 4A.
====

[[v24-17-22]]

^<<v24-17-22,22>>^ And YOU must bring no load out of YOUR homes on the sabbath day; and no work at all must YOU do. And YOU must sanctify the sabbath day, just as I commanded YOUR forefathers;

[[v24-17-23]]

^<<v24-17-23,23>>^ but they did not listen or incline their ear, and they proceeded to harden their neck in order not to hear and in order to receive no discipline.”’

[[v24-17-24]]

^<<v24-17-24,24>>^ “‘“And it must occur that, if YOU strictly obey me,” is the utterance of Jehovah, “to bring in no load through the gates of this city on the sabbath day and to sanctify the sabbath day by not doing on it any work,

[[v24-17-25]]

^<<v24-17-25,25>>^ there will also certainly enter in by the gates of this city kings with princes, sitting on the throne of David, riding in the chariot and upon horses, they and their princes, the men^&#42;1^ of Judah and the inhabitants of Jerusalem; and this city will certainly be inhabited to time indefinite.

[NOTE]
====
. “Men of.” Heb., ʼish, sing. but in a collective sense.
====

[[v24-17-26]]

^<<v24-17-26,26>>^ And people will actually come from the cities of Judah and from round about Jerusalem and from the land of Benjamin and from the lowland^&#42;1^ and from the mountainous region and from the Negʹeb,^&#42;2^ bringing whole burnt offering and sacrifice and grain offering and frankincense and bringing thanksgiving sacrifice into the house of Jehovah.

[NOTE]
====
. Or, “the Shephelah.” Heb., hash·shephe·lahʹ.
. Or, “the south.”
====

[[v24-17-27]]

^<<v24-17-27,27>>^ “‘“But if YOU will not obey me by sanctifying the sabbath day and not carrying a load, but there is a coming in &#91;with it&#93; through the gates of Jerusalem on the sabbath day, I will also set a fire ablaze in her gates, and it will certainly devour the dwelling towers of Jerusalem and will not be extinguished.”’”

'''

xref:024-jeremiah/024-jeremiah-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremiah/024-jeremiah-018.adoc#v24-18-0[Próximo Capítulo &#62;]