include::./index.adoc[]

[[v24-30-0]]
=== Jeremiah, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-30-1]]

^<<v24-30-1,1>>^ The word that occurred to Jeremiah from Jehovah, saying:

[[v24-30-2]]

^<<v24-30-2,2>>^ “This is what Jehovah the God of Israel has said, ‘Write for yourself in a book all the words that I will speak to you.

[[v24-30-3]]

^<<v24-30-3,3>>^ For, “look! there are days coming,” is the utterance of Jehovah, “and I will gather the captive ones of my people, Israel and Judah,” Jehovah has said, “and I will bring them back to the land that I gave to their forefathers, and they will certainly repossess it.”’”

[[v24-30-4]]

^<<v24-30-4,4>>^ And these are the words that Jehovah has spoken to Israel and to Judah.

[[v24-30-5]]

^<<v24-30-5,5>>^ For this is what Jehovah has said: “The sound of trembling we have heard, dread, and there is no peace.

[[v24-30-6]]

^<<v24-30-6,6>>^ Ask, please, O men, and see whether a male is giving birth. Why is it that I have seen every able-bodied man with his hands upon his loins like a female that is giving birth, and all faces have turned pale?

[[v24-30-7]]

^<<v24-30-7,7>>^ Alas! For that day is a great one, so that there is no other like it, and it is the time of distress for Jacob. But he will be saved even out of it.”

[[v24-30-8]]

^<<v24-30-8,8>>^ “And it must occur in that day,” is the utterance of Jehovah of armies, “that I shall break one’s yoke from off your neck, and your bands I shall tear in two, and no more will strangers exploit him as a servant.

[[v24-30-9]]

^<<v24-30-9,9>>^ And they will certainly serve Jehovah their God and David their king, whom I shall raise up for them.”

[[v24-30-10]]

^<<v24-30-10,10>>^ “And as for you, do not be afraid, O my servant Jacob,” is the utterance of Jehovah, “and do not be struck with terror, O Israel. For here I am saving you from far off and your offspring from the land of their captivity. And Jacob will certainly return and be free of disturbance and be at ease, and there will be no one causing trembling.”

[[v24-30-11]]

^<<v24-30-11,11>>^ “For I am with you,” is the utterance of Jehovah, “to save you; but I shall make an extermination among all the nations to which I have scattered you. However, in your case I shall make no extermination. And I shall have to correct you to the proper degree, as I shall by no means leave you unpunished.”

[[v24-30-12]]

^<<v24-30-12,12>>^ For this is what Jehovah has said: “There is no cure for your^&#42;1^ breakdown. Your stroke is chronic.

[NOTE]
====
. “Your,” fem. sing., referring to the city of Zion.
====

[[v24-30-13]]

^<<v24-30-13,13>>^ There is no one pleading your cause, for &#91;your&#93; ulcer. There are no means of healing, no mending, for you.

[[v24-30-14]]

^<<v24-30-14,14>>^ All those intensely loving you are the ones that have forgotten you. You are not the one for whom they keep searching. For with the stroke of an enemy I have struck you, with the chastisement of someone cruel, on account of the abundance of your error; your sins have become numerous.

[[v24-30-15]]

^<<v24-30-15,15>>^ Why do you cry out on account of your breakdown? Your pain is incurable on account of the abundance of your error; your sins have become numerous. I have done these things to you.

[[v24-30-16]]

^<<v24-30-16,16>>^ Therefore all those devouring you will themselves be devoured; and as for all your adversaries, into captivity they will all of them go. And those pillaging you^&#42;1^ will certainly come to be for pillaging, and all those plundering you I shall give over to plundering.”

[NOTE]
====
. See vs 12 ftn.
====

[[v24-30-17]]

^<<v24-30-17,17>>^ “For I shall bring up a recuperation for you, and from your strokes I shall heal you,” is the utterance of Jehovah. “For a woman chased away is what they called you: ‘That is Zion, for whom no one is searching.’”

[[v24-30-18]]

^<<v24-30-18,18>>^ This is what Jehovah has said: “Here I am gathering the captive ones of the tents of Jacob, and for his tabernacles I shall have pity. And the city will actually be rebuilt upon her mound; and upon its rightful site the dwelling tower itself will sit.

[[v24-30-19]]

^<<v24-30-19,19>>^ And from them there will certainly go forth thanksgiving, and the sound of those who are laughing. And I will multiply them, and they will not become few; and I will make them heavy in number, and they will not become insignificant.

[[v24-30-20]]

^<<v24-30-20,20>>^ And his sons must become as in former times, and before me his own assembly will be firmly established. And I will turn my attention upon all his oppressors.

[[v24-30-21]]

^<<v24-30-21,21>>^ And his majestic one will certainly come to be from him, and from the midst of him his own ruler will go forth; and I will cause him to come near, and he must approach to me.”
“For who, now, is this one that has given his heart in pledge in order to approach to me?” is the utterance of Jehovah.

[[v24-30-22]]

^<<v24-30-22,22>>^ “And YOU will certainly become my people, and I myself shall become YOUR God.”

[[v24-30-23]]

^<<v24-30-23,23>>^ Look! A windstorm of Jehovah, rage itself, has gone forth, an onward-sweeping tempest.^&#42;1^ Upon the head of the wicked ones it will whirl.

[NOTE]
====
. Or, “a roaring tempest.”
====

[[v24-30-24]]

^<<v24-30-24,24>>^ The burning anger of Jehovah will not turn back until he will have executed and until he will have carried out the ideas of his heart. In the final part of the days YOU people will give YOUR consideration to it.

'''

xref:024-jeremiah/024-jeremiah-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremiah/024-jeremiah-031.adoc#v24-31-0[Próximo Capítulo &#62;]