include::./index.adoc[]

[[v24-35-0]]
=== Jeremiah, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-35-1]]

^<<v24-35-1,1>>^ The word that occurred to Jeremiah from Jehovah in the days of Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah, saying:

[[v24-35-2]]

^<<v24-35-2,2>>^ “Go^&#42;1^ to the house of the Reʹcha·bites, and you must speak with them and bring them into the house of Jehovah, to one of the dining rooms; and you must give them wine to drink.”

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-35-3]]

^<<v24-35-3,3>>^ So I took Ja·az·a·niʹah the son of Jeremiah the son of Hab·az·zi·niʹah and his brothers, and all his sons, and all the household of the Reʹcha·bites,

[[v24-35-4]]

^<<v24-35-4,4>>^ and I proceeded to bring them into the house of Jehovah, to the dining room of the sons of Haʹnan the son of Ig·da·liʹah,^&#42;1^ a man of the &#91;true&#93; God,^&#42;2^ which was beside the dining room of the princes that was above the dining room of Ma·a·seiʹah^&#42;3^ the son of Shalʹlum the doorkeeper.^&#42;4^

[NOTE]
====
. Meaning “Great Is Jehovah.” Heb., Yigh·dal·yaʹhu.
. “A man of the [true] God.” Heb., ʼish ha·ʼElo·himʹ. See App 1F.
. Meaning “Work of Jehovah.” Heb., Ma·ʽase·yaʹhu.
. Lit., “keeper of the threshold.”
====

[[v24-35-5]]

^<<v24-35-5,5>>^ Then I put before the sons of the house of the Reʹcha·bites cups full of wine and goblets and said to them: “Drink wine.”

[[v24-35-6]]

^<<v24-35-6,6>>^ But they said: “We shall drink no wine, because Jonʹa·dab the son of Reʹchab, our forefather, was the one that laid the command upon us, saying, ‘YOU must drink no wine, neither YOU nor YOUR sons, to time indefinite.

[[v24-35-7]]

^<<v24-35-7,7>>^ And no house must YOU build, and no seed must YOU sow; and no vineyard must YOU plant, nor must it come to be YOURS. But in tents YOU should dwell all YOUR days, in order that YOU may keep living many days upon the surface of the ground where YOU are residing as aliens.’

[[v24-35-8]]

^<<v24-35-8,8>>^ So we keep obeying the voice of Je·honʹa·dab^&#42;1^ the son of Reʹchab our forefather in everything that he commanded us by drinking no wine all our days, we, our wives, our sons and our daughters,

[NOTE]
====
. “Jehonadab.” Heb., Yehoh·na·dhavʹ, as in 2Ki 10:15, where see ftn.
====

[[v24-35-9]]

^<<v24-35-9,9>>^ and by not building houses for us to dwell in, so that no vineyard or field or seed should become ours.

[[v24-35-10]]

^<<v24-35-10,10>>^ And we keep dwelling in tents and obeying and doing according to all that Jonʹa·dab our forefather commanded us.

[[v24-35-11]]

^<<v24-35-11,11>>^ But it came about when Neb·u·chad·rezʹzar the king of Babylon came up against the land that we began to say, ‘Come, and let us enter into Jerusalem because of the military force of the Chal·deʹans and because of the military force of the Syrians,^&#42;1^ and let us dwell in Jerusalem.’”

[NOTE]
====
. Or, “Aramaeans.” Heb., ʼAramʹ.
====

[[v24-35-12]]

^<<v24-35-12,12>>^ And the word of Jehovah proceeded to occur to Jeremiah, saying:

[[v24-35-13]]

^<<v24-35-13,13>>^ “This is what Jehovah of armies, the God of Israel, has said, ‘Go, and you must say to the men^&#42;1^ of Judah and to the inhabitants of Jerusalem: “Did YOU not continually receive exhortation to obey my words?” is the utterance of Jehovah.

[NOTE]
====
. “To the men of.” Heb., leʼishʹ, sing. but used collectively.
====

[[v24-35-14]]

^<<v24-35-14,14>>^ “There has been a carrying out of the words of Je·honʹa·dab the son of Reʹchab, that he commanded his sons, to drink no wine, and they have drunk none down to this day, because they have obeyed the commandment of their forefather. And as for me, I have spoken to YOU men, rising up early and speaking, but YOU have not obeyed me.

[[v24-35-15]]

^<<v24-35-15,15>>^ And I kept sending to YOU all my servants the prophets, rising up early and sending &#91;them&#93;, saying, ‘Turn back, please, each one from his bad way, and make YOUR dealings good, and do not walk after other gods to serve them. And keep dwelling on the ground that I have given to YOU and to YOUR forefathers.’ But YOU did not incline YOUR ear, nor did YOU listen to me.

[[v24-35-16]]

^<<v24-35-16,16>>^ But the sons of Je·honʹa·dab the son of Reʹchab have carried out the commandment of their forefather that he commanded them; but as for this people, they have not listened to me.”’”

[[v24-35-17]]

^<<v24-35-17,17>>^ “Therefore this is what Jehovah, the God of armies, the God of Israel, has said, ‘Here I am bringing upon Judah and upon all the inhabitants of Jerusalem all the calamity that I have spoken against them, for the reason that I have spoken to them but they did not listen, and I kept calling to them but they did not answer.’”

[[v24-35-18]]

^<<v24-35-18,18>>^ And to the household of the Reʹcha·bites Jeremiah said: “This is what Jehovah of armies, the God of Israel, has said, ‘For the reason that YOU have obeyed the commandment of Je·honʹa·dab YOUR forefather and continue keeping all his commandments and doing according to all that he commanded YOU,

[[v24-35-19]]

^<<v24-35-19,19>>^ therefore this is what Jehovah of armies, the God of Israel, has said: “There will not be cut off from Jonʹa·dab the son of Reʹchab a man to stand^&#42;1^ before me always.”’”^&#42;2^

[NOTE]
====
. Lit., “standing.”
. Lit., “all the days.”
====

'''

xref:024-jeremiah/024-jeremiah-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremiah/024-jeremiah-036.adoc#v24-36-0[Próximo Capítulo &#62;]