include::./index.adoc[]

[[v24-37-0]]
=== Jeremiah, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-37-1]]

^<<v24-37-1,1>>^ And King Zed·e·kiʹah the son of Jo·siʹah began to reign in place of Co·niʹah^&#42;1^ the son of Je·hoiʹa·kim, whom Neb·u·chad·rezʹzar the king of Babylon made king in the land of Judah.

[NOTE]
====
. See 22:24 ftn.
====

[[v24-37-2]]

^<<v24-37-2,2>>^ And he himself and his servants and the people of the land^&#42;1^ did not listen to the words of Jehovah that he spoke by means of Jeremiah the prophet.

[NOTE]
====
. See 34:19 ftn.
====

[[v24-37-3]]

^<<v24-37-3,3>>^ And King Zed·e·kiʹah proceeded to send Je·huʹcal the son of Shel·e·miʹah^&#42;1^ and Zeph·a·niʹah^&#42;2^ the son of Ma·a·seiʹah^&#42;3^ the priest to Jeremiah the prophet, saying: “Pray, please, in our behalf to Jehovah our God.”

[NOTE]
====
. Heb., She·lem·yahʹ. Compare 36:14 ftn, “Shelemiah.”
. Meaning “Jehovah Has Concealed [or, Treasured].” Heb., Tsephan·yaʹhu.
. Heb., Ma·ʽase·yahʹ. Compare 35:4 ftn, “Maaseiah.”
====

[[v24-37-4]]

^<<v24-37-4,4>>^ And Jeremiah was coming in and going out into the midst of the people, as they had not put him in the house of detention.

[[v24-37-5]]

^<<v24-37-5,5>>^ And there was a military force of Pharʹaoh that came out of Egypt; and the Chal·deʹans that were laying siege to Jerusalem got to hear the report about them. So they withdrew from against Jerusalem.

[[v24-37-6]]

^<<v24-37-6,6>>^ Then the word of Jehovah occurred to Jeremiah the prophet, saying:

[[v24-37-7]]

^<<v24-37-7,7>>^ “This is what Jehovah the God of Israel has said, ‘This is what YOU men should say to the king of Judah, the one sending YOU to me to inquire of me: “Look! The military force of Pharʹaoh that is coming forth to YOU people for the purpose of assistance will have to go back to their land, Egypt.

[[v24-37-8]]

^<<v24-37-8,8>>^ And the Chal·deʹans will certainly come back and fight against this city and capture it and burn it with fire.”

[[v24-37-9]]

^<<v24-37-9,9>>^ This is what Jehovah has said: “Do not deceive YOUR souls, saying, ‘The Chal·deʹans will without fail go away from against us,’ because they will not go away.

[[v24-37-10]]

^<<v24-37-10,10>>^ For if YOU men had struck down all the military force of the Chal·deʹans who are fighting YOU and there remained over among them men^&#42;1^ pierced through, they would each one in his tent rise up and actually burn this city with fire.”’”

[NOTE]
====
. “Men.” Heb., ʼana·shimʹ, pl. of ʼish.
====

[[v24-37-11]]

^<<v24-37-11,11>>^ And it occurred when the military force of the Chal·deʹans had withdrawn themselves from against Jerusalem because of the military force of Pharʹaoh,

[[v24-37-12]]

^<<v24-37-12,12>>^ that Jeremiah began to go forth from Jerusalem to go to the land of Benjamin and to get &#91;his&#93; portion from there in the midst of the people.

[[v24-37-13]]

^<<v24-37-13,13>>^ So it came about when he was in the Gate of Benjamin that the officer holding the oversight, whose name was I·riʹjah the son of Shel·e·miʹah the son of Han·a·niʹah, was there. At once he took hold of Jeremiah the prophet, saying: “It is to the Chal·deʹans that you are falling away!”^&#42;1^

[NOTE]
====
. Or, “deserting.”
====

[[v24-37-14]]

^<<v24-37-14,14>>^ But Jeremiah said: “It is false! I am not falling away to the Chal·deʹans.” But he did not listen to him. So I·riʹjah kept hold of Jeremiah and brought him in to the princes.

[[v24-37-15]]

^<<v24-37-15,15>>^ And the princes began to get indignant at Jeremiah, and they struck him and put him into the house of fetters, in the house of Je·honʹa·than the secretary, for this was what they had made the house of detention.

[[v24-37-16]]

^<<v24-37-16,16>>^ When Jeremiah came into the house of the cistern and into the vaulted rooms, then Jeremiah continued dwelling there many days.

[[v24-37-17]]

^<<v24-37-17,17>>^ And King Zed·e·kiʹah proceeded to send and take him, and the king began asking him questions in his house in a place of concealment. And he went on to say: “Does there exist a word from Jehovah?” To this Jeremiah said: “There does exist!” And he said further: “Into the hand of the king of Babylon you will be given!”

[[v24-37-18]]

^<<v24-37-18,18>>^ Then Jeremiah said to King Zed·e·kiʹah: “In what way have I sinned against you and against your servants and against this people, so that YOU men have put me into the house of detention?

[[v24-37-19]]

^<<v24-37-19,19>>^ Where, now, are YOUR prophets who prophesied to YOU, saying, ‘The king of Babylon will not come against YOU men and against this land’?

[[v24-37-20]]

^<<v24-37-20,20>>^ And now listen, please, O my lord the king. May my request for favor, please, fall before you, and do not send me back to the house of Je·honʹa·than the secretary, that I may not die there.”

[[v24-37-21]]

^<<v24-37-21,21>>^ Accordingly King Zed·e·kiʹah commanded, and they then put Jeremiah in custody in the Courtyard of the Guard; and there was a giving of a round loaf of bread to him daily from the street of the bakers, until all the bread was exhausted from the city. And Jeremiah continued dwelling in the Courtyard of the Guard.

'''

xref:024-jeremiah/024-jeremiah-036.adoc#v24-36-0[&#60; Capítulo Anterior] | <<v24-37-0,Topo>> | xref:024-jeremiah/024-jeremiah-038.adoc#v24-38-0[Próximo Capítulo &#62;]