include::./index.adoc[]

[[v24-2-0]]
=== Jeremiah, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-2-1]]

^<<v24-2-1,1>>^ And the word of Jehovah proceeded to occur to me, saying:

[[v24-2-2]]

^<<v24-2-2,2>>^ “Go,^&#42;1^ and you must call out in the ears of Jerusalem, saying, ‘This is what Jehovah has said: “I well remember, on your^&#42;2^ part, the loving-kindness^&#42;3^ of your youth, the love during your being engaged to marry, your walking after me in the wilderness, in a land not sown with seed.

[NOTE]
====
. Lit., “Let there be a going.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. “Your,” fem. sing., addressed to “Jerusalem.”
. Or, “loyal love.” Heb., cheʹsedh.
====

[[v24-2-3]]

^<<v24-2-3,3>>^ Israel was something holy^&#42;1^ to Jehovah, the first yield to Him.”’^&#42;2^ ‘Any persons devouring him would make themselves guilty. Calamity itself would come upon them,’ was the utterance of Jehovah.”

[NOTE]
====
. Or, “was holiness.” Heb., qoʹdhesh.
. Or, “the firstfruits of His produce.”
====

[[v24-2-4]]

^<<v24-2-4,4>>^ Hear the word of Jehovah, O house of Jacob, and all YOU families of the house of Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ This is what Jehovah has said: “What have YOUR fathers found in me that was unjust, so that they have become far off from me, and they kept walking after the vain idol and becoming vain themselves?

[[v24-2-6]]

^<<v24-2-6,6>>^ And they have not said, ‘Where is Jehovah, the One bringing us up out of the land of Egypt, the One walking us through the wilderness, through a land of desert plain and pit, through a land of no water and of deep shadow,^&#42;1^ through a land through which no man^&#42;2^ passed and in which no earthling man^&#42;3^ dwelt?’

[NOTE]
====
. Or, “death shadow.”
. “Man.” Heb., ʼish.
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v24-2-7]]

^<<v24-2-7,7>>^ “And I gradually brought YOU to a land of the orchard, to eat its fruitage and its good things. But YOU came in and defiled my land; and my own inheritance YOU made something detestable.

[[v24-2-8]]

^<<v24-2-8,8>>^ The priests themselves did not say, ‘Where is Jehovah?’ And the very ones handling the law did not know me; and the shepherds themselves transgressed^&#42;1^ against me, and even the prophets prophesied by Baʹal, and after those who could bring no benefit they walked.

[NOTE]
====
. Or, “revolted.”
====

[[v24-2-9]]

^<<v24-2-9,9>>^ “‘Therefore I shall contend further with YOU people,’ is the utterance of Jehovah, ‘and with the sons of YOUR sons I shall contend.’

[[v24-2-10]]

^<<v24-2-10,10>>^ “‘But pass over to the coastlands^&#42;1^ of the Kitʹtim and see. Yes, send even to Keʹdar and give YOUR special consideration, and see whether anything like this has happened.

[NOTE]
====
. Or, “islands.”
====

[[v24-2-11]]

^<<v24-2-11,11>>^ Has a nation exchanged gods, even for those that are no gods?^&#42;1^ But my own people have exchanged my^&#42;2^ glory for what can bring no benefit.

[NOTE]
====
. “Are no gods.” Heb., loʼ ʼelo·himʹ.
. “My,” in the original Heb. text; MLXXSyVg, “its.” One of the Eighteen Emendations of the Sopherim made out of a misapplied reverence for Jehovah God. See App 2B.
====

[[v24-2-12]]

^<<v24-2-12,12>>^ Stare in amazement, O YOU heavens, at this; and bristle up in very great horror,’^&#42;1^ is the utterance of Jehovah,

[NOTE]
====
. “In very great horror,” by a correction; M, “be [pl.] very much devastated.”
====

[[v24-2-13]]

^<<v24-2-13,13>>^ ‘because there are two bad things that my people have done: They have left even me, the source of living water, in order to hew out for themselves cisterns, broken cisterns, that cannot contain the water.’

[[v24-2-14]]

^<<v24-2-14,14>>^ “‘Is Israel a servant,^&#42;1^ or a slave born in the household? Why is it that he has come to be for plunder?

[NOTE]
====
. Or, “Is Israel a slave.” Heb., ha·ʽeʹvedh Yis·ra·ʼelʹ.
====

[[v24-2-15]]

^<<v24-2-15,15>>^ Against him maned young lions roar; they have given out their voice. And they went making his land an object of astonishment. His own cities have been set afire, so that there is no inhabitant.

[[v24-2-16]]

^<<v24-2-16,16>>^ Even the sons of Noph^&#42;1^ and Tahʹpan·es^&#42;2^ themselves kept feeding on you at the crown of the head.

[NOTE]
====
. “Memphis,” LXXVg.
. “Tahpanhes,” Mmargin.
====

[[v24-2-17]]

^<<v24-2-17,17>>^ Is not this what you^&#42;1^ proceeded to do to yourself by your leaving Jehovah your God during the time of &#91;his&#93; walking you in the way?

[NOTE]
====
. “You,” fem. sing., addressed to Jerusalem.
====

[[v24-2-18]]

^<<v24-2-18,18>>^ And now what concern should you have for the way of Egypt in order to drink the waters of Shiʹhor?^&#42;1^ And what concern should you have for the way of As·syrʹi·a in order to drink the waters of the River?^&#42;2^

[NOTE]
====
. Or, “a branch of the Nile.”
. That is, the Euphrates.
====

[[v24-2-19]]

^<<v24-2-19,19>>^ Your badness should correct you, and your own acts of unfaithfulness should reprove you. Know, then, and see that your leaving Jehovah your God is something bad and bitter, and no dread of me &#91;has resulted&#93; to you,’ is the utterance of the Sovereign Lord, Jehovah of armies.

[[v24-2-20]]

^<<v24-2-20,20>>^ “‘For long ago I broke your yoke to pieces; I tore your bands apart. But you said: “I am not going to serve,” for upon every high hill and under every luxuriant tree you were lying sprawled out, prostituting yourself.

[[v24-2-21]]

^<<v24-2-21,21>>^ And as for me, I had planted you as a choice red vine, all of it a true seed. So how have you been changed toward me into the degenerate &#91;shoots&#93; of a foreign vine?’

[[v24-2-22]]

^<<v24-2-22,22>>^ “‘But though you should do the washing with alkali and take to yourself large quantities of lye, your error would certainly be a stain before me,’ is the utterance of the Sovereign Lord Jehovah.

[[v24-2-23]]

^<<v24-2-23,23>>^ How can you say, ‘I have not defiled myself. After the Baʹals^&#42;1^ I have not walked’? See your way in the valley. Take note of what you have done. A swift young she-camel aimlessly running to and fro in her ways;

[NOTE]
====
. Or, “Baal images.”
====

[[v24-2-24]]

^<<v24-2-24,24>>^ a zebra accustomed to the wilderness, at the craving of her soul, snuffing up the wind;^&#42;1^ at her time for copulation, who can turn her back? All those who are looking for her will not go tiring themselves out. In her month they will find her.

[NOTE]
====
. “Wind.” Heb., ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v24-2-25]]

^<<v24-2-25,25>>^ Hold your foot back from &#91;becoming&#93; barefoot, and your throat from thirst. But you proceeded to say, ‘It is hopeless! No, but I have fallen in love with strangers, and after them I am going to walk.’

[[v24-2-26]]

^<<v24-2-26,26>>^ “As with the shame of a thief when he is found out, so those of the house of Israel have felt shame, they, their kings, their princes and their priests and their prophets.

[[v24-2-27]]

^<<v24-2-27,27>>^ They are saying to a tree, ‘You are my father,’ and to a stone, ‘You yourself brought me to birth.’ But to me they have turned the back of the neck and not the face. And in the time of their calamity they will say, ‘Do rise up and save us!’

[[v24-2-28]]

^<<v24-2-28,28>>^ “But where are your gods^&#42;1^ that you have made for yourself? Let them rise up if they can save you in the time of your calamity. For as the number of your cities your gods have become, O Judah.

[NOTE]
====
. “Your gods.” Heb., ʼelo·heyʹkha, pl. of ʼelohʹah, with eyʹkha, “your,” masc. sing., addressed to “Judah.”
====

[[v24-2-29]]

^<<v24-2-29,29>>^ “‘Why do YOU people keep contending against me? Why have YOU transgressed, all of YOU, against me?’ is the utterance of Jehovah.

[[v24-2-30]]

^<<v24-2-30,30>>^ To no effect I have struck YOUR sons. No discipline did they take. YOUR sword has devoured YOUR prophets, like a lion that is causing ruin.

[[v24-2-31]]

^<<v24-2-31,31>>^ O generation, see for yourselves the word of Jehovah.
“Have I become a mere wilderness to Israel or a land of intense darkness? Why is it that these, my people, have said, ‘We have roamed. We shall come to you no more’?

[[v24-2-32]]

^<<v24-2-32,32>>^ Can a virgin forget her ornaments, a bride her breastbands? And yet my own people—they have forgotten me days without number.

[[v24-2-33]]

^<<v24-2-33,33>>^ “Why do you,^&#42;1^ O woman, improve your way in order to look for love? Therefore it has also been in bad things that you have taught your ways.

[NOTE]
====
. “You,” fem. sing., addressed to Jerusalem, or Zion.
====

[[v24-2-34]]

^<<v24-2-34,34>>^ Also, in your skirts^&#42;1^ there have been found the blood marks^&#42;2^ of the souls^&#42;3^ of the innocent poor ones. Not in the act of breaking in^&#42;4^ have I found them, but &#91;they are&#93; upon all these.

[NOTE]
====
. “Skirts,” MVg; LXXSy, “hands.”
. “Blood marks.” LXX, “bloods.” Lit., “blood,” sing. in M, but the accompanying Heb. verb for “have been found” and the following Heb. pronoun for “them” are pl.
. “The souls of.” Heb., naph·shohthʹ; Gr., psy·khonʹ; Lat., a·ni·maʹrum. See App 4A.
. Or, “housebreaking.”
====

[[v24-2-35]]

^<<v24-2-35,35>>^ “But you say, ‘I have remained innocent. Surely his anger has turned back from me.’
“Here I am entering into controversy with you on account of your saying, ‘I have not sinned.’

[[v24-2-36]]

^<<v24-2-36,36>>^ Why do you treat as very insignificant the changing of your way? Of Egypt, too, you will become ashamed, just as you became ashamed of As·syrʹi·a.

[[v24-2-37]]

^<<v24-2-37,37>>^ For this cause also you will go forth with your hands upon your head, because Jehovah has rejected the objects of your confidence, and you will have no success with them.”

'''

xref:024-jeremiah/024-jeremiah-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremiah/024-jeremiah-003.adoc#v24-3-0[Próximo Capítulo &#62;]