include::./index.adoc[]

[[v24-1-0]]
=== Jeremiah, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-1-1]]

^<<v24-1-1,1>>^ The words of Jeremiah^&#42;1^ the son of Hil·kiʹah,^&#42;2^ one of the priests that were in Anʹa·thoth in the land of Benjamin;

[NOTE]
====
. Meaning “Jehovah Loosens [the womb]”; or, “Jehovah Exalts.” Heb., Yir·meyaʹhu.
. Meaning “My Portion Is Jehovah.” Heb., Chil·qi·yaʹhu.
====

[[v24-1-2]]

^<<v24-1-2,2>>^ to whom the word of Jehovah occurred in the days of Jo·siʹah the son of Aʹmon, the king of Judah, in the thirteenth year of his reigning.

[[v24-1-3]]

^<<v24-1-3,3>>^ And it kept on occurring in the days of Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah, until the completion of the eleventh year of Zed·e·kiʹah^&#42;1^ the son of Jo·siʹah, the king of Judah, until Jerusalem went into exile in the fifth month.

[NOTE]
====
. “Of Zedekiah.” Heb., leTsidh·qi·yaʹhu, meaning “Jehovah Is Righteousness.”
====

[[v24-1-4]]

^<<v24-1-4,4>>^ And the word of Jehovah began to occur to me, saying:

[[v24-1-5]]

^<<v24-1-5,5>>^ “Before I was forming you in the belly I knew you, and before you proceeded to come forth from the womb I sanctified you. Prophet to the nations I made you.”

[[v24-1-6]]

^<<v24-1-6,6>>^ But I said: “Alas, O Sovereign Lord Jehovah! Here I actually do not know how to speak, for I am but a boy.”^&#42;1^

[NOTE]
====
. Or, “young person.” Heb., naʹʽar.
====

[[v24-1-7]]

^<<v24-1-7,7>>^ And Jehovah went on to say to me: “Do not say, ‘I am but a boy.’ But to all those to whom I shall send you, you should go; and everything that I shall command you, you should speak.

[[v24-1-8]]

^<<v24-1-8,8>>^ Do not be afraid because of their faces, for ‘I am with you to deliver you,’ is the utterance of Jehovah.”

[[v24-1-9]]

^<<v24-1-9,9>>^ At that Jehovah thrust his hand out and caused it to touch my mouth. Then Jehovah said to me: “Here I have put my words in your mouth.

[[v24-1-10]]

^<<v24-1-10,10>>^ See, I have commissioned you this day to be over the nations and over the kingdoms, in order to uproot and to pull down and to destroy and to tear down, to build and to plant.”

[[v24-1-11]]

^<<v24-1-11,11>>^ And the word of Jehovah continued to occur to me, saying: “What are you seeing, Jeremiah?”
So I said: “An offshoot^&#42;1^ of an almond tree^&#42;2^ is what I am seeing.”

[NOTE]
====
. Or, “staff; rod.” Compare 1Sa 17:40, 43.
. “An almond tree.” Heb., sha·qedhʹ, “awakening one”; one of the first trees to bloom in the spring.
====

[[v24-1-12]]

^<<v24-1-12,12>>^ And Jehovah went on to say to me: “You have seen well, for I am keeping awake^&#42;1^ concerning my word in order to carry it out.”

[NOTE]
====
. “Am keeping awake.” Heb., sho·qedhʹ, corresponding to sha·qedhʹ in vs 11.
====

[[v24-1-13]]

^<<v24-1-13,13>>^ And the word of Jehovah proceeded to occur to me the second time, saying: “What are you seeing?”
So I said: “A widemouthed cooking pot blown upon^&#42;1^ is what I am seeing, and its mouth^&#42;2^ is away from the north.”

[NOTE]
====
. “Blown upon,” as respects the fire underneath. Or, “set aflame,” suggesting a furnace.
. Lit., “face.” But see Zec 5:8.
====

[[v24-1-14]]

^<<v24-1-14,14>>^ At this Jehovah said to me: “Out of the north the calamity will be loosened against all the inhabitants of the land.

[[v24-1-15]]

^<<v24-1-15,15>>^ For ‘here I am calling for all the families of the kingdoms of the north,’ is the utterance of Jehovah; ‘and they will certainly come and place each one his throne at the entrance of the gates of Jerusalem, and against all her walls round about and against all the cities of Judah.

[[v24-1-16]]

^<<v24-1-16,16>>^ And I will speak with them my judgments over all their badness, in that they have left me and they keep making sacrificial smoke to other gods^&#42;1^ and bowing down to the works of their own hands.’

[NOTE]
====
. “To . . . gods.” Heb., leʼ·lo·himʹ.
====

[[v24-1-17]]

^<<v24-1-17,17>>^ “And as for you, you should gird up your hips, and you must rise up and speak to them everything that I myself command you. Do not be struck with any terror because of them, in order that I may not strike you with terror before them.

[[v24-1-18]]

^<<v24-1-18,18>>^ But as for me, here I have made you today a fortified city and an iron pillar and copper walls against all the land, toward the kings of Judah, toward her princes, toward her priests and toward the people of the land.^&#42;1^

[NOTE]
====
. “And toward the people of the land.” Heb., u·leʽamʹ ha·ʼaʹrets. Later used contemptuously. Compare Joh 7:47-49.
====

[[v24-1-19]]

^<<v24-1-19,19>>^ And they will be certain to fight against you, but they will not prevail against you, for ‘I am with you,’ is the utterance of Jehovah, ‘to deliver you.’”

'''

xref:023-isaiah/023-isaiah-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremiah/024-jeremiah-002.adoc#v24-2-0[Próximo Capítulo &#62;]