include::./index.adoc[]

[[v24-29-0]]
=== Jeremiah, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-29-1]]

^<<v24-29-1,1>>^ And these are the words of the letter that Jeremiah the prophet sent from Jerusalem to the remainder of the older men of the exiled people and to the priests and to the prophets and to all the people, whom Neb·u·chad·nezʹzar had carried into exile from Jerusalem to Babylon,

[[v24-29-2]]

^<<v24-29-2,2>>^ after Jec·o·niʹah the king and the lady and the court officials, the princes of Judah and Jerusalem, and the craftsmen and the builders of bulwarks had gone forth from Jerusalem.

[[v24-29-3]]

^<<v24-29-3,3>>^ It was by the hand of El·aʹsah the son of Shaʹphan and Gem·a·riʹah the son of Hil·kiʹah, whom Zed·e·kiʹah the king of Judah sent to Babylon to Neb·u·chad·nezʹzar the king of Babylon, saying:

[[v24-29-4]]

^<<v24-29-4,4>>^ “This is what Jehovah of armies, the God of Israel, has said to all the exiled people, whom I have caused to go into exile from Jerusalem to Babylon,

[[v24-29-5]]

^<<v24-29-5,5>>^ ‘Build houses and inhabit &#91;them&#93;, and plant gardens and eat their fruitage.

[[v24-29-6]]

^<<v24-29-6,6>>^ Take wives and become father to sons and to daughters; and take wives for YOUR own sons and give YOUR own daughters to husbands, that they may give birth to sons and to daughters; and become many there, and do not become few.

[[v24-29-7]]

^<<v24-29-7,7>>^ Also, seek the peace of the city to which I have caused YOU to go into exile, and pray in its behalf to Jehovah, for in its peace there will prove to be peace for YOU yourselves.

[[v24-29-8]]

^<<v24-29-8,8>>^ For this is what Jehovah of armies, the God of Israel, has said: “Let not YOUR prophets who are in among YOU and YOUR practicers of divination deceive YOU, and do not YOU listen to their^&#42;1^ dreams that they^&#42;2^ are dreaming.

[NOTE]
====
. “Your,” MTLXXSyVg. Compare 27:9.
. “You,” MTLXXSyVg.
====

[[v24-29-9]]

^<<v24-29-9,9>>^ For ‘it is in falsehood that they are prophesying to YOU in my name. I have not sent them,’ is the utterance of Jehovah.”’”

[[v24-29-10]]

^<<v24-29-10,10>>^ “For this is what Jehovah has said, ‘In accord with the fulfilling of seventy years at Babylon I shall turn my attention to YOU people, and I will establish toward YOU my good word in bringing YOU back to this place.’

[[v24-29-11]]

^<<v24-29-11,11>>^ “‘For I myself well know the thoughts that I am thinking toward YOU,’ is the utterance of Jehovah, ‘thoughts of peace, and not of calamity, to give YOU a future and a hope.

[[v24-29-12]]

^<<v24-29-12,12>>^ And YOU will certainly call me and come and pray to me, and I will listen to YOU.’

[[v24-29-13]]

^<<v24-29-13,13>>^ “‘And YOU will actually seek me and find &#91;me&#93;, for YOU will search for me with all YOUR heart.

[[v24-29-14]]

^<<v24-29-14,14>>^ And I will let myself be found by YOU,’ is the utterance of Jehovah. ‘And I will gather YOUR body of captives and collect YOU together out of all the nations and out of all the places to which I have dispersed YOU,’ is the utterance of Jehovah. ‘And I will bring YOU back to the place from which I caused YOU to go into exile.’

[[v24-29-15]]

^<<v24-29-15,15>>^ “But YOU have said, ‘Jehovah has raised up for us prophets in Babylon.’

[[v24-29-16]]

^<<v24-29-16,16>>^ “For this is what Jehovah has said to the king sitting on the throne of David and to all the people dwelling in this city, YOUR brothers that have not gone forth with YOU into exile,

[[v24-29-17]]

^<<v24-29-17,17>>^ ‘This is what Jehovah of armies has said: “Here I am sending against them the sword, the famine and the pestilence, and I will make them like the burst-open figs that cannot be eaten for badness.”’

[[v24-29-18]]

^<<v24-29-18,18>>^ “‘And I will pursue after them with the sword, with the famine and with the pestilence, and I will give them for a quaking to all the kingdoms of the earth, for a curse and for an object of astonishment and for a whistling at and for a reproach among all the nations to which I shall certainly disperse them,

[[v24-29-19]]

^<<v24-29-19,19>>^ due to the fact that they have not listened to my words,’ is the utterance of Jehovah, ‘that I have sent to them with my servants the prophets, getting up early and sending &#91;them&#93;.’
“‘But YOU have not listened,’ is the utterance of Jehovah.

[[v24-29-20]]

^<<v24-29-20,20>>^ “And as for YOU, hear the word of Jehovah, all you exiled people, whom I have sent away from Jerusalem to Babylon.

[[v24-29-21]]

^<<v24-29-21,21>>^ This is what Jehovah of armies, the God of Israel, has said concerning Aʹhab the son of Ko·laiʹah and to Zed·e·kiʹah the son of Ma·a·seiʹah, who are prophesying to YOU falsehood in my own name, ‘Here I am giving them into the hand of Neb·u·chad·rezʹzar the king of Babylon, and he must strike them down before YOUR eyes.

[[v24-29-22]]

^<<v24-29-22,22>>^ And from them a malediction will certainly be taken on the part of the entire body of exiles of Judah that is in Babylon, saying: “May Jehovah make you like Zed·e·kiʹah and like Aʹhab, whom the king of Babylon roasted in the fire!”

[[v24-29-23]]

^<<v24-29-23,23>>^ for the reason that they have carried on senselessness in Israel, and they keep committing adultery with the wives of their companions and keep speaking falsely in my own name the word that I did not command them.
“‘“And I am the One knowing and am a witness,” is the utterance of Jehovah.’”

[[v24-29-24]]

^<<v24-29-24,24>>^ “And to She·maiʹah^&#42;1^ of Ne·helʹam you will say,

[NOTE]
====
. Meaning “Jehovah Has Heard.” Heb., Shemaʽ·yaʹhu.
====

[[v24-29-25]]

^<<v24-29-25,25>>^ ‘This is what Jehovah of armies, the God of Israel, has said: “For the reason that you yourself have sent in your name letters to all the people who are in Jerusalem, and to Zeph·a·niʹah the son of Ma·a·seiʹah, the priest, and to all the priests, saying,

[[v24-29-26]]

^<<v24-29-26,26>>^ ‘Jehovah himself has made you priest instead of Je·hoiʹa·da the priest, in order to become the grand overseer^&#42;1^ of the house of Jehovah toward any man^&#42;2^ maddened and behaving like a prophet, and you must put him into the stocks and into the pillory;

[NOTE]
====
. “The grand overseer.” Lit., “overseers.” Heb., peqi·dhimʹ, pl. to denote grandeur.
. “Man.” Heb., ʼish.
====

[[v24-29-27]]

^<<v24-29-27,27>>^ now, then, why have you not rebuked Jeremiah of Anʹa·thoth, who is behaving as a prophet to YOU people?

[[v24-29-28]]

^<<v24-29-28,28>>^ For that is why he has sent to us at Babylon, saying: “It^&#42;1^ is long drawn out! Build houses and inhabit &#91;them&#93;, and plant gardens and eat their fruitage,—”’”’”

[NOTE]
====
. “It,” fem. sing., apparently referring to the “exile” in vss 14, 16.
====

[[v24-29-29]]

^<<v24-29-29,29>>^ And Zeph·a·niʹah the priest proceeded to read this letter in the ears of Jeremiah the prophet.

[[v24-29-30]]

^<<v24-29-30,30>>^ Then the word of Jehovah occurred to Jeremiah, saying:

[[v24-29-31]]

^<<v24-29-31,31>>^ “Send to all the exiled people, saying, ‘This is what Jehovah has said concerning She·maiʹah of Ne·helʹam: “For the reason that She·maiʹah has prophesied to YOU people, but I myself did not send him, and he tried to make YOU trust in falsehood,

[[v24-29-32]]

^<<v24-29-32,32>>^ therefore this is what Jehovah has said, ‘Here I am turning my attention upon She·maiʹah of Ne·helʹam and upon his offspring.’
“‘“‘He will not come to have a man dwelling in the midst of this people; and he will not look upon the good that I am doing for my people,’ is the utterance of Jehovah, ‘for he has spoken outright revolt against Jehovah.’”’”

'''

xref:024-jeremiah/024-jeremiah-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremiah/024-jeremiah-030.adoc#v24-30-0[Próximo Capítulo &#62;]