include::./index.adoc[]

[[v24-4-0]]
=== Jeremiah, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-4-1]]

^<<v24-4-1,1>>^ “If you would return, O Israel,” is the utterance of Jehovah, “you may return even to me. And if you will take away your disgusting things on my account,^&#42;1^ then you will not go as a fugitive.

[NOTE]
====
. Lit., “from my face.”
====

[[v24-4-2]]

^<<v24-4-2,2>>^ And &#91;if&#93; you will certainly swear, ‘As Jehovah is alive in truth, in justice and in righteousness!’ then in him^&#42;1^ the nations will actually bless themselves, and in him they will boast about themselves.”

[NOTE]
====
. “Him.” Possibly referring to “Israel.”
====

[[v24-4-3]]

^<<v24-4-3,3>>^ For this is what Jehovah has said to the men^&#42;1^ of Judah and to Jerusalem: “Plow for yourselves arable land, and do not keep sowing among^&#42;2^ thorns.

[NOTE]
====
. “To the men of.” Heb., leʼishʹ, sing. but used collectively.
. Lit., “to”; or, “for.”
====

[[v24-4-4]]

^<<v24-4-4,4>>^ Get yourselves circumcised to Jehovah, and take away the foreskins of YOUR hearts, YOU men^&#42;1^ of Judah and inhabitants of Jerusalem; that my rage may not go forth just like a fire, and it certainly burn with no one to do the extinguishing, on account of the badness of YOUR dealings.”

[NOTE]
====
. “Men of.” Heb., ʼish, sing. but used collectively.
====

[[v24-4-5]]

^<<v24-4-5,5>>^ Tell &#91;it&#93; in Judah, YOU men, and publish &#91;it&#93; even in Jerusalem, and say &#91;it&#93; out, and blow a horn^&#42;1^ throughout the land. Call out loudly^&#42;2^ and say: “Gather yourselves together, and let us enter into the fortified cities.

[NOTE]
====
. Or, “shofar.”
. Lit., “Call out, be full [do it fully].”
====

[[v24-4-6]]

^<<v24-4-6,6>>^ Raise a signal toward Zion. Make provision for shelter. Do not stand still.” For there is a calamity that I am bringing in from the north, even a great crash.

[[v24-4-7]]

^<<v24-4-7,7>>^ He has gone up as a lion out of his thicket, and the one who is bringing the nations to ruin has pulled away; he has gone forth from his place in order to render your^&#42;1^ land as an object of astonishment. Your own cities will fall in ruins so that there will be no inhabitant.

[NOTE]
====
. “Your,” fem. sing.
====

[[v24-4-8]]

^<<v24-4-8,8>>^ On this account gird on sackcloth, YOU people. Beat YOUR breasts and howl, because the burning anger of Jehovah has not turned back from us.

[[v24-4-9]]

^<<v24-4-9,9>>^ “And it must occur in that day,” is the utterance of Jehovah, “that the heart of the king will perish, also the heart of the princes; and the priests will certainly be driven to astonishment, and the prophets themselves will be amazed.”

[[v24-4-10]]

^<<v24-4-10,10>>^ And I proceeded to say: “Alas, O Sovereign Lord Jehovah! Truly you have absolutely deceived this people and Jerusalem, saying, ‘Peace itself will become YOURS,’ and the sword has reached clear to the soul.”^&#42;1^

[NOTE]
====
. “The soul.” Heb., han·naʹphesh; Gr., psy·khesʹ; Lat., aʹni·mam. See App 4A.
====

[[v24-4-11]]

^<<v24-4-11,11>>^ At that time it will be said to this people and to Jerusalem: “There is a searing wind of the beaten paths through the wilderness &#91;on&#93; the way to the daughter of my people; it is not for winnowing, nor for cleansing.

[[v24-4-12]]

^<<v24-4-12,12>>^ The full wind itself comes even from these to me. Now I myself also shall speak forth the judgments with them.

[[v24-4-13]]

^<<v24-4-13,13>>^ Look! Like rain clouds he will come up, and his chariots are like a storm wind. His horses are swifter than eagles.^&#42;1^ Woe to us, because we have been despoiled!

[NOTE]
====
. Or, “vultures.”
====

[[v24-4-14]]

^<<v24-4-14,14>>^ Wash your heart clean of sheer badness, O Jerusalem, in order that you may be saved. How long will your erroneous thoughts lodge within you?

[[v24-4-15]]

^<<v24-4-15,15>>^ For a voice is telling from Dan and is publishing something hurtful from the mountainous region of Eʹphra·im.

[[v24-4-16]]

^<<v24-4-16,16>>^ Make mention &#91;of it&#93;, YOU people, yes, to the nations. Publish &#91;it&#93; against Jerusalem.”
“Watchers are coming from a land far away, and they will let out their voice against the very cities of Judah.

[[v24-4-17]]

^<<v24-4-17,17>>^ Like guards of the open field they have become against her on all sides, because she has rebelled even against me,” is the utterance of Jehovah.

[[v24-4-18]]

^<<v24-4-18,18>>^ “Your^&#42;1^ way and your dealings—there will be a rendering^&#42;2^ of these to you.^&#42;3^ This is the calamity upon you, for it is bitter; because it has reached clear to your heart.”

[NOTE]
====
. “Your,” fem. sing.
. “There will be a rendering.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. “Your way and your dealings have done these things to you,” in agreement with TLXXSyVg and some Heb. mss.
====

[[v24-4-19]]

^<<v24-4-19,19>>^ O my intestines, my intestines! I am in severe pains in the walls of my heart. My heart is boisterous within me. I cannot keep silent, for the sound of the horn is what my soul has heard, the alarm signal of war.

[[v24-4-20]]

^<<v24-4-20,20>>^ Crash upon crash is what has been called out, for the whole land has been despoiled. Suddenly my tents have been despoiled, in a moment my tent cloths.

[[v24-4-21]]

^<<v24-4-21,21>>^ How long shall I keep seeing the signal, keep hearing the sound of the horn?

[[v24-4-22]]

^<<v24-4-22,22>>^ For my people is foolish. Of me they have not taken note. They are unwise sons; and they are not those having understanding. Wise they are for doing bad, but for doing good they actually have no knowledge.

[[v24-4-23]]

^<<v24-4-23,23>>^ I saw the land,^&#42;1^ and, look! &#91;it was&#93; empty and waste; and into the heavens, and their light was no more.

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v24-4-24]]

^<<v24-4-24,24>>^ I saw the mountains, and, look! they were rocking, and the hills themselves were all given a shaking.

[[v24-4-25]]

^<<v24-4-25,25>>^ I saw, and, look! there was not an earthling man,^&#42;1^ and the flying creatures of the heavens had all fled.

[NOTE]
====
. “An earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v24-4-26]]

^<<v24-4-26,26>>^ I saw, and, look! the orchard itself was a wilderness, and the very cities of it had all been torn down. It was because of Jehovah, because of his burning anger.

[[v24-4-27]]

^<<v24-4-27,27>>^ For this is what Jehovah has said: “A desolate waste is what the whole land will become, and shall I not carry out a sheer extermination?^&#42;1^

[NOTE]
====
. Or, “but an extermination I shall not carry out.”
====

[[v24-4-28]]

^<<v24-4-28,28>>^ On this account the land will mourn, and the heavens above will certainly become dark. It is because I have spoken, I have considered, and I have not felt regret, nor shall I turn back from it.

[[v24-4-29]]

^<<v24-4-29,29>>^ Because of the sound of the horsemen and bow shooters the entire city is running away. They have entered into the thickets, and into the rocks^&#42;1^ they have gone up. Every city is left, and there is no man^&#42;2^ dwelling in them.”

[NOTE]
====
. “And into the rocks.” Heb., u·vak·ke·phimʹ; Gr., peʹtras. Compare Mt 16:18 ftn, “Rock-mass.”
. “Man.” Heb., ʼish.
====

[[v24-4-30]]

^<<v24-4-30,30>>^ Now that you^&#42;1^ are despoiled, what will you do, since you used to clothe yourself with scarlet, since you used to deck yourself with ornaments of gold, since you used to enlarge your eyes with black paint? It is in vain that you used to make yourself pretty. Those lusting after &#91;you&#93; have rejected you; they keep seeking for your very soul.

[NOTE]
====
. “You,” fem. sing., addressed to Zion, or Jerusalem.
====

[[v24-4-31]]

^<<v24-4-31,31>>^ For a voice like that of a sick woman^&#42;1^ I have heard, the distress like that of a woman giving birth to her first child, the voice of the daughter of Zion who keeps gasping for breath. She keeps spreading out her palms: “Woe, now, to me, for my soul is tired of the killers!”

[NOTE]
====
. “A woman having childbirth pains,” by a slight correction.
====

'''

xref:024-jeremiah/024-jeremiah-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremiah/024-jeremiah-005.adoc#v24-5-0[Próximo Capítulo &#62;]