include::./index.adoc[]

[[v24-52-0]]
=== Jeremiah, 52
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-52-1]]

^<<v24-52-1,1>>^ Zed·e·kiʹah was twenty-one years old when he began to reign, and for eleven years he reigned in Jerusalem. And the name of his mother was Ha·muʹtal the daughter of Jeremiah of Libʹnah.

[[v24-52-2]]

^<<v24-52-2,2>>^ And he continued to do what was bad in the eyes of Jehovah, according to all that Je·hoiʹa·kim had done.

[[v24-52-3]]

^<<v24-52-3,3>>^ For on account of the anger of Jehovah it occurred in Jerusalem and Judah, until he had cast them out from before his face. And Zed·e·kiʹah proceeded to rebel against the king of Babylon.

[[v24-52-4]]

^<<v24-52-4,4>>^ Finally it came about in the ninth year of his being king, in the tenth month, on the tenth day of the month, that Neb·u·chad·rezʹzar the king of Babylon came, he and all his military force, against Jerusalem, and they began to camp against her and to build against her a siege wall all around.

[[v24-52-5]]

^<<v24-52-5,5>>^ So the city came under siege until the eleventh year of King Zed·e·kiʹah.

[[v24-52-6]]

^<<v24-52-6,6>>^ In the fourth month, on the ninth day of the month, the famine also got to be severe in the city and there proved to be no bread for the people of the land.^&#42;1^

[NOTE]
====
. “For the people of the land.” Heb., leʽamʹ ha·ʼaʹrets.
====

[[v24-52-7]]

^<<v24-52-7,7>>^ Finally the city was broken through; and as regards all the men of war, they began to run away and go forth from the city by night by the way of the gate between the double wall that is by the king’s garden, while the Chal·deʹans were all around against the city; and they kept going by the way of the Arʹa·bah.

[[v24-52-8]]

^<<v24-52-8,8>>^ And a military force of the Chal·deʹans went chasing after the king, and they got to overtake Zed·e·kiʹah in the desert plains of Jerʹi·cho; and all his own military force was scattered from his side.

[[v24-52-9]]

^<<v24-52-9,9>>^ Then they seized the king and brought him up to the king of Babylon at Ribʹlah in the land of Haʹmath, that he might pronounce upon him judicial decisions.

[[v24-52-10]]

^<<v24-52-10,10>>^ And the king of Babylon proceeded to slaughter the sons of Zed·e·kiʹah before his eyes, and also all the princes of Judah he slaughtered in Ribʹlah.

[[v24-52-11]]

^<<v24-52-11,11>>^ And the eyes of Zed·e·kiʹah he blinded, after which the king of Babylon bound him with copper fetters and brought him to Babylon and put him in the house of custody until the day of his death.

[[v24-52-12]]

^<<v24-52-12,12>>^ And in the fifth month, on the tenth day of the month, that is, &#91;in&#93; the nineteenth year of King Neb·u·chad·rezʹzar, the king of Babylon, Neb·uʹzar·adʹan the chief of the bodyguard, who was standing before the king of Babylon, came into Jerusalem.

[[v24-52-13]]

^<<v24-52-13,13>>^ And he proceeded to burn the house of Jehovah and the house of the king and all the houses of Jerusalem; and every great house he burned with fire.

[[v24-52-14]]

^<<v24-52-14,14>>^ And all the walls of Jerusalem, round about, all the military forces of the Chal·deʹans that were with the chief of the bodyguard pulled down.

[[v24-52-15]]

^<<v24-52-15,15>>^ And some of the lowly ones of the people and the rest of the people that were left remaining in the city and the deserters that had fallen away to the king of Babylon and the rest of the master workmen Neb·uʹzar·adʹan the chief of the bodyguard took into exile.

[[v24-52-16]]

^<<v24-52-16,16>>^ And some of the lowly ones of the land Neb·uʹzar·adʹan the chief of the bodyguard let remain as vinedressers and as compulsory laborers.

[[v24-52-17]]

^<<v24-52-17,17>>^ And the copper pillars that belonged to the house of Jehovah and the carriages and the copper sea that was in the house of Jehovah the Chal·deʹans broke to pieces and went carrying all the copper of them to Babylon.

[[v24-52-18]]

^<<v24-52-18,18>>^ And the cans and the shovels and the extinguishers and the bowls and the cups and all the copper utensils with which they used to minister they took.

[[v24-52-19]]

^<<v24-52-19,19>>^ And the basins and the fire holders and the bowls and the cans and the lampstands and the cups and the bowls that were of genuine gold, and those that were of genuine silver, the chief of the bodyguard took.

[[v24-52-20]]

^<<v24-52-20,20>>^ And the two pillars, the one sea, and the twelve copper bulls that were under &#91;the sea&#93;, the carriages,^&#42;1^ that King Solʹo·mon had made for the house of Jehovah. There happened to be no weight &#91;taken&#93; of the copper of them—all these articles.

[NOTE]
====
. “Under [the sea], the carriages,” MTVg; LXX, “under the sea”; Sy, “under the sides of the sea.”
====

[[v24-52-21]]

^<<v24-52-21,21>>^ And as regards the pillars, eighteen cubits^&#42;1^ in height was each pillar, and a thread of twelve cubits itself would go around it; and its thickness was four fingerbreadths,^&#42;2^ it being hollow.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.).
. A fingerbreadth equaled 1.85 cm (0.72 in.).
====

[[v24-52-22]]

^<<v24-52-22,22>>^ And the capital upon it was of copper, and the height of the one capital was five cubits; and as regards the network and the pomegranates upon the capital, all around, the whole was of copper; and the second pillar had just the same as these, also the pomegranates.

[[v24-52-23]]

^<<v24-52-23,23>>^ And the pomegranates came to be ninety-six, on the sides,^&#42;1^ all the pomegranates being one hundred upon the network round about.

[NOTE]
====
. Lit., “windward.”
====

[[v24-52-24]]

^<<v24-52-24,24>>^ Furthermore, the chief of the bodyguard took Se·raiʹah the chief priest and Zeph·a·niʹah the second priest and the three doorkeepers,

[[v24-52-25]]

^<<v24-52-25,25>>^ and from the city he took one court official that happened to be commissioner over the men of war, and seven men of those having access to the king,^&#42;1^ who were found in the city, and the secretary of the chief of the army, the one mustering the people of the land,^&#42;2^ and sixty men^&#42;3^ of the people of the land, who were found in the midst of the city.

[NOTE]
====
. Lit., “from those seeing the king’s face.”
. “The people of the land.” Heb., ʽam ha·ʼaʹrets.
. “Men.” Heb., ʼish.
====

[[v24-52-26]]

^<<v24-52-26,26>>^ So these Neb·uʹzar·adʹan the chief of the bodyguard took and conducted them to the king of Babylon at Ribʹlah.

[[v24-52-27]]

^<<v24-52-27,27>>^ And these the king of Babylon proceeded to strike down and to put them to death in Ribʹlah in the land of Haʹmath. Thus Judah went into exile from off its soil.

[[v24-52-28]]

^<<v24-52-28,28>>^ These are the people whom Neb·u·chad·rezʹzar took into exile: in the seventh year, three thousand and twenty-three Jews.

[[v24-52-29]]

^<<v24-52-29,29>>^ In the eighteenth year of Neb·u·chad·rezʹzar, from Jerusalem there were eight hundred and thirty-two souls.

[[v24-52-30]]

^<<v24-52-30,30>>^ In the twenty-third year of Neb·u·chad·rezʹzar, Neb·uʹzar·adʹan the chief of the bodyguard took Jews into exile, seven hundred and forty-five souls.
All the souls were four thousand and six hundred.^&#42;1^

[NOTE]
====
. LXX and 2Ki 25 omit the contents of vss 28-30.
====

[[v24-52-31]]

^<<v24-52-31,31>>^ At length it came about in the thirty-seventh year of the exile of Je·hoiʹa·chin the king of Judah, in the twelfth month, on the twenty-fifth day of the month, that Eʹvil-merʹo·dach the king of Babylon, in the year of his becoming king,^&#42;1^ raised up the head of Je·hoiʹa·chin the king of Judah and proceeded to bring him forth from the prison house.

[NOTE]
====
. Lit., “his kingship.” Heb., mal·khu·thohʹ.
====

[[v24-52-32]]

^<<v24-52-32,32>>^ And he began to speak with him good things and to put his throne^&#42;1^ higher than the thrones of the &#91;other&#93; kings that were with him in Babylon.

[NOTE]
====
. Or, “seat.”
====

[[v24-52-33]]

^<<v24-52-33,33>>^ And he took off^&#42;1^ his prison garments, and he ate bread before him constantly all the days of his life.

[NOTE]
====
. Lit., “he changed.”
====

[[v24-52-34]]

^<<v24-52-34,34>>^ And as for his allowance, there was a constant allowance given him from the king of Babylon, daily as due,^&#42;1^ until the day of his death, all the days of his life.

[NOTE]
====
. Lit., “a thing of a day on its day.”
====

'''

xref:024-jeremiah/024-jeremiah-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentations/025-lamentations-001.adoc#v25-1-0[Próximo Capítulo &#62;]