include::./index.adoc[]

[[v24-42-0]]
=== Jeremiah, 42
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-42-1]]

^<<v24-42-1,1>>^ Then all the chiefs of the military forces and Jo·haʹnan the son of Ka·reʹah and Jez·a·niʹah^&#42;1^ the son of Ho·shaiʹah and all the people, from the smallest one even to the greatest one, approached

[NOTE]
====
. “Jezaniah,” MTSyVg; LXX, “Azariah,” as in 43:2.
====

[[v24-42-2]]

^<<v24-42-2,2>>^ and said to Jeremiah the prophet: “May our request for favor, please, fall before you, and do you pray in our behalf to Jehovah your God, in behalf of all this remnant, for we have been left remaining, a few out of many, just as your eyes are seeing us.

[[v24-42-3]]

^<<v24-42-3,3>>^ And may Jehovah your God tell us the way in which we should walk and the thing that we should do.”

[[v24-42-4]]

^<<v24-42-4,4>>^ At that Jeremiah the prophet said to them: “I have heard. Here I am praying to Jehovah YOUR God according to YOUR words; and it will certainly occur that every word that Jehovah gives in answer to YOU I shall tell YOU. I shall not hold back from YOU a word.”

[[v24-42-5]]

^<<v24-42-5,5>>^ And they, for their part, said to Jeremiah: “May Jehovah prove to be a true and faithful witness against us if it is not according to every word with which Jehovah your God sends you to us that we shall exactly do.

[[v24-42-6]]

^<<v24-42-6,6>>^ Whether good or bad, it is the voice of Jehovah our God to whom we are sending you that we shall obey, to the intent that it may go well with us because we obey the voice of Jehovah our God.”

[[v24-42-7]]

^<<v24-42-7,7>>^ Now it came about at the end of ten days that the word of Jehovah proceeded to occur to Jeremiah.

[[v24-42-8]]

^<<v24-42-8,8>>^ So he called for Jo·haʹnan the son of Ka·reʹah and for all the chiefs of the military forces who were with him and for all the people, from the smallest one even to the greatest one;

[[v24-42-9]]

^<<v24-42-9,9>>^ and he went on to say to them: “This is what Jehovah the God of Israel, to whom YOU sent me to cause your request for favor to fall before him, has said,

[[v24-42-10]]

^<<v24-42-10,10>>^ ‘If YOU will without fail keep dwelling in this land, I will also build YOU up and I shall not tear &#91;YOU&#93; down, and I will plant YOU and I shall not uproot &#91;YOU&#93;; for I shall certainly feel regret over the calamity that I have caused to YOU.

[[v24-42-11]]

^<<v24-42-11,11>>^ Do not be afraid because of the king of Babylon, of whom YOU are in fear.’
“‘Do not be afraid because of him,’ is the utterance of Jehovah, ‘for I am with YOU, in order to save YOU and to deliver YOU out of his hand.

[[v24-42-12]]

^<<v24-42-12,12>>^ And I shall give to YOU mercies, and he will certainly have mercy upon YOU and return YOU to YOUR own soil.

[[v24-42-13]]

^<<v24-42-13,13>>^ “‘But if YOU are saying: “No; we are not going to dwell in this land!” in order to disobey the voice of Jehovah YOUR God,

[[v24-42-14]]

^<<v24-42-14,14>>^ saying: “No, but into the land of Egypt we shall enter, where we shall see no war and the sound of the horn we shall not hear and for bread we shall not go hungry; and there is where we shall dwell”;

[[v24-42-15]]

^<<v24-42-15,15>>^ even now therefore hear the word of Jehovah, O remnant of Judah. This is what Jehovah of armies, the God of Israel, has said: “If YOU yourselves positively set YOUR faces to enter into Egypt and YOU actually enter in to reside there as aliens,

[[v24-42-16]]

^<<v24-42-16,16>>^ it must also occur that the very sword of which YOU are afraid will there catch up with YOU in the land of Egypt, and the very famine at which YOU are in a fright will there closely follow after YOU to Egypt; and there is where YOU will die.

[[v24-42-17]]

^<<v24-42-17,17>>^ And it will come about that all the men that have set their faces to enter into Egypt to reside there as aliens will be the ones to die by the sword, by the famine and by the pestilence; and they will not come to have a survivor or an escapee, because of the calamity that I am bringing in upon them.”’

[[v24-42-18]]

^<<v24-42-18,18>>^ “For this is what Jehovah of armies, the God of Israel, has said, ‘Just as my anger and my rage have been poured out upon the inhabitants of Jerusalem, so my rage will be poured out upon YOU because of YOUR entering into Egypt, and YOU will certainly become a curse and an object of astonishment and a malediction and a reproach, and you will no more see this place.’

[[v24-42-19]]

^<<v24-42-19,19>>^ “Jehovah has spoken against YOU, O remnant of Judah. Do not enter into Egypt. YOU should positively know that I have borne witness against YOU today,

[[v24-42-20]]

^<<v24-42-20,20>>^ that YOU have committed error against YOUR souls;^&#42;1^ for YOU yourselves have sent me to Jehovah YOUR God, saying, ‘Pray in our behalf to Jehovah our God; and according to everything that Jehovah our God says tell us that way, and we shall certainly do.’

[NOTE]
====
. “Against your souls.” Heb., benaph·shoh·theh·khemʹ; Gr., psy·khaisʹ; Lat., aʹni·mas. See App 4A.
====

[[v24-42-21]]

^<<v24-42-21,21>>^ And I tell YOU today, but YOU will certainly not obey the voice of Jehovah YOUR God or anything with which he has sent me to YOU.

[[v24-42-22]]

^<<v24-42-22,22>>^ And now YOU should positively know that by the sword, by the famine and by the pestilence YOU will die in the place into which YOU do delight to enter to reside as aliens.”

'''

xref:024-jeremiah/024-jeremiah-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremiah/024-jeremiah-043.adoc#v24-43-0[Próximo Capítulo &#62;]