include::./index.adoc[]

[[v24-12-0]]
=== Jeremiah, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-12-1]]

^<<v24-12-1,1>>^ You are righteous, O Jehovah, when I make my complaint to you, indeed when I speak even about matters of judgment with you. Why is it that the way of wicked ones is what has succeeded, that all those who are committing treachery are the unworried ones?

[[v24-12-2]]

^<<v24-12-2,2>>^ You have planted them; they have also taken root. They keep going ahead; they have also produced fruit. You are near in their mouth, but far away from their kidneys.^&#42;1^

[NOTE]
====
. See 11:20 ftn.
====

[[v24-12-3]]

^<<v24-12-3,3>>^ And you yourself, O Jehovah, know me well; you see me, and you have examined my heart in union with yourself. Single them out like sheep for the slaughtering, and set them apart^&#42;1^ for the day of killing.

[NOTE]
====
. Or, “sanctify them.”
====

[[v24-12-4]]

^<<v24-12-4,4>>^ How long should the land keep withering away, and the very vegetation of all the field dry up? Because of the badness of those dwelling in it the beasts and the flying creatures have been swept away. For they have said: “He does not see our future.”

[[v24-12-5]]

^<<v24-12-5,5>>^ Because with footmen you have run, and they would tire you out, how, then, can you run a race with horses? And in the land of peace are you confident?^&#42;1^ So how will you act among the proud &#91;thickets&#93; along the Jordan?

[NOTE]
====
. Or, “you are confident (trusting).” LXXא,B, “you are not confident.”
====

[[v24-12-6]]

^<<v24-12-6,6>>^ For even your own brothers and the household of your own father, even they themselves have dealt treacherously with you. Even they themselves have called out loudly behind you. Do not put any faith in them, just because they speak to you good things.

[[v24-12-7]]

^<<v24-12-7,7>>^ “I have left my house; I have deserted my inheritance; I have given the beloved one of my soul into the palm of her enemies.

[[v24-12-8]]

^<<v24-12-8,8>>^ My inheritance has become to me like a lion in the forest. She has let loose her voice even against me. That is why I have hated her.

[[v24-12-9]]

^<<v24-12-9,9>>^ My inheritance is as a many-colored bird of prey to me; the birds of prey are round about upon it. Come, gather together, all YOU wild beasts of the field; bring &#91;them&#93; to eat.

[[v24-12-10]]

^<<v24-12-10,10>>^ Many shepherds themselves have brought my vineyard to ruin; they have stamped down my share. They have turned my desirable share into a wilderness of a desolate waste.

[[v24-12-11]]

^<<v24-12-11,11>>^ One has made it a desolate waste; it has withered away;^&#42;1^ it is desolated to me. The whole land has been made desolate, because there is no man^&#42;2^ that has taken &#91;it&#93; to heart.

[NOTE]
====
. Or, “has mourned.”
. “Man.” Heb., ʼish.
====

[[v24-12-12]]

^<<v24-12-12,12>>^ On all the beaten paths through the wilderness the despoilers have come. For the sword belonging to Jehovah is devouring from one end of the land even to the other end of the land. There is no peace for any flesh.

[[v24-12-13]]

^<<v24-12-13,13>>^ They have sown wheat, but thorns are what they have reaped. They have worked themselves sick; they will be of no benefit. And they will certainly be^&#42;1^ ashamed of the products of YOU people because of the burning anger of Jehovah.”

[NOTE]
====
. Or, “And be,” imperative pl.
====

[[v24-12-14]]

^<<v24-12-14,14>>^ This is what Jehovah has said against all my bad neighbors,^&#42;1^ who are touching the hereditary possession that I caused my people, even Israel, to possess: “Here I am uprooting them from off their ground; and the house of Judah I shall uproot from the midst of them.

[NOTE]
====
. “Neighbors,” evidently neighbor nations, or peoples.
====

[[v24-12-15]]

^<<v24-12-15,15>>^ And it must occur that after my uprooting them I shall again certainly have mercy upon them and will bring them back, each one to his hereditary possession and each one to his land.”

[[v24-12-16]]

^<<v24-12-16,16>>^ “And it must occur that if they will without fail learn the ways of my people in swearing by my name, ‘As Jehovah is alive!’ just as they taught my people to swear by Baʹal, they will also be built up in the midst of my people.

[[v24-12-17]]

^<<v24-12-17,17>>^ But if they will not obey, I will also uproot that nation, uprooting and destroying &#91;it&#93;,” is the utterance of Jehovah.

'''

xref:024-jeremiah/024-jeremiah-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremiah/024-jeremiah-013.adoc#v24-13-0[Próximo Capítulo &#62;]