include::./index.adoc[]

[[v24-46-0]]
=== Jeremiah, 46
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-46-1]]

^<<v24-46-1,1>>^ This is what occurred as the word of Jehovah to Jeremiah the prophet concerning the nations:

[[v24-46-2]]

^<<v24-46-2,2>>^ For Egypt, concerning the military force of Pharʹaoh Neʹcho^&#42;1^ the king of Egypt, who happened to be by the river Eu·phraʹtes at Carʹche·mish, whom Neb·u·chad·rezʹzar the king of Babylon defeated in the fourth year of Je·hoiʹa·kim the son of Jo·siʹah, the king of Judah:

[NOTE]
====
. Or, “Nekaw (Nekau).” LXXVg, ­“Nechao.”
====

[[v24-46-3]]

^<<v24-46-3,3>>^ “Set in array, O men, buckler and large shield, and approach to battle.

[[v24-46-4]]

^<<v24-46-4,4>>^ Harness the horses, and mount, O YOU horsemen, and station yourselves with the helmet. Polish the lances. Clothe yourselves with coats of mail.

[[v24-46-5]]

^<<v24-46-5,5>>^ “‘Why is it that I have seen them terror-stricken? They are turning back, and their mighty men themselves are crushed to pieces; and they have positively fled, and they have not turned around. There is fright all around,’ is the utterance of Jehovah.

[[v24-46-6]]

^<<v24-46-6,6>>^ ‘Let not the swift one try to flee, and let not the mighty man try to escape. Up north by the bank of the river Eu·phraʹtes they have stumbled and fallen.’

[[v24-46-7]]

^<<v24-46-7,7>>^ “Who is this one that comes up just like the Nile River, like the rivers the waters of which toss themselves?

[[v24-46-8]]

^<<v24-46-8,8>>^ Egypt itself comes up just like the Nile River, and like rivers the waters toss themselves. And it says, ‘I shall go up. I shall cover the earth. I shall readily destroy the city and those inhabiting it.’

[[v24-46-9]]

^<<v24-46-9,9>>^ Go up, O YOU horses; and drive madly, O YOU chariots! And let the mighty men go forth, Cush^&#42;1^ and Put, who are handling the shield, and the Luʹdim, who are handling &#91;and&#93; treading the bow.

[NOTE]
====
. “Cush,” M; TSy, “Cushite men”; LXX, “warriors of the Ethiopians”; Vg, “Ethiopia.”
====

[[v24-46-10]]

^<<v24-46-10,10>>^ “And that day belongs to the Sovereign Lord, Jehovah of armies, the day of vengeance for avenging himself upon his adversaries. And the sword will certainly devour and satisfy itself and take its fill of their blood, for the Sovereign Lord, Jehovah of armies, has a sacrifice in the land of the north by the river Eu·phraʹtes.

[[v24-46-11]]

^<<v24-46-11,11>>^ “Go up to Gilʹe·ad and get some balsam, O virgin daughter of Egypt. In vain you have multiplied the means of healing. There is no mending for you.

[[v24-46-12]]

^<<v24-46-12,12>>^ The nations have heard your dishonor^&#42;1^ and your own outcry has filled the land.^&#42;2^ For they have stumbled, mighty man against mighty man. Together they have fallen down, both of them.”

[NOTE]
====
. “Dishonor,” MTSyVg; LXX, “voice.”
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v24-46-13]]

^<<v24-46-13,13>>^ The word that Jehovah spoke to Jeremiah the prophet as regards the coming of Neb·u·chad·rezʹzar the king of Babylon to strike down the land of Egypt:

[[v24-46-14]]

^<<v24-46-14,14>>^ “Tell &#91;it&#93; in Egypt, O men, and publish &#91;it&#93; in Migʹdol, and publish &#91;it&#93; in Noph^&#42;1^ and in Tahʹpan·hes. Say, ‘Station yourself, making preparation also for yourself, for a sword will certainly devour all around you.

[NOTE]
====
. “Noph,” M; T(Aram.), Ma·phehsʹ; LXXVg, “Memphis.”
====

[[v24-46-15]]

^<<v24-46-15,15>>^ Why is it that your powerful ones have been washed away? They have made no stand, for Jehovah himself has pushed them away.

[[v24-46-16]]

^<<v24-46-16,16>>^ In great numbers they are stumbling. They also actually fall. And they keep saying one to the other: “Do rise up, and do let us return to our people and to the land of our relatives because of the maltreating sword.”’

[[v24-46-17]]

^<<v24-46-17,17>>^ There they have proclaimed, ‘Pharʹaoh the king of Egypt is a mere noise. He has let the festal time pass by.’

[[v24-46-18]]

^<<v24-46-18,18>>^ “‘As I am alive,’ is the utterance of the King, whose name is Jehovah of armies, ‘like Taʹbor among the mountains and like Carʹmel by the sea he will come in.

[[v24-46-19]]

^<<v24-46-19,19>>^ Make for yourself mere baggage for exile, O inhabitress, the daughter of Egypt. For Noph itself will become a mere object of astonishment and will actually be set afire, so as to be without an inhabitant.

[[v24-46-20]]

^<<v24-46-20,20>>^ Egypt is as a very pretty heifer. From the north a mosquito itself will certainly come against her.^&#42;1^

[NOTE]
====
. “Against her,” TLXXSy and 100 Heb. mss.
====

[[v24-46-21]]

^<<v24-46-21,21>>^ Furthermore, her hired &#91;soldiers&#93; in the midst of her are like fattened calves. But they themselves also have given way; they have fled together. They have not made a stand. For the very day of their disaster has come in upon them, the time of their being given attention.’

[[v24-46-22]]

^<<v24-46-22,22>>^ “‘Her voice is like that of a serpent that goes along; for with vital energy men will go, and with axes they will actually come in to her, like those who are gathering^&#42;1^ pieces of wood.

[NOTE]
====
. Or, “cutting.”
====

[[v24-46-23]]

^<<v24-46-23,23>>^ They will certainly cut down her forest,’ is the utterance of Jehovah, ‘for it could not be penetrated. For they have become more numerous than the locust, and they are without number.

[[v24-46-24]]

^<<v24-46-24,24>>^ The daughter of Egypt will certainly feel shame. She will actually be given into the hand of the people of the north.’

[[v24-46-25]]

^<<v24-46-25,25>>^ “Jehovah of armies, the God of Israel, has said, ‘Here I am turning my attention upon Aʹmon^&#42;1^ from No^&#42;2^ and upon Pharʹaoh and upon Egypt and upon her gods and upon her kings, even upon Pharʹaoh and upon all those trusting in him.’

[NOTE]
====
. Or, “Amen.” M, ʼA·mohnʹ, an Egyptian word.
. “From No,” M; TVg, “of Alexandria”; LXX, “her son”; Sy, “of the waters.” Also known as Thebes.
====

[[v24-46-26]]

^<<v24-46-26,26>>^ “‘And I will give them into the hand of those seeking for their soul^&#42;1^ and into the hand of Neb·u·chad·rezʹzar the king of Babylon and into the hand of his servants; and afterward she will be resided in as in the days of old,’ is the utterance of Jehovah.

[NOTE]
====
. “Their soul.” Heb., naph·shamʹ; Lat., aʹni·mam. See App 4A.
====

[[v24-46-27]]

^<<v24-46-27,27>>^ “‘And as for you, do not be afraid, O my servant Jacob, and do not be terror-stricken, O Israel. For here I am saving you from far away and your offspring from the land of their captivity. And Jacob will certainly return and have no disturbance and be at ease and without anyone causing trembling.

[[v24-46-28]]

^<<v24-46-28,28>>^ As for you, do not be afraid, O my servant Jacob,’ is the utterance of Jehovah, ‘for I am with you. For I shall make an extermination among all the nations to which I have dispersed you, but with you I shall make no extermination. Yet I shall have to chastise you to the proper degree, and I shall absolutely not leave you unpunished.’”

'''

xref:024-jeremiah/024-jeremiah-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremiah/024-jeremiah-047.adoc#v24-47-0[Próximo Capítulo &#62;]