include::./index.adoc[]

[[v24-44-0]]
=== Jeremiah, 44
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-44-1]]

^<<v24-44-1,1>>^ The word that occurred to Jeremiah for all the Jews that were dwelling in the land of Egypt, the ones dwelling in Migʹdol and in Tahʹpan·hes and in Noph^&#42;1^ and in the land of Pathʹros, saying:

[NOTE]
====
. “Noph,” M; TSy, “Maphas (Memphis)”; Vg, “Memphis.”
====

[[v24-44-2]]

^<<v24-44-2,2>>^ “This is what Jehovah of armies, the God of Israel, has said, ‘YOU yourselves have seen all the calamity that I have brought in upon Jerusalem and upon all the cities of Judah, and here they are a devastated place this day, and in them there is no inhabitant.

[[v24-44-3]]

^<<v24-44-3,3>>^ It is because of their badness that they did in order to offend me by going and making sacrificial smoke and rendering service to other gods whom they themselves had not known, neither YOU nor YOUR forefathers.

[[v24-44-4]]

^<<v24-44-4,4>>^ And I kept sending to YOU all my servants the prophets, rising up early and sending, saying: “Do not do, please, this detestable sort of thing that I have hated.”

[[v24-44-5]]

^<<v24-44-5,5>>^ But they did not listen, nor did they incline their ear to turn back from their badness by not making sacrificial smoke to other gods.

[[v24-44-6]]

^<<v24-44-6,6>>^ So my rage, and my anger, was poured out and it burned in the cities of Judah and in the streets of Jerusalem; and they came to be a devastated place, a desolate waste, as at this day.’

[[v24-44-7]]

^<<v24-44-7,7>>^ “And now this is what Jehovah, the God of armies, the God of Israel, has said, ‘Why are YOU causing a great calamity to YOUR souls, in order to cut off from yourselves man and woman, child and suckling, out of the midst of Judah, so that YOU do not leave over for yourselves a remnant;

[[v24-44-8]]

^<<v24-44-8,8>>^ by offending me with the works of YOUR hands by making sacrificial smoke to other gods in the land of Egypt, into which YOU are entering to reside as aliens; for the purpose of causing a cutting off of yourselves and for the purpose of YOUR becoming a malediction and a reproach among all the nations of the earth?

[[v24-44-9]]

^<<v24-44-9,9>>^ Have YOU forgotten the bad deeds of YOUR forefathers and the bad deeds of the kings of Judah and the bad deeds of their wives and YOUR own bad deeds and the bad deeds of YOUR wives, that they have done in the land of Judah and in the streets of Jerusalem?

[[v24-44-10]]

^<<v24-44-10,10>>^ And down to this day they did not feel crushed, and they did not become afraid, nor did they walk in my law and in my statutes that I put before YOU and before YOUR forefathers.’

[[v24-44-11]]

^<<v24-44-11,11>>^ “Therefore this is what Jehovah of armies, the God of Israel, has said, ‘Here I am setting my face against YOU for calamity and for cutting off all Judah.

[[v24-44-12]]

^<<v24-44-12,12>>^ And I will take the remnant of Judah who set their faces to enter into the land of Egypt to reside there as aliens, and they will all certainly come to their finish in the land of Egypt. They will fall by the sword; &#91;and&#93; by the famine they will come to their finish, from the smallest one even to the greatest one; by the sword and by the famine they will die. And they must become a curse, an object of astonishment and a malediction and a reproach.

[[v24-44-13]]

^<<v24-44-13,13>>^ And I will hold an accounting against those dwelling in the land of Egypt, just as I held an accounting against Jerusalem, with the sword, with the famine and with the pestilence.

[[v24-44-14]]

^<<v24-44-14,14>>^ And there will come to be no escapee or survivor for the remnant of Judah who are entering in to reside there as aliens, in the land of Egypt, even to return to the land of Judah to which they are lifting up their soul&#91;ful desire&#93; to return in order to dwell; for they will not return, except some escaped ones.’”

[[v24-44-15]]

^<<v24-44-15,15>>^ And all the men who were knowing that their wives had been making sacrificial smoke to other gods,^&#42;1^ and all the wives who were standing as a great congregation, and all the people who were dwelling in the land of Egypt, in Pathʹros, proceeded to answer Jeremiah, saying:

[NOTE]
====
. “To . . . gods.” Heb., leʼ·lo·himʹ.
====

[[v24-44-16]]

^<<v24-44-16,16>>^ “As regards the word that you have spoken to us in the name of Jehovah, we are not listening to you;

[[v24-44-17]]

^<<v24-44-17,17>>^ but we shall positively do every word that has gone forth from our mouth, in order to make sacrificial smoke to the ‘queen of the heavens’^&#42;1^ and to pour^&#42;2^ out to her drink offerings, just as we ourselves and our forefathers, our kings and our princes did in the cities of Judah and in the streets of Jerusalem, when we used to be satisfied with bread and to be well off, and we did not see any calamity at all.

[NOTE]
====
. “To the work (worship) of the heavens,” about 30 Heb. mss. Compare 7:18 ftn, “Queen.”
. Lit., “there will be a pouring.” In Heb. this is a verb in the infinitive absolute.
====

[[v24-44-18]]

^<<v24-44-18,18>>^ And from the time that we ceased to make sacrificial smoke to the ‘queen of the heavens’ and pour out drink offerings to her we have lacked everything, and by the sword and by the famine we have come to our finish.

[[v24-44-19]]

^<<v24-44-19,19>>^ “Also, when^&#42;1^ we were making sacrificial smoke to the ‘queen of the heavens’ and &#91;were disposed&#93; to pour out drink offerings to her, did we without asking our husbands make for her sacrificial cakes, in order to make an image of her, and to pour out drink offerings to her?”

[NOTE]
====
. “Also, when,” M; Sy, “And all the women answered and said, ‘When.’ ”
====

[[v24-44-20]]

^<<v24-44-20,20>>^ In turn Jeremiah said to all the people, to the able-bodied men and to the wives and to all the people, who were answering him with a word, saying:

[[v24-44-21]]

^<<v24-44-21,21>>^ “As for the sacrificial smoke that YOU made in the cities of Judah and in the streets of Jerusalem, YOU and YOUR forefathers, YOUR kings and YOUR princes and the people of the land,^&#42;1^ was it not this that Jehovah remembered and that proceeded to come up into his heart?

[NOTE]
====
. “And the people of the land.” Heb., weʽamʹ ha·ʼaʹrets.
====

[[v24-44-22]]

^<<v24-44-22,22>>^ Finally Jehovah was no longer able to put up with it because of the badness of YOUR dealings, because of the detestable things that YOU had done, and so YOUR land came to be a devastated place and an object of astonishment and a malediction, without an inhabitant, as at this day.

[[v24-44-23]]

^<<v24-44-23,23>>^ Because of the fact that YOU made sacrificial smoke and that YOU sinned against Jehovah and did not obey the voice of Jehovah and in his law and in his statutes and in his reminders YOU did not walk, that is why there has befallen YOU this calamity as at this day.”

[[v24-44-24]]

^<<v24-44-24,24>>^ And Jeremiah continued on to say to all the people and to all the women: “Hear the word of Jehovah, all Judah who are in the land of Egypt.

[[v24-44-25]]

^<<v24-44-25,25>>^ This is what Jehovah of armies, the God of Israel, has said, ‘As for YOU men and YOUR wives, YOU women also speak with YOUR mouths, (and with YOUR hands YOU people have made a fulfillment,) saying: “We shall without fail perform our vows that we have vowed, to make sacrificial smoke to the ‘queen of the heavens’ and to pour out drink offerings to her.” YOU women will without fail carry out YOUR vows, and YOU will without fail perform YOUR vows.’

[[v24-44-26]]

^<<v24-44-26,26>>^ “Therefore hear the word of Jehovah, all Judah who are dwelling in the land of Egypt, ‘“Here I myself have sworn by my great name,” Jehovah has said, “that my name will no more prove to be something called out by the mouth of any man^&#42;1^ of Judah, saying, ‘As the Sovereign Lord Jehovah is alive!’ in all the land of Egypt.

[NOTE]
====
. Or, “every man of.” Heb., kol-ʼishʹ.
====

[[v24-44-27]]

^<<v24-44-27,27>>^ Here I am keeping alert toward them for calamity and not for good; and all the men of Judah that are in the land of Egypt will certainly come to their finish by the sword and by the famine, until they cease to be.

[[v24-44-28]]

^<<v24-44-28,28>>^ And as for the ones escaping from the sword, they will return from the land of Egypt to the land of Judah, few in number; and all those of the remnant of Judah, who are coming into the land of Egypt to reside there as aliens, will certainly know whose word comes true, that from me or that from them.”’”

[[v24-44-29]]

^<<v24-44-29,29>>^ “‘And this is the sign for YOU,’ is the utterance of Jehovah, ‘that I am turning my attention upon YOU in this place, in order that YOU may know that my words will without fail come true upon YOU for calamity:

[[v24-44-30]]

^<<v24-44-30,30>>^ This is what Jehovah has said: “Here I am giving Pharʹaoh Hophʹra, the king of Egypt, into the hand of his enemies and into the hand of those seeking for his soul, just as I have given Zed·e·kiʹah the king of Judah into the hand of Neb·u·chad·rezʹzar the king of Babylon, his enemy and the one seeking for his soul.”’”

'''

xref:024-jeremiah/024-jeremiah-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremiah/024-jeremiah-045.adoc#v24-45-0[Próximo Capítulo &#62;]