include::./index.adoc[]

[[v24-28-0]]
=== Jeremiah, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-28-1]]

^<<v24-28-1,1>>^ Then it came about in that year, in the beginning of the kingdom of Zed·e·kiʹah^&#42;1^ the king of Judah, in the fourth year, in the fifth month, that Han·a·niʹah the son of Azʹzur, the prophet who was from Gibʹe·on, said to me in the house of Jehovah before the eyes of the priests and of all the people:

[NOTE]
====
. See 27:12 ftn.
====

[[v24-28-2]]

^<<v24-28-2,2>>^ “This is what Jehovah of armies, the God of Israel, has said, ‘I will break the yoke of the king of Babylon.

[[v24-28-3]]

^<<v24-28-3,3>>^ Within two full years more I am bringing back to this place all the utensils of the house of Jehovah that Neb·u·chad·nezʹzar the king of Babylon took from this place that he might bring them to Babylon.’”

[[v24-28-4]]

^<<v24-28-4,4>>^ “‘And Jec·o·niʹah the son of Je·hoiʹa·kim, the king of Judah, and all the exiles of Judah who have come to Babylon I am bringing back to this place,’ is the utterance of Jehovah, ‘for I shall break the yoke of the king of Babylon.’”

[[v24-28-5]]

^<<v24-28-5,5>>^ And Jeremiah the prophet proceeded to say to Han·a·niʹah the prophet before the eyes of the priests and before the eyes of all the people who were standing in the house of Jehovah;

[[v24-28-6]]

^<<v24-28-6,6>>^ yes, Jeremiah the prophet proceeded to say: “Amen!^&#42;1^ Thus may Jehovah do! May Jehovah establish your words that you have prophesied by bringing back the utensils of the house of Jehovah and all the exiled people from Babylon to this place!

[NOTE]
====
. Or, “So be it!” Heb., ʼa·menʹ.
====

[[v24-28-7]]

^<<v24-28-7,7>>^ However, hear, please, this word that I am speaking in your ears and in the ears of all the people.

[[v24-28-8]]

^<<v24-28-8,8>>^ As regards the prophets that happened to be prior to me and prior to you from long ago, they also used to prophesy concerning many lands and concerning great kingdoms, of war and of calamity^&#42;1^ and of pestilence.

[NOTE]
====
. “Calamity,” MTSyVg; 23 Heb. mss, “famine.”
====

[[v24-28-9]]

^<<v24-28-9,9>>^ As regards the prophet that prophesies of peace, when the word of the prophet comes true the prophet whom Jehovah has sent in truth will become known.”

[[v24-28-10]]

^<<v24-28-10,10>>^ At that Han·a·niʹah the prophet took the yoke bar from off the neck of Jeremiah the prophet and broke it.

[[v24-28-11]]

^<<v24-28-11,11>>^ And Han·a·niʹah went on to say before the eyes of all the people: “This is what Jehovah has said, ‘Just like this I shall break the yoke of Neb·u·chad·nezʹzar the king of Babylon within two full years more from off the neck of all the nations.’” And Jeremiah the prophet proceeded to go his way.

[[v24-28-12]]

^<<v24-28-12,12>>^ Then the word of Jehovah occurred to Jeremiah, after Han·a·niʹah the prophet had broken the yoke bar from off the neck of Jeremiah the prophet, saying:

[[v24-28-13]]

^<<v24-28-13,13>>^ “Go,^&#42;1^ and you must say to Han·a·niʹah, ‘This is what Jehovah has said: “Yoke bars of wood you have broken, and instead of them you will have to make yoke bars of iron.”

[NOTE]
====
. See 2:2 ftn, “Go.”
====

[[v24-28-14]]

^<<v24-28-14,14>>^ For this is what Jehovah of armies, the God of Israel, has said: “A yoke of iron I will put upon the neck of all these nations, to serve Neb·u·chad·nezʹzar the king of Babylon; and they must serve him. And even the wild beasts of the field I will give him.”’”

[[v24-28-15]]

^<<v24-28-15,15>>^ And Jeremiah the prophet went on to say to Han·a·niʹah the prophet: “Listen, please, O Han·a·niʹah! Jehovah has not sent you, but you yourself have caused this people to trust in a falsehood.

[[v24-28-16]]

^<<v24-28-16,16>>^ Therefore this is what Jehovah has said, ‘Look! I am sending you away from off the surface of the ground. This year you yourself must die, for you have spoken outright revolt against Jehovah.’”

[[v24-28-17]]

^<<v24-28-17,17>>^ So Han·a·niʹah the prophet died in that year, in the seventh month.

'''

xref:024-jeremiah/024-jeremiah-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremiah/024-jeremiah-029.adoc#v24-29-0[Próximo Capítulo &#62;]