include::./index.adoc[]

[[v24-33-0]]
=== Jeremiah, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v24-33-1]]

^<<v24-33-1,1>>^ And the word of Jehovah proceeded to occur to Jeremiah the second time, while he was yet shut up in the Courtyard of the Guard, saying:

[[v24-33-2]]

^<<v24-33-2,2>>^ “This is what Jehovah the Maker of &#91;earth&#93;^&#42;1^ has said, Jehovah the Former of it to establish it firmly, Jehovah being his name,

[NOTE]
====
. Lit., “it,” fem.
====

[[v24-33-3]]

^<<v24-33-3,3>>^ ‘Call to me, and I shall answer you^&#42;1^ and readily tell you great and incomprehensible things that you have not known.’”

[NOTE]
====
. “You,” masc. sing.
====

[[v24-33-4]]

^<<v24-33-4,4>>^ “For this is what Jehovah the God of Israel has said concerning the houses of this city and concerning the houses of the kings of Judah that are pulled down on account of the siege ramparts and on account of the sword;

[[v24-33-5]]

^<<v24-33-5,5>>^ &#91;concerning&#93; those who are coming to fight against the Chal·deʹans and to fill places with the carcasses of the men^&#42;1^ whom I have struck down in my anger and in my rage, and on account of all whose badness I have concealed my face from this city,

[NOTE]
====
. “The men.” Heb., ha·ʼa·dhamʹ.
====

[[v24-33-6]]

^<<v24-33-6,6>>^ ‘Here I am bringing up for her a recuperation and health; and I will heal them and reveal to them an abundance of peace and truth.

[[v24-33-7]]

^<<v24-33-7,7>>^ And I will bring back the captives of Judah and the captives of Israel, and I will build them just as at the start.

[[v24-33-8]]

^<<v24-33-8,8>>^ And I will purify them from all their error with which they have sinned against me, and I will forgive all their errors with which they have sinned against me and with which they have transgressed against me.

[[v24-33-9]]

^<<v24-33-9,9>>^ And she will certainly become to me a name of exultation, a praise and a beauty toward all the nations of the earth who will hear of all the goodness that I am rendering to them. And they will certainly be in dread and be agitated on account of all the goodness and on account of all the peace that I am rendering to her.’”

[[v24-33-10]]

^<<v24-33-10,10>>^ “This is what Jehovah has said, ‘In this place that YOU people will be saying is waste without man^&#42;1^ and without domestic animal, in the cities of Judah and in the streets of Jerusalem that are desolated without man and without inhabitant and without domestic animal, there will yet be heard

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
====

[[v24-33-11]]

^<<v24-33-11,11>>^ the sound of exultation and the sound of rejoicing, the voice of the bridegroom and the voice of the bride, the voice of those saying: “LAUD Jehovah of armies, for Jehovah is good; for to time indefinite is his loving-kindness!”’^&#42;1^
“‘They will be bringing a thanksgiving offering into the house of Jehovah, for I shall bring back the captives of the land just as at the start,’ Jehovah has said.”

[NOTE]
====
. Or, “his loyal love.” Heb., chas·dohʹ.
====

[[v24-33-12]]

^<<v24-33-12,12>>^ “This is what Jehovah of armies has said, ‘In this waste place without man and even domestic animal and in all its cities there will yet come to be the pasture ground of the shepherds who are making the flock lie down.’

[[v24-33-13]]

^<<v24-33-13,13>>^ “‘In the cities of the mountainous region, in the cities of the lowland and in the cities of the south and in the land of Benjamin and in the surroundings of Jerusalem and in the cities of Judah flocks will yet pass by under the hands of the one taking the count,’ Jehovah has said.”

[[v24-33-14]]

^<<v24-33-14,14>>^ “‘Look! There are days coming,’ is the utterance of Jehovah, ‘and I shall certainly carry out the good word that I have spoken, concerning the house of Israel and concerning the house of Judah.

[[v24-33-15]]

^<<v24-33-15,15>>^ In those days and at that time I shall make sprout for David a righteous sprout, and he will certainly execute justice and righteousness in the land.^&#42;1^

[NOTE]
====
. Or, “in the earth.” Heb., ba·ʼaʹrets.
====

[[v24-33-16]]

^<<v24-33-16,16>>^ In those days Judah will be saved and Jerusalem itself will reside in security. And this is what she will be called, Jehovah Is Our Righteousness.’”^&#42;1^

[NOTE]
====
. See 23:6 ftn.
====

[[v24-33-17]]

^<<v24-33-17,17>>^ “For this is what Jehovah has said, ‘There will not be cut off in David’s case a man to sit^&#42;1^ upon the throne of the house of Israel.

[NOTE]
====
. Lit., “a man sitting.” Heb., ʼish yo·shevʹ.
====

[[v24-33-18]]

^<<v24-33-18,18>>^ And in the case of the priests, the Levites,^&#42;1^ there will not be cut off a man from before me to offer up whole burnt offering and to make smoke with a grain offering and to render sacrifice always.’”^&#42;2^

[NOTE]
====
. Or, “the Levite priests.”
. Lit., “all the days.” Heb., kol-hai·ya·mimʹ.
====

[[v24-33-19]]

^<<v24-33-19,19>>^ And the word of Jehovah came further to Jeremiah, saying:

[[v24-33-20]]

^<<v24-33-20,20>>^ “This is what Jehovah has said, ‘If YOU people could break my covenant of the day and my covenant of the night, even in order for day and night not to occur in their time,

[[v24-33-21]]

^<<v24-33-21,21>>^ likewise could my own covenant be broken with David my servant so that he should not come to have a son ruling as king upon his throne; also with the Levites, the priests, my ministers.

[[v24-33-22]]

^<<v24-33-22,22>>^ Just as the army of the heavens cannot be counted, neither the sand of the sea be measured, so I shall multiply the seed of David my servant and the Levites who are ministering to me.’”

[[v24-33-23]]

^<<v24-33-23,23>>^ And the word of Jehovah continued to occur to Jeremiah, saying:

[[v24-33-24]]

^<<v24-33-24,24>>^ “Have you not seen what those of this people have spoken, saying, ‘The two families whom Jehovah has chosen, he will also reject them’? And my own people they keep treating with disrespect, so that it should no more continue being a nation before them.

[[v24-33-25]]

^<<v24-33-25,25>>^ “This is what Jehovah has said, ‘If it was not a fact that I had appointed my own covenant of the day and night, the statutes of heaven and earth,

[[v24-33-26]]

^<<v24-33-26,26>>^ so too I would reject even the seed of Jacob and of David my servant, so that I should not take from his seed^&#42;1^ rulers over the seed of Abraham, Isaac and Jacob. For I shall gather their captives and will have pity upon them.’”

[NOTE]
====
. Or, “offspring; posterity.”
====

'''

xref:024-jeremiah/024-jeremiah-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremiah/024-jeremiah-034.adoc#v24-34-0[Próximo Capítulo &#62;]