include::./index.adoc[]

[[v14-31-0]]
=== The Second of Chronicles, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-31-1]]

^<<v14-31-1,1>>^ And as soon as they finished all this, all the Israelites that were found &#91;there&#93; went out to the cities of Judah, and they proceeded to break up the sacred pillars and cut down the sacred poles^&#42;1^ and pull down the high places and the altars out of all Judah and Benjamin and in Eʹphra·im and Ma·nasʹseh until they had finished; after which all the sons of Israel returned to their cities, each one to his own possession.

[NOTE]
====
. Or, “the Asherim.”
====

[[v14-31-2]]

^<<v14-31-2,2>>^ Then Hez·e·kiʹah set the divisions of the priests and of the Levites in their divisions, each one in accordance with its service for the priests and for the Levites as regards the burnt offering and the communion sacrifices to minister and to give thanks and praise in the gates of the camps of Jehovah.

[[v14-31-3]]

^<<v14-31-3,3>>^ And there was a portion of the king from his own goods for the burnt offerings, for the burnt offerings of the morning and the evening, and also the burnt offerings for the sabbaths and for the new moons and for the festival seasons, according to what is written in the law of Jehovah.

[[v14-31-4]]

^<<v14-31-4,4>>^ Furthermore, he said to the people, the inhabitants of Jerusalem, to give the portion of the priests and of the Levites, in order that they might adhere strictly to the law of Jehovah.

[[v14-31-5]]

^<<v14-31-5,5>>^ And as soon as the word broke forth, the sons of Israel increased the firstfruits of the grain, new wine, and oil and honey and all the produce of the field, and the tenth of everything they brought in abundantly.

[[v14-31-6]]

^<<v14-31-6,6>>^ And the sons of Israel and of Judah that were dwelling in the cities of Judah, even they themselves &#91;brought in&#93;^&#42;1^ the tenth of cattle and sheep and the tenth of the holy things, the things sanctified to Jehovah their God. They brought in and so gave heaps upon heaps.

[NOTE]
====
. “Brought in,” LXXVg; M omits.
====

[[v14-31-7]]

^<<v14-31-7,7>>^ In the third month they started the heaps by laying the lowest layer, and in the seventh month they finished.

[[v14-31-8]]

^<<v14-31-8,8>>^ When Hez·e·kiʹah and the princes came and saw the heaps, they proceeded to bless Jehovah and his people Israel.

[[v14-31-9]]

^<<v14-31-9,9>>^ In time Hez·e·kiʹah inquired of the priests and the Levites concerning the heaps.

[[v14-31-10]]

^<<v14-31-10,10>>^ Then Az·a·riʹah^&#42;1^ the chief priest of the house of Zaʹdok said to him, yes, he said: “From the time they started to bring the contribution into the house of Jehovah there has been an eating and getting satisfied and having a surplus in abundance; for Jehovah himself has blessed his people, and what has been left over is this great plenty.”^&#42;2^

[NOTE]
====
. “Azariah.” Heb., ʽAzar·yaʹhu.
. “Blessed his people, and we still have this quantity (great number; multitude) left,” LXX. This difficult passage in M appears to read: “blessed his people and the remainder (ones left over), even this crowd.”
====

[[v14-31-11]]

^<<v14-31-11,11>>^ At this Hez·e·kiʹah said to prepare dining rooms in the house of Jehovah. Accordingly they prepared &#91;them&#93;.

[[v14-31-12]]

^<<v14-31-12,12>>^ And they kept bringing in the contribution and the tenth and the holy things in faithfulness; and Con·a·niʹah^&#42;1^ the Levite was in charge of them as leader, and Shimʹe·i his brother was second.

[NOTE]
====
. “Conaniah.” Heb., Kow·nan·yaʹhu.
====

[[v14-31-13]]

^<<v14-31-13,13>>^ And Je·hiʹel and Az·a·ziʹah^&#42;1^ and Naʹhath and Asʹa·hel and Jerʹi·moth and Joʹza·bad and Eʹli·el and Is·ma·chiʹah^&#42;2^ and Maʹhath and Be·naiʹah^&#42;3^ were commissioners at the side of Con·a·niʹah and Shimʹe·i his brother, by the order of Hez·e·kiʹah the king, and Az·a·riʹah was the leading one of the house of the &#91;true&#93; God.

[NOTE]
====
. “And Azaziah.” Heb., wa·ʽAzaz·yaʹhu.
. “And Ismachiah.” Heb., weYis·makh·yaʹhu.
. “And Benaiah.” Heb., u·Vena·yaʹhu.
====

[[v14-31-14]]

^<<v14-31-14,14>>^ And Koʹre the son of Imʹnah the Levite was the gatekeeper to the east, in charge of the voluntary offerings of the &#91;true&#93; God, to give Jehovah’s contribution and the most holy things.

[[v14-31-15]]

^<<v14-31-15,15>>^ And under his control there were Eʹden and Mi·niʹa·min and Jeshʹu·a^&#42;1^ and She·maiʹah,^&#42;2^ Am·a·riʹah^&#42;3^ and Shec·a·niʹah,^&#42;4^ in the cities of the priests, in office of trust, to give to their brothers in the divisions, equally to great and small;

[NOTE]
====
. “And Jeshua.” Heb., weYe·shuʹaʽ; LXX, “Jesus.” See Ge 49:18 ftn, “You.”
. “And Shemaiah.” Heb., u·Shema·ʽeyaʹhu.
. “Amariah.” Heb., ʼAmar·yaʹhu.
. “And Shecaniah.” Heb., u·Shekhan·yaʹhu.
====

[[v14-31-16]]

^<<v14-31-16,16>>^ apart from their genealogical enrollment of the males from three years of age upward, of all those coming to the house of Jehovah as a daily matter of course, for their service by their obligations according to their divisions.

[[v14-31-17]]

^<<v14-31-17,17>>^ This is^&#42;1^ the genealogical enrollment of the priests by the house of their fathers and also of the Levites, from the age of twenty years upward, by their obligations in their divisions;

[NOTE]
====
. “This is,” LXX; M, “And [they had].”
====

[[v14-31-18]]

^<<v14-31-18,18>>^ both for the genealogical enrollment among all their little ones, their wives and their sons and their daughters, for all the congregation, because in their office of trust they proceeded to sanctify themselves for what was holy;

[[v14-31-19]]

^<<v14-31-19,19>>^ and for the sons of Aaron, the priests, in the fields of pasture ground of their cities. In all the different cities there were men that had been designated by &#91;their&#93; names, to give portions to every male among the priests and to the entire genealogical enrollment among the Levites.

[[v14-31-20]]

^<<v14-31-20,20>>^ And Hez·e·kiʹah proceeded to do like this in all Judah, and he continued to do what was good and right and faithful before Jehovah his God.

[[v14-31-21]]

^<<v14-31-21,21>>^ And in every work that he started in the service of the house of the &#91;true&#93; God and in the law and in the commandment to search for his God, it was with all his heart that he acted, and he proved successful.

'''

xref:014-2-chronicles/014-2-chronicles-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-032.adoc#v14-32-0[Próximo Capítulo &#62;]