include::./index.adoc[]

[[v14-3-0]]
=== The Second of Chronicles, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-3-1]]

^<<v14-3-1,1>>^ Finally Solʹo·mon started to build the house of Jehovah in Jerusalem on Mount Mo·riʹah, where &#91;Jehovah&#93;^&#42;1^ had appeared to David his father, in the place that David had prepared on the threshing floor of Orʹnan the Jebʹu·site.

[NOTE]
====
. “Jehovah,” LXX; M, “he.”
====

[[v14-3-2]]

^<<v14-3-2,2>>^ Accordingly he started to build in the second month on the second &#91;day&#93;, in the fourth year of his reign.

[[v14-3-3]]

^<<v14-3-3,3>>^ And these things Solʹo·mon laid as a foundation for building the house of the &#91;true&#93; God, the length in cubits by the former measurement^&#42;1^ being sixty cubits, and the width twenty cubits.

[NOTE]
====
. ‘A cubit by the former measurement’ was possibly the same as the long cubit that equaled 51.8 cm (20.4 in.). See Eze 40:5 ftn, “Handbreadth.”
====

[[v14-3-4]]

^<<v14-3-4,4>>^ And the porch that was in front of the length was twenty cubits in front of the width of the house, and its height was a hundred and twenty;^&#42;1^ and he proceeded to overlay it inside with pure gold.

[NOTE]
====
. “A hundred and twenty,” MLXXB; LXXASy, “twenty cubits.” By a transposition of the letters of the Heb. word for “a hundred” it would read “cubits,” to produce the expression “twenty cubits.”
====

[[v14-3-5]]

^<<v14-3-5,5>>^ And the great house he covered with juniper wood, after which he covered it with good gold, and then he brought up upon it palm-tree figures and chains.

[[v14-3-6]]

^<<v14-3-6,6>>^ Further, he overlaid the house with precious stone^&#42;1^ for beauty; and the gold was gold from the gold country.^&#42;2^

[NOTE]
====
. Or, “studded the house with precious stones.”
. “Gold country.” Heb., par·waʹyim; LXXBagster(Gr.), pha·rou·imʹ.
====

[[v14-3-7]]

^<<v14-3-7,7>>^ And he went on to cover the house, the rafters, the thresholds and its walls and its doors with gold; and he engraved cherubs upon the walls.

[[v14-3-8]]

^<<v14-3-8,8>>^ And he proceeded to make the house of the Most Holy, its length in relation to the width of the house being twenty cubits, and its own width being twenty cubits; and then he covered it with good gold to the amount of six hundred talents.

[[v14-3-9]]

^<<v14-3-9,9>>^ And the weight for the nails was fifty gold shekels;^&#42;1^ and the roof chambers he covered with gold.

[NOTE]
====
. See App 8A.
====

[[v14-3-10]]

^<<v14-3-10,10>>^ Then he made in the house of the Most Holy two cherubs in the workmanship of images, and overlaid them with gold.

[[v14-3-11]]

^<<v14-3-11,11>>^ As for the wings of the cherubs, their length was twenty cubits, the one wing of five cubits reaching to the wall of the house, and the other wing of five cubits reaching to the wing of the other cherub.

[[v14-3-12]]

^<<v14-3-12,12>>^ And the wing of the one cherub of five cubits was reaching to the wall of the house, and the other wing of five cubits was in contact with the wing of the other cherub.

[[v14-3-13]]

^<<v14-3-13,13>>^ The wings of these cherubs were spread out twenty cubits; and they were standing upon their feet with their faces inward.

[[v14-3-14]]

^<<v14-3-14,14>>^ Further, he made the curtain of blue thread and wool dyed reddish purple and crimson and fine fabric, and worked in cherubs upon it.

[[v14-3-15]]

^<<v14-3-15,15>>^ Then he made before the house two pillars, thirty-five cubits in length,^&#42;1^ and the capital that was upon the top of each one was five cubits.

[NOTE]
====
. “Length,” MSy; LXX, “height.”
====

[[v14-3-16]]

^<<v14-3-16,16>>^ Further, he made chains in necklace style^&#42;1^ and put them upon the tops of the pillars, and made a hundred pomegranates and put them on the chains.

[NOTE]
====
. “In necklace style,” by a slight correction; M, “in the innermost room.”
====

[[v14-3-17]]

^<<v14-3-17,17>>^ And he proceeded to set up the pillars in front of the temple, one to the right and one to the left, after which he called the name of the right-hand one Jaʹchin^&#42;1^ and the name of the left-hand one Boʹaz.^&#42;2^

[NOTE]
====
. Meaning “He Will Firmly Establish.”
. Possibly meaning “In Strength.”
====

'''

xref:014-2-chronicles/014-2-chronicles-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-004.adoc#v14-4-0[Próximo Capítulo &#62;]