include::./index.adoc[]

[[v14-35-0]]
=== The Second of Chronicles, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-35-1]]

^<<v14-35-1,1>>^ Then Jo·siʹah held in Jerusalem a passover to Jehovah and they slaughtered the passover victim on the fourteenth day of the first month.

[[v14-35-2]]

^<<v14-35-2,2>>^ So he stationed the priests over the things under their care and encouraged them in the service of the house of Jehovah.

[[v14-35-3]]

^<<v14-35-3,3>>^ And he went on to say to the Levites, the instructors of all Israel, those holy to Jehovah: “Put the holy Ark in the house that Solʹo·mon the son of David the king of Israel built; it is not YOURS as a burden upon the shoulder. Now serve Jehovah YOUR God and his people Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ And make preparation by the house of YOUR forefathers according to YOUR divisions, by the writing of David the king of Israel and by the writing of Solʹo·mon his son.

[[v14-35-5]]

^<<v14-35-5,5>>^ And stand in the holy place by the classes^&#42;1^ of the house of the forefathers for YOUR brothers, the sons of the people, and the portion of a paternal house belonging to the Levites.

[NOTE]
====
. Lit., “divisions.”
====

[[v14-35-6]]

^<<v14-35-6,6>>^ And slaughter the passover victim and sanctify yourselves and make preparation for YOUR brothers to do according to the word of Jehovah by means of Moses.”

[[v14-35-7]]

^<<v14-35-7,7>>^ Jo·siʹah now contributed to the sons of the people flocks, male lambs and male kids,^&#42;1^ the whole for the passover victims for all who were to be found, to the number of thirty thousand, and cattle, three thousand. These were from the goods of the king.

[NOTE]
====
. Lit., “sons of the goats.”
====

[[v14-35-8]]

^<<v14-35-8,8>>^ And his princes themselves made a contribution as a voluntary offering for the people, for the priests and for the Levites. Hil·kiʹah^&#42;1^ and Zech·a·riʹah and Je·hiʹel themselves as leaders of the house of the &#91;true&#93; God gave to the priests for the passover victims two thousand six hundred, and three hundred cattle.

[NOTE]
====
. “Hilkiah.” Heb., Chil·qi·yahʹ.
====

[[v14-35-9]]

^<<v14-35-9,9>>^ And Con·a·niʹah and She·maiʹah and Ne·thanʹel his brothers and Hash·a·biʹah and Je·iʹel and Joʹza·bad, the chiefs of the Levites, contributed to the Levites for passover victims five thousand, and five hundred cattle.

[[v14-35-10]]

^<<v14-35-10,10>>^ And the service was prepared and the priests kept standing at their places, and the Levites by their divisions, according to the king’s commandment.

[[v14-35-11]]

^<<v14-35-11,11>>^ And they proceeded to slaughter the passover victim and the priests sprinkled &#91;the blood&#93; from their hand,^&#42;1^ while the Levites were stripping the skins off.

[NOTE]
====
. “The blood from their hand,” LXX; Sy, “some of the blood.”
====

[[v14-35-12]]

^<<v14-35-12,12>>^ Further, they prepared^&#42;1^ the burnt offerings so as to give them to the classes by the paternal house, to the sons of the people, so as to make a presentation to Jehovah according to what is written in the book of Moses; and thus also with the cattle.

[NOTE]
====
. “They prepared,” LXX; M, “they removed.”
====

[[v14-35-13]]

^<<v14-35-13,13>>^ And they went boiling the passover offering over the fire according to the custom; and the things made holy they boiled in cooking pots and in round-bottomed pots and in banquet bowls, after which they brought it quickly to all the sons of the people.

[[v14-35-14]]

^<<v14-35-14,14>>^ And afterward they prepared for themselves and for the priests, because the priests the sons of Aaron were engaged in offering up the burnt sacrifices and the fat pieces until night, and the Levites, for their part, prepared for themselves and for the priests the sons of Aaron.

[[v14-35-15]]

^<<v14-35-15,15>>^ And the singers the sons of Aʹsaph were at their office according to the commandment of David and of Aʹsaph and of Heʹman and of Je·duʹthun the visionary of the king; and the gatekeepers were at the different gates. There was no need for them to turn aside from their service, because their brothers the Levites themselves prepared for them.

[[v14-35-16]]

^<<v14-35-16,16>>^ And all the service of Jehovah was prepared on that day to hold the passover and to offer up the burnt offerings upon the altar of Jehovah, according to the commandment of King Jo·siʹah.

[[v14-35-17]]

^<<v14-35-17,17>>^ And the sons of Israel that were to be found proceeded to hold the passover at that time and also the festival of the unfermented cakes for seven days.

[[v14-35-18]]

^<<v14-35-18,18>>^ And there had never been held a passover like it in Israel since the days of Samuel the prophet, neither had any of the other kings of Israel themselves held a passover like that which Jo·siʹah and the priests and the Levites and all Judah and Israel that were to be found and the inhabitants of Jerusalem held.

[[v14-35-19]]

^<<v14-35-19,19>>^ In the eighteenth year of Jo·siʹah’s reign this passover was held.

[[v14-35-20]]

^<<v14-35-20,20>>^ After all this when Jo·siʹah had prepared the house, Neʹcho^&#42;1^ the king of Egypt came up to fight at Carʹche·mish by the Eu·phraʹtes. Then Jo·siʹah went out to an encounter with him.

[NOTE]
====
. Or, “Nekaw (Nekau).”
====

[[v14-35-21]]

^<<v14-35-21,21>>^ At that he sent messengers to him, saying: “What do I have to do with you,^&#42;1^ O king of Judah? It is not against you that I am coming today,^&#42;2^ but it is against another house that my fight is and that God himself said that I should cause disturbance. Refrain for your own sake because of God, who is with me, and do not let him bring you to ruin.”

[NOTE]
====
. Lit., “What [is there] to me and to you?” A Heb. idiom; a repellent question indicating objection to Josiah’s intervention. See App 7B.
. “Not against you that I am coming today,” LXXSyVg; M, “not against you yourself today.”
====

[[v14-35-22]]

^<<v14-35-22,22>>^ And Jo·siʹah did not turn his face away from him, but to fight against him he disguised himself and did not listen to the words of Neʹcho from the mouth of God. So he came to fight in the valley plain of Me·gidʹdo.

[[v14-35-23]]

^<<v14-35-23,23>>^ And the shooters got to shoot at King Jo·siʹah, so that the king said to his servants: “Take me down, for I have been very severely wounded.”

[[v14-35-24]]

^<<v14-35-24,24>>^ Accordingly his servants took him down from the chariot and had him ride in the second war chariot that was his and brought him to Jerusalem. Thus he died and was buried in the graveyard of his forefathers; and all Judah and Jerusalem were mourning over Jo·siʹah.

[[v14-35-25]]

^<<v14-35-25,25>>^ And Jeremiah^&#42;1^ began to chant over Jo·siʹah; and all the male singers and female singers keep talking about Jo·siʹah in their dirges down till today; and they have them set as a regulation over Israel, and there they are written among the dirges.

[NOTE]
====
. “Jeremiah.” Heb., Yir·meyaʹhu.
====

[[v14-35-26]]

^<<v14-35-26,26>>^ As for the rest of the affairs of Jo·siʹah and his acts of loving-kindness,^&#42;1^ according to what is written in the law of Jehovah,

[NOTE]
====
. Or, “loyal love.”
====

[[v14-35-27]]

^<<v14-35-27,27>>^ and his affairs, the first and the last, there they are written in the Book of the Kings of Israel and Judah.

'''

xref:014-2-chronicles/014-2-chronicles-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-036.adoc#v14-36-0[Próximo Capítulo &#62;]