include::./index.adoc[]

[[v14-15-0]]
=== The Second of Chronicles, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-15-1]]

^<<v14-15-1,1>>^ Now for Az·a·riʹah^&#42;1^ the son of Oʹded, the spirit of God came to be upon him.

[NOTE]
====
. “Now for Azariah.” Heb., wa·­ʽAzar·yaʹhu, meaning “Jehovah Has Helped.”
====

[[v14-15-2]]

^<<v14-15-2,2>>^ Consequently he went out before Aʹsa and said to him: “Hear me, O Aʹsa and all Judah and Benjamin! Jehovah is with YOU as long as YOU prove to be with him; and if YOU search for him, he will let himself be found by YOU, but if YOU leave him he will leave YOU.

[[v14-15-3]]

^<<v14-15-3,3>>^ And many were the days that Israel had been without a true God^&#42;1^ and without a priest teaching and without Law.

[NOTE]
====
. Or, “a God of truth (faithfulness).” Heb., ʼElo·hehʹ ʼemethʹ.
====

[[v14-15-4]]

^<<v14-15-4,4>>^ But when in their distress they returned to Jehovah the God of Israel and looked for him, then he let himself be found by them.

[[v14-15-5]]

^<<v14-15-5,5>>^ And in those times there was no peace for one going out or for one coming in, because there were many disorders among all the inhabitants of the lands.

[[v14-15-6]]

^<<v14-15-6,6>>^ And they were crushed to pieces, nation against nation and city against city, because God himself kept them in disorder with every sort of distress.

[[v14-15-7]]

^<<v14-15-7,7>>^ And YOU, be courageous and do not let YOUR hands drop down, because there exists a reward for YOUR activity.”

[[v14-15-8]]

^<<v14-15-8,8>>^ And as soon as Aʹsa heard these words and the prophecy of Oʹded the prophet, he took courage and proceeded to cause the disgusting things to vanish from all the land of Judah and Benjamin and from the cities that he had captured from the mountainous region of Eʹphra·im, and to renew Jehovah’s altar that was before the porch of Jehovah.

[[v14-15-9]]

^<<v14-15-9,9>>^ And he began to collect together all Judah and Benjamin and the alien residents^&#42;1^ with them from Eʹphra·im and Ma·nasʹseh and Simʹe·on, for they had deserted to him from Israel in great number when they saw that Jehovah his God was with him.

[NOTE]
====
. Or, “and the temporary residents.” Heb., wehag·ga·rimʹ; Gr., pro·se·lyʹtous, “proselytes.”
====

[[v14-15-10]]

^<<v14-15-10,10>>^ So they were collected together at Jerusalem in the third month of the fifteenth year of Aʹsa’s reign.

[[v14-15-11]]

^<<v14-15-11,11>>^ Then they sacrificed to Jehovah on that day from the spoil they had brought, seven hundred cattle and seven thousand sheep.

[[v14-15-12]]

^<<v14-15-12,12>>^ Furthermore, they entered into a covenant to search for Jehovah the God of their forefathers with all their heart and with all their soul;

[[v14-15-13]]

^<<v14-15-13,13>>^ that anyone that would not search for Jehovah the God of Israel should be put to death, whether small or great, whether man or woman.

[[v14-15-14]]

^<<v14-15-14,14>>^ So they swore to Jehovah with a loud voice and with joyful shouting and with the trumpets and with horns.^&#42;1^

[NOTE]
====
. “And with horns (shofars).” Heb., u·veshoh·pha·rohthʹ, animals’ curved horns.
====

[[v14-15-15]]

^<<v14-15-15,15>>^ And all Judah gave way to rejoicing over the thing sworn; for it was with all their heart that they had sworn and with full pleasure on their part that they had looked for him, so that he let himself be found by them; and Jehovah continued to give them rest all around.

[[v14-15-16]]

^<<v14-15-16,16>>^ As for even Maʹa·cah &#91;his&#93; grandmother,^&#42;1^ Aʹsa the king himself removed her from &#91;being&#93; lady, because she had made a horrible idol for the sacred pole; and then Aʹsa cut down her horrible idol and pulverized it and burned it in the torrent valley of Kidʹron.

[NOTE]
====
. Lit., “mother.” She was queen mother.
====

[[v14-15-17]]

^<<v14-15-17,17>>^ And the high places themselves did not disappear from Israel. Only Aʹsa’s heart itself proved to be complete all his days.

[[v14-15-18]]

^<<v14-15-18,18>>^ And he proceeded to bring the things made holy by his father and the things made holy by himself into the house of the &#91;true&#93; God, silver and gold and utensils.

[[v14-15-19]]

^<<v14-15-19,19>>^ As for war, it did not occur down to the thirty-fifth year of Aʹsa’s reign.

'''

xref:014-2-chronicles/014-2-chronicles-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-016.adoc#v14-16-0[Próximo Capítulo &#62;]