include::./index.adoc[]

[[v14-4-0]]
=== The Second of Chronicles, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-4-1]]

^<<v14-4-1,1>>^ Then he made the copper altar, twenty cubits being its length, and twenty cubits its width, and ten cubits its height.

[[v14-4-2]]

^<<v14-4-2,2>>^ And he proceeded to make the molten sea ten cubits from its one brim to its other brim, circular all around, and its height was five cubits, and it took a line of thirty cubits to circle all around it.

[[v14-4-3]]

^<<v14-4-3,3>>^ And there was the likeness of gourd-shaped ornaments^&#42;1^ under it clear around, surrounding it, ten in a cubit, enclosing the sea all around. The gourd-shaped ornaments were in two rows, being cast in its casting.

[NOTE]
====
. “Gourd-shaped ornaments,” by a correction in agreement with 1Ki 7:24. Lit., “bulls.”
====

[[v14-4-4]]

^<<v14-4-4,4>>^ It was standing upon twelve bulls, three facing the north and three facing the west and three facing the south and three facing the east; and the sea was above upon them, and all their hind parts were inward.

[[v14-4-5]]

^<<v14-4-5,5>>^ And its thickness was a handbreadth;^&#42;1^ and its brim was like the workmanship of the brim of a cup, a lily blossom. As a receptacle, three thousand bath measures^&#42;2^ were what it could contain.

[NOTE]
====
. About 7.4 cm (2.9 in.).
. About 66,000 L (17,430 gal) when filled to capacity. Compare 1Ki 7:26 ftn, “Measures.”
====

[[v14-4-6]]

^<<v14-4-6,6>>^ Further, he made ten basins, and put five to the right and five to the left, to wash in them. Things having to do with the burnt offering they would rinse in them. But the sea was for the priests to wash in it.

[[v14-4-7]]

^<<v14-4-7,7>>^ He then made lampstands of gold, ten of them of the same plan, and put them in the temple, five to the right and five to the left.

[[v14-4-8]]

^<<v14-4-8,8>>^ Further, he made ten tables, and stationed them in the temple, five to the right and five to the left, and made a hundred bowls of gold.

[[v14-4-9]]

^<<v14-4-9,9>>^ Then he made the courtyard of the priests and the great enclosure and the doors belonging to the enclosure, and their doors he overlaid with copper.

[[v14-4-10]]

^<<v14-4-10,10>>^ And the sea he placed at the right side, to the east, toward the south.

[[v14-4-11]]

^<<v14-4-11,11>>^ Finally Hiʹram^&#42;1^ made the cans and the shovels and the bowls.
So Hiʹram finished doing the work that he did for King Solʹo·mon on the house of the &#91;true&#93; God.

[NOTE]
====
. “Hiram,” LXXVg; M, “Huram.”
====

[[v14-4-12]]

^<<v14-4-12,12>>^ The two pillars and the round capitals upon the top of the two pillars and the two networks to cover the two round capitals that were upon the top of the pillars

[[v14-4-13]]

^<<v14-4-13,13>>^ and the four hundred pomegranates for the two networks, two rows of pomegranates for each network to cover the two round capitals that were upon the pillars,^&#42;1^

[NOTE]
====
. “Upon the pillars,” LXX; M, “in front of the pillars.”
====

[[v14-4-14]]

^<<v14-4-14,14>>^ and the ten carriages and the ten basins upon the carriages;

[[v14-4-15]]

^<<v14-4-15,15>>^ the one sea and the twelve bulls under it,

[[v14-4-16]]

^<<v14-4-16,16>>^ and the cans and the shovels and the forks and all their utensils Hiʹram-aʹbiv^&#42;1^ made for King Solʹo·mon for the house of Jehovah, of polished copper.

[NOTE]
====
. Or, “Hiram his father.” Compare 2:13 ftn.
====

[[v14-4-17]]

^<<v14-4-17,17>>^ In the District of the Jordan the king cast them in the thick ground^&#42;1^ between Sucʹcoth and Zerʹe·dah.

[NOTE]
====
. Lit., “the thickness (compactness) of the ground,” that is, the clayey ground. Possibly, by a correction of M, “at the ford of Adamah.” See 1Ki 7:46 ftn, “Mold.”
====

[[v14-4-18]]

^<<v14-4-18,18>>^ Thus Solʹo·mon made all these utensils in very great quantity, for the weight of the copper was not ascertained.

[[v14-4-19]]

^<<v14-4-19,19>>^ And Solʹo·mon proceeded to make all the utensils that were at the house of the &#91;true&#93; God and the golden altar and the tables with the showbread^&#42;1^ upon them,

[NOTE]
====
. See 1Ki 7:48 ftn.
====

[[v14-4-20]]

^<<v14-4-20,20>>^ and the lampstands and their lamps of pure gold, to light them up before the innermost room according to the rule;

[[v14-4-21]]

^<<v14-4-21,21>>^ and the blossoms and the lamps and the snuffers, of gold, (it was the purest gold,)

[[v14-4-22]]

^<<v14-4-22,22>>^ and the extinguishers and the bowls and the cups and the fire holders, of pure gold, and the entrance of the house, its inner doors for the Most Holy and the doors of the house of the temple, of gold.

'''

xref:014-2-chronicles/014-2-chronicles-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-005.adoc#v14-5-0[Próximo Capítulo &#62;]