include::./index.adoc[]

[[v14-17-0]]
=== The Second of Chronicles, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-17-1]]

^<<v14-17-1,1>>^ And Je·hoshʹa·phat his son began to reign in place of him and to make his position strong over Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ And he proceeded to put military forces in all the fortified cities of Judah and to put garrisons in the land of Judah and in the cities of Eʹphra·im that Aʹsa his father had captured.

[[v14-17-3]]

^<<v14-17-3,3>>^ And Jehovah continued with Je·hoshʹa·phat, because he walked in the former ways of David his forefather and did not search for the Baʹals.

[[v14-17-4]]

^<<v14-17-4,4>>^ For it was for the God of his father that he searched and in his commandment he walked, and not according to the doing of Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ And Jehovah kept the kingdom firmly established in his hand; and all Judah continued to give presents to Je·hoshʹa·phat, and he came to have riches and glory in abundance.

[[v14-17-6]]

^<<v14-17-6,6>>^ And his heart became bold in the ways of Jehovah, and he even removed the high places and the sacred poles from Judah.

[[v14-17-7]]

^<<v14-17-7,7>>^ And in the third year of his reigning he sent for his princes, namely, Ben-haʹil and O·ba·diʹah and Zech·a·riʹah and Ne·thanʹel and Mi·caiʹah, to teach in the cities of Judah,

[[v14-17-8]]

^<<v14-17-8,8>>^ and with them the Levites, She·maiʹah and Neth·a·niʹah and Zeb·a·diʹah and Asʹa·hel and She·mirʹa·moth and Je·honʹa·than and Ad·o·niʹjah and To·biʹjah and Tob-ad·o·niʹjah the Levites, and with them E·lishʹa·ma and Je·hoʹram the priests.

[[v14-17-9]]

^<<v14-17-9,9>>^ And they began teaching in Judah, and with them there was the book of Jehovah’s law; and they kept going around through all the cities of Judah and teaching among the people.

[[v14-17-10]]

^<<v14-17-10,10>>^ And the dread of Jehovah came to be upon all the kingdoms of the lands that were all around Judah, and they did not fight against Je·hoshʹa·phat.

[[v14-17-11]]

^<<v14-17-11,11>>^ And from the Phi·lisʹtines they were bringing to Je·hoshʹa·phat presents and money as tribute. The Arabs also were bringing to him flocks, seven thousand seven hundred rams and seven thousand seven hundred he-goats.

[[v14-17-12]]

^<<v14-17-12,12>>^ And Je·hoshʹa·phat continued advancing and growing great to a superior degree; and he went on building fortified places and storage cities in Judah.

[[v14-17-13]]

^<<v14-17-13,13>>^ And there were many interests that became his in the cities of Judah; and warriors, valiant, mighty men, were in Jerusalem.

[[v14-17-14]]

^<<v14-17-14,14>>^ And these were their offices by the house of their forefathers: Of Judah the chiefs of thousands, Adʹnah the chief, and with him there were three hundred thousand valiant, mighty men.

[[v14-17-15]]

^<<v14-17-15,15>>^ And under his control there was Je·ho·haʹnan the chief, and with him there were two hundred and eighty thousand.

[[v14-17-16]]

^<<v14-17-16,16>>^ And under his control there was Am·a·siʹah the son of Zichʹri the volunteer for Jehovah, and with him there were two hundred thousand valiant, mighty men.

[[v14-17-17]]

^<<v14-17-17,17>>^ And out of Benjamin there was the valiant, mighty man E·liʹa·da, and with him there were two hundred thousand men equipped with the bow and shield.

[[v14-17-18]]

^<<v14-17-18,18>>^ And under his control there was Je·hozʹa·bad, and with him there were a hundred and eighty thousand men outfitted for the army.

[[v14-17-19]]

^<<v14-17-19,19>>^ These were the ones ministering to the king apart from those whom the king put in the fortified cities throughout all Judah.

'''

xref:014-2-chronicles/014-2-chronicles-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-018.adoc#v14-18-0[Próximo Capítulo &#62;]