include::./index.adoc[]

[[v14-32-0]]
=== The Second of Chronicles, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-32-1]]

^<<v14-32-1,1>>^ After these things and this faithful course Sen·nachʹer·ib the king of As·syrʹi·a came and proceeded to invade Judah and camp against the fortified cities, and kept thinking of making them his by a breakthrough.

[[v14-32-2]]

^<<v14-32-2,2>>^ When Hez·e·kiʹah saw that Sen·nachʹer·ib had come with his face set for war against Jerusalem,

[[v14-32-3]]

^<<v14-32-3,3>>^ then he decided with his princes and his mighty men to stop up the waters of the springs that were outside the city; and so they helped him.

[[v14-32-4]]

^<<v14-32-4,4>>^ Accordingly many people were collected together, and they went stopping up all the fountains and the torrent that floods through the middle of the land, saying: “Why should the kings of As·syrʹi·a come and actually find a great deal of water?”

[[v14-32-5]]

^<<v14-32-5,5>>^ Furthermore, he took courage and built up all the broken-down wall and raised towers upon it, and on the outside another wall, and repaired the Mound^&#42;1^ of the City of David, and made missiles in abundance and shields.

[NOTE]
====
. “The Mound of.” Heb., ham·mil·lohʼʹ.
====

[[v14-32-6]]

^<<v14-32-6,6>>^ And he proceeded to put military chiefs over the people and collect them to him at the public square of the gate of the city and speak to the heart of them, saying:

[[v14-32-7]]

^<<v14-32-7,7>>^ “Be courageous and strong. Do not be afraid nor be terrified because of the king of As·syrʹi·a and on account of all the crowd that is with him; for with us there are more than there are with him.

[[v14-32-8]]

^<<v14-32-8,8>>^ With him there is an arm of flesh, but with us there is Jehovah our God to help us and to fight our battles.” And the people began to brace themselves upon the words of Hez·e·kiʹah the king of Judah.

[[v14-32-9]]

^<<v14-32-9,9>>^ It was after this that Sen·nachʹer·ib the king of As·syrʹi·a sent his servants to Jerusalem, while he was at Laʹchish and all his imperial might with him, to Hez·e·kiʹah the king of Judah and to all the Ju·deʹans that were in Jerusalem, saying:

[[v14-32-10]]

^<<v14-32-10,10>>^ “This is what Sen·nachʹer·ib the king of As·syrʹi·a has said, ‘In what is it that YOU are trusting while sitting quiet under siege in Jerusalem?

[[v14-32-11]]

^<<v14-32-11,11>>^ Is not Hez·e·kiʹah alluring YOU so as to give YOU over to die by famine and by thirst, saying: “Jehovah our God himself will deliver us out of the palm of the king of As·syrʹi·a”?

[[v14-32-12]]

^<<v14-32-12,12>>^ Is it not Hez·e·kiʹah himself that removed his high places and his altars and then said to Judah and to Jerusalem: “Before one altar YOU should bow and upon it YOU should make sacrificial smoke”?

[[v14-32-13]]

^<<v14-32-13,13>>^ Do YOU not know what I myself and my forefathers did to all the peoples of the lands? Did the gods of the nations of the lands at all prove able to deliver their land out of my hand?

[[v14-32-14]]

^<<v14-32-14,14>>^ Who was there among all the gods of these nations that my forefathers devoted to destruction that proved able to deliver his people out of my hand, so that YOUR God should be able to deliver YOU out of my hand?

[[v14-32-15]]

^<<v14-32-15,15>>^ And now do not let Hez·e·kiʹah deceive YOU or allure YOU like this and do not put faith in him, for no god^&#42;1^ of any nation or kingdom was able to deliver his people out of my hand and out of the hand of my forefathers. How much less, then, will YOUR own God deliver^&#42;2^ YOU out of my hand?’”

[NOTE]
====
. Lit., “not any god.” Heb., loʼ . . . kol-ʼelohʹah, sing. of ʼelo·himʹ.
. “Deliver,” pl. in Heb., in agreement with its subject ʼElo·heh·khemʹ, “your own God,” which is pl. to denote majesty and divine powers. The verb in LXXVg is sing.; likewise in M, vs 17b.
====

[[v14-32-16]]

^<<v14-32-16,16>>^ And his servants spoke yet further against Jehovah the &#91;true&#93; God and against Hez·e·kiʹah his servant.

[[v14-32-17]]

^<<v14-32-17,17>>^ Even letters he wrote to reproach Jehovah the God of Israel and to talk against him, saying: “Like the gods of the nations of the lands who did not deliver their people out of my hand, so the God of Hez·e·kiʹah will not deliver his people out of my hand.”

[[v14-32-18]]

^<<v14-32-18,18>>^ And they kept calling with a loud voice in the Jews’ language to the people of Jerusalem that were upon the wall, to make them afraid and to disturb them, in order that they might capture the city.

[[v14-32-19]]

^<<v14-32-19,19>>^ And they went on speaking against the God of Jerusalem the same way as against the gods of the peoples of the earth, the work of man’s hands.

[[v14-32-20]]

^<<v14-32-20,20>>^ But Hez·e·kiʹah the king and Isaiah^&#42;1^ the son of Aʹmoz, the prophet, kept praying over this and crying to the heavens for aid.

[NOTE]
====
. “And Isaiah.” Heb., wI·sha·ʽeyaʹhu, meaning “Salvation of Jehovah”; LXX, “Esaias”; Vgc, “Isaias.”
====

[[v14-32-21]]

^<<v14-32-21,21>>^ And Jehovah proceeded to send an angel and efface every valiant, mighty man and leader and chief in the camp of the king of As·syrʹi·a, so that he went back with shame of face to his own land. Later on he entered the house of his god^&#42;1^ and there certain ones that had come out of his own inward parts felled him with the sword.

[NOTE]
====
. “His god.” Heb., ʼelo·havʹ, pl. of ʼelohʹah, applied to the false god of Sennacherib to denote majesty; Gr., the·ouʹ; Lat., deʹi.
====

[[v14-32-22]]

^<<v14-32-22,22>>^ Thus Jehovah saved Hez·e·kiʹah and the inhabitants of Jerusalem out of the hand of Sen·nachʹer·ib the king of As·syrʹi·a and out of the hand of all others and gave them rest all around.

[[v14-32-23]]

^<<v14-32-23,23>>^ And there were many bringing gifts to Jehovah at Jerusalem and choice things to Hez·e·kiʹah the king of Judah, and he came to be exalted in the eyes of all the nations after that.

[[v14-32-24]]

^<<v14-32-24,24>>^ In those days Hez·e·kiʹah fell sick to the point of dying, and he began to pray to Jehovah. So He talked to him, and a portent He gave him.

[[v14-32-25]]

^<<v14-32-25,25>>^ But according to the benefit rendered him Hez·e·kiʹah made no return, for his heart became haughty and there came to be indignation against him and against Judah and Jerusalem.

[[v14-32-26]]

^<<v14-32-26,26>>^ However, Hez·e·kiʹah humbled himself for the haughtiness of his heart, he and the inhabitants of Jerusalem, and Jehovah’s indignation did not come upon them in the days of Hez·e·kiʹah.

[[v14-32-27]]

^<<v14-32-27,27>>^ And Hez·e·kiʹah came to have riches and glory to a very great amount; and storehouses he made for himself for silver and for gold and for precious stones and for balsam oil and for shields and for all the desirable articles;

[[v14-32-28]]

^<<v14-32-28,28>>^ and also storage places for the produce of grain and new wine and oil, and also stalls for all the different sorts of beasts and stalls for the droves.

[[v14-32-29]]

^<<v14-32-29,29>>^ And cities he acquired for himself, and also livestock of the flock and of the herd in abundance; for God gave him very many goods.

[[v14-32-30]]

^<<v14-32-30,30>>^ And Hez·e·kiʹah was the one that stopped up the upper source of the waters of Giʹhon and kept them directed straight along down to the west to the City of David, and Hez·e·kiʹah continued to prove successful in every work of his.

[[v14-32-31]]

^<<v14-32-31,31>>^ And thus it was that by the spokesmen of the princes of Babylon^&#42;1^ that were sent to him to inquire about the portent that had happened in the land, the &#91;true&#93; God left him to put him to the test, to get to know everything in his heart.

[NOTE]
====
. “Babylon,” LXXVg; M, “Babel.”
====

[[v14-32-32]]

^<<v14-32-32,32>>^ As for the rest of the affairs of Hez·e·kiʹah and his acts of loving-kindness,^&#42;1^ there they are written in the vision of Isaiah^&#42;2^ the prophet, the son of Aʹmoz, in the Book of the Kings of Judah and Israel.

[NOTE]
====
. Or, “loyal love.”
. “Isaiah.” Heb., Yesha·ʽeyaʹhu.
====

[[v14-32-33]]

^<<v14-32-33,33>>^ Finally Hez·e·kiʹah lay down with his forefathers, and they buried him in the ascent to the burial places of the sons of David; and honor was what all Judah and the inhabitants of Jerusalem rendered to him at his death. And Ma·nasʹseh his son began to reign in place of him.

'''

xref:014-2-chronicles/014-2-chronicles-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-033.adoc#v14-33-0[Próximo Capítulo &#62;]