include::./index.adoc[]

[[v14-22-0]]
=== The Second of Chronicles, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-22-1]]

^<<v14-22-1,1>>^ Then the inhabitants of Jerusalem made A·ha·ziʹah^&#42;1^ his youngest son king in place of him, (for the marauder band that came with the Arabs to the camp had killed all the older ones,) and A·ha·ziʹah the son of Je·hoʹram began to reign as king of Judah.

[NOTE]
====
. “Ahaziah.” Heb., ʼAchaz·yaʹhu. The same as “Jehoahaz” in 21:17, also meaning “Jehovah Has Taken Hold.” Here God’s name, abbreviated as Yaʹhu, follows “Ahaz” instead of preceding it.
====

[[v14-22-2]]

^<<v14-22-2,2>>^ Twenty-two^&#42;1^ years old was A·ha·ziʹah when he began to reign, and for one year he reigned in Jerusalem. And his mother’s name was Ath·a·liʹah the granddaughter^&#42;2^ of Omʹri.

[NOTE]
====
. “Twenty-two,” LXXLSy and 2Ki 8:26; MVg, “forty-two”; LXX, “twenty.”
. Lit., “daughter.”
====

[[v14-22-3]]

^<<v14-22-3,3>>^ He himself also walked in the ways of the house of Aʹhab, for his mother herself became his counselor in doing wickedly.

[[v14-22-4]]

^<<v14-22-4,4>>^ And he went on doing what was bad in Jehovah’s eyes, the same as the house of Aʹhab, for they themselves became counselors to him after the death of his father, to his ruination.

[[v14-22-5]]

^<<v14-22-5,5>>^ It was also in their counsel that he walked, so that he went with Je·hoʹram the son of Aʹhab the king of Israel to the war against Hazʹa·el the king of Syria at Raʹmoth-gilʹe·ad, at which the shooters got to strike Je·hoʹram.^&#42;1^

[NOTE]
====
. Lit., “Joram.”
====

[[v14-22-6]]

^<<v14-22-6,6>>^ Hence he returned to get healed at Jezʹre·el from the wounds that they had inflicted upon him at Raʹmah when he fought Hazʹa·el the king of Syria.
As for Az·a·riʹah^&#42;1^ the son of Je·hoʹram the king of Judah, he went down to see Je·hoʹram the son of Aʹhab in Jezʹre·el, for he was sick.

[NOTE]
====
. “As for Azariah.” Heb., wa·ʽAzar·yaʹhu; in vss 1, 2, 7-11, “Ahaziah.”
====

[[v14-22-7]]

^<<v14-22-7,7>>^ But it was from God that the downfall of A·ha·ziʹah occurred by &#91;his&#93; coming to Je·hoʹram; and when he came, he went out with Je·hoʹram to Jeʹhu the grandson^&#42;1^ of Nimʹshi, whom Jehovah had anointed to cut off the house of Aʹhab.

[NOTE]
====
. Lit., “son.”
====

[[v14-22-8]]

^<<v14-22-8,8>>^ And it came about that as soon as Jeʹhu had entered into controversy with the house of Aʹhab, he got to find the princes of Judah and the sons of the brothers of A·ha·ziʹah, ministers of A·ha·ziʹah, and he proceeded to kill them.

[[v14-22-9]]

^<<v14-22-9,9>>^ Then he went looking for A·ha·ziʹah, and they finally captured him, as he was hiding in Sa·marʹi·a, and brought him to Jeʹhu. Then they put him to death and buried him, for they said: “He is the grandson of Je·hoshʹa·phat, who searched for Jehovah with all his heart.” And there was no one of the house of A·ha·ziʹah to retain power for the kingdom.

[[v14-22-10]]

^<<v14-22-10,10>>^ As regards Ath·a·liʹah the mother of A·ha·ziʹah, she saw that her son had died. So she rose up and destroyed all the royal offspring of the house of Judah.

[[v14-22-11]]

^<<v14-22-11,11>>^ However, Je·ho·shabʹe·ath the daughter of the king took Je·hoʹash^&#42;1^ the son of A·ha·ziʹah and stole him away from among the sons of the king that were to be put to death, and put him and his nursing woman in the inner room for the couches. And Je·ho·shabʹe·ath the daughter of King Je·hoʹram, the wife of Je·hoiʹa·da the priest, (for she herself happened to be the sister of A·ha·ziʹah,) kept him concealed because of Ath·a·liʹah, and she did not put him to death.

[NOTE]
====
. Lit., “Joash.” See 2Ki 11:21 ftn.
====

[[v14-22-12]]

^<<v14-22-12,12>>^ And he continued with them in the house of the &#91;true&#93; God hidden for six years, while Ath·a·liʹah was ruling as queen over the land.

'''

xref:014-2-chronicles/014-2-chronicles-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-023.adoc#v14-23-0[Próximo Capítulo &#62;]