include::./index.adoc[]

[[v14-16-0]]
=== The Second of Chronicles, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-16-1]]

^<<v14-16-1,1>>^ In the thirty-sixth year of the reign of Aʹsa, Baʹa·sha the king of Israel came up against Judah and began to build Raʹmah, so as not to allow anyone to go out or come in to Aʹsa the king of Judah.

[[v14-16-2]]

^<<v14-16-2,2>>^ Aʹsa now brought out silver and gold from the treasures of Jehovah’s house and the king’s house and sent to Ben-haʹdad the king of Syria, who was dwelling at Damascus, saying:

[[v14-16-3]]

^<<v14-16-3,3>>^ “There is a covenant between me and you and between my father and your father. Here I do send you silver and gold. Go, break your covenant with Baʹa·sha the king of Israel, that he may withdraw from me.”

[[v14-16-4]]

^<<v14-16-4,4>>^ So Ben-haʹdad listened to King Aʹsa and sent the chiefs of the military forces that were his against the cities of Israel, so that they struck Iʹjon and Dan and Aʹbel-maʹim and all the storage places of the cities of Naphʹta·li.

[[v14-16-5]]

^<<v14-16-5,5>>^ And it came about that as soon as Baʹa·sha heard of it, he immediately quit building Raʹmah and stopped his work.

[[v14-16-6]]

^<<v14-16-6,6>>^ As for Aʹsa the king, he took all Judah, and they proceeded to carry away the stones of Raʹmah and its timbers with which Baʹa·sha had built, and he began to build with them Geʹba and Mizʹpah.

[[v14-16-7]]

^<<v14-16-7,7>>^ And at that time Ha·naʹni the seer came to Aʹsa the king of Judah and then said to him: “Because you leaned upon the king of Syria and did not lean upon Jehovah your God, for that reason the military force of the king of Syria has escaped out of your hand.

[[v14-16-8]]

^<<v14-16-8,8>>^ Did not the E·thi·oʹpi·ans and the Libʹy·ans themselves happen to be a very great military force in multitude, in chariots and in horsemen; and because of your leaning upon Jehovah did he not give them into your hand?

[[v14-16-9]]

^<<v14-16-9,9>>^ For, as regards Jehovah, his eyes are roving about through all the earth to show his strength in behalf of those whose heart is complete toward him. You have acted foolishly respecting this, for from now on there will exist wars against you.”

[[v14-16-10]]

^<<v14-16-10,10>>^ However, Aʹsa became offended at the seer and put him in the house of the stocks, because he was in a rage at him over this. And Aʹsa began to crush some others of the people at that same time.

[[v14-16-11]]

^<<v14-16-11,11>>^ And, look! the affairs of Aʹsa, the first and the last, there they are written in the Book of the Kings of Judah and of Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ And Aʹsa in the thirty-ninth year of his reign developed an ailment in his feet until he was very sick; and even in his sickness he searched not for Jehovah but for the healers.

[[v14-16-13]]

^<<v14-16-13,13>>^ Finally Aʹsa lay down with his forefathers and died in the forty-first year of his reigning.

[[v14-16-14]]

^<<v14-16-14,14>>^ So they buried him in his grand burial place^&#42;1^ that he had excavated for himself in the City of David; and they laid him in the bed that had been filled with balsam oil and different sorts of ointment mixed in an ointment of special make. Further, they made an extraordinarily great funeral burning for him.^&#42;2^

[NOTE]
====
. “In his grand burial place.” Lit., “in his burial places.” Heb., veqiv·ro·thavʹ, pl. to denote excellence; LXX, “tomb”; Vg, “sepulcher.”
. Not a cremation of Asa but a burning of spices.
====

'''

xref:014-2-chronicles/014-2-chronicles-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-017.adoc#v14-17-0[Próximo Capítulo &#62;]