include::./index.adoc[]

[[v14-30-0]]
=== The Second of Chronicles, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-30-1]]

^<<v14-30-1,1>>^ And Hez·e·kiʹah proceeded to send to all Israel and Judah, and even letters he wrote to Eʹphra·im and Ma·nasʹseh, to come to the house of Jehovah in Jerusalem to hold the passover to Jehovah the God of Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ However, the king and his princes and all the congregation in Jerusalem resolved to hold the passover in the second month;

[[v14-30-3]]

^<<v14-30-3,3>>^ for they had not been able to hold it at that time, because not enough priests, on the one hand, had sanctified themselves and the people, on the other hand, had not gathered themselves to Jerusalem.

[[v14-30-4]]

^<<v14-30-4,4>>^ And the thing was right in the eyes of the king and in the eyes of all the congregation.

[[v14-30-5]]

^<<v14-30-5,5>>^ So they decided to have the call^&#42;1^ pass through all Israel, from Beʹer-sheʹba to Dan, to come and hold the passover to Jehovah the God of Israel at Jerusalem; for it was not as a multitude that they had done so according to what is written.

[NOTE]
====
. Lit., “voice.” Heb., qohl; Gr., keʹryg·ma, “proclamation; preaching.” Compare Mt 12:41 ftn.
====

[[v14-30-6]]

^<<v14-30-6,6>>^ Accordingly the runners with the letters from the hand of the king and of his princes went throughout all Israel and Judah, even according to the commandment of the king, saying: “YOU sons of Israel, return to Jehovah the God of Abraham, Isaac and Israel, that he may return to the escaped ones that are left of YOU out of the palm of the kings of As·syrʹi·a.

[[v14-30-7]]

^<<v14-30-7,7>>^ And do not become like YOUR forefathers and like YOUR brothers that acted unfaithfully toward Jehovah the God of their forefathers, so that he constituted them an object of astonishment, just as YOU are seeing.

[[v14-30-8]]

^<<v14-30-8,8>>^ Now do not stiffen YOUR neck as YOUR forefathers did. Give place^&#42;1^ to Jehovah and come to his sanctuary that he has sanctified to time indefinite and serve Jehovah YOUR God, that his burning anger may turn back from YOU.

[NOTE]
====
. Lit., “hand.”
====

[[v14-30-9]]

^<<v14-30-9,9>>^ For when YOU return to Jehovah, YOUR brothers and YOUR sons will be objects of mercy before those holding them captive, and be allowed to return to this land; for Jehovah YOUR God is gracious and merciful, and he will not turn away the face from YOU if YOU return to him.”

[[v14-30-10]]

^<<v14-30-10,10>>^ So the runners continued on, passing along from city to city throughout the land of Eʹphra·im and Ma·nasʹseh, even to Zebʹu·lun; but they were continually speaking in mockery of them and deriding them.

[[v14-30-11]]

^<<v14-30-11,11>>^ Only individuals from Ashʹer and Ma·nasʹseh and from Zebʹu·lun humbled themselves so that they came to Jerusalem.

[[v14-30-12]]

^<<v14-30-12,12>>^ The hand of the &#91;true&#93; God proved to be also in Judah to give them one heart to perform the commandment of the king and the princes in the matter of Jehovah.

[[v14-30-13]]

^<<v14-30-13,13>>^ And they proceeded to gather themselves together at Jerusalem, a numerous people, to hold the festival of the unfermented cakes in the second month, a congregation very multitudinous.

[[v14-30-14]]

^<<v14-30-14,14>>^ Then they rose up and removed the altars that were in Jerusalem, and all the incense altars they removed and then threw &#91;them&#93; into the torrent valley of Kidʹron.

[[v14-30-15]]

^<<v14-30-15,15>>^ After that they slaughtered the passover victim on the fourteenth &#91;day&#93; of the second month; and the priests and the Levites themselves had been humiliated, so that they sanctified themselves and brought burnt offerings to the house of Jehovah.

[[v14-30-16]]

^<<v14-30-16,16>>^ And they kept standing at their place according to their rule, according to the law of Moses the man of the &#91;true&#93; God,^&#42;1^ the priests sprinkling the blood received from the hand of the Levites.

[NOTE]
====
. “The man of the [true] God.” Heb., ʼish-ha·ʼElo·himʹ.
====

[[v14-30-17]]

^<<v14-30-17,17>>^ For there were many in the congregation that had not sanctified themselves; and the Levites were in charge of slaughtering the passover victims for all that were not clean, to sanctify them to Jehovah.

[[v14-30-18]]

^<<v14-30-18,18>>^ For there was a great number of the people, many from Eʹphra·im and Ma·nasʹseh, Isʹsa·char and Zebʹu·lun, that had not cleansed themselves, for they did not eat the passover according to what is written; but Hez·e·kiʹah prayed for them, saying: “May the good Jehovah himself make allowance for

[[v14-30-19]]

^<<v14-30-19,19>>^ every one that has prepared his heart to search for the &#91;true&#93; God, Jehovah, the God of his forefathers, though without the purification for what is holy.”

[[v14-30-20]]

^<<v14-30-20,20>>^ Accordingly Jehovah listened to Hez·e·kiʹah and healed the people.

[[v14-30-21]]

^<<v14-30-21,21>>^ So the sons of Israel that were found in Jerusalem held the festival of the unfermented cakes seven days with great rejoicing; and the Levites and the priests were offering praise to Jehovah day by day with loud instruments, even to Jehovah.

[[v14-30-22]]

^<<v14-30-22,22>>^ Moreover, Hez·e·kiʹah spoke to the heart of all the Levites who were acting with fine discretion toward Jehovah. And they proceeded to eat the appointed feast for seven days, sacrificing communion sacrifices and making confession to Jehovah the God of their forefathers.

[[v14-30-23]]

^<<v14-30-23,23>>^ Then all the congregation decided to hold it for seven more days, and so they held it for seven days with rejoicing.

[[v14-30-24]]

^<<v14-30-24,24>>^ For Hez·e·kiʹah the king of Judah himself contributed for the congregation a thousand bulls and seven thousand sheep, and the princes themselves contributed for the congregation a thousand bulls and ten thousand sheep; and priests kept sanctifying themselves in great number.

[[v14-30-25]]

^<<v14-30-25,25>>^ And all the congregation of Judah and the priests and the Levites and all the congregation that came from Israel and the alien residents^&#42;1^ that came from the land of Israel and those dwelling in Judah continued rejoicing.

[NOTE]
====
. Or, “and the temporary residents.” Heb., wehag·ge·rimʹ; LXXVg, “proselytes.”
====

[[v14-30-26]]

^<<v14-30-26,26>>^ And there came to be great rejoicing in Jerusalem, for from the days of Solʹo·mon the son of David the king of Israel there was none like this in Jerusalem.

[[v14-30-27]]

^<<v14-30-27,27>>^ Finally the priests, the Levites, stood up and blessed the people; and a hearing was granted to their voice, so that their prayer came to his holy dwelling, the heavens.

'''

xref:014-2-chronicles/014-2-chronicles-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-031.adoc#v14-31-0[Próximo Capítulo &#62;]