include::./index.adoc[]

[[v14-14-0]]
=== The Second of Chronicles, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-14-1]]

^<<v14-14-1,1>>^ Finally A·biʹjah lay down with his forefathers, and they buried him in the City of David; and Aʹsa his son began to reign in place of him. In his days the land had no disturbance for ten years.^&#42;1^

[NOTE]
====
. MLXX end chapter 13 here.
====

[[v14-14-2]]

^<<v14-14-2,2>>^ And Aʹsa proceeded to do what was good and right in the eyes of Jehovah his God.

[[v14-14-3]]

^<<v14-14-3,3>>^ So he removed the foreign altars^&#42;1^ and the high places and broke up the sacred pillars and cut down the sacred poles.^&#42;2^

[NOTE]
====
. Lit., “the altars of a foreign (country).”
. Or, “the Asherim.”
====

[[v14-14-4]]

^<<v14-14-4,4>>^ Further, he said to Judah to search for Jehovah the God of their forefathers and to do the law and the commandment.

[[v14-14-5]]

^<<v14-14-5,5>>^ Accordingly he removed from all the cities of Judah the high places and the incense stands; and the kingdom continued without disturbance before him.

[[v14-14-6]]

^<<v14-14-6,6>>^ And he went on to build fortified cities in Judah, for the land had no disturbance; and there was no war against him during these years, for Jehovah gave him rest.

[[v14-14-7]]

^<<v14-14-7,7>>^ So he said to Judah: “Let us build these cities and make walls around and towers, double doors and bars. For us the land is yet available, because we have searched for Jehovah our God. We have searched, and he gives us rest all around.” And they went building and proving successful.

[[v14-14-8]]

^<<v14-14-8,8>>^ And Aʹsa came to have a military force bearing the large shield and lance, three hundred thousand out of Judah. And out of Benjamin those bearing the buckler and bending the bow were two hundred and eighty thousand. All these were valiant, mighty men.

[[v14-14-9]]

^<<v14-14-9,9>>^ Later Zeʹrah the E·thi·oʹpi·an^&#42;1^ went out against them with a military force of a million^&#42;2^ men and three hundred chariots, and came as far as Ma·reʹshah.

[NOTE]
====
. “Ethiopian,” LXXVg; M, “Cushite.”
. Lit., “a thousand thousands.”
====

[[v14-14-10]]

^<<v14-14-10,10>>^ Then Aʹsa went out against him^&#42;1^ and they drew up in battle formation in the valley of Zephʹa·thah at Ma·reʹshah.

[NOTE]
====
. Lit., “in front of him,” M; Gr., eis sy·nanʹte·sin au·toiʹ; Vgc(Lat.), obʹvi·am eʹi. Compare Ge 10:9 ftn, “Opposition to.”
====

[[v14-14-11]]

^<<v14-14-11,11>>^ And Aʹsa began to call to Jehovah his God and say: “O Jehovah, as to helping, it does not matter with you whether there are many or &#91;those with&#93; no power. Help us, O Jehovah our God, for upon you we do lean, and in your name we have come against this crowd. O Jehovah, you are our God. Do not let mortal man^&#42;1^ retain strength against you.”

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ; Gr., anʹthro·pos; Lat., hoʹmo.
====

[[v14-14-12]]

^<<v14-14-12,12>>^ At that Jehovah defeated the E·thi·oʹpi·ans before Aʹsa and before Judah, and the E·thi·oʹpi·ans took to flight.

[[v14-14-13]]

^<<v14-14-13,13>>^ And Aʹsa and the people that were with him kept pursuing them as far as Geʹrar, and those of the E·thi·oʹpi·ans continued falling down till there was no one alive of them; for they were broken to pieces before Jehovah and before his camp. Afterward they carried off a very great deal of spoil.

[[v14-14-14]]

^<<v14-14-14,14>>^ Further, they struck all the cities round about Geʹrar, for the dread of Jehovah had come to be upon them; and they went plundering all the cities, for there happened to be much to plunder in them.

[[v14-14-15]]

^<<v14-14-15,15>>^ And even the tents with livestock they struck so that they took captive flocks in great number and camels, after which they returned to Jerusalem.

'''

xref:014-2-chronicles/014-2-chronicles-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-015.adoc#v14-15-0[Próximo Capítulo &#62;]