include::./index.adoc[]

[[v14-13-0]]
=== The Second of Chronicles, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-13-1]]

^<<v14-13-1,1>>^ In the eighteenth year of King Jer·o·boʹam it was that A·biʹjah began to reign over Judah.

[[v14-13-2]]

^<<v14-13-2,2>>^ Three years he reigned in Jerusalem, and his mother’s name was Mi·caiʹah^&#42;1^ the daughter of U·riʹel of Gibʹe·ah. And war itself took place between A·biʹjah and Jer·o·boʹam.

[NOTE]
====
. “Micaiah,” MVg; LXXSy, 11:20-22 and 1Ki 15:2, “Maacah.”
====

[[v14-13-3]]

^<<v14-13-3,3>>^ So A·biʹjah engaged in the war with a military force of four hundred thousand mighty men of war, chosen men. And Jer·o·boʹam himself drew up in battle formation against him with eight hundred thousand chosen men, valiant, mighty men.

[[v14-13-4]]

^<<v14-13-4,4>>^ A·biʹjah now rose up upon Mount Zem·a·raʹim, which is in the mountainous region of Eʹphra·im, and said: “Hear me, O Jer·o·boʹam and all Israel.

[[v14-13-5]]

^<<v14-13-5,5>>^ Is it not for YOU to know that Jehovah the God of Israel himself gave a kingdom to David over Israel to time indefinite, to him and to his sons, by a covenant of salt?

[[v14-13-6]]

^<<v14-13-6,6>>^ And Jer·o·boʹam the son of Neʹbat, the servant of Solʹo·mon the son of David, proceeded to rise up and rebel against his lord.^&#42;1^

[NOTE]
====
. “His lord.” Heb., ʼadho·navʹ, pl. of ʼa·dhohnʹ, to denote excellence.
====

[[v14-13-7]]

^<<v14-13-7,7>>^ And idle men, good-for-nothing fellows, kept collecting themselves together by him. Finally they proved superior to Re·ho·boʹam the son of Solʹo·mon, when Re·ho·boʹam himself happened to be young and fainthearted, and he did not hold his own against them.

[[v14-13-8]]

^<<v14-13-8,8>>^ “And now YOU men are thinking of holding YOUR own against the kingdom of Jehovah in the hand of the sons of David, when YOU are a large crowd and there are with YOU the golden calves that Jer·o·boʹam made for YOU as gods.^&#42;1^

[NOTE]
====
. “As gods.” Or, “as god.” Heb., leʼ·lo·himʹ, pl. of ʼelohʹah. See 1Ki 12:28 ftn, “God.”
====

[[v14-13-9]]

^<<v14-13-9,9>>^ Have YOU not driven out Jehovah’s priests, the sons of Aaron, and the Levites, and do YOU not keep making priests for yourselves like the peoples of the lands? As for anyone that came and filled his hand with power^&#42;1^ by means of a young bull^&#42;2^ and seven rams, he became a priest of what are no gods.^&#42;3^

[NOTE]
====
. Or, “and installed himself.”
. “A young bull.” Lit., “a bull, a son of a herd.”
. “Of what are no gods.” Heb., leloʼʹ ʼelo·himʹ.
====

[[v14-13-10]]

^<<v14-13-10,10>>^ As for us, Jehovah is our God, and we have not left him; but priests are ministering to Jehovah, the sons of Aaron, and also the Levites in the work.

[[v14-13-11]]

^<<v14-13-11,11>>^ And they are making burnt offerings smoke to Jehovah morning by morning and evening by evening and also perfumed incense; and the layers of bread are upon the table of pure &#91;gold&#93;, and there are the golden lampstand and its lamps to light up evening by evening; because we are keeping the obligation to Jehovah our God, but YOU yourselves have left him.

[[v14-13-12]]

^<<v14-13-12,12>>^ And, look! with us there is at the head the &#91;true&#93; God with his priests and the signal trumpets for sounding the battle alarm against YOU. O sons of Israel, do not fight against Jehovah the God of YOUR forefathers, for YOU will not prove successful.”

[[v14-13-13]]

^<<v14-13-13,13>>^ And Jer·o·boʹam, for his part, dispatched an ambush around to come behind them, so that they proved to be in front of Judah and the ambush behind them.

[[v14-13-14]]

^<<v14-13-14,14>>^ When those of Judah turned around, why, there they had the battle in front and behind. And they began to cry out to Jehovah, while the priests were loudly sounding the trumpets.

[[v14-13-15]]

^<<v14-13-15,15>>^ And the men of Judah broke out shouting a war cry. And it came about that, when the men of Judah shouted a war cry, then the &#91;true&#93; God himself defeated Jer·o·boʹam and all Israel before A·biʹjah and Judah.

[[v14-13-16]]

^<<v14-13-16,16>>^ And the sons of Israel took to flight from before Judah, and then God gave them into their hand.

[[v14-13-17]]

^<<v14-13-17,17>>^ And A·biʹjah and his people went striking them down with a vast slaughter; and the slain of Israel kept falling down, five hundred thousand chosen men.

[[v14-13-18]]

^<<v14-13-18,18>>^ Thus the sons of Israel were humbled at that time, but the sons of Judah proved superior because they leaned upon Jehovah the God of their forefathers.

[[v14-13-19]]

^<<v14-13-19,19>>^ And A·biʹjah kept chasing after Jer·o·boʹam and got to capture cities from him, Bethʹel and its dependent towns, and Jeshʹa·nah and its dependent towns, and Eʹphra·in^&#42;1^ and its dependent towns.

[NOTE]
====
. “Ephrain,” Mmargin; MLXXSyVg, “Ephron.”
====

[[v14-13-20]]

^<<v14-13-20,20>>^ And Jer·o·boʹam did not retain any more power in the days of A·biʹjah;^&#42;1^ but Jehovah dealt him a blow, so that he died.

[NOTE]
====
. “Abijah.” Heb., ʼAvi·yaʹhu.
====

[[v14-13-21]]

^<<v14-13-21,21>>^ And A·biʹjah continued to strengthen himself. In time he got fourteen wives for himself, and became father to twenty-two sons and sixteen daughters.

[[v14-13-22]]

^<<v14-13-22,22>>^ And the rest of A·biʹjah’s affairs, even his ways and his words, are written in the exposition^&#42;1^ of the prophet Idʹdo.

[NOTE]
====
. Or, “commentary; midrash.” The first of two occurrences of “midrash” in M. See 24:27 and ftn.
====

'''

xref:014-2-chronicles/014-2-chronicles-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-014.adoc#v14-14-0[Próximo Capítulo &#62;]