include::./index.adoc[]

[[v14-5-0]]
=== The Second of Chronicles, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-5-1]]

^<<v14-5-1,1>>^ Finally all the work that Solʹo·mon had to do for the house of Jehovah was at its completion, and Solʹo·mon began to bring in the things made holy by David his father; and the silver and the gold and all the utensils he put in the treasures of the house of the &#91;true&#93; God.

[[v14-5-2]]

^<<v14-5-2,2>>^ It was then that Solʹo·mon proceeded to congregate the older men^&#42;1^ of Israel and all the heads of the tribes, the chieftains of the paternal houses of the sons of Israel, to Jerusalem, to bring the ark of the covenant of Jehovah up from the City of David, that is to say, Zion.

[NOTE]
====
. Or, “elders.”
====

[[v14-5-3]]

^<<v14-5-3,3>>^ So all the men of Israel congregated themselves to the king at the festival, that of the seventh month.

[[v14-5-4]]

^<<v14-5-4,4>>^ So all the older men of Israel came, and the Levites began to carry the Ark.

[[v14-5-5]]

^<<v14-5-5,5>>^ And they came bringing up the Ark and the tent of meeting and all the holy utensils that were in the tent. The priests the Levites^&#42;1^ brought them up.

[NOTE]
====
. “The priests the Levites,” M; TLXXSy and 24 Heb. mss, “The priests and the Levites”; Vg, “The priests with the Levites.”
====

[[v14-5-6]]

^<<v14-5-6,6>>^ And King Solʹo·mon and all the assembly of Israelites that were keeping their appointment with him before the Ark were sacrificing sheep and cattle that could not be counted or numbered for multitude.

[[v14-5-7]]

^<<v14-5-7,7>>^ Then the priests brought the ark of the covenant of Jehovah into its place, into the innermost room of the house, into the Most Holy, to underneath the wings of the cherubs.

[[v14-5-8]]

^<<v14-5-8,8>>^ Thus the cherubs were continually spreading out their wings over the place of the Ark, so that the cherubs covered over the Ark and its poles from above.

[[v14-5-9]]

^<<v14-5-9,9>>^ But the poles were long, so that the tips of the poles were visible at the Holy^&#42;1^ in front of the innermost room, but they were not visible outside, and they^&#42;2^ continue there down to this day.

[NOTE]
====
. “Holy,” LXX, five Heb. mss and 1Ki 8:8; M, “Ark.”
. “They,” TLXXSy, many Heb. mss and 1Ki 8:8; M, “it.”
====

[[v14-5-10]]

^<<v14-5-10,10>>^ There was nothing in the Ark but the two tablets that Moses had given at Hoʹreb, when Jehovah covenanted with the sons of Israel while they were coming out from Egypt.

[[v14-5-11]]

^<<v14-5-11,11>>^ And it came about when the priests came out from the holy place (for all the priests that were to be found had, for their part, sanctified themselves—there was no need to observe the divisions);

[[v14-5-12]]

^<<v14-5-12,12>>^ and the Levites that were singers belonging to all of them, namely, to Aʹsaph, to Heʹman, to Je·duʹthun and to their sons and to their brothers clothed in fine fabric with cymbals and with stringed instruments and harps, were standing to the east of the altar and along with them priests to &#91;the number of&#93; a hundred and twenty sounding the trumpets;

[[v14-5-13]]

^<<v14-5-13,13>>^ and it came about that as soon as the trumpeters and the singers were as one in causing one sound to be heard in praising and thanking Jehovah, and as soon as they lifted up the sound with the trumpets and with the cymbals and with the instruments of song and with praising Jehovah, “for he is good, for to time indefinite is his loving-kindness,”^&#42;1^ the house itself was filled with a cloud, the very house of Jehovah,

[NOTE]
====
. Or, “loyal love.”
====

[[v14-5-14]]

^<<v14-5-14,14>>^ and the priests were not able to stand to minister because of the cloud; for the glory of Jehovah filled the house of the &#91;true&#93; God.

'''

xref:014-2-chronicles/014-2-chronicles-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-006.adoc#v14-6-0[Próximo Capítulo &#62;]