include::./index.adoc[]

[[v14-28-0]]
=== The Second of Chronicles, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-28-1]]

^<<v14-28-1,1>>^ Twenty years old was Aʹhaz when he began to reign, and for sixteen years he reigned in Jerusalem, and he did not do what was right in Jehovah’s eyes like David his forefather.

[[v14-28-2]]

^<<v14-28-2,2>>^ But he walked in the ways of the kings of Israel, and even molten statues he made of the Baʹals.

[[v14-28-3]]

^<<v14-28-3,3>>^ And he himself made sacrificial smoke in the valley of the son of Hinʹnom^&#42;1^ and proceeded to burn up his sons^&#42;2^ in the fire, according to the detestable things of the nations that Jehovah had driven out from before the sons of Israel.

[NOTE]
====
. “In the valley of the son of Hinnom.” Heb., beghehʼʹ ven-Hin·nomʹ; Gr., en Gai·be·ne·nomʹ; Vgc(Lat.), in valʹle Be·nenʹnom. See App 4C.
. “Sons,” MLXXVg; Sy and 2Ki 16:3, “son.”
====

[[v14-28-4]]

^<<v14-28-4,4>>^ And he regularly sacrificed and made sacrificial smoke on the high places and upon the hills and under every sort of luxuriant tree.

[[v14-28-5]]

^<<v14-28-5,5>>^ Consequently Jehovah his God gave him into the hand of the king of Syria, so that they struck him and carried off from him a great number of captives and brought them to Damascus. And also into the hand of the king of Israel he was given, so that he struck him with a great slaughter.

[[v14-28-6]]

^<<v14-28-6,6>>^ Accordingly Peʹkah the son of Rem·a·liʹah killed in Judah a hundred and twenty thousand in one day, all valiant men, because of their leaving Jehovah the God of their forefathers.

[[v14-28-7]]

^<<v14-28-7,7>>^ Further, Zichʹri, a mighty man of Eʹphra·im, killed Ma·a·seiʹah the son of the king and Az·riʹkam the leader of the household and El·kaʹnah the one next to the king.

[[v14-28-8]]

^<<v14-28-8,8>>^ Moreover, the sons of Israel took two hundred thousand of their brothers captive, women, sons and daughters; and also a great deal of spoil they took from them as plunder, after which they brought the spoil to Sa·marʹi·a.

[[v14-28-9]]

^<<v14-28-9,9>>^ And there happened to be a prophet of Jehovah there whose name was Oʹded. So he went out before the army that was coming to Sa·marʹi·a and said to them: “Look! It was because of the rage of Jehovah the God of YOUR forefathers against Judah that he gave them into YOUR hand, so that YOU did a killing among them with a raging that has reached clear to the heavens.

[[v14-28-10]]

^<<v14-28-10,10>>^ And now the sons of Judah and of Jerusalem YOU are thinking^&#42;1^ of reducing to menservants and maidservants for yourselves. Nevertheless, are there not with YOU yourselves cases of guilt against Jehovah YOUR God?

[NOTE]
====
. Lit., “saying [to yourselves].”
====

[[v14-28-11]]

^<<v14-28-11,11>>^ And now listen to me and return the captives that you have captured from YOUR brothers, for Jehovah’s burning anger is against YOU.”

[[v14-28-12]]

^<<v14-28-12,12>>^ At that &#91;certain&#93; men of the heads of the sons of Eʹphra·im, Az·a·riʹah the son of Je·ho·haʹnan, Ber·e·chiʹah the son of Me·shilʹle·moth and Je·hiz·kiʹah the son of Shalʹlum and A·maʹsa the son of Hadʹlai, rose up against those coming in from the military campaign,

[[v14-28-13]]

^<<v14-28-13,13>>^ and they said to them: “YOU must not bring in the captives here, for it will result in guilt against Jehovah on our part. YOU are thinking of adding to our sins and to our guilt, for abundant is the guilt we have, and there is burning anger against Israel.”

[[v14-28-14]]

^<<v14-28-14,14>>^ Accordingly the armed men left the captives and the plunder before the princes and all the congregation.

[[v14-28-15]]

^<<v14-28-15,15>>^ Then the men that were designated by their names rose up and took hold of the captives, and all their naked ones they clothed from the spoil. So they clothed them and furnished them with sandals and fed them and gave them drink and greased them. Furthermore, in the case of anyone tottering, they gave them transportation on the asses and brought them to Jerʹi·cho, the city of palm trees, beside their brothers. After that they returned to Sa·marʹi·a.

[[v14-28-16]]

^<<v14-28-16,16>>^ At that time King Aʹhaz sent to the kings of As·syrʹi·a for them to help him.

[[v14-28-17]]

^<<v14-28-17,17>>^ And once again the Eʹdom·ites themselves came in and went striking down Judah and carrying off captives.

[[v14-28-18]]

^<<v14-28-18,18>>^ As for the Phi·lisʹtines, they made a raid upon the cities of the She·pheʹlah^&#42;1^ and the Negʹeb^&#42;2^ of Judah and got to capture Beth-sheʹmesh and Aiʹja·lon and Ge·deʹroth and Soʹco and its dependent towns and Timʹnah and its dependent towns and Gimʹzo and its dependent towns; and they took up dwelling there.

[NOTE]
====
. Or, “the lowland.”
. Or, “the south.” See Ge 12:9 ftn.
====

[[v14-28-19]]

^<<v14-28-19,19>>^ For Jehovah humbled Judah on account of Aʹhaz the king of Israel,^&#42;1^ because he let unrestraint grow in Judah, and there was an acting with great unfaithfulness^&#42;2^ toward Jehovah.

[NOTE]
====
. “Israel,” M; TLXXSyVg and about 12 Heb. mss, “Judah.”
. “There was an acting with . . . unfaithfulness.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v14-28-20]]

^<<v14-28-20,20>>^ Eventually Tilʹgath-pil·neʹser the king of As·syrʹi·a came against him and caused him distress, and did not strengthen him.

[[v14-28-21]]

^<<v14-28-21,21>>^ For Aʹhaz stripped the house of Jehovah and the house of the king and of the princes and thus made a gift to the king of As·syrʹi·a; but it was of no assistance to him.

[[v14-28-22]]

^<<v14-28-22,22>>^ However, at the time that he was causing him distress, he acted unfaithfully still more toward Jehovah, that is, King Aʹhaz did.

[[v14-28-23]]

^<<v14-28-23,23>>^ And he began to sacrifice to the gods of Damascus that were striking him, and he went on to say: “Because the gods of the kings of Syria are helping them, to them I shall sacrifice, that they may help me.” And they themselves became to him a cause for making him and all Israel stumble.

[[v14-28-24]]

^<<v14-28-24,24>>^ Furthermore, Aʹhaz gathered together the utensils of the house of the &#91;true&#93; God and cut to pieces the utensils of the house of the &#91;true&#93; God, and closed the doors of the house of Jehovah, and made altars for himself at every corner in Jerusalem.

[[v14-28-25]]

^<<v14-28-25,25>>^ And in all cities, even the cities of Judah, he made high places for making sacrificial smoke to other gods, so that he offended Jehovah the God of his forefathers.

[[v14-28-26]]

^<<v14-28-26,26>>^ As for the rest of his affairs and all his ways, the first and the last, there they are written in the Book of the Kings of Judah and of Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Finally Aʹhaz lay down with his forefathers, and they buried him in the city, in Jerusalem, for they did not bring him into the burial places of the kings of Israel. And Hez·e·kiʹah his son began to reign in place of him.

'''

xref:014-2-chronicles/014-2-chronicles-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-029.adoc#v14-29-0[Próximo Capítulo &#62;]