include::./index.adoc[]

[[v14-6-0]]
=== The Second of Chronicles, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-6-1]]

^<<v14-6-1,1>>^ It was then that Solʹo·mon said: “Jehovah himself said he was to reside in the thick gloom;

[[v14-6-2]]

^<<v14-6-2,2>>^ and I, for my part, have built a house of lofty abode for you and an established place for you to dwell in to time indefinite.”^&#42;1^

[NOTE]
====
. “To time indefinite.” Lit., “times indefinite.” Heb., ʽoh·la·mimʹ, pl.
====

[[v14-6-3]]

^<<v14-6-3,3>>^ Then the king turned his face and began to bless all the congregation^&#42;1^ of Israel, while all the congregation of Israel were standing up.

[NOTE]
====
. “Congregation of.” Heb., qehalʹ; Gr., ek·kle·siʹan.
====

[[v14-6-4]]

^<<v14-6-4,4>>^ And he went on to say: “Blessed be Jehovah the God of Israel, who spoke with his own mouth with David my father and by his own hands has given fulfillment, saying,

[[v14-6-5]]

^<<v14-6-5,5>>^ ‘From the day that I brought my people out from the land of Egypt I have not chosen a city out of all the tribes of Israel to build a house for my name to prove to be there, and I have not chosen a man to become leader over my people Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ But I shall choose Jerusalem for my name to prove to be there, and I shall choose David to come to be over my people Israel.’

[[v14-6-7]]

^<<v14-6-7,7>>^ And it came to be close to the heart of David my father to build a house to the name of Jehovah the God of Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ But Jehovah said to David my father, ‘For the reason that it proved to be close to your heart to build a house to my name, you did well because it proved to be close to your heart.

[[v14-6-9]]

^<<v14-6-9,9>>^ Only you yourself will not build the house, but your son who is coming forth from your loins is the one that will build the house to my name.’

[[v14-6-10]]

^<<v14-6-10,10>>^ And Jehovah proceeded to carry out his word that he had spoken, that I might rise up in the place of David my father and sit upon the throne of Israel, just as Jehovah had spoken, and that I might build the house to the name of Jehovah the God of Israel,

[[v14-6-11]]

^<<v14-6-11,11>>^ and that I might place there the ark where the covenant of Jehovah is that he concluded with the sons of Israel.”

[[v14-6-12]]

^<<v14-6-12,12>>^ And he began standing before the altar of Jehovah in front of all the congregation of Israel, and he now spread out his palms.

[[v14-6-13]]

^<<v14-6-13,13>>^ (For Solʹo·mon had made a platform of copper and then put it in the middle of the enclosure. Its length was five cubits,^&#42;1^ and its width five cubits, and its height three cubits; and he kept standing upon it.) And he proceeded to kneel upon his knees in front of all the congregation of Israel and to spread his palms out to the heavens.

[NOTE]
====
. A cubit equaled 44.5 cm (17.5 in.).
====

[[v14-6-14]]

^<<v14-6-14,14>>^ And he went on to say: “O Jehovah the God of Israel, there is no God^&#42;1^ like you in the heavens or on the earth, keeping the covenant and the loving-kindness toward your servants who are walking before you with all their heart;

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; Gr., The·osʹ; Lat., Deʹus.
====

[[v14-6-15]]

^<<v14-6-15,15>>^ you who have kept toward your servant David my father what you promised him, so that you made the promise^&#42;1^ with your mouth, and with your own hand you have made fulfillment as at this day.

[NOTE]
====
. Lit., “you spoke.”
====

[[v14-6-16]]

^<<v14-6-16,16>>^ And now, O Jehovah the God of Israel, keep toward your servant David my father what you promised him, saying, ‘There will not be cut off a man of yours from before me to sit upon the throne of Israel, if only your sons will take care of their way by walking in my law, just as you have walked before me.’

[[v14-6-17]]

^<<v14-6-17,17>>^ And now, O Jehovah the God of Israel, let your promise^&#42;1^ that you have promised to your servant David prove trustworthy.

[NOTE]
====
. Lit., “word.”
====

[[v14-6-18]]

^<<v14-6-18,18>>^ “But will God truly dwell with mankind^&#42;1^ upon the earth? Look! Heaven, yes, the heaven of the heavens themselves, cannot contain you; how much less, then, this house that I have built?

[NOTE]
====
. Lit., “the earthling man.” Heb., ha·ʼa·dhamʹ.
====

[[v14-6-19]]

^<<v14-6-19,19>>^ And you must turn toward the prayer of your servant and to his request for favor, O Jehovah my God, by listening to the entreating cry and to the prayer with which your servant is praying before you,

[[v14-6-20]]

^<<v14-6-20,20>>^ that your eyes may prove to be opened toward this house day and night, toward the place where you said you would put your name, by listening to the prayer with which your servant prays toward this place.

[[v14-6-21]]

^<<v14-6-21,21>>^ And you must listen to the entreaties of your servant and of your people Israel when they pray toward this place, that you yourself may hear from the place of your dwelling, from the heavens; and you must hear and forgive.

[[v14-6-22]]

^<<v14-6-22,22>>^ “If a man sins against his fellowman and he actually lays a cursing upon him to bring him under liability to the curse, and he actually comes &#91;within&#93; the curse before your altar in this house,

[[v14-6-23]]

^<<v14-6-23,23>>^ then may you yourself hear from the heavens, and you must act and judge your servants so as to pay back the wicked by putting his course^&#42;1^ upon his own head and by pronouncing the righteous one righteous by giving to him according to his own righteousness.

[NOTE]
====
. Or, “his way.” Heb., dar·kohʹ.
====

[[v14-6-24]]

^<<v14-6-24,24>>^ “And if your people Israel are defeated before an enemy because they kept sinning against you, and they indeed return and laud your name and pray and make request for favor before you in this house,

[[v14-6-25]]

^<<v14-6-25,25>>^ then may you yourself hear from the heavens, and you must forgive the sin of your people Israel and bring them back to the ground that you gave to them and their forefathers.

[[v14-6-26]]

^<<v14-6-26,26>>^ “When the heavens are shut up so that no rain occurs because they kept sinning against you, and they actually pray toward this place and laud your name &#91;and&#93; from their sin they turn back because you kept afflicting them,

[[v14-6-27]]

^<<v14-6-27,27>>^ then may you yourself hear from the heavens, and you must forgive the sin of your servants, even of your people Israel, because you instruct them regarding the good way in which they should walk; and you must give rain upon your land that you have given to your people as a hereditary possession.

[[v14-6-28]]

^<<v14-6-28,28>>^ “In case a famine occurs in the land, in case a pestilence occurs, in case scorching and mildew, locusts and cockroaches occur; in case their enemies besiege them in the land of their gates^&#42;1^—any sort of plague and any sort of malady—

[NOTE]
====
. Or, “cities,” as represented by their gates.
====

[[v14-6-29]]

^<<v14-6-29,29>>^ whatever prayer, whatever request for favor there may occur on the part of any man or of all your people Israel, because they know each one his own plague and his own pain; when he actually spreads out his palms toward this house,

[[v14-6-30]]

^<<v14-6-30,30>>^ then may you yourself hear from the heavens, the place of your dwelling, and you must forgive and give to each one according to all his ways, because you know his heart (for you yourself alone well know the heart of the sons of mankind);

[[v14-6-31]]

^<<v14-6-31,31>>^ to the end that they may fear you by walking in your ways all the days that they are alive upon the surface of the ground that you gave to our forefathers.

[[v14-6-32]]

^<<v14-6-32,32>>^ “And also to the foreigner who is no part of your people Israel and who actually comes from a distant land by reason of your great name and your strong hand and your stretched-out arm, and they actually come and pray toward this house,

[[v14-6-33]]

^<<v14-6-33,33>>^ then may you yourself listen from the heavens, from your established place of dwelling, and you must do according to all for which the foreigner calls to you; in order that all the peoples of the earth may know your name and may fear you the same as your people Israel do, and may know that your name has been called upon this house that I have built.

[[v14-6-34]]

^<<v14-6-34,34>>^ “In case your people go out to the war against their enemies in the way that you send them, and they indeed pray to you in the direction of this city that you have chosen and the house that I have built to your name,

[[v14-6-35]]

^<<v14-6-35,35>>^ you must also hear from the heavens their prayer and their request for favor, and you must execute judgment for them.

[[v14-6-36]]

^<<v14-6-36,36>>^ “In case they sin against you (for there is no man that does not sin), and you have to be incensed at them and abandon them to an enemy, and their captors actually carry them off captive to a land distant or nearby;

[[v14-6-37]]

^<<v14-6-37,37>>^ and they indeed come to their senses in the land where they have been carried off captive, and they actually return and make request to you for favor in the land where they are captives, saying, ‘We have sinned, we have erred and we have acted wickedly’;

[[v14-6-38]]

^<<v14-6-38,38>>^ and they indeed return to you with all their heart and with all their soul in the land where they are captives of those who carried them off captive, and they indeed pray in the direction of their land that you gave to their forefathers and the city that you have chosen and the house that I have built to your name;

[[v14-6-39]]

^<<v14-6-39,39>>^ you must also hear from the heavens, from your established place of dwelling, their prayer and their requests for favor, and you must execute judgment for them and forgive your people who have sinned against you.

[[v14-6-40]]

^<<v14-6-40,40>>^ “Now, O my God, please, let your eyes prove to be opened and your ears attentive to the prayer respecting this place.

[[v14-6-41]]

^<<v14-6-41,41>>^ And now do rise up, O Jehovah God, into your rest, you and the Ark of your strength. Let your priests themselves, O Jehovah God, be clothed with salvation, and let your loyal ones themselves rejoice in goodness.

[[v14-6-42]]

^<<v14-6-42,42>>^ O Jehovah God, do not turn back the face of your anointed one.^&#42;1^ O do remember the loving-kindnesses^&#42;2^ to David your servant.”

[NOTE]
====
. “Your anointed one.” Lit., “your anointed ones.” Heb., meshi·cheyʹkha, pl.; Gr., khri·stouʹ; Syr., dam·shi·chakh; Lat., chriʹsti.
. Or, “[cases of] loyal love.”
====

'''

xref:014-2-chronicles/014-2-chronicles-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-007.adoc#v14-7-0[Próximo Capítulo &#62;]