include::./index.adoc[]

[[v14-12-0]]
=== The Second of Chronicles, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-12-1]]

^<<v14-12-1,1>>^ And it came about that, as soon as the kingship of Re·ho·boʹam was firmly established and as soon as he was strong, he left the law of Jehovah, and also all Israel with him.

[[v14-12-2]]

^<<v14-12-2,2>>^ And it came about in the fifth year of King Re·ho·boʹam that Shiʹshak the king of Egypt came up against Jerusalem, (for they had behaved unfaithfully toward Jehovah,)

[[v14-12-3]]

^<<v14-12-3,3>>^ with twelve hundred chariots and with sixty thousand horsemen; and there was no number to the people that came with him out of Egypt—Libʹy·ans,^&#42;1^ Sukʹki·im and E·thi·oʹpi·ans.^&#42;2^

[NOTE]
====
. “Libyans.” Heb., Lu·vimʹ.
. “And Ethiopians,” LXXVg; Heb., weKhu·shimʹ, “and Cushites.”
====

[[v14-12-4]]

^<<v14-12-4,4>>^ And he got to capture the fortified cities that belonged to Judah and finally came as far as Jerusalem.

[[v14-12-5]]

^<<v14-12-5,5>>^ Now as for She·maiʹah the prophet, he came to Re·ho·boʹam and the princes of Judah who had gathered themselves at Jerusalem because of Shiʹshak, and he proceeded to say to them: “This is what Jehovah has said, ‘YOU, for your part, have left me, and I, too, for my part, have left YOU to the hand of Shiʹshak.’”

[[v14-12-6]]

^<<v14-12-6,6>>^ At that the princes of Israel and the king humbled themselves and said: “Jehovah is righteous.”

[[v14-12-7]]

^<<v14-12-7,7>>^ And when Jehovah saw that they had humbled themselves, the word of Jehovah came to She·maiʹah, saying: “They have humbled themselves. I shall not bring them to ruin, and in a little while I shall certainly give them an escape, and my rage will not pour forth upon Jerusalem by the hand of Shiʹshak.

[[v14-12-8]]

^<<v14-12-8,8>>^ But they will become servants of his, that they may know the difference between my service and the service of the kingdoms of the lands.”

[[v14-12-9]]

^<<v14-12-9,9>>^ So Shiʹshak the king of Egypt came up against Jerusalem and took the treasures of the house of Jehovah and the treasures of the king’s house. Everything he took; and so he took the gold shields that Solʹo·mon had made.

[[v14-12-10]]

^<<v14-12-10,10>>^ Consequently King Re·ho·boʹam made in their place copper shields, and he committed them to the control of the chiefs of the runners, the guards of the entrance of the king’s house.

[[v14-12-11]]

^<<v14-12-11,11>>^ And it would occur that as often as the king came to the house of Jehovah, the runners came in and carried them and returned them to the guard chamber of the runners.

[[v14-12-12]]

^<<v14-12-12,12>>^ And because he humbled himself, Jehovah’s anger turned back from him, and he &#91;did&#93; not &#91;think&#93; of bringing them to ruin completely. And, besides, there happened to be good things in Judah.

[[v14-12-13]]

^<<v14-12-13,13>>^ And King Re·ho·boʹam continued to make his position strong in Jerusalem and kept reigning; for Re·ho·boʹam was forty-one years old when he began to reign, and for seventeen years he reigned in Jerusalem, the city that Jehovah had chosen out of all the tribes of Israel to put his name there. And his mother’s name was Naʹa·mah the Amʹmon·it·ess.

[[v14-12-14]]

^<<v14-12-14,14>>^ But he did what was bad, for he had not firmly established his heart to search for Jehovah.

[[v14-12-15]]

^<<v14-12-15,15>>^ As for Re·ho·boʹam’s affairs, the first and the last, are they not written among the words of She·maiʹah the prophet and of Idʹdo the visionary by genealogical enrollment? And there were wars between Re·ho·boʹam and Jer·o·boʹam all the time.

[[v14-12-16]]

^<<v14-12-16,16>>^ Finally Re·ho·boʹam lay down with his forefathers and was buried in the City of David; and A·biʹjah^&#42;1^ his son began to reign in place of him.

[NOTE]
====
. “Abijam” in 1Ki 14:31; 1Ki 15:1, 7, 8.
====

'''

xref:014-2-chronicles/014-2-chronicles-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-013.adoc#v14-13-0[Próximo Capítulo &#62;]