include::./index.adoc[]

[[v14-24-0]]
=== The Second of Chronicles, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-24-1]]

^<<v14-24-1,1>>^ Seven years old was Je·hoʹash^&#42;1^ when he began to reign, and for forty years he reigned in Jerusalem. And his mother’s name was Zibʹi·ah from Beʹer-sheʹba.

[NOTE]
====
. Lit., “Joash.” See 2Ki 11:21 ftn.
====

[[v14-24-2]]

^<<v14-24-2,2>>^ And Je·hoʹash kept doing what was right in Jehovah’s eyes all the days of Je·hoiʹa·da the priest.

[[v14-24-3]]

^<<v14-24-3,3>>^ And Je·hoiʹa·da proceeded to get two wives for him, and he came to be father to sons and daughters.

[[v14-24-4]]

^<<v14-24-4,4>>^ Now it occurred afterward that it became close to the heart of Je·hoʹash to renovate the house of Jehovah.

[[v14-24-5]]

^<<v14-24-5,5>>^ Accordingly he collected the priests and the Levites together and said to them: “Go out to the cities of Judah and collect money from all Israel to repair the house of YOUR God from year to year; and YOU, for YOUR part, should act quickly in the matter.” And the Levites did not act quickly.

[[v14-24-6]]

^<<v14-24-6,6>>^ So the king called Je·hoiʹa·da the head and said to him: “Why is it that you have not required an account of the Levites for bringing in from Judah and Jerusalem the sacred tax ordered by Moses the servant of Jehovah, even that of the congregation of Israel, for the tent of the Testimony?

[[v14-24-7]]

^<<v14-24-7,7>>^ For as regards Ath·a·liʹah the wicked woman, her sons themselves had broken into the house of the &#91;true&#93; God, and even all the holy things of the house of Jehovah they had rendered up to the Baʹals.”

[[v14-24-8]]

^<<v14-24-8,8>>^ Then the king said &#91;the word&#93;, and so they made a chest and put it outside at the gate of the house of Jehovah.

[[v14-24-9]]

^<<v14-24-9,9>>^ After that they issued a call throughout Judah and Jerusalem to bring to Jehovah the sacred tax ordered by Moses the servant of the &#91;true&#93; God^&#42;1^ upon Israel in the wilderness.

[NOTE]
====
. “Servant of the [true] God.” Heb., ʽe·vedh-ha·ʼElo·himʹ; Sy, “servant of Jehovah.” See App 1F.
====

[[v14-24-10]]

^<<v14-24-10,10>>^ And all the princes and all the people began to rejoice, and they kept bringing and casting it into the chest until they all had given.

[[v14-24-11]]

^<<v14-24-11,11>>^ And it came about at the proper time he would bring the chest to the care of the king by the hand of the Levites, and, as soon as they saw that there was plenty of money, the secretary of the king and the commissioner of the chief priest came and then emptied the chest and lifted it up and returned it to its place. That was the way they did from day to day, so that they gathered money in abundance.

[[v14-24-12]]

^<<v14-24-12,12>>^ Then the king and Je·hoiʹa·da would give it to the doers of the work of the service of Jehovah’s house, and they came to be hirers of the stonecutters and of the craftsmen for renovating Jehovah’s house, and also of the workers in iron and copper for repairing Jehovah’s house.

[[v14-24-13]]

^<<v14-24-13,13>>^ And the doers of the work began operations, and the repair work kept advancing by their hand, and finally they made the house of the &#91;true&#93; God stand as it structurally should and made it strong.

[[v14-24-14]]

^<<v14-24-14,14>>^ And as soon as they had finished they brought before the king and Je·hoiʹa·da the rest of the money, and they proceeded to make utensils for the house of Jehovah, utensils for the ministry and for making offerings and cups and utensils of gold and of silver; and they came to be offerers of burnt sacrifices in the house of Jehovah constantly all the days of Je·hoiʹa·da.

[[v14-24-15]]

^<<v14-24-15,15>>^ And Je·hoiʹa·da got to be old and satisfied with years and gradually died, being a hundred and thirty years old at his death.

[[v14-24-16]]

^<<v14-24-16,16>>^ So they buried him in the City of David along with the kings, because he had done good in Israel and with the &#91;true&#93; God and His house.

[[v14-24-17]]

^<<v14-24-17,17>>^ And after Je·hoiʹa·da’s death the princes of Judah came in and proceeded to bow down to the king. At that time the king listened to them.

[[v14-24-18]]

^<<v14-24-18,18>>^ And gradually they left the house of Jehovah the God of their forefathers and began serving the sacred poles and the idols, so that there came to be indignation against Judah and Jerusalem because of this guilt of theirs.

[[v14-24-19]]

^<<v14-24-19,19>>^ And he kept sending prophets among them to bring them back to Jehovah; and they kept bearing witness^&#42;1^ against them, but they did not give ear.

[NOTE]
====
. “Kept bearing witness.” Lat., pro·te·stanʹtes.
====

[[v14-24-20]]

^<<v14-24-20,20>>^ And God’s spirit itself enveloped^&#42;1^ Zech·a·riʹah the son of Je·hoiʹa·da the priest, so that he stood up above the people and said to them: “This is what the &#91;true&#93; God has said, ‘Why are YOU overstepping the commandments of Jehovah, so that YOU cannot prove successful? Because YOU have left Jehovah, he will, in turn, leave YOU.’”

[NOTE]
====
. Lit., “clothed.”
====

[[v14-24-21]]

^<<v14-24-21,21>>^ Finally they conspired against him and pelted him with stones at the king’s commandment in the courtyard of Jehovah’s house.

[[v14-24-22]]

^<<v14-24-22,22>>^ And Je·hoʹash the king did not remember the loving-kindness that Je·hoiʹa·da his father had exercised toward him, so that he killed his son, who, when he was at the point of dying, said: “Let Jehovah see to it and ask it back.”

[[v14-24-23]]

^<<v14-24-23,23>>^ And it came about at the turn of the year a military force of Syria came up against him, and they began to invade Judah and Jerusalem. Then they brought all the princes of the people to ruin from among the people, and all their spoil they sent to the king of Damascus.

[[v14-24-24]]

^<<v14-24-24,24>>^ For it was with a small number of men that the military force of the Syrians made an invasion, and Jehovah himself gave into their hand a military force of very great number, because they had left Jehovah the God of their forefathers; and upon Je·hoʹash they executed acts of judgment.

[[v14-24-25]]

^<<v14-24-25,25>>^ And when they went away from him (for they left him with many diseases), his own servants conspired against him because of the blood of the sons^&#42;1^ of Je·hoiʹa·da the priest; and they got to kill him upon his own couch, so that he died. Then they buried him in the City of David, but they did not bury him in the burial places of the kings.

[NOTE]
====
. “Sons,” MSy; LXXVg, “son.” Possibly M uses the pl. here to denote the excellence and worth of Jehoiada’s son Zechariah, the prophet-priest.
====

[[v14-24-26]]

^<<v14-24-26,26>>^ And these were the conspirators against him: Zaʹbad the son of Shimʹe·ath the Amʹmon·it·ess and Je·hozʹa·bad the son of Shimʹrith the Moʹab·i·tess.

[[v14-24-27]]

^<<v14-24-27,27>>^ As for his sons and the abundance of the pronouncement against him and the founding of the house of the &#91;true&#93; God, there they are written in the exposition^&#42;1^ of the Book of the Kings. And Am·a·ziʹah his son began to reign in place of him.

[NOTE]
====
. Or, “midrash.” Heb., midh·rashʹ. The only other occurrence of this Heb. word in M is in 13:22, where see ftn.
====

'''

xref:014-2-chronicles/014-2-chronicles-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-025.adoc#v14-25-0[Próximo Capítulo &#62;]