include::./index.adoc[]

[[v14-26-0]]
=== The Second of Chronicles, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-26-1]]

^<<v14-26-1,1>>^ Then all the people of Judah took Uz·ziʹah,^&#42;1^ he being sixteen years old, and they made him king in place of his father Am·a·ziʹah.

[NOTE]
====
. Meaning “My Strength Is Jehovah.” Heb., ʽUz·zi·yaʹhu.
====

[[v14-26-2]]

^<<v14-26-2,2>>^ He it was that rebuilt Eʹloth and then restored it to Judah after the king had lain down with his forefathers.

[[v14-26-3]]

^<<v14-26-3,3>>^ Sixteen years old was Uz·ziʹah when he began to reign, and for fifty-two years he reigned in Jerusalem. And his mother’s name was Je·co·liʹah of Jerusalem.

[[v14-26-4]]

^<<v14-26-4,4>>^ And he kept doing what was right in Jehovah’s eyes, according to all that Am·a·ziʹah his father had done.

[[v14-26-5]]

^<<v14-26-5,5>>^ And he continually tended to search for God in the days of Zech·a·riʹah, the instructor in the fear of the &#91;true&#93; God; and, in the days of his searching for Jehovah, the &#91;true&#93; God made him prosperous.

[[v14-26-6]]

^<<v14-26-6,6>>^ And he proceeded to go out and fight against the Phi·lisʹtines and break through the wall of Gath and the wall of Jabʹneh and the wall of Ashʹdod, after which he built cities in Ashʹdod &#91;territory&#93; and among the Phi·lisʹtines.

[[v14-26-7]]

^<<v14-26-7,7>>^ And the &#91;true&#93; God continued to help him against the Phi·lisʹtines and against the Arabians that were dwelling in Gur·baʹal and the Me·uʹnim.

[[v14-26-8]]

^<<v14-26-8,8>>^ And the Amʹmon·ites began to give tribute to Uz·ziʹah. Eventually his fame went even as far as Egypt, for he displayed strength to an extraordinary degree.

[[v14-26-9]]

^<<v14-26-9,9>>^ Moreover, Uz·ziʹah built towers in Jerusalem by the Corner Gate and by the Valley Gate and by the Buttress, and made them strong.

[[v14-26-10]]

^<<v14-26-10,10>>^ Further, he built towers in the wilderness, and hewed out many cisterns (for there was a great deal of livestock that became his), and also in the She·pheʹlah and on the tableland. There were farmers and vinedressers in the mountains and in Carʹmel, for a lover of agriculture he proved to be.

[[v14-26-11]]

^<<v14-26-11,11>>^ Moreover, Uz·ziʹah came to have a force engaging in war, those going out on military service in troops, by the number of their registration by the hand of Je·iʹel the secretary and Ma·a·seiʹah the officer under the control of Han·a·niʹah of the king’s princes.

[[v14-26-12]]

^<<v14-26-12,12>>^ The entire number of the heads of the paternal houses, of the valiant, mighty men, was two thousand six hundred.

[[v14-26-13]]

^<<v14-26-13,13>>^ And under their control the army forces were three hundred and seven thousand five hundred men engaging in war with the power of a military force to help the king against the enemy.

[[v14-26-14]]

^<<v14-26-14,14>>^ And Uz·ziʹah continued to prepare for them, for the entire army, shields and lances and helmets and coats of mail and bows and slingstones.

[[v14-26-15]]

^<<v14-26-15,15>>^ Further, he made in Jerusalem engines of war, the invention of engineers, that they might come to be upon the towers and upon the corners, to shoot arrows and great stones. Consequently his fame went out to a great distance, for he was helped wonderfully until he was strong.

[[v14-26-16]]

^<<v14-26-16,16>>^ However, as soon as he was strong, his heart became haughty even to the point of causing ruin, so that he acted unfaithfully against Jehovah his God and came into the temple of Jehovah to burn incense upon the altar of incense.

[[v14-26-17]]

^<<v14-26-17,17>>^ Immediately Az·a·riʹah the priest and with him priests of Jehovah, eighty valiant men, came in after him.

[[v14-26-18]]

^<<v14-26-18,18>>^ Then they stood up against Uz·ziʹah the king and said to him: “It is not your business, O Uz·ziʹah, to burn incense to Jehovah, but it is the business of the priests the sons of Aaron, the ones sanctified, to burn incense. Go out from the sanctuary; for you have acted unfaithfully, and it is not for any glory to you on the part of Jehovah God.”

[[v14-26-19]]

^<<v14-26-19,19>>^ But Uz·ziʹah became enraged while in his hand there was a censer for burning incense, and, during his rage against the priests, leprosy itself flashed up in his forehead before the priests in the house of Jehovah beside the altar of incense.

[[v14-26-20]]

^<<v14-26-20,20>>^ When Az·a·riʹah the chief priest^&#42;1^ and all the priests turned toward him, why, there he was stricken with leprosy in his forehead! So they excitedly began to remove him from there, and he himself also hastened to go out, because Jehovah had smitten him.

[NOTE]
====
. Or, “the high priest.” LXX, “the first priest”; Lat., ponʹti·fex.
====

[[v14-26-21]]

^<<v14-26-21,21>>^ And Uz·ziʹah the king continued to be a leper until the day of his death, and he kept dwelling in a house exempt from duties, as a leper; for he had been severed from the house of Jehovah, while Joʹtham his son was over the king’s house, judging the people of the land.

[[v14-26-22]]

^<<v14-26-22,22>>^ And the rest of the affairs of Uz·ziʹah, the first and the last, Isaiah^&#42;1^ the son of Aʹmoz the prophet has written.

[NOTE]
====
. Meaning “Salvation of Jehovah.” Heb., Yesha·ʽeyaʹhu.
====

[[v14-26-23]]

^<<v14-26-23,23>>^ Finally Uz·ziʹah lay down with his forefathers; and so they buried him with his forefathers, &#91;but&#93; in the burial field that belonged to the kings, for they said: “He is a leper.” And Joʹtham his son began to reign in place of him.

'''

xref:014-2-chronicles/014-2-chronicles-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-027.adoc#v14-27-0[Próximo Capítulo &#62;]