include::./index.adoc[]

[[v14-19-0]]
=== The Second of Chronicles, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-19-1]]

^<<v14-19-1,1>>^ Then Je·hoshʹa·phat the king of Judah returned in peace to his own house at Jerusalem.

[[v14-19-2]]

^<<v14-19-2,2>>^ Jeʹhu the son of Ha·naʹni the visionary now went out before him and said to King Je·hoshʹa·phat: “Is it to the wicked that help is to be given, and is it for those hating Jehovah that you should have love? And for this there is indignation against you from the person of Jehovah.

[[v14-19-3]]

^<<v14-19-3,3>>^ Nevertheless, there are good things that have been found with you, because you have cleared out the sacred poles from the land and you have prepared your heart to search for the &#91;true&#93; God.”

[[v14-19-4]]

^<<v14-19-4,4>>^ And Je·hoshʹa·phat continued dwelling in Jerusalem; and he began to go out again among the people from Beʹer-sheʹba to the mountainous region of Eʹphra·im, that he might bring them back to Jehovah the God of their forefathers.

[[v14-19-5]]

^<<v14-19-5,5>>^ And he proceeded to station judges throughout the land in all the fortified cities of Judah, city by city.

[[v14-19-6]]

^<<v14-19-6,6>>^ And he went on to say to the judges: “See what YOU are doing, because it is not for man that YOU judge but it is for Jehovah; and he is with YOU in the matter of judgment.

[[v14-19-7]]

^<<v14-19-7,7>>^ And now let the dread of Jehovah come to be upon YOU. Be careful and act, for with Jehovah our God there is no unrighteousness or partiality or taking of a bribe.”

[[v14-19-8]]

^<<v14-19-8,8>>^ And in Jerusalem also Je·hoshʹa·phat stationed some of the Levites and the priests and some of the heads of the paternal houses of Israel for the judgment of Jehovah and for the legal cases of the inhabitants of Jerusalem.^&#42;1^

[NOTE]
====
. “The legal cases of the inhabitants of Jerusalem,” by a correction of M and in agreement with LXXVg; M, “the legal case. Then they returned to Jerusalem.”
====

[[v14-19-9]]

^<<v14-19-9,9>>^ Further, he laid a command upon them, saying: “This is how YOU should do in the fear of Jehovah with faithfulness and with a complete heart.

[[v14-19-10]]

^<<v14-19-10,10>>^ As for every legal case that will come to YOU of YOUR brothers who are dwelling in their cities, involving the shedding of blood,^&#42;1^ involving law and commandment and regulations and judicial decisions, YOU must warn them that they may not do wrong against Jehovah and indignation may not have to take place against YOU and against YOUR brothers. This is how YOU should do that YOU may not incur guilt.

[NOTE]
====
. Lit., “between blood and blood.” Compare De 17:8.
====

[[v14-19-11]]

^<<v14-19-11,11>>^ And here is Am·a·riʹah the chief priest^&#42;1^ over YOU for every matter of Jehovah; and Zeb·a·diʹah the son of Ishʹma·el the leader of the house of Judah for every matter of the king; and as officers the Levites are available for YOU. Be strong and act, and let Jehovah prove to be with what is good.”

[NOTE]
====
. “The chief priest.” Lat., sa·cerʹdos et ponʹti·fex.
====

'''

xref:014-2-chronicles/014-2-chronicles-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-020.adoc#v14-20-0[Próximo Capítulo &#62;]