include::./index.adoc[]

[[v14-34-0]]
=== The Second of Chronicles, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-34-1]]

^<<v14-34-1,1>>^ Eight years old was Jo·siʹah when he began to reign, and for thirty-one years he reigned in Jerusalem.

[[v14-34-2]]

^<<v14-34-2,2>>^ And he proceeded to do what was right in Jehovah’s eyes and walk in the ways of David his forefather; and he did not turn aside to the right or to the left.

[[v14-34-3]]

^<<v14-34-3,3>>^ And in the eighth year of his reigning, while he was still a boy, he started to search for the God of David his forefather; and in the twelfth year he started to cleanse Judah and Jerusalem from the high places and the sacred poles and the graven images and the molten statues.

[[v14-34-4]]

^<<v14-34-4,4>>^ Further, they pulled down before him the altars of the Baʹals; and the incense stands that were up above he cut down from off them; and the sacred poles and the graven images and the molten statues he broke in pieces and reduced to powder, and then sprinkled &#91;it&#93; upon the surface of the burial places of those that used to sacrifice to them.

[[v14-34-5]]

^<<v14-34-5,5>>^ And the bones of priests he burned upon their altars. Thus he cleansed Judah and Jerusalem.

[[v14-34-6]]

^<<v14-34-6,6>>^ Also, in the cities of Ma·nasʹseh and Eʹphra·im and Simʹe·on and clear to Naphʹta·li, in their devastated places all around,

[[v14-34-7]]

^<<v14-34-7,7>>^ he even went pulling down the altars and the sacred poles, and the graven images he crushed and reduced to powder; and all the incense stands he cut down in all the land of Israel, after which he returned to Jerusalem.

[[v14-34-8]]

^<<v14-34-8,8>>^ And in the eighteenth year of his reigning, when he had cleansed the land and the house, he sent Shaʹphan the son of Az·a·liʹah and Ma·a·seiʹah the chief of the city and Joʹah the son of Joʹa·haz the recorder to repair the house of Jehovah his God.

[[v14-34-9]]

^<<v14-34-9,9>>^ And they proceeded to come to Hil·kiʹah^&#42;1^ the high priest^&#42;2^ and give the money that was being brought to the house of God, which the Levites the doorkeepers had gathered from the hand of Ma·nasʹseh and Eʹphra·im and from all the rest of Israel and from all Judah and Benjamin and the inhabitants of Jerusalem.^&#42;3^

[NOTE]
====
. Meaning “My Portion Is Jehovah.” Heb., Chil·qi·yaʹhu.
. Lit., “the great priest,” MLXXVg.
. “The inhabitants of Jerusalem,” MTLXXSyVg; Mmargin and many Heb. mss, “they returned to Jerusalem.”
====

[[v14-34-10]]

^<<v14-34-10,10>>^ Then they put &#91;it&#93; into the hand of the doers^&#42;1^ of the work that were appointed over^&#42;2^ the house of Jehovah. In turn the doers of the work who were active in the house of Jehovah applied it to mending and repairing the house.

[NOTE]
====
. “Doers,” LXXSyVg and many Heb. mss; M, “doer.”
. Or, “in.”
====

[[v14-34-11]]

^<<v14-34-11,11>>^ So they gave it to the craftsmen and the builders to buy hewn stones and timbers for clamps and to build with beams the houses that the kings of Judah had brought to ruin.

[[v14-34-12]]

^<<v14-34-12,12>>^ And the men were acting in faithfulness in the work; and over them there were appointed Jaʹhath and O·ba·diʹah the Levites, from the sons of Me·rarʹi, and Zech·a·riʹah and Me·shulʹlam, from the sons of the Koʹhath·ites, to act as overseers. And the Levites, each of whom was expert with the instruments of song,

[[v14-34-13]]

^<<v14-34-13,13>>^ were over the burden bearers, and the overseers of all the doers of the work for the different services; and from the Levites there were secretaries and officers and gatekeepers.

[[v14-34-14]]

^<<v14-34-14,14>>^ Now while they were bringing out the money that was being brought to the house of Jehovah, Hil·kiʹah the priest found the book of Jehovah’s law by the hand of Moses.

[[v14-34-15]]

^<<v14-34-15,15>>^ So Hil·kiʹah answered and said to Shaʹphan the secretary: “The very book of the law I have found in the house of Jehovah.” With that Hil·kiʹah gave the book to Shaʹphan.

[[v14-34-16]]

^<<v14-34-16,16>>^ Then Shaʹphan brought the book to the king and replied further to the king, saying: “All that has been put in the hand of your servants they are doing.

[[v14-34-17]]

^<<v14-34-17,17>>^ And they pour out the money that is found in the house of Jehovah and put it in the hand of the appointed men and into the hand of the doers of the work.”

[[v14-34-18]]

^<<v14-34-18,18>>^ And Shaʹphan the secretary went on to report to the king, saying: “There is a book that Hil·kiʹah the priest gave me.” And Shaʹphan began to read out of it before the king.

[[v14-34-19]]

^<<v14-34-19,19>>^ And it came about that as soon as the king heard the words of the law, he immediately ripped his garments apart.

[[v14-34-20]]

^<<v14-34-20,20>>^ Then the king commanded Hil·kiʹah and A·hiʹkam the son of Shaʹphan and Abʹdon the son of Miʹcah and Shaʹphan the secretary and A·saiʹah the king’s servant, saying:

[[v14-34-21]]

^<<v14-34-21,21>>^ “Go, inquire of Jehovah in my own behalf and in behalf of what is left in Israel and in Judah concerning the words of the book that has been found, for great is Jehovah’s rage that must be poured out against us because of the fact that our forefathers did not keep the word of Jehovah by doing according to all that is written in this book.”

[[v14-34-22]]

^<<v14-34-22,22>>^ Accordingly Hil·kiʹah along with those whom the king &#91;had said&#93;^&#42;1^ went to Hulʹdah the prophetess, the wife of Shalʹlum the son of Tikʹvah^&#42;2^ the son of Harʹhas^&#42;3^ the caretaker of the garments, as she was dwelling in Jerusalem in the second quarter; and they proceeded to speak to her like this.

[NOTE]
====
. “Had said,” LXX; M ­omits.
. Lit., “Tokhath.”
. Lit., “Hasrah.” But see 2Ki 22:14.
====

[[v14-34-23]]

^<<v14-34-23,23>>^ In turn she said to them:
“This is what Jehovah the God of Israel has said, ‘SAY^&#42;1^ to the man that sent YOU to me:

[NOTE]
====
. “Say,” imperative, masc., pl.
====

[[v14-34-24]]

^<<v14-34-24,24>>^ “This is what Jehovah has said, ‘Here I am bringing calamity upon this place and its inhabitants, all the curses that are written in the book that they read before the king of Judah,

[[v14-34-25]]

^<<v14-34-25,25>>^ due to the fact that they have left me and gone making sacrificial smoke to other gods, in order to offend me with all the doings of their hands and that my rage may pour forth upon this place and not be extinguished.’”

[[v14-34-26]]

^<<v14-34-26,26>>^ And to the king of Judah, who is sending YOU to inquire of Jehovah, this is what YOU should say to him: “This is what Jehovah the God of Israel has said, ‘As regards the words that you have heard,

[[v14-34-27]]

^<<v14-34-27,27>>^ for the reason that your heart was soft so that you humbled yourself because of God^&#42;1^ at your hearing his words concerning this place and its inhabitants, and you humbled yourself before me and ripped your garments apart and wept before me, I, even I, have heard, is the utterance of Jehovah.

[NOTE]
====
. “God,” MVg; Sy, “Jehovah”; LXX, “me.”
====

[[v14-34-28]]

^<<v14-34-28,28>>^ Here I am gathering you to your forefathers, and you will certainly be gathered to your graveyard^&#42;1^ in peace, and your eyes will not look upon all the calamity that I am bringing upon this place and its inhabitants.’”’”
Then they brought the reply to the king.

[NOTE]
====
. Lit., “burial places.”
====

[[v14-34-29]]

^<<v14-34-29,29>>^ And the king proceeded to send and gather all the older men of Judah and of Jerusalem.

[[v14-34-30]]

^<<v14-34-30,30>>^ The king now went up to the house of Jehovah with all the men of Judah and the inhabitants of Jerusalem and the priests and the Levites and all the people, the great as well as the small; and he began to read in their ears all the words of the book of the covenant, which had been found at the house of Jehovah.

[[v14-34-31]]

^<<v14-34-31,31>>^ And the king kept standing in his place and proceeded to conclude the covenant before Jehovah to go following Jehovah and to keep his commandments and his testimonies and his regulations with all his heart and with all his soul, to perform the words of the covenant that were written in this book.

[[v14-34-32]]

^<<v14-34-32,32>>^ Furthermore, he had all those who were found in Jerusalem and Benjamin to take their stand &#91;to it&#93;. And the inhabitants of Jerusalem proceeded to do according to the covenant of God, the God of their forefathers.

[[v14-34-33]]

^<<v14-34-33,33>>^ After that Jo·siʹah removed all the detestable things out of all the lands that belonged to the sons of Israel, and he had all who were found in Israel take up service, to serve Jehovah their God. All his days they did not turn aside from following Jehovah the God of their forefathers.

'''

xref:014-2-chronicles/014-2-chronicles-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-035.adoc#v14-35-0[Próximo Capítulo &#62;]