include::./index.adoc[]

[[v14-9-0]]
=== The Second of Chronicles, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-9-1]]

^<<v14-9-1,1>>^ And the queen of Sheʹba herself heard the report about Solʹo·mon, and she proceeded to come to test Solʹo·mon with perplexing questions at Jerusalem, along with a very impressive train and camels carrying balsam oil, and gold in great quantity, and precious stones. At length she came in to Solʹo·mon and spoke with him about everything that happened to be close to her heart.

[[v14-9-2]]

^<<v14-9-2,2>>^ Solʹo·mon, in turn, went on to tell her all her matters, and no matter was hidden from Solʹo·mon that he did not tell her.

[[v14-9-3]]

^<<v14-9-3,3>>^ When the queen of Sheʹba got to see Solʹo·mon’s wisdom and the house that he had built,

[[v14-9-4]]

^<<v14-9-4,4>>^ and the food of his table and the sitting of his servants and the table service^&#42;1^ of his waiters and their attire and his drinking service and their attire, and his burnt sacrifices that he regularly offered up at the house of Jehovah, then there proved to be no more spirit in her.

[NOTE]
====
. Lit., “the standing.”
====

[[v14-9-5]]

^<<v14-9-5,5>>^ So she said to the king: “True was the word that I heard in my own land about your matters and about your wisdom.

[[v14-9-6]]

^<<v14-9-6,6>>^ And I did not put faith in their words until I had come that my own eyes might see; and, look! there has not been told me the half of the abundance of your wisdom. You have surpassed the report that I have heard.

[[v14-9-7]]

^<<v14-9-7,7>>^ Happy are your men, and happy are these servants of yours who are standing before you constantly and listening to your wisdom.

[[v14-9-8]]

^<<v14-9-8,8>>^ May Jehovah your God come to be blessed, who has taken delight in you by putting you upon his throne as king for Jehovah your God; because your God loved Israel, to make it stand to time indefinite, so that he put you over them as king to execute judicial decision and righteousness.”

[[v14-9-9]]

^<<v14-9-9,9>>^ Then she gave the king a hundred and twenty talents^&#42;1^ of gold, and balsam oil in very great quantity, and precious stones; and there had not come to be the like of that balsam oil which the queen of Sheʹba gave to King Solʹo·mon.

[NOTE]
====
. See App 8A.
====

[[v14-9-10]]

^<<v14-9-10,10>>^ And, besides, the servants of Hiʹram and the servants of Solʹo·mon who brought gold from Oʹphir brought timbers of algum trees and precious stones.

[[v14-9-11]]

^<<v14-9-11,11>>^ And the king proceeded to make out of the timbers of the algum trees stairs for the house of Jehovah and for the king’s house and also harps and stringed instruments for the singers, and the like of them had never been seen before in the land of Judah.

[[v14-9-12]]

^<<v14-9-12,12>>^ And King Solʹo·mon himself gave the queen of Sheʹba all her delight for which she had asked, besides &#91;the value of&#93; what she brought to the king. So she turned about and went to her own land, she together with her servants.

[[v14-9-13]]

^<<v14-9-13,13>>^ And the weight of the gold that came to Solʹo·mon in one year amounted to six hundred and sixty-six talents^&#42;1^ of gold,

[NOTE]
====
. See App 8A.
====

[[v14-9-14]]

^<<v14-9-14,14>>^ aside from the men of travel^&#42;1^ and the merchants who were bringing in and all the kings of the Arabs and the governors of the land who were bringing in gold and silver to Solʹo·mon.

[NOTE]
====
. Or, “the traffickers.” Possibly, by a correction of M, “the ships of Tarshish.”
====

[[v14-9-15]]

^<<v14-9-15,15>>^ And King Solʹo·mon went on to make two hundred large shields of alloyed gold (six hundred &#91;shekels&#93; of alloyed gold he proceeded to lay upon each large shield),

[[v14-9-16]]

^<<v14-9-16,16>>^ and three hundred bucklers of alloyed gold (three miʹnas^&#42;1^ of gold he proceeded to lay upon each buckler). Then the king put them in the House of the Forest of Lebʹa·non.

[NOTE]
====
. “Minas,” Sy and 1Ki 10:17; M, “hundred.”
====

[[v14-9-17]]

^<<v14-9-17,17>>^ Further, the king made a great ivory throne and overlaid it with pure gold.

[[v14-9-18]]

^<<v14-9-18,18>>^ And there were six steps to the throne, and there was a footstool in gold to the throne (they were attached), and there were armrests on this side and on that side by the place of sitting, and two lions were standing beside the armrests.

[[v14-9-19]]

^<<v14-9-19,19>>^ And there were twelve lions standing there upon the six steps on this side and on that side. No other kingdom had any made just like it.

[[v14-9-20]]

^<<v14-9-20,20>>^ And all the drinking vessels of King Solʹo·mon were of gold, and all the vessels of the House of the Forest of Lebʹa·non were of pure gold. There was nothing of silver; it was considered as nothing at all in the days of Solʹo·mon.

[[v14-9-21]]

^<<v14-9-21,21>>^ For ships belonging to the king were going to Tarʹshish with the servants of Hiʹram. Once every three years ships of Tarʹshish would come in, carrying gold and silver, ivory, and apes and peacocks.

[[v14-9-22]]

^<<v14-9-22,22>>^ So King Solʹo·mon was greater than all the other kings of the earth in riches and wisdom.

[[v14-9-23]]

^<<v14-9-23,23>>^ And all the kings of the earth were seeking the face of Solʹo·mon to hear his wisdom, which the &#91;true&#93; God had put in his heart.

[[v14-9-24]]

^<<v14-9-24,24>>^ And they were bringing each his gift, articles of silver and articles of gold and garments, armor and balsam oil, horses and mules as a yearly matter of course.

[[v14-9-25]]

^<<v14-9-25,25>>^ And Solʹo·mon came to have four thousand stalls of horses and chariots and twelve thousand steeds,^&#42;1^ and he kept them stationed in the chariot cities and close by the king in Jerusalem.

[NOTE]
====
. Or, “horsemen.”
====

[[v14-9-26]]

^<<v14-9-26,26>>^ And he came to be ruler over all the kings from the River^&#42;1^ down to the land of the Phi·lisʹtines and down to the boundary of Egypt.

[NOTE]
====
. That is, the Euphrates.
====

[[v14-9-27]]

^<<v14-9-27,27>>^ Furthermore, the king made the silver in Jerusalem like the stones; and cedarwood he made like the sycamore trees that are in the She·pheʹlah^&#42;1^ for abundance.

[NOTE]
====
. Or, “the lowland.”
====

[[v14-9-28]]

^<<v14-9-28,28>>^ And there were those bringing out horses to Solʹo·mon from Egypt and from all the other lands.

[[v14-9-29]]

^<<v14-9-29,29>>^ As for the rest of the affairs of Solʹo·mon, the first and the last, are they not written among the words of Nathan the prophet and in the prophecy of A·hiʹjah the Shiʹlo·nite and in the record of visions of Idʹdo^&#42;1^ the visionary concerning Jer·o·boʹam the son of Neʹbat?

[NOTE]
====
. Lit., “Jedi,” M; Mmargin, “Jedo.” See 12:15.
====

[[v14-9-30]]

^<<v14-9-30,30>>^ And Solʹo·mon continued to reign in Jerusalem over all Israel for forty years.

[[v14-9-31]]

^<<v14-9-31,31>>^ Finally Solʹo·mon lay down with his forefathers. So they buried him in the City of David his father; and Re·ho·boʹam his son began to reign in place of him.

'''

xref:014-2-chronicles/014-2-chronicles-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-010.adoc#v14-10-0[Próximo Capítulo &#62;]