include::./index.adoc[]

[[v14-25-0]]
=== The Second of Chronicles, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-25-1]]

^<<v14-25-1,1>>^ At the age of twenty-five years Am·a·ziʹah became king, and for twenty-nine years he reigned in Jerusalem. And his mother’s name was Je·ho·adʹdan of Jerusalem.

[[v14-25-2]]

^<<v14-25-2,2>>^ And he continued to do what was right in Jehovah’s eyes, only not with a complete heart.

[[v14-25-3]]

^<<v14-25-3,3>>^ And it came about that as soon as the kingdom had become strong upon him, he promptly killed his servants who had struck down the king his father.

[[v14-25-4]]

^<<v14-25-4,4>>^ And their sons he did not put to death, but &#91;did&#93; according to what is written in the law, in the book of Moses, that Jehovah commanded, saying: “Fathers should not die for sons, neither should sons themselves die for fathers; but it is each one for his own sin that they should die.”

[[v14-25-5]]

^<<v14-25-5,5>>^ And Am·a·ziʹah proceeded to collect Judah together and to have them stand according to the house of the forefathers, by the chiefs of thousands and by the chiefs of hundreds for all Judah and Benjamin; and he went on to register them from twenty years of age upward, and finally he found them &#91;to be&#93; three hundred thousand choice men going out to the army, handling lance and large shield.

[[v14-25-6]]

^<<v14-25-6,6>>^ Further, he hired from Israel a hundred thousand valiant, mighty men for a hundred silver talents.^&#42;1^

[NOTE]
====
. See App 8A.
====

[[v14-25-7]]

^<<v14-25-7,7>>^ And a certain man of the &#91;true&#93; God came to him, saying: “O king, do not let the army of Israel come with you, for Jehovah is not with Israel, &#91;that is,&#93; all the sons of Eʹphra·im.

[[v14-25-8]]

^<<v14-25-8,8>>^ But come you yourself, act, be courageous for the war. The &#91;true&#93; God could cause you to stumble before an enemy; for there exists power with God^&#42;1^ to help and to cause stumbling.”

[NOTE]
====
. “God,” MVg; LXX, “Jehovah.”
====

[[v14-25-9]]

^<<v14-25-9,9>>^ At this Am·a·ziʹah said to the man of the &#91;true&#93; God: “But what is there to do about the hundred talents that I have given to the troops of Israel?” To this the man of the &#91;true&#93; God said: “There exists with Jehovah the means to give you much more than this.”

[[v14-25-10]]

^<<v14-25-10,10>>^ Accordingly Am·a·ziʹah separated them, namely, the troops that had come to him from Eʹphra·im, to go to their own place. However, their anger got very hot against Judah, so that they returned to their own place in the heat of anger.

[[v14-25-11]]

^<<v14-25-11,11>>^ And Am·a·ziʹah, for his part, took courage and proceeded to lead his own people and go to the Valley of Salt; and he went striking down the sons of Seʹir, ten thousand &#91;of them&#93;.

[[v14-25-12]]

^<<v14-25-12,12>>^ And there were ten thousand that the sons of Judah captured alive. So they brought them to the top of the crag, and proceeded to throw them from the top of the crag; and they, one and all, burst apart.

[[v14-25-13]]

^<<v14-25-13,13>>^ As for the members of the troop whom Am·a·ziʹah had sent back from going with him to the war, they began making raids upon the cities of Judah, from Sa·marʹi·a clear to Beth-hoʹron, and went striking down three thousand of them and taking a great plunder.

[[v14-25-14]]

^<<v14-25-14,14>>^ But it occurred after Am·a·ziʹah came from striking down the Eʹdom·ites that he now brought the gods of the sons of Seʹir and set them up for himself as gods, and before them he began to bow down, and to them he began to make sacrificial smoke.

[[v14-25-15]]

^<<v14-25-15,15>>^ Consequently Jehovah’s anger became hot against Am·a·ziʹah, and so he sent a prophet to him and said to him: “Why have you searched for the people’s gods that did not deliver their own people out of your hand?”

[[v14-25-16]]

^<<v14-25-16,16>>^ And it came about when he spoke to him that &#91;the king&#93; immediately said to him: “Was it a counselor of the king that we constituted you? Quit for your own sake. Why should they strike you down?” Accordingly the prophet quit, but he said: “I certainly know that God has resolved to bring you to ruin, because you have done this and you have not listened to my counsel.”

[[v14-25-17]]

^<<v14-25-17,17>>^ Then Am·a·ziʹah the king of Judah took counsel and sent to Je·hoʹash the son of Je·hoʹa·haz the son of Jeʹhu the king of Israel, saying: “Come! Let us look each other in the face.”

[[v14-25-18]]

^<<v14-25-18,18>>^ At that Je·hoʹash the king of Israel sent to Am·a·ziʹah the king of Judah, saying: “The thorny weed itself that was in Lebʹa·non sent to the cedar that was in Lebʹa·non, saying, ‘Do give your daughter to my son as a wife.’ However, a wild beast of the field that was in Lebʹa·non passed by and trampled the thorny weed down.

[[v14-25-19]]

^<<v14-25-19,19>>^ You have said to yourself, Here you have struck down Eʹdom. And your heart has lifted you up to be glorified. Now do keep dwelling in your own house. Why should you engage in strife in a bad position and have to fall, you and Judah with you?”

[[v14-25-20]]

^<<v14-25-20,20>>^ But Am·a·ziʹah did not listen; for it was from the &#91;true&#93; God for the purpose of giving them into his hand, because they had searched for the gods of Eʹdom.

[[v14-25-21]]

^<<v14-25-21,21>>^ So Je·hoʹash the king of Israel went up, and they proceeded to look each other in the face, he and Am·a·ziʹah the king of Judah, at Beth-sheʹmesh, which belongs to Judah.

[[v14-25-22]]

^<<v14-25-22,22>>^ And Judah came to be defeated before Israel, so that they took to flight each one to his tent.^&#42;1^

[NOTE]
====
. Lit., “tents.”
====

[[v14-25-23]]

^<<v14-25-23,23>>^ And it was Am·a·ziʹah the king of Judah, the son of Je·hoʹash the son of Je·hoʹa·haz, that Je·hoʹash the king of Israel seized at Beth-sheʹmesh, after which he brought him to Jerusalem and made a breach in the wall of Jerusalem, from the Gate of Eʹphra·im clear to the Corner Gate, four hundred cubits.^&#42;1^

[NOTE]
====
. About 178 m (584 ft).
====

[[v14-25-24]]

^<<v14-25-24,24>>^ And &#91;he took&#93;^&#42;1^ all the gold and the silver and all the articles that were to be found in the house of the &#91;true&#93; God with Oʹbed-eʹdom and the treasures of the king’s house and the hostages, and then returned to Sa·marʹi·a.

[NOTE]
====
. “He took,” Sy; MLXXVg omit.
====

[[v14-25-25]]

^<<v14-25-25,25>>^ And Am·a·ziʹah the son of Je·hoʹash the king of Judah continued to live after the death of Je·hoʹash the son of Je·hoʹa·haz the king of Israel fifteen years.

[[v14-25-26]]

^<<v14-25-26,26>>^ As for the rest of the affairs of Am·a·ziʹah, the first and the last, look! are they not written in the Book of the Kings of Judah and Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ And from the time that Am·a·ziʹah turned aside from following Jehovah, they proceeded to form a conspiracy against him in Jerusalem. At length he fled to Laʹchish; but they sent after him to Laʹchish and put him to death there.

[[v14-25-28]]

^<<v14-25-28,28>>^ So they carried him upon horses and buried him with his forefathers in the city of Judah.^&#42;1^

[NOTE]
====
. “Judah,” M; LXXSyVg, 12 Heb. mss and 2Ki 14:20, “David.”
====

'''

xref:014-2-chronicles/014-2-chronicles-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-026.adoc#v14-26-0[Próximo Capítulo &#62;]