include::./index.adoc[]

[[v14-20-0]]
=== The Second of Chronicles, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-20-1]]

^<<v14-20-1,1>>^ And it came about afterward that the sons of Moʹab and the sons of Amʹmon and with them some of the Amʹmon·im^&#42;1^ came against Je·hoshʹa·phat in war.

[NOTE]
====
. Lit., “from the Ammonim.” Heb., me·ha·ʽAm·moh·nimʹ; by a transposition of letters in M, “the Meunim; Meunites”; LXX, “the Minaians”; Vgc, “the Ammonites.”
====

[[v14-20-2]]

^<<v14-20-2,2>>^ So people came and told Je·hoshʹa·phat, saying: “There has come against you a large crowd from the region of the sea,^&#42;1^ from Eʹdom;^&#42;2^ and there they are in Hazʹa·zon-taʹmar, that is to say, En-geʹdi.”

[NOTE]
====
. That is, the Red Sea.
. “From Edom,” one Heb. ms; Heb., me·ʼAramʹ, “from Syria”; Gr., Sy·riʹas; Lat., Syʹri·a; Sy, “the Red Sea.”
====

[[v14-20-3]]

^<<v14-20-3,3>>^ At that Je·hoshʹa·phat became afraid and set his face to search for Jehovah. So he proclaimed a fast for all Judah.

[[v14-20-4]]

^<<v14-20-4,4>>^ Eventually those of Judah were collected together to inquire of Jehovah. Even from all the cities of Judah they came to consult Jehovah.

[[v14-20-5]]

^<<v14-20-5,5>>^ Then Je·hoshʹa·phat stood up in the congregation^&#42;1^ of Judah and of Jerusalem in the house of Jehovah before the new courtyard,

[NOTE]
====
. “In the congregation of.” Heb., biq·halʹ; Gr., ek·kle·siʹai.
====

[[v14-20-6]]

^<<v14-20-6,6>>^ and he proceeded to say:
“O Jehovah the God of our forefathers, are you not God in the heavens, and are you not dominating over all the kingdoms of the nations, and are there not in your hand power and mightiness, with no one to hold his ground against you?

[[v14-20-7]]

^<<v14-20-7,7>>^ Did not you yourself, O God of ours, drive away the inhabitants of this land from before your people Israel and then give it to the seed of Abraham, your lover,^&#42;1^ to time indefinite?

[NOTE]
====
. Or, “friend.” Lat., a·miʹci.
====

[[v14-20-8]]

^<<v14-20-8,8>>^ And they took up dwelling in it, and they proceeded to build in it for you a sanctuary for your name, saying,

[[v14-20-9]]

^<<v14-20-9,9>>^ ‘If there should come upon us calamity, sword, adverse judgment, or pestilence or famine, let us stand before this house and before you (for your name is in this house), that we may call to you for aid out of our distress, and may you hear and save.’

[[v14-20-10]]

^<<v14-20-10,10>>^ And now here the sons of Amʹmon, and Moʹab and the mountainous region of Seʹir, whom you did not allow Israel to invade when they were coming out of the land of Egypt, but they turned away from them and did not annihilate them,

[[v14-20-11]]

^<<v14-20-11,11>>^ yes, here they are rewarding us by coming in to drive us out from your possession that you caused us to possess.

[[v14-20-12]]

^<<v14-20-12,12>>^ O our God, will you not execute judgment upon them? For in us there is no power before this large crowd that is coming against us; and we ourselves do not know what we ought to do, but our eyes are toward you.”

[[v14-20-13]]

^<<v14-20-13,13>>^ All the while all those of Judah were standing before Jehovah, even their little ones, their wives and their sons.

[[v14-20-14]]

^<<v14-20-14,14>>^ Now as for Ja·ha·ziʹel the son of Zech·a·riʹah the son of Be·naiʹah the son of Je·iʹel the son of Mat·ta·niʹah the Levite of the sons of Aʹsaph, the spirit of Jehovah came to be upon him in the middle of the congregation.

[[v14-20-15]]

^<<v14-20-15,15>>^ Consequently he said: “Pay attention, all Judah and YOU inhabitants of Jerusalem and King Je·hoshʹa·phat! Here is what Jehovah has said to YOU, ‘Do not YOU be afraid or be terrified because of this large crowd; for the battle is not YOURS, but God’s.

[[v14-20-16]]

^<<v14-20-16,16>>^ Tomorrow go down against them. There they are coming up by the pass of Ziz; and YOU will be certain to find them at the end of the torrent valley in front of the wilderness of Je·ruʹel.

[[v14-20-17]]

^<<v14-20-17,17>>^ YOU will not need to fight in this instance. Take YOUR position, stand still and see the salvation of Jehovah in YOUR behalf. O Judah and Jerusalem, do not be afraid or be terrified. Tomorrow go out against^&#42;1^ them, and Jehovah will be with YOU.’”

[NOTE]
====
. Or, “before.” See Ge 10:9 ftn, “Opposition to.”
====

[[v14-20-18]]

^<<v14-20-18,18>>^ At once Je·hoshʹa·phat bowed low with his face to the earth, and all Judah and the inhabitants of Jerusalem themselves fell down before Jehovah to do obeisance to Jehovah.

[[v14-20-19]]

^<<v14-20-19,19>>^ Then the Levites of the sons of the Koʹhath·ites and of the sons of the Koʹrah·ites rose up to praise Jehovah the God of Israel with an extraordinarily loud voice.

[[v14-20-20]]

^<<v14-20-20,20>>^ And they proceeded to rise early in the morning and go out to the wilderness of Te·koʹa. And as they went out, Je·hoshʹa·phat stood up and then said: “Hear me, O Judah and YOU inhabitants of Jerusalem! Put faith in Jehovah YOUR God that YOU may prove yourselves of long duration. Put faith in his prophets and so prove successful.”

[[v14-20-21]]

^<<v14-20-21,21>>^ Further, he took counsel with the people and stationed singers to Jehovah and those offering praise in holy adornment as they went out ahead of the armed men, and saying: “GIVE praise to Jehovah, for to time indefinite is his loving-kindness.”^&#42;1^

[NOTE]
====
. Or, “loyal love.”
====

[[v14-20-22]]

^<<v14-20-22,22>>^ And at the time that they started off with the joyful cry and praise, Jehovah set men in ambush against the sons of Amʹmon, Moʹab and the mountainous region of Seʹir who were coming into Judah, and they went smiting one another.

[[v14-20-23]]

^<<v14-20-23,23>>^ And the sons of Amʹmon and Moʹab proceeded to stand up against the inhabitants of the mountainous region of Seʹir to devote them to destruction and annihilate them; and as soon as they finished with the inhabitants of Seʹir, they helped each one to bring his own fellow to ruin.

[[v14-20-24]]

^<<v14-20-24,24>>^ But as for Judah, it came to the watchtower of the wilderness. When they turned their faces toward the crowd, why, there they were, their carcasses fallen to the earth without anyone escaping.

[[v14-20-25]]

^<<v14-20-25,25>>^ So Je·hoshʹa·phat and his people came to plunder the spoil on them, and they got to find among them in abundance both goods and clothing^&#42;1^ and desirable articles; and they went stripping them off for themselves until they could carry no more. And it came to be three days that they were plundering the spoil, for it was abundant.

[NOTE]
====
. “Clothing,” Vg and seven Heb. mss; M, “carcasses.”
====

[[v14-20-26]]

^<<v14-20-26,26>>^ And on the fourth day they congregated together at the low plain of Berʹa·cah, for there they blessed Jehovah. That is why they called the name of that place Low Plain of Berʹa·cah^&#42;1^—until today.

[NOTE]
====
. Meaning “Blessing.”
====

[[v14-20-27]]

^<<v14-20-27,27>>^ Then all the men of Judah and Jerusalem returned, with Je·hoshʹa·phat at their head, to return to Jerusalem with rejoicing, for Jehovah had made them rejoice over their enemies.

[[v14-20-28]]

^<<v14-20-28,28>>^ So they came to Jerusalem with stringed instruments and with harps and with trumpets to the house of Jehovah.

[[v14-20-29]]

^<<v14-20-29,29>>^ And the dread of God came to be upon all the kingdoms of the lands when they heard that Jehovah had fought against the enemies of Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ Thus the royal realm of Je·hoshʹa·phat had no disturbance, and his God continued to give him rest all around.

[[v14-20-31]]

^<<v14-20-31,31>>^ And Je·hoshʹa·phat went on reigning over Judah. Thirty-five years old he was when he began to reign, and for twenty-five years he reigned in Jerusalem. And his mother’s name was A·zuʹbah the daughter of Shilʹhi.

[[v14-20-32]]

^<<v14-20-32,32>>^ And he kept walking in the way of his father Aʹsa, and he did not turn aside from it, by doing what was right in Jehovah’s eyes.

[[v14-20-33]]

^<<v14-20-33,33>>^ Only the high places themselves did not disappear; and the people themselves had not yet prepared their heart for the God of their forefathers.

[[v14-20-34]]

^<<v14-20-34,34>>^ As for the rest of the affairs of Je·hoshʹa·phat, the first and the last, there they are written among the words of Jeʹhu the son of Ha·naʹni, which were inserted in the Book of the Kings of Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ And after this Je·hoshʹa·phat the king of Judah had partnership with A·ha·ziʹah the king of Israel, who acted wickedly.

[[v14-20-36]]

^<<v14-20-36,36>>^ So he made him a partner with himself in making ships to go to Tarʹshish and they made ships in Eʹzi·on-geʹber.

[[v14-20-37]]

^<<v14-20-37,37>>^ However, E·li·eʹzer the son of Dod·avʹa·hu of Ma·reʹsha spoke prophetically against Je·hoshʹa·phat, saying: “Inasmuch as you have had partnership with A·ha·ziʹah, Jehovah will certainly break down your works.” Accordingly the ships were wrecked, and they did not retain strength to go to Tarʹshish.

'''

xref:014-2-chronicles/014-2-chronicles-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-021.adoc#v14-21-0[Próximo Capítulo &#62;]