include::./index.adoc[]

[[v14-7-0]]
=== The Second of Chronicles, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-7-1]]

^<<v14-7-1,1>>^ Now as soon as Solʹo·mon finished praying, the fire itself came down from the heavens and proceeded to consume the burnt offering and the sacrifices, and Jehovah’s glory itself filled the house.

[[v14-7-2]]

^<<v14-7-2,2>>^ And the priests were unable to enter into the house of Jehovah because Jehovah’s glory had filled the house of Jehovah.

[[v14-7-3]]

^<<v14-7-3,3>>^ And all the sons of Israel were spectators when the fire came down and the glory of Jehovah was upon the house, and they immediately bowed low with their faces to the earth upon the pavement and prostrated themselves and thanked Jehovah, “for he is good, for his loving-kindness is to time indefinite.”

[[v14-7-4]]

^<<v14-7-4,4>>^ And the king and all the people were offering sacrifice before Jehovah.

[[v14-7-5]]

^<<v14-7-5,5>>^ And King Solʹo·mon went on offering the sacrifice of twenty-two thousand cattle and a hundred and twenty thousand sheep. Thus the king and all the people inaugurated the house of the &#91;true&#93; God.

[[v14-7-6]]

^<<v14-7-6,6>>^ And the priests were standing at their posts of duty, and the Levites with the instruments of song to Jehovah that David the king had made to thank Jehovah, “for his loving-kindness is to time indefinite,” when David would render praise by their hand; and the priests were loudly sounding the trumpets in front of them, while all the Israelites were standing.

[[v14-7-7]]

^<<v14-7-7,7>>^ Then Solʹo·mon sanctified the middle of the courtyard that was before the house of Jehovah, because there he rendered up the burnt offerings and the fat pieces of the communion sacrifices, for the copper altar that Solʹo·mon had made was itself not able to contain the burnt offering and the grain offering and the fat pieces.

[[v14-7-8]]

^<<v14-7-8,8>>^ And Solʹo·mon proceeded to hold the festival at that time for seven days, and all Israel with him, a very great congregation^&#42;1^ from the entering in of Haʹmath down to the torrent valley of Egypt.

[NOTE]
====
. “Congregation.” Heb., qa·halʹ; Gr., ek·kle·siʹa; Lat., ec·cleʹsi·a.
====

[[v14-7-9]]

^<<v14-7-9,9>>^ But on the eighth day they held a solemn assembly, because the inauguration of the altar they had held for seven days and the festival for seven days.

[[v14-7-10]]

^<<v14-7-10,10>>^ And on the twenty-third day of the seventh month he sent the people away to their homes, joyful and feeling good at heart over the goodness that Jehovah had performed toward David and toward Solʹo·mon and toward Israel his people.

[[v14-7-11]]

^<<v14-7-11,11>>^ Thus Solʹo·mon finished the house of Jehovah and the house of the king; and in everything that had come into Solʹo·mon’s heart to do regarding the house of Jehovah and his own house he proved successful.

[[v14-7-12]]

^<<v14-7-12,12>>^ Jehovah now appeared to Solʹo·mon during the night and said to him: “I have heard your prayer, and I have chosen this place for myself as a house of sacrifice.

[[v14-7-13]]

^<<v14-7-13,13>>^ When I shut up the heavens that no rain may occur and when I command the grasshoppers to eat up the land and if I send a pestilence among my people,

[[v14-7-14]]

^<<v14-7-14,14>>^ and my people upon whom my name has been called humble themselves and pray and seek my face and turn back from their bad ways, then I myself shall hear from the heavens and forgive their sin, and I shall heal their land.

[[v14-7-15]]

^<<v14-7-15,15>>^ Now my own eyes will prove to be opened and my ears attentive to prayer at this place.

[[v14-7-16]]

^<<v14-7-16,16>>^ And now I do choose and sanctify this house that my name may prove to be there to time indefinite, and my eyes and my heart will certainly prove to be there always.

[[v14-7-17]]

^<<v14-7-17,17>>^ “And if you yourself will walk before me, just as David your father walked, even by doing according to all that I have commanded you, and you will keep my regulations and my judicial decisions,

[[v14-7-18]]

^<<v14-7-18,18>>^ I will also establish the throne of your kingship, just as I covenanted with David your father, saying, ‘There will not a man of yours be cut off from ruling over Israel.’

[[v14-7-19]]

^<<v14-7-19,19>>^ But if YOU yourselves turn back and actually leave my statutes and my commandments that I have put before YOU, and YOU actually go and serve other gods and bow down to them,

[[v14-7-20]]

^<<v14-7-20,20>>^ I will also uproot them from off my ground that I have given them; and this house that I have sanctified for my name, I shall throw away from before my face, and I shall make it a proverbial saying and a taunt among all the peoples.

[[v14-7-21]]

^<<v14-7-21,21>>^ As for this house that had become heaps of ruins,^&#42;1^ everyone passing by it will stare in amazement and be certain to say, ‘For what reason did Jehovah do like that to this land and to this house?’

[NOTE]
====
. See 1Ki 9:8 ftn.
====

[[v14-7-22]]

^<<v14-7-22,22>>^ And they will have to say, ‘It was for the reason that they left Jehovah the God of their forefathers who had brought them out of the land of Egypt, and they proceeded to take hold of other gods and bow down to them and serve them. That is why he brought upon them all this calamity.’”

'''

xref:014-2-chronicles/014-2-chronicles-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-008.adoc#v14-8-0[Próximo Capítulo &#62;]