include::./index.adoc[]

[[v14-23-0]]
=== The Second of Chronicles, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-23-1]]

^<<v14-23-1,1>>^ And in the seventh year Je·hoiʹa·da showed himself courageous and proceeded to take the chiefs of hundreds, namely, Az·a·riʹah the son of Je·roʹham, and Ishʹma·el the son of Je·ho·haʹnan and Az·a·riʹah the son of Oʹbed and Ma·a·seiʹah the son of A·daiʹah and E·li·shaʹphat the son of Zichʹri, with him into the covenant.

[[v14-23-2]]

^<<v14-23-2,2>>^ Afterward they went around throughout Judah and collected together the Levites from all the cities of Judah and the heads of the paternal houses of Israel. So they came to Jerusalem.

[[v14-23-3]]

^<<v14-23-3,3>>^ Then all the congregation concluded a covenant with the king in the house of the &#91;true&#93; God, after which he said to them:
“Look! The son of the king himself will reign, just as Jehovah promised concerning the sons of David.

[[v14-23-4]]

^<<v14-23-4,4>>^ This is the thing that YOU will do: one third of YOU who are coming in on the sabbath, of the priests and of the Levites, will be for doorkeepers;

[[v14-23-5]]

^<<v14-23-5,5>>^ and one third will be at the house of the king; and one third will be at the Gate of the Foundation; and all the people will be in the courtyards of the house of Jehovah.

[[v14-23-6]]

^<<v14-23-6,6>>^ And do not let anyone enter the house of Jehovah but the priests and those of the Levites ministering. These are the ones that will enter, because they are a holy group, and all the people themselves will keep the obligation to Jehovah.

[[v14-23-7]]

^<<v14-23-7,7>>^ And the Levites must encircle the king all around, each one with his weapons in his hands; and as for anyone coming into the house, he should be put to death. And continue with the king when he comes in and when he goes out.”

[[v14-23-8]]

^<<v14-23-8,8>>^ And the Levites and all Judah proceeded to do according to all that Je·hoiʹa·da the priest had commanded. So they took each one his men that were coming in on the sabbath together with those going out on the sabbath, for Je·hoiʹa·da the priest had not set the divisions free from duty.

[[v14-23-9]]

^<<v14-23-9,9>>^ Further, Je·hoiʹa·da the priest gave the chiefs of hundreds the spears and the shields and the circular shields that had belonged to King David, which were in the house of the &#91;true&#93; God.

[[v14-23-10]]

^<<v14-23-10,10>>^ And he went on to station all the people, even each one with his missile in his hand, from the right side of the house clear to the left side of the house, by the altar and by the house, all around near the king.

[[v14-23-11]]

^<<v14-23-11,11>>^ Then they brought the king’s son out and put upon him the diadem and the Testimony and made him king, and so Je·hoiʹa·da and his sons anointed him and said: “Let the king live!”

[[v14-23-12]]

^<<v14-23-12,12>>^ When Ath·a·liʹah heard the sound of the people running and praising the king, she at once came to the people at the house of Jehovah.

[[v14-23-13]]

^<<v14-23-13,13>>^ Then she saw, and there was the king standing by his pillar^&#42;1^ at the entry, and the princes and the trumpets by the king, and all the people of the land were rejoicing and blowing the trumpets, and the singers with the instruments of song and those giving the signal for offering praise. Immediately Ath·a·liʹah ripped her garments apart and said: “Conspiracy! Conspiracy!”

[NOTE]
====
. Possibly, “his standing place.”
====

[[v14-23-14]]

^<<v14-23-14,14>>^ But Je·hoiʹa·da the priest brought out the chiefs of hundreds, the appointed ones of the military force, and said to them: “Take her out from inside the rows; and as for anyone coming after her, he should be put to death with the sword!” For the priest had said: “YOU must not put her to death at the house of Jehovah.”

[[v14-23-15]]

^<<v14-23-15,15>>^ So they laid their hands upon her. When she came to the entry of the horse gate of the king’s house, they at once put her to death there.

[[v14-23-16]]

^<<v14-23-16,16>>^ Then Je·hoiʹa·da concluded a covenant between himself^&#42;1^ and all the people and the king that they would continue as the people of Jehovah.

[NOTE]
====
. “Jehovah” in 2Ki 11:17.
====

[[v14-23-17]]

^<<v14-23-17,17>>^ After that all the people came to the house of Baʹal and pulled it down; and his altars and his images they broke up, and Matʹtan the priest of Baʹal they killed before the altars.

[[v14-23-18]]

^<<v14-23-18,18>>^ Further, Je·hoiʹa·da put the offices of the house of Jehovah in the hand of the priests &#91;and&#93; the Levites,^&#42;1^ whom David had put in divisions over the house of Jehovah to offer up the burnt sacrifices of Jehovah according to what is written in the law of Moses, with rejoicing and with song by the hands of David.

[NOTE]
====
. “The priests and the Levites,” LXXSyVg and some Heb. mss; M, “the priests, the Levites.”
====

[[v14-23-19]]

^<<v14-23-19,19>>^ So he stationed the gatekeepers by the gates of the house of Jehovah that no one unclean in any respect might enter.

[[v14-23-20]]

^<<v14-23-20,20>>^ He now took the chiefs of hundreds and the lordly ones and the rulers over the people and all the people of the land and brought the king down from the house of Jehovah. Then they came right through the upper gate to the king’s house and seated the king upon the throne of the kingdom.

[[v14-23-21]]

^<<v14-23-21,21>>^ And all the people of the land continued to rejoice; and the city itself had no disturbance, and Ath·a·liʹah they had put to death with the sword.

'''

xref:014-2-chronicles/014-2-chronicles-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-024.adoc#v14-24-0[Próximo Capítulo &#62;]