include::./index.adoc[]

[[v14-18-0]]
=== The Second of Chronicles, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-18-1]]

^<<v14-18-1,1>>^ And Je·hoshʹa·phat came to have riches and glory in abundance; but he formed a marriage alliance with Aʹhab.

[[v14-18-2]]

^<<v14-18-2,2>>^ So years later he went down to Aʹhab at Sa·marʹi·a; and Aʹhab proceeded to sacrifice sheep and cattle in abundance for him and for the people that were with him. And he began to allure him to go up against Raʹmoth-gilʹe·ad.

[[v14-18-3]]

^<<v14-18-3,3>>^ And Aʹhab the king of Israel went on to say to Je·hoshʹa·phat the king of Judah: “Will you go with me to Raʹmoth-gilʹe·ad?” At this he said to him: “I am the same as you are, and my people are like your people and with you in the war.”

[[v14-18-4]]

^<<v14-18-4,4>>^ However, Je·hoshʹa·phat said to the king of Israel: “Please, inquire first of all for the word of Jehovah.”

[[v14-18-5]]

^<<v14-18-5,5>>^ So the king of Israel collected the prophets together, four hundred men, and said to them: “Shall we go against Raʹmoth-gilʹe·ad in war, or shall I refrain?” And they began to say: “Go up, and the &#91;true&#93; God will give &#91;it&#93; into the king’s hand.”

[[v14-18-6]]

^<<v14-18-6,6>>^ But Je·hoshʹa·phat said: “Is there not here a prophet of Jehovah still? Then let us inquire through him.”

[[v14-18-7]]

^<<v14-18-7,7>>^ At that the king of Israel said to Je·hoshʹa·phat: “There is still one man through whom to inquire of Jehovah, but I myself certainly hate him, for he is prophesying concerning me, not for good, but, all his days, for bad. He is Mi·caiʹah^&#42;1^ the son of Imʹlah.” However, Je·hoshʹa·phat said: “Do not let the king say a thing like that.”

[NOTE]
====
. See 1Ki 22:8 ftn.
====

[[v14-18-8]]

^<<v14-18-8,8>>^ Accordingly the king of Israel called a court official and said: “Bring Mi·caiʹah the son of Imʹlah quickly.”

[[v14-18-9]]

^<<v14-18-9,9>>^ Now the king of Israel and Je·hoshʹa·phat the king of Judah were sitting each one on his throne, clothed in garments, and were sitting in the threshing floor at the entrance of the gate of Sa·marʹi·a; and all the prophets were acting as prophets before them.

[[v14-18-10]]

^<<v14-18-10,10>>^ Then Zed·e·kiʹah the son of Che·naʹa·nah made for himself horns of iron and said: “This is what Jehovah has said, ‘With these you will push the Syrians until you exterminate them.’”

[[v14-18-11]]

^<<v14-18-11,11>>^ And all the other prophets were prophesying the same as that, saying: “Go up to Raʹmoth-gilʹe·ad and prove successful, and Jehovah will certainly give &#91;it&#93; into the king’s hand.”

[[v14-18-12]]

^<<v14-18-12,12>>^ And the messenger that went to call Mi·caiʹah spoke to him, saying: “Look! The words of the prophets are unanimously^&#42;1^ of good to the king; and let your word, please, become like one of them and you must speak good.”

[NOTE]
====
. Lit., “one mouth.”
====

[[v14-18-13]]

^<<v14-18-13,13>>^ But Mi·caiʹah^&#42;1^ said: “As Jehovah is living, what my God will say, that is what I shall speak.”

[NOTE]
====
. Heb., Mi·khaʹyehu. See Mic Title ftn.
====

[[v14-18-14]]

^<<v14-18-14,14>>^ Then he came in to the king, and the king proceeded to say to him: “Mi·caiʹah,^&#42;1^ shall we go to Raʹmoth-gilʹe·ad in war, or shall I refrain?” At once he said: “Go up and prove successful; and they will be given into YOUR hand.”

[NOTE]
====
. Lit., “Micah.”
====

[[v14-18-15]]

^<<v14-18-15,15>>^ At that the king said to him: “For how many times am I putting you under oath that you should not speak to me anything but truth in the name of Jehovah?”

[[v14-18-16]]

^<<v14-18-16,16>>^ So he said: “I certainly see all the Israelites scattered upon the mountains, like sheep that have no shepherd. And Jehovah went on to say: ‘These have no masters. Let them go back each one to his house in peace.’”

[[v14-18-17]]

^<<v14-18-17,17>>^ Then the king of Israel said to Je·hoshʹa·phat: “Did I not say to you, ‘He will prophesy concerning me, not good things, but bad’?”

[[v14-18-18]]

^<<v14-18-18,18>>^ And he went on to say: “Therefore HEAR the word of Jehovah: I certainly see Jehovah sitting upon his throne and all the army of the heavens standing at his right and his left.

[[v14-18-19]]

^<<v14-18-19,19>>^ And Jehovah proceeded to say, ‘Who will fool Aʹhab the king of Israel that he may go up and fall at Raʹmoth-gilʹe·ad?’ And there was talk, this one saying something like this, and that one saying something like that.

[[v14-18-20]]

^<<v14-18-20,20>>^ Finally a spirit came out and stood before Jehovah and said, ‘I myself shall fool him.’ At that Jehovah said to him, ‘By what means?’

[[v14-18-21]]

^<<v14-18-21,21>>^ To this he said, ‘I shall go forth and certainly become a deceptive spirit in the mouth of all his prophets.’ So he said, ‘You will fool him, and, what is more, you will come off the winner. Go out and do that way.’

[[v14-18-22]]

^<<v14-18-22,22>>^ And now here Jehovah has put a deceptive spirit in the mouth of these prophets of yours; but Jehovah himself has spoken calamity concerning you.”

[[v14-18-23]]

^<<v14-18-23,23>>^ Zed·e·kiʹah the son of Che·naʹa·nah now approached and struck Mi·caiʹah on the cheek and said: “In just which way did the spirit of Jehovah pass along from me to speak with you?”

[[v14-18-24]]

^<<v14-18-24,24>>^ At that Mi·caiʹah said: “Look! You are seeing &#91;which way&#93; on that day when you will enter the innermost chamber to hide yourself.”

[[v14-18-25]]

^<<v14-18-25,25>>^ Then the king of Israel said: “TAKE Mi·caiʹah and turn him back to Aʹmon the chief of the city and to Joʹash the king’s son.

[[v14-18-26]]

^<<v14-18-26,26>>^ And YOU men must say, ‘This is what the king has said: “PUT this fellow in the house of detention and feed him with a reduced allowance of bread and a reduced allowance of water until I return in peace.”’”

[[v14-18-27]]

^<<v14-18-27,27>>^ Upon that Mi·caiʹah said: “If you return at all in peace, Jehovah has not spoken with^&#42;1^ me.” And he added: “Hear, all YOU peoples.”

[NOTE]
====
. Or, “by.”
====

[[v14-18-28]]

^<<v14-18-28,28>>^ And the king of Israel and Je·hoshʹa·phat the king of Judah proceeded to go up to Raʹmoth-gilʹe·ad.

[[v14-18-29]]

^<<v14-18-29,29>>^ The king of Israel now said to Je·hoshʹa·phat: “There will be a disguising and entering^&#42;1^ into the battle &#91;for me&#93;, but you, for your part, put on your garments.” Accordingly the king of Israel disguised himself, after which they entered into the battle.

[NOTE]
====
. “There will be a disguising and entering,” that is, on Ahab’s part. In Heb. these are verbs, understood to be in the infinitive absolute, indefinite as to time and impersonal.
====

[[v14-18-30]]

^<<v14-18-30,30>>^ As for the king of Syria, he had commanded the chiefs of the chariots that were his, saying: “YOU must fight, neither with the small nor with the great, but with the king of Israel alone.”

[[v14-18-31]]

^<<v14-18-31,31>>^ And it came about that, as soon as the chiefs of the chariots saw Je·hoshʹa·phat, they, for their part, said to themselves: “It is the king of Israel.” So they turned around against him to fight; and Je·hoshʹa·phat began to cry for aid, and Jehovah himself helped him, and God at once allured them away from him.

[[v14-18-32]]

^<<v14-18-32,32>>^ And it came about that as soon as the chiefs of the chariots saw that it did not prove to be the king of Israel, they immediately came back from following him.

[[v14-18-33]]

^<<v14-18-33,33>>^ And there was a man that bent the bow in his innocence, but he got to strike the king of Israel between the appendages and the coat of mail, so that he said to the charioteer: “Turn your hand around, and you must take me out from the camp, because I have been badly wounded.”

[[v14-18-34]]

^<<v14-18-34,34>>^ And the battle kept rising in intensity on that day, and the king of Israel himself had to be kept in a standing position in the chariot facing the Syrians until the evening; and gradually he died at the time of the setting of the sun.

'''

xref:014-2-chronicles/014-2-chronicles-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-019.adoc#v14-19-0[Próximo Capítulo &#62;]