include::./index.adoc[]

[[v14-29-0]]
=== The Second of Chronicles, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-29-1]]

^<<v14-29-1,1>>^ Hez·e·kiʹah^&#42;1^ himself became king at the age of twenty-five years, and for twenty-nine years he reigned in Jerusalem. And his mother’s name was A·biʹjah the daughter of Zech·a·riʹah.

[NOTE]
====
. See 2Ki 20:10 ftn.
====

[[v14-29-2]]

^<<v14-29-2,2>>^ And he kept doing what was right in Jehovah’s eyes, according to all that David his forefather had done.

[[v14-29-3]]

^<<v14-29-3,3>>^ He himself, in the first year of his reigning, in the first month, opened the doors of the house of Jehovah and began to repair them.

[[v14-29-4]]

^<<v14-29-4,4>>^ Then he brought the priests and the Levites and gathered them to the open place to the east.

[[v14-29-5]]

^<<v14-29-5,5>>^ And he proceeded to say to them: “Listen to me, YOU Levites. Now sanctify yourselves and sanctify the house of Jehovah the God of YOUR forefathers, and bring the impure thing out from the holy place.

[[v14-29-6]]

^<<v14-29-6,6>>^ For our fathers have acted unfaithfully and have done what was bad in the eyes of Jehovah our God, so that they left him and turned around their face away from the tabernacle of Jehovah and offered the back of the neck.

[[v14-29-7]]

^<<v14-29-7,7>>^ They also closed the doors of the porch and kept the lamps extinguished, and incense they did not burn, and burnt sacrifice they did not offer up in the holy place to the God of Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ And Jehovah’s indignation came to be against Judah and Jerusalem, so that he constituted them an object at which to quake, an object of astonishment and a cause for whistling, just as YOU are seeing with YOUR own eyes.

[[v14-29-9]]

^<<v14-29-9,9>>^ And here our forefathers fell by the sword, and our sons and our daughters and our wives were in captivity for this.

[[v14-29-10]]

^<<v14-29-10,10>>^ Now it is close to my heart to conclude a covenant with Jehovah the God of Israel, that his burning anger may turn back from us.

[[v14-29-11]]

^<<v14-29-11,11>>^ Now, my sons, do not give yourselves up to rest, for YOU are the ones whom Jehovah has chosen to stand before him to minister to him and to continue as his ministers and makers of sacrificial smoke.”

[[v14-29-12]]

^<<v14-29-12,12>>^ At that the Levites rose up, Maʹhath the son of A·maʹsai and Joel the son of Az·a·riʹah of the sons of the Koʹhath·ites; and from the sons of Me·rarʹi, Kish the son of Abʹdi and Az·a·riʹah the son of Je·halʹle·lel; and from the Gerʹshon·ites, Joʹah the son of Zimʹmah and Eʹden the son of Joʹah;

[[v14-29-13]]

^<<v14-29-13,13>>^ and from the sons of E·li·zaʹphan, Shimʹri and Je·uʹel; and from the sons of Aʹsaph, Zech·a·riʹah and Mat·ta·niʹah;

[[v14-29-14]]

^<<v14-29-14,14>>^ and from the sons of Heʹman, Je·hiʹel and Shimʹe·i; and from the sons of Je·duʹthun, She·maiʹah and Uzʹzi·el.

[[v14-29-15]]

^<<v14-29-15,15>>^ Then they gathered their brothers together and sanctified themselves and came according to the king’s commandment in the words of Jehovah, to cleanse the house of Jehovah.

[[v14-29-16]]

^<<v14-29-16,16>>^ The priests now came inside the house of Jehovah to do the cleansing and brought out all the uncleanness that they found in the temple of Jehovah to the courtyard of the house of Jehovah. In turn the Levites received it to take it out to the torrent valley of Kidʹron outside.

[[v14-29-17]]

^<<v14-29-17,17>>^ Thus they got started on the first &#91;day&#93; of the first month at sanctifying, and on the eighth day of the month they came to the porch of Jehovah; so that they sanctified the house of Jehovah in eight days, and on the sixteenth day of the first month they finished.

[[v14-29-18]]

^<<v14-29-18,18>>^ After that they came inside to Hez·e·kiʹah the king and said: “We have cleansed the whole house of Jehovah, the altar of burnt offering and all its utensils, and the table of the layer bread and all its utensils.

[[v14-29-19]]

^<<v14-29-19,19>>^ And all the utensils that King Aʹhaz removed from employment during his reign in his unfaithfulness^&#42;1^ we have prepared, and have sanctified them; and there they are before the altar of Jehovah.”

[NOTE]
====
. “Unfaithfulness,” M; Gr., a·po·sta·siʹai, “apostasy,” from the verb a·phiʹste·mi, “stand away from”; the noun has the sense of desertion, abandonment or rebellion. See Jos 22:22; Ac 21:21; 2Th 2:3 ftns.
====

[[v14-29-20]]

^<<v14-29-20,20>>^ And Hez·e·kiʹah the king proceeded to get up early and gather the princes of the city together and go up to the house of Jehovah.

[[v14-29-21]]

^<<v14-29-21,21>>^ And they came bringing seven bulls and seven rams and seven male lambs and seven male goats as a sin offering for the kingdom and for the sanctuary and for Judah. So he said to the sons of Aaron the priests to offer them up upon the altar of Jehovah.

[[v14-29-22]]

^<<v14-29-22,22>>^ Accordingly they slaughtered the cattle and the priests received the blood and sprinkled it upon the altar; after which they slaughtered the rams and sprinkled the blood upon the altar, and they slaughtered the male lambs and sprinkled the blood upon the altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Then they brought the male goats of the sin offering near before the king and the congregation and laid their hands upon them.

[[v14-29-24]]

^<<v14-29-24,24>>^ The priests now slaughtered them and made a sin offering with their blood upon the altar, to make atonement for all Israel; because it was for all Israel that the king said the burnt offering and the sin offering &#91;should be&#93;.

[[v14-29-25]]

^<<v14-29-25,25>>^ Meantime, he had the Levites stationed at the house of Jehovah, with cymbals, with stringed instruments and with harps, by the commandment of David and of Gad the king’s visionary and of Nathan the prophet, for it was by the hand of Jehovah that the commandment was by means of his prophets.

[[v14-29-26]]

^<<v14-29-26,26>>^ So the Levites kept standing with the instruments of David, and also the priests with the trumpets.

[[v14-29-27]]

^<<v14-29-27,27>>^ Then Hez·e·kiʹah said to offer up the burnt sacrifice on the altar; and at the time that the burnt offering started, the song of Jehovah started and also the trumpets, even under the direction of the instruments of David the king of Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ And all the congregation^&#42;1^ were bowing down while the song was resounding and the trumpets were blaring—all this until the burnt offering was finished.

[NOTE]
====
. “The congregation.” Heb., haq·qa·halʹ; Gr., he ek·kle·siʹa.
====

[[v14-29-29]]

^<<v14-29-29,29>>^ And as soon as they finished offering it up, the king and all those found with him bowed low and prostrated themselves.

[[v14-29-30]]

^<<v14-29-30,30>>^ Hez·e·kiʹah the king and the princes now said to the Levites to praise Jehovah in the words of David and of Aʹsaph the visionary. So they began to offer praise even with rejoicing, and they kept bending down and prostrating themselves.

[[v14-29-31]]

^<<v14-29-31,31>>^ Finally Hez·e·kiʹah answered and said: “Now YOU have filled YOUR hand with power for Jehovah. Approach, and bring sacrifices and thanksgiving sacrifices to the house of Jehovah.” And the congregation began to bring sacrifices and thanksgiving sacrifices, and also every one willing of heart, burnt offerings.

[[v14-29-32]]

^<<v14-29-32,32>>^ And the number of the burnt offerings that the congregation brought came to be seventy cattle, a hundred rams, two hundred male lambs—all these as a burnt offering to Jehovah;

[[v14-29-33]]

^<<v14-29-33,33>>^ and also the holy offerings, six hundred cattle and three thousand of the flock.

[[v14-29-34]]

^<<v14-29-34,34>>^ Only the priests themselves happened to be too few, and they were not able to skin all the burnt offerings. So their brothers the Levites helped them out until the work was finished and until the priests could sanctify themselves, for the Levites were more upright of heart for sanctifying themselves than the priests.

[[v14-29-35]]

^<<v14-29-35,35>>^ And, too, the burnt offerings were in great quantity with the fat pieces of the communion sacrifices and with the drink offerings for the burnt offerings. Thus the service of the house of Jehovah was prepared.

[[v14-29-36]]

^<<v14-29-36,36>>^ Consequently Hez·e·kiʹah and all the people rejoiced over the fact that the &#91;true&#93; God had made preparation for the people, because it was all of a sudden that the thing had occurred.

'''

xref:014-2-chronicles/014-2-chronicles-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-030.adoc#v14-30-0[Próximo Capítulo &#62;]