include::./index.adoc[]

[[v14-11-0]]
=== The Second of Chronicles, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v14-11-1]]

^<<v14-11-1,1>>^ When Re·ho·boʹam arrived at Jerusalem, he immediately congregated the house of Judah and Benjamin, a hundred and eighty thousand choice men able-bodied for war, to fight against Israel so as to bring the kingdom back to Re·ho·boʹam.

[[v14-11-2]]

^<<v14-11-2,2>>^ Then the word of Jehovah came to She·maiʹah^&#42;1^ the man of the &#91;true&#93; God, saying:

[NOTE]
====
. Meaning “Jehovah Has Heard.” Heb., Shema·ʽeyaʹhu.
====

[[v14-11-3]]

^<<v14-11-3,3>>^ “Say to Re·ho·boʹam the son of Solʹo·mon the king of Judah and to all Israel in Judah and Benjamin, saying,

[[v14-11-4]]

^<<v14-11-4,4>>^ ‘This is what Jehovah has said: “YOU must not go up and fight against YOUR brothers. Return each one to his house, for it is at my own instance that this thing has been brought about.”’” So they obeyed the word of Jehovah and returned from going against Jer·o·boʹam.

[[v14-11-5]]

^<<v14-11-5,5>>^ And Re·ho·boʹam continued to dwell in Jerusalem and proceeded to build fortified cities in Judah.

[[v14-11-6]]

^<<v14-11-6,6>>^ Thus he rebuilt Bethʹle·hem and Eʹtam and Te·koʹa,

[[v14-11-7]]

^<<v14-11-7,7>>^ and Beth-zur and Soʹco and A·dulʹlam,

[[v14-11-8]]

^<<v14-11-8,8>>^ and Gath and Ma·reʹshah and Ziph,

[[v14-11-9]]

^<<v14-11-9,9>>^ and Ad·o·raʹim and Laʹchish and A·zeʹkah,

[[v14-11-10]]

^<<v14-11-10,10>>^ and Zoʹrah and Aiʹja·lon and Heʹbron, fortified cities, which were in Judah and Benjamin.

[[v14-11-11]]

^<<v14-11-11,11>>^ Further, he reinforced the fortified places and put leaders in them and supplies of food and oil and wine,

[[v14-11-12]]

^<<v14-11-12,12>>^ and in all the different cities large shields and lances; and he went on reinforcing them to a very great degree. And Judah and Benjamin continued his.

[[v14-11-13]]

^<<v14-11-13,13>>^ And the priests and the Levites themselves that were in all Israel took their stand by him out of all their territories.

[[v14-11-14]]

^<<v14-11-14,14>>^ For the Levites left their pasture grounds and their possession and then came to Judah and Jerusalem, because Jer·o·boʹam and his sons had discharged them from acting as priests to Jehovah.

[[v14-11-15]]

^<<v14-11-15,15>>^ And he proceeded to put in office for himself priests for the high places and for the goat-shaped demons^&#42;1^ and for the calves that he had made.

[NOTE]
====
. “Goat-shaped demons.” Perhaps to those worshiping them these were thought to be hairy creatures having the form of a he-goat. See Le 17:7 ftn, “Demons.”
====

[[v14-11-16]]

^<<v14-11-16,16>>^ And following them from all the tribes of Israel those that were giving their heart to seek Jehovah the God of Israel came themselves to Jerusalem to sacrifice to Jehovah the God of their forefathers.

[[v14-11-17]]

^<<v14-11-17,17>>^ And they kept strengthening the kingship of Judah and confirming Re·ho·boʹam the son of Solʹo·mon for three years, for they walked in the way of David and Solʹo·mon for three years.

[[v14-11-18]]

^<<v14-11-18,18>>^ Then Re·ho·boʹam took as his wife Maʹha·lath the daughter of Jerʹi·moth the son of David, and of Abʹi·ha·il the daughter of E·liʹab the son of Jesʹse.

[[v14-11-19]]

^<<v14-11-19,19>>^ In time she bore him sons, Jeʹush and Shem·a·riʹah and Zaʹham.

[[v14-11-20]]

^<<v14-11-20,20>>^ And after her he took Maʹa·cah the granddaughter of Abʹsa·lom. In time she bore him A·biʹjah and Atʹtai and Ziʹza and She·loʹmith.

[[v14-11-21]]

^<<v14-11-21,21>>^ And Re·ho·boʹam was more in love with Maʹa·cah the granddaughter of Abʹsa·lom than all his other wives and his concubines; for there were eighteen wives that he had taken, also sixty concubines, so that he became father to twenty-eight sons and sixty daughters.

[[v14-11-22]]

^<<v14-11-22,22>>^ Consequently Re·ho·boʹam put A·biʹjah the son of Maʹa·cah in office as head, as leader among his brothers, for &#91;he thought&#93; of making him king.

[[v14-11-23]]

^<<v14-11-23,23>>^ However, he acted understandingly and distributed some out of all his sons to all the lands of Judah and of Benjamin, to all the fortified cities, and gave them food in abundance and procured a multitude of wives &#91;for them&#93;.

'''

xref:014-2-chronicles/014-2-chronicles-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-chronicles/014-2-chronicles-012.adoc#v14-12-0[Próximo Capítulo &#62;]