include::./index.adoc[]

[[v44-5-0]]
=== Acts of Apostles, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-5-1]]

^<<v44-5-1,1>>^ However, a certain man, An·a·niʹas by name, together with Sap·phiʹra his wife, sold a possession

[[v44-5-2]]

^<<v44-5-2,2>>^ and secretly held back some of the price, his wife also knowing about it, and he brought just a part and deposited it at the feet of the apostles.

[[v44-5-3]]

^<<v44-5-3,3>>^ But Peter said: “An·a·niʹas, why has Satan emboldened you^&#42;1^ to play false to the holy spirit and to hold back secretly some of the price of the field?

[NOTE]
====
. Lit., “filled your heart.” See Es 7:5; Ec 8:11.
====

[[v44-5-4]]

^<<v44-5-4,4>>^ As long as it remained with you did it not remain yours, and after it was sold did it not continue in your control? Why was it that you purposed such a deed as this in your heart? You have played false, not to men, but to God.”

[[v44-5-5]]

^<<v44-5-5,5>>^ On hearing these words An·a·niʹas fell down and expired. And great fear came over all those hearing of it.

[[v44-5-6]]

^<<v44-5-6,6>>^ But the younger men rose, wrapped him in cloths, and carried him out and buried him.

[[v44-5-7]]

^<<v44-5-7,7>>^ Now after an interval of about three hours his wife came in, not knowing what had happened.

[[v44-5-8]]

^<<v44-5-8,8>>^ Peter said to her: “Tell me, did YOU &#91;two&#93; sell the field for so much?” She said: “Yes, for so much.”

[[v44-5-9]]

^<<v44-5-9,9>>^ So Peter said to her: “Why was it agreed upon between YOU &#91;two&#93; to make a test of the spirit of Jehovah?^&#42;1^ Look! The feet of those who buried your husband are at the door, and they will carry you out.”

[NOTE]
====
. See App 1D.
====

[[v44-5-10]]

^<<v44-5-10,10>>^ Instantly she fell down at his feet and expired. When the young men came in they found her dead, and they carried her out and buried her alongside her husband.

[[v44-5-11]]

^<<v44-5-11,11>>^ Consequently great fear came over the whole congregation^&#42;1^ and over all those hearing about these things.

[NOTE]
====
. Lit., “ecclesia.” Gr., ek·kle·siʹan; Lat., ec·cleʹsi·a; J17,​18(Heb.), haq·qa·halʹ, “the congregation.”
====

[[v44-5-12]]

^<<v44-5-12,12>>^ Moreover, through the hands of the apostles many signs and portents continued to occur among the people; and they were all with one accord in Solʹo·mon’s colonnade.

[[v44-5-13]]

^<<v44-5-13,13>>^ True, not a one of the others had the courage to join himself to them; nevertheless, the people were extolling them.

[[v44-5-14]]

^<<v44-5-14,14>>^ More than that, believers in the Lord kept on being added, multitudes both of men and of women;

[[v44-5-15]]

^<<v44-5-15,15>>^ so that they brought the sick out even into the broad ways and laid them there upon little beds and cots, in order that, as Peter would go by, at least his shadow might fall upon some one of them.

[[v44-5-16]]

^<<v44-5-16,16>>^ Also, the multitude from the cities around Jerusalem kept coming together, bearing sick people and those troubled with unclean spirits, and they would one and all be cured.

[[v44-5-17]]

^<<v44-5-17,17>>^ But the high priest and all those with him, the then existing sect of the Sadducees, rose and became filled with jealousy,

[[v44-5-18]]

^<<v44-5-18,18>>^ and they laid hands upon the apostles and put them in the public place of custody.

[[v44-5-19]]

^<<v44-5-19,19>>^ But during the night Jehovah’s^&#42;1^ angel opened the doors of the prison, brought them out and said:

[NOTE]
====
. See App 1D.
====

[[v44-5-20]]

^<<v44-5-20,20>>^ “Be on YOUR way, and, having taken a stand in the temple, keep on speaking to the people all the sayings about this life.”

[[v44-5-21]]

^<<v44-5-21,21>>^ After hearing this, they entered into the temple at daybreak and began to teach.
Now when the high priest and those with him arrived, they called together the Sanʹhe·drin and all the assembly of older men^&#42;1^ of the sons of Israel, and they sent out to the jail to have them brought.

[NOTE]
====
. Or, “and all the Senate.”
====

[[v44-5-22]]

^<<v44-5-22,22>>^ But when the officers got there they did not find them in the prison. So they returned and made report,

[[v44-5-23]]

^<<v44-5-23,23>>^ saying: “The jail we found locked with all security and the guards standing at the doors, but on opening up we found no one inside.”

[[v44-5-24]]

^<<v44-5-24,24>>^ Well, when both the captain of the temple and the chief priests heard these words, they fell into a quandary over these matters as to what this would come to.

[[v44-5-25]]

^<<v44-5-25,25>>^ But a certain man arrived and reported to them: “Look! The men YOU put in the prison are in the temple, standing and teaching the people.”

[[v44-5-26]]

^<<v44-5-26,26>>^ Then the captain went off with his officers and proceeded to bring them, but without violence, as they were afraid of being stoned by the people.

[[v44-5-27]]

^<<v44-5-27,27>>^ So they brought them and stood them in the Sanʹhe·drin hall. And the high priest questioned them

[[v44-5-28]]

^<<v44-5-28,28>>^ and said: “We positively ordered YOU not to keep teaching upon the basis of this name, and yet, look! YOU have filled Jerusalem with YOUR teaching, and YOU are determined to bring the blood of this man upon us.”

[[v44-5-29]]

^<<v44-5-29,29>>^ In answer Peter and the &#91;other&#93; apostles said: “We must obey God as ruler rather than men.

[[v44-5-30]]

^<<v44-5-30,30>>^ The God of our forefathers raised up Jesus, whom YOU slew, hanging him upon a stake.^&#42;1^

[NOTE]
====
. Or, “tree.” Gr., xyʹlou; J22(Heb.), ʽets. See 2:36 ftn.
====

[[v44-5-31]]

^<<v44-5-31,31>>^ God exalted this one as Chief Agent and Savior to his right hand, to give repentance to Israel and forgiveness of sins.

[[v44-5-32]]

^<<v44-5-32,32>>^ And we are witnesses of these matters, and so is the holy spirit, which God has given to those obeying him as ruler.”

[[v44-5-33]]

^<<v44-5-33,33>>^ When they heard this, they felt deeply cut and were wanting to do away with them.

[[v44-5-34]]

^<<v44-5-34,34>>^ But a certain man rose in the Sanʹhe·drin, a Pharisee named Ga·maʹli·el, a Law teacher esteemed by all the people, and gave the command to put the men outside for a little while.

[[v44-5-35]]

^<<v44-5-35,35>>^ And he said to them: “Men of Israel, pay attention to yourselves as to what YOU intend to do respecting these men.

[[v44-5-36]]

^<<v44-5-36,36>>^ For instance, before these days Theuʹdas rose, saying he himself was somebody, and a number of men, about four hundred, joined his party. But he was done away with, and all those who were obeying him were dispersed and came to nothing.

[[v44-5-37]]

^<<v44-5-37,37>>^ After him Judas the Gal·i·leʹan rose in the days of the registration, and he drew off people after him. And yet that man perished, and all those who were obeying him were scattered abroad.

[[v44-5-38]]

^<<v44-5-38,38>>^ And so, under the present circumstances, I say to YOU, Do not meddle with these men, but let them alone; (because, if this scheme or this work is from men, it will be overthrown;

[[v44-5-39]]

^<<v44-5-39,39>>^ but if it is from God, YOU will not be able to overthrow them;) otherwise, YOU may perhaps be found fighters actually against God.”

[[v44-5-40]]

^<<v44-5-40,40>>^ At this they gave heed to him, and they summoned the apostles, flogged them, and ordered them to stop speaking upon the basis of Jesus’ name, and let them go.

[[v44-5-41]]

^<<v44-5-41,41>>^ These, therefore, went their way from before the Sanʹhe·drin, rejoicing because they had been counted worthy to be dishonored in behalf of his name.

[[v44-5-42]]

^<<v44-5-42,42>>^ And every day in the temple and from house to house^&#42;1^ they continued without letup teaching and declaring the good news^&#42;2^ about the Christ, Jesus.

[NOTE]
====
. Lit., “according to house.” Gr., katʼ oiʹkon. Here ka·taʹ is used with the accusative sing. in the distributive sense. R. C. H. Lenski, in his work The Interpretation of The Acts of the Apostles, Minneapolis (1961), made the following comment on Ac 5:42: “Never for a moment did the apostles cease their blessed work. ‘Every day’ they continued, and this openly ‘in the Temple’ where the Sanhedrin and the Temple police could see and hear them, and, of course, also κατ’ οἴκον, which is distributive, ‘from house to house,’ and not merely adverbial, ‘at home.’ ”
. Or, “declaring the evangel (gospel).” Gr., eu·ag·ge·li·zoʹme·noi; Lat., e·van·ge·li·zanʹtes, “evangelizing.”
====

'''

xref:044-acts/044-acts-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-acts/044-acts-006.adoc#v44-6-0[Próximo Capítulo &#62;]