include::./index.adoc[]

[[v44-2-0]]
=== Acts of Apostles, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-2-1]]

^<<v44-2-1,1>>^ Now while the day of the &#91;festival of&#93; Pentecost was in progress they were all together at the same place,

[[v44-2-2]]

^<<v44-2-2,2>>^ and suddenly there occurred from heaven a noise just like that of a rushing stiff breeze, and it filled the whole house in which they were sitting.

[[v44-2-3]]

^<<v44-2-3,3>>^ And tongues as if of fire became visible to them and were distributed about, and one sat upon each one of them,

[[v44-2-4]]

^<<v44-2-4,4>>^ and they all became filled with holy spirit and started to speak with different tongues, just as the spirit was granting them to make utterance.

[[v44-2-5]]

^<<v44-2-5,5>>^ As it was, there were dwelling in Jerusalem Jews, reverent men, from every nation of those under heaven.

[[v44-2-6]]

^<<v44-2-6,6>>^ So, when this sound occurred, the multitude came together and were bewildered, because each one heard them speaking in his own language.

[[v44-2-7]]

^<<v44-2-7,7>>^ Indeed, they were astonished and began to wonder and say: “See here, all these who are speaking are Gal·i·leʹans, are they not?

[[v44-2-8]]

^<<v44-2-8,8>>^ And yet how is it we are hearing, each one of us, his own language in which we were born?

[[v44-2-9]]

^<<v44-2-9,9>>^ Parʹthi·ans and Medes and Eʹlam·ites, and the inhabitants of Mes·o·po·taʹmi·a, and Ju·deʹa and Cap·pa·doʹci·a, Ponʹtus and the &#91;district of&#93; Asia,

[[v44-2-10]]

^<<v44-2-10,10>>^ and Phrygʹi·a and Pam·phylʹi·a, Egypt and the parts of Libʹy·a, which is toward Cy·reʹne, and sojourners from Rome, both Jews and proselytes,^&#42;1^

[NOTE]
====
. Or, “converts.”
====

[[v44-2-11]]

^<<v44-2-11,11>>^ Creʹtans and Arabians, we hear them speaking in our tongues about the magnificent things of God.”

[[v44-2-12]]

^<<v44-2-12,12>>^ Yes, they were all astonished and were in perplexity, saying one to another: “What does this thing purport to be?”

[[v44-2-13]]

^<<v44-2-13,13>>^ However, different ones mocked at them and began to say: “They are full of sweet wine.”

[[v44-2-14]]

^<<v44-2-14,14>>^ But Peter stood up with the eleven and raised his voice and made this utterance to them: “Men of Ju·deʹa and all YOU inhabitants of Jerusalem, let this be known to YOU and give ear to my sayings.

[[v44-2-15]]

^<<v44-2-15,15>>^ These &#91;people&#93; are, in fact, not drunk, as YOU suppose, for it is the third hour^&#42;1^ of the day.

[NOTE]
====
. That is, about 9 a.m., counting from sunrise.
====

[[v44-2-16]]

^<<v44-2-16,16>>^ On the contrary, this is what was said through the prophet Joel,

[[v44-2-17]]

^<<v44-2-17,17>>^ ‘“And in the last days,” God says, “I shall pour out some of my spirit^&#42;1^ upon every sort of flesh,^&#42;2^ and YOUR sons and YOUR daughters will prophesy and YOUR young men will see visions and YOUR old men^&#42;3^ will dream dreams;

[NOTE]
====
. Or, “active force.” Gr., pneuʹma·tos; Lat., Spiʹri·tu; J17,​18,​22(Heb.), ru·chiʹ, “my spirit.” See Ge 1:2 ftn, “Force.”
. Or, “upon all flesh.” Gr., e·piʹ paʹsan sarʹka; Lat., carʹnem; J17,​18,​22(Heb.), ba·sarʹ.
. Or, “elders.” Gr., pre·sbyʹte·roi.
====

[[v44-2-18]]

^<<v44-2-18,18>>^ and even upon my men slaves and upon my women slaves I will pour out some of my spirit in those days, and they will prophesy.

[[v44-2-19]]

^<<v44-2-19,19>>^ And I will give portents in heaven above and signs on earth below, blood and fire and smoke mist;

[[v44-2-20]]

^<<v44-2-20,20>>^ the sun will be turned into darkness and the moon into blood before the great and illustrious day of Jehovah^&#42;1^ arrives.

[NOTE]
====
. See App 1D.
====

[[v44-2-21]]

^<<v44-2-21,21>>^ And everyone who calls on the name of Jehovah^&#42;1^ will be saved.”’

[NOTE]
====
. See App 1D.
====

[[v44-2-22]]

^<<v44-2-22,22>>^ “Men of Israel, hear these words: Jesus the Naz·a·reneʹ, a man publicly shown by God to YOU through powerful works and portents and signs that God did through him in YOUR midst, just as YOU yourselves know,

[[v44-2-23]]

^<<v44-2-23,23>>^ this &#91;man&#93;, as one delivered up by the determined counsel and foreknowledge of God, YOU fastened to a stake by the hand of lawless men and did away with.

[[v44-2-24]]

^<<v44-2-24,24>>^ But God resurrected him by loosing the pangs of death, because it was not possible for him to continue to be held fast by it.

[[v44-2-25]]

^<<v44-2-25,25>>^ For David says respecting him, ‘I had Jehovah^&#42;1^ constantly before my eyes; because he is at my right hand that I may never be shaken.

[NOTE]
====
. See App 1D.
====

[[v44-2-26]]

^<<v44-2-26,26>>^ On this account my heart became cheerful and my tongue rejoiced greatly. Moreover, even my flesh will reside in hope;

[[v44-2-27]]

^<<v44-2-27,27>>^ because you will not leave my soul in Haʹdes,^&#42;1^ neither will you allow your loyal one to see corruption.

[NOTE]
====
. “Hades,” אAB; J7,​8,​11-18,​22, “Sheol.” See App 4B.
====

[[v44-2-28]]

^<<v44-2-28,28>>^ You have made life’s ways known to me, you will fill me with good cheer with your face.’

[[v44-2-29]]

^<<v44-2-29,29>>^ “Men, brothers, it is allowable to speak with freeness of speech to YOU concerning the family head David, that he both deceased and was buried and his tomb is among us to this day.

[[v44-2-30]]

^<<v44-2-30,30>>^ Therefore, because he was a prophet and knew that God^&#42;1^ had sworn to him with an oath that he would seat one from the fruitage of his loins^&#42;2^ upon his throne,

[NOTE]
====
. “God,” אAB; J7,​8,​10, “Jehovah.”
. Or, “one of his offspring.”
====

[[v44-2-31]]

^<<v44-2-31,31>>^ he saw beforehand and spoke concerning the resurrection of the Christ, that neither was he forsaken in Haʹdes nor did his flesh see corruption.

[[v44-2-32]]

^<<v44-2-32,32>>^ This Jesus God resurrected, of which fact we are all witnesses.

[[v44-2-33]]

^<<v44-2-33,33>>^ Therefore because he was exalted to^&#42;1^ the right hand of God and received the promised holy spirit from the Father, he has poured out this which YOU see and hear.

[NOTE]
====
. Or, “by.”
====

[[v44-2-34]]

^<<v44-2-34,34>>^ Actually David did not ascend to the heavens, but he himself says, ‘Jehovah^&#42;1^ said to my Lord: “Sit at my right hand,

[NOTE]
====
. See App 1D.
====

[[v44-2-35]]

^<<v44-2-35,35>>^ until I place your enemies as a stool for your feet.”’

[[v44-2-36]]

^<<v44-2-36,36>>^ Therefore let all the house of Israel know for a certainty that God made him both Lord and Christ, this Jesus whom YOU impaled.”^&#42;1^

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v44-2-37]]

^<<v44-2-37,37>>^ Now when they heard this they were stabbed to the heart, and they said to Peter and the rest of the apostles: “Men, brothers, what shall we do?”

[[v44-2-38]]

^<<v44-2-38,38>>^ Peter &#91;said&#93; to them: “Repent, and let each one of YOU be baptized in the name of Jesus Christ for forgiveness of YOUR sins, and YOU will receive the free gift of the holy spirit.

[[v44-2-39]]

^<<v44-2-39,39>>^ For the promise is to YOU and to YOUR children and to all those afar off, just as many as Jehovah^&#42;1^ our God may call to him.”

[NOTE]
====
. See App 1D.
====

[[v44-2-40]]

^<<v44-2-40,40>>^ And with many other words he bore thorough witness and kept exhorting them, saying: “Get saved from this crooked generation.”

[[v44-2-41]]

^<<v44-2-41,41>>^ Therefore those who embraced his word heartily were baptized, and on that day about three thousand souls were added.

[[v44-2-42]]

^<<v44-2-42,42>>^ And they continued devoting themselves to the teaching of the apostles and to sharing &#91;with one another&#93;,^&#42;1^ to taking of meals^&#42;2^ and to prayers.

[NOTE]
====
. Or, “association together.”
. Lit., “to the breaking of the bread.”
====

[[v44-2-43]]

^<<v44-2-43,43>>^ Indeed, fear began to fall upon every soul, and many portents and signs began to occur through the apostles.

[[v44-2-44]]

^<<v44-2-44,44>>^ All those who became believers were together in having all things in common,

[[v44-2-45]]

^<<v44-2-45,45>>^ and they went selling their possessions and properties and distributing the &#91;proceeds&#93; to all, just as anyone would have the need.

[[v44-2-46]]

^<<v44-2-46,46>>^ And day after day they were in constant attendance at the temple with one accord, and they took their meals in private homes^&#42;1^ and partook of food with great rejoicing and sincerity of heart,

[NOTE]
====
. Or, “from house to house.” Gr., katʼ oiʹkon. See 5:42 ftn, “House.”
====

[[v44-2-47]]

^<<v44-2-47,47>>^ praising God and finding favor with all the people. At the same time Jehovah^&#42;1^ continued to join to them daily those being saved.

[NOTE]
====
. See App 1D.
====

'''

xref:044-acts/044-acts-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-acts/044-acts-003.adoc#v44-3-0[Próximo Capítulo &#62;]