include::./index.adoc[]

[[v44-1-0]]
=== Acts of Apostles, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-1-1]]

^<<v44-1-1,1>>^ The first account, O The·ophʹi·lus, I composed about all the things Jesus started both to do and to teach,

[[v44-1-2]]

^<<v44-1-2,2>>^ until the day that he was taken up, after he had given commandment through holy spirit to the apostles whom he chose.

[[v44-1-3]]

^<<v44-1-3,3>>^ To these also by many positive proofs he showed himself alive after he had suffered, being seen by them throughout forty days and telling the things about the kingdom of God.

[[v44-1-4]]

^<<v44-1-4,4>>^ And while he was meeting with them he gave them the orders: “Do not withdraw from Jerusalem, but keep waiting for what the Father has promised, about which YOU heard from me;

[[v44-1-5]]

^<<v44-1-5,5>>^ because John, indeed, baptized with water, but YOU will be baptized in holy spirit not many days after this.”

[[v44-1-6]]

^<<v44-1-6,6>>^ When, now, they had assembled, they went asking him: “Lord,^&#42;1^ are you restoring the kingdom to Israel at this time?”

[NOTE]
====
. Or, “Master.”
====

[[v44-1-7]]

^<<v44-1-7,7>>^ He said to them: “It does not belong to YOU to get knowledge of the times or seasons^&#42;1^ which the Father has placed in his own jurisdiction;^&#42;2^

[NOTE]
====
. Or, “appointed times.” Gr., kai·rousʹ.
. Lit., “authority.” Gr., e·xou·siʹai.
====

[[v44-1-8]]

^<<v44-1-8,8>>^ but YOU will receive power when the holy spirit arrives upon YOU, and YOU will be witnesses^&#42;1^ of me both in Jerusalem and in all Ju·deʹa and Sa·marʹi·a and to the most distant part^&#42;2^ of the earth.”

[NOTE]
====
. “Witnesses.” Gr., marʹty·res; Lat., teʹstes.
. “Most distant part.” Or, “extremity.” Gr., e·skhaʹtou; J17,​18,​22(Heb.), qetsehʹ. See Jer 25:31, 33 ftns. Compare Mt 12:42 ftn.
====

[[v44-1-9]]

^<<v44-1-9,9>>^ And after he had said these things, while they were looking on, he was lifted up and a cloud caught him up from their vision.

[[v44-1-10]]

^<<v44-1-10,10>>^ And as they were gazing into the sky while he was on his way, also, look! two men in white^&#42;1^ garments stood alongside them,

[NOTE]
====
. Or, “bright.”
====

[[v44-1-11]]

^<<v44-1-11,11>>^ and they said: “Men of Galʹi·lee, why do YOU stand looking into the sky? This Jesus who was received up from YOU into the sky will come thus in the same manner as YOU have beheld him going into the sky.”^&#42;1^

[NOTE]
====
. Lit., “heaven.” Gr., ou·ra·nonʹ; Lat., caeʹlum; J17(Heb.), hash·sha·ma·yemahʹ, “toward the heaven.”
====

[[v44-1-12]]

^<<v44-1-12,12>>^ Then they returned to Jerusalem from a mountain called the Mount of Olives, which is near Jerusalem, being a sabbath day’s journey^&#42;1^ away.

[NOTE]
====
. According to rabbinical sources based on Jos 3:4, this was about 2,000 cubits (890 m; 2,920 ft).
====

[[v44-1-13]]

^<<v44-1-13,13>>^ So, when they had entered, they went up into the upper chamber, where they were staying, Peter as well as John and James and Andrew, Philip and Thomas, Bar·tholʹo·mew and Matthew, James &#91;the son&#93; of Al·phaeʹus and Simon the zealous one,^&#42;1^ and Judas &#91;the son&#93; of James.

[NOTE]
====
. “The zealous one.” See Lu 6:15 ftn.
====

[[v44-1-14]]

^<<v44-1-14,14>>^ With one accord all these were persisting in prayer, together with some women and Mary the mother of Jesus and with his brothers.

[[v44-1-15]]

^<<v44-1-15,15>>^ Now during these days Peter rose up in the midst of the brothers and said (the crowd^&#42;1^ of persons was all together about one hundred and twenty):

[NOTE]
====
. Or, “number.”
====

[[v44-1-16]]

^<<v44-1-16,16>>^ “Men, brothers, it was necessary for the scripture to be fulfilled, which the holy spirit spoke beforehand by David’s mouth about Judas, who became a guide to those who arrested Jesus,

[[v44-1-17]]

^<<v44-1-17,17>>^ because he had been numbered among us and he obtained a share in this ministry.

[[v44-1-18]]

^<<v44-1-18,18>>^ (This very man, therefore, purchased a field with the wages for unrighteousness, and pitching head foremost^&#42;1^ he noisily burst in his midst and all his intestines were poured out.

[NOTE]
====
. Or, “and becoming swollen up.”
====

[[v44-1-19]]

^<<v44-1-19,19>>^ It also became known to all the inhabitants of Jerusalem, so that that field was called in their language A·kelʹda·ma, that is, Field of Blood.)

[[v44-1-20]]

^<<v44-1-20,20>>^ For it is written in the book of Psalms, ‘Let his lodging place become desolate, and let there be no dweller in it,’ and, ‘His office of oversight^&#42;1^ let someone else take.’

[NOTE]
====
. “Office of oversight.” Gr., e·pi·sko·penʹ; J17,​18(Heb.), u·phequd·da·thohʹ (from pa·qadhʹ). See 2Ki 11:18 ftn.
====

[[v44-1-21]]

^<<v44-1-21,21>>^ It is therefore necessary that of the men that assembled with us during all the time in which the Lord Jesus went in and out^&#42;1^ among us,

[NOTE]
====
. Or, “carried on his activities.”
====

[[v44-1-22]]

^<<v44-1-22,22>>^ starting with his baptism by John and until the day he was received up from us, one of these men should become a witness with us of his resurrection.”

[[v44-1-23]]

^<<v44-1-23,23>>^ So they put up two, Joseph called Barʹsab·bas, who was surnamed Justus, and Mat·thiʹas.

[[v44-1-24]]

^<<v44-1-24,24>>^ And they prayed and said: “You, O Jehovah,^&#42;1^ who know the hearts of all, designate which one of these two men you have chosen,

[NOTE]
====
. See App 1D.
====

[[v44-1-25]]

^<<v44-1-25,25>>^ to take the place of this ministry and apostleship, from which Judas deviated to go to his own place.”

[[v44-1-26]]

^<<v44-1-26,26>>^ So they cast lots over them, and the lot fell upon Mat·thiʹas; and he was reckoned along with the eleven apostles.

'''

xref:043-john/043-john-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-acts/044-acts-002.adoc#v44-2-0[Próximo Capítulo &#62;]