include::./index.adoc[]

[[v44-17-0]]
=== Acts of Apostles, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-17-1]]

^<<v44-17-1,1>>^ They now journeyed through Am·phipʹo·lis and Ap·ol·loʹni·a and came to Thes·sa·lo·niʹca, where there was a synagogue of the Jews.

[[v44-17-2]]

^<<v44-17-2,2>>^ So according to Paul’s custom he went inside to them, and for three sabbaths he reasoned with them from the Scriptures,

[[v44-17-3]]

^<<v44-17-3,3>>^ explaining and proving by references that it was necessary for the Christ to suffer and to rise from the dead, and &#91;saying&#93;: “This is the Christ, this Jesus whom I am publishing to YOU.”

[[v44-17-4]]

^<<v44-17-4,4>>^ As a result some of them became believers and associated themselves with Paul and Silas, and a great multitude of the Greeks who worshiped &#91;God&#93; and not a few of the principal women did so.

[[v44-17-5]]

^<<v44-17-5,5>>^ But the Jews, getting jealous, took into their company certain wicked men of the marketplace idlers and formed a mob and proceeded to throw the city into an uproar. And they assaulted the house of Jaʹson and went seeking to have them brought forth to the rabble.

[[v44-17-6]]

^<<v44-17-6,6>>^ When they did not find them they dragged Jaʹson and certain brothers to the city rulers,^&#42;1^ crying out: “These men that have overturned the inhabited earth are present here also,

[NOTE]
====
. Lit., “politarchs.” Gr., po·li·tarʹkhas, governors of the citizens.
====

[[v44-17-7]]

^<<v44-17-7,7>>^ and Jaʹson has received them with hospitality. And all these &#91;men&#93; act in opposition to the decrees of Caesar,^&#42;1^ saying there is another king, Jesus.”

[NOTE]
====
. Or, “of the emperor.” Gr., Kaiʹsa·ros.
====

[[v44-17-8]]

^<<v44-17-8,8>>^ They indeed agitated the crowd and the city rulers when they heard these things;

[[v44-17-9]]

^<<v44-17-9,9>>^ and first after taking sufficient security^&#42;1^ from Jaʹson and the others they let them go.

[NOTE]
====
. Or, “sufficient bail.” Lat., saʹtis, “enough.”
====

[[v44-17-10]]

^<<v44-17-10,10>>^ Immediately by night the brothers sent both Paul and Silas out to Be·roeʹa, and these, upon arriving, went into the synagogue of the Jews.

[[v44-17-11]]

^<<v44-17-11,11>>^ Now the latter were more noble-minded than those in Thes·sa·lo·niʹca, for they received the word with the greatest eagerness of mind, carefully examining the Scriptures daily as to whether these things were so.

[[v44-17-12]]

^<<v44-17-12,12>>^ Therefore many of them became believers, and so did not a few of the reputable Greek women and of the men.

[[v44-17-13]]

^<<v44-17-13,13>>^ But when the Jews from Thes·sa·lo·niʹca learned that the word of God was published also in Be·roeʹa by Paul, they came there also to incite and agitate the masses.

[[v44-17-14]]

^<<v44-17-14,14>>^ Then the brothers immediately sent Paul off to go as far as the sea; but both Silas and Timothy remained behind there.

[[v44-17-15]]

^<<v44-17-15,15>>^ However, those conducting Paul brought him as far as Athens and, after receiving a command for Silas and Timothy to come to him as quickly as possible, they departed.

[[v44-17-16]]

^<<v44-17-16,16>>^ Now while Paul was waiting for them in Athens, his spirit within him came to be irritated at beholding that the city was full of idols.

[[v44-17-17]]

^<<v44-17-17,17>>^ Consequently he began to reason in the synagogue with the Jews and the other people who worshiped &#91;God&#93; and every day in the marketplace with those who happened to be on hand.

[[v44-17-18]]

^<<v44-17-18,18>>^ But certain ones of both the Ep·i·cu·reʹan and the Stoʹic philosophers took to conversing with him controversially, and some would say: “What is it this chatterer^&#42;1^ would like to tell?” Others: “He seems to be a publisher of foreign deities.”^&#42;2^ This was because he was declaring the good news of Jesus and the resurrection.

[NOTE]
====
. Lit., “seed picker.”
. Lit., “demons.” Gr., dai·mo·niʹon.
====

[[v44-17-19]]

^<<v44-17-19,19>>^ So they laid hold of him and led him to the Ar·e·opʹa·gus,^&#42;1^ saying: “Can we get to know what this new teaching is which is spoken by you?

[NOTE]
====
. Or, “Hill of Ares; Mars’ Hill.” Gr., Aʹrei·on Paʹgon; Lat., A·ri·oʹpa·gum.
====

[[v44-17-20]]

^<<v44-17-20,20>>^ For you are introducing some things that are strange to our ears. Therefore we desire to get to know what these things purport to be.”

[[v44-17-21]]

^<<v44-17-21,21>>^ In fact, all Athenians and the foreigners sojourning there would spend their leisure time at nothing but telling something or listening to something new.

[[v44-17-22]]

^<<v44-17-22,22>>^ Paul now stood in the midst of the Ar·e·opʹa·gus and said:
“Men of Athens, I behold that in all things YOU seem to be more given to the fear of the deities^&#42;1^ than others are.

[NOTE]
====
. “More given to the fear of the deities.” Lit., “more demon-dreading.” Gr., dei·si·dai·mo·ne·steʹrous; Lat., su·per·sti·ti·o·si·oʹres. Demons were thought by the Greeks to be deities, good or evil. Compare 25:19 ftn.
====

[[v44-17-23]]

^<<v44-17-23,23>>^ For instance, while passing along and carefully observing YOUR objects of veneration I also found an altar on which had been inscribed ‘To an Unknown God.’ Therefore what YOU are unknowingly giving godly devotion to, this I am publishing to YOU.

[[v44-17-24]]

^<<v44-17-24,24>>^ The God that made the world and all the things in it, being, as this One is, Lord of heaven and earth, does not dwell in handmade temples,^&#42;1^

[NOTE]
====
. Or, “divine habitations (dwellings).” Gr., na·oisʹ; J17,​22(Heb.), beheh·kha·lohthʹ, “in palaces (temples).”
====

[[v44-17-25]]

^<<v44-17-25,25>>^ neither is he attended to by human hands as if he needed anything, because he himself gives to all &#91;persons&#93; life and breath and all things.

[[v44-17-26]]

^<<v44-17-26,26>>^ And he made out of one &#91;man&#93; every nation of men, to dwell upon the entire surface of the earth, and he decreed the appointed times and the set limits of the dwelling of &#91;men&#93;,

[[v44-17-27]]

^<<v44-17-27,27>>^ for them to seek God, if they might grope for him and really find him, although, in fact, he is not far off from each one of us.

[[v44-17-28]]

^<<v44-17-28,28>>^ For by^&#42;1^ him we have life and move and exist, even as certain ones^&#42;2^ of the poets among YOU have said, ‘For we are also his progeny.’

[NOTE]
====
. Or, “in.”
. “Certain ones,” namely, Aratus and Cleanthes. Paul’s quotation is from Phænomena, by Aratus, and from Hymn to Zeus, by Cleanthes.
====

[[v44-17-29]]

^<<v44-17-29,29>>^ “Seeing, therefore, that we are the progeny of God, we ought not to imagine that the Divine Being^&#42;1^ is like gold or silver or stone, like something sculptured by the art and contrivance of man.

[NOTE]
====
. “Divine Being.” Gr., Theiʹon, related to The·osʹ, “God”; Lat., Di·viʹnum.
====

[[v44-17-30]]

^<<v44-17-30,30>>^ True, God has overlooked the times of such ignorance, yet now he is telling mankind that they should all everywhere repent.

[[v44-17-31]]

^<<v44-17-31,31>>^ Because he has set a day in which he purposes to judge the inhabited earth^&#42;1^ in righteousness by a man whom he has appointed, and he has furnished a guarantee^&#42;2^ to all men in that he has resurrected him from the dead.”

[NOTE]
====
. “Inhabited earth.” Lit., “inhabited.” Gr., oi·kou·meʹnen, fem. sing., referring to the earth; Lat., orʹbem, “circle,” that is, of the earth. See Isa 13:11 ftn, “Land.”
. Or, “faith.”
====

[[v44-17-32]]

^<<v44-17-32,32>>^ Well, when they heard of a resurrection of the dead, some began to mock, while others said: “We will hear you about this even another time.”

[[v44-17-33]]

^<<v44-17-33,33>>^ Thus Paul went out from their midst,

[[v44-17-34]]

^<<v44-17-34,34>>^ but some men joined themselves to him and became believers, among whom also were Di·o·nysʹi·us, a judge of the court of the Ar·e·opʹa·gus,^&#42;1^ and a woman named Damʹa·ris, and others besides them.

[NOTE]
====
. Or, “Dionysius, an Areopagite.”
====

'''

xref:044-acts/044-acts-016.adoc#v44-16-0[&#60; Capítulo Anterior] | <<v44-17-0,Topo>> | xref:044-acts/044-acts-018.adoc#v44-18-0[Próximo Capítulo &#62;]