include::./index.adoc[]

[[v44-3-0]]
=== Acts of Apostles, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-3-1]]

^<<v44-3-1,1>>^ Now Peter and John were going up into the temple for the hour of prayer, the ninth hour,^&#42;1^

[NOTE]
====
. That is, about 3 p.m., counting from sunrise.
====

[[v44-3-2]]

^<<v44-3-2,2>>^ and a certain man that was lame from his mother’s womb was being carried, and they would daily put him near the temple door that was called Beautiful, in order to ask gifts of mercy from those entering into the temple.

[[v44-3-3]]

^<<v44-3-3,3>>^ When he caught sight of Peter and John about to go into the temple he began requesting to get gifts of mercy.

[[v44-3-4]]

^<<v44-3-4,4>>^ But Peter, together with John, gazed at him and said: “Take a look at us.”

[[v44-3-5]]

^<<v44-3-5,5>>^ So he fixed his attention upon them, expecting to get something from them.

[[v44-3-6]]

^<<v44-3-6,6>>^ However, Peter said: “Silver and gold I do not possess, but what I do have is what I give you: In the name of Jesus Christ the Naz·a·reneʹ, walk!”

[[v44-3-7]]

^<<v44-3-7,7>>^ With that he took hold of him by the right hand and raised him up. Instantly the soles of his feet and his anklebones were made firm;

[[v44-3-8]]

^<<v44-3-8,8>>^ and, leaping up, he stood up and began walking, and he entered with them into the temple, walking and leaping and praising God.

[[v44-3-9]]

^<<v44-3-9,9>>^ And all the people got sight of him walking and praising God.

[[v44-3-10]]

^<<v44-3-10,10>>^ Moreover, they began to recognize him, that this was the man that used to sit for gifts of mercy at the Beautiful Gate of the temple, and they became filled with astonishment and ecstasy at what had happened to him.

[[v44-3-11]]

^<<v44-3-11,11>>^ Well, as the man was holding onto Peter and John, all the people ran together to them at what was called Solʹo·mon’s colonnade, surprised out of their wits.

[[v44-3-12]]

^<<v44-3-12,12>>^ When Peter saw this, he said to the people: “Men of Israel, why are YOU wondering over this, or why are YOU gazing at us as though by personal power or godly devotion we have made him walk?

[[v44-3-13]]

^<<v44-3-13,13>>^ The God of Abraham and of Isaac and of Jacob, the God of our forefathers, has glorified his Servant, Jesus, whom YOU, for YOUR part, delivered up and disowned before Pilate’s face, when he had decided to release him.

[[v44-3-14]]

^<<v44-3-14,14>>^ Yes, YOU disowned that holy and righteous one, and YOU asked for a man, a murderer, to be freely granted to YOU,

[[v44-3-15]]

^<<v44-3-15,15>>^ whereas YOU killed the Chief Agent of life. But God raised him up from the dead, of which fact we are witnesses.

[[v44-3-16]]

^<<v44-3-16,16>>^ Consequently his name, by &#91;our&#93; faith in his name, has made this man strong whom YOU behold and know, and the faith that is through him has given the man this complete soundness in the sight of all of YOU.

[[v44-3-17]]

^<<v44-3-17,17>>^ And now, brothers, I know that YOU acted in ignorance, just as YOUR rulers also did.

[[v44-3-18]]

^<<v44-3-18,18>>^ But in this way God has fulfilled the things he announced beforehand through the mouth of all the prophets, that his Christ would suffer.

[[v44-3-19]]

^<<v44-3-19,19>>^ “Repent, therefore, and turn around so as to get YOUR sins blotted out, that seasons^&#42;1^ of refreshing may come from the person^&#42;2^ of Jehovah^&#42;3^

[NOTE]
====
. Or, “appointed times.” Gr., kai·roiʹ.
. Lit., “from face.”
. See App 1D.
====

[[v44-3-20]]

^<<v44-3-20,20>>^ and that he may send forth the Christ appointed for YOU, Jesus,

[[v44-3-21]]

^<<v44-3-21,21>>^ whom heaven, indeed, must hold within itself^&#42;1^ until the times of restoration of all things of which God spoke through the mouth of his holy prophets of old time.

[NOTE]
====
. Or, “must receive.”
====

[[v44-3-22]]

^<<v44-3-22,22>>^ In fact, Moses said, ‘Jehovah^&#42;1^ God will raise up for YOU from among YOUR brothers a prophet like me. YOU must listen to him according to all the things he speaks to YOU.

[NOTE]
====
. “Jehovah,” J7,​8,​10-18,​20,​22-24 and LXXP. Fouad Inv. 266 in De 18:15; Gr., Kyʹri·os. See App 1D.
====

[[v44-3-23]]

^<<v44-3-23,23>>^ Indeed, any soul^&#42;1^ that does not listen to that Prophet will be completely destroyed from among the people.’

[NOTE]
====
. Or, “every soul.”
====

[[v44-3-24]]

^<<v44-3-24,24>>^ And all the prophets, in fact, from Samuel on and those in succession, just as many as have spoken, have also plainly declared these days.

[[v44-3-25]]

^<<v44-3-25,25>>^ YOU are the sons of the prophets and of the covenant which God covenanted with YOUR forefathers, saying to Abraham, ‘And in your seed^&#42;1^ all the families of the earth will be blessed.’

[NOTE]
====
. Or, “offspring.”
====

[[v44-3-26]]

^<<v44-3-26,26>>^ To YOU first God, after raising up his Servant, sent him forth to bless YOU by turning each one away from YOUR wicked deeds.”

'''

xref:044-acts/044-acts-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-acts/044-acts-004.adoc#v44-4-0[Próximo Capítulo &#62;]