include::./index.adoc[]

[[v44-9-0]]
=== Acts of Apostles, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-9-1]]

^<<v44-9-1,1>>^ But Saul, still breathing threat and murder against the disciples of the Lord, went to the high priest

[[v44-9-2]]

^<<v44-9-2,2>>^ and asked him for letters to the synagogues in Damascus, in order that he might bring bound to Jerusalem any whom he found who belonged to The Way,^&#42;1^ both men and women.

[NOTE]
====
. “The Way.” Gr., tes ho·douʹ.
====

[[v44-9-3]]

^<<v44-9-3,3>>^ Now as he was traveling he approached Damascus, when suddenly a light from heaven flashed around him,

[[v44-9-4]]

^<<v44-9-4,4>>^ and he fell to the ground and heard a voice say to him: “Saul, Saul, why are you persecuting me?”

[[v44-9-5]]

^<<v44-9-5,5>>^ He said: “Who are you, Lord?” He said: “I am Jesus, whom you are persecuting.

[[v44-9-6]]

^<<v44-9-6,6>>^ Nevertheless, rise and enter into the city, and what you must do will be told you.”

[[v44-9-7]]

^<<v44-9-7,7>>^ Now the men that were journeying with him were standing speechless, hearing, indeed, the sound of a voice, but not beholding any man.

[[v44-9-8]]

^<<v44-9-8,8>>^ But Saul got up from the ground, and though his eyes were opened he was seeing nothing. So they led him by the hand and conducted him into Damascus.

[[v44-9-9]]

^<<v44-9-9,9>>^ And for three days he did not see anything, and he neither ate nor drank.

[[v44-9-10]]

^<<v44-9-10,10>>^ There was in Damascus a certain disciple named An·a·niʹas, and the Lord said to him in a vision: “An·a·niʹas!” He said: “Here I am, Lord.”

[[v44-9-11]]

^<<v44-9-11,11>>^ The Lord said to him: “Rise, go to the street called Straight, and at the house of Judas look for a man named Saul, from Tarsus. For, look! he is praying,

[[v44-9-12]]

^<<v44-9-12,12>>^ and in a vision^&#42;1^ he has seen a man named An·a·niʹas come in and lay his hands upon him that he might recover sight.”

[NOTE]
====
. “In a vision,” BCSyh,pArm; P74אAVg omit.
====

[[v44-9-13]]

^<<v44-9-13,13>>^ But An·a·niʹas answered: “Lord, I have heard from many about this man, how many injurious things he did to your holy ones^&#42;1^ in Jerusalem.

[NOTE]
====
. Or, “your saints.”
====

[[v44-9-14]]

^<<v44-9-14,14>>^ And here he has authority from the chief priests to put in bonds all those calling upon your name.”

[[v44-9-15]]

^<<v44-9-15,15>>^ But the Lord said to him: “Be on your way, because this man is a chosen vessel to me to bear my name to the nations as well as to kings and the sons of Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ For I shall show him plainly how many things he must suffer for my name.”

[[v44-9-17]]

^<<v44-9-17,17>>^ So An·a·niʹas went off and entered into the house, and he laid his hands upon him and said: “Saul, brother, the Lord, the Jesus that appeared to you on the road over which you were coming, has sent me forth, in order that you may recover sight and be filled with holy spirit.”

[[v44-9-18]]

^<<v44-9-18,18>>^ And immediately there fell from his eyes what looked like scales, and he recovered sight; and he rose and was baptized,

[[v44-9-19]]

^<<v44-9-19,19>>^ and he took food and gained strength.
He got to be for some days with the disciples in Damascus,

[[v44-9-20]]

^<<v44-9-20,20>>^ and immediately in the synagogues he began to preach Jesus, that this One is the Son of God.

[[v44-9-21]]

^<<v44-9-21,21>>^ But all those hearing him gave way to astonishment and would say: “Is this not the man that ravaged those in Jerusalem who call upon this name, and that had come here for this very purpose, that he might lead them bound to the chief priests?”

[[v44-9-22]]

^<<v44-9-22,22>>^ But Saul kept on acquiring power all the more and was confounding the Jews that dwelt in Damascus as he proved logically that this is the Christ.

[[v44-9-23]]

^<<v44-9-23,23>>^ Now when a good many days were coming to a close, the Jews took counsel together to do away with him.

[[v44-9-24]]

^<<v44-9-24,24>>^ However, their plot against him became known to Saul. But they were closely watching also the gates both day and night in order to do away with him.

[[v44-9-25]]

^<<v44-9-25,25>>^ So his disciples took him and let him down by night through an opening in the wall, lowering him in a basket.

[[v44-9-26]]

^<<v44-9-26,26>>^ On arriving in Jerusalem he made efforts to join himself to the disciples; but they were all afraid of him, because they did not believe he was a disciple.

[[v44-9-27]]

^<<v44-9-27,27>>^ So Barʹna·bas came to his aid and led him to the apostles, and he told them in detail how on the road he had seen the Lord and that he had spoken to him, and how in Damascus he had spoken boldly in the name of Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ And he continued with them, walking in and out^&#42;1^ at Jerusalem, speaking boldly in the name of the Lord;

[NOTE]
====
. Or, “carrying on his daily life.”
====

[[v44-9-29]]

^<<v44-9-29,29>>^ and he was talking and disputing with the Greek-speaking Jews.^&#42;1^ But these made attempts to do away with him.

[NOTE]
====
. Lit., “the Hellenists.” J17, “the Grecian Jews.”
====

[[v44-9-30]]

^<<v44-9-30,30>>^ When the brothers detected this, they brought him down to Caes·a·reʹa and sent him off to Tarsus.

[[v44-9-31]]

^<<v44-9-31,31>>^ Then, indeed, the congregation throughout the whole of Ju·deʹa and Galʹi·lee and Sa·marʹi·a entered into a period of peace, being built up; and as it walked in the fear of Jehovah^&#42;1^ and in the comfort of the holy spirit it kept on multiplying.

[NOTE]
====
. See App 1D.
====

[[v44-9-32]]

^<<v44-9-32,32>>^ Now as Peter was going through all &#91;parts&#93; he came down also to the holy ones^&#42;1^ that dwelt in Lydʹda.

[NOTE]
====
. Or, “the saints.”
====

[[v44-9-33]]

^<<v44-9-33,33>>^ There he found a certain man named Ae·neʹas, who had been lying flat on his cot for eight years, as he was paralyzed.

[[v44-9-34]]

^<<v44-9-34,34>>^ And Peter said to him: “Ae·neʹas, Jesus Christ heals you. Rise and make up your bed.” And he rose immediately.

[[v44-9-35]]

^<<v44-9-35,35>>^ And all those who inhabited Lydʹda and the &#91;plain of&#93; Sharʹon^&#42;1^ saw him, and these turned to the Lord.

[NOTE]
====
. “Sharon,” J17,​18,​22; אAB, “Saron.”
====

[[v44-9-36]]

^<<v44-9-36,36>>^ But in Jopʹpa there was a certain disciple named Tabʹi·tha, which, when translated, means Dorʹcas.^&#42;1^ She abounded in good deeds and gifts of mercy that she was rendering.

[NOTE]
====
. “Dorcas” (Gr.) corresponds with “Tabitha” (Aram.); both names mean “Gazelle.”
====

[[v44-9-37]]

^<<v44-9-37,37>>^ But in those days she happened to fall sick and die. So they bathed her and laid her in an upper chamber.

[[v44-9-38]]

^<<v44-9-38,38>>^ Now as Lydʹda was near Jopʹpa, when the disciples heard that Peter was in this city they dispatched two men to him to entreat &#91;him&#93;: “Please do not hesitate^&#42;1^ to come on as far as us.”

[NOTE]
====
. Or, “do not delay.”
====

[[v44-9-39]]

^<<v44-9-39,39>>^ At that Peter rose and went with them. And when he arrived, they led him up into the upper chamber; and all the widows presented themselves to him weeping and exhibiting many inner garments and outer garments that Dorʹcas used to make while she was with them.

[[v44-9-40]]

^<<v44-9-40,40>>^ But Peter put everybody outside and, bending his knees, he prayed, and, turning to the body, he said: “Tabʹi·tha,^&#42;1^ rise!” She opened her eyes and, as she caught sight of Peter, she sat up.

[NOTE]
====
. See vs 36 ftn.
====

[[v44-9-41]]

^<<v44-9-41,41>>^ Giving her his hand, he raised her up, and he called the holy ones and the widows and presented her alive.

[[v44-9-42]]

^<<v44-9-42,42>>^ This became known throughout all Jopʹpa, and many became believers on the Lord.

[[v44-9-43]]

^<<v44-9-43,43>>^ For quite a few days he remained in Jopʹpa with a certain Simon, a tanner.

'''

xref:044-acts/044-acts-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-acts/044-acts-010.adoc#v44-10-0[Próximo Capítulo &#62;]