include::./index.adoc[]

[[v44-26-0]]
=== Acts of Apostles, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-26-1]]

^<<v44-26-1,1>>^ A·gripʹpa said to Paul: “You are permitted to speak in behalf of yourself.” Then Paul stretched his hand out and proceeded to say in his defense:

[[v44-26-2]]

^<<v44-26-2,2>>^ “Concerning all the things of which I am accused by Jews, King A·gripʹpa, I count myself happy that it is before you I am to make my defense this day,

[[v44-26-3]]

^<<v44-26-3,3>>^ especially as you are expert on all the customs as well as the controversies among Jews. Therefore I beg you to hear me patiently.

[[v44-26-4]]

^<<v44-26-4,4>>^ “Indeed, as to the manner of life from youth up that I led from &#91;the&#93; beginning among my nation and in Jerusalem, all the Jews

[[v44-26-5]]

^<<v44-26-5,5>>^ that have been previously acquainted with me from the first know, if they but wish to bear witness, that according to the strictest sect of our form of worship^&#42;1^ I lived a Pharisee.

[NOTE]
====
. Or, “sect of our religion.” Lat., secʹtam noʹstrae re·li·gi·oʹnis.
====

[[v44-26-6]]

^<<v44-26-6,6>>^ And yet now for the hope of the promise that was made by God to our forefathers I stand called to judgment;

[[v44-26-7]]

^<<v44-26-7,7>>^ whereas our twelve tribes are hoping to attain to the fulfillment of this promise by intensely rendering him sacred service^&#42;1^ night and day. Concerning this hope I am accused by Jews, O king.

[NOTE]
====
. Lit., “rendering sacred service.” J13-17, “serving (worshiping) Jehovah.”
====

[[v44-26-8]]

^<<v44-26-8,8>>^ “Why is it judged unbelievable among YOU men that God raises up the dead?

[[v44-26-9]]

^<<v44-26-9,9>>^ I, for one, really thought within myself I ought to commit many acts of opposition against the name of Jesus the Naz·a·reneʹ;

[[v44-26-10]]

^<<v44-26-10,10>>^ which, in fact, I did in Jerusalem, and many of the holy ones I locked up in prisons, as I had received authority from the chief priests; and when they were to be executed, I cast my vote^&#42;1^ against them.

[NOTE]
====
. Lit., “[voting] pebble.” Gr., pseʹphon. See Re 2:17 ftn, “Pebble.”
====

[[v44-26-11]]

^<<v44-26-11,11>>^ And by punishing them many times in all the synagogues I tried to force them to make a recantation; and since I was extremely mad against them, I went so far as to persecuting them even in outside cities.

[[v44-26-12]]

^<<v44-26-12,12>>^ “Amid these efforts as I was journeying to Damascus with authority and a commission from the chief priests,

[[v44-26-13]]

^<<v44-26-13,13>>^ I saw at midday on the road, O king, a light beyond the brilliance of the sun flash from heaven about me and about those journeying with me.

[[v44-26-14]]

^<<v44-26-14,14>>^ And when we had all fallen to the ground I heard a voice say to me in the Hebrew language, ‘Saul, Saul, why are you persecuting me? To keep kicking against the goads makes it hard for you.’

[[v44-26-15]]

^<<v44-26-15,15>>^ But I said, ‘Who are you, Lord?’ And the Lord said, ‘I am Jesus, whom you are persecuting.

[[v44-26-16]]

^<<v44-26-16,16>>^ Nevertheless, rise and stand on your feet. For to this end I have made myself visible to you, in order to choose you as an attendant and a witness both of things you have seen and things I shall make you see respecting me;

[[v44-26-17]]

^<<v44-26-17,17>>^ while I deliver you from &#91;this&#93; people and from the nations, to whom I am sending you,

[[v44-26-18]]

^<<v44-26-18,18>>^ to open their eyes, to turn them from darkness to light and from the authority of Satan to God, in order for them to receive forgiveness of sins and an inheritance among those sanctified by &#91;their&#93; faith in me.’

[[v44-26-19]]

^<<v44-26-19,19>>^ “Wherefore, King A·gripʹpa, I did not become disobedient to the heavenly sight,

[[v44-26-20]]

^<<v44-26-20,20>>^ but both to those in Damascus first and to those in Jerusalem, and over all the country of Ju·deʹa, and to the nations I went bringing the message that they should repent and turn to God by doing works that befit repentance.^&#42;1^

[NOTE]
====
. Lit., “change of mind.” Gr., me·ta·noiʹas.
====

[[v44-26-21]]

^<<v44-26-21,21>>^ On account of these things Jews seized me in the temple and attempted to slay me.

[[v44-26-22]]

^<<v44-26-22,22>>^ However, because I have obtained the help that is from God I continue to this day bearing witness to both small and great, but saying nothing except things the Prophets as well as Moses stated were going to take place,

[[v44-26-23]]

^<<v44-26-23,23>>^ that the Christ was to suffer and, as the first to be resurrected^&#42;1^ from the dead, he was going to publish light both to this people and to the nations.”

[NOTE]
====
. Lit., “first out of resurrection.”
====

[[v44-26-24]]

^<<v44-26-24,24>>^ Now as he was saying these things in his defense, Festus said in a loud voice: “You are going mad, Paul! Great learning is driving you into madness!”

[[v44-26-25]]

^<<v44-26-25,25>>^ But Paul said: “I am not going mad, Your Excellency Festus, but I am uttering sayings of truth and of soundness of mind.

[[v44-26-26]]

^<<v44-26-26,26>>^ In reality, the king to whom I am speaking with freeness of speech well knows about these things; for I am persuaded that not one of these things escapes his notice, for this thing has not been done in a corner.

[[v44-26-27]]

^<<v44-26-27,27>>^ Do you, King A·gripʹpa, believe the Prophets? I know you believe.”

[[v44-26-28]]

^<<v44-26-28,28>>^ But A·gripʹpa said to Paul: “In a short time you would persuade me to become a Christian.”^&#42;1^

[NOTE]
====
. “A Christian.” Gr., Khri·sti·a·nonʹ; Lat., Chri·sti·aʹnum.
====

[[v44-26-29]]

^<<v44-26-29,29>>^ At this Paul said: “I could wish to God that whether in a short time or in a long time not only you but also all those who hear me today would become men such as I also am, with the exception of these bonds.”

[[v44-26-30]]

^<<v44-26-30,30>>^ And the king rose and so did the governor and Ber·niʹce and the men seated with them.

[[v44-26-31]]

^<<v44-26-31,31>>^ But as they withdrew they began talking with one another, saying: “This man practices nothing deserving death or bonds.”

[[v44-26-32]]

^<<v44-26-32,32>>^ Moreover, A·gripʹpa said to Festus: “This man could have been released if he had not appealed to Caesar.”^&#42;1^

[NOTE]
====
. Or, “the emperor.”
====

'''

xref:044-acts/044-acts-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-acts/044-acts-027.adoc#v44-27-0[Próximo Capítulo &#62;]