include::./index.adoc[]

[[v44-28-0]]
=== Acts of Apostles, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-28-1]]

^<<v44-28-1,1>>^ And when we had made it to safety, then we learned that the island was called Malta.^&#42;1^

[NOTE]
====
. “Melita,” אAB.
====

[[v44-28-2]]

^<<v44-28-2,2>>^ And the foreign-speaking people^&#42;1^ showed us extraordinary human kindness,^&#42;2^ for they kindled a fire and received all of us helpfully because of the rain that was falling and because of the cold.

[NOTE]
====
. Or, “the barbarians.”
. Lit., “affection for mankind.” Gr., phi·lan·thro·piʹan. Compare Tit 3:4 ftn.
====

[[v44-28-3]]

^<<v44-28-3,3>>^ But when Paul collected a certain bundle of sticks and laid it upon the fire, a viper came out due to the heat and fastened itself on his hand.

[[v44-28-4]]

^<<v44-28-4,4>>^ When the foreign-speaking people caught sight of the venomous creature hanging from his hand, they began saying to one another: “Surely this man is a murderer, and although he made it to safety from the sea, vindictive justice did not permit him to keep on living.”

[[v44-28-5]]

^<<v44-28-5,5>>^ However, he shook the venomous creature off into the fire and suffered no harm.

[[v44-28-6]]

^<<v44-28-6,6>>^ But they were expecting he was going to swell up with inflammation or suddenly drop dead. After they waited for a long while and beheld nothing hurtful happen to him, they changed their mind and began saying he was a god.

[[v44-28-7]]

^<<v44-28-7,7>>^ Now in the neighborhood of that place the principal man of the island, named Pubʹli·us, had lands; and he received us hospitably and entertained us benevolently three days.

[[v44-28-8]]

^<<v44-28-8,8>>^ But it happened that the father of Pubʹli·us was lying down distressed with fever and dysentery, and Paul went in to him and prayed, laid his hands upon him and healed him.

[[v44-28-9]]

^<<v44-28-9,9>>^ After this occurred, the rest of the people on the island who had sicknesses also began to come to him and be cured.

[[v44-28-10]]

^<<v44-28-10,10>>^ And they also honored us with many gifts and, when we were setting sail, they loaded us with things for our needs.

[[v44-28-11]]

^<<v44-28-11,11>>^ Three months later we set sail in a boat from Alexandria that had wintered in the island and with the figurehead “Sons of Zeus.”^&#42;1^

[NOTE]
====
. Or, “Dioscuri,” the twin brothers Castor and Pollux.
====

[[v44-28-12]]

^<<v44-28-12,12>>^ And putting into port at Syracuse we remained three days,

[[v44-28-13]]

^<<v44-28-13,13>>^ from which place we went around and arrived at Rheʹgi·um. And a day later a south wind sprang up and we made it into Pu·teʹo·li^&#42;1^ on the second day.

[NOTE]
====
. Now called Pozzuoli.
====

[[v44-28-14]]

^<<v44-28-14,14>>^ Here we found brothers and were entreated to remain with them seven days; and in this way we came toward Rome.

[[v44-28-15]]

^<<v44-28-15,15>>^ And from there the brothers, when they heard the news about us, came to meet us as far as the Marketplace of Apʹpi·us^&#42;1^ and Three Taverns^&#42;2^ and, upon catching sight of them, Paul thanked God and took courage.

[NOTE]
====
. Or, “Appii Forum.” Lat., Apʹpi·i Foʹrum.
. Or, “Tres Tabernae.” Vgc(Lat.), tres Ta·berʹnas.
====

[[v44-28-16]]

^<<v44-28-16,16>>^ When, finally, we entered into Rome, Paul was permitted to stay by himself with the soldier guarding him.

[[v44-28-17]]

^<<v44-28-17,17>>^ However, three days later he called together those who were the principal men of the Jews. When they had assembled, he proceeded to say to them: “Men, brothers, although I had done nothing contrary to the people or the customs of our forefathers, I was delivered over as a prisoner from Jerusalem into the hands of the Romans.

[[v44-28-18]]

^<<v44-28-18,18>>^ And these, after making an examination, were desirous of releasing me, as there was no cause for death in me.

[[v44-28-19]]

^<<v44-28-19,19>>^ But when the Jews kept speaking against it, I was compelled to appeal to Caesar,^&#42;1^ but not as though I had anything of which to accuse my nation.

[NOTE]
====
. Or, “the emperor.”
====

[[v44-28-20]]

^<<v44-28-20,20>>^ Really on this account I entreated to see and speak to YOU, for because of the hope of Israel this chain I have around me.”

[[v44-28-21]]

^<<v44-28-21,21>>^ They said to him: “Neither have we received letters concerning you from Ju·deʹa, nor has anyone of the brothers that has arrived reported or spoken anything wicked about you.

[[v44-28-22]]

^<<v44-28-22,22>>^ But we think it proper to hear from you what your thoughts are, for truly as regards this sect it is known to us that everywhere it is spoken against.”

[[v44-28-23]]

^<<v44-28-23,23>>^ They now arranged for a day with him, and they came in greater numbers to him in his lodging place. And he explained the matter to them by bearing thorough witness concerning the kingdom of God and by using persuasion with them concerning Jesus from both the law of Moses and the Prophets, from morning till evening.

[[v44-28-24]]

^<<v44-28-24,24>>^ And some began to believe the things said; others would not believe.

[[v44-28-25]]

^<<v44-28-25,25>>^ So, because they were at disagreement with one another, they began to depart, while Paul made this one comment:
“The holy spirit aptly spoke through Isaiah the prophet to YOUR forefathers,

[[v44-28-26]]

^<<v44-28-26,26>>^ saying, ‘Go to this people and say: “By hearing, YOU will hear but by no means understand; and, looking, YOU will look but by no means see.

[[v44-28-27]]

^<<v44-28-27,27>>^ For the heart of this people has grown unreceptive,^&#42;1^ and with their ears they have heard without response, and they have shut their eyes; that they should never see with their eyes and hear with their ears and understand with their heart and turn back, and I should heal them.”’

[NOTE]
====
. Lit., “was thickened (fattened).”
====

[[v44-28-28]]

^<<v44-28-28,28>>^ Therefore let it be known to YOU that this, the means by which God saves,^&#42;1^ has been sent out to the nations; they will certainly listen to it.”

[NOTE]
====
. Or, “this salvation of God.”
====

[[v44-28-29]]

^<<v44-28-29,29>>^ ^&#42;1^ ——

[NOTE]
====
. אAB omit vs 29; ItmssVgc, “And when he had said this, the Jews went away, having a great deal of disputing among themselves.”
====

[[v44-28-30]]

^<<v44-28-30,30>>^ So he remained for an entire two years in his own hired house, and he would kindly receive all those who came in to him,

[[v44-28-31]]

^<<v44-28-31,31>>^ preaching^&#42;1^ the kingdom of God to them and teaching the things concerning the Lord Jesus Christ with the greatest freeness of speech, without hindrance.

[NOTE]
====
. Or, “heralding.” Gr., ke·rysʹson; Lat., praeʹdi·cans. Compare Da 5:29 ftn, “Heralded.”
====

'''

xref:044-acts/044-acts-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romans/045-romans-001.adoc#v45-1-0[Próximo Capítulo &#62;]