include::./index.adoc[]

[[v44-18-0]]
=== Acts of Apostles, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-18-1]]

^<<v44-18-1,1>>^ After these things he departed from Athens and came to Corinth.

[[v44-18-2]]

^<<v44-18-2,2>>^ And he found a certain Jew named Aqʹui·la, a native of Ponʹtus who had recently come from Italy, and Pris·cilʹla his wife, because of the fact that Claudius had ordered all the Jews to depart from Rome. So he went to them

[[v44-18-3]]

^<<v44-18-3,3>>^ and on account of being of the same trade he stayed at their home, and they worked, for they were tentmakers by trade.

[[v44-18-4]]

^<<v44-18-4,4>>^ However, he would give a talk in the synagogue every sabbath and would persuade Jews and Greeks.^&#42;1^

[NOTE]
====
. Lit., “Hellenes.” Gr., Helʹle·nas.
====

[[v44-18-5]]

^<<v44-18-5,5>>^ When, now, both Silas and Timothy came down from Mac·e·doʹni·a, Paul began to be intensely occupied with the word, witnessing to the Jews to prove that Jesus is the Christ.

[[v44-18-6]]

^<<v44-18-6,6>>^ But after they kept on opposing and speaking abusively, he shook out his garments and said to them: “Let YOUR blood be upon YOUR own heads. I am clean. From now on I will go to people of the nations.”

[[v44-18-7]]

^<<v44-18-7,7>>^ Accordingly he transferred from there and went into the house of a man named Titius Justus, a worshiper of God, whose house was adjoining the synagogue.

[[v44-18-8]]

^<<v44-18-8,8>>^ But Crisʹpus the presiding officer of the synagogue became a believer in the Lord, and so did all his household. And many of the Corinthians that heard began to believe and be baptized.

[[v44-18-9]]

^<<v44-18-9,9>>^ Moreover, by night the Lord said to Paul through a vision: “Have no fear, but keep on speaking and do not keep silent,

[[v44-18-10]]

^<<v44-18-10,10>>^ because I am with you and no man will assault you so as to do you injury; for I have many people in this city.”

[[v44-18-11]]

^<<v44-18-11,11>>^ So he stayed set there a year and six months, teaching among them the word of God.

[[v44-18-12]]

^<<v44-18-12,12>>^ Now while Galʹli·o was proconsul^&#42;1^ of A·chaʹia,^&#42;2^ the Jews rose up with one accord against Paul and led him to the judgment seat,

[NOTE]
====
. A provincial governor for the Roman Senate.
. The Roman province of southern Greece with its capital at Corinth.
====

[[v44-18-13]]

^<<v44-18-13,13>>^ saying: “Contrary to the law this person leads men to another persuasion in worshiping God.”

[[v44-18-14]]

^<<v44-18-14,14>>^ But as Paul was going to open his mouth, Galʹli·o said to the Jews: “If it were, indeed, some wrong or a wicked act of villainy, O Jews, I would with reason put up patiently with YOU.

[[v44-18-15]]

^<<v44-18-15,15>>^ But if it is controversies over speech and names and the law among YOU, YOU yourselves must see to it. I do not wish to be a judge of these things.”

[[v44-18-16]]

^<<v44-18-16,16>>^ With that he drove them away from the judgment seat.

[[v44-18-17]]

^<<v44-18-17,17>>^ So they all laid hold of Sosʹthe·nes the presiding officer of the synagogue and went to beating him in front of the judgment seat. But Galʹli·o would not concern himself at all with these things.

[[v44-18-18]]

^<<v44-18-18,18>>^ However, after staying quite some days longer, Paul said good-bye to the brothers and proceeded to sail away for Syria, and with him Pris·cilʹla and Aqʹui·la, as he had the hair of his head clipped short in Cenʹchre·ae,^&#42;1^ for he had a vow.

[NOTE]
====
. Corinth’s seaport for eastern points.
====

[[v44-18-19]]

^<<v44-18-19,19>>^ So they arrived at Ephʹe·sus, and he left them there; but he himself entered into the synagogue and reasoned with the Jews.

[[v44-18-20]]

^<<v44-18-20,20>>^ Although they kept requesting him to remain for a longer time, he would not consent

[[v44-18-21]]

^<<v44-18-21,21>>^ but said good-bye and told them: “I will return to YOU again, if Jehovah^&#42;1^ is willing.” And he put out to sea from Ephʹe·sus

[NOTE]
====
. See App 1D.
====

[[v44-18-22]]

^<<v44-18-22,22>>^ and came down to Caes·a·reʹa. And he went up^&#42;1^ and greeted the congregation, and went down to Antioch.

[NOTE]
====
. To Jerusalem, apparently.
====

[[v44-18-23]]

^<<v44-18-23,23>>^ And when he had passed some time there he departed and went from place to place through the country of Ga·laʹti·a and Phrygʹi·a, strengthening all the disciples.

[[v44-18-24]]

^<<v44-18-24,24>>^ Now a certain Jew named A·polʹlos, a native of Alexandria, an eloquent man, arrived in Ephʹe·sus; and he was well versed in the Scriptures.

[[v44-18-25]]

^<<v44-18-25,25>>^ This &#91;man&#93; had been orally instructed in the way of Jehovah^&#42;1^ and, as he was aglow with the spirit, he went speaking and teaching with correctness the things about Jesus, but being acquainted with only the baptism of John.

[NOTE]
====
. See App 1D.
====

[[v44-18-26]]

^<<v44-18-26,26>>^ And this &#91;man&#93; started to speak boldly in the synagogue. When Pris·cilʹla and Aqʹui·la heard him, they took him into their company and expounded the way of God more correctly to him.

[[v44-18-27]]

^<<v44-18-27,27>>^ Further, because he was desiring to go across into A·chaʹia, the brothers wrote the disciples, exhorting them to receive him kindly. So when he got there, he greatly helped those who had believed on account of &#91;God’s&#93;^&#42;1^ undeserved kindness;

[NOTE]
====
. Lit., “the.”
====

[[v44-18-28]]

^<<v44-18-28,28>>^ for with intensity he thoroughly proved the Jews to be wrong publicly, while he demonstrated by the Scriptures that Jesus was the Christ.

'''

xref:044-acts/044-acts-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-acts/044-acts-019.adoc#v44-19-0[Próximo Capítulo &#62;]