include::./index.adoc[]

[[v44-11-0]]
=== Acts of Apostles, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-11-1]]

^<<v44-11-1,1>>^ Now the apostles and the brothers that were in Ju·deʹa heard that people of the nations had also received the word of God.

[[v44-11-2]]

^<<v44-11-2,2>>^ So when Peter came up to Jerusalem, the &#91;supporters&#93; of circumcision began to contend with him,

[[v44-11-3]]

^<<v44-11-3,3>>^ saying he had gone into the house of men that were not circumcised and had eaten with them.

[[v44-11-4]]

^<<v44-11-4,4>>^ At this Peter commenced and went on to explain the particulars to them, saying:

[[v44-11-5]]

^<<v44-11-5,5>>^ “I was in the city of Jopʹpa praying, and in a trance I saw a vision, some sort of vessel descending like a great linen sheet being let down by its four extremities from heaven, and it came clear to me.

[[v44-11-6]]

^<<v44-11-6,6>>^ Gazing into it, I made observations and saw four-footed creatures of the earth and wild beasts and creeping things and birds of heaven.

[[v44-11-7]]

^<<v44-11-7,7>>^ I also heard a voice say to me, ‘Rise, Peter, slaughter and eat!’

[[v44-11-8]]

^<<v44-11-8,8>>^ But I said, ‘Not at all, Lord, because a defiled or unclean thing has never entered into my mouth.’

[[v44-11-9]]

^<<v44-11-9,9>>^ The second time the voice from heaven answered, ‘You stop calling defiled the things God has cleansed.’

[[v44-11-10]]

^<<v44-11-10,10>>^ This occurred for a third time, and everything was pulled up again into heaven.

[[v44-11-11]]

^<<v44-11-11,11>>^ Also, look! at that instant there were three men standing at the house in which we were, they having been dispatched from Caes·a·reʹa to me.

[[v44-11-12]]

^<<v44-11-12,12>>^ So the spirit told me to go with them, not doubting at all. But these six brothers also went with me, and we entered into the house of the man.

[[v44-11-13]]

^<<v44-11-13,13>>^ “He reported to us how he saw the angel stand in his house and say, ‘Dispatch men to Jopʹpa and send for Simon who is surnamed Peter,

[[v44-11-14]]

^<<v44-11-14,14>>^ and he will speak those things to you by which you and all your household may get saved.’

[[v44-11-15]]

^<<v44-11-15,15>>^ But when I started to speak, the holy spirit fell upon them just as it did also upon us in &#91;the&#93; beginning.

[[v44-11-16]]

^<<v44-11-16,16>>^ At this I called to mind the saying of the Lord, how he used to say, ‘John, for his part, baptized with water, but YOU will be baptized in holy spirit.’

[[v44-11-17]]

^<<v44-11-17,17>>^ If, therefore, God gave the same free gift to them as he also did to us who have believed upon the Lord Jesus Christ, who was I that I should be able to hinder God?”

[[v44-11-18]]

^<<v44-11-18,18>>^ Now when they heard these things, they acquiesced, and they glorified God, saying: “Well, then, God has granted repentance for the purpose of life to people of the nations also.”

[[v44-11-19]]

^<<v44-11-19,19>>^ Consequently those who had been scattered by the tribulation that arose over Stephen went through as far as Phoe·niʹcia and Cyʹprus and Antioch, but speaking the word to no one except to Jews only.

[[v44-11-20]]

^<<v44-11-20,20>>^ However, out of them there were some men of Cyʹprus and Cy·reʹne that came to Antioch and began talking to the Greek-speaking people,^&#42;1^ declaring the good news of the Lord Jesus.

[NOTE]
====
. “Greek-speaking people.” Lit., “Hellenists.” AD*, “Greeks.”
====

[[v44-11-21]]

^<<v44-11-21,21>>^ Furthermore, the hand of Jehovah^&#42;1^ was with them, and a great number that became believers turned to the Lord.

[NOTE]
====
. See App 1D.
====

[[v44-11-22]]

^<<v44-11-22,22>>^ The account about them got to the ears of the congregation that was in Jerusalem, and they sent out Barʹna·bas as far as Antioch.

[[v44-11-23]]

^<<v44-11-23,23>>^ When he arrived and saw the undeserved kindness of God, he rejoiced and began to encourage them all to continue in the Lord with hearty purpose;

[[v44-11-24]]

^<<v44-11-24,24>>^ for he was a good man and full of holy spirit and of faith. And a considerable crowd was added to the Lord.

[[v44-11-25]]

^<<v44-11-25,25>>^ So he went off to Tarsus to make a thorough search for Saul

[[v44-11-26]]

^<<v44-11-26,26>>^ and, after he found him, he brought him to Antioch. It thus came about that for a whole year they gathered together with them in the congregation and taught quite a crowd, and it was first in Antioch that the disciples were by divine providence called^&#42;1^ Christians.^&#42;2^

[NOTE]
====
. Or, “named.”
. “Christians.” Gr., Khri·sti·a·nousʹ; Lat., Chri·sti·aʹni; J17,​18,​22(Heb.), Meshi·chi·yimʹ, “Messia­nists.”
====

[[v44-11-27]]

^<<v44-11-27,27>>^ Now in these days prophets came down from Jerusalem to Antioch.

[[v44-11-28]]

^<<v44-11-28,28>>^ One of them named Agʹa·bus rose and proceeded to indicate through the spirit that a great famine was about to come upon the entire inhabited earth; which, for that matter, did take place in the time of Claudius.

[[v44-11-29]]

^<<v44-11-29,29>>^ So those of the disciples determined, each of them according as anyone could afford it, to send a relief ministration to the brothers dwelling in Ju·deʹa;

[[v44-11-30]]

^<<v44-11-30,30>>^ and this they did, dispatching it to the older men^&#42;1^ by the hand of Barʹna·bas and Saul.

[NOTE]
====
. Or, “elders.” Gr., pre·sby·teʹrous.
====

'''

xref:044-acts/044-acts-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-acts/044-acts-012.adoc#v44-12-0[Próximo Capítulo &#62;]