include::./index.adoc[]

[[v44-14-0]]
=== Acts of Apostles, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-14-1]]

^<<v44-14-1,1>>^ Now in I·coʹni·um they entered together into the synagogue of the Jews and spoke in such a manner that a great multitude of both Jews and Greeks became believers.

[[v44-14-2]]

^<<v44-14-2,2>>^ But the Jews that did not believe stirred up and wrongly influenced the souls of people of the nations against the brothers.

[[v44-14-3]]

^<<v44-14-3,3>>^ Therefore they spent considerable time speaking with boldness by the authority of Jehovah,^&#42;1^ who bore witness to the word of his undeserved kindness by granting signs and portents to occur through their hands.

[NOTE]
====
. See App 1D.
====

[[v44-14-4]]

^<<v44-14-4,4>>^ However, the multitude of the city was split, and some were for the Jews but others for the apostles.

[[v44-14-5]]

^<<v44-14-5,5>>^ Now when a violent attempt took place on the part of both people of the nations and Jews with their rulers, to treat them insolently and pelt them with stones,

[[v44-14-6]]

^<<v44-14-6,6>>^ they, on being informed of it, fled to the cities of Lyc·a·oʹni·a, Lysʹtra and Derʹbe and the country round about;

[[v44-14-7]]

^<<v44-14-7,7>>^ and there they went on declaring the good news.

[[v44-14-8]]

^<<v44-14-8,8>>^ Now in Lysʹtra there was sitting a certain man disabled in his feet, lame from his mother’s womb, and he had never walked at all.

[[v44-14-9]]

^<<v44-14-9,9>>^ This man was listening to Paul speak, who, on looking at him intently and seeing he had faith to be made well,^&#42;1^

[NOTE]
====
. Or, “to be saved.”
====

[[v44-14-10]]

^<<v44-14-10,10>>^ said with a loud voice: “Stand up erect on your feet.” And he leaped up and began walking.

[[v44-14-11]]

^<<v44-14-11,11>>^ And the crowds, seeing what Paul had done, raised their voices, saying in the Lyc·a·oʹni·an tongue: “The gods have become like humans and have come down to us!”

[[v44-14-12]]

^<<v44-14-12,12>>^ And they went calling Barʹna·bas Zeus,^&#42;1^ but Paul Herʹmes,^&#42;2^ since he was the one taking the lead in speaking.

[NOTE]
====
. Or, “Jupiter.” Gr., Diʹa; Lat., Ioʹvem.
. Or, “Mercury.” Gr., Her·menʹ; Lat., Mer·cuʹri·um.
====

[[v44-14-13]]

^<<v44-14-13,13>>^ And the priest of Zeus, whose &#91;temple&#93; was before the city,^&#42;1^ brought bulls and garlands to the gates and was desiring to offer sacrifices with the crowds.

[NOTE]
====
. Lit., “the (one) being before the city.”
====

[[v44-14-14]]

^<<v44-14-14,14>>^ However, when the apostles Barʹna·bas and Paul heard of it, they ripped their outer garments and leaped out into the crowd, crying out

[[v44-14-15]]

^<<v44-14-15,15>>^ and saying: “Men, why are YOU doing these things? We also are humans having the same infirmities as YOU do, and are declaring the good news to YOU, for YOU to turn from these vain things to the living God, who made the heaven and the earth and the sea and all the things in them.

[[v44-14-16]]

^<<v44-14-16,16>>^ In the past generations he permitted all the nations to go on in their ways,

[[v44-14-17]]

^<<v44-14-17,17>>^ although, indeed, he did not leave himself without witness in that he did good, giving YOU rains from heaven and fruitful seasons, filling YOUR hearts to the full with food and good cheer.”

[[v44-14-18]]

^<<v44-14-18,18>>^ And yet by saying these things they scarcely restrained the crowds from sacrificing to them.

[[v44-14-19]]

^<<v44-14-19,19>>^ But Jews arrived from Antioch and I·coʹni·um and persuaded the crowds, and they stoned Paul and dragged him outside the city, imagining he was dead.

[[v44-14-20]]

^<<v44-14-20,20>>^ However, when the disciples surrounded him, he rose up and entered into the city. And on the next day he left with Barʹna·bas for Derʹbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ And after declaring the good news to that city and making quite a few disciples, they returned to Lysʹtra and to I·coʹni·um and to Antioch,

[[v44-14-22]]

^<<v44-14-22,22>>^ strengthening the souls of the disciples, encouraging them to remain in the faith and &#91;saying&#93;: “We must enter into the kingdom of God through many tribulations.”

[[v44-14-23]]

^<<v44-14-23,23>>^ Moreover, they appointed^&#42;1^ older men for them in each congregation and, offering prayer with fastings, they committed them to Jehovah^&#42;2^ in whom they had become believers.

[NOTE]
====
. Lit., “having appointed [by extended hand].”
. See App 1D.
====

[[v44-14-24]]

^<<v44-14-24,24>>^ And they went through Pi·sidʹi·a and came into Pam·phylʹi·a,

[[v44-14-25]]

^<<v44-14-25,25>>^ and, after speaking the word^&#42;1^ in Perga, they went down to At·ta·liʹa.

[NOTE]
====
. “Word,” BD; אACVgSyp, “word of the Lord”; P74, “word of God”; J17, “word of Jehovah.”
====

[[v44-14-26]]

^<<v44-14-26,26>>^ And from there they sailed off for Antioch, where they had been entrusted to the undeserved kindness of God for the work they had fully performed.

[[v44-14-27]]

^<<v44-14-27,27>>^ When they had arrived and had gathered the congregation together, they proceeded to relate the many things God had done by means of them, and that he had opened to the nations the door to^&#42;1^ faith.

[NOTE]
====
. Or, “of.”
====

[[v44-14-28]]

^<<v44-14-28,28>>^ So they spent not a little time with the disciples.

'''

xref:044-acts/044-acts-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-acts/044-acts-015.adoc#v44-15-0[Próximo Capítulo &#62;]