include::./index.adoc[]

[[v44-22-0]]
=== Acts of Apostles, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-22-1]]

^<<v44-22-1,1>>^ “Men, brothers and fathers, hear my defense to YOU now.”

[[v44-22-2]]

^<<v44-22-2,2>>^ (Well, when they heard he was addressing them in the Hebrew language, they kept all the more silent, and he said:)

[[v44-22-3]]

^<<v44-22-3,3>>^ “I am a Jew, born in Tarsus of Ci·liʹcia, but educated in this city at the feet of Ga·maʹli·el, instructed according to the strictness of the ancestral Law, being zealous for God just as all of YOU are this day.

[[v44-22-4]]

^<<v44-22-4,4>>^ And I persecuted this Way to the death, binding and handing over to prisons both men and women,

[[v44-22-5]]

^<<v44-22-5,5>>^ as both the high priest and all the assembly of older men^&#42;1^ can bear me witness. From them I also procured letters to the brothers in Damascus, and I was on my way to bring also those who were there bound to Jerusalem to be punished.

[NOTE]
====
. Or, “assembly of elders; presbytery.” Gr., pre·sby·teʹri·on.
====

[[v44-22-6]]

^<<v44-22-6,6>>^ “But as I was journeying and drawing close to Damascus, about midday, suddenly out of heaven a great light flashed all around me,

[[v44-22-7]]

^<<v44-22-7,7>>^ and I fell to the ground and heard a voice say to me, ‘Saul, Saul, why are you persecuting me?’

[[v44-22-8]]

^<<v44-22-8,8>>^ I answered, ‘Who are you, Lord?’ And he said to me, ‘I am Jesus the Naz·a·reneʹ, whom you are persecuting.’

[[v44-22-9]]

^<<v44-22-9,9>>^ Now the men that were with me beheld, indeed, the light but did not hear^&#42;1^ the voice of the one speaking to me.

[NOTE]
====
. Or, “hear understandingly,” as Paul did in vs 7.
====

[[v44-22-10]]

^<<v44-22-10,10>>^ At that I said, ‘What shall^&#42;1^ I do, Lord?’ The Lord said to me, ‘Rise, go your way into Damascus, and there you will be told about everything it is appointed for you to do.’

[NOTE]
====
. Or, “must.”
====

[[v44-22-11]]

^<<v44-22-11,11>>^ But as I could not see anything for the glory of that light, I arrived in Damascus, being led by the hand of those who were with me.

[[v44-22-12]]

^<<v44-22-12,12>>^ “Now An·a·niʹas, a certain man reverent according to the Law, well reported on by all the Jews dwelling there,

[[v44-22-13]]

^<<v44-22-13,13>>^ came to me and, standing by me, he said to me, ‘Saul, brother, have your sight again!’^&#42;1^ And I looked up at him that very hour.

[NOTE]
====
. Or, “brother, look up!”
====

[[v44-22-14]]

^<<v44-22-14,14>>^ He said, ‘The God of our forefathers has chosen you to come to know his will and to see the righteous One and to hear the voice of his mouth,

[[v44-22-15]]

^<<v44-22-15,15>>^ because you are to be a witness for him to all men of things you have seen and heard.

[[v44-22-16]]

^<<v44-22-16,16>>^ And now why are you delaying? Rise, get baptized and wash your sins away by your calling^&#42;1^ upon his name.’

[NOTE]
====
. Or, “wash your sins away and call.”
====

[[v44-22-17]]

^<<v44-22-17,17>>^ “But when I had returned to Jerusalem and was praying in the temple, I fell into a trance^&#42;1^

[NOTE]
====
. “I fell into a trance,” אAB; J13,​14,​17,​22, “Jehovah’s hand was upon me”; J18, “Jehovah’s spirit clothed me.”
====

[[v44-22-18]]

^<<v44-22-18,18>>^ and saw him saying to me, ‘Hurry up and get out of Jerusalem quickly, because they will not agree to your witness concerning me.’

[[v44-22-19]]

^<<v44-22-19,19>>^ And I said, ‘Lord, they themselves well know that I used to imprison and flog in one synagogue after another those believing upon you;

[[v44-22-20]]

^<<v44-22-20,20>>^ and when the blood of Stephen your witness was being spilled, I myself was also standing by and approving and guarding the outer garments of those doing away with him.’

[[v44-22-21]]

^<<v44-22-21,21>>^ And yet he said to me, ‘Get on your way, because I shall send you out to nations far off.’”

[[v44-22-22]]

^<<v44-22-22,22>>^ Now they kept listening to him down to this word, and they raised their voices, saying: “Take such a &#91;man&#93; away from the earth, for he was not fit to live!”

[[v44-22-23]]

^<<v44-22-23,23>>^ And because they were crying out and throwing their outer garments about and tossing dust into the air,

[[v44-22-24]]

^<<v44-22-24,24>>^ the military commander^&#42;1^ ordered him to be brought into the soldiers’ quarters and said he should be examined under scourging, that he might know fully for what cause they were shouting against him this way.

[NOTE]
====
. Lit., “chiliarch,” a commander of 1,000 soldiers.
====

[[v44-22-25]]

^<<v44-22-25,25>>^ But when they had stretched him out for the whipping,^&#42;1^ Paul said to the army officer^&#42;2^ standing there: “Is it lawful for YOU men to scourge a man that is a Roman and uncondemned?”

[NOTE]
====
. Or, “stretched him out with the straps.”
. Lit., “centurion,” a commander of 100 soldiers.
====

[[v44-22-26]]

^<<v44-22-26,26>>^ Well, when the army officer heard this, he went to the military commander and made report, saying: “What are you intending to do? Why, this man is a Roman.”

[[v44-22-27]]

^<<v44-22-27,27>>^ So the military commander approached and said to him: “Tell me, Are you a Roman?” He said: “Yes.”

[[v44-22-28]]

^<<v44-22-28,28>>^ The military commander responded: “I purchased these rights as a citizen^&#42;1^ for a large sum &#91;of money&#93;.” Paul said: “But I was even born &#91;in them&#93;.”^&#42;2^

[NOTE]
====
. Or, “I purchased this citizenship.”
. Or, “[in it].”
====

[[v44-22-29]]

^<<v44-22-29,29>>^ Immediately, therefore, the men that were about to examine him with torture withdrew from him; and the military commander became afraid on ascertaining that he was a Roman and that he had bound him.

[[v44-22-30]]

^<<v44-22-30,30>>^ So, the next day, as he desired to know for sure just why he was being accused by the Jews, he let him loose and commanded the chief priests and all the Sanʹhe·drin to assemble. And he brought Paul down and stood him among them.

'''

xref:044-acts/044-acts-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-acts/044-acts-023.adoc#v44-23-0[Próximo Capítulo &#62;]