include::./index.adoc[]

[[v44-10-0]]
=== Acts of Apostles, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-10-1]]

^<<v44-10-1,1>>^ Now in Caes·a·reʹa there was a certain man named Cornelius, an army officer^&#42;1^ of the Italian band, as it was called,

[NOTE]
====
. Or, “a centurion,” in command of 100 soldiers.
====

[[v44-10-2]]

^<<v44-10-2,2>>^ a devout man and one fearing God together with all his household, and he made many gifts of mercy to the people and made supplication to God continually.

[[v44-10-3]]

^<<v44-10-3,3>>^ Just about the ninth hour^&#42;1^ of the day he saw plainly in a vision an angel of God come in to him and say to him: “Cornelius!”

[NOTE]
====
. That is, about 3 p.m., counting from sunrise.
====

[[v44-10-4]]

^<<v44-10-4,4>>^ The man gazed at him and, becoming frightened, said: “What is it, Lord?” He said to him: “Your prayers and gifts of mercy have ascended as a remembrance before God.

[[v44-10-5]]

^<<v44-10-5,5>>^ So now send men to Jopʹpa and summon a certain Simon who is surnamed Peter.

[[v44-10-6]]

^<<v44-10-6,6>>^ This man is being entertained by a certain Simon, a tanner, who has a house by the sea.”

[[v44-10-7]]

^<<v44-10-7,7>>^ As soon as the angel that spoke to him had left, he called two of his house servants and a devout soldier from among those who were in constant attendance upon him,

[[v44-10-8]]

^<<v44-10-8,8>>^ and he related everything to them and dispatched them to Jopʹpa.

[[v44-10-9]]

^<<v44-10-9,9>>^ The next day as they were pursuing their journey and were approaching the city, Peter went up to the housetop about the sixth hour^&#42;1^ to pray.

[NOTE]
====
. That is, about 12 noon, counting from sunrise.
====

[[v44-10-10]]

^<<v44-10-10,10>>^ But he became very hungry and wanted to eat. While they were preparing, he fell into a trance

[[v44-10-11]]

^<<v44-10-11,11>>^ and beheld heaven opened and some sort of vessel descending like a great linen sheet being let down by its four extremities upon the earth;

[[v44-10-12]]

^<<v44-10-12,12>>^ and in it there were all sorts of four-footed creatures and creeping things of the earth and birds of heaven.

[[v44-10-13]]

^<<v44-10-13,13>>^ And a voice came to him: “Rise, Peter, slaughter^&#42;1^ and eat!”

[NOTE]
====
. Or, “sacrifice.”
====

[[v44-10-14]]

^<<v44-10-14,14>>^ But Peter said: “Not at all, Lord, because never have I eaten anything defiled and unclean.”

[[v44-10-15]]

^<<v44-10-15,15>>^ And the voice &#91;spoke&#93; again to him, the second time: “You stop calling defiled the things God has cleansed.”

[[v44-10-16]]

^<<v44-10-16,16>>^ This occurred a third time, and immediately the vessel was taken up into heaven.

[[v44-10-17]]

^<<v44-10-17,17>>^ Now while Peter was in great perplexity inwardly over what the vision he had seen might mean, look! the men dispatched by Cornelius had made inquiries for Simon’s house and stood there at the gate.

[[v44-10-18]]

^<<v44-10-18,18>>^ And they called out and inquired whether Simon who was surnamed Peter was being entertained there.

[[v44-10-19]]

^<<v44-10-19,19>>^ As Peter was going over in his mind about the vision, the spirit said: “Look! Three^&#42;1^ men are seeking you.

[NOTE]
====
. “Three,” P74אACVgSyp; B, “Two.”
====

[[v44-10-20]]

^<<v44-10-20,20>>^ However, rise, go downstairs and be on your way with them, not doubting at all, because I have dispatched them.”

[[v44-10-21]]

^<<v44-10-21,21>>^ So Peter went downstairs to the men and said: “Look! I am the one YOU are seeking. What is the cause for which YOU are present?”

[[v44-10-22]]

^<<v44-10-22,22>>^ They said: “Cornelius, an army officer, a man righteous and fearing God and well reported by the whole nation of the Jews, was given divine instructions^&#42;1^ by a holy angel to send for you to come to his house and to hear the things you have to say.”

[NOTE]
====
. “Was given divine instructions,” אAB; J18, “was given a command of Jehovah.”
====

[[v44-10-23]]

^<<v44-10-23,23>>^ Therefore he invited them in and entertained them.
The next day he rose and went off with them, and some of the brothers that were from Jopʹpa went with him.

[[v44-10-24]]

^<<v44-10-24,24>>^ On the day after that he entered into Caes·a·reʹa. Cornelius, of course, was expecting them and had called together his relatives and intimate friends.

[[v44-10-25]]

^<<v44-10-25,25>>^ As Peter entered, Cornelius met him, fell down at his feet and did obeisance to him.

[[v44-10-26]]

^<<v44-10-26,26>>^ But Peter lifted him up, saying: “Rise; I myself am also a man.”

[[v44-10-27]]

^<<v44-10-27,27>>^ And as he conversed with him he went in and found many people assembled,

[[v44-10-28]]

^<<v44-10-28,28>>^ and he said to them: “YOU well know how unlawful it is for a Jew to join himself to or approach a man of another race; and yet God has shown me I should call no man defiled or unclean.

[[v44-10-29]]

^<<v44-10-29,29>>^ Hence I came, really without objection, when I was sent for. Therefore I inquire the reason that YOU have sent for me.”

[[v44-10-30]]

^<<v44-10-30,30>>^ Accordingly Cornelius said: “Four days ago counting from this hour I was praying in my house at the ninth hour,^&#42;1^ when, look! a man in bright raiment stood before me

[NOTE]
====
. See vs 3 ftn.
====

[[v44-10-31]]

^<<v44-10-31,31>>^ and said, ‘Cornelius, your prayer has been favorably heard and your gifts of mercy have been remembered before God.

[[v44-10-32]]

^<<v44-10-32,32>>^ Send, therefore, to Jopʹpa and call for Simon, who is surnamed Peter. This man is being entertained in the house of Simon, a tanner, by the sea.’

[[v44-10-33]]

^<<v44-10-33,33>>^ Therefore I at once sent to you, and you did well in coming here. And so at this time we are all present before God to hear all the things you have been commanded by Jehovah^&#42;1^ to say.”

[NOTE]
====
. “Jehovah,” J17,​18,​23; P45אABC(Gr.), tou Ky·riʹou; P74DSyp, “God.” See App 1D.
====

[[v44-10-34]]

^<<v44-10-34,34>>^ At this Peter opened his mouth and said: “For a certainty I perceive that God is not partial,

[[v44-10-35]]

^<<v44-10-35,35>>^ but in every nation the man that fears him and works righteousness is acceptable to him.

[[v44-10-36]]

^<<v44-10-36,36>>^ He sent out the word to the sons of Israel to declare to them the good news of peace through Jesus Christ: this One is Lord of all &#91;others&#93;.

[[v44-10-37]]

^<<v44-10-37,37>>^ YOU know the subject that was talked about throughout the whole of Ju·deʹa, starting from Galʹi·lee after the baptism that John preached,

[[v44-10-38]]

^<<v44-10-38,38>>^ namely, Jesus who was from Nazʹa·reth, how God anointed him with holy spirit and power, and he went through the land doing good and healing all those oppressed by the Devil; because God was with him.

[[v44-10-39]]

^<<v44-10-39,39>>^ And we are witnesses of all the things he did both in the country of the Jews and in Jerusalem; but they also did away with him by hanging him on a stake.^&#42;1^

[NOTE]
====
. Or, “tree.” See App 5C.
====

[[v44-10-40]]

^<<v44-10-40,40>>^ God raised this One up on the third day and granted him to become manifest,

[[v44-10-41]]

^<<v44-10-41,41>>^ not to all the people, but to witnesses appointed beforehand by God, to us, who ate and drank with him after his rising from the dead.

[[v44-10-42]]

^<<v44-10-42,42>>^ Also, he ordered us to preach to the people and to give a thorough witness that this is the One decreed by God to be judge of the living and the dead.

[[v44-10-43]]

^<<v44-10-43,43>>^ To him all the prophets bear witness, that everyone putting faith in him gets forgiveness of sins through his name.”

[[v44-10-44]]

^<<v44-10-44,44>>^ While Peter was yet speaking about these matters the holy spirit fell upon all those hearing the word.

[[v44-10-45]]

^<<v44-10-45,45>>^ And the faithful ones that had come with Peter who were of those circumcised were amazed, because the free gift of the holy spirit was being poured out also upon people of the nations.

[[v44-10-46]]

^<<v44-10-46,46>>^ For they heard them speaking with tongues and magnifying God. Then Peter responded:

[[v44-10-47]]

^<<v44-10-47,47>>^ “Can anyone forbid water so that these might not be baptized who have received the holy spirit even as we have?”

[[v44-10-48]]

^<<v44-10-48,48>>^ With that he commanded them to be baptized in the name of Jesus Christ. Then they requested him to remain for some days.

'''

xref:044-acts/044-acts-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-acts/044-acts-011.adoc#v44-11-0[Próximo Capítulo &#62;]