include::./index.adoc[]

[[v44-12-0]]
=== Acts of Apostles, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-12-1]]

^<<v44-12-1,1>>^ About that particular time Herod^&#42;1^ the king applied his hands to mistreating some of those of the congregation.

[NOTE]
====
. That is, Herod Agrippa I.
====

[[v44-12-2]]

^<<v44-12-2,2>>^ He did away with James the brother of John by the sword.

[[v44-12-3]]

^<<v44-12-3,3>>^ As he saw it was pleasing to the Jews, he went on to arrest Peter also. (As it was, those were days of the unfermented cakes.)

[[v44-12-4]]

^<<v44-12-4,4>>^ And laying hold of him, he put him in prison, turning him over to four shifts of four soldiers each to guard him, as he intended to produce him for the people after the passover.

[[v44-12-5]]

^<<v44-12-5,5>>^ Consequently Peter was being kept in the prison; but prayer to God for him was being carried on intensely by the congregation.

[[v44-12-6]]

^<<v44-12-6,6>>^ Now when Herod was about to produce him, that night Peter was sleeping bound with two chains between two soldiers, and guards before the door were keeping the prison.

[[v44-12-7]]

^<<v44-12-7,7>>^ But, look! Jehovah’s^&#42;1^ angel stood by, and a light shone in the prison cell. Striking Peter on the side, he roused him, saying: “Rise quickly!” And his chains fell off his hands.

[NOTE]
====
. See App 1D.
====

[[v44-12-8]]

^<<v44-12-8,8>>^ The angel said to him: “Gird yourself and bind your sandals on.” He did so. Finally he said to him: “Put your outer garment on and keep following me.”

[[v44-12-9]]

^<<v44-12-9,9>>^ And he went out and kept following him, but he did not know that what was happening through the angel was real. In fact, he supposed he was seeing a vision.

[[v44-12-10]]

^<<v44-12-10,10>>^ Going through the first sentinel guard and the second they got to the iron gate leading into the city, and this opened to them of its own accord. And after they went out they advanced down one street, and immediately the angel departed from him.

[[v44-12-11]]

^<<v44-12-11,11>>^ And Peter, coming to himself, said: “Now I actually know that Jehovah^&#42;1^ sent his angel forth and delivered me out of Herod’s hand and from all that the people of the Jews were expecting.”

[NOTE]
====
. See App 1D.
====

[[v44-12-12]]

^<<v44-12-12,12>>^ And after he considered it, he went to the house of Mary the mother of John who was surnamed Mark, where quite a few were gathered together and praying.

[[v44-12-13]]

^<<v44-12-13,13>>^ When he knocked at the door of the gateway, a servant girl named Rhoda came to attend to the call,

[[v44-12-14]]

^<<v44-12-14,14>>^ and, upon recognizing the voice of Peter, out of joy she did not open the gate, but ran inside and reported that Peter was standing before the gateway.

[[v44-12-15]]

^<<v44-12-15,15>>^ They said to her: “You are mad.” But she kept on strongly asserting it was so. They began to say: “It is his angel.”

[[v44-12-16]]

^<<v44-12-16,16>>^ But Peter remained there knocking. When they opened, they saw him and were astonished.

[[v44-12-17]]

^<<v44-12-17,17>>^ But he motioned to them with his hand to be silent and told them in detail how Jehovah^&#42;1^ brought him out of the prison, and he said: “Report these things to James and the brothers.” With that he went out and journeyed to another place.

[NOTE]
====
. See App 1D.
====

[[v44-12-18]]

^<<v44-12-18,18>>^ Well, when it became day, there was no little stir among the soldiers over what really had become of Peter.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herod made diligent search for him and, when not finding him, he examined the guards and commanded them to be led off &#91;to punishment&#93;; and he went down from Ju·deʹa to Caes·a·reʹa and spent some time there.

[[v44-12-20]]

^<<v44-12-20,20>>^ Now he was in a fighting mood against the people of Tyre and of Siʹdon. So with one accord they came^&#42;1^ to him and, after persuading Blastus, who was in charge of the bedchamber of the king, they began suing for peace, because their country was supplied with food from that of the king.

[NOTE]
====
. Or, “they began presenting themselves.” Lit., “they were alongside.”
====

[[v44-12-21]]

^<<v44-12-21,21>>^ But on a set day Herod clothed himself with royal raiment and sat down upon the judgment seat and began giving them a public address.

[[v44-12-22]]

^<<v44-12-22,22>>^ In turn the assembled people began shouting: “A god’s voice, and not a man’s!”

[[v44-12-23]]

^<<v44-12-23,23>>^ Instantly the angel of Jehovah^&#42;1^ struck him, because he did not give the glory to God; and he became eaten up with worms and expired.

[NOTE]
====
. See App 1D.
====

[[v44-12-24]]

^<<v44-12-24,24>>^ But the word of Jehovah^&#42;1^ went on growing and spreading.

[NOTE]
====
. “Of Jehovah,” J7,​8,​10,​23; B(Gr.), tou Ky·riʹou; P74אADSyp, “of God.” See App 1D.
====

[[v44-12-25]]

^<<v44-12-25,25>>^ As for Barʹna·bas and Saul, after having fully carried out the relief ministration in Jerusalem, they returned and took along with them John, the one surnamed Mark.

'''

xref:044-acts/044-acts-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-acts/044-acts-013.adoc#v44-13-0[Próximo Capítulo &#62;]