include::./index.adoc[]

[[v44-21-0]]
=== Acts of Apostles, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-21-1]]

^<<v44-21-1,1>>^ Now when we had torn ourselves away from them and put out to sea, we ran with a straight course and came to Cos, but on the next &#91;day&#93; to Rhodes, and from there to Patʹa·ra.

[[v44-21-2]]

^<<v44-21-2,2>>^ And when we had found a boat that was crossing to Phoe·niʹcia, we went aboard and sailed away.

[[v44-21-3]]

^<<v44-21-3,3>>^ After coming in sight of the island of Cyʹprus we left it behind on the left side and sailed on to Syria, and landed at Tyre, for there the boat was to unload &#91;its&#93; cargo.

[[v44-21-4]]

^<<v44-21-4,4>>^ By a search we found the disciples and remained here seven days. But through the spirit they repeatedly told Paul not to set foot in Jerusalem.

[[v44-21-5]]

^<<v44-21-5,5>>^ So when we had completed the days, we went forth and started on our way; but they all, together with the women and children, conducted us as far as outside the city. And kneeling down on the beach we had prayer

[[v44-21-6]]

^<<v44-21-6,6>>^ and said good-bye to one another, and we went up into the boat but they returned to their homes.

[[v44-21-7]]

^<<v44-21-7,7>>^ We then completed the voyage from Tyre and arrived at Ptol·e·maʹis, and we greeted the brothers and stayed one day with them.

[[v44-21-8]]

^<<v44-21-8,8>>^ The next day we set out and arrived in Caes·a·reʹa, and we entered into the house of Philip the evangelizer,^&#42;1^ who was one of the seven men, and we stayed with him.

[NOTE]
====
. Or, “missionary.” Gr., eu·ag·ge·li·stouʹ; Lat., e·van·ge·liʹstae.
====

[[v44-21-9]]

^<<v44-21-9,9>>^ This man had four daughters, virgins, that prophesied.

[[v44-21-10]]

^<<v44-21-10,10>>^ But while we were remaining quite a number of days, a certain prophet named Agʹa·bus came down from Ju·deʹa,

[[v44-21-11]]

^<<v44-21-11,11>>^ and he came to us and took up the girdle of Paul, bound his own feet and hands and said: “Thus says the holy spirit, ‘The man to whom this girdle belongs the Jews will bind in this manner in Jerusalem and deliver into the hands of people of the nations.’”

[[v44-21-12]]

^<<v44-21-12,12>>^ Now when we heard this, both we and those of that place began entreating him not to go up to Jerusalem.

[[v44-21-13]]

^<<v44-21-13,13>>^ Then Paul answered: “What are YOU doing by weeping and making me weak at heart? Rest assured, I am ready not only to be bound but also to die at Jerusalem for the name of the Lord Jesus.”

[[v44-21-14]]

^<<v44-21-14,14>>^ When he would not be dissuaded, we acquiesced with the words: “Let the will of Jehovah^&#42;1^ take place.”

[NOTE]
====
. See App 1D.
====

[[v44-21-15]]

^<<v44-21-15,15>>^ Now after these days we prepared for the journey and began going up to Jerusalem.

[[v44-21-16]]

^<<v44-21-16,16>>^ But some of the disciples from Caes·a·reʹa also went with us, to bring us to the man at whose home we were to be entertained, a certain Mnaʹson of Cyʹprus, an early disciple.

[[v44-21-17]]

^<<v44-21-17,17>>^ When we got into Jerusalem, the brothers received us gladly.

[[v44-21-18]]

^<<v44-21-18,18>>^ But on the following &#91;day&#93; Paul went in with us to James; and all the older men^&#42;1^ were present.^&#42;2^

[NOTE]
====
. Or, “elders.”
. Or, “came there.”
====

[[v44-21-19]]

^<<v44-21-19,19>>^ And he greeted them and began giving in detail an account of the things God did among the nations through his ministry.

[[v44-21-20]]

^<<v44-21-20,20>>^ After hearing this they began to glorify God, and they said to him: “You behold, brother, how many thousands^&#42;1^ of believers there are among the Jews; and they are all zealous for the Law.

[NOTE]
====
. Lit., “myriads; tens of thousands.”
====

[[v44-21-21]]

^<<v44-21-21,21>>^ But they have heard it rumored about you that you have been teaching all the Jews among the nations an apostasy^&#42;1^ from Moses, telling them neither to circumcise their children nor to walk in the &#91;solemn&#93; customs.

[NOTE]
====
. “An apostasy.” Gr., a·po·sta·siʹan (from the verb a·phiʹste·mi, “stand away from”). The noun has the sense of desertion, abandonment or rebellion. See Jos 22:22; 2Ch 29:19; 2Th 2:3.
====

[[v44-21-22]]

^<<v44-21-22,22>>^ What, then, is to be done about it? In any case they are going to hear you have arrived.

[[v44-21-23]]

^<<v44-21-23,23>>^ Therefore do this which we tell you: We have four men with a vow upon themselves.

[[v44-21-24]]

^<<v44-21-24,24>>^ Take these men along and cleanse yourself ceremonially with them and take care of their expenses, that they may have their heads shaved. And so everybody will know that there is nothing to the rumors they were told about you, but that you are walking orderly, you yourself also keeping the Law.

[[v44-21-25]]

^<<v44-21-25,25>>^ As for the believers from among the nations, we have sent out,^&#42;1^ rendering our decision that they should keep themselves from what is sacrificed to idols as well as from blood and what is strangled^&#42;2^ and from fornication.”

[NOTE]
====
. “Sent out,” BD; P74אAVg, “written.”
. Or, “what is killed without draining its blood.”
====

[[v44-21-26]]

^<<v44-21-26,26>>^ Then Paul took the men along the next day and cleansed himself ceremonially with them and went into the temple, to give notice of the days to be fulfilled for the ceremonial cleansing, until the offering should be presented for each one of them.

[[v44-21-27]]

^<<v44-21-27,27>>^ Now when the seven days were about to be concluded, the Jews from Asia on beholding him in the temple began to throw all the crowd into confusion, and they laid their hands upon him,

[[v44-21-28]]

^<<v44-21-28,28>>^ crying out: “Men of Israel, help! This is the man that teaches everybody everywhere against the people and the Law and this place and, what is more, he even brought Greeks into the temple and has defiled this holy place.”

[[v44-21-29]]

^<<v44-21-29,29>>^ For they had previously seen Trophʹi·mus the E·pheʹsian in the city with him, but they were imagining Paul had brought him into the temple.

[[v44-21-30]]

^<<v44-21-30,30>>^ And the whole city was set in an uproar, and a running together of the people occurred; and they laid hold of Paul and dragged him outside the temple. And immediately the doors were closed.

[[v44-21-31]]

^<<v44-21-31,31>>^ And while they were seeking to kill him, information came up to the commander^&#42;1^ of the band that all Jerusalem was in confusion;

[NOTE]
====
. Lit., “chiliarch,” a commander of 1,000 soldiers.
====

[[v44-21-32]]

^<<v44-21-32,32>>^ and he at once took soldiers and army officers^&#42;1^ and ran down to them. When they caught sight of the military commander and the soldiers, they quit beating Paul.

[NOTE]
====
. Lit., “centurions,” officers each in command of 100 soldiers.
====

[[v44-21-33]]

^<<v44-21-33,33>>^ Then the military commander came near and took hold of him and gave command for him to be bound with two chains; and he proceeded to inquire who he might be and what he had done.

[[v44-21-34]]

^<<v44-21-34,34>>^ But some in the crowd began shouting out one thing, and others another. So, being unable himself to learn anything certain because of the tumult, he commanded him to be brought to the soldiers’ quarters.

[[v44-21-35]]

^<<v44-21-35,35>>^ But when he got upon the stairs, the situation became such that he was being carried along by the soldiers because of the violence of the crowd;

[[v44-21-36]]

^<<v44-21-36,36>>^ for the multitude of the people kept following, crying out: “Take him away!”^&#42;1^

[NOTE]
====
. Or, “Kill him!”
====

[[v44-21-37]]

^<<v44-21-37,37>>^ And as he was about to be led into the soldiers’ quarters, Paul said to the military commander: “Am I allowed to say something to you?” He said: “Can you speak Greek?

[[v44-21-38]]

^<<v44-21-38,38>>^ Are you not really the Egyptian who before these days stirred up a sedition and led the four thousand dagger^&#42;1^ men out into the wilderness?”

[NOTE]
====
. Lit., “Sicarii; assassins.” Gr., si·ka·riʹon.
====

[[v44-21-39]]

^<<v44-21-39,39>>^ Then Paul said: “I am, in fact, a Jew, of Tarsus in Ci·liʹcia, a citizen of no obscure city. So I beg you, permit me to speak to the people.”

[[v44-21-40]]

^<<v44-21-40,40>>^ After he gave permission, Paul, standing on the stairs, motioned with his hand to the people. When a great silence fell, he addressed them in the Hebrew language, saying:

'''

xref:044-acts/044-acts-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-acts/044-acts-022.adoc#v44-22-0[Próximo Capítulo &#62;]