include::./index.adoc[]

[[v44-6-0]]
=== Acts of Apostles, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-6-1]]

^<<v44-6-1,1>>^ Now in these days, when the disciples were increasing, a murmuring arose on the part of the Greek-speaking Jews^&#42;1^ against the Hebrew-speaking Jews,^&#42;2^ because their widows were being overlooked in the daily distribution.^&#42;3^

[NOTE]
====
. Lit., “of the Hellenists.” Gr., ton Hel·le·ni·stonʹ; Lat., Grae·coʹrum.
. Lit., “the Hebrews.” Gr., tous E·braiʹous; Lat., He·braeʹos.
. Or, “in the . . . ministration.” Gr., en tei di·a·ko·niʹai; Lat., in mi·ni·steʹri·o.
====

[[v44-6-2]]

^<<v44-6-2,2>>^ So the twelve called the multitude of the disciples to them and said: “It is not pleasing for us to leave the word of God to distribute &#91;food&#93;^&#42;1^ to tables.

[NOTE]
====
. Or, “to be ministering.” Gr., di·a·ko·neinʹ; Lat., mi·ni·straʹre.
====

[[v44-6-3]]

^<<v44-6-3,3>>^ So, brothers, search out for yourselves seven certified men from among YOU, full of spirit and wisdom, that we may appoint them over this necessary business;

[[v44-6-4]]

^<<v44-6-4,4>>^ but we shall devote ourselves to prayer and to the ministry of the word.”

[[v44-6-5]]

^<<v44-6-5,5>>^ And the thing spoken was pleasing to the whole multitude, and they selected Stephen, a man full of faith and holy spirit, and Philip and Prochʹo·rus and Ni·caʹnor and Tiʹmon and Parʹme·nas and Nic·o·laʹus, a proselyte of Antioch;

[[v44-6-6]]

^<<v44-6-6,6>>^ and they placed them before the apostles, and, after having prayed, these laid their hands upon them.

[[v44-6-7]]

^<<v44-6-7,7>>^ Consequently the word of God went on growing, and the number of the disciples kept multiplying in Jerusalem very much; and a great crowd of priests began to be obedient to the faith.

[[v44-6-8]]

^<<v44-6-8,8>>^ Now Stephen, full of graciousness and power, was performing great portents and signs among the people.

[[v44-6-9]]

^<<v44-6-9,9>>^ But certain men rose up of those from the so-called Synagogue of the Freedmen,^&#42;1^ and of the Cy·reʹni·ans and Alexandrians and of those from Ci·liʹcia and Asia, to dispute with Stephen;

[NOTE]
====
. Lit., “Libertines.” Arm, “Libyans.”
====

[[v44-6-10]]

^<<v44-6-10,10>>^ and yet they could not hold their own against the wisdom and the spirit with which he was speaking.

[[v44-6-11]]

^<<v44-6-11,11>>^ Then they secretly induced men to say: “We have heard him speaking blasphemous sayings against Moses and God.”

[[v44-6-12]]

^<<v44-6-12,12>>^ And they stirred up the people and the older men^&#42;1^ and the scribes, and, coming upon him suddenly, they took him by force and led him to the Sanʹhe·drin.

[NOTE]
====
. “Older men.” Or, “elders.” Gr., pre·sby·teʹrous.
====

[[v44-6-13]]

^<<v44-6-13,13>>^ And they brought forward false witnesses, who said: “This man does not stop speaking things against this holy place and against the Law.

[[v44-6-14]]

^<<v44-6-14,14>>^ For instance, we have heard him say that this Jesus the Naz·a·reneʹ will throw down this place and change the customs that Moses handed down to us.”

[[v44-6-15]]

^<<v44-6-15,15>>^ And as all those sitting in the Sanʹhe·drin gazed at him, they saw that his face was as an angel’s face.

'''

xref:044-acts/044-acts-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-acts/044-acts-007.adoc#v44-7-0[Próximo Capítulo &#62;]