include::./index.adoc[]

[[v44-8-0]]
=== Acts of Apostles, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-8-1]]

^<<v44-8-1,1>>^ Saul, for his part, was approving of the murder of him.
On that day great persecution arose against the congregation that was in Jerusalem; all except the apostles were scattered throughout the regions of Ju·deʹa and Sa·marʹi·a.

[[v44-8-2]]

^<<v44-8-2,2>>^ But reverent men carried Stephen to the burial, and they made a great lamentation over him.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saul, though, began to deal outrageously with the congregation. Invading one house after another and, dragging out both men and women, he would turn them over to prison.

[[v44-8-4]]

^<<v44-8-4,4>>^ However, those who had been scattered went through the land declaring the good news of the word.

[[v44-8-5]]

^<<v44-8-5,5>>^ Philip, for one, went down to the city of Sa·marʹi·a and began to preach the Christ to them.

[[v44-8-6]]

^<<v44-8-6,6>>^ With one accord the crowds were paying attention to the things said by Philip while they listened and looked at the signs he was performing.

[[v44-8-7]]

^<<v44-8-7,7>>^ For there were many that had unclean spirits, and these would cry out with a loud voice and come out. Moreover, many that were paralyzed and lame were cured.

[[v44-8-8]]

^<<v44-8-8,8>>^ So there came to be a great deal of joy in that city.

[[v44-8-9]]

^<<v44-8-9,9>>^ Now in the city there was a certain man named Simon, who, prior to this, had been practicing magical arts and amazing the nation of Sa·marʹi·a, saying he himself was somebody great.

[[v44-8-10]]

^<<v44-8-10,10>>^ And all of them, from the least to the greatest, would pay attention to him and say: “This man is the Power of God, which can be called Great.”

[[v44-8-11]]

^<<v44-8-11,11>>^ So they would pay attention to him because of his having amazed them for quite a while by his magical arts.

[[v44-8-12]]

^<<v44-8-12,12>>^ But when they believed Philip, who was declaring the good news of the kingdom of God and of the name of Jesus Christ, they proceeded to be baptized, both men and women.

[[v44-8-13]]

^<<v44-8-13,13>>^ Simon himself also became a believer, and, after being baptized, he was in constant attendance upon Philip; and he was amazed at beholding signs and great powerful works taking place.

[[v44-8-14]]

^<<v44-8-14,14>>^ When the apostles in Jerusalem heard that Sa·marʹi·a had accepted the word of God, they dispatched Peter and John to them;

[[v44-8-15]]

^<<v44-8-15,15>>^ and these went down and prayed for them to get holy spirit.

[[v44-8-16]]

^<<v44-8-16,16>>^ For it had not yet fallen upon any one of them, but they had only been baptized in the name of the Lord Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Then they went laying their hands upon them, and they began to receive holy spirit.

[[v44-8-18]]

^<<v44-8-18,18>>^ Now when Simon saw that through the laying on of the hands of the apostles the spirit was given, he offered them money,

[[v44-8-19]]

^<<v44-8-19,19>>^ saying: “Give me also this authority, that anyone upon whom I lay my hands may receive holy spirit.”

[[v44-8-20]]

^<<v44-8-20,20>>^ But Peter said to him: “May your silver perish with you, because you thought through money to get possession of the free gift of God.

[[v44-8-21]]

^<<v44-8-21,21>>^ You have neither part nor lot in this matter, for your heart is not straight in the sight of God.

[[v44-8-22]]

^<<v44-8-22,22>>^ Repent, therefore, of this badness of yours, and supplicate Jehovah^&#42;1^ that, if possible, the device of your heart may be forgiven you;

[NOTE]
====
. “Jehovah,” J18,​22,​23; Gr., tou Ky·riʹou; VgSyp, “God.” See App 1D.
====

[[v44-8-23]]

^<<v44-8-23,23>>^ for I see you are a^&#42;1^ poisonous gall and a bond of unrighteousness.”

[NOTE]
====
. “You are in a,” D*Vg.
====

[[v44-8-24]]

^<<v44-8-24,24>>^ In answer Simon said: “YOU men, make supplication for me to Jehovah^&#42;1^ that none of the things YOU have said may come upon me.”

[NOTE]
====
. “Jehovah,” J7,​8,​10,​13,​15-18,​22,​23; אAB(Gr.), ton Kyʹri·on; DVgmssSyh,p, “God.” See App 1D.
====

[[v44-8-25]]

^<<v44-8-25,25>>^ Therefore, when they had given the witness thoroughly and had spoken the word of Jehovah,^&#42;1^ they turned back to Jerusalem, and they went declaring the good news to many villages of the Sa·marʹi·tans.

[NOTE]
====
. “Of Jehovah,” J7,​8,​10,​17,​18; אBCD(Gr.), tou Ky·riʹou; P74ASyp, “of God.” See App 1D.
====

[[v44-8-26]]

^<<v44-8-26,26>>^ However, Jehovah’s^&#42;1^ angel spoke to Philip, saying: “Rise and go to the south to the road that runs down from Jerusalem to Gaʹza.” (This is a desert road.)

[NOTE]
====
. See App 1D.
====

[[v44-8-27]]

^<<v44-8-27,27>>^ With that he rose and went, and, look! an E·thi·oʹpi·an eunuch, a man in power under Can·daʹce queen of the E·thi·oʹpi·ans, and who was over all her treasure. He had gone to Jerusalem to worship,

[[v44-8-28]]

^<<v44-8-28,28>>^ but he was returning and was sitting in his chariot and reading aloud the prophet Isaiah.

[[v44-8-29]]

^<<v44-8-29,29>>^ So the spirit said to Philip: “Approach and join yourself to this chariot.”

[[v44-8-30]]

^<<v44-8-30,30>>^ Philip ran alongside and heard him reading aloud Isaiah the prophet, and he said: “Do you actually know what you are reading?”

[[v44-8-31]]

^<<v44-8-31,31>>^ He said: “Really, how could I ever do so, unless someone guided me?” And he entreated Philip to get on and sit down with him.

[[v44-8-32]]

^<<v44-8-32,32>>^ Now the passage of Scripture that he was reading aloud was this: “As a sheep he was brought to the slaughter, and as a lamb that is voiceless before its shearer, so he does not open his mouth.

[[v44-8-33]]

^<<v44-8-33,33>>^ During his humiliation the judgment was taken away from him. Who will tell the details of his generation?^&#42;1^ Because his life is taken away from the earth.”

[NOTE]
====
. Or, “manner of life.”
====

[[v44-8-34]]

^<<v44-8-34,34>>^ In answer the eunuch said to Philip: “I beg you, About whom does the prophet say this? About himself or about some other man?”

[[v44-8-35]]

^<<v44-8-35,35>>^ Philip opened his mouth and, starting with this Scripture, he declared to him the good news about Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Now as they were going over the road, they came to a certain body of water, and the eunuch said: “Look! A body of water; what prevents me from getting baptized?”

[[v44-8-37]]

^<<v44-8-37,37>>^ ^&#42;1^ ——

[NOTE]
====
. P45,​74אABCVgSyp omit vs 37; ItVgcArm, “Philip said to him: ‘If you believe with all your heart, it is permissible.’ In reply he said: ‘I believe that Jesus Christ is the Son of God.’ ”
====

[[v44-8-38]]

^<<v44-8-38,38>>^ With that he commanded the chariot to halt, and they both went down into the water, both Philip and the eunuch; and he baptized him.

[[v44-8-39]]

^<<v44-8-39,39>>^ When they had come up out of the water, Jehovah’s^&#42;1^ spirit quickly led Philip away, and the eunuch did not see him anymore, for he kept going on his way rejoicing.

[NOTE]
====
. See App 1D.
====

[[v44-8-40]]

^<<v44-8-40,40>>^ But Philip was found to be in Ashʹdod,^&#42;1^ and he went through the territory and kept on declaring the good news to all the cities until he got to Caes·a·reʹa.

[NOTE]
====
. “Ashdod,” J17,​18,​22; אAB, “Azotus.”
====

'''

xref:044-acts/044-acts-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-acts/044-acts-009.adoc#v44-9-0[Próximo Capítulo &#62;]