include::./index.adoc[]

[[v44-13-0]]
=== Acts of Apostles, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-13-1]]

^<<v44-13-1,1>>^ Now in Antioch there were prophets and teachers in the local congregation, Barʹna·bas as well as Symʹe·on who was called Niʹger, and Lucius of Cy·reʹne, and Manʹa·en who was educated with Herod the district ruler,^&#42;1^ and Saul.

[NOTE]
====
. Lit., “the tetrarch,” a territorial prince for the emperor.
====

[[v44-13-2]]

^<<v44-13-2,2>>^ As they were publicly ministering to Jehovah^&#42;1^ and fasting, the holy spirit said: “Of all persons set Barʹna·bas and Saul apart for me for the work to which I have called them.”

[NOTE]
====
. See App 1D.
====

[[v44-13-3]]

^<<v44-13-3,3>>^ Then they fasted and prayed and laid their hands upon them and let them go.

[[v44-13-4]]

^<<v44-13-4,4>>^ Accordingly these men, sent out by the holy spirit, went down to Se·leuʹcia, and from there they sailed away to Cyʹprus.

[[v44-13-5]]

^<<v44-13-5,5>>^ And when they got to be in Salʹa·mis they began publishing the word of God in the synagogues of the Jews. They had John also as an attendant.

[[v44-13-6]]

^<<v44-13-6,6>>^ When they had gone through the whole island as far as Paʹphos, they met up with a certain man, a sorcerer, a false prophet, a Jew whose name was Bar-Jeʹsus,

[[v44-13-7]]

^<<v44-13-7,7>>^ and he was with the proconsul^&#42;1^ Sergius Paulus, an intelligent man. Calling Barʹna·bas and Saul to him, this man earnestly sought to hear the word of God.

[NOTE]
====
. A provincial governor for the Roman Senate.
====

[[v44-13-8]]

^<<v44-13-8,8>>^ But Elʹy·mas the sorcerer (that, in fact, is the way his name is translated) began opposing them, seeking to turn the proconsul away from the faith.

[[v44-13-9]]

^<<v44-13-9,9>>^ Saul, who is also Paul,^&#42;1^ becoming filled with holy spirit, looked at him intently

[NOTE]
====
. Possibly meaning “Little.” Gr., Pauʹlos.
====

[[v44-13-10]]

^<<v44-13-10,10>>^ and said: “O man full of every sort of fraud and every sort of villainy, you son of the Devil, you enemy of everything righteous, will you not quit distorting the right ways of Jehovah?^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v44-13-11]]

^<<v44-13-11,11>>^ Well, then, look! Jehovah’s^&#42;1^ hand is upon you, and you will be blind, not seeing the sunlight for a period of time.” Instantly a thick mist and darkness fell upon him, and he went around seeking men to lead him by the hand.

[NOTE]
====
. See App 1D.
====

[[v44-13-12]]

^<<v44-13-12,12>>^ Then the proconsul, upon seeing what had happened, became a believer, as he was astounded at the teaching of Jehovah.^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v44-13-13]]

^<<v44-13-13,13>>^ The men, together with Paul, now put out to sea from Paʹphos and arrived at Perga in Pam·phylʹi·a. But John withdrew from them and returned to Jerusalem.

[[v44-13-14]]

^<<v44-13-14,14>>^ They, however, went on from Perga and came to Antioch in Pi·sidʹi·a and, going into the synagogue on the sabbath day, they took a seat.

[[v44-13-15]]

^<<v44-13-15,15>>^ After the public reading of the Law and of the Prophets the presiding officers of the synagogue sent out to them, saying: “Men, brothers, if there is any word of encouragement for the people that YOU have, tell it.”

[[v44-13-16]]

^<<v44-13-16,16>>^ So Paul rose, and motioning with his hand, he said:
“Men, Israelites and YOU &#91;others&#93; that fear God, hear.

[[v44-13-17]]

^<<v44-13-17,17>>^ The God of this people Israel chose our forefathers, and he exalted the people during their alien residence in the land of Egypt and brought them out of it with an uplifted arm.

[[v44-13-18]]

^<<v44-13-18,18>>^ And for a period of about forty years he put up with their manner of action in the wilderness.

[[v44-13-19]]

^<<v44-13-19,19>>^ After destroying seven nations in the land of Caʹnaan, he distributed the land of them by lot:

[[v44-13-20]]

^<<v44-13-20,20>>^ all that during about four hundred and fifty years.
“And after these things^&#42;1^ he gave them judges until Samuel the prophet.

[NOTE]
====
. “During about four hundred and fifty years. And after these things,” P74אABCVg.
====

[[v44-13-21]]

^<<v44-13-21,21>>^ But from then on they demanded a king, and God gave them Saul son of Kish, a man of the tribe of Benjamin, for forty years.

[[v44-13-22]]

^<<v44-13-22,22>>^ And after removing him, he raised up for them David as king, respecting whom he bore witness and said, ‘I have found David the son of Jesʹse, a man agreeable to my heart, who will do all the things I desire.’

[[v44-13-23]]

^<<v44-13-23,23>>^ From the offspring of this &#91;man&#93; according to his promise God has brought to Israel a savior, Jesus,

[[v44-13-24]]

^<<v44-13-24,24>>^ after John, in advance of the entry of that One, had preached publicly to all the people of Israel baptism &#91;in symbol&#93; of repentance.

[[v44-13-25]]

^<<v44-13-25,25>>^ But as John was fulfilling his course, he would say, ‘What do YOU suppose I am? I am not he.^&#42;1^ But, look! one is coming after me the sandals of whose feet I am not worthy to untie.’

[NOTE]
====
. Or, “What you suppose I am I am not.”
====

[[v44-13-26]]

^<<v44-13-26,26>>^ “Men, brothers, YOU sons of the stock of Abraham and those &#91;others&#93; among YOU who fear God, the word of this salvation has been sent forth to us.

[[v44-13-27]]

^<<v44-13-27,27>>^ For the inhabitants of Jerusalem and their rulers did not know this One, but, when acting as judges, they fulfilled the things voiced by the Prophets, which things are read aloud every Sabbath,

[[v44-13-28]]

^<<v44-13-28,28>>^ and, although they found no cause for death, they demanded of Pilate that he be executed.

[[v44-13-29]]

^<<v44-13-29,29>>^ When, now, they had accomplished all the things written about him, they took him down from the stake^&#42;1^ and laid him in a memorial tomb.

[NOTE]
====
. Or, “tree.” See App 5C.
====

[[v44-13-30]]

^<<v44-13-30,30>>^ But God raised him up from the dead;

[[v44-13-31]]

^<<v44-13-31,31>>^ and for many days he became visible to those who had gone up with him from Galʹi·lee to Jerusalem, who are now his witnesses to the people.

[[v44-13-32]]

^<<v44-13-32,32>>^ “And so we are declaring to YOU the good news about the promise made to the forefathers,

[[v44-13-33]]

^<<v44-13-33,33>>^ that God has entirely fulfilled it to us their^&#42;1^ children in that he resurrected Jesus; even as it is written in the second psalm, ‘You are my son, I have become your Father this day.’

[NOTE]
====
. “To us their,” Syp; P74אABC*DVg, “to our.”
====

[[v44-13-34]]

^<<v44-13-34,34>>^ And that fact that he resurrected him from the dead destined no more to return to corruption, he has stated in this way, ‘I will give YOU people the loving-kindnesses to David that are faithful.’

[[v44-13-35]]

^<<v44-13-35,35>>^ Hence he also says in another psalm, ‘You will not allow your loyal one to see corruption.’

[[v44-13-36]]

^<<v44-13-36,36>>^ For David, on the one hand, served the express will of God in his own generation and fell asleep &#91;in death&#93; and was laid with his forefathers and did see corruption.

[[v44-13-37]]

^<<v44-13-37,37>>^ On the other hand, he whom God raised up did not see corruption.

[[v44-13-38]]

^<<v44-13-38,38>>^ “Let it therefore be known to YOU, brothers, that through this One a forgiveness of sins is being published to YOU;

[[v44-13-39]]

^<<v44-13-39,39>>^ and that from all the things from which YOU could not be declared guiltless by means of the law of Moses, everyone who believes is declared guiltless by means of this One.

[[v44-13-40]]

^<<v44-13-40,40>>^ Therefore see to it that what is said in the Prophets does not come upon YOU,

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Behold it, YOU scorners, and wonder at it, and vanish away, because I am working a work in YOUR days, a work that YOU will by no means believe even if anyone relates it to YOU in detail.’”

[[v44-13-42]]

^<<v44-13-42,42>>^ Now when they were going out, the people began entreating for these matters to be spoken to them on the following sabbath.

[[v44-13-43]]

^<<v44-13-43,43>>^ So after the synagogue assembly was dissolved, many of the Jews and of the proselytes who worshiped &#91;God&#93;^&#42;1^ followed Paul and Barʹna·bas, who in speaking to them began urging them to continue in the undeserved kindness of God.

[NOTE]
====
. “Who worshiped (feared) God,” Syp; J18, “who feared Jehovah.”
====

[[v44-13-44]]

^<<v44-13-44,44>>^ The next sabbath nearly all the city gathered together to hear the word of Jehovah.^&#42;1^

[NOTE]
====
. “Of Jehovah,” J17,​22; P74אABc(Gr.), tou Ky·riʹou; B*CSyh,p, “of God.” See App 1D.
====

[[v44-13-45]]

^<<v44-13-45,45>>^ When the Jews got sight of the crowds, they were filled with jealousy and began blasphemously contradicting the things being spoken by Paul.

[[v44-13-46]]

^<<v44-13-46,46>>^ And so, talking with boldness, Paul and Barʹna·bas said: “It was necessary for the word of God to be spoken first to YOU. Since YOU are thrusting it away from YOU and do not judge yourselves worthy of everlasting life, look! we turn to the nations.

[[v44-13-47]]

^<<v44-13-47,47>>^ In fact, Jehovah^&#42;1^ has laid commandment upon us in these words, ‘I have appointed you as a light of nations, for you to be a salvation to the extremity^&#42;2^ of the earth.’”

[NOTE]
====
. See App 1D.
. “Extremity.” Or, “most distant part.” Gr., e·skhaʹtou. See 1:8 ftn, “Part.”
====

[[v44-13-48]]

^<<v44-13-48,48>>^ When those of the nations heard this, they began to rejoice and to glorify the word of Jehovah,^&#42;1^ and all those who were rightly disposed for everlasting life became believers.

[NOTE]
====
. “Of Jehovah,” J7,​8,​10,​13,​15-17,​22,​23; P45,74אAC(Gr.), tou Ky·riʹou; BD, “of God.” See App 1D.
====

[[v44-13-49]]

^<<v44-13-49,49>>^ Furthermore, the word of Jehovah^&#42;1^ went on being carried throughout the whole country.

[NOTE]
====
. See App 1D.
====

[[v44-13-50]]

^<<v44-13-50,50>>^ But the Jews stirred up the reputable women who worshiped &#91;God&#93;^&#42;1^ and the principal men of the city, and they raised up a persecution against Paul and Barʹna·bas and threw them outside their boundaries.

[NOTE]
====
. “Who worshiped (feared) God,” Syp; J7,​8,​10,​18, “who feared Jehovah.”
====

[[v44-13-51]]

^<<v44-13-51,51>>^ These shook the dust off their feet against them and went to I·coʹni·um.

[[v44-13-52]]

^<<v44-13-52,52>>^ And the disciples continued to be filled with joy and holy spirit.

'''

xref:044-acts/044-acts-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-acts/044-acts-014.adoc#v44-14-0[Próximo Capítulo &#62;]