include::./index.adoc[]

[[v44-20-0]]
=== Acts of Apostles, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-20-1]]

^<<v44-20-1,1>>^ Now after the uproar had subsided, Paul sent for the disciples, and when he had encouraged them and bidden them farewell, he went forth to journey into Mac·e·doʹni·a.

[[v44-20-2]]

^<<v44-20-2,2>>^ After going through those parts and encouraging the ones there with many a word, he came into Greece.

[[v44-20-3]]

^<<v44-20-3,3>>^ And when he had spent three months there, because a plot was hatched against him by the Jews as he was about to set sail for Syria, he made up his mind to return through Mac·e·doʹni·a.

[[v44-20-4]]

^<<v44-20-4,4>>^ There were accompanying him Sopʹa·ter the son of Pyrʹrhus of Be·roeʹa, Ar·is·tarʹchus and Se·cunʹdus of the Thes·sa·loʹni·ans, and Gaʹius of Derʹbe, and Timothy, and from the &#91;district of&#93; Asia Tychʹi·cus and Trophʹi·mus.

[[v44-20-5]]

^<<v44-20-5,5>>^ These went on and were waiting for us in Troʹas;

[[v44-20-6]]

^<<v44-20-6,6>>^ but we put out to sea from Phi·lipʹpi after the days of the unfermented cakes, and we came to them in Troʹas within five days; and there we spent seven days.

[[v44-20-7]]

^<<v44-20-7,7>>^ On the first day of the week, when we were gathered together to have a meal,^&#42;1^ Paul began discoursing to them, as he was going to depart the next day; and he prolonged his speech until midnight.

[NOTE]
====
. Lit., “to break bread.”
====

[[v44-20-8]]

^<<v44-20-8,8>>^ So there were quite a few lamps in the upper chamber where we were gathered together.

[[v44-20-9]]

^<<v44-20-9,9>>^ Seated at the window, a certain young man named Euʹty·chus fell into a deep sleep while Paul kept talking on, and, collapsing in sleep, he fell down from the third story and was picked up dead.

[[v44-20-10]]

^<<v44-20-10,10>>^ But Paul went downstairs, threw himself upon him and embraced him and said: “STOP raising a clamor, for his soul^&#42;1^ is in him.”

[NOTE]
====
. Or, “life.” See App 4A.
====

[[v44-20-11]]

^<<v44-20-11,11>>^ He now went upstairs and began the meal^&#42;1^ and took food, and after conversing for quite a while, until daybreak, he at length departed.

[NOTE]
====
. Lit., “having broken the bread.”
====

[[v44-20-12]]

^<<v44-20-12,12>>^ So they took the boy away alive and were comforted beyond measure.

[[v44-20-13]]

^<<v44-20-13,13>>^ We now went ahead to the boat and set sail to Asʹsos, where we were intending to take Paul aboard, for, after giving instructions to this effect, he himself was intending to go on foot.

[[v44-20-14]]

^<<v44-20-14,14>>^ So when he caught up with us in Asʹsos, we took him aboard and went to Mit·y·leʹne;

[[v44-20-15]]

^<<v44-20-15,15>>^ and, sailing away from there the succeeding day, we arrived opposite Chiʹos, but the next day we touched at Saʹmos, and on the following day we arrived at Mi·leʹtus.

[[v44-20-16]]

^<<v44-20-16,16>>^ For Paul had decided to sail past Ephʹe·sus, in order that he might not spend any time in the &#91;district of&#93; Asia; for he was hastening to get to Jerusalem on the day of the &#91;festival of&#93; Pentecost if he possibly could.

[[v44-20-17]]

^<<v44-20-17,17>>^ However, from Mi·leʹtus he sent to Ephʹe·sus and called for the older men^&#42;1^ of the congregation.

[NOTE]
====
. “Older men.” Or, “elders.” Gr., pre·sby·teʹrous.
====

[[v44-20-18]]

^<<v44-20-18,18>>^ When they got to him he said to them: “YOU well know how from the first day that I stepped into the &#91;district of&#93; Asia I was with you the whole time,

[[v44-20-19]]

^<<v44-20-19,19>>^ slaving for the Lord with the greatest lowliness of mind and tears and trials that befell me by the plots of the Jews;

[[v44-20-20]]

^<<v44-20-20,20>>^ while I did not hold back from telling YOU any of the things that were profitable nor from teaching YOU publicly and from house to house.^&#42;1^

[NOTE]
====
. Or, “and in private houses.” Lit., “and according to houses.” Gr., kai katʼ oiʹkous. Here ka·taʹ is used with the accusative pl. in the distributive sense. Compare 5:42 ftn, “House.”
====

[[v44-20-21]]

^<<v44-20-21,21>>^ But I thoroughly bore witness both to Jews and to Greeks about repentance toward God and faith in our Lord Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ And now, look! bound in the spirit, I am journeying to Jerusalem, although not knowing the things that will happen to me in it,

[[v44-20-23]]

^<<v44-20-23,23>>^ except that from city to city the holy spirit repeatedly bears witness to me as it says that bonds and tribulations are waiting for me.

[[v44-20-24]]

^<<v44-20-24,24>>^ Nevertheless, I do not make my soul^&#42;1^ of any account as dear to me, if only I may finish my course and the ministry that I received of the Lord Jesus, to bear thorough witness to the good news of the undeserved kindness of God.

[NOTE]
====
. Or, “life.”
====

[[v44-20-25]]

^<<v44-20-25,25>>^ “And now, look! I know that all of YOU among whom I went preaching^&#42;1^ the kingdom^&#42;2^ will see my face no more.

[NOTE]
====
. Or, “herald­ing.” Gr., ke·rysʹson; Lat., praeʹdi·cans. Compare Da 5:29 ftn, “Heralded.”
. “Kingdom,” אAB; VgSyp, “kingdom of God”; J17, “kingdom of Jehovah.”
====

[[v44-20-26]]

^<<v44-20-26,26>>^ Hence I call YOU to witness this very day that I am clean from the blood of all men,

[[v44-20-27]]

^<<v44-20-27,27>>^ for I have not held back from telling YOU all the counsel of God.

[[v44-20-28]]

^<<v44-20-28,28>>^ Pay attention to yourselves and to all the flock, among which the holy spirit has appointed YOU overseers,^&#42;1^ to shepherd the congregation of God,^&#42;2^ which he purchased with the blood of his own &#91;Son&#93;.^&#42;3^

[NOTE]
====
. “Overseers.” Gr., e·pi·skoʹpous; J17(Heb.), liph·qi·dhimʹ, “as overseers.” See Ne 11:9 ftn.
. “God,” אBVg; AD, “the Lord.”
. For a discussion of “the blood of his own [Son]” see App 6C.
====

[[v44-20-29]]

^<<v44-20-29,29>>^ I know that after my going away oppressive wolves will enter in among YOU and will not treat the flock with tenderness,

[[v44-20-30]]

^<<v44-20-30,30>>^ and from among YOU yourselves men will rise and speak twisted things to draw away the disciples after themselves.

[[v44-20-31]]

^<<v44-20-31,31>>^ “Therefore keep awake, and bear in mind that for three years, night and day, I did not quit admonishing each one with tears.

[[v44-20-32]]

^<<v44-20-32,32>>^ And now I commit YOU to God^&#42;1^ and to the word of his undeserved kindness, which &#91;word&#93; can build YOU up and give YOU the inheritance among all the sanctified ones.

[NOTE]
====
. “God,” אADVgSypJ8,​17,​18,​22; B, “the Lord.”
====

[[v44-20-33]]

^<<v44-20-33,33>>^ I have coveted no man’s silver or gold or apparel.

[[v44-20-34]]

^<<v44-20-34,34>>^ YOU yourselves know that these hands have attended to the needs of me and of those with me.

[[v44-20-35]]

^<<v44-20-35,35>>^ I have exhibited to YOU in all things that by thus laboring YOU must assist those who are weak, and must bear in mind the words of the Lord Jesus, when he himself said, ‘There is more happiness in giving than there is in receiving.’”

[[v44-20-36]]

^<<v44-20-36,36>>^ And when he had said these things, he kneeled down with all of them and prayed.

[[v44-20-37]]

^<<v44-20-37,37>>^ Indeed, quite a bit of weeping broke out among them all, and they fell upon Paul’s neck and tenderly kissed him,

[[v44-20-38]]

^<<v44-20-38,38>>^ because they were especially pained at the word he had spoken that they were going to behold his face no more. So they proceeded to conduct him to the boat.

'''

xref:044-acts/044-acts-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-acts/044-acts-021.adoc#v44-21-0[Próximo Capítulo &#62;]