include::./index.adoc[]

[[v44-19-0]]
=== Acts of Apostles, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-19-1]]

^<<v44-19-1,1>>^ In the course of events, while A·polʹlos was in Corinth, Paul went through the inland parts and came down to Ephʹe·sus, and found some disciples;

[[v44-19-2]]

^<<v44-19-2,2>>^ and he said to them: “Did you receive holy spirit when YOU became believers?” They said to him: “Why, we have never heard whether there is a holy spirit.”

[[v44-19-3]]

^<<v44-19-3,3>>^ And he said: “In what, then, were YOU baptized?” They said: “In John’s baptism.”

[[v44-19-4]]

^<<v44-19-4,4>>^ Paul said: “John baptized with the baptism &#91;in symbol&#93; of repentance, telling the people to believe in the one coming after him, that is, in Jesus.”

[[v44-19-5]]

^<<v44-19-5,5>>^ On hearing this, they got baptized in the name of the Lord Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ And when Paul laid his hands upon them, the holy spirit came upon them, and they began speaking with tongues and prophesying.

[[v44-19-7]]

^<<v44-19-7,7>>^ All together, there were about twelve men.

[[v44-19-8]]

^<<v44-19-8,8>>^ Entering into the synagogue, he spoke with boldness for three months, giving talks and using persuasion concerning the kingdom of God.

[[v44-19-9]]

^<<v44-19-9,9>>^ But when some went on hardening themselves and not believing, speaking injuriously about The Way before the multitude, he withdrew from them and separated the disciples from them, daily giving talks in the school &#91;auditorium&#93; of Ty·ranʹnus.^&#42;1^

[NOTE]
====
. DItmss add: “from the fifth hour to the tenth,” that is, from about 11 a.m. to about 4 p.m.
====

[[v44-19-10]]

^<<v44-19-10,10>>^ This took place for two years, so that all those inhabiting the &#91;district of&#93; Asia heard the word of the Lord, both Jews and Greeks.

[[v44-19-11]]

^<<v44-19-11,11>>^ And God kept performing extraordinary works of power through the hands of Paul,

[[v44-19-12]]

^<<v44-19-12,12>>^ so that even cloths and aprons were borne from his body to the ailing people, and the diseases left them, and the wicked spirits came out.

[[v44-19-13]]

^<<v44-19-13,13>>^ But certain ones of the roving Jews who practiced the casting out of demons also undertook to name the name of the Lord Jesus over those having the wicked spirits, saying: “I solemnly charge YOU by Jesus whom Paul preaches.”

[[v44-19-14]]

^<<v44-19-14,14>>^ Now there were seven sons of a certain Sceʹva, a Jewish chief priest, doing this.

[[v44-19-15]]

^<<v44-19-15,15>>^ But in answer the wicked spirit said to them: “I know Jesus and I am acquainted with Paul; but who are YOU?”

[[v44-19-16]]

^<<v44-19-16,16>>^ With that the man in whom the wicked spirit was leaped upon them, got the mastery of one after the other,^&#42;1^ and prevailed against them, so that they fled naked and wounded out of that house.

[NOTE]
====
. Lit., “of both [of them].”
====

[[v44-19-17]]

^<<v44-19-17,17>>^ This became known to all, both the Jews and the Greeks that dwelt in Ephʹe·sus; and a fear fell upon them all, and the name of the Lord Jesus went on being magnified.

[[v44-19-18]]

^<<v44-19-18,18>>^ And many of those who had become believers would come and confess and report their practices openly.

[[v44-19-19]]

^<<v44-19-19,19>>^ Indeed, quite a number of those who practiced magical arts brought their books together and burned them up before everybody. And they calculated together the prices of them and found them worth fifty thousand pieces of silver.

[[v44-19-20]]

^<<v44-19-20,20>>^ Thus in a mighty way the word of Jehovah^&#42;1^ kept growing and prevailing.

[NOTE]
====
. “Of Jehovah,” J7,​8,​10,​13,​15-18,​23; Gr., tou Ky·riʹou; VgSyp, “of God.” See App 1D.
====

[[v44-19-21]]

^<<v44-19-21,21>>^ Now when these things had been completed, Paul purposed in his spirit that, after going through Mac·e·doʹni·a and A·chaʹia, he would journey to Jerusalem, saying: “After I get there I must also see Rome.”

[[v44-19-22]]

^<<v44-19-22,22>>^ So he dispatched to Mac·e·doʹni·a two of those who ministered to him, Timothy and E·rasʹtus, but he himself delayed for some time in the &#91;district of&#93; Asia.

[[v44-19-23]]

^<<v44-19-23,23>>^ At that particular time there arose no little disturbance concerning The Way.^&#42;1^

[NOTE]
====
. “The Way,” אAB; Vgc, “the way of the Lord”; Syp, “the way of God”; J17,​18, “Jehovah’s way.”
====

[[v44-19-24]]

^<<v44-19-24,24>>^ For a certain man named De·meʹtri·us, a silversmith, by making silver shrines^&#42;1^ of Arʹte·mis^&#42;2^ furnished the craftsmen no little gain;

[NOTE]
====
. Or, “divine habitations (dwellings).” Gr., na·ousʹ; J17(Heb.), heh·khelohthʹ, “palaces; temples.”
. Or, “Diana.” Gr., Ar·teʹmi·dos; Lat., Di·aʹnae.
====

[[v44-19-25]]

^<<v44-19-25,25>>^ and he gathered them and those who worked at such things and said: “Men, YOU well know that from this business we have our prosperity.

[[v44-19-26]]

^<<v44-19-26,26>>^ Also, YOU behold and hear how not only in Ephʹe·sus but in nearly all the &#91;district of&#93; Asia this Paul has persuaded a considerable crowd and turned them to another opinion, saying that the ones that are made by hands are not gods.

[[v44-19-27]]

^<<v44-19-27,27>>^ Moreover, the danger exists not only that this occupation of ours will come into disrepute but also that the temple of the great goddess Arʹte·mis will be esteemed as nothing and even her magnificence which the whole &#91;district of&#93; Asia and the inhabited earth worships is about to be brought down to nothing.”

[[v44-19-28]]

^<<v44-19-28,28>>^ Hearing this and becoming full of anger, the men began crying out, saying: “Great is Arʹte·mis of the E·pheʹsians!”

[[v44-19-29]]

^<<v44-19-29,29>>^ So the city became filled with confusion, and with one accord they rushed into the theater, taking forcibly along with them Gaʹius and Ar·is·tarʹchus, Mac·e·doʹni·ans, traveling companions of Paul.

[[v44-19-30]]

^<<v44-19-30,30>>^ For his part, Paul was willing to go inside to the people, but the disciples would not permit him.

[[v44-19-31]]

^<<v44-19-31,31>>^ Even some of the commissioners of festivals and games,^&#42;1^ who were friendly to him, sent to him and began pleading for him not to risk himself in the theater.

[NOTE]
====
. Lit., “some of the Asiarchs.”
====

[[v44-19-32]]

^<<v44-19-32,32>>^ The fact is, some were crying out one thing and others another; for the assembly was in confusion, and the majority of them did not know the reason why they had come together.

[[v44-19-33]]

^<<v44-19-33,33>>^ So together they brought Alexander out of the crowd, the Jews thrusting him up front; and Alexander motioned with his hand and was wanting to make his defense to the people.

[[v44-19-34]]

^<<v44-19-34,34>>^ But when they recognized that he was a Jew, one cry arose from them all as they shouted for about two hours: “Great is Arʹte·mis of the E·pheʹsians!”

[[v44-19-35]]

^<<v44-19-35,35>>^ When, finally, the city recorder had quieted the crowd, he said: “Men of Ephʹe·sus, who really is there of mankind that does not know that the city of the E·pheʹsians is the temple keeper of the great Arʹte·mis and of the image that fell from heaven?^&#42;1^

[NOTE]
====
. “That fell from heaven.” Lit., “fallen from Zeus (Jupiter).”
====

[[v44-19-36]]

^<<v44-19-36,36>>^ Therefore since these things are indisputable, it is becoming for YOU to keep calm and not act rashly.

[[v44-19-37]]

^<<v44-19-37,37>>^ For YOU have brought these men who are neither robbers of temples nor blasphemers of our goddess.

[[v44-19-38]]

^<<v44-19-38,38>>^ Therefore if De·meʹtri·us and the craftsmen with him do have a case against someone, court days are held and there are proconsuls; let them bring charges against one another.

[[v44-19-39]]

^<<v44-19-39,39>>^ If, though, YOU are searching for anything beyond that, it must^&#42;1^ be decided in a regular assembly.

[NOTE]
====
. Or, “will.”
====

[[v44-19-40]]

^<<v44-19-40,40>>^ For we are really in danger of being charged with sedition over today’s affair, no single cause existing that will permit us to render a reason for this disorderly mob.”

[[v44-19-41]]

^<<v44-19-41,41>>^ And when he had said these things, he dismissed the assembly.

'''

xref:044-acts/044-acts-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-acts/044-acts-020.adoc#v44-20-0[Próximo Capítulo &#62;]