include::./index.adoc[]

[[v44-4-0]]
=== Acts of Apostles, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-4-1]]

^<<v44-4-1,1>>^ Now while the &#91;two&#93;^&#42;1^ were speaking to the people, the chief priests and the captain of the temple and the Sadducees came upon them,

[NOTE]
====
. Lit., “while they.”
====

[[v44-4-2]]

^<<v44-4-2,2>>^ being annoyed because they were teaching the people and were plainly declaring the resurrection from the dead in the case of Jesus;

[[v44-4-3]]

^<<v44-4-3,3>>^ and they laid their hands upon them and put them in custody till the next day, for it was already evening.

[[v44-4-4]]

^<<v44-4-4,4>>^ However, many of those who had listened to the speech believed, and the number of the men became about five thousand.

[[v44-4-5]]

^<<v44-4-5,5>>^ The next day there took place in Jerusalem the gathering together of their rulers and older men^&#42;1^ and scribes

[NOTE]
====
. Or, “elders.” Gr., tous pre·sby·teʹrous.
====

[[v44-4-6]]

^<<v44-4-6,6>>^ (also Anʹnas the chief priest and Caʹia·phas and John and Alexander and as many as were of the chief priest’s kinsfolk),

[[v44-4-7]]

^<<v44-4-7,7>>^ and they stood them in their midst and began to inquire: “By what power or in whose name did YOU do this?”

[[v44-4-8]]

^<<v44-4-8,8>>^ Then Peter, filled with holy spirit, said to them:
“Rulers of the people and older men,

[[v44-4-9]]

^<<v44-4-9,9>>^ if we are this day being examined, on the basis of a good deed to an ailing man, as to by whom this man has been made well,^&#42;1^

[NOTE]
====
. Or, “has been saved.”
====

[[v44-4-10]]

^<<v44-4-10,10>>^ let it be known to all of YOU and to all the people of Israel, that in the name of Jesus Christ the Naz·a·reneʹ, whom YOU impaled^&#42;1^ but whom God raised up from the dead, by this one^&#42;2^ does this man stand here sound in front of YOU.

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
. Or, “in this name.”
====

[[v44-4-11]]

^<<v44-4-11,11>>^ This is ‘the stone that was treated by YOU builders as of no account that has become the head of the corner.’

[[v44-4-12]]

^<<v44-4-12,12>>^ Furthermore, there is no salvation in anyone else, for there is not another name under heaven that has been given among men by which we must get saved.”

[[v44-4-13]]

^<<v44-4-13,13>>^ Now when they beheld the outspokenness of Peter and John, and perceived that they were men unlettered and ordinary, they got to wondering. And they began to recognize about them that they used to be with Jesus;

[[v44-4-14]]

^<<v44-4-14,14>>^ and as they were looking at the man that had been cured standing with them, they had nothing to say in rebuttal.

[[v44-4-15]]

^<<v44-4-15,15>>^ So they commanded them to go outside the Sanʹhe·drin hall, and they began consulting with one another,

[[v44-4-16]]

^<<v44-4-16,16>>^ saying: “What shall we do with these men? Because, for a fact, a noteworthy sign has occurred through them, one manifest to all the inhabitants of Jerusalem; and we cannot deny it.

[[v44-4-17]]

^<<v44-4-17,17>>^ Nevertheless, in order that it may not be spread abroad further among the people, let us tell them with threats not to speak anymore upon the basis of this name to any man at all.”

[[v44-4-18]]

^<<v44-4-18,18>>^ With that they called them and charged them, nowhere to make any utterance or to teach upon the basis of the name of Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ But in reply Peter and John said to them: “Whether it is righteous in the sight of God to listen to YOU rather than to God, judge for yourselves.

[[v44-4-20]]

^<<v44-4-20,20>>^ But as for us, we cannot stop speaking about the things we have seen and heard.”

[[v44-4-21]]

^<<v44-4-21,21>>^ So, when they had further threatened them, they released them, since they did not find any ground on which to punish them and on account of the people, because they were all glorifying God over what had occurred;

[[v44-4-22]]

^<<v44-4-22,22>>^ for the man upon whom this sign of healing had occurred was more than forty years old.

[[v44-4-23]]

^<<v44-4-23,23>>^ After being released they went to their own people and reported what things the chief priests and the older men had said to them.

[[v44-4-24]]

^<<v44-4-24,24>>^ Upon hearing this they with one accord raised their voices to God and said:
“Sovereign Lord,^&#42;1^ you are the One who made the heaven and the earth and the sea and all the things in them,

[NOTE]
====
. “Sovereign Lord.” Gr., Deʹspo·ta; Lat., Doʹmi·ne; J17,​18(Heb.), ʼAdho·naiʹ. See App 1E.
====

[[v44-4-25]]

^<<v44-4-25,25>>^ and who through holy spirit said by the mouth of our forefather David, your servant, ‘Why did nations become tumultuous and peoples meditate upon empty things?

[[v44-4-26]]

^<<v44-4-26,26>>^ The kings of the earth took their stand and the rulers massed together as one against Jehovah^&#42;1^ and against his anointed one.’^&#42;2^

[NOTE]
====
. See App 1D.
. Or, “his Christ.”
====

[[v44-4-27]]

^<<v44-4-27,27>>^ Even so, both Herod and Pontius Pilate with &#91;men of&#93; nations and with peoples of Israel were in actuality gathered together in this city against your holy servant Jesus, whom you anointed,^&#42;1^

[NOTE]
====
. Or, “you made Christ.” Gr., eʹkhri·sas.
====

[[v44-4-28]]

^<<v44-4-28,28>>^ in order to do what things your hand and counsel had foreordained to occur.

[[v44-4-29]]

^<<v44-4-29,29>>^ And now, Jehovah,^&#42;1^ give attention to their threats, and grant your slaves to keep speaking your word with all boldness,

[NOTE]
====
. See App 1D.
====

[[v44-4-30]]

^<<v44-4-30,30>>^ while you stretch out your hand for healing and while signs and portents occur through the name of your holy servant Jesus.”

[[v44-4-31]]

^<<v44-4-31,31>>^ And when they had made supplication, the place in which they were gathered together was shaken; and they were one and all filled with the holy spirit and were speaking the word of God with boldness.

[[v44-4-32]]

^<<v44-4-32,32>>^ Moreover, the multitude of those who had believed had one heart and soul, and not even one would say that any of the things he possessed was his own; but they had all things in common.

[[v44-4-33]]

^<<v44-4-33,33>>^ Also, with great power the apostles continued giving forth the witness concerning the resurrection of the Lord Jesus; and undeserved kindness in large measure was upon them all.

[[v44-4-34]]

^<<v44-4-34,34>>^ In fact, there was not one in need among them; for all those who were possessors of fields or houses would sell them and bring the values of the things sold

[[v44-4-35]]

^<<v44-4-35,35>>^ and they would deposit them at the feet of the apostles. In turn distribution would be made to each one, just as he would have the need.

[[v44-4-36]]

^<<v44-4-36,36>>^ So Joseph, who was surnamed Barʹna·bas by the apostles, which means, when translated, Son of Comfort, a Levite, a native of Cyʹprus,

[[v44-4-37]]

^<<v44-4-37,37>>^ possessing a piece of land, sold it and brought the money and deposited it at the feet of the apostles.

'''

xref:044-acts/044-acts-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-acts/044-acts-005.adoc#v44-5-0[Próximo Capítulo &#62;]