include::./index.adoc[]

[[v44-27-0]]
=== Acts of Apostles, 27
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v44-27-1]]

^<<v44-27-1,1>>^ Now as it was decided for us to sail away to Italy, they proceeded to hand both Paul and certain other prisoners over to an army officer^&#42;1^ named Julius of the band of Au·gusʹtus.

[NOTE]
====
. Or, “the centurion,” a commander of 100 soldiers.
====

[[v44-27-2]]

^<<v44-27-2,2>>^ Going aboard a boat from Ad·ra·mytʹti·um that was about to sail to places along the coast of the &#91;district of&#93; Asia, we set sail, there being with us Ar·is·tarʹchus a Mac·e·doʹni·an from Thes·sa·lo·niʹca.

[[v44-27-3]]

^<<v44-27-3,3>>^ And the next day we landed at Siʹdon, and Julius treated Paul with human kindness^&#42;1^ and permitted him to go to his friends and enjoy &#91;their&#93; care.

[NOTE]
====
. Lit., “with human affection.” Gr., phi·lan·throʹpos.
====

[[v44-27-4]]

^<<v44-27-4,4>>^ And putting out to sea from there we sailed under the &#91;shelter of&#93; Cyʹprus, because the winds were contrary;

[[v44-27-5]]

^<<v44-27-5,5>>^ and we navigated through the open sea along Ci·liʹcia and Pam·phylʹi·a and put into port at Myʹra in Lyʹci·a.

[[v44-27-6]]

^<<v44-27-6,6>>^ But there the army officer found a boat^&#42;1^ from Alexandria that was sailing for Italy, and he made us board it.

[NOTE]
====
. A grain ship.
====

[[v44-27-7]]

^<<v44-27-7,7>>^ Then, after sailing on slowly quite a number of days and coming to Cniʹdus with difficulty, because the wind did not let us get on, we sailed under the &#91;shelter of&#93; Crete at Sal·moʹne,

[[v44-27-8]]

^<<v44-27-8,8>>^ and coasting along it with difficulty we came to a certain place called Fair Havens, near which was the city La·seʹa.

[[v44-27-9]]

^<<v44-27-9,9>>^ As considerable time had passed and by now it was hazardous to navigate because even the fast &#91;of atonement day&#93;^&#42;1^ had already passed by, Paul made a recommendation,

[NOTE]
====
. Or, “the [autumn] fast.”
====

[[v44-27-10]]

^<<v44-27-10,10>>^ saying to them: “Men, I perceive that navigation is going to be with damage and great loss not only of the cargo and the boat but also of our souls.”^&#42;1^

[NOTE]
====
. Or, “lives.”
====

[[v44-27-11]]

^<<v44-27-11,11>>^ However, the army officer went heeding the pilot and the shipowner rather than the things said by Paul.

[[v44-27-12]]

^<<v44-27-12,12>>^ Now as the harbor was inconvenient for wintering, the majority advised setting sail from there, to see if they could somehow make it to Phoenix to winter, a harbor of Crete that opens toward the northeast and toward the southeast.^&#42;1^

[NOTE]
====
. Or, “looking along the southwest wind and along the northwest wind.”
====

[[v44-27-13]]

^<<v44-27-13,13>>^ Moreover, when the south wind blew softly, they thought they had as good as realized their purpose, and they lifted anchor and began coasting inshore along Crete.

[[v44-27-14]]

^<<v44-27-14,14>>^ After no great while, however, a tempestuous wind called Eu·ro·aqʹui·lo^&#42;1^ rushed down upon it.

[NOTE]
====
. “Euroaquilo.” Gr., Eu·ra·kyʹlon; Lat., eu·ro·aʹqui·lo; a northeast wind.
====

[[v44-27-15]]

^<<v44-27-15,15>>^ As the boat was violently seized and was not able to keep its head against the wind, we gave way and were borne along.

[[v44-27-16]]

^<<v44-27-16,16>>^ Now we ran under &#91;the shelter of&#93; a certain small island called Cauʹda, and yet we were hardly able to get possession of the skiff at the stern.

[[v44-27-17]]

^<<v44-27-17,17>>^ But after hoisting it aboard they began using helps to undergird the boat; and being in fear of running aground on the Syrʹtis,^&#42;1^ they lowered the gear and thus were driven along.

[NOTE]
====
. Two large shallow gulfs, full of shifting sandbanks, on the coast of Libya, North Africa.
====

[[v44-27-18]]

^<<v44-27-18,18>>^ Yet because we were being violently tossed with the tempest, the following &#91;day&#93; they began to lighten the ship;

[[v44-27-19]]

^<<v44-27-19,19>>^ and the third &#91;day&#93;, with their own hands, they threw away the tackling of the boat.

[[v44-27-20]]

^<<v44-27-20,20>>^ When, now, neither sun nor stars appeared for many days, and no little tempest was lying upon us, all hope of our being saved finally began to be cut off.

[[v44-27-21]]

^<<v44-27-21,21>>^ And when there had been a long abstinence from food, then Paul stood up in the midst of them and said: “Men, YOU certainly ought to have taken my advice and not have put out to sea from Crete and have sustained this damage and loss.

[[v44-27-22]]

^<<v44-27-22,22>>^ Still, now I recommend to YOU to be of good cheer, for not a soul^&#42;1^ of YOU will be lost, only the boat will.

[NOTE]
====
. Or, “a life.”
====

[[v44-27-23]]

^<<v44-27-23,23>>^ For this night there stood near me an angel of the God to whom I belong and to whom I render sacred service,^&#42;1^

[NOTE]
====
. Lit., “I am rendering sacred service.” Gr., la·treuʹo; J17(Heb.), ʼaniʹ ʽo·vedhʹ, “I serve (worship).” See Ex 3:12 ftn.
====

[[v44-27-24]]

^<<v44-27-24,24>>^ saying, ‘Have no fear, Paul. You must stand before Caesar, and, look! God has freely given you all those sailing with you.’

[[v44-27-25]]

^<<v44-27-25,25>>^ Therefore be of good cheer, men; for I believe God that it will be exactly as it has been told me.

[[v44-27-26]]

^<<v44-27-26,26>>^ However, we must be cast ashore on a certain island.”

[[v44-27-27]]

^<<v44-27-27,27>>^ Now as the fourteenth night fell and we were being tossed to and fro on the &#91;sea of&#93; Aʹdri·a,^&#42;1^ at midnight the sailors began to suspect they were drawing near to some land.

[NOTE]
====
. Then including what is now the Adriatic Sea, the Ionian Sea and that part of the Mediterranean Sea between Sicily and Crete.
====

[[v44-27-28]]

^<<v44-27-28,28>>^ And they sounded the depth and found it twenty fathoms;^&#42;1^ so they proceeded a short distance and again made a sounding and found it fifteen fathoms.

[NOTE]
====
. “Fathoms.” Gr., or·gui·asʹ. A fathom is commonly viewed as being four cubits (c. 1.8 m; 6 ft).
====

[[v44-27-29]]

^<<v44-27-29,29>>^ And because of fearing we might be cast somewhere upon the rocks, they cast out four anchors from the stern and began wishing for it to become day.

[[v44-27-30]]

^<<v44-27-30,30>>^ But when the sailors began seeking to escape from the boat and lowered the skiff into the sea under the pretense of intending to let down anchors from the prow,

[[v44-27-31]]

^<<v44-27-31,31>>^ Paul said to the army officer and the soldiers: “Unless these men remain in the boat, YOU cannot be saved.”

[[v44-27-32]]

^<<v44-27-32,32>>^ Then the soldiers cut away the ropes of the skiff and let it fall off.

[[v44-27-33]]

^<<v44-27-33,33>>^ Now close to the approach of day Paul began to encourage one and all to take some food, saying: “Today is the fourteenth day YOU have been on the watch and YOU are continuing without food, having taken nothing for yourselves.

[[v44-27-34]]

^<<v44-27-34,34>>^ Therefore I encourage YOU to take some food, for this is in the interest of YOUR safety; for not a hair of the head of one of YOU will perish.”

[[v44-27-35]]

^<<v44-27-35,35>>^ After he said this, he also took a loaf, gave thanks to God before them all and broke it and started eating.

[[v44-27-36]]

^<<v44-27-36,36>>^ So they all became cheerful and themselves began taking some food.

[[v44-27-37]]

^<<v44-27-37,37>>^ Now, all together, we souls^&#42;1^ in the boat were two hundred and seventy-six.^&#42;2^

[NOTE]
====
. Or, “persons.”
. “Two hundred and seventy-six,” אItmssVgSyh,p; A, “two hundred and seventy-five”; B, “about seventy-six.” In WH the Gr. word ὡς (hos, “about”) is marked by superior half-brackets, and in the margin appears the Gr. word di·a·koʹsi·ai, “two hundred.” The copyist for B evidently made a mistake by combining the final Omega, ῳ (oi), of the preceding Gr. word, πλοίῳ (ploiʹoi), with the next letter, Sigma, ς (s), standing for 200, to form the Gr. word ὡς (hos, “about”). Hence the actual number is 276 instead of 76.
====

[[v44-27-38]]

^<<v44-27-38,38>>^ When they had been satisfied with food, they proceeded to lighten the boat by throwing the wheat overboard into the sea.

[[v44-27-39]]

^<<v44-27-39,39>>^ Finally when it became day, they could not recognize the land but they were observing a certain bay with a beach, and on this they were determined, if they could, to beach the boat.

[[v44-27-40]]

^<<v44-27-40,40>>^ So, cutting away the anchors, they let them fall into the sea, at the same time loosing the lashings of the rudder oars and, after hoisting the foresail to the wind, they made for the beach.

[[v44-27-41]]

^<<v44-27-41,41>>^ When they lighted upon a shoal washed on each side by the sea, they ran the ship aground and the prow got stuck and stayed immovable, but the stern began to be violently broken to pieces.

[[v44-27-42]]

^<<v44-27-42,42>>^ At this it became the determination of the soldiers to kill the prisoners, that no one might swim away and escape.

[[v44-27-43]]

^<<v44-27-43,43>>^ But the army officer desired to bring Paul safely through and restrained them from their purpose. And he commanded those able to swim to cast themselves into the sea and make it to land first,

[[v44-27-44]]

^<<v44-27-44,44>>^ and the rest to do so, some upon planks and some upon certain things from the boat. And thus it came about that all were brought safely to land.

'''

xref:044-acts/044-acts-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-acts/044-acts-028.adoc#v44-28-0[Próximo Capítulo &#62;]