include::./index.adoc[]

[[v21-2-0]]
=== Ecclesiastes, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v21-2-1]]

^<<v21-2-1,1>>^ I said, even I, in my heart: “Do come now, let me try you out with rejoicing. Also, see good.” And, look! that too was vanity.

[[v21-2-2]]

^<<v21-2-2,2>>^ I said to laughter: “Insanity!” and to rejoicing: “What is this doing?”

[[v21-2-3]]

^<<v21-2-3,3>>^ I explored with my heart by cheering my flesh even with wine, while I was leading my heart with wisdom, even to lay hold on folly until I could see what good there was to the sons of mankind in what they did under the heavens for the number of the days of their life.

[[v21-2-4]]

^<<v21-2-4,4>>^ I engaged in greater works. I built houses for myself; I planted vineyards for myself.

[[v21-2-5]]

^<<v21-2-5,5>>^ I made gardens and parks^&#42;1^ for myself, and I planted in them fruit trees of all sorts.

[NOTE]
====
. “And parks.” Heb., u·phar·de·simʹ, pl. of par·desʹ; LXXSy, “parks; paradises.”
====

[[v21-2-6]]

^<<v21-2-6,6>>^ I made pools of water for myself, to irrigate with them the forest, springing up with trees.

[[v21-2-7]]

^<<v21-2-7,7>>^ I acquired menservants and maidservants, and I came to have sons of the household. Also, livestock, cattle and flocks in great quantity I came to have, more so than all those who happened to be before me in Jerusalem.

[[v21-2-8]]

^<<v21-2-8,8>>^ I accumulated also silver and gold for myself, and property peculiar to kings and the jurisdictional districts. I made male singers and female singers for myself and the exquisite delights of the sons of mankind, a lady, even ladies.

[[v21-2-9]]

^<<v21-2-9,9>>^ And I became greater and increased more than anyone that happened to be before me in Jerusalem. Moreover, my own wisdom remained mine.

[[v21-2-10]]

^<<v21-2-10,10>>^ And anything that my eyes asked for I did not keep away from them. I did not hold back my heart from any sort of rejoicing, for my heart was joyful because of all my hard work, and this came to be my portion from all my hard work.

[[v21-2-11]]

^<<v21-2-11,11>>^ And I, even I, turned toward all the works of mine that my hands had done and toward the hard work that I had worked hard to accomplish, and, look! everything was vanity and a striving after wind, and there was nothing of advantage under the sun.

[[v21-2-12]]

^<<v21-2-12,12>>^ And I, even I, turned to see wisdom and madness and folly; for what can the earthling man do who comes in after the king? The thing that people have already done.

[[v21-2-13]]

^<<v21-2-13,13>>^ And I saw, even I, that there exists more advantage for wisdom than for folly, just as there is more advantage for light than for darkness.

[[v21-2-14]]

^<<v21-2-14,14>>^ As regards anyone wise, his eyes are in his head; but the stupid one is walking on in sheer darkness. And I have come to know, I too, that there is one eventuality that eventuates to them all.

[[v21-2-15]]

^<<v21-2-15,15>>^ And I myself said in my heart: “An eventuality like that upon the stupid one will eventuate to me, yes, me.” Why, then, had I become wise, I overmuch so at that time? And I spoke in my heart: “This too is vanity.”

[[v21-2-16]]

^<<v21-2-16,16>>^ For there is no more remembrance of the wise one than of the stupid one to time indefinite. In the days that are already coming in, everyone is certainly forgotten; and how will the wise one die? Along with the stupid one.

[[v21-2-17]]

^<<v21-2-17,17>>^ And I hated life, because the work that has been done under the sun was calamitous from my standpoint, for everything was vanity and a striving after wind.

[[v21-2-18]]

^<<v21-2-18,18>>^ And I, even I, hated all my hard work at which I was working hard under the sun, that I would leave behind for the man who would come to be after me.

[[v21-2-19]]

^<<v21-2-19,19>>^ And who is there knowing whether he will prove to be wise or foolish? Yet he will take control over all my hard work at which I worked hard and at which I showed wisdom under the sun. This too is vanity.

[[v21-2-20]]

^<<v21-2-20,20>>^ And I myself turned around toward making my heart despair over all the hard work at which I had worked hard under the sun.

[[v21-2-21]]

^<<v21-2-21,21>>^ For there exists the man whose hard work has been with wisdom and with knowledge and with proficiency, but to a man that has not worked hard at such a thing will be given the portion of that one. This too is vanity and a big calamity.

[[v21-2-22]]

^<<v21-2-22,22>>^ For what does a man come to have^&#42;1^ for all his hard work and for the striving of his heart with which he is working hard under the sun?

[NOTE]
====
. Lit., “what is there proving to be for the man?” Heb., meh-ho·wehʹ la·ʼa·dhamʹ? The participle ho·wehʹ is from the root verb ha·wahʹ, related to the divine name, Yeho·wahʹ.
====

[[v21-2-23]]

^<<v21-2-23,23>>^ For all his days his occupation means pains and vexation, also during the night his heart just does not lie down. This too is mere vanity.

[[v21-2-24]]

^<<v21-2-24,24>>^ With a man there is nothing better &#91;than&#93; that he should eat and indeed drink and cause his soul to see good because of his hard work. This too I have seen, even I, that this is from the hand of the &#91;true&#93; God.^&#42;1^

[NOTE]
====
. “The [true] God.” Heb., ha·ʼElo·himʹ, with ha, “the,” for emphasis; TSy, “Jehovah.” See App 1F.
====

[[v21-2-25]]

^<<v21-2-25,25>>^ For who eats and who drinks^&#42;1^ better than I do?

[NOTE]
====
. “Drinks,” LXXBagsterSy; M, “hastens.”
====

[[v21-2-26]]

^<<v21-2-26,26>>^ For to the man that is good before him he has given wisdom and knowledge and rejoicing, but to the sinner he has given the occupation of gathering and bringing together merely to give to the one that is good before the &#91;true&#93; God. This too is vanity and a striving after wind.

'''

xref:021-ecclesiastes/021-ecclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]