include::./index.adoc[]

[[v21-7-0]]
=== Ecclesiastes, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v21-7-1]]

^<<v21-7-1,1>>^ A name^&#42;1^ is better than good oil, and the day of death than the day of one’s being born.

[NOTE]
====
. “A name.” Heb., shem; LXXVg, “A good name.” See Pr 22:1 ftn.
====

[[v21-7-2]]

^<<v21-7-2,2>>^ Better is it to go to the house of mourning than to go to the banquet house, because that is the end of all mankind; and the one alive should take &#91;it&#93; to his heart.

[[v21-7-3]]

^<<v21-7-3,3>>^ Better is vexation than laughter, for by the crossness of the face the heart becomes better.

[[v21-7-4]]

^<<v21-7-4,4>>^ The heart of the wise ones is in the house of mourning, but the heart of the stupid ones is in the house of rejoicing.

[[v21-7-5]]

^<<v21-7-5,5>>^ Better is it to hear the rebuke of someone wise than to be the man^&#42;1^ hearing the song of the stupid ones.

[NOTE]
====
. See 6:2 ftn.
====

[[v21-7-6]]

^<<v21-7-6,6>>^ For as the sound of thorns under the pot, so is the laughter of the stupid one; and this too is vanity.

[[v21-7-7]]

^<<v21-7-7,7>>^ For mere oppression may make a wise one act crazy, and a gift can destroy the heart.

[[v21-7-8]]

^<<v21-7-8,8>>^ Better is the end afterward of a matter than its beginning. Better is one who is patient^&#42;1^ than one who is haughty in spirit.

[NOTE]
====
. Lit., “long in spirit.”
====

[[v21-7-9]]

^<<v21-7-9,9>>^ Do not hurry yourself in your spirit to become offended, for the taking of offense is what rests in the bosom of the stupid ones.

[[v21-7-10]]

^<<v21-7-10,10>>^ Do not say: “Why has it happened that the former days proved to be better than these?” for it is not due to wisdom that you have asked about this.

[[v21-7-11]]

^<<v21-7-11,11>>^ Wisdom along with an inheritance is good and is advantageous^&#42;1^ for those seeing the sun.

[NOTE]
====
. Or, “Wisdom [compared] with a possession is better and is more profitable.”
====

[[v21-7-12]]

^<<v21-7-12,12>>^ For wisdom is for a protection^&#42;1^ &#91;the same as&#93; money is for a protection; but the advantage of knowledge is that wisdom itself preserves alive its owners.

[NOTE]
====
. Lit., “for a shadow.” Heb., betselʹ.
====

[[v21-7-13]]

^<<v21-7-13,13>>^ See the work of the &#91;true&#93; God, for who is able to make straight what he has made crooked?

[[v21-7-14]]

^<<v21-7-14,14>>^ On a good day prove yourself to be in goodness, and on a calamitous day see that the &#91;true&#93; God has made even this exactly as that, to the intent that mankind^&#42;1^ may not discover anything at all after them.

[NOTE]
====
. See 6:7 ftn.
====

[[v21-7-15]]

^<<v21-7-15,15>>^ Everything I have seen during my vain days. There exists the righteous one perishing in his righteousness, and there exists the wicked one continuing long in his badness.

[[v21-7-16]]

^<<v21-7-16,16>>^ Do not become righteous overmuch, nor show yourself excessively wise. Why should you cause desolation to yourself?

[[v21-7-17]]

^<<v21-7-17,17>>^ Do not be wicked overmuch, nor become foolish. Why should you die when it is not your time?

[[v21-7-18]]

^<<v21-7-18,18>>^ It is better that you should take hold of the one, but from the other also do not withdraw your hand; for he that fears God will go forth with them all.

[[v21-7-19]]

^<<v21-7-19,19>>^ Wisdom itself is stronger for the wise one than ten men in power who happened to be in a city.

[[v21-7-20]]

^<<v21-7-20,20>>^ For there is no man righteous in the earth that keeps doing good and does not sin.

[[v21-7-21]]

^<<v21-7-21,21>>^ Also, do not give your heart to all the words that people may speak, that you may not hear your servant calling down evil upon you.

[[v21-7-22]]

^<<v21-7-22,22>>^ For your own heart well knows even many times that you, even you, have called down evil upon others.

[[v21-7-23]]

^<<v21-7-23,23>>^ All this I have tested with wisdom. I said: “I will become wise.” But it was far from me.

[[v21-7-24]]

^<<v21-7-24,24>>^ What has come to be is far off and exceedingly deep. Who can find it out?

[[v21-7-25]]

^<<v21-7-25,25>>^ I myself turned around, even my heart did, to know and to explore and to search for wisdom and the reason of things, and to know about the wickedness of stupidity and the foolishness of madness;

[[v21-7-26]]

^<<v21-7-26,26>>^ and I was finding out: More bitter than death &#91;I found&#93; the woman who is herself nets for hunting and whose heart is dragnets &#91;and&#93; whose hands are fetters. One is good before the &#91;true&#93; God if one escapes from her, but one is sinning if one is captured by her.

[[v21-7-27]]

^<<v21-7-27,27>>^ “See! This I have found,” said the congregator,^&#42;1^ “one thing &#91;taken&#93; after another, to find out the sum-up,

[NOTE]
====
. “Said the congregator.” The verb and subject are both fem. See Title and 1:1 ftns.
====

[[v21-7-28]]

^<<v21-7-28,28>>^ which my soul has continuously sought, but I have not found. One man out of a thousand I have found, but a woman among all these I have not found.

[[v21-7-29]]

^<<v21-7-29,29>>^ See! This only I have found, that the &#91;true&#93; God made mankind^&#42;1^ upright, but they themselves have sought out many plans.”

[NOTE]
====
. “Mankind.” Heb., ha·ʼa·dhamʹ.
====

'''

xref:021-ecclesiastes/021-ecclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]