include::./index.adoc[]

[[v21-4-0]]
=== Ecclesiastes, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v21-4-1]]

^<<v21-4-1,1>>^ And I myself returned that I might see all the acts of oppression that are being done under the sun, and, look! the tears of those being oppressed, but they had no comforter; and on the side of their oppressors there was power, so that they had no comforter.

[[v21-4-2]]

^<<v21-4-2,2>>^ And I congratulated the dead who had already died rather than the living who were still alive.

[[v21-4-3]]

^<<v21-4-3,3>>^ So better than both of them &#91;is&#93; the one who has not yet come to be, who has not seen the calamitous work that is being done under the sun.

[[v21-4-4]]

^<<v21-4-4,4>>^ And I myself have seen all the hard work and all the proficiency in work, that it means the rivalry of one^&#42;1^ toward another; this also is vanity and a striving after the wind.

[NOTE]
====
. “One.” Heb., ʼish.
====

[[v21-4-5]]

^<<v21-4-5,5>>^ The stupid one is folding his hands and is eating his own flesh.

[[v21-4-6]]

^<<v21-4-6,6>>^ Better is a handful of rest than a double handful of hard work and striving after the wind.

[[v21-4-7]]

^<<v21-4-7,7>>^ I myself returned that I might see the vanity under the sun:

[[v21-4-8]]

^<<v21-4-8,8>>^ There exists one, but not a second one; also no son or brother does he have, but there is no end to all his hard work. Also, his eyes themselves are not satisfied with riches: “And for whom am I working hard and causing my soul to lack in good things?” This too is vanity, and it is a calamitous occupation.

[[v21-4-9]]

^<<v21-4-9,9>>^ Two are better than one, because they have a good reward for their hard work.

[[v21-4-10]]

^<<v21-4-10,10>>^ For if one of them should fall, the other one can raise his partner up. But how will it be with just the one^&#42;1^ who falls when there is not another to raise him up?

[NOTE]
====
. Or, “But woe to just the one!”
====

[[v21-4-11]]

^<<v21-4-11,11>>^ Moreover, if two lie down together, they also will certainly get warm; but how can just one keep warm?

[[v21-4-12]]

^<<v21-4-12,12>>^ And if somebody could overpower one alone, two together could make a stand against him. And a threefold cord cannot quickly be torn in two.

[[v21-4-13]]

^<<v21-4-13,13>>^ Better is a needy but wise child than an old but stupid king, who has not come to know enough to be warned any longer.

[[v21-4-14]]

^<<v21-4-14,14>>^ For he has gone forth from the prison house itself to become king, although in the kingship of this one he had been born as one of little means.

[[v21-4-15]]

^<<v21-4-15,15>>^ I have seen all those alive who are walking about under the sun, &#91;how it goes&#93; with the child, who is second, that stands up in the other one’s place.

[[v21-4-16]]

^<<v21-4-16,16>>^ There is no end to all the people, to all those before whom he^&#42;1^ happened to be; neither will people afterward rejoice in him, for this too is vanity and a striving after the wind.

[NOTE]
====
. Or, “they,” that is, “the people.”
====

'''

xref:021-ecclesiastes/021-ecclesiastes-003.adoc#v21-3-0[&#60; Capítulo Anterior] | <<v21-4-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-005.adoc#v21-5-0[Próximo Capítulo &#62;]