include::./index.adoc[]

[[v21-1-0]]
=== Ecclesiastes, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v21-1-1]]

^<<v21-1-1,1>>^ The words of the congregator,^&#42;1^ the son of David the king in Jerusalem.

[NOTE]
====
. Or, “assembler; convener; convoker,” M; LXXVg, “Ecclesiastes,” that is, a member of an ecclesia (congregation; assembly).
====

[[v21-1-2]]

^<<v21-1-2,2>>^ “The greatest vanity!”^&#42;1^ the congregator has said, “the greatest vanity! Everything is vanity!”

[NOTE]
====
. “The greatest vanity!” Lit., “Vanity of vanities,” M(Heb., havelʹ hava·limʹ)LXXSyVg.
====

[[v21-1-3]]

^<<v21-1-3,3>>^ What profit does a man^&#42;1^ have in all his hard work at which he works hard under the sun?^&#42;2^

[NOTE]
====
. Lit., “to an earthling man.” Heb., la·ʼa·dhamʹ.
. “Under the sun.” Heb., ta·chathʹ hash·shaʹmesh. This phrase occurs 29 times in Ecclesiastes.
====

[[v21-1-4]]

^<<v21-1-4,4>>^ A generation is going, and a generation is coming; but the earth is standing even to time indefinite.

[[v21-1-5]]

^<<v21-1-5,5>>^ And the sun also has flashed forth, and the sun has set, and it is coming panting to its place where it is going to flash forth.

[[v21-1-6]]

^<<v21-1-6,6>>^ The wind^&#42;1^ is going to the south, and it is circling around to the north. Round and round it^&#42;2^ is continually circling, and right back to its circlings the wind^&#42;3^ is returning.

[NOTE]
====
. “The wind.” Lit., “It,” possibly referring to the sun in its movements southward and northward between the summer and winter solstices.
. “It.” Lit., “the wind,” but in translation it is transferred to the beginning of the vs.
. “The wind.” Heb., ha·ruʹach; Gr., pneuʹma. Compare Ge 1:2 ftn, “Force.”
====

[[v21-1-7]]

^<<v21-1-7,7>>^ All the winter torrents are going forth to the sea, yet the sea itself is not full. To the place where the winter torrents are going forth, there they are returning so as to go forth.

[[v21-1-8]]

^<<v21-1-8,8>>^ All things are wearisome; no one is able to speak of it. The eye is not satisfied at seeing, neither is the ear filled from hearing.

[[v21-1-9]]

^<<v21-1-9,9>>^ That which has come to be, that is what will come to be; and that which has been done, that is what will be done; and so there is nothing new under the sun.^&#42;1^

[NOTE]
====
. See vs 3 ftn, “Sun.”
====

[[v21-1-10]]

^<<v21-1-10,10>>^ Does anything exist of which one may say: “See this; it is new”? It has already had existence for time indefinite; what has come into existence is from time prior to us.

[[v21-1-11]]

^<<v21-1-11,11>>^ There is no remembrance of people of former times, nor will there be of those also who will come to be later. There will prove to be no remembrance even of them among those who will come to be still later on.

[[v21-1-12]]

^<<v21-1-12,12>>^ I, the congregator,^&#42;1^ happened to be king over Israel in Jerusalem.

[NOTE]
====
. See vs 1 ftn.
====

[[v21-1-13]]

^<<v21-1-13,13>>^ And I set my heart to seek and explore wisdom in relation to everything that has been done under the heavens—the calamitous occupation that God has given to the sons of mankind^&#42;1^ in which to be occupied.

[NOTE]
====
. Or, “men.” Heb., ha·ʼa·dhamʹ.
====

[[v21-1-14]]

^<<v21-1-14,14>>^ I saw all the works that were done under the sun, and, look! everything was vanity and a striving after wind.^&#42;1^

[NOTE]
====
. See vs 6, second ftn on “Wind.”
====

[[v21-1-15]]

^<<v21-1-15,15>>^ That which is made crooked cannot be made straight, and that which is wanting cannot possibly be counted.

[[v21-1-16]]

^<<v21-1-16,16>>^ I, even I, spoke with my heart, saying: “Look! I myself have greatly increased in wisdom more than anyone that happened to be before me in Jerusalem, and my own heart saw a great deal of wisdom and knowledge.”

[[v21-1-17]]

^<<v21-1-17,17>>^ And I proceeded to give my heart to knowing wisdom and to knowing madness, and I have come to know folly, that this too is a striving after wind.^&#42;1^

[NOTE]
====
. See vs 6, second ftn on “Wind.”
====

[[v21-1-18]]

^<<v21-1-18,18>>^ For in the abundance of wisdom there is an abundance of vexation, so that he that increases knowledge increases pain.

'''

xref:020-proverbs/020-proverbs-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-ecclesiastes/021-ecclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]