include::./index.adoc[]

[[v56-3-0]]
=== To Titus, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v56-3-1]]

^<<v56-3-1,1>>^ Continue reminding them to be in subjection and be obedient to governments and authorities as rulers, to be ready for every good work,

[[v56-3-2]]

^<<v56-3-2,2>>^ to speak injuriously of no one, not to be belligerent,^&#42;1^ to be reasonable,^&#42;2^ exhibiting all mildness toward all men.

[NOTE]
====
. Lit., “not disposed to fight.”
. Lit., “yielding.”
====

[[v56-3-3]]

^<<v56-3-3,3>>^ For even we were once senseless, disobedient, being misled, being slaves to various desires and pleasures, carrying on in badness and envy, abhorrent, hating one another.

[[v56-3-4]]

^<<v56-3-4,4>>^ However, when the kindness and the love for man^&#42;1^ on the part of our Savior, God, was manifested,

[NOTE]
====
. Lit., “the philanthropy.” Gr., he phi·lan·thro·piʹa. Compare Ac 28:2 ftn, “Kindness.”
====

[[v56-3-5]]

^<<v56-3-5,5>>^ owing to no works in righteousness that we had performed, but according to his mercy he saved us through the bath that brought us to life^&#42;1^ and through the making of us new by holy spirit.

[NOTE]
====
. Or, “the bath of rebirth.” Lit., “bath of regeneration.” Gr., lou·trouʹ pa·lin·ge·ne·siʹas; Lat., la·vaʹcrum re·ge·ne·ra·ti·oʹnis. Compare Mt 19:28 ftn.
====

[[v56-3-6]]

^<<v56-3-6,6>>^ This &#91;spirit&#93; he poured out richly upon us through Jesus Christ our Savior,

[[v56-3-7]]

^<<v56-3-7,7>>^ that, after being declared righteous by virtue of the undeserved kindness of that one, we might become heirs according to a hope of everlasting life.

[[v56-3-8]]

^<<v56-3-8,8>>^ Faithful is the saying, and concerning these things I desire you to make firm assertions constantly, in order that those who have believed God may keep their minds on maintaining fine works. These things are fine and beneficial to men.

[[v56-3-9]]

^<<v56-3-9,9>>^ But shun foolish questionings and genealogies and strife and fights over the Law, for they are unprofitable and futile.

[[v56-3-10]]

^<<v56-3-10,10>>^ As for a man that promotes a sect,^&#42;1^ reject him after a first and a second admonition;^&#42;2^

[NOTE]
====
. “That promotes a sect.” Or, “sectarian.” Gr., hai·re·ti·konʹ; Lat., he·reʹti·cum.
. Lit., “putting mind within.”
====

[[v56-3-11]]

^<<v56-3-11,11>>^ knowing that such a man has been turned out of the way^&#42;1^ and is sinning, he being self-condemned.

[NOTE]
====
. Lit., “has been turned inside out.”
====

[[v56-3-12]]

^<<v56-3-12,12>>^ When I send Arʹte·mas or Tychʹi·cus to you, do your utmost to come to me at Ni·copʹo·lis, for there is where I have decided to winter.

[[v56-3-13]]

^<<v56-3-13,13>>^ Carefully supply Zeʹnas, who is versed in the Law,^&#42;1^ and A·polʹlos for their trip, that they may not lack anything.

[NOTE]
====
. “Versed in the Law.” Lit., “the lawyer.” Gr., ton no·mi·konʹ.
====

[[v56-3-14]]

^<<v56-3-14,14>>^ But let our people also learn to maintain fine works so as to meet their pressing needs, that they may not be unfruitful.

[[v56-3-15]]

^<<v56-3-15,15>>^ All those with me send you their greetings. Give my greetings to those who have affection for us in the faith.
May the undeserved kindness be with all of YOU people.

'''

xref:056-titus/056-titus-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-philemon/057-philemon-001.adoc#v57-1-0[Próximo Capítulo &#62;]