include::./index.adoc[]

[[v56-2-0]]
=== To Titus, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v56-2-1]]

^<<v56-2-1,1>>^ You, however, keep on speaking what things are fitting for healthful teaching.

[[v56-2-2]]

^<<v56-2-2,2>>^ Let the aged men be moderate in habits, serious, sound in mind, healthy in faith, in love, in endurance.

[[v56-2-3]]

^<<v56-2-3,3>>^ Likewise let the aged women be reverent in behavior, not slanderous, neither enslaved to a lot of wine, teachers of what is good;

[[v56-2-4]]

^<<v56-2-4,4>>^ that they may recall the young women to their senses^&#42;1^ to love their husbands, to love their children,

[NOTE]
====
. Lit., “they may be making mentally sound the young [women].”
====

[[v56-2-5]]

^<<v56-2-5,5>>^ to be sound in mind, chaste, workers at home, good, subjecting themselves to their own husbands, so that the word of God may not be spoken of abusively.^&#42;1^

[NOTE]
====
. Lit., “may not be blasphemed.” Gr., me . . . bla·sphe·meʹtai; Lat., non bla·sphe·meʹtur.
====

[[v56-2-6]]

^<<v56-2-6,6>>^ Likewise keep on exhorting the younger men to be sound in mind,

[[v56-2-7]]

^<<v56-2-7,7>>^ in all things showing yourself an example of fine works; showing uncorruptness in your teaching, seriousness,

[[v56-2-8]]

^<<v56-2-8,8>>^ wholesome speech which cannot be condemned; so that the man on the opposing side may get ashamed, having nothing vile to say about us.

[[v56-2-9]]

^<<v56-2-9,9>>^ Let slaves be in subjection to their owners in all things, and please them well, not talking back,

[[v56-2-10]]

^<<v56-2-10,10>>^ not committing theft,^&#42;1^ but exhibiting good fidelity to the full, so that they may adorn the teaching of our Savior, God, in all things.

[NOTE]
====
. Or, “not embezzling.”
====

[[v56-2-11]]

^<<v56-2-11,11>>^ For the undeserved kindness of God which brings salvation to all sorts of men has been manifested,

[[v56-2-12]]

^<<v56-2-12,12>>^ instructing us to repudiate ungodliness and worldly desires and to live with soundness of mind and righteousness and godly devotion^&#42;1^ amid this present system of things,^&#42;2^

[NOTE]
====
. “Godly devotion,” אAVg; J7,​8, “fear of Jehovah.”
. Or, “order of things.” Gr., ai·oʹni; Lat., saeʹcu·lo; J17,​22(Heb.), ba·ʽoh·lamʹ haz·zehʹ, “amid this order of things.”
====

[[v56-2-13]]

^<<v56-2-13,13>>^ while we wait for the happy hope and glorious manifestation of the great God and of &#91;the&#93; Savior of us, Christ Jesus,^&#42;1^

[NOTE]
====
. For a discussion of this vs, see App 6E.
====

[[v56-2-14]]

^<<v56-2-14,14>>^ who gave himself for us that he might deliver us from every sort of lawlessness and cleanse for himself a people peculiarly his own, zealous for fine works.

[[v56-2-15]]

^<<v56-2-15,15>>^ Keep on speaking these things and exhorting and reproving with full authority to command.^&#42;1^ Let no man ever despise you.

[NOTE]
====
. “Authority to command.” Lit., “enjoinder.”
====

'''

xref:056-titus/056-titus-001.adoc#v56-1-0[&#60; Capítulo Anterior] | <<v56-2-0,Topo>> | xref:056-titus/056-titus-003.adoc#v56-3-0[Próximo Capítulo &#62;]