include::./index.adoc[]

[[v56-1-0]]
=== To Titus, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v56-1-1]]

^<<v56-1-1,1>>^ Paul, a slave of God and an apostle of Jesus Christ according to the faith of God’s chosen ones and the accurate knowledge of the truth which accords with godly devotion

[[v56-1-2]]

^<<v56-1-2,2>>^ upon the basis of a hope of the everlasting life which God, who cannot lie, promised before times long lasting,^&#42;1^

[NOTE]
====
. Or, “promised long ago.”
====

[[v56-1-3]]

^<<v56-1-3,3>>^ whereas in his own due times he made his word manifest in the preaching^&#42;1^ with which I was entrusted, under command of our Savior, God;^&#42;2^

[NOTE]
====
. Or, “manifest in the public announcement.”
. Lit., “of the Savior of us, God.” Gr., tou so·teʹros he·monʹ The·ouʹ; Lat., Sal·va·toʹris noʹstri Deʹi; J17,​22(Heb.), ha·ʼElo·himʹ Moh·shi·ʽeʹnu.
====

[[v56-1-4]]

^<<v56-1-4,4>>^ to Titus, a genuine child according to a faith shared in common:
May there be undeserved kindness and peace from God &#91;the&#93; Father and Christ Jesus our Savior.

[[v56-1-5]]

^<<v56-1-5,5>>^ For this reason I left you in Crete, that you might correct the things that were defective and might make appointments of older men^&#42;1^ in city after city, as I gave you orders;

[NOTE]
====
. Or, “appoint elders.”
====

[[v56-1-6]]

^<<v56-1-6,6>>^ if there is any man free from accusation, a husband of one wife, having believing children that were not under a charge of debauchery nor unruly.

[[v56-1-7]]

^<<v56-1-7,7>>^ For an overseer^&#42;1^ must be free from accusation as God’s steward,^&#42;2^ not self-willed, not prone to wrath, not a drunken brawler, not a smiter, not greedy of dishonest gain,

[NOTE]
====
. “Overseer.” Gr., e·piʹsko·pon; J17(Heb.), pheqidhʹ.
. Or, “house manager.” Lit., “house administrator.” Gr., oi·ko·noʹmon; Lat., di·spen·sa·toʹrem; J17(Heb.), keso·khenʹ, “as steward.”
====

[[v56-1-8]]

^<<v56-1-8,8>>^ but hospitable,^&#42;1^ a lover of goodness, sound in mind, righteous, loyal, self-controlled,

[NOTE]
====
. Or, “a lover of strangers.”
====

[[v56-1-9]]

^<<v56-1-9,9>>^ holding firmly to the faithful word as respects his &#91;art of&#93; teaching, that he may be able both to exhort by the teaching that is healthful and to reprove those who contradict.

[[v56-1-10]]

^<<v56-1-10,10>>^ For there are many unruly men,^&#42;1^ profitless talkers, and deceivers of the mind, especially those men who adhere to the circumcision.

[NOTE]
====
. “Unruly men.” Lit., “not self-subjecting (ones).”
====

[[v56-1-11]]

^<<v56-1-11,11>>^ It is necessary to shut the mouths of these, as these very men keep on subverting entire households by teaching things they ought not for the sake of dishonest gain.

[[v56-1-12]]

^<<v56-1-12,12>>^ A certain one of them, their own prophet,^&#42;1^ said: “Creʹtans are always liars, injurious wild beasts, unemployed gluttons.”^&#42;2^

[NOTE]
====
. Epimenides, a Cretan poet of the sixth cent. B.C.E.
. “Unemployed gluttons.” Lit., “ineffective bellies.”
====

[[v56-1-13]]

^<<v56-1-13,13>>^ This witness is true. For this very cause keep on reproving them with severity, that they may be healthy in the faith,

[[v56-1-14]]

^<<v56-1-14,14>>^ paying no attention to Jewish fables and commandments of men who turn themselves away from the truth.

[[v56-1-15]]

^<<v56-1-15,15>>^ All things are clean to clean &#91;persons&#93;. But to &#91;persons&#93; defiled and faithless nothing is clean, but both their minds and their consciences are defiled.

[[v56-1-16]]

^<<v56-1-16,16>>^ They publicly declare they know God, but they disown him by their works, because they are detestable and disobedient and not approved for good work of any sort.

'''

xref:055-2-timothy/055-2-timothy-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-titus/056-titus-002.adoc#v56-2-0[Próximo Capítulo &#62;]