include::./index.adoc[]

[[v59-5-0]]
=== The Letter of James, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v59-5-1]]

^<<v59-5-1,1>>^ Come, now, YOU rich &#91;men&#93;, weep, howling over YOUR miseries that are coming upon YOU.

[[v59-5-2]]

^<<v59-5-2,2>>^ YOUR riches have rotted, and YOUR outer garments have become moth-eaten.

[[v59-5-3]]

^<<v59-5-3,3>>^ YOUR gold and silver are rusted away, and their rust will be as a witness against YOU and will eat YOUR fleshy parts. Something like fire is what YOU have stored up in the last days.^&#42;1^

[NOTE]
====
. “And will eat your fleshy parts like fire. You have stored up treasure in the last days,” Vg.
====

[[v59-5-4]]

^<<v59-5-4,4>>^ Look! The wages due the workers who harvested YOUR fields but which are held up by YOU, keep crying out, and the calls for help on the part of the reapers have entered into the ears of Jehovah^&#42;1^ of armies.

[NOTE]
====
. See App 1D.
====

[[v59-5-5]]

^<<v59-5-5,5>>^ YOU have lived in luxury upon the earth and have gone in for sensual pleasure.^&#42;1^ YOU have fattened YOUR hearts on the day of slaughter.

[NOTE]
====
. Lit., “you behaved voluptuously.”
====

[[v59-5-6]]

^<<v59-5-6,6>>^ YOU have condemned, YOU have murdered the righteous one. Is he not opposing YOU?^&#42;1^

[NOTE]
====
. Or, “the righteous one; he is not opposing you.”
====

[[v59-5-7]]

^<<v59-5-7,7>>^ Exercise patience, therefore, brothers, until the presence^&#42;1^ of the Lord. Look! The farmer keeps waiting for the precious fruit of the earth, exercising patience over it until he gets the early rain and the late rain.

[NOTE]
====
. See App 5B.
====

[[v59-5-8]]

^<<v59-5-8,8>>^ YOU too exercise patience; make YOUR hearts firm, because the presence of the Lord has drawn close.

[[v59-5-9]]

^<<v59-5-9,9>>^ Do not heave sighs^&#42;1^ against one another, brothers, so that YOU do not get judged. Look! The Judge is standing before the doors.

[NOTE]
====
. Lit., “Do not be groaning.”
====

[[v59-5-10]]

^<<v59-5-10,10>>^ Brothers, take as a pattern of the suffering of evil and the exercising of patience the prophets, who spoke in the name of Jehovah.^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v59-5-11]]

^<<v59-5-11,11>>^ Look! We pronounce happy those who have endured. YOU have heard of the endurance of Job and have seen the outcome^&#42;1^ Jehovah^&#42;2^ gave, that Jehovah^&#42;3^ is very tender in affection and merciful.^&#42;4^

[NOTE]
====
. Lit., “end.” Gr., teʹlos.
. See App 1D.
. See App 1D.
. Lit., “compassionate.”
====

[[v59-5-12]]

^<<v59-5-12,12>>^ Above all things, though, my brothers, stop swearing, yes, either by heaven or by earth or by any other oath. But let YOUR Yes mean Yes, and YOUR No, No, so that YOU do not fall under judgment.

[[v59-5-13]]

^<<v59-5-13,13>>^ Is there anyone suffering evil among YOU? Let him carry on prayer. Is there anyone in good spirits? Let him sing psalms.^&#42;1^

[NOTE]
====
. Or, “praises to God.”
====

[[v59-5-14]]

^<<v59-5-14,14>>^ Is there anyone sick among YOU? Let him call the older men^&#42;1^ of the congregation to &#91;him&#93;, and let them pray over him, greasing &#91;him&#93; with oil in the name of Jehovah.^&#42;2^

[NOTE]
====
. Or, “elders.” Gr., pre·sby·teʹrous; J17,​22(Heb.), ziq·nehʹ. See Nu 11:25.
. See App 1D.
====

[[v59-5-15]]

^<<v59-5-15,15>>^ And the prayer of faith will make the indisposed one well,^&#42;1^ and Jehovah^&#42;2^ will raise him up. Also, if he has committed sins, it will be forgiven him.

[NOTE]
====
. Lit., “will save the (one) being tired.”
. See App 1D.
====

[[v59-5-16]]

^<<v59-5-16,16>>^ Therefore openly confess YOUR sins to one another and pray for one another, that YOU may get healed. A righteous man’s supplication, when it is at work,^&#42;1^ has much force.

[NOTE]
====
. Or, “when rendered with earnestness.”
====

[[v59-5-17]]

^<<v59-5-17,17>>^ E·liʹjah was a man with feelings like ours, and yet in prayer he prayed for it not to rain; and it did not rain upon the land for three years and six months.

[[v59-5-18]]

^<<v59-5-18,18>>^ And he prayed again, and the heaven gave rain and the land put forth its fruit.

[[v59-5-19]]

^<<v59-5-19,19>>^ My brothers, if anyone among YOU is misled^&#42;1^ from the truth and another turns him back,

[NOTE]
====
. Lit., “should be made to err.”
====

[[v59-5-20]]

^<<v59-5-20,20>>^ know that he who turns a sinner back from the error of his way will save his soul from death and will cover a multitude of sins.

'''

xref:059-james/059-james-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-peter/060-1-peter-001.adoc#v60-1-0[Próximo Capítulo &#62;]