include::./index.adoc[]

[[v59-1-0]]
=== The Letter of James, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v59-1-1]]

^<<v59-1-1,1>>^ James,^&#42;1^ a slave of God and of &#91;the&#93; Lord Jesus Christ, to the twelve tribes that are scattered about:^&#42;2^
Greetings!

[NOTE]
====
. Lit., “Jacob.” Gr., I·aʹko·bos. “James” is an abbreviated English form of Jacob, meaning “Taking Hold of the Heel; Supplanter.”
. “That are scattered about.” Lit., “the (ones) in the dispersion [Gr., di·a·spo·raiʹ; Lat., di·sper·si·oʹne].”
====

[[v59-1-2]]

^<<v59-1-2,2>>^ Consider it all joy, my brothers, when YOU meet with various trials,

[[v59-1-3]]

^<<v59-1-3,3>>^ knowing as YOU do that this tested quality of^&#42;1^ YOUR faith works out endurance.

[NOTE]
====
. Or, “this way of testing.”
====

[[v59-1-4]]

^<<v59-1-4,4>>^ But let endurance have its work complete, that YOU may be complete and sound in all respects, not lacking in anything.

[[v59-1-5]]

^<<v59-1-5,5>>^ So, if any one of YOU is lacking in wisdom, let him keep on asking God, for he gives generously to all and without reproaching; and it will be given him.

[[v59-1-6]]

^<<v59-1-6,6>>^ But let him keep on asking in faith, not doubting^&#42;1^ at all, for he who doubts is like a wave of the sea driven by the wind and blown about.

[NOTE]
====
. Lit., “judging for self dividedly.”
====

[[v59-1-7]]

^<<v59-1-7,7>>^ In fact, let not that man suppose that he will receive anything from Jehovah;^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v59-1-8]]

^<<v59-1-8,8>>^ he is an indecisive^&#42;1^ man, unsteady in all his ways.

[NOTE]
====
. Lit., “two-souled.” Gr., diʹpsy·khos; Lat., duʹplex aʹni·mo.
====

[[v59-1-9]]

^<<v59-1-9,9>>^ But let the lowly brother exult over his exaltation,

[[v59-1-10]]

^<<v59-1-10,10>>^ and the rich one over his humiliation, because like a flower of the vegetation he will pass away.

[[v59-1-11]]

^<<v59-1-11,11>>^ For the sun rises with its burning heat and withers the vegetation, and its flower drops off and the beauty of its outward appearance perishes. So, too, the rich man will fade away in his ways of life.

[[v59-1-12]]

^<<v59-1-12,12>>^ Happy is the man that keeps on enduring trial, because on becoming approved he will receive the crown of life, which Jehovah^&#42;1^ promised to those who continue loving him.

[NOTE]
====
. “Jehovah,” J7,​8,​13,​16,​17; C(Gr.), Kyʹri·os; ItVgSyp, “God”; אAB omit. See App 1D.
====

[[v59-1-13]]

^<<v59-1-13,13>>^ When under trial, let no one say: “I am being tried by God.” For with evil things God cannot be tried nor does he himself try anyone.

[[v59-1-14]]

^<<v59-1-14,14>>^ But each one is tried by being drawn out and enticed^&#42;1^ by his own desire.

[NOTE]
====
. Or, “caught as by bait.” Lit., “being baited on.”
====

[[v59-1-15]]

^<<v59-1-15,15>>^ Then the desire, when it has become fertile, gives birth to sin; in turn, sin, when it has been accomplished, brings forth death.

[[v59-1-16]]

^<<v59-1-16,16>>^ Do not be misled, my beloved brothers.

[[v59-1-17]]

^<<v59-1-17,17>>^ Every good gift and every perfect present is from above, for it comes down from the Father of the &#91;celestial&#93; lights, and with him there is not a variation of the turning of the shadow.^&#42;1^

[NOTE]
====
. Or, “variation or shadow caused by a turning.”
====

[[v59-1-18]]

^<<v59-1-18,18>>^ Because he willed it, he brought us forth by the word of truth, for us to be certain firstfruits of his creatures.

[[v59-1-19]]

^<<v59-1-19,19>>^ Know this, my beloved brothers. Every man must be swift about hearing, slow about speaking, slow about wrath;

[[v59-1-20]]

^<<v59-1-20,20>>^ for man’s wrath does not work out God’s righteousness.

[[v59-1-21]]

^<<v59-1-21,21>>^ Hence put away all filthiness and that superfluous thing, badness, and accept with mildness the implanting of the word which is able to save YOUR souls.^&#42;1^

[NOTE]
====
. Or, “your lives.” Gr., tas psy·khasʹ hy·monʹ; Lat., aʹni·mas veʹstras; J17(Heb.), naph·sho·theh·khemʹ.
====

[[v59-1-22]]

^<<v59-1-22,22>>^ However, become doers of the word, and not hearers only, deceiving yourselves with false reasoning.

[[v59-1-23]]

^<<v59-1-23,23>>^ For if anyone is a hearer of the word, and not a doer, this one is like a man looking at his natural face in a mirror.

[[v59-1-24]]

^<<v59-1-24,24>>^ For he looks at himself, and off he goes and immediately forgets what sort of man he is.

[[v59-1-25]]

^<<v59-1-25,25>>^ But he who peers^&#42;1^ into the perfect law that belongs to freedom and who persists in &#91;it&#93;, this &#91;man&#93;, because he has become, not a forgetful hearer, but a doer of the work, will be happy in his doing &#91;it&#93;.

[NOTE]
====
. Lit., “having stooped beside.”
====

[[v59-1-26]]

^<<v59-1-26,26>>^ If any man seems to himself^&#42;1^ to be a formal worshiper^&#42;2^ and yet does not bridle his tongue, but goes on deceiving his own heart, this man’s form of worship is futile.

[NOTE]
====
. Or, “thinks himself.”
. “Formal worshiper.” Lat., re·li·gi·oʹsum, “religious.”
====

[[v59-1-27]]

^<<v59-1-27,27>>^ The form of worship^&#42;1^ that is clean and undefiled from the standpoint of our God and Father is this: to look after orphans^&#42;2^ and widows in their tribulation, and to keep oneself without spot from the world.

[NOTE]
====
. “Form of worship.” Gr., thre·skeiʹa; Lat., re·liʹgi·o, “religion.”
. Or, “bereaved ones.”
====

'''

xref:058-hebrews/058-hebrews-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-james/059-james-002.adoc#v59-2-0[Próximo Capítulo &#62;]