include::./index.adoc[]

[[v59-3-0]]
=== The Letter of James, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v59-3-1]]

^<<v59-3-1,1>>^ Not many of YOU should become teachers, my brothers, knowing that we shall receive heavier judgment.

[[v59-3-2]]

^<<v59-3-2,2>>^ For we all stumble many times. If anyone does not stumble in word, this one is a perfect man, able to bridle also &#91;his&#93; whole body.

[[v59-3-3]]

^<<v59-3-3,3>>^ If we put bridles in the mouths of horses for them to obey us, we manage also their whole body.

[[v59-3-4]]

^<<v59-3-4,4>>^ Look! Even boats, although they are so big and are driven by hard winds, are steered by a very small rudder to where the inclination of the man at the helm wishes.

[[v59-3-5]]

^<<v59-3-5,5>>^ So, too, the tongue is a little member and yet makes great brags. Look! How little a fire it takes to set so great a woodland on fire!

[[v59-3-6]]

^<<v59-3-6,6>>^ Well, the tongue is a fire. The tongue is constituted a world of unrighteousness among our members, for it spots up all the body and sets the wheel of natural life aflame and it is set aflame by Ge·henʹna.^&#42;1^

[NOTE]
====
. See App 4C.
====

[[v59-3-7]]

^<<v59-3-7,7>>^ For every species of wild beast as well as bird and creeping thing and sea creature is to be tamed and has been tamed by humankind.

[[v59-3-8]]

^<<v59-3-8,8>>^ But the tongue, not one of mankind can get it tamed. An unruly injurious thing, it is full of death-dealing poison.

[[v59-3-9]]

^<<v59-3-9,9>>^ With it we bless Jehovah,^&#42;1^ even &#91;the&#93; Father, and yet with it we curse men who have come into existence “in the likeness of God.”

[NOTE]
====
. “Jehovah,” J18,​23; אABC(Gr.), ton Kyʹri·on; VgcSyh, “God.” See App 1D.
====

[[v59-3-10]]

^<<v59-3-10,10>>^ Out of the same mouth come forth blessing and cursing.
It is not proper, my brothers, for these things to go on occurring this way.

[[v59-3-11]]

^<<v59-3-11,11>>^ A fountain does not cause the sweet and the bitter to bubble out of the same opening, does it?

[[v59-3-12]]

^<<v59-3-12,12>>^ My brothers, a fig tree cannot produce olives or a vine figs, can it? Neither can salt water produce sweet water.

[[v59-3-13]]

^<<v59-3-13,13>>^ Who is wise and understanding among YOU? Let him show out of his fine conduct his works with a mildness that belongs to wisdom.

[[v59-3-14]]

^<<v59-3-14,14>>^ But if YOU have bitter jealousy and contentiousness in YOUR hearts, do not be bragging^&#42;1^ and lying against the truth.

[NOTE]
====
. Lit., “not be you boasting down.”
====

[[v59-3-15]]

^<<v59-3-15,15>>^ This is not the wisdom that comes down from above, but is &#91;the&#93; earthly, animal,^&#42;1^ demonic.

[NOTE]
====
. Lit., “soulical.” Gr., psy·khi·keʹ; Lat., a·ni·maʹlis. See 1Co 2:14 and 1Co 15:44 ftns.
====

[[v59-3-16]]

^<<v59-3-16,16>>^ For where jealousy and contentiousness are, there disorder^&#42;1^ and every vile thing are.

[NOTE]
====
. Lit., “unsettled state.”
====

[[v59-3-17]]

^<<v59-3-17,17>>^ But the wisdom from above is first of all chaste, then peaceable, reasonable,^&#42;1^ ready to obey, full of mercy and good fruits, not making partial distinctions, not hypocritical.

[NOTE]
====
. Lit., “yielding.”
====

[[v59-3-18]]

^<<v59-3-18,18>>^ Moreover, the fruit of righteousness has its seed sown under peaceful conditions^&#42;1^ for^&#42;2^ those who are making peace.

[NOTE]
====
. Or, “sown with peace.”
. Or, “by.”
====

'''

xref:059-james/059-james-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-james/059-james-004.adoc#v59-4-0[Próximo Capítulo &#62;]