include::./index.adoc[]

[[v59-4-0]]
=== The Letter of James, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v59-4-1]]

^<<v59-4-1,1>>^ From what source are there wars and from what source are there fights among YOU? Are they not from this source, namely, from YOUR cravings for sensual pleasure that carry on a conflict in YOUR members?

[[v59-4-2]]

^<<v59-4-2,2>>^ YOU desire, and yet YOU do not have. YOU go on murdering and coveting,^&#42;1^ and yet YOU are not able to obtain. YOU go on fighting and waging war. YOU do not have because of YOUR not asking.

[NOTE]
====
. Or, “and are jealous.”
====

[[v59-4-3]]

^<<v59-4-3,3>>^ YOU do ask, and yet YOU do not receive, because YOU are asking for a wrong purpose, that YOU may expend &#91;it&#93; upon YOUR cravings for sensual pleasure.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adulteresses,^&#42;1^ do YOU not know that the friendship with the world is enmity with God? Whoever, therefore, wants to be a friend of the world is constituting himself an enemy of God.

[NOTE]
====
. “Adulteresses.” Lat., a·dulʹte·ri.
====

[[v59-4-5]]

^<<v59-4-5,5>>^ Or does it seem to YOU that the scripture says to no purpose: “It is with a tendency to envy that the spirit which has taken up residence within us keeps longing”?

[[v59-4-6]]

^<<v59-4-6,6>>^ However, the undeserved kindness which he gives is greater. Hence it says: “God opposes the haughty ones, but he gives undeserved kindness to the humble ones.”

[[v59-4-7]]

^<<v59-4-7,7>>^ Subject yourselves, therefore, to God; but oppose^&#42;1^ the Devil, and he will flee from YOU.

[NOTE]
====
. Lit., “stand you against.”
====

[[v59-4-8]]

^<<v59-4-8,8>>^ Draw close to God, and he will draw close to YOU. Cleanse YOUR hands, YOU sinners, and purify YOUR hearts, YOU indecisive^&#42;1^ ones.

[NOTE]
====
. Lit., “two-souled.”
====

[[v59-4-9]]

^<<v59-4-9,9>>^ Give way to misery and mourn and weep. Let YOUR laughter be turned into mourning, and &#91;YOUR&#93; joy into dejection.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humble yourselves in the eyes of Jehovah,^&#42;1^ and he will exalt YOU.

[NOTE]
====
. See App 1D.
====

[[v59-4-11]]

^<<v59-4-11,11>>^ Quit speaking against one another, brothers. He who speaks against a brother or judges his brother speaks against law and judges law. Now if you judge law, you are, not a doer of law, but a judge.

[[v59-4-12]]

^<<v59-4-12,12>>^ One there is that is lawgiver and judge, he who is able to save and to destroy. But you, who are you to be judging &#91;your&#93; neighbor?

[[v59-4-13]]

^<<v59-4-13,13>>^ Come, now, YOU who say: “Today or tomorrow we will journey to this city and will spend a year there, and we will engage in business and make profits,”

[[v59-4-14]]

^<<v59-4-14,14>>^ whereas YOU do not know what YOUR life will be tomorrow. For YOU are a mist appearing for a little while and then disappearing.

[[v59-4-15]]

^<<v59-4-15,15>>^ Instead, YOU ought to say: “If Jehovah^&#42;1^ wills, we shall live and also do this or that.”

[NOTE]
====
. See App 1D.
====

[[v59-4-16]]

^<<v59-4-16,16>>^ But now YOU take pride in YOUR self-assuming brags. All such taking of pride is wicked.

[[v59-4-17]]

^<<v59-4-17,17>>^ Therefore, if one knows how to do what is right and yet does not do it, it is a sin for him.

'''

xref:059-james/059-james-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-james/059-james-005.adoc#v59-5-0[Próximo Capítulo &#62;]