include::./index.adoc[]

[[v5-32-0]]
=== Deuteronomy, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-32-1]]

^<<v5-32-1,1>>^ “Give ear, O heavens, and let me speak;
And let the earth hear the sayings of my mouth.

[[v5-32-2]]

^<<v5-32-2,2>>^ My instruction will drip as the rain,
My saying will trickle as the dew,
As gentle rains upon grass
And as copious showers upon vegetation.

[[v5-32-3]]

^<<v5-32-3,3>>^ For I shall declare the name of Jehovah.^&#42;1^
Do YOU attribute greatness to our God!

[NOTE]
====
. See App 1C §1.
====

[[v5-32-4]]

^<<v5-32-4,4>>^ The Rock, perfect is his activity,^&#42;1^
For all his ways are justice.
A God^&#42;2^ of faithfulness, with whom there is no injustice;
Righteous and upright is he.

[NOTE]
====
. “The Rock, perfect is his activity.” Heb., hats·Tsurʹ ta·mimʹ po·ʽolohʹ; LXX, “God, true are his works”; Sy, “For without blemish (spotless) are his works”; Vg, “God’s works are perfect.”
. “A God,” M(Heb., ʼEl)Sam; Gr., The·osʹ; Lat., Deʹus.
====

[[v5-32-5]]

^<<v5-32-5,5>>^ They have^&#42;1^ acted ruinously on their own part;^&#42;2^
They are not his children, the defect is their own.^&#42;3^
A generation crooked and twisted!

[NOTE]
====
. “They have,” SamLXXSyVg; M, “He has.”
. Or, “ruinously toward him.”
. “They have sinned; blameworthy children do not belong to him,” LXX.
====

[[v5-32-6]]

^<<v5-32-6,6>>^ Is it to Jehovah^&#42;1^ that YOU keep doing this way,
O people stupid and not wise?
Is he not your Father who has produced you,
He who made you and proceeded to give you stability?

[NOTE]
====
. See App 1C §1.
====

[[v5-32-7]]

^<<v5-32-7,7>>^ Remember the days of old,
CONSIDER the years back from generation to generation;
Ask your father, and he can tell you;
Your old men, and they can say it to you.

[[v5-32-8]]

^<<v5-32-8,8>>^ When the Most High gave the nations an inheritance,^&#42;1^
When he parted the sons of Adam^&#42;2^ from one another,
He proceeded to fix the boundary of the peoples
With regard for the number of the sons of Israel.

[NOTE]
====
. “When the Most High was dividing nations,” LXXSyVg. Evidently they understood the Heb. verb to be derived from a similar-looking root that means “to sift; to pass through a sieve.” According to this, M would read: “When the Most High sprinkled the nations [as through a sieve].” This thought runs parallel, or in poetic balance, with the second part of the vs. See VT, Vol. II, 1952, pp. 356, 357.
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v5-32-9]]

^<<v5-32-9,9>>^ For Jehovah’s share is^&#42;1^ his people;
Jacob is the allotment that he inherits.

[NOTE]
====
. “And Jehovah’s share became,” LXX.
====

[[v5-32-10]]

^<<v5-32-10,10>>^ He came to find him in a wilderness land,
And in an empty,^&#42;1^ howling desert.
He began to encircle him, to take care of him,
To safeguard him as the pupil of his eye.

[NOTE]
====
. Or, “and in a featureless.” Heb., u·vethoʹhu, the same Heb. noun as in Ge 1:2.
====

[[v5-32-11]]

^<<v5-32-11,11>>^ Just as an eagle stirs up its nest,
Hovers over its fledglings,
Spreads out its wings, takes them,
Carries them on its pinions,

[[v5-32-12]]

^<<v5-32-12,12>>^ Jehovah alone kept leading him,
And there was no foreign god^&#42;1^ along with him.

[NOTE]
====
. “God.” MSam(Heb.), ʼel; Gr., the·osʹ.
====

[[v5-32-13]]

^<<v5-32-13,13>>^ He kept making him ride upon earth’s high places,
So that he ate^&#42;1^ the produce of the field.
And he kept making him suck honey out of a crag,
And oil out of a flinty rock;

[NOTE]
====
. Or, “and he continued to eat,” M; Vg, “that he might eat”; Sam, “he made him eat”; LXX, “he made them eat.”
====

[[v5-32-14]]

^<<v5-32-14,14>>^ Butter^&#42;1^ of the herd and milk of the flock
Together with the fat of rams,
And male sheep, the breed of Baʹshan, and he-goats
Together with the kidney fat of wheat;
And the blood of the grape you kept drinking as wine.^&#42;2^

[NOTE]
====
. Or, “curds.”
. “Wine.” Heb., chaʹmer, that is, still-foaming, fermenting wine.
====

[[v5-32-15]]

^<<v5-32-15,15>>^ When Jeshʹu·run^&#42;1^ began to grow fat, then he kicked.^&#42;2^
You have grown fat, you have become thick, you have become gorged.
So he forsook God,^&#42;3^ who made him,
And despised the Rock^&#42;4^ of his salvation.

[NOTE]
====
. Meaning “Upright One”; an honorary title for Israel. Heb., Yeshu·runʹ.
. “And Jacob ate and got full and the loved one kicked,” LXX (Sam is similar); Vg, “The dear one got fat and kicked.”
. “God,” MSam. Heb., ʼElohʹah, the first occurrence of the sing. form of ʼElo·himʹ; Gr., The·onʹ; Lat., Deʹum. See Job 3:4 ftn.
. “The Rock of.” Heb., Tsur; LXXVg, “God”; Sy, “Strong (Mighty) One.”
====

[[v5-32-16]]

^<<v5-32-16,16>>^ They began inciting him to jealousy with strange gods;
With detestable things they kept offending him.

[[v5-32-17]]

^<<v5-32-17,17>>^ They went sacrificing to demons,^&#42;1^ not to God,^&#42;2^
Gods^&#42;3^ whom they had not known,
New ones who recently came in,
With whom YOUR forefathers were not acquainted.^&#42;4^

[NOTE]
====
. “To demons (idols).” Heb., lash·she·dhimʹ; Gr., dai·mo·niʹois; Lat., dae·moʹni·bus.
. “Not to God.” Heb., loʼ ʼEloʹah; Gr., ou The·oiʹ; Lat., non Deʹo.
. “Gods.” Heb., ʼelo·himʹ; Gr., the·oisʹ; Lat., diʹis.
. Or, “about whom your forefathers had not known.”
====

[[v5-32-18]]

^<<v5-32-18,18>>^ The Rock who fathered you, you proceeded to forget,
And you began to leave God out of memory, the One bringing you forth with childbirth pains.

[[v5-32-19]]

^<<v5-32-19,19>>^ When Jehovah^&#42;1^ saw it, then he came to disrespect them,
Because of the vexation his sons and his daughters gave.

[NOTE]
====
. See App 1C §1.
====

[[v5-32-20]]

^<<v5-32-20,20>>^ So he said, ‘Let me conceal my face from them,
Let me see what their end will be afterward.
For they are a generation of perverseness,
Sons in whom there is no faithfulness.

[[v5-32-21]]

^<<v5-32-21,21>>^ They, for their part, have incited me to jealousy with what is no god;
They have vexed me with their vain idols;^&#42;1^
And I, for my part, shall incite them to jealousy with what is no people;
With a stupid nation I shall offend them.

[NOTE]
====
. Lit., “their vanities.”
====

[[v5-32-22]]

^<<v5-32-22,22>>^ For a fire has been ignited in my anger
And it will burn down to Sheʹol, the lowest place,^&#42;1^
And it will consume the earth and its produce
And will set ablaze the foundations of mountains.

[NOTE]
====
. Or, “down to the lowest Sheol.” LXX, “to Hades below.”
====

[[v5-32-23]]

^<<v5-32-23,23>>^ I shall increase calamities upon them;
My arrows I shall spend upon them.

[[v5-32-24]]

^<<v5-32-24,24>>^ Exhausted from hunger they will be and eaten up by burning fever
And bitter destruction.
And the teeth of beasts I shall send upon them,
With the venom of reptiles of the dust.

[[v5-32-25]]

^<<v5-32-25,25>>^ Outdoors a sword will bereave them,
And indoors^&#42;1^ fright,
Of both young man and virgin,
Suckling together with gray-haired man.

[NOTE]
====
. Lit., “at the interior rooms.”
====

[[v5-32-26]]

^<<v5-32-26,26>>^ I should have said: “I shall disperse them,^&#42;1^
I will make the mention of them cease from mortal men,”

[NOTE]
====
. Or, “cleave them in pieces.”
====

[[v5-32-27]]

^<<v5-32-27,27>>^ Were it not that I was afraid of vexation from the enemy,
That their adversaries might misconstrue it,
That they might say: “Our hand^&#42;1^ has proved superior,
And it was not Jehovah who worked all this out.”

[NOTE]
====
. “Our hand,” SamLXXSyVg and many Heb. mss; M, “Our hands,” but with a sing. verb.
====

[[v5-32-28]]

^<<v5-32-28,28>>^ For they are a nation on whom counsel perishes,
And among them there is no understanding.

[[v5-32-29]]

^<<v5-32-29,29>>^ O that they were wise! Then they would ponder over this.
They would consider their end afterward.

[[v5-32-30]]

^<<v5-32-30,30>>^ How could one pursue a thousand,
And two put ten thousand to flight?
Not unless their Rock had sold them^&#42;1^
And Jehovah had surrendered them.^&#42;2^

[NOTE]
====
. “Had delivered them up,” LXX.
. “Had shut them up,” Vg.
====

[[v5-32-31]]

^<<v5-32-31,31>>^ For their rock is not like our Rock,^&#42;1^
Even our enemies being the ones to decide.^&#42;2^

[NOTE]
====
. “For their gods are not like our God,” LXX; Vgc, “For our God is not like their gods.”
. “And our enemies are judges,” Vg; LXX, “but our enemies are senseless.”
====

[[v5-32-32]]

^<<v5-32-32,32>>^ For their vine is from the vine of Sodʹom
And from the terraces of Go·morʹrah.
Their grapes are grapes of poison,
Their clusters are bitter.

[[v5-32-33]]

^<<v5-32-33,33>>^ Their wine is the venom of big snakes
And the cruel poison of cobras.

[[v5-32-34]]

^<<v5-32-34,34>>^ Is it not laid up with me,
With a seal affixed to it in my storehouse?^&#42;1^

[NOTE]
====
. Or, “among my supplies.”
====

[[v5-32-35]]

^<<v5-32-35,35>>^ Vengeance is mine, and retribution.
At the appointed time their foot will move unsteadily,
For the day of their disaster is near,
And the events in readiness for them do make haste.’

[[v5-32-36]]

^<<v5-32-36,36>>^ For Jehovah will judge his people
And he will feel regret over his servants,
Because he will see that support^&#42;1^ has disappeared
And there is only a helpless and worthless one.^&#42;2^

[NOTE]
====
. Lit., “hand.”
. Lit., “only one restrained and one let go (abandoned).” See VT, Vol. II, 1952, pp. 371-374.
====

[[v5-32-37]]

^<<v5-32-37,37>>^ And he will certainly say, ‘Where are their gods,^&#42;1^
The rock in whom they sought refuge,^&#42;2^

[NOTE]
====
. “Their gods.” MSam(Heb.), ʼelo·hehʹmoh, pl.; Gr., the·oiʹ; Lat., diʹi.
. “Where are their gods upon whom they put their trust?” LXX; Vg, “Where are their gods in whom they had confidence?”
====

[[v5-32-38]]

^<<v5-32-38,38>>^ Who used to eat the fat of their sacrifices,
To drink the wine of their drink offerings?
Let them get up and help YOU.
Let them become a concealment place for YOU.

[[v5-32-39]]

^<<v5-32-39,39>>^ SEE now that I—I am he^&#42;1^
And there are no gods together with me.
I put to death, and I make alive.^&#42;2^
I have severely wounded, and I—I will heal,
And there is no one snatching out of my hand.

[NOTE]
====
. Lit., “I​—⁠I [am] he.” Heb., ʼaniʹ ʼaniʹ huʼ. Compare Ex 3:14; App 6F.
. Or, “I preserve alive.”
====

[[v5-32-40]]

^<<v5-32-40,40>>^ For I raise my hand to heaven &#91;in an oath&#93;,
And I do say: “As I am alive to time indefinite,”^&#42;1^

[NOTE]
====
. Or, “alive forever.”
====

[[v5-32-41]]

^<<v5-32-41,41>>^ If I do indeed sharpen my glittering sword,^&#42;1^
And my hand takes hold on judgment,
I will pay back vengeance to my adversaries
And render retribution to those who intensely hate me.

[NOTE]
====
. Lit., “the lightning of my sword.”
====

[[v5-32-42]]

^<<v5-32-42,42>>^ I shall intoxicate my arrows with blood,
While my sword will eat flesh,
With the blood of the slain and the captives,^&#42;1^
With the heads of the leaders of the enemy.’^&#42;2^

[NOTE]
====
. Or, “captivity,” that is, a body of captives.
. Or, “the long-haired head of the enemy.”
====

[[v5-32-43]]

^<<v5-32-43,43>>^ Be glad, YOU nations, with his people,^&#42;1^
For he will avenge the blood of his servants,
And he will pay back vengeance to his adversaries
And will indeed make atonement for the ground of his people.”^&#42;2^

[NOTE]
====
. “Be glad, O heavens, together with him, and let all the angels of God worship him. Be glad, you nations, with his people, and let all the sons of God strengthen themselves in him,” LXXBagster. Compare Heb 1:6.
. “For the ground of his people,” SamLXXVg; M, “for his ground, for his people”; Sy, “for his ground and for his people.”
====

[[v5-32-44]]

^<<v5-32-44,44>>^ Thus Moses came and spoke all the words of this song in the hearing^&#42;1^ of the people, he and Ho·sheʹa^&#42;2^ the son of Nun.

[NOTE]
====
. Lit., “ears.”
. Meaning “Salvation; Deliverance”; the original name of Joshua.
====

[[v5-32-45]]

^<<v5-32-45,45>>^ After Moses finished speaking all these words to all Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ he went on to say to them: “Apply YOUR hearts to all the words that I am speaking in warning to YOU^&#42;1^ today, that YOU may command YOUR sons to take care to do all the words of this law.

[NOTE]
====
. Or, “in witness against you.”
====

[[v5-32-47]]

^<<v5-32-47,47>>^ For it is no valueless word for YOU, but it means YOUR life, and by this word YOU may lengthen YOUR days upon the soil to which YOU are crossing the Jordan to take possession of it.”

[[v5-32-48]]

^<<v5-32-48,48>>^ And Jehovah proceeded to speak to Moses on this same day, saying:

[[v5-32-49]]

^<<v5-32-49,49>>^ “Go up into this mountain of Abʹa·rim,^&#42;1^ Mount Neʹbo, which is in the land of Moʹab, which fronts toward Jerʹi·cho, and see the land of Caʹnaan, which I am giving to the sons of Israel as a possession.

[NOTE]
====
. Or, “the borderland.”
====

[[v5-32-50]]

^<<v5-32-50,50>>^ Then die on the mountain into which you are going up, and be gathered to your people, just as Aaron your brother died on Mount Hor and got to be gathered to his people;

[[v5-32-51]]

^<<v5-32-51,51>>^ for the reason that YOU men acted undutifully toward me in the middle of the sons of Israel at the waters of Merʹi·bah of Kaʹdesh in the wilderness of Zin; for the reason that YOU men did not sanctify me^&#42;1^ in the middle of the sons of Israel.

[NOTE]
====
. “You men did not sanctify me (hold me sacred; treat me as holy).” Heb., loʼ-qid·dash·temʹ ʼoh·thiʹ; Gr., he·gi·aʹsa·te; Lat., sanc·ti·fi·caʹstis.
====

[[v5-32-52]]

^<<v5-32-52,52>>^ For from a distance you will see the land, but you will not go there into the land that I am giving to the sons of Israel.”

'''

xref:005-deuteronomy/005-deuteronomy-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-033.adoc#v5-33-0[Próximo Capítulo &#62;]