include::./index.adoc[]

[[v5-15-0]]
=== Deuteronomy, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-15-1]]

^<<v5-15-1,1>>^ “At the end of every seven years you should make a release.

[[v5-15-2]]

^<<v5-15-2,2>>^ And this is the manner of the release: there will be a releasing^&#42;1^ by every creditor of the debt^&#42;2^ that he may let his fellow incur. He should not press his fellow or his brother for payment, because a release to Jehovah must be called.^&#42;3^

[NOTE]
====
. “There will be a releasing.” In Heb. this is a verb in the infinitive absolute, indefinite as to time.
. Lit., “every owner of a debt of his hand.”
. Lit., “one (he) must call.”
====

[[v5-15-3]]

^<<v5-15-3,3>>^ The foreigner you may press for payment; but whatever of yours may prove to be with your brother let your hand release.

[[v5-15-4]]

^<<v5-15-4,4>>^ However, no one should come to be poor among you, because Jehovah will without fail bless you in the land that Jehovah your God is giving you as an inheritance to take possession of it,

[[v5-15-5]]

^<<v5-15-5,5>>^ only if you will without fail listen to the voice of Jehovah your God so as to be careful to do all this commandment that I am commanding you today.

[[v5-15-6]]

^<<v5-15-6,6>>^ For Jehovah your God will indeed bless you just as he has promised you, and you will certainly lend on pledge to many nations, whereas you yourself will not borrow; and you must dominate over many nations, whereas over you they will not dominate.

[[v5-15-7]]

^<<v5-15-7,7>>^ “In case some one of your brothers becomes poor among you in one of your cities,^&#42;1^ in your land that Jehovah your God is giving you, you must not harden your heart or be closefisted toward your poor brother.

[NOTE]
====
. “Cities,” LXXSy; MSam, “gates”; Vg, “within the gates of your city.”
====

[[v5-15-8]]

^<<v5-15-8,8>>^ For you should generously open your hand to him and by all means lend him on pledge as much as he needs, which he is in want of.

[[v5-15-9]]

^<<v5-15-9,9>>^ Watch out for yourself for fear a base word^&#42;1^ should come to be in your heart, saying, ‘The seventh year, the year of the release,^&#42;2^ has come close,’ and your eye should indeed become ungenerous toward your poor brother, and you should give him nothing, and he has to call out to Jehovah against you, and it has become a sin on your part.

[NOTE]
====
. Or, “a word of belial (worthlessness).”
. “The year of the release.” Lat., anʹnus re·mis·si·oʹnis.
====

[[v5-15-10]]

^<<v5-15-10,10>>^ You should by all means give to him, and your heart should not be stingy in your giving to him, because on this account Jehovah your God will bless you in every deed of yours and in every undertaking of yours.

[[v5-15-11]]

^<<v5-15-11,11>>^ For someone poor will never cease to be in the midst of the land. That is why I am commanding you, saying, ‘You should generously open up your hand to your afflicted and poor brother^&#42;1^ in your land.’

[NOTE]
====
. Or, “to your brother, to your afflicted one and to your poor one.”
====

[[v5-15-12]]

^<<v5-15-12,12>>^ “In case there should be sold to you your brother, a Hebrew or a Hebrewess, and he has served you six years, then in the seventh year you should send him out from you as one set free.

[[v5-15-13]]

^<<v5-15-13,13>>^ And in case you should send him out from you as one set free, you must not send him out empty-handed.

[[v5-15-14]]

^<<v5-15-14,14>>^ You should surely equip him with something from your flock and your threshing floor and your oil and winepress. Just as Jehovah your God has blessed you, you should give to him.

[[v5-15-15]]

^<<v5-15-15,15>>^ And you must remember that you became a slave in the land of Egypt and Jehovah your God proceeded to redeem you. That is why I am commanding you this thing today.

[[v5-15-16]]

^<<v5-15-16,16>>^ “And it must occur that in case he says to you, ‘I shall not go out from your company!’ because he does love you and your household, since it was well with him while with you,

[[v5-15-17]]

^<<v5-15-17,17>>^ you must also take an awl and put it through his ear and to the door, and he must become your slave to time indefinite. And to your slave girl you should also do this way.

[[v5-15-18]]

^<<v5-15-18,18>>^ It should not be something hard in your eyes when you send him out from your company as one set free; because for double the value of a hired laborer he served you six years, and Jehovah your God has blessed you in everything that you would do.

[[v5-15-19]]

^<<v5-15-19,19>>^ “Every male firstborn that will be born in your herd and in your flock you should sanctify to Jehovah your God. You must do no service with the firstborn of your bull, nor shear the firstborn of your flock.

[[v5-15-20]]

^<<v5-15-20,20>>^ Before Jehovah your God you should eat it year by year in the place that Jehovah will choose, you and your household.

[[v5-15-21]]

^<<v5-15-21,21>>^ And in case there should prove to be in it a defect, being lame or blind, any bad defect, you must not sacrifice it to Jehovah your God.

[[v5-15-22]]

^<<v5-15-22,22>>^ Inside your gates you should eat it, the unclean one and the clean one together, like the gazelle and like the stag.

[[v5-15-23]]

^<<v5-15-23,23>>^ Only its blood you must not eat. Upon the earth you should pour it out as water.

'''

xref:005-deuteronomy/005-deuteronomy-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-016.adoc#v5-16-0[Próximo Capítulo &#62;]