include::./index.adoc[]

[[v5-12-0]]
=== Deuteronomy, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-12-1]]

^<<v5-12-1,1>>^ “These are the regulations and the judicial decisions that YOU should be careful to carry out in the land that Jehovah the God of your forefathers will certainly allow you to take possession of, all the days that YOU are alive on the soil.

[[v5-12-2]]

^<<v5-12-2,2>>^ YOU should absolutely destroy all the places where the nations whom YOU are dispossessing have served their gods, on the tall mountains and the hills and under every luxuriant tree.

[[v5-12-3]]

^<<v5-12-3,3>>^ And YOU must pull down their altars and shatter their sacred pillars, and YOU should burn their sacred poles^&#42;1^ in the fire and cut down the graven images of their gods, and YOU must destroy their names from that place.

[NOTE]
====
. Or, “their Asherim.”
====

[[v5-12-4]]

^<<v5-12-4,4>>^ “YOU must not do that way to Jehovah YOUR God,

[[v5-12-5]]

^<<v5-12-5,5>>^ but to the place that Jehovah YOUR God will choose out of all YOUR tribes to place his name there, to have it reside,^&#42;1^ YOU will seek, and there you must come.

[NOTE]
====
. Or, “there, to his residence.”
====

[[v5-12-6]]

^<<v5-12-6,6>>^ And there YOU must bring YOUR burnt offerings and YOUR sacrifices and YOUR tenth parts^&#42;1^ and the contribution of YOUR hand and YOUR vow offerings and YOUR voluntary offerings and the firstborn ones of YOUR herd and of YOUR flock.

[NOTE]
====
. Or, “your tithes.”
====

[[v5-12-7]]

^<<v5-12-7,7>>^ And there YOU must eat before Jehovah YOUR God and rejoice in every undertaking of YOURS,^&#42;1^ YOU and YOUR households, because Jehovah your God has blessed you.

[NOTE]
====
. Or, “in all the gain of your hand.”
====

[[v5-12-8]]

^<<v5-12-8,8>>^ “YOU must not do according to all that we are doing here today, each one whatever is right in his own eyes,

[[v5-12-9]]

^<<v5-12-9,9>>^ because YOU have not yet come into the resting-place and the inheritance that Jehovah your God is giving you.

[[v5-12-10]]

^<<v5-12-10,10>>^ And YOU must cross the Jordan and dwell in the land that Jehovah YOUR God is giving YOU as a possession, and he will certainly give YOU rest from all YOUR enemies round about, and YOU will indeed dwell in security.

[[v5-12-11]]

^<<v5-12-11,11>>^ And it must occur that the place that Jehovah YOUR God will choose to have his name reside there is where YOU will bring all about which I am commanding YOU, YOUR burnt offerings and YOUR sacrifices, YOUR tenth parts and the contribution of YOUR hand and every choice of YOUR vow offerings that YOU will vow to Jehovah.

[[v5-12-12]]

^<<v5-12-12,12>>^ And YOU must rejoice before Jehovah YOUR God, YOU and YOUR sons and YOUR daughters and YOUR man slaves and YOUR slave girls and the Levite who is inside YOUR gates,^&#42;1^ because he has no share or inheritance with YOU.

[NOTE]
====
. “Gates,” MSamLXX; SyVg, “cities.”
====

[[v5-12-13]]

^<<v5-12-13,13>>^ Watch out for yourself for fear you may offer up your burnt offerings in any other place you may see.

[[v5-12-14]]

^<<v5-12-14,14>>^ But in the place that Jehovah will choose in one of your tribes is where you should offer up your burnt offerings, and there you should do all that I am commanding you.

[[v5-12-15]]

^<<v5-12-15,15>>^ “Only whenever your soul craves it you may slaughter, and you must eat meat according to the blessing of Jehovah your God that he has given you, inside all your gates.^&#42;1^ The unclean one and the clean one may eat it, like the gazelle and like the stag.

[NOTE]
====
. “All your gates,” MSam; LXX, “every city”; SyVg, “(all) your cities.”
====

[[v5-12-16]]

^<<v5-12-16,16>>^ Only the blood YOU must not eat. On the earth you should pour it out as water.

[[v5-12-17]]

^<<v5-12-17,17>>^ You will not be allowed to eat inside your gates the tenth part of your grain or of your new wine or of your oil or the firstborn ones of your herd and of your flock or any of your vow offerings that you will vow or your voluntary offerings or the contribution of your hand.

[[v5-12-18]]

^<<v5-12-18,18>>^ But before Jehovah your God you will eat it, in the place that Jehovah your God will choose, you and your son and your daughter and your man slave and your slave girl and the Levite who is inside your gates; and you must rejoice before Jehovah your God in every undertaking of yours.

[[v5-12-19]]

^<<v5-12-19,19>>^ Watch out for yourself that you may not abandon the Levite all your days on your soil.

[[v5-12-20]]

^<<v5-12-20,20>>^ “When Jehovah your God will widen out your territory,^&#42;1^ just as he has promised you, and you will be certain to say, ‘Let me eat meat,’ because your soul craves to eat meat, whenever your soul craves it you may eat meat.

[NOTE]
====
. Or, “boundary.”
====

[[v5-12-21]]

^<<v5-12-21,21>>^ In case the place that Jehovah your God will choose to put his name there should be far away from you, you must then slaughter some of your herd or some of your flock that Jehovah has given you, just as I have commanded you, and you must eat inside your gates whenever your soul craves it.

[[v5-12-22]]

^<<v5-12-22,22>>^ Only in the way that the gazelle and the stag may be eaten, so you may eat it: the unclean one and the clean one together may eat it.

[[v5-12-23]]

^<<v5-12-23,23>>^ Simply be firmly resolved not to eat the blood, because the blood is the soul and you must not eat the soul with the flesh.^&#42;1^

[NOTE]
====
. Or, “meat.”
====

[[v5-12-24]]

^<<v5-12-24,24>>^ You must not eat it. You should pour it out upon the ground as water.

[[v5-12-25]]

^<<v5-12-25,25>>^ You must not eat it, in order that it may go well with you and your sons after you, because you will do what is right in Jehovah’s eyes.

[[v5-12-26]]

^<<v5-12-26,26>>^ Merely your holy things that will become yours, and your vow offerings you should carry, and you must come to the place that Jehovah will choose.

[[v5-12-27]]

^<<v5-12-27,27>>^ And you must render up your burnt offerings, the flesh and the blood, upon the altar of Jehovah your God; and the blood of your sacrifices should be poured out against the altar of Jehovah your God, but the flesh you may eat.

[[v5-12-28]]

^<<v5-12-28,28>>^ “Watch, and you must obey all these words that I am commanding you, in order that it may go well with you and your sons after you to time indefinite, because you will do what is good and right in the eyes of Jehovah your God.

[[v5-12-29]]

^<<v5-12-29,29>>^ “When Jehovah your God will cut off from before you the nations to whom you are going to dispossess them, you must also dispossess them and dwell in their land.

[[v5-12-30]]

^<<v5-12-30,30>>^ Watch out for yourself for fear you may be entrapped after them, after they have been annihilated from before you, and for fear you may inquire respecting their gods, saying, ‘How was it these nations used to serve^&#42;1^ their gods? And I, yes, I, will do the same way.’

[NOTE]
====
. Or, “worship.” See 4:19 ftn.
====

[[v5-12-31]]

^<<v5-12-31,31>>^ You must not do that way to Jehovah your God, for everything detestable to Jehovah that he does hate they have done to their gods, for even their sons and their daughters they regularly burn in the fire to their gods.^&#42;1^

[NOTE]
====
. MLXX end chapter 12 here.
====

[[v5-12-32]]

^<<v5-12-32,32>>^ Every word that I am commanding YOU is what YOU should be careful to do. YOU must not add to it nor take away from it.

'''

xref:005-deuteronomy/005-deuteronomy-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-013.adoc#v5-13-0[Próximo Capítulo &#62;]