include::./index.adoc[]

[[v5-33-0]]
=== Deuteronomy, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-33-1]]

^<<v5-33-1,1>>^ Now this is the blessing with which Moses the man of the &#91;true&#93; God blessed the sons of Israel before his death.

[[v5-33-2]]

^<<v5-33-2,2>>^ And he proceeded to say:
“Jehovah—from Siʹnai he came,
And he flashed forth from Seʹir upon them.
He beamed forth from the mountainous region of Paʹran,
And with him were holy myriads,^&#42;1^
At his right hand warriors belonging to them.^&#42;2^

[NOTE]
====
. Or, “tens of thousands of holy ones.”
. Or, “and with him were myriads of Kadesh, at his right hand warriors [or, angels] thereof.” See JTS, Vol. 2, 1951, pp. 30, 31. LXX, “with [the] myriads of Kadesh; at his right hand angels [were] with him”; Vg, “and with him thousands of holy ones. In his right hand [there was] a fiery law.” Mmargin breaks the Heb. into two words, ʼesh (fire) and dath (law), to read, “the fire of a law”; or, “a fiery law.” But this would introduce into the Pentateuch a Persian loanword, dath (law), which is found elsewhere in Heb. only in Ezra and Esther. See Ezr 8:36; Es 1:8.
====

[[v5-33-3]]

^<<v5-33-3,3>>^ He was also cherishing his people;^&#42;1^
All their^&#42;2^ holy ones are in your hand.
And they—they reclined at your feet;^&#42;3^
They began to receive some of your words.

[NOTE]
====
. “His people,” LXX; MSamSyVg, “peoples,” referring to the Israelite tribes or their ancestors.
. Possibly, “his,” in the collective sense, referring to “his people,” which is pl. in M (Heb., ʽam·mimʹ).
. Possibly, “And they​—⁠they followed at your feet.” The meaning of the Heb. verb is uncertain. LXX, “And these are under you”; Vg, “And they who approach his feet.”
====

[[v5-33-4]]

^<<v5-33-4,4>>^ (Moses laid as a command upon us a law,^&#42;1^
A possession of the congregation of Jacob.)

[NOTE]
====
. “Moses laid as a command upon us a law.” Some consider these words to be a gloss from the margin and so would delete them.
====

[[v5-33-5]]

^<<v5-33-5,5>>^ And he came to be king in Jeshʹu·run,^&#42;1^
When the heads of the people gathered themselves,
The entire number of the tribes of Israel.

[NOTE]
====
. Meaning “Upright One”; an honorary title for Israel.
====

[[v5-33-6]]

^<<v5-33-6,6>>^ Let Reuʹben live and not die off,
And let his men &#91;not&#93; become few.”^&#42;1^

[NOTE]
====
. “And let his number become complete (perfect),” by a correction proposed in BHK and BHS; LXX, “and let him be great in number”; Vg, “and let him be small in number.”
====

[[v5-33-7]]

^<<v5-33-7,7>>^ And this was Judah’s &#91;blessing&#93;,^&#42;1^ as he went on to say:
“Hear, O Jehovah, the voice of Judah,
And may you bring him to his people.
His arms have contended for what is his;^&#42;2^
And may you prove yourself a helper from his adversaries.”

[NOTE]
====
. “Blessing.” Inserted for sense in agreement with vs 1.
. Or, “contended for him.”
====

[[v5-33-8]]

^<<v5-33-8,8>>^ And as to Leʹvi he said:
“Your Thumʹmim^&#42;1^ and your Uʹrim belong to the man loyal to you,^&#42;2^
Whom you put to the test at Masʹsah.
You began to contend with him by the waters of Merʹi·bah,

[NOTE]
====
. See Ex 28:30 ftn, “Thummim.”
. Possibly, “your man of loyal love.”
====

[[v5-33-9]]

^<<v5-33-9,9>>^ The man who said to his father and his mother, ‘I have not seen him.’
Even his brothers he did not acknowledge,
And his sons he did not know.
For they kept your saying,
And your covenant they continued to observe.

[[v5-33-10]]

^<<v5-33-10,10>>^ Let them instruct Jacob in your judicial decisions
And Israel in your law.
Let them render up incense before your nostrils
And a whole offering on your altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Bless, O Jehovah, his vital energy,
And may you show pleasure in the activity of his hands.
Wound severely in their hips those who rise up against him,
And those who intensely hate him, that they may not rise up.”

[[v5-33-12]]

^<<v5-33-12,12>>^ As to Benjamin he said:
“Let the beloved one of Jehovah reside in security by him,
While he shelters him the whole day,
And he must reside between his shoulders.”

[[v5-33-13]]

^<<v5-33-13,13>>^ And as to Joseph he said:
“May his land be continually blessed from Jehovah
With the choice things of heaven, with dew,^&#42;1^
And with the watery deep lying down below,

[NOTE]
====
. “Of heaven above,” two Heb. mss. In TO this line reads: “with dew of heaven from above.” See Ge 49:25.
====

[[v5-33-14]]

^<<v5-33-14,14>>^ And with the choice things, the products of the sun,
And with the choice things, the yield of the lunar months,

[[v5-33-15]]

^<<v5-33-15,15>>^ And with the choicest from the mountains of the east,
And with the choice things of the indefinitely lasting hills,

[[v5-33-16]]

^<<v5-33-16,16>>^ And with the choice things of the earth and its fullness,
And with the approval of the One residing in the thornbush.
May they come upon the head of Joseph
And upon the crown of the head of the one singled out^&#42;1^ from his brothers.

[NOTE]
====
. “One singled out.” MSam(Heb.), nezirʹ, translated “Naz­irite” (meaning “One Singled Out; Dedicated One; Separated One”) in Nu 6:2, 13, 18-20.
====

[[v5-33-17]]

^<<v5-33-17,17>>^ As the firstborn of a bull his splendor is,
And his horns are the horns of a wild bull.^&#42;1^
With them he will push peoples
All together to the ends of the earth,
And they are the tens of thousands of Eʹphra·im,
And they are the thousands of Ma·nasʹseh.”

[NOTE]
====
. Or, “a buffalo.”
====

[[v5-33-18]]

^<<v5-33-18,18>>^ And as to Zebʹu·lun he said:
“Rejoice, O Zebʹu·lun, in your going out,
And, Isʹsa·char, in your tents.

[[v5-33-19]]

^<<v5-33-19,19>>^ Peoples to the mountain they will call.
There they will sacrifice the sacrifices of righteousness.
For they will suck the abounding wealth of the seas
And the hidden hoards of the sand.”^&#42;1^

[NOTE]
====
. “And the hidden treasures of the sands,” Vg; LXX, “and the commerce of the inhabitants of the seacoast.”
====

[[v5-33-20]]

^<<v5-33-20,20>>^ And as to Gad he said:
“Blessed is the one widening the borders of Gad.
As a lion^&#42;1^ he must reside,
And he must tear the arm, yes, the crown of the head.

[NOTE]
====
. “As a lion.” Heb., kela·viʼʹ, the Asian lion.
====

[[v5-33-21]]

^<<v5-33-21,21>>^ And he will pick out the first part for himself,^&#42;1^
For there the allotment of a statute-giver is reserved.
And the heads of the people will gather themselves together.^&#42;2^
The righteousness of Jehovah will he certainly execute
And his judicial decisions with Israel.”

[NOTE]
====
. Lit., “And he will see the first part is his.” Vg, “And he saw the first place (preeminence) to be his.”
. Lit., “for there was the allotment (share) of a commander [his prescribed allotment, by an emendation] covered in. And he proceeded to come [with] the heads of the people,” M; Vg, “for in his part the teacher was laid up (reserved) . . . .”
====

[[v5-33-22]]

^<<v5-33-22,22>>^ And as to Dan he said:
“Dan is a lion cub.
He will leap out from Baʹshan.”

[[v5-33-23]]

^<<v5-33-23,23>>^ And as to Naphʹta·li he said:
“Naphʹta·li is satisfied with the approval
And full of the blessing of Jehovah.
Do take possession of the west and south.”^&#42;1^

[NOTE]
====
. Possibly, “The sea and its fish are his possession.” LXXSyVg, “The sea (west) and the south he will inherit (take possession of).”
====

[[v5-33-24]]

^<<v5-33-24,24>>^ And as to Ashʹer he said:
“Blessed with sons is Ashʹer.
Let him become one approved by his brothers,
And one dipping his foot in oil.

[[v5-33-25]]

^<<v5-33-25,25>>^ Iron and copper are your gate locks,
And in proportion to your days is your leisurely walk.^&#42;1^

[NOTE]
====
. “Leisurely walk.” Or, “gait.” According to KB3, p. 199, “strength.”
====

[[v5-33-26]]

^<<v5-33-26,26>>^ There is none like the &#91;true&#93; God^&#42;1^ of Jeshʹu·run,
Who rides upon heaven in help of you
And upon cloudy skies in his eminence.^&#42;2^

[NOTE]
====
. “Like the [true] God of.” Heb., ka·ʼElʹ. Here the definite article ha, “the,” is indicated by the vowel points under the Heb. preposition Kaph, “k,” to form ka, “like the.” This introduction gives special emphasis to the noun “God,” here rendered “the [true] God.” See Heb. grammars under “prep­ositions”; App 1G.
. “And the magnificent one of the firmament,” LXX; Vg, “by his magnificence the clouds run to and fro.”
====

[[v5-33-27]]

^<<v5-33-27,27>>^ A hiding place is the God of ancient time,
And underneath are the indefinitely lasting arms.
And he will drive away from before you the enemy,
And he will say, ‘Annihilate &#91;them&#93;!’

[[v5-33-28]]

^<<v5-33-28,28>>^ And Israel will reside in security,
The fountain of Jacob by itself,
Upon^&#42;1^ a land of grain and new wine.
Yes, his heavens will let the dew drip down.

[NOTE]
====
. “Upon,” Sam; M, “to (for).”
====

[[v5-33-29]]

^<<v5-33-29,29>>^ Happy you are, O Israel!
Who is there like you,
A people enjoying salvation in Jehovah,
The shield of your help,
And the One who is your eminent sword?
So your enemies will cringe before you,^&#42;1^
And you—upon their high places you will tread.”^&#42;2^

[NOTE]
====
. Or, “will pretend to be obedient to you.”
. The tribe of Simeon is not named in the blessing upon all Israel, but with Levi named and also the tribes of Ephraim and Manasseh that descended from Joseph, the number of tribes remains 12.
====

'''

xref:005-deuteronomy/005-deuteronomy-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-034.adoc#v5-34-0[Próximo Capítulo &#62;]