include::./index.adoc[]

[[v5-10-0]]
=== Deuteronomy, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-10-1]]

^<<v5-10-1,1>>^ “At that particular time Jehovah said to me, ‘Carve for yourself two tablets of stone like the first ones, and come up to me into the mountain, and you must make an ark of wood for yourself.

[[v5-10-2]]

^<<v5-10-2,2>>^ And I shall write upon the tablets the words that appeared on the first tablets, which you shattered, and you must place them in the ark.’

[[v5-10-3]]

^<<v5-10-3,3>>^ So I made an ark of acacia wood and carved two tablets of stone like the first ones and went up into the mountain, and the two tablets were in my hand.

[[v5-10-4]]

^<<v5-10-4,4>>^ Then he wrote upon the tablets the same writing as the first, the Ten Words,^&#42;1^ which Jehovah had spoken to YOU in the mountain out of the middle of the fire in the day of the congregation; after which Jehovah gave them to me.

[NOTE]
====
. “The Ten Words,” that is, words of command, commandments. Heb., ʽaseʹreth had·deva·rimʹ; Gr., deʹka loʹgous, “Decalogue”; Lat., verʹba deʹcem. See 4:13 ftn; Ex 34:28 ftn, “Words.”
====

[[v5-10-5]]

^<<v5-10-5,5>>^ Then I turned and went down from the mountain and placed the tablets in the ark that I had made, that they might continue there, just as Jehovah had commanded me.

[[v5-10-6]]

^<<v5-10-6,6>>^ “And the sons of Israel pulled away from Be·erʹoth Benʹe-jaʹa·kan for Mo·seʹrah. There Aaron died, and he got to be buried there; and El·e·aʹzar his son began to act as priest instead of him.

[[v5-10-7]]

^<<v5-10-7,7>>^ From there they pulled away for Gudʹgo·dah, and from Gudʹgo·dah for Jotʹba·thah, a land of torrent valleys running with water.

[[v5-10-8]]

^<<v5-10-8,8>>^ “At that particular time Jehovah separated the tribe of Leʹvi to carry the ark of Jehovah’s covenant, to stand before Jehovah for ministering to him and to bless in his name until this day.

[[v5-10-9]]

^<<v5-10-9,9>>^ That is why Leʹvi has come to have no share and inheritance with his brothers. Jehovah is his inheritance, just as Jehovah your God had said to him.

[[v5-10-10]]

^<<v5-10-10,10>>^ And I—I stayed^&#42;1^ in the mountain the same as the first days, forty days and forty nights, and Jehovah proceeded to listen to me also on that occasion. Jehovah did not want to bring you to ruin.

[NOTE]
====
. Lit., “stood.” Compare Ex 9:16 ftn, “Existence.”
====

[[v5-10-11]]

^<<v5-10-11,11>>^ Then Jehovah said to me, ‘Get up, go before the people for a pulling away, that they may go in and take possession of the land that I have sworn to their forefathers to give to them.’

[[v5-10-12]]

^<<v5-10-12,12>>^ “And now, O Israel, what is Jehovah your God asking of you but to fear Jehovah your God, so as to walk in all his ways and to love him and to serve Jehovah your God with all your heart and all your soul;

[[v5-10-13]]

^<<v5-10-13,13>>^ to keep the commandments of Jehovah and his statutes that I am commanding you today, for your good?

[[v5-10-14]]

^<<v5-10-14,14>>^ Behold, to Jehovah your God belong the heavens, even the heavens of the heavens, the earth and all that is in it.

[[v5-10-15]]

^<<v5-10-15,15>>^ Only to your forefathers did Jehovah get attached so as to love them, so that he chose their offspring after them, even YOU, out of all the peoples, as at this day.

[[v5-10-16]]

^<<v5-10-16,16>>^ And YOU must circumcise the foreskin of YOUR hearts and not harden^&#42;1^ YOUR necks any longer.

[NOTE]
====
. Or, “stiffen.”
====

[[v5-10-17]]

^<<v5-10-17,17>>^ For Jehovah YOUR God is the God of gods^&#42;1^ and the Lord of lords,^&#42;2^ the God^&#42;3^ great, mighty and fear-inspiring, who treats none with partiality nor accepts a bribe,^&#42;4^

[NOTE]
====
. “The God of gods.” Or, “God of the gods.” MSam(Heb.), ʼElo·hehʹ ha·ʼelo·himʹ; Gr., The·osʹ ton the·onʹ; Lat., Deʹus de·oʹrum.
. “And the Lord of lords.” Or, “and Lord of the lords.” Heb., wa·ʼAdho·nehʹ (pl. to denote excellence) ha·ʼadho·nimʹ; Gr., Kyʹri·os ton ky·riʹon; Lat., Doʹmi·nus do·mi·nanʹti·um, “Lord of dominating ones.”
. “The God.” MSam(Heb.), ha·ʼElʹ; Gr., ho The·osʹ; Lat., Deʹus. See App 1G.
. Or, “gift.”
====

[[v5-10-18]]

^<<v5-10-18,18>>^ executing judgment for the fatherless boy and the widow and loving the alien resident so as to give him bread and a mantle.

[[v5-10-19]]

^<<v5-10-19,19>>^ YOU too must love the alien resident, for YOU became alien residents in the land of Egypt.

[[v5-10-20]]

^<<v5-10-20,20>>^ “Jehovah your God you should fear. Him you should serve, and to him you should cling, and by his name you should make sworn statements.

[[v5-10-21]]

^<<v5-10-21,21>>^ He is the One for you to praise,^&#42;1^ and he is your God, who has done with you these great and fear-inspiring things that your eyes have seen.

[NOTE]
====
. Lit., “He is your praise.”
====

[[v5-10-22]]

^<<v5-10-22,22>>^ With seventy souls your forefathers went down into Egypt, and now Jehovah your God has constituted you like the stars of the heavens for multitude.

'''

xref:005-deuteronomy/005-deuteronomy-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-011.adoc#v5-11-0[Próximo Capítulo &#62;]