include::./index.adoc[]

[[v5-22-0]]
=== Deuteronomy, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-22-1]]

^<<v5-22-1,1>>^ “You must not see the bull of your brother or his sheep straying about and deliberately withdraw^&#42;1^ from them. You should by all means lead them back to your brother.

[NOTE]
====
. Or, “hide yourself.”
====

[[v5-22-2]]

^<<v5-22-2,2>>^ And if your brother is not near you and you have not got to know him, you must also bring it home into the midst of your house, and it must continue with you until your brother has searched for it. And you must return it to him.

[[v5-22-3]]

^<<v5-22-3,3>>^ That is the way too that you will do with his ass, and that is the way you will do with his mantle, and that is the way you will do with anything lost of your brother’s, which gets lost from him and which you have found. You will not be allowed to withdraw yourself.

[[v5-22-4]]

^<<v5-22-4,4>>^ “You must not see the ass of your brother or his bull fall down on the road and deliberately withdraw from them. You should by all means help him raise them up.

[[v5-22-5]]

^<<v5-22-5,5>>^ “No garb of an able-bodied man should be put upon a woman, neither should an able-bodied man wear the mantle of a woman; for anybody doing these things is something detestable to Jehovah your God.

[[v5-22-6]]

^<<v5-22-6,6>>^ “In case a bird’s nest happens to be before you in the way, in any tree or on the earth with young ones or eggs, and the mother is sitting upon the young ones or the eggs, you must not take the mother along with the offspring.

[[v5-22-7]]

^<<v5-22-7,7>>^ You should by all means send the mother away, but you may take the offspring for yourself; in order that it may go well with you, and you may indeed lengthen your days.

[[v5-22-8]]

^<<v5-22-8,8>>^ “In case you build a new house, you must also make a parapet for your roof, that you may not place bloodguilt upon your house because someone falling might fall from it.

[[v5-22-9]]

^<<v5-22-9,9>>^ “You must not sow your vineyard with two sorts of seed, for fear that the full produce of the seed that you might sow and the product of the vineyard may be forfeited to the sanctuary.^&#42;1^

[NOTE]
====
. “May be forfeited to the sanctuary.” Lit., “may be holy,” that is, fall to the sanctuary’s share. Heb., tiq·dashʹ.
====

[[v5-22-10]]

^<<v5-22-10,10>>^ “You must not plow with a bull and an ass together.

[[v5-22-11]]

^<<v5-22-11,11>>^ “You must not wear mixed stuff of wool and linen together.

[[v5-22-12]]

^<<v5-22-12,12>>^ “You should make tassels for yourself on the four extremities of your clothing with which you cover yourself.

[[v5-22-13]]

^<<v5-22-13,13>>^ “In case a man takes a wife and actually has relations with her and has come to hate her,

[[v5-22-14]]

^<<v5-22-14,14>>^ and he has charged her with notorious deeds and brought forth a bad name upon her and has said, ‘This is the woman I have taken, and I proceeded to go near her, and I did not find evidence of virginity in her’;

[[v5-22-15]]

^<<v5-22-15,15>>^ the father of the girl and her mother must also take and bring forth the evidence of the girl’s virginity to the older men of the city at the gate of it;

[[v5-22-16]]

^<<v5-22-16,16>>^ and the girl’s father must say to the older men, ‘I gave my daughter to this man as a wife, and he went hating^&#42;1^ her.

[NOTE]
====
. Or, “disdaining.”
====

[[v5-22-17]]

^<<v5-22-17,17>>^ And here he is charging her with notorious deeds, saying: “I have found your daughter does not have evidence of virginity.” Now this is the evidence of my daughter’s virginity.’ And they must spread out the mantle before the older men of the city.

[[v5-22-18]]

^<<v5-22-18,18>>^ And the older men of that city must take the man and discipline him.

[[v5-22-19]]

^<<v5-22-19,19>>^ And they must fine him a hundred silver shekels^&#42;1^ and give them to the girl’s father, because he brought forth a bad name upon a virgin of Israel; and she will continue to be his wife. He will not be allowed to divorce^&#42;2^ her all his days.

[NOTE]
====
. “Silver shekels,” Vg; MSam, “silver pieces”; LXX, “shekels.” To calculate value, see App 8A.
. Lit., “send away.”
====

[[v5-22-20]]

^<<v5-22-20,20>>^ “If, though, this thing has proved to be the truth, evidence of virginity was not found in the girl,

[[v5-22-21]]

^<<v5-22-21,21>>^ they must also bring the girl out to the entrance of her father’s house, and the men of her city must pelt her with stones, and she must die, because she has committed a disgraceful folly in Israel by committing prostitution in the house of her father. So you must clear away what is bad from your midst.

[[v5-22-22]]

^<<v5-22-22,22>>^ “In case a man is found lying down with a woman owned^&#42;1^ by an owner, both of them must then die together, the man lying down with the woman and the woman. So you must clear away what is bad out of Israel.

[NOTE]
====
. “Owned,” that is, as a wife.
====

[[v5-22-23]]

^<<v5-22-23,23>>^ “In case there happened to be a virgin girl engaged to a man, and a man actually found her in the city and lay down with her,

[[v5-22-24]]

^<<v5-22-24,24>>^ YOU must also bring them both out to the gate of that city and pelt them with stones, and they must die, the girl for the reason that she did not scream in the city, and the man for the reason that he humiliated the wife of his fellowman. So you must clear away what is evil from your midst.

[[v5-22-25]]

^<<v5-22-25,25>>^ “If, however, it is in the field that the man found the girl who was engaged, and the man grabbed hold of her and lay down with her, the man who lay down with her must also die by himself,

[[v5-22-26]]

^<<v5-22-26,26>>^ and to the girl you must do nothing. The girl has no sin deserving of death, because just as when a man rises up against his fellowman and indeed murders him, even a soul, so it is with this case.

[[v5-22-27]]

^<<v5-22-27,27>>^ For it was in the field that he found her. The girl who was engaged screamed, but there was no one to rescue her.

[[v5-22-28]]

^<<v5-22-28,28>>^ “In case a man finds a girl, a virgin who has not been engaged, and he actually seizes her and lies down with her, and they have been found out,

[[v5-22-29]]

^<<v5-22-29,29>>^ the man who lay down with her must also give the girl’s father fifty silver shekels,^&#42;1^ and she will become his wife due to the fact that he humiliated her. He will not be allowed to divorce her all his days.^&#42;2^

[NOTE]
====
. “Silver shekels,” Vg; M, “silver pieces”; LXX, “silver didrachmas.”
. MSamLXX end chapter 22 here.
====

[[v5-22-30]]

^<<v5-22-30,30>>^ “No man should take his father’s wife, that he may not uncover the skirt of his father.^&#42;1^

[NOTE]
====
. Or, “not lie with his father’s wife.”
====

'''

xref:005-deuteronomy/005-deuteronomy-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-023.adoc#v5-23-0[Próximo Capítulo &#62;]