include::./index.adoc[]

[[v5-11-0]]
=== Deuteronomy, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-11-1]]

^<<v5-11-1,1>>^ “And you must love Jehovah your God and keep your obligation to him and his statutes and his judicial decisions and his commandments always.

[[v5-11-2]]

^<<v5-11-2,2>>^ And YOU well know today (for &#91;I do&#93; not &#91;address&#93; YOUR sons who have not known and who have not seen the discipline of Jehovah YOUR God, his greatness, his strong hand and his outstretched arm,

[[v5-11-3]]

^<<v5-11-3,3>>^ nor his signs and his deeds that he did in the midst of Egypt to Pharʹaoh the king of Egypt and to all his land;

[[v5-11-4]]

^<<v5-11-4,4>>^ nor what he did to the military forces of Egypt, to his horses and his war chariots against the faces of which he made the waters of the Red Sea overflow when they were chasing after them, and Jehovah proceeded to destroy them till this day;

[[v5-11-5]]

^<<v5-11-5,5>>^ nor what he has done to YOU in the wilderness until YOUR coming to this place;

[[v5-11-6]]

^<<v5-11-6,6>>^ nor what he did to Daʹthan and A·biʹram the sons of E·liʹab the son of Reuʹben, when the earth opened its mouth and proceeded to swallow them up and their households and their tents and every existing thing that stepped after them in the midst of all Israel);

[[v5-11-7]]

^<<v5-11-7,7>>^ for YOUR eyes were the ones seeing all the great deeds of Jehovah that he did.

[[v5-11-8]]

^<<v5-11-8,8>>^ “And YOU must keep the whole commandment that I am commanding you today, in order that YOU may grow strong and may indeed enter in and take possession of the land to which YOU are crossing to take possession of it,

[[v5-11-9]]

^<<v5-11-9,9>>^ and in order that YOU may lengthen YOUR days on the soil that Jehovah swore to YOUR forefathers to give to them and their seed, a land flowing with milk and honey.

[[v5-11-10]]

^<<v5-11-10,10>>^ “For the land to which you are going to take possession of it is not like the land of Egypt out of which YOU came, where you used to sow your seed and you had to do irrigating with your foot,^&#42;1^ like a garden of vegetables.

[NOTE]
====
. Or, “had to water it with your foot,” that is, by some form of foot power, whether on a waterwheel or by forming and opening water channels.
====

[[v5-11-11]]

^<<v5-11-11,11>>^ But the land to which YOU are crossing to take possession of it is a land of mountains and valley plains. Of the rain of the heavens it drinks water;

[[v5-11-12]]

^<<v5-11-12,12>>^ a land that Jehovah your God is caring for. The eyes of Jehovah your God are constantly upon it, from the beginning of the year to the close of the year.

[[v5-11-13]]

^<<v5-11-13,13>>^ “And it must occur that if YOU will without fail obey my commandments that I am commanding YOU today so as to love Jehovah YOUR God and to serve him with all YOUR heart and all YOUR soul,

[[v5-11-14]]

^<<v5-11-14,14>>^ I^&#42;1^ also shall certainly give rain for YOUR land at its appointed time, autumn rain and spring rain,^&#42;2^ and you will indeed gather your grain and your sweet wine and your oil.

[NOTE]
====
. “I,” MSy; SamLXXVgc, “he.”
. Lit., “early (former) rain and latter rain.”
====

[[v5-11-15]]

^<<v5-11-15,15>>^ And I shall certainly give vegetation in your field for your domestic animals, and you will indeed eat and be satisfied.

[[v5-11-16]]

^<<v5-11-16,16>>^ Watch out for yourselves for fear YOUR heart may be enticed, and YOU do turn aside and worship other gods and bow down to them,

[[v5-11-17]]

^<<v5-11-17,17>>^ and Jehovah’s anger does blaze against YOU, and he does shut up the heavens so that no rain will occur and the ground will not give its produce and YOU have to perish speedily from off the good land that Jehovah is giving YOU.

[[v5-11-18]]

^<<v5-11-18,18>>^ “And YOU must apply these words of mine to YOUR heart and YOUR soul and bind them as a sign upon YOUR hand, and they must serve as a frontlet band between YOUR eyes.

[[v5-11-19]]

^<<v5-11-19,19>>^ YOU must also teach them to YOUR sons, so as to speak of them when you sit in your house and when you walk on the road and when you lie down and when you get up.

[[v5-11-20]]

^<<v5-11-20,20>>^ And you must write them upon the doorposts of your house and on your gates,

[[v5-11-21]]

^<<v5-11-21,21>>^ in order that YOUR days and the days of YOUR sons may be many on the soil that Jehovah swore to YOUR forefathers to give to them, as the days of the heavens over the earth.

[[v5-11-22]]

^<<v5-11-22,22>>^ “For if YOU strictly keep all this commandment that I am commanding YOU so as to do it, to love Jehovah YOUR God, to walk in all his ways and to cling to him,

[[v5-11-23]]

^<<v5-11-23,23>>^ Jehovah also must drive away all these nations on account of YOU, and YOU will certainly dispossess nations greater and more numerous than YOU are.

[[v5-11-24]]

^<<v5-11-24,24>>^ Every place on which the sole of YOUR foot will tread will become YOURS. From the wilderness up to^&#42;1^ Lebʹa·non, from the River, the river Eu·phraʹtes, to the western^&#42;2^ sea YOUR boundary will become.

[NOTE]
====
. “Up to.” Lit., “and,” MSamLXXSyVg.
. Lit., “hinder,” that is, to one’s back when facing east.
====

[[v5-11-25]]

^<<v5-11-25,25>>^ No man will make a firm stand against YOU. The dread of YOU and the fear of YOU Jehovah YOUR God will put before the face of all the land on which YOU will tread, just as he has promised YOU.

[[v5-11-26]]

^<<v5-11-26,26>>^ “See, I am putting before YOU today blessing and malediction:

[[v5-11-27]]

^<<v5-11-27,27>>^ the blessing, provided YOU will obey the commandments of Jehovah YOUR God that I am commanding YOU today;

[[v5-11-28]]

^<<v5-11-28,28>>^ and the malediction, if YOU will not obey the commandments of Jehovah YOUR God and YOU do turn aside from the way about which I am commanding YOU today, so as to walk after other gods whom YOU have not known.

[[v5-11-29]]

^<<v5-11-29,29>>^ “And it must occur that when Jehovah your God brings you into the land to which you are going to take possession of it, you must also give^&#42;1^ the blessing upon Mount Gerʹi·zim and the malediction upon Mount Eʹbal.

[NOTE]
====
. Or, “pronounce.”
====

[[v5-11-30]]

^<<v5-11-30,30>>^ Are they not on the side of the Jordan toward the direction of the sunset, in the land of the Caʹnaan·ites dwelling in the Arʹa·bah, in front of Gilʹgal, beside the big trees of Moʹreh?^&#42;1^

[NOTE]
====
. Sam adds, “in front of Shechem.”
====

[[v5-11-31]]

^<<v5-11-31,31>>^ For YOU are crossing the Jordan to go in and take possession of the land that Jehovah YOUR God is giving YOU, and YOU must take possession of it and dwell in it.

[[v5-11-32]]

^<<v5-11-32,32>>^ And YOU must be careful to carry out all the regulations and the judicial decisions that I am putting before YOU today.

'''

xref:005-deuteronomy/005-deuteronomy-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-012.adoc#v5-12-0[Próximo Capítulo &#62;]