include::./index.adoc[]

[[v5-25-0]]
=== Deuteronomy, 25
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-25-1]]

^<<v5-25-1,1>>^ “In case a dispute arises between men, and they have presented themselves for the judgment, they must also judge them and pronounce the righteous one righteous and pronounce the wicked one wicked.

[[v5-25-2]]

^<<v5-25-2,2>>^ And it must occur that if the wicked one deserves to be beaten,^&#42;1^ the judge must also have him laid prostrate and given strokes before him by number to correspond with his wicked deed.

[NOTE]
====
. Lit., “one is a son of beating.”
====

[[v5-25-3]]

^<<v5-25-3,3>>^ With forty strokes he may beat him. He should add none, for fear he should continue to beat him with many strokes in addition to these and your brother is actually disgraced in your eyes.

[[v5-25-4]]

^<<v5-25-4,4>>^ “You must not muzzle a bull while it is threshing.

[[v5-25-5]]

^<<v5-25-5,5>>^ “In case brothers dwell together and one of them has died without his having a son, the wife of the dead one should not become a strange man’s outside. Her brother-in-law should go to her, and he must take her as his wife and perform brother-in-law marriage with her.^&#42;1^

[NOTE]
====
. “And perform brother-in-law (levirate) marriage with her.” Heb., weyib·bemahʹ.
====

[[v5-25-6]]

^<<v5-25-6,6>>^ And it must occur that the firstborn whom she will bear should succeed to the name of his dead brother, that his name may not be wiped out of Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ “Now if the man finds no delight in taking his brother’s widow, his brother’s widow must then go up to the gate to the older men and say, ‘My husband’s brother has refused to preserve his brother’s name in Israel. He has not consented to perform brother-in-law marriage with me.’

[[v5-25-8]]

^<<v5-25-8,8>>^ And the older men of his city must call him and speak to him, and he must stand and say, ‘I have found no delight in taking her.’

[[v5-25-9]]

^<<v5-25-9,9>>^ At that his brother’s widow must approach him before the eyes of the older men and draw his sandal off his foot and spit in his face and answer and say, ‘That is the way it should be done to the man who will not build up his brother’s household.’

[[v5-25-10]]

^<<v5-25-10,10>>^ And his name must be called in Israel ‘The house of the one who had his sandal drawn off.’

[[v5-25-11]]

^<<v5-25-11,11>>^ “In case men struggle together with one another, and the wife of the one has come near to deliver her husband out of the hand of the one striking him, and she has thrust out her hand and grabbed hold of him by his privates,

[[v5-25-12]]

^<<v5-25-12,12>>^ you must then amputate her hand.^&#42;1^ Your eye must feel no sorrow.

[NOTE]
====
. Lit., “palm.”
====

[[v5-25-13]]

^<<v5-25-13,13>>^ “You must not come to have in your bag two sorts of weights,^&#42;1^ a great one and a small one.

[NOTE]
====
. Lit., “in your bag a weight and a weight.”
====

[[v5-25-14]]

^<<v5-25-14,14>>^ You must not come to have in your house two sorts of eʹphahs,^&#42;1^ a great one and a small one.

[NOTE]
====
. Lit., “in your house an ephah and an ephah.”
====

[[v5-25-15]]

^<<v5-25-15,15>>^ A weight accurate and just you should continue to have. An eʹphah accurate and just you should continue to have, in order that your days may become long on the soil that Jehovah^&#42;1^ your God is giving you.

[NOTE]
====
. See App 1C §1.
====

[[v5-25-16]]

^<<v5-25-16,16>>^ For everyone doing these things, every doer of injustice, is something detestable to Jehovah^&#42;1^ your God.

[NOTE]
====
. See App 1C §1.
====

[[v5-25-17]]

^<<v5-25-17,17>>^ “There should be a remembering^&#42;1^ of what Amʹa·lek did to you in the way when YOU were coming out of Egypt,

[NOTE]
====
. See 24:9 ftn, “Remembering.”
====

[[v5-25-18]]

^<<v5-25-18,18>>^ how he met you in the way and proceeded to strike in the rear of you all those straggling after you, while you were exhausted and weary; and he did not fear God.

[[v5-25-19]]

^<<v5-25-19,19>>^ And it must occur that when Jehovah your God has given you rest from all your enemies round about in the land that Jehovah your God is giving you as an inheritance to take possession of it, you should wipe out the mention of Amʹa·lek from under the heavens. You must not forget.

'''

xref:005-deuteronomy/005-deuteronomy-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-026.adoc#v5-26-0[Próximo Capítulo &#62;]