include::./index.adoc[]

[[v5-14-0]]
=== Deuteronomy, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-14-1]]

^<<v5-14-1,1>>^ “Sons YOU are of Jehovah YOUR God. YOU must not make cuttings upon yourselves or impose baldness on YOUR foreheads^&#42;1^ for a dead person.

[NOTE]
====
. Lit., “between your eyes,” that is, by shaving the eyebrows.
====

[[v5-14-2]]

^<<v5-14-2,2>>^ For you are a holy people to Jehovah your God, and Jehovah has chosen you to become his people, a special property, out of all the peoples who are on the surface of the ground.

[[v5-14-3]]

^<<v5-14-3,3>>^ “You must eat no detestable thing of any sort.

[[v5-14-4]]

^<<v5-14-4,4>>^ This is the sort of beast that YOU may eat: the bull, the sheep and the goat,

[[v5-14-5]]

^<<v5-14-5,5>>^ the stag and gazelle and roebuck and wild goat and antelope^&#42;1^ and wild sheep and chamois;^&#42;2^

[NOTE]
====
. “And antelope.” Heb., wedhi·shonʹ. Some would identify this animal as the bison.
. “And chamois.” Heb., wa·zaʹmer, a bouncing, leaping animal, likely a kind of gazelle.
====

[[v5-14-6]]

^<<v5-14-6,6>>^ and every beast that splits the hoof and that forms a cleft into two hoofs, chewing^&#42;1^ the cud among the beasts. It YOU may eat.

[NOTE]
====
. Lit., “bringing up [regurgitating].”
====

[[v5-14-7]]

^<<v5-14-7,7>>^ Only this sort YOU must not eat out of those that chew the cud or that split the hoof, cloven: the camel and the hare and the rock badger, because they are chewers of the cud but do not split the hoof. They are unclean for YOU.

[[v5-14-8]]

^<<v5-14-8,8>>^ The pig also, because it is a splitter of the hoof but there is no cud. It is unclean for YOU. None of their flesh must YOU eat, and their carcasses YOU must not touch.

[[v5-14-9]]

^<<v5-14-9,9>>^ “This sort out of everything that is in the waters YOU may eat: Everything that has fins and scales YOU may eat.

[[v5-14-10]]

^<<v5-14-10,10>>^ And everything that has no fins and scales YOU must not eat. It is unclean for YOU.

[[v5-14-11]]

^<<v5-14-11,11>>^ “Any clean bird YOU may eat.

[[v5-14-12]]

^<<v5-14-12,12>>^ But these are the ones of which YOU must not eat: the eagle and the osprey^&#42;1^ and the black vulture,

[NOTE]
====
. Lit., “the breaker,” a kind of bird of prey.
====

[[v5-14-13]]

^<<v5-14-13,13>>^ and the red kite^&#42;1^ and the black kite and the glede^&#42;2^ according to its kind;^&#42;3^

[NOTE]
====
. “The red kite,” SamLXX and Le 11:14. The Heb. term suggests a bird distinguished by a swooping or darting flight, hence, a bird of prey.
. “And the glede (kite).” Heb., wehad·dai·yahʹ, an un­identified unclean bird.
. “According to its kind.” Heb., lemi·nahʹ. See Ge 1:11 ftn.
====

[[v5-14-14]]

^<<v5-14-14,14>>^ and every raven according to its kind;

[[v5-14-15]]

^<<v5-14-15,15>>^ and the ostrich^&#42;1^ and the owl^&#42;2^ and the gull and the falcon according to its kind;

[NOTE]
====
. Lit., “the daughter of the des­ert [hard, stony tract of land]”; or, “the daughter of greed.”
. “Night owl,” LXXVg.
====

[[v5-14-16]]

^<<v5-14-16,16>>^ the little owl and the long-eared owl and the swan,^&#42;1^

[NOTE]
====
. “Ibis,” LXXVg.
====

[[v5-14-17]]

^<<v5-14-17,17>>^ and the pelican and the vulture and the cormorant,

[[v5-14-18]]

^<<v5-14-18,18>>^ and the stork and the heron according to its kind, and the hoopoe and the bat.

[[v5-14-19]]

^<<v5-14-19,19>>^ And every winged swarming creature is unclean for YOU. They should not be eaten.

[[v5-14-20]]

^<<v5-14-20,20>>^ Any clean flying creature YOU may eat.

[[v5-14-21]]

^<<v5-14-21,21>>^ “YOU must not eat any body &#91;already&#93; dead.^&#42;1^ To the alien resident who is inside your gates you may give it, and he must eat it; or there may be a selling^&#42;2^ of it to a foreigner, because you are a holy people to Jehovah your God.
“You must not boil a kid in its mother’s milk.

[NOTE]
====
. “Body [already] dead,” that is, any animal found dead.
. “There may be a selling.” In Heb. this is a verb in the infinitive absolute, indefinite as to time.
====

[[v5-14-22]]

^<<v5-14-22,22>>^ “Without fail you should give a tenth^&#42;1^ of all the produce of your seed, that which comes forth of the field year by year.

[NOTE]
====
. Or, “tithe.”
====

[[v5-14-23]]

^<<v5-14-23,23>>^ And before Jehovah your God, in the place that he^&#42;1^ will choose to have his name reside there, you must eat the tenth part of your grain, your new wine and your oil and the firstborn ones of your herd and of your flock; in order that you may learn to fear Jehovah your God always.

[NOTE]
====
. “He,” MSyVg; SamLXX, “Jehovah your God.”
====

[[v5-14-24]]

^<<v5-14-24,24>>^ “Now in case the journey should be too long for you, because you will not be able to carry it, since the place that Jehovah your God will choose to place his name there will be too far away for you, (because Jehovah your God will bless you,)

[[v5-14-25]]

^<<v5-14-25,25>>^ you must then turn it into money, and you must wrap the money up in your hand and travel to the place that Jehovah your God will choose.

[[v5-14-26]]

^<<v5-14-26,26>>^ You must also give the money for whatever your soul may crave in the way of cattle and sheep and goats and wine and intoxicating liquor and anything that your soul may ask of you; and you must eat there before Jehovah your God and rejoice, you and your household.

[[v5-14-27]]

^<<v5-14-27,27>>^ And the Levite who is inside your gates, you must not abandon him, for he has no share or inheritance with you.

[[v5-14-28]]

^<<v5-14-28,28>>^ “At the end of three years you will bring out the entire tenth part of your produce in that year, and you must deposit it inside your gates.

[[v5-14-29]]

^<<v5-14-29,29>>^ And the Levite, because he has no share or inheritance with you, and the alien resident and the fatherless boy and the widow, who are inside your gates, must come, and they must eat and satisfy themselves; in order that Jehovah your God may bless you in every deed of your hand that you will do.

'''

xref:005-deuteronomy/005-deuteronomy-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-015.adoc#v5-15-0[Próximo Capítulo &#62;]