include::./index.adoc[]

[[v5-8-0]]
=== Deuteronomy, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-8-1]]

^<<v5-8-1,1>>^ “Every commandment that I am commanding you today YOU should be careful to keep, in order that YOU may continue living and indeed multiply and go in and take possession of the land about which Jehovah swore to YOUR forefathers.

[[v5-8-2]]

^<<v5-8-2,2>>^ And you must remember all the way that Jehovah your God made you walk these forty years in the wilderness, in order to humble you, to put you to the test so as to know what was in your heart, as to whether you would keep his commandments or not.

[[v5-8-3]]

^<<v5-8-3,3>>^ So he humbled you and let you go hungry and fed you with the manna, which neither you had known nor your fathers had known; in order to make you know that not by bread alone does man live but by every expression of Jehovah’s mouth does man live.

[[v5-8-4]]

^<<v5-8-4,4>>^ Your mantle did not wear out upon you, nor did your foot become swollen these forty years.

[[v5-8-5]]

^<<v5-8-5,5>>^ And you well know with your own heart that just as a man corrects his son, Jehovah your God was correcting you.

[[v5-8-6]]

^<<v5-8-6,6>>^ “And you must keep the commandments of Jehovah your God by walking in his ways and by fearing him.

[[v5-8-7]]

^<<v5-8-7,7>>^ For Jehovah your God is bringing you into a good land, a land of torrent valleys of water, springs and watery deeps^&#42;1^ issuing forth in the valley plain and in the mountainous region,

[NOTE]
====
. “And watery deeps (great quan­tities of water).” Heb., u·theho·mothʹ, pl., as in Sam.
====

[[v5-8-8]]

^<<v5-8-8,8>>^ a land of wheat and barley and vines and figs and pomegranates, a land of oil olives and honey,

[[v5-8-9]]

^<<v5-8-9,9>>^ a land in which you will not eat bread with scarcity, in which you will lack nothing, a land the stones of which are iron and out of the mountains of which you will mine copper.

[[v5-8-10]]

^<<v5-8-10,10>>^ “When you have eaten and satisfied yourself, you must also bless Jehovah your God for the good land that he has given you.

[[v5-8-11]]

^<<v5-8-11,11>>^ Watch out for yourself that you may not forget Jehovah your God so as not to keep his commandments and his judicial decisions and his statutes that I am commanding you today;

[[v5-8-12]]

^<<v5-8-12,12>>^ for fear that you may eat and indeed satisfy yourself, and you may build good houses and indeed dwell in them,

[[v5-8-13]]

^<<v5-8-13,13>>^ and your herd and your flock may increase, and silver and gold may increase for you, and all that is yours may increase;

[[v5-8-14]]

^<<v5-8-14,14>>^ and your heart may indeed be lifted up and you may indeed forget Jehovah your God, who brought you out of the land of Egypt, out of the house of slaves;

[[v5-8-15]]

^<<v5-8-15,15>>^ who caused you to walk through the great and fear-inspiring wilderness, with poisonous^&#42;1^ serpents and scorpions^&#42;2^ and with thirsty ground that has no water; who brought forth water for you out of the flinty rock;

[NOTE]
====
. Or, “fiery; inflammation-causing.” LXX, “stinging; biting”; Vg, “fiery (burning) in breath.”
. Lit., “And fighter.” Heb., weʽaq·ravʹ; Lat., et scorʹpi·o.
====

[[v5-8-16]]

^<<v5-8-16,16>>^ who fed you with manna in the wilderness, which your fathers had not known, in order to humble you and in order to put you to the test so as to do you good in your afterdays;

[[v5-8-17]]

^<<v5-8-17,17>>^ and you do say in your heart, ‘My own power and the full might of my own hand have made this wealth for me.’

[[v5-8-18]]

^<<v5-8-18,18>>^ And you must remember Jehovah your God, because he is the giver of power to you to make wealth; in order to carry out his covenant that he swore to your forefathers, as at this day.

[[v5-8-19]]

^<<v5-8-19,19>>^ “And it must occur that if you should at all forget Jehovah your God and you should actually walk after other gods and serve them and bow down to them, I do bear witness against YOU today that YOU people will absolutely perish.

[[v5-8-20]]

^<<v5-8-20,20>>^ Like the nations that Jehovah is destroying from before YOU, that is the way YOU will perish, because YOU will not listen to the voice of Jehovah YOUR God.

'''

xref:005-deuteronomy/005-deuteronomy-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-009.adoc#v5-9-0[Próximo Capítulo &#62;]