include::./index.adoc[]

[[v5-2-0]]
=== Deuteronomy, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-2-1]]

^<<v5-2-1,1>>^ “Then we turned and pulled away for the wilderness by the way of the Red Sea, just as Jehovah had spoken to me; and we were many days in going around Mount Seʹir.

[[v5-2-2]]

^<<v5-2-2,2>>^ Finally Jehovah said this to me,

[[v5-2-3]]

^<<v5-2-3,3>>^ ‘YOU have gone around this mountain long enough. Change YOUR direction to the north.

[[v5-2-4]]

^<<v5-2-4,4>>^ And command the people, saying: “YOU are passing along by the border of YOUR brothers, the sons of Eʹsau, who are dwelling in Seʹir; and they will be afraid because of YOU, and YOU must be very careful.

[[v5-2-5]]

^<<v5-2-5,5>>^ Do not engage in strife with them, because I shall not give YOU of their land so much as the width of the sole of the foot; because I have given Mount Seʹir to Eʹsau as a holding.

[[v5-2-6]]

^<<v5-2-6,6>>^ What food YOU may buy from them for money, YOU must eat; and also what water YOU may purchase from them for money, YOU must drink.

[[v5-2-7]]

^<<v5-2-7,7>>^ For Jehovah your God has blessed you in every deed of your hand. He well knows of your walking through this great wilderness. These forty years Jehovah your God has been with you. You have not lacked a thing.”’

[[v5-2-8]]

^<<v5-2-8,8>>^ So we passed on away from our brothers, the sons of Eʹsau, who are dwelling in Seʹir, from the way of the Arʹa·bah, from Eʹlath and from Eʹzi·on-geʹber.
“Next we turned and passed on by the way of the wilderness of Moʹab.

[[v5-2-9]]

^<<v5-2-9,9>>^ Jehovah then said to me, ‘Do not molest Moʹab or engage in war with them, because I shall not give you any of his land as a holding, for to the sons of Lot I have given Ar as a holding.

[[v5-2-10]]

^<<v5-2-10,10>>^ (The Eʹmim^&#42;1^ dwelt in it in former times, a people great and numerous and tall like the Anʹa·kim.

[NOTE]
====
. Or, “frightful creatures.”
====

[[v5-2-11]]

^<<v5-2-11,11>>^ As for the Rephʹa·im, they also were considered like the Anʹa·kim, and the Moʹab·ites used to call them Eʹmim.

[[v5-2-12]]

^<<v5-2-12,12>>^ And the Horʹites dwelt in Seʹir in former times, and the sons of Eʹsau proceeded to dispossess them and to annihilate them from before them and to dwell in their place, just the same as Israel must do to the land that is his holding, which Jehovah will certainly give to them.)

[[v5-2-13]]

^<<v5-2-13,13>>^ At this time rise and make YOUR way across the torrent valley of Zeʹred.’ Accordingly we went crossing the torrent valley of Zeʹred.

[[v5-2-14]]

^<<v5-2-14,14>>^ And the days that we walked from Kaʹdesh-barʹne·a until we crossed the torrent valley of Zeʹred were thirty-eight years, until all the generation of the men of war had come to their end from the midst of the camp, just as Jehovah had sworn to them.

[[v5-2-15]]

^<<v5-2-15,15>>^ And the hand of Jehovah also proved to be upon them to disquiet them out of the midst of the camp, until they came to their end.

[[v5-2-16]]

^<<v5-2-16,16>>^ “And it came about that as soon as all the men of war had finished dying off from the midst of the people,

[[v5-2-17]]

^<<v5-2-17,17>>^ Jehovah spoke further to me, saying,

[[v5-2-18]]

^<<v5-2-18,18>>^ ‘You are passing today by the territory of Moʹab, that is, Ar,

[[v5-2-19]]

^<<v5-2-19,19>>^ and you must get close in front of the sons of Amʹmon. Do not molest them or engage in strife with them, because I shall not give you any of the land of the sons of Amʹmon as a holding, for it is to the sons of Lot that I have given it as a holding.

[[v5-2-20]]

^<<v5-2-20,20>>^ As the land of the Rephʹa·im it also used to be considered. (The Rephʹa·im dwelt in it in former times, and the Amʹmon·ites used to call them Zam·zumʹmim.

[[v5-2-21]]

^<<v5-2-21,21>>^ They were a great and numerous and tall people like the Anʹa·kim; and Jehovah went annihilating them from before them, that they might dispossess them and dwell in their place;

[[v5-2-22]]

^<<v5-2-22,22>>^ just the same as he did for the sons of Eʹsau, who are dwelling in Seʹir, when he annihilated the Horʹites from before them, that they might dispossess them and dwell in their place until this day.

[[v5-2-23]]

^<<v5-2-23,23>>^ As for the Avʹvim, who were dwelling in settlements as far as Gaʹza, the Caphʹto·rim, who came out from Caphʹtor, annihilated them, that they might dwell in their place.)

[[v5-2-24]]

^<<v5-2-24,24>>^ “‘GET up, pull away and cross the torrent valley of Arʹnon. See, I have given into your hand Siʹhon the king of Heshʹbon, the Amʹor·ite. So start to take possession of his land, and engage in war with him.

[[v5-2-25]]

^<<v5-2-25,25>>^ This day I shall start to put the dread of you and the fear of you before the peoples beneath all the heavens, who will hear the report about you; and they will indeed be agitated and have pains like those of childbirth because of you.’

[[v5-2-26]]

^<<v5-2-26,26>>^ “Then I sent messengers from the wilderness of Kedʹe·moth to Siʹhon the king of Heshʹbon with words of peace, saying,

[[v5-2-27]]

^<<v5-2-27,27>>^ ‘Let me pass through your land. Only on the road^&#42;1^ I shall walk. I shall not turn to the right or to the left.

[NOTE]
====
. “Road,” MSamLXX; Vg, “public way.”
====

[[v5-2-28]]

^<<v5-2-28,28>>^ What food you will sell me for money, I must eat; and what water you will give me for money, I must drink. Only let me pass through on my feet,

[[v5-2-29]]

^<<v5-2-29,29>>^ just the same as the sons of Eʹsau dwelling in Seʹir and the Moʹab·ites dwelling in Ar did to me, until I shall pass over the Jordan into the land that Jehovah our God is giving to us.’

[[v5-2-30]]

^<<v5-2-30,30>>^ And Siʹhon the king of Heshʹbon did not let us pass through him, because Jehovah your God had let his spirit become obstinate and his heart become hard, in order to give him into your hand just as at this day.

[[v5-2-31]]

^<<v5-2-31,31>>^ “At this Jehovah said to me, ‘See, I have started to abandon Siʹhon and his land to you. Start to take possession of his land.’

[[v5-2-32]]

^<<v5-2-32,32>>^ When Siʹhon came on out, he and all his people, to meet us in battle at Jaʹhaz,

[[v5-2-33]]

^<<v5-2-33,33>>^ then Jehovah our God abandoned him to us, so that we defeated him and his sons^&#42;1^ and all his people.

[NOTE]
====
. “Sons,” MmarginSamLXXSyVg.
====

[[v5-2-34]]

^<<v5-2-34,34>>^ And we went capturing all his cities at that particular time and devoting every city to destruction, men and women and little children. We left no survivor.

[[v5-2-35]]

^<<v5-2-35,35>>^ Only the domestic animals did we take as plunder for ourselves, together with the spoil of the cities that we had captured.

[[v5-2-36]]

^<<v5-2-36,36>>^ From A·roʹer, which is by the bank of the torrent valley of Arʹnon, and the city that is in the torrent valley, as far as Gilʹe·ad, there proved to be no town that was too high up for us. Jehovah our God abandoned them all to us.

[[v5-2-37]]

^<<v5-2-37,37>>^ Only you did not go near the land of the sons of Amʹmon, the whole bank of the torrent valley of Jabʹbok, nor the cities of the mountainous region, nor anything about which Jehovah our God had given command.

'''

xref:005-deuteronomy/005-deuteronomy-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-003.adoc#v5-3-0[Próximo Capítulo &#62;]