include::./index.adoc[]

[[v5-9-0]]
=== Deuteronomy, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-9-1]]

^<<v5-9-1,1>>^ “Hear, O Israel, you are today crossing the Jordan to go in and dispossess nations greater and mightier than you, cities great and fortified to the heavens,

[[v5-9-2]]

^<<v5-9-2,2>>^ a people great and tall, the sons of Anʹa·kim, about whom you yourself have known and you yourself have heard it said, ‘Who can make a firm stand before the sons of Aʹnak?’

[[v5-9-3]]

^<<v5-9-3,3>>^ And you well know today that Jehovah your God is crossing before you. A consuming fire he is. He will annihilate them, and he himself will subdue them before you; and you must dispossess them and destroy them speedily, just as Jehovah has spoken to you.

[[v5-9-4]]

^<<v5-9-4,4>>^ “Do not say in your heart when Jehovah your God pushes them away from before you this, ‘It was for my own righteousness that Jehovah has brought me in to take possession of this land,’ whereas it is for the wickedness of these nations that Jehovah is driving them away from before you.

[[v5-9-5]]

^<<v5-9-5,5>>^ It is not for your righteousness or for the uprightness of your heart that you are going in to take possession of their land; in fact, it is for the wickedness of these nations that Jehovah your God is driving them away from before you, and in order to carry out the word that Jehovah swore to your forefathers, Abraham, Isaac and Jacob.

[[v5-9-6]]

^<<v5-9-6,6>>^ And you must know that it is not for your righteousness that Jehovah your God is giving you this good land to take possession of it; for you are a stiff-necked people.

[[v5-9-7]]

^<<v5-9-7,7>>^ “Remember: Do not forget how you have provoked Jehovah your God in the wilderness. From the day that you went out of the land of Egypt until YOUR coming to this place YOU people have proved rebellious in YOUR behavior with Jehovah.

[[v5-9-8]]

^<<v5-9-8,8>>^ Even in Hoʹreb YOU provoked Jehovah to anger so that Jehovah got incensed at YOU to the point of annihilating YOU.

[[v5-9-9]]

^<<v5-9-9,9>>^ When I went up the mountain to receive the stone tablets, the tablets of the covenant that Jehovah had concluded with YOU, and I kept dwelling in the mountain forty days and forty nights, (I neither ate bread nor drank water,)

[[v5-9-10]]

^<<v5-9-10,10>>^ then Jehovah gave me the two tablets of stone written upon with God’s finger; and upon them were all the words^&#42;1^ that Jehovah had spoken with YOU in the mountain out of the middle of the fire in the day of the congregation.^&#42;2^

[NOTE]
====
. According to LXXSyVg; MSam, “upon them there was [the same] as all the words.”
. “The congregation.” Heb., haq·qa·halʹ; Gr., ek·kle·siʹas. See 4:10 ftn, “Horeb.”
====

[[v5-9-11]]

^<<v5-9-11,11>>^ And it came about that at the end of the forty days and forty nights Jehovah gave me the two tablets of stone, the tablets of the covenant;

[[v5-9-12]]

^<<v5-9-12,12>>^ and Jehovah proceeded to say to me, ‘Get up, go down quickly from here, because your people whom you brought out of Egypt have acted ruinously. They have turned aside quickly from the way about which I commanded them. They have made themselves a molten image.’

[[v5-9-13]]

^<<v5-9-13,13>>^ And Jehovah went on to say this to me, ‘I have seen this people, and, look! it is a stiff-necked people.

[[v5-9-14]]

^<<v5-9-14,14>>^ Let me alone that I may annihilate them and wipe out their name from under the heavens, and let me make you a nation mightier and more populous than they are.’

[[v5-9-15]]

^<<v5-9-15,15>>^ “After that I turned and went down from the mountain, while the mountain was burning with fire; and the two tablets of the covenant were in both my hands.

[[v5-9-16]]

^<<v5-9-16,16>>^ Then I looked, and there YOU had sinned against Jehovah YOUR God! YOU had made yourselves a molten calf. YOU had turned aside quickly from the way about which Jehovah had commanded YOU.

[[v5-9-17]]

^<<v5-9-17,17>>^ At that I took hold of the two tablets and flung them down from both my hands and shattered them before YOUR eyes.

[[v5-9-18]]

^<<v5-9-18,18>>^ And I proceeded to prostrate myself before Jehovah, as at first, forty days and forty nights. I neither ate bread nor drank water, because of all YOUR sin that YOU had committed in doing evil in the eyes of Jehovah so as to offend him.

[[v5-9-19]]

^<<v5-9-19,19>>^ For I was scared because of the hot anger with which Jehovah had got indignant at YOU to the point of annihilating YOU. However, Jehovah listened to me also that time.

[[v5-9-20]]

^<<v5-9-20,20>>^ “At Aaron, too, Jehovah got very incensed to the point of annihilating him; but I made supplication also in behalf of Aaron at that particular time.

[[v5-9-21]]

^<<v5-9-21,21>>^ And YOUR sin that YOU had made, the calf, I took, and I proceeded to burn it in the fire and to crush it, grinding it thoroughly until it had become fine like dust; after which I threw its dust into the torrent that was descending from the mountain.

[[v5-9-22]]

^<<v5-9-22,22>>^ “Further, at Tabʹe·rah and at Masʹsah and at Kibʹroth-hat·taʹa·vah YOU proved yourselves provokers of Jehovah to anger.

[[v5-9-23]]

^<<v5-9-23,23>>^ And when Jehovah sent YOU out of Kaʹdesh-barʹne·a, saying, ‘Go up and take possession of the land that I shall certainly give YOU!’ then YOU behaved rebelliously against the order of Jehovah YOUR God, and YOU did not exercise faith toward him and did not listen to his voice.

[[v5-9-24]]

^<<v5-9-24,24>>^ YOU have proved yourselves rebellious in behavior with Jehovah from the day of my knowing YOU.

[[v5-9-25]]

^<<v5-9-25,25>>^ “So I kept prostrating myself before Jehovah forty days and forty nights, for I prostrated myself thus because Jehovah talked^&#42;1^ of annihilating YOU.

[NOTE]
====
. Or, “thought.”
====

[[v5-9-26]]

^<<v5-9-26,26>>^ And I began to make supplication to Jehovah and to say, ‘O Sovereign Lord Jehovah,^&#42;1^ do not bring to ruin your people, even your private property,^&#42;2^ whom you redeemed with your greatness, whom you brought out of Egypt with a strong hand.

[NOTE]
====
. “O Sovereign Lord Jehovah.” Heb., ʼAdho·naiʹ Yehwihʹ. See App 1E.
. Or, “your inheritance.”
====

[[v5-9-27]]

^<<v5-9-27,27>>^ Remember your servants Abraham, Isaac and Jacob. Do not turn your face to the hardness of this people and their wickedness and their sin,

[[v5-9-28]]

^<<v5-9-28,28>>^ for fear the land^&#42;1^ out of which you brought us may say: “Because Jehovah was unable to bring them into the land that he had promised them, and because he hated them he brought them out to put them to death in the wilderness.”

[NOTE]
====
. “The land,” sing. but with the verb, “may say,” pl. in Heb.; SamLXXSyVg, “the inhabitants of the land.”
====

[[v5-9-29]]

^<<v5-9-29,29>>^ They are, too, your people and your private property whom you brought out with your great power and your outstretched arm.’

'''

xref:005-deuteronomy/005-deuteronomy-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-010.adoc#v5-10-0[Próximo Capítulo &#62;]