include::./index.adoc[]

[[v5-31-0]]
=== Deuteronomy, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-31-1]]

^<<v5-31-1,1>>^ Then Moses went and spoke these words to all Israel

[[v5-31-2]]

^<<v5-31-2,2>>^ and said to them: “A hundred and twenty years old I am today. I shall no more be allowed to go out and come in, as Jehovah has said to me, ‘You will not cross this Jordan.’

[[v5-31-3]]

^<<v5-31-3,3>>^ Jehovah^&#42;1^ your God is the one crossing before you. He himself will annihilate these nations from before you, and you must drive them away. Joshua^&#42;2^ is the one crossing before you, just as Jehovah has spoken.

[NOTE]
====
. See App 1C §1.
. “Joshua.” Heb., Yehoh·shuʹaʽ, “Jehoshua”; Gr., Ἰησοῦς (Jesus); Syr., Ye·shuaʽ; Lat., Ioʹsu·e.
====

[[v5-31-4]]

^<<v5-31-4,4>>^ And Jehovah will certainly do to them just as he has done to Siʹhon and to Og, the kings of the Amʹor·ites, and to their land, when he annihilated them.

[[v5-31-5]]

^<<v5-31-5,5>>^ And Jehovah has abandoned them to YOU, and YOU must do to them according to all the commandment that I have commanded YOU.

[[v5-31-6]]

^<<v5-31-6,6>>^ BE courageous and strong. Do not be afraid or suffer a shock before them, because Jehovah your God is the one marching with you. He will neither desert you nor leave you entirely.”

[[v5-31-7]]

^<<v5-31-7,7>>^ And Moses proceeded to call Joshua and say to him before the eyes of all Israel: “Be courageous and strong, because you—you will bring^&#42;1^ this people into the land that Jehovah swore to their forefathers to give to them, and you yourself will give it to them as an inheritance.

[NOTE]
====
. “You will bring,” SamSyVg and five Heb. mss; M, “you will go with”; LXX, “you will go before the face of.” Compare vs 23.
====

[[v5-31-8]]

^<<v5-31-8,8>>^ And Jehovah is the one marching before you. He himself will continue with you. He will neither desert you nor leave you entirely. Do not be afraid or be terrified.”

[[v5-31-9]]

^<<v5-31-9,9>>^ Then Moses wrote this law and gave it to the priests the sons of Leʹvi, the carriers of the ark of Jehovah’s covenant, and to all the older men of Israel.

[[v5-31-10]]

^<<v5-31-10,10>>^ And Moses went on to command them, saying: “At the end of every seven years, in the appointed time of the year of the release, in the festival of booths,

[[v5-31-11]]

^<<v5-31-11,11>>^ when all Israel comes to see^&#42;1^ the face of Jehovah your God in the place that he will choose, you will read this law in front of all Israel in their hearing.^&#42;2^

[NOTE]
====
. “See,” by a correction of the vowel pointing of M; LXXSyVg, “appear before.” Compare 16:16.
. Lit., “ears.”
====

[[v5-31-12]]

^<<v5-31-12,12>>^ Congregate the people, the men and the women and the little ones and your alien resident who is within your gates, in order that they may listen and in order that they may learn, as they must fear Jehovah YOUR God and take care to carry out all the words of this law.

[[v5-31-13]]

^<<v5-31-13,13>>^ And their sons who have not known should listen, and they must learn to fear Jehovah YOUR God all the days that YOU are living upon the soil to which YOU are crossing the Jordan to take possession of it.”

[[v5-31-14]]

^<<v5-31-14,14>>^ After that Jehovah said to Moses: “Look! The days have drawn near for you to die. Call Joshua, and station yourselves in the tent of meeting, that I may commission him.” So Moses and Joshua went and stationed themselves in the tent of meeting.

[[v5-31-15]]

^<<v5-31-15,15>>^ Then Jehovah appeared at the tent in the pillar of cloud, and the pillar of cloud began to stand by the entrance of the tent.

[[v5-31-16]]

^<<v5-31-16,16>>^ Jehovah now said to Moses: “Look! You are lying down with your forefathers; and this people will certainly get up and have immoral intercourse^&#42;1^ with foreign gods of the land to which they are going, in their very midst, and they will certainly forsake me and break my covenant that I have concluded with them.

[NOTE]
====
. Or, “and commit fornication.”
====

[[v5-31-17]]

^<<v5-31-17,17>>^ At that my anger will indeed blaze against them in that day, and I shall certainly forsake them and conceal my face from them, and they must become something to be consumed; and many calamities and distresses must come upon them, and they will be bound to say in that day, ‘Is it not because our^&#42;1^ God is not in our midst that these calamities have come upon us?’^&#42;2^

[NOTE]
====
. Lit., “my,” MSam.
. Lit., “me,” MSam.
====

[[v5-31-18]]

^<<v5-31-18,18>>^ As for me, I shall absolutely conceal my face in that day because of all the badness that they have done, because they have turned to other gods.

[[v5-31-19]]

^<<v5-31-19,19>>^ “And now WRITE for yourselves this song and teach it to the sons of Israel. Place it in their mouths in order that this song may serve as my witness against the sons of Israel.

[[v5-31-20]]

^<<v5-31-20,20>>^ For I shall bring them to the ground that I have sworn about^&#42;1^ to their forefathers, which flows with milk and honey, and they will certainly eat and be satisfied and grow fat and turn to other gods, and they will indeed serve them and treat me with disrespect and break my covenant.

[NOTE]
====
. Or, “I have promised on oath.”
====

[[v5-31-21]]

^<<v5-31-21,21>>^ And it must occur that when many calamities and distresses will come upon them, this song must also answer before them as a witness, because it should not be forgotten out of the mouth of their offspring, for I well know their inclination that they are developing today before I bring them into the land about which I have sworn.”^&#42;1^

[NOTE]
====
. “I have sworn,” M; LXXSy, “I have sworn to their forefathers”; Sam, “I have sworn to his forefathers”; Vg, “I have promised him.”
====

[[v5-31-22]]

^<<v5-31-22,22>>^ So Moses wrote this song in that day, that he might teach it to the sons of Israel.

[[v5-31-23]]

^<<v5-31-23,23>>^ And he proceeded to commission Joshua the son of Nun and to say: “Be courageous and strong, because you—you will bring the sons of Israel into the land about which I have sworn to them, and I myself shall continue with you.”

[[v5-31-24]]

^<<v5-31-24,24>>^ And it came about that as soon as Moses had finished writing the words of this law in a book until their completion,

[[v5-31-25]]

^<<v5-31-25,25>>^ Moses began to command the Levites, the carriers of the ark of Jehovah’s covenant, saying:

[[v5-31-26]]

^<<v5-31-26,26>>^ “Taking^&#42;1^ this book of the law, YOU must place it at the side of the ark of the covenant of Jehovah^&#42;2^ YOUR God, and it must serve as a witness there against you.

[NOTE]
====
. “Taking.” In Heb. this is a verb in the infinitive absolute, indefinite as to time.
. See App 1C §1.
====

[[v5-31-27]]

^<<v5-31-27,27>>^ For I—I well know your rebelliousness and your stiff neck. If while I am yet alive with YOU today, YOU have proved rebellious in behavior toward Jehovah,^&#42;1^ then how much more so after my death!

[NOTE]
====
. See App 1C §1.
====

[[v5-31-28]]

^<<v5-31-28,28>>^ Congregate to me all the older men of YOUR tribes and YOUR officers, and let me speak in their hearing these words, and let me take the heavens and the earth as witnesses against them.

[[v5-31-29]]

^<<v5-31-29,29>>^ For I well know that after my death YOU will without fail act ruinously, and YOU will certainly turn aside from the way about which I have commanded YOU; and calamity will be bound to befall YOU at the close of the days, because YOU will do what is bad in the eyes of Jehovah^&#42;1^ so as to offend him by the works of YOUR hands.”

[NOTE]
====
. See App 1C §1.
====

[[v5-31-30]]

^<<v5-31-30,30>>^ And Moses proceeded to speak in the hearing of all the congregation^&#42;1^ of Israel the words of this song until their completion:

[NOTE]
====
. “All the congregation of.” Heb., kol-qehalʹ; Gr., ek·kle·siʹas.
====

'''

xref:005-deuteronomy/005-deuteronomy-030.adoc#v5-30-0[&#60; Capítulo Anterior] | <<v5-31-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-032.adoc#v5-32-0[Próximo Capítulo &#62;]