include::./index.adoc[]

[[v5-23-0]]
=== Deuteronomy, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-23-1]]

^<<v5-23-1,1>>^ “No man castrated by crushing the testicles or having his male member cut off may come into the congregation^&#42;1^ of Jehovah.

[NOTE]
====
. “Into the congregation of.” Heb., biq·halʹ; Gr., ek·kle·siʹan; Lat., ec·cleʹsi·am.
====

[[v5-23-2]]

^<<v5-23-2,2>>^ “No illegitimate son may come into the congregation of Jehovah. Even to the tenth generation none of his may come into the congregation of Jehovah.

[[v5-23-3]]

^<<v5-23-3,3>>^ “No Amʹmon·ite or Moʹab·ite^&#42;1^ may come into the congregation of Jehovah. Even to the tenth generation none of theirs may come into the congregation of Jehovah to time indefinite,

[NOTE]
====
. “Ammonite or Moabite,” masc., possibly referring to the males only.
====

[[v5-23-4]]

^<<v5-23-4,4>>^ for the reason that they did not come to YOUR aid with bread and water in the way when YOU were going out of Egypt, and because they hired^&#42;1^ against you Baʹlaam the son of Beʹor from Peʹthor of Mes·o·po·taʹmi·a^&#42;2^ to call down evil upon you.

[NOTE]
====
. “They hired,” LXXVg; MSamSy, “he hired; there was hired.”
. “Mesopotamia,” LXX; Vg, “Mesopotamia of Syria”; MSamSy, “Aram-naharaim.”
====

[[v5-23-5]]

^<<v5-23-5,5>>^ And Jehovah^&#42;1^ your God did not want to listen to Baʹlaam; but Jehovah your God in your behalf changed the malediction into a blessing, because Jehovah your God loved you.

[NOTE]
====
. See App 1C §1.
====

[[v5-23-6]]

^<<v5-23-6,6>>^ You must not work for^&#42;1^ their peace and their prosperity all your days to time indefinite.

[NOTE]
====
. Or, “not ask about.”
====

[[v5-23-7]]

^<<v5-23-7,7>>^ “You must not detest an Eʹdom·ite,^&#42;1^ for he is your brother.
“You must not detest an Egyptian, for you became an alien resident in his country.

[NOTE]
====
. Or, “Idumean.”
====

[[v5-23-8]]

^<<v5-23-8,8>>^ The sons that may be born to them as the third generation^&#42;1^ may come for themselves into the congregation of Jehovah.

[NOTE]
====
. Or, “as great-grandsons.”
====

[[v5-23-9]]

^<<v5-23-9,9>>^ “In case you go out into camp against your enemies, you must also keep yourself from every bad thing.

[[v5-23-10]]

^<<v5-23-10,10>>^ In case there happens to be in you a man who does not continue clean, because of a pollution that occurs at night, he must also go outside the camp. He may not come into the midst of the camp.

[[v5-23-11]]

^<<v5-23-11,11>>^ And it must occur that at the falling of evening he should wash with water, and at the setting of the sun he may come into the midst of the camp.

[[v5-23-12]]

^<<v5-23-12,12>>^ And a private place^&#42;1^ should be at your service outside the camp, and you must go out there.

[NOTE]
====
. Or, “a privy.”
====

[[v5-23-13]]

^<<v5-23-13,13>>^ And a peg should be at your service along with your implements,^&#42;1^ and it must occur that when you squat outside, you must also dig a hole with it and turn and cover your excrement.

[NOTE]
====
. Or, “on your tools,” M; LXXVg, “on your belt.”
====

[[v5-23-14]]

^<<v5-23-14,14>>^ For Jehovah your God is walking about within your camp to deliver you and to abandon your enemies to you; and your camp must prove to be holy, that he may see nothing indecent in you^&#42;1^ and certainly turn away from accompanying you.

[NOTE]
====
. Lit., “that he may not see in you the nakedness of a thing.”
====

[[v5-23-15]]

^<<v5-23-15,15>>^ “You must not hand over a slave to his master^&#42;1^ when he escapes from his master to you.

[NOTE]
====
. “His master.” Heb., ʼadho·navʹ, pl. to denote excellence.
====

[[v5-23-16]]

^<<v5-23-16,16>>^ With you he will keep on dwelling in among you in whatever place he may choose in one of your cities,^&#42;1^ wherever he likes. You must not maltreat him.

[NOTE]
====
. Lit., “your gates.”
====

[[v5-23-17]]

^<<v5-23-17,17>>^ “None of the daughters of Israel may become a temple prostitute, neither may anyone of the sons of Israel become a temple prostitute.^&#42;1^

[NOTE]
====
. Or, “a catamite,” a boy kept for purposes of sexual perversion.
====

[[v5-23-18]]

^<<v5-23-18,18>>^ You must not bring the hire of a harlot^&#42;1^ or the price of a dog^&#42;2^ into the house of Jehovah your God for any vow, because they are something detestable to Jehovah your God, even both of them.

[NOTE]
====
. Or, “prostitute.” Gr., porʹnes.
. Likely a pederast; one who practices anal intercourse, especially with a boy.
====

[[v5-23-19]]

^<<v5-23-19,19>>^ “You must not make your brother pay interest, interest on money, interest on food, interest on anything on which one may claim interest.

[[v5-23-20]]

^<<v5-23-20,20>>^ You may make a foreigner pay interest, but your brother you must not make pay interest; in order that Jehovah your God may bless you in every undertaking of yours on the land to which you are going so as to take possession of it.

[[v5-23-21]]

^<<v5-23-21,21>>^ “In case you vow a vow to Jehovah your God, you must not be slow about paying it, because Jehovah your God will without fail require it of you, and it would indeed become a sin on your part.

[[v5-23-22]]

^<<v5-23-22,22>>^ But in case you omit making a vow, it will not become a sin on your part.

[[v5-23-23]]

^<<v5-23-23,23>>^ The utterance of your lips you should keep, and you must do just as you have vowed to Jehovah your God as a voluntary offering that you spoke of with your mouth.

[[v5-23-24]]

^<<v5-23-24,24>>^ “In case you go into the vineyard of your fellowman, you must eat only enough grapes for you to satisfy your soul,^&#42;1^ but you must not put any into a receptacle of yours.

[NOTE]
====
. “For . . . your soul (own self).” MSam(Heb.), kenaph·shekhaʹ; Gr., psy·khenʹ sou; Syr., naph·shakh.
====

[[v5-23-25]]

^<<v5-23-25,25>>^ “In case you go into the standing grain of your fellowman, you must pluck off only the ripe ears with your hand, but the sickle you must not swing to and fro upon the standing grain of your fellowman.

'''

xref:005-deuteronomy/005-deuteronomy-022.adoc#v5-22-0[&#60; Capítulo Anterior] | <<v5-23-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-024.adoc#v5-24-0[Próximo Capítulo &#62;]