include::./index.adoc[]

[[v5-3-0]]
=== Deuteronomy, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-3-1]]

^<<v5-3-1,1>>^ “Then we turned and went up by the way of Baʹshan. At this Og the king of Baʹshan came on out, he and all his people, to meet us in battle at Edʹre·i.

[[v5-3-2]]

^<<v5-3-2,2>>^ So Jehovah said to me, ‘Do not be afraid of him, for I shall certainly give him and all his people and his land into your hand; and you must do to him just as you did to Siʹhon the king of the Amʹor·ites, who was dwelling in Heshʹbon.’

[[v5-3-3]]

^<<v5-3-3,3>>^ Accordingly Jehovah our God gave into our hand also Og the king of Baʹshan and all his people, and we kept striking him until he had no survivor remaining.

[[v5-3-4]]

^<<v5-3-4,4>>^ And we went capturing all his cities at that particular time. There proved to be no town that we did not take from them, sixty cities, all the region of Arʹgob, the kingdom of Og in Baʹshan.

[[v5-3-5]]

^<<v5-3-5,5>>^ All these were cities fortified with a high wall, doors and bar, aside from very many rural towns.

[[v5-3-6]]

^<<v5-3-6,6>>^ However, we devoted them to destruction, just as we had done to Siʹhon the king of Heshʹbon, in devoting every city to destruction, men, women and little children.

[[v5-3-7]]

^<<v5-3-7,7>>^ And all the domestic animals and the spoil of the cities we took as plunder for ourselves.

[[v5-3-8]]

^<<v5-3-8,8>>^ “And we proceeded to take at that particular time the land from the hand of the two kings of the Amʹor·ites who were in the region of the Jordan, from the torrent valley of Arʹnon as far as Mount Herʹmon;

[[v5-3-9]]

^<<v5-3-9,9>>^ (the Si·doʹni·ans used to call Herʹmon Sirʹi·on, and the Amʹor·ites used to call it Seʹnir,)^&#42;1^

[NOTE]
====
. “Sirion . . . Senir.” These names appear in the Ugaritic texts found at Ras Shamra, Syria, and in the documents from Bogazköy, Turkey.
====

[[v5-3-10]]

^<<v5-3-10,10>>^ all the cities of the tableland and all Gilʹe·ad and all Baʹshan as far as Salʹe·cah and Edʹre·i, the cities of the kingdom of Og in Baʹshan.

[[v5-3-11]]

^<<v5-3-11,11>>^ For only Og the king of Baʹshan remained of what was left of the Rephʹa·im. Look! His bier was a bier of iron.^&#42;1^ Is it not in Rabʹbah of the sons of Amʹmon? Nine cubits^&#42;2^ is its length, and four cubits its width, by the cubit of a man.

[NOTE]
====
. Or, “a sarcophagus of black basalt.” The Arabs still refer to basalt as iron.
. A cubit equaled 44.5 cm (17.5 in.).
====

[[v5-3-12]]

^<<v5-3-12,12>>^ And we took possession of this land at that particular time; from A·roʹer, which is by the torrent valley of Arʹnon, and^&#42;1^ half of the mountainous region of Gilʹe·ad, and its cities I have given to the Reuʹben·ites and the Gadʹites.

[NOTE]
====
. “And,” MLXXSy; Vg, “as far as.”
====

[[v5-3-13]]

^<<v5-3-13,13>>^ And the rest of Gilʹe·ad and all Baʹshan of the kingdom of Og I have given to the half tribe of Ma·nasʹseh. All the region of Arʹgob of all Baʹshan, is it not called the land of the Rephʹa·im?

[[v5-3-14]]

^<<v5-3-14,14>>^ “Jaʹir the son of Ma·nasʹseh took all the region of Arʹgob as far as the boundary of the Geshʹur·ites and the Ma·acʹa·thites, and he proceeded to call those villages of Baʹshan^&#42;1^ by his own name, Havʹvoth-jaʹir,^&#42;2^ to this day.

[NOTE]
====
. “Call those villages of Bashan.” Lit., “call them Bashan.”
. Meaning “Tent Villages of Jair.”
====

[[v5-3-15]]

^<<v5-3-15,15>>^ And to Maʹchir I have given Gilʹe·ad.

[[v5-3-16]]

^<<v5-3-16,16>>^ And to the Reuʹben·ites and the Gadʹites I have given from Gilʹe·ad to the torrent valley of Arʹnon, the middle of the torrent valley being a boundary, and as far as Jabʹbok, the torrent valley that is the boundary of the sons of Amʹmon;

[[v5-3-17]]

^<<v5-3-17,17>>^ and the Arʹa·bah^&#42;1^ and the Jordan and the border, from Chinʹne·reth to the sea of the Arʹa·bah, the Salt Sea, at the base of the slopes of Pisʹgah toward the sunrising.

[NOTE]
====
. Or, “the desert plains.”
====

[[v5-3-18]]

^<<v5-3-18,18>>^ “So I commanded YOU men at that particular time, saying, ‘Jehovah YOUR God has given YOU this land to take possession of it. YOU will pass over, equipped, before YOUR brothers, the sons of Israel, all the valiant men.^&#42;1^

[NOTE]
====
. Lit., “the sons of ability.”
====

[[v5-3-19]]

^<<v5-3-19,19>>^ Only YOUR wives and YOUR little ones and YOUR livestock (I well know that YOU have a great deal of livestock) will continue dwelling in YOUR cities that I have given YOU,

[[v5-3-20]]

^<<v5-3-20,20>>^ until Jehovah gives YOUR brothers rest, as well as YOU, and they also have taken possession of the land that Jehovah YOUR God is giving them across the Jordan; after which YOU must come back, each one to his holding that I have given YOU.’

[[v5-3-21]]

^<<v5-3-21,21>>^ “And I commanded Joshua at that particular time, saying, ‘Your eyes are seeing all that Jehovah YOUR God has done to these two kings. The same way Jehovah will do to all the kingdoms to which you are passing over there.

[[v5-3-22]]

^<<v5-3-22,22>>^ YOU men must not be afraid of them, for Jehovah YOUR God is the One fighting for YOU.’

[[v5-3-23]]

^<<v5-3-23,23>>^ “And I proceeded to implore favor from Jehovah at that particular time, saying,

[[v5-3-24]]

^<<v5-3-24,24>>^ ‘O Sovereign Lord Jehovah, you yourself have started to make your servant see your greatness and your strong arm, for who is a god^&#42;1^ in the heavens or on the earth that does deeds like yours and mighty performances like yours?

[NOTE]
====
. “A god.” MSam(Heb.), ʼel; Gr., the·osʹ; Lat., Deʹus.
====

[[v5-3-25]]

^<<v5-3-25,25>>^ Let me pass over, please, and see the good land that is across the Jordan, this good mountainous region and Lebʹa·non.’

[[v5-3-26]]

^<<v5-3-26,26>>^ And Jehovah continued to be furious^&#42;1^ against me on YOUR account and did not listen to me; but Jehovah said to me, ‘That is enough of you! Never speak to me further on this matter.

[NOTE]
====
. Or, “Jehovah became furious.”
====

[[v5-3-27]]

^<<v5-3-27,27>>^ Go up to the top of Pisʹgah and raise your eyes to the west and north and south and east and see with your eyes, for you will not pass over this Jordan.

[[v5-3-28]]

^<<v5-3-28,28>>^ And commission Joshua and encourage him and strengthen him, because he is the one to pass over before this people and he is the one to cause them to inherit the land that you will see.’

[[v5-3-29]]

^<<v5-3-29,29>>^ All this while we were dwelling in the valley in front of Beth-peʹor.

'''

xref:005-deuteronomy/005-deuteronomy-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-004.adoc#v5-4-0[Próximo Capítulo &#62;]