include::./index.adoc[]

[[v5-21-0]]
=== Deuteronomy, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-21-1]]

^<<v5-21-1,1>>^ “In case someone is found slain on the ground that Jehovah^&#42;1^ your God is giving you to take possession of it, fallen on the field, and it has not become known who struck him fatally,

[NOTE]
====
. See App 1C §1.
====

[[v5-21-2]]

^<<v5-21-2,2>>^ your older men and your judges must also go out and measure to the cities that are all around the slain one;

[[v5-21-3]]

^<<v5-21-3,3>>^ and it must prove to be the city nearest to the slain one. And the older men of that city must take a young cow of the herd that has not been worked with,^&#42;1^ that has not pulled in a yoke;

[NOTE]
====
. Possibly, “that has not been crossed (mated; impregnated),” by a correction. See VT, Vol. II, 1952, p. 356.
====

[[v5-21-4]]

^<<v5-21-4,4>>^ and the older men of that city must lead the young cow down to a torrent valley running with water in which there was customarily no tilling or sowing of seed, and they must break the neck of the young cow there in the torrent valley.

[[v5-21-5]]

^<<v5-21-5,5>>^ “And the priests the sons of Leʹvi must approach, because they are the ones Jehovah your God has chosen to minister to him and to bless in the name of Jehovah and at whose mouth every dispute over every violent deed^&#42;1^ should be disposed of.

[NOTE]
====
. Lit., “every dispute and every violent deed.” A form of hendiadys. Compare Ge 3:16 ftn.
====

[[v5-21-6]]

^<<v5-21-6,6>>^ Then all the older men of that city who are nearest to the slain one should wash their hands over the young cow, the neck of which was broken in the torrent valley;

[[v5-21-7]]

^<<v5-21-7,7>>^ and they must answer and say, ‘Our hands did not shed this blood, neither did our eyes see &#91;it shed&#93;.

[[v5-21-8]]

^<<v5-21-8,8>>^ Do not set it to the account of your people Israel, whom you redeemed, O Jehovah,^&#42;1^ and do not put the guilt of innocent blood in the midst of your people Israel.’ And the bloodguilt must not be set to their account.

[NOTE]
====
. See App 1C §1.
====

[[v5-21-9]]

^<<v5-21-9,9>>^ And you—you will clear away the guilt of innocent blood from your midst, because you will do what is right in Jehovah’s eyes.

[[v5-21-10]]

^<<v5-21-10,10>>^ “In case you go out to the battle against your enemies and Jehovah your God has given them into your hand and you have carried them away captive;

[[v5-21-11]]

^<<v5-21-11,11>>^ and you have seen among the captives a woman beautiful in form, and you have got attached to her and taken her for your wife,

[[v5-21-12]]

^<<v5-21-12,12>>^ you must then bring her into the midst of your house. She must now shave her head and attend to her nails,

[[v5-21-13]]

^<<v5-21-13,13>>^ and remove the mantle of her captivity from off her and dwell in your house and weep for her father and her mother a whole lunar month;^&#42;1^ and after that you should have relations with her, and you must take possession of her as your bride, and she must become your wife.

[NOTE]
====
. Lit., “a month of days.”
====

[[v5-21-14]]

^<<v5-21-14,14>>^ And it must occur that if you have found no delight in her, you must then send her away, agreeably to her own soul;^&#42;1^ but you must by no means sell her for money. You must not deal tyrannically with her after you have humiliated her.

[NOTE]
====
. “Agreeably to her own soul,” M(Heb., lenaph·shahʹ)SamSy. Or, “agreeably to (for) herself; where she wishes.” LXXVg, “free.”
====

[[v5-21-15]]

^<<v5-21-15,15>>^ “In case a man comes to have two wives, the one loved and the other hated, and they, the loved one and the hated one, have borne sons to him, and the firstborn son has come to be of the hated one,

[[v5-21-16]]

^<<v5-21-16,16>>^ it must also occur that in the day that he gives as an inheritance to his sons what he happens to have, he will not be allowed to constitute the son of the loved one his firstborn at the expense of the hated one’s son, the firstborn.

[[v5-21-17]]

^<<v5-21-17,17>>^ For he should recognize as the firstborn the hated one’s son by giving him two parts in everything he is found to have, because that one is the beginning of his generative power. The right of the firstborn’s position belongs to him.

[[v5-21-18]]

^<<v5-21-18,18>>^ “In case a man happens to have a son who is stubborn and rebellious, he not listening to the voice of his father or the voice of his mother, and they have corrected him but he will not listen to them,

[[v5-21-19]]

^<<v5-21-19,19>>^ his father and his mother must also take hold of him and bring him out to the older men of his city and to the gate of his place,

[[v5-21-20]]

^<<v5-21-20,20>>^ and they must say to the older men of his city, ‘This son of ours is stubborn and rebellious; he is not listening to our voice, being a glutton^&#42;1^ and a drunkard.’

[NOTE]
====
. Or, “being lavish.”
====

[[v5-21-21]]

^<<v5-21-21,21>>^ Then all the men of his city must pelt him with stones, and he must die. So you must clear away what is bad from your midst, and all Israel will hear and indeed become afraid.

[[v5-21-22]]

^<<v5-21-22,22>>^ “And in case there comes to be in a man a sin deserving the sentence of death, and he has been put to death, and you have hung him upon a stake,^&#42;1^

[NOTE]
====
. Lit., “tree”; or, “wood.”
====

[[v5-21-23]]

^<<v5-21-23,23>>^ his dead body should not stay all night on the stake; but you should by all means bury him on that day, because something accursed^&#42;1^ of God is the one hung up; and you must not defile your soil, which Jehovah your God is giving you as an inheritance.

[NOTE]
====
. Lit., “because a malediction [in a concrete sense].”
====

'''

xref:005-deuteronomy/005-deuteronomy-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-022.adoc#v5-22-0[Próximo Capítulo &#62;]