include::./index.adoc[]

[[v5-7-0]]
=== Deuteronomy, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-7-1]]

^<<v5-7-1,1>>^ “When Jehovah your God at last brings you into the land to which you are going so as to take possession of it, he must also clear away populous nations from before you, the Hitʹtites and the Girʹga·shites and the Amʹor·ites and the Caʹnaan·ites and the Perʹiz·zites and the Hiʹvites and the Jebʹu·sites, seven nations more populous and mighty than you are.

[[v5-7-2]]

^<<v5-7-2,2>>^ And Jehovah your God will certainly abandon them to you, and you must defeat them. You should without fail devote them to destruction. You must conclude no covenant with them nor show them any favor.

[[v5-7-3]]

^<<v5-7-3,3>>^ And you must form no marriage alliance with them. Your daughter you must not give to his son, and his daughter you must not take for your son.

[[v5-7-4]]

^<<v5-7-4,4>>^ For he will turn your son from following me, and they will certainly serve other gods; and Jehovah’s anger will indeed blaze against YOU, and he will certainly annihilate you in a hurry.

[[v5-7-5]]

^<<v5-7-5,5>>^ “On the other hand, this is what YOU should do to them: Their altars YOU should pull down, and their sacred pillars YOU should break down, and their sacred poles^&#42;1^ YOU should cut down, and their graven images YOU should burn with fire.

[NOTE]
====
. Or, “their Asherim.”
====

[[v5-7-6]]

^<<v5-7-6,6>>^ For you are a holy people to Jehovah your God. It is you Jehovah your God has chosen to become his people, a special property, out of all the peoples that are on the surface of the ground.

[[v5-7-7]]

^<<v5-7-7,7>>^ “It was not because of YOUR being the most populous of all the peoples that Jehovah showed affection for YOU so that he chose YOU, for YOU were the least of all the peoples.

[[v5-7-8]]

^<<v5-7-8,8>>^ But it was because of Jehovah’s loving YOU, and because of his keeping the sworn statement that he had sworn to YOUR forefathers, that Jehovah brought YOU out with a strong hand, that he might redeem you from the house of slaves, from the hand of Pharʹaoh the king of Egypt.

[[v5-7-9]]

^<<v5-7-9,9>>^ And you well know that Jehovah your God is the &#91;true&#93; God, the faithful God,^&#42;1^ keeping covenant and loving-kindness^&#42;2^ in the case of those who love him and those who keep his commandments to a thousand generations,

[NOTE]
====
. “The faithful God,” M(Heb., ha·ʼElʹ han·ne·ʼemanʹ)Sam; Gr., The·osʹ pi·stosʹ; Lat., Deʹus . . . fi·deʹlis. See App 1G.
. Or, “loyal love.”
====

[[v5-7-10]]

^<<v5-7-10,10>>^ but repaying to his face the one who hates him by destroying him. He will not hesitate toward the one who hates him; he will repay him to his face.

[[v5-7-11]]

^<<v5-7-11,11>>^ And you must keep the commandment and the regulations and the judicial decisions that I am commanding you today by doing them.

[[v5-7-12]]

^<<v5-7-12,12>>^ “And it must occur that, because YOU continue listening to these judicial decisions and YOU do keep them and do carry them out, Jehovah your God must keep toward you the covenant and the loving-kindness about which he swore to your forefathers.

[[v5-7-13]]

^<<v5-7-13,13>>^ And he will certainly love you and bless you and multiply you and bless the fruit of your belly and the fruit of your soil, your grain and your new wine and your oil, the young of your cows and the progeny of your flock, on the soil that he swore to your forefathers to give to you.

[[v5-7-14]]

^<<v5-7-14,14>>^ The most blessed of all the peoples you will become. There will not prove to be in you a male or a female without offspring, nor among your domestic animals.

[[v5-7-15]]

^<<v5-7-15,15>>^ And Jehovah will certainly remove from you every sickness; and as for all the evil diseases of Egypt that you have known, he will not place them upon you, and he will indeed put them upon all those who hate you.

[[v5-7-16]]

^<<v5-7-16,16>>^ And you must consume all the peoples whom Jehovah your God is giving to you. Your eye must not feel sorry for them; and you must not serve their gods, because that will be a snare to you.

[[v5-7-17]]

^<<v5-7-17,17>>^ “In case you say in your heart, ‘These nations are too populous for me. How shall I be able to drive them away?’

[[v5-7-18]]

^<<v5-7-18,18>>^ you must not be afraid of them. You should by all means remember what Jehovah your God did to Pharʹaoh and all Egypt,

[[v5-7-19]]

^<<v5-7-19,19>>^ the great provings that your eyes saw, and the signs and the miracles and the strong hand and the outstretched arm with which Jehovah your God brought you out. That is the way Jehovah your God will do to all the peoples before whom you are afraid.

[[v5-7-20]]

^<<v5-7-20,20>>^ And Jehovah your God will also send the feeling of dejection^&#42;1^ upon them, until those perish who were let remain and who were concealing themselves from before you.

[NOTE]
====
. “The feeling of dejection.” See Ex 23:28 and Jos 24:12 ftns.
====

[[v5-7-21]]

^<<v5-7-21,21>>^ You must not suffer a shock because of them, for Jehovah your God is in your midst, a great and fear-inspiring God.

[[v5-7-22]]

^<<v5-7-22,22>>^ “And Jehovah your God will certainly push these nations away from before you little by little. You will not be allowed to finish them off quickly, for fear the wild beasts of the field may multiply against you.

[[v5-7-23]]

^<<v5-7-23,23>>^ And Jehovah your God will indeed abandon them to you and rout them with a great rout, until they are annihilated.

[[v5-7-24]]

^<<v5-7-24,24>>^ And he will certainly give their kings into your hand, and you must destroy their names from under the heavens. Nobody will take a firm stand against you, until you have exterminated them.

[[v5-7-25]]

^<<v5-7-25,25>>^ The graven images of their gods you should burn in the fire. You must not desire the silver and the gold upon them, nor indeed take it for yourself, for fear you may be ensnared by it; for it is a thing detestable to Jehovah your God.

[[v5-7-26]]

^<<v5-7-26,26>>^ And you must not bring a detestable thing into your house and actually become a thing devoted to destruction^&#42;1^ like it. You should thoroughly loathe it and absolutely detest it, because it is something devoted to destruction.

[NOTE]
====
. “A thing devoted to destruction.” Heb., cheʹrem; Gr. and Lat., a·naʹthe·ma, “an accursed thing.” See Ga 1:8 ftn.
====

'''

xref:005-deuteronomy/005-deuteronomy-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-008.adoc#v5-8-0[Próximo Capítulo &#62;]