include::./index.adoc[]

[[v5-4-0]]
=== Deuteronomy, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v5-4-1]]

^<<v5-4-1,1>>^ “And now, O Israel, listen to the regulations and the judicial decisions that I am teaching YOU to do, in order that YOU may live and may indeed go in and take possession of the land that Jehovah the God of YOUR forefathers is giving YOU.

[[v5-4-2]]

^<<v5-4-2,2>>^ YOU must not add to the word that I am commanding YOU, neither must YOU take away from it, so as to keep the commandments of Jehovah YOUR God that I am commanding YOU.

[[v5-4-3]]

^<<v5-4-3,3>>^ “YOUR own eyes are the ones that saw what Jehovah did in the case of the Baʹal of Peʹor,^&#42;1^ that every man who walked after the Baʹal of Peʹor was the one whom Jehovah your God annihilated from your midst.

[NOTE]
====
. Or, “of Baal-peor.”
====

[[v5-4-4]]

^<<v5-4-4,4>>^ But YOU who are cleaving to Jehovah YOUR God are all of YOU alive today.

[[v5-4-5]]

^<<v5-4-5,5>>^ See, I have taught YOU regulations and judicial decisions, just as Jehovah my God has commanded me, for YOU to do that way in the midst of the land to which YOU are going to take possession of it.

[[v5-4-6]]

^<<v5-4-6,6>>^ And YOU must keep and do them, because this is wisdom on YOUR part and understanding on YOUR part before the eyes of the peoples who will hear of all these regulations, and they will certainly say, ‘This great nation is undoubtedly a wise and understanding people.’

[[v5-4-7]]

^<<v5-4-7,7>>^ For what great nation is there that has gods^&#42;1^ near to it the way Jehovah our God is in all our calling upon him?

[NOTE]
====
. “Gods.” Heb., ʼelo·himʹ, followed by the pl. adjective qero·vimʹ, “near” (Vg is the same); LXX, “God; a god,” followed by a sing. adjective.
====

[[v5-4-8]]

^<<v5-4-8,8>>^ And what great nation is there that has righteous regulations and judicial decisions like all this law that I am putting before YOU today?

[[v5-4-9]]

^<<v5-4-9,9>>^ “Only watch out for yourself and take good care of your soul, that you may not forget the things that your eyes have seen and that they may not depart from your heart all the days of your life; and you must make them known to your sons and to your grandsons,^&#42;1^

[NOTE]
====
. Lit., “your sons’ sons.”
====

[[v5-4-10]]

^<<v5-4-10,10>>^ the day that you stood before Jehovah your God in Hoʹreb,^&#42;1^ when Jehovah said to me, ‘Congregate^&#42;2^ the people together to me that I may let them hear my words, that they may learn to fear me all the days that they are alive on the soil and that they may teach their sons.’

[NOTE]
====
. LXX adds, “in the day of the assembly [Gr., ek·kle·siʹas],” the first occurrence of this word in LXX.
. Or, “Assemble.” Gr., Ek·kle·siʹa·son; Lat., conʹgre·ga.
====

[[v5-4-11]]

^<<v5-4-11,11>>^ “So YOU people came near and stood at the base of the mountain, and the mountain was burning with fire up to midheaven;^&#42;1^ there was darkness, cloud and thick gloom.

[NOTE]
====
. Lit., “up to the heart of the heavens.”
====

[[v5-4-12]]

^<<v5-4-12,12>>^ And Jehovah began to speak to YOU out of the middle of the fire. The sound of words was what YOU were hearing, but no form were YOU seeing—nothing but a voice.

[[v5-4-13]]

^<<v5-4-13,13>>^ And he proceeded to state to YOU his covenant, which he commanded YOU to perform—the Ten Words,^&#42;1^ after which he wrote them upon two tablets of stone.

[NOTE]
====
. “The Ten Words (Decalogue),” commonly called the Ten Commandments. Heb., ʽaseʹreth had·deva·rimʹ; Gr., deʹka rheʹma·ta, “Ten Sayings”; Lat., deʹcem verʹba. See 10:4 ftn; Ex 34:28 ftn, “Words.”
====

[[v5-4-14]]

^<<v5-4-14,14>>^ And it was I whom Jehovah commanded at that particular time to teach YOU regulations and judicial decisions, for YOU to do them in the land to which YOU are passing over to take possession of it.

[[v5-4-15]]

^<<v5-4-15,15>>^ “And YOU must take good care of YOUR souls, because YOU did not see any form on the day of Jehovah’s speaking to YOU in Hoʹreb out of the middle of the fire,

[[v5-4-16]]

^<<v5-4-16,16>>^ that YOU may not act ruinously and may not really make for yourselves a carved image, the form of any symbol, the representation of male or female,

[[v5-4-17]]

^<<v5-4-17,17>>^ the representation of any beast that is in the earth, the representation of any winged bird that flies in the heavens,

[[v5-4-18]]

^<<v5-4-18,18>>^ the representation of anything moving on the ground, the representation of any fish that is in the waters under the earth;

[[v5-4-19]]

^<<v5-4-19,19>>^ and that you may not raise your eyes to the heavens and indeed see the sun and the moon and the stars, all the army of the heavens, and actually get seduced and bow down to them and serve them,^&#42;1^ which Jehovah your God has apportioned to all the peoples under the whole heavens.

[NOTE]
====
. “And serve (worship) them.” Heb., wa·ʽavadh·tamʹ; Gr., la·treuʹseis, “you will render sacred service.” See Ex 3:12 ftn.
====

[[v5-4-20]]

^<<v5-4-20,20>>^ But YOU are the ones Jehovah took that he might bring YOU out of the iron furnace, out of Egypt, to become a people of private ownership^&#42;1^ to him as at this day.

[NOTE]
====
. Or, “people of inheritance.”
====

[[v5-4-21]]

^<<v5-4-21,21>>^ “And Jehovah got incensed at me on YOUR account, so that he swore that I should not cross the Jordan or go into the good land that Jehovah your God is giving you as an inheritance.

[[v5-4-22]]

^<<v5-4-22,22>>^ For I am dying in this land. I am not crossing the Jordan, but YOU are crossing, and YOU must take possession of this good land.

[[v5-4-23]]

^<<v5-4-23,23>>^ Watch out for yourselves that YOU may not forget the covenant of Jehovah YOUR God that he concluded with YOU and that YOU do not make for yourselves a carved image, the form of anything about which Jehovah your God has commanded you.

[[v5-4-24]]

^<<v5-4-24,24>>^ For Jehovah your God is a consuming fire, a God exacting exclusive devotion.^&#42;1^

[NOTE]
====
. “A God exacting exclusive devotion.” MSam(Heb.), ʼEl qan·naʼʹ; Gr., The·osʹ ze·lo·tesʹ.
====

[[v5-4-25]]

^<<v5-4-25,25>>^ “In case you^&#42;1^ become father to sons and grandsons and YOU have resided a long time in the land and do act ruinously and do make a carved image, a form of anything, and do commit evil in the eyes of Jehovah your God so as to offend him,

[NOTE]
====
. “You,” sing., MLXX; SamSyItVg, “you,” pl.
====

[[v5-4-26]]

^<<v5-4-26,26>>^ I do take as witnesses against YOU today the heavens and the earth, that YOU will positively perish in a hurry from off the land to which YOU are crossing the Jordan to take possession of it. YOU will not lengthen YOUR days on it, because YOU will positively be annihilated.

[[v5-4-27]]

^<<v5-4-27,27>>^ And Jehovah will certainly scatter YOU among the peoples, and YOU will indeed be let remain few in number among the nations to which Jehovah will drive YOU away.

[[v5-4-28]]

^<<v5-4-28,28>>^ And there YOU will have to serve gods, the product of the hands of man, wood and stone, which cannot see or hear or eat or smell.

[[v5-4-29]]

^<<v5-4-29,29>>^ “If YOU do look for Jehovah your God from there, you will also certainly find him, because you will inquire for him with all your heart and with all your soul.

[[v5-4-30]]

^<<v5-4-30,30>>^ When you are in sore straits and all these words have found you out at the close of the days, then you will have to return to Jehovah your God and to listen to his voice.

[[v5-4-31]]

^<<v5-4-31,31>>^ For Jehovah your God is a merciful God. He will not desert you or bring you to ruin or forget the covenant of your forefathers that he swore to them.

[[v5-4-32]]

^<<v5-4-32,32>>^ “Now ask, please, concerning the former days that occurred before you, from the day that God created man^&#42;1^ on the earth and from one end of the heavens clear to the other end of the heavens, Was any great thing brought about like this or was anything heard like it?

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
====

[[v5-4-33]]

^<<v5-4-33,33>>^ Has any other people heard the voice of God^&#42;1^ speaking out of the middle of the fire the way you yourself have heard it, and kept on living?

[NOTE]
====
. “God,” MVg; SamLXX, “the living God.”
====

[[v5-4-34]]

^<<v5-4-34,34>>^ Or did God attempt to come to take a nation to himself out of the midst of another nation with provings, with signs and with miracles and with war and with a strong hand and with an outstretched arm and with great fearsomeness like all that Jehovah YOUR God has done for YOU in Egypt before your eyes?

[[v5-4-35]]

^<<v5-4-35,35>>^ You—you have been shown, so as to know that Jehovah is the &#91;true&#93; God; there is no other besides him.

[[v5-4-36]]

^<<v5-4-36,36>>^ Out of the heavens he made you hear his voice so as to correct you; and upon the earth he made you see his great fire, and his words you heard from the middle of the fire.

[[v5-4-37]]

^<<v5-4-37,37>>^ “And &#91;yet you continue to live&#93;, because^&#42;1^ he loved your forefathers so that he chose their seed after them^&#42;2^ and brought you out of Egypt in his sight with his great power,

[NOTE]
====
. “And yet you continue to live, because,” the probable reading of the Heb., to agree with vs 33 and 5:26; LXXVg, “Because.”
. “Their seed after them,” SamLXXSyVg; M, “his seed after him.”
====

[[v5-4-38]]

^<<v5-4-38,38>>^ to drive away nations greater and mightier than you from before you, so as to bring you in, to give you their land as an inheritance as at this day.

[[v5-4-39]]

^<<v5-4-39,39>>^ And you well know today, and you must call back to your heart^&#42;1^ that Jehovah is the &#91;true&#93; God in the heavens above and on the earth beneath. There is no other.

[NOTE]
====
. Or, “must recall to your mind.”
====

[[v5-4-40]]

^<<v5-4-40,40>>^ And you must keep his regulations and his commandments that I am commanding you today, that it may go well with you and your sons after you, and in order that you may lengthen your days on the soil that Jehovah your God is giving you, always.”

[[v5-4-41]]

^<<v5-4-41,41>>^ At that time Moses proceeded to set apart three cities on the side of the Jordan toward the rising of the sun,

[[v5-4-42]]

^<<v5-4-42,42>>^ for the manslayer to flee there who slays his fellow without knowing it, while he was not hating him formerly; and he must flee to one of these cities and live,

[[v5-4-43]]

^<<v5-4-43,43>>^ namely, Beʹzer in the wilderness on the tableland for the Reuʹben·ites, and Raʹmoth in Gilʹe·ad for the Gadʹites, and Goʹlan in Baʹshan for the Ma·nasʹsites.

[[v5-4-44]]

^<<v5-4-44,44>>^ Now this is the law that Moses set before the sons of Israel.

[[v5-4-45]]

^<<v5-4-45,45>>^ These are the testimonies^&#42;1^ and the regulations and the judicial decisions that Moses spoke to the sons of Israel on their coming out of Egypt,

[NOTE]
====
. Or, “reminders; exhortations.”
====

[[v5-4-46]]

^<<v5-4-46,46>>^ in the region of the Jordan in the valley in front of Beth-peʹor, in the land of Siʹhon the king of the Amʹor·ites, who was dwelling in Heshʹbon, whom Moses and the sons of Israel defeated on their coming out of Egypt.

[[v5-4-47]]

^<<v5-4-47,47>>^ And they went taking possession of his land and of the land of Og the king of Baʹshan, the two kings of the Amʹor·ites who were in the region of the Jordan toward the rising of the sun,

[[v5-4-48]]

^<<v5-4-48,48>>^ from A·roʹer, which is on the bank of the torrent valley of Arʹnon, up to Mount Siʹon,^&#42;1^ that is to say, Herʹmon,

[NOTE]
====
. “Si­on,” MSamLXXVg; Sy, “Sirion.” See 3:9 ftn.
====

[[v5-4-49]]

^<<v5-4-49,49>>^ and all the Arʹa·bah in the region of the Jordan toward the east, and as far as the sea of the Arʹa·bah at the base of the slopes of Pisʹgah.

'''

xref:005-deuteronomy/005-deuteronomy-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomy/005-deuteronomy-005.adoc#v5-5-0[Próximo Capítulo &#62;]