include::./index.adoc[]

[[v50-2-0]]
=== To the Philippians, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v50-2-1]]

^<<v50-2-1,1>>^ If, then, there is any encouragement in Christ, if any consolation of love, if any sharing of spirit, if any tender affections and compassions,

[[v50-2-2]]

^<<v50-2-2,2>>^ make my joy full in that YOU are of the same mind and have the same love, being joined together in soul, holding the one thought in mind,

[[v50-2-3]]

^<<v50-2-3,3>>^ doing nothing out of contentiousness or out of egotism, but with lowliness of mind considering that the others are superior to YOU,

[[v50-2-4]]

^<<v50-2-4,4>>^ keeping an eye, not in personal interest upon just YOUR own matters,^&#42;1^ but also in personal interest upon those of the others.

[NOTE]
====
. Lit., “not the (things) of selves each (ones).”
====

[[v50-2-5]]

^<<v50-2-5,5>>^ Keep this mental attitude^&#42;1^ in YOU that was also in Christ Jesus,

[NOTE]
====
. Lit., “This be you minding.”
====

[[v50-2-6]]

^<<v50-2-6,6>>^ who, although he was existing in God’s form, gave no consideration to a seizure,^&#42;1^ namely, that he should be equal to God.

[NOTE]
====
. Or, “thing to be seized.” Lit., “snatching.”
====

[[v50-2-7]]

^<<v50-2-7,7>>^ No, but he emptied himself and took a slave’s form and came to be in the likeness of men.

[[v50-2-8]]

^<<v50-2-8,8>>^ More than that, when he found himself in fashion as a man, he humbled himself and became obedient as far as death, yes, death on a torture stake.^&#42;1^

[NOTE]
====
. See App 5C.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ For this very reason also God exalted him to a superior position and kindly gave him the name that is above every &#91;other&#93; name,

[[v50-2-10]]

^<<v50-2-10,10>>^ so that in the name of Jesus every knee should bend of those in heaven and those on earth and those under the ground,

[[v50-2-11]]

^<<v50-2-11,11>>^ and every tongue should openly acknowledge^&#42;1^ that Jesus Christ is Lord to the glory of God the Father.

[NOTE]
====
. Lit., “should confess out.”
====

[[v50-2-12]]

^<<v50-2-12,12>>^ Consequently, my beloved ones, in the way that YOU have always obeyed, not during my presence only, but now much more readily during my absence, keep working out YOUR own salvation with fear and trembling;

[[v50-2-13]]

^<<v50-2-13,13>>^ for God is the one that, for the sake of &#91;his&#93; good pleasure, is acting within YOU in order for YOU both to will and to act.

[[v50-2-14]]

^<<v50-2-14,14>>^ Keep doing all things free from murmurings and arguments,^&#42;1^

[NOTE]
====
. Lit., “divided reckonings.”
====

[[v50-2-15]]

^<<v50-2-15,15>>^ that YOU may come to be blameless and innocent, children of God without a blemish in among a crooked and twisted generation, among whom YOU are shining as illuminators in the world,

[[v50-2-16]]

^<<v50-2-16,16>>^ keeping a tight grip on the word of life, that I may have cause for exultation in Christ’s day, that I did not run in vain or work hard in vain.

[[v50-2-17]]

^<<v50-2-17,17>>^ Notwithstanding, even if I am^&#42;1^ being poured out like a drink offering^&#42;2^ upon the sacrifice and public service to which faith has led YOU, I am glad and I rejoice with all of YOU.^&#42;3^

[NOTE]
====
. Or, “my life is; my blood is.”
. “Drink offering.” Or, “libation.”
. “I congratulate all of you,” Vg.
====

[[v50-2-18]]

^<<v50-2-18,18>>^ Now in the same way YOU yourselves also be glad and rejoice with me.^&#42;1^

[NOTE]
====
. “And congratulate me,” Vg.
====

[[v50-2-19]]

^<<v50-2-19,19>>^ For my part I am hoping in the Lord Jesus to send Timothy to YOU shortly, that I may be a cheerful soul when I get to know about the things pertaining to YOU.

[[v50-2-20]]

^<<v50-2-20,20>>^ For I have no one else of a disposition like his who will genuinely care for the things pertaining to YOU.

[[v50-2-21]]

^<<v50-2-21,21>>^ For all the others are seeking their own interests, not those of Christ Jesus.

[[v50-2-22]]

^<<v50-2-22,22>>^ But YOU know the proof he gave of himself, that like a child with a father he slaved with me in furtherance of the good news.

[[v50-2-23]]

^<<v50-2-23,23>>^ This, therefore, is the man I am hoping to send just as soon as I have seen how things stand concerning me.

[[v50-2-24]]

^<<v50-2-24,24>>^ Indeed, I am confident^&#42;1^ in &#91;the&#93; Lord that I myself shall also come shortly.

[NOTE]
====
. Or, “I trust.”
====

[[v50-2-25]]

^<<v50-2-25,25>>^ However, I consider it necessary to send to YOU E·paph·ro·diʹtus, my brother and fellow worker and fellow soldier, but YOUR envoy^&#42;1^ and private servant for my need,

[NOTE]
====
. Or, “apostle.” Gr., a·poʹsto·lon.
====

[[v50-2-26]]

^<<v50-2-26,26>>^ since he is longing to see all of YOU^&#42;1^ and is depressed because YOU heard he had fallen sick.

[NOTE]
====
. “Longing to see all of you,” א*ACDSyh,hi,pArm; אcBVg, “longing for all of you.”
====

[[v50-2-27]]

^<<v50-2-27,27>>^ Yes, indeed, he fell sick nearly to the point of death; but God had mercy on him, in fact, not only on him, but also on me, that I should not get grief upon grief.

[[v50-2-28]]

^<<v50-2-28,28>>^ Therefore with the greater haste I am sending him, that on seeing him YOU may rejoice again and I may be the more free from grief.

[[v50-2-29]]

^<<v50-2-29,29>>^ Therefore give him the customary welcome in &#91;the&#93; Lord with all joy; and keep holding men of that sort dear,

[[v50-2-30]]

^<<v50-2-30,30>>^ because on account of the Lord’s^&#42;1^ work he came quite near to death, exposing his soul^&#42;2^ to danger, that he might fully make up for YOUR not being here to render private service to me.

[NOTE]
====
. “Lord’s,” אA; P46BDItVgSyp, “Christ’s.”
. Or, “life.”
====

'''

xref:050-philippians/050-philippians-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-philippians/050-philippians-003.adoc#v50-3-0[Próximo Capítulo &#62;]