include::./index.adoc[]

[[v50-3-0]]
=== To the Philippians, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v50-3-1]]

^<<v50-3-1,1>>^ Finally, my brothers, continue rejoicing in &#91;the&#93; Lord. To be writing the same things to YOU is not troublesome for me, but it is of safety to YOU.

[[v50-3-2]]

^<<v50-3-2,2>>^ Look out for the dogs, look out for the workers of injury, look out for those who mutilate the flesh.^&#42;1^

[NOTE]
====
. “Those who mutilate the flesh.” Or, “the incision.” Lit., “the cutting down.”
====

[[v50-3-3]]

^<<v50-3-3,3>>^ For we are those with the real circumcision,^&#42;1^ who are rendering sacred service^&#42;2^ by God’s spirit and have our boasting in Christ Jesus and do not have our confidence in the flesh,

[NOTE]
====
. Lit., “we are the circumcision.”
. “Rendering sacred service.” Gr., la·treuʹon·tes; J17(Heb.), ha·ʽo·vedhimʹ, “who serve (worship).” See Ex 3:12 ftn.
====

[[v50-3-4]]

^<<v50-3-4,4>>^ though I, if anyone, do have grounds for confidence also in the flesh.
If any other man thinks he has grounds for confidence in the flesh, I the more so:

[[v50-3-5]]

^<<v50-3-5,5>>^ circumcised the eighth day, out of the family stock of Israel, of the tribe of Benjamin, a Hebrew &#91;born&#93; from Hebrews; as respects law, a Pharisee;

[[v50-3-6]]

^<<v50-3-6,6>>^ as respects zeal, persecuting the congregation; as respects righteousness that is by means of law, one who proved himself blameless.

[[v50-3-7]]

^<<v50-3-7,7>>^ Yet what things were gains to me, these I have considered loss on account of the Christ.

[[v50-3-8]]

^<<v50-3-8,8>>^ Why, for that matter, I do indeed also consider all things to be loss on account of the excelling value of the knowledge of Christ Jesus my Lord. On account of him I have taken the loss of all things and I consider them as a lot of refuse, that I may gain Christ

[[v50-3-9]]

^<<v50-3-9,9>>^ and be found in union with him, having, not my own righteousness, which results from law, but that which is through faith in Christ, the righteousness that issues from God on the basis of faith,

[[v50-3-10]]

^<<v50-3-10,10>>^ so as to know him and the power of his resurrection and a sharing in his sufferings, submitting myself to a death like his,

[[v50-3-11]]

^<<v50-3-11,11>>^ &#91;to see&#93; if I may by any means attain to the earlier resurrection^&#42;1^ from the dead.

[NOTE]
====
. “Earlier resurrection.” Lit., “out-resurrection.” Gr., e·xa·naʹsta·sin.
====

[[v50-3-12]]

^<<v50-3-12,12>>^ Not that I have already received it or am already made perfect, but I am pursuing to see if I may also lay hold on that for which I have also been laid hold on by Christ Jesus.^&#42;1^

[NOTE]
====
. “Jesus,” P46אAVg; BD omit.
====

[[v50-3-13]]

^<<v50-3-13,13>>^ Brothers, I do not yet consider myself as having laid hold on &#91;it&#93;; but there is one thing about it: Forgetting the things behind and stretching forward to the things ahead,

[[v50-3-14]]

^<<v50-3-14,14>>^ I am pursuing down toward the goal for the prize^&#42;1^ of the upward call of God by means of Christ Jesus.

[NOTE]
====
. Lit., “into the prize.”
====

[[v50-3-15]]

^<<v50-3-15,15>>^ Let us, then, as many of us as are mature, be of this mental attitude; and if YOU are mentally inclined otherwise in any respect, God will reveal the above &#91;attitude&#93; to YOU.

[[v50-3-16]]

^<<v50-3-16,16>>^ At any rate, to what extent we have made progress, let us go on walking orderly in this same routine.^&#42;1^

[NOTE]
====
. Lit., “to the same walking in line.”
====

[[v50-3-17]]

^<<v50-3-17,17>>^ Unitedly become imitators of me, brothers, and keep YOUR eye on those who are walking in a way that accords with the example YOU have in us.

[[v50-3-18]]

^<<v50-3-18,18>>^ For there are many, I used to mention them often but now I mention them also with weeping, who are walking as the enemies of the torture stake^&#42;1^ of the Christ,

[NOTE]
====
. See App 5C.
====

[[v50-3-19]]

^<<v50-3-19,19>>^ and their finish^&#42;1^ is destruction, and their god is their belly, and their glory consists in their shame, and they have their minds upon things on the earth.

[NOTE]
====
. Or, “end; accomplished end.” Gr., teʹlos.
====

[[v50-3-20]]

^<<v50-3-20,20>>^ As for us, our citizenship^&#42;1^ exists in the heavens, from which place also we are eagerly waiting for a savior, the Lord Jesus Christ,

[NOTE]
====
. Or, “our life as citizens.”
====

[[v50-3-21]]

^<<v50-3-21,21>>^ who will refashion our humiliated body^&#42;1^ to be conformed to his glorious body^&#42;2^ according to the operation of the power that he has, even to subject all things to himself.

[NOTE]
====
. Lit., “the body of our lowliness.”
. Lit., “the body of his glory.”
====

'''

xref:050-philippians/050-philippians-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-philippians/050-philippians-004.adoc#v50-4-0[Próximo Capítulo &#62;]