include::./index.adoc[]

[[v50-4-0]]
=== To the Philippians, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v50-4-1]]

^<<v50-4-1,1>>^ Consequently, my brothers beloved and longed for, my joy and crown, stand firm in this way in &#91;the&#93; Lord,^&#42;1^ beloved ones.

[NOTE]
====
. “Lord,” אABVg; J7,​8,​13,​14,​16,​24, “Jehovah.”
====

[[v50-4-2]]

^<<v50-4-2,2>>^ Eu·oʹdi·a I exhort and Synʹty·che I exhort to be of the same mind in &#91;the&#93; Lord.

[[v50-4-3]]

^<<v50-4-3,3>>^ Yes, I request you too, genuine yokefellow, keep assisting these &#91;women&#93; who have striven side by side with me in the good news along with Clement as well as the rest of my fellow workers, whose names are in the book of life.

[[v50-4-4]]

^<<v50-4-4,4>>^ Always rejoice in &#91;the&#93; Lord.^&#42;1^ Once more I will say, Rejoice!

[NOTE]
====
. “Lord,” אABVg; J7,​8,​13,​14,​16,​24, “Jehovah.”
====

[[v50-4-5]]

^<<v50-4-5,5>>^ Let YOUR reasonableness become known to all men. The Lord^&#42;1^ is near.

[NOTE]
====
. “The Lord,” אABVg; J7,​8, “Jehovah.”
====

[[v50-4-6]]

^<<v50-4-6,6>>^ Do not be anxious over anything, but in everything by prayer and supplication along with thanksgiving let YOUR petitions be made known to God;

[[v50-4-7]]

^<<v50-4-7,7>>^ and the peace of God that excels all thought will guard YOUR hearts and YOUR mental powers by means of Christ Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Finally, brothers, whatever things^&#42;1^ are true, whatever things are of serious concern, whatever things are righteous, whatever things are chaste, whatever things are lovable,^&#42;2^ whatever things are well spoken of, whatever virtue there is and whatever praiseworthy thing there is, continue considering these things.

[NOTE]
====
. Lit., “as many (things) as.”
. Lit., “affection-inducing.”
====

[[v50-4-9]]

^<<v50-4-9,9>>^ The things that YOU learned as well as accepted and heard and saw in connection with me, practice these; and the God of peace will be with you.

[[v50-4-10]]

^<<v50-4-10,10>>^ I do rejoice greatly in &#91;the&#93; Lord^&#42;1^ that now at last YOU have revived YOUR thinking in my behalf, to which YOU were really giving thought, but YOU lacked opportunity.

[NOTE]
====
. “Lord,” אABVg; J7,​8,​13,​14,​16,​24, “Jehovah.”
====

[[v50-4-11]]

^<<v50-4-11,11>>^ Not that I am speaking with regard to being in want, for I have learned, in whatever circumstances I am, to be self-sufficient.^&#42;1^

[NOTE]
====
. Or, “content.”
====

[[v50-4-12]]

^<<v50-4-12,12>>^ I know indeed how to be low &#91;on provisions&#93;, I know indeed how to have an abundance. In everything and in all circumstances I have learned the secret of both how to be full and how to hunger, both how to have an abundance and how to suffer want.

[[v50-4-13]]

^<<v50-4-13,13>>^ For all things I have the strength by virtue of him who imparts power to me.

[[v50-4-14]]

^<<v50-4-14,14>>^ Nevertheless, YOU acted well in becoming sharers with me in my tribulation.

[[v50-4-15]]

^<<v50-4-15,15>>^ In fact, YOU Phi·lipʹpi·ans, also know that at &#91;the&#93; start of declaring the good news, when I departed from Mac·e·doʹni·a, not a congregation took a share with me in the matter of giving and receiving, except YOU alone;

[[v50-4-16]]

^<<v50-4-16,16>>^ because, even in Thes·sa·lo·niʹca, YOU sent something to me both once and a second time for my need.

[[v50-4-17]]

^<<v50-4-17,17>>^ Not that I am earnestly seeking the gift, but that I am earnestly seeking the fruitage that brings more credit to YOUR account.

[[v50-4-18]]

^<<v50-4-18,18>>^ However, I have all things in full and have an abundance. I am filled, now that I have received from E·paph·ro·diʹtus the things from YOU, a sweet-smelling odor, an acceptable sacrifice, well-pleasing to God.^&#42;1^

[NOTE]
====
. “God,” אABVgSyp; J7,​8, “Jehovah.”
====

[[v50-4-19]]

^<<v50-4-19,19>>^ In turn, my God will fully supply all YOUR need to the extent of his riches in glory by means of Christ Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ Now to our God and Father be the glory forever and ever. Amen.

[[v50-4-21]]

^<<v50-4-21,21>>^ Give my greetings to every holy one in union with Christ Jesus. The brothers who are with me send YOU their greetings.

[[v50-4-22]]

^<<v50-4-22,22>>^ All the holy ones, but especially those of the household of Caesar,^&#42;1^ send YOU their greetings.

[NOTE]
====
. Or, “the emperor.”
====

[[v50-4-23]]

^<<v50-4-23,23>>^ The undeserved kindness of the Lord Jesus Christ &#91;be&#93; with the spirit YOU &#91;show&#93;.^&#42;1^

[NOTE]
====
. P46אADItVgSyh,pArm close with “Amen”; B omits.
====

'''

xref:050-philippians/050-philippians-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossians/051-colossians-001.adoc#v51-1-0[Próximo Capítulo &#62;]