include::./index.adoc[]

[[v50-1-0]]
=== To the Philippians, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v50-1-1]]

^<<v50-1-1,1>>^ Paul and Timothy, slaves of Christ Jesus, to all the holy ones in union with Christ Jesus who are in Phi·lipʹpi, along with overseers^&#42;1^ and ministerial servants:^&#42;2^

[NOTE]
====
. “Overseers.” Gr., e·pi·skoʹpois, dative, pl.; J17(Heb.), hap·peqi·dhimʹ, “the overseers.”
. Or, “deacons.” Gr., di·a·koʹnois, dative, pl.; Lat., di·aʹco·nis.
====

[[v50-1-2]]

^<<v50-1-2,2>>^ May YOU have undeserved kindness and peace from God our Father and &#91;the&#93; Lord Jesus Christ.

[[v50-1-3]]

^<<v50-1-3,3>>^ I thank my God always upon every remembrance of YOU

[[v50-1-4]]

^<<v50-1-4,4>>^ in every supplication of mine for all of YOU, as I offer my supplication with joy,

[[v50-1-5]]

^<<v50-1-5,5>>^ because of the contribution YOU have made to the good news from the first day until this moment.

[[v50-1-6]]

^<<v50-1-6,6>>^ For I am confident of this very thing, that he who started a good work in YOU will carry it to completion until the day of Jesus Christ.

[[v50-1-7]]

^<<v50-1-7,7>>^ It is altogether right for me to think this regarding all of YOU, on account of my having YOU in my heart, all of YOU being sharers with me in the undeserved kindness, both in my &#91;prison&#93; bonds and in the defending and legally establishing of the good news.

[[v50-1-8]]

^<<v50-1-8,8>>^ For God is my witness of how I am yearning for all of YOU in such tender affection as Christ Jesus has.

[[v50-1-9]]

^<<v50-1-9,9>>^ And this is what I continue praying, that YOUR love may abound yet more and more with accurate knowledge^&#42;1^ and full discernment;^&#42;2^

[NOTE]
====
. Lit., “in accurate knowledge.” Gr., en e·pi·gnoʹsei; Lat., in sci·enʹti·a.
. Lit., “sense perception.” Gr., ai·stheʹsei; Lat., senʹsu.
====

[[v50-1-10]]

^<<v50-1-10,10>>^ that YOU may make sure of the more important things, so that YOU may be flawless and not be stumbling others up to the day of Christ,

[[v50-1-11]]

^<<v50-1-11,11>>^ and may be filled with righteous fruit, which is through Jesus Christ, to God’s glory and praise.

[[v50-1-12]]

^<<v50-1-12,12>>^ Now I desire YOU to know, brothers, that my affairs have turned out for the advancement of the good news rather than otherwise,

[[v50-1-13]]

^<<v50-1-13,13>>^ so that my bonds have become public knowledge in association with Christ among all the Prae·toʹri·an Guard^&#42;1^ and all the rest;

[NOTE]
====
. The bodyguard of the Roman emperor.
====

[[v50-1-14]]

^<<v50-1-14,14>>^ and most of the brothers in &#91;the&#93; Lord, feeling confidence by reason of my &#91;prison&#93; bonds, are showing all the more courage to speak the word of God fearlessly.

[[v50-1-15]]

^<<v50-1-15,15>>^ True, some are preaching the Christ through envy and rivalry, but others also through goodwill.

[[v50-1-16]]

^<<v50-1-16,16>>^ The latter are publicizing the Christ out of love, for they know I am set here for the defense of the good news;

[[v50-1-17]]

^<<v50-1-17,17>>^ but the former do it out of contentiousness, not with a pure motive, for they are supposing to stir up tribulation &#91;for me&#93; in my &#91;prison&#93; bonds.

[[v50-1-18]]

^<<v50-1-18,18>>^ What then? &#91;Nothing,&#93; except that in every way, whether in pretense or in truth, Christ is being publicized, and in this I rejoice. In fact, I will also keep on rejoicing,

[[v50-1-19]]

^<<v50-1-19,19>>^ for I know this will result in my salvation^&#42;1^ through YOUR supplication and a supply of the spirit of Jesus Christ,

[NOTE]
====
. Or, “my being released.”
====

[[v50-1-20]]

^<<v50-1-20,20>>^ in harmony with my eager expectation and hope that I shall not be ashamed in any respect, but that in all freeness of speech Christ will, as always before, so now be magnified by means of my body, whether through life or through death.

[[v50-1-21]]

^<<v50-1-21,21>>^ For in my case to live is Christ, and to die, gain.

[[v50-1-22]]

^<<v50-1-22,22>>^ Now if it be to live on in the flesh, this is a fruitage of my work—and yet which thing to select I do not make known.^&#42;1^

[NOTE]
====
. Or, “thing to choose I do not know.”
====

[[v50-1-23]]

^<<v50-1-23,23>>^ I am under pressure from these two things; but what I do desire is the releasing^&#42;1^ and the being with Christ, for this, to be sure, is far better.

[NOTE]
====
. For a discussion of “the releasing,” see App 5D.
====

[[v50-1-24]]

^<<v50-1-24,24>>^ However, for me to remain in the flesh is more necessary on YOUR account.

[[v50-1-25]]

^<<v50-1-25,25>>^ So, being confident of this, I know I shall remain and shall abide with all of YOU for YOUR advancement and the joy that belongs to &#91;YOUR&#93; faith,

[[v50-1-26]]

^<<v50-1-26,26>>^ so that YOUR exultation may overflow in Christ Jesus by reason of me through my presence^&#42;1^ again with YOU.

[NOTE]
====
. See App 5B.
====

[[v50-1-27]]

^<<v50-1-27,27>>^ Only behave^&#42;1^ in a manner worthy of the good news about the Christ, in order that, whether I come and see YOU or be absent, I may hear about the things which concern YOU, that YOU are standing firm in one spirit, with one soul^&#42;2^ striving side by side for the faith of the good news,

[NOTE]
====
. Or, “carry on as citizens.”
. Or, “as one man.”
====

[[v50-1-28]]

^<<v50-1-28,28>>^ and in no respect being frightened by YOUR opponents. This very thing is a proof of destruction for them, but of salvation for YOU; and this &#91;indication&#93; is from God,

[[v50-1-29]]

^<<v50-1-29,29>>^ because to YOU the privilege was given in behalf of Christ, not only to put YOUR faith in him, but also to suffer in his behalf.

[[v50-1-30]]

^<<v50-1-30,30>>^ For YOU have the same struggle as YOU saw in my case and as YOU now hear about in my case.

'''

xref:049-ephesians/049-ephesians-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-philippians/050-philippians-002.adoc#v50-2-0[Próximo Capítulo &#62;]