include::./index.adoc[]

[[v25-1-0]]
=== Lamentations, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_א &#91;ʼAʹleph&#93;^&#42;1^_

[[v25-1-1]]

^<<v25-1-1,1>>^ ^&#42;1^ O how she has come to sit solitary, the city that was abundant with people!
How she has become like a widow, she that was populous among the nations!
How she that was a princess among the jurisdictional districts has come to be for forced labor!

[NOTE]
====
. LXX gives the following introduction to vs 1: “And it occurred that, after Israel had been taken captive and Jerusalem had been desolated, Jeremiah sat down weeping and lamented with this lamentation over Jerusalem and said.” Vgmss introduce as follows: “And it occurred that, after Israel had been led away into captivity and Jerusalem was deserted, Jeremiah the prophet sat weeping and wailed with this lamentation over Jerusalem; and sighing with a bitter spirit, and moaning woefully, he said.” T introduces as follows: “Jeremiah the prophet and great priest said.”
====

_ב &#91;Behth&#93;_

[[v25-1-2]]

^<<v25-1-2,2>>^ Profusely she weeps during the night, and her tears are upon her cheeks.
She has no one to comfort her from among all her lovers.
All her very own companions have dealt treacherously with her. They have become enemies to her.

_ג &#91;Giʹmel&#93;_

[[v25-1-3]]

^<<v25-1-3,3>>^ Judah has gone into exile because of the affliction and because of the abundance of servitude.
She herself has had to dwell among the nations. No resting-place has she found.
All those who were persecuting^&#42;1^ her have overtaken her among distressing circumstances.

[NOTE]
====
. Or, “pursuing.”
====

_ד &#91;Daʹleth&#93;_

[[v25-1-4]]

^<<v25-1-4,4>>^ The ways of Zion are mourning, because there are none coming to the festival.
All her gates are laid desolate; her priests are sighing.
Her virgins are grief-stricken, and she herself has bitterness.

_ה &#91;Heʼ&#93;_

[[v25-1-5]]

^<<v25-1-5,5>>^ Her adversaries have become the head. Those who are her enemies are unconcerned.
Because Jehovah himself has brought grief to her on account of the abundance of her transgressions,
Her own children have walked captive before the adversary.

_ו &#91;Waw&#93;_

[[v25-1-6]]

^<<v25-1-6,6>>^ And from the daughter of Zion there goes out all her splendor.
Her princes have proved to be like stags that have found no pasturage;
And they keep walking without power before the pursuer.^&#42;1^

[NOTE]
====
. Or, “persecutor.”
====

_ז &#91;Zaʹyin&#93;_

[[v25-1-7]]

^<<v25-1-7,7>>^ Jerusalem has remembered &#91;in&#93; the days of her affliction and of her homeless people
All her desirable things that happened to be from days of long ago.
When her people fell into the hand of the adversary and she had no helper,
The adversaries saw her. They laughed over her collapse.

_ח &#91;Chehth&#93;_

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalem has committed outright sin. That is why she has become a mere abhorrent thing.
All who were honoring her have treated her as something cheap, for they have seen her nakedness.
She herself is also sighing and turns her back.

_ט &#91;Tehth&#93;_

[[v25-1-9]]

^<<v25-1-9,9>>^ Her uncleanness is in her skirts. She did not remember the future for her,
And down she goes in a wondrous manner. No comforter does she have.
O Jehovah, see my affliction, for the enemy has put on great airs.

_י &#91;Yohdh&#93;_

[[v25-1-10]]

^<<v25-1-10,10>>^ The adversary has spread out his own hand against all her desirable things.
For she has seen nations that have come into her sanctuary,
Whom you commanded that they should not come into the congregation^&#42;1^ belonging to you.

[NOTE]
====
. “Into the congregation.” Heb., vaq·qa·halʹ; Gr., ek·kle·siʹan; Lat., ec·cleʹsi·am.
====

_כ &#91;Kaph&#93;_

[[v25-1-11]]

^<<v25-1-11,11>>^ All her people are sighing; they are looking for bread.
They have given their desirable things for something to eat, in order to refresh the soul.^&#42;1^
See, O Jehovah, and do look, for I have become as a valueless woman.^&#42;2^

[NOTE]
====
. “Soul.” Heb., naʹphesh; Lat., aʹni·mam. See App 4A.
. The Heb. word for “valueless” is fem. sing., as if a woman representing the city is speaking.
====

_ל &#91;Laʹmedh&#93;_

[[v25-1-12]]

^<<v25-1-12,12>>^ Is it nothing to all YOU who are passing along the way? Look and see.
Does there exist any pain like my pain that has been severely dealt out to me,
With which Jehovah has caused grief in the day of his burning anger?

_מ &#91;Mem&#93;_

[[v25-1-13]]

^<<v25-1-13,13>>^ From the height he has sent fire into my bones, and he subdues each one.
He has spread out a net for my feet. He has turned me backward.
He has made me a woman laid desolate. All the day I am ill.

_נ &#91;Nun&#93;_

[[v25-1-14]]

^<<v25-1-14,14>>^ He has kept himself alert against my transgressions. In his hand they intertwine one another.
They have come up upon my neck. My power has stumbled.
Jehovah^&#42;1^ has given me into the hand of those against whom I am unable to rise up.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

_ס &#91;Saʹmekh&#93;_

[[v25-1-15]]

^<<v25-1-15,15>>^ All my powerful ones Jehovah^&#42;1^ has tossed aside from the midst of me.
He has called against me a meeting, in order to break my young men to pieces.
Jehovah^&#42;2^ has trodden the very winepress belonging to the virgin daughter of Judah.

[NOTE]
====
. See vs 14 ftn.
. See vs 14 ftn.
====

_ע &#91;ʽAʹyin&#93;_

[[v25-1-16]]

^<<v25-1-16,16>>^ Over these things I am weeping as a woman.^&#42;1^ My eye, my eye is running down with waters.
For a comforter has become far away from me, someone to refresh my soul.
My sons have become those laid desolate, for the enemy has put on great airs.

[NOTE]
====
. Compare vs 11 ftn, “Woman.”
====

_פ &#91;Peʼ&#93;_

[[v25-1-17]]

^<<v25-1-17,17>>^ Zion has spread out her hands. No comforter does she have.
Jehovah has given a command concerning Jacob to all who are around him as his adversaries.
Jerusalem has become an abhorrent thing in among them.

_צ &#91;Tsa·dhehʹ&#93;_

[[v25-1-18]]

^<<v25-1-18,18>>^ Jehovah is righteous, for it is against his mouth that I have rebelled.
Listen, now, all YOU peoples, and see my pain.
My own virgins and my own young men have gone into captivity.

_ק &#91;Qohph&#93;_

[[v25-1-19]]

^<<v25-1-19,19>>^ I have called to those intensely loving me. They themselves have tricked me.
In the city my own priests and my own old men have expired,
While they had to look for something to eat for themselves that they might refresh their soul.

_ר &#91;Rehsh&#93;_

[[v25-1-20]]

^<<v25-1-20,20>>^ See, O Jehovah, for I am in sore straits. My very intestines are in a ferment.
My heart has been overturned in the midst of me, for I have been absolutely rebellious.
Outside the sword caused bereavement of children. Within the house it is the same as death.

_ש &#91;Shin&#93;_

[[v25-1-21]]

^<<v25-1-21,21>>^ People have heard^&#42;1^ how I myself am sighing as a woman. There is no comforter for me.
All my enemies themselves have heard of my calamity. They have exulted, because you yourself have done &#91;it&#93;.
You will certainly bring the day that you have proclaimed, that they may become like me.

[NOTE]
====
. “They have heard,” MVg; T, “Nations have heard”; LXX, “Hear [pl.], please”; Sy, “Hear.”
====

_ת &#91;Taw&#93;_

[[v25-1-22]]

^<<v25-1-22,22>>^ May all their badness come before you, and deal severely with them,
Just as you have dealt severely with me on account of all my transgressions.
For my sighs are many, and my heart is ill.

'''

xref:024-jeremiah/024-jeremiah-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentations/025-lamentations-002.adoc#v25-2-0[Próximo Capítulo &#62;]