include::./index.adoc[]

[[v25-2-0]]
=== Lamentations, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_א &#91;ʼAʹleph&#93;_

[[v25-2-1]]

^<<v25-2-1,1>>^ O how Jehovah^&#42;1^ in his anger beclouds the daughter of Zion!
He has thrown down from heaven to earth the beauty of Israel.
And he has not remembered his footstool in the day of his anger.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

_ב &#91;Behth&#93;_

[[v25-2-2]]

^<<v25-2-2,2>>^ Jehovah^&#42;1^ has swallowed up, he has shown no compassion upon any abiding places of Jacob.
In his fury he has torn down the fortified places of the daughter of Judah.
He has brought into contact with the earth, he has profaned the kingdom and her princes.

[NOTE]
====
. See vs 1 ftn.
====

_ג &#91;Giʹmel&#93;_

[[v25-2-3]]

^<<v25-2-3,3>>^ In the heat of anger he has cut down every horn of Israel.
He has turned his right hand back from before the enemy;
And in Jacob he keeps burning like a flaming fire that has devoured all around.

_ד &#91;Daʹleth&#93;_

[[v25-2-4]]

^<<v25-2-4,4>>^ He has trodden his bow like an enemy. His right hand has taken its position
Like an adversary, and he kept killing all those desirable to the eyes.
Into the tent of the daughter of Zion he has poured out his rage, just like fire.

_ה &#91;Heʼ&#93;_

[[v25-2-5]]

^<<v25-2-5,5>>^ Jehovah^&#42;1^ has become like an enemy. He has swallowed down Israel.
He has swallowed down all her dwelling towers; he has brought his fortified places to ruin.
And in the daughter of Judah he makes mourning and lamentation abound.

[NOTE]
====
. See vs 1 ftn.
====

_ו &#91;Waw&#93;_

[[v25-2-6]]

^<<v25-2-6,6>>^ And he treats his booth violently like that in a garden. He has brought his festival to ruin.
Jehovah has caused to be forgotten in Zion festival and sabbath,
And in his angry denunciation he shows no respect for king and priest.

_ז &#91;Zaʹyin&#93;_

[[v25-2-7]]

^<<v25-2-7,7>>^ Jehovah^&#42;1^ has cast off his altar. He has spurned his sanctuary.
Into the hand of the enemy he has surrendered the walls of her dwelling towers.
In the house of Jehovah they have let out &#91;their&#93; own voice, as in the day of a festival.

[NOTE]
====
. See vs 1 ftn.
====

_ח &#91;Chehth&#93;_

[[v25-2-8]]

^<<v25-2-8,8>>^ Jehovah has thought of bringing the wall of the daughter of Zion to ruin.
He has stretched out the measuring line. He has not turned back his hand from swallowing up.
And he causes rampart and wall to go mourning. Together they have faded away.

_ט &#91;Tehth&#93;_

[[v25-2-9]]

^<<v25-2-9,9>>^ Her gates have sunk down into the very earth. He has destroyed and broken her bars in pieces.
Her king and her princes are among the nations. There is no law.
Her own prophets also have found no vision from Jehovah.

_י &#91;Yohdh&#93;_

[[v25-2-10]]

^<<v25-2-10,10>>^ The older men of the daughter of Zion sit down on the earth, &#91;where&#93; they keep silence.
They have brought up dust upon their head. They have girded on sackcloth.
The virgins of Jerusalem have brought their head down to the very earth.

_כ &#91;Kaph&#93;_

[[v25-2-11]]

^<<v25-2-11,11>>^ My eyes have come to their end in sheer tears. My intestines are in a ferment.
My liver has been poured out to the very earth, on account of the crash of the daughter of my people,
Because of the fainting away of child and suckling in the public squares of the town.

_ל &#91;Laʹmedh&#93;_

[[v25-2-12]]

^<<v25-2-12,12>>^ To their mothers they kept saying: “Where are grain and wine?”
Because of their fainting away like someone slain in the public squares of the city,
Because of their soul being poured out into the bosom of their mothers.

_מ &#91;Mem&#93;_

[[v25-2-13]]

^<<v25-2-13,13>>^ Of what shall I use you as a witness? What shall I liken to you, O daughter of Jerusalem?
What shall I make equal to you, that I may comfort you, O virgin daughter of Zion?
For your breakdown is just as great as the sea. Who can bring healing to you?

_נ &#91;Nun&#93;_

[[v25-2-14]]

^<<v25-2-14,14>>^ Your own prophets have visioned for you worthless and unsatisfying things,
And they have not uncovered your error in order to turn back your captivity,
But they kept visioning for you worthless and misleading pronouncements.

_ס &#91;Saʹmekh&#93;_

[[v25-2-15]]

^<<v25-2-15,15>>^ At you all those passing along on the road have clapped their hands.
They have whistled and kept wagging their head at the daughter of Jerusalem, &#91;saying:&#93;
“Is this the city of which they used to say, ‘It is the perfection of prettiness, an exultation for all the earth’?”

_פ &#91;Peʼ&#93;^&#42;1^_

[[v25-2-16]]

^<<v25-2-16,16>>^ At you all your enemies have opened their mouth.
They have whistled and kept grinding the teeth. They have said: “We will swallow &#91;her&#93;^&#42;1^ down.
This indeed is the day that we have hoped for. We have found! We have seen!”

[NOTE]
====
. “Her,” LXXSy.
====

_ע &#91;ʽAʹyin&#93;^&#42;1^_

[[v25-2-17]]

^<<v25-2-17,17>>^ Jehovah has done what he had in mind. He has accomplished his saying,
What he had commanded from the days of long ago. He has torn down and shown no compassion.
And over you he causes the enemy to rejoice. He has made the horn of your adversaries high.

_צ &#91;Tsa·dhehʹ&#93;_

[[v25-2-18]]

^<<v25-2-18,18>>^ Their heart has cried out to Jehovah,^&#42;1^ O wall of the daughter of Zion.
Cause tears to descend just like a torrent day and night.
Give no numbness to yourself. May the pupil^&#42;2^ of your eye not keep quiet.

[NOTE]
====
. See vs 1 ftn.
. Lit., “daughter.”
====

_ק &#91;Qohph&#93;_

[[v25-2-19]]

^<<v25-2-19,19>>^ Rise up! Whine during the night at the start of the morning watches.
Pour out your heart before the face of Jehovah^&#42;1^ just like water.
Raise to him your palms on account of the soul of your children,
Who are fainting away because of famine at the head of all the streets.

[NOTE]
====
. See vs 1 ftn.
====

_ר &#91;Rehsh&#93;_

[[v25-2-20]]

^<<v25-2-20,20>>^ See, O Jehovah, and do look to the one to whom you have dealt severely in this manner.
Should the women keep eating their own fruitage, the children born fully formed,
Or in the sanctuary of Jehovah^&#42;1^ should priest and prophet be killed?

[NOTE]
====
. See vs 1 ftn.
====

_ש &#91;Shin&#93;_

[[v25-2-21]]

^<<v25-2-21,21>>^ Boy and old man have lain down on the earth of the streets.
My virgins and my young men themselves have fallen by the sword.
You have killed in the day of your anger. You have slaughtered; you have had no compassion.

_ת &#91;Taw&#93;_

[[v25-2-22]]

^<<v25-2-22,22>>^ As in the day of a festival you proceeded to call out my places of alien residence all around.
And in the day of the wrath of Jehovah there proved to be no escapee or survivor;
Those whom I brought forth fully formed and reared, my enemy himself exterminated them.

'''

xref:025-lamentations/025-lamentations-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-lamentations/025-lamentations-003.adoc#v25-3-0[Próximo Capítulo &#62;]