include::./index.adoc[]

[[v25-3-0]]
=== Lamentations, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_א &#91;ʼAʹleph&#93;^&#42;1^_

[[v25-3-1]]

^<<v25-3-1,1>>^ I am the able-bodied man that has seen affliction because of the staff of his fury.

[[v25-3-2]]

^<<v25-3-2,2>>^ It is I whom he has led and makes to walk in darkness and not in light.

[[v25-3-3]]

^<<v25-3-3,3>>^ Indeed, it is against me that he repeatedly turns his hand all day long.

_ב &#91;Behth&#93;_

[[v25-3-4]]

^<<v25-3-4,4>>^ He has caused my flesh and my skin to wear away. He has broken my bones.

[[v25-3-5]]

^<<v25-3-5,5>>^ He has built against me, that he may encircle &#91;me&#93; with poisonous plant and hardship.

[[v25-3-6]]

^<<v25-3-6,6>>^ In dark places he has made me sit like men dead for a long time.

_ג &#91;Giʹmel&#93;_

[[v25-3-7]]

^<<v25-3-7,7>>^ He has blocked me up as with a stone wall, that I may not go forth. He has made my copper fetters heavy.

[[v25-3-8]]

^<<v25-3-8,8>>^ Also, when I call for aid and cry for help, he actually hampers my prayer.

[[v25-3-9]]

^<<v25-3-9,9>>^ He has blocked up my ways with hewn stone. My roadways he has twisted.

_ד &#91;Daʹleth&#93;_

[[v25-3-10]]

^<<v25-3-10,10>>^ As a bear lying in wait he is to me, as a lion in places of concealment.

[[v25-3-11]]

^<<v25-3-11,11>>^ My ways he has disarranged, and he makes me lie fallow.^&#42;1^ He has made me one laid desolate.

[NOTE]
====
. Or, “he tears me to pieces.”
====

[[v25-3-12]]

^<<v25-3-12,12>>^ He has trodden his bow, and he sets me up as the target for the arrow.

_ה &#91;Heʼ&#93;_

[[v25-3-13]]

^<<v25-3-13,13>>^ He has brought into my kidneys the sons of his quiver.

[[v25-3-14]]

^<<v25-3-14,14>>^ I have become an object of laughter to all people against me,^&#42;1^ the theme of their song all day long.

[NOTE]
====
. “All my people,” MLXXVg; Sy, “all peoples”; T, “all scatterers of my people.”
====

[[v25-3-15]]

^<<v25-3-15,15>>^ He has given me a sufficiency of bitter things. He has saturated me with wormwood.

_ו &#91;Waw&#93;_

[[v25-3-16]]

^<<v25-3-16,16>>^ And with gravel he makes my teeth get broken. He has made me cower in the ashes.

[[v25-3-17]]

^<<v25-3-17,17>>^ You also do a casting off so that there is no peace for my soul. I have lost memory of what good is.

[[v25-3-18]]

^<<v25-3-18,18>>^ And I keep saying: “My excellency has perished, and my expectation from Jehovah.”

_ז &#91;Zaʹyin&#93;_

[[v25-3-19]]

^<<v25-3-19,19>>^ Remember my affliction and my homeless state, the wormwood and the poisonous plant.

[[v25-3-20]]

^<<v25-3-20,20>>^ Without fail your^&#42;1^ soul will remember and bow low over me.

[NOTE]
====
. “Your,” emended by the Sopherim to read “my” in M; one of the Eighteen Emendations. See App 2B.
====

[[v25-3-21]]

^<<v25-3-21,21>>^ This is what I shall bring back to my heart. That is why I shall show a waiting attitude.

_ח &#91;Chehth&#93;_

[[v25-3-22]]

^<<v25-3-22,22>>^ It is the acts of loving-kindness^&#42;1^ of Jehovah that we have not come to our finish, because his mercies will certainly not come to an end.

[NOTE]
====
. Or, “loyal love.”
====

[[v25-3-23]]

^<<v25-3-23,23>>^ They are new each morning. Your faithfulness is abundant.

[[v25-3-24]]

^<<v25-3-24,24>>^ “Jehovah is my share,” my soul has said, “that is why I shall show a waiting attitude for him.”

_ט &#91;Tehth&#93;_

[[v25-3-25]]

^<<v25-3-25,25>>^ Good is Jehovah to the one hoping in him, to the soul that keeps seeking for him.

[[v25-3-26]]

^<<v25-3-26,26>>^ Good it is that one should wait, even silently, for the salvation of Jehovah.

[[v25-3-27]]

^<<v25-3-27,27>>^ Good it is for an able-bodied man that he should carry the yoke during his youth.

_י &#91;Yohdh&#93;_

[[v25-3-28]]

^<<v25-3-28,28>>^ Let him sit solitary and keep silent, because he has laid &#91;something&#93; upon him.

[[v25-3-29]]

^<<v25-3-29,29>>^ Let him put his mouth in the very dust. Perhaps there exists a hope.

[[v25-3-30]]

^<<v25-3-30,30>>^ Let him give &#91;his&#93; cheek to the very one striking him. Let him have his sufficiency of reproach.

_כ &#91;Kaph&#93;_

[[v25-3-31]]

^<<v25-3-31,31>>^ For not to time indefinite will Jehovah^&#42;1^ keep on casting off.

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v25-3-32]]

^<<v25-3-32,32>>^ For although he has caused grief, he will also certainly show mercy according to the abundance of his loving-kindness.

[[v25-3-33]]

^<<v25-3-33,33>>^ For not out of his own heart has he afflicted or does he grieve the sons of men.^&#42;1^

[NOTE]
====
. “Men.” Heb., ʼish, sing. but in a collective sense.
====

_ל &#91;Laʹmedh&#93;_

[[v25-3-34]]

^<<v25-3-34,34>>^ For crushing beneath one’s feet all the prisoners of the earth,

[[v25-3-35]]

^<<v25-3-35,35>>^ For turning aside the judgment of an able-bodied man before the face of the Most High,

[[v25-3-36]]

^<<v25-3-36,36>>^ For making a man^&#42;1^ crooked in his legal case, Jehovah^&#42;2^ himself has had no countenance.

[NOTE]
====
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
. See vs 31 ftn.
====

_מ &#91;Mem&#93;_

[[v25-3-37]]

^<<v25-3-37,37>>^ Who, now, has said that something should occur &#91;when&#93; Jehovah^&#42;1^ himself has not commanded?

[NOTE]
====
. See vs 31 ftn.
====

[[v25-3-38]]

^<<v25-3-38,38>>^ From the mouth of the Most High bad things and what is good do not go forth.

[[v25-3-39]]

^<<v25-3-39,39>>^ How can a living man^&#42;1^ indulge in complaints, an able-bodied man on account of his sin?

[NOTE]
====
. Or, “a living earthling man.” Heb., ʼa·dhamʹ chai.
====

_נ &#91;Nun&#93;_

[[v25-3-40]]

^<<v25-3-40,40>>^ Do let us search out our ways and explore them, and do let us return clear to Jehovah.

[[v25-3-41]]

^<<v25-3-41,41>>^ Let us raise our heart along with &#91;our&#93; palms to God^&#42;1^ in the heavens:

[NOTE]
====
. “God.” Heb., ʼEl; Vg, “Jehovah.”
====

[[v25-3-42]]

^<<v25-3-42,42>>^ “We ourselves have transgressed, and we have behaved rebelliously. You yourself have not forgiven.

_ס &#91;Saʹmekh&#93;_

[[v25-3-43]]

^<<v25-3-43,43>>^ You have blocked approach with anger, and you keep pursuing us. You have killed; you have shown no compassion.

[[v25-3-44]]

^<<v25-3-44,44>>^ You have blocked approach to yourself with a cloud mass, that prayer may not pass through.

[[v25-3-45]]

^<<v25-3-45,45>>^ You make us mere offscouring and refuse in the midst of the peoples.”

_פ &#91;Peʼ&#93;^&#42;1^_

[[v25-3-46]]

^<<v25-3-46,46>>^ Against us all our enemies have opened their mouth.

[[v25-3-47]]

^<<v25-3-47,47>>^ Dread and the hollow themselves have become ours, desolateness and breakdown.

[[v25-3-48]]

^<<v25-3-48,48>>^ With streams of water my eye keeps running down on account of the breakdown of the daughter of my people.

_ע &#91;ʽAʹyin&#93;_

[[v25-3-49]]

^<<v25-3-49,49>>^ My very eye has been poured forth and will not keep still, so that there are no pauses,

[[v25-3-50]]

^<<v25-3-50,50>>^ Until Jehovah looks down and sees from heaven.

[[v25-3-51]]

^<<v25-3-51,51>>^ My own eye has dealt severely with my soul, because of all the daughters^&#42;1^ of my city.

[NOTE]
====
. Or, “dependent towns.”
====

_צ &#91;Tsa·dhehʹ&#93;_

[[v25-3-52]]

^<<v25-3-52,52>>^ My enemies have positively hunted for me just as for a bird, for no cause.

[[v25-3-53]]

^<<v25-3-53,53>>^ They have silenced my life in the pit itself, and they kept hurling stones at me.

[[v25-3-54]]

^<<v25-3-54,54>>^ Waters have flowed over my head. I have said: “I shall certainly be cut off!”

_ק &#91;Qohph&#93;_

[[v25-3-55]]

^<<v25-3-55,55>>^ I have called out your name, O Jehovah, from a pit of the lowest sort.

[[v25-3-56]]

^<<v25-3-56,56>>^ My voice you must hear. Do not hide your ear to my relief, to my cry for help.

[[v25-3-57]]

^<<v25-3-57,57>>^ You have drawn near in the day that I kept calling you. You said: “Do not be afraid.”

_ר &#91;Rehsh&#93;_

[[v25-3-58]]

^<<v25-3-58,58>>^ You have taken up, O Jehovah,^&#42;1^ the contests of my soul. You have repurchased my life.

[NOTE]
====
. See vs 31 ftn.
====

[[v25-3-59]]

^<<v25-3-59,59>>^ You have seen, O Jehovah, the wrong done to me. O do conduct the judgment for me.

[[v25-3-60]]

^<<v25-3-60,60>>^ You have seen all their vengeance, all their thoughts against me.

_ש &#91;Sin&#93; or &#91;Shin&#93;_

[[v25-3-61]]

^<<v25-3-61,61>>^ You have heard their reproach, O Jehovah, all their thoughts against me,

[[v25-3-62]]

^<<v25-3-62,62>>^ The lips of those rising up against me and their whispering against me all day long.

[[v25-3-63]]

^<<v25-3-63,63>>^ Do look at their very sitting down and their rising up. I am the subject of their song.

_ת &#91;Taw&#93;_

[[v25-3-64]]

^<<v25-3-64,64>>^ You will give back to them a treatment, O Jehovah, according to the work of their hands.

[[v25-3-65]]

^<<v25-3-65,65>>^ You will give to them the insolence of heart, your curse to them.

[[v25-3-66]]

^<<v25-3-66,66>>^ You will pursue in anger and annihilate them from under the heavens of Jehovah.

'''

xref:025-lamentations/025-lamentations-002.adoc#v25-2-0[&#60; Capítulo Anterior] | <<v25-3-0,Topo>> | xref:025-lamentations/025-lamentations-004.adoc#v25-4-0[Próximo Capítulo &#62;]