include::./index.adoc[]

[[v25-4-0]]
=== Lamentations, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

_א &#91;ʼAʹleph&#93;_

[[v25-4-1]]

^<<v25-4-1,1>>^ O how the gold that shines becomes dim, the good gold!^&#42;1^
O how the holy stones^&#42;2^ are poured out at the head of all the streets!

[NOTE]
====
. Or, “O how the gold [Heb., za·havʹ] becomes dim, how the good gold [Heb., hak·keʹthem] changes!” See Job 28:16, 17 ftns.
. Or, “the stones of the sanctuary.”
====

_ב &#91;Behth&#93;_

[[v25-4-2]]

^<<v25-4-2,2>>^ As for the precious sons of Zion, those who were weighed against refined gold,^&#42;1^
O how they have been reckoned as large jars of earthenware, the work of the hands of a potter!

[NOTE]
====
. “Against refined gold.” Heb., bap·pazʹ.
====

_ג &#91;Giʹmel&#93;_

[[v25-4-3]]

^<<v25-4-3,3>>^ Even jackals themselves have presented the udder. They have suckled their cubs.
The daughter of my people becomes cruel, like ostriches in the wilderness.

_ד &#91;Daʹleth&#93;_

[[v25-4-4]]

^<<v25-4-4,4>>^ The tongue of the suckling has cleaved to its palate because of thirst.
Children themselves have asked for bread. There is no one dealing &#91;it&#93; out to them.

_ה &#91;Heʼ&#93;_

[[v25-4-5]]

^<<v25-4-5,5>>^ The very ones that were eating pleasant things have been struck with astonishment in the streets.
The very ones that were being reared in scarlet have had to embrace ash heaps.

_ו &#91;Waw&#93;_

[[v25-4-6]]

^<<v25-4-6,6>>^ The &#91;punishment for the&#93; error of the daughter of my people also becomes greater than the &#91;punishment for the&#93; sin of Sodʹom,
Which was overthrown as in a moment, and to which no hands turned &#91;helpfully&#93;.

_ז &#91;Zaʹyin&#93;_

[[v25-4-7]]

^<<v25-4-7,7>>^ Her Nazʹi·rites were purer than snow; they were whiter than milk.
They were in fact more ruddy than corals; their polish was as the sapphire.

_ח &#91;Chehth&#93;_

[[v25-4-8]]

^<<v25-4-8,8>>^ Their aspect has become darker than blackness itself. They have not been recognized in the streets.
Their skin has shriveled upon their bones. It has become just as dry as a tree.

_ט &#91;Tehth&#93;_

[[v25-4-9]]

^<<v25-4-9,9>>^ Better have those slain with the sword proved to be than those slain by famine,
Because these pine away,^&#42;1^ pierced through for lack of the produce of the open field.

[NOTE]
====
. Lit., “flow forth,” evidently figuratively.
====

_י &#91;Yohdh&#93;_

[[v25-4-10]]

^<<v25-4-10,10>>^ The very hands of compassionate women have boiled their own children.
They have become as bread of consolation to one during the breakdown of the daughter of my people.

_כ &#91;Kaph&#93;_

[[v25-4-11]]

^<<v25-4-11,11>>^ Jehovah has accomplished his rage. He has poured out his burning anger.
And he sets a fire ablaze in Zion, which eats up her foundations.

_ל &#91;Laʹmedh&#93;_

[[v25-4-12]]

^<<v25-4-12,12>>^ The kings of the earth and all the inhabitants of the productive land^&#42;1^ had not believed
That the adversary and the enemy would come into the gates of Jerusalem.

[NOTE]
====
. “The productive land.” Heb., the·velʹ; LXX, “the inhabited earth”; Lat., orʹbis, “the circle,” that is, of the earth.
====

_מ &#91;Mem&#93;_

[[v25-4-13]]

^<<v25-4-13,13>>^ Because of the sins of her prophets, the errors of her priests,
There were in the midst of her those pouring out the blood of righteous ones.

_נ &#91;Nun&#93;_

[[v25-4-14]]

^<<v25-4-14,14>>^ They have wandered about as blind in the streets. They have become polluted with blood,
So that none are able to touch their garments.

_ס &#91;Saʹmekh&#93;_

[[v25-4-15]]

^<<v25-4-15,15>>^ “Get out of the way! Unclean!” they have called out to them. “Get out of the way! Get out of the way! Do not touch!”
For they have gone homeless. They have also wandered about. People have said among the nations: “They will not reside again as aliens.

_פ &#91;Peʼ&#93;_

[[v25-4-16]]

^<<v25-4-16,16>>^ The face of Jehovah has divided them up. He will not look upon them again.
Men will certainly show no consideration even for the priests. They will certainly show no favor even to the old men.”

_ע &#91;ʽAʹyin&#93;_

[[v25-4-17]]

^<<v25-4-17,17>>^ While we yet are, our eyes keep pining away in vain for assistance to us.
During our looking about we have looked out to a nation that can bring no salvation.

_צ &#91;Tsa·dhehʹ&#93;_

[[v25-4-18]]

^<<v25-4-18,18>>^ They have hunted our steps so that there is no walking in our public squares.
Our end has drawn near. Our days have come to their full, for our end has come.

_ק &#91;Qohph&#93;_

[[v25-4-19]]

^<<v25-4-19,19>>^ Swifter than the eagles of the heavens our pursuers have proved to be.
Upon the mountains they have hotly pursued us. In the wilderness they have lain in wait for us.

_ר &#91;Rehsh&#93;_

[[v25-4-20]]

^<<v25-4-20,20>>^ The very breath^&#42;1^ of our nostrils, the anointed one^&#42;2^ of Jehovah,^&#42;3^ has been captured in their large pit,
The one of whom we have said: “In his shade we shall live among the nations.”

[NOTE]
====
. Or, “spirit (wind).” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tus.
. “Anointed one of.” Heb., meshiʹach; Gr., khri·stosʹ; Syr., meshi·cheh; Lat., chriʹstus.
. “The anointed Lord,” LXXBagsterVg.
====

_ש &#91;Sin&#93;_

[[v25-4-21]]

^<<v25-4-21,21>>^ Exult and rejoice, O daughter of Eʹdom, dwelling as you do in the land of Uz.
To you also the cup^&#42;1^ will pass along. You will become drunk and show yourself in nakedness.

[NOTE]
====
. “The cup,” MSyVg; T, “the cup of cursing”; LXX, “the cup of Jehovah.”
====

_ת &#91;Taw&#93;_

[[v25-4-22]]

^<<v25-4-22,22>>^ Your error, O daughter of Zion, has come to its finish. He will not^&#42;1^ carry you off into exile again.
He has turned his attention to your error, O daughter of Eʹdom. He has uncovered your sins.

[NOTE]
====
. Or, “No one will.”
====

'''

xref:025-lamentations/025-lamentations-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentations/025-lamentations-005.adoc#v25-5-0[Próximo Capítulo &#62;]