include::./index.adoc[]

[[v61-1-0]]
=== The Second of Peter, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v61-1-1]]

^<<v61-1-1,1>>^ Simon Peter, a slave and apostle of Jesus Christ, to those who have obtained a faith, held in equal privilege with ours, by the righteousness of our God^&#42;1^ and &#91;the&#93; Savior Jesus Christ:^&#42;2^

[NOTE]
====
. “Our God,” ABVg; אSyh, “our Lord.”
. “Of our God and [the] Savior Jesus Christ,” in agreement with the distinction between God and Jesus in the next vs. See App 6E.
====

[[v61-1-2]]

^<<v61-1-2,2>>^ May undeserved kindness and peace be increased to YOU by an accurate knowledge of God and of Jesus^&#42;1^ our Lord,

[NOTE]
====
. See App 6E.
====

[[v61-1-3]]

^<<v61-1-3,3>>^ forasmuch as his divine power^&#42;1^ has given us freely all the things that concern life and godly devotion, through the accurate knowledge of the one who called us through glory and virtue.

[NOTE]
====
. “His divine power,” אAB; J18, “Jehovah by his power.”
====

[[v61-1-4]]

^<<v61-1-4,4>>^ Through these things he has freely given us the precious and very grand promises, that through these YOU may become sharers in divine nature,^&#42;1^ having escaped from the corruption that is in the world through lust.

[NOTE]
====
. “In divine nature.” Gr., theiʹas . . . phyʹse·os.
====

[[v61-1-5]]

^<<v61-1-5,5>>^ Yes, for this very reason, by YOUR contributing in response all earnest effort, supply to YOUR faith virtue, to &#91;YOUR&#93; virtue knowledge,

[[v61-1-6]]

^<<v61-1-6,6>>^ to &#91;YOUR&#93; knowledge self-control, to &#91;YOUR&#93; self-control endurance, to &#91;YOUR&#93; endurance godly devotion,

[[v61-1-7]]

^<<v61-1-7,7>>^ to &#91;YOUR&#93; godly devotion brotherly affection, to &#91;YOUR&#93; brotherly affection love.

[[v61-1-8]]

^<<v61-1-8,8>>^ For if these things exist in YOU and overflow, they will prevent YOU from being either inactive or unfruitful^&#42;1^ regarding the accurate knowledge of our Lord Jesus Christ.

[NOTE]
====
. Or, “cause you to be neither inactive nor unfruitful.”
====

[[v61-1-9]]

^<<v61-1-9,9>>^ For if these things are not present in anyone, he is blind, shutting his eyes &#91;to the light&#93;,^&#42;1^ and has become forgetful of his cleansing from his sins of long ago.

[NOTE]
====
. Or, “blind, seeing only what is near.”
====

[[v61-1-10]]

^<<v61-1-10,10>>^ For this reason, brothers, all the more do YOUR utmost to make the calling and choosing of YOU sure for yourselves; for if YOU keep on doing these things YOU will by no means ever fail.

[[v61-1-11]]

^<<v61-1-11,11>>^ In fact, thus there will be richly supplied to YOU the entrance into the everlasting kingdom of our Lord and Savior Jesus Christ.

[[v61-1-12]]

^<<v61-1-12,12>>^ For this reason I shall be disposed always to remind YOU of these things, although YOU know &#91;them&#93; and are firmly set in the truth that is present &#91;in YOU&#93;.

[[v61-1-13]]

^<<v61-1-13,13>>^ But I consider it right, as long as I am in this tabernacle, to rouse YOU up by way of reminding YOU,

[[v61-1-14]]

^<<v61-1-14,14>>^ knowing as I do that the putting off of my tabernacle is soon to be,^&#42;1^ just as also our Lord Jesus Christ signified to me.

[NOTE]
====
. Or, “is coming swiftly.”
====

[[v61-1-15]]

^<<v61-1-15,15>>^ So I will do my utmost also at every time that, after my departure, YOU may be able to make mention of these things^&#42;1^ for yourselves.

[NOTE]
====
. Or, “to call these things to remembrance.”
====

[[v61-1-16]]

^<<v61-1-16,16>>^ No, it was not by following artfully contrived false stories that we acquainted YOU with the power and presence^&#42;1^ of our Lord Jesus Christ, but it was by having become eyewitnesses of his magnificence.

[NOTE]
====
. See App 5B.
====

[[v61-1-17]]

^<<v61-1-17,17>>^ For he received from God the Father honor and glory, when words such as these^&#42;1^ were borne to him by the magnificent glory: “This is my son, my beloved, whom I myself have approved.”^&#42;2^

[NOTE]
====
. “Words such as these.” Lit., “such a voice.”
. Lit., “thought well.”
====

[[v61-1-18]]

^<<v61-1-18,18>>^ Yes, these words^&#42;1^ we heard borne from heaven while we were with him in the holy mountain.

[NOTE]
====
. Lit., “this voice.”
====

[[v61-1-19]]

^<<v61-1-19,19>>^ Consequently we have the prophetic word &#91;made&#93; more sure; and YOU are doing well in paying attention to it as to a lamp shining in a dark place, until day dawns and a daystar^&#42;1^ rises, in YOUR hearts.

[NOTE]
====
. Lit., “light bearer.”
====

[[v61-1-20]]

^<<v61-1-20,20>>^ For YOU know this first, that no prophecy of Scripture springs from any private interpretation.^&#42;1^

[NOTE]
====
. Or, “comes out of private disclosure [or, release].”
====

[[v61-1-21]]

^<<v61-1-21,21>>^ For prophecy was at no time brought by man’s will, but men spoke from God as they were borne along by holy spirit.

'''

xref:060-1-peter/060-1-peter-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-peter/061-2-peter-002.adoc#v61-2-0[Próximo Capítulo &#62;]