include::./index.adoc[]

[[v61-2-0]]
=== The Second of Peter, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v61-2-1]]

^<<v61-2-1,1>>^ However, there also came to be false prophets among the people, as there will also be false teachers among YOU. These very ones will quietly bring in destructive sects^&#42;1^ and will disown even the owner that bought them, bringing speedy destruction upon themselves.

[NOTE]
====
. Or, “heresies.” Gr., hai·reʹseis; Lat., secʹtas.
====

[[v61-2-2]]

^<<v61-2-2,2>>^ Furthermore, many will follow their acts of loose conduct,^&#42;1^ and on account of these the way of the truth will be spoken of abusively.

[NOTE]
====
. “Acts of loose conduct.” Gr., a·sel·geiʹais. See Ga 5:19 ftn, “Conduct.”
====

[[v61-2-3]]

^<<v61-2-3,3>>^ Also, with covetousness they will exploit YOU with counterfeit words. But as for them, the judgment from of old is not moving slowly, and the destruction of them is not slumbering.

[[v61-2-4]]

^<<v61-2-4,4>>^ Certainly if God did not hold back from punishing the angels that sinned, but, by throwing them into Tarʹta·rus,^&#42;1^ delivered them to pits of dense darkness to be reserved for judgment;

[NOTE]
====
. For a discussion of “Tartarus,” see App 4D.
====

[[v61-2-5]]

^<<v61-2-5,5>>^ and he did not hold back from punishing an ancient^&#42;1^ world, but kept Noah, a preacher of righteousness, safe with seven others when he brought a deluge^&#42;2^ upon a world of ungodly people;

[NOTE]
====
. Lit., “archaic.” Gr., ar·khaiʹou.
. Or, “flood; cataclysm.” Gr., ka·ta·kly·smonʹ; Lat., di·luʹvi·um.
====

[[v61-2-6]]

^<<v61-2-6,6>>^ and by reducing the cities Sodʹom and Go·morʹrah to ashes he condemned them, setting a pattern for ungodly persons^&#42;1^ of things to come;

[NOTE]
====
. Lit., “irreverential (ones).”
====

[[v61-2-7]]

^<<v61-2-7,7>>^ and he delivered righteous Lot, who was greatly distressed by the indulgence of the law-defying people in loose conduct^&#42;1^—

[NOTE]
====
. “Loose conduct.” Lit., “lewdness of conduct.”
====

[[v61-2-8]]

^<<v61-2-8,8>>^ for that righteous man by what he saw and heard while dwelling among them from day to day was tormenting his righteous soul by reason of their lawless deeds—

[[v61-2-9]]

^<<v61-2-9,9>>^ Jehovah^&#42;1^ knows how to deliver people of godly devotion out of trial, but to reserve unrighteous people for the day of judgment to be cut off,^&#42;2^

[NOTE]
====
. See App 1D.
. Or, “be checked.” Compare Mt 25:46.
====

[[v61-2-10]]

^<<v61-2-10,10>>^ especially, however, those who go on after flesh with the desire to defile &#91;it&#93; and who look down^&#42;1^ on lordship.
Daring, self-willed, they do not tremble at glorious ones^&#42;2^ but speak abusively,

[NOTE]
====
. Lit., “minding down.”
. Lit., “at glories.”
====

[[v61-2-11]]

^<<v61-2-11,11>>^ whereas angels, although they are greater in strength and power, do not bring against them an accusation in abusive terms, &#91;not doing so&#93; out of respect for Jehovah.^&#42;1^

[NOTE]
====
. “For Jehovah,” J7,​8,​13,​16-18,​22-24; אBC(Gr.), Ky·riʹoi; AVgSyh omit. See App 1D.
====

[[v61-2-12]]

^<<v61-2-12,12>>^ But these &#91;men&#93;, like unreasoning animals born naturally to be caught and destroyed, will, in the things of which they are ignorant and speak abusively, even suffer destruction in their own &#91;course of&#93; destruction,

[[v61-2-13]]

^<<v61-2-13,13>>^ wronging themselves as a reward for wrongdoing.
They consider luxurious living in the daytime a pleasure. They are spots and blemishes, indulging with unrestrained delight in their deceptive teachings^&#42;1^ while feasting together with YOU.

[NOTE]
====
. Or, “in their dissipations.”
====

[[v61-2-14]]

^<<v61-2-14,14>>^ They have eyes full of adultery^&#42;1^ and unable to desist from sin, and they entice^&#42;2^ unsteady souls. They have a heart trained in covetousness. They are accursed children.

[NOTE]
====
. Lit., “full of adulteress.”
. Lit., “baiting on.”
====

[[v61-2-15]]

^<<v61-2-15,15>>^ Abandoning the straight path, they have been misled. They have followed the path of Baʹlaam, &#91;the son&#93; of Beʹor, who loved the reward of wrongdoing,

[[v61-2-16]]

^<<v61-2-16,16>>^ but got a reproof for his own violation of what was right.^&#42;1^ A voiceless beast of burden, making utterance with the voice of a man, hindered the prophet’s mad course.

[NOTE]
====
. Lit., “exceeding of law.”
====

[[v61-2-17]]

^<<v61-2-17,17>>^ These are fountains without water, and mists driven by a violent storm, and for them the blackness of darkness has been reserved.

[[v61-2-18]]

^<<v61-2-18,18>>^ For they utter swelling expressions of no profit, and by the desires of the flesh and by loose habits they entice those who are just escaping from people who conduct themselves in error.

[[v61-2-19]]

^<<v61-2-19,19>>^ While they are promising them freedom, they themselves are existing as slaves of corruption. For whoever is overcome by another is enslaved by this one.^&#42;1^

[NOTE]
====
. Or, “is overcome by something is enslaved by the same.”
====

[[v61-2-20]]

^<<v61-2-20,20>>^ Certainly if, after having escaped from the defilements of the world by an accurate knowledge of the Lord and Savior Jesus Christ, they get involved^&#42;1^ again with these very things and are overcome, the final conditions have become worse for them than the first.

[NOTE]
====
. Lit., “having been inwoven.”
====

[[v61-2-21]]

^<<v61-2-21,21>>^ For it would have been better for them not to have accurately known the path of righteousness than after knowing it accurately to turn away from the holy commandment delivered to them.

[[v61-2-22]]

^<<v61-2-22,22>>^ The saying of the true proverb has happened to them: “The dog has returned to its own vomit, and the sow that was bathed to rolling in the mire.”

'''

xref:061-2-peter/061-2-peter-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-peter/061-2-peter-003.adoc#v61-3-0[Próximo Capítulo &#62;]