include::./index.adoc[]

[[v61-3-0]]
=== The Second of Peter, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v61-3-1]]

^<<v61-3-1,1>>^ Beloved ones, this is now the second letter I am writing YOU, in which, as in my first one, I am arousing YOUR clear thinking faculties^&#42;1^ by way of a reminder,

[NOTE]
====
. Lit., “mental perception.”
====

[[v61-3-2]]

^<<v61-3-2,2>>^ that YOU should remember the sayings previously spoken by the holy prophets and the commandment of the Lord and Savior through YOUR apostles.

[[v61-3-3]]

^<<v61-3-3,3>>^ For YOU know this first, that in the last days there will come ridiculers^&#42;1^ with their ridicule, proceeding according to their own desires

[NOTE]
====
. Lit., “players in sport [of mocking].”
====

[[v61-3-4]]

^<<v61-3-4,4>>^ and saying: “Where is this promised presence^&#42;1^ of his? Why, from the day our forefathers fell asleep &#91;in death&#93;, all things are continuing exactly as from creation’s beginning.”

[NOTE]
====
. See App 5B.
====

[[v61-3-5]]

^<<v61-3-5,5>>^ For, according to their wish, this fact escapes their notice, that there were heavens from of old and an earth standing compactly out of water and in the midst of water by the word of God;

[[v61-3-6]]

^<<v61-3-6,6>>^ and by those &#91;means&#93; the world of that time suffered destruction when it was deluged with water.

[[v61-3-7]]

^<<v61-3-7,7>>^ But by the same word the heavens and the earth that are now are stored up for fire and are being reserved to the day of judgment and of destruction of the ungodly men.

[[v61-3-8]]

^<<v61-3-8,8>>^ However, let this one fact not be escaping YOUR notice, beloved ones, that one day is with Jehovah^&#42;1^ as a thousand years and a thousand years as one day.

[NOTE]
====
. See App 1D.
====

[[v61-3-9]]

^<<v61-3-9,9>>^ Jehovah^&#42;1^ is not slow respecting his promise, as some people consider slowness, but he is patient with YOU because he does not desire any to be destroyed but desires all to attain to repentance.^&#42;2^

[NOTE]
====
. See App 1D.
. Lit., “change of mind.” Gr., me·taʹnoi·an.
====

[[v61-3-10]]

^<<v61-3-10,10>>^ Yet Jehovah’s^&#42;1^ day will come as a thief, in which the heavens will pass away with a hissing noise, but the elements^&#42;2^ being intensely hot will be dissolved,^&#42;3^ and earth and the works in it will be discovered.^&#42;4^

[NOTE]
====
. See App 1D.
. Or, “the celestial bodies.” Gr., stoi·kheiʹa.
. Lit., “will be loosed.”
. “Be discovered,” אB; AVgc, “be burned up.”
====

[[v61-3-11]]

^<<v61-3-11,11>>^ Since all these things are thus to be dissolved, what sort of persons ought YOU to be in holy acts of conduct and deeds of godly devotion,

[[v61-3-12]]

^<<v61-3-12,12>>^ awaiting and keeping close in mind^&#42;1^ the presence^&#42;2^ of the day of Jehovah,^&#42;3^ through which &#91;the&#93; heavens being on fire will be dissolved and &#91;the&#93; elements being intensely hot will melt!

[NOTE]
====
. “Keeping close in mind.” Or, “ardently desiring.” Lit., “speeding up.”
. See App 5B.
. “Of Jehovah,” J7,​8,​17; CVgc(Gr.), tou Ky·riʹou; אABVgSyh, “of God.” See App 1D.
====

[[v61-3-13]]

^<<v61-3-13,13>>^ But there are new heavens and a new earth that we are awaiting according to his promise, and in these righteousness is to dwell.

[[v61-3-14]]

^<<v61-3-14,14>>^ Hence, beloved ones, since YOU are awaiting these things, do YOUR utmost to be found finally by him spotless and unblemished and in peace.

[[v61-3-15]]

^<<v61-3-15,15>>^ Furthermore, consider the patience^&#42;1^ of our Lord as salvation, just as our beloved brother Paul according to the wisdom given him also wrote YOU,

[NOTE]
====
. Lit., “longness of spirit.”
====

[[v61-3-16]]

^<<v61-3-16,16>>^ speaking about these things as he does also in all &#91;his&#93; letters. In them, however, are some things hard to understand, which the untaught^&#42;1^ and unsteady are twisting,^&#42;2^ as &#91;they do&#93; also the rest of the Scriptures, to their own destruction.

[NOTE]
====
. Lit., “nonlearners.”
. Lit., “are distorting.”
====

[[v61-3-17]]

^<<v61-3-17,17>>^ YOU, therefore, beloved ones, having this advance knowledge, be on YOUR guard that YOU may not be led away with them by the error of the law-defying people^&#42;1^ and fall from YOUR own steadfastness.

[NOTE]
====
. Lit., “illegal (ones).”
====

[[v61-3-18]]

^<<v61-3-18,18>>^ No, but go on growing in the undeserved kindness and knowledge of our Lord and Savior Jesus Christ. To him &#91;be&#93; the glory both now and to the day of eternity.

'''

xref:061-2-peter/061-2-peter-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-john/062-1-john-001.adoc#v62-1-0[Próximo Capítulo &#62;]