include::./index.adoc[]

[[v18-34-0]]
=== Job, 34
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-34-1]]

^<<v18-34-1,1>>^ And E·liʹhu continued to answer and say:

[[v18-34-2]]

^<<v18-34-2,2>>^ “Listen, YOU wise ones, to my words;
And YOU who know, give ear to me.

[[v18-34-3]]

^<<v18-34-3,3>>^ For the ear itself makes a test of words,
Just as the palate tastes when eating.

[[v18-34-4]]

^<<v18-34-4,4>>^ Judgment let us choose for ourselves;
Let us know among ourselves what is good.

[[v18-34-5]]

^<<v18-34-5,5>>^ For Job has said, ‘I certainly am in the right,
But God^&#42;1^ himself has turned aside the judgment of me.

[NOTE]
====
. “But God.” Heb., weʼElʹ.
====

[[v18-34-6]]

^<<v18-34-6,6>>^ Against my own judgment do I tell lies?
My severe wound is incurable though there is no transgression.’

[[v18-34-7]]

^<<v18-34-7,7>>^ What able-bodied man^&#42;1^ is like Job,
&#91;Who&#93; drinks up derision like water?

[NOTE]
====
. “Able-bodied man.” Heb., gheʹver.
====

[[v18-34-8]]

^<<v18-34-8,8>>^ And he is certainly on his way to companionship with practicers of what is hurtful
And to walking with men of wickedness.

[[v18-34-9]]

^<<v18-34-9,9>>^ For he has said, ‘An able-bodied man does not profit
By his taking pleasure in God.’^&#42;1^

[NOTE]
====
. “God.” Heb., ʼElo·himʹ; LXX, “Jehovah.”
====

[[v18-34-10]]

^<<v18-34-10,10>>^ Therefore, YOU men of heart, listen to me.
Far be it from the &#91;true&#93; God^&#42;1^ to act wickedly,
And the Almighty to act unjustly!

[NOTE]
====
. “From the [true] God.” Heb., la·ʼElʹ; LXX, “Jehovah.” See App 1G.
====

[[v18-34-11]]

^<<v18-34-11,11>>^ For &#91;according to&#93; the way earthling man^&#42;1^ acts he will reward him,
And according to the path of man^&#42;2^ he will cause it to come upon him.

[NOTE]
====
. “Earthling man.” Heb., ʼa·dhamʹ.
. “Man.” Heb., ʼish.
====

[[v18-34-12]]

^<<v18-34-12,12>>^ Yes, for a fact, God^&#42;1^ himself does not act wickedly,
And the Almighty himself does not pervert judgment.

[NOTE]
====
. “God.” Heb., ʼEl; LXX, “Jehovah.”
====

[[v18-34-13]]

^<<v18-34-13,13>>^ Who has assigned to him the earth,
And who has appointed &#91;to him&#93; the productive land,^&#42;1^ even all of it?

[NOTE]
====
. “Productive land.” Heb., te·velʹ; Lat., orʹbem, “circle,” that is, of the earth.
====

[[v18-34-14]]

^<<v18-34-14,14>>^ If he sets his heart upon anyone,
&#91;If&#93; that one’s spirit and breath he gathers to himself,

[[v18-34-15]]

^<<v18-34-15,15>>^ All flesh will expire together,
And earthling man^&#42;1^ himself will return to the very dust.

[NOTE]
====
. “And earthling man.” Heb., weʼa·dhamʹ.
====

[[v18-34-16]]

^<<v18-34-16,16>>^ So if &#91;you have&#93; understanding, do listen to this;
Do give ear to the sound of my words.

[[v18-34-17]]

^<<v18-34-17,17>>^ Really will anyone hating justice control,
And if a powerful one is righteous will you pronounce &#91;him&#93; wicked?

[[v18-34-18]]

^<<v18-34-18,18>>^ Shall one say^&#42;1^ to a king, ‘You are good for nothing’?^&#42;2^
To nobles, ‘You are wicked’?

[NOTE]
====
. Lit., “Shall there be a saying.” In Heb. this is a verb in the infinitive construct, indefinite as to time and impersonal.
. Lit., “king, ‘Belial!’?”
====

[[v18-34-19]]

^<<v18-34-19,19>>^ &#91;There is One&#93; who has not shown partiality to princes
And has not given more consideration to the noble one than to the lowly one,
For all of them are the work of his hands.

[[v18-34-20]]

^<<v18-34-20,20>>^ In a moment they die, even in the middle of the night;
The people shake back and forth and pass away,
And powerful ones depart by no hand.

[[v18-34-21]]

^<<v18-34-21,21>>^ For his eyes are upon the ways of man,^&#42;1^
And all his steps he sees.

[NOTE]
====
. Or, “each one.” Heb., ʼish, as in vs 23.
====

[[v18-34-22]]

^<<v18-34-22,22>>^ There is no darkness nor any deep shadow
For those practicing what is hurtful to conceal themselves there.

[[v18-34-23]]

^<<v18-34-23,23>>^ For he sets no appointed time for any man
To go to God^&#42;1^ in judgment.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-34-24]]

^<<v18-34-24,24>>^ He breaks powerful ones without any investigation,
And he makes others stand up instead of them.

[[v18-34-25]]

^<<v18-34-25,25>>^ Therefore he recognizes what their works are,
And he does overthrow &#91;them&#93; at night, and they get crushed.

[[v18-34-26]]

^<<v18-34-26,26>>^ As wicked ones he does slap them
In the place of onlookers;

[[v18-34-27]]

^<<v18-34-27,27>>^ For the reason that they have turned aside from following him,
And none of his ways have they considered,

[[v18-34-28]]

^<<v18-34-28,28>>^ So as to cause the outcry of the lowly one to come to him;
And so he hears the outcry of the afflicted ones.

[[v18-34-29]]

^<<v18-34-29,29>>^ When he himself causes quietness, who, then, can condemn?
And when he conceals &#91;his&#93; face, who can behold him,
Whether it is toward a nation or toward a man,^&#42;1^ it being the same thing?

[NOTE]
====
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
====

[[v18-34-30]]

^<<v18-34-30,30>>^ So that an apostate man may not reign,
Nor there be snares of the people.

[[v18-34-31]]

^<<v18-34-31,31>>^ For will anyone actually say to God himself,
‘I have borne, although I do not act corruptly;

[[v18-34-32]]

^<<v18-34-32,32>>^ Although I behold nothing, instruct me yourself;
If any unrighteousness I have committed,
I shall not do &#91;it&#93; again’?

[[v18-34-33]]

^<<v18-34-33,33>>^ Will he make good for it from your standpoint because you do refuse &#91;judgment&#93;,
Because you yourself choose, and not I?
Even what you well know, speak.

[[v18-34-34]]

^<<v18-34-34,34>>^ Men of heart themselves will say to me—
Even a wise able-bodied man that is listening to me,

[[v18-34-35]]

^<<v18-34-35,35>>^ ‘Job himself speaks without knowledge,
And his words are without &#91;his&#93; having insight.’

[[v18-34-36]]

^<<v18-34-36,36>>^ My father, let Job be tested^&#42;1^ out to the limit
Over his replies among men of hurtfulness.

[NOTE]
====
. Or, “O that Job may be tested.”
====

[[v18-34-37]]

^<<v18-34-37,37>>^ For on top of his sin he adds revolt;
Among us he claps &#91;his hands&#93; and multiplies his sayings against the &#91;true&#93; God!”^&#42;1^

[NOTE]
====
. “Against the [true] God.” Heb., la·ʼElʹ. See App 1G.
====

'''

xref:018-job/018-job-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-job/018-job-035.adoc#v18-35-0[Próximo Capítulo &#62;]