include::./index.adoc[]

[[v18-37-0]]
=== Job, 37
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-37-1]]

^<<v18-37-1,1>>^ “Indeed at this my heart begins to tremble,
And it leaps up from its place.

[[v18-37-2]]

^<<v18-37-2,2>>^ Listen attentively, YOU men, to the rumbling of his voice,
And the growling that goes forth from his mouth.

[[v18-37-3]]

^<<v18-37-3,3>>^ Under the whole heavens he lets it loose,
And his lightning is to the extremities^&#42;1^ of the earth.

[NOTE]
====
. Lit., “wings.”
====

[[v18-37-4]]

^<<v18-37-4,4>>^ After it a sound roars;
He thunders with the sound of his superiority,
And he does not hold them back when his voice is heard.

[[v18-37-5]]

^<<v18-37-5,5>>^ God^&#42;1^ thunders with his voice in a wonderful way,
Doing great things that we cannot know.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-37-6]]

^<<v18-37-6,6>>^ For to the snow he says, ‘Fall earthward,’
And &#91;to&#93; the downpour of rain, even &#91;to&#93; the downpour of his strong rains.

[[v18-37-7]]

^<<v18-37-7,7>>^ On the hand of every earthling man he puts a seal
For every mortal man to know his work.

[[v18-37-8]]

^<<v18-37-8,8>>^ And the wild beast comes into the ambush,
And in its hiding places it dwells.

[[v18-37-9]]

^<<v18-37-9,9>>^ Out of the interior room comes the storm wind
And out of the north winds the cold.

[[v18-37-10]]

^<<v18-37-10,10>>^ By the breath of God^&#42;1^ the ice is given
And the breadth of waters is under constraint.^&#42;2^

[NOTE]
====
. “God.” Heb., ʼEl.
. Or, “is frozen.”
====

[[v18-37-11]]

^<<v18-37-11,11>>^ Yes, with moisture he burdens the cloud,
His light scatters the cloud mass,

[[v18-37-12]]

^<<v18-37-12,12>>^ And it is being turned round about by his steering &#91;them&#93; for their performance
Wherever he commands them upon the face of the productive land^&#42;1^ of the earth.

[NOTE]
====
. “Productive land of,” M(Heb., the·velʹ)T; Lat., orʹbis, “circle,” that is, of the earth.
====

[[v18-37-13]]

^<<v18-37-13,13>>^ Whether for a rod^&#42;1^ or for his land
Or for loving-kindness,^&#42;2^ he makes it produce effects.

[NOTE]
====
. Symbolizing correction or chastisement.
. Or, “loyal love.”
====

[[v18-37-14]]

^<<v18-37-14,14>>^ Do give ear to this, O Job;
Stand still and show yourself attentive to the wonderful works of God.

[[v18-37-15]]

^<<v18-37-15,15>>^ Do you know when God^&#42;1^ laid an appointment upon them,
And when he caused the light of his cloud to beam?

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-37-16]]

^<<v18-37-16,16>>^ Do you know about the poisings of the cloud,
The wonderful works of the One perfect in knowledge?

[[v18-37-17]]

^<<v18-37-17,17>>^ How your garments are hot
When the earth shows quietness^&#42;1^ from the south?

[NOTE]
====
. Or, “when there is a quieting of the earth.”
====

[[v18-37-18]]

^<<v18-37-18,18>>^ With him can you beat out the skies
Hard like a molten mirror?

[[v18-37-19]]

^<<v18-37-19,19>>^ Let us know what we should say to him;
We cannot produce &#91;words&#93; because of darkness.

[[v18-37-20]]

^<<v18-37-20,20>>^ Should it be related to him that I would speak?
Or has any man said that it will be communicated?

[[v18-37-21]]

^<<v18-37-21,21>>^ And now they do not really see the light;
It is brilliant in the skies,
When a wind^&#42;1^ itself has passed by and proceeded to cleanse them.

[NOTE]
====
. “When a wind.” Heb., weruʹach. See Ge 1:2 ftn, “Force.”
====

[[v18-37-22]]

^<<v18-37-22,22>>^ Out of the north golden splendor^&#42;1^ comes.
Upon God^&#42;2^ dignity is fear-inspiring.

[NOTE]
====
. Lit., “gold.” Heb., za·havʹ.
. “God.” Heb., ʼElohʹah.
====

[[v18-37-23]]

^<<v18-37-23,23>>^ As for the Almighty, we have not found him out;
He is exalted in power,
And justice and abundance of righteousness he will not belittle.

[[v18-37-24]]

^<<v18-37-24,24>>^ Therefore let men^&#42;1^ fear him.
He does not regard any who are wise in &#91;their own&#93; heart.”

[NOTE]
====
. “Men.” Heb., ʼana·shimʹ, pl. of ʼish.
====

'''

xref:018-job/018-job-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-job/018-job-038.adoc#v18-38-0[Próximo Capítulo &#62;]