include::./index.adoc[]

[[v18-41-0]]
=== Job, 41
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-41-1]]

^<<v18-41-1,1>>^ “Can you draw out Le·viʹa·than^&#42;1^ with a fishhook,
Or with a rope can you hold down its tongue?

[NOTE]
====
. “Leviathan,” M(Heb., liw·ya·thanʹ)Vg; LXX, “a dragon.”
====

[[v18-41-2]]

^<<v18-41-2,2>>^ Can you put a rush in its nostrils,
Or with a thorn can you bore its jaws?

[[v18-41-3]]

^<<v18-41-3,3>>^ Will it make many entreaties to you,
Or will it say soft words to you?

[[v18-41-4]]

^<<v18-41-4,4>>^ Will it conclude a covenant with you,
That you may take it as a slave to time indefinite?

[[v18-41-5]]

^<<v18-41-5,5>>^ Will you play with it as with a bird,
Or will you tie it for your young girls?

[[v18-41-6]]

^<<v18-41-6,6>>^ Will partners barter for it?^&#42;1^
Will they divide it up among tradesmen?^&#42;2^

[NOTE]
====
. Or, “make a feast over it.”
. Lit., “Canaanites.” Heb., kena·ʽanimʹ.
====

[[v18-41-7]]

^<<v18-41-7,7>>^ Will you fill its skin with harpoons,
Or its head with fish spears?

[[v18-41-8]]

^<<v18-41-8,8>>^ Put your hand upon it.
Remember the battle. Do not do it again.^&#42;1^

[NOTE]
====
. MLXX end chapter 40 here.
====

[[v18-41-9]]

^<<v18-41-9,9>>^ Look! One’s expectation about it will certainly be disappointed.
One will also be hurled down at the mere sight of it.

[[v18-41-10]]

^<<v18-41-10,10>>^ None is so audacious that he should stir it up.
And who is it that can hold his ground before me?

[[v18-41-11]]

^<<v18-41-11,11>>^ Who has given me something first, that I ought to reward him?
Under the whole heavens it is mine.

[[v18-41-12]]

^<<v18-41-12,12>>^ I shall not keep silent about its parts
Or the matter of &#91;its&#93; mightiness and the grace of its proportions.

[[v18-41-13]]

^<<v18-41-13,13>>^ Who has uncovered the face of its clothing?
Into its double jaw^&#42;1^ who will enter?

[NOTE]
====
. Lit., “bridle,” M; LXX, “scale armor [coat of mail].”
====

[[v18-41-14]]

^<<v18-41-14,14>>^ The doors of its face^&#42;1^ who has opened?
Its teeth round about are frightful.

[NOTE]
====
. “Face,” M; Sy, “mouth.”
====

[[v18-41-15]]

^<<v18-41-15,15>>^ Furrows of scales are its haughtiness,
Closed as with a tight seal.

[[v18-41-16]]

^<<v18-41-16,16>>^ One to the other they fit closely,
And not even air can come in between them.

[[v18-41-17]]

^<<v18-41-17,17>>^ Each one to the other^&#42;1^ they are stuck together;
They grasp one another and cannot be separated.

[NOTE]
====
. Lit., “to its brother.”
====

[[v18-41-18]]

^<<v18-41-18,18>>^ Its very sneezings flash forth light,
And its eyes are like the beams of dawn.

[[v18-41-19]]

^<<v18-41-19,19>>^ Out of its mouth there go lightning flashes,
Even sparks of fire make their escape.

[[v18-41-20]]

^<<v18-41-20,20>>^ Out of its nostrils smoke goes forth,
Like a furnace set aflame even with rushes.

[[v18-41-21]]

^<<v18-41-21,21>>^ Its soul^&#42;1^ itself sets coals ablaze,
And even a flame goes forth out of its mouth.

[NOTE]
====
. “Its soul.” Heb., naph·shohʹ; Gr., psy·kheʹ.
====

[[v18-41-22]]

^<<v18-41-22,22>>^ In its neck lodges strength,
And before it despair leaps.^&#42;1^

[NOTE]
====
. “Despair leaps,” M; LXX, “destruction runs.”
====

[[v18-41-23]]

^<<v18-41-23,23>>^ The folds of its flesh do cling together;
They are as a casting upon it, immovable.

[[v18-41-24]]

^<<v18-41-24,24>>^ Its heart is cast like stone,
Yes, cast like a lower millstone.

[[v18-41-25]]

^<<v18-41-25,25>>^ Due to its rising up the strong get frightened;
Due to consternation they get bewildered.

[[v18-41-26]]

^<<v18-41-26,26>>^ Overtaking it, the sword itself does not prove equal,
Nor spear, dart or arrowhead.

[[v18-41-27]]

^<<v18-41-27,27>>^ It regards iron as mere straw,
Copper as mere rotten wood.

[[v18-41-28]]

^<<v18-41-28,28>>^ An arrow^&#42;1^ does not chase it away;
The slingstones have been changed for it into mere stubble.

[NOTE]
====
. Lit., “A son of a bow.”
====

[[v18-41-29]]

^<<v18-41-29,29>>^ A club has been regarded &#91;by it&#93; as mere stubble,
And it laughs at the rattling of a javelin.

[[v18-41-30]]

^<<v18-41-30,30>>^ As pointed earthenware fragments^&#42;1^ are its underparts;
It spreads out a threshing instrument upon the mire.

[NOTE]
====
. Or, “The most pointed (sharpest) of earthenware fragments,” according to the Heb. idiom.
====

[[v18-41-31]]

^<<v18-41-31,31>>^ It causes the depths to boil just like a pot;
It makes the very sea like an ointment pot.

[[v18-41-32]]

^<<v18-41-32,32>>^ Behind itself it makes a pathway shine;^&#42;1^
One would regard the watery deep as gray-headedness.^&#42;2^

[NOTE]
====
. “And the Tartarus of the abyss as a captive,” LXX. See App 4D.
. “As gray-headedness,” M; LXX, “as a place to walk”; Sy, “as the dry land.”
====

[[v18-41-33]]

^<<v18-41-33,33>>^ Upon the dust there is not the like of it,
The one made to be without terror.

[[v18-41-34]]

^<<v18-41-34,34>>^ Everything high it sees.
It is king over all majestic wild beasts.”^&#42;1^

[NOTE]
====
. Lit., “all the sons of pride (dignity).”
====

'''

xref:018-job/018-job-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-job/018-job-042.adoc#v18-42-0[Próximo Capítulo &#62;]