include::./index.adoc[]

[[v18-29-0]]
=== Job, 29
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-29-1]]

^<<v18-29-1,1>>^ And Job proceeded again to lift up his proverbial utterance and went on to say:

[[v18-29-2]]

^<<v18-29-2,2>>^ “O that I were as in the lunar months of long ago,
As in the days when God^&#42;1^ was guarding me;

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-29-3]]

^<<v18-29-3,3>>^ When he caused his lamp to shine upon my head,
&#91;When&#93; I would walk &#91;through&#93; darkness by his light;

[[v18-29-4]]

^<<v18-29-4,4>>^ Just as I happened to be in the days of my prime,
When intimacy with God was at my tent;

[[v18-29-5]]

^<<v18-29-5,5>>^ When the Almighty was yet with me,
&#91;When&#93; my attendants were all around me!

[[v18-29-6]]

^<<v18-29-6,6>>^ When I washed my steps in butter,
And the rock kept pouring out streams of oil for me;^&#42;1^

[NOTE]
====
. Lit., “was being poured out as streams of oil with me.”
====

[[v18-29-7]]

^<<v18-29-7,7>>^ When I went forth to the gate by the town,
In the public square I would prepare my seat!

[[v18-29-8]]

^<<v18-29-8,8>>^ The boys saw me and hid themselves,
And even the aged ones rose up, they stood.

[[v18-29-9]]

^<<v18-29-9,9>>^ Princes themselves restrained words,
And the palm they would put upon their mouth.

[[v18-29-10]]

^<<v18-29-10,10>>^ The voice of the leaders themselves was hidden,
And their very tongue cleaved to their palate.

[[v18-29-11]]

^<<v18-29-11,11>>^ For the ear itself listened and proceeded to pronounce me happy,
And the eye itself saw and proceeded to bear witness for me.

[[v18-29-12]]

^<<v18-29-12,12>>^ For I would rescue the afflicted one crying for help,
And the fatherless boy and anyone that had no helper.

[[v18-29-13]]

^<<v18-29-13,13>>^ The blessing of the one about to perish—upon me it would come,
And the heart of the widow I would make glad.

[[v18-29-14]]

^<<v18-29-14,14>>^ With righteousness I clothed myself, and it was clothing me.
My justice was like a sleeveless coat—and a turban.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eyes I became to the blind one;
And feet to the lame one I was.

[[v18-29-16]]

^<<v18-29-16,16>>^ I was a real father to the poor ones;
And the legal case of one whom I did not know—I would examine it.

[[v18-29-17]]

^<<v18-29-17,17>>^ And I would break the jawbones of the wrongdoer,
And from his teeth I would tear^&#42;1^ away the prey.

[NOTE]
====
. “Tear,” by a slight correction; M, “throw.”
====

[[v18-29-18]]

^<<v18-29-18,18>>^ And I used to say, ‘Within my nest^&#42;1^ I shall expire,
And like the grains of sand I shall multiply &#91;my&#93; days.

[NOTE]
====
. “Within my nest.” Possibly, “In my old age,” to agree with LXX.
====

[[v18-29-19]]

^<<v18-29-19,19>>^ My root is opened for the waters,
And dew itself will stay overnight upon my bough.

[[v18-29-20]]

^<<v18-29-20,20>>^ My glory is fresh with me,
And my bow in my hand will shoot repeatedly.’

[[v18-29-21]]

^<<v18-29-21,21>>^ To me they listened; and they waited,
And they would keep silent for my counsel.

[[v18-29-22]]

^<<v18-29-22,22>>^ After my word they would not speak again,
And upon them my word would drip.

[[v18-29-23]]

^<<v18-29-23,23>>^ And they waited for me as for the rain,
And their mouth they opened wide for the spring rain.

[[v18-29-24]]

^<<v18-29-24,24>>^ I would smile at them—they would not believe &#91;it&#93;—
And the light of my face they would not cast down.

[[v18-29-25]]

^<<v18-29-25,25>>^ I would choose the way for them, and I was sitting as head;
And I resided as a king among &#91;his&#93; troops,
As one who comforts the mourners.

'''

xref:018-job/018-job-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-job/018-job-030.adoc#v18-30-0[Próximo Capítulo &#62;]