include::./index.adoc[]

[[v18-14-0]]
=== Job, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-14-1]]

^<<v18-14-1,1>>^ “Man,^&#42;1^ born of woman,
Is short-lived and glutted with agitation.

[NOTE]
====
. Or, “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v18-14-2]]

^<<v18-14-2,2>>^ Like a blossom he has come forth and is cut off,
And he runs away like the shadow and does not keep existing.^&#42;1^

[NOTE]
====
. Lit., “keep standing.” See Ex 9:16 ftn, “Existence.”
====

[[v18-14-3]]

^<<v18-14-3,3>>^ Yes, upon this one you have opened your eye,
And me^&#42;1^ you bring into judgment with you.

[NOTE]
====
. “Me,” M; LXXSyVg, “him.”
====

[[v18-14-4]]

^<<v18-14-4,4>>^ Who can produce someone clean out of someone unclean?
There is not one.^&#42;1^

[NOTE]
====
. Or, “No one can.”
====

[[v18-14-5]]

^<<v18-14-5,5>>^ If his days are decided,
The number of his months is with you;
A decree for him you have made that he may not go beyond.

[[v18-14-6]]

^<<v18-14-6,6>>^ Turn your gaze from upon him that he may have rest,^&#42;1^
Until he finds pleasure as a hired laborer does in his day.

[NOTE]
====
. Or, “may cease,” as in vs 7.
====

[[v18-14-7]]

^<<v18-14-7,7>>^ For there exists hope for even a tree.
If it gets cut down, it will even sprout again,^&#42;1^
And its own twig will not cease to be.

[NOTE]
====
. Lit., “yet change.”
====

[[v18-14-8]]

^<<v18-14-8,8>>^ If its root grows old in the earth
And in the dust its stump dies,

[[v18-14-9]]

^<<v18-14-9,9>>^ At the scent of water it will sprout
And it will certainly produce a bough like a new plant.

[[v18-14-10]]

^<<v18-14-10,10>>^ But an able-bodied man^&#42;1^ dies and lies vanquished;
And an earthling man^&#42;2^ expires, and where is he?^&#42;3^

[NOTE]
====
. “But an able-bodied man.” Heb., wegheʹver.
. “An earthling man.” Heb., ʼa·dhamʹ.
. “Where is he?” MVg; LXXSy, “he is no more.”
====

[[v18-14-11]]

^<<v18-14-11,11>>^ Waters do disappear from a sea,
And a river itself drains off and dries up.

[[v18-14-12]]

^<<v18-14-12,12>>^ Man^&#42;1^ also has to lie down and does not get up.
Until heaven is no more they will not wake up,
Nor will they be aroused from their sleep.^&#42;2^

[NOTE]
====
. Lit., “And man.” Heb., weʼishʹ.
. “He will not wake up, nor will he rouse himself from his sleep,” Vg and by a slight correction of M.
====

[[v18-14-13]]

^<<v18-14-13,13>>^ O that in Sheʹol^&#42;1^ you would conceal me,
That you would keep me secret until your anger turns back,
That you would set a time limit for me and remember me!

[NOTE]
====
. “In Sheol.” Heb., bish·ʼohlʹ; Gr., haiʹdei; Syr., ba·shiul; Lat., in·ferʹno; that is, the common grave of mankind. See App 4B.
====

[[v18-14-14]]

^<<v18-14-14,14>>^ If an able-bodied man^&#42;1^ dies can he live again?
All the days of my compulsory service I shall wait,
Until my relief comes.

[NOTE]
====
. “An able-bodied man.” Heb., geʹver.
====

[[v18-14-15]]

^<<v18-14-15,15>>^ You will call, and I myself shall answer you.
For the work of your hands you will have a yearning.

[[v18-14-16]]

^<<v18-14-16,16>>^ For now you keep counting my very steps;
You watch for nothing but my sin.

[[v18-14-17]]

^<<v18-14-17,17>>^ Sealed up in a bag is my revolt,
And you apply glue over my error.

[[v18-14-18]]

^<<v18-14-18,18>>^ However, a mountain itself, falling, will fade away,
And even a rock will be moved away from its place.

[[v18-14-19]]

^<<v18-14-19,19>>^ Water certainly rubs away even stones;
Its outpouring washes off earth’s dust.
So you have destroyed the very hope of mortal man.^&#42;1^

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
====

[[v18-14-20]]

^<<v18-14-20,20>>^ You overpower him forever so that he goes away;
You are disfiguring his face so that you send him away.

[[v18-14-21]]

^<<v18-14-21,21>>^ His sons get honored, but he does not know &#91;it&#93;;
And they become insignificant, but he does not consider them.

[[v18-14-22]]

^<<v18-14-22,22>>^ Only his own flesh while upon him will keep aching,
And his own soul while within him will keep mourning.”^&#42;1^

[NOTE]
====
. Or, “Only his own kin (fleshly relatives) will keep aching for him, and his own slaves (acquired souls) will keep mourning over him.” To contrast “fleshly relatives” and “acquired souls,” compare Ge 37:27 and Isa 58:7 with Ge (12:5; 14:21; 36:6); Eze 27:13; Re 18:13 ftn, “Souls.”
====

'''

xref:018-job/018-job-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-job/018-job-015.adoc#v18-15-0[Próximo Capítulo &#62;]