include::./index.adoc[]

[[v18-19-0]]
=== Job, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-19-1]]

^<<v18-19-1,1>>^ And Job proceeded to answer and say:

[[v18-19-2]]

^<<v18-19-2,2>>^ “How long will YOU men keep irritating my soul
And keep crushing me with words?

[[v18-19-3]]

^<<v18-19-3,3>>^ These ten times YOU proceeded to rebuke me;
YOU are not ashamed &#91;that&#93; YOU deal so hard with me.

[[v18-19-4]]

^<<v18-19-4,4>>^ And, granted that I have made a mistake,
It is with me that my mistake will lodge.^&#42;1^

[NOTE]
====
. LXX adds: “by saying a thing that was not necessary, and my sayings (utterances) are mistaken (err) and not seasonable (timely).”
====

[[v18-19-5]]

^<<v18-19-5,5>>^ If for a fact against me YOU men do put on great airs,
And YOU show my reproach to be proper against me,

[[v18-19-6]]

^<<v18-19-6,6>>^ KNOW, then, that God^&#42;1^ himself has misled me,
And his hunting net he has closed in upon me.

[NOTE]
====
. “God.” Heb., ʼElohʹah, sing. of ʼElo·himʹ.
====

[[v18-19-7]]

^<<v18-19-7,7>>^ Look! I keep crying out, ‘Violence!’ but I get no answer;
I keep crying for help, but there is no justice.

[[v18-19-8]]

^<<v18-19-8,8>>^ My very path he has blocked with a stone wall, and I cannot pass over;
And upon my roadways he puts darkness itself.

[[v18-19-9]]

^<<v18-19-9,9>>^ My own glory he has stripped from me,
And he takes away the crown of my head.

[[v18-19-10]]

^<<v18-19-10,10>>^ He pulls me down on all sides, and I go away;
And he pulls my hope out just like a tree.

[[v18-19-11]]

^<<v18-19-11,11>>^ His anger also grows hot against me,
And he keeps reckoning me as an adversary of his.

[[v18-19-12]]

^<<v18-19-12,12>>^ Unitedly his troops come and cast up their way against me,
And they camp round about my tent.

[[v18-19-13]]

^<<v18-19-13,13>>^ My own brothers he has put far away from me,
And the very ones knowing me have even turned aside from me.

[[v18-19-14]]

^<<v18-19-14,14>>^ My intimate acquaintances^&#42;1^ have ceased to be,
And those known by me have themselves forgotten me,

[NOTE]
====
. Or, “My relations.”
====

[[v18-19-15]]

^<<v18-19-15,15>>^ Those residing as aliens in my house; and my slave girls themselves reckon me as a stranger;
A real foreigner I have become in their eyes.

[[v18-19-16]]

^<<v18-19-16,16>>^ To my servant I have called, but he does not answer.
With my own mouth I keep imploring him for compassion.

[[v18-19-17]]

^<<v18-19-17,17>>^ My breath^&#42;1^ itself has become loathsome to my wife,
And I have become foul-smelling to the sons of my &#91;mother’s&#93; belly.

[NOTE]
====
. “My breath (spirit).” Heb., ru·chiʹ; Lat., haʹli·tum.
====

[[v18-19-18]]

^<<v18-19-18,18>>^ Also young boys themselves have rejected me;
Let me but rise up, and they begin to speak against me.

[[v18-19-19]]

^<<v18-19-19,19>>^ All the men of my intimate group detest me,
And those whom I loved have turned against me.

[[v18-19-20]]

^<<v18-19-20,20>>^ To my skin and to my flesh my bones actually cleave,
And I escape with the skin of my teeth.^&#42;1^

[NOTE]
====
. “And my flesh becomes hairless in my teeth,” by another derivation of the verb and some corrections of M. Compare 13:14.
====

[[v18-19-21]]

^<<v18-19-21,21>>^ Show me some favor, show me some favor, O YOU my companions,
For God’s^&#42;1^ own hand has touched me.

[NOTE]
====
. “God’s.” Heb., ʼElohʹah.
====

[[v18-19-22]]

^<<v18-19-22,22>>^ Why do YOU men keep persecuting me as God^&#42;1^ does,
And not become satisfied with my very flesh?

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-19-23]]

^<<v18-19-23,23>>^ O that now my words were written down!
O that in a book they were even inscribed!

[[v18-19-24]]

^<<v18-19-24,24>>^ With an iron stylus and &#91;with&#93; lead,
Forever in the rock O that they were hewn!

[[v18-19-25]]

^<<v18-19-25,25>>^ And I myself well know that my redeemer^&#42;1^ is alive,
And that, coming after &#91;me&#93;, he will rise up over &#91;the&#93; dust.

[NOTE]
====
. “My redeemer (repurchaser).” By extension of thought, “my avenger (vindicator).” Heb., goʹʼali; Lat., re·demʹptor. See Nu 35:21; Ps 19:14; Pr 23:11; Isa 63:16; Jer 50:34.
====

[[v18-19-26]]

^<<v18-19-26,26>>^ And after my skin, &#91;which&#93; they have skinned off,—this!
Yet reduced in my flesh^&#42;1^ I shall behold God,^&#42;2^

[NOTE]
====
. Lit., “Yet out of my flesh,” or, “Yet apart from my flesh.”
. “God.” Heb., ʼElohʹah.
====

[[v18-19-27]]

^<<v18-19-27,27>>^ Whom even I shall behold for myself,
And &#91;whom&#93; my very eyes will certainly see, but not some stranger.
My kidneys have failed deep within me.

[[v18-19-28]]

^<<v18-19-28,28>>^ For YOU men say, ‘Why do we keep persecuting him?’
When the very root of &#91;the&#93; matter is found in me.^&#42;1^

[NOTE]
====
. According to M; LXX, “we shall find in him.”
====

[[v18-19-29]]

^<<v18-19-29,29>>^ Be frightened for yourselves because of a sword,
For the sword means a raging against errors,
In order that YOU men may know there is a judge.”^&#42;1^

[NOTE]
====
. “There is a judge,” T and by a different vowel pointing of M (see 1Sa 24:15); others make it read, “there is an Almighty.”
====

'''

xref:018-job/018-job-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-job/018-job-020.adoc#v18-20-0[Próximo Capítulo &#62;]