include::./index.adoc[]

[[v18-13-0]]
=== Job, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-13-1]]

^<<v18-13-1,1>>^ “Look! All this my eye has seen,
My ear has heard and considers it.

[[v18-13-2]]

^<<v18-13-2,2>>^ What YOU men know I myself well know also;
I am not inferior to YOU.^&#42;1^

[NOTE]
====
. See 12:3 ftn.
====

[[v18-13-3]]

^<<v18-13-3,3>>^ However, I, for my part, would speak to the Almighty himself,
And in arguing with God^&#42;1^ I would find delight.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-13-4]]

^<<v18-13-4,4>>^ On the other hand, YOU men are smearers of falsehood;
All of YOU are physicians of no value.

[[v18-13-5]]

^<<v18-13-5,5>>^ If only YOU would absolutely keep silent,
That it might prove to be wisdom on YOUR part!

[[v18-13-6]]

^<<v18-13-6,6>>^ Hear, please, my counterarguments,
And to the pleadings of my lips pay attention.

[[v18-13-7]]

^<<v18-13-7,7>>^ Will YOU men speak unrighteousness for God himself,
And for him will YOU speak deceit?

[[v18-13-8]]

^<<v18-13-8,8>>^ Will YOU be treating him with partiality,
Or for the &#91;true&#93; God will YOU contend at law?

[[v18-13-9]]

^<<v18-13-9,9>>^ Would it be good that he sound YOU out?
Or as one trifles with mortal man will YOU trifle with him?

[[v18-13-10]]

^<<v18-13-10,10>>^ He will positively reprove YOU
If in secrecy YOU try to show partiality;^&#42;1^

[NOTE]
====
. “Show partiality,” M; TSyVg, “treat him with partiality.”
====

[[v18-13-11]]

^<<v18-13-11,11>>^ Will not his very dignity make YOU start up with fright,
And the very dread of him fall upon YOU?

[[v18-13-12]]

^<<v18-13-12,12>>^ YOUR memorable sayings are proverbs of ashes;
YOUR shield bosses^&#42;1^ are as shield bosses of clay.

[NOTE]
====
. Or, “your breastworks.”
====

[[v18-13-13]]

^<<v18-13-13,13>>^ KEEP silent before me, that I myself may speak.
Then let come upon me whatever it may be!

[[v18-13-14]]

^<<v18-13-14,14>>^ Why do I carry my flesh in my teeth
And place my own soul^&#42;1^ in my palm?

[NOTE]
====
. “And . . . my own soul.” Heb., wenaph·shiʹ; Gr., psy·khenʹ; Lat., aʹni·mam. Compare Jg 12:3; 1Sa 19:5.
====

[[v18-13-15]]

^<<v18-13-15,15>>^ Even if he would slay me, would I not wait?^&#42;1^
I would only argue to his face for my own ways.

[NOTE]
====
. Or, “I would not wait,” M; MmarginTSyVg, “for him I would wait.”
====

[[v18-13-16]]

^<<v18-13-16,16>>^ He^&#42;1^ would also be my salvation,
For before him no apostate will come in.

[NOTE]
====
. Or, “That.”
====

[[v18-13-17]]

^<<v18-13-17,17>>^ HEAR my word clear through,
And let my declaration be in YOUR ears.

[[v18-13-18]]

^<<v18-13-18,18>>^ Look! Please, I have presented a case of justice;
I well know that I myself am in the right.

[[v18-13-19]]

^<<v18-13-19,19>>^ Who is the one that will contend with me?
For now were I to become silent I should simply expire!

[[v18-13-20]]

^<<v18-13-20,20>>^ Only two things do not do^&#42;1^ to me;
In that case I shall not conceal myself just on your account;

[NOTE]
====
. “Do.” The Heb. verb is sing. to agree with “you” and “your(s)” addressed to God in vss 20-27.
====

[[v18-13-21]]

^<<v18-13-21,21>>^ Put your own hand far away from upon me,
And the fright of you—may it not terrify me.

[[v18-13-22]]

^<<v18-13-22,22>>^ Either call that I myself may answer;
Or may I speak, and you return me answer.

[[v18-13-23]]

^<<v18-13-23,23>>^ In what way do I have errors and sins?
Make me to know my own revolt and my own sin.

[[v18-13-24]]

^<<v18-13-24,24>>^ Why do you conceal your very face
And regard me as an enemy of yours?

[[v18-13-25]]

^<<v18-13-25,25>>^ Will you make a mere leaf driven about quiver,
Or keep chasing after mere dry stubble?

[[v18-13-26]]

^<<v18-13-26,26>>^ For you keep writing against me bitter things
And you make me possess &#91;the consequences of&#93; the errors of my youth.

[[v18-13-27]]

^<<v18-13-27,27>>^ You also keep my feet put in the stocks,
And you watch all my paths;
For the soles^&#42;1^ of my feet you mark your own line.

[NOTE]
====
. Lit., “roots of.”
====

[[v18-13-28]]

^<<v18-13-28,28>>^ And he^&#42;1^ is like something rotten^&#42;2^ that wears out;
Like a garment that a moth actually eats up.

[NOTE]
====
. “He,” that is, Job.
. “Something rotten (rottenness),” MVg; LXX, “skin bag”; Sy, “leather bag.”
====

'''

xref:018-job/018-job-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-job/018-job-014.adoc#v18-14-0[Próximo Capítulo &#62;]