include::./index.adoc[]

[[v18-39-0]]
=== Job, 39
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-39-1]]

^<<v18-39-1,1>>^ “Have you come to know the appointed time for the mountain goats of the crag to give birth?
Do you observe just when the hinds bring forth with birth pangs?

[[v18-39-2]]

^<<v18-39-2,2>>^ Do you count the lunar months that they fulfill,
Or have you come to know the appointed time that they give birth?

[[v18-39-3]]

^<<v18-39-3,3>>^ They bow down when they cast forth their young ones,
&#91;When&#93; they get rid of their pangs.^&#42;1^

[NOTE]
====
. Or, “let loose their fetuses.”
====

[[v18-39-4]]

^<<v18-39-4,4>>^ Their sons become robust, they get big in the open field;
They actually go forth and do not return to them.

[[v18-39-5]]

^<<v18-39-5,5>>^ Who sent forth the zebra free,
And who loosened the very bands of the wild ass,

[[v18-39-6]]

^<<v18-39-6,6>>^ Whose house I have appointed the desert plain
And whose dwelling places the salt country?

[[v18-39-7]]

^<<v18-39-7,7>>^ It laughs at the turmoil of a town;
The noises of a stalker it does not hear.

[[v18-39-8]]

^<<v18-39-8,8>>^ It explores mountains for its pasturage
And after every sort of green plant it seeks.

[[v18-39-9]]

^<<v18-39-9,9>>^ Does a wild bull want to serve you,
Or will it spend the night by your manger?

[[v18-39-10]]

^<<v18-39-10,10>>^ Will you bind a wild bull fast with its ropes in the furrow,
Or will it harrow low plains after you?

[[v18-39-11]]

^<<v18-39-11,11>>^ Will you trust in it because its power is abundant,
And will you leave your toil to it?

[[v18-39-12]]

^<<v18-39-12,12>>^ Will you rely on it that it will bring back your seed
And that it will gather to your threshing floor?

[[v18-39-13]]

^<<v18-39-13,13>>^ Has the wing of the female ostrich flapped joyously,
Or &#91;has she&#93; the pinions of a stork and the plumage?

[[v18-39-14]]

^<<v18-39-14,14>>^ For she leaves her eggs to the earth itself
And in the dust she keeps them warm,

[[v18-39-15]]

^<<v18-39-15,15>>^ And she forgets that some foot may crush them
Or even a wild beast of the field may tread on them.

[[v18-39-16]]

^<<v18-39-16,16>>^ She does treat her sons roughly, as if not hers—
In vain is her toil &#91;because she has&#93; no dread.

[[v18-39-17]]

^<<v18-39-17,17>>^ For God^&#42;1^ has made her forget wisdom,
And he has not given her a share in understanding.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-39-18]]

^<<v18-39-18,18>>^ At the time she flaps &#91;her wings&#93; on high,
She laughs at the horse and at its rider.

[[v18-39-19]]

^<<v18-39-19,19>>^ Can you give to the horse mightiness?
Can you clothe its neck with a rustling mane?^&#42;1^

[NOTE]
====
. “A rustling mane,” M; T, “strength.”
====

[[v18-39-20]]

^<<v18-39-20,20>>^ Can you cause it to leap like a locust?
The dignity of its snorting is frightful.

[[v18-39-21]]

^<<v18-39-21,21>>^ It paws^&#42;1^ in the low plain and exults in power;
It goes forth to meet armor.

[NOTE]
====
. “It paws,” LXXSyVg; M, “They paw.”
====

[[v18-39-22]]

^<<v18-39-22,22>>^ It laughs at dread, and is not terrified;
Nor does it turn back on account of a sword.

[[v18-39-23]]

^<<v18-39-23,23>>^ Against it a quiver rattles,
The blade of a spear and a javelin.

[[v18-39-24]]

^<<v18-39-24,24>>^ With pounding and excitement it swallows up the earth,
And it does not believe that it is the sound of a horn.

[[v18-39-25]]

^<<v18-39-25,25>>^ As soon as the horn blows it says Aha!
And from far off it smells the battle,
The uproar of chiefs^&#42;1^ and the war cry.

[NOTE]
====
. Lit., “princes.” Heb., sa·rimʹ.
====

[[v18-39-26]]

^<<v18-39-26,26>>^ Is it owing to your understanding that the falcon soars up,
That it spreads its wings to the south wind?

[[v18-39-27]]

^<<v18-39-27,27>>^ Or is it at your order that an eagle flies upward
And that it builds its nest high up,

[[v18-39-28]]

^<<v18-39-28,28>>^ That on a crag it resides and stays during the night
Upon the tooth of a crag and an inaccessible place?

[[v18-39-29]]

^<<v18-39-29,29>>^ From there it has to search for food;
Far into the distance its eyes keep looking.

[[v18-39-30]]

^<<v18-39-30,30>>^ And its young ones themselves keep sipping up blood;
And where the slain are, there it is.”

'''

xref:018-job/018-job-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-job/018-job-040.adoc#v18-40-0[Próximo Capítulo &#62;]