include::./index.adoc[]

[[v18-7-0]]
=== Job, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-7-1]]

^<<v18-7-1,1>>^ “Is there not a compulsory labor for mortal man on earth,
And are not his days like the days of a hired laborer?

[[v18-7-2]]

^<<v18-7-2,2>>^ Like a slave he pants for the shadow,
And like a hired laborer he waits for his wages.

[[v18-7-3]]

^<<v18-7-3,3>>^ Thus I have been made to possess worthless lunar months,
And nights of trouble they have counted out to me.

[[v18-7-4]]

^<<v18-7-4,4>>^ When I have lain down I have also said, ‘When shall I get up?’
And &#91;when&#93; evening actually goes its measure, I have also been glutted with restlessness until morning twilight.

[[v18-7-5]]

^<<v18-7-5,5>>^ My flesh has become clothed with maggots and lumps of dust;
My skin itself has formed crusts and dissolves.

[[v18-7-6]]

^<<v18-7-6,6>>^ My days themselves have become swifter than a weaver’s shuttle,
And they come to an end in hopelessness.

[[v18-7-7]]

^<<v18-7-7,7>>^ Remember that my life is wind;
That my eye will not see good again.

[[v18-7-8]]

^<<v18-7-8,8>>^ The eye of him that sees me will not behold me;
Your eyes will be upon me, but I shall not be.

[[v18-7-9]]

^<<v18-7-9,9>>^ The cloud certainly comes to its end and goes away;
So he that is going down to Sheʹol will not come up.

[[v18-7-10]]

^<<v18-7-10,10>>^ He will not return anymore to his house,
And his place will not acknowledge him anymore.

[[v18-7-11]]

^<<v18-7-11,11>>^ I, also, I shall not hold back my mouth.
I will speak in the distress of my spirit;^&#42;1^
I will be concerned with the bitterness of my soul!

[NOTE]
====
. “My spirit.” Heb., ru·chiʹ; Lat., spiʹri·tus.
====

[[v18-7-12]]

^<<v18-7-12,12>>^ Am I a sea or a sea monster,
That you should set a guard over me?

[[v18-7-13]]

^<<v18-7-13,13>>^ When I said, ‘My divan will comfort me,
My bed will help carry my concern,’

[[v18-7-14]]

^<<v18-7-14,14>>^ You even have terrified me with dreams,
And by visions you make me start up in fright,

[[v18-7-15]]

^<<v18-7-15,15>>^ So that my soul chooses suffocation,
Death rather than my bones.

[[v18-7-16]]

^<<v18-7-16,16>>^ I have rejected &#91;it&#93;; to time indefinite I would not live.
Cease from me, for my days are an exhalation.

[[v18-7-17]]

^<<v18-7-17,17>>^ What is mortal man that you should rear him,^&#42;1^
And that you should set your heart upon him,

[NOTE]
====
. Or, “make much of him.”
====

[[v18-7-18]]

^<<v18-7-18,18>>^ And that you should pay attention to him every morning,
That every moment you should test him?

[[v18-7-19]]

^<<v18-7-19,19>>^ Why will you not turn your gaze from me,
Nor let me alone until I swallow my saliva?^&#42;1^

[NOTE]
====
. That is, alone for the briefest time. See Nu 4:20 ftn.
====

[[v18-7-20]]

^<<v18-7-20,20>>^ If I have sinned, what can I accomplish against you, the Observer of mankind?^&#42;1^
Why is it that you have set me as your target, so that I should become a burden to you?^&#42;2^

[NOTE]
====
. “Mankind.” Heb., ha·ʼa·dhamʹ.
. “You,” LXX and the original Heb. text; M, “myself.” This is one of the Eighteen Emendations of the Jewish Sopherim. See App 2B.
====

[[v18-7-21]]

^<<v18-7-21,21>>^ And why do you not pardon my transgression
And overlook my error?
For now in dust I shall lie down;
And you will certainly look for me, and I shall not be.”

'''

xref:018-job/018-job-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-job/018-job-008.adoc#v18-8-0[Próximo Capítulo &#62;]