include::./index.adoc[]

[[v18-35-0]]
=== Job, 35
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-35-1]]

^<<v18-35-1,1>>^ And E·liʹhu continued answering and saying:

[[v18-35-2]]

^<<v18-35-2,2>>^ “Is this what you have regarded as justice?
You have said, ‘My righteousness is more than God’s.’^&#42;1^

[NOTE]
====
. “More than God’s.” Heb., me·ʼElʹ; LXX, “Jehovah.”
====

[[v18-35-3]]

^<<v18-35-3,3>>^ For you say, ‘Of what use is it to you?
What benefit do I have more than by my sinning?’

[[v18-35-4]]

^<<v18-35-4,4>>^ I myself shall reply to you
And to your companions^&#42;1^ with you.

[NOTE]
====
. “Companions,” M; LXX, “three friends.”
====

[[v18-35-5]]

^<<v18-35-5,5>>^ Look up to heaven and see,
And behold the clouds, &#91;that&#93; they are indeed higher than you.

[[v18-35-6]]

^<<v18-35-6,6>>^ If you actually sin, what do you accomplish against him?
And &#91;if&#93; your revolts actually increase, what do you do to him?

[[v18-35-7]]

^<<v18-35-7,7>>^ If you are really in the right, what do you give him,
Or what does he receive from your own hand?

[[v18-35-8]]

^<<v18-35-8,8>>^ Your wickedness may be against a man^&#42;1^ like you,
And your righteousness to a son of earthling man.^&#42;2^

[NOTE]
====
. “Against a man.” Heb., leʼishʹ.
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v18-35-9]]

^<<v18-35-9,9>>^ Because of the multitude of oppressions they keep calling for aid;
They keep crying for help because of the arm of the great ones.

[[v18-35-10]]

^<<v18-35-10,10>>^ And yet no one has said, ‘Where is God^&#42;1^ my Grand Maker,^&#42;2^
The One giving melodies in the night?’

[NOTE]
====
. “God.” Heb., ʼElohʹah.
. “Grand Maker,” pl. in M, to denote excellence and grandeur, although “God” is sing.
====

[[v18-35-11]]

^<<v18-35-11,11>>^ He is the One teaching us more than the beasts^&#42;1^ of the earth,
And he makes us wiser than even the flying creatures of the heavens.

[NOTE]
====
. Or, “the domestic animals.”
====

[[v18-35-12]]

^<<v18-35-12,12>>^ There they keep crying out, but he does not answer,
Because of the pride of the bad ones.

[[v18-35-13]]

^<<v18-35-13,13>>^ Only the untruth God^&#42;1^ does not hear,
And the Almighty himself does not behold it.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-35-14]]

^<<v18-35-14,14>>^ How much less, then, when you say you do not behold him!
The legal case is before him, and so you should wait anxiously for him.

[[v18-35-15]]

^<<v18-35-15,15>>^ And now because his anger has not called for an accounting,
He has also not taken note of the extreme rashness.

[[v18-35-16]]

^<<v18-35-16,16>>^ And Job himself opens his mouth wide simply for nothing;
Without knowledge he multiplies mere words.”

'''

xref:018-job/018-job-034.adoc#v18-34-0[&#60; Capítulo Anterior] | <<v18-35-0,Topo>> | xref:018-job/018-job-036.adoc#v18-36-0[Próximo Capítulo &#62;]