include::./index.adoc[]

[[v18-2-0]]
=== Job, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-2-1]]

^<<v18-2-1,1>>^ Afterward it came to be the day when the sons^&#42;1^ of the &#91;true&#93; God entered to take their station before Jehovah, and Satan^&#42;2^ also proceeded to enter right among them to take his station before Jehovah.

[NOTE]
====
. “The angels,” LXX.
. See 1:6 ftn, “Satan.”
====

[[v18-2-2]]

^<<v18-2-2,2>>^ Then Jehovah said to Satan: “Just where do you come from?” At that Satan answered Jehovah and said: “From roving about in the earth and from walking about in it.”

[[v18-2-3]]

^<<v18-2-3,3>>^ And Jehovah went on to say to Satan: “Have you set your heart upon my servant Job, that there is no one like him in the earth, a man blameless and upright, fearing God and turning aside from bad? Even yet he is holding fast his integrity, although you incite me against him to swallow him up without cause.”

[[v18-2-4]]

^<<v18-2-4,4>>^ But Satan answered Jehovah and said: “Skin in behalf of skin, and everything that a man has he will give in behalf of his soul.^&#42;1^

[NOTE]
====
. “His soul (life).” Heb., naph·shohʹ; Gr., psy·khesʹ; Lat., aʹni·ma. See App 4A.
====

[[v18-2-5]]

^<<v18-2-5,5>>^ For a change, thrust out your hand, please, and touch as far as his bone and his flesh &#91;and see&#93; whether he will not curse^&#42;1^ you to your very face.”

[NOTE]
====
. See 1:5 ftn.
====

[[v18-2-6]]

^<<v18-2-6,6>>^ Accordingly Jehovah said to Satan: “There he is in your hand! Only watch out for his soul^&#42;1^ itself!”

[NOTE]
====
. See vs 4 ftn.
====

[[v18-2-7]]

^<<v18-2-7,7>>^ So Satan went out away from the person^&#42;1^ of Jehovah and struck Job with a malignant boil from the sole of his foot to the crown of his head.

[NOTE]
====
. See 1:12 ftn.
====

[[v18-2-8]]

^<<v18-2-8,8>>^ And he proceeded to take for himself a fragment of earthenware with which to scrape himself; and he was sitting in among the ashes.

[[v18-2-9]]

^<<v18-2-9,9>>^ Finally his wife said to him: “Are you yet holding fast your integrity? Curse^&#42;1^ God and die!”

[NOTE]
====
. See 1:5 ftn.
====

[[v18-2-10]]

^<<v18-2-10,10>>^ But he said to her: “As one of the senseless women speaks, you speak also. Shall we accept merely what is good from the &#91;true&#93; God and not accept also what is bad?” In all this Job did not sin with his lips.

[[v18-2-11]]

^<<v18-2-11,11>>^ And three companions of Job got to hear of all this calamity that had come upon him, and they proceeded to come, each one from his own place, Elʹi·phaz the Teʹman·ite and Bilʹdad the Shuʹhite and Zoʹphar the Naʹa·ma·thite. So they met together by appointment to come and sympathize with him and comfort him.

[[v18-2-12]]

^<<v18-2-12,12>>^ When they raised their eyes from far off they did not then recognize him. And they proceeded to raise their voice and weep and rip each one his sleeveless coat apart and toss dust toward the heavens upon their heads.

[[v18-2-13]]

^<<v18-2-13,13>>^ And they kept sitting with him on the earth seven days and seven nights, and there was no one speaking a word to him, for they saw that the pain was very great.

'''

xref:018-job/018-job-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-job/018-job-003.adoc#v18-3-0[Próximo Capítulo &#62;]