include::./index.adoc[]

[[v18-26-0]]
=== Job, 26
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-26-1]]

^<<v18-26-1,1>>^ And Job proceeded to answer and say:

[[v18-26-2]]

^<<v18-26-2,2>>^ “O how much help you have been to one without power!
O &#91;how&#93; you have saved an arm that is without strength!

[[v18-26-3]]

^<<v18-26-3,3>>^ How much you have advised one that is without wisdom,
And you have made practical wisdom itself known to the multitude!

[[v18-26-4]]

^<<v18-26-4,4>>^ To whom have you told words,
And whose breath^&#42;1^ has come forth from you?

[NOTE]
====
. “And whose breath.” Heb., wenish·math-miʹ.
====

[[v18-26-5]]

^<<v18-26-5,5>>^ Those impotent in death^&#42;1^ keep trembling
Beneath the waters and those residing in them.

[NOTE]
====
. “Those impotent in death.” Heb., hor·pha·ʼimʹ; in earlier occurrences translated “the Rephaim”; LXXVg, “giants.”
====

[[v18-26-6]]

^<<v18-26-6,6>>^ Sheʹol is naked in front of him,
And &#91;the place of&#93; destruction^&#42;1^ has no covering.

[NOTE]
====
. “And [the place of] destruction.” Heb., la·ʼavad·dohnʹ, “Abaddon,” the first occurrence of this Heb. word; Gr., a·po·leiʹai; Lat., per·di·ti·oʹni. Compare “Apollyon” in Re 9:11 where see ftns.
====

[[v18-26-7]]

^<<v18-26-7,7>>^ He is stretching out the north over the empty place,
Hanging the earth upon nothing;

[[v18-26-8]]

^<<v18-26-8,8>>^ Wrapping up the waters in his clouds,
So that the cloud mass is not split under them;

[[v18-26-9]]

^<<v18-26-9,9>>^ Enclosing the face of the throne,^&#42;1^
Spreading out^&#42;2^ over it his cloud.

[NOTE]
====
. “The throne.” By a different vowel pointing, “his full moon.”
. “Spreading out.” In Heb. the mixed form of this verb is understood to be in the infinitive absolute, indefinite as to time and impersonal.
====

[[v18-26-10]]

^<<v18-26-10,10>>^ He has described a circle upon the face of the waters,
To where light ends in darkness.

[[v18-26-11]]

^<<v18-26-11,11>>^ The very pillars of heaven shake,
And they are amazed because of his rebuke.

[[v18-26-12]]

^<<v18-26-12,12>>^ By his power he has stirred up the sea,
And by his understanding he has broken the stormer^&#42;1^ to pieces.

[NOTE]
====
. “The stormer.” Heb., raʹhav. Possibly a sea monster.
====

[[v18-26-13]]

^<<v18-26-13,13>>^ By his wind^&#42;1^ he has polished up heaven itself,
His hand has pierced the gliding serpent.

[NOTE]
====
. “By his wind (spirit).” Heb., beru·chohʹ; Lat., spiʹri·tus.
====

[[v18-26-14]]

^<<v18-26-14,14>>^ Look! These are the fringes of his ways,
And what a whisper of a matter has been heard of him!
But of his mighty thunder who can show an understanding?”

'''

xref:018-job/018-job-025.adoc#v18-25-0[&#60; Capítulo Anterior] | <<v18-26-0,Topo>> | xref:018-job/018-job-027.adoc#v18-27-0[Próximo Capítulo &#62;]