include::./index.adoc[]

[[v18-16-0]]
=== Job, 16
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-16-1]]

^<<v18-16-1,1>>^ And Job proceeded to answer and say:

[[v18-16-2]]

^<<v18-16-2,2>>^ “I have heard many things like these.
All of YOU are troublesome comforters!

[[v18-16-3]]

^<<v18-16-3,3>>^ Is there an end to windy words?
Or what galls^&#42;1^ you, that you answer?

[NOTE]
====
. Lit., “pains [offends].”
====

[[v18-16-4]]

^<<v18-16-4,4>>^ I myself also could well speak as YOU men do.
If only YOUR souls existed where my soul is,
Would I be brilliant in words^&#42;1^ against YOU,
And would I wag my head against YOU?

[NOTE]
====
. “Let me join words,” according to another derivation of the verb.
====

[[v18-16-5]]

^<<v18-16-5,5>>^ I would strengthen YOU with the words of my mouth,
And the consolation of my own lips would hold back—.

[[v18-16-6]]

^<<v18-16-6,6>>^ If I do speak, my own pain is not held back,
And if I do cease doing so, what goes away from me?

[[v18-16-7]]

^<<v18-16-7,7>>^ Only now he has made me weary;
He has made all those assembling with me desolate.

[[v18-16-8]]

^<<v18-16-8,8>>^ You also seize me. It has become a witness,
So that my leanness rises up against me. In my face it testifies.

[[v18-16-9]]

^<<v18-16-9,9>>^ His very anger has torn &#91;me&#93; to pieces, and he harbors animosity against me.
He actually grinds his teeth against me.
My adversary himself sharpens his eyes against me.

[[v18-16-10]]

^<<v18-16-10,10>>^ They have opened their mouth wide against me,
With reproach they have struck my cheeks,
In large number they mass themselves against me.

[[v18-16-11]]

^<<v18-16-11,11>>^ God^&#42;1^ hands me over to young boys,^&#42;2^
And into the hands of wicked ones he throws me headlong.

[NOTE]
====
. “God.” Heb., ʼEl.
. Lit., “a young boy,” M; LXXVg, “an unjust one.”
====

[[v18-16-12]]

^<<v18-16-12,12>>^ I had come to be at ease, but he proceeded to shake me up;
And he grabbed me by the back of the neck and proceeded to smash me,
And he sets me up as a target for himself.

[[v18-16-13]]

^<<v18-16-13,13>>^ His archers encircle me;
He splits open my kidneys and feels no compassion;
He pours out my gallbladder to the very earth.

[[v18-16-14]]

^<<v18-16-14,14>>^ He keeps breaking through me with breach after breach;
He runs at me like a mighty one.

[[v18-16-15]]

^<<v18-16-15,15>>^ Sackcloth I have sewed together over my skin,
And I have thrust my horn in the very dust.

[[v18-16-16]]

^<<v18-16-16,16>>^ My face itself has become reddened from weeping,
And upon my eyelids there is deep shadow,^&#42;1^

[NOTE]
====
. Lit., “death shadow.”
====

[[v18-16-17]]

^<<v18-16-17,17>>^ Although there is no violence upon my palms,
And my prayer is pure.

[[v18-16-18]]

^<<v18-16-18,18>>^ O earth, do not cover my blood!
And let there prove to be no place for my outcry!

[[v18-16-19]]

^<<v18-16-19,19>>^ Also now, look! in the heavens is one testifying about me,
And my witness^&#42;1^ is in the heights.

[NOTE]
====
. “And my witness.” Heb., wesa·hadhiʹ, considered an Aram. loanword. See Ge 31:47 ftn, “Jegar-sahadutha.”
====

[[v18-16-20]]

^<<v18-16-20,20>>^ My companions are spokesmen against me;
To God^&#42;1^ my eye has looked sleeplessly.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-16-21]]

^<<v18-16-21,21>>^ And the decision is to be made between an able-bodied man and God,
The same as between a son of man^&#42;1^ and his fellow.

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
====

[[v18-16-22]]

^<<v18-16-22,22>>^ For just a few years^&#42;1^ are to come,
And by the path by which I shall not return I shall go away.

[NOTE]
====
. “Just numbered years,” LXX.
====

'''

xref:018-job/018-job-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-job/018-job-017.adoc#v18-17-0[Próximo Capítulo &#62;]