include::./index.adoc[]

[[v18-32-0]]
=== Job, 32
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-32-1]]

^<<v18-32-1,1>>^ So these three men ceased from answering Job, for he was righteous in his^&#42;1^ own eyes.

[NOTE]
====
. “His,” M; LXXSy, “their.”
====

[[v18-32-2]]

^<<v18-32-2,2>>^ But the anger of E·liʹhu^&#42;1^ the son of Barʹa·chel the Buzʹite of the family of Ram came to be hot. Against Job his anger blazed over his declaring his own soul righteous rather than God.^&#42;2^

[NOTE]
====
. Meaning “My God Is He.”
. “Than God.” Heb., me·ʼElo·himʹ; LXX, “Jehovah.”
====

[[v18-32-3]]

^<<v18-32-3,3>>^ Also, against his three companions his anger blazed over the fact that they had not found an answer but they proceeded to pronounce God^&#42;1^ wicked.

[NOTE]
====
. “God,” originally. M, “Job.” The Jewish Sopherim changed the original text from “God” to “Job.” This is one of the Eighteen Emendations. See App 2B.
====

[[v18-32-4]]

^<<v18-32-4,4>>^ And E·liʹhu himself had waited for Job with words, because they were older than he was in days.

[[v18-32-5]]

^<<v18-32-5,5>>^ And E·liʹhu gradually saw that there was no answer in the mouth of the three men, and his anger kept getting hotter.

[[v18-32-6]]

^<<v18-32-6,6>>^ And E·liʹhu the son of Barʹa·chel the Buzʹite proceeded to answer and say:
“Young I am in days
And YOU men are aged.
That is why I drew back^&#42;1^ and was afraid
To declare my knowledge to YOU men.

[NOTE]
====
. Or, “I feared.” Heb., za·chalʹti.
====

[[v18-32-7]]

^<<v18-32-7,7>>^ I said, ‘Days themselves should speak,
And a multitude of years are what should make wisdom known.’

[[v18-32-8]]

^<<v18-32-8,8>>^ Surely it is the spirit in mortal men
And the breath of the Almighty &#91;that&#93; gives them understanding.

[[v18-32-9]]

^<<v18-32-9,9>>^ It is not those merely abundant in days that prove wise,
Nor those just old that understand judgment.

[[v18-32-10]]

^<<v18-32-10,10>>^ Therefore I said, ‘Do listen to me.
I shall declare my knowledge, even I.’

[[v18-32-11]]

^<<v18-32-11,11>>^ Look! I have waited for the words of YOU men,
I kept giving ear to YOUR reasonings,
Until YOU could search for words &#91;to say&#93;.

[[v18-32-12]]

^<<v18-32-12,12>>^ And to YOU I kept my attention turned,
And here there is no one reproving Job,
None of YOU answering his sayings,

[[v18-32-13]]

^<<v18-32-13,13>>^ That YOU may not say, ‘We have found wisdom;
It is God^&#42;1^ that drives him away, not a man.’

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-32-14]]

^<<v18-32-14,14>>^ As he has not arrayed words against me,
So with the sayings of YOU men I shall not reply to him.

[[v18-32-15]]

^<<v18-32-15,15>>^ They have been terrified, they have answered no more;
Words have moved away from them.

[[v18-32-16]]

^<<v18-32-16,16>>^ And I have waited, for they do not continue speaking;
For they stood still, they answered no more.

[[v18-32-17]]

^<<v18-32-17,17>>^ I shall give in answer my part, even I;
I shall declare my knowledge, even I;

[[v18-32-18]]

^<<v18-32-18,18>>^ For I have become full of words;
Spirit has brought pressure upon me in my belly.

[[v18-32-19]]

^<<v18-32-19,19>>^ Look! My belly is like wine that has no vent;
Like new skin bottles it wants to burst open.

[[v18-32-20]]

^<<v18-32-20,20>>^ Let me speak that it may be a relief to me.
I shall open my lips that I may answer.

[[v18-32-21]]

^<<v18-32-21,21>>^ Let me not, please, show partiality to a man;^&#42;1^
And on an earthling man^&#42;2^ I shall not bestow a title;

[NOTE]
====
. “Man.” Heb., ʼish.
. “Earthling man.” Heb., ʼa·dhamʹ.
====

[[v18-32-22]]

^<<v18-32-22,22>>^ For I certainly do not know how I can bestow a title;
Easily my Maker would carry me away.

'''

xref:018-job/018-job-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-job/018-job-033.adoc#v18-33-0[Próximo Capítulo &#62;]