include::./index.adoc[]

[[v18-31-0]]
=== Job, 31
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-31-1]]

^<<v18-31-1,1>>^ “A covenant I have concluded with my eyes.
So how could I show myself attentive to a virgin?

[[v18-31-2]]

^<<v18-31-2,2>>^ And what portion is there from God^&#42;1^ above,
Or inheritance from the Almighty from on high?

[NOTE]
====
. “God.” Heb., ʼElohʹah; Gr., ho The·osʹ.
====

[[v18-31-3]]

^<<v18-31-3,3>>^ Is there not disaster for a wrongdoer,
And misfortune for those practicing what is hurtful?

[[v18-31-4]]

^<<v18-31-4,4>>^ Does he not himself see my ways
And count even all my steps?

[[v18-31-5]]

^<<v18-31-5,5>>^ If I have walked with &#91;men of&#93; untruth,
And my foot hastens to deception,

[[v18-31-6]]

^<<v18-31-6,6>>^ He will weigh me in accurate scales^&#42;1^
And God^&#42;2^ will get to know my integrity.

[NOTE]
====
. Lit., “in scales of righteousness.”
. “God.” Heb., ʼElohʹah; LXX, “Jehovah.”
====

[[v18-31-7]]

^<<v18-31-7,7>>^ If my stepping deviates from the way,
Or my heart has walked merely after my eyes,
Or any defect has stuck in my own palms,

[[v18-31-8]]

^<<v18-31-8,8>>^ Let me sow seed and someone else eat,
And let my own descendants be rooted out.

[[v18-31-9]]

^<<v18-31-9,9>>^ If my heart has been enticed toward a woman,
And I kept lying in wait at the very entranceway of my companion,

[[v18-31-10]]

^<<v18-31-10,10>>^ Let my wife do the grinding for another man,
And over her let other men kneel down.

[[v18-31-11]]

^<<v18-31-11,11>>^ For that would be loose conduct,
And that would be an error for &#91;attention by&#93; the justices.

[[v18-31-12]]

^<<v18-31-12,12>>^ For that is a fire that would eat clear to destruction,^&#42;1^
And among all my produce it would take root.

[NOTE]
====
. “Destruction.” Heb., ʼavad·dohnʹ. See 26:6 ftn.
====

[[v18-31-13]]

^<<v18-31-13,13>>^ If I used to refuse the judgment of my slave man
Or of my slave girl in their case at law with me,

[[v18-31-14]]

^<<v18-31-14,14>>^ Then what can I do when God^&#42;1^ rises up?
And when he calls for an accounting, what can I answer him?

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-31-15]]

^<<v18-31-15,15>>^ Did not the One making me in the belly make him,
And did not just One proceed to prepare us in the womb?

[[v18-31-16]]

^<<v18-31-16,16>>^ If I used to hold back the lowly ones from &#91;their&#93; delight,
And the eyes of the widow I would cause to fail,

[[v18-31-17]]

^<<v18-31-17,17>>^ And I used to eat my morsel by myself,
While the fatherless boy did not eat from it

[[v18-31-18]]

^<<v18-31-18,18>>^ (For from my youth he grew up with me as with a father,
And from the belly of my mother I kept leading her);

[[v18-31-19]]

^<<v18-31-19,19>>^ If I used to see anyone perishing from having no garment,
Or that the poor one had no covering;

[[v18-31-20]]

^<<v18-31-20,20>>^ If his loins did not bless me,
Nor from the shorn wool of my young rams he would warm himself;

[[v18-31-21]]

^<<v18-31-21,21>>^ If I waved my hand to and fro against the fatherless boy,
When I would see &#91;need of&#93; my assistance in the gate,

[[v18-31-22]]

^<<v18-31-22,22>>^ Let my own shoulder blade fall from its shoulder,
And let my own arm be broken from its upper bone.

[[v18-31-23]]

^<<v18-31-23,23>>^ For disaster from God^&#42;1^ was a dread to me,
And against his dignity I could not hold out.

[NOTE]
====
. “God.” Heb., ʼEl; Gr., Ky·riʹou, “Jehovah.”
====

[[v18-31-24]]

^<<v18-31-24,24>>^ If I have put gold^&#42;1^ as my confidence,
Or to gold^&#42;2^ I have said, ‘You are my trust!’

[NOTE]
====
. “Gold.” Heb., za·havʹ.
. “Or to gold.” Heb., welak·keʹthem. See 28:16 ftn.
====

[[v18-31-25]]

^<<v18-31-25,25>>^ If I used to rejoice because my property was much,
And because my hand had found a lot of things;

[[v18-31-26]]

^<<v18-31-26,26>>^ If I used to see the light when it would flash forth,
Or the precious moon walking along,

[[v18-31-27]]

^<<v18-31-27,27>>^ And my heart began to be enticed in secrecy
And my hand proceeded to kiss my mouth,^&#42;1^

[NOTE]
====
. Apparently alluding to throwing a kiss with the hand in an idolatrous practice. Kissing of idols is mentioned in 1Ki 19:18; Ho 13:2.
====

[[v18-31-28]]

^<<v18-31-28,28>>^ That too would be an error for &#91;attention by&#93; the justices,
For I should have denied the &#91;true&#93; God above.

[[v18-31-29]]

^<<v18-31-29,29>>^ If I used to rejoice at the extinction of one intensely hating me,
Or I felt excited^&#42;1^ because evil had found him—

[NOTE]
====
. “Felt excited,” M; T, “made a joyful noise.”
====

[[v18-31-30]]

^<<v18-31-30,30>>^ And I did not allow my palate to sin
By asking for an oath against his soul.

[[v18-31-31]]

^<<v18-31-31,31>>^ If the men of my tent did not say,
‘Who can produce anyone that has not been satisfied from food^&#42;1^ of his?’—

[NOTE]
====
. Lit., “flesh; meat.”
====

[[v18-31-32]]

^<<v18-31-32,32>>^ Outside no alien resident would spend the night;
My doors I kept open to the path.^&#42;1^

[NOTE]
====
. “Path,” M; TLXXSyVg, “traveler.”
====

[[v18-31-33]]

^<<v18-31-33,33>>^ If like an earthling man^&#42;1^ I covered over my transgressions
By hiding my error in my shirt pocket—

[NOTE]
====
. “Like an earthling man (Adam; man).” Heb., kheʼa·dhamʹ, possibly, “from man; among men.”
====

[[v18-31-34]]

^<<v18-31-34,34>>^ Because I would suffer a shock at a large crowd,
Or the contempt itself of families would terrorize me
And I would keep silent, I would not go out of the entrance.

[[v18-31-35]]

^<<v18-31-35,35>>^ O that I had someone listening to me,
That according to my signature^&#42;1^ the Almighty himself would answer me!
Or that the individual^&#42;2^ in the case at law with me had written a document itself!

[NOTE]
====
. Lit., “mark,” evidently in writing, confirming a legal document.
. Lit., “man.” Heb., ʼish.
====

[[v18-31-36]]

^<<v18-31-36,36>>^ Surely upon my shoulder I would carry it;
I would bind it around me like a grand crown.

[[v18-31-37]]

^<<v18-31-37,37>>^ The number of my steps I would tell him;
Like a leader I would approach him.

[[v18-31-38]]

^<<v18-31-38,38>>^ If against me my own ground would cry for aid,
And together its furrows themselves would weep;

[[v18-31-39]]

^<<v18-31-39,39>>^ If its fruitage^&#42;1^ I have eaten without money,
And the soul of its owners I have caused to pant,

[NOTE]
====
. Lit., “its power.” Heb., ko·chahʹ.
====

[[v18-31-40]]

^<<v18-31-40,40>>^ Instead of wheat let the thorny weed go forth,
And instead of barley stinking weeds.”
The words of Job have come to an end.

'''

xref:018-job/018-job-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-job/018-job-032.adoc#v18-32-0[Próximo Capítulo &#62;]