include::./index.adoc[]

[[v18-28-0]]
=== Job, 28
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-28-1]]

^<<v18-28-1,1>>^ “Indeed, for silver there exists a place to find it
And a place for gold that they refine;

[[v18-28-2]]

^<<v18-28-2,2>>^ Iron itself is taken from the very dust
And &#91;from&#93; stone copper is being poured out.

[[v18-28-3]]

^<<v18-28-3,3>>^ An end to the darkness he has set;
And to every limit he is searching out
Stone in the gloom and deep shadow.

[[v18-28-4]]

^<<v18-28-4,4>>^ He has sunk a shaft far from where &#91;people&#93; reside as aliens,
Places forgotten far from the foot;
Some of mortal men^&#42;1^ have swung down, they have dangled.

[NOTE]
====
. “Some of mortal men.” Heb., me·ʼenohshʹ.
====

[[v18-28-5]]

^<<v18-28-5,5>>^ As for the earth, out of it food goes forth;
But underneath it, it has been upturned as if by fire.

[[v18-28-6]]

^<<v18-28-6,6>>^ Its stones are the place of the sapphire,
And it has gold dust.

[[v18-28-7]]

^<<v18-28-7,7>>^ A pathway—no bird of prey has known it,
Nor has the eye of a black kite caught sight of it.

[[v18-28-8]]

^<<v18-28-8,8>>^ The majestic wild beasts^&#42;1^ have not trodden it down solid;
The young lion has not paced over it.

[NOTE]
====
. Lit., “The sons of pride (dignity).”
====

[[v18-28-9]]

^<<v18-28-9,9>>^ Upon the flint he has thrust out his hand;
He has overthrown mountains from &#91;their&#93; root;

[[v18-28-10]]

^<<v18-28-10,10>>^ Into the rocks he has channeled water-filled galleries,
And all precious things his eye has seen.

[[v18-28-11]]

^<<v18-28-11,11>>^ The places from which rivers trickled he has dammed up,
And the concealed thing he brings forth to the light.

[[v18-28-12]]

^<<v18-28-12,12>>^ But wisdom—where can it be found,
And where, now, is the place of understanding?

[[v18-28-13]]

^<<v18-28-13,13>>^ Mortal man has not come to know its valuation,^&#42;1^
And it is not found in the land of those living.

[NOTE]
====
. “Valuation,” MSyVg; LXX, “way.”
====

[[v18-28-14]]

^<<v18-28-14,14>>^ The watery deep^&#42;1^ itself has said,
‘It is not in me!’
The sea too has said, ‘It is not with me!’

[NOTE]
====
. Or, “surging waters.” Heb., tehohmʹ, as in Ge 1:2; Gr., aʹbys·sos; Lat., a·bysʹsus.
====

[[v18-28-15]]

^<<v18-28-15,15>>^ Pure gold cannot be given in exchange for it,
And silver cannot be weighed out as its price.

[[v18-28-16]]

^<<v18-28-16,16>>^ It cannot be paid for with gold^&#42;1^ of Oʹphir,
With the rare onyx stone and the sapphire.

[NOTE]
====
. “With gold.” Heb., bekheʹthem, an Egyptian loanword.
====

[[v18-28-17]]

^<<v18-28-17,17>>^ Gold^&#42;1^ and glass cannot be compared to it,
Nor is any vessel of refined gold an exchange for it.

[NOTE]
====
. “Gold.” Heb., za·havʹ.
====

[[v18-28-18]]

^<<v18-28-18,18>>^ Coral and rock crystal themselves will not be mentioned,
But a bagful of wisdom is worth more than &#91;one full of&#93; pearls.

[[v18-28-19]]

^<<v18-28-19,19>>^ The topaz of Cush^&#42;1^ cannot be compared to it;
It cannot be paid for even with gold in its purity.

[NOTE]
====
. “Cush,” M(Heb., Kush)Sy; LXXVg, “Ethiopia.”
====

[[v18-28-20]]

^<<v18-28-20,20>>^ But wisdom itself—from where does it come,
And where, now, is the place of understanding?

[[v18-28-21]]

^<<v18-28-21,21>>^ It has been hidden even from the eyes of everyone alive,
And from the flying creatures of the heavens it has been concealed.

[[v18-28-22]]

^<<v18-28-22,22>>^ Destruction^&#42;1^ and death themselves have said,
‘With our ears we have heard a report of it.’

[NOTE]
====
. “Destruction.” Heb., ʼavad·dohnʹ. See 26:6 ftn.
====

[[v18-28-23]]

^<<v18-28-23,23>>^ God^&#42;1^ is the One who has understood its way,
And he himself has known its place,

[NOTE]
====
. “God.” Heb., ʼElo·himʹ.
====

[[v18-28-24]]

^<<v18-28-24,24>>^ For he himself looks to the very ends of the earth;
Under the whole heavens^&#42;1^ he sees,

[NOTE]
====
. “Under the whole heavens,” MSy; LXXVg, “everything under the heavens.”
====

[[v18-28-25]]

^<<v18-28-25,25>>^ To make a weight for the wind,^&#42;1^
While he has proportioned the waters themselves by a measure;

[NOTE]
====
. “For the wind.” Heb., la·ruʹach; Gr., a·neʹmon; Lat., venʹtis.
====

[[v18-28-26]]

^<<v18-28-26,26>>^ When he made for the rain a regulation,
And a way for the thunderous storm cloud,

[[v18-28-27]]

^<<v18-28-27,27>>^ Then it was that he saw &#91;wisdom&#93;^&#42;1^ and proceeded to tell about it;
He prepared it and also searched it through.

[NOTE]
====
. Lit., “it,” fem., referring to wisdom.
====

[[v18-28-28]]

^<<v18-28-28,28>>^ And he went on to say to man,^&#42;1^
‘Look! The fear of Jehovah^&#42;2^—that is wisdom,
And to turn away from bad is understanding.’”

[NOTE]
====
. Or, “to earthling man.” Heb., la·ʼa·dhamʹ.
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

'''

xref:018-job/018-job-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-job/018-job-029.adoc#v18-29-0[Próximo Capítulo &#62;]