include::./index.adoc[]

[[v18-23-0]]
=== Job, 23
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-23-1]]

^<<v18-23-1,1>>^ And Job proceeded to answer and say:

[[v18-23-2]]

^<<v18-23-2,2>>^ “Even today my state of concern is rebelliousness;
My own hand is heavy on account of my sighing.

[[v18-23-3]]

^<<v18-23-3,3>>^ O that I really knew where I might find him!
I would come clear to his fixed place.

[[v18-23-4]]

^<<v18-23-4,4>>^ I would present before^&#42;1^ him a case of justice,
And my mouth I would fill with counterarguments;

[NOTE]
====
. Or, “against.” Compare Ge 10:9 ftn, “Opposition to.”
====

[[v18-23-5]]

^<<v18-23-5,5>>^ I would know the words with which he answers me,
And I would consider what he says to me.

[[v18-23-6]]

^<<v18-23-6,6>>^ Would he with an abundance of power contend with me?
O no! Surely he himself would pay heed to me.

[[v18-23-7]]

^<<v18-23-7,7>>^ There the upright one himself will certainly set matters straight with him,
And I would go safe forever from my judge.^&#42;1^

[NOTE]
====
. Or, “from my opponent-at-law,” by a correction.
====

[[v18-23-8]]

^<<v18-23-8,8>>^ Look! To the east I go, and he is not there;
And back again, and I cannot discern him;

[[v18-23-9]]

^<<v18-23-9,9>>^ To the left where he is working, but I cannot behold &#91;him&#93;;
He turns aside^&#42;1^ to the right, but I do not see &#91;him&#93;.

[NOTE]
====
. “I turn aside,” SyVg.
====

[[v18-23-10]]

^<<v18-23-10,10>>^ For he well knows the way I take.
&#91;After&#93; he has tested me out, I shall come forth as gold itself.

[[v18-23-11]]

^<<v18-23-11,11>>^ Of his steps^&#42;1^ my foot has laid hold;
His way I have kept, and I do not deviate.

[NOTE]
====
. “Steps,” LXXSyVg; M, “step.”
====

[[v18-23-12]]

^<<v18-23-12,12>>^ &#91;From&#93; the commandment of his lips I do not move away.
I have treasured up the sayings of his mouth more than what is prescribed for me.

[[v18-23-13]]

^<<v18-23-13,13>>^ And he is in one &#91;mind&#93;, and who can resist him?
And his own soul has a desire, and he will do &#91;it&#93;.

[[v18-23-14]]

^<<v18-23-14,14>>^ For he will carry out completely what is prescribed for me,
And things like these are many with him.

[[v18-23-15]]

^<<v18-23-15,15>>^ That is why I feel disturbed because of him;
I show myself attentive and am in dread of him.

[[v18-23-16]]

^<<v18-23-16,16>>^ Even God^&#42;1^ himself has made my heart timid,
And the Almighty himself has disturbed me.

[NOTE]
====
. “Even God.” Heb., weʼElʹ.
====

[[v18-23-17]]

^<<v18-23-17,17>>^ For I have not been put to silence because of darkness,
Nor because gloom has covered my own face.

'''

xref:018-job/018-job-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-job/018-job-024.adoc#v18-24-0[Próximo Capítulo &#62;]