include::./index.adoc[]

[[v18-15-0]]
=== Job, 15
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-15-1]]

^<<v18-15-1,1>>^ And Elʹi·phaz the Teʹman·ite proceeded to answer and say:

[[v18-15-2]]

^<<v18-15-2,2>>^ “Will a wise person himself answer with windy knowledge,^&#42;1^
Or will he fill his belly with the east wind?

[NOTE]
====
. Lit., “knowledge of wind.” Heb.,  dha·ʽath-ruʹach.
====

[[v18-15-3]]

^<<v18-15-3,3>>^ Merely reproving with a word will be of no use,
And mere utterances will be of no benefit by themselves.

[[v18-15-4]]

^<<v18-15-4,4>>^ However, you yourself make fear &#91;before God&#93; to have no force,
And you diminish the having of any concern before God.^&#42;1^

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-15-5]]

^<<v18-15-5,5>>^ For your error trains your mouth,^&#42;1^
And you choose the tongue of shrewd people.

[NOTE]
====
. Or, “your mouth teaches your error.” LXX, “you are guilty by the words of your mouth”; Sy, “your mouth teaches sin.”
====

[[v18-15-6]]

^<<v18-15-6,6>>^ Your mouth pronounces you wicked, and not I;
And your own lips answer against you.

[[v18-15-7]]

^<<v18-15-7,7>>^ Were you the very first man^&#42;1^ to be born,
Or before the hills were you brought forth with labor pains?

[NOTE]
====
. “Man.” Heb., ʼa·dhamʹ.
====

[[v18-15-8]]

^<<v18-15-8,8>>^ To the confidential talk of God^&#42;1^ do you listen,
And do you limit wisdom to yourself?

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-15-9]]

^<<v18-15-9,9>>^ What do you actually know that we do not know?
What do you understand that is not also with us?

[[v18-15-10]]

^<<v18-15-10,10>>^ Both the gray-headed and the aged one are with us,
The one greater than your father in days.

[[v18-15-11]]

^<<v18-15-11,11>>^ Are the consolations of God^&#42;1^ not enough for you,
Or a word &#91;spoken&#93; gently with you?

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-15-12]]

^<<v18-15-12,12>>^ Why does your heart carry you away,
And why do your eyes flash?

[[v18-15-13]]

^<<v18-15-13,13>>^ For you turn your spirit against God himself,
And you have caused words to go forth from your own mouth.

[[v18-15-14]]

^<<v18-15-14,14>>^ What is mortal man^&#42;1^ that he should be clean,
Or that anyone born of a woman should be in the right?

[NOTE]
====
. “Mortal man.” Heb., ʼenohshʹ.
====

[[v18-15-15]]

^<<v18-15-15,15>>^ Look! In his holy ones he has no faith,
And the heavens themselves are actually not clean in his eyes.

[[v18-15-16]]

^<<v18-15-16,16>>^ How much less so when one is detestable and corrupt,
A man who is drinking in unrighteousness just like water!

[[v18-15-17]]

^<<v18-15-17,17>>^ I shall declare it to you. Listen to me!
Even this I have beheld, so let me relate &#91;it&#93;,

[[v18-15-18]]

^<<v18-15-18,18>>^ That which wise ones themselves tell
And which they did not hide, &#91;it being&#93; from their fathers.

[[v18-15-19]]

^<<v18-15-19,19>>^ To them alone the land was given,
And no stranger passed through the midst of them.

[[v18-15-20]]

^<<v18-15-20,20>>^ All his days a wicked one is suffering torture,
Even the very number of years that have been reserved for the tyrant.

[[v18-15-21]]

^<<v18-15-21,21>>^ The sound of dreadful things is in his ears;
During peace a despoiler himself comes upon him.

[[v18-15-22]]

^<<v18-15-22,22>>^ He does not believe that he will come back out of darkness,
And he is reserved for a sword.

[[v18-15-23]]

^<<v18-15-23,23>>^ He is straying about in search of bread^&#42;1^—where is it?
He well knows that the day of darkness is ready at his hand.

[NOTE]
====
. Or, “food.”
====

[[v18-15-24]]

^<<v18-15-24,24>>^ Distress and anguish keep terrifying him;
They overpower him like a king in readiness for the assault.

[[v18-15-25]]

^<<v18-15-25,25>>^ Because he stretches out his hand against God^&#42;1^ himself,
And over the Almighty he tries to show himself superior;

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-15-26]]

^<<v18-15-26,26>>^ &#91;Because&#93; he runs against him stiff-neckedly,
With the thick bosses of his shields;

[[v18-15-27]]

^<<v18-15-27,27>>^ Because he actually covers his face with his fattiness
And he puts on fat upon his loins,

[[v18-15-28]]

^<<v18-15-28,28>>^ He merely resides in cities that are to be effaced;
In houses in which people will not keep dwelling,
Which certainly prove destined for heaps of stones.

[[v18-15-29]]

^<<v18-15-29,29>>^ He will not grow rich and his wealth will not mount up,
Nor will he spread out the acquisition^&#42;1^ of them over the earth.

[NOTE]
====
. “Acquisition.” The meaning in M is uncertain; LXX, “shadow”; Vg, “root.”
====

[[v18-15-30]]

^<<v18-15-30,30>>^ He will not turn away from darkness;
His twig a flame will dry up,
And he will turn aside by a blast^&#42;1^ of His mouth.

[NOTE]
====
. “By a blast of.” Heb., beruʹach.
====

[[v18-15-31]]

^<<v18-15-31,31>>^ Let him put no faith in worthlessness, being led astray,
For mere worthlessness will prove to be what he gets in exchange;

[[v18-15-32]]

^<<v18-15-32,32>>^ Before his day^&#42;1^ will it be fulfilled.
And his shoot itself will certainly not grow luxuriantly.

[NOTE]
====
. Lit., “in not his day.”
====

[[v18-15-33]]

^<<v18-15-33,33>>^ He will thrust away his unripe grapes just like a vine,
And cast off his blossoms just like an olive tree.

[[v18-15-34]]

^<<v18-15-34,34>>^ For the assembly of apostates is sterile,
And fire itself must eat up the tents of bribery.

[[v18-15-35]]

^<<v18-15-35,35>>^ There is a conceiving of trouble and a giving birth to what is hurtful,
And their belly itself prepares deceit.”

'''

xref:018-job/018-job-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-job/018-job-016.adoc#v18-16-0[Próximo Capítulo &#62;]