include::./index.adoc[]

[[v18-30-0]]
=== Job, 30
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-30-1]]

^<<v18-30-1,1>>^ “And now they have laughed at me,
Those younger in days than I am,
Whose fathers I would have refused
To place with the dogs of my flock.

[[v18-30-2]]

^<<v18-30-2,2>>^ Even the power of their hands—of what use was it to me?
In them vigor has perished.

[[v18-30-3]]

^<<v18-30-3,3>>^ Because of want and hunger they are sterile,
Gnawing at a waterless region,
&#91;Where&#93; yesterday there were storm and desolation.

[[v18-30-4]]

^<<v18-30-4,4>>^ They were plucking the salt herb by the bushes,
And the root of broom trees was their food.

[[v18-30-5]]

^<<v18-30-5,5>>^ From the community they would be driven away;
People would shout at them as at a thief.

[[v18-30-6]]

^<<v18-30-6,6>>^ &#91;They have&#93; to reside on the very slope of torrent valleys,
In holes of the dust and in rocks.

[[v18-30-7]]

^<<v18-30-7,7>>^ Among the bushes they would cry out;
Under the nettles they would huddle together.

[[v18-30-8]]

^<<v18-30-8,8>>^ Sons of the senseless one, also sons of the nameless one,
They have been scourged out of the land.

[[v18-30-9]]

^<<v18-30-9,9>>^ And now I have become even the theme of their song,
And I am to them for a byword.

[[v18-30-10]]

^<<v18-30-10,10>>^ They have detested me, they have kept themselves far from me;
And from my face they did not hold back &#91;their&#93; spit.

[[v18-30-11]]

^<<v18-30-11,11>>^ For he loosened &#91;my&#93; own bowstring and proceeded to humble me,
And the bridle they left loose on my account.

[[v18-30-12]]

^<<v18-30-12,12>>^ At &#91;my&#93; right hand they rise up as a brood;
My feet they have let go,
But they proceeded to cast up against me their disastrous barriers.

[[v18-30-13]]

^<<v18-30-13,13>>^ They have torn down my roadways;
They were beneficial only for adversity to me,
Without their having any helper.

[[v18-30-14]]

^<<v18-30-14,14>>^ As through a wide gap they proceed to come;
Under a storm they have rolled along.

[[v18-30-15]]

^<<v18-30-15,15>>^ Sudden terrors have been turned upon me;
My noble bearing is chased like the wind,^&#42;1^
And like a cloud my salvation has passed away.

[NOTE]
====
. “Like the wind.” Heb., ka·ruʹach. See Ge 1:2 ftn, “Force.”
====

[[v18-30-16]]

^<<v18-30-16,16>>^ And now my soul is poured out within me;
Days of affliction take hold upon me.

[[v18-30-17]]

^<<v18-30-17,17>>^ At night my very bones have been bored through &#91;and dropped&#93; from off me,
And &#91;pains&#93; gnawing me do not take any rest.

[[v18-30-18]]

^<<v18-30-18,18>>^ By the abundance of power my garment takes on a change;
Like the collar of my long garment it engirdles me.

[[v18-30-19]]

^<<v18-30-19,19>>^ He has brought me down to the clay,
So that I show myself like dust and ashes.

[[v18-30-20]]

^<<v18-30-20,20>>^ I cry to you for help, but you do not answer me;
I have stood, that you might show yourself attentive to me.

[[v18-30-21]]

^<<v18-30-21,21>>^ You change yourself to become cruel to me;
With the full might of your hand you harbor animosity toward me.

[[v18-30-22]]

^<<v18-30-22,22>>^ You lift me to the wind, you cause me to ride &#91;it&#93;;
Then you dissolve me with a crash.

[[v18-30-23]]

^<<v18-30-23,23>>^ For I well know that to death you will make me turn back,
And to the house of meeting for everyone living.

[[v18-30-24]]

^<<v18-30-24,24>>^ Only no one thrusts his hand out against a mere heap of ruins,
Nor during one’s decay is there a cry for help respecting those things.

[[v18-30-25]]

^<<v18-30-25,25>>^ Certainly I have wept for the one having a hard day;
My soul has grieved for the poor one.

[[v18-30-26]]

^<<v18-30-26,26>>^ Although for good I waited, yet bad came;
And I kept awaiting the light, but gloom came.

[[v18-30-27]]

^<<v18-30-27,27>>^ My own intestines were made to boil and did not keep silent;
Days of affliction confronted me.

[[v18-30-28]]

^<<v18-30-28,28>>^ Saddened I walked about when there was no sunlight;^&#42;1^
I got up in the congregation,^&#42;2^ I kept crying for help.

[NOTE]
====
. “Sunlight,” M; by a correction, “comfort.”
. “In the congregation.” Heb., vaq·qa·halʹ; Gr., ek·kle·siʹai.
====

[[v18-30-29]]

^<<v18-30-29,29>>^ A brother to jackals I became,
And a companion to the daughters of the ostrich.

[[v18-30-30]]

^<<v18-30-30,30>>^ My very skin became black &#91;and dropped&#93; off me,
And my very bones became hot from dryness.

[[v18-30-31]]

^<<v18-30-31,31>>^ And my harp came to be merely for mourning,
And my pipe for the voice of weeping ones.

'''

xref:018-job/018-job-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-job/018-job-031.adoc#v18-31-0[Próximo Capítulo &#62;]