include::./index.adoc[]

[[v18-33-0]]
=== Job, 33
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-33-1]]

^<<v18-33-1,1>>^ “Now, however, O Job, please hear my words,^&#42;1^
And to all my speaking^&#42;2^ do give ear.

[NOTE]
====
. “My words.” Heb., mil·laiʹ.
. Lit., “my words.” Heb., deva·raiʹ.
====

[[v18-33-2]]

^<<v18-33-2,2>>^ Look, please! I have to open my mouth;
My tongue with my palate has to speak.

[[v18-33-3]]

^<<v18-33-3,3>>^ My sayings are the uprightness of my heart,
And knowledge is what my lips do utter sincerely.

[[v18-33-4]]

^<<v18-33-4,4>>^ God’s own spirit^&#42;1^ made me,
And the Almighty’s own breath proceeded to bring me to life.

[NOTE]
====
. Lit., “The spirit of God.” Heb., ru·ach-ʼElʹ.
====

[[v18-33-5]]

^<<v18-33-5,5>>^ If you are able, make reply to me,
Array &#91;words&#93; before me; do take your station.

[[v18-33-6]]

^<<v18-33-6,6>>^ Look! I am to the &#91;true&#93; God just what you are;
From the clay I was shaped, I too.

[[v18-33-7]]

^<<v18-33-7,7>>^ Look! No frightfulness in me will terrify you,
And no pressure by me will be heavy upon you.

[[v18-33-8]]

^<<v18-33-8,8>>^ Only you have said in my ears,
And the sound of &#91;your&#93; words I kept hearing,

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘I am pure without transgression;
Clean I am, and I have no error.

[[v18-33-10]]

^<<v18-33-10,10>>^ Look! Occasions for opposition to me he finds,
He takes me for an enemy of his.

[[v18-33-11]]

^<<v18-33-11,11>>^ He puts my feet in the stocks,
He watches all my paths.’

[[v18-33-12]]

^<<v18-33-12,12>>^ Look! In this you have not been in the right, I answer you;
For God^&#42;1^ is much more than mortal man.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-33-13]]

^<<v18-33-13,13>>^ Why is it against him that you contended,
Because all your words he does not answer?

[[v18-33-14]]

^<<v18-33-14,14>>^ For God^&#42;1^ speaks once,
And twice—though one does not regard it—

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-33-15]]

^<<v18-33-15,15>>^ In a dream, a vision of the night,
When deep sleep falls upon men,
During slumbers upon the bed.

[[v18-33-16]]

^<<v18-33-16,16>>^ It is then that he uncovers the ear of men,
And on exhortation to them he puts his seal,

[[v18-33-17]]

^<<v18-33-17,17>>^ To turn aside a man^&#42;1^ from his deed,
And that he may cover pride itself from an able-bodied man.^&#42;2^

[NOTE]
====
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
. “From an able-bodied man.” Heb., mig·geʹver.
====

[[v18-33-18]]

^<<v18-33-18,18>>^ He keeps his soul back from the pit
And his life from passing away by a missile.^&#42;1^

[NOTE]
====
. “From passing away by a missile.” BHK proposes corrections that would make this read, “from passing over into Sheol,” thus running parallel with “pit” in the first part of the vs.
====

[[v18-33-19]]

^<<v18-33-19,19>>^ And he is actually reproved with pain upon his bed,
And the quarreling of his bones is continual.

[[v18-33-20]]

^<<v18-33-20,20>>^ And his life certainly makes bread loathsome,
And his own soul desirable food.

[[v18-33-21]]

^<<v18-33-21,21>>^ His flesh wastes away from sight,
And his bones that were not seen certainly grow bare.

[[v18-33-22]]

^<<v18-33-22,22>>^ And his soul draws near to the pit,
And his life to those inflicting death.^&#42;1^

[NOTE]
====
. “To those inflicting death.” By a correction of M, “to dead ones”; or, “to the place of dead ones.”
====

[[v18-33-23]]

^<<v18-33-23,23>>^ If there exists for him a messenger,^&#42;1^
A spokesman,^&#42;2^ one out of a thousand,
To tell to man his uprightness,^&#42;3^

[NOTE]
====
. Or, “an angel.” Lat., anʹge·lus.
. Or, “an interpreter.”
. “His uprightness,” M; LXX, “his own blame. He will show his want of understanding.”
====

[[v18-33-24]]

^<<v18-33-24,24>>^ Then he favors him and says,
‘Let him off from going down into the pit!
I have found a ransom!^&#42;1^

[NOTE]
====
. Or, “covering.” Heb., khoʹpher.
====

[[v18-33-25]]

^<<v18-33-25,25>>^ Let his flesh become fresher than in youth;
Let him return to the days of his youthful vigor.’

[[v18-33-26]]

^<<v18-33-26,26>>^ He will make entreaty to God^&#42;1^ that he may take pleasure in him,
And he will see his face with joyful shouting,
And He will restore His righteousness to mortal man.^&#42;2^

[NOTE]
====
. “God.” Heb., ʼElohʹah; LXX, “Jehovah.”
. “To mortal man.” Heb., le·ʼenohshʹ.
====

[[v18-33-27]]

^<<v18-33-27,27>>^ He will sing to men and say,
‘I have sinned; and what is upright I have perverted,
And it certainly was not the proper thing for me.

[[v18-33-28]]

^<<v18-33-28,28>>^ He has redeemed my^&#42;1^ soul from passing into the pit,
And my life itself will see the light.’

[NOTE]
====
. “My,” MLXXSy; MmarginTVg, “his.”
====

[[v18-33-29]]

^<<v18-33-29,29>>^ Look! All these things God^&#42;1^ performs,
Two times, three times, in the case of an able-bodied man,

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-33-30]]

^<<v18-33-30,30>>^ To turn his soul back from the pit,
That he may be enlightened with the light^&#42;1^ of those living.

[NOTE]
====
. According to M; Sy, “to see the light.”
====

[[v18-33-31]]

^<<v18-33-31,31>>^ Pay attention, O Job! Listen to me!
Keep silent, and I myself shall continue speaking.

[[v18-33-32]]

^<<v18-33-32,32>>^ If there are any words &#91;to say&#93;, make reply to me;
Speak, for I have taken delight in your righteousness.

[[v18-33-33]]

^<<v18-33-33,33>>^ If there are none, you yourself listen to me;
Keep silent, and I shall teach you wisdom.”

'''

xref:018-job/018-job-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-job/018-job-034.adoc#v18-34-0[Próximo Capítulo &#62;]