include::./index.adoc[]

[[v18-8-0]]
=== Job, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-8-1]]

^<<v18-8-1,1>>^ And Bilʹdad the Shuʹhite proceeded to answer and say:

[[v18-8-2]]

^<<v18-8-2,2>>^ “How long will you keep uttering these things,
When the sayings of your mouth are but a powerful wind?

[[v18-8-3]]

^<<v18-8-3,3>>^ Will God^&#42;1^ himself pervert judgment,
Or will the Almighty himself pervert righteousness?

[NOTE]
====
. “God.” Heb., ha·ʼElʹ. Here ha is an interrogative particle introducing a question.
====

[[v18-8-4]]

^<<v18-8-4,4>>^ If your own sons have sinned against him,
So that he lets them go into the hand of their revolt,

[[v18-8-5]]

^<<v18-8-5,5>>^ If you yourself will look for God,
And &#91;if&#93; of the Almighty you will implore favor,

[[v18-8-6]]

^<<v18-8-6,6>>^ If you are pure and upright,
By now he would awake for you^&#42;1^
And he would certainly restore your righteous abiding place.

[NOTE]
====
. According to M; LXX, “he will listen to your supplication.”
====

[[v18-8-7]]

^<<v18-8-7,7>>^ Also, your beginning may have proved to be a small thing,
But your own end afterward would grow very great.

[[v18-8-8]]

^<<v18-8-8,8>>^ Indeed, ask, please, of the former generation,
And direct &#91;your attention&#93; to the things searched out by their fathers.

[[v18-8-9]]

^<<v18-8-9,9>>^ For we were only yesterday, and we know nothing,
Because our days on earth are a shadow.

[[v18-8-10]]

^<<v18-8-10,10>>^ Will not they themselves instruct you, tell you,^&#42;1^
And from their heart will they not bring forth words?

[NOTE]
====
. “Tell you,” LXX; M, “say to you.”
====

[[v18-8-11]]

^<<v18-8-11,11>>^ Will a papyrus plant grow tall without a swampy place?
Will a reed grow big without water?

[[v18-8-12]]

^<<v18-8-12,12>>^ While it is yet in its bud, not plucked off,
Even ahead of all other grass it will dry up.

[[v18-8-13]]

^<<v18-8-13,13>>^ Thus are the pathways^&#42;1^ of all those forgetting God,^&#42;2^
And the very hope of an apostate^&#42;3^ will perish,

[NOTE]
====
. “Pathways,” M; LXX, “the final things (outcome); the end afterward.”
. “God.” Heb., ʼEl; LXX, “Jehovah.”
. Or, “ungodly (profane) one”; or, “anyone alienated from God.”
====

[[v18-8-14]]

^<<v18-8-14,14>>^ Whose confidence is cut off,
And whose trust is a spider’s house.^&#42;1^

[NOTE]
====
. Or, “web.”
====

[[v18-8-15]]

^<<v18-8-15,15>>^ He will lean upon his house, but it will not keep standing;
He will take hold of it, but it will not last.

[[v18-8-16]]

^<<v18-8-16,16>>^ He is full of sap before the sun,
And in his garden his own twig goes forth.

[[v18-8-17]]

^<<v18-8-17,17>>^ In a stone heap his roots become interwoven,
A house of stones he beholds.

[[v18-8-18]]

^<<v18-8-18,18>>^ If one swallows him up from his place,
It will also certainly deny him, &#91;saying,&#93; ‘I have not seen you.’

[[v18-8-19]]

^<<v18-8-19,19>>^ Look! That is the dissolving of his way;
And from the dust others spring up.

[[v18-8-20]]

^<<v18-8-20,20>>^ Look! God^&#42;1^ himself will not reject anyone blameless,
Neither will he take hold of the hand of evildoers,

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-8-21]]

^<<v18-8-21,21>>^ Until he fills your mouth with laughter,
And your lips with joyful shouting.

[[v18-8-22]]

^<<v18-8-22,22>>^ The very ones hating you will be clothed with shame,
And the tent of wicked ones will not be.”

'''

xref:018-job/018-job-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-job/018-job-009.adoc#v18-9-0[Próximo Capítulo &#62;]