include::./index.adoc[]

[[v18-20-0]]
=== Job, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-20-1]]

^<<v18-20-1,1>>^ And Zoʹphar the Naʹa·ma·thite proceeded to reply and say:

[[v18-20-2]]

^<<v18-20-2,2>>^ “Therefore do my own disquieting thoughts themselves answer me,
Even on account of my inward excitement.

[[v18-20-3]]

^<<v18-20-3,3>>^ An insulting exhortation to me I hear;
And a spirit without the understanding that I have replies to me.

[[v18-20-4]]

^<<v18-20-4,4>>^ Have you at all times known this very thing,
Since man^&#42;1^ was put upon the earth,

[NOTE]
====
. Or, “Adam.” Heb., ʼa·dhamʹ.
====

[[v18-20-5]]

^<<v18-20-5,5>>^ That the joyful cry of wicked people is short
And the rejoicing of an apostate is for a moment?

[[v18-20-6]]

^<<v18-20-6,6>>^ Although his excellency ascends to heaven itself
And his very head reaches to the clouds,

[[v18-20-7]]

^<<v18-20-7,7>>^ Like his manure cakes he perishes forever;
The very ones seeing him will say, ‘Where is he?’

[[v18-20-8]]

^<<v18-20-8,8>>^ Like a dream he will fly off, and they will not find him;
And he will be chased away like a vision of the night.

[[v18-20-9]]

^<<v18-20-9,9>>^ The eye that has caught sight of him will not do so again,
And no more will his place behold him.

[[v18-20-10]]

^<<v18-20-10,10>>^ His own sons will seek the favor of lowly people,
And his own hands will give back his valuable things.

[[v18-20-11]]

^<<v18-20-11,11>>^ His own bones have been full of his youthful vigor,
But with him it will lie down in mere dust.

[[v18-20-12]]

^<<v18-20-12,12>>^ If what is bad tastes sweet in his mouth,
If he causes it to melt away under his tongue,

[[v18-20-13]]

^<<v18-20-13,13>>^ If he has compassion upon it and does not leave it,
And if he keeps holding it back in the midst of his palate,

[[v18-20-14]]

^<<v18-20-14,14>>^ His food itself will certainly be changed in his own intestines;
It will be the gall of cobras within him.

[[v18-20-15]]

^<<v18-20-15,15>>^ Wealth he has swallowed down, but he will vomit it up;
God^&#42;1^ will drive it out from his very belly.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-20-16]]

^<<v18-20-16,16>>^ The venom of cobras he will suck;
The tongue of a viper will kill him.

[[v18-20-17]]

^<<v18-20-17,17>>^ He will never see the watercourses,
Torrential streams of honey and butter.

[[v18-20-18]]

^<<v18-20-18,18>>^ He will be giving back &#91;his&#93; acquired property and will not swallow &#91;it&#93; down;
Like wealth from his trade, but which he will not enjoy.

[[v18-20-19]]

^<<v18-20-19,19>>^ For he has crushed to pieces, he has left lowly ones;
He has snatched away a house itself that he did not proceed to build.

[[v18-20-20]]

^<<v18-20-20,20>>^ For he will certainly know no ease in his belly;
By means of his desirable things he will not escape.

[[v18-20-21]]

^<<v18-20-21,21>>^ There is nothing left over for him to devour;
That is why his well-being will not endure.

[[v18-20-22]]

^<<v18-20-22,22>>^ While his plenty is at its peak he will be feeling anxious;
All the power^&#42;1^ of misfortune itself will come against him.

[NOTE]
====
. Lit., “hand.”
====

[[v18-20-23]]

^<<v18-20-23,23>>^ Let it occur that, to fill his belly,
He will send his burning anger upon him
And will rain &#91;it&#93; upon him, into his bowels.

[[v18-20-24]]

^<<v18-20-24,24>>^ He will run away from armor of iron;
A bow of copper will cut him up.

[[v18-20-25]]

^<<v18-20-25,25>>^ A missile^&#42;1^ itself will even go out through his back,
And a glittering weapon^&#42;2^ out through his gall;
Frightful objects will go against him.

[NOTE]
====
. “Missile,” by a correction; M, “One has drawn out [a weapon].”
. “A glittering weapon.” Lit., “lightning.”
====

[[v18-20-26]]

^<<v18-20-26,26>>^ All darkness will be reserved for his treasured things;
A fire that no one fanned will eat him up;
It will go badly with a survivor in his tent.

[[v18-20-27]]

^<<v18-20-27,27>>^ Heaven will uncover his error,
And earth will be in revolt against him.

[[v18-20-28]]

^<<v18-20-28,28>>^ A heavy shower will roll his house away;^&#42;1^
There will be things poured forth on the day of his anger.

[NOTE]
====
. Or, “The increase of his house will roll away.”
====

[[v18-20-29]]

^<<v18-20-29,29>>^ This is the share of the wicked man^&#42;1^ from God,^&#42;2^
Even his stated inheritance from God.”^&#42;3^

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
. “From God.” Heb., me·ʼElo·himʹ.
. “From God.” Heb., me·ʼElʹ.
====

'''

xref:018-job/018-job-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-job/018-job-021.adoc#v18-21-0[Próximo Capítulo &#62;]