include::./index.adoc[]

[[v18-18-0]]
=== Job, 18
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-18-1]]

^<<v18-18-1,1>>^ And Bilʹdad the Shuʹhite proceeded to answer and say:

[[v18-18-2]]

^<<v18-18-2,2>>^ “How long will YOU people be at putting an end to words?
YOU should understand, that afterward we may speak.

[[v18-18-3]]

^<<v18-18-3,3>>^ Why should we be reckoned as beasts
&#91;And&#93; be regarded as unclean in YOUR eyes?

[[v18-18-4]]

^<<v18-18-4,4>>^ He is tearing his soul to pieces in his anger.
For your sake will the earth be abandoned,
Or a rock move away from its place?

[[v18-18-5]]

^<<v18-18-5,5>>^ The light also of wicked ones will be extinguished
And the spark of his fire will not shine.

[[v18-18-6]]

^<<v18-18-6,6>>^ A light itself will certainly grow dark in his tent,
And in it his own lamp will be extinguished.

[[v18-18-7]]

^<<v18-18-7,7>>^ His steps of vigor^&#42;1^ will become cramped.
Even his counsel will cast him off.

[NOTE]
====
. Or, “uncanny power.”
====

[[v18-18-8]]

^<<v18-18-8,8>>^ For he will indeed be let go into a net by his feet,
And onto a network he will walk.

[[v18-18-9]]

^<<v18-18-9,9>>^ A trap will seize &#91;him&#93; by the heel;
A snare keeps hold upon him.

[[v18-18-10]]

^<<v18-18-10,10>>^ A cord for him is hidden on the earth,
And a catching device for him on &#91;his&#93; pathway.

[[v18-18-11]]

^<<v18-18-11,11>>^ Round about, sudden terrors certainly make him start up in fright,
And indeed chase him at his feet.

[[v18-18-12]]

^<<v18-18-12,12>>^ His vigor becomes famished,
And disaster stands ready to make him limp.

[[v18-18-13]]

^<<v18-18-13,13>>^ It will eat the pieces of his skin;^&#42;1^
The firstborn of death^&#42;2^ will eat his limbs.

[NOTE]
====
. “His skin will be eaten by disease,” by a slight correction of M.
. “The firstborn of death,” that is, the most deadly disease.
====

[[v18-18-14]]

^<<v18-18-14,14>>^ His confidence will be torn away from his own tent
And it will march him to the king of terrors.

[[v18-18-15]]

^<<v18-18-15,15>>^ There will reside in his tent something that is not his;
Sulphur will be strewed upon his own abiding place.

[[v18-18-16]]

^<<v18-18-16,16>>^ Underneath will his very roots dry up,
And, up above, his bough will wither.

[[v18-18-17]]

^<<v18-18-17,17>>^ The very mentioning of him will certainly perish from the earth,
And he will have no name out in the street.

[[v18-18-18]]

^<<v18-18-18,18>>^ They will push him out of the light into the darkness,
And from the productive land^&#42;1^ they will chase him away.

[NOTE]
====
. “And from the productive land.” Heb., u·mit·te·velʹ; Lat., et de orʹbe, “and from the [terrestrial] circle.”
====

[[v18-18-19]]

^<<v18-18-19,19>>^ He will have no posterity and no progeny among his people,
And there will be no survivor in his place of alien residence.

[[v18-18-20]]

^<<v18-18-20,20>>^ At his day the people in the West will indeed stare in amazement,
And a shudder will certainly seize even the people in the East.

[[v18-18-21]]

^<<v18-18-21,21>>^ Only these are the tabernacles of a wrongdoer,
And this is the place of one that has not known God.”^&#42;1^

[NOTE]
====
. “God.” Heb., ʼEl.
====

'''

xref:018-job/018-job-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-job/018-job-019.adoc#v18-19-0[Próximo Capítulo &#62;]