include::./index.adoc[]

[[v18-40-0]]
=== Job, 40
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-40-1]]

^<<v18-40-1,1>>^ And Jehovah proceeded to answer Job and say:

[[v18-40-2]]

^<<v18-40-2,2>>^ “Should there be any contending^&#42;1^ of a faultfinder with the Almighty?
Let the reprover of God^&#42;2^ himself answer it.”

[NOTE]
====
. “Should there be any contending.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
. “God.” Heb., ʼElohʹah.
====

[[v18-40-3]]

^<<v18-40-3,3>>^ And Job went on to answer Jehovah and say:

[[v18-40-4]]

^<<v18-40-4,4>>^ “Look! I have become of little account.
What shall I reply to you?
My hand I have put over my mouth.

[[v18-40-5]]

^<<v18-40-5,5>>^ Once have I spoken, and I will not answer;
And twice, and I will add nothing.”

[[v18-40-6]]

^<<v18-40-6,6>>^ And Jehovah went on to answer Job out of the windstorm and say:

[[v18-40-7]]

^<<v18-40-7,7>>^ “Gird up your loins, please, like an able-bodied man;
I shall question you, and you inform me.

[[v18-40-8]]

^<<v18-40-8,8>>^ Really, will you invalidate my justice?
Will you pronounce me wicked in order that you may be in the right?^&#42;1^

[NOTE]
====
. “Do you imagine that I have treated you otherwise than that you should appear righteous?” LXX.
====

[[v18-40-9]]

^<<v18-40-9,9>>^ Or do you have an arm like that of the &#91;true&#93; God,^&#42;1^
And with a voice like his can you make it thunder?

[NOTE]
====
. “Like that of the [true] God.” Heb., ka·ʼElʹ. See De 33:26 ftn, “God.”
====

[[v18-40-10]]

^<<v18-40-10,10>>^ Deck yourself, please, with superiority and highness;
And with dignity and splendor may you clothe yourself.

[[v18-40-11]]

^<<v18-40-11,11>>^ Let flow the furious outbursts of your anger,
And see every one haughty and bring him low.

[[v18-40-12]]

^<<v18-40-12,12>>^ See every one haughty, humble him,
And tread down the wicked right where they are.

[[v18-40-13]]

^<<v18-40-13,13>>^ Hide them together in the dust,
Bind their very faces in the hidden place,

[[v18-40-14]]

^<<v18-40-14,14>>^ And I, even I, shall commend you,
Because your right hand can save you.

[[v18-40-15]]

^<<v18-40-15,15>>^ Here, now, is Be·heʹmoth^&#42;1^ that I have made as well as you.
Green grass it eats just as a bull does.

[NOTE]
====
. Or, “hippopotamus.” Heb., vehe·mohthʹ, pl. of behe·mahʹ (compare Ge 1:24 ftn, “Animal”); Gr., the·riʹa; Lat.(vs 10), Be·heʹmoth.
====

[[v18-40-16]]

^<<v18-40-16,16>>^ Here, now, its power is in its hips,
And its dynamic energy in the tendons of its belly.

[[v18-40-17]]

^<<v18-40-17,17>>^ It bends down its tail like a cedar;
The sinews of its thighs are interwoven.

[[v18-40-18]]

^<<v18-40-18,18>>^ Its bones are tubes of copper;
Its strong bones are like wrought-iron rods.

[[v18-40-19]]

^<<v18-40-19,19>>^ It is the beginning of the ways of God;^&#42;1^
Its Maker can bring near his sword.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-40-20]]

^<<v18-40-20,20>>^ For the mountains themselves bear their produce for it,
And all the wild beasts of the field themselves play there.^&#42;1^

[NOTE]
====
. “He made pleasure for the four-footed creatures in the Tartarus,” LXX. See App 4D.
====

[[v18-40-21]]

^<<v18-40-21,21>>^ Under the thorny lotus trees it lies down,
In the concealed place of reeds and the swampy place.

[[v18-40-22]]

^<<v18-40-22,22>>^ The thorny lotus trees keep it blocked off with their shadow;
The poplars of the torrent valley surround it.

[[v18-40-23]]

^<<v18-40-23,23>>^ If the river acts violently, it does not run in panic.
It is confident, although the Jordan should burst forth against its mouth.

[[v18-40-24]]

^<<v18-40-24,24>>^ Before its eyes can anyone take it?
With snares can anyone bore &#91;its&#93; nose?^&#42;1^

[NOTE]
====
. MLXX continue this chapter for eight more vss.
====

'''

xref:018-job/018-job-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-job/018-job-041.adoc#v18-41-0[Próximo Capítulo &#62;]