include::./index.adoc[]

[[v18-17-0]]
=== Job, 17
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-17-1]]

^<<v18-17-1,1>>^ “My very spirit^&#42;1^ has been broken, my own days have been extinguished;
The graveyard is for me.

[NOTE]
====
. Or, “breath.” See 12:10 ftn, “Spirit.”
====

[[v18-17-2]]

^<<v18-17-2,2>>^ Certainly there is mockery at me,
And amid their rebellious behavior my eye lodges.

[[v18-17-3]]

^<<v18-17-3,3>>^ Please, do put my security with yourself.
Who else is there that will shake hands with me in pledge?

[[v18-17-4]]

^<<v18-17-4,4>>^ For their heart you have closed to discretion.
That is why you do not exalt them.

[[v18-17-5]]

^<<v18-17-5,5>>^ He may tell companions to take their shares,
But the very eyes of his sons will fail.

[[v18-17-6]]

^<<v18-17-6,6>>^ And he has set me forth as a proverbial saying of peoples,
So that I become someone into whose face to spit.

[[v18-17-7]]

^<<v18-17-7,7>>^ And from vexation my eye grows dimmer
And my members are all of them like the shadow.

[[v18-17-8]]

^<<v18-17-8,8>>^ Upright people stare in amazement at this,
And even the innocent one gets excited over the apostate.

[[v18-17-9]]

^<<v18-17-9,9>>^ The righteous one keeps holding fast to his way,
And the one with clean hands keeps increasing in strength.

[[v18-17-10]]

^<<v18-17-10,10>>^ However, YOU men may all of YOU resume. So come on, please,
As I do not find anyone wise among YOU.

[[v18-17-11]]

^<<v18-17-11,11>>^ My own days have passed along, my own plans have been torn apart,
The wishes of my heart.

[[v18-17-12]]

^<<v18-17-12,12>>^ Night they keep putting for day:
‘Light is near on account of darkness.’

[[v18-17-13]]

^<<v18-17-13,13>>^ If I keep waiting, Sheʹol is my house;
In the darkness I shall have to spread out my lounge.

[[v18-17-14]]

^<<v18-17-14,14>>^ To the pit I shall have to call out, ‘You are my father!’
To the maggot, ‘My mother and my sister!’

[[v18-17-15]]

^<<v18-17-15,15>>^ So where, then, is my hope?
And my hope—who is it that beholds it?

[[v18-17-16]]

^<<v18-17-16,16>>^ To the bars of Sheʹol^&#42;1^ they^&#42;2^ will go down,
When we, all together, must descend to the very dust.”

[NOTE]
====
. “Sheol.” Heb., sheʼolʹ; Gr., haiʹden; Lat., in·ferʹnum. See App 4B.
. “They,” fem., referring to “hope,” twice in vs 15.
====

'''

xref:018-job/018-job-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v18-17-0,Topo>> | xref:018-job/018-job-018.adoc#v18-18-0[Próximo Capítulo &#62;]