include::./index.adoc[]

[[v18-10-0]]
=== Job, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-10-1]]

^<<v18-10-1,1>>^ “My soul certainly feels a loathing toward my life.
I will give vent to my concern about myself.^&#42;1^
I will speak in the bitterness of my soul!

[NOTE]
====
. “About myself,” MVg; LXX, “about him.”
====

[[v18-10-2]]

^<<v18-10-2,2>>^ I shall say to God,^&#42;1^ ‘Do not pronounce me wicked.
Cause me to know why it is that you are contending with me.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-10-3]]

^<<v18-10-3,3>>^ Is it good for you that you should do wrong,
That you should reject &#91;the product of&#93; the hard work of your hands,^&#42;1^
And that upon the counsel of wicked ones you should actually beam?

[NOTE]
====
. Or, “palms.”
====

[[v18-10-4]]

^<<v18-10-4,4>>^ Do you have eyes of flesh,
Or is it as a mortal man sees that you see?

[[v18-10-5]]

^<<v18-10-5,5>>^ Are your days like the days of mortal man,
Or your years just like the days of an able-bodied man,

[[v18-10-6]]

^<<v18-10-6,6>>^ That you should try to find my error
And for my sin you should keep looking?

[[v18-10-7]]

^<<v18-10-7,7>>^ This in spite of your own knowledge that I am not in the wrong,
And there is no one delivering out of your own hand?

[[v18-10-8]]

^<<v18-10-8,8>>^ Your own hands have shaped me so that they made me
In entirety round about, and yet you would swallow me up.

[[v18-10-9]]

^<<v18-10-9,9>>^ Remember, please, that out of clay you have made me
And to dust you will make me return.

[[v18-10-10]]

^<<v18-10-10,10>>^ Did you not proceed to pour me out as milk itself
And like cheese to curdle me?

[[v18-10-11]]

^<<v18-10-11,11>>^ With skin and flesh you proceeded to clothe me
And with bones and sinews to weave me together.

[[v18-10-12]]

^<<v18-10-12,12>>^ Life and loving-kindness^&#42;1^ you have worked with me;
And your own care has guarded my spirit.^&#42;2^

[NOTE]
====
. Or, “loyal love.”
. “My spirit (breath).” Heb., ru·chiʹ; Gr., pneuʹma; Lat., spiʹri·tum.
====

[[v18-10-13]]

^<<v18-10-13,13>>^ And these things you have concealed in your heart.
I well know that these things are with you.

[[v18-10-14]]

^<<v18-10-14,14>>^ If I have sinned and you have kept watching me
And of my error you do not hold me innocent;

[[v18-10-15]]

^<<v18-10-15,15>>^ If I am actually in the wrong, too bad for me!
And &#91;if&#93; I am actually in the right, I may not raise my head,
Glutted with dishonor and saturated with affliction.

[[v18-10-16]]

^<<v18-10-16,16>>^ And &#91;if&#93; it acts haughtily, like a young lion you will hunt for me,
And you will again show yourself marvelous in my case.

[[v18-10-17]]

^<<v18-10-17,17>>^ You will bring forth new witnesses^&#42;1^ of yours in front of me,
And you will make your vexation with me greater;
Hardship after hardship is with me.^&#42;2^

[NOTE]
====
. “Witnesses,” MVg; LXX, “testing”; Sy, “weapons.”
. Or, “one shift of compulsory labor after another is with me.”
====

[[v18-10-18]]

^<<v18-10-18,18>>^ So why from a womb did you bring me out?
Could I have expired,^&#42;1^ that not even an eye could see me,

[NOTE]
====
. Or, “Let me expire.”
====

[[v18-10-19]]

^<<v18-10-19,19>>^ There as though I had not come to be I should have become;
From the belly to the burial place I should have been brought.’

[[v18-10-20]]

^<<v18-10-20,20>>^ Are not my days few? Let him leave off,
Let him turn his gaze from me, that I may brighten up a little

[[v18-10-21]]

^<<v18-10-21,21>>^ Before I go away—and I shall not come back—
To the land of darkness and deep shadow,^&#42;1^

[NOTE]
====
. Lit., “death shadow.”
====

[[v18-10-22]]

^<<v18-10-22,22>>^ To the land of obscurity like gloom, of deep shadow
And disorder, where it beams no more than gloom does.”

'''

xref:018-job/018-job-009.adoc#v18-9-0[&#60; Capítulo Anterior] | <<v18-10-0,Topo>> | xref:018-job/018-job-011.adoc#v18-11-0[Próximo Capítulo &#62;]