include::./index.adoc[]

[[v18-11-0]]
=== Job, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-11-1]]

^<<v18-11-1,1>>^ And Zoʹphar the Naʹa·ma·thite proceeded to answer and say:

[[v18-11-2]]

^<<v18-11-2,2>>^ “Will a multitude of words go unanswered,
Or will a mere boaster^&#42;1^ be in the right?

[NOTE]
====
. Lit., “a man of lips.”
====

[[v18-11-3]]

^<<v18-11-3,3>>^ Will your empty talk itself put men^&#42;1^ to silence,
And will you keep deriding without having anyone rebuke &#91;you&#93;?

[NOTE]
====
. “Men.” Heb., methimʹ, adult males.
====

[[v18-11-4]]

^<<v18-11-4,4>>^ Also, you say, ‘My instruction is pure,
And I have proved really clean in your eyes.’

[[v18-11-5]]

^<<v18-11-5,5>>^ Yet O if only God himself would speak
And open his lips with you!

[[v18-11-6]]

^<<v18-11-6,6>>^ Then he would tell you the secrets of wisdom,
For the things of practical wisdom are manifold.^&#42;1^
Also, you would know^&#42;2^ that God allows some of your error to be forgotten for you.

[NOTE]
====
. Lit., “doubled.”
. Lit., “And know you,” imperative.
====

[[v18-11-7]]

^<<v18-11-7,7>>^ Can you find out the deep things of God,
Or can you find out to the very limit of the Almighty?

[[v18-11-8]]

^<<v18-11-8,8>>^ It is higher than heaven. What can you accomplish?
It is deeper than Sheʹol. What can you know?

[[v18-11-9]]

^<<v18-11-9,9>>^ It is longer than the earth in measure,
And broader than the sea.

[[v18-11-10]]

^<<v18-11-10,10>>^ If he moves on and hands &#91;someone&#93; over
And calls a court, then who can resist him?

[[v18-11-11]]

^<<v18-11-11,11>>^ For he himself well knows men^&#42;1^ who are untrue.
When he sees what is hurtful, will he not also show himself attentive?

[NOTE]
====
. See vs 3 ftn.
====

[[v18-11-12]]

^<<v18-11-12,12>>^ Even a hollow-minded man^&#42;1^ himself will get good motive
As soon as an asinine zebra be born a man.^&#42;2^

[NOTE]
====
. “Even a . . . man.” Heb., weʼishʹ.
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
====

[[v18-11-13]]

^<<v18-11-13,13>>^ If you yourself will really prepare your heart
And actually spread out your palms to him,

[[v18-11-14]]

^<<v18-11-14,14>>^ If what is hurtful is in your hand, put it far away,
And let no unrighteousness dwell in your tents.

[[v18-11-15]]

^<<v18-11-15,15>>^ For then you will raise your face without defect
And you will certainly become established, and you will not fear.

[[v18-11-16]]

^<<v18-11-16,16>>^ For you—you will forget trouble itself;
As waters that have passed along you will remember &#91;it&#93;.

[[v18-11-17]]

^<<v18-11-17,17>>^ And brighter than midday will &#91;your&#93; life’s duration arise;
Darkness will become like the morning itself.

[[v18-11-18]]

^<<v18-11-18,18>>^ And you will be bound to trust because there exists hope;
And you will certainly look carefully around—in security you will lie down.

[[v18-11-19]]

^<<v18-11-19,19>>^ And you will indeed stretch yourself out, with no one to make &#91;you&#93; tremble.
And many people will certainly put you in a gentle mood;^&#42;1^

[NOTE]
====
. Lit., “soften your face.”
====

[[v18-11-20]]

^<<v18-11-20,20>>^ And the very eyes of the wicked will fail;
And a place for flight will certainly perish from them,
And their hope will be an expiring of the soul.”

'''

xref:018-job/018-job-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-job/018-job-012.adoc#v18-12-0[Próximo Capítulo &#62;]