include::./index.adoc[]

[[v18-36-0]]
=== Job, 36
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-36-1]]

^<<v18-36-1,1>>^ And E·liʹhu proceeded to say further:

[[v18-36-2]]

^<<v18-36-2,2>>^ “Have patience with me a little while, and I shall declare to you
That there are yet words &#91;to say&#93; for God.^&#42;1^

[NOTE]
====
. “For God.” Heb., le·ʼElohʹah.
====

[[v18-36-3]]

^<<v18-36-3,3>>^ I shall carry my knowledge from far off,
And to my Fashioner^&#42;1^ I shall ascribe righteousness.

[NOTE]
====
. Or, “and to my Maker.” Heb., u·lePho·ʽaliʹ.
====

[[v18-36-4]]

^<<v18-36-4,4>>^ For my words are for a fact no falsehood;
The One perfect in knowledge is with you.

[[v18-36-5]]

^<<v18-36-5,5>>^ Look! God^&#42;1^ is mighty and will not reject;
&#91;He is&#93; mighty in power of heart;^&#42;2^

[NOTE]
====
. “God.” Heb., ʼEl.
. Or, “good motive.” Compare 34:34.
====

[[v18-36-6]]

^<<v18-36-6,6>>^ He will not preserve anyone wicked alive,
But the judgment of the afflicted ones he will give.

[[v18-36-7]]

^<<v18-36-7,7>>^ He will not take away his eyes from anyone righteous;
Even kings on the throne—
He will also seat them forever, and they will be exalted.

[[v18-36-8]]

^<<v18-36-8,8>>^ And if they are bound in fetters,
They are captured with ropes of affliction.

[[v18-36-9]]

^<<v18-36-9,9>>^ Then he will tell them about the way they act
And their transgressions, because they take a superior air.

[[v18-36-10]]

^<<v18-36-10,10>>^ And he will uncover their ear to exhortation,
And he will say that they should turn back from what is hurtful.

[[v18-36-11]]

^<<v18-36-11,11>>^ If they obey and serve,
They will finish their days in what is good
And their years in pleasantness.

[[v18-36-12]]

^<<v18-36-12,12>>^ But if they do not obey, they will pass away even by a missile,
And they will expire without knowledge.

[[v18-36-13]]

^<<v18-36-13,13>>^ And those apostate in heart will themselves lay up anger.
They should not cry for help because he has bound them.

[[v18-36-14]]

^<<v18-36-14,14>>^ Their soul will die in youth itself,
And their life among male temple prostitutes.

[[v18-36-15]]

^<<v18-36-15,15>>^ He will rescue the afflicted one in his affliction,
And he will uncover their ear in the oppression.

[[v18-36-16]]

^<<v18-36-16,16>>^ And he will also certainly allure you from the mouth of distress!
Broader space, not constraint, will be in its place,
And the consolation of your table will be full of fatness.

[[v18-36-17]]

^<<v18-36-17,17>>^ With the judicial sentence upon the wicked one you will certainly be filled;
Judicial sentence and justice will themselves take hold.

[[v18-36-18]]

^<<v18-36-18,18>>^ For &#91;take care&#93; that rage does not allure you into &#91;spiteful&#93; handclapping,
And let not a large ransom itself lead you astray.

[[v18-36-19]]

^<<v18-36-19,19>>^ Will your cry for help take effect? No, nor in distress
Even all &#91;your&#93; powerful efforts.

[[v18-36-20]]

^<<v18-36-20,20>>^ Do not pant for the night,^&#42;1^
For peoples to retreat &#91;from&#93; where they are.

[NOTE]
====
. Or, “night’s [rest].”
====

[[v18-36-21]]

^<<v18-36-21,21>>^ Be on your guard that you do not turn to what is hurtful,
For this you have chosen rather than affliction.

[[v18-36-22]]

^<<v18-36-22,22>>^ Look! God^&#42;1^ himself acts exaltedly with his power;
Who is an instructor like him?

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v18-36-23]]

^<<v18-36-23,23>>^ Who has called his way to account against him,
And who has said, ‘You have committed unrighteousness’?

[[v18-36-24]]

^<<v18-36-24,24>>^ Remember that you should magnify his activity
Of which men have sung.

[[v18-36-25]]

^<<v18-36-25,25>>^ All mankind^&#42;1^ themselves have gazed upon it;
Mortal man himself keeps looking from far off.

[NOTE]
====
. “Mankind.” Heb., ʼa·dhamʹ.
====

[[v18-36-26]]

^<<v18-36-26,26>>^ Behold! God is more exalted than we can know;
In number his years are beyond searching.

[[v18-36-27]]

^<<v18-36-27,27>>^ For he draws up the drops of water;
They filter as rain for his mist,

[[v18-36-28]]

^<<v18-36-28,28>>^ So that the clouds trickle,
They drip upon mankind abundantly.

[[v18-36-29]]

^<<v18-36-29,29>>^ Indeed, who can understand the cloud layers,
The crashings from his booth?

[[v18-36-30]]

^<<v18-36-30,30>>^ Look! He has spread out over it his light,
And the roots of the sea he has covered.

[[v18-36-31]]

^<<v18-36-31,31>>^ For by them he pleads the cause of peoples;
He gives food in abundance.

[[v18-36-32]]

^<<v18-36-32,32>>^ In his hands he has covered over the lightning,^&#42;1^
And he lays a command upon it against an assailant.

[NOTE]
====
. Lit., “light.” Heb., ʼohr, the same noun as in vs 30.
====

[[v18-36-33]]

^<<v18-36-33,33>>^ His booming tells about him,
The livestock also concerning the one coming up.

'''

xref:018-job/018-job-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-job/018-job-037.adoc#v18-37-0[Próximo Capítulo &#62;]