include::./index.adoc[]

[[v18-21-0]]
=== Job, 21
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v18-21-1]]

^<<v18-21-1,1>>^ And Job proceeded to answer and say:

[[v18-21-2]]

^<<v18-21-2,2>>^ “Listen, YOU men, attentively to my word,
And let this become YOUR consolation.

[[v18-21-3]]

^<<v18-21-3,3>>^ Put up with me, and I myself shall speak;
And after my speaking you may &#91;each&#93; deride.

[[v18-21-4]]

^<<v18-21-4,4>>^ As for me, is my concern &#91;expressed&#93; to man?
Or why is it that my spirit does not get impatient?

[[v18-21-5]]

^<<v18-21-5,5>>^ Turn YOUR faces to me and stare in amazement,
And put &#91;YOUR&#93; hand upon &#91;YOUR&#93; mouth.

[[v18-21-6]]

^<<v18-21-6,6>>^ And if I have remembered, I have also become disturbed,
And shuddering has taken hold of my flesh.

[[v18-21-7]]

^<<v18-21-7,7>>^ Why is it that the wicked themselves keep living,
Have grown old, also have become superior in wealth?

[[v18-21-8]]

^<<v18-21-8,8>>^ Their offspring are firmly established with them in their sight,
And their descendants before their eyes.

[[v18-21-9]]

^<<v18-21-9,9>>^ Their houses are peace itself, free from dread,
And the rod of God^&#42;1^ is not upon them.

[NOTE]
====
. “God.” Heb., ʼElohʹah. See 3:4 ftn.
====

[[v18-21-10]]

^<<v18-21-10,10>>^ His own bull actually impregnates, and it does not waste semen;
His cow brings forth and suffers no abortion.

[[v18-21-11]]

^<<v18-21-11,11>>^ They keep sending out their young boys just like a flock,
And their own male children go skipping about.

[[v18-21-12]]

^<<v18-21-12,12>>^ They continue raising &#91;their voice&#93; with the tambourine and harp,
And keep rejoicing at the sound of the pipe.

[[v18-21-13]]

^<<v18-21-13,13>>^ They spend their days in good times,
And in a moment down to Sheʹol they descend.

[[v18-21-14]]

^<<v18-21-14,14>>^ And they say to the &#91;true&#93; God, ‘Turn away from us!
And in the knowledge of your ways we have found no delight.

[[v18-21-15]]

^<<v18-21-15,15>>^ What does the Almighty amount to, that we should serve him,^&#42;1^
And how do we benefit ourselves in that we have come in touch with him?’

[NOTE]
====
. Or, “we should worship him (render him sacred service).” Heb., na·ʽav·dhenʹnu.
====

[[v18-21-16]]

^<<v18-21-16,16>>^ Look! Their well-being is not in their own power.^&#42;1^
The very counsel of wicked ones has kept far from me.

[NOTE]
====
. Lit., “hand.”
====

[[v18-21-17]]

^<<v18-21-17,17>>^ How many times is the lamp of the wicked ones extinguished,
And &#91;how many times&#93; does their disaster come upon them?
&#91;How many times&#93; in his anger does he apportion destruction?

[[v18-21-18]]

^<<v18-21-18,18>>^ Do they become like straw before a wind,^&#42;1^
And like chaff that a storm wind has stolen away?

[NOTE]
====
. “Wind.” Heb., ruʹach; Gr., a·neʹmou; Lat., venʹti.
====

[[v18-21-19]]

^<<v18-21-19,19>>^ God^&#42;1^ himself will store up one’s hurtfulness for one’s own sons;
He will reward him that he may know &#91;it&#93;.

[NOTE]
====
. “God.” Heb., ʼElohʹah.
====

[[v18-21-20]]

^<<v18-21-20,20>>^ His eyes will see his decay,
And from the rage of the Almighty he will drink.

[[v18-21-21]]

^<<v18-21-21,21>>^ For what will his delight be in his house after him,
When the number of his months will really be cut in two?

[[v18-21-22]]

^<<v18-21-22,22>>^ Will he teach knowledge even to God,^&#42;1^
When that One himself judges high ones?

[NOTE]
====
. “Even to God.” Heb., hal·ʼElʹ. See 22:2 ftn, “God.”
====

[[v18-21-23]]

^<<v18-21-23,23>>^ This very one will die during his full self-sufficiency,
When he is altogether carefree and at ease;

[[v18-21-24]]

^<<v18-21-24,24>>^ &#91;When&#93; his own thighs have become full of fat
And the very marrow of his bones is being kept moist.

[[v18-21-25]]

^<<v18-21-25,25>>^ And this other one will die with a bitter soul
When he has not eaten of good things.

[[v18-21-26]]

^<<v18-21-26,26>>^ Together in the dust they will lie down
And maggots themselves will form a cover over them.

[[v18-21-27]]

^<<v18-21-27,27>>^ Look! I well know the thoughts of YOU men
And the schemes with which YOU would act violently against me.

[[v18-21-28]]

^<<v18-21-28,28>>^ For YOU say, ‘Where is the house of the noble one,
And where is the tent, the tabernacles of wicked ones?’

[[v18-21-29]]

^<<v18-21-29,29>>^ Have YOU not asked those traveling over the roads?
And do YOU not carefully inspect their very signs,

[[v18-21-30]]

^<<v18-21-30,30>>^ That at the day of disaster an evil one is spared,
At the day of fury he is delivered?^&#42;1^

[NOTE]
====
. “He is delivered,” by a correction; M, “brought,” as in vs 32.
====

[[v18-21-31]]

^<<v18-21-31,31>>^ Who will tell him of his way to his very face?
And for what he himself has done who will reward him?

[[v18-21-32]]

^<<v18-21-32,32>>^ As for him, to the graveyard he will be brought,
And over a tomb^&#42;1^ a vigil will be kept.

[NOTE]
====
. Or, “heap of sheaves.”
====

[[v18-21-33]]

^<<v18-21-33,33>>^ To him the clods of earth of a torrent valley will certainly become sweet,
And after him he will drag all mankind,^&#42;1^
And those before him were without number.

[NOTE]
====
. Or, “every earthling man.” Heb., kol-ʼa·dhamʹ.
====

[[v18-21-34]]

^<<v18-21-34,34>>^ So how vainly YOU men try to comfort me,
And YOUR very replies do remain as unfaithfulness!”

'''

xref:018-job/018-job-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-job/018-job-022.adoc#v18-22-0[Próximo Capítulo &#62;]