include::./index.adoc[]

[[v16-3-0]]
=== Nehemiah, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-3-1]]

^<<v16-3-1,1>>^ And E·liʹa·shib the high priest and his brothers, the priests, proceeded to get up and build the Sheep Gate. They themselves sanctified it and went setting up its doors; and as far as the Tower of Meʹah^&#42;1^ they sanctified it, as far as the Tower of Ha·nanʹel.

[NOTE]
====
. Lit., “Tower of the Hundred.”
====

[[v16-3-2]]

^<<v16-3-2,2>>^ And at their side the men of Jerʹi·cho did building. And at their side Zacʹcur the son of Imʹri did building.

[[v16-3-3]]

^<<v16-3-3,3>>^ And the Fish Gate was what the sons of Has·se·naʹah built; they themselves timbered it and then set up its doors, its bolts and its bars.

[[v16-3-4]]

^<<v16-3-4,4>>^ And at their side Merʹe·moth the son of U·riʹjah the son of Hakʹkoz did repair work, and at their side Me·shulʹlam the son of Ber·e·chiʹah the son of Me·shezʹa·bel did repair work; and at their side Zaʹdok the son of Baʹa·na did repair work.

[[v16-3-5]]

^<<v16-3-5,5>>^ And at their side the Te·koʹites did repair work; but their majestic ones themselves did not bring the back of their neck into the service of their masters.^&#42;1^

[NOTE]
====
. “Their masters [or, lord].” Heb., ʼadho·neh·hemʹ, pl. of ʼa·dhohnʹ, possibly to denote excellence.
====

[[v16-3-6]]

^<<v16-3-6,6>>^ And the Gate of the Old &#91;City&#93; was what Joiʹa·da the son of Pa·seʹah and Me·shulʹlam the son of Bes·o·deiʹah repaired; they themselves timbered it and then set up its doors and its bolts and its bars.

[[v16-3-7]]

^<<v16-3-7,7>>^ And at their side Mel·a·tiʹah the Gibʹe·on·ite and Jaʹdon the Me·ronʹo·thite, did repair work, men of Gibʹe·on and Mizʹpah, belonging to the throne of the governor beyond the River.

[[v16-3-8]]

^<<v16-3-8,8>>^ At his side Uzʹzi·el the son of Har·haiʹah, goldsmiths, did repair work; and at his side Han·a·niʹah a member of the ointment mixers did repair work; and they proceeded to flagstone Jerusalem as far as the Broad Wall.

[[v16-3-9]]

^<<v16-3-9,9>>^ And at their side Re·phaʹiah the son of Hur, a prince of half the district of Jerusalem, did repair work.

[[v16-3-10]]

^<<v16-3-10,10>>^ And at their side Je·daʹiah the son of Ha·ruʹmaph did repair work in front of his own house; and at his side Hatʹtush the son of Hash·ab·neiʹah did repair work.

[[v16-3-11]]

^<<v16-3-11,11>>^ Another measured section was what Mal·chiʹjah the son of Haʹrim and Hasʹshub the son of Paʹhath-moʹab^&#42;1^ repaired, and also the Tower of the Bake Ovens.

[NOTE]
====
. Meaning “Governor of Moab.”
====

[[v16-3-12]]

^<<v16-3-12,12>>^ And at his side Shalʹlum the son of Hal·loʹhesh, a prince of half the district of Jerusalem, did repair work, he and his daughters.

[[v16-3-13]]

^<<v16-3-13,13>>^ The Valley Gate was what Haʹnun and the inhabitants of Za·noʹah repaired; they themselves built it and then set up its doors, its bolts and its bars, also a thousand cubits^&#42;1^ in the wall as far as the Gate of the Ash-heaps.^&#42;2^

[NOTE]
====
. About 445 m (1460 ft).
. “The Dung Gate,” LXXVg.
====

[[v16-3-14]]

^<<v16-3-14,14>>^ And the Gate of the Ash-heaps was what Mal·chiʹjah the son of Reʹchab, a prince of the district of Beth-hac·cheʹrem, repaired; he himself went building it and setting up its doors, its bolts and its bars.

[[v16-3-15]]

^<<v16-3-15,15>>^ And the Fountain Gate was what Shalʹlun^&#42;1^ the son of Col·hoʹzeh, a prince of the district of Mizʹpah, repaired; he himself proceeded to build it and to roof it over and to set up its doors, its bolts and its bars, and also the wall of the Pool of the Canal^&#42;2^ to the King’s Garden and as far as the Stairway that goes down from the City of David.

[NOTE]
====
. “Shallum,” Sy and some Heb. mss.
. Or, “the Pool of Shelah.”
====

[[v16-3-16]]

^<<v16-3-16,16>>^ After him Ne·he·miʹah the son of Azʹbuk, a prince of half the district of Beth-zur, did repair work as far as in front of the Burial Places of David and as far as the pool that had been made and as far as the House of the Mighty Ones.^&#42;1^

[NOTE]
====
. Or, “the Gibborim.” Heb., hag·Gib·bo·rimʹ.
====

[[v16-3-17]]

^<<v16-3-17,17>>^ After him the Levites did repair work, Reʹhum the son of Baʹni; at his side Hash·a·biʹah, a prince of half the district of Keiʹlah, did repair work for his district.

[[v16-3-18]]

^<<v16-3-18,18>>^ After him their brothers did repair work, Bavʹvai the son of Henʹa·dad, a prince of half the district of Keiʹlah.

[[v16-3-19]]

^<<v16-3-19,19>>^ And Eʹzer the son of Jeshʹu·a,^&#42;1^ a prince of Mizʹpah, proceeded at his side to repair another measured section in front of the going up to the Armory at the Buttress.

[NOTE]
====
. “Jesus,” LXX.
====

[[v16-3-20]]

^<<v16-3-20,20>>^ After him Barʹuch the son of Zabʹbai worked with fervor &#91;and&#93; repaired another measured section, from the Buttress as far as the entrance of the house of E·liʹa·shib the high priest.

[[v16-3-21]]

^<<v16-3-21,21>>^ After him Merʹe·moth the son of U·riʹjah the son of Hakʹkoz repaired another measured section, from the entrance of the house of E·liʹa·shib as far as the end of E·liʹa·shib’s house.

[[v16-3-22]]

^<<v16-3-22,22>>^ And after him the priests, men of the &#91;Jordan&#93; District, did repair work.

[[v16-3-23]]

^<<v16-3-23,23>>^ After them^&#42;1^ Benjamin and Hasʹshub did repair work in front of their own house. After them Az·a·riʹah the son of Ma·a·seiʹah the son of A·na·niʹah did repair work close by his own house.

[NOTE]
====
. “Him,” M.
====

[[v16-3-24]]

^<<v16-3-24,24>>^ After him Binʹnu·i the son of Henʹa·dad repaired another measured section, from the house of Az·a·riʹah as far as the Buttress and as far as the corner.

[[v16-3-25]]

^<<v16-3-25,25>>^ &#91;After him&#93; Paʹlal the son of Uʹzai &#91;did repair work&#93; in front of the Buttress and the tower that goes out from the King’s House, the upper one that belongs to the Courtyard of the Guard. After him there was Pe·daiʹah the son of Paʹrosh.

[[v16-3-26]]

^<<v16-3-26,26>>^ And the Nethʹi·nim^&#42;1^ themselves happened to be dwellers in Oʹphel; &#91;they did repair work&#93; as far as in front of the Water Gate on the east and the protruding tower.

[NOTE]
====
. “And the Nethinim (temple slaves).” Lit., “And the given ones.” Heb., wehan·Nethi·nimʹ; Gr., Na·thi·nimʹ; Vgc(Lat.), Na·thi·naeʹi. Compare Nu 3:9 ftn.
====

[[v16-3-27]]

^<<v16-3-27,27>>^ After them the Te·koʹites repaired another measured section, from in front of the great protruding tower as far as the wall of Oʹphel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Above the Horse Gate the priests did repair work, each one in front of his own house.

[[v16-3-29]]

^<<v16-3-29,29>>^ After them Zaʹdok the son of Imʹmer did repair work in front of his own house.
And after him She·maiʹah the son of Shec·a·niʹah, the keeper of the East Gate,^&#42;1^ did repair work.

[NOTE]
====
. Lit., “the Gate of the [Sun]rising.”
====

[[v16-3-30]]

^<<v16-3-30,30>>^ After him Han·a·niʹah the son of Shel·e·miʹah and Haʹnun the sixth son of Zaʹlaph repaired another measured section.
After him Me·shulʹlam the son of Ber·e·chiʹah did repair work in front of his own hall.

[[v16-3-31]]

^<<v16-3-31,31>>^ After him Mal·chiʹjah, a member^&#42;1^ of the goldsmith guild, did repair work as far as the house of the Nethʹi·nim and the traders, in front of the Inspection Gate^&#42;2^ and as far as the roof chamber of the corner.

[NOTE]
====
. Lit., “son.”
. Or, “the Gate of Hammiphkad.”
====

[[v16-3-32]]

^<<v16-3-32,32>>^ ^&#42;1^ And between the roof chamber of the corner and the Sheep Gate the goldsmiths and the traders did repair work.

[NOTE]
====
. In the margin of M opposite this vs is written the Heb. expression meaning “half of the book,” indicating that this is the middle vs of the 685 Heb. vss of the combined books of Ezra and Nehemiah, and that in M the two were one book.
====

'''

xref:016-nehemiah/016-nehemiah-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-nehemiah/016-nehemiah-004.adoc#v16-4-0[Próximo Capítulo &#62;]