include::./index.adoc[]

[[v16-6-0]]
=== Nehemiah, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-6-1]]

^<<v16-6-1,1>>^ Now it came about that, as soon as it was told to San·balʹlat and To·biʹah and to Geʹshem the Arabian and to the rest of our enemies that I had rebuilt the wall and there had not been left in it a gap (although up to that time the doors themselves I had not set up in the gates),

[[v16-6-2]]

^<<v16-6-2,2>>^ San·balʹlat and Geʹshem immediately sent to me, saying: “Do come, and let us meet together by appointment in the villages of the valley plain of Oʹno.” But they were scheming to do me harm.

[[v16-6-3]]

^<<v16-6-3,3>>^ So I sent messengers to them, saying: “It is a great work that I am doing, and I am not able to go down. Why should the work cease while I take off from it and have to go down to YOU?”

[[v16-6-4]]

^<<v16-6-4,4>>^ However, they sent me the same word four times, and I kept replying to them with the same word.

[[v16-6-5]]

^<<v16-6-5,5>>^ Finally San·balʹlat sent his attendant to me with the same word a fifth time, with an open letter in his hand.

[[v16-6-6]]

^<<v16-6-6,6>>^ There was written in it: “Among the nations it has been heard, and Geʹshem^&#42;1^ is saying &#91;it&#93;, that you and the Jews are scheming to rebel. That is why you are building the wall; and you are becoming a king to them, according to these words.

[NOTE]
====
. “And Geshem.” Heb., weGhash·muʹ.
====

[[v16-6-7]]

^<<v16-6-7,7>>^ And there are even prophets that you have appointed to call out concerning you throughout Jerusalem, saying, ‘There is a king in Judah!’ And now things like these will be told to the king. So now do come, and let us consult together.”

[[v16-6-8]]

^<<v16-6-8,8>>^ However, I sent to him, saying: “Things such as you are saying have not been brought about, but it is out of your own heart that you are inventing them.”

[[v16-6-9]]

^<<v16-6-9,9>>^ For all of them were trying to make us afraid, saying: “Their hands will drop down from the work so that it will not be done.” But now strengthen^&#42;1^ my hands.

[NOTE]
====
. “Strengthen,” imperative, M; LXXSyVg, “I strengthened.”
====

[[v16-6-10]]

^<<v16-6-10,10>>^ And I myself entered the house of She·maiʹah the son of De·laʹiah the son of Me·hetʹa·bel while he was shut up. And he proceeded to say: “Let us meet by appointment at the house of the &#91;true&#93; God, within the temple,^&#42;1^ and let us close the doors of the temple; for they are coming in to kill you, even by night they are coming in to kill you.”

[NOTE]
====
. “The temple.” Heb., ha·heh·khalʹ; Lat., temʹpli. See Mt 23:16 ftn.
====

[[v16-6-11]]

^<<v16-6-11,11>>^ But I said: “Should a man like me run away? And who is there like me that could enter into the temple and live? I shall not enter!”

[[v16-6-12]]

^<<v16-6-12,12>>^ So I investigated, and here it was not God that had sent him, but he had spoken this prophecy against me as To·biʹah and San·balʹlat themselves had hired him.

[[v16-6-13]]

^<<v16-6-13,13>>^ For this reason he had been hired in order that I might be afraid and do that way, and I should certainly sin and it should certainly become in their possession a bad reputation, in order that they might reproach me.

[[v16-6-14]]

^<<v16-6-14,14>>^ Do remember, O my God, To·biʹah and San·balʹlat, according to these deeds of &#91;each&#93; one, and also No·a·diʹah the prophetess and the rest of the prophets that were continually trying to make me afraid.

[[v16-6-15]]

^<<v16-6-15,15>>^ At length the wall came to completion on the twenty-fifth &#91;day&#93; of Eʹlul,^&#42;1^ in fifty-two days.

[NOTE]
====
. “Elul.” The postexilic name of the sixth Jewish lunar month, which falls within August and September.
====

[[v16-6-16]]

^<<v16-6-16,16>>^ And it came about that, as soon as all our enemies heard &#91;of it&#93; and all the nations that were around us got to see it, they at once fell very much in their own eyes, and they got to know that it was from our God that this work had been done.

[[v16-6-17]]

^<<v16-6-17,17>>^ In those days also the nobles of Judah were making numerous their letters that were going to To·biʹah and those of To·biʹah that were coming in to them.

[[v16-6-18]]

^<<v16-6-18,18>>^ For many in Judah were sworn^&#42;1^ to him, for a son-in-law he was to Shec·a·niʹah the son of Aʹrah; and Je·ho·haʹnan his son had himself taken the daughter of Me·shulʹlam the son of Ber·e·chiʹah.

[NOTE]
====
. Lit., “owners (lords) of an oath.”
====

[[v16-6-19]]

^<<v16-6-19,19>>^ Also, good things about him they were continually saying before me. And my own words they were continually taking out to him. There were letters that To·biʹah sent to make me afraid.

'''

xref:016-nehemiah/016-nehemiah-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-nehemiah/016-nehemiah-007.adoc#v16-7-0[Próximo Capítulo &#62;]