include::./index.adoc[]

[[v16-5-0]]
=== Nehemiah, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-5-1]]

^<<v16-5-1,1>>^ However, there came to be a great outcry of the people and their wives against their Jewish brothers.

[[v16-5-2]]

^<<v16-5-2,2>>^ And there were those who were saying: “Our sons and our daughters we are giving as security^&#42;1^ that we may get grain and eat and keep alive.”

[NOTE]
====
. “Giving as security,” by a slight correction of M. Compare vs 3.
====

[[v16-5-3]]

^<<v16-5-3,3>>^ And there were those who were saying: “Our fields and our vineyards and our houses we are giving as security that we may get grain during the food shortage.”

[[v16-5-4]]

^<<v16-5-4,4>>^ And there were those who were saying: “We have borrowed money for the king’s tribute on our fields and our vineyards.

[[v16-5-5]]

^<<v16-5-5,5>>^ And now our flesh is the same as the flesh of our brothers; our sons are the same as their sons, but here we are reducing our sons and our daughters to slaves, and there are some of our daughters already reduced; and there is no power in our hands while our fields and our vineyards belong to others.”

[[v16-5-6]]

^<<v16-5-6,6>>^ Now I became very angry as soon as I heard their outcry and these words.

[[v16-5-7]]

^<<v16-5-7,7>>^ So my heart took consideration within me, and I began finding fault with the nobles and the deputy rulers, and went on to say to them: “Usury is what YOU are exacting, each one from his own brother.”
Further, I arranged a great assembly on their account.

[[v16-5-8]]

^<<v16-5-8,8>>^ And I proceeded to say to them: “We ourselves have bought back our own Jewish brothers who were sold to the nations, as far as it was in our power; and at the same time will YOU yourselves sell YOUR own brothers, and must they be sold to us?” At this they became speechless, and they did not find a word.

[[v16-5-9]]

^<<v16-5-9,9>>^ And I^&#42;1^ went on to say: “The thing that YOU are doing is not good. Is it not in the fear of our God that YOU should walk because of the reproach of the nations, our enemies?

[NOTE]
====
. “I,” MmarginLXXSyVg; M, “he.”
====

[[v16-5-10]]

^<<v16-5-10,10>>^ And also I, my brothers and my attendants are giving money and grain on loan among them. Let us, please, leave off this lending on interest.

[[v16-5-11]]

^<<v16-5-11,11>>^ Please, restore to them on this day their fields, their vineyards, their olive groves and their houses, and the hundredth^&#42;1^ of the money and the grain, the new wine and the oil that YOU are exacting as interest from them.”

[NOTE]
====
. Or, “one percent,” that is, monthly.
====

[[v16-5-12]]

^<<v16-5-12,12>>^ To this they said: “We shall make restoration, and from them we shall ask nothing back. We shall do precisely as you are saying.” So I called the priests and made them swear to do according to this word.

[[v16-5-13]]

^<<v16-5-13,13>>^ Also, my bosom I shook out and then said: “In this manner may the &#91;true&#93; God shake out from his house and from his acquired property every man that does not carry out this word; and in this manner may he become shaken out and empty.” To this all the congregation^&#42;1^ said: “Amen!”^&#42;2^ And they began to praise Jehovah. And the people proceeded to do according to this word.

[NOTE]
====
. “The congregation.” Heb., haq·qa·halʹ; Gr., ek·kle·siʹa.
. Or, “So be it!” Heb., ʼa·menʹ; Gr., a·menʹ; Lat., aʹmen. See Ro 1:25.
====

[[v16-5-14]]

^<<v16-5-14,14>>^ Another thing: From the day that he commissioned me to become their governor^&#42;1^ in the land of Judah, from the twentieth year to the thirty-second year of Ar·ta·xerxʹes the king, twelve years, I myself and my brothers did not eat the bread due the governor.

[NOTE]
====
. “Their governor,” LXX; SyVg and one Heb. ms omit “their.”
====

[[v16-5-15]]

^<<v16-5-15,15>>^ As for the former governors that were prior to me, they had made it heavy upon the people, and they kept taking from them for bread and wine daily^&#42;1^ forty silver shekels.^&#42;2^ Also, their attendants themselves domineered over the people. As for me, I did not do that way on account of the fear of God.

[NOTE]
====
. “Daily,” Vg; M, “after.” Probably, “after (at) the rate of.”
. A shekel weighed 11.4 g (0.367 oz t). See App 8A.
====

[[v16-5-16]]

^<<v16-5-16,16>>^ And, what is more, in the work of this wall I took a hand, and not a field did we acquire; and all my attendants were collected together there for the work.

[[v16-5-17]]

^<<v16-5-17,17>>^ And the Jews and the deputy rulers, a hundred and fifty men, and those coming in to us from the nations that were around us were at my table.

[[v16-5-18]]

^<<v16-5-18,18>>^ As for that which happened to be made ready daily, one bull, six select sheep and birds were made ready for me, and once every ten days every sort of wine in abundance. And along with this the bread due the governor I did not demand, because the service upon this people was heavy.

[[v16-5-19]]

^<<v16-5-19,19>>^ Do remember for me, O my God, for good, all that I have done in behalf of this people.

'''

xref:016-nehemiah/016-nehemiah-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-nehemiah/016-nehemiah-006.adoc#v16-6-0[Próximo Capítulo &#62;]