include::./index.adoc[]

[[v16-2-0]]
=== Nehemiah, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-2-1]]

^<<v16-2-1,1>>^ And it came about in the month Niʹsan,^&#42;1^ in the twentieth year of Ar·ta·xerxʹes the king, that wine was before him, and I as usual took up the wine and gave it to the king. But never had I happened to be gloomy before him.

[NOTE]
====
. “Nisan.” The first of two occurrences of this postexilic name of the first Jewish lunar month, which falls within March and April. See Es 3:7.
====

[[v16-2-2]]

^<<v16-2-2,2>>^ So the king said to me: “Why is your face gloomy when you yourself are not sick? This is nothing but a gloominess of heart.” At this I became very much afraid.

[[v16-2-3]]

^<<v16-2-3,3>>^ Then I said to the king: “Let the king himself live to time indefinite! Why should not my face become gloomy when the city, the house of the burial places of my forefathers, is devastated, and its very gates have been eaten up with fire?”

[[v16-2-4]]

^<<v16-2-4,4>>^ In turn the king said to me: “What is this that you are seeking to secure?” At once I prayed to the God of the heavens.

[[v16-2-5]]

^<<v16-2-5,5>>^ After that I said to the king: “If to the king it does seem good, and if your servant seems good before you, that you would send me to Judah, to the city of the burial places of my forefathers, that I may rebuild it.”

[[v16-2-6]]

^<<v16-2-6,6>>^ At this the king said to me, as his queenly consort was sitting beside him: “How long will your journey come to be and when will you return?” So it seemed good before the king that he should send me, when I gave him the appointed time.

[[v16-2-7]]

^<<v16-2-7,7>>^ And I went on to say to the king: “If to the king it does seem good, let letters be given me to the governors beyond the River,^&#42;1^ that they may let me pass until I come to Judah;

[NOTE]
====
. That is, the Euphrates.
====

[[v16-2-8]]

^<<v16-2-8,8>>^ also a letter to Aʹsaph the keeper of the park^&#42;1^ that belongs to the king, that he may give me trees to build with timber the gates of the Castle^&#42;2^ that belongs to the house, and for the wall of the city and for the house into which I am to enter.” So the king gave &#91;them&#93; to me, according to the good hand of my God upon me.

[NOTE]
====
. “The park.” Heb., hap·par·desʹ; Gr., pa·ra·deiʹsou; Syr., par·dai·saʼ.
. Or, “the Fortress,” located to the northwest of the rebuilt temple.
====

[[v16-2-9]]

^<<v16-2-9,9>>^ Eventually I came to the governors beyond the River and gave them the letters of the king. Moreover, the king sent with me chiefs of the military force and horsemen.

[[v16-2-10]]

^<<v16-2-10,10>>^ When San·balʹlat the Horʹo·nite and To·biʹah the servant, the Amʹmon·ite, got to hear &#91;of it&#93;, then it seemed to them something very bad that a man^&#42;1^ had come to seek something good for the sons of Israel.

[NOTE]
====
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
====

[[v16-2-11]]

^<<v16-2-11,11>>^ At length I came to Jerusalem, and I continued there for three days.

[[v16-2-12]]

^<<v16-2-12,12>>^ Then I rose up by night, I and a few men with me, and I did not tell a man what my God was putting into my heart to do for Jerusalem, and there was no domestic animal with me except the domestic animal on which I was riding.

[[v16-2-13]]

^<<v16-2-13,13>>^ And I proceeded to go out by the Valley Gate by night and in front of the Fountain of the Big Snake^&#42;1^ and to the Gate of the Ash-heaps,^&#42;2^ and I was constantly examining the walls of Jerusalem, how they were broken down and the gates of it had been eaten up by fire.

[NOTE]
====
. Lit., “the Dragon Fountain,” MVg; by a correction of M in harmony with LXX, “the Fountain of the Fig Trees.” Probably the same as the Well of En-rogel.
. “The Gate of the Ash-heaps.” Usually called the Dung Gate as in LXXVg.
====

[[v16-2-14]]

^<<v16-2-14,14>>^ And I went passing along to the Fountain Gate and to the King’s Pool, and there was no place for the domestic animal under me to pass along.

[[v16-2-15]]

^<<v16-2-15,15>>^ But I kept on ascending in the torrent valley by night, and I kept on examining the wall; after which I came back and entered by the Valley Gate, and so got back.

[[v16-2-16]]

^<<v16-2-16,16>>^ And the deputy rulers themselves did not know where I had gone and what I was doing; and to the Jews and the priests and the nobles and the deputy rulers and the rest of the doers of the work I had not yet told anything.

[[v16-2-17]]

^<<v16-2-17,17>>^ Finally I said to them: “YOU are seeing the bad plight in which we are, how Jerusalem is devastated and its gates have been burned with fire. Come and let us rebuild the wall of Jerusalem, that we may no longer continue to be a reproach.”

[[v16-2-18]]

^<<v16-2-18,18>>^ And I went on to tell them of the hand of my God, how it was good upon me, and also of the king’s words that he had said to me. At this they said: “Let us get up, and we must build.” So they strengthened their hands for the good work.

[[v16-2-19]]

^<<v16-2-19,19>>^ Now when San·balʹlat the Horʹo·nite and To·biʹah the servant, the Amʹmon·ite, and Geʹshem the Arabian heard of it, they began to deride us and look on us despisingly and say: “What is this thing that YOU are doing? Is it against the king that YOU are rebelling?”

[[v16-2-20]]

^<<v16-2-20,20>>^ However, I replied to them and said to them: “The God of the heavens is the One that will grant us success, and we ourselves, his servants, shall get up, and we must build; but YOU yourselves have no share, nor just claim, nor memorial in Jerusalem.”

'''

xref:016-nehemiah/016-nehemiah-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-nehemiah/016-nehemiah-003.adoc#v16-3-0[Próximo Capítulo &#62;]