include::./index.adoc[]

[[v16-8-0]]
=== Nehemiah, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-8-1]]

^<<v16-8-1,1>>^ And all the people proceeded to gather themselves as one man at the public square that was before the Water Gate. Then they said to Ezʹra the copyist to bring the book of the law of Moses, which Jehovah had commanded Israel.

[[v16-8-2]]

^<<v16-8-2,2>>^ Accordingly Ezʹra the priest brought the law before the congregation^&#42;1^ of men as well as of women and of all intelligent enough to listen, on the first day of the seventh month.

[NOTE]
====
. “The congregation of.” Heb., haq·qa·halʹ; Gr., ek·kle·siʹas.
====

[[v16-8-3]]

^<<v16-8-3,3>>^ And he continued to read aloud from it before the public square that is before the Water Gate, from daybreak till midday, in front of the men and the women and the other intelligent ones; and the ears of all the people were &#91;attentive&#93; to the book of the law.

[[v16-8-4]]

^<<v16-8-4,4>>^ And Ezʹra the copyist kept standing upon a wooden podium,^&#42;1^ which they had made for the occasion;^&#42;2^ and there were standing alongside him Mat·ti·thiʹah and Sheʹma and A·naiʹah and U·riʹah and Hil·kiʹah and Ma·a·seiʹah to his right hand, and at his left Pe·daiʹah and Mishʹa·el and Mal·chiʹjah and Haʹshum and Hash-badʹda·nah, Zech·a·riʹah &#91;and&#93; Me·shulʹlam.

[NOTE]
====
. “Upon a wooden podium.” Heb., ʽal-migh·dal-ʽetsʹ; Gr., e·piʹ beʹma·tos xy·liʹnou.
. Lit., “word; saying; thing.”
====

[[v16-8-5]]

^<<v16-8-5,5>>^ And Ezʹra proceeded to open the book before the eyes of all the people, for he happened to be above all the people; and as he opened it all the people stood up.

[[v16-8-6]]

^<<v16-8-6,6>>^ Then Ezʹra blessed Jehovah the &#91;true&#93; God, the great One, at which all the people answered, “Amen! Amen!” with the lifting up of their hands. They then bowed low and prostrated themselves to Jehovah with &#91;their&#93; faces to the earth.

[[v16-8-7]]

^<<v16-8-7,7>>^ And Jeshʹu·a and Baʹni and She·re·biʹah, Jaʹmin, Akʹkub, Shabʹbe·thai, Ho·diʹah, Ma·a·seiʹah, Ke·liʹta, Az·a·riʹah, Joʹza·bad, Haʹnan, Pe·laʹiah, even the Levites, were explaining the law to the people,^&#42;1^ while the people were in a standing position.

[NOTE]
====
. Or, “instructing the people in the law.”
====

[[v16-8-8]]

^<<v16-8-8,8>>^ And they continued reading aloud from the book, from the law of the &#91;true&#93; God, it being expounded,^&#42;1^ and there being a putting^&#42;2^ of meaning &#91;into it&#93;; and they continued giving understanding in the reading.

[NOTE]
====
. Or, “interpreted.” Heb., mepho·rashʹ; Lat., di·stincʹte.
. “There being a putting.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v16-8-9]]

^<<v16-8-9,9>>^ And Ne·he·miʹah, that is, the Tir·shaʹtha, and Ezʹra the priest, the copyist, and the Levites who were instructing the people proceeded to say to all the people: “This very day is holy to Jehovah YOUR God. Do not mourn or weep.” For all the people were weeping as they were hearing the words of the law.

[[v16-8-10]]

^<<v16-8-10,10>>^ And he went on to say to them: “Go, eat the fatty things and drink the sweet things, and send portions to the one for whom nothing has been prepared; for this day is holy to our Lord,^&#42;1^ and do not feel hurt, for the joy of Jehovah is YOUR stronghold.”

[NOTE]
====
. “To our Lord.” Heb., la·ʼAdho·nehʹnu.
====

[[v16-8-11]]

^<<v16-8-11,11>>^ And the Levites were ordering all the people to be silent, saying: “Keep quiet! for this day is holy; and do not feel hurt.”

[[v16-8-12]]

^<<v16-8-12,12>>^ So all the people went away to eat and drink and to send out portions and to carry on a great rejoicing, for they had understood the words that had been made known to them.

[[v16-8-13]]

^<<v16-8-13,13>>^ And on the second day the heads of the fathers of all the people, the priests and the Levites, gathered themselves together to Ezʹra the copyist, even to gain insight into the words of the law.

[[v16-8-14]]

^<<v16-8-14,14>>^ Then they found written in the law that Jehovah had commanded by means of Moses that the sons of Israel should dwell in booths during the festival in the seventh month,

[[v16-8-15]]

^<<v16-8-15,15>>^ and that they should make proclamation and cause a call to pass throughout all their cities and throughout Jerusalem, saying: “Go out to the mountainous region and bring in olive leaves and the leaves of oil trees and myrtle leaves and palm leaves and the leaves of branchy trees to make booths, according to what is written.”

[[v16-8-16]]

^<<v16-8-16,16>>^ And the people proceeded to go out and bring &#91;them&#93; in and make booths for themselves, each one upon his own roof and in their courtyards and in the courtyards of the house of the &#91;true&#93; God and in the public square of the Water Gate and in the public square of the Gate of Eʹphra·im.

[[v16-8-17]]

^<<v16-8-17,17>>^ Thus all the congregation of those who had come back from the captivity made booths and took up dwelling in the booths; for the sons of Israel had not done that way from the days of Joshua^&#42;1^ the son of Nun until that day, so that there came to be very great rejoicing.

[NOTE]
====
. “Joshua.” Heb., Ye·shuʹaʽ; LXX, “Jesus.” Compare Jos 1:1 ftn, “Joshua.”
====

[[v16-8-18]]

^<<v16-8-18,18>>^ And there was a reading aloud of the book of the law of the &#91;true&#93; God day by day, from the first day until the last day; and they went on holding the festival seven days, and on the eighth day there was a solemn assembly, according to the rule.

'''

xref:016-nehemiah/016-nehemiah-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-nehemiah/016-nehemiah-009.adoc#v16-9-0[Próximo Capítulo &#62;]