include::./index.adoc[]

[[v16-9-0]]
=== Nehemiah, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-9-1]]

^<<v16-9-1,1>>^ And on the twenty-fourth day of this month the sons of Israel gathered themselves together with fasting and with sackcloth and dirt upon themselves.

[[v16-9-2]]

^<<v16-9-2,2>>^ And the seed of Israel proceeded to separate themselves from all the foreigners,^&#42;1^ and to stand and make confession of their own sins and the errors of their fathers.

[NOTE]
====
. Lit., “sons of a foreign (country).”
====

[[v16-9-3]]

^<<v16-9-3,3>>^ Then they rose up at their place and they read aloud from the book of the law of Jehovah their God a fourth part of the day; and a fourth part they were making confession and bowing down to Jehovah their God.

[[v16-9-4]]

^<<v16-9-4,4>>^ And Jeshʹu·a and Baʹni, Kadʹmi·el, Sheb·a·niʹah, Bunʹni, She·re·biʹah, Baʹni &#91;and&#93; Che·naʹni proceeded to rise on the platform of the Levites and cry out with a loud voice to Jehovah their God.

[[v16-9-5]]

^<<v16-9-5,5>>^ And the Levites Jeshʹu·a and Kadʹmi·el, Baʹni, Hash·ab·neiʹah, She·re·biʹah, Ho·diʹah, Sheb·a·niʹah &#91;and&#93; Peth·a·hiʹah went on to say: “Rise, bless Jehovah YOUR God from time indefinite to time indefinite. And let them bless your glorious name, which is exalted above all blessing and praise.

[[v16-9-6]]

^<<v16-9-6,6>>^ “You are Jehovah alone; you yourself have made the heavens, &#91;even&#93; the heaven of the heavens, and all their army, the earth and all that is upon it, the seas and all that is in them; and you are preserving all of them alive; and the army of the heavens are bowing down to you.

[[v16-9-7]]

^<<v16-9-7,7>>^ You are Jehovah the &#91;true&#93; God, who chose Aʹbram and brought him out of Ur of the Chal·deʹans and constituted his name Abraham.

[[v16-9-8]]

^<<v16-9-8,8>>^ And you found his heart faithful before you; so there was a contracting^&#42;1^ of the covenant with him to give &#91;him&#93; the land of the Caʹnaan·ites, the Hitʹtites, the Amʹor·ites and the Perʹiz·zites and the Jebʹu·sites and the Girʹga·shites, to give &#91;it&#93; to his seed; and you proceeded to carry out your words, because you are righteous.

[NOTE]
====
. “There was a contracting.” In Heb. this is a verb in the infinitive absolute, indefinite as to time and impersonal.
====

[[v16-9-9]]

^<<v16-9-9,9>>^ “So you saw the affliction of our forefathers in Egypt, and their outcry at the Red Sea you heard.

[[v16-9-10]]

^<<v16-9-10,10>>^ Then you gave signs and miracles against Pharʹaoh and all his servants and all the people of his land, for you knew that they acted presumptuously against them; and you proceeded to make a name for yourself as at this day.

[[v16-9-11]]

^<<v16-9-11,11>>^ And the sea you split before them, so that they crossed over through the midst of the sea on the dry land; and their pursuers you hurled into the depths like a stone in the strong waters.

[[v16-9-12]]

^<<v16-9-12,12>>^ And by a pillar of cloud you led them by day, and by a pillar of fire by night, to light up for them the way in which they should go.

[[v16-9-13]]

^<<v16-9-13,13>>^ And upon Mount Siʹnai you came down and spoke with them out of heaven and went on to give them upright judicial decisions and laws of truth, good regulations and commandments.

[[v16-9-14]]

^<<v16-9-14,14>>^ And your holy sabbath you made known to them, and commandments and regulations and a law you commanded them by means of Moses your servant.

[[v16-9-15]]

^<<v16-9-15,15>>^ And bread from heaven you gave them for their hunger, and waters out of the crag you brought forth to them for their thirst, and you went on to say to them to enter and possess the land that you had lifted your hand &#91;in an oath&#93; to give to them.

[[v16-9-16]]

^<<v16-9-16,16>>^ “And they themselves, even our forefathers, acted presumptuously and proceeded to harden their neck, and they did not listen to your commandments.

[[v16-9-17]]

^<<v16-9-17,17>>^ So they refused to listen, and they did not remember your wonderful acts that you performed with them, but they hardened their neck and appointed a head to return to their servitude in Egypt.^&#42;1^ But you are a God^&#42;2^ of acts of forgiveness, gracious and merciful, slow to anger and abundant in loving-kindness, and you did not leave them.

[NOTE]
====
. “In Egypt,” LXX and some Heb. mss; M, “in their rebellion.”
. “A God.” Heb., ʼElohʹah, sing. of ʼElo·himʹ.
====

[[v16-9-18]]

^<<v16-9-18,18>>^ Yes, when they had made for themselves a molten statue of a calf and began to say, ‘This is your God^&#42;1^ who led you up out of Egypt,’ and they went on to commit great acts of disrespect,

[NOTE]
====
. “Your God.” Heb., ʼelo·heyʹkha, pl. to denote excellence, because the demonstrative pronoun zeh, “this,” and the verb he·ʽel·khaʹ, “led you,” are sing., showing that “God” is sing.; Gr., hoi the·oiʹ, “gods”; Lat., Deʹus tuʹus, “your God.” Compare Ex 32:4 ftn, “God.”
====

[[v16-9-19]]

^<<v16-9-19,19>>^ you, even you, in your abundant mercy did not leave them in the wilderness. The pillar of cloud itself did not depart from over them by day to lead them in the way, nor the pillar of fire by night to light up for them the way in which they should go.

[[v16-9-20]]

^<<v16-9-20,20>>^ And your good spirit you gave to make them prudent, and your manna you did not hold back from their mouth, and water you gave them for their thirst.

[[v16-9-21]]

^<<v16-9-21,21>>^ And for forty years you provided them with food in the wilderness. They lacked nothing. Their very garments did not wear out, and their feet themselves did not become swollen.

[[v16-9-22]]

^<<v16-9-22,22>>^ “And you proceeded to give them kingdoms and peoples, and to apportion them piece by piece; so that they took possession of the land of Siʹhon, even the land of the king of Heshʹbon, and the land of Og the king of Baʹshan.

[[v16-9-23]]

^<<v16-9-23,23>>^ And their sons you made as many as the stars of the heavens. Then you brought them into the land that you had promised to their forefathers that &#91;they&#93; should enter to take possession.

[[v16-9-24]]

^<<v16-9-24,24>>^ So their sons came in and took the land in possession, and you proceeded to subdue before them the inhabitants of the land, the Caʹnaan·ites, and to give them into their hand, even their kings and the peoples of the land, to do with them according to their liking.

[[v16-9-25]]

^<<v16-9-25,25>>^ And they went capturing fortified cities and a fat soil and taking in possession houses full of all good things, cisterns hewn out, vineyards and olive groves and trees for food in abundance, and they began to eat and to be satisfied and to grow fat and to luxuriate in your great goodness.

[[v16-9-26]]

^<<v16-9-26,26>>^ “However, they became disobedient and rebelled against you and kept casting your law behind their back, and your own prophets they killed, who bore witness against them to bring them back to you; and they went on committing acts of great disrespect.

[[v16-9-27]]

^<<v16-9-27,27>>^ For this you gave them into the hand of their adversaries, who kept causing them distress; but in the time of their distress they would cry out to you, and you yourself would hear from the very heavens; and in accord with your abundant mercy you would give them saviors who would save them out of the hand of their adversaries.

[[v16-9-28]]

^<<v16-9-28,28>>^ “But as soon as they were at rest, they would again do what is bad before you, and you would leave them to the hand of their enemies, who would tread them down. Then they would return and call to you for aid, and you yourself would hear from the very heavens and deliver them in accord with your abundant mercy, time and again.

[[v16-9-29]]

^<<v16-9-29,29>>^ Although you would bear witness against them to bring them back to your law, they themselves even acted presumptuously and did not listen to your commandments; and against your own judicial decisions they sinned, which, if a man^&#42;1^ will do, he must also live by means of them.^&#42;2^ And they kept giving a stubborn shoulder, and their neck they hardened, and they did not listen.

[NOTE]
====
. Or, “an earthling man.” Heb., ʼa·dhamʹ.
. Or, “live in them.”
====

[[v16-9-30]]

^<<v16-9-30,30>>^ But you were indulgent with them for many years and kept bearing witness against them by your spirit by means of your prophets, and they did not give ear. Finally you gave them into the hand of the peoples of the lands.

[[v16-9-31]]

^<<v16-9-31,31>>^ And in your abundant mercy you did not make an extermination of them or leave them; for you are a God^&#42;1^ gracious and merciful.

[NOTE]
====
. “God.” Heb., ʼEl.
====

[[v16-9-32]]

^<<v16-9-32,32>>^ “And now, O our God, the God^&#42;1^ great, mighty and fear-inspiring,^&#42;2^ keeping the covenant and loving-kindness,^&#42;3^ do not let all the hardship that has found us, our kings, our princes and our priests and our prophets and our forefathers and all your people from the days of the kings of As·syrʹi·a down to this day, seem little before you.

[NOTE]
====
. Or, “the [true] God.” The title ʼEl preceded by the Heb. definite article ha, “the,” but followed by the qualifications “great, mighty and fear-inspiring.” See App 1G.
. “And fear-inspiring (reverend).” Heb., wehan·noh·raʼʹ.
. Or, “loyal love.”
====

[[v16-9-33]]

^<<v16-9-33,33>>^ And you are righteous as regards all that has come upon us, for faithfully is how you have acted, but we are the ones that have done wickedly.

[[v16-9-34]]

^<<v16-9-34,34>>^ As for our kings, our princes, our priests and our forefathers, they have not performed your law, nor paid attention to your commandments or to your testimonies^&#42;1^ with which you bore witness against them.

[NOTE]
====
. Or, “reminders; exhortations.”
====

[[v16-9-35]]

^<<v16-9-35,35>>^ And they themselves—during their^&#42;1^ kingdom and amid your abundant good things that you gave to them and in the broad and fat land that you made available for them, they did not serve you and did not turn back from their bad practices.

[NOTE]
====
. “Their,” MVg; LXXSy and two Heb. mss, “your.”
====

[[v16-9-36]]

^<<v16-9-36,36>>^ Look! We are today slaves; and as for the land that you gave to our forefathers to eat its fruitage and its good things, look! we are slaves upon it,

[[v16-9-37]]

^<<v16-9-37,37>>^ and its produce is abounding for the kings that you have put over us because of our sins, and over our bodies they are ruling and over our domestic animals, according to their liking, and we are in great distress.^&#42;1^

[NOTE]
====
. MLXX end chapter 9 here.
====

[[v16-9-38]]

^<<v16-9-38,38>>^ “So in view of all this we are contracting^&#42;1^ a trustworthy arrangement, both in writing and attested by the seal of our princes,^&#42;2^ our Levites &#91;and&#93; our priests.”

[NOTE]
====
. Lit., “cutting.”
. Lit., “and upon what was sealed of our princes.”
====

'''

xref:016-nehemiah/016-nehemiah-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-nehemiah/016-nehemiah-010.adoc#v16-10-0[Próximo Capítulo &#62;]