include::./index.adoc[]

[[v16-4-0]]
=== Nehemiah, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-4-1]]

^<<v16-4-1,1>>^ ^&#42;1^ Now it came about that, as soon as San·balʹlat heard that we were rebuilding the wall, he became angry and highly offended, and he kept deriding the Jews.

[NOTE]
====
. In M this is 3:33.
====

[[v16-4-2]]

^<<v16-4-2,2>>^ And he began to say before his brothers and the military force of Sa·marʹi·a, yes, he began to say: “What are the feeble Jews doing? Will they depend upon themselves? Will they sacrifice? Will they finish up in a day? Will they bring the stones to life out of the heaps of dusty rubbish when they are burned?”

[[v16-4-3]]

^<<v16-4-3,3>>^ Now To·biʹah the Amʹmon·ite was alongside him, and he went on to say: “Even what they are building, if a fox went up &#91;against it&#93;, he would certainly break down their wall of stones.”

[[v16-4-4]]

^<<v16-4-4,4>>^ Hear, O our God, for we have become an object of contempt; and make their reproach return upon their own head, and give them to the plunder in the land of captivity.

[[v16-4-5]]

^<<v16-4-5,5>>^ And do not cover over their error and their sin from before you. Let it not be wiped out, for they have committed offense against the builders.

[[v16-4-6]]

^<<v16-4-6,6>>^ So we kept building the wall, and the entire wall came to be joined together clear to half its &#91;height&#93;, and the people continued to have a heart for working.

[[v16-4-7]]

^<<v16-4-7,7>>^ ^&#42;1^ Now it came about that, as soon as San·balʹlat and To·biʹah and the Arabians and the Amʹmon·ites and the Ashʹdod·ites heard that the repairing of the walls of Jerusalem had gone forward, for the gaps had started to be stopped up, they became very angry.

[NOTE]
====
. M begins chapter 4 here.
====

[[v16-4-8]]

^<<v16-4-8,8>>^ And all of them began to conspire together to come and fight against Jerusalem and cause me^&#42;1^ disturbance.

[NOTE]
====
. “Me,” by a slight correction; M, “him.”
====

[[v16-4-9]]

^<<v16-4-9,9>>^ But we prayed to our God and kept a guard posted against them day and night on account of them.

[[v16-4-10]]

^<<v16-4-10,10>>^ And Judah began to say: “The power of the burden bearer has stumbled, and there is a great deal of rubbish; and we ourselves are not able to build on the wall.”

[[v16-4-11]]

^<<v16-4-11,11>>^ Moreover, our adversaries kept saying: “They will not know and they will not see until we come right in among them, and we shall certainly kill them and put a stop to the work.”

[[v16-4-12]]

^<<v16-4-12,12>>^ And it came about that, whenever the Jews dwelling close by them came in, they proceeded to say to us ten times: “&#91;They will come up&#93;^&#42;1^ from all the places where YOU people will return to us.”

[NOTE]
====
. “They are coming up,” LXX; M omits.
====

[[v16-4-13]]

^<<v16-4-13,13>>^ So I kept &#91;men&#93; posted at the lowest parts of the place behind the wall at the open places, and I kept the people posted by families with their swords, their lances and their bows.

[[v16-4-14]]

^<<v16-4-14,14>>^ When I saw &#91;their fear&#93; I immediately rose and said to the nobles and the deputy rulers and the rest of the people: “Do not be afraid on their account. Jehovah^&#42;1^ the great and the fear-inspiring One keep in YOUR mind; and fight for YOUR brothers, YOUR sons and YOUR daughters, YOUR wives and YOUR homes.”

[NOTE]
====
. One of 134 scribal changes from YHWH to ʼAdho·naiʹ. See App 1B.
====

[[v16-4-15]]

^<<v16-4-15,15>>^ Now it came about that as soon as our enemies heard that it had become known to us, so that the &#91;true&#93; God^&#42;1^ had frustrated their counsel and we had all of us gone back to the wall, each one to his work,

[NOTE]
====
. “The [true] God.” The definite article ha, “the,” precedes the title ʼElo·himʹ for emphasis. See App 1F.
====

[[v16-4-16]]

^<<v16-4-16,16>>^ yes, it came about that from that day forward half of my young men were active in the work and half of them were holding the lances, the shields and the bows and the coats of mail; and the princes were behind the whole house of Judah.

[[v16-4-17]]

^<<v16-4-17,17>>^ As for the builders on the wall and those who were carrying the burden of load bearers, &#91;each&#93; one was active in the work with his one hand while the other &#91;hand&#93; was holding the missile.

[[v16-4-18]]

^<<v16-4-18,18>>^ And the builders were girded, each one with his sword upon his hip, while building; and the one to blow the horn was alongside me.

[[v16-4-19]]

^<<v16-4-19,19>>^ And I proceeded to say to the nobles and the deputy rulers and the rest of the people: “The work is large and extensive, and we are spread about upon the wall far apart from one another.

[[v16-4-20]]

^<<v16-4-20,20>>^ In the place where YOU hear the sound of the horn,^&#42;1^ there is where YOU will collect yourselves together to us. Our God himself will fight for us.”

[NOTE]
====
. Or, “the shofar.”
====

[[v16-4-21]]

^<<v16-4-21,21>>^ While we were active in the work, the other half of them also were holding the lances, from the ascending of the dawn until the stars came out.

[[v16-4-22]]

^<<v16-4-22,22>>^ Besides, at that time I said to the people: “Let the men spend the night, each one with his attendant, in the midst of Jerusalem, and they must become for us a guard by night and workers^&#42;1^ by day.”

[NOTE]
====
. Lit., “work.”
====

[[v16-4-23]]

^<<v16-4-23,23>>^ As for me and my brothers and my attendants and the men of the guard who were behind me, we were not taking off our garments, each one &#91;having&#93; his missile in his right hand.^&#42;1^

[NOTE]
====
. “In his right hand,” by a correction; M is obscure. Lit., “the waters.”
====

'''

xref:016-nehemiah/016-nehemiah-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-nehemiah/016-nehemiah-005.adoc#v16-5-0[Próximo Capítulo &#62;]