include::./index.adoc[]

[[v16-10-0]]
=== Nehemiah, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-10-1]]

^<<v16-10-1,1>>^ Now attesting it by seal^&#42;1^ there were:
Ne·he·miʹah the Tir·shaʹtha, the son of Hac·a·liʹah,
And Zed·e·kiʹah,

[NOTE]
====
. Lit., “And upon the ones sealed.”
====

[[v16-10-2]]

^<<v16-10-2,2>>^ Se·raiʹah, Az·a·riʹah, Jeremiah,

[[v16-10-3]]

^<<v16-10-3,3>>^ Pashʹhur, Am·a·riʹah, Mal·chiʹjah,

[[v16-10-4]]

^<<v16-10-4,4>>^ Hatʹtush, Sheb·a·niʹah, Malʹluch,

[[v16-10-5]]

^<<v16-10-5,5>>^ Haʹrim, Merʹe·moth, O·ba·diʹah,

[[v16-10-6]]

^<<v16-10-6,6>>^ Daniel, Ginʹne·thon, Barʹuch,

[[v16-10-7]]

^<<v16-10-7,7>>^ Me·shulʹlam, A·biʹjah, Mijʹa·min,

[[v16-10-8]]

^<<v16-10-8,8>>^ Ma·a·ziʹah, Bilʹgai &#91;and&#93; She·maiʹah, these being the priests.

[[v16-10-9]]

^<<v16-10-9,9>>^ Also the Levites: Jeshʹu·a the son of Az·a·niʹah, Binʹnu·i of the sons of Henʹa·dad, Kadʹmi·el

[[v16-10-10]]

^<<v16-10-10,10>>^ and their brothers Sheb·a·niʹah, Ho·diʹah, Ke·liʹta, Pe·laʹiah, Haʹnan,

[[v16-10-11]]

^<<v16-10-11,11>>^ Miʹca, Reʹhob, Hash·a·biʹah,

[[v16-10-12]]

^<<v16-10-12,12>>^ Zacʹcur, She·re·biʹah, Sheb·a·niʹah,

[[v16-10-13]]

^<<v16-10-13,13>>^ Ho·diʹah, Baʹni &#91;and&#93; Be·niʹnu.

[[v16-10-14]]

^<<v16-10-14,14>>^ The heads of the people: Paʹrosh, Paʹhath-moʹab, Eʹlam, Zatʹtu, Baʹni,

[[v16-10-15]]

^<<v16-10-15,15>>^ Bunʹni, Azʹgad, Beʹbai,

[[v16-10-16]]

^<<v16-10-16,16>>^ Ad·o·niʹjah,^&#42;1^ Bigʹvai, Aʹdin,

[NOTE]
====
. “Adonikam” in Ezr 2:13.
====

[[v16-10-17]]

^<<v16-10-17,17>>^ Aʹter, Hez·e·kiʹah, Azʹzur,

[[v16-10-18]]

^<<v16-10-18,18>>^ Ho·diʹah, Haʹshum, Beʹzai,

[[v16-10-19]]

^<<v16-10-19,19>>^ Haʹriph,^&#42;1^ Anʹa·thoth, Neʹbai,

[NOTE]
====
. “Jorah” in Ezr 2:18.
====

[[v16-10-20]]

^<<v16-10-20,20>>^ Magʹpi·ash, Me·shulʹlam, Heʹzir,

[[v16-10-21]]

^<<v16-10-21,21>>^ Me·shezʹa·bel, Zaʹdok, Jadʹdu·a,

[[v16-10-22]]

^<<v16-10-22,22>>^ Pel·a·tiʹah, Haʹnan, A·naiʹah,

[[v16-10-23]]

^<<v16-10-23,23>>^ Ho·sheʹa, Han·a·niʹah, Hasʹshub,

[[v16-10-24]]

^<<v16-10-24,24>>^ Hal·loʹhesh, Pilʹha, Shoʹbek,

[[v16-10-25]]

^<<v16-10-25,25>>^ Reʹhum, Ha·shabʹnah, Ma·a·seiʹah,

[[v16-10-26]]

^<<v16-10-26,26>>^ and A·hiʹjah, Haʹnan, Aʹnan,

[[v16-10-27]]

^<<v16-10-27,27>>^ Malʹluch, Haʹrim, Baʹa·nah.

[[v16-10-28]]

^<<v16-10-28,28>>^ As for the rest of the people, the priests, the Levites, the gatekeepers, the singers, the Nethʹi·nim^&#42;1^ and everyone separating himself from the peoples of the lands to the law of the &#91;true&#93; God, their wives, their sons and their daughters, everyone having knowledge &#91;and&#93; understanding,

[NOTE]
====
. Or, “the temple slaves.” Lit., “the given ones.” Compare Nu 3:9 ftn.
====

[[v16-10-29]]

^<<v16-10-29,29>>^ they were adhering to their brothers, their majestic ones, and coming into &#91;liability to&#93; a curse and into an oath, to walk in the law of the &#91;true&#93; God, which had been given by the hand of Moses the servant of the &#91;true&#93; God, and to keep and to perform all the commandments of Jehovah our Lord and his judicial decisions and his regulations;

[[v16-10-30]]

^<<v16-10-30,30>>^ and that we should not give our daughters to the peoples of the land, and their daughters we should not take for our sons.

[[v16-10-31]]

^<<v16-10-31,31>>^ As for the peoples of the land who were bringing in wares and every kind of cereal on the sabbath day to sell, we should take nothing from them on the sabbath or on a holy day, and we should forego the seventh year and the debt of every hand.

[[v16-10-32]]

^<<v16-10-32,32>>^ Also, we imposed upon ourselves commandments to give, each of us, a third of a shekel^&#42;1^ yearly for the service of the house of our God,

[NOTE]
====
. A shekel weighed 11.4 g (0.367 oz t). See App 8A.
====

[[v16-10-33]]

^<<v16-10-33,33>>^ for the layer bread and the constant grain offering and the constant burnt offering of the sabbaths, the new moons, for the appointed feasts and for the holy things and for the sin offerings to make atonement for Israel and all the work of the house of our God.

[[v16-10-34]]

^<<v16-10-34,34>>^ Also, the lots we cast concerning the supply^&#42;1^ of the wood that the priests, the Levites and the people should bring to the house of our God, by the house of our forefathers, at the appointed times, year by year, to burn upon the altar of Jehovah our God, according to what is written in the law;

[NOTE]
====
. Or, “offering of.” Heb., qur·banʹ. See “corban” in Mr 7:11.
====

[[v16-10-35]]

^<<v16-10-35,35>>^ and to bring the first ripe fruits of our ground and the first ripe fruits of all the fruitage of every sort of tree, year by year, to the house of Jehovah;

[[v16-10-36]]

^<<v16-10-36,36>>^ and the firstborn of our sons and of our domestic animals, according to what is written in the law, and the firstborn of our herds and of our flocks, to bring &#91;them&#93; to the house of our God, to the priests that were ministering in the house of our God.

[[v16-10-37]]

^<<v16-10-37,37>>^ Also, the firstfruits of our coarse meal and our contributions and the fruitage of every sort of tree, new wine and oil we should bring to the priests to the dining halls of the house of our God, also the tenth^&#42;1^ from our soil to the Levites, as they, the Levites, are the ones receiving a tenth in all our agricultural cities.

[NOTE]
====
. Or, “tithe.”
====

[[v16-10-38]]

^<<v16-10-38,38>>^ And the priest, the son of Aaron, must prove to be with the Levites when the Levites receive a tenth; and the Levites themselves should offer up a tenth of the tenth to the house of our God to the dining halls of the supply house.

[[v16-10-39]]

^<<v16-10-39,39>>^ For it is to the dining halls that the sons of Israel and the sons of the Levites should bring the contribution of the grain, the new wine and the oil, and there is where the utensils of the sanctuary and the priests that were ministering, and the gatekeepers and the singers are; and we should not neglect the house of our God.

'''

xref:016-nehemiah/016-nehemiah-009.adoc#v16-9-0[&#60; Capítulo Anterior] | <<v16-10-0,Topo>> | xref:016-nehemiah/016-nehemiah-011.adoc#v16-11-0[Próximo Capítulo &#62;]