include::./index.adoc[]

[[v16-12-0]]
=== Nehemiah, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v16-12-1]]

^<<v16-12-1,1>>^ And these were the priests and the Levites that went up with Ze·rubʹba·bel the son of She·alʹti·el and Jeshʹu·a: Se·raiʹah, Jeremiah, Ezʹra,

[[v16-12-2]]

^<<v16-12-2,2>>^ Am·a·riʹah, Malʹluch, Hatʹtush,

[[v16-12-3]]

^<<v16-12-3,3>>^ Shec·a·niʹah, Reʹhum, Merʹe·moth,

[[v16-12-4]]

^<<v16-12-4,4>>^ Idʹdo, Ginʹne·thoi, A·biʹjah,

[[v16-12-5]]

^<<v16-12-5,5>>^ Mijʹa·min, Ma·a·diʹah, Bilʹgah,

[[v16-12-6]]

^<<v16-12-6,6>>^ She·maiʹah, and Joiʹa·rib, Je·daʹiah,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salʹlu,^&#42;1^ Aʹmok, Hil·kiʹah, Je·daʹiah. These were the heads of the priests and their brothers in the days of Jeshʹu·a.

[NOTE]
====
. Probably the same as “Sallai” in vs 20.
====

[[v16-12-8]]

^<<v16-12-8,8>>^ And the Levites were Jeshʹu·a, Binʹnu·i, Kadʹmi·el, She·re·biʹah, Judah, Mat·ta·niʹah, over the giving of thanks, he and his brothers.

[[v16-12-9]]

^<<v16-12-9,9>>^ And Bak·bu·kiʹah and Unʹni their brothers were opposite them for guard duties.

[[v16-12-10]]

^<<v16-12-10,10>>^ Jeshʹu·a himself became father to Joiʹa·kim, and Joiʹa·kim himself became father to E·liʹa·shib, and E·liʹa·shib to Joiʹa·da.

[[v16-12-11]]

^<<v16-12-11,11>>^ And Joiʹa·da himself became father to Jonʹa·than, and Jonʹa·than himself became father to Jadʹdu·a.

[[v16-12-12]]

^<<v16-12-12,12>>^ And in the days of Joiʹa·kim there happened to be priests, the heads of the paternal houses: for Se·raiʹah, Me·raiʹah; for Jeremiah, Han·a·niʹah;

[[v16-12-13]]

^<<v16-12-13,13>>^ for Ezʹra, Me·shulʹlam; for Am·a·riʹah, Je·ho·haʹnan;

[[v16-12-14]]

^<<v16-12-14,14>>^ for Malʹlu·chi,^&#42;1^ Jonʹa·than; for Sheb·a·niʹah, Joseph;

[NOTE]
====
. “Malluch,” LXX.
====

[[v16-12-15]]

^<<v16-12-15,15>>^ for Haʹrim, Adʹna; for Me·raʹioth, Helʹkai;

[[v16-12-16]]

^<<v16-12-16,16>>^ for Idʹdo, Zech·a·riʹah; for Ginʹne·thon, Me·shulʹlam;

[[v16-12-17]]

^<<v16-12-17,17>>^ for A·biʹjah, Zichʹri; for Mi·niʹa·min,^&#42;1^ ——;^&#42;2^ for Mo·a·diʹah, Pilʹtai;

[NOTE]
====
. “Mijamin” in vs 5.
. M evidently omits a name here.
====

[[v16-12-18]]

^<<v16-12-18,18>>^ for Bilʹgah, Sham·muʹa; for She·maiʹah, Je·honʹa·than;

[[v16-12-19]]

^<<v16-12-19,19>>^ and for Joiʹa·rib, Mat·teʹnai; for Je·daʹiah, Uzʹzi;

[[v16-12-20]]

^<<v16-12-20,20>>^ for Sal·laʹi, Kalʹlai; for Aʹmok, Eʹber;

[[v16-12-21]]

^<<v16-12-21,21>>^ for Hil·kiʹah, Hash·a·biʹah; for Je·daʹiah, Ne·thanʹel.

[[v16-12-22]]

^<<v16-12-22,22>>^ The Levites in the days of E·liʹa·shib, Joiʹa·da and Jo·haʹnan and Jadʹdu·a were recorded as heads of paternal houses, also the priests, down till the kingship of Da·riʹus the Persian.

[[v16-12-23]]

^<<v16-12-23,23>>^ The sons of Leʹvi as heads of the paternal houses were recorded in the book of the affairs of the times, even down till the days of Jo·haʹnan the son of E·liʹa·shib.

[[v16-12-24]]

^<<v16-12-24,24>>^ And the heads of the Levites were Hash·a·biʹah, She·re·biʹah and Jeshʹu·a^&#42;1^ the son of Kadʹmi·el and their brothers opposite them to offer praise &#91;and&#93; give thanks according to the commandment of David the man of the &#91;true&#93; God, guard group corresponding with guard group.

[NOTE]
====
. “Jesu,” LXX.
====

[[v16-12-25]]

^<<v16-12-25,25>>^ Mat·ta·niʹah and Bak·bu·kiʹah, O·ba·diʹah, Me·shulʹlam, Talʹmon, Akʹkub were keeping guard as gatekeepers, a guard group by the stores of the gates.

[[v16-12-26]]

^<<v16-12-26,26>>^ These were in the days of Joiʹa·kim the son of Jeshʹu·a the son of Joʹza·dak and in the days of Ne·he·miʹah the governor and Ezʹra the priest, the copyist.

[[v16-12-27]]

^<<v16-12-27,27>>^ And at the inauguration of the wall of Jerusalem they looked for the Levites, to bring them out of all their places to Jerusalem to carry on an inauguration and a rejoicing even with thanksgivings and with song, cymbals &#91;and&#93; stringed instruments and with harps.

[[v16-12-28]]

^<<v16-12-28,28>>^ And the sons of the singers proceeded to gather themselves even from the District, from all around Jerusalem and from the settlements of the Ne·tophʹa·thites,

[[v16-12-29]]

^<<v16-12-29,29>>^ and from Beth-gilʹgal and from the fields of Geʹba and Azʹma·veth, for there were settlements that the singers had built for themselves all around Jerusalem.

[[v16-12-30]]

^<<v16-12-30,30>>^ And the priests and the Levites proceeded to cleanse themselves and cleanse the people and the gates and the wall.

[[v16-12-31]]

^<<v16-12-31,31>>^ Then I brought up the princes of Judah upon the wall. Further, I appointed two large thanksgiving choirs and processions, &#91;and the one was walking&#93;^&#42;1^ to the right upon the wall to the Gate of the Ash-heaps.^&#42;2^

[NOTE]
====
. Inserted to agree with vs 38.
. “The Gate of the Ash-heaps.” Usually called the Dung Gate as in LXXVg.
====

[[v16-12-32]]

^<<v16-12-32,32>>^ And Ho·shaiʹah and half of the princes of Judah began to walk behind them,

[[v16-12-33]]

^<<v16-12-33,33>>^ also Az·a·riʹah, Ezʹra and Me·shulʹlam,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judah and Benjamin and She·maiʹah and Jeremiah;

[[v16-12-35]]

^<<v16-12-35,35>>^ also of the sons of the priests with the trumpets Zech·a·riʹah the son of Jonʹa·than the son of She·maiʹah the son of Mat·ta·niʹah the son of Mi·caiʹah the son of Zacʹcur the son of Aʹsaph,

[[v16-12-36]]

^<<v16-12-36,36>>^ and his brothers She·maiʹah and Azʹar·el, Milʹa·lai, Gilʹa·lai, Maʹai, Ne·thanʹel and Judah, Ha·naʹni, with the instruments of song of David the man of the &#91;true&#93; God; and Ezʹra the copyist before them.

[[v16-12-37]]

^<<v16-12-37,37>>^ And at the Fountain Gate and straight ahead of them they went up on the Stairway of the City of David by the ascent of the wall above the House of David and clear to the Water Gate to the east.

[[v16-12-38]]

^<<v16-12-38,38>>^ And the other thanksgiving choir was walking in front, and I after it, also half of the people, upon the wall up over the Tower of the Bake Ovens and on to the Broad Wall,

[[v16-12-39]]

^<<v16-12-39,39>>^ and up over the Gate of Eʹphra·im and on to the Gate of the Old &#91;City&#93; and clear to the Fish Gate and the Tower of Ha·nanʹel and the Tower of Meʹah and on to the Sheep Gate; and they came to a stand at the Gate of the Guard.

[[v16-12-40]]

^<<v16-12-40,40>>^ At length the two thanksgiving choirs came to a stand at the house of the &#91;true&#93; God, also I and half of the deputy rulers with me,

[[v16-12-41]]

^<<v16-12-41,41>>^ and the priests E·liʹa·kim, Ma·a·seiʹah, Mi·niʹa·min,^&#42;1^ Mi·caiʹah, Eli·o·eʹnai, Zech·a·riʹah, Han·a·niʹah with the trumpets,

[NOTE]
====
. “Mijamin” in 10:7.
====

[[v16-12-42]]

^<<v16-12-42,42>>^ and Ma·a·seiʹah and She·maiʹah, and El·e·aʹzar and Uzʹzi and Je·ho·haʹnan and Mal·chiʹjah and Eʹlam and Eʹzer. And the singers with Iz·ra·hiʹah the overseer kept making themselves heard.

[[v16-12-43]]

^<<v16-12-43,43>>^ And they proceeded to sacrifice on that day great sacrifices and to rejoice, for the &#91;true&#93; God himself caused them to rejoice with great joy. And also the women and the children themselves rejoiced, so that the rejoicing of Jerusalem could be heard far away.

[[v16-12-44]]

^<<v16-12-44,44>>^ Further, there were appointed on that day men over the halls for the stores, for the contributions, for the firstfruits and for the tenths,^&#42;1^ to gather into them out of^&#42;2^ the fields of the cities the portions &#91;called for by&#93; the law for the priests and the Levites; for the rejoicing of Judah was because of the priests and of the Levites who were in attendance.

[NOTE]
====
. Or, “tithes.”
. Or, “according to.”
====

[[v16-12-45]]

^<<v16-12-45,45>>^ And they began taking care of the obligation of their God and the obligation of the purification, also the singers and the gatekeepers, according to the commandment of David &#91;and&#93; Solʹo·mon his son.

[[v16-12-46]]

^<<v16-12-46,46>>^ For in the days of David and Aʹsaph in bygone time there were heads of the singers and the song of praise and thanksgivings to God.

[[v16-12-47]]

^<<v16-12-47,47>>^ And all Israel during the days of Ze·rubʹba·bel and during the days of Ne·he·miʹah were giving the portions of the singers and of the gatekeepers according to the daily need^&#42;1^ and were sanctifying &#91;them&#93; to the Levites; and the Levites were sanctifying &#91;them&#93; to the sons of Aaron.

[NOTE]
====
. Lit., “a thing of a day on its day.”
====

'''

xref:016-nehemiah/016-nehemiah-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-nehemiah/016-nehemiah-013.adoc#v16-13-0[Próximo Capítulo &#62;]