include::./index.adoc[]

[[v60-2-0]]
=== The First of Peter, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v60-2-1]]

^<<v60-2-1,1>>^ Accordingly, put away all badness and all deceitfulness and hypocrisy and envies and all sorts of backbiting,

[[v60-2-2]]

^<<v60-2-2,2>>^ &#91;and,&#93; as newborn infants, form a longing for the unadulterated milk belonging to the word, that through it YOU may grow to salvation,

[[v60-2-3]]

^<<v60-2-3,3>>^ provided YOU have tasted that the Lord^&#42;1^ is kind.

[NOTE]
====
. “The Lord.” Gr., ho Kyʹri·os. In a comment on this vs F. J. A. Hort wrote in The First Epistle of St Peter, London, 1898, p. 104: “In the Psalm [34:8] ὁ κύριος stands for Jehovah, as it very often does, the LXX. inserting and omitting the article with κύριος on no apparent principle. On the other hand the next verse shews St Peter to have used ὁ κύριος in its commonest though not universal N.T. sense, of Christ. It would be rash however to conclude that he meant to identify Jehovah with Christ. No such identification can be clearly made out in the N.T.  St Peter is not here making a formal quotation, but merely borrowing O.T. language, and applying it in his own manner. His use, though different from that of the Psalm, is not at variance with it, for it is through the χρηστότης [khre·stoʹtes, “kindness”] of the Son that the χρηστότης of the Father is clearly made known to Christians: ‘he that hath seen me hath seen the Father.’ ” See App 6F.
====

[[v60-2-4]]

^<<v60-2-4,4>>^ Coming to him as to a living stone, rejected, it is true, by men, but chosen, precious, with God,

[[v60-2-5]]

^<<v60-2-5,5>>^ YOU yourselves also as living stones are being built up a spiritual house for the purpose of a holy priesthood, to offer up spiritual sacrifices acceptable to God through Jesus Christ.

[[v60-2-6]]

^<<v60-2-6,6>>^ For it is contained in Scripture: “Look! I am laying in Zion a stone, chosen, a foundation cornerstone, precious; and no one exercising faith in it will by any means come to disappointment.”^&#42;1^

[NOTE]
====
. Or, “by no means be ashamed.”
====

[[v60-2-7]]

^<<v60-2-7,7>>^ It is to YOU, therefore, that he is precious,^&#42;1^ because YOU are believers; but to those not believing, “the identical stone that the builders rejected has become &#91;the&#93; head of &#91;the&#93; corner,”

[NOTE]
====
. Or, “It is you, therefore, that have the precious estimation.”
====

[[v60-2-8]]

^<<v60-2-8,8>>^ and “a stone of stumbling and a rock-mass of offense.” These are stumbling because they are disobedient to the word.^&#42;1^ To this very end they were also appointed.

[NOTE]
====
. Or, “stumbling at the word because they are unbelievingly disobedient.”
====

[[v60-2-9]]

^<<v60-2-9,9>>^ But YOU are “a chosen race,^&#42;1^ a royal priesthood, a holy nation, a people for special possession, that YOU should declare abroad the excellencies”^&#42;2^ of the one that called YOU out of darkness into his wonderful light.

[NOTE]
====
. “Race.” Gr., geʹnos; different from ge·ne·aʹ, “generation,” as in Mt 24:34.
. Lit., “virtues.”
====

[[v60-2-10]]

^<<v60-2-10,10>>^ For YOU were once not a people, but are now God’s people; YOU were those who had not been shown mercy, but are now those who have been shown mercy.

[[v60-2-11]]

^<<v60-2-11,11>>^ Beloved, I exhort YOU as aliens and temporary residents to keep abstaining from fleshly desires, which are the very ones that carry on a conflict against the soul.^&#42;1^

[NOTE]
====
. Or, “against the life.” Gr., ka·taʹ tes psy·khesʹ; Lat., ad·verʹsus aʹni·mam; J17,​18(Heb.), ban·naʹphesh.
====

[[v60-2-12]]

^<<v60-2-12,12>>^ Maintain YOUR conduct fine among the nations, that, in the thing in which they are speaking against YOU as evildoers, they may as a result of YOUR fine works of which they are eyewitnesses glorify God in the day for &#91;his&#93; inspection.

[[v60-2-13]]

^<<v60-2-13,13>>^ For the Lord’s^&#42;1^ sake subject yourselves to every human creation: whether to a king as being superior

[NOTE]
====
. “The Lord’s,” אAB; VgcSyp, “God’s”; J7,​8, “Jehovah’s.”
====

[[v60-2-14]]

^<<v60-2-14,14>>^ or to governors as being sent by him to inflict punishment on evildoers but to praise doers of good.

[[v60-2-15]]

^<<v60-2-15,15>>^ For so the will of God is, that by doing good YOU may muzzle the ignorant talk of the unreasonable^&#42;1^ men.

[NOTE]
====
. Lit., “senseless.”
====

[[v60-2-16]]

^<<v60-2-16,16>>^ Be as free people, and yet holding YOUR freedom, not as a blind for badness, but as slaves of God.

[[v60-2-17]]

^<<v60-2-17,17>>^ Honor &#91;men&#93; of all sorts, have love for the whole association of brothers,^&#42;1^ be in fear of God, have honor for the king.

[NOTE]
====
. “Whole association of brothers.” Lit., “brotherhood.”
====

[[v60-2-18]]

^<<v60-2-18,18>>^ Let house servants be in subjection to &#91;their&#93; owners with all &#91;due&#93; fear, not only to the good and reasonable, but also to those hard to please.

[[v60-2-19]]

^<<v60-2-19,19>>^ For if someone, because of conscience toward God, bears up under grievous things and suffers unjustly, this is an agreeable thing.

[[v60-2-20]]

^<<v60-2-20,20>>^ For what merit is there in it if, when YOU are sinning and being slapped,^&#42;1^ YOU endure it? But if, when YOU are doing good and YOU suffer, YOU endure it, this is a thing agreeable with God.

[NOTE]
====
. Lit., “being hit with fist.”
====

[[v60-2-21]]

^<<v60-2-21,21>>^ In fact, to this &#91;course&#93; YOU were called, because even Christ suffered for YOU, leaving YOU a model^&#42;1^ for YOU to follow his steps closely.

[NOTE]
====
. Or, “copy.” Lit., “underwriting.” Gr., hy·po·gram·monʹ; Lat., ex·emʹplum.
====

[[v60-2-22]]

^<<v60-2-22,22>>^ He committed no sin, nor was deception found in his mouth.

[[v60-2-23]]

^<<v60-2-23,23>>^ When he was being reviled, he did not go reviling in return. When he was suffering, he did not go threatening, but kept on committing himself to the one who judges righteously.

[[v60-2-24]]

^<<v60-2-24,24>>^ He himself bore^&#42;1^ our sins in his own body upon the stake,^&#42;2^ in order that we might be done with sins and live to righteousness. And “by his stripes YOU were healed.”

[NOTE]
====
. Or, “He himself bore up.”
. Or, “tree.” Lit., “wood.” Gr., xyʹlon. See App 5C.
====

[[v60-2-25]]

^<<v60-2-25,25>>^ For YOU were like sheep, going astray; but now YOU have returned to the shepherd and overseer^&#42;1^ of YOUR souls.^&#42;2^

[NOTE]
====
. “Overseer.” Gr., e·piʹsko·pon; J17(Heb.), peqidhʹ.
. Or, “lives.”
====

'''

xref:060-1-peter/060-1-peter-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-peter/060-1-peter-003.adoc#v60-3-0[Próximo Capítulo &#62;]