include::./index.adoc[]

[[v60-3-0]]
=== The First of Peter, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v60-3-1]]

^<<v60-3-1,1>>^ In like manner, YOU wives, be in subjection to YOUR own husbands, in order that, if any are not obedient to the word, they may be won^&#42;1^ without a word^&#42;2^ through the conduct of &#91;their&#93; wives,

[NOTE]
====
. “They may be won,” אABVg; Syp, “you may win them”; J18, “you may win them to Jehovah.”
. Or, “the word.”
====

[[v60-3-2]]

^<<v60-3-2,2>>^ because of having been eyewitnesses of YOUR chaste conduct together with deep respect.

[[v60-3-3]]

^<<v60-3-3,3>>^ And do not let YOUR adornment be that of the external braiding of the hair and of the putting on of gold ornaments or the wearing of outer garments,

[[v60-3-4]]

^<<v60-3-4,4>>^ but let it be the secret person^&#42;1^ of the heart in the incorruptible &#91;apparel&#93; of the quiet and mild spirit, which is of great value in the eyes of God.

[NOTE]
====
. Or, “the secret man.” Lit., “the hidden man.”
====

[[v60-3-5]]

^<<v60-3-5,5>>^ For so, too, formerly the holy women^&#42;1^ who were hoping in God used to adorn themselves, subjecting themselves to their own husbands,

[NOTE]
====
. Or, “wives.”
====

[[v60-3-6]]

^<<v60-3-6,6>>^ as Sarah used to obey Abraham, calling him “lord.” And YOU have become her children, provided YOU keep on doing good and not fearing any cause for terror.

[[v60-3-7]]

^<<v60-3-7,7>>^ YOU husbands, continue dwelling in like manner with them according to knowledge, assigning them honor as to a weaker vessel, the feminine one, since YOU are also heirs with them of the undeserved favor of life, in order for YOUR prayers not to be hindered.

[[v60-3-8]]

^<<v60-3-8,8>>^ Finally, all of YOU be like-minded, showing fellow feeling,^&#42;1^ having brotherly affection, tenderly compassionate, humble in mind,

[NOTE]
====
. “Showing fellow feeling.” Lit., “sympathetic.” Gr., sym·pa·theisʹ.
====

[[v60-3-9]]

^<<v60-3-9,9>>^ not paying back injury for injury or reviling for reviling, but, to the contrary, bestowing a blessing, because YOU were called to this &#91;course&#93;, so that YOU might inherit a blessing.

[[v60-3-10]]

^<<v60-3-10,10>>^ For, “he that would love life and see good days, let him restrain his tongue from what is bad and &#91;his&#93; lips from speaking deception,

[[v60-3-11]]

^<<v60-3-11,11>>^ but let him turn away from what is bad and do what is good; let him seek peace and pursue it.

[[v60-3-12]]

^<<v60-3-12,12>>^ For &#91;the&#93; eyes of Jehovah^&#42;1^ are upon the righteous ones, and his ears are toward their supplication; but &#91;the&#93; face of Jehovah^&#42;2^ is against those doing bad things.”

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v60-3-13]]

^<<v60-3-13,13>>^ Indeed, who is the man that will harm YOU if YOU become zealous for what is good?

[[v60-3-14]]

^<<v60-3-14,14>>^ But even if YOU should suffer for the sake of righteousness, YOU are happy. However, the object of their fear do not YOU fear, neither become agitated.

[[v60-3-15]]

^<<v60-3-15,15>>^ But sanctify the Christ as Lord^&#42;1^ in YOUR hearts, always ready to make a defense before everyone that demands of YOU a reason for the hope in YOU, but doing so together with a mild temper and deep respect.^&#42;2^

[NOTE]
====
. “The Christ as Lord,” אABC; TR, “the Lord God”; J7,​8,​11-14,​16,​17,​24, “Jehovah God.”
. Lit., “fear.”
====

[[v60-3-16]]

^<<v60-3-16,16>>^ Hold a good conscience, so that in the particular in which YOU are spoken against they may get ashamed who are speaking slightingly of YOUR good conduct in connection with Christ.

[[v60-3-17]]

^<<v60-3-17,17>>^ For it is better to suffer because YOU are doing good, if the will of God wishes it, than because YOU are doing evil.

[[v60-3-18]]

^<<v60-3-18,18>>^ Why, even Christ died once for all time concerning sins, a righteous &#91;person&#93; for unrighteous ones, that he might lead YOU to God, he being put to death in the flesh, but being made alive in the spirit.

[[v60-3-19]]

^<<v60-3-19,19>>^ In this &#91;state&#93; also he went his way and preached^&#42;1^ to the spirits in prison,

[NOTE]
====
. Or, “heralded.” Gr., e·keʹry·xen; Lat., prae·di·caʹvit. Compare Da 5:29 ftn, “Heralded.”
====

[[v60-3-20]]

^<<v60-3-20,20>>^ who had once been disobedient when the patience of God was waiting in Noah’s days, while the ark was being constructed, in which a few people, that is, eight souls, were carried safely through the water.

[[v60-3-21]]

^<<v60-3-21,21>>^ That which corresponds to this^&#42;1^ is also now saving YOU, namely, baptism, (not the putting away of the filth of the flesh, but the request made to God for a good conscience,) through the resurrection of Jesus Christ.

[NOTE]
====
. Lit., “Which thing as an antitype.” Gr., ho . . . an·tiʹty·pon.
====

[[v60-3-22]]

^<<v60-3-22,22>>^ He is at God’s right hand, for he went his way to heaven; and angels and authorities and powers were made subject to him.

'''

xref:060-1-peter/060-1-peter-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-peter/060-1-peter-004.adoc#v60-4-0[Próximo Capítulo &#62;]