include::./index.adoc[]

[[v60-5-0]]
=== The First of Peter, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v60-5-1]]

^<<v60-5-1,1>>^ Therefore, to the older men^&#42;1^ among YOU I give this exhortation, for I too am an older man with &#91;them&#93;^&#42;2^ and a witness of the sufferings of the Christ, a sharer even of the glory that is to be revealed:

[NOTE]
====
. Or, “elders.” Gr., pre·sby·teʹrous.
. “Older man with [them].” Lit., “fellow elder.” Gr., syn·pre·sbyʹte·ros.
====

[[v60-5-2]]

^<<v60-5-2,2>>^ Shepherd the flock of God in YOUR care, not under compulsion,^&#42;1^ but willingly;^&#42;2^ neither for love of dishonest gain, but eagerly;

[NOTE]
====
. Lit., “not necessarily.”
. Lit., “yieldingly.”
====

[[v60-5-3]]

^<<v60-5-3,3>>^ neither as lording it over those who are God’s^&#42;1^ inheritance,^&#42;2^ but becoming examples to the flock.

[NOTE]
====
. Lit., “the.” J13,​14,​17,​18, “Jehovah’s.”
. Or, “lording it over those allotted to you.”
====

[[v60-5-4]]

^<<v60-5-4,4>>^ And when the chief shepherd has been made manifest, YOU will receive^&#42;1^ the unfadable crown of glory.

[NOTE]
====
. Or, “carry away as a prize.”
====

[[v60-5-5]]

^<<v60-5-5,5>>^ In like manner, YOU younger men, be in subjection to the older men. But all of YOU gird yourselves with lowliness of mind toward one another, because God opposes the haughty ones, but he gives undeserved kindness to the humble ones.

[[v60-5-6]]

^<<v60-5-6,6>>^ Humble yourselves, therefore, under the mighty hand of God, that he may exalt YOU in due time;

[[v60-5-7]]

^<<v60-5-7,7>>^ while YOU throw all YOUR anxiety upon him, because he cares for YOU.

[[v60-5-8]]

^<<v60-5-8,8>>^ Keep YOUR senses, be watchful. YOUR adversary, the Devil, walks about like a roaring lion, seeking to devour^&#42;1^ &#91;someone&#93;.

[NOTE]
====
. Lit., “to drink down.”
====

[[v60-5-9]]

^<<v60-5-9,9>>^ But take YOUR stand against him, solid in the faith, knowing that the same things in the way of sufferings are being accomplished in the entire association of YOUR brothers^&#42;1^ in the world.

[NOTE]
====
. “Entire association of . . . brothers.” Lit., “brotherhood.” Gr., a·del·phoʹte·ti.
====

[[v60-5-10]]

^<<v60-5-10,10>>^ But, after YOU have suffered a little while, the God of all undeserved kindness, who called YOU to his everlasting glory in union with Christ, will himself finish YOUR training, he will make YOU firm, he will make YOU strong.

[[v60-5-11]]

^<<v60-5-11,11>>^ To him be the might forever. Amen.

[[v60-5-12]]

^<<v60-5-12,12>>^ Through Sil·vaʹnus,^&#42;1^ a faithful brother, as I account him, I have written YOU in few &#91;words&#93;, to give encouragement and an earnest witness that this is the true undeserved kindness of God; in which stand firm.

[NOTE]
====
. Or, “Silas.”
====

[[v60-5-13]]

^<<v60-5-13,13>>^ She who is in Babylon,^&#42;1^ a chosen one like &#91;YOU&#93;, sends YOU her greetings, and so does Mark my son.

[NOTE]
====
. “Babylon.” Gr., Ba·by·loʹni; J17,​22(Heb.), ­beVa·velʹ, “in Babylon.”
====

[[v60-5-14]]

^<<v60-5-14,14>>^ Greet one another with a kiss of love.
May all of YOU who are in union with Christ have peace.

'''

xref:060-1-peter/060-1-peter-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-peter/061-2-peter-001.adoc#v61-1-0[Próximo Capítulo &#62;]