include::./index.adoc[]

[[v60-1-0]]
=== The First of Peter, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v60-1-1]]

^<<v60-1-1,1>>^ Peter,^&#42;1^ an apostle of Jesus Christ, to the temporary residents scattered about^&#42;2^ in Ponʹtus, Ga·laʹti·a, Cap·pa·doʹci·a, Asia, and Bi·thynʹi·a, to the ones chosen

[NOTE]
====
. “Peter.” Gr., Peʹtros, meaning “A Piece of Rock.”
. Lit., “alien residents of dispersion.” See Jas 1:1.
====

[[v60-1-2]]

^<<v60-1-2,2>>^ according to the foreknowledge of God the Father, with sanctification by the spirit, for the purpose of their being obedient and sprinkled with the blood of Jesus Christ:
May undeserved kindness and peace be increased to YOU.

[[v60-1-3]]

^<<v60-1-3,3>>^ Blessed be the God and Father of our Lord Jesus Christ, for according to his great mercy he gave us a new birth^&#42;1^ to a living hope through the resurrection of Jesus Christ from the dead,

[NOTE]
====
. Lit., “having generated again us.” Gr., a·na·gen·neʹsas he·masʹ; Lat., re·ge·ne·raʹvit nos.
====

[[v60-1-4]]

^<<v60-1-4,4>>^ to an incorruptible and undefiled and unfading inheritance. It is reserved^&#42;1^ in the heavens for YOU,

[NOTE]
====
. Lit., “Having been kept.”
====

[[v60-1-5]]

^<<v60-1-5,5>>^ who are being safeguarded^&#42;1^ by God’s power through faith for a salvation ready to be revealed in the last period of time.

[NOTE]
====
. Lit., “being kept under watch.”
====

[[v60-1-6]]

^<<v60-1-6,6>>^ In this fact YOU are greatly rejoicing, though for a little while at present, if it must be, YOU have been grieved by various trials,

[[v60-1-7]]

^<<v60-1-7,7>>^ in order that the tested quality^&#42;1^ of YOUR faith, of much greater value than gold that perishes despite its being proved by fire, may be found a cause for praise and glory and honor at the revelation^&#42;2^ of Jesus Christ.

[NOTE]
====
. Or, “the testing.” Lit., “the proof.”
. Lit., “uncovering; disclosure.” Gr., a·po·ka·lyʹpsei; Lat., re·ve·la·ti·oʹne.
====

[[v60-1-8]]

^<<v60-1-8,8>>^ Though YOU never saw him, YOU love him. Though YOU are not looking upon him at present, yet YOU exercise faith in him and are greatly rejoicing with an unspeakable and glorified joy,

[[v60-1-9]]

^<<v60-1-9,9>>^ as YOU receive^&#42;1^ the end^&#42;2^ of YOUR faith, the salvation of YOUR souls.

[NOTE]
====
. Or, “carry away as a prize.”
. Or, “completed end; accomplished end.” Gr., teʹlos.
====

[[v60-1-10]]

^<<v60-1-10,10>>^ Concerning this very salvation a diligent inquiry and a careful search were made by the prophets who prophesied about the undeserved kindness meant for YOU.

[[v60-1-11]]

^<<v60-1-11,11>>^ They kept on investigating^&#42;1^ what particular season or what sort of &#91;season&#93; the spirit in them was indicating concerning Christ^&#42;2^ when it was bearing witness beforehand about the sufferings for Christ and about the glories to follow these.

[NOTE]
====
. Lit., “searching.”
. Or, “the spirit of Christ which was in them indicated.”
====

[[v60-1-12]]

^<<v60-1-12,12>>^ It was revealed to them that, not to themselves, but to YOU, they were ministering the things that have now been announced to YOU through those who have declared the good news to YOU with holy spirit sent forth from heaven. Into these very things angels are desiring to peer.^&#42;1^

[NOTE]
====
. Lit., “to stoop beside.”
====

[[v60-1-13]]

^<<v60-1-13,13>>^ Hence brace up YOUR minds for activity,^&#42;1^ keep YOUR senses completely; set YOUR hope^&#42;2^ upon the undeserved kindness that is to be brought to YOU at the revelation of Jesus Christ.

[NOTE]
====
. Lit., “gird up the loins of your mind (mental perception).”
. Or, “keep balanced and set your hope completely.”
====

[[v60-1-14]]

^<<v60-1-14,14>>^ As obedient children,^&#42;1^ quit being fashioned according to the desires YOU formerly had in YOUR ignorance,

[NOTE]
====
. Or, “persons.”
====

[[v60-1-15]]

^<<v60-1-15,15>>^ but, in accord with the Holy One who called YOU, do YOU also become holy yourselves in all &#91;YOUR&#93; conduct,

[[v60-1-16]]

^<<v60-1-16,16>>^ because it is written: “YOU must be holy, because I am holy.”

[[v60-1-17]]

^<<v60-1-17,17>>^ Furthermore, if YOU are calling upon the Father who judges impartially^&#42;1^ according to each one’s work, conduct yourselves with fear during the time of YOUR alien residence.

[NOTE]
====
. Lit., “without reception of faces.”
====

[[v60-1-18]]

^<<v60-1-18,18>>^ For YOU know that it was not with corruptible things, with silver or gold, that YOU were delivered^&#42;1^ from YOUR fruitless form of conduct received by tradition from YOUR forefathers.

[NOTE]
====
. Lit., “you were freed by ransom.”
====

[[v60-1-19]]

^<<v60-1-19,19>>^ But it was with precious blood, like that of an unblemished and spotless lamb, even Christ’s.

[[v60-1-20]]

^<<v60-1-20,20>>^ True, he was foreknown before the founding^&#42;1^ of the world, but he was made manifest at the end of the times for the sake of YOU

[NOTE]
====
. Lit., “throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v60-1-21]]

^<<v60-1-21,21>>^ who through him are believers in God, the one who raised him up from the dead and gave him glory; so that YOUR faith and hope might be in God.

[[v60-1-22]]

^<<v60-1-22,22>>^ Now that YOU have purified YOUR souls^&#42;1^ by &#91;YOUR&#93; obedience to the truth with unhypocritical brotherly affection as the result, love one another intensely^&#42;2^ from the heart.

[NOTE]
====
. Or, “lives.” See App 4A.
. Lit., “outstretchedly.”
====

[[v60-1-23]]

^<<v60-1-23,23>>^ For YOU have been given a new birth, not by corruptible, but by incorruptible &#91;reproductive&#93; seed,^&#42;1^ through the word of &#91;the&#93; living and enduring God.

[NOTE]
====
. “Seed.” Gr., spo·rasʹ; Lat., seʹmi·ne.
====

[[v60-1-24]]

^<<v60-1-24,24>>^ For “all flesh is like grass, and all its glory is like a blossom of grass; the grass becomes withered, and the flower falls off,

[[v60-1-25]]

^<<v60-1-25,25>>^ but the saying of Jehovah^&#42;1^ endures forever.” Well, this is the “saying,” this which has been declared to YOU as good news.

[NOTE]
====
. “Of Jehovah,” J7,​8,​13,​14,​16-18,​20,​22,​23; אAB(Gr.), Ky·riʹou; Syp, “of our God.” See App 1D.
====

'''

xref:059-james/059-james-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-peter/060-1-peter-002.adoc#v60-2-0[Próximo Capítulo &#62;]