include::./index.adoc[]

[[v60-4-0]]
=== The First of Peter, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v60-4-1]]

^<<v60-4-1,1>>^ Therefore since Christ suffered in the flesh, YOU too arm yourselves with the same mental disposition;^&#42;1^ because the person that has suffered in the flesh has desisted from sins,

[NOTE]
====
. Lit., “mental inclination.”
====

[[v60-4-2]]

^<<v60-4-2,2>>^ to the end that he may live the remainder of &#91;his&#93; time in the flesh, no more for the desires of men, but for God’s will.

[[v60-4-3]]

^<<v60-4-3,3>>^ For the time that has passed by is sufficient for YOU to have worked out the will of the nations when YOU proceeded in deeds of loose conduct,^&#42;1^ lusts, excesses with wine, revelries, drinking matches, and illegal idolatries.

[NOTE]
====
. “Deeds of loose conduct.” Gr., a·sel·geiʹais; J17,​18,​22(Heb.), zim·mahʹ. See Ga 5:19 ftn, “Conduct.” Compare Le 18:17 ftn.
====

[[v60-4-4]]

^<<v60-4-4,4>>^ Because YOU do not continue running with them in this course to the same low sink of debauchery, they are puzzled and go on speaking abusively of YOU.

[[v60-4-5]]

^<<v60-4-5,5>>^ But these people will render an account to the one ready to judge those living and those dead.

[[v60-4-6]]

^<<v60-4-6,6>>^ In fact, for this purpose the good news was declared also to the dead, that they might be judged as to the flesh from the standpoint of men but might live as to the spirit from the standpoint of God.

[[v60-4-7]]

^<<v60-4-7,7>>^ But the end^&#42;1^ of all things has drawn close. Be sound in mind, therefore, and be vigilant^&#42;2^ with a view to prayers.

[NOTE]
====
. Or, “complete end.” Gr., teʹlos.
. Lit., “be you sober.”
====

[[v60-4-8]]

^<<v60-4-8,8>>^ Above all things, have intense^&#42;1^ love for one another, because love covers a multitude of sins.

[NOTE]
====
. Lit., “outstretching.”
====

[[v60-4-9]]

^<<v60-4-9,9>>^ Be hospitable to one another without grumbling.

[[v60-4-10]]

^<<v60-4-10,10>>^ In proportion as each one has received a gift, use it in ministering to one another as fine stewards^&#42;1^ of God’s undeserved kindness expressed in various ways.

[NOTE]
====
. Or, “house managers.” Lit., “house administrators.” Gr., oi·ko·noʹmoi; Lat., di·spen·sa·toʹres; J22(Heb.), kesoh·khenimʹ, “as stewards.”
====

[[v60-4-11]]

^<<v60-4-11,11>>^ If anyone speaks, &#91;let him speak&#93; as it were &#91;the&#93; sacred pronouncements of God; if anyone ministers, &#91;let him minister&#93; as dependent on the strength that God supplies; so that in all things God may be glorified through Jesus Christ. The glory and the might are his forever and ever. Amen.

[[v60-4-12]]

^<<v60-4-12,12>>^ Beloved ones, do not be puzzled at the burning among YOU, which is happening to YOU for a trial, as though a strange thing were befalling YOU.

[[v60-4-13]]

^<<v60-4-13,13>>^ On the contrary, go on rejoicing forasmuch as YOU are sharers in the sufferings of the Christ, that YOU may rejoice and be overjoyed also during the revelation^&#42;1^ of his glory.

[NOTE]
====
. Lit., “uncovering; disclosure.” Gr., a·po·ka·lyʹpsei.
====

[[v60-4-14]]

^<<v60-4-14,14>>^ If YOU are being reproached for the name of Christ, YOU are happy, because the &#91;spirit&#93; of glory, even the spirit of God, is resting upon YOU.

[[v60-4-15]]

^<<v60-4-15,15>>^ However, let none of YOU suffer as a murderer or a thief or an evildoer or as a busybody in other people’s matters.

[[v60-4-16]]

^<<v60-4-16,16>>^ But if &#91;he suffers&#93; as a Christian,^&#42;1^ let him not feel shame, but let him keep on glorifying God in this name.

[NOTE]
====
. “As a Christian.” Gr., hos Khri·sti·a·nosʹ; Lat., ut Chri·sti·aʹnus; J22(Heb.), ­kiM·shi·chiʹ, “as a Messianist.”
====

[[v60-4-17]]

^<<v60-4-17,17>>^ For it is the appointed time for the judgment to start with the house of God. Now if it starts first with us, what will the end be of those who are not obedient to the good news of God?

[[v60-4-18]]

^<<v60-4-18,18>>^ “And if the righteous &#91;man&#93; is being saved with difficulty, where will the ungodly &#91;man&#93; and the sinner make a showing?”

[[v60-4-19]]

^<<v60-4-19,19>>^ So, then, also let those who are suffering in harmony with the will of God keep on commending their souls to a faithful Creator while they are doing good.^&#42;1^

[NOTE]
====
. Or, “to a faithful Creator in well-doing.”
====

'''

xref:060-1-peter/060-1-peter-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-peter/060-1-peter-005.adoc#v60-5-0[Próximo Capítulo &#62;]