include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v29-2-1]]

^<<v29-2-1,1>>^ “Blow a horn^&#42;1^ in Zion, O men, and shout a war cry in my holy mountain. Let all the inhabitants of the land^&#42;2^ get agitated; for the day of Jehovah is coming, for it is near!

[NOTE]
====
. Or, “shofar.” Heb., shoh·pharʹ.
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v29-2-2]]

^<<v29-2-2,2>>^ It is a day of darkness and gloominess, a day of clouds and thick gloom, like light of dawn spread out upon the mountains.
“There is a people numerous and mighty; one like it has not been made to exist from the indefinite past, and after it there will be none again to the years of generation after generation.

[[v29-2-3]]

^<<v29-2-3,3>>^ Ahead of it a fire has devoured, and behind it a flame consumes. Like the garden of Eʹden^&#42;1^ the land is ahead of it; but behind it is a desolate wilderness, and there has also proved to be nothing thereof escaping.

[NOTE]
====
. “Like the garden of Eden.” Heb., keghan-ʽEʹdhen; Gr., hos pa·raʹdei·sos try·phesʹ, “Like a paradise of delight”; Syr., ʼaikh par·dai·saʼ daʽ·den; Lat., quaʹsi horʹtus vo·lu·ptaʹtis, “Like a garden of pleasure.”
====

[[v29-2-4]]

^<<v29-2-4,4>>^ “Its appearance is like the appearance of horses, and like steeds is the way they keep running.

[[v29-2-5]]

^<<v29-2-5,5>>^ As with the sound of chariots on the tops of the mountains they keep skipping about, as with the sound of a flaming fire that is devouring stubble. It is like a mighty people, drawn up in battle order.

[[v29-2-6]]

^<<v29-2-6,6>>^ Because of it, peoples will be in severe pains. As for all faces, they will certainly collect a glow &#91;of excitement&#93;.

[[v29-2-7]]

^<<v29-2-7,7>>^ “Like powerful men^&#42;1^ they run. Like men of war they go up a wall. And they go each one in his own ways, and they do not alter their paths.

[NOTE]
====
. Or, “Like mighty men.” Heb., keghib·boh·rimʹ.
====

[[v29-2-8]]

^<<v29-2-8,8>>^ And one another they do not shove. As an able-bodied man^&#42;1^ in his course, they keep going; and should some fall even among the missiles, the &#91;others&#93; do not break off course.

[NOTE]
====
. “An able-bodied man.” Heb., geʹver.
====

[[v29-2-9]]

^<<v29-2-9,9>>^ “Into the city they rush. On the wall they run. On the houses they go up. Through the windows they go in like the thief.

[[v29-2-10]]

^<<v29-2-10,10>>^ Before it &#91;the&#93; land has become agitated, &#91;the&#93; heavens have rocked. Sun and moon themselves have become dark, and the very stars have withdrawn their brightness.

[[v29-2-11]]

^<<v29-2-11,11>>^ And Jehovah himself will certainly give forth his voice before his military force, for his camp is very numerous. For he who is carrying out his word is mighty; for the day of Jehovah is great and very fear-inspiring, and who can hold up under it?”

[[v29-2-12]]

^<<v29-2-12,12>>^ “And now also,” the utterance of Jehovah is, “come back to me with all YOUR hearts, and with fasting and with weeping and with wailing.

[[v29-2-13]]

^<<v29-2-13,13>>^ And rip apart YOUR hearts, and not YOUR garments; and come back to Jehovah YOUR God, for he is gracious and merciful, slow to anger and abundant in loving-kindness,^&#42;1^ and he will certainly feel regret on account of the calamity.

[NOTE]
====
. Or, “loyal love.” Heb., cheʹsedh.
====

[[v29-2-14]]

^<<v29-2-14,14>>^ Who is there knowing whether he will turn back and actually feel regret and let remain after it a blessing, a grain offering and a drink offering for Jehovah YOUR God?

[[v29-2-15]]

^<<v29-2-15,15>>^ “Blow a horn in Zion, O men. Sanctify a time of fasting. Call together a solemn assembly.

[[v29-2-16]]

^<<v29-2-16,16>>^ Gather &#91;the&#93; people together. Sanctify^&#42;1^ a congregation. Collect &#91;the&#93; old men together. Gather children and those sucking the breasts together. Let &#91;the&#93; bridegroom go forth from his interior room, and &#91;the&#93; bride from her nuptial chamber.

[NOTE]
====
. Or, “Hold sacred; Treat as holy.” Heb., qad·deshuʹ; Gr., ha·gi·aʹsa·te; Lat., sanc·ti·fi·caʹte.
====

[[v29-2-17]]

^<<v29-2-17,17>>^ “Between the porch and the altar let the priests, the ministers of Jehovah, weep and say, ‘Do feel sorry, O Jehovah, for your people, and do not make your inheritance a reproach, for nations to rule over them. Why should they say among the peoples: “Where is their God?”’

[[v29-2-18]]

^<<v29-2-18,18>>^ And Jehovah will be zealous for his land and will show compassion upon his people.

[[v29-2-19]]

^<<v29-2-19,19>>^ And Jehovah will answer and say to his people, ‘Here I am sending to YOU the grain and the new wine and the oil, and YOU people will certainly be satisfied with it; and I shall not make YOU anymore a reproach among the nations.

[[v29-2-20]]

^<<v29-2-20,20>>^ And the northerner^&#42;1^ I shall put far away from upon YOU, and I shall actually disperse him to a waterless land and desolated waste, with his face to the eastern sea and his rear section to the western^&#42;2^ sea. And the stink from him will certainly ascend, and the stench from him will keep ascending; for He will actually do a great thing in what He does.’

[NOTE]
====
. Possibly, “chirper,” by a correction.
. Lit., “hinder,” that is, to one’s back when facing east.
====

[[v29-2-21]]

^<<v29-2-21,21>>^ “Do not be fearful, O ground. Be joyful and rejoice; for Jehovah will actually do a great thing in what He does.

[[v29-2-22]]

^<<v29-2-22,22>>^ Do not be fearful, YOU beasts of the open field, for the pasture grounds of &#91;the&#93; wilderness will certainly grow green. For the tree will actually give its fruitage. The fig tree and the vine must give their vital energy.

[[v29-2-23]]

^<<v29-2-23,23>>^ And, YOU sons of Zion, be joyful and rejoice in Jehovah YOUR God;^&#42;1^ for he will be bound to give YOU the autumn rain^&#42;2^ in right measure, and he will bring down upon YOU people a downpour, autumn rain and spring rain, as at the first.

[NOTE]
====
. “Your God.” Heb., ʼElo·heh·khemʹ.
. “Autumn rain,” by a correction; M, “instructor.”
====

[[v29-2-24]]

^<<v29-2-24,24>>^ And the threshing floors must be full of &#91;cleansed&#93; grain, and the press vats must overflow with new wine and oil.

[[v29-2-25]]

^<<v29-2-25,25>>^ And I will make compensation to YOU for the years that the locust, the creeping, unwinged locust, and the cockroach and the caterpillar have eaten, my great military force that I have sent among YOU.

[[v29-2-26]]

^<<v29-2-26,26>>^ And YOU will certainly eat, eating and becoming satisfied, and YOU will be bound to praise the name of Jehovah YOUR God, who has done with YOU so wonderfully; and my people will not be ashamed to time indefinite.

[[v29-2-27]]

^<<v29-2-27,27>>^ And YOU people will have to know that I am in the midst of Israel, and that I am Jehovah YOUR God and there is no other. And my people will not be ashamed to time indefinite.^&#42;1^

[NOTE]
====
. MLXX end chap. 2 here; TLXXBagsterSyVg continue chap. 2 through vs 32 (3:5 of M).
====

[[v29-2-28]]

^<<v29-2-28,28>>^ “And after that it must occur that I shall pour out my spirit^&#42;1^ on every sort of flesh, and YOUR sons and YOUR daughters will certainly prophesy. As for YOUR old men, dreams they will dream. As for YOUR young men, visions they will see.

[NOTE]
====
. “My spirit.” Heb., ru·chiʹ; Gr., pneuʹma·tos; Lat., spiʹri·tum.
====

[[v29-2-29]]

^<<v29-2-29,29>>^ And even on the menservants and on the maidservants in those days I shall pour out my spirit.

[[v29-2-30]]

^<<v29-2-30,30>>^ “And I will give portents in the heavens and on the earth, blood and fire and columns of smoke.

[[v29-2-31]]

^<<v29-2-31,31>>^ The sun itself will be turned into darkness, and the moon into blood, before the coming of the great and fear-inspiring day of Jehovah.

[[v29-2-32]]

^<<v29-2-32,32>>^ And it must occur that everyone who calls on the name of Jehovah will get away safe; for in Mount Zion and in Jerusalem there will prove to be the escaped ones, just as Jehovah has said, and in among the survivors,^&#42;1^ whom Jehovah is calling.”^&#42;2^

[NOTE]
====
. “In among the survivors,” MVg; Gr., eu·ag·ge·li·zoʹme·noi, “those telling good news; those evangelizing.”
. MLXX end chap. 3 here; TLXXBagsterSyVg end chap. 2.
====

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]