include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v29-3-1]]

^<<v29-3-1,1>>^ “For, look! in those days and in that time, when I shall bring back the captive ones of Judah and Jerusalem,

[[v29-3-2]]

^<<v29-3-2,2>>^ I will also collect together all the nations and bring them down to the low plain of Je·hoshʹa·phat; and I will put myself on judgment with them there on account of my people and my inheritance Israel, whom they scattered among the nations; and they apportioned out my own land.

[[v29-3-3]]

^<<v29-3-3,3>>^ And for my people they kept casting lots; and they would give the male child for a prostitute,^&#42;1^ and the female child they sold for wine, that they might drink.

[NOTE]
====
. Lit., “for the prostitute.” Heb., baz·zoh·nahʹ; Gr., porʹnais; Lat., in pro·stiʹbu·lum.
====

[[v29-3-4]]

^<<v29-3-4,4>>^ “And, also, what do YOU have to do with me,^&#42;1^ O Tyre and Siʹdon and all YOU regions of Phi·lisʹti·a? Is it the treatment that YOU are giving me as a reward? And if YOU are giving such treatment to me, swiftly, speedily I shall pay back YOUR treatment upon YOUR heads.

[NOTE]
====
. Lit., “what are you to me?” A Heb. idiom; a repellent question indicating objection to the “treatment.” See App 7B.
====

[[v29-3-5]]

^<<v29-3-5,5>>^ Because YOU men have taken my own silver and my own gold, and YOU have brought my own desirable good things into YOUR temples;

[[v29-3-6]]

^<<v29-3-6,6>>^ and the sons of Judah and the sons of Jerusalem YOU have sold to the sons of the Greeks,^&#42;1^ for the purpose of removing them far from their own territory;

[NOTE]
====
. “The Greeks,” LXXVg; Heb., hai·Yewa·nimʹ, “the Ionians.”
====

[[v29-3-7]]

^<<v29-3-7,7>>^ here I am arousing them &#91;to come&#93; from the place where YOU have sold them, and I will pay back YOUR treatment upon YOUR own heads.

[[v29-3-8]]

^<<v29-3-8,8>>^ And I will sell YOUR sons and YOUR daughters into the hand of the sons of Judah, and they must sell them to the men of Sheʹba, to a nation far away; for Jehovah himself has spoken &#91;it&#93;.

[[v29-3-9]]

^<<v29-3-9,9>>^ “Proclaim this, YOU people, among the nations, ‘Sanctify war! Arouse the powerful men!^&#42;1^ Let them draw near! Let them come up, all the men^&#42;2^ of war!

[NOTE]
====
. See 2:7 ftn.
. “Men of.” Heb., ʼan·shehʹ, pl. of ʼish.
====

[[v29-3-10]]

^<<v29-3-10,10>>^ Beat YOUR plowshares into swords and YOUR pruning shears into lances. As for the weak one, let him say: “I am a powerful man.”

[[v29-3-11]]

^<<v29-3-11,11>>^ Lend YOUR aid and come, all YOU nations round about, and collect yourselves together.’”
To that place, O Jehovah, bring your powerful ones down.

[[v29-3-12]]

^<<v29-3-12,12>>^ “Let the nations be aroused and come up to the low plain of Je·hoshʹa·phat; for there I shall sit in order to judge all the nations round about.

[[v29-3-13]]

^<<v29-3-13,13>>^ “THRUST in a sickle, for harvest has grown ripe. Come, descend, for &#91;the&#93; winepress has become full. The press vats actually overflow; for their badness has become abundant.

[[v29-3-14]]

^<<v29-3-14,14>>^ Crowds, crowds are in the low plain of the decision, for the day of Jehovah is near in the low plain of the decision.

[[v29-3-15]]

^<<v29-3-15,15>>^ Sun and moon themselves will certainly become dark, and the very stars will actually withdraw their brightness.

[[v29-3-16]]

^<<v29-3-16,16>>^ And out of Zion Jehovah himself will roar, and out of Jerusalem he will give forth his voice. And heaven and earth certainly will rock; but Jehovah will be a refuge for his people, and a fortress for the sons of Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ And YOU people will have to know that I am Jehovah YOUR God, residing in Zion my holy mountain. And Jerusalem must become a holy place; and as regards strangers, they will no more pass through her.

[[v29-3-18]]

^<<v29-3-18,18>>^ “And it must occur in that day that the mountains will drip with sweet wine,^&#42;1^ and the very hills will flow^&#42;2^ with milk, and the very streambeds of Judah will all flow with water. And out of the house of Jehovah there will go forth a spring, and it must irrigate the torrent valley of the Acacia Trees.^&#42;3^

[NOTE]
====
. Or, “fresh grape juice.”
. Lit., “go.”
. Or, “valley of Shittim.”
====

[[v29-3-19]]

^<<v29-3-19,19>>^ As regards Egypt, a desolate waste it will become; and as regards Eʹdom, a wilderness of desolate waste it will become, because of the violence to the sons of Judah, in whose land they shed innocent blood.

[[v29-3-20]]

^<<v29-3-20,20>>^ But as for Judah, to time indefinite it will be inhabited, and Jerusalem to generation after generation.

[[v29-3-21]]

^<<v29-3-21,21>>^ And I will consider innocent their blood^&#42;1^ that I had not considered innocent;^&#42;2^ and Jehovah will be residing in Zion.”

[NOTE]
====
. That is, death by bloodshed.
. “And I will avenge their blood and by no means consider [them] innocent,” LXX; Vg, “And I will cleanse their blood that I had not cleansed.”
====

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]