include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v29-1-1]]

^<<v29-1-1,1>>^ The word of Jehovah that occurred to Joel the son of Pe·thuʹel:

[[v29-1-2]]

^<<v29-1-2,2>>^ “Hear this, YOU older men,^&#42;1^ and give ear, all YOU inhabitants of the land.^&#42;2^ Has this occurred in YOUR days, or even in the days of YOUR forefathers?

[NOTE]
====
. Or, “you elders.” Heb., haz·zeqe·nimʹ; Gr., pre·sbyʹte·roi. See Ac 15:2 ftn.
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v29-1-3]]

^<<v29-1-3,3>>^ Concerning it give an account to YOUR own sons, and YOUR sons to their sons, and their sons to the following generation.

[[v29-1-4]]

^<<v29-1-4,4>>^ What was left by the caterpillar, the locust has eaten; and what was left by the locust, the creeping, unwinged locust^&#42;1^ has eaten; and what the creeping, unwinged locust has left, the cockroach has eaten.

[NOTE]
====
. “The creeping, unwinged locust.” Heb., hai·yaʹleq. See Ps 105:34 ftn.
====

[[v29-1-5]]

^<<v29-1-5,5>>^ “Wake up, YOU drunkards, and weep; and howl, all YOU wine drinkers, on account of sweet wine, for it has been cut off from YOUR mouths.

[[v29-1-6]]

^<<v29-1-6,6>>^ For there is a nation that has come up into my land, mighty and without number. Its teeth are the teeth of a lion,^&#42;1^ and it has the jawbones of a lion.^&#42;2^

[NOTE]
====
. “Lion.” Heb., ʼar·yehʹ, the African lion.
. “Lion.” Heb., la·viʼʹ, the Asian lion.
====

[[v29-1-7]]

^<<v29-1-7,7>>^ It has set my vine as an object of astonishment, and my fig tree as a stump. It has positively stripped it bare and thrown &#91;it&#93; away. The twigs of it have become white.

[[v29-1-8]]

^<<v29-1-8,8>>^ Wail,^&#42;1^ as a virgin girded with sackcloth does over the owner^&#42;2^ of her youth.

[NOTE]
====
. “Wail,” imperative, fem. sing.
. “Owner.” Heb., baʹʽal; Gr., anʹdra; Lat., viʹrum, “husband.”
====

[[v29-1-9]]

^<<v29-1-9,9>>^ “Grain offering and drink offering have been cut off from the house of Jehovah; the priests, the ministers of Jehovah, have mourned.

[[v29-1-10]]

^<<v29-1-10,10>>^ &#91;The&#93; field has been despoiled, &#91;the&#93; ground has gone to mourning; for &#91;the&#93; grain has been despoiled, &#91;the&#93; new wine has been dried up, &#91;the&#93; oil has faded away.

[[v29-1-11]]

^<<v29-1-11,11>>^ Farmers have felt shame; vinedressers have howled,^&#42;1^ on account of wheat and on account of barley; for the harvest of &#91;the&#93; field has perished.

[NOTE]
====
. Or, “Feel shame, you farmers; howl, you vinedressers.”
====

[[v29-1-12]]

^<<v29-1-12,12>>^ The vine itself has shown dryness, and even the fig tree has faded away. As for &#91;the&#93; pomegranate tree, also &#91;the&#93; palm tree and &#91;the&#93; apple tree, all the trees of the field, they have dried up; for exultation has gone ashamed away from the sons of mankind.^&#42;1^

[NOTE]
====
. Or, “earthling man.” Heb., ʼa·dhamʹ.
====

[[v29-1-13]]

^<<v29-1-13,13>>^ “Gird yourselves, and beat YOUR breasts, YOU priests. Howl, YOU ministers of &#91;the&#93; altar. Come in, spend the night in sackcloth, YOU ministers of my God;^&#42;1^ for from the house of YOUR God grain offering and drink offering have been withheld.

[NOTE]
====
. “My God.” Heb., ʼElo·haiʹ.
====

[[v29-1-14]]

^<<v29-1-14,14>>^ Sanctify a time of fasting. Call together a solemn assembly. Gather together &#91;the&#93; older men, all the inhabitants of the land,^&#42;1^ to the house of Jehovah YOUR God, and cry to Jehovah for aid.

[NOTE]
====
. Or, “the earth.” Heb., ha·ʼaʹrets.
====

[[v29-1-15]]

^<<v29-1-15,15>>^ “Alas for the day; because the day of Jehovah is near, and like a despoiling from the Almighty One^&#42;1^ it will come!

[NOTE]
====
. “From the Almighty One.” Heb., mi·Shad·daiʹ. Compare Ge 17:1 ftn.
====

[[v29-1-16]]

^<<v29-1-16,16>>^ Has not food itself been cut off before our very eyes; from the house of our God, rejoicing and joyfulness?

[[v29-1-17]]

^<<v29-1-17,17>>^ Dried figs^&#42;1^ have shriveled under their shovels. Storehouses have been laid desolate. Barns^&#42;2^ have been torn down, for &#91;the&#93; grain has dried up.

[NOTE]
====
. “Dried figs.” Or, “Grain seeds.”
. Possibly, “Tanks.”
====

[[v29-1-18]]

^<<v29-1-18,18>>^ O how the domestic animal has sighed! &#91;How&#93; the droves of cattle have wandered in confusion! For there is no pasturage for them. Also, the droves of the sheep have been the ones made to bear guilt.

[[v29-1-19]]

^<<v29-1-19,19>>^ “To you, O Jehovah, I shall call; for fire itself has devoured the pasture grounds of &#91;the&#93; wilderness, and a very flame has consumed all the trees of the field.

[[v29-1-20]]

^<<v29-1-20,20>>^ The beasts of the field also keep longing for you, because the channels of water have dried up, and fire itself has devoured the pasture grounds of the wilderness.”

'''

xref:028-hosea/028-hosea-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]