include::./index.adoc[]

[[v37-1-0]]
=== Haggai, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v37-1-1]]

^<<v37-1-1,1>>^ In the second year of Da·riʹus the king, in the sixth month, on the first day of the month, the word of Jehovah occurred by means of Hagʹgai the prophet to Ze·rubʹba·bel the son of She·alʹti·el, the governor of Judah, and to Joshua^&#42;1^ the son of Je·hozʹa·dak the high^&#42;2^ priest, saying:

[NOTE]
====
. “Joshua,” meaning “Jehovah Is Salvation.” Lit., “Jehoshua,” M; Sy, “Jeshua”; LXXVg, “Jesus.” See Heb 4:8 ftn, “Joshua.”
. Or, “chief.” Lit., “great,” MLXXVg.
====

[[v37-1-2]]

^<<v37-1-2,2>>^ “This is what Jehovah of armies^&#42;1^ has said, ‘As regards this people, they have said: “The time has not come, the time of the house of Jehovah, for &#91;it&#93; to be built.”’”

[NOTE]
====
. “Jehovah of armies.” Heb., Yehwahʹ tseva·ʼohthʹ; Gr., Kyʹri·os pan·to·kraʹtor, “Jehovah Almighty”; Luther (German, 1964 ed.), der HERR Zeʹba·oth. This expression occurs 14 times in Haggai’s prophecy.
====

[[v37-1-3]]

^<<v37-1-3,3>>^ And the word of Jehovah continued to come by means of Hagʹgai the prophet, saying:

[[v37-1-4]]

^<<v37-1-4,4>>^ “Is it the time for YOU yourselves to dwell in YOUR paneled houses, while this house is waste?

[[v37-1-5]]

^<<v37-1-5,5>>^ And now this is what Jehovah of armies has said, ‘Set YOUR heart upon YOUR ways.

[[v37-1-6]]

^<<v37-1-6,6>>^ YOU have sown much seed, but there is a bringing of little in. There is an eating, but it is not to satisfaction. There is a drinking, but not to the point of getting intoxicated. There is a putting on of clothes, but it is not with anyone’s getting warm; and he that is hiring himself out is hiring himself out for a bag having holes.’”

[[v37-1-7]]

^<<v37-1-7,7>>^ “This is what Jehovah of armies has said, ‘Set YOUR heart upon YOUR ways.’

[[v37-1-8]]

^<<v37-1-8,8>>^ “‘Go up to the mountain,^&#42;1^ and YOU must bring in lumber. And build the house, that I may take pleasure in it and I may be glorified,’ Jehovah has said.”

[NOTE]
====
. Or, “the mountainous region.”
====

[[v37-1-9]]

^<<v37-1-9,9>>^ “‘There was a looking for much, but here there was just a little; and YOU have brought &#91;it&#93; into the house, and I blew upon it—for what reason?’ is the utterance of Jehovah of armies. ‘By reason of my house that is waste, while YOU are on the run, each one in behalf of his own house.

[[v37-1-10]]

^<<v37-1-10,10>>^ Therefore over YOU &#91;the&#93; heavens kept back &#91;their&#93; dew, and the earth itself kept back its yield.

[[v37-1-11]]

^<<v37-1-11,11>>^ And I kept calling for dryness upon the earth,^&#42;1^ and upon the mountains, and upon the grain, and upon the new wine, and upon the oil, and upon what the ground would bring forth, and upon earthling man,^&#42;2^ and upon domestic animal, and upon all the toil of &#91;the&#93; hands.’”

[NOTE]
====
. Or, “the land.” Heb., ha·ʼaʹrets.
. Or, “mankind.” Heb., ha·ʼa·dhamʹ.
====

[[v37-1-12]]

^<<v37-1-12,12>>^ And Ze·rubʹba·bel the son of She·alʹti·el, and Joshua the son of Je·hozʹa·dak the high priest,^&#42;1^ and all the remaining ones of the people began to listen to the voice of Jehovah their God,^&#42;2^ and to the words of Hagʹgai the prophet, as Jehovah their God had sent him; and the people began to fear because of Jehovah.

[NOTE]
====
. Lit., “the great priest.”
. “Their God.” Heb., ʼElo·heh·hemʹ.
====

[[v37-1-13]]

^<<v37-1-13,13>>^ And Hagʹgai the messenger^&#42;1^ of Jehovah went on to say to the people according to the messenger’s commission from Jehovah, saying: “‘I am with YOU people,’ is the utterance of Jehovah.”

[NOTE]
====
. Or, “angel of.” Heb., mal·ʼakhʹ; Gr., agʹge·los; Lat., nunʹti·us, “messenger.”
====

[[v37-1-14]]

^<<v37-1-14,14>>^ And Jehovah proceeded to rouse up the spirit of Ze·rubʹba·bel the son of She·alʹti·el, the governor of Judah, and the spirit^&#42;1^ of Joshua the son of Je·hozʹa·dak the high priest, and the spirit of all the remaining ones of the people; and they began to enter in and to do the work in the house of Jehovah of armies their God.

[NOTE]
====
. “Spirit of.” Heb., ruʹach; Gr., pneuʹma; Lat., spiʹri·tum.
====

[[v37-1-15]]

^<<v37-1-15,15>>^ It was on the twenty-fourth day of the sixth month in the second year of Da·riʹus the king.

'''

xref:036-zephaniah/036-zephaniah-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-haggai/037-haggai-002.adoc#v37-2-0[Próximo Capítulo &#62;]