include::./index.adoc[]

[[v37-2-0]]
=== Haggai, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v37-2-1]]

^<<v37-2-1,1>>^ In the seventh &#91;month&#93;, on the twenty-first &#91;day&#93; of the month, the word of Jehovah occurred by means of Hagʹgai the prophet, saying:

[[v37-2-2]]

^<<v37-2-2,2>>^ “Say, please, to Ze·rubʹba·bel the son of She·alʹti·el, the governor of Judah, and to Joshua the son of Je·hozʹa·dak the high priest, and to the remaining ones of the people, saying,

[[v37-2-3]]

^<<v37-2-3,3>>^ ‘Who is there among YOU that is remaining over who saw this house in its former glory? And how are YOU people seeing it now? Is it not, in comparison with that, as nothing in YOUR eyes?’

[[v37-2-4]]

^<<v37-2-4,4>>^ “‘But now be strong, O Ze·rubʹba·bel,’ is the utterance of Jehovah, ‘and be strong, O Joshua the son of Je·hozʹa·dak the high priest.’
“‘And be strong, all YOU people of the land,’^&#42;1^ is the utterance of Jehovah, ‘and work.’
“‘For I am with YOU people,’ is the utterance of Jehovah of armies.

[NOTE]
====
. “People of the land.” Heb., ʽam ha·ʼaʹrets. Later used contemptuously. Compare Joh 7:47-49.
====

[[v37-2-5]]

^<<v37-2-5,5>>^ ‘&#91;Remember&#93; the thing^&#42;1^ that I concluded^&#42;2^ with YOU people when YOU came forth from Egypt, and &#91;when&#93; my spirit was standing in among YOU. Do not be afraid.’”

[NOTE]
====
. Lit., “word.”
. Lit., “cut.”
====

[[v37-2-6]]

^<<v37-2-6,6>>^ “For this is what Jehovah of armies has said, ‘Yet once—it is a little while—and I am rocking the heavens and the earth and the sea and the dry ground.’

[[v37-2-7]]

^<<v37-2-7,7>>^ “‘And I will rock all the nations,^&#42;1^ and the desirable things^&#42;2^ of all the nations must come in;^&#42;3^ and I will fill this house with glory,’ Jehovah of armies has said.

[NOTE]
====
. Lit., “And I will shake all the nations.”
. “Desirable things,” by a change of vowel pointing; M, “desirable (precious) thing,” sing. but evidently in a collective sense, for this word is accompanied by a pl. verb.
. Or, “and they, the desirable things of all the nations, must come in.”
====

[[v37-2-8]]

^<<v37-2-8,8>>^ “‘The silver is mine, and the gold is mine,’ is the utterance of Jehovah of armies.

[[v37-2-9]]

^<<v37-2-9,9>>^ “‘Greater will the glory of this later house become than &#91;that of&#93; the former,’ Jehovah of armies has said.
“‘And in this place I shall give peace,’ is the utterance of Jehovah of armies.”

[[v37-2-10]]

^<<v37-2-10,10>>^ In the twenty-fourth &#91;day&#93; of the ninth &#91;month&#93;, in the second year of Da·riʹus, the word of Jehovah occurred to Hagʹgai the prophet, saying:

[[v37-2-11]]

^<<v37-2-11,11>>^ “This is what Jehovah of armies has said, ‘Ask, please, the priests as to &#91;the&#93; law, saying:

[[v37-2-12]]

^<<v37-2-12,12>>^ “If a man^&#42;1^ carries holy flesh in the skirt of his garment, and he actually touches with his skirt bread or stew or wine or oil or any sort of food, will it become holy?”’”
And the priests proceeded to answer and say: “No!”

[NOTE]
====
. “A man.” Heb., ʼish.
====

[[v37-2-13]]

^<<v37-2-13,13>>^ And Hagʹgai went on to say: “If someone unclean by a deceased soul^&#42;1^ touches any of these things, will it become unclean?”
In turn the priests answered and said: “It will become unclean.”

[NOTE]
====
. Lit., “a soul,” that is, a dead soul. Heb., neʹphesh; Gr., psy·kheiʹ; Lat., aʹni·ma. See Le 21:11 and Nu 6:6 ftns; App 4A.
====

[[v37-2-14]]

^<<v37-2-14,14>>^ Accordingly Hagʹgai answered and said: “‘That is how this people is, and that is how this nation is before me,’ is the utterance of Jehovah, ‘and that is how all the work of their hands is, and whatever they present there. It is unclean.’

[[v37-2-15]]

^<<v37-2-15,15>>^ “‘But now, please, set YOUR heart &#91;on this&#93; from this day and forward, before there was the placing of a stone upon a stone in the temple^&#42;1^ of Jehovah,

[NOTE]
====
. “In the temple of.” Heb., beheh·khalʹ; Gr., na·oiʹ; Lat., temʹplo. See Mt 23:16 ftn.
====

[[v37-2-16]]

^<<v37-2-16,16>>^ from when those things happened to be—one came to a heap of twenty &#91;measures&#93;, and it proved to be ten; one came to the press vat to draw off fifty &#91;measures&#93; of the wine trough, and it proved to be twenty;

[[v37-2-17]]

^<<v37-2-17,17>>^ I struck YOU people with scorching and with mildew and with hail, even all the work of YOUR hands, and there was no one with YOU &#91;turning&#93; to me,’ is the utterance of Jehovah—

[[v37-2-18]]

^<<v37-2-18,18>>^ “‘Set YOUR heart, please, &#91;on this&#93; from this day and forward, from the twenty-fourth &#91;day&#93; of the ninth &#91;month&#93;, from the day that the foundation of the temple of Jehovah was laid; set YOUR heart &#91;on this&#93;:

[[v37-2-19]]

^<<v37-2-19,19>>^ Is there as yet the seed in the grain pit?^&#42;1^ And as yet, the vine and the fig tree and the pomegranate tree and the olive tree—it has not borne, has it? From this day I shall bestow blessing.’”

[NOTE]
====
. Or, “storeroom.”
====

[[v37-2-20]]

^<<v37-2-20,20>>^ And the word of Jehovah proceeded to occur a second time to Hagʹgai on the twenty-fourth &#91;day&#93; of the month, saying:

[[v37-2-21]]

^<<v37-2-21,21>>^ “Say to Ze·rubʹba·bel the governor of Judah, ‘I am rocking the heavens and the earth.

[[v37-2-22]]

^<<v37-2-22,22>>^ And I shall certainly overthrow the throne of kingdoms and annihilate the strength of the kingdoms of the nations; and I will overthrow &#91;the&#93; chariot and its riders, and &#91;the&#93; horses and their riders will certainly come down, each one by the sword of his brother.’”

[[v37-2-23]]

^<<v37-2-23,23>>^ “‘In that day,’ is the utterance of Jehovah of armies, ‘I shall take you, O Ze·rubʹba·bel the son of She·alʹti·el, my servant,’ is the utterance of Jehovah; ‘and I shall certainly set you as a seal ring, because you are the one whom I have chosen,’ is the utterance of Jehovah of armies.”

'''

xref:037-haggai/037-haggai-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zechariah/038-zechariah-001.adoc#v38-1-0[Próximo Capítulo &#62;]