include::./index.adoc[]

[[v58-6-0]]
=== To the Hebrews, 6
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-6-1]]

^<<v58-6-1,1>>^ For this reason, now that we have left the primary doctrine about the Christ, let us press on to maturity, not laying a foundation again, namely, repentance from dead works, and faith toward God,

[[v58-6-2]]

^<<v58-6-2,2>>^ the teaching on baptisms and the laying on of the hands, the resurrection of the dead and everlasting judgment.

[[v58-6-3]]

^<<v58-6-3,3>>^ And this we will do, if God indeed permits.

[[v58-6-4]]

^<<v58-6-4,4>>^ For it is impossible as regards those who have once for all been enlightened, and who have tasted the heavenly free gift, and who have become partakers of holy spirit,

[[v58-6-5]]

^<<v58-6-5,5>>^ and who have tasted the fine word of God and powers of the coming system of things,^&#42;1^

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v58-6-6]]

^<<v58-6-6,6>>^ but who have fallen away, to revive^&#42;1^ them again to repentance, because they impale^&#42;2^ the Son of God afresh for themselves and expose him to public shame.

[NOTE]
====
. Lit., “to be renovating.”
. Or, “fasten on a stake (pole).” See App 5C.
====

[[v58-6-7]]

^<<v58-6-7,7>>^ For example, the ground that drinks in the rain which often comes upon it, and that then brings forth vegetation suitable to those for whom it is also cultivated, receives in return a blessing from God.

[[v58-6-8]]

^<<v58-6-8,8>>^ But if it produces thorns and thistles, it is rejected and is near to being cursed; and it ends up with being burned.

[[v58-6-9]]

^<<v58-6-9,9>>^ However, in YOUR case, beloved ones, we are convinced of better things and things accompanied with salvation, although we are speaking in this way.

[[v58-6-10]]

^<<v58-6-10,10>>^ For God is not unrighteous so as to forget YOUR work and the love YOU showed for his name, in that YOU have ministered^&#42;1^ to the holy ones and continue ministering.

[NOTE]
====
. Lit., “having served.”
====

[[v58-6-11]]

^<<v58-6-11,11>>^ But we desire each one of YOU to show the same industriousness^&#42;1^ so as to have the full assurance of the hope down to the end,^&#42;2^

[NOTE]
====
. Lit., “speed up.” Gr., spou·denʹ.
. Or, “finish.” Gr., teʹlous.
====

[[v58-6-12]]

^<<v58-6-12,12>>^ in order that YOU may not become sluggish, but be imitators of those who through faith and patience^&#42;1^ inherit the promises.

[NOTE]
====
. “Patience.” Lit., “longness of spirit.”
====

[[v58-6-13]]

^<<v58-6-13,13>>^ For when God made his promise to Abraham, since he could not swear by anyone greater, he swore by himself,

[[v58-6-14]]

^<<v58-6-14,14>>^ saying: “Assuredly in blessing I will bless you, and in multiplying I will multiply you.”

[[v58-6-15]]

^<<v58-6-15,15>>^ And thus after &#91;Abraham&#93;^&#42;1^ had shown patience, he obtained &#91;this&#93; promise.

[NOTE]
====
. Lit., “he.”
====

[[v58-6-16]]

^<<v58-6-16,16>>^ For men swear by the one greater, and their oath is the end of every dispute, as it is a legal guarantee to them.

[[v58-6-17]]

^<<v58-6-17,17>>^ In this manner God, when he purposed to demonstrate more abundantly to the heirs of the promise the unchangeableness of his counsel, stepped in^&#42;1^ with an oath,

[NOTE]
====
. Lit., “he mediated.”
====

[[v58-6-18]]

^<<v58-6-18,18>>^ in order that, through two unchangeable things in which it is impossible for God to lie, we who have fled to the refuge may have strong encouragement to lay hold on the hope set before us.

[[v58-6-19]]

^<<v58-6-19,19>>^ This &#91;hope&#93; we have as an anchor for the soul, both sure and firm, and it enters in within^&#42;1^ the curtain,

[NOTE]
====
. Or, “beyond.”
====

[[v58-6-20]]

^<<v58-6-20,20>>^ where a forerunner has entered in our behalf, Jesus, who has become a high priest according to the manner of Mel·chizʹe·dek forever.

'''

xref:058-hebrews/058-hebrews-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebrews/058-hebrews-007.adoc#v58-7-0[Próximo Capítulo &#62;]