include::./index.adoc[]

[[v58-1-0]]
=== To the Hebrews, 1
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-1-1]]

^<<v58-1-1,1>>^ God, who long ago spoke on many occasions and in many ways to our forefathers by means of the prophets,

[[v58-1-2]]

^<<v58-1-2,2>>^ has at the end of these days spoken to us by means of a Son, whom he appointed heir of all things, and through whom he made the systems of things.^&#42;1^

[NOTE]
====
. Or, “the orders of things.” Gr., tous ai·oʹnas; Lat., saeʹcu·la; J22(Heb.), ha·ʽoh·la·mimʹ.
====

[[v58-1-3]]

^<<v58-1-3,3>>^ He is the reflection^&#42;1^ of &#91;his&#93; glory and the exact representation of his very being,^&#42;2^ and he sustains all things by the word of his power; and after he had made a purification for our sins he sat down on the right hand of the Majesty^&#42;3^ in lofty places.

[NOTE]
====
. Lit., “beaming forth from.”
. Or, “the image imprinted by his substance.”
. Lit., “of the Greatness.” Gr., tes Me·ga·lo·syʹnes; Lat., Ma·ie·staʹtis; J17,​18,​22(Heb.), hag·Gedhul·lahʹ.
====

[[v58-1-4]]

^<<v58-1-4,4>>^ So he has become better than the angels, to the extent that he has inherited a name more excellent than theirs.

[[v58-1-5]]

^<<v58-1-5,5>>^ For example, to which one of the angels did he ever say: “You are my son; I, today, I have become your father”? And again: “I myself shall become his father, and he himself will become my son”?

[[v58-1-6]]

^<<v58-1-6,6>>^ But when he again brings his Firstborn into the inhabited earth, he says: “And let all God’s angels do obeisance to^&#42;1^ him.”

[NOTE]
====
. Or, “let . . . worship.” Gr., pro·sky·ne·saʹto·san; Lat., a·doʹrent. See 2Ki 2:15 and ftn.
====

[[v58-1-7]]

^<<v58-1-7,7>>^ Also, with reference to the angels he says: “And he makes his angels spirits, and his public servants^&#42;1^ a flame of fire.”

[NOTE]
====
. Lit., “public workers.” Gr., lei·tour·gousʹ.
====

[[v58-1-8]]

^<<v58-1-8,8>>^ But with reference to the Son: “God is your throne forever and ever, and &#91;the&#93; scepter of your^&#42;1^ kingdom is the scepter of uprightness.^&#42;2^

[NOTE]
====
. “Your,” ADItVgSyh,p and Ps 45:6; P46אB, “his.”
. Lit., “staff of the straightness.”
====

[[v58-1-9]]

^<<v58-1-9,9>>^ You loved righteousness, and you hated lawlessness. That is why God, your God, anointed you with &#91;the&#93; oil of exultation more than your partners.”

[[v58-1-10]]

^<<v58-1-10,10>>^ And: “You at &#91;the&#93; beginning, O Lord, laid the foundations of the earth itself, and the heavens are &#91;the&#93; works of your hands.

[[v58-1-11]]

^<<v58-1-11,11>>^ They themselves will perish,^&#42;1^ but you yourself are to remain continually; and just like an outer garment they will all grow old,

[NOTE]
====
. Lit., “will destroy themselves.”
====

[[v58-1-12]]

^<<v58-1-12,12>>^ and you will wrap them up just as a cloak, as an outer garment;^&#42;1^ and they will be changed, but you are the same, and your years will never run out.”

[NOTE]
====
. “As an outer garment,” P46אABD; VgSyp and TR omit.
====

[[v58-1-13]]

^<<v58-1-13,13>>^ But with reference to which one of the angels has he ever said: “Sit at my right hand, until I place your enemies as a stool for your feet”?

[[v58-1-14]]

^<<v58-1-14,14>>^ Are they not all spirits for public service, sent forth to minister for those who are going to inherit salvation?

'''

xref:057-philemon/057-philemon-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebrews/058-hebrews-002.adoc#v58-2-0[Próximo Capítulo &#62;]