include::./index.adoc[]

[[v58-8-0]]
=== To the Hebrews, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-8-1]]

^<<v58-8-1,1>>^ Now as to the things being discussed this is the main point: We have such a high priest as this, and he has sat down at the right hand of the throne of the Majesty^&#42;1^ in the heavens,

[NOTE]
====
. See 1:3 ftn, “Majesty.”
====

[[v58-8-2]]

^<<v58-8-2,2>>^ a public servant^&#42;1^ of the holy place^&#42;2^ and of the true tent,^&#42;3^ which Jehovah^&#42;4^ put up, and not man.

[NOTE]
====
. Lit., “public worker.” Gr., lei·tour·gosʹ.
. Or, “places.”
. Or, “tabernacle.”
. See App 1D.
====

[[v58-8-3]]

^<<v58-8-3,3>>^ For every high priest is appointed to offer both gifts and sacrifices; wherefore it was necessary for this one also to have something to offer.

[[v58-8-4]]

^<<v58-8-4,4>>^ If, now, he were upon earth, he would not be a priest, there being &#91;men&#93; who offer the gifts according to the Law,

[[v58-8-5]]

^<<v58-8-5,5>>^ but which &#91;men&#93; are rendering sacred service in a typical representation^&#42;1^ and a shadow of the heavenly things; just as Moses, when about to make the tent in completion, was given the divine command:^&#42;2^ For says he: “See that you make all things after &#91;their&#93; pattern^&#42;3^ that was shown to you in the mountain.”

[NOTE]
====
. “Typical representation.” Lit., “example.”
. Lit., “has been divinely warned.”
. Or, “type.” Gr., tyʹpon; Lat., ex·emʹplar.
====

[[v58-8-6]]

^<<v58-8-6,6>>^ But now &#91;Jesus&#93;^&#42;1^ has obtained a more excellent public service, so that he is also the mediator of a correspondingly better covenant, which has been legally established upon better promises.

[NOTE]
====
. Lit., “he.”
====

[[v58-8-7]]

^<<v58-8-7,7>>^ For if that first covenant had been faultless, no place would have been sought for a second;

[[v58-8-8]]

^<<v58-8-8,8>>^ for he does find fault with the people when he says: “‘Look! There are days coming,’ says Jehovah,^&#42;1^ ‘and I will conclude with the house of Israel and with the house of Judah a new covenant;

[NOTE]
====
. See App 1D.
====

[[v58-8-9]]

^<<v58-8-9,9>>^ not according to the covenant that I made with their forefathers in &#91;the&#93; day of my taking hold of their hand to bring them forth out of the land of Egypt, because they did not continue in my covenant, so that I stopped caring for them,’ says Jehovah.”^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v58-8-10]]

^<<v58-8-10,10>>^ “‘For this is the covenant that I shall covenant with the house of Israel after those days,’ says Jehovah.^&#42;1^ ‘I will put my laws in their mind, and in their hearts I shall write them. And I will become their God, and they themselves will become my people.

[NOTE]
====
. See App 1D.
====

[[v58-8-11]]

^<<v58-8-11,11>>^ “‘And they will by no means teach each one his fellow citizen and each one his brother, saying: “Know Jehovah!”^&#42;1^ For they will all know me, from &#91;the&#93; least one to &#91;the&#93; greatest one of them.

[NOTE]
====
. See App 1D.
====

[[v58-8-12]]

^<<v58-8-12,12>>^ For I shall be merciful to their unrighteous deeds, and I shall by no means call their sins to mind anymore.’”

[[v58-8-13]]

^<<v58-8-13,13>>^ In his saying “a new &#91;covenant&#93;” he has made the former one obsolete.^&#42;1^ Now that which is made obsolete and growing old is near to vanishing away.

[NOTE]
====
. “He has made . . . obsolete.” Lit., “he has made old.”
====

'''

xref:058-hebrews/058-hebrews-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebrews/058-hebrews-009.adoc#v58-9-0[Próximo Capítulo &#62;]