include::./index.adoc[]

[[v58-11-0]]
=== To the Hebrews, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-11-1]]

^<<v58-11-1,1>>^ Faith is the assured expectation^&#42;1^ of things hoped for, the evident demonstration^&#42;2^ of realities^&#42;3^ though not beheld.

[NOTE]
====
. “Assured expectation.” Lit., “a sub-standing.” Gr., hy·poʹsta·sis; Lat., sub·stanʹti·a.
. “Evident demonstration.” Or, “convincing evidence.” Gr., eʹleg·khos; Lat., ar·gu·menʹtum. Compare Joh 16:8 ftn.
. Lit., “of things.” Gr., prag·maʹton.
====

[[v58-11-2]]

^<<v58-11-2,2>>^ For by means of this the men of old times^&#42;1^ had witness borne to them.

[NOTE]
====
. “Men of old times.” Lit., “older men.” Gr., pre·sbyʹte·roi.
====

[[v58-11-3]]

^<<v58-11-3,3>>^ By faith we perceive that the systems of things^&#42;1^ were put in order^&#42;2^ by God’s word, so that what is beheld has come to be out of things that do not appear.

[NOTE]
====
. Or, “the orders of things.” Gr., tous ai·oʹnas; Lat., saeʹcu·la; J22(Heb.), ha·ʽoh·la·mimʹ.
. Or, “were prepared; were adjusted.” Lit., “to have been adjusted down.” Gr., ka·ter·tiʹsthai.
====

[[v58-11-4]]

^<<v58-11-4,4>>^ By faith Abel offered God a sacrifice of greater worth than Cain, through which &#91;faith&#93; he had witness borne to him that he was righteous, God bearing witness respecting his gifts; and through it he, although he died, yet speaks.

[[v58-11-5]]

^<<v58-11-5,5>>^ By faith Eʹnoch was transferred so as not to see death, and he was nowhere to be found because God had transferred him; for before his transference he had the witness that he had pleased God well.

[[v58-11-6]]

^<<v58-11-6,6>>^ Moreover, without faith it is impossible to please &#91;him&#93; well, for he that approaches God must believe that he is and that he becomes the rewarder^&#42;1^ of those earnestly seeking him.

[NOTE]
====
. Lit., “giver back of reward.”
====

[[v58-11-7]]

^<<v58-11-7,7>>^ By faith Noah, after being given divine warning of things not yet beheld, showed godly fear and constructed an ark for the saving of his household; and through this &#91;faith&#93; he condemned the world, and he became an heir of the righteousness that is according to faith.

[[v58-11-8]]

^<<v58-11-8,8>>^ By faith Abraham, when he was called, obeyed in going out into a place he was destined to receive as an inheritance; and he went out, although not knowing where he was going.

[[v58-11-9]]

^<<v58-11-9,9>>^ By faith he resided as an alien in the land of the promise as in a foreign land, and dwelt in tents with Isaac and Jacob, the heirs with him of the very same promise.

[[v58-11-10]]

^<<v58-11-10,10>>^ For he was awaiting the city having real foundations, the builder^&#42;1^ and maker of which &#91;city&#93; is God.

[NOTE]
====
. Lit., “artificer.” Gr., te·khniʹtes.
====

[[v58-11-11]]

^<<v58-11-11,11>>^ By faith also Sarah herself received power to conceive seed, even when she was past the age limit, since she esteemed him faithful who had promised.

[[v58-11-12]]

^<<v58-11-12,12>>^ Hence also from one &#91;man&#93;, and him as good as dead, there were born &#91;children&#93; just as the stars of heaven for multitude and as the sands that are by the seaside, innumerable.

[[v58-11-13]]

^<<v58-11-13,13>>^ In faith all these died, although they did not get the &#91;fulfillment of the&#93; promises, but they saw them afar off and welcomed^&#42;1^ them and publicly declared that they were strangers and temporary residents in the land.

[NOTE]
====
. Or, “greeted; embraced; hailed.”
====

[[v58-11-14]]

^<<v58-11-14,14>>^ For those who say such things give evidence that they are earnestly seeking a place of their own.

[[v58-11-15]]

^<<v58-11-15,15>>^ And yet, if they had indeed kept remembering that &#91;place&#93; from which they had gone forth, they would have had opportunity to return.

[[v58-11-16]]

^<<v58-11-16,16>>^ But now they are reaching out for a better &#91;place&#93;, that is, one belonging to heaven. Hence God is not ashamed of them, to be called upon as their God, for he has made a city ready for them.

[[v58-11-17]]

^<<v58-11-17,17>>^ By faith Abraham, when he was tested, as good as offered^&#42;1^ up Isaac, and the man that had gladly received the promises attempted^&#42;2^ to offer up &#91;his&#93; only-begotten &#91;son&#93;,

[NOTE]
====
. Or, “Abraham, when being tried, has (as it were) offered.”
. Or, “proceeded.”
====

[[v58-11-18]]

^<<v58-11-18,18>>^ although it had been said to him: “What will be called ‘your seed’ will be through Isaac.”

[[v58-11-19]]

^<<v58-11-19,19>>^ But he reckoned that God was able to raise him up even from the dead; and from there he did receive him also in an illustrative way.^&#42;1^

[NOTE]
====
. Lit., “in a parable.” Gr., en pa·ra·bo·leiʹ.
====

[[v58-11-20]]

^<<v58-11-20,20>>^ By faith also Isaac blessed Jacob and Eʹsau concerning things to come.

[[v58-11-21]]

^<<v58-11-21,21>>^ By faith Jacob, when about to die, blessed each of the sons of Joseph and worshiped leaning^&#42;1^ upon the top of his staff.

[NOTE]
====
. In agreement with the sense of the Heb. text in Ge 47:31, where see ftn.
====

[[v58-11-22]]

^<<v58-11-22,22>>^ By faith Joseph, nearing his end, made mention of the exodus of the sons of Israel; and he gave a command concerning his bones.

[[v58-11-23]]

^<<v58-11-23,23>>^ By faith Moses was hid for three months by his parents after his birth, because they saw the young child was beautiful and they did not fear the order of the king.

[[v58-11-24]]

^<<v58-11-24,24>>^ By faith Moses, when grown up, refused^&#42;1^ to be called the son of the daughter of Pharʹaoh,

[NOTE]
====
. Lit., “he denied.”
====

[[v58-11-25]]

^<<v58-11-25,25>>^ choosing to be ill-treated with the people of God rather than to have the temporary enjoyment of sin,

[[v58-11-26]]

^<<v58-11-26,26>>^ because he esteemed the reproach of the Christ^&#42;1^ as riches greater than the treasures of Egypt; for he looked intently toward the payment of the reward.

[NOTE]
====
. “Of the Christ.” Gr., tou Khri·stouʹ; Lat., Chriʹsti; J17,​18,​22(Heb.), ham·Ma·shiʹach, “the Messiah (Anointed One).”
====

[[v58-11-27]]

^<<v58-11-27,27>>^ By faith he left Egypt, but not fearing the anger of the king, for he continued steadfast as seeing the One who is invisible.

[[v58-11-28]]

^<<v58-11-28,28>>^ By faith he had celebrated^&#42;1^ the passover^&#42;2^ and the splashing of the blood, that the destroyer might not touch their firstborn ones.

[NOTE]
====
. Or, “he actually celebrated.”
. Gr., paʹskha; Lat., paʹscha; J17,​18,​22(Heb.), hap·peʹsach, “the passover.”
====

[[v58-11-29]]

^<<v58-11-29,29>>^ By faith they passed through the Red Sea as on dry land, but on venturing out upon it the Egyptians were swallowed up.

[[v58-11-30]]

^<<v58-11-30,30>>^ By faith the walls of Jerʹi·cho fell down after they had been encircled^&#42;1^ for seven days.

[NOTE]
====
. Or, “had been besieged (gone around).”
====

[[v58-11-31]]

^<<v58-11-31,31>>^ By faith Raʹhab the harlot did not perish with those who acted disobediently, because she received the spies in a peaceable way.

[[v58-11-32]]

^<<v58-11-32,32>>^ And what more shall I say? For the time will fail me if I go on to relate about Gidʹe·on, Baʹrak, Samson, Jephʹthah, David as well as Samuel and the &#91;other&#93; prophets,

[[v58-11-33]]

^<<v58-11-33,33>>^ who through faith defeated kingdoms in conflict, effected righteousness, obtained promises, stopped the mouths of lions,

[[v58-11-34]]

^<<v58-11-34,34>>^ stayed the force of fire, escaped the edge^&#42;1^ of the sword, from a weak state were made powerful, became valiant in war, routed the armies of foreigners.

[NOTE]
====
. Lit., “mouths.”
====

[[v58-11-35]]

^<<v58-11-35,35>>^ Women received their dead by resurrection; but other &#91;men&#93; were tortured because they would not accept release by some ransom, in order that they might attain a better resurrection.

[[v58-11-36]]

^<<v58-11-36,36>>^ Yes, others received their trial by mockings and scourgings, indeed, more than that, by bonds and prisons.

[[v58-11-37]]

^<<v58-11-37,37>>^ They were stoned, they were tried, they were sawn asunder, they died by slaughter with the sword, they went about in sheepskins, in goatskins, while they were in want, in tribulation, under ill-treatment;

[[v58-11-38]]

^<<v58-11-38,38>>^ and the world was not worthy of them. They wandered about in deserts and mountains and caves and dens of the earth.

[[v58-11-39]]

^<<v58-11-39,39>>^ And yet all these, although they had witness borne to them through their faith, did not get the &#91;fulfillment of the&#93; promise,

[[v58-11-40]]

^<<v58-11-40,40>>^ as God foresaw^&#42;1^ something better for us, in order that they might not be made perfect apart from us.

[NOTE]
====
. Or, “provided.”
====

'''

xref:058-hebrews/058-hebrews-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebrews/058-hebrews-012.adoc#v58-12-0[Próximo Capítulo &#62;]