include::./index.adoc[]

[[v58-9-0]]
=== To the Hebrews, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-9-1]]

^<<v58-9-1,1>>^ For its part, then, the former &#91;covenant&#93; used to have ordinances of sacred service^&#42;1^ and &#91;its&#93; mundane^&#42;2^ holy place.

[NOTE]
====
. “Sacred service.” Gr., la·treiʹas; J22(Heb.), ʽavoh·dhahʹ. See Ex 12:25 ftn.
. Or, “worldly,” that is, belonging to this world. Gr., ko·smi·konʹ; Novum Testamentum, Theodore Bezae, 1642, reprinted in 1925, Lat., mun·daʹnum; J17(Heb.), ʼar·tsiʹ, “earthly.”
====

[[v58-9-2]]

^<<v58-9-2,2>>^ For there was constructed a first tent &#91;compartment&#93; in which were the lampstand and also the table and the display of the loaves;^&#42;1^ and it is called “the Holy Place.”

[NOTE]
====
. “Display of the loaves.” Or, “showbread.”
====

[[v58-9-3]]

^<<v58-9-3,3>>^ But behind the second curtain was the tent &#91;compartment&#93; called “the Most Holy.”^&#42;1^

[NOTE]
====
. Or, “the Holy of Holies.” Gr., Haʹgi·a Ha·giʹon; Lat., sancʹta sanc·toʹrum; J17,​18,​22(Heb.), Qo·dheshʹ haq·Qodha·shimʹ.
====

[[v58-9-4]]

^<<v58-9-4,4>>^ This had a golden censer and the ark of the covenant overlaid all around with gold, in which were the golden jar having the manna and the rod of Aaron that budded and the tablets of the covenant;^&#42;1^

[NOTE]
====
. See App 7D.
====

[[v58-9-5]]

^<<v58-9-5,5>>^ but up above it were the glorious cherubs overshadowing the propitiatory &#91;cover&#93;.^&#42;1^ But now is not the time to speak in detail concerning these things.

[NOTE]
====
. Or, “mercy seat.” Gr., hi·la·steʹri·on; Lat., pro·pi·ti·a·toʹri·um; J17(Heb.), hak·kap·poʹreth, “the propitiatory cover.” See 1Ch 28:11 ftn.
====

[[v58-9-6]]

^<<v58-9-6,6>>^ After these things had been constructed this way, the priests enter the first tent &#91;compartment&#93; at all times to perform the sacred services;

[[v58-9-7]]

^<<v58-9-7,7>>^ but into the second &#91;compartment&#93; the high priest alone enters once a year, not without blood, which he offers for himself and for the sins of ignorance of the people.

[[v58-9-8]]

^<<v58-9-8,8>>^ Thus the holy spirit makes it plain that the way into the holy place^&#42;1^ had not yet been made manifest while the first tent was standing.

[NOTE]
====
. Lit., “holies (holy places)”; pl. to denote excellence.
====

[[v58-9-9]]

^<<v58-9-9,9>>^ This very &#91;tent&#93; is an illustration^&#42;1^ for the appointed time that is now here, and in keeping with it both gifts and sacrifices are offered. However, these are not able to make the &#91;man&#93; doing sacred service^&#42;2^ perfect as respects his conscience,

[NOTE]
====
. Or, “parable.” Gr., pa·ra·bo·leʹ.
. “Doing sacred service.” Gr., la·treuʹon·ta; J17(Heb.), ha·ʽo·vedhʹ, “the one serving (worshiping).” See Ex 3:12 ftn.
====

[[v58-9-10]]

^<<v58-9-10,10>>^ but have to do only with foods and drinks and various baptisms.^&#42;1^ They were legal requirements pertaining to the flesh and were imposed until the appointed time to set things straight.^&#42;2^

[NOTE]
====
. Or, “washings.”
. Lit., “of thorough straightening out.”
====

[[v58-9-11]]

^<<v58-9-11,11>>^ However, when Christ came as a high priest of the good things that have come to pass,^&#42;1^ through the greater and more perfect tent not made with hands, that is, not of this creation,

[NOTE]
====
. “Things that have come to pass,” P46BD*Syh,p; אADcItVg, “things to come.”
====

[[v58-9-12]]

^<<v58-9-12,12>>^ he entered, no, not with^&#42;1^ the blood of goats and of young bulls, but with his own blood, once for all time into the holy place and obtained^&#42;2^ an everlasting deliverance^&#42;3^ &#91;for us&#93;.

[NOTE]
====
. Or, “through.”
. Or, “found.”
. Lit., “ransoming.”
====

[[v58-9-13]]

^<<v58-9-13,13>>^ For if the blood of goats and of bulls and the ashes of a heifer sprinkled on those who have been defiled^&#42;1^ sanctifies to the extent of cleanness of the flesh,

[NOTE]
====
. Lit., “having been made common.”
====

[[v58-9-14]]

^<<v58-9-14,14>>^ how much more will the blood of the Christ, who through an everlasting spirit offered himself without blemish to God, cleanse our consciences from dead works that we may render sacred service to &#91;the&#93; living God?

[[v58-9-15]]

^<<v58-9-15,15>>^ So that is why he is a mediator of a new covenant, in order that, because a death has occurred for &#91;their&#93; release by ransom from the transgressions under the former covenant, the ones who have been called might receive the promise of the everlasting inheritance.

[[v58-9-16]]

^<<v58-9-16,16>>^ For where there is a covenant,^&#42;1^ the death of the &#91;human&#93; covenanter^&#42;2^ needs to be furnished.

[NOTE]
====
. For a discussion of “covenant,” see App 7D.
. “Of the [human] convenanter.” Or, “of the mediating [sacrifice; victim].” See App 7D.
====

[[v58-9-17]]

^<<v58-9-17,17>>^ For a covenant is valid over dead &#91;victims&#93;,^&#42;1^ since it is not in force at any time while the &#91;human&#93; covenanter is living.

[NOTE]
====
. Or, “[persons].”
====

[[v58-9-18]]

^<<v58-9-18,18>>^ Consequently neither was the former &#91;covenant&#93; inaugurated^&#42;1^ without blood.

[NOTE]
====
. Lit., “innovated.”
====

[[v58-9-19]]

^<<v58-9-19,19>>^ For when every commandment according to the Law had been spoken by Moses to all the people, he took the blood of the young bulls and of the goats with water and scarlet wool and hyssop and sprinkled the book^&#42;1^ itself and all the people,

[NOTE]
====
. Or, “tablet.”
====

[[v58-9-20]]

^<<v58-9-20,20>>^ saying: “This is the blood of the covenant that God has laid as a charge upon YOU.”^&#42;1^

[NOTE]
====
. “Jehovah has concluded with you,” J3,​7,​8,​20.
====

[[v58-9-21]]

^<<v58-9-21,21>>^ And he sprinkled the tent and all the vessels of the public service likewise with the blood.

[[v58-9-22]]

^<<v58-9-22,22>>^ Yes, nearly all things are cleansed with blood according to the Law, and unless blood is poured out no forgiveness^&#42;1^ takes place.

[NOTE]
====
. Lit., “letting go off.”
====

[[v58-9-23]]

^<<v58-9-23,23>>^ Therefore it was necessary that the typical representations of the things in the heavens should be cleansed by these means, but the heavenly things themselves with sacrifices that are better than such sacrifices.

[[v58-9-24]]

^<<v58-9-24,24>>^ For Christ entered, not into a holy place made with hands, which is a copy of the reality,^&#42;1^ but into heaven itself, now to appear before the person of God for us.

[NOTE]
====
. Or, “into holy places . . . which are copies of the realities.”
====

[[v58-9-25]]

^<<v58-9-25,25>>^ Neither is it in order that he should offer himself often, as indeed the high priest enters into the holy place^&#42;1^ from year to year with blood not his own.

[NOTE]
====
. Or, “the holy places.”
====

[[v58-9-26]]

^<<v58-9-26,26>>^ Otherwise, he would have to suffer often from the founding^&#42;1^ of the world. But now he has manifested himself once for all time at the conclusion^&#42;2^ of the systems of things^&#42;3^ to put sin away through the sacrifice of himself.

[NOTE]
====
. Lit., “throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
. Or, “joint end; consummation; ending together.” Gr., syn·te·leiʹai, dative, sing.
. Or, “of the orders of things.” Gr., ton ai·oʹnon; Lat., sae·cu·loʹrum; J22(Heb.), ha·ʽoh·la·mimʹ.
====

[[v58-9-27]]

^<<v58-9-27,27>>^ And as it is reserved for men to die once for all time, but after this a judgment,

[[v58-9-28]]

^<<v58-9-28,28>>^ so also the Christ was offered once for all time to bear the sins of many; and the second time that he appears it will be apart from sin^&#42;1^ and to those earnestly looking for him for &#91;their&#93; salvation.

[NOTE]
====
. Or, “be without a sin offering.”
====

'''

xref:058-hebrews/058-hebrews-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebrews/058-hebrews-010.adoc#v58-10-0[Próximo Capítulo &#62;]