include::./index.adoc[]

[[v58-7-0]]
=== To the Hebrews, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-7-1]]

^<<v58-7-1,1>>^ For this Mel·chizʹe·dek, king of Saʹlem, priest of the Most High God, who met Abraham returning from the slaughter of the kings and blessed him

[[v58-7-2]]

^<<v58-7-2,2>>^ and to whom Abraham apportioned a tenth from all things, is first of all, by translation, “King of Righteousness,” and is then also king of Saʹlem, that is, “King of Peace.”

[[v58-7-3]]

^<<v58-7-3,3>>^ In being fatherless, motherless, without genealogy, having neither a beginning of days nor an end of life, but having been made like the Son of God, he remains a priest perpetually.

[[v58-7-4]]

^<<v58-7-4,4>>^ BEHOLD, then, how great this man was to whom Abraham, the family head,^&#42;1^ gave a tenth out of the chief spoils.

[NOTE]
====
. “Family head.” Lit., “patriarch.” Gr., pa·tri·arʹkhes.
====

[[v58-7-5]]

^<<v58-7-5,5>>^ True, the men from the sons of Leʹvi who receive their priestly office have a commandment to collect tithes from the people according to the Law, that is, from their brothers, even if these have issued from the loins of Abraham;

[[v58-7-6]]

^<<v58-7-6,6>>^ but the man who did not trace his genealogy from them took tithes from Abraham and blessed him who had the promises.

[[v58-7-7]]

^<<v58-7-7,7>>^ Now without any dispute,^&#42;1^ the less is blessed by the greater.

[NOTE]
====
. Lit., “contradiction.” Gr., an·ti·lo·giʹas.
====

[[v58-7-8]]

^<<v58-7-8,8>>^ And in the one case it is men who are dying that receive tithes, but in the other case it is someone of whom it is witnessed that he lives.

[[v58-7-9]]

^<<v58-7-9,9>>^ And, if I may use the expression, through Abraham even Leʹvi who receives tithes has paid tithes,

[[v58-7-10]]

^<<v58-7-10,10>>^ for he was still in the loins of his forefather when Mel·chizʹe·dek met him.

[[v58-7-11]]

^<<v58-7-11,11>>^ If, then, perfection were really through the Levitical priesthood, (for with it as a feature^&#42;1^ the people were given the Law,) what further need would there be for another priest to arise according to the manner^&#42;2^ of Mel·chizʹe·dek and not said to be according to the manner of Aaron?

[NOTE]
====
. Or, “on it as a basis.”
. See 5:6 ftn.
====

[[v58-7-12]]

^<<v58-7-12,12>>^ For since the priesthood is being changed, there comes to be of necessity a change also of the law.

[[v58-7-13]]

^<<v58-7-13,13>>^ For the man respecting whom these things are said has been a member of another tribe, from which no one has officiated at the altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ For it is quite plain that our Lord has sprung up out of Judah, a tribe about which Moses spoke nothing concerning priests.

[[v58-7-15]]

^<<v58-7-15,15>>^ And it is still more abundantly clear that with a similarity^&#42;1^ to Mel·chizʹe·dek there arises another priest,

[NOTE]
====
. Lit., “likeness.”
====

[[v58-7-16]]

^<<v58-7-16,16>>^ who has become such, not according to the law of a commandment depending upon the flesh, but according to the power of an indestructible^&#42;1^ life,

[NOTE]
====
. Lit., “in­dissoluble.”
====

[[v58-7-17]]

^<<v58-7-17,17>>^ for in witness it is said: “You are a priest forever according to the manner of Mel·chizʹe·dek.”

[[v58-7-18]]

^<<v58-7-18,18>>^ Certainly, then, there occurs a setting aside of the preceding commandment on account of its weakness and ineffectiveness.^&#42;1^

[NOTE]
====
. Lit., “unbeneficial(ness).”
====

[[v58-7-19]]

^<<v58-7-19,19>>^ For the Law made nothing perfect, but the bringing in besides of a better hope did, through which we are drawing near to God.

[[v58-7-20]]

^<<v58-7-20,20>>^ Also, to the extent that it was not without a sworn oath,

[[v58-7-21]]

^<<v58-7-21,21>>^ (for there are indeed men that have become priests without a sworn oath, but there is one with an oath sworn by the One who said respecting him: “Jehovah^&#42;1^ has sworn (and he will feel no regret), ‘You are a priest forever,’”)

[NOTE]
====
. See App 1D.
====

[[v58-7-22]]

^<<v58-7-22,22>>^ to that extent also Jesus has become the one given in pledge of a better covenant.^&#42;1^

[NOTE]
====
. See App 7D.
====

[[v58-7-23]]

^<<v58-7-23,23>>^ Furthermore, many had to become priests &#91;in succession&#93; because of being prevented by death from continuing as such,

[[v58-7-24]]

^<<v58-7-24,24>>^ but he because of continuing alive forever has his priesthood without any successors.^&#42;1^

[NOTE]
====
. Or, “priesthood not successive (not transferable).”
====

[[v58-7-25]]

^<<v58-7-25,25>>^ Consequently he is able also to save completely those who are approaching God through him, because he is always alive to plead^&#42;1^ for them.

[NOTE]
====
. Lit., “to be interceding.”
====

[[v58-7-26]]

^<<v58-7-26,26>>^ For such a high priest as this was suitable for us, loyal, guileless, undefiled, separated from the sinners, and become higher than the heavens.

[[v58-7-27]]

^<<v58-7-27,27>>^ He does not need daily, as those high priests do, to offer up sacrifices, first for his own sins and then for those of the people: (for this he did once for all time when he offered himself up;)

[[v58-7-28]]

^<<v58-7-28,28>>^ for the Law appoints men high priests having weakness, but the word of the sworn oath that came after the Law appoints a Son, who is perfected^&#42;1^ forever.

[NOTE]
====
. Or, “inaugurated; installed; consecrated to office; empowered.” Gr., te·te·lei·o·meʹnon. Compare 5:9 ftn.
====

'''

xref:058-hebrews/058-hebrews-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebrews/058-hebrews-008.adoc#v58-8-0[Próximo Capítulo &#62;]