include::./index.adoc[]

[[v58-4-0]]
=== To the Hebrews, 4
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-4-1]]

^<<v58-4-1,1>>^ Therefore, since a promise is left of entering into his rest, let us fear that sometime someone of YOU may seem to have fallen short of it.

[[v58-4-2]]

^<<v58-4-2,2>>^ For we have had the good news declared to us also, even as they also had; but the word which was heard did not benefit them, because they were not united by faith with those who did hear.^&#42;1^

[NOTE]
====
. “Because it [the word] was not united by faith with those who heard,” א.
====

[[v58-4-3]]

^<<v58-4-3,3>>^ For we who have exercised faith do enter into the rest, just as he has said: “So I swore in my anger, ‘They shall not enter into my rest,’” although his^&#42;1^ works were finished from the founding^&#42;2^ of the world.

[NOTE]
====
. Lit., “the,” אAB; Syp, “God’s”; J17, “Jehovah’s.”
. Lit., “throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v58-4-4]]

^<<v58-4-4,4>>^ For in one place he has said of the seventh day as follows: “And God^&#42;1^ rested on the seventh day from all his works,”

[NOTE]
====
. “God,” אABVgSyp; J17, “he.”
====

[[v58-4-5]]

^<<v58-4-5,5>>^ and again in this place: “They shall not enter into my rest.”

[[v58-4-6]]

^<<v58-4-6,6>>^ Since, therefore, it remains for some to enter into it, and those to whom the good news was first declared did not enter in because of disobedience,

[[v58-4-7]]

^<<v58-4-7,7>>^ he again marks off a certain day by saying after so long a time in David’s &#91;psalm&#93; “Today”; just as it has been said above: “Today if YOU people listen to his own voice, do not harden YOUR hearts.”

[[v58-4-8]]

^<<v58-4-8,8>>^ For if Joshua^&#42;1^ had led them into a place of rest, &#91;God&#93;^&#42;2^ would not afterward have spoken of another day.

[NOTE]
====
. “Jehoshua,” J17,​18,​22; P46אABVg, “Jesus”; Syp, “Jeshu-bar-Nun (Jesus son of Nun).” See Jos 1:1 ftn, “Joshua.”
. Lit., “he.”
====

[[v58-4-9]]

^<<v58-4-9,9>>^ So there remains a sabbath resting for the people of God.

[[v58-4-10]]

^<<v58-4-10,10>>^ For the man that has entered into &#91;God’s&#93;^&#42;1^ rest has also himself rested from his own works, just as God did from his own.

[NOTE]
====
. Lit., “his.”
====

[[v58-4-11]]

^<<v58-4-11,11>>^ Let us therefore do our utmost to enter into that rest, for fear anyone should fall in the same pattern of disobedience.

[[v58-4-12]]

^<<v58-4-12,12>>^ For the word of God is alive and exerts power^&#42;1^ and is sharper than any two-edged sword and pierces even to the dividing of soul and spirit, and of joints and &#91;their&#93; marrow, and &#91;is&#93; able to discern^&#42;2^ thoughts and intentions^&#42;3^ of &#91;the&#93; heart.

[NOTE]
====
. “Exerts power.” Lit., “energetic.” Gr., e·ner·gesʹ.
. “Able to discern.” Lit., “judger.” Gr., kri·ti·kosʹ.
. “Intentions.” Lit., “mental inclinations.”
====

[[v58-4-13]]

^<<v58-4-13,13>>^ And there is not a creation that is not manifest to his sight, but all things are naked and openly exposed to the eyes of him with whom we have an accounting.

[[v58-4-14]]

^<<v58-4-14,14>>^ Seeing, therefore, that we have a great high priest who has passed through the heavens, Jesus the Son of God, let us hold onto &#91;our&#93; confessing of &#91;him&#93;.

[[v58-4-15]]

^<<v58-4-15,15>>^ For we have as high priest,^&#42;1^ not one who cannot sympathize with our weaknesses, but one who has been tested in all respects like ourselves, but without sin.

[NOTE]
====
. “High priest.” Gr., ar·khi·e·reʹa; Lat., pon·tiʹfi·cem, “pontifex”; J17,​22(Heb.), ko·henʹ ga·dhohlʹ.
====

[[v58-4-16]]

^<<v58-4-16,16>>^ Let us, therefore, approach with freeness of speech to the throne of undeserved kindness, that we may obtain mercy and find undeserved kindness for help at the right time.

'''

xref:058-hebrews/058-hebrews-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebrews/058-hebrews-005.adoc#v58-5-0[Próximo Capítulo &#62;]