include::./index.adoc[]

[[v58-5-0]]
=== To the Hebrews, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-5-1]]

^<<v58-5-1,1>>^ For every high priest taken from among men is appointed in behalf of men over the things pertaining to God, that he may offer gifts and sacrifices for sins.

[[v58-5-2]]

^<<v58-5-2,2>>^ He is able to deal moderately with the ignorant and erring ones since he also is surrounded with his own weakness,

[[v58-5-3]]

^<<v58-5-3,3>>^ and on its account he is obliged to make offerings for sins as much for himself as for the people.

[[v58-5-4]]

^<<v58-5-4,4>>^ Also, a man takes this honor, not of his own accord, but only when he is called by God, just as Aaron also &#91;was&#93;.

[[v58-5-5]]

^<<v58-5-5,5>>^ So too the Christ did not glorify himself by becoming a high priest, but &#91;was glorified by him&#93; who spoke with reference to him: “You are my son; I, today, I have become your father.”

[[v58-5-6]]

^<<v58-5-6,6>>^ Just as he says also in another place: “You are a priest forever according to the manner^&#42;1^ of Mel·chizʹe·dek.”

[NOTE]
====
. Lit., “the lineup [fashion].”
====

[[v58-5-7]]

^<<v58-5-7,7>>^ In the days of his flesh &#91;Christ&#93; offered up supplications and also petitions to the One who was able to save him out of death, with strong outcries and tears, and he was favorably heard for his godly fear.

[[v58-5-8]]

^<<v58-5-8,8>>^ Although he was a Son, he learned obedience from the things he suffered;

[[v58-5-9]]

^<<v58-5-9,9>>^ and after he had been made perfect^&#42;1^ he became responsible for everlasting salvation to all those obeying him,

[NOTE]
====
. Or, “after he had been inaugurated (installed; empowered; consecrated to office).” Gr., te·lei·o·theisʹ. See Le 21:10 ftn. Compare Le 8:33 ftn.
====

[[v58-5-10]]

^<<v58-5-10,10>>^ because he has been specifically called by God a high priest according to the manner of Mel·chizʹe·dek.

[[v58-5-11]]

^<<v58-5-11,11>>^ Concerning him we have much to say and hard to be explained,^&#42;1^ since YOU have become dull in YOUR hearing.

[NOTE]
====
. Lit., “hard to interpret.”
====

[[v58-5-12]]

^<<v58-5-12,12>>^ For, indeed, although YOU ought to be teachers in view of the time, YOU again need someone to teach YOU from the beginning the elementary things of the sacred pronouncements of God; and YOU have become such as need milk, not solid food.^&#42;1^

[NOTE]
====
. Lit., “nourishment.”
====

[[v58-5-13]]

^<<v58-5-13,13>>^ For everyone that partakes of milk is unacquainted with the word of righteousness, for he is a babe.

[[v58-5-14]]

^<<v58-5-14,14>>^ But solid food belongs to mature people, to those who through use have their perceptive powers^&#42;1^ trained^&#42;2^ to distinguish both right and wrong.

[NOTE]
====
. Lit., “sense organs.”
. Lit., “having been trained (like gymnast).” Gr., ge·gy·mna·smeʹna.
====

'''

xref:058-hebrews/058-hebrews-004.adoc#v58-4-0[&#60; Capítulo Anterior] | <<v58-5-0,Topo>> | xref:058-hebrews/058-hebrews-006.adoc#v58-6-0[Próximo Capítulo &#62;]