include::./index.adoc[]

[[v58-2-0]]
=== To the Hebrews, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-2-1]]

^<<v58-2-1,1>>^ That is why it is necessary for us to pay more than the usual attention to^&#42;1^ the things heard by us, that we may never drift away.

[NOTE]
====
. Lit., “more abundantly to be having [mind] toward.”
====

[[v58-2-2]]

^<<v58-2-2,2>>^ For if the word spoken through angels proved to be firm, and every transgression and disobedient act received a retribution^&#42;1^ in harmony with justice;

[NOTE]
====
. Lit., “paying back of reward.”
====

[[v58-2-3]]

^<<v58-2-3,3>>^ how shall we escape if we have neglected^&#42;1^ a salvation of such greatness in that it began to be spoken through &#91;our&#93; Lord and was verified for us by those who heard him,

[NOTE]
====
. Lit., “having been unconcerned.”
====

[[v58-2-4]]

^<<v58-2-4,4>>^ while God joined in bearing witness with signs as well as portents and various powerful works^&#42;1^ and with distributions of holy spirit according to his will?

[NOTE]
====
. Or, “various miracles.”
====

[[v58-2-5]]

^<<v58-2-5,5>>^ For it is not to angels that he has subjected the inhabited earth^&#42;1^ to come, about which we are speaking.

[NOTE]
====
. Lit., “inhabited.” Gr., oi·kou·meʹnen, fem. sing., referring to the earth; Lat., orʹbem terʹrae, “circle of the earth.” Compare Isa 13:11 ftn, “Land.”
====

[[v58-2-6]]

^<<v58-2-6,6>>^ But a certain witness has given proof somewhere, saying: “What is man that you keep him in mind,^&#42;1^ or &#91;the&#93; son of man that you take care of him?

[NOTE]
====
. Lit., “you are remembering.”
====

[[v58-2-7]]

^<<v58-2-7,7>>^ You made him a little^&#42;1^ lower than angels; with glory and honor you crowned him, and appointed him over the works of your hands.^&#42;2^

[NOTE]
====
. Or, “for a little while.”
. “And appointed him over the works of your hands,” אACD*VgSyp and Ps 8:6; P46BDc omit.
====

[[v58-2-8]]

^<<v58-2-8,8>>^ All things you subjected under his feet.” For in that he subjected all things to him &#91;God&#93;^&#42;1^ left nothing that is not subject to him. Now, though, we do not yet see all things in subjection to him;

[NOTE]
====
. Lit., “he.”
====

[[v58-2-9]]

^<<v58-2-9,9>>^ but we behold Jesus, who has been made a little^&#42;1^ lower than angels, crowned with glory and honor for having suffered death, that he by God’s undeserved kindness might taste death for every^&#42;2^ &#91;man&#93;.

[NOTE]
====
. Or, “for a little while.”
. Or, “every kind of.”
====

[[v58-2-10]]

^<<v58-2-10,10>>^ For it was fitting for the one for whose sake all things are and through whom all things are, in bringing many sons to glory, to make the Chief Agent^&#42;1^ of their salvation perfect through sufferings.

[NOTE]
====
. Lit., “Chief Leader.”
====

[[v58-2-11]]

^<<v58-2-11,11>>^ For both he who is sanctifying and those who are being sanctified^&#42;1^ all &#91;stem&#93; from one, and for this cause he is not ashamed to call them “brothers,”^&#42;2^

[NOTE]
====
. Or, “those who are held sacred (treated as holy).” Gr., hoi ha·gi·a·zoʹme·noi; Lat., qui sanc·ti·fi·canʹtur; J17,​22(Heb.), ham·qud·da·shimʹ.
. “Brothers.” Gr., a·del·phousʹ; Lat., fraʹtres; J17,​18,​22(Heb.), ʼa·chimʹ.
====

[[v58-2-12]]

^<<v58-2-12,12>>^ as he says: “I will declare your name to my brothers; in the middle of &#91;the&#93; congregation^&#42;1^ I will praise you with song.”

[NOTE]
====
. Lit., “of ecclesia.” Gr., ek·kle·siʹas; Lat., ec·cleʹsi·ae; J17,​18,​22(Heb.), qa·halʹ.
====

[[v58-2-13]]

^<<v58-2-13,13>>^ And again: “I will have my trust in him.” And again: “Look! I and the young children, whom Jehovah^&#42;1^ gave me.”

[NOTE]
====
. See App 1D.
====

[[v58-2-14]]

^<<v58-2-14,14>>^ Therefore, since the “young children” are sharers of blood and flesh, he also similarly partook of the same things, that through his death he might bring to nothing^&#42;1^ the one having the means to cause death, that is, the Devil;^&#42;2^

[NOTE]
====
. Or, “he might destroy (render inactive).”
. “Devil,” אABVg; SypJ17,​18,​22, “Satan.”
====

[[v58-2-15]]

^<<v58-2-15,15>>^ and &#91;that&#93; he might emancipate all those who for fear of death were subject to slavery all through their lives.

[[v58-2-16]]

^<<v58-2-16,16>>^ For he is really not assisting angels at all, but he is assisting Abraham’s seed.

[[v58-2-17]]

^<<v58-2-17,17>>^ Consequently he was obliged to become like his “brothers” in all respects, that he might become a merciful and faithful high priest^&#42;1^ in things pertaining to God, in order to offer propitiatory sacrifice^&#42;2^ for the sins of the people.

[NOTE]
====
. Lit., “chief priest.”
. Lit., “to be making propitiation.”
====

[[v58-2-18]]

^<<v58-2-18,18>>^ For in that he himself has suffered when being put to the test, he is able to come to the aid of those who are being put to the test.

'''

xref:058-hebrews/058-hebrews-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebrews/058-hebrews-003.adoc#v58-3-0[Próximo Capítulo &#62;]