include::./index.adoc[]

[[v58-13-0]]
=== To the Hebrews, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v58-13-1]]

^<<v58-13-1,1>>^ Let YOUR brotherly love continue.

[[v58-13-2]]

^<<v58-13-2,2>>^ Do not forget hospitality,^&#42;1^ for through it some, unknown to themselves, entertained^&#42;2^ angels.

[NOTE]
====
. Or, “kindness to strangers.”
. Lit., “having treated as strangers.”
====

[[v58-13-3]]

^<<v58-13-3,3>>^ Keep in mind those in prison bonds as though YOU have been bound with them, and those being ill-treated, since YOU yourselves also are still in a body.

[[v58-13-4]]

^<<v58-13-4,4>>^ Let marriage be honorable among all, and the marriage bed be without defilement, for God will judge fornicators and adulterers.^&#42;1^

[NOTE]
====
. “Adulterers.” Lat., a·dulʹte·ros.
====

[[v58-13-5]]

^<<v58-13-5,5>>^ Let &#91;YOUR&#93; manner of life be free of the love of money, while YOU are content with the present things. For he has said: “I will by no means leave you nor by any means forsake you.”

[[v58-13-6]]

^<<v58-13-6,6>>^ So that we may be of good courage and say: “Jehovah^&#42;1^ is my helper; I will not be afraid. What can^&#42;2^ man do to me?”

[NOTE]
====
. See App 1D.
. Lit., “will.”
====

[[v58-13-7]]

^<<v58-13-7,7>>^ Remember those who are taking the lead among YOU,^&#42;1^ who have spoken the word of God to YOU, and as YOU contemplate how &#91;their&#93; conduct turns out imitate &#91;their&#93; faith.

[NOTE]
====
. Or, “are governors of you.” Gr., he·gou·meʹnon hy·monʹ. See Mt 2:6 ftn, “Governors.”
====

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Christ is the same yesterday and today, and forever.

[[v58-13-9]]

^<<v58-13-9,9>>^ Do not be carried away with various and strange teachings; for it is fine for the heart to be given firmness^&#42;1^ by undeserved kindness, not by eatables, by which those who occupy themselves with them have not been benefited.

[NOTE]
====
. Lit., “to be stabilized.”
====

[[v58-13-10]]

^<<v58-13-10,10>>^ We have an altar from which those who do sacred service^&#42;1^ at the tent^&#42;2^ have no authority^&#42;3^ to eat.

[NOTE]
====
. “Do sacred service.” Gr., la·treuʹon·tes. Compare Ex 3:12 ftn.
. Or, “tabernacle.”
. “Authority.” D* omits.
====

[[v58-13-11]]

^<<v58-13-11,11>>^ For the bodies of those animals whose blood is taken into the holy place^&#42;1^ by the high priest for sin are burned up outside the camp.

[NOTE]
====
. Or, “places.”
====

[[v58-13-12]]

^<<v58-13-12,12>>^ Hence Jesus also, that he might sanctify the people with his own blood, suffered outside the gate.

[[v58-13-13]]

^<<v58-13-13,13>>^ Let us, then, go forth to him outside the camp, bearing the reproach he bore,^&#42;1^

[NOTE]
====
. Or, “reproach for him; his reproach.”
====

[[v58-13-14]]

^<<v58-13-14,14>>^ for we do not have here a city that continues, but we are earnestly seeking the one to come.

[[v58-13-15]]

^<<v58-13-15,15>>^ Through him let us always offer to God a sacrifice of praise, that is, the fruit of lips which make public declaration^&#42;1^ to his name.

[NOTE]
====
. Lit., “confessing.”
====

[[v58-13-16]]

^<<v58-13-16,16>>^ Moreover, do not forget the doing of good and the sharing of things with others, for with such sacrifices God is well pleased.

[[v58-13-17]]

^<<v58-13-17,17>>^ Be obedient to those who are taking the lead among YOU^&#42;1^ and be submissive,^&#42;2^ for they are keeping watch over YOUR souls as those who will render an account; that they may do this with joy and not with sighing, for this would be damaging to YOU.

[NOTE]
====
. Or, “are governors of you.” Gr., he·gou·meʹnois hy·monʹ. See Mt 2:6 ftn, “Governors.”
. Lit., “be you yielding under.”
====

[[v58-13-18]]

^<<v58-13-18,18>>^ Carry on prayer for us, for we trust we have an honest conscience, as we wish to conduct ourselves honestly in all things.

[[v58-13-19]]

^<<v58-13-19,19>>^ But I exhort YOU more especially to do this, that I may be restored to YOU the sooner.

[[v58-13-20]]

^<<v58-13-20,20>>^ Now may the God of peace, who brought up from the dead the great shepherd of the sheep with the blood of an everlasting covenant, our Lord Jesus,

[[v58-13-21]]

^<<v58-13-21,21>>^ equip YOU with every good thing to do his will, performing in us through Jesus Christ that which is well-pleasing in his sight; to whom be the glory forever and ever. Amen.

[[v58-13-22]]

^<<v58-13-22,22>>^ Now I exhort YOU, brothers, to bear with this word of encouragement, for I have, indeed, composed a letter to YOU in few words.

[[v58-13-23]]

^<<v58-13-23,23>>^ Take note that our brother Timothy has been released, with whom, if he comes quite soon,^&#42;1^ I shall see YOU.

[NOTE]
====
. Or, “comes more quickly [than I expected].”
====

[[v58-13-24]]

^<<v58-13-24,24>>^ Give my greetings to all those who are taking the lead among YOU^&#42;1^ and to all the holy ones. Those in^&#42;2^ Italy send YOU their greetings.

[NOTE]
====
. See vs 17 ftn, “You.”
. Or, “of.”
====

[[v58-13-25]]

^<<v58-13-25,25>>^ The undeserved kindness be with all of YOU.^&#42;1^

[NOTE]
====
. ACDItVgSyh,p add “Amen”; P46אArm omit.
====

'''

xref:058-hebrews/058-hebrews-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-james/059-james-001.adoc#v59-1-0[Próximo Capítulo &#62;]