include::./index.adoc[]

[[v42-5-0]]
=== According to Luke, 5
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-5-1]]

^<<v42-5-1,1>>^ On an occasion when the crowd was pressing close upon him and listening to the word of God, he was standing beside the lake of Gen·nesʹa·ret.

[[v42-5-2]]

^<<v42-5-2,2>>^ And he saw two boats docked at the lakeside, but the fishermen had got out of them and were washing off their nets.

[[v42-5-3]]

^<<v42-5-3,3>>^ Going aboard one of the boats, which was Simon’s, he asked him to pull away a bit from land. Then he sat down, and from the boat he began teaching the crowds.

[[v42-5-4]]

^<<v42-5-4,4>>^ When he ceased speaking, he said to Simon: “Pull out to where it is deep, and YOU men let down YOUR nets for a catch.”

[[v42-5-5]]

^<<v42-5-5,5>>^ But Simon in reply said: “Instructor, for a whole night we toiled and took nothing, but at your bidding I will lower the nets.”

[[v42-5-6]]

^<<v42-5-6,6>>^ Well, when they did this, they enclosed a great multitude of fish. In fact, their nets began ripping apart.

[[v42-5-7]]

^<<v42-5-7,7>>^ So they motioned to their partners in the other boat to come and assist them; and they did come, and they filled both boats, so that these began to sink.

[[v42-5-8]]

^<<v42-5-8,8>>^ Seeing this, Simon Peter fell down at the knees of Jesus, saying: “Depart from me, because I am a sinful man, Lord.”^&#42;1^

[NOTE]
====
. Or, “Master.”
====

[[v42-5-9]]

^<<v42-5-9,9>>^ For at the catch of fish which they took up astonishment overwhelmed him and all those with him,

[[v42-5-10]]

^<<v42-5-10,10>>^ and likewise both James and John, Zebʹe·dee’s sons, who were sharers with Simon. But Jesus said to Simon: “Stop being afraid. From now on you will be catching men alive.”

[[v42-5-11]]

^<<v42-5-11,11>>^ So they brought the boats back to land, and abandoned everything and followed him.

[[v42-5-12]]

^<<v42-5-12,12>>^ On a further occasion while he was in one of the cities, look! a man full of leprosy! When he caught sight of Jesus he fell upon his face and begged him, saying: “Lord, if you just want to, you can make me clean.”

[[v42-5-13]]

^<<v42-5-13,13>>^ And so, stretching out his hand, he touched him, saying: “I want to. Be made clean.” And immediately the leprosy vanished from him.

[[v42-5-14]]

^<<v42-5-14,14>>^ And he gave the man orders to tell nobody: “But go off and show yourself to the priest, and make an offering in connection with your cleansing, just as Moses directed, for a witness^&#42;1^ to them.”

[NOTE]
====
. “A witness.” Gr., mar·tyʹri·on; Lat., te·sti·moʹni·um.
====

[[v42-5-15]]

^<<v42-5-15,15>>^ But the word about him was spreading the more, and great crowds would come together to listen and to be cured of their sicknesses.

[[v42-5-16]]

^<<v42-5-16,16>>^ However, he continued in retirement in the deserts and praying.

[[v42-5-17]]

^<<v42-5-17,17>>^ In the course of one of the days he was teaching, and Pharisees and teachers of the law who had come out of every village of Galʹi·lee and Ju·deʹa and Jerusalem were sitting there; and Jehovah’s^&#42;1^ power was there for him to do healing.

[NOTE]
====
. See App 1D.
====

[[v42-5-18]]

^<<v42-5-18,18>>^ And, look! men carrying on a bed a man who was paralyzed, and they were seeking a way to bring him in and place him before him.

[[v42-5-19]]

^<<v42-5-19,19>>^ So, not finding a way to bring him in on account of the crowd, they climbed up to the roof, and through the tiling they let him down with the little bed among those in front of Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ And when he saw their faith he said: “Man, your sins are forgiven you.”

[[v42-5-21]]

^<<v42-5-21,21>>^ Thereupon the scribes and the Pharisees started to reason, saying: “Who is this that is speaking blasphemies? Who can forgive sins except God alone?”

[[v42-5-22]]

^<<v42-5-22,22>>^ But Jesus, discerning their reasonings, said in answer to them: “What are YOU reasoning out in YOUR hearts?

[[v42-5-23]]

^<<v42-5-23,23>>^ Which is easier, to say, ‘Your sins are forgiven you,’ or to say, ‘Get up and walk’?

[[v42-5-24]]

^<<v42-5-24,24>>^ But in order for YOU to know that the Son of man has authority on the earth to forgive sins—” he said to the paralyzed man: “I say to you, Get up and pick up your little bed and be on your way home.”

[[v42-5-25]]

^<<v42-5-25,25>>^ And instantly he rose up before them, picked up what he used to lie on and went off to his home, glorifying God.

[[v42-5-26]]

^<<v42-5-26,26>>^ Then an ecstasy seized one and all, and they began to glorify God, and they became filled with fear, saying: “We have seen strange things today!”

[[v42-5-27]]

^<<v42-5-27,27>>^ Now after these things he went out and beheld a tax collector named Leʹvi sitting at the tax office, and he said to him: “Be my follower.”

[[v42-5-28]]

^<<v42-5-28,28>>^ And leaving everything behind he rose up and went following him.

[[v42-5-29]]

^<<v42-5-29,29>>^ Also, Leʹvi spread a big reception feast for him in his house; and there was a great crowd of tax collectors and others who were with them reclining at the meal.

[[v42-5-30]]

^<<v42-5-30,30>>^ At this the Pharisees and their scribes began murmuring to his disciples, saying: “Why is it YOU eat and drink with tax collectors and sinners?”

[[v42-5-31]]

^<<v42-5-31,31>>^ In reply Jesus said to them: “Those who are healthy do not need a physician, but those who are ailing do.

[[v42-5-32]]

^<<v42-5-32,32>>^ I have come to call, not righteous persons, but sinners to repentance.”

[[v42-5-33]]

^<<v42-5-33,33>>^ They said to him: “The disciples of John fast frequently and offer supplications, and so do those of the Pharisees, but yours eat and drink.”

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus said to them: “YOU cannot make the friends of the bridegroom^&#42;1^ fast while the bridegroom is with them, can YOU?

[NOTE]
====
. Lit., “the sons of the bridechamber.”
====

[[v42-5-35]]

^<<v42-5-35,35>>^ Yet days will come when the bridegroom will indeed be taken away from them; then they will fast in those days.”

[[v42-5-36]]

^<<v42-5-36,36>>^ Further, he went on to give an illustration to them: “No one cuts a patch from a new outer garment and sews it onto an old outer garment; but if he does, then both the new patch tears away and the patch from the new garment does not match the old.

[[v42-5-37]]

^<<v42-5-37,37>>^ Moreover, no one puts new wine into old wineskins; but if he does, then the new wine will burst the wineskins, and it will be spilled out and the wineskins will be ruined.

[[v42-5-38]]

^<<v42-5-38,38>>^ But new wine must be put into new wineskins.

[[v42-5-39]]

^<<v42-5-39,39>>^ No one that has drunk old wine wants new; for he says, ‘The old is nice.’”^&#42;1^

[NOTE]
====
. “Nice,” אBSyp; ACVg, “nicer.”
====

'''

xref:042-luke/042-luke-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-luke/042-luke-006.adoc#v42-6-0[Próximo Capítulo &#62;]