include::./index.adoc[]

[[v42-7-0]]
=== According to Luke, 7
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-7-1]]

^<<v42-7-1,1>>^ When he had completed all his sayings in the hearing of the people, he entered into Ca·perʹna·um.

[[v42-7-2]]

^<<v42-7-2,2>>^ Now a certain army officer’s^&#42;1^ slave, who was dear to him, was ailing and was about to pass away.

[NOTE]
====
. Or, “centurion’s.” Lat., cen·tu·ri·oʹnis. A centurion was a commander of 100 soldiers.
====

[[v42-7-3]]

^<<v42-7-3,3>>^ When he heard about Jesus, he sent forth older men of the Jews to him to ask him to come and bring his slave safely through.

[[v42-7-4]]

^<<v42-7-4,4>>^ Then those that came up to Jesus began to entreat him earnestly,^&#42;1^ saying: “He is worthy of your conferring this upon him,

[NOTE]
====
. Or, “with haste.”
====

[[v42-7-5]]

^<<v42-7-5,5>>^ for he loves our nation and he himself built the synagogue for us.”

[[v42-7-6]]

^<<v42-7-6,6>>^ So Jesus started off with them. But when he was not far from the house, the army officer had already sent friends to say to him: “Sir, do not bother, for I am not fit to have you come in under my roof.

[[v42-7-7]]

^<<v42-7-7,7>>^ For that reason I did not consider myself worthy to come to you. But say the word, and let my servant be healed.

[[v42-7-8]]

^<<v42-7-8,8>>^ For I too am a man placed under authority, having soldiers under me, and I say to this one, ‘Be on your way!’ and he is on his way, and to another, ‘Come!’ and he comes, and to my slave, ‘Do this!’ and he does it.”

[[v42-7-9]]

^<<v42-7-9,9>>^ Well, when Jesus heard these things he marveled at him, and he turned to the crowd following him and said: “I tell YOU, Not even in Israel have I found so great a faith.”

[[v42-7-10]]

^<<v42-7-10,10>>^ And those that had been sent, on getting back to the house, found the slave in good health.

[[v42-7-11]]

^<<v42-7-11,11>>^ Closely following this^&#42;1^ he traveled to a city called Naʹin, and his disciples and a great crowd were traveling with him.

[NOTE]
====
. “Closely following this,” P75אcAB; א*CD, “On the following day.”
====

[[v42-7-12]]

^<<v42-7-12,12>>^ As he got near the gate of the city, why, look! there was a dead man being carried out, the only-begotten^&#42;1^ son of his mother. Besides, she was a widow. A considerable crowd from the city was also with her.

[NOTE]
====
. Or, “the only.” Gr., mo·no·ge·nesʹ. See 8:42 ftn.
====

[[v42-7-13]]

^<<v42-7-13,13>>^ And when the Lord^&#42;1^ caught sight of her, he was moved with pity for her, and he said to her: “Stop weeping.”

[NOTE]
====
. Or, “Master.”
====

[[v42-7-14]]

^<<v42-7-14,14>>^ With that he approached and touched the bier, and the bearers stood still, and he said: “Young man, I say to you, Get up!”^&#42;1^

[NOTE]
====
. Or, “Wake up!”
====

[[v42-7-15]]

^<<v42-7-15,15>>^ And the dead man sat up and started to speak, and he gave him to his mother.

[[v42-7-16]]

^<<v42-7-16,16>>^ Now fear seized them all, and they began to glorify God, saying: “A great prophet has been raised up among us,” and, “God has turned his attention to his people.”

[[v42-7-17]]

^<<v42-7-17,17>>^ And this news concerning him spread out into all Ju·deʹa and all the surrounding country.

[[v42-7-18]]

^<<v42-7-18,18>>^ Now John’s disciples reported to him about all these things.

[[v42-7-19]]

^<<v42-7-19,19>>^ So John summoned a certain two of his disciples and sent them to the Lord^&#42;1^ to say: “Are you the Coming One or are we to expect a different one?”^&#42;2^

[NOTE]
====
. Or, “Master.”
. “A different one,” אB; AD, “another.”
====

[[v42-7-20]]

^<<v42-7-20,20>>^ When they came up to him the men said: “John the Baptist dispatched us to you to say, ‘Are you the Coming One or are we to expect another?’”^&#42;1^

[NOTE]
====
. “Another,” P75AB; אD, “a different one.”
====

[[v42-7-21]]

^<<v42-7-21,21>>^ In that hour he cured many of sicknesses and grievous diseases and wicked spirits, and granted many blind persons the favor of seeing.

[[v42-7-22]]

^<<v42-7-22,22>>^ Hence in answer he said to the &#91;two&#93;: “Go YOUR way, report to John what YOU saw and heard: the blind are receiving sight, the lame are walking, the lepers are being cleansed and the deaf are hearing, the dead are being raised up, the poor are being told the good news.

[[v42-7-23]]

^<<v42-7-23,23>>^ And happy is he who has not stumbled over me.”

[[v42-7-24]]

^<<v42-7-24,24>>^ When the messengers of John had gone away, he started to say to the crowds concerning John: “What did YOU go out into the wilderness to behold? A reed being tossed by the wind?

[[v42-7-25]]

^<<v42-7-25,25>>^ What, then, did YOU go out to see? A man dressed in soft outer garments? Why, those in splendid dress and existing in luxury are in royal houses.

[[v42-7-26]]

^<<v42-7-26,26>>^ Really, then, what did YOU go out to see? A prophet? Yes, I tell YOU, and far more than a prophet.

[[v42-7-27]]

^<<v42-7-27,27>>^ This is he concerning whom it is written, ‘Look! I am sending forth my messenger before your face, who will prepare your way ahead of you.’

[[v42-7-28]]

^<<v42-7-28,28>>^ I tell YOU, Among those born of women there is none greater than John; but a person that is a lesser one in the kingdom of God is greater than he is.”

[[v42-7-29]]

^<<v42-7-29,29>>^ (And all the people and the tax collectors, when they heard &#91;this&#93;,^&#42;1^ declared God to be righteous, they having been baptized with the baptism^&#42;2^ of John.

[NOTE]
====
. Or, “him.”
. Or, “immersion; dipping.” Gr., baʹpti·sma.
====

[[v42-7-30]]

^<<v42-7-30,30>>^ But the Pharisees and those versed in the Law disregarded the counsel of God to them, they not having been baptized by him.)

[[v42-7-31]]

^<<v42-7-31,31>>^ “With whom, therefore, shall I compare the men of this generation, and whom are they like?

[[v42-7-32]]

^<<v42-7-32,32>>^ They are like young children sitting in a marketplace and crying out to one another, and who say, ‘We played the flute for YOU, but YOU did not dance; we wailed, but YOU did not weep.’

[[v42-7-33]]

^<<v42-7-33,33>>^ Correspondingly, John the Baptist has come neither eating bread nor drinking wine, but YOU say, ‘He has a demon.’

[[v42-7-34]]

^<<v42-7-34,34>>^ The Son of man has come eating and drinking, but YOU say, ‘Look! A man gluttonous and given to drinking wine, a friend of tax collectors and sinners!’

[[v42-7-35]]

^<<v42-7-35,35>>^ All the same, wisdom is proved righteous by all its children.”

[[v42-7-36]]

^<<v42-7-36,36>>^ Now a certain one of the Pharisees kept asking him to dine with him. Accordingly he entered into the house of the Pharisee and reclined at the table.

[[v42-7-37]]

^<<v42-7-37,37>>^ And, look! a woman who was known in the city to be a sinner learned that he was reclining at a meal in the house of the Pharisee, and she brought an alabaster case of perfumed oil,

[[v42-7-38]]

^<<v42-7-38,38>>^ and, taking a position behind at his feet, she wept and started to wet his feet with her tears and she would wipe them off with the hair of her head. Also, she tenderly kissed his feet and greased them with the perfumed oil.

[[v42-7-39]]

^<<v42-7-39,39>>^ At the sight the Pharisee that invited him said within himself: “This man, if he were a prophet, would know who and what kind of woman it is that is touching him, that she is a sinner.”

[[v42-7-40]]

^<<v42-7-40,40>>^ But in reply Jesus said to him: “Simon, I have something to say to you.” He said: “Teacher, say it!”

[[v42-7-41]]

^<<v42-7-41,41>>^ “Two men were debtors to a certain lender; the one was in debt for five hundred de·narʹi·i,^&#42;1^ but the other for fifty.

[NOTE]
====
. A denarius was a Roman silver coin that weighed 3.85 g (0.124 oz t).
====

[[v42-7-42]]

^<<v42-7-42,42>>^ When they did not have anything with which to pay back, he freely forgave them both. Therefore, which of them will love him the more?”

[[v42-7-43]]

^<<v42-7-43,43>>^ In answer Simon said: “I suppose it is the one to whom he freely forgave the more.” He said to him: “You judged correctly.”

[[v42-7-44]]

^<<v42-7-44,44>>^ With that he turned to the woman and said to Simon: “Do you behold this woman? I entered into your house; you gave me no water for my feet. But this woman wet my feet with her tears and wiped them off with her hair.

[[v42-7-45]]

^<<v42-7-45,45>>^ You gave me no kiss; but this woman, from the hour that I came in, did not leave off tenderly kissing my feet.

[[v42-7-46]]

^<<v42-7-46,46>>^ You did not grease my head with oil; but this woman greased my feet with perfumed oil.

[[v42-7-47]]

^<<v42-7-47,47>>^ By virtue of this, I tell you, her sins, many though they are, are forgiven, because she loved much; but he who is forgiven little, loves little.”

[[v42-7-48]]

^<<v42-7-48,48>>^ Then he said to her: “Your sins are forgiven.”

[[v42-7-49]]

^<<v42-7-49,49>>^ At this those reclining at the table with him started to say within themselves: “Who is this man who even forgives sins?”

[[v42-7-50]]

^<<v42-7-50,50>>^ But he said to the woman: “Your faith has saved you; go your way in peace.”

'''

xref:042-luke/042-luke-006.adoc#v42-6-0[&#60; Capítulo Anterior] | <<v42-7-0,Topo>> | xref:042-luke/042-luke-008.adoc#v42-8-0[Próximo Capítulo &#62;]