include::./index.adoc[]

[[v42-24-0]]
=== According to Luke, 24
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-24-1]]

^<<v42-24-1,1>>^ On the first day of the week, however, they went very early to the tomb, bearing the spices they had prepared.

[[v42-24-2]]

^<<v42-24-2,2>>^ But they found the stone rolled away from the memorial tomb,

[[v42-24-3]]

^<<v42-24-3,3>>^ and when they entered they did not find the body of the Lord Jesus.^&#42;1^

[NOTE]
====
. “Of the Lord Jesus,” P75אABCWVgSyArm; DItmss omit.
====

[[v42-24-4]]

^<<v42-24-4,4>>^ While they were in perplexity over this, look! two men in flashing clothing stood by them.

[[v42-24-5]]

^<<v42-24-5,5>>^ As the &#91;women&#93; became frightened and kept their faces turned to the ground, the &#91;men&#93; said to them: “Why are YOU looking for the living One among the dead?

[[v42-24-6]]

^<<v42-24-6,6>>^ &#91;&#91;He is not here, but has been raised up.&#93;&#93;^&#42;1^ Recall how he spoke to YOU while he was yet in Galʹi·lee,

[NOTE]
====
. “He is not here, but has been raised up,” P75אABVgSyArm; DItmss omit.
====

[[v42-24-7]]

^<<v42-24-7,7>>^ saying that the Son of man must be delivered into the hands of sinful men and be impaled^&#42;1^ and yet on the third day rise.”

[NOTE]
====
. Or, “fastened on a stake (pole).” See App 5C.
====

[[v42-24-8]]

^<<v42-24-8,8>>^ So they called his sayings to mind,

[[v42-24-9]]

^<<v42-24-9,9>>^ and they returned from the memorial tomb^&#42;1^ and reported all these things to the eleven and to all the rest.

[NOTE]
====
. “From the memorial tomb,” P75אABWVgSy; DItmssArm omit.
====

[[v42-24-10]]

^<<v42-24-10,10>>^ They were the Magʹda·lene Mary, and Jo·anʹna, and Mary the &#91;mother&#93; of James. Also, the rest of the women with them were telling the apostles these things.

[[v42-24-11]]

^<<v42-24-11,11>>^ However, these sayings appeared as nonsense to them and they would not believe the &#91;women&#93;.

[[v42-24-12]]

^<<v42-24-12,12>>^ &#91;&#91;But Peter rose and ran to the memorial tomb, and, stooping forward, he beheld the bandages alone. So he went off, wondering within himself at what had occurred.&#93;&#93;^&#42;1^

[NOTE]
====
. According to P75אABWVgSy; DItmss omit these bracketed words.
====

[[v42-24-13]]

^<<v42-24-13,13>>^ But, look! on that very day two of them were journeying to a village about seven miles^&#42;1^ distant from Jerusalem &#91;and&#93; named Em·maʹus,

[NOTE]
====
. Or, “seven and a half [Roman] miles.” Lit., “sixty stadia.” Gr., sta·diʹous he·xeʹkon·ta; Lat., sta·di·oʹrum se·xa·ginʹta; about 11 km. Mt 5:41 ftn; see App 8A.
====

[[v42-24-14]]

^<<v42-24-14,14>>^ and they were conversing with each other over all these things that had come about.

[[v42-24-15]]

^<<v42-24-15,15>>^ Now as they were conversing and discussing, Jesus himself approached and began walking with them;

[[v42-24-16]]

^<<v42-24-16,16>>^ but their eyes were kept from recognizing him.

[[v42-24-17]]

^<<v42-24-17,17>>^ He said to them: “What are these matters that YOU are debating between yourselves as YOU walk along?” And they stood still with sad faces.

[[v42-24-18]]

^<<v42-24-18,18>>^ In answer the one named Cleʹo·pas said to him: “Are you dwelling as an alien by yourself in Jerusalem and so do not know the things that have occurred in her in these days?”

[[v42-24-19]]

^<<v42-24-19,19>>^ And he said to them: “What things?” They said to him: “The things concerning Jesus the Naz·a·reneʹ, who became a prophet powerful in work and word before God and all the people;

[[v42-24-20]]

^<<v42-24-20,20>>^ and how our chief priests and rulers handed him over to the sentence of death and impaled him.

[[v42-24-21]]

^<<v42-24-21,21>>^ But we were hoping that this &#91;man&#93; was the one destined to deliver Israel; yes, and besides all these things, this makes the third day since these things occurred.

[[v42-24-22]]

^<<v42-24-22,22>>^ Moreover, certain women from among us also astonished us, because they had been early to the memorial tomb

[[v42-24-23]]

^<<v42-24-23,23>>^ but did not find his body and they came saying they had also seen a supernatural sight of angels, who said he is alive.

[[v42-24-24]]

^<<v42-24-24,24>>^ Further, some of those with us went off to the memorial tomb; and they found it so, just as the women had said, but they did not see him.”

[[v42-24-25]]

^<<v42-24-25,25>>^ So he said to them: “O senseless ones and slow in heart to believe on all the things the prophets spoke!

[[v42-24-26]]

^<<v42-24-26,26>>^ Was it not necessary for the Christ to suffer these things and to enter into his glory?”

[[v42-24-27]]

^<<v42-24-27,27>>^ And commencing at Moses and all the Prophets he interpreted to them things pertaining to himself in all the Scriptures.

[[v42-24-28]]

^<<v42-24-28,28>>^ Finally they got close to the village where they were journeying, and he made as if he was journeying on farther.

[[v42-24-29]]

^<<v42-24-29,29>>^ But they used pressure upon him, saying: “Stay with us, because it is toward evening and the day has already declined.” With that he went in to stay with them.

[[v42-24-30]]

^<<v42-24-30,30>>^ And as he was reclining with them at the meal he took the loaf, blessed it, broke it and began to hand it to them.

[[v42-24-31]]

^<<v42-24-31,31>>^ At that their eyes were fully opened and they recognized him; and he disappeared from them.

[[v42-24-32]]

^<<v42-24-32,32>>^ And they said to each other: “Were not our hearts burning^&#42;1^ as he was speaking to us on the road, as he was fully opening up the Scriptures to us?”

[NOTE]
====
. “Burning,” אAB; D, “veiled”; Syp,s, “heavy”; Itms l, “dull”; Itms c, “blinded.”
====

[[v42-24-33]]

^<<v42-24-33,33>>^ And in that very hour they rose and returned to Jerusalem, and they found the eleven and those with them assembled together,

[[v42-24-34]]

^<<v42-24-34,34>>^ saying: “For a fact the Lord^&#42;1^ was raised up and he appeared to Simon!”

[NOTE]
====
. Or, “Master.”
====

[[v42-24-35]]

^<<v42-24-35,35>>^ Now they themselves related the &#91;events&#93; on the road and how he became known to them by the breaking of the loaf.

[[v42-24-36]]

^<<v42-24-36,36>>^ While they were speaking of these things he himself stood in their midst &#91;&#91;and said to them: “May YOU have peace.”&#93;&#93;^&#42;1^

[NOTE]
====
. “And said . . . peace,” P75אAB; DIt omit.
====

[[v42-24-37]]

^<<v42-24-37,37>>^ But because they were terrified, and had become frightened, they were imagining they beheld a spirit.

[[v42-24-38]]

^<<v42-24-38,38>>^ So he said to them: “Why are YOU troubled, and why is it doubts come up in YOUR hearts?

[[v42-24-39]]

^<<v42-24-39,39>>^ See my hands and my feet, that it is I myself; feel me and see, because a spirit does not have flesh and bones just as YOU behold that I have.”

[[v42-24-40]]

^<<v42-24-40,40>>^ &#91;&#91;And as he said this he showed them his hands and his feet.&#93;&#93;^&#42;1^

[NOTE]
====
. According to P75אABWVgSyh,hi,pArm (compare Joh 20:20); DItSyc,s omit vs 40.
====

[[v42-24-41]]

^<<v42-24-41,41>>^ But while they were still not believing for sheer joy and were wondering, he said to them: “Do YOU have something there to eat?”

[[v42-24-42]]

^<<v42-24-42,42>>^ And they handed him a piece of broiled fish;^&#42;1^

[NOTE]
====
. VgSyc,p and mss ENXΔΘ (sixth to tenth cent.) add, “and a honeycomb”; P75אABDSys omit.
====

[[v42-24-43]]

^<<v42-24-43,43>>^ and he took it and ate it before their eyes.

[[v42-24-44]]

^<<v42-24-44,44>>^ He now said to them: “These are my words which I spoke to YOU while I was yet with YOU, that all the things written in the law of Moses and in the Prophets and Psalms about me must be fulfilled.”

[[v42-24-45]]

^<<v42-24-45,45>>^ Then he opened up their minds fully to grasp the meaning of the Scriptures,

[[v42-24-46]]

^<<v42-24-46,46>>^ and he said to them: “In this way it is written that the Christ would suffer and rise from among the dead on the third day,

[[v42-24-47]]

^<<v42-24-47,47>>^ and on the basis of his name repentance for forgiveness of sins would be preached in all the nations—starting out from Jerusalem,

[[v42-24-48]]

^<<v42-24-48,48>>^ YOU are to be witnesses of these things.

[[v42-24-49]]

^<<v42-24-49,49>>^ And, look! I am sending forth upon YOU that which is promised by my Father. YOU, though, abide in the city until YOU become clothed with power from on high.”

[[v42-24-50]]

^<<v42-24-50,50>>^ But he led them out as far as Bethʹa·ny, and he lifted up his hands and blessed them.

[[v42-24-51]]

^<<v42-24-51,51>>^ As he was blessing them he was parted from them and began to be borne up to heaven.^&#42;1^

[NOTE]
====
. “And began to be borne up to heaven,” P75אcABCWVgSypArm; א*DSys omit.
====

[[v42-24-52]]

^<<v42-24-52,52>>^ And they did obeisance to him and^&#42;1^ returned to Jerusalem with great joy.

[NOTE]
====
. “Did obeisance to him and,” P75אABCWSyh,p; DItmssSys omit. Compare Heb 1:6.
====

[[v42-24-53]]

^<<v42-24-53,53>>^ And they were continually in the temple blessing God.

'''

xref:042-luke/042-luke-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-john/043-john-001.adoc#v43-1-0[Próximo Capítulo &#62;]