include::./index.adoc[]

[[v42-3-0]]
=== According to Luke, 3
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-3-1]]

^<<v42-3-1,1>>^ In the fifteenth year of the reign of Ti·beʹri·us Caesar,^&#42;1^ when Pontius Pilate was governor of Ju·deʹa, and Herod^&#42;2^ was district ruler^&#42;3^ of Galʹi·lee, but Philip his brother was district ruler of the country of It·u·raeʹa and Trach·o·niʹtis, and Ly·saʹni·as was district ruler of Ab·i·leʹne,

[NOTE]
====
. Or, “the emperor.” Gr., Kaiʹsa·ros; Lat., Caeʹsa·ris.
. That is, Herod Antipas, son of Herod the Great.
. “District ruler.” Lit., “tetrarch”; a territorial prince for the Roman emperor. Lat., te·trarʹcha.
====

[[v42-3-2]]

^<<v42-3-2,2>>^ in the days of chief priest Anʹnas and of Caʹia·phas, God’s declaration came to John the son of Zech·a·riʹah in the wilderness.

[[v42-3-3]]

^<<v42-3-3,3>>^ So he came into all the country around the Jordan, preaching baptism &#91;in symbol&#93; of repentance for forgiveness of sins,

[[v42-3-4]]

^<<v42-3-4,4>>^ just as it is written in the book of the words of Isaiah the prophet: “Listen! Someone is crying out in the wilderness, ‘Prepare the way of Jehovah,^&#42;1^ YOU people, make his roads straight.

[NOTE]
====
. See App 1D.
====

[[v42-3-5]]

^<<v42-3-5,5>>^ Every gully must be filled up, and every mountain and hill leveled down, and the curves must become straight ways and the rough places smooth ways;

[[v42-3-6]]

^<<v42-3-6,6>>^ and all flesh will see the saving means of God.’”

[[v42-3-7]]

^<<v42-3-7,7>>^ Therefore he began to say to the crowds coming out to be baptized by him: “YOU offspring of vipers, who has intimated to YOU to flee from the coming wrath?

[[v42-3-8]]

^<<v42-3-8,8>>^ Therefore produce fruits that befit repentance.^&#42;1^ And do not start saying within yourselves, ‘As a father we have Abraham.’ For I say to YOU that God has power to raise up children to Abraham from these stones.

[NOTE]
====
. Lit., “change of mind.” Gr., me·ta·noiʹas.
====

[[v42-3-9]]

^<<v42-3-9,9>>^ Indeed, the ax is already in position at the root of the trees; every tree, therefore, not producing fine fruit is to be cut down and thrown into the fire.”

[[v42-3-10]]

^<<v42-3-10,10>>^ And the crowds would ask him: “What, then, shall we do?”

[[v42-3-11]]

^<<v42-3-11,11>>^ In reply he would say to them: “Let the man that has two undergarments share with the man that has none, and let him that has things to eat do the same.”

[[v42-3-12]]

^<<v42-3-12,12>>^ But even tax collectors came to be baptized, and they said to him: “Teacher, what shall we do?”

[[v42-3-13]]

^<<v42-3-13,13>>^ He said to them: “Do not demand anything more than the tax rate.”

[[v42-3-14]]

^<<v42-3-14,14>>^ Also, those in military service would ask him: “What shall we also do?” And he said to them: “Do not harass anybody or accuse anybody falsely, but be satisfied with YOUR provisions.”^&#42;1^

[NOTE]
====
. Or, “wages.”
====

[[v42-3-15]]

^<<v42-3-15,15>>^ Now as the people were in expectation and all were reasoning in their hearts about John: “May he perhaps be the Christ?”

[[v42-3-16]]

^<<v42-3-16,16>>^ John gave the answer, saying to all: “I, for my part, baptize YOU with water; but the one stronger than I am is coming, the lace of whose sandals I am not fit to untie. He will baptize YOU people with holy spirit and fire.

[[v42-3-17]]

^<<v42-3-17,17>>^ His winnowing shovel is in his hand to clean up his threshing floor completely and to gather the wheat into his storehouse, but the chaff he will burn up with fire that cannot be put out.”

[[v42-3-18]]

^<<v42-3-18,18>>^ Therefore he also gave many other exhortations and continued declaring good news to the people.

[[v42-3-19]]

^<<v42-3-19,19>>^ But Herod the district ruler,^&#42;1^ for being reproved by him concerning He·roʹdi·as the wife of his brother and concerning all the wicked deeds that Herod did,

[NOTE]
====
. See vs 1 ftn, “Ruler.”
====

[[v42-3-20]]

^<<v42-3-20,20>>^ added also this to all those &#91;deeds&#93;: he locked John up in prison.

[[v42-3-21]]

^<<v42-3-21,21>>^ Now when all the people were baptized, Jesus also was baptized^&#42;1^ and, as he was praying, the heaven was opened up

[NOTE]
====
. Or, “was immersed; was dipped.” Gr., ba·pti·sthenʹtos.
====

[[v42-3-22]]

^<<v42-3-22,22>>^ and the holy spirit in bodily shape like a dove came down upon him, and a voice came out of heaven: “You are my Son, the beloved; I have approved you.”

[[v42-3-23]]

^<<v42-3-23,23>>^ Furthermore, Jesus himself, when he commenced &#91;his work&#93;,^&#42;1^ was about thirty years old, being the son, as the opinion was,^&#42;2^
of Joseph,
&#91;son&#93; of Heʹli,

[NOTE]
====
. Or, “commenced [to teach].”
. Or, “as it was established by law.”
====

[[v42-3-24]]

^<<v42-3-24,24>>^ &#91;son&#93; of Matʹthat,
&#91;son&#93; of Leʹvi,
&#91;son&#93; of Melʹchi,
&#91;son&#93; of Janʹna·i,
&#91;son&#93; of Joseph,

[[v42-3-25]]

^<<v42-3-25,25>>^ &#91;son&#93; of Mat·ta·thiʹas,
&#91;son&#93; of Aʹmos,
&#91;son&#93; of Naʹhum,
&#91;son&#93; of Esʹli,
&#91;son&#93; of Nagʹga·i,

[[v42-3-26]]

^<<v42-3-26,26>>^ &#91;son&#93; of Maʹath,
&#91;son&#93; of Mat·ta·thiʹas,
&#91;son&#93; of Semʹe·in,
&#91;son&#93; of Joʹsech,
&#91;son&#93; of Joʹda,

[[v42-3-27]]

^<<v42-3-27,27>>^ &#91;son&#93; of Jo·anʹan,
&#91;son&#93; of Rheʹsa,
&#91;son&#93; of Ze·rubʹba·bel,
&#91;son&#93; of She·alʹti·el,^&#42;1^
&#91;son&#93; of Neʹri,

[NOTE]
====
. Lit., “Salathiel.”
====

[[v42-3-28]]

^<<v42-3-28,28>>^ &#91;son&#93; of Melʹchi,
&#91;son&#93; of Adʹdi,
&#91;son&#93; of Coʹsam,
&#91;son&#93; of El·maʹdam,
&#91;son&#93; of Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ &#91;son&#93; of Jesus,^&#42;1^
&#91;son&#93; of E·li·eʹzer,
&#91;son&#93; of Joʹrim,
&#91;son&#93; of Matʹthat,
&#91;son&#93; of Leʹvi,

[NOTE]
====
. “Jesus,” אBVgSysJ18,​22; ASypJ17,​21, “Jose(s).”
====

[[v42-3-30]]

^<<v42-3-30,30>>^ &#91;son&#93; of Symʹe·on,
&#91;son&#93; of Judas,
&#91;son&#93; of Joseph,
&#91;son&#93; of Joʹnam,
&#91;son&#93; of E·liʹa·kim,

[[v42-3-31]]

^<<v42-3-31,31>>^ &#91;son&#93; of Meʹle·a,
&#91;son&#93; of Menʹna,
&#91;son&#93; of Matʹta·tha,
&#91;son&#93; of Nathan,
&#91;son&#93; of David,

[[v42-3-32]]

^<<v42-3-32,32>>^ &#91;son&#93; of Jesʹse,
&#91;son&#93; of Oʹbed,^&#42;1^
&#91;son&#93; of Boʹaz,
&#91;son&#93; of Salʹmon,^&#42;2^
&#91;son&#93; of Nahʹshon,

[NOTE]
====
. “Jobel,” א*BSys.
. “Sala,” א*BSys.
====

[[v42-3-33]]

^<<v42-3-33,33>>^ &#91;son&#93; of Am·minʹa·dab,^&#42;1^
&#91;son&#93; of Arʹni,^&#42;2^
&#91;son&#93; of Hezʹron,
&#91;son&#93; of Peʹrez,
&#91;son&#93; of Judah,

[NOTE]
====
. “Admin,” א; B, “Admein.”
. “Aram,” ADVgSyp. Or, “Ram.” See 1Ch 2:9; Mt 1:3, 4.
====

[[v42-3-34]]

^<<v42-3-34,34>>^ &#91;son&#93; of Jacob,
&#91;son&#93; of Isaac,
&#91;son&#93; of Abraham,
&#91;son&#93; of Teʹrah,
&#91;son&#93; of Naʹhor,

[[v42-3-35]]

^<<v42-3-35,35>>^ &#91;son&#93; of Seʹrug,
&#91;son&#93; of Reʹu,
&#91;son&#93; of Peʹleg,
&#91;son&#93; of Eʹber,
&#91;son&#93; of Sheʹlah,

[[v42-3-36]]

^<<v42-3-36,36>>^ &#91;son&#93; of Ca·iʹnan,^&#42;1^
&#91;son&#93; of Ar·pachʹshad,
&#91;son&#93; of Shem,
&#91;son&#93; of Noah,
&#91;son&#93; of Laʹmech,

[NOTE]
====
. P75D omit “son of Cainan,” in harmony with Ge 10:24; Ge 11:12, 15; 1Ch 1:18.
====

[[v42-3-37]]

^<<v42-3-37,37>>^ &#91;son&#93; of Me·thuʹse·lah,
&#91;son&#93; of Eʹnoch,
&#91;son&#93; of Jaʹred,
&#91;son&#93; of Ma·haʹla·le·el,
&#91;son&#93; of Ca·iʹnan,

[[v42-3-38]]

^<<v42-3-38,38>>^ &#91;son&#93; of Eʹnosh,
&#91;son&#93; of Seth,
&#91;son&#93; of Adam,
&#91;son&#93; of God.

'''

xref:042-luke/042-luke-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-luke/042-luke-004.adoc#v42-4-0[Próximo Capítulo &#62;]