include::./index.adoc[]

[[v42-22-0]]
=== According to Luke, 22
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-22-1]]

^<<v42-22-1,1>>^ Now the festival of the unfermented cakes, the so-called Passover, was getting near.

[[v42-22-2]]

^<<v42-22-2,2>>^ Also, the chief priests and the scribes were seeking the effective way for them to get rid of him, for they were in fear of the people.

[[v42-22-3]]

^<<v42-22-3,3>>^ But Satan entered into Judas, the one called Is·carʹi·ot, who was numbered among the twelve;

[[v42-22-4]]

^<<v42-22-4,4>>^ and he went off and talked with the chief priests and &#91;temple&#93; captains about the effective way to betray him to them.

[[v42-22-5]]

^<<v42-22-5,5>>^ Well, they rejoiced and agreed to give him silver money.

[[v42-22-6]]

^<<v42-22-6,6>>^ So he consented, and he began to seek a good opportunity to betray him to them without a crowd around.

[[v42-22-7]]

^<<v42-22-7,7>>^ The day of the unfermented cakes now arrived, on which the passover &#91;victim&#93; must be sacrificed;

[[v42-22-8]]

^<<v42-22-8,8>>^ and he dispatched Peter and John, saying: “Go and get the passover ready for us to eat.”

[[v42-22-9]]

^<<v42-22-9,9>>^ They said to him: “Where do you want us to get &#91;it&#93; ready?”

[[v42-22-10]]

^<<v42-22-10,10>>^ He said to them: “Look! When YOU enter into the city a man carrying an earthenware vessel of water will meet YOU. Follow him into the house into which he enters.

[[v42-22-11]]

^<<v42-22-11,11>>^ And YOU must say to the landlord of the house, ‘The Teacher says to you: “Where is the guest room in which I may eat the passover with my disciples?”’

[[v42-22-12]]

^<<v42-22-12,12>>^ And that &#91;man&#93; will show YOU a large upper room furnished. Get &#91;it&#93; ready there.”

[[v42-22-13]]

^<<v42-22-13,13>>^ So they departed and found it just as he had said to them, and they got the passover ready.

[[v42-22-14]]

^<<v42-22-14,14>>^ At length when the hour came, he reclined at the table, and the apostles with him.

[[v42-22-15]]

^<<v42-22-15,15>>^ And he said to them: “I have greatly desired to eat this passover with YOU before I suffer;

[[v42-22-16]]

^<<v42-22-16,16>>^ for I tell YOU, I will not eat it again until it becomes fulfilled in the kingdom of God.”

[[v42-22-17]]

^<<v42-22-17,17>>^ And, accepting a cup, he gave thanks and said: “Take this and pass it from one to the other among yourselves;

[[v42-22-18]]

^<<v42-22-18,18>>^ for I tell YOU, From now on I will not drink again from the product of the vine until the kingdom of God arrives.”

[[v42-22-19]]

^<<v42-22-19,19>>^ Also, he took a loaf, gave thanks, broke it, and gave it to them, saying: “This means^&#42;1^ my body which is to be given in YOUR behalf. Keep doing this in remembrance of me.”

[NOTE]
====
. Or, “is,” in the sense of signifying, importing, representing. See Mt 26:26 ftn.
====

[[v42-22-20]]

^<<v42-22-20,20>>^ Also, the cup in the same way after they had the evening meal, he saying: “This cup means the new covenant by virtue of my blood, which is to be poured out in YOUR behalf.^&#42;1^

[NOTE]
====
. “Which is to be given . . . poured out in your behalf,” P75אABWVgSyh,pArm; DIt omit these words of vss 19, 20.
====

[[v42-22-21]]

^<<v42-22-21,21>>^ “But, look! the hand of my betrayer is with me at the table.

[[v42-22-22]]

^<<v42-22-22,22>>^ Because the Son of man is going his way according to what is marked out; all the same, woe to that man through whom he is betrayed!”

[[v42-22-23]]

^<<v42-22-23,23>>^ So they started to discuss among themselves the question of which of them would really be the one that was about to do this.

[[v42-22-24]]

^<<v42-22-24,24>>^ However, there also arose a heated dispute among them over which one of them seemed to be greatest.

[[v42-22-25]]

^<<v42-22-25,25>>^ But he said to them: “The kings of the nations lord it over them, and those having authority over them are called Benefactors.

[[v42-22-26]]

^<<v42-22-26,26>>^ YOU, though, are not to be that way. But let him that is the greatest among YOU become as the youngest, and the one acting as chief as the one ministering.^&#42;1^

[NOTE]
====
. Or, “serving.”
====

[[v42-22-27]]

^<<v42-22-27,27>>^ For which one is greater, the one reclining at the table or the one ministering? Is it not the one reclining at the table? But I am in YOUR midst as the one ministering.

[[v42-22-28]]

^<<v42-22-28,28>>^ “However, YOU are the ones that have stuck with me in my trials;

[[v42-22-29]]

^<<v42-22-29,29>>^ and I make a covenant with YOU, just as my Father has made a covenant with me, for a kingdom,

[[v42-22-30]]

^<<v42-22-30,30>>^ that YOU may eat and drink at my table in my kingdom, and sit on thrones to judge the twelve tribes of Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ “Simon, Simon, look! Satan has demanded to have YOU men to sift YOU as wheat.

[[v42-22-32]]

^<<v42-22-32,32>>^ But I have made supplication for you that your faith may not give out; and you, when once you have returned, strengthen your brothers.”

[[v42-22-33]]

^<<v42-22-33,33>>^ Then he said to him: “Lord,^&#42;1^ I am ready to go with you both into prison and into death.”

[NOTE]
====
. Or, “Master.”
====

[[v42-22-34]]

^<<v42-22-34,34>>^ But he said: “I tell you, Peter, A cock will not crow today until you have three times denied knowing me.”

[[v42-22-35]]

^<<v42-22-35,35>>^ He also said to them: “When I sent YOU forth without purse and food pouch and sandals, YOU did not want for anything, did YOU?” They said: “No!”^&#42;1^

[NOTE]
====
. Lit., “For nothing!”
====

[[v42-22-36]]

^<<v42-22-36,36>>^ Then he said to them: “But now let the one that has a purse take it up, likewise also a food pouch; and let the one having no sword sell his outer garment and buy one.

[[v42-22-37]]

^<<v42-22-37,37>>^ For I tell YOU that this which is written must be accomplished in me, namely, ‘And he was reckoned with lawless ones.’ For that which concerns me is having an accomplishment.”

[[v42-22-38]]

^<<v42-22-38,38>>^ Then they said: “Lord,^&#42;1^ look! here are two swords.” He said to them: “It is enough.”

[NOTE]
====
. Or, “Master.”
====

[[v42-22-39]]

^<<v42-22-39,39>>^ On going out he went as customarily to the Mount of Olives; and the disciples also followed him.

[[v42-22-40]]

^<<v42-22-40,40>>^ Having come to the place he said to them: “Carry on prayer, that YOU do not enter into temptation.”

[[v42-22-41]]

^<<v42-22-41,41>>^ And he himself drew away from them about a stone’s throw, and bent his knees and began to pray,

[[v42-22-42]]

^<<v42-22-42,42>>^ saying: “Father, if you wish, remove this cup from me. Nevertheless, let, not my will, but yours take place.”

[[v42-22-43]]

^<<v42-22-43,43>>^ Then an angel from heaven appeared to him and strengthened him.

[[v42-22-44]]

^<<v42-22-44,44>>^ But getting into an agony he continued praying more earnestly; and his sweat became as drops of blood falling to the ground.^&#42;1^

[NOTE]
====
. Vss 43, 44 are contained in א*DVgSyc,h,hi,pArm; P75אcABWSys omit.
====

[[v42-22-45]]

^<<v42-22-45,45>>^ And he rose from prayer, went to the disciples and found them slumbering from grief;

[[v42-22-46]]

^<<v42-22-46,46>>^ and he said to them: “Why are YOU sleeping? Rise and carry on prayer, that YOU do not enter into temptation.”

[[v42-22-47]]

^<<v42-22-47,47>>^ While he was yet speaking, look! a crowd, and the &#91;man&#93; called Judas, one of the twelve, was going before them; and he approached Jesus to kiss him.

[[v42-22-48]]

^<<v42-22-48,48>>^ But Jesus said to him: “Judas, do you betray the Son of man with a kiss?”

[[v42-22-49]]

^<<v42-22-49,49>>^ When those about him saw what was going to happen, they said: “Lord, shall we strike with the sword?”

[[v42-22-50]]

^<<v42-22-50,50>>^ A certain one of them even did strike the slave of the high priest and took off his right ear.

[[v42-22-51]]

^<<v42-22-51,51>>^ But in reply Jesus said: “LET it go as far as this.” And he touched the ear and healed him.

[[v42-22-52]]

^<<v42-22-52,52>>^ Jesus then said to the chief priests and captains of the temple and older men that had come there for him: “Did YOU come out with swords and clubs as against a robber?

[[v42-22-53]]

^<<v42-22-53,53>>^ While I was with YOU in the temple day after day YOU did not stretch out YOUR hands against me. But this is YOUR hour and the authority of darkness.”

[[v42-22-54]]

^<<v42-22-54,54>>^ Then they arrested him and led him off and brought him into the house of the high priest; but Peter was following at a distance.

[[v42-22-55]]

^<<v42-22-55,55>>^ When they lit a fire in the midst of the courtyard and sat down together, Peter was sitting in among them.

[[v42-22-56]]

^<<v42-22-56,56>>^ But a certain servant girl saw him sitting by the bright fire and looked him over and said: “This man also was with him.”

[[v42-22-57]]

^<<v42-22-57,57>>^ But he denied it,^&#42;1^ saying: “I do not know him, woman.”

[NOTE]
====
. “Him,” AD*VgSyh.
====

[[v42-22-58]]

^<<v42-22-58,58>>^ And after a short time another person seeing him said: “You also are one of them.” But Peter said: “Man, I am not.”

[[v42-22-59]]

^<<v42-22-59,59>>^ And after about an hour intervened a certain other &#91;man&#93; began insisting strongly: “For a certainty this &#91;man&#93; also was with him; for, in fact, he is a Gal·i·leʹan!”

[[v42-22-60]]

^<<v42-22-60,60>>^ But Peter said: “Man, I do not know what you are saying.” And instantly, while he was yet speaking, a cock crowed.

[[v42-22-61]]

^<<v42-22-61,61>>^ And the Lord turned and looked upon Peter, and Peter recalled the utterance of the Lord when he said to him: “Before a cock crows today you will disown me three times.”

[[v42-22-62]]

^<<v42-22-62,62>>^ And he went outside and wept bitterly.

[[v42-22-63]]

^<<v42-22-63,63>>^ Now the men that had him^&#42;1^ in custody began to make fun of him, hitting him;

[NOTE]
====
. “Him,” אBDItVg; ASyp, “Jesus.”
====

[[v42-22-64]]

^<<v42-22-64,64>>^ and after covering him over they would ask and say: “Prophesy. Who is it that struck you?”

[[v42-22-65]]

^<<v42-22-65,65>>^ And they went on saying many other things in blasphemy against him.

[[v42-22-66]]

^<<v42-22-66,66>>^ At length when it became day, the assembly of older men of the people, both chief priests and scribes, gathered together, and they haled him into their Sanʹhe·drin hall,^&#42;1^ saying:

[NOTE]
====
. Or, “their Sanhedrin.”
====

[[v42-22-67]]

^<<v42-22-67,67>>^ “If you are the Christ, tell us.” But he said to them: “Even if I told YOU, YOU would not believe it at all.

[[v42-22-68]]

^<<v42-22-68,68>>^ Moreover, if I questioned YOU, YOU would not answer at all.

[[v42-22-69]]

^<<v42-22-69,69>>^ However, from now on the Son of man will be sitting at the powerful right hand^&#42;1^ of God.”

[NOTE]
====
. Or, “at the right hand of the power.”
====

[[v42-22-70]]

^<<v42-22-70,70>>^ At this they all said: “Are you, therefore, the Son of God?” He said to them: “YOU yourselves are saying that I am.”

[[v42-22-71]]

^<<v42-22-71,71>>^ They said: “Why do we need further witness? For we ourselves have heard &#91;it&#93; out of his own mouth.”

'''

xref:042-luke/042-luke-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-luke/042-luke-023.adoc#v42-23-0[Próximo Capítulo &#62;]