include::./index.adoc[]

[[v42-14-0]]
=== According to Luke, 14
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-14-1]]

^<<v42-14-1,1>>^ And on an occasion when he went into the house of a certain one of the rulers of the Pharisees on the sabbath to eat a meal, they were closely watching him.

[[v42-14-2]]

^<<v42-14-2,2>>^ And, look! there was before him a certain man who had dropsy.

[[v42-14-3]]

^<<v42-14-3,3>>^ So in response Jesus spoke to those versed in the Law and to the Pharisees, saying: “Is it lawful on the sabbath to cure or not?”

[[v42-14-4]]

^<<v42-14-4,4>>^ But they kept silent. With that he took hold of &#91;the man&#93;, healed him and sent &#91;him&#93; away.

[[v42-14-5]]

^<<v42-14-5,5>>^ And he said to them: “Who of YOU, if his son or bull falls into a well, will not immediately pull him out on the sabbath day?”

[[v42-14-6]]

^<<v42-14-6,6>>^ And they were not able to answer back on these things.

[[v42-14-7]]

^<<v42-14-7,7>>^ He then went on to tell the invited men an illustration, as he marked how they were choosing the most prominent places for themselves, saying to them:

[[v42-14-8]]

^<<v42-14-8,8>>^ “When you are invited by someone to a marriage feast, do not lie down in the most prominent place. Perhaps someone more distinguished than you may at the time have been invited by him,

[[v42-14-9]]

^<<v42-14-9,9>>^ and he that invited you and him will come and say to you, ‘Let this man have the place.’ And then you will start off with shame to occupy the lowest place.

[[v42-14-10]]

^<<v42-14-10,10>>^ But when you are invited, go and recline in the lowest place, that when the man that has invited you comes he will say to you, ‘Friend, go on up higher.’ Then you will have honor in front of all your fellow guests.

[[v42-14-11]]

^<<v42-14-11,11>>^ For everyone that exalts himself will be humbled and he that humbles himself will be exalted.”

[[v42-14-12]]

^<<v42-14-12,12>>^ Next he proceeded to say also to the man that invited him: “When you spread a dinner or evening meal, do not call your friends or your brothers or your relatives or rich neighbors. Perhaps sometime they might also invite you in return and it would become a repayment to you.

[[v42-14-13]]

^<<v42-14-13,13>>^ But when you spread a feast, invite poor people, crippled, lame, blind;

[[v42-14-14]]

^<<v42-14-14,14>>^ and you will be happy, because they have nothing with which to repay you. For you will be repaid in the resurrection of the righteous ones.”

[[v42-14-15]]

^<<v42-14-15,15>>^ On hearing these things a certain one of the fellow guests said to him: “Happy is he who eats bread^&#42;1^ in the kingdom of God.”

[NOTE]
====
. Or, “is at the feast.”
====

[[v42-14-16]]

^<<v42-14-16,16>>^ &#91;Jesus&#93;^&#42;1^ said to him: “A certain man was spreading a grand evening meal, and he invited many.

[NOTE]
====
. Lit., “He.”
====

[[v42-14-17]]

^<<v42-14-17,17>>^ And he sent his slave out at the hour of the evening meal to say to the invited ones, ‘Come, because things are now ready.’

[[v42-14-18]]

^<<v42-14-18,18>>^ But they all in common started to beg off. The first said to him, ‘I bought a field and need to go out and see it; I ask you, Have me excused.’^&#42;1^

[NOTE]
====
. Or, “Please let me be excused.”
====

[[v42-14-19]]

^<<v42-14-19,19>>^ And another said, ‘I bought five yoke of cattle and am going to examine them; I ask you, Have me excused.’

[[v42-14-20]]

^<<v42-14-20,20>>^ Still another said, ‘I just married a wife and for this reason I cannot come.’

[[v42-14-21]]

^<<v42-14-21,21>>^ So the slave came up and reported these things to his master. Then the householder became wrathful and said to his slave, ‘Go out quickly into the broad ways and the lanes of the city, and bring in here the poor and crippled and blind and lame.’

[[v42-14-22]]

^<<v42-14-22,22>>^ In time the slave said, ‘Master, what you ordered has been done, and yet there is room.’

[[v42-14-23]]

^<<v42-14-23,23>>^ And the master said to the slave, ‘Go out into the roads and the fenced-in places, and compel them to come in, that my house may be filled.

[[v42-14-24]]

^<<v42-14-24,24>>^ For I say to YOU people, None of those men that were invited shall have a taste of my evening meal.’”

[[v42-14-25]]

^<<v42-14-25,25>>^ Now great crowds were traveling with him, and he turned and said to them:

[[v42-14-26]]

^<<v42-14-26,26>>^ “If anyone comes to me and does not hate his father and mother and wife and children and brothers and sisters, yes, and even his own soul,^&#42;1^ he cannot be my disciple.

[NOTE]
====
. Or, “life.” See App 4A.
====

[[v42-14-27]]

^<<v42-14-27,27>>^ Whoever is not carrying his torture stake^&#42;1^ and coming after me cannot be my disciple.

[NOTE]
====
. See App 5C.
====

[[v42-14-28]]

^<<v42-14-28,28>>^ For example, who of YOU that wants to build a tower does not first sit down and calculate the expense, to see if he has enough to complete it?

[[v42-14-29]]

^<<v42-14-29,29>>^ Otherwise, he might lay its foundation but not be able to finish it, and all the onlookers might start to ridicule him,

[[v42-14-30]]

^<<v42-14-30,30>>^ saying, ‘This man started to build but was not able to finish.’

[[v42-14-31]]

^<<v42-14-31,31>>^ Or what king, marching to meet another king in war, does not first sit down and take counsel whether he is able with ten thousand troops to cope with the one that comes against him with twenty thousand?

[[v42-14-32]]

^<<v42-14-32,32>>^ If, in fact, he cannot do so, then while that one is yet far away he sends out a body of ambassadors and sues for peace.

[[v42-14-33]]

^<<v42-14-33,33>>^ Thus, you may be sure, none of YOU that does not say good-bye to all his belongings can be my disciple.

[[v42-14-34]]

^<<v42-14-34,34>>^ “Salt, to be sure, is fine. But if even the salt loses its strength, with what will it be seasoned?

[[v42-14-35]]

^<<v42-14-35,35>>^ It is suitable neither for soil nor for manure. People throw it outside. Let him that has ears to listen, listen.”

'''

xref:042-luke/042-luke-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-luke/042-luke-015.adoc#v42-15-0[Próximo Capítulo &#62;]