include::./index.adoc[]

[[v42-2-0]]
=== According to Luke, 2
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-2-1]]

^<<v42-2-1,1>>^ Now in those days a decree went forth from Caesar^&#42;1^ Au·gusʹtus for all the inhabited earth^&#42;2^ to be registered;

[NOTE]
====
. Or, “Emperor.” Lat., Caeʹsa·re.
. Lit., “the inhabited.” Gr., ten oi·kou·meʹnen, fem. sing., referring to the earth.
====

[[v42-2-2]]

^<<v42-2-2,2>>^ (this first registration took place when Qui·rinʹi·us was governor of Syria;)

[[v42-2-3]]

^<<v42-2-3,3>>^ and all people went traveling to be registered, each one to his own city.

[[v42-2-4]]

^<<v42-2-4,4>>^ Of course, Joseph also went up from Galʹi·lee, out of the city of Nazʹa·reth, into Ju·deʹa, to David’s city, which is called Bethʹle·hem, because of his being a member of the house and family of David,

[[v42-2-5]]

^<<v42-2-5,5>>^ to get registered with Mary, who had been given him in marriage as promised, at present heavy with child.

[[v42-2-6]]

^<<v42-2-6,6>>^ While they were there, the days came to the full for her to give birth.

[[v42-2-7]]

^<<v42-2-7,7>>^ And she gave birth to her son, the firstborn, and she bound him with cloth bands and laid him in a manger, because there was no place for them in the lodging room.^&#42;1^

[NOTE]
====
. Or, “guest room.” See Mr 14:14.
====

[[v42-2-8]]

^<<v42-2-8,8>>^ There were also in that same country shepherds living out of doors^&#42;1^ and keeping watches in the night over their flocks.

[NOTE]
====
. Or, “dwelling in the fields.”
====

[[v42-2-9]]

^<<v42-2-9,9>>^ And suddenly Jehovah’s^&#42;1^ angel stood by them, and Jehovah’s^&#42;2^ glory gleamed around them, and they became very fearful.

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v42-2-10]]

^<<v42-2-10,10>>^ But the angel said to them: “Have no fear, for, look! I am declaring to YOU good news of a great joy that all the people will have,

[[v42-2-11]]

^<<v42-2-11,11>>^ because there was born to YOU today a Savior, who is^&#42;1^ Christ &#91;the&#93; Lord,^&#42;2^ in David’s city.

[NOTE]
====
. Or, “is to be.”
. “Christ [the] Lord.” Gr., Khri·stosʹ kyʹri·os. This expression might be a Gr. rendering of the Heb. ma·shiʹach Yeho·wahʹ, “Jehovah’s Christ,” as in J5-8,​10. See 2:26.
====

[[v42-2-12]]

^<<v42-2-12,12>>^ And this is a sign for YOU: YOU will find an infant bound in cloth bands and lying in a manger.”

[[v42-2-13]]

^<<v42-2-13,13>>^ And suddenly there came to be with the angel a multitude of the heavenly army,^&#42;1^ praising God and saying:

[NOTE]
====
. Or, “host.” Lat., mi·liʹti·ae.
====

[[v42-2-14]]

^<<v42-2-14,14>>^ “Glory in the heights above to God, and upon earth peace among men of goodwill.”^&#42;1^

[NOTE]
====
. Or, “men whom he approves.” Gr., an·throʹpois eu·do·kiʹas.
====

[[v42-2-15]]

^<<v42-2-15,15>>^ So when the angels had departed from them into heaven, the shepherds began saying to one another: “Let us by all means go clear to Bethʹle·hem and see this thing that has taken place, which Jehovah^&#42;1^ has made known to us.”

[NOTE]
====
. See App 1D.
====

[[v42-2-16]]

^<<v42-2-16,16>>^ And they went with haste and found Mary as well as Joseph, and the infant lying in the manger.

[[v42-2-17]]

^<<v42-2-17,17>>^ When they saw it, they made known the saying that had been spoken to them concerning this young child.

[[v42-2-18]]

^<<v42-2-18,18>>^ And all that heard marveled over the things told them by the shepherds,

[[v42-2-19]]

^<<v42-2-19,19>>^ but Mary began to preserve all these sayings, drawing conclusions in her heart.

[[v42-2-20]]

^<<v42-2-20,20>>^ Then the shepherds went back, glorifying and praising God for all the things they heard and saw, just as these had been told them.

[[v42-2-21]]

^<<v42-2-21,21>>^ Now when eight days came to the full for circumcising him, his name was also called Jesus,^&#42;1^ the name called by the angel before he was conceived in the womb.

[NOTE]
====
. See Mt 1:21 ftn.
====

[[v42-2-22]]

^<<v42-2-22,22>>^ Also, when the days for purifying them according to the law of Moses came to the full, they brought him up to Jerusalem to present him to Jehovah,^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v42-2-23]]

^<<v42-2-23,23>>^ just as it is written in Jehovah’s^&#42;1^ law: “Every male opening a womb must be called holy to Jehovah,”^&#42;2^

[NOTE]
====
. See App 1D.
. See App 1D.
====

[[v42-2-24]]

^<<v42-2-24,24>>^ and to offer sacrifice according to what is said in the law of Jehovah:^&#42;1^ “A pair of turtledoves or two young pigeons.”

[NOTE]
====
. See App 1D.
====

[[v42-2-25]]

^<<v42-2-25,25>>^ And, look! there was a man in Jerusalem named Simʹe·on, and this man was righteous and reverent, waiting for Israel’s consolation, and holy spirit was upon him.

[[v42-2-26]]

^<<v42-2-26,26>>^ Furthermore, it had been divinely revealed to him by the holy spirit that he would not see death before he had seen the Christ of Jehovah.^&#42;1^

[NOTE]
====
. See App 1D.
====

[[v42-2-27]]

^<<v42-2-27,27>>^ Under the power of the spirit he now came into the temple; and as the parents brought the young child Jesus in to do for it according to the customary practice of the law,

[[v42-2-28]]

^<<v42-2-28,28>>^ he himself received it into his arms and blessed God and said:

[[v42-2-29]]

^<<v42-2-29,29>>^ “Now, Sovereign Lord,^&#42;1^ you are letting your slave go free in peace according to your declaration;

[NOTE]
====
. “Sovereign Lord,” אAB; Gr., deʹspo·ta; J7,​8,​10,​13,​16,​17,​22(Heb.), ʼAdho·naiʹ; J9,​18, “Jehovah.”
====

[[v42-2-30]]

^<<v42-2-30,30>>^ because my eyes have seen your means of saving

[[v42-2-31]]

^<<v42-2-31,31>>^ that you have made ready in the sight of all the peoples,

[[v42-2-32]]

^<<v42-2-32,32>>^ a light for removing the veil from the nations^&#42;1^ and a glory of your people Israel.”

[NOTE]
====
. Or, “a light of the nations for a revelation.”
====

[[v42-2-33]]

^<<v42-2-33,33>>^ And its father and mother continued wondering at the things being spoken about it.

[[v42-2-34]]

^<<v42-2-34,34>>^ Also, Simʹe·on blessed them, but said to Mary its mother: “Look! This one is laid for the fall and the rising again^&#42;1^ of many in Israel and for a sign to be talked against

[NOTE]
====
. Or, “the resurrection.” Gr., a·naʹsta·sin. See Mt 22:23 ftn.
====

[[v42-2-35]]

^<<v42-2-35,35>>^ (yes, a long sword will be run through the soul^&#42;1^ of you yourself), in order that the reasonings of many hearts may be uncovered.”

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ. See App 4A.
====

[[v42-2-36]]

^<<v42-2-36,36>>^ Now there was Anna a prophetess, Phanʹu·el’s daughter, of Ashʹer’s tribe (this woman was well along in years, and had lived with a husband for seven years from her virginity,

[[v42-2-37]]

^<<v42-2-37,37>>^ and she was a widow now eighty-four years old), who was never missing from the temple, rendering sacred service^&#42;1^ night and day with fastings and supplications.

[NOTE]
====
. Or, “rendering worship.” Gr., la·treuʹou·sa; J17(Heb.), ʽa·vedhahʹ. See Ex 3:12 ftn.
====

[[v42-2-38]]

^<<v42-2-38,38>>^ And in that very hour she came near and began returning thanks to God^&#42;1^ and speaking about &#91;the child&#93;^&#42;2^ to all those waiting for Jerusalem’s deliverance.

[NOTE]
====
. “God,” אB; AVgSyp,s, “the Lord”; J5,​7-17, “Jehovah.”
. Lit., “about it.”
====

[[v42-2-39]]

^<<v42-2-39,39>>^ So when they had carried out all the things according to the law of Jehovah,^&#42;1^ they went back into Galʹi·lee to their own city Nazʹa·reth.

[NOTE]
====
. See App 1D.
====

[[v42-2-40]]

^<<v42-2-40,40>>^ And the young child continued growing and getting strong, being filled with wisdom, and God’s favor continued upon him.

[[v42-2-41]]

^<<v42-2-41,41>>^ Now his parents were accustomed to go from year to year to Jerusalem for the festival of the passover.

[[v42-2-42]]

^<<v42-2-42,42>>^ And when he became twelve years old, they went up according to the custom of the festival

[[v42-2-43]]

^<<v42-2-43,43>>^ and completed the days. But when they were returning, the boy Jesus remained behind in Jerusalem, and his parents did not notice it.

[[v42-2-44]]

^<<v42-2-44,44>>^ Assuming that he was in the company traveling together, they covered a day’s distance and then began to hunt him up among the relatives and acquaintances.

[[v42-2-45]]

^<<v42-2-45,45>>^ But, not finding him, they returned to Jerusalem, making a diligent search for him.

[[v42-2-46]]

^<<v42-2-46,46>>^ Well, after three days they found him in the temple, sitting in the midst of the teachers and listening to them and questioning them.

[[v42-2-47]]

^<<v42-2-47,47>>^ But all those listening to him were in constant amazement at his understanding and his answers.

[[v42-2-48]]

^<<v42-2-48,48>>^ Now when they saw him they were astounded, and his mother said to him: “Child, why did you treat us this way? Here your father and I in mental distress have been looking for you.”

[[v42-2-49]]

^<<v42-2-49,49>>^ But he said to them: “Why did YOU have to go looking for me? Did YOU not know that I must be in the &#91;house&#93; of my Father?”

[[v42-2-50]]

^<<v42-2-50,50>>^ However, they did not grasp the saying that he spoke to them.

[[v42-2-51]]

^<<v42-2-51,51>>^ And he went down with them and came to Nazʹa·reth, and he continued subject to them. Also, his mother carefully kept all these sayings^&#42;1^ in her heart.

[NOTE]
====
. Or, “things.” Gr., rheʹma·ta. See 1:37 ftn.
====

[[v42-2-52]]

^<<v42-2-52,52>>^ And Jesus went on progressing in wisdom and in physical growth and in favor with God and men.

'''

xref:042-luke/042-luke-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-luke/042-luke-003.adoc#v42-3-0[Próximo Capítulo &#62;]