include::./index.adoc[]

[[v42-8-0]]
=== According to Luke, 8
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-8-1]]

^<<v42-8-1,1>>^ Shortly afterwards he went journeying from city to city and from village to village, preaching^&#42;1^ and declaring the good news of the kingdom of God. And the twelve were with him,

[NOTE]
====
. Or, “heralding.” Gr., ke·rysʹson; Lat., praeʹdi·cans.
====

[[v42-8-2]]

^<<v42-8-2,2>>^ and certain women that had been cured of wicked spirits and sicknesses, Mary the so-called Magʹda·lene, from whom seven demons had come out,

[[v42-8-3]]

^<<v42-8-3,3>>^ and Jo·anʹna the wife of Chuʹza, Herod’s man in charge, and Su·sanʹna and many other women, who were ministering to them from their belongings.

[[v42-8-4]]

^<<v42-8-4,4>>^ Now when a great crowd had collected together with those that went to him from city after city, he spoke by means of an illustration:

[[v42-8-5]]

^<<v42-8-5,5>>^ “A sower went out to sow his seed. Well, as he was sowing, some of it fell alongside the road and was trampled down, and the birds of heaven ate it up.

[[v42-8-6]]

^<<v42-8-6,6>>^ Some other landed upon the rock-mass, and, after sprouting, it dried up because of not having moisture.

[[v42-8-7]]

^<<v42-8-7,7>>^ Some other fell among the thorns, and the thorns that grew up with it choked it off.

[[v42-8-8]]

^<<v42-8-8,8>>^ Some other fell upon the good soil, and, after sprouting, it produced fruit a hundredfold.” As he told these things, he proceeded to call out: “Let him that has ears to listen, listen.”

[[v42-8-9]]

^<<v42-8-9,9>>^ But his disciples began to ask him what this illustration might mean.

[[v42-8-10]]

^<<v42-8-10,10>>^ He said: “To YOU it is granted to understand the sacred secrets of the kingdom of God, but for the rest it is in illustrations, in order that, though looking, they may look in vain and, though hearing, they may not get the meaning.

[[v42-8-11]]

^<<v42-8-11,11>>^ Now the illustration means this: The seed is the word of God.

[[v42-8-12]]

^<<v42-8-12,12>>^ Those alongside the road are the ones that have heard, then the Devil comes and takes the word away from their hearts in order that they may not believe and be saved.

[[v42-8-13]]

^<<v42-8-13,13>>^ Those upon the rock-mass are the ones who, when they hear it, receive the word with joy, but these have no root; they believe for a season, but in a season of testing they fall away.

[[v42-8-14]]

^<<v42-8-14,14>>^ As for that which fell among the thorns, these are the ones that have heard, but, by being carried away by anxieties and riches and pleasures of this life, they are completely choked and bring nothing to perfection.

[[v42-8-15]]

^<<v42-8-15,15>>^ As for that on the fine soil, these are the ones that, after hearing the word with a fine and good heart, retain it and bear fruit with endurance.

[[v42-8-16]]

^<<v42-8-16,16>>^ “No one, after lighting a lamp, covers it with a vessel or puts it underneath a bed, but he puts it on a lampstand, that those stepping in may behold the light.

[[v42-8-17]]

^<<v42-8-17,17>>^ For there is nothing hidden that will not become manifest, neither anything carefully concealed that will never become known and never come into the open.

[[v42-8-18]]

^<<v42-8-18,18>>^ Therefore, pay attention to how YOU listen; for whoever has, more will be given him, but whoever does not have, even what he imagines he has will be taken away from him.”

[[v42-8-19]]

^<<v42-8-19,19>>^ Now his mother and brothers came toward him, but they were unable to get to him because of the crowd.

[[v42-8-20]]

^<<v42-8-20,20>>^ However, it was reported to him: “Your mother and your brothers are standing outside wanting to see you.”

[[v42-8-21]]

^<<v42-8-21,21>>^ In reply he said to them: “My mother and my brothers are these who hear the word of God and do it.”

[[v42-8-22]]

^<<v42-8-22,22>>^ In the course of one of the days he and his disciples got into a boat, and he said to them: “Let us cross to the other side of the lake.” So they set sail.

[[v42-8-23]]

^<<v42-8-23,23>>^ But as they were sailing he fell asleep. Now a violent windstorm descended upon the lake, and they began to fill up with &#91;water&#93; and to be in danger.

[[v42-8-24]]

^<<v42-8-24,24>>^ Finally they went to him and roused him, saying: “Instructor, Instructor, we are about to perish!” Rousing himself, he rebuked the wind and the raging of the water, and they subsided, and a calm set in.

[[v42-8-25]]

^<<v42-8-25,25>>^ Then he said to them: “Where is YOUR faith?” But struck with fear, they marveled, saying to one another: “Who really is this, for he orders even the winds and the water, and they obey him?”

[[v42-8-26]]

^<<v42-8-26,26>>^ And they put in to shore in the country of the Gerʹa·senes,^&#42;1^ which is on the side opposite Galʹi·lee.

[NOTE]
====
. “Gerasenes,” P75BDItVg; א, “Gergesenes”; ASyp,s, “Gadarenes.”
====

[[v42-8-27]]

^<<v42-8-27,27>>^ But as he got out onto land a certain man from the city who had demons met him. And for a considerable time he had not worn clothing, and he was staying, not at home, but among the tombs.

[[v42-8-28]]

^<<v42-8-28,28>>^ At the sight of Jesus he cried aloud and fell down before him, and with a loud voice he said: “What have I to do with you,^&#42;1^ Jesus Son of the Most High God? I beg you, do not torment me.”

[NOTE]
====
. An idiom; a repellent question indicating objection. See App 7B.
====

[[v42-8-29]]

^<<v42-8-29,29>>^ (For he had been ordering the unclean spirit to come out of the man. For over a long time it had held him fast, and he was repeatedly bound with chains and fetters under guard, but he would burst the bonds and be driven by the demon into the lonely places.)

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus asked him: “What is your name?” He said: “Legion,” because many demons had entered into him.

[[v42-8-31]]

^<<v42-8-31,31>>^ And they kept entreating him not to order them to go away into the abyss.^&#42;1^

[NOTE]
====
. Or, “the deep.” See Ro 10:7.
====

[[v42-8-32]]

^<<v42-8-32,32>>^ Now a herd of a considerable number of swine was feeding there on the mountain; so they entreated him to permit them to enter into those. And he gave them permission.

[[v42-8-33]]

^<<v42-8-33,33>>^ Then the demons went out of the man and entered into the swine, and the herd rushed over the precipice into the lake and drowned.

[[v42-8-34]]

^<<v42-8-34,34>>^ But when the herders saw what had happened, they fled and reported it to the city and to the countryside.

[[v42-8-35]]

^<<v42-8-35,35>>^ Then people turned out to see what had happened, and they came to Jesus and found the man from whom the demons came out, clothed and in his sound mind, sitting at the feet of Jesus; and they became fearful.

[[v42-8-36]]

^<<v42-8-36,36>>^ Those who had seen it reported to them how the demon-possessed man had been made well.^&#42;1^

[NOTE]
====
. Or, “had been saved.”
====

[[v42-8-37]]

^<<v42-8-37,37>>^ So all the multitude from the surrounding country of the Gerʹa·senes^&#42;1^ asked him to get away from them, because they were in the grip of great fear. Then he went aboard the boat and turned away.

[NOTE]
====
. See vs 26 ftn.
====

[[v42-8-38]]

^<<v42-8-38,38>>^ However, the man from whom the demons had gone out kept begging to continue with him; but he dismissed the man, saying:

[[v42-8-39]]

^<<v42-8-39,39>>^ “Be on your way back home, and keep on relating what things God did for you.” Accordingly he went away, proclaiming throughout the whole city what things Jesus did for him.

[[v42-8-40]]

^<<v42-8-40,40>>^ When Jesus got back, the crowd received him kindly, for they were all expecting him.

[[v42-8-41]]

^<<v42-8-41,41>>^ But, look! a man named Jaʹi·rus came, and this man was a presiding officer of the synagogue. And he fell at the feet of Jesus and began to entreat him to enter into his house,

[[v42-8-42]]

^<<v42-8-42,42>>^ because he had an only-begotten^&#42;1^ daughter about twelve years old and she was dying.
As he was going the crowds thronged him.

[NOTE]
====
. Or, “an only.” Gr., mo·no·ge·nesʹ. See Jg 11:34 ftn, “Child.”
====

[[v42-8-43]]

^<<v42-8-43,43>>^ And a woman, subject to a flow of blood for twelve years, who had not been able to get a cure from anyone,

[[v42-8-44]]

^<<v42-8-44,44>>^ approached from behind and touched the fringe^&#42;1^ of his outer garment, and instantly her flow of blood stopped.

[NOTE]
====
. Or, “border; tassel.”
====

[[v42-8-45]]

^<<v42-8-45,45>>^ So Jesus said: “Who was it that touched me?” When they were all denying it, Peter said: “Instructor, the crowds are hemming you in and closely pressing you.”

[[v42-8-46]]

^<<v42-8-46,46>>^ Yet Jesus said: “Someone touched me, for I perceived that power went out of me.”

[[v42-8-47]]

^<<v42-8-47,47>>^ Seeing that she had not escaped notice, the woman came trembling and fell down before him and disclosed before all the people the cause for which she touched him and how she was healed instantly.

[[v42-8-48]]

^<<v42-8-48,48>>^ But he said to her: “Daughter, your faith has made you well;^&#42;1^ go your way in peace.”

[NOTE]
====
. Or, “has saved you.”
====

[[v42-8-49]]

^<<v42-8-49,49>>^ While he was yet speaking, a certain representative of the presiding officer of the synagogue came, saying: “Your daughter has died; do not bother the teacher any longer.”

[[v42-8-50]]

^<<v42-8-50,50>>^ On hearing this, Jesus answered him: “Have no fear, only put forth faith, and she will be saved.”

[[v42-8-51]]

^<<v42-8-51,51>>^ When he reached the house he did not let anyone go in with him except Peter and John and James and the girl’s father and mother.

[[v42-8-52]]

^<<v42-8-52,52>>^ But people were all weeping and beating themselves in grief for her. So he said: “STOP weeping, for she did not die but is sleeping.”

[[v42-8-53]]

^<<v42-8-53,53>>^ At this they began to laugh at him scornfully, because they knew she had died.

[[v42-8-54]]

^<<v42-8-54,54>>^ But he took her by the hand and called, saying: “Girl, get up!”^&#42;1^

[NOTE]
====
. Or, “wake up!”
====

[[v42-8-55]]

^<<v42-8-55,55>>^ And her spirit^&#42;1^ returned, and she rose instantly, and he ordered something to be given her to eat.

[NOTE]
====
. Or, “her breath (life-force).” Gr., to pneuʹma au·tesʹ; J17,​18,​22(Heb.), ru·chahʹ.
====

[[v42-8-56]]

^<<v42-8-56,56>>^ Well, her parents were beside themselves; but he instructed them to tell no one what had happened.

'''

xref:042-luke/042-luke-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-luke/042-luke-009.adoc#v42-9-0[Próximo Capítulo &#62;]