include::./index.adoc[]

[[v42-9-0]]
=== According to Luke, 9
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-9-1]]

^<<v42-9-1,1>>^ Then he called the twelve together and gave them power and authority over all the demons and to cure sicknesses.

[[v42-9-2]]

^<<v42-9-2,2>>^ And so he sent them forth to preach the kingdom of God and to heal,

[[v42-9-3]]

^<<v42-9-3,3>>^ and he said to them: “Carry nothing for the trip, neither staff nor food pouch, nor bread nor silver money; neither have two undergarments.

[[v42-9-4]]

^<<v42-9-4,4>>^ But wherever YOU enter into a home, stay there and leave from there.

[[v42-9-5]]

^<<v42-9-5,5>>^ And wherever people do not receive YOU, on going out of that city shake the dust off YOUR feet for a witness against them.”

[[v42-9-6]]

^<<v42-9-6,6>>^ Then starting out they went through the territory from village to village, declaring the good news and performing cures everywhere.

[[v42-9-7]]

^<<v42-9-7,7>>^ Now Herod the district ruler^&#42;1^ heard of all the things happening, and he was in great perplexity because of its being said by some that John had been raised up from the dead,

[NOTE]
====
. Or, “the tetrarch.” See 3:1 and ftns.
====

[[v42-9-8]]

^<<v42-9-8,8>>^ but by others that E·liʹjah had appeared, but by still others that a certain one of the ancient prophets had risen.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herod said: “John I beheaded. Who, then, is this about whom I am hearing such things?” So he was seeking to see him.

[[v42-9-10]]

^<<v42-9-10,10>>^ And when the apostles returned they recounted to him what things they had done. With that he took them along and withdrew to privacy into a city called Beth·saʹi·da.

[[v42-9-11]]

^<<v42-9-11,11>>^ But the crowds, getting to know it, followed him. And he received them kindly and began to speak to them about the kingdom of God, and he healed those needing a cure.

[[v42-9-12]]

^<<v42-9-12,12>>^ Then the day started to decline. The twelve now came up and said to him: “Dismiss the crowd, that they may go into the villages and countryside round about and procure lodging and find provisions, because out here we are in a lonely place.”

[[v42-9-13]]

^<<v42-9-13,13>>^ But he said to them: “YOU give them something to eat.” They said: “We have nothing more than five loaves and two fishes, unless perhaps we ourselves go and buy foodstuffs for all these people.”

[[v42-9-14]]

^<<v42-9-14,14>>^ They were, in fact, about five thousand men. But he said to his disciples: “Have them recline as at meals, in groups of about fifty each.”

[[v42-9-15]]

^<<v42-9-15,15>>^ And they did so and had them all recline.

[[v42-9-16]]

^<<v42-9-16,16>>^ Then taking the five loaves and the two fishes, he looked up to heaven, blessed them and broke them up and began to give them to the disciples to set before the crowd.

[[v42-9-17]]

^<<v42-9-17,17>>^ So they all ate and were satisfied, and the surplus that they had was taken up, twelve baskets of fragments.

[[v42-9-18]]

^<<v42-9-18,18>>^ Later, while he was praying alone, the disciples came together to him,^&#42;1^ and he questioned them, saying: “Who are the crowds saying that I am?”

[NOTE]
====
. Or, “the disciples were with him.” B*, “the disciples came upon him.”
====

[[v42-9-19]]

^<<v42-9-19,19>>^ In reply they said: “John the Baptist;^&#42;1^ but others, E·liʹjah,^&#42;2^ and still others, that one of the ancient prophets has risen.”

[NOTE]
====
. Or, “the Immerser; Dipper.” Gr., ton Ba·pti·stenʹ.
. Meaning “My God Is Jehovah.” J17,​18,​22(Heb.), ʼE·li·yaʹhu.
====

[[v42-9-20]]

^<<v42-9-20,20>>^ Then he said to them: “YOU, though, who do YOU say I am?” Peter said in reply: “The Christ of God.”

[[v42-9-21]]

^<<v42-9-21,21>>^ Then in a stern talk to them he instructed them not to be telling this to anybody,

[[v42-9-22]]

^<<v42-9-22,22>>^ but said: “The Son of man must undergo many sufferings and be rejected by the older men and chief priests and scribes, and be killed, and on the third day be raised up.”

[[v42-9-23]]

^<<v42-9-23,23>>^ Then he went on to say to all: “If anyone wants to come after me, let him disown himself and pick up his torture stake^&#42;1^ day after day and follow me continually.

[NOTE]
====
. See App 5C.
====

[[v42-9-24]]

^<<v42-9-24,24>>^ For whoever wants to save his soul^&#42;1^ will lose it; but whoever loses his soul for my sake is the one that will save it.

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; J17,​18,​22(Heb.), naph·shohʹ (from neʹphesh). See App 4A.
====

[[v42-9-25]]

^<<v42-9-25,25>>^ Really, what does a man benefit himself if he gains the whole world but loses his own self or suffers damage?

[[v42-9-26]]

^<<v42-9-26,26>>^ For whoever becomes ashamed of me and of my words, the Son of man will be ashamed of this one when he arrives in his glory and that of the Father and of the holy angels.

[[v42-9-27]]

^<<v42-9-27,27>>^ But I tell YOU truthfully, There are some of those standing here that will not taste death at all until first they see the kingdom of God.”

[[v42-9-28]]

^<<v42-9-28,28>>^ In actual fact, about eight days after these words, he took Peter and John and James along and climbed up into the mountain to pray.

[[v42-9-29]]

^<<v42-9-29,29>>^ And as he was praying the appearance of his face became different and his apparel became glitteringly white.^&#42;1^

[NOTE]
====
. Or, “bright.”
====

[[v42-9-30]]

^<<v42-9-30,30>>^ Also, look! two men were conversing with him, who were Moses and E·liʹjah.

[[v42-9-31]]

^<<v42-9-31,31>>^ These appeared with glory and began talking about his departure^&#42;1^ that he was destined to fulfill at Jerusalem.

[NOTE]
====
. “Departure.” Gr., eʹxo·don, as in 2Pe 1:15.
====

[[v42-9-32]]

^<<v42-9-32,32>>^ Now Peter and those with him were weighed down with sleep; but when they got fully awake they saw his glory and the two men standing with him.

[[v42-9-33]]

^<<v42-9-33,33>>^ And as these were being separated from him, Peter said to Jesus: “Instructor, it is fine for us to be here, so let us erect three tents, one for you and one for Moses and one for E·liʹjah,” he not realizing what he was saying.

[[v42-9-34]]

^<<v42-9-34,34>>^ But as he was saying these things a cloud formed and began to overshadow them. As they entered into the cloud, they became fearful.

[[v42-9-35]]

^<<v42-9-35,35>>^ And a voice came out of the cloud, saying: “This is my Son, the one that has been chosen. Listen to him.”

[[v42-9-36]]

^<<v42-9-36,36>>^ And as the voice occurred Jesus was found alone. But they kept quiet and did not report to anyone in those days any of the things they saw.

[[v42-9-37]]

^<<v42-9-37,37>>^ On the succeeding day, when they got down from the mountain, a great crowd met him.

[[v42-9-38]]

^<<v42-9-38,38>>^ And, look! a man cried out from the crowd, saying: “Teacher, I beg you to take a look at my son, because he is my only-begotten,^&#42;1^

[NOTE]
====
. Or, “only one.” Gr., mo·no·ge·nesʹ.
====

[[v42-9-39]]

^<<v42-9-39,39>>^ and, look! a spirit takes him, and suddenly he cries out, and it throws him into convulsions with foam, and it scarcely withdraws from him after bruising him.

[[v42-9-40]]

^<<v42-9-40,40>>^ And I begged your disciples to expel it, but they could not.”

[[v42-9-41]]

^<<v42-9-41,41>>^ In response Jesus said: “O faithless and twisted generation, how long must I continue with YOU and put up with YOU? Lead your son over here.”

[[v42-9-42]]

^<<v42-9-42,42>>^ But even as he was approaching, the demon dashed him to the ground and violently convulsed him. However, Jesus rebuked the unclean spirit and healed the boy and delivered him to his father.

[[v42-9-43]]

^<<v42-9-43,43>>^ Well, they all began to be astounded at the majestic power^&#42;1^ of God.
Now as they were all marveling at all the things he was doing, he said to his disciples:

[NOTE]
====
. “Majestic power.” Or, “majesty.” Gr., me·ga·lei·oʹte·ti; Lat., ma·gni·tuʹdi·ne; J17,​22(Heb.), gedhul·lathʹ.
====

[[v42-9-44]]

^<<v42-9-44,44>>^ “Give lodgment to these words in YOUR ears, for the Son of man is destined to be delivered into the hands of men.”

[[v42-9-45]]

^<<v42-9-45,45>>^ But they continued without understanding of this saying. In fact, it was concealed from them that they might not see through it, and they were afraid to question him about this saying.

[[v42-9-46]]

^<<v42-9-46,46>>^ Then a reasoning entered among them as to who would be^&#42;1^ the greatest of them.

[NOTE]
====
. Or, “who was.”
====

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, knowing the reasoning of their hearts, took a young child, set it beside him

[[v42-9-48]]

^<<v42-9-48,48>>^ and said to them: “Whoever receives this young child on the basis of my name receives me &#91;too&#93;, and whoever receives me receives him &#91;also&#93; that sent me forth. For he that conducts himself as a lesser one among all of YOU is the one that is^&#42;1^ great.”

[NOTE]
====
. Or, “is to be.”
====

[[v42-9-49]]

^<<v42-9-49,49>>^ In response John said: “Instructor, we saw a certain man expelling demons by the use of your name and we tried to prevent him, because he is not following^&#42;1^ with us.”

[NOTE]
====
. Or, “going.”
====

[[v42-9-50]]

^<<v42-9-50,50>>^ But Jesus said to him: “Do not YOU men try to prevent &#91;him&#93;, for he that is not against YOU is for YOU.”

[[v42-9-51]]

^<<v42-9-51,51>>^ As the days were now coming to the full for him to be taken up,^&#42;1^ he firmly set his face to go to Jerusalem.

[NOTE]
====
. Or, “for his ascension.”
====

[[v42-9-52]]

^<<v42-9-52,52>>^ So he sent forth messengers in advance of him. And they went their way and entered into a village of Sa·marʹi·tans, to make preparation for him;

[[v42-9-53]]

^<<v42-9-53,53>>^ but they did not receive him, because his face was set for going to Jerusalem.

[[v42-9-54]]

^<<v42-9-54,54>>^ When the disciples James and John saw this they said: “Lord,^&#42;1^ do you want us to tell fire to come down from heaven and annihilate them?”

[NOTE]
====
. Or, “Master.”
====

[[v42-9-55]]

^<<v42-9-55,55>>^ But he turned and rebuked them.

[[v42-9-56]]

^<<v42-9-56,56>>^ So they went to a different village.

[[v42-9-57]]

^<<v42-9-57,57>>^ Now as they were going on the road, someone said to him: “I will follow you to wherever you may depart.”

[[v42-9-58]]

^<<v42-9-58,58>>^ And Jesus said to him: “Foxes have dens and birds of heaven have roosts, but the Son of man has nowhere to lay down his head.”

[[v42-9-59]]

^<<v42-9-59,59>>^ Then he said to another: “Be my follower.” The man said: “Permit me first to leave and bury my father.”

[[v42-9-60]]

^<<v42-9-60,60>>^ But he said to him: “Let the dead bury their dead, but you go away and declare abroad the kingdom of God.”

[[v42-9-61]]

^<<v42-9-61,61>>^ And still another said: “I will follow you, Lord; but first permit me to say good-bye to those in my household.”^&#42;1^

[NOTE]
====
. Or, “house.”
====

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus said to him: “No man that has put his hand to a plow and looks at the things behind is well fitted for the kingdom of God.”

'''

xref:042-luke/042-luke-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-luke/042-luke-010.adoc#v42-10-0[Próximo Capítulo &#62;]