include::./index.adoc[]

[[v42-11-0]]
=== According to Luke, 11
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-11-1]]

^<<v42-11-1,1>>^ Now on the occasion of his being in a certain place praying, when he stopped, a certain one of his disciples said to him: “Lord, teach us how to pray, just as John also taught his disciples.”

[[v42-11-2]]

^<<v42-11-2,2>>^ Then he said to them: “Whenever YOU pray, say, ‘Father, let your name be sanctified.^&#42;1^ Let your kingdom come.

[NOTE]
====
. Or, “let . . . be held sacred; let . . . be treated as holy.” Gr., ha·gi·a·stheʹto; Lat., sanc·ti·fi·ceʹtur; J17,​18(Heb.), yith·qad·dashʹ.
====

[[v42-11-3]]

^<<v42-11-3,3>>^ Give us our bread for the day according to the day’s requirement.

[[v42-11-4]]

^<<v42-11-4,4>>^ And forgive us our sins, for we ourselves also forgive everyone that is in debt to us; and do not bring us into temptation.’”

[[v42-11-5]]

^<<v42-11-5,5>>^ Further, he said to them: “Who of YOU will have a friend and will go to him at midnight and say to him, ‘Friend, loan me three loaves,

[[v42-11-6]]

^<<v42-11-6,6>>^ because a friend of mine has just come to me on a journey and I have nothing to set before him’?

[[v42-11-7]]

^<<v42-11-7,7>>^ And that one from inside says in reply, ‘Quit making me trouble. The door is already locked, and my young children are with me in bed; I cannot rise up and give you anything.’

[[v42-11-8]]

^<<v42-11-8,8>>^ I tell YOU, Although he will not rise up and give him anything because of being his friend, certainly because of his bold persistence he will get up and give him what things he needs.

[[v42-11-9]]

^<<v42-11-9,9>>^ Accordingly I say to YOU, Keep on asking, and it will be given YOU; keep on seeking, and YOU will find; keep on knocking, and it will be opened to YOU.

[[v42-11-10]]

^<<v42-11-10,10>>^ For everyone asking receives, and everyone seeking finds, and to everyone knocking it will be opened.

[[v42-11-11]]

^<<v42-11-11,11>>^ Indeed, which father is there among YOU who, if his son asks for a fish, will perhaps hand him a serpent instead of a fish?

[[v42-11-12]]

^<<v42-11-12,12>>^ Or if he also asks for an egg, will hand him a scorpion?

[[v42-11-13]]

^<<v42-11-13,13>>^ Therefore, if YOU, although being wicked, know how to give good gifts to YOUR children, how much more so will the Father in heaven give holy spirit to those asking him!”

[[v42-11-14]]

^<<v42-11-14,14>>^ Later he was expelling a dumb demon. After the demon came out, the dumb man spoke. And the crowds marveled.

[[v42-11-15]]

^<<v42-11-15,15>>^ But certain ones of them said: “He expels the demons by means of Be·elʹze·bub^&#42;1^ the ruler of the demons.”

[NOTE]
====
. “Beelzebub,” VgSyc,p,s; P45,​75ACDW(Gr.), Be·el·ze·boulʹ; אB(Gr.), Be·e·ze·boulʹ. See Mt 12:24 ftn.
====

[[v42-11-16]]

^<<v42-11-16,16>>^ However, others, to tempt him, began seeking a sign out of heaven from him.

[[v42-11-17]]

^<<v42-11-17,17>>^ Knowing their imaginations he said to them: “Every kingdom divided against itself comes to desolation, and a house &#91;divided&#93; against itself falls.

[[v42-11-18]]

^<<v42-11-18,18>>^ So if Satan is also divided against himself, how will his kingdom stand? Because YOU say I expel the demons by means of Be·elʹze·bub.

[[v42-11-19]]

^<<v42-11-19,19>>^ If it is by means of Be·elʹze·bub I expel the demons, by whom do YOUR sons expel them? Because of this they will be judges of YOU.

[[v42-11-20]]

^<<v42-11-20,20>>^ But if it is by means of God’s finger I expel the demons, the kingdom of God has really overtaken YOU.

[[v42-11-21]]

^<<v42-11-21,21>>^ When a strong man, well armed, guards his palace, his belongings continue in peace.

[[v42-11-22]]

^<<v42-11-22,22>>^ But when someone stronger than he is comes against him and conquers him, he takes away his full armament in which he was trusting, and he divides out the things he despoiled him of.

[[v42-11-23]]

^<<v42-11-23,23>>^ He that is not on my side is against me, and he that does not gather with me scatters.

[[v42-11-24]]

^<<v42-11-24,24>>^ “When an unclean spirit comes out of a man, it passes through parched places in search of a resting-place, and, after finding none, it says, ‘I will return to my house out of which I moved.’

[[v42-11-25]]

^<<v42-11-25,25>>^ And on arriving it finds it swept clean^&#42;1^ and adorned.

[NOTE]
====
. “Unoccupied, swept clean,” B.
====

[[v42-11-26]]

^<<v42-11-26,26>>^ Then it goes its way and takes along seven different^&#42;1^ spirits more wicked than itself, and, after getting inside, they dwell there; and the final circumstances of that man become worse than the first.”

[NOTE]
====
. Or, “other.”
====

[[v42-11-27]]

^<<v42-11-27,27>>^ Now as he was saying these things a certain woman out of the crowd raised her voice and said to him: “Happy is the womb that carried you and the breasts that you sucked!”

[[v42-11-28]]

^<<v42-11-28,28>>^ But he said: “No, rather, Happy are those hearing the word of God and keeping it!”

[[v42-11-29]]

^<<v42-11-29,29>>^ When the crowds were massing together, he started to say: “This generation is a wicked generation; it looks for a sign. But no sign will be given it except the sign of Joʹnah.

[[v42-11-30]]

^<<v42-11-30,30>>^ For just as Joʹnah became a sign to the Ninʹe·vites, in the same way will the Son of man be also to this generation.

[[v42-11-31]]

^<<v42-11-31,31>>^ The queen of the south will be raised up in the judgment with the men of this generation and will condemn them; because she came from the ends^&#42;1^ of the earth to hear the wisdom of Solʹo·mon, but, look! something more than Solʹo·mon is here.

[NOTE]
====
. See Mt 12:42 ftn.
====

[[v42-11-32]]

^<<v42-11-32,32>>^ The men of Ninʹe·veh will rise in the judgment with this generation and will condemn it; because they repented at what Joʹnah preached; but, look! something more than Joʹnah is here.

[[v42-11-33]]

^<<v42-11-33,33>>^ After lighting a lamp, a person puts it, not in a vault nor under a measuring basket, but upon the lampstand, that those stepping in may behold the light.

[[v42-11-34]]

^<<v42-11-34,34>>^ The lamp of the body is your eye. When your eye is simple,^&#42;1^ your whole body is also bright; but when it is wicked,^&#42;2^ your body is also dark.

[NOTE]
====
. Or, “sincere; all one way; in focus; generous.”
. Or, “bad; envious.”
====

[[v42-11-35]]

^<<v42-11-35,35>>^ Be alert, therefore. Perhaps the light that is in you is darkness.

[[v42-11-36]]

^<<v42-11-36,36>>^ Therefore, if your whole body is bright with no part at all dark, it will all be as bright as when a lamp gives you light by its rays.”

[[v42-11-37]]

^<<v42-11-37,37>>^ When he had spoken this, a Pharisee requested him to dine with him. So he went in and reclined at the table.

[[v42-11-38]]

^<<v42-11-38,38>>^ However, the Pharisee was surprised at seeing that he did not first wash^&#42;1^ before the dinner.

[NOTE]
====
. Lit., “he was not first dipped (baptized).”
====

[[v42-11-39]]

^<<v42-11-39,39>>^ But the Lord said to him: “Now YOU Pharisees, YOU cleanse the outside of the cup and dish, but the inside of YOU is full of plunder and wickedness.

[[v42-11-40]]

^<<v42-11-40,40>>^ Unreasonable persons! He that made the outside made also the inside, did he not?

[[v42-11-41]]

^<<v42-11-41,41>>^ Nevertheless, give as gifts of mercy the things that are inside, and, look! all &#91;other&#93; things are clean about YOU.^&#42;1^

[NOTE]
====
. Or, “to you.”
====

[[v42-11-42]]

^<<v42-11-42,42>>^ But woe to YOU Pharisees, because YOU give the tenth of the mint and the rue and of every &#91;other&#93; vegetable, but YOU pass by the justice^&#42;1^ and the love of God! These things YOU were under obligation to do, but those other things not to omit.

[NOTE]
====
. Or, “the judgment.” Gr., ten kriʹsin; Lat., iu·diʹci·um; J17,​18,​22(Heb.), ham·mish·patʹ.
====

[[v42-11-43]]

^<<v42-11-43,43>>^ Woe to YOU Pharisees, because YOU love the front seats in the synagogues and the greetings in the marketplaces!^&#42;1^

[NOTE]
====
. Or, “places of assembly.” Gr., a·go·raisʹ.
====

[[v42-11-44]]

^<<v42-11-44,44>>^ Woe to YOU, because YOU are as those memorial tombs which are not in evidence, so that men walk upon them and do not know &#91;it&#93;!”

[[v42-11-45]]

^<<v42-11-45,45>>^ In answer a certain one of those versed in the Law said to him: “Teacher, in saying these things you also insult us.”

[[v42-11-46]]

^<<v42-11-46,46>>^ Then he said: “Woe also to YOU who are versed in the Law, because YOU load men with loads hard to be borne, but YOU yourselves do not touch the loads with one of YOUR fingers!

[[v42-11-47]]

^<<v42-11-47,47>>^ “Woe to YOU, because YOU build the memorial tombs of the prophets, but YOUR forefathers killed them!

[[v42-11-48]]

^<<v42-11-48,48>>^ Certainly YOU are witnesses of the deeds of YOUR forefathers and yet YOU give consent to them, because these killed the prophets^&#42;1^ but YOU are building &#91;their tombs&#93;.

[NOTE]
====
. Lit., “killed them.”
====

[[v42-11-49]]

^<<v42-11-49,49>>^ On this account the wisdom of God also said, ‘I will send forth to them prophets and apostles, and they will kill and persecute some of them,

[[v42-11-50]]

^<<v42-11-50,50>>^ so that the blood of all the prophets spilled from the founding^&#42;1^ of the world may be required from this generation,

[NOTE]
====
. Lit., “a throwing down [of seed].” Gr., ka·ta·bo·lesʹ.
====

[[v42-11-51]]

^<<v42-11-51,51>>^ from the blood of Abel down to the blood of Zech·a·riʹah, who was slain between the altar and the house.’ Yes, I tell YOU, it will be required from this generation.

[[v42-11-52]]

^<<v42-11-52,52>>^ “Woe to YOU who are versed in the Law, because YOU took away the key of knowledge; YOU yourselves did not go in, and those going in YOU hindered!”

[[v42-11-53]]

^<<v42-11-53,53>>^ So when he went out from there the scribes and the Pharisees started in to press upon him terribly and to ply him with questions about further things,

[[v42-11-54]]

^<<v42-11-54,54>>^ lying in wait for him, to catch something out of his mouth.

'''

xref:042-luke/042-luke-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-luke/042-luke-012.adoc#v42-12-0[Próximo Capítulo &#62;]