include::./index.adoc[]

[[v42-20-0]]
=== According to Luke, 20
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-20-1]]

^<<v42-20-1,1>>^ On one of the days while he was teaching the people in the temple and declaring the good news, the chief priests and the scribes with the older men came near,

[[v42-20-2]]

^<<v42-20-2,2>>^ and they spoke up, saying to him: “Tell us by what authority you do these things, or who it is that gave you this authority.”

[[v42-20-3]]

^<<v42-20-3,3>>^ In reply he said to them: “I will also ask YOU a question, and YOU tell me:

[[v42-20-4]]

^<<v42-20-4,4>>^ Was the baptism^&#42;1^ of John from heaven or from men?”

[NOTE]
====
. Or, “immersion; dipping.” Gr., baʹpti·sma.
====

[[v42-20-5]]

^<<v42-20-5,5>>^ Then among themselves they drew conclusions, saying: “If we say, ‘From heaven,’ he will say, ‘Why is it YOU did not believe him?’

[[v42-20-6]]

^<<v42-20-6,6>>^ But if we say, ‘From men,’ the people one and all will stone us, for they are persuaded that John was a prophet.”

[[v42-20-7]]

^<<v42-20-7,7>>^ So they replied that they did not know its source.

[[v42-20-8]]

^<<v42-20-8,8>>^ And Jesus said to them: “Neither am I telling YOU by what authority I do these things.”

[[v42-20-9]]

^<<v42-20-9,9>>^ Then he started to tell the people this illustration: “A man planted a vineyard and let it out to cultivators, and he traveled abroad for considerable time.

[[v42-20-10]]

^<<v42-20-10,10>>^ But in due season he sent out a slave to the cultivators, that they might give him some of the fruit of the vineyard. The cultivators, however, sent him away empty, after beating him up.

[[v42-20-11]]

^<<v42-20-11,11>>^ But he repeated and sent them a different slave. That one also they beat up and dishonored and sent away empty.

[[v42-20-12]]

^<<v42-20-12,12>>^ Yet again he sent a third; this one also they wounded and threw out.

[[v42-20-13]]

^<<v42-20-13,13>>^ At this the owner of the vineyard said, ‘What shall I do? I will send my son the beloved. Likely they will respect this one.’

[[v42-20-14]]

^<<v42-20-14,14>>^ When the cultivators caught sight of him they went reasoning with one another, saying, ‘This is the heir; let us kill him, that the inheritance may become ours.’

[[v42-20-15]]

^<<v42-20-15,15>>^ With that they threw him outside the vineyard and killed him. What, therefore, will the owner of the vineyard do to them?

[[v42-20-16]]

^<<v42-20-16,16>>^ He will come and destroy these cultivators and will give the vineyard to others.”
On hearing &#91;this&#93; they said: “Never may that happen!”

[[v42-20-17]]

^<<v42-20-17,17>>^ But he looked upon them and said: “What, then, does this that is written mean, ‘The stone which the builders rejected, this has become the chief cornerstone’?

[[v42-20-18]]

^<<v42-20-18,18>>^ Everyone falling upon that stone will be shattered. As for anyone upon whom it falls, it will pulverize him.”

[[v42-20-19]]

^<<v42-20-19,19>>^ The scribes and the chief priests now sought to get their hands on him in that very hour, but they feared the people; for they perceived that he spoke this illustration with them in mind.

[[v42-20-20]]

^<<v42-20-20,20>>^ And, after observing him closely, they sent out men secretly hired to pretend that they were righteous, in order that they might catch him in speech, so as to turn him over to the government and to the authority of the governor.

[[v42-20-21]]

^<<v42-20-21,21>>^ And they questioned him, saying: “Teacher, we know you speak and teach correctly and show no partiality, but you teach the way of God in line with truth:

[[v42-20-22]]

^<<v42-20-22,22>>^ Is it lawful for us to pay tax to Caesar^&#42;1^ or not?”

[NOTE]
====
. Or, “to the emperor.” Gr., Kaiʹsa·ri; Lat., Caeʹsa·ri.
====

[[v42-20-23]]

^<<v42-20-23,23>>^ But he detected their cunning and said to them:

[[v42-20-24]]

^<<v42-20-24,24>>^ “Show me a de·narʹi·us.^&#42;1^ Whose image and inscription does it have?” They said: “Caesar’s.”

[NOTE]
====
. A Roman silver coin that weighed 3.85 g (0.124 oz t).
====

[[v42-20-25]]

^<<v42-20-25,25>>^ He said to them: “By all means, then, pay back Caesar’s things to Caesar, but God’s things to God.”

[[v42-20-26]]

^<<v42-20-26,26>>^ Well, they were not able to catch him in this saying before the people, but, in amazement at his answer, they said nothing.

[[v42-20-27]]

^<<v42-20-27,27>>^ However, some of the Sadducees, those who say there is no resurrection, came up and questioned him,

[[v42-20-28]]

^<<v42-20-28,28>>^ saying: “Teacher, Moses wrote us, ‘If a man’s brother dies having a wife, but this one remained childless, his brother should take the wife and raise up offspring from her for his brother.’

[[v42-20-29]]

^<<v42-20-29,29>>^ Accordingly there were seven brothers; and the first took a wife and died childless.

[[v42-20-30]]

^<<v42-20-30,30>>^ So the second,

[[v42-20-31]]

^<<v42-20-31,31>>^ and the third took her. Likewise even the seven: they did not leave children behind, but died off.

[[v42-20-32]]

^<<v42-20-32,32>>^ Lastly, the woman also died.

[[v42-20-33]]

^<<v42-20-33,33>>^ Consequently, in the resurrection,^&#42;1^ of which one of them does she become &#91;the&#93; wife? For the seven got her as wife.”

[NOTE]
====
. “Resurrection.” Gr., a·na·staʹsei, “raising up; standing up” (from a·naʹ, “up,” and staʹsis, “standing”); Lat., re·sur·rec·ti·oʹne.
====

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus said to them: “The children of this system of things^&#42;1^ marry and are given in marriage,

[NOTE]
====
. Or, “order of things.” Gr., ai·oʹnos; Lat., saeʹcu·li; J17,​18,​22(Heb.), ha·ʽoh·lamʹ, “the order of things.”
====

[[v42-20-35]]

^<<v42-20-35,35>>^ but those who have been counted worthy of gaining that system of things and the resurrection from the dead neither marry nor are given in marriage.

[[v42-20-36]]

^<<v42-20-36,36>>^ In fact, neither can they die anymore, for they are like the angels, and they are God’s children^&#42;1^ by being children of the resurrection.

[NOTE]
====
. “Children.” Or, “sons.”
====

[[v42-20-37]]

^<<v42-20-37,37>>^ But that the dead are raised up even Moses disclosed, in the account about the thornbush, when he calls Jehovah^&#42;1^ ‘the God of Abraham^&#42;2^ and God of Isaac and God of Jacob.’

[NOTE]
====
. See App 1D.
. Or, “when he says: ‘Jehovah the God of Abraham.’ ”
====

[[v42-20-38]]

^<<v42-20-38,38>>^ He is a God, not of the dead, but of the living, for they are all living to him.”^&#42;1^

[NOTE]
====
. Or, “living from his standpoint.”
====

[[v42-20-39]]

^<<v42-20-39,39>>^ In response some of the scribes said: “Teacher, you spoke well.”

[[v42-20-40]]

^<<v42-20-40,40>>^ For no longer did they have the courage to ask him a single question.

[[v42-20-41]]

^<<v42-20-41,41>>^ In turn he said to them: “How is it they say that the Christ is David’s son?

[[v42-20-42]]

^<<v42-20-42,42>>^ For David himself says in the book of Psalms, ‘Jehovah^&#42;1^ said to my Lord, Sit at my right hand

[NOTE]
====
. See App 1D.
====

[[v42-20-43]]

^<<v42-20-43,43>>^ until I place your enemies as a stool for your feet.’

[[v42-20-44]]

^<<v42-20-44,44>>^ David, therefore, calls him ‘Lord’; so how is he his son?”

[[v42-20-45]]

^<<v42-20-45,45>>^ Then, while all the people were listening he said to the disciples:

[[v42-20-46]]

^<<v42-20-46,46>>^ “Look out for the scribes who desire to walk around in robes and like greetings in the marketplaces^&#42;1^ and front seats in the synagogues and most prominent places at evening meals,

[NOTE]
====
. See 11:43 ftn.
====

[[v42-20-47]]

^<<v42-20-47,47>>^ and who devour the houses of the widows and for a pretext make long prayers. These will receive a heavier judgment.”

'''

xref:042-luke/042-luke-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-luke/042-luke-021.adoc#v42-21-0[Próximo Capítulo &#62;]