include::./index.adoc[]

[[v42-13-0]]
=== According to Luke, 13
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-13-1]]

^<<v42-13-1,1>>^ At that very season there were certain ones present that reported to him about the Gal·i·leʹans whose blood Pilate had mixed with their sacrifices.

[[v42-13-2]]

^<<v42-13-2,2>>^ So in reply he said to them: “Do YOU imagine that these Gal·i·leʹans were proved worse sinners than all other Gal·i·leʹans because they have suffered these things?

[[v42-13-3]]

^<<v42-13-3,3>>^ No, indeed, I tell YOU; but, unless YOU repent, YOU will all likewise be destroyed.

[[v42-13-4]]

^<<v42-13-4,4>>^ Or those eighteen upon whom the tower in Si·loʹam^&#42;1^ fell, thereby killing them, do YOU imagine that they were proved greater debtors than all other men inhabiting Jerusalem?

[NOTE]
====
. “Siloam,” אAB; J17,​18,​22, “Shiloah.”
====

[[v42-13-5]]

^<<v42-13-5,5>>^ No, indeed, I tell YOU; but, unless YOU repent, YOU will all be destroyed in the same way.”

[[v42-13-6]]

^<<v42-13-6,6>>^ Then he went on to tell this illustration: “A certain man had a fig tree planted in his vineyard, and he came looking for fruit on it, but found none.

[[v42-13-7]]

^<<v42-13-7,7>>^ Then he said to the vinedresser, ‘Here it is three years that I have come looking for fruit on this fig tree, but have found none. Cut it down! Why really should it keep the ground useless?’

[[v42-13-8]]

^<<v42-13-8,8>>^ In reply he said to him, ‘Master, let it alone also this year, until I dig around it and put on manure;

[[v42-13-9]]

^<<v42-13-9,9>>^ and if then it produces fruit in the future, &#91;well and good&#93;; but if not, you shall^&#42;1^ cut it down.’”

[NOTE]
====
. Or, “must.”
====

[[v42-13-10]]

^<<v42-13-10,10>>^ Now he was teaching in one of the synagogues on the sabbath.

[[v42-13-11]]

^<<v42-13-11,11>>^ And, look! a woman with a spirit of weakness for eighteen years, and she was bent double and was unable to raise herself up at all.

[[v42-13-12]]

^<<v42-13-12,12>>^ When he saw her, Jesus addressed her and said to her: “Woman, you are released from your weakness.”

[[v42-13-13]]

^<<v42-13-13,13>>^ And he laid his hands on her; and instantly she straightened up, and began to glorify God.

[[v42-13-14]]

^<<v42-13-14,14>>^ But in response the presiding officer of the synagogue, indignant because Jesus did the cure on the sabbath, began to say to the crowd: “There are six days on which work ought to be done; on them, therefore, come and be cured, and not on the sabbath day.”

[[v42-13-15]]

^<<v42-13-15,15>>^ However, the Lord^&#42;1^ answered him and said: “Hypocrites, does not each one of YOU on the sabbath untie his bull or his ass from the stall and lead it away to give it drink?

[NOTE]
====
. Or, “Master.”
====

[[v42-13-16]]

^<<v42-13-16,16>>^ Was it not due, then, for this woman who is a daughter of Abraham, and whom Satan held bound, look! eighteen years, to be loosed from this bond on the sabbath day?”

[[v42-13-17]]

^<<v42-13-17,17>>^ Well, when he said these things, all his opposers began to feel shame; but all the crowd began to rejoice at all the glorious things done by him.

[[v42-13-18]]

^<<v42-13-18,18>>^ Therefore he went on to say: “What is the kingdom of God like, and with what shall I compare it?

[[v42-13-19]]

^<<v42-13-19,19>>^ It is like a mustard grain that a man took and put in his garden, and it grew and became a tree, and the birds of heaven took up lodging in its branches.”

[[v42-13-20]]

^<<v42-13-20,20>>^ And again he said: “With what shall I compare the kingdom of God?

[[v42-13-21]]

^<<v42-13-21,21>>^ It is like leaven, which a woman took and hid in^&#42;1^ three large measures^&#42;2^ of flour until the whole mass was fermented.”

[NOTE]
====
. Or, “mixed with.”
. Lit., “seah measures.” Gr., saʹta. A seah measure equaled 7.33 L (6.66 dry qt).
====

[[v42-13-22]]

^<<v42-13-22,22>>^ And he journeyed through from city to city and from village to village, teaching and continuing on his journey to Jerusalem.

[[v42-13-23]]

^<<v42-13-23,23>>^ Now a certain man said to him: “Lord, are those who are being saved few?” He said to them:

[[v42-13-24]]

^<<v42-13-24,24>>^ “Exert yourselves vigorously^&#42;1^ to get in through the narrow door, because many, I tell YOU, will seek to get in but will not be able,

[NOTE]
====
. Lit., “Be struggling.”
====

[[v42-13-25]]

^<<v42-13-25,25>>^ when once the householder has got up and locked the door, and YOU start to stand outside and to knock at the door, saying, ‘Sir, open to us.’ But in answer he will say to YOU, ‘I do not know where YOU are from.’

[[v42-13-26]]

^<<v42-13-26,26>>^ Then YOU will start saying, ‘We ate and drank in front of you, and you taught in our broad ways.’

[[v42-13-27]]

^<<v42-13-27,27>>^ But he will speak and say to YOU, ‘I do not know where YOU are from. Get away from me, all YOU workers of unrighteousness!’

[[v42-13-28]]

^<<v42-13-28,28>>^ There is where &#91;YOUR&#93; weeping and the gnashing of &#91;YOUR&#93; teeth will be, when YOU see Abraham and Isaac and Jacob and all the prophets in the kingdom of God, but yourselves thrown outside.

[[v42-13-29]]

^<<v42-13-29,29>>^ Furthermore, people will come from eastern parts and western, and from north and south, and will recline at the table in the kingdom of God.

[[v42-13-30]]

^<<v42-13-30,30>>^ And, look! there are those last who will be first, and there are those first who will be last.”

[[v42-13-31]]

^<<v42-13-31,31>>^ In that very hour certain Pharisees came up, saying to him: “Get out and be on your way from here, because Herod^&#42;1^ wants to kill you.”

[NOTE]
====
. That is, Herod Antipas, son of Herod the Great. See 3:1.
====

[[v42-13-32]]

^<<v42-13-32,32>>^ And he said to them: “Go and tell that fox, ‘Look! I am casting out demons and accomplishing healing today and tomorrow, and the third day I shall be finished.’^&#42;1^

[NOTE]
====
. Lit., “I am being perfected.”
====

[[v42-13-33]]

^<<v42-13-33,33>>^ Nevertheless, I must go on my way today and tomorrow and the following day, because it is not admissible for a prophet to be destroyed outside of Jerusalem.

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalem, Jerusalem, the killer of the prophets and stoner of those sent forth to her—how often I wanted to gather your children together in the manner that a hen gathers her brood of chicks under her wings, but YOU people did not want &#91;it&#93;!

[[v42-13-35]]

^<<v42-13-35,35>>^ Look! YOUR house is abandoned to YOU. I tell YOU, YOU will by no means see me until YOU say, ‘Blessed is he that comes in Jehovah’s^&#42;1^ name.’”

[NOTE]
====
. See App 1D.
====

'''

xref:042-luke/042-luke-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-luke/042-luke-014.adoc#v42-14-0[Próximo Capítulo &#62;]