include::./index.adoc[]

[[v42-19-0]]
=== According to Luke, 19
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-19-1]]

^<<v42-19-1,1>>^ And he entered Jerʹi·cho and was going through.

[[v42-19-2]]

^<<v42-19-2,2>>^ Now here there was a man called by the name Zac·chaeʹus; and he was a chief tax collector, and he was rich.

[[v42-19-3]]

^<<v42-19-3,3>>^ Well, he was seeking to see who this Jesus was, but he could not for the crowd, because he was small in size.

[[v42-19-4]]

^<<v42-19-4,4>>^ So he ran ahead to an advance position and climbed a fig-mulberry tree^&#42;1^ in order to see him, because he was about to go through that way.

[NOTE]
====
. Or, “sycamore tree.”
====

[[v42-19-5]]

^<<v42-19-5,5>>^ Now when Jesus got to the place, he looked up and said to him: “Zac·chaeʹus, hurry and get down, for today I must stay in your house.”

[[v42-19-6]]

^<<v42-19-6,6>>^ With that he hurried and got down and with rejoicing he received him as guest.

[[v42-19-7]]

^<<v42-19-7,7>>^ But when they saw &#91;it&#93;, they all fell to muttering, saying: “With a man that is a sinner he went in to lodge.”

[[v42-19-8]]

^<<v42-19-8,8>>^ But Zac·chaeʹus stood up and said to the Lord:^&#42;1^ “Look! The half of my belongings, Lord, I am giving to the poor, and whatever I extorted from anyone by false accusation I am restoring fourfold.”

[NOTE]
====
. Or, “Master.”
====

[[v42-19-9]]

^<<v42-19-9,9>>^ At this Jesus said to him: “This day salvation has come to this house, because he also is a son of Abraham.

[[v42-19-10]]

^<<v42-19-10,10>>^ For the Son of man came to seek and to save what was lost.”

[[v42-19-11]]

^<<v42-19-11,11>>^ While they were listening to these things he spoke in addition an illustration, because he was near Jerusalem and they were imagining that the kingdom of God was going to display itself instantly.

[[v42-19-12]]

^<<v42-19-12,12>>^ Therefore he said: “A certain man of noble birth traveled to a distant land to secure kingly power^&#42;1^ for himself and to return.

[NOTE]
====
. Or, “secure a kingdom.”
====

[[v42-19-13]]

^<<v42-19-13,13>>^ Calling ten slaves of his he gave them ten miʹnas^&#42;1^ and told them, ‘Do business till I come.’

[NOTE]
====
. A Gr. mina weighed 340 g (10.9 oz t); not a coin, and different from the Heb. mina.
====

[[v42-19-14]]

^<<v42-19-14,14>>^ But his citizens hated him and sent out a body of ambassadors after him, to say, ‘We do not want this &#91;man&#93; to become king over us.’

[[v42-19-15]]

^<<v42-19-15,15>>^ “Eventually when he got back after having secured the kingly power,^&#42;1^ he commanded to be called to him these slaves to whom he had given the silver money, in order to ascertain what they had gained by business activity.

[NOTE]
====
. Or, “kingdom.” Gr., ba·si·leiʹan; Lat., reʹgno.
====

[[v42-19-16]]

^<<v42-19-16,16>>^ Then the first one presented himself, saying, ‘Lord,^&#42;1^ your miʹna gained ten miʹnas.’

[NOTE]
====
. Or, “Master.”
====

[[v42-19-17]]

^<<v42-19-17,17>>^ So he said to him, ‘Well done, good slave! Because in a very small matter you have proved yourself faithful, hold authority over ten cities.’

[[v42-19-18]]

^<<v42-19-18,18>>^ Now the second came, saying, ‘Your miʹna, Lord, made five miʹnas.’

[[v42-19-19]]

^<<v42-19-19,19>>^ He said to this one also, ‘You, too, be in charge of five cities.’

[[v42-19-20]]

^<<v42-19-20,20>>^ But a different one^&#42;1^ came, saying, ‘Lord, here is your miʹna, that I kept laid away in a cloth.

[NOTE]
====
. Or, “another one.” Sys, “the last one.”
====

[[v42-19-21]]

^<<v42-19-21,21>>^ You see, I was in fear of you, because you are a harsh man; you take up what you did not deposit and you reap what you did not sow.’

[[v42-19-22]]

^<<v42-19-22,22>>^ He said to him, ‘Out of your own mouth I judge you, wicked slave. You knew, did you, that I am a harsh man, taking up what I did not deposit and reaping what I did not sow?

[[v42-19-23]]

^<<v42-19-23,23>>^ Hence why is it you did not put my silver money in a bank? Then on my arrival I would have collected it with interest.’

[[v42-19-24]]

^<<v42-19-24,24>>^ “With that he said to those standing by, ‘Take the miʹna from him and give it to him that has the ten miʹnas.’

[[v42-19-25]]

^<<v42-19-25,25>>^ But they said to him, ‘Lord, he has ten miʹnas!’—

[[v42-19-26]]

^<<v42-19-26,26>>^ ‘I say to YOU, To everyone that has, more will be given; but from the one that does not have, even what he has will be taken away.

[[v42-19-27]]

^<<v42-19-27,27>>^ Moreover, these enemies of mine that did not want me to become king over them BRING here and slaughter them before me.’”

[[v42-19-28]]

^<<v42-19-28,28>>^ So, after he had said these things, he began to go on ahead, going up to Jerusalem.

[[v42-19-29]]

^<<v42-19-29,29>>^ And when he got near to Bethʹpha·ge and Bethʹa·ny at the mountain called Mount of Olives, he sent forth two of the disciples,

[[v42-19-30]]

^<<v42-19-30,30>>^ saying: “Go into the village that is within sight of YOU, and in it after YOU pass in YOU will find a colt tied, on which none of mankind ever sat. Loose it and bring it.

[[v42-19-31]]

^<<v42-19-31,31>>^ But if anyone asks YOU, ‘Why is it YOU are loosing it?’ YOU must speak in this way, ‘The Lord needs it.’”

[[v42-19-32]]

^<<v42-19-32,32>>^ So those who were sent forth departed and found it just as he said to them.

[[v42-19-33]]

^<<v42-19-33,33>>^ But as they were loosing the colt the owners of it said to them: “Why are YOU loosing the colt?”

[[v42-19-34]]

^<<v42-19-34,34>>^ They said: “The Lord needs it.”

[[v42-19-35]]

^<<v42-19-35,35>>^ And they led it to Jesus, and they threw their outer garments upon the colt and set Jesus upon &#91;it&#93;.

[[v42-19-36]]

^<<v42-19-36,36>>^ As he moved along they kept spreading their outer garments on the road.

[[v42-19-37]]

^<<v42-19-37,37>>^ As soon as he got near the road down the Mount of Olives all the multitude of the disciples started to rejoice and praise God with a loud voice concerning all the powerful works they had seen,

[[v42-19-38]]

^<<v42-19-38,38>>^ saying: “Blessed is the One coming as the King in Jehovah’s^&#42;1^ name! Peace in heaven, and glory in the highest places!”^&#42;2^

[NOTE]
====
. See App 1D.
. Or, “in the heights above.”
====

[[v42-19-39]]

^<<v42-19-39,39>>^ However, some of the Pharisees from the crowd said to him: “Teacher, rebuke your disciples.”

[[v42-19-40]]

^<<v42-19-40,40>>^ But in reply he said: “I tell YOU, If these remained silent, the stones would cry out.”

[[v42-19-41]]

^<<v42-19-41,41>>^ And when he got nearby, he viewed the city and wept over it,

[[v42-19-42]]

^<<v42-19-42,42>>^ saying: “If you, even you, had discerned in this day the things having to do with peace—but now they have been hid from your eyes.

[[v42-19-43]]

^<<v42-19-43,43>>^ Because the days will come upon you when your enemies will build around you a fortification with pointed stakes and will encircle you and distress you from every side,

[[v42-19-44]]

^<<v42-19-44,44>>^ and they will dash you and your children within you to the ground, and they will not leave a stone upon a stone in you, because you did not discern the time of your being inspected.”

[[v42-19-45]]

^<<v42-19-45,45>>^ And he entered into the temple and started to throw out those who were selling,

[[v42-19-46]]

^<<v42-19-46,46>>^ saying to them: “It is written, ‘And my house will be a house of prayer,’ but YOU made it a cave of robbers.”

[[v42-19-47]]

^<<v42-19-47,47>>^ Furthermore, he went teaching daily in the temple. But the chief priests and the scribes and the principal ones of the people were seeking to destroy him;

[[v42-19-48]]

^<<v42-19-48,48>>^ and yet they did not find the effective thing for them to do, for the people one and all kept hanging onto him to hear him.

'''

xref:042-luke/042-luke-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-luke/042-luke-020.adoc#v42-20-0[Próximo Capítulo &#62;]