include::./index.adoc[]

[[v42-10-0]]
=== According to Luke, 10
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-10-1]]

^<<v42-10-1,1>>^ After these things the Lord designated seventy^&#42;1^ others and sent them forth by twos in advance of him into every city and place to which he himself was going to come.

[NOTE]
====
. “Seventy,” אACWSyp; P75BDVgSyc,sArm, “seventy-two.”
====

[[v42-10-2]]

^<<v42-10-2,2>>^ Then he began to say to them: “The harvest, indeed, is great, but the workers are few. Therefore beg the Master of the harvest to send out workers into his harvest.

[[v42-10-3]]

^<<v42-10-3,3>>^ Go forth. Look! I am sending YOU forth as lambs in among wolves.

[[v42-10-4]]

^<<v42-10-4,4>>^ Do not carry a purse, nor a food pouch, nor sandals, and do not embrace anybody in greeting along the road.

[[v42-10-5]]

^<<v42-10-5,5>>^ Wherever YOU enter into a house say first, ‘May this house have peace.’

[[v42-10-6]]

^<<v42-10-6,6>>^ And if a friend^&#42;1^ of peace is there, YOUR peace will rest upon him.^&#42;2^ But if there is not, it will turn back to YOU.

[NOTE]
====
. Lit., “son.”
. Or, “it.”
====

[[v42-10-7]]

^<<v42-10-7,7>>^ So stay in that house, eating and drinking the things they provide, for the worker is worthy of his wages. Do not be transferring from house to house.

[[v42-10-8]]

^<<v42-10-8,8>>^ “Also, wherever YOU enter into a city and they receive YOU, eat the things set before YOU,

[[v42-10-9]]

^<<v42-10-9,9>>^ and cure the sick ones in it, and go on telling them, ‘The kingdom of God has come near to YOU.’

[[v42-10-10]]

^<<v42-10-10,10>>^ But wherever YOU enter into a city and they do not receive YOU, go out into its broad ways and say,

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Even the dust that got stuck to our feet from YOUR city we wipe off against YOU. Nevertheless, keep this in mind, that the kingdom of God has come near.’

[[v42-10-12]]

^<<v42-10-12,12>>^ I tell YOU that it will be more endurable for Sodʹom in that day than for that city.

[[v42-10-13]]

^<<v42-10-13,13>>^ “Woe to you, Cho·raʹzin! Woe to you, Beth·saʹi·da! because if the powerful works that have taken place in YOU had taken place in Tyre and Siʹdon, they would long ago have repented sitting in sackcloth and ashes.

[[v42-10-14]]

^<<v42-10-14,14>>^ Consequently it will be more endurable for Tyre and Siʹdon in the judgment than for YOU.

[[v42-10-15]]

^<<v42-10-15,15>>^ And you, Ca·perʹna·um, will you perhaps be exalted to heaven? Down to Haʹdes^&#42;1^ you will come!

[NOTE]
====
. “Hades,” אABJ21; J7-18,​22, “Sheol.”
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “He that listens to YOU listens to me &#91;too&#93;. And he that disregards YOU disregards me &#91;too&#93;. Moreover, he that disregards me disregards &#91;also&#93; him that sent me forth.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Then the seventy^&#42;1^ returned with joy, saying: “Lord,^&#42;2^ even the demons are made subject to us by the use of your name.”

[NOTE]
====
. “Seventy,” אACWSyp; P45,​75BDVgArm, “seventy-two.”
. Or, “Master.”
====

[[v42-10-18]]

^<<v42-10-18,18>>^ At that he said to them: “I began to behold Satan already fallen like lightning from heaven.

[[v42-10-19]]

^<<v42-10-19,19>>^ Look! I have given YOU the authority to trample underfoot serpents and scorpions, and over all the power of the enemy, and nothing will by any means do YOU hurt.

[[v42-10-20]]

^<<v42-10-20,20>>^ Nevertheless, do not rejoice over this, that the spirits are made subject to YOU, but rejoice because YOUR names have been inscribed in the heavens.”

[[v42-10-21]]

^<<v42-10-21,21>>^ In that very hour he became overjoyed in the holy spirit and said: “I publicly praise you, Father, Lord of heaven and earth, because you have carefully hidden these things from wise and intellectual ones, and have revealed them to babes. Yes, O Father, because to do thus came to be the way approved by you.

[[v42-10-22]]

^<<v42-10-22,22>>^ All things have been delivered to me by my Father, and who the Son is no one knows but the Father; and who the Father is, no one &#91;knows&#93; but the Son, and he to whom the Son is willing to reveal him.”

[[v42-10-23]]

^<<v42-10-23,23>>^ With that he turned to the disciples by themselves and said: “Happy are the eyes that behold the things YOU are beholding.

[[v42-10-24]]

^<<v42-10-24,24>>^ For I say to YOU, Many prophets and kings desired to see the things YOU are beholding but did not see them, and to hear the things YOU are hearing but did not hear them.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Now, look! a certain man versed in the Law rose up, to test him out, and said: “Teacher, by doing what shall I inherit everlasting life?”

[[v42-10-26]]

^<<v42-10-26,26>>^ He said to him: “What is written in the Law? How do you read?”

[[v42-10-27]]

^<<v42-10-27,27>>^ In answer he said: “‘You must love Jehovah^&#42;1^ your God with your whole heart and with your whole soul^&#42;2^ and with your whole strength and with your whole mind,’ and, ‘your neighbor as yourself.’”

[NOTE]
====
. See App 1D.
. Or, “life.” See App 4A.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ He said to him: “You answered correctly; ‘keep on doing this and you will get life.’”

[[v42-10-29]]

^<<v42-10-29,29>>^ But, wanting to prove himself righteous, the man said to Jesus: “Who really is my neighbor?”

[[v42-10-30]]

^<<v42-10-30,30>>^ In reply Jesus said: “A certain man was going down from Jerusalem to Jerʹi·cho and fell among robbers, who both stripped him and inflicted blows, and went off, leaving him half-dead.

[[v42-10-31]]

^<<v42-10-31,31>>^ Now, by coincidence, a certain priest was going down over that road, but, when he saw him, he went by on the opposite side.

[[v42-10-32]]

^<<v42-10-32,32>>^ Likewise, a Levite also, when he got down to the place and saw him, went by on the opposite side.

[[v42-10-33]]

^<<v42-10-33,33>>^ But a certain Sa·marʹi·tan traveling the road came upon him and, at seeing him, he was moved with pity.

[[v42-10-34]]

^<<v42-10-34,34>>^ So he approached him and bound up his wounds, pouring oil and wine upon them. Then he mounted him upon his own beast and brought him to an inn and took care of him.

[[v42-10-35]]

^<<v42-10-35,35>>^ And the next day he took out two de·narʹi·i,^&#42;1^ gave them to the innkeeper, and said, ‘Take care of him, and whatever you spend besides this, I will repay you when I come back here.’

[NOTE]
====
. See App 8A.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Who of these three seems to you to have made himself neighbor to the man that fell among the robbers?”

[[v42-10-37]]

^<<v42-10-37,37>>^ He said: “The one that acted mercifully toward him.” Jesus then said to him: “Go your way and be doing the same yourself.”

[[v42-10-38]]

^<<v42-10-38,38>>^ Now as they were going their way he entered into a certain village. Here a certain woman named Martha received him as guest into the house.

[[v42-10-39]]

^<<v42-10-39,39>>^ This woman also had a sister called Mary, who, however, sat down at the feet of the Lord and kept listening to his word.

[[v42-10-40]]

^<<v42-10-40,40>>^ Martha, on the other hand, was distracted with attending to many duties. So, she came near and said: “Lord,^&#42;1^ does it not matter to you that my sister has left me alone to attend to things? Tell her, therefore, to join in helping me.”

[NOTE]
====
. Or, “Master.”
====

[[v42-10-41]]

^<<v42-10-41,41>>^ In answer the Lord said to her: “Martha, Martha, you are anxious and disturbed about many things.

[[v42-10-42]]

^<<v42-10-42,42>>^ A few things, though, are needed, or just one.^&#42;1^ For her part, Mary chose the good portion, and it will not be taken away from her.”

[NOTE]
====
. According to אcBCc; P45,​75AC*WVgSyc, “One thing, though, is necessary.”
====

'''

xref:042-luke/042-luke-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-luke/042-luke-011.adoc#v42-11-0[Próximo Capítulo &#62;]