include::./index.adoc[]

[[v42-12-0]]
=== According to Luke, 12
// Rbi8 1984, Rbi8 - New World Translation of the Holy Scriptures—With References

[[v42-12-1]]

^<<v42-12-1,1>>^ In the meantime, when the crowd had gathered together in so many thousands^&#42;1^ that they were stepping upon one another, he started out by saying first to his disciples: “Watch out for the leaven of the Pharisees, which is hypocrisy.

[NOTE]
====
. Lit., “of the myriads.”
====

[[v42-12-2]]

^<<v42-12-2,2>>^ But there is nothing carefully concealed that will not be revealed, and secret that will not become known.

[[v42-12-3]]

^<<v42-12-3,3>>^ Wherefore what things YOU say in the darkness will be heard in the light,^&#42;1^ and what YOU whisper^&#42;2^ in private rooms will be preached from the housetops.

[NOTE]
====
. Or, “in public; without privacy.”
. Lit., “spoke toward the ear.”
====

[[v42-12-4]]

^<<v42-12-4,4>>^ Moreover, I say to YOU, my friends, Do not fear those who kill the body and after this are not able to do anything more.

[[v42-12-5]]

^<<v42-12-5,5>>^ But I will indicate to YOU whom to fear: Fear him who after killing has authority to throw into Ge·henʹna.^&#42;1^ Yes, I tell YOU, fear this One.

[NOTE]
====
. See App 4C.
====

[[v42-12-6]]

^<<v42-12-6,6>>^ Five sparrows sell for two coins of small value,^&#42;1^ do they not? Yet not one of them goes forgotten before God.

[NOTE]
====
. Lit., “for two assarii.” An assarion was one sixteenth of a denarius. See App 8A.
====

[[v42-12-7]]

^<<v42-12-7,7>>^ But even the hairs of YOUR heads are all numbered. Have no fear; YOU are worth more than many sparrows.

[[v42-12-8]]

^<<v42-12-8,8>>^ “I say, then, to YOU, Everyone that confesses union with me before men, the Son of man will also confess union with him before the angels of God.

[[v42-12-9]]

^<<v42-12-9,9>>^ But he that disowns me before men will be disowned before the angels of God.

[[v42-12-10]]

^<<v42-12-10,10>>^ And everyone that says a word against the Son of man, it will be forgiven him; but he that blasphemes against the holy spirit will not be forgiven it.

[[v42-12-11]]

^<<v42-12-11,11>>^ But when they bring YOU in before public assemblies^&#42;1^ and government officials and authorities, do not become anxious about how or what^&#42;2^ YOU will speak in defense or what YOU will say;

[NOTE]
====
. Lit., “synagogues.”
. “How or what,” אABVg; DItSyc,p, “how”; Sys, “what.”
====

[[v42-12-12]]

^<<v42-12-12,12>>^ for the holy spirit will teach YOU in that very hour the things YOU ought to say.”

[[v42-12-13]]

^<<v42-12-13,13>>^ Then a certain one of the crowd said to him: “Teacher, tell my brother to divide the inheritance with me.”

[[v42-12-14]]

^<<v42-12-14,14>>^ He said to him: “Man, who appointed me judge or apportioner^&#42;1^ over YOU persons?”

[NOTE]
====
. Or, “divider.”
====

[[v42-12-15]]

^<<v42-12-15,15>>^ Then he said to them: “Keep YOUR eyes open and guard against every sort of covetousness, because even when a person has an abundance his life does not result from the things he possesses.”

[[v42-12-16]]

^<<v42-12-16,16>>^ With that he spoke an illustration to them, saying: “The land of a certain rich man produced well.

[[v42-12-17]]

^<<v42-12-17,17>>^ Consequently he began reasoning within himself, saying, ‘What shall I do, now that I have nowhere to gather my crops?’

[[v42-12-18]]

^<<v42-12-18,18>>^ So he said, ‘I will do this: I will tear down my storehouses and build bigger ones, and there I will gather all my grain and all my good things;

[[v42-12-19]]

^<<v42-12-19,19>>^ and I will say to my soul: “Soul, you have many good things laid up for many years; take your ease, eat, drink, enjoy yourself.”’

[[v42-12-20]]

^<<v42-12-20,20>>^ But God said to him, ‘Unreasonable one, this night they are demanding your soul^&#42;1^ from you. Who, then, is to have the things you stored up?’

[NOTE]
====
. Or, “life.” Gr., psy·khenʹ; J17,​18,​22(Heb.), naph·shekhaʹ (from neʹphesh).
====

[[v42-12-21]]

^<<v42-12-21,21>>^ So it goes with the man that lays up treasure for himself but is not rich toward God.”

[[v42-12-22]]

^<<v42-12-22,22>>^ Then he said to his disciples: “On this account I say to YOU, Quit being anxious about YOUR souls as to what YOU will eat or about YOUR bodies as to what YOU will wear.

[[v42-12-23]]

^<<v42-12-23,23>>^ For the soul is worth more than food and the body than clothing.

[[v42-12-24]]

^<<v42-12-24,24>>^ Mark well that the ravens neither sow seed nor reap, and they have neither barn nor storehouse, and yet God feeds them. Of how much more worth are YOU than birds?

[[v42-12-25]]

^<<v42-12-25,25>>^ Who of YOU by being anxious can add a cubit to his life span?

[[v42-12-26]]

^<<v42-12-26,26>>^ If, therefore, YOU cannot do the least thing, why be anxious about the remaining things?

[[v42-12-27]]

^<<v42-12-27,27>>^ Mark well how the lilies grow; they neither toil nor spin; but I tell YOU, Not even Solʹo·mon in all his glory was arrayed as one of these.

[[v42-12-28]]

^<<v42-12-28,28>>^ If, now, God thus clothes the vegetation in the field that today exists and tomorrow is cast into an oven, how much rather will he clothe YOU, YOU with little faith!

[[v42-12-29]]

^<<v42-12-29,29>>^ So quit seeking what YOU might eat and what YOU might drink, and quit being in anxious suspense;

[[v42-12-30]]

^<<v42-12-30,30>>^ for all these are the things the nations of the world are eagerly pursuing, but YOUR Father knows YOU need these things.

[[v42-12-31]]

^<<v42-12-31,31>>^ Nevertheless, seek continually his kingdom, and these things will be added to YOU.

[[v42-12-32]]

^<<v42-12-32,32>>^ “Have no fear, little flock, because YOUR Father has approved of giving YOU the kingdom.

[[v42-12-33]]

^<<v42-12-33,33>>^ Sell the things belonging to YOU and give gifts of mercy. Make purses for yourselves that do not wear out, a never-failing treasure in the heavens, where a thief does not get near nor moth consumes.

[[v42-12-34]]

^<<v42-12-34,34>>^ For where YOUR treasure is, there YOUR hearts will be also.

[[v42-12-35]]

^<<v42-12-35,35>>^ “Let YOUR loins be girded and YOUR lamps be burning,

[[v42-12-36]]

^<<v42-12-36,36>>^ and YOU yourselves be like men waiting for their master when he returns^&#42;1^ from the marriage,^&#42;2^ so that at his arriving and knocking they may at once open to him.

[NOTE]
====
. Or, “breaks away; departs.” See App 5D.
. Or, “wedding feast.”
====

[[v42-12-37]]

^<<v42-12-37,37>>^ Happy are those slaves whom the master on arriving finds watching! Truly I say to YOU, He will gird himself and make them recline at the table and will come alongside and minister to them.

[[v42-12-38]]

^<<v42-12-38,38>>^ And if he arrives in the second watch,^&#42;1^ even if in the third,^&#42;2^ and finds them thus, happy are they!

[NOTE]
====
. From about 9 p.m. until midnight. See Mr 13:35 ftns.
. From midnight until about 3 a.m.
====

[[v42-12-39]]

^<<v42-12-39,39>>^ But know this, that if the householder had known at what hour the thief would come, he would have kept watching and not have let his house be broken into.

[[v42-12-40]]

^<<v42-12-40,40>>^ YOU also, keep ready, because at an hour that YOU do not think likely the Son of man is coming.”

[[v42-12-41]]

^<<v42-12-41,41>>^ Then Peter said: “Lord,^&#42;1^ are you saying this illustration to us or also to all?”

[NOTE]
====
. Or, “Master.”
====

[[v42-12-42]]

^<<v42-12-42,42>>^ And the Lord said: “Who really is the faithful steward,^&#42;1^ the discreet one, whom his master will appoint over his body of attendants to keep giving them their measure of food supplies at the proper time?

[NOTE]
====
. Or, “house manager.” Gr., oi·ko·noʹmos; Lat., di·spen·saʹtor; J17(Heb.), has·so·khenʹ, “the steward.” See Ge 24:2 ftn; Eph 1:10 ftn, “Administration.”
====

[[v42-12-43]]

^<<v42-12-43,43>>^ Happy is that slave, if his master on arriving finds him doing so!

[[v42-12-44]]

^<<v42-12-44,44>>^ I tell YOU truthfully, He will appoint him over all his belongings.

[[v42-12-45]]

^<<v42-12-45,45>>^ But if ever that slave should say in his heart, ‘My master delays coming,’ and should start to beat the menservants and the maidservants, and to eat and drink and get drunk,

[[v42-12-46]]

^<<v42-12-46,46>>^ the master of that slave will come on a day that he is not expecting &#91;him&#93; and in an hour that he does not know, and he will punish him with the greatest severity^&#42;1^ and assign him a part with the unfaithful ones.

[NOTE]
====
. Or, “will cut him in two.”
====

[[v42-12-47]]

^<<v42-12-47,47>>^ Then that slave that understood the will of his master but did not get ready or do in line with his will will be beaten with many strokes.

[[v42-12-48]]

^<<v42-12-48,48>>^ But the one that did not understand and so did things deserving of strokes will be beaten with few. Indeed, everyone to whom much was given, much will be demanded of him; and the one whom people put in charge of much, they will demand more than usual of him.

[[v42-12-49]]

^<<v42-12-49,49>>^ “I came to start a fire on the earth, and what more is there for me to wish if it has already been lighted?

[[v42-12-50]]

^<<v42-12-50,50>>^ Indeed, I have a baptism with which to be baptized, and how I am being distressed until it is finished!

[[v42-12-51]]

^<<v42-12-51,51>>^ Do YOU imagine I came to give peace on the earth? No, indeed, I tell YOU, but rather division.

[[v42-12-52]]

^<<v42-12-52,52>>^ For from now on there will be five in one house divided, three against two and two against three.

[[v42-12-53]]

^<<v42-12-53,53>>^ They will be divided, father against son and son against father, mother against daughter and daughter against &#91;her&#93; mother, mother-in-law against &#91;her&#93; daughter-in-law and daughter-in-law against &#91;her&#93; mother-in-law.”

[[v42-12-54]]

^<<v42-12-54,54>>^ Then he went on to say also to the crowds: “When YOU see a cloud rising in western parts, at once YOU say, ‘A storm is coming,’ and it turns out so.

[[v42-12-55]]

^<<v42-12-55,55>>^ And when YOU see that a south wind is blowing, YOU say, ‘There will be a heat wave,’ and it occurs.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hypocrites, YOU know how to examine the outward appearance of earth and sky, but how is it YOU do not know how to examine this particular time?

[[v42-12-57]]

^<<v42-12-57,57>>^ Why do YOU not judge also for yourselves what is righteous?

[[v42-12-58]]

^<<v42-12-58,58>>^ For example, when you are going with your adversary at law to a ruler, get to work, while on the way, to rid yourself of the dispute with him, that he may never hale you before the judge, and the judge deliver you to the court officer, and the court officer throw you into prison.

[[v42-12-59]]

^<<v42-12-59,59>>^ I tell you, You will certainly not get out from there until you pay over the last small coin of very little value.”^&#42;1^

[NOTE]
====
. Lit., “the last lepton.” See App 8A.
====

'''

xref:042-luke/042-luke-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-luke/042-luke-013.adoc#v42-13-0[Próximo Capítulo &#62;]